Elin Decompiled Documentation: ButtonGrid Class Reference
ButtonGrid Class Reference
Public Types
enum Mode {
Default , Grid , Ingredient , Recipe ,
RecipeGrid , Search
}
Public Member Functions
override string ToString ()
T Attach< T > (string id, bool rightAttach=true)
Transform Attach (string id, bool rightAttach=true)
void Dettach (string id)
void Reset ()
void SetBodySlot (BodySlot b, InvOwner owner, bool showIndex=false)
void Redraw ()
void SetCardGrid (Card c, InvOwner owner=null)
void SetCard (Card c, Mode mode=Mode.Default, Action< UINote > onWriteNote=null)
void SetArea (Area a)
void SetItem (GridItem i)
void SetObject (object o)
void SetDummy ()
virtual void SetDragParent (IDragParent p)
void SetIngredient (Recipe r, Recipe.Ingredient _ing)
void SetIngredient (Recipe r, Thing t)
void SetRecipeVariation (UIRecipeInfo.RecipeVariation a)
void SetRecipe ()
void SetRecipe (Area a)
void SetRecipe (Recipe r)
void RefreshCraftable ()
void SetCraftRecipe (Recipe r, Mode mode, bool tooltip=false)
void WriteReqMat (UINote n, Recipe r)
bool ShowMouseHintLeft ()
string GetTextMouseHintLeft ()
bool ShowMouseHintRight ()
string GetTextMouseHintRight ()
RenderRow GetRenderRow ()
void OnRefreshPref ()
override bool CanMiddleClick ()
override void OnMiddleClick (bool forceClick)
Public Member Functions inherited from UIButton
virtual bool CanMiddleClick ()
virtual void OnMiddleClick (bool forceClick)
void SetItem (Item i)
virtual void RefreshItem ()
virtual void OnHover ()
void Toggle ()
void ToggleCheck ()
void SetCheck (bool check)
void SetToggle (bool isOn, Action< bool > onToggle=null)
void SetToggleWithScore (bool isOn, Action< bool > onToggle, int? score)
void SetTooltip (Action< UITooltip > onShowTooltip=null, bool enable=true)
void SetTooltip (string id, Action< UITooltip > onShowTooltip=null, bool enable=true)
void SetTooltipLang (string lang=null)
virtual void ShowTooltip ()
void ShowTooltipForced (bool ignoreWhenRightClick=true)
override void OnPointerDown (PointerEventData eventData)
override void OnPointerClick (PointerEventData eventData)
override void OnPointerUp (PointerEventData eventData)
void OnPointerUpOnDrag (PointerEventData eventData)
void _OnPress ()
void OnPress ()
void AddHighlight (Func< bool > killCondition)
void DoHighlightTransition (bool instant=false)
void DoNormalTransition (bool instant=true)
override Selectable FindSelectableOnDown ()
override Selectable FindSelectableOnUp ()
override Selectable FindSelectableOnLeft ()
override Selectable FindSelectableOnRight ()
void SetNavigation (UIButton up, UIButton down=null, UIButton left=null, UIButton right=null)
override bool IsActive ()
void SetInteractableWithAlpha (bool enable)
virtual void ApplySkin ()
void ApplySkin ()
bool ShowMouseHintLeft ()
string GetTextMouseHintLeft ()
bool ShowMouseHintRight ()
string GetTextMouseHintRight ()
RenderRow GetRenderRow ()
void OnRefreshPref ()
Public Attributes
Area area
Recipe recipe
Recipe.Ingredient ing
Card card
int index
InvOwner invOwner
bool keepBg
List< Transform > listAttach = new List<Transform>()
Public Attributes inherited from UIButton
UIText mainText
UIText subText
UIText subText2
UIText keyText
Image icon
Image imageCheck
Graphic[] targetGraphics
float scaleIcon = 1f
float slideX
float navigationFix
bool isChecked
bool instantClick = true
UISelectableGroup group
TooltipData tooltip
SoundData soundClick
SoundData soundHighlight
Transform animeTarget
Anime animeClick
Anime animeHold
ButtonType buttonType
BaseSkinRoot skinRoot
Action onDoubleClick
Action onRightClick
Action< int > onInputWheel
object refObj
int refInt
string refStr
bool animating
bool selected
Vector3 originalIconScale = Vector3.one
UIButton highlightTarget
Item item
Protected Member Functions
override void OnDestroy ()
Protected Member Functions inherited from UIButton
override void Awake ()
override void OnEnable ()
override void DoStateTransition (SelectionState state, bool instant)
Properties
ColorProfile Colors [get]
Card Card [get]
virtual float extFixY [get]
Properties inherited from UIButton
List< Graphic > Graphics [get]
virtual bool CanDragLeftButton [get]
Private Attributes
int rightAttachCount
Additional Inherited Members
Static Public Member Functions inherited from UIButton
static void UpdateButtons ()
static void TryHihlight ()
static void TryShowTip (Transform root=null, bool highlight=true, bool ignoreWhenRightClick=true)
static void TryShowTip< T > (Transform root=null, bool highlight=true, bool ignoreWhenRightClick=true)
Static Public Attributes inherited from UIButton
static bool DoSlide
static bool locked
static UIButton lastButton
static UIButton lastHovered
static UIButton currentHighlight
static UIButton currentPressedButton
static float lastClicked
static float doubleClickTime = 0.4f
static Vector2 buttonPos
static Action onPressed
static List< UIButton > buttons = new List<UIButton>()
static Action actionTooltip
Detailed Description
Definition at line 6 of file ButtonGrid.cs.
Member Enumeration Documentation
Mode
enum ButtonGrid.Mode
Enumerator
Default
Grid
Ingredient
Recipe
RecipeGrid
Search
Definition at line 8 of file ButtonGrid.cs.
    {
        Default,
        Grid,
        Ingredient,
        Recipe,
        RecipeGrid,
        Search
    }
Member Function Documentation
Attach()
Transform ButtonGrid.Attach (string id, bool rightAttach = true) inline
Definition at line 63 of file ButtonGrid.cs.
    {
        Transform transform = PoolManager.Spawn<Transform>("attach_" + id, "UI/Element/Grid/Attach/" + id, base.transform);
        listAttach.Add(transform);
        if (rightAttach)
        {
            RectTransform rectTransform = transform.Rect();
            rectTransform.anchoredPosition = new Vector2(rectTransform.anchoredPosition.x, -8 - 8 * rightAttachCount);
            transform.tag = "RightAttach";
            rightAttachCount++;
        }
        transform.name = id;
        return transform;
    }
References listAttach, rightAttachCount, and PoolManager.Spawn().
Referenced by Attach< T >(), TraitCanvas.OnSetCardGrid(), TraitContainer.OnSetCardGrid(), TraitEquipItem.OnSetCardGrid(), TraitFigure.OnSetCardGrid(), DragItemCard.OnStartDrag(), LayerCraft.RefreshCategory(), and LayerCraftFloat.RefreshCraft().
Attach< T >()
T ButtonGrid.Attach< T > (string id, bool rightAttach = true) inline
Type Constraints
T : Component
Definition at line 58 of file ButtonGrid.cs.
                                                                   : Component
    {
        return Attach(id, rightAttach).GetComponent<T>();
    }
References Attach().
CanMiddleClick()
override bool ButtonGrid.CanMiddleClick () inline virtual
Reimplemented from UIButton.
Definition at line 746 of file ButtonGrid.cs.
    {
        if (invOwner != null && card != null)
        {
            return EClass.ui.AllowInventoryInteractions;
        }
        return false;
    }
References card, and EClass.ui.
Dettach()
void ButtonGrid.Dettach (string id) inline
Definition at line 78 of file ButtonGrid.cs.
    {
        listAttach.ForeachReverse(delegate(Transform t)
        {
            if (t.name == id)
            {
                if (t.tag.Contains("RightAttach"))
                {
                    rightAttachCount--;
                }
                listAttach.Remove(t);
                PoolManager.Despawn(t);
            }
        });
    }
References PoolManager.Despawn(), and listAttach.
Referenced by DragItemCard.OnEndDrag(), and LayerCraft.RefreshCategory().
GetRenderRow()
RenderRow ButtonGrid.GetRenderRow () inline
Implements IPrefImage.
Definition at line 713 of file ButtonGrid.cs.
    {
        if (refObj is RenderRow)
        {
            return (RenderRow)refObj;
        }
        if (recipe == null)
        {
            if (card == null)
            {
                return null;
            }
            return card.sourceCard;
        }
        return recipe.renderRow;
    }
References card.
GetTextMouseHintLeft()
string ButtonGrid.GetTextMouseHintLeft () inline
Implements IMouseHint.
Definition at line 682 of file ButtonGrid.cs.
    {
        if (!invOwner.CanShiftClick(this))
        {
            if (!invOwner.CanCtrlClick(this))
            {
                if (!invOwner.CanAltClick(this))
                {
                    return "";
                }
                return invOwner.GetTextAltClick(this);
            }
            return invOwner.GetTextCtrlClick(this);
        }
        return invOwner.GetTextShiftClick(this);
    }
GetTextMouseHintRight()
string ButtonGrid.GetTextMouseHintRight () inline
Implements IMouseHint.
Definition at line 708 of file ButtonGrid.cs.
    {
        return invOwner.GetAutoUseLang(this) ?? "";
    }
OnDestroy()
override void ButtonGrid.OnDestroy () inline protected
Definition at line 112 of file ButtonGrid.cs.
    {
        if (listAttach.Count > 0)
        {
            Reset();
        }
        rightAttachCount = 0;
    }
References Reset.
OnMiddleClick()
override void ButtonGrid.OnMiddleClick (bool forceClick) inline virtual
Reimplemented from UIButton.
Definition at line 755 of file ButtonGrid.cs.
    {
        Thing t = card.Thing;
        InvOwner o = invOwner;
        if ((forceClick || EInput.middleMouse.clicked) && o.AllowContext)
        {
            o.ShowContextMenu(this);
        }
        EInput.middleMouse.pressedLongAction = delegate
        {
            if (EClass.ui.AllowInventoryInteractions && EClass.core.config.game.holdMiddleButtonToHold && o.TryHold(t))
            {
                if (!(t.trait is TraitAbility) && t.trait.IsTool)
                {
                    HotItemHeld.disableTool = true;
                }
                if (EClass.ui.contextMenu.isActive)
                {
                    EClass.ui.contextMenu.currentMenu.Hide();
                }
                EInput.Consume();
            }
        };
    }
References InvOwner.AllowContext, card, ButtonState.clicked, Core.config, EInput.Consume(), EClass.core, CoreConfig.game, CoreConfig.GameConfig.holdMiddleButtonToHold, Trait.IsTool, EInput.middleMouse, InvOwner.ShowContextMenu(), Card.trait, InvOwner.TryHold(), and EClass.ui.
OnRefreshPref()
void ButtonGrid.OnRefreshPref () inline
Implements IPrefImage.
Definition at line 730 of file ButtonGrid.cs.
    {
        if (refObj is RenderRow renderRow)
        {
            renderRow.SetImage(icon, null, 0, setNativeSize: false);
        }
        if (recipe != null)
        {
            SetRecipe(recipe);
        }
        else if (card != null)
        {
            SetCard(card);
        }
    }
References card.
Redraw()
void ButtonGrid.Redraw () inline
Definition at line 140 of file ButtonGrid.cs.
    {
        SetCardGrid(card, invOwner);
    }
References card.
Referenced by LayerDragGrid.Redraw().
RefreshCraftable()
void ButtonGrid.RefreshCraftable () inline
Definition at line 576 of file ButtonGrid.cs.
    {
        ThingStack thingStack = EClass.pc.things.GetThingStack(recipe.GetIdThing(), recipe.GetRefVal());
        bool flag = recipe.IsCraftable();
        string text = recipe.Name;
        if (recipe.Mold != null && recipe.Mold.trait.CraftNum > 1)
        {
            text = text + " x " + recipe.Mold.trait.CraftNum;
        }
        mainText.SetText(text, flag ? FontColor.Good : FontColor.Bad);
        subText.text = thingStack.count.ToString() ?? "";
        recipe.SetTextDifficulty(subText2);
    }
References ThingStack.count, ThingContainer.GetThingStack(), EClass.pc, and Card.things.
Reset()
void ButtonGrid.Reset () inline
Definition at line 94 of file ButtonGrid.cs.
    {
        base.image.color = Color.white;
        if (listAttach.Count > 0)
        {
            foreach (Transform item in listAttach)
            {
                PoolManager.Despawn(item);
            }
            listAttach.Clear();
        }
        if ((bool)icon)
        {
            icon.enabled = true;
        }
        rightAttachCount = 0;
    }
References Color, PoolManager.Despawn(), and item.
SetArea()
void ButtonGrid.SetArea (Area a) inline
Definition at line 390 of file ButtonGrid.cs.
    {
        Reset();
        icon.sprite = SpriteSheet.Get("icon_area");
        icon.SetNativeSize();
        mainText.SetActive(enable: false);
    }
References SpriteSheet.Get(), and Reset.
SetBodySlot()
void ButtonGrid.SetBodySlot (BodySlot b, InvOwner owner, bool showIndex = false) inline
Definition at line 121 of file ButtonGrid.cs.
    {
        SetCardGrid(b.thing, owner);
        imageCheck.sprite = SpriteSheet.Get("Media/Graphics/Icon/Element/", "eq_" + b.element.alias);
        imageCheck.SetNativeSize();
        imageCheck.SetAlpha((b.thing == null) ? 1f : 0.4f);
        if ((bool)subText)
        {
            if (showIndex)
            {
                owner.owner.Chara.body.SetBodyIndexText(b, subText);
            }
            else
            {
                subText.SetActive(enable: false);
            }
        }
    }
References Chara.body, Card.Chara, BodySlot.element, SpriteSheet.Get(), InvOwner.owner, CharaBody.SetBodyIndexText(), and BodySlot.thing.
Referenced by LayerEquip.RefreshEquipment(), and WidgetEquip.RefreshEquipment().
SetCard()
void ButtonGrid.SetCard (Card c, Mode mode = Mode::Default, Action< UINote > onWriteNote = null) inline
Definition at line 184 of file ButtonGrid.cs.
    {
        Reset();
        CoreRef.ButtonAssets refs = EClass.core.refs.buttonAssets;
        card = c;
        bool showNew = invOwner?.ShowNew ?? false;
        if (c == null || c.isDestroyed)
        {
            if (mode != Mode.Ingredient)
            {
                RefreshBG();
                icon.sprite = EClass.core.refs.icons.trans;
                mainText.text = "";
                if ((bool)subText)
                {
                    subText.text = "";
                }
            }
            else
            {
                icon.sprite = Core.Instance.refs.spriteNoIng;
            }
            icon.SetNativeSize();
            if (invOwner == null || !invOwner.AlwaysShowTooltip || onWriteNote == null)
            {
                SetTooltip(null, enable: false);
                return;
            }
            SetTooltip("note", delegate(UITooltip t)
            {
                onWriteNote(t.note);
            });
            return;
        }
        SetTooltip("note", delegate(UITooltip t)
        {
            if (c.isNew)
            {
                c.isNew = false;
                RefreshBG();
            }
            c.WriteNote(t.note, onWriteNote);
            if (ing != null)
            {
                t.note.Space();
                t.note.AddText("mark_ing".lang() + (ing.optional ? "opIngredient" : "reqIng").lang(ing.GetName()));
            }
        });
        c.SetImage(icon);
        if (c == EClass.pc.held && c.invY != 1)
        {
            Attach("held");
        }
        if (c.trait is TraitAbility && (c.trait as TraitAbility).CanUse(EClass.pc))
        {
            Attach<Image>("target_self").sprite = (c.trait as TraitAbility).act.TargetType.IconType;
        }
        if (EClass.core.config.test.showRefIcon && c.IsIdentified)
        {
            SourceElement.Row refElement = c.trait.GetRefElement();
            if (refElement != null)
            {
                if ((bool)refElement.GetSprite())
                {
                    Image image = Attach<Image>("reficon", rightAttach: false);
                    refElement.SetImage(image);
                }
            }
            else
            {
                Sprite refSprite = c.trait.GetRefSprite();
                if ((bool)refSprite)
                {
                    Image obj = Attach<Image>("reficon", rightAttach: false);
                    obj.sprite = refSprite;
                    obj.color = Color.white;
                }
            }
        }
        if (c.tier > 0)
        {
            Attach<Image>("quality", rightAttach: false).sprite = EClass.core.refs.icons.quality[Mathf.Clamp(c.tier - 1, 0, EClass.core.refs.icons.quality.Count - 1)];
        }
        if (c.c_equippedSlot != 0 && invOwner != null && invOwner.owner.isChara && !invOwner.owner.IsPC)
        {
            Attach("equip", rightAttach: false);
        }
        if (c.isNPCProperty || c.isGifted)
        {
            Attach("npcProperty");
        }
        if (mode != Mode.Search)
        {
            c.trait.OnSetCardGrid(this);
        }
        switch (mode)
        {
        case Mode.Grid:
        case Mode.Search:
            RefreshBG();
            if (c.IsContainer && c.c_indexContainerIcon != 0)
            {
                Attach("icon_container", rightAttach: false).GetComponent<Image>().sprite = EClass.core.refs.spritesContainerIcon[c.c_indexContainerIcon];
            }
            if (c.IsIdentified)
            {
                BlessedState blessedState2 = c.blessedState;
                if (blessedState2 != 0)
                {
                    Attach("status_" + blessedState2);
                }
            }
            else
            {
                Attach("status_unidentified");
            }
            if (c.IsDecayed)
            {
                Attach("rotten");
            }
            else if (c.IsRotting)
            {
                Attach("rotting");
            }
            c.trait.SetMainText(mainText, hotitem: false);
            if (mode == Mode.Search)
            {
                Card rootCard = c.GetRootCard();
                if (rootCard != EClass.pc)
                {
                    Attach((rootCard == c) ? "searched" : "searched_container", rightAttach: false);
                }
            }
            break;
        case Mode.Default:
        {
            Color c2 = Colors.Skin.textUnidentified;
            if (c.IsIdentified)
            {
                c2 = c.blessedState switch
                {
                    BlessedState.Blessed => Colors.Skin.textBlessed,
                    BlessedState.Doomed => Colors.Skin.textDoomed,
                    BlessedState.Cursed => Colors.Skin.textCursed,
                    _ => Colors.Skin.textIdentified,
                };
            }
            mainText.SetText(c.Name, c2);
            if ((bool)subText)
            {
                subText.SetText(Lang._weight(c.ChildrenAndSelfWeight));
            }
            break;
        }
        case Mode.Ingredient:
            if (c.IsIdentified)
            {
                BlessedState blessedState = c.blessedState;
                if (blessedState != 0)
                {
                    Attach("status_" + blessedState);
                }
            }
            else
            {
                Attach("status_unidentified");
            }
            if (c.IsDecayed)
            {
                Attach("rotten");
            }
            else if (c.IsRotting)
            {
                Attach("rotting");
            }
            break;
        }
        if (c.c_isImportant)
        {
            Attach("important");
        }
        void RefreshBG()
        {
            if (!keepBg)
            {
                if (c == null)
                {
                    base.image.sprite = refs.bgDefault;
                }
                else
                {
                    Sprite sprite = refs.bgDefault;
                    if (c.rarity >= Rarity.Superior && c.IsIdentified && c.IsEquipmentOrRangedOrAmmo)
                    {
                        sprite = ((c.rarity >= Rarity.Artifact) ? refs.bgArtifact : ((c.rarity >= Rarity.Mythical) ? refs.bgMythical : ((c.rarity < Rarity.Legendary) ? refs.bgSuperior : refs.bgLegendary)));
                    }
                    else if (showNew && c.isNew && c.invY != 1)
                    {
                        sprite = refs.bgNew;
                    }
                    base.image.sprite = sprite;
                }
            }
        }
    }
References Lang._weight(), UINote.AddText(), CoreRef.ButtonAssets.bgArtifact, CoreRef.ButtonAssets.bgDefault, CoreRef.ButtonAssets.bgLegendary, CoreRef.ButtonAssets.bgNew, CoreRef.ButtonAssets.bgSuperior, Card.blessedState, CoreRef.buttonAssets, Card.c_equippedSlot, Card.c_indexContainerIcon, Card.c_isImportant, TraitCatalyst.CanUse(), card, Card.ChildrenAndSelfWeight, Color, Core.config, EClass.core, Trait.GetRefElement(), Trait.GetRefSprite(), Card.GetRootCard(), SourceElement.Row.GetSprite(), Chara.held, CoreRef.icons, if(), Core.Instance, Card.invY, Card.IsContainer, Card.IsDecayed, Card.isDestroyed, Card.IsEquipmentOrRangedOrAmmo, Card.isGifted, Card.IsIdentified, Card.isNew, Card.isNPCProperty, Card.IsRotting, Card.Name, UITooltip.note, Trait.OnSetCardGrid(), EClass.pc, CoreRef.Icons.quality, Card.rarity, Core.refs, Reset, SourceElement.Row.SetImage(), Card.SetImage(), Trait.SetMainText(), CoreConfig.Test.showRefIcon, UINote.Space(), CoreRef.spriteNoIng, CoreRef.spritesContainerIcon, CoreConfig.test, Card.tier, Card.trait, CoreRef.Icons.trans, and Card.WriteNote().
Referenced by InvOwnerDraglet.OnClick(), UIDragGridIngredients.Refresh(), LayerGacha.RefreshCoin(), LayerCraftFloat.RefreshDisassemble(), UIInventory.RefreshList(), WidgetSearch.RefreshList(), LayerCraft.RefreshProduct(), and LayerResource.ShowThings().
SetCardGrid()
void ButtonGrid.SetCardGrid (Card c, InvOwner owner = null) inline
Definition at line 145 of file ButtonGrid.cs.
    {
        if (owner != null)
        {
            invOwner = owner;
        }
        if (c != null && !c.isDestroyed)
        {
            base.interactable = true;
        }
        SetCard(c, Mode.Grid, delegate(UINote n)
        {
            invOwner?.OnWriteNote(this, n);
        });
        onRightClick = delegate
        {
            if (EClass.ui.AllowInventoryInteractions && invOwner != null)
            {
                InvOwner.clickTimer = 0f;
                invOwner.OnRightClick(this);
                UIButton.onPressed = delegate
                {
                    invOwner.OnRightPressed(this);
                };
                EInput.Consume();
                UIButton.TryShowTip();
            }
        };
        this.SetOnClick(delegate
        {
            if (EClass.ui.AllowInventoryInteractions)
            {
                invOwner?.OnClick(this);
                EInput.Consume();
                UIButton.TryShowTip();
            }
        });
    }
References EInput.Consume(), Card.isDestroyed, UIButton.TryShowTip(), and EClass.ui.
Referenced by InvOwner.Transaction.Process(), WidgetCurrentTool.RebuildSlots(), UIInventory.RefreshGrid(), LayerDragGrid.SetInv(), and LayerDragGrid.Validate().
SetCraftRecipe()
void ButtonGrid.SetCraftRecipe (Recipe r, Mode mode, bool tooltip = false) inline
Definition at line 590 of file ButtonGrid.cs.
    {
        Reset();
        recipe = r;
        if (mode == Mode.Recipe)
        {
            RefreshCraftable();
        }
        else
        {
            mainText.SetActive(enable: false);
        }
        RecipeCard rCard = r as RecipeCard;
        if (rCard != null)
        {
            r.SetImage(icon);
        }
        else
        {
            r.SetImage(icon);
        }
        if (!tooltip)
        {
            return;
        }
        SetTooltip("note", delegate(UITooltip t)
        {
            if (r.ingredients.Count == 0)
            {
                r.BuildIngredientList();
            }
            EClass.player.recipes.hoveredRecipes.Add(r.id);
            Dettach("recipe_new");
            if (rCard != null)
            {
                if (mode == Mode.RecipeGrid && rCard._mold == null)
                {
                    CardBlueprint.SetNormalRarity();
                    rCard._mold = ThingGen.Create(r.id);
                }
                rCard.Mold.WriteNote(t.note, delegate(UINote n)
                {
                    n.Space();
                    WriteReqMat(n, r);
                }, IInspect.NoteMode.Product, r);
            }
            else
            {
                UINote note = t.note;
                note.Clear();
                note.AddHeaderCard(r.GetName(), icon.sprite);
                if (!r.GetDetail().IsEmpty())
                {
                    note.AddText(r.GetDetail());
                }
                WriteReqMat(note, r);
                t.note.Build();
            }
        });
    }
References RecipeCard._mold, UINote.AddHeaderCard(), UINote.AddText(), UINote.Build(), UINote.Clear(), Recipe.GetDetail(), Recipe.GetName(), RecipeManager.hoveredRecipes, Recipe.id, Recipe.ingredients, RecipeCard.Mold, UITooltip.note, EClass.player, Player.recipes, Reset, Recipe.SetImage(), UINote.Space(), and Card.WriteNote().
Referenced by LayerCraft.RefreshCategory(), LayerCraftFloat.RefreshCraft(), and WidgetCodex.RefreshList().
SetDragParent()
virtual void ButtonGrid.SetDragParent (IDragParent p) inline virtual
Reimplemented in ButtonGridDrag.
Definition at line 431 of file ButtonGrid.cs.
    {
    }
SetDummy()
void ButtonGrid.SetDummy () inline
Definition at line 417 of file ButtonGrid.cs.
    {
        Reset();
        icon.enabled = false;
        mainText.SetActive(enable: false);
        base.onClick.RemoveAllListeners();
        base.onClick.AddListener(delegate
        {
            SE.BeepSmall();
        });
        tooltip.enable = false;
        base.image.color = new Color(1f, 1f, 1f, 0.3f);
    }
References Color, and Reset.
Referenced by GridItem.SetButton().
SetIngredient() [1/2]
void ButtonGrid.SetIngredient (Recipe r, Recipe::Ingredient _ing) inline
Definition at line 435 of file ButtonGrid.cs.
    {
        if (_ing.id.IsEmpty())
        {
            SetDummy();
            return;
        }
        mainText.SetActive(enable: true);
        base.image.color = Color.white;
        ing = _ing;
        if (ing.thing != null && (ing.thing.isDestroyed || ing.thing.Num == 0))
        {
            ing.thing = null;
        }
        Thing thing = ing.thing;
        SetCard(thing, Mode.Ingredient);
        if (r != null && r.source.colorIng != 0 && r.ingredients != null && r.ingredients.Count > 0 && r.ingredients.IndexOf(_ing) == r.source.colorIng)
        {
            Attach("ing_color", rightAttach: false);
        }
        if (ing.optional)
        {
            UIButton componentInChildren = Attach("ing_option", rightAttach: false).GetComponentInChildren<UIButton>(includeInactive: true);
            componentInChildren.SetActive(ing.thing != null);
            componentInChildren.SetOnClick(delegate
            {
                SE.Trash();
                ing.thing = null;
                SetIngredient(r, _ing);
                r.SaveLastIngredients();
                r.OnChangeIngredient();
                if ((bool)LayerCraft.Instance)
                {
                    LayerCraft.Instance.OnChangeIngredient();
                }
            });
        }
        HitSummary summary = Core.Instance.screen.tileSelector.summary;
        int num = thing?.Num ?? 0;
        int num2 = summary.countValid;
        if (num2 == 0)
        {
            num2 = 1;
        }
        num2 *= ing.req;
        if (ing.optional && num == 0)
        {
            num2 = 0;
        }
        bool flag = num < num2 && !ing.optional;
        string text = num.ToShortNumber().TagColor(Colors.colorIngPredict) + (" -" + num2).TagColor(flag ? Colors.colorIngCost : Colors.colorIngReq);
        mainText.text = text;
        if (thing == null)
        {
            SetTooltip("note", delegate(UITooltip tt)
            {
                tt.note.Clear();
                tt.note.Space(16);
                tt.note.AddText("mark_ing".lang() + (ing.optional ? "opIngredient" : "noIngredient").lang(_ing.GetName()), ing.optional ? FontColor.Good : FontColor.Bad);
                tt.note.Build();
            });
            EClass.sources.cards.map[ing.IdThing].SetImage(icon);
            icon.SetAlpha(0.5f);
        }
        else if (thing.GetRootCard() != EClass.pc)
        {
            Attach("pcInv", rightAttach: false);
        }
    }
References UINote.AddText(), UINote.Build(), SourceManager.cards, UINote.Clear(), Color, RecipeSource.colorIng, HitSummary.countValid, Card.GetRootCard(), Recipe.ingredients, Core.Instance, LayerCraft.Instance, SourceCard.map, UITooltip.note, Card.Num, LayerCraft.OnChangeIngredient(), Recipe.OnChangeIngredient(), EClass.pc, Recipe.SaveLastIngredients(), Core.screen, Recipe.source, EClass.sources, UINote.Space(), BaseTileSelector.summary, and BaseGameScreen.tileSelector.
Referenced by DropdownGrid.Activate(), and DropdownGrid.BuildIngredients().
SetIngredient() [2/2]
void ButtonGrid.SetIngredient (Recipe r, Thing t) inline
Definition at line 505 of file ButtonGrid.cs.
    {
        SetCard(t, Mode.Ingredient);
        int num = t.Num;
        mainText.text = num.ToShortNumber();
        mainText.SetActive(enable: true);
        ing = null;
        if (t.GetRootCard() != EClass.pc)
        {
            Attach("pcInv", rightAttach: false);
        }
    }
References Card.GetRootCard(), Card.Num, and EClass.pc.
SetItem()
void ButtonGrid.SetItem (GridItem i) inline
Definition at line 398 of file ButtonGrid.cs.
    {
        Reset();
        mainText.SetActive(enable: true);
        i.SetButton(this);
    }
References Reset, and GridItem.SetButton().
Referenced by Dialog.OnAfterInit(), WidgetHotbar.RebuildPage(), and WidgetHotbar.SetItem().
SetObject()
void ButtonGrid.SetObject (object o) inline
Definition at line 405 of file ButtonGrid.cs.
    {
        if (o is Area)
        {
            SetArea(o as Area);
        }
        else if (o is Card)
        {
            SetCard(o as Card);
        }
    }
Referenced by LayerInteraction.Show().
SetRecipe() [1/3]
void ButtonGrid.SetRecipe () inline
Definition at line 533 of file ButtonGrid.cs.
    {
        SetRecipe(recipe);
    }
Referenced by AM_Build.OnFinishProcessTiles(), BuildMenu.RefreshCategory(), and BuildMenu.RefreshCategoryArea().
SetRecipe() [2/3]
void ButtonGrid.SetRecipe (Area a) inline
Definition at line 538 of file ButtonGrid.cs.
    {
        Reset();
        area = a;
        icon.sprite = Core.Instance.refs.spriteArea;
        icon.SetNativeSize();
        mainText.SetActive(enable: false);
    }
References Core.Instance, Core.refs, Reset, and CoreRef.spriteArea.
SetRecipe() [3/3]
void ButtonGrid.SetRecipe (Recipe r) inline
Definition at line 547 of file ButtonGrid.cs.
    {
        Reset();
        recipe = r;
        if (r.UseStock)
        {
            recipe.ingredients[0].RefreshThing();
            Thing thing = recipe.ingredients[0].thing;
            mainText.SetText(thing.Num.ToShortNumber(), SkinManager.CurrentColors.buttonGrid);
            if (r.VirtualBlock)
            {
                r.renderRow.SetImage(icon, null, r.GetDefaultColor(), setNativeSize: true, 0, thing.trait.IdSkin);
            }
            else
            {
                thing.SetImage(icon);
            }
        }
        else
        {
            r.renderRow.SetImage(icon, null, r.GetDefaultColor(), setNativeSize: true, 0, r.idSkin);
        }
        mainText.SetActive(r.UseStock);
        if (r.UseStock && r.ingredients[0].thing?.GetRootCard() != EClass.pc)
        {
            Attach("pcInv", rightAttach: false);
        }
    }
References SkinColorProfile.buttonGrid, SkinManager.CurrentColors, Recipe.GetDefaultColor(), Recipe.idSkin, Trait.IdSkin, Recipe.ingredients, Card.Num, EClass.pc, Recipe.renderRow, Reset, Card.SetImage(), RenderRow.SetImage(), Card.trait, Recipe.UseStock, and Recipe.VirtualBlock.
SetRecipeVariation()
void ButtonGrid.SetRecipeVariation (UIRecipeInfo::RecipeVariation a) inline
Definition at line 518 of file ButtonGrid.cs.
    {
        Reset();
        Recipe recipe = a.recipe;
        if (recipe.UseStock && !recipe.VirtualBlock && recipe.ingredients[0].thing != null)
        {
            recipe.ingredients[0].thing.SetImage(icon, a.dir, recipe.ingredients[0].thing.trait.IdSkin);
        }
        else
        {
            recipe.renderRow.SetImage(icon, null, recipe.renderRow.GetColorInt(recipe.GetColorMaterial()), setNativeSize: true, (recipe.renderRow is SourceChara.Row) ? recipe.idSkin : a.dir, (recipe.renderRow is SourceChara.Row) ? a.dir : recipe.idSkin);
        }
        mainText.SetActive(enable: false);
    }
References RenderRow.GetColorInt(), Recipe.GetColorMaterial(), Recipe.idSkin, Recipe.ingredients, Recipe.renderRow, Reset, RenderRow.SetImage(), Recipe.UseStock, and Recipe.VirtualBlock.
Referenced by UIRecipeInfo.Refresh().
ShowMouseHintLeft()
bool ButtonGrid.ShowMouseHintLeft () inline
Implements IMouseHint.
Definition at line 669 of file ButtonGrid.cs.
    {
        if (invOwner != null && card != null)
        {
            if (!invOwner.CanShiftClick(this) && !invOwner.CanCtrlClick(this))
            {
                return invOwner.CanAltClick(this);
            }
            return true;
        }
        return false;
    }
References card.
ShowMouseHintRight()
bool ButtonGrid.ShowMouseHintRight () inline
Implements IMouseHint.
Definition at line 699 of file ButtonGrid.cs.
    {
        if (invOwner != null && card != null)
        {
            return invOwner.AllowAutouse;
        }
        return false;
    }
References card.
ToString()
override string ButtonGrid.ToString () inline
Definition at line 53 of file ButtonGrid.cs.
    {
        return card?.ToString();
    }
References card, and Card.ToString().
WriteReqMat()
void ButtonGrid.WriteReqMat (UINote n, Recipe r) inline
Definition at line 651 of file ButtonGrid.cs.
    {
        r.WriteReqFactory(n);
        r.WriteReqSkill(n);
        n.AddHeaderTopic("reqMat");
        foreach (Recipe.Ingredient ingredient in r.ingredients)
        {
            int count = EClass._map.Stocked.ListThingStack(ingredient, StockSearchMode.AroundPC).count;
            Color c = ((count >= ingredient.req) ? SkinManager.CurrentColors.textGood : SkinManager.CurrentColors.textBad);
            string text = "<color=" + c.ToHex() + ">" + ingredient.GetName() + " x " + ingredient.req + "  (" + count + ")</color>";
            if (ingredient.optional)
            {
                text = "opIngredient".lang(text);
            }
            n.AddText(text).text1.SetSize(-1);
        }
    }
References EClass._map, UINote.AddHeaderTopic(), UINote.AddText(), Color, ThingStack.count, SkinManager.CurrentColors, Recipe.ingredients, Props.ListThingStack(), UIText.SetSize(), Map.Stocked, UIItem.text1, SkinColorProfile.textBad, SkinColorProfile.textGood, Recipe.WriteReqFactory(), and Recipe.WriteReqSkill().
Member Data Documentation
area
Area ButtonGrid.area
Definition at line 18 of file ButtonGrid.cs.
Referenced by BuildMenu.Refresh().
card
Card ButtonGrid.card
Definition at line 24 of file ButtonGrid.cs.
Referenced by InvOwner.AutoUse(), InvOwner.CanAltClick(), InvOwner.CanCtrlClick(), InvOwner.CanShiftClick(), DragItemCard.DragInfo.DragInfo(), InvOwner.GetAutoUseLang(), InvOwnerAlly.GetAutoUseLang(), InvOwner.GetShitDestOwner(), InvOwner.ListInteractions(), InvOwner.OnAltClick(), InvOwner.OnClick(), InvOwnerDraglet.OnClick(), WidgetCurrentTool.OnClickButtonHotItem(), InvOwner.OnCtrlClick(), InvOwner.OnRightClick(), InvOwner.OnRightPressed(), InvOwner.OnShiftClick(), InvOwner.OnWriteNote(), InvOwnerEquip.OnWriteNote(), InvOwnerAlly.Process(), ButtonHotItem.Refresh(), Player.RefreshCurrentHotItem(), WidgetCurrentTool.RefreshHighlight(), Card.RemoveThing(), WidgetCurrentTool.Select(), LayerAbility.SetDirty(), Thing.ShowSplitMenu(), Thing.ShowSplitMenu2(), ToString(), UIDragGridIngredients.Update(), ActionMode.UpdateInput(), and LayerDragGrid.Validate().
index
int ButtonGrid.index
Definition at line 26 of file ButtonGrid.cs.
Referenced by DragItemCard.DragInfo.DragInfo(), InvOwner.Transaction.IsValid(), InvOwnerDraglet.OnClick(), LayerAbility.SetDirty(), and ActionMode.UpdateInput().
ing
Recipe.Ingredient ButtonGrid.ing
Definition at line 22 of file ButtonGrid.cs.
Referenced by DropdownGrid.TrySelect().
invOwner
InvOwner ButtonGrid.invOwner
Definition at line 28 of file ButtonGrid.cs.
Referenced by InvOwner.CanShiftClick(), DragItemCard.DragInfo.DragInfo(), InvOwner.GetShitDestOwner(), InvOwner.OnClick(), DragItemCard.OnDrag(), ELayer.OnRightClick(), InvOwner.Transaction.Process(), Thing.ShowSplitMenu(), InvOwner.Transaction.Transaction(), and ActionMode.UpdateInput().
keepBg
bool ButtonGrid.keepBg
Definition at line 30 of file ButtonGrid.cs.
listAttach
List<Transform> ButtonGrid.listAttach = new List<Transform>()
Definition at line 33 of file ButtonGrid.cs.
Referenced by Attach(), and Dettach().
recipe
Recipe ButtonGrid.recipe
Definition at line 20 of file ButtonGrid.cs.
Referenced by BuildMenu.Refresh(), BuildMenu.Select(), and LayerCraftFloat.Update().
rightAttachCount
int ButtonGrid.rightAttachCount private
Definition at line 35 of file ButtonGrid.cs.
Referenced by Attach().
Property Documentation
Card
Card ButtonGrid.Card get
Definition at line 39 of file ButtonGrid.cs.
    {
        get
        {
            if (card == null || card.isDestroyed)
            {
                return null;
            }
            return card;
        }
    }
Colors
ColorProfile ButtonGrid.Colors get
Definition at line 37 of file ButtonGrid.cs.
extFixY
virtual float ButtonGrid.extFixY get
Definition at line 51 of file ButtonGrid.cs.
The documentation for this class was generated from the following file:
Elin/ButtonGrid.cs