Elin Decompiled Documentation: SourceFood Class Reference
SourceFood Class Reference
Classes
class Row2
Public Member Functions
override Row CreateRow ()
override Row CreateRowByMapping (IReadOnlyDictionary< string, int > mapping)
override void SetRow (Row r)
override IReadOnlyDictionary< string, int > GetRowMapping ()
override IReadOnlyDictionary< string, string > GetTypeMapping ()
override void Reset ()
override void OnImportRow (Row _r, SourceThing.Row c)
Public Member Functions inherited from SourceThingV
override Row CreateRow ()
override Row CreateRowByMapping (IReadOnlyDictionary< string, int > mapping)
override void SetRow (Row r)
override IReadOnlyDictionary< string, int > GetRowMapping ()
override IReadOnlyDictionary< string, string > GetTypeMapping ()
override void RestorePref ()
override void ValidatePref ()
override void Reset ()
override void OnAfterImportData ()
virtual void OnImportRow (Row _r, SourceThing.Row c)
Public Member Functions inherited from SourceDataString< SourceThingV.Row >
override T GetRow (string id)
Static Public Attributes
static new readonly IReadOnlyDictionary< string, int > RowMapping
static new readonly IReadOnlyDictionary< string, string > TypeMapping
Static Public Attributes inherited from SourceThingV
static readonly IReadOnlyDictionary< string, int > RowMapping
static readonly IReadOnlyDictionary< string, string > TypeMapping
Additional Inherited Members
Properties inherited from SourceThingV
override string[] ImportFields [get]
Detailed Description
Definition at line 4 of file SourceFood.cs.
Member Function Documentation
CreateRow()
override Row SourceFood.CreateRow () inline
Definition at line 152 of file SourceFood.cs.
    {
        return new Row2
        {
            id = SourceData.GetString(0),
            _origin = SourceData.GetString(1),
            name_JP = SourceData.GetString(2),
            unit_JP = SourceData.GetString(3),
            name = SourceData.GetString(4),
            unit = SourceData.GetString(5),
            name2_JP = SourceData.GetStringArray(6),
            name2 = SourceData.GetStringArray(7),
            unknown_JP = SourceData.GetString(8),
            unknown = SourceData.GetString(9),
            tiles = SourceData.GetIntArray(10),
            parse = SourceData.GetStringArray(11),
            vals = SourceData.GetStringArray(12),
            trait = SourceData.GetStringArray(13),
            elements = Core.ParseElements(SourceData.GetStr(14)),
            idTaste = SourceData.GetString(16),
            TST = SourceData.GetInt(17),
            NUT = SourceData.GetInt(18),
            STR = SourceData.GetInt(19),
            STR2 = SourceData.GetInt(20),
            END = SourceData.GetInt(21),
            END2 = SourceData.GetInt(22),
            DEX = SourceData.GetInt(23),
            DEX2 = SourceData.GetInt(24),
            PER = SourceData.GetInt(25),
            PER2 = SourceData.GetInt(26),
            LER = SourceData.GetInt(27),
            LER2 = SourceData.GetInt(28),
            WIL = SourceData.GetInt(29),
            WIL2 = SourceData.GetInt(30),
            MAG = SourceData.GetInt(31),
            MAG2 = SourceData.GetInt(32),
            CHA = SourceData.GetInt(33),
            CHA2 = SourceData.GetInt(34),
            LV = SourceData.GetInt(36),
            chance = SourceData.GetInt(37),
            value = SourceData.GetInt(38),
            weight = SourceData.GetInt(39),
            recipeKey = SourceData.GetStringArray(40),
            factory = SourceData.GetStringArray(41),
            components = SourceData.GetStringArray(42),
            defMat = SourceData.GetString(43),
            category = SourceData.GetString(44),
            tag = SourceData.GetStringArray(45),
            detail_JP = SourceData.GetString(46),
            detail = SourceData.GetString(47)
        };
    }
References SourceData< T, T2 >.GetInt(), SourceData< T, T2 >.GetIntArray(), SourceData< T, T2 >.GetStr(), SourceData< T, T2 >.GetString(), SourceData< T, T2 >.GetStringArray(), and Core.ParseElements().
CreateRowByMapping()
override Row SourceFood.CreateRowByMapping (IReadOnlyDictionary< string, int > mapping) inline
Definition at line 205 of file SourceFood.cs.
    {
        return new Row2
        {
            id = SourceData.GetString(mapping["id"]),
            _origin = SourceData.GetString(mapping["_origin"]),
            name_JP = SourceData.GetString(mapping["name_JP"]),
            unit_JP = SourceData.GetString(mapping["unit_JP"]),
            name = SourceData.GetString(mapping["name"]),
            unit = SourceData.GetString(mapping["unit"]),
            name2_JP = SourceData.GetStringArray(mapping["name2_JP"]),
            name2 = SourceData.GetStringArray(mapping["name2"]),
            unknown_JP = SourceData.GetString(mapping["unknown_JP"]),
            unknown = SourceData.GetString(mapping["unknown"]),
            tiles = SourceData.GetIntArray(mapping["tiles"]),
            parse = SourceData.GetStringArray(mapping["parse"]),
            vals = SourceData.GetStringArray(mapping["vals"]),
            trait = SourceData.GetStringArray(mapping["trait"]),
            elements = Core.ParseElements(SourceData.GetStr(mapping["elements"])),
            idTaste = SourceData.GetString(mapping["idTaste"]),
            TST = SourceData.GetInt(mapping["TST"]),
            NUT = SourceData.GetInt(mapping["NUT"]),
            STR = SourceData.GetInt(mapping["STR"]),
            STR2 = SourceData.GetInt(mapping["STR2"]),
            END = SourceData.GetInt(mapping["END"]),
            END2 = SourceData.GetInt(mapping["END2"]),
            DEX = SourceData.GetInt(mapping["DEX"]),
            DEX2 = SourceData.GetInt(mapping["DEX2"]),
            PER = SourceData.GetInt(mapping["PER"]),
            PER2 = SourceData.GetInt(mapping["PER2"]),
            LER = SourceData.GetInt(mapping["LER"]),
            LER2 = SourceData.GetInt(mapping["LER2"]),
            WIL = SourceData.GetInt(mapping["WIL"]),
            WIL2 = SourceData.GetInt(mapping["WIL2"]),
            MAG = SourceData.GetInt(mapping["MAG"]),
            MAG2 = SourceData.GetInt(mapping["MAG2"]),
            CHA = SourceData.GetInt(mapping["CHA"]),
            CHA2 = SourceData.GetInt(mapping["CHA2"]),
            LV = SourceData.GetInt(mapping["LV"]),
            chance = SourceData.GetInt(mapping["chance"]),
            value = SourceData.GetInt(mapping["value"]),
            weight = SourceData.GetInt(mapping["weight"]),
            recipeKey = SourceData.GetStringArray(mapping["recipeKey"]),
            factory = SourceData.GetStringArray(mapping["factory"]),
            components = SourceData.GetStringArray(mapping["components"]),
            defMat = SourceData.GetString(mapping["defMat"]),
            category = SourceData.GetString(mapping["category"]),
            tag = SourceData.GetStringArray(mapping["tag"]),
            detail_JP = SourceData.GetString(mapping["detail_JP"]),
            detail = SourceData.GetString(mapping["detail"])
        };
    }
References SourceData< T, T2 >.GetInt(), SourceData< T, T2 >.GetIntArray(), SourceData< T, T2 >.GetStr(), SourceData< T, T2 >.GetString(), SourceData< T, T2 >.GetStringArray(), and Core.ParseElements().
GetRowMapping()
override IReadOnlyDictionary< string, int > SourceFood.GetRowMapping () inline
Definition at line 263 of file SourceFood.cs.
    {
        return RowMapping;
    }
References RowMapping.
GetTypeMapping()
override IReadOnlyDictionary< string, string > SourceFood.GetTypeMapping () inline
Definition at line 268 of file SourceFood.cs.
    {
        return TypeMapping;
    }
References TypeMapping.
OnImportRow()
override void SourceFood.OnImportRow (Row _r, SourceThing::Row c) inline virtual
Reimplemented from SourceThingV.
Definition at line 279 of file SourceFood.cs.
    {
        List<int> list = new List<int>(c.elements);
        Row2 row = _r as Row2;
        Add(10, row.NUT);
        Parse(row.STR, 70, row.STR2, 440);
        Parse(row.END, 71, row.END2, 441);
        Parse(row.DEX, 72, row.DEX2, 442);
        Parse(row.PER, 73, row.PER2, 443);
        Parse(row.LER, 74, row.LER2, 444);
        Parse(row.WIL, 75, row.WIL2, 445);
        Parse(row.MAG, 76, row.MAG2, 446);
        Parse(row.CHA, 77, row.CHA2, 447);
        for (int i = 0; i < row.elements.Length; i += 2)
        {
            Add(_r.elements[i], row.elements[i + 1]);
        }
        c.elements = list.ToArray();
        c.name2 = row.name2;
        c.name2_JP = row.name2_JP;
        c.unknown = row.unknown;
        c.unknown_JP = row.unknown_JP;
        if (!row.unit_JP.IsEmpty())
        {
            c.unit_JP = row.unit_JP;
        }
        void Add(int ele, int a)
        {
            list.Add(ele);
            list.Add(a);
        }
        void Parse(int raw, int ele, int raw2, int ele2)
        {
            if (raw != 0)
            {
                Add(ele, raw);
            }
            if (raw2 != 0)
            {
                Add(ele2, raw2);
            }
        }
    }
References SourceFood.Row2.CHA, SourceFood.Row2.CHA2, SourceFood.Row2.DEX, SourceFood.Row2.DEX2, CardRow.elements, SourceFood.Row2.END, SourceFood.Row2.END2, SourceFood.Row2.LER, SourceFood.Row2.LER2, SourceFood.Row2.MAG, SourceFood.Row2.MAG2, CardRow.name2, CardRow.name2_JP, SourceFood.Row2.NUT, SourceFood.Row2.PER, SourceFood.Row2.PER2, SourceFood.Row2.STR, SourceFood.Row2.STR2, SourceThing.Row.unit_JP, SourceThing.Row.unknown, SourceThing.Row.unknown_JP, SourceFood.Row2.WIL, and SourceFood.Row2.WIL2.
Reset()
override void SourceFood.Reset () inline
Definition at line 273 of file SourceFood.cs.
    {
        base.Reset();
        EClass.sources.things.Reset();
    }
References EClass.sources, and SourceManager.things.
SetRow()
override void SourceFood.SetRow (Row r) inline
Definition at line 258 of file SourceFood.cs.
    {
        map[r.id] = r;
    }
References CardRow.id.
Member Data Documentation
RowMapping
new readonly IReadOnlyDictionary<string, int> SourceFood.RowMapping static
Definition at line 52 of file SourceFood.cs.
Referenced by GetRowMapping().
TypeMapping
new readonly IReadOnlyDictionary<string, string> SourceFood.TypeMapping static
Definition at line 102 of file SourceFood.cs.
Referenced by GetTypeMapping().
The documentation for this class was generated from the following file:
Elin/SourceFood.cs