Elin Decompiled Documentation: DropdownRecipe Class Reference
DropdownRecipe Class Reference
Public Member Functions
void RefreshLabel ()
string GetLabel (Thing t, bool showColor)
Public Attributes
Recipe recipe
UIText textLabel
UIText orgLabel
Recipe.Ingredient ingredient
Static Public Attributes
static Color colorCost
static Color colorPredict
Detailed Description
Definition at line 4 of file DropdownRecipe.cs.
Member Function Documentation
GetLabel()
string DropdownRecipe.GetLabel (Thing t, bool showColor) inline
Definition at line 11 of file DropdownRecipe.cs.
    {
        if (t == null)
        {
            return string.Concat(new string[]
            {
                " <color=",
                DropdownRecipe.colorCost.ToHex(),
                ">",
                "noMaterial".lang(),
                "</color>"
            });
        }
        HitSummary summary = Core.Instance.screen.tileSelector.summary;
        int num = t.Num;
        return string.Concat(new string[]
        {
            showColor ? ("<color=" + t.material.matColor.ToHex() + ">■</color> ") : "",
            t.NameSimple,
            " (",
            num.ToString(),
            ")"
        }) + ((summary.countValid == 0) ? "" : string.Concat(new string[]
        {
            " <color=",
            DropdownRecipe.colorCost.ToHex(),
            "> -",
            (this.ingredient.req * summary.countValid).ToString(),
            "</color>"
        }));
    }
References colorCost, HitSummary.countValid, ingredient, Card.material, Card.NameSimple, Card.Num, EClass.screen, BaseTileSelector.summary, and BaseGameScreen.tileSelector.
Referenced by RefreshLabel().
RefreshLabel()
void DropdownRecipe.RefreshLabel () inline
Definition at line 6 of file DropdownRecipe.cs.
    {
        this.textLabel.SetText(this.GetLabel(this.ingredient.thing, this.recipe.source.colorIng == this.recipe.ingredients.IndexOf(this.ingredient)));
    }
References RecipeSource.colorIng, GetLabel(), ingredient, Recipe.source, and textLabel.
Referenced by UIRecipeInfo.RefreshBalance().
Member Data Documentation
colorCost
Color DropdownRecipe.colorCost static
Definition at line 43 of file DropdownRecipe.cs.
Referenced by GetLabel().
colorPredict
Color DropdownRecipe.colorPredict static
Definition at line 45 of file DropdownRecipe.cs.
ingredient
Recipe.Ingredient DropdownRecipe.ingredient
Definition at line 53 of file DropdownRecipe.cs.
Referenced by GetLabel(), and RefreshLabel().
orgLabel
UIText DropdownRecipe.orgLabel
Definition at line 51 of file DropdownRecipe.cs.
Referenced by UIRecipeInfo.RefreshList().
recipe
Recipe DropdownRecipe.recipe
Definition at line 47 of file DropdownRecipe.cs.
textLabel
UIText DropdownRecipe.textLabel
Definition at line 49 of file DropdownRecipe.cs.
Referenced by RefreshLabel().
The documentation for this class was generated from the following file:
Elin/DropdownRecipe.cs