Elin Decompiled Documentation: BaseSkinRoot Class Reference
BaseSkinRoot Class Reference
Public Member Functions
virtual SkinColorProfile GetColors (SkinType type)
virtual void ApplySkin (UIImage t)
virtual void ApplySkin (UIRawImage t)
virtual void ApplySkin (UIText t, FontSource f)
virtual SkinAsset_Button GetButton ()
Properties
string Name [get]
virtual SkinColorProfile Colors [get]
virtual SkinColorProfileEx ColorsEx [get]
Detailed Description
Definition at line 3 of file BaseSkinRoot.cs.
Member Function Documentation
ApplySkin() [1/3]
virtual void BaseSkinRoot.ApplySkin (UIImage t) inline virtual
Reimplemented in SkinRoot, and SkinRootStatic.
Definition at line 16 of file BaseSkinRoot.cs.
    {
    }
Referenced by UIImage.ApplySkin(), UIRawImage.ApplySkin(), and UIText.ApplySkin().
ApplySkin() [2/3]
virtual void BaseSkinRoot.ApplySkin (UIRawImage t) inline virtual
Reimplemented in SkinRoot.
Definition at line 20 of file BaseSkinRoot.cs.
    {
    }
ApplySkin() [3/3]
virtual void BaseSkinRoot.ApplySkin (UIText t, FontSource f) inline virtual
Reimplemented in SkinRoot.
Definition at line 24 of file BaseSkinRoot.cs.
    {
    }
GetButton()
virtual SkinAsset_Button BaseSkinRoot.GetButton () inline virtual
Reimplemented in SkinRoot.
Definition at line 28 of file BaseSkinRoot.cs.
    {
        return null;
    }
Referenced by UIText.ApplySkin(), NotificationCondition.OnRefresh(), and NotificationStats.OnRefresh().
GetColors()
virtual SkinColorProfile BaseSkinRoot.GetColors (SkinType type) inline virtual
Reimplemented in SkinRoot, and SkinRootStatic.
Definition at line 11 of file BaseSkinRoot.cs.
    {
        return null;
    }
Referenced by UIText.ApplySkin().
Property Documentation
Colors
virtual SkinColorProfile BaseSkinRoot.Colors get
Definition at line 7 of file BaseSkinRoot.cs.
Referenced by UIImage.ApplySkin(), and UIRawImage.ApplySkin().
ColorsEx
virtual SkinColorProfileEx BaseSkinRoot.ColorsEx get
Definition at line 9 of file BaseSkinRoot.cs.
Name
string BaseSkinRoot.Name get
Definition at line 5 of file BaseSkinRoot.cs.
Referenced by ContentConfigTest.OnInstantiate().
The documentation for this class was generated from the following file:
Elin/Plugins.UI/BaseSkinRoot.cs