Elin Decompiled Documentation: ExcelDataList Class Reference
ExcelDataList Class Reference
Public Member Functions
void Reload ()
virtual void Initialize ()
virtual void OnInitialize ()
Dictionary< string, string > GetRow (string id)
Public Attributes
List< ExcelData > items = new List<ExcelData>(0)
Dictionary< string, Dictionary< string, string > > all = new Dictionary<string, Dictionary<string, string>>()
List< Dictionary< string, string > > list = new List<Dictionary<string, string>>()
Protected Attributes
bool initialized
Properties
virtual int StartIndex [get]
Detailed Description
Definition at line 4 of file ExcelDataList.cs.
Member Function Documentation
GetRow()
Dictionary< string, string > ExcelDataList.GetRow (string id) inline
Definition at line 49 of file ExcelDataList.cs.
    {
        if (!initialized)
        {
            Initialize();
        }
        return all.TryGetValue(id) ?? list[0];
    }
References all, Initialize(), initialized, and list.
Initialize()
virtual void ExcelDataList.Initialize () inline virtual
Definition at line 23 of file ExcelDataList.cs.
    {
        if (initialized)
        {
            return;
        }
        foreach (ExcelData item in items)
        {
            item.startIndex = StartIndex;
            List<Dictionary<string, string>> obj = item.BuildList();
            string directoryName = new FileInfo(item.path).DirectoryName;
            foreach (Dictionary<string, string> item2 in obj)
            {
                item2["path"] = directoryName;
                all[item2["id"]] = item2;
                list.Add(item2);
            }
        }
        OnInitialize();
        initialized = true;
    }
References all, initialized, item, items, list, OnInitialize(), and StartIndex.
Referenced by Card.ApplyTone(), ToneDataList.ApplyTone(), GetRow(), TalkDataList.GetTalk(), ToneDataList.GetToneID(), Card.SetRandomTalk(), and Card.SetRandomTone().
OnInitialize()
virtual void ExcelDataList.OnInitialize () inline virtual
Reimplemented in TalkDataList, and ToneDataList.
Definition at line 45 of file ExcelDataList.cs.
    {
    }
Referenced by Initialize().
Reload()
void ExcelDataList.Reload () inline
Definition at line 16 of file ExcelDataList.cs.
    {
        all.Clear();
        list.Clear();
        initialized = false;
    }
References all, initialized, and list.
Member Data Documentation
all
Dictionary<string, Dictionary<string, string> > ExcelDataList.all = new Dictionary<string, Dictionary<string, string>>()
Definition at line 8 of file ExcelDataList.cs.
Referenced by Card.ApplyTone(), ToneDataList.ApplyTone(), GetRow(), TalkDataList.GetTalk(), ToneDataList.GetToneID(), Initialize(), and Reload().
initialized
bool ExcelDataList.initialized protected
Definition at line 12 of file ExcelDataList.cs.
Referenced by ToneDataList.ApplyTone(), GetRow(), TalkDataList.GetTalk(), ToneDataList.GetToneID(), Initialize(), and Reload().
items
List<ExcelData> ExcelDataList.items = new List<ExcelData>(0)
Definition at line 6 of file ExcelDataList.cs.
Referenced by Initialize(), BaseModManager.InitLang(), and BaseModPackage.Parse().
list
List<Dictionary<string, string> > ExcelDataList.list = new List<Dictionary<string, string>>()
Definition at line 10 of file ExcelDataList.cs.
Referenced by Card.ApplyTone(), GetRow(), Initialize(), TalkDataList.OnInitialize(), Reload(), Card.SetRandomTalk(), and Card.SetRandomTone().
Property Documentation
StartIndex
virtual int ExcelDataList.StartIndex get
Definition at line 14 of file ExcelDataList.cs.
Referenced by Initialize().
The documentation for this class was generated from the following file:
Elin/Plugins.basecore/ExcelDataList.cs