Elin Decompiled Documentation: TraitSeed Class Reference
TraitSeed Class Reference
Public Member Functions
override void OnCreate (int lv)
override void SetName (ref string s)
override void WriteNote (UINote n, bool identified)
void TrySprout (bool force=false, bool sucker=false, VirtualDate date=null)
Public Member Functions inherited from Trait
string GetParam (int i, string def=null)
int GetParamInt (int i, int def)
virtual bool Contains (RecipeSource r)
virtual int GetValue ()
virtual bool CanStackTo (Thing to)
virtual string GetHoverText ()
virtual Action GetHealAction (Chara c)
virtual bool CanBlend (Thing t)
virtual void OnBlend (Thing t, Chara c)
virtual int GetActDuration (Chara c)
virtual SourceElement.Row GetRefElement ()
virtual Sprite GetRefSprite ()
virtual void OnRenderExtra (RenderParam p)
virtual Emo2 GetHeldEmo (Chara c)
virtual void SetOwner (Card _owner)
virtual bool IdleUse (Chara c, int dist)
virtual void OnSetOwner ()
virtual void OnImportMap ()
virtual void SetParams (params string[] s)
virtual void OnCrafted (Recipe recipe, List< Thing > ings)
virtual void OnCreate (int lv)
virtual void OnEquip (Chara c, bool onSetOwner)
virtual void OnUnequip (Chara c)
virtual void OnChangePlaceState (PlaceState state)
virtual void OnAddedToZone ()
virtual void OnRemovedFromZone ()
virtual void OnSimulateHour (VirtualDate date)
virtual string GetName ()
virtual void SetName (ref string s)
virtual void OnRenderTile (Point point, HitResult result, int dir)
virtual int CompareTo (Card b)
virtual bool CanBuiltAt (Point p)
virtual void Update ()
Point GetPoint ()
Point GetRandomPoint (Func< Point, bool > func=null, Chara accessChara=null)
virtual List< Point > ListPoints (Point center=null, bool onlyPassable=true)
virtual Recipe GetRecipe ()
virtual Recipe GetBuildModeRecipe ()
virtual bool CanCook (Card c)
void CookProgress ()
virtual bool CanOffer (Card tg)
void OfferProcess (Chara cc)
void Offer (Chara cc)
virtual bool TryProgress (AIProgress p)
virtual LockOpenState TryOpenLock (Chara cc, bool msgFail=true)
virtual void WriteNote (UINote n, bool identified)
int GetSortVal (UIList.SortMode m)
virtual HotItem GetHotItem ()
virtual bool CanRead (Chara c)
virtual void OnRead (Chara c)
virtual bool CanEat (Chara c)
virtual void OnEat (Chara c)
virtual bool CanDrink (Chara c)
virtual void OnDrink (Chara c)
virtual void OnThrowGround (Chara c, Point p)
virtual bool CanUse (Chara c)
virtual bool CanUse (Chara c, Card tg)
virtual bool CanUse (Chara c, Point p)
virtual bool OnUse (Chara c)
virtual bool OnUse (Chara c, Card tg)
virtual bool OnUse (Chara c, Point p)
virtual void TrySetAct (ActPlan p)
virtual void TrySetHeldAct (ActPlan p)
virtual void OnHeld ()
virtual void OnTickHeld ()
virtual void OnSetCurrentItem ()
virtual void OnUnsetCurrentItem ()
virtual bool OnChildDecay (Card c, bool firstDecay)
virtual bool CanChildDecay (Card c)
virtual void OnSetCardGrid (ButtonGrid b)
virtual void OnStepped (Chara c)
virtual void OnSteppedOut (Chara c)
virtual void OnOpenDoor (Chara c)
void Install (bool byPlayer)
void Uninstall ()
virtual void OnInstall (bool byPlayer)
virtual void OnUninstall ()
virtual void TryToggle ()
virtual void Toggle (bool on, bool silent=false)
virtual void PlayToggleEffect (bool silent)
virtual void OnToggle ()
virtual void TrySetToggleAct (ActPlan p)
bool IsFuelEnough (int num=1, List< Thing > excludes=null, bool tryRefuel=true)
bool IsFuel (string s)
bool IsFuel (Thing t)
int GetFuelValue (Thing t)
int GetFuelValue (string id)
void Refuel (Thing t)
void TryRefuel (int dest, List< Thing > excludes)
virtual void OnEnterScreen ()
virtual void RefreshRenderer ()
virtual void SetMainText (UIText t, bool hotitem)
virtual bool CanCopy (Thing t)
string GetTextRestock (string lang, bool pet)
Emo2 GetRestockedIcon ()
void OnBarter ()
Thing CreateStock ()
Static Public Member Functions
static Thing MakeSeed (SourceObj.Row obj, PlantData plant=null)
static void LevelSeed (Thing t, SourceObj.Row obj, int num)
static Thing MakeSeed (string idSource)
static Thing ApplySeed (Thing t, int refval)
static Thing MakeSeed (SourceObj.Row obj)
static Thing MakeRandomSeed (bool enc=false)
static SourceObj.Row GetRandomSeedObj ()
Static Public Member Functions inherited from EClass
static int rndSeed (int a, int seed)
static int rnd (long a)
static int rnd (int a)
static int curve (int a, int start, int step, int rate=75)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Static Public Attributes
static List< SourceObj.Row > listSeeds
Static Public Attributes inherited from Trait
static TraitSelfFactory SelfFactory = new TraitSelfFactory()
Static Public Attributes inherited from EClass
static Core core
Properties
SourceObj.Row row [get]
override int InstallBottomPriority [get]
override bool CanExtendBuild [get]
override bool CanChangeHeight [get]
override bool CanName [get]
override int DefaultStock [get]
Properties inherited from Trait
string[] Params [get]
virtual byte WeightMod [get]
virtual int IdSkin [get]
virtual string Name [get]
virtual TileType tileType [get]
virtual RefCardName RefCardName [get]
virtual bool IsBlockPath [get]
virtual bool IsBlockSight [get]
virtual bool IsDoor [get]
virtual bool IsOpenSight [get]
virtual bool IsOpenPath [get]
virtual bool IsFloating [get]
virtual bool IsNoShop [get]
virtual bool IsGround [get]
virtual bool IsOnlyUsableByPc [get]
virtual bool InvertHeldSprite [get]
virtual bool IsChangeFloorHeight [get]
virtual bool ShouldRefreshTile [get]
virtual bool ShouldTryRefreshRoom [get]
virtual int InstallBottomPriority [get]
virtual bool CanHarvest [get]
virtual int radius [get]
virtual TraitRadiusType radiusType [get]
virtual bool CanUseRoomRadius [get]
virtual int GuidePriotiy [get]
virtual int Electricity [get]
virtual bool IgnoreLastStackHeight [get]
virtual int Decay [get]
virtual int DecaySpeed [get]
virtual int DecaySpeedChild [get]
virtual bool IsFridge [get]
virtual int DefaultStock [get]
virtual bool HoldAsDefaultInteraction [get]
virtual int CraftNum [get]
virtual bool ShowOrbit [get]
virtual bool HaveUpdate [get]
virtual bool IsSpot [get]
virtual bool IsFactory [get]
virtual bool CanAutofire [get]
virtual bool CanName [get]
virtual bool CanPutAway [get]
virtual bool CanChangeHeight [get]
virtual bool CanStack [get]
virtual bool CanCopyInBlueprint [get]
virtual bool CanBeAttacked [get]
virtual bool CanBeTeleported [get]
virtual bool CanExtendBuild [get]
virtual string langNote [get]
virtual string IDInvStyle [get]
virtual string IDActorEx [get]
virtual bool MaskOnBuild [get]
virtual bool ShowContextOnPick [get]
virtual bool IsThrowMainAction [get]
virtual bool LevelAsQuality [get]
virtual bool UseDummyTile [get]
virtual bool RequireFullStackCheck [get]
virtual bool DisableAutoCombat [get]
virtual InvGridSize InvGridSize [get]
virtual bool IsContainer [get]
virtual bool CanUseContent [get]
virtual bool CanSearchContent [get]
virtual bool CanOpenContainer [get]
virtual bool IsSpecialContainer [get]
virtual ContainerType ContainerType [get]
virtual ThrowType ThrowType [get]
virtual EffectDead EffectDead [get]
virtual bool IsHomeItem [get]
virtual bool IsAltar [get]
virtual bool IsRestSpot [get]
virtual bool CanBeMasked [get]
virtual bool IsLocalAct [get]
virtual bool IsBlendBase [get]
virtual bool CanBeOnlyBuiltInHome [get]
virtual bool CanBuildInTown [get]
virtual bool CanBeHeld [get]
virtual bool CanBeStolen [get]
virtual bool CanOnlyCarry [get]
virtual bool CanBeDestroyed [get]
virtual bool CanBeSmashedToDeath [get]
virtual bool CanBeHallucinated [get]
virtual bool CanBeDropped [get]
virtual string ReqHarvest [get]
virtual bool CanBeDisassembled [get]
virtual bool CanBeShipped [get]
virtual bool HasCharges [get]
virtual bool ShowCharges [get]
virtual bool ShowChildrenNumber [get]
virtual bool ShowAsTool [get]
virtual bool CanBeHeldAsFurniture [get]
virtual bool HideInAdv [get]
virtual bool NoHeldDir [get]
virtual bool AlwaysHideOnLowWall [get]
bool ExistsOnMap [get]
virtual bool RenderExtra [get]
virtual float DropChance [get]
virtual string IdNoRestock [get]
virtual int IdleUseChance [get]
virtual string RecipeCat [get]
virtual bool IsTool [get]
virtual string LangUse [get]
virtual bool IgnoreOnSteppedWhenMoving [get]
virtual bool IsOn [get]
virtual bool IsAnimeOn [get]
bool IsToggle [get]
virtual bool AutoToggle [get]
bool IsLighting [get]
virtual bool IsLightOn [get]
virtual bool IsNightOnlyLight [get]
virtual TileMode tileMode [get]
virtual bool UseAltTiles [get]
virtual bool UseLowblock [get]
virtual bool UseExtra [get]
virtual bool UseLightColor [get]
virtual ? Color ColorExtra [get]
virtual int MaxFuel [get]
virtual int FuelCost [get]
virtual bool ShowFuelWindow [get]
bool IsRequireFuel [get]
string IdToggleExtra [get]
virtual ToggleType ToggleType [get]
virtual string IdSoundToggleOn [get]
virtual string IdSoundToggleOff [get]
virtual int ShopLv [get]
virtual CopyShopType CopyShop [get]
virtual int NumCopyItem [get]
virtual ShopType ShopType [get]
virtual CurrencyType CurrencyType [get]
virtual PriceType PriceType [get]
virtual bool AllowSell [get]
virtual int CostRerollShop [get]
virtual bool AllowCriminal [get]
virtual int RestockDay [get]
virtual SlaverType SlaverType [get]
virtual string LangBarter [get]
string TextNextRestock [get]
string TextNextRestockPet [get]
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Additional Inherited Members
Public Types inherited from Trait
enum TileMode {
Default , Door , Illumination , DefaultNoAnime ,
SignalAnime , FakeBlock
}
enum CopyShopType { None , Item , Spellbook }
Public Attributes inherited from Trait
Card owner
Static Protected Attributes inherited from Trait
static List< Point > listRadiusPoints = new List<Point>()
Detailed Description
Definition at line 5 of file TraitSeed.cs.
Member Function Documentation
ApplySeed()
static Thing TraitSeed.ApplySeed (Thing t, int refval) inline static
Definition at line 169 of file TraitSeed.cs.
    {
        t.refVal = refval;
        SourceObj.Row row = EClass.sources.objs.map.TryGetValue(refval);
        if (row != null && row.vals.Length != 0)
        {
            t.idSkin = row.vals[0].ToInt();
        }
        return t;
    }
References SourceManager.objs, row, and EClass.sources.
Referenced by MakeRandomSeed(), MakeSeed(), OnCreate(), and FoodEffect.Proc().
GetRandomSeedObj()
static SourceObj.Row TraitSeed.GetRandomSeedObj () inline static
Definition at line 195 of file TraitSeed.cs.
    {
        if (listSeeds == null)
        {
            listSeeds = EClass.sources.objs.rows.Where((SourceObj.Row s) => s.HasTag(CTAG.seed) && !s.HasTag(CTAG.rareSeed)).ToList();
        }
        return listSeeds.RandomItemWeighted((SourceObj.Row a) => a.chance);
    }
References listSeeds, SourceManager.objs, and EClass.sources.
Referenced by MakeRandomSeed(), and OnCreate().
LevelSeed()
static void TraitSeed.LevelSeed (Thing t, SourceObj::Row obj, int num) inline static
Definition at line 140 of file TraitSeed.cs.
    {
        if (obj == null || obj.growth == null || !obj.growth.CanLevelSeed)
        {
            return;
        }
        for (int i = 0; i < num; i++)
        {
            if (obj == null || obj.objType == "crop")
            {
                if (t.encLV == 0)
                {
                    CraftUtil.AddRandomFoodEnc(t);
                }
                else
                {
                    Rand.SetSeed(t.c_seed);
                    CraftUtil.ModRandomFoodEnc(t);
                }
            }
            t.ModEncLv(1);
        }
    }
References CraftUtil.AddRandomFoodEnc(), Card.c_seed, Card.encLV, Card.ModEncLv(), CraftUtil.ModRandomFoodEnc(), and Rand.SetSeed().
Referenced by TraitCrafter.Craft(), Trait.CreateStock(), Zone.Generate(), CraftUtil.MakeDish(), and MakeSeed().
MakeRandomSeed()
static Thing TraitSeed.MakeRandomSeed (bool enc = false) inline static
Definition at line 187 of file TraitSeed.cs.
    {
        Thing thing = ThingGen.Create("seed", null);
        SourceObj.Row randomSeedObj = GetRandomSeedObj();
        ApplySeed(thing, randomSeedObj.id);
        return thing;
    }
References ApplySeed(), ThingGen.Create(), GetRandomSeedObj(), and TileRow.id.
Referenced by Trait.CreateStock(), Card.Decay(), SurvivalManager.OnMineWreck(), and CoreDebug.SetStartStockpile().
MakeSeed() [1/3]
static Thing TraitSeed.MakeSeed (SourceObj::Row obj) inline static
Definition at line 180 of file TraitSeed.cs.
    {
        Thing thing = ThingGen.Create("seed");
        ApplySeed(thing, obj.id);
        return thing;
    }
References ApplySeed(), ThingGen.Create(), and Card.id.
MakeSeed() [2/3]
static Thing TraitSeed.MakeSeed (SourceObj::Row obj, PlantData plant = null) inline static
Definition at line 88 of file TraitSeed.cs.
    {
        Thing thing = plant?.seed;
        if (EClass._zone.IsUserZone)
        {
            thing = null;
        }
        Thing thing2 = ThingGen.Create("seed");
        ApplySeed(thing2, obj.id);
        if (thing != null && obj.growth != null && obj.growth.CanLevelSeed)
        {
            foreach (Element value in thing.elements.dict.Values)
            {
                if (value.IsFoodTrait)
                {
                    thing2.elements.SetTo(value.id, value.Value);
                }
            }
            thing2.SetEncLv(thing.encLV);
            thing2.elements.SetBase(2, EClass.curve(thing2.encLV, 50, 10, 80));
            thing2.c_refText = thing.c_refText;
            thing2.c_seed = thing.c_seed;
            int num = plant?.water ?? 0;
            int num2 = plant?.fert ?? 0;
            int num3 = 220 / (Mathf.Clamp(EClass.pc.Evalue(286) - thing.LV, 0, 50) * 2 + 10 + num * 2 + ((num2 > 0) ? 20 : 0) + (EClass.pc.HasElement(1325) ? 25 : 0));
            if (EClass.player.isAutoFarming)
            {
                num3 = 2 + num3 * 2;
            }
            if (EClass.rnd(num3) == 0 && EClass._zone.IsPCFactionOrTent)
            {
                int num4 = Mathf.Max(5, EClass.pc.Evalue(286)) - thing2.encLV;
                if (num4 <= 0)
                {
                    if (!EClass.player.isAutoFarming)
                    {
                        Msg.Say("seedLvLimit", thing2);
                    }
                }
                else
                {
                    int num5 = Mathf.Clamp(EClass.rnd(num4) - 5, 1, EClass.player.isAutoFarming ? 3 : 10);
                    LevelSeed(thing2, obj, num5);
                    EClass.pc.PlaySound("seed_level");
                }
            }
            Rand.SetSeed();
        }
        thing2.SetBlessedState(BlessedState.Normal);
        return thing2;
    }
References EClass._zone, ApplySeed(), Card.c_refText, Card.c_seed, ThingGen.Create(), EClass.curve(), ElementContainer.dict, Card.elements, Card.encLV, Card.Evalue(), Card.HasElement(), Card.id, Element.id, if(), Player.isAutoFarming, Element.IsFoodTrait, Zone.IsPCFactionOrTent, Zone.IsUserZone, LevelSeed(), Card.LV, EClass.pc, plant, EClass.player, Card.PlaySound(), EClass.rnd(), Msg.Say(), ElementContainer.SetBase(), Card.SetBlessedState(), Card.SetEncLv(), Rand.SetSeed(), ElementContainer.SetTo(), and Element.Value.
Referenced by TraitCrafter.Craft(), Zone.Generate(), MakeSeed(), Map.MineObj(), Trait.OnBarter(), QuestLoytelFarm.OnComplete(), QuestNasu.OnComplete(), GrowSystemTree.OnMineObj(), CoreDebug.QuickStart(), and GrowSystem.TryPopSeed().
MakeSeed() [3/3]
static Thing TraitSeed.MakeSeed (string idSource) inline static
Definition at line 164 of file TraitSeed.cs.
    {
        return MakeSeed(EClass.sources.objs.alias[idSource]);
    }
References MakeSeed(), SourceManager.objs, and EClass.sources.
OnCreate()
override void TraitSeed.OnCreate (int lv) inline virtual
Reimplemented from Trait.
Definition at line 21 of file TraitSeed.cs.
    {
        ApplySeed(owner.Thing, GetRandomSeedObj().id);
        owner.c_seed = EClass.rnd(10000);
    }
References ApplySeed(), GetRandomSeedObj(), Trait.owner, EClass.rnd(), and Card.Thing.
SetName()
override void TraitSeed.SetName (ref string s) inline virtual
Reimplemented from Trait.
Definition at line 27 of file TraitSeed.cs.
    {
        s = "_of".lang(row.GetName(), s);
    }
References SourceObj.GetName(), and row.
TrySprout()
void TraitSeed.TrySprout (bool force = false, bool sucker = false, VirtualDate date = null) inline
Definition at line 70 of file TraitSeed.cs.
    {
        Point pos = owner.pos;
        if (!pos.HasObj && pos.cell.CanGrow(row, date ?? new VirtualDate()))
        {
            pos.SetObj(row.id, 1, owner.dir);
            EClass._map.AddPlant(pos, owner.Thing);
            if (sucker)
            {
                Zone.Suckers.Add(owner.Thing);
            }
            else
            {
                owner.Destroy();
            }
        }
    }
References EClass._map, ActPlan.List.Add(), Map.AddPlant(), Cell.CanGrow(), Point.cell, Card.Destroy(), Card.dir, Point.HasObj, Trait.owner, Card.pos, row, Point.SetObj(), Zone.Suckers, and Card.Thing.
WriteNote()
override void TraitSeed.WriteNote (UINote n, bool identified) inline virtual
Reimplemented from Trait.
Definition at line 32 of file TraitSeed.cs.
    {
        base.WriteNote(n, identified);
        int num = 1;
        if (!row._growth.IsEmpty() && row._growth.Length >= 4)
        {
            if (row._growth.Length >= 5)
            {
                num = row._growth[4].ToInt();
            }
            n.AddText("isHarvestCrop".lang(num.ToString() ?? ""));
        }
        n.AddText("isConsumeFertility".lang((0.1f * (float)row.costSoil).ToString() ?? ""));
        if (row.tag.Contains("flood"))
        {
            n.AddText("isWaterCrop");
        }
        if (row.growth != null)
        {
            if (row.growth.GrowOnLand)
            {
                n.AddText("isGrowOnLand");
            }
            if (row.growth.GrowUndersea)
            {
                n.AddText("isGrowUndersea");
            }
            if (row.growth.NeedSunlight)
            {
                n.AddText("isNeedSun");
            }
        }
        if (row.growth == null || !row.growth.CanLevelSeed)
        {
            n.AddText("isDecoSeed", FontColor.Warning);
        }
    }
References UINote.AddText(), and row.
Member Data Documentation
listSeeds
List<SourceObj.Row> TraitSeed.listSeeds static
Definition at line 7 of file TraitSeed.cs.
Referenced by GetRandomSeedObj().
Property Documentation
CanChangeHeight
override bool TraitSeed.CanChangeHeight get
Definition at line 15 of file TraitSeed.cs.
CanExtendBuild
override bool TraitSeed.CanExtendBuild get
Definition at line 13 of file TraitSeed.cs.
CanName
override bool TraitSeed.CanName get
Definition at line 17 of file TraitSeed.cs.
DefaultStock
override int TraitSeed.DefaultStock get
Definition at line 19 of file TraitSeed.cs.
InstallBottomPriority
override int TraitSeed.InstallBottomPriority get
Definition at line 11 of file TraitSeed.cs.
row
SourceObj.Row TraitSeed.row get
Definition at line 9 of file TraitSeed.cs.
Referenced by ApplySeed(), TraitCrafter.Craft(), SetName(), TrySprout(), and WriteNote().
The documentation for this class was generated from the following file:
Elin/TraitSeed.cs