Elin Decompiled Documentation: LayerEditPlaylist.ListBGM Class Reference
LayerEditPlaylist.ListBGM Class Reference
Public Member Functions
override void List ()
Public Member Functions inherited from ListOwner< BGMData, ItemGeneral >
virtual void List ()
virtual void List ()
virtual void OnCreate ()
virtual void OnCreate ()
virtual void OnSwitchContent ()
virtual void OnSwitchContent ()
virtual void OnRefreshMenu ()
virtual void OnRefreshMenu ()
void MoveToOther (object c)
void MoveToOther (object c)
virtual void OnClick (T1 a, T2 b)
virtual void OnInstantiate (T1 a, T2 b)
virtual void OnList ()
Public Attributes
List< BGMData > items
string idTitle
bool single
Public Attributes inherited from ListOwner< BGMData, ItemGeneral >
Layer layer
Window window
UIMultiList multi
ListOwner other
UIList list
WindowMenu menu
string textTab
string textHeader
bool main
int index
Properties
new LayerEditPlaylist layer [get]
override string IdTitle [get]
Properties inherited from ListOwner< BGMData, ItemGeneral >
ListOwner Main [get]
virtual string IdTitle [get]
virtual string IdHeaderRow [get]
virtual string TextTab [get]
virtual string TextHeader [get]
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Additional Inherited Members
Static Public Member Functions inherited from EClass
static int rnd (int a)
static int curve (int a, int start, int step, int rate=75)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Static Public Attributes inherited from EClass
static Core core
Detailed Description
Definition at line 12 of file LayerEditPlaylist.cs.
Member Function Documentation
List()
override void LayerEditPlaylist.ListBGM.List () inline virtual
Reimplemented from ListOwner< BGMData, ItemGeneral >.
Definition at line 24 of file LayerEditPlaylist.cs.
        {
            list.callbacks = new UIList.Callback<BGMData, ItemGeneral>
            {
                onInstantiate = delegate(BGMData a, ItemGeneral b)
                {
                    b.SetMainText(((a.id > 1) ? "♪ " : "") + a._name.IsEmpty(a.name).ToTitleCase());
                    b.button1.keyText.text = a.id.ToString() ?? "";
                    if (a.id != 0 && layer.jukebox == null)
                    {
                        b.AddSubButton(EClass.core.refs.icons.resume, delegate
{
                            EClass.Sound.PlayBGM(a);
                        });
                    }
                    if (main && layer.mode == Mode.Playlist)
                    {
                        b.AddSubButton(EClass.core.refs.icons.down, delegate
{
                            BGMData select = items.Move(a, 1);
                            list.OnMove(a, select);
                        });
                        b.AddSubButton(EClass.core.refs.icons.up, delegate
{
                            BGMData select2 = items.Move(a, -1);
                            list.OnMove(a, select2);
                        });
                    }
                    b.Build();
                    if (!single)
                    {
                        b.button1.soundClick = null;
                    }
                },
                onClick = delegate(BGMData c, ItemGeneral i)
                {
                    if (layer.mode == Mode.Playlist)
                    {
                        items.Remove(c);
                        (other as ListBGM).items.Add(c);
                        MoveToOther(c);
                    }
                    else if (layer.board != null)
                    {
                        layer.board.data.idBGM = ((layer.board.data.idBGM != c.id) ? c.id : 0);
                        layer.board.ApplyData();
                        layer.Close();
                    }
                    else
                    {
                        layer.jukebox.OnSetBGM(c);
                        layer.Close();
                    }
                },
                onList = delegate
                {
                    foreach (BGMData item in items)
                    {
                        list.Add(item);
                    }
                }
            };
            list.List();
        }
References ItemGeneral.AddSubButton(), TraitHouseBoard.ApplyData(), LayerEditPlaylist.board, ItemGeneral.Build(), EClass.core, CoreRef.Icons.down, CoreRef.icons, LayerEditPlaylist.ListBGM.items, LayerEditPlaylist.jukebox, LayerEditPlaylist.ListBGM.layer, ListOwner< BGMData, ItemGeneral >.list, ListOwner< BGMData, ItemGeneral >.main, LayerEditPlaylist.mode, ListOwner< BGMData, ItemGeneral >.MoveToOther(), TraitJukeBox.OnSetBGM(), ListOwner< BGMData, ItemGeneral >.other, Core.refs, CoreRef.Icons.resume, ItemGeneral.SetMainText(), LayerEditPlaylist.ListBGM.single, and CoreRef.Icons.up.
Member Data Documentation
idTitle
string LayerEditPlaylist.ListBGM.idTitle
Definition at line 16 of file LayerEditPlaylist.cs.
items
List<BGMData> LayerEditPlaylist.ListBGM.items
Definition at line 14 of file LayerEditPlaylist.cs.
Referenced by LayerEditPlaylist.ListBGM.List().
single
bool LayerEditPlaylist.ListBGM.single
Definition at line 18 of file LayerEditPlaylist.cs.
Referenced by LayerEditPlaylist.ListBGM.List().
Property Documentation
IdTitle
override string LayerEditPlaylist.ListBGM.IdTitle get
Definition at line 22 of file LayerEditPlaylist.cs.
layer
new LayerEditPlaylist LayerEditPlaylist.ListBGM.layer get
Definition at line 20 of file LayerEditPlaylist.cs.
Referenced by LayerEditPlaylist.ListBGM.List().
The documentation for this class was generated from the following file:
Elin/LayerEditPlaylist.cs