Elin Decompiled Documentation: BaseStats Class Reference
BaseStats Class Reference
Public Member Functions
virtual Color GetColor (Gradient gradient)
virtual Color GetColor (SkinColorProfile c)
Color GetColor ()
virtual string GetText ()
virtual string GetPhaseStr ()
virtual int GetValue ()
virtual Sprite GetSprite ()
virtual void SetText (UIText t, SkinColorProfile cols=null)
virtual int GetPhase ()
void PopText ()
virtual void WriteNote (UINote n, Action< UINote > onWriteNote=null)
virtual void _WriteNote (UINote n, bool asChild=false)
Public Attributes
int id
SourceStat.Row _source
Static Public Attributes
static Chara CC
Static Public Attributes inherited from EClass
static Core core
Properties
SourceStat.Row source [get]
virtual Emo2 EmoIcon [get]
virtual ConditionType Type [get]
virtual string idSprite [get]
virtual bool ShowInWidget [get]
virtual Chara Owner [get]
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Additional Inherited Members
Static Public Member Functions inherited from EClass
static int rnd (int a)
static int curve (int a, int start, int step, int rate=75)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Detailed Description
Definition at line 6 of file BaseStats.cs.
Member Function Documentation
_WriteNote()
virtual void BaseStats._WriteNote (UINote n, bool asChild = false) inline virtual
Reimplemented in BaseCondition.
Definition at line 138 of file BaseStats.cs.
    {
        List<string> list = new List<string>();
        foreach (string key in this.source.nullify)
        {
            list.Add("hintNullify".lang(EClass.sources.stats.alias[key].GetName(), null, null, null, null));
        }
        if (list.Count > 0)
        {
            if (!asChild)
            {
                n.Space(8, 1);
            }
            foreach (string str in list)
            {
                n.AddText("_bullet".lang() + str, FontColor.DontChange);
            }
        }
    }
References source, EClass.sources, and SourceManager.stats.
Referenced by WriteNote().
GetColor() [1/3]
Color BaseStats.GetColor () inline
Definition at line 39 of file BaseStats.cs.
    {
        return this.GetColor(SkinManager.CurrentColors);
    }
References GetColor().
Referenced by GetColor(), PopText(), and SetText().
GetColor() [2/3]
virtual Color BaseStats.GetColor (Gradient gradient) inline virtual
Reimplemented in BaseCondition, and Stats.
Definition at line 29 of file BaseStats.cs.
    {
        return Color.white;
    }
References Color.
Referenced by NotificationStats.OnRefresh().
GetColor() [3/3]
virtual Color BaseStats.GetColor (SkinColorProfile c) inline virtual
Reimplemented in ConBuffStats.
Definition at line 34 of file BaseStats.cs.
    {
        return this.GetColor(c.gradients[this.source.colors.IsEmpty("default")]);
    }
References GetColor().
GetPhase()
virtual int BaseStats.GetPhase () inline virtual
Reimplemented in BaseBuff, BaseCondition, BaseDebuff, BaseStance, ConAnorexia, ConBlind, ConBuffStats, ConBurning, ConConfuse, ConDrug, ConDrunk, ConEntangle, ConFaint, ConFear, ConGravity, ConParalyze, ConReload, ConSleep, ConSuffocation, ConSuspend, ConWait, ConWet, ConWrath, Stats, StatsBurden, and StatsStamina.
Definition at line 97 of file BaseStats.cs.
    {
        return 0;
    }
GetPhaseStr()
virtual string BaseStats.GetPhaseStr () inline virtual
Reimplemented in BaseCondition, and ConBuffStats.
Definition at line 57 of file BaseStats.cs.
    {
        return this.GetText();
    }
References GetText().
Referenced by Chara.GetHoverText2(), PopText(), and Chara.RefreshSpeed().
GetSprite()
virtual Sprite BaseStats.GetSprite () inline virtual
Definition at line 75 of file BaseStats.cs.
    {
        return SpriteSheet.Get("Media/Graphics/Icon/Element/icon_elements", this.idSprite) ?? EClass.core.refs.spriteDefaultCondition;
    }
References EClass.core, and idSprite.
Referenced by WindowChara.AddStatus(), and NotificationBuff.OnInstantiate().
GetText()
virtual string BaseStats.GetText () inline virtual
Reimplemented in BaseCondition, ConBuffStats, and Stats.
Definition at line 52 of file BaseStats.cs.
    {
        return null;
    }
Referenced by WindowChara.AddStatus(), GetPhaseStr(), NotificationStats.OnRefresh(), and SetText().
GetValue()
virtual int BaseStats.GetValue () inline virtual
Reimplemented in BaseCondition, and Stats.
Definition at line 62 of file BaseStats.cs.
    {
        return 0;
    }
Referenced by Chara.GetHoverText2().
PopText()
void BaseStats.PopText () inline
Definition at line 110 of file BaseStats.cs.
    {
        if (!EClass.core.IsGameStarted || !this.Owner.ShouldShowMsg)
        {
            return;
        }
        string phaseStr = this.GetPhaseStr();
        if (phaseStr.IsEmpty() || phaseStr == "#")
        {
            return;
        }
        Popper popper = EClass.scene.popper.Pop(this.Owner.renderer.PositionCenter(), "Condition");
        Color c = this.GetColor() * 1.3f;
        c.r += 0.3f;
        c.g += 0.3f;
        c.b += 0.3f;
        popper.SetText(phaseStr, c);
    }
References Color, EClass.core, GetColor(), GetPhaseStr(), Owner, Scene.popper, CardRenderer.PositionCenter(), Card.renderer, and EClass.scene.
SetText()
virtual void BaseStats.SetText (UIText t, SkinColorProfile cols = null) inline virtual
Definition at line 80 of file BaseStats.cs.
    {
        if (cols == null)
        {
            cols = EClass.ui.skins.currentSkin.colors._default;
        }
        t.SetText(this.GetText(), this.GetColor(cols));
    }
References GetColor(), GetText(), and EClass.ui.
Referenced by WindowChara.AddNeeds(), and WindowChara.AddStatus().
WriteNote()
virtual void BaseStats.WriteNote (UINote n, Action< UINote > onWriteNote = null) inline virtual
Definition at line 129 of file BaseStats.cs.
    {
        n.Clear();
        n.AddHeader(this.source.GetName(), null);
        n.AddText("NoteText_flavor_element", this.source.GetDetail(), FontColor.DontChange);
        this._WriteNote(n, false);
        n.Build();
    }
References _WriteNote(), and source.
Referenced by WindowChara.AddStatus().
Member Data Documentation
_source
SourceStat.Row BaseStats._source
Definition at line 163 of file BaseStats.cs.
CC
Chara BaseStats.CC static
Definition at line 158 of file BaseStats.cs.
Referenced by Stats.Mod(), StatsMana.Mod(), StatsStamina.Mod(), Stats.OnChangePhase(), and ActEffect.Proc().
id
int BaseStats.id
Definition at line 161 of file BaseStats.cs.
Referenced by Chara.AddCondition(), Chara.AddResistCon(), Chara.GetHoverText2(), Chara.ResistCon(), and BaseCondition.SetElement().
Property Documentation
EmoIcon
virtual Emo2 BaseStats.EmoIcon get
Definition at line 21 of file BaseStats.cs.
    {
        get
        {
            return Emo2.none;
        }
    }
Referenced by BaseCondition.SetOwner(), and Chara.TickConditions().
idSprite
virtual string BaseStats.idSprite get
Definition at line 67 of file BaseStats.cs.
    {
        get
        {
            return this.source.element.IsEmpty(this.source.alias);
        }
    }
Referenced by GetSprite().
Owner
virtual Chara BaseStats.Owner get
Definition at line 102 of file BaseStats.cs.
    {
        get
        {
            return BaseStats.CC;
        }
    }
Referenced by PopText().
ShowInWidget
virtual bool BaseStats.ShowInWidget get
Definition at line 89 of file BaseStats.cs.
    {
        get
        {
            return true;
        }
    }
Referenced by WidgetStats.OnRefresh().
source
SourceStat.Row BaseStats.source get
Definition at line 8 of file BaseStats.cs.
    {
        get
        {
            SourceStat.Row result;
            if ((result = this._source) == null)
            {
                result = (this._source = EClass.sources.stats.map[this.id]);
            }
            return result;
        }
    }
Referenced by _WriteNote(), Chara.AddCondition(), WindowChara.AddNeeds(), WindowChara.AddStatus(), Chara.GetHoverText2(), StatsBurden.GetPhase(), and WriteNote().
Type
virtual ConditionType BaseStats.Type get
Definition at line 44 of file BaseStats.cs.
    {
        get
        {
            return this.source.group.ToEnum(true);
        }
    }
Referenced by TraitShrine._OnUse(), Chara.AddCondition(), Chara.Cure(), Card.DamageHP(), BaseCondition.PhaseMsg(), and ActEffect.Proc().
The documentation for this class was generated from the following file:
Elin/BaseStats.cs