Elin Decompiled Documentation: LayerQuestBoard Class Reference
LayerQuestBoard Class Reference
Public Member Functions
override void OnInit ()
override void OnSwitchContent (Window window)
void RefreshQuest ()
void RefreshHire ()
void RefreshRanking ()
override void OnKill ()
Public Member Functions inherited from ELayer
override void OnBeforeAddLayer ()
void InitInspector ()
sealed override void Init ()
override void OnAfterAddLayer ()
void TryShowHelp ()
void AddLayerToUI (string id)
void TryShowHint (string _langHint=null)
void TalkHomeMemeber (string id)
void TalkMaid (string id)
override void OnRightClick ()
Public Member Functions inherited from Layer
virtual string GetTextHeader (Window window)
virtual bool HeaderIsListOf (int id)
virtual void Init ()
virtual void OnInit ()
virtual void OnAfterInit ()
virtual void ApplySkin ()
void ShowScreenLock (string id)
void UpdateInput ()
virtual void OnUpdateInput ()
virtual void OnRightClick ()
virtual bool OnBack ()
virtual void OnChangeLayer ()
virtual void OnCreate ()
void _AddLayer (string id)
Layer AddLayer (string id)
T AddLayer< T > ()
T AddLayer< T > (string id)
T AddLayerDontCloseOthers< T > ()
Layer AddLayerDontCloseOthers (Layer l)
T GetOrAddLayer< T > ()
virtual void OnBeforeAddLayer ()
virtual void OnAfterAddLayer ()
Layer AddLayer (Layer l)
void ToggleLayer (string id)
T ToggleLayer< T > (string id=null)
void WaitAndClose ()
void OnClickClose ()
virtual void Close ()
void CloseLayers ()
void RemoveLayers (bool removeImportant=false)
bool RemoveLayer< T > ()
void RemoveLayer (Layer l)
virtual void OnKill ()
Layer SetOnKill (Action action)
void DisableClose ()
void Delay (float duration=0.05f)
Layer SetDelay (float d)
Layer GetLayer (string id)
T GetLayer< T > (bool fromTop=false)
Layer GetTopLayer ()
void SwitchContent (int idWindow, int i)
virtual void OnSwitchContent (Window window)
Layer SetTitles (string langList, string idHeaderRow=null)
bool IsBlockWidgetClick ()
bool IsHideHud ()
bool IsAllowGeneralInput ()
bool IsUseBlur ()
bool IsPointerOnLayer ()
void ApplySkin ()
Public Attributes
UIList list
UIList listHire
UIDynamicList listRanking
UIText textClient
UIText textTitle
UIText textDetail
UIText textHours
UIText textNote
UIText textReward
UIText textQuestLimit
Portrait portrait
UIButton buttonTalk
UICurrency uiCurrency
Gradient gradientRank
Public Attributes inherited from Layer
Option option
UnityEvent onKill
Anime animeIn
Anime animeOut
bool closeOthers
bool defaultActionMode = true
Button screenLock
Layer parent
string idLayer
List< Layer > layers = new List<Layer>()
Vector2 lastParentPos
List< Window > windows = new List<Window>()
string langHint
Additional Inherited Members
Static Public Member Functions inherited from ELayer
static int rnd (int a)
Static Public Member Functions inherited from Layer
static T Create< T > ()
static T Create< T > (string path)
static Layer Create (string path)
Static Public Attributes inherited from Layer
static int skipInput
static bool closeOnRightClick
static bool rightClicked
static bool cancelKeyDown
static bool ignoreSounds
static Transform blurStopInstance
static string[] searchPath = new string[3] { "Layer", "Layer/Dialog", "Layer/LayerHome" }
Protected Member Functions inherited from ELayer
sealed override void _Close ()
sealed override void Kill ()
Protected Member Functions inherited from Layer
virtual void Awake ()
virtual void _Close ()
virtual void Kill ()
Protected Attributes inherited from Layer
RectTransform _rect
bool isDestroyed
Properties inherited from ELayer
static Core core [get]
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static FactionBranch Branch [get]
static Faction Home [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static CoreConfig config [get]
static GameSetting setting [get]
static ColorProfile Colors [get]
static SourceManager sources [get]
static World world [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
bool IsFloat [get]
virtual string IdHelp [get]
Properties inherited from Layer
Layer TopLayer [get]
string uid [get]
virtual RectTransform rectLayers [get]
virtual bool blockWidgetClick [get]
Detailed Description
Definition at line 3 of file LayerQuestBoard.cs.
Member Function Documentation
OnInit()
override void LayerQuestBoard.OnInit () inline virtual
Reimplemented from Layer.
Definition at line 33 of file LayerQuestBoard.cs.
    {
        if (ELayer._zone.IsPCFaction)
        {
            ELayer._zone.branch.UpdateReqruits();
        }
        windows[0].setting.tabs[1].disable = !ELayer._zone.IsPCFaction;
    }
References ELayer._zone, Zone.branch, Zone.IsPCFaction, FactionBranch.UpdateReqruits(), and Layer.windows.
OnKill()
override void LayerQuestBoard.OnKill () inline virtual
Reimplemented from Layer.
Definition at line 215 of file LayerQuestBoard.cs.
    {
        if (ELayer.Branch != null)
        {
            ELayer.Branch.ClearNewRecruits();
        }
    }
References ELayer.Branch, and FactionBranch.ClearNewRecruits().
OnSwitchContent()
override void LayerQuestBoard.OnSwitchContent (Window window) inline virtual
Reimplemented from Layer.
Definition at line 42 of file LayerQuestBoard.cs.
    {
        switch (window.idTab)
        {
        case 0:
            RefreshQuest();
            break;
        case 1:
            RefreshHire();
            break;
        case 2:
            RefreshRanking();
            break;
        }
        WindowMenu menuRight = windows[0].menuRight;
        menuRight.Clear();
        if (window.idTab != 0)
        {
            return;
        }
        UIButton button = null;
        button = menuRight.AddButton("rerollQuest".lang(GetCost().ToString() ?? ""), delegate
        {
            if (ELayer._zone.influence < GetCost())
            {
                SE.Beep();
                Msg.Say("notEnoughInfluence");
            }
            else
            {
                SE.Dice();
                ELayer._zone.UpdateQuests(force: true);
                RefreshQuest();
                ELayer._zone.influence -= GetCost();
                if (ELayer.player.questRerollCost < 14)
                {
                    ELayer.player.questRerollCost++;
                }
                button.mainText.SetText("rerollQuest".lang(GetCost().ToString() ?? ""));
            }
        });
        static int GetCost()
        {
            return 1;
        }
    }
References ELayer._zone, WindowMenu.AddButton(), WindowMenu.Clear(), Window.idTab, Spatial.influence, UIButton.mainText, ELayer.player, Player.questRerollCost, RefreshHire(), RefreshQuest(), RefreshRanking(), Msg.Say(), UIText.SetText(), Zone.UpdateQuests(), and Layer.windows.
RefreshHire()
void LayerQuestBoard.RefreshHire () inline
Definition at line 123 of file LayerQuestBoard.cs.
    {
        UIList list = listHire;
        list.Clear();
        list.callbacks = new UIList.Callback<HireInfo, ButtonChara>
        {
            onClick = delegate(HireInfo a, ButtonChara b)
            {
                a.isNew = false;
                GameLang.refDrama1 = "(" + "money2".lang() + ": " + CalcGold.Hire(a.chara) + ")";
                GameLang.refDrama2 = ELayer.pc.things.Find("ticket_resident")?.Name ?? "";
                a.chara.ShowDialog("_chara", "4-1").onKill.AddListener(RefreshHire);
            },
            onInstantiate = delegate(HireInfo a, ButtonChara b)
            {
                Chara chara = a.chara;
                b.SetChara(chara, ButtonChara.Mode.Hire);
                int cost = CalcGold.Hire(chara);
                b.item.text1.text = cost.ToString().TagColorGoodBad(() => ELayer.pc.GetCurrency("money2") >= cost || ELayer.pc.things.Find("ticket_resident") != null);
                b.item.text2.text = ((a.Days == -1) ? "-" : (a.Days.ToString() ?? ""));
                HintIcon[] componentsInChildren = b.layoutTag.GetComponentsInChildren<HintIcon>();
                for (int i = 0; i < componentsInChildren.Length; i++)
                {
                    componentsInChildren[i].onPointerDown = delegate
                    {
                        list.callbacks.OnClick(a, b);
                    };
                }
                b.textHobby.text = chara.GetTextHobby();
                b.textWork.text = chara.GetTextWork();
                b.textLifeStyle.text = "lifestyle".lang() + ": " + ("lifestyle_" + chara.idTimeTable).lang();
                b.item.image1.SetActive(a.isNew);
            },
            onRefresh = null
        };
        foreach (HireInfo item in ELayer.Branch.listRecruit)
        {
            if (!item.chara.IsHomeMember() && (item.chara.currentZone == null || !item.chara.currentZone.IsPlayerFaction))
            {
                list.Add(item);
            }
        }
        list.Refresh();
        this.RebuildLayout(recursive: true);
    }
References UIList.Add(), ELayer.Branch, BaseList.callbacks, HireInfo.chara, UIList.Clear(), HireInfo.Days, ThingContainer.Find(), Card.GetCurrency(), Chara.GetTextHobby(), Chara.GetTextWork(), CalcGold.Hire(), Chara.idTimeTable, UIItem.image1, HireInfo.isNew, ButtonChara.item, item, ButtonChara.layoutTag, list, listHire, FactionBranch.listRecruit, Card.Name, HintIcon.onPointerDown, ELayer.pc, UIList.Refresh(), RefreshHire(), ButtonChara.SetChara(), Chara.ShowDialog(), and Card.things.
Referenced by OnSwitchContent(), and RefreshHire().
RefreshQuest()
void LayerQuestBoard.RefreshQuest () inline
Definition at line 89 of file LayerQuestBoard.cs.
    {
        list.Clear();
        list.callbacks = new UIList.Callback<Quest, ItemQuest>
        {
            onInstantiate = delegate(Quest a, ItemQuest b)
            {
                b.SetQuest(a);
                b.button.SetOnClick(delegate
                {
                    Close();
                    a.OnClickQuest();
                });
            }
        };
        ELayer._zone.UpdateQuests();
        foreach (Quest global in ELayer.game.quests.globalList)
        {
            if (global.IsVisibleOnQuestBoard())
            {
                list.Add(global);
            }
        }
        foreach (Chara chara in ELayer._map.charas)
        {
            if (chara.quest != null && !ELayer.game.quests.list.Contains(chara.quest) && !chara.IsPCParty && chara.memberType == FactionMemberType.Default && chara.quest.IsVisibleOnQuestBoard())
            {
                list.Add(chara.quest);
            }
        }
        list.Refresh();
        textQuestLimit.SetText("questLimit".lang(ELayer.game.quests.CountRandomQuest().ToString() ?? "", 5.ToString() ?? ""));
    }
References ELayer._map, ELayer._zone, UIList.Add(), ItemQuest.button, Map.charas, UIList.Clear(), Layer.Close(), QuestManager.CountRandomQuest(), ELayer.game, QuestManager.globalList, Quest.IsVisibleOnQuestBoard(), list, QuestManager.list, Quest.OnClickQuest(), Chara.quest, Game.quests, UIList.Refresh(), ItemQuest.SetQuest(), UIText.SetText(), textQuestLimit, and Zone.UpdateQuests().
Referenced by OnSwitchContent().
RefreshRanking()
void LayerQuestBoard.RefreshRanking () inline
Definition at line 169 of file LayerQuestBoard.cs.
    {
        UIDynamicList list = listRanking;
        list.Clear();
        list.callbacks = new UIList.Callback<Chara, ButtonChara>
        {
            onClick = delegate
            {
            },
            onRedraw = delegate(Chara a, ButtonChara b, int i)
            {
                b.SetChara(a, ButtonChara.Mode.Ranking);
                int advRank = a.trait.GetAdvRank();
                b.textAlias.SetText(a.trait.GetAdvRankText());
                b.textAlias.color = gradientRank.Evaluate(0.1f * (float)advRank);
                b.item.image2.SetActive(a.IsPCFaction);
                bool enable = a.GetInt(111) > 0;
                b.transDefeated.SetActive(enable);
            },
            onList = delegate
            {
                foreach (Chara value in ELayer.game.cards.globalCharas.Values)
                {
                    if (value.trait.ShowAdvRank)
                    {
                        list.Add(value);
                    }
                }
                list.objects.Sort((object a, object b) => GetSortVal(b as Chara) - GetSortVal(a as Chara));
            },
            onRefresh = null
        };
        list.List();
        int num = list.objects.IndexOf(ELayer.pc);
        if (num != -1)
        {
            list.dsv.scrollByItemIndex(num);
            list.Refresh();
        }
        this.RebuildLayout(recursive: true);
        static int GetSortVal(Chara c)
        {
            return c.trait.GetAdvRank() * 10000 + Mathf.Clamp(c.LV, 0, 1000) + ((c.trait is TraitAdventurerBacker) ? 1000 : 0);
        }
    }
References UIList.Add(), Game.cards, UIList.Clear(), ELayer.game, TraitChara.GetAdvRank(), TraitChara.GetAdvRankText(), BaseCard.GetInt(), CardManager.globalCharas, gradientRank, UIItem.image2, Chara.IsPCFaction, ButtonChara.item, list, UIList.List(), listRanking, Card.LV, ELayer.pc, UIList.Refresh(), ButtonChara.SetChara(), UIText.SetText(), TraitChara.ShowAdvRank, UIList.Sort(), ButtonChara.textAlias, Chara.trait, and ButtonChara.transDefeated.
Referenced by OnSwitchContent().
Member Data Documentation
buttonTalk
UIButton LayerQuestBoard.buttonTalk
Definition at line 27 of file LayerQuestBoard.cs.
gradientRank
Gradient LayerQuestBoard.gradientRank
Definition at line 31 of file LayerQuestBoard.cs.
Referenced by RefreshRanking().
list
UIList LayerQuestBoard.list
Definition at line 5 of file LayerQuestBoard.cs.
Referenced by RefreshHire(), RefreshQuest(), and RefreshRanking().
listHire
UIList LayerQuestBoard.listHire
Definition at line 7 of file LayerQuestBoard.cs.
Referenced by RefreshHire().
listRanking
UIDynamicList LayerQuestBoard.listRanking
Definition at line 9 of file LayerQuestBoard.cs.
Referenced by RefreshRanking().
portrait
Portrait LayerQuestBoard.portrait
Definition at line 25 of file LayerQuestBoard.cs.
textClient
UIText LayerQuestBoard.textClient
Definition at line 11 of file LayerQuestBoard.cs.
textDetail
UIText LayerQuestBoard.textDetail
Definition at line 15 of file LayerQuestBoard.cs.
textHours
UIText LayerQuestBoard.textHours
Definition at line 17 of file LayerQuestBoard.cs.
textNote
UIText LayerQuestBoard.textNote
Definition at line 19 of file LayerQuestBoard.cs.
textQuestLimit
UIText LayerQuestBoard.textQuestLimit
Definition at line 23 of file LayerQuestBoard.cs.
Referenced by RefreshQuest().
textReward
UIText LayerQuestBoard.textReward
Definition at line 21 of file LayerQuestBoard.cs.
textTitle
UIText LayerQuestBoard.textTitle
Definition at line 13 of file LayerQuestBoard.cs.
uiCurrency
UICurrency LayerQuestBoard.uiCurrency
Definition at line 29 of file LayerQuestBoard.cs.
The documentation for this class was generated from the following file:
Elin/LayerQuestBoard.cs