Elin Decompiled Documentation: CharaBody Class Reference
CharaBody Class Reference
Public Member Functions
void SetOwner (Chara chara, bool deserialized=false)
void Unequip (Thing thing, bool refresh=true)
void UnequipAll (int idSlot)
void Unequip (BodySlot slot, bool refresh=true)
bool IsEquippable (Thing thing, BodySlot slot, bool text=true)
bool IsTooHeavyToEquip (Thing thing)
void UnqeuipIfTooHeavy (Thing t)
bool Equip (Thing thing, BodySlot slot=null, bool msg=true)
void AddBodyPart (int ele, Thing thing=null)
void RefreshBodyParts ()
void RemoveBodyPart (int ele)
void RemoveBodyPartAt (int idx)
BodySlot GetSlot (Thing t, bool onlyEmpty=false, bool secondSlot=false)
BodySlot GetSlot (int elementId, bool onlyEmpty=true, bool secondSlot=false)
Thing GetEquippedThing (int elementId)
int GetWeight (bool armorOnly=false)
int GetAttackIndex (Thing t)
int GetMeleeDistance ()
AttackStyle GetAttackStyle ()
int GetAttackStyleElement (AttackStyle style)
int GetSortVal (BodySlot slot)
void SetBodyIndexText (BodySlot b, UIText t)
Public Attributes
Chara owner
List< BodySlot > slots = new List<BodySlot>()
BodySlot slotMainHand
BodySlot slotOffHand
BodySlot slotRange
Properties
int[] rawSlots [get]
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Additional Inherited Members
Static Public Member Functions inherited from EClass
static int rndSeed (int a, int seed)
static int rnd (long a)
static int rnd (int a)
static int curve (int a, int start, int step, int rate=75)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Static Public Attributes inherited from EClass
static Core core
Detailed Description
Definition at line 4 of file CharaBody.cs.
Member Function Documentation
AddBodyPart()
void CharaBody.AddBodyPart (int ele, Thing thing = null) inline
Definition at line 261 of file CharaBody.cs.
    {
        BodySlot item = new BodySlot
        {
            elementId = ele,
            thing = thing,
            index = slots.Count
        };
        if (ele == 35)
        {
            if (slotMainHand == null)
            {
                slotMainHand = item;
            }
            else if (slotOffHand == null)
            {
                slotOffHand = item;
            }
        }
        if (ele == 41)
        {
            slotRange = item;
        }
        slots.Add(item);
    }
References item, slotMainHand, slotOffHand, slotRange, and slots.
Referenced by Chara.AddRandomBodyPart(), DNA.Apply(), Chara.ApplyRace(), CoreDebug.ChangeRace(), Player.CreateEquip(), Chara.ResetBody(), and SetOwner().
Equip()
bool CharaBody.Equip (Thing thing, BodySlot slot = null, bool msg = true) inline
Definition at line 182 of file CharaBody.cs.
    {
        slot = slot ?? GetSlot(thing.category.slot) ?? GetSlot(thing.category.slot, onlyEmpty: false);
        if (slot == slotMainHand || slot == slotOffHand)
        {
            owner.combatCount = 10;
        }
        if (slot == null || slot.elementId != thing.category.slot)
        {
            Debug.LogWarning("could not equip:" + thing?.ToString() + "/" + slot?.ToString() + "/" + owner);
            return false;
        }
        if (!IsEquippable(thing, slot))
        {
            return false;
        }
        if (slot.thing != null)
        {
            if (slot.thing == thing)
            {
                Unequip(slot);
                return false;
            }
            Unequip(slot, refresh: false);
        }
        Unequip(thing, refresh: false);
        if (thing.parent != owner)
        {
            if (msg && owner.IsPC && thing.parent is Thing)
            {
                Msg.Say("movedToEquip", thing, thing.parent as Thing);
            }
            owner.AddCard(thing);
        }
        slot.thing = thing;
        thing.c_equippedSlot = slot.index + 1;
        thing.elements.SetParent(owner);
        thing.trait.OnEquip(owner, onSetOwner: false);
        if (EClass.pc != null)
        {
            EClass.pc.faction.charaElements.OnEquip(owner, thing);
        }
        owner.SetTempHand();
        if (owner.IsPC)
        {
            if (msg)
            {
                LayerChara.Refresh();
            }
            LayerInventory.SetDirty(thing);
            WidgetEquip.SetDirty();
        }
        if (slot.elementId == 45 && EClass.core.IsGameStarted)
        {
            owner.RecalculateFOV();
        }
        if (owner.isCreated && EClass.core.IsGameStarted)
        {
            owner.Refresh();
        }
        if (owner.isCreated)
        {
            if (thing.Evalue(656) > 0)
            {
                thing.blessedState = BlessedState.Cursed;
            }
            if (thing.blessedState <= BlessedState.Cursed)
            {
                owner.Say("equipCursed", owner);
                owner.PlaySound("curse3");
            }
        }
        if (slot.elementId == 37 && owner.HasElement(1209) && !thing.HasElement(419))
        {
            owner.Say("tail_covered", owner);
        }
        return true;
    }
References Card.AddCard(), Card.blessedState, Card.category, Faction.charaElements, EClass.core, Debug, BodySlot.elementId, Card.elements, Card.Evalue(), Chara.faction, GetSlot(), Card.HasElement(), Chara.isCreated, IsEquippable(), Core.IsGameStarted, Chara.IsPC, Trait.OnEquip(), ElementContainerFaction.OnEquip(), owner, Card.parent, EClass.pc, Card.PlaySound(), Card.RecalculateFOV(), LayerChara.Refresh(), Chara.Refresh(), Msg.Say(), Card.Say(), WidgetEquip.SetDirty(), LayerInventory.SetDirty(), ElementContainer.SetParent(), Chara.SetTempHand(), slotMainHand, slotOffHand, BodySlot.thing, Card.trait, and Unequip().
Referenced by CoreDebug.ChangeRace(), Chara.EQ_CAT(), Chara.EQ_ID(), InvOwner.ListInteractions(), InvOwner.OnDrag(), TraitMannequin.OnUse(), HotItemEQSet.Perform(), InvOwner.PutBack(), AI_Equip.Run(), and Chara.TryEquip().
GetAttackIndex()
int CharaBody.GetAttackIndex (Thing t) inline
Definition at line 403 of file CharaBody.cs.
    {
        int num = 0;
        foreach (BodySlot slot in slots)
        {
            if (slot.thing != null && slot.elementId == 35 && slot.thing.source.offense.Length >= 2)
            {
                if (slot.thing == t)
                {
                    return num;
                }
                num++;
            }
        }
        return -1;
    }
References BodySlot.elementId, slots, Thing.source, and BodySlot.thing.
GetAttackStyle()
AttackStyle CharaBody.GetAttackStyle () inline
Definition at line 433 of file CharaBody.cs.
    {
        bool flag = false;
        int num = 0;
        foreach (BodySlot slot in slots)
        {
            if (slot.elementId == 35 && slot.thing != null)
            {
                if (slot.thing.IsMeleeWeapon)
                {
                    num++;
                }
                else
                {
                    flag = true;
                }
            }
        }
        if (num > 1)
        {
            return AttackStyle.TwoWield;
        }
        if (flag)
        {
            return AttackStyle.Shield;
        }
        if (num == 1)
        {
            return AttackStyle.TwoHand;
        }
        return AttackStyle.Default;
    }
References BodySlot.elementId, Card.IsMeleeWeapon, slots, and BodySlot.thing.
Referenced by Chara.CalcCastingChance(), Card.DamageHP(), AttackProcess.GetTwoHandEncBonus(), AttackProcess.Prepare(), WindowCharaMini.Refresh(), and WindowChara.RefreshProfile().
GetAttackStyleElement()
int CharaBody.GetAttackStyleElement (AttackStyle style) inline
Definition at line 466 of file CharaBody.cs.
    {
        return style switch
        {
            AttackStyle.TwoHand => 130,
            AttackStyle.TwoWield => 131,
            _ => 0,
        };
    }
Referenced by AttackProcess.Perform().
GetEquippedThing()
Thing CharaBody.GetEquippedThing (int elementId) inline
Definition at line 378 of file CharaBody.cs.
    {
        foreach (BodySlot slot in slots)
        {
            if (slot.elementId == elementId && slot.thing != null)
            {
                return slot.thing;
            }
        }
        return null;
    }
References BodySlot.elementId, slots, and BodySlot.thing.
Referenced by QuestCrafter.CanUpdateOnTalk(), Card.GetLightRadius(), and CoreDebug.QuickStart().
GetMeleeDistance()
int CharaBody.GetMeleeDistance () inline
Definition at line 420 of file CharaBody.cs.
    {
        int num = owner.Evalue(666);
        foreach (BodySlot slot in slots)
        {
            if (slot.elementId == 35 && slot.thing != null && slot.thing.Evalue(666) > num)
            {
                num = slot.thing.Evalue(666);
            }
        }
        return 1 + num;
    }
References BodySlot.elementId, Card.Evalue(), owner, slots, and BodySlot.thing.
Referenced by GoalCombat.TryUseAbility().
GetSlot() [1/2]
BodySlot CharaBody.GetSlot (int elementId, bool onlyEmpty = true, bool secondSlot = false) inline
Definition at line 361 of file CharaBody.cs.
    {
        bool flag = true;
        foreach (BodySlot slot in slots)
        {
            if (elementId == slot.elementId && (!onlyEmpty || slot.thing == null))
            {
                if (!(secondSlot && flag))
                {
                    return slot;
                }
                flag = false;
            }
        }
        return null;
    }
References BodySlot.elementId, slots, and BodySlot.thing.
GetSlot() [2/2]
BodySlot CharaBody.GetSlot (Thing t, bool onlyEmpty = false, bool secondSlot = false) inline
Definition at line 347 of file CharaBody.cs.
    {
        BodySlot slot = GetSlot(t.category.slot, onlyEmpty: true, secondSlot);
        if (slot != null)
        {
            return slot;
        }
        if (!onlyEmpty)
        {
            return GetSlot(t.category.slot, onlyEmpty: false, secondSlot);
        }
        return null;
    }
References Card.category, and GetSlot().
Referenced by Chara.EQ_CAT(), Chara.EQ_ID(), Equip(), GetSlot(), InvOwner.ListInteractions(), HotItemEQSet.Perform(), Chara.RefreshSpeed(), Chara.ShouldEquip(), and Chara.TryEquip().
GetSortVal()
int CharaBody.GetSortVal (BodySlot slot) inline
Definition at line 476 of file CharaBody.cs.
    {
        return -(slot.element.sort * 100 + owner.body.slots.IndexOf(slot));
    }
References Chara.body, owner, and slots.
Referenced by LayerEquip.RefreshEquipment(), WidgetEquip.RefreshEquipment(), WindowChara.RefreshEquipment(), and ButtonElement.SetGrid().
GetWeight()
int CharaBody.GetWeight (bool armorOnly = false) inline
Definition at line 390 of file CharaBody.cs.
    {
        int num = 0;
        foreach (BodySlot slot in slots)
        {
            if (slot.thing != null && (!armorOnly || (slot.elementId != 44 && slot.elementId != 45)))
            {
                num += slot.thing.ChildrenAndSelfWeight;
            }
        }
        return num;
    }
References Card.ChildrenAndSelfWeight, BodySlot.elementId, slots, and BodySlot.thing.
Referenced by Chara.GetArmorSkill(), WindowCharaMini.Refresh(), and WindowChara.RefreshProfile().
IsEquippable()
bool CharaBody.IsEquippable (Thing thing, BodySlot slot, bool text = true) inline
Definition at line 106 of file CharaBody.cs.
    {
        if (slot == null)
        {
            return false;
        }
        switch (slot.elementId)
        {
        case 31:
            if (owner.HasElement(1555))
            {
                return CannotEquip();
            }
            break;
        case 33:
            if (owner.HasElement(1554))
            {
                return CannotEquip();
            }
            break;
        case 39:
            if (owner.HasElement(1552))
            {
                return CannotEquip();
            }
            break;
        }
        if (slot.thing != null && slot.thing.blessedState <= BlessedState.Cursed)
        {
            return CannotEquip();
        }
        if (IsTooHeavyToEquip(thing))
        {
            if (EClass.core.IsGameStarted && owner.IsPC && text)
            {
                Msg.Say("tooHeavyToEquip", thing);
            }
            return false;
        }
        return true;
        bool CannotEquip()
        {
            if (text)
            {
                Msg.Say("cannnotEquip", slot.element.GetName().ToLower());
            }
            return false;
        }
    }
References Card.blessedState, EClass.core, BodySlot.element, BodySlot.elementId, Card.HasElement(), Core.IsGameStarted, Chara.IsPC, IsTooHeavyToEquip(), owner, Msg.Say(), and BodySlot.thing.
Referenced by Equip(), InvOwner.OnDrag(), and Chara.ShouldEquip().
IsTooHeavyToEquip()
bool CharaBody.IsTooHeavyToEquip (Thing thing) inline
Definition at line 156 of file CharaBody.cs.
    {
        if (owner.HasElement(1204) && thing.ChildrenAndSelfWeight > 1000)
        {
            return thing.category.slot != 44;
        }
        return false;
    }
References Card.ChildrenAndSelfWeight, Card.HasElement(), and owner.
Referenced by Thing.CanAutoFire(), Chara.CanEquipRanged(), IsEquippable(), ActRanged.Perform(), and UnqeuipIfTooHeavy().
RefreshBodyParts()
void CharaBody.RefreshBodyParts () inline
Definition at line 287 of file CharaBody.cs.
    {
        for (int i = 0; i < slots.Count; i++)
        {
            BodySlot bodySlot = slots[i];
            bodySlot.index = i;
            int elementId = bodySlot.elementId;
            if (elementId == 35)
            {
                if (slotMainHand == null)
                {
                    slotMainHand = bodySlot;
                }
                else if (slotOffHand == null)
                {
                    slotOffHand = bodySlot;
                }
            }
            if (elementId == 41)
            {
                slotRange = bodySlot;
            }
            if (bodySlot.thing != null)
            {
                bodySlot.thing.c_equippedSlot = i + 1;
            }
        }
    }
References BodySlot.elementId, slotMainHand, slotOffHand, slotRange, slots, and BodySlot.thing.
Referenced by DNA.Apply(), Chara.ApplyRace(), and Chara.ResetBody().
RemoveBodyPart()
void CharaBody.RemoveBodyPart (int ele) inline
Definition at line 316 of file CharaBody.cs.
    {
        int idx = slots.FindIndex((BodySlot a) => a.elementId == ele);
        RemoveBodyPartAt(idx);
    }
References BodySlot.elementId, RemoveBodyPartAt(), and slots.
Referenced by DNA.Apply(), Chara.ApplyRace(), CoreDebug.ChangeRace(), and Chara.ResetBody().
RemoveBodyPartAt()
void CharaBody.RemoveBodyPartAt (int idx) inline
Definition at line 322 of file CharaBody.cs.
    {
        if (idx != -1)
        {
            BodySlot bodySlot = slots[idx];
            if (bodySlot.thing != null)
            {
                Unequip(bodySlot);
            }
            if (slotMainHand == bodySlot)
            {
                slotMainHand = null;
            }
            if (slotOffHand == bodySlot)
            {
                slotOffHand = null;
            }
            if (slotRange == bodySlot)
            {
                slotRange = null;
            }
            slots.RemoveAt(idx);
        }
    }
References slotMainHand, slotOffHand, slotRange, slots, BodySlot.thing, and Unequip().
Referenced by RemoveBodyPart(), and Chara.RemoveLastBodyPart().
SetBodyIndexText()
void CharaBody.SetBodyIndexText (BodySlot b, UIText t) inline
Definition at line 481 of file CharaBody.cs.
    {
        if (!t)
        {
            return;
        }
        if (b.indexPart == 0)
        {
            int num = 0;
            foreach (BodySlot slot in slots)
            {
                if (slot.elementId == b.element.id)
                {
                    num++;
                }
                if (b == slot)
                {
                    break;
                }
            }
            b.indexPart = num;
        }
        if (b.elementId == 35)
        {
            t.SetText(b.indexPart.ToString() ?? "");
            t.SetActive(enable: true);
        }
        else
        {
            t.SetActive(enable: false);
        }
    }
References BodySlot.element, BodySlot.elementId, BodySlot.indexPart, UIText.SetText(), and slots.
Referenced by ButtonGrid.SetBodySlot().
SetOwner()
void CharaBody.SetOwner (Chara chara, bool deserialized = false) inline
Definition at line 18 of file CharaBody.cs.
    {
        owner = chara;
        if (!deserialized)
        {
            return;
        }
        if (rawSlots != null)
        {
            for (int i = 0; i < rawSlots.Length; i++)
            {
                AddBodyPart(rawSlots[i]);
            }
        }
        foreach (Thing thing in owner.things)
        {
            if (thing.isEquipped)
            {
                int num = thing.c_equippedSlot - 1;
                if (num < 0 || num >= slots.Count)
                {
                    thing.c_equippedSlot = 0;
                    continue;
                }
                slots[num].thing = thing;
                thing.elements.SetParent(owner);
                thing.trait.OnEquip(owner, onSetOwner: true);
            }
        }
    }
References AddBodyPart(), Card.elements, Thing.isEquipped, Trait.OnEquip(), owner, rawSlots, ElementContainer.SetParent(), slots, Card.things, and Card.trait.
Referenced by Chara.OnCreate(), and Chara.OnDeserialized().
Unequip() [1/2]
void CharaBody.Unequip (BodySlot slot, bool refresh = true) inline
Definition at line 68 of file CharaBody.cs.
    {
        if (slot.thing == null)
        {
            return;
        }
        Thing thing = slot.thing;
        if (EClass.pc != null)
        {
            EClass.pc.faction.charaElements.OnUnequip(owner, thing);
        }
        thing.elements.SetParent();
        thing.trait.OnUnequip(owner);
        thing.c_equippedSlot = 0;
        slot.thing = null;
        if (owner.IsPC)
        {
            if (refresh)
            {
                LayerChara.Refresh();
            }
            WidgetEquip.SetDirty();
        }
        LayerInventory.SetDirty(thing);
        if (slot.elementId == 45 && EClass.core.IsGameStarted)
        {
            owner.RecalculateFOV();
        }
        if (refresh && owner.isCreated && EClass.core.IsGameStarted)
        {
            owner.Refresh();
            if (slot.elementId == 37 && owner.HasElement(1209) && !thing.HasElement(419))
            {
                owner.Say("tail_free", owner);
            }
        }
    }
References Faction.charaElements, EClass.core, BodySlot.elementId, Card.elements, Chara.faction, Card.HasElement(), Chara.isCreated, Core.IsGameStarted, Chara.IsPC, Trait.OnUnequip(), ElementContainerFaction.OnUnequip(), owner, EClass.pc, Card.RecalculateFOV(), LayerChara.Refresh(), Chara.Refresh(), Card.Say(), WidgetEquip.SetDirty(), LayerInventory.SetDirty(), ElementContainer.SetParent(), BodySlot.thing, and Card.trait.
Unequip() [2/2]
void CharaBody.Unequip (Thing thing, bool refresh = true) inline
Definition at line 49 of file CharaBody.cs.
    {
        if (thing.isEquipped)
        {
            Unequip(slots[thing.c_equippedSlot - 1], refresh);
        }
    }
References Card.c_equippedSlot, Thing.isEquipped, slots, and Unequip().
Referenced by CoreDebug.ChangeRace(), Equip(), InvOwner.Grab(), Player.OnStartNewGame(), HotItemEQSet.Perform(), RemoveBodyPartAt(), Card.RemoveThing(), Unequip(), UnequipAll(), and UnqeuipIfTooHeavy().
UnequipAll()
void CharaBody.UnequipAll (int idSlot) inline
Definition at line 57 of file CharaBody.cs.
    {
        foreach (BodySlot slot in slots)
        {
            if (slot.elementId == idSlot)
            {
                Unequip(slot);
            }
        }
    }
References BodySlot.elementId, slots, and Unequip().
Referenced by Feat.Apply().
UnqeuipIfTooHeavy()
void CharaBody.UnqeuipIfTooHeavy (Thing t) inline
Definition at line 165 of file CharaBody.cs.
    {
        if (t.isEquipped)
        {
            _ = slots[t.c_equippedSlot - 1];
            if (IsTooHeavyToEquip(t))
            {
                owner.Say("tooHeavyToEquip", t);
                Unequip(t);
            }
        }
        if (!owner.IsPC && !t.isEquipped)
        {
            owner.TryEquip(t);
        }
    }
References Thing.isEquipped, Chara.IsPC, IsTooHeavyToEquip(), owner, Card.Say(), slots, Chara.TryEquip(), and Unequip().
Referenced by ActEffect.Proc().
Member Data Documentation
owner
Chara CharaBody.owner
Definition at line 6 of file CharaBody.cs.
Referenced by Equip(), GetMeleeDistance(), GetSortVal(), IsEquippable(), IsTooHeavyToEquip(), SetOwner(), Unequip(), and UnqeuipIfTooHeavy().
slotMainHand
BodySlot CharaBody.slotMainHand
Definition at line 10 of file CharaBody.cs.
Referenced by AddBodyPart(), Equip(), CharaActorPCC.OnRender(), RefreshBodyParts(), RemoveBodyPartAt(), Chara.RestockEquip(), Chara.ShouldEquip(), and Chara.TryEquip().
slotOffHand
BodySlot CharaBody.slotOffHand
Definition at line 12 of file CharaBody.cs.
Referenced by AddBodyPart(), Equip(), CharaActorPCC.OnRender(), RefreshBodyParts(), and RemoveBodyPartAt().
slotRange
BodySlot CharaBody.slotRange
Definition at line 14 of file CharaBody.cs.
Referenced by AddBodyPart(), RefreshBodyParts(), and RemoveBodyPartAt().
slots
List<BodySlot> CharaBody.slots = new List<BodySlot>()
Definition at line 8 of file CharaBody.cs.
Referenced by Thing.AddAttackEvaluation(), AddBodyPart(), ActMelee.Attack(), CoreDebug.ChangeRace(), DragItemCard.DragInfo.DragInfo(), GetAttackIndex(), GetAttackStyle(), Element.GetCost(), GetEquippedThing(), GetMeleeDistance(), GetSlot(), GetSortVal(), GetWeight(), TraitFoodEggFertilized.Incubate(), Chara.OnSerializing(), Player.OnStartNewGame(), TraitAmmo.OnUse(), TraitMannequin.OnUse(), HotItemEQSet.Perform(), AttackProcess.ProcShieldEncs(), RefreshBodyParts(), WindowCharaMini.RefreshEquipment(), LayerEquip.RefreshEquipment(), WidgetEquip.RefreshEquipment(), WindowChara.RefreshEquipment(), HotItemEQSet.Register(), RemoveBodyPart(), RemoveBodyPartAt(), Chara.RemoveLastBodyPart(), Chara.ResetBody(), SetBodyIndexText(), ButtonElement.SetGrid(), SetOwner(), Unequip(), UnequipAll(), UnqeuipIfTooHeavy(), and Element.BonusInfo.WriteNote().
Property Documentation
rawSlots
int [] CharaBody.rawSlots get
Definition at line 16 of file CharaBody.cs.
Referenced by SetOwner().
The documentation for this class was generated from the following file:
Elin/CharaBody.cs