Elin Decompiled Documentation: ThingGen Class Reference
ThingGen Class Reference
Static Public Member Functions
static Thing _Create (string id, int idMat=-1, int lv=-1)
static Thing TestCreate ()
static Thing CreateCurrency (int a, string id="money")
static Thing CreateParcel (string idLang=null, params Thing[] things)
static Thing Create (string id, int idMat=-1, int lv=-1)
static Thing Create (string id, string idMat, int lv=-1)
static Thing CreateFromFilter (string id, int lv=-1)
static Thing CreateRawMaterial (SourceMaterial.Row m)
static Thing CreateFromCategory (string idCat, int lv=-1)
static Thing CreateFromTag (string idTag, int lv=-1)
static Thing CreateBill (int pay, bool tax)
static Thing CreateBlock (int id, int idMat)
static Thing CreateFloor (int id, int idMat, bool platform=false)
static Thing CreateObj (int id, int idMat)
static Thing CreateMap (string idSource=null, int lv=-1)
static Thing CreatePlan (int ele)
static Thing CreateRecipe (string id)
static Thing CreateSpellbook (string alias, int num=1)
static Thing CreateSpellbook (int ele, int num=1, int charge=-1)
static Thing CreateRedBook (string id, int num=1)
static Thing CreateSkillbook (int ele, int num=1)
static Thing CreateScroll (int ele, int num=1)
static Thing Createジュアさまの薄い本 ()
static Thing CreateUsuihon (Religion faith)
static Thing CreateRune (int ele, int v, bool free=false)
static Thing CreateRod (int ele, int charge=-1)
static Thing CreatePotion (int ele, int num=1)
static Thing CreatePerfume (int ele, int num=1)
static Thing CreateCassette (int id)
static Thing CreateLetter (string idLetter)
static Thing CreateCardboardBox (int uidZone=-1)
static Thing CreateTreasure (string id, int lv, TreasureType type=TreasureType.Map)
static void CreateTreasureContent (Thing t, int lv, TreasureType type, bool clearContent)
static void TryLickChest (Thing chest)
Static Public Member Functions inherited from EClass
static int rndSeed (int a, int seed)
static int rnd (long a)
static int rnd (int a)
static int curve (int _a, int start, int step, int rate=75)
static int sqrt (int a)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Additional Inherited Members
Static Public Attributes inherited from EClass
static Core core
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Detailed Description
Definition at line 4 of file ThingGen.cs.
Member Function Documentation
_Create()
static Thing ThingGen._Create (string id, int idMat = -1, int lv = -1) inline static
Definition at line 6 of file ThingGen.cs.
    {
        Thing thing = new Thing();
        CardRow s = EClass.sources.cards.map.TryGetValue(id);
        if (s == null)
        {
            Debug.LogError("exception: Item not found:" + id);
            id = "869";
            s = EClass.sources.cards.map.TryGetValue(id);
        }
        if (s.isOrigin)
        {
            id = SpawnListThing.Get("origin_" + id, (SourceThing.Row a) => a.origin == s).Select(lv)?.id ?? EClass.sources.cards.rows.Where((CardRow a) => a.origin == s).First().id;
        }
        if (lv < 1)
        {
            lv = 1;
        }
        thing.Create(id, idMat, lv);
        if (thing.trait is TraitAmmo)
        {
            thing.SetNum(EClass.rnd(20) + 10);
        }
        return thing;
    }
References SourceManager.cards, Card.Create(), Debug, SpawnListThing.Get(), CardRow.id, CardRow.isOrigin, SourceCard.map, CardRow.origin, EClass.rnd(), SourceCard.rows, SpawnList.Select(), Card.SetNum(), EClass.sources, and Card.trait.
Referenced by Create(), CreateFromCategory(), CreateFromFilter(), CreateFromTag(), and TestCreate().
Createジュアさまの薄い本()
static Thing ThingGen.Createジュアさまの薄い本 () inline static
Definition at line 189 of file ThingGen.cs.
    {
        return CreateUsuihon(EClass.game.religions.Healing);
    }
References CreateUsuihon(), EClass.game, ReligionManager.Healing, and Game.religions.
Referenced by ReligionManager.ジュアさまの薄い本をください().
Create() [1/2]
static Thing ThingGen.Create (string id, int idMat = -1, int lv = -1) inline static
Definition at line 53 of file ThingGen.cs.
    {
        return _Create(id, idMat, lv);
    }
References _Create().
Referenced by Game._Create(), InvOwnerRecycle._OnProcess(), TraitGodStatue._OnUse(), TraitShrine._OnUse(), Card.Add(), ThingContainer.AddCurrency(), Card.AddThing(), Zone.AddThing(), GameDate.AdvanceDay(), GameDate.AdvanceYear(), RecipeCard.Build(), DropdownGrid.BuildIngredients(), Map.Burn(), AI_Shopping.Buy(), Zone.ClaimZone(), DramaOutcome.convert_Jure(), TraitCrafter.Craft(), RecipeCard.Craft(), Create(), CreateBill(), CreateBlock(), SourceMaterial.Row.CreateByProduct(), CreateCardboardBox(), CreateCassette(), CreateCurrency(), InvOwner.CreateDefaultContainer(), InvOwnerChangeMaterial.CreateDefaultContainer(), Player.CreateEquip(), CreateFloor(), CreateLetter(), CreateMap(), RecipeCard.CreateMold(), CreateObj(), CreateParcel(), CreatePerfume(), CreatePlan(), CreatePotion(), CreateRawMaterial(), CreateRecipe(), CreateRedBook(), CreateRod(), CreateRune(), CreateScroll(), CreateSkillbook(), CreateSpellbook(), Trait.CreateStock(), CreateTreasure(), CreateTreasureContent(), CreateUsuihon(), FactionBranch.DailyOutcome(), QuestDeliver.Deliver(), Card.Die(), Chara.DoHostileAction(), Map.DropBlockComponent(), Recipe.DropIngredients(), Quest.DropReward(), Card.Duplicate(), DramaOutcome.duponne_capture(), DramaOutcome.duponne_reward(), Card.EjectSockets(), Chara.EQ_ID(), Chara.EQ_Item(), ZonePreEnterBoutWin.Execute(), ZonePreEnterDigStairs.Execute(), DramaOutcome.fiama_gold(), DramaOutcome.fiama_starter_gift(), AI_Fuck.Finish(), CoreDebug.Fix_LostCore(), Zone.Generate(), FactionBranch.GenerateGarbage(), DNA.GenerateGene(), Zone_SnowGrave.GenerateGrave(), DramaOutcome.get_scratch(), FactionBranch.GetDailyIncome(), AI_Shear.GetFur(), FortuneRollData.GetPrize(), CraftUtil.GetRandomLoveLunchIngredient(), MiniGame.GetSlotReward(), DramaOutcome.give_sketch_reward(), QuestDebt.GiveBill(), QuestDebt.GiveReward(), TaskHarvest.HarvestThing(), DramaOutcome.ListFelmeraBarter(), CraftUtil.MakeBloodSample(), CraftUtil.MakeDarkSoup(), CraftUtil.MakeDish(), Card.MakeEgg(), AI_Fish.Makefish(), Chara.MakeGrave(), CraftUtil.MakeLoveLunch(), Card.MakeMilk(), TraitSeed.MakeRandomSeed(), AI_OpenGambleChest.MakeReward(), TraitSeed.MakeSeed(), SurvivalManager.MeteorThing(), Map.MineBlock(), Map.MineObj(), CraftUtil.MixIngredients(), Chara.MutateRandom(), DramaOutcome.nerun_gift(), DramaOutcome.nerun_gift2(), DramaOutcome.nerun_gift3(), Zone_Void.OnActivate(), Faction.OnAdvanceMonth(), Trait.OnBarter(), QuestVernis.OnChangePhase(), TraitBrewery.OnChildDecay(), ContentCodex.OnClickGetCard(), QuestNasu.OnComplete(), FactionBranch.OnCreate(), TaskChopWood.OnCreateProgress(), TaskHarvest.OnCreateProgress(), QuestCraft.OnDropReward(), QuestDefense.OnDropReward(), QuestRandom.OnDropReward(), SurvivalManager.OnExpandFloor(), Zone_TestRoom.OnGenerateMap(), MapGenDungen.OnGenerateTerrain(), GrowSystem.OnMineObj(), GrowSystemFlower.OnMineObj(), GrowSystemHerb.OnMineObj(), GrowSystemWeed.OnMineObj(), GrowSystemWheat.OnMineObj(), SurvivalManager.OnMineWreck(), QuestCraft.OnProgressComplete(), TaskDig.OnProgressComplete(), TaskMine.OnProgressComplete(), FactionBranch.OnSimulateDay(), QuestDeliver.OnStart(), QuestFiamaLock.OnStart(), TraitGiftJure.OnUse(), TraitGiftNewYear.OnUse(), TraitGiftPack.OnUse(), TraitPlamoBox.OnUse(), TraitStairsLocked.OnUse(), TraitPotionEmpty.OnUse(), ZoneEventDefenseGame.OnVisit(), DramaManager.ParseLine(), InvOwnerDeliver.PayBill(), ActDreamBug.Perform(), Chara.PickOrDrop(), Zone_Dungeon.PlaceRail(), TraitGacha.PlayGacha(), GrowSystem.PopHarvest(), GenRoom.Populate(), TraitBaseContainer.Prespawn(), TraitContainerCurrency.Prespawn(), TraitToolBelt.Prespawn(), FoodEffect.Proc(), ActEffect.Proc(), Religion.Punish(), Religion.PunishTakeOver(), DramaOutcome.PutOutFire(), DramaOutcome.QuestDefense_1(), DramaOutcome.QuestSharedContainer_Drop1(), CoreDebug.QuickStart(), FactionBranch.ReceivePackages(), Religion.Reforge(), CoreDebug.Reset_LoytelDebt(), Chara.RestockEquip(), Chara.RestockInventory(), SerializedCards.Restore(), AI_Craft_Snowman.Run(), AI_Idle.Run(), AI_OpenGambleChest.Run(), AI_PlayMusic.Run(), AI_Steal.Run(), TaskCullLife.Run(), CoreDebug.SetStartStockpile(), GameDate.ShipGoods(), GameDate.ShipLetter(), GameDate.ShipRandomPackages(), Chara.ShowDialog(), CoreDebug.Spawn(), Zone.SpawnAltar(), Card.SpawnLoot(), Zone.SpawnLostItems(), SurvivalManager.StartRaid(), AI_PlayMusic.ThrowReward(), BiomeProfile.ClusterThing.TryCreate(), TraitSwitch.TryDisarmTrap(), Chara.TryDropBossLoot(), Zone.TryGenerateShrine(), Recipe.TryGetFirstTimeBonus(), GrowSystem.TryPick(), Chara.TryPoisonPotion(), Map.TryShatter(), DramaOutcome.Tutorial1(), TraitFoodEgg.Update(), TraitSpotBiome.Update(), ActionMode.UpdateInput(), CoreDebug.UpdateInput(), Chara.Vomit(), and ActEffect.Wish().
Create() [2/2]
static Thing ThingGen.Create (string id, string idMat, int lv = -1) inline static
Definition at line 58 of file ThingGen.cs.
    {
        return Create(id, idMat.IsEmpty() ? (-1) : EClass.sources.materials.alias[idMat].id, lv);
    }
References Create(), SourceManager.materials, and EClass.sources.
CreateBill()
static Thing ThingGen.CreateBill (int pay, bool tax) inline static
Definition at line 85 of file ThingGen.cs.
    {
        Thing thing = Create(tax ? "bill_tax" : "bill");
        thing.c_bill = pay;
        if (tax)
        {
            EClass.player.stats.taxBills += thing.c_bill;
            EClass.player.taxBills++;
        }
        else
        {
            EClass.player.unpaidBill += thing.c_bill;
        }
        return thing;
    }
References Card.c_bill, Create(), EClass.player, and Player.taxBills.
Referenced by Faction.OnAdvanceMonth(), and GameDate.ShipPackages().
CreateBlock()
static Thing ThingGen.CreateBlock (int id, int idMat) inline static
Definition at line 101 of file ThingGen.cs.
    {
        Thing thing = Create(EClass.sources.blocks.rows[id].idThing, idMat);
        thing.refVal = id;
        return thing;
    }
References SourceManager.blocks, Create(), and EClass.sources.
Referenced by Recipe.Craft(), Map.DropBlockComponent(), and CoreDebug.QuickStart().
CreateCardboardBox()
static Thing ThingGen.CreateCardboardBox (int uidZone = -1) inline static
Definition at line 244 of file ThingGen.cs.
    {
        Thing thing = Create("cardboard_box", new string[5] { "pine", "wood_birch", "wood_acacia", "oak", "cedar" }.RandomItem());
        thing.things.DestroyAll();
        Spatial spatial = ((uidZone == -1) ? null : EClass.game.spatials.map.TryGetValue(uidZone));
        if (spatial != null)
        {
            thing.c_idRefName = "sender_header".lang("sender_post".lang(spatial.Name));
        }
        return thing;
    }
References Create(), ThingContainer.DestroyAll(), EClass.game, SpatialManager.map, Spatial.Name, Game.spatials, and Card.things.
Referenced by GameDate.ShipPackages(), and GameDate.ShipRandomPackages().
CreateCassette()
static Thing ThingGen.CreateCassette (int id) inline static
Definition at line 230 of file ThingGen.cs.
    {
        Thing thing = Create("856");
        thing.refVal = id;
        return thing;
    }
References Create().
Referenced by QuestCurry.OnComplete(), and QuestDebt.OnStart().
CreateCurrency()
static Thing ThingGen.CreateCurrency (int a, string id = "money") inline static
Definition at line 37 of file ThingGen.cs.
    {
        return Create(id).SetNum(a);
    }
References Create(), and Card.SetNum().
Referenced by Chara.ApplyDeathPenalty(), Player.CreateEquip(), QuestRandom.OnDropReward(), and TraitFarmChest.OnUse().
CreateFloor()
static Thing ThingGen.CreateFloor (int id, int idMat, bool platform = false) inline static
Definition at line 108 of file ThingGen.cs.
    {
        _ = EClass.sources.floors.rows[id];
        Thing thing = Create(platform ? "platform" : "floor", idMat);
        thing.refVal = id;
        return thing;
    }
References Create(), SourceManager.floors, and EClass.sources.
Referenced by Recipe.Craft(), Map.DropBlockComponent(), SurvivalManager.OnMineWreck(), and CoreDebug.QuickStart().
CreateFromCategory()
static Thing ThingGen.CreateFromCategory (string idCat, int lv = -1) inline static
Definition at line 75 of file ThingGen.cs.
    {
        return _Create(SpawnListThing.Get("cat_" + idCat, (SourceThing.Row s) => EClass.sources.categories.map[s.category].IsChildOf(idCat)).Select(lv).id, -1, lv);
    }
References _Create(), SourceManager.categories, SpawnListThing.Get(), CardRow.id, SpawnList.Select(), and EClass.sources.
Referenced by DropdownGrid.BuildIngredients(), TraitCrafter.Craft(), CreateTreasureContent(), FactionBranch.DailyOutcome(), Chara.EQ_CAT(), FactionBranch.GenerateGarbage(), TaskHarvest.HarvestThing(), CraftUtil.MakeBloodMeal(), Trait.OnBarter(), TaskHarvest.OnCreateProgress(), MapGenDungen.OnGenerateTerrain(), GrowSystemKinoko.OnMineObj(), GrowSystem.PopHarvest(), TraitBaseContainer.Prespawn(), TraitBaseContainer.PutChara(), CoreDebug.QuickStart(), Chara.RestockEquip(), AI_Idle.Run(), GameDate.ShipRandomPackages(), Card.SpawnLoot(), and Zone.SpawnLostItems().
CreateFromFilter()
static Thing ThingGen.CreateFromFilter (string id, int lv = -1) inline static
Definition at line 63 of file ThingGen.cs.
    {
        return _Create(SpawnList.Get(id).Select(lv).id, -1, lv);
    }
References _Create(), SpawnList.Get(), CardRow.id, and SpawnList.Select().
Referenced by Trait.CreateStock(), CreateTreasureContent(), CraftUtil.GetRandomDarkSoupIngredient(), QuestDefenseGame.OnInit(), SurvivalManager.OnMineWreck(), TraitBaseContainer.Prespawn(), SerializedCards.Restore(), AI_Steal.Run(), and Card.SpawnLoot().
CreateFromTag()
static Thing ThingGen.CreateFromTag (string idTag, int lv = -1) inline static
Definition at line 80 of file ThingGen.cs.
    {
        return _Create(SpawnListThing.Get("tag_" + idTag, (SourceThing.Row s) => s.tag.Contains(idTag)).Select(lv).id, -1, lv);
    }
References _Create(), SpawnListThing.Get(), CardRow.id, and SpawnList.Select().
Referenced by FactionBranch.GenerateGarbage(), and GameDate.ShipRandomPackages().
CreateLetter()
static Thing ThingGen.CreateLetter (string idLetter) inline static
Definition at line 237 of file ThingGen.cs.
    {
        Thing thing = Create("letter");
        thing.SetStr(53, idLetter);
        return thing;
    }
References Create(), and BaseCard.SetStr().
Referenced by TraitGiftJure.OnUse().
CreateMap()
static Thing ThingGen.CreateMap (string idSource = null, int lv = -1) inline static
Definition at line 124 of file ThingGen.cs.
    {
        if (idSource.IsEmpty())
        {
            idSource = EClass.game.world.region.GetRandomSiteSource().id;
        }
        if (lv == -1)
        {
            lv = 1 + EClass.rnd(EClass.rnd(50) + 1);
        }
        return Create("map");
    }
References Create(), EClass.game, Region.GetRandomSiteSource(), World.region, EClass.rnd(), and Game.world.
Referenced by Trait.CreateStock().
CreateObj()
static Thing ThingGen.CreateObj (int id, int idMat) inline static
Definition at line 116 of file ThingGen.cs.
    {
        _ = EClass.sources.objs.rows[id];
        Thing thing = Create("obj", idMat);
        thing.refVal = id;
        return thing;
    }
References Create(), SourceManager.objs, and EClass.sources.
Referenced by Recipe.Craft().
CreateParcel()
static Thing ThingGen.CreateParcel (string idLang = null, params Thing[] things) inline static
Definition at line 42 of file ThingGen.cs.
    {
        Thing thing = Create("parcel");
        foreach (Thing c in things)
        {
            thing.AddCard(c);
        }
        thing.c_idRefName = idLang.lang();
        return thing;
    }
References Create().
Referenced by GameDate.AdvanceDay(), Chara.MutateRandom(), Faction.OnAdvanceMonth(), SurvivalManager.OnMineWreck(), and InvOwnerDeliver.PayBill().
CreatePerfume()
static Thing ThingGen.CreatePerfume (int ele, int num = 1) inline static
Definition at line 223 of file ThingGen.cs.
    {
        Thing thing = Create("perfume").SetNum(num);
        TraitPotion.Create(thing, ele);
        return thing;
    }
References TraitPotion.Create(), Create(), and Card.SetNum().
Referenced by Trait.OnBarter().
CreatePlan()
static Thing ThingGen.CreatePlan (int ele) inline static
Definition at line 137 of file ThingGen.cs.
    {
        Thing thing = Create("book_plan");
        thing.refVal = ele;
        return thing;
    }
References Create().
Referenced by Trait.OnBarter().
CreatePotion()
static Thing ThingGen.CreatePotion (int ele, int num = 1) inline static
Definition at line 216 of file ThingGen.cs.
    {
        Thing thing = Create("1163").SetNum(num);
        TraitPotion.Create(thing, ele);
        return thing;
    }
References TraitPotion.Create(), Create(), and Card.SetNum().
Referenced by Trait.CreateStock(), Trait.OnBarter(), and QuestVernis.OnChangePhase().
CreateRawMaterial()
static Thing ThingGen.CreateRawMaterial (SourceMaterial::Row m) inline static
Definition at line 68 of file ThingGen.cs.
    {
        Thing thing = Create(m.thing);
        thing.ChangeMaterial(m.id);
        return thing;
    }
References Card.ChangeMaterial(), and Create().
Referenced by SourceMaterial.Row.CreateByProduct(), Map.MineFloor(), and DramaOutcome.QuestCraft_Drop1().
CreateRecipe()
static Thing ThingGen.CreateRecipe (string id) inline static
Definition at line 144 of file ThingGen.cs.
    {
        Thing thing = Create("rp_random");
        thing.SetStr(53, id);
        return thing;
    }
References Create(), and BaseCard.SetStr().
Referenced by Player.CreateEquip(), DramaOutcome.duponne_reward(), DramaOutcome.give_catball_recipe(), Trait.OnBarter(), QuestCrafter.OnDropReward(), QuestDialog.OnDropReward(), SurvivalManager.OnMineWreck(), TraitGiftJure.OnUse(), and DramaOutcome.QuestVernis_DropRecipe().
CreateRedBook()
static Thing ThingGen.CreateRedBook (string id, int num = 1) inline static
Definition at line 167 of file ThingGen.cs.
    {
        Thing thing = Create("book").SetNum(num);
        thing.SetStr(53, id);
        thing.idSkin = (thing.trait as TraitBook).Item.skin;
        return thing;
    }
References Create(), Item, Card.SetNum(), and BaseCard.SetStr().
Referenced by Player.CreateEquip(), DramaOutcome.duponne_reward(), Trait.OnBarter(), and CoreDebug.QuickStart().
CreateRod()
static Thing ThingGen.CreateRod (int ele, int charge = -1) inline static
Definition at line 209 of file ThingGen.cs.
    {
        Thing thing = Create("rod");
        TraitRod.Create(thing, ele, charge);
        return thing;
    }
References TraitRod.Create(), and Create().
Referenced by Trait.CreateStock(), and SurvivalManager.OnMineWreck().
CreateRune()
static Thing ThingGen.CreateRune (int ele, int v, bool free = false) inline static
Definition at line 201 of file ThingGen.cs.
    {
        Thing thing = Create(free ? "rune_free" : "rune");
        thing.refVal = ele;
        thing.encLV = v;
        return thing;
    }
References Create().
Referenced by Trait.OnBarter().
CreateScroll()
static Thing ThingGen.CreateScroll (int ele, int num = 1) inline static
Definition at line 182 of file ThingGen.cs.
    {
        Thing thing = Create("scroll_random").SetNum(num);
        TraitSpellbook.Create(thing, ele);
        return thing;
    }
References TraitSpellbook.Create(), Create(), and Card.SetNum().
Referenced by InvOwnerEnchant.CreateDefaultContainer(), InvOwnerIdentify.CreateDefaultContainer(), InvOwnerLighten.CreateDefaultContainer(), InvOwnerReconstruction.CreateDefaultContainer(), InvOwnerUncurse.CreateDefaultContainer(), Trait.CreateStock(), Trait.OnBarter(), QuestCompanion.OnDropReward(), DramaOutcome.QuestExploration_AfterCrystal(), DramaOutcome.QuestExploration_Drop1(), and Chara.TryDropBossLoot().
CreateSkillbook()
static Thing ThingGen.CreateSkillbook (int ele, int num = 1) inline static
Definition at line 175 of file ThingGen.cs.
    {
        Thing thing = Create("book_skill").SetNum(num);
        thing.refVal = ele;
        return thing;
    }
References Create(), and Card.SetNum().
Referenced by Trait.OnBarter().
CreateSpellbook() [1/2]
static Thing ThingGen.CreateSpellbook (int ele, int num = 1, int charge = -1) inline static
Definition at line 156 of file ThingGen.cs.
    {
        Thing thing = Create("spellbook").SetNum(num);
        TraitSpellbook.Create(thing, ele);
        if (charge != -1)
        {
            thing.SetCharge(charge);
        }
        return thing;
    }
References TraitSpellbook.Create(), Create(), Card.SetCharge(), and Card.SetNum().
CreateSpellbook() [2/2]
static Thing ThingGen.CreateSpellbook (string alias, int num = 1) inline static
Definition at line 151 of file ThingGen.cs.
    {
        return CreateSpellbook(EClass.sources.elements.alias[alias].id, num);
    }
References CreateSpellbook(), SourceManager.elements, and EClass.sources.
Referenced by Player.CreateEquip(), CreateSpellbook(), Trait.CreateStock(), Trait.OnBarter(), and Chara.RestockEquip().
CreateTreasure()
static Thing ThingGen.CreateTreasure (string id, int lv, TreasureType type = TreasureType::Map) inline static
Definition at line 256 of file ThingGen.cs.
    {
        Thing thing = Create(id, -1, lv);
        CreateTreasureContent(thing, lv, type, clearContent: true);
        return thing;
    }
References Create(), and CreateTreasureContent().
Referenced by FactionBranch.DailyOutcome(), ZoneEventSiege.OnKill(), and Chara.TryDropBossLoot().
CreateTreasureContent()
static void ThingGen.CreateTreasureContent (Thing t, int lv, TreasureType type, bool clearContent) inline static
Definition at line 263 of file ThingGen.cs.
    {
        int miracleChance = lv;
        int num = EClass.curve(lv, 20, 15);
        bool flag = true;
        bool flag2 = true;
        int guaranteedMythical = ((type == TreasureType.BossQuest) ? 1 : 0);
        ChangeSeed();
        t.AddEditorTag(EditorTag.PreciousContainer);
        if (clearContent)
        {
            t.things.DestroyAll();
        }
        switch (type)
        {
        case TreasureType.Map:
            miracleChance += 50;
            t.Add("money", EClass.rndHalf(1000 + num * 100));
            t.Add("money2", EClass.rndHalf(Mathf.Min(3 + num / 10, 10)));
            t.Add("medal", EClass.rnd(3));
            break;
        case TreasureType.BossNefia:
        case TreasureType.BossQuest:
            t.Add("money", EClass.rndHalf(500 + num * 50));
            t.Add("plat", EClass.rndHalf(Mathf.Min(3 + num / 10, 15)));
            t.Add("rp_random", 1, lv);
            if (EClass.rnd(5) == 0)
            {
                t.Add("medal", EClass.rnd(3));
            }
            else if (EClass.rnd(3) == 0)
            {
                t.Add("map_treasure", 1, EClass.rndHalf(lv + 10));
            }
            else
            {
                t.Add("book_skill", 1, lv);
            }
            t.c_lockLv /= 2;
            break;
        case TreasureType.SurvivalRaid:
            t.Add("plat", EClass.rndHalf(Mathf.Min(3 + num / 10, 15)));
            t.Add("money2", EClass.rndHalf(Mathf.Min(3 + num / 10, 10)));
            t.Add("medal", EClass.rndHalf(8));
            t.Add("book_skill", 1, lv);
            t.Add("book_skill", 1, lv);
            t.c_lockLv /= 3;
            break;
        case TreasureType.RandomChest:
            flag2 = false;
            miracleChance /= 2;
            if (miracleChance > 50)
            {
                miracleChance = 50;
            }
            if (EClass.rnd(2) == 0)
            {
                t.Add("money", EClass.rndHalf(10 + num * 25));
            }
            else if (EClass.rnd(2) == 0)
            {
                t.Add("money2", 1 + EClass.rnd(Mathf.Min(2 + num / 25, 5)));
            }
            else
            {
                t.Add("plat", 1 + EClass.rnd(Mathf.Min(2 + num / 25, 5)));
            }
            if (EClass._zone is Zone_Civilized)
            {
                flag = false;
                break;
            }
            if (EClass.rnd(10) == 0)
            {
                t.Add("map_treasure", 1, EClass.rndHalf(lv + 10));
            }
            if (EClass.rnd(3) == 0)
            {
                t.AddCard(Create("rp_random", -1, lv));
            }
            if (t.c_lockLv > 0 && EClass.rnd(3) == 0)
            {
                t.Add("medal");
            }
            break;
        }
        if (type == TreasureType.RandomChest && EClass.rnd(2) == 0)
        {
            t.AddCard(CreateFromCategory("junk", lv));
        }
        else if (EClass.rnd(3) == 0)
        {
            t.Add("rp_random", 1, lv);
        }
        else if (type != TreasureType.Map && EClass.rnd(2) == 0)
        {
            Thing thing = CreateFromCategory("furniture", lv);
            if (!thing.IsContainer && (t.c_lockLv == 0 || thing.SelfWeight < 10000))
            {
                t.AddCard(thing);
            }
        }
        else
        {
            t.AddCard(CreateFromCategory("junk", lv));
        }
        if (EClass.rnd(3) == 0)
        {
            t.Add("book_ancient", 1, lv);
        }
        if (t.c_lockLv > 0)
        {
            miracleChance += 20 + (int)Mathf.Sqrt(t.c_lockLv * 5);
        }
        if (flag)
        {
            SetRarity(100);
            t.AddCard(CreateFromFilter("eq", lv));
            if (flag2)
            {
                SetRarity(20);
                t.AddCard(CreateFromFilter("eq", lv));
            }
        }
        Rand.SetSeed();
        static void ChangeSeed()
        {
            EClass.player.seedChest++;
            Rand.SetSeed(EClass.game.seed + EClass.player.seedChest);
        }
        void SetRarity(int mtp)
        {
            ChangeSeed();
            Rarity rarity = ((miracleChance * mtp / 100 < EClass.rnd(100)) ? Rarity.Superior : ((EClass.rnd(20) == 0) ? Rarity.Mythical : Rarity.Legendary));
            if (guaranteedMythical > 0)
            {
                guaranteedMythical--;
                rarity = Rarity.Mythical;
            }
            CardBlueprint.Set(new CardBlueprint
            {
                rarity = rarity
            });
        }
    }
References EClass._zone, Card.Add(), Card.AddCard(), Card.AddEditorTag(), Card.c_lockLv, Create(), CreateFromCategory(), CreateFromFilter(), EClass.curve(), ThingContainer.DestroyAll(), EClass.game, Card.IsContainer, EClass.player, EClass.rnd(), EClass.rndHalf(), Game.seed, Player.seedChest, Thing.SelfWeight, CardBlueprint.Set(), Rand.SetSeed(), and Card.things.
Referenced by CreateTreasure(), Trait.OnBarter(), SurvivalManager.OnMineWreck(), TraitChest.Prespawn(), TraitChestOyster.Prespawn(), and TraitCoffin.Prespawn().
CreateUsuihon()
static Thing ThingGen.CreateUsuihon (Religion faith) inline static
Definition at line 194 of file ThingGen.cs.
    {
        Thing thing = Create("1084");
        thing.c_idRefName = EClass.game.religions.Healing.id;
        return thing;
    }
References Create(), EClass.game, ReligionManager.Healing, ReligionHealing.id, and Game.religions.
Referenced by Createジュアさまの薄い本().
TestCreate()
static Thing ThingGen.TestCreate () inline static
Definition at line 32 of file ThingGen.cs.
    {
        return _Create(SpawnList.Get("thing").Select().id);
    }
References _Create(), SpawnList.Get(), CardRow.id, and SpawnList.Select().
Referenced by CoreDebug.UpdateInput().
TryLickChest()
static void ThingGen.TryLickChest (Thing chest) inline static
Definition at line 409 of file ThingGen.cs.
    {
        foreach (Chara chara in EClass._map.charas)
        {
            if (!chara.HasElement(1412) || chara.Dist(chest) >= 5)
            {
                continue;
            }
            chara.Say("lick", chara, chest);
            chest.PlaySound("offering");
            chest.PlayEffect("mutation");
            {
                foreach (Thing thing in chest.things)
                {
                    thing.TryLickEnchant(chara, msg: false);
                }
                break;
            }
        }
    }
References EClass._map, Map.charas, Card.Dist(), Card.HasElement(), Card.Say(), Card.things, and Thing.TryLickEnchant().
Referenced by Chara.TryDropBossLoot().
The documentation for this class was generated from the following file:
Elin/ThingGen.cs