Elin Decompiled Documentation: MsgBlock Class Reference
MsgBlock Class Reference
Public Member Functions
void Append (string s, Color col)
void Append (Sprite s, bool fitLine=false)
UIItem Load (string id)
void Reset ()
Public Attributes
int countElements
Image bg
LayoutGroup layout
CanvasGroup cg
MsgBox box
UIText txt
int repeat
Static Public Attributes
static MsgBlock lastBlock
static string lastText
Private Member Functions
void Awake ()
void AddElement (Component c, bool autoNewLine=true)
void AddElement (Component c, MsgBlock block)
Private Attributes
RectTransform rect
Detailed Description
Definition at line 5 of file MsgBlock.cs.
Member Function Documentation
AddElement() [1/2]
void MsgBlock.AddElement (Component c, bool autoNewLine = true) inline private
Definition at line 70 of file MsgBlock.cs.
    {
        if (rect.rect.width + c.Rect().rect.width > box.maxWidth)
        {
            box.CreateNewBlock();
        }
        AddElement(c, box.currentBlock);
    }
References AddElement(), box, MsgBox.CreateNewBlock(), MsgBox.currentBlock, MsgBox.maxWidth, and rect.
Referenced by AddElement(), Append(), and Load().
AddElement() [2/2]
void MsgBlock.AddElement (Component c, MsgBlock block) inline private
Definition at line 79 of file MsgBlock.cs.
    {
        c.transform.SetParent(block.transform, worldPositionStays: false);
        block.layout.RebuildLayout();
        countElements++;
    }
References block, and countElements.
Append() [1/2]
void MsgBlock.Append (Sprite s, bool fitLine = false) inline
Definition at line 46 of file MsgBlock.cs.
    {
        Transform transform = PoolManager.Spawn(box.prefabs.image, layout);
        Image componentInChildren = transform.GetComponentInChildren<Image>();
        componentInChildren.sprite = s;
        if (fitLine)
        {
            componentInChildren.Rect().sizeDelta = new Vector2(rect.sizeDelta.y, rect.sizeDelta.y);
        }
        else
        {
            componentInChildren.SetNativeSize();
        }
        transform.transform.Rect().sizeDelta = componentInChildren.Rect().sizeDelta;
        AddElement(transform);
    }
References AddElement(), box, MsgBox.Prefabs.image, layout, MsgBox.prefabs, rect, and PoolManager.Spawn().
Append() [2/2]
void MsgBlock.Append (string s, Color col) inline
Definition at line 35 of file MsgBlock.cs.
    {
        txt = PoolManager.Spawn(box.prefabs.text, layout);
        txt.SetText(s, col);
        txt.RebuildLayout();
        AddElement(txt);
        lastBlock = this;
        lastText = s;
        repeat = 0;
    }
References AddElement(), box, lastBlock, lastText, layout, MsgBox.prefabs, repeat, UIText.SetText(), PoolManager.Spawn(), MsgBox.Prefabs.text, and txt.
Referenced by MsgBox.Append().
Awake()
void MsgBlock.Awake () inline private
Definition at line 30 of file MsgBlock.cs.
    {
        rect = this.Rect();
    }
References rect.
Load()
UIItem MsgBlock.Load (string id) inline
Definition at line 63 of file MsgBlock.cs.
    {
        UIItem uIItem = UnityEngine.Object.Instantiate(ResourceCache.Load<UIItem>("UI/Element/Msg/" + id));
        AddElement(uIItem, autoNewLine: false);
        return uIItem;
    }
References AddElement().
Referenced by MsgBox.Load().
Reset()
void MsgBlock.Reset () inline
Definition at line 86 of file MsgBlock.cs.
    {
        for (int num = base.transform.childCount - 1; num >= 0; num--)
        {
            Transform child = base.transform.GetChild(num);
            if (!child.tag.Contains("IgnoreDestroy"))
            {
                PoolManager.DespawnOrDestroy(child);
            }
        }
        this.RebuildLayout();
    }
References PoolManager.DespawnOrDestroy().
Referenced by MsgBox.CreateNewBlock().
Member Data Documentation
bg
Image MsgBlock.bg
Definition at line 13 of file MsgBlock.cs.
Referenced by MsgBox.CreateNewBlock().
box
MsgBox MsgBlock.box
Definition at line 22 of file MsgBlock.cs.
Referenced by MsgLine.AddElement(), AddElement(), and Append().
cg
CanvasGroup MsgBlock.cg
Definition at line 17 of file MsgBlock.cs.
Referenced by MsgBox.ToggleLog().
countElements
int MsgBlock.countElements
Definition at line 11 of file MsgBlock.cs.
Referenced by AddElement(), and MsgBox.SetCurrentBlock().
lastBlock
MsgBlock MsgBlock.lastBlock static
Definition at line 7 of file MsgBlock.cs.
Referenced by Append(), and WidgetMainText.Append().
lastText
string MsgBlock.lastText static
Definition at line 9 of file MsgBlock.cs.
Referenced by Append(), and WidgetMainText.Append().
layout
LayoutGroup MsgBlock.layout
Definition at line 15 of file MsgBlock.cs.
Referenced by Append().
rect
RectTransform MsgBlock.rect private
Definition at line 19 of file MsgBlock.cs.
Referenced by AddElement(), Append(), and Awake().
repeat
int MsgBlock.repeat
Definition at line 28 of file MsgBlock.cs.
Referenced by Append(), and WidgetMainText.Append().
txt
UIText MsgBlock.txt
Definition at line 25 of file MsgBlock.cs.
Referenced by Append(), and WidgetMainText.Append().
The documentation for this class was generated from the following file:
Elin/Plugins.UI/MsgBlock.cs