Elin Decompiled Documentation: ContentHomeReport Class Reference
ContentHomeReport Class Reference
Public Member Functions
override void OnSwitchContent (int idTab)
void RefreshInfo ()
string GetTextHappiness (List< Chara > list)
void RefreshResources ()
Public Member Functions inherited from UIContent
virtual void OnSwitchContent (int idTab)
virtual void OnInstantiate ()
Public Member Functions inherited from UINote
void Clear ()
void Build ()
void Space (int sizeY=0, int sizeX=1)
UINote AddNote (string id)
UIItem AddHeader (string text, Sprite sprite=null)
UIItem AddHeaderCard (string text, Sprite sprite=null)
UIItem AddHeaderTopic (string text, Sprite sprite=null)
UIItem AddHeader (string id, string text, Sprite sprite=null)
UIItem AddText (string text, FontColor color=FontColor.DontChange)
UIItem AddText (string id, string text, FontColor color=FontColor.DontChange)
UIItem AddText (string id, string text, Color color)
UIItem AddItem (string id)
UIItem AddTopic (string id, string text, string value=null)
UIItem AddTopic (string text, string value=null)
void AddImage (Sprite sprite)
void AddImage (string idFile)
UIButton AddButton (string text, Action onClick)
UIButton AddButtonLink (string text, string url)
UIDropdown AddDropdown (string id="DropdownDefault")
UIButton AddToggle (string idLang="", bool isOn=false, Action< bool > action=null)
Transform AddPrefab (string path)
T AddExtra< T > (string path)
Public Attributes
UIText textName
UIText textRank
UIText textWealth
UIText textHearth
UIText textPopu
UIText textInfluence
UIText textKnowledge
UIText textHeaderReport
UIText textReknown
UIText textKarma
UIButton buttonHappinessResident
UIButton buttonHappinessLivestock
UIList listCurrencies
UIList listResources
Faction faction
FactionBranch branch
Zone zone
Public Attributes inherited from UINote
RectTransform target
UINoteProfile prof
SkinType skinType
string idDefaultText
LayoutGroup layout
RectTransform cur
bool extraRebuild
Properties
int tabResearch [get]
Detailed Description
Definition at line 3 of file ContentHomeReport.cs.
Member Function Documentation
GetTextHappiness()
string ContentHomeReport.GetTextHappiness (List< Chara > list) inline
Definition at line 70 of file ContentHomeReport.cs.
    {
        int num = 0;
        int num2 = 0;
        int num3 = 0;
        int num4 = 0;
        foreach (Chara item in list)
        {
            int happiness = item.GetHappiness();
            if (happiness >= 80)
            {
                num2++;
            }
            else if (happiness >= 30)
            {
                num3++;
            }
            else
            {
                num4++;
            }
            num += happiness;
        }
        int avg = ((list.Count != 0) ? (num / list.Count) : 0);
        string s = "(" + num2.ToString().TagColor(FontColor.Good) + "/" + num3.ToString().TagColor(FontColor.Default) + "/" + num4.ToString().TagColor(FontColor.Bad) + ")";
        return (((list.Count == 0) ? " - " : avg.ToString()) + "%").TagColorGoodBad(() => list.Count == 0 || avg >= 50) + " " + s.TagSize(14);
    }
References item.
OnSwitchContent()
override void ContentHomeReport.OnSwitchContent (int idTab) inline virtual
Reimplemented from UIContent.
Definition at line 41 of file ContentHomeReport.cs.
    {
        faction = EClass.pc.faction;
        branch = EClass.Branch ?? EClass.pc.homeZone.branch;
        zone = EClass.Branch?.owner ?? EClass.pc.homeZone;
    }
References branch, EClass.Branch, Zone.branch, Chara.faction, faction, Chara.homeZone, FactionBranch.owner, EClass.pc, and zone.
RefreshInfo()
void ContentHomeReport.RefreshInfo () inline
Definition at line 48 of file ContentHomeReport.cs.
    {
        textName.SetText(faction.name + " <size=13>" + "_branch".lang(zone.Name) + "</size>");
        textRank.SetText(branch.RankText);
        textReknown.SetText("0");
        textKarma.SetText("20");
        textPopu.SetText((branch.rank != 0) ? branch.faith.Name : "none".lang());
        textHeaderReport.text = "headerHomeReport".lang(EClass.world.date.year.ToString() ?? "", EClass.world.date.month + "/" + EClass.world.date.day);
        buttonHappinessResident.mainText.text = branch.happiness.residents.GetText();
        buttonHappinessLivestock.mainText.text = branch.happiness.livestocks.GetText();
        buttonHappinessResident.subText.text = branch.CountMembers(FactionMemberType.Default).ToString() ?? "";
        buttonHappinessLivestock.subText.text = branch.CountMembers(FactionMemberType.Livestock).ToString() ?? "";
        buttonHappinessResident.SetTooltip(delegate(UITooltip t)
        {
            branch.happiness.residents.WriteNote(t.note);
        });
        buttonHappinessLivestock.SetTooltip(delegate(UITooltip t)
        {
            branch.happiness.livestocks.WriteNote(t.note);
        });
    }
References branch, buttonHappinessLivestock, buttonHappinessResident, FactionBranch.CountMembers(), World.date, Date.day, faction, FactionBranch.faith, Happiness.GetText(), FactionBranch.happiness, HappinessManager.livestocks, Date.month, Faction.name, Religion.Name, Spatial.Name, UITooltip.note, FactionBranch.rank, FactionBranch.RankText, HappinessManager.residents, UIText.SetText(), UIButton.SetTooltip(), textKarma, textName, textPopu, textRank, textReknown, EClass.world, Happiness.WriteNote(), Date.year, and zone.
RefreshResources()
void ContentHomeReport.RefreshResources () inline
Definition at line 98 of file ContentHomeReport.cs.
    {
        listCurrencies.Clear();
        listCurrencies.callbacks = new UIList.Callback<BaseHomeResource, ItemHomeResource>
        {
            onInstantiate = delegate(BaseHomeResource a, ItemHomeResource b)
            {
                b.SetResource(a);
            },
            onList = delegate
            {
                foreach (BaseHomeResource item in branch.resources.list)
                {
                    if (item.IsCurrency)
                    {
                        listCurrencies.Add(item);
                    }
                }
            }
        };
        listCurrencies.List();
        listResources.Clear();
        listResources.callbacks = new UIList.Callback<BaseHomeResource, ItemHomeResource>
        {
            onInstantiate = delegate(BaseHomeResource a, ItemHomeResource b)
            {
                b.SetResource(a);
            },
            onList = delegate
            {
                foreach (BaseHomeResource item2 in branch.resources.list)
                {
                    if (item2.IsRate)
                    {
                        listResources.Add(item2);
                    }
                }
            }
        };
        listResources.List();
    }
References UIList.Add(), branch, UIList.Clear(), BaseHomeResource.IsRate, item, HomeResourceManager.list, UIList.List(), listCurrencies, listResources, FactionBranch.resources, and ItemHomeResource.SetResource().
Member Data Documentation
branch
FactionBranch ContentHomeReport.branch
Definition at line 35 of file ContentHomeReport.cs.
Referenced by OnSwitchContent(), RefreshInfo(), and RefreshResources().
buttonHappinessLivestock
UIButton ContentHomeReport.buttonHappinessLivestock
Definition at line 27 of file ContentHomeReport.cs.
Referenced by RefreshInfo().
buttonHappinessResident
UIButton ContentHomeReport.buttonHappinessResident
Definition at line 25 of file ContentHomeReport.cs.
Referenced by RefreshInfo().
faction
Faction ContentHomeReport.faction
Definition at line 33 of file ContentHomeReport.cs.
Referenced by OnSwitchContent(), and RefreshInfo().
listCurrencies
UIList ContentHomeReport.listCurrencies
Definition at line 29 of file ContentHomeReport.cs.
Referenced by RefreshResources().
listResources
UIList ContentHomeReport.listResources
Definition at line 31 of file ContentHomeReport.cs.
Referenced by RefreshResources().
textHeaderReport
UIText ContentHomeReport.textHeaderReport
Definition at line 19 of file ContentHomeReport.cs.
textHearth
UIText ContentHomeReport.textHearth
Definition at line 11 of file ContentHomeReport.cs.
textInfluence
UIText ContentHomeReport.textInfluence
Definition at line 15 of file ContentHomeReport.cs.
textKarma
UIText ContentHomeReport.textKarma
Definition at line 23 of file ContentHomeReport.cs.
Referenced by RefreshInfo().
textKnowledge
UIText ContentHomeReport.textKnowledge
Definition at line 17 of file ContentHomeReport.cs.
textName
UIText ContentHomeReport.textName
Definition at line 5 of file ContentHomeReport.cs.
Referenced by RefreshInfo().
textPopu
UIText ContentHomeReport.textPopu
Definition at line 13 of file ContentHomeReport.cs.
Referenced by RefreshInfo().
textRank
UIText ContentHomeReport.textRank
Definition at line 7 of file ContentHomeReport.cs.
Referenced by RefreshInfo().
textReknown
UIText ContentHomeReport.textReknown
Definition at line 21 of file ContentHomeReport.cs.
Referenced by RefreshInfo().
textWealth
UIText ContentHomeReport.textWealth
Definition at line 9 of file ContentHomeReport.cs.
zone
Zone ContentHomeReport.zone
Definition at line 37 of file ContentHomeReport.cs.
Referenced by OnSwitchContent(), and RefreshInfo().
Property Documentation
tabResearch
int ContentHomeReport.tabResearch get
Definition at line 39 of file ContentHomeReport.cs.
The documentation for this class was generated from the following file:
Elin/ContentHomeReport.cs