Elin Decompiled Documentation: WidgetArtTool Class Reference
WidgetArtTool Class Reference
Public Member Functions
override void OnActivate ()
void Reset ()
Public Member Functions inherited from Widget
void Test ()
bool IsInRightMode ()
void Activate ()
void RefreshOrder ()
virtual void OnActivate ()
virtual object CreateExtra ()
void Deactivate ()
virtual void OnDeactivate ()
void Close ()
void Reactivate ()
virtual void OnManagerActivate ()
virtual void OnManagerDeactivate ()
void SetAnchor (RectPosition p)
void SetPivot (RectPosition p)
virtual void OnChangePivot ()
void UpdateConfig ()
virtual void OnUpdateConfig ()
void ClampToScreen ()
virtual void OnChangeResolution ()
void OnChangePosition ()
virtual void OnChangeActionMode ()
virtual void OnFlip ()
bool IsAlignTop ()
Layer AddLayer (Layer l, Transform trans)
void RefreshTipPivotPosition ()
SkinSet GetSkin ()
SkinConfig GetSkinConfig ()
void SetSkin (int id, int v=0)
void TestSkin ()
virtual void ApplySkin ()
virtual void OnApplySkin ()
void InstantiateDeco (SkinDeco deco)
void AddDeco (SkinDeco deco)
void RemoveDeco (SkinDeco deco)
virtual bool CanShowContextMenu ()
void ShowContextMenu ()
void SetBaseContextMenu (UIContextMenu m)
virtual void OnSetContextMenu (UIContextMenu m)
void SetGridContextMenu (UIContextMenu m)
void SoundActivate ()
void OnChangeResolution ()
SkinSet GetSkin ()
SkinConfig GetSkinConfig ()
Public Attributes
UISlider sliderSpeed
UISlider sliderBrightness
UISlider sliderLight
UISlider sliderTime
float zoom = 1f
float hour = 12f
Public Attributes inherited from Widget
Image imageBG
SoundData soundActivate
UIDragPanel dragPanel
RectTransform tipPivotLeft
RectTransform tipPivotRight
Properties
CinemaConfig conf [get]
Properties inherited from Widget
string ID [get]
Config config [get]
SkinRoot skinRoot [get]
bool IsSealed [get]
virtual bool ShowStyleMenu [get]
virtual bool AlwaysTop [get]
virtual bool IsStaticPosition [get]
virtual bool AlwaysBottom [get]
virtual Type SetSiblingAfter [get]
virtual bool ShowInBuildMode [get]
virtual bool RightClickToClose [get]
virtual bool AllowRightClickToClose [get]
Properties inherited from EMono
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SoundManager Sound [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static CoreDebug debug [get]
Additional Inherited Members
Public Types inherited from Widget
enum WidgetType { Default , ZoomMenu }
enum State { Active , Inactive }
Static Public Member Functions inherited from EMono
static int rnd (int a)
Static Public Attributes inherited from EMono
static Core core
Protected Member Functions inherited from Widget
void ClampToScreenEnsured (Component c, Vector2 anchoredPos)
void ClampToScreen (RectTransform rect, float margin=10f)
Protected Attributes inherited from Widget
bool flip
Detailed Description
Definition at line 1 of file WidgetArtTool.cs.
Member Function Documentation
OnActivate()
override void WidgetArtTool.OnActivate () inline virtual
Reimplemented from Widget.
Definition at line 17 of file WidgetArtTool.cs.
    {
        _ = EMono.scene.camSupport;
        sliderSpeed.SetSlider(conf.speed, delegate(float a)
        {
            conf.speed = (int)a;
            return "Speed (" + (int)a + ")";
        });
        sliderBrightness.SetSlider(conf.brightness, delegate(float a)
        {
            conf.brightness = (int)a;
            return "Brightness (" + (int)a + "%)";
        });
        sliderLight.SetSlider(conf.light, delegate(float a)
        {
            conf.light = (int)a;
            return "Light (" + (int)a + "%)";
        });
        GameDate d = EMono.world.date;
        sliderTime.SetSlider(d.hour, delegate(float a)
        {
            Weather.Condition currentCondition = EMono.world.weather.CurrentCondition;
            if (d.hour != (int)a)
            {
                d.hour = (int)a - 1;
                d.AdvanceHour();
                EMono.world.weather.SetCondition(currentCondition);
            }
            EMono._map.RefreshFOV(EMono.pc.pos.x, EMono.pc.pos.z, 20, recalculate: true);
            EMono.screen.RefreshAll();
            return "Time (" + d.hour + ")";
        }, notify: false);
        sliderTime.SetActive(EMono.debug.enable);
        this.RebuildLayout(recursive: true);
    }
References EMono._map, GameDate.AdvanceHour(), CinemaConfig.brightness, Scene.camSupport, conf, Weather.CurrentCondition, World.date, EMono.debug, CoreDebug.enable, Date.hour, CinemaConfig.light, EMono.pc, Card.pos, BaseGameScreen.RefreshAll(), Map.RefreshFOV(), EMono.scene, EMono.screen, Weather.SetCondition(), sliderBrightness, sliderLight, sliderSpeed, sliderTime, CinemaConfig.speed, World.weather, EMono.world, Point.x, and Point.z.
Reset()
void WidgetArtTool.Reset () inline
Definition at line 53 of file WidgetArtTool.cs.
    {
        EMono.player.cinemaConfig = new CinemaConfig();
        sliderBrightness.value = conf.brightness;
        sliderLight.value = conf.light;
        sliderSpeed.value = conf.speed;
    }
References CinemaConfig.brightness, conf, CinemaConfig.light, and CinemaConfig.speed.
Member Data Documentation
hour
float WidgetArtTool.hour = 12f
Definition at line 13 of file WidgetArtTool.cs.
sliderBrightness
UISlider WidgetArtTool.sliderBrightness
Definition at line 5 of file WidgetArtTool.cs.
Referenced by OnActivate().
sliderLight
UISlider WidgetArtTool.sliderLight
Definition at line 7 of file WidgetArtTool.cs.
Referenced by OnActivate().
sliderSpeed
UISlider WidgetArtTool.sliderSpeed
Definition at line 3 of file WidgetArtTool.cs.
Referenced by OnActivate().
sliderTime
UISlider WidgetArtTool.sliderTime
Definition at line 9 of file WidgetArtTool.cs.
Referenced by OnActivate().
zoom
float WidgetArtTool.zoom = 1f
Definition at line 11 of file WidgetArtTool.cs.
Property Documentation
conf
CinemaConfig WidgetArtTool.conf get
Definition at line 15 of file WidgetArtTool.cs.
Referenced by OnActivate(), and Reset().
The documentation for this class was generated from the following file:
Elin/WidgetArtTool.cs