Elin Decompiled Documentation: SourceStat Class Reference
SourceStat Class Reference
Classes
class Row
Public Member Functions
override Row CreateRow ()
override Row CreateRowByMapping (IReadOnlyDictionary< string, int > mapping)
override void SetRow (Row r)
override IReadOnlyDictionary< string, int > GetRowMapping ()
override IReadOnlyDictionary< string, string > GetTypeMapping ()
override void OnInit ()
Public Member Functions inherited from SourceDataInt< SourceStat.Row >
override T GetRow (string id)
Public Attributes
Dictionary< string, List< Row > > groups = new Dictionary<string, List<Row>>()
Static Public Attributes
static readonly IReadOnlyDictionary< string, int > RowMapping
static readonly IReadOnlyDictionary< string, string > TypeMapping
Properties
override string[] ImportFields [get]
Detailed Description
Definition at line 4 of file SourceStat.cs.
Member Function Documentation
CreateRow()
override Row SourceStat.CreateRow () inline
Definition at line 177 of file SourceStat.cs.
    {
        return new Row
        {
            id = SourceData.GetInt(0),
            alias = SourceData.GetString(1),
            name_JP = SourceData.GetString(2),
            name = SourceData.GetString(3),
            type = SourceData.GetString(4),
            group = SourceData.GetString(5),
            curse = SourceData.GetString(6),
            duration = SourceData.GetString(7),
            durationMax = SourceData.GetInt(8),
            hexPower = SourceData.GetInt(9),
            negate = SourceData.GetStringArray(10),
            defenseAttb = SourceData.GetStringArray(11),
            resistance = SourceData.GetStringArray(12),
            gainRes = SourceData.GetInt(13),
            elements = SourceData.GetStringArray(14),
            nullify = SourceData.GetStringArray(15),
            tag = SourceData.GetStringArray(16),
            phase = SourceData.GetIntArray(17),
            colors = SourceData.GetString(18),
            element = SourceData.GetString(19),
            effect = SourceData.GetStringArray(20),
            strPhase_JP = SourceData.GetStringArray(21),
            strPhase = SourceData.GetStringArray(22),
            textPhase_JP = SourceData.GetString(23),
            textPhase = SourceData.GetString(24),
            textEnd_JP = SourceData.GetString(25),
            textEnd = SourceData.GetString(26),
            textPhase2_JP = SourceData.GetString(27),
            textPhase2 = SourceData.GetString(28),
            gradient = SourceData.GetString(29),
            invert = SourceData.GetBool(30),
            detail_JP = SourceData.GetString(31),
            detail = SourceData.GetString(32)
        };
    }
References SourceData< T, T2 >.GetBool(), SourceData< T, T2 >.GetInt(), SourceData< T, T2 >.GetIntArray(), SourceData< T, T2 >.GetString(), and SourceData< T, T2 >.GetStringArray().
CreateRowByMapping()
override Row SourceStat.CreateRowByMapping (IReadOnlyDictionary< string, int > mapping) inline
Definition at line 217 of file SourceStat.cs.
    {
        return new Row
        {
            id = SourceData.GetInt(mapping["id"]),
            alias = SourceData.GetString(mapping["alias"]),
            name_JP = SourceData.GetString(mapping["name_JP"]),
            name = SourceData.GetString(mapping["name"]),
            type = SourceData.GetString(mapping["type"]),
            group = SourceData.GetString(mapping["group"]),
            curse = SourceData.GetString(mapping["curse"]),
            duration = SourceData.GetString(mapping["duration"]),
            durationMax = SourceData.GetInt(mapping["durationMax"]),
            hexPower = SourceData.GetInt(mapping["hexPower"]),
            negate = SourceData.GetStringArray(mapping["negate"]),
            defenseAttb = SourceData.GetStringArray(mapping["defenseAttb"]),
            resistance = SourceData.GetStringArray(mapping["resistance"]),
            gainRes = SourceData.GetInt(mapping["gainRes"]),
            elements = SourceData.GetStringArray(mapping["elements"]),
            nullify = SourceData.GetStringArray(mapping["nullify"]),
            tag = SourceData.GetStringArray(mapping["tag"]),
            phase = SourceData.GetIntArray(mapping["phase"]),
            colors = SourceData.GetString(mapping["colors"]),
            element = SourceData.GetString(mapping["element"]),
            effect = SourceData.GetStringArray(mapping["effect"]),
            strPhase_JP = SourceData.GetStringArray(mapping["strPhase_JP"]),
            strPhase = SourceData.GetStringArray(mapping["strPhase"]),
            textPhase_JP = SourceData.GetString(mapping["textPhase_JP"]),
            textPhase = SourceData.GetString(mapping["textPhase"]),
            textEnd_JP = SourceData.GetString(mapping["textEnd_JP"]),
            textEnd = SourceData.GetString(mapping["textEnd"]),
            textPhase2_JP = SourceData.GetString(mapping["textPhase2_JP"]),
            textPhase2 = SourceData.GetString(mapping["textPhase2"]),
            gradient = SourceData.GetString(mapping["gradient"]),
            invert = SourceData.GetBool(mapping["invert"]),
            detail_JP = SourceData.GetString(mapping["detail_JP"]),
            detail = SourceData.GetString(mapping["detail"])
        };
    }
References SourceData< T, T2 >.GetBool(), SourceData< T, T2 >.GetInt(), SourceData< T, T2 >.GetIntArray(), SourceData< T, T2 >.GetString(), and SourceData< T, T2 >.GetStringArray().
GetRowMapping()
override IReadOnlyDictionary< string, int > SourceStat.GetRowMapping () inline
Definition at line 262 of file SourceStat.cs.
    {
        return RowMapping;
    }
References RowMapping.
GetTypeMapping()
override IReadOnlyDictionary< string, string > SourceStat.GetTypeMapping () inline
Definition at line 267 of file SourceStat.cs.
    {
        return TypeMapping;
    }
References TypeMapping.
OnInit()
override void SourceStat.OnInit () inline
Definition at line 272 of file SourceStat.cs.
    {
        foreach (Row row in rows)
        {
            if (!row.group.IsEmpty())
            {
                groups.GetOrCreate(row.group).Add(row);
            }
        }
    }
References SourceStat.Row.group, and groups.
SetRow()
override void SourceStat.SetRow (Row r) inline
Definition at line 257 of file SourceStat.cs.
    {
        map[r.id] = r;
    }
References SourceStat.Row.id.
Member Data Documentation
groups
Dictionary<string, List<Row> > SourceStat.groups = new Dictionary<string, List<Row>>()
Definition at line 173 of file SourceStat.cs.
Referenced by OnInit().
RowMapping
readonly IReadOnlyDictionary<string, int> SourceStat.RowMapping static
Definition at line 98 of file SourceStat.cs.
Referenced by GetRowMapping().
TypeMapping
readonly IReadOnlyDictionary<string, string> SourceStat.TypeMapping static
Definition at line 135 of file SourceStat.cs.
Referenced by GetTypeMapping().
Property Documentation
ImportFields
override string [] SourceStat.ImportFields get
Definition at line 175 of file SourceStat.cs.
The documentation for this class was generated from the following file:
Elin/SourceStat.cs