Elin Decompiled Documentation: LayerEmbark Class Reference
LayerEmbark Class Reference
Public Types
enum Mode { top , previewMap , member , map }
Public Member Functions
override void OnAfterAddLayer ()
void OnClickBack ()
void SwitchMode (int i)
void SwitchMode (Mode _mode)
override bool OnBack ()
override void OnKill ()
void RerollPreviewMap ()
void OnClickPreview (UIMapPreview preview)
void RefreshMembers ()
void RerollPC ()
void RerollMembers ()
string GetAlias ()
void RerollPlayerAlias ()
void RerollPlayerName ()
void OnEndEditPlayerName ()
void ListPlayerAlias ()
Public Member Functions inherited from ELayer
override void OnBeforeAddLayer ()
void InitInspector ()
sealed override void Init ()
override void OnAfterAddLayer ()
void TryShowHelp ()
void AddLayerToUI (string id)
void TryShowHint (string _langHint=null)
void TalkHomeMemeber (string id)
void TalkMaid (string id)
override void OnRightClick ()
Public Member Functions inherited from Layer
virtual string GetTextHeader (Window window)
virtual bool HeaderIsListOf (int id)
virtual void Init ()
virtual void OnInit ()
virtual void OnAfterInit ()
virtual void ApplySkin ()
void ShowScreenLock (string id)
void UpdateInput ()
virtual void OnUpdateInput ()
virtual void OnRightClick ()
virtual bool OnBack ()
virtual void OnChangeLayer ()
virtual void OnCreate ()
void _AddLayer (string id)
Layer AddLayer (string id)
T AddLayer< T > ()
T AddLayer< T > (string id)
T AddLayerDontCloseOthers< T > ()
Layer AddLayerDontCloseOthers (Layer l)
T GetOrAddLayer< T > ()
virtual void OnBeforeAddLayer ()
virtual void OnAfterAddLayer ()
Layer AddLayer (Layer l)
void ToggleLayer (string id)
T ToggleLayer< T > (string id=null)
void WaitAndClose ()
void OnClickClose ()
virtual void Close ()
void CloseLayers ()
void RemoveLayers (bool removeImportant=false)
bool RemoveLayer< T > ()
void RemoveLayer (Layer l)
virtual void OnKill ()
Layer SetOnKill (Action action)
void DisableClose ()
void Delay (float duration=0.05f)
Layer SetDelay (float d)
Layer GetLayer (string id)
T GetLayer< T > (bool fromTop=false)
Layer GetTopLayer ()
void SwitchContent (int idWindow, int i)
virtual void OnSwitchContent (Window window)
Layer SetTitles (string langList, string idHeaderRow=null)
bool IsBlockWidgetClick ()
bool IsHideHud ()
bool IsAllowGeneralInput ()
bool IsUseBlur ()
bool IsPointerOnLayer ()
void ApplySkin ()
Public Attributes
UIMapPreview mapPreview
GameObject goTop
GameObject goPreviewMap
GameObject goMembers
GameObject goMap
UICharaMaker maker
UIMapSelector selector
UIList listMembers
InputField inputHomeName
InputField inputPlayerAlias
InputField inputSupplyType
InputField inputRegion
InputField inputEra
InputField inputPlayerName
UICardInfo cardInfo
UIButton buttonRerollSupply
UIButton toggleSkipQuests
UIButton buttonEmbark
UISelectableGroup groupGameMode
RectTransform mapHolder1
RectTransform mapHolder2
Mode mode
Mode lastMode
EmbarkActor moldActor
GridLayoutGroup gridPreview
UIMapPreview moldPreview
List< UIMapPreview > previews
Public Attributes inherited from Layer
Option option
UnityEvent onKill
Anime animeIn
Anime animeOut
bool closeOthers
bool defaultActionMode = true
Button screenLock
Layer parent
string idLayer
List< Layer > layers = new List<Layer>()
Vector2 lastParentPos
List< Window > windows = new List<Window>()
string langHint
Static Public Attributes
static LayerEmbark Instance
Static Public Attributes inherited from Layer
static int skipInput
static bool closeOnRightClick
static bool rightClicked
static bool cancelKeyDown
static bool ignoreSounds
static Transform blurStopInstance
static string[] searchPath = new string[3] { "Layer", "Layer/Dialog", "Layer/LayerHome" }
Properties
GameBlueprint bp [get]
LayerTitle title [get]
Properties inherited from ELayer
static Core core [get]
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static FactionBranch Branch [get]
static Faction Home [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static CoreConfig config [get]
static GameSetting setting [get]
static ColorProfile Colors [get]
static SourceManager sources [get]
static World world [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
bool IsFloat [get]
virtual string IdHelp [get]
Properties inherited from Layer
Layer TopLayer [get]
string uid [get]
virtual RectTransform rectLayers [get]
virtual bool blockWidgetClick [get]
Private Member Functions
void Update ()
Private Attributes
bool firstPreview = true
Additional Inherited Members
Static Public Member Functions inherited from ELayer
static int rnd (int a)
Static Public Member Functions inherited from Layer
static T Create< T > ()
static T Create< T > (string path)
static Layer Create (string path)
Protected Member Functions inherited from ELayer
sealed override void _Close ()
sealed override void Kill ()
Protected Member Functions inherited from Layer
virtual void Awake ()
virtual void _Close ()
virtual void Kill ()
Protected Attributes inherited from Layer
RectTransform _rect
bool isDestroyed
Detailed Description
Definition at line 5 of file LayerEmbark.cs.
Member Enumeration Documentation
Mode
enum LayerEmbark.Mode
Enumerator
top
previewMap
member
map
Definition at line 7 of file LayerEmbark.cs.
    {
        top,
        previewMap,
        member,
        map
    }
Member Function Documentation
GetAlias()
string LayerEmbark.GetAlias () inline
Definition at line 256 of file LayerEmbark.cs.
    {
        if (ELayer.rnd(4) == 0)
        {
            return ELayer.player.title;
        }
        return bp.charas.RandomItem().Name;
    }
References bp, ZoneBlueprint.charas, ELayer.player, ELayer.rnd(), and Player.title.
ListPlayerAlias()
void LayerEmbark.ListPlayerAlias () inline
Definition at line 280 of file LayerEmbark.cs.
    {
        ELayer.ui.AddLayer<LayerList>().SetStringList(() => WordGen.GetList("title"), delegate(int a, string b)
        {
            ELayer.player.title = b;
        });
    }
References ELayer.ui.
OnAfterAddLayer()
override void LayerEmbark.OnAfterAddLayer () inline virtual
Reimplemented from ELayer.
Definition at line 77 of file LayerEmbark.cs.
    {
        Instance = this;
        if (ELayer.game == null)
        {
            Game.Create();
        }
        if (bp.map != null)
        {
            mapPreview.SetMap(bp.map);
        }
        if (!LayerTitle.actor)
        {
            LayerTitle.actor = Util.Instantiate(moldActor);
        }
        RefreshMembers();
        SwitchMode(Mode.top);
        ELayer.ui.AddLayer<LayerEditBio>();
    }
References LayerTitle.actor, bp, Game.Create(), ELayer.game, Instance, ZoneBlueprint.map, mapPreview, moldActor, RefreshMembers(), UIMapPreview.SetMap(), SwitchMode(), ELayer.ui, and Util.
OnBack()
override bool LayerEmbark.OnBack () inline virtual
Reimplemented from Layer.
Definition at line 151 of file LayerEmbark.cs.
    {
        if (mode == Mode.map)
        {
            return false;
        }
        if (mode != 0)
        {
            SwitchMode(Mode.top);
            return false;
        }
        return base.OnBack();
    }
References mode, and SwitchMode().
OnClickBack()
void LayerEmbark.OnClickBack () inline
Definition at line 97 of file LayerEmbark.cs.
    {
        if (mode == Mode.previewMap && lastMode != Mode.map)
        {
            SE.Click();
        }
        SwitchMode(Mode.top);
    }
References lastMode, mode, and SwitchMode().
OnClickPreview()
void LayerEmbark.OnClickPreview (UIMapPreview preview) inline
Definition at line 205 of file LayerEmbark.cs.
    {
        bp.map = preview.map;
        bp.genSetting = preview.thread.bp.genSetting;
        mapPreview.SetMap(bp.map);
        SwitchMode(Mode.top);
    }
References bp, UIMapPreview.GenThread.bp, ZoneBlueprint.genSetting, UIMapPreview.map, ZoneBlueprint.map, mapPreview, UIMapPreview.SetMap(), SwitchMode(), and UIMapPreview.thread.
OnEndEditPlayerName()
void LayerEmbark.OnEndEditPlayerName () inline
Definition at line 275 of file LayerEmbark.cs.
    {
        ELayer.player.chara.c_altName = inputPlayerName.text;
    }
References inputPlayerName.
OnKill()
override void LayerEmbark.OnKill () inline virtual
Reimplemented from Layer.
Definition at line 173 of file LayerEmbark.cs.
    {
    }
RefreshMembers()
void LayerEmbark.RefreshMembers () inline
Definition at line 213 of file LayerEmbark.cs.
    {
        listMembers.Clear();
        listMembers.callbacks = new UIList.Callback<Chara, ButtonChara>
        {
            onInstantiate = delegate(Chara a, ButtonChara b)
            {
                b.SetChara(a, ButtonChara.Mode.Embark);
                a.elements.ListBestSkills();
                b.item.button2.SetActive(a == ELayer.player.chara);
                b.item.button1.SetActive(a == ELayer.player.chara);
                b.item.button1.onClick.AddListener(delegate
                {
                    ELayer.ui.AddLayer<LayerEditBio>().SetChara(null, delegate
                    {
                        RefreshMembers();
                    });
                });
            }
        };
        foreach (Chara chara in bp.charas)
        {
            if (chara.IsPCC)
            {
                listMembers.Add(chara);
            }
        }
        listMembers.Refresh();
    }
References UIList.Add(), bp, UIItem.button1, UIItem.button2, Player.chara, ZoneBlueprint.charas, UIList.Clear(), Card.elements, Chara.IsPCC, ButtonChara.item, ElementContainer.ListBestSkills(), listMembers, ELayer.player, UIList.Refresh(), RefreshMembers(), ButtonChara.SetChara(), and ELayer.ui.
Referenced by OnAfterAddLayer(), RefreshMembers(), RerollMembers(), and SwitchMode().
RerollMembers()
void LayerEmbark.RerollMembers () inline
Definition at line 250 of file LayerEmbark.cs.
    {
        bp.RerollChara();
        RefreshMembers();
    }
References bp, RefreshMembers(), and GameBlueprint.RerollChara().
RerollPC()
void LayerEmbark.RerollPC () inline
Definition at line 243 of file LayerEmbark.cs.
    {
        bp.charas.Remove(ELayer.player.chara);
        bp.charas.Insert(0, ELayer.player.chara);
        (listMembers.buttons[0].component as ButtonChara).SetChara(ELayer.player.chara, ButtonChara.Mode.Embark);
    }
References bp, UIList.buttons, Player.chara, ZoneBlueprint.charas, listMembers, and ELayer.player.
RerollPlayerAlias()
void LayerEmbark.RerollPlayerAlias () inline
Definition at line 265 of file LayerEmbark.cs.
    {
        ELayer.player.title = WordGen.Get("title");
    }
RerollPlayerName()
void LayerEmbark.RerollPlayerName () inline
Definition at line 270 of file LayerEmbark.cs.
    {
        ELayer.player.chara.c_altName = NameGen.getRandomName();
    }
RerollPreviewMap()
void LayerEmbark.RerollPreviewMap () inline
Definition at line 177 of file LayerEmbark.cs.
    {
        if (firstPreview)
        {
            for (int i = 0; i < 8; i++)
            {
                UIMapPreview p = Util.Instantiate(moldPreview, gridPreview);
                previews.Add(p);
                p.button.onClick.AddListener(delegate
                {
                    if (!p.thread.done)
                    {
                        SE.Beep();
                    }
                    else
                    {
                        OnClickPreview(p);
                    }
                });
            }
            firstPreview = false;
        }
        foreach (UIMapPreview preview in previews)
        {
            preview.GenerateMap(bp);
        }
    }
References bp, UIMapPreview.button, UIMapPreview.GenThread.done, firstPreview, UIMapPreview.GenerateMap(), gridPreview, moldPreview, previews, UIMapPreview.thread, and Util.
Referenced by SwitchMode().
SwitchMode() [1/2]
void LayerEmbark.SwitchMode (int i) inline
Definition at line 106 of file LayerEmbark.cs.
    {
        SwitchMode(i.ToEnum<Mode>());
    }
References SwitchMode().
Referenced by OnAfterAddLayer(), OnBack(), OnClickBack(), OnClickPreview(), and SwitchMode().
SwitchMode() [2/2]
void LayerEmbark.SwitchMode (Mode _mode) inline
Definition at line 111 of file LayerEmbark.cs.
    {
        bool flag = lastMode == Mode.map;
        if (_mode == Mode.top && mode == Mode.previewMap && flag)
        {
            _mode = Mode.map;
        }
        lastMode = mode;
        mode = _mode;
        goPreviewMap.SetActive(mode == Mode.previewMap);
        goTop.SetActive(mode == Mode.top);
        goMembers.SetActive(mode == Mode.member);
        buttonEmbark.SetActive(mode == Mode.top);
        goMap.SetActive(mode == Mode.map);
        switch (mode)
        {
        case Mode.top:
            mapPreview.transform.SetParent(mapHolder1, worldPositionStays: false);
            ELayer.ui.hud.hint.Show("hintEmbarkTop".lang(), icon: false);
            selector.WriteNote(ELayer.player.zone);
            break;
        case Mode.previewMap:
            SE.Play("click_paper");
            ELayer.ui.hud.hint.Show("hintEmbarkPreview".lang(), icon: false);
            RerollPreviewMap();
            break;
        case Mode.member:
            ELayer.ui.AddLayer<LayerEditBio>().SetChara(null, delegate
            {
                RefreshMembers();
                SwitchMode(Mode.top);
            });
            break;
        case Mode.map:
            mapPreview.transform.SetParent(mapHolder2, worldPositionStays: false);
            ELayer.ui.hud.hint.Show("hintEmbarkMap".lang(), icon: false);
            break;
        }
    }
References buttonEmbark, goMap, goMembers, goPreviewMap, goTop, lastMode, mapHolder1, mapHolder2, mapPreview, mode, ELayer.player, RefreshMembers(), RerollPreviewMap(), selector, SwitchMode(), ELayer.ui, UIMapSelector.WriteNote(), and Player.zone.
Update()
void LayerEmbark.Update () inline private
Definition at line 165 of file LayerEmbark.cs.
    {
        if (mode == Mode.map)
        {
            ActionMode.Title.InputMovement();
        }
    }
References ActionMode.InputMovement(), mode, and ActionMode.Title.
Member Data Documentation
buttonEmbark
UIButton LayerEmbark.buttonEmbark
Definition at line 51 of file LayerEmbark.cs.
Referenced by SwitchMode().
buttonRerollSupply
UIButton LayerEmbark.buttonRerollSupply
Definition at line 47 of file LayerEmbark.cs.
cardInfo
UICardInfo LayerEmbark.cardInfo
Definition at line 45 of file LayerEmbark.cs.
firstPreview
bool LayerEmbark.firstPreview = true private
Definition at line 71 of file LayerEmbark.cs.
Referenced by RerollPreviewMap().
goMap
GameObject LayerEmbark.goMap
Definition at line 25 of file LayerEmbark.cs.
Referenced by SwitchMode().
goMembers
GameObject LayerEmbark.goMembers
Definition at line 23 of file LayerEmbark.cs.
Referenced by SwitchMode().
goPreviewMap
GameObject LayerEmbark.goPreviewMap
Definition at line 21 of file LayerEmbark.cs.
Referenced by SwitchMode().
goTop
GameObject LayerEmbark.goTop
Definition at line 19 of file LayerEmbark.cs.
Referenced by SwitchMode().
gridPreview
GridLayoutGroup LayerEmbark.gridPreview
Definition at line 65 of file LayerEmbark.cs.
Referenced by RerollPreviewMap().
groupGameMode
UISelectableGroup LayerEmbark.groupGameMode
Definition at line 53 of file LayerEmbark.cs.
inputEra
InputField LayerEmbark.inputEra
Definition at line 41 of file LayerEmbark.cs.
inputHomeName
InputField LayerEmbark.inputHomeName
Definition at line 33 of file LayerEmbark.cs.
inputPlayerAlias
InputField LayerEmbark.inputPlayerAlias
Definition at line 35 of file LayerEmbark.cs.
inputPlayerName
InputField LayerEmbark.inputPlayerName
Definition at line 43 of file LayerEmbark.cs.
Referenced by OnEndEditPlayerName().
inputRegion
InputField LayerEmbark.inputRegion
Definition at line 39 of file LayerEmbark.cs.
inputSupplyType
InputField LayerEmbark.inputSupplyType
Definition at line 37 of file LayerEmbark.cs.
Instance
LayerEmbark LayerEmbark.Instance static
Definition at line 15 of file LayerEmbark.cs.
Referenced by OnAfterAddLayer().
lastMode
Mode LayerEmbark.lastMode
Definition at line 61 of file LayerEmbark.cs.
Referenced by OnClickBack(), and SwitchMode().
listMembers
UIList LayerEmbark.listMembers
Definition at line 31 of file LayerEmbark.cs.
Referenced by RefreshMembers(), and RerollPC().
maker
UICharaMaker LayerEmbark.maker
Definition at line 27 of file LayerEmbark.cs.
mapHolder1
RectTransform LayerEmbark.mapHolder1
Definition at line 55 of file LayerEmbark.cs.
Referenced by SwitchMode().
mapHolder2
RectTransform LayerEmbark.mapHolder2
Definition at line 57 of file LayerEmbark.cs.
Referenced by SwitchMode().
mapPreview
UIMapPreview LayerEmbark.mapPreview
Definition at line 17 of file LayerEmbark.cs.
Referenced by OnAfterAddLayer(), OnClickPreview(), and SwitchMode().
mode
Mode LayerEmbark.mode
Definition at line 59 of file LayerEmbark.cs.
Referenced by OnBack(), OnClickBack(), SwitchMode(), and Update().
moldActor
EmbarkActor LayerEmbark.moldActor
Definition at line 63 of file LayerEmbark.cs.
Referenced by OnAfterAddLayer().
moldPreview
UIMapPreview LayerEmbark.moldPreview
Definition at line 67 of file LayerEmbark.cs.
Referenced by RerollPreviewMap().
previews
List<UIMapPreview> LayerEmbark.previews
Definition at line 69 of file LayerEmbark.cs.
Referenced by RerollPreviewMap().
selector
UIMapSelector LayerEmbark.selector
Definition at line 29 of file LayerEmbark.cs.
Referenced by SwitchMode().
toggleSkipQuests
UIButton LayerEmbark.toggleSkipQuests
Definition at line 49 of file LayerEmbark.cs.
Property Documentation
bp
GameBlueprint LayerEmbark.bp get
Definition at line 73 of file LayerEmbark.cs.
Referenced by GetAlias(), OnAfterAddLayer(), OnClickPreview(), RefreshMembers(), RerollMembers(), RerollPC(), and RerollPreviewMap().
title
LayerTitle LayerEmbark.title get
Definition at line 75 of file LayerEmbark.cs.
The documentation for this class was generated from the following file:
Elin/LayerEmbark.cs