Elin Decompiled Documentation: QuestManager Class Reference
QuestManager Class Reference
Public Member Functions
Quest Add (string id, string idGlobalChara=null)
Quest Start (string id, string idGlobalChara)
Quest Start (string id, Chara c=null, bool assignQuest=true)
Quest Start (Quest q)
void Remove (Quest q)
void RemoveGlobal (Quest q)
void RemoveAll (Chara c)
void Complete (Quest q)
bool OnShowDialog (Chara c)
void OnAdvanceHour ()
bool IsStarted< T > ()
int GetPhase< T > ()
T Get< T > ()
Quest Get (string id)
Quest Get (int uid)
Quest GetGlobal (string id)
bool IsCompleted (string id)
int CountNew ()
int CountRandomQuest ()
void UpdateJournal ()
bool IsDeliverTarget (Chara c)
void AddQuestAsh ()
void AddQuestFiama ()
bool HasFarAwayEscort (bool execute=false)
void OnEnterZone ()
Public Attributes
List< Quest > list = new List<Quest>()
List< Quest > globalList = new List<Quest>()
HashSet< string > completedIDs = new HashSet<string>()
HashSet< string > completedTypes = new HashSet<string>()
int uid
Static Public Attributes
const int MaxRandomQuest = 5
Static Public Attributes inherited from EClass
static Core core
Properties
QuestMain Main [get]
new QuestHome Home [get]
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Additional Inherited Members
Static Public Member Functions inherited from EClass
static int rnd (int a)
static int curve (int a, int start, int step, int rate=75)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Detailed Description
Definition at line 7 of file QuestManager.cs.
Member Function Documentation
Add()
Quest QuestManager.Add (string id, string idGlobalChara = null) inline
Definition at line 25 of file QuestManager.cs.
    {
        Quest quest = Quest.Create(id, null, null);
        if (idGlobalChara.IsEmpty())
        {
            idGlobalChara = quest.source.drama[0];
        }
        quest.SetClient(EClass.game.cards.globalCharas.Find(idGlobalChara), false);
        EClass.game.quests.globalList.Add(quest);
        return quest;
    }
References Game.cards, Quest.Create(), CardManager.Find(), EClass.game, CardManager.globalCharas, globalList, Game.quests, Quest.SetClient(), and Quest.source.
Referenced by GameDate.AdvanceDay(), QuestLoytelFarm.OnComplete(), QuestShippingChest.OnComplete(), QuestVernis.OnComplete(), QuestDialog.OnDropReward(), QuestIntoDarkness.OnStart(), CoreDebug.QuickStart(), Chara.ShowDialog(), and CoreDebug.UpdateInput().
AddQuestAsh()
void QuestManager.AddQuestAsh () inline
Definition at line 267 of file QuestManager.cs.
    {
        Chara c = EClass.game.cards.globalCharas.Find("ashland");
        QuestCraft questCraft = Quest.Create("ash1", null, null) as QuestCraft;
        questCraft.SetClient(c, true);
        questCraft.req1.Add(new QuestCraft.Req("rock", 1));
        questCraft.req1.Add(new QuestCraft.Req("branch", 1));
        questCraft.req2.Add(new QuestCraft.Req("axe", 1));
    }
References Game.cards, Quest.Create(), CardManager.Find(), EClass.game, CardManager.globalCharas, QuestCraft.req1, QuestCraft.req2, and Quest.SetClient().
AddQuestFiama()
void QuestManager.AddQuestFiama () inline
Definition at line 277 of file QuestManager.cs.
    {
        Chara c = EClass.game.cards.globalCharas.Find("fiama");
        QuestCraft questCraft = Quest.Create("fiama1", null, null) as QuestCraft;
        questCraft.SetClient(c, true);
        questCraft.req1.Add(new QuestCraft.Req("crim", 3));
        questCraft.req2.Add(new QuestCraft.Req("hotcrim", 1));
    }
References Game.cards, Quest.Create(), CardManager.Find(), EClass.game, CardManager.globalCharas, QuestCraft.req1, QuestCraft.req2, and Quest.SetClient().
Complete()
void QuestManager.Complete (Quest q) inline
Definition at line 111 of file QuestManager.cs.
    {
        q.Complete();
    }
References Quest.Complete().
Referenced by QuestCraft.Deliver(), QuestDeliver.Deliver(), Quest.OnCompleteTask(), and DramaManager.ParseLine().
CountNew()
int QuestManager.CountNew () inline
Definition at line 214 of file QuestManager.cs.
    {
        int num = 0;
        using (List<Quest>.Enumerator enumerator = this.list.GetEnumerator())
        {
            while (enumerator.MoveNext())
            {
                if (enumerator.Current.isNew)
                {
                    num++;
                }
            }
        }
        return num;
    }
References list.
CountRandomQuest()
int QuestManager.CountRandomQuest () inline
Definition at line 230 of file QuestManager.cs.
    {
        int num = 0;
        using (List<Quest>.Enumerator enumerator = this.list.GetEnumerator())
        {
            while (enumerator.MoveNext())
            {
                if (enumerator.Current is QuestRandom)
                {
                    num++;
                }
            }
        }
        return num;
    }
References list.
Referenced by LayerQuestBoard.RefreshQuest().
Get() [1/2]
Quest QuestManager.Get (int uid) inline
Definition at line 185 of file QuestManager.cs.
    {
        foreach (Quest quest in this.list)
        {
            if (quest.uid == uid)
            {
                return quest;
            }
        }
        return null;
    }
References list, Quest.uid, and uid.
Get() [2/2]
Quest QuestManager.Get (string id) inline
Definition at line 173 of file QuestManager.cs.
    {
        foreach (Quest quest in this.list)
        {
            if (quest.GetType().ToString() == id || quest.id == id)
            {
                return quest;
            }
        }
        return null;
    }
References Quest.id, and list.
Referenced by InvOwnerDeliver._OnProcess(), AI_PlayMusic.Evaluate(), ZonePreEnterOnCompleteQuestInstance.Execute(), DramaOutcome.OnClaimLand(), Zone_DungeonPuppy.OnGenerateMap(), DramaManager.ParseLine(), InvOwnerDeliver.PayBill(), DramaOutcome.poppy_found(), DramaOutcome.QuestDebt_reward(), DramaOutcome.QuestExploration_AfterCrystal(), DramaOutcome.QuestExploration_MeetFarris(), DramaOutcome.QuestExploration_MeetFarris2(), Remove(), Chara.ShowDialog(), Chara.Tick(), Chara.TryDropBossLoot(), and CoreDebug.UpdateInput().
Get< T >()
T QuestManager.Get< T > () inline
Type Constraints
T : Quest
Definition at line 161 of file QuestManager.cs.
                              : Quest
    {
        foreach (Quest quest in this.list)
        {
            if (quest is T)
            {
                return quest as T;
            }
        }
        return default(T);
    }
References list.
GetGlobal()
Quest QuestManager.GetGlobal (string id) inline
Definition at line 197 of file QuestManager.cs.
    {
        foreach (Quest quest in this.globalList)
        {
            if (quest.GetType().ToString() == id || quest.id == id)
            {
                return quest;
            }
        }
        return null;
    }
References globalList, and Quest.id.
Referenced by GameDate.AdvanceDay().
GetPhase< T >()
int QuestManager.GetPhase< T > () inline
Type Constraints
T : Quest
Definition at line 145 of file QuestManager.cs.
                                     : Quest
    {
        if (this.completedTypes.Contains(typeof(T).ToString()))
        {
            return 999;
        }
        foreach (Quest quest in this.list)
        {
            if (quest is T)
            {
                return quest.phase;
            }
        }
        return -1;
    }
References completedTypes, list, and Quest.phase.
Referenced by IsStarted< T >().
HasFarAwayEscort()
bool QuestManager.HasFarAwayEscort (bool execute = false) inline
Definition at line 286 of file QuestManager.cs.
    {
        bool has = false;
        if (EClass._zone.IsTown || EClass._zone.IsPCFaction || EClass._zone.HasLaw || EClass._zone.IsInstance)
        {
            return false;
        }
        EClass._map.charas.ForeachReverse(delegate(Chara m)
        {
            if (!m.IsEscorted())
            {
                return;
            }
            if (EClass.pc.Dist(m) < 5)
            {
                return;
            }
            has = true;
            if (execute)
            {
                m.Destroy();
            }
        });
        if (has & execute)
        {
            this.OnEnterZone();
        }
        return has;
    }
References EClass._map, EClass._zone, Map.charas, Card.Destroy(), Card.Dist(), Zone.HasLaw, Chara.IsEscorted(), Zone.IsInstance, Zone.IsPCFaction, Zone.IsTown, OnEnterZone(), and EClass.pc.
Referenced by Player.ExitBorder().
IsCompleted()
bool QuestManager.IsCompleted (string id) inline
Definition at line 209 of file QuestManager.cs.
    {
        return this.completedIDs.Contains(id);
    }
References completedIDs.
Referenced by GameDate.AdvanceDay(), QuestVernis.CanUpdateOnTalk(), and QuestDialog.OnDropReward().
IsDeliverTarget()
bool QuestManager.IsDeliverTarget (Chara c) inline
Definition at line 252 of file QuestManager.cs.
    {
        using (List<Quest>.Enumerator enumerator = this.list.GetEnumerator())
        {
            while (enumerator.MoveNext())
            {
                if (enumerator.Current.IsDeliverTarget(c))
                {
                    return true;
                }
            }
        }
        return false;
    }
References list.
Referenced by ActPlan._Update().
IsStarted< T >()
bool QuestManager.IsStarted< T > () inline
Type Constraints
T : Quest
Definition at line 140 of file QuestManager.cs.
                                       : Quest
    {
        return this.GetPhase<T>() != -1;
    }
References GetPhase< T >().
OnAdvanceHour()
void QuestManager.OnAdvanceHour () inline
Definition at line 128 of file QuestManager.cs.
    {
        this.list.ForeachReverse(delegate(Quest q)
        {
            if (q.IsExpired)
            {
                Msg.Say("questExpired", q.GetTitle(), null, null, null);
                q.Fail();
            }
        });
    }
References Quest.IsExpired, and list.
Referenced by GameDate.AdvanceHour().
OnEnterZone()
void QuestManager.OnEnterZone () inline
Definition at line 316 of file QuestManager.cs.
    {
        this.list.ForeachReverse(delegate(Quest q)
        {
            q.OnEnterZone();
        });
    }
References list, and Quest.OnEnterZone().
Referenced by HasFarAwayEscort(), and Scene.Init().
OnShowDialog()
bool QuestManager.OnShowDialog (Chara c) inline
Definition at line 116 of file QuestManager.cs.
    {
        foreach (Quest quest in this.list)
        {
            if (quest.person.chara == c && (quest.CanUpdateOnTalk(c) || (quest.CanAutoAdvance && EClass.debug.autoAdvanceQuest)))
            {
                return quest.UpdateOnTalk();
            }
        }
        return false;
    }
References CoreDebug.autoAdvanceQuest, Quest.CanAutoAdvance, Quest.CanUpdateOnTalk(), Person.chara, EClass.debug, list, Quest.person, and Quest.UpdateOnTalk().
Referenced by Chara.ShowDialog().
Remove()
void QuestManager.Remove (Quest q) inline
Definition at line 63 of file QuestManager.cs.
    {
        if (!this.list.Remove(q))
        {
            string[] array = new string[10];
            array[0] = "exception: Failed to remove quest:";
            int num = 1;
            Quest quest = q;
            array[num] = ((quest != null) ? quest.ToString() : null);
            array[2] = "/";
            array[3] = q.uid.ToString();
            array[4] = "/";
            array[5] = q.source.id;
            array[6] = "/";
            array[7] = q.deadline.ToString();
            array[8] = "/";
            array[9] = q.Hours.ToString();
            Debug.Log(string.Concat(array));
            q = this.Get(q.uid);
            Debug.Log(q);
            if (q != null && q.IsRandomQuest)
            {
                this.list.Remove(q);
            }
        }
    }
References Quest.deadline, Get(), Quest.Hours, Quest.IsRandomQuest, list, Quest.source, and Quest.uid.
Referenced by Quest.Complete(), Quest.Fail(), ItemQuestTracker.OnClickClose(), LayerCraft.RefreshTrackButton(), and RemoveAll().
RemoveAll()
void QuestManager.RemoveAll (Chara c) inline
Definition at line 95 of file QuestManager.cs.
    {
        foreach (Quest q in (from a in this.list
        where a.chara == c
        select a).ToList<Quest>())
        {
            this.Remove(q);
        }
        foreach (Quest q2 in (from a in this.globalList
        where a.chara == c
        select a).ToList<Quest>())
        {
            this.RemoveGlobal(q2);
        }
    }
References globalList, list, Remove(), and RemoveGlobal().
Referenced by DramaOutcome.QuestExploration_AfterComplete().
RemoveGlobal()
void QuestManager.RemoveGlobal (Quest q) inline
Definition at line 90 of file QuestManager.cs.
    {
        this.globalList.Remove(q);
    }
References globalList.
Referenced by RemoveAll().
Start() [1/3]
Quest QuestManager.Start (Quest q) inline
Definition at line 48 of file QuestManager.cs.
    {
        this.list.Insert(0, q);
        q.Start();
        if (EClass.core.IsGameStarted)
        {
            q.UpdateJournal();
            if (EClass.player.questTracker)
            {
                WidgetQuestTracker.Show();
            }
        }
        return q;
    }
References EClass.core, list, EClass.player, Player.questTracker, WidgetQuestTracker.Show(), Quest.Start(), and Quest.UpdateJournal().
Start() [2/3]
Quest QuestManager.Start (string id, Chara c = null, bool assignQuest = true) inline
Definition at line 43 of file QuestManager.cs.
    {
        return this.Start(Quest.Create(id, null, null).SetClient(c, assignQuest));
    }
References Quest.Create(), Quest.SetClient(), and Start().
Start() [3/3]
Quest QuestManager.Start (string id, string idGlobalChara) inline
Definition at line 37 of file QuestManager.cs.
    {
        Quest q = Quest.Create(id, null, null).SetClient(EClass.game.cards.globalCharas.Find(idGlobalChara), false);
        return this.Start(q);
    }
References Game.cards, Quest.Create(), CardManager.Find(), EClass.game, CardManager.globalCharas, Quest.SetClient(), and Start().
Referenced by TraitDoorman_Fighter.GiveTrial(), TraitDoorman_Mage.GiveTrial(), TraitDoorman_Thief.GiveTrial(), DramaOutcome.guild_trial(), QuestDialog.OnDropReward(), Player.OnStartNewGame(), DramaManager.ParseLine(), DramaOutcome.QuestExploration_AfterComplete(), DramaOutcome.QuestExploration_AfterCrystal(), DramaOutcome.QuestExploration_MeetFarris2(), LayerCraft.RefreshTrackButton(), Start(), Game.StartNewGame(), and CoreDebug.UpdateInput().
UpdateJournal()
void QuestManager.UpdateJournal () inline
Definition at line 246 of file QuestManager.cs.
    {
        SE.WriteJournal();
        Msg.Say("journalUpdate");
    }
References Msg.Say().
Referenced by DramaManager.ParseLine().
Member Data Documentation
completedIDs
HashSet<string> QuestManager.completedIDs = new HashSet<string>()
Definition at line 333 of file QuestManager.cs.
Referenced by Quest.Complete(), IsCompleted(), and DramaOutcome.melilith_friend().
completedTypes
HashSet<string> QuestManager.completedTypes = new HashSet<string>()
Definition at line 336 of file QuestManager.cs.
Referenced by Quest.Complete(), and GetPhase< T >().
globalList
List<Quest> QuestManager.globalList = new List<Quest>()
Definition at line 330 of file QuestManager.cs.
Referenced by Add(), GetGlobal(), QuestDefense.OnChangePhase(), DramaOutcome.OnClaimLand(), QuestIntroInspector.OnComplete(), QuestSharedContainer.OnComplete(), TCExtra.OnDraw(), QuestDialog.OnDropReward(), QuestExploration.OnStart(), DramaManager.ParseLine(), LayerQuestBoard.RefreshQuest(), RemoveAll(), RemoveGlobal(), and Game.StartNewGame().
list
List<Quest> QuestManager.list = new List<Quest>()
Definition at line 327 of file QuestManager.cs.
Referenced by CountNew(), CountRandomQuest(), Card.DamageHP(), Get(), Get< T >(), GetPhase< T >(), Chara.GiveGift(), IsDeliverTarget(), Chara.IsEscorted(), Player.ModKarma(), OnAdvanceHour(), OnEnterZone(), Game.OnLoad(), OnShowDialog(), ContentQuest.OnSwitchContent(), ItemQuestTracker.Refresh(), WidgetQuestTracker.Refresh(), TCOrbitChara.RefreshAll(), LayerQuestBoard.RefreshQuest(), LayerCraft.RefreshTrackButton(), Remove(), RemoveAll(), ItemQuest.SetQuest(), Start(), WidgetQuestTracker.TryShow(), TraitTeleporter.TryTeleport(), and Zone.UpdateQuests().
MaxRandomQuest
const int QuestManager.MaxRandomQuest = 5 static
Definition at line 324 of file QuestManager.cs.
uid
int QuestManager.uid
Definition at line 339 of file QuestManager.cs.
Referenced by Get(), and Quest.Init().
Property Documentation
Home
new QuestHome QuestManager.Home get
Definition at line 17 of file QuestManager.cs.
    {
        get
        {
            return this.Get<QuestHome>();
        }
    }
Main
QuestMain QuestManager.Main get
Definition at line 9 of file QuestManager.cs.
    {
        get
        {
            return this.Get<QuestMain>();
        }
    }
Referenced by DramaOutcome.QuestExploration_AfterComplete(), and DramaOutcome.QuestExploration_MeetFarris2().
The documentation for this class was generated from the following file:
Elin/QuestManager.cs