Elin Decompiled Documentation: TCSimpleText Class Reference
TCSimpleText Class Reference
Static Public Member Functions
static TCSimpleText Spawn ()
static TCSimpleText SpawnIcon (Sprite sprite=null)
Static Public Member Functions inherited from EMono
static int rnd (int a)
Public Attributes
TextMesh tm
SpriteRenderer sr
int num
Additional Inherited Members
Static Public Attributes inherited from EMono
static Core core
Properties inherited from EMono
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SoundManager Sound [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static CoreDebug debug [get]
Detailed Description
Definition at line 3 of file TCSimpleText.cs.
Member Function Documentation
Spawn()
static TCSimpleText TCSimpleText.Spawn () inline static
Definition at line 11 of file TCSimpleText.cs.
    {
        return PoolManager.Spawn(EMono.core.refs.tcs.simpleText, EMono.screen);
    }
References EMono.core, Core.refs, EMono.screen, CoreRef.TCs.simpleText, PoolManager.Spawn(), and CoreRef.tcs.
Referenced by ActionMode.RefreshTexts().
SpawnIcon()
static TCSimpleText TCSimpleText.SpawnIcon (Sprite sprite = null) inline static
Definition at line 16 of file TCSimpleText.cs.
    {
        TCSimpleText tCSimpleText = PoolManager.Spawn(EMono.core.refs.tcs.simpleTextIcon, EMono.screen);
        if ((bool)tCSimpleText)
        {
            tCSimpleText.sr.sprite = sprite;
        }
        return tCSimpleText;
    }
References EMono.core, Core.refs, EMono.screen, CoreRef.TCs.simpleTextIcon, PoolManager.Spawn(), and CoreRef.tcs.
Referenced by ActionMode.RefreshTexts().
Member Data Documentation
num
int TCSimpleText.num
Definition at line 9 of file TCSimpleText.cs.
sr
SpriteRenderer TCSimpleText.sr
Definition at line 7 of file TCSimpleText.cs.
tm
TextMesh TCSimpleText.tm
Definition at line 5 of file TCSimpleText.cs.
Referenced by ActionMode.RefreshTexts().
The documentation for this class was generated from the following file:
Elin/TCSimpleText.cs