Elin Decompiled Documentation: CalcMoney Class Reference
CalcMoney Class Reference
Static Public Member Functions
static int Negotiate (int a, float mod=1.5f)
static int Invest (long a, float mod=2f)
static int Meal (Chara c)
static int Heal (Chara c)
static int Picklock (Chara c, Thing t)
static int Identify (Chara c, bool superior)
static int Revive (Chara c)
static int BuySlave (Chara c)
static int SellSlave (Chara c)
static int Whore (Chara seller, Chara buyer)
static int InvestShop (Chara c, Chara tc)
static int InvestZone (Chara c)
Static Public Member Functions inherited from EClass
static int rndSeed (int a, int seed)
static int rnd (long a)
static int rnd (int a)
static int curve (long _a, int start, int step, int rate=75)
static int sqrt (int a)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Additional Inherited Members
Static Public Attributes inherited from EClass
static Core core
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Detailed Description
Definition at line 3 of file CalcMoney.cs.
Member Function Documentation
BuySlave()
static int CalcMoney.BuySlave (Chara c) inline static
Definition at line 45 of file CalcMoney.cs.
    {
        return Negotiate((c.LV + 5) * (c.LV + 5) * 20 + Rand.rndSeed(c.LV * 20, c.uid));
    }
References Card.LV, Negotiate(), Rand.rndSeed(), and Card.uid.
Referenced by ListPeopleBuySlave.Cost().
Heal()
static int CalcMoney.Heal (Chara c) inline static
Definition at line 25 of file CalcMoney.cs.
    {
        return Negotiate(Guild.Fighter.ServicePrice(100));
    }
References Guild.Fighter, Negotiate(), and GuildFighter.ServicePrice().
Identify()
static int CalcMoney.Identify (Chara c, bool superior) inline static
Definition at line 35 of file CalcMoney.cs.
    {
        return Negotiate(Guild.Fighter.ServicePrice(superior ? 750 : 50));
    }
References Guild.Fighter, Negotiate(), and GuildFighter.ServicePrice().
Invest()
static int CalcMoney.Invest (long a, float mod = 2f) inline static
Definition at line 10 of file CalcMoney.cs.
    {
        long num = a * 100 / (long)(100f + (float)Mathf.Max(0, EClass.pc.CHA / 2 + EClass.pc.Evalue(292)) * mod);
        if (num >= 0 && num < 100000000)
        {
            return (int)num;
        }
        return 100000000;
    }
References Card.CHA, Card.Evalue(), and EClass.pc.
Referenced by InvestShop(), and InvestZone().
InvestShop()
static int CalcMoney.InvestShop (Chara c, Chara tc) inline static
Definition at line 67 of file CalcMoney.cs.
    {
        long a = Guild.Merchant.InvestPrice(tc.c_invest * 700);
        return Mathf.Max(b: Invest(Guild.Merchant.InvestPrice(tc.c_invest * tc.c_invest * 80 + 200)), a: Invest(a));
    }
References Card.c_invest, Invest(), GuildMerchant.InvestPrice(), and Guild.Merchant.
InvestZone()
static int CalcMoney.InvestZone (Chara c) inline static
Definition at line 73 of file CalcMoney.cs.
    {
        long a = EClass._zone.development * 50;
        return Mathf.Max(b: Invest((long)EClass._zone.development * (long)EClass._zone.development / 4 + 500), a: Invest(a));
    }
References EClass._zone, Spatial.development, and Invest().
Meal()
static int CalcMoney.Meal (Chara c) inline static
Definition at line 20 of file CalcMoney.cs.
    {
        return Negotiate(Guild.Fighter.ServicePrice(70));
    }
References Guild.Fighter, Negotiate(), and GuildFighter.ServicePrice().
Negotiate()
static int CalcMoney.Negotiate (int a, float mod = 1::5f) inline static
Definition at line 5 of file CalcMoney.cs.
    {
        return Mathf.Max((int)((float)((long)a * 100L) / (100f + (float)Mathf.Max(0, EClass.pc.CHA / 2 + EClass.pc.Evalue(291)) * mod)), 1);
    }
References Card.CHA, Card.Evalue(), and EClass.pc.
Referenced by BuySlave(), Heal(), Identify(), Meal(), Picklock(), and Revive().
Picklock()
static int CalcMoney.Picklock (Chara c, Thing t) inline static
Definition at line 30 of file CalcMoney.cs.
    {
        return Negotiate(Guild.Fighter.ServicePrice(t.c_lockLv * 65 + 75));
    }
References Card.c_lockLv, Guild.Fighter, Negotiate(), and GuildFighter.ServicePrice().
Revive()
static int CalcMoney.Revive (Chara c) inline static
Definition at line 40 of file CalcMoney.cs.
    {
        return Negotiate((c.LV + 5) * (c.LV + 5) * 3);
    }
References Card.LV, and Negotiate().
Referenced by ListPeopleRevive.OnClick(), and ListPeopleRevive.OnInstantiate().
SellSlave()
static int CalcMoney.SellSlave (Chara c) inline static
Definition at line 50 of file CalcMoney.cs.
    {
        return (c.LV + 5) * (c.LV + 5) * 5;
    }
References Card.LV.
Whore()
static int CalcMoney.Whore (Chara seller, Chara buyer) inline static
Definition at line 55 of file CalcMoney.cs.
    {
        int num = Mathf.Max(seller.CHA * 6, 20) * ((!buyer.IsWealthy) ? 1 : 2);
        int num2 = Mathf.Max(buyer.CHA * 12, 20) * ((!buyer.IsWealthy) ? 1 : 2);
        Debug.Log("seller:" + num + " buyer:" + num2 + " wealthy:" + buyer.IsWealthy);
        if (num > num2)
        {
            num = num2;
        }
        return num;
    }
References Card.CHA, Debug, and Chara.IsWealthy.
Referenced by AI_Fuck.Finish().
The documentation for this class was generated from the following file:
Elin/CalcMoney.cs