Elin Decompiled Documentation: LayerTech Class Reference
LayerTech Class Reference
Public Member Functions
override void OnInit ()
void RefreshTech ()
void RefreshFocus ()
Public Member Functions inherited from ELayer
override void OnBeforeAddLayer ()
void InitInspector ()
sealed override void Init ()
override void OnAfterAddLayer ()
void TryShowHelp ()
void AddLayerToUI (string id)
void TryShowHint (string _langHint=null)
void TalkHomeMemeber (string id)
void TalkMaid (string id)
override void OnRightClick ()
Public Attributes
UIList listTech
UIText textHeader
bool listComplete
Additional Inherited Members
Static Public Member Functions inherited from ELayer
static int rnd (int a)
Protected Member Functions inherited from ELayer
sealed override void _Close ()
sealed override void Kill ()
Properties inherited from ELayer
static Core core [get]
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static FactionBranch Branch [get]
static Faction Home [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static CoreConfig config [get]
static GameSetting setting [get]
static ColorProfile Colors [get]
static SourceManager sources [get]
static World world [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
bool IsFloat [get]
virtual string IdHelp [get]
Detailed Description
Definition at line 3 of file LayerTech.cs.
Member Function Documentation
OnInit()
override void LayerTech.OnInit () inline
Definition at line 5 of file LayerTech.cs.
    {
        this.RefreshTech();
    }
References RefreshTech().
RefreshFocus()
void LayerTech.RefreshFocus () inline
Definition at line 41 of file LayerTech.cs.
    {
        foreach (ItemResearch itemResearch in this.listTech.GetComponentsInChildren<ItemResearch>())
        {
            itemResearch.goFocus.SetActive(itemResearch.plan == ELayer.Branch.researches.focused);
        }
    }
References ELayer.Branch, ResearchManager.focused, ItemResearch.goFocus, listTech, ItemResearch.plan, and FactionBranch.researches.
Referenced by RefreshTech().
RefreshTech()
void LayerTech.RefreshTech () inline
Definition at line 10 of file LayerTech.cs.
    {
        WindowMenu menuRight = this.windows[0].menuRight;
        menuRight.Clear();
        menuRight.AddButton2Line("toggle", () => (this.listComplete ? "toggleComplete" : "toggleIncomplete").lang(), delegate(UIButton b)
        {
            this.listComplete = !this.listComplete;
            this.RefreshTech();
        }, null, "2line");
        this.textHeader.text = (this.listComplete ? "headerResearched" : "headerResearching").lang();
        UIList list = this.listTech;
        list.sortMode = ELayer.player.pref.sortResearch;
        BaseList list2 = list;
        UIList.Callback<ResearchPlan, ItemResearch> callback = new UIList.Callback<ResearchPlan, ItemResearch>();
        callback.onInstantiate = delegate(ResearchPlan a, ItemResearch b)
        {
            b.SetPlan(a, list, ELayer.Branch, this);
        };
        callback.onList = delegate(UIList.SortMode m)
        {
            foreach (ResearchPlan o in (this.listComplete ? ELayer.Branch.researches.finished : ELayer.Branch.researches.plans))
            {
                list.Add(o);
            }
        };
        callback.onSort = ((ResearchPlan a, UIList.SortMode m) => a.GetSortVal(m));
        list2.callbacks = callback;
        list.List(false);
        this.RefreshFocus();
    }
References ELayer.Branch, ResearchManager.finished, ResearchPlan.GetSortVal(), listComplete, listTech, ResearchManager.plans, ELayer.player, Player.pref, RefreshFocus(), RefreshTech(), FactionBranch.researches, and ItemResearch.SetPlan().
Referenced by OnInit(), RefreshTech(), and ItemResearch.SetPlan().
Member Data Documentation
listComplete
bool LayerTech.listComplete
Definition at line 53 of file LayerTech.cs.
Referenced by RefreshTech().
listTech
UIList LayerTech.listTech
Definition at line 49 of file LayerTech.cs.
Referenced by RefreshFocus(), and RefreshTech().
textHeader
UIText LayerTech.textHeader
Definition at line 51 of file LayerTech.cs.
The documentation for this class was generated from the following file:
Elin/LayerTech.cs