Elin Decompiled Documentation: LayerTextureViewer Class Reference
LayerTextureViewer Class Reference
Public Member Functions
override void OnInit ()
override void OnSwitchContent (Window window)
void RefreshPage ()
void SetPos (Component r, int x, int y, float size=0f, Vector2 posFix=default(Vector2))
Public Member Functions inherited from ELayer
override void OnBeforeAddLayer ()
void InitInspector ()
sealed override void Init ()
override void OnAfterAddLayer ()
void TryShowHelp ()
void AddLayerToUI (string id)
void TryShowHint (string _langHint=null)
void TalkHomeMemeber (string id)
void TalkMaid (string id)
override void OnRightClick ()
Public Member Functions inherited from Layer
virtual string GetTextHeader (Window window)
virtual bool HeaderIsListOf (int id)
virtual void Init ()
virtual void OnInit ()
virtual void OnAfterInit ()
virtual void ApplySkin ()
void ShowScreenLock (string id)
void UpdateInput ()
virtual void OnUpdateInput ()
virtual void OnRightClick ()
virtual bool OnBack ()
virtual void OnChangeLayer ()
virtual void OnCreate ()
void _AddLayer (string id)
Layer AddLayer (string id)
T AddLayer< T > ()
T AddLayer< T > (string id)
T AddLayerDontCloseOthers< T > ()
Layer AddLayerDontCloseOthers (Layer l)
T GetOrAddLayer< T > ()
virtual void OnBeforeAddLayer ()
virtual void OnAfterAddLayer ()
Layer AddLayer (Layer l)
void ToggleLayer (string id)
T ToggleLayer< T > (string id=null)
void WaitAndClose ()
void OnClickClose ()
virtual void Close ()
void CloseLayers ()
void RemoveLayers (bool removeImportant=false)
bool RemoveLayer< T > ()
void RemoveLayer (Layer l)
virtual void OnKill ()
Layer SetOnKill (Action action)
void DisableClose ()
void Delay (float duration=0.05f)
Layer SetDelay (float d)
Layer GetLayer (string id)
T GetLayer< T > (bool fromTop=false)
Layer GetTopLayer ()
void SwitchContent (int idWindow, int i)
virtual void OnSwitchContent (Window window)
Layer SetTitles (string langList, string idHeaderRow=null)
bool IsBlockWidgetClick ()
bool IsHideHud ()
bool IsAllowGeneralInput ()
bool IsUseBlur ()
bool IsPointerOnLayer ()
void ApplySkin ()
Public Attributes
RawImage imageTex
Image highlight
Image moldMarker
TextureData data
UIScrollView view
Scrollbar scrollbarH
Scrollbar scrollvarV
UIText textHint
Transform transMask
float scale
float highlightSize
List< Image > markers = new List<Image>()
Vector2 markerFix
Color colorUser
Color colorMod
Color colorLocal
int sizeX
int sizeY
bool fixZoom
bool snow
Vector2 test
Public Attributes inherited from Layer
Option option
UnityEvent onKill
Anime animeIn
Anime animeOut
bool closeOthers
bool defaultActionMode = true
Button screenLock
Layer parent
string idLayer
List< Layer > layers = new List<Layer>()
Vector2 lastParentPos
List< Window > windows = new List<Window>()
string langHint
Private Member Functions
void Update ()
Private Attributes
bool zoom
Additional Inherited Members
Static Public Member Functions inherited from ELayer
static int rnd (int a)
Static Public Member Functions inherited from Layer
static T Create< T > ()
static T Create< T > (string path)
static Layer Create (string path)
Static Public Attributes inherited from Layer
static int skipInput
static bool closeOnRightClick
static bool rightClicked
static bool cancelKeyDown
static bool ignoreSounds
static Transform blurStopInstance
static string[] searchPath = new string[3] { "Layer", "Layer/Dialog", "Layer/LayerHome" }
Protected Member Functions inherited from ELayer
sealed override void _Close ()
sealed override void Kill ()
Protected Member Functions inherited from Layer
virtual void Awake ()
virtual void _Close ()
virtual void Kill ()
Protected Attributes inherited from Layer
RectTransform _rect
bool isDestroyed
Properties inherited from ELayer
static Core core [get]
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static FactionBranch Branch [get]
static Faction Home [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static CoreConfig config [get]
static GameSetting setting [get]
static ColorProfile Colors [get]
static SourceManager sources [get]
static World world [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
bool IsFloat [get]
virtual string IdHelp [get]
Properties inherited from Layer
Layer TopLayer [get]
string uid [get]
virtual RectTransform rectLayers [get]
virtual bool blockWidgetClick [get]
Detailed Description
Definition at line 5 of file LayerTextureViewer.cs.
Member Function Documentation
OnInit()
override void LayerTextureViewer.OnInit () inline virtual
Reimplemented from Layer.
Definition at line 51 of file LayerTextureViewer.cs.
    {
        windows[0].AddBottomSpace();
        windows[0].AddBottomButton("openUser", delegate
        {
            Util.ShowExplorer(CorePath.user + "Texture Replace/dummy.txt");
        });
        windows[0].AddBottomButton("toggleSnowTexture", delegate
        {
            SE.Tab();
            snow = !snow;
            OnSwitchContent(windows[0]);
        });
    }
References OnSwitchContent(), snow, CorePath.user, Util, and Layer.windows.
OnSwitchContent()
override void LayerTextureViewer.OnSwitchContent (Window window) inline virtual
Reimplemented from Layer.
Definition at line 66 of file LayerTextureViewer.cs.
    {
        data = ELayer.core.textures.texMap.TryGetValue(window.CurrentTab.idLang + (snow ? "Snow" : "")) ?? ELayer.core.textures.texMap[window.CurrentTab.idLang];
        RefreshPage();
        scrollbarH.value = 0f;
        scrollvarV.value = 1f;
    }
References ELayer.core, Window.CurrentTab, data, RefreshPage(), snow, TextureManager.texMap, and Core.textures.
Referenced by OnInit().
RefreshPage()
void LayerTextureViewer.RefreshPage () inline
Definition at line 74 of file LayerTextureViewer.cs.
    {
        scale = 0.5f;
        switch (data.id)
        {
        case "objS":
        case "objSS":
        case "objSSnow":
        case "objSSSnow":
            scale = 1f;
            break;
        }
        if (zoom)
        {
            scale *= 2f;
        }
        if (fixZoom)
        {
            scale /= ELayer.ui.canvasScaler.scaleFactor;
        }
        imageTex.texture = null;
        imageTex.texture = data.tex;
        imageTex.rectTransform.sizeDelta = new Vector2((float)data.tex.width * scale, (float)data.tex.height * scale);
        imageTex.RebuildLayoutTo<Layer>();
        foreach (Image marker in markers)
        {
            Object.Destroy(marker.gameObject);
        }
        markers.Clear();
        foreach (TextureReplace value in data.dictReplace.Values)
        {
            Image image = Util.Instantiate(moldMarker, imageTex.transform.parent);
            image.rectTransform.sizeDelta = new Vector2(((float)Mathf.Max(value.w, data.tileW) + highlightSize * 2f) * scale, ((float)Mathf.Max(value.h, data.tileH) + highlightSize * 2f) * scale);
            SetPos(image, value.index % 100, value.index / 100 * -1, highlightSize, markerFix);
            image.color = ((value.source == TextureReplace.Source.Local) ? colorLocal : ((value.source == TextureReplace.Source.User) ? colorUser : colorMod));
            markers.Add(image);
        }
    }
References colorLocal, colorMod, colorUser, data, TextureData.dictReplace, fixZoom, TextureReplace.h, highlightSize, TextureData.id, imageTex, TextureReplace.index, markerFix, markers, moldMarker, scale, SetPos(), TextureReplace.source, TextureData.tex, TextureData.tileH, TextureData.tileW, ELayer.ui, Util, TextureReplace.w, and zoom.
Referenced by OnSwitchContent(), and Update().
SetPos()
void LayerTextureViewer.SetPos (Component r, int x, int y, float size = 0f, Vector2 posFix = default(Vector2)) inline
Definition at line 113 of file LayerTextureViewer.cs.
    {
        r.Rect().anchoredPosition = new Vector2((float)(x * data.tileW) * scale * test.x - highlightSize * scale, (float)(y * data.tileH) * scale * test.y + highlightSize * scale) + posFix;
    }
References data, highlightSize, scale, test, TextureData.tileH, and TextureData.tileW.
Referenced by RefreshPage(), and Update().
Update()
void LayerTextureViewer.Update () inline private
Definition at line 118 of file LayerTextureViewer.cs.
    {
        _ = imageTex.rectTransform;
        RectTransformUtility.ScreenPointToLocalPointInRectangle(imageTex.rectTransform, Input.mousePosition, ELayer.ui.canvas.worldCamera, out var localPoint);
        int num = (int)localPoint.x / (int)((float)data.tileW * scale);
        int num2 = (int)localPoint.y / (int)((float)data.tileH * scale);
        if (EInput.axis != Vector2.zero)
        {
            sizeX = Mathf.Clamp(sizeX + (int)EInput.axis.x, 1, 5);
            sizeY = Mathf.Clamp(sizeY + (int)EInput.axis.y * -1, 1, 5);
            EInput.requireAxisReset = true;
        }
        if (EInput.middleMouse.clicked)
        {
            SE.Tab();
            zoom = !zoom;
            RefreshPage();
        }
        bool flag = InputModuleEX.IsPointerOver(transMask);
        highlight.SetActive(flag);
        if (!flag)
        {
            return;
        }
        highlight.rectTransform.sizeDelta = new Vector2(((float)(data.tileW * sizeX) + highlightSize * 2f) * scale, ((float)(data.tileH * sizeY) + highlightSize * 2f) * scale);
        SetPos(highlight, num, num2, highlightSize);
        string text = data.id + "_";
        int index = Mathf.Abs(num2) * 100 + num;
        text += index;
        textHint.text = text + ((sizeX == 1 && sizeY == 1) ? "" : ("(" + sizeX + "x" + sizeY + ")"));
        if (!EInput.leftMouse.clicked)
        {
            return;
        }
        UIContextMenu uIContextMenu = ELayer.ui.CreateContextMenuInteraction();
        TextureReplace replace = data.dictReplace.TryGetValue(index);
        if (replace != null)
        {
            uIContextMenu.AddButton("open_replace", delegate
            {
                Util.Run(replace.file.FullName);
            });
            if (replace.source != TextureReplace.Source.Mod)
            {
                uIContextMenu.AddButton("delete_replace", delegate
                {
                    try
                    {
                        data.DeleteReplace(replace);
                        data.ForceRefresh();
                    }
                    catch
                    {
                    }
                    SE.Trash();
                    RefreshPage();
                });
            }
        }
        else
        {
            uIContextMenu.AddButton("create_replace", delegate
            {
                data.CreateReplace(index, CorePath.user + "Texture Replace/", TextureReplace.Source.User, sizeX, sizeY);
                SE.Change();
                RefreshPage();
            });
        }
        if (ELayer._zone.isMapSaved && (replace == null || replace.source != TextureReplace.Source.Local))
        {
            uIContextMenu.AddButton("create_replaceLocal", delegate
            {
                string text2 = ELayer._zone.pathSave + "Texture Replace";
                IO.CreateDirectory(text2);
                data.CreateReplace(index, text2 + "/", TextureReplace.Source.Local, sizeX, sizeY);
                SE.Change();
                RefreshPage();
            });
        }
        uIContextMenu.Show();
    }
References ELayer._zone, UIContextMenu.AddButton(), EInput.axis, ButtonState.clicked, TextureData.CreateReplace(), data, TextureData.DeleteReplace(), TextureData.dictReplace, TextureReplace.file, TextureData.ForceRefresh(), highlight, highlightSize, imageTex, Spatial.isMapSaved, InputModuleEX.IsPointerOver(), EInput.leftMouse, EInput.middleMouse, RefreshPage(), scale, SetPos(), UIContextMenu.Show(), sizeX, sizeY, TextureReplace.source, TextureData.tileH, TextureData.tileW, transMask, ELayer.ui, CorePath.user, Util, and zoom.
Member Data Documentation
colorLocal
Color LayerTextureViewer.colorLocal
Definition at line 37 of file LayerTextureViewer.cs.
Referenced by RefreshPage().
colorMod
Color LayerTextureViewer.colorMod
Definition at line 35 of file LayerTextureViewer.cs.
Referenced by RefreshPage().
colorUser
Color LayerTextureViewer.colorUser
Definition at line 33 of file LayerTextureViewer.cs.
Referenced by RefreshPage().
data
TextureData LayerTextureViewer.data
Definition at line 13 of file LayerTextureViewer.cs.
Referenced by OnSwitchContent(), RefreshPage(), SetPos(), and Update().
fixZoom
bool LayerTextureViewer.fixZoom
Definition at line 43 of file LayerTextureViewer.cs.
Referenced by RefreshPage().
highlight
Image LayerTextureViewer.highlight
Definition at line 9 of file LayerTextureViewer.cs.
Referenced by Update().
highlightSize
float LayerTextureViewer.highlightSize
Definition at line 27 of file LayerTextureViewer.cs.
Referenced by RefreshPage(), SetPos(), and Update().
imageTex
RawImage LayerTextureViewer.imageTex
Definition at line 7 of file LayerTextureViewer.cs.
Referenced by RefreshPage(), and Update().
markerFix
Vector2 LayerTextureViewer.markerFix
Definition at line 31 of file LayerTextureViewer.cs.
Referenced by RefreshPage().
markers
List<Image> LayerTextureViewer.markers = new List<Image>()
Definition at line 29 of file LayerTextureViewer.cs.
Referenced by RefreshPage().
moldMarker
Image LayerTextureViewer.moldMarker
Definition at line 11 of file LayerTextureViewer.cs.
Referenced by RefreshPage().
scale
float LayerTextureViewer.scale
Definition at line 25 of file LayerTextureViewer.cs.
Referenced by RefreshPage(), SetPos(), and Update().
scrollbarH
Scrollbar LayerTextureViewer.scrollbarH
Definition at line 17 of file LayerTextureViewer.cs.
scrollvarV
Scrollbar LayerTextureViewer.scrollvarV
Definition at line 19 of file LayerTextureViewer.cs.
sizeX
int LayerTextureViewer.sizeX
Definition at line 39 of file LayerTextureViewer.cs.
Referenced by Update().
sizeY
int LayerTextureViewer.sizeY
Definition at line 41 of file LayerTextureViewer.cs.
Referenced by Update().
snow
bool LayerTextureViewer.snow
Definition at line 45 of file LayerTextureViewer.cs.
Referenced by OnInit(), and OnSwitchContent().
test
Vector2 LayerTextureViewer.test
Definition at line 47 of file LayerTextureViewer.cs.
Referenced by SetPos().
textHint
UIText LayerTextureViewer.textHint
Definition at line 21 of file LayerTextureViewer.cs.
transMask
Transform LayerTextureViewer.transMask
Definition at line 23 of file LayerTextureViewer.cs.
Referenced by Update().
view
UIScrollView LayerTextureViewer.view
Definition at line 15 of file LayerTextureViewer.cs.
zoom
bool LayerTextureViewer.zoom private
Definition at line 49 of file LayerTextureViewer.cs.
Referenced by RefreshPage(), and Update().
The documentation for this class was generated from the following file:
Elin/LayerTextureViewer.cs