Elin Decompiled Documentation: HotItemToggleVisible Class Reference
HotItemToggleVisible Class Reference
Public Member Functions
override bool ShouldHighlight ()
override Sprite GetSprite (bool highlight)
override void OnHover (UIButton b)
override void OnClick (ButtonHotItem b, Hotbar h)
Public Member Functions inherited from HotItemIcon
override Sprite GetSprite ()
Public Member Functions inherited from HotItem
string TextHotkey ()
virtual void OnClick (ButtonHotItem b, Hotbar h)
virtual void OnRightClick (ButtonHotItem b)
virtual bool CanAutoFire (Chara tg)
virtual void OnSetCurrentItem ()
virtual void OnUnsetCurrentItem ()
virtual void OnUnselect ()
virtual void SetImage (Image icon)
virtual bool TrySetAct (ActPlan p)
virtual void OnMarkMapHighlights ()
virtual void OnRenderTile (Point point, HitResult result, int dir)
Public Member Functions inherited from UIButton.Item
virtual Sprite GetSprite ()
virtual Sprite GetSprite (bool highlight)
virtual bool ShouldHighlight ()
virtual void OnAddedToBar ()
virtual void OnShowContextMenu (UIContextMenu m)
virtual void OnHover (UIButton b)
virtual void OnClick (UIButton b)
virtual void OnSetItem (UIButton b)
virtual void SetSubText (UIText t)
Public Attributes
bool sticky
Public Attributes inherited from HotItem
ButtonHotItem button
Hotbar hotbar
bool disabled
Public Attributes inherited from UIButton.Item
bool always
Properties
override string Name [get]
override string TextTip [get]
override bool KeepVisibleWhenHighlighted [get]
override bool UseIconForHighlight [get]
Properties inherited from HotItemIcon
virtual int defaultIcon [get]
Properties inherited from HotItem
override Sprite SpriteHighlight [get]
override bool IsSelectable [get]
override string TextTip [get]
virtual Thing RenderThing [get]
virtual Thing Thing [get]
virtual Thing Tool [get]
virtual bool IsTool [get]
virtual bool LookAtMouse [get]
virtual bool IsGameAction [get]
virtual bool UseUIObjMaterial [get]
Properties inherited from UIButton.Item
virtual string TextTip [get]
virtual string Name [get]
virtual Sprite SpriteHighlight [get]
virtual string pathSprite [get]
virtual bool IsSelectable [get]
virtual bool AdjustImageSize [get]
virtual bool UseIconForHighlight [get]
virtual bool KeepVisibleWhenHighlighted [get]
virtual Color SpriteColor [get]
virtual Vector3 SpriteScale [get]
virtual bool Hidden [get]
virtual Transition Transition [get]
Detailed Description
Definition at line 3 of file HotItemToggleVisible.cs.
Member Function Documentation
GetSprite()
override Sprite HotItemToggleVisible.GetSprite (bool highlight) inline virtual
Reimplemented from UIButton.Item.
Definition at line 20 of file HotItemToggleVisible.cs.
    {
        if (!highlight)
        {
            return GetSprite();
        }
        return SpriteSheet.Get("icon_visible_highlight");
    }
References SpriteSheet.Get(), and HotItemIcon.GetSprite().
OnClick()
override void HotItemToggleVisible.OnClick (ButtonHotItem b, Hotbar h) inline virtual
Reimplemented from HotItem.
Definition at line 38 of file HotItemToggleVisible.cs.
    {
        if (!b)
        {
            SE.Beep();
            return;
        }
        if (b.widget.Visible)
        {
            SE.ClickGeneral();
            sticky = !sticky;
        }
        else
        {
            SE.Play("pop_context");
            b.widget.ToggleVisible();
        }
        b.widget.RefreshHighlight();
    }
References WidgetHotbar.RefreshHighlight(), sticky, WidgetHotbar.ToggleVisible(), WidgetHotbar.Visible, and ButtonHotItem.widget.
Referenced by OnHover().
OnHover()
override void HotItemToggleVisible.OnHover (UIButton b) inline virtual
Reimplemented from UIButton.Item.
Definition at line 29 of file HotItemToggleVisible.cs.
    {
        ButtonHotItem buttonHotItem = b as ButtonHotItem;
        if (!buttonHotItem.widget.Visible)
        {
            OnClick(buttonHotItem, buttonHotItem.widget.hotbar);
        }
    }
References WidgetHotbar.hotbar, OnClick(), WidgetHotbar.Visible, and ButtonHotItem.widget.
ShouldHighlight()
override bool HotItemToggleVisible.ShouldHighlight () inline virtual
Reimplemented from UIButton.Item.
Definition at line 15 of file HotItemToggleVisible.cs.
    {
        return sticky;
    }
References sticky.
Member Data Documentation
sticky
bool HotItemToggleVisible.sticky
Definition at line 5 of file HotItemToggleVisible.cs.
Referenced by OnClick(), and ShouldHighlight().
Property Documentation
KeepVisibleWhenHighlighted
override bool HotItemToggleVisible.KeepVisibleWhenHighlighted get
Definition at line 11 of file HotItemToggleVisible.cs.
Name
override string HotItemToggleVisible.Name get
Definition at line 7 of file HotItemToggleVisible.cs.
TextTip
override string HotItemToggleVisible.TextTip get
Definition at line 9 of file HotItemToggleVisible.cs.
UseIconForHighlight
override bool HotItemToggleVisible.UseIconForHighlight get
Definition at line 13 of file HotItemToggleVisible.cs.
The documentation for this class was generated from the following file:
Elin/HotItemToggleVisible.cs