Elin Decompiled Documentation: ContentStatistics Class Reference
ContentStatistics Class Reference
Public Member Functions
override void OnSwitchContent (int idTab)
Public Member Functions inherited from UIContent
virtual void OnSwitchContent (int idTab)
virtual void OnInstantiate ()
Public Member Functions inherited from UINote
void Clear ()
void Build ()
void Space (int sizeY=0, int sizeX=1)
UINote AddNote (string id)
UIItem AddHeader (string text, Sprite sprite=null)
UIItem AddHeaderCard (string text, Sprite sprite=null)
UIItem AddHeaderTopic (string text, Sprite sprite=null)
UIItem AddHeader (string id, string text, Sprite sprite=null)
UIItem AddText (string text, FontColor color=FontColor.DontChange)
UIItem AddText (string id, string text, FontColor color=FontColor.DontChange)
UIItem AddText (string id, string text, Color color)
UIItem AddItem (string id)
UIItem AddTopic (string id, string text, string value=null)
UIItem AddTopic (string text, string value=null)
void AddImage (Sprite sprite)
void AddImage (string idFile)
UIButton AddButton (string text, Action onClick)
UIButton AddButtonLink (string text, string url)
UIDropdown AddDropdown (string id="DropdownDefault")
UIButton AddToggle (string idLang="", bool isOn=false, Action< bool > action=null)
Transform AddPrefab (string path)
T AddExtra< T > (string path)
Public Attributes
UIList list1
UIList list2
Public Attributes inherited from UINote
RectTransform target
UINoteProfile prof
SkinType skinType
string idDefaultText
LayoutGroup layout
RectTransform cur
bool extraRebuild
Detailed Description
Definition at line 1 of file ContentStatistics.cs.
Member Function Documentation
OnSwitchContent()
override void ContentStatistics.OnSwitchContent (int idTab) inline virtual
Reimplemented from UIContent.
Definition at line 7 of file ContentStatistics.cs.
    {
        NumLogManager nums = EClass.player.nums;
        list1.callbacks = new UIList.Callback<NumLog, ItemNumLog>
        {
            onInstantiate = delegate(NumLog a, ItemNumLog b)
            {
                b.SetLog(a);
            }
        };
        list2.callbacks = new UIList.Callback<NumLog, ItemNumLog>
        {
            onInstantiate = delegate(NumLog a, ItemNumLog b)
            {
                b.SetLog(a);
            }
        };
        foreach (NumLog item in nums.listCategory)
        {
            list1.Add(item);
        }
        foreach (NumLog item2 in nums.listImportant)
        {
            list2.Add(item2);
        }
        list1.Refresh();
        list2.Refresh();
        this.RebuildLayout(recursive: true);
    }
References UIList.Add(), item, list1, list2, Player.nums, EClass.player, UIList.Refresh(), and ItemNumLog.SetLog().
Member Data Documentation
list1
UIList ContentStatistics.list1
Definition at line 3 of file ContentStatistics.cs.
Referenced by OnSwitchContent().
list2
UIList ContentStatistics.list2
Definition at line 5 of file ContentStatistics.cs.
Referenced by OnSwitchContent().
The documentation for this class was generated from the following file:
Elin/ContentStatistics.cs