Elin Decompiled Documentation: ButtonResourceTrack Class Reference
ButtonResourceTrack Class Reference
Public Member Functions
void SetProp (string id)
void SetCat (string id)
void Refresh ()
Public Attributes
PropSet prop
PropSetCategory cat
Properties
UIResourceTrack track [get]
Detailed Description
Definition at line 3 of file ButtonResourceTrack.cs.
Member Function Documentation
Refresh()
void ButtonResourceTrack.Refresh () inline
Definition at line 42 of file ButtonResourceTrack.cs.
    {
        if (cat != null)
        {
            subText.SetText(cat.sum.ToString() ?? "");
            return;
        }
        int num = ((prop != null) ? prop.num : 0);
        subText.SetText(num.ToString() ?? "");
    }
References cat, PropSet.num, prop, and PropSetCategory.sum.
Referenced by SetCat(), and SetProp().
SetCat()
void ButtonResourceTrack.SetCat (string id) inline
Definition at line 28 of file ButtonResourceTrack.cs.
    {
        cat = EClass._map.Stocked.categoryMap[id];
        tooltip.text = cat.source.GetName();
        tooltip.enable = true;
        onRightClick = delegate
        {
            EClass.player.trackedCategories.Remove(id);
            track._Refresh();
            SE.Trash();
        };
        Refresh();
    }
References EClass._map, UIResourceTrack._Refresh(), cat, Props.categoryMap, EClass.player, Refresh(), PropSetCategory.source, Map.Stocked, track, and Player.trackedCategories.
Referenced by UIResourceTrack._Refresh().
SetProp()
void ButtonResourceTrack.SetProp (string id) inline
Definition at line 11 of file ButtonResourceTrack.cs.
    {
        Debug.Log(id);
        prop = EClass._map.Stocked.cardMap.GetOrCreate(id);
        CardRow cardRow = EClass.sources.cards.map[id];
        tooltip.text = cardRow.GetName();
        tooltip.enable = true;
        cardRow.SetImage(icon);
        onRightClick = delegate
        {
            EClass.player.trackedCards.Remove(id);
            track._Refresh();
            SE.Trash();
        };
        Refresh();
    }
References EClass._map, UIResourceTrack._Refresh(), Props.cardMap, SourceManager.cards, CardRow.GetName(), SourceCard.map, EClass.player, prop, Refresh(), RenderRow.SetImage(), EClass.sources, Map.Stocked, track, and Player.trackedCards.
Referenced by UIResourceTrack._Refresh().
Member Data Documentation
cat
PropSetCategory ButtonResourceTrack.cat
Definition at line 7 of file ButtonResourceTrack.cs.
Referenced by Refresh(), and SetCat().
prop
PropSet ButtonResourceTrack.prop
Definition at line 5 of file ButtonResourceTrack.cs.
Referenced by Refresh(), and SetProp().
Property Documentation
track
UIResourceTrack ButtonResourceTrack.track get
Definition at line 9 of file ButtonResourceTrack.cs.
Referenced by SetCat(), and SetProp().
The documentation for this class was generated from the following file:
Elin/ButtonResourceTrack.cs