Elin Decompiled Documentation: PathProgress Class Reference
PathProgress Class Reference
Public Types
enum State { Idle , Searching , PathReady , Fail }
Public Member Functions
bool IsDestinationReached (Point pos)
void RequestPath (Point _startPoint, Point _destPoint, int _destDist, bool _ignoreConnection, int _searchLimit=-1)
void RequestPathImmediate (Point _startPoint, Point _destPoint, int _destDist, bool _ignoreConnection, int _searchLimit=-1)
Public Attributes
IPathfindWalker walker
List< PathFinderNode > nodes = new List<PathFinderNode>()
Point startPoint = new Point()
Point destPoint = new Point()
int nodeIndex
State state
int destDist
int searchLimit
bool ignoreConnection
PathManager.MoveType moveType
Properties
bool HasPath [get]
Detailed Description
Definition at line 4 of file PathProgress.cs.
Member Enumeration Documentation
State
enum PathProgress.State
Enumerator
Idle
Searching
PathReady
Fail
Definition at line 6 of file PathProgress.cs.
    {
        Idle,
        Searching,
        PathReady,
        Fail
    }
Member Function Documentation
IsDestinationReached()
bool PathProgress.IsDestinationReached (Point pos) inline
Definition at line 46 of file PathProgress.cs.
    {
        return Util.Distance(pos.x, pos.z, destPoint.x, destPoint.z) <= destDist;
    }
References destDist, destPoint, Util, Point.x, and Point.z.
RequestPath()
void PathProgress.RequestPath (Point _startPoint, Point _destPoint, int _destDist, bool _ignoreConnection, int _searchLimit = -1) inline
Definition at line 51 of file PathProgress.cs.
    {
        startPoint.Set(_startPoint);
        destPoint.Set(_destPoint);
        destDist = _destDist;
        ignoreConnection = _ignoreConnection;
        searchLimit = ((_searchLimit == -1) ? PathManager.Instance.searchLimit : _searchLimit);
        PathManager.Instance.RequestPath(this);
    }
References destDist, destPoint, ignoreConnection, PathManager.Instance, PathManager.RequestPath(), PathManager.searchLimit, searchLimit, Point.Set(), and startPoint.
Referenced by AI_Goto.TryGoTo().
RequestPathImmediate()
void PathProgress.RequestPathImmediate (Point _startPoint, Point _destPoint, int _destDist, bool _ignoreConnection, int _searchLimit = -1) inline
Definition at line 61 of file PathProgress.cs.
    {
        startPoint.Set(_startPoint);
        destPoint.Set(_destPoint);
        destDist = _destDist;
        ignoreConnection = _ignoreConnection;
        searchLimit = ((_searchLimit == -1) ? PathManager.Instance.searchLimit : _searchLimit);
        PathManager.Instance.RequestPathImmediate(this);
    }
References destDist, destPoint, ignoreConnection, PathManager.Instance, PathManager.RequestPathImmediate(), PathManager.searchLimit, searchLimit, Point.Set(), and startPoint.
Referenced by PathManager._GetFirstStep(), PathManager.IsPathClear(), PathManager.RequestPathImmediate(), and AI_Goto.TryGoTo().
Member Data Documentation
destDist
int PathProgress.destDist
Definition at line 26 of file PathProgress.cs.
Referenced by IsDestinationReached(), RequestPath(), and RequestPathImmediate().
destPoint
Point PathProgress.destPoint = new Point()
Definition at line 20 of file PathProgress.cs.
Referenced by Algorithms.PathFinder._FindPath(), IsDestinationReached(), RequestPath(), and RequestPathImmediate().
ignoreConnection
bool PathProgress.ignoreConnection
Definition at line 30 of file PathProgress.cs.
Referenced by Algorithms.PathFinder._FindPath(), RequestPath(), and RequestPathImmediate().
moveType
PathManager.MoveType PathProgress.moveType
Definition at line 32 of file PathProgress.cs.
Referenced by Algorithms.PathFinder.FindPath().
nodeIndex
int PathProgress.nodeIndex
Definition at line 22 of file PathProgress.cs.
Referenced by AI_Goto.TryGoTo().
nodes
List<PathFinderNode> PathProgress.nodes = new List<PathFinderNode>()
Definition at line 16 of file PathProgress.cs.
Referenced by Algorithms.PathFinder._FindPath(), PathManager._GetFirstStep(), Spatial.Dist(), Algorithms.PathFinder.FindPath(), PathManager.IsPathClear(), AI_Goto.TryGoTo(), Chara.TryMoveTowards(), and GameUpdater.Update().
searchLimit
int PathProgress.searchLimit
Definition at line 28 of file PathProgress.cs.
Referenced by Algorithms.PathFinder._FindPath(), RequestPath(), and RequestPathImmediate().
startPoint
Point PathProgress.startPoint = new Point()
Definition at line 18 of file PathProgress.cs.
Referenced by Algorithms.PathFinder._FindPath(), Algorithms.PathFinder.FindPath(), RequestPath(), and RequestPathImmediate().
state
State PathProgress.state
Definition at line 24 of file PathProgress.cs.
Referenced by AI_Goto.Run(), and AI_Goto.TryGoTo().
walker
IPathfindWalker PathProgress.walker
Definition at line 14 of file PathProgress.cs.
Property Documentation
HasPath
bool PathProgress.HasPath get
Definition at line 34 of file PathProgress.cs.
    {
        get
        {
            if (state == State.PathReady)
            {
                return nodes.Count >= 1;
            }
            return false;
        }
    }
Referenced by PathManager._GetFirstStep(), Spatial.Dist(), Zone_Dungeon.PlaceRail(), Chara.TryMoveTowards(), and GameUpdater.Update().
The documentation for this class was generated from the following file:
Elin/PathProgress.cs