Elin Decompiled Documentation: LayerHelp Class Reference
LayerHelp Class Reference
Public Member Functions
override void OnAfterInit ()
override void OnRightClick ()
Public Member Functions inherited from ELayer
override void OnBeforeAddLayer ()
void InitInspector ()
sealed override void Init ()
override void OnAfterAddLayer ()
void TryShowHelp ()
void AddLayerToUI (string id)
void TryShowHint (string _langHint=null)
void TalkHomeMemeber (string id)
void TalkMaid (string id)
override void OnRightClick ()
Static Public Member Functions
static void Toggle (string idFile, string idTopic=null)
Static Public Member Functions inherited from ELayer
static int rnd (int a)
Public Attributes
UIBook book
Static Public Attributes
static string lastIdFile
static string lastIdTopic
Properties
override bool blockWidgetClick [get]
Properties inherited from ELayer
static Core core [get]
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static FactionBranch Branch [get]
static Faction Home [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static CoreConfig config [get]
static GameSetting setting [get]
static ColorProfile Colors [get]
static SourceManager sources [get]
static World world [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
bool IsFloat [get]
virtual string IdHelp [get]
Private Member Functions
void OnDestroy ()
Additional Inherited Members
Protected Member Functions inherited from ELayer
sealed override void _Close ()
sealed override void Kill ()
Detailed Description
Definition at line 1 of file LayerHelp.cs.
Member Function Documentation
OnAfterInit()
override void LayerHelp.OnAfterInit () inline
Definition at line 11 of file LayerHelp.cs.
    {
        switch (book.mode)
        {
        case UIBook.Mode.Announce:
            book.Show("version" + (ELayer.core.version.demo ? "_demo" : ""));
            break;
        case UIBook.Mode.About:
            book.Show("about_EA");
            break;
        }
    }
References book, and ELayer.core.
OnDestroy()
void LayerHelp.OnDestroy () inline private
Definition at line 45 of file LayerHelp.cs.
    {
        if (book.mode == UIBook.Mode.Help)
        {
            lastIdFile = book.idFile;
            lastIdTopic = book.idTopic;
        }
    }
References book, lastIdFile, and lastIdTopic.
OnRightClick()
override void LayerHelp.OnRightClick () inline
Definition at line 33 of file LayerHelp.cs.
    {
        if ((bool)book.inputSearch && book.transSearchResult.gameObject.activeSelf)
        {
            book.showSearchResult = false;
        }
        else
        {
            base.OnRightClick();
        }
    }
References book.
Toggle()
static void LayerHelp.Toggle (string idFile, string idTopic = null) inline static
Definition at line 24 of file LayerHelp.cs.
    {
        LayerHelp layerHelp = ELayer.ui.ToggleLayer<LayerHelp>();
        if (layerHelp != null)
        {
            layerHelp.book.Show(idFile, idTopic);
        }
    }
References book, and ELayer.ui.
Referenced by StickyTutorial.OnClick(), StickyWelcome.OnClick(), HotItemLayer.OnClick(), LayerCredit.OnClickCredit(), ContentGallery.OnClickHelp(), LayerEditBio.OnClickHelp(), LayerFeedback.OnInit(), AM_BaseGameMode.OnUpdateInput(), HotItemContext.Show(), and LayerUploader.Upload().
Member Data Documentation
book
UIBook LayerHelp.book
Definition at line 7 of file LayerHelp.cs.
Referenced by OnAfterInit(), OnDestroy(), OnRightClick(), and Toggle().
lastIdFile
string LayerHelp.lastIdFile static
Definition at line 3 of file LayerHelp.cs.
Referenced by HotItemLayer.OnClick(), and OnDestroy().
lastIdTopic
string LayerHelp.lastIdTopic static
Definition at line 5 of file LayerHelp.cs.
Referenced by HotItemLayer.OnClick(), and OnDestroy().
Property Documentation
blockWidgetClick
override bool LayerHelp.blockWidgetClick get
Definition at line 9 of file LayerHelp.cs.
The documentation for this class was generated from the following file:
Elin/LayerHelp.cs