Elin Decompiled Documentation: UICurrency Class Reference
UICurrency Class Reference
Classes
class Item
class Options
Public Member Functions
void Build (UICurrency.Options _options)
void Build ()
void Add (Sprite icon, string lang, Func< string > func)
void Refresh ()
Public Attributes
List< UICurrency.Item > items = new List<UICurrency.Item>()
bool autoBuild
bool disable
UICurrency.Options options
Sprite[] icons
LayoutGroup layout
Card target
Private Member Functions
void Awake ()
void OnEnable ()
Private Attributes
UIButton mold
Additional Inherited Members
Static Public Member Functions inherited from EMono
static int rnd (int a)
Static Public Attributes inherited from EMono
static Core core
Properties inherited from EMono
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SoundManager Sound [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static CoreDebug debug [get]
Detailed Description
Definition at line 6 of file UICurrency.cs.
Member Function Documentation
Add()
void UICurrency.Add (Sprite icon, string lang, Func< string > func) inline
Definition at line 101 of file UICurrency.cs.
    {
        UIButton uibutton = Util.Instantiate<UIButton>(this.mold, this.layout);
        uibutton.icon.sprite = icon;
        uibutton.icon.SetNativeSize();
        uibutton.tooltip.lang = lang.lang().ToTitleCase(true);
        this.items.Add(new UICurrency.Item
        {
            func = func,
            text = uibutton.mainText
        });
        uibutton.mainText.SetText(func());
        uibutton.mainText.RebuildLayout(false);
        uibutton.RebuildLayout(false);
    }
References items, layout, mold, and text.
Referenced by Build().
Awake()
void UICurrency.Awake () inline private
Definition at line 8 of file UICurrency.cs.
    {
        if (this.autoBuild)
        {
            this.Build();
        }
        base.InvokeRepeating("Refresh", 0.1f, 0.1f);
    }
References autoBuild, and Build().
Build() [1/2]
void UICurrency.Build () inline
Definition at line 28 of file UICurrency.cs.
    {
        this.items.Clear();
        this.mold = this.layout.CreateMold(null);
        if (this.options.plat)
        {
            this.Add(this.icons[1], "plat", () => EMono.pc.GetCurrency("plat").ToString("#,0") ?? "");
        }
        if (this.options.money)
        {
            this.Add(this.icons[0], "money", () => EMono.pc.GetCurrency("money").ToString("#,0") ?? "");
        }
        if (this.options.money2)
        {
            this.Add(this.icons[5], "money2", () => EMono.pc.GetCurrency("money2").ToString("#,0") ?? "");
        }
        if (this.options.medal)
        {
            this.Add(this.icons[4], "medal", () => EMono.pc.GetCurrency("medal").ToString("#,0") ?? "");
        }
        if (this.options.ecopo)
        {
            this.Add(EMono.sources.cards.map["ecopo"].GetSprite(0, 0, false), "ecopo", () => EMono.pc.GetCurrency("ecopo").ToString("#,0") ?? "");
        }
        if (this.options.influence)
        {
            this.Add(this.icons[3], "influence", () => EMono._zone.influence.ToString() ?? "");
        }
        if (this.options.casino)
        {
            this.Add(this.icons[10], "casino_coin", () => EMono.pc.GetCurrency("casino_coin").ToString("#,0") ?? "");
        }
        if (this.options.weight)
        {
            this.Add(this.icons[11], "weightInv", () => Lang._weight(this.target.ChildrenWeight, false, 0) + " / " + Lang._weight(this.target.WeightLimit, true, 0));
        }
        if (EMono.BranchOrHomeBranch != null)
        {
            HomeResourceManager resources = EMono.BranchOrHomeBranch.resources;
            if (this.options.branchMoney)
            {
                this.Add(this.icons[5], resources.money.Name, () => resources.money.value.ToString("#,0") ?? "");
            }
            if (this.options.branchFood)
            {
                this.Add(this.icons[6], resources.food.Name, () => resources.food.value.ToString("#,0") ?? "");
            }
            if (this.options.branchKnowledge)
            {
                this.Add(this.icons[7], resources.knowledge.Name, () => resources.knowledge.value.ToString("#,0") ?? "");
            }
            if (this.options.admin)
            {
                this.Add(this.icons[9], "ap", () => EMono.Branch.policies.CurrentAP().ToString() + "/" + EMono.Branch.MaxAP.ToString());
            }
            if (this.options.resources)
            {
                using (List<BaseHomeResource>.Enumerator enumerator = EMono.BranchOrHomeBranch.resources.list.GetEnumerator())
                {
                    while (enumerator.MoveNext())
                    {
                        BaseHomeResource r = enumerator.Current;
                        if (r.IsAvailable)
{
                            this.Add(r.Sprite, r.Name, () => r.value.ToString("#,0") ?? "");
                        }
                    }
                }
            }
        }
        this.layout.RebuildLayout(false);
    }
References EMono._zone, Add(), EMono.Branch, EMono.BranchOrHomeBranch, SourceManager.cards, PolicyManager.CurrentAP(), HomeResourceManager.food, Card.GetCurrency(), icons, Spatial.influence, BaseHomeResource.IsAvailable, items, HomeResourceManager.knowledge, layout, HomeResourceManager.list, SourceCard.map, FactionBranch.MaxAP, HomeResourceManager.money, BaseHomeResource.Name, options, EMono.pc, FactionBranch.policies, FactionBranch.resources, EMono.sources, BaseHomeResource.Sprite, and BaseHomeResource.value.
Referenced by Awake(), and Build().
Build() [2/2]
void UICurrency.Build (UICurrency::Options _options) inline
Definition at line 22 of file UICurrency.cs.
    {
        this.options = _options;
        this.Build();
    }
References Build().
Referenced by InvOwner.BuildUICurrency(), and InvOwnerRecycle.BuildUICurrency().
OnEnable()
void UICurrency.OnEnable () inline private
Definition at line 17 of file UICurrency.cs.
    {
        this.Refresh();
    }
References Refresh().
Refresh()
void UICurrency.Refresh () inline
Definition at line 117 of file UICurrency.cs.
    {
        foreach (UICurrency.Item item in this.items)
        {
            string text = item.func();
            if (item.text.text != (text ?? ""))
            {
                item.text.SetText(text);
                item.text.RebuildLayout(false);
                item.text.transform.parent.RebuildLayout(false);
            }
        }
    }
References text.
Referenced by OnEnable().
Member Data Documentation
autoBuild
bool UICurrency.autoBuild
Definition at line 133 of file UICurrency.cs.
Referenced by Awake().
disable
bool UICurrency.disable
Definition at line 135 of file UICurrency.cs.
icons
Sprite [] UICurrency.icons
Definition at line 139 of file UICurrency.cs.
Referenced by Build().
items
List<UICurrency.Item> UICurrency.items = new List<UICurrency.Item>()
Definition at line 131 of file UICurrency.cs.
Referenced by Add(), and Build().
layout
LayoutGroup UICurrency.layout
Definition at line 141 of file UICurrency.cs.
Referenced by Add(), and Build().
mold
UIButton UICurrency.mold private
Definition at line 145 of file UICurrency.cs.
Referenced by Add().
options
UICurrency.Options UICurrency.options
Definition at line 137 of file UICurrency.cs.
Referenced by Build().
target
Card UICurrency.target
Definition at line 143 of file UICurrency.cs.
The documentation for this class was generated from the following file:
Elin/UICurrency.cs