Elin Decompiled Documentation: TaskMine Class Reference
TaskMine Class Reference
Public Types
enum Mode { Default , Ramp }
Public Types inherited from BaseTaskHarvest
enum HarvestType {
Floor , Block , Obj , Thing ,
Disassemble
}
Public Types inherited from AIAct
enum Status { Running , Fail , Success }
Public Types inherited from Act
enum CostType {
None , MP , SP , None ,
MP , SP
}
enum CostType {
None , MP , SP , None ,
MP , SP
}
Public Types inherited from IInspect
enum NoteMode { Default , Recipe , Product , Info }
Public Member Functions
override string GetTextSmall (Card c)
override void OnCreateProgress (Progress_Custom p)
override void DrawMarker (int x, int z, RenderParam p)
override HitResult GetHitResult ()
override void OnProgressComplete ()
Public Member Functions inherited from BaseTaskHarvest
virtual string GetBaseText (string str)
override string GetTextSmall (Card c)
override string GetText (string str="")
void SetTarget (Chara c, Thing _tool=null)
int GetToolEfficiency (Thing t, SourceMaterial.Row mat)
override bool CanProgress ()
int[] GetToolEfficiency (SourceMaterial.Row mat)
string GetTextDifficulty ()
Public Member Functions inherited from TaskDesignation
virtual string GetTextOrbit ()
bool PointHasOtherDesignation ()
virtual void DrawMarker (int x, int z, RenderParam p)
virtual void Draw (int x, int z, RenderParam p)
virtual void OnEnterScreen ()
virtual void OnLeaveScreen ()
virtual void TrySpawnOrbit ()
void DespawnOrbit ()
Public Member Functions inherited from TaskPoint
override bool CanManualCancel ()
override bool CanPerform ()
override bool _CanPerformTask (Chara chara, int radius)
override IEnumerable< Status > Run ()
void OnInspect ()
void WriteNote (UINote n, Action< UINote > onWriteNote=null, IInspect.NoteMode mode=IInspect.NoteMode.Default, Recipe recipe=null)
Public Member Functions inherited from Task
virtual HitResult GetHitResult ()
override void OnSuccess ()
void TryLayer (int min=30)
Status Destroy ()
virtual void OnDestroy ()
override Status Cancel ()
override void OnReset ()
override bool CanProgress ()
bool CanPerformTask (Chara chara, int radius)
virtual bool _CanPerformTask (Chara chara, int radius)
virtual void OnAdd ()
void ToggleSuspend ()
Public Member Functions inherited from AIAct
override string ToString ()
override MultiSprite GetStateIcon ()
virtual Point GetDestination ()
AIProgress GetProgress ()
string GetCurrentActionText ()
override bool IsToolValid ()
virtual void OnStart ()
void SetOwner (Chara c)
virtual void OnSetOwner ()
void SetChild (AIAct seq, Func< Status > _onChildFail=null)
void Start ()
override bool Perform ()
Status Restart ()
Status Success (Action action=null)
virtual void OnSuccess ()
bool TryCancel (Card c)
virtual Status Cancel ()
virtual void OnCancel ()
virtual void OnCancelOrSuccess ()
virtual bool CanManualCancel ()
Status KeepRunning ()
void Reset ()
virtual void OnReset ()
Status Tick ()
virtual IEnumerable< Status > Run ()
Status TickChild ()
Status Do (AIAct _seq, Func< Status > _onChildFail=null)
Status DoGotoInteraction (Point pos, Func< Status > _onChildFail=null)
Status DoGoto (Point pos, int dist=0, bool ignoreConnection=false, Func< Status > _onChildFail=null)
Status DoGoto (Card card, Func< Status > _onChildFail=null)
Status DoGoto (Card card, int dist, Func< Status > _onChildFail=null)
Status DoGotoSpot (Card card, Func< Status > _onChildFail=null)
Status DoGoto< T > (Func< Status > _onChildFail=null)
Status DoGotoSpot< T > (Func< Status > _onChildFail=null, bool ignoreAccessType=false)
Status DoGrab (Card card, int num=-1, bool pickHeld=false, Func< Status > _onChildFail=null)
Status DoGrab< T > ()
Status DoProgress ()
Status DoIdle (int repeat=3)
Status DoWait (int count=1)
virtual AIProgress CreateProgress ()
virtual void OnCreateProgress (Progress_Custom p)
virtual bool CanProgress ()
virtual void OnBeforeProgress ()
virtual void OnProgress ()
virtual void OnProgressComplete ()
void SimulateZone (int days)
virtual void OnSimulateZone (int days)
virtual void OnSimulatePosition ()
Public Member Functions inherited from Act
virtual CursorInfo GetCursorIcon (Card c)
virtual MultiSprite GetStateIcon ()
override Sprite GetSprite ()
virtual bool ShowMouseHint (Card c)
virtual bool IsValidTC (Card c)
virtual string GetHintText (string str="")
virtual string GetText (string str="")
virtual string GetTextSmall (Card c)
virtual Color GetActPlanColor ()
virtual bool Perform ()
virtual bool CanPerform ()
bool Perform (Chara _cc, Card _tc=null, Point _tp=null)
bool CanPerform (Chara _cc, Card _tc=null, Point _tp=null)
virtual bool IsToolValid ()
new void SetImage (Image image)
virtual void OnMarkMapHighlights ()
virtual bool ShouldMapHighlight (Point p)
virtual CursorInfo GetCursorIcon (Card c)
virtual MultiSprite GetStateIcon ()
override Sprite GetSprite ()
virtual bool ShowMouseHint (Card c)
virtual bool IsValidTC (Card c)
virtual string GetHintText (string str="")
virtual string GetText (string str="")
virtual string GetTextSmall (Card c)
virtual Color GetActPlanColor ()
virtual bool Perform ()
virtual bool CanPerform ()
bool Perform (Chara _cc, Card _tc=null, Point _tp=null)
bool CanPerform (Chara _cc, Card _tc=null, Point _tp=null)
virtual bool IsToolValid ()
new void SetImage (Image image)
virtual void OnMarkMapHighlights ()
virtual bool ShouldMapHighlight (Point p)
Public Member Functions inherited from Element
virtual SourceElement.Row GetSource ()
virtual int GetSourcePotential (int v)
virtual Sprite GetSprite ()
int GetMaterialSourceValue (Thing t, int v)
virtual int GetSourceValue (int v, int lv, SourceValueType type)
virtual Sprite GetIcon (string suffix="")
int SortVal (bool charaSheet=false)
virtual bool CanLink (ElementContainer owner)
bool HasTag (string tag)
void SetImage (Image i)
virtual string GetDetail ()
bool IsFactionElement (Chara c)
Element GetParent (Card c)
void WriteNote (UINote n, ElementContainer owner=null, Action< UINote > onWriteNote=null)
void WriteNoteWithRef (UINote n, ElementContainer owner, Action< UINote > onWriteNote, Element refEle)
void _WriteNote (UINote n, Chara c, Act act)
void _WriteNote (UINote n, ElementContainer owner, Action< UINote > onWriteNote, bool isRef, bool addHeader=true)
virtual void OnWriteNote (UINote n, ElementContainer owner)
virtual void OnChangeValue ()
void CheckLevelBonus (ElementContainer owner, UINote n=null)
int GetSortVal (UIList.SortMode m)
virtual Act.Cost GetCost (Chara c)
virtual int GetPower (Card c)
virtual void SetTextValue (UIText text)
virtual SourceElement.Row GetSource ()
virtual int GetSourcePotential (int v)
virtual Sprite GetSprite ()
int GetMaterialSourceValue (Thing t, int v)
virtual int GetSourceValue (int v, int lv, SourceValueType type)
virtual Sprite GetIcon (string suffix="")
int SortVal (bool charaSheet=false)
virtual bool CanLink (ElementContainer owner)
bool HasTag (string tag)
void SetImage (Image i)
virtual string GetDetail ()
bool IsFactionElement (Chara c)
Element GetParent (Card c)
void WriteNote (UINote n, ElementContainer owner=null, Action< UINote > onWriteNote=null)
void WriteNoteWithRef (UINote n, ElementContainer owner, Action< UINote > onWriteNote, Element refEle)
void _WriteNote (UINote n, Chara c, Act act)
void _WriteNote (UINote n, ElementContainer owner, Action< UINote > onWriteNote, bool isRef, bool addHeader=true)
virtual void OnWriteNote (UINote n, ElementContainer owner)
virtual void OnChangeValue ()
void CheckLevelBonus (ElementContainer owner, UINote n=null)
int GetSortVal (UIList.SortMode m)
virtual Act.Cost GetCost (Chara c)
virtual int GetPower (Card c)
virtual void SetTextValue (UIText text)
void WriteNote (UINote n, Action< UINote > onWriteNote=null, NoteMode mode=NoteMode.Default, Recipe recipe=null)
void OnInspect ()
void OnEnterScreen ()
void OnLeaveScreen ()
Static Public Member Functions
static bool CanMine (Point pos, Card t)
Static Public Member Functions inherited from BaseTaskHarvest
static Thing GetBestTool (Chara c, Point p)
static int GetReqEle (string _raw)
Static Public Member Functions inherited from Act
static void SetReference (Chara _cc, Card _tc=null, Point _tp=null)
static void SetTool (Thing t)
static void SetReference (Chara _cc, Card _tc=null, Point _tp=null)
static void SetTool (Thing t)
Static Public Member Functions inherited from Element
static string GetName (string alias)
static SourceElement.Row Get (int id)
static Dictionary< int, int > GetElementMap (int[] list)
static Dictionary< int, int > GetElementMap (int[] list, Dictionary< int, int > map)
static SourceElement.Row GetRandomElement (int lv=1)
static Element Create (int id, int v=0)
static Element Create (string id, int v=1)
static int GetId (string alias)
static int GetResistLv (int v)
static int GetResistDamage (int dmg, int v)
static string GetName (string alias)
static SourceElement.Row Get (int id)
static Dictionary< int, int > GetElementMap (int[] list)
static Dictionary< int, int > GetElementMap (int[] list, Dictionary< int, int > map)
static SourceElement.Row GetRandomElement (int lv=1)
static Element Create (int id, int v=0)
static Element Create (string id, int v=1)
static int GetId (string alias)
static int GetResistLv (int v)
static int GetResistDamage (int dmg, int v)
Static Public Member Functions inherited from EClass
static int rnd (int a)
static int curve (int a, int start, int step, int rate=75)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Public Attributes
Mode mode
int ramp = 3
bool mined
Public Attributes inherited from BaseTaskHarvest
Thing target
Element reqElement
int matHardness
int idEle
int reqLv
int toolLv
int maxProgress
int efficiency
int difficulty
int effectFrame = 1
bool isToolRequired
Thing tool
Public Attributes inherited from TaskDesignation
long sync
bool isSynced
TCOrbitTask orbit
Public Attributes inherited from TaskPoint
Point pos = new Point()
bool isRepeated
Public Attributes inherited from Task
TaskList taskList
bool isDestroyed
int nextTry
bool suspended
Public Attributes inherited from AIAct
new Chara owner
Status status
IEnumerator< Status > Enumerator
AIAct child
AIAct parent
byte restartCount
Func< Status > onChildFail
Func< bool > isFail
Public Attributes inherited from Element
SourceElement.Row _source
int id
int vBase
int vExp
int vPotential
int vTempPotential
int vLink
int vSource
int vSourcePotential
ElementContainer owner
Properties
override HarvestType harvestType [get]
override int destDist [get]
override bool isBlock [get]
override int RightHand [get]
override bool destIgnoreConnection [get]
override bool ShowMapHighlightBlock [get]
override CursorInfo CursorIcon [get]
override bool IsHostileAct [get]
Properties inherited from BaseTaskHarvest
bool IsTooHard [get]
bool IsHarvest [get]
virtual bool CanReapSeed [get]
virtual HarvestType harvestType [get]
virtual bool IsGrowth [get]
override bool CanPressRepeat [get]
override int LeftHand [get]
override CursorInfo CursorIcon [get]
Properties inherited from TaskDesignation
override bool HasProgress [get]
virtual int idMarker [get]
virtual int W [get]
virtual int H [get]
virtual bool ShowOrbit [get]
virtual bool Working [get]
override bool ShowAuto [get]
override CursorInfo CursorIcon [get]
TaskManager.Designations Designations [get]
long Sync [get]
Properties inherited from TaskPoint
override bool HasProgress [get]
virtual int destDist [get]
virtual bool destIgnoreConnection [get]
virtual bool isBlock [get]
virtual bool Loop [get]
bool CanInspect [get]
string InspectName [get]
Point InspectPoint [get]
Vector3 InspectPosition [get]
Properties inherited from Task
override TargetType TargetType [get]
Properties inherited from AIAct
virtual bool IsRunning [get]
bool IsChildRunning [get]
bool IsMoveAI [get]
virtual int MaxRestart [get]
virtual new string Name [get]
virtual MultiSprite stateIcon [get]
virtual Sprite actionIcon [get]
virtual bool IsNoGoal [get]
virtual bool IsAutoTurn [get]
virtual bool IsIdle [get]
virtual bool PushChara [get]
virtual int MaxProgress [get]
virtual bool ShowProgress [get]
virtual bool UseTurbo [get]
virtual int CurrentProgress [get]
virtual bool ShowCursor [get]
virtual bool CancelWhenDamaged [get]
virtual bool CancelWhenMoved [get]
virtual bool InformCancel [get]
virtual Thing RenderThing [get]
AIAct Current [get]
override bool IsAct [get]
override bool ShowPotential [get]
override bool UsePotential [get]
override bool ShowRelativeAttribute [get]
virtual bool HasProgress [get]
Properties inherited from Act
override bool ShowPotential [get]
override bool UsePotential [get]
override bool ShowRelativeAttribute [get]
virtual CursorInfo CursorIcon [get]
virtual string ID [get]
virtual bool IsAct [get]
virtual bool WillEndTurn [get]
virtual bool CloseLayers [get]
virtual int LeftHand [get]
virtual int RightHand [get]
virtual int ElementPowerMod [get]
virtual bool ShowMapHighlight [get]
virtual bool ShowMapHighlightBlock [get]
virtual bool PickHeldOnStart [get]
virtual bool DropHeldOnStart [get]
virtual bool CanPressRepeat [get]
virtual bool CanAutofire [get]
virtual bool ResetAxis [get]
virtual bool RequireTool [get]
virtual bool IsHostileAct [get]
virtual bool HideRightInfo [get]
virtual bool HaveLongPressAction [get]
virtual float Radius [get]
virtual int PerformDistance [get]
virtual int MaxRadius [get]
virtual TargetType TargetType [get]
virtual bool LocalAct [get]
virtual bool CanRapidFire [get]
virtual float RapidDelay [get]
virtual bool ShowAuto [get]
virtual bool IsCrime [get]
Properties inherited from Element
SourceElement.Row source [get]
virtual int DisplayValue [get]
virtual int MinValue [get]
int Value [get]
int ValueWithoutLink [get]
virtual int MinPotential [get]
int Potential [get]
virtual bool CanGainExp [get]
bool IsFlag [get]
virtual string Name [get]
virtual string FullName [get]
virtual int ExpToNext [get]
virtual bool UseExpMod [get]
virtual int CostTrain [get]
virtual int CostLearn [get]
virtual bool ShowXP [get]
virtual bool ShowMsgOnValueChanged [get]
virtual bool ShowValue [get]
virtual bool ShowPotential [get]
virtual bool UsePotential [get]
virtual bool PotentialAsStock [get]
virtual bool ShowRelativeAttribute [get]
virtual bool ShowBonuses [get]
virtual string ShortName [get]
bool IsGlobalElement [get]
bool IsFactionWideElement [get]
bool IsPartyWideElement [get]
virtual bool ShowEncNumber [get]
bool IsTrait [get]
bool IsFoodTrait [get]
bool IsFoodTraitMain [get]
bool IsMainAttribute [get]
Act act [get]
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Properties inherited from IInspect
bool CanInspect [get]
string InspectName [get]
Point InspectPoint [get]
Vector3 InspectPosition [get]
Properties inherited from ISyncScreen
long Sync [get]
Additional Inherited Members
Static Public Attributes inherited from Act
static Chara CC
static Card TC
static Point TP = new Point()
static Thing TOOL
static int powerMod = 100
static bool forcePt
Static Public Attributes inherited from Element
const int Div = 5
static Element Void = new Element()
static int[] List_MainAttributes
static int[] List_MainAttributesMajor
static int[] List_Body
static int[] List_Mind
static List< SourceElement.Row > ListElements = new List<SourceElement.Row>()
static List< SourceElement.Row > ListAttackElements = new List<SourceElement.Row>()
Static Public Attributes inherited from EClass
static Core core
Static Package Functions inherited from Element
static string< _WriteNote > g__Calc (ref Element.<>c__DisplayClass103_0 A_0)
Detailed Description
Definition at line 1 of file TaskMine.cs.
Member Enumeration Documentation
Mode
enum TaskMine.Mode
Enumerator
Default
Ramp
Definition at line 3 of file TaskMine.cs.
    {
        Default,
        Ramp
    }
Member Function Documentation
CanMine()
static bool TaskMine.CanMine (Point pos, Card t) inline static
Definition at line 31 of file TaskMine.cs.
    {
        if (t != null && pos.HasBlock && (!pos.HasObj || !pos.sourceObj.tileType.IsBlockMount))
        {
            if (t.HasElement(220))
            {
                return true;
            }
            if ((pos.matBlock.category == "wood" || pos.matBlock.category == "grass") && t.HasElement(225))
            {
                return true;
            }
        }
        return false;
    }
References Point.HasBlock, Card.HasElement(), Point.HasObj, Point.matBlock, TaskPoint.pos, and Point.sourceObj.
Referenced by AM_Adv.HighlightWall(), OnCreateProgress(), and HotItemHeld.TrySetToolAct().
DrawMarker()
override void TaskMine.DrawMarker (int x, int z, RenderParam p) inline virtual
Reimplemented from TaskDesignation.
Definition at line 93 of file TaskMine.cs.
    {
        if (ActionMode.Mine.IsRoofEditMode() && pos.HasWallOrFence)
        {
            EClass.screen.guide.DrawWall(pos, Working ? EClass.Colors.blockColors.ActiveOpacity : EClass.Colors.blockColors.InactiveOpacity);
        }
        else
        {
            base.DrawMarker(x, z, p);
        }
    }
References ColorProfile.BlockColors.ActiveOpacity, ColorProfile.blockColors, EClass.Colors, ScreenGuide.DrawWall(), BaseGameScreen.guide, Point.HasWallOrFence, ColorProfile.BlockColors.InactiveOpacity, AM_Mine.IsRoofEditMode(), ActionMode.Mine, TaskPoint.pos, EClass.screen, and TaskDesignation.Working.
GetHitResult()
override HitResult TaskMine.GetHitResult () inline virtual
Reimplemented from Task.
Definition at line 105 of file TaskMine.cs.
    {
        if (ActionMode.Mine.IsRoofEditMode())
        {
            if (pos.cell._roofBlock == 0)
            {
                return HitResult.Default;
            }
            return HitResult.Valid;
        }
        if (pos.cell.HasBlock || !pos.cell.isSeen)
        {
            if (pos.sourceBlock.tileType.Invisible && !ActionMode.Mine.IsActive)
            {
                return HitResult.Default;
            }
            if (mode == Mode.Ramp && (pos.cell.HasRamp || EClass._map.GetRampDir(pos.x, pos.z, EClass.sources.blocks.rows[ramp].tileType) == -1))
            {
                return HitResult.Default;
            }
            return HitResult.Valid;
        }
        if (!mined && !pos.HasObj && owner != null && !owner.IsAgent && pos.Equals(owner.pos) && pos.Installed == null && EClass._zone.CanDigUnderground)
        {
            return HitResult.Valid;
        }
        return HitResult.Default;
    }
References EClass._map, Cell._roofBlock, EClass._zone, SourceManager.blocks, Zone.CanDigUnderground, Point.cell, Point.Equals(), Map.GetRampDir(), Cell.HasBlock, Point.HasObj, Cell.HasRamp, Point.Installed, Card.IsAgent, AM_Mine.IsRoofEditMode(), Cell.isSeen, ActionMode.Mine, mined, mode, AIAct.owner, Card.pos, TaskPoint.pos, ramp, Point.sourceBlock, EClass.sources, Point.x, and Point.z.
GetTextSmall()
override string TaskMine.GetTextSmall (Card c) inline virtual
Reimplemented from BaseTaskHarvest.
Definition at line 47 of file TaskMine.cs.
    {
        if (!pos.cell.HasBlock)
        {
            return pos.cell.GetFloorName();
        }
        return pos.cell.GetBlockName();
    }
References Point.cell, Cell.GetBlockName(), Cell.GetFloorName(), Cell.HasBlock, and TaskPoint.pos.
OnCreateProgress()
override void TaskMine.OnCreateProgress (Progress_Custom p) inline virtual
Reimplemented from AIAct.
Definition at line 56 of file TaskMine.cs.
    {
        SetTarget(owner);
        p.textHint = pos.cell.GetBlockName();
        p.maxProgress = maxProgress;
        p.onProgressBegin = delegate
        {
            if (!CanMine(pos, owner.Tool))
            {
                p.Cancel();
            }
            else if (base.IsTooHard)
            {
                owner.Say("tooHardToMine", owner, pos.cell.GetBlockName());
                p.Cancel();
            }
            else if (owner.Tool != null)
            {
                owner.Say("mine_start", owner, owner.Tool);
            }
        };
        p.onProgress = delegate
        {
            owner.LookAt(pos);
            owner.PlaySound(pos.matBlock.GetSoundImpact());
            pos.Animate(AnimeID.HitObj, animeBlock: true);
            pos.matBlock.PlayHitEffect(pos);
            pos.matBlock.AddBlood(pos);
            owner.renderer.NextFrame();
            owner.elements.ModExp(220, 5);
            if (EClass._zone.IsCrime(owner, this))
            {
                owner.pos.TryWitnessCrime(owner);
            }
        };
    }
References EClass._zone, Point.Animate(), AIAct.Cancel(), CanMine(), Point.cell, Card.elements, Cell.GetBlockName(), Zone.IsCrime(), Chara.LookAt(), Point.matBlock, BaseTaskHarvest.maxProgress, ElementContainer.ModExp(), CardRenderer.NextFrame(), AIAct.owner, Card.PlaySound(), Card.pos, TaskPoint.pos, Card.renderer, Card.Say(), BaseTaskHarvest.SetTarget(), Card.Tool, and Point.TryWitnessCrime().
OnProgressComplete()
override void TaskMine.OnProgressComplete () inline virtual
Reimplemented from AIAct.
Definition at line 134 of file TaskMine.cs.
    {
        string recipeID = pos.sourceBlock.RecipeID;
        int hardness = pos.matBlock.hardness;
        switch (mode)
        {
        case Mode.Default:
            if (pos.HasBlock || ActionMode.Mine.IsRoofEditMode())
            {
                if (owner.IsPC)
                {
                    EClass.player.stats.digs++;
                }
                EClass._map.MineBlock(pos, recoverBlock: false, owner);
            }
            else if (pos.Installed == null)
            {
                EClass._zone.AddThing("stairsDown_cave", pos.x, pos.z).Install();
                return;
            }
            break;
        case Mode.Ramp:
            EClass._map.MineRamp(pos, (ramp == 3) ? pos.matBlock.ramp : ramp);
            break;
        }
        if (!owner.IsAgent)
        {
            owner.elements.ModExp(220, 20 + hardness);
            if (EClass.rnd(10) == 0)
            {
                EClass._map.TrySmoothPick(pos, ThingGen.Create("pebble"), owner);
            }
            if (EClass.rnd(10) == 0)
            {
                EClass._map.TrySmoothPick(pos, ThingGen.Create("stone"), owner);
            }
            if (EClass._zone.IsCrime(owner, this))
            {
                EClass.player.ModKarma(-1);
            }
            if (EClass.rnd(2) == 0)
            {
                owner.stamina.Mod(-1);
            }
        }
        if (owner != null && owner.IsPC)
        {
            EClass.player.recipes.ComeUpWithRecipe(recipeID, 30);
        }
        mined = true;
    }
References EClass._map, EClass._zone, Zone.AddThing(), RecipeManager.ComeUpWithRecipe(), ThingGen.Create(), Player.Stats.digs, Card.elements, Point.HasBlock, Card.Install(), Point.Installed, Card.IsAgent, Zone.IsCrime(), Chara.IsPC, AM_Mine.IsRoofEditMode(), Point.matBlock, ActionMode.Mine, Map.MineBlock(), mined, Map.MineRamp(), Stats.Mod(), mode, ElementContainer.ModExp(), Player.ModKarma(), AIAct.owner, EClass.player, TaskPoint.pos, ramp, Player.recipes, EClass.rnd(), Point.sourceBlock, Chara.stamina, Player.stats, Map.TrySmoothPick(), Point.x, and Point.z.
Member Data Documentation
mined
bool TaskMine.mined
Definition at line 13 of file TaskMine.cs.
Referenced by GetHitResult(), and OnProgressComplete().
mode
Mode TaskMine.mode
Definition at line 9 of file TaskMine.cs.
Referenced by GetHitResult(), and OnProgressComplete().
ramp
int TaskMine.ramp = 3
Definition at line 11 of file TaskMine.cs.
Referenced by GetHitResult(), and OnProgressComplete().
Property Documentation
CursorIcon
override CursorInfo TaskMine.CursorIcon get
Definition at line 27 of file TaskMine.cs.
destDist
override int TaskMine.destDist get
Definition at line 17 of file TaskMine.cs.
destIgnoreConnection
override bool TaskMine.destIgnoreConnection get
Definition at line 23 of file TaskMine.cs.
harvestType
override HarvestType TaskMine.harvestType get
Definition at line 15 of file TaskMine.cs.
isBlock
override bool TaskMine.isBlock get
Definition at line 19 of file TaskMine.cs.
IsHostileAct
override bool TaskMine.IsHostileAct get
Definition at line 29 of file TaskMine.cs.
RightHand
override int TaskMine.RightHand get
Definition at line 21 of file TaskMine.cs.
ShowMapHighlightBlock
override bool TaskMine.ShowMapHighlightBlock get
Definition at line 25 of file TaskMine.cs.
The documentation for this class was generated from the following file:
Elin/TaskMine.cs