Elin Decompiled Documentation: UIDragGridIngredients Class Reference
UIDragGridIngredients Class Reference
Public Member Functions
void Update ()
void Refresh ()
Public Attributes
LayerDragGrid layer
UIList list
UIScrollView view
GameObject goList
Additional Inherited Members
Static Public Member Functions inherited from EMono
static int rnd (int a)
Static Public Attributes inherited from EMono
static Core core
Properties inherited from EMono
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SoundManager Sound [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static CoreDebug debug [get]
Detailed Description
Definition at line 5 of file UIDragGridIngredients.cs.
Member Function Documentation
Refresh()
void UIDragGridIngredients.Refresh () inline
Definition at line 34 of file UIDragGridIngredients.cs.
    {
        Debug.Log("Refreshing uiDragGridIngredients");
        List<Thing> list = new List<Thing>();
        bool allowStockIngredients = this.layer.owner.AllowStockIngredients;
        if ((EMono._zone.IsPCFaction || EMono._zone is Zone_Tent) && allowStockIngredients)
        {
            foreach (Thing thing in EMono._map.Stocked.Things)
            {
                if (this.layer.owner.ShouldShowGuide(thing) && EMono._map.Stocked.ShouldListAsResource(thing))
                {
                    Window.SaveData windowSaveData = thing.parentCard.GetWindowSaveData();
                    if (windowSaveData == null || !windowSaveData.excludeCraft)
                    {
                        list.Add(thing);
                        thing.SetSortVal(UIList.SortMode.ByCategory, CurrencyType.Money);
                    }
                }
            }
            list.Sort((Thing a, Thing b) => b.sortVal - a.sortVal);
        }
        this.list.callbacks = new UIList.Callback<Thing, ButtonGrid>
        {
            onClick = delegate(Thing a, ButtonGrid b)
            {
                int currentIndex = this.layer.currentIndex;
                this.layer.buttons[currentIndex].SetCardGrid(a, this.layer.owner);
                this.layer.owner.OnProcess(a);
            },
            onInstantiate = delegate(Thing a, ButtonGrid b)
            {
                b.SetCard(a, ButtonGrid.Mode.Grid, null);
                b.SetOnClick(delegate
                {
                });
                b.onRightClick = delegate()
                {
                    this.list.callbacks.OnClick(a, b);
                };
            }
        };
        this.list.Clear();
        foreach (Thing o in list)
        {
            this.list.Add(o);
        }
        this.list.Refresh(false);
    }
References EMono._map, EMono._zone, InvOwnerDraglet.AllowStockIngredients, LayerDragGrid.buttons, LayerDragGrid.currentIndex, Card.GetWindowSaveData(), Zone.IsPCFaction, layer, list, InvOwnerDraglet.OnProcess(), LayerDragGrid.owner, Card.parentCard, ButtonGrid.SetCard(), Card.SetSortVal(), Props.ShouldListAsResource(), InvOwner.ShouldShowGuide(), Card.sortVal, Map.Stocked, and Props.Things.
Referenced by LayerDragGrid.ClearButtons(), InvOwnerDraglet.OnClick(), InvOwnerDraglet.OnProcess(), LayerDragGrid.SetInv(), and Update().
Update()
void UIDragGridIngredients.Update () inline
Definition at line 7 of file UIDragGridIngredients.cs.
    {
        bool activeSelf = this.goList.activeSelf;
        bool isNoGoal = EMono.pc.ai.IsNoGoal;
        this.goList.SetActive(isNoGoal);
        if (activeSelf != isNoGoal)
        {
            this.Refresh();
        }
        if (EInput.middleMouse.down)
        {
            ButtonGrid componentOf = InputModuleEX.GetComponentOf<ButtonGrid>();
            if (componentOf && componentOf.GetComponentInParent<UIDragGridIngredients>())
            {
                Thing t = componentOf.card.Thing;
                t.ShowSplitMenu2(componentOf, "actPutIn", delegate(int n)
                {
                    Thing thing = t.Split(n);
                    thing = EMono.pc.Pick(thing, true, false);
                    int currentIndex = this.layer.currentIndex;
                    this.layer.buttons[currentIndex].SetCardGrid(thing, this.layer.owner);
                    this.layer.owner.OnProcess(thing);
                });
            }
        }
    }
References Chara.ai, LayerDragGrid.buttons, ButtonGrid.card, LayerDragGrid.currentIndex, goList, AIAct.IsNoGoal, layer, InvOwnerDraglet.OnProcess(), LayerDragGrid.owner, EMono.pc, Chara.Pick(), Refresh(), Thing.ShowSplitMenu2(), Card.Split(), and Card.Thing.
Member Data Documentation
goList
GameObject UIDragGridIngredients.goList
Definition at line 89 of file UIDragGridIngredients.cs.
Referenced by Update().
layer
LayerDragGrid UIDragGridIngredients.layer
Definition at line 83 of file UIDragGridIngredients.cs.
Referenced by Refresh(), and Update().
list
UIList UIDragGridIngredients.list
Definition at line 85 of file UIDragGridIngredients.cs.
Referenced by Refresh().
view
UIScrollView UIDragGridIngredients.view
Definition at line 87 of file UIDragGridIngredients.cs.
The documentation for this class was generated from the following file:
Elin/UIDragGridIngredients.cs