Elin Decompiled Documentation: ButtonChara Class Reference
ButtonChara Class Reference
Public Types
enum Mode {
Default , Hire , Journal , Embark ,
Ranking
}
Public Member Functions
void SetChara (Chara c, Mode m)
Public Member Functions inherited from UIButton
virtual bool CanMiddleClick ()
virtual void OnMiddleClick (bool forceClick)
void SetItem (Item i)
virtual void RefreshItem ()
virtual void OnHover ()
void Toggle ()
void ToggleCheck ()
void SetCheck (bool check)
void SetToggle (bool isOn, Action< bool > onToggle=null)
void SetToggleWithScore (bool isOn, Action< bool > onToggle, int? score)
void SetTooltip (Action< UITooltip > onShowTooltip=null, bool enable=true)
void SetTooltip (string id, Action< UITooltip > onShowTooltip=null, bool enable=true)
void SetTooltipLang (string lang=null)
virtual void ShowTooltip ()
void ShowTooltipForced (bool ignoreWhenRightClick=true)
override void OnPointerDown (PointerEventData eventData)
override void OnPointerClick (PointerEventData eventData)
override void OnPointerUp (PointerEventData eventData)
void OnPointerUpOnDrag (PointerEventData eventData)
void _OnPress ()
void OnPress ()
void AddHighlight (Func< bool > killCondition)
void DoHighlightTransition (bool instant=false)
void DoNormalTransition (bool instant=true)
override Selectable FindSelectableOnDown ()
override Selectable FindSelectableOnUp ()
override Selectable FindSelectableOnLeft ()
override Selectable FindSelectableOnRight ()
void SetNavigation (UIButton up, UIButton down=null, UIButton left=null, UIButton right=null)
override bool IsActive ()
void SetInteractableWithAlpha (bool enable)
virtual void ApplySkin ()
void ApplySkin ()
Public Attributes
Portrait portrait
UIText textName
UIText textAlias
UIText textBio
UIText textWork
UIText textHobby
UIText textLifeStyle
new UIItem item
Transform transDefeated
LayoutGroup layoutTag
Public Attributes inherited from UIButton
UIText mainText
UIText subText
UIText subText2
UIText keyText
Image icon
Image imageCheck
Graphic[] targetGraphics
float scaleIcon = 1f
float slideX
float navigationFix
bool isChecked
bool instantClick = true
UISelectableGroup group
TooltipData tooltip
SoundData soundClick
SoundData soundHighlight
Transform animeTarget
Anime animeClick
Anime animeHold
ButtonType buttonType
BaseSkinRoot skinRoot
Action onDoubleClick
Action onRightClick
Action< int > onInputWheel
object refObj
int refInt
string refStr
bool animating
bool selected
Vector3 originalIconScale = Vector3.one
UIButton highlightTarget
Item item
Additional Inherited Members
Static Public Member Functions inherited from UIButton
static void UpdateButtons ()
static void TryHihlight ()
static void TryShowTip (Transform root=null, bool highlight=true, bool ignoreWhenRightClick=true)
static void TryShowTip< T > (Transform root=null, bool highlight=true, bool ignoreWhenRightClick=true)
Static Public Attributes inherited from UIButton
static bool DoSlide
static bool locked
static UIButton lastButton
static UIButton lastHovered
static UIButton currentHighlight
static UIButton currentPressedButton
static float lastClicked
static float doubleClickTime = 0.4f
static Vector2 buttonPos
static Action onPressed
static List< UIButton > buttons = new List<UIButton>()
static Action actionTooltip
Protected Member Functions inherited from UIButton
override void Awake ()
override void OnEnable ()
override void DoStateTransition (SelectionState state, bool instant)
Properties inherited from UIButton
List< Graphic > Graphics [get]
virtual bool CanDragLeftButton [get]
Detailed Description
Definition at line 4 of file ButtonChara.cs.
Member Enumeration Documentation
Mode
enum ButtonChara.Mode
Enumerator
Default
Hire
Journal
Embark
Ranking
Definition at line 6 of file ButtonChara.cs.
    {
        Default,
        Hire,
        Journal,
        Embark,
        Ranking
    }
Member Function Documentation
SetChara()
void ButtonChara.SetChara (Chara c, Mode m) inline
Definition at line 35 of file ButtonChara.cs.
    {
        if ((bool)portrait)
        {
            portrait.SetChara(c);
        }
        if (m == Mode.Ranking)
        {
            textBio.text = ((c.currentZone == null) ? "???" : c.currentZone.Name);
        }
        else
        {
            textAlias.text = c.Aka;
            if ((bool)textBio)
            {
                textBio.text = c.race.GetText().ToTitleCase(wholeText: true) + " " + Lang.Parse("age", c.bio.TextAge(c)) + " " + Lang._gender(c.bio.gender);
            }
        }
        textName.text = c.Name;
        if ((bool)layoutTag)
        {
            layoutTag.DestroyChildren();
            HintIcon hintIcon = Util.Instantiate<HintIcon>("UI/Element/Item/Tag General", layoutTag);
            hintIcon.text.SetText(c.job.GetName().ToTitleCase(wholeText: true));
            hintIcon.RebuildLayout();
            layoutTag.RebuildLayout();
        }
    }
References Lang._gender(), Chara.Aka, Card.bio, Chara.currentZone, Biography.gender, Chara.job, layoutTag, Card.Name, Spatial.Name, Lang.Parse(), portrait, Chara.race, Portrait.SetChara(), UIText.SetText(), HintIcon.text, Biography.TextAge(), textBio, and Util.
Referenced by LayerHire.Refresh(), LayerQuestBoard.RefreshHire(), LayerEmbark.RefreshMembers(), LayerQuestBoard.RefreshRanking(), and ContentRanking.SwitchRanking().
Member Data Documentation
item
new UIItem ButtonChara.item
Definition at line 29 of file ButtonChara.cs.
Referenced by LayerHire.Refresh(), LayerQuestBoard.RefreshHire(), LayerEmbark.RefreshMembers(), LayerQuestBoard.RefreshRanking(), and ContentRanking.SwitchRanking().
layoutTag
LayoutGroup ButtonChara.layoutTag
Definition at line 33 of file ButtonChara.cs.
Referenced by LayerQuestBoard.RefreshHire(), and SetChara().
portrait
Portrait ButtonChara.portrait
Definition at line 15 of file ButtonChara.cs.
Referenced by SetChara().
textAlias
UIText ButtonChara.textAlias
Definition at line 19 of file ButtonChara.cs.
Referenced by LayerQuestBoard.RefreshRanking().
textBio
UIText ButtonChara.textBio
Definition at line 21 of file ButtonChara.cs.
Referenced by SetChara().
textHobby
UIText ButtonChara.textHobby
Definition at line 25 of file ButtonChara.cs.
textLifeStyle
UIText ButtonChara.textLifeStyle
Definition at line 27 of file ButtonChara.cs.
textName
UIText ButtonChara.textName
Definition at line 17 of file ButtonChara.cs.
textWork
UIText ButtonChara.textWork
Definition at line 23 of file ButtonChara.cs.
transDefeated
Transform ButtonChara.transDefeated
Definition at line 31 of file ButtonChara.cs.
Referenced by LayerQuestBoard.RefreshRanking().
The documentation for this class was generated from the following file:
Elin/ButtonChara.cs