Elin Decompiled Documentation: GlobalGoalVisitAndStay Class Reference
GlobalGoalVisitAndStay Class Reference
Public Member Functions
override void OnAdvanceHour ()
virtual void OnStay ()
virtual void OnTravel ()
virtual Zone GetDestZone ()
Public Member Functions inherited from GlobalGoal
void SetOwner (Chara c)
void Start ()
virtual void OnStart ()
void AdvanceHour ()
virtual void OnAdvanceHour ()
void Kill ()
void Complete ()
virtual void OnComplete ()
Public Attributes
int uidZone
Public Attributes inherited from GlobalGoal
int hours
Chara owner
Properties
Zone destZone [get]
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Additional Inherited Members
Static Public Member Functions inherited from EClass
static int rnd (int a)
static int curve (int a, int start, int step, int rate=75)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Static Public Attributes inherited from EClass
static Core core
Detailed Description
Definition at line 4 of file GlobalGoalVisitAndStay.cs.
Member Function Documentation
GetDestZone()
virtual Zone GlobalGoalVisitAndStay.GetDestZone () inline virtual
Reimplemented in GlobalGoalExplore, and GlobalGoalVisitTown.
Definition at line 58 of file GlobalGoalVisitAndStay.cs.
    {
        return owner.homeZone;
    }
References Chara.homeZone, and GlobalGoal.owner.
Referenced by OnAdvanceHour().
OnAdvanceHour()
override void GlobalGoalVisitAndStay.OnAdvanceHour () inline virtual
Reimplemented from GlobalGoal.
Definition at line 11 of file GlobalGoalVisitAndStay.cs.
    {
        if (owner.currentZone == EClass.game.activeZone)
        {
            return;
        }
        if (uidZone == 0)
        {
            if (GetDestZone() == null)
            {
                Kill();
                return;
            }
            uidZone = GetDestZone().uid;
            if (EClass.debug.logAdv)
            {
                Debug.Log(owner.Name + " -> " + destZone.Name + " / " + this);
            }
        }
        if (owner.currentZone == destZone)
        {
            OnStay();
            if (hours > 64 && EClass.rnd(48) == 0)
            {
                Complete();
            }
            return;
        }
        OnTravel();
        if (hours > 6 && EClass.rnd(4) == 0 && destZone != EClass.game.activeZone)
        {
            if (EClass.debug.logAdv)
            {
                Debug.Log(owner.Name + " reached " + destZone.Name);
            }
            owner.MoveZone(destZone, ZoneTransition.EnterState.RandomVisit);
        }
    }
References Game.activeZone, GlobalGoal.Complete(), Chara.currentZone, EClass.debug, Debug, destZone, EClass.game, GetDestZone(), GlobalGoal.hours, GlobalGoal.Kill(), CoreDebug.logAdv, Chara.MoveZone(), Card.Name, Spatial.Name, OnStay(), OnTravel(), GlobalGoal.owner, EClass.rnd(), Spatial.uid, and uidZone.
OnStay()
virtual void GlobalGoalVisitAndStay.OnStay () inline virtual
Definition at line 50 of file GlobalGoalVisitAndStay.cs.
    {
    }
Referenced by OnAdvanceHour().
OnTravel()
virtual void GlobalGoalVisitAndStay.OnTravel () inline virtual
Definition at line 54 of file GlobalGoalVisitAndStay.cs.
    {
    }
Referenced by OnAdvanceHour().
Member Data Documentation
uidZone
int GlobalGoalVisitAndStay.uidZone
Definition at line 7 of file GlobalGoalVisitAndStay.cs.
Referenced by OnAdvanceHour().
Property Documentation
destZone
Zone GlobalGoalVisitAndStay.destZone get
Definition at line 9 of file GlobalGoalVisitAndStay.cs.
Referenced by OnAdvanceHour().
The documentation for this class was generated from the following file:
Elin/GlobalGoalVisitAndStay.cs