Elin Decompiled Documentation: SourceQuest Class Reference
SourceQuest Class Reference
Classes
class Row
Public Member Functions
override Row CreateRow ()
override Row CreateRowByMapping (IReadOnlyDictionary< string, int > mapping)
override void SetRow (Row r)
override IReadOnlyDictionary< string, int > GetRowMapping ()
override IReadOnlyDictionary< string, string > GetTypeMapping ()
Public Member Functions inherited from SourceDataString< SourceQuest.Row >
override T GetRow (string id)
Static Public Attributes
static readonly IReadOnlyDictionary< string, int > RowMapping
static readonly IReadOnlyDictionary< string, string > TypeMapping
Properties
override string[] ImportFields [get]
Detailed Description
Definition at line 4 of file SourceQuest.cs.
Member Function Documentation
CreateRow()
override Row SourceQuest.CreateRow () inline
Definition at line 104 of file SourceQuest.cs.
    {
        return new Row
        {
            id = SourceData.GetString(0),
            name_JP = SourceData.GetString(1),
            name = SourceData.GetString(2),
            type = SourceData.GetString(3),
            drama = SourceData.GetStringArray(4),
            idZone = SourceData.GetString(5),
            group = SourceData.GetString(6),
            tags = SourceData.GetStringArray(7),
            money = SourceData.GetInt(8),
            chance = SourceData.GetInt(9),
            minFame = SourceData.GetInt(10),
            detail_JP = SourceData.GetString(11),
            detail = SourceData.GetString(12),
            talkProgress_JP = SourceData.GetString(13),
            talkProgress = SourceData.GetString(14),
            talkComplete_JP = SourceData.GetString(15),
            talkComplete = SourceData.GetString(16)
        };
    }
References SourceData< T, T2 >.GetInt(), SourceData< T, T2 >.GetString(), SourceData< T, T2 >.GetStringArray(), and money.
CreateRowByMapping()
override Row SourceQuest.CreateRowByMapping (IReadOnlyDictionary< string, int > mapping) inline
Definition at line 128 of file SourceQuest.cs.
    {
        return new Row
        {
            id = SourceData.GetString(mapping["id"]),
            name_JP = SourceData.GetString(mapping["name_JP"]),
            name = SourceData.GetString(mapping["name"]),
            type = SourceData.GetString(mapping["type"]),
            drama = SourceData.GetStringArray(mapping["drama"]),
            idZone = SourceData.GetString(mapping["idZone"]),
            group = SourceData.GetString(mapping["group"]),
            tags = SourceData.GetStringArray(mapping["tags"]),
            money = SourceData.GetInt(mapping["money"]),
            chance = SourceData.GetInt(mapping["chance"]),
            minFame = SourceData.GetInt(mapping["minFame"]),
            detail_JP = SourceData.GetString(mapping["detail_JP"]),
            detail = SourceData.GetString(mapping["detail"]),
            talkProgress_JP = SourceData.GetString(mapping["talkProgress_JP"]),
            talkProgress = SourceData.GetString(mapping["talkProgress"]),
            talkComplete_JP = SourceData.GetString(mapping["talkComplete_JP"]),
            talkComplete = SourceData.GetString(mapping["talkComplete"])
        };
    }
References SourceData< T, T2 >.GetInt(), SourceData< T, T2 >.GetString(), SourceData< T, T2 >.GetStringArray(), and money.
GetRowMapping()
override IReadOnlyDictionary< string, int > SourceQuest.GetRowMapping () inline
Definition at line 157 of file SourceQuest.cs.
    {
        return RowMapping;
    }
References RowMapping.
GetTypeMapping()
override IReadOnlyDictionary< string, string > SourceQuest.GetTypeMapping () inline
Definition at line 162 of file SourceQuest.cs.
    {
        return TypeMapping;
    }
References TypeMapping.
SetRow()
override void SourceQuest.SetRow (Row r) inline
Definition at line 152 of file SourceQuest.cs.
    {
        map[r.id] = r;
    }
References SourceQuest.Row.id.
Member Data Documentation
RowMapping
readonly IReadOnlyDictionary<string, int> SourceQuest.RowMapping static
Initial value:
= new Dictionary<string, int>
    {
        ["id"] = 0,
        ["name_JP"] = 1,
        ["name"] = 2,
        ["type"] = 3,
        ["drama"] = 4,
        ["idZone"] = 5,
        ["group"] = 6,
        ["tags"] = 7,
        ["money"] = 8,
        ["chance"] = 9,
        ["minFame"] = 10,
        ["detail_JP"] = 11,
        ["detail"] = 12,
        ["talkProgress_JP"] = 13,
        ["talkProgress"] = 14,
        ["talkComplete_JP"] = 15,
        ["talkComplete"] = 16
    }
Definition at line 60 of file SourceQuest.cs.
Referenced by GetRowMapping().
TypeMapping
readonly IReadOnlyDictionary<string, string> SourceQuest.TypeMapping static
Initial value:
= new Dictionary<string, string>
    {
        ["id"] = "string",
        ["name_JP"] = "string",
        ["name"] = "string",
        ["type"] = "string",
        ["drama"] = "string[]",
        ["idZone"] = "string",
        ["group"] = "string",
        ["tags"] = "string[]",
        ["money"] = "int",
        ["chance"] = "int",
        ["minFame"] = "int",
        ["detail_JP"] = "string",
        ["detail"] = "string",
        ["talkProgress_JP"] = "string",
        ["talkProgress"] = "string",
        ["talkComplete_JP"] = "string",
        ["talkComplete"] = "string"
    }
Definition at line 81 of file SourceQuest.cs.
Referenced by GetTypeMapping().
Property Documentation
ImportFields
override string [] SourceQuest.ImportFields get
Definition at line 102 of file SourceQuest.cs.
The documentation for this class was generated from the following file:
Elin/SourceQuest.cs