Elin Decompiled Documentation: MsgLog Class Reference
MsgLog Class Reference
Classes
class Data
Public Member Functions
void Add (Data data)
Data Add (string text, FontColor c)
Data Add (string text, string col=null)
List< Data > GetList (bool reverse=false)
Public Attributes
Dictionary< int, Data > dict = new Dictionary<int, Data>()
int currentLogIndex
string id
Properties
int maxLog [get]
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Private Member Functions
void OnSerializing (StreamingContext context)
Additional Inherited Members
Static Public Member Functions inherited from EClass
static int rndSeed (int a, int seed)
static int rnd (long a)
static int rnd (int a)
static int curve (int a, int start, int step, int rate=75)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Static Public Attributes inherited from EClass
static Core core
Detailed Description
Definition at line 6 of file MsgLog.cs.
Member Function Documentation
Add() [1/3]
void MsgLog.Add (Data data) inline
Definition at line 53 of file MsgLog.cs.
    {
        dict.Add(currentLogIndex, data);
        currentLogIndex++;
        if (currentLogIndex >= maxLog)
        {
            dict.Remove(currentLogIndex - maxLog);
        }
    }
References currentLogIndex, dict, and maxLog.
Referenced by Add(), FactionBranch.LogRaw(), Msg.SayRaw(), and GameDate.ShipGoods().
Add() [2/3]
Data MsgLog.Add (string text, FontColor c) inline
Definition at line 63 of file MsgLog.cs.
    {
        return Add(text, c.ToString());
    }
References Add().
Add() [3/3]
Data MsgLog.Add (string text, string col = null) inline
Definition at line 68 of file MsgLog.cs.
    {
        Data data = new Data
        {
            text = text,
            col = col
        };
        data.date = (VirtualDate.current ?? EClass.world.date).Copy();
        Add(data);
        return data;
    }
References Add(), Copy, World.date, and EClass.world.
GetList()
List< Data > MsgLog.GetList (bool reverse = false) inline
Definition at line 80 of file MsgLog.cs.
    {
        List<Data> list = new List<Data>();
        foreach (Data value in dict.Values)
        {
            list.Add(value);
        }
        list.Sort((Data a, Data b) => a.date.GetRaw() - b.date.GetRaw());
        if (reverse)
        {
            list.Reverse();
        }
        return list;
    }
References MsgLog.Data.date, dict, and Date.GetRaw().
Referenced by ContentChronicle.OnSwitchContent(), and ContentHomeLog.RefreshLog().
OnSerializing()
void MsgLog.OnSerializing (StreamingContext context) inline private
Definition at line 42 of file MsgLog.cs.
    {
        foreach (int item in dict.Keys.ToList())
        {
            if (item >= currentLogIndex || item <= currentLogIndex - maxLog)
            {
                dict.Remove(item);
            }
        }
    }
References currentLogIndex, dict, item, and maxLog.
Member Data Documentation
currentLogIndex
int MsgLog.currentLogIndex
Definition at line 24 of file MsgLog.cs.
Referenced by Add(), and OnSerializing().
dict
Dictionary<int, Data> MsgLog.dict = new Dictionary<int, Data>()
Definition at line 21 of file MsgLog.cs.
Referenced by Add(), GetList(), and OnSerializing().
id
string MsgLog.id
Definition at line 27 of file MsgLog.cs.
Property Documentation
maxLog
int MsgLog.maxLog get
Definition at line 29 of file MsgLog.cs.
    {
        get
        {
            if (id == "chronicle")
            {
                return 9999;
            }
            return 50;
        }
    }
Referenced by Add(), and OnSerializing().
The documentation for this class was generated from the following file:
Elin/MsgLog.cs