Elin Decompiled Documentation: CustomMerchantStock Class Reference
CustomMerchantStock Class Reference
Public Member Functions
List< Thing > Generate (Card owner)
override string ToString ()
Public Member Functions inherited from CustomFileContent
bool HasFileChanged ()
virtual void OnSetLang (string lang)
void Load ()
Public Member Functions inherited from CustomContent
virtual void OnGameLoad (GameIOContext context)
virtual void OnGameSave (GameIOContext context)
override string ToString ()
Static Public Member Functions
static CustomMerchantStock CreateFromId (string stockId, ModPackage owner)
Static Public Member Functions inherited from EClass
static int rndSeed (int a, int seed)
static int rnd (long a)
static int rnd (int a)
static int curve (long _a, int start, int step, int rate=75)
static int sqrt (int a)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Public Attributes
List< CustomThingContent > items = new List<CustomThingContent>()
Protected Member Functions
override void LoadContent ()
abstract void LoadContent ()
Additional Inherited Members
Static Public Attributes inherited from EClass
static Core core
Properties inherited from CustomFileContent
DateTime LastModified = DateTime.MinValue [get, set]
FileInfo File [get, set]
Properties inherited from CustomContent
string ContentId [get, protected set]
EMod Owner [get, protected set]
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Detailed Description
Definition at line 8 of file CustomMerchantStock.cs.
Member Function Documentation
CreateFromId()
static CustomMerchantStock CustomMerchantStock.CreateFromId (string stockId, ModPackage owner) inline static
Definition at line 33 of file CustomMerchantStock.cs.
    {
        var (fileInfo, eMod) = PackageIterator.GetFilesEx("Data/stock_" + stockId + ".json").LastOrDefault();
        if (fileInfo == null)
        {
            return null;
        }
        if (owner == null)
        {
            owner = eMod as ModPackage;
        }
        return new CustomMerchantStock
        {
            ContentId = "MerchantStock/" + stockId,
            Owner = owner,
            File = fileInfo
        };
    }
References CustomContent.ContentId, CustomFileContent.File, and CustomContent.Owner.
Referenced by CustomCharaContent.CreateFromRow().
Generate()
List< Thing > CustomMerchantStock.Generate (Card owner) inline
Definition at line 12 of file CustomMerchantStock.cs.
    {
        Load();
        List<Thing> list = new List<Thing>();
        int createLv = owner?.trait?.ShopLv ?? (-1);
        foreach (CustomThingContent item2 in items)
        {
            try
            {
                Thing item = item2.Create(createLv);
                list.Add(item);
            }
            catch (Exception ex)
            {
                ModUtil.LogModError("can't create stock item '" + item2.ContentId + "'\n" + ex.Message, base.Owner);
                Debug.LogError(ex);
            }
        }
        return list;
    }
References Card.Add(), CustomContent.ContentId, CustomThingContent.Create(), Debug, item, items, CustomFileContent.Load(), Trait.ShopLv, and Card.trait.
LoadContent()
override void CustomMerchantStock.LoadContent () inline protected virtual
Implements CustomFileContent.
Definition at line 52 of file CustomMerchantStock.cs.
    {
        CustomMerchantStock customMerchantStock = IO.LoadFile<CustomMerchantStock>(base.File.FullName);
        items = customMerchantStock.items;
    }
References items.
ToString()
override string CustomMerchantStock.ToString () inline
Definition at line 58 of file CustomMerchantStock.cs.
    {
        return $"{base.ContentId}/items({items.Count})";
    }
References $.
Member Data Documentation
items
List<CustomThingContent> CustomMerchantStock.items = new List<CustomThingContent>()
Definition at line 10 of file CustomMerchantStock.cs.
Referenced by Generate(), and LoadContent().
The documentation for this class was generated from the following file:
Elin/CustomMerchantStock.cs