Elin Decompiled Documentation: ConStrife Class Reference
ConStrife Class Reference
Public Member Functions
override bool ShouldOverride (Condition c)
override bool CanStack (Condition c)
override ElementContainer GetElementContainer ()
void AddKill (Chara c)
void SetTurn ()
override void Tick ()
void TryApplyParty ()
void SyncPC ()
override void OnWriteNote (List< string > list)
override void SetOwner (Chara _owner, bool onDeserialize=false)
override void OnRemoved ()
Public Member Functions inherited from BaseBuff
override int GetPhase ()
override bool CanStack (Condition c)
Public Member Functions inherited from BaseDebuff
override bool ShouldOverride (Condition c)
override int GetPhase ()
override BaseNotification CreateNotification ()
Public Member Functions inherited from Condition
override BaseNotification CreateNotification ()
virtual void OnStacked (int p)
Condition SetPerfume (int duration=3)
override void Tick ()
virtual void OnCalculateFov (Fov fov, ref int radius, ref float power)
virtual void OnCreateFov (Fov fov)
override void OnValueChanged ()
void Kill (bool silent=false)
Public Member Functions inherited from BaseCondition
virtual bool CanStack (Condition c)
virtual bool ShouldOverride (Condition c)
virtual bool IsOverrideConditionMet (Condition c, int turn)
virtual bool TryMove (Point p)
virtual ElementContainer GetElementContainer ()
void SetElement (int id)
void SetRefVal (int a, int b)
virtual Color GetSpriteColor ()
override string ToString ()
override string GetText ()
override int GetValue ()
override Color GetColor (Gradient g)
virtual void SetOwner (Chara _owner, bool onDeserialize=false)
void RefreshEmoIcon ()
SourceElement.Row GetElementSource (int i)
void Start ()
virtual bool TryNullify (Condition c)
virtual void OnBeforeStart ()
virtual void OnStart ()
virtual void OnStartOrStack ()
virtual void OnHit (Card attacker, AttackSource source)
virtual void PlayEffect ()
virtual void PlayEndEffect ()
virtual void OnRefresh ()
void SetPhase ()
bool IsNullPhase ()
override int GetPhase ()
void PhaseMsg (bool inc)
override string GetPhaseStr ()
virtual void Tick ()
void Mod (int a, bool force=false)
virtual void OnValueChanged ()
virtual void OnChangePhase (int lastPhase, int newPhase)
virtual void OnRemoved ()
virtual int EvaluatePower (int p)
virtual int EvaluateTurn (int p)
virtual BaseNotification CreateNotification ()
Element GetDefenseAttribute (Chara c=null)
override void _WriteNote (UINote n, bool asChild=false)
virtual void OnWriteNote (List< string > list)
virtual RendererReplacer GetRendererReplacer ()
Public Member Functions inherited from BaseStats
virtual Color GetColor (Gradient gradient)
virtual Color GetColor (SkinColorProfile c)
Color GetColor ()
virtual string GetText ()
virtual string GetPhaseStr ()
virtual int GetValue ()
virtual int GetSortVal ()
virtual Sprite GetSprite ()
virtual void SetText (UIText t, SkinColorProfile cols=null)
virtual int GetPhase ()
void PopText ()
virtual void WriteNote (UINote n, Action< UINote > onWriteNote=null)
virtual void _WriteNote (UINote n, bool asChild=false)
Public Attributes
int exp
int lv
int turn
Public Attributes inherited from BaseCondition
int[] _ints = new int[5]
int phase = -1
ElementContainer elements
Chara owner
Public Attributes inherited from BaseStats
int id
SourceStat.Row _source
Properties
override string TextDuration [get]
int ExpToNext [get]
Properties inherited from BaseBuff
override bool CanManualRemove [get]
Properties inherited from Condition
virtual bool IsKilled [get]
virtual string TextDuration [get]
Properties inherited from BaseCondition
int value [get, set]
int power [get, set]
int refVal [get, set]
int refVal2 [get, set]
bool givenByPcParty [get, set]
bool isPerfume [get, set]
override Chara Owner [get]
virtual string Name [get]
virtual bool IsToggle [get]
virtual bool AllowMultipleInstance [get]
virtual bool ConsumeTurn [get]
virtual bool HasDuration [get]
virtual int MaxDuration [get]
virtual bool PreventRegen [get]
virtual bool ShouldRefresh [get]
virtual bool CancelAI [get]
virtual bool TimeBased [get]
virtual bool SyncRide [get]
virtual bool UseElements [get]
virtual int GainResistFactor [get]
virtual int P2 [get]
SourceElement.Row sourceElement [get]
virtual bool IsElemental [get]
virtual string RefString1 [get]
virtual bool ShouldTryNullify [get]
virtual bool CanManualRemove [get]
Properties inherited from BaseStats
SourceStat.Row source [get]
virtual Emo2 EmoIcon [get]
virtual ConditionType Type [get]
virtual string idSprite [get]
virtual bool ShowInWidget [get]
virtual Chara Owner [get]
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Private Attributes
ElementContainer ec = new ElementContainerCondition()
Additional Inherited Members
Static Public Member Functions inherited from Condition
static T Create< T > (int power=100, Action< T > onCreate=null)
static Condition Create (string alias, int power=100, Action< Condition > onCreate=null)
Static Public Member Functions inherited from EClass
static int rndSeed (int a, int seed)
static int rnd (long a)
static int rnd (int a)
static int curve (long _a, int start, int step, int rate=75)
static int sqrt (int a)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Static Public Attributes inherited from Condition
static bool ignoreEffect
Static Public Attributes inherited from BaseStats
static Chara CC
Static Public Attributes inherited from EClass
static Core core
Detailed Description
Definition at line 5 of file ConStrife.cs.
Member Function Documentation
AddKill()
void ConStrife.AddKill (Chara c) inline
Definition at line 38 of file ConStrife.cs.
    {
        if (!owner.IsPC)
        {
            return;
        }
        if (c.IsPCFactionOrMinion)
        {
            if (c.IsMinion)
            {
                exp += 2;
            }
            else
            {
                exp += 30;
            }
        }
        else
        {
            exp++;
        }
        while (exp >= ExpToNext)
        {
            if (lv >= 5)
            {
                exp = ExpToNext;
                break;
            }
            exp -= ExpToNext;
            lv++;
            ec.SetBase(964, (lv >= 3) ? ((lv - 2) * 5) : 0);
            ec.SetBase(662, lv * 10);
            TryApplyParty();
        }
        SetTurn();
    }
References ec, exp, ExpToNext, Chara.IsMinion, Chara.IsPC, Card.IsPCFactionOrMinion, lv, BaseCondition.owner, ElementContainer.SetBase(), SetTurn(), and TryApplyParty().
CanStack()
override bool ConStrife.CanStack (Condition c) inline virtual
Reimplemented from BaseBuff.
Definition at line 28 of file ConStrife.cs.
    {
        return true;
    }
GetElementContainer()
override ElementContainer ConStrife.GetElementContainer () inline virtual
Reimplemented from BaseCondition.
Definition at line 33 of file ConStrife.cs.
    {
        return ec;
    }
References ec.
OnRemoved()
override void ConStrife.OnRemoved () inline virtual
Reimplemented from BaseCondition.
Definition at line 173 of file ConStrife.cs.
    {
        ec.SetParent();
    }
References ec, and ElementContainer.SetParent().
OnWriteNote()
override void ConStrife.OnWriteNote (List< string > list) inline virtual
Reimplemented from BaseCondition.
Definition at line 138 of file ConStrife.cs.
    {
        list.Add("hintStrife".lang(lv.ToString() ?? "", exp + "/" + ExpToNext));
        list.Add("hintStrife2".lang((lv * 10).ToString() ?? "", (lv * 5).ToString() ?? "").TagColorGoodBad(() => true));
        foreach (Element e in ec.dict.Values)
        {
            if (e.Value == 0)
            {
                continue;
            }
            if (e.IsFlag)
            {
                list.Add(e.Name.TagColorGoodBad(() => e.Value >= 0));
            }
            else if (elements != null && elements.Has(e.id) && elements.Value(e.id) != e.Value)
            {
                list.Add("modValue".lang(e.Name, ((e.Value < 0) ? "" : "+") + elements.Value(e.id) + (e.source.tag.Contains("ratio") ? "%" : "") + " (" + e.Value + ")").TagColor(() => e.Value >= 0));
            }
            else
            {
                list.Add("modValue".lang(e.Name, ((e.Value < 0) ? "" : "+") + e.Value + (e.source.tag.Contains("ratio") ? "%" : "")).TagColorGoodBad(() => e.Value >= 0));
            }
        }
        if (lv >= 2)
        {
            list.Add("hintStrife3".lang().TagColorGoodBad(() => true));
        }
    }
References ElementContainer.dict, ec, BaseCondition.elements, exp, ExpToNext, ElementContainer.Has(), Element.id, Element.IsFlag, lv, Element.Name, Element.source, BaseCondition.ToString(), Element.Value, and ElementContainer.Value().
SetOwner()
override void ConStrife.SetOwner (Chara _owner, bool onDeserialize = false) inline virtual
Reimplemented from BaseCondition.
Definition at line 167 of file ConStrife.cs.
    {
        base.SetOwner(_owner);
        ec.SetParent(owner);
    }
References ec, BaseCondition.owner, and ElementContainer.SetParent().
SetTurn()
void ConStrife.SetTurn () inline
Definition at line 75 of file ConStrife.cs.
    {
        turn = Mathf.Max(100 - lv * 10, 10);
    }
References lv, and turn.
Referenced by AddKill(), and Tick().
ShouldOverride()
override bool ConStrife.ShouldOverride (Condition c) inline virtual
Reimplemented from BaseDebuff.
Definition at line 23 of file ConStrife.cs.
    {
        return false;
    }
SyncPC()
void ConStrife.SyncPC () inline
Definition at line 122 of file ConStrife.cs.
    {
        ConStrife condition = EClass.pc.GetCondition<ConStrife>();
        if (condition == null || condition.lv < 2)
        {
            turn = 0;
            Kill();
            return;
        }
        turn = condition.turn;
        lv = condition.lv;
        exp = condition.exp;
        ec.SetBase(964, condition.ec.GetOrCreateElement(964).vBase);
        ec.SetBase(662, condition.ec.GetOrCreateElement(662).vBase);
    }
References ec, exp, ElementContainer.GetOrCreateElement(), Condition.Kill(), lv, EClass.pc, ElementContainer.SetBase(), turn, and Element.vBase.
Referenced by Tick().
Tick()
override void ConStrife.Tick () inline virtual
Reimplemented from Condition.
Definition at line 80 of file ConStrife.cs.
    {
        if (!owner.IsPC)
        {
            SyncPC();
            return;
        }
        turn--;
        if (turn < 0)
        {
            lv--;
            if (lv >= 1)
            {
                SetTurn();
                exp = ExpToNext / 2;
            }
            else
            {
                Kill();
            }
        }
        else
        {
            TryApplyParty();
        }
    }
References exp, ExpToNext, Chara.IsPC, Condition.Kill(), lv, BaseCondition.owner, SetTurn(), SyncPC(), TryApplyParty(), and turn.
TryApplyParty()
void ConStrife.TryApplyParty () inline
Definition at line 107 of file ConStrife.cs.
    {
        if (lv < 2 || !owner.IsPC)
        {
            return;
        }
        foreach (Chara member in EClass.pc.party.members)
        {
            if (!member.HasCondition<ConStrife>())
            {
                (member.AddCondition<ConStrife>() as ConStrife)?.SyncPC();
            }
        }
    }
References Chara.AddCondition(), Chara.HasCondition(), Chara.IsPC, lv, Party.members, BaseCondition.owner, Chara.party, and EClass.pc.
Referenced by AddKill(), and Tick().
Member Data Documentation
ec
ElementContainer ConStrife.ec = new ElementContainerCondition() private
Definition at line 8 of file ConStrife.cs.
Referenced by AddKill(), GetElementContainer(), OnRemoved(), OnWriteNote(), SetOwner(), and SyncPC().
exp
int ConStrife.exp
Definition at line 11 of file ConStrife.cs.
Referenced by AddKill(), OnWriteNote(), SyncPC(), and Tick().
lv
int ConStrife.lv
Definition at line 14 of file ConStrife.cs.
Referenced by AddKill(), OnWriteNote(), SetTurn(), SyncPC(), Tick(), and TryApplyParty().
turn
int ConStrife.turn
Definition at line 17 of file ConStrife.cs.
Referenced by SetTurn(), SyncPC(), and Tick().
Property Documentation
ExpToNext
int ConStrife.ExpToNext get
Definition at line 21 of file ConStrife.cs.
Referenced by AddKill(), OnWriteNote(), and Tick().
TextDuration
override string ConStrife.TextDuration get
Definition at line 19 of file ConStrife.cs.
The documentation for this class was generated from the following file:
Elin/ConStrife.cs