Elin Decompiled Documentation: PrimitiveUI.PrimitiveCanvas.PUIStrokeElement Class Reference
PrimitiveUI.PrimitiveCanvas.PUIStrokeElement Class Reference
Public Member Functions
PUIStrokeElement (Vector2[] rawPoints, Vector2[] points, StrokeStyle strokeStyle, bool isClosedPath)
void UpdatePoints (Vector2[] newPoints)
override List< UIVertex > GetUIVertexTriangleStream (Vector2 offset, Vector2 scale, Color32 color)
abstract List< UIVertex > GetUIVertexTriangleStream (Vector2 offset, Vector2 scale, Color32 color)
Properties
Vector2[] rawPoints [get, private set]
StrokeStyle strokeStyle [get, private set]
bool isClosedPath [get, private set]
Additional Inherited Members
Protected Attributes inherited from PrimitiveUI.PrimitiveCanvas.PUIElement
Color32 color
Vector2[] points
UIVertex[] uiVerts
List< UIVertex > uiVertexTriangleStream
Detailed Description
Definition at line 71 of file PrimitiveCanvas.cs.
Constructor & Destructor Documentation
PUIStrokeElement()
PrimitiveUI.PrimitiveCanvas.PUIStrokeElement.PUIStrokeElement (Vector2[] rawPoints, Vector2[] points, StrokeStyle strokeStyle, bool isClosedPath) inline
Definition at line 79 of file PrimitiveCanvas.cs.
        {
            uiVerts = new UIVertex[points.Length];
            uiVertexTriangleStream = new List<UIVertex>((points.Length - 1) * 6);
            this.rawPoints = rawPoints;
            this.strokeStyle = strokeStyle;
            this.isClosedPath = isClosedPath;
            color = strokeStyle.color;
            for (int i = 0; i < uiVerts.Length; i++)
            {
                UIVertex simpleVert = UIVertex.simpleVert;
                simpleVert.color = color;
                uiVerts[i] = simpleVert;
            }
            UpdatePoints(points);
        }
References PrimitiveUI.PrimitiveCanvas.PUIElement.color, PrimitiveUI.StrokeStyle.color, PrimitiveUI.PrimitiveCanvas.PUIStrokeElement.isClosedPath, PrimitiveUI.PrimitiveCanvas.PUIElement.points, PrimitiveUI.PrimitiveCanvas.PUIStrokeElement.rawPoints, PrimitiveUI.PrimitiveCanvas.PUIStrokeElement.strokeStyle, PrimitiveUI.PrimitiveCanvas.PUIElement.uiVertexTriangleStream, PrimitiveUI.PrimitiveCanvas.PUIElement.uiVerts, and PrimitiveUI.PrimitiveCanvas.PUIStrokeElement.UpdatePoints().
Member Function Documentation
GetUIVertexTriangleStream()
override List< UIVertex > PrimitiveUI.PrimitiveCanvas.PUIStrokeElement.GetUIVertexTriangleStream (Vector2 offset, Vector2 scale, Color32 color) inline virtual
Implements PrimitiveUI.PrimitiveCanvas.PUIElement.
Definition at line 101 of file PrimitiveCanvas.cs.
        {
            uiVertexTriangleStream.Clear();
            color = (Color)color * (Color)base.color;
            if (color.Equals(uiVerts[0].color))
            {
                for (int i = 0; i < uiVerts.Length; i++)
                {
                    uiVerts[i].position = new Vector3((points[i].x + offset.x) * scale.x, (points[i].y + offset.y) * scale.y, 0f);
                }
            }
            else
            {
                for (int j = 0; j < uiVerts.Length; j++)
                {
                    uiVerts[j].color = color;
                    uiVerts[j].position = new Vector3((points[j].x + offset.x) * scale.x, (points[j].y + offset.y) * scale.y, 0f);
                }
            }
            for (int k = 0; k < uiVerts.Length; k += 4)
            {
                uiVertexTriangleStream.Add(uiVerts[k]);
                uiVertexTriangleStream.Add(uiVerts[k + 1]);
                uiVertexTriangleStream.Add(uiVerts[k + 2]);
                uiVertexTriangleStream.Add(uiVerts[k + 2]);
                uiVertexTriangleStream.Add(uiVerts[k + 3]);
                uiVertexTriangleStream.Add(uiVerts[k]);
            }
            return uiVertexTriangleStream;
        }
References Color, PrimitiveUI.PrimitiveCanvas.PUIElement.color, PrimitiveUI.PrimitiveCanvas.PUIElement.points, PrimitiveUI.PrimitiveCanvas.PUIElement.uiVertexTriangleStream, and PrimitiveUI.PrimitiveCanvas.PUIElement.uiVerts.
UpdatePoints()
void PrimitiveUI.PrimitiveCanvas.PUIStrokeElement.UpdatePoints (Vector2[] newPoints) inline
Definition at line 96 of file PrimitiveCanvas.cs.
        {
            points = newPoints;
        }
References PrimitiveUI.PrimitiveCanvas.PUIElement.points.
Referenced by PrimitiveUI.PrimitiveCanvas.OnRectTransformDimensionsChange(), and PrimitiveUI.PrimitiveCanvas.PUIStrokeElement.PUIStrokeElement().
Property Documentation
isClosedPath
bool PrimitiveUI.PrimitiveCanvas.PUIStrokeElement.isClosedPath get private set
Definition at line 77 of file PrimitiveCanvas.cs.
{ get; private set; }
Referenced by PrimitiveUI.PrimitiveCanvas.OnRectTransformDimensionsChange(), and PrimitiveUI.PrimitiveCanvas.PUIStrokeElement.PUIStrokeElement().
rawPoints
Vector2 [] PrimitiveUI.PrimitiveCanvas.PUIStrokeElement.rawPoints get private set
Definition at line 73 of file PrimitiveCanvas.cs.
{ get; private set; }
Referenced by PrimitiveUI.PrimitiveCanvas.OnRectTransformDimensionsChange(), and PrimitiveUI.PrimitiveCanvas.PUIStrokeElement.PUIStrokeElement().
strokeStyle
StrokeStyle PrimitiveUI.PrimitiveCanvas.PUIStrokeElement.strokeStyle get private set
Definition at line 75 of file PrimitiveCanvas.cs.
{ get; private set; }
Referenced by PrimitiveUI.PrimitiveCanvas.OnRectTransformDimensionsChange(), and PrimitiveUI.PrimitiveCanvas.PUIStrokeElement.PUIStrokeElement().
The documentation for this class was generated from the following file:
Elin/Plugins.UI/PrimitiveUI/PrimitiveCanvas.cs