Elin Decompiled Documentation: TalkDataList Class Reference
TalkDataList Class Reference
Public Member Functions
override void OnInitialize ()
string GetTalk (string id, string idTopic, bool useDefault=false, bool human=true)
string GetRandomID (string tag)
Public Member Functions inherited from ExcelDataList
void Reload ()
virtual void Initialize ()
virtual void OnInitialize ()
Dictionary< string, string > GetRow (string id)
Public Attributes
List< string > IDs
Public Attributes inherited from ExcelDataList
List< ExcelData > items = new List<ExcelData>(0)
Dictionary< string, Dictionary< string, string > > all = new Dictionary<string, Dictionary<string, string>>()
List< Dictionary< string, string > > list = new List<Dictionary<string, string>>()
Properties
override int StartIndex [get]
Properties inherited from ExcelDataList
virtual int StartIndex [get]
Additional Inherited Members
Protected Attributes inherited from ExcelDataList
bool initialized
Detailed Description
Definition at line 5 of file TalkDataList.cs.
Member Function Documentation
GetRandomID()
string TalkDataList.GetRandomID (string tag) inline
Definition at line 58 of file TalkDataList.cs.
    {
        return IDs.RandomItem();
    }
References IDs.
Referenced by Card.SetRandomTalk().
GetTalk()
string TalkDataList.GetTalk (string id, string idTopic, bool useDefault = false, bool human = true) inline
Definition at line 23 of file TalkDataList.cs.
    {
        if (!initialized)
        {
            Initialize();
        }
        bool flag = false;
        Dictionary<string, string> dictionary = all.TryGetValue(idTopic);
        if (dictionary == null)
        {
            return "";
        }
        string text = dictionary.TryGetValue(id);
        if (text.IsEmpty())
        {
            if (!useDefault)
            {
                Debug.LogError("id not found:" + id);
                return "";
            }
            text = dictionary.TryGetValue("default");
            flag = true;
        }
        text = text.Split(new string[3] { "\r\n", "\r", "\n" }, StringSplitOptions.None).RandomItem();
        if (!human)
        {
            if (flag && !text.IsEmpty() && !text.StartsWith("(") && !text.StartsWith("*"))
            {
                text = "(" + text + ")";
            }
            text = text.Replace("。)", ")");
        }
        return text;
    }
References ExcelDataList.all, Debug, human, ExcelDataList.Initialize(), and ExcelDataList.initialized.
Referenced by Person.GetDramaTitle(), Card.GetTalkText(), and Card.HasTalk().
OnInitialize()
override void TalkDataList.OnInitialize () inline virtual
Reimplemented from ExcelDataList.
Definition at line 11 of file TalkDataList.cs.
    {
        IDs = new List<string>();
        foreach (string key in list[0].Keys)
        {
            if (key != "id" && key != "path")
            {
                IDs.Add(key);
            }
        }
    }
References IDs, and ExcelDataList.list.
Member Data Documentation
IDs
List<string> TalkDataList.IDs
Definition at line 7 of file TalkDataList.cs.
Referenced by GetRandomID(), and OnInitialize().
Property Documentation
StartIndex
override int TalkDataList.StartIndex get
Definition at line 9 of file TalkDataList.cs.
The documentation for this class was generated from the following file:
Elin/Plugins.basecore/TalkDataList.cs