Elin Decompiled Documentation: LiquidProfile Class Reference
LiquidProfile Class Reference
Public Member Functions
void Apply (Color? previewColor=null)
void ApplyColor ()
Static Public Member Functions
static LiquidProfile Get (string id)
static void Apply (string id)
Static Public Member Functions inherited from EScriptable
static int rnd (int a)
Public Attributes
Color modColor
float transparency
Texture2D surface
Vector4 surfaceAnime
Detailed Description
Definition at line 3 of file LiquidProfile.cs.
Member Function Documentation
Apply() [1/2]
void LiquidProfile.Apply (Color? previewColor = null) inline
Definition at line 23 of file LiquidProfile.cs.
    {
        BaseTileMap tileMap = EClass.scene.screenElin.tileMap;
        Set(tileMap.passLiquid.mat);
        Set(tileMap.passFloorWater.mat);
        Set(tileMap.passAutoTileWater.mat);
        void Set(Material mat)
        {
            mat.SetFloat("_Transparency", transparency);
            mat.SetColor("_ModColor", previewColor ?? EClass._map.config.colorLiquid?.Get() ?? modColor);
            mat.SetVector("_SurfaceAnime", surfaceAnime);
            mat.SetTexture("_SurfaceTex", surface);
        }
    }
References EClass._map, MapConfig.colorLiquid, Map.config, SerializableColor.Get(), MeshPass.mat, Material, modColor, BaseTileMap.passAutoTileWater, BaseTileMap.passFloorWater, BaseTileMap.passLiquid, EClass.scene, Scene.screenElin, surface, surfaceAnime, BaseGameScreen.tileMap, and transparency.
Apply() [2/2]
static void LiquidProfile.Apply (string id) inline static
Definition at line 18 of file LiquidProfile.cs.
    {
        Get(id).Apply();
    }
References Apply(), and Get().
Referenced by Apply(), Scene.ApplyZoneConfig(), and WidgetSceneCustomizer.ShowPicker().
ApplyColor()
void LiquidProfile.ApplyColor () inline
Definition at line 38 of file LiquidProfile.cs.
    {
        modColor = EClass._map.config.colorLiquid.Get();
    }
References EClass._map, MapConfig.colorLiquid, Map.config, SerializableColor.Get(), and modColor.
Get()
static LiquidProfile LiquidProfile.Get (string id) inline static
Definition at line 13 of file LiquidProfile.cs.
    {
        return Resources.Load<LiquidProfile>("Scene/Profile/Liquid/" + id);
    }
Referenced by Apply(), WidgetSceneCustomizer.RefreshColor(), and WidgetSceneCustomizer.ShowPicker().
Member Data Documentation
modColor
Color LiquidProfile.modColor
Definition at line 5 of file LiquidProfile.cs.
Referenced by Apply(), ApplyColor(), WidgetSceneCustomizer.RefreshColor(), and WidgetSceneCustomizer.ShowPicker().
surface
Texture2D LiquidProfile.surface
Definition at line 9 of file LiquidProfile.cs.
Referenced by Apply().
surfaceAnime
Vector4 LiquidProfile.surfaceAnime
Definition at line 11 of file LiquidProfile.cs.
Referenced by Apply().
transparency
float LiquidProfile.transparency
Definition at line 7 of file LiquidProfile.cs.
Referenced by Apply().
The documentation for this class was generated from the following file:
Elin/LiquidProfile.cs