Elin Decompiled Documentation: LayerShippingResult Class Reference
LayerShippingResult Class Reference
Public Member Functions
void Show ()
void UpdateRepeating ()
void Refresh ()
void Show (ShippingResult _result)
Public Member Functions inherited from ELayer
override void OnBeforeAddLayer ()
void InitInspector ()
sealed override void Init ()
override void OnAfterAddLayer ()
void TryShowHelp ()
void AddLayerToUI (string id)
void TryShowHint (string _langHint=null)
void TalkHomeMemeber (string id)
void TalkMaid (string id)
override void OnRightClick ()
Public Member Functions inherited from Layer
virtual string GetTextHeader (Window window)
virtual bool HeaderIsListOf (int id)
virtual void Init ()
virtual void OnInit ()
virtual void OnAfterInit ()
virtual void ApplySkin ()
void ShowScreenLock (string id)
void UpdateInput ()
virtual void OnUpdateInput ()
virtual void OnRightClick ()
virtual bool OnBack ()
virtual void OnChangeLayer ()
virtual void OnCreate ()
void _AddLayer (string id)
Layer AddLayer (string id)
T AddLayer< T > ()
T AddLayer< T > (string id)
T AddLayerDontCloseOthers< T > ()
Layer AddLayerDontCloseOthers (Layer l)
T GetOrAddLayer< T > ()
virtual void OnBeforeAddLayer ()
virtual void OnAfterAddLayer ()
Layer AddLayer (Layer l)
void ToggleLayer (string id)
T ToggleLayer< T > (string id=null)
void WaitAndClose ()
void OnClickClose ()
virtual void Close ()
void CloseLayers ()
void RemoveLayers (bool removeImportant=false)
bool RemoveLayer< T > ()
void RemoveLayer (Layer l)
virtual void OnKill ()
Layer SetOnKill (Action action)
void DisableClose ()
void Delay (float duration=0.05f)
Layer SetDelay (float d)
Layer GetLayer (string id)
T GetLayer< T > (bool fromTop=false)
Layer GetTopLayer ()
void SwitchContent (int idWindow, int i)
virtual void OnSwitchContent (Window window)
Layer SetTitles (string langList, string idHeaderRow=null)
bool IsBlockWidgetClick ()
bool IsHideHud ()
bool IsAllowGeneralInput ()
bool IsUseBlur ()
bool IsPointerOnLayer ()
void ApplySkin ()
Public Attributes
UIList list
UIButton buttonNext
UIButton buttonPrev
Image gaugeGold
Image gaugeHearth
Image gaugeDebt
Image imageBG
UIText textGold
UIText textGold2
UIText textHearth
UIText textHearth2
UIText textHome
UIText textIncome
UIText textIncomeTotal
UIText textTitle
UIText textDebt
bool showEffect = true
float duration
int update
int maxUpdate
ShippingResult result
Sprite[] spriteBG
Public Attributes inherited from Layer
Option option
UnityEvent onKill
Anime animeIn
Anime animeOut
bool closeOthers
bool defaultActionMode = true
Button screenLock
Layer parent
string idLayer
List< Layer > layers = new List<Layer>()
Vector2 lastParentPos
List< Window > windows = new List<Window>()
string langHint
Private Member Functions
new void Awake ()
Private Attributes
int lastBonus
Additional Inherited Members
Static Public Member Functions inherited from ELayer
static int rnd (int a)
Static Public Member Functions inherited from Layer
static T Create< T > ()
static T Create< T > (string path)
static Layer Create (string path)
Static Public Attributes inherited from Layer
static int skipInput
static bool closeOnRightClick
static bool rightClicked
static bool cancelKeyDown
static bool ignoreSounds
static Transform blurStopInstance
static string[] searchPath = new string[3] { "Layer", "Layer/Dialog", "Layer/LayerHome" }
Protected Member Functions inherited from ELayer
sealed override void _Close ()
sealed override void Kill ()
virtual void Awake ()
virtual void _Close ()
virtual void Kill ()
Protected Attributes inherited from Layer
RectTransform _rect
bool isDestroyed
Properties inherited from ELayer
static Core core [get]
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static FactionBranch Branch [get]
static Faction Home [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static CoreConfig config [get]
static GameSetting setting [get]
static ColorProfile Colors [get]
static SourceManager sources [get]
static World world [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
bool IsFloat [get]
virtual string IdHelp [get]
Properties inherited from Layer
Layer TopLayer [get]
string uid [get]
virtual RectTransform rectLayers [get]
virtual bool blockWidgetClick [get]
Detailed Description
Definition at line 5 of file LayerShippingResult.cs.
Member Function Documentation
Awake()
new void LayerShippingResult.Awake () inline private virtual
Reimplemented from Layer.
Definition at line 53 of file LayerShippingResult.cs.
    {
        Rand.SetSeed(ELayer.game.seed + ELayer.player.stats.days);
        int num = ELayer.rnd(spriteBG.Length);
        if (num == 1 && ELayer.game.cards.globalCharas.Find("corgon") == null)
        {
            num = 0;
        }
        if (num == 2 && ELayer.game.cards.globalCharas.Find("loytel") == null)
        {
            num = 0;
        }
        imageBG.sprite = spriteBG[num];
        Rand.SetSeed();
        base.Awake();
    }
References Game.cards, Player.Stats.days, CardManager.GlobalCharaList.Find(), ELayer.game, CardManager.globalCharas, ELayer.player, ELayer.rnd(), Game.seed, Rand.SetSeed(), spriteBG, and Player.stats.
Refresh()
void LayerShippingResult.Refresh () inline
Definition at line 85 of file LayerShippingResult.cs.
    {
        if (update == 0)
        {
            lastBonus = 0;
        }
        if (!showEffect)
        {
            if (update != maxUpdate)
            {
                DOTweenAnimation[] componentsInChildren = GetComponentsInChildren<DOTweenAnimation>();
                foreach (DOTweenAnimation dOTweenAnimation in componentsInChildren)
                {
                    if (dOTweenAnimation.tween != null)
                    {
                        dOTweenAnimation.tween.Kill(complete: true);
                    }
                }
            }
            update = maxUpdate;
        }
        FactionBranch branch = (ELayer.game.spatials.Find(result.uidZone) ?? ELayer.pc.homeZone).branch;
        float num = (float)update / (float)maxUpdate;
        int income = result.GetIncome();
        income = (int)((float)income * num);
        int a = result.total + income;
        textIncome.text = Lang._currency(income, showUnit: true);
        textIncomeTotal.text = Lang._currency(a, showUnit: true);
        int shippingBonus = ELayer.player.stats.GetShippingBonus(result.total);
        int shippingBonus2 = ELayer.player.stats.GetShippingBonus(a);
        int lastShippingExp = ELayer.player.stats.lastShippingExp;
        int lastShippingExpMax = ELayer.player.stats.lastShippingExpMax;
        int hearthLv = result.hearthLv;
        int num2 = (int)((float)result.hearthExpGained * num);
        int nextExp = branch.GetNextExp(hearthLv);
        int num3 = result.hearthExp + num2;
        gaugeGold.rectTransform.sizeDelta = new Vector2(Mathf.Min(300, 300 * lastShippingExp / lastShippingExpMax), 50f);
        gaugeHearth.rectTransform.sizeDelta = new Vector2(Mathf.Min(300, 300 * num3 / nextExp), 50f);
        gaugeDebt.rectTransform.sizeDelta = new Vector2(Mathf.Min(300f, 300f * ((float)result.debt / 20000000f)), 50f);
        textGold.text = "shipping_nextGold".lang(lastShippingExp.ToFormat(), lastShippingExpMax.ToFormat());
        int num4 = shippingBonus2 - shippingBonus;
        textGold2.text = ((num4 == 0) ? "" : ("+" + num4));
        textHearth.text = "shipping_hearth".lang(hearthLv.ToString() ?? "", (100f * (float)num3 / (float)nextExp).ToString("F1"));
        float num5 = 100f * (float)num2 / (float)nextExp;
        textHearth2.text = ((num5 == 0f) ? "" : ("+" + num5.ToString("F1") + "%"));
        textDebt.text = (ELayer.game.quests.IsStarted<QuestDebt>() ? (Lang._currency(result.debt, showUnit: true) ?? "") : "???");
        gaugeDebt.SetActive(ELayer.game.quests.IsStarted<QuestDebt>());
        if (shippingBonus2 - shippingBonus != lastBonus)
        {
            lastBonus = shippingBonus2 - shippingBonus;
            if (showEffect)
            {
                SE.Play("ore_drop");
            }
        }
        update++;
        if (showEffect && update > maxUpdate)
        {
            SE.Play("regi");
            showEffect = false;
        }
    }
References Lang._currency(), ShippingResult.debt, SpatialManager.Find(), ELayer.game, gaugeDebt, ShippingResult.GetIncome(), FactionBranch.GetNextExp(), Player.Stats.GetShippingBonus(), ShippingResult.hearthLv, Chara.homeZone, lastBonus, Player.Stats.lastShippingExp, Player.Stats.lastShippingExpMax, maxUpdate, ELayer.pc, ELayer.player, Game.quests, result, showEffect, Game.spatials, Player.stats, ShippingResult.total, ShippingResult.uidZone, and update.
Referenced by Show(), and UpdateRepeating().
Show() [1/2]
void LayerShippingResult.Show () inline
Definition at line 70 of file LayerShippingResult.cs.
    {
        Show(ELayer.player.shippingResults.LastItem() ?? new ShippingResult());
        SE.Play("money_shipping");
        InvokeRepeating("UpdateRepeating", 0f, duration / (float)maxUpdate);
    }
References duration, maxUpdate, ELayer.player, Player.shippingResults, and Show().
Referenced by Show().
Show() [2/2]
void LayerShippingResult.Show (ShippingResult _result) inline
Definition at line 148 of file LayerShippingResult.cs.
    {
        result = _result;
        Zone zone = ELayer.game.spatials.Find(result.uidZone) ?? ELayer.pc.homeZone;
        _ = zone.branch;
        list.callbacks = new UIList.Callback<ShippingResult.Item, UIItem>
        {
            onInstantiate = delegate(ShippingResult.Item a, UIItem b)
            {
                b.text1.SetText(a.text);
                b.text2.SetText(a.income.ToFormat());
            }
        };
        list.Clear();
        foreach (ShippingResult.Item item in result.items)
        {
            list.Add(item);
        }
        list.Refresh();
        Date date = Date.ToDate(result.rawDate);
        textTitle.text = date.month + "/" + date.day + " " + date.year;
        textHome.text = "shipping_home".lang(zone.Name);
        Refresh();
        int count = ELayer.player.shippingResults.Count;
        int index = ELayer.player.shippingResults.IndexOf(result);
        buttonNext.SetActive(index != -1 && count > index + 1);
        buttonPrev.SetActive(index > 0);
        buttonNext.SetOnClick(delegate
        {
            showEffect = false;
            Show(ELayer.player.shippingResults[index + 1]);
        });
        buttonPrev.SetOnClick(delegate
        {
            showEffect = false;
            Show(ELayer.player.shippingResults[index - 1]);
        });
        this.RebuildLayout(recursive: true);
    }
References UIList.Add(), Zone.branch, buttonNext, buttonPrev, UIList.Clear(), SpatialManager.Find(), ELayer.game, Chara.homeZone, item, ShippingResult.items, list, Spatial.Name, ELayer.pc, ELayer.player, ShippingResult.rawDate, Refresh(), UIList.Refresh(), result, UIText.SetText(), Player.shippingResults, Show(), showEffect, Game.spatials, UIItem.text1, UIItem.text2, Date.ToDate(), ShippingResult.uidZone, and Date.year.
UpdateRepeating()
void LayerShippingResult.UpdateRepeating () inline
Definition at line 77 of file LayerShippingResult.cs.
    {
        if (showEffect)
        {
            Refresh();
        }
    }
References Refresh(), and showEffect.
Member Data Documentation
buttonNext
UIButton LayerShippingResult.buttonNext
Definition at line 9 of file LayerShippingResult.cs.
Referenced by Show().
buttonPrev
UIButton LayerShippingResult.buttonPrev
Definition at line 11 of file LayerShippingResult.cs.
Referenced by Show().
duration
float LayerShippingResult.duration
Definition at line 41 of file LayerShippingResult.cs.
Referenced by Show().
gaugeDebt
Image LayerShippingResult.gaugeDebt
Definition at line 17 of file LayerShippingResult.cs.
Referenced by Refresh().
gaugeGold
Image LayerShippingResult.gaugeGold
Definition at line 13 of file LayerShippingResult.cs.
gaugeHearth
Image LayerShippingResult.gaugeHearth
Definition at line 15 of file LayerShippingResult.cs.
imageBG
Image LayerShippingResult.imageBG
Definition at line 19 of file LayerShippingResult.cs.
lastBonus
int LayerShippingResult.lastBonus private
Definition at line 51 of file LayerShippingResult.cs.
Referenced by Refresh().
list
UIList LayerShippingResult.list
Definition at line 7 of file LayerShippingResult.cs.
Referenced by Show().
maxUpdate
int LayerShippingResult.maxUpdate
Definition at line 45 of file LayerShippingResult.cs.
Referenced by Refresh(), and Show().
result
ShippingResult LayerShippingResult.result
Definition at line 47 of file LayerShippingResult.cs.
Referenced by Refresh(), and Show().
showEffect
bool LayerShippingResult.showEffect = true
Definition at line 39 of file LayerShippingResult.cs.
Referenced by Refresh(), Show(), and UpdateRepeating().
spriteBG
Sprite [] LayerShippingResult.spriteBG
Definition at line 49 of file LayerShippingResult.cs.
Referenced by Awake().
textDebt
UIText LayerShippingResult.textDebt
Definition at line 37 of file LayerShippingResult.cs.
textGold
UIText LayerShippingResult.textGold
Definition at line 21 of file LayerShippingResult.cs.
textGold2
UIText LayerShippingResult.textGold2
Definition at line 23 of file LayerShippingResult.cs.
textHearth
UIText LayerShippingResult.textHearth
Definition at line 25 of file LayerShippingResult.cs.
textHearth2
UIText LayerShippingResult.textHearth2
Definition at line 27 of file LayerShippingResult.cs.
textHome
UIText LayerShippingResult.textHome
Definition at line 29 of file LayerShippingResult.cs.
textIncome
UIText LayerShippingResult.textIncome
Definition at line 31 of file LayerShippingResult.cs.
textIncomeTotal
UIText LayerShippingResult.textIncomeTotal
Definition at line 33 of file LayerShippingResult.cs.
textTitle
UIText LayerShippingResult.textTitle
Definition at line 35 of file LayerShippingResult.cs.
update
int LayerShippingResult.update
Definition at line 43 of file LayerShippingResult.cs.
Referenced by Refresh().
The documentation for this class was generated from the following file:
Elin/LayerShippingResult.cs