Elin Decompiled Documentation: LayerInteraction Class Reference
LayerInteraction Class Reference
Classes
class Item
class Page
Public Types
enum Mode {
Map , Inventory , EloMap , Area ,
Custom
}
Public Member Functions
override void OnInit ()
override void OnKill ()
override void OnUpdateInput ()
void Show (List< Page > _pages, Mode _mode)
void ShowPage (int index)
void ShowPage (Page page)
void Reload ()
Public Member Functions inherited from ELayer
override void OnBeforeAddLayer ()
void InitInspector ()
sealed override void Init ()
override void OnAfterAddLayer ()
void TryShowHelp ()
void AddLayerToUI (string id)
void TryShowHint (string _langHint=null)
void TalkHomeMemeber (string id)
void TalkMaid (string id)
override void OnRightClick ()
Public Member Functions inherited from Layer
virtual string GetTextHeader (Window window)
virtual bool HeaderIsListOf (int id)
virtual void Init ()
virtual void OnInit ()
virtual void OnAfterInit ()
virtual void ApplySkin ()
void ShowScreenLock (string id)
void UpdateInput ()
virtual void OnUpdateInput ()
virtual void OnRightClick ()
virtual bool OnBack ()
virtual void OnChangeLayer ()
virtual void OnCreate ()
void _AddLayer (string id)
Layer AddLayer (string id)
T AddLayer< T > ()
T AddLayer< T > (string id)
T AddLayerDontCloseOthers< T > ()
Layer AddLayerDontCloseOthers (Layer l)
T GetOrAddLayer< T > ()
virtual void OnBeforeAddLayer ()
virtual void OnAfterAddLayer ()
Layer AddLayer (Layer l)
void ToggleLayer (string id)
T ToggleLayer< T > (string id=null)
void WaitAndClose ()
void OnClickClose ()
virtual void Close ()
void CloseLayers ()
void RemoveLayers (bool removeImportant=false)
bool RemoveLayer< T > ()
void RemoveLayer (Layer l)
virtual void OnKill ()
Layer SetOnKill (Action action)
void DisableClose ()
void Delay (float duration=0.05f)
Layer SetDelay (float d)
Layer GetLayer (string id)
T GetLayer< T > (bool fromTop=false)
Layer GetTopLayer ()
void SwitchContent (int idWindow, int i)
virtual void OnSwitchContent (Window window)
Layer SetTitles (string langList, string idHeaderRow=null)
bool IsBlockWidgetClick ()
bool IsHideHud ()
bool IsAllowGeneralInput ()
bool IsUseBlur ()
bool IsPointerOnLayer ()
void ApplySkin ()
Static Public Member Functions
static void Show (IInspect newTarget)
static bool TryShow (bool quick)
static Page GetPage (IInspect o)
Static Public Member Functions inherited from ELayer
static int rnd (int a)
Static Public Member Functions inherited from Layer
static T Create< T > ()
static T Create< T > (string path)
static Layer Create (string path)
Public Attributes
Mode mode
Point point
List< Page > pages = new List<Page>()
InteractionMenu menu
WindowChara windowChara
Public Attributes inherited from Layer
Option option
UnityEvent onKill
Anime animeIn
Anime animeOut
bool closeOthers
bool defaultActionMode = true
Button screenLock
Layer parent
string idLayer
List< Layer > layers = new List<Layer>()
Vector2 lastParentPos
List< Window > windows = new List<Window>()
string langHint
Static Public Attributes
static LayerInteraction Instance
static IInspect Target
Static Public Attributes inherited from Layer
static int skipInput
static bool closeOnRightClick
static bool rightClicked
static bool cancelKeyDown
static bool ignoreSounds
static Transform blurStopInstance
static string[] searchPath = new string[3] { "Layer", "Layer/Dialog", "Layer/LayerHome" }
Private Member Functions
void Update ()
Private Attributes
bool first = true
Additional Inherited Members
Protected Member Functions inherited from ELayer
sealed override void _Close ()
sealed override void Kill ()
Protected Member Functions inherited from Layer
virtual void Awake ()
virtual void _Close ()
virtual void Kill ()
Protected Attributes inherited from Layer
RectTransform _rect
bool isDestroyed
Properties inherited from ELayer
static Core core [get]
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static FactionBranch Branch [get]
static Faction Home [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static CoreConfig config [get]
static GameSetting setting [get]
static ColorProfile Colors [get]
static SourceManager sources [get]
static World world [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
bool IsFloat [get]
virtual string IdHelp [get]
Properties inherited from Layer
Layer TopLayer [get]
string uid [get]
virtual RectTransform rectLayers [get]
virtual bool blockWidgetClick [get]
Detailed Description
Definition at line 5 of file LayerInteraction.cs.
Member Enumeration Documentation
Mode
enum LayerInteraction.Mode
Enumerator
Map
Inventory
EloMap
Area
Custom
Definition at line 7 of file LayerInteraction.cs.
    {
        Map,
        Inventory,
        EloMap,
        Area,
        Custom
    }
Member Function Documentation
GetPage()
static Page LayerInteraction.GetPage (IInspect o) inline static
Definition at line 142 of file LayerInteraction.cs.
    {
        Page page = new Page();
        _ = page.items;
        if (o is Area)
        {
            Area area = o as Area;
            page.area = area;
        }
        else if (o is Chara)
        {
            Chara t2 = o as Chara;
            string text = "charaInfo".lang();
            if (!t2.IsHomeMember())
            {
                text = text + "(" + "unidentified".lang() + ")";
            }
            if (t2.IsHomeMember())
            {
                page.Add(t2, "tTalk".lang(), "", delegate
                {
                    t2.ShowDialog();
                });
            }
            else
            {
                page.Add(t2, text, "", delegate
                {
                    if (!t2.IsHomeMember())
                    {
                        SE.Beep();
                    }
                });
            }
        }
        else if (o is Thing)
        {
            Thing t = o as Thing;
            page.Add(t, "objInfo", "", delegate
            {
                ELayer.ui.AddLayer<LayerInfo>().Set(t);
            });
            if (t.trait is TraitQuestBoard)
            {
                page.Add(t, "quest", "", delegate
                {
                    ELayer.ui.AddLayer<LayerQuestBoard>();
                }, 20, auto: true);
                page.Add(t, "hire", "", delegate
                {
                    ELayer.ui.AddLayer<LayerHire>();
                }, 20, auto: true);
            }
            if (t.trait is TraitGacha)
            {
                page.Add(t, "gacha", "", delegate
                {
                    ELayer.ui.AddLayer<LayerGacha>();
                }, 10, auto: true);
            }
            if (t.trait.IsFactory)
            {
                page.Add(t, "craft", "icon_Inspect", delegate
                {
                    ELayer.ui.AddLayer<LayerCraft>().SetFactory(t);
                }, 100, auto: true);
            }
            if (t.IsInstalled)
            {
                page.Add(t, "move", "", delegate
                {
                    ActionMode.Inspect.Activate(t);
                });
            }
        }
        return page;
    }
References AM_MoveInstalled.Activate(), LayerInteraction.Page.Add(), Area, ActionMode.Inspect, Trait.IsFactory, Chara.IsHomeMember(), Card.IsInstalled, LayerInteraction.Page.items, Chara.ShowDialog(), Card.trait, and ELayer.ui.
Referenced by Show().
OnInit()
override void LayerInteraction.OnInit () inline virtual
Reimplemented from Layer.
Definition at line 95 of file LayerInteraction.cs.
    {
        Instance = this;
        first = true;
    }
References first, and Instance.
OnKill()
override void LayerInteraction.OnKill () inline virtual
Reimplemented from Layer.
Definition at line 101 of file LayerInteraction.cs.
    {
        Target = null;
    }
References Target.
OnUpdateInput()
override void LayerInteraction.OnUpdateInput () inline virtual
Reimplemented from Layer.
Definition at line 118 of file LayerInteraction.cs.
    {
    }
Reload()
void LayerInteraction.Reload () inline
Definition at line 293 of file LayerInteraction.cs.
    {
    }
Show() [1/2]
static void LayerInteraction.Show (IInspect newTarget) inline static
Definition at line 122 of file LayerInteraction.cs.
    {
        if (Target != newTarget)
        {
            Target = newTarget;
            Page page = GetPage(Target);
            ((Instance != null) ? Instance : ELayer.ui.AddLayer<LayerInteraction>()).ShowPage(page);
        }
    }
References GetPage(), Instance, ShowPage(), Target, and ELayer.ui.
Referenced by TryShow().
Show() [2/2]
void LayerInteraction.Show (List< Page > _pages, Mode _mode) inline
Definition at line 220 of file LayerInteraction.cs.
    {
        pages = _pages;
        mode = _mode;
        switch (mode)
        {
        case Mode.Map:
            point.Set(Scene.HitPoint);
            break;
        case Mode.EloMap:
        {
            Page page = new Page();
            pages = new List<Page>();
            pages.Add(page);
            page.Add(null, "test1", "", delegate
            {
            });
            page.Add(null, "test2", "", delegate
            {
            });
            break;
        }
        }
        foreach (Page page2 in pages)
        {
            ButtonGrid buttonGrid = (ButtonGrid)(page2.button = menu.Add() as ButtonGrid);
            buttonGrid.SetObject(page2.items[0].target);
            Page _page = page2;
            buttonGrid.onClick.AddListener(delegate
            {
                ShowPage(_page);
                SE.Click();
            });
            buttonGrid.RebuildLayout(recursive: true);
        }
        menu.Show();
        ShowPage(0);
    }
References InteractionMenu.Add(), LayerInteraction.Page.Add(), LayerInteraction.Page.button, Scene.HitPoint, LayerInteraction.Page.items, menu, mode, pages, point, Point.Set(), ButtonGrid.SetObject(), InteractionMenu.Show(), and ShowPage().
ShowPage() [1/2]
void LayerInteraction.ShowPage (int index) inline
Definition at line 259 of file LayerInteraction.cs.
    {
        ShowPage(pages[index]);
    }
References pages, and ShowPage().
Referenced by Show(), and ShowPage().
ShowPage() [2/2]
void LayerInteraction.ShowPage (Page page) inline
Definition at line 264 of file LayerInteraction.cs.
    {
        menu.Clear();
        foreach (Item item in page.items)
        {
            UIButton uIButton = menu.Add();
            uIButton.icon.sprite = SpriteSheet.Get(item.idSprite.IsEmpty("icon_" + item.text)) ?? uIButton.icon.sprite;
            uIButton.mainText.SetText((item.textFunc != null) ? item.textFunc() : item.text.lang());
            uIButton.onClick.AddListener(delegate
            {
                item.action();
                if (item.reload)
                {
                    Reload();
                    ShowPage(page);
                }
            });
            uIButton.RebuildLayout(recursive: true);
        }
        Chara chara = Target as Chara;
        bool flag = chara?.IsHomeMember() ?? false;
        windowChara.SetActive(flag);
        if (flag)
        {
            windowChara.SetChara(chara);
        }
        menu.Show();
    }
References InteractionMenu.Add(), InteractionMenu.Clear(), SpriteSheet.Get(), UIButton.icon, Chara.IsHomeMember(), item, UIButton.mainText, menu, WindowChara.SetChara(), UIText.SetText(), InteractionMenu.Show(), Target, and windowChara.
TryShow()
static bool LayerInteraction.TryShow (bool quick) inline static
Definition at line 132 of file LayerInteraction.cs.
    {
        if (!Scene.HitPoint.IsValid)
        {
            return false;
        }
        Show(ELayer.scene.mouseTarget.pos.ListInspectorTargets().NextItem(Target));
        return true;
    }
References Scene.HitPoint, Point.IsValid, Point.ListInspectorTargets(), Scene.mouseTarget, PointTarget.pos, ELayer.scene, Show(), and Target.
Update()
void LayerInteraction.Update () inline private
Definition at line 106 of file LayerInteraction.cs.
    {
        if (mode == Mode.Map)
        {
            _ = ELayer.screen.tileSelector;
            MeshPass obj = ((point.HasBlock || point.cell.liquidLv > 0) ? ELayer.screen.guide.passGuideBlock : ELayer.screen.guide.passGuideFloor);
            int num = 0;
            Vector3 vector = point.Position();
            obj.Add(vector.x, vector.y, vector.z, num, 0.3f);
        }
    }
References MeshPass.Add(), BaseGameScreen.guide, mode, ScreenGuide.passGuideBlock, ScreenGuide.passGuideFloor, point, Point.Position(), ELayer.screen, and BaseGameScreen.tileSelector.
Member Data Documentation
first
bool LayerInteraction.first = true private
Definition at line 89 of file LayerInteraction.cs.
Referenced by OnInit().
Instance
LayerInteraction LayerInteraction.Instance static
Definition at line 79 of file LayerInteraction.cs.
Referenced by OnInit(), and Show().
menu
InteractionMenu LayerInteraction.menu
Definition at line 91 of file LayerInteraction.cs.
Referenced by Show(), and ShowPage().
mode
Mode LayerInteraction.mode
Definition at line 83 of file LayerInteraction.cs.
Referenced by Show(), and Update().
pages
List<Page> LayerInteraction.pages = new List<Page>()
Definition at line 87 of file LayerInteraction.cs.
Referenced by Show(), and ShowPage().
point
Point LayerInteraction.point
Definition at line 85 of file LayerInteraction.cs.
Referenced by Show(), and Update().
Target
IInspect LayerInteraction.Target static
Definition at line 81 of file LayerInteraction.cs.
Referenced by OnKill(), Show(), ShowPage(), and TryShow().
windowChara
WindowChara LayerInteraction.windowChara
Definition at line 93 of file LayerInteraction.cs.
Referenced by ShowPage().
The documentation for this class was generated from the following file:
Elin/LayerInteraction.cs