Elin Decompiled Documentation: TaskPoint Class Reference
TaskPoint Class Reference
Public Member Functions
override bool CanManualCancel ()
override bool CanPerform ()
override bool _CanPerformTask (Chara chara, int radius)
override IEnumerable< Status > Run ()
void OnInspect ()
void WriteNote (UINote n, Action< UINote > onWriteNote=null, IInspect.NoteMode mode=IInspect.NoteMode.Default, Recipe recipe=null)
Public Member Functions inherited from Task
virtual HitResult GetHitResult ()
override void OnSuccess ()
void TryLayer (int min=30)
Status Destroy ()
virtual void OnDestroy ()
override Status Cancel ()
override void OnReset ()
override bool CanProgress ()
bool CanPerformTask (Chara chara, int radius)
virtual bool _CanPerformTask (Chara chara, int radius)
virtual void OnAdd ()
void ToggleSuspend ()
Public Member Functions inherited from AIAct
override string ToString ()
override MultiSprite GetStateIcon ()
virtual Point GetDestination ()
AIProgress GetProgress ()
string GetCurrentActionText ()
override bool IsToolValid ()
virtual void OnStart ()
void SetOwner (Chara c)
virtual void OnSetOwner ()
void SetChild (AIAct seq, Func< Status > _onChildFail=null)
void Start ()
override bool Perform ()
Status Restart ()
Status Success (Action action=null)
virtual void OnSuccess ()
bool TryCancel (Card c)
virtual Status Cancel ()
virtual void OnCancel ()
virtual void OnCancelOrSuccess ()
virtual bool CanManualCancel ()
Status KeepRunning ()
void Reset ()
virtual void OnReset ()
Status Tick ()
virtual IEnumerable< Status > Run ()
Status TickChild ()
Status Do (AIAct _seq, Func< Status > _onChildFail=null)
Status DoGotoInteraction (Point pos, Func< Status > _onChildFail=null)
Status DoGoto (Point pos, int dist=0, bool ignoreConnection=false, Func< Status > _onChildFail=null)
Status DoGoto (Card card, Func< Status > _onChildFail=null)
Status DoGoto (Card card, int dist, Func< Status > _onChildFail=null)
Status DoGotoSpot (Card card, Func< Status > _onChildFail=null)
Status DoGoto< T > (Func< Status > _onChildFail=null)
Status DoGotoSpot< T > (Func< Status > _onChildFail=null, bool ignoreAccessType=false)
Status DoGrab (Card card, int num=-1, bool pickHeld=false, Func< Status > _onChildFail=null)
Status DoGrab< T > ()
Status DoProgress ()
Status DoIdle (int repeat=3)
Status DoWait (int count=1)
virtual AIProgress CreateProgress ()
virtual void OnCreateProgress (Progress_Custom p)
virtual bool CanProgress ()
virtual void OnBeforeProgress ()
virtual void OnProgress ()
virtual void OnProgressComplete ()
void SimulateZone (int days)
virtual void OnSimulateZone (int days)
virtual void OnSimulatePosition ()
Public Member Functions inherited from Act
virtual CursorInfo GetCursorIcon (Card c)
virtual MultiSprite GetStateIcon ()
override Sprite GetSprite ()
virtual bool ShowMouseHint (Card c)
virtual bool IsValidTC (Card c)
virtual string GetHintText (string str="")
virtual string GetText (string str="")
virtual string GetTextSmall (Card c)
virtual Color GetActPlanColor ()
virtual bool Perform ()
virtual bool CanPerform ()
bool Perform (Chara _cc, Card _tc=null, Point _tp=null)
bool CanPerform (Chara _cc, Card _tc=null, Point _tp=null)
virtual bool IsToolValid ()
new void SetImage (Image image)
virtual void OnMarkMapHighlights ()
virtual bool ShouldMapHighlight (Point p)
virtual CursorInfo GetCursorIcon (Card c)
virtual MultiSprite GetStateIcon ()
override Sprite GetSprite ()
virtual bool ShowMouseHint (Card c)
virtual bool IsValidTC (Card c)
virtual string GetHintText (string str="")
virtual string GetText (string str="")
virtual string GetTextSmall (Card c)
virtual Color GetActPlanColor ()
virtual bool Perform ()
virtual bool CanPerform ()
bool Perform (Chara _cc, Card _tc=null, Point _tp=null)
bool CanPerform (Chara _cc, Card _tc=null, Point _tp=null)
virtual bool IsToolValid ()
new void SetImage (Image image)
virtual void OnMarkMapHighlights ()
virtual bool ShouldMapHighlight (Point p)
Public Member Functions inherited from Element
virtual SourceElement.Row GetSource ()
virtual int GetSourcePotential (int v)
virtual Sprite GetSprite ()
int GetMaterialSourceValue (Thing t, int v)
virtual int GetSourceValue (int v, int lv, SourceValueType type)
virtual Sprite GetIcon (string suffix="")
int SortVal (bool charaSheet=false)
virtual bool CanLink (ElementContainer owner)
bool HasTag (string tag)
void SetImage (Image i)
virtual string GetDetail ()
bool IsFactionElement (Chara c)
Element GetParent (Card c)
void WriteNote (UINote n, ElementContainer owner=null, Action< UINote > onWriteNote=null)
void WriteNoteWithRef (UINote n, ElementContainer owner, Action< UINote > onWriteNote, Element refEle)
void _WriteNote (UINote n, Chara c, Act act)
void _WriteNote (UINote n, ElementContainer owner, Action< UINote > onWriteNote, bool isRef, bool addHeader=true)
virtual void OnWriteNote (UINote n, ElementContainer owner)
virtual void OnChangeValue ()
void CheckLevelBonus (ElementContainer owner, UINote n=null)
int GetSortVal (UIList.SortMode m)
virtual Act.Cost GetCost (Chara c)
virtual int GetPower (Card c)
virtual void SetTextValue (UIText text)
virtual SourceElement.Row GetSource ()
virtual int GetSourcePotential (int v)
virtual Sprite GetSprite ()
int GetMaterialSourceValue (Thing t, int v)
virtual int GetSourceValue (int v, int lv, SourceValueType type)
virtual Sprite GetIcon (string suffix="")
int SortVal (bool charaSheet=false)
virtual bool CanLink (ElementContainer owner)
bool HasTag (string tag)
void SetImage (Image i)
virtual string GetDetail ()
bool IsFactionElement (Chara c)
Element GetParent (Card c)
void WriteNote (UINote n, ElementContainer owner=null, Action< UINote > onWriteNote=null)
void WriteNoteWithRef (UINote n, ElementContainer owner, Action< UINote > onWriteNote, Element refEle)
void _WriteNote (UINote n, Chara c, Act act)
void _WriteNote (UINote n, ElementContainer owner, Action< UINote > onWriteNote, bool isRef, bool addHeader=true)
virtual void OnWriteNote (UINote n, ElementContainer owner)
virtual void OnChangeValue ()
void CheckLevelBonus (ElementContainer owner, UINote n=null)
int GetSortVal (UIList.SortMode m)
virtual Act.Cost GetCost (Chara c)
virtual int GetPower (Card c)
virtual void SetTextValue (UIText text)
void WriteNote (UINote n, Action< UINote > onWriteNote=null, NoteMode mode=NoteMode.Default, Recipe recipe=null)
void OnInspect ()
Public Attributes
Point pos = new Point()
bool isRepeated
Public Attributes inherited from Task
TaskList taskList
bool isDestroyed
int nextTry
bool suspended
Public Attributes inherited from AIAct
new Chara owner
Status status
IEnumerator< Status > Enumerator
AIAct child
AIAct parent
byte restartCount
Func< Status > onChildFail
Func< bool > isFail
Public Attributes inherited from Element
SourceElement.Row _source
int id
int vBase
int vExp
int vPotential
int vTempPotential
int vLink
int vSource
int vSourcePotential
ElementContainer owner
Properties
override bool HasProgress [get]
virtual int destDist [get]
virtual bool destIgnoreConnection [get]
virtual bool isBlock [get]
virtual bool Loop [get]
bool CanInspect [get]
string InspectName [get]
Point InspectPoint [get]
Vector3 InspectPosition [get]
Properties inherited from Task
override TargetType TargetType [get]
Properties inherited from AIAct
virtual bool IsRunning [get]
bool IsChildRunning [get]
bool IsMoveAI [get]
virtual int MaxRestart [get]
virtual new string Name [get]
virtual MultiSprite stateIcon [get]
virtual Sprite actionIcon [get]
virtual bool IsNoGoal [get]
virtual bool IsAutoTurn [get]
virtual bool IsIdle [get]
virtual bool PushChara [get]
virtual int MaxProgress [get]
virtual bool ShowProgress [get]
virtual bool UseTurbo [get]
virtual int CurrentProgress [get]
virtual bool ShowCursor [get]
virtual bool CancelWhenDamaged [get]
virtual bool CancelWhenMoved [get]
virtual bool InformCancel [get]
virtual Thing RenderThing [get]
AIAct Current [get]
override bool IsAct [get]
override bool ShowPotential [get]
override bool UsePotential [get]
override bool ShowRelativeAttribute [get]
virtual bool HasProgress [get]
Properties inherited from Act
override bool ShowPotential [get]
override bool UsePotential [get]
override bool ShowRelativeAttribute [get]
virtual CursorInfo CursorIcon [get]
virtual string ID [get]
virtual bool IsAct [get]
virtual bool WillEndTurn [get]
virtual bool CloseLayers [get]
virtual int LeftHand [get]
virtual int RightHand [get]
virtual int ElementPowerMod [get]
virtual bool ShowMapHighlight [get]
virtual bool ShowMapHighlightBlock [get]
virtual bool PickHeldOnStart [get]
virtual bool DropHeldOnStart [get]
virtual bool CanPressRepeat [get]
virtual bool CanAutofire [get]
virtual bool ResetAxis [get]
virtual bool RequireTool [get]
virtual bool IsHostileAct [get]
virtual bool HideRightInfo [get]
virtual bool HaveLongPressAction [get]
virtual float Radius [get]
virtual int PerformDistance [get]
virtual int MaxRadius [get]
virtual TargetType TargetType [get]
virtual bool LocalAct [get]
virtual bool CanRapidFire [get]
virtual float RapidDelay [get]
virtual bool ShowAuto [get]
virtual bool IsCrime [get]
Properties inherited from Element
SourceElement.Row source [get]
virtual int DisplayValue [get]
virtual int MinValue [get]
int Value [get]
int ValueWithoutLink [get]
virtual int MinPotential [get]
int Potential [get]
virtual bool CanGainExp [get]
bool IsFlag [get]
virtual string Name [get]
virtual string FullName [get]
virtual int ExpToNext [get]
virtual bool UseExpMod [get]
virtual int CostTrain [get]
virtual int CostLearn [get]
virtual bool ShowXP [get]
virtual bool ShowMsgOnValueChanged [get]
virtual bool ShowValue [get]
virtual bool ShowPotential [get]
virtual bool UsePotential [get]
virtual bool PotentialAsStock [get]
virtual bool ShowRelativeAttribute [get]
virtual bool ShowBonuses [get]
virtual string ShortName [get]
bool IsGlobalElement [get]
bool IsFactionWideElement [get]
bool IsPartyWideElement [get]
virtual bool ShowEncNumber [get]
bool IsTrait [get]
bool IsFoodTrait [get]
bool IsFoodTraitMain [get]
bool IsMainAttribute [get]
Act act [get]
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Properties inherited from IInspect
bool CanInspect [get]
string InspectName [get]
Point InspectPoint [get]
Vector3 InspectPosition [get]
Static Private Attributes
static Point tempPos = new Point()
Additional Inherited Members
Public Types inherited from AIAct
enum Status { Running , Fail , Success }
Public Types inherited from Act
enum CostType {
None , MP , SP , None ,
MP , SP
}
enum CostType {
None , MP , SP , None ,
MP , SP
}
Public Types inherited from IInspect
enum NoteMode { Default , Recipe , Product , Info }
Static Public Member Functions inherited from Act
static void SetReference (Chara _cc, Card _tc=null, Point _tp=null)
static void SetTool (Thing t)
static void SetReference (Chara _cc, Card _tc=null, Point _tp=null)
static void SetTool (Thing t)
Static Public Member Functions inherited from Element
static string GetName (string alias)
static SourceElement.Row Get (int id)
static Dictionary< int, int > GetElementMap (int[] list)
static Dictionary< int, int > GetElementMap (int[] list, Dictionary< int, int > map)
static SourceElement.Row GetRandomElement (int lv=1)
static Element Create (int id, int v=0)
static Element Create (string id, int v=1)
static int GetId (string alias)
static int GetResistLv (int v)
static int GetResistDamage (int dmg, int v)
static string GetName (string alias)
static SourceElement.Row Get (int id)
static Dictionary< int, int > GetElementMap (int[] list)
static Dictionary< int, int > GetElementMap (int[] list, Dictionary< int, int > map)
static SourceElement.Row GetRandomElement (int lv=1)
static Element Create (int id, int v=0)
static Element Create (string id, int v=1)
static int GetId (string alias)
static int GetResistLv (int v)
static int GetResistDamage (int dmg, int v)
Static Public Member Functions inherited from EClass
static int rnd (int a)
static int curve (int a, int start, int step, int rate=75)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Static Public Attributes inherited from Act
static Chara CC
static Card TC
static Point TP = new Point()
static Thing TOOL
static int powerMod = 100
static bool forcePt
Static Public Attributes inherited from Element
const int Div = 5
static Element Void = new Element()
static int[] List_MainAttributes
static int[] List_MainAttributesMajor
static int[] List_Body
static int[] List_Mind
static List< SourceElement.Row > ListElements = new List<SourceElement.Row>()
static List< SourceElement.Row > ListAttackElements = new List<SourceElement.Row>()
Static Public Attributes inherited from EClass
static Core core
Static Package Functions inherited from Element
static string< _WriteNote > g__Calc (ref Element.<>c__DisplayClass103_0 A_0)
Detailed Description
Definition at line 6 of file TaskPoint.cs.
Member Function Documentation
_CanPerformTask()
override bool TaskPoint._CanPerformTask (Chara chara, int radius) inline virtual
Reimplemented from Task.
Definition at line 59 of file TaskPoint.cs.
    {
        if (radius != -1 && chara.pos.Distance(pos) > radius)
        {
            return false;
        }
        if (pos.cell.isSurrounded)
        {
            return false;
        }
        return true;
    }
References Point.cell, Point.Distance(), Cell.isSurrounded, Card.pos, and pos.
CanManualCancel()
override bool TaskPoint.CanManualCancel () inline virtual
Reimplemented from AIAct.
Reimplemented in TaskPourWater.
Definition at line 33 of file TaskPoint.cs.
    {
        if (base.IsChildRunning)
        {
            return child is AI_Goto;
        }
        return false;
    }
References AIAct.child.
CanPerform()
override bool TaskPoint.CanPerform () inline virtual
Reimplemented from Act.
Definition at line 42 of file TaskPoint.cs.
    {
        if (owner == null)
        {
            owner = Act.CC;
        }
        tempPos.Set(pos);
        pos.Set(Act.TP);
        HitResult hitResult = GetHitResult();
        pos.Set(tempPos);
        if (hitResult != HitResult.Valid)
        {
            return hitResult == HitResult.Warning;
        }
        return true;
    }
References Act.CC, Task.GetHitResult(), AIAct.owner, pos, Point.Set(), tempPos, and Act.TP.
Referenced by HotItemHeld.CanChangeHeightByWheel(), HotItemHeld.CanRotate(), HotItemHeld.OnRenderTile(), and Run().
OnInspect()
void TaskPoint.OnInspect () inline
Implements IInspect.
Definition at line 124 of file TaskPoint.cs.
    {
    }
Run()
override IEnumerable< Status > TaskPoint.Run () inline virtual
Reimplemented from AIAct.
Definition at line 72 of file TaskPoint.cs.
    {
        if (owner.IsPC && AM_Adv.actCount > 0)
        {
            while (EInput.rightMouse.pressing)
            {
                pos.Set(Act.TP.Set(ActionMode.Adv.mouseTarget.pos));
                if (CanPerform())
                {
                    break;
                }
                yield return Status.Running;
            }
            pos.Set(Act.TP.Set(ActionMode.Adv.mouseTarget.pos));
            if (!CanPerform() || !EInput.rightMouse.pressing || (HasProgress && !CanProgress()))
            {
                yield return Destroy();
            }
        }
        do
        {
            if (owner.pos.Distance(pos) > destDist)
            {
                yield return DoGoto(pos, destDist, destIgnoreConnection);
                if (owner.pos.Distance(pos) > destDist)
                {
                    Debug.Log(AM_Adv.actCount + "/" + pos?.ToString() + "/" + owner.pos);
                    Debug.Log(destDist + "/" + owner.pos.Distance(pos));
                    yield return Destroy();
                }
            }
            if (!CanProgress())
            {
                yield return Destroy();
            }
            if (HasProgress)
            {
                yield return DoProgress();
            }
            else
            {
                yield return KeepRunning();
                OnProgressComplete();
            }
            if (owner != null && owner.IsPC)
            {
                AM_Adv.actCount++;
            }
        }
        while (Loop);
    }
References AM_Adv.actCount, ActionMode.Adv, CanPerform(), Task.CanProgress(), destDist, destIgnoreConnection, Task.Destroy(), Point.Distance(), AIAct.DoGoto(), AIAct.DoProgress(), HasProgress, Chara.IsPC, AIAct.KeepRunning(), Loop, AM_Adv.mouseTarget, AIAct.OnProgressComplete(), AIAct.owner, Card.pos, PointTarget.pos, pos, Point.Set(), Point.ToString(), and Act.TP.
WriteNote()
void TaskPoint.WriteNote (UINote n, Action< UINote > onWriteNote = null, IInspect::NoteMode mode = IInspect::NoteMode::Default, Recipe recipe = null) inline
Implements IInspect.
Definition at line 128 of file TaskPoint.cs.
    {
        n.Clear();
        n.AddHeaderCard(Name);
        n.Build();
    }
References AIAct.Name.
Member Data Documentation
isRepeated
bool TaskPoint.isRepeated
Definition at line 13 of file TaskPoint.cs.
Referenced by AM_Adv._OnUpdateInput().
pos
Point TaskPoint.pos = new Point()
Definition at line 11 of file TaskPoint.cs.
Referenced by _CanPerformTask(), Recipe.Build(), RecipeCard.Build(), TaskMine.CanMine(), CanPerform(), TaskBaseBuild.CanPlaceCard(), TaskDrawWater.CanProgress(), TaskHarvest.CanProgress(), TaskPlow.CanProgress(), TaskPourWater.CanProgress(), TaskBuild.CanRotateBlock(), TaskBuild.DrawMarker(), TaskMine.DrawMarker(), AM_Dig.ForcedInstaComplete(), AM_Mine.ForcedInstaComplete(), BaseTaskHarvest.GetBestTool(), TaskBuild.GetHitResult(), TaskCut.GetHitResult(), TaskDig.GetHitResult(), TaskDrawWater.GetHitResult(), TaskHarvest.GetHitResult(), TaskMine.GetHitResult(), TaskMoveInstalled.GetHitResult(), TaskPlow.GetHitResult(), TaskPourWater.GetHitResult(), BaseTaskHarvest.GetTextSmall(), TaskDig.GetTextSmall(), TaskMine.GetTextSmall(), TaskDig.GetTreasureMap(), TaskHarvest.HarvestThing(), TaskDig.OnCreateProgress(), TaskDrawWater.OnCreateProgress(), TaskHarvest.OnCreateProgress(), TaskMine.OnCreateProgress(), TaskPlow.OnCreateProgress(), TaskPourWater.OnCreateProgress(), TaskBuild.OnDestroy(), TaskCut.OnProgress(), AI_Water.OnProgressComplete(), TaskBuild.OnProgressComplete(), TaskCut.OnProgressComplete(), TaskDig.OnProgressComplete(), TaskMine.OnProgressComplete(), TaskMoveInstalled.OnProgressComplete(), InspectGroupObj.OnSetActions(), TaskCut.OnStart(), TaskDesignation.PointHasOtherDesignation(), AI_HaulResource.Run(), TaskMoveInstalled.Run(), Run(), TCOrbitTask.SetOwner(), and TaskHarvest.TryGetAct().
tempPos
Point TaskPoint.tempPos = new Point() static private
Definition at line 8 of file TaskPoint.cs.
Referenced by CanPerform().
Property Documentation
CanInspect
bool TaskPoint.CanInspect get
Implements IInspect.
Definition at line 25 of file TaskPoint.cs.
destDist
virtual int TaskPoint.destDist get
Definition at line 17 of file TaskPoint.cs.
Referenced by AI_HaulResource.Run(), and Run().
destIgnoreConnection
virtual bool TaskPoint.destIgnoreConnection get
Definition at line 19 of file TaskPoint.cs.
Referenced by AI_HaulResource.Run(), and Run().
HasProgress
override bool TaskPoint.HasProgress get
Definition at line 15 of file TaskPoint.cs.
Referenced by Run().
InspectName
string TaskPoint.InspectName get
Implements IInspect.
Definition at line 27 of file TaskPoint.cs.
InspectPoint
Point TaskPoint.InspectPoint get
Implements IInspect.
Definition at line 29 of file TaskPoint.cs.
InspectPosition
Vector3 TaskPoint.InspectPosition get
Implements IInspect.
Definition at line 31 of file TaskPoint.cs.
isBlock
virtual bool TaskPoint.isBlock get
Definition at line 21 of file TaskPoint.cs.
Referenced by TaskDesignation.DrawMarker().
Loop
virtual bool TaskPoint.Loop get
Definition at line 23 of file TaskPoint.cs.
Referenced by Run().
The documentation for this class was generated from the following file:
Elin/TaskPoint.cs