Elin Decompiled Documentation: LayerHire Class Reference
LayerHire Class Reference
Public Member Functions
override void OnAfterInit ()
void Refresh ()
override void OnKill ()
Public Member Functions inherited from ELayer
override void OnBeforeAddLayer ()
void InitInspector ()
sealed override void Init ()
override void OnAfterAddLayer ()
void TryShowHelp ()
void AddLayerToUI (string id)
void TryShowHint (string _langHint=null)
void TalkHomeMemeber (string id)
void TalkMaid (string id)
override void OnRightClick ()
Public Attributes
UIList list
Additional Inherited Members
Static Public Member Functions inherited from ELayer
static int rnd (int a)
Protected Member Functions inherited from ELayer
sealed override void _Close ()
sealed override void Kill ()
Properties inherited from ELayer
static Core core [get]
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static FactionBranch Branch [get]
static Faction Home [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static CoreConfig config [get]
static GameSetting setting [get]
static ColorProfile Colors [get]
static SourceManager sources [get]
static World world [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
bool IsFloat [get]
virtual string IdHelp [get]
Detailed Description
Definition at line 1 of file LayerHire.cs.
Member Function Documentation
OnAfterInit()
override void LayerHire.OnAfterInit () inline
Definition at line 5 of file LayerHire.cs.
    {
        Refresh();
    }
References Refresh().
OnKill()
override void LayerHire.OnKill () inline
Definition at line 50 of file LayerHire.cs.
    {
        ELayer.Branch.ClearNewRecruits();
    }
References ELayer.Branch, and FactionBranch.ClearNewRecruits().
Refresh()
void LayerHire.Refresh () inline
Definition at line 10 of file LayerHire.cs.
    {
        list.Clear();
        list.callbacks = new UIList.Callback<HireInfo, ButtonChara>
        {
            onClick = delegate
            {
            },
            onInstantiate = delegate(HireInfo a, ButtonChara b)
            {
                Chara chara = a.chara;
                b.SetChara(chara, ButtonChara.Mode.Hire);
                CalcGold.Hire(chara);
                b.item.text2.text = a.Days.ToString() ?? "";
                b.item.button1.onClick.AddListener(delegate
                {
                    a.isNew = false;
                    Refresh();
                    ELayer.ui.AddLayerDontCloseOthers<LayerChara>().SetChara(a.chara);
                });
                b.item.button2.onClick.AddListener(delegate
                {
                    a.isNew = false;
                    a.chara.ShowDialog("_chara", "4-1").onKill.AddListener(Refresh);
                });
                b.item.image1.SetActive(a.isNew);
            },
            onRefresh = null
        };
        foreach (HireInfo item in ELayer.Home.listReserve)
        {
            if (!item.chara.IsHomeMember() && !item.chara.currentZone.IsPlayerFaction)
            {
                list.Add(item);
            }
        }
        list.Refresh();
        this.RebuildLayout(recursive: true);
    }
References HireInfo.chara, HireInfo.Days, CalcGold.Hire(), ELayer.Home, HireInfo.isNew, ButtonChara.item, item, list, Faction.listReserve, Refresh(), ButtonChara.SetChara(), Chara.ShowDialog(), and ELayer.ui.
Referenced by OnAfterInit(), and Refresh().
Member Data Documentation
list
UIList LayerHire.list
Definition at line 3 of file LayerHire.cs.
Referenced by Refresh().
The documentation for this class was generated from the following file:
Elin/LayerHire.cs