Elin Decompiled Documentation: DamageTextRenderer Class Reference
DamageTextRenderer Class Reference
Public Member Functions
void Add (Card target, Card attacker, int dmg, Element e=null)
void Flush ()
Public Attributes
Card lastTarget
Card lastAttacker
Element lastElement = Element.Void
int sum
int num
Additional Inherited Members
Static Public Member Functions inherited from EClass
static int rndSeed (int a, int seed)
static int rnd (long a)
static int rnd (int a)
static int curve (int _a, int start, int step, int rate=75)
static int sqrt (int a)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Static Public Attributes inherited from EClass
static Core core
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Detailed Description
Definition at line 3 of file DamageTextRenderer.cs.
Member Function Documentation
Add()
void DamageTextRenderer.Add (Card target, Card attacker, int dmg, Element e = null) inline
Definition at line 15 of file DamageTextRenderer.cs.
    {
        if (e == null)
        {
            e = Element.Void;
        }
        if (lastTarget != target || lastAttacker != attacker || lastElement.id != e.id)
        {
            Flush();
            lastTarget = target;
            lastAttacker = attacker;
            lastElement = e;
        }
        sum += dmg;
        num++;
        if (!EClass.core.config.test.stackNumbers)
        {
            Flush();
        }
    }
References Core.config, EClass.core, Flush(), Element.id, lastAttacker, lastElement, lastTarget, num, CoreConfig.Test.stackNumbers, sum, CoreConfig.test, and Element.Void.
Referenced by Card.DamageHP().
Flush()
void DamageTextRenderer.Flush () inline
Definition at line 36 of file DamageTextRenderer.cs.
    {
        if (this.num != 0)
        {
            Card card = lastTarget;
            Card card2 = lastAttacker;
            Element element = lastElement;
            Popper popper = EClass.scene.popper.Pop(card.renderer.PositionCenter(), "DamageNum");
            Color c = EClass.Colors.textColors.damage;
            if (card2 != null)
            {
                c = (card2.IsPC ? EClass.Colors.textColors.damagePC : (card2.IsPCFaction ? EClass.Colors.textColors.damagePCParty : EClass.Colors.textColors.damage));
            }
            if (element != Element.Void)
            {
                c = EClass.Colors.elementColors.TryGetValue(element.source.alias);
                float num = (c.r + c.g + c.b) / 3f;
                num = ((num > 0.5f) ? 0f : (0.6f - num));
                c = new Color(c.r + num, c.g + num, c.b + num, 1f);
            }
            popper.SetText((this.num == 1) ? (sum.ToFormat() ?? "") : (sum.ToFormat() + "<size=18> (x" + this.num + ")</size>"), c);
            sum = (this.num = 0);
        }
    }
References card, Color, EClass.Colors, ColorProfile.TextColors.damage, ColorProfile.elementColors, lastAttacker, lastElement, lastTarget, num, PopperManager.Pop(), Scene.popper, EClass.scene, Popper.SetText(), Element.source, sum, ColorProfile.textColors, UDictionary< TKey, TValue >.TryGetValue(), and Element.Void.
Referenced by Add(), and Scene.OnUpdate().
Member Data Documentation
lastAttacker
Card DamageTextRenderer.lastAttacker
Definition at line 7 of file DamageTextRenderer.cs.
Referenced by Add(), and Flush().
lastElement
Element DamageTextRenderer.lastElement = Element.Void
Definition at line 9 of file DamageTextRenderer.cs.
Referenced by Add(), and Flush().
lastTarget
Card DamageTextRenderer.lastTarget
Definition at line 5 of file DamageTextRenderer.cs.
Referenced by Add(), and Flush().
num
int DamageTextRenderer.num
Definition at line 13 of file DamageTextRenderer.cs.
Referenced by Add(), and Flush().
sum
int DamageTextRenderer.sum
Definition at line 11 of file DamageTextRenderer.cs.
Referenced by Add(), and Flush().
The documentation for this class was generated from the following file:
Elin/DamageTextRenderer.cs