Elin Decompiled Documentation: MapGenRegion Class Reference
MapGenRegion Class Reference
Protected Member Functions
override bool OnGenerateTerrain ()
Protected Member Functions inherited from BaseMapGen
virtual void GenerateTerrain ()
virtual bool OnGenerateTerrain ()
Properties
static MapGenRegion Instance [get]
Properties inherited from BaseMapGen
bool extraBiome [get]
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Static Private Attributes
static MapGenRegion _Instance
Additional Inherited Members
Public Member Functions inherited from BaseMapGen
void SetSize (int size, int _poiSize)
void Generate (ZoneBlueprint _bp)
Public Member Functions inherited from GenBounds
void SetFloor (BiomeProfile.Tile t, int x, int z)
void SetBlock (BiomeProfile.Tile t, int x, int z, int idMat=-1)
void SetFloor (int x, int z, int idMat, int idFloor, int direction=0)
void SetBlock (int x, int z, int idMat, int idBlock, int direction=0)
bool IsEmpty ()
List< Point > ListEmptyPoint ()
GenBounds GetBounds (int w, int h, bool ignoreBlock)
GenBounds GetBounds (Map map, Zone zone, int x, int y, int width, int height, int dw, int dh, bool ignoreBlock)
PartialMap TryAddMapPiece (MapPiece.Type type=MapPiece.Type.Any, float ruin=-1f, string tags=null, Action< PartialMap, GenBounds > onCreate=null)
Static Public Member Functions inherited from GenBounds
static GenBounds Create (Zone z)
Static Public Member Functions inherited from EClass
static int rndSeed (int a, int seed)
static int rnd (long a)
static int rnd (int a)
static int curve (int a, int start, int step, int rate=75)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Public Attributes inherited from BaseMapGen
NoiseLayer layerHeight
NoiseLayer layerRiver
NoiseLayer layerStratum
NoiseLayer layerBiome
BiomeProfile[] biomeProfiles
BiomeProfile biomeShore
BiomeProfile biomeSand
BiomeProfile biomeWater
Crawler[] crawlers
ZoneBlueprint bp
ZoneProfile zp
int blockHeight
int seed
int lastSize
int OX
int OZ
BiomeProfile[,] biomes
bool[,] subBiomes
MapGenVariation variation
MapHeight hSetting
Public Attributes inherited from GenBounds
Map map
Zone zone
int Size
int x
int y
int width
int height
int marginPartial
Func< Cell, bool > FuncCheckEmpty
Static Public Attributes inherited from BaseMapGen
static string err
Static Public Attributes inherited from EClass
static Core core
Protected Attributes inherited from BaseMapGen
bool skipWater
float[,] heights1
float[,] heights2
float[,] heights3
float[,] waters
float[,] heights3d
float waterCount
Detailed Description
Definition at line 4 of file MapGenRegion.cs.
Member Function Documentation
OnGenerateTerrain()
override bool MapGenRegion.OnGenerateTerrain () inline protected virtual
Reimplemented from BaseMapGen.
Definition at line 10 of file MapGenRegion.cs.
    {
        EClass.scene.elomapActor.Initialize(zone.Region.elomap);
        EloMap elomap = EClass.scene.elomapActor.elomap;
        SetSize(Mathf.Max(elomap.w, elomap.h), 10);
        map.CreateNew(Size);
        for (int i = 0; i < elomap.h; i++)
        {
            for (int j = 0; j < elomap.w; j++)
            {
                _ = elomap.cells[j, i];
                int gridX = elomap.minX + j;
                int gridY = elomap.minY + i;
                map.cells[j, i].isSeen = true;
                SetFloor(j, i, 66, 43);
                foreach (STETilemap tilemap in elomap.group.Tilemaps)
                {
                    if (tilemap == elomap.fogmap || tilemap == elomap.cloudmap)
                    {
                        continue;
                    }
                    int tileIdFromTileData = Tileset.GetTileIdFromTileData(tilemap.GetTileData(gridX, gridY));
                    SourceGlobalTile.Row row = EClass.sources.globalTiles.tileAlias.TryGetValue(tileIdFromTileData);
                    if (row != null)
                    {
                        map.cells[j, i].impassable = row.attribs[0] == 0;
                        if (row.floor != 0)
{
                            SetFloor(j, i, EClass.sources.floors.rows[row.floor].DefaultMaterial.id, row.floor);
                        }
                    }
                }
                if (Tileset.GetTileIdFromTileData(elomap.cloudmap.GetTileData(gridX, gridY)) < 1000)
                {
                    map.cells[j, i].impassable = true;
                }
            }
        }
        map.poiMap.Reset();
        map.SetZone(zone);
        map.config.idSceneProfile = "region";
        map.RefreshAllTiles();
        return true;
    }
References SourceGlobalTile.Row.attribs, EloMap.cells, Map.cells, EloMap.cloudmap, Map.CreateNew(), EloMapActor.elomap, Region.elomap, Scene.elomapActor, SourceGlobalTile.Row.floor, SourceManager.floors, EloMap.fogmap, SourceManager.globalTiles, EloMap.group, EloMap.h, Cell.impassable, EloMapActor.Initialize(), Cell.isSeen, GenBounds.map, Map.poiMap, Map.RefreshAllTiles(), Zone.Region, POIMap.Reset(), EClass.scene, GenBounds.SetFloor(), BaseMapGen.SetSize(), Map.SetZone(), GenBounds.Size, EClass.sources, SourceGlobalTile.tileAlias, EloMap.w, and GenBounds.zone.
Member Data Documentation
_Instance
MapGenRegion MapGenRegion._Instance static private
Definition at line 6 of file MapGenRegion.cs.
Property Documentation
Instance
MapGenRegion MapGenRegion.Instance static get
Definition at line 8 of file MapGenRegion.cs.
Referenced by ZoneBlueprint.GenerateMap().
The documentation for this class was generated from the following file:
Elin/MapGenRegion.cs