Elin Decompiled Documentation: InvOwner.Transaction Class Reference
InvOwner.Transaction Class Reference
Public Member Functions
Transaction (DragItemCard.DragInfo from, UIInventory destUIInv, int num=1)
Transaction (DragItemCard.DragInfo from, DragItemCard.DragInfo to, int num=1)
Transaction (ButtonGrid button, int num=1, InvOwner owner=null)
bool Process (bool startTransaction=false)
int GetPrice ()
bool IsValid ()
string GetTextDetail ()
Public Attributes
Thing thing
ButtonGrid button
int num = 1
DragItemCard.DragInfo from
DragItemCard.DragInfo to
UIInventory destUIInv
InvOwner inv
Static Public Attributes
static ErrorMessage error = new ErrorMessage()
Properties
InvOwner destInv [get]
bool sell [get]
string IDCurrency [get]
CurrencyType currency [get]
bool FreeTrade [get]
Detailed Description
Definition at line 33 of file InvOwner.cs.
Constructor & Destructor Documentation
Transaction() [1/3]
InvOwner.Transaction.Transaction (DragItemCard::DragInfo from, UIInventory destUIInv, int num = 1) inline
Definition at line 107 of file InvOwner.cs.
        {
            this.from = from;
            button = from.button;
            thing = from.thing;
            this.num = num;
            inv = from.invOwner;
            this.destUIInv = destUIInv;
        }
References DragItemCard.button, InvOwner.Transaction.button, InvOwner.Transaction.destUIInv, InvOwner.Transaction.from, InvOwner.Transaction.inv, InvOwner.Transaction.num, and InvOwner.Transaction.thing.
Transaction() [2/3]
InvOwner.Transaction.Transaction (DragItemCard::DragInfo from, DragItemCard::DragInfo to, int num = 1) inline
Definition at line 117 of file InvOwner.cs.
        {
            this.from = from;
            this.to = to;
            button = from.button;
            thing = from.thing;
            this.num = num;
            inv = from.invOwner;
        }
References DragItemCard.button, InvOwner.Transaction.button, InvOwner.Transaction.from, InvOwner.Transaction.inv, InvOwner.Transaction.num, InvOwner.Transaction.thing, and InvOwner.Transaction.to.
Transaction() [3/3]
InvOwner.Transaction.Transaction (ButtonGrid button, int num = 1, InvOwner owner = null) inline
Definition at line 127 of file InvOwner.cs.
        {
            this.button = button;
            thing = button.card as Thing;
            this.num = num;
            inv = owner ?? button.invOwner;
        }
References InvOwner.Transaction.button, InvOwner.Transaction.inv, ButtonGrid.invOwner, InvOwner.Transaction.num, InvOwner.owner, and InvOwner.Transaction.thing.
Member Function Documentation
GetPrice()
int InvOwner.Transaction.GetPrice () inline
Definition at line 353 of file InvOwner.cs.
        {
            if (Trader != null)
            {
                return Trader.GetPrice(thing, currency, num, sell);
            }
            return 0;
        }
References InvOwner.Transaction.currency, InvOwner.GetPrice(), InvOwner.Transaction.num, InvOwner.Transaction.sell, InvOwner.Transaction.thing, and InvOwner.Trader.
Referenced by InvOwner.Transaction.IsValid(), InvOwner.OnWriteNote(), and InvOwner.Transaction.Process().
GetTextDetail()
string InvOwner.Transaction.GetTextDetail () inline
Definition at line 452 of file InvOwner.cs.
        {
            if (FreeTrade || (destInv.UseGuide && !destInv.ShouldShowGuide(thing)))
            {
                return "";
            }
            return destInv.GetTextDetail(thing, currency, num, sell);
        }
References InvOwner.Transaction.currency, InvOwner.Transaction.destInv, InvOwner.Transaction.FreeTrade, InvOwner.GetTextDetail(), InvOwner.Transaction.num, InvOwner.Transaction.sell, InvOwner.ShouldShowGuide(), InvOwner.Transaction.thing, and InvOwner.UseGuide.
Referenced by InvOwner.ListInteractions(), and InvOwner.OnDrag().
IsValid()
bool InvOwner.Transaction.IsValid () inline
Definition at line 362 of file InvOwner.cs.
        {
            if (destInv is InvOwnerToolbelt)
            {
                return false;
            }
            if (destInv.UseGuide && !destInv.ShouldShowGuide(thing))
            {
                return false;
            }
            if (destInv.Container.c_lockLv != 0)
            {
                return false;
            }
            if (thing.trait is TraitAbility && destInv.owner != EClass.pc)
            {
                return false;
            }
            if (destInv.CopyOnTransfer && to != null && to.button.index != LayerDragGrid.Instance.currentIndex)
            {
                return false;
            }
            if (!destInv.AllowTransfer)
            {
                return false;
            }
            if (thing.trait.IsContainer && destInv.Container != EClass.pc && !(destInv.Container.trait is TraitToolBelt) && thing.things.Count > 0 && (!destInv.CopyOnTransfer || !destInv.ShouldShowGuide(thing)) && (destInv != Trader || ShopTransaction.current == null || !ShopTransaction.current.HasBought(thing)))
            {
                error.Set("errorUnemptyContainer");
                return false;
            }
            if (HasTrader && Trader.currency != 0)
            {
                int price = GetPrice();
                if (sell)
                {
                    if (destInv.destInvY == 0 && destInv.Container.things.IsFull(thing))
                    {
                        return false;
                    }
                    if (thing.c_isImportant)
                    {
                        return false;
                    }
                    if (ShopTransaction.current == null || !ShopTransaction.current.CanSellBack(thing))
                    {
                        if (!Trader.AllowSell)
{
                            return false;
                        }
                        if (!FreeTrade && price == 0)
{
                            return false;
                        }
                    }
                }
                else if (!FreeTrade)
                {
                    if (Trader.UseHomeResource)
                    {
                        if (Trader.homeResource.value < price)
{
                            return false;
                        }
                    }
                    else if (EClass.pc.GetCurrency(IDCurrency) < price || price < 0 || (price == 0 && Trader.GetPrice(thing, currency, 1, sell) > 0))
                    {
                        return false;
                    }
                }
            }
            if (to != null)
            {
                if (to.invOwner.IsMagicChest && to.container.things.IsFull())
                {
                    return false;
                }
                if (to.thing != null && !to.thing.isDestroyed && !destInv.AllowHold(to.thing))
                {
                    return false;
                }
            }
            if (destInv.owner.IsPC && !destInv.Container.IsPC && destInv.IsWeightOver(thing))
            {
                error.Set("errorOverweight");
                return false;
            }
            return true;
        }
References InvOwner.AllowHold(), InvOwner.AllowSell, InvOwner.AllowTransfer, DragItemCard.button, Card.c_isImportant, Card.c_lockLv, ShopTransaction.CanSellBack(), InvOwner.Container, InvOwner.CopyOnTransfer, InvOwner.Transaction.currency, InvOwner.currency, ShopTransaction.current, LayerDragGrid.currentIndex, InvOwner.Transaction.destInv, InvOwner.destInvY, InvOwner.Transaction.error, InvOwner.Transaction.FreeTrade, Card.GetCurrency(), InvOwner.Transaction.GetPrice(), InvOwner.GetPrice(), ShopTransaction.HasBought(), InvOwner.HasTrader, InvOwner.homeResource, InvOwner.Transaction.IDCurrency, ButtonGrid.index, LayerDragGrid.Instance, Trait.IsContainer, ThingContainer.IsFull(), Card.IsPC, InvOwner.IsWeightOver(), InvOwner.owner, EClass.pc, InvOwner.Transaction.sell, InvOwner.ErrorMessage.Set(), InvOwner.ShouldShowGuide(), InvOwner.Transaction.thing, Card.things, InvOwner.Transaction.to, InvOwner.Trader, Card.trait, InvOwner.UseGuide, InvOwner.UseHomeResource, and BaseHomeResource.value.
Referenced by InvOwnerAlly.GetAutoUseLang(), InvOwner.ListInteractions(), InvOwner.OnDrag(), InvOwner.OnWriteNote(), and InvOwner.Transaction.Process().
Process()
bool InvOwner.Transaction.Process (bool startTransaction = false) inline
Definition at line 135 of file InvOwner.cs.
        {
            error = new ErrorMessage
            {
                card = this.thing
            };
            if (!IsValid())
            {
                SE.Play(error.sound);
                if (!error.lang.IsEmpty())
                {
                    Msg.Say(error.lang, error.card);
                }
                return false;
            }
            if (inv.IsFailByCurse(this.thing))
            {
                return false;
            }
            if (destInv.CopyOnTransfer)
            {
                int num = this.thing.Num;
                if (from != null && !(from.invOwner is InvOwnerAlly))
                {
                    this.thing = from.invOwner.PutBack(from);
                }
                else if (this.thing.parent != inv.Container)
                {
                    this.thing = inv.Container.AddThing(this.thing);
                }
                if (num != this.thing.Num)
                {
                    this.thing = this.thing.Split(num);
                    this.thing = EClass.pc.Pick(this.thing, msg: false, tryStack: false);
                }
                if (destInv.SingleTarget)
                {
                    this.thing = this.thing.Split(1);
                }
                if (to != null)
                {
                    to.button.SetCardGrid(this.thing, to.button.invOwner);
                }
                else
                {
                    int currentIndex = LayerDragGrid.Instance.currentIndex;
                    destInv.buttons[currentIndex].SetCardGrid(this.thing, destInv.buttons[currentIndex].invOwner);
                }
                destInv.OnProcess(this.thing);
                if (GetPrice() != 0)
                {
                    SE.Play("buy");
                    EClass.pc.ModCurrency(GetPrice() * -1, IDCurrency);
                }
                return true;
            }
            if (!startTransaction && to == null && (destInv.owner.IsPC ? EClass.pc : destInv.Container).things.IsFull(this.thing))
            {
                if (destInv.owner == EClass.pc)
                {
                    error.Set("backpack_full");
                }
                SE.Beep();
                return false;
            }
            Thing thing = this.thing.parent as Thing;
            if (thing != null && thing.isNPCProperty)
            {
                Msg.Say("steal_container", thing, this.thing);
                this.thing.isNPCProperty = false;
                EClass.player.ModKarma(-1);
                EClass.pc.pos.TryWitnessCrime(EClass.pc);
            }
            DragItemCard dragItemCard = new DragItemCard(button, startTransaction);
            Thing thing2 = this.thing.Split(this.num);
            Thing thing3 = thing2;
            bool flag = false;
            if (FreeTrade)
            {
                flag = true;
            }
            else
            {
                SE.Play(sell ? "sell" : "buy");
                int price = GetPrice();
                if (Trader.UseHomeResource)
                {
                    Trader.homeResource.Mod(sell ? price : (-price));
                }
                else
                {
                    if (sell)
                    {
                        EClass.pc.ModCurrency(price, IDCurrency);
                    }
                    else
                    {
                        EClass.pc.ModCurrency(-price, IDCurrency);
                    }
                    if (sell && !thing2.IsIdentified)
                    {
                        thing2.Identify(show: true, IDTSource.SuperiorIdentify);
                    }
                    else
                    {
                        ShopTransaction.current.Process(thing2, thing2.Num, sell);
                    }
                    Msg.Say(sell ? "sold" : "bought", thing2, Lang._currency(Mathf.Abs(price), IDCurrency));
                    if (thing2.id == "statue_weird" && sell)
                    {
                        EClass.pc.Say("statue_install");
                    }
                }
            }
            if (destInv.Container.isChara && !destInv.owner.IsPC && !destInv.owner.Chara.CanAcceptItem(thing2))
            {
                destInv.owner.Chara.Talk("tooHeavy");
                return false;
            }
            if (thing2.c_isImportant && !destInv.owner.IsPC && destInv.DenyImportant)
            {
                Msg.Say("markedImportant");
                return false;
            }
            if (inv.owner.isChara && inv.owner.Chara.IsPCFaction && !inv.owner.IsPC && thing2.IsRangedWeapon)
            {
                thing2.ammoData = null;
                thing2.c_ammo = 0;
            }
            if (startTransaction)
            {
                dragItemCard.from.thing = thing2;
                EClass.ui.StartDrag(dragItemCard);
            }
            else
            {
                if (to != null)
                {
                    thing2.invY = to.invY;
                    thing3 = to.container.AddThing(thing2, tryStack: true, to.invX, to.invY);
                    if (thing3 == thing2)
                    {
                        if (to.thing != null)
{
                            if (FreeTrade && !destInv.IsMagicChest)
{
                                if (!EClass.core.config.game.doubleClickToHold || !EInput.leftMouse.down || !(EClass.ui.dragDuration < 0.35f) || from == null || !(from.button == to.button) || to.button.invOwner is InvOwnerHotbar)
{
                                    EClass.ui.nextDrag = new DragItemCard(to.button);
                                    to.invOwner.Grab(to);
                                    flag = false;
                                }
                            }
                            else if (destInv.Container != thing2.parent)
{
                                thing3 = destInv.Container.AddThing(thing2);
                            }
                        }
                        to.grid[to.invX] = thing2;
                        thing2.invX = to.invX;
                        to.button.card = thing2;
                    }
                }
                else
                {
                    bool useGrid = EClass.game.UseGrid;
                    if (!EClass.game.UseGrid && (bool)destUIInv)
                    {
                        RectTransform rectTransform = new GameObject().AddComponent<RectTransform>();
                        rectTransform.SetParent(destUIInv.list.transform);
                        rectTransform.SetAnchor(0f, 0f, 0f, 0f);
                        rectTransform.localScale = Vector3.one;
                        rectTransform.sizeDelta = Vector3.one;
                        rectTransform.position = Input.mousePosition;
                        from.thing.posInvX = (int)rectTransform.anchoredPosition.x;
                        from.thing.posInvY = (int)rectTransform.anchoredPosition.y;
                    }
                    thing3 = ((!destInv.owner.IsPC) ? destInv.Container.AddThing(thing2, useGrid) : EClass.pc.Pick(thing2, msg: false));
                }
                destInv.OnProcess(thing3);
            }
            if (destInv.Container.trait is TraitDeliveryChest)
            {
                thing2.SetInt(102, EClass._zone.uid);
            }
            else
            {
                thing2.SetInt(102);
            }
            Chara chara = destInv.Container.Chara;
            if (chara != null && !chara.IsPC)
            {
                chara.TryEquip(thing2);
                if (thing2.id == "lovepotion" || thing2.id == "dreambug")
                {
                    EClass.pc.GiveLovePotion(chara, thing2);
                    EClass.ui.CloseLayers();
                    return true;
                }
            }
            if (thing2.id == "statue_weird")
            {
                if (!destInv.owner.IsPC)
                {
                    EClass.pc.Say("statue_sell");
                }
                else if (thing == null || thing.GetRootCard() != EClass.pc)
                {
                    EClass.pc.Say("statue_pick");
                }
            }
            if (flag)
            {
                SE.Drop();
            }
            return true;
        }
References Lang._currency(), EClass._zone, Card.AddThing(), DragItemCard.button, InvOwner.Transaction.button, InvOwner.buttons, Card.c_isImportant, Chara.CanAcceptItem(), InvOwner.ErrorMessage.card, card, Card.Chara, Core.config, InvOwner.Container, InvOwner.CopyOnTransfer, EClass.core, ShopTransaction.current, LayerDragGrid.currentIndex, InvOwner.DenyImportant, InvOwner.Transaction.destInv, InvOwner.Transaction.destUIInv, CoreConfig.GameConfig.doubleClickToHold, ButtonState.down, InvOwner.Transaction.error, InvOwner.Transaction.FreeTrade, InvOwner.Transaction.from, CoreConfig.game, EClass.game, InvOwner.Transaction.GetPrice(), Card.GetRootCard(), Chara.GiveLovePotion(), InvOwner.homeResource, Card.id, InvOwner.Transaction.IDCurrency, Thing.Identify(), LayerDragGrid.Instance, InvOwner.Transaction.inv, ButtonGrid.invOwner, Card.isChara, InvOwner.IsFailByCurse(), Card.IsIdentified, InvOwner.IsMagicChest, Card.isNPCProperty, Card.IsPC, Chara.IsPC, Chara.IsPCFaction, Card.IsRangedWeapon, InvOwner.Transaction.IsValid(), InvOwner.ErrorMessage.lang, EInput.leftMouse, UIInventory.list, HomeResource.Mod(), Card.ModCurrency(), Player.ModKarma(), Card.Num, InvOwner.Transaction.num, InvOwner.OnProcess(), InvOwner.owner, Card.parent, EClass.pc, Chara.Pick(), EClass.player, Card.pos, ShopTransaction.Process(), Msg.Say(), Card.Say(), InvOwner.Transaction.sell, InvOwner.ErrorMessage.Set(), ButtonGrid.SetCardGrid(), BaseCard.SetInt(), InvOwner.SingleTarget, InvOwner.ErrorMessage.sound, Card.Split(), Card.Talk(), InvOwner.Transaction.thing, InvOwner.Transaction.to, InvOwner.Trader, Card.trait, Chara.TryEquip(), Point.TryWitnessCrime(), EClass.ui, Spatial.uid, Game.UseGrid, and InvOwner.UseHomeResource.
Referenced by InvOwner.OnClick(), InvOwner.OnDrag(), and InvOwnerAlly.Process().
Member Data Documentation
button
ButtonGrid InvOwner.Transaction.button
Definition at line 39 of file InvOwner.cs.
Referenced by InvOwner.Transaction.Process(), and InvOwner.Transaction.Transaction().
destUIInv
UIInventory InvOwner.Transaction.destUIInv
Definition at line 47 of file InvOwner.cs.
Referenced by InvOwner.Transaction.Process(), and InvOwner.Transaction.Transaction().
error
ErrorMessage InvOwner.Transaction.error = new ErrorMessage() static
Definition at line 35 of file InvOwner.cs.
Referenced by InvOwner.Transaction.IsValid(), and InvOwner.Transaction.Process().
from
DragItemCard.DragInfo InvOwner.Transaction.from
Definition at line 43 of file InvOwner.cs.
Referenced by InvOwner.Transaction.Process(), and InvOwner.Transaction.Transaction().
inv
InvOwner InvOwner.Transaction.inv
Definition at line 49 of file InvOwner.cs.
Referenced by InvOwner.Transaction.Process(), and InvOwner.Transaction.Transaction().
num
int InvOwner.Transaction.num = 1
Definition at line 41 of file InvOwner.cs.
Referenced by InvOwner.Transaction.GetPrice(), InvOwner.Transaction.GetTextDetail(), InvOwner.Transaction.Process(), and InvOwner.Transaction.Transaction().
thing
Thing InvOwner.Transaction.thing
Definition at line 37 of file InvOwner.cs.
Referenced by InvOwner.Transaction.GetPrice(), InvOwner.Transaction.GetTextDetail(), InvOwner.Transaction.IsValid(), InvOwner.Transaction.Process(), and InvOwner.Transaction.Transaction().
to
DragItemCard.DragInfo InvOwner.Transaction.to
Definition at line 45 of file InvOwner.cs.
Referenced by InvOwner.Transaction.IsValid(), InvOwner.Transaction.Process(), and InvOwner.Transaction.Transaction().
Property Documentation
currency
CurrencyType InvOwner.Transaction.currency get
Definition at line 89 of file InvOwner.cs.
Referenced by InvOwner.Transaction.GetPrice(), InvOwner.Transaction.GetTextDetail(), and InvOwner.Transaction.IsValid().
destInv
InvOwner InvOwner.Transaction.destInv get
Definition at line 51 of file InvOwner.cs.
        {
            get
            {
                if (to == null)
                {
                    if (!(destUIInv != null))
                    {
                        if (!inv.owner.IsPC)
{
                            return Main;
                        }
                        return Trader;
                    }
                    return destUIInv.owner;
                }
                return to.invOwner;
            }
        }
Referenced by InvOwner.Transaction.GetTextDetail(), InvOwner.Transaction.IsValid(), and InvOwner.Transaction.Process().
FreeTrade
bool InvOwner.Transaction.FreeTrade get
Definition at line 91 of file InvOwner.cs.
        {
            get
            {
                if (HasTrader && currency != 0 && (to == null || to.invOwner.owner != EClass.pc))
                {
                    if ((bool)destUIInv)
                    {
                        return destUIInv.owner.owner == EClass.pc;
                    }
                    return false;
                }
                return true;
            }
        }
Referenced by InvOwner.Transaction.GetTextDetail(), InvOwner.Transaction.IsValid(), and InvOwner.Transaction.Process().
IDCurrency
string InvOwner.Transaction.IDCurrency get
Definition at line 87 of file InvOwner.cs.
Referenced by InvOwner.Transaction.IsValid(), and InvOwner.Transaction.Process().
sell
bool InvOwner.Transaction.sell get
Definition at line 71 of file InvOwner.cs.
        {
            get
            {
                if (destInv.InvertSell || destInv.owner.IsPC)
                {
                    if (destInv.InvertSell)
                    {
                        return destInv.owner.IsPC;
                    }
                    return false;
                }
                return true;
            }
        }
Referenced by InvOwner.Transaction.GetPrice(), InvOwner.Transaction.GetTextDetail(), InvOwner.Transaction.IsValid(), and InvOwner.Transaction.Process().
The documentation for this class was generated from the following file:
Elin/InvOwner.cs