Elin Decompiled Documentation: LogicalFire Class Reference
LogicalFire Class Reference
Public Member Functions
override void Update ()
void Transfer (Point p, byte amount=1)
Public Member Functions inherited from LogicalPoint
new void Set (Point p)
virtual void Update ()
virtual void Kill ()
Public Member Functions inherited from Point
bool Within (int _x, int _z, int _w, int _h)
Chara FirstVisibleChara ()
bool HasRoomOrArea (BaseArea a)
bool IsInSpot< T > ()
bool IsPublicSpace ()
Point ()
Point (Point p)
Point (int _x, int _z)
Point (int _index)
Point Copy ()
T Copy< T > ()
Point Set (int _x, int _z)
Point Set (int index)
Point Set (Point point)
override string ToString ()
void Set (Vector3 v)
ref Vector3 PositionAuto ()
ref Vector3 Position (int height)
ref Vector3 Position ()
ref Vector3 PositionTopdown ()
ref Vector3 PositionTopdownTreasure ()
ref Vector3 PositionCenter ()
Quaternion GetRotation (Point to)
float GetAngle (Point to)
float GetAngle2 (Point to)
Point GetNearestPoint (bool allowBlock=false, bool allowChara=true, bool allowInstalled=true, bool ignoreCenter=false)
bool ForeachNearestPoint (Func< Point, bool > endFunc, bool allowBlock=false, bool allowChara=true, bool allowInstalled=true, bool ignoreCenter=false, int maxRange=30)
Point GetRandomNeighbor ()
Point GetRandomPoint (int radius, bool requireLos=true, bool allowChara=true, bool allowBlocked=false, int tries=100)
Point GetRandomPointInRadius (int minRadius, int maxRadius, bool requireLos=true, bool allowChara=true, bool allowBlocked=false, int tries=2000)
Point GetPointTowards (Point dest)
void TalkWitnesses (Chara criminal, string idTalk, int radius=4, WitnessType type=WitnessType.everyone, Func< Chara, bool > talkIf=null, int chance=3)
List< Chara > ListWitnesses (Chara criminal, int radius=4, WitnessType type=WitnessType.crime, Chara target=null)
bool TryWitnessCrime (Chara criminal, Chara target=null, int radius=4, Func< Chara, bool > funcWitness=null)
void CallGuard (Chara criminal, Chara caller)
void SetBlock (int idMat=0, int idBlock=0)
void SetFloor (int idMat=0, int idFloor=0)
void SetObj (int id=0, int value=1, int dir=0)
void ModFire (int value, bool extinguish=false)
void Plow ()
bool Equals (int _x, int _z)
override bool Equals (object obj)
override int GetHashCode ()
int Distance (Point p)
int Distance (int tx, int tz)
bool IsBlockByHeight (Point p)
Point Clamp (bool useBounds=false)
List< Card > ListCards (bool includeMasked=false)
List< Card > ListVisibleCards ()
Card FindAttackTarget ()
Chara FindChara (Func< Chara, bool > func)
T FindThing< T > ()
Thing FindThing (Func< Thing, bool > func)
List< Card > ListThings< T > (bool onlyInstalled=true)
List< Chara > ListCharas ()
List< Chara > ListVisibleCharas ()
List< Chara > ListCharasInNeighbor (Func< Chara, bool > func)
List< Chara > ListCharasInRadius (Chara cc, int dist, Func< Chara, bool > func, bool onlyVisible=true)
T GetInstalled< T > ()
Effect PlayEffect (string id)
SoundSource PlaySound (string id, bool synced=true, float v=1f, bool spatial=true)
void RefreshNeighborTiles ()
void RefreshTile ()
bool HasNonHomeProperty (Thing exclude=null)
void Animate (AnimeID id, bool animeBlock=false)
RenderParam ApplyAnime (RenderParam p)
Vector3 ApplyAnime (ref Vector3 p)
List< IInspect > ListInspectorTargets ()
void ForeachMultiSize (int w, int h, Action< Point, bool > action)
void ForeachNeighbor (Action< Point > action, bool diagonal=true)
Point ToRegionPos ()
void SetHighlight (int id)
Properties
int fireAmount [get]
override LogicalPointManager manager [get]
Properties inherited from LogicalPoint
virtual LogicalPointManager manager [get]
Properties inherited from Point
int index [get]
Cell cell [get]
SourceMaterial.Row matRoofBlock [get]
SourceMaterial.Row matBlock [get]
SourceMaterial.Row matFloor [get]
SourceMaterial.Row matBridge [get]
SourceBlock.Row sourceRoofBlock [get]
SourceBlock.Row sourceBlock [get]
SourceFloor.Row sourceFloor [get]
SourceFloor.Row sourceBridge [get]
SourceObj.Row sourceObj [get]
CellDetail detail [get]
Area area [get]
Point Front [get]
GrowSystem growth [get]
int eloX [get]
int eloY [get]
bool HasDesignation [get]
bool HasDirt [get]
bool IsValid [get, set]
bool IsInBounds [get]
bool IsInBoundsPlus [get]
bool IsFarmField [get]
bool IsWater [get]
bool HasRamp [get]
bool HasRail [get]
bool HasRampOrLadder [get]
bool HasObj [get]
bool HasDecal [get]
bool HasBlock [get]
bool HasMinableBlock [get]
bool HasWallOrFence [get]
bool HasWall [get]
bool HasFence [get]
bool HasNonWallBlock [get]
bool HasTaskBuild [get]
bool HasBlockRecipe [get]
bool HasFloor [get]
bool HasBridge [get]
bool IsSky [get]
bool HasArea [get]
bool HasChara [get]
bool HasThing [get]
bool HasMultipleChara [get]
bool IsDeepWater [get]
Chara FirstChara [get]
Thing FirstThing [get]
Thing LastThing [get]
Thing Installed [get]
List< Thing > Things [get]
List< Chara > Charas [get]
bool IsSeen [get]
bool IsSync [get]
bool IsHidden [get]
bool IsBlocked [get]
bool IsHotSpring [get]
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Additional Inherited Members
Static Public Member Functions inherited from Point
static Point GetShared (int x, int z)
Static Public Member Functions inherited from EClass
static int rndSeed (int a, int seed)
static int rnd (int a)
static int curve (int a, int start, int step, int rate=75)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Public Attributes inherited from LogicalPoint
new int index
bool open
int life = 5
Public Attributes inherited from Point
int x
int z
Static Public Attributes inherited from Point
static readonly XY[] Surrounds
static Vector3 fixedPos
static Point shared = new Point()
static Point shared2 = new Point()
static Point shared3 = new Point()
static Map map
static Point Invalid
static Point Zero = new Point()
static BaseGameScreen _screen
Static Public Attributes inherited from EClass
static Core core
Detailed Description
Definition at line 1 of file LogicalFire.cs.
Member Function Documentation
Transfer()
void LogicalFire.Transfer (Point p, byte amount = 1) inline
Definition at line 89 of file LogicalFire.cs.
    {
        ModFire(-amount);
        if (!p.cell.HasFire)
        {
            SE.Play("fire");
        }
        p.ModFire(amount);
    }
References Point.cell, Cell.HasFire, and Point.ModFire().
Referenced by Update().
Update()
override void LogicalFire.Update () inline virtual
Reimplemented from LogicalPoint.
Definition at line 7 of file LogicalFire.cs.
    {
        manager.refreshList.Add(this);
        bool flag = false;
        XY[] surrounds = Point.Surrounds;
        for (int i = 0; i < surrounds.Length; i++)
        {
            XY xY = surrounds[i];
            Point.shared.Set(x + xY.x, z + xY.y);
            if (!Point.shared.IsValid)
            {
                continue;
            }
            Cell cell = Point.shared.cell;
            if (cell.fireAmount == fireAmount)
            {
                continue;
            }
            if (cell.fireAmount > fireAmount)
            {
                manager.GetOrCreate(Point.shared);
                continue;
            }
            if (fireAmount <= 0)
            {
                base.cell.effect = null;
                continue;
            }
            byte b = (byte)(fireAmount - cell.fireAmount);
            if (cell.fireAmount == 0)
            {
                if (fireAmount >= 2 && b >= 2)
                {
                    if (EClass.rnd(2) == 0)
                    {
                        Transfer(Point.shared, 1);
                    }
                    ModFire(-1);
                    flag = true;
                }
            }
            else if (b == 1)
            {
                if (life < 2)
                {
                    ModFire(-1);
                }
                else if (EClass.rnd(3) == 0)
                {
                    Transfer(Point.shared, 1);
                    ModFire(1);
                    flag = true;
                }
            }
            else
            {
                if (b > 6)
                {
                    b = 6;
                }
                Transfer(Point.shared, (byte)(b - 1));
                flag = true;
            }
        }
        if (fireAmount == 0)
        {
            base.cell.effect = null;
        }
        else
        {
            EClass._map.Burn(x, z);
        }
        if (!flag)
        {
            life--;
        }
        if (life < 0)
        {
            Kill();
        }
    }
References EClass._map, Map.Burn(), Point.cell, Cell.fireAmount, fireAmount, LogicalPointManager.GetOrCreate(), Point.IsValid, LogicalPoint.Kill(), LogicalPoint.life, manager, Point.ModFire(), LogicalPointManager.refreshList, EClass.rnd(), Point.Set(), Point.shared, Point.Surrounds, Transfer(), Point.x, XY.x, XY.y, and Point.z.
Property Documentation
fireAmount
int LogicalFire.fireAmount get
Definition at line 3 of file LogicalFire.cs.
Referenced by Update().
manager
override LogicalPointManager LogicalFire.manager get
Definition at line 5 of file LogicalFire.cs.
Referenced by Update().
The documentation for this class was generated from the following file:
Elin/LogicalFire.cs