Elin Decompiled Documentation: SourceMaterial.Row Class Reference
SourceMaterial.Row Class Reference
Public Member Functions
override void OnImportData (SourceData data)
void Init ()
void SetTiles ()
void AddBlood (Point p, int a=1)
void PlayHitEffect (Point p)
Color GetColor ()
string TryGetSound (string suffx, RenderRow c=null)
string GetSoundDead (RenderRow c=null)
string GetSoundDrop (RenderRow c=null)
string GetSoundCraft (RenderRow c=null)
string GetSoundImpact (RenderRow c=null)
void CreateByProduct (Thing container, int num)
Public Attributes
int id
string alias
string name_JP
string name
string category
string[] tag
string thing
string[] goods
string[] minerals
int decal
int decay
int grass
int defFloor
int defBlock
int edge
int ramp
string idSound
string soundFoot
int hardness
string[] groups
int tier
int chance
int weight
int value
int quality
int atk
int dmg
int dv
int pv
int dice
string[] bits
int[] elements
string[] altName
string[] altName_JP
Color matColor
Color altColor
Dictionary< int, int > elementMap
string name_L
string detail_L
string[] altName_L
Static Public Attributes
static string[] IDPick
static string[] IDAxe
Properties
override bool UseAlias [get]
override string GetAlias [get]
bool UsePick [get]
bool UseAxe [get]
Private Member Functions
void< CreateByProduct > g__C (string _id, ref SourceMaterial.Row.<>c__DisplayClass52_0 A_2)
Detailed Description
Definition at line 136 of file SourceMaterial.cs.
Member Function Documentation
AddBlood()
void SourceMaterial.Row.AddBlood (Point p, int a = 1) inline
Definition at line 172 of file SourceMaterial.cs.
        {
            if (this.decal == 0)
            {
                return;
            }
            if (p.cell.IsSnowTile && this != MATERIAL.sourceSnow)
            {
                MATERIAL.sourceSnow.AddBlood(p, a);
                return;
            }
            for (int i = 0; i < a; i++)
            {
                EClass._map.AddDecal(p.x + ((EClass.rnd(2) == 0) ? 0 : (EClass.rnd(3) - 1)), p.z + ((EClass.rnd(2) == 0) ? 0 : (EClass.rnd(3) - 1)), this.decal, 1, true);
            }
        }
References EClass._map, Map.AddDecal(), Point.cell, SourceMaterial.Row.decal, Cell.IsSnowTile, EClass.rnd(), MATERIAL.sourceSnow, Point.x, and Point.z.
Referenced by Map.DestroyObj(), Map.MineBlock(), TaskDig.OnCreateProgress(), TaskHarvest.OnCreateProgress(), and TaskPlow.OnCreateProgress().
CreateByProduct()
void SourceMaterial.Row.CreateByProduct (Thing container, int num) inline
Definition at line 237 of file SourceMaterial.cs.
        {
            SourceMaterial.Row.<>c__DisplayClass52_0 CS$<>8__locals1;
            CS$<>8__locals1.<>4__this = this;
            CS$<>8__locals1.num = num;
            CS$<>8__locals1.container = container;
            Thing thing = ThingGen.CreateRawMaterial(this);
            thing.ModNum(CS$<>8__locals1.num, true);
            CS$<>8__locals1.container.AddThing(thing, true, -1, -1);
            this.<CreateByProduct>g__C|52_0("dye", ref CS$<>8__locals1);
            string text = this.category;
            uint num2 = <PrivateImplementationDetails>.ComputeStringHash(text);
            if (num2 <= 1167392201U)
            {
                if (num2 <= 270655681U)
                {
                    if (num2 != 174734082U)
                    {
                        if (num2 == 270655681U)
{
                            if (text == "fiber")
{
                                this.<CreateByProduct>g__C|52_0("thread", ref CS$<>8__locals1);
                                this.<CreateByProduct>g__C|52_0("texture", ref CS$<>8__locals1);
                                this.<CreateByProduct>g__C|52_0("string", ref CS$<>8__locals1);
                            }
                        }
                    }
                    else if (text == "soil")
                    {
                        this.<CreateByProduct>g__C|52_0("glass", ref CS$<>8__locals1);
                        this.<CreateByProduct>g__C|52_0("clay", ref CS$<>8__locals1);
                        this.<CreateByProduct>g__C|52_0("brick", ref CS$<>8__locals1);
                    }
                }
                else if (num2 != 862676408U)
                {
                    if (num2 != 974867124U)
                    {
                        if (num2 == 1167392201U)
{
                            if (text == "crystal")
{
                                this.<CreateByProduct>g__C|52_0("glass", ref CS$<>8__locals1);
                                this.<CreateByProduct>g__C|52_0("gem", ref CS$<>8__locals1);
                            }
                        }
                    }
                    else if (text == "rock")
                    {
                        this.<CreateByProduct>g__C|52_0("rock", ref CS$<>8__locals1);
                        this.<CreateByProduct>g__C|52_0("pebble", ref CS$<>8__locals1);
                        this.<CreateByProduct>g__C|52_0("cutstone", ref CS$<>8__locals1);
                    }
                }
                else if (text == "skin")
                {
                    this.<CreateByProduct>g__C|52_0("texture", ref CS$<>8__locals1);
                }
            }
            else if (num2 <= 1527558748U)
            {
                if (num2 != 1237752336U)
                {
                    if (num2 == 1527558748U)
                    {
                        if (text == "gem")
{
                            this.<CreateByProduct>g__C|52_0("cutstone", ref CS$<>8__locals1);
                            this.<CreateByProduct>g__C|52_0("ingot", ref CS$<>8__locals1);
                            this.<CreateByProduct>g__C|52_0("gem", ref CS$<>8__locals1);
                        }
                    }
                }
                else if (!(text == "water"))
                {
                }
            }
            else if (num2 != 2226448744U)
            {
                if (num2 != 2585652531U)
                {
                    if (num2 == 3683705231U)
                    {
                        if (text == "bone")
{
                            this.<CreateByProduct>g__C|52_0("glass", ref CS$<>8__locals1);
                            this.<CreateByProduct>g__C|52_0("stick", ref CS$<>8__locals1);
                        }
                    }
                }
                else if (text == "ore")
                {
                    this.<CreateByProduct>g__C|52_0("cutstone", ref CS$<>8__locals1);
                    this.<CreateByProduct>g__C|52_0("ingot", ref CS$<>8__locals1);
                }
            }
            else if (text == "wood")
            {
                this.<CreateByProduct>g__C|52_0("plank", ref CS$<>8__locals1);
                this.<CreateByProduct>g__C|52_0("stick", ref CS$<>8__locals1);
                this.<CreateByProduct>g__C|52_0("bark", ref CS$<>8__locals1);
            }
            foreach (string text2 in this.goods)
            {
                this.<CreateByProduct>g__C|52_0(text2, ref CS$<>8__locals1);
            }
        }
References SourceMaterial.Row.category, SourceMaterial.Row.CreateByProduct(), ThingGen.CreateRawMaterial(), SourceMaterial.Row.g__C(), SourceMaterial.Row.goods, text, and SourceMaterial.Row.thing.
Referenced by SourceMaterial.Row.CreateByProduct().
g__C()
void< CreateByProduct > SourceMaterial.Row.g__C (string _id, ref SourceMaterial::Row::<>c__DisplayClass52_0 A_2) inline private
Definition at line 363 of file SourceMaterial.cs.
        {
            Thing thing = ThingGen.Create(_id, -1, -1);
            thing.ChangeMaterial(this.id);
            thing.ModNum(A_2.num, true);
            A_2.container.AddThing(thing, true, -1, -1);
        }
References ThingGen.Create(), Card.ModNum(), and SourceMaterial.Row.thing.
Referenced by SourceMaterial.Row.CreateByProduct().
GetColor()
Color SourceMaterial.Row.GetColor () inline
Definition at line 194 of file SourceMaterial.cs.
        {
            return Core.Instance.Colors.matColors[this.alias].main;
        }
References SourceMaterial.Row.alias.
Referenced by UIMapPreview._RefreshPoint(), Map.MineBlock(), Map.MineFloor(), and SourceMaterial.Row.PlayHitEffect().
GetSoundCraft()
string SourceMaterial.Row.GetSoundCraft (RenderRow c = null) inline
Definition at line 219 of file SourceMaterial.cs.
        {
            if (this.category == "wood")
            {
                return "build_progress";
            }
            return this.TryGetSound("craft", c);
        }
References SourceMaterial.Row.category, and SourceMaterial.Row.TryGetSound().
GetSoundDead()
string SourceMaterial.Row.GetSoundDead (RenderRow c = null) inline
Definition at line 209 of file SourceMaterial.cs.
        {
            return this.TryGetSound("dead", c);
        }
References SourceMaterial.Row.TryGetSound().
Referenced by Map.DestroyObj(), Map.MineBlock(), and Map.MineFloor().
GetSoundDrop()
string SourceMaterial.Row.GetSoundDrop (RenderRow c = null) inline
Definition at line 214 of file SourceMaterial.cs.
        {
            return this.TryGetSound("drop", c);
        }
References SourceMaterial.Row.TryGetSound().
GetSoundImpact()
string SourceMaterial.Row.GetSoundImpact (RenderRow c = null) inline
Definition at line 228 of file SourceMaterial.cs.
        {
            if (c != null && !c.idSound.IsEmpty())
            {
                return "Material/" + c.idSound;
            }
            return "Material/" + this.idSound;
        }
References SourceMaterial.Row.idSound.
Referenced by TaskDig.OnCreateProgress(), TaskDrawWater.OnCreateProgress(), TaskHarvest.OnCreateProgress(), TaskPlow.OnCreateProgress(), and SourceMaterial.Row.TryGetSound().
Init()
void SourceMaterial.Row.Init () inline
Definition at line 160 of file SourceMaterial.cs.
        {
            MatColors matColors = Core.Instance.Colors.matColors.TryGetValue(this.alias, null);
            this.matColor = matColors.main;
            this.altColor = matColors.alt;
            this.SetTiles();
        }
References SourceMaterial.Row.alias, and SourceMaterial.Row.SetTiles().
OnImportData()
override void SourceMaterial.Row.OnImportData (SourceData data) inline
Definition at line 154 of file SourceMaterial.cs.
        {
            base.OnImportData(data);
            this.SetTiles();
        }
References SourceMaterial.Row.SetTiles().
PlayHitEffect()
void SourceMaterial.Row.PlayHitEffect (Point p) inline
Definition at line 189 of file SourceMaterial.cs.
        {
            Effect.Get("mine2").Play(p, 0f, null, null).SetParticleColor(this.GetColor()).Emit(2 + EClass.rnd(4));
        }
References Effect.Get(), SourceMaterial.Row.GetColor(), Effect.Play(), and EClass.rnd().
Referenced by TaskDig.OnCreateProgress(), TaskDrawWater.OnCreateProgress(), TaskHarvest.OnCreateProgress(), and TaskPlow.OnCreateProgress().
SetTiles()
void SourceMaterial.Row.SetTiles () inline
Definition at line 168 of file SourceMaterial.cs.
        {
        }
Referenced by SourceMaterial.Row.Init(), and SourceMaterial.Row.OnImportData().
TryGetSound()
string SourceMaterial.Row.TryGetSound (string suffx, RenderRow c = null) inline
Definition at line 199 of file SourceMaterial.cs.
        {
            string soundImpact = this.GetSoundImpact(c);
            if (EClass.Sound.Exist(soundImpact + "_" + suffx))
            {
                return soundImpact + "_" + suffx;
            }
            return soundImpact;
        }
References SourceMaterial.Row.GetSoundImpact(), and EClass.Sound.
Referenced by SourceMaterial.Row.GetSoundCraft(), SourceMaterial.Row.GetSoundDead(), and SourceMaterial.Row.GetSoundDrop().
Member Data Documentation
alias
string SourceMaterial.Row.alias
Definition at line 373 of file SourceMaterial.cs.
Referenced by BiomeProfile.BaseTile._GetMat(), Trait.CreateStock(), Card.DyeRandom(), SourceMaterial.Row.GetColor(), SourceMaterial.Row.Init(), Map.MineFloor(), and Map.MineObj().
altColor
Color SourceMaterial.Row.altColor
Definition at line 443 of file SourceMaterial.cs.
altName
string [] SourceMaterial.Row.altName
Definition at line 435 of file SourceMaterial.cs.
altName_JP
string [] SourceMaterial.Row.altName_JP
Definition at line 437 of file SourceMaterial.cs.
altName_L
string [] SourceMaterial.Row.altName_L
Definition at line 465 of file SourceMaterial.cs.
atk
int SourceMaterial.Row.atk
Definition at line 421 of file SourceMaterial.cs.
bits
string [] SourceMaterial.Row.bits
Definition at line 431 of file SourceMaterial.cs.
category
string SourceMaterial.Row.category
Definition at line 379 of file SourceMaterial.cs.
Referenced by SourceMaterial.Row.CreateByProduct(), and SourceMaterial.Row.GetSoundCraft().
chance
int SourceMaterial.Row.chance
Definition at line 413 of file SourceMaterial.cs.
decal
int SourceMaterial.Row.decal
Definition at line 389 of file SourceMaterial.cs.
Referenced by SourceMaterial.Row.AddBlood().
decay
int SourceMaterial.Row.decay
Definition at line 391 of file SourceMaterial.cs.
defBlock
int SourceMaterial.Row.defBlock
Definition at line 397 of file SourceMaterial.cs.
defFloor
int SourceMaterial.Row.defFloor
Definition at line 395 of file SourceMaterial.cs.
Referenced by MapGen.OnGenerateTerrain().
detail_L
string SourceMaterial.Row.detail_L
Definition at line 463 of file SourceMaterial.cs.
dice
int SourceMaterial.Row.dice
Definition at line 429 of file SourceMaterial.cs.
dmg
int SourceMaterial.Row.dmg
Definition at line 423 of file SourceMaterial.cs.
dv
int SourceMaterial.Row.dv
Definition at line 425 of file SourceMaterial.cs.
edge
int SourceMaterial.Row.edge
Definition at line 399 of file SourceMaterial.cs.
elementMap
Dictionary<int, int> SourceMaterial.Row.elementMap
Definition at line 445 of file SourceMaterial.cs.
elements
int [] SourceMaterial.Row.elements
Definition at line 433 of file SourceMaterial.cs.
Referenced by Thing.ApplyMaterial().
goods
string [] SourceMaterial.Row.goods
Definition at line 385 of file SourceMaterial.cs.
Referenced by SourceMaterial.Row.CreateByProduct().
grass
int SourceMaterial.Row.grass
Definition at line 393 of file SourceMaterial.cs.
groups
string [] SourceMaterial.Row.groups
Definition at line 409 of file SourceMaterial.cs.
hardness
int SourceMaterial.Row.hardness
Definition at line 407 of file SourceMaterial.cs.
Referenced by BaseTaskHarvest.SetTarget().
id
int SourceMaterial.Row.id
Definition at line 371 of file SourceMaterial.cs.
Referenced by BiomeProfile.BaseTile._GetMat(), MapGen.OnGenerateTerrain(), TraitBoat.OnRemovedFromZone(), ActEffect.Proc(), BaseTaskHarvest.SetTarget(), and ActionMode.UpdateInput().
IDAxe
string [] SourceMaterial.Row.IDAxe static
Initial value:
= new string[]
        {
            "wood"
        }
Definition at line 456 of file SourceMaterial.cs.
IDPick
string [] SourceMaterial.Row.IDPick static
Initial value:
= new string[]
        {
            "rock",
            "ore",
            "gem",
            "crystal",
            "bone"
        }
Definition at line 447 of file SourceMaterial.cs.
idSound
string SourceMaterial.Row.idSound
Definition at line 403 of file SourceMaterial.cs.
Referenced by SourceMaterial.Row.GetSoundImpact().
matColor
Color SourceMaterial.Row.matColor
Definition at line 440 of file SourceMaterial.cs.
Referenced by Chara._Move(), BaseTileMap.DrawTile(), TileMapElona.DrawTile(), and Lot.SetBaseRoom().
minerals
string [] SourceMaterial.Row.minerals
Definition at line 387 of file SourceMaterial.cs.
name
string SourceMaterial.Row.name
Definition at line 377 of file SourceMaterial.cs.
name_JP
string SourceMaterial.Row.name_JP
Definition at line 375 of file SourceMaterial.cs.
Referenced by BiomeProfile.BaseTile._GetMat().
name_L
string SourceMaterial.Row.name_L
Definition at line 461 of file SourceMaterial.cs.
pv
int SourceMaterial.Row.pv
Definition at line 427 of file SourceMaterial.cs.
quality
int SourceMaterial.Row.quality
Definition at line 419 of file SourceMaterial.cs.
ramp
int SourceMaterial.Row.ramp
Definition at line 401 of file SourceMaterial.cs.
soundFoot
string SourceMaterial.Row.soundFoot
Definition at line 405 of file SourceMaterial.cs.
Referenced by Chara._Move().
tag
string [] SourceMaterial.Row.tag
Definition at line 381 of file SourceMaterial.cs.
Referenced by BaseTaskHarvest.SetTarget().
thing
string SourceMaterial.Row.thing
Definition at line 383 of file SourceMaterial.cs.
Referenced by SourceMaterial.Row.CreateByProduct(), and SourceMaterial.Row.g__C().
tier
int SourceMaterial.Row.tier
Definition at line 411 of file SourceMaterial.cs.
value
int SourceMaterial.Row.value
Definition at line 417 of file SourceMaterial.cs.
weight
int SourceMaterial.Row.weight
Definition at line 415 of file SourceMaterial.cs.
Property Documentation
GetAlias
override string SourceMaterial.Row.GetAlias get
Definition at line 146 of file SourceMaterial.cs.
        {
            get
            {
                return this.alias;
            }
        }
UseAlias
override bool SourceMaterial.Row.UseAlias get
Definition at line 138 of file SourceMaterial.cs.
        {
            get
            {
                return true;
            }
        }
UseAxe
bool SourceMaterial.Row.UseAxe get
Definition at line 354 of file SourceMaterial.cs.
        {
            get
            {
                return SourceMaterial.Row.IDAxe.Contains(this.category);
            }
        }
UsePick
bool SourceMaterial.Row.UsePick get
Definition at line 346 of file SourceMaterial.cs.
        {
            get
            {
                return SourceMaterial.Row.IDPick.Contains(this.category);
            }
        }
The documentation for this class was generated from the following file:
Elin/SourceMaterial.cs