Elin Decompiled Documentation: UIDragGridInfo Class Reference
UIDragGridInfo Class Reference
Public Member Functions
void Refresh ()
void Init (Card _owner)
void InitFuel (Card _owner)
Public Attributes
Window window
UIText textHeader
Transform transMold
Transform moldThing
Transform moldPlus
Transform moldEqual
Transform moldOr
Transform moldCat
Transform moldUnknown
UIList list
Card owner
UINote note
Private Member Functions
void Awake ()
Additional Inherited Members
Static Public Member Functions inherited from EMono
static int rnd (int a)
Static Public Attributes inherited from EMono
static Core core
Properties inherited from EMono
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SoundManager Sound [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static CoreDebug debug [get]
Detailed Description
Definition at line 6 of file UIDragGridInfo.cs.
Member Function Documentation
Awake()
void UIDragGridInfo.Awake () inline private
Definition at line 32 of file UIDragGridInfo.cs.
    {
        window.SetActive(enable: false);
        transMold.SetActive(enable: false);
    }
References transMold, and window.
Init()
void UIDragGridInfo.Init (Card _owner) inline
Definition at line 43 of file UIDragGridInfo.cs.
    {
        owner = _owner;
        TraitCrafter crafter = owner.trait as TraitCrafter;
        if (crafter == null)
        {
            return;
        }
        textHeader.text = "knownRecipe".lang();
        List<SourceRecipe.Row> recipes = EMono.sources.recipes.rows.Where((SourceRecipe.Row r) => r.factory == crafter.IdSource).ToList();
        if (recipes.Count == 0)
        {
            return;
        }
        list.callbacks = new UIList.Callback<SourceRecipe.Row, LayoutGroup>
        {
            onClick = delegate
            {
            },
            onInstantiate = delegate(SourceRecipe.Row a, LayoutGroup b)
            {
                for (int i = 0; i < crafter.numIng; i++)
                {
                    if (i != 0)
                    {
                        Util.Instantiate(moldPlus, b);
                    }
                    string[] array2 = i switch
                    {
                        1 => a.ing2,
                        0 => a.ing1,
                        _ => a.ing3,
                    };
                    if (array2.IsEmpty())
                    {
                        break;
                    }
                    string[] array3 = array2;
                    foreach (string text2 in array3)
                    {
                        if (text2 != array2[0])
{
                            Util.Instantiate(moldOr, b);
                        }
                        AddThing(text2, null);
                    }
                }
                Util.Instantiate(moldEqual, b);
                AddThing(a.thing, (a.type == "FixedResource") ? "noInherit" : null);
            },
            onList = delegate
            {
                foreach (SourceRecipe.Row item in recipes)
                {
                    if (item.tag.Contains("known") || EMono.player.knownCraft.Contains(item.id) || EMono.debug.godCraft)
                    {
                        list.Add(item);
                    }
                }
            }
        };
        list.List();
        TraitRollingFortune traitRollingFortune = owner.trait as TraitRollingFortune;
        note.SetActive(traitRollingFortune != null);
        if (traitRollingFortune != null)
        {
            EMono._zone.GetOrCreateFortuneRollData().WriteNote(note);
        }
        window.SetActive(enable: true);
        window.RebuildLayout(recursive: true);
        void AddThing(string id, string lang)
        {
            if (id.IsEmpty() || id == "notImplemented" || id == "any")
            {
                Util.Instantiate(moldUnknown, P_2.b).GetComponentInChildren<UIButton>().tooltip.lang = "???";
            }
            else
            {
                id = id.Replace("%", "@");
                string[] array = id.Split('@');
                string text = "";
                id = array[0];
                if (id.StartsWith('#'))
                {
                    text = id.Replace("#", "");
                    id = EMono.sources.categories.map[text].GetIdThing();
                }
                CardRow cardRow = EMono.sources.cards.map[id];
                SourceMaterial.Row mat = cardRow.DefaultMaterial;
                if (array.Length >= 2)
                {
                    mat = ((!(array[1] == "gelatin")) ? EMono.sources.materials.alias[array[1]] : EMono.sources.materials.alias["jelly"]);
                }
                Transform transform = Util.Instantiate(moldThing, P_2.b);
                Image componentInChildren = transform.GetComponentInChildren<Image>();
                UIButton component = componentInChildren.GetComponent<UIButton>();
                cardRow.SetImage(componentInChildren, null, cardRow.GetColorInt(mat));
                string s = cardRow.GetName();
                if (!text.IsEmpty() || lang != null)
                {
                    Util.Instantiate(moldCat, transform).GetComponentInChildren<UIText>().SetText((lang ?? "category").lang());
                    if (lang == null)
                    {
                        string @ref = EMono.sources.categories.map[text].GetName();
                        s = "ingCat".lang(@ref);
                    }
                }
                component.tooltip.lang = s.ToTitleCase();
            }
        }
    }
References EMono._zone, UIList.Add(), SourceManager.cards, SourceManager.categories, EMono.debug, RenderRow.DefaultMaterial, RenderRow.GetColorInt(), CardRow.GetName(), Zone.GetOrCreateFortuneRollData(), CoreDebug.godCraft, TraitCrafter.IdSource, item, Player.knownCraft, UIList.List(), list, SourceCard.map, SourceManager.materials, moldCat, moldEqual, moldOr, moldPlus, moldThing, moldUnknown, note, TraitCrafter.numIng, owner, EMono.player, SourceManager.recipes, RenderRow.SetImage(), EMono.sources, Util, window, and FortuneRollData.WriteNote().
Referenced by Refresh().
InitFuel()
void UIDragGridInfo.InitFuel (Card _owner) inline
Definition at line 155 of file UIDragGridInfo.cs.
    {
        owner = _owner;
        textHeader.text = "knownFuel".lang();
        List<SourceThing.Row> fuels = new List<SourceThing.Row>();
        foreach (SourceThing.Row row in EMono.sources.things.rows)
        {
            if (owner.trait.IsFuel(row.id))
            {
                fuels.Add(row);
            }
        }
        list.callbacks = new UIList.Callback<SourceThing.Row, LayoutGroup>
        {
            onClick = delegate
            {
            },
            onInstantiate = delegate(SourceThing.Row a, LayoutGroup b)
            {
                AddThing(a.id);
                Util.Instantiate(moldEqual, b);
                AddThing(owner.id);
            },
            onList = delegate
            {
                foreach (SourceThing.Row item in fuels)
                {
                    list.Add(item);
                }
            }
        };
        list.List();
        window.SetActive(enable: true);
        window.RebuildLayout(recursive: true);
        void AddThing(string id)
        {
            if (id.IsEmpty() || id == "notImplemented" || id == "any")
            {
                Util.Instantiate(moldUnknown, P_1.b).GetComponentInChildren<UIButton>().tooltip.lang = "???";
            }
            else
            {
                id = id.Replace("%", "@");
                string[] array = id.Split('@');
                string cat = "";
                id = array[0];
                if (id.StartsWith('#'))
                {
                    cat = id.Replace("#", "");
                    List<CardRow> obj = EMono.sources.cards.rows.Where((CardRow r) => r.Category.IsChildOf(cat)).ToList();
                    obj.Sort((CardRow a, CardRow b) => a.value - b.value);
                    id = obj[0].id;
                }
                CardRow cardRow = EMono.sources.cards.map[id];
                SourceMaterial.Row mat = cardRow.DefaultMaterial;
                if (array.Length >= 2)
                {
                    mat = ((!(array[1] == "gelatin")) ? EMono.sources.materials.alias[array[1]] : EMono.sources.materials.alias["jelly"]);
                }
                Transform transform = Util.Instantiate(moldThing, P_1.b);
                Image componentInChildren = transform.GetComponentInChildren<Image>();
                UIButton component = componentInChildren.GetComponent<UIButton>();
                cardRow.SetImage(componentInChildren, null, cardRow.GetColorInt(mat));
                string s = cardRow.GetName();
                if (!cat.IsEmpty())
                {
                    Transform obj2 = Util.Instantiate(moldCat, transform);
                    string @ref = EMono.sources.categories.map[cat].GetName();
                    obj2.GetComponentInChildren<UIText>().SetText("(" + "category".lang() + ")");
                    s = "ingCat".lang(@ref);
                }
                component.tooltip.lang = s.ToTitleCase();
            }
        }
    }
References UIList.Add(), SourceManager.cards, SourceManager.categories, RenderRow.Category, RenderRow.DefaultMaterial, RenderRow.GetColorInt(), CardRow.GetName(), Card.id, Trait.IsFuel(), item, UIText.lang, UIList.List(), list, SourceCard.map, SourceManager.materials, moldCat, moldEqual, moldThing, moldUnknown, owner, SourceCard.rows, RenderRow.SetImage(), EMono.sources, SourceManager.things, Card.trait, Util, RenderRow.value, and window.
Refresh()
void UIDragGridInfo.Refresh () inline
Definition at line 38 of file UIDragGridInfo.cs.
    {
        Init(owner);
    }
References Init(), and owner.
Referenced by TraitCrafter.Craft().
Member Data Documentation
list
UIList UIDragGridInfo.list
Definition at line 26 of file UIDragGridInfo.cs.
Referenced by Init(), and InitFuel().
moldCat
Transform UIDragGridInfo.moldCat
Definition at line 22 of file UIDragGridInfo.cs.
Referenced by Init(), and InitFuel().
moldEqual
Transform UIDragGridInfo.moldEqual
Definition at line 18 of file UIDragGridInfo.cs.
Referenced by Init(), and InitFuel().
moldOr
Transform UIDragGridInfo.moldOr
Definition at line 20 of file UIDragGridInfo.cs.
Referenced by Init().
moldPlus
Transform UIDragGridInfo.moldPlus
Definition at line 16 of file UIDragGridInfo.cs.
Referenced by Init().
moldThing
Transform UIDragGridInfo.moldThing
Definition at line 14 of file UIDragGridInfo.cs.
Referenced by Init(), and InitFuel().
moldUnknown
Transform UIDragGridInfo.moldUnknown
Definition at line 24 of file UIDragGridInfo.cs.
Referenced by Init(), and InitFuel().
note
UINote UIDragGridInfo.note
Definition at line 30 of file UIDragGridInfo.cs.
Referenced by Init().
owner
Card UIDragGridInfo.owner
Definition at line 28 of file UIDragGridInfo.cs.
Referenced by Init(), InitFuel(), and Refresh().
textHeader
UIText UIDragGridInfo.textHeader
Definition at line 10 of file UIDragGridInfo.cs.
transMold
Transform UIDragGridInfo.transMold
Definition at line 12 of file UIDragGridInfo.cs.
Referenced by Awake().
window
Window UIDragGridInfo.window
Definition at line 8 of file UIDragGridInfo.cs.
Referenced by Awake(), Init(), and InitFuel().
The documentation for this class was generated from the following file:
Elin/UIDragGridInfo.cs