Elin Decompiled Documentation: UiInputField Class Reference
UiInputField Class Reference
Public Member Functions
void HideCaret ()
void Clear ()
override void OnSelect (BaseEventData eventData)
override void OnDeselect (BaseEventData eventData)
Public Attributes
bool dontClearOnESC
Action onUpdate
Action onDisable
bool registerToTabSwitcher
string stringEdit = ""
Protected Member Functions
override void Awake ()
override void Start ()
override void OnDisable ()
Events
Action OnSubmitEvent
Action InputSelected
Action InputDeselected
Private Member Functions
void Update ()
void OnValueChanged (string s)
void OnEndEdit (string s)
void Deselect ()
Detailed Description
Definition at line 6 of file UiInputField.cs.
Member Function Documentation
Awake()
override void UiInputField.Awake () inline protected
Definition at line 31 of file UiInputField.cs.
    {
        base.textComponent.font = SkinManager.Instance.fontSet.ui.source.font;
    }
References FontSource.font, SkinManager.fontSet, SkinManager.Instance, SkinManager.FontData.source, and SkinManager.FontSet.ui.
Clear()
void UiInputField.Clear () inline
Definition at line 93 of file UiInputField.cs.
    {
        base.text = string.Empty;
    }
Referenced by UIContextMenu.AddSlider().
Deselect()
void UiInputField.Deselect () inline private
Definition at line 84 of file UiInputField.cs.
    {
        if (!EventSystem.current.alreadySelecting)
        {
            EventSystem.current.SetSelectedGameObject(null);
        }
        DeactivateInputField();
    }
Referenced by OnEndEdit().
HideCaret()
void UiInputField.HideCaret () inline
Definition at line 53 of file UiInputField.cs.
    {
        m_CaretSelectPosition = 0;
    }
OnDeselect()
override void UiInputField.OnDeselect (BaseEventData eventData) inline
Definition at line 104 of file UiInputField.cs.
    {
        base.OnDeselect(eventData);
        this.InputDeselected();
    }
References InputDeselected.
OnDisable()
override void UiInputField.OnDisable () inline protected
Definition at line 58 of file UiInputField.cs.
    {
        onDisable?.Invoke();
    }
References onDisable.
OnEndEdit()
void UiInputField.OnEndEdit (string s) inline private
Definition at line 71 of file UiInputField.cs.
    {
        if (Input.GetKeyDown(KeyCode.Return) || Input.GetKeyDown(KeyCode.KeypadEnter))
        {
            this.OnSubmitEvent();
        }
        Deselect();
        if (dontClearOnESC && Input.GetKeyDown(KeyCode.Escape))
        {
            base.text = stringEdit;
        }
    }
References Deselect(), OnSubmitEvent, and stringEdit.
Referenced by Start().
OnSelect()
override void UiInputField.OnSelect (BaseEventData eventData) inline
Definition at line 98 of file UiInputField.cs.
    {
        base.OnSelect(eventData);
        this.InputSelected();
    }
References InputSelected.
OnValueChanged()
void UiInputField.OnValueChanged (string s) inline private
Definition at line 63 of file UiInputField.cs.
    {
        if (dontClearOnESC && !Input.GetKeyDown(KeyCode.Escape))
        {
            stringEdit = base.text;
        }
    }
References dontClearOnESC, and stringEdit.
Referenced by Start().
Start()
override void UiInputField.Start () inline protected
Definition at line 36 of file UiInputField.cs.
    {
        base.Start();
        if (registerToTabSwitcher)
        {
            ManlySingleton<InputFieldsTabSwitcher>.Instance.RegisterInputField(this);
        }
        base.onEndEdit.AddListener(OnEndEdit);
        base.onValueChanged.AddListener(OnValueChanged);
        stringEdit = base.text;
    }
References ManlySingleton< T >.Instance, OnEndEdit(), OnValueChanged(), registerToTabSwitcher, and stringEdit.
Update()
void UiInputField.Update () inline private
Definition at line 48 of file UiInputField.cs.
    {
        onUpdate?.Invoke();
    }
References onUpdate.
Member Data Documentation
dontClearOnESC
bool UiInputField.dontClearOnESC
Definition at line 8 of file UiInputField.cs.
Referenced by OnValueChanged().
onDisable
Action UiInputField.onDisable
Definition at line 12 of file UiInputField.cs.
Referenced by OnDisable().
onUpdate
Action UiInputField.onUpdate
Definition at line 10 of file UiInputField.cs.
Referenced by Update().
registerToTabSwitcher
bool UiInputField.registerToTabSwitcher
Definition at line 15 of file UiInputField.cs.
Referenced by Start().
stringEdit
string UiInputField.stringEdit = ""
Definition at line 17 of file UiInputField.cs.
Referenced by OnEndEdit(), OnValueChanged(), and Start().
Event Documentation
InputDeselected
Action UiInputField.InputDeselected
Initial value:
= delegate
    {
    }
Definition at line 27 of file UiInputField.cs.
Referenced by OnDeselect().
InputSelected
Action UiInputField.InputSelected
Initial value:
= delegate
    {
    }
Definition at line 23 of file UiInputField.cs.
Referenced by OnSelect().
OnSubmitEvent
Action UiInputField.OnSubmitEvent
Initial value:
= delegate
    {
    }
Definition at line 19 of file UiInputField.cs.
Referenced by OnEndEdit().
The documentation for this class was generated from the following file:
Elin/Plugins.UI/UiInputField.cs