Elin Decompiled Documentation: WidgetQuestTracker Class Reference
WidgetQuestTracker Class Reference
Public Member Functions
override void OnActivate ()
void Refresh ()
Public Member Functions inherited from Widget
void Test ()
bool IsInRightMode ()
void Activate ()
void RefreshOrder ()
virtual void OnActivate ()
virtual object CreateExtra ()
void Deactivate ()
virtual void OnDeactivate ()
void Close ()
void Reactivate ()
virtual void OnManagerActivate ()
virtual void OnManagerDeactivate ()
void SetAnchor (RectPosition p)
void SetPivot (RectPosition p)
virtual void OnChangePivot ()
void UpdateConfig ()
virtual void OnUpdateConfig ()
void ClampToScreen ()
virtual void OnChangeResolution ()
void OnChangePosition ()
virtual void OnChangeActionMode ()
virtual void OnFlip ()
bool IsAlignTop ()
Layer AddLayer (Layer l, Transform trans)
void RefreshTipPivotPosition ()
SkinSet GetSkin ()
SkinConfig GetSkinConfig ()
void SetSkin (int id, int v=0)
void TestSkin ()
virtual void ApplySkin ()
virtual void OnApplySkin ()
void InstantiateDeco (SkinDeco deco)
void AddDeco (SkinDeco deco)
void RemoveDeco (SkinDeco deco)
virtual bool CanShowContextMenu ()
void ShowContextMenu ()
void SetBaseContextMenu (UIContextMenu m)
virtual void OnSetContextMenu (UIContextMenu m)
void SetGridContextMenu (UIContextMenu m)
void SoundActivate ()
void OnChangeResolution ()
SkinSet GetSkin ()
SkinConfig GetSkinConfig ()
Static Public Member Functions
static void Show ()
static bool TryShow ()
Static Public Member Functions inherited from EMono
static int rnd (int a)
Public Attributes
List< ItemQuestTracker > items
ItemQuestTracker mold
LayoutGroup layout
Public Attributes inherited from Widget
Image imageBG
SoundData soundActivate
UIDragPanel dragPanel
RectTransform tipPivotLeft
RectTransform tipPivotRight
Static Public Attributes
static WidgetQuestTracker Instance
Static Public Attributes inherited from EMono
static Core core
Private Member Functions
void OnEnable ()
void OnDisable ()
Additional Inherited Members
Public Types inherited from Widget
enum WidgetType { Default , ZoomMenu }
enum State { Active , Inactive }
Protected Member Functions inherited from Widget
void ClampToScreenEnsured (Component c, Vector2 anchoredPos)
void ClampToScreen (RectTransform rect, float margin=10f)
Protected Attributes inherited from Widget
bool flip
Properties inherited from Widget
string ID [get]
Config config [get]
SkinRoot skinRoot [get]
bool IsSealed [get]
virtual bool ShowStyleMenu [get]
virtual bool AlwaysTop [get]
virtual bool IsStaticPosition [get]
virtual bool AlwaysBottom [get]
virtual Type SetSiblingAfter [get]
virtual bool ShowInBuildMode [get]
virtual bool RightClickToClose [get]
virtual bool AllowRightClickToClose [get]
Properties inherited from EMono
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SoundManager Sound [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static CoreDebug debug [get]
Detailed Description
Definition at line 4 of file WidgetQuestTracker.cs.
Member Function Documentation
OnActivate()
override void WidgetQuestTracker.OnActivate () inline virtual
Reimplemented from Widget.
Definition at line 24 of file WidgetQuestTracker.cs.
    {
        Instance = this;
        Refresh();
    }
References Instance, and Refresh().
OnDisable()
void WidgetQuestTracker.OnDisable () inline private
Definition at line 19 of file WidgetQuestTracker.cs.
    {
        CancelInvoke();
    }
OnEnable()
void WidgetQuestTracker.OnEnable () inline private
Definition at line 14 of file WidgetQuestTracker.cs.
    {
        InvokeRepeating("Refresh", 0.5f, 0.5f);
    }
Refresh()
void WidgetQuestTracker.Refresh () inline
Definition at line 30 of file WidgetQuestTracker.cs.
    {
        if (EMono.game == null || (bool)LayerDrama.Instance)
        {
            return;
        }
        foreach (Quest item in EMono.game.quests.list)
        {
            if (!item.track)
            {
                continue;
            }
            ItemQuestTracker itemQuestTracker = null;
            foreach (ItemQuestTracker item2 in items)
            {
                if (item2.quest == item)
                {
                    itemQuestTracker = item2;
                    break;
                }
            }
            if (!(itemQuestTracker != null))
            {
                itemQuestTracker = Util.Instantiate(mold, layout);
                itemQuestTracker.SetActive(enable: false);
                itemQuestTracker.quest = item;
                items.Add(itemQuestTracker);
            }
        }
        items.ForeachReverse(delegate(ItemQuestTracker i)
        {
            i.Refresh();
        });
        this.RebuildLayout();
        if (items.Count == 0)
        {
            EMono.ui.widgets.DeactivateWidget(this);
        }
        else
        {
            EMono.player.questTracker = true;
        }
    }
References EMono.game, LayerDrama.Instance, item, items, layout, QuestManager.list, mold, ItemQuestTracker.quest, Game.quests, ItemQuestTracker.Refresh(), EMono.ui, and Util.
Referenced by OnActivate(), ContentQuest.OnSwitchContent(), and Recipe.ToggleTrack().
Show()
static void WidgetQuestTracker.Show () inline static
Definition at line 74 of file WidgetQuestTracker.cs.
    {
        if (!EMono.ui.widgets.GetWidget("QuestTracker"))
        {
            EMono.ui.widgets.Toggle("QuestTracker");
        }
    }
References EMono.ui.
Referenced by QuestManager.Start().
TryShow()
static bool WidgetQuestTracker.TryShow () inline static
Definition at line 82 of file WidgetQuestTracker.cs.
    {
        bool flag = false;
        foreach (Quest item in EMono.game.quests.list)
        {
            if (item.track)
            {
                flag = true;
            }
        }
        if (flag || (bool)EMono.ui.widgets.GetWidget("QuestTracker"))
        {
            EMono.ui.widgets.Toggle("QuestTracker")?.SoundActivate();
            return false;
        }
        if (!EMono.ui.GetLayer<LayerJournal>())
        {
            EMono.ui.ToggleLayer<LayerJournal>().SwitchContent(0, 0);
        }
        return true;
    }
References EMono.game, item, QuestManager.list, Game.quests, and EMono.ui.
Referenced by HotItemWidget.OnClick().
Member Data Documentation
Instance
WidgetQuestTracker WidgetQuestTracker.Instance static
Definition at line 6 of file WidgetQuestTracker.cs.
Referenced by ItemQuestTracker.Kill(), OnActivate(), ContentQuest.OnSwitchContent(), and Recipe.ToggleTrack().
items
List<ItemQuestTracker> WidgetQuestTracker.items
Definition at line 8 of file WidgetQuestTracker.cs.
Referenced by ItemQuestTracker.Kill(), and Refresh().
layout
LayoutGroup WidgetQuestTracker.layout
Definition at line 12 of file WidgetQuestTracker.cs.
Referenced by Refresh().
mold
ItemQuestTracker WidgetQuestTracker.mold
Definition at line 10 of file WidgetQuestTracker.cs.
Referenced by Refresh().
The documentation for this class was generated from the following file:
Elin/WidgetQuestTracker.cs