Elin Decompiled Documentation: EloPos Class Reference
EloPos Class Reference
Public Attributes
Zone zone
EloMap.Cell cell
EloMap.TileInfo tile
int gx
int gy
Properties
EloMap elomap [get]
EloMapActor actor [get]
bool IInspect. CanInspect [get]
string IInspect. InspectName [get]
Point IInspect. InspectPoint [get]
Vector3 IInspect. InspectPosition [get]
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Properties inherited from IInspect
bool CanInspect [get]
string InspectName [get]
Point InspectPoint [get]
Vector3 InspectPosition [get]
Private Member Functions
void IInspect. OnInspect ()
void IInspect. WriteNote (UINote n, Action< UINote > onWriteNote=null, IInspect.NoteMode mode=IInspect.NoteMode.Default, Recipe recipe=null)
Additional Inherited Members
Public Types inherited from IInspect
enum NoteMode { Default , Recipe , Product , Info }
void WriteNote (UINote n, Action< UINote > onWriteNote=null, NoteMode mode=NoteMode.Default, Recipe recipe=null)
void OnInspect ()
Static Public Member Functions inherited from EClass
static int rndSeed (int a, int seed)
static int rnd (long a)
static int rnd (int a)
static int curve (int a, int start, int step, int rate=75)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Static Public Attributes inherited from EClass
static Core core
Detailed Description
Definition at line 4 of file EloPos.cs.
Member Function Documentation
OnInspect()
void IInspect. EloPos.OnInspect () inline private
Implements IInspect.
Definition at line 28 of file EloPos.cs.
    {
    }
WriteNote()
void IInspect. EloPos.WriteNote (UINote n, Action< UINote > onWriteNote = null, IInspect::NoteMode mode = IInspect::NoteMode::Default, Recipe recipe = null) inline private
Implements IInspect.
Definition at line 32 of file EloPos.cs.
    {
        n.Clear();
        UIItem uIItem = n.AddHeaderCard(zone.Name);
        uIItem.image2.sprite = tile.sprite;
        uIItem.image2.SetNativeSize();
        n.AddHeaderTopic("mainFaction".lang());
        n.AddText(zone.mainFaction.name);
        n.Space();
        n.AddHeaderTopic("listRoamers".lang());
        int num = 0;
        foreach (Chara value in EClass.game.cards.globalCharas.Values)
        {
            if (value.currentZone == zone)
            {
                n.AddText(value.Name);
                num++;
                if (num > 5)
                {
                    break;
                }
            }
        }
        if (num == 0)
        {
            n.AddText("????????");
        }
        n.Build();
    }
References UINote.AddHeaderCard(), UINote.AddHeaderTopic(), UINote.AddText(), UINote.Build(), Game.cards, UINote.Clear(), Chara.currentZone, EClass.game, CardManager.globalCharas, UIItem.image2, Spatial.mainFaction, Card.Name, Faction.name, Spatial.Name, UINote.Space(), tile, and zone.
Member Data Documentation
cell
EloMap.Cell EloPos.cell
Definition at line 8 of file EloPos.cs.
gx
int EloPos.gx
Definition at line 12 of file EloPos.cs.
gy
int EloPos.gy
Definition at line 14 of file EloPos.cs.
tile
EloMap.TileInfo EloPos.tile
Definition at line 10 of file EloPos.cs.
Referenced by WriteNote().
zone
Zone EloPos.zone
Definition at line 6 of file EloPos.cs.
Referenced by WriteNote().
Property Documentation
actor
EloMapActor EloPos.actor get
Definition at line 18 of file EloPos.cs.
CanInspect
bool IInspect. EloPos.CanInspect get private
Implements IInspect.
Definition at line 20 of file EloPos.cs.
elomap
EloMap EloPos.elomap get
Definition at line 16 of file EloPos.cs.
InspectName
string IInspect. EloPos.InspectName get private
Implements IInspect.
Definition at line 22 of file EloPos.cs.
InspectPoint
Point IInspect. EloPos.InspectPoint get private
Implements IInspect.
Definition at line 24 of file EloPos.cs.
InspectPosition
Vector3 IInspect. EloPos.InspectPosition get private
Implements IInspect.
Definition at line 26 of file EloPos.cs.
The documentation for this class was generated from the following file:
Elin/EloPos.cs