Elin Decompiled Documentation: Area Class Reference
Area Class Reference
Public Member Functions
virtual void OnLoad ()
void AddPoint (Point point, bool onLoad=false)
void RemovePoint (Point point)
virtual void OnRemovePoint (Point point)
virtual void OnInstallCard (Card t)
virtual void OnUninstallCard (Card t)
void OnHoverArea (MeshPass pass)
virtual byte GetTile (int index)
virtual void Update ()
void OnRemove ()
Public Member Functions inherited from BaseArea
Point GetRandomFreePos ()
Thing GetEmptySeat ()
virtual Point GetRandomPoint (bool walkable=true, bool allowChara=true)
void ChangeType (string _id)
void SetRandomName (int seed=-1)
string GetRandomName (int seed=-1)
HashSet< string > ListRoomNames ()
int GetSortVal (UIList.SortMode m)
List< Interaction > ListInteractions ()
void OnInspect ()
void WriteNote (UINote n, Action< UINote > onWriteNote=null, IInspect.NoteMode mode=IInspect.NoteMode.Default, Recipe recipe=null)
void WriteNote (UINote n, Action< UINote > onWriteNote=null, NoteMode mode=NoteMode.Default, Recipe recipe=null)
void OnInspect ()
Static Public Member Functions
static Area Create (string id)
Static Public Member Functions inherited from EClass
static int rndSeed (int a, int seed)
static int rnd (long a)
static int rnd (int a)
static int curve (int a, int start, int step, int rate=75)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Public Attributes
TaskList< Task > taskList = new TaskList<Task>()
bool isDestroyed
Public Attributes inherited from BaseArea
int uid
PointList points = new PointList()
AreaData data = new AreaData()
AreaType type = new AreaTypeRoom()
TraitRoomPlate plate
Properties
virtual bool isListable [get]
virtual bool AutoTask [get]
RoomManager manager [get]
Properties inherited from BaseArea
virtual string Name [get]
bool IsPrivate [get]
SourceArea.Row source [get]
bool CanInspect [get]
string InspectName [get]
Point InspectPoint [get]
Vector3 InspectPosition [get]
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Properties inherited from IInspect
bool CanInspect [get]
string InspectName [get]
Point InspectPoint [get]
Vector3 InspectPosition [get]
Additional Inherited Members
Public Types inherited from BaseArea
enum AccessType { Public , Resident , Private }
Public Types inherited from IInspect
enum NoteMode { Default , Recipe , Product , Info }
Static Public Attributes inherited from EClass
static Core core
Detailed Description
Definition at line 3 of file Area.cs.
Member Function Documentation
AddPoint()
void Area.AddPoint (Point point, bool onLoad = false) inline
Definition at line 27 of file Area.cs.
    {
        if (!onLoad)
        {
            points.Add(point);
        }
        point.cell.GetOrCreateDetail().area = this;
    }
References CellDetail.area, Point.cell, Cell.GetOrCreateDetail(), and BaseArea.points.
Referenced by RoomManager.AddArea(), OnLoad(), AM_ExpandArea.OnProcessTiles(), and RoomManager.TryAddArea().
Create()
static Area Area.Create (string id) inline static
Definition at line 104 of file Area.cs.
    {
        Area area = new Area();
        area.ChangeType(id);
        EClass._map.rooms.AssignUID(area);
        return area;
    }
References EClass._map, RoomManager.AssignUID(), BaseArea.ChangeType(), and Map.rooms.
Referenced by AM_CreateArea.CreateNew(), BuildMenu.RefreshCategoryArea(), and RoomManager.TryAddArea().
GetTile()
virtual byte Area.GetTile (int index) inline virtual
Definition at line 75 of file Area.cs.
    {
        return 33;
    }
Referenced by BaseTileMap.DrawTile(), and TileMapElona.DrawTile().
OnHoverArea()
void Area.OnHoverArea (MeshPass pass) inline
Definition at line 67 of file Area.cs.
    {
        foreach (Point point in points)
        {
            pass.Add(point, (EClass.scene.actionMode.AreaHihlight == AreaHighlightMode.Edit) ? 34 : 33);
        }
    }
References Scene.actionMode, ActionMode.AreaHihlight, BaseArea.points, and EClass.scene.
Referenced by BaseTileSelector.OnUpdate().
OnInstallCard()
virtual void Area.OnInstallCard (Card t) inline virtual
Definition at line 59 of file Area.cs.
    {
    }
Referenced by Card.SetPlaceState().
OnLoad()
virtual void Area.OnLoad () inline virtual
Definition at line 16 of file Area.cs.
    {
        foreach (Point point in points)
        {
            AddPoint(point, onLoad: true);
        }
        taskList.OnLoad();
        type.owner = this;
        manager.mapIDs.Add(uid, this);
    }
References AddPoint(), manager, RoomManager.mapIDs, TaskList< T >.OnLoad(), BaseArea.points, taskList, and BaseArea.uid.
OnRemove()
void Area.OnRemove () inline
Definition at line 84 of file Area.cs.
    {
        if (isDestroyed)
        {
            return;
        }
        isDestroyed = true;
        Task[] array = taskList.items.ToArray();
        for (int i = 0; i < array.Length; i++)
        {
            array[i].Destroy();
        }
        foreach (Point point in points)
        {
            OnRemovePoint(point);
            point.detail.area = null;
            point.cell.TryDespawnDetail();
        }
    }
References Point.cell, Task.Destroy(), isDestroyed, TaskList< T >.items, OnRemovePoint(), BaseArea.points, taskList, and Cell.TryDespawnDetail().
Referenced by RoomManager.RemoveArea().
OnRemovePoint()
virtual void Area.OnRemovePoint (Point point) inline virtual
Definition at line 55 of file Area.cs.
    {
    }
Referenced by OnRemove(), and RemovePoint().
OnUninstallCard()
virtual void Area.OnUninstallCard (Card t) inline virtual
Definition at line 63 of file Area.cs.
    {
    }
Referenced by Card.SetPlaceState().
RemovePoint()
void Area.RemovePoint (Point point) inline
Definition at line 36 of file Area.cs.
    {
        if (points.Count <= 1)
        {
            return;
        }
        foreach (Point point2 in points)
        {
            if (point2.Equals(point))
            {
                OnRemovePoint(point2);
                points.Remove(point2);
                point.detail.area = null;
                point.cell.TryDespawnDetail();
                break;
            }
        }
    }
References Point.cell, Point.Equals(), OnRemovePoint(), BaseArea.points, and Cell.TryDespawnDetail().
Referenced by AM_ExpandArea.OnProcessTiles().
Update()
virtual void Area.Update () inline virtual
Definition at line 80 of file Area.cs.
    {
    }
Member Data Documentation
isDestroyed
bool Area.isDestroyed
Definition at line 8 of file Area.cs.
Referenced by OnRemove(), and GoalTask.TryAssignTask().
taskList
TaskList<Task> Area.taskList = new TaskList<Task>()
Definition at line 6 of file Area.cs.
Referenced by OnLoad(), OnRemove(), and GoalTask.TryAssignAreaTask().
Property Documentation
AutoTask
virtual bool Area.AutoTask get
Definition at line 12 of file Area.cs.
isListable
virtual bool Area.isListable get
Definition at line 10 of file Area.cs.
manager
RoomManager Area.manager get
Definition at line 14 of file Area.cs.
Referenced by OnLoad().
The documentation for this class was generated from the following file:
Elin/Area.cs