Elin Decompiled Documentation: Applibot.OutlineImage Class Reference
Applibot.OutlineImage Class Reference
Public Member Functions
void Capture ()
Public Member Functions inherited from Applibot.CustomImageBase
Material GetModifiedMaterial (Material baseMaterial)
void DestroyMaterial ()
Protected Member Functions
override void UpdateMaterial (Material baseMaterial)
Protected Member Functions inherited from Applibot.CustomImageBase
virtual void UpdateMaterial (Material baseMaterial)
void OnEnable ()
void OnDisable ()
void OnDestroy ()
Private Member Functions
void Awake ()
Private Attributes
Color _outlineColor = Color.white
Image _image
bool _isStatic
int _OutlineColor = Shader.PropertyToID("_OutlineColor")
readonly int _SrcFactor = Shader.PropertyToID("_SrcFactor")
readonly int _DstFactor = Shader.PropertyToID("_DstFactor")
Additional Inherited Members
Protected Attributes inherited from Applibot.CustomImageBase
Material material
Properties inherited from Applibot.CustomImageBase
CanvasScaler canvasScaler [get]
Graphic graphic [get]
Detailed Description
Definition at line 6 of file OutlineImage.cs.
Member Function Documentation
Awake()
void Applibot.OutlineImage.Awake () inline private
Definition at line 53 of file OutlineImage.cs.
    {
        _image = base.graphic as Image;
        if (Application.isPlaying && _isStatic)
        {
            Capture();
        }
    }
References Applibot.OutlineImage._image, Applibot.OutlineImage._isStatic, and Applibot.OutlineImage.Capture().
Capture()
void Applibot.OutlineImage.Capture () inline
Definition at line 62 of file OutlineImage.cs.
    {
        UpdateMaterial(null);
        material.SetInt(_SrcFactor, 1);
        material.SetInt(_DstFactor, 0);
        if (TryGetComponent<RawImage>(out var component))
        {
            Texture mainTexture = base.graphic.mainTexture;
            float width = (base.transform as RectTransform).rect.width;
            float height = (base.transform as RectTransform).rect.height;
            RenderTexture renderTexture = new RenderTexture((int)width, (int)height, 0, RenderTextureFormat.ARGBHalf);
            Graphics.Blit(mainTexture, renderTexture, material);
            component.texture = renderTexture;
            DestroyMaterial();
            base.enabled = false;
        }
    }
References Applibot.OutlineImage._DstFactor, Applibot.OutlineImage._SrcFactor, Applibot.CustomImageBase.DestroyMaterial(), Applibot.CustomImageBase.material, and Applibot.OutlineImage.UpdateMaterial().
Referenced by Applibot.OutlineImage.Awake().
UpdateMaterial()
override void Applibot.OutlineImage.UpdateMaterial (Material baseMaterial) inline protected virtual
Reimplemented from Applibot.CustomImageBase.
Definition at line 23 of file OutlineImage.cs.
    {
        if (material == null)
        {
            Shader shader = Shader.Find("Applibot/UI/Outline");
            material = new Material(shader);
        }
        material.SetColor(_OutlineColor, _outlineColor);
        material.SetInt(_SrcFactor, 5);
        material.SetInt(_DstFactor, 10);
        if (base.canvasScaler != null)
        {
            Vector2 referenceResolution = base.canvasScaler.referenceResolution;
            Vector2 one = Vector2.one;
            if (_image != null && _image.sprite.packed)
            {
                Rect textureRect = _image.sprite.textureRect;
                one = new Vector2(textureRect.width, textureRect.height);
            }
            else
            {
                Texture mainTexture = base.graphic.mainTexture;
                one = new Vector2(mainTexture.width, mainTexture.height);
            }
            float x = one.x / referenceResolution.x;
            float y = one.y / referenceResolution.y;
            material.SetVector("_scaleFactor", new Vector4(x, y));
        }
    }
References Applibot.OutlineImage._DstFactor, Applibot.OutlineImage._image, Applibot.OutlineImage._outlineColor, Applibot.OutlineImage._OutlineColor, Applibot.OutlineImage._SrcFactor, Material, and Applibot.CustomImageBase.material.
Referenced by Applibot.OutlineImage.Capture().
Member Data Documentation
_DstFactor
readonly int Applibot.OutlineImage._DstFactor = Shader.PropertyToID("_DstFactor") private
Definition at line 21 of file OutlineImage.cs.
Referenced by Applibot.OutlineImage.Capture(), and Applibot.OutlineImage.UpdateMaterial().
_image
Image Applibot.OutlineImage._image private
Definition at line 12 of file OutlineImage.cs.
Referenced by Applibot.OutlineImage.Awake(), and Applibot.OutlineImage.UpdateMaterial().
_isStatic
bool Applibot.OutlineImage._isStatic private
Definition at line 15 of file OutlineImage.cs.
Referenced by Applibot.OutlineImage.Awake().
_outlineColor
Color Applibot.OutlineImage._outlineColor = Color.white private
Definition at line 10 of file OutlineImage.cs.
Referenced by Applibot.OutlineImage.UpdateMaterial().
_OutlineColor
int Applibot.OutlineImage._OutlineColor = Shader.PropertyToID("_OutlineColor") private
Definition at line 17 of file OutlineImage.cs.
Referenced by Applibot.OutlineImage.UpdateMaterial().
_SrcFactor
readonly int Applibot.OutlineImage._SrcFactor = Shader.PropertyToID("_SrcFactor") private
Definition at line 19 of file OutlineImage.cs.
Referenced by Applibot.OutlineImage.Capture(), and Applibot.OutlineImage.UpdateMaterial().
The documentation for this class was generated from the following file:
Elin/Plugins.UI/Applibot/OutlineImage.cs