Elin Decompiled Documentation: CharaGen Class Reference
CharaGen Class Reference
Static Public Member Functions
static Chara _Create (string id, int idMat=-1, int lv=-1)
static Chara Create (string id, int lv=-1)
static Chara CreateFromFilter (string id, int lv=-1, int levelRange=-1)
static Chara CreateFromFilter (SpawnList list, int lv=-1, int levelRange=-1)
static Chara CreateFromElement (string idEle, int lv=-1, string idFilter="chara")
static Chara CreateWealthy (int lv=-1)
Static Public Member Functions inherited from EClass
static int rndSeed (int a, int seed)
static int rnd (int a)
static int curve (int a, int start, int step, int rate=75)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Static Public Attributes
static int objLv
Static Public Attributes inherited from EClass
static Core core
Additional Inherited Members
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Detailed Description
Definition at line 1 of file CharaGen.cs.
Member Function Documentation
_Create()
static Chara CharaGen._Create (string id, int idMat = -1, int lv = -1) inline static
Definition at line 5 of file CharaGen.cs.
    {
        Chara chara = new Chara();
        if (lv < 1)
        {
            lv = 1;
        }
        objLv = lv;
        chara.Create(id, idMat, lv);
        return chara;
    }
References Card.Create(), and objLv.
Referenced by Create().
Create()
static Chara CharaGen.Create (string id, int lv = -1) inline static
Definition at line 17 of file CharaGen.cs.
    {
        return _Create(id, -1, lv);
    }
References _Create().
Referenced by InvOwnerChaosOffering._OnProcess(), Game.AddAdventurer(), Game.AddAdventurers(), Zone.AddChara(), ZoneUtil.AddMerchant(), RecipeCard.Build(), ZoneEventSiegeGuard.CreateChara(), CreateFromFilter(), RecipeCard.CreateMold(), Chara.CreateReplacement(), Chara.Die(), LayerGachaResult.Draw(), Chara.Duplicate(), ZonePreEnterEncounter.Execute(), DramaOutcome.fiama_pet1(), DramaOutcome.fiama_pet2(), DramaOutcome.fiama_pet3(), DramaOutcome.fiama_pet4(), CoreDebug.Fix_EtherDisease(), DNA.Generate(), FortuneRollData.GetPrize(), TraitFoodEggFertilized.Incubate(), Zone_WindRest.OnAfterSimulate(), Zone_Nymelle.OnBeforeSimulate(), QuestIntroInspector.OnComplete(), QuestVernis.OnComplete(), Player.OnCreateGame(), TraitDrinkMilkMother.OnDrink(), QuestDialog.OnDropReward(), Zone_DungeonPuppy.OnGenerateMap(), GrowSystemTree.OnHitFail(), TraitDiary.OnRead(), TraitGiftNewYear.OnUse(), ZoneEventMusic.OnVisit(), TraitContainer.Open(), ActEffect.ProcAt(), CoreDebug.QuickStart(), SerializedCards.Restore(), Meeting.SetChara(), AM_MoveInstalled.SetTarget(), Zone.Simulate(), CoreDebug.Spawn(), Zone.SpawnAltar(), Game.StartNewGame(), Zone.TryGenerateBigDaddy(), Religion.TryGetGift(), SlaverData.TryRefresh(), Zone.TrySpawnFollower(), and CoreDebug.UpdateInput().
CreateFromElement()
static Chara CharaGen.CreateFromElement (string idEle, int lv = -1, string idFilter = "chara") inline static
Definition at line 32 of file CharaGen.cs.
    {
        SpawnList spawnList = SpawnListChara.Get("chara_ele" + idEle, delegate(SourceChara.Row c)
        {
            string[] mainElement = c.mainElement;
            for (int i = 0; i < mainElement.Length; i++)
            {
                if (mainElement[i].Split(',')[0] == idEle)
                {
                    return true;
                }
            }
            return false;
        });
        CardBlueprint.Set(new CardBlueprint
        {
            idEle = idEle
        });
        return Create(spawnList.Select(lv).id, lv);
    }
References SpawnListChara.Get().
Referenced by ActEffect.ProcAt().
CreateFromFilter() [1/2]
static Chara CharaGen.CreateFromFilter (SpawnList list, int lv = -1, int levelRange = -1) inline static
Definition at line 27 of file CharaGen.cs.
    {
        return Create(list.Select(lv, levelRange).id, lv);
    }
References Create(), CardRow.id, and SpawnList.Select().
CreateFromFilter() [2/2]
static Chara CharaGen.CreateFromFilter (string id, int lv = -1, int levelRange = -1) inline static
Definition at line 22 of file CharaGen.cs.
    {
        return CreateFromFilter(SpawnList.Get(id), lv, levelRange);
    }
References CreateFromFilter(), and SpawnList.Get().
Referenced by ZoneUtil.AddBandits(), Zone.AddRandomVisitor(), Zone.ClaimZone(), ZoneEventDefenseGame.CreateChara(), ZoneEventSiege.CreateChara(), CreateFromFilter(), Chara.Die(), ZonePreEnterBout.Execute(), ZonePreEnterEncounter.Execute(), Region.OnAdvanceHour(), QuestEscort.OnStart(), ZoneEventMusic.OnVisit(), ActEffect.ProcAt(), TraitBaseSpellbook.ReadFailEffect(), and SerializedCards.Restore().
CreateWealthy()
static Chara CharaGen.CreateWealthy (int lv = -1) inline static
Definition at line 53 of file CharaGen.cs.
    {
        return CreateFromFilter(SpawnListChara.Get("c_wealthy", (SourceChara.Row r) => r.works.Contains("Rich") || r.hobbies.Contains("Rich")), lv);
    }
References SpawnListChara.Get().
Member Data Documentation
objLv
int CharaGen.objLv static
Definition at line 3 of file CharaGen.cs.
Referenced by _Create().
The documentation for this class was generated from the following file:
Elin/CharaGen.cs