Elin Decompiled Documentation: LayerSkinDeco Class Reference
LayerSkinDeco Class Reference
Public Member Functions
override void OnInit ()
void SetWidget (Widget _widget)
override void OnUpdateInput ()
void Activate (SkinDecoActor actor)
override void OnKill ()
Public Member Functions inherited from ELayer
override void OnBeforeAddLayer ()
void InitInspector ()
sealed override void Init ()
override void OnAfterAddLayer ()
void TryShowHelp ()
void AddLayerToUI (string id)
void TryShowHint (string _langHint=null)
void TalkHomeMemeber (string id)
void TalkMaid (string id)
override void OnRightClick ()
Public Member Functions inherited from Layer
virtual string GetTextHeader (Window window)
virtual bool HeaderIsListOf (int id)
virtual void Init ()
virtual void OnInit ()
virtual void OnAfterInit ()
virtual void ApplySkin ()
void ShowScreenLock (string id)
void UpdateInput ()
virtual void OnUpdateInput ()
virtual void OnRightClick ()
virtual bool OnBack ()
virtual void OnChangeLayer ()
virtual void OnCreate ()
void _AddLayer (string id)
Layer AddLayer (string id)
T AddLayer< T > ()
T AddLayer< T > (string id)
T AddLayerDontCloseOthers< T > ()
Layer AddLayerDontCloseOthers (Layer l)
T GetOrAddLayer< T > ()
virtual void OnBeforeAddLayer ()
virtual void OnAfterAddLayer ()
Layer AddLayer (Layer l)
void ToggleLayer (string id)
T ToggleLayer< T > (string id=null)
void WaitAndClose ()
void OnClickClose ()
virtual void Close ()
void CloseLayers ()
void RemoveLayers (bool removeImportant=false)
bool RemoveLayer< T > ()
void RemoveLayer (Layer l)
virtual void OnKill ()
Layer SetOnKill (Action action)
void DisableClose ()
void Delay (float duration=0.05f)
Layer SetDelay (float d)
Layer GetLayer (string id)
T GetLayer< T > (bool fromTop=false)
Layer GetTopLayer ()
void SwitchContent (int idWindow, int i)
virtual void OnSwitchContent (Window window)
Layer SetTitles (string langList, string idHeaderRow=null)
bool IsBlockWidgetClick ()
bool IsHideHud ()
bool IsAllowGeneralInput ()
bool IsUseBlur ()
bool IsPointerOnLayer ()
void ApplySkin ()
Public Attributes
Widget widget
Transform widgetHolder
Public Attributes inherited from Layer
Option option
UnityEvent onKill
Anime animeIn
Anime animeOut
bool closeOthers
bool defaultActionMode = true
Button screenLock
Layer parent
string idLayer
List< Layer > layers = new List<Layer>()
Vector2 lastParentPos
List< Window > windows = new List<Window>()
string langHint
Properties
List< SkinDeco > decos [get]
SkinConfig cfg [get]
Properties inherited from ELayer
static Core core [get]
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static FactionBranch Branch [get]
static Faction Home [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static CoreConfig config [get]
static GameSetting setting [get]
static ColorProfile Colors [get]
static SourceManager sources [get]
static World world [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
bool IsFloat [get]
virtual string IdHelp [get]
Properties inherited from Layer
Layer TopLayer [get]
string uid [get]
virtual RectTransform rectLayers [get]
virtual bool blockWidgetClick [get]
Additional Inherited Members
Static Public Member Functions inherited from ELayer
static int rnd (int a)
Static Public Member Functions inherited from Layer
static T Create< T > ()
static T Create< T > (string path)
static Layer Create (string path)
Static Public Attributes inherited from Layer
static int skipInput
static bool closeOnRightClick
static bool rightClicked
static bool cancelKeyDown
static bool ignoreSounds
static Transform blurStopInstance
static string[] searchPath = new string[3] { "Layer", "Layer/Dialog", "Layer/LayerHome" }
Protected Member Functions inherited from ELayer
sealed override void _Close ()
sealed override void Kill ()
Protected Member Functions inherited from Layer
virtual void Awake ()
virtual void _Close ()
virtual void Kill ()
Protected Attributes inherited from Layer
RectTransform _rect
bool isDestroyed
Detailed Description
Definition at line 5 of file LayerSkinDeco.cs.
Member Function Documentation
Activate()
void LayerSkinDeco.Activate (SkinDecoActor actor) inline
Definition at line 137 of file LayerSkinDeco.cs.
    {
        actor.image.raycastTarget = true;
        actor.transform.SetParent(base.transform, worldPositionStays: true);
        UIDragPanel uIDragPanel = actor.gameObject.AddComponent<UIDragPanel>();
        uIDragPanel.target = actor.Rect();
        uIDragPanel.bound = actor.Rect();
        uIDragPanel.clamp = false;
    }
Referenced by OnUpdateInput(), and SetWidget().
OnInit()
override void LayerSkinDeco.OnInit () inline virtual
Reimplemented from Layer.
Definition at line 16 of file LayerSkinDeco.cs.
    {
        base.OnInit();
    }
OnKill()
override void LayerSkinDeco.OnKill () inline virtual
Reimplemented from Layer.
Definition at line 147 of file LayerSkinDeco.cs.
    {
        widget.transform.SetParent(ELayer.ui.widgets.transform, worldPositionStays: false);
        widget.RefreshOrder();
        foreach (SkinDeco deco in decos)
        {
            SkinDecoActor actor = deco.actor;
            actor.image.raycastTarget = false;
            UnityEngine.Object.DestroyImmediate(actor.gameObject.GetComponent<UIDragPanel>());
            actor.transform.SetParent(widget.transform, worldPositionStays: true);
            deco.x = (int)actor.Rect().anchoredPosition.x;
            deco.y = (int)actor.Rect().anchoredPosition.y;
            actor.Refresh();
        }
    }
References SkinDeco.actor, decos, SkinDecoActor.Refresh(), Widget.RefreshOrder(), ELayer.ui, and widget.
OnUpdateInput()
override void LayerSkinDeco.OnUpdateInput () inline virtual
Reimplemented from Layer.
Definition at line 31 of file LayerSkinDeco.cs.
    {
        if (EInput.leftMouse.clicked)
        {
            if (EInput.leftMouse.dragging)
            {
                return;
            }
            SkinDecoActor selected = InputModuleEX.GetComponentOf<SkinDecoActor>();
            Vector3 clickPos = Input.mousePosition;
            UIContextMenu i = ELayer.ui.CreateContextMenu();
            if ((bool)selected)
            {
                SkinDeco deco = selected.owner;
                i.AddButton("editColor", delegate
                {
                    ELayer.ui.AddLayer<LayerColorPicker>().SetColor(deco.color, Color.white, delegate(PickerState state, Color _c)
                    {
                        deco.color = _c;
                        selected.Refresh();
                    });
                });
                i.AddButton("bringToTop", delegate
                {
                    decos.Remove(deco);
                    decos.Add(deco);
                    selected.transform.SetAsLastSibling();
                });
                i.AddSlider("rotation", (float n) => (n * 45f).ToString() ?? "", deco.rz, delegate(float a)
                {
                    deco.rz = (int)a;
                    selected.Refresh();
                }, 0f, 7f, isInt: true);
                i.AddSlider("size", (float n) => n.ToString() ?? "", Mathf.Abs(deco.sx), delegate(float a)
                {
                    deco.sx = (int)a * ((deco.sx > 0) ? 1 : (-1));
                    deco.sy = (int)a * ((deco.sy > 0) ? 1 : (-1));
                    selected.Refresh();
                }, 10f, 400f, isInt: true);
                i.AddToggle("shadow", deco.shadow, delegate(bool a)
                {
                    deco.shadow = a;
                    selected.Refresh();
                });
                i.AddToggle("reverse", deco.reverse, delegate(bool a)
                {
                    deco.reverse = a;
                    selected.Refresh();
                });
                i.AddToggle("placeBeforeWidget", deco.bottom, delegate(bool a)
                {
                    deco.bottom = a;
                    selected.Refresh();
                });
                i.AddButton("removeDeco", delegate
                {
                    widget.RemoveDeco(selected.owner);
                });
            }
            else
            {
                UIContextMenu uIContextMenu = i.AddChild("addDeco");
                UIList uIList = Util.Instantiate<UIList>("UI/Element/List/ListImageGrid", uIContextMenu);
                uIList.callbacks = new UIList.Callback<Sprite, UIButton>
                {
                    onInstantiate = delegate(Sprite a, UIButton _b)
                    {
                        _b.icon.sprite = a;
                    },
                    onClick = delegate(Sprite a, UIButton _b)
                    {
                        SkinDeco skinDeco = new SkinDeco
{
                            sx = 100,
                            sy = 100,
                            color = Color.white
                        };
                        skinDeco.id = int.Parse(a.name.Remove(0, 4));
                        widget.AddDeco(skinDeco);
                        SkinDecoActor actor = skinDeco.actor;
                        Activate(actor);
                        actor.transform.position = clickPos;
                        EInput.Consume();
                        i.Hide();
                    }
                };
                Sprite[] array = Resources.LoadAll<Sprite>("Media/Graphics/Deco/");
                foreach (Sprite o in array)
                {
                    uIList.Add(o);
                }
                uIList.Refresh();
            }
            i.Show();
        }
        if (EInput.rightMouse.down)
        {
            UIContextMenu uIContextMenu2 = ELayer.ui.CreateContextMenu();
            uIContextMenu2.AddButton("quitEdit", delegate
            {
                Close();
            });
            uIContextMenu2.Show();
        }
    }
References Activate(), SkinDeco.actor, UIContextMenu.AddButton(), UIContextMenu.AddChild(), Widget.AddDeco(), UIContextMenu.AddSlider(), UIContextMenu.AddToggle(), SkinDeco.bottom, ButtonState.clicked, Layer.Close(), Color, SkinDeco.color, EInput.Consume(), decos, ButtonState.down, ButtonState.dragging, UIContextMenu.Hide(), EInput.leftMouse, SkinDecoActor.owner, SkinDecoActor.Refresh(), Widget.RemoveDeco(), SkinDeco.reverse, EInput.rightMouse, SkinDeco.rz, SkinDeco.shadow, UIContextMenu.Show(), SkinDeco.sx, SkinDeco.sy, ELayer.ui, Util, and widget.
SetWidget()
void LayerSkinDeco.SetWidget (Widget _widget) inline
Definition at line 21 of file LayerSkinDeco.cs.
    {
        widget = _widget;
        foreach (SkinDeco deco in decos)
        {
            Activate(deco.actor);
        }
        widget.transform.SetParent(widgetHolder, worldPositionStays: false);
    }
References Activate(), SkinDeco.actor, decos, widget, and widgetHolder.
Member Data Documentation
widget
Widget LayerSkinDeco.widget
Definition at line 8 of file LayerSkinDeco.cs.
Referenced by OnKill(), OnUpdateInput(), and SetWidget().
widgetHolder
Transform LayerSkinDeco.widgetHolder
Definition at line 10 of file LayerSkinDeco.cs.
Referenced by SetWidget().
Property Documentation
cfg
SkinConfig LayerSkinDeco.cfg get
Definition at line 14 of file LayerSkinDeco.cs.
decos
List<SkinDeco> LayerSkinDeco.decos get
Definition at line 12 of file LayerSkinDeco.cs.
Referenced by OnKill(), OnUpdateInput(), and SetWidget().
The documentation for this class was generated from the following file:
Elin/LayerSkinDeco.cs