Elin Decompiled Documentation: TCOrbitChara Class Reference
TCOrbitChara Class Reference
Public Member Functions
override void OnSetOwner ()
override void Refresh ()
void RefreshAll ()
virtual void Refresh ()
Public Member Functions inherited from TC
void SetOwner (CardRenderer r)
virtual void OnSetOwner ()
virtual void OnDraw (ref Vector3 pos)
void Kill ()
virtual void OnKill ()
Public Attributes
GameObject goIcon
SpriteRenderer iconRelation
SpriteRenderer iconStatus
SpriteRenderer barHP
SpriteRenderer bgHP
SpriteRenderer barHP2
SpriteRenderer bgHP2
new Chara owner
Public Attributes inherited from TC
CardRenderer render
Private Attributes
float timer
bool showHP
bool showIcon
bool showHP2
Additional Inherited Members
Static Public Member Functions inherited from EMono
static int rnd (int a)
Static Public Attributes inherited from TC
static GameSetting.RenderSetting.TCSetting _setting
Static Public Attributes inherited from EMono
static Core core
Properties inherited from TC
Card owner [get]
virtual bool isUI [get]
virtual Vector3 FixPos [get]
Properties inherited from EMono
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SoundManager Sound [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static CoreDebug debug [get]
Detailed Description
Definition at line 3 of file TCOrbitChara.cs.
Member Function Documentation
OnSetOwner()
override void TCOrbitChara.OnSetOwner () inline virtual
Reimplemented from TC.
Definition at line 29 of file TCOrbitChara.cs.
    {
        owner = base.owner as Chara;
        RenderData data = owner.renderer.data;
        goIcon.transform.SetLocalPositionY(data.offset.y + data.size.y + 0.32f);
        RefreshAll();
    }
References RenderObject.data, goIcon, RenderData.offset, owner, RefreshAll(), Card.renderer, and RenderData.size.
Refresh()
override void TCOrbitChara.Refresh () inline virtual
Reimplemented from TCOrbit.
Definition at line 37 of file TCOrbitChara.cs.
    {
        timer += Time.deltaTime;
        if (timer > 0.2f)
        {
            timer = 0f;
            RefreshAll();
        }
        if ((!owner.isHidden || EMono.pc.CanSee(owner)) && (showHP || showHP2 || showIcon))
        {
            if (!base.gameObject.activeSelf)
            {
                base.gameObject.SetActive(value: true);
            }
            base.transform.position = owner.renderer.position;
        }
        else if (base.gameObject.activeSelf)
        {
            base.gameObject.SetActive(value: false);
        }
    }
References Chara.CanSee(), Card.isHidden, owner, EMono.pc, CardRenderer.position, RefreshAll(), Card.renderer, showHP, showHP2, showIcon, and timer.
RefreshAll()
void TCOrbitChara.RefreshAll () inline
Definition at line 59 of file TCOrbitChara.cs.
    {
        showHP = (showHP2 = (showIcon = false));
        if (owner.isDead || owner.host != null)
        {
            return;
        }
        _ = owner.ai;
        _ = EMono.core.refs.orbitIcons;
        Emo2 emo = owner.emoIcon;
        if (emo == Emo2.none)
        {
            if (owner.isRestocking && (!owner.IsPCParty || EMono._zone.IsPCFaction) && owner.trait.GetRestockedIcon() != 0 && !(EMono._zone is Zone_Dungeon))
            {
                emo = owner.trait.GetRestockedIcon();
            }
            else
            {
                bool flag = false;
                if (owner.quest != null && EMono.game.quests.list.Contains(owner.quest))
                {
                    flag = true;
                }
                else if (owner.IsUnique)
                {
                    string id = owner.id;
                    if (!(id == "ashland"))
                    {
                        if (id == "fiama")
{
                            if (EMono.game.quests.GetPhase<QuestMain>() >= 200 && EMono.player.dialogFlags.TryGetValue("fiama1", 0) == 0)
{
                                flag = true;
                            }
                            else if (EMono.pc.homeBranch != null)
{
                                foreach (Chara member in EMono.pc.homeBranch.members)
{
                                    if (member.isDead && member.GetInt(100) != 0)
{
                                        flag = true;
                                        break;
                                    }
                                }
                            }
                        }
                    }
                    else
                    {
                        int phase = EMono.game.quests.GetPhase<QuestMain>();
                        if ((phase == 0 && EMono.player.dialogFlags.TryGetValue("ash1", 0) == 0) || phase == 200)
{
                            flag = true;
                        }
                    }
                }
                if (flag)
                {
                    emo = Emo2.hint;
                }
            }
        }
        if (EMono.player.currentHotItem.Thing != null && EMono.player.currentHotItem.Thing.trait.GetHeldEmo(owner) != 0)
        {
            emo = EMono.player.currentHotItem.Thing.trait.GetHeldEmo(owner);
        }
        showIcon = emo != Emo2.none;
        if (showIcon)
        {
            iconStatus.sprite = EMono.core.refs.spritesEmo[(int)emo];
        }
        iconStatus.SetActive(showIcon);
        float num = (float)owner.hp / (float)owner.MaxHP;
        showHP = num < 0.9f && (owner.IsPCParty || owner.IsHostile() || (owner.enemy != null && owner.enemy.IsPCParty));
        if (showHP)
        {
            barHP.transform.SetLocalScaleX(Mathf.Max(0f, num));
            barHP.SetActive(enable: true);
            bgHP.SetActive(enable: true);
        }
        else
        {
            barHP.SetActive(enable: false);
            bgHP.SetActive(enable: false);
        }
        if ((bool)barHP2)
        {
            float num2 = Mathf.Min(1f, (owner.parasite != null) ? ((float)owner.parasite.hp / (float)owner.parasite.MaxHP) : 1f, (owner.ride != null) ? ((float)owner.ride.hp / (float)owner.ride.MaxHP) : 1f);
            showHP2 = num2 < 0.9f;
            if (showHP2)
            {
                barHP2.transform.SetLocalScaleX(Mathf.Max(0f, num2));
                barHP2.SetActive(enable: true);
                bgHP2.SetActive(enable: true);
            }
            else
            {
                barHP2.SetActive(enable: false);
                bgHP2.SetActive(enable: false);
            }
        }
    }
References EMono._zone, Chara.ai, barHP, barHP2, bgHP, bgHP2, EMono.core, Player.currentHotItem, Player.dialogFlags, Chara.emoIcon, Chara.enemy, EMono.game, Trait.GetHeldEmo(), BaseCard.GetInt(), Trait.GetRestockedIcon(), Chara.homeBranch, Chara.host, Card.hp, iconStatus, Card.id, Chara.isDead, Chara.IsHostile(), Zone.IsPCFaction, Chara.IsPCParty, Card.isRestocking, Card.IsUnique, QuestManager.list, Chara.MaxHP, FactionBranch.members, CoreRef.orbitIcons, owner, Chara.parasite, EMono.pc, EMono.player, Chara.quest, Game.quests, Core.refs, Chara.ride, showHP, showHP2, showIcon, CoreRef.spritesEmo, HotItem.Thing, Card.trait, and Chara.trait.
Referenced by OnSetOwner(), and Refresh().
Member Data Documentation
barHP
SpriteRenderer TCOrbitChara.barHP
Definition at line 11 of file TCOrbitChara.cs.
Referenced by RefreshAll().
barHP2
SpriteRenderer TCOrbitChara.barHP2
Definition at line 15 of file TCOrbitChara.cs.
Referenced by RefreshAll().
bgHP
SpriteRenderer TCOrbitChara.bgHP
Definition at line 13 of file TCOrbitChara.cs.
Referenced by RefreshAll().
bgHP2
SpriteRenderer TCOrbitChara.bgHP2
Definition at line 17 of file TCOrbitChara.cs.
Referenced by RefreshAll().
goIcon
GameObject TCOrbitChara.goIcon
Definition at line 5 of file TCOrbitChara.cs.
Referenced by OnSetOwner().
iconRelation
SpriteRenderer TCOrbitChara.iconRelation
Definition at line 7 of file TCOrbitChara.cs.
iconStatus
SpriteRenderer TCOrbitChara.iconStatus
Definition at line 9 of file TCOrbitChara.cs.
Referenced by RefreshAll().
owner
new Chara TCOrbitChara.owner
Definition at line 19 of file TCOrbitChara.cs.
Referenced by OnSetOwner(), Refresh(), and RefreshAll().
showHP
bool TCOrbitChara.showHP private
Definition at line 23 of file TCOrbitChara.cs.
Referenced by Refresh(), and RefreshAll().
showHP2
bool TCOrbitChara.showHP2 private
Definition at line 27 of file TCOrbitChara.cs.
Referenced by Refresh(), and RefreshAll().
showIcon
bool TCOrbitChara.showIcon private
Definition at line 25 of file TCOrbitChara.cs.
Referenced by Refresh(), and RefreshAll().
timer
float TCOrbitChara.timer private
Definition at line 21 of file TCOrbitChara.cs.
Referenced by Refresh().
The documentation for this class was generated from the following file:
Elin/TCOrbitChara.cs