Elin Decompiled Documentation: ContentConfig Class Reference
ContentConfig Class Reference
Public Member Functions
void SetSlider (Slider slider, float value, Func< float, string > action)
Public Member Functions inherited from UIContent
virtual void OnSwitchContent (int idTab)
virtual void OnInstantiate ()
Public Member Functions inherited from UINote
void Clear ()
void Build ()
void Space (int sizeY=0, int sizeX=1)
UINote AddNote (string id)
UIItem AddHeader (string text, Sprite sprite=null)
UIItem AddHeaderCard (string text, Sprite sprite=null)
UIItem AddHeaderTopic (string text, Sprite sprite=null)
UIItem AddHeader (string id, string text, Sprite sprite=null)
UIItem AddText (string text, FontColor color=FontColor.DontChange)
UIItem AddText (string id, string text, FontColor color=FontColor.DontChange)
UIItem AddText (string id, string text, Color color)
UIItem AddItem (string id)
UIItem AddTopic (string id, string text, string value=null)
UIItem AddTopic (string text, string value=null)
void AddImage (Sprite sprite)
void AddImage (string idFile)
UIButton AddButton (string text, Action onClick)
UIButton AddButtonLink (string text, string url)
UIDropdown AddDropdown (string id="DropdownDefault")
UIButton AddToggle (string idLang="", bool isOn=false, Action< bool > action=null)
Transform AddPrefab (string path)
T AddExtra< T > (string path)
Properties
CoreConfig config [get]
Additional Inherited Members
Public Attributes inherited from UINote
RectTransform target
UINoteProfile prof
SkinType skinType
string idDefaultText
LayoutGroup layout
RectTransform cur
bool extraRebuild
Detailed Description
Definition at line 4 of file ContentConfig.cs.
Member Function Documentation
SetSlider()
void ContentConfig.SetSlider (Slider slider, float value, Func< float, string > action) inline
Definition at line 8 of file ContentConfig.cs.
    {
        slider.onValueChanged.RemoveAllListeners();
        slider.onValueChanged.AddListener(delegate(float a)
        {
            slider.GetComponentInChildren<UIText>(includeInactive: true).text = action(a);
        });
        slider.value = value;
        slider.GetComponentInChildren<UIText>(includeInactive: true).text = action(value);
    }
Referenced by ContentConfigGame.OnInstantiate(), ContentConfigInput.OnInstantiate(), ContentConfigOther.OnInstantiate(), and ContentConfigTest.OnInstantiate().
Property Documentation
config
CoreConfig ContentConfig.config get
Definition at line 6 of file ContentConfig.cs.
The documentation for this class was generated from the following file:
Elin/ContentConfig.cs