Elin Decompiled Documentation: SourceMaterial Class Reference
SourceMaterial Class Reference
Classes
class Row
class Tier
class TierList
Public Member Functions
override Row CreateRow ()
override Row CreateRowByMapping (IReadOnlyDictionary< string, int > mapping)
override void SetRow (Row r)
override IReadOnlyDictionary< string, int > GetRowMapping ()
override IReadOnlyDictionary< string, string > GetTypeMapping ()
override void OnInit ()
override void OnAfterImportData ()
void OnImportRow (Row r)
Public Member Functions inherited from SourceDataInt< SourceMaterial.Row >
override T GetRow (string id)
Static Public Attributes
static readonly IReadOnlyDictionary< string, int > RowMapping
static readonly IReadOnlyDictionary< string, string > TypeMapping
static Dictionary< string, TierList > tierMap = new Dictionary<string, TierList>()
Properties
override string[] ImportFields [get]
Detailed Description
Definition at line 6 of file SourceMaterial.cs.
Member Function Documentation
CreateRow()
override Row SourceMaterial.CreateRow () inline
Definition at line 404 of file SourceMaterial.cs.
    {
        return new Row
        {
            id = SourceData.GetInt(0),
            alias = SourceData.GetString(1),
            name_JP = SourceData.GetString(2),
            name = SourceData.GetString(3),
            category = SourceData.GetString(4),
            tag = SourceData.GetStringArray(5),
            thing = SourceData.GetString(6),
            goods = SourceData.GetStringArray(7),
            minerals = SourceData.GetStringArray(8),
            decal = SourceData.GetInt(9),
            decay = SourceData.GetInt(10),
            grass = SourceData.GetInt(11),
            defFloor = SourceData.GetInt(12),
            defBlock = SourceData.GetInt(13),
            edge = SourceData.GetInt(14),
            ramp = SourceData.GetInt(15),
            idSound = SourceData.GetString(16),
            soundFoot = SourceData.GetString(17),
            hardness = SourceData.GetInt(18),
            groups = SourceData.GetStringArray(19),
            tier = SourceData.GetInt(20),
            chance = SourceData.GetInt(21),
            weight = SourceData.GetInt(22),
            value = SourceData.GetInt(23),
            quality = SourceData.GetInt(24),
            atk = SourceData.GetInt(25),
            dmg = SourceData.GetInt(26),
            dv = SourceData.GetInt(27),
            pv = SourceData.GetInt(28),
            dice = SourceData.GetInt(29),
            bits = SourceData.GetStringArray(30),
            elements = Core.ParseElements(SourceData.GetStr(31)),
            altName = SourceData.GetStringArray(32),
            altName_JP = SourceData.GetStringArray(33)
        };
    }
References SourceData< T, T2 >.GetInt(), SourceData< T, T2 >.GetStr(), SourceData< T, T2 >.GetString(), SourceData< T, T2 >.GetStringArray(), and Core.ParseElements().
CreateRowByMapping()
override Row SourceMaterial.CreateRowByMapping (IReadOnlyDictionary< string, int > mapping) inline
Definition at line 445 of file SourceMaterial.cs.
    {
        return new Row
        {
            id = SourceData.GetInt(mapping["id"]),
            alias = SourceData.GetString(mapping["alias"]),
            name_JP = SourceData.GetString(mapping["name_JP"]),
            name = SourceData.GetString(mapping["name"]),
            category = SourceData.GetString(mapping["category"]),
            tag = SourceData.GetStringArray(mapping["tag"]),
            thing = SourceData.GetString(mapping["thing"]),
            goods = SourceData.GetStringArray(mapping["goods"]),
            minerals = SourceData.GetStringArray(mapping["minerals"]),
            decal = SourceData.GetInt(mapping["decal"]),
            decay = SourceData.GetInt(mapping["decay"]),
            grass = SourceData.GetInt(mapping["grass"]),
            defFloor = SourceData.GetInt(mapping["defFloor"]),
            defBlock = SourceData.GetInt(mapping["defBlock"]),
            edge = SourceData.GetInt(mapping["edge"]),
            ramp = SourceData.GetInt(mapping["ramp"]),
            idSound = SourceData.GetString(mapping["idSound"]),
            soundFoot = SourceData.GetString(mapping["soundFoot"]),
            hardness = SourceData.GetInt(mapping["hardness"]),
            groups = SourceData.GetStringArray(mapping["groups"]),
            tier = SourceData.GetInt(mapping["tier"]),
            chance = SourceData.GetInt(mapping["chance"]),
            weight = SourceData.GetInt(mapping["weight"]),
            value = SourceData.GetInt(mapping["value"]),
            quality = SourceData.GetInt(mapping["quality"]),
            atk = SourceData.GetInt(mapping["atk"]),
            dmg = SourceData.GetInt(mapping["dmg"]),
            dv = SourceData.GetInt(mapping["dv"]),
            pv = SourceData.GetInt(mapping["pv"]),
            dice = SourceData.GetInt(mapping["dice"]),
            bits = SourceData.GetStringArray(mapping["bits"]),
            elements = Core.ParseElements(SourceData.GetStr(mapping["elements"])),
            altName = SourceData.GetStringArray(mapping["altName"]),
            altName_JP = SourceData.GetStringArray(mapping["altName_JP"])
        };
    }
References SourceData< T, T2 >.GetInt(), SourceData< T, T2 >.GetStr(), SourceData< T, T2 >.GetString(), SourceData< T, T2 >.GetStringArray(), and Core.ParseElements().
GetRowMapping()
override IReadOnlyDictionary< string, int > SourceMaterial.GetRowMapping () inline
Definition at line 491 of file SourceMaterial.cs.
    {
        return RowMapping;
    }
References RowMapping.
GetTypeMapping()
override IReadOnlyDictionary< string, string > SourceMaterial.GetTypeMapping () inline
Definition at line 496 of file SourceMaterial.cs.
    {
        return TypeMapping;
    }
References TypeMapping.
OnAfterImportData()
override void SourceMaterial.OnAfterImportData () inline
Definition at line 546 of file SourceMaterial.cs.
    {
        rows.Sort((Row a, Row b) => a.id - b.id);
    }
References SourceMaterial.Row.id.
OnImportRow()
void SourceMaterial.OnImportRow (Row r) inline
Definition at line 551 of file SourceMaterial.cs.
    {
        List<int> list = new List<int>(r.elements);
        for (int i = 0; i < r.elements.Length; i += 2)
        {
            Add(r.elements[i], r.elements[i + 1]);
        }
        Add(13, r.hardness);
        r.elements = list.ToArray();
        void Add(int ele, int a)
        {
            list.Add(ele);
            list.Add(a);
        }
    }
References SourceMaterial.Row.elements, and SourceMaterial.Row.hardness.
OnInit()
override void SourceMaterial.OnInit () inline
Definition at line 501 of file SourceMaterial.cs.
    {
        Cell.matList = rows;
        tierMap.Clear();
        tierMap.Add("gem", new TierList());
        tierMap.Add("ore", new TierList());
        foreach (Row row in rows)
        {
            row.Init();
            row.elementMap = Element.GetElementMap(row.elements);
            if (!row.groups.IsEmpty())
            {
                string[] groups = row.groups;
                foreach (string key in groups)
                {
                    TierList tierList = tierMap.TryGetValue(key);
                    if (tierList == null)
                    {
                        tierList = new TierList();
                        tierMap[key] = tierList;
                    }
                    Tier obj = tierList.tiers[row.tier];
                    obj.list.Add(row);
                    obj.sum += row.chance;
                }
            }
            string category = row.category;
            if (!(category == "gem"))
            {
                if (category == "ore")
                {
                    Tier obj2 = tierMap["ore"].tiers[row.tier];
                    obj2.list.Add(row);
                    obj2.sum += row.chance;
                }
            }
            else
            {
                Tier obj3 = tierMap["gem"].tiers[row.tier];
                obj3.list.Add(row);
                obj3.sum += row.chance;
            }
        }
    }
References SourceMaterial.Row.category, SourceMaterial.Row.chance, SourceMaterial.Row.elements, Element.GetElementMap(), SourceMaterial.Row.groups, SourceMaterial.Row.Init(), SourceMaterial.Tier.list, SourceMaterial.Row.tier, tierMap, and SourceMaterial.TierList.tiers.
SetRow()
override void SourceMaterial.SetRow (Row r) inline
Definition at line 486 of file SourceMaterial.cs.
    {
        map[r.id] = r;
    }
References SourceMaterial.Row.id.
Member Data Documentation
RowMapping
readonly IReadOnlyDictionary<string, int> SourceMaterial.RowMapping static
Definition at line 324 of file SourceMaterial.cs.
Referenced by GetRowMapping().
tierMap
Dictionary<string, TierList> SourceMaterial.tierMap = new Dictionary<string, TierList>() static
Definition at line 400 of file SourceMaterial.cs.
Referenced by MATERIAL.GetRandomMaterial(), OnInit(), and ActEffect.Proc().
TypeMapping
readonly IReadOnlyDictionary<string, string> SourceMaterial.TypeMapping static
Definition at line 362 of file SourceMaterial.cs.
Referenced by GetTypeMapping().
Property Documentation
ImportFields
override string [] SourceMaterial.ImportFields get
Definition at line 402 of file SourceMaterial.cs.
The documentation for this class was generated from the following file:
Elin/SourceMaterial.cs