Elin Decompiled Documentation: TraitShrine Class Reference
TraitShrine Class Reference
Public Member Functions
override void OnCreate (int lv)
override void _OnUse (Chara c)
override void OnRenderExtra (RenderParam p)
SourceMaterial.Row GetMaterial ()
override string GetName ()
Public Member Functions inherited from TraitPowerStatue
override void OnCreate (int lv)
override bool CanUse (Chara c)
override bool OnUse (Chara c)
virtual void _OnUse (Chara c)
virtual bool IsImplemented ()
Public Member Functions inherited from TraitItem
override bool CanUse (Chara c)
override void WriteNote (UINote n, bool identified)
Public Member Functions inherited from Trait
string GetParam (int i, string def=null)
int GetParamInt (int i, int def)
virtual bool Contains (RecipeSource r)
virtual int GetValue ()
virtual bool CanStackTo (Thing to)
virtual string GetHoverText ()
virtual Action GetHealAction (Chara c)
virtual bool CanBlend (Thing t)
virtual void OnBlend (Thing t, Chara c)
virtual int GetActDuration (Chara c)
virtual SourceElement.Row GetRefElement ()
virtual Sprite GetRefSprite ()
virtual void OnRenderExtra (RenderParam p)
virtual Emo2 GetHeldEmo (Chara c)
virtual void SetOwner (Card _owner)
virtual bool IdleUse (Chara c, int dist)
virtual void OnSetOwner ()
virtual void OnImportMap ()
virtual void SetParams (params string[] s)
virtual void OnCrafted (Recipe recipe, List< Thing > ings)
virtual void OnCreate (int lv)
virtual void OnEquip (Chara c, bool onSetOwner)
virtual void OnUnequip (Chara c)
virtual void OnChangePlaceState (PlaceState state)
virtual void OnAddedToZone ()
virtual void OnRemovedFromZone ()
virtual void OnSimulateHour (VirtualDate date)
virtual string GetName ()
virtual void SetName (ref string s)
virtual void OnRenderTile (Point point, HitResult result, int dir)
virtual int CompareTo (Card b)
virtual bool CanBuiltAt (Point p)
virtual void Update ()
Point GetPoint ()
Point GetRandomPoint (Func< Point, bool > func=null, Chara accessChara=null)
virtual List< Point > ListPoints (Point center=null, bool onlyPassable=true)
virtual Recipe GetRecipe ()
virtual Recipe GetBuildModeRecipe ()
virtual bool CanCook (Card c)
void CookProgress ()
virtual bool CanOffer (Card tg)
void OfferProcess (Chara cc)
void Offer (Chara cc)
virtual bool TryProgress (AIProgress p)
virtual LockOpenState TryOpenLock (Chara cc, bool msgFail=true)
virtual void WriteNote (UINote n, bool identified)
int GetSortVal (UIList.SortMode m)
virtual HotItem GetHotItem ()
virtual bool CanRead (Chara c)
virtual void OnRead (Chara c)
virtual bool CanEat (Chara c)
virtual void OnEat (Chara c)
virtual bool CanDrink (Chara c)
virtual void OnDrink (Chara c)
virtual void OnThrowGround (Chara c, Point p)
virtual bool CanUse (Chara c)
virtual bool CanUse (Chara c, Card tg)
virtual bool CanUse (Chara c, Point p)
virtual bool OnUse (Chara c)
virtual bool OnUse (Chara c, Card tg)
virtual bool OnUse (Chara c, Point p)
virtual void TrySetAct (ActPlan p)
virtual void TrySetHeldAct (ActPlan p)
virtual void OnHeld ()
virtual void OnTickHeld ()
virtual void OnSetCurrentItem ()
virtual void OnUnsetCurrentItem ()
virtual bool OnChildDecay (Card c, bool firstDecay)
virtual bool CanChildDecay (Card c)
virtual void OnSetCardGrid (ButtonGrid b)
virtual void OnStepped (Chara c)
virtual void OnSteppedOut (Chara c)
virtual void OnOpenDoor (Chara c)
void Install (bool byPlayer)
void Uninstall ()
virtual void OnInstall (bool byPlayer)
virtual void OnUninstall ()
virtual void TryToggle ()
virtual void Toggle (bool on, bool silent=false)
virtual void PlayToggleEffect (bool silent)
virtual void OnToggle ()
virtual void TrySetToggleAct (ActPlan p)
bool IsFuelEnough (int num=1, List< Thing > excludes=null, bool tryRefuel=true)
bool IsFuel (string s)
bool IsFuel (Thing t)
int GetFuelValue (Thing t)
int GetFuelValue (string id)
void Refuel (Thing t)
void TryRefuel (int dest, List< Thing > excludes)
virtual void OnEnterScreen ()
virtual void RefreshRenderer ()
virtual void SetMainText (UIText t, bool hotitem)
virtual bool CanCopy (Thing t)
string GetTextRestock (string lang, bool pet)
Emo2 GetRestockedIcon ()
void OnBarter (bool reroll=false)
Thing CreateStock ()
Public Attributes
SourceMaterial.Row mat
Public Attributes inherited from Trait
Card owner
Properties
ShrineData Shrine [get]
override bool RenderExtra [get]
Properties inherited from TraitPowerStatue
override bool CanBeDestroyed [get]
override bool CanBeStolen [get]
override bool CanBeTeleported [get]
override bool CanUseFromInventory [get]
override bool UseExtra [get]
override bool CanStack [get]
Properties inherited from TraitItem
virtual bool CanUseFromInventory [get]
virtual bool CanUseInUserZone [get]
Properties inherited from Trait
string[] Params [get]
virtual byte WeightMod [get]
virtual int IdSkin [get]
virtual string Name [get]
virtual TileType tileType [get]
virtual RefCardName RefCardName [get]
virtual bool IsBlockPath [get]
virtual bool IsBlockSight [get]
virtual bool IsDoor [get]
virtual bool IsOpenSight [get]
virtual bool IsOpenPath [get]
virtual bool IsFloating [get]
virtual bool IsNoShop [get]
virtual bool IsGround [get]
virtual bool IsOnlyUsableByPc [get]
virtual bool InvertHeldSprite [get]
virtual bool IsChangeFloorHeight [get]
virtual bool ShouldRefreshTile [get]
virtual bool ShouldTryRefreshRoom [get]
virtual int InstallBottomPriority [get]
virtual bool CanHarvest [get]
virtual int radius [get]
virtual TraitRadiusType radiusType [get]
virtual bool CanUseRoomRadius [get]
virtual int GuidePriotiy [get]
virtual int Electricity [get]
virtual bool IgnoreLastStackHeight [get]
virtual int Decay [get]
virtual int DecaySpeed [get]
virtual int DecaySpeedChild [get]
virtual bool IsFridge [get]
virtual int DefaultStock [get]
virtual bool HoldAsDefaultInteraction [get]
virtual int CraftNum [get]
virtual bool ShowOrbit [get]
virtual bool HaveUpdate [get]
virtual bool IsSpot [get]
virtual bool IsFactory [get]
virtual bool CanAutofire [get]
virtual bool CanName [get]
virtual bool CanPutAway [get]
virtual bool CanChangeHeight [get]
virtual bool CanStack [get]
virtual bool CanCopyInBlueprint [get]
virtual bool CanBeAttacked [get]
virtual bool CanBeTeleported [get]
virtual bool CanExtendBuild [get]
virtual string langNote [get]
virtual string IDInvStyle [get]
virtual string IDActorEx [get]
virtual bool MaskOnBuild [get]
virtual bool ShowContextOnPick [get]
virtual bool IsThrowMainAction [get]
virtual bool LevelAsQuality [get]
virtual bool UseDummyTile [get]
virtual bool RequireFullStackCheck [get]
virtual bool DisableAutoCombat [get]
virtual InvGridSize InvGridSize [get]
virtual bool IsContainer [get]
virtual bool CanUseContent [get]
virtual bool CanSearchContent [get]
virtual bool CanOpenContainer [get]
virtual bool IsSpecialContainer [get]
virtual ContainerType ContainerType [get]
virtual ThrowType ThrowType [get]
virtual EffectDead EffectDead [get]
virtual bool IsHomeItem [get]
virtual bool IsAltar [get]
virtual bool IsRestSpot [get]
virtual bool CanBeMasked [get]
virtual bool IsLocalAct [get]
virtual bool IsBlendBase [get]
virtual bool CanBeOnlyBuiltInHome [get]
virtual bool CanBuildInTown [get]
virtual bool CanBeHeld [get]
virtual bool CanBeStolen [get]
virtual bool CanOnlyCarry [get]
virtual bool CanBeDestroyed [get]
virtual bool CanBeSmashedToDeath [get]
virtual bool CanBeHallucinated [get]
virtual bool CanBeDropped [get]
virtual string ReqHarvest [get]
virtual bool CanBeDisassembled [get]
virtual bool CanBeShipped [get]
virtual bool HasCharges [get]
virtual bool ShowCharges [get]
virtual bool ShowChildrenNumber [get]
virtual bool ShowAsTool [get]
virtual bool CanBeHeldAsFurniture [get]
virtual bool HideInAdv [get]
virtual bool NoHeldDir [get]
virtual bool AlwaysHideOnLowWall [get]
bool ExistsOnMap [get]
virtual bool RenderExtra [get]
virtual float DropChance [get]
virtual string IdNoRestock [get]
virtual int IdleUseChance [get]
virtual string RecipeCat [get]
virtual bool IsTool [get]
virtual string LangUse [get]
virtual bool IgnoreOnSteppedWhenMoving [get]
virtual bool IsOn [get]
virtual bool IsAnimeOn [get]
bool IsToggle [get]
virtual bool AutoToggle [get]
bool IsLighting [get]
virtual bool IsLightOn [get]
virtual bool IsNightOnlyLight [get]
virtual TileMode tileMode [get]
virtual bool UseAltTiles [get]
virtual bool UseLowblock [get]
virtual bool UseExtra [get]
virtual bool UseLightColor [get]
virtual ? Color ColorExtra [get]
virtual int MaxFuel [get]
virtual int FuelCost [get]
virtual bool ShowFuelWindow [get]
bool IsRequireFuel [get]
string IdToggleExtra [get]
virtual ToggleType ToggleType [get]
virtual string IdSoundToggleOn [get]
virtual string IdSoundToggleOff [get]
virtual int ShopLv [get]
virtual CopyShopType CopyShop [get]
virtual int NumCopyItem [get]
virtual ShopType ShopType [get]
virtual CurrencyType CurrencyType [get]
virtual PriceType PriceType [get]
virtual bool AllowSell [get]
virtual int CostRerollShop [get]
virtual bool AllowCriminal [get]
virtual int RestockDay [get]
virtual SlaverType SlaverType [get]
virtual string LangBarter [get]
virtual bool RemoveGlobalOnBanish [get]
string TextNextRestock [get]
string TextNextRestockPet [get]
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Additional Inherited Members
Public Types inherited from Trait
enum TileMode {
Default , Door , Illumination , DefaultNoAnime ,
SignalAnime , FakeBlock
}
enum CopyShopType { None , Item , Spellbook }
Static Public Member Functions inherited from EClass
static int rndSeed (int a, int seed)
static int rnd (long a)
static int rnd (int a)
static int curve (int a, int start, int step, int rate=75)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Static Public Attributes inherited from Trait
static TraitSelfFactory SelfFactory = new TraitSelfFactory()
Static Public Attributes inherited from EClass
static Core core
Static Protected Attributes inherited from Trait
static List< Point > listRadiusPoints = new List<Point>()
Detailed Description
Definition at line 1 of file TraitShrine.cs.
Member Function Documentation
_OnUse()
override void TraitShrine._OnUse (Chara c) inline virtual
Reimplemented from TraitPowerStatue.
Definition at line 30 of file TraitShrine.cs.
    {
        Point point = (owner.ExistsOnMap ? owner.pos : EClass.pc.pos);
        switch (Shrine.id)
        {
        case "material":
            ActEffect.Proc(EffectId.ChangeMaterial, EClass.pc, null, 100, new ActRef
            {
                n1 = GetMaterial().alias
            });
            break;
        case "armor":
        {
            bool flag = mat.alias == "gold";
            ActEffect.Proc(flag ? EffectId.EnchantArmorGreat : EffectId.EnchantArmor, 100, flag ? BlessedState.Blessed : BlessedState.Normal, EClass.pc);
            break;
        }
        case "replenish":
        {
            foreach (Chara member in EClass.pc.party.members)
            {
                member.hp = member.MaxHP;
                member.mana.value = member.mana.max;
                member.stamina.Mod(member.stamina.max / 3);
                if (!member.IsPC)
                {
                    member.stamina.value = member.stamina.max;
                }
                member.PlayEffect("revive");
                member.Say("heal_light", member);
                foreach (Condition item in member.conditions.Copy())
                {
                    if (item.Type == ConditionType.Debuff && !item.IsKilled)
                    {
                        member.Say("removeHex", member, item.Name.ToLower());
                        item.Kill();
                    }
                }
            }
            break;
        }
        case "strife":
        {
            for (int i = 0; i < 3 + EClass.rnd(2); i++)
            {
                EClass._zone.SpawnMob(point.GetNearestPoint(allowBlock: false, allowChara: false), (i == 0) ? SpawnSetting.Boss(owner.LV) : SpawnSetting.DefenseEnemy(owner.LV))?.PlayEffect("teleport");
            }
            break;
        }
        case "knowledge":
        {
            Thing t2 = ThingGen.Create((EClass.rnd(3) == 0) ? "book_skill" : "book_ancient", -1, owner.LV);
            EClass._zone.AddCard(t2, point);
            break;
        }
        case "invention":
            EClass.player.recipes.ComeUpWithRandomRecipe(null, 10);
            break;
        case "item":
        {
            Thing t = ThingGen.Create("water");
            EClass._zone.AddCard(t, point);
            break;
        }
        }
    }
References EClass._zone, Zone.AddCard(), SpawnSetting.Boss(), RecipeManager.ComeUpWithRandomRecipe(), Chara.conditions, ThingGen.Create(), SpawnSetting.DefenseEnemy(), GetMaterial(), Point.GetNearestPoint(), ShrineData.id, Chara.IsPC, item, Card.LV, Chara.mana, Stats.max, Chara.MaxHP, Party.members, Stats.Mod(), Trait.owner, Chara.party, EClass.pc, Card.PlayEffect(), EClass.player, Card.pos, ActEffect.Proc(), Player.recipes, EClass.rnd(), Card.Say(), Shrine, Zone.SpawnMob(), and Chara.stamina.
GetMaterial()
SourceMaterial.Row TraitShrine.GetMaterial () inline
Definition at line 109 of file TraitShrine.cs.
    {
        if (mat != null)
        {
            return mat;
        }
        Rand.SetSeed(owner.c_seed);
        if (Shrine.id == "armor")
        {
            mat = EClass.sources.materials.alias[(EClass.rnd(5) == 0) ? "gold" : "granite"];
        }
        else
        {
            mat = MATERIAL.GetRandomMaterial(owner.LV / 3, (EClass.rnd(2) == 0) ? "metal" : "leather");
        }
        Rand.SetSeed();
        return mat;
    }
References MATERIAL.GetRandomMaterial(), SourceManager.materials, EClass.rnd(), Rand.SetSeed(), and EClass.sources.
Referenced by _OnUse().
GetName()
override string TraitShrine.GetName () inline virtual
Reimplemented from Trait.
Definition at line 128 of file TraitShrine.cs.
    {
        string @ref = "";
        if (Shrine.id == "material")
        {
            @ref = GetMaterial().GetName().ToTitleCase();
        }
        return ("shrine_" + Shrine.id).lang(@ref);
    }
OnCreate()
override void TraitShrine.OnCreate (int lv) inline virtual
Reimplemented from TraitPowerStatue.
Definition at line 23 of file TraitShrine.cs.
    {
        base.OnCreate(lv);
        owner.refVal = EClass.gamedata.shrines.IndexOf(EClass.gamedata.shrines.RandomItemWeighted((ShrineData a) => a.chance));
        owner.idSkin = Shrine.skin;
    }
References ShrineData.chance, EClass.gamedata, Shrine, GameData.shrines, and ShrineData.skin.
OnRenderExtra()
override void TraitShrine.OnRenderExtra (RenderParam p) inline virtual
Reimplemented from Trait.
Definition at line 97 of file TraitShrine.cs.
    {
        PaintPosition paintPosition = EClass.setting.render.paintPos.TryGetValue("shrine");
        int num = 1;
        p.x += paintPosition.pos.x * (float)num;
        p.y += paintPosition.pos.y;
        p.z += paintPosition.pos.z;
        p.tile = EClass.core.refs.renderers.objs_shrine.ConvertTile(Shrine.tile) * num;
        p.matColor = BaseTileMap.GetColorInt(ref GetMaterial().matColor, 100);
        EClass.core.refs.renderers.objs_shrine.Draw(p);
    }
References RenderData.ConvertTile(), EClass.core, RenderData.Draw(), BaseTileMap.GetColorInt(), CoreRef.Renderers.objs_shrine, GameSetting.RenderSetting.paintPos, PaintPosition.pos, Core.refs, GameSetting.render, CoreRef.renderers, EClass.setting, and UDictionary< TKey, TValue >.TryGetValue().
Member Data Documentation
mat
SourceMaterial.Row TraitShrine.mat
Definition at line 3 of file TraitShrine.cs.
Property Documentation
RenderExtra
override bool TraitShrine.RenderExtra get
Definition at line 7 of file TraitShrine.cs.
    {
        get
        {
            if (owner.isOn)
            {
                if (!owner.IsInstalled)
                {
                    return owner.isRoofItem;
                }
                return true;
            }
            return false;
        }
    }
Shrine
ShrineData TraitShrine.Shrine get
Definition at line 5 of file TraitShrine.cs.
Referenced by _OnUse(), and OnCreate().
The documentation for this class was generated from the following file:
Elin/TraitShrine.cs