Elin Decompiled Documentation: CharacterSpacing Class Reference
CharacterSpacing Class Reference
Public Member Functions
override void ModifyMesh (VertexHelper vh)
Protected Member Functions
CharacterSpacing ()
Properties
float offset [get, set]
Private Member Functions
MatchCollection GetRegexMatchedTags (string text, out int lengthWithoutTags)
Private Attributes
float m_Offset
List< UIVertex > m_Verts = new List<UIVertex>()
Static Private Attributes
const string REGEX_TAGS = "<b>|</b>|<i>|</i>|<size=.*?>|</size>|<color=.*?>|</color>|<material=.*?>|</material>"
Detailed Description
Definition at line 9 of file CharacterSpacing.cs.
Constructor & Destructor Documentation
CharacterSpacing()
CharacterSpacing.CharacterSpacing () inline protected
Definition at line 37 of file CharacterSpacing.cs.
    {
    }
Member Function Documentation
GetRegexMatchedTags()
MatchCollection CharacterSpacing.GetRegexMatchedTags (string text, out int lengthWithoutTags) inline private
Definition at line 136 of file CharacterSpacing.cs.
    {
        MatchCollection matchCollection = Regex.Matches(text, "<b>|</b>|<i>|</i>|<size=.*?>|</size>|<color=.*?>|</color>|<material=.*?>|</material>");
        lengthWithoutTags = 0;
        int num = 0;
        foreach (Match item in matchCollection)
        {
            num += item.Length;
        }
        lengthWithoutTags = text.Length - num;
        return matchCollection;
    }
References item.
Referenced by ModifyMesh().
ModifyMesh()
override void CharacterSpacing.ModifyMesh (VertexHelper vh) inline
Definition at line 41 of file CharacterSpacing.cs.
    {
        if (!IsActive())
        {
            return;
        }
        vh.GetUIVertexStream(m_Verts);
        Text component = GetComponent<Text>();
        List<string> list = new List<string>();
        for (int i = 0; i < component.cachedTextGenerator.lineCount; i++)
        {
            int startCharIdx = component.cachedTextGenerator.lines[i].startCharIdx;
            int num = ((i < component.cachedTextGenerator.lineCount - 1) ? component.cachedTextGenerator.lines[i + 1].startCharIdx : component.text.Length);
            list.Add(component.text.Substring(startCharIdx, num - startCharIdx));
        }
        float num2 = offset * (float)component.fontSize / 100f;
        float num3 = 0f;
        IEnumerator enumerator = null;
        Match match = null;
        if (component.alignment == TextAnchor.LowerLeft || component.alignment == TextAnchor.MiddleLeft || component.alignment == TextAnchor.UpperLeft)
        {
            num3 = 0f;
        }
        else if (component.alignment == TextAnchor.LowerCenter || component.alignment == TextAnchor.MiddleCenter || component.alignment == TextAnchor.UpperCenter)
        {
            num3 = 0.5f;
        }
        else if (component.alignment == TextAnchor.LowerRight || component.alignment == TextAnchor.MiddleRight || component.alignment == TextAnchor.UpperRight)
        {
            num3 = 1f;
        }
        bool flag = true;
        int num4 = 0;
        for (int j = 0; j < list.Count; j++)
        {
            if (!flag)
            {
                break;
            }
            string text = list[j];
            int lengthWithoutTags = text.Length;
            if (lengthWithoutTags > component.cachedTextGenerator.characterCountVisible - num4)
            {
                lengthWithoutTags = component.cachedTextGenerator.characterCountVisible - num4;
                text = text.Substring(0, lengthWithoutTags) + " ";
                lengthWithoutTags++;
            }
            if (component.supportRichText)
            {
                enumerator = GetRegexMatchedTags(text, out lengthWithoutTags).GetEnumerator();
                match = null;
                if (enumerator.MoveNext())
                {
                    match = (Match)enumerator.Current;
                }
            }
            bool flag2 = list[j].Length > 0 && (list[j][list[j].Length - 1] == ' ' || list[j][list[j].Length - 1] == '\n');
            float num5 = (float)(-(lengthWithoutTags - 1 - (flag2 ? 1 : 0))) * num2 * num3;
            float num6 = 0f;
            for (int k = 0; k < text.Length; k++)
            {
                if (!flag)
                {
                    break;
                }
                if (component.supportRichText && match != null && match.Index == k)
                {
                    k += match.Length - 1;
                    num4 += match.Length - 1;
                    num6 -= 1f;
                    match = null;
                    if (enumerator.MoveNext())
                    {
                        match = (Match)enumerator.Current;
                    }
                }
                if (num4 * 6 + 5 >= m_Verts.Count)
                {
                    flag = false;
                    break;
                }
                for (int l = 0; l < 6; l++)
                {
                    UIVertex value = m_Verts[num4 * 6 + l];
                    value.position += Vector3.right * (num2 * num6 + num5);
                    m_Verts[num4 * 6 + l] = value;
                }
                num4++;
                num6 += 1f;
            }
        }
        vh.Clear();
        vh.AddUIVertexTriangleStream(m_Verts);
    }
References GetRegexMatchedTags(), if(), m_Verts, and offset.
Member Data Documentation
m_Offset
float CharacterSpacing.m_Offset private
Definition at line 14 of file CharacterSpacing.cs.
m_Verts
List<UIVertex> CharacterSpacing.m_Verts = new List<UIVertex>() private
Definition at line 16 of file CharacterSpacing.cs.
Referenced by ModifyMesh().
REGEX_TAGS
const string CharacterSpacing.REGEX_TAGS = "<b>|</b>|<i>|</i>|<size=.*?>|</size>|<color=.*?>|</color>|<material=.*?>|</material>" static private
Definition at line 11 of file CharacterSpacing.cs.
Property Documentation
offset
float CharacterSpacing.offset get set
Definition at line 18 of file CharacterSpacing.cs.
    {
        get
        {
            return m_Offset;
        }
        set
        {
            if (m_Offset != value)
            {
                m_Offset = value;
                if (base.graphic != null)
                {
                    base.graphic.SetVerticesDirty();
                }
            }
        }
    }
Referenced by ModifyMesh().
The documentation for this class was generated from the following file:
Elin/Plugins.UI/CharacterSpacing.cs