Elin Decompiled Documentation: LayerGlobalMap Class Reference
LayerGlobalMap Class Reference
Public Member Functions
override void OnInit ()
void RefreshSummary ()
Public Member Functions inherited from ELayer
override void OnBeforeAddLayer ()
void InitInspector ()
sealed override void Init ()
override void OnAfterAddLayer ()
void TryShowHelp ()
void AddLayerToUI (string id)
void TryShowHint (string _langHint=null)
void TalkHomeMemeber (string id)
void TalkMaid (string id)
override void OnRightClick ()
Public Attributes
UIText textName
UIText textExplore
UIText textTerritory
UIText textPopu
UIText textWealth
UIText textRestore
UIText textProgress
Additional Inherited Members
Static Public Member Functions inherited from ELayer
static int rnd (int a)
Protected Member Functions inherited from ELayer
sealed override void _Close ()
sealed override void Kill ()
Properties inherited from ELayer
static Core core [get]
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static FactionBranch Branch [get]
static Faction Home [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static CoreConfig config [get]
static GameSetting setting [get]
static ColorProfile Colors [get]
static SourceManager sources [get]
static World world [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
bool IsFloat [get]
virtual string IdHelp [get]
Detailed Description
Definition at line 3 of file LayerGlobalMap.cs.
Member Function Documentation
OnInit()
override void LayerGlobalMap.OnInit () inline
Definition at line 19 of file LayerGlobalMap.cs.
    {
        RefreshSummary();
    }
References RefreshSummary().
RefreshSummary()
void LayerGlobalMap.RefreshSummary () inline
Definition at line 24 of file LayerGlobalMap.cs.
    {
        textName.SetText(ELayer.world.Name + Environment.NewLine + "<size=18> (" + ELayer.pc.currentZone.Region.Name + ")</size>");
        textExplore.SetText("0%");
        textTerritory.SetText(ELayer.Home.CountTerritories().ToString() ?? "");
        textRestore.SetText("1 (0/20)");
        textWealth.SetText(ELayer.Home.CountWealth().ToString() ?? "");
        textPopu.SetText(ELayer.Home.CountMembers().ToString() ?? "");
        textProgress.SetText("_progress".lang(ELayer.player.stats.days.ToString() ?? "", ELayer.player.stats.sieges.ToString() ?? ""));
    }
References Faction.CountMembers(), Faction.CountTerritories(), Faction.CountWealth(), Chara.currentZone, Player.Stats.days, ELayer.Home, Spatial.Name, ELayer.pc, ELayer.player, Zone.Region, Player.Stats.sieges, Player.stats, textExplore, textName, textPopu, textProgress, textRestore, textTerritory, textWealth, and ELayer.world.
Referenced by OnInit().
Member Data Documentation
textExplore
UIText LayerGlobalMap.textExplore
Definition at line 7 of file LayerGlobalMap.cs.
Referenced by RefreshSummary().
textName
UIText LayerGlobalMap.textName
Definition at line 5 of file LayerGlobalMap.cs.
Referenced by RefreshSummary().
textPopu
UIText LayerGlobalMap.textPopu
Definition at line 11 of file LayerGlobalMap.cs.
Referenced by RefreshSummary().
textProgress
UIText LayerGlobalMap.textProgress
Definition at line 17 of file LayerGlobalMap.cs.
Referenced by RefreshSummary().
textRestore
UIText LayerGlobalMap.textRestore
Definition at line 15 of file LayerGlobalMap.cs.
Referenced by RefreshSummary().
textTerritory
UIText LayerGlobalMap.textTerritory
Definition at line 9 of file LayerGlobalMap.cs.
Referenced by RefreshSummary().
textWealth
UIText LayerGlobalMap.textWealth
Definition at line 13 of file LayerGlobalMap.cs.
Referenced by RefreshSummary().
The documentation for this class was generated from the following file:
Elin/LayerGlobalMap.cs