Elin Decompiled Documentation: World Class Reference
World Class Reference
Public Member Functions
override void OnCreate ()
void CreateDayData ()
void ModEther (int a=3)
void SendPackage (Thing p)
Public Member Functions inherited from Spatial
int GetInt (int id, int? defaultInt=null)
void AddInt (int id, int value)
void SetInt (int id, int value=0)
override string ToString ()
void Create (string _id, int _x, int _y, int _icon)
void Register ()
virtual void OnCreate ()
virtual void OnAfterCreate ()
virtual void SetMainFaction (Faction f)
Zone GetFirstZone ()
void OnBeforeSave ()
virtual void _OnBeforeSave ()
void _OnLoad ()
virtual void OnLoad ()
virtual void Destroy ()
void DeleteMapRecursive ()
virtual void AddChild (Spatial child)
void RemoveChild (Spatial child)
Zone FindDeepestZone ()
Zone FindZone (int lv)
Zone FindZone (string _id)
virtual bool CanKill ()
int Dist (Point p)
int Dist (Spatial s)
void MakeGameObject (GameObject parentGo)
Public Attributes
GameDate date = new GameDate()
Season season = new Season()
Weather weather = new Weather()
Schedule schedule = new Schedule()
DayData dayData
int ether
Public Attributes inherited from Spatial
Spatial parent
string id
string idUser
string name
string idMainFaction
string idProfile
string idCurrentSubset
string idHat
int[] _ints = new int[30]
List< Spatial > children = new List<Spatial>()
List< Spatial > connections = new List<Spatial>()
Dictionary< int, int > mapInt = new Dictionary<int, int>()
bool destryoed
bool isImported
BitArray32 bits
Properties
Region region [get]
Properties inherited from Spatial
int _bits [get, set]
int uid [get, set]
int icon [get, set]
int x [get, set]
int y [get, set]
int lastActive [get, set]
int idPrefix [get, set]
int lv [get, set]
int visitCount [get, set]
int dateExpire [get, set]
int dateRevive [get, set]
int _dangerLv [get, set]
int dateRegenerate [get, set]
int influence [get, set]
int investment [get, set]
int development [get, set]
int electricity [get, set]
int dateHat [get, set]
int uidBoss [get, set]
int dateQuest [get, set]
int version [get, set]
bool isGenerated [get, set]
bool isShore [get, set]
bool isRandomSite [get, set]
bool isKnown [get, set]
bool isMapSaved [get, set]
bool isExternalZone [get, set]
bool isConquered [get, set]
bool isBeach [get, set]
bool isPeace [get, set]
bool isDeathLocation [get, set]
Faction mainFaction [get, set]
SourceZone.Row source [get]
bool IsPlayerFaction [get]
bool IsClosed [get]
int mapX [get]
int mapY [get]
virtual int ContentLv [get]
virtual int DangerLv [get]
virtual int DangerLvFix [get]
virtual float VolumeSea [get]
virtual bool ShowDangerLv [get]
virtual bool CanSpawnAdv [get]
string pathSave [get]
virtual string Name [get]
string NameWithDangerLevel [get]
virtual string NameSuffix [get]
virtual bool IsRegion [get]
virtual bool CanFastTravel [get]
EloMap.TileInfo Tile [get]
virtual bool IsSnowZone [get]
virtual bool IsSnowCovered [get]
virtual Point RegionPos [get]
virtual bool isClaimable [get]
int Seed [get]
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Additional Inherited Members
Static Public Member Functions inherited from EClass
static int rndSeed (int a, int seed)
static int rnd (int a)
static int curve (int a, int start, int step, int rate=75)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Static Public Attributes inherited from EClass
static Core core
Protected Member Functions inherited from Spatial
Zone _FindZone (string _id)
Protected Attributes inherited from Spatial
Point _regionPos = new Point()
Detailed Description
Definition at line 3 of file World.cs.
Member Function Documentation
CreateDayData()
void World.CreateDayData () inline
Definition at line 43 of file World.cs.
    {
        dayData = new DayData();
        int num = EClass.rnd(100);
        for (int i = 0; i < DayData.LuckRange.Length; i++)
        {
            if (num >= DayData.LuckRange[i])
            {
                dayData.luck = i.ToEnum<DayData.Luck>();
                break;
            }
        }
        dayData.seed = EClass.rnd(100000);
    }
References dayData, DayData.LuckRange, and EClass.rnd().
Referenced by GameDate.AdvanceDay(), OnCreate(), and LayerNewspaper.OnInit().
ModEther()
void World.ModEther (int a = 3) inline
Definition at line 58 of file World.cs.
    {
        ether += a;
        if (ether >= 100)
        {
            ether = 0;
            weather.SetCondition(Weather.Condition.Ether, 24);
        }
    }
References ether, Weather.SetCondition(), and weather.
OnCreate()
override void World.OnCreate () inline virtual
Reimplemented from Spatial.
Definition at line 25 of file World.cs.
    {
        Prologue prologue = EClass.game.Prologue;
        date.year = prologue.year;
        date.month = prologue.month;
        date.day = prologue.day;
        date.hour = prologue.hour;
        for (int i = 0; i < 5; i++)
        {
            schedule.list.Add(new Schedule.Item
            {
                date = date.Copy()
            });
        }
        weather._currentCondition = prologue.weather;
        CreateDayData();
    }
References CreateDayData(), Prologue.day, EClass.game, Prologue.hour, Schedule.list, Prologue.month, Game.Prologue, schedule, Prologue.weather, and Prologue.year.
SendPackage()
void World.SendPackage (Thing p) inline
Definition at line 68 of file World.cs.
    {
        EClass.game.cards.listPackage.Add(p);
    }
References ActPlan.List.Add(), Game.cards, EClass.game, and CardManager.listPackage.
Referenced by GameDate.AdvanceDay(), GameDate.AdvanceYear(), Chara.MutateRandom(), Faction.OnAdvanceMonth(), FactionBranch.OnSimulateDay(), InvOwnerDeliver.PayBill(), GameDate.ShipLetter(), GameDate.ShipPackages(), GameDate.ShipRandomPackages(), and Faction.TryPayBill().
Member Data Documentation
date
GameDate World.date = new GameDate()
Definition at line 6 of file World.cs.
Referenced by Chara._Move(), InvOwnerGene._OnProcess(), WidgetDate._Refresh(), Zone.AbandonZone(), Zone.Activate(), MsgLog.Add(), FactionBranch.AddRecruit(), Faction.AddReserve(), LayerSleep.Advance(), DramaCustomSequence.Build(), Zone.CanDestroy(), Chara.CanRevive(), Card.CheckJustCooked(), Region.CheckRandomSites(), Chara.ChooseNewGoal(), Zone.ClaimZone(), GameIndex.Create(), SpatialGen.CreateInstance(), Region.CreateRandomSite(), Card.DamageHP(), Zone.Deactivate(), BaseTileMap.DrawTile(), DramaOutcome.get_scratch(), Card.GetLightRadius(), TraitGeneMachine.GetProgress(), TraitGeneMachine.GetProgressText(), Trait.GetRestockedIcon(), Trait.GetTextRestock(), Weather.GetTimeSinceLastRain(), Weather.GetWeatherForecast(), Quest.Init(), Quest.IsVisibleOnQuestBoard(), TraitMoongate.LoadMap(), RecipeCard.MakeDish(), Player.MoveZone(), WidgetArtTool.OnActivate(), Region.OnAdvanceHour(), Trait.OnBarter(), BaseListPeople.OnClick(), QuestLoytelFarm.OnComplete(), QuestShippingChest.OnComplete(), QuestVernis.OnComplete(), FactionBranch.OnCreate(), QuestDialog.OnDropReward(), Zone_Field.OnGenerateMap(), LayerNewspaper.OnInit(), Game.OnLoad(), QuestIntoDarkness.OnStart(), Player.OnStartNewGame(), TraitDaggerGrave.OnUse(), TraitHat.OnUse(), Zone.OnVisit(), FoodEffect.Proc(), FortuneRollData.Refresh(), LayerTravel.Refresh(), Weather.RefreshForecasts(), Zone.RefreshHat(), ContentHomeReport.RefreshInfo(), UIHomeInfo.RefreshInfo(), UIHomeInfo.RefreshReport(), BaseGameScreen.RefreshSky(), CoreConfig.RefreshUIBrightness(), BaseGameScreen.RefreshWeather(), Zone.Revive(), AI_Idle.Run(), AI_Slaughter.Run(), AI_Steal.Run(), Weather.SetCondition(), AIWork.SetDestination(), GameDate.ShipGoods(), HotItemContext.Show(), Zone.Simulate(), Zone.ToString(), Thing.TryLickEnchant(), SlaverData.TryRefresh(), TraitCoreZone.TrySetAct(), Trait.TryToggle(), Chara.TryWorkOutside(), GameUpdater.Update(), CoreDebug.UpdateInput(), Zone.UpdateQuests(), Scene.UpdateTimeRatio(), and VirtualDate.VirtualDate().
dayData
DayData World.dayData
Definition at line 18 of file World.cs.
Referenced by CreateDayData(), and LayerNewspaper.OnInit().
ether
int World.ether
Definition at line 21 of file World.cs.
Referenced by ModEther().
schedule
Schedule World.schedule = new Schedule()
Definition at line 15 of file World.cs.
Referenced by OnCreate(), and ContentTop.OnSwitchContent().
season
Season World.season = new Season()
Definition at line 9 of file World.cs.
Referenced by Weather.RefreshWeather(), and Weather.SetCondition().
weather
Weather World.weather = new Weather()
Definition at line 12 of file World.cs.
Referenced by Chara._Move(), WidgetDate._Refresh(), GameDate.AdvanceHour(), GameUpdater.SurfaceUpdater.FixedUpdate(), Scene.Init(), ModEther(), WidgetArtTool.OnActivate(), TraitGenerator.OnSimulateHour(), BaseGameScreen.RefreshScreenSize(), BaseGameScreen.RefreshWeather(), GameScreenElona.RefreshWeather(), LayerNewspaper.RefreshWeather(), Chara.TickConditions(), Trait.TryToggle(), GameUpdater.Update100ms(), and CoreDebug.UpdateInput().
Property Documentation
region
Region World.region get
Definition at line 23 of file World.cs.
Referenced by LayerSleep.Advance(), GameDate.AdvanceDay(), Region.CanCreateZone(), ThingGen.CreateMap(), Expedition.End(), Chara.FallFromZone(), GlobalGoalExplore.GetDestZone(), GlobalGoalVisitTown.GetDestZone(), EloMapActor.GetEloMap(), EloMap.GetRoadDist(), SpatialManager.ListReturnLocations(), TraitMoongate.LoadMap(), CoreDebug.LOG_Spatials(), TraitNewZone.MoveZone(), GlobalGoalAdv.OnAdvanceHour(), Chara.OnBanish(), Game.OnLoad(), TraitScrollMap.OnRead(), LayerTreasureMap.SetMap(), and Chara.Tick().
The documentation for this class was generated from the following file:
Elin/World.cs