Elin Decompiled Documentation: Empyrean.ColorPicker.ColorPicker Class Reference
Empyrean.ColorPicker.ColorPicker Class Reference
Public Member Functions
void Init ()
void OnColorPickedFromPalette (Vector2 positionOnPalette)
void SelectColor (Color newColor)
bool IsAlphaBeingUsed ()
Public Attributes
SelectedColorController selectedColor
ColorPalette palette
HueSlider hueSlider
LabeledColorSlider redHueSlider
LabeledColorSlider greenSatSlider
LabeledColorSlider blueValSlider
Dropper dropper
Color defaultColor
int[] colors = new int[10]
Static Package Attributes
static bool slidersHsvMode
Properties
Color SelectedColor [get, set]
float Alpha [get]
float Hue [get]
float Saturation [get]
float ValueHSV [get]
Events
Action< Color > ColorUpdated
Private Types
enum ColorUpdateMode {
MANUAL , RGBA , HSVA , HSV ,
MARKER
}
Private Member Functions
void OnColorSliderValueChanged (float value)
void OnHueSliderValueChanged (float value)
void OnHexColorSelected (Color color)
void UpdateColorPicker (ColorUpdateMode mode, bool sendEvent=true)
void UpdateColor (ColorUpdateMode mode)
void UpdateSlidersValues (ColorUpdateMode mode)
void StartDropper ()
void OnColorPicked (Color color)
void OnDropperCanceled ()
void OnSlidersModeButton ()
Private Attributes
LabeledColorSlider alphaSlider
HexInput hexInput
Button dropperButton
Button slidersModeButton
bool useAlpha = true
Color backupColor
Detailed Description
Definition at line 7 of file ColorPicker.cs.
Member Enumeration Documentation
ColorUpdateMode
enum Empyrean.ColorPicker.ColorPicker.ColorUpdateMode private
Enumerator
MANUAL
RGBA
HSVA
HSV
MARKER
Definition at line 9 of file ColorPicker.cs.
    {
        MANUAL,
        RGBA,
        HSVA,
        HSV,
        MARKER
    }
Member Function Documentation
Init()
void Empyrean.ColorPicker.ColorPicker.Init () inline
Definition at line 99 of file ColorPicker.cs.
    {
        redHueSlider.ColorValueChanged += OnColorSliderValueChanged;
        blueValSlider.ColorValueChanged += OnColorSliderValueChanged;
        greenSatSlider.ColorValueChanged += OnColorSliderValueChanged;
        alphaSlider.ColorValueChanged += OnColorSliderValueChanged;
        hueSlider.Init();
        hueSlider.HueValueChanged += OnHueSliderValueChanged;
        palette.ColorPicked += OnColorPickedFromPalette;
        hexInput.ColorSelected += OnHexColorSelected;
        if (dropperButton != null)
        {
            dropperButton.onClick.AddListener(StartDropper);
        }
        slidersModeButton.onClick.AddListener(OnSlidersModeButton);
        alphaSlider.gameObject.SetActive(useAlpha);
    }
References Empyrean.ColorPicker.ColorPicker.alphaSlider, Empyrean.ColorPicker.ColorPicker.dropperButton, Empyrean.ColorPicker.ColorPicker.hueSlider, Empyrean.ColorPicker.HueSlider.Init(), Empyrean.ColorPicker.ColorPicker.OnColorPickedFromPalette(), Empyrean.ColorPicker.ColorPicker.OnColorSliderValueChanged(), Empyrean.ColorPicker.ColorPicker.OnHexColorSelected(), Empyrean.ColorPicker.ColorPicker.OnHueSliderValueChanged(), Empyrean.ColorPicker.ColorPicker.OnSlidersModeButton(), Empyrean.ColorPicker.ColorPicker.slidersModeButton, Empyrean.ColorPicker.ColorPicker.StartDropper(), and Empyrean.ColorPicker.ColorPicker.useAlpha.
Referenced by PixelPaint.Init(), and UIColorPicker.SetColor().
IsAlphaBeingUsed()
bool Empyrean.ColorPicker.ColorPicker.IsAlphaBeingUsed () inline
Definition at line 224 of file ColorPicker.cs.
    {
        return useAlpha;
    }
References Empyrean.ColorPicker.ColorPicker.useAlpha.
Referenced by HexInput.Awake(), and HexInput.GetAlpha().
OnColorPicked()
void Empyrean.ColorPicker.ColorPicker.OnColorPicked (Color color) inline private
Definition at line 199 of file ColorPicker.cs.
    {
        SelectColor(color);
    }
References Empyrean.ColorPicker.ColorPicker.SelectColor().
Referenced by Empyrean.ColorPicker.ColorPicker.StartDropper().
OnColorPickedFromPalette()
void Empyrean.ColorPicker.ColorPicker.OnColorPickedFromPalette (Vector2 positionOnPalette) inline
Definition at line 127 of file ColorPicker.cs.
    {
        selectedColor.Select(new HSVColor(hueSlider.value, positionOnPalette.x, positionOnPalette.y, Alpha));
        UpdateColorPicker(ColorUpdateMode.MARKER);
    }
References Empyrean.ColorPicker.ColorPicker.Alpha, Empyrean.ColorPicker.ColorPicker.hueSlider, SelectedColorController.Select(), Empyrean.ColorPicker.ColorPicker.selectedColor, Empyrean.ColorPicker.ColorPicker.UpdateColorPicker(), and Empyrean.ColorPicker.HueSlider.value.
Referenced by Empyrean.ColorPicker.ColorPicker.Init().
OnColorSliderValueChanged()
void Empyrean.ColorPicker.ColorPicker.OnColorSliderValueChanged (float value) inline private
Definition at line 117 of file ColorPicker.cs.
    {
        UpdateColorPicker((!slidersHsvMode) ? ColorUpdateMode.RGBA : ColorUpdateMode.HSVA);
    }
References Empyrean.ColorPicker.ColorPicker.slidersHsvMode, and Empyrean.ColorPicker.ColorPicker.UpdateColorPicker().
Referenced by Empyrean.ColorPicker.ColorPicker.Init().
OnDropperCanceled()
void Empyrean.ColorPicker.ColorPicker.OnDropperCanceled () inline private
Definition at line 204 of file ColorPicker.cs.
    {
        SelectColor(backupColor);
    }
References Empyrean.ColorPicker.ColorPicker.backupColor, and Empyrean.ColorPicker.ColorPicker.SelectColor().
Referenced by Empyrean.ColorPicker.ColorPicker.StartDropper().
OnHexColorSelected()
void Empyrean.ColorPicker.ColorPicker.OnHexColorSelected (Color color) inline private
Definition at line 133 of file ColorPicker.cs.
    {
        SelectColor(color);
    }
References Empyrean.ColorPicker.ColorPicker.SelectColor().
Referenced by Empyrean.ColorPicker.ColorPicker.Init().
OnHueSliderValueChanged()
void Empyrean.ColorPicker.ColorPicker.OnHueSliderValueChanged (float value) inline private
Definition at line 122 of file ColorPicker.cs.
    {
        UpdateColorPicker(ColorUpdateMode.HSV);
    }
References Empyrean.ColorPicker.ColorPicker.UpdateColorPicker().
Referenced by Empyrean.ColorPicker.ColorPicker.Init().
OnSlidersModeButton()
void Empyrean.ColorPicker.ColorPicker.OnSlidersModeButton () inline private
Definition at line 209 of file ColorPicker.cs.
    {
        slidersHsvMode = !slidersHsvMode;
        redHueSlider.ToggleSliderMode();
        greenSatSlider.ToggleSliderMode();
        blueValSlider.ToggleSliderMode();
        UpdateColorPicker(ColorUpdateMode.MANUAL, sendEvent: false);
    }
References Empyrean.ColorPicker.ColorPicker.blueValSlider, Empyrean.ColorPicker.ColorPicker.greenSatSlider, Empyrean.ColorPicker.ColorPicker.redHueSlider, Empyrean.ColorPicker.ColorPicker.slidersHsvMode, Empyrean.ColorPicker.LabeledColorSlider.ToggleSliderMode(), and Empyrean.ColorPicker.ColorPicker.UpdateColorPicker().
Referenced by Empyrean.ColorPicker.ColorPicker.Init().
SelectColor()
void Empyrean.ColorPicker.ColorPicker.SelectColor (Color newColor) inline
Definition at line 218 of file ColorPicker.cs.
    {
        selectedColor.Select(newColor);
        UpdateColorPicker(ColorUpdateMode.MANUAL);
    }
References SelectedColorController.Select(), Empyrean.ColorPicker.ColorPicker.selectedColor, and Empyrean.ColorPicker.ColorPicker.UpdateColorPicker().
Referenced by PixelPaint.Init(), LayerColorPicker.OnClickReset(), Empyrean.ColorPicker.ColorPicker.OnColorPicked(), Empyrean.ColorPicker.ColorPicker.OnDropperCanceled(), Empyrean.ColorPicker.ColorPicker.OnHexColorSelected(), LayerPixelPaint.OnInit(), UIColorPicker.SetColor(), and PixelPaint.Update().
StartDropper()
void Empyrean.ColorPicker.ColorPicker.StartDropper () inline private
Definition at line 193 of file ColorPicker.cs.
    {
        backupColor = selectedColor.RGBA;
        dropper.PickColors(OnColorPicked, OnDropperCanceled);
    }
References Empyrean.ColorPicker.ColorPicker.backupColor, Empyrean.ColorPicker.ColorPicker.dropper, Empyrean.ColorPicker.ColorPicker.OnColorPicked(), Empyrean.ColorPicker.ColorPicker.OnDropperCanceled(), Empyrean.ColorPicker.Dropper.PickColors(), SelectedColorController.RGBA, and Empyrean.ColorPicker.ColorPicker.selectedColor.
Referenced by Empyrean.ColorPicker.ColorPicker.Init().
UpdateColor()
void Empyrean.ColorPicker.ColorPicker.UpdateColor (ColorUpdateMode mode) inline private
Definition at line 150 of file ColorPicker.cs.
    {
        switch (mode)
        {
        case ColorUpdateMode.HSV:
            selectedColor.Select(new HSVColor(hueSlider.value, palette.MarkerPosition.x, palette.MarkerPosition.y, Alpha));
            break;
        case ColorUpdateMode.HSVA:
            selectedColor.Select(new HSVColor(redHueSlider.Value * 359f, greenSatSlider.Value, blueValSlider.Value, Alpha));
            break;
        case ColorUpdateMode.RGBA:
            selectedColor.Select(new Color(redHueSlider.Value, greenSatSlider.Value, blueValSlider.Value, Alpha));
            break;
        }
    }
References Empyrean.ColorPicker.ColorPicker.Alpha, Empyrean.ColorPicker.ColorPicker.blueValSlider, Color, Empyrean.ColorPicker.ColorPicker.greenSatSlider, Empyrean.ColorPicker.ColorPicker.hueSlider, Empyrean.ColorPicker.ColorPalette.MarkerPosition, Empyrean.ColorPicker.ColorPicker.palette, Empyrean.ColorPicker.ColorPicker.redHueSlider, SelectedColorController.Select(), Empyrean.ColorPicker.ColorPicker.selectedColor, Empyrean.ColorPicker.HueSlider.value, and Empyrean.ColorPicker.LabeledColorSlider.Value.
Referenced by Empyrean.ColorPicker.ColorPicker.UpdateColorPicker().
UpdateColorPicker()
void Empyrean.ColorPicker.ColorPicker.UpdateColorPicker (ColorUpdateMode mode, bool sendEvent = true) inline private
Definition at line 138 of file ColorPicker.cs.
    {
        UpdateColor(mode);
        UpdateSlidersValues(mode);
        hexInput.SelectColor(selectedColor.RGBA);
        palette.SelectColor(selectedColor.HSV);
        if (sendEvent)
        {
            this.ColorUpdated(selectedColor.RGBA);
        }
    }
References Empyrean.ColorPicker.ColorPicker.ColorUpdated, Empyrean.ColorPicker.ColorPicker.hexInput, SelectedColorController.HSV, Empyrean.ColorPicker.ColorPicker.palette, SelectedColorController.RGBA, HexInput.SelectColor(), Empyrean.ColorPicker.ColorPalette.SelectColor(), Empyrean.ColorPicker.ColorPicker.selectedColor, Empyrean.ColorPicker.ColorPicker.UpdateColor(), and Empyrean.ColorPicker.ColorPicker.UpdateSlidersValues().
Referenced by Empyrean.ColorPicker.ColorPicker.OnColorPickedFromPalette(), Empyrean.ColorPicker.ColorPicker.OnColorSliderValueChanged(), Empyrean.ColorPicker.ColorPicker.OnHueSliderValueChanged(), Empyrean.ColorPicker.ColorPicker.OnSlidersModeButton(), and Empyrean.ColorPicker.ColorPicker.SelectColor().
UpdateSlidersValues()
void Empyrean.ColorPicker.ColorPicker.UpdateSlidersValues (ColorUpdateMode mode) inline private
Definition at line 166 of file ColorPicker.cs.
    {
        if (mode != ColorUpdateMode.HSV)
        {
            hueSlider.value = selectedColor.HSV.h;
        }
        if (mode != ColorUpdateMode.RGBA && mode != ColorUpdateMode.HSVA)
        {
            if (slidersHsvMode)
            {
                redHueSlider.Value = selectedColor.HSV.h / 359f;
                greenSatSlider.Value = selectedColor.HSV.s;
                blueValSlider.Value = selectedColor.HSV.v;
            }
            else
            {
                redHueSlider.Value = selectedColor.RGBA.r;
                greenSatSlider.Value = selectedColor.RGBA.g;
                blueValSlider.Value = selectedColor.RGBA.b;
            }
            if (useAlpha)
            {
                alphaSlider.Value = selectedColor.RGBA.a;
            }
        }
    }
References HSVColor.h, SelectedColorController.HSV, SelectedColorController.RGBA, HSVColor.s, Empyrean.ColorPicker.ColorPicker.selectedColor, Empyrean.ColorPicker.ColorPicker.slidersHsvMode, Empyrean.ColorPicker.ColorPicker.useAlpha, and HSVColor.v.
Referenced by Empyrean.ColorPicker.ColorPicker.UpdateColorPicker().
Member Data Documentation
alphaSlider
LabeledColorSlider Empyrean.ColorPicker.ColorPicker.alphaSlider private
Definition at line 40 of file ColorPicker.cs.
Referenced by Empyrean.ColorPicker.ColorPicker.Init().
backupColor
Color Empyrean.ColorPicker.ColorPicker.backupColor private
Definition at line 63 of file ColorPicker.cs.
Referenced by Empyrean.ColorPicker.ColorPicker.OnDropperCanceled(), and Empyrean.ColorPicker.ColorPicker.StartDropper().
blueValSlider
LabeledColorSlider Empyrean.ColorPicker.ColorPicker.blueValSlider
Definition at line 37 of file ColorPicker.cs.
Referenced by Empyrean.ColorPicker.ColorPicker.OnSlidersModeButton(), and Empyrean.ColorPicker.ColorPicker.UpdateColor().
colors
int [] Empyrean.ColorPicker.ColorPicker.colors = new int[10]
Definition at line 61 of file ColorPicker.cs.
defaultColor
Color Empyrean.ColorPicker.ColorPicker.defaultColor
Definition at line 55 of file ColorPicker.cs.
dropper
Dropper Empyrean.ColorPicker.ColorPicker.dropper
Definition at line 46 of file ColorPicker.cs.
Referenced by LayerColorPicker.OnBack(), LayerColorPicker.OnKill(), and Empyrean.ColorPicker.ColorPicker.StartDropper().
dropperButton
Button Empyrean.ColorPicker.ColorPicker.dropperButton private
Definition at line 49 of file ColorPicker.cs.
Referenced by Empyrean.ColorPicker.ColorPicker.Init().
greenSatSlider
LabeledColorSlider Empyrean.ColorPicker.ColorPicker.greenSatSlider
Definition at line 34 of file ColorPicker.cs.
Referenced by Empyrean.ColorPicker.ColorPicker.OnSlidersModeButton(), and Empyrean.ColorPicker.ColorPicker.UpdateColor().
hexInput
HexInput Empyrean.ColorPicker.ColorPicker.hexInput private
Definition at line 43 of file ColorPicker.cs.
Referenced by Empyrean.ColorPicker.ColorPicker.UpdateColorPicker().
hueSlider
HueSlider Empyrean.ColorPicker.ColorPicker.hueSlider
Definition at line 28 of file ColorPicker.cs.
Referenced by Empyrean.ColorPicker.ColorPicker.Init(), Empyrean.ColorPicker.ColorPicker.OnColorPickedFromPalette(), and Empyrean.ColorPicker.ColorPicker.UpdateColor().
palette
ColorPalette Empyrean.ColorPicker.ColorPicker.palette
Definition at line 25 of file ColorPicker.cs.
Referenced by Empyrean.ColorPicker.ColorPicker.UpdateColor(), and Empyrean.ColorPicker.ColorPicker.UpdateColorPicker().
redHueSlider
LabeledColorSlider Empyrean.ColorPicker.ColorPicker.redHueSlider
Definition at line 31 of file ColorPicker.cs.
Referenced by Empyrean.ColorPicker.ColorPicker.OnSlidersModeButton(), and Empyrean.ColorPicker.ColorPicker.UpdateColor().
selectedColor
SelectedColorController Empyrean.ColorPicker.ColorPicker.selectedColor
Definition at line 22 of file ColorPicker.cs.
Referenced by Empyrean.ColorPicker.ColorPicker.OnColorPickedFromPalette(), Empyrean.ColorPicker.ColorPicker.SelectColor(), Empyrean.ColorPicker.ColorPicker.StartDropper(), Empyrean.ColorPicker.ColorPicker.UpdateColor(), Empyrean.ColorPicker.ColorPicker.UpdateColorPicker(), and Empyrean.ColorPicker.ColorPicker.UpdateSlidersValues().
slidersHsvMode
bool Empyrean.ColorPicker.ColorPicker.slidersHsvMode static package
Definition at line 18 of file ColorPicker.cs.
Referenced by Empyrean.ColorPicker.ColorPicker.OnColorSliderValueChanged(), Empyrean.ColorPicker.ColorPicker.OnSlidersModeButton(), and Empyrean.ColorPicker.ColorPicker.UpdateSlidersValues().
slidersModeButton
Button Empyrean.ColorPicker.ColorPicker.slidersModeButton private
Definition at line 52 of file ColorPicker.cs.
Referenced by Empyrean.ColorPicker.ColorPicker.Init().
useAlpha
bool Empyrean.ColorPicker.ColorPicker.useAlpha = true private
Definition at line 58 of file ColorPicker.cs.
Referenced by Empyrean.ColorPicker.ColorPicker.Init(), Empyrean.ColorPicker.ColorPicker.IsAlphaBeingUsed(), and Empyrean.ColorPicker.ColorPicker.UpdateSlidersValues().
Property Documentation
Alpha
float Empyrean.ColorPicker.ColorPicker.Alpha get
Definition at line 77 of file ColorPicker.cs.
    {
        get
        {
            if (!useAlpha)
            {
                return 1f;
            }
            return alphaSlider.Value;
        }
    }
Referenced by Empyrean.ColorPicker.ColorPicker.OnColorPickedFromPalette(), and Empyrean.ColorPicker.ColorPicker.UpdateColor().
Hue
float Empyrean.ColorPicker.ColorPicker.Hue get
Definition at line 89 of file ColorPicker.cs.
Referenced by Empyrean.ColorPicker.SliderBackgroundController.GetColorByTypeAndIndex().
Saturation
float Empyrean.ColorPicker.ColorPicker.Saturation get
Definition at line 91 of file ColorPicker.cs.
Referenced by Empyrean.ColorPicker.SliderBackgroundController.GetColorByTypeAndIndex().
SelectedColor
Color Empyrean.ColorPicker.ColorPicker.SelectedColor get set
Definition at line 65 of file ColorPicker.cs.
    {
        get
        {
            return selectedColor.RGBA;
        }
        set
        {
            SelectColor(value);
        }
    }
Referenced by Empyrean.ColorPicker.SliderBackgroundController.DelayedUpdateBg(), Empyrean.ColorPicker.SliderBackgroundController.GetColorByTypeAndIndex(), LayerColorPicker.OnClickConfirm(), LayerPixelPaint.OnInit(), UIColorPicker.SetColor(), and PixelPaint.Update().
ValueHSV
float Empyrean.ColorPicker.ColorPicker.ValueHSV get
Definition at line 93 of file ColorPicker.cs.
Referenced by Empyrean.ColorPicker.SliderBackgroundController.GetColorByTypeAndIndex().
Event Documentation
ColorUpdated
Action<Color> Empyrean.ColorPicker.ColorPicker.ColorUpdated
Initial value:
= delegate
    {
    }
Definition at line 95 of file ColorPicker.cs.
Referenced by Empyrean.ColorPicker.ColorPicker.UpdateColorPicker().
The documentation for this class was generated from the following file:
Elin/Plugins.UI/Empyrean/ColorPicker/ColorPicker.cs