Elin Decompiled Documentation: LayerTitle Class Reference
LayerTitle Class Reference
Classes
class TitleType
Public Member Functions
override void OnInit ()
void Refresh ()
void OnClickStart ()
void OnChangeResolution ()
void OnClickContinue ()
void OnClickConfig ()
void OnClickMod ()
void OnClickCredit ()
void OnClickAnnounce ()
void OnClickAbout ()
void OnClickFeedback ()
void OnClickExit ()
override void OnKill ()
void OnChangeLanguage ()
Public Member Functions inherited from ELayer
override void OnBeforeAddLayer ()
void InitInspector ()
sealed override void Init ()
override void OnAfterAddLayer ()
void TryShowHelp ()
void AddLayerToUI (string id)
void TryShowHint (string _langHint=null)
void TalkHomeMemeber (string id)
void TalkMaid (string id)
override void OnRightClick ()
Public Member Functions inherited from Layer
virtual string GetTextHeader (Window window)
virtual bool HeaderIsListOf (int id)
virtual void Init ()
virtual void OnInit ()
virtual void OnAfterInit ()
virtual void ApplySkin ()
void ShowScreenLock (string id)
void UpdateInput ()
virtual void OnUpdateInput ()
virtual void OnRightClick ()
virtual bool OnBack ()
virtual void OnChangeLayer ()
virtual void OnCreate ()
void _AddLayer (string id)
Layer AddLayer (string id)
T AddLayer< T > ()
T AddLayer< T > (string id)
T AddLayerDontCloseOthers< T > ()
Layer AddLayerDontCloseOthers (Layer l)
T GetOrAddLayer< T > ()
virtual void OnBeforeAddLayer ()
virtual void OnAfterAddLayer ()
Layer AddLayer (Layer l)
void ToggleLayer (string id)
T ToggleLayer< T > (string id=null)
void WaitAndClose ()
void OnClickClose ()
virtual void Close ()
void CloseLayers ()
void RemoveLayers (bool removeImportant=false)
bool RemoveLayer< T > ()
void RemoveLayer (Layer l)
virtual void OnKill ()
Layer SetOnKill (Action action)
void DisableClose ()
void Delay (float duration=0.05f)
Layer SetDelay (float d)
Layer GetLayer (string id)
T GetLayer< T > (bool fromTop=false)
Layer GetTopLayer ()
void SwitchContent (int idWindow, int i)
virtual void OnSwitchContent (Window window)
Layer SetTitles (string langList, string idHeaderRow=null)
bool IsBlockWidgetClick ()
bool IsHideHud ()
bool IsAllowGeneralInput ()
bool IsUseBlur ()
bool IsPointerOnLayer ()
void ApplySkin ()
void OnChangeLanguage ()
void OnChangeResolution ()
Static Public Member Functions
static void KillActor ()
Static Public Member Functions inherited from ELayer
static int rnd (int a)
Static Public Member Functions inherited from Layer
static T Create< T > ()
static T Create< T > (string path)
static Layer Create (string path)
Public Attributes
TitleType[] types
LayerEditBio embark
UIText textVersion
UIText textIntro
Transform transBook
CanvasGroup cgBook
CanvasGroup cgBG
float speed
GraphicRaycaster ray
Transform titleActor
Image uiLight
RawImage imageFog
RawImage imageBG
bool toggle
bool altTitle
Public Attributes inherited from Layer
Option option
UnityEvent onKill
Anime animeIn
Anime animeOut
bool closeOthers
bool defaultActionMode = true
Button screenLock
Layer parent
string idLayer
List< Layer > layers = new List<Layer>()
Vector2 lastParentPos
List< Window > windows = new List<Window>()
string langHint
Static Public Attributes
static LayerTitle Instance
static EmbarkActor actor
Static Public Attributes inherited from Layer
static int skipInput
static bool closeOnRightClick
static bool rightClicked
static bool cancelKeyDown
static bool ignoreSounds
static Transform blurStopInstance
static string[] searchPath = new string[3] { "Layer", "Layer/Dialog", "Layer/LayerHome" }
Properties
TitleType CurrentTitle [get]
Properties inherited from ELayer
static Core core [get]
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static FactionBranch Branch [get]
static Faction Home [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static CoreConfig config [get]
static GameSetting setting [get]
static ColorProfile Colors [get]
static SourceManager sources [get]
static World world [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
bool IsFloat [get]
virtual string IdHelp [get]
Properties inherited from Layer
Layer TopLayer [get]
string uid [get]
virtual RectTransform rectLayers [get]
virtual bool blockWidgetClick [get]
Private Member Functions
void Update ()
Additional Inherited Members
Protected Member Functions inherited from ELayer
sealed override void _Close ()
sealed override void Kill ()
Protected Member Functions inherited from Layer
virtual void Awake ()
virtual void _Close ()
virtual void Kill ()
Protected Attributes inherited from Layer
RectTransform _rect
bool isDestroyed
Detailed Description
Definition at line 5 of file LayerTitle.cs.
Member Function Documentation
KillActor()
static void LayerTitle.KillActor () inline static
Definition at line 191 of file LayerTitle.cs.
    {
        if ((bool)actor)
        {
            UnityEngine.Object.DestroyImmediate(actor.gameObject);
        }
    }
References actor.
Referenced by LayerEditBio.OnClickStart(), Game.StartNewGame(), and DramaOutcome.StartNewGame2().
OnChangeLanguage()
void LayerTitle.OnChangeLanguage () inline
Implements IChangeLanguage.
Definition at line 186 of file LayerTitle.cs.
    {
        textIntro.text = IO.LoadText(CorePath.CorePackage.TextData + "intro.txt");
    }
References CorePath.CorePackage.TextData.
OnChangeResolution()
void LayerTitle.OnChangeResolution () inline
Implements IChangeResolution.
Definition at line 88 of file LayerTitle.cs.
    {
        imageBG.transform.localScale = new Vector3(Mathf.Max(1f, 1.7777778f / ((float)Screen.width / (float)Screen.height)), 1f, 1f);
    }
Referenced by Refresh().
OnClickAbout()
void LayerTitle.OnClickAbout () inline
Definition at line 124 of file LayerTitle.cs.
    {
        ELayer.ui.AddLayer("LayerAbout");
    }
References ELayer.ui.
OnClickAnnounce()
void LayerTitle.OnClickAnnounce () inline
Definition at line 119 of file LayerTitle.cs.
    {
        ELayer.ui.AddLayer("LayerAnnounce");
    }
References ELayer.ui.
OnClickConfig()
void LayerTitle.OnClickConfig () inline
Definition at line 104 of file LayerTitle.cs.
    {
        ELayer.ui.AddLayer<LayerConfig>();
    }
References ELayer.ui.
OnClickContinue()
void LayerTitle.OnClickContinue () inline
Definition at line 93 of file LayerTitle.cs.
    {
        if (ELayer.ui.GetTopLayer() is LayerTitle)
        {
            Core.TryWarnMod(delegate
            {
                ELayer.ui.AddLayer<LayerLoadGame>().Init(_backup: false);
            }, ELayer.core.mods.CountUserMod() > 0);
        }
    }
References ELayer.core, ModManager.CountUserMod(), ELayer.Init(), Core.mods, Core.TryWarnMod(), and ELayer.ui.
OnClickCredit()
void LayerTitle.OnClickCredit () inline
Definition at line 114 of file LayerTitle.cs.
    {
        ELayer.ui.AddLayer<LayerCredit>();
    }
References ELayer.ui.
OnClickExit()
void LayerTitle.OnClickExit () inline
Definition at line 134 of file LayerTitle.cs.
    {
        if (Application.isEditor)
        {
            ELayer.ui.RemoveLayer(this);
            if ((bool)actor)
            {
                UnityEngine.Object.DestroyImmediate(actor.gameObject);
            }
            ELayer.ui.AddLayer<LayerTitle>();
        }
        else
        {
            ELayer.core.Quit();
        }
    }
References actor, ELayer.core, Core.Quit(), and ELayer.ui.
OnClickFeedback()
void LayerTitle.OnClickFeedback () inline
Definition at line 129 of file LayerTitle.cs.
    {
        ELayer.ui.ToggleFeedback();
    }
References ELayer.ui.
OnClickMod()
void LayerTitle.OnClickMod () inline
Definition at line 109 of file LayerTitle.cs.
    {
        ELayer.ui.AddLayer<LayerMod>();
    }
References ELayer.ui.
OnClickStart()
void LayerTitle.OnClickStart () inline
Definition at line 76 of file LayerTitle.cs.
    {
        if (ELayer.ui.GetTopLayer() is LayerTitle)
        {
            Core.TryWarnMod(delegate
            {
                embark = ELayer.ui.AddLayer<LayerEditBio>();
                SoundManager.current.PlayBGM(CurrentTitle.bgm);
            }, ELayer.core.mods.CountUserMod() > 0);
        }
    }
References LayerTitle.TitleType.bgm, ELayer.core, ModManager.CountUserMod(), CurrentTitle, embark, Core.mods, Core.TryWarnMod(), and ELayer.ui.
OnInit()
override void LayerTitle.OnInit () inline virtual
Reimplemented from Layer.
Definition at line 57 of file LayerTitle.cs.
    {
        Instance = this;
        textVersion.text = ELayer.core.version.GetText() ?? "";
        textIntro.text = IO.LoadText(CorePath.CorePackage.TextData + "intro.txt");
        ELayer.ui.SetLight(enable: true);
        titleActor = Util.Instantiate(titleActor);
        Refresh();
        SoundManager.current.PlayBGM(CurrentTitle.bgmTitle);
    }
References LayerTitle.TitleType.bgmTitle, ELayer.core, CurrentTitle, Version.GetText(), Instance, Refresh(), CorePath.CorePackage.TextData, titleActor, ELayer.ui, Util, and BaseCore.version.
OnKill()
override void LayerTitle.OnKill () inline virtual
Reimplemented from Layer.
Definition at line 151 of file LayerTitle.cs.
    {
        UnityEngine.Object.DestroyImmediate(titleActor.gameObject);
        if ((bool)embark)
        {
            ELayer.ui.RemoveLayer(embark);
            UnityEngine.Object.DestroyImmediate(embark);
        }
        ELayer.ui.SetLight(enable: false);
    }
References embark, titleActor, and ELayer.ui.
Refresh()
void LayerTitle.Refresh () inline
Definition at line 68 of file LayerTitle.cs.
    {
        titleActor.GetComponentInChildren<SpriteRenderer>().sprite = CurrentTitle.bg;
        uiLight.color = CurrentTitle.light;
        imageFog.color = CurrentTitle.fog;
        OnChangeResolution();
    }
References LayerTitle.TitleType.bg, CurrentTitle, LayerTitle.TitleType.fog, imageFog, LayerTitle.TitleType.light, OnChangeResolution(), titleActor, and uiLight.
Referenced by OnInit(), and Update().
Update()
void LayerTitle.Update () inline private
Definition at line 162 of file LayerTitle.cs.
    {
        LayerEditBio layer = ELayer.ui.GetLayer<LayerEditBio>();
        if (!layer && SoundManager.current.currentBGM.id != CurrentTitle.bgmTitle.name)
        {
            if (toggle)
            {
                altTitle = !altTitle;
            }
            SoundManager.current.PlayBGM(CurrentTitle.bgmTitle);
            Refresh();
        }
        float num = Mathf.Clamp(cgBook.alpha + Time.smoothDeltaTime * speed * (float)((!layer) ? 1 : (-1)), 0f, 1f);
        if (cgBook.alpha != num)
        {
            cgBook.alpha = num;
        }
        if (cgBG.alpha != num)
        {
            cgBG.alpha = num;
        }
        ray.enabled = num == 1f;
    }
References altTitle, LayerTitle.TitleType.bgmTitle, cgBG, cgBook, CurrentTitle, Refresh(), speed, toggle, and ELayer.ui.
Member Data Documentation
actor
EmbarkActor LayerTitle.actor static
Definition at line 25 of file LayerTitle.cs.
Referenced by KillActor(), LayerEditBio.OnAfterAddLayer(), LayerEmbark.OnAfterAddLayer(), OnClickExit(), DramaOutcome.StartNewGame(), Game.StartNewGame(), and DramaOutcome.StartNewGame2().
altTitle
bool LayerTitle.altTitle
Definition at line 53 of file LayerTitle.cs.
Referenced by Update().
cgBG
CanvasGroup LayerTitle.cgBG
Definition at line 37 of file LayerTitle.cs.
Referenced by Update().
cgBook
CanvasGroup LayerTitle.cgBook
Definition at line 35 of file LayerTitle.cs.
Referenced by Update().
embark
LayerEditBio LayerTitle.embark
Definition at line 27 of file LayerTitle.cs.
Referenced by OnClickStart(), and OnKill().
imageBG
RawImage LayerTitle.imageBG
Definition at line 49 of file LayerTitle.cs.
imageFog
RawImage LayerTitle.imageFog
Definition at line 47 of file LayerTitle.cs.
Referenced by Refresh().
Instance
LayerTitle LayerTitle.Instance static
Definition at line 23 of file LayerTitle.cs.
Referenced by OnInit().
ray
GraphicRaycaster LayerTitle.ray
Definition at line 41 of file LayerTitle.cs.
speed
float LayerTitle.speed
Definition at line 39 of file LayerTitle.cs.
Referenced by Update().
textIntro
UIText LayerTitle.textIntro
Definition at line 31 of file LayerTitle.cs.
textVersion
UIText LayerTitle.textVersion
Definition at line 29 of file LayerTitle.cs.
titleActor
Transform LayerTitle.titleActor
Definition at line 43 of file LayerTitle.cs.
Referenced by OnInit(), OnKill(), and Refresh().
toggle
bool LayerTitle.toggle
Definition at line 51 of file LayerTitle.cs.
Referenced by Update().
transBook
Transform LayerTitle.transBook
Definition at line 33 of file LayerTitle.cs.
types
TitleType [] LayerTitle.types
Definition at line 21 of file LayerTitle.cs.
uiLight
Image LayerTitle.uiLight
Definition at line 45 of file LayerTitle.cs.
Referenced by Refresh().
Property Documentation
CurrentTitle
TitleType LayerTitle.CurrentTitle get
Definition at line 55 of file LayerTitle.cs.
Referenced by OnClickStart(), OnInit(), Refresh(), and Update().
The documentation for this class was generated from the following file:
Elin/LayerTitle.cs