Elin Decompiled Documentation: LangList Class Reference
LangList Class Reference
Classes
class Row
Public Member Functions
override Row CreateRow ()
override Row CreateRowByMapping (IReadOnlyDictionary< string, int > mapping)
override void SetRow (Row r)
override IReadOnlyDictionary< string, int > GetRowMapping ()
override IReadOnlyDictionary< string, string > GetTypeMapping ()
override string[] GetList (string id)
Public Member Functions inherited from SourceDataString< LangList.Row >
override T GetRow (string id)
Static Public Attributes
static readonly IReadOnlyDictionary< string, int > RowMapping
static readonly IReadOnlyDictionary< string, string > TypeMapping
Properties
override bool AllowHotInitialization [get]
Detailed Description
Definition at line 4 of file LangList.cs.
Member Function Documentation
CreateRow()
override Row LangList.CreateRow () inline
Definition at line 43 of file LangList.cs.
    {
        return new Row
        {
            id = SourceData.GetString(0),
            filter = SourceData.GetString(1),
            text_JP = SourceData.GetStringArray(2),
            text = SourceData.GetStringArray(3)
        };
    }
References SourceData< T, T2 >.GetString(), and SourceData< T, T2 >.GetStringArray().
CreateRowByMapping()
override Row LangList.CreateRowByMapping (IReadOnlyDictionary< string, int > mapping) inline
Definition at line 54 of file LangList.cs.
    {
        return new Row
        {
            id = SourceData.GetString(mapping["id"]),
            filter = SourceData.GetString(mapping["filter"]),
            text_JP = SourceData.GetStringArray(mapping["text_JP"]),
            text = SourceData.GetStringArray(mapping["text"])
        };
    }
References SourceData< T, T2 >.GetString(), and SourceData< T, T2 >.GetStringArray().
GetList()
override string[] LangList.GetList (string id) inline
Definition at line 80 of file LangList.cs.
    {
        Row row = map.TryGetValue(id);
        if (row == null)
        {
            return null;
        }
        if (!Lang.isBuiltin)
        {
            if (row.text_L == null || row.text_L.Length == 0)
            {
                return row.text;
            }
            return row.text_L;
        }
        if (!Lang.isJP)
        {
            return row.text;
        }
        return row.text_JP;
    }
References Lang.isBuiltin, Lang.isJP, LangList.Row.text, LangList.Row.text_JP, and LangList.Row.text_L.
GetRowMapping()
override IReadOnlyDictionary< string, int > LangList.GetRowMapping () inline
Definition at line 70 of file LangList.cs.
    {
        return RowMapping;
    }
References RowMapping.
GetTypeMapping()
override IReadOnlyDictionary< string, string > LangList.GetTypeMapping () inline
Definition at line 75 of file LangList.cs.
    {
        return TypeMapping;
    }
References TypeMapping.
SetRow()
override void LangList.SetRow (Row r) inline
Definition at line 65 of file LangList.cs.
    {
        map[r.id] = r;
    }
References LangList.Row.id.
Member Data Documentation
RowMapping
readonly IReadOnlyDictionary<string, int> LangList.RowMapping static
Initial value:
= new Dictionary<string, int>
    {
        ["id"] = 0,
        ["filter"] = 1,
        ["text_JP"] = 2,
        ["text"] = 3
    }
Definition at line 25 of file LangList.cs.
Referenced by GetRowMapping().
TypeMapping
readonly IReadOnlyDictionary<string, string> LangList.TypeMapping static
Initial value:
= new Dictionary<string, string>
    {
        ["id"] = "string",
        ["filter"] = "string",
        ["text_JP"] = "string[]",
        ["text"] = "string[]"
    }
Definition at line 33 of file LangList.cs.
Referenced by GetTypeMapping().
Property Documentation
AllowHotInitialization
override bool LangList.AllowHotInitialization get
Definition at line 41 of file LangList.cs.
The documentation for this class was generated from the following file:
Elin/Plugins.basecore/LangList.cs