Elin Decompiled Documentation: SourceCard Class Reference
SourceCard Class Reference
Public Member Functions
void Init ()
TraitCrafter GetModelCrafter (string id)
void AddRow (CardRow row, bool isChara=false)
Public Attributes
List< CardRow > rows = new List<CardRow>()
Dictionary< string, CardRow > map = new Dictionary<string, CardRow>()
Dictionary< string, CardRow > firstVariations = new Dictionary<string, CardRow>()
Dictionary< string, TraitCrafter > crafters = new Dictionary<string, TraitCrafter>()
Additional Inherited Members
Static Public Member Functions inherited from EClass
static int rnd (int a)
static int curve (int a, int start, int step, int rate=75)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Static Public Attributes inherited from EClass
static Core core
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Detailed Description
Definition at line 4 of file SourceCard.cs.
Member Function Documentation
AddRow()
void SourceCard.AddRow (CardRow row, bool isChara = false) inline
Definition at line 32 of file SourceCard.cs.
    {
        if (row.id.IsEmpty())
        {
            Debug.Log("assf");
            return;
        }
        row.isChara = isChara;
        row.elementMap = Element.GetElementMap(row.elements);
        if (row.isChara)
        {
            (row as SourceChara.Row).tileType = TileType.Obj;
        }
        else
        {
            SourceThing.Row row2 = row as SourceThing.Row;
            if (row2._tileType.IsEmpty())
            {
                row2.tileType = TileType.Obj;
            }
            else
            {
                row2.tileType = TileType.dict[row2._tileType];
            }
        }
        if (!row._origin.IsEmpty())
        {
            row.origin = EClass.sources.things.map[row._origin];
            if (!firstVariations.ContainsKey(row._origin))
            {
                firstVariations[row._origin] = row;
            }
            row.origin.isOrigin = true;
        }
        row.SetRenderData();
        rows.Add(row);
        map[row.id] = row;
    }
References CardRow._origin, RenderRow._tileType, TileType.dict, CardRow.elements, firstVariations, Element.GetElementMap(), CardRow.id, CardRow.isChara, map, TileType.Obj, rows, RenderRow.SetRenderData(), EClass.sources, and SourceManager.things.
Referenced by Init().
GetModelCrafter()
TraitCrafter SourceCard.GetModelCrafter (string id) inline
Definition at line 27 of file SourceCard.cs.
    {
        return crafters.GetOrCreate(id, () => (map[id].model.trait as TraitCrafter) ?? Trait.SelfFactory);
    }
References crafters, map, and Trait.SelfFactory.
Referenced by RecipeSource.GetReqSkill().
Init()
void SourceCard.Init () inline
Definition at line 14 of file SourceCard.cs.
    {
        foreach (SourceThing.Row row in EClass.sources.things.rows)
        {
            AddRow(row);
        }
        foreach (SourceChara.Row row2 in EClass.sources.charas.rows)
        {
            AddRow(row2, isChara: true);
        }
        SourceChara.rowDefaultPCC = EClass.sources.charas.map["chara"];
    }
References AddRow(), SourceManager.charas, EClass.sources, and SourceManager.things.
Referenced by SourceManager.Init().
Member Data Documentation
crafters
Dictionary<string, TraitCrafter> SourceCard.crafters = new Dictionary<string, TraitCrafter>()
Definition at line 12 of file SourceCard.cs.
Referenced by GetModelCrafter().
firstVariations
Dictionary<string, CardRow> SourceCard.firstVariations = new Dictionary<string, CardRow>()
Definition at line 10 of file SourceCard.cs.
Referenced by AddRow(), and Thing.SetSource().
map
Dictionary<string, CardRow> SourceCard.map = new Dictionary<string, CardRow>()
Definition at line 8 of file SourceCard.cs.
Referenced by ThingGen._Create(), WidgetStockTracker._Refresh(), AddRow(), PartialMap.Apply(), UICurrency.Build(), TraitCrafter.Craft(), RecipeCard.Craft(), RendererReplacer.CreateFrom(), SpawnList.CreateMaster(), Recipe.DropIngredients(), BiomeProfile.Style.GetIdLight(), GetModelCrafter(), Recipe.Ingredient.GetName(), DNA.GetText(), ThingContainer.GetThingStack(), TaskHarvest.HarvestThing(), TaskHarvest.HaveHarvestThing(), UIDragGridInfo.Init(), UIDragGridInfo.InitFuel(), CodexManager.ListKills(), Props.ListThingStack(), Card.MakeFoodFrom(), TaskHarvest.OnCreateProgress(), TraitBaseSpellbook.OnRead(), ResearchPlan.ParseReward(), Dialog.Recipe(), Zone.RefreshHat(), WindowChara.RefreshInfo(), UIRecipeInfo.RefreshList(), SerializedCards.Restore(), ButtonGrid.SetIngredient(), ButtonResourceTrack.SetProp(), RenderRow.SetRenderData(), TraitToolTorch.TrySetHeldAct(), and ActEffect.Wish().
rows
List<CardRow> SourceCard.rows = new List<CardRow>()
Definition at line 6 of file SourceCard.cs.
Referenced by ThingGen._Create(), AddRow(), RecipeManager.BuildList(), UIDragGridInfo.InitFuel(), Core.OnApplicationFocus(), and ActEffect.Wish().
The documentation for this class was generated from the following file:
Elin/SourceCard.cs