Elin Decompiled Documentation: ContentHomeRanking Class Reference
ContentHomeRanking Class Reference
Public Member Functions
override void OnSwitchContent (int idTab)
void Refresh ()
Public Member Functions inherited from UIContent
virtual void OnSwitchContent (int idTab)
virtual void OnInstantiate ()
Public Member Functions inherited from UINote
void Clear ()
void Build ()
void Space (int sizeY=0, int sizeX=1)
UINote AddNote (string id)
UIItem AddHeader (string text, Sprite sprite=null)
UIItem AddHeaderCard (string text, Sprite sprite=null)
UIItem AddHeaderTopic (string text, Sprite sprite=null)
UIItem AddHeader (string id, string text, Sprite sprite=null)
UIItem AddText (string text, FontColor color=FontColor.DontChange)
UIItem AddText (string id, string text, FontColor color=FontColor.DontChange)
UIItem AddText (string id, string text, Color color)
UIItem AddItem (string id)
UIItem AddTopic (string id, string text, string value=null)
UIItem AddTopic (string text, string value=null)
void AddImage (Sprite sprite)
void AddImage (string idFile)
UIButton AddButton (string text, Action onClick)
UIButton AddButtonLink (string text, string url)
UIDropdown AddDropdown (string id="DropdownDefault")
UIButton AddToggle (string idLang="", bool isOn=false, Action< bool > action=null)
Transform AddPrefab (string path)
T AddExtra< T > (string path)
Public Attributes
UIDynamicList listRanking
Color[] colors
Public Attributes inherited from UINote
RectTransform target
UINoteProfile prof
SkinType skinType
string idDefaultText
LayoutGroup layout
RectTransform cur
bool extraRebuild
Detailed Description
Definition at line 4 of file ContentHomeRanking.cs.
Member Function Documentation
OnSwitchContent()
override void ContentHomeRanking.OnSwitchContent (int idTab) inline virtual
Reimplemented from UIContent.
Definition at line 10 of file ContentHomeRanking.cs.
    {
        Refresh();
    }
References Refresh().
Refresh()
void ContentHomeRanking.Refresh () inline
Definition at line 15 of file ContentHomeRanking.cs.
    {
        List<RankedZone> ranks = EClass.game.spatials.ranks.GetList();
        UIDynamicList list = listRanking;
        list.Clear();
        list.callbacks = new UIList.Callback<RankedZone, UIItem>
        {
            onClick = delegate
            {
            },
            onRedraw = delegate(RankedZone a, UIItem b, int i)
            {
                b.text1.text = ((a.z.visitCount > 0) ? a.Name : "?????");
                b.text2.text = $"{a.Value:#,0}";
                b.text3.text = a.rank.ToString() ?? "";
                b.text4.text = a.GetFactionName();
                b.image1.sprite = a.GetSprite() ?? b.image1.sprite;
                b.image1.SetNativeSize();
                b.text3.color = colors[(a.rank > 3) ? ((a.rank <= 10) ? 1 : ((a.rank <= 100) ? 2 : 3)) : 0];
                b.image2.SetActive(a.z.IsPCFaction);
            },
            onList = delegate
            {
                foreach (RankedZone item in ranks)
                {
                    list.Add(item);
                }
            },
            onRefresh = null
        };
        list.List();
        int num = -1;
        foreach (RankedZone item2 in ranks)
        {
            if (item2.z == EClass._zone)
            {
                num = list.objects.IndexOf(item2);
            }
        }
        if (num != -1)
        {
            list.dsv.scrollByItemIndex(num);
            list.Refresh();
        }
        this.RebuildLayout(recursive: true);
    }
References $, EClass._zone, UIDynamicList.Add(), UIDynamicList.Clear(), colors, EClass.game, RankedZone.GetFactionName(), RankedZoneManager.GetList(), RankedZone.GetSprite(), UIItem.image1, UIItem.image2, Zone.IsPCFaction, item, UIDynamicList.List(), listRanking, RankedZone.Name, RankedZone.rank, SpatialManager.ranks, Game.spatials, and RankedZone.z.
Referenced by OnSwitchContent().
Member Data Documentation
colors
Color [] ContentHomeRanking.colors
Definition at line 8 of file ContentHomeRanking.cs.
Referenced by Refresh().
listRanking
UIDynamicList ContentHomeRanking.listRanking
Definition at line 6 of file ContentHomeRanking.cs.
Referenced by Refresh().
The documentation for this class was generated from the following file:
Elin/ContentHomeRanking.cs