Elin Decompiled Documentation: QuestTaskHunt Class Reference
QuestTaskHunt Class Reference
Public Types
enum Type { Default , Race }
enum Setup { Random , FighterGuild }
Public Member Functions
override bool IsComplete ()
override void OnInit ()
override void OnKillChara (Chara c)
override string GetTextProgress ()
override void OnGetDetail (ref string detail, bool onJournal)
Public Member Functions inherited from QuestTask
void SetOwner (Quest quest)
virtual bool IsComplete ()
virtual void OnInit ()
virtual void OnStart ()
virtual void OnKillChara (Chara c)
virtual void OnGiveItem (Chara c, Thing t)
virtual void OnModKarma (int a)
virtual string GetTextProgress ()
virtual void OnGetDetail (ref string detail, bool onJournal)
Static Public Member Functions
static List< SourceChara.Row > ListTargets (string idRace)
Static Public Member Functions inherited from EClass
static int rnd (int a)
static int curve (int a, int start, int step, int rate=75)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Public Attributes
int numHunted
int numRequired
string idRace
QuestTaskHunt.Type type
QuestTaskHunt.Setup setup
Public Attributes inherited from QuestTask
Quest owner
Properties
SourceRace.Row Race [get]
override string RefDrama2 [get]
override string RefDrama3 [get]
Properties inherited from QuestTask
virtual string RefDrama1 [get]
virtual string RefDrama2 [get]
virtual string RefDrama3 [get]
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Private Member Functions
void< OnKillChara > g__CountKill (ref QuestTaskHunt.<>c__DisplayClass16_0 A_1)
Additional Inherited Members
Static Public Attributes inherited from EClass
static Core core
Detailed Description
Definition at line 6 of file QuestTaskHunt.cs.
Member Enumeration Documentation
Setup
enum QuestTaskHunt.Setup
Enumerator
Random
FighterGuild
Definition at line 181 of file QuestTaskHunt.cs.
    {
        Random,
        FighterGuild
    }
Type
enum QuestTaskHunt.Type
Enumerator
Default
Race
Definition at line 175 of file QuestTaskHunt.cs.
    {
        Default,
        Race
    }
Member Function Documentation
g__CountKill()
void< OnKillChara > QuestTaskHunt.g__CountKill (ref QuestTaskHunt::<>c__DisplayClass16_0 A_1) inline private
Definition at line 150 of file QuestTaskHunt.cs.
    {
        this.numHunted++;
        if (this.numHunted > this.numRequired)
        {
            this.numHunted = this.numRequired;
            return;
        }
        this.owner.bonusMoney += EClass.curve(3 + A_1.c.LV, 50, 10, 75) * ((this.type == QuestTaskHunt.Type.Race) ? 2 : 1);
    }
References EClass.curve(), numHunted, and numRequired.
Referenced by OnKillChara().
GetTextProgress()
override string QuestTaskHunt.GetTextProgress () inline virtual
Reimplemented from QuestTask.
Definition at line 102 of file QuestTaskHunt.cs.
    {
        if (this.type == QuestTaskHunt.Type.Race)
        {
            return "progressHuntRace".lang(this.numHunted.ToString() ?? "", this.numRequired.ToString() ?? "", this.Race.GetName(), null, null);
        }
        return "progressHunt".lang(this.numHunted.ToString() ?? "", this.numRequired.ToString() ?? "", null, null, null);
    }
References numHunted, and type.
IsComplete()
override bool QuestTaskHunt.IsComplete () inline virtual
Reimplemented from QuestTask.
Definition at line 36 of file QuestTaskHunt.cs.
    {
        return this.numHunted >= this.numRequired;
    }
References numRequired.
ListTargets()
static List< SourceChara.Row > QuestTaskHunt.ListTargets (string idRace) inline static
Definition at line 41 of file QuestTaskHunt.cs.
    {
        List<SourceChara.Row> list = new List<SourceChara.Row>();
        foreach (SourceChara.Row row in EClass.sources.charas.rows)
        {
            if (row.quality == 0 && row.race == idRace && row.chance > 0 && row.hostility != "Friend")
            {
                list.Add(row);
            }
        }
        return list;
    }
References SourceManager.charas, idRace, and EClass.sources.
Referenced by OnGetDetail(), and OnInit().
OnGetDetail()
override void QuestTaskHunt.OnGetDetail (ref string detail, bool onJournal) inline virtual
Reimplemented from QuestTask.
Definition at line 111 of file QuestTaskHunt.cs.
    {
        if (this.type == QuestTaskHunt.Type.Race)
        {
            if (!onJournal)
            {
                return;
            }
            List<SourceChara.Row> list = QuestTaskHunt.ListTargets(this.idRace);
            int num = 0;
            detail = string.Concat(new string[]
            {
                detail,
                Environment.NewLine,
                Environment.NewLine,
                "target_huntRace".lang(),
                Environment.NewLine
            });
            foreach (SourceChara.Row row in list)
            {
                detail = string.Concat(new string[]
                {
                    detail,
                    row.GetName().ToTitleCase(true),
                    " (",
                    EClass.sources.races.map[this.idRace].GetName(),
                    ")"
                });
                num++;
                if (num > 5)
                {
                    break;
                }
                detail += Environment.NewLine;
            }
        }
    }
References idRace, ListTargets(), SourceManager.races, EClass.sources, and type.
OnInit()
override void QuestTaskHunt.OnInit () inline virtual
Reimplemented from QuestTask.
Definition at line 54 of file QuestTaskHunt.cs.
    {
        if (this.setup == QuestTaskHunt.Setup.FighterGuild)
        {
            this.numRequired = 20;
            this.idRace = "yeek";
            this.type = QuestTaskHunt.Type.Race;
            return;
        }
        if (this.type == QuestTaskHunt.Type.Race)
        {
            for (int i = 0; i < 100; i++)
            {
                SourceRace.Row row = EClass.sources.races.rows.RandomItem<SourceRace.Row>();
                if (QuestTaskHunt.ListTargets(row.id).Count != 0)
                {
                    this.idRace = row.id;
                }
            }
            this.numRequired = 3 + this.owner.difficulty * 2 + EClass.rnd(5);
            return;
        }
        this.numRequired = 10 + this.owner.difficulty * 3 + EClass.rnd(5);
    }
References SourceRace.Row.id, ListTargets(), SourceManager.races, EClass.rnd(), setup, EClass.sources, and type.
OnKillChara()
override void QuestTaskHunt.OnKillChara (Chara c) inline virtual
Reimplemented from QuestTask.
Definition at line 79 of file QuestTaskHunt.cs.
    {
        QuestTaskHunt.<>c__DisplayClass16_0 CS$<>8__locals1;
        CS$<>8__locals1.<>4__this = this;
        CS$<>8__locals1.c = c;
        if (CS$<>8__locals1.c.IsPCFaction)
        {
            return;
        }
        if (this.type == QuestTaskHunt.Type.Race)
        {
            if (CS$<>8__locals1.c.race.id == this.idRace)
            {
                this.<OnKillChara>g__CountKill|16_0(ref CS$<>8__locals1);
                return;
            }
        }
        else if (CS$<>8__locals1.c.OriginalHostility <= Hostility.Enemy)
        {
            this.<OnKillChara>g__CountKill|16_0(ref CS$<>8__locals1);
        }
    }
References g__CountKill(), OnKillChara(), and type.
Referenced by OnKillChara().
Member Data Documentation
idRace
string QuestTaskHunt.idRace
Definition at line 168 of file QuestTaskHunt.cs.
Referenced by ListTargets(), and OnGetDetail().
numHunted
int QuestTaskHunt.numHunted
Definition at line 162 of file QuestTaskHunt.cs.
Referenced by g__CountKill(), and GetTextProgress().
numRequired
int QuestTaskHunt.numRequired
Definition at line 165 of file QuestTaskHunt.cs.
Referenced by g__CountKill(), and IsComplete().
setup
QuestTaskHunt.Setup QuestTaskHunt.setup
Definition at line 173 of file QuestTaskHunt.cs.
Referenced by OnInit().
type
QuestTaskHunt.Type QuestTaskHunt.type
Definition at line 171 of file QuestTaskHunt.cs.
Referenced by GetTextProgress(), OnGetDetail(), OnInit(), and OnKillChara().
Property Documentation
Race
SourceRace.Row QuestTaskHunt.Race get
Definition at line 8 of file QuestTaskHunt.cs.
    {
        get
        {
            return EClass.sources.races.map[this.idRace];
        }
    }
RefDrama2
override string QuestTaskHunt.RefDrama2 get
Definition at line 16 of file QuestTaskHunt.cs.
    {
        get
        {
            if (this.type != QuestTaskHunt.Type.Race)
            {
                return "";
            }
            return this.Race.GetName();
        }
    }
RefDrama3
override string QuestTaskHunt.RefDrama3 get
Definition at line 28 of file QuestTaskHunt.cs.
    {
        get
        {
            return this.numRequired.ToString() ?? "";
        }
    }
The documentation for this class was generated from the following file:
Elin/QuestTaskHunt.cs