Elin Decompiled Documentation: Portrait Class Reference
Portrait Class Reference
Public Member Functions
void SetPerson (Person p)
void SetChara (Chara c, PCCData pccData=null)
Color GetRandomHairColor (Chara c)
void SetPortrait (string id, Color colorOverlay=default(Color), bool applyColorMod=true)
void SetPortrait (bool isPortrait, Sprite spritePortrait, Sprite spriteOverlay=null, Color colorOverlay=default(Color), Sprite spriteFull=null)
Public Member Functions inherited from UIButton
virtual bool CanMiddleClick ()
virtual void OnMiddleClick (bool forceClick)
void SetItem (Item i)
virtual void RefreshItem ()
virtual void OnHover ()
void Toggle ()
void ToggleCheck ()
void SetCheck (bool check)
void SetToggle (bool isOn, Action< bool > onToggle=null)
void SetToggleWithScore (bool isOn, Action< bool > onToggle, int? score)
void SetTooltip (Action< UITooltip > onShowTooltip=null, bool enable=true)
void SetTooltip (string id, Action< UITooltip > onShowTooltip=null, bool enable=true)
void SetTooltipLang (string lang=null)
virtual void ShowTooltip ()
void ShowTooltipForced (bool ignoreWhenRightClick=true)
override void OnPointerDown (PointerEventData eventData)
override void OnPointerClick (PointerEventData eventData)
override void OnPointerUp (PointerEventData eventData)
void OnPointerUpOnDrag (PointerEventData eventData)
void _OnPress ()
void OnPress ()
void AddHighlight (Func< bool > killCondition)
void DoHighlightTransition (bool instant=false)
void DoNormalTransition (bool instant=true)
override Selectable FindSelectableOnDown ()
override Selectable FindSelectableOnUp ()
override Selectable FindSelectableOnLeft ()
override Selectable FindSelectableOnRight ()
void SetNavigation (UIButton up, UIButton down=null, UIButton left=null, UIButton right=null)
override bool IsActive ()
void SetInteractableWithAlpha (bool enable)
virtual void ApplySkin ()
void ApplySkin ()
Static Public Member Functions
static List< ModItem< Sprite > > ListPlayerPortraits (int gender, bool nullPortrait=false)
static List< ModItem< Sprite > > ListPortraits (string idDict)
static List< ModItem< Sprite > > ListPortraits (int gender, string cat)
static string GetRandomPortrait (string idDict)
static string GetRandomPortrait (int gender, string cat)
static bool Exists (string id)
Static Public Member Functions inherited from UIButton
static void UpdateButtons ()
static void TryHihlight ()
static void TryShowTip (Transform root=null, bool highlight=true, bool ignoreWhenRightClick=true)
static void TryShowTip< T > (Transform root=null, bool highlight=true, bool ignoreWhenRightClick=false)
Public Attributes
Image portrait
Image overlay
Image imageChara
Image imageFaith
Image imageFull
Image imageFrame
Sprite spriteNoPortrait
bool enableFull = true
bool hideIfNoPortrait
bool fixSpritePos = true
bool showPortrait = true
float charaScale = 1f
Public Attributes inherited from UIButton
UIText mainText
UIText subText
UIText subText2
UIText keyText
Image icon
Image imageCheck
Graphic[] targetGraphics
float scaleIcon = 1f
float slideX
float navigationFix
bool isChecked
bool instantClick = true
UISelectableGroup group
TooltipData tooltip
SoundData soundClick
SoundData soundHighlight
Transform animeTarget
Anime animeClick
Anime animeHold
ButtonType buttonType
BaseSkinRoot skinRoot
Action onDoubleClick
Action onRightClick
Action< int > onInputWheel
object refObj
int refInt
string refStr
bool animating
bool selected
Vector3 originalIconScale = Vector3.one
UIButton highlightTarget
Item item
Static Public Attributes
static ModItemList< Sprite > modPortraitBGFs = new ModItemList<Sprite>(3)
static ModItemList< Sprite > modPortraitBGs = new ModItemList<Sprite>(3)
static ModItemList< Sprite > modPortraits = new ModItemList<Sprite>(3)
static ModItemList< Sprite > modOverlays = new ModItemList<Sprite>(3)
static ModItemList< Sprite > modFull = new ModItemList<Sprite>(3)
static Dictionary< string, List< ModItem< Sprite > > > dictList = new Dictionary<string, List<ModItem<Sprite>>>()
static HashSet< string > allIds = new HashSet<string>()
Static Public Attributes inherited from UIButton
static bool DoSlide
static bool locked
static UIButton lastButton
static UIButton lastHovered
static UIButton currentHighlight
static UIButton currentPressedButton
static float lastClicked
static float doubleClickTime = 0.4f
static Vector2 buttonPos
static Action onPressed
static List< UIButton > buttons = new List<UIButton>()
static Action actionTooltip
Private Attributes
FilterMode filter
Additional Inherited Members
Protected Member Functions inherited from UIButton
override void Awake ()
override void OnEnable ()
override void DoStateTransition (SelectionState state, bool instant)
Properties inherited from UIButton
List< Graphic > Graphics [get]
virtual bool CanDragLeftButton [get]
Detailed Description
Definition at line 6 of file Portrait.cs.
Member Function Documentation
Exists()
static bool Portrait.Exists (string id) inline static
Definition at line 115 of file Portrait.cs.
    {
        return modPortraits.dict.ContainsKey(id);
    }
References ModItemList< T >.dict, and modPortraits.
GetRandomHairColor()
Color Portrait.GetRandomHairColor (Chara c) inline
Definition at line 205 of file Portrait.cs.
    {
        Rand.SetSeed(c.uid);
        Color randomColor = PCCManager.current.GetBodySet("female").map["hair"].GetRandomColor();
        Rand.SetSeed();
        return randomColor;
    }
References Color, Rand.SetSeed(), and Card.uid.
Referenced by LayerEditPortrait.Activate(), and SetChara().
GetRandomPortrait() [1/2]
static string Portrait.GetRandomPortrait (int gender, string cat) inline static
Definition at line 110 of file Portrait.cs.
    {
        return ListPortraits(gender, cat).RandomItem().id;
    }
References ListPortraits().
GetRandomPortrait() [2/2]
static string Portrait.GetRandomPortrait (string idDict) inline static
Definition at line 105 of file Portrait.cs.
    {
        return ListPortraits(idDict).RandomItem().id;
    }
References ListPortraits().
Referenced by Chara.ApplyEditorTags(), UICharaMaker.ListGender(), and Biography.SetPortrait().
ListPlayerPortraits()
static List< ModItem< Sprite > > Portrait.ListPlayerPortraits (int gender, bool nullPortrait = false) inline static
Definition at line 48 of file Portrait.cs.
    {
        List<ModItem<Sprite>> list = ListPortraits(gender, "c").Concat(ListPortraits(gender, "guard")).Concat(ListPortraits(gender, "special")).Concat(ListPortraits(gender, "foxfolk"))
            .ToList();
        if (nullPortrait)
        {
            list.Insert(0, new ModItem<Sprite>(null));
        }
        return list;
    }
References ListPortraits().
Referenced by LayerEditPCC.SetPortraitSlider().
ListPortraits() [1/2]
static List< ModItem< Sprite > > Portrait.ListPortraits (int gender, string cat) inline static
Definition at line 77 of file Portrait.cs.
    {
        if (cat.IsEmpty())
        {
            cat = "c";
        }
        string key = cat + gender;
        List<ModItem<Sprite>> list = dictList.TryGetValue(key);
        if (list == null || list.Count == 0)
        {
            list = new List<ModItem<Sprite>>();
            foreach (ModItem<Sprite> item in modPortraits.list)
            {
                string[] array = item.id.Split('-')[0].Split('_');
                if (!(array[0] != cat))
                {
                    int num = ((array.Length > 1) ? ((array[1] == "m") ? 2 : ((array[1] == "f") ? 1 : 0)) : 0);
                    if (num == 0 || gender == 0 || gender == num)
                    {
                        list.Add(item);
                    }
                }
            }
            dictList.Add(key, list);
        }
        return list;
    }
References dictList, UIButton.item, ModItemList< T >.list, and modPortraits.
ListPortraits() [2/2]
static List< ModItem< Sprite > > Portrait.ListPortraits (string idDict) inline static
Definition at line 59 of file Portrait.cs.
    {
        List<ModItem<Sprite>> list = dictList.TryGetValue(idDict);
        if (list == null || list.Count == 0)
        {
            list = new List<ModItem<Sprite>>();
            foreach (ModItem<Sprite> item in modPortraits.list)
            {
                if (item.id.Contains(idDict))
                {
                    list.Add(item);
                }
            }
            dictList.Add(idDict, list);
        }
        return list;
    }
References dictList, UIButton.item, ModItemList< T >.list, and modPortraits.
Referenced by GetRandomPortrait(), ListPlayerPortraits(), and LayerEditPortrait.RefreshList().
SetChara()
void Portrait.SetChara (Chara c, PCCData pccData = null) inline
Definition at line 138 of file Portrait.cs.
    {
        portrait.enabled = true;
        overlay.enabled = true;
        if ((bool)imageChara)
        {
            imageChara.sprite = c.GetSprite();
            imageChara.SetNativeSize();
            if (fixSpritePos)
            {
                imageChara.transform.localScale = (c.IsPCC ? new Vector3(1.3f, 1.4f, 1f) : new Vector3(1f, 1f, 1f)) * charaScale;
                imageChara.rectTransform.pivot = (c.IsPCC ? new Vector2(0.5f, 0.3f) : new Vector2(0.5f, 0.2f));
                imageChara.rectTransform.anchoredPosition = (c.IsPCC ? new Vector2(-25f, 20f) : new Vector2(-25f, 20f));
            }
        }
        if ((bool)imageFaith)
        {
            imageFaith.sprite = c.faith.GetSprite();
        }
        if (c.GetIdPortrait().IsEmpty() || modPortraits.GetItem(c.GetIdPortrait(), returnNull: true) == null)
        {
            if (hideIfNoPortrait)
            {
                portrait.enabled = false;
                overlay.enabled = false;
                return;
            }
            if ((bool)spriteNoPortrait)
            {
                SetPortrait(isPortrait: false, spriteNoPortrait);
                return;
            }
            SetPortrait(isPortrait: false, c.GetSprite());
            c.SetImage(portrait);
            portrait.transform.localScale = new Vector3(1f, 1f, 1f);
            portrait.preserveAspect = true;
            portrait.SetNativeSize();
            portrait.Rect().SetAnchor(0.5f, 0f, 0.5f, 0f);
            portrait.Rect().SetPivot(0.5f, 0f);
            portrait.Rect().anchoredPosition = new Vector2(0f, 0f);
            portrait.material = EClass.core.refs.matUIPortraitChara;
            return;
        }
        if (pccData == null && c.isChara)
        {
            pccData = c.Chara.pccData;
        }
        Color colorOverlay = pccData?.GetHairColor(applyMod: true) ?? Color.white;
        overlay.enabled = true;
        if (pccData == null)
        {
            if (c.GetInt(105) != 0)
            {
                colorOverlay = IntColor.FromInt(c.GetInt(105));
            }
            else
            {
                colorOverlay = GetRandomHairColor(c);
                if (c.id == "shojo")
                {
                    overlay.enabled = false;
                }
            }
        }
        SetPortrait(c.GetIdPortrait(), colorOverlay);
    }
References Card.Chara, charaScale, Color, EClass.core, Chara.faith, fixSpritePos, IntColor.FromInt(), Chara.GetIdPortrait(), BaseCard.GetInt(), ModItemList< T >.GetItem(), GetRandomHairColor(), Religion.GetSprite(), Chara.GetSprite(), hideIfNoPortrait, Card.id, imageChara, imageFaith, Chara.isChara, CoreRef.matUIPortraitChara, modPortraits, Chara.pccData, portrait, Core.refs, Card.SetImage(), SetPortrait(), and spriteNoPortrait.
Referenced by LayerEditPortrait.Activate(), UICharaMaker.EditPCC(), UICharaMaker.ListGender(), LayerEditPCC.OnClickChangePortrait(), UICharaMaker.OnClickChangePortrait(), LayerEditPortrait.OnClickClear(), WindowChara.OnClickPortrait(), LayerEditPortrait.RefreshList(), WindowChara.RefreshStatic(), UICharaMaker.RerollHair(), UICharaMaker.RerollPCC(), ButtonGeneral.SetCard(), ButtonRoster.SetChara(), UICharaMaker.SetChara(), ItemGachaResult.SetChara(), ButtonChara.SetChara(), and SetPerson().
SetPerson()
void Portrait.SetPerson (Person p) inline
Definition at line 120 of file Portrait.cs.
    {
        if (p.hasChara)
        {
            SetChara(p.chara);
        }
        else if (!p.idPortrait.IsEmpty())
        {
            Rand.SetSeed(p.uidChara);
            SetPortrait(p.idPortrait, PCCManager.current.GetBodySet("female").map["hair"].GetRandomColor());
            Rand.SetSeed();
        }
        else
        {
            SetPortrait(p.source.portrait);
        }
    }
References Person.chara, Person.hasChara, Person.idPortrait, SetChara(), SetPortrait(), Rand.SetSeed(), Person.source, and Person.uidChara.
Referenced by ContentQuest.SelectQuest(), ItemQuest.SetQuest(), and DramaActor.Talk().
SetPortrait() [1/2]
void Portrait.SetPortrait (bool isPortrait, Sprite spritePortrait, Sprite spriteOverlay = null, Color colorOverlay = default(Color), Sprite spriteFull = null) inline
Definition at line 225 of file Portrait.cs.
    {
        filter = ((isPortrait && Core.Instance.config.test.aaPortrait) ? FilterMode.Bilinear : FilterMode.Point);
        portrait.rectTransform.anchorMin = overlay.rectTransform.anchorMin;
        portrait.rectTransform.anchorMax = overlay.rectTransform.anchorMax;
        portrait.rectTransform.sizeDelta = overlay.rectTransform.sizeDelta;
        if ((bool)spritePortrait)
        {
            portrait.sprite = spritePortrait;
            FixTexture(spritePortrait);
        }
        if ((bool)overlay)
        {
            FixTexture(spriteOverlay);
            overlay.sprite = spriteOverlay;
            overlay.color = new Color(colorOverlay.r * 1.1f, colorOverlay.g * 1.1f, colorOverlay.b * 1.1f, colorOverlay.a);
            overlay.SetActive(spriteOverlay);
        }
        if (enableFull && (bool)imageFull)
        {
            FixTexture(spriteFull);
            imageFull.sprite = spriteFull;
            base.gameObject.SetActive(!spriteFull);
            imageFull.SetActive(spriteFull);
        }
        if (!showPortrait)
        {
            portrait.SetActive(enable: false);
            overlay.SetActive(enable: false);
        }
        void FixTexture(Sprite s)
        {
            if ((bool)s && isPortrait)
            {
                s.texture.wrapMode = TextureWrapMode.Clamp;
                if (s.texture.filterMode != filter)
                {
                    s.texture.filterMode = filter;
                }
            }
        }
    }
References CoreConfig.Test.aaPortrait, Color, Core.config, enableFull, filter, imageFull, Core.Instance, overlay, portrait, showPortrait, and CoreConfig.test.
SetPortrait() [2/2]
void Portrait.SetPortrait (string id, Color colorOverlay = default(Color), bool applyColorMod = true) inline
Definition at line 213 of file Portrait.cs.
    {
        Sprite @object = modPortraits.GetItem(id).GetObject();
        Sprite object2 = modOverlays.GetObject(id + "-overlay");
        Sprite spriteFull = ((enableFull && (bool)imageFull) ? modFull.GetObject(id + "-full") : null);
        if (applyColorMod)
        {
            colorOverlay = PCCManager.current.ApplyColorMod(colorOverlay);
        }
        SetPortrait(isPortrait: true, @object, object2, colorOverlay, spriteFull);
    }
References enableFull, ModItemList< T >.GetItem(), ModItemList< T >.GetObject(), imageFull, modFull, modOverlays, modPortraits, and SetPortrait().
Referenced by LayerLoadGame.RefreshInfo(), LayerEditPortrait.RefreshList(), SetChara(), SetPerson(), and SetPortrait().
Member Data Documentation
allIds
HashSet<string> Portrait.allIds = new HashSet<string>() static
Definition at line 20 of file Portrait.cs.
Referenced by Chara.GetIdPortrait(), and ModManager.ParseExtra().
charaScale
float Portrait.charaScale = 1f
Definition at line 44 of file Portrait.cs.
Referenced by SetChara().
dictList
Dictionary<string, List<ModItem<Sprite> > > Portrait.dictList = new Dictionary<string, List<ModItem<Sprite>>>() static
Definition at line 18 of file Portrait.cs.
Referenced by ListPortraits().
enableFull
bool Portrait.enableFull = true
Definition at line 36 of file Portrait.cs.
Referenced by SetPortrait().
filter
FilterMode Portrait.filter private
Definition at line 46 of file Portrait.cs.
Referenced by SetPortrait().
fixSpritePos
bool Portrait.fixSpritePos = true
Definition at line 40 of file Portrait.cs.
Referenced by SetChara().
hideIfNoPortrait
bool Portrait.hideIfNoPortrait
Definition at line 38 of file Portrait.cs.
Referenced by SetChara().
imageChara
Image Portrait.imageChara
Definition at line 26 of file Portrait.cs.
Referenced by SetChara().
imageFaith
Image Portrait.imageFaith
Definition at line 28 of file Portrait.cs.
Referenced by SetChara().
imageFrame
Image Portrait.imageFrame
Definition at line 32 of file Portrait.cs.
imageFull
Image Portrait.imageFull
Definition at line 30 of file Portrait.cs.
Referenced by SetPortrait().
modFull
ModItemList<Sprite> Portrait.modFull = new ModItemList<Sprite>(3) static
Definition at line 16 of file Portrait.cs.
Referenced by ModManager.ParseExtra(), and SetPortrait().
modOverlays
ModItemList<Sprite> Portrait.modOverlays = new ModItemList<Sprite>(3) static
Definition at line 14 of file Portrait.cs.
Referenced by ModManager.ParseExtra(), and SetPortrait().
modPortraitBGFs
ModItemList<Sprite> Portrait.modPortraitBGFs = new ModItemList<Sprite>(3) static
Definition at line 8 of file Portrait.cs.
Referenced by ModManager.ParseExtra(), WindowChara.RefreshStatic(), and WindowChara.SetPortraitFrame().
modPortraitBGs
ModItemList<Sprite> Portrait.modPortraitBGs = new ModItemList<Sprite>(3) static
Definition at line 10 of file Portrait.cs.
Referenced by ModManager.ParseExtra(), WindowChara.RefreshStatic(), and WindowChara.SetPortraitBG().
modPortraits
ModItemList<Sprite> Portrait.modPortraits = new ModItemList<Sprite>(3) static
Definition at line 12 of file Portrait.cs.
Referenced by Exists(), ListPortraits(), ModManager.ParseExtra(), Person.Person(), LayerNewspaper.RefreshNews(), SetChara(), and SetPortrait().
overlay
Image Portrait.overlay
Definition at line 24 of file Portrait.cs.
Referenced by SetPortrait().
portrait
Image Portrait.portrait
Definition at line 22 of file Portrait.cs.
Referenced by SetChara(), and SetPortrait().
showPortrait
bool Portrait.showPortrait = true
Definition at line 42 of file Portrait.cs.
Referenced by SetPortrait().
spriteNoPortrait
Sprite Portrait.spriteNoPortrait
Definition at line 34 of file Portrait.cs.
Referenced by SetChara().
The documentation for this class was generated from the following file:
Elin/Portrait.cs