Elin Decompiled Documentation: SurvivalManager Class Reference
SurvivalManager Class Reference
Classes
class Flags
Public Member Functions
ZoneEventRaid GetRaidEvent ()
void Meteor (Point pos, Action action)
void MeteorThing (Point pos, string id, bool install=false)
void MeteorThing (Point pos, Thing t, bool install=false)
void RefreshRewards ()
void OnExpandFloor (Point pos)
void CheckLoytelDebt ()
bool OnMineWreck (Point point)
Point GetRandomPoint ()
List< SourceChara.Row > ListUnrecruitedUniques ()
void OnUpdateRecruit (FactionBranch branch)
void StartRaid ()
Public Attributes
Flags flags = new Flags()
List< string > listReward = new List<string>()
Properties
bool IsInRaid [get]
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Additional Inherited Members
Static Public Member Functions inherited from EClass
static int rndSeed (int a, int seed)
static int rnd (long a)
static int rnd (int a)
static int curve (int a, int start, int step, int rate=75)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Static Public Attributes inherited from EClass
static Core core
Detailed Description
Definition at line 8 of file SurvivalManager.cs.
Member Function Documentation
CheckLoytelDebt()
void SurvivalManager.CheckLoytelDebt () inline
Definition at line 257 of file SurvivalManager.cs.
    {
        if (EClass.game.cards.globalCharas.Find("loytel") != null && !EClass.game.quests.IsAdded<QuestDebt>())
        {
            Quest quest = EClass.game.quests.Add("debt", "loytel");
            EClass.game.quests.globalList.Remove(quest);
            EClass.game.quests.Start(quest);
        }
    }
References QuestManager.Add(), Game.cards, CardManager.GlobalCharaList.Find(), EClass.game, CardManager.globalCharas, QuestManager.globalList, Game.quests, and QuestManager.Start().
Referenced by OnExpandFloor(), and OnMineWreck().
GetRaidEvent()
ZoneEventRaid SurvivalManager.GetRaidEvent () inline
Definition at line 146 of file SurvivalManager.cs.
    {
        return EClass._zone.events.GetEvent<ZoneEventRaid>();
    }
References EClass._zone, and Zone.events.
GetRandomPoint()
Point SurvivalManager.GetRandomPoint () inline
Definition at line 407 of file SurvivalManager.cs.
    {
        TraitCoreZone traitCoreZone = EClass._map.FindThing<TraitCoreZone>();
        Point point = ((traitCoreZone != null) ? traitCoreZone.owner.pos : EClass._map.GetCenterPos());
        List<Cell> list = new List<Cell>();
        EClass._map.ForeachSphere(point.x, point.z, 50f, delegate(Point p)
        {
            if (!p.IsSky && !p.IsBlocked && !p.HasObj && !p.HasThing)
            {
                list.Add(p.cell);
            }
        });
        if (list.Count == 0)
        {
            return null;
        }
        return list.RandomItem().GetPoint();
    }
References EClass._map, Map.FindThing(), Map.ForeachSphere(), MapBounds.GetCenterPos(), Point.HasObj, Point.HasThing, Point.IsBlocked, Point.IsSky, Trait.owner, and Card.pos.
Referenced by ZoneEventRaid.OnKill(), and OnMineWreck().
ListUnrecruitedUniques()
List< SourceChara.Row > SurvivalManager.ListUnrecruitedUniques () inline
Definition at line 426 of file SurvivalManager.cs.
    {
        return EClass.sources.charas.rows.Where(delegate(SourceChara.Row r)
        {
            if (r.quality != 4 || r.race == "god" || r.size.Length != 0)
            {
                return false;
            }
            switch (r.id)
            {
            case "fiama":
            case "loytel":
            case "nino":
            case "big_daddy":
            case "littleOne":
            case "sorin":
            case "vesda":
            case "azzrasizzle":
                return false;
            default:
                if (EClass.game.cards.globalCharas.Find(r.id) == null)
                {
                    return r.LV < flags.raidLv + 10;
                }
                return false;
            }
        }).ToList();
    }
References SourceManager.charas, and EClass.sources.
Meteor()
void SurvivalManager.Meteor (Point pos, Action action) inline
Definition at line 151 of file SurvivalManager.cs.
    {
        EffectMeteor.Create(pos, 0, 1, delegate
        {
            action();
        });
    }
References EffectMeteor.Create().
MeteorThing() [1/2]
void SurvivalManager.MeteorThing (Point pos, string id, bool install = false) inline
Definition at line 159 of file SurvivalManager.cs.
    {
        Meteor(pos, delegate
        {
            Card card = EClass._zone.AddCard(ThingGen.Create(id), pos);
            if (card.id == "rod_wish")
            {
                card.SetCharge(1);
            }
            if (install)
            {
                card.Install();
            }
        });
    }
References EClass._zone, Zone.AddCard(), card, ThingGen.Create(), if(), and Meteor.
Referenced by ZoneEventRaid.OnKill(), and OnMineWreck().
MeteorThing() [2/2]
void SurvivalManager.MeteorThing (Point pos, Thing t, bool install = false) inline
Definition at line 175 of file SurvivalManager.cs.
    {
        Meteor(pos, delegate
        {
            Card card = EClass._zone.AddCard(t, pos);
            if (install)
            {
                card.Install();
            }
        });
    }
References EClass._zone, Zone.AddCard(), card, and Meteor.
OnExpandFloor()
void SurvivalManager.OnExpandFloor (Point pos) inline
Definition at line 210 of file SurvivalManager.cs.
    {
        int i = 0;
        bool done = false;
        EClass._map.ForeachCell(delegate(Cell c)
        {
            if (!c.sourceFloor.tileType.IsSkipFloor)
            {
                i++;
            }
        });
        Check(6, delegate
        {
            EClass._zone.ClaimZone(debug: false, pos);
        });
        Check(9, delegate
        {
            EClass.pc.homeBranch.AddMemeber(EClass._zone.AddCard(CharaGen.Create("shojo"), pos.x, pos.z).Chara);
        });
        Check(20, delegate
        {
            EClass.pc.homeBranch.AddMemeber(EClass._zone.AddCard(CharaGen.Create("fiama"), pos.x, pos.z).Chara);
        });
        Check(40, delegate
        {
            EClass.pc.homeBranch.AddMemeber(EClass._zone.AddCard(CharaGen.Create("nino"), pos.x, pos.z).Chara);
        });
        Check(60, delegate
        {
            EClass.pc.homeBranch.AddMemeber(EClass._zone.AddCard(CharaGen.Create("loytel"), pos.x, pos.z).Chara);
            CheckLoytelDebt();
        });
        Check(80, delegate
        {
            EClass._zone.AddCard(ThingGen.Create("core_defense"), pos).Install();
        });
        void Check(int a, Action action)
        {
            if (!done && flags.floors < a && i >= a)
            {
                Meteor(pos, action);
                EClass.game.survival.flags.floors = a;
                done = true;
            }
        }
    }
References EClass._map, EClass._zone, Zone.AddCard(), FactionBranch.AddMemeber(), Card.Chara, CheckLoytelDebt(), Zone.ClaimZone(), ThingGen.Create(), CharaGen.Create(), EClass.debug, flags, SurvivalManager.Flags.floors, Map.ForeachCell(), Chara.homeBranch, Card.Install(), Meteor, EClass.pc, Cell.sourceFloor, Point.x, and Point.z.
Referenced by TaskBuild.OnProgressComplete().
OnMineWreck()
bool SurvivalManager.OnMineWreck (Point point) inline
Definition at line 267 of file SurvivalManager.cs.
    {
        if (EClass._zone.events.GetEvent<ZoneEventSurvival>() == null)
        {
            EClass._zone.events.Add(new ZoneEventSurvival());
        }
        CheckLoytelDebt();
        SourceObj.Row sourceObj = point.cell.sourceObj;
        int searchWreck = EClass.game.survival.flags.searchWreck;
        string[] array = new string[6] { "log", "rock", "branch", "bone", "grass", "vine" };
        int chanceChange = 25;
        int num = searchWreck / 50 + 1;
        if (searchWreck == 0)
        {
            Thing t2 = ThingGen.CreateParcel(null, ThingGen.Create("log").SetNum(6), ThingGen.Create("rock").SetNum(4), ThingGen.Create("resin").SetNum(2), ThingGen.Create("money2").SetNum(10), ThingGen.Create("1267"), ThingGen.CreateRod(50311, 8));
            Pop(t2);
        }
        switch (sourceObj.alias)
        {
        case "nest_bird":
            chanceChange = 65;
            return Pop(ThingGen.Create((EClass.rnd(10) == 0) ? "egg_fertilized" : "_egg").TryMakeRandomItem(num));
        case "wreck_wood":
            array = new string[8] { "log", "log", "branch", "grass", "vine", "resin", "leaf", "chunk" };
            break;
        case "wreck_junk":
            chanceChange = 100;
            return Pop(ThingGen.CreateFromFilter("shop_junk", num));
        case "wreck_stone":
            chanceChange = 30;
            array = new string[4] { "rock", "rock", "stone", "bone" };
            break;
        case "wreck_scrap":
            chanceChange = 75;
            array = new string[1] { "scrap" };
            break;
        case "wreck_cloth":
            chanceChange = 75;
            array = new string[1] { "fiber" };
            break;
        case "wreck_precious":
            chanceChange = 100;
            return Pop(ThingGen.CreateFromFilter("shop_magic", num));
        default:
            return false;
        }
        if (EClass.rnd(3 + EClass.game.survival.flags.spawnedFloor * 2) == 0 && EClass.game.survival.flags.spawnedFloor < 8)
        {
            EClass.game.survival.flags.spawnedFloor++;
            switch (EClass.game.survival.flags.spawnedFloor)
            {
            case 5:
            case 6:
                return Pop(ThingGen.CreateFloor(33, 97).SetNum(3));
            case 7:
            case 8:
                return Pop(ThingGen.CreateFloor(43, 66).SetNum(3));
            default:
                return Pop(ThingGen.CreateFloor(40, 45).SetNum(3));
            }
        }
        if (EClass.rnd(20) == 0)
        {
            return Pop(TraitSeed.MakeRandomSeed());
        }
        if (EClass.rnd(12 + num / 5) == 0)
        {
            return Pop(ThingGen.Create("money2"));
        }
        if (searchWreck > 10 && EClass.rnd(40 + num) == 0)
        {
            TreasureType treasureType = ((EClass.rnd(10) == 0) ? TreasureType.BossNefia : ((EClass.rnd(10) == 0) ? TreasureType.Map : TreasureType.RandomChest));
            Thing t3 = ThingGen.Create(treasureType switch
            {
                TreasureType.Map => "chest_treasure",
                TreasureType.BossNefia => "chest_boss",
                _ => "chest3",
            });
            ThingGen.CreateTreasureContent(t3, num, treasureType, clearContent: true);
            MeteorThing(GetRandomPoint(), t3, install: true);
        }
        if (EClass.rnd(12) == 0)
        {
            Point pos = point.GetNearestPoint(allowBlock: false, allowChara: false, allowInstalled: false, ignoreCenter: true) ?? point;
            if (searchWreck < 100 || EClass.rnd(3) != 0)
            {
                EClass._zone.SpawnMob(pos, SpawnSetting.HomeWild(num));
            }
            else
            {
                EClass._zone.SpawnMob(pos, SpawnSetting.HomeEnemy(Mathf.Max(num - 5, 1)));
            }
        }
        return Pop(ThingGen.Create(array.RandomItem()).SetNum(1 + EClass.rnd(3)));
        bool Next()
        {
            EClass.game.survival.flags.searchWreck++;
            int searchWreck2 = EClass.game.survival.flags.searchWreck;
            Point pos2 = point.GetNearestPoint(allowBlock: false, allowChara: false, allowInstalled: false, ignoreCenter: true) ?? point;
            if (searchWreck2 == 20)
            {
                Thing container = ThingGen.CreateParcel(null, ThingGen.CreateRecipe("container_shipping"), ThingGen.CreateRecipe("stonecutter"), ThingGen.CreateRecipe("workbench2"));
                Meteor(pos2, delegate
                {
                    EClass._zone.AddCard(container, pos2);
                });
            }
            if (searchWreck2 > (EClass.debug.enable ? 5 : 100) && !flags.gotTaxChest)
            {
                MeteorThing(pos2, "chest_tax");
                flags.gotTaxChest = true;
            }
            if (searchWreck2 > (EClass.debug.enable ? 10 : 200) && !flags.gotGaragara)
            {
                MeteorThing(pos2, "rolling_fortune");
                flags.gotGaragara = true;
            }
            NextObj();
            return true;
        }
        void NextObj()
        {
            if (EClass.rnd(100) < chanceChange)
            {
                string[] source = new string[12]
                {
                    "nest_bird", "wreck_wood", "wreck_wood", "wreck_wood", "wreck_wood", "wreck_wood", "wreck_stone", "wreck_stone", "wreck_scrap", "wreck_junk",
                    "wreck_cloth", "wreck_precious"
                };
                EClass._map.SetObj(point.x, point.z, EClass.sources.objs.alias[source.RandomItem()].id);
            }
        }
        bool Pop(Thing t)
        {
            EClass._map.TrySmoothPick(point, t, EClass.pc);
            Next();
            return true;
        }
    }
References EClass._map, EClass._zone, ZoneEventManager.Add(), Zone.AddCard(), TileRow.alias, Point.cell, CheckLoytelDebt(), ThingGen.Create(), ThingGen.CreateFloor(), ThingGen.CreateFromFilter(), ThingGen.CreateParcel(), ThingGen.CreateRecipe(), ThingGen.CreateRod(), ThingGen.CreateTreasureContent(), EClass.debug, CoreDebug.enable, Zone.events, flags, EClass.game, Point.GetNearestPoint(), GetRandomPoint(), SurvivalManager.Flags.gotGaragara, SurvivalManager.Flags.gotTaxChest, SpawnSetting.HomeEnemy(), SpawnSetting.HomeWild(), TraitSeed.MakeRandomSeed(), Meteor, MeteorThing(), Next, SourceManager.objs, EClass.pc, EClass.rnd(), SurvivalManager.Flags.searchWreck, Card.SetNum(), Map.SetObj(), Cell.sourceObj, EClass.sources, SurvivalManager.Flags.spawnedFloor, Zone.SpawnMob(), Game.survival, Card.TryMakeRandomItem(), Map.TrySmoothPick(), Point.x, and Point.z.
Referenced by Map.MineObj().
OnUpdateRecruit()
void SurvivalManager.OnUpdateRecruit (FactionBranch branch) inline
Definition at line 455 of file SurvivalManager.cs.
    {
        List<SourceChara.Row> list = ListUnrecruitedUniques();
        for (int i = 0; i < (EClass.debug.enable ? 10 : 2); i++)
        {
            SourceChara.Row row = list.RandomItem();
            if (row != null)
            {
                Chara chara = CharaGen.Create(row.id);
                chara.RemoveEditorTag(EditorTag.AINoMove);
                branch.AddRecruit(chara);
                list.Remove(row);
            }
        }
    }
References FactionBranch.AddRecruit(), CharaGen.Create(), CardRow.id, and Card.RemoveEditorTag().
RefreshRewards()
void SurvivalManager.RefreshRewards () inline
Definition at line 187 of file SurvivalManager.cs.
    {
        if (listReward.Count <= 0)
        {
            Add(new string[7] { "659", "758", "759", "806", "828", "1190", "1191" });
            if (flags.raidLv < 50)
            {
                Add(new string[7] { "pillow_jure", "pillow_ehekatl", "pillow_opatos", "pillow_kumiromi", "pillow_lulwy", "pillow_mani", "pillow_itzpalt" });
            }
            else
            {
                Add(new string[1] { "rod_wish" });
            }
        }
        void Add(string[] ids)
        {
            foreach (string item in ids)
            {
                listReward.Add(item);
            }
        }
    }
References Add(), flags, item, listReward, and SurvivalManager.Flags.raidLv.
Referenced by ZoneEventRaid.OnKill().
StartRaid()
void SurvivalManager.StartRaid () inline
Definition at line 471 of file SurvivalManager.cs.
    {
        flags.raid = true;
        Point pos = EClass.pc.pos.GetNearestPoint(allowBlock: false, allowChara: false, allowInstalled: false, ignoreCenter: true) ?? EClass.pc.pos;
        Meteor(pos, delegate
        {
            EClass._zone.AddCard(ThingGen.Create("teleporter_demon"), pos).Install();
        });
        flags.dateNextRaid = EClass.world.date.GetRaw(72);
    }
References EClass._zone, Zone.AddCard(), ThingGen.Create(), World.date, Point.GetNearestPoint(), Date.GetRaw(), Card.Install(), Meteor, EClass.pc, Card.pos, and EClass.world.
Referenced by TraitCoreDefense.TrySetAct().
Member Data Documentation
flags
Flags SurvivalManager.flags = new Flags()
Definition at line 139 of file SurvivalManager.cs.
Referenced by WidgetDate._Refresh(), OnExpandFloor(), ZoneEventRaid.OnInit(), ZoneEventRaid.OnKill(), OnMineWreck(), ZoneEventSurvival.OnTickRound(), RefreshRewards(), TraitCoreDefense.TrySetAct(), and TraitSpotBiome.Update().
listReward
List<string> SurvivalManager.listReward = new List<string>()
Definition at line 142 of file SurvivalManager.cs.
Referenced by ZoneEventRaid.OnKill(), and RefreshRewards().
Property Documentation
IsInRaid
bool SurvivalManager.IsInRaid get
Definition at line 144 of file SurvivalManager.cs.
Referenced by ZoneEventSurvival.OnTickRound(), and TraitCoreDefense.TrySetAct().
The documentation for this class was generated from the following file:
Elin/SurvivalManager.cs