Elin Decompiled Documentation: DynamicAsset< T > Class Template Reference
DynamicAsset< T > Class Template Reference
Public Member Functions
DynamicAsset ()
DynamicAsset (string groupId, bool instantiate)
T GetNew (string id, Transform parent=null)
T GetOriginal (string id)
Public Attributes
string groupId = ""
List< T > list = new List<T>()
Dictionary< string, T > map
bool usePool
bool instantiate = true
Private Member Functions
void Init ()
Private Attributes
bool initialized
Detailed Description
Type Constraints
T : MonoBehaviour
Definition at line 6 of file DynamicAsset.cs.
Constructor & Destructor Documentation
DynamicAsset() [1/2]
DynamicAsset< T >.DynamicAsset () inline
Definition at line 20 of file DynamicAsset.cs.
    {
    }
DynamicAsset() [2/2]
DynamicAsset< T >.DynamicAsset (string groupId, bool instantiate) inline
Definition at line 24 of file DynamicAsset.cs.
    {
        this.groupId = groupId;
        this.instantiate = instantiate;
    }
References DynamicAsset< T >.groupId, and DynamicAsset< T >.instantiate.
Member Function Documentation
GetNew()
T DynamicAsset< T >.GetNew (string id, Transform parent = null) inline
Definition at line 40 of file DynamicAsset.cs.
    {
        T original = GetOriginal(id);
        if (!instantiate || original == null)
        {
            return original;
        }
        T val = (usePool ? PoolManager.Spawn<T>(groupId + "/" + id, groupId + "/" + id) : UnityEngine.Object.Instantiate(original).GetComponent<T>());
        if ((bool)parent)
        {
            val.transform.SetParent(parent, worldPositionStays: false);
        }
        return val;
    }
References DynamicAsset< T >.GetOriginal(), DynamicAsset< T >.groupId, DynamicAsset< T >.instantiate, PoolManager.Spawn(), and DynamicAsset< T >.usePool.
GetOriginal()
T DynamicAsset< T >.GetOriginal (string id) inline
Definition at line 55 of file DynamicAsset.cs.
    {
        if (!initialized)
        {
            Init();
        }
        if (map.TryGetValue(id, out var value))
        {
            return value;
        }
        value = Resources.Load<T>(groupId + "/" + id);
        map[id] = value;
        list.Add(value);
        return value;
    }
References DynamicAsset< T >.groupId, DynamicAsset< T >.Init(), DynamicAsset< T >.initialized, DynamicAsset< T >.list, and DynamicAsset< T >.map.
Referenced by DynamicAsset< T >.GetNew().
Init()
void DynamicAsset< T >.Init () inline private
Definition at line 30 of file DynamicAsset.cs.
    {
        map = new Dictionary<string, T>();
        foreach (T item in list)
        {
            map.Add(item.name, item);
        }
        initialized = true;
    }
References DynamicAsset< T >.initialized, item, DynamicAsset< T >.list, and DynamicAsset< T >.map.
Referenced by DynamicAsset< T >.GetOriginal().
Member Data Documentation
groupId
string DynamicAsset< T >.groupId = ""
Definition at line 8 of file DynamicAsset.cs.
Referenced by DynamicAsset< T >.DynamicAsset(), DynamicAsset< T >.GetNew(), and DynamicAsset< T >.GetOriginal().
initialized
bool DynamicAsset< T >.initialized private
Definition at line 18 of file DynamicAsset.cs.
Referenced by DynamicAsset< T >.GetOriginal(), and DynamicAsset< T >.Init().
instantiate
bool DynamicAsset< T >.instantiate = true
Definition at line 16 of file DynamicAsset.cs.
Referenced by DynamicAsset< T >.DynamicAsset(), and DynamicAsset< T >.GetNew().
list
List<T> DynamicAsset< T >.list = new List<T>()
Definition at line 10 of file DynamicAsset.cs.
Referenced by DynamicAsset< T >.GetOriginal(), and DynamicAsset< T >.Init().
map
Dictionary<string, T> DynamicAsset< T >.map
Definition at line 12 of file DynamicAsset.cs.
Referenced by DynamicAsset< T >.GetOriginal(), and DynamicAsset< T >.Init().
usePool
bool DynamicAsset< T >.usePool
Definition at line 14 of file DynamicAsset.cs.
Referenced by DynamicAsset< T >.GetNew(), and Effect.Kill().
The documentation for this class was generated from the following file:
Elin/Plugins.basecore/DynamicAsset.cs