Elin Decompiled Documentation: AI_PassTime Class Reference
AI_PassTime Class Reference
Public Types
enum Type { passTime , meditate , selfHarm }
Public Types inherited from AIAct
enum Status { Running , Fail , Success }
Public Types inherited from Act
enum CostType {
None , MP , SP , None ,
MP , SP
}
enum CostType {
None , MP , SP , None ,
MP , SP
}
Public Member Functions
override bool CanManualCancel ()
override MultiSprite GetStateIcon ()
override void OnStart ()
override IEnumerable< Status > Run ()
override void OnCancel ()
Public Member Functions inherited from AIAct
override string ToString ()
override MultiSprite GetStateIcon ()
virtual Point GetDestination ()
AIProgress GetProgress ()
string GetCurrentActionText ()
override bool IsToolValid ()
virtual void OnStart ()
void SetOwner (Chara c)
virtual void OnSetOwner ()
void SetChild (AIAct seq, Func< Status > _onChildFail=null)
void Start ()
override bool Perform ()
Status Restart ()
Status Success (Action action=null)
virtual void OnSuccess ()
bool TryCancel (Card c)
virtual Status Cancel ()
virtual void OnCancel ()
virtual void OnCancelOrSuccess ()
virtual bool CanManualCancel ()
Status KeepRunning ()
void Reset ()
virtual void OnReset ()
Status Tick ()
virtual IEnumerable< Status > Run ()
Status TickChild ()
Status Do (AIAct _seq, Func< Status > _onChildFail=null)
Status DoGotoInteraction (Point pos, Func< Status > _onChildFail=null)
Status DoGoto (Point pos, int dist=0, bool ignoreConnection=false, Func< Status > _onChildFail=null)
Status DoGoto (Card card, Func< Status > _onChildFail=null)
Status DoGoto (Card card, int dist, Func< Status > _onChildFail=null)
Status DoGotoSpot (Card card, Func< Status > _onChildFail=null)
Status DoGoto< T > (Func< Status > _onChildFail=null)
Status DoGotoSpot< T > (Func< Status > _onChildFail=null, bool ignoreAccessType=false)
Status DoGrab (Card card, int num=-1, bool pickHeld=false, Func< Status > _onChildFail=null)
Status DoGrab< T > ()
Status DoProgress ()
Status DoIdle (int repeat=3)
Status DoWait (int count=1)
virtual AIProgress CreateProgress ()
virtual void OnCreateProgress (Progress_Custom p)
virtual bool CanProgress ()
virtual void OnBeforeProgress ()
virtual void OnProgress ()
virtual void OnProgressComplete ()
void SimulateZone (int days)
virtual void OnSimulateZone (int days)
virtual void OnSimulatePosition ()
Public Member Functions inherited from Act
virtual CursorInfo GetCursorIcon (Card c)
virtual MultiSprite GetStateIcon ()
override Sprite GetSprite ()
virtual bool ShowMouseHint (Card c)
virtual bool IsValidTC (Card c)
virtual string GetHintText (string str="")
virtual string GetText (string str="")
virtual string GetTextSmall (Card c)
virtual Color GetActPlanColor ()
virtual bool Perform ()
virtual bool CanPerform ()
bool Perform (Chara _cc, Card _tc=null, Point _tp=null)
bool CanPerform (Chara _cc, Card _tc=null, Point _tp=null)
virtual bool IsToolValid ()
new void SetImage (Image image)
virtual void OnMarkMapHighlights ()
virtual bool ShouldMapHighlight (Point p)
virtual CursorInfo GetCursorIcon (Card c)
virtual MultiSprite GetStateIcon ()
override Sprite GetSprite ()
virtual bool ShowMouseHint (Card c)
virtual bool IsValidTC (Card c)
virtual string GetHintText (string str="")
virtual string GetText (string str="")
virtual string GetTextSmall (Card c)
virtual Color GetActPlanColor ()
virtual bool Perform ()
virtual bool CanPerform ()
bool Perform (Chara _cc, Card _tc=null, Point _tp=null)
bool CanPerform (Chara _cc, Card _tc=null, Point _tp=null)
virtual bool IsToolValid ()
new void SetImage (Image image)
virtual void OnMarkMapHighlights ()
virtual bool ShouldMapHighlight (Point p)
Public Member Functions inherited from Element
virtual SourceElement.Row GetSource ()
virtual int GetSourcePotential (int v)
virtual Sprite GetSprite ()
int GetMaterialSourceValue (Thing t, int v)
virtual int GetSourceValue (int v, int lv, SourceValueType type)
virtual Sprite GetIcon (string suffix="")
int SortVal (bool charaSheet=false)
virtual bool CanLink (ElementContainer owner)
bool HasTag (string tag)
void SetImage (Image i)
virtual string GetDetail ()
bool IsFactionElement (Chara c)
Element GetParent (Card c)
void WriteNote (UINote n, ElementContainer owner=null, Action< UINote > onWriteNote=null)
void WriteNoteWithRef (UINote n, ElementContainer owner, Action< UINote > onWriteNote, Element refEle)
void _WriteNote (UINote n, Chara c, Act act)
void _WriteNote (UINote n, ElementContainer owner, Action< UINote > onWriteNote, bool isRef, bool addHeader=true)
virtual void OnWriteNote (UINote n, ElementContainer owner)
virtual void OnChangeValue ()
void CheckLevelBonus (ElementContainer owner, UINote n=null)
int GetSortVal (UIList.SortMode m)
virtual Act.Cost GetCost (Chara c)
virtual int GetPower (Card c)
virtual void SetTextValue (UIText text)
virtual SourceElement.Row GetSource ()
virtual int GetSourcePotential (int v)
virtual Sprite GetSprite ()
int GetMaterialSourceValue (Thing t, int v)
virtual int GetSourceValue (int v, int lv, SourceValueType type)
virtual Sprite GetIcon (string suffix="")
int SortVal (bool charaSheet=false)
virtual bool CanLink (ElementContainer owner)
bool HasTag (string tag)
void SetImage (Image i)
virtual string GetDetail ()
bool IsFactionElement (Chara c)
Element GetParent (Card c)
void WriteNote (UINote n, ElementContainer owner=null, Action< UINote > onWriteNote=null)
void WriteNoteWithRef (UINote n, ElementContainer owner, Action< UINote > onWriteNote, Element refEle)
void _WriteNote (UINote n, Chara c, Act act)
void _WriteNote (UINote n, ElementContainer owner, Action< UINote > onWriteNote, bool isRef, bool addHeader=true)
virtual void OnWriteNote (UINote n, ElementContainer owner)
virtual void OnChangeValue ()
void CheckLevelBonus (ElementContainer owner, UINote n=null)
int GetSortVal (UIList.SortMode m)
virtual Act.Cost GetCost (Chara c)
virtual int GetPower (Card c)
virtual void SetTextValue (UIText text)
Public Attributes
Thing target
bool startedFull
Public Attributes inherited from AIAct
new Chara owner
Status status
IEnumerator< Status > Enumerator
AIAct child
AIAct parent
byte restartCount
Func< Status > onChildFail
Func< bool > isFail
Public Attributes inherited from Element
SourceElement.Row _source
int id
int vBase
int vExp
int vPotential
int vTempPotential
int vLink
int vSource
int vSourcePotential
ElementContainer owner
Properties
virtual Type type [get]
virtual int exp [get]
virtual int turns [get]
override bool IsAutoTurn [get]
override bool LocalAct [get]
override TargetType TargetType [get]
bool IsFull [get]
Properties inherited from AIAct
virtual bool IsRunning [get]
bool IsChildRunning [get]
bool IsMoveAI [get]
virtual int MaxRestart [get]
virtual new string Name [get]
virtual MultiSprite stateIcon [get]
virtual Sprite actionIcon [get]
virtual bool IsNoGoal [get]
virtual bool IsAutoTurn [get]
virtual bool IsIdle [get]
virtual bool PushChara [get]
virtual int MaxProgress [get]
virtual bool ShowProgress [get]
virtual bool UseTurbo [get]
virtual int CurrentProgress [get]
virtual bool ShowCursor [get]
virtual bool CancelWhenDamaged [get]
virtual bool CancelWhenMoved [get]
virtual bool InformCancel [get]
virtual Thing RenderThing [get]
AIAct Current [get]
override bool IsAct [get]
override bool ShowPotential [get]
override bool UsePotential [get]
override bool ShowRelativeAttribute [get]
virtual bool HasProgress [get]
Properties inherited from Act
override bool ShowPotential [get]
override bool UsePotential [get]
override bool ShowRelativeAttribute [get]
virtual CursorInfo CursorIcon [get]
virtual string ID [get]
virtual bool IsAct [get]
virtual bool WillEndTurn [get]
virtual bool CloseLayers [get]
virtual int LeftHand [get]
virtual int RightHand [get]
virtual int ElementPowerMod [get]
virtual bool ShowMapHighlight [get]
virtual bool ShowMapHighlightBlock [get]
virtual bool PickHeldOnStart [get]
virtual bool DropHeldOnStart [get]
virtual bool CanPressRepeat [get]
virtual bool CanAutofire [get]
virtual bool ResetAxis [get]
virtual bool RequireTool [get]
virtual bool IsHostileAct [get]
virtual bool HideRightInfo [get]
virtual bool HaveLongPressAction [get]
virtual float Radius [get]
virtual int PerformDistance [get]
virtual int MaxRadius [get]
virtual TargetType TargetType [get]
virtual bool LocalAct [get]
virtual bool CanRapidFire [get]
virtual float RapidDelay [get]
virtual bool ShowAuto [get]
virtual bool IsCrime [get]
Properties inherited from Element
SourceElement.Row source [get]
virtual int DisplayValue [get]
virtual int MinValue [get]
int Value [get]
int ValueWithoutLink [get]
virtual int MinPotential [get]
int Potential [get]
virtual bool CanGainExp [get]
bool IsFlag [get]
virtual string Name [get]
virtual string FullName [get]
virtual int ExpToNext [get]
virtual bool UseExpMod [get]
virtual int CostTrain [get]
virtual int CostLearn [get]
virtual bool ShowXP [get]
virtual bool ShowMsgOnValueChanged [get]
virtual bool ShowValue [get]
virtual bool ShowPotential [get]
virtual bool UsePotential [get]
virtual bool PotentialAsStock [get]
virtual bool ShowRelativeAttribute [get]
virtual bool ShowBonuses [get]
virtual string ShortName [get]
bool IsGlobalElement [get]
bool IsFactionWideElement [get]
bool IsPartyWideElement [get]
virtual bool ShowEncNumber [get]
bool IsTrait [get]
bool IsFoodTrait [get]
bool IsFoodTraitMain [get]
bool IsMainAttribute [get]
Act act [get]
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Additional Inherited Members
Static Public Member Functions inherited from Act
static void SetReference (Chara _cc, Card _tc=null, Point _tp=null)
static void SetTool (Thing t)
static void SetReference (Chara _cc, Card _tc=null, Point _tp=null)
static void SetTool (Thing t)
Static Public Member Functions inherited from Element
static string GetName (string alias)
static SourceElement.Row Get (int id)
static Dictionary< int, int > GetElementMap (int[] list)
static Dictionary< int, int > GetElementMap (int[] list, Dictionary< int, int > map)
static SourceElement.Row GetRandomElement (int lv=1)
static Element Create (int id, int v=0)
static Element Create (string id, int v=1)
static int GetId (string alias)
static int GetResistLv (int v)
static int GetResistDamage (int dmg, int v)
static string GetName (string alias)
static SourceElement.Row Get (int id)
static Dictionary< int, int > GetElementMap (int[] list)
static Dictionary< int, int > GetElementMap (int[] list, Dictionary< int, int > map)
static SourceElement.Row GetRandomElement (int lv=1)
static Element Create (int id, int v=0)
static Element Create (string id, int v=1)
static int GetId (string alias)
static int GetResistLv (int v)
static int GetResistDamage (int dmg, int v)
Static Public Member Functions inherited from EClass
static int rnd (int a)
static int curve (int a, int start, int step, int rate=75)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Static Public Attributes inherited from Act
static Chara CC
static Card TC
static Point TP = new Point()
static Thing TOOL
static int powerMod = 100
static bool forcePt
Static Public Attributes inherited from Element
const int Div = 5
static Element Void = new Element()
static int[] List_MainAttributes
static int[] List_MainAttributesMajor
static int[] List_Body
static int[] List_Mind
static List< SourceElement.Row > ListElements = new List<SourceElement.Row>()
static List< SourceElement.Row > ListAttackElements = new List<SourceElement.Row>()
Static Public Attributes inherited from EClass
static Core core
Static Package Functions inherited from Element
static string< _WriteNote > g__Calc (ref Element.<>c__DisplayClass103_0 A_0)
Detailed Description
Definition at line 3 of file AI_PassTime.cs.
Member Enumeration Documentation
Type
enum AI_PassTime.Type
Enumerator
passTime
meditate
selfHarm
Definition at line 5 of file AI_PassTime.cs.
    {
        passTime,
        meditate,
        selfHarm
    }
Member Function Documentation
CanManualCancel()
override bool AI_PassTime.CanManualCancel () inline virtual
Reimplemented from AIAct.
Definition at line 54 of file AI_PassTime.cs.
    {
        return true;
    }
GetStateIcon()
override MultiSprite AI_PassTime.GetStateIcon () inline virtual
Reimplemented from Act.
Definition at line 59 of file AI_PassTime.cs.
    {
        return type switch
        {
            Type.meditate => EClass.core.refs.stateIcons.meditation,
            Type.selfHarm => EClass.core.refs.stateIcons.selfharm,
            _ => base.GetStateIcon(),
        };
    }
References EClass.core, CoreRef.StateIcons.meditation, Core.refs, CoreRef.StateIcons.selfharm, CoreRef.stateIcons, and type.
OnCancel()
override void AI_PassTime.OnCancel () inline virtual
Reimplemented from AIAct.
Definition at line 150 of file AI_PassTime.cs.
    {
        if (owner != null)
        {
            owner.Say(type.ToString() + "_end", owner);
        }
    }
References AIAct.owner, Card.Say(), and type.
OnStart()
override void AI_PassTime.OnStart () inline virtual
Reimplemented from AIAct.
Definition at line 69 of file AI_PassTime.cs.
    {
        startedFull = IsFull;
    }
References IsFull, and startedFull.
Run()
override IEnumerable< Status > AI_PassTime.Run () inline virtual
Reimplemented from AIAct.
Definition at line 74 of file AI_PassTime.cs.
    {
        if (target != null)
        {
            yield return DoGoto(target.pos);
        }
        owner.Say(type.ToString() + "_start", owner);
        for (int i = 0; i < turns; i++)
        {
            if (exp > 0 && i % 5 == 0)
            {
                owner.ModExp(GetType().Name, exp);
            }
            if (type == Type.selfHarm)
            {
                if (EClass.rnd(10) == 0)
                {
                    owner.AddCondition<ConBleed>(50);
                }
                else if (EClass.rnd(10) == 0)
                {
                    owner.DamageHP(5 + EClass.rnd(5));
                    if (owner != null)
                    {
                        owner.Teleport(ActEffect.GetTeleportPos(EClass.pc.pos));
                    }
                }
            }
            else
            {
                foreach (Chara member in EClass.pc.party.members)
                {
                    bool flag = false;
                    foreach (Condition condition in member.conditions)
                    {
                        if (condition.PreventRegen)
{
                            flag = true;
                        }
                    }
                    if (!flag)
                    {
                        int num = 1 + EClass.pc.Evalue(6003) / 5;
                        if (EClass.rnd(3) == 0)
{
                            member.HealHP(num * (member.IsPC ? 1 : 2));
                        }
                        member.mana.Mod(num * (member.IsPC ? 1 : 2));
                    }
                }
                if (i == 50 && EClass.pc.pos.IsHotSpring && (!EClass.pc.IsPCC || EClass.pc.pccData.state == PCCState.Undie))
                {
                    int p = (EClass._zone.elements.Has(3701) ? 150 : 100);
                    foreach (Chara member2 in EClass.pc.party.members)
                    {
                        member2.AddCondition<ConHotspring>(p)?.SetPerfume();
                    }
                }
                if (!startedFull && IsFull)
                {
                    yield return Success();
                }
                if (!EClass.debug.enable && owner.CanSleep() && EClass.rnd(10) == 0)
                {
                    owner.Sleep();
                    yield return Success();
                }
            }
            yield return KeepRunning();
        }
        if (owner != null)
        {
            owner.Say(type.ToString() + "_end", owner);
        }
    }
References EClass._zone, Chara.AddCondition(), Chara.CanSleep(), Chara.conditions, Card.DamageHP(), EClass.debug, AIAct.DoGoto(), Zone.elements, CoreDebug.enable, Card.Evalue(), exp, ActEffect.GetTeleportPos(), ElementContainer.Has(), Card.HealHP(), IsFull, Point.IsHotSpring, Chara.IsPC, Chara.IsPCC, AIAct.KeepRunning(), Chara.mana, Party.members, Stats.Mod(), Card.ModExp(), AIAct.Name, AIAct.owner, Chara.party, EClass.pc, Chara.pccData, Card.pos, BaseCondition.PreventRegen, EClass.rnd(), Card.Say(), Chara.Sleep(), startedFull, AIAct.Success, target, Card.Teleport(), turns, and type.
Member Data Documentation
startedFull
bool AI_PassTime.startedFull
Definition at line 14 of file AI_PassTime.cs.
Referenced by OnStart(), and Run().
target
Thing AI_PassTime.target
Definition at line 12 of file AI_PassTime.cs.
Referenced by Run().
Property Documentation
exp
virtual int AI_PassTime.exp get
Definition at line 18 of file AI_PassTime.cs.
Referenced by Run().
IsAutoTurn
override bool AI_PassTime.IsAutoTurn get
Definition at line 22 of file AI_PassTime.cs.
IsFull
bool AI_PassTime.IsFull get
Definition at line 38 of file AI_PassTime.cs.
    {
        get
        {
            if (owner != null)
            {
                if (owner.hp == owner.MaxHP)
                {
                    return owner.mana.value == owner.mana.max;
                }
                return false;
            }
            return true;
        }
    }
Referenced by OnStart(), and Run().
LocalAct
override bool AI_PassTime.LocalAct get
Definition at line 24 of file AI_PassTime.cs.
TargetType
override TargetType AI_PassTime.TargetType get
Definition at line 26 of file AI_PassTime.cs.
    {
        get
        {
            if (type != 0)
            {
                return TargetType.Self;
            }
            return TargetType.Any;
        }
    }
turns
virtual int AI_PassTime.turns get
Definition at line 20 of file AI_PassTime.cs.
Referenced by Run().
type
virtual Type AI_PassTime.type get
Definition at line 16 of file AI_PassTime.cs.
Referenced by GetStateIcon(), OnCancel(), and Run().
The documentation for this class was generated from the following file:
Elin/AI_PassTime.cs