Elin Decompiled Documentation: BaseCore Class Reference
BaseCore Class Reference
Public Member Functions
virtual void ConsumeInput ()
void WaitForEndOfFrame (Action action)
virtual void StopEventSystem (float duration=0.2f)
virtual void StopEventSystem (Component c, Action action, float duration=0.15f)
virtual void FreezeScreen (float duration=0.3f)
virtual void UnfreezeScreen ()
virtual void RebuildBGMList ()
Public Attributes
Version version
Version versionMoongate
Version versionMod
ReleaseMode releaseMode
string langCode
EventSystem eventSystem
List< Action > actionsLateUpdate = new List<Action>()
List< Action > actionsNextFrame = new List<Action>()
Canvas canvas
string forceLangCode
int frame
Static Public Attributes
static bool IsOffline
static BaseCore Instance
static bool resetRuntime
static Func< bool > BlockInput
Protected Member Functions
virtual void Awake ()
Protected Attributes
int lastScreenWidth
int lastScreenHeight
Properties
virtual float uiScale [get]
Private Member Functions
IEnumerator _WaitForEndOfFrame (Action action)
Detailed Description
Definition at line 7 of file BaseCore.cs.
Member Function Documentation
_WaitForEndOfFrame()
IEnumerator BaseCore._WaitForEndOfFrame (Action action) inline private
Definition at line 66 of file BaseCore.cs.
    {
        yield return new WaitForEndOfFrame();
        action();
    }
References WaitForEndOfFrame().
Referenced by WaitForEndOfFrame().
Awake()
virtual void BaseCore.Awake () inline protected virtual
Reimplemented in Core, and CoreEmu.
Definition at line 48 of file BaseCore.cs.
    {
        GameObject[] array = GameObject.FindGameObjectsWithTag("Temp");
        for (int i = 0; i < array.Length; i++)
        {
            UnityEngine.Object.DestroyImmediate(array[i]);
        }
    }
ConsumeInput()
virtual void BaseCore.ConsumeInput () inline virtual
Reimplemented in Core.
Definition at line 57 of file BaseCore.cs.
    {
    }
Referenced by UIContextMenu.Hide().
FreezeScreen()
virtual void BaseCore.FreezeScreen (float duration = 0::3f) inline virtual
Reimplemented in Core.
Definition at line 80 of file BaseCore.cs.
    {
    }
Referenced by UIDynamicList.List(), and ListPeopleCallReserve.OnClick().
RebuildBGMList()
virtual void BaseCore.RebuildBGMList () inline virtual
Reimplemented in Core.
Definition at line 88 of file BaseCore.cs.
    {
    }
StopEventSystem() [1/2]
virtual void BaseCore.StopEventSystem (Component c, Action action, float duration = 0::15f) inline virtual
Reimplemented in Core.
Definition at line 76 of file BaseCore.cs.
    {
    }
StopEventSystem() [2/2]
virtual void BaseCore.StopEventSystem (float duration = 0::2f) inline virtual
Reimplemented in Core.
Definition at line 72 of file BaseCore.cs.
    {
    }
Referenced by UIList.RemoveDynamic().
UnfreezeScreen()
virtual void BaseCore.UnfreezeScreen () inline virtual
Reimplemented in Core.
Definition at line 84 of file BaseCore.cs.
    {
    }
Referenced by UIDynamicList.List().
WaitForEndOfFrame()
void BaseCore.WaitForEndOfFrame (Action action) inline
Definition at line 61 of file BaseCore.cs.
    {
        StartCoroutine(_WaitForEndOfFrame(action));
    }
References _WaitForEndOfFrame().
Referenced by AM_Adv._OnUpdateInput(), _WaitForEndOfFrame(), Layer.Delay(), WidgetManager.DialogLoad(), WidgetManager.DialogSave(), PartialMap.ExportDialog(), Zone.ExportDialog(), AM_Copy.ImportDialog(), Zone.ImportDialog(), Scene.Init(), UIDynamicList.List(), ContentConfigOther.OnClickDownloadWallpaper(), WidgetSceneCustomizer.OnClickLoad(), WidgetSceneCustomizer.OnClickSave(), LayerEditHouse.OnInit(), LayerList.OnKill(), UIButton.OnPointerClick(), UIButton.OnPointerDown(), Card.SetPaintData(), CoreDebug.UpdateInput(), and Layer.WaitAndClose().
Member Data Documentation
actionsLateUpdate
List<Action> BaseCore.actionsLateUpdate = new List<Action>()
Definition at line 29 of file BaseCore.cs.
Referenced by BaseTileMap.DrawTile(), Window.Init(), Core.LateUpdate(), UIFollow.LateUpdate(), TCUI.OnDraw(), and UIText.SetText().
actionsNextFrame
List<Action> BaseCore.actionsNextFrame = new List<Action>()
Definition at line 31 of file BaseCore.cs.
Referenced by InvOwnerIdentify._OnProcess(), HyphenationJpn._SetText(), UICharaMaker.ListJob(), UICharaMaker.ListRace(), LayerInventory.OnAfterInit(), Core.OnApplicationFocus(), BaseListPeople.OnInstantiate(), WidgetHotbar.OnSetContextMenu(), AM_Paint.OnUpdateInput(), Tutorial.Play(), CoreDebug.QuickStart(), Player.RefreshCurrentHotItem(), UIDynamicList.RefreshHighlight(), UIScreenshot.SavePreview(), PartialMap.SavePreview(), TCText.Say(), UI.StartDrag(), Game.StartNewGame(), DramaOutcome.StartNewGame2(), DramaActor.Talk(), ActThrow.Throw(), ButtonAbility.TryUse(), Dialog.TryWarn(), and Core.Update().
BlockInput
Func<bool> BaseCore.BlockInput static
Definition at line 15 of file BaseCore.cs.
Referenced by Layer.OnClickClose().
canvas
Canvas BaseCore.canvas
Definition at line 34 of file BaseCore.cs.
Referenced by CoreConfig.ApplyScale(), Core.Awake(), Util.ClampToScreen(), and SkinManager.SetFonts().
eventSystem
EventSystem BaseCore.eventSystem
Definition at line 27 of file BaseCore.cs.
Referenced by UIContextMenu.Hide(), and ELayer.Kill().
forceLangCode
string BaseCore.forceLangCode
Definition at line 37 of file BaseCore.cs.
Referenced by Core.Awake(), and Core.StartCase().
frame
int BaseCore.frame
Definition at line 40 of file BaseCore.cs.
Referenced by Core.Update().
Instance
BaseCore BaseCore.Instance static
Definition at line 11 of file BaseCore.cs.
Referenced by HyphenationJpn._SetText(), Util.ClampToScreen(), PopManager.CopyAll(), Layer.Delay(), Map.ExportMetaData(), SourceData< T, T2 >.ExportTexts(), UIContextMenu.Hide(), Window.Init(), BaseModPackage.IsValidVersion(), ELayer.Kill(), UIFollow.LateUpdate(), UIDynamicList.List(), ListPeopleCallReserve.OnClick(), UIButton.OnPointerClick(), UIButton.OnPointerDown(), PopManager.Pop(), UIContextMenuPopper.PositionMenu(), UIDynamicList.RefreshHighlight(), UIList.RemoveDynamic(), SkinManager.SetFonts(), UIText.SetText(), LangSetting.SetVersion(), and Layer.WaitAndClose().
IsOffline
bool BaseCore.IsOffline static
Definition at line 9 of file BaseCore.cs.
Referenced by ModManager.Init(), LayerMod.OnInit(), and Core.StartCase().
langCode
string BaseCore.langCode
Definition at line 25 of file BaseCore.cs.
Referenced by CoreConfig.Init(), and Core.StartCase().
lastScreenHeight
int BaseCore.lastScreenHeight protected
Definition at line 44 of file BaseCore.cs.
Referenced by Core.Update().
lastScreenWidth
int BaseCore.lastScreenWidth protected
Definition at line 42 of file BaseCore.cs.
Referenced by Core.Update().
releaseMode
ReleaseMode BaseCore.releaseMode
Definition at line 23 of file BaseCore.cs.
Referenced by Core.Awake(), and CoreDebug.UpdateInput().
resetRuntime
bool BaseCore.resetRuntime static
Definition at line 13 of file BaseCore.cs.
Referenced by Core.Awake().
version
Version BaseCore.version
Definition at line 17 of file BaseCore.cs.
Referenced by WidgetSystemIndicator._Refresh(), Core.Awake(), GameIO.CanLoad(), GameIndex.Create(), Map.ExportMetaData(), SourceData< T, T2 >.ExportTexts(), Net.DownloadMeta.IsValidVersion(), Card.LevelUp(), FactionBranch.ModExp(), WidgetFeed.OnActivate(), WidgetMainText.OnActivate(), LayerHelp.OnAfterInit(), LayerFeedback.OnInit(), LayerMod.OnInit(), LayerTitle.OnInit(), TraitMoongate.OnUse(), TraitMoongateEx.OnUse(), Zone.OnVisit(), ModManager.ParseExtra(), LayerLoadGame.RefreshInfo(), LayerLoadGame.RefreshList(), CoreConfig.Save(), Game.Save(), Map.Save(), Net.SendChat(), LangSetting.SetVersion(), UI.ToggleFeedback(), CoreConfig.TryLoadConfig(), TraitCoreZone.TrySetAct(), TraitWaystone.TrySetAct(), Net.UploadFile(), and Map.ValidateVersion().
versionMod
Version BaseCore.versionMod
Definition at line 21 of file BaseCore.cs.
Referenced by BaseModPackage.IsValidVersion().
versionMoongate
Version BaseCore.versionMoongate
Definition at line 19 of file BaseCore.cs.
Referenced by MapMetaData.IsValidVersion(), and Net.DownloadMeta.IsValidVersion().
Property Documentation
uiScale
virtual float BaseCore.uiScale get
Definition at line 46 of file BaseCore.cs.
Referenced by PopManager.CopyAll(), Window.Init(), UIFollow.LateUpdate(), PopManager.Pop(), and UIContextMenuPopper.PositionMenu().
The documentation for this class was generated from the following file:
Elin/Plugins.basecore/BaseCore.cs