Elin Decompiled Documentation: LayerInventory Class Reference
LayerInventory Class Reference
Public Member Functions
bool IsPlayerContainer (bool includePlayer=false)
Card GetPlayerContainer ()
override bool HeaderIsListOf (int id)
override void OnInit ()
override void OnAfterInit ()
UIInventory SetInv (int idWindow=0)
override void OnUpdateInput ()
override void OnKill ()
override void OnRightClick ()
Public Member Functions inherited from ELayer
override void OnBeforeAddLayer ()
void InitInspector ()
sealed override void Init ()
override void OnAfterAddLayer ()
void TryShowHelp ()
void AddLayerToUI (string id)
void TryShowHint (string _langHint=null)
void TalkHomeMemeber (string id)
void TalkMaid (string id)
override void OnRightClick ()
Public Member Functions inherited from Layer
virtual string GetTextHeader (Window window)
virtual bool HeaderIsListOf (int id)
virtual void Init ()
virtual void OnInit ()
virtual void OnAfterInit ()
virtual void ApplySkin ()
void ShowScreenLock (string id)
void UpdateInput ()
virtual void OnUpdateInput ()
virtual void OnRightClick ()
virtual bool OnBack ()
virtual void OnChangeLayer ()
virtual void OnCreate ()
void _AddLayer (string id)
Layer AddLayer (string id)
T AddLayer< T > ()
T AddLayer< T > (string id)
T AddLayerDontCloseOthers< T > ()
Layer AddLayerDontCloseOthers (Layer l)
T GetOrAddLayer< T > ()
virtual void OnBeforeAddLayer ()
virtual void OnAfterAddLayer ()
Layer AddLayer (Layer l)
void ToggleLayer (string id)
T ToggleLayer< T > (string id=null)
void WaitAndClose ()
void OnClickClose ()
virtual void Close ()
void CloseLayers ()
void RemoveLayers (bool removeImportant=false)
bool RemoveLayer< T > ()
void RemoveLayer (Layer l)
virtual void OnKill ()
Layer SetOnKill (Action action)
void DisableClose ()
void Delay (float duration=0.05f)
Layer SetDelay (float d)
Layer GetLayer (string id)
T GetLayer< T > (bool fromTop=false)
Layer GetTopLayer ()
void SwitchContent (int idWindow, int i)
virtual void OnSwitchContent (Window window)
Layer SetTitles (string langList, string idHeaderRow=null)
bool IsBlockWidgetClick ()
bool IsHideHud ()
bool IsAllowGeneralInput ()
bool IsUseBlur ()
bool IsPointerOnLayer ()
void ApplySkin ()
Static Public Member Functions
static LayerInventory GetTopLayer (Thing t, bool includePlayer=false, InvOwner exclude=null)
static LayerInventory GetLayer (Card t)
static LayerInventory GetPCLayer ()
static void Close (Thing t)
static bool IsOpen (Thing t)
static void SetDirty (Thing t)
static void SetDirtyAll (bool immediate=false)
static void TryShowGuide (UIList list)
static void TryShowGuide (List< ButtonGrid > list)
static LayerInventory _Create (string path="")
static LayerInventory CreatePCBackpack (bool mousePos=false)
static bool CloseAllyInv (Chara c)
static void CloseAllyInv ()
static LayerInventory CreateContainerAlly (Chara owner, Card container)
static bool IsOpen (Card container)
static LayerInventory CreateContainerPC (Card container)
static LayerInventory CreateContainer (Card owner)
static LayerInventory CreateContainer (Card owner, Card container)
static LayerInventory CreateContainer< T > (Card c, Card container, CurrencyType currency=CurrencyType.None)
static LayerInventory CreateBuy (Card c, CurrencyType currency=CurrencyType.Money, PriceType price=PriceType.Default)
Static Public Member Functions inherited from ELayer
static int rnd (int a)
Static Public Member Functions inherited from Layer
static T Create< T > ()
static T Create< T > (string path)
static Layer Create (string path)
Public Attributes
List< UIInventory > invs = new List<UIInventory>()
UICurrency uiCurrency
bool floatInv
bool mainInv
WindowCharaMini mini
bool wasInventoryOpen
Public Attributes inherited from Layer
Option option
UnityEvent onKill
Anime animeIn
Anime animeOut
bool closeOthers
bool defaultActionMode = true
Button screenLock
Layer parent
string idLayer
List< Layer > layers = new List<Layer>()
Vector2 lastParentPos
List< Window > windows = new List<Window>()
string langHint
Static Public Attributes
static List< LayerInventory > listInv = new List<LayerInventory>()
static InvOwner highlightInv
Static Public Attributes inherited from Layer
static int skipInput
static bool closeOnRightClick
static bool rightClicked
static bool cancelKeyDown
static bool ignoreSounds
static Transform blurStopInstance
static string[] searchPath = new string[3] { "Layer", "Layer/Dialog", "Layer/LayerHome" }
Properties
InvOwner Inv [get]
Properties inherited from ELayer
static Core core [get]
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static FactionBranch Branch [get]
static Faction Home [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static CoreConfig config [get]
static GameSetting setting [get]
static ColorProfile Colors [get]
static SourceManager sources [get]
static World world [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
bool IsFloat [get]
virtual string IdHelp [get]
Properties inherited from Layer
Layer TopLayer [get]
string uid [get]
virtual RectTransform rectLayers [get]
virtual bool blockWidgetClick [get]
Private Member Functions
void OnDestroy ()
Additional Inherited Members
Protected Member Functions inherited from ELayer
sealed override void _Close ()
sealed override void Kill ()
Protected Member Functions inherited from Layer
virtual void Awake ()
virtual void _Close ()
virtual void Kill ()
Protected Attributes inherited from Layer
RectTransform _rect
bool isDestroyed
Detailed Description
Definition at line 5 of file LayerInventory.cs.
Member Function Documentation
_Create()
static LayerInventory LayerInventory._Create (string path = "") inline static
Definition at line 344 of file LayerInventory.cs.
    {
        if (ELayer.game.altInv && path.IsEmpty())
        {
            path = "LayerInventoryGrid";
        }
        return Layer.Create(path.IsEmpty() ? "LayerInventory" : ("LayerInventory/" + path)) as LayerInventory;
    }
References Game.altInv, Layer.Create(), and ELayer.game.
Referenced by CreateBuy(), CreateContainer(), CreateContainer< T >(), CreateContainerAlly(), CreateContainerPC(), and CreatePCBackpack().
Close()
static void LayerInventory.Close (Thing t) inline static
Definition at line 63 of file LayerInventory.cs.
    {
        foreach (LayerInventory item in listInv)
        {
            if (item.invs[0].owner.Container == t)
            {
                item.Close();
                break;
            }
        }
    }
References item, and listInv.
Referenced by ActionMode.UpdateInput().
CloseAllyInv() [1/2]
static void LayerInventory.CloseAllyInv () inline static
Definition at line 379 of file LayerInventory.cs.
    {
        foreach (LayerInventory item in listInv.Copy())
        {
            if (!item.IsPlayerContainer(includePlayer: true))
            {
                ELayer.ui.layerFloat.RemoveLayer(item);
            }
        }
    }
References item, listInv, and ELayer.ui.
Referenced by CreateContainerAlly().
CloseAllyInv() [2/2]
static bool LayerInventory.CloseAllyInv (Chara c) inline static
Definition at line 366 of file LayerInventory.cs.
    {
        foreach (LayerInventory item in listInv.Copy())
        {
            if (item.Inv.owner == c)
            {
                ELayer.ui.layerFloat.RemoveLayer(item);
                return true;
            }
        }
        return false;
    }
References item, listInv, and ELayer.ui.
Referenced by LayerDragGrid.OnKill(), and LayerDragGrid.SetInv().
CreateBuy()
static LayerInventory LayerInventory.CreateBuy (Card c, CurrencyType currency = CurrencyType::Money, PriceType price = PriceType::Default) inline static
Definition at line 613 of file LayerInventory.cs.
    {
        LayerInventory layerInventory = _Create();
        UIInventory uIInventory = layerInventory.SetInv();
        Thing thing = c.things.Find("chest_merchant");
        SE.Play("shop_open");
        InvOwnerShop invOwnerShop = new InvOwnerShop(c, thing, currency, price);
        uIInventory.AddTab(invOwnerShop, UIInventory.Mode.Buy).dest = ELayer.pc;
        if (Window.dictData.TryGetValue("ChestMerchant") == null)
        {
            Window.dictData.Add("ChestMerchant", new Window.SaveData
            {
                useBG = true
            });
        }
        layerInventory.windows[0].saveData = thing.GetWindowSaveData();
        uIInventory.tabs[0].owner.BuildUICurrency(layerInventory.uiCurrency, c.trait.CostRerollShop != 0);
        ShopTransaction.current = new ShopTransaction
        {
            trader = invOwnerShop
        };
        layerInventory.SetOnKill(ShopTransaction.current.OnEndTransaction);
        return layerInventory;
    }
References _Create(), UIInventory.AddTab(), Trait.CostRerollShop, currency, ShopTransaction.current, UIInventory.Tab.dest, Window.dictData, ThingContainer.Find(), Card.GetWindowSaveData(), ShopTransaction.OnEndTransaction(), ELayer.pc, SetInv(), Layer.SetOnKill(), UIInventory.tabs, Card.things, Card.trait, uiCurrency, and Layer.windows.
Referenced by TraitVendingMachine.OnUse().
CreateContainer() [1/2]
static LayerInventory LayerInventory.CreateContainer (Card owner) inline static
Definition at line 541 of file LayerInventory.cs.
    {
        if (owner.GetRootCard() == ELayer.pc)
        {
            return CreateContainerPC(owner);
        }
        Card card = owner;
        if (owner.trait is TraitShippingChest)
        {
            card = ELayer.game.cards.container_shipping;
            card.things.SetSize(owner.things.width, owner.things.height);
            ELayer.player.uidLastShippedZone = ELayer._zone.uid;
        }
        if (owner.trait is TraitDeliveryChest)
        {
            card = ELayer.game.cards.container_deliver;
            Tutorial.Play("deliver_box");
        }
        return CreateContainer(owner, card);
    }
References ELayer._zone, card, Game.cards, CardManager.container_deliver, CardManager.container_shipping, CreateContainer(), CreateContainerPC(), ELayer.game, Card.GetRootCard(), ThingContainer.height, ELayer.pc, Tutorial.Play(), Card.things, Card.trait, Spatial.uid, and ThingContainer.width.
Referenced by ActPlan._Update(), CreateContainer(), ActionMode.DoFunc(), WidgetEquip.OnActivate(), TraitContainer.Open(), UI.OpenFloatInv(), and ButtonRoster.Refresh().
CreateContainer() [2/2]
static LayerInventory LayerInventory.CreateContainer (Card owner, Card container) inline static
Definition at line 562 of file LayerInventory.cs.
    {
        if (container.isChara)
        {
            SE.PopInventory();
        }
        LayerInventory layerInventory = _Create();
        layerInventory.SetInv().AddTab(owner, UIInventory.Mode.Take, container.Thing).dest = ELayer.pc;
        if (container.c_windowSaveData == null)
        {
            container.c_windowSaveData = new Window.SaveData
            {
                useBG = true
            };
            if (container == ELayer.game.cards.container_shipping)
            {
                container.c_windowSaveData.autodump = AutodumpFlag.none;
            }
        }
        layerInventory.windows[0].saveData = container.c_windowSaveData;
        ELayer.ui.AddLayer(layerInventory);
        if (container.id == "barrel")
        {
            if ((bool)WidgetFeed.Instance)
            {
                WidgetFeed.Instance.Nerun("barrel".langList().RandomItem());
            }
            ELayer.player.forceTalk = true;
            ELayer.pc.party.members.RandomItem().Talk("barrel");
        }
        return layerInventory;
    }
References _Create(), UIInventory.AddTab(), Card.c_windowSaveData, Game.cards, CardManager.container_shipping, UIInventory.Tab.dest, ELayer.game, Card.id, WidgetFeed.Instance, Card.isChara, Party.members, WidgetFeed.Nerun(), Chara.party, ELayer.pc, SetInv(), Card.Thing, ELayer.ui, and Layer.windows.
CreateContainer< T >()
static LayerInventory LayerInventory.CreateContainer< T > (Card c, Card container, CurrencyType currency = CurrencyType::None) inline static
Type Constraints
T : InvOwner
Definition at line 595 of file LayerInventory.cs.
                                                                                                                               : InvOwner
    {
        LayerInventory layerInventory = _Create();
        UIInventory uIInventory = layerInventory.SetInv();
        T owner = Activator.CreateInstance(typeof(T), c, container, currency) as T;
        uIInventory.AddTab(owner, UIInventory.Mode.Buy).dest = ELayer.pc;
        if (container.c_windowSaveData == null)
        {
            container.c_windowSaveData = new Window.SaveData
            {
                useBG = true
            };
        }
        layerInventory.windows[0].saveData = container.c_windowSaveData;
        ELayer.ui.AddLayer(layerInventory);
        return layerInventory;
    }
References _Create(), UIInventory.AddTab(), Card.c_windowSaveData, currency, UIInventory.Tab.dest, ELayer.pc, SetInv(), ELayer.ui, and Layer.windows.
CreateContainerAlly()
static LayerInventory LayerInventory.CreateContainerAlly (Chara owner, Card container) inline static
Definition at line 390 of file LayerInventory.cs.
    {
        SetDirty(container.Thing);
        CloseAllyInv();
        LayerInventory layerInventory = _Create("LayerInventoryFloat");
        UIInventory uIInventory = layerInventory.SetInv();
        Window window = layerInventory.windows[0];
        window.buttonClose.SetActive(enable: true);
        uIInventory.AddTab(new InvOwnerAlly(owner, container.Thing));
        uIInventory.tabs[0].textTab = container.Name;
        uIInventory.floatMode = true;
        if (ELayer.player.windowAllyInv == null)
        {
            Vector2 sizeDelta = window.Rect().sizeDelta;
            ELayer.player.windowAllyInv = new Window.SaveData
            {
                x = 0f,
                y = 200f,
                w = sizeDelta.x,
                h = sizeDelta.y,
                anchor = RectPosition.Center,
                useBG = ELayer.core.config.game.showInvBG,
                advDistribution = false
            };
        }
        window.saveData = ELayer.player.windowAllyInv;
        window.saveData.open = true;
        ELayer.ui.layerFloat.AddLayer(layerInventory);
        window.ClampToScreen();
        window.UpdateSaveData();
        return layerInventory;
    }
References _Create(), UIInventory.AddTab(), Window.buttonClose, Window.ClampToScreen(), CloseAllyInv(), Core.config, ELayer.core, CoreConfig.game, Card.Name, ELayer.player, SetDirty(), SetInv(), CoreConfig.GameConfig.showInvBG, UIInventory.tabs, Card.Thing, ELayer.ui, Window.UpdateSaveData(), Player.windowAllyInv, Layer.windows, and Window.SaveData.x.
Referenced by LayerDragGrid.SetInv().
CreateContainerPC()
static LayerInventory LayerInventory.CreateContainerPC (Card container) inline static
Definition at line 435 of file LayerInventory.cs.
    {
        SetDirty(container.Thing);
        foreach (LayerInventory item in listInv)
        {
            if (item.GetPlayerContainer() == container)
            {
                ELayer.ui.layerFloat.RemoveLayer(item);
                return null;
            }
        }
        LayerInventory layerInventory = _Create("LayerInventoryFloat");
        UIInventory uIInventory = layerInventory.SetInv();
        Window window = layerInventory.windows[0];
        Vector2 anchoredPosition = default(Vector2);
        bool flag = container.c_windowSaveData == null;
        window.buttonClose.SetActive(enable: true);
        uIInventory.AddTab(new InvOwner(ELayer.pc, container.Thing));
        uIInventory.tabs[0].textTab = container.Name;
        uIInventory.floatMode = true;
        if (container.c_windowSaveData == null)
        {
            anchoredPosition = window.Rect().anchoredPosition + new Vector2(-80f, -80f);
            Vector2 sizeDelta = window.Rect().sizeDelta;
            container.c_windowSaveData = new Window.SaveData
            {
                x = anchoredPosition.x,
                y = anchoredPosition.y,
                w = sizeDelta.x,
                h = sizeDelta.y,
                anchor = RectPosition.Auto,
                useBG = ELayer.core.config.game.showInvBG,
                advDistribution = false
            };
            if (container.trait.IsFridge)
            {
                container.c_windowSaveData.onlyRottable = true;
            }
        }
        if (container.IsToolbelt)
        {
            container.c_windowSaveData.useBG = false;
        }
        window.saveData = container.c_windowSaveData;
        window.saveData.open = true;
        if (container.IsToolbelt)
        {
            return layerInventory;
        }
        ELayer.ui.layerFloat.AddLayer(layerInventory);
        if (flag)
        {
            RectTransform rectTransform = window.Rect();
            if (ELayer.player.openContainerCenter)
            {
                rectTransform.anchorMin = new Vector2(0.5f, 0.5f);
                rectTransform.anchorMax = new Vector2(0.5f, 0.5f);
                anchoredPosition = new Vector2(0f, rectTransform.sizeDelta.y / 2f);
            }
            else
            {
                RectTransform rectTransform2 = null;
                RectTransform rectTransform3 = null;
                foreach (LayerInventory item2 in listInv)
                {
                    if (!(item2 == layerInventory) && item2.IsFloat)
                    {
                        RectTransform rectTransform4 = item2.windows[0].Rect();
                        if (!rectTransform3 || rectTransform4.Rect().localPosition.x < rectTransform3.Rect().localPosition.x)
{
                            rectTransform3 = rectTransform4;
                        }
                        if (!rectTransform2 || rectTransform4.Rect().localPosition.y > rectTransform2.Rect().localPosition.y)
{
                            rectTransform2 = rectTransform4;
                        }
                    }
                }
                if (uIInventory.tabs[0].owner.Container.things.width < 3 && (bool)rectTransform3)
                {
                    rectTransform.anchorMin = rectTransform3.anchorMin;
                    rectTransform.anchorMax = rectTransform3.anchorMax;
                    anchoredPosition.x = rectTransform3.anchoredPosition.x - rectTransform.sizeDelta.x - rectTransform3.sizeDelta.x * 0.5f + 35f;
                    anchoredPosition.y = rectTransform3.anchoredPosition.y;
                }
                else if ((bool)rectTransform2)
                {
                    rectTransform.anchorMin = rectTransform2.anchorMin;
                    rectTransform.anchorMax = rectTransform2.anchorMax;
                    anchoredPosition.x = rectTransform2.anchoredPosition.x;
                    anchoredPosition.y = rectTransform2.anchoredPosition.y + rectTransform.sizeDelta.y - 25f;
                }
                else
                {
                    rectTransform.anchorMin = new Vector2(0.5f, 0.5f);
                    rectTransform.anchorMax = new Vector2(0.5f, 0.5f);
                    anchoredPosition = Vector2.one;
                }
            }
            rectTransform.anchoredPosition = anchoredPosition;
            window.ClampToScreen();
            window.UpdateSaveData();
        }
        return layerInventory;
    }
References _Create(), UIInventory.AddTab(), Window.buttonClose, Window.ClampToScreen(), Core.config, ELayer.core, CoreConfig.game, ELayer.IsFloat, item, listInv, Player.openContainerCenter, ELayer.pc, ELayer.player, SetDirty(), SetInv(), CoreConfig.GameConfig.showInvBG, UIInventory.tabs, Card.Thing, ELayer.ui, Window.UpdateSaveData(), Layer.windows, and Window.SaveData.x.
Referenced by CreateContainer().
CreatePCBackpack()
static LayerInventory LayerInventory.CreatePCBackpack (bool mousePos = false) inline static
Definition at line 353 of file LayerInventory.cs.
    {
        LayerInventory layerInventory = _Create("LayerInventoryFloatMain");
        Window window = layerInventory.windows[0];
        layerInventory.mainInv = true;
        window.setting.saveWindow = true;
        UIInventory uIInventory = layerInventory.SetInv();
        uIInventory.AddTab(new InvOwner(ELayer.pc));
        uIInventory.SetHeader("stash");
        uIInventory.floatMode = true;
        return layerInventory;
    }
References _Create(), UIInventory.AddTab(), ELayer.pc, UIInventory.SetHeader(), SetInv(), and Layer.windows.
Referenced by UI.OpenFloatInv().
GetLayer()
static LayerInventory LayerInventory.GetLayer (Card t) inline static
Definition at line 45 of file LayerInventory.cs.
    {
        LayerInventory result = null;
        foreach (LayerInventory item in listInv)
        {
            if (item.Inv.Container == t)
            {
                return item;
            }
        }
        return result;
    }
References item, and listInv.
Referenced by GetPCLayer(), and ActionMode.UpdateInput().
GetPCLayer()
static LayerInventory LayerInventory.GetPCLayer () inline static
Definition at line 58 of file LayerInventory.cs.
    {
        return GetLayer(ELayer.pc);
    }
References GetLayer(), and ELayer.pc.
Referenced by InvOwner.GetShitDestOwner().
GetPlayerContainer()
Card LayerInventory.GetPlayerContainer () inline
Definition at line 223 of file LayerInventory.cs.
    {
        UIInventory.Tab tab = invs[0].tabs[0];
        if (!IsPlayerContainer())
        {
            return null;
        }
        return tab.owner.Container;
    }
References InvOwner.Container, invs, IsPlayerContainer(), and UIInventory.Tab.owner.
GetTopLayer()
static LayerInventory LayerInventory.GetTopLayer (Thing t, bool includePlayer = false, InvOwner exclude = null) inline static
Definition at line 26 of file LayerInventory.cs.
    {
        LayerInventory result = null;
        int num = -1;
        foreach (LayerInventory item in listInv)
        {
            if (item.IsPlayerContainer(includePlayer) && item.Inv != exclude && !item.Inv.Container.IsToolbelt && !item.Inv.Container.things.IsFull(t, recursive: false))
            {
                int siblingIndex = item.transform.GetSiblingIndex();
                if (siblingIndex > num)
                {
                    num = siblingIndex;
                    result = item;
                }
            }
        }
        return result;
    }
References item, and listInv.
Referenced by InvOwner.GetShitDestOwner().
HeaderIsListOf()
override bool LayerInventory.HeaderIsListOf (int id) inline virtual
Reimplemented from Layer.
Definition at line 233 of file LayerInventory.cs.
    {
        return false;
    }
IsOpen() [1/2]
static bool LayerInventory.IsOpen (Card container) inline static
Definition at line 423 of file LayerInventory.cs.
    {
        foreach (LayerInventory item in listInv)
        {
            if (item.GetPlayerContainer() == container)
            {
                return true;
            }
        }
        return false;
    }
References item, and listInv.
IsOpen() [2/2]
static bool LayerInventory.IsOpen (Thing t) inline static
Definition at line 75 of file LayerInventory.cs.
    {
        foreach (LayerInventory item in listInv)
        {
            if (item.invs[0].owner.Container == t)
            {
                return true;
            }
        }
        return false;
    }
References item, and listInv.
Referenced by InvOwner.ListInteractions(), and TraitContainer.OnSetCardGrid().
IsPlayerContainer()
bool LayerInventory.IsPlayerContainer (bool includePlayer = false) inline
Definition at line 210 of file LayerInventory.cs.
    {
        if (invs[0].tabs[0].mode != UIInventory.Mode.All)
        {
            return false;
        }
        if (!includePlayer && invs[0].owner.Container == ELayer.pc)
        {
            return false;
        }
        return invs[0].owner.Container.GetRootCard() == ELayer.pc;
    }
References invs, and ELayer.pc.
Referenced by GetPlayerContainer(), and UI.ToggleInventory().
OnAfterInit()
override void LayerInventory.OnAfterInit () inline virtual
Reimplemented from Layer.
Definition at line 260 of file LayerInventory.cs.
    {
        ELayer.core.actionsNextFrame.Add(delegate
        {
            ELayer.core.actionsNextFrame.Add(delegate
            {
                if ((bool)invs[0] && (bool)invs[0].gameObject)
                {
                    invs[0].RefreshHighlight();
                }
            });
        });
    }
References BaseCore.actionsNextFrame, ELayer.core, and invs.
OnDestroy()
void LayerInventory.OnDestroy () inline private
Definition at line 323 of file LayerInventory.cs.
    {
        if (invs.Count > 0)
        {
            SetDirty(invs[0].owner.Container.Thing);
        }
        listInv.Remove(this);
    }
References invs, listInv, and SetDirty().
OnInit()
override void LayerInventory.OnInit () inline virtual
Reimplemented from Layer.
Definition at line 238 of file LayerInventory.cs.
    {
        foreach (UIInventory inv in invs)
        {
            inv.OnInit();
        }
        listInv.Add(this);
        if (Inv.Container == ELayer.pc)
        {
            InvOwner.Main = Inv;
        }
        if (!floatInv)
        {
            InvOwner.Trader = Inv;
            wasInventoryOpen = ELayer.ui.IsInventoryOpen;
            if (!wasInventoryOpen)
            {
                ELayer.ui.OpenFloatInv(ignoreSound: true);
            }
        }
    }
References InvOwner.Container, floatInv, Inv, invs, listInv, UIInventory.OnInit(), ELayer.pc, ELayer.ui, and wasInventoryOpen.
OnKill()
override void LayerInventory.OnKill () inline virtual
Reimplemented from Layer.
Definition at line 297 of file LayerInventory.cs.
    {
        listInv.Remove(this);
        EInput.haltInput = false;
        if (Inv == InvOwner.Trader)
        {
            if (Inv.UseGuide)
            {
                SetDirtyAll();
            }
            InvOwner.Trader = null;
            if (!wasInventoryOpen && ELayer.ui.IsInventoryOpen)
            {
                ELayer.ui.ToggleInventory();
            }
        }
        if (Inv.Container == ELayer.pc)
        {
            InvOwner.Main = null;
        }
        if (!ELayer.game.isKilling && Inv.owner == ELayer.pc)
        {
            SE.Play("pop_inventory_deactivate");
        }
    }
References InvOwner.Container, ELayer.game, Inv, Game.isKilling, listInv, InvOwner.owner, ELayer.pc, SetDirtyAll(), InvOwner.Trader, ELayer.ui, InvOwner.UseGuide, and wasInventoryOpen.
OnRightClick()
override void LayerInventory.OnRightClick () inline virtual
Reimplemented from ELayer.
Definition at line 332 of file LayerInventory.cs.
    {
        if (invs[0].isList)
        {
            base.OnRightClick();
        }
        if (!invs[0].floatMode && InputModuleEX.GetComponentOf<ButtonGrid>() == null)
        {
            Close();
        }
    }
References Layer.Close(), and invs.
OnUpdateInput()
override void LayerInventory.OnUpdateInput () inline virtual
Reimplemented from Layer.
Definition at line 282 of file LayerInventory.cs.
    {
        if (EInput.action == EAction.MenuInventory || Input.GetKeyDown(KeyCode.Tab))
        {
            Close();
            EInput.WaitReleaseKey();
            return;
        }
        if (EInput.action == EAction.Dump)
        {
            TaskDump.TryPerform();
        }
        base.OnUpdateInput();
    }
References EInput.action, Layer.Close(), TaskDump.TryPerform(), and EInput.WaitReleaseKey().
SetDirty()
static void LayerInventory.SetDirty (Thing t) inline static
Definition at line 87 of file LayerInventory.cs.
    {
        if (!ELayer.game.altInv || t == null)
        {
            return;
        }
        foreach (LayerInventory item in listInv)
        {
            if (item.invs[0].owner.Container == t.parent || ((bool)item.mini && item.mini.gameObject.activeInHierarchy))
            {
                item.invs[0].dirty = true;
            }
        }
        if (t.invY == 1 || ELayer.pc.held == t)
        {
            WidgetCurrentTool.dirty = true;
        }
        if (t.isEquipped)
        {
            WidgetEquip.dirty = true;
        }
    }
References Game.altInv, ELayer.game, Chara.held, item, listInv, and ELayer.pc.
Referenced by Card.AddThing(), ActMelee.Attack(), Card.ChangeMaterial(), CreateContainerAlly(), CreateContainerPC(), Card.Decay(), Chara.DropHeld(), CharaBody.Equip(), InvOwner.Grab(), Chara.HoldCard(), Thing.Identify(), Card.ModCharge(), Card.OnChildNumChange(), OnDestroy(), InvOwnerDraglet.OnProcess(), ConSleep.OnRemoved(), TraitEquipItem.OnUse(), TraitFoodPreparedPackage.OnUse(), ActRanged.Perform(), Chara.PickHeld(), ActEffect.Proc(), UIInventory.RefreshMenu(), Card.RemoveThing(), Card.SetCharge(), Card.SetTier(), Chara.TryAbsorbRod(), ActRanged.TryReload(), ButtonAbility.TryUse(), and CharaBody.Unequip().
SetDirtyAll()
static void LayerInventory.SetDirtyAll (bool immediate = false) inline static
Definition at line 110 of file LayerInventory.cs.
    {
        foreach (LayerInventory item in listInv)
        {
            item.invs[0].dirty = true;
            if (immediate)
            {
                item.invs[0].CheckDirty();
            }
        }
        if ((bool)WidgetEquip.Instance)
        {
            WidgetEquip.dirty = true;
            if (immediate)
            {
                WidgetEquip.Instance.CheckDirty();
            }
        }
        WidgetCurrentTool.dirty = true;
        if (immediate)
        {
            WidgetCurrentTool.Instance.CheckDirty();
        }
    }
References WidgetCurrentTool.CheckDirty(), WidgetEquip.CheckDirty(), WidgetCurrentTool.Instance, WidgetEquip.Instance, item, and listInv.
Referenced by LayerAbility.ClearHotElement(), TraitBaseSpellbook.ModCharge(), WidgetSearch.OnDeactivate(), LayerDragGrid.OnKill(), OnKill(), CoreDebug.QuickStart(), LayerDragGrid.Redraw(), UIInventory.RefreshGrid(), WidgetSearch.RefreshList(), and LayerAbility.SelectGroup().
SetInv()
UIInventory LayerInventory.SetInv (int idWindow = 0) inline
Definition at line 274 of file LayerInventory.cs.
    {
        UIInventory uIInventory = invs[idWindow];
        uIInventory.window = windows[idWindow];
        uIInventory.layer = this;
        return uIInventory;
    }
References invs, and Layer.windows.
Referenced by CreateBuy(), CreateContainer(), CreateContainer< T >(), CreateContainerAlly(), CreateContainerPC(), and CreatePCBackpack().
TryShowGuide() [1/2]
static void LayerInventory.TryShowGuide (List< ButtonGrid > list) inline static
Definition at line 149 of file LayerInventory.cs.
    {
        bool flag = InvOwner.HasTrader && InvOwner.Trader.UseGuide;
        if (flag)
        {
            WidgetSearch.selected = null;
        }
        bool flag2 = (bool)WidgetSearch.Instance && WidgetSearch.selected != null && !ELayer.ui.IsDragging;
        if (!flag2 && WidgetEquip.dragEquip == null && LayerAbility.hotElement == null && !flag)
        {
            return;
        }
        foreach (ButtonGrid item in list)
        {
            Thing thing = item.card as Thing;
            if (LayerAbility.hotElement != null)
            {
                if ((bool)item && item.invOwner != null && (thing == null || thing.trait is TraitAbility) && item.invOwner.owner == ELayer.pc && !(item.invOwner is InvOwnerEquip))
                {
                    item.Attach("guide", rightAttach: false);
                }
            }
            else if (WidgetEquip.dragEquip != null && !flag)
            {
                if (item.invOwner is InvOwnerEquip invOwnerEquip && invOwnerEquip.slot.elementId == WidgetEquip.dragEquip.category.slot)
                {
                    item.Attach("guide", rightAttach: false);
                }
            }
            else if (flag2)
            {
                if (item.card == WidgetSearch.selected || item.card == WidgetSearch.selected.parent)
                {
                    item.Attach("guide", rightAttach: false);
                }
            }
            else
            {
                if (thing == null)
                {
                    continue;
                }
                bool show = InvOwner.Trader.ShouldShowGuide(thing);
                if (!show && thing.CanSearchContents)
                {
                    thing.things.Foreach(delegate(Thing _t)
                    {
                        if (!show && InvOwner.Trader.ShouldShowGuide(_t))
{
                            show = true;
                        }
                    });
                }
                if (show)
                {
                    item.Attach("guide", rightAttach: false);
                }
            }
        }
    }
References Thing.CanSearchContents, Card.category, WidgetEquip.dragEquip, BodySlot.elementId, ThingContainer.Foreach(), LayerAbility.hotElement, if(), WidgetSearch.Instance, item, Card.parent, ELayer.pc, WidgetSearch.selected, InvOwner.ShouldShowGuide(), InvOwnerEquip.slot, Card.things, InvOwner.Trader, ELayer.ui, and InvOwner.UseGuide.
TryShowGuide() [2/2]
static void LayerInventory.TryShowGuide (UIList list) inline static
Definition at line 135 of file LayerInventory.cs.
    {
        List<ButtonGrid> list2 = new List<ButtonGrid>();
        foreach (UIList.ButtonPair button in list.buttons)
        {
            ButtonGrid buttonGrid = button.component as ButtonGrid;
            if ((bool)buttonGrid)
            {
                list2.Add(buttonGrid);
            }
        }
        TryShowGuide(list2);
    }
References UIList.buttons, and TryShowGuide().
Referenced by WidgetCurrentTool.RebuildSlots(), WidgetEquip.RefreshEquipment(), UIInventory.RefreshGrid(), and TryShowGuide().
Member Data Documentation
floatInv
bool LayerInventory.floatInv
Definition at line 15 of file LayerInventory.cs.
Referenced by OnInit().
highlightInv
InvOwner LayerInventory.highlightInv static
Definition at line 9 of file LayerInventory.cs.
Referenced by UIInventory.Update().
invs
List<UIInventory> LayerInventory.invs = new List<UIInventory>()
Definition at line 11 of file LayerInventory.cs.
Referenced by GetPlayerContainer(), IsPlayerContainer(), OnAfterInit(), OnDestroy(), InvOwner.OnDrag(), OnInit(), OnRightClick(), UIInventory.RefreshMenu(), SetInv(), and ActionMode.UpdateInput().
listInv
List<LayerInventory> LayerInventory.listInv = new List<LayerInventory>() static
Definition at line 7 of file LayerInventory.cs.
Referenced by Core.Awake(), Close(), CloseAllyInv(), CreateContainerPC(), GetLayer(), GetTopLayer(), IsOpen(), OnDestroy(), OnInit(), OnKill(), Player.RefreshCurrentHotItem(), UIInventory.RefreshMenu(), Card.RemoveThing(), LayerAbility.SetDirty(), SetDirty(), SetDirtyAll(), and UI.ToggleInventory().
mainInv
bool LayerInventory.mainInv
Definition at line 17 of file LayerInventory.cs.
mini
WindowCharaMini LayerInventory.mini
Definition at line 19 of file LayerInventory.cs.
uiCurrency
UICurrency LayerInventory.uiCurrency
Definition at line 13 of file LayerInventory.cs.
Referenced by CreateBuy().
wasInventoryOpen
bool LayerInventory.wasInventoryOpen
Definition at line 22 of file LayerInventory.cs.
Referenced by OnInit(), and OnKill().
Property Documentation
Inv
InvOwner LayerInventory.Inv get
Definition at line 24 of file LayerInventory.cs.
Referenced by InvOwner.GetShitDestOwner(), OnInit(), OnKill(), and ButtonRoster.Refresh().
The documentation for this class was generated from the following file:
Elin/LayerInventory.cs