Elin Decompiled Documentation: HotItemActionMode Class Reference
HotItemActionMode Class Reference
Public Member Functions
override void OnClick (ButtonHotItem b, Hotbar h)
override bool ShouldHighlight ()
Public Member Functions inherited from HotItem
string TextHotkey ()
virtual void OnClick (ButtonHotItem b, Hotbar h)
virtual void OnRightClick (ButtonHotItem b)
virtual bool CanAutoFire (Chara tg)
virtual void OnSetCurrentItem ()
virtual void OnUnsetCurrentItem ()
virtual void OnUnselect ()
virtual void SetImage (Image icon)
virtual bool TrySetAct (ActPlan p)
virtual void OnMarkMapHighlights ()
virtual void OnRenderTile (Point point, HitResult result, int dir)
Static Public Member Functions
static void Execute (string id)
Public Attributes
string id
Public Attributes inherited from HotItem
ButtonHotItem button
Hotbar hotbar
bool disabled
Properties
override string Name [get]
override string pathSprite [get]
override bool KeepVisibleWhenHighlighted [get]
Properties inherited from HotItem
override Sprite SpriteHighlight [get]
override bool IsSelectable [get]
override string TextTip [get]
virtual Thing RenderThing [get]
virtual Thing Thing [get]
virtual Thing Tool [get]
virtual bool IsTool [get]
virtual bool LookAtMouse [get]
virtual bool IsGameAction [get]
virtual bool UseUIObjMaterial [get]
Detailed Description
Definition at line 4 of file HotItemActionMode.cs.
Member Function Documentation
Execute()
static void HotItemActionMode.Execute (string id) inline static
Definition at line 30 of file HotItemActionMode.cs.
    {
        uint num = <PrivateImplementationDetails>.ComputeStringHash(id);
        if (num <= 1491228771U)
        {
            if (num <= 996747083U)
            {
                if (num <= 547102523U)
                {
                    if (num != 482302120U)
                    {
                        if (num != 547102523U)
{
                            return;
                        }
                        if (!(id == "Deconstruct"))
{
                            return;
                        }
                        ActionMode.Deconstruct.Activate(false, false);
                        return;
                    }
                    else
                    {
                        if (!(id == "EditArea"))
{
                            return;
                        }
                        ActionMode.EditArea.Activate(false, false);
                        return;
                    }
                }
                else if (num != 561074963U)
                {
                    if (num != 996747083U)
                    {
                        return;
                    }
                    if (!(id == "Dig"))
                    {
                        return;
                    }
                    ActionMode.Dig.Activate(TaskDig.Mode.Default);
                    return;
                }
                else
                {
                    if (!(id == "Populate"))
                    {
                        return;
                    }
                    ActionMode.Populate.Activate(false, false);
                    return;
                }
            }
            else if (num <= 1143685331U)
            {
                if (num != 1027767735U)
                {
                    if (num != 1143685331U)
                    {
                        return;
                    }
                    if (!(id == "EditMarker"))
                    {
                        return;
                    }
                    ActionMode.EditMarker.Activate(false, false);
                    return;
                }
                else
                {
                    if (!(id == "Inspect"))
                    {
                        return;
                    }
                    if (!EClass.scene.actionMode.IsBuildMode)
                    {
                        BuildMenu.Toggle();
                        return;
                    }
                    ActionMode.Inspect.Activate(false, false);
                    return;
                }
            }
            else if (num != 1198054235U)
            {
                if (num != 1286637829U)
                {
                    if (num != 1491228771U)
                    {
                        return;
                    }
                    if (!(id == "Cut"))
                    {
                        return;
                    }
                    ActionMode.Cut.Activate(false, false);
                    return;
                }
                else
                {
                    if (!(id == "Visibility"))
                    {
                        return;
                    }
                    ActionMode.Visibility.Activate(false, false);
                    return;
                }
            }
            else
            {
                if (!(id == "FlagCell"))
                {
                    return;
                }
                ActionMode.FlagCell.Activate(false, false);
                return;
            }
        }
        else if (num <= 2316551543U)
        {
            if (num <= 2056661452U)
            {
                if (num != 1703884388U)
                {
                    if (num != 2056661452U)
                    {
                        return;
                    }
                    if (!(id == "RemoveDesignation"))
                    {
                        return;
                    }
                    ActionMode.RemoveDesignation.Activate(false, false);
                    return;
                }
                else
                {
                    if (!(id == "Copy"))
                    {
                        return;
                    }
                    ActionMode.Copy.Activate(false, false);
                    return;
                }
            }
            else if (num != 2207663855U)
            {
                if (num != 2316551543U)
                {
                    return;
                }
                if (!(id == "StateEditor"))
                {
                    return;
                }
                ActionMode.StateEditor.Activate(false, false);
                return;
            }
            else
            {
                if (!(id == "Picker"))
                {
                    return;
                }
                ActionMode.Picker.Activate(false, false);
                return;
            }
        }
        else if (num <= 2818509998U)
        {
            if (num != 2778370147U)
            {
                if (num != 2818509998U)
                {
                    return;
                }
                if (!(id == "Terrain"))
                {
                    return;
                }
                ActionMode.Terrain.Activate(false, false);
                return;
            }
            else
            {
                if (!(id == "ExitBuild"))
                {
                    return;
                }
                ActionMode.DefaultMode.Activate(false, false);
                return;
            }
        }
        else if (num != 3137301143U)
        {
            if (num != 3848897750U)
            {
                if (num != 3870556090U)
                {
                    return;
                }
                if (!(id == "Cinema"))
                {
                    return;
                }
                ActionMode.Cinema.Activate(false, false);
                return;
            }
            else
            {
                if (!(id == "Mine"))
                {
                    return;
                }
                ActionMode.Mine.Activate(false, false);
                return;
            }
        }
        else
        {
            if (!(id == "DigFloor"))
            {
                return;
            }
            ActionMode.Dig.Activate(TaskDig.Mode.RemoveFloor);
            return;
        }
    }
References Scene.actionMode, ActionMode.Activate(), AM_Dig.Activate(), AM_Mine.Activate(), AM_MoveInstalled.Activate(), ActionMode.Cinema, ActionMode.Copy, ActionMode.Cut, ActionMode.Deconstruct, ActionMode.DefaultMode, ActionMode.Dig, ActionMode.EditArea, ActionMode.EditMarker, ActionMode.FlagCell, ActionMode.Inspect, ActionMode.IsBuildMode, ActionMode.Mine, ActionMode.Picker, ActionMode.Populate, ActionMode.RemoveDesignation, EClass.scene, ActionMode.StateEditor, ActionMode.Terrain, BuildMenu.Toggle(), and ActionMode.Visibility.
Referenced by OnClick(), and LayerQuickMenu.OnInit().
OnClick()
override void HotItemActionMode.OnClick (ButtonHotItem b, Hotbar h) inline virtual
Reimplemented from HotItem.
Definition at line 261 of file HotItemActionMode.cs.
    {
        HotItemActionMode.Execute(this.id);
    }
References Execute().
ShouldHighlight()
override bool HotItemActionMode.ShouldHighlight () inline
Definition at line 266 of file HotItemActionMode.cs.
    {
        ActionMode actionMode = EClass.scene.actionMode;
        string text = this.id;
        uint num = <PrivateImplementationDetails>.ComputeStringHash(text);
        if (num <= 1286637829U)
        {
            if (num <= 996747083U)
            {
                if (num <= 547102523U)
                {
                    if (num != 482302120U)
                    {
                        if (num == 547102523U)
{
                            if (text == "Deconstruct")
{
                                return actionMode == ActionMode.Deconstruct;
                            }
                        }
                    }
                    else if (text == "EditArea")
                    {
                        return actionMode == ActionMode.EditArea || actionMode == ActionMode.CreateArea || actionMode == ActionMode.ExpandArea;
                    }
                }
                else if (num != 561074963U)
                {
                    if (num == 996747083U)
                    {
                        if (text == "Dig")
{
                            return actionMode == ActionMode.Dig && ActionMode.Dig.mode == TaskDig.Mode.Default;
                        }
                    }
                }
                else if (text == "Populate")
                {
                    return actionMode == ActionMode.Populate;
                }
            }
            else if (num <= 1143685331U)
            {
                if (num != 1027767735U)
                {
                    if (num == 1143685331U)
                    {
                        if (text == "EditMarker")
{
                            return actionMode == ActionMode.EditMarker;
                        }
                    }
                }
                else if (text == "Inspect")
                {
                    return actionMode == ActionMode.Inspect || actionMode == ActionMode.Build;
                }
            }
            else if (num != 1198054235U)
            {
                if (num == 1286637829U)
                {
                    if (text == "Visibility")
                    {
                        return actionMode == ActionMode.Visibility;
                    }
                }
            }
            else if (text == "FlagCell")
            {
                return actionMode == ActionMode.FlagCell;
            }
        }
        else if (num <= 2207663855U)
        {
            if (num <= 1703884388U)
            {
                if (num != 1491228771U)
                {
                    if (num == 1703884388U)
                    {
                        if (text == "Copy")
{
                            return actionMode == ActionMode.Copy;
                        }
                    }
                }
                else if (text == "Cut")
                {
                    return actionMode == ActionMode.Cut;
                }
            }
            else if (num != 2056661452U)
            {
                if (num == 2207663855U)
                {
                    if (text == "Picker")
                    {
                        return actionMode == ActionMode.Picker;
                    }
                }
            }
            else if (text == "RemoveDesignation")
            {
                return actionMode == ActionMode.RemoveDesignation;
            }
        }
        else if (num <= 2818509998U)
        {
            if (num != 2316551543U)
            {
                if (num == 2818509998U)
                {
                    if (text == "Terrain")
                    {
                        return actionMode == ActionMode.Terrain;
                    }
                }
            }
            else if (text == "StateEditor")
            {
                return actionMode == ActionMode.StateEditor;
            }
        }
        else if (num != 3137301143U)
        {
            if (num != 3848897750U)
            {
                if (num == 3870556090U)
                {
                    if (text == "Cinema")
                    {
                        return actionMode == ActionMode.Cinema;
                    }
                }
            }
            else if (text == "Mine")
            {
                return actionMode == ActionMode.Mine;
            }
        }
        else if (text == "DigFloor")
        {
            return actionMode == ActionMode.Dig && ActionMode.Dig.mode == TaskDig.Mode.RemoveFloor;
        }
        return false;
    }
References Scene.actionMode, ActionMode.Build, ActionMode.Cinema, ActionMode.Copy, ActionMode.Cut, ActionMode.Deconstruct, ActionMode.EditMarker, ActionMode.ExpandArea, ActionMode.FlagCell, id, ActionMode.Mine, ActionMode.Picker, ActionMode.Populate, ActionMode.RemoveDesignation, EClass.scene, ActionMode.StateEditor, ActionMode.Terrain, text, and ActionMode.Visibility.
Member Data Documentation
id
string HotItemActionMode.id
Definition at line 415 of file HotItemActionMode.cs.
Referenced by ShouldHighlight().
Property Documentation
KeepVisibleWhenHighlighted
override bool HotItemActionMode.KeepVisibleWhenHighlighted get
Definition at line 22 of file HotItemActionMode.cs.
    {
        get
        {
            return true;
        }
    }
Name
override string HotItemActionMode.Name get
Definition at line 6 of file HotItemActionMode.cs.
    {
        get
        {
            return this.id.lang();
        }
    }
pathSprite
override string HotItemActionMode.pathSprite get
Definition at line 14 of file HotItemActionMode.cs.
    {
        get
        {
            return "icon_" + this.id;
        }
    }
The documentation for this class was generated from the following file:
Elin/HotItemActionMode.cs