Elin Decompiled Documentation: LayerEditHouse Class Reference
LayerEditHouse Class Reference
Public Member Functions
override void OnInit ()
void SetBoard (TraitHouseBoard b)
void RefreshTemplates ()
void ApplyData ()
override void OnKill ()
Public Member Functions inherited from ELayer
override void OnBeforeAddLayer ()
void InitInspector ()
sealed override void Init ()
override void OnAfterAddLayer ()
void TryShowHelp ()
void AddLayerToUI (string id)
void TryShowHint (string _langHint=null)
void TalkHomeMemeber (string id)
void TalkMaid (string id)
override void OnRightClick ()
Public Member Functions inherited from Layer
virtual string GetTextHeader (Window window)
virtual bool HeaderIsListOf (int id)
virtual void Init ()
virtual void OnInit ()
virtual void OnAfterInit ()
virtual void ApplySkin ()
void ShowScreenLock (string id)
void UpdateInput ()
virtual void OnUpdateInput ()
virtual void OnRightClick ()
virtual bool OnBack ()
virtual void OnChangeLayer ()
virtual void OnCreate ()
void _AddLayer (string id)
Layer AddLayer (string id)
T AddLayer< T > ()
T AddLayer< T > (string id)
T AddLayerDontCloseOthers< T > ()
Layer AddLayerDontCloseOthers (Layer l)
T GetOrAddLayer< T > ()
virtual void OnBeforeAddLayer ()
virtual void OnAfterAddLayer ()
Layer AddLayer (Layer l)
void ToggleLayer (string id)
T ToggleLayer< T > (string id=null)
void WaitAndClose ()
void OnClickClose ()
virtual void Close ()
void CloseLayers ()
void RemoveLayers (bool removeImportant=false)
bool RemoveLayer< T > ()
void RemoveLayer (Layer l)
virtual void OnKill ()
Layer SetOnKill (Action action)
void DisableClose ()
void Delay (float duration=0.05f)
Layer SetDelay (float d)
Layer GetLayer (string id)
T GetLayer< T > (bool fromTop=false)
Layer GetTopLayer ()
void SwitchContent (int idWindow, int i)
virtual void OnSwitchContent (Window window)
Layer SetTitles (string langList, string idHeaderRow=null)
bool IsBlockWidgetClick ()
bool IsHideHud ()
bool IsAllowGeneralInput ()
bool IsUseBlur ()
bool IsPointerOnLayer ()
void ApplySkin ()
Public Attributes
TraitHouseBoard board
UISlider sliderBlock
UISlider sliderRoof
UISlider sliderRamp
UISlider sliderWallHeight
UISlider sliderHeightFix
UISlider sliderDeco
UISlider sliderDeco2
UISlider sliderDecoFix
UISlider sliderDecoFix2
UIDropdown ddRoofStyle
UIDropdown ddTemplate
UIButton toggleReverse
UIButton toggleAltRoof
UIButton buttonColorRoof
UIButton buttonColorBlock
UIButton buttonColorDeco
UIButton buttonColorDeco2
UIButton toggleAtrium
int maxWallDeco
Public Attributes inherited from Layer
Option option
UnityEvent onKill
Anime animeIn
Anime animeOut
bool closeOthers
bool defaultActionMode = true
Button screenLock
Layer parent
string idLayer
List< Layer > layers = new List<Layer>()
Vector2 lastParentPos
List< Window > windows = new List<Window>()
string langHint
Properties
TraitHouseBoard.Data data [get]
Properties inherited from ELayer
static Core core [get]
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static FactionBranch Branch [get]
static Faction Home [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static CoreConfig config [get]
static GameSetting setting [get]
static ColorProfile Colors [get]
static SourceManager sources [get]
static World world [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
bool IsFloat [get]
virtual string IdHelp [get]
Properties inherited from Layer
Layer TopLayer [get]
string uid [get]
virtual RectTransform rectLayers [get]
virtual bool blockWidgetClick [get]
Private Member Functions
void RefreshBlockList ()
Private Attributes
bool first = true
Additional Inherited Members
Static Public Member Functions inherited from ELayer
static int rnd (int a)
Static Public Member Functions inherited from Layer
static T Create< T > ()
static T Create< T > (string path)
static Layer Create (string path)
Static Public Attributes inherited from Layer
static int skipInput
static bool closeOnRightClick
static bool rightClicked
static bool cancelKeyDown
static bool ignoreSounds
static Transform blurStopInstance
static string[] searchPath = new string[3] { "Layer", "Layer/Dialog", "Layer/LayerHome" }
Protected Member Functions inherited from ELayer
sealed override void _Close ()
sealed override void Kill ()
Protected Member Functions inherited from Layer
virtual void Awake ()
virtual void _Close ()
virtual void Kill ()
Protected Attributes inherited from Layer
RectTransform _rect
bool isDestroyed
Detailed Description
Definition at line 7 of file LayerEditHouse.cs.
Member Function Documentation
ApplyData()
void LayerEditHouse.ApplyData () inline
Definition at line 263 of file LayerEditHouse.cs.
    {
        board.ApplyData();
        toggleAltRoof.SetActive(board.data.idRoofTile != 0);
    }
References TraitHouseBoard.ApplyData(), board, TraitHouseBoard.data, TraitHouseBoard.Data.idRoofTile, and toggleAltRoof.
Referenced by RefreshBlockList(), RefreshTemplates(), and SetBoard().
OnInit()
override void LayerEditHouse.OnInit () inline virtual
Reimplemented from Layer.
Definition at line 53 of file LayerEditHouse.cs.
    {
        windows[0].AddBottomButton("save", delegate
        {
            ELayer.core.WaitForEndOfFrame(delegate
            {
                string text = StandaloneFileBrowser.SaveFilePanel("Save Template", CorePath.LotTemplate, "new house", "tpl");
                if (!string.IsNullOrEmpty(text))
                {
                    IO.SaveFile(text, board.data);
                    RefreshTemplates();
                }
            });
        });
    }
References board, ELayer.core, TraitHouseBoard.data, if(), CorePath.LotTemplate, RefreshTemplates(), SFB.StandaloneFileBrowser.SaveFilePanel(), BaseCore.WaitForEndOfFrame(), and Layer.windows.
OnKill()
override void LayerEditHouse.OnKill () inline virtual
Reimplemented from Layer.
Definition at line 269 of file LayerEditHouse.cs.
    {
        ELayer.screen.tileMap.usingHouseBoard = false;
        if ((bool)BuildMenu.Instance)
        {
            BuildMenu.Instance.SetActive(enable: true);
        }
    }
References BuildMenu.Instance.
RefreshBlockList()
void LayerEditHouse.RefreshBlockList () inline private
Definition at line 175 of file LayerEditHouse.cs.
    {
        bool num = ELayer.screen.tileMap.roofStyles[data.idRoofStyle].type != RoofStyle.Type.FlatFloor;
        List<int> blocks = new List<int>();
        if (num)
        {
            foreach (SourceBlock.Row row in ELayer.sources.blocks.rows)
            {
                if (row.tileType == TileType.Block)
                {
                    blocks.Add(row.id);
                }
            }
        }
        else
        {
            foreach (SourceFloor.Row row2 in ELayer.sources.floors.rows)
            {
                blocks.Add(row2.id);
            }
        }
        int num2 = blocks.IndexOf(data.idBlock);
        if (num2 == -1)
        {
            num2 = 0;
        }
        sliderBlock.SetList(num2, blocks, delegate(int a, int b)
        {
            data.idBlock = b;
            ApplyData();
        }, (int a) => blocks.IndexOf(a).ToString() ?? "");
        buttonColorRoof.icon.color = IntColor.FromInt(data.colRoof);
        buttonColorRoof.SetOnClick(delegate
        {
            ELayer.ui.AddLayer<LayerColorPicker>().SetColor(IntColor.FromInt(data.colRoof), IntColor.FromInt(data.colRoof), delegate(PickerState state, Color c)
            {
                data.colRoof = IntColor.ToInt(c);
                buttonColorRoof.icon.color = c;
                board.ApplyData();
            });
        });
        buttonColorBlock.icon.color = IntColor.FromInt(data.colBlock);
        buttonColorBlock.SetOnClick(delegate
        {
            ELayer.ui.AddLayer<LayerColorPicker>().SetColor(IntColor.FromInt(data.colBlock), IntColor.FromInt(data.colBlock), delegate(PickerState state, Color c)
            {
                data.colBlock = IntColor.ToInt(c);
                buttonColorBlock.icon.color = c;
                board.ApplyData();
            });
        });
        buttonColorDeco.icon.color = IntColor.FromInt(data.colDeco);
        buttonColorDeco.SetOnClick(delegate
        {
            ELayer.ui.AddLayer<LayerColorPicker>().SetColor(IntColor.FromInt(data.colDeco), IntColor.FromInt(data.colDeco), delegate(PickerState state, Color c)
            {
                data.colDeco = IntColor.ToInt(c);
                buttonColorDeco.icon.color = c;
                board.ApplyData();
            });
        });
        buttonColorDeco2.icon.color = IntColor.FromInt(data.colDeco2);
        buttonColorDeco2.SetOnClick(delegate
        {
            ELayer.ui.AddLayer<LayerColorPicker>().SetColor(IntColor.FromInt(data.colDeco2), IntColor.FromInt(data.colDeco2), delegate(PickerState state, Color c)
            {
                data.colDeco2 = IntColor.ToInt(c);
                buttonColorDeco2.icon.color = c;
                board.ApplyData();
            });
        });
    }
References ApplyData(), TraitHouseBoard.ApplyData(), TileType.Block, SourceManager.blocks, board, buttonColorBlock, buttonColorDeco, buttonColorDeco2, buttonColorRoof, Color, data, SourceManager.floors, IntColor.FromInt(), BaseTileMap.roofStyles, ELayer.screen, sliderBlock, ELayer.sources, BaseGameScreen.tileMap, IntColor.ToInt(), RoofStyle.type, and ELayer.ui.
Referenced by SetBoard().
RefreshTemplates()
void LayerEditHouse.RefreshTemplates () inline
Definition at line 248 of file LayerEditHouse.cs.
    {
        FileInfo[] list = (from a in new DirectoryInfo(CorePath.LotTemplate).GetFiles()
            where a.Name.EndsWith(".tpl")
            select a).ToArray();
        ddTemplate.SetList(0, list, (FileInfo a, int b) => a.Name, delegate(int a, FileInfo b)
        {
            int idBGM = board.data.idBGM;
            board.data = IO.LoadFile<TraitHouseBoard.Data>(b.FullName);
            board.data.idBGM = idBGM;
            ApplyData();
            SetBoard(board);
        });
    }
References ApplyData(), board, TraitHouseBoard.data, ddTemplate, TraitHouseBoard.Data.idBGM, CorePath.LotTemplate, and SetBoard().
Referenced by OnInit(), and SetBoard().
SetBoard()
void LayerEditHouse.SetBoard (TraitHouseBoard b) inline
Definition at line 69 of file LayerEditHouse.cs.
    {
        if ((bool)BuildMenu.Instance)
        {
            BuildMenu.Instance.SetActive(enable: false);
        }
        ELayer.screen.tileMap.usingHouseBoard = true;
        board = b;
        ddRoofStyle.SetList(data.idRoofStyle, ELayer.screen.tileMap.roofStyles, (RoofStyle a, int b) => a.GetName(b).lang(), delegate(int a, RoofStyle b)
        {
            data.idRoofStyle = a;
            ApplyData();
            RefreshBlockList();
        });
        toggleReverse.SetToggle(data.reverse, delegate(bool on)
        {
            data.reverse = on;
            ApplyData();
        });
        toggleAltRoof.SetToggle(data.altRoof, delegate(bool on)
        {
            data.altRoof = on;
            ApplyData();
        });
        List<int> blocks = new List<int>();
        int num = 0;
        blocks.Add(0);
        foreach (SourceObj.Row row in ELayer.sources.objs.rows)
        {
            if (row.tileType == TileType.Roof && !row.tag.Contains("hidden"))
            {
                blocks.Add(row.id);
            }
        }
        num = blocks.IndexOf(data.idRoofTile);
        if (num == -1)
        {
            num = 0;
        }
        sliderRoof.SetList(num, blocks, delegate(int a, int b)
        {
            data.idRoofTile = b;
            ApplyData();
        }, (int a) => blocks.IndexOf(a).ToString() ?? "");
        List<int> ramps = new List<int>();
        foreach (SourceBlock.Row row2 in ELayer.sources.blocks.rows)
        {
            if (row2.tileType == TileType.Stairs || row2.tileType == TileType.Slope)
            {
                ramps.Add(row2.id);
            }
        }
        int num2 = ramps.IndexOf(data.idRamp);
        if (num2 == -1)
        {
            num2 = 0;
        }
        sliderRamp.SetList(num2, ramps, delegate(int a, int b)
        {
            data.idRamp = b;
            ApplyData();
        }, (int a) => ramps.IndexOf(a).ToString() ?? "");
        sliderWallHeight.SetSlider(data.height, delegate(float a)
        {
            data.height = (int)a;
            ApplyData();
            return a.ToString() ?? "";
        }, 1, 20);
        sliderHeightFix.SetSlider(data.heightFix, delegate(float a)
        {
            data.heightFix = (int)a;
            ApplyData();
            return a.ToString() ?? "";
        }, 0, 60);
        sliderDecoFix.SetSlider(data.decoFix, delegate(float a)
        {
            data.decoFix = (int)a;
            ApplyData();
            return a.ToString() ?? "";
        }, -20, 20);
        sliderDecoFix2.SetSlider(data.decoFix2, delegate(float a)
        {
            data.decoFix2 = (int)a;
            ApplyData();
            return a.ToString() ?? "";
        }, -20, 400);
        sliderDeco.SetSlider(data.idDeco, delegate(float a)
        {
            data.idDeco = (int)a;
            ApplyData();
            return a.ToString() ?? "";
        }, 0, maxWallDeco);
        sliderDeco2.SetSlider(data.idDeco2, delegate(float a)
        {
            data.idDeco2 = (int)a;
            ApplyData();
            return a.ToString() ?? "";
        }, 0, maxWallDeco);
        if (first)
        {
            RefreshTemplates();
        }
        RefreshBlockList();
        first = false;
    }
References ApplyData(), SourceManager.blocks, board, data, ddRoofStyle, first, RoofStyle.GetName(), BuildMenu.Instance, maxWallDeco, SourceManager.objs, RefreshBlockList(), RefreshTemplates(), TileType.Roof, BaseTileMap.roofStyles, ELayer.screen, UIButton.SetToggle(), sliderDeco, sliderDeco2, sliderDecoFix, sliderDecoFix2, sliderHeightFix, sliderRamp, sliderRoof, sliderWallHeight, TileType.Slope, ELayer.sources, TileType.Stairs, BaseGameScreen.tileMap, toggleAltRoof, and toggleReverse.
Referenced by RefreshTemplates().
Member Data Documentation
board
TraitHouseBoard LayerEditHouse.board
Definition at line 9 of file LayerEditHouse.cs.
Referenced by ApplyData(), OnInit(), RefreshBlockList(), RefreshTemplates(), and SetBoard().
buttonColorBlock
UIButton LayerEditHouse.buttonColorBlock
Definition at line 39 of file LayerEditHouse.cs.
Referenced by RefreshBlockList().
buttonColorDeco
UIButton LayerEditHouse.buttonColorDeco
Definition at line 41 of file LayerEditHouse.cs.
Referenced by RefreshBlockList().
buttonColorDeco2
UIButton LayerEditHouse.buttonColorDeco2
Definition at line 43 of file LayerEditHouse.cs.
Referenced by RefreshBlockList().
buttonColorRoof
UIButton LayerEditHouse.buttonColorRoof
Definition at line 37 of file LayerEditHouse.cs.
Referenced by RefreshBlockList().
ddRoofStyle
UIDropdown LayerEditHouse.ddRoofStyle
Definition at line 29 of file LayerEditHouse.cs.
Referenced by SetBoard().
ddTemplate
UIDropdown LayerEditHouse.ddTemplate
Definition at line 31 of file LayerEditHouse.cs.
Referenced by RefreshTemplates().
first
bool LayerEditHouse.first = true private
Definition at line 49 of file LayerEditHouse.cs.
Referenced by SetBoard().
maxWallDeco
int LayerEditHouse.maxWallDeco
Definition at line 47 of file LayerEditHouse.cs.
Referenced by SetBoard().
sliderBlock
UISlider LayerEditHouse.sliderBlock
Definition at line 11 of file LayerEditHouse.cs.
Referenced by RefreshBlockList().
sliderDeco
UISlider LayerEditHouse.sliderDeco
Definition at line 21 of file LayerEditHouse.cs.
Referenced by SetBoard().
sliderDeco2
UISlider LayerEditHouse.sliderDeco2
Definition at line 23 of file LayerEditHouse.cs.
Referenced by SetBoard().
sliderDecoFix
UISlider LayerEditHouse.sliderDecoFix
Definition at line 25 of file LayerEditHouse.cs.
Referenced by SetBoard().
sliderDecoFix2
UISlider LayerEditHouse.sliderDecoFix2
Definition at line 27 of file LayerEditHouse.cs.
Referenced by SetBoard().
sliderHeightFix
UISlider LayerEditHouse.sliderHeightFix
Definition at line 19 of file LayerEditHouse.cs.
Referenced by SetBoard().
sliderRamp
UISlider LayerEditHouse.sliderRamp
Definition at line 15 of file LayerEditHouse.cs.
Referenced by SetBoard().
sliderRoof
UISlider LayerEditHouse.sliderRoof
Definition at line 13 of file LayerEditHouse.cs.
Referenced by SetBoard().
sliderWallHeight
UISlider LayerEditHouse.sliderWallHeight
Definition at line 17 of file LayerEditHouse.cs.
Referenced by SetBoard().
toggleAltRoof
UIButton LayerEditHouse.toggleAltRoof
Definition at line 35 of file LayerEditHouse.cs.
Referenced by ApplyData(), and SetBoard().
toggleAtrium
UIButton LayerEditHouse.toggleAtrium
Definition at line 45 of file LayerEditHouse.cs.
toggleReverse
UIButton LayerEditHouse.toggleReverse
Definition at line 33 of file LayerEditHouse.cs.
Referenced by SetBoard().
Property Documentation
data
TraitHouseBoard.Data LayerEditHouse.data get
Definition at line 51 of file LayerEditHouse.cs.
Referenced by RefreshBlockList(), and SetBoard().
The documentation for this class was generated from the following file:
Elin/LayerEditHouse.cs