Elin Decompiled Documentation: AI_Eat Class Reference
AI_Eat Class Reference
Public Member Functions
bool IsValidTarget (Card c)
override bool CanManualCancel ()
override void OnStart ()
override IEnumerable< Status > Run ()
Public Member Functions inherited from AIAct
override string ToString ()
override MultiSprite GetStateIcon ()
virtual bool ShouldAllyAttack (Chara tg)
virtual Point GetDestination ()
AIProgress GetProgress ()
string GetCurrentActionText ()
override bool IsToolValid ()
virtual void OnStart ()
void SetOwner (Chara c)
virtual void OnSetOwner ()
void SetChild (AIAct seq, Func< Status > _onChildFail=null)
void Start ()
override bool Perform ()
Status Restart ()
Status Success (Action action=null)
virtual void OnSuccess ()
bool TryCancel (Card c)
virtual Status Cancel ()
virtual void OnCancel ()
virtual void OnCancelOrSuccess ()
virtual bool CanManualCancel ()
Status KeepRunning ()
void Reset ()
virtual void OnReset ()
Status Tick ()
virtual IEnumerable< Status > Run ()
Status TickChild ()
Status Do (AIAct _seq, Func< Status > _onChildFail=null)
Status DoGotoInteraction (Point pos, Func< Status > _onChildFail=null)
Status DoGoto (Point pos, int dist=0, bool ignoreConnection=false, Func< Status > _onChildFail=null)
Status DoGoto (Card card, Func< Status > _onChildFail=null)
Status DoGoto (Card card, int dist, Func< Status > _onChildFail=null)
Status DoGotoSpot (Card card, Func< Status > _onChildFail=null)
Status DoGoto< T > (Func< Status > _onChildFail=null)
Status DoGotoSpot< T > (Func< Status > _onChildFail=null, bool ignoreAccessType=false)
Status DoGrab (Card card, int num=-1, bool pickHeld=false, Func< Status > _onChildFail=null)
Status DoGrab< T > ()
Status DoProgress ()
Status DoIdle (int repeat=3)
Status DoWait (int count=1)
virtual AIProgress CreateProgress ()
virtual void OnCreateProgress (Progress_Custom p)
virtual bool CanProgress ()
virtual void OnBeforeProgress ()
virtual void OnProgress ()
virtual void OnProgressComplete ()
void SimulateZone (int days)
virtual void OnSimulateZone (int days)
virtual void OnSimulatePosition ()
Public Member Functions inherited from Act
virtual CursorInfo GetCursorIcon (Card c)
virtual MultiSprite GetStateIcon ()
override Sprite GetSprite ()
virtual bool ShowMouseHint (Card c)
virtual bool IsValidTC (Card c)
virtual string GetHintText (string str="")
virtual string GetText (string str="")
virtual string GetTextSmall (Card c)
virtual Color GetActPlanColor ()
virtual bool Perform ()
virtual bool CanPerform ()
bool Perform (Chara _cc, Card _tc=null, Point _tp=null)
bool CanPerform (Chara _cc, Card _tc=null, Point _tp=null)
virtual bool IsToolValid ()
new void SetImage (Image image)
virtual void OnMarkMapHighlights ()
virtual bool ShouldMapHighlight (Point p)
Public Member Functions inherited from Element
virtual SourceElement.Row GetSource ()
virtual int GetSourcePotential (int v)
virtual Sprite GetSprite ()
int GetMaterialSourceValue (Thing t, int v)
virtual int GetSourceValue (int v, int lv, SourceValueType type)
virtual Sprite GetIcon (string suffix="")
int SortVal (bool charaSheet=false)
virtual bool CanLink (ElementContainer owner)
bool HasTag (string tag)
void SetImage (Image i)
virtual string GetDetail ()
bool IsFactionElement (Chara c)
Element GetParent (Card c)
void WriteNote (UINote n, ElementContainer owner=null, Action< UINote > onWriteNote=null)
void WriteNoteWithRef (UINote n, ElementContainer owner, Action< UINote > onWriteNote, Element refEle)
void _WriteNote (UINote n, Chara c, Act act)
void AddHeaderAbility (UINote n)
void _WriteNote (UINote n, ElementContainer owner, Action< UINote > onWriteNote, bool isRef, bool addHeader=true)
virtual void OnWriteNote (UINote n, ElementContainer owner)
virtual void OnChangeValue ()
void CheckLevelBonus (ElementContainer owner, UINote n=null)
int GetSortVal (UIList.SortMode m)
virtual Act.Cost GetCost (Chara c)
virtual int GetPower (Card c)
virtual void SetTextValue (UIText text)
virtual bool IsPurchaseFeatReqMet (ElementContainer owner, int lv=-1)
virtual void WritePurchaseReq (UINote n, int lv=1)
Public Attributes
Card target
bool cook = true
Public Attributes inherited from AIAct
new Chara owner
Status status
IEnumerator< Status > Enumerator
AIAct child
AIAct parent
byte restartCount
Func< Status > onChildFail
Func< bool > isFail
Public Attributes inherited from Element
SourceElement.Row _source
int id
int vBase
int vExp
int vPotential
int vTempPotential
int vLink
int vSource
int vSourcePotential
ElementContainer owner
Properties
override bool LocalAct [get]
override bool IsHostileAct [get]
Properties inherited from AIAct
virtual bool IsRunning [get]
bool IsChildRunning [get]
bool IsMoveAI [get]
virtual int MaxRestart [get]
virtual new string Name [get]
virtual MultiSprite stateIcon [get]
virtual Sprite actionIcon [get]
virtual bool IsNoGoal [get]
virtual bool IsAutoTurn [get]
virtual bool IsIdle [get]
virtual bool CancelOnAggro [get]
virtual bool PushChara [get]
virtual int MaxProgress [get]
virtual bool ShowProgress [get]
virtual bool UseTurbo [get]
virtual int CurrentProgress [get]
virtual bool ShowCursor [get]
virtual bool CancelWhenDamaged [get]
virtual bool CancelWhenMoved [get]
virtual bool InformCancel [get]
virtual Thing RenderThing [get]
AIAct Current [get]
override bool IsAct [get]
override bool ShowPotential [get]
override bool UsePotential [get]
override bool ShowRelativeAttribute [get]
virtual bool HasProgress [get]
Properties inherited from Act
override bool ShowPotential [get]
override bool UsePotential [get]
override bool ShowRelativeAttribute [get]
virtual CursorInfo CursorIcon [get]
virtual string ID [get]
virtual bool IsAct [get]
virtual bool WillEndTurn [get]
virtual bool CloseLayers [get]
virtual int LeftHand [get]
virtual int RightHand [get]
virtual int ElementPowerMod [get]
virtual bool ShowMapHighlight [get]
virtual bool ShowMapHighlightBlock [get]
virtual bool PickHeldOnStart [get]
virtual bool DropHeldOnStart [get]
virtual bool CanPressRepeat [get]
virtual bool CanAutofire [get]
virtual bool ResetAxis [get]
virtual bool RequireTool [get]
virtual bool IsHostileAct [get]
virtual bool HideRightInfo [get]
virtual bool HaveLongPressAction [get]
virtual float Radius [get]
virtual int PerformDistance [get]
virtual int MaxRadius [get]
virtual TargetType TargetType [get]
virtual bool LocalAct [get]
virtual bool CanRapidFire [get]
virtual float RapidDelay [get]
virtual bool ShowAuto [get]
virtual bool IsCrime [get]
Properties inherited from Element
SourceElement.Row source [get]
virtual int DisplayValue [get]
virtual int MinValue [get]
int Value [get]
int ValueWithoutLink [get]
virtual int MinPotential [get]
int Potential [get]
virtual bool CanGainExp [get]
bool IsFlag [get]
virtual string Name [get]
virtual string FullName [get]
virtual int ExpToNext [get]
virtual bool UseExpMod [get]
virtual int CostTrain [get]
virtual int CostLearn [get]
virtual bool ShowXP [get]
virtual bool ShowMsgOnValueChanged [get]
virtual bool ShowValue [get]
virtual bool ShowPotential [get]
virtual bool UsePotential [get]
virtual bool PotentialAsStock [get]
virtual bool ShowRelativeAttribute [get]
virtual bool ShowBonuses [get]
virtual string ShortName [get]
bool IsGlobalElement [get]
bool IsFactionWideElement [get]
bool IsPartyWideElement [get]
virtual bool ShowEncNumber [get]
bool IsTrait [get]
bool IsFoodTrait [get]
bool IsFoodTraitMain [get]
bool IsMainAttribute [get]
Act act [get]
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Additional Inherited Members
Public Types inherited from AIAct
enum Status { Running , Fail , Success }
Public Types inherited from Act
enum CostType { None , MP , SP }
Static Public Member Functions inherited from Act
static void SetReference (Chara _cc, Card _tc=null, Point _tp=null)
static void SetTool (Thing t)
Static Public Member Functions inherited from Element
static string GetName (string alias)
static SourceElement.Row Get (int id)
static Dictionary< int, int > GetElementMap (int[] list)
static Dictionary< int, int > GetElementMap (int[] list, Dictionary< int, int > map)
static SourceElement.Row GetRandomElement (int lv=1)
static Element Create (int id, int v=0)
static Element Create (string id, int v=1)
static int GetId (string alias)
static int GetResistLv (int v)
static int GetResistDamage (int dmg, int v, int power=0)
Static Public Member Functions inherited from EClass
static int rnd (int a)
static int curve (int a, int start, int step, int rate=75)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Static Public Attributes inherited from Act
static Chara CC
static Card TC
static Point TP = new Point()
static Thing TOOL
static int powerMod = 100
static bool forcePt
Static Public Attributes inherited from Element
const int Div = 5
static Element Void = new Element()
static int[] List_MainAttributes = new int[9] { 70, 72, 71, 77, 74, 75, 76, 73, 79 }
static int[] List_MainAttributesMajor = new int[8] { 70, 72, 71, 77, 74, 75, 76, 73 }
static int[] List_Body = new int[4] { 70, 72, 71, 77 }
static int[] List_Mind = new int[4] { 74, 75, 76, 73 }
static List< SourceElement.Row > ListElements = new List<SourceElement.Row>()
static List< SourceElement.Row > ListAttackElements = new List<SourceElement.Row>()
Static Public Attributes inherited from EClass
static Core core
Detailed Description
Definition at line 4 of file AI_Eat.cs.
Member Function Documentation
CanManualCancel()
override bool AI_Eat.CanManualCancel () inline virtual
Reimplemented from AIAct.
Definition at line 29 of file AI_Eat.cs.
    {
        return true;
    }
IsValidTarget()
bool AI_Eat.IsValidTarget (Card c) inline
Definition at line 24 of file AI_Eat.cs.
    {
        return c?.trait.CanEat(owner) ?? false;
    }
References Trait.CanEat(), AIAct.owner, and Card.trait.
Referenced by Run().
OnStart()
override void AI_Eat.OnStart () inline virtual
Reimplemented from AIAct.
Definition at line 34 of file AI_Eat.cs.
    {
    }
Run()
override IEnumerable< Status > AI_Eat.Run () inline virtual
Reimplemented from AIAct.
Definition at line 38 of file AI_Eat.cs.
    {
        if (target != null && (target.GetRootCard() == owner || target.parent == null))
        {
            owner.HoldCard(target, 1);
        }
        else if (target != null)
        {
            yield return DoGrab(target, 1);
        }
        else
        {
            if (!IsValidTarget(owner.held))
            {
                yield return DoGrab<TraitFood>();
                if (!IsValidTarget(owner.held))
                {
                    yield return Cancel();
                }
            }
            if (cook)
            {
                yield return Do(new AI_Cook(), base.KeepRunning);
                if (!IsValidTarget(owner.held))
                {
                    yield return Cancel();
                }
                yield return DoGotoSpot<TraitHearth>(base.KeepRunning);
            }
        }
        target = owner.held;
        if (target == null)
        {
            yield return Cancel();
        }
        if (EClass._zone.IsPCFaction && !owner.IsPCParty && owner.memberType != FactionMemberType.Livestock && !owner.noMove)
        {
            yield return DoGotoSpot<TraitSpotDining>(base.KeepRunning);
        }
        int max = ((target.SelfWeight < 100) ? 1 : (2 + (int)Mathf.Sqrt(target.SelfWeight * 2 / 3)));
        int turn = 0;
        Progress_Custom seq = new Progress_Custom
        {
            cancelWhenMoved = false,
            canProgress = () => IsValidTarget(target) && owner.held == target,
            onProgressBegin = delegate
            {
                owner.Say("eat_start", owner, target.GetName(NameStyle.Full, 1));
                owner.PlaySound("eat");
            },
            onProgress = delegate(Progress_Custom p)
            {
                target.PlayAnime(AnimeID.Eat);
                if (turn == 1 && owner.IsPC && owner.hunger.GetPhase() == 0 && !EClass.debug.godFood)
                {
                    owner.Say("eat_full");
                    p.Cancel();
                }
                if (turn == 1)
                {
                    foreach (Element value in target.elements.dict.Values)
                    {
                        if (!value.source.foodEffect.IsEmpty())
{
                            string[] foodEffect = value.source.foodEffect;
                            if (foodEffect[0] == "poison" || foodEffect[0] == "love")
{
                                owner.Talk("eatWeird");
                                break;
                            }
                        }
                    }
                    CardRow refCard = target.refCard;
                    if (refCard != null && refCard.id == "mammoth")
                    {
                        EClass.player.forceTalk = true;
                        owner.Talk("eatammoth");
                    }
                }
                turn++;
            },
            onProgressComplete = delegate
            {
                if (owner.IsPC && owner.hunger.GetPhase() == 0 && !EClass.debug.godFood)
                {
                    owner.Say("eat_full");
                }
                else
                {
                    owner.Say("eat_end", owner, target.GetName(NameStyle.Full, 1));
                    owner.ShowEmo(Emo.happy);
                    FoodEffect.Proc(owner, target.Thing);
                    target.ModNum(-1);
                }
            }
        }.SetDuration(max, 5);
        yield return Do(seq);
    }
References EClass._zone, AIAct.Cancel(), cook, EClass.debug, ElementContainer.dict, AIAct.Do(), AIAct.DoGrab(), Card.elements, Card.GetName(), Stats.GetPhase(), Card.GetRootCard(), CoreDebug.godFood, Chara.held, Chara.HoldCard(), Chara.hunger, CardRow.id, Chara.IsPC, Zone.IsPCFaction, Chara.IsPCParty, IsValidTarget(), AIAct.KeepRunning(), Chara.memberType, Card.ModNum(), Card.noMove, AIAct.owner, Card.parent, Card.PlayAnime(), Card.PlaySound(), FoodEffect.Proc(), Card.refCard, Card.Say(), Card.SelfWeight, Card.ShowEmo(), Element.source, Card.Talk(), target, and Card.Thing.
Member Data Documentation
cook
bool AI_Eat.cook = true
Definition at line 8 of file AI_Eat.cs.
Referenced by Run().
target
Card AI_Eat.target
Definition at line 6 of file AI_Eat.cs.
Referenced by Run().
Property Documentation
IsHostileAct
override bool AI_Eat.IsHostileAct get
Definition at line 12 of file AI_Eat.cs.
    {
        get
        {
            if (target != null)
            {
                return target.isNPCProperty;
            }
            return false;
        }
    }
LocalAct
override bool AI_Eat.LocalAct get
Definition at line 10 of file AI_Eat.cs.
The documentation for this class was generated from the following file:
Elin/AI_Eat.cs