Elin Decompiled Documentation: AI_Steal Class Reference
AI_Steal Class Reference
Public Member Functions
override bool IsValidTC (Card c)
override bool CanPerform ()
override bool Perform ()
override IEnumerable< Status > Run ()
Public Member Functions inherited from AI_TargetCard
override bool CanProgress ()
override IEnumerable< Status > Run ()
Public Member Functions inherited from AIAct
override string ToString ()
override MultiSprite GetStateIcon ()
virtual bool ShouldAllyAttack (Chara tg)
virtual Point GetDestination ()
AIProgress GetProgress ()
string GetCurrentActionText ()
override bool IsToolValid ()
virtual void OnStart ()
void SetOwner (Chara c)
virtual void OnSetOwner ()
void SetChild (AIAct seq, Func< Status > _onChildFail=null)
void Start ()
override bool Perform ()
Status Restart ()
Status Success (Action action=null)
virtual void OnSuccess ()
bool TryCancel (Card c)
virtual Status Cancel ()
virtual void OnCancel ()
virtual void OnCancelOrSuccess ()
virtual bool CanManualCancel ()
Status KeepRunning ()
void Reset ()
virtual void OnReset ()
Status Tick ()
virtual IEnumerable< Status > Run ()
Status TickChild ()
Status Do (AIAct _seq, Func< Status > _onChildFail=null)
Status DoGotoInteraction (Point pos, Func< Status > _onChildFail=null)
Status DoGoto (Point pos, int dist=0, bool ignoreConnection=false, Func< Status > _onChildFail=null)
Status DoGoto (Card card, Func< Status > _onChildFail=null)
Status DoGoto (Card card, int dist, Func< Status > _onChildFail=null)
Status DoGotoSpot (Card card, Func< Status > _onChildFail=null)
Status DoGoto< T > (Func< Status > _onChildFail=null)
Status DoGotoSpot< T > (Func< Status > _onChildFail=null, bool ignoreAccessType=false)
Status DoGrab (Card card, int num=-1, bool pickHeld=false, Func< Status > _onChildFail=null)
Status DoGrab< T > ()
Status DoProgress ()
Status DoIdle (int repeat=3)
Status DoWait (int count=1)
virtual AIProgress CreateProgress ()
virtual void OnCreateProgress (Progress_Custom p)
virtual bool CanProgress ()
virtual void OnBeforeProgress ()
virtual void OnProgress ()
virtual void OnProgressComplete ()
void SimulateZone (int days)
virtual void OnSimulateZone (int days)
virtual void OnSimulatePosition ()
Public Member Functions inherited from Act
virtual CursorInfo GetCursorIcon (Card c)
virtual MultiSprite GetStateIcon ()
override Sprite GetSprite ()
virtual bool ShowMouseHint (Card c)
virtual bool IsValidTC (Card c)
virtual string GetHintText (string str="")
virtual string GetText (string str="")
virtual string GetTextSmall (Card c)
bool IsTargetHostileParty ()
virtual Color GetActPlanColor ()
virtual bool Perform ()
virtual bool CanPerform ()
bool Perform (Chara _cc, Card _tc=null, Point _tp=null)
bool CanPerform (Chara _cc, Card _tc=null, Point _tp=null)
virtual bool IsToolValid ()
new void SetImage (Image image)
virtual void OnMarkMapHighlights ()
virtual bool ShouldMapHighlight (Point p)
Public Member Functions inherited from Element
virtual SourceElement.Row GetSource ()
virtual int GetSourcePotential (int v)
virtual Sprite GetSprite ()
int GetMaterialSourceValue (Thing t, int v)
virtual int GetSourceValue (int v, int lv, SourceValueType type)
virtual Sprite GetIcon (string suffix="")
bool IsActive (Card c)
int SortVal (bool charaSheet=false)
virtual bool CanLink (ElementContainer owner)
bool HasTag (string tag)
void SetImage (Image i)
virtual string GetDetail ()
bool IsFactionElement (Chara c)
Element GetParent (Card c)
void WriteNote (UINote n, ElementContainer owner=null, Action< UINote > onWriteNote=null)
void WriteNoteWithRef (UINote n, ElementContainer owner, Action< UINote > onWriteNote, Element refEle)
void _WriteNote (UINote n, Chara c, Act act)
void AddHeaderAbility (UINote n)
void _WriteNote (UINote n, ElementContainer owner, Action< UINote > onWriteNote, bool isRef, bool addHeader=true)
void AddEncNote (UINote n, Card Card, ElementContainer.NoteMode mode=ElementContainer.NoteMode.Default, Func< Element, string, string > funcText=null, Action< UINote, Element > onAddNote=null)
virtual void OnWriteNote (UINote n, ElementContainer owner)
virtual void OnChangeValue ()
void CheckLevelBonus (ElementContainer owner, UINote n=null)
int GetSortVal (UIList.SortMode m)
virtual Act.Cost GetCost (Chara c)
virtual int GetPower (Card c)
virtual void SetTextValue (UIText text)
virtual bool IsPurchaseFeatReqMet (ElementContainer owner, int lv=-1)
virtual void WritePurchaseReq (UINote n, int lv=1)
Properties
override TargetType TargetType [get]
override int MaxRadius [get]
override bool IsHostileAct [get]
Properties inherited from AI_TargetCard
virtual bool GotoTarget [get]
override bool HasProgress [get]
virtual bool CanTargetInventory [get]
Properties inherited from AIAct
virtual bool IsRunning [get]
bool IsChildRunning [get]
bool IsMoveAI [get]
virtual int MaxRestart [get]
virtual new string Name [get]
virtual MultiSprite stateIcon [get]
virtual Sprite actionIcon [get]
virtual bool IsNoGoal [get]
virtual bool IsAutoTurn [get]
virtual bool IsIdle [get]
virtual bool CancelOnAggro [get]
virtual bool PushChara [get]
virtual int MaxProgress [get]
virtual bool ShowProgress [get]
virtual bool UseTurbo [get]
virtual int CurrentProgress [get]
virtual bool ShowCursor [get]
virtual bool CancelWhenDamaged [get]
virtual bool CancelWhenMoved [get]
virtual bool InformCancel [get]
virtual Thing RenderThing [get]
AIAct Current [get]
override bool IsAct [get]
override bool ShowPotential [get]
override bool UsePotential [get]
override bool ShowRelativeAttribute [get]
virtual bool HasProgress [get]
Properties inherited from Act
override bool ShowPotential [get]
override bool UsePotential [get]
override bool ShowRelativeAttribute [get]
virtual CursorInfo CursorIcon [get]
virtual string ID [get]
virtual bool IsAct [get]
virtual bool WillEndTurn [get]
virtual bool CloseLayers [get]
virtual int LeftHand [get]
virtual int RightHand [get]
virtual int ElementPowerMod [get]
virtual bool ShowMapHighlight [get]
virtual bool ShowMapHighlightBlock [get]
virtual bool PickHeldOnStart [get]
virtual bool DropHeldOnStart [get]
virtual bool CanPressRepeat [get]
virtual bool CanAutofire [get]
virtual bool ResetAxis [get]
virtual bool RequireTool [get]
virtual bool IsHostileAct [get]
virtual bool HideRightInfo [get]
virtual bool HaveLongPressAction [get]
virtual float Radius [get]
virtual int PerformDistance [get]
virtual int MaxRadius [get]
virtual TargetType TargetType [get]
virtual bool LocalAct [get]
virtual bool CanRapidFire [get]
virtual float RapidDelay [get]
virtual bool ShowAuto [get]
virtual bool IsCrime [get]
Properties inherited from Element
SourceElement.Row source [get]
virtual int DisplayValue [get]
virtual int MinValue [get]
int Value [get]
int ValueWithoutLink [get]
virtual int MinPotential [get]
int Potential [get]
virtual bool CanGainExp [get]
bool IsFlag [get]
virtual string Name [get]
virtual string FullName [get]
virtual int ExpToNext [get]
virtual bool UseExpMod [get]
virtual int CostTrain [get]
virtual int CostLearn [get]
virtual bool ShowXP [get]
virtual bool ShowMsgOnValueChanged [get]
virtual bool ShowValue [get]
virtual bool ShowPotential [get]
virtual bool UsePotential [get]
virtual bool PotentialAsStock [get]
virtual bool ShowRelativeAttribute [get]
virtual bool ShowBonuses [get]
virtual string ShortName [get]
bool IsGlobalElement [get]
bool IsFactionWideElement [get]
bool IsPartyWideElement [get]
virtual bool ShowEncNumber [get]
bool IsTrait [get]
bool IsFoodTrait [get]
bool IsFoodTraitMain [get]
bool IsMainAttribute [get]
Act act [get]
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Additional Inherited Members
Public Types inherited from AIAct
enum Status { Running , Fail , Success }
Public Types inherited from Act
enum CostType { None , MP , SP }
Static Public Member Functions inherited from Act
static void SetReference (Chara _cc, Card _tc=null, Point _tp=null)
static void SetTool (Thing t)
Static Public Member Functions inherited from Element
static string GetName (string alias)
static SourceElement.Row Get (int id)
static Dictionary< int, int > GetElementMap (int[] list)
static Dictionary< int, int > GetElementMap (int[] list, Dictionary< int, int > map)
static SourceElement.Row GetRandomElement (int lv=1, bool useWeight=true)
static Element Create (int id, int v=0)
static Element Create (string id, int v=1)
static int GetId (string alias)
static int GetResistLv (int v)
static int GetResistDamage (int dmg, int v, int power=0)
Static Public Member Functions inherited from EClass
static int rndSeed (int a, int seed)
static int rnd (int a)
static int curve (int a, int start, int step, int rate=75)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Public Attributes inherited from AI_TargetCard
Card target
Public Attributes inherited from AIAct
new Chara owner
Status status
IEnumerator< Status > Enumerator
AIAct child
AIAct parent
byte restartCount
Func< Status > onChildFail
Func< bool > isFail
Public Attributes inherited from Element
SourceElement.Row _source
int id
int vBase
int vExp
int vPotential
int vTempPotential
int vLink
int vSource
int vSourcePotential
ElementContainer owner
Static Public Attributes inherited from Act
static Chara CC
static Card TC
static Point TP = new Point()
static Thing TOOL
static int powerMod = 100
static bool forcePt
static Act CurrentAct
Static Public Attributes inherited from Element
const int Div = 5
static Element Void = new Element()
static int[] List_MainAttributes = new int[9] { 70, 72, 71, 77, 74, 75, 76, 73, 79 }
static int[] List_MainAttributesMajor = new int[8] { 70, 72, 71, 77, 74, 75, 76, 73 }
static int[] List_Body = new int[4] { 70, 72, 71, 77 }
static int[] List_Mind = new int[4] { 74, 75, 76, 73 }
static List< SourceElement.Row > ListElements = new List<SourceElement.Row>()
static List< SourceElement.Row > ListAttackElements = new List<SourceElement.Row>()
Static Public Attributes inherited from EClass
static Core core
Detailed Description
Definition at line 4 of file AI_Steal.cs.
Member Function Documentation
CanPerform()
override bool AI_Steal.CanPerform () inline virtual
Reimplemented from Act.
Definition at line 41 of file AI_Steal.cs.
    {
        if (Act.TC != null)
        {
            return Act.TC.trait.CanBeStolen;
        }
        return false;
    }
References Trait.CanBeStolen, Act.TC, and Card.trait.
IsValidTC()
override bool AI_Steal.IsValidTC (Card c) inline virtual
Reimplemented from Act.
Definition at line 12 of file AI_Steal.cs.
    {
        if (EClass._zone.IsUserZone)
        {
            return false;
        }
        if (c.isThing & (EClass._zone is Zone_LittleGarden))
        {
            return false;
        }
        if (!c.isNPCProperty && c.isThing)
        {
            return false;
        }
        if (!c.trait.CanBeStolen)
        {
            return false;
        }
        if (c.c_lockLv > 0)
        {
            return false;
        }
        if (!c.isThing)
        {
            return !c.IsPCFaction;
        }
        return true;
    }
References EClass._zone, Card.c_lockLv, Trait.CanBeStolen, Card.isNPCProperty, Card.IsPCFaction, Card.isThing, Zone.IsUserZone, and Card.trait.
Perform()
override bool AI_Steal.Perform () inline virtual
Reimplemented from Act.
Definition at line 50 of file AI_Steal.cs.
    {
        target = Act.TC;
        return base.Perform();
    }
References AI_TargetCard.target, and Act.TC.
Run()
override IEnumerable< Status > AI_Steal.Run () inline virtual
Reimplemented from AIAct.
Definition at line 56 of file AI_Steal.cs.
    {
        Chara chara = target.Chara;
        if (chara != null)
        {
            target = chara.things.FindStealable();
            if (target == null && chara.GetInt(30) < EClass.world.date.GetRaw())
            {
                if (EClass.rnd(2) == 0)
                {
                    target = chara.AddThing(ThingGen.Create("money").SetNum(1 + EClass.rnd(chara.LV * 10)));
                    if (EClass.rnd(3) == 0)
                    {
                        chara.SetInt(30, EClass.world.date.GetRaw() + 1440);
                    }
                }
                else
                {
                    target = chara.AddThing(ThingGen.CreateFromFilter("steal", chara.LV));
                    chara.SetInt(30, EClass.world.date.GetRaw() + 1440);
                }
            }
            if (target == null)
            {
                owner.Say("steal_chara_nothing", owner, chara);
                yield return Cancel();
            }
            owner.Say("steal_chara", owner, chara);
        }
        else
        {
            if (target.things.Count > 0)
            {
                Thing thing = target.things.FindStealable();
                if (thing != null)
                {
                    target = thing;
                }
            }
            owner.Say("steal_thing", owner, target);
        }
        ICardParent targetParent = target.parent;
        Card card = chara;
        if (card == null)
        {
            card = target;
        }
        Card root = card.GetRootCard();
        Progress_Custom seq = new Progress_Custom
        {
            canProgress = () => target.parent == targetParent && (chara == null || chara.ExistsOnMap),
            onProgressBegin = delegate
            {
            },
            onProgress = delegate(Progress_Custom p)
            {
                owner.LookAt(root);
                owner.PlaySound("steal");
                root.renderer.PlayAnime(AnimeID.Shiver);
                if (!EClass.debug.godMode)
                {
                    if (chara != null && owner.Dist(chara) > 1)
                    {
                        EClass.pc.TryMoveTowards(chara.pos);
                        if (owner == null)
{
                            p.Cancel();
                            return;
                        }
                        if (chara != null && owner.Dist(chara) > 1)
{
                            EClass.pc.Say("targetTooFar");
                            p.Cancel();
                            return;
                        }
                    }
                    if (target.ChildrenAndSelfWeight > owner.Evalue(281) * 200 + owner.STR * 100 + 1000)
                    {
                        EClass.pc.Say("tooHeavy", target);
                        p.Cancel();
                    }
                    else
                    {
                        int count = owner.pos.ListWitnesses(owner, 4, WitnessType.crime, chara).Count;
                        if (owner.pos.TryWitnessCrime(owner, chara, 4, delegate(Chara c)
{
                            int num = ((!c.CanSee(owner)) ? 30 : 0);
                            int num2 = c.PER * 250 / 100;
                            if (target.isThing && (target.Thing.isEquipped || target.IsRangedWeapon || target.IsThrownWeapon))
{
                                num2 *= 2;
                                if (target.rarity >= Rarity.Legendary)
{
                                    num2 *= 2;
                                }
                                if (target.rarity >= Rarity.Artifact)
{
                                    num2 *= 2;
                                }
                            }
                            if (c.IsUnique)
{
                                num2 *= 2;
                            }
                            return EClass.rnd(num2) > owner.Evalue(281) + owner.DEX + num;
                        }))
{
                            p.Cancel();
                        }
                        else
{
                            owner.elements.ModExp(281, Mathf.Min(count * 5 + 5, 25));
                        }
                    }
                }
            },
            onProgressComplete = delegate
            {
                if (target.isThing && target.IsInstalled)
                {
                    target.SetPlaceState(PlaceState.roaming);
                }
                owner.Say("steal_end", owner, target);
                if (chara != null && (chara.IsPCFaction || chara.OriginalHostility >= Hostility.Friend))
                {
                    EClass.player.ModKarma(-1);
                }
                else if (chara == null || chara.hostility > Hostility.Enemy)
                {
                    EClass.player.ModKarma(-1);
                }
                target.isNPCProperty = false;
                if (!target.category.IsChildOf("currency"))
                {
                    target.isStolen = true;
                }
                owner.Pick(target.Thing);
                owner.elements.ModExp(281, 50f);
                if (EClass.rnd(2) == 0)
                {
                    EClass.pc.stamina.Mod(-1);
                }
            }
        }.SetDuration(20, 4);
        yield return Do(seq);
    }
References Card.AddThing(), AIAct.Cancel(), Chara.CanSee(), card, Card.category, Card.Chara, Card.ChildrenAndSelfWeight, ThingGen.Create(), ThingGen.CreateFromFilter(), World.date, EClass.debug, Card.Dist(), AIAct.Do(), Card.elements, Card.Evalue(), Card.ExistsOnMap, ThingContainer.FindStealable(), BaseCard.GetInt(), Date.GetRaw(), CoreDebug.godMode, Chara.hostility, Thing.isEquipped, Card.IsInstalled, Chara.IsPCFaction, Card.IsRangedWeapon, Card.isThing, Card.IsThrownWeapon, Card.IsUnique, Point.ListWitnesses(), Chara.LookAt(), Card.LV, Stats.Mod(), ElementContainer.ModExp(), Player.ModKarma(), Chara.OriginalHostility, AIAct.owner, Card.parent, EClass.pc, Chara.Pick(), CardRenderer.PlayAnime(), EClass.player, Card.PlaySound(), Card.pos, Card.rarity, Card.renderer, EClass.rnd(), Card.Say(), BaseCard.SetInt(), Card.SetNum(), Card.SetPlaceState(), Chara.stamina, Card.STR, AI_TargetCard.target, Card.Thing, Card.things, Chara.TryMoveTowards(), Point.TryWitnessCrime(), and EClass.world.
Property Documentation
IsHostileAct
override bool AI_Steal.IsHostileAct get
Definition at line 10 of file AI_Steal.cs.
MaxRadius
override int AI_Steal.MaxRadius get
Definition at line 8 of file AI_Steal.cs.
TargetType
override TargetType AI_Steal.TargetType get
Definition at line 6 of file AI_Steal.cs.
The documentation for this class was generated from the following file:
Elin/AI_Steal.cs