Elin Decompiled Documentation: Thing Class Reference
Thing Class Reference
Public Member Functions
bool CanAutoFire (Chara c, Card tg, bool reloading=false)
int GetEfficiency ()
override void SetSource ()
override void OnCreate (int genLv)
override void ApplyMaterialElements (bool remove)
override void ApplyMaterial (bool remove=false)
override string GetName (NameStyle style, int _num=-1)
override string GetHoverText ()
override string GetExtraName ()
List< Element > ListLimitedValidTraits (bool limit)
List< Element > ListValidTraits (bool isCraft, bool limit)
override void WriteNote (UINote n, Action< UINote > onWriteNote=null, IInspect.NoteMode mode=IInspect.NoteMode.Default, Recipe recipe=null)
override void SetRenderParam (RenderParam p)
override SubPassData GetSubPassData ()
override bool CanStackTo (Thing to)
void GetIngredients (Recipe.Ingredient ing, List< Thing > list)
bool IsValidIngredient (Recipe.Ingredient ing)
void GetRecipes (HashSet< Recipe > recipes)
void GetDisassembles (List< Thing > list)
void Disassemble ()
void ShowSplitMenu (ButtonGrid button, InvOwner.Transaction trans=null)
void ShowSplitMenu2 (ButtonGrid button, string lang, Action< int > onSplit=null)
void DoAct (Act act)
void TryLickEnchant (Chara c, bool msg=true, Chara tg=null, BodySlot slot=null)
Element AddEnchant (int lv=-1)
void RemoveEnchant ()
Thing Identify (bool show=true, IDTSource idtSource=IDTSource.Identify)
Public Member Functions inherited from Card
override string ToString ()
bool CanReserve (AIAct act)
bool TryReserve (AIAct act)
void Mod ()
Window.SaveData GetWindowSaveData ()
bool IsExcludeFromCraft ()
void SetDirtyWeight ()
void ChangeWeight (int a)
int Evalue (int ele)
int Evalue (string alias)
bool HasTag (CTAG tag)
bool HasEditorTag (EditorTag tag)
void AddEditorTag (EditorTag tag)
void RemoveEditorTag (EditorTag tag)
virtual string GetName (NameStyle style, int num=-1)
virtual string GetExtraName ()
virtual string GetDetail ()
int GetBestAttribute ()
void ModExp (string alias, int a)
void ModExp (int ele, int a)
bool IsChildOf (Card c)
string ReferenceId ()
void Create (string _id, int _idMat=-1, int genLv=-1)
virtual void OnBeforeCreate ()
virtual void OnCreate (int genLv)
virtual void SetSource ()
virtual void ApplyEditorTags (EditorTag tag)
void ApplyTrait ()
Card SetLv (int a)
void AddExp (int a)
void LevelUp ()
virtual void ApplyMaterialElements (bool remove)
virtual void ApplyMaterial (bool remove=false)
Card ChangeMaterial (int idNew)
Card ChangeMaterial (string idNew)
Card ChangeMaterial (SourceMaterial.Row row)
void SetReplica (bool on)
Thing Add (string id, int num=1, int lv=1)
Card AddCard (Card c)
void RemoveCard (Card c)
void NotifyAddThing (Thing t, int num)
Thing AddThing (string id, int lv=-1)
Thing AddThing (Thing t, bool tryStack=true, int destInvX=-1, int destInvY=-1)
void PurgeDuplicateArtifact (Thing af)
void RemoveThings ()
void RemoveThing (Thing thing)
bool ShouldTrySetDirtyInventory ()
virtual bool CanStackTo (Thing to)
bool TryStackTo (Thing to)
ICardParent GetRoot ()
Card GetRootCard ()
bool IsStackable (Thing tg)
Thing Duplicate (int num)
Thing Split (int a)
Thing SetNum (int a)
Thing SetNoSell ()
void ModNum (int a, bool notify=true)
void AddSocket ()
void ApplySocket (Thing t)
void ApplySocket (int id, int lv, Card mod=null)
void EjectSockets ()
void OnChildNumChange (Card c)
Card Install ()
void SetPlaceState (PlaceState newState, bool byPlayer=false)
int GetTotalQuality (bool applyBonus=true)
void ModEncLv (int a)
void SetEncLv (int a)
virtual void SetBlessedState (BlessedState s)
virtual void ChangeRarity (Rarity q)
bool TryPay (int a, string id="money")
void SetCharge (int a)
void ModCharge (int a, bool destroy=false)
void ModCurrency (int a, string id="money")
int GetCurrency (string id="money")
virtual void HealHPHost (int a, HealSource origin=HealSource.None)
virtual void HealHP (int a, HealSource origin=HealSource.None)
virtual int GetArmorSkill ()
virtual int ApplyProtection (int dmg, int mod=100)
void DamageHP (int dmg, AttackSource attackSource=AttackSource.None, Card origin=null)
void DamageHP (int dmg, int ele, int eleP=100, AttackSource attackSource=AttackSource.None, Card origin=null, bool showEffect=true)
virtual void Die (Element e=null, Card origin=null, AttackSource attackSource=AttackSource.None)
void Explode (Point p, Card origin)
void Deconstruct ()
void Destroy ()
void SpawnLoot (Card origin)
Thing TryMakeRandomItem (int lv=-1)
Card MakeFoodFrom (string _id)
Card MakeFoodFrom (Card c)
void MakeFoodRef (Card c1, Card c2=null)
string TryGetFoodName (Card c)
string GetFoodName (string s)
void MakeFigureFrom (string id)
void MakeRefFrom (string id)
void MakeRefFrom (Card c1, Card c2=null)
void SetHidden (bool hide=true)
virtual Card.MoveResult _Move (Point p, Card.MoveType type=Card.MoveType.Walk)
unsafe void MoveImmediate (Point p, bool focus=true, bool cancelAI=true)
unsafe void Teleport (Point point, bool silent=false, bool force=false)
virtual void OnLand ()
int ResistLvFrom (int ele)
int ResistLv (int res)
bool HasElement (int ele, int req=1)
bool HasElement (string id, int req=1)
virtual CardRenderer _CreateRenderer ()
void AddBlood (int a=1, int id=-1)
RenderParam GetRenderParam ()
virtual void SetRenderParam (RenderParam p)
void DyeRandom ()
void Dye (string idMat)
void Dye (SourceMaterial.Row mat)
void RefreshColor ()
ref Color GetRandomColor ()
virtual Sprite GetSprite (int dir=0)
virtual Sprite GetImageSprite ()
void SetImage (Image image, int dir, int idSkin=0)
virtual void SetImage (Image image)
void ShowEmo (Emo _emo=Emo.none, float duration=0f, bool skipSame=true)
void PlaySoundHold (bool spatial=true)
void PlaySoundDrop (bool spatial=true)
SoundSource PlaySound (string id, float v=1f, bool spatial=true)
void KillAnime ()
void PlayAnime (AnimeID id, bool force=false)
void PlayAnime (AnimeID id, Point dest, bool force=false)
void PlayAnimeLoot ()
unsafe Effect PlayEffect (string id, bool useRenderPos=true, float range=0f, Vector3 fix=default(Vector3))
unsafe void PlayEffect (int ele, bool useRenderPos=true, float range=0f)
virtual void SetDir (int d)
void SetRandomDir ()
virtual void LookAt (Card c)
virtual void LookAt (Point p)
virtual void Rotate (bool reverse=false)
void ChangeAltitude (int a)
virtual SubPassData GetSubPassData ()
unsafe void SetFreePos (Point point)
unsafe void RenderMarker (Point point, bool active, HitResult result, bool main, int dir, bool useCurrentPosition=false)
void RecalculateFOV ()
bool HasLight ()
float GetLightPower ()
int GetSightRadius ()
int GetLightRadius ()
void CalculateFOV ()
void SetRandomLightColors ()
Fov CreateFov ()
void ClearFOV ()
virtual void OnSimulateHour (VirtualDate date)
void DecayNatural (int hour=1)
void Decay (int a=10)
void Talk (string idTopic, string ref1=null, string ref2=null, bool forceSync=false)
void TalkRaw (string text, string ref1=null, string ref2=null, bool forceSync=false)
string ApplyNewLine (string text)
void SayRaw (string text, string ref1=null, string ref2=null)
void SayNothingHappans ()
void Say (string lang, string ref1=null, string ref2=null)
void Say (string lang, Card c1, Card c2, string ref1=null, string ref2=null)
void Say (string lang, Card c1, string ref1=null, string ref2=null)
string GetTalkText (string idTopic, bool stripPun=false, bool useDefault=true)
string ApplyTone (string text, bool stripPun=false)
void SetRandomTalk ()
void SetRandomTone ()
void TryStack (Thing t)
void ApplyBacker (int bid)
void RemoveBacker ()
void SetPaintData ()
byte[] GetPaintData ()
void ClearPaintSprite ()
Sprite GetPaintSprite ()
void TryUnrestrain (bool force=false, Chara c=null)
TraitShackle GetRestrainer ()
virtual void Tick ()
Thing SetPriceFix (int a)
int GetEquipValue ()
void SetSale (bool sale)
int GetValue (bool sell=false)
virtual int GetPrice (CurrencyType currency=CurrencyType.Money, bool sell=false, PriceType priceType=PriceType.Default, Chara c=null)
virtual string GetHoverText ()
virtual string GetHoverText2 ()
int Dist (Card c)
int Dist (Point p)
bool IsInMutterDistance (int d=10)
void SetCensored (bool enable)
void SetDeconstruct (bool deconstruct)
virtual void SetSortVal (UIList.SortMode m, CurrencyType currency=CurrencyType.Money)
virtual int SecondaryCompare (UIList.SortMode m, Card c)
void ForeachFOV (Func< Point, bool > func)
void ForeachPoint (Action< Point, bool > action)
void OnInspect ()
virtual void WriteNote (UINote n, Action< UINote > onWriteNote=null, IInspect.NoteMode mode=IInspect.NoteMode.Default, Recipe recipe=null)
void Inspect ()
virtual bool HasCondition< T > ()
bool HaveFur ()
bool CanBeSheared ()
Public Member Functions inherited from BaseCard
bool GetBool (int id)
void SetBool (int id, bool enable)
int GetInt (int id, int? defaultInt=null)
void AddInt (int id, int value)
void SetInt (int id, int value=0)
string GetStr (int id, string defaultStr=null)
void SetStr (int id, string value=null)
T GetObj< T > (int id)
void SetObj (int id, object o)
T SetObj< T > (int id, object o)
ICardParent GetRoot ()
void RemoveCard (Card c)
void OnChildNumChange (Card c)
string ReferenceId ()
void WriteNote (UINote n, Action< UINote > onWriteNote=null, IInspect.NoteMode mode=IInspect.NoteMode.Default, Recipe recipe=null)
void OnInspect ()
Static Public Member Functions
static void AddAttackEvaluation (UINote n, Chara chara, Thing current=null)
static Tuple< SourceElement.Row, int > GetEnchant (int lv, Func< SourceElement.Row, bool > func, bool neg)
Static Public Member Functions inherited from Card
static string ApplyTone (Chara c, ref string text, string _tones, int gender, bool stripPun=false)
static int GetTilePrice (TileRow row, SourceMaterial.Row mat)
Static Public Member Functions inherited from EClass
static int rnd (int a)
static int curve (int a, int start, int step, int rate=75)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Public Attributes
SourceThing.Row source
int stackOrder
string tempName
Public Attributes inherited from Card
int[] _ints = new int[30]
string id = ""
ThingContainer things = new ThingContainer()
ElementContainerCard elements = new ElementContainerCard()
Biography bio
List< int > sockets
AIAct reservedAct
Props props
Trait trait
ICardParent parent
Fov fov
Point pos = new Point()
CardRenderer renderer
int turn
int _colorInt
float roundTimer
float angle = 180f
bool isDestroyed
CardBlueprint bp
BitArray32 _bits1
BitArray32 _bits2
PlaceState placeState
bool dirtyWeight = true
SourceMaterial.Row _material
Emo lastEmo
int sortVal
Public Attributes inherited from BaseCard
Dictionary< int, object > mapObj = new Dictionary<int, object>()
Dictionary< int, int > mapInt = new Dictionary<int, int>()
Dictionary< int, string > mapStr = new Dictionary<int, string>()
Static Public Attributes
const int MaxFurnitureEnc = 12
Static Public Attributes inherited from EClass
static Core core
Properties
bool isEquipped [get]
bool IsMeleeWithAmmo [get]
int range [get]
int Penetration [get]
override bool isThing [get]
override CardRow sourceCard [get]
override SourcePref Pref [get]
override int SelfWeight [get]
override int[] Tiles [get]
bool CanSearchContents [get]
bool IsSharedContainer [get]
Properties inherited from Card
Card parentCard [get]
Thing parentThing [get]
int colorInt [get]
bool IsHotItem [get]
int uid [get, set]
int idMaterial [get, set]
int dir [get, set]
int Num [get, set]
int _x [get, set]
int _z [get, set]
int refVal [get, set]
int decay [get, set]
int altitude [get, set]
int hp [get, set]
float fx [get, set]
float fy [get, set]
BlessedState blessedState [get, set]
PlaceState _placeState [get, set]
int rarityLv [get, set]
Rarity rarity [get, set]
int encLV [get, set]
int posInvX [get, set]
int posInvY [get, set]
int idSkin [get, set]
int feat [get, set]
int LV [get, set]
int exp [get, set]
int qualityTier [get, set]
bool isCensored [get, set]
bool isDeconstructing [get, set]
bool isDyed [get, set]
bool isModified [get, set]
bool isNew [get, set]
bool isPlayerCreation [get, set]
bool ignoreAutoPick [get, set]
bool freePos [get, set]
bool isHidden [get, set]
bool isOn [get, set]
bool isNPCProperty [get, set]
bool isRestrained [get, set]
bool isRoofItem [get, set]
bool isMasked [get, set]
bool disableAutoToggle [get, set]
bool isImported [get, set]
bool autoRefuel [get, set]
bool ignoreStackHeight [get, set]
bool isFloating [get, set]
bool isWeightChanged [get, set]
bool isFireproof [get, set]
bool isAcidproof [get, set]
bool isReplica [get, set]
bool isSummon [get, set]
bool isElemental [get, set]
bool isBroken [get, set]
bool isSubsetCard [get, set]
bool noSnow [get, set]
bool noMove [get, set]
bool isGifted [get, set]
bool isCrafted [get, set]
bool isLostProperty [get, set]
bool noShadow [get, set]
bool noSell [get, set]
bool isLeashed [get, set]
bool isStolen [get, set]
bool isSale [get, set]
bool isCopy [get, set]
bool isRestocking [get, set]
bool isBackerContent [get]
SourceBacker.Row sourceBacker [get]
BedType c_bedType [get, set]
int c_equippedSlot [get, set]
int c_lockLv [get, set]
Hostility c_originalHostility [get, set]
MinionType c_minionType [get, set]
int c_vomit [get, set]
bool c_isImportant [get, set]
bool c_lockedHard [get, set]
bool c_revealLock [get, set]
bool c_isTrained [get, set]
bool c_isPrayed [get, set]
bool c_isDisableStockUse [get, set]
int c_lightColor [get, set]
Color LightColor [get]
int c_uidZone [get, set]
int c_uidRefCard [get, set]
int c_priceFix [get, set]
int c_priceAdd [get, set]
int c_dyeMat [get, set]
VisitorState visitorState [get, set]
RescueState c_rescueState [get, set]
BossType c_bossType [get, set]
int c_dateStockExpire [get, set]
int c_IDTState [get, set]
int c_charges [get, set]
int c_bill [get, set]
int c_invest [get, set]
int c_seed [get, set]
int c_allowance [get, set]
int c_fur [get, set]
int c_containerSize [get, set]
int c_weight [get, set]
int c_diceDim [get, set]
int c_indexContainerIcon [get, set]
int c_idMainElement [get, set]
int c_summonDuration [get, set]
int c_idBacker [get, set]
int c_uidMaster [get, set]
int c_ammo [get, set]
int c_daysWithGod [get, set]
string c_idPortrait [get, set]
string c_idRace [get, set]
string c_idJob [get, set]
string c_idTone [get, set]
string c_color [get, set]
string c_idTalk [get, set]
string c_idDeity [get, set]
string c_altName [get, set]
string c_altName2 [get, set]
string c_refText [get, set]
string c_idRefName [get, set]
string c_idRidePCC [get, set]
string c_idAbility [get, set]
string c_context [get, set]
string c_idEditor [get, set]
string c_editorTags [get, set]
string c_editorTraitVal [get, set]
string c_idTrait [get, set]
string c_idRefCard [get, set]
string c_idRefCard2 [get, set]
string c_note [get, set]
UniqueData c_uniqueData [get, set]
Thing ammoData [get, set]
Thing c_copyContainer [get, set]
Window.SaveData c_windowSaveData [get, set]
CharaUpgrade c_upgrades [get, set]
CharaGenes c_genes [get, set]
List< int > c_corruptionHistory [get, set]
ContainerUpgrade c_containerUpgrade [get, set]
DNA c_DNA [get, set]
CharaList c_charaList [get, set]
byte[] c_textureData [get, set]
SourceMaterial.Row DyeMat [get]
int invX [get, set]
int invY [get, set]
CardRow refCard [get]
CardRow refCard2 [get]
int ExpToNext [get]
int DefaultLV [get]
int ChildrenWeight [get]
int ChildrenAndSelfWeight [get]
int ChildrenAndSelfWeightSingle [get]
virtual int SelfWeight [get]
virtual int WeightLimit [get]
SourceCategory.Row category [get]
SourceMaterial.Row material [get]
virtual string AliasMaterialOnCreate [get]
Cell Cell [get]
virtual Thing Thing [get]
virtual Chara Chara [get]
virtual bool isThing [get]
virtual bool isChara [get]
bool ExistsOnMap [get]
virtual bool isSynced [get]
bool IsContainer [get]
bool IsUnique [get]
bool IsPowerful [get]
bool IsImportant [get]
virtual SourcePref Pref [get]
virtual bool IsDeadOrSleeping [get]
virtual bool IsDisabled [get]
virtual bool IsMoving [get]
virtual bool flipX [get]
virtual bool IsAliveInCurrentZone [get]
virtual string actorPrefab [get]
virtual CardRow sourceCard [get]
virtual CardRow sourceRenderCard [get]
TileType TileType [get]
string Name [get]
string NameSimple [get]
string NameOne [get]
virtual bool IsPC [get]
bool _IsPC [get]
virtual bool IsPCC [get]
virtual bool IsPCParty [get]
virtual bool IsMinion [get]
virtual bool IsPCPartyMinion [get]
virtual bool IsPCFactionMinion [get]
virtual bool IsMultisize [get]
bool IsToolbelt [get]
bool IsLightsource [get]
bool IsEquipment [get]
bool IsFood [get]
bool ShowFoodEnc [get]
bool IsWeapon [get]
bool IsEquipmentOrRanged [get]
bool IsMeleeWeapon [get]
bool IsRangedWeapon [get]
bool IsThrownWeapon [get]
bool IsAmmo [get]
bool IsAgent [get]
bool IsFurniture [get]
bool IsBlessed [get]
bool IsCursed [get]
bool IsRestrainedResident [get]
virtual bool IsPCFaction [get]
bool IsPCFactionOrMinion [get]
virtual bool IsGlobal [get]
virtual int MaxDecay [get]
bool IsDecayed [get]
bool IsRotting [get]
bool IsFresn [get]
virtual int MaxHP [get]
virtual int Power [get]
int FameLv [get]
virtual int[] Tiles [get]
virtual int PrefIndex [get]
bool IsVariation [get]
virtual int DV [get]
virtual int PV [get]
int HIT [get]
int DMG [get]
int STR [get]
int DEX [get]
int END [get]
int PER [get]
int LER [get]
int WIL [get]
int MAG [get]
int CHA [get]
int INT [get]
int LUC [get]
int W [get]
int H [get]
bool IsIdentified [get]
string TextRarity [get]
bool IsInstalled [get]
bool IsMale [get]
bool IsNegativeGift [get]
bool HasContainerSize [get]
Thing Tool [get]
virtual SourceMaterial.Row DefaultMaterial [get]
virtual bool HasHost [get]
int Quality [get]
int QualityLv [get]
Point ThisOrParentPos [get]
LightData LightData [get]
CardRenderer HostRenderer [get]
bool ShouldShowMsg [get]
bool CanInspect [get]
string InspectName [get]
Point InspectPoint [get]
Vector3 InspectPosition [get]
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Properties inherited from IInspect
bool CanInspect [get]
string InspectName [get]
Point InspectPoint [get]
Vector3 InspectPosition [get]
Private Member Functions
void< ApplyMaterial > g__SetBase (int ele, int a, ref Thing.<>c__DisplayClass27_0 A_3)
Additional Inherited Members
Public Types inherited from Card
enum MoveResult { Fail , Success , Door }
enum MoveType { Walk , Force }
Public Types inherited from IInspect
enum NoteMode { Default , Recipe , Product , Info }
Protected Member Functions inherited from Card
virtual void OnSerializing ()
virtual void OnDeserialized ()
Static Package Functions inherited from Card
static bool< MakeFoodRef > g__IsIgnoreName (Card c)
static int< Dist > g__DistMulti (Point p1, Card c)
Detailed Description
Definition at line 8 of file Thing.cs.
Member Function Documentation
AddAttackEvaluation()
static void Thing.AddAttackEvaluation (UINote n, Chara chara, Thing current = null) inline static
Definition at line 1507 of file Thing.cs.
    {
        n.AddHeader("headerAttackEval", null);
        int num = 0;
        foreach (BodySlot bodySlot in chara.body.slots)
        {
            if (bodySlot.thing != null && bodySlot.elementId == 35 && bodySlot.thing.source.offense.Length >= 2)
            {
                AttackProcess.Current.Prepare(chara, bodySlot.thing, null, null, num, false);
                string text = AttackProcess.Current.GetText();
                if (bodySlot.thing == current)
                {
                    text = text.TagColor(() => true, null);
                }
                n.AddText(text, FontColor.DontChange);
                num++;
            }
        }
        AttackProcess.Current.Prepare(chara, null, null, null, 0, false);
        string text2 = AttackProcess.Current.GetText();
        if (num == 0)
        {
            text2 = text2.TagColor(() => true, null);
        }
        n.AddText(text2, FontColor.DontChange);
    }
References Chara.body, AttackProcess.Current, BodySlot.elementId, AttackProcess.GetText(), AttackProcess.Prepare(), CharaBody.slots, source, text, and BodySlot.thing.
Referenced by InvOwnerEquip.OnWriteNote().
AddEnchant()
Element Thing.AddEnchant (int lv = -1) inline
Definition at line 2010 of file Thing.cs.
    {
        if (base.IsToolbelt || base.IsLightsource)
        {
            return null;
        }
        Tuple<SourceElement.Row, int> enchant = Thing.GetEnchant(lv, (SourceElement.Row r) => r.IsEncAppliable(base.category), base.IsCursed);
        if (enchant == null)
        {
            return null;
        }
        return this.elements.ModBase(enchant.Item1.id, enchant.Item2);
    }
References GetEnchant().
Referenced by OnCreate().
ApplyMaterial()
override void Thing.ApplyMaterial (bool remove = false) inline virtual
Reimplemented from Card.
Definition at line 308 of file Thing.cs.
    {
        Thing.<>c__DisplayClass27_0 CS$<>8__locals1;
        CS$<>8__locals1.<>4__this = this;
        if (this.source.HasTag(CTAG.replica))
        {
            base.isReplica = true;
        }
        if (remove)
        {
            this.ApplyMaterialElements(true);
            base.isAcidproof = (base.isFireproof = false);
            return;
        }
        CS$<>8__locals1.pvSet = false;
        CS$<>8__locals1.dmgSet = false;
        CS$<>8__locals1.hitSet = false;
        if (this.sourceCard.quality == 4)
        {
            if (this.source.offense.Length != 0)
            {
                base.c_diceDim = this.source.offense[1];
            }
            if (this.source.offense.Length > 2)
            {
                this.<ApplyMaterial>g__SetBase|27_0(66, this.source.offense[2], ref CS$<>8__locals1);
            }
            if (this.source.offense.Length > 3)
            {
                this.<ApplyMaterial>g__SetBase|27_0(67, this.source.offense[3], ref CS$<>8__locals1);
            }
            if (this.source.defense.Length != 0)
            {
                this.<ApplyMaterial>g__SetBase|27_0(64, this.source.defense[0], ref CS$<>8__locals1);
            }
            if (this.source.defense.Length > 1)
            {
                this.<ApplyMaterial>g__SetBase|27_0(65, this.source.defense[1], ref CS$<>8__locals1);
            }
        }
        else
        {
            int num = 120;
            bool flag = !base.IsAmmo;
            if (base.rarity <= Rarity.Crude)
            {
                num = 150;
            }
            else if (base.rarity == Rarity.Superior)
            {
                num = 100;
            }
            else if (base.rarity >= Rarity.Legendary)
            {
                num = 80;
            }
            if (this.source.offense.Length != 0)
            {
                base.c_diceDim = this.source.offense[1] * base.material.dice / (num + (flag ? EClass.rnd(25) : 0));
            }
            if (this.source.offense.Length > 2)
            {
                this.<ApplyMaterial>g__SetBase|27_0(66, this.source.offense[2] * base.material.atk * 9 / (num - (flag ? EClass.rnd(30) : 0)), ref CS$<>8__locals1);
            }
            if (this.source.offense.Length > 3)
            {
                this.<ApplyMaterial>g__SetBase|27_0(67, this.source.offense[3] * base.material.dmg * 5 / (num - (flag ? EClass.rnd(30) : 0)), ref CS$<>8__locals1);
            }
            if (this.source.defense.Length != 0)
            {
                this.<ApplyMaterial>g__SetBase|27_0(64, this.source.defense[0] * base.material.dv * 7 / (num - (flag ? EClass.rnd(30) : 0)), ref CS$<>8__locals1);
            }
            if (this.source.defense.Length > 1)
            {
                this.<ApplyMaterial>g__SetBase|27_0(65, this.source.defense[1] * base.material.pv * 9 / (num - (flag ? EClass.rnd(30) : 0)), ref CS$<>8__locals1);
            }
        }
        if (base.isReplica)
        {
            if (this.source.offense.Length != 0)
            {
                base.c_diceDim = Mathf.Max(this.source.offense[1] / 3, 1);
            }
            if (this.source.offense.Length > 2)
            {
                this.<ApplyMaterial>g__SetBase|27_0(66, this.source.offense[2] / 3, ref CS$<>8__locals1);
            }
            if (this.source.offense.Length > 3)
            {
                this.<ApplyMaterial>g__SetBase|27_0(67, this.source.offense[3] / 3, ref CS$<>8__locals1);
            }
            if (this.source.defense.Length != 0)
            {
                this.<ApplyMaterial>g__SetBase|27_0(64, this.source.defense[0] / 3, ref CS$<>8__locals1);
            }
            if (this.source.defense.Length > 1)
            {
                this.<ApplyMaterial>g__SetBase|27_0(65, this.source.defense[1] / 3, ref CS$<>8__locals1);
            }
        }
        if (base.IsEquipmentOrRanged || base.IsAmmo)
        {
            if (base.IsWeapon || base.IsAmmo)
            {
                if (CS$<>8__locals1.dmgSet)
                {
                    this.elements.ModBase(67, base.encLV + ((base.blessedState == BlessedState.Blessed) ? 1 : 0));
                }
            }
            else if (CS$<>8__locals1.pvSet)
            {
                this.elements.ModBase(65, (base.encLV + ((base.blessedState == BlessedState.Blessed) ? 1 : 0)) * 2);
            }
        }
        if (this.sockets != null)
        {
            for (int i = 0; i < this.sockets.Count; i++)
            {
                int num2 = this.sockets[i];
                int num3 = num2 / 100;
                if (num3 == 67 & CS$<>8__locals1.dmgSet)
                {
                    this.elements.ModBase(67, num2 % 100);
                }
                if (num3 == 66 & CS$<>8__locals1.hitSet)
                {
                    this.elements.ModBase(66, num2 % 100);
                }
                if (num3 == 65 & CS$<>8__locals1.pvSet)
                {
                    this.elements.ModBase(65, num2 % 100);
                }
            }
        }
        if (base.material == null || base.material.elements == null)
        {
            string[] array = new string[5];
            array[0] = base.idMaterial.ToString();
            array[1] = "/";
            int num4 = 2;
            SourceMaterial.Row material = base.material;
            array[num4] = ((material != null) ? material.name : null);
            array[3] = "/";
            int num5 = 4;
            SourceMaterial.Row material2 = base.material;
            int[] array2 = (material2 != null) ? material2.elements : null;
            array[num5] = ((array2 != null) ? array2.ToString() : null);
            Debug.Log(string.Concat(array));
        }
        this.ApplyMaterialElements(false);
        foreach (string a in base.material.bits)
        {
            if (!(a == "fire"))
            {
                if (a == "acid")
                {
                    base.isAcidproof = true;
                }
            }
            else
            {
                base.isFireproof = true;
            }
        }
        if (base.rarity >= Rarity.Artifact)
        {
            base.isAcidproof = (base.isFireproof = true);
        }
        this._colorInt = 0;
    }
References ApplyMaterial(), ApplyMaterialElements(), Card.elements, SourceMaterial.Row.elements, g__SetBase(), material, ElementContainer.ModBase(), CardRow.quality, EClass.rnd(), Card.sockets, source, and sourceCard.
Referenced by ApplyMaterial().
ApplyMaterialElements()
override void Thing.ApplyMaterialElements (bool remove) inline virtual
Reimplemented from Card.
Definition at line 289 of file Thing.cs.
    {
        Chara chara = null;
        if (EClass.core.IsGameStarted && this.isEquipped)
        {
            Card rootCard = base.GetRootCard();
            chara = ((rootCard != null) ? rootCard.Chara : null);
            if (chara != null)
            {
                this.elements.SetParent(null);
            }
        }
        this.elements.ApplyMaterialElementMap(this, remove);
        if (chara != null)
        {
            this.elements.SetParent(chara);
        }
    }
References ElementContainer.ApplyMaterialElementMap(), Card.Chara, EClass.core, Card.elements, Card.GetRootCard(), and ElementContainer.SetParent().
Referenced by ApplyMaterial().
CanAutoFire()
bool Thing.CanAutoFire (Chara c, Card tg, bool reloading = false) inline
Definition at line 98 of file Thing.cs.
    {
        if (base.GetRootCard() != c)
        {
            return false;
        }
        if (base.HasTag(CTAG.throwWeapon))
        {
            return true;
        }
        if (!this.trait.CanAutofire)
        {
            return false;
        }
        if (this.trait is TraitToolRange)
        {
            if ((c.IsPCFaction && c.body.IsTooHeavyToEquip(this)) || reloading)
            {
                return false;
            }
        }
        else if (this.trait is TraitAbility && c.IsPC)
        {
            Act act = (this.trait as TraitAbility).act;
            Element element = c.elements.GetElement(act.id);
            if (act is Spell && (element == null || element.vPotential == 0))
            {
                return false;
            }
        }
        return true;
    }
References Chara.body, Trait.CanAutofire, Card.elements, ElementContainer.GetElement(), Element.id, Chara.IsPC, Chara.IsPCFaction, CharaBody.IsTooHeavyToEquip(), Card.trait, and Element.vPotential.
Referenced by AM_Adv._OnUpdateInput().
CanStackTo()
override bool Thing.CanStackTo (Thing to) inline virtual
Reimplemented from Card.
Definition at line 1654 of file Thing.cs.
    {
        if (this.trait.HasCharges || to.isEquipped || base.isModified || to.isModified || to.id != this.id || to.idMaterial != base.idMaterial || to.refVal != base.refVal || to.blessedState != base.blessedState || to.rarityLv != base.rarityLv || to.qualityTier != base.qualityTier || to.idSkin != base.idSkin || to.isGifted != base.isGifted)
        {
            return false;
        }
        if ((to.isDyed || base.isDyed) && to.c_dyeMat != base.c_dyeMat)
        {
            return false;
        }
        if (base.c_idRefCard != to.c_idRefCard || base.c_idRefCard2 != to.c_idRefCard2)
        {
            return false;
        }
        if (base.IsDecayed != to.IsDecayed)
        {
            return false;
        }
        if (!this.trait.CanStackTo(to))
        {
            return false;
        }
        if (base.noSell != to.noSell || base.isCopy != to.isCopy)
        {
            return false;
        }
        if (base.isStolen != to.isStolen)
        {
            return false;
        }
        if (base.isCrafted != to.isCrafted)
        {
            return false;
        }
        if ((to.isWeightChanged || base.isWeightChanged) && to.SelfWeight != this.SelfWeight)
        {
            return false;
        }
        if (to.c_IDTState != base.c_IDTState)
        {
            return false;
        }
        if (to.c_priceAdd != base.c_priceAdd || to.c_priceFix != base.c_priceFix)
        {
            return false;
        }
        if (to.ChildrenAndSelfWeight + base.ChildrenAndSelfWeight > 1000000000)
        {
            return false;
        }
        if (this.trait.IsRequireFuel && base.c_charges != to.c_charges)
        {
            return false;
        }
        bool flag = false;
        if (to.parent is Card)
        {
            Window.SaveData windowSaveData = (to.parent as Card).GetWindowSaveData();
            if (windowSaveData != null && windowSaveData.compress)
            {
                flag = true;
            }
        }
        if (flag)
        {
            if (base.encLV != to.encLV && !base.IsFood)
            {
                return false;
            }
            if (this.elements.dict.Count<KeyValuePair<int, Element>>() != to.elements.dict.Count<KeyValuePair<int, Element>>())
            {
                return false;
            }
            foreach (Element element in this.elements.dict.Values)
            {
                if (to.elements.GetElement(element.id) == null)
                {
                    return false;
                }
            }
            base.encLV = (to.encLV = Mathf.CeilToInt(1f * (float)(base.encLV * base.Num + to.encLV * to.Num) / (float)(base.Num + to.Num)));
            foreach (Element element2 in this.elements.dict.Values)
            {
                Element element3 = to.elements.GetElement(element2.id);
                element2.vBase = (element3.vBase = (element2.vBase * base.Num + element3.vBase * to.Num) / (base.Num + to.Num));
            }
            return true;
        }
        else
        {
            if (base.encLV != to.encLV)
            {
                return false;
            }
            if (this.elements.dict.Count<KeyValuePair<int, Element>>() != to.elements.dict.Count<KeyValuePair<int, Element>>())
            {
                return false;
            }
            foreach (Element element4 in this.elements.dict.Values)
            {
                Element element5 = to.elements.GetElement(element4.id);
                if (element5 == null || element4.vBase / 10 * 10 != element5.vBase / 10 * 10)
                {
                    return false;
                }
            }
            return true;
        }
        bool result;
        return result;
    }
References Card.blessedState, Card.c_charges, Card.c_dyeMat, Card.c_idRefCard, Card.c_idRefCard2, Card.c_IDTState, Card.c_priceAdd, Card.c_priceFix, Card.ChildrenAndSelfWeight, ElementContainer.dict, Card.elements, Card.encLV, ElementContainer.GetElement(), Card.id, Element.id, Card.idMaterial, Card.idSkin, Card.isCopy, Card.isCrafted, Card.IsDecayed, Card.isDyed, isEquipped, Card.isGifted, Card.isModified, Card.isStolen, Card.isWeightChanged, Card.noSell, Card.Num, Card.parent, Card.qualityTier, Card.rarityLv, Card.refVal, SelfWeight, and Element.vBase.
Referenced by ThingContainer.CanStack(), TaskDump.ListThingsToPut(), and DragItemCard.OnDragSpecial().
Disassemble()
void Thing.Disassemble () inline
Definition at line 1794 of file Thing.cs.
    {
    }
Referenced by LayerCraftFloat.RefreshDisassemble().
DoAct()
void Thing.DoAct (Act act) inline
Definition at line 1885 of file Thing.cs.
    {
        if (!EClass.pc.HasNoGoal || (act.LocalAct && EClass._zone.IsRegion))
        {
            SE.Beep();
            return;
        }
        EClass.player.hotItemToRestore = EClass.player.currentHotItem;
        if (act.IsAct)
        {
            act.Perform(EClass.pc, null, null);
            return;
        }
        AIAct ai = act as AIAct;
        EClass.pc.SetAI(ai);
        ActionMode.Adv.SetTurbo(-1);
    }
References EClass._zone, ActionMode.Adv, Player.currentHotItem, Chara.HasNoGoal, Act.IsAct, Spatial.IsRegion, Act.LocalAct, EClass.pc, Act.Perform(), EClass.player, Chara.SetAI(), and AM_Adv.SetTurbo().
Referenced by InvOwner.ListInteractions().
g__SetBase()
void< ApplyMaterial > Thing.g__SetBase (int ele, int a, ref Thing::<>c__DisplayClass27_0 A_3) inline private
Definition at line 2077 of file Thing.cs.
    {
        this.elements.SetBase(ele, a, 0);
        if (ele == 67)
        {
            A_3.dmgSet = true;
        }
        if (ele == 65)
        {
            A_3.pvSet = true;
        }
        if (ele == 66)
        {
            A_3.hitSet = true;
        }
    }
Referenced by ApplyMaterial().
GetDisassembles()
void Thing.GetDisassembles (List< Thing > list) inline
Definition at line 1790 of file Thing.cs.
    {
    }
Referenced by RecipeUpdater.RunDisassemble().
GetEfficiency()
int Thing.GetEfficiency () inline
Definition at line 131 of file Thing.cs.
    {
        return (int)(50 + base.LV * 10 + base.encLV * 10 + base.rarity * (Rarity)10 + (int)(base.blessedState * (BlessedState)10));
    }
Referenced by AIWork.GetSession().
GetEnchant()
static Tuple< SourceElement.Row, int > Thing.GetEnchant (int lv, Func< SourceElement::Row, bool > func, bool neg) inline static
Definition at line 1924 of file Thing.cs.
    {
        List<SourceElement.Row> list = new List<SourceElement.Row>();
        int num = 0;
        int num2 = lv + 5 + EClass.rndSqrt(10);
        float num3 = (float)(3 + Mathf.Min(lv / 10, 15)) + Mathf.Sqrt((float)lv);
        foreach (SourceElement.Row row in EClass.sources.elements.rows)
        {
            if ((!neg || !row.tag.Contains("flag")) && func(row) && row.LV < num2)
            {
                list.Add(row);
                num += row.chance;
            }
        }
        if (num == 0)
        {
            return null;
        }
        int num4 = EClass.rnd(num);
        int num5 = 0;
        foreach (SourceElement.Row row2 in list)
        {
            num5 += row2.chance;
            if (num4 < num5)
            {
                string category = EClass.sources.elements.map[row2.id].category;
                bool flag = category == "skill" || category == "attribute" || category == "resist";
                int item = (row2.mtp + EClass.rnd(row2.mtp + (int)num3)) / row2.mtp * ((flag && neg) ? -1 : 1);
                return new Tuple<SourceElement.Row, int>(row2, item);
            }
        }
        return null;
    }
References SourceManager.elements, neg, EClass.rnd(), EClass.rndSqrt(), and EClass.sources.
Referenced by AddEnchant(), OnCreate(), and TraitMod.OnCreate().
GetExtraName()
override string Thing.GetExtraName () inline virtual
Reimplemented from Card.
Definition at line 818 of file Thing.cs.
    {
        string text = "";
        if (this.trait.ShowChildrenNumber && base.c_lockLv == 0)
        {
            if (this.things.Count > 0)
            {
                text += "childCount".lang(this.things.Count.ToString() ?? "", null, null, null, null);
            }
            else if (this.trait.CanOpenContainer)
            {
                text += "empty".lang();
            }
        }
        if ((this.trait is TraitRoomPlate || this.trait is TraitHouseBoard) && this.pos.IsValid)
        {
            Room room = this.pos.cell.room;
            if (EClass.debug.enable && room != null && room.data.group != 0)
            {
                text = text + " #" + room.data.group.ToString();
            }
        }
        return text;
    }
References BaseArea.data, EClass.debug, CoreDebug.enable, AreaData.group, and text.
GetHoverText()
override string Thing.GetHoverText () inline virtual
Reimplemented from Card.
Definition at line 783 of file Thing.cs.
    {
        string text = "";
        text = text + " <size=14>(" + Lang._weight(base.ChildrenAndSelfWeight, true, 0) + ")</size> ";
        if (EClass.debug.showExtra)
        {
            text += Environment.NewLine;
            string[] array = new string[15];
            array[0] = text;
            array[1] = "id:";
            array[2] = this.id;
            array[3] = "  tile:";
            array[4] = this.source.idRenderData;
            array[5] = "/";
            int num = 6;
            object obj = (this.source.tiles.Length != 0) ? this.source.tiles[0] : "-";
            array[num] = ((obj != null) ? obj.ToString() : null);
            array[7] = " num:";
            array[8] = base.Num.ToString();
            array[9] = " lv:";
            array[10] = base.LV.ToString();
            array[11] = " enc:";
            array[12] = base.encLV.ToString();
            array[13] = " / ";
            array[14] = base.material.alias;
            text = string.Concat(array);
        }
        string hoverText = this.trait.GetHoverText();
        if (!hoverText.IsEmpty())
        {
            text = text + Environment.NewLine + hoverText;
        }
        return base.GetHoverText() + text;
    }
References EClass.debug, CoreDebug.showExtra, and text.
GetIngredients()
void Thing.GetIngredients (Recipe::Ingredient ing, List< Thing > list) inline
Definition at line 1766 of file Thing.cs.
    {
        if (ing.CanSetThing(this))
        {
            list.Add(this);
        }
        if (this.things.Count > 0 && base.c_lockLv == 0 && !base.isNPCProperty)
        {
            foreach (Thing thing in this.things)
            {
                thing.GetIngredients(ing, list);
            }
        }
    }
References GetIngredients().
Referenced by GetIngredients(), and LayerCraftFloat.ShowContextMenu().
GetName()
override string Thing.GetName (NameStyle style, int _num = -1) inline virtual
Reimplemented from Card.
Definition at line 479 of file Thing.cs.
    {
        int num = (_num == -1) ? base.Num : _num;
        string text = "";
        string text2 = "";
        string text3 = "";
        string str = "";
        string sig = "";
        string text4 = "";
        string text5 = this.source.GetText("unit", false);
        ArticleStyle style2 = (style == NameStyle.FullNoArticle) ? ArticleStyle.None : ArticleStyle.Default;
        bool flag = base.IsIdentified || this.source.unknown.IsEmpty();
        bool isEquipmentOrRanged = base.IsEquipmentOrRanged;
        bool flag2 = Lang.setting.nameStyle == 0;
        if (flag)
        {
            if (base.c_idRefCard.IsEmpty() && !base.c_altName.IsEmpty())
            {
                text = base.c_altName;
            }
            else
            {
                string[] array = this.trait.GetName().Split(',', StringSplitOptions.None);
                text = array[0];
                if (array.Length > 1)
                {
                    text5 = array[1];
                }
            }
            if (text.IsEmpty())
            {
                text = this.id;
            }
            if (isEquipmentOrRanged && base.IsIdentified && base.rarity >= Rarity.Legendary)
            {
                if (base.rarity != Rarity.Artifact && !base.material.GetTextArray("altName").IsEmpty())
                {
                    text = base.material.GetTextArray("altName")[0] + Lang.space + text;
                }
            }
            else
            {
                if (this.source.naming == "m" || (this.source.naming == "ms" && base.material != this.source.DefaultMaterial))
                {
                    if (isEquipmentOrRanged)
                    {
                        string[] textArray = base.material.GetTextArray("altName");
                        if (textArray != null && textArray.Length >= 2)
{
                            text = base.material.GetTextArray("altName")[1] + Lang.space + text;
                            goto IL_1F2;
                        }
                    }
                    text = "_of2".lang(base.material.GetName(), text, null, null, null);
                }
                IL_1F2:
                if (this.source.naming == "ma")
                {
                    text = base.material.GetName();
                }
                if (base.qualityTier > 0)
                {
                    text = Lang.GetList("quality_general")[Mathf.Clamp(base.qualityTier, 0, 3)] + text;
                }
            }
        }
        else
        {
            text = "unknown";
            string idUnknown = this.source.GetText("unknown", false);
            if (idUnknown.StartsWith("#"))
            {
                Rand.UseSeed(EClass.game.seed + (this.trait.CanStack ? this.sourceCard._index : base.uid) + base.refVal, delegate
                {
                    idUnknown = Lang.GetList(idUnknown.Remove(0, 1)).RandomItem<string>();
                });
            }
            text = idUnknown;
        }
        if (!base.c_idRefCard.IsEmpty() && this.trait.RefCardName != RefCardName.None)
        {
            string text6 = base.c_altName.IsEmpty(base.refCard.GetName());
            if (!base.c_idRefCard2.IsEmpty())
            {
                text6 = "_and".lang(text6, base.c_altName2.IsEmpty(base.refCard2.GetName()), null, null, null);
            }
            if (text6 == "*r")
            {
                string text7 = base.refCard.GetText("aka", false);
                if (!text7.IsEmpty())
                {
                    text = "_of".lang(text7, text, null, null, null);
                }
            }
            else if (!this.source.name2.IsEmpty())
            {
                text = this.source.GetTextArray("name2")[0].Replace("#1", text6);
            }
            else if (this.source.naming.Contains("last"))
            {
                text = text + Lang.space + text6;
            }
            else if (this.source.naming.Contains("first"))
            {
                text = text6 + Lang.space + text;
            }
            else if (this.source.naming.Contains("of"))
            {
                text = "_of".lang(text6, text, null, null, null);
            }
            else
            {
                text = (text5.IsEmpty() ? "_of3" : "_of2").lang(text6, text, null, null, null);
            }
        }
        if (base.c_bill != 0)
        {
            text = "_of".lang(Lang._currency(base.c_bill, true, 0), text, null, null, null);
        }
        this.trait.SetName(ref text);
        if (style == NameStyle.Simple)
        {
            return text;
        }
        if (style == NameStyle.Ref)
        {
            return text;
        }
        if (!base.c_refText.IsEmpty())
        {
            text = "_named".lang(base.c_refText, text, null, null, null);
        }
        if (base.IsIdentified)
        {
            int hit = base.HIT;
            int dmg = base.DMG;
            if ((base.IsMeleeWeapon || base.IsRangedWeapon || base.IsAmmo || hit != 0 || dmg != 0) && this.source.offense.Length != 0)
            {
                string text8 = "";
                if (this.source.offense[0] != 0)
                {
                    text8 = text8 + this.source.offense[0].ToString() + "d" + base.c_diceDim.ToString();
                }
                if (dmg != 0)
                {
                    text8 += ((base.IsMeleeWeapon || base.IsRangedWeapon || base.IsAmmo) ? dmg.ToText(true) : (dmg.ToString() ?? ""));
                }
                if (hit != 0)
                {
                    text8 = text8 + ((dmg != 0 || this.source.offense[0] != 0) ? ", " : "") + hit.ToString();
                }
                text2 = text2 + " (" + text8.IsEmpty(" - ") + ") ";
            }
            int dv = this.DV;
            int pv = this.PV;
            if (dv != 0 || pv != 0)
            {
                text2 += " [";
                text2 = text2 + dv.ToString() + ", " + pv.ToString();
                text2 += "] ";
            }
            if (this.trait.HasCharges && this.trait.ShowCharges)
            {
                text2 = text2 + " " + "itemCharges".lang(base.c_charges.ToString() ?? "", null, null, null, null);
            }
        }
        else if (base.c_IDTState == 3 || base.c_IDTState == 1)
        {
            text2 = "(" + base.TextRarity.ToTitleCase(false) + ")";
        }
        if (base.IsDecayed)
        {
            text = "rotten".lang() + text;
        }
        else if (base.IsRotting)
        {
            text = "rotting".lang() + text;
        }
        if (base.IsIdentified)
        {
            if (base.blessedState != BlessedState.Normal)
            {
                str = ("bs" + base.blessedState.ToString()).lang();
            }
            Rarity rarity = base.rarity;
            if (rarity - Rarity.Legendary > 1)
            {
                if (rarity == Rarity.Artifact)
                {
                    style2 = ArticleStyle.None;
                    text3 = "";
                    text = (isEquipmentOrRanged ? text.Bracket(3) : text);
                }
            }
            else
            {
                style2 = ArticleStyle.The;
                text3 = "";
                if (isEquipmentOrRanged)
                {
                    Rand.UseSeed(base.uid + EClass.game.seed, delegate
                    {
                        sig = AliasGen.GetRandomAlias().Bracket((this.rarity == Rarity.Mythical) ? 3 : 2);
                    });
                    sig = Lang.space + sig;
                }
            }
        }
        if (base.encLV != 0)
        {
            if (base.category.tag.Contains("enc"))
            {
                if (base.c_altName.IsEmpty())
                {
                    string[] list = Lang.GetList("quality_furniture");
                    text = "_qualityFurniture".lang(list[Mathf.Clamp(base.encLV - 1, 0, list.Length - 1)], text, null, null, null);
                }
            }
            else
            {
                sig = sig + Lang.space + ((base.encLV > 0) ? ("+" + base.encLV.ToString()) : (base.encLV.ToString() ?? ""));
            }
        }
        if (base.c_lockLv != 0 && base.c_revealLock)
        {
            sig = sig + Lang.space + "+" + base.c_lockLv.ToString();
        }
        if (base.isLostProperty)
        {
            text = "_lostproperty".lang(text, null, null, null, null);
        }
        if (this.trait is TraitEquipItem && EClass.player.eqBait == this && EClass.player.eqBait.GetRootCard() == EClass.pc)
        {
            text4 += "equippedItem".lang();
        }
        if (!base.c_note.IsEmpty() && (!base.isBackerContent || EClass.core.config.backer.Show(base.c_note)))
        {
            string text9 = base.c_note;
            if (text9.StartsWith('@'))
            {
                LangNote.Row row = Lang.Note.map.TryGetValue(text9.TrimStart('@'), null);
                text9 = (((row != null) ? row.GetText("text", false) : null) ?? base.c_note);
            }
            string text10 = base.category.IsChildOf("book") ? "_written" : "_engraved";
            if (this.id == "grave_dagger1" || this.id == "grave_dagger2")
            {
                text10 = "_daggerGrave";
            }
            if (text9.Contains("_bracketLeft".lang()))
            {
                text = (text10 + "Alt").lang(text9, text, null, null, null);
            }
            else
            {
                text = text10.lang(text9, text, null, null, null);
            }
        }
        if (flag2)
        {
            if (num > 1)
            {
                text = "_unit".lang(num.ToFormat() ?? "", str + text, text5, null, null);
            }
            else
            {
                text = str + text;
            }
        }
        else if (this.trait is TraitAbility)
        {
            text = text.ToTitleCase(true);
        }
        else if (text5.IsEmpty() || (!base.IsIdentified && !this.source.unknown.IsEmpty()))
        {
            text = (str + text).AddArticle(num, style2, this.source.name);
        }
        else
        {
            text = "_unit".lang((num == 1) ? "" : (num.ToFormat() ?? ""), text, (str + text5).AddArticle(num, style2, this.source.unit), null, null);
        }
        if (base.rarity >= Rarity.Legendary)
        {
            text = text.ToTitleCase(true);
        }
        string text11 = (base.isSale && this.things.Count > 0) ? "forSale2".lang() : ((base.isSale || (base.parentThing != null && base.parentThing.isSale && TraitSalesTag.CanTagSale(this, true))) ? "forSale".lang(Lang._currency(this.GetPrice(CurrencyType.Money, true, PriceType.PlayerShop, null), "money"), null, null, null, null) : "");
        if (this.trait is TraitSalesTag && base.isOn && !base.GetStr(11, null).IsEmpty())
        {
            text11 += "soldOut".lang(EClass.sources.categories.map[base.GetStr(11, null)].GetName(), null, null, null, null);
        }
        if (base.GetInt(101, null) != 0)
        {
            text4 = "_limitedStock".lang(text4, null, null, null, null);
        }
        return string.Concat(new string[]
        {
            text4,
            text3,
            text,
            sig,
            text2,
            text11
        });
    }
References Card.DV, EClass.game, Trait.GetName(), Trait.HasCharges, Card.id, Card.PV, Card.rarity, Game.seed, Trait.SetName(), source, text, and Card.trait.
Referenced by InvOwnerBlend._OnProcess(), WidgetPopText._SayPick(), Zone.g__SearchDest(), QuestDeliver.IsDestThing(), ThingContainer.RefreshGrid(), AI_OpenGambleChest.Run(), UIMagicChest.Search(), UIInventory.Sort(), ActThrow.Throw(), and Chara.TryUse().
GetRecipes()
void Thing.GetRecipes (HashSet< Recipe > recipes) inline
Definition at line 1786 of file Thing.cs.
    {
    }
Referenced by RecipeUpdater.RunRecipe().
GetSubPassData()
override SubPassData Thing.GetSubPassData () inline virtual
Reimplemented from Card.
Definition at line 1640 of file Thing.cs.
    {
        Chara chara = base.GetRootCard() as Chara;
        if ((this.trait.ShowAsTool && (chara != EClass.pc || !HotItemHeld.disableTool)) || (((chara != null) ? chara.held : null) != this && (this.placeState == PlaceState.installed || !this.renderer.data.subCrate.enable || !(this.parent is Zone))))
        {
            return SubPassData.Default;
        }
        if (!this.renderer.data.subCrate.enable)
        {
            return EClass.setting.pass.subCrate;
        }
        return this.renderer.data.subCrate;
    }
References SubPassData.Default, HotItemHeld.disableTool, Card.GetRootCard(), Chara.held, GameSetting.pass, EClass.pc, and EClass.setting.
Identify()
Thing Thing.Identify (bool show = true, IDTSource idtSource = IDTSource::Identify) inline
Definition at line 2028 of file Thing.cs.
    {
        if (base.IsIdentified)
        {
            return this;
        }
        string @ref = "";
        if (show)
        {
            @ref = this.GetName(NameStyle.Full, base.Num);
        }
        Rarity rarity = (idtSource == IDTSource.Skill) ? Rarity.Superior : ((idtSource == IDTSource.SkillHigh) ? Rarity.Legendary : Rarity.Normal);
        if (rarity != Rarity.Normal && ((base.IsEquipmentOrRanged && base.rarity >= rarity) || base.rarity >= Rarity.Mythical))
        {
            base.c_IDTState = 3;
        }
        else if (base.rarity >= Rarity.Mythical && idtSource != IDTSource.SuperiorIdentify)
        {
            base.c_IDTState = 1;
        }
        else
        {
            base.c_IDTState = 0;
        }
        if (show)
        {
            string name = this.GetName(NameStyle.Full, base.Num);
            if (base.c_IDTState == 0)
            {
                Msg.Say("identified", @ref, name, null, null);
            }
            else
            {
                Msg.Say((idtSource == IDTSource.Skill) ? "identified3" : "identified2", @ref, name, base.TextRarity, null);
            }
        }
        if (base.IsIdentified)
        {
            Card rootCard = base.GetRootCard();
            if (rootCard != null)
            {
                rootCard.TryStack(this);
            }
        }
        LayerInventory.SetDirty(this);
        return this;
    }
References Card.GetRootCard(), Msg.Say(), LayerInventory.SetDirty(), and Card.TryStack().
Referenced by RecipeCard.Craft(), TraitBaseSpellbook.OnRead(), TraitScrollStatic.OnRead(), AI_Read.OnSetOwner(), QuestDeliver.OnStart(), ActZap.Perform(), DramaOutcome.QuestExploration_AfterCrystal(), AI_UseCrafter.Run(), and Chara.TryIdentify().
IsValidIngredient()
bool Thing.IsValidIngredient (Recipe::Ingredient ing) inline
Definition at line 1781 of file Thing.cs.
    {
        return !this.isDestroyed && base.GetRootCard().Dist(EClass.pc) <= 1 && ing.CanSetThing(this);
    }
References EClass.pc.
ListLimitedValidTraits()
List< Element > Thing.ListLimitedValidTraits (bool limit) inline
Definition at line 843 of file Thing.cs.
    {
        List<Element> list = new List<Element>();
        if (base.ShowFoodEnc)
        {
            foreach (Element element in this.elements.dict.Values)
            {
                if (element.IsFoodTraitMain && element.Value > 0)
                {
                    list.Add(element);
                }
            }
            list.Sort((Element a, Element b) => ElementContainer.GetSortVal(b) - ElementContainer.GetSortVal(a));
            if (limit && list.Count > 5)
            {
                int num = list.Count - 5;
                for (int i = 0; i < num; i++)
                {
                    list.RemoveAt(list.Count - 1);
                }
            }
        }
        return list;
    }
References ElementContainer.GetSortVal(), Element.IsFoodTraitMain, and Element.Value.
ListValidTraits()
List< Element > Thing.ListValidTraits (bool isCraft, bool limit) inline
Definition at line 868 of file Thing.cs.
    {
        List<Element> list = this.ListLimitedValidTraits(limit);
        bool showFoodEnc = base.ShowFoodEnc;
        bool flag = EClass.pc.HasElement(1650, 1);
        if (showFoodEnc)
        {
            foreach (Element element in this.elements.dict.Values)
            {
                if (element.IsFoodTrait && !list.Contains(element) && (isCraft || flag || element.IsFoodTraitMain) && (!element.IsFoodTraitMain || element.Value < 0))
                {
                    list.Add(element);
                }
            }
        }
        foreach (Element element2 in this.elements.dict.Values)
        {
            if ((isCraft || flag || ((!element2.IsFoodTrait || element2.IsFoodTraitMain) && (!showFoodEnc || !element2.IsTrait || element2.Value >= 0))) && !list.Contains(element2) && (element2.IsTrait || (element2.IsFoodTrait && !element2.IsFoodTraitMain)))
            {
                list.Add(element2);
            }
        }
        return list;
    }
References Card.HasElement(), Element.IsFoodTrait, Element.IsFoodTraitMain, Element.IsTrait, EClass.pc, and Element.Value.
OnCreate()
override void Thing.OnCreate (int genLv) inline virtual
Reimplemented from Card.
Definition at line 152 of file Thing.cs.
    {
        if (this.bp.blesstedState != null)
        {
            this.SetBlessedState(this.bp.blesstedState.GetValueOrDefault());
        }
        else if (base.category.ignoreBless == 0 && this.bp.rarity == Rarity.Random && base.rarity != Rarity.Artifact)
        {
            if (EClass.rnd(25) == 0)
            {
                this.SetBlessedState(BlessedState.Blessed);
            }
            else if (EClass.rnd(25) == 0)
            {
                this.SetBlessedState(BlessedState.Cursed);
            }
            else if (EClass.rnd(50) == 0 && base.category.slot != 0)
            {
                this.SetBlessedState(BlessedState.Doomed);
            }
        }
        if (!EClass.debug.autoIdentify && (!this.source.unknown_JP.IsEmpty() || (base.category.slot != 0 && base.rarity >= Rarity.Superior)))
        {
            base.c_IDTState = 5;
        }
        string id = this.id;
        if (id == "bill_tax" || id == "bill")
        {
            base.c_bill = 100 + EClass.rnd(100);
        }
        if (base.category.slot != 0)
        {
            int num = 0;
            if (base.rarity == Rarity.Superior)
            {
                num = EClass.rnd(3);
            }
            else if (base.rarity == Rarity.Legendary)
            {
                num = EClass.rnd(4) + 2;
            }
            else if (base.rarity == Rarity.Mythical)
            {
                num = EClass.rnd(3) + 5;
            }
            else if (base.rarity >= Rarity.Artifact)
            {
                num = EClass.rnd(2) + 1;
            }
            if (num > 0 && !base.HasTag(CTAG.godArtifact))
            {
                for (int i = 0; i < num; i++)
                {
                    this.AddEnchant(genLv);
                }
            }
        }
        if (base.IsRangedWeapon && !this.IsMeleeWithAmmo)
        {
            if (base.HasTag(CTAG.godArtifact))
            {
                base.AddSocket();
                base.AddSocket();
            }
            else
            {
                int num2 = 1;
                int num3 = (EClass.rnd(10) == 0) ? 1 : 0;
                if (base.rarity == Rarity.Superior)
                {
                    num2 = 2 + num3;
                }
                else if (base.rarity == Rarity.Legendary)
                {
                    num2 = EClass.rnd(2) + 3 + num3;
                }
                else if (base.rarity == Rarity.Mythical)
                {
                    num2 = EClass.rnd(2) + 4 + num3;
                }
                else if (base.rarity >= Rarity.Artifact)
                {
                    num2 = EClass.rnd(2) + 1;
                }
                if (num2 > 0)
                {
                    for (int j = 0; j < num2; j++)
                    {
                        base.AddSocket();
                    }
                    for (int k = 0; k < EClass.rnd(num2 + 1); k++)
                    {
                        Tuple<SourceElement.Row, int> enchant = Thing.GetEnchant(genLv, (SourceElement.Row r) => r.tag.Contains("modRanged"), false);
                        if (enchant != null && InvOwnerMod.IsValidMod(this, enchant.Item1))
{
                            base.ApplySocket(enchant.Item1.id, enchant.Item2, null);
                        }
                    }
                }
            }
        }
        if ((this.bp.rarity != Rarity.Normal || this.bp.qualityBonus != 0) && base.rarity < Rarity.Artifact && base.category.tag.Contains("enc"))
        {
            int num4 = 0;
            if (EClass.rnd(6) == 0)
            {
                if (this.bp.qualityBonus == 0)
                {
                    num4 = EClass.rnd(EClass.rnd(11) + 1);
                    if (num4 == 1 && EClass.rnd(3) != 0)
                    {
                        num4 = 0;
                    }
                }
                else if (this.bp.qualityBonus < 0)
                {
                    if (EClass.rnd(3) == 0)
                    {
                        num4 = 1;
                    }
                }
                else if (this.bp.qualityBonus >= 10)
                {
                    num4 = Mathf.Min(this.bp.qualityBonus / 10 + 2, 7) + EClass.rnd(EClass.rnd(5) + 1);
                }
            }
            if (num4 > 0)
            {
                base.SetEncLv(Mathf.Min(num4, 12));
            }
        }
        if (base.HasTag(CTAG.randomSkin))
        {
            base.idSkin = EClass.rnd(this.source.skins.Length + 1);
        }
    }
References AddEnchant(), CoreDebug.autoIdentify, CardBlueprint.blesstedState, Card.bp, EClass.debug, GetEnchant(), InvOwnerMod.IsValidMod(), CardBlueprint.qualityBonus, CardBlueprint.rarity, EClass.rnd(), Card.SetBlessedState(), and source.
RemoveEnchant()
void Thing.RemoveEnchant () inline
Definition at line 2024 of file Thing.cs.
    {
    }
SetRenderParam()
override void Thing.SetRenderParam (RenderParam p) inline virtual
Reimplemented from Card.
Definition at line 1534 of file Thing.cs.
    {
        p.matColor = (float)base.colorInt;
        p.mat = base.material;
        if (!this.renderer.usePass)
        {
            return;
        }
        switch (this.trait.tileMode)
        {
        case Trait.TileMode.Default:
            if (this.source._altTiles.Length != 0 && this.trait.UseAltTiles)
            {
                p.tile = (float)(this.source._altTiles[base.dir % this.source._altTiles.Length] * (this.flipX ? -1 : 1));
            }
            else
            {
                p.tile = (float)(this.sourceCard._tiles[base.dir % this.sourceCard._tiles.Length] * (this.flipX ? -1 : 1));
            }
            if (this.source.anime.Length != 0 && this.trait.IsAnimeOn)
            {
                if (this.source.anime.Length > 2)
                {
                    float num = Time.realtimeSinceStartup * 1000f / (float)this.source.anime[1] % (float)this.source.anime[2];
                    if ((int)num == this.source.anime[0] - 1 && this.source.anime.Length > 3)
                    {
                        base.PlaySound("anime_sound" + this.source.anime[3].ToString(), 1f, true);
                    }
                    if (num < (float)this.source.anime[0])
                    {
                        p.tile += num * (float)(this.flipX ? -1 : 1);
                    }
                }
                else
                {
                    float num2 = Time.realtimeSinceStartup * 1000f / (float)this.source.anime[1] % (float)this.source.anime[0];
                    p.tile += num2 * (float)(this.flipX ? -1 : 1);
                }
            }
            break;
        case Trait.TileMode.Door:
        {
            if (this.source._altTiles.Length != 0 && this.trait.UseAltTiles)
            {
                p.tile = (float)(this.source._altTiles[base.dir % this.source._altTiles.Length] * (this.flipX ? -1 : 1));
            }
            else
            {
                p.tile = (float)(this.sourceCard._tiles[base.dir % this.sourceCard._tiles.Length] * (this.flipX ? -1 : 1));
            }
            if (this.parent is Zone && this.pos.cell.HasFullBlock)
            {
                p.tile += (float)((p.tile < 0f) ? -64 : 64);
            }
            TraitDoorSwing traitDoorSwing = this.trait as TraitDoorSwing;
            if (traitDoorSwing != null && traitDoorSwing.IsOpen())
            {
                p.tile += (float)((p.tile < 0f) ? -1 : 1);
            }
            break;
        }
        case Trait.TileMode.Illumination:
            if (base.isOn || base.isRoofItem)
            {
                int num3 = (int)((float)base.uid + Time.realtimeSinceStartup * 5f);
                int num4 = (int)(Time.realtimeSinceStartup * 5f);
                p.tile = (float)((this.sourceCard._tiles[base.dir % this.sourceCard._tiles.Length] + num3 % 3 + 1) * (this.flipX ? -1 : 1));
                if (num4 % 16 == 0)
                {
                    p.color = 5242880f;
                }
                else if (num4 % 11 == 0)
                {
                    p.color = 7864320f;
                }
                else
                {
                    p.color = 13107200f;
                }
            }
            else
            {
                p.tile = (float)(this.sourceCard._tiles[base.dir % this.sourceCard._tiles.Length] * (this.flipX ? -1 : 1));
            }
            break;
        case Trait.TileMode.DefaultNoAnime:
            if (this.source._altTiles.Length != 0 && this.trait.UseAltTiles)
            {
                p.tile = (float)(this.source._altTiles[base.dir % this.source._altTiles.Length] * (this.flipX ? -1 : 1));
            }
            else
            {
                p.tile = (float)(this.sourceCard._tiles[base.dir % this.sourceCard._tiles.Length] * (this.flipX ? -1 : 1));
            }
            break;
        }
        if (base.idSkin != 0)
        {
            int num5 = base.idSkin - 1;
            if (this.sourceCard.skins.Length != 0)
            {
                p.tile += (float)((p.tile < 0f) ? (-(float)this.sourceCard.skins[num5]) : this.sourceCard.skins[num5]);
            }
        }
    }
References TraitDoorSwing.IsOpen(), RenderParam.mat, and MeshPassParam.tile.
Referenced by BaseTileMap.DrawTile(), TileMapElona.DrawTile(), and CharaActorPCC.OnRender().
SetSource()
override void Thing.SetSource () inline virtual
Reimplemented from Card.
Definition at line 136 of file Thing.cs.
    {
        this.source = EClass.sources.things.map.TryGetValue(this.id, null);
        if (this.source != null && this.source.isOrigin)
        {
            this.source = (EClass.sources.cards.firstVariations[this.id] as SourceThing.Row);
            this.id = this.source.id;
        }
        if (this.source == null)
        {
            Debug.LogWarning("Thing " + this.id + " not found");
            this.id = "1101";
            this.source = EClass.sources.things.map[this.id];
        }
    }
References SourceManager.cards, SourceCard.firstVariations, Card.id, source, EClass.sources, and SourceManager.things.
ShowSplitMenu()
void Thing.ShowSplitMenu (ButtonGrid button, InvOwner::Transaction trans = null) inline
Definition at line 1798 of file Thing.cs.
    {
        Thing.<>c__DisplayClass43_0 CS$<>8__locals1 = new Thing.<>c__DisplayClass43_0();
        CS$<>8__locals1.<>4__this = this;
        CS$<>8__locals1.trans = trans;
        CS$<>8__locals1.button = button;
        CS$<>8__locals1.count = 1;
        CS$<>8__locals1.m = EClass.ui.CreateContextMenuInteraction();
        CS$<>8__locals1.buy = (CS$<>8__locals1.trans != null);
        CS$<>8__locals1.buttonBuy = null;
        CS$<>8__locals1.itemSlider = null;
        CS$<>8__locals1.itemSlider = CS$<>8__locals1.m.AddSlider("sliderSplitMenu", "adjustmentNum", delegate(float a)
        {
            if (!EClass.core.IsGameStarted)
            {
                return "";
            }
            return "/" + CS$<>8__locals1.<>4__this.Num.ToString();
        }, (float)CS$<>8__locals1.count, delegate(float b)
        {
            CS$<>8__locals1.count = (int)b;
            if (CS$<>8__locals1.trans != null)
            {
                CS$<>8__locals1.trans.num = CS$<>8__locals1.count;
            }
            base.<ShowSplitMenu>g__UpdateButton|0();
        }, 1f, (float)base.Num, true, false, true).GetComponent<UIItem>();
        if (CS$<>8__locals1.buy)
        {
            CS$<>8__locals1.buttonBuy = CS$<>8__locals1.m.AddButton("invBuy", delegate()
            {
                base.<ShowSplitMenu>g__Process|1();
            }, true);
        }
        CS$<>8__locals1.m.onDestroy = delegate()
        {
            if (!CS$<>8__locals1.buy && !CS$<>8__locals1.m.wasCanceled)
            {
                base.<ShowSplitMenu>g__Process|1();
            }
        };
        CS$<>8__locals1.m.Show();
        if (CS$<>8__locals1.buttonBuy)
        {
            CS$<>8__locals1.buttonBuy.gameObject.AddComponent<CanvasGroup>();
        }
        CS$<>8__locals1.<ShowSplitMenu>g__UpdateButton|0();
    }
References EClass.core, and EClass.ui.
Referenced by InvOwner.ListInteractions(), and InvOwner.OnCtrlClick().
ShowSplitMenu2()
void Thing.ShowSplitMenu2 (ButtonGrid button, string lang, Action< int > onSplit = null) inline
Definition at line 1847 of file Thing.cs.
    {
        Thing.<>c__DisplayClass44_0 CS$<>8__locals1 = new Thing.<>c__DisplayClass44_0();
        CS$<>8__locals1.<>4__this = this;
        CS$<>8__locals1.lang = lang;
        CS$<>8__locals1.button = button;
        CS$<>8__locals1.onSplit = onSplit;
        CS$<>8__locals1.count = 1;
        UIContextMenu uicontextMenu = EClass.ui.CreateContextMenuInteraction();
        CS$<>8__locals1.buttonBuy = null;
        CS$<>8__locals1.itemSlider = null;
        CS$<>8__locals1.itemSlider = uicontextMenu.AddSlider("sliderSplitMenu", "adjustmentNum", delegate(float a)
        {
            if (!EClass.core.IsGameStarted)
            {
                return "";
            }
            return "/" + CS$<>8__locals1.<>4__this.Num.ToString();
        }, (float)CS$<>8__locals1.count, delegate(float b)
        {
            CS$<>8__locals1.count = (int)b;
            base.<ShowSplitMenu2>g__UpdateButton|0();
        }, 1f, (float)base.Num, true, false, true).GetComponent<UIItem>();
        CS$<>8__locals1.buttonBuy = uicontextMenu.AddButton("invBuy", delegate()
        {
            base.<ShowSplitMenu2>g__Process|1();
        }, true);
        uicontextMenu.onDestroy = delegate()
        {
        };
        uicontextMenu.Show();
        if (CS$<>8__locals1.buttonBuy)
        {
            CS$<>8__locals1.buttonBuy.gameObject.AddComponent<CanvasGroup>();
        }
        CS$<>8__locals1.<ShowSplitMenu2>g__UpdateButton|0();
    }
References EClass.core, and EClass.ui.
Referenced by UIDragGridIngredients.Update().
TryLickEnchant()
void Thing.TryLickEnchant (Chara c, bool msg = true, Chara tg = null, BodySlot slot = null) inline
Definition at line 1958 of file Thing.cs.
    {
        if (!base.IsEquipmentOrRanged)
        {
            return;
        }
        if (base.IsCursed || base.rarity <= Rarity.Normal)
        {
            return;
        }
        if (base.GetInt(107, null) > 0)
        {
            return;
        }
        if (tg == null)
        {
            Rand.SetSeed(EClass.world.date.day + this.source._index + c.uid);
            if (msg)
            {
                c.Say("lick", c, this, null, null);
                base.PlaySound("offering", 1f, true);
                base.PlayEffect("mutation", true, 0f, default(Vector3));
            }
            this.AddEnchant(base.LV);
        }
        else
        {
            Rand.SetSeed(base.uid);
            List<Element> list = new List<Element>();
            foreach (Element element in this.elements.dict.Values)
            {
                if (element.id != 67 && element.id != 66 && element.id != 64 && element.id != 65)
                {
                    list.Add(element);
                }
            }
            if (list.Count > 0)
            {
                Element element2 = list.RandomItem<Element>();
                this.elements.ModBase(element2.id, Mathf.Max(EClass.rnd(Mathf.Abs(element2.vBase / 5)), 1));
            }
            if (msg)
            {
                c.Say("lick2", c, tg, slot.name.ToLower(), null);
                tg.PlaySound("offering", 1f, true);
                tg.PlayEffect("mutation", true, 0f, default(Vector3));
            }
        }
        Rand.SetSeed(-1);
        base.SetInt(107, 1);
    }
References World.date, Date.day, Element.id, EClass.rnd(), Card.Say(), Card.uid, Element.vBase, and EClass.world.
Referenced by ThingGen.TryLickChest().
WriteNote()
override void Thing.WriteNote (UINote n, Action< UINote > onWriteNote = null, IInspect::NoteMode mode = IInspect::NoteMode::Default, Recipe recipe = null) inline virtual
Reimplemented from Card.
Definition at line 893 of file Thing.cs.
    {
        i.Clear();
        TraitAbility traitAbility = this.trait as TraitAbility;
        bool showEQStats = base.IsEquipmentOrRanged || base.IsAmmo;
        bool flag = mode == IInspect.NoteMode.Product;
        bool flag2 = base.IsIdentified || flag;
        string text = base.Name;
        if (base.rarity == Rarity.Legendary || base.rarity == Rarity.Mythical)
        {
            string text2 = text.Contains("") ? "" : (text.Contains("") ? "" : "");
            if (text2 != "")
            {
                string[] array = text.Split(text2, StringSplitOptions.None);
                text = array[0] + Environment.NewLine + text2 + array[1];
            }
        }
        if (flag)
        {
            text = recipe.GetName();
        }
        if (mode != IInspect.NoteMode.Recipe)
        {
            UIItem uiitem = i.AddHeaderCard(text, null);
            this.SetImage(uiitem.image2);
            uiitem.image2.Rect().pivot = new Vector2(0.5f, 0.5f);
            string text3 = base.Num.ToFormat() ?? "";
            string text4 = (Mathf.Ceil(0.01f * (float)base.ChildrenAndSelfWeight) * 0.1f).ToString("F1") + "s";
            if (this.things.Count > 0)
            {
                text3 = text3 + " (" + this.things.Count.ToString() + ")";
            }
            if (base.ChildrenAndSelfWeight != this.SelfWeight)
            {
                text4 = text4 + " (" + (Mathf.Ceil(0.01f * (float)this.SelfWeight) * 0.1f).ToString("F1") + "s)";
            }
            text = "_quantity".lang(text3 ?? "", text4, null, null, null);
            if (flag && recipe != null && LayerCraft.Instance)
            {
                text = text + "  " + "_recipe_lv".lang(recipe.RecipeLv.ToString() ?? "", null, null, null, null);
            }
            uiitem.text2.SetText(text);
            if (showEQStats && flag2)
            {
                if (!flag)
                {
                    text = "";
                    if (this.DV != 0 || this.PV != 0 || base.HIT != 0 || base.DMG != 0 || this.Penetration != 0)
                    {
                        if (base.DMG != 0)
{
                            text = string.Concat(new string[]
{
                                text,
                                "DMG".lang(),
                                (base.DMG > 0) ? "+" : "",
                                base.DMG.ToString(),
                                ", "
                            });
                        }
                        if (base.HIT != 0)
{
                            text = string.Concat(new string[]
{
                                text,
                                "HIT".lang(),
                                (base.HIT > 0) ? "+" : "",
                                base.HIT.ToString(),
                                ", "
                            });
                        }
                        if (this.DV != 0)
{
                            text = string.Concat(new string[]
{
                                text,
                                "DV".lang(),
                                (this.DV > 0) ? "+" : "",
                                this.DV.ToString(),
                                ", "
                            });
                        }
                        if (this.PV != 0)
{
                            text = string.Concat(new string[]
{
                                text,
                                "PV".lang(),
                                (this.PV > 0) ? "+" : "",
                                this.PV.ToString(),
                                ", "
                            });
                        }
                        if (this.Penetration != 0)
{
                            text = string.Concat(new string[]
{
                                text,
                                "PEN".lang(),
                                (this.Penetration > 0) ? "+" : "",
                                this.Penetration.ToString(),
                                "%, "
                            });
                        }
                        text = text.TrimEnd(' ').TrimEnd(',');
                    }
                    if (!text.IsEmpty())
                    {
                        i.AddText("NoteText_eqstats", text, FontColor.DontChange);
                    }
                }
                TraitToolRange traitToolRange = this.trait as TraitToolRange;
                if (traitToolRange != null)
                {
                    i.AddText("NoteText_eqstats", "tip_range".lang(traitToolRange.BestDist.ToString() ?? "", null, null, null, null), FontColor.DontChange);
                }
            }
            else
            {
                string text5 = "";
                if (EClass.debug.showExtra)
                {
                    int totalQuality = base.GetTotalQuality(true);
                    int totalQuality2 = base.GetTotalQuality(false);
                    text5 = string.Concat(new string[]
                    {
                        text5,
                        "Lv. ",
                        base.LV.ToString(),
                        " TQ. ",
                        base.GetTotalQuality(true).ToString(),
                        (totalQuality == totalQuality2) ? "" : (" (" + totalQuality2.ToString() + ")")
                    });
                }
                if (base.HasElement(10, 1))
                {
                    text5 = text5 + (text5.IsEmpty() ? "" : "  ") + "_nutrition".lang(base.Evalue(10).ToFormat() ?? "", null, null, null, null);
                }
                if ((base.category.IsChildOf("resource") || this.trait.IsTool) && !(this.trait is TraitAbility))
                {
                    text5 = text5 + (text5.IsEmpty() ? "" : "  ") + "_hardness".lang(base.material.hardness.ToString() ?? "", null, null, null, null);
                }
                if (flag && recipe != null && LayerCraft.Instance)
                {
                    text5 = text5 + (text5.IsEmpty() ? "" : "  ") + "_max_quality".lang(recipe.GetQualityBonus().ToString() ?? "", null, null, null, null);
                }
                if (!text5.IsEmpty())
                {
                    i.AddText("NoteText_eqstats", text5, FontColor.DontChange);
                }
            }
            string detail = this.GetDetail();
            if (!detail.IsEmpty())
            {
                LayoutElement component = i.AddText("NoteText_flavor", detail, FontColor.DontChange).GetComponent<LayoutElement>();
                if (flag)
                {
                    component.preferredWidth = 400f;
                }
                i.Space(8, 1);
            }
        }
        if (this.trait is TraitBookPlan)
        {
            TraitBookPlan traitBookPlan = this.trait as TraitBookPlan;
            i.AddText("NoteText_flavor", traitBookPlan.source.GetDetail(), FontColor.DontChange);
            i.Space(8, 1);
        }
        if (traitAbility != null)
        {
            i.Space(8, 1);
            Act act = traitAbility.CreateAct();
            Element orCreateElement = EClass.pc.elements.GetOrCreateElement(act.source.id);
            orCreateElement._WriteNote(i, EClass.pc.elements, null, false, false);
            orCreateElement._WriteNote(i, EClass.pc, act);
            return;
        }
        if (EClass.debug.showExtra)
        {
            string[] array2 = new string[8];
            array2[0] = "(id:";
            array2[1] = this.id;
            array2[2] = " tile:";
            int num = 3;
            string text6 = this.source.tiles.IsEmpty() ? "-" : this.source.tiles[0];
            array2[num] = ((text6 != null) ? text6.ToString() : null);
            array2[4] = ") lv:";
            array2[5] = base.LV.ToString();
            array2[6] = " price:";
            array2[7] = this.GetPrice(CurrencyType.Money, false, PriceType.Default, null).ToString();
            i.AddText(string.Concat(array2), FontColor.DontChange);
        }
        Card rootCard = base.GetRootCard();
        if (rootCard != null && rootCard != EClass.pc && rootCard != this && rootCard.ExistsOnMap)
        {
            Thing thing = this.parent as Thing;
            if (!(((thing != null) ? thing.trait : null) is TraitChestMerchant))
            {
                i.AddText("isChildOf".lang(base.GetRootCard().Name, null, null, null, null), FontColor.ItemName);
            }
        }
        if (flag2)
        {
            i.AddText("isMadeOf".lang(base.material.GetText("name", false), base.material.hardness.ToString() ?? "", null, null, null), FontColor.DontChange);
        }
        i.AddText("isCategorized".lang(base.category.GetText("name", false), null, null, null, null), FontColor.DontChange);
        if (base.category.skill != 0)
        {
            int key = base.category.skill;
            int key2 = 132;
            if (base.IsRangedWeapon)
            {
                key2 = 133;
            }
            if (this.trait is TraitToolRangeCane)
            {
                key2 = 304;
            }
            if (base.Evalue(482) > 0)
            {
                key = 305;
                key2 = 304;
            }
            i.AddText("isUseSkill".lang(EClass.sources.elements.map[key].GetName().ToTitleCase(true), EClass.sources.elements.map[key2].GetName().ToTitleCase(true), null, null, null), FontColor.DontChange);
        }
        if (base.IsContainer)
        {
            i.AddText("isContainer".lang(this.things.MaxCapacity.ToString() ?? "", null, null, null, null), FontColor.DontChange);
        }
        if (base.c_lockLv != 0)
        {
            i.AddText((base.c_lockedHard ? "isLockedHard" : "isLocked").lang(base.c_lockLv.ToString() ?? "", null, null, null, null), FontColor.Warning);
        }
        if (base.isCrafted && recipe == null)
        {
            i.AddText("isCrafted".lang(), FontColor.DontChange);
        }
        if (this.trait.Decay > 0)
        {
            string s2;
            if (base.IsDecayed)
            {
                s2 = "isRotten";
            }
            else if (base.IsRotting)
            {
                s2 = "isRotting";
            }
            else if (base.IsFresn)
            {
                s2 = "isFresh";
            }
            else
            {
                s2 = "isNotFresh";
            }
            i.AddText(s2.lang(), FontColor.DontChange);
        }
        if (base.isDyed)
        {
            i.AddText("isDyed".lang(), FontColor.DontChange);
        }
        if (base.IsEquipment)
        {
            text = "isEquipable".lang(Element.Get(base.category.slot).GetText("name", false), null, null, null, null);
            i.AddText(text, FontColor.DontChange);
        }
        if (base.isFireproof)
        {
            i.AddText("isFreproof", FontColor.DontChange);
        }
        if (base.isAcidproof)
        {
            i.AddText("isAcidproof", FontColor.DontChange);
        }
        if (this.trait.Electricity > 0)
        {
            i.AddText("isGenerateElectricity".lang(this.trait.Electricity.ToString() ?? "", null, null, null, null), FontColor.DontChange);
        }
        if (this.trait.Electricity < 0)
        {
            i.AddText("isConsumeElectricity".lang(Mathf.Abs(this.trait.Electricity).ToString() ?? "", null, null, null, null), FontColor.DontChange);
        }
        if (base.IsUnique)
        {
            i.AddText("isPrecious", FontColor.DontChange);
        }
        if (base.isCopy)
        {
            i.AddText("isCopy", FontColor.DontChange);
        }
        if (!this.trait.CanBeDestroyed)
        {
            i.AddText("isIndestructable", FontColor.DontChange);
        }
        if (base.GetInt(107, null) > 0)
        {
            i.AddText("isLicked", FontColor.DontChange);
        }
        if (!base.c_idDeity.IsEmpty())
        {
            Religion religion = EClass.game.religions.Find(base.c_idDeity) ?? EClass.game.religions.Eyth;
            i.AddText("isDeity".lang(religion.Name, null, null, null, null), FontColor.Myth);
        }
        if (base.isGifted && base.GetRoot() != EClass.pc)
        {
            i.AddText("isGifted", FontColor.Ether);
        }
        if (base.isNPCProperty)
        {
            i.AddText("isNPCProperty", FontColor.Ether);
        }
        if (base.c_priceFix != 0)
        {
            i.AddText(((base.c_priceFix > 0) ? "isPriceUp" : "isPriceDown").lang(Mathf.Abs(base.c_priceFix).ToString() ?? "", null, null, null, null), FontColor.Ether);
        }
        if (base.noSell)
        {
            i.AddText("isNoSell", FontColor.Ether);
        }
        if (base.isStolen)
        {
            i.AddText("isStolen", FontColor.Ether);
        }
        if (base.c_isImportant)
        {
            i.AddText("isMarkedImportant", FontColor.Ether);
        }
        if (base.GetInt(25, null) != 0)
        {
            i.AddText("isDangerLv".lang((base.GetInt(25, null) + 1).ToString() ?? "", (EClass.pc.FameLv + 10).ToString() ?? "", null, null, null), FontColor.DontChange);
        }
        FontColor color = FontColor.Util;
        if (this.trait is TraitTool && !(this.trait is TraitToolRange))
        {
            if (base.HasElement(220, 1))
            {
                i.AddText("canMine".lang(), color);
            }
            if (base.HasElement(225, 1))
            {
                i.AddText("canLumberjack".lang(), color);
                i.AddText("canLumberjack2".lang(), color);
            }
            if (base.HasElement(230, 1))
            {
                i.AddText("canDig", color);
            }
            if (base.HasElement(286, 1))
            {
                i.AddText("canFarm", color);
            }
            if (base.HasElement(245, 1))
            {
                i.AddText("canFish", color);
            }
            if (base.HasElement(237, 1))
            {
                i.AddText("canTame", color);
            }
        }
        if (this.trait is TraitToolMusic)
        {
            i.AddText("canPlayMusic".lang(), color);
        }
        if (Lang.Has("hint_" + this.trait.ToString()))
        {
            i.AddText("hint_" + this.trait.ToString(), FontColor.Util);
        }
        if (Lang.Has("hint_" + this.trait.ToString() + "2"))
        {
            i.AddText("hint_" + this.trait.ToString() + "2", FontColor.Util);
        }
        if (base.HasTag(CTAG.tourism))
        {
            i.AddText("isTourism", FontColor.Util);
        }
        string langPlaceType = base.TileType.LangPlaceType;
        if (langPlaceType == "place_Door" || langPlaceType == "place_WallMount")
        {
            i.AddText(base.TileType.LangPlaceType + "_hint".lang(), FontColor.Util);
        }
        if (this.trait.IsHomeItem)
        {
            i.AddText("isHomeItem".lang(), FontColor.Util);
        }
        if (base.HasTag(CTAG.throwWeapon))
        {
            i.AddText("isThrowWeapon", FontColor.DontChange);
        }
        if (EClass.debug.showExtra && base.HasTag(CTAG.throwWeaponEnemy))
        {
            i.AddText("isThrowWeaponEnemy", FontColor.DontChange);
        }
        if (base.HasElement(10, 1))
        {
            i.AddText("isEdible", FontColor.DontChange);
        }
        if (base.HasTag(CTAG.rareResource))
        {
            i.AddText("isRareResource", FontColor.Great);
        }
        TraitBed traitBed = this.trait as TraitBed;
        if (traitBed != null)
        {
            i.AddText("isBed".lang(traitBed.MaxHolders.ToString() ?? "", null, null, null, null), FontColor.DontChange);
        }
        bool flag3 = base.IsEquipmentOrRanged || base.IsAmmo || base.IsThrownWeapon;
        if (flag2)
        {
            if (flag3)
            {
                Element element = this.elements.GetElement(653);
                if (element != null)
                {
                    i.AddText("isAlive".lang(element.vBase.ToString() ?? "", (element.vExp / 10).ToString() ?? "", (element.ExpToNext / 10).ToString() ?? "", null, null), FontColor.Great);
                }
                string[] rangedSubCats = new string[]
                {
                    "eleConvert",
                    "eleAttack"
                };
                this.elements.AddNote(i, (Element e) => (!(this.trait is TraitToolRange) || this.category.slot != 0 || e is Ability || rangedSubCats.Contains(e.source.categorySub) || e.HasTag("modRanged")) && !e.IsTrait && (!(e.source.categorySub == "eleAttack") || this.IsWeapon || this.IsRangedWeapon || this.IsAmmo || this.IsThrownWeapon) && (!showEQStats || (e.id != 64 && e.id != 65 && e.id != 66 && e.id != 67)), null, ElementContainer.NoteMode.Default, false, null, null);
            }
            if (this.sockets == null)
            {
                goto IL_11FC;
            }
            using (List<int>.Enumerator enumerator = this.sockets.GetEnumerator())
            {
                while (enumerator.MoveNext())
                {
                    int num2 = enumerator.Current;
                    i.AddText((num2 == 0) ? "emptySocket".lang() : "socket".lang(EClass.sources.elements.map[num2 / 100].GetName(), (num2 % 100).ToString() ?? "", null, null, null), FontColor.Gray);
                }
                goto IL_11FC;
            }
        }
        i.AddText("isUnidentified".lang(), FontColor.Flavor);
        if (base.c_IDTState == 1)
        {
            i.AddText("isUnidentified2".lang(), FontColor.Flavor);
        }
        IL_11FC:
        this.trait.WriteNote(i, flag2);
        if (flag2 && !flag3)
        {
            bool infoMode = mode == IInspect.NoteMode.Info;
            List<Element> list = this.ListValidTraits(false, !infoMode);
            List<Element> list2 = this.ListValidTraits(false, false);
            if (list2.Count - list.Count <= 1)
            {
                list = list2;
            }
            this.elements.AddNote(i, (Element e) => list.Contains(e), null, ElementContainer.NoteMode.Trait, false, delegate(Element e, string s)
            {
                string text8 = s;
                string text9 = e.source.GetText("textExtra", false);
                if (!text9.IsEmpty())
                {
                    string text10 = "";
                    if (e.id == 2 && mode == IInspect.NoteMode.Product)
                    {
                        int num3 = recipe.GetQualityBonus() / 10;
                        if (num3 >= 0)
{
                            num3++;
                        }
                        text10 = "qualityLimit".lang(num3.ToString() ?? "", null, null, null, null);
                    }
                    int num4 = e.Value / 10;
                    if (e.Value >= 0)
                    {
                        num4++;
                    }
                    else
                    {
                        num4--;
                    }
                    text9 = string.Concat(new string[]
                    {
                        "Lv.",
                        num4.ToString(),
                        text10,
                        " ",
                        text9
                    });
                    if (infoMode && e.IsFoodTraitMain)
                    {
                        text9 += "traitAdditive".lang();
                    }
                    text8 += (" <size=12>" + text9 + "</size>").TagColor(FontColor.Passive, null);
                }
                return text8;
            }, delegate(UINote n, Element e)
            {
            });
            if (base.ShowFoodEnc && EClass.pc.HasElement(1650, 1))
            {
                if (FoodEffect.IsHumanFlesh(this))
                {
                    i.AddText("foodHuman".lang(), FontColor.Ether);
                }
                if (FoodEffect.IsUndeadFlesh(this))
                {
                    i.AddText("foodUndead".lang(), FontColor.Ether);
                }
            }
            if (list.Count != list2.Count)
            {
                i.AddText("traitOther".lang((list2.Count - list.Count).ToString() ?? "", null, null, null, null), FontColor.DontChange);
            }
            if (mode == IInspect.NoteMode.Product && base.HasTag(CTAG.dish_bonus))
            {
                i.AddHeader("HeaderAdditionalTrait", "additional_trait", null);
                this.source.model.elements.AddNote(i, (Element e) => e.IsFoodTraitMain, null, ElementContainer.NoteMode.Trait, false, delegate(Element e, string s)
                {
                    string text8 = s;
                    string text9 = e.source.GetText("textExtra", false);
                    if (!text9.IsEmpty())
                    {
                        string text10 = "";
                        int num3 = e.Value / 10;
                        if (e.Value >= 0)
{
                            num3++;
                        }
                        else
{
                            num3--;
                        }
                        text9 = string.Concat(new string[]
{
                            "Lv.",
                            num3.ToString(),
                            text10,
                            " ",
                            text9
                        });
                        if (infoMode && e.IsFoodTraitMain)
{
                            text9 += "traitAdditive".lang();
                        }
                        text8 += (" <size=12>" + text9 + "</size>").TagColor(FontColor.Passive, null);
                    }
                    return text8;
                }, null);
            }
        }
        if (EClass.debug.showExtra)
        {
            i.AddText("decay:" + base.decay.ToString(), FontColor.DontChange);
        }
        if (this.id == "statue_weird")
        {
            i.AddText("weirdStatue", FontColor.DontChange);
        }
        if (base.isReplica)
        {
            i.AddText("isReplica", FontColor.Passive);
        }
        if (flag2)
        {
            Chara chara = base.GetRootCard() as Chara;
            Card parentCard = base.parentCard;
            if (((parentCard != null) ? parentCard.trait : null) is TraitChestMerchant)
            {
                chara = null;
            }
            if (base.c_equippedSlot != 0 && base.category.slot == 35 && chara != null)
            {
                Thing.AddAttackEvaluation(i, chara, this);
            }
            if (base.IsThrownWeapon || base.IsRangedWeapon || (base.IsMeleeWeapon && base.c_equippedSlot == 0))
            {
                i.AddHeader("headerAttackEval", null);
                AttackProcess.Current.Prepare(chara ?? EClass.pc, this, null, null, 0, base.IsThrownWeapon);
                string text7 = AttackProcess.Current.GetText();
                text7 = text7.TagColor(() => true, null);
                i.AddText(text7, FontColor.DontChange);
            }
        }
        if (base.ammoData != null)
        {
            i.AddHeader("headerAttackAmmo", null);
            i.AddText(base.ammoData.Name, FontColor.DontChange);
        }
        if (onWriteNote != null)
        {
            onWriteNote(i);
        }
        if (LayerDragGrid.Instance)
        {
            LayerDragGrid.Instance.owner.OnWriteNote(this, i);
        }
        if (EClass.debug.showExtra)
        {
            foreach (Element element2 in this.elements.dict.Values)
            {
                i.AddText(string.Concat(new string[]
                {
                    element2.source.alias,
                    "/",
                    element2.Value.ToString(),
                    "/",
                    element2.vBase.ToString(),
                    "/",
                    element2.vSource.ToString()
                }), FontColor.DontChange);
            }
        }
        i.Build();
    }
References Element._WriteNote(), TraitToolRange.BestDist, Card.category, TraitAbility.CreateAct(), EClass.debug, Card.elements, SourceManager.elements, Card.ExistsOnMap, Element.ExpToNext, ReligionManager.Eyth, Card.FameLv, ReligionManager.Find(), EClass.game, Element.Get(), ElementContainer.GetOrCreateElement(), Card.GetRootCard(), Card.HasElement(), Element.HasTag(), Element.id, LayerCraft.Instance, Element.IsFoodTraitMain, FoodEffect.IsHumanFlesh(), Element.IsTrait, FoodEffect.IsUndeadFlesh(), TraitBed.MaxHolders, EClass.pc, religion, Game.religions, CoreDebug.showExtra, Element.source, TraitBookSkill.source, EClass.sources, text, Card.trait, Element.Value, Element.vBase, Element.vExp, and Element.WriteNote().
Referenced by LayerCraft.RefreshProduct(), GridItemCardSource.SetButton(), and UICardInfo.SetThing().
Member Data Documentation
MaxFurnitureEnc
const int Thing.MaxFurnitureEnc = 12 static
Definition at line 2094 of file Thing.cs.
source
SourceThing.Row Thing.source
Definition at line 2096 of file Thing.cs.
Referenced by BuildMenu._Search(), AddAttackEvaluation(), ApplyMaterial(), ActMelee.Attack(), CharaBody.GetAttackIndex(), GetName(), Religion.GetOfferingValue(), ThingContainer.GetThingStack(), TaskHarvest.HarvestThing(), TaskHarvest.HaveHarvestThing(), QuestDeliver.IsDestThing(), BaseArea.ListRoomNames(), Props.ListThingStacksInCategory(), TraitTent.OnChangePlaceState(), OnCreate(), TaskHarvest.OnCreateProgress(), Props.OnNumChange(), AI_Fish.ProgressFish.OnProgressComplete(), CharaActorPCC.OnRender(), Chara.Pick(), AttackProcess.Prepare(), ThingContainer.RefreshGrid(), WidgetSearch.Search(), SetSource(), LayerResource.ShowThings(), Card.SpawnLoot(), TraitFactionBoard.TrySetAct(), TraitEcoMark.TrySetHeldAct(), TraitTicketFurniture.TrySetHeldAct(), Chara.TryUse(), and CoreDebug.UpdateInput().
stackOrder
int Thing.stackOrder
Definition at line 2098 of file Thing.cs.
Referenced by Map._ValidateInstalled(), and Map.Save().
tempName
string Thing.tempName
Definition at line 2100 of file Thing.cs.
Referenced by ThingContainer.RefreshGrid().
Property Documentation
CanSearchContents
bool Thing.CanSearchContents get
Definition at line 1903 of file Thing.cs.
    {
        get
        {
            return base.IsContainer && base.c_lockLv == 0 && !base.isNPCProperty && this.trait.CanSearchContents;
        }
    }
Referenced by ThingContainer._ListCurrency(), ThingContainer.AddFactory(), Card.AddThing(), ThingContainer.Find(), ThingContainer.Find< T >(), ThingContainer.Foreach(), ThingContainer.g__TrySearchContainer(), ThingContainer.GetCurrency(), ThingContainer.GetThingStack(), TaskDump.IsValidContainer(), LayerInventory.TryShowGuide(), and ThingContainer.TryStack().
isEquipped
bool Thing.isEquipped get
Definition at line 10 of file Thing.cs.
    {
        get
        {
            return base.c_equippedSlot != 0;
        }
    }
Referenced by InvOwner.AllowHold(), Chara.CanEat(), CanStackTo(), DragItemCard.DragInfo.DragInfo(), ZonePreEnterBoutWin.Execute(), ZonePreEnterEncounter.Execute(), Card.GetLightRadius(), QuestDeliver.IsDestThing(), ThingContainer.IsOverflowing(), InvOwner.ListInteractions(), InvOwner.OnClick(), HotItemEQSet.Perform(), ActEffect.Proc(), CardActor.RefreshSprite(), CharaBody.SetOwner(), Chara.ShouldEquip(), Chara.ShouldThrowAway(), InvOwner.TryHold(), Chara.TryPutSharedItems(), Map.TryShatter(), CharaBody.Unequip(), and CharaBody.UnqeuipIfTooHeavy().
IsMeleeWithAmmo
bool Thing.IsMeleeWithAmmo get
Definition at line 18 of file Thing.cs.
    {
        get
        {
            return this.trait is TraitToolRange && this.isEquipped;
        }
    }
Referenced by ActRanged.TryReload().
IsSharedContainer
bool Thing.IsSharedContainer get
Definition at line 1911 of file Thing.cs.
    {
        get
        {
            if (base.IsContainer && base.c_lockLv == 0 && !base.isNPCProperty)
            {
                Window.SaveData obj = base.GetObj<Window.SaveData>(2);
                return obj != null && obj.sharedType == ContainerSharedType.Shared;
            }
            return false;
        }
    }
Referenced by AI_Shopping.Buy(), QuestSharedContainer.CanUpdateOnTalk(), Props.Find(), Zone.g__SearchDest(), Props.GetNum(), AI_Idle.Run(), TraitBaseContainer.SetName(), Zone.TryGetThingFromSharedContainer(), and Chara.TryTakeSharedItems().
isThing
override bool Thing.isThing get
Definition at line 46 of file Thing.cs.
    {
        get
        {
            return true;
        }
    }
Penetration
int Thing.Penetration get
Definition at line 34 of file Thing.cs.
    {
        get
        {
            if (this.source.substats.Length == 0)
            {
                return 0;
            }
            return this.source.substats[0];
        }
    }
Referenced by AttackProcess.Prepare().
Pref
override SourcePref Thing.Pref get
Definition at line 62 of file Thing.cs.
    {
        get
        {
            if (this.source.origin == null || this.source.pref.UsePref)
            {
                return this.source.pref;
            }
            return this.source.origin.pref;
        }
    }
Referenced by BaseTileMap.DrawTile(), Cell.GetSurfaceHeight(), BaseTileMap.GetThingPosition(), and CoreDebug.UpdateInput().
range
int Thing.range get
Definition at line 26 of file Thing.cs.
    {
        get
        {
            return this.source.range;
        }
    }
SelfWeight
override int Thing.SelfWeight get
Definition at line 74 of file Thing.cs.
    {
        get
        {
            if (!base.IsUnique)
            {
                return (base.isWeightChanged ? base.c_weight : this.source.weight) * base.material.weight / 100;
            }
            if (!base.isWeightChanged)
            {
                return this.source.weight;
            }
            return base.c_weight;
        }
    }
Referenced by InvOwnerDeliver._OnProcess(), CanStackTo(), ThingGen.CreateTreasureContent(), Religion.GetOfferingValue(), CraftUtil.MixIngredients(), TraitBrewery.OnChildDecay(), and Chara.Revive().
sourceCard
override CardRow Thing.sourceCard get
Definition at line 54 of file Thing.cs.
    {
        get
        {
            return this.source;
        }
    }
Referenced by ApplyMaterial(), TraitCatalyst.CreateAct(), UIInspector.DrawHighlight(), BaseTileMap.DrawTile(), TileMapElona.DrawTile(), BaseTileMap.GetThingPosition(), DragItemCard.OnDragSpecial(), CharaActorPCC.OnRender(), ActEffect.Proc(), WidgetSearch.Search(), and AM_Picker.TestThing().
Tiles
override int [] Thing.Tiles get
Definition at line 90 of file Thing.cs.
    {
        get
        {
            return this.sourceCard._tiles;
        }
    }
The documentation for this class was generated from the following file:
Elin/Thing.cs