Elin Decompiled Documentation: HotItemAct Class Reference
HotItemAct Class Reference
Public Member Functions
override Sprite GetSprite ()
HotItemAct ()
HotItemAct (string alias)
HotItemAct (SourceElement.Row row)
override void SetImage (Image icon)
override bool TrySetAct (ActPlan p)
Public Member Functions inherited from HotItemGameAction
override void OnClick (ButtonHotItem b, Hotbar h)
override void OnRightClick (ButtonHotItem b)
override void OnMarkMapHighlights ()
Public Member Functions inherited from HotItem
string TextHotkey ()
virtual void OnClick (ButtonHotItem b, Hotbar h)
virtual void OnRightClick (ButtonHotItem b)
virtual bool CanAutoFire (Chara tg)
virtual void OnSetCurrentItem ()
virtual void OnUnsetCurrentItem ()
virtual void OnUnselect ()
virtual void SetImage (Image icon)
virtual bool TrySetAct (ActPlan p)
virtual void OnMarkMapHighlights ()
virtual void OnRenderTile (Point point, HitResult result, int dir)
Public Attributes
int id
Act _act
Public Attributes inherited from HotItem
ButtonHotItem button
Hotbar hotbar
bool disabled
Properties
override Act act [get]
override string Name [get]
SourceElement.Row source [get]
override bool UseUIObjMaterial [get]
override Color SpriteColor [get]
Properties inherited from HotItemGameAction
virtual Act act [get]
override bool IsGameAction [get]
Properties inherited from HotItem
override Sprite SpriteHighlight [get]
override bool IsSelectable [get]
override string TextTip [get]
virtual Thing RenderThing [get]
virtual Thing Thing [get]
virtual Thing Tool [get]
virtual bool IsTool [get]
virtual bool LookAtMouse [get]
virtual bool IsGameAction [get]
virtual bool UseUIObjMaterial [get]
Detailed Description
Definition at line 6 of file HotItemAct.cs.
Constructor & Destructor Documentation
HotItemAct() [1/3]
HotItemAct.HotItemAct () inline
Definition at line 62 of file HotItemAct.cs.
    {
    }
HotItemAct() [2/3]
HotItemAct.HotItemAct (string alias) inline
Definition at line 66 of file HotItemAct.cs.
    {
        this.id = EClass.sources.elements.alias[alias].id;
    }
References SourceManager.elements, and EClass.sources.
HotItemAct() [3/3]
HotItemAct.HotItemAct (SourceElement::Row row) inline
Definition at line 71 of file HotItemAct.cs.
    {
        this.id = row.id;
    }
Member Function Documentation
GetSprite()
override Sprite HotItemAct.GetSprite () inline
Definition at line 37 of file HotItemAct.cs.
    {
        return this.act.GetSprite();
    }
References act, and Act.GetSprite().
SetImage()
override void HotItemAct.SetImage (Image icon) inline virtual
Reimplemented from HotItem.
Definition at line 76 of file HotItemAct.cs.
    {
        this.act.SetImage(icon);
    }
References act, and Act.SetImage().
TrySetAct()
override bool HotItemAct.TrySetAct (ActPlan p) inline virtual
Reimplemented from HotItem.
Definition at line 81 of file HotItemAct.cs.
    {
        Card tg = null;
        p.pos.ListVisibleCards().ForeachReverse(delegate(Card a)
        {
            if (EClass.pc.CanSee(a) && !a.HasHost && this.act.IsValidTC(a))
            {
                tg = a;
                return true;
            }
            return false;
        });
        if (!this.act.CanPerform(EClass.pc, tg, p.pos))
        {
            return false;
        }
        p.TrySetAct(this.source.GetName(), delegate()
        {
            Card tg;
            if (tg != null && !tg.ExistsOnMap)
            {
                return false;
            }
            Point point = (tg != null && tg.ExistsOnMap) ? tg.pos : p.pos;
            if (!this.act.CanPerform(EClass.pc, tg, point))
            {
                return false;
            }
            string[] array = new string[8];
            array[0] = "hotitemact:";
            int num = 1;
            HotItemAct <>4__this = this;
            array[num] = ((<>4__this != null) ? <>4__this.ToString() : null);
            array[2] = "/";
            array[3] = this.act.id.ToString();
            array[4] = "/";
            int num2 = 5;
            tg = tg;
            array[num2] = ((tg != null) ? tg.ToString() : null);
            array[6] = "/";
            array[7] = p.performed.ToString();
            Debug.Log(string.Concat(array));
            if (p.performed && this.act.CanPressRepeat)
            {
                return EClass.pc.UseAbility(this.act.source.alias, tg, point, false);
            }
            return ButtonAbility.TryUse(this.act, tg, point, null, true, true);
        }, tg, null, -1, EClass._zone.IsCrime(EClass.pc, this.act), this.act.LocalAct, this.act.CanPressRepeat);
        return true;
    }
References EClass._zone, act, Act.CanPerform(), Chara.CanSee(), Card.ExistsOnMap, Card.HasHost, Zone.IsCrime(), Point.ListVisibleCards(), EClass.pc, ActPlan.performed, ActPlan.pos, Card.pos, source, Card.ToString(), Point.ToString(), ActPlan.TrySetAct(), and ButtonAbility.TryUse().
Member Data Documentation
_act
Act HotItemAct._act
Definition at line 135 of file HotItemAct.cs.
id
int HotItemAct.id
Definition at line 133 of file HotItemAct.cs.
Property Documentation
act
override Act HotItemAct.act get
Definition at line 8 of file HotItemAct.cs.
    {
        get
        {
            Act result;
            if ((result = this._act) == null)
            {
                result = (this._act = ACT.Create(this.id));
            }
            return result;
        }
    }
Referenced by GetSprite(), SetImage(), and TrySetAct().
Name
override string HotItemAct.Name get
Definition at line 21 of file HotItemAct.cs.
    {
        get
        {
            return this.source.GetName();
        }
    }
source
SourceElement.Row HotItemAct.source get
Definition at line 29 of file HotItemAct.cs.
    {
        get
        {
            return EClass.sources.elements.map.TryGetValue(this.id, null) ?? EClass.sources.elements.rows[0];
        }
    }
Referenced by TrySetAct().
SpriteColor
override Color HotItemAct.SpriteColor get
Definition at line 50 of file HotItemAct.cs.
    {
        get
        {
            if (!this.source.aliasRef.IsEmpty())
            {
                return EClass.setting.elements[this.source.aliasRef].colorSprite;
            }
            return Color.white;
        }
    }
UseUIObjMaterial
override bool HotItemAct.UseUIObjMaterial get
Definition at line 42 of file HotItemAct.cs.
    {
        get
        {
            return true;
        }
    }
The documentation for this class was generated from the following file:
Elin/HotItemAct.cs