Elin Decompiled Documentation: ActPlan.Item Class Reference
ActPlan.Item Class Reference
Public Member Functions
string GetText (bool showName)
string GetTextContext (bool showName)
bool Perform (bool repeated=false)
Public Attributes
Act act
Card tc
Point pos
Properties
Chara cc [get]
bool HideHint [get]
Detailed Description
Definition at line 20 of file ActPlan.cs.
Member Function Documentation
GetText()
string ActPlan.Item.GetText (bool showName) inline
Definition at line 46 of file ActPlan.cs.
        {
            return act.GetText() + ((showName && act.GetTextSmall(tc) != null) ? ("\n<size=28>" + act.GetTextSmall(tc) + "</size>") : "");
        }
References ActPlan.Item.act, Act.GetText(), Act.GetTextSmall(), and ActPlan.Item.tc.
GetTextContext()
string ActPlan.Item.GetTextContext (bool showName) inline
Definition at line 51 of file ActPlan.cs.
        {
            return act.GetText() + ((showName && tc != null && !HideHint) ? ("<size=13> (" + tc.Name + ")</size>") : "");
        }
References ActPlan.Item.act, Act.GetText(), ActPlan.Item.HideHint, Card.Name, and ActPlan.Item.tc.
Referenced by ActPlan.ShowContextMenu().
Perform()
bool ActPlan.Item.Perform (bool repeated = false) inline
Definition at line 56 of file ActPlan.cs.
        {
            if (AM_Adv.actCount == 0 && !Dialog.warned)
            {
                warning = true;
                Chara _CC = Act.CC;
                Card _TC = Act.TC;
                Point _TP = new Point(Act.TP);
                if (EClass._zone.IsCrime(EClass.pc, act) && act.ID != "actContainer")
                {
                    Dialog.TryWarnCrime(delegate
                    {
                        Act.CC = _CC;
                        Act.TC = _TC;
                        Act.TP.Set(_TP);
                        if (Perform())
{
                            EClass.player.EndTurn();
                        }
                    });
                    return false;
                }
                if (act is TaskHarvest && (act as TaskHarvest).mode == BaseTaskHarvest.HarvestType.Disassemble)
                {
                    Dialog.TryWarnDisassemble(delegate
                    {
                        Act.CC = _CC;
                        Act.TC = _TC;
                        Act.TP.Set(_TP);
                        if (Perform())
{
                            EClass.player.EndTurn();
                        }
                    });
                    return false;
                }
            }
            warning = false;
            int num = cc.pos.Distance(pos);
            bool flag = num == 1 && cc.CanInteractTo(pos);
            AIAct aIAct = act as AIAct;
            if (act.IsAct)
            {
                if (act.PerformDistance != -1 && (num > act.PerformDistance || (num == 1 && !flag)))
                {
                    cc.SetAIImmediate(new DynamicAIAct(act.GetText(), () => act.Perform(cc, tc, pos))
                    {
                        pos = pos.Copy()
                    });
                    return false;
                }
                bool num2 = act.Perform(cc, tc, pos);
                if (num2 && !EClass.pc.HasNoGoal)
                {
                    ActionMode.Adv.SetTurbo();
                }
                if (num2)
                {
                    return EClass.pc.HasNoGoal;
                }
                return false;
            }
            if (repeated)
            {
                if (cc.ai.GetType() == act.GetType() && cc.ai.IsRunning)
                {
                    return false;
                }
                aIAct.Reset();
                if (!act.CanPerform())
                {
                    cc.SetAI(Chara._NoGoalRepeat);
                    return false;
                }
                if (aIAct is Task task)
                {
                    task.isDestroyed = false;
                    TaskPoint taskPoint = task as TaskPoint;
                    if (EClass.scene.mouseTarget.isValid && taskPoint != null)
                    {
                        taskPoint.isRepeated = true;
                        taskPoint.pos = EClass.scene.mouseTarget.pos.Copy();
                    }
                }
            }
            cc.SetAIImmediate(aIAct);
            ActionMode.Adv.SetTurbo(aIAct.UseTurbo ? (-1) : 0);
            return false;
        }
References Chara._NoGoalRepeat, EClass._zone, ActPlan.Item.act, AM_Adv.actCount, ActionMode.Adv, Chara.ai, Chara.CanInteractTo(), Act.CanPerform(), Act.CC, ActPlan.Item.cc, Point.Copy(), Point.Distance(), Player.EndTurn(), Act.GetText(), Chara.HasNoGoal, Act.ID, Act.IsAct, Zone.IsCrime(), AIAct.IsRunning, PointTarget.isValid, Scene.mouseTarget, EClass.pc, Act.Perform(), ActPlan.Item.Perform(), Act.PerformDistance, EClass.player, ActPlan.Item.pos, Card.pos, PointTarget.pos, AIAct.Reset(), EClass.scene, Point.Set(), Chara.SetAI(), Chara.SetAIImmediate(), AM_Adv.SetTurbo(), Act.TC, ActPlan.Item.tc, Act.TP, Dialog.TryWarnCrime(), Dialog.TryWarnDisassemble(), AIAct.UseTurbo, Dialog.warned, and ActPlan.warning.
Referenced by ActPlan.Item.Perform(), and ActPlan.ShowContextMenu().
Member Data Documentation
act
Act ActPlan.Item.act
Definition at line 22 of file ActPlan.cs.
Referenced by ActPlan.Item.GetText(), ActPlan.Item.GetTextContext(), and ActPlan.Item.Perform().
pos
Point ActPlan.Item.pos
Definition at line 26 of file ActPlan.cs.
Referenced by ActPlan.Item.Perform().
tc
Card ActPlan.Item.tc
Definition at line 24 of file ActPlan.cs.
Referenced by ActPlan.Item.GetText(), ActPlan.Item.GetTextContext(), and ActPlan.Item.Perform().
Property Documentation
cc
Chara ActPlan.Item.cc get
Definition at line 28 of file ActPlan.cs.
Referenced by ActPlan.Item.Perform().
HideHint
bool ActPlan.Item.HideHint get
Definition at line 30 of file ActPlan.cs.
        {
            get
            {
                if (!EClass.pc.isBlind)
                {
                    if (tc != null && tc.isChara)
                    {
                        return !EClass.pc.CanSee(tc);
                    }
                    return false;
                }
                return true;
            }
        }
Referenced by ActPlan.Item.GetTextContext().
The documentation for this class was generated from the following file:
Elin/ActPlan.cs