Elin Decompiled Documentation: WidgetMainText Class Reference
WidgetMainText Class Reference
Classes
class Extra
Public Member Functions
override object CreateExtra ()
override void OnActivate ()
void RefreshBG ()
void Append (string s, Point pos=null)
void Append (string s, Color col, Point pos=null)
void Append (Sprite sprite)
void _ToggleLog ()
void NewLine ()
override void OnSetContextMenu (UIContextMenu m)
override void OnChangeResolution ()
Public Member Functions inherited from Widget
void Test ()
bool IsInRightMode ()
void Activate ()
void RefreshOrder ()
virtual void OnActivate ()
virtual object CreateExtra ()
void Deactivate ()
virtual void OnDeactivate ()
void Close ()
void Reactivate ()
virtual void OnManagerActivate ()
virtual void OnManagerDeactivate ()
void SetAnchor (RectPosition p)
void SetPivot (RectPosition p)
virtual void OnChangePivot ()
void UpdateConfig ()
virtual void OnUpdateConfig ()
void ClampToScreen ()
virtual void OnChangeResolution ()
void OnChangePosition ()
virtual void OnChangeActionMode ()
virtual void OnFlip ()
bool IsAlignTop ()
Layer AddLayer (Layer l, Transform trans)
void RefreshTipPivotPosition ()
SkinSet GetSkin ()
SkinConfig GetSkinConfig ()
void SetSkin (int id, int v=0)
void TestSkin ()
virtual void ApplySkin ()
virtual void OnApplySkin ()
void InstantiateDeco (SkinDeco deco)
void AddDeco (SkinDeco deco)
void RemoveDeco (SkinDeco deco)
virtual bool CanShowContextMenu ()
void ShowContextMenu ()
void SetBaseContextMenu (UIContextMenu m)
virtual void OnSetContextMenu (UIContextMenu m)
void SetGridContextMenu (UIContextMenu m)
void SoundActivate ()
void OnChangeResolution ()
SkinSet GetSkin ()
SkinConfig GetSkinConfig ()
Static Public Member Functions
static void HideLog ()
static void ToggleLog ()
static void Refresh ()
Static Public Member Functions inherited from EMono
static int rnd (int a)
Public Attributes
MsgBox box
UIItem moldLine
int visibleLines
Transform layout
Sprite spriteElin
Sprite spriteDestroy
Sprite spriteEther
bool newLine = true
Public Attributes inherited from Widget
Image imageBG
SoundData soundActivate
UIDragPanel dragPanel
RectTransform tipPivotLeft
RectTransform tipPivotRight
Static Public Attributes
static WidgetMainText Instance
static MsgBox boxBk
static bool ignoreStack
Static Public Attributes inherited from EMono
static Core core
Properties
Extra extra [get]
override bool ShowStyleMenu [get]
override bool AlwaysTop [get]
Properties inherited from Widget
string ID [get]
Config config [get]
SkinRoot skinRoot [get]
bool IsSealed [get]
virtual bool ShowStyleMenu [get]
virtual bool AlwaysTop [get]
virtual bool IsStaticPosition [get]
virtual bool AlwaysBottom [get]
virtual Type SetSiblingAfter [get]
virtual bool ShowInBuildMode [get]
virtual bool RightClickToClose [get]
virtual bool AllowRightClickToClose [get]
Properties inherited from EMono
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SoundManager Sound [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static CoreDebug debug [get]
Private Member Functions
void _Refresh ()
Private Attributes
UIItem currentItem
Additional Inherited Members
Public Types inherited from Widget
enum WidgetType { Default , ZoomMenu }
enum State { Active , Inactive }
Protected Member Functions inherited from Widget
void ClampToScreenEnsured (Component c, Vector2 anchoredPos)
void ClampToScreen (RectTransform rect, float margin=10f)
Protected Attributes inherited from Widget
bool flip
Detailed Description
Definition at line 4 of file WidgetMainText.cs.
Member Function Documentation
_Refresh()
void WidgetMainText._Refresh () inline private
Definition at line 203 of file WidgetMainText.cs.
    {
        box.SetActive(box.isShowingLog || !WidgetFeed.Intercept, delegate(bool enabled)
        {
            if (enabled)
            {
                box.RebuildLayout(recursive: true);
            }
        });
    }
References box, WidgetFeed.Intercept, and MsgBox.isShowingLog.
Referenced by _ToggleLog(), Append(), OnActivate(), and Refresh().
_ToggleLog()
void WidgetMainText._ToggleLog () inline
Definition at line 176 of file WidgetMainText.cs.
    {
        box.ToggleLog();
        _Refresh();
        if (box.isShowingLog)
        {
            if ((bool)WidgetFeed.Instance)
            {
                WidgetFeed.Instance.pop.KillAll();
            }
            box.RebuildLayout(recursive: true);
        }
    }
References _Refresh(), box, WidgetFeed.Instance, MsgBox.isShowingLog, PopManager.KillAll(), WidgetFeed.pop, and MsgBox.ToggleLog().
Referenced by HideLog(), Scene.OnUpdate(), WidgetManager.Reset(), and ToggleLog().
Append() [1/3]
void WidgetMainText.Append (Sprite sprite) inline
Definition at line 152 of file WidgetMainText.cs.
    {
        box.Append(sprite);
        _Refresh();
    }
References _Refresh(), MsgBox.Append(), and box.
Append() [2/3]
void WidgetMainText.Append (string s, Color col, Point pos = null) inline
Definition at line 98 of file WidgetMainText.cs.
    {
        if (s.IsEmpty() || s == " ")
        {
            return;
        }
        if (pos != null)
        {
            box.Load("MsgFocus").button1.onClick.AddListener(delegate
            {
                EMono.screen.Focus(pos);
            });
        }
        if (s.StartsWith("*"))
        {
            s = " " + s;
        }
        if (Lang.setting.useSpace)
        {
            s += " ";
            if (s[0] == ' ')
            {
                s = s.TrimStart(' ');
            }
        }
        else if (s.EndsWith("*"))
        {
            s += " ";
        }
        if (MsgBlock.lastBlock != null && MsgBlock.lastText == s && !ignoreStack)
        {
            MsgBlock lastBlock = MsgBlock.lastBlock;
            if (lastBlock.txt != null)
            {
                UIText txt = lastBlock.txt;
                lastBlock.repeat++;
                string text = txt.text;
                if (text.EndsWith(")  ") && text.Contains("(x"))
                {
                    text = text.Substring(0, text.IndexOf("(x"));
                }
                txt.text = text + "(x" + (lastBlock.repeat + 1) + ")  ";
                if (lastBlock.repeat == 1)
                {
                    txt.RebuildLayout();
                    box.RebuildLayout(recursive: true);
                }
                return;
            }
        }
        box.Append(s, col);
        _Refresh();
    }
References _Refresh(), MsgBox.Append(), box, UIItem.button1, BaseGameScreen.Focus(), ignoreStack, MsgBlock.lastBlock, MsgBlock.lastText, MsgBox.Load(), MsgBlock.repeat, EMono.screen, Lang.setting, MsgBlock.txt, and LangSetting.useSpace.
Append() [3/3]
void WidgetMainText.Append (string s, Point pos = null) inline
Definition at line 93 of file WidgetMainText.cs.
    {
        Append(s, Msg.colors.Default, pos);
    }
References Append(), Msg.colors, and MsgColors.Default.
Referenced by Msg.Append(), Append(), Msg.GetGameText(), Msg.Nerun(), OnActivate(), Msg.SayHomeMember(), Msg.SayPic(), Msg.SayRaw(), and Msg.Talk().
CreateExtra()
override object WidgetMainText.CreateExtra () inline virtual
Reimplemented from Widget.
Definition at line 48 of file WidgetMainText.cs.
    {
        return new Extra();
    }
HideLog()
static void WidgetMainText.HideLog () inline static
Definition at line 158 of file WidgetMainText.cs.
    {
        if ((bool)Instance && Instance.box.isShowingLog)
        {
            Instance._ToggleLog();
        }
    }
References _ToggleLog(), box, Instance, and MsgBox.isShowingLog.
Referenced by ELayer.OnAfterAddLayer().
NewLine()
void WidgetMainText.NewLine () inline
Definition at line 190 of file WidgetMainText.cs.
    {
        box.MarkNewBlock();
    }
References box, and MsgBox.MarkNewBlock().
Referenced by Msg.NewLine(), OnActivate(), and Zone_User.OnActivate().
OnActivate()
override void WidgetMainText.OnActivate () inline virtual
Reimplemented from Widget.
Definition at line 53 of file WidgetMainText.cs.
    {
        bool flag = true;
        if ((bool)boxBk)
        {
            UnityEngine.Object.DestroyImmediate(box.gameObject);
            box = boxBk;
            boxBk.transform.SetParent(base.transform, worldPositionStays: false);
            boxBk.GetComponentInChildren<UIDragPanel>(includeInactive: true).SetTarget(this.Rect());
            boxBk = null;
            flag = false;
        }
        dragPanel = box.dragPanel;
        imageBG = box.imageBg;
        Instance = this;
        box.maxBlock = extra.maxLine;
        box.fadeLines = extra.fadeLines;
        if (base.config.skin.bgColor.Equals(new Color(0f, 0f, 0f, 0f)))
        {
            base.config.skin.bgColor = EMono.core.refs.bg_msg[extra.bg].color;
        }
        RefreshBG();
        OnChangeResolution();
        box.Init();
        if (flag)
        {
            Append("welcome_intro".langGame(EMono.core.version.GetText()));
            Append(spriteElin);
            NewLine();
            Append("welcome".langGame(EInput.keys.report.key.ToString() ?? ""));
            NewLine();
        }
        _Refresh();
    }
References _Refresh(), Append(), WidgetMainText.Extra.bg, CoreRef.bg_msg, box, boxBk, Color, EMono.core, MsgBox.dragPanel, Widget.dragPanel, extra, WidgetMainText.Extra.fadeLines, Version.GetText(), MsgBox.imageBg, Widget.imageBG, MsgBox.Init(), Instance, EInput.KeyMap.key, EInput.keys, WidgetMainText.Extra.maxLine, NewLine(), OnChangeResolution(), RefreshBG(), Core.refs, EInput.KeyMapManager.report, spriteElin, and BaseCore.version.
OnChangeResolution()
override void WidgetMainText.OnChangeResolution () inline virtual
Reimplemented from Widget.
Definition at line 251 of file WidgetMainText.cs.
    {
        base.OnChangeResolution();
        RectTransform rectTransform = this.Rect();
        rectTransform.sizeDelta = new Vector2(0.01f * (float)Screen.width * (float)extra.width, rectTransform.sizeDelta.y);
    }
References extra, and WidgetMainText.Extra.width.
Referenced by OnActivate(), and OnSetContextMenu().
OnSetContextMenu()
override void WidgetMainText.OnSetContextMenu (UIContextMenu m) inline virtual
Reimplemented from Widget.
Definition at line 214 of file WidgetMainText.cs.
    {
        SkinConfig cfg = base.config.skin;
        UIContextMenu uIContextMenu = m.AddChild("setting");
        uIContextMenu.AddSlider("msgLines", (float n) => n.ToString() ?? "", box.maxBlock, delegate(float a)
        {
            box.maxBlock = (int)a;
            extra.maxLine = (int)a;
        }, 2f, 10f, isInt: true, hideOther: false);
        uIContextMenu.AddSlider("width", (float a) => a.ToString() ?? "", extra.width, delegate(float a)
        {
            extra.width = (int)a;
            OnChangeResolution();
        }, 30f, 100f, isInt: true);
        UIContextMenu uIContextMenu2 = m.AddChild("style");
        uIContextMenu2.AddToggle("fadeLines", extra.fadeLines, delegate(bool a)
        {
            extra.fadeLines = (box.fadeLines = a);
            box.RefreshAlpha();
        });
        uIContextMenu2.AddSlider("changeBG", (float n) => n + "/" + (EMono.core.refs.bg_msg.Count - 1), extra.bg, delegate(float a)
        {
            extra.bg = (int)a;
            cfg.bgColor = EMono.core.refs.bg_msg[extra.bg].color;
            RefreshBG();
        }, 0f, EMono.core.refs.bg_msg.Count - 1, isInt: true);
        uIContextMenu2.AddButton("colorBG", delegate
        {
            EMono.ui.AddLayer<LayerColorPicker>().SetColor(cfg.bgColor, EMono.ui.skins.skinSets[cfg.id].bgs[cfg.bg].color, delegate(PickerState state, Color _c)
            {
                cfg.bgColor = _c;
                RefreshBG();
            });
        });
        SetBaseContextMenu(m);
    }
References UIContextMenu.AddButton(), UIContextMenu.AddChild(), UIContextMenu.AddSlider(), UIContextMenu.AddToggle(), SkinConfig.bg, WidgetMainText.Extra.bg, CoreRef.bg_msg, SkinConfig.bgColor, box, Color, EMono.core, extra, WidgetMainText.Extra.fadeLines, SkinConfig.id, MsgBox.maxBlock, OnChangeResolution(), MsgBox.RefreshAlpha(), RefreshBG(), Core.refs, Widget.SetBaseContextMenu(), EMono.ui, and WidgetMainText.Extra.width.
Refresh()
static void WidgetMainText.Refresh () inline static
Definition at line 195 of file WidgetMainText.cs.
    {
        if ((bool)Instance)
        {
            Instance._Refresh();
        }
    }
References _Refresh(), and Instance.
Referenced by WidgetFeed.OnActivate(), and WidgetFeed.OnDeactivate().
RefreshBG()
void WidgetMainText.RefreshBG () inline
Definition at line 88 of file WidgetMainText.cs.
    {
        box.SetBG(EMono.core.refs.bg_msg[extra.bg], base.config.skin.bgColor);
    }
References WidgetMainText.Extra.bg, CoreRef.bg_msg, box, EMono.core, extra, Core.refs, and MsgBox.SetBG().
Referenced by OnActivate(), and OnSetContextMenu().
ToggleLog()
static void WidgetMainText.ToggleLog () inline static
Definition at line 166 of file WidgetMainText.cs.
    {
        if (!Instance)
        {
            EMono.ui.widgets.Activate("MainText");
        }
        Instance._ToggleLog();
        SE.ClickGeneral();
    }
References _ToggleLog(), Instance, and EMono.ui.
Referenced by HotItemToggleLog.OnClick(), and AM_BaseGameMode.OnUpdateInput().
Member Data Documentation
box
MsgBox WidgetMainText.box
Definition at line 23 of file WidgetMainText.cs.
Referenced by _Refresh(), _ToggleLog(), Append(), HideLog(), NewLine(), OnActivate(), OnSetContextMenu(), Scene.OnUpdate(), RefreshBG(), and WidgetManager.Reset().
boxBk
MsgBox WidgetMainText.boxBk static
Definition at line 19 of file WidgetMainText.cs.
Referenced by OnActivate().
currentItem
UIItem WidgetMainText.currentItem private
Definition at line 25 of file WidgetMainText.cs.
ignoreStack
bool WidgetMainText.ignoreStack static
Definition at line 21 of file WidgetMainText.cs.
Referenced by Append().
Instance
WidgetMainText WidgetMainText.Instance static
Definition at line 17 of file WidgetMainText.cs.
Referenced by HideLog(), OnActivate(), Zone_User.OnActivate(), Scene.OnUpdate(), Refresh(), WidgetManager.Reset(), and ToggleLog().
layout
Transform WidgetMainText.layout
Definition at line 31 of file WidgetMainText.cs.
moldLine
UIItem WidgetMainText.moldLine
Definition at line 27 of file WidgetMainText.cs.
newLine
bool WidgetMainText.newLine = true
Definition at line 40 of file WidgetMainText.cs.
spriteDestroy
Sprite WidgetMainText.spriteDestroy
Definition at line 35 of file WidgetMainText.cs.
Referenced by Msg.GetGameText().
spriteElin
Sprite WidgetMainText.spriteElin
Definition at line 33 of file WidgetMainText.cs.
Referenced by OnActivate().
spriteEther
Sprite WidgetMainText.spriteEther
Definition at line 37 of file WidgetMainText.cs.
visibleLines
int WidgetMainText.visibleLines
Definition at line 29 of file WidgetMainText.cs.
Property Documentation
AlwaysTop
override bool WidgetMainText.AlwaysTop get
Definition at line 46 of file WidgetMainText.cs.
extra
Extra WidgetMainText.extra get
Definition at line 42 of file WidgetMainText.cs.
Referenced by OnActivate(), OnChangeResolution(), OnSetContextMenu(), and RefreshBG().
ShowStyleMenu
override bool WidgetMainText.ShowStyleMenu get
Definition at line 44 of file WidgetMainText.cs.
The documentation for this class was generated from the following file:
Elin/WidgetMainText.cs