Elin Decompiled Documentation: TextConv Class Reference
TextConv Class Reference
Classes
class Item
Public Member Functions
StringBuilder Apply (ref string text, int gender)
override void BuildMap (string sheetName=null)
Public Member Functions inherited from ExcelData
ExcelData ()
ExcelData (string _path, int _index)
ExcelData (string _path)
void LoadBook ()
bool IsModified ()
virtual void BuildMap (string sheetName="_default")
List< Dictionary< string, string > > BuildList (string sheetName="_default")
void Override (Dictionary< string, SourceData > sources, bool canAddData=true)
string GetText (string id, string topic="text")
Public Attributes
string[] I_M
string[] I_F
string[] you_M
string[] you_F
string[] tags
int p_I_M
int p_I_F
int p_you_M
int p_you_F
List< Item > items = new List<Item>()
Public Attributes inherited from ExcelData
int startIndex = 5
XSSFWorkbook book
IRow rowIndex
Dictionary< string, Sheet > sheets = new Dictionary<string, Sheet>()
string path
int maxEmptyRows
DateTime lastModified
Detailed Description
Definition at line 6 of file TextConv.cs.
Member Function Documentation
Apply()
StringBuilder TextConv.Apply (ref string text, int gender) inline
Definition at line 71 of file TextConv.cs.
    {
        BuildMap(null);
        StringBuilder stringBuilder = new StringBuilder();
        string text2 = null;
        Item item = null;
        int num = 0;
        if (gender == 0)
        {
            gender = ((Rand.rnd(3) != 0) ? 1 : 2);
        }
        while (num < text.Length)
        {
            bool flag = false;
            foreach (Item item2 in items)
            {
                if ((item2.probab != 0 && Rand.Range(0, 100) >= item2.probab) || (item2.gender != 0 && gender != item2.gender))
                {
                    continue;
                }
                string[] keys = item2.keys;
                foreach (string text3 in keys)
                {
                    flag = true;
                    for (int j = 0; j < text3.Length; j++)
                    {
                        if (num + j >= text.Length || text[num + j] != text3[j])
{
                            flag = false;
                            break;
                        }
                    }
                    if (flag && item2.suffix != null)
                    {
                        flag = false;
                        if (num + text3.Length >= text.Length)
{
                            continue;
                        }
                        string[] suffix = item2.suffix;
                        foreach (string text4 in suffix)
{
                            if (text[num + text3.Length] == text4[0])
{
                                flag = true;
                                break;
                            }
                        }
                    }
                    if (flag)
                    {
                        item = item2;
                        text2 = text3;
                        break;
                    }
                }
                if (flag)
                {
                    break;
                }
            }
            if (flag && text2.Length > 0)
            {
                stringBuilder.Append((item.additive ? text2 : "") + item.strs[Rand.Range(0, item.strs.Length)]);
                num += text2.Length;
            }
            else
            {
                stringBuilder.Append(text[num]);
                num++;
            }
        }
        stringBuilder.Replace("…ー", "ー…");
        return stringBuilder;
    }
References BuildMap(), TextConv.Item.gender, item, items, TextConv.Item.keys, TextConv.Item.probab, Rand.Range(), Rand.rnd(), and TextConv.Item.suffix.
BuildMap()
override void TextConv.BuildMap (string sheetName = null) inline virtual
Reimplemented from ExcelData.
Definition at line 147 of file TextConv.cs.
    {
        LoadBook();
        ISheet sheetAt = book.GetSheetAt(0);
        if (sheetAt.LastRowNum <= 3)
        {
            return;
        }
        for (int i = 3; i <= sheetAt.LastRowNum; i++)
        {
            IRow row = sheetAt.GetRow(i);
            if (row.Cells.Count == 0)
            {
                Debug.LogWarning(path + "/" + book?.ToString() + "/" + sheetName + "/" + sheetAt.LastRowNum + "/" + i);
                continue;
            }
            string text = row.GetCell(0).ToString();
            if (text.IsEmpty())
            {
                Debug.LogWarning(path + "/" + book?.ToString() + "/" + sheetName + "/" + sheetAt.LastRowNum + "/" + i);
                continue;
            }
            string text2 = row.GetCell(1).ToString();
            string text3 = row.GetCell(2)?.ToString() ?? "";
            int @int = ExcelParser.GetInt(4, row);
            if (text[0] == '$')
            {
                switch (text + "_" + text3)
                {
                case "$I_":
                    I_M = (I_F = text2.Split(','));
                    p_I_M = (p_I_F = @int);
                    break;
                case "$you_":
                    you_M = (you_F = text2.Split(','));
                    p_you_M = (p_you_F = @int);
                    break;
                case "$I_M":
                    I_M = text2.Split(',');
                    p_I_M = @int;
                    break;
                case "$you_M":
                    you_M = text2.Split(',');
                    p_you_M = @int;
                    break;
                case "$I_F":
                    I_F = text2.Split(',');
                    p_I_F = @int;
                    break;
                case "$you_F":
                    you_F = text2.Split(',');
                    p_you_F = @int;
                    break;
                case "$tag":
                    tags = text2.Split(',');
                    break;
                }
            }
            items.Add(new Item(row, text, text2, text3, @int));
        }
    }
References ExcelData.book, Debug, ExcelParser.GetInt(), I_F, I_M, items, ExcelData.LoadBook(), p_I_F, p_I_M, p_you_F, p_you_M, ExcelData.path, tags, you_F, and you_M.
Referenced by Apply().
Member Data Documentation
I_F
string [] TextConv.I_F
Definition at line 53 of file TextConv.cs.
Referenced by BuildMap().
I_M
string [] TextConv.I_M
Definition at line 51 of file TextConv.cs.
Referenced by BuildMap().
items
List<Item> TextConv.items = new List<Item>()
Definition at line 69 of file TextConv.cs.
Referenced by Apply(), and BuildMap().
p_I_F
int TextConv.p_I_F
Definition at line 63 of file TextConv.cs.
Referenced by BuildMap().
p_I_M
int TextConv.p_I_M
Definition at line 61 of file TextConv.cs.
Referenced by BuildMap().
p_you_F
int TextConv.p_you_F
Definition at line 67 of file TextConv.cs.
Referenced by BuildMap().
p_you_M
int TextConv.p_you_M
Definition at line 65 of file TextConv.cs.
Referenced by BuildMap().
tags
string [] TextConv.tags
Definition at line 59 of file TextConv.cs.
Referenced by BuildMap().
you_F
string [] TextConv.you_F
Definition at line 57 of file TextConv.cs.
Referenced by BuildMap().
you_M
string [] TextConv.you_M
Definition at line 55 of file TextConv.cs.
Referenced by BuildMap().
The documentation for this class was generated from the following file:
Elin/Plugins.basecore/TextConv.cs