Elin Decompiled Documentation: LayerPixelPaint Class Reference
LayerPixelPaint Class Reference
Public Member Functions
override void OnInit ()
void SetCanvas (TraitCanvas c)
Public Member Functions inherited from ELayer
override void OnBeforeAddLayer ()
void InitInspector ()
sealed override void Init ()
override void OnAfterAddLayer ()
void TryShowHelp ()
void AddLayerToUI (string id)
void TryShowHint (string _langHint=null)
void TalkHomeMemeber (string id)
void TalkMaid (string id)
override void OnRightClick ()
Public Member Functions inherited from Layer
virtual string GetTextHeader (Window window)
virtual bool HeaderIsListOf (int id)
virtual void Init ()
virtual void OnInit ()
virtual void OnAfterInit ()
virtual void ApplySkin ()
void ShowScreenLock (string id)
void UpdateInput ()
virtual void OnUpdateInput ()
virtual void OnRightClick ()
virtual bool OnBack ()
virtual void OnChangeLayer ()
virtual void OnCreate ()
void _AddLayer (string id)
Layer AddLayer (string id)
T AddLayer< T > ()
T AddLayer< T > (string id)
T AddLayerDontCloseOthers< T > ()
Layer AddLayerDontCloseOthers (Layer l)
T GetOrAddLayer< T > ()
virtual void OnBeforeAddLayer ()
virtual void OnAfterAddLayer ()
Layer AddLayer (Layer l)
void ToggleLayer (string id)
T ToggleLayer< T > (string id=null)
void WaitAndClose ()
void OnClickClose ()
virtual void Close ()
void CloseLayers ()
void RemoveLayers (bool removeImportant=false)
bool RemoveLayer< T > ()
void RemoveLayer (Layer l)
virtual void OnKill ()
Layer SetOnKill (Action action)
void DisableClose ()
void Delay (float duration=0.05f)
Layer SetDelay (float d)
Layer GetLayer (string id)
T GetLayer< T > (bool fromTop=false)
Layer GetTopLayer ()
void SwitchContent (int idWindow, int i)
virtual void OnSwitchContent (Window window)
Layer SetTitles (string langList, string idHeaderRow=null)
bool IsBlockWidgetClick ()
bool IsHideHud ()
bool IsAllowGeneralInput ()
bool IsUseBlur ()
bool IsPointerOnLayer ()
void ApplySkin ()
Public Attributes
PixelPaint paint
GridLayoutGroup layoutColors
ColorPicker picker
Action onApply
Public Attributes inherited from Layer
Option option
UnityEvent onKill
Anime animeIn
Anime animeOut
bool closeOthers
bool defaultActionMode = true
Button screenLock
Layer parent
string idLayer
List< Layer > layers = new List<Layer>()
Vector2 lastParentPos
List< Window > windows = new List<Window>()
string langHint
Additional Inherited Members
Static Public Member Functions inherited from ELayer
static int rnd (int a)
Static Public Member Functions inherited from Layer
static T Create< T > ()
static T Create< T > (string path)
static Layer Create (string path)
Static Public Attributes inherited from Layer
static int skipInput
static bool closeOnRightClick
static bool rightClicked
static bool cancelKeyDown
static bool ignoreSounds
static Transform blurStopInstance
static string[] searchPath = new string[3] { "Layer", "Layer/Dialog", "Layer/LayerHome" }
Protected Member Functions inherited from ELayer
sealed override void _Close ()
sealed override void Kill ()
Protected Member Functions inherited from Layer
virtual void Awake ()
virtual void _Close ()
virtual void Kill ()
Protected Attributes inherited from Layer
RectTransform _rect
bool isDestroyed
Properties inherited from ELayer
static Core core [get]
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static FactionBranch Branch [get]
static Faction Home [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static CoreConfig config [get]
static GameSetting setting [get]
static ColorProfile Colors [get]
static SourceManager sources [get]
static World world [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
bool IsFloat [get]
virtual string IdHelp [get]
Properties inherited from Layer
Layer TopLayer [get]
string uid [get]
virtual RectTransform rectLayers [get]
virtual bool blockWidgetClick [get]
Detailed Description
Definition at line 6 of file LayerPixelPaint.cs.
Member Function Documentation
OnInit()
override void LayerPixelPaint.OnInit () inline virtual
Reimplemented from Layer.
Definition at line 16 of file LayerPixelPaint.cs.
    {
        UIItem t = layoutColors.CreateMold<UIItem>();
        for (int i = 0; i < 8; i++)
        {
            UIItem item = Util.Instantiate(t, layoutColors);
            int _i = i;
            item.button1.icon.color = IntColor.FromInt(ELayer.core.config.colors[_i]);
            item.button1.SetOnClick(delegate
            {
                picker.SelectColor(item.button1.icon.color);
            });
            item.button2.SetOnClick(delegate
            {
                item.button1.icon.color = picker.SelectedColor;
                ELayer.core.config.colors[_i] = IntColor.ToInt(picker.SelectedColor);
                SE.Tab();
            });
        }
        layoutColors.RebuildLayout();
        windows[0].AddBottomButton("apply", delegate
        {
            onApply?.Invoke();
        });
        windows[0].AddBottomButton("cancel", delegate
        {
            Close();
        });
        paint.Init();
    }
References Layer.Close(), CoreConfig.colors, Core.config, ELayer.core, IntColor.FromInt(), PixelPaint.Init(), item, layoutColors, onApply, paint, picker, Empyrean.ColorPicker.ColorPicker.SelectColor(), Empyrean.ColorPicker.ColorPicker.SelectedColor, IntColor.ToInt(), Util, and Layer.windows.
SetCanvas()
void LayerPixelPaint.SetCanvas (TraitCanvas c) inline
Definition at line 47 of file LayerPixelPaint.cs.
    {
        onApply = delegate
        {
            c.owner.PlaySound(c.owner.material.GetSoundImpact());
            c.owner.renderer.PlayAnime(AnimeID.Shiver);
            Thing thing = c.owner.Split(1);
            thing.c_textureData = paint.tex.EncodeToPNG();
            thing.isModified = true;
            thing.ClearPaintSprite();
            thing.GetPaintSprite();
            thing.renderer.RefreshSprite();
            Close();
        };
        if (c.owner.c_textureData != null)
        {
            paint.tex.LoadImage(c.owner.c_textureData);
        }
        paint.imageMask.texture = c.owner.GetSprite().texture;
        paint.imageMask.SetNativeSize();
        paint.imagePreview.SetNativeSize();
    }
References Card.c_textureData, Card.ClearPaintSprite(), Layer.Close(), Card.GetPaintSprite(), Card.GetSprite(), PixelPaint.imageMask, PixelPaint.imagePreview, Card.material, onApply, Trait.owner, paint, CardRenderer.PlayAnime(), Card.PlaySound(), CardRenderer.RefreshSprite(), Card.renderer, Card.Split(), and PixelPaint.tex.
Member Data Documentation
layoutColors
GridLayoutGroup LayerPixelPaint.layoutColors
Definition at line 10 of file LayerPixelPaint.cs.
Referenced by OnInit().
onApply
Action LayerPixelPaint.onApply
Definition at line 14 of file LayerPixelPaint.cs.
Referenced by OnInit(), and SetCanvas().
paint
PixelPaint LayerPixelPaint.paint
Definition at line 8 of file LayerPixelPaint.cs.
Referenced by OnInit(), and SetCanvas().
picker
ColorPicker LayerPixelPaint.picker
Definition at line 12 of file LayerPixelPaint.cs.
Referenced by OnInit().
The documentation for this class was generated from the following file:
Elin/LayerPixelPaint.cs