Elin Decompiled Documentation: B83.Win32.Window Class Reference
B83.Win32.Window Class Reference
Public Member Functions
static bool EnumThreadWindows (uint dwThreadId, EnumThreadDelegate lpfn, IntPtr lParam)
static bool GetWindowRect (IntPtr hwnd, out RECT lpRect)
static bool IsWindowVisible (IntPtr hWnd)
Static Public Member Functions
static string GetClassName (IntPtr hWnd)
static string GetWindowText (IntPtr hWnd)
Private Member Functions
static int GetClassName (IntPtr hWnd, StringBuilder lpClassName, int nMaxCount)
static int GetWindowTextLength (IntPtr hWnd)
static int GetWindowText (IntPtr hWnd, StringBuilder lpString, int nMaxCount)
Detailed Description
Definition at line 7 of file Window.cs.
Member Function Documentation
EnumThreadWindows()
static bool B83.Win32.Window.EnumThreadWindows (uint dwThreadId, EnumThreadDelegate lpfn, IntPtr lParam)
Referenced by B83.Win32.UnityDragAndDropHook.InstallHook().
GetClassName() [1/2]
static string B83.Win32.Window.GetClassName (IntPtr hWnd) inline static
Definition at line 21 of file Window.cs.
    {
        StringBuilder stringBuilder = new StringBuilder(256);
        int className = GetClassName(hWnd, stringBuilder, 256);
        return stringBuilder.ToString(0, className);
    }
References B83.Win32.Window.GetClassName().
GetClassName() [2/2]
static int B83.Win32.Window.GetClassName (IntPtr hWnd, StringBuilder lpClassName, int nMaxCount) private
Referenced by B83.Win32.UnityDragAndDropHook.EnumCallback(), and B83.Win32.Window.GetClassName().
GetWindowRect()
static bool B83.Win32.Window.GetWindowRect (IntPtr hwnd, out RECT lpRect)
GetWindowText() [1/2]
static string B83.Win32.Window.GetWindowText (IntPtr hWnd) inline static
Definition at line 34 of file Window.cs.
    {
        int num = GetWindowTextLength(hWnd) + 2;
        StringBuilder stringBuilder = new StringBuilder(num);
        int windowText = GetWindowText(hWnd, stringBuilder, num);
        return stringBuilder.ToString(0, windowText);
    }
References B83.Win32.Window.GetWindowText(), and B83.Win32.Window.GetWindowTextLength().
GetWindowText() [2/2]
static int B83.Win32.Window.GetWindowText (IntPtr hWnd, StringBuilder lpString, int nMaxCount) private
Referenced by B83.Win32.Window.GetWindowText().
GetWindowTextLength()
static int B83.Win32.Window.GetWindowTextLength (IntPtr hWnd) private
Referenced by B83.Win32.Window.GetWindowText().
IsWindowVisible()
static bool B83.Win32.Window.IsWindowVisible (IntPtr hWnd)
Referenced by B83.Win32.UnityDragAndDropHook.EnumCallback().
The documentation for this class was generated from the following file:
Elin/Plugins.basecore/B83/Win32/Window.cs