Elin Decompiled Documentation: Expedition Class Reference
Expedition Class Reference
Public Member Functions
void SetOwner (FactionBranch _branch)
void OnCreate ()
void Start ()
void OnAdvanceHour ()
void End ()
Static Public Member Functions
static Expedition Create (Chara c, ExpeditionType type)
Static Public Member Functions inherited from EClass
static int rnd (int a)
static int curve (int a, int start, int step, int rate=75)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Public Attributes
int hours
int uidChara
ExpeditionType type
HomeResource.CostList costs = new HomeResource.CostList()
FactionBranch branch
Properties
Chara chara [get]
int MinHour [get]
int MaxHour [get]
string strType [get]
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Additional Inherited Members
Static Public Attributes inherited from EClass
static Core core
Detailed Description
Definition at line 4 of file Expedition.cs.
Member Function Documentation
Create()
static Expedition Expedition.Create (Chara c, ExpeditionType type) inline static
Definition at line 127 of file Expedition.cs.
    {
        Expedition expedition = new Expedition();
        expedition.uidChara = c.uid;
        expedition.type = type;
        expedition.SetOwner(c.homeBranch);
        expedition.OnCreate();
        return expedition;
    }
References Chara.homeBranch, OnCreate(), SetOwner(), type, and Card.uid.
Referenced by ListPeopleExpedition.OnList(), and Chara.TryWorkOutside().
End()
void Expedition.End () inline
Definition at line 88 of file Expedition.cs.
    {
        this.branch.expeditions.dict.Remove(this.uidChara);
        this.chara.MoveZone(this.chara.homeZone, ZoneTransition.EnterState.Auto);
        WidgetPopText.Say("expeditionEnd".lang(this.chara.Name, this.strType, null, null, null), FontColor.Default, null);
        this.branch.Log("bExpeditionEnd", this.chara, this.strType, null, null);
        if (this.chara.IsInActiveZone)
        {
            Msg.Say("bExpeditionEnd", this.chara, this.strType, null, null);
        }
        ExpeditionType expeditionType = this.type;
        if (expeditionType != ExpeditionType.Search)
        {
            if (expeditionType != ExpeditionType.Explore)
            {
                return;
            }
            this.chara.GetWorkSummary().progress = 100;
        }
        else
        {
            foreach (Zone zone in EClass.world.region.ListZonesInRadius(this.branch.owner, 10))
            {
                if (!zone.isKnown)
                {
                    zone.isKnown = true;
                    WidgetPopText.Say("discoverZone".lang(zone.Name, null, null, null, null), FontColor.Great, null);
                }
            }
            Zone zone2 = EClass.world.region.CreateRandomSite(this.chara.homeZone, 8, null, true, 0);
            if (zone2 != null)
            {
                zone2.isKnown = true;
                WidgetPopText.Say("discoverZone".lang(zone2.Name, null, null, null, null), FontColor.Great, null);
                return;
            }
        }
    }
References branch, chara, Region.CreateRandomSite(), ExpeditionManager.dict, FactionBranch.expeditions, Chara.GetWorkSummary(), Chara.homeZone, Chara.IsInActiveZone, Spatial.isKnown, Region.ListZonesInRadius(), FactionBranch.Log(), Chara.MoveZone(), Card.Name, Spatial.Name, WorkSummary.progress, World.region, Msg.Say(), WidgetPopText.Say(), strType, type, uidChara, and EClass.world.
Referenced by OnAdvanceHour().
OnAdvanceHour()
void Expedition.OnAdvanceHour () inline
Definition at line 79 of file Expedition.cs.
    {
        this.hours--;
        if (this.hours <= 0)
        {
            this.End();
        }
    }
References End(), and hours.
Referenced by ExpeditionManager.OnSimulateHour().
OnCreate()
void Expedition.OnCreate () inline
Definition at line 43 of file Expedition.cs.
    {
        HomeResourceManager resources = this.branch.resources;
        switch (this.type)
        {
        case ExpeditionType.Search:
            this.hours = 24;
            return;
        case ExpeditionType.Training:
            this.hours = 120;
            return;
        case ExpeditionType.Explore:
            this.hours = 10;
            return;
        case ExpeditionType.Hunt:
            this.hours = 10;
            return;
        default:
            this.hours = 24;
            return;
        }
    }
References branch, FactionBranch.resources, and type.
Referenced by Create().
SetOwner()
void Expedition.SetOwner (FactionBranch _branch) inline
Definition at line 38 of file Expedition.cs.
    {
        this.branch = _branch;
    }
Referenced by Create(), and ExpeditionManager.SetOwner().
Start()
void Expedition.Start () inline
Definition at line 66 of file Expedition.cs.
    {
        this.hours = Rand.Range(this.MinHour, this.MaxHour);
        this.costs.Pay();
        WidgetPopText.Say("expeditionStart".lang(this.chara.Name, this.strType, null, null, null), FontColor.Default, null);
        EClass.Branch.Log("bExpeditionStart", this.chara, this.strType, null, null);
        if (this.chara.IsInActiveZone)
        {
            Msg.Say("bExpeditionStart", this.chara, this.strType, null, null);
        }
        this.chara.MoveZone("somewhere");
    }
References EClass.Branch, chara, costs, Chara.IsInActiveZone, FactionBranch.Log(), MaxHour, MinHour, Chara.MoveZone(), Card.Name, Msg.Say(), WidgetPopText.Say(), and strType.
Referenced by ExpeditionManager.Add().
Member Data Documentation
branch
FactionBranch Expedition.branch
Definition at line 148 of file Expedition.cs.
Referenced by End(), and OnCreate().
costs
HomeResource.CostList Expedition.costs = new HomeResource.CostList()
Definition at line 146 of file Expedition.cs.
Referenced by ListPeopleExpedition.OnClick(), ListPeopleExpedition.SetSubText(), and Start().
hours
int Expedition.hours
Definition at line 138 of file Expedition.cs.
Referenced by OnAdvanceHour(), and Chara.TryWorkOutside().
type
ExpeditionType Expedition.type
Definition at line 144 of file Expedition.cs.
Referenced by Create(), End(), and OnCreate().
uidChara
int Expedition.uidChara
Definition at line 141 of file Expedition.cs.
Referenced by ExpeditionManager.Add(), and End().
Property Documentation
chara
Chara Expedition.chara get
Definition at line 6 of file Expedition.cs.
    {
        get
        {
            return RefChara.Get(this.uidChara);
        }
    }
Referenced by End(), and Start().
MaxHour
int Expedition.MaxHour get
Definition at line 22 of file Expedition.cs.
    {
        get
        {
            return (int)((float)this.hours * 1.2f);
        }
    }
Referenced by ListPeopleExpedition.SetSubText(), and Start().
MinHour
int Expedition.MinHour get
Definition at line 14 of file Expedition.cs.
    {
        get
        {
            return (int)((float)this.hours * 0.8f);
        }
    }
Referenced by ListPeopleExpedition.SetSubText(), and Start().
strType
string Expedition.strType get
Definition at line 30 of file Expedition.cs.
    {
        get
        {
            return ("ex" + this.type.ToString()).lang();
        }
    }
Referenced by End(), and Start().
The documentation for this class was generated from the following file:
Elin/Expedition.cs