Elin Decompiled Documentation: LayerNewZone Class Reference
LayerNewZone Class Reference
Public Member Functions
override void OnInit ()
override void OnKill ()
void OnClickExit ()
void OnClickSelectMembers ()
void Embark ()
Public Member Functions inherited from ELayer
override void OnBeforeAddLayer ()
void InitInspector ()
sealed override void Init ()
override void OnAfterAddLayer ()
void TryShowHelp ()
void AddLayerToUI (string id)
void TryShowHint (string _langHint=null)
void TalkHomeMemeber (string id)
void TalkMaid (string id)
override void OnRightClick ()
Public Member Functions inherited from Layer
virtual string GetTextHeader (Window window)
virtual bool HeaderIsListOf (int id)
virtual void Init ()
virtual void OnInit ()
virtual void OnAfterInit ()
virtual void ApplySkin ()
void ShowScreenLock (string id)
void UpdateInput ()
virtual void OnUpdateInput ()
virtual void OnRightClick ()
virtual bool OnBack ()
virtual void OnChangeLayer ()
virtual void OnCreate ()
void _AddLayer (string id)
Layer AddLayer (string id)
T AddLayer< T > ()
T AddLayer< T > (string id)
T AddLayerDontCloseOthers< T > ()
Layer AddLayerDontCloseOthers (Layer l)
T GetOrAddLayer< T > ()
virtual void OnBeforeAddLayer ()
virtual void OnAfterAddLayer ()
Layer AddLayer (Layer l)
void ToggleLayer (string id)
T ToggleLayer< T > (string id=null)
void WaitAndClose ()
void OnClickClose ()
virtual void Close ()
void CloseLayers ()
void RemoveLayers (bool removeImportant=false)
bool RemoveLayer< T > ()
void RemoveLayer (Layer l)
virtual void OnKill ()
Layer SetOnKill (Action action)
void DisableClose ()
void Delay (float duration=0.05f)
Layer SetDelay (float d)
Layer GetLayer (string id)
T GetLayer< T > (bool fromTop=false)
Layer GetTopLayer ()
void SwitchContent (int idWindow, int i)
virtual void OnSwitchContent (Window window)
Layer SetTitles (string langList, string idHeaderRow=null)
bool IsBlockWidgetClick ()
bool IsHideHud ()
bool IsAllowGeneralInput ()
bool IsUseBlur ()
bool IsPointerOnLayer ()
void ApplySkin ()
Public Attributes
UIMapSelector selector
UIButton buttonSelectMember
List< Chara > settlers = new List<Chara>()
Public Attributes inherited from Layer
Option option
UnityEvent onKill
Anime animeIn
Anime animeOut
bool closeOthers
bool defaultActionMode = true
Button screenLock
Layer parent
string idLayer
List< Layer > layers = new List<Layer>()
Vector2 lastParentPos
List< Window > windows = new List<Window>()
string langHint
Additional Inherited Members
Static Public Member Functions inherited from ELayer
static int rnd (int a)
Static Public Member Functions inherited from Layer
static T Create< T > ()
static T Create< T > (string path)
static Layer Create (string path)
Static Public Attributes inherited from Layer
static int skipInput
static bool closeOnRightClick
static bool rightClicked
static bool cancelKeyDown
static bool ignoreSounds
static Transform blurStopInstance
static string[] searchPath = new string[3] { "Layer", "Layer/Dialog", "Layer/LayerHome" }
Protected Member Functions inherited from ELayer
sealed override void _Close ()
sealed override void Kill ()
Protected Member Functions inherited from Layer
virtual void Awake ()
virtual void _Close ()
virtual void Kill ()
Protected Attributes inherited from Layer
RectTransform _rect
bool isDestroyed
Properties inherited from ELayer
static Core core [get]
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static FactionBranch Branch [get]
static Faction Home [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static CoreConfig config [get]
static GameSetting setting [get]
static ColorProfile Colors [get]
static SourceManager sources [get]
static World world [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
bool IsFloat [get]
virtual string IdHelp [get]
Properties inherited from Layer
Layer TopLayer [get]
string uid [get]
virtual RectTransform rectLayers [get]
virtual bool blockWidgetClick [get]
Detailed Description
Definition at line 3 of file LayerNewZone.cs.
Member Function Documentation
Embark()
void LayerNewZone.Embark () inline
Definition at line 33 of file LayerNewZone.cs.
    {
        ELayer.game.Save();
        Close();
        ActionMode.Sim.Activate();
        ELayer.screen.Focus(settlers[0]);
        Dialog d = Dialog.CreateNarration("embark", "embark");
        d.list.AddButton(null, Lang.Get("ok"), delegate
        {
            Chara chara = CharaGen.Create("chicken");
            chara.SetFaction(ELayer.Home);
            ELayer._zone.AddCard(chara, settlers[0].pos);
            ELayer.Branch.Recruit(chara);
            d.Close();
        });
        ELayer.ui.AddLayer(d);
        ELayer._zone.RefreshBGM();
        ELayer.Sound.PlayBGM("jingle_embark");
    }
References ELayer._zone, ActionMode.Activate(), UIButtonList.AddButton(), Layer.Close(), Dialog.CreateNarration(), BaseGameScreen.Focus(), ELayer.game, Lang.Get(), Dialog.list, Zone.RefreshBGM(), Game.Save(), ELayer.screen, settlers, ActionMode.Sim, ELayer.Sound, and ELayer.ui.
Referenced by OnClickSelectMembers().
OnClickExit()
void LayerNewZone.OnClickExit () inline
Definition at line 20 of file LayerNewZone.cs.
    {
        Close();
        ELayer.player.MoveZone(ELayer.pc.currentZone);
        ActionMode.EloMap.Activate();
    }
References ActionMode.Activate(), Layer.Close(), Chara.currentZone, ActionMode.EloMap, Player.MoveZone(), ELayer.pc, and ELayer.player.
OnClickSelectMembers()
void LayerNewZone.OnClickSelectMembers () inline
Definition at line 27 of file LayerNewZone.cs.
    {
        settlers.Clear();
        ELayer.ui.AddLayer(LayerPeople.CreateSelectEmbarkMembers(settlers).SetOnConfirm(Embark));
    }
References LayerPeople.CreateSelectEmbarkMembers(), Embark(), LayerPeople.SetOnConfirm(), settlers, and ELayer.ui.
OnInit()
override void LayerNewZone.OnInit () inline virtual
Reimplemented from Layer.
Definition at line 11 of file LayerNewZone.cs.
    {
        buttonSelectMember.SetActive(ELayer._zone.IsPlayerFaction);
    }
References ELayer._zone, buttonSelectMember, and Spatial.IsPlayerFaction.
OnKill()
override void LayerNewZone.OnKill () inline virtual
Reimplemented from Layer.
Definition at line 16 of file LayerNewZone.cs.
    {
    }
Member Data Documentation
buttonSelectMember
UIButton LayerNewZone.buttonSelectMember
Definition at line 7 of file LayerNewZone.cs.
Referenced by OnInit().
selector
UIMapSelector LayerNewZone.selector
Definition at line 5 of file LayerNewZone.cs.
settlers
List<Chara> LayerNewZone.settlers = new List<Chara>()
Definition at line 9 of file LayerNewZone.cs.
Referenced by Embark(), and OnClickSelectMembers().
The documentation for this class was generated from the following file:
Elin/LayerNewZone.cs