Elin Decompiled Documentation: IO Class Reference
IO Class Reference
Public Types
enum Compression { LZ4 , None }
Static Public Member Functions
static void OnError (object sender, Newtonsoft.Json.Serialization.ErrorEventArgs args)
static void PrintLog ()
static string GetJSON (object obj)
static T LoadJSON< T > (string json)
static void SaveFile (string path, object obj, bool compress=false, JsonSerializerSettings setting=null)
static void SaveText (string path, string text)
static void SaveTextArray (string path, string[] text)
static T LoadFile< T > (string path, bool compress=false, JsonSerializerSettings setting=null)
static T LoadStreamJson< T > (MemoryStream stream, JsonSerializerSettings setting=null)
static void WriteLZ4 (string _path, byte[] _bytes, Compression compression=Compression.None)
static byte[] ReadLZ4 (string _path, int size, Compression compression)
static byte[] ReadLZ4 (byte[] bytes)
static bool IsCompressed (string path)
static void Compress (string path, string text)
static string Decompress (string path)
static void CopyDir (string sourceDirectory, string targetDirectory, Func< string, bool > funcExclude=null)
static void _CopyDir (DirectoryInfo source, DirectoryInfo target, Func< string, bool > funcExclude=null)
static void Copy (string fromPath, string toPath)
static void CopyAs (string fromPath, string toPath)
static void CopyAll (string fromPath, string toPath, bool overwrite=true)
static void DeleteFile (string path)
static void DeleteFiles (string path)
static void CreateDirectory (string path)
static void DeleteDirectory (string path)
static T Duplicate< T > (T t)
static void CreateTempDirectory (string path=null)
static void DeleteTempDirectory (string path=null)
static T LoadObject< T > (FileInfo file, object option=null)
static T LoadObject< T > (string _path, object option=null)
static void SavePNG (Texture2D tex, string _path)
static Texture2D LoadPNG (string _path, FilterMode filter=FilterMode.Point)
static byte[] ReadPngFile (string _path)
static T DeepCopy< T > (T target)
static string[] LoadTextArray (string _path)
static string LoadText (string _path)
Static Public Attributes
static string log
static JsonSerializerSettings jsReadGeneral
static JsonSerializerSettings jsWriteGeneral
static JsonSerializerSettings jsWriteConfig
static Formatting formatting = Formatting.Indented
static TextureImportSetting.Data importSetting = new TextureImportSetting.Data()
static JsonSerializerSettings dpSetting
static Formatting dpFormat = Formatting.Indented
Properties
static string TempPath [get]
Detailed Description
Definition at line 10 of file IO.cs.
Member Enumeration Documentation
Compression
enum IO.Compression
Enumerator
LZ4
None
Definition at line 12 of file IO.cs.
    {
        LZ4,
        None
    }
Member Function Documentation
_CopyDir()
static void IO._CopyDir (DirectoryInfo source, DirectoryInfo target, Func< string, bool > funcExclude = null) inline static
Definition at line 259 of file IO.cs.
    {
        if (funcExclude == null || !funcExclude(source.Name))
        {
            Directory.CreateDirectory(target.FullName);
            FileInfo[] files = source.GetFiles();
            foreach (FileInfo fileInfo in files)
            {
                fileInfo.CopyTo(Path.Combine(target.FullName, fileInfo.Name), overwrite: true);
            }
            DirectoryInfo[] directories = source.GetDirectories();
            foreach (DirectoryInfo directoryInfo in directories)
            {
                DirectoryInfo target2 = target.CreateSubdirectory(directoryInfo.Name);
                _CopyDir(directoryInfo, target2, funcExclude);
            }
        }
    }
References _CopyDir().
Referenced by _CopyDir(), and CopyDir().
Compress()
static void IO.Compress (string path, string text) inline static
Definition at line 217 of file IO.cs.
    {
        Debug.Log("Compressing: " + path);
        using FileStream innerStream = new FileStream(path, FileMode.Create);
        using LZ4Stream stream = new LZ4Stream(innerStream, LZ4StreamMode.Compress);
        using StreamWriter streamWriter = new StreamWriter(stream);
        streamWriter.Write(text);
    }
References Debug.
Referenced by SaveFile().
Copy()
static void IO.Copy (string fromPath, string toPath) inline static
Definition at line 278 of file IO.cs.
    {
        if (!File.Exists(fromPath))
        {
            Debug.Log("File does not exist:" + fromPath);
            return;
        }
        FileInfo fileInfo = new FileInfo(fromPath);
        DirectoryInfo directoryInfo = new DirectoryInfo(toPath);
        if (!Directory.Exists(directoryInfo.FullName))
        {
            CreateDirectory(directoryInfo.FullName);
        }
        File.Copy(fileInfo.FullName, directoryInfo.FullName + "/" + fileInfo.Name, overwrite: true);
    }
References CreateDirectory(), and Debug.
CopyAll()
static void IO.CopyAll (string fromPath, string toPath, bool overwrite = true) inline static
Definition at line 306 of file IO.cs.
    {
        CreateDirectory(toPath);
        string[] directories = Directory.GetDirectories(fromPath, "*", SearchOption.AllDirectories);
        for (int i = 0; i < directories.Length; i++)
        {
            Directory.CreateDirectory(directories[i].Replace(fromPath, toPath));
        }
        directories = Directory.GetFiles(fromPath, "*.*", SearchOption.AllDirectories);
        foreach (string text in directories)
        {
            string text2 = text.Replace(fromPath, toPath);
            if (overwrite || !File.Exists(text2))
            {
                File.Copy(text, text2, overwrite: true);
            }
        }
    }
References CreateDirectory().
CopyAs()
static void IO.CopyAs (string fromPath, string toPath) inline static
Definition at line 294 of file IO.cs.
    {
        if (!File.Exists(fromPath))
        {
            Debug.LogError("File does not exist:" + fromPath);
        }
        else
        {
            File.Copy(fromPath, toPath, overwrite: true);
        }
    }
References Debug.
CopyDir()
static void IO.CopyDir (string sourceDirectory, string targetDirectory, Func< string, bool > funcExclude = null) inline static
Definition at line 245 of file IO.cs.
    {
        DirectoryInfo directoryInfo = new DirectoryInfo(sourceDirectory);
        DirectoryInfo target = new DirectoryInfo(targetDirectory);
        if (!directoryInfo.Exists)
        {
            Debug.Log("Source dir doesn't exist:" + directoryInfo.FullName);
        }
        else
        {
            _CopyDir(directoryInfo, target, funcExclude);
        }
    }
References _CopyDir(), and Debug.
CreateDirectory()
static void IO.CreateDirectory (string path) inline static
Definition at line 345 of file IO.cs.
    {
        if (!Directory.Exists(path))
        {
            Directory.CreateDirectory(path);
        }
    }
Referenced by Copy(), CopyAll(), CreateTempDirectory(), SaveFile(), SaveText(), and SaveTextArray().
CreateTempDirectory()
static void IO.CreateTempDirectory (string path = null) inline static
Definition at line 379 of file IO.cs.
    {
        CreateDirectory(path ?? TempPath);
    }
References CreateDirectory().
Decompress()
static string IO.Decompress (string path) inline static
Definition at line 226 of file IO.cs.
    {
        try
        {
            using FileStream innerStream = new FileStream(path, FileMode.Open);
            using LZ4Stream stream = new LZ4Stream(innerStream, LZ4StreamMode.Decompress);
            using StreamReader streamReader = new StreamReader(stream);
            return streamReader.ReadToEnd();
        }
        catch (Exception message)
        {
            Debug.Log(message);
        }
        Debug.Log("Cannot decompress:" + IsCompressed(path) + "/" + path);
        string text = File.ReadAllText(path);
        Debug.Log(text);
        return text.IsEmpty("");
    }
References Debug, and IsCompressed().
Referenced by LoadFile< T >().
DeepCopy< T >()
static T IO.DeepCopy< T > (T target) inline static
Definition at line 477 of file IO.cs.
    {
        return JsonConvert.DeserializeObject<T>(JsonConvert.SerializeObject(target, dpFormat, dpSetting), dpSetting);
    }
DeleteDirectory()
static void IO.DeleteDirectory (string path) inline static
Definition at line 353 of file IO.cs.
    {
        path = path.Replace("\\\\?\\", "");
        if (Directory.Exists(path))
        {
            DirectoryInfo directoryInfo = new DirectoryInfo(path);
            try
            {
                new FileIOPermission(FileIOPermissionAccess.AllAccess, path).Demand();
            }
            catch (SecurityException ex)
            {
                Debug.Log(ex.ToString());
            }
            if (directoryInfo.Exists)
            {
                directoryInfo.Delete(recursive: true);
            }
        }
    }
References Debug.
Referenced by DeleteTempDirectory().
DeleteFile()
static void IO.DeleteFile (string path) inline static
Definition at line 325 of file IO.cs.
    {
        if (File.Exists(path))
        {
            File.Delete(path);
        }
    }
DeleteFiles()
static void IO.DeleteFiles (string path) inline static
Definition at line 333 of file IO.cs.
    {
        if (Directory.Exists(path))
        {
            FileInfo[] files = new DirectoryInfo(path).GetFiles();
            for (int i = 0; i < files.Length; i++)
            {
                files[i].Delete();
            }
        }
    }
DeleteTempDirectory()
static void IO.DeleteTempDirectory (string path = null) inline static
Definition at line 384 of file IO.cs.
    {
        DeleteDirectory(path ?? TempPath);
    }
References DeleteDirectory().
Duplicate< T >()
static T IO.Duplicate< T > (T t) inline static
Definition at line 374 of file IO.cs.
    {
        return JsonConvert.DeserializeObject<T>(JsonConvert.SerializeObject(t, formatting, jsWriteGeneral), jsReadGeneral);
    }
GetJSON()
static string IO.GetJSON (object obj) inline static
Definition at line 79 of file IO.cs.
    {
        return JsonConvert.SerializeObject(obj, formatting, jsWriteGeneral);
    }
IsCompressed()
static bool IO.IsCompressed (string path) inline static
Definition at line 202 of file IO.cs.
    {
        byte[] array;
        using (BinaryReader binaryReader = new BinaryReader(File.OpenRead(path)))
        {
            binaryReader.BaseStream.Seek(0L, SeekOrigin.Begin);
            array = binaryReader.ReadBytes(4);
        }
        if (array.Length > 3 && array[0] == 123 && array[1] == 13 && array[2] == 10 && array[3] == 32)
        {
            return false;
        }
        return true;
    }
Referenced by Decompress(), and LoadFile< T >().
LoadFile< T >()
static T IO.LoadFile< T > (string path, bool compress = false, JsonSerializerSettings setting = null) inline static
Definition at line 118 of file IO.cs.
    {
        if (!File.Exists(path))
        {
            Debug.Log("File does not exist:" + path);
            return default(T);
        }
        string value = (IsCompressed(path) ? Decompress(path) : File.ReadAllText(path));
        Debug.Log("#io LoadFile;" + path);
        return JsonConvert.DeserializeObject<T>(value, setting ?? jsReadGeneral);
    }
References Debug, Decompress(), and IsCompressed().
LoadJSON< T >()
static T IO.LoadJSON< T > (string json) inline static
Definition at line 84 of file IO.cs.
    {
        return JsonConvert.DeserializeObject<T>(json, jsReadGeneral);
    }
LoadObject< T >() [1/2]
static T IO.LoadObject< T > (FileInfo file, object option = null) inline static
Type Constraints
T : UnityEngine.Object
Definition at line 389 of file IO.cs.
                                                                               : UnityEngine.Object
    {
        return LoadObject<T>(file.FullName, option);
    }
LoadObject< T >() [2/2]
static T IO.LoadObject< T > (string _path, object option = null) inline static
Type Constraints
T : UnityEngine.Object
Definition at line 394 of file IO.cs.
                                                                              : UnityEngine.Object
    {
        Type typeFromHandle = typeof(T);
        if (typeFromHandle == typeof(Sprite))
        {
            SpriteLoadOption spriteLoadOption = option as SpriteLoadOption;
            Texture2D texture2D = LoadPNG(_path);
            if (!texture2D)
            {
                return null;
            }
            return Sprite.Create(texture2D, new Rect(0f, 0f, texture2D.width, texture2D.height), spriteLoadOption?.pivot ?? new Vector2(0.5f, 0f), 100f) as T;
        }
        if (typeFromHandle == typeof(Texture2D))
        {
            return LoadPNG(_path) as T;
        }
        if (typeof(ExcelData).IsAssignableFrom(typeFromHandle))
        {
            T val = Activator.CreateInstance<T>();
            (val as ExcelData).path = _path;
            return val;
        }
        if (typeFromHandle == typeof(TextData))
        {
            return new TextData
            {
                lines = File.ReadAllLines(_path)
            } as T;
        }
        return null;
    }
References LoadPNG(), and SpriteLoadOption.pivot.
LoadPNG()
static Texture2D IO.LoadPNG (string _path, FilterMode filter = FilterMode::Point) inline static
Definition at line 433 of file IO.cs.
    {
        if (!File.Exists(_path))
        {
            return null;
        }
        byte[] array = ReadPngFile(_path);
        int num = 16;
        int num2 = 0;
        for (int i = 0; i < 4; i++)
        {
            if (num + 1 < array.Length)
            {
                num2 = num2 * 256 + array[num++];
            }
        }
        int num3 = 0;
        for (int j = 0; j < 4; j++)
        {
            if (num + 1 < array.Length)
            {
                num3 = num3 * 256 + array[num++];
            }
        }
        TextureImportSetting.Data data = (TextureImportSetting.Instance ? TextureImportSetting.Instance.data : importSetting);
        Texture2D texture2D = new Texture2D(num2, num3, data.format, data.mipmap, data.linear);
        texture2D.LoadImage(array);
        texture2D.wrapMode = data.wrapMode;
        texture2D.filterMode = filter;
        texture2D.anisoLevel = data.anisoLevel;
        texture2D.mipMapBias = data.mipmapBias;
        return texture2D;
    }
References TextureImportSetting.Data.anisoLevel, TextureImportSetting.Data.format, TextureImportSetting.Data.linear, TextureImportSetting.Data.mipmap, TextureImportSetting.Data.mipmapBias, ReadPngFile(), and TextureImportSetting.Data.wrapMode.
Referenced by LoadObject< T >().
LoadStreamJson< T >()
static T IO.LoadStreamJson< T > (MemoryStream stream, JsonSerializerSettings setting = null) inline static
Definition at line 130 of file IO.cs.
    {
        stream.Position = 0L;
        string value = "";
        using (StreamReader streamReader = new StreamReader(stream))
        {
            value = streamReader.ReadToEnd();
        }
        return JsonConvert.DeserializeObject<T>(value, setting ?? jsReadGeneral);
    }
LoadText()
static string IO.LoadText (string _path) inline static
Definition at line 496 of file IO.cs.
    {
        string[] array = LoadTextArray(_path);
        string text = "";
        string[] array2 = array;
        foreach (string text2 in array2)
        {
            text = text + text2 + Environment.NewLine;
        }
        return text;
    }
References LoadTextArray().
LoadTextArray()
static string[] IO.LoadTextArray (string _path) inline static
Definition at line 482 of file IO.cs.
    {
        if (!File.Exists(_path))
        {
            _path += ".txt";
            if (!File.Exists(_path))
            {
                Debug.Log(_path);
                return new string[0];
            }
        }
        return File.ReadAllLines(_path);
    }
References Debug.
Referenced by LoadText().
OnError()
static void IO.OnError (object sender, Newtonsoft::Json::Serialization::ErrorEventArgs args) inline static
Definition at line 66 of file IO.cs.
    {
    }
PrintLog()
static void IO.PrintLog () inline static
Definition at line 70 of file IO.cs.
    {
        if (!log.IsEmpty())
        {
            Debug.LogWarning(log);
            log = null;
        }
    }
References Debug.
ReadLZ4() [1/2]
static byte[] IO.ReadLZ4 (byte[] bytes) inline static
Definition at line 189 of file IO.cs.
    {
        try
        {
            return LZ4Codec.Unwrap(bytes);
        }
        catch
        {
            Debug.Log("Exception: Failed to unwrap:");
            return bytes;
        }
    }
References Debug.
ReadLZ4() [2/2]
static byte[] IO.ReadLZ4 (string _path, int size, Compression compression) inline static
Definition at line 159 of file IO.cs.
    {
        for (int i = 0; i < 5; i++)
        {
            string text = _path + ((i == 0) ? "" : (".b" + i));
            if (!File.Exists(text))
            {
                Debug.Log("Couldn't find:" + text);
                continue;
            }
            byte[] array = File.ReadAllBytes(text);
            if (compression == Compression.LZ4)
            {
                try
                {
                    return ReadLZ4(array);
                }
                catch (Exception message)
                {
                    Debug.Log(message);
                }
            }
            if (array.Length == size)
            {
                return array;
            }
        }
        return null;
    }
References Debug, and ReadLZ4().
Referenced by ReadLZ4().
ReadPngFile()
static byte[] IO.ReadPngFile (string _path) inline static
Definition at line 467 of file IO.cs.
    {
        FileStream fileStream = new FileStream(_path, FileMode.Open, FileAccess.Read, FileShare.ReadWrite);
        BinaryReader binaryReader = new BinaryReader(fileStream);
        byte[] result = binaryReader.ReadBytes((int)binaryReader.BaseStream.Length);
        binaryReader.Close();
        fileStream.Close();
        return result;
    }
Referenced by LoadPNG().
SaveFile()
static void IO.SaveFile (string path, object obj, bool compress = false, JsonSerializerSettings setting = null) inline static
Definition at line 89 of file IO.cs.
    {
        string text = JsonConvert.SerializeObject(obj, formatting, setting ?? jsWriteGeneral);
        CreateDirectory(Path.GetDirectoryName(path));
        Debug.Log("#io SaveFile;" + path);
        if (compress)
        {
            Compress(path, text);
        }
        else
        {
            File.WriteAllText(path, text);
        }
    }
References Compress(), CreateDirectory(), and Debug.
SavePNG()
static void IO.SavePNG (Texture2D tex, string _path) inline static
Definition at line 427 of file IO.cs.
    {
        byte[] bytes = tex.EncodeToPNG();
        File.WriteAllBytes(_path, bytes);
    }
SaveText()
static void IO.SaveText (string path, string text) inline static
Definition at line 104 of file IO.cs.
    {
        CreateDirectory(Path.GetDirectoryName(path));
        Debug.Log("#io SaveFile;" + path);
        File.WriteAllText(path, text);
    }
References CreateDirectory(), and Debug.
SaveTextArray()
static void IO.SaveTextArray (string path, string[] text) inline static
Definition at line 111 of file IO.cs.
    {
        CreateDirectory(Path.GetDirectoryName(path));
        Debug.Log("#io SaveFile;" + path);
        File.WriteAllLines(path, text);
    }
References CreateDirectory(), and Debug.
WriteLZ4()
static void IO.WriteLZ4 (string _path, byte[] _bytes, Compression compression = Compression::None) inline static
Definition at line 141 of file IO.cs.
    {
        byte[] bytes = ((compression == Compression.LZ4) ? LZ4Codec.Wrap(_bytes, 0, _bytes.Length) : _bytes);
        for (int i = 0; i < 5; i++)
        {
            string path = _path + ((i == 0) ? "" : (".b" + i));
            try
            {
                File.WriteAllBytes(path, bytes);
                break;
            }
            catch (Exception message)
            {
                Debug.Log(message);
            }
        }
    }
References Debug.
Member Data Documentation
dpFormat
Formatting IO.dpFormat = Formatting.Indented static
Definition at line 62 of file IO.cs.
dpSetting
JsonSerializerSettings IO.dpSetting static
Initial value:
= new JsonSerializerSettings
    {
        NullValueHandling = NullValueHandling.Ignore,
        DefaultValueHandling = DefaultValueHandling.Include,
        PreserveReferencesHandling = PreserveReferencesHandling.Objects,
        TypeNameHandling = TypeNameHandling.Auto,
        Error = OnError
    }
Definition at line 53 of file IO.cs.
formatting
Formatting IO.formatting = Formatting.Indented static
Definition at line 49 of file IO.cs.
importSetting
TextureImportSetting.Data IO.importSetting = new TextureImportSetting.Data() static
Definition at line 51 of file IO.cs.
jsReadGeneral
JsonSerializerSettings IO.jsReadGeneral static
Initial value:
= new JsonSerializerSettings
    {
        NullValueHandling = NullValueHandling.Ignore,
        DefaultValueHandling = DefaultValueHandling.Ignore,
        PreserveReferencesHandling = PreserveReferencesHandling.Objects,
        TypeNameHandling = TypeNameHandling.Auto,
        Error = OnError
    }
Definition at line 20 of file IO.cs.
jsWriteConfig
JsonSerializerSettings IO.jsWriteConfig static
Initial value:
= new JsonSerializerSettings
    {
        NullValueHandling = NullValueHandling.Ignore,
        DefaultValueHandling = DefaultValueHandling.Populate,
        PreserveReferencesHandling = PreserveReferencesHandling.Objects,
        TypeNameHandling = TypeNameHandling.Auto,
        ContractResolver = ShouldSerializeContractResolver.Instance,
        Error = OnError
    }
Definition at line 39 of file IO.cs.
jsWriteGeneral
JsonSerializerSettings IO.jsWriteGeneral static
Initial value:
= new JsonSerializerSettings
    {
        NullValueHandling = NullValueHandling.Ignore,
        DefaultValueHandling = DefaultValueHandling.Ignore,
        PreserveReferencesHandling = PreserveReferencesHandling.Objects,
        TypeNameHandling = TypeNameHandling.Auto,
        ContractResolver = ShouldSerializeContractResolver.Instance,
        Error = OnError
    }
Definition at line 29 of file IO.cs.
log
string IO.log static
Definition at line 18 of file IO.cs.
Property Documentation
TempPath
string IO.TempPath static get
Definition at line 64 of file IO.cs.
The documentation for this class was generated from the following file:
Elin/Plugins.basecore/IO.cs