Elin Decompiled Documentation: PartialMapMenu Class Reference
PartialMapMenu Class Reference
Public Member Functions
void Init ()
void Deactivate ()
void SetVisible (bool visible)
void DestorySprites ()
void RefreshOptions ()
void Refresh ()
void RefreshCategory (DirectoryInfo dir=null)
void OpenFolder ()
Static Public Member Functions
static void Activate ()
Static Public Member Functions inherited from EMono
static int rnd (int a)
Public Attributes
GameObject goMain
GameObject goCat
GameObject goOption
UIList listCat
UIList listCatSub
UIDynamicList list
CanvasGroup cg
UIButton buttonSave
UIButton buttonEdit
UIButton buttonDelete
UIButton toggleRotate
UIButton toggleIgnoreBlock
Dictionary< string, Sprite > dictSprite = new Dictionary<string, Sprite>()
DirectoryInfo rootDir
Static Public Attributes
static PartialMapMenu Instance
static DirectoryInfo lastDir
static DirectoryInfo lastDirSub
Static Public Attributes inherited from EMono
static Core core
Properties
AM_Copy am [get]
DirectoryInfo dir [get]
bool IsEditor [get]
PartialMap partial [get]
Properties inherited from EMono
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SoundManager Sound [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static CoreDebug debug [get]
Detailed Description
Definition at line 6 of file PartialMapMenu.cs.
Member Function Documentation
Activate()
static void PartialMapMenu.Activate () inline static
Definition at line 50 of file PartialMapMenu.cs.
    {
        if (!Instance)
        {
            Instance = Util.Instantiate<PartialMapMenu>("UI/BuildMenu/PartialMapMenu", EMono.ui);
            Instance.Init();
        }
        Instance.Refresh();
        MapPiece.CacheMap.Clear();
    }
References MapPiece.CacheMap, Init(), Instance, Refresh(), and EMono.ui.
Referenced by AM_Copy.OnActivate().
Deactivate()
void PartialMapMenu.Deactivate () inline
Definition at line 84 of file PartialMapMenu.cs.
    {
        DestorySprites();
        Object.DestroyImmediate(Instance.gameObject);
    }
References DestorySprites(), and Instance.
Referenced by AM_Copy.OnDeactivate().
DestorySprites()
void PartialMapMenu.DestorySprites () inline
Definition at line 96 of file PartialMapMenu.cs.
    {
        foreach (Sprite value in dictSprite.Values)
        {
            Object.Destroy(value.texture);
            Object.Destroy(value);
        }
        dictSprite.Clear();
    }
References dictSprite.
Referenced by Deactivate(), AM_Copy.OnSave(), and AM_Copy.RefreshMenu().
Init()
void PartialMapMenu.Init () inline
Definition at line 61 of file PartialMapMenu.cs.
    {
        rootDir = new DirectoryInfo(CorePath.MapPieceSaveUser);
        goCat.SetActive(IsEditor);
        RefreshOptions();
        if (!IsEditor)
        {
            return;
        }
        RefreshCategory();
        if (lastDir != null)
        {
            listCat.Select((DirectoryInfo a) => a.FullName == lastDir.FullName);
            am.dir = lastDir;
        }
        if (lastDirSub != null)
        {
            RefreshCategory(lastDir);
            listCatSub.Select((DirectoryInfo a) => a.FullName == lastDirSub.FullName);
            am.dir = lastDirSub;
        }
    }
References goCat, IsEditor, lastDir, lastDirSub, listCat, listCatSub, RefreshCategory(), RefreshOptions(), and rootDir.
Referenced by Activate().
OpenFolder()
void PartialMapMenu.OpenFolder () inline
Definition at line 253 of file PartialMapMenu.cs.
    {
        Util.ShowExplorer(CorePath.MapPieceSave + "Test");
    }
Refresh()
void PartialMapMenu.Refresh () inline
Definition at line 124 of file PartialMapMenu.cs.
    {
        list.callbacks = new UIList.Callback<MapMetaData, ButtonGrid>
        {
            onClick = delegate(MapMetaData a, ButtonGrid b)
            {
                SE.Click();
                am.Import(a.path);
                am.partialMap.name = a.name;
            },
            onRedraw = delegate(MapMetaData a, ButtonGrid b, int i)
            {
                string path = a.path.GetFullFileNameWithoutExtension() + ".txt";
                if (File.Exists(path))
                {
                    string str = File.ReadAllText(path);
                    if (!str.IsEmpty())
                    {
                        a.name = str;
                    }
                }
                if (a.name.IsEmpty())
                {
                    a.name = "unknown";
                }
                b.mainText.SetText(IsEditor ? new FileInfo(a.path).Name : a.name);
                b.subText.text = Lang._currency(a.partial.value);
                Sprite sprite = dictSprite.TryGetValue(a.path);
                if (!sprite)
                {
                    string path2 = a.path.GetFullFileNameWithoutExtension() + ".jpg";
                    if (File.Exists(path2))
                    {
                        Texture2D texture2D = new Texture2D(1, 1);
                        byte[] source = File.ReadAllBytes(path2);
                        texture2D.LoadImage(source.ToArray());
                        sprite = Sprite.Create(texture2D, new Rect(0f, 0f, texture2D.width, texture2D.height), new Vector2(0.5f, 0.5f));
                        b.icon.sprite = sprite;
                        dictSprite[a.path] = sprite;
                    }
                }
                if ((bool)sprite)
                {
                    b.icon.sprite = sprite;
                }
                UIButton componentInDirectChildren = b.GetComponentInDirectChildren<UIButton>();
                componentInDirectChildren.SetActive(IsEditor);
                componentInDirectChildren.SetOnClick(delegate
                {
                    SE.Click();
                    am.overwritePath = a.path;
                    am.RefreshMenu(show: false);
                });
            },
            onList = delegate
            {
                foreach (FileInfo item in dir.GetFiles().Concat(MOD.listPartialMaps))
                {
                    if (item.Name.EndsWith(".mp"))
                    {
                        MapMetaData metaData = Map.GetMetaData(item.FullName);
                        if (metaData != null && metaData.partial != null)
{
                            list.Add(metaData);
                        }
                    }
                }
            }
        };
        list.List();
    }
References am, dictSprite, dir, Map.GetMetaData(), AM_Copy.Import(), IsEditor, list, MapMetaData.name, MapMetaData.partial, MapMetaData.path, AM_Copy.RefreshMenu(), and PartialMap.value.
Referenced by Activate(), AM_Copy.OnSave(), RefreshCategory(), and AM_Copy.RefreshMenu().
RefreshCategory()
void PartialMapMenu.RefreshCategory (DirectoryInfo dir = null) inline
Definition at line 196 of file PartialMapMenu.cs.
    {
        UIList _listCat = listCat;
        bool isMain = true;
        if (dir == null)
        {
            dir = rootDir;
        }
        if (dir.FullName != rootDir.FullName)
        {
            _listCat = listCatSub;
            isMain = false;
        }
        _listCat.Clear();
        _listCat.callbacks = new UIList.Callback<DirectoryInfo, UIButton>
        {
            onClick = delegate(DirectoryInfo a, UIButton b)
            {
                SE.Click();
                _listCat.Select(a);
                am.dir = a;
                if (isMain)
                {
                    lastDir = (lastDirSub = a);
                    RefreshCategory(a);
                }
                else
                {
                    lastDirSub = a;
                }
                Refresh();
            },
            onInstantiate = delegate(DirectoryInfo a, UIButton b)
            {
                int num = 0;
                FileInfo[] files = a.GetFiles("*.mp", SearchOption.AllDirectories);
                for (int i = 0; i < files.Length; i++)
                {
                    _ = files[i];
                    num++;
                }
                b.mainText.text = ((a == dir && !isMain) ? "(Root)" : (a.Name + "(" + num + ")"));
            },
            onList = delegate
            {
                _listCat.Add(isMain ? rootDir : dir);
                DirectoryInfo[] array = (isMain ? new DirectoryInfo(CorePath.MapPieceSave).GetDirectories() : dir.GetDirectories());
                foreach (DirectoryInfo o in array)
                {
                    _listCat.Add(o);
                }
            }
        };
        _listCat.List();
        listCatSub.SetActive(listCatSub.items.Count > 1);
    }
References dir, lastDir, lastDirSub, listCat, listCatSub, Refresh(), RefreshCategory(), and rootDir.
Referenced by Init(), AM_Copy.OnSave(), and RefreshCategory().
RefreshOptions()
void PartialMapMenu.RefreshOptions () inline
Definition at line 106 of file PartialMapMenu.cs.
    {
        goOption.SetActive(IsEditor && partial != null);
        if (partial != null)
        {
            toggleRotate.SetToggle(partial.allowRotate, delegate(bool on)
            {
                partial.allowRotate = on;
                partial.Update();
            });
            toggleIgnoreBlock.SetToggle(partial.ignoreBlock, delegate(bool on)
            {
                partial.ignoreBlock = on;
                partial.Update();
            });
        }
    }
References PartialMap.allowRotate, goOption, PartialMap.ignoreBlock, IsEditor, partial, toggleIgnoreBlock, toggleRotate, and PartialMap.Update().
Referenced by Init(), and SetVisible().
SetVisible()
void PartialMapMenu.SetVisible (bool visible) inline
Definition at line 90 of file PartialMapMenu.cs.
    {
        RefreshOptions();
        goMain.SetActive(visible);
    }
References goMain, and RefreshOptions().
Referenced by AM_Copy.RefreshMenu().
Member Data Documentation
buttonDelete
UIButton PartialMapMenu.buttonDelete
Definition at line 32 of file PartialMapMenu.cs.
Referenced by AM_Copy.RefreshMenu().
buttonEdit
UIButton PartialMapMenu.buttonEdit
Definition at line 30 of file PartialMapMenu.cs.
Referenced by AM_Copy.RefreshMenu().
buttonSave
UIButton PartialMapMenu.buttonSave
Definition at line 28 of file PartialMapMenu.cs.
Referenced by AM_Copy.RefreshMenu().
cg
CanvasGroup PartialMapMenu.cg
Definition at line 26 of file PartialMapMenu.cs.
dictSprite
Dictionary<string, Sprite> PartialMapMenu.dictSprite = new Dictionary<string, Sprite>()
Definition at line 38 of file PartialMapMenu.cs.
Referenced by DestorySprites(), and Refresh().
goCat
GameObject PartialMapMenu.goCat
Definition at line 16 of file PartialMapMenu.cs.
Referenced by Init().
goMain
GameObject PartialMapMenu.goMain
Definition at line 14 of file PartialMapMenu.cs.
Referenced by SetVisible().
goOption
GameObject PartialMapMenu.goOption
Definition at line 18 of file PartialMapMenu.cs.
Referenced by RefreshOptions().
Instance
PartialMapMenu PartialMapMenu.Instance static
Definition at line 8 of file PartialMapMenu.cs.
Referenced by Activate(), and Deactivate().
lastDir
DirectoryInfo PartialMapMenu.lastDir static
Definition at line 10 of file PartialMapMenu.cs.
Referenced by Init(), and RefreshCategory().
lastDirSub
DirectoryInfo PartialMapMenu.lastDirSub static
Definition at line 12 of file PartialMapMenu.cs.
Referenced by Init(), and RefreshCategory().
list
UIDynamicList PartialMapMenu.list
Definition at line 24 of file PartialMapMenu.cs.
Referenced by Refresh().
listCat
UIList PartialMapMenu.listCat
Definition at line 20 of file PartialMapMenu.cs.
Referenced by Init(), and RefreshCategory().
listCatSub
UIList PartialMapMenu.listCatSub
Definition at line 22 of file PartialMapMenu.cs.
Referenced by Init(), and RefreshCategory().
rootDir
DirectoryInfo PartialMapMenu.rootDir
Definition at line 40 of file PartialMapMenu.cs.
Referenced by Init(), and RefreshCategory().
toggleIgnoreBlock
UIButton PartialMapMenu.toggleIgnoreBlock
Definition at line 36 of file PartialMapMenu.cs.
Referenced by RefreshOptions().
toggleRotate
UIButton PartialMapMenu.toggleRotate
Definition at line 34 of file PartialMapMenu.cs.
Referenced by RefreshOptions().
Property Documentation
am
AM_Copy PartialMapMenu.am get
Definition at line 42 of file PartialMapMenu.cs.
Referenced by Refresh().
dir
DirectoryInfo PartialMapMenu.dir get
Definition at line 44 of file PartialMapMenu.cs.
Referenced by Refresh(), and RefreshCategory().
IsEditor
bool PartialMapMenu.IsEditor get
Definition at line 46 of file PartialMapMenu.cs.
Referenced by Init(), Refresh(), and RefreshOptions().
partial
PartialMap PartialMapMenu.partial get
Definition at line 48 of file PartialMapMenu.cs.
Referenced by RefreshOptions().
The documentation for this class was generated from the following file:
Elin/PartialMapMenu.cs