Elin Decompiled Documentation: SourceBlock Class Reference
SourceBlock Class Reference
Classes
class Row
Public Member Functions
override Row CreateRow ()
override void SetRow (Row r)
override void BackupPref ()
override void RestorePref ()
override void ValidatePref ()
override void OnAfterImportData ()
override void OnInit ()
Public Member Functions inherited from SourceDataInt< SourceBlock.Row >
override T GetRow (string id)
Public Attributes
Dictionary< int, Row > _rows = new Dictionary<int, Row>()
Static Public Attributes
static RenderData FallbackRenderData
Detailed Description
Definition at line 4 of file SourceBlock.cs.
Member Function Documentation
BackupPref()
override void SourceBlock.BackupPref () inline
Definition at line 115 of file SourceBlock.cs.
    {
        _rows.Clear();
        foreach (Row row in rows)
        {
            _rows[row.id] = row;
        }
    }
References _rows, and TileRow.id.
CreateRow()
override Row SourceBlock.CreateRow () inline
Definition at line 73 of file SourceBlock.cs.
    {
        return new Row
        {
            id = SourceData.GetInt(0),
            alias = SourceData.GetString(1),
            name_JP = SourceData.GetString(2),
            name = SourceData.GetString(3),
            sort = SourceData.GetInt(4),
            reqHarvest = SourceData.GetStringArray(5),
            hp = SourceData.GetInt(6),
            idThing = SourceData.GetString(7),
            _tileType = SourceData.GetString(8),
            _idRenderData = SourceData.GetString(9),
            tiles = SourceData.GetIntArray(10),
            snowTile = SourceData.GetInt(11),
            colorMod = SourceData.GetInt(12),
            colorType = SourceData.GetString(13),
            value = SourceData.GetInt(14),
            LV = SourceData.GetInt(15),
            recipeKey = SourceData.GetStringArray(16),
            factory = SourceData.GetStringArray(17),
            components = SourceData.GetStringArray(18),
            defMat = SourceData.GetString(19),
            category = SourceData.GetString(20),
            roof = SourceData.GetInt(21),
            autoFloor = SourceData.GetString(22),
            concrete = SourceData.GetBool(23),
            transparent = SourceData.GetBool(24),
            transition = SourceData.GetIntArray(25),
            tag = SourceData.GetStringArray(26),
            soundFoot = SourceData.GetString(27),
            detail_JP = SourceData.GetString(28),
            detail = SourceData.GetString(29)
        };
    }
References SourceData< T, T2 >.GetBool(), SourceData< T, T2 >.GetInt(), SourceData< T, T2 >.GetIntArray(), SourceData< T, T2 >.GetString(), and SourceData< T, T2 >.GetStringArray().
OnAfterImportData()
override void SourceBlock.OnAfterImportData () inline
Definition at line 140 of file SourceBlock.cs.
    {
        int num = 0;
        foreach (Row row in rows)
        {
            if (row.sort != 0)
            {
                num = row.sort;
            }
            row.sort = num;
            num++;
        }
        rows.Sort((Row a, Row b) => a.id - b.id);
    }
References TileRow.id, and RenderRow.sort.
OnInit()
override void SourceBlock.OnInit () inline
Definition at line 155 of file SourceBlock.cs.
    {
        FallbackRenderData = ResourceCache.Load<RenderData>("Scene/Render/Data/block");
        Cell.blockList = rows;
        SourceFloor floors = Core.Instance.sources.floors;
        foreach (Row row in rows)
        {
            row.Init();
            row.sourceAutoFloor = (row.autoFloor.IsEmpty() ? floors.rows[40] : floors.alias[row.autoFloor]);
        }
    }
References SourceBlock.Row.autoFloor, FallbackRenderData, SourceManager.floors, TileRow.Init(), Core.Instance, and Core.sources.
RestorePref()
override void SourceBlock.RestorePref () inline
Definition at line 124 of file SourceBlock.cs.
    {
        foreach (Row row in rows)
        {
            row.pref = _rows.TryGetValue(row.id)?.pref ?? new SourcePref();
        }
    }
References _rows, and TileRow.id.
SetRow()
override void SourceBlock.SetRow (Row r) inline
Definition at line 110 of file SourceBlock.cs.
    {
        map[r.id] = r;
    }
References TileRow.id.
ValidatePref()
override void SourceBlock.ValidatePref () inline
Definition at line 132 of file SourceBlock.cs.
    {
        foreach (Row row in rows)
        {
            row.pref.Validate();
        }
    }
References RenderRow.pref, and SourcePref.Validate().
Member Data Documentation
_rows
Dictionary<int, Row> SourceBlock._rows = new Dictionary<int, Row>()
Definition at line 69 of file SourceBlock.cs.
Referenced by BackupPref(), and RestorePref().
FallbackRenderData
RenderData SourceBlock.FallbackRenderData static
Definition at line 71 of file SourceBlock.cs.
Referenced by OnInit().
The documentation for this class was generated from the following file:
Elin/SourceBlock.cs