Elin Decompiled Documentation: GoalCombat Class Reference
GoalCombat Class Reference
Classes
class ItemAbility
Public Member Functions
override bool CanManualCancel ()
override IEnumerable< AIAct.Status > Run ()
bool TryMove (int dist)
void AddAbility (Act a, int mod=0, int chance=100, bool aiPt=false)
virtual bool TryUseRanged (int dist)
virtual bool TryThrow (int dist)
virtual bool TryUseAbility (int dist, bool beforeMove=false)
virtual void BuildAbilityList ()
virtual bool TryAbortCombat ()
Public Member Functions inherited from Goal
Goal Duplicate ()
Public Member Functions inherited from AIAct
override string ToString ()
override MultiSprite GetStateIcon ()
virtual Point GetDestination ()
AIProgress GetProgress ()
string GetCurrentActionText ()
override bool IsToolValid ()
virtual void OnStart ()
void SetOwner (Chara c)
virtual void OnSetOwner ()
void SetChild (AIAct seq, Func< AIAct.Status > _onChildFail=null)
void Start ()
override bool Perform ()
AIAct.Status Restart ()
AIAct.Status Success (Action action=null)
virtual void OnSuccess ()
bool TryCancel (Card c)
virtual AIAct.Status Cancel ()
virtual void OnCancel ()
virtual void OnCancelOrSuccess ()
virtual bool CanManualCancel ()
AIAct.Status KeepRunning ()
void Reset ()
virtual void OnReset ()
AIAct.Status Tick ()
virtual IEnumerable< AIAct.Status > Run ()
AIAct.Status TickChild ()
AIAct.Status Do (AIAct _seq, Func< AIAct.Status > _onChildFail=null)
AIAct.Status DoGotoInteraction (Point pos, Func< AIAct.Status > _onChildFail=null)
AIAct.Status DoGoto (Point pos, int dist=0, bool ignoreConnection=false, Func< AIAct.Status > _onChildFail=null)
AIAct.Status DoGoto (Card card, Func< AIAct.Status > _onChildFail=null)
AIAct.Status DoGoto (Card card, int dist, Func< AIAct.Status > _onChildFail=null)
AIAct.Status DoGotoSpot (Card card, Func< AIAct.Status > _onChildFail=null)
AIAct.Status DoGoto< T > (Func< AIAct.Status > _onChildFail=null)
AIAct.Status DoGotoSpot< T > (Func< AIAct.Status > _onChildFail=null, bool ignoreAccessType=false)
AIAct.Status DoGrab (Card card, int num=-1, bool pickHeld=false, Func< AIAct.Status > _onChildFail=null)
AIAct.Status DoGrab< T > ()
AIAct.Status DoProgress ()
AIAct.Status DoIdle (int repeat=3)
AIAct.Status DoWait (int count=1)
virtual AIProgress CreateProgress ()
virtual void OnCreateProgress (Progress_Custom p)
virtual bool CanProgress ()
virtual void OnBeforeProgress ()
virtual void OnProgress ()
virtual void OnProgressComplete ()
void SimulateZone (int days)
virtual void OnSimulateZone (int days)
virtual void OnSimulatePosition ()
Public Member Functions inherited from Act
virtual CursorInfo GetCursorIcon (Card c)
virtual MultiSprite GetStateIcon ()
override Sprite GetSprite ()
virtual bool ShowMouseHint (Card c)
virtual bool IsValidTC (Card c)
virtual string GetHintText (string str="")
virtual string GetText (string str="")
virtual string GetTextSmall (Card c)
virtual Color GetActPlanColor ()
virtual bool Perform ()
virtual bool CanPerform ()
bool Perform (Chara _cc, Card _tc=null, Point _tp=null)
bool CanPerform (Chara _cc, Card _tc=null, Point _tp=null)
virtual bool IsToolValid ()
new void SetImage (Image image)
virtual void OnMarkMapHighlights ()
virtual bool ShouldMapHighlight (Point p)
Public Member Functions inherited from Element
virtual SourceElement.Row GetSource ()
virtual int GetSourcePotential (int v)
virtual Sprite GetSprite ()
int GetMaterialSourceValue (Thing t, int v)
virtual int GetSourceValue (int v, int lv, SourceValueType type)
virtual Sprite GetIcon (string suffix="")
int SortVal (bool charaSheet=false)
virtual bool CanLink (ElementContainer owner)
bool HasTag (string tag)
void SetImage (Image i)
virtual string GetDetail ()
bool IsFactionElement (Chara c)
Element GetParent (Card c)
void WriteNote (UINote n, ElementContainer owner=null, Action< UINote > onWriteNote=null)
void WriteNoteWithRef (UINote n, ElementContainer owner, Action< UINote > onWriteNote, Element refEle)
void _WriteNote (UINote n, Chara c, Act act)
void _WriteNote (UINote n, ElementContainer owner, Action< UINote > onWriteNote, bool isRef, bool addHeader=true)
virtual void OnWriteNote (UINote n, ElementContainer owner)
virtual void OnChangeValue ()
void CheckLevelBonus (ElementContainer owner, UINote n=null)
int GetSortVal (UIList.SortMode m)
virtual Act.Cost GetCost (Chara c)
virtual int GetPower (Card c)
virtual void SetTextValue (UIText text)
Public Attributes
Chara destEnemy
Chara tc
int idleCount
int moveFail
List< GoalCombat.ItemAbility > abilities
List< Chara > charas = new List<Chara>()
Public Attributes inherited from AIAct
new Chara owner
AIAct.Status status
IEnumerator< AIAct.Status > Enumerator
AIAct child
AIAct parent
byte restartCount
Func< AIAct.Status > onChildFail
Func< bool > isFail
Public Attributes inherited from Element
SourceElement.Row _source
int id
int vBase
int vExp
int vPotential
int vTempPotential
int vLink
int vSource
int vSourcePotential
ElementContainer owner
Properties
override CursorInfo CursorIcon [get]
override bool CancelWhenDamaged [get]
Tactics tactics [get]
Properties inherited from Goal
override bool InformCancel [get]
Properties inherited from AIAct
virtual bool IsRunning [get]
bool IsChildRunning [get]
bool IsMoveAI [get]
virtual int MaxRestart [get]
virtual new string Name [get]
virtual MultiSprite stateIcon [get]
virtual Sprite actionIcon [get]
virtual bool IsNoGoal [get]
virtual bool IsAutoTurn [get]
virtual bool IsIdle [get]
virtual bool PushChara [get]
virtual int MaxProgress [get]
virtual bool ShowProgress [get]
virtual bool UseTurbo [get]
virtual int CurrentProgress [get]
virtual bool ShowCursor [get]
virtual bool CancelWhenDamaged [get]
virtual bool CancelWhenMoved [get]
virtual bool InformCancel [get]
virtual Thing RenderThing [get]
AIAct Current [get]
override bool IsAct [get]
override bool ShowPotential [get]
override bool UsePotential [get]
override bool ShowRelativeAttribute [get]
virtual bool HasProgress [get]
Properties inherited from Act
override bool ShowPotential [get]
override bool UsePotential [get]
override bool ShowRelativeAttribute [get]
virtual CursorInfo CursorIcon [get]
virtual string ID [get]
virtual bool IsAct [get]
virtual bool WillEndTurn [get]
virtual bool CloseLayers [get]
virtual int LeftHand [get]
virtual int RightHand [get]
virtual int ElementPowerMod [get]
virtual bool ShowMapHighlight [get]
virtual bool ShowMapHighlightBlock [get]
virtual bool PickHeldOnStart [get]
virtual bool DropHeldOnStart [get]
virtual bool CanPressRepeat [get]
virtual bool CanAutofire [get]
virtual bool ResetAxis [get]
virtual bool RequireTool [get]
virtual bool IsHostileAct [get]
virtual bool HideRightInfo [get]
virtual bool HaveLongPressAction [get]
virtual float Radius [get]
virtual int PerformDistance [get]
virtual int MaxRadius [get]
virtual TargetType TargetType [get]
virtual bool LocalAct [get]
virtual bool CanRapidFire [get]
virtual float RapidDelay [get]
virtual bool ShowAuto [get]
virtual bool IsCrime [get]
Properties inherited from Element
SourceElement.Row source [get]
virtual int DisplayValue [get]
virtual int MinValue [get]
int Value [get]
int ValueWithoutLink [get]
virtual int MinPotential [get]
int Potential [get]
virtual bool CanGainExp [get]
bool IsFlag [get]
virtual string Name [get]
virtual string FullName [get]
virtual int ExpToNext [get]
virtual bool UseExpMod [get]
virtual int CostTrain [get]
virtual int CostLearn [get]
virtual bool ShowXP [get]
virtual bool ShowMsgOnValueChanged [get]
virtual bool ShowValue [get]
virtual bool ShowPotential [get]
virtual bool UsePotential [get]
virtual bool PotentialAsStock [get]
virtual bool ShowRelativeAttribute [get]
virtual bool ShowBonuses [get]
virtual string ShortName [get]
bool IsGlobalElement [get]
bool IsFactionWideElement [get]
bool IsPartyWideElement [get]
virtual bool ShowEncNumber [get]
bool IsTrait [get]
bool IsFoodTrait [get]
bool IsFoodTraitMain [get]
bool IsMainAttribute [get]
Act act [get]
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Private Member Functions
void< Run > g__CalmDown ()
Additional Inherited Members
Public Types inherited from AIAct
enum Status { Running , Fail , Success }
Public Types inherited from Act
enum CostType { None , MP , SP }
Static Public Member Functions inherited from Act
static void SetReference (Chara _cc, Card _tc=null, Point _tp=null)
static void SetTool (Thing t)
Static Public Member Functions inherited from Element
static string GetName (string alias)
static SourceElement.Row Get (int id)
static Dictionary< int, int > GetElementMap (int[] list)
static Dictionary< int, int > GetElementMap (int[] list, Dictionary< int, int > map)
static SourceElement.Row GetRandomElement (int lv=1)
static Element Create (int id, int v=0)
static Element Create (string id, int v=1)
static int GetId (string alias)
static int GetResistLv (int v)
static int GetResistDamage (int dmg, int v)
Static Public Member Functions inherited from EClass
static int rnd (int a)
static int curve (int a, int start, int step, int rate=75)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Static Public Attributes inherited from Act
static Chara CC
static Card TC
static Point TP = new Point()
static Thing TOOL
static int powerMod = 100
static bool forcePt
Static Public Attributes inherited from Element
const int Div = 5
static Element Void = new Element()
static int[] List_MainAttributes
static int[] List_MainAttributesMajor
static int[] List_Body
static int[] List_Mind
static List< SourceElement.Row > ListElements = new List<SourceElement.Row>()
static List< SourceElement.Row > ListAttackElements = new List<SourceElement.Row>()
Static Public Attributes inherited from EClass
static Core core
Static Package Functions inherited from Element
static string< _WriteNote > g__Calc (ref Element.<>c__DisplayClass103_0 A_0)
Detailed Description
Definition at line 6 of file GoalCombat.cs.
Member Function Documentation
AddAbility()
void GoalCombat.AddAbility (Act a, int mod = 0, int chance = 100, bool aiPt = false) inline
Definition at line 388 of file GoalCombat.cs.
    {
        this.abilities.Add(new GoalCombat.ItemAbility
        {
            act = a,
            priorityMod = mod,
            chance = chance,
            aiPt = aiPt
        });
    }
References abilities.
Referenced by BuildAbilityList().
BuildAbilityList()
virtual void GoalCombat.BuildAbilityList () inline virtual
Reimplemented in GoalAutoCombat.
Definition at line 1013 of file GoalCombat.cs.
    {
        foreach (ActList.Item item in this.owner.ability.list.items)
        {
            this.AddAbility(item.act, 0, item.chance, item.pt);
        }
        this.AddAbility(ACT.Ranged, 0, 100, false);
        this.AddAbility(ACT.Melee, 0, 100, false);
        this.AddAbility(ACT.Item, 0, 100, false);
    }
References AddAbility(), ACT.Item, ACT.Melee, and ACT.Ranged.
Referenced by Run().
CanManualCancel()
override bool GoalCombat.CanManualCancel () inline virtual
Reimplemented from AIAct.
Definition at line 24 of file GoalCombat.cs.
    {
        return true;
    }
g__CalmDown()
void< Run > GoalCombat.g__CalmDown () inline private
Definition at line 1030 of file GoalCombat.cs.
    {
        this.owner.enemy = null;
        if (this.owner.ride != null)
        {
            this.owner.ride.enemy = null;
        }
        if (this.owner.parasite != null)
        {
            this.owner.parasite.enemy = null;
        }
        this.owner.hostility = this.owner.OriginalHostility;
        if (this.tc.enemy == this.owner)
        {
            this.tc.enemy = null;
            if (this.tc.ride != null)
            {
                this.tc.ride.enemy = null;
            }
            if (this.tc.parasite != null)
            {
                this.tc.parasite.enemy = null;
            }
            this.tc.hostility = this.tc.OriginalHostility;
        }
        this.owner.Say("calmDown", this.owner, null, null);
    }
References Chara.enemy, Chara.OriginalHostility, AIAct.owner, Chara.parasite, Chara.ride, Card.Say(), and tc.
Referenced by Run().
Run()
override IEnumerable< AIAct.Status > GoalCombat.Run () inline virtual
Reimplemented from AIAct.
Definition at line 37 of file GoalCombat.cs.
    {
        if (this.destEnemy != null)
        {
            this.owner.enemy = this.destEnemy;
            this.destEnemy = null;
        }
        int count = 0;
        int lostCount = 0;
        bool dontWander = this.owner.IsPCParty && !this.owner.IsPC && EClass.game.config.tactics.dontWander;
        for (;;)
        {
            if (EClass.debug.logCombat)
            {
                Debug.Log(string.Concat(new string[]
                {
                    "",
                    this.owner.Name,
                    "/",
                    count.ToString(),
                    "/",
                    lostCount.ToString()
                }));
            }
            if (EClass._zone.isPeace && this.owner.IsPCFactionOrMinion && !this.owner.IsPC)
            {
                this.owner.enemy = null;
                this.owner.ShowEmo(Emo.happy, 0f, true);
                yield return base.Success(null);
            }
            int num = count;
            count = num + 1;
            if (dontWander && this.owner.enemy != null && !EClass.pc.isBlind && !EClass.pc.CanSeeLos(this.owner.enemy, -1, false) && (this.owner.Dist(EClass.pc) > 4 || this.owner.Dist(this.owner.enemy) > 1))
            {
                Point firstStep = this.owner.GetFirstStep(EClass.pc.pos, PathManager.MoveType.Combat);
                if (firstStep.IsValid && !firstStep.HasChara)
                {
                    this.owner.enemy = null;
                }
            }
            this.tc = this.owner.enemy;
            if (this.tc != null && this.owner.IsPCFaction)
            {
                AI_Shear ai_Shear = EClass.pc.ai as AI_Shear;
                if (ai_Shear != null && ai_Shear.target == this.tc)
                {
                    this.tc = (this.owner.enemy = null);
                }
            }
            if (this.tc == null || this.tc.isDead || !this.tc.ExistsOnMap || !this.tc.pos.IsInBounds || lostCount >= 5)
            {
                this.tc = (this.owner.enemy = null);
                if (this.owner.IsPC && EClass.game.config.autoCombat.abortOnKill)
                {
                    yield return base.Success(null);
                }
                this.owner.FindNewEnemy();
                lostCount = 0;
                if (this.owner.enemy == null)
                {
                    yield return base.Success(null);
                }
                this.tc = this.owner.enemy;
            }
            else if (!this.owner.CanSeeLos(this.tc, -1, false))
            {
                num = lostCount;
                lostCount = num + 1;
            }
            else
            {
                lostCount = 0;
            }
            if (this.owner.IsPC && this.tc.HasEditorTag(EditorTag.Invulnerable))
            {
                Msg.Say("abort_idle");
                yield return base.Success(null);
            }
            if (this.tc.IsPCFaction && this.owner.id == "melilith_boss" && EClass._map.plDay.list.Count > 1 && EClass._map.plDay.list[0].data.id != 107)
            {
                EClass._zone.SetBGM(107, true);
            }
            if (this.abilities == null)
            {
                this.abilities = new List<GoalCombat.ItemAbility>();
                this.BuildAbilityList();
            }
            if (this.owner.IsPCFaction && this.tc.IsPCFaction && EClass.rnd(5) == 0 && count > 2)
            {
                this.<Run>g__CalmDown|14_0();
                yield return base.Success(null);
            }
            if (this.owner.OriginalHostility >= Hostility.Neutral && this.tc.OriginalHostility >= Hostility.Neutral && !this.owner.IsPCParty && this.owner.c_bossType == BossType.none && (!(this.owner.trait is TraitGuard) || this.owner.IsPCFaction || !this.tc.IsPCParty || !EClass.player.IsCriminal))
            {
                if (this.owner.calmCheckTurn < 0 || (!this.owner.enemy.IsPCParty && EClass.rnd(10) == 0))
                {
                    this.<Run>g__CalmDown|14_0();
                    yield return base.Success(null);
                }
                this.owner.calmCheckTurn--;
            }
            if (this.owner.IsPC)
            {
                CursorSystem.ignoreCount = 1;
            }
            if (this.tc.host != null && (this.tc.hp == 0 || EClass.rnd(5) == 0))
            {
                this.tc = this.owner.SetEnemy(this.tc.host);
            }
            if (this.tc.parasite != null && !this.tc.isRestrained && this.tc.parasite.hp > 0 && EClass.rnd(5) == 0)
            {
                this.tc = this.owner.SetEnemy(this.tc.parasite);
            }
            if (this.tc.ride != null && !this.tc.isRestrained && this.tc.ride.hp > 0 && EClass.rnd(5) == 0)
            {
                this.tc = this.owner.SetEnemy(this.tc.ride);
            }
            if (this.tc.enemy != null)
            {
                this.tc.TrySetEnemy(this.owner);
            }
            if (!this.tc.IsMinion && EClass.rnd(10) == 0 && EClass.rnd(this.tc.DEX + 10) > this.owner.LV && this.tc.HasElement(1315, 1) && !this.owner.HasElement(1315, 1) && this.owner.race.IsMachine && this.owner.CanBeTempAlly(this.tc))
            {
                this.owner.Say("dominate_machine", this.tc, this.owner, null, null);
                this.owner.PlayEffect("boost", true, 0f, default(Vector3));
                this.owner.PlaySound("boost", 1f, true);
                this.owner.ShowEmo(Emo.love, 0f, true);
                this.owner.lastEmo = Emo.angry;
                this.owner.MakeMinion(this.tc.IsPCParty ? EClass.pc : this.tc, MinionType.Default);
                yield return base.Success(null);
            }
            if (EClass.rnd(5) == 0 && this.tc.HasElement(1325, 1) && this.owner.race.IsPlant && this.owner.CanBeTempAlly(this.tc))
            {
                this.owner.Say("dominate_plant", this.tc, this.owner, null, null);
                this.owner.ShowEmo(Emo.love, 0f, true);
                this.owner.lastEmo = Emo.angry;
                this.owner.MakeMinion((this.tc.IsPCParty || this.tc.IsPCFactionMinion) ? EClass.pc : this.tc, MinionType.Friend);
                yield return base.Success(null);
            }
            if (EClass.rnd(20) == 0 && this.owner.isRestrained)
            {
                this.owner.Talk("restrained", null, null, false);
            }
            if (this is GoalAutoCombat)
            {
                ActionMode.Adv.SetTurbo(EClass.game.config.autoCombat.turbo ? -1 : 0);
                EClass.pc.ModExp(135, 20);
            }
            int dist = this.owner.Dist(this.tc);
            bool move = this.owner.host == null && (this.tactics.ChanceMove > EClass.rnd(100) || (this.owner.IsPC && this.tc.HasCondition<ConFear>() && dist >= EClass.pc.GetSightRadius() - 1));
            bool haltSecondMove = false;
            if (!this.owner.IsPC && !this.owner.isBlind && this.tc.source.HasTag(CTAG.suicide) && this.owner.IsNeutralOrAbove() && !this.owner.isSummon && !this.owner.IsMinion && !this.tc.HasCondition<ConWet>())
            {
                if (dist <= 3)
                {
                    if (EClass.rnd(15) == 0)
                    {
                        this.owner.Talk("run_suicide", null, null, false);
                    }
                    if (this.owner.host == null && this.owner.TryMoveFrom(this.tc.pos) != Card.MoveResult.Fail)
                    {
                        yield return AIAct.Status.Running;
                        this.idleCount = 0;
                        continue;
                    }
                }
                else if (dist <= 5)
                {
                    haltSecondMove = true;
                    move = false;
                }
            }
            if (dontWander)
            {
                int num2 = this.owner.Dist(EClass.pc);
                if (num2 > 3)
                {
                    int x = this.tc.pos.x;
                    int z = this.tc.pos.z;
                    if (EClass.pc.pos.Distance(this.owner.pos.x + ((x > this.owner.pos.x) ? 1 : ((x < this.owner.pos.x) ? -1 : 0)), this.owner.pos.z + ((z > this.owner.pos.z) ? 1 : ((z < this.owner.pos.z) ? -1 : 0))) >= num2)
                    {
                        move = false;
                        haltSecondMove = true;
                    }
                }
            }
            if (this.owner.IsPC && EClass.game.config.autoCombat.bDontChase)
            {
                move = false;
                haltSecondMove = true;
            }
            if (EClass.debug.logCombat)
            {
                Debug.Log(string.Concat(new string[]
                {
                    this.owner.Name,
                    "/",
                    move.ToString(),
                    "/",
                    haltSecondMove.ToString(),
                    "/",
                    dist.ToString()
                }));
            }
            if (move)
            {
                if (this.owner.IsPC && dist <= this.owner.GetSightRadius() && this.TryUseAbility(dist, true))
                {
                    yield return AIAct.Status.Running;
                    this.idleCount = 0;
                    continue;
                }
                if (this.TryMove(dist))
                {
                    if (EClass.debug.logCombat)
                    {
                        Debug.Log("moved:" + this.owner.Name);
                    }
                    yield return AIAct.Status.Running;
                    this.idleCount = 0;
                    continue;
                }
            }
            if (this.owner == null)
            {
                yield return this.Cancel();
            }
            if (dist <= this.owner.GetSightRadius() && this.TryUseAbility(dist, false))
            {
                yield return AIAct.Status.Running;
                this.idleCount = 0;
            }
            else
            {
                if (EClass.debug.logCombat)
                {
                    Debug.Log(string.Concat(new string[]
                    {
                        this.owner.Name,
                        "/",
                        move.ToString(),
                        "/",
                        haltSecondMove.ToString(),
                        "/",
                        this.tactics.ChanceSecondMove.ToString()
                    }));
                }
                if (!move && !haltSecondMove && this.tactics.ChanceSecondMove > EClass.rnd(100) && this.TryMove(dist))
                {
                    yield return AIAct.Status.Running;
                    this.idleCount = 0;
                }
                else
                {
                    if (this.owner == null)
                    {
                        yield return this.Cancel();
                    }
                    this.idleCount++;
                    if (this.TryAbortCombat())
                    {
                        yield return base.Success(null);
                    }
                    if (this.idleCount > 2)
                    {
                        if (dontWander)
{
                            yield return base.Success(null);
                        }
                        this.idleCount = 0;
                        string aiIdle = this.owner.source.aiIdle;
                        if (aiIdle == "stand" || aiIdle == "root")
{
                            yield return base.Success(null);
                        }
                        yield return base.DoGoto(this.tc.pos, 0, false, null);
                    }
                    else if (this.owner.FindNearestNewEnemy())
                    {
                        continue;
                    }
                    yield return AIAct.Status.Running;
                }
            }
        }
        yield break;
    }
References EClass._map, EClass._zone, abilities, ActionMode.Adv, BuildAbilityList(), Chara.calmCheckTurn, AIAct.Cancel(), Chara.CanSeeLos(), Tactics.ChanceSecondMove, Game.config, EClass.debug, destEnemy, Card.Dist(), Point.Distance(), Chara.enemy, Chara.FindNearestNewEnemy(), Chara.FindNewEnemy(), g__CalmDown(), EClass.game, Chara.GetFirstStep(), Card.GetSightRadius(), Point.HasChara, Chara.HasCondition(), Chara.host, idleCount, Chara.isBlind, Player.IsCriminal, Chara.isDead, Chara.IsMinion, Chara.IsNeutralOrAbove(), Chara.IsPC, Chara.IsPCFaction, Chara.IsPCParty, Spatial.isPeace, Card.isRestrained, Point.IsValid, CoreDebug.logCombat, Chara.MakeMinion(), Card.ModExp(), Card.Name, Chara.OriginalHostility, AIAct.owner, Chara.parasite, EClass.pc, Card.PlayEffect(), EClass.player, Card.PlaySound(), Map.plDay, Card.pos, Chara.ride, EClass.rnd(), Run(), Msg.Say(), Card.Say(), Zone.SetBGM(), Chara.SetEnemy(), AM_Adv.SetTurbo(), Card.ShowEmo(), Chara.source, AIAct.Success(), tactics, Card.Talk(), AI_TargetCard.target, tc, TryAbortCombat(), TryMove(), Chara.TryMoveFrom(), Chara.TrySetEnemy(), TryUseAbility(), Point.x, and Point.z.
Referenced by Run().
TryAbortCombat()
virtual bool GoalCombat.TryAbortCombat () inline virtual
Reimplemented in GoalAutoCombat.
Definition at line 1024 of file GoalCombat.cs.
    {
        return false;
    }
Referenced by Run().
TryMove()
bool GoalCombat.TryMove (int dist) inline
Definition at line 325 of file GoalCombat.cs.
    {
        if (this.owner.host != null)
        {
            return false;
        }
        if (this.owner.isBlind)
        {
            return this.owner.MoveRandom();
        }
        int num = this.tc.HasCondition<ConFear>() ? 1 : this.tactics.DestDist;
        if (!this.owner.IsPC && (this.tactics.source.id == "archer" || this.tactics.source.id == "gunner") && !this.owner.TryEquipRanged())
        {
            num = 1;
        }
        if (!this.owner.IsPC && num > 1)
        {
            if (this.tactics.DestDist == 2)
            {
                if (EClass.rnd(5) == 0)
                {
                    num = 1;
                }
            }
            else if (this.owner.turn / 3 % 5 > 2)
            {
                num--;
            }
        }
        bool flag = false;
        if (dist > num)
        {
            flag = (this.owner.TryMoveTowards(this.tc.pos) > Card.MoveResult.Fail);
            if (!flag)
            {
                this.moveFail++;
            }
        }
        else if (dist < num)
        {
            flag = (this.owner.TryMoveFrom(this.tc.pos) > Card.MoveResult.Fail);
        }
        if (flag)
        {
            this.moveFail = 0;
        }
        if (EClass.debug.logCombat)
        {
            Debug.Log(string.Concat(new string[]
            {
                "TryMove:",
                this.owner.Name,
                "/",
                flag.ToString(),
                "/",
                dist.ToString(),
                "/",
                num.ToString()
            }));
        }
        return flag;
    }
References EClass.debug, Tactics.DestDist, Chara.HasCondition(), Chara.host, Chara.isBlind, Chara.IsPC, CoreDebug.logCombat, moveFail, Chara.MoveRandom(), Card.Name, AIAct.owner, Card.pos, EClass.rnd(), tactics, tc, Chara.TryEquipRanged(), Chara.TryMoveFrom(), Chara.TryMoveTowards(), and Card.turn.
Referenced by Run().
TryThrow()
virtual bool GoalCombat.TryThrow (int dist) inline virtual
Definition at line 404 of file GoalCombat.cs.
    {
        if (dist > this.owner.GetSightRadius())
        {
            return false;
        }
        Thing thing = this.owner.TryGetThrowable();
        if (thing == null)
        {
            return false;
        }
        if (!ACT.Throw.CanPerform(this.owner, this.tc, this.tc.pos))
        {
            return false;
        }
        ActThrow.Throw(this.owner, this.tc.pos, this.tc, thing.HasElement(410, 1) ? thing : thing.Split(1), ThrowMethod.Default);
        return true;
    }
References ActThrow.CanPerform(), Card.GetSightRadius(), Card.HasElement(), AIAct.owner, Card.pos, Card.Split(), tc, ACT.Throw, ActThrow.Throw(), and Chara.TryGetThrowable().
Referenced by TryUseAbility().
TryUseAbility()
virtual bool GoalCombat.TryUseAbility (int dist, bool beforeMove = false) inline virtual
Definition at line 423 of file GoalCombat.cs.
    {
        GoalCombat.<>c__DisplayClass19_0 CS$<>8__locals1 = new GoalCombat.<>c__DisplayClass19_0();
        CS$<>8__locals1.<>4__this = this;
        if (this.abilities.Count == 0)
        {
            string str = "no ability:";
            Chara owner = this.owner;
            Debug.Log(str + ((owner != null) ? owner.ToString() : null));
            return false;
        }
        CS$<>8__locals1.numEnemy = -1;
        CS$<>8__locals1.numFriend = -1;
        CS$<>8__locals1.numNeutral = -1;
        CS$<>8__locals1.charaBuilt = false;
        bool flag = this.owner.CanSeeLos(this.tc, dist, false);
        bool isPCFaction = this.owner.IsPCFaction;
        bool flag2 = this.owner.HasCondition<ConSilence>();
        bool isBlind = this.owner.isBlind;
        bool flag3 = this.owner.HasCondition<ConFear>();
        bool isConfused = this.owner.isConfused;
        bool flag4 = this.owner.HasCondition<ConDim>();
        foreach (GoalCombat.ItemAbility itemAbility in this.abilities)
        {
            if (EClass.rnd(100) >= itemAbility.chance)
            {
                itemAbility.priority = 0;
            }
            else
            {
                Act act = itemAbility.act;
                SourceElement.Row s = act.source;
                itemAbility.priority = 0;
                itemAbility.tg = null;
                itemAbility.pt = false;
                if (s.abilityType.Length != 0 && (!this.owner.IsPC || !flag2 || !(act is Spell)) && (!beforeMove || act.HasTag("before_move")))
                {
                    string text = s.abilityType[0];
                    if (this.id != 6602 || (dist > 1 && !this.tc.HasCondition<ConEntangle>()))
                    {
                        uint num = <PrivateImplementationDetails>.ComputeStringHash(text);
                        int num2;
                        if (num <= 2140930120U)
{
                            if (num <= 979982427U)
{
                                if (num <= 115652151U)
{
                                    if (num != 13211034U)
{
                                        if (num != 115652151U)
{
                                            goto IL_BCA;
                                        }
                                        if (!(text == "debuff"))
{
                                            goto IL_BCA;
                                        }
                                        if (flag)
{
                                            num2 = this.tactics.P_Debuff;
                                            goto IL_BCD;
                                        }
                                        continue;
                                    }
                                    else
{
                                        if (!(text == "summon"))
{
                                            goto IL_BCA;
                                        }
                                        if (this.owner.isRestrained || (this.tc != null && this.tc.IsRestrainedResident))
{
                                            continue;
                                        }
                                        int num3 = EClass._zone.CountMinions(this.owner);
                                        if (num3 < this.owner.MaxSummon)
{
                                            num2 = this.tactics.P_Summon - 20 * num3 / this.owner.MaxSummon;
                                            goto IL_BCD;
                                        }
                                        continue;
                                    }
                                }
                                else if (num != 601369519U)
{
                                    if (num != 740945997U)
{
                                        if (num != 979982427U)
{
                                            goto IL_BCA;
                                        }
                                        if (!(text == "heal"))
{
                                            goto IL_BCA;
                                        }
                                        goto IL_72E;
                                    }
                                    else
{
                                        if (!(text == "any"))
{
                                            goto IL_BCA;
                                        }
                                        num2 = 50;
                                        goto IL_BCD;
                                    }
                                }
                                else
{
                                    if (!(text == "suicide"))
{
                                        goto IL_BCA;
                                    }
                                    if (this.owner.IsPC || this.owner.HasCondition<ConWet>())
{
                                        continue;
                                    }
                                    if (this.owner.HasTag(CTAG.kamikaze))
{
                                        num2 = ((dist <= 1) ? 1000 : 0);
                                        goto IL_BCD;
                                    }
                                    num2 = 100 - 125 * this.owner.hp / this.owner.MaxHP;
                                    if (EClass.rnd(200) > num2)
{
                                        continue;
                                    }
                                    goto IL_BCD;
                                }
                            }
                            else if (num <= 1167440125U)
{
                                if (num != 1000963043U)
{
                                    if (num != 1167440125U)
{
                                        goto IL_BCA;
                                    }
                                    if (!(text == "attack"))
{
                                        goto IL_BCA;
                                    }
                                }
                                else if (!(text == "attackMelee"))
{
                                    goto IL_BCA;
                                }
                            }
                            else if (num != 1244307660U)
{
                                if (num != 2043306875U)
{
                                    if (num != 2140930120U)
{
                                        goto IL_BCA;
                                    }
                                    if (!(text == "summonAlly"))
{
                                        goto IL_BCA;
                                    }
                                    if (!this.owner.isRestrained && (this.tc == null || !this.tc.IsRestrainedResident))
{
                                        if (this.owner.IsPC)
{
                                            if (EClass.player.lastEmptyAlly <= 0)
{
                                                continue;
                                            }
                                        }
                                        else if (EClass._zone.CountMinions(this.owner) > 0)
{
                                            continue;
                                        }
                                        num2 = this.tactics.P_Summon;
                                        goto IL_BCD;
                                    }
                                    continue;
                                }
                                else
{
                                    if (!(text == "melee"))
{
                                        goto IL_BCA;
                                    }
                                    if (dist > this.owner.body.GetMeleeDistance())
{
                                        continue;
                                    }
                                    num2 = (flag3 ? (this.owner.IsPC ? 0 : (this.tactics.P_Melee / 2)) : this.tactics.P_Melee);
                                    if (isConfused)
{
                                        num2 -= (this.owner.IsPC ? 30 : 10);
                                    }
                                    if (isBlind)
{
                                        num2 -= (this.owner.IsPC ? 50 : 10);
                                    }
                                    if (this.tc.HasElement(1221, 1))
{
                                        num2 -= 40;
                                    }
                                    if (this.tc.HasElement(1223, 1))
{
                                        num2 -= 40;
                                        goto IL_BCD;
                                    }
                                    goto IL_BCD;
                                }
                            }
                            else
{
                                if (!(text == "buff"))
{
                                    goto IL_BCA;
                                }
                                num2 = CS$<>8__locals1.<TryUseAbility>g__ForeachChara|4(itemAbility, delegate(Chara c)
{
                                    if (!c.HasCondition(s.proc[1]))
{
                                        return CS$<>8__locals1.<>4__this.tactics.P_Buff;
                                    }
                                    return 0;
                                }, true);
                                if (itemAbility.aiPt || (this.owner.IsPC && this.tactics.CastPartyBuff))
{
                                    itemAbility.pt = true;
                                    goto IL_BCD;
                                }
                                goto IL_BCD;
                            }
                        }
                        else if (num <= 2762313447U)
{
                            if (num <= 2360683452U)
{
                                if (num != 2301512864U)
{
                                    if (num != 2360683452U)
{
                                        goto IL_BCA;
                                    }
                                    if (!(text == "attackArea"))
{
                                        goto IL_BCA;
                                    }
                                    if (this.owner.isRestrained || (this.tc != null && this.tc.IsRestrainedResident))
{
                                        continue;
                                    }
                                    bool flag5 = itemAbility.act is ActBolt;
                                    if (!flag || (this.owner.IsPCParty && (EClass._zone.IsTown || EClass._zone.IsPCFaction)))
{
                                        continue;
                                    }
                                    CS$<>8__locals1.<TryUseAbility>g__GetNumEnemy|0(flag5 ? 6 : 5);
                                    if (CS$<>8__locals1.numEnemy != 0 && (!this.owner.IsPCFactionOrMinion || CS$<>8__locals1.<TryUseAbility>g__GetNumNeutral|1(flag5 ? 6 : 5) <= 0))
{
                                        num2 = this.tactics.P_Spell - 20 + CS$<>8__locals1.numEnemy * 10 + CS$<>8__locals1.<TryUseAbility>g__GetAttackMod|5(act);
                                        goto IL_BCD;
                                    }
                                    continue;
                                }
                                else
{
                                    if (!(text == "wait"))
{
                                        goto IL_BCA;
                                    }
                                    if (!this.owner.IsPCParty)
{
                                        num2 = 50;
                                        goto IL_BCD;
                                    }
                                    continue;
                                }
                            }
                            else if (num != 2627848062U)
{
                                if (num != 2671260646U)
{
                                    if (num != 2762313447U)
{
                                        goto IL_BCA;
                                    }
                                    if (!(text == "buffStats"))
{
                                        goto IL_BCA;
                                    }
                                    num2 = CS$<>8__locals1.<TryUseAbility>g__ForeachChara|4(itemAbility, delegate(Chara c)
{
                                        Element buffStats = c.GetBuffStats(s.proc[1]);
                                        if (buffStats != null && buffStats.Value >= 0)
{
                                            return 0;
                                        }
                                        return CS$<>8__locals1.<>4__this.tactics.P_Buff;
                                    }, true);
                                    if (itemAbility.aiPt || (this.owner.IsPC && this.tactics.CastPartyBuff))
{
                                        itemAbility.pt = true;
                                        goto IL_BCD;
                                    }
                                    goto IL_BCD;
                                }
                                else
{
                                    if (!(text == "item"))
{
                                        goto IL_BCA;
                                    }
                                    num2 = (itemAbility.act as ActItem).BuildAct(this.owner);
                                    goto IL_BCD;
                                }
                            }
                            else
{
                                if (!(text == "ground"))
{
                                    goto IL_BCA;
                                }
                                if (!flag || this.owner.isRestrained || (this.tc != null && this.tc.IsRestrainedResident))
{
                                    continue;
                                }
                                num2 = 50;
                                if (isPCFaction)
{
                                    num2 -= 10;
                                    goto IL_BCD;
                                }
                                goto IL_BCD;
                            }
                        }
                        else if (num <= 3546849056U)
{
                            if (num != 3164374115U)
{
                                if (num != 3289626814U)
{
                                    if (num != 3546849056U)
{
                                        goto IL_BCA;
                                    }
                                    if (!(text == "dot"))
{
                                        goto IL_BCA;
                                    }
                                }
                                else
{
                                    if (!(text == "teleport"))
{
                                        goto IL_BCA;
                                    }
                                    num2 = 40;
                                    goto IL_BCD;
                                }
                            }
                            else
{
                                if (!(text == "taunt"))
{
                                    goto IL_BCA;
                                }
                                bool flag6 = this.owner.HasCondition<StanceTaunt>();
                                bool flag7 = this.tactics.source.taunt != -1 && 100 * this.owner.hp / this.owner.MaxHP >= this.tactics.source.taunt;
                                num2 = ((flag6 && !flag7) ? 100 : ((!flag6 && flag7) ? 100 : 0));
                                goto IL_BCD;
                            }
                        }
                        else if (num != 4208725202U)
{
                            if (num != 4274235348U)
{
                                if (num != 4289936826U)
{
                                    goto IL_BCA;
                                }
                                if (!(text == "debuffStats"))
{
                                    goto IL_BCA;
                                }
                                if (flag)
{
                                    num2 = CS$<>8__locals1.<TryUseAbility>g__ForeachChara|4(itemAbility, delegate(Chara c)
{
                                        Element buffStats = c.GetBuffStats(s.proc[1]);
                                        if (buffStats != null && buffStats.Value <= 0)
{
                                            return 0;
                                        }
                                        return CS$<>8__locals1.<>4__this.tactics.P_Debuff;
                                    }, false);
                                    goto IL_BCD;
                                }
                                continue;
                            }
                            else
{
                                if (!(text == "hot"))
{
                                    goto IL_BCA;
                                }
                                goto IL_72E;
                            }
                        }
                        else
{
                            if (!(text == "range"))
{
                                goto IL_BCA;
                            }
                            if (!flag || EClass.rnd(100) > this.tactics.RangedChance)
{
                                continue;
                            }
                            num2 = (flag3 ? (this.owner.IsPC ? 0 : (this.tactics.P_Range / 2)) : this.tactics.P_Range);
                            if (isConfused)
{
                                num2 -= (this.owner.IsPC ? 30 : 10);
                            }
                            if (isBlind)
{
                                num2 -= (this.owner.IsPC ? 50 : 10);
                            }
                            if (this.owner.ranged != null && this.owner.ranged.trait is TraitToolRangeCane && this.owner.mana.value <= 0)
{
                                continue;
                            }
                            goto IL_BCD;
                        }
                        if (!flag)
{
                            continue;
                        }
                        bool flag8 = text == "dot";
                        if (flag8 && (this.owner.isRestrained || (this.tc != null && this.tc.IsRestrainedResident)))
{
                            continue;
                        }
                        num2 = ((text == "attackMelee") ? this.tactics.P_Melee : this.tactics.P_Spell) + CS$<>8__locals1.<TryUseAbility>g__GetAttackMod|5(act);
                        if (num2 > 0 && flag8)
{
                            num2 += 10;
                        }
                        IL_BCD:
                        if (s.target == "Neighbor")
{
                            if (dist > 1)
{
                                continue;
                            }
                            num2 += 10;
                        }
                        if (s.proc.Length == 0 || !(s.proc[0] == "Debuff") || !this.tc.HasCondition(s.proc[1]))
{
                            if (s.abilityType.Length > 1)
{
                                num2 += (this.owner.IsPC ? s.abilityType[2] : s.abilityType[1]).ToInt();
                            }
                            if (act is Spell)
{
                                if (this.owner.IsPC)
{
                                    if (act.vPotential <= 0)
{
                                        continue;
                                    }
                                    if (flag2 || isConfused || flag4)
{
                                        num2 -= 50;
                                    }
                                }
                                else
{
                                    if (flag2)
{
                                        num2 -= 30;
                                    }
                                    if (isConfused || flag4)
{
                                        num2 -= 10;
                                    }
                                }
                            }
                            if (num2 > 0)
{
                                num2 += itemAbility.priorityMod + EClass.rnd(this.tactics.RandomFacotr + itemAbility.priorityMod);
                            }
                            itemAbility.priority = num2;
                            continue;
                        }
                        continue;
                        IL_72E:
                        bool isHOT = text == "hot";
                        num2 = CS$<>8__locals1.<TryUseAbility>g__ForeachChara|4(itemAbility, (Chara c) => base.<TryUseAbility>g__HealFactor|7(c), true);
                        if (itemAbility.aiPt || (this.owner.IsPC && this.tactics.CastPartyBuff))
{
                            itemAbility.pt = true;
                            goto IL_BCD;
                        }
                        goto IL_BCD;
                        IL_BCA:
                        num2 = 0;
                        goto IL_BCD;
                    }
                }
            }
        }
        this.abilities.Sort((GoalCombat.ItemAbility a, GoalCombat.ItemAbility b) => b.priority - a.priority);
        foreach (GoalCombat.ItemAbility itemAbility2 in this.abilities)
        {
            if (itemAbility2.priority > 0)
            {
                if (EClass.debug.logCombat && this.owner.IsPC)
                {
                    Debug.Log(itemAbility2.act.Name + "/" + itemAbility2.priority.ToString());
                }
                if (itemAbility2.act.source.alias == "ActRanged")
                {
                    if (this.TryThrow(dist))
                    {
                        return true;
                    }
                    if (this.TryUseRanged(dist))
                    {
                        return true;
                    }
                }
                else
                {
                    Act.Cost cost = itemAbility2.act.GetCost(this.owner);
                    if (!this.owner.IsPCParty || !itemAbility2.pt || itemAbility2.act.TargetType.ForceParty || cost.cost * EClass.pc.party.members.Count <= this.owner.mana.value)
                    {
                        if (isPCFaction && cost.cost > 0)
{
                            Act.CostType type = cost.type;
                            if (type != Act.CostType.MP)
{
                                if (type == Act.CostType.SP)
{
                                    if (cost.cost > this.owner.stamina.value)
{
                                        continue;
                                    }
                                }
                            }
                            else if (cost.cost > this.owner.mana.value)
{
                                continue;
                            }
                        }
                        if ((cost.cost <= 0 || EClass.rnd(100) <= this.tactics.AbilityChance) && itemAbility2.act.CanPerform(this.owner, itemAbility2.tg ?? this.tc, null) && this.owner.UseAbility(itemAbility2.act, itemAbility2.tg ?? this.tc, null, (itemAbility2.act.HaveLongPressAction && itemAbility2.pt) || itemAbility2.aiPt))
{
                            if (EClass.debug.logCombat)
{
                                string[] array = new string[9];
                                array[0] = this.owner.Name;
                                array[1] = "/";
                                array[2] = itemAbility2.act.id.ToString();
                                array[3] = "/";
                                array[4] = itemAbility2.act.CanPerform(this.owner, itemAbility2.tg ?? this.tc, null).ToString();
                                array[5] = "/";
                                int num4 = 6;
                                Chara tg = itemAbility2.tg;
                                array[num4] = ((tg != null) ? tg.ToString() : null);
                                array[7] = "/";
                                int num5 = 8;
                                Chara chara = this.tc;
                                array[num5] = ((chara != null) ? chara.ToString() : null);
                                Debug.Log(string.Concat(array));
                            }
                            return true;
                        }
                    }
                }
            }
        }
        if (EClass.debug.logCombat)
        {
            Debug.Log(this.owner.Name + "/" + this.abilities.Count.ToString());
            foreach (GoalCombat.ItemAbility itemAbility3 in this.abilities)
            {
                Debug.Log(itemAbility3.act.Name);
            }
        }
        return false;
    }
References EClass._zone, abilities, Tactics.AbilityChance, SourceElement.Row.abilityType, Element.act, Chara.body, Chara.CanSeeLos(), Act.Cost.cost, Zone.CountMinions(), EClass.debug, Chara.GetBuffStats(), CharaBody.GetMeleeDistance(), Chara.HasCondition(), Card.HasElement(), Card.HasTag(), Element.HasTag(), Chara.isBlind, Chara.isConfused, Chara.IsPC, Chara.IsPCFaction, Zone.IsPCFaction, Chara.IsPCParty, Card.isRestrained, Zone.IsTown, Player.lastEmptyAlly, CoreDebug.logCombat, Chara.MaxHP, Chara.MaxSummon, Party.members, Card.Name, AIAct.owner, Trait.owner, Tactics.P_Debuff, Tactics.P_Melee, Tactics.P_Range, Tactics.P_Summon, Chara.party, EClass.pc, EClass.player, SourceElement.Row.proc, Tactics.RandomFacotr, Chara.ranged, Tactics.RangedChance, EClass.rnd(), Element.source, Tactics.source, tactics, SourceElement.Row.target, tc, text, Chara.ToString(), Card.trait, TryThrow(), TryUseAbility(), TryUseRanged(), Act.Cost.type, Chara.UseAbility(), Element.Value, and Element.vPotential.
Referenced by Run(), and TryUseAbility().
TryUseRanged()
virtual bool GoalCombat.TryUseRanged (int dist) inline virtual
Reimplemented in GoalAutoCombat.
Definition at line 399 of file GoalCombat.cs.
    {
        return this.owner.TryEquipRanged() && ACT.Ranged.Perform(this.owner, this.tc, null);
    }
References AIAct.owner, ActRanged.Perform(), ACT.Ranged, tc, and Chara.TryEquipRanged().
Referenced by TryUseAbility().
Member Data Documentation
abilities
List<GoalCombat.ItemAbility> GoalCombat.abilities
Definition at line 1066 of file GoalCombat.cs.
Referenced by AddAbility(), Run(), and TryUseAbility().
charas
List<Chara> GoalCombat.charas = new List<Chara>()
Definition at line 1068 of file GoalCombat.cs.
destEnemy
Chara GoalCombat.destEnemy
Definition at line 1058 of file GoalCombat.cs.
Referenced by Run().
idleCount
int GoalCombat.idleCount
Definition at line 1062 of file GoalCombat.cs.
Referenced by Run(), and GoalAutoCombat.TryAbortCombat().
moveFail
int GoalCombat.moveFail
Definition at line 1064 of file GoalCombat.cs.
Referenced by TryMove().
tc
Chara GoalCombat.tc
Definition at line 1060 of file GoalCombat.cs.
Referenced by g__CalmDown(), Run(), TryMove(), TryThrow(), TryUseAbility(), and TryUseRanged().
Property Documentation
CancelWhenDamaged
override bool GoalCombat.CancelWhenDamaged get
Definition at line 16 of file GoalCombat.cs.
    {
        get
        {
            return false;
        }
    }
CursorIcon
override CursorInfo GoalCombat.CursorIcon get
Definition at line 8 of file GoalCombat.cs.
    {
        get
        {
            return CursorSystem.IconMelee;
        }
    }
tactics
Tactics GoalCombat.tactics get
Definition at line 29 of file GoalCombat.cs.
    {
        get
        {
            return this.owner.tactics;
        }
    }
Referenced by Run(), TryMove(), and TryUseAbility().
The documentation for this class was generated from the following file:
Elin/GoalCombat.cs