Elin Decompiled Documentation: HotAction Class Reference
HotAction Class Reference
Public Member Functions
override void OnClick (ButtonHotItem b, Hotbar h)
virtual void Perform ()
override void OnShowContextMenu (UIContextMenu m)
Public Member Functions inherited from HotItem
string TextHotkey ()
virtual void OnClick (ButtonHotItem b, Hotbar h)
virtual void OnRightClick (ButtonHotItem b)
virtual bool CanAutoFire (Chara tg)
virtual void OnSetCurrentItem ()
virtual void OnUnsetCurrentItem ()
virtual void OnUnselect ()
virtual void SetImage (Image icon)
virtual bool TrySetAct (ActPlan p)
virtual void OnMarkMapHighlights ()
virtual void OnRenderTile (Point point, HitResult result, int dir)
Public Member Functions inherited from UIButton.Item
virtual Sprite GetSprite ()
virtual Sprite GetSprite (bool highlight)
virtual bool ShouldHighlight ()
virtual void OnAddedToBar ()
virtual void OnShowContextMenu (UIContextMenu m)
virtual void OnHover (UIButton b)
virtual void OnClick (UIButton b)
virtual void OnSetItem (UIButton b)
virtual void SetSubText (UIText t)
Public Attributes
int _bgColor
string text
Public Attributes inherited from HotItem
ButtonHotItem button
Hotbar hotbar
bool disabled
Public Attributes inherited from UIButton.Item
bool always
Properties
Color bgColor [get, set]
override Color SpriteColor [get]
virtual string Id [get]
virtual bool CanChangeIconColor [get]
virtual bool CanName [get]
override string Name [get]
override string pathSprite [get]
Properties inherited from HotItem
override Sprite SpriteHighlight [get]
override bool IsSelectable [get]
override string TextTip [get]
virtual Thing RenderThing [get]
virtual Thing Thing [get]
virtual Thing Tool [get]
virtual bool IsTool [get]
virtual bool LookAtMouse [get]
virtual bool IsGameAction [get]
virtual bool UseUIObjMaterial [get]
Properties inherited from UIButton.Item
virtual string TextTip [get]
virtual string Name [get]
virtual Sprite SpriteHighlight [get]
virtual string pathSprite [get]
virtual bool IsSelectable [get]
virtual bool AdjustImageSize [get]
virtual bool UseIconForHighlight [get]
virtual bool KeepVisibleWhenHighlighted [get]
virtual Color SpriteColor [get]
virtual Vector3 SpriteScale [get]
virtual bool Hidden [get]
virtual Transition Transition [get]
Detailed Description
Definition at line 4 of file HotAction.cs.
Member Function Documentation
OnClick()
override void HotAction.OnClick (ButtonHotItem b, Hotbar h) inline virtual
Reimplemented from HotItem.
Definition at line 46 of file HotAction.cs.
    {
        if (!EClass.player.CanAcceptInput())
        {
            SE.Beep();
        }
        else
        {
            Perform();
        }
    }
References Player.CanAcceptInput(), Perform(), and EClass.player.
OnShowContextMenu()
override void HotAction.OnShowContextMenu (UIContextMenu m) inline virtual
Reimplemented from UIButton.Item.
Reimplemented in HotItemEQSet, HotItemLayout, and HotItemWidgetSet.
Definition at line 62 of file HotAction.cs.
    {
        base.OnShowContextMenu(m);
        if (CanName)
        {
            m.AddButton("changeName", delegate
            {
                Dialog.InputName("dialogChangeName", text.IsEmpty(""), delegate(bool cancel, string t)
                {
                    if (!cancel)
                    {
                        text = t;
                    }
                });
            });
        }
        if (!CanChangeIconColor)
        {
            return;
        }
        m.AddButton("actChangeColor", delegate
        {
            if (_bgColor == 0)
            {
                bgColor = Color.white;
            }
            EClass.ui.AddLayer<LayerColorPicker>().SetColor(bgColor, Color.white, delegate(PickerState state, Color _c)
            {
                bgColor = _c;
                button.icon.color = _c;
            });
        });
    }
References _bgColor, UIContextMenu.AddButton(), bgColor, CanChangeIconColor, CanName, Color, Dialog.InputName(), text, and EClass.ui.
Perform()
virtual void HotAction.Perform () inline virtual
Reimplemented in HotItemActionAudoDump, HotItemActionSleep, HotItemEQSet, HotItemFocusPos, HotItemLayout, and HotItemWidgetSet.
Definition at line 58 of file HotAction.cs.
    {
    }
Referenced by OnClick().
Member Data Documentation
_bgColor
int HotAction._bgColor
Definition at line 7 of file HotAction.cs.
Referenced by OnShowContextMenu().
text
string HotAction.text
Definition at line 10 of file HotAction.cs.
Referenced by OnShowContextMenu().
Property Documentation
bgColor
Color HotAction.bgColor get set
Definition at line 12 of file HotAction.cs.
    {
        get
        {
            return IntColor.FromInt(_bgColor);
        }
        set
        {
            _bgColor = IntColor.ToInt(ref value);
        }
    }
Referenced by OnShowContextMenu().
CanChangeIconColor
virtual bool HotAction.CanChangeIconColor get
Definition at line 38 of file HotAction.cs.
Referenced by OnShowContextMenu().
CanName
virtual bool HotAction.CanName get
Definition at line 40 of file HotAction.cs.
Referenced by OnShowContextMenu().
Id
virtual string HotAction.Id get
Definition at line 36 of file HotAction.cs.
Name
override string HotAction.Name get
Definition at line 42 of file HotAction.cs.
pathSprite
override string HotAction.pathSprite get
Definition at line 44 of file HotAction.cs.
SpriteColor
override Color HotAction.SpriteColor get
Definition at line 24 of file HotAction.cs.
    {
        get
        {
            if (!CanChangeIconColor || _bgColor == 0)
            {
                return base.SpriteColor;
            }
            return bgColor;
        }
    }
The documentation for this class was generated from the following file:
Elin/HotAction.cs