Elin Decompiled Documentation: WidgetSearch Class Reference
WidgetSearch Class Reference
Classes
class Extra
class Word
Public Member Functions
override object CreateExtra ()
override void OnActivate ()
override bool CheckClose ()
void RefreshSearch ()
override void Search (string s)
void RefreshWords ()
override void RefreshList ()
override void OnDeactivate ()
Public Member Functions inherited from WidgetCodex
override void OnActivate ()
void Clear ()
virtual void Search (string s)
virtual void RefreshList ()
virtual bool CheckClose ()
Public Member Functions inherited from Widget
void Test ()
bool IsInRightMode ()
void Activate ()
void RefreshOrder ()
virtual void OnActivate ()
virtual object CreateExtra ()
void Deactivate ()
virtual void OnDeactivate ()
void Close ()
void Reactivate ()
virtual void OnManagerActivate ()
virtual void OnManagerDeactivate ()
void SetAnchor (RectPosition p)
void SetPivot (RectPosition p)
virtual void OnChangePivot ()
void UpdateConfig ()
virtual void OnUpdateConfig ()
void ClampToScreen ()
virtual void OnChangeResolution ()
void OnChangePosition ()
virtual void OnChangeActionMode ()
virtual void OnFlip ()
bool IsAlignTop ()
Layer AddLayer (Layer l, Transform trans)
void RefreshTipPivotPosition ()
SkinSet GetSkin ()
SkinConfig GetSkinConfig ()
void SetSkin (int id, int v=0)
void TestSkin ()
virtual void ApplySkin ()
virtual void OnApplySkin ()
void InstantiateDeco (SkinDeco deco)
void AddDeco (SkinDeco deco)
void RemoveDeco (SkinDeco deco)
virtual bool CanShowContextMenu ()
void ShowContextMenu ()
void SetBaseContextMenu (UIContextMenu m)
virtual void OnSetContextMenu (UIContextMenu m)
void SetGridContextMenu (UIContextMenu m)
void SoundActivate ()
void OnChangeResolution ()
SkinSet GetSkin ()
SkinConfig GetSkinConfig ()
Public Attributes
HashSet< Card > cards = new HashSet<Card>()
CanvasGroup cgResult
UIList listWords
Zone lastZone
Public Attributes inherited from WidgetCodex
InputField field
WordSearch search = new WordSearch()
UIDynamicList list
HashSet< Recipe > recipes = new HashSet<Recipe>()
string lastSearch
UIButton buttonClear
UIButton buttonRefresh
Transform transResult
Public Attributes inherited from Widget
Image imageBG
SoundData soundActivate
UIDragPanel dragPanel
RectTransform tipPivotLeft
RectTransform tipPivotRight
Static Public Attributes
static WidgetSearch Instance
static Card selected
Static Public Attributes inherited from EMono
static Core core
Properties
Extra extra [get]
override SearchType type [get]
Properties inherited from WidgetCodex
virtual SearchType type [get]
Properties inherited from Widget
string ID [get]
Config config [get]
SkinRoot skinRoot [get]
bool IsSealed [get]
virtual bool ShowStyleMenu [get]
virtual bool AlwaysTop [get]
virtual bool IsStaticPosition [get]
virtual bool AlwaysBottom [get]
virtual Type SetSiblingAfter [get]
virtual bool ShowInBuildMode [get]
virtual bool RightClickToClose [get]
virtual bool AllowRightClickToClose [get]
Properties inherited from EMono
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SoundManager Sound [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static CoreDebug debug [get]
Private Member Functions
new void Update ()
Private Attributes
bool isDirty
Additional Inherited Members
Public Types inherited from WidgetCodex
enum SearchType { Codex , Search }
Public Types inherited from Widget
enum WidgetType { Default , ZoomMenu }
enum State { Active , Inactive }
Static Public Member Functions inherited from EMono
static int rnd (int a)
Protected Member Functions inherited from WidgetCodex
void Update ()
Protected Member Functions inherited from Widget
void ClampToScreenEnsured (Component c, Vector2 anchoredPos)
void ClampToScreen (RectTransform rect, float margin=10f)
Protected Attributes inherited from Widget
bool flip
Detailed Description
Definition at line 5 of file WidgetSearch.cs.
Member Function Documentation
CheckClose()
override bool WidgetSearch.CheckClose () inline virtual
Reimplemented from WidgetCodex.
Definition at line 73 of file WidgetSearch.cs.
    {
        if (Input.GetKey(KeyCode.LeftControl))
        {
            return Input.GetKeyDown(KeyCode.F);
        }
        return false;
    }
CreateExtra()
override object WidgetSearch.CreateExtra () inline virtual
Reimplemented from Widget.
Definition at line 43 of file WidgetSearch.cs.
    {
        return new Extra();
    }
OnActivate()
override void WidgetSearch.OnActivate () inline virtual
Reimplemented from WidgetCodex.
Definition at line 48 of file WidgetSearch.cs.
    {
        base.OnActivate();
        Instance = this;
        selected = null;
        if (extra.words == null)
        {
            extra.words = new List<Word>();
            string[] array = Lang.GetList("search_words");
            foreach (string text in array)
            {
                extra.words.Add(new Word
                {
                    text = text
                });
            }
        }
        RefreshWords();
        RefreshList();
        if (!extra.lastSearch.IsEmpty())
        {
            field.text = extra.lastSearch;
        }
    }
References extra, Lang.GetList(), Instance, WidgetSearch.Extra.lastSearch, RefreshList(), RefreshWords(), selected, and WidgetSearch.Extra.words.
OnDeactivate()
override void WidgetSearch.OnDeactivate () inline virtual
Reimplemented from Widget.
Definition at line 326 of file WidgetSearch.cs.
    {
        base.OnDeactivate();
        if (field.text.IsEmpty())
        {
            extra.lastSearch = "";
        }
        LayerInventory.SetDirtyAll();
    }
References LayerInventory.SetDirtyAll().
RefreshList()
override void WidgetSearch.RefreshList () inline virtual
Reimplemented from WidgetCodex.
Definition at line 271 of file WidgetSearch.cs.
    {
        LayerInventory.SetDirtyAll();
        selected = null;
        list.callbacks = new UIList.Callback<Card, ButtonGrid>
        {
            onClick = delegate(Card a, ButtonGrid b)
            {
                Card rootCard = a.GetRootCard();
                if (rootCard == EMono.pc)
                {
                    LayerInventory.SetDirtyAll();
                    selected = a;
                    SE.Click();
                }
                else if (EMono.pc.ai.IsNoGoal)
                {
                    if (a.isDestroyed || !rootCard.pos.IsValid)
                    {
                        SE.Beep();
                        Search(field.text);
                    }
                    else
                    {
                        SE.Click();
                        selected = null;
                        EMono.pc.SetAIImmediate(new AI_Goto(rootCard.pos.Copy(), 0));
                        ActionMode.Adv.SetTurbo(3);
                    }
                }
                else
                {
                    SE.Beep();
                }
            },
            onRedraw = delegate(Card a, ButtonGrid b, int i)
            {
                if (a.isDestroyed)
                {
                    isDirty = true;
                }
                b.SetCard(a, ButtonGrid.Mode.Search);
            },
            onList = delegate
            {
                foreach (Card card in cards)
                {
                    list.Add(card);
                }
            }
        };
        list.List();
        list.dsv.OnResize();
    }
References ActionMode.Adv, Chara.ai, card, Point.Copy(), Card.GetRootCard(), Card.isDestroyed, AIAct.IsNoGoal, Point.IsValid, EMono.pc, Card.pos, Search, Chara.SetAIImmediate(), ButtonGrid.SetCard(), LayerInventory.SetDirtyAll(), and AM_Adv.SetTurbo().
Referenced by OnActivate().
RefreshSearch()
void WidgetSearch.RefreshSearch () inline
Definition at line 98 of file WidgetSearch.cs.
    {
        SE.Tab();
        lastSearch = "";
        Search(field.text);
    }
References WidgetCodex.field, WidgetCodex.lastSearch, and WidgetCodex.Search.
RefreshWords()
void WidgetSearch.RefreshWords () inline
Definition at line 213 of file WidgetSearch.cs.
    {
        listWords.callbacks = new UIList.Callback<Word, UIItem>
        {
            onClick = delegate(Word a, UIItem b)
            {
                if (a.type == 1)
                {
                    if (field.text.IsEmpty())
                    {
                        SE.BeepSmall();
                    }
                    else
                    {
                        SE.ClickOk();
                        extra.words.Add(new Word
{
                            text = field.text
                        });
                        listWords.List();
                    }
                }
                else
                {
                    field.text = a.text;
                    SE.Tab();
                }
            },
            onInstantiate = delegate(Word a, UIItem b)
            {
                b.button1.mainText.SetText(a.text);
                b.button2.SetActive(a.type != 1);
                b.button2.SetOnClick(delegate
                {
                    extra.words.Remove(a);
                    SE.Trash();
                    listWords.List();
                });
            },
            onList = delegate
            {
                foreach (Word word in extra.words)
                {
                    listWords.Add(word);
                }
                if (extra.words.Count < 10)
                {
                    listWords.Add(new Word
                    {
                        text = "add_search_word".lang(),
                        type = 1
                    });
                }
            }
        };
        listWords.List();
    }
References UIList.Add(), UIItem.button1, UIItem.button2, UIList.List(), UIButton.mainText, UIText.SetText(), WidgetSearch.Word.text, WidgetSearch.Word.type, and WidgetSearch.Extra.words.
Referenced by OnActivate().
Search()
override void WidgetSearch.Search (string s) inline virtual
Reimplemented from WidgetCodex.
Definition at line 105 of file WidgetSearch.cs.
    {
        if (!s.IsEmpty())
        {
            extra.lastSearch = s;
        }
        s = s.ToLower();
        if (!buttonClear)
        {
            return;
        }
        buttonClear.SetActive(field.text != "");
        buttonRefresh.SetActive(field.text != "");
        if (s == lastSearch || s.Length == 0)
        {
            return;
        }
        lastSearch = s;
        lastZone = EMono._zone;
        bool encSearch = s.Length >= 2 && (s[0] == '@' || s[0] == '');
        if (encSearch)
        {
            s = s.Substring(1);
        }
        HashSet<Card> newCards = new HashSet<Card>();
        if (!s.IsEmpty())
        {
            if (!encSearch && (EMono._zone.IsTown || EMono._zone.HasLaw || EMono._zone.IsPCFaction || EMono._zone is Zone_Tent))
            {
                foreach (Chara chara in EMono._map.charas)
                {
                    if (chara.IsNeutralOrAbove() && (chara.Name.ToLower().Contains(s) || chara.sourceCard.GetSearchName(jp: false).Contains(s)))
                    {
                        newCards.Add(chara);
                    }
                }
            }
            if (EMono._zone.IsPCFaction || EMono._zone is Zone_Tent)
            {
                foreach (Thing thing2 in EMono._map.things)
                {
                    if (encSearch)
                    {
                        if (thing2.MatchEncSearch(s))
{
                            newCards.Add(thing2);
                        }
                    }
                    else if (thing2.Name.ToLower().Contains(s) || thing2.sourceCard.GetSearchName(jp: false).Contains(s))
                    {
                        newCards.Add(thing2);
                    }
                }
                foreach (Card item in EMono._map.props.stocked.all)
                {
                    if (!(item.parent is Thing thing) || !thing.trait.CanSearchContent)
                    {
                        continue;
                    }
                    if (encSearch)
                    {
                        if (item.MatchEncSearch(s))
{
                            newCards.Add(item);
                        }
                    }
                    else if (item.Name.ToLower().Contains(s) || item.sourceCard.GetSearchName(jp: false).Contains(s))
                    {
                        newCards.Add(item);
                    }
                }
            }
            for (int i = 0; i < 2; i++)
            {
                foreach (Chara chara2 in EMono._map.charas)
                {
                    if ((i == 0 && chara2 == EMono.pc) || (i == 1 && chara2 != EMono.pc) || !chara2.IsPCFactionOrMinion)
                    {
                        continue;
                    }
                    chara2.things.Foreach(delegate(Thing t)
                    {
                        if (!((t.parent as Card)?.trait is TraitChestMerchant))
{
                            if (encSearch)
{
                                if (t.MatchEncSearch(s))
{
                                    newCards.Add(t);
                                }
                            }
                            else if (t.Name.ToLower().Contains(s) || t.source.GetSearchName(jp: false).Contains(s))
{
                                newCards.Add(t);
                            }
                        }
                    });
                }
            }
        }
        if (!newCards.SetEquals(cards))
        {
            cards = newCards;
            RefreshList();
        }
        cgResult.alpha = ((list.ItemCount > 0) ? 1f : 0f);
    }
References EMono._map, EMono._zone, Props.all, WidgetCodex.buttonClear, WidgetCodex.buttonRefresh, Map.charas, WidgetCodex.field, ThingContainer.Foreach(), RenderRow.GetSearchName(), Zone.HasLaw, if(), Chara.IsNeutralOrAbove(), Zone.IsPCFaction, Card.IsPCFactionOrMinion, Zone.IsTown, item, WidgetCodex.lastSearch, lastZone, Thing.MatchEncSearch(), Card.Name, Card.parent, EMono.pc, Map.props, Thing.source, Chara.sourceCard, Thing.sourceCard, PropsManager.stocked, Card.things, and Map.things.
Update()
new void WidgetSearch.Update () inline private
Definition at line 82 of file WidgetSearch.cs.
    {
        if (EMono.scene.actionMode.IsFuncPressed(CoreConfig.GameFunc.PropertySearch))
        {
            EMono.ui.widgets.DeactivateWidget(this);
            return;
        }
        base.Update();
        if (lastZone != EMono._zone || isDirty)
        {
            lastSearch = "";
            Search(field.text);
            isDirty = false;
        }
    }
References EMono._zone, Scene.actionMode, WidgetCodex.field, isDirty, ActionMode.IsFuncPressed(), WidgetCodex.lastSearch, lastZone, EMono.scene, WidgetCodex.Search, and EMono.ui.
Member Data Documentation
cards
HashSet<Card> WidgetSearch.cards = new HashSet<Card>()
Definition at line 27 of file WidgetSearch.cs.
cgResult
CanvasGroup WidgetSearch.cgResult
Definition at line 31 of file WidgetSearch.cs.
Instance
WidgetSearch WidgetSearch.Instance static
Definition at line 25 of file WidgetSearch.cs.
Referenced by OnActivate(), AM_BaseGameMode.OnUpdateInput(), and LayerInventory.TryShowGuide().
isDirty
bool WidgetSearch.isDirty private
Definition at line 37 of file WidgetSearch.cs.
Referenced by Update().
lastZone
Zone WidgetSearch.lastZone
Definition at line 35 of file WidgetSearch.cs.
Referenced by Search(), and Update().
listWords
UIList WidgetSearch.listWords
Definition at line 33 of file WidgetSearch.cs.
selected
Card WidgetSearch.selected static
Definition at line 29 of file WidgetSearch.cs.
Referenced by OnActivate(), and LayerInventory.TryShowGuide().
Property Documentation
extra
Extra WidgetSearch.extra get
Definition at line 39 of file WidgetSearch.cs.
Referenced by OnActivate().
type
override SearchType WidgetSearch.type get
Definition at line 41 of file WidgetSearch.cs.
The documentation for this class was generated from the following file:
Elin/WidgetSearch.cs