Elin Decompiled Documentation: EloMapActor Class Reference
EloMapActor Class Reference
Public Member Functions
void Initialize (EloMap _elomap)
void OnActivate ()
void OnDeactivate ()
void OnChangeHour ()
EloMap GetEloMap ()
void OnKillGame ()
Public Attributes
EloMap elomap
Transform transMap
Transform transLight
Transform moldLight
Tileset tileset
EloMapTileSelector selector
List< EloMapLight > lights = new List<EloMapLight>()
Properties
bool IsActive [get]
Properties inherited from EMono
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SoundManager Sound [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static CoreDebug debug [get]
Private Member Functions
void Awake ()
Additional Inherited Members
Static Public Member Functions inherited from EMono
static int rnd (int a)
Static Public Attributes inherited from EMono
static Core core
Detailed Description
Definition at line 5 of file EloMapActor.cs.
Member Function Documentation
Awake()
void EloMapActor.Awake () inline private
Definition at line 23 of file EloMapActor.cs.
    {
        this.SetActive(enable: false);
    }
GetEloMap()
EloMap EloMapActor.GetEloMap () inline
Definition at line 82 of file EloMapActor.cs.
    {
        Initialize(EMono.world.region.elomap);
        return elomap;
    }
References elomap, Region.elomap, Initialize(), World.region, and EMono.world.
Initialize()
void EloMapActor.Initialize (EloMap _elomap) inline
Definition at line 28 of file EloMapActor.cs.
    {
        elomap = _elomap;
        if (!transMap)
        {
            transMap = Util.Instantiate<Transform>(elomap.idMap);
            transLight = Object.Instantiate(moldLight);
            lights.Clear();
            transMap.SetActive(enable: false);
            transLight.SetActive(enable: false);
            EMono.scene.screenElona.SetUnitSize();
        }
        if (!elomap.initialized)
        {
            elomap.Init(this);
        }
        STETilemap fogmap = elomap.fogmap;
        transMap.position = new Vector3((float)(-fogmap.MinGridX) * EMono.scene.screenElona.tileAlign.x + EMono.scene.screenElona.actorPos.x, (float)(-fogmap.MinGridY) * EMono.scene.screenElona.tileAlign.y + EMono.scene.screenElona.actorPos.y, EMono.scene.screenElona.actorPos.z);
    }
References GameScreenElona.actorPos, elomap, EloMap.fogmap, EloMap.idMap, EloMap.Init(), EloMap.initialized, lights, moldLight, EMono.scene, Scene.screenElona, GameScreenElona.SetUnitSize(), BaseGameScreen.tileAlign, transLight, transMap, and Util.
Referenced by Zone.Activate(), Region.CanCreateZone(), GetEloMap(), Zone.GetProfile(), EloMap.GetRoadDist(), Region.InitElomap(), MapGenRegion.OnGenerateTerrain(), and LayerTreasureMap.SetMap().
OnActivate()
void EloMapActor.OnActivate () inline
Definition at line 48 of file EloMapActor.cs.
    {
        transLight.SetActive(enable: true);
        foreach (EloMapLight light in lights)
        {
            light.sr.transform.position = TilemapUtils.GetGridWorldPos(elomap.fogmap, light.gx, light.gy);
        }
        OnChangeHour();
        elomap.objmap.UpdateMesh();
    }
References elomap, EloMap.fogmap, EloMapLight.gx, EloMapLight.gy, lights, EloMap.objmap, OnChangeHour(), and transLight.
Referenced by GameScreenElona.OnActivate().
OnChangeHour()
void EloMapActor.OnChangeHour () inline
Definition at line 71 of file EloMapActor.cs.
    {
        Color white = Color.white;
        white.a = EMono.scene.profile.light.orbitAlphaCurve.Evaluate(EMono.scene.timeRatio);
        white.a *= white.a;
        foreach (EloMapLight light in lights)
        {
            light.sr.color = white;
        }
    }
References Color, SceneProfile.light, lights, SceneLightProfile.orbitAlphaCurve, Scene.profile, EMono.scene, and Scene.timeRatio.
Referenced by OnActivate(), and GameScreenElona.OnChangeHour().
OnDeactivate()
void EloMapActor.OnDeactivate () inline
Definition at line 59 of file EloMapActor.cs.
    {
        if ((bool)transMap)
        {
            transMap.SetActive(enable: false);
        }
        if ((bool)transLight)
        {
            transLight.SetActive(enable: false);
        }
    }
References transLight, and transMap.
Referenced by GameScreenElona.OnDeactivate().
OnKillGame()
void EloMapActor.OnKillGame () inline
Definition at line 88 of file EloMapActor.cs.
    {
        this.SetActive(enable: false);
        if ((bool)transMap)
        {
            transLight.SetActive(enable: false);
            transMap.SetActive(enable: false);
        }
        if ((bool)transMap)
        {
            Object.DestroyImmediate(transMap.gameObject);
            Object.DestroyImmediate(transLight.gameObject);
            lights.Clear();
        }
    }
References lights, transLight, and transMap.
Referenced by Scene.OnKillGame().
Member Data Documentation
elomap
EloMap EloMapActor.elomap
Definition at line 7 of file EloMapActor.cs.
Referenced by Region.CanCreateZone(), GetEloMap(), Zone.GetProfile(), Initialize(), OnActivate(), MapGenRegion.OnGenerateTerrain(), GameScreenElona.RefreshPosition(), Weather.RefreshWeather(), RegionPoint.SetRegionPoint(), and WidgetDebug.UpdateText().
lights
List<EloMapLight> EloMapActor.lights = new List<EloMapLight>()
Definition at line 19 of file EloMapActor.cs.
Referenced by EloMap.AddLight(), Initialize(), OnActivate(), OnChangeHour(), OnKillGame(), and EloMap.RemoveLight().
moldLight
Transform EloMapActor.moldLight
Definition at line 13 of file EloMapActor.cs.
Referenced by Initialize().
selector
EloMapTileSelector EloMapActor.selector
Definition at line 17 of file EloMapActor.cs.
Referenced by UI.Hide(), and UI.Show().
tileset
Tileset EloMapActor.tileset
Definition at line 15 of file EloMapActor.cs.
Referenced by RankedZone.GetSprite(), EloMap.GetTileInfo(), LayerTravel.Refresh(), and TraitMapBoard.TrySetAct().
transLight
Transform EloMapActor.transLight
Definition at line 11 of file EloMapActor.cs.
Referenced by EloMap.AddLight(), Initialize(), OnActivate(), OnDeactivate(), and OnKillGame().
transMap
Transform EloMapActor.transMap
Definition at line 9 of file EloMapActor.cs.
Referenced by EloMap.Init(), Initialize(), GameScreenElona.OnActivate(), OnDeactivate(), OnKillGame(), and LayerTreasureMap.SetMap().
Property Documentation
IsActive
bool EloMapActor.IsActive get
Definition at line 21 of file EloMapActor.cs.
Referenced by BaseGameScreen.ModTargetZoomIndex(), and Scene.OnUpdate().
The documentation for this class was generated from the following file:
Elin/EloMapActor.cs