Elin Decompiled Documentation: ZoneEventSurvival Class Reference
ZoneEventSurvival Class Reference
Public Member Functions
override void OnTickRound ()
Public Member Functions inherited from ZoneEvent
virtual string GetText ()
void Tick (float delta)
void Init ()
void OnSimulateHour ()
virtual void OnVisit ()
virtual void OnInit ()
virtual void OnFirstTick ()
virtual void OnTick ()
virtual void OnTickRound ()
virtual void OnKill ()
virtual void OnCharaDie (Chara c)
virtual void OnLeaveZone ()
virtual void OnLoad ()
void Kill ()
Additional Inherited Members
Static Public Member Functions inherited from EClass
static int rndSeed (int a, int seed)
static int rnd (long a)
static int rnd (int a)
static int curve (int _a, int start, int step, int rate=75)
static int sqrt (int a)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Public Attributes inherited from ZoneEvent
float time
int rounds
int hoursElapsed
int minElapsed
Zone zone
bool firstTick = true
Static Public Attributes inherited from EClass
static Core core
Properties inherited from ZoneEvent
SourceQuest.Row source [get]
virtual string id [get]
virtual string TextWidgetDate [get]
virtual float roundInterval [get]
virtual Playlist playlist [get]
virtual bool debugSkip [get]
virtual string RefStr2 [get]
virtual string RefStr3 [get]
virtual int hoursToKill [get]
virtual bool HasReport [get]
string Name [get]
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Detailed Description
Definition at line 1 of file ZoneEventSurvival.cs.
Member Function Documentation
OnTickRound()
override void ZoneEventSurvival.OnTickRound () inline virtual
Reimplemented from ZoneEvent.
Definition at line 3 of file ZoneEventSurvival.cs.
    {
        if (EClass._map.cells.GetLength(0) <= 100)
        {
            return;
        }
        Cell cell = EClass._map.cells[100, 100];
        if (!cell.HasObj)
        {
            EClass._map.SetObj(cell.x, cell.z, 46);
        }
        if (EClass.game.survival.flags.raid)
        {
            TraitVoidgate traitVoidgate = EClass._map.FindThing<TraitVoidgate>();
            if (traitVoidgate != null)
            {
                traitVoidgate.owner.isOn = EClass.game.survival.IsInRaid;
            }
            if (!EClass.game.survival.IsInRaid)
            {
                EClass.world.date.GetRemainingHours(EClass.game.survival.flags.dateNextRaid);
                _ = 0;
            }
        }
    }
References EClass._map, Map.cells, World.date, SurvivalManager.Flags.dateNextRaid, Map.FindThing(), SurvivalManager.flags, EClass.game, Date.GetRemainingHours(), Cell.HasObj, SurvivalManager.IsInRaid, SurvivalManager.Flags.raid, Map.SetObj(), Game.survival, EClass.world, Cell.x, and Cell.z.
The documentation for this class was generated from the following file:
Elin/ZoneEventSurvival.cs