Elin Decompiled Documentation: UIDynamicList Class Reference
UIDynamicList Class Reference
Classes
class Row
Public Member Functions
Row NewRow ()
override void Clear ()
override void Add (object o)
void RemoveObj (object o)
void AddHeader (Action< UIItem > onSetHeader)
void Refresh ()
int GetIndex (object o)
void UpdateRow (DSVRow dsvRow, int index)
override void Redraw ()
override void List ()
override void List (UIList.SortMode m)
void OnResizeWindow ()
void Select< T > (Func< T, bool > func, bool invoke=false)
bool Select (object o, bool invoke=false)
bool RefreshHighlight (bool invoke=false)
void Scroll (int index=0)
void Scroll (object o)
T GetComp< T > (object o)
Public Member Functions inherited from BaseList
virtual void NextSort ()
virtual void List ()
virtual void List (UIList.SortMode sort)
virtual void Redraw ()
virtual void Clear ()
virtual void Add (object o)
void RefreshNoItem ()
void RefreshBGGrid ()
Public Attributes
DynamicScrollView dsv
Transform moldItem
Transform moldHeader
int columns = 1
bool autoSize = true
bool captureScreen = true
bool refreshHighlight = true
bool rebuildLayout = true
bool useGrid
bool useHighlight
List< Row > rows = new List<Row>()
List< object > objects = new List<object>()
object selectedObject
float minHeight
bool first = true
Public Attributes inherited from BaseList
UIList.BGType bgType
Vector2 bgFix
Vector2 bgUvFix = Vector2.one
UIList.ICallback callbacks
UIList.SortMode[] sorts
Action onBeforeRedraw
Action onAfterRedraw
bool useDefaultNoItem = true
bool numbering
SkinType skinType
RawImage bgGrid
UIList.SortMode sortMode
bool isBuilt
Properties
override int ItemCount [get]
override int RowCount [get]
Properties inherited from BaseList
virtual int ItemCount [get]
virtual int RowCount [get]
SkinRootStatic Skin [get]
Private Member Functions
void _Add (object o)
Private Attributes
bool autoSized
Additional Inherited Members
Protected Attributes inherited from BaseList
Transform transNoItem
Detailed Description
Definition at line 7 of file UIDynamicList.cs.
Member Function Documentation
_Add()
void UIDynamicList._Add (object o) inline private
Definition at line 80 of file UIDynamicList.cs.
    {
        if (autoSize && !autoSized)
        {
            autoSized = true;
            this.RebuildLayoutTo<Layer>();
            GridLayoutGroup component = dsv.itemPrototype.GetComponent<GridLayoutGroup>();
            columns = (int)(this.Rect().rect.width / (component.spacing.x + component.cellSize.x));
            if (columns < 1)
            {
                columns = 1;
            }
        }
        if (rows.Count == 0)
        {
            NewRow();
        }
        Row row = rows.LastItem();
        if (row.objects.Count >= columns)
        {
            row = NewRow();
        }
        row.objects.Add(o);
    }
References autoSize, autoSized, columns, dsv, Mosframe.DynamicScrollView.itemPrototype, NewRow(), UIDynamicList.Row.objects, and rows.
Referenced by List().
Add()
override void UIDynamicList.Add (object o) inline virtual
Reimplemented from BaseList.
Definition at line 68 of file UIDynamicList.cs.
    {
        if (o == null)
        {
            Debug.Log("Tried to add null object");
        }
        else
        {
            objects.Add(o);
        }
    }
References Debug, and objects.
Referenced by LayerCraft.GetTargets(), DramaEventEndRoll.Init(), ContentHomeRanking.Refresh(), PartialMapMenu.Refresh(), BuildMenu.RefreshCategory(), LayerCraft.RefreshCategory(), BuildMenu.RefreshCategoryArea(), LayerCraftFloat.RefreshCraft(), LayerCraftFloat.RefreshDisassemble(), ContentCodex.RefreshList(), LayerEditPortrait.RefreshList(), LayerEditSkin.RefreshList(), WidgetCodex.RefreshList(), LayerCraft.RefreshProduct(), UIBook.Search(), LayerAbility.SelectGroup(), and LayerResource.ShowThings().
AddHeader()
void UIDynamicList.AddHeader (Action< UIItem > onSetHeader) inline
Definition at line 109 of file UIDynamicList.cs.
    {
        Row row = NewRow();
        row.isHeader = true;
        row.onSetHeader = onSetHeader;
        NewRow();
    }
References NewRow().
Clear()
override void UIDynamicList.Clear () inline virtual
Reimplemented from BaseList.
Definition at line 62 of file UIDynamicList.cs.
    {
        rows.Clear();
        objects.Clear();
    }
References objects, and rows.
Referenced by DramaEventEndRoll.Init(), List(), ContentHomeRanking.Refresh(), BuildMenu.RefreshCategory(), BuildMenu.RefreshCategoryArea(), ContentCodex.RefreshList(), LayerEditPortrait.RefreshList(), LayerEditSkin.RefreshList(), UIBook.Search(), and LayerAbility.SelectGroup().
GetComp< T >()
T UIDynamicList.GetComp< T > (object o) inline
Type Constraints
T : Component
Definition at line 383 of file UIDynamicList.cs.
                                          : Component
    {
        foreach (DSVRow container in dsv.containers)
        {
            foreach (DSVRow.Item item in container.items)
            {
                if (item.obj == o)
                {
                    return item.comp as T;
                }
            }
        }
        return null;
    }
References Mosframe.DynamicScrollView.containers, dsv, item, and DSVRow.items.
GetIndex()
int UIDynamicList.GetIndex (object o) inline
Definition at line 135 of file UIDynamicList.cs.
    {
        for (int i = 0; i < rows.Count; i++)
        {
            for (int j = 0; j < rows[i].objects.Count; j++)
            {
                if (rows[i].objects[j] == o)
                {
                    return i;
                }
            }
        }
        return -1;
    }
References objects, and rows.
Referenced by BuildMenu.Select().
List() [1/2]
override void UIDynamicList.List () inline virtual
Reimplemented from BaseList.
Definition at line 235 of file UIDynamicList.cs.
    {
        List(sortMode);
    }
References List(), and BaseList.sortMode.
Referenced by LayerAbility._Redraw(), LayerEditPortrait.Activate(), DramaEventEndRoll.Init(), List(), LayerAbility.OnInit(), OnResizeWindow(), Redraw(), ContentHomeRanking.Refresh(), PartialMapMenu.Refresh(), BuildMenu.RefreshCategory(), LayerCraft.RefreshCategory(), LayerCraftFloat.RefreshCraft(), LayerCraftFloat.RefreshDisassemble(), ContentCodex.RefreshList(), LayerEditPortrait.RefreshList(), LayerEditSkin.RefreshList(), WidgetCodex.RefreshList(), UIBook.Search(), LayerAbility.SelectGroup(), and LayerResource.ShowThings().
List() [2/2]
override void UIDynamicList.List (UIList::SortMode m) inline virtual
Reimplemented from BaseList.
Definition at line 240 of file UIDynamicList.cs.
    {
        if (!first && captureScreen)
        {
            BaseCore.Instance.FreezeScreen();
        }
        first = false;
        sortMode = m;
        Clear();
        callbacks.OnList(sortMode);
        foreach (object @object in objects)
        {
            _Add(@object);
        }
        Layer root = base.transform.GetComponentInParent<Layer>();
        root = root.parent?.GetComponent<Layer>() ?? root;
        if (objects.Count != 0)
        {
            if (refreshHighlight)
            {
                UIButton.TryHihlight();
                UIButton.TryShowTip(root.transform);
                BaseCore.Instance.WaitForEndOfFrame(delegate
                {
                    UIButton.TryHihlight();
                    UIButton.TryShowTip(root.transform);
                    if (captureScreen)
                    {
                        BaseCore.Instance.WaitForEndOfFrame(delegate
{
                            BaseCore.Instance.UnfreezeScreen();
                        });
                    }
                });
            }
        }
        else
        {
            TooltipManager.Instance.HideTooltips();
        }
        Refresh();
    }
References _Add(), BaseList.callbacks, captureScreen, Clear(), first, BaseCore.FreezeScreen(), TooltipManager.HideTooltips(), BaseCore.Instance, TooltipManager.Instance, objects, Layer.parent, Refresh(), refreshHighlight, BaseList.sortMode, UIButton.TryHihlight(), UIButton.TryShowTip(), BaseCore.UnfreezeScreen(), and BaseCore.WaitForEndOfFrame().
NewRow()
Row UIDynamicList.NewRow () inline
Definition at line 55 of file UIDynamicList.cs.
    {
        Row row = new Row();
        rows.Add(row);
        return row;
    }
References rows.
Referenced by _Add(), and AddHeader().
OnResizeWindow()
void UIDynamicList.OnResizeWindow () inline
Definition at line 283 of file UIDynamicList.cs.
    {
        if (autoSize)
        {
            this.RebuildLayoutTo<Layer>();
            GridLayoutGroup component = dsv.itemPrototype.GetComponent<GridLayoutGroup>();
            columns = (int)(this.Rect().rect.width / (component.spacing.x + component.cellSize.x));
            if (columns < 1)
            {
                columns = 1;
            }
            List();
            dsv.OnResize();
        }
    }
References autoSize, columns, dsv, Mosframe.DynamicScrollView.itemPrototype, List(), and Mosframe.DynamicScrollView.OnResize().
Referenced by Window.Update().
Redraw()
override void UIDynamicList.Redraw () inline virtual
Reimplemented from BaseList.
Definition at line 230 of file UIDynamicList.cs.
    {
        List();
    }
References List().
Referenced by ContentCodex.OnClickGetCard(), LayerCraft.OnCompleteCraft(), LayerEditPortrait.RefreshHairColor(), LayerAbility.SetDirty(), and ButtonAbility.ToggleFav().
Refresh()
void UIDynamicList.Refresh () inline
Definition at line 117 of file UIDynamicList.cs.
    {
        dsv.prevTotalItemCount = -1;
        dsv.totalItemCount = rows.Count;
        this.RebuildLayoutTo<Layer>();
        if (!isBuilt)
        {
            dsv.Build();
            isBuilt = true;
        }
        else
        {
            dsv.Update();
        }
        RefreshNoItem();
        RefreshBGGrid();
    }
References Mosframe.DynamicScrollView.Build(), dsv, BaseList.isBuilt, BaseList.RefreshBGGrid(), BaseList.RefreshNoItem(), rows, and Mosframe.DynamicScrollView.Update().
Referenced by List(), and BuildMenu.Select().
RefreshHighlight()
bool UIDynamicList.RefreshHighlight (bool invoke = false) inline
Definition at line 325 of file UIDynamicList.cs.
    {
        bool result = false;
        foreach (DSVRow container in dsv.containers)
        {
            foreach (DSVRow.Item item in container.items)
            {
                UIButton b = item.comp as UIButton;
                if (b == null || !b.gameObject.activeInHierarchy)
                {
                    continue;
                }
                b.selected = item.obj == selectedObject;
                if (b.selected)
                {
                    BaseCore.Instance.actionsNextFrame.Add(delegate
                    {
                        if (b != null)
{
                            b.DoNormalTransition();
                            b.DoHighlightTransition(instant: true);
                        }
                    });
                    result = true;
                    b.DoHighlightTransition(instant: true);
                    if (invoke)
                    {
                        callbacks.OnClick(item.obj, item.comp);
                    }
                }
                else
                {
                    b.DoNormalTransition();
                }
            }
        }
        return result;
    }
References BaseCore.actionsNextFrame, BaseList.callbacks, Mosframe.DynamicScrollView.containers, UIButton.DoHighlightTransition(), UIButton.DoNormalTransition(), dsv, BaseCore.Instance, item, DSVRow.items, UIButton.selected, and selectedObject.
Referenced by BuildMenu.Refresh(), and Select().
RemoveObj()
void UIDynamicList.RemoveObj (object o) inline
Definition at line 105 of file UIDynamicList.cs.
    {
    }
Scroll() [1/2]
void UIDynamicList.Scroll (int index = 0) inline
Definition at line 364 of file UIDynamicList.cs.
    {
        if (index <= 0)
        {
            dsv.contentAnchoredPosition = 0f;
        }
        else
        {
            dsv.scrollByItemIndex(index);
        }
        dsv.refresh();
    }
References dsv, Mosframe.DynamicScrollView.refresh(), and Mosframe.DynamicScrollView.scrollByItemIndex().
Referenced by BuildMenu.RefreshCategory(), LayerCraft.RefreshCategory(), and Scroll().
Scroll() [2/2]
void UIDynamicList.Scroll (object o) inline
Definition at line 377 of file UIDynamicList.cs.
    {
        int index = objects.IndexOf(o);
        Scroll(index);
    }
References objects, and Scroll().
Select()
bool UIDynamicList.Select (object o, bool invoke = false) inline
Definition at line 319 of file UIDynamicList.cs.
    {
        selectedObject = o;
        return RefreshHighlight(invoke);
    }
References RefreshHighlight(), and selectedObject.
Referenced by ContentCodex.OnClickGetCard(), LayerCraft.OnCompleteCraft(), ContentCodex.OnSwitchContent(), BuildMenu.RefreshCategory(), LayerCraft.RefreshCategory(), ContentCodex.RefreshList(), LayerEditPortrait.RefreshList(), LayerEditSkin.RefreshList(), Select< T >(), and BuildMenu.Unselect().
Select< T >()
void UIDynamicList.Select< T > (Func< T, bool > func, bool invoke = false) inline
Definition at line 299 of file UIDynamicList.cs.
    {
        foreach (DSVRow container in dsv.containers)
        {
            foreach (DSVRow.Item item in container.items)
            {
                UIButton uIButton = item.comp as UIButton;
                if (!(uIButton == null) && uIButton.gameObject.activeInHierarchy)
                {
                    T arg = (T)item.obj;
                    if (func(arg))
                    {
                        Select(item.obj, invoke);
                        return;
                    }
                }
            }
        }
    }
References Mosframe.DynamicScrollView.containers, dsv, if(), item, DSVRow.items, and Select().
UpdateRow()
void UIDynamicList.UpdateRow (DSVRow dsvRow, int index) inline
Definition at line 150 of file UIDynamicList.cs.
    {
        Row row = rows[index];
        for (int i = 0; i < columns; i++)
        {
            if (dsvRow.items.Count <= i)
            {
                dsvRow.items.Add(new DSVRow.Item
                {
                    comp = callbacks.GetComponent(Util.Instantiate(moldItem, dsvRow.transform).transform)
                });
            }
            Component comp = dsvRow.items[i].comp;
            bool flag = !row.isHeader && row.objects.Count > i;
            comp.SetActive(flag);
            dsvRow.items[i].obj = null;
            if (!flag)
            {
                continue;
            }
            object obj = row.objects[i];
            dsvRow.items[i].obj = obj;
            callbacks.OnRedraw(obj, comp, columns * index + i);
            UIButton uIButton = comp as UIButton;
            if (!uIButton)
            {
                uIButton = (comp as UIItem)?.button1;
            }
            if ((bool)uIButton && callbacks.useOnClick)
            {
                uIButton.onClick.RemoveAllListeners();
                uIButton.onClick.AddListener(delegate
                {
                    callbacks.OnClick(obj, comp);
                });
            }
            if (useHighlight)
            {
                uIButton.selected = obj == selectedObject;
                if (uIButton.selected)
                {
                    uIButton.DoHighlightTransition(instant: true);
                }
                else
                {
                    uIButton.DoNormalTransition();
                }
            }
        }
        if (dsvRow.items.Count > columns)
        {
            for (int j = columns; j < dsvRow.items.Count; j++)
            {
                dsvRow.items[j].comp.SetActive(enable: false);
                dsvRow.items[j].obj = null;
            }
        }
        if ((bool)dsvRow.itemHeader)
        {
            if (row.isHeader)
            {
                dsvRow.itemHeader.SetActive(enable: true);
                row.onSetHeader(dsvRow.itemHeader);
            }
            else
            {
                dsvRow.itemHeader.SetActive(enable: false);
            }
        }
        if ((bool)dsvRow.bgGrid)
        {
            dsvRow.bgGrid.SetActive(useGrid);
        }
        if (useGrid)
        {
            dsvRow.bgGrid.Rect().sizeDelta = new Vector2((float)row.objects.Count * dsvRow.GetComponent<GridLayoutGroup>().cellSize.x, 0f);
            dsvRow.bgGrid.uvRect = new Rect(0f, 0f, row.objects.Count, 1f);
        }
    }
References DSVRow.bgGrid, BaseList.callbacks, columns, UIButton.DoHighlightTransition(), UIButton.DoNormalTransition(), UIDynamicList.Row.isHeader, DSVRow.itemHeader, DSVRow.items, UIDynamicList.Row.objects, UIDynamicList.Row.onSetHeader, rows, UIButton.selected, selectedObject, useGrid, and useHighlight.
Referenced by Mosframe.DynamicScrollView.updateItem().
Member Data Documentation
autoSize
bool UIDynamicList.autoSize = true
Definition at line 26 of file UIDynamicList.cs.
Referenced by _Add(), and OnResizeWindow().
autoSized
bool UIDynamicList.autoSized private
Definition at line 49 of file UIDynamicList.cs.
Referenced by _Add().
captureScreen
bool UIDynamicList.captureScreen = true
Definition at line 28 of file UIDynamicList.cs.
Referenced by List().
columns
int UIDynamicList.columns = 1
Definition at line 24 of file UIDynamicList.cs.
Referenced by _Add(), OnResizeWindow(), and UpdateRow().
dsv
DynamicScrollView UIDynamicList.dsv
Definition at line 18 of file UIDynamicList.cs.
Referenced by _Add(), GetComp< T >(), OnResizeWindow(), DramaEventEndRoll.Play(), Refresh(), LayerCraftFloat.RefreshCraft(), LayerCraftFloat.RefreshDisassemble(), RefreshHighlight(), ContentCodex.RefreshList(), WidgetCodex.RefreshList(), LayerCraftFloat.RefreshSize(), Scroll(), BuildMenu.Select(), Select< T >(), and LayerResource.ShowThings().
first
bool UIDynamicList.first = true
Definition at line 47 of file UIDynamicList.cs.
Referenced by List().
minHeight
float UIDynamicList.minHeight
Definition at line 44 of file UIDynamicList.cs.
moldHeader
Transform UIDynamicList.moldHeader
Definition at line 22 of file UIDynamicList.cs.
moldItem
Transform UIDynamicList.moldItem
Definition at line 20 of file UIDynamicList.cs.
objects
List<object> UIDynamicList.objects = new List<object>()
Definition at line 40 of file UIDynamicList.cs.
Referenced by Add(), Clear(), GetIndex(), List(), BuildMenu.RefreshCategory(), LayerCraft.RefreshCategory(), ContentCodex.RefreshList(), Scroll(), and BuildMenu.Select().
rebuildLayout
bool UIDynamicList.rebuildLayout = true
Definition at line 32 of file UIDynamicList.cs.
refreshHighlight
bool UIDynamicList.refreshHighlight = true
Definition at line 30 of file UIDynamicList.cs.
Referenced by List().
rows
List<Row> UIDynamicList.rows = new List<Row>()
Definition at line 38 of file UIDynamicList.cs.
Referenced by _Add(), Clear(), GetIndex(), NewRow(), Refresh(), LayerCraft.RefreshCategory(), and UpdateRow().
selectedObject
object UIDynamicList.selectedObject
Definition at line 42 of file UIDynamicList.cs.
Referenced by RefreshHighlight(), Select(), and UpdateRow().
useGrid
bool UIDynamicList.useGrid
Definition at line 34 of file UIDynamicList.cs.
Referenced by UpdateRow().
useHighlight
bool UIDynamicList.useHighlight
Definition at line 36 of file UIDynamicList.cs.
Referenced by UpdateRow().
Property Documentation
ItemCount
override int UIDynamicList.ItemCount get
Definition at line 51 of file UIDynamicList.cs.
Referenced by LayerCraftFloat.RefreshSize().
RowCount
override int UIDynamicList.RowCount get
Definition at line 53 of file UIDynamicList.cs.
The documentation for this class was generated from the following file:
Elin/Plugins.UI/UIDynamicList.cs