Elin Decompiled Documentation: InspectGroup< T > Class Template Reference
InspectGroup< T > Class Template Reference
Classes
class Item
Public Member Functions
bool CanInspect ()
virtual bool Contains (IInspect t)
string GetName ()
virtual void SetActions ()
sealed override void SetActions ()
virtual void OnSetActions ()
Item Add (string text, string idSprite, Action action, bool sound=false, int priority=0, bool auto=false)
Item Add (string text, string idSprite, Action< T > action, bool sound=false, int priority=0, bool auto=false)
Static Public Member Functions
static InspectGroup Create (IInspect t)
Static Public Member Functions inherited from EClass
static int rndSeed (int a, int seed)
static int rnd (long a)
static int rnd (int a)
static int curve (int _a, int start, int step, int rate=75)
static int sqrt (int a)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Public Attributes
Type type
List< Item > actions = new List<Item>()
List< IInspect > targets = new List<IInspect>()
Properties
IInspect FirstTarget [get]
bool Solo [get]
virtual string MultiName [get]
new T FirstTarget [get]
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Additional Inherited Members
Static Public Attributes inherited from EClass
static Core core
Detailed Description
Type Constraints
T : IInspect
Definition at line 107 of file InspectGroup.cs.
Member Function Documentation
Add() [1/2]
Item InspectGroup< T >.Add (string text, string idSprite, Action action, bool sound = false, int priority = 0, bool auto = false) inline
Definition at line 121 of file InspectGroup.cs.
    {
        Item item = new Item
        {
            text = text,
            idSprite = idSprite,
            action = delegate
            {
                action();
            },
            sound = sound,
            priority = priority,
            auto = auto
        };
        actions.Add(item);
        return item;
    }
References InspectGroup< T >.actions, and item.
Referenced by AM_Select.OnRefreshSummary().
Add() [2/2]
Item InspectGroup< T >.Add (string text, string idSprite, Action< T > action, bool sound = false, int priority = 0, bool auto = false) inline
Definition at line 139 of file InspectGroup.cs.
    {
        Item item = new Item
        {
            text = text,
            idSprite = idSprite,
            action = delegate(IInspect a)
            {
                action((T)a);
            },
            sound = sound,
            priority = priority,
            auto = auto,
            multi = true
        };
        actions.Add(item);
        return item;
    }
References InspectGroup< T >.actions, and item.
CanInspect()
bool InspectGroup< T >.CanInspect () inline
Definition at line 73 of file InspectGroup.cs.
    {
        for (int num = targets.Count - 1; num >= 0; num--)
        {
            if (!targets[num].CanInspect)
            {
                targets.RemoveAt(num);
            }
        }
        if (targets.Count > 0)
        {
            return FirstTarget.CanInspect;
        }
        return false;
    }
References IInspect.CanInspect, InspectGroup< T >.CanInspect(), InspectGroup< T >.FirstTarget, and InspectGroup< T >.targets.
Referenced by InspectGroup< T >.CanInspect(), UIInspector.OnUpdate(), and UIInspector.Refresh().
Contains()
virtual bool InspectGroup< T >.Contains (IInspect t) inline virtual
Definition at line 89 of file InspectGroup.cs.
    {
        return targets.Contains(t);
    }
References InspectGroup< T >.targets.
Create()
static InspectGroup InspectGroup< T >.Create (IInspect t) inline static
Definition at line 37 of file InspectGroup.cs.
    {
        InspectGroup inspectGroup = null;
        if (t is Area)
        {
            inspectGroup = new InspectGroupArea();
        }
        else if (t is Chara)
        {
            inspectGroup = new InspectGroupChara();
        }
        else if (t is Thing)
        {
            inspectGroup = new InspectGroupThing();
        }
        else if (t is TaskPoint)
        {
            inspectGroup = new InspectGroupTask();
        }
        else if (t is ObjInfo)
        {
            inspectGroup = new InspectGroupObj();
        }
        else if (t is BlockInfo)
        {
            inspectGroup = new InspectGroupBlock();
        }
        else if (t is EloPos)
        {
            inspectGroup = new InspectGroupEloPos();
        }
        inspectGroup.type = t.GetType();
        inspectGroup.targets.Add(t);
        return inspectGroup;
    }
References InspectGroup< T >.targets.
Referenced by UIInspector.Inspect(), and AM_Select.OnRefreshSummary().
GetName()
string InspectGroup< T >.GetName () inline
Definition at line 94 of file InspectGroup.cs.
    {
        if (!Solo)
        {
            return MultiName + " x " + targets.Count;
        }
        return FirstTarget.InspectName;
    }
References InspectGroup< T >.FirstTarget, IInspect.InspectName, InspectGroup< T >.MultiName, InspectGroup< T >.Solo, and InspectGroup< T >.targets.
Referenced by AM_Select.SetMouseInfo().
OnSetActions()
virtual void InspectGroup< T >.OnSetActions () inline virtual
Reimplemented in InspectGroupArea, InspectGroupBlock, InspectGroupChara, InspectGroupObj, InspectGroupTask, and InspectGroupThing.
Definition at line 117 of file InspectGroup.cs.
    {
    }
Referenced by InspectGroup< T >.SetActions().
SetActions() [1/2]
virtual void InspectGroup< T >.SetActions () inline virtual
Definition at line 103 of file InspectGroup.cs.
    {
    }
Referenced by UIInspector.Refresh().
SetActions() [2/2]
sealed override void InspectGroup< T >.SetActions () inline
Definition at line 111 of file InspectGroup.cs.
    {
        actions.Clear();
        OnSetActions();
    }
References InspectGroup< T >.actions, and InspectGroup< T >.OnSetActions().
Member Data Documentation
actions
List<Item> InspectGroup< T >.actions = new List<Item>()
Definition at line 27 of file InspectGroup.cs.
Referenced by InspectGroup< T >.Add(), UIInspector.Refresh(), and InspectGroup< T >.SetActions().
targets
List<IInspect> InspectGroup< T >.targets = new List<IInspect>()
Definition at line 29 of file InspectGroup.cs.
Referenced by InspectGroup< T >.CanInspect(), InspectGroup< T >.Contains(), InspectGroup< T >.Create(), InspectGroup< T >.GetName(), UIInspector.OnUpdate(), and UIInspector.Refresh().
type
Type InspectGroup< T >.type
Definition at line 25 of file InspectGroup.cs.
Referenced by AM_Select.OnRefreshSummary().
Property Documentation
FirstTarget [1/2]
IInspect InspectGroup< T >.FirstTarget get
Definition at line 31 of file InspectGroup.cs.
Referenced by InspectGroup< T >.CanInspect(), InspectGroup< T >.GetName(), and UIInspector.InspectUnderMouse().
FirstTarget [2/2]
new T InspectGroup< T >.FirstTarget get
Definition at line 109 of file InspectGroup.cs.
MultiName
virtual string InspectGroup< T >.MultiName get
Definition at line 35 of file InspectGroup.cs.
Referenced by InspectGroup< T >.GetName().
Solo
bool InspectGroup< T >.Solo get
Definition at line 33 of file InspectGroup.cs.
Referenced by InspectGroup< T >.GetName(), and UIInspector.Refresh().
The documentation for this class was generated from the following file:
Elin/InspectGroup.cs