Elin Decompiled Documentation: Gender Class Reference
Gender Class Reference
Static Public Member Functions
static string Name (int g)
static int GetRandom ()
Static Public Attributes
const int unknown = 0
const int female = 1
const int male = 2
Detailed Description
Definition at line 1 of file Gender.cs.
Member Function Documentation
GetRandom()
static int Gender.GetRandom () inline static
Definition at line 19 of file Gender.cs.
    {
        if (Rand.rnd(30) == 0)
        {
            return 0;
        }
        return Rand.Range(1, 3);
    }
References Rand.Range(), and Rand.rnd().
Referenced by Biography.Generate().
Name()
static string Gender.Name (int g) inline static
Definition at line 9 of file Gender.cs.
    {
        return (g switch
        {
            1 => "female",
            2 => "male",
            _ => "gay",
        }).lang();
    }
Referenced by ActEffect.Proc().
Member Data Documentation
female
const int Gender.female = 1 static
Definition at line 5 of file Gender.cs.
male
const int Gender.male = 2 static
Definition at line 7 of file Gender.cs.
unknown
const int Gender.unknown = 0 static
Definition at line 3 of file Gender.cs.
The documentation for this class was generated from the following file:
Elin/Plugins.basecore/Gender.cs