Elin Decompiled Documentation: ReligionExtension Class Reference
ReligionExtension Class Reference
Static Public Member Functions
static void SpawnAltar (this Religion religion)
Detailed Description
Definition at line 1 of file ReligionExtension.cs.
Member Function Documentation
SpawnAltar()
static void ReligionExtension.SpawnAltar (this Religion religion) inline static
Definition at line 3 of file ReligionExtension.cs.
    {
        Thing thing = ThingGen.Create("altar");
        (thing.trait as TraitAltar)?.SetDeity(religion.id);
        Point nearestPoint = EClass.pc.pos.GetNearestPoint(allowBlock: true, allowChara: false, allowInstalled: false);
        if (nearestPoint != null)
        {
            EClass._zone.AddCard(thing, nearestPoint).Install();
        }
    }
References EClass._zone, Zone.AddCard(), ThingGen.Create(), Point.GetNearestPoint(), Card.Install(), EClass.pc, Card.pos, and religion.
The documentation for this class was generated from the following file:
Elin/ReligionExtension.cs