Elin Decompiled Documentation: EInput.KeyboardPress Class Reference
EInput.KeyboardPress Class Reference
Public Member Functions
bool Update (bool forcePress=false)
void Consume ()
Public Attributes
float timer
int count
bool consumed
Func< KeyMap > func
Properties
EAction Action [get]
bool IsRepeating [get]
Detailed Description
Definition at line 201 of file EInput.cs.
Member Function Documentation
Consume()
void EInput.KeyboardPress.Consume () inline
Definition at line 243 of file EInput.cs.
        {
            consumed = true;
        }
References EInput.KeyboardPress.consumed.
Referenced by AM_Adv._OnUpdateInput(), and Scene.Init().
Update()
bool EInput.KeyboardPress.Update (bool forcePress = false) inline
Definition at line 215 of file EInput.cs.
        {
            if (Input.GetKey(func().key) || forcePress)
            {
                if (consumed)
                {
                    return false;
                }
                if (count == 1)
                {
                    timer += delta;
                    if (timer < 0.5f)
                    {
                        return false;
                    }
                }
                else
                {
                    timer = 0f;
                }
                count++;
                return true;
            }
            consumed = false;
            count = 0;
            return false;
        }
References EInput.KeyboardPress.consumed, EInput.KeyboardPress.count, EInput.delta, EInput.KeyboardPress.func, and EInput.KeyboardPress.timer.
Referenced by ActionMode.DoFunc(), and EInput.GetAction().
Member Data Documentation
consumed
bool EInput.KeyboardPress.consumed
Definition at line 207 of file EInput.cs.
Referenced by EInput.KeyboardPress.Consume(), and EInput.KeyboardPress.Update().
count
int EInput.KeyboardPress.count
Definition at line 205 of file EInput.cs.
Referenced by EInput.KeyboardPress.Update().
func
Func<KeyMap> EInput.KeyboardPress.func
Definition at line 209 of file EInput.cs.
Referenced by EInput.SetKeyMap(), and EInput.KeyboardPress.Update().
timer
float EInput.KeyboardPress.timer
Definition at line 203 of file EInput.cs.
Referenced by EInput.KeyboardPress.Update().
Property Documentation
Action
EAction EInput.KeyboardPress.Action get
Definition at line 211 of file EInput.cs.
Referenced by EInput.GetAction().
IsRepeating
bool EInput.KeyboardPress.IsRepeating get
Definition at line 213 of file EInput.cs.
Referenced by AM_Adv._OnUpdateInput().
The documentation for this class was generated from the following file:
Elin/Plugins.basecore/EInput.cs