Elin Decompiled Documentation: WidgetMouseover Class Reference
WidgetMouseover Class Reference
Public Member Functions
override void OnActivate ()
void Refresh ()
void Show (string s)
void Hide (bool immediate=false)
override void OnManagerActivate ()
override void OnManagerDeactivate ()
Public Member Functions inherited from Widget
void Test ()
bool IsInRightMode ()
void Activate ()
void RefreshOrder ()
virtual void OnActivate ()
virtual object CreateExtra ()
void Deactivate ()
virtual void OnDeactivate ()
void Close ()
void Reactivate ()
virtual void OnManagerActivate ()
virtual void OnManagerDeactivate ()
void SetAnchor (RectPosition p)
void SetPivot (RectPosition p)
virtual void OnChangePivot ()
void UpdateConfig ()
virtual void OnUpdateConfig ()
void ClampToScreen ()
virtual void OnChangeResolution ()
void OnChangePosition ()
virtual void OnChangeActionMode ()
virtual void OnFlip ()
bool IsAlignTop ()
Layer AddLayer (Layer l, Transform trans)
void RefreshTipPivotPosition ()
SkinSet GetSkin ()
SkinConfig GetSkinConfig ()
void SetSkin (int id, int v=0)
void TestSkin ()
virtual void ApplySkin ()
virtual void OnApplySkin ()
void InstantiateDeco (SkinDeco deco)
void AddDeco (SkinDeco deco)
void RemoveDeco (SkinDeco deco)
virtual bool CanShowContextMenu ()
void ShowContextMenu ()
void SetBaseContextMenu (UIContextMenu m)
virtual void OnSetContextMenu (UIContextMenu m)
void SetGridContextMenu (UIContextMenu m)
void SoundActivate ()
void OnChangeResolution ()
SkinSet GetSkin ()
SkinConfig GetSkinConfig ()
Public Attributes
Chara roster
UIText textName
LayoutGroup layout
CanvasGroup cg
Tween tween
Public Attributes inherited from Widget
Image imageBG
SoundData soundActivate
UIDragPanel dragPanel
RectTransform tipPivotLeft
RectTransform tipPivotRight
Static Public Attributes
static WidgetMouseover Instance
Static Public Attributes inherited from EMono
static Core core
Private Attributes
float timer
Additional Inherited Members
Public Types inherited from Widget
enum WidgetType { Default , ZoomMenu }
enum State { Active , Inactive }
Static Public Member Functions inherited from EMono
static int rnd (int a)
Protected Member Functions inherited from Widget
void ClampToScreenEnsured (Component c, Vector2 anchoredPos)
void ClampToScreen (RectTransform rect, float margin=10f)
Protected Attributes inherited from Widget
bool flip
Properties inherited from Widget
string ID [get]
Config config [get]
SkinRoot skinRoot [get]
bool IsSealed [get]
virtual bool ShowStyleMenu [get]
virtual bool AlwaysTop [get]
virtual bool IsStaticPosition [get]
virtual bool AlwaysBottom [get]
virtual Type SetSiblingAfter [get]
virtual bool ShowInBuildMode [get]
virtual bool RightClickToClose [get]
virtual bool AllowRightClickToClose [get]
Properties inherited from EMono
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SoundManager Sound [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static CoreDebug debug [get]
Detailed Description
Definition at line 6 of file WidgetMouseover.cs.
Member Function Documentation
Hide()
void WidgetMouseover.Hide (bool immediate = false) inline
Definition at line 114 of file WidgetMouseover.cs.
    {
        imageBG.raycastTarget = false;
        if (immediate)
        {
            layout.SetActive(enable: false);
            return;
        }
        TweenUtil.KillTween(ref tween);
        tween = cg.DOFade(0f, 0.3f).OnComplete(delegate
        {
            if ((bool)layout)
            {
                layout.SetActive(enable: false);
            }
        }).SetEase(Ease.InQuad);
    }
References cg, layout, and tween.
Referenced by AM_Adv.OnActivate(), and AM_ViewZone.OnActivate().
OnActivate()
override void WidgetMouseover.OnActivate () inline virtual
Reimplemented from Widget.
Definition at line 22 of file WidgetMouseover.cs.
    {
        Instance = this;
        Hide(immediate: true);
    }
References Instance.
OnManagerActivate()
override void WidgetMouseover.OnManagerActivate () inline virtual
Reimplemented from Widget.
Definition at line 132 of file WidgetMouseover.cs.
    {
        base.OnManagerActivate();
        imageBG.raycastTarget = true;
        Show("[" + Lang.Get("WidgetMouseover") + "]");
    }
References Lang.Get(), and Show().
OnManagerDeactivate()
override void WidgetMouseover.OnManagerDeactivate () inline virtual
Reimplemented from Widget.
Definition at line 139 of file WidgetMouseover.cs.
    {
        base.OnManagerDeactivate();
        Hide(immediate: true);
    }
Refresh()
void WidgetMouseover.Refresh () inline
Definition at line 28 of file WidgetMouseover.cs.
    {
        timer += Core.delta;
        PointTarget mouseTarget = EMono.scene.mouseTarget;
        if (!mouseTarget.hasTargetChanged && timer < 0.1f)
        {
            return;
        }
        timer = 0f;
        bool flag = EInput.isShiftDown && mouseTarget.pos.Equals(EMono.pc.pos) && (EMono.pc.ride != null || EMono.pc.parasite != null);
        if (((!flag && mouseTarget.target == null) || (ActionMode.IsAdv && Input.GetMouseButton(0))) && roster == null)
        {
            Hide();
            return;
        }
        string text = "";
        Card card = mouseTarget.card;
        if (roster != null && roster.ExistsOnMap)
        {
            flag = false;
            card = roster;
        }
        if (flag)
        {
            if (EMono.pc.ride != null)
            {
                text += EMono.pc.ride.GetHoverText();
                text += EMono.pc.ride.GetHoverText2();
            }
            if (EMono.pc.parasite != null)
            {
                if (EMono.pc.ride != null)
                {
                    text += Environment.NewLine;
                }
                text += EMono.pc.parasite.GetHoverText();
                text += EMono.pc.parasite.GetHoverText2();
            }
        }
        else if (card != null)
        {
            text = card.GetHoverText();
            if (roster == null)
            {
                int count = EMono.scene.mouseTarget.cards.Count;
                if (count > 1)
                {
                    text += "otherCards".lang((count - 1).ToString() ?? "");
                }
            }
            text += card.GetHoverText2();
            if (roster == null && mouseTarget.target != card)
            {
                text = text + Environment.NewLine + mouseTarget.target.InspectName;
            }
        }
        else if (mouseTarget.target != null)
        {
            text = mouseTarget.target.InspectName;
        }
        Show(text);
    }
References card, PointTarget.card, PointTarget.cards, Core.delta, Point.Equals(), Card.ExistsOnMap, Chara.GetHoverText(), Chara.GetHoverText2(), PointTarget.hasTargetChanged, IInspect.InspectName, ActionMode.IsAdv, Scene.mouseTarget, Chara.parasite, EMono.pc, Card.pos, PointTarget.pos, Chara.ride, roster, EMono.scene, Show(), PointTarget.target, and timer.
Referenced by PointTarget.CycleTarget(), and ActionMode.UpdateInput().
Show()
void WidgetMouseover.Show (string s) inline
Definition at line 91 of file WidgetMouseover.cs.
    {
        layout.SetActive(enable: true);
        cg.alpha = 1f;
        TweenUtil.KillTween(ref tween);
        textName.text = s;
        switch (this.Rect().GetAnchor())
        {
        case RectPosition.TopLEFT:
        case RectPosition.BottomLEFT:
            layout.childAlignment = TextAnchor.MiddleLeft;
            break;
        case RectPosition.TopRIGHT:
        case RectPosition.BottomRIGHT:
            layout.childAlignment = TextAnchor.MiddleRight;
            break;
        default:
            layout.childAlignment = TextAnchor.MiddleCenter;
            break;
        }
        layout.RebuildLayout();
    }
References layout, and tween.
Referenced by OnManagerActivate(), and Refresh().
Member Data Documentation
cg
CanvasGroup WidgetMouseover.cg
Definition at line 16 of file WidgetMouseover.cs.
Referenced by Hide().
Instance
WidgetMouseover WidgetMouseover.Instance static
Definition at line 8 of file WidgetMouseover.cs.
Referenced by PointTarget.CycleTarget(), AM_Adv.OnActivate(), AM_ViewZone.OnActivate(), OnActivate(), ButtonRoster.OnPointerEnter(), ButtonRoster.OnPointerExit(), and ActionMode.UpdateInput().
layout
LayoutGroup WidgetMouseover.layout
Definition at line 14 of file WidgetMouseover.cs.
Referenced by Hide(), and Show().
roster
Chara WidgetMouseover.roster
Definition at line 10 of file WidgetMouseover.cs.
Referenced by Refresh().
textName
UIText WidgetMouseover.textName
Definition at line 12 of file WidgetMouseover.cs.
timer
float WidgetMouseover.timer private
Definition at line 20 of file WidgetMouseover.cs.
Referenced by Refresh().
tween
Tween WidgetMouseover.tween
Definition at line 18 of file WidgetMouseover.cs.
Referenced by Hide(), and Show().
The documentation for this class was generated from the following file:
Elin/WidgetMouseover.cs