Elin Decompiled Documentation: WidgetCodex Class Reference
WidgetCodex Class Reference
Public Types
enum SearchType { Codex , Search }
Public Types inherited from Widget
enum WidgetType { Default , ZoomMenu }
enum State { Active , Inactive }
Public Member Functions
override void OnActivate ()
void Clear ()
virtual void Search (string s)
virtual void RefreshList ()
virtual bool CheckClose ()
Public Member Functions inherited from Widget
void Test ()
bool IsInRightMode ()
void Activate ()
void RefreshOrder ()
virtual void OnActivate ()
virtual object CreateExtra ()
void Deactivate ()
virtual void OnDeactivate ()
void Close ()
void Reactivate ()
virtual void OnManagerActivate ()
virtual void OnManagerDeactivate ()
void SetAnchor (RectPosition p)
void SetPivot (RectPosition p)
virtual void OnChangePivot ()
void UpdateConfig ()
virtual void OnUpdateConfig ()
void ClampToScreen ()
virtual void OnChangeResolution ()
void OnChangePosition ()
virtual void OnChangeActionMode ()
virtual void OnFlip ()
bool IsAlignTop ()
Layer AddLayer (Layer l, Transform trans)
void RefreshTipPivotPosition ()
SkinSet GetSkin ()
SkinConfig GetSkinConfig ()
void SetSkin (int id, int v=0)
void TestSkin ()
virtual void ApplySkin ()
virtual void OnApplySkin ()
void InstantiateDeco (SkinDeco deco)
void AddDeco (SkinDeco deco)
void RemoveDeco (SkinDeco deco)
virtual bool CanShowContextMenu ()
void ShowContextMenu ()
void SetBaseContextMenu (UIContextMenu m)
virtual void OnSetContextMenu (UIContextMenu m)
void SetGridContextMenu (UIContextMenu m)
void SoundActivate ()
Public Attributes
InputField field
WordSearch search = new WordSearch()
UIDynamicList list
HashSet< Recipe > recipes = new HashSet<Recipe>()
string lastSearch
UIButton buttonClear
Transform transResult
Public Attributes inherited from Widget
Image imageBG
SoundData soundActivate
UIDragPanel dragPanel
RectTransform tipPivotLeft
RectTransform tipPivotRight
Protected Member Functions
void Update ()
Protected Member Functions inherited from Widget
void ClampToScreenEnsured (Component c, Vector2 anchoredPos)
void ClampToScreen (RectTransform rect, float margin=10f)
Properties
virtual SearchType type [get]
Properties inherited from Widget
string ID [get]
Config config [get]
SkinRoot skinRoot [get]
bool IsSealed [get]
virtual bool ShowStyleMenu [get]
virtual bool AlwaysTop [get]
virtual bool IsStaticPosition [get]
virtual bool AlwaysBottom [get]
virtual Type SetSiblingAfter [get]
virtual bool ShowInBuildMode [get]
virtual bool RightClickToClose [get]
virtual bool AllowRightClickToClose [get]
Properties inherited from EMono
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SoundManager Sound [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static CoreDebug debug [get]
Private Attributes
int count
Additional Inherited Members
Static Public Member Functions inherited from EMono
static int rnd (int a)
Static Public Attributes inherited from EMono
static Core core
Protected Attributes inherited from Widget
bool flip
Detailed Description
Definition at line 5 of file WidgetCodex.cs.
Member Enumeration Documentation
SearchType
enum WidgetCodex.SearchType
Enumerator
Codex
Search
Definition at line 7 of file WidgetCodex.cs.
    {
        Codex,
        Search
    }
Member Function Documentation
CheckClose()
virtual bool WidgetCodex.CheckClose () inline virtual
Reimplemented in WidgetSearch.
Definition at line 136 of file WidgetCodex.cs.
    {
        return false;
    }
Referenced by Update().
Clear()
void WidgetCodex.Clear () inline
Definition at line 43 of file WidgetCodex.cs.
    {
        field.text = "";
    }
OnActivate()
override void WidgetCodex.OnActivate () inline virtual
Reimplemented from Widget.
Reimplemented in WidgetSearch.
Definition at line 31 of file WidgetCodex.cs.
    {
        field.onValueChanged.AddListener(Search);
        field.onSubmit.AddListener(Search);
        lastSearch = null;
        Search("");
        if (EMono._zone.isStarted)
        {
            field.Select();
        }
    }
References EMono._zone, field, Zone.isStarted, lastSearch, and Search.
RefreshList()
virtual void WidgetCodex.RefreshList () inline virtual
Reimplemented in WidgetSearch.
Definition at line 86 of file WidgetCodex.cs.
    {
        list.callbacks = new UIList.Callback<Recipe, ButtonGrid>
        {
            onClick = delegate
            {
            },
            onRedraw = delegate(Recipe a, ButtonGrid b, int i)
            {
                b.SetCraftRecipe(a, ButtonGrid.Mode.RecipeGrid, tooltip: true);
            },
            onList = delegate
            {
                foreach (Recipe recipe in recipes)
                {
                    list.Add(recipe);
                }
            }
        };
        list.List();
        list.dsv.OnResize();
    }
References list, recipes, and ButtonGrid.SetCraftRecipe().
Referenced by Search().
Search()
virtual void WidgetCodex.Search (string s) inline virtual
Reimplemented in WidgetSearch.
Definition at line 48 of file WidgetCodex.cs.
    {
        s = s.ToLower();
        buttonClear.SetActive(field.text != "");
        if (s == lastSearch)
        {
            return;
        }
        RecipeManager.BuildList();
        HashSet<Recipe> hashSet = new HashSet<Recipe>();
        if (!s.IsEmpty())
        {
            foreach (RecipeSource item in RecipeManager.list)
            {
                if (!item.isChara && !item.noListing && !item.isBridgePillar && (item.row.GetSearchName(jp: false).Contains(s) || item.row.GetSearchName(jp: true).Contains(s)) && (EMono.player.recipes.knownRecipes.ContainsKey(item.id) || item.alwaysKnown))
                {
                    hashSet.Add(Recipe.Create(item));
                }
            }
        }
        else
        {
            foreach (RecipeSource item2 in RecipeManager.list)
            {
                if (!item2.isChara && !item2.noListing && !item2.isBridgePillar && (EMono.player.recipes.knownRecipes.ContainsKey(item2.id) || item2.alwaysKnown))
                {
                    hashSet.Add(Recipe.Create(item2));
                }
            }
        }
        if (!hashSet.SetEquals(recipes))
        {
            recipes = hashSet;
            RefreshList();
        }
        lastSearch = s;
    }
References RecipeSource.alwaysKnown, RecipeManager.BuildList(), buttonClear, Recipe.Create(), field, RenderRow.GetSearchName(), RecipeSource.id, RecipeSource.isBridgePillar, RecipeSource.isChara, RecipeManager.knownRecipes, lastSearch, RecipeManager.list, RecipeSource.noListing, EMono.player, Player.recipes, recipes, RefreshList(), and RecipeSource.row.
Update()
void WidgetCodex.Update () inline protected
Definition at line 109 of file WidgetCodex.cs.
    {
        count++;
        if (Input.GetKeyDown(KeyCode.Escape))
        {
            Close();
            EInput.Consume(consumeAxis: false, 5);
            return;
        }
        int functionkeyDown = EInput.GetFunctionkeyDown();
        if (count > 10 && functionkeyDown != -1)
        {
            WidgetHotbar hotbarExtra = WidgetHotbar.HotbarExtra;
            if ((bool)hotbarExtra && hotbarExtra.GetItem(functionkeyDown) is HotItemWidget hotItemWidget && hotItemWidget.id == base.ID)
            {
                Close();
                EInput.Consume(consumeAxis: false, 5);
                return;
            }
        }
        if (CheckClose())
        {
            Close();
            EInput.Consume();
        }
    }
References CheckClose(), Widget.Close(), count, WidgetHotbar.GetItem(), WidgetHotbar.HotbarExtra, and HotItemWidget.id.
Member Data Documentation
buttonClear
UIButton WidgetCodex.buttonClear
Definition at line 23 of file WidgetCodex.cs.
Referenced by Search(), and WidgetSearch.Search().
count
int WidgetCodex.count private
Definition at line 27 of file WidgetCodex.cs.
Referenced by Update().
field
InputField WidgetCodex.field
Definition at line 13 of file WidgetCodex.cs.
Referenced by OnActivate(), WidgetSearch.OnDeactivate(), WidgetSearch.RefreshList(), WidgetSearch.RefreshWords(), Search(), and WidgetSearch.Search().
lastSearch
string WidgetCodex.lastSearch
Definition at line 21 of file WidgetCodex.cs.
Referenced by OnActivate(), Search(), and WidgetSearch.Search().
list
UIDynamicList WidgetCodex.list
Definition at line 17 of file WidgetCodex.cs.
Referenced by RefreshList(), and WidgetSearch.RefreshList().
recipes
HashSet<Recipe> WidgetCodex.recipes = new HashSet<Recipe>()
Definition at line 19 of file WidgetCodex.cs.
Referenced by RefreshList(), and Search().
search
WordSearch WidgetCodex.search = new WordSearch()
Definition at line 15 of file WidgetCodex.cs.
transResult
Transform WidgetCodex.transResult
Definition at line 25 of file WidgetCodex.cs.
Property Documentation
type
virtual SearchType WidgetCodex.type get
Definition at line 29 of file WidgetCodex.cs.
The documentation for this class was generated from the following file:
Elin/WidgetCodex.cs