Elin Decompiled Documentation: ListPeopleRevive Class Reference
ListPeopleRevive Class Reference
Public Member Functions
override bool IsDisabled (Chara c)
override void OnInstantiate (Chara a, ItemGeneral b)
override void OnClick (Chara c, ItemGeneral i)
override void OnList ()
Public Member Functions inherited from BaseListPeople
virtual bool IsDisabled (Chara c)
override void List ()
override void OnInstantiate (Chara a, ItemGeneral b)
void AddSubButtonWork (ItemGeneral b, Chara a)
void WriteHobbies (UITooltip t, Chara a, BaseArea roomWork)
virtual void SetSubText (Chara a, ItemGeneral b)
override void OnClick (Chara c, ItemGeneral i)
override void OnList ()
override void OnRefreshMenu ()
Public Member Functions inherited from ListOwner< Chara, ItemGeneral >
virtual void OnClick (T1 a, T2 b)
virtual void OnInstantiate (T1 a, T2 b)
virtual void OnList ()
virtual void List ()
virtual void OnCreate ()
virtual void OnSwitchContent ()
virtual void OnRefreshMenu ()
void RefreshTab ()
void MoveToOther (object c)
Additional Inherited Members
Static Public Member Functions inherited from EClass
static int rndSeed (int a, int seed)
static int rnd (long a)
static int rnd (int a)
static int curve (int a, int start, int step, int rate=75)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Public Attributes inherited from BaseListPeople
Chara owner
FactionMemberType memberType
Public Attributes inherited from ListOwner< Chara, ItemGeneral >
Layer layer
Window window
UIMultiList multi
ListOwner other
UIList list
WindowMenu menu
Window.Setting.Tab tab
string textTab
string textHeader
bool main
int index
Static Public Attributes inherited from EClass
static Core core
Properties inherited from BaseListPeople
new LayerPeople layer [get]
override string IdHeaderRow [get]
virtual bool ShowCharaSheet [get]
virtual bool ShowShowMode [get]
virtual LayerPeople.ShowMode ShowMode [get]
virtual bool ShowGoto [get]
virtual bool ShowHome [get]
Properties inherited from ListOwner< Chara, ItemGeneral >
ListOwner Main [get]
virtual string IdTitle [get]
virtual string IdHeaderRow [get]
virtual string TextTab [get]
virtual string TextHeader [get]
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Detailed Description
Definition at line 4 of file ListPeopleRevive.cs.
Member Function Documentation
IsDisabled()
override bool ListPeopleRevive.IsDisabled (Chara c) inline virtual
Reimplemented from BaseListPeople.
Definition at line 6 of file ListPeopleRevive.cs.
    {
        return false;
    }
OnClick()
override void ListPeopleRevive.OnClick (Chara c, ItemGeneral i) inline
Definition at line 18 of file ListPeopleRevive.cs.
    {
        if (EClass.pc.TryPay(CalcMoney.Revive(c)))
        {
            c.GetRevived();
            list.List();
        }
    }
References Chara.GetRevived(), ListOwner< Chara, ItemGeneral >.list, UIList.List(), EClass.pc, CalcMoney.Revive(), and Card.TryPay().
OnInstantiate()
override void ListPeopleRevive.OnInstantiate (Chara a, ItemGeneral b) inline
Definition at line 11 of file ListPeopleRevive.cs.
    {
        base.OnInstantiate(a, b);
        int money = EClass.pc.GetCurrency();
        b.AddPrefab<UIItem>("costMoney").text1.SetText((CalcMoney.Revive(a).ToString() ?? "").TagColorGoodBad(() => money >= CalcMoney.Revive(a)));
    }
References Card.GetCurrency(), money, EClass.pc, and CalcMoney.Revive().
OnList()
override void ListPeopleRevive.OnList () inline virtual
Reimplemented from BaseListPeople.
Definition at line 27 of file ListPeopleRevive.cs.
    {
        foreach (KeyValuePair<int, Chara> item in EClass.game.cards.globalCharas.Where((KeyValuePair<int, Chara> a) => a.Value.CanRevive() && a.Value.isDead && a.Value.faction == EClass.pc.faction && !a.Value.isSummon))
        {
            list.Add(item.Value);
        }
    }
References UIList.Add(), Game.cards, Chara.faction, EClass.game, CardManager.globalCharas, item, ListOwner< Chara, ItemGeneral >.list, and EClass.pc.
The documentation for this class was generated from the following file:
Elin/ListPeopleRevive.cs