Elin Decompiled Documentation: Date Class Reference
Date Class Reference
Public Types
enum TextFormat {
Default , Log , Widget , Schedule ,
Travel , YearMonthDay , LogPlusYear
}
Public Member Functions
Date Copy ()
override string ToString ()
void AddHour (int a)
void AddDay (int a)
void AddMonth (int a)
string GetText (Date.TextFormat format)
int GetRawReal (int offsetHours=0)
int GetRaw (int offsetHours=0)
int GetRawDay ()
bool IsExpired (int time)
int GetRemainingHours (int rawDeadLine)
int GetRemainingSecs (int rawDeadLine)
int GetElapsedMins (int rawDate)
int GetElapsedHour (int rawDate)
Static Public Member Functions
static string GetText (int raw, Date.TextFormat format)
static string GetText (int hour)
static string GetText2 (int hour)
static string SecToDate (int sec)
static string MinToDayAndHour (int min)
static int[] GetDateArray (int raw)
static Date ToDate (int raw)
Static Public Member Functions inherited from EClass
static int rnd (int a)
static int curve (int a, int start, int step, int rate=75)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Public Attributes
int[] raw = new int[6]
Static Public Attributes
const int ShippingHour = 5
const int HourToken = 60
const int DayToken = 1440
const int MonthToken = 43200
const int YearToken = 518400
const int HourTokenReal = 60
const int DayTokenReal = 1440
const int MonthTokenReal = 46080
const int YearTokenReal = 552960
Static Public Attributes inherited from EClass
static Core core
Properties
int year [get, set]
int month [get, set]
int day [get, set]
int hour [get, set]
int min [get, set]
int sec [get, set]
bool IsDay [get]
bool IsNight [get]
PeriodOfDay periodOfDay [get]
string NameMonth [get]
string NameMonthShort [get]
string NameTime [get]
bool IsSpring [get]
bool IsSummer [get]
bool IsAutumn [get]
bool IsWinter [get]
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Detailed Description
Definition at line 4 of file Date.cs.
Member Enumeration Documentation
TextFormat
enum Date.TextFormat
Enumerator
Default
Log
Widget
Schedule
Travel
YearMonthDay
LogPlusYear
Definition at line 455 of file Date.cs.
    {
        Default,
        Log,
        Widget,
        Schedule,
        Travel,
        YearMonthDay,
        LogPlusYear
    }
Member Function Documentation
AddDay()
void Date.AddDay (int a) inline
Definition at line 198 of file Date.cs.
    {
        this.day += a;
        while (this.day > 30)
        {
            this.day -= 30;
            this.AddMonth(1);
        }
    }
References AddMonth(), and day.
Referenced by AddHour().
AddHour()
void Date.AddHour (int a) inline
Definition at line 188 of file Date.cs.
    {
        this.hour += a;
        while (this.hour >= 24)
        {
            this.hour -= 24;
            this.AddDay(1);
        }
    }
References AddDay(), and hour.
Referenced by Weather.GetForecast(), Weather.GetWeatherForecast(), and Weather.RefreshForecasts().
AddMonth()
void Date.AddMonth (int a) inline
Definition at line 208 of file Date.cs.
    {
        this.month += a;
        while (this.month > 12)
        {
            this.month -= 12;
            int year = this.year;
            this.year = year + 1;
        }
    }
References month, and year.
Referenced by AddDay().
Copy()
Date Date.Copy () inline
Definition at line 78 of file Date.cs.
    {
        return new Date
        {
            year = this.year,
            month = this.month,
            day = this.day,
            hour = this.hour,
            min = this.min,
            sec = this.sec
        };
    }
References day, hour, min, month, sec, and year.
Referenced by GameIndex.Create(), Weather.GetWeatherForecast(), and Weather.RefreshForecasts().
GetDateArray()
static int[] Date.GetDateArray (int raw) inline static
Definition at line 391 of file Date.cs.
    {
        return new int[]
        {
            raw % 60,
            raw / 60 % 24,
            raw / 60 / 24 % 30,
            raw / 60 / 24 / 30 % 12,
            raw / 60 / 24 / 30 / 12
        };
    }
References raw.
Referenced by ToDate().
GetElapsedHour()
int Date.GetElapsedHour (int rawDate) inline
Definition at line 354 of file Date.cs.
    {
        if (rawDate != 0)
        {
            return (this.GetRaw(0) - rawDate) / 60;
        }
        return 0;
    }
References GetRaw().
Referenced by Player.MoveZone().
GetElapsedMins()
int Date.GetElapsedMins (int rawDate) inline
Definition at line 349 of file Date.cs.
    {
        return this.GetRaw(0) - rawDate;
    }
References GetRaw().
Referenced by Weather.GetTimeSinceLastRain().
GetRaw()
int Date.GetRaw (int offsetHours = 0) inline
Definition at line 324 of file Date.cs.
    {
        return this.min + (this.hour + offsetHours) * 60 + this.day * 1440 + this.month * 43200 + this.year * 518400;
    }
References day, month, and year.
Referenced by InvOwnerGene._OnProcess(), Zone.AbandonZone(), Zone.Activate(), MeetingManager.Add(), FactionBranch.AddRecruit(), Faction.AddReserve(), Region.CheckRandomSites(), Zone.ClaimZone(), SpatialGen.CreateInstance(), Region.CreateRandomSite(), Zone.Deactivate(), DramaOutcome.get_scratch(), GetElapsedHour(), GetElapsedMins(), GetRemainingHours(), GetRemainingSecs(), Quest.Init(), IsExpired(), Quest.IsVisibleOnQuestBoard(), TraitMoongate.LoadMap(), Player.MoveZone(), Trait.OnBarter(), BaseListPeople.OnClick(), QuestLoytelFarm.OnComplete(), QuestShippingChest.OnComplete(), QuestVernis.OnComplete(), FactionBranch.OnCreate(), QuestDialog.OnDropReward(), Zone_Field.OnGenerateMap(), Game.OnLoad(), QuestIntoDarkness.OnStart(), Player.OnStartNewGame(), TraitHat.OnUse(), Zone.OnVisit(), FoodEffect.Proc(), LayerTravel.Refresh(), Zone.Revive(), AI_Idle.Run(), AI_Steal.Run(), Weather.SetCondition(), GameDate.ShipGoods(), SlaverData.TryRefresh(), TraitSyringeGene.TrySetHeldAct(), Chara.TryWorkOutside(), and Zone.UpdateQuests().
GetRawDay()
int Date.GetRawDay () inline
Definition at line 329 of file Date.cs.
    {
        return this.day * 1440 + this.month * 43200 + this.year * 518400;
    }
Referenced by Card.DamageHP().
GetRawReal()
int Date.GetRawReal (int offsetHours = 0) inline
Definition at line 319 of file Date.cs.
    {
        return this.min + (this.hour + offsetHours) * 60 + this.day * 1440 + this.month * 46080 + this.year * 552960;
    }
References day, month, and year.
Referenced by GameIO.GetGameList().
GetRemainingHours()
int Date.GetRemainingHours (int rawDeadLine) inline
Definition at line 339 of file Date.cs.
    {
        return (rawDeadLine - this.GetRaw(0)) / 60;
    }
References GetRaw().
Referenced by TraitGeneMachine.GetProgress(), TraitGeneMachine.GetProgressText(), Trait.GetTextRestock(), BaseListPeople.OnClick(), LayerTravel.Refresh(), and Zone.ToString().
GetRemainingSecs()
int Date.GetRemainingSecs (int rawDeadLine) inline
Definition at line 344 of file Date.cs.
    {
        return rawDeadLine - this.GetRaw(0);
    }
References GetRaw().
GetText() [1/3]
string Date.GetText (Date::TextFormat format) inline
Definition at line 219 of file Date.cs.
    {
        switch (format)
        {
        case Date.TextFormat.Log:
            return string.Concat(new string[]
            {
                this.month.ToString(),
                "/",
                this.day.ToString(),
                " ",
                this.hour.ToString(),
                ":",
                this.min.ToString()
            });
        case Date.TextFormat.Widget:
            return "dateYearMonthDay".lang(this.year.ToString() ?? "", this.month.ToString() ?? "", this.day.ToString() ?? "", null, null);
        case Date.TextFormat.Schedule:
            return "dateSchedule".lang(this.NameMonth, this.day.ToString() ?? "", null, null, null);
        case Date.TextFormat.Travel:
        {
            string str = "_short";
            if (format == Date.TextFormat.Travel)
            {
                return "travelDate".lang(this.year.ToString() ?? "", this.month.ToString() ?? "", this.day.ToString() ?? "", null, null);
            }
            string str2 = "";
            if (this.day != 0)
            {
                str2 = str2 + this.day.ToString() + Lang.Get("wDay" + str);
            }
            if (this.hour != 0)
            {
                str2 = str2 + this.hour.ToString() + Lang.Get("wHour" + str);
            }
            if (this.min != 0)
            {
                str2 = str2 + this.min.ToString() + Lang.Get("wMin" + str);
            }
            return str2 + this.sec.ToString() + Lang.Get("wSec" + str);
        }
        case Date.TextFormat.YearMonthDay:
            return "dateYearMonthDay".lang(this.year.ToString() ?? "", this.month.ToString() ?? "", this.day.ToString() ?? "", null, null);
        case Date.TextFormat.LogPlusYear:
            return string.Concat(new string[]
            {
                this.year.ToString(),
                ", ",
                this.month.ToString(),
                "/",
                this.day.ToString(),
                " ",
                this.hour.ToString(),
                ":",
                this.min.ToString()
            });
        default:
            return string.Concat(new string[]
            {
                "Day ",
                this.day.ToString(),
                " ",
                this.hour.ToString(),
                ":",
                this.min.ToString()
            });
        }
    }
References day, hour, min, month, NameMonth, sec, and year.
Referenced by WidgetDate._Refresh(), GetText(), Trait.GetTextRestock(), Player.MoveZone(), BaseListPeople.OnClick(), UIHomeInfo.RefreshInfo(), ItemQuest.SetQuest(), and ToString().
GetText() [2/3]
static string Date.GetText (int hour) inline static
Definition at line 293 of file Date.cs.
    {
        if (hour < 0)
        {
            return "dateDayVoid".lang();
        }
        if (hour > 24)
        {
            return "dateDay".lang((hour / 24).ToString() ?? "", null, null, null, null);
        }
        return "dateHour".lang(hour.ToString() ?? "", null, null, null, null);
    }
References hour, and ToString().
GetText() [3/3]
static string Date.GetText (int raw, Date::TextFormat format) inline static
Definition at line 288 of file Date.cs.
    {
        return Date.ToDate(raw).GetText(format);
    }
References GetText(), raw, and ToDate().
GetText2()
static string Date.GetText2 (int hour) inline static
Definition at line 306 of file Date.cs.
    {
        if (hour < 0)
        {
            return "-";
        }
        if (hour > 24)
        {
            return (hour / 24).ToString() + "d";
        }
        return hour.ToString() + "h";
    }
References hour.
Referenced by LayerTravel.Refresh().
IsExpired()
bool Date.IsExpired (int time) inline
Definition at line 334 of file Date.cs.
    {
        return time - this.GetRaw(0) < 0;
    }
References GetRaw().
Referenced by Zone.Activate(), Zone.CanDestroy(), Region.CheckRandomSites(), Trait.GetRestockedIcon(), Trait.OnBarter(), BaseListPeople.OnClick(), MeetingManager.OnSimulateHour(), Zone.OnVisit(), Zone.RefreshHat(), AIWork.SetDestination(), SlaverData.TryRefresh(), TraitCoreZone.TrySetAct(), and Chara.TryWorkOutside().
MinToDayAndHour()
static string Date.MinToDayAndHour (int min) inline static
Definition at line 376 of file Date.cs.
    {
        int num = min / 60;
        int num2 = num / 24;
        if (num == 0)
        {
            return min.ToString() + "";
        }
        if (num2 != 0)
        {
            return num2.ToString() + "" + (num % 24).ToString() + "";
        }
        return num.ToString() + "";
    }
References min, and ToString().
SecToDate()
static string Date.SecToDate (int sec) inline static
Definition at line 363 of file Date.cs.
    {
        return string.Concat(new string[]
        {
            (sec / 60 / 60).ToString(),
            " ",
            (sec / 60 % 60).ToString(),
            " ",
            (sec % 60).ToString(),
            ""
        });
    }
References sec, and ToString().
ToDate()
static Date Date.ToDate (int raw) inline static
Definition at line 403 of file Date.cs.
    {
        int[] dateArray = Date.GetDateArray(raw);
        int num = dateArray[4];
        int num2 = dateArray[3];
        int num3 = dateArray[2];
        if (num2 == 0)
        {
            num2 = 12;
            num--;
        }
        if (num3 == 0)
        {
            num3 = 30;
            num2--;
        }
        if (num2 == 0)
        {
            num2 = 12;
            num--;
        }
        return new Date
        {
            min = dateArray[0],
            hour = dateArray[1],
            day = num3,
            month = num2,
            year = num
        };
    }
References day, GetDateArray(), hour, min, month, raw, and year.
Referenced by GetText(), and LayerShippingResult.Show().
ToString()
override string Date.ToString () inline
Definition at line 151 of file Date.cs.
    {
        return this.GetText(Date.TextFormat.Log);
    }
References GetText().
Referenced by GetText(), MinToDayAndHour(), and SecToDate().
Member Data Documentation
DayToken
const int Date.DayToken = 1440 static
Definition at line 441 of file Date.cs.
DayTokenReal
const int Date.DayTokenReal = 1440 static
Definition at line 449 of file Date.cs.
HourToken
const int Date.HourToken = 60 static
Definition at line 439 of file Date.cs.
HourTokenReal
const int Date.HourTokenReal = 60 static
Definition at line 447 of file Date.cs.
MonthToken
const int Date.MonthToken = 43200 static
Definition at line 443 of file Date.cs.
MonthTokenReal
const int Date.MonthTokenReal = 46080 static
Definition at line 451 of file Date.cs.
raw
int [] Date.raw = new int[6]
Definition at line 437 of file Date.cs.
Referenced by GetDateArray(), GetText(), ToDate(), and VirtualDate.VirtualDate().
ShippingHour
const int Date.ShippingHour = 5 static
Definition at line 434 of file Date.cs.
YearToken
const int Date.YearToken = 518400 static
Definition at line 445 of file Date.cs.
YearTokenReal
const int Date.YearTokenReal = 552960 static
Definition at line 453 of file Date.cs.
Property Documentation
day
int Date.day get set
Definition at line 30 of file Date.cs.
    {
        get
        {
            return this.raw[2];
        }
        set
        {
            this.raw[2] = value;
        }
    }
Referenced by AddDay(), Copy(), GetRaw(), GetRawReal(), StickyHomeReport.GetText(), GetText(), Weather.GetWeatherForecast(), LayerNewspaper.OnInit(), TraitGachaBall.OnUse(), ContentHomeReport.RefreshInfo(), UIHomeInfo.RefreshInfo(), UIHomeInfo.RefreshReport(), LayerShippingResult.Show(), HotItemContext.Show(), VirtualDate.SimulateDay(), ToDate(), and Thing.TryLickEnchant().
hour
int Date.hour get set
Definition at line 42 of file Date.cs.
    {
        get
        {
            return this.raw[3];
        }
        set
        {
            this.raw[3] = value;
        }
    }
Referenced by AddHour(), GameDate.AdvanceHour(), Chara.ChooseNewGoal(), Copy(), GetText(), GetText2(), WidgetArtTool.OnActivate(), Region.OnAdvanceHour(), TraitDaggerGrave.OnUse(), VirtualDate.SimulateHour(), Chara.TickWork(), ToDate(), and Trait.TryToggle().
IsAutumn
bool Date.IsAutumn get
Definition at line 172 of file Date.cs.
    {
        get
        {
            return this.month >= 9 && this.month <= 11;
        }
    }
IsDay
bool Date.IsDay get
Definition at line 91 of file Date.cs.
    {
        get
        {
            return !this.IsNight;
        }
    }
Referenced by GameUpdater.Update().
IsNight
bool Date.IsNight get
Definition at line 99 of file Date.cs.
    {
        get
        {
            return this.hour >= 19 || this.hour <= 5;
        }
    }
Referenced by BaseTileMap.DrawTile(), Card.GetLightRadius(), BaseGameScreen.RefreshSky(), CoreConfig.RefreshUIBrightness(), BaseGameScreen.RefreshWeather(), AI_Idle.Run(), and Zone.Simulate().
IsSpring
bool Date.IsSpring get
Definition at line 156 of file Date.cs.
    {
        get
        {
            return this.month >= 3 && this.month <= 5;
        }
    }
IsSummer
bool Date.IsSummer get
Definition at line 164 of file Date.cs.
    {
        get
        {
            return this.month >= 6 && this.month <= 8;
        }
    }
IsWinter
bool Date.IsWinter get
Definition at line 180 of file Date.cs.
    {
        get
        {
            return this.month >= 12 || this.month <= 2;
        }
    }
Referenced by GrowSystem.CanGrow().
min
int Date.min get set
Definition at line 54 of file Date.cs.
    {
        get
        {
            return this.raw[4];
        }
        set
        {
            this.raw[4] = value;
        }
    }
Referenced by Copy(), GetText(), MinToDayAndHour(), ToDate(), and Scene.UpdateTimeRatio().
month
int Date.month get set
Definition at line 18 of file Date.cs.
    {
        get
        {
            return this.raw[1];
        }
        set
        {
            this.raw[1] = value;
        }
    }
Referenced by AddMonth(), GameDate.AdvanceMonth(), Copy(), GetRaw(), GetRawReal(), StickyHomeReport.GetText(), GetText(), ContentHomeReport.RefreshInfo(), UIHomeInfo.RefreshInfo(), LayerShippingResult.Show(), VirtualDate.SimulateMonth(), and ToDate().
NameMonth
string Date.NameMonth get
Definition at line 127 of file Date.cs.
    {
        get
        {
            return this.month.ToString() ?? "";
        }
    }
Referenced by GetText().
NameMonthShort
string Date.NameMonthShort get
Definition at line 135 of file Date.cs.
    {
        get
        {
            return this.month.ToString() ?? "";
        }
    }
NameTime
string Date.NameTime get
Definition at line 143 of file Date.cs.
    {
        get
        {
            return this.periodOfDay.ToString().lang();
        }
    }
periodOfDay
PeriodOfDay Date.periodOfDay get
Definition at line 107 of file Date.cs.
    {
        get
        {
            if (this.hour >= 5 && this.hour <= 6)
            {
                return PeriodOfDay.Dawn;
            }
            if (this.hour >= 7 && this.hour <= 17)
            {
                return PeriodOfDay.Day;
            }
            if (this.hour >= 18 && this.hour <= 19)
            {
                return PeriodOfDay.Dusk;
            }
            return PeriodOfDay.Night;
        }
    }
Referenced by WidgetDate._Refresh(), and Card.GetLightRadius().
sec
int Date.sec get set
Definition at line 66 of file Date.cs.
    {
        get
        {
            return this.raw[5];
        }
        set
        {
            this.raw[5] = value;
        }
    }
Referenced by Copy(), GetText(), and SecToDate().
year
int Date.year get set
Definition at line 6 of file Date.cs.
    {
        get
        {
            return this.raw[0];
        }
        set
        {
            this.raw[0] = value;
        }
    }
Referenced by AddMonth(), GameDate.AdvanceYear(), Copy(), GetRaw(), GetRawReal(), GetText(), LayerNewspaper.OnInit(), ContentHomeReport.RefreshInfo(), UIHomeInfo.RefreshInfo(), LayerShippingResult.Show(), VirtualDate.SimulateYear(), and ToDate().
The documentation for this class was generated from the following file:
Elin/Date.cs