Elin Decompiled Documentation: LayerChara Class Reference
LayerChara Class Reference
Public Member Functions
LayerChara SetChara (Chara c)
Public Member Functions inherited from ELayer
override void OnBeforeAddLayer ()
void InitInspector ()
sealed override void Init ()
override void OnAfterAddLayer ()
void TryShowHelp ()
void AddLayerToUI (string id)
void TryShowHint (string _langHint=null)
void TalkHomeMemeber (string id)
void TalkMaid (string id)
override void OnRightClick ()
Static Public Member Functions
static void Refresh ()
Static Public Member Functions inherited from ELayer
static int rnd (int a)
Public Attributes
WindowChara windowChara
Static Public Attributes
static LayerChara Instance
Properties
override bool blockWidgetClick [get]
Properties inherited from ELayer
static Core core [get]
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static FactionBranch Branch [get]
static Faction Home [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static CoreConfig config [get]
static GameSetting setting [get]
static ColorProfile Colors [get]
static SourceManager sources [get]
static World world [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
bool IsFloat [get]
virtual string IdHelp [get]
Additional Inherited Members
Protected Member Functions inherited from ELayer
sealed override void _Close ()
sealed override void Kill ()
Detailed Description
Definition at line 1 of file LayerChara.cs.
Member Function Documentation
Refresh()
static void LayerChara.Refresh () inline static
Definition at line 16 of file LayerChara.cs.
    {
        if ((bool)Instance)
        {
            Instance.windowChara.Refresh();
        }
    }
References Instance, WindowChara.Refresh(), and windowChara.
Referenced by CharaBody.Equip(), and CharaBody.Unequip().
SetChara()
LayerChara LayerChara.SetChara (Chara c) inline
Definition at line 9 of file LayerChara.cs.
    {
        windowChara.SetChara(c);
        Instance = this;
        return this;
    }
References Instance, WindowChara.SetChara(), and windowChara.
Referenced by ActionMode.DoFunc(), Card.Inspect(), WidgetExp.OnClick(), and WidgetExpHome.OnClick().
Member Data Documentation
Instance
LayerChara LayerChara.Instance static
Definition at line 3 of file LayerChara.cs.
Referenced by Refresh(), and SetChara().
windowChara
WindowChara LayerChara.windowChara
Definition at line 5 of file LayerChara.cs.
Referenced by WidgetExp.OnClick(), WidgetExpHome.OnClick(), Refresh(), and SetChara().
Property Documentation
blockWidgetClick
override bool LayerChara.blockWidgetClick get
Definition at line 7 of file LayerChara.cs.
The documentation for this class was generated from the following file:
Elin/LayerChara.cs