Elin Decompiled Documentation: PostEffectProfile Class Reference
PostEffectProfile Class Reference
Public Member Functions
void OnChangeProfile ()
void Apply (Camera cam)
Public Attributes
float Brightness
float Saturation
float Contrast
int sharpen = 20
int sharpen2 = 80
int blur
bool enableAA
bool enableCharaAA
bool disable
bool kuwahara
AAMode aaMode
float offsetScale
float blurRadius
Private Member Functions
void OnValidate ()
Additional Inherited Members
Static Public Member Functions inherited from EScriptable
static int rnd (int a)
Detailed Description
Definition at line 4 of file PostEffectProfile.cs.
Member Function Documentation
Apply()
void PostEffectProfile.Apply (Camera cam) inline
Definition at line 49 of file PostEffectProfile.cs.
    {
        Antialiasing component = cam.transform.GetComponent<Antialiasing>();
        if ((bool)component)
        {
            component.enabled = enableAA;
            component.mode = aaMode;
            component.offsetScale = offsetScale;
            component.blurRadius = blurRadius;
        }
        if (enableCharaAA)
        {
            EClass.scene.screenElin.tileMap.passChara.mat.EnableKeyword("AA_ON");
            EClass.scene.screenElin.tileMap.passCharaL.mat.EnableKeyword("AA_ON");
            EClass.scene.screenElin.tileMap.passCharaLW.mat.EnableKeyword("AA_ON");
        }
        else
        {
            EClass.scene.screenElin.tileMap.passChara.mat.DisableKeyword("AA_ON");
            EClass.scene.screenElin.tileMap.passCharaL.mat.DisableKeyword("AA_ON");
            EClass.scene.screenElin.tileMap.passCharaLW.mat.DisableKeyword("AA_ON");
        }
    }
References aaMode, blurRadius, enableAA, enableCharaAA, MeshPass.mat, offsetScale, BaseTileMap.passChara, BaseTileMap.passCharaL, BaseTileMap.passCharaLW, EClass.scene, Scene.screenElin, and BaseGameScreen.tileMap.
Referenced by CoreConfig.ApplyGrading(), and OnValidate().
OnChangeProfile()
void PostEffectProfile.OnChangeProfile () inline
Definition at line 40 of file PostEffectProfile.cs.
    {
        CoreConfig.GraphicSetting graphic = EClass.core.config.graphic;
        graphic.sharpen = sharpen;
        graphic.sharpen2 = sharpen2;
        graphic.blur = blur;
        graphic.kuwahara = kuwahara;
    }
References blur, Core.config, EClass.core, CoreConfig.graphic, kuwahara, sharpen, and sharpen2.
Referenced by CoreConfig.Init(), CoreConfig.OnReset(), and CoreConfig.ResetGraphics().
OnValidate()
void PostEffectProfile.OnValidate () inline private
Definition at line 32 of file PostEffectProfile.cs.
    {
        if (Application.isPlaying)
        {
            Apply(EClass.scene.cam);
        }
    }
References Apply(), Scene.cam, and EClass.scene.
Member Data Documentation
aaMode
AAMode PostEffectProfile.aaMode
Definition at line 26 of file PostEffectProfile.cs.
Referenced by Apply().
blur
int PostEffectProfile.blur
Definition at line 16 of file PostEffectProfile.cs.
Referenced by OnChangeProfile().
blurRadius
float PostEffectProfile.blurRadius
Definition at line 30 of file PostEffectProfile.cs.
Referenced by Apply().
Brightness
float PostEffectProfile.Brightness
Definition at line 6 of file PostEffectProfile.cs.
Referenced by CoreConfig.ApplyGrading().
Contrast
float PostEffectProfile.Contrast
Definition at line 10 of file PostEffectProfile.cs.
Referenced by CoreConfig.ApplyGrading().
disable
bool PostEffectProfile.disable
Definition at line 22 of file PostEffectProfile.cs.
enableAA
bool PostEffectProfile.enableAA
Definition at line 18 of file PostEffectProfile.cs.
Referenced by Apply().
enableCharaAA
bool PostEffectProfile.enableCharaAA
Definition at line 20 of file PostEffectProfile.cs.
Referenced by Apply().
kuwahara
bool PostEffectProfile.kuwahara
Definition at line 24 of file PostEffectProfile.cs.
Referenced by OnChangeProfile().
offsetScale
float PostEffectProfile.offsetScale
Definition at line 28 of file PostEffectProfile.cs.
Referenced by Apply().
Saturation
float PostEffectProfile.Saturation
Definition at line 8 of file PostEffectProfile.cs.
Referenced by CoreConfig.ApplyGrading().
sharpen
int PostEffectProfile.sharpen = 20
Definition at line 12 of file PostEffectProfile.cs.
Referenced by OnChangeProfile().
sharpen2
int PostEffectProfile.sharpen2 = 80
Definition at line 14 of file PostEffectProfile.cs.
Referenced by OnChangeProfile().
The documentation for this class was generated from the following file:
Elin/PostEffectProfile.cs