Elin Decompiled Documentation: Feat Class Reference
Feat Class Reference
Public Member Functions
override bool CanLink (ElementContainer owner)
override Sprite GetIcon (string suffix="")
override void OnWriteNote (UINote n, ElementContainer owner)
string GetHint (ElementContainer owner)
bool IsAvailable (ElementContainer owner, int a=1)
List< string > Apply (int a, ElementContainer owner, bool hint=false)
override bool CanLink (ElementContainer owner)
override Sprite GetIcon (string suffix="")
override void OnWriteNote (UINote n, ElementContainer owner)
string GetHint (ElementContainer owner)
bool IsAvailable (ElementContainer owner, int a=1)
List< string > Apply (int a, ElementContainer owner, bool hint=false)
Public Member Functions inherited from Element
virtual SourceElement.Row GetSource ()
virtual int GetSourcePotential (int v)
virtual Sprite GetSprite ()
int GetMaterialSourceValue (Thing t, int v)
virtual int GetSourceValue (int v, int lv, SourceValueType type)
virtual Sprite GetIcon (string suffix="")
int SortVal (bool charaSheet=false)
virtual bool CanLink (ElementContainer owner)
bool HasTag (string tag)
void SetImage (Image i)
virtual string GetDetail ()
bool IsFactionElement (Chara c)
Element GetParent (Card c)
void WriteNote (UINote n, ElementContainer owner=null, Action< UINote > onWriteNote=null)
void WriteNoteWithRef (UINote n, ElementContainer owner, Action< UINote > onWriteNote, Element refEle)
void _WriteNote (UINote n, Chara c, Act act)
void _WriteNote (UINote n, ElementContainer owner, Action< UINote > onWriteNote, bool isRef, bool addHeader=true)
virtual void OnWriteNote (UINote n, ElementContainer owner)
virtual void OnChangeValue ()
void CheckLevelBonus (ElementContainer owner, UINote n=null)
int GetSortVal (UIList.SortMode m)
virtual Act.Cost GetCost (Chara c)
virtual int GetPower (Card c)
virtual void SetTextValue (UIText text)
virtual SourceElement.Row GetSource ()
virtual int GetSourcePotential (int v)
virtual Sprite GetSprite ()
int GetMaterialSourceValue (Thing t, int v)
virtual int GetSourceValue (int v, int lv, SourceValueType type)
virtual Sprite GetIcon (string suffix="")
int SortVal (bool charaSheet=false)
virtual bool CanLink (ElementContainer owner)
bool HasTag (string tag)
void SetImage (Image i)
virtual string GetDetail ()
bool IsFactionElement (Chara c)
Element GetParent (Card c)
void WriteNote (UINote n, ElementContainer owner=null, Action< UINote > onWriteNote=null)
void WriteNoteWithRef (UINote n, ElementContainer owner, Action< UINote > onWriteNote, Element refEle)
void _WriteNote (UINote n, Chara c, Act act)
void _WriteNote (UINote n, ElementContainer owner, Action< UINote > onWriteNote, bool isRef, bool addHeader=true)
virtual void OnWriteNote (UINote n, ElementContainer owner)
virtual void OnChangeValue ()
void CheckLevelBonus (ElementContainer owner, UINote n=null)
int GetSortVal (UIList.SortMode m)
virtual Act.Cost GetCost (Chara c)
virtual int GetPower (Card c)
virtual void SetTextValue (UIText text)
Static Public Attributes
static List< string > hints = new List<string>()
static string[] featRef = new string[5]
Static Public Attributes inherited from Element
const int Div = 5
static Element Void = new Element()
static int[] List_MainAttributes
static int[] List_MainAttributesMajor
static int[] List_Body
static int[] List_Mind
static List< SourceElement.Row > ListElements = new List<SourceElement.Row>()
static List< SourceElement.Row > ListAttackElements = new List<SourceElement.Row>()
Static Public Attributes inherited from EClass
static Core core
Properties
override bool ShowBonuses [get]
override string Name [get]
override string FullName [get]
override bool ShowXP [get]
override bool ShowValue [get]
override int CostLearn [get]
Properties inherited from Element
SourceElement.Row source [get]
virtual int DisplayValue [get]
virtual int MinValue [get]
int Value [get]
int ValueWithoutLink [get]
virtual int MinPotential [get]
int Potential [get]
virtual bool CanGainExp [get]
bool IsFlag [get]
virtual string Name [get]
virtual string FullName [get]
virtual int ExpToNext [get]
virtual bool UseExpMod [get]
virtual int CostTrain [get]
virtual int CostLearn [get]
virtual bool ShowXP [get]
virtual bool ShowMsgOnValueChanged [get]
virtual bool ShowValue [get]
virtual bool ShowPotential [get]
virtual bool UsePotential [get]
virtual bool PotentialAsStock [get]
virtual bool ShowRelativeAttribute [get]
virtual bool ShowBonuses [get]
virtual string ShortName [get]
bool IsGlobalElement [get]
bool IsFactionWideElement [get]
bool IsPartyWideElement [get]
virtual bool ShowEncNumber [get]
bool IsTrait [get]
bool IsFoodTrait [get]
bool IsFoodTraitMain [get]
bool IsMainAttribute [get]
Act act [get]
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Private Member Functions
void< Apply > g__Note (string s, ref Feat.<>c__DisplayClass19_0 A_2)
void< Apply > g__NoteElement (int ele, int a, ref Feat.<>c__DisplayClass19_0 A_3)
void< Apply > g__ModBase (int ele, int _v, bool hide, ref Feat.<>c__DisplayClass19_0 A_4)
void< Apply > g__ModPotential (int ele, int _v, ref Feat.<>c__DisplayClass19_0 A_3)
void< Apply > g__ModAttribute (int ele, ref Feat.<>c__DisplayClass19_0 A_2)
void< Apply > g__GodHint (ref Feat.<>c__DisplayClass19_0 A_1)
Additional Inherited Members
Static Public Member Functions inherited from Element
static string GetName (string alias)
static SourceElement.Row Get (int id)
static Dictionary< int, int > GetElementMap (int[] list)
static Dictionary< int, int > GetElementMap (int[] list, Dictionary< int, int > map)
static SourceElement.Row GetRandomElement (int lv=1)
static Element Create (int id, int v=0)
static Element Create (string id, int v=1)
static int GetId (string alias)
static int GetResistLv (int v)
static int GetResistDamage (int dmg, int v)
static string GetName (string alias)
static SourceElement.Row Get (int id)
static Dictionary< int, int > GetElementMap (int[] list)
static Dictionary< int, int > GetElementMap (int[] list, Dictionary< int, int > map)
static SourceElement.Row GetRandomElement (int lv=1)
static Element Create (int id, int v=0)
static Element Create (string id, int v=1)
static int GetId (string alias)
static int GetResistLv (int v)
static int GetResistDamage (int dmg, int v)
Static Public Member Functions inherited from EClass
static int rnd (int a)
static int curve (int a, int start, int step, int rate=75)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Public Attributes inherited from Element
SourceElement.Row _source
int id
int vBase
int vExp
int vPotential
int vTempPotential
int vLink
int vSource
int vSourcePotential
ElementContainer owner
Static Package Functions inherited from Element
static string< _WriteNote > g__Calc (ref Element.<>c__DisplayClass103_0 A_0)
Detailed Description
Definition at line 6 of file Feat.2.cs.
Member Function Documentation
Apply() [1/2]
List< string > Feat.Apply (int a, ElementContainer owner, bool hint = false) inline
Definition at line 100 of file Feat.2.cs.
    {
        Feat.<>c__DisplayClass19_0 CS$<>8__locals1;
        CS$<>8__locals1.hint = hint;
        CS$<>8__locals1.owner = owner;
        CS$<>8__locals1.a = a;
        CS$<>8__locals1.<>4__this = this;
        if (CS$<>8__locals1.hint)
        {
            Feat.hints.Clear();
        }
        int value = base.Value;
        CS$<>8__locals1.A = Mathf.Abs(CS$<>8__locals1.a);
        CS$<>8__locals1.invert = ((CS$<>8__locals1.a >= 0) ? 1 : -1);
        if (CS$<>8__locals1.hint)
        {
            Feat.featRef[0] = (CS$<>8__locals1.a.ToString() ?? "");
            Feat.featRef[1] = (CS$<>8__locals1.a.ToString() ?? "");
        }
        Chara chara = CS$<>8__locals1.owner.Chara;
        int num = this.vPotential;
        if (!CS$<>8__locals1.hint && CS$<>8__locals1.a > 0 && chara != null)
        {
            num = (this.vPotential = chara.LV);
        }
        int i = this.id;
        if (i <= 1330)
        {
            if (i <= 1305)
            {
                if (i <= 1230)
                {
                    switch (i)
                    {
                    case 1202:
                        this.<Apply>g__ModBase|19_2(403, CS$<>8__locals1.a * 20, true, ref CS$<>8__locals1);
                        goto IL_12F3;
                    case 1203:
                    case 1205:
                    case 1207:
                    case 1208:
                    case 1209:
                    case 1211:
                    case 1214:
                    case 1215:
                    case 1219:
                    case 1220:
                    case 1222:
                    case 1225:
                        goto IL_12F3;
                    case 1204:
                        this.<Apply>g__ModBase|19_2(64, CS$<>8__locals1.a * 50, true, ref CS$<>8__locals1);
                        this.<Apply>g__ModBase|19_2(401, CS$<>8__locals1.a, false, ref CS$<>8__locals1);
                        goto IL_12F3;
                    case 1206:
                        this.<Apply>g__ModBase|19_2(78, -CS$<>8__locals1.a * 10, false, ref CS$<>8__locals1);
                        goto IL_12F3;
                    case 1210:
                        this.<Apply>g__ModBase|19_2(955, CS$<>8__locals1.a * 5, false, ref CS$<>8__locals1);
                        this.<Apply>g__ModBase|19_2(953, CS$<>8__locals1.a * 10, false, ref CS$<>8__locals1);
                        this.<Apply>g__ModBase|19_2(958, CS$<>8__locals1.a * 5, false, ref CS$<>8__locals1);
                        this.<Apply>g__ModBase|19_2(956, CS$<>8__locals1.a * 10, false, ref CS$<>8__locals1);
                        this.<Apply>g__ModBase|19_2(950, CS$<>8__locals1.a * -5, false, ref CS$<>8__locals1);
                        goto IL_12F3;
                    case 1212:
                        this.<Apply>g__ModBase|19_2(961, CS$<>8__locals1.a * 5, false, ref CS$<>8__locals1);
                        this.<Apply>g__ModBase|19_2(953, CS$<>8__locals1.a * 5, false, ref CS$<>8__locals1);
                        this.<Apply>g__ModBase|19_2(958, CS$<>8__locals1.a * 5, false, ref CS$<>8__locals1);
                        this.<Apply>g__ModBase|19_2(956, CS$<>8__locals1.a * 5, false, ref CS$<>8__locals1);
                        this.<Apply>g__ModBase|19_2(954, CS$<>8__locals1.a * 5, false, ref CS$<>8__locals1);
                        this.<Apply>g__ModBase|19_2(957, CS$<>8__locals1.a * 5, false, ref CS$<>8__locals1);
                        this.<Apply>g__ModBase|19_2(959, CS$<>8__locals1.a * 5, false, ref CS$<>8__locals1);
                        goto IL_12F3;
                    case 1213:
                        this.<Apply>g__ModBase|19_2(962, CS$<>8__locals1.a * 20, false, ref CS$<>8__locals1);
                        goto IL_12F3;
                    case 1216:
                        this.<Apply>g__ModBase|19_2(6020, CS$<>8__locals1.a, false, ref CS$<>8__locals1);
                        goto IL_12F3;
                    case 1217:
                        this.<Apply>g__ModBase|19_2(952, CS$<>8__locals1.a * -10, false, ref CS$<>8__locals1);
                        this.<Apply>g__ModBase|19_2(955, CS$<>8__locals1.a * 20, false, ref CS$<>8__locals1);
                        this.<Apply>g__ModBase|19_2(964, CS$<>8__locals1.a * 20, false, ref CS$<>8__locals1);
                        goto IL_12F3;
                    case 1218:
                        this.<Apply>g__ModBase|19_2(950, CS$<>8__locals1.a / 40, false, ref CS$<>8__locals1);
                        this.<Apply>g__ModBase|19_2(952, CS$<>8__locals1.a / 40, false, ref CS$<>8__locals1);
                        this.<Apply>g__ModBase|19_2(955, CS$<>8__locals1.a / 40, false, ref CS$<>8__locals1);
                        this.<Apply>g__ModBase|19_2(953, CS$<>8__locals1.a / 40, false, ref CS$<>8__locals1);
                        this.<Apply>g__ModBase|19_2(958, CS$<>8__locals1.a / 40, false, ref CS$<>8__locals1);
                        this.<Apply>g__ModBase|19_2(956, CS$<>8__locals1.a / 40, false, ref CS$<>8__locals1);
                        this.<Apply>g__ModBase|19_2(954, CS$<>8__locals1.a / 40, false, ref CS$<>8__locals1);
                        this.<Apply>g__ModBase|19_2(959, CS$<>8__locals1.a / 40, false, ref CS$<>8__locals1);
                        this.<Apply>g__ModBase|19_2(964, CS$<>8__locals1.a / 40, false, ref CS$<>8__locals1);
                        this.<Apply>g__ModBase|19_2(961, CS$<>8__locals1.a / 40, false, ref CS$<>8__locals1);
                        goto IL_12F3;
                    case 1221:
                        this.<Apply>g__ModBase|19_2(964, CS$<>8__locals1.a * 20, false, ref CS$<>8__locals1);
                        goto IL_12F3;
                    case 1223:
                        this.<Apply>g__ModBase|19_2(963, CS$<>8__locals1.a * 20, false, ref CS$<>8__locals1);
                        goto IL_12F3;
                    case 1224:
                        this.<Apply>g__ModBase|19_2(951, CS$<>8__locals1.a * 15, false, ref CS$<>8__locals1);
                        goto IL_12F3;
                    case 1226:
                        this.<Apply>g__ModBase|19_2(955, CS$<>8__locals1.a * 5, false, ref CS$<>8__locals1);
                        this.<Apply>g__ModBase|19_2(953, CS$<>8__locals1.a * 5, false, ref CS$<>8__locals1);
                        goto IL_12F3;
                    default:
                        if (i != 1230)
{
                            goto IL_12F3;
                        }
                        this.<Apply>g__ModBase|19_2(60, CS$<>8__locals1.A * 2 * CS$<>8__locals1.invert, false, ref CS$<>8__locals1);
                        this.<Apply>g__ModBase|19_2(79, CS$<>8__locals1.A * 3 * CS$<>8__locals1.invert, false, ref CS$<>8__locals1);
                        goto IL_12F3;
                    }
                }
                else
                {
                    if (i == 1233)
                    {
                        this.<Apply>g__ModBase|19_2(954, CS$<>8__locals1.a * 10, false, ref CS$<>8__locals1);
                        this.<Apply>g__ModBase|19_2(423, CS$<>8__locals1.a, false, ref CS$<>8__locals1);
                        this.<Apply>g__ModBase|19_2(425, CS$<>8__locals1.a, false, ref CS$<>8__locals1);
                        this.<Apply>g__ModBase|19_2(424, CS$<>8__locals1.a, false, ref CS$<>8__locals1);
                        this.<Apply>g__ModBase|19_2(421, CS$<>8__locals1.a, false, ref CS$<>8__locals1);
                        goto IL_12F3;
                    }
                    if (i != 1300 && i != 1305)
                    {
                        goto IL_12F3;
                    }
                }
            }
            else if (i <= 1315)
            {
                if (i != 1310 && i != 1315)
                {
                    goto IL_12F3;
                }
            }
            else if (i != 1320 && i != 1325 && i != 1330)
            {
                goto IL_12F3;
            }
        }
        else if (i <= 1355)
        {
            if (i <= 1340)
            {
                if (i != 1335 && i != 1340)
                {
                    goto IL_12F3;
                }
            }
            else if (i != 1345 && i != 1350 && i != 1355)
            {
                goto IL_12F3;
            }
        }
        else if (i <= 1415)
        {
            switch (i)
            {
            case 1400:
                Feat.featRef[0] = ((CS$<>8__locals1.a * 10).ToString() ?? "");
                goto IL_12F3;
            case 1401:
                this.<Apply>g__ModBase|19_2(78, CS$<>8__locals1.a * 15, false, ref CS$<>8__locals1);
                goto IL_12F3;
            case 1402:
            case 1403:
            case 1405:
                goto IL_12F3;
            case 1404:
                Feat.featRef[0] = ((CS$<>8__locals1.a * 10).ToString() ?? "");
                goto IL_12F3;
            case 1406:
                Feat.featRef[0] = ((CS$<>8__locals1.a * 20).ToString() ?? "");
                Feat.featRef[1] = ((CS$<>8__locals1.a * 5).ToString() ?? "");
                goto IL_12F3;
            default:
                if (i != 1415)
                {
                    goto IL_12F3;
                }
                this.<Apply>g__ModBase|19_2(60, CS$<>8__locals1.a * 15, false, ref CS$<>8__locals1);
                this.<Apply>g__ModBase|19_2(79, CS$<>8__locals1.a * 5, false, ref CS$<>8__locals1);
                this.<Apply>g__ModBase|19_2(953, CS$<>8__locals1.a * 3, false, ref CS$<>8__locals1);
                this.<Apply>g__ModBase|19_2(961, CS$<>8__locals1.a, false, ref CS$<>8__locals1);
                this.<Apply>g__ModBase|19_2(960, CS$<>8__locals1.a, false, ref CS$<>8__locals1);
                goto IL_12F3;
            }
        }
        else
        {
            if (i == 1419)
            {
                this.<Apply>g__ModPotential|19_3(101, CS$<>8__locals1.a * 50, ref CS$<>8__locals1);
                this.<Apply>g__ModPotential|19_3(111, CS$<>8__locals1.a * 50, ref CS$<>8__locals1);
                this.<Apply>g__ModPotential|19_3(103, CS$<>8__locals1.a * 50, ref CS$<>8__locals1);
                this.<Apply>g__ModPotential|19_3(106, CS$<>8__locals1.a * 50, ref CS$<>8__locals1);
                this.<Apply>g__ModPotential|19_3(122, CS$<>8__locals1.a * 50, ref CS$<>8__locals1);
                this.<Apply>g__ModPotential|19_3(120, CS$<>8__locals1.a * 50, ref CS$<>8__locals1);
                this.<Apply>g__ModPotential|19_3(123, CS$<>8__locals1.a * 50, ref CS$<>8__locals1);
                goto IL_12F3;
            }
            switch (i)
            {
            case 1510:
                this.<Apply>g__ModBase|19_2(65, CS$<>8__locals1.a * 3, false, ref CS$<>8__locals1);
                goto IL_12F3;
            case 1511:
                this.<Apply>g__ModBase|19_2(65, -CS$<>8__locals1.a * 3, false, ref CS$<>8__locals1);
                goto IL_12F3;
            case 1512:
                this.<Apply>g__ModBase|19_2(73, CS$<>8__locals1.a * 5, false, ref CS$<>8__locals1);
                goto IL_12F3;
            case 1513:
                this.<Apply>g__ModBase|19_2(73, -CS$<>8__locals1.a * 5, false, ref CS$<>8__locals1);
                goto IL_12F3;
            case 1514:
                this.<Apply>g__ModBase|19_2(72, CS$<>8__locals1.a * 3, false, ref CS$<>8__locals1);
                goto IL_12F3;
            case 1515:
                this.<Apply>g__ModBase|19_2(72, -CS$<>8__locals1.a * 3, false, ref CS$<>8__locals1);
                goto IL_12F3;
            case 1516:
                this.<Apply>g__ModBase|19_2(300, CS$<>8__locals1.a * 4, false, ref CS$<>8__locals1);
                goto IL_12F3;
            case 1517:
                this.<Apply>g__ModBase|19_2(300, -CS$<>8__locals1.a * 4, false, ref CS$<>8__locals1);
                goto IL_12F3;
            case 1518:
                this.<Apply>g__ModBase|19_2(79, CS$<>8__locals1.a * 5, false, ref CS$<>8__locals1);
                goto IL_12F3;
            case 1519:
                this.<Apply>g__ModBase|19_2(79, -CS$<>8__locals1.a * 5, false, ref CS$<>8__locals1);
                goto IL_12F3;
            case 1520:
                this.<Apply>g__ModBase|19_2(70, CS$<>8__locals1.a * 3, false, ref CS$<>8__locals1);
                goto IL_12F3;
            case 1521:
                this.<Apply>g__ModBase|19_2(70, -CS$<>8__locals1.a * 3, false, ref CS$<>8__locals1);
                goto IL_12F3;
            case 1522:
                this.<Apply>g__ModBase|19_2(77, CS$<>8__locals1.a * 5, false, ref CS$<>8__locals1);
                goto IL_12F3;
            case 1523:
                this.<Apply>g__ModBase|19_2(77, -CS$<>8__locals1.a * 5, false, ref CS$<>8__locals1);
                goto IL_12F3;
            case 1524:
                this.<Apply>g__ModBase|19_2(307, CS$<>8__locals1.a * 4, false, ref CS$<>8__locals1);
                goto IL_12F3;
            case 1525:
                this.<Apply>g__ModBase|19_2(307, -CS$<>8__locals1.a * 4, false, ref CS$<>8__locals1);
                goto IL_12F3;
            case 1526:
                this.<Apply>g__ModBase|19_2(951, CS$<>8__locals1.a * 5, false, ref CS$<>8__locals1);
                this.<Apply>g__ModBase|19_2(950, -CS$<>8__locals1.a * 5, false, ref CS$<>8__locals1);
                goto IL_12F3;
            case 1527:
                this.<Apply>g__ModBase|19_2(951, -CS$<>8__locals1.a * 5, false, ref CS$<>8__locals1);
                this.<Apply>g__ModBase|19_2(950, CS$<>8__locals1.a * 5, false, ref CS$<>8__locals1);
                goto IL_12F3;
            case 1528:
                this.<Apply>g__ModBase|19_2(952, CS$<>8__locals1.a * 5, false, ref CS$<>8__locals1);
                goto IL_12F3;
            case 1529:
                this.<Apply>g__ModBase|19_2(952, -CS$<>8__locals1.a * 5, false, ref CS$<>8__locals1);
                goto IL_12F3;
            case 1530:
                this.<Apply>g__ModBase|19_2(960, CS$<>8__locals1.a * 5, false, ref CS$<>8__locals1);
                this.<Apply>g__ModBase|19_2(956, -CS$<>8__locals1.a * 5, false, ref CS$<>8__locals1);
                goto IL_12F3;
            case 1531:
                this.<Apply>g__ModBase|19_2(960, -CS$<>8__locals1.a * 5, false, ref CS$<>8__locals1);
                this.<Apply>g__ModBase|19_2(956, CS$<>8__locals1.a * 5, false, ref CS$<>8__locals1);
                goto IL_12F3;
            case 1532:
            case 1533:
            case 1534:
            case 1535:
            case 1536:
            case 1537:
            case 1538:
            case 1539:
            case 1540:
            case 1541:
            case 1542:
            case 1543:
            case 1544:
            case 1545:
            case 1546:
            case 1547:
            case 1548:
            case 1549:
            case 1558:
            case 1559:
                goto IL_12F3;
            case 1550:
                this.<Apply>g__ModBase|19_2(404, -CS$<>8__locals1.a * 10, false, ref CS$<>8__locals1);
                goto IL_12F3;
            case 1551:
                this.<Apply>g__ModBase|19_2(77, -CS$<>8__locals1.a * (4 + num / 5), false, ref CS$<>8__locals1);
                goto IL_12F3;
            case 1552:
                this.<Apply>g__ModBase|19_2(79, CS$<>8__locals1.a * Mathf.Min(30 + num / 5, 100), false, ref CS$<>8__locals1);
                if (!CS$<>8__locals1.hint && CS$<>8__locals1.a > 0 && chara != null)
                {
                    chara.body.UnequipAll(39);
                    goto IL_12F3;
                }
                goto IL_12F3;
            case 1553:
                this.<Apply>g__ModBase|19_2(73, CS$<>8__locals1.a * (5 + num / 3), false, ref CS$<>8__locals1);
                this.<Apply>g__ModBase|19_2(77, -CS$<>8__locals1.a * (5 + num / 3), false, ref CS$<>8__locals1);
                goto IL_12F3;
            case 1554:
                this.<Apply>g__ModBase|19_2(404, CS$<>8__locals1.a * 10, false, ref CS$<>8__locals1);
                this.<Apply>g__ModBase|19_2(401, CS$<>8__locals1.a, false, ref CS$<>8__locals1);
                this.<Apply>g__ModBase|19_2(79, CS$<>8__locals1.a * (10 + num / 5), false, ref CS$<>8__locals1);
                if (!CS$<>8__locals1.hint && CS$<>8__locals1.a > 0 && chara != null)
                {
                    chara.body.UnequipAll(33);
                    goto IL_12F3;
                }
                goto IL_12F3;
            case 1555:
                this.<Apply>g__ModBase|19_2(65, CS$<>8__locals1.a * (12 + num), false, ref CS$<>8__locals1);
                this.<Apply>g__ModBase|19_2(77, -CS$<>8__locals1.a * (5 + num / 5), false, ref CS$<>8__locals1);
                if (!CS$<>8__locals1.hint && CS$<>8__locals1.a > 0 && chara != null)
                {
                    chara.body.UnequipAll(31);
                    goto IL_12F3;
                }
                goto IL_12F3;
            case 1556:
                this.<Apply>g__ModBase|19_2(64, -CS$<>8__locals1.a * (10 + num), false, ref CS$<>8__locals1);
                this.<Apply>g__ModBase|19_2(67, CS$<>8__locals1.a * (5 + num / 2), false, ref CS$<>8__locals1);
                goto IL_12F3;
            case 1557:
                this.<Apply>g__ModBase|19_2(71, -CS$<>8__locals1.a * (5 + num / 3), false, ref CS$<>8__locals1);
                this.<Apply>g__ModBase|19_2(72, -CS$<>8__locals1.a * (4 + num / 4), false, ref CS$<>8__locals1);
                this.<Apply>g__ModBase|19_2(74, CS$<>8__locals1.a * (6 + num / 2), false, ref CS$<>8__locals1);
                this.<Apply>g__ModBase|19_2(75, CS$<>8__locals1.a * (2 + num / 6), false, ref CS$<>8__locals1);
                goto IL_12F3;
            case 1560:
                this.<Apply>g__ModBase|19_2(60, -CS$<>8__locals1.a * 15, false, ref CS$<>8__locals1);
                this.<Apply>g__ModBase|19_2(70, -CS$<>8__locals1.a * (4 + num / 3), false, ref CS$<>8__locals1);
                goto IL_12F3;
            case 1561:
                this.<Apply>g__ModBase|19_2(61, -CS$<>8__locals1.a * 15, false, ref CS$<>8__locals1);
                this.<Apply>g__ModBase|19_2(76, -CS$<>8__locals1.a * (4 + num / 3), false, ref CS$<>8__locals1);
                goto IL_12F3;
            case 1562:
                this.<Apply>g__ModBase|19_2(65, CS$<>8__locals1.a * (15 + num / 2), false, ref CS$<>8__locals1);
                this.<Apply>g__ModBase|19_2(79, -CS$<>8__locals1.a * (10 + num / 5), false, ref CS$<>8__locals1);
                goto IL_12F3;
            case 1563:
                this.<Apply>g__ModBase|19_2(77, -CS$<>8__locals1.a * (3 + num / 4), false, ref CS$<>8__locals1);
                goto IL_12F3;
            case 1564:
                this.<Apply>g__ModBase|19_2(961, CS$<>8__locals1.a * 5, false, ref CS$<>8__locals1);
                goto IL_12F3;
            case 1565:
                this.<Apply>g__ModBase|19_2(955, CS$<>8__locals1.a * 20, false, ref CS$<>8__locals1);
                goto IL_12F3;
            default:
                switch (i)
                {
                case 1610:
                    this.<Apply>g__ModBase|19_2(60, CS$<>8__locals1.a * 4, false, ref CS$<>8__locals1);
                    goto IL_12F3;
                case 1611:
                    this.<Apply>g__ModBase|19_2(61, CS$<>8__locals1.a * 4, false, ref CS$<>8__locals1);
                    goto IL_12F3;
                case 1612:
                    this.<Apply>g__ModBase|19_2(62, CS$<>8__locals1.a * 4, false, ref CS$<>8__locals1);
                    goto IL_12F3;
                case 1613:
                case 1614:
                case 1615:
                case 1616:
                case 1617:
                case 1618:
                case 1619:
                case 1637:
                case 1638:
                case 1639:
                case 1641:
                    goto IL_12F3;
                case 1620:
                    this.<Apply>g__ModAttribute|19_4(70, ref CS$<>8__locals1);
                    goto IL_12F3;
                case 1621:
                    this.<Apply>g__ModAttribute|19_4(72, ref CS$<>8__locals1);
                    goto IL_12F3;
                case 1622:
                    this.<Apply>g__ModAttribute|19_4(71, ref CS$<>8__locals1);
                    goto IL_12F3;
                case 1623:
                    this.<Apply>g__ModAttribute|19_4(73, ref CS$<>8__locals1);
                    goto IL_12F3;
                case 1624:
                    this.<Apply>g__ModAttribute|19_4(74, ref CS$<>8__locals1);
                    goto IL_12F3;
                case 1625:
                    this.<Apply>g__ModAttribute|19_4(76, ref CS$<>8__locals1);
                    goto IL_12F3;
                case 1626:
                    this.<Apply>g__ModAttribute|19_4(75, ref CS$<>8__locals1);
                    goto IL_12F3;
                case 1627:
                    this.<Apply>g__ModAttribute|19_4(77, ref CS$<>8__locals1);
                    goto IL_12F3;
                case 1628:
                    this.<Apply>g__ModBase|19_2(78, CS$<>8__locals1.a * 2, false, ref CS$<>8__locals1);
                    goto IL_12F3;
                case 1629:
                    this.<Apply>g__ModBase|19_2(79, CS$<>8__locals1.a * 5, false, ref CS$<>8__locals1);
                    goto IL_12F3;
                case 1630:
                    this.<Apply>g__ModBase|19_2(65, ((CS$<>8__locals1.A == 1) ? 2 : ((CS$<>8__locals1.A == 2) ? 5 : 10)) * CS$<>8__locals1.invert, false, ref CS$<>8__locals1);
                    goto IL_12F3;
                case 1631:
                    this.<Apply>g__ModBase|19_2(64, ((CS$<>8__locals1.A == 1) ? 2 : ((CS$<>8__locals1.A == 2) ? 5 : 10)) * CS$<>8__locals1.invert, false, ref CS$<>8__locals1);
                    goto IL_12F3;
                case 1632:
                    this.<Apply>g__ModBase|19_2(150, CS$<>8__locals1.a * 2, false, ref CS$<>8__locals1);
                    goto IL_12F3;
                case 1633:
                    this.<Apply>g__ModBase|19_2(210, CS$<>8__locals1.a * 3, false, ref CS$<>8__locals1);
                    this.<Apply>g__ModBase|19_2(402, ((CS$<>8__locals1.A == 3) ? 1 : 0) * CS$<>8__locals1.invert, false, ref CS$<>8__locals1);
                    goto IL_12F3;
                case 1634:
                    this.<Apply>g__ModBase|19_2(291, CS$<>8__locals1.a * 4, false, ref CS$<>8__locals1);
                    goto IL_12F3;
                case 1635:
                    this.<Apply>g__ModBase|19_2(100, CS$<>8__locals1.a * 3, false, ref CS$<>8__locals1);
                    goto IL_12F3;
                case 1636:
                    this.<Apply>g__ModBase|19_2(306, CS$<>8__locals1.a * 4, false, ref CS$<>8__locals1);
                    goto IL_12F3;
                case 1640:
                    this.<Apply>g__ModBase|19_2(77, CS$<>8__locals1.a * 2, false, ref CS$<>8__locals1);
                    goto IL_12F3;
                case 1642:
                    Feat.featRef[0] = (((CS$<>8__locals1.a == 1) ? 10 : ((CS$<>8__locals1.a == 2) ? 20 : 30)).ToString() ?? "");
                    goto IL_12F3;
                case 1643:
                    Feat.featRef[0] = (((CS$<>8__locals1.a == 1) ? 1 : ((CS$<>8__locals1.a == 2) ? 3 : 5)).ToString() ?? "");
                    goto IL_12F3;
                case 1644:
                    Feat.featRef[0] = (CS$<>8__locals1.a.ToString() ?? "");
                    if (!CS$<>8__locals1.hint && CS$<>8__locals1.a > 0)
                    {
                        CS$<>8__locals1.owner.Chara.AddRandomBodyPart(CS$<>8__locals1.owner.Chara.IsPC);
                        if (CS$<>8__locals1.owner.Chara.IsPC && WidgetEquip.Instance)
{
                            WidgetEquip.Instance.Rebuild();
                        }
                    }
                    this.<Apply>g__ModBase|19_2(60, (CS$<>8__locals1.A > 5) ? ((CS$<>8__locals1.A - 5) * -3 * CS$<>8__locals1.invert) : 0, false, ref CS$<>8__locals1);
                    this.<Apply>g__ModBase|19_2(79, (CS$<>8__locals1.A > 5) ? ((CS$<>8__locals1.A - 5) * -5 * CS$<>8__locals1.invert) : 0, false, ref CS$<>8__locals1);
                    this.<Apply>g__ModBase|19_2(77, (CS$<>8__locals1.A > 5) ? ((CS$<>8__locals1.A - 5) * -3 * CS$<>8__locals1.invert) : 0, false, ref CS$<>8__locals1);
                    goto IL_12F3;
                default:
                    goto IL_12F3;
                }
                break;
            }
        }
        this.<Apply>g__GodHint|19_5(ref CS$<>8__locals1);
        IL_12F3:
        if (CS$<>8__locals1.hint)
        {
            string text = base.source.GetText("textExtra", false);
            if (!text.IsEmpty())
            {
                string text2 = text.SplitNewline().TryGet(value - 1, 99);
                if (!text2.IsEmpty())
                {
                    int num2 = 0;
                    string[] array = text2.Split(',', StringSplitOptions.None);
                    for (i = 0; i < array.Length; i++)
                    {
                        string item = array[i].Replace("#1", Feat.featRef[num2]);
                        Feat.hints.Add(item);
                        num2++;
                    }
                }
            }
        }
        return Feat.hints;
    }
References Apply(), Chara.body, Card.Chara, featRef, g__GodHint(), g__ModAttribute(), g__ModBase(), g__ModPotential(), hint, hints, Element.id, WidgetEquip.Instance, Card.LV, Element.owner, WidgetEquip.Rebuild(), CharaBody.UnequipAll(), and Element.vPotential.
Referenced by Apply(), g__GodHint(), g__ModAttribute(), g__ModBase(), g__ModPotential(), g__NoteElement(), GetHint(), OnWriteNote(), and Chara.SetFeat().
Apply() [2/2]
List< string > Feat.Apply (int a, ElementContainer owner, bool hint = false) inline
Definition at line 309 of file FEAT.cs.
    {
        if (hint)
        {
            hints.Clear();
        }
        int value = base.Value;
        int A = Mathf.Abs(a);
        int invert = ((a >= 0) ? 1 : (-1));
        if (hint)
        {
            featRef[0] = a.ToString() ?? "";
            featRef[1] = a.ToString() ?? "";
        }
        Chara chara = owner.Chara;
        int num = vPotential;
        if (!hint && a > 0 && chara != null)
        {
            num = (vPotential = chara.LV);
        }
        switch (id)
        {
        case 1206:
            ModBase(78, -a * 10, hide: false);
            break;
        case 1642:
            featRef[0] = ((a == 1) ? 10 : ((a == 2) ? 20 : 30)).ToString() ?? "";
            break;
        case 1643:
            featRef[0] = ((a == 1) ? 1 : ((a == 2) ? 3 : 5)).ToString() ?? "";
            break;
        case 1610:
            ModBase(60, a * 4, hide: false);
            break;
        case 1611:
            ModBase(61, a * 4, hide: false);
            break;
        case 1612:
            ModBase(62, a * 4, hide: false);
            break;
        case 1620:
            ModAttribute(70);
            break;
        case 1621:
            ModAttribute(72);
            break;
        case 1622:
            ModAttribute(71);
            break;
        case 1623:
            ModAttribute(73);
            break;
        case 1626:
            ModAttribute(75);
            break;
        case 1625:
            ModAttribute(76);
            break;
        case 1627:
            ModAttribute(77);
            break;
        case 1624:
            ModAttribute(74);
            break;
        case 1629:
            ModBase(79, a * 5, hide: false);
            break;
        case 1630:
            ModBase(65, ((A == 1) ? 2 : ((A == 2) ? 5 : 10)) * invert, hide: false);
            break;
        case 1631:
            ModBase(64, ((A == 1) ? 2 : ((A == 2) ? 5 : 10)) * invert, hide: false);
            break;
        case 1632:
            ModBase(150, a * 2, hide: false);
            break;
        case 1633:
            ModBase(210, a * 3, hide: false);
            ModBase(402, ((A == 3) ? 1 : 0) * invert, hide: false);
            break;
        case 1634:
            ModBase(291, a * 4, hide: false);
            break;
        case 1635:
            ModBase(100, a * 3, hide: false);
            break;
        case 1636:
            ModBase(306, a * 4, hide: false);
            break;
        case 1628:
            ModBase(78, a * 2, hide: false);
            break;
        case 1640:
            ModBase(77, a * 2, hide: false);
            break;
        case 1400:
            featRef[0] = (a * 10).ToString() ?? "";
            break;
        case 1404:
            featRef[0] = (a * 10).ToString() ?? "";
            break;
        case 1401:
            ModBase(78, a * 15, hide: false);
            break;
        case 1406:
            featRef[0] = (a * 20).ToString() ?? "";
            featRef[1] = (a * 5).ToString() ?? "";
            break;
        case 1644:
            featRef[0] = a.ToString() ?? "";
            if (!hint && a > 0)
            {
                owner.Chara.AddRandomBodyPart(owner.Chara.IsPC);
                if (owner.Chara.IsPC && (bool)WidgetEquip.Instance)
                {
                    WidgetEquip.Instance.Rebuild();
                }
            }
            ModBase(60, (A > 5) ? ((A - 5) * -3 * invert) : 0, hide: false);
            ModBase(79, (A > 5) ? ((A - 5) * -5 * invert) : 0, hide: false);
            ModBase(77, (A > 5) ? ((A - 5) * -3 * invert) : 0, hide: false);
            break;
        case 1230:
            ModBase(60, A * 2 * invert, hide: false);
            ModBase(79, A * 3 * invert, hide: false);
            break;
        case 1204:
            ModBase(64, a * 50, hide: true);
            ModBase(401, a, hide: false);
            break;
        case 1202:
            ModBase(403, a * 20, hide: true);
            break;
        case 1210:
            ModBase(955, a * 5, hide: false);
            ModBase(953, a * 10, hide: false);
            ModBase(958, a * 5, hide: false);
            ModBase(956, a * 10, hide: false);
            ModBase(950, a * -5, hide: false);
            break;
        case 1233:
            ModBase(954, a * 10, hide: false);
            ModBase(423, a, hide: false);
            ModBase(425, a, hide: false);
            ModBase(424, a, hide: false);
            ModBase(421, a, hide: false);
            break;
        case 1226:
            ModBase(955, a * 5, hide: false);
            ModBase(953, a * 5, hide: false);
            break;
        case 1212:
            ModBase(961, a * 5, hide: false);
            ModBase(953, a * 5, hide: false);
            ModBase(958, a * 5, hide: false);
            ModBase(956, a * 5, hide: false);
            ModBase(954, a * 5, hide: false);
            ModBase(957, a * 5, hide: false);
            ModBase(959, a * 5, hide: false);
            break;
        case 1213:
            ModBase(962, a * 20, hide: false);
            break;
        case 1224:
            ModBase(951, a * 15, hide: false);
            break;
        case 1217:
            ModBase(952, a * -10, hide: false);
            ModBase(955, a * 20, hide: false);
            ModBase(964, a * 20, hide: false);
            break;
        case 1218:
            ModBase(950, a / 40, hide: false);
            ModBase(952, a / 40, hide: false);
            ModBase(955, a / 40, hide: false);
            ModBase(953, a / 40, hide: false);
            ModBase(958, a / 40, hide: false);
            ModBase(956, a / 40, hide: false);
            ModBase(954, a / 40, hide: false);
            ModBase(959, a / 40, hide: false);
            ModBase(964, a / 40, hide: false);
            ModBase(961, a / 40, hide: false);
            break;
        case 1221:
            ModBase(964, a * 20, hide: false);
            break;
        case 1223:
            ModBase(963, a * 20, hide: false);
            break;
        case 1216:
            ModBase(6020, a, hide: false);
            break;
        case 1415:
            ModBase(60, a * 15, hide: false);
            ModBase(79, a * 5, hide: false);
            ModBase(953, a * 3, hide: false);
            ModBase(961, a, hide: false);
            ModBase(960, a, hide: false);
            break;
        case 1419:
            ModPotential(101, a * 50);
            ModPotential(111, a * 50);
            ModPotential(103, a * 50);
            ModPotential(106, a * 50);
            ModPotential(122, a * 50);
            ModPotential(120, a * 50);
            ModPotential(123, a * 50);
            break;
        case 1510:
            ModBase(65, a * 3, hide: false);
            break;
        case 1511:
            ModBase(65, -a * 3, hide: false);
            break;
        case 1512:
            ModBase(73, a * 5, hide: false);
            break;
        case 1513:
            ModBase(73, -a * 5, hide: false);
            break;
        case 1514:
            ModBase(72, a * 3, hide: false);
            break;
        case 1515:
            ModBase(72, -a * 3, hide: false);
            break;
        case 1516:
            ModBase(300, a * 4, hide: false);
            break;
        case 1517:
            ModBase(300, -a * 4, hide: false);
            break;
        case 1518:
            ModBase(79, a * 5, hide: false);
            break;
        case 1519:
            ModBase(79, -a * 5, hide: false);
            break;
        case 1520:
            ModBase(70, a * 3, hide: false);
            break;
        case 1521:
            ModBase(70, -a * 3, hide: false);
            break;
        case 1522:
            ModBase(77, a * 5, hide: false);
            break;
        case 1523:
            ModBase(77, -a * 5, hide: false);
            break;
        case 1524:
            ModBase(307, a * 4, hide: false);
            break;
        case 1525:
            ModBase(307, -a * 4, hide: false);
            break;
        case 1526:
            ModBase(951, a * 5, hide: false);
            ModBase(950, -a * 5, hide: false);
            break;
        case 1527:
            ModBase(951, -a * 5, hide: false);
            ModBase(950, a * 5, hide: false);
            break;
        case 1528:
            ModBase(952, a * 5, hide: false);
            break;
        case 1529:
            ModBase(952, -a * 5, hide: false);
            break;
        case 1530:
            ModBase(960, a * 5, hide: false);
            ModBase(956, -a * 5, hide: false);
            break;
        case 1531:
            ModBase(960, -a * 5, hide: false);
            ModBase(956, a * 5, hide: false);
            break;
        case 1300:
        case 1305:
        case 1310:
        case 1315:
        case 1320:
        case 1325:
        case 1330:
        case 1335:
        case 1340:
        case 1345:
        case 1350:
        case 1355:
            GodHint();
            break;
        case 1550:
            ModBase(404, -a * 10, hide: false);
            break;
        case 1551:
            ModBase(77, -a * (4 + num / 5), hide: false);
            break;
        case 1552:
            ModBase(79, a * Mathf.Min(30 + num / 5, 100), hide: false);
            if (!hint && a > 0)
            {
                chara?.body.UnequipAll(39);
            }
            break;
        case 1553:
            ModBase(73, a * (5 + num / 3), hide: false);
            ModBase(77, -a * (5 + num / 3), hide: false);
            break;
        case 1554:
            ModBase(404, a * 10, hide: false);
            ModBase(401, a, hide: false);
            ModBase(79, a * (10 + num / 5), hide: false);
            if (!hint && a > 0)
            {
                chara?.body.UnequipAll(33);
            }
            break;
        case 1555:
            ModBase(65, a * (12 + num), hide: false);
            ModBase(77, -a * (5 + num / 5), hide: false);
            if (!hint && a > 0)
            {
                chara?.body.UnequipAll(31);
            }
            break;
        case 1556:
            ModBase(64, -a * (10 + num), hide: false);
            ModBase(67, a * (5 + num / 2), hide: false);
            break;
        case 1557:
            ModBase(71, -a * (5 + num / 3), hide: false);
            ModBase(72, -a * (4 + num / 4), hide: false);
            ModBase(74, a * (6 + num / 2), hide: false);
            ModBase(75, a * (2 + num / 6), hide: false);
            break;
        case 1560:
            ModBase(60, -a * 15, hide: false);
            ModBase(70, -a * (4 + num / 3), hide: false);
            break;
        case 1561:
            ModBase(61, -a * 15, hide: false);
            ModBase(76, -a * (4 + num / 3), hide: false);
            break;
        case 1562:
            ModBase(65, a * (15 + num / 2), hide: false);
            ModBase(79, -a * (10 + num / 5), hide: false);
            break;
        case 1563:
            ModBase(77, -a * (3 + num / 4), hide: false);
            break;
        case 1564:
            ModBase(961, a * 5, hide: false);
            break;
        case 1565:
            ModBase(955, a * 20, hide: false);
            break;
        }
        if (hint)
        {
            string text = base.source.GetText("textExtra");
            if (!text.IsEmpty())
            {
                string text2 = text.SplitNewline().TryGet(value - 1, 99);
                if (!text2.IsEmpty())
                {
                    int num2 = 0;
                    string[] array = text2.Split(',');
                    for (int i = 0; i < array.Length; i++)
                    {
                        string item = array[i].Replace("#1", featRef[num2]);
                        hints.Add(item);
                        num2++;
                    }
                }
            }
        }
        return hints;
        void GodHint()
        {
            if (!hint)
            {
                return;
            }
            foreach (Element value2 in owner.Card.Chara.faithElements.dict.Values)
            {
                if (value2.source.id != id)
                {
                    NoteElement(value2.id, value2.Value);
                }
            }
        }
        void ModAttribute(int ele)
        {
            if (!hint)
            {
                Debug.Log(A);
                Debug.Log(((A == 1) ? 2 : ((A == 2) ? 4 : 5)) * invert);
            }
            ModBase(ele, ((A == 1) ? 2 : ((A == 2) ? 4 : 5)) * invert, hide: false);
            ModPotential(ele, a * 10);
        }
        void ModBase(int ele, int _v, bool hide)
        {
            if (!hint)
            {
                owner.ModBase(ele, _v);
            }
            if (!hide && _v != 0)
            {
                NoteElement(ele, _v);
            }
        }
        void ModPotential(int ele, int _v)
        {
            if (!hint)
            {
                owner.ModPotential(ele, _v);
            }
            Note("modPotential".lang(EClass.sources.elements.map[ele].GetName(), "+" + _v + "%"));
        }
        void Note(string s)
        {
            if (hint)
            {
                hints.Add(s);
            }
        }
        void NoteElement(int ele, int a)
        {
            SourceElement.Row row = EClass.sources.elements.map[ele];
            if (row.category == "ability")
            {
                Note("hintLearnAbility".lang(row.GetName().ToTitleCase()));
            }
            else if (row.tag.Contains("flag"))
            {
                Note(row.GetName());
            }
            else
            {
                string @ref = ((a < 0) ? "" : "+") + a;
                if (row.category == "resist")
                {
                    int num3 = 0;
                    @ref = ((a > 0) ? "+" : "-").Repeat(Mathf.Clamp(Mathf.Abs(a) / 5 + num3, 1, 5));
                    Note("modValueRes".lang(row.GetName(), @ref));
                }
                else
                {
                    Note("modValue".lang(row.GetName(), @ref));
                }
            }
        }
    }
References Chara.AddRandomBodyPart(), Chara.body, ElementContainer.Card, SourceElement.Row.category, Card.Chara, ElementContainer.Chara, ElementContainer.dict, SourceManager.elements, Chara.faithElements, featRef, SourceElement.Row.GetName(), hint, hints, Element.id, WidgetEquip.Instance, Chara.IsPC, Card.LV, ElementContainer.ModBase(), ModPotential, ElementContainer.ModPotential(), Element.owner, WidgetEquip.Rebuild(), Element.source, EClass.sources, SourceElement.Row.tag, CharaBody.UnequipAll(), Element.Value, and Element.vPotential.
CanLink() [1/2]
override bool Feat.CanLink (ElementContainer owner) inline virtual
Reimplemented from Element.
Definition at line 33 of file Feat.2.cs.
    {
        return !base.IsGlobalElement;
    }
CanLink() [2/2]
override bool Feat.CanLink (ElementContainer owner) inline virtual
Reimplemented from Element.
Definition at line 266 of file FEAT.cs.
    {
        return !base.IsGlobalElement;
    }
g__GodHint()
void< Apply > Feat.g__GodHint (ref Feat::<>c__DisplayClass19_0 A_1) inline private
Definition at line 670 of file Feat.2.cs.
    {
        if (!A_1.hint)
        {
            return;
        }
        foreach (Element element in A_1.owner.Card.Chara.faithElements.dict.Values)
        {
            if (element.source.id != this.id)
            {
                this.<Apply>g__NoteElement|19_1(element.id, element.Value, ref A_1);
            }
        }
    }
References Apply(), ElementContainer.Card, Card.Chara, ElementContainer.dict, Chara.faithElements, g__NoteElement(), Element.id, Element.owner, Element.source, and Element.Value.
Referenced by Apply().
g__ModAttribute()
void< Apply > Feat.g__ModAttribute (int ele, ref Feat::<>c__DisplayClass19_0 A_2) inline private
Definition at line 658 of file Feat.2.cs.
    {
        if (!A_2.hint)
        {
            Debug.Log(A_2.A);
            Debug.Log(((A_2.A == 1) ? 2 : ((A_2.A == 2) ? 4 : 5)) * A_2.invert);
        }
        this.<Apply>g__ModBase|19_2(ele, ((A_2.A == 1) ? 2 : ((A_2.A == 2) ? 4 : 5)) * A_2.invert, false, ref A_2);
        this.<Apply>g__ModPotential|19_3(ele, A_2.a * 10, ref A_2);
    }
References Apply(), g__ModBase(), and g__ModPotential().
Referenced by Apply().
g__ModBase()
void< Apply > Feat.g__ModBase (int ele, int _v, bool hide, ref Feat::<>c__DisplayClass19_0 A_4) inline private
Definition at line 635 of file Feat.2.cs.
    {
        if (!A_4.hint)
        {
            A_4.owner.ModBase(ele, _v);
        }
        if (!hide && _v != 0)
        {
            this.<Apply>g__NoteElement|19_1(ele, _v, ref A_4);
        }
    }
References Apply(), and g__NoteElement().
Referenced by Apply(), and g__ModAttribute().
g__ModPotential()
void< Apply > Feat.g__ModPotential (int ele, int _v, ref Feat::<>c__DisplayClass19_0 A_3) inline private
Definition at line 648 of file Feat.2.cs.
    {
        if (!A_3.hint)
        {
            A_3.owner.ModPotential(ele, _v);
        }
        this.<Apply>g__Note|19_0("modPotential".lang(EClass.sources.elements.map[ele].GetName(), "+" + _v.ToString() + "%", null, null, null), ref A_3);
    }
References Apply(), SourceManager.elements, g__Note(), and EClass.sources.
Referenced by Apply(), and g__ModAttribute().
g__Note()
void< Apply > Feat.g__Note (string s, ref Feat::<>c__DisplayClass19_0 A_2) inline private
Definition at line 600 of file Feat.2.cs.
    {
        if (!A_2.hint)
        {
            return;
        }
        Feat.hints.Add(s);
    }
References hints.
Referenced by g__ModPotential(), and g__NoteElement().
g__NoteElement()
void< Apply > Feat.g__NoteElement (int ele, int a, ref Feat::<>c__DisplayClass19_0 A_3) inline private
Definition at line 610 of file Feat.2.cs.
    {
        SourceElement.Row row = EClass.sources.elements.map[ele];
        if (row.category == "ability")
        {
            this.<Apply>g__Note|19_0("hintLearnAbility".lang(row.GetName().ToTitleCase(false), null, null, null, null), ref A_3);
            return;
        }
        if (row.tag.Contains("flag"))
        {
            this.<Apply>g__Note|19_0(row.GetName(), ref A_3);
            return;
        }
        string @ref = ((a < 0) ? "" : "+") + a.ToString();
        if (row.category == "resist")
        {
            int num = 0;
            @ref = ((a > 0) ? "+" : "-").Repeat(Mathf.Clamp(Mathf.Abs(a) / 5 + num, 1, 5));
            this.<Apply>g__Note|19_0("modValueRes".lang(row.GetName(), @ref, null, null, null), ref A_3);
            return;
        }
        this.<Apply>g__Note|19_0("modValue".lang(row.GetName(), @ref, null, null, null), ref A_3);
    }
References Apply(), SourceElement.Row.category, SourceManager.elements, g__Note(), SourceElement.Row.GetName(), EClass.sources, and SourceElement.Row.tag.
Referenced by g__GodHint(), and g__ModBase().
GetHint() [1/2]
string Feat.GetHint (ElementContainer owner) inline
Definition at line 76 of file Feat.2.cs.
    {
        string text = "";
        this.Apply(base.Value, owner, true);
        foreach (string str in Feat.hints)
        {
            text = text + str.StripLastPun() + ", ";
        }
        return text.TrimEnd(' ').TrimEnd(',');
    }
References Apply(), hints, and Element.owner.
GetHint() [2/2]
string Feat.GetHint (ElementContainer owner) inline
Definition at line 285 of file FEAT.cs.
    {
        string text = "";
        Apply(base.Value, owner, hint: true);
        foreach (string hint in hints)
        {
            text = text + hint.StripLastPun() + ", ";
        }
        return text.TrimEnd(' ').TrimEnd(',');
    }
References Apply(), hint, hints, and Element.owner.
GetIcon() [1/2]
override Sprite Feat.GetIcon (string suffix = "") inline virtual
Reimplemented from Element.
Definition at line 62 of file Feat.2.cs.
    {
        return SpriteSheet.Get("Media/Graphics/Icon/Element/icon_elements", "ele_Feat");
    }
GetIcon() [2/2]
override Sprite Feat.GetIcon (string suffix = "") inline virtual
Reimplemented from Element.
Definition at line 271 of file FEAT.cs.
    {
        return SpriteSheet.Get("Media/Graphics/Icon/Element/icon_elements", "ele_Feat");
    }
IsAvailable() [1/2]
bool Feat.IsAvailable (ElementContainer owner, int a = 1) inline
Definition at line 87 of file Feat.2.cs.
    {
        if (base.source.req.Length != 0)
        {
            Element element = owner.GetElement(base.source.req[0]);
            if (element == null || element.ValueWithoutLink < ((base.source.req.Length == 1) ? 1 : base.source.req[Mathf.Clamp(a, 1, base.source.req.Length - 1)].ToInt()))
            {
                return false;
            }
        }
        return true;
    }
References ElementContainer.GetElement(), Element.owner, and Element.ValueWithoutLink.
Referenced by Chara.ListAvailabeFeats().
IsAvailable() [2/2]
bool Feat.IsAvailable (ElementContainer owner, int a = 1) inline
Definition at line 296 of file FEAT.cs.
    {
        if (base.source.req.Length != 0)
        {
            Element element = owner.GetElement(base.source.req[0]);
            if (element == null || element.ValueWithoutLink < ((base.source.req.Length == 1) ? 1 : base.source.req[Mathf.Clamp(a, 1, base.source.req.Length - 1)].ToInt()))
            {
                return false;
            }
        }
        return true;
    }
References ElementContainer.GetElement(), Element.owner, and Element.ValueWithoutLink.
OnWriteNote() [1/2]
override void Feat.OnWriteNote (UINote n, ElementContainer owner) inline virtual
Reimplemented from Element.
Definition at line 67 of file Feat.2.cs.
    {
        this.Apply(base.Value, owner, true);
        foreach (string str in Feat.hints)
        {
            n.AddText("_bullet".lang() + str, FontColor.DontChange);
        }
    }
References Apply(), hints, and Element.owner.
OnWriteNote() [2/2]
override void Feat.OnWriteNote (UINote n, ElementContainer owner) inline virtual
Reimplemented from Element.
Definition at line 276 of file FEAT.cs.
    {
        Apply(base.Value, owner, hint: true);
        foreach (string hint in hints)
        {
            n.AddText("_bullet".lang() + hint);
        }
    }
References Apply(), hint, hints, and Element.owner.
Member Data Documentation
featRef
string [] Feat.featRef = new string[5] static
Definition at line 687 of file Feat.2.cs.
Referenced by Apply(), and ElementContainer.GetFeatRef().
hints
static List< string > Feat.hints = new List<string>() static
Definition at line 685 of file Feat.2.cs.
Referenced by Apply(), g__Note(), GetHint(), and OnWriteNote().
Property Documentation
CostLearn
override int Feat.CostLearn get
Definition at line 54 of file Feat.2.cs.
    {
        get
        {
            return base.source.cost.TryGet(base.Value - 1, -1);
        }
    }
FullName
override string Feat.FullName get
Definition at line 24 of file Feat.2.cs.
    {
        get
        {
            string[] array = base.source.GetText("name", false).SplitNewline();
            return array.TryGet(base.Value - 1, -1) + ((base.source.max > 1 && array.Length == 1 && base.Value > 1) ? (" " + base.Value.ToString()) : "");
        }
    }
Referenced by Chara.SetFeat().
Name
override string Feat.Name get
Definition at line 16 of file Feat.2.cs.
    {
        get
        {
            return base.source.GetText("name", false).SplitNewline().TryGet(base.Value - 1, -1);
        }
    }
ShowBonuses
override bool Feat.ShowBonuses get
Definition at line 8 of file Feat.2.cs.
    {
        get
        {
            return false;
        }
    }
ShowValue
override bool Feat.ShowValue get
Definition at line 46 of file Feat.2.cs.
    {
        get
        {
            return false;
        }
    }
ShowXP
override bool Feat.ShowXP get
Definition at line 38 of file Feat.2.cs.
    {
        get
        {
            return false;
        }
    }
The documentation for this class was generated from the following files:
Elin/Feat.2.cs
Elin/FEAT.cs