Elin Decompiled Documentation: LayerEditPCC Class Reference
LayerEditPCC Class Reference
Public Member Functions
void Activate (Chara _chara, UIPCC.Mode m, string idUniform=null, Action _onKill=null)
void Apply ()
void OnClickChangePortrait ()
override void OnKill ()
void SetPortraitSlider ()
Public Member Functions inherited from ELayer
override void OnBeforeAddLayer ()
void InitInspector ()
sealed override void Init ()
override void OnAfterAddLayer ()
void TryShowHelp ()
void AddLayerToUI (string id)
void TryShowHint (string _langHint=null)
void TalkHomeMemeber (string id)
void TalkMaid (string id)
override void OnRightClick ()
Public Member Functions inherited from Layer
virtual string GetTextHeader (Window window)
virtual bool HeaderIsListOf (int id)
virtual void Init ()
virtual void OnInit ()
virtual void OnAfterInit ()
virtual void ApplySkin ()
void ShowScreenLock (string id)
void UpdateInput ()
virtual void OnUpdateInput ()
virtual void OnRightClick ()
virtual bool OnBack ()
virtual void OnChangeLayer ()
virtual void OnCreate ()
void _AddLayer (string id)
Layer AddLayer (string id)
T AddLayer< T > ()
T AddLayer< T > (string id)
T AddLayerDontCloseOthers< T > ()
Layer AddLayerDontCloseOthers (Layer l)
T GetOrAddLayer< T > ()
virtual void OnBeforeAddLayer ()
virtual void OnAfterAddLayer ()
Layer AddLayer (Layer l)
void ToggleLayer (string id)
T ToggleLayer< T > (string id=null)
void WaitAndClose ()
void OnClickClose ()
virtual void Close ()
void CloseLayers ()
void RemoveLayers (bool removeImportant=false)
bool RemoveLayer< T > ()
void RemoveLayer (Layer l)
virtual void OnKill ()
Layer SetOnKill (Action action)
void DisableClose ()
void Delay (float duration=0.05f)
Layer SetDelay (float d)
Layer GetLayer (string id)
T GetLayer< T > (bool fromTop=false)
Layer GetTopLayer ()
void SwitchContent (int idWindow, int i)
virtual void OnSwitchContent (Window window)
Layer SetTitles (string langList, string idHeaderRow=null)
bool IsBlockWidgetClick ()
bool IsHideHud ()
bool IsAllowGeneralInput ()
bool IsUseBlur ()
bool IsPointerOnLayer ()
void ApplySkin ()
Public Attributes
UIPCC.Mode mode
UIPCC uiPCC
Portrait portrait
Chara chara
UISlider sliderPortrait
PCCData backup
string backupPortrait
bool applied
Public Attributes inherited from Layer
Option option
UnityEvent onKill
Anime animeIn
Anime animeOut
bool closeOthers
bool defaultActionMode = true
Button screenLock
Layer parent
string idLayer
List< Layer > layers = new List<Layer>()
Vector2 lastParentPos
List< Window > windows = new List<Window>()
string langHint
Properties
bool UniformMode [get]
bool IsMale [get]
Properties inherited from ELayer
static Core core [get]
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static FactionBranch Branch [get]
static Faction Home [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static CoreConfig config [get]
static GameSetting setting [get]
static ColorProfile Colors [get]
static SourceManager sources [get]
static World world [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
bool IsFloat [get]
virtual string IdHelp [get]
Properties inherited from Layer
Layer TopLayer [get]
string uid [get]
virtual RectTransform rectLayers [get]
virtual bool blockWidgetClick [get]
Private Member Functions
void Update ()
Private Attributes
Color lastHair
Additional Inherited Members
Static Public Member Functions inherited from ELayer
static int rnd (int a)
Static Public Member Functions inherited from Layer
static T Create< T > ()
static T Create< T > (string path)
static Layer Create (string path)
Static Public Attributes inherited from Layer
static int skipInput
static bool closeOnRightClick
static bool rightClicked
static bool cancelKeyDown
static bool ignoreSounds
static Transform blurStopInstance
static string[] searchPath = new string[3] { "Layer", "Layer/Dialog", "Layer/LayerHome" }
Protected Member Functions inherited from ELayer
sealed override void _Close ()
sealed override void Kill ()
Protected Member Functions inherited from Layer
virtual void Awake ()
virtual void _Close ()
virtual void Kill ()
Protected Attributes inherited from Layer
RectTransform _rect
bool isDestroyed
Detailed Description
Definition at line 5 of file LayerEditPCC.cs.
Member Function Documentation
Activate()
void LayerEditPCC.Activate (Chara _chara, UIPCC::Mode m, string idUniform = null, Action _onKill = null) inline
Definition at line 39 of file LayerEditPCC.cs.
    {
        chara = (_chara.IsPCC ? _chara : ELayer.pc);
        mode = m;
        uiPCC.exportPath = CorePath.user + "PCC/";
        uiPCC.onShowPalette = delegate(PCC pcc, string id, PCC.Part part, TestActor actor)
        {
            LayerColorPicker layerColorPicker = ELayer.ui.AddLayer<LayerColorPicker>();
            Color color = pcc.data.GetColor(id);
            layerColorPicker.SetColor(color, color, delegate(PickerState state, Color _c)
            {
                pcc.data.SetColor(id, _c);
                actor.Reset();
            });
        };
        PCCData newData = new PCCData();
        newData.Set(chara.pccData);
        backup = IO.DeepCopy(newData);
        backupPortrait = chara.c_idPortrait;
        if (UniformMode)
        {
            ELayer.game.uniforms.Apply(newData, idUniform, IsMale, canUseOtherGender: false);
            windows[0].SetCaption("_uniform".lang(ELayer.sources.jobs.map[idUniform].GetName().ToTitleCase(), IsMale ? "male".lang() : "female".lang()));
        }
        else
        {
            ELayer.game.uniforms.Apply(newData, PCCUniformManager.dummy);
        }
        uiPCC.Init(newData, mode);
        SetPortraitSlider();
        windows[0].AddBottomButton("removeAllCloth", delegate
        {
            uiPCC.RemoveAll();
            ELayer.Sound.Play("offering");
        });
        windows[0].AddBottomButton("reset", delegate
        {
            if (UniformMode)
            {
                ELayer.game.uniforms.RemoveUniform(newData);
            }
            uiPCC.Reset(backup);
            chara.c_idPortrait = backupPortrait;
            SetPortraitSlider();
            ELayer.Sound.Play("offering");
            newData.colors.Clear();
        });
        if (UniformMode)
        {
            PCCData otherUni = ELayer.game.uniforms.GetUniform(idUniform, !IsMale);
            if (otherUni != null)
            {
                windows[0].AddBottomButton("copyUniform", delegate
                {
                    PCCData pCCData = new PCCData();
                    pCCData.Set(chara.pccData);
                    ELayer.game.uniforms.Apply(pCCData, otherUni);
                    uiPCC.Reset(pCCData);
                    ELayer.Sound.Play("offering");
                });
            }
        }
        windows[2].SetActive(enable: true);
        portrait.SetActive(!UniformMode);
        if (_onKill != null)
        {
            SetOnKill(_onKill);
        }
    }
References backup, backupPortrait, Card.c_idPortrait, chara, Color, ELayer.game, IsMale, SourceManager.jobs, mode, ELayer.pc, Chara.pccData, portrait, LayerColorPicker.SetColor(), Layer.SetOnKill(), SetPortraitSlider(), ELayer.Sound, ELayer.sources, ELayer.ui, uiPCC, UniformMode, Game.uniforms, and Layer.windows.
Referenced by OnClickChangePortrait().
Apply()
void LayerEditPCC.Apply () inline
Definition at line 109 of file LayerEditPCC.cs.
    {
        PCCData data = uiPCC.pcc.data;
        ELayer.game.uniforms.Apply(data, chara.job.id, IsMale, canUseOtherGender: true);
        chara.pccData.Set(data);
        PCC.Get(chara.pccData).Build();
        chara.SetInt(105, IntColor.ToInt(chara.pccData.GetHairColor()));
        applied = true;
    }
References applied, chara, ELayer.game, IsMale, Chara.job, Chara.pccData, BaseCard.SetInt(), IntColor.ToInt(), uiPCC, and Game.uniforms.
OnClickChangePortrait()
void LayerEditPCC.OnClickChangePortrait () inline
Definition at line 119 of file LayerEditPCC.cs.
    {
        ELayer.ui.AddLayer<LayerEditPortrait>().Activate(chara, uiPCC.pcc.data, delegate
        {
            portrait.SetChara(chara, uiPCC.actor.data);
            uiPCC.actor.Reset();
        });
    }
References Activate(), chara, portrait, Portrait.SetChara(), ELayer.ui, and uiPCC.
OnKill()
override void LayerEditPCC.OnKill () inline virtual
Reimplemented from Layer.
Definition at line 128 of file LayerEditPCC.cs.
    {
        Apply();
    }
SetPortraitSlider()
void LayerEditPCC.SetPortraitSlider () inline
Definition at line 155 of file LayerEditPCC.cs.
    {
        if ((bool)sliderPortrait)
        {
            List<ModItem<Sprite>> list = Portrait.ListPlayerPortraits(chara.bio.gender, chara != ELayer.pc);
            list.Sort((ModItem<Sprite> a, ModItem<Sprite> b) => Lang.comparer.Compare(a.id, b.id));
            sliderPortrait.SetList(list.Find((ModItem<Sprite> a) => a.id == chara.c_idPortrait), list, delegate(int a, ModItem<Sprite> b)
            {
                chara.c_idPortrait = b.id;
                portrait.SetChara(chara, uiPCC.actor.data);
            }, (ModItem<Sprite> a) => (!a.id.IsEmpty()) ? a.id : "None");
        }
    }
References Lang.comparer, ModItem< T >.id, Portrait.ListPlayerPortraits(), and ELayer.pc.
Referenced by Activate().
Update()
void LayerEditPCC.Update () inline private
Definition at line 133 of file LayerEditPCC.cs.
    {
        Color hairColor = uiPCC.actor.data.GetHairColor();
        if (hairColor != lastHair)
        {
            portrait.SetChara(chara, uiPCC.actor.data);
            lastHair = hairColor;
        }
        int wheel = EInput.wheel;
        if (InputModuleEX.IsPointerOver(windows[1].transform))
        {
            if (wheel < 0)
            {
                uiPCC.actor.provider.NextDir();
            }
            if (wheel > 0)
            {
                uiPCC.actor.provider.PrevDir();
            }
        }
    }
References Color, InputModuleEX.IsPointerOver(), and EInput.wheel.
Member Data Documentation
applied
bool LayerEditPCC.applied
Definition at line 21 of file LayerEditPCC.cs.
Referenced by Apply().
backup
PCCData LayerEditPCC.backup
Definition at line 17 of file LayerEditPCC.cs.
Referenced by Activate().
backupPortrait
string LayerEditPCC.backupPortrait
Definition at line 19 of file LayerEditPCC.cs.
Referenced by Activate().
chara
Chara LayerEditPCC.chara
Definition at line 13 of file LayerEditPCC.cs.
Referenced by Activate(), Apply(), and OnClickChangePortrait().
lastHair
Color LayerEditPCC.lastHair private
Definition at line 23 of file LayerEditPCC.cs.
mode
UIPCC.Mode LayerEditPCC.mode
Definition at line 7 of file LayerEditPCC.cs.
Referenced by Activate().
portrait
Portrait LayerEditPCC.portrait
Definition at line 11 of file LayerEditPCC.cs.
Referenced by Activate(), and OnClickChangePortrait().
sliderPortrait
UISlider LayerEditPCC.sliderPortrait
Definition at line 15 of file LayerEditPCC.cs.
uiPCC
UIPCC LayerEditPCC.uiPCC
Definition at line 9 of file LayerEditPCC.cs.
Referenced by Activate(), Apply(), and OnClickChangePortrait().
Property Documentation
IsMale
bool LayerEditPCC.IsMale get
Definition at line 37 of file LayerEditPCC.cs.
Referenced by Activate(), and Apply().
UniformMode
bool LayerEditPCC.UniformMode get
Definition at line 25 of file LayerEditPCC.cs.
    {
        get
        {
            if (mode != UIPCC.Mode.UniformM)
            {
                return mode == UIPCC.Mode.UniformF;
            }
            return true;
        }
    }
Referenced by Activate().
The documentation for this class was generated from the following file:
Elin/LayerEditPCC.cs