Elin Decompiled Documentation: UIFactionInfo Class Reference
UIFactionInfo Class Reference
Public Member Functions
void SetFaction (Faction f)
void SetReligion (Religion f)
void SetZone (Zone _zone)
void Clear ()
Public Attributes
UINote note
Image imageFull
Anime imageIn
Anime imageOut
Tween tween
Transform transImage
Transform pivot
UIButton buttonBuy
UIButton buttonVisit
UIButton buttonExplore
int gx
int gy
Zone zone
LayoutGroup layoutButtons
Properties
EloMap elomap [get]
EloMapActor actor [get]
Properties inherited from EMono
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SoundManager Sound [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static CoreDebug debug [get]
Private Member Functions
void Awake ()
Additional Inherited Members
Static Public Member Functions inherited from EMono
static int rnd (int a)
Static Public Attributes inherited from EMono
static Core core
Detailed Description
Definition at line 7 of file UIFactionInfo.cs.
Member Function Documentation
Awake()
void UIFactionInfo.Awake () inline private
Definition at line 25 of file UIFactionInfo.cs.
    {
        if (this.imageFull)
        {
            this.imageFull.SetAlpha(0f);
        }
    }
References imageFull.
Clear()
void UIFactionInfo.Clear () inline
Definition at line 153 of file UIFactionInfo.cs.
    {
        this.note.Clear();
        this.note.Build();
    }
References note.
Referenced by ContentFaction.RefreshZones().
SetFaction()
void UIFactionInfo.SetFaction (Faction f) inline
Definition at line 33 of file UIFactionInfo.cs.
    {
        this.note.Clear();
        this.note.AddHeader("HeaderNoteFaction", f.Name, null);
        this.note.AddTopic("relation", f.relation.GetTextRelation() ?? "");
        this.note.AddTopic("type", f.TextType ?? "");
        this.note.Build();
        if (!this.imageFull)
        {
            return;
        }
        this.transImage.SetPositionX(this.pivot.position.x);
        Sprite sprite = Resources.Load<Sprite>("Media/Graphics/Image/Faction/" + f.source.id + "_avatar");
        TweenUtil.KillTween(ref this.tween, false);
        if (sprite)
        {
            if (sprite != this.imageFull.sprite)
            {
                this.imageFull.SetAlpha(0f);
            }
            this.imageFull.sprite = sprite;
            this.imageFull.SetNativeSize();
            this.tween = this.imageIn.Play(this.imageFull.transform, null, -1f, 0f);
            return;
        }
        this.tween = this.imageOut.Play(this.imageFull.transform, null, -1f, 0f);
    }
References FactionRelation.GetTextRelation(), imageFull, imageIn, imageOut, Faction.Name, note, pivot, Faction.relation, Faction.TextType, transImage, and tween.
Referenced by LayerFactions.RefreshFactions(), and ContentFaction.RefreshFactions().
SetReligion()
void UIFactionInfo.SetReligion (Religion f) inline
Definition at line 61 of file UIFactionInfo.cs.
    {
        this.note.Clear();
        UIItem c = this.note.AddHeader("HeaderFaction", "", f.GetSprite());
        c.Find("Name", true).SetText(f.Name);
        c.Find("Topic1", true).SetTopic("relationGod", f.relation.ToString() ?? "");
        c.Find("Topic2", true).SetTopic("type", f.source.GetText("textType", false) ?? "");
        c.Find("Topic3", true).SetTopic("avatar", f.source.textAvatar ?? "");
        string lang = "GSSleep";
        if (f.id == "harmony")
        {
            lang = "GSWithdraw";
        }
        if (f.id == "oblivion")
        {
            lang = "GSStray";
        }
        c.Find("Topic4", true).SetTopic("status", lang);
        this.note.AddText(f.source.GetDetail(), FontColor.DontChange).Hyphenate();
        this.note.Build();
        if (!this.imageFull)
        {
            return;
        }
        this.transImage.SetPositionX(this.pivot.position.x);
        Sprite sprite = Resources.Load<Sprite>("Media/Graphics/Image/Faction/" + f.source.id + "_avatar");
        TweenUtil.KillTween(ref this.tween, false);
        if (sprite)
        {
            if (sprite != this.imageFull.sprite)
            {
                this.imageFull.SetAlpha(0f);
            }
            this.imageFull.sprite = sprite;
            this.imageFull.SetNativeSize();
            this.tween = this.imageIn.Play(this.imageFull.transform, null, -1f, 0f);
            return;
        }
        this.tween = this.imageOut.Play(this.imageFull.transform, null, -1f, 0f);
    }
References Religion.GetSprite(), Religion.id, imageFull, imageIn, imageOut, Religion.Name, note, pivot, Religion.relation, Religion.source, transImage, and tween.
Referenced by ContentFaction.RefreshFactions().
SetZone()
void UIFactionInfo.SetZone (Zone _zone) inline
Definition at line 102 of file UIFactionInfo.cs.
    {
        this.zone = _zone;
        FactionBranch branch = this.zone.branch;
        this.gx = this.zone.x;
        this.gy = this.zone.y;
        this.note.Clear();
        this.note.AddHeader("HeaderNoteFaction", this.zone.Name, null);
        this.note.AddTopic("mainFaction", this.zone.mainFaction.Name ?? "");
        this.note.AddTopic("branchLv", branch.TextLv);
        this.note.AddTopic("wealth", branch.resources.worth.value.ToFormat() ?? "");
        this.note.AddTopic("ranking", EMono.game.spatials.ranks.GetRankText(this.zone) ?? "");
        this.note.AddTopic("rank_income", "rank_income2".lang(EMono.game.spatials.ranks.GetIncome(this.zone).ToFormat(), null, null, null, null));
        this.note.Space(0, 1);
        this.note.AddHeaderTopic("landfeat".lang(), null);
        List<Element> list = _zone.ListLandFeats();
        for (int i = 0; i < list.Count; i++)
        {
            this.note.AddText(list[i].Name + (((i == 1 && branch.lv < 4) || (i == 2 && branch.lv < 7)) ? "landfeat_locked".lang() : ""), FontColor.DontChange);
        }
        this.note.Space(0, 1);
        this.note.AddHeaderTopic("listRoamers".lang(), null);
        int num = 0;
        foreach (Chara chara in EMono.game.cards.globalCharas.Values)
        {
            if (chara.homeBranch == branch)
            {
                this.note.AddText(chara.Name, FontColor.DontChange);
                num++;
                if (num > 5)
                {
                    break;
                }
            }
        }
        if (num == 0)
        {
            this.note.AddText("????????", FontColor.DontChange);
        }
        this.note.Space(0, 1);
        this.note.AddHeaderTopic("listPolicies".lang(), null);
        foreach (Element element in branch.elements.dict.Values)
        {
            if (element.source.category == "policy")
            {
                this.note.AddText(element.Name, FontColor.DontChange);
            }
        }
        this.note.Build();
    }
References EMono._zone, Zone.branch, Game.cards, EMono.game, RankedZoneManager.GetIncome(), RankedZoneManager.GetRankText(), CardManager.globalCharas, Chara.homeBranch, Zone.ListLandFeats(), FactionBranch.lv, Spatial.mainFaction, Card.Name, Element.Name, Faction.Name, Spatial.Name, note, SpatialManager.ranks, FactionBranch.resources, Element.source, Game.spatials, FactionBranch.TextLv, BaseHomeResource.value, HomeResourceManager.worth, Spatial.x, Spatial.y, and zone.
Referenced by ContentFaction.RefreshZones(), and LayerFactions.RefreshZones().
Member Data Documentation
buttonBuy
UIButton UIFactionInfo.buttonBuy
Definition at line 173 of file UIFactionInfo.cs.
buttonExplore
UIButton UIFactionInfo.buttonExplore
Definition at line 177 of file UIFactionInfo.cs.
buttonVisit
UIButton UIFactionInfo.buttonVisit
Definition at line 175 of file UIFactionInfo.cs.
gx
int UIFactionInfo.gx
Definition at line 179 of file UIFactionInfo.cs.
gy
int UIFactionInfo.gy
Definition at line 181 of file UIFactionInfo.cs.
imageFull
Image UIFactionInfo.imageFull
Definition at line 161 of file UIFactionInfo.cs.
Referenced by Awake(), SetFaction(), and SetReligion().
imageIn
Anime UIFactionInfo.imageIn
Definition at line 163 of file UIFactionInfo.cs.
Referenced by SetFaction(), and SetReligion().
imageOut
Anime UIFactionInfo.imageOut
Definition at line 165 of file UIFactionInfo.cs.
Referenced by SetFaction(), and SetReligion().
layoutButtons
LayoutGroup UIFactionInfo.layoutButtons
Definition at line 185 of file UIFactionInfo.cs.
note
UINote UIFactionInfo.note
Definition at line 159 of file UIFactionInfo.cs.
Referenced by Clear(), SetFaction(), SetReligion(), and SetZone().
pivot
Transform UIFactionInfo.pivot
Definition at line 171 of file UIFactionInfo.cs.
Referenced by SetFaction(), and SetReligion().
transImage
Transform UIFactionInfo.transImage
Definition at line 169 of file UIFactionInfo.cs.
Referenced by SetFaction(), and SetReligion().
tween
Tween UIFactionInfo.tween
Definition at line 167 of file UIFactionInfo.cs.
Referenced by SetFaction(), and SetReligion().
zone
Zone UIFactionInfo.zone
Definition at line 183 of file UIFactionInfo.cs.
Referenced by SetZone().
Property Documentation
actor
EloMapActor UIFactionInfo.actor get
Definition at line 17 of file UIFactionInfo.cs.
    {
        get
        {
            return EMono.scene.elomapActor;
        }
    }
elomap
EloMap UIFactionInfo.elomap get
Definition at line 9 of file UIFactionInfo.cs.
    {
        get
        {
            return EMono.scene.elomapActor.elomap;
        }
    }
The documentation for this class was generated from the following file:
Elin/UIFactionInfo.cs