Elin Decompiled Documentation: UIBook Class Reference
UIBook Class Reference
Classes
class Item
class Page
Public Types
enum Mode {
Help , Announce , Book , Parchment ,
Gallery , About
}
Public Member Functions
void Search (string s)
void ClearSearch ()
void ModPage (int a)
void Show (string _idFile=null, string _idTopic=null, string title=null, BookList.Item _bookItem=null)
void Show ()
void BuildPages ()
void AddPage (Page page)
void RefreshTopics ()
void AddButtonClose ()
UIButton AddButton (string lang, Action action)
Public Attributes
Mode mode
int currentPage
List< Page > pages = new List<Page>()
UINote note
UINote note2
UINote noteSearch
UIList list
UIDynamicList listSearchResult
UIText textTitle
UIText textPage
UIText textPage2
string idFile
string idTopic
string idFirstFile
string idFirstTopic
SkinRootStatic skin
LayoutGroup layoutButton
UIButton moldButton
BookList.Item bookItem
Scrollbar scrollbar
Window window
UIButton buttonPrev
UIButton buttonNext
InputField inputSearch
UIButton buttonClear
UIScrollView scrollView
Transform transSearchResult
string lastSearch
bool showSearchResult
float searchResultHeight
float marginSearchResult
Color colorSearchHit
Static Public Attributes
static string str_pc
static string searchWord
static Dictionary< string, string > helpTitles = new Dictionary<string, string>()
static SearchContext searchContext
Private Member Functions
void Awake ()
void Update ()
Detailed Description
Definition at line 8 of file UIBook.cs.
Member Enumeration Documentation
Mode
enum UIBook.Mode
Enumerator
Announce
Book
Parchment
Gallery
About
Definition at line 10 of file UIBook.cs.
    {
        Help,
        Announce,
        Book,
        Parchment,
        Gallery,
        About
    }
Member Function Documentation
AddButton()
UIButton UIBook.AddButton (string lang, Action action) inline
Definition at line 621 of file UIBook.cs.
            {
                item2 = item3;
                idFirstFile = null;
            }
        }
        list.Refresh();
        if (item2 != null)
AddButtonClose()
void UIBook.AddButtonClose () inline
Definition at line 613 of file UIBook.cs.
            {
                item.items.Add(item3);
            }
            else
Referenced by UIBook.Page.BuildNote().
AddPage()
void UIBook.AddPage (Page page) inline
Definition at line 538 of file UIBook.cs.
    {
        page.idx = pages.Count;
        pages.Add(page);
        page.book = this;
    }
References pages.
Referenced by BuildPages(), and ContentGallery.Refresh().
Awake()
void UIBook.Awake () inline private
Definition at line 332 of file UIBook.cs.
    {
        if (searchContext == null || Application.isEditor)
        {
            searchContext = new SearchContext();
            searchContext.Init();
        }
        if ((bool)inputSearch)
        {
            inputSearch.onValueChanged.AddListener(Search);
            inputSearch.onSubmit.AddListener(Search);
            lastSearch = null;
        }
    }
References SearchContext.Init(), inputSearch, lastSearch, Search, and searchContext.
BuildPages()
void UIBook.BuildPages () inline
Definition at line 493 of file UIBook.cs.
    {
        pages.Clear();
        string[] array = IO.LoadTextArray(CorePath.CorePackage.Help + idFile);
        if (idFile == "version" && Lang.langCode == "CN")
        {
            array = IO.LoadTextArray(CorePath.CorePackage.TextEN + idFile);
        }
        if (array.IsEmpty())
        {
            array = IO.LoadTextArray(CorePath.CorePackage.Text + idFile);
        }
        if (array.IsEmpty())
        {
            array = IO.LoadTextArray(CorePath.CorePackage.TextCommon + idFile);
        }
        if (array.IsEmpty())
        {
            array = IO.LoadTextArray(CorePath.CorePackage.HelpEN + idFile);
        }
        if (array.IsEmpty())
        {
            array = IO.LoadTextArray(CorePath.CorePackage.TextEN + idFile);
        }
        Page page = new Page();
        int num = 0;
        string[] array2 = array;
        foreach (string text in array2)
        {
            if (bookItem != null && num == 0)
            {
                num++;
                continue;
            }
            if (text == "{p}")
            {
                AddPage(page);
                page = new Page();
            }
            page.lines.Add(text);
            num++;
        }
        AddPage(page);
    }
References AddPage(), bookItem, CorePath.CorePackage.Help, CorePath.CorePackage.HelpEN, idFile, Lang.langCode, pages, CorePath.CorePackage.Text, CorePath.CorePackage.TextCommon, and CorePath.CorePackage.TextEN.
Referenced by RefreshTopics(), and Show().
ClearSearch()
void UIBook.ClearSearch () inline
Definition at line 432 of file UIBook.cs.
    {
        inputSearch.text = "";
        lastSearch = null;
    }
References lastSearch.
ModPage()
void UIBook.ModPage (int a) inline
Definition at line 438 of file UIBook.cs.
    {
        SE.Play("read_paper");
        if ((bool)note2)
        {
            a *= 2;
        }
        currentPage += a;
        if (currentPage < 0)
        {
            currentPage = 0;
        }
        if (currentPage >= pages.Count)
        {
            currentPage = pages.Count - ((!note2) ? 1 : 2);
        }
        ShowPage(currentPage);
    }
References currentPage, note2, and pages.
RefreshTopics()
void UIBook.RefreshTopics () inline
Definition at line 545 of file UIBook.cs.
    {
        string[] array = IO.LoadTextArray(CorePath.CorePackage.Help + "_topics.txt");
        List<UIList> lists = new List<UIList>();
        lists.Add(list);
        list.Clear();
        list.callbacks = new UIList.Callback<Item, ButtonCategory>
        {
            onClick = delegate(Item a, ButtonCategory b)
            {
                if (a.items.Count > 0)
                {
                    b.buttonFold.onClick.Invoke();
                }
                else
                {
                    idFile = a.idFile;
                    idTopic = a.id;
                    textTitle.SetText(a.title);
                    BuildPages();
                    ShowPage();
                }
            },
            onInstantiate = delegate(Item a, ButtonCategory b)
            {
                b.mainText.text = a.title;
                bool flag = false;
                if (a.items.Count > 0)
                {
                    foreach (Item item4 in a.items)
                    {
                        if (item4.idFile == idFile && item4.id == idTopic)
{
                            flag = true;
                        }
                    }
                }
                b.SetFold(a.items.Count > 0, !flag, delegate(UIList l)
                {
                    lists.Add(l);
                    foreach (Item item5 in a.items)
                    {
                        l.Add(item5);
                    }
                });
            },
            onRefresh = null
        };
        string oldValue = '\t'.ToString();
        Item item = null;
        Item item2 = null;
        helpTitles.Clear();
        string[] array2 = array;
        for (int i = 0; i < array2.Length; i++)
        {
            string[] array3 = array2[i].Replace(oldValue, "").Split(',');
            string[] array4 = array3[0].Split('-');
            Item item3 = new Item
            {
                idFile = array4[0],
                id = array4[1],
                title = array3[1]
            };
            helpTitles[array3[0]] = item3.title.Replace("$", "");
            if (item3.title.StartsWith("$"))
            {
                item = item3;
References BuildPages(), ButtonCategory.buttonFold, UIList.Clear(), CorePath.CorePackage.Help, helpTitles, UIBook.Item.id, UIBook.Item.idFile, idFile, idTopic, item, UIBook.Item.items, list, ButtonCategory.SetFold(), UIText.SetText(), textTitle, UIBook.Item.title, and title.
Referenced by Show().
Search()
void UIBook.Search (string s) inline
Definition at line 369 of file UIBook.cs.
    {
        if (s == lastSearch)
        {
            return;
        }
        lastSearch = s;
        if (s.IsEmpty())
        {
            return;
        }
        transSearchResult.SetActive(enable: true);
        listSearchResult.Clear();
        listSearchResult.callbacks = new UIList.Callback<SearchContext.Item, UIButton>
        {
            onClick = delegate(SearchContext.Item a, UIButton b)
            {
                if (!a.system)
                {
                    SE.Play("click_recipe");
                    searchWord = s;
                    Show(a.idFile, a.idTopic);
                }
            },
            onRedraw = delegate(SearchContext.Item a, UIButton b, int i)
            {
                if (a.system)
                {
                    b.mainText.text = "";
                    b.subText.text = a.text;
                }
                else
                {
                    string text = helpTitles.TryGetValue(a.idFile + "-") ?? "";
                    string text2 = helpTitles.TryGetValue(a.idFile + "-" + a.idTopic) ?? a.idTopic;
                    b.mainText.text = (text.IsEmpty() ? "" : (text + " - ")) + text2;
                    string text3 = a.text;
                    if (!text3.Contains("</color>"))
                    {
                        int num = a.textSearch.IndexOf(s.ToLower());
                        if (num != -1)
{
                            text3 = text3.Substring(0, num) + text3.Substring(num, s.Length).TagColor(colorSearchHit) + text3.Substring(num + s.Length);
                        }
                    }
                    b.subText.text = text3;
                }
            },
            onList = delegate
            {
                foreach (SearchContext.Item item in searchContext.Search(s))
                {
                    listSearchResult.Add(item);
                }
            },
            onRefresh = null
        };
        listSearchResult.List();
        scrollView.content.RebuildLayout(recursive: true);
        RectTransform rectTransform = transSearchResult.Rect();
        rectTransform.sizeDelta = new Vector2(rectTransform.sizeDelta.x, Mathf.Min(searchResultHeight, scrollView.content.sizeDelta.y + marginSearchResult));
    }
References UIDynamicList.Add(), UIDynamicList.Clear(), colorSearchHit, helpTitles, item, lastSearch, UIDynamicList.List(), listSearchResult, marginSearchResult, scrollView, SearchContext.Search(), searchContext, searchResultHeight, searchWord, Show(), and transSearchResult.
Show() [1/2]
void UIBook.Show () inline
Definition at line 470 of file UIBook.cs.
    {
        note.Clear();
        if ((bool)note2)
        {
            note2.Clear();
        }
        if ((bool)layoutButton)
        {
            moldButton = layoutButton.CreateMold<UIButton>();
        }
        if (mode == Mode.Help)
        {
            idFirstFile = idFile;
            idFirstTopic = idTopic;
            RefreshTopics();
        }
        else
        {
            ShowPage(currentPage);
        }
    }
References UINote.Clear(), currentPage, idFile, idFirstFile, idFirstTopic, idTopic, layoutButton, mode, moldButton, note, note2, and RefreshTopics().
Referenced by Search(), and Show().
Show() [2/2]
void UIBook.Show (string _idFile = null, string _idTopic = null, string title = null, BookList::Item _bookItem = null) inline
Definition at line 457 of file UIBook.cs.
    {
        if (!title.IsEmpty() && (bool)window)
        {
            window.textCaption.SetText(title);
        }
        idFile = _idFile;
        idTopic = _idTopic;
        bookItem = _bookItem;
        BuildPages();
        Show();
    }
References bookItem, BuildPages(), idFile, idTopic, UIText.SetText(), Show(), Window.textCaption, title, and window.
Referenced by LayerHelp.OnAfterInit(), ContentGallery.Refresh(), and LayerHelp.Toggle().
Update()
void UIBook.Update () inline private
Definition at line 347 of file UIBook.cs.
    {
        if ((bool)inputSearch)
        {
            if (inputSearch.isFocused)
            {
                showSearchResult = true;
            }
            else if (Input.GetMouseButtonDown(0) && !InputModuleEX.IsPointerOver(scrollView) && !InputModuleEX.IsPointerOver(inputSearch))
            {
                showSearchResult = false;
            }
            buttonClear.SetActive(inputSearch.text != "");
            transSearchResult.SetActive((inputSearch.isFocused || showSearchResult) && inputSearch.text != "");
            if (Input.GetKeyDown(KeyCode.Escape) && inputSearch.text == "")
            {
                window.layer.Close();
                EInput.Consume(consumeAxis: false, 5);
            }
        }
    }
References buttonClear, Layer.Close(), EInput.Consume(), inputSearch, InputModuleEX.IsPointerOver(), Window.layer, scrollView, showSearchResult, transSearchResult, and window.
Member Data Documentation
bookItem
BookList.Item UIBook.bookItem
Definition at line 302 of file UIBook.cs.
Referenced by BuildPages(), and Show().
buttonClear
UIButton UIBook.buttonClear
Definition at line 314 of file UIBook.cs.
Referenced by Update().
buttonNext
UIButton UIBook.buttonNext
Definition at line 310 of file UIBook.cs.
buttonPrev
UIButton UIBook.buttonPrev
Definition at line 308 of file UIBook.cs.
colorSearchHit
Color UIBook.colorSearchHit
Definition at line 328 of file UIBook.cs.
Referenced by UIBook.Page.BuildNote(), and Search().
currentPage
int UIBook.currentPage
Definition at line 264 of file UIBook.cs.
Referenced by ModPage(), ContentGallery.OnDestroy(), Show(), and ContentGallery.ToggleMode().
helpTitles
Dictionary<string, string> UIBook.helpTitles = new Dictionary<string, string>() static
Definition at line 259 of file UIBook.cs.
Referenced by RefreshTopics(), and Search().
idFile
string UIBook.idFile
Definition at line 285 of file UIBook.cs.
Referenced by BuildPages(), LayerHelp.OnDestroy(), RefreshTopics(), and Show().
idFirstFile
string UIBook.idFirstFile
Definition at line 291 of file UIBook.cs.
Referenced by Show().
idFirstTopic
string UIBook.idFirstTopic
Definition at line 294 of file UIBook.cs.
Referenced by Show().
idTopic
string UIBook.idTopic
Definition at line 288 of file UIBook.cs.
Referenced by UIBook.Page.BuildNote(), LayerHelp.OnDestroy(), RefreshTopics(), and Show().
inputSearch
InputField UIBook.inputSearch
Definition at line 312 of file UIBook.cs.
Referenced by Awake(), LayerHelp.OnRightClick(), and Update().
lastSearch
string UIBook.lastSearch
Definition at line 320 of file UIBook.cs.
Referenced by Awake(), ClearSearch(), and Search().
layoutButton
LayoutGroup UIBook.layoutButton
Definition at line 298 of file UIBook.cs.
Referenced by Show().
list
UIList UIBook.list
Definition at line 274 of file UIBook.cs.
Referenced by RefreshTopics().
listSearchResult
UIDynamicList UIBook.listSearchResult
Definition at line 276 of file UIBook.cs.
Referenced by Search().
marginSearchResult
float UIBook.marginSearchResult
Definition at line 326 of file UIBook.cs.
Referenced by Search().
mode
Mode UIBook.mode
Definition at line 261 of file UIBook.cs.
Referenced by UIBook.Page.BuildNote(), LayerHelp.OnAfterInit(), LayerHelp.OnDestroy(), LayerHelp.OnInit(), and Show().
moldButton
UIButton UIBook.moldButton
Definition at line 300 of file UIBook.cs.
Referenced by Show().
note
UINote UIBook.note
Definition at line 268 of file UIBook.cs.
Referenced by Show().
note2
UINote UIBook.note2
Definition at line 270 of file UIBook.cs.
Referenced by ModPage(), and Show().
noteSearch
UINote UIBook.noteSearch
Definition at line 272 of file UIBook.cs.
pages
List<Page> UIBook.pages = new List<Page>()
Definition at line 266 of file UIBook.cs.
Referenced by AddPage(), BuildPages(), ModPage(), and ContentGallery.Refresh().
scrollbar
Scrollbar UIBook.scrollbar
Definition at line 304 of file UIBook.cs.
scrollView
UIScrollView UIBook.scrollView
Definition at line 316 of file UIBook.cs.
Referenced by Search(), and Update().
searchContext
SearchContext UIBook.searchContext static
Definition at line 330 of file UIBook.cs.
Referenced by Awake(), and Search().
searchResultHeight
float UIBook.searchResultHeight
Definition at line 324 of file UIBook.cs.
Referenced by Search().
searchWord
string UIBook.searchWord static
Definition at line 257 of file UIBook.cs.
Referenced by UIBook.Page.BuildNote(), and Search().
showSearchResult
bool UIBook.showSearchResult
Definition at line 322 of file UIBook.cs.
Referenced by Update().
skin
SkinRootStatic UIBook.skin
Definition at line 296 of file UIBook.cs.
str_pc
string UIBook.str_pc static
Definition at line 255 of file UIBook.cs.
Referenced by UIBook.Page.BuildNote().
textPage
UIText UIBook.textPage
Definition at line 280 of file UIBook.cs.
textPage2
UIText UIBook.textPage2
Definition at line 282 of file UIBook.cs.
textTitle
UIText UIBook.textTitle
Definition at line 278 of file UIBook.cs.
Referenced by RefreshTopics().
transSearchResult
Transform UIBook.transSearchResult
Definition at line 318 of file UIBook.cs.
Referenced by LayerHelp.OnRightClick(), Search(), and Update().
window
Window UIBook.window
Definition at line 306 of file UIBook.cs.
Referenced by Show(), and Update().
The documentation for this class was generated from the following file:
Elin/Plugins.UI/UIBook.cs