Elin Decompiled Documentation: B83.Win32.WinAPI Class Reference
B83.Win32.WinAPI Class Reference
Public Member Functions
static IntPtr GetModuleHandle (string lpModuleName)
static uint GetCurrentThreadId ()
static IntPtr SetWindowsHookEx (HookType hookType, HookProc lpfn, IntPtr hMod, uint dwThreadId)
static bool UnhookWindowsHookEx (IntPtr hhk)
static IntPtr CallNextHookEx (IntPtr hhk, int nCode, IntPtr wParam, ref MSG lParam)
static void DragAcceptFiles (IntPtr hwnd, bool fAccept)
static uint DragQueryFile (IntPtr hDrop, uint iFile, StringBuilder lpszFile, uint cch)
static void DragFinish (IntPtr hDrop)
static void DragQueryPoint (IntPtr hDrop, out POINT pos)
Detailed Description
Definition at line 7 of file WinAPI.cs.
Member Function Documentation
CallNextHookEx()
static IntPtr B83.Win32.WinAPI.CallNextHookEx (IntPtr hhk, int nCode, IntPtr wParam, ref MSG lParam)
Referenced by B83.Win32.UnityDragAndDropHook.Callback().
DragAcceptFiles()
static void B83.Win32.WinAPI.DragAcceptFiles (IntPtr hwnd, bool fAccept)
Referenced by B83.Win32.UnityDragAndDropHook.InstallHook(), and B83.Win32.UnityDragAndDropHook.UninstallHook().
DragFinish()
static void B83.Win32.WinAPI.DragFinish (IntPtr hDrop)
Referenced by B83.Win32.UnityDragAndDropHook.Callback().
DragQueryFile()
static uint B83.Win32.WinAPI.DragQueryFile (IntPtr hDrop, uint iFile, StringBuilder lpszFile, uint cch)
Referenced by B83.Win32.UnityDragAndDropHook.Callback().
DragQueryPoint()
static void B83.Win32.WinAPI.DragQueryPoint (IntPtr hDrop, out POINT pos)
Referenced by B83.Win32.UnityDragAndDropHook.Callback().
GetCurrentThreadId()
static uint B83.Win32.WinAPI.GetCurrentThreadId ()
Referenced by B83.Win32.UnityDragAndDropHook.InstallHook().
GetModuleHandle()
static IntPtr B83.Win32.WinAPI.GetModuleHandle (string lpModuleName)
Referenced by B83.Win32.UnityDragAndDropHook.InstallHook().
SetWindowsHookEx()
static IntPtr B83.Win32.WinAPI.SetWindowsHookEx (HookType hookType, HookProc lpfn, IntPtr hMod, uint dwThreadId)
Referenced by B83.Win32.UnityDragAndDropHook.InstallHook().
UnhookWindowsHookEx()
static bool B83.Win32.WinAPI.UnhookWindowsHookEx (IntPtr hhk)
Referenced by B83.Win32.UnityDragAndDropHook.UninstallHook().
The documentation for this class was generated from the following file:
Elin/Plugins.basecore/B83/Win32/WinAPI.cs