Elin Decompiled Documentation: ZoneEvent Class Reference
ZoneEvent Class Reference
Public Member Functions
virtual string GetText ()
void Tick (float delta)
void Init ()
void OnSimulateHour ()
virtual void OnVisit ()
virtual void OnInit ()
virtual void OnFirstTick ()
virtual void OnTick ()
virtual void OnTickRound ()
virtual void OnKill ()
virtual void OnCharaDie (Chara c)
virtual void OnLeaveZone ()
virtual void OnLoad ()
void Kill ()
Public Attributes
float time
int rounds
int hoursElapsed
int minElapsed
Zone zone
bool firstTick = true
Properties
SourceQuest.Row source [get]
virtual string id [get]
virtual string TextWidgetDate [get]
virtual float roundInterval [get]
virtual Playlist playlist [get]
virtual bool debugSkip [get]
virtual string RefStr2 [get]
virtual string RefStr3 [get]
virtual int hoursToKill [get]
virtual bool HasReport [get]
string Name [get]
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Additional Inherited Members
Static Public Member Functions inherited from EClass
static int rndSeed (int a, int seed)
static int rnd (long a)
static int rnd (int a)
static int curve (int a, int start, int step, int rate=75)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Static Public Attributes inherited from EClass
static Core core
Detailed Description
Definition at line 3 of file ZoneEvent.cs.
Member Function Documentation
GetText()
virtual string ZoneEvent.GetText () inline virtual
Definition at line 43 of file ZoneEvent.cs.
    {
        return Lang.ParseRaw(source.GetDetail().Split('|')[1], "", RefStr2, RefStr3);
    }
References Lang.ParseRaw(), RefStr2, RefStr3, and source.
Init()
void ZoneEvent.Init () inline
Definition at line 64 of file ZoneEvent.cs.
    {
        OnInit();
    }
References OnInit().
Referenced by ZoneEventManager.Add().
Kill()
void ZoneEvent.Kill () inline
Definition at line 114 of file ZoneEvent.cs.
    {
        if (zone == null)
        {
            zone = EClass._zone;
        }
        zone.events.list.Remove(this);
        OnKill();
    }
References EClass._zone, Zone.events, ZoneEventManager.list, OnKill(), and zone.
Referenced by ZoneEventSiege.OnCharaDie(), OnSimulateHour(), ZoneEventBeggerChest.OnTickRound(), ZoneEventPhone.OnTickRound(), ZoneEventSiege.OnTickRound(), and TraitPhone.OnUse().
OnCharaDie()
virtual void ZoneEvent.OnCharaDie (Chara c) inline virtual
Reimplemented in ZoneEventDefenseGame, ZoneEventSiege, and ZoneEventSubdue.
Definition at line 102 of file ZoneEvent.cs.
    {
    }
Referenced by ZoneEventManager.OnCharaDie().
OnFirstTick()
virtual void ZoneEvent.OnFirstTick () inline virtual
Definition at line 86 of file ZoneEvent.cs.
    {
    }
Referenced by Tick().
OnInit()
virtual void ZoneEvent.OnInit () inline virtual
Reimplemented in ZoneEventPhone, ZoneEventRaid, and ZoneEventSiege.
Definition at line 82 of file ZoneEvent.cs.
    {
    }
Referenced by Init().
OnKill()
virtual void ZoneEvent.OnKill () inline virtual
Reimplemented in ZoneEventPhone, ZoneEventRaid, and ZoneEventSiege.
Definition at line 98 of file ZoneEvent.cs.
    {
    }
Referenced by Kill().
OnLeaveZone()
virtual void ZoneEvent.OnLeaveZone () inline virtual
Reimplemented in ZoneEventHarvest.
Definition at line 106 of file ZoneEvent.cs.
    {
    }
OnLoad()
virtual void ZoneEvent.OnLoad () inline virtual
Definition at line 110 of file ZoneEvent.cs.
    {
    }
OnSimulateHour()
void ZoneEvent.OnSimulateHour () inline
Definition at line 69 of file ZoneEvent.cs.
    {
        hoursElapsed++;
        if (hoursToKill != 0 && hoursElapsed >= hoursToKill)
        {
            Kill();
        }
    }
References hoursElapsed, hoursToKill, and Kill().
OnTick()
virtual void ZoneEvent.OnTick () inline virtual
Definition at line 90 of file ZoneEvent.cs.
    {
    }
Referenced by Tick().
OnTickRound()
virtual void ZoneEvent.OnTickRound () inline virtual
Reimplemented in ZoneEventBeggerChest, ZoneEventPhone, ZoneEventQuest, ZoneEventSiege, and ZoneEventSurvival.
Definition at line 94 of file ZoneEvent.cs.
    {
    }
Referenced by Tick().
OnVisit()
virtual void ZoneEvent.OnVisit () inline virtual
Reimplemented in ZoneEventDefenseGame, ZoneEventHarvest, ZoneEventMusic, ZoneEventSiege, and ZoneEventSubdue.
Definition at line 78 of file ZoneEvent.cs.
    {
    }
Tick()
void ZoneEvent.Tick (float delta) inline
Definition at line 48 of file ZoneEvent.cs.
    {
        if (firstTick)
        {
            firstTick = false;
            OnFirstTick();
        }
        OnTick();
        time += delta;
        if (time > roundInterval * (float)rounds)
        {
            rounds++;
            OnTickRound();
        }
    }
References firstTick, OnFirstTick(), OnTick(), OnTickRound(), roundInterval, rounds, and time.
Referenced by ZoneEventManager.Tick().
Member Data Documentation
firstTick
bool ZoneEvent.firstTick = true
Definition at line 19 of file ZoneEvent.cs.
Referenced by Tick().
hoursElapsed
int ZoneEvent.hoursElapsed
Definition at line 12 of file ZoneEvent.cs.
Referenced by OnSimulateHour().
minElapsed
int ZoneEvent.minElapsed
Definition at line 15 of file ZoneEvent.cs.
Referenced by ZoneEventQuest.OnTickRound().
rounds
int ZoneEvent.rounds
Definition at line 9 of file ZoneEvent.cs.
Referenced by ZoneEventDefenseGame._OnTickRound(), and Tick().
time
float ZoneEvent.time
Definition at line 6 of file ZoneEvent.cs.
Referenced by Tick().
zone
Zone ZoneEvent.zone
Definition at line 17 of file ZoneEvent.cs.
Referenced by Kill().
Property Documentation
debugSkip
virtual bool ZoneEvent.debugSkip get
Definition at line 31 of file ZoneEvent.cs.
Referenced by ZoneEventManager.Add().
HasReport
virtual bool ZoneEvent.HasReport get
Definition at line 39 of file ZoneEvent.cs.
hoursToKill
virtual int ZoneEvent.hoursToKill get
Definition at line 37 of file ZoneEvent.cs.
Referenced by OnSimulateHour().
id
virtual string ZoneEvent.id get
Definition at line 23 of file ZoneEvent.cs.
Name
string ZoneEvent.Name get
Definition at line 41 of file ZoneEvent.cs.
playlist
virtual Playlist ZoneEvent.playlist get
Definition at line 29 of file ZoneEvent.cs.
RefStr2
virtual string ZoneEvent.RefStr2 get
Definition at line 33 of file ZoneEvent.cs.
Referenced by GetText().
RefStr3
virtual string ZoneEvent.RefStr3 get
Definition at line 35 of file ZoneEvent.cs.
Referenced by GetText().
roundInterval
virtual float ZoneEvent.roundInterval get
Definition at line 27 of file ZoneEvent.cs.
Referenced by Tick().
source
SourceQuest.Row ZoneEvent.source get
Definition at line 21 of file ZoneEvent.cs.
Referenced by GetText().
TextWidgetDate
virtual string ZoneEvent.TextWidgetDate get
Definition at line 25 of file ZoneEvent.cs.
Referenced by WidgetDate._Refresh().
The documentation for this class was generated from the following file:
Elin/ZoneEvent.cs