Elin Decompiled Documentation: GuildFighter Class Reference
GuildFighter Class Reference
Public Member Functions
int ServicePrice (int a)
bool CanGiveContribution (Chara c)
bool ShowBounty (Chara c)
bool HasBounty (Chara c)
Public Member Functions inherited from Guild
void RefreshDevelopment ()
Public Member Functions inherited from Faction
void Init ()
void OnLoad ()
float GetHappiness ()
Sprite GetSprite ()
int CountTax ()
int GetMaxReserve ()
List< FactionBranch > GetChildren ()
int CountWealth ()
int CountTerritories ()
int CountMembers ()
Hostility GetHostility ()
void ModRelation (int a)
bool HasMember (string id, bool includeReserve=true)
bool IsWearingPanty (Chara c)
void AddContribution (int a)
void AddReserve (Chara c)
void RemoveReserve (Chara c)
void OnAdvanceDay ()
void OnAdvanceMonth ()
void TryPayBill (Thing bill)
FactionBranch FindBranch (Chara c)
void AddGlobalPolicy (int id)
bool IsGlobalPolicyActive (int id)
void SetGlobalPolicyActive (int id, bool active)
int GetResidentTax ()
int GetRankIncome ()
int GetFactionSalary ()
int GetTotalTax (bool evasion)
int GetBaseTax (bool evasion)
int GetFameTax (bool evasion)
int EvadeTax (int v, bool evasion)
void SetTaxTooltip (UINote n)
int CountTaxFreeLand ()
Properties
override QuestGuild Quest [get]
override bool IsCurrentZone [get]
Properties inherited from Guild
static Guild Current [get]
static GuildFighter Fighter [get]
static GuildMage Mage [get]
static GuildThief Thief [get]
static GuildMerchant Merchant [get]
static QuestGuild CurrentQuest [get]
override string TextType [get]
virtual QuestGuild Quest [get]
virtual bool IsCurrentZone [get]
bool IsMember [get]
Properties inherited from Faction
string Name [get]
SourceFaction.Row source [get]
virtual string TextType [get]
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Additional Inherited Members
Static Public Member Functions inherited from Guild
static Guild GetCurrentGuild ()
Static Public Member Functions inherited from Faction
static Faction Create (SourceFaction.Row r)
Static Public Member Functions inherited from EClass
static int rnd (int a)
static int curve (int a, int start, int step, int rate=75)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Public Attributes inherited from Faction
FactionRelation relation = new FactionRelation()
string id
string uid
string name
List< HireInfo > listReserve = new List<HireInfo>()
ElementContainerZone elements = new ElementContainerZone()
HashSet< int > globalPolicies = new HashSet<int>()
ElementContainerFaction charaElements = new ElementContainerFaction()
SourceFaction.Row _source
Static Public Attributes inherited from EClass
static Core core
Detailed Description
Definition at line 1 of file GuildFighter.cs.
Member Function Documentation
CanGiveContribution()
bool GuildFighter.CanGiveContribution (Chara c) inline
Definition at line 26 of file GuildFighter.cs.
    {
        if (c.IsUnique || c.rarity < Rarity.Legendary)
        {
            return false;
        }
        if (c.Chara.OriginalHostility != Hostility.Enemy && c.c_bossType != BossType.Evolved)
        {
            return false;
        }
        return true;
    }
References Card.c_bossType, Card.Chara, Card.IsUnique, Chara.OriginalHostility, and Card.rarity.
Referenced by Card.DamageHP(), and HasBounty().
HasBounty()
bool GuildFighter.HasBounty (Chara c) inline
Definition at line 44 of file GuildFighter.cs.
    {
        if (!CanGiveContribution(c))
        {
            return false;
        }
        if (relation.rank < 4)
        {
            return false;
        }
        if (c.uid % 2 != 0)
        {
            return false;
        }
        return true;
    }
References CanGiveContribution(), FactionRelation.rank, Faction.relation, and Card.uid.
Referenced by Card.DamageHP(), and Chara.GetHoverText().
ServicePrice()
int GuildFighter.ServicePrice (int a) inline
Definition at line 17 of file GuildFighter.cs.
    {
        if (!base.IsMember)
        {
            return a;
        }
        return a * 100 / (125 + relation.rank * 2);
    }
Referenced by CalcMoney.Heal(), CalcMoney.Identify(), CalcMoney.Meal(), and CalcMoney.Picklock().
ShowBounty()
bool GuildFighter.ShowBounty (Chara c) inline
Definition at line 39 of file GuildFighter.cs.
    {
        return false;
    }
Referenced by Chara.GetHoverText().
Property Documentation
IsCurrentZone
override bool GuildFighter.IsCurrentZone get
Definition at line 5 of file GuildFighter.cs.
    {
        get
        {
            if (EClass._zone.id == "kapul")
            {
                return EClass._zone.lv == -1;
            }
            return false;
        }
    }
Referenced by Guild.GetCurrentGuild().
Quest
override QuestGuild GuildFighter.Quest get
Definition at line 3 of file GuildFighter.cs.
The documentation for this class was generated from the following file:
Elin/GuildFighter.cs