Elin Decompiled Documentation: UIBook.Page Class Reference
UIBook.Page Class Reference
Public Member Functions
virtual void BuildNote (UINote n, string idTopic)
Public Attributes
UIBook book
int idx
List< string > lines = new List<string>()
Detailed Description
Definition at line 31 of file UIBook.cs.
Member Function Documentation
BuildNote()
virtual void UIBook.Page.BuildNote (UINote n, string idTopic) inline virtual
Reimplemented in ContentGallery.Page.
Definition at line 39 of file UIBook.cs.
        {
            string text = "";
            bool center = false;
            bool hasSearchWord = !searchWord.IsEmpty();
            bool skip = false;
            UINote current = n;
            ParseLines(lines, idTopic);
            void Flush()
            {
                if (!text.IsEmpty())
                {
                    UIItem uIItem = current.AddText(STR(text));
                    text = "";
                    if (center)
                    {
                        uIItem.text1.alignment = TextAnchor.UpperCenter;
                    }
                    LayoutElement component = uIItem.GetComponent<LayoutElement>();
                    if ((bool)component)
                    {
                        component.enabled = false;
                    }
                }
            }
            void ParseLines(List<string> lines, string idTopic)
            {
                char c = 'a';
                bool flag = false;
                foreach (string line in lines)
                {
                    string text2 = Lang.Parse(line, "test1", "test2");
                    if (text2.Length == 0)
                    {
                        if (!skip && (idTopic.IsEmpty() || flag))
{
                            text += Environment.NewLine;
                        }
                    }
                    else
                    {
                        c = text2[0];
                        if (!idTopic.IsEmpty())
{
                            if (c == '$')
{
                                if (flag)
{
                                    break;
                                }
                                if (text2.Split('$')[1] == idTopic)
{
                                    flag = true;
                                    continue;
                                }
                            }
                            if (!flag)
{
                                continue;
                            }
                        }
                        if (book.mode == Mode.Announce)
{
                            switch (c)
{
                            case '■':
                                Flush();
                                current.AddHeader("HeaderPatch_header", line);
                                continue;
                            case '[':
                                text = text.TrimEnd(Environment.NewLine.ToCharArray());
                                Flush();
                                current.AddHeader("HeaderPatch_category", line);
                                continue;
                            case '*':
                                Flush();
                                text = line.TrimStart('*').TrimStart(' ').TrimEnd(Environment.NewLine.ToCharArray());
                                current.AddText("NoteText_list", text);
                                text = "";
                                continue;
                            }
                        }
                        if (c == '{')
{
                            Flush();
                            string[] array = text2.Split('}');
                            text = array[1];
                            string[] array2 = array[0].TrimStart('{').Split(array[0].Contains('|') ? '|' : ',');
                            if (!skip || !(array2[0] != "endif"))
{
                                switch (array2[0])
{
                                case "if":
{
                                    string text5 = array2[1];
                                    if (!(text5 == "cn"))
{
                                        if (text5 == "!cn" && Lang.langCode == "CN")
{
                                            skip = true;
                                        }
                                    }
                                    else if (Lang.langCode != "CN")
{
                                        skip = true;
                                    }
                                    break;
                                }
                                case "endif":
                                    skip = false;
                                    break;
                                case "include":
                                case "load":
{
                                    string text3 = "";
                                    string text4 = "";
                                    if (array2[0] == "include")
{
                                        text3 = array2[1];
                                        text4 = "include";
                                    }
                                    else
{
                                        text4 = array2[1];
                                        text3 = array2[2];
                                    }
                                    text4 += ".txt";
                                    string[] array3 = IO.LoadTextArray(CorePath.CorePackage.Help + text4);
                                    if (array3.IsEmpty())
{
                                        array3 = IO.LoadTextArray(CorePath.CorePackage.Text + text4);
                                    }
                                    if (array3.IsEmpty())
{
                                        array3 = IO.LoadTextArray(CorePath.CorePackage.TextCommon + text4);
                                    }
                                    if (!array3.IsEmpty())
{
                                        ParseLines(array3.ToList(), text3);
                                    }
                                    break;
                                }
                                case "center":
                                    center = true;
                                    break;
                                case "/center":
                                    center = false;
                                    break;
                                case "layout":
                                    if (array2.Length == 1)
{
                                        current = n;
                                    }
                                    else
{
                                        current = n.AddNote(STR(array2[1]));
                                    }
                                    break;
                                case "nerun":
                                    current.AddText("NoteText_nerun", STR(text));
                                    break;
                                case "topic":
                                    current.AddHeader("HeaderHelpTopic", array2[1]);
                                    break;
                                case "Q":
                                    current.AddText("NoteText_Q", STR(array2[1]));
                                    break;
                                case "A":
                                    current.AddText("NoteText_A", STR(array2[1]));
                                    break;
                                case "pair":
                                    current.AddTopic("TopicPair", STR(array2[1]), STR(array2[2]));
                                    break;
                                case "image":
                                    current.AddImage(array2[1]);
                                    break;
                                case "link":
                                    current.AddButtonLink(array2[1], array2[2]);
                                    break;
                                case "button":
                                    if (array2[1] == "close")
{
                                        book.AddButtonClose();
                                    }
                                    break;
                                }
                                text = "";
                            }
                        }
                        else if (!skip)
{
                            text = text + text2 + Environment.NewLine;
                        }
                    }
                }
                if (!text.IsEmpty())
                {
                    text = text.Replace("#pc", str_pc);
                    UIItem uIItem2 = current.AddText("NoteText_help", STR(text));
                    if (center)
                    {
                        uIItem2.text1.alignment = TextAnchor.UpperCenter;
                    }
                }
            }
            string STR(string s)
            {
                if (!hasSearchWord)
                {
                    return s;
                }
                return Regex.Replace(s, searchWord, searchWord.TagColor(book.colorSearchHit), RegexOptions.IgnoreCase);
            }
        }
References UIBook.AddButtonClose(), UINote.AddButtonLink(), UINote.AddHeader(), UINote.AddImage(), UINote.AddNote(), UINote.AddText(), UINote.AddTopic(), UIBook.Page.book, UIBook.colorSearchHit, CorePath.CorePackage.Help, UIBook.idTopic, Lang.langCode, UIBook.Page.lines, UIBook.mode, Lang.Parse(), UIBook.searchWord, UIBook.str_pc, CorePath.CorePackage.Text, and CorePath.CorePackage.TextCommon.
Member Data Documentation
book
UIBook UIBook.Page.book
Definition at line 33 of file UIBook.cs.
Referenced by UIBook.Page.BuildNote().
idx
int UIBook.Page.idx
Definition at line 35 of file UIBook.cs.
lines
List<string> UIBook.Page.lines = new List<string>()
Definition at line 37 of file UIBook.cs.
Referenced by UIBook.Page.BuildNote().
The documentation for this class was generated from the following file:
Elin/Plugins.UI/UIBook.cs