Elin Decompiled Documentation: SourceElement Class Reference
SourceElement Class Reference
Classes
class Row
Public Member Functions
override Row CreateRow ()
override void SetRow (Row r)
override void OnInit ()
override void OnAfterImportData ()
void AddRow (Row ele, int id, string idOrg)
Public Member Functions inherited from SourceDataInt< SourceElement.Row >
override T GetRow (string id)
Public Attributes
List< Row > hobbies = new List<Row>()
Properties
override string[] ImportFields [get]
Detailed Description
Definition at line 7 of file SourceElement.cs.
Member Function Documentation
AddRow()
void SourceElement.AddRow (Row ele, int id, string idOrg) inline
Definition at line 397 of file SourceElement.cs.
    {
        if (Application.isEditor || !map.ContainsKey(id))
        {
            Row row = EClass.sources.elements.alias[idOrg];
            System.Reflection.FieldInfo[] fields = row.GetType().GetFields();
            Row row2 = new Row();
            System.Reflection.FieldInfo[] array = fields;
            foreach (System.Reflection.FieldInfo fieldInfo in array)
            {
                row2.SetField(fieldInfo.Name, row.GetField<object>(fieldInfo.Name));
            }
            row2.id = id;
            row2.idMold = row.id;
            row2.alias = row.alias + ele.alias.Remove(0, 3);
            row2.aliasRef = ele.alias;
            row2.aliasParent = ele.aliasParent;
            row2.chance = row.chance * ele.chance / 100;
            row2.LV = row.LV;
            row2.OnImportData(EClass.sources.elements);
            rows.Add(row2);
        }
    }
References SourceElement.Row.alias, SourceElement.Row.aliasParent, SourceManager.elements, SourceElement.Row.id, SourceElement.Row.LV, and EClass.sources.
Referenced by OnAfterImportData().
CreateRow()
override Row SourceElement.CreateRow () inline
Definition at line 284 of file SourceElement.cs.
    {
        return new Row
        {
            id = SourceData.GetInt(0),
            alias = SourceData.GetString(1),
            name_JP = SourceData.GetString(2),
            name = SourceData.GetString(3),
            altname_JP = SourceData.GetString(4),
            altname = SourceData.GetString(5),
            aliasParent = SourceData.GetString(6),
            aliasRef = SourceData.GetString(7),
            aliasMtp = SourceData.GetString(8),
            parentFactor = SourceData.GetFloat(9),
            lvFactor = SourceData.GetInt(10),
            encFactor = SourceData.GetInt(11),
            encSlot = SourceData.GetString(12),
            mtp = SourceData.GetInt(13),
            LV = SourceData.GetInt(14),
            chance = SourceData.GetInt(15),
            value = SourceData.GetInt(16),
            cost = SourceData.GetIntArray(17),
            geneSlot = SourceData.GetInt(18),
            sort = SourceData.GetInt(19),
            target = SourceData.GetString(20),
            proc = SourceData.GetStringArray(21),
            type = SourceData.GetString(22),
            group = SourceData.GetString(23),
            category = SourceData.GetString(24),
            categorySub = SourceData.GetString(25),
            abilityType = SourceData.GetStringArray(26),
            tag = SourceData.GetStringArray(27),
            thing = SourceData.GetString(28),
            eleP = SourceData.GetInt(29),
            cooldown = SourceData.GetInt(30),
            charge = SourceData.GetInt(31),
            radius = SourceData.GetFloat(32),
            max = SourceData.GetInt(33),
            req = SourceData.GetStringArray(34),
            idTrainer = SourceData.GetString(35),
            partySkill = SourceData.GetInt(36),
            tagTrainer = SourceData.GetString(37),
            levelBonus_JP = SourceData.GetString(38),
            levelBonus = SourceData.GetString(39),
            foodEffect = SourceData.GetStringArray(40),
            langAct = SourceData.GetStringArray(42),
            detail_JP = SourceData.GetString(43),
            detail = SourceData.GetString(44),
            textPhase_JP = SourceData.GetString(45),
            textPhase = SourceData.GetString(46),
            textExtra_JP = SourceData.GetString(47),
            textExtra = SourceData.GetString(48),
            textInc_JP = SourceData.GetString(49),
            textInc = SourceData.GetString(50),
            textDec_JP = SourceData.GetString(51),
            textDec = SourceData.GetString(52),
            textAlt_JP = SourceData.GetStringArray(53),
            textAlt = SourceData.GetStringArray(54),
            adjective_JP = SourceData.GetStringArray(55),
            adjective = SourceData.GetStringArray(56)
        };
    }
References SourceData< T, T2 >.GetFloat(), SourceData< T, T2 >.GetInt(), SourceData< T, T2 >.GetIntArray(), SourceData< T, T2 >.GetString(), and SourceData< T, T2 >.GetStringArray().
OnAfterImportData()
override void SourceElement.OnAfterImportData () inline
Definition at line 368 of file SourceElement.cs.
    {
        Core.SetCurrent();
        foreach (Row row in rows)
        {
            map[row.id] = row;
            alias[row.GetAlias] = row;
        }
        int num = 50000;
        int num2 = 0;
        for (int i = 910; i < 927; i++)
        {
            Row ele = EClass.sources.elements.map[i];
            AddRow(ele, num + num2 + 100, "ball_");
            AddRow(ele, num + num2 + 200, "breathe_");
            AddRow(ele, num + num2 + 300, "bolt_");
            AddRow(ele, num + num2 + 400, "hand_");
            AddRow(ele, num + num2 + 500, "arrow_");
            AddRow(ele, num + num2 + 600, "funnel_");
            AddRow(ele, num + num2 + 700, "miasma_");
            AddRow(ele, num + num2 + 800, "weapon_");
            AddRow(ele, num + num2 + 900, "puddle_");
            AddRow(ele, num + num2 + 1000, "sword_");
            AddRow(ele, num + num2 + 1100, "bit_");
            AddRow(ele, num + num2 + 1200, "flare_");
            num2++;
        }
    }
References AddRow(), SourceManager.elements, SourceElement.Row.GetAlias, SourceElement.Row.id, Core.SetCurrent(), and EClass.sources.
OnInit()
override void SourceElement.OnInit () inline
Definition at line 352 of file SourceElement.cs.
    {
        foreach (Row row in rows)
        {
            if (row.id >= 100 && row.id < 400)
            {
                hobbies.Add(row);
            }
            row.isAttribute = row.category == "attribute";
            row.isPrimaryAttribute = row.isAttribute && row.tag.Contains("primary");
            row.isSkill = row.category == "skill";
            row.isSpell = row.categorySub == "spell";
            row.isTrait = row.tag.Contains("trait");
        }
    }
References hobbies, SourceElement.Row.id, and SourceElement.Row.tag.
SetRow()
override void SourceElement.SetRow (Row r) inline
Definition at line 347 of file SourceElement.cs.
    {
        map[r.id] = r;
    }
References SourceElement.Row.id.
Member Data Documentation
hobbies
List<Row> SourceElement.hobbies = new List<Row>()
Definition at line 280 of file SourceElement.cs.
Referenced by Biography.Generate(), and OnInit().
Property Documentation
ImportFields
override string [] SourceElement.ImportFields get
Definition at line 282 of file SourceElement.cs.
The documentation for this class was generated from the following file:
Elin/SourceElement.cs