Elin Decompiled Documentation: LayerList Class Reference
LayerList Class Reference
Classes
class CustomItem
Public Member Functions
override void OnInit ()
override void OnUpdateInput ()
LayerList SetMold (int index)
LayerList SetSize (float w=450f, float h=-1f)
LayerList SetPivot (float x, float y=-1f)
void RefreshSize ()
LayerList SetList< TValue > (ICollection< TValue > items, Func< TValue, string > getString, Action< int, string > onSelect, bool autoClose=true)
LayerList SetStringList (Func< ICollection< string > > getList, Action< int, string > onSelect, bool autoClose=true)
LayerList SetList2< TValue > (ICollection< TValue > _list, Func< TValue, string > getText, Action< TValue, ItemGeneral > onClick, Action< TValue, ItemGeneral > onInstantiate, bool autoClose=true)
LayerList SetListCheck< TValue > (ICollection< TValue > _list, Func< TValue, string > getText, Action< TValue, ItemGeneral > onClick, Action< List< UIList.ButtonPair > > onValidate)
LayerList EnableReroll ()
LayerList ManualList (Action< UIList, LayerList > onInit)
LayerList SetHeader (string lang)
LayerList SetNoSound ()
void SetHighlightTarget (UIButton _target)
override void OnKill ()
void Add (string lang, Action< int > action)
void Show (bool autoClose=true)
Public Member Functions inherited from ELayer
override void OnBeforeAddLayer ()
void InitInspector ()
sealed override void Init ()
override void OnAfterAddLayer ()
void TryShowHelp ()
void AddLayerToUI (string id)
void TryShowHint (string _langHint=null)
void TalkHomeMemeber (string id)
void TalkMaid (string id)
override void OnRightClick ()
Public Member Functions inherited from Layer
virtual string GetTextHeader (Window window)
virtual bool HeaderIsListOf (int id)
virtual void Init ()
virtual void OnInit ()
virtual void OnAfterInit ()
virtual void ApplySkin ()
void ShowScreenLock (string id)
void UpdateInput ()
virtual void OnUpdateInput ()
virtual void OnRightClick ()
virtual bool OnBack ()
virtual void OnChangeLayer ()
virtual void OnCreate ()
void _AddLayer (string id)
Layer AddLayer (string id)
T AddLayer< T > ()
T AddLayer< T > (string id)
T AddLayerDontCloseOthers< T > ()
Layer AddLayerDontCloseOthers (Layer l)
T GetOrAddLayer< T > ()
virtual void OnBeforeAddLayer ()
virtual void OnAfterAddLayer ()
Layer AddLayer (Layer l)
void ToggleLayer (string id)
T ToggleLayer< T > (string id=null)
void WaitAndClose ()
void OnClickClose ()
virtual void Close ()
void CloseLayers ()
void RemoveLayers (bool removeImportant=false)
bool RemoveLayer< T > ()
void RemoveLayer (Layer l)
virtual void OnKill ()
Layer SetOnKill (Action action)
void DisableClose ()
void Delay (float duration=0.05f)
Layer SetDelay (float d)
Layer GetLayer (string id)
T GetLayer< T > (bool fromTop=false)
Layer GetTopLayer ()
void SwitchContent (int idWindow, int i)
virtual void OnSwitchContent (Window window)
Layer SetTitles (string langList, string idHeaderRow=null)
bool IsBlockWidgetClick ()
bool IsHideHud ()
bool IsAllowGeneralInput ()
bool IsUseBlur ()
bool IsPointerOnLayer ()
void ApplySkin ()
Public Attributes
UIList list
UIButton buttonReroll
UIButton highlightTarget
UIItem moldItemCheck
Transform moldItemGeneral
Transform moldItemDetail
bool useItem
bool autoX
bool autoY
bool noSound
UIScrollView scroll
Vector2 sizeMin
Vector2 sizeMax
Vector2 paddings
List< CustomItem > customItems = new List<CustomItem>()
Public Attributes inherited from Layer
Option option
UnityEvent onKill
Anime animeIn
Anime animeOut
bool closeOthers
bool defaultActionMode = true
Button screenLock
Layer parent
string idLayer
List< Layer > layers = new List<Layer>()
Vector2 lastParentPos
List< Window > windows = new List<Window>()
string langHint
Protected Member Functions
override void Awake ()
Protected Member Functions inherited from ELayer
sealed override void _Close ()
sealed override void Kill ()
virtual void Awake ()
virtual void _Close ()
virtual void Kill ()
Private Member Functions
void Update ()
void LateUpdate ()
Private Attributes
bool initialized
Additional Inherited Members
Static Public Member Functions inherited from ELayer
static int rnd (int a)
Static Public Member Functions inherited from Layer
static T Create< T > ()
static T Create< T > (string path)
static Layer Create (string path)
Static Public Attributes inherited from Layer
static int skipInput
static bool closeOnRightClick
static bool rightClicked
static bool cancelKeyDown
static bool ignoreSounds
static Transform blurStopInstance
static string[] searchPath = new string[3] { "Layer", "Layer/Dialog", "Layer/LayerHome" }
Protected Attributes inherited from Layer
RectTransform _rect
bool isDestroyed
Properties inherited from ELayer
static Core core [get]
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static FactionBranch Branch [get]
static Faction Home [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static CoreConfig config [get]
static GameSetting setting [get]
static ColorProfile Colors [get]
static SourceManager sources [get]
static World world [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
bool IsFloat [get]
virtual string IdHelp [get]
Properties inherited from Layer
Layer TopLayer [get]
string uid [get]
virtual RectTransform rectLayers [get]
virtual bool blockWidgetClick [get]
Detailed Description
Definition at line 5 of file LayerList.cs.
Member Function Documentation
Add()
void LayerList.Add (string lang, Action< int > action) inline
Definition at line 340 of file LayerList.cs.
    {
        if (!initialized)
        {
            initialized = true;
        }
        customItems.Add(new CustomItem
        {
            lang = lang,
            action = action,
            id = customItems.Count
        });
    }
References customItems, and initialized.
Referenced by TraitMapBoard.TrySetAct().
Awake()
override void LayerList.Awake () inline protected virtual
Reimplemented from Layer.
Definition at line 48 of file LayerList.cs.
    {
        base.Awake();
        if ((bool)buttonReroll)
        {
            buttonReroll.SetActive(enable: false);
        }
    }
References buttonReroll.
EnableReroll()
LayerList LayerList.EnableReroll () inline
Definition at line 259 of file LayerList.cs.
    {
        buttonReroll.SetActive(enable: true);
        buttonReroll.onClick.RemoveAllListeners();
        buttonReroll.onClick.AddListener(delegate
        {
            list.List();
        });
        list.RebuildLayout(recursive: true);
        RefreshSize();
        return this;
    }
References buttonReroll, list, UIList.List(), and RefreshSize().
Referenced by UICharaMaker.ListAlias(), and TraitFactionBoard.TrySetAct().
LateUpdate()
void LayerList.LateUpdate () inline private
Definition at line 308 of file LayerList.cs.
    {
        if ((bool)highlightTarget)
        {
            highlightTarget.DoHighlightTransition();
        }
    }
References UIButton.DoHighlightTransition(), and highlightTarget.
ManualList()
LayerList LayerList.ManualList (Action< UIList, LayerList > onInit) inline
Definition at line 272 of file LayerList.cs.
    {
        buttonReroll.SetActive(enable: false);
        list.moldItem = moldItemGeneral;
        onInit(list, this);
        list.List();
        RefreshSize();
        return this;
    }
References buttonReroll, list, UIList.List(), moldItemGeneral, and RefreshSize().
OnInit()
override void LayerList.OnInit () inline virtual
Reimplemented from Layer.
Definition at line 57 of file LayerList.cs.
    {
        if ((bool)highlightTarget)
        {
            highlightTarget.DoHighlightTransition();
        }
        EInput.WaitReleaseKey();
    }
References UIButton.DoHighlightTransition(), highlightTarget, and EInput.WaitReleaseKey().
OnKill()
override void LayerList.OnKill () inline virtual
Reimplemented from Layer.
Definition at line 316 of file LayerList.cs.
    {
        if ((bool)highlightTarget)
        {
            ELayer.core.WaitForEndOfFrame(delegate
            {
                if ((bool)highlightTarget)
                {
                    if (!InputModuleEX.IsPointerOver(highlightTarget))
                    {
                        highlightTarget.DoNormalTransition();
                    }
                    else
                    {
                        highlightTarget.DoHighlightTransition();
                    }
                }
            });
        }
        TooltipManager.Instance.HideTooltips(immediate: true);
        TooltipManager.Instance.disableHide = null;
        EInput.WaitReleaseKey();
    }
References ELayer.core, TooltipManager.HideTooltips(), highlightTarget, TooltipManager.Instance, InputModuleEX.IsPointerOver(), BaseCore.WaitForEndOfFrame(), and EInput.WaitReleaseKey().
OnUpdateInput()
override void LayerList.OnUpdateInput () inline virtual
Reimplemented from Layer.
Definition at line 66 of file LayerList.cs.
    {
        foreach (UIList.ButtonPair button in list.buttons)
        {
            ItemGeneral itemGeneral = button.component as ItemGeneral;
            UIButton uIButton = (itemGeneral ? itemGeneral.button1 : (button.component as UIButton));
            if ((bool)uIButton && uIButton.interactable && !EInput.waitReleaseAnyKey && (bool)uIButton.keyText && !uIButton.keyText.text.IsEmpty() && uIButton.keyText.text == Input.inputString)
            {
                SE.ClickOk();
                uIButton.onClick.Invoke();
                return;
            }
        }
        base.OnUpdateInput();
    }
References UIList.buttons, UIButton.keyText, and list.
RefreshSize()
void LayerList.RefreshSize () inline
Definition at line 117 of file LayerList.cs.
    {
        RectTransform rectTransform = windows[0].Rect();
        float x = rectTransform.sizeDelta.x;
        float y = rectTransform.sizeDelta.y;
        this.RebuildLayout(recursive: true);
        Vector2 sizeDelta = scroll.content.Rect().sizeDelta;
        if (autoX)
        {
            x = Mathf.Clamp(sizeDelta.x, sizeMin.x, sizeMax.x) + paddings.x;
        }
        if (autoY)
        {
            y = Mathf.Clamp(sizeDelta.y, sizeMin.y, sizeMax.y) + paddings.y;
        }
        rectTransform.sizeDelta = new Vector2(x, y);
    }
References autoX, autoY, paddings, scroll, sizeMax, sizeMin, and Layer.windows.
Referenced by EnableReroll(), ManualList(), SetList2< TValue >(), SetListCheck< TValue >(), SetStringList(), and Show().
SetHeader()
LayerList LayerList.SetHeader (string lang) inline
Definition at line 282 of file LayerList.cs.
    {
        windows[0].SetCaption(lang.lang());
        return this;
    }
References Layer.windows.
SetHighlightTarget()
void LayerList.SetHighlightTarget (UIButton _target) inline
Definition at line 294 of file LayerList.cs.
    {
        highlightTarget = _target;
        highlightTarget.DoHighlightTransition();
    }
References UIButton.DoHighlightTransition(), and highlightTarget.
SetList2< TValue >()
LayerList LayerList.SetList2< TValue > (ICollection< TValue > _list, Func< TValue, string > getText, Action< TValue, ItemGeneral > onClick, Action< TValue, ItemGeneral > onInstantiate, bool autoClose = true) inline
Definition at line 181 of file LayerList.cs.
    {
        list.callbacks = new UIList.Callback<TValue, ItemGeneral>
        {
            onClick = delegate(TValue a, ItemGeneral b)
            {
                onClick(a, b);
                if (autoClose)
                {
                    Close();
                }
            },
            onInstantiate = delegate(TValue a, ItemGeneral item)
            {
                item.button1.mainText.text = getText(a);
                item.DisableIcon();
                item.Build();
                if (noSound)
                {
                    item.button1.soundClick = null;
                }
                if (onInstantiate != null)
                {
                    onInstantiate(a, item);
                }
            },
            onList = delegate
            {
                foreach (TValue item in _list)
                {
                    list.Add(item);
                }
            }
        };
        list.List();
        RefreshSize();
        UIButton.TryShowTip(base.transform);
        return this;
    }
References UIList.Add(), Layer.Close(), item, list, UIList.List(), noSound, RefreshSize(), and UIButton.TryShowTip().
SetList< TValue >()
LayerList LayerList.SetList< TValue > (ICollection< TValue > items, Func< TValue, string > getString, Action< int, string > onSelect, bool autoClose = true) inline
Definition at line 135 of file LayerList.cs.
    {
        List<string> strs = new List<string>();
        foreach (TValue item in items)
        {
            strs.Add(getString(item));
        }
        SetStringList(() => strs, onSelect, autoClose);
        return this;
    }
References item, and SetStringList().
SetListCheck< TValue >()
LayerList LayerList.SetListCheck< TValue > (ICollection< TValue > _list, Func< TValue, string > getText, Action< TValue, ItemGeneral > onClick, Action< List< UIList::ButtonPair > > onValidate) inline
Definition at line 221 of file LayerList.cs.
    {
        list.moldItem = moldItemCheck.transform;
        list.callbacks = new UIList.Callback<TValue, ItemGeneral>
        {
            onClick = delegate
            {
            },
            onInstantiate = delegate(TValue a, ItemGeneral item)
            {
                item.button1.mainText.text = getText(a);
                item.DisableIcon();
                item.Build();
                item.button1.SetOnClick(delegate
                {
                    onClick(a, item);
                    Validate();
                });
            },
            onList = delegate
            {
                foreach (TValue item in _list)
                {
                    list.Add(item);
                }
            }
        };
        list.List();
        Validate();
        RefreshSize();
        UIButton.TryShowTip(base.transform);
        return this;
        void Validate()
        {
            onValidate(list.buttons);
        }
    }
References UIList.Add(), UIList.buttons, item, list, UIList.List(), moldItemCheck, RefreshSize(), and UIButton.TryShowTip().
SetMold()
LayerList LayerList.SetMold (int index) inline
Definition at line 82 of file LayerList.cs.
    {
        switch (index)
        {
        case 0:
            list.moldItem = moldItemGeneral;
            break;
        case 1:
            list.moldItem = moldItemDetail;
            break;
        }
        return this;
    }
References moldItemDetail, and moldItemGeneral.
SetNoSound()
LayerList LayerList.SetNoSound () inline
Definition at line 288 of file LayerList.cs.
    {
        noSound = true;
        return this;
    }
References noSound.
SetPivot()
LayerList LayerList.SetPivot (float x, float y = -1f) inline
Definition at line 111 of file LayerList.cs.
    {
        windows[0].Rect().pivot = new Vector2(x, y);
        return this;
    }
References Layer.windows.
SetSize()
LayerList LayerList.SetSize (float w = 450f, float h = -1f) inline
Definition at line 96 of file LayerList.cs.
    {
        Vector2 sizeDelta = windows[0].Rect().sizeDelta;
        windows[0].Rect().sizeDelta = new Vector2((w == -1f) ? sizeDelta.x : w, (h == -1f) ? sizeDelta.y : h);
        if (w != -1f)
        {
            autoX = false;
        }
        if (h != -1f)
        {
            autoY = false;
        }
        return this;
    }
References autoX, autoY, and Layer.windows.
Referenced by UICharaMaker.ListDifficulties(), UICharaMaker.ListJob(), and UICharaMaker.ListRace().
SetStringList()
LayerList LayerList.SetStringList (Func< ICollection< string > > getList, Action< int, string > onSelect, bool autoClose = true) inline
Definition at line 146 of file LayerList.cs.
    {
        list.callbacks = new UIList.Callback<string, ItemGeneral>
        {
            onClick = delegate(string a, ItemGeneral b)
            {
                onSelect(list.items.IndexOf(a), a);
                if (autoClose)
                {
                    Close();
                }
            },
            onInstantiate = delegate(string a, ItemGeneral item)
            {
                item.button1.mainText.text = a;
                item.DisableIcon();
                item.Build();
                if (noSound)
                {
                    item.button1.soundClick = null;
                }
            },
            onList = delegate
            {
                foreach (string item in getList())
                {
                    list.Add(item);
                }
            }
        };
        list.List();
        RefreshSize();
        return this;
    }
References UIList.Add(), Layer.Close(), item, UIList.items, list, UIList.List(), noSound, and RefreshSize().
Referenced by SetList< TValue >().
Show()
void LayerList.Show (bool autoClose = true) inline
Definition at line 354 of file LayerList.cs.
    {
        list.callbacks = new UIList.Callback<CustomItem, ItemGeneral>
        {
            onClick = delegate(CustomItem a, ItemGeneral b)
            {
                a.action(a.id);
                if (autoClose)
                {
                    Close();
                }
            },
            onInstantiate = delegate(CustomItem a, ItemGeneral item)
            {
                item.button1.mainText.text = a.lang.lang();
                item.DisableIcon();
                item.Build();
            },
            onList = delegate
            {
                foreach (CustomItem customItem in customItems)
                {
                    list.Add(customItem);
                }
            }
        };
        buttonReroll.SetActive(enable: false);
        list.List();
        RefreshSize();
        if (!autoClose)
        {
            windows[0].AddBottomButton("back", Close, setFirst: true);
        }
    }
References LayerList.CustomItem.action, UIList.Add(), buttonReroll, Layer.Close(), customItems, LayerList.CustomItem.id, item, LayerList.CustomItem.lang, list, UIList.List(), RefreshSize(), and Layer.windows.
Referenced by TraitMapBoard.TrySetAct().
Update()
void LayerList.Update () inline private
Definition at line 300 of file LayerList.cs.
    {
        if ((bool)highlightTarget)
        {
            highlightTarget.DoHighlightTransition();
        }
    }
References UIButton.DoHighlightTransition(), and highlightTarget.
Member Data Documentation
autoX
bool LayerList.autoX
Definition at line 30 of file LayerList.cs.
Referenced by RefreshSize(), and SetSize().
autoY
bool LayerList.autoY
Definition at line 32 of file LayerList.cs.
Referenced by RefreshSize(), and SetSize().
buttonReroll
UIButton LayerList.buttonReroll
Definition at line 18 of file LayerList.cs.
Referenced by Awake(), EnableReroll(), ManualList(), and Show().
customItems
List<CustomItem> LayerList.customItems = new List<CustomItem>()
Definition at line 46 of file LayerList.cs.
Referenced by Add(), and Show().
highlightTarget
UIButton LayerList.highlightTarget
Definition at line 20 of file LayerList.cs.
Referenced by LateUpdate(), OnInit(), OnKill(), SetHighlightTarget(), and Update().
initialized
bool LayerList.initialized private
Definition at line 44 of file LayerList.cs.
Referenced by Add().
list
UIList LayerList.list
Definition at line 16 of file LayerList.cs.
Referenced by EnableReroll(), ManualList(), OnUpdateInput(), SetList2< TValue >(), SetListCheck< TValue >(), SetStringList(), and Show().
moldItemCheck
UIItem LayerList.moldItemCheck
Definition at line 22 of file LayerList.cs.
Referenced by SetListCheck< TValue >().
moldItemDetail
Transform LayerList.moldItemDetail
Definition at line 26 of file LayerList.cs.
Referenced by SetMold().
moldItemGeneral
Transform LayerList.moldItemGeneral
Definition at line 24 of file LayerList.cs.
Referenced by ManualList(), and SetMold().
noSound
bool LayerList.noSound
Definition at line 34 of file LayerList.cs.
Referenced by SetList2< TValue >(), SetNoSound(), and SetStringList().
paddings
Vector2 LayerList.paddings
Definition at line 42 of file LayerList.cs.
Referenced by RefreshSize().
scroll
UIScrollView LayerList.scroll
Definition at line 36 of file LayerList.cs.
Referenced by RefreshSize().
sizeMax
Vector2 LayerList.sizeMax
Definition at line 40 of file LayerList.cs.
Referenced by RefreshSize().
sizeMin
Vector2 LayerList.sizeMin
Definition at line 38 of file LayerList.cs.
Referenced by RefreshSize().
useItem
bool LayerList.useItem
Definition at line 28 of file LayerList.cs.
The documentation for this class was generated from the following file:
Elin/LayerList.cs