Elin Decompiled Documentation: ButtonElement Class Reference
ButtonElement Class Reference
Public Types
enum Mode {
Skill , Attribute , Tech , Feat ,
Enchant , Policy , OnlyValue , FeatPurchase ,
LandFeat , FeatMini
}
Public Member Functions
void SetElement (Element _e, ElementContainer _owner, Mode _mode=Mode.Skill)
void Refresh ()
void SetGrid (Element e, Chara c)
Public Member Functions inherited from UIButton
virtual bool CanMiddleClick ()
virtual void OnMiddleClick (bool forceClick)
void SetItem (Item i)
virtual void RefreshItem ()
virtual void OnHover ()
void Toggle ()
void ToggleCheck ()
void SetCheck (bool check)
void SetToggle (bool isOn, Action< bool > onToggle=null)
void SetTooltip (Action< UITooltip > onShowTooltip=null, bool enable=true)
void SetTooltip (string id, Action< UITooltip > onShowTooltip=null, bool enable=true)
void SetTooltipLang (string lang=null)
virtual void ShowTooltip ()
void ShowTooltipForced (bool ignoreWhenRightClick=true)
override void OnPointerDown (PointerEventData eventData)
override void OnPointerClick (PointerEventData eventData)
override void OnPointerUp (PointerEventData eventData)
void OnPointerUpOnDrag (PointerEventData eventData)
void _OnPress ()
void OnPress ()
void AddHighlight (Func< bool > killCondition)
void DoHighlightTransition (bool instant=false)
void DoNormalTransition (bool instant=true)
override Selectable FindSelectableOnDown ()
override Selectable FindSelectableOnUp ()
override Selectable FindSelectableOnLeft ()
override Selectable FindSelectableOnRight ()
void SetNavigation (UIButton up, UIButton down=null, UIButton left=null, UIButton right=null)
override bool IsActive ()
void SetInteractableWithAlpha (bool enable)
virtual void ApplySkin ()
void ApplySkin ()
Public Attributes
Image imagePotential
GameObject goExp
Element e
ElementContainer owner
UIButton buttonUpgrade
UIItem moldItemResist
LayoutGroup layout
Mode mode
Public Attributes inherited from UIButton
UIText mainText
UIText subText
UIText subText2
UIText keyText
Image icon
Image imageCheck
Graphic[] targetGraphics
float scaleIcon = 1f
float slideX
float navigationFix
bool isChecked
bool instantClick = true
UISelectableGroup group
TooltipData tooltip
SoundData soundClick
SoundData soundHighlight
Transform animeTarget
Anime animeClick
Anime animeHold
ButtonType buttonType
BaseSkinRoot skinRoot
Action onDoubleClick
Action onRightClick
Action< int > onInputWheel
object refObj
int refInt
string refStr
bool animating
bool selected
Vector3 originalIconScale = Vector3.one
UIButton highlightTarget
Item item
Additional Inherited Members
Static Public Member Functions inherited from UIButton
static void UpdateButtons ()
static void TryHihlight ()
static void TryShowTip (Transform root=null, bool highlight=true, bool ignoreWhenRightClick=true)
static void TryShowTip< T > (Transform root=null, bool highlight=true, bool ignoreWhenRightClick=true)
Static Public Attributes inherited from UIButton
static bool DoSlide
static bool locked
static UIButton lastButton
static UIButton lastHovered
static UIButton currentHighlight
static UIButton currentPressedButton
static float lastClicked
static float doubleClickTime = 0.4f
static Vector2 buttonPos
static Action onPressed
static List< UIButton > buttons = new List<UIButton>()
static Action actionTooltip
Protected Member Functions inherited from UIButton
override void Awake ()
override void OnEnable ()
override void DoStateTransition (SelectionState state, bool instant)
Properties inherited from UIButton
List< Graphic > Graphics [get]
virtual bool CanDragLeftButton [get]
Detailed Description
Definition at line 5 of file ButtonElement.cs.
Member Enumeration Documentation
Mode
enum ButtonElement.Mode
Enumerator
Skill
Attribute
Tech
Feat
Enchant
Policy
OnlyValue
FeatPurchase
LandFeat
FeatMini
Definition at line 7 of file ButtonElement.cs.
    {
        Skill,
        Attribute,
        Tech,
        Feat,
        Enchant,
        Policy,
        OnlyValue,
        FeatPurchase,
        LandFeat,
        FeatMini
    }
Member Function Documentation
Refresh()
void ButtonElement.Refresh () inline
Definition at line 45 of file ButtonElement.cs.
    {
        string text = "";
        if ((bool)WindowChara.Instance && WindowChara.Instance.chara == EClass.pc && EClass.player.trackedElements.Contains(e.id))
        {
            text = "*";
        }
        switch (mode)
        {
        case Mode.Tech:
        {
            mainText.SetText(text + e.Name + " " + e.DisplayValue, FontColor.Default);
            int techUpgradeCost = EClass.Branch.GetTechUpgradeCost(e);
            int currency = EClass.pc.GetCurrency("money2");
            if (EClass.Branch.elements.ValueWithoutLink(e.id) == 0 || e.source.cost[0] == 0 || techUpgradeCost == 0)
            {
                subText.SetText("-");
            }
            else
            {
                subText.SetText(techUpgradeCost.ToString() ?? "", (currency >= techUpgradeCost) ? FontColor.Good : FontColor.Bad);
            }
            break;
        }
        case Mode.Policy:
            mainText.SetText(text + e.Name, FontColor.Default);
            e.SetTextValue(subText);
            Mathf.Clamp((float)e.Potential / 300f, 0.1f, 1f);
            if ((bool)imagePotential)
            {
                imagePotential.SetActive(enable: false);
            }
            break;
        case Mode.LandFeat:
        {
            string text3 = text + e.Name;
            if (e.HasTag("network") && EClass.Branch != null && EClass.Branch.HasNetwork)
            {
                text3 = "feat_network".lang(text3);
            }
            mainText.SetText(text3 + " " + e.Value, FontColor.Default);
            subText.horizontalOverflow = HorizontalWrapMode.Overflow;
            subText.text = e.GetDetail().SplitNewline()[0].StripLastPun();
            if ((bool)imagePotential)
            {
                imagePotential.SetActive(enable: false);
            }
            break;
        }
        case Mode.Feat:
        case Mode.FeatPurchase:
        case Mode.FeatMini:
            if (mode == Mode.FeatPurchase)
            {
                e.IsPurchaseFeatReqMet(EClass.pc.elements);
                mainText.SetText(e.FullName, e.IsPurchaseFeatReqMet(EClass.pc.elements) ? FontColor.Default : FontColor.Warning);
                subText.text = e.GetDetail().SplitNewline()[0].StripLastPun();
                subText2.text = "".TagColor((EClass.pc.feat >= e.CostLearn) ? EClass.Colors.Skin.textGood : EClass.Colors.Skin.textBad, e.CostLearn.ToString() ?? "");
            }
            else
            {
                string text2 = ((mode == Mode.FeatMini) ? e.FullName : e.source.GetText("textPhase").SplitNewline().TryGet(e.Value - 1)
                    .StripLastPun());
                FontColor c = (e.HasTag("neg") ? FontColor.Bad : FontColor.ButtonSelectable);
                if (e.source.category == "ether")
                {
                    c = FontColor.Ether;
                }
                mainText.SetText(text + text2, c);
                subText.text = ((mode == Mode.FeatMini) ? "" : (e as Feat).GetHint(owner));
            }
            if ((bool)imagePotential)
            {
                imagePotential.SetActive(enable: false);
            }
            break;
        case Mode.Attribute:
            mainText.SetText(text + e.Name, FontColor.Default);
            e.SetTextValue(subText);
            break;
        case Mode.OnlyValue:
            e.SetTextValue(subText);
            imagePotential.SetActive(enable: false);
            break;
        default:
        {
            mainText.SetText(text + e.Name, (e.owner == null || !e.IsFactionElement(e.owner.Card as Chara)) ? FontColor.Default : FontColor.Myth);
            e.SetTextValue(subText);
            bool flag = e.source.category == "skill";
            if ((bool)imagePotential)
            {
                imagePotential.SetActive(flag && imagePotential.enabled);
            }
            break;
        }
        }
        if ((bool)imagePotential)
        {
            int num = (e.Potential - 80) / 20;
            imagePotential.enabled = e.Potential != 80;
            imagePotential.sprite = EClass.core.refs.spritesPotential[Mathf.Clamp(Mathf.Abs(num), 0, EClass.core.refs.spritesPotential.Count - 1)];
            imagePotential.color = ((num >= 0) ? Color.white : new Color(1f, 0.7f, 0.7f));
        }
        e.SetImage(icon);
        if (mode == Mode.FeatPurchase)
        {
            Element refEle = Element.Create(e.id, e.Value - 1);
            SetTooltip("note", delegate(UITooltip tt)
            {
                e.WriteNoteWithRef(tt.note, owner, null, refEle);
            });
        }
        else
        {
            SetTooltip("note", delegate(UITooltip tt)
            {
                e.WriteNote(tt.note, owner);
            });
        }
    }
References EClass.Branch, ElementContainer.Card, WindowChara.chara, Color, EClass.Colors, EClass.core, Element.CostLearn, Element.Create(), currency, Element.DisplayValue, e, Card.elements, FactionBranch.elements, Card.feat, Element.FullName, Card.GetCurrency(), Element.GetDetail(), FactionBranch.GetTechUpgradeCost(), FactionBranch.HasNetwork, Element.HasTag(), UIButton.icon, Element.id, imagePotential, WindowChara.Instance, Element.IsFactionElement(), Element.IsPurchaseFeatReqMet(), UIButton.mainText, mode, Element.Name, UITooltip.note, owner, Element.owner, EClass.pc, EClass.player, Element.Potential, Core.refs, Element.SetImage(), UIText.SetText(), Element.SetTextValue(), UIButton.SetTooltip(), ColorProfile.Skin, Element.source, CoreRef.spritesPotential, UIButton.subText, SkinColorProfile.textBad, SkinColorProfile.textGood, Player.trackedElements, Element.Value, ElementContainer.ValueWithoutLink(), Element.WriteNote(), and Element.WriteNoteWithRef().
Referenced by SetElement().
SetElement()
void ButtonElement.SetElement (Element _e, ElementContainer _owner, Mode _mode = Mode::Skill) inline
Definition at line 37 of file ButtonElement.cs.
    {
        e = _e;
        owner = _owner;
        mode = _mode;
        Refresh();
    }
References e, mode, owner, and Refresh().
Referenced by WindowCharaMini.Refresh(), LayerHome.RefreshFeat(), WindowChara.RefreshProfile(), WindowChara.RefreshSkill(), and WindowChara.RefreshStatic().
SetGrid()
void ButtonElement.SetGrid (Element e, Chara c) inline
Definition at line 166 of file ButtonElement.cs.
    {
        string text = "";
        bool flag = false;
        IList<BodySlot> list = c.body.slots.Copy();
        list.Sort((BodySlot a, BodySlot b) => c.body.GetSortVal(b) - c.body.GetSortVal(a));
        foreach (BodySlot item in list)
        {
            if (item.elementId == 44)
            {
                continue;
            }
            UIItem uIItem = Util.Instantiate(moldItemResist, layout);
            Thing thing = item.thing;
            if (thing == null)
            {
                uIItem.text1.SetActive(enable: false);
                uIItem.image1.color = Color.white.SetAlpha(0.5f);
                continue;
            }
            if (!thing.IsIdentified)
            {
                flag = true;
                uIItem.text1.SetText("?", FontColor.Passive);
                uIItem.image1.color = Color.white.SetAlpha(0.5f);
                continue;
            }
            Element element = item.thing.elements.GetElement(e.id);
            int num = 0;
            if (element != null)
            {
                num = element.Value;
                if (!element.CanLink(thing.elements) || element.IsGlobalElement)
                {
                    num = 0;
                }
            }
            if (num == 0)
            {
                uIItem.text1.SetActive(enable: false);
                uIItem.image1.color = Color.white.SetAlpha(0.5f);
            }
            text = (e.IsFlag ? "" : (Mathf.Abs(num).ToString() ?? ""));
            uIItem.text1.SetText(text, (num >= 0) ? FontColor.Good : FontColor.Bad);
        }
        text = "";
        int value = e.Value;
        int num2 = value;
        if (e is Resistance)
        {
            num2 = Element.GetResistLv(value);
            text = ((num2 <= 0) ? Lang.GetList("resistNeg")[-num2] : Lang.GetList("resist")[Mathf.Min(num2, 5)]);
        }
        text = text + " (" + (flag ? "?" : (e.IsFlag ? "" : (value.ToString() ?? ""))) + ")";
        Sprite sprite = e.GetIcon();
        if (sprite != null && (bool)icon)
        {
            icon.sprite = sprite;
        }
        mainText.SetText(e.ShortName, (!e.IsFactionElement(c)) ? FontColor.Default : FontColor.Myth);
        subText.SetText(text, (num2 == 0) ? FontColor.Default : ((num2 > 0) ? FontColor.Good : FontColor.Bad));
        SetTooltip("note", delegate(UITooltip tt)
        {
            e.WriteNote(tt.note, c.elements);
        });
    }
References Chara.body, Element.CanLink(), Color, e, Card.elements, Element.GetIcon(), Lang.GetList(), Element.GetResistLv(), CharaBody.GetSortVal(), UIButton.icon, Element.id, Element.IsFactionElement(), Element.IsGlobalElement, Card.IsIdentified, UIButton.item, layout, UIButton.mainText, moldItemResist, UITooltip.note, UIText.SetText(), UIButton.SetTooltip(), Element.ShortName, CharaBody.slots, UIButton.subText, UIItem.text1, Util, Element.Value, and Element.WriteNote().
Referenced by WindowCharaMini.Refresh(), and WindowChara.RefreshSkill().
Member Data Documentation
buttonUpgrade
UIButton ButtonElement.buttonUpgrade
Definition at line 29 of file ButtonElement.cs.
e
Element ButtonElement.e
Definition at line 25 of file ButtonElement.cs.
Referenced by Refresh(), SetElement(), and SetGrid().
goExp
GameObject ButtonElement.goExp
Definition at line 23 of file ButtonElement.cs.
imagePotential
Image ButtonElement.imagePotential
Definition at line 21 of file ButtonElement.cs.
Referenced by Refresh().
layout
LayoutGroup ButtonElement.layout
Definition at line 33 of file ButtonElement.cs.
Referenced by SetGrid().
mode
Mode ButtonElement.mode
Definition at line 35 of file ButtonElement.cs.
Referenced by Refresh(), and SetElement().
moldItemResist
UIItem ButtonElement.moldItemResist
Definition at line 31 of file ButtonElement.cs.
Referenced by SetGrid().
owner
ElementContainer ButtonElement.owner
Definition at line 27 of file ButtonElement.cs.
Referenced by Refresh(), and SetElement().
The documentation for this class was generated from the following file:
Elin/ButtonElement.cs