Elin Decompiled Documentation: BaseInspectPos Class Reference
BaseInspectPos Class Reference
Public Member Functions
void OnInspect ()
virtual void WriteNote (UINote n, Action< UINote > onWriteNote=null, IInspect.NoteMode mode=IInspect.NoteMode.Default, Recipe recipe=null)
void WriteNote (UINote n, Action< UINote > onWriteNote=null, IInspect.NoteMode mode=IInspect.NoteMode.Default, Recipe recipe=null)
void OnInspect ()
Public Attributes
Point pos = new Point()
Properties
Point InspectPoint [get]
unsafe Vector3 InspectPosition [get]
virtual bool CanInspect [get]
virtual string InspectName [get]
Properties inherited from IInspect
bool CanInspect [get]
string InspectName [get]
Point InspectPoint [get]
Vector3 InspectPosition [get]
Additional Inherited Members
Public Types inherited from IInspect
enum NoteMode { Default , Recipe , Product , Info }
Detailed Description
Definition at line 4 of file BaseInspectPos.cs.
Member Function Documentation
OnInspect()
void BaseInspectPos.OnInspect () inline
Implements IInspect.
Definition at line 6 of file BaseInspectPos.cs.
    {
    }
WriteNote()
virtual void BaseInspectPos.WriteNote (UINote n, Action< UINote > onWriteNote = null, IInspect::NoteMode mode = IInspect::NoteMode::Default, Recipe recipe = null) inline virtual
Implements IInspect.
Reimplemented in BlockInfo, and ObjInfo.
Definition at line 42 of file BaseInspectPos.cs.
    {
    }
Member Data Documentation
pos
Point BaseInspectPos.pos = new Point()
Definition at line 46 of file BaseInspectPos.cs.
Referenced by BlockInfo._CanInspect(), ObjInfo._CanInspect(), BlockInfo.GetTemp(), ObjInfo.GetTemp(), BlockInfo.GetTempList(), ObjInfo.GetTempList(), InspectGroupBlock.OnSetActions(), InspectGroupObj.OnSetActions(), and BlockInfo.WriteNote().
Property Documentation
CanInspect
virtual bool BaseInspectPos.CanInspect get
Implements IInspect.
Definition at line 26 of file BaseInspectPos.cs.
    {
        get
        {
            return this.pos.HasBlock;
        }
    }
InspectName
virtual string BaseInspectPos.InspectName get
Implements IInspect.
Definition at line 34 of file BaseInspectPos.cs.
    {
        get
        {
            return "BaseInspectPos";
        }
    }
InspectPoint
Point BaseInspectPos.InspectPoint get
Implements IInspect.
Definition at line 10 of file BaseInspectPos.cs.
    {
        get
        {
            return this.pos;
        }
    }
InspectPosition
unsafe Vector3 BaseInspectPos.InspectPosition get
Implements IInspect.
Definition at line 18 of file BaseInspectPos.cs.
    {
        get
        {
            return *this.pos.Position();
        }
    }
The documentation for this class was generated from the following file:
Elin/BaseInspectPos.cs