Elin Decompiled Documentation: CharaRenderer Class Reference
CharaRenderer Class Reference
Public Member Functions
override void SetOwner (Card c)
override void OnEnterScreen ()
override void Draw (RenderParam p, ref Vector3 v, bool drawShadow)
override void NextFrame ()
override void UpdatePosition (ref Vector3 destPos, RenderParam p)
void DrawHat ()
override void DrawHeld ()
override void RefreshStateIcon ()
override void SetFirst (bool first)
override void SetFirst (bool first, Vector3 pos)
override void Refresh ()
Public Member Functions inherited from CardRenderer
Vector3 PositionCenter ()
virtual void SetOwner (Card c)
override void Draw (RenderParam p)
override void RenderToRenderCam (RenderParam p)
override void Draw (RenderParam p, ref Vector3 v, bool drawShadow)
virtual void UpdatePosition (ref Vector3 destPos, RenderParam p)
virtual void DrawHeld ()
void RefreshSprite ()
override void OnEnterScreen ()
void AddExtra (string id)
void RefreshExtra ()
void RemoveExtra (string id)
override void OnLeaveScreen ()
void KillActor ()
void PlayAnime (AnimeID id, bool force)
void PlayAnime (AnimeID id, Card dest)
void PlayAnime (AnimeID id, Point dest)
void PlayAnime (AnimeID id, Vector3 dest=default(Vector3), bool force=false)
virtual void KillAnime ()
virtual void IdleFrame ()
virtual void NextFrame ()
virtual void NextDir ()
T AddTC< T > (TC tc)
T GetTC< T > ()
TC GetTC (string id)
T GetOrCreateTC< T > (Func< T > func)
void RemoveTC< T > ()
void RemoveTC (TC tc)
void RemoveTC (int index)
void TrySpawnOrbit ()
bool IsTalking ()
TCSimpleText SpawnSimpleText ()
void DespawnSimpleText ()
void SetCensored (bool enable)
virtual void RefreshStateIcon ()
void Say (string text, Color c=default(Color), float duration=0f)
void ShowEmo (Emo emo, float duration=0f)
virtual void SetFirst (bool first, Vector3 pos)
virtual void SetFirst (bool first)
virtual void Refresh ()
virtual void OnEnterScreen ()
virtual void OnLeaveScreen ()
virtual void RenderToRenderCam (RenderParam p)
virtual void Draw (RenderParam p)
virtual void Draw (RenderParam p, ref Vector3 v, bool drawShadow)
void RenderToRenderCam (RenderParam p)
void Draw (RenderParam p)
void OnEnterScreen ()
void OnLeaveScreen ()
Public Attributes
new Chara owner
Vector3 orgPos
bool first = true
bool ignoreFirst
Point movePoint = new Point()
AnimationCurve hopCurve
PCCData pccData
int step
bool isMoving
Public Attributes inherited from CardRenderer
TCOrbit orbit
Card owner
CardActor actor
bool hasActor
bool hasText
bool isChara
bool skip
Vector3 position
TransAnime anime
List< TC > listTC = new List<TC>()
TCSimpleText simpleText
RendererReplacer replacer
Public Attributes inherited from RenderObject
bool usePass
bool isSynced
long sync
RenderData data
Static Public Attributes
static int _animeFramePC
static int _animeFramePCC
static int _animeFrame
static bool smoothmove
Static Public Attributes inherited from RenderObject
static float gameDelta
static float gameSpeed
static float altitudeFix
static GameSetting.RenderSetting.AnimeSetting animeSetting
static GameSetting.RenderSetting renderSetting
static RenderParam shared = new RenderParam()
static RenderParam currentParam
static Vector3 tempV
static bool enableAnime
static List< ISyncScreen > syncList
static long syncFrame
Static Public Attributes inherited from EClass
static Core core
Properties
int currentDir [get]
override bool IsMoving [get]
Properties inherited from CardRenderer
virtual bool IsMoving [get]
Properties inherited from RenderObject
long Sync [get]
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Properties inherited from ISyncScreen
long Sync [get]
Private Attributes
float moveTimer
float nextframeTimer
float actTime = 0.3f
float lastShadowFix
float lastShadowFix2
Additional Inherited Members
Static Public Member Functions inherited from EClass
static int rnd (int a)
static int curve (int a, int start, int step, int rate=75)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Detailed Description
Definition at line 3 of file CharaRenderer.cs.
Member Function Documentation
Draw()
override void CharaRenderer.Draw (RenderParam p, ref Vector3 v, bool drawShadow) inline virtual
Reimplemented from CardRenderer.
Definition at line 84 of file CharaRenderer.cs.
    {
        base.Draw(p, ref v, drawShadow);
        if ((Zone.sourceHat != null || owner.hat != null) && owner.Pref.hatY != 0f && owner.host == null)
        {
            DrawHat();
        }
        if (owner.IsPC)
        {
            if (owner.held != null && !owner.IsDeadOrSleeping && (!owner.held.trait.ShowAsTool || HotItemHeld.disableTool))
            {
                DrawHeld();
            }
        }
        else if (owner.held != null && !owner.IsDeadOrSleeping && !owner.held.trait.ShowAsTool)
        {
            DrawHeld();
        }
    }
References HotItemHeld.disableTool, DrawHat(), DrawHeld(), Card.hat, SourcePref.hatY, Chara.held, Chara.host, Chara.IsDeadOrSleeping, Chara.IsPC, owner, Card.Pref, Trait.ShowAsTool, Zone.sourceHat, and Card.trait.
DrawHat()
void CharaRenderer.DrawHat () inline
Definition at line 297 of file CharaRenderer.cs.
    {
        if (pccData == null || !owner.IsDeadOrSleeping)
        {
            CardRow cardRow = Zone.sourceHat ?? owner.hat;
            SourcePref pref = cardRow.pref;
            bool flag = currentDir == 1 || currentDir == 3;
            int liquidLv = RenderObject.currentParam.liquidLv;
            float num = ((replacer != null) ? replacer.pref.hatY : owner.Pref.hatY);
            if (pccData != null)
            {
                num += RenderObject.renderSetting.hatPos[actor.GetFrame()].y;
            }
            RenderObject.currentParam.liquidLv = 0;
            RenderObject.currentParam.x += 0.01f * (float)pref.equipX;
            RenderObject.currentParam.y += num + 0.01f * (float)pref.equipY;
            RenderObject.currentParam.z -= pref.hatY;
            RenderObject.currentParam.tile = cardRow._tiles[owner.uid % cardRow._tiles.Length] * ((!flag) ? 1 : (-1));
            cardRow.renderData.Draw(RenderObject.currentParam);
            RenderObject.currentParam.y -= num;
            RenderObject.currentParam.liquidLv = liquidLv;
        }
    }
References RenderRow._tiles, CardRenderer.actor, currentDir, RenderObject.currentParam, RenderData.Draw(), SourcePref.equipX, SourcePref.equipY, CardActor.GetFrame(), Card.hat, SourcePref.hatY, Chara.IsDeadOrSleeping, RenderParam.liquidLv, owner, pccData, Card.Pref, RendererReplacer.pref, RenderRow.pref, RenderRow.renderData, RenderObject.renderSetting, CardRenderer.replacer, and MeshPassParam.y.
Referenced by Draw().
DrawHeld()
override void CharaRenderer.DrawHeld () inline virtual
Reimplemented from CardRenderer.
Definition at line 321 of file CharaRenderer.cs.
    {
        Card held = owner.held;
        int num = currentDir;
        RenderData renderData = held.renderer.data;
        SourcePref pref = held.Pref;
        bool flag = num == 1 || num == 3;
        if (held.isChara)
        {
            Vector3[] array = (EClass.player.altHeldPos ? RenderObject.renderSetting.heldPosChara2 : RenderObject.renderSetting.heldPosChara);
            RenderObject.currentParam.x += array[num].x;
            RenderObject.currentParam.y += array[num].y;
            RenderObject.currentParam.z += array[num].z + data.offset.z - renderData.offset.z;
            if (EClass.player.altHeldPos)
            {
                held.SetDir((owner.dir == 0) ? 2 : ((owner.dir == 1) ? 1 : ((owner.dir != 2) ? 3 : 0)));
            }
            else
            {
                held.SetDir((owner.dir == 0) ? 2 : owner.dir);
            }
        }
        else
        {
            Vector3[] heldPos = RenderObject.renderSetting.heldPos;
            if (hasActor)
            {
                RenderObject.currentParam.x += heldPos[num].x;
                RenderObject.currentParam.y += heldPos[num].y + 0.02f * (float)(actor.GetFrame() % 2);
                RenderObject.currentParam.z += heldPos[num].z + data.offset.z - renderData.offset.z;
            }
            else
            {
                RenderObject.currentParam.x += heldPos[4].x;
                RenderObject.currentParam.y += heldPos[4].y;
                RenderObject.currentParam.z += heldPos[4].z + data.offset.z - renderData.offset.z;
            }
            if (held.trait.NoHeldDir || !held.sourceCard.ContainsTag("noHeldDir"))
            {
                held.dir = (owner.flipX ? 1 : 0);
            }
        }
        if (!owner.Cell.sourceSurface.tileType.IsDeepWater)
        {
            int liquidLv = RenderObject.currentParam.liquidLv;
            if (held.isChara)
            {
                RenderObject.currentParam.liquidLv = 0;
            }
            held.SetRenderParam(RenderObject.currentParam);
            RenderObject.currentParam.x += renderData.heldPos.x - renderData.offset.x + (flag ? 0.01f : (-0.01f)) * (float)pref.equipX;
            RenderObject.currentParam.y += renderData.heldPos.y - renderData.offset.y + 0.01f * (float)pref.equipY;
            RenderObject.currentParam.z += renderData.heldPos.z;
            RenderObject.tempV.x = RenderObject.currentParam.x;
            RenderObject.tempV.y = RenderObject.currentParam.y;
            RenderObject.tempV.z = RenderObject.currentParam.z;
            held.renderer.Draw(RenderObject.currentParam, ref RenderObject.tempV, drawShadow: false);
            RenderObject.currentParam.liquidLv = liquidLv;
        }
    }
References CardRenderer.actor, Player.altHeldPos, Card.Cell, RenderRow.ContainsTag(), currentDir, RenderObject.currentParam, RenderObject.data, Card.dir, CardRenderer.Draw(), SourcePref.equipX, SourcePref.equipY, CardActor.GetFrame(), CardRenderer.hasActor, Chara.held, RenderData.heldPos, Card.isChara, RenderParam.liquidLv, Trait.NoHeldDir, RenderData.offset, owner, EClass.player, Card.Pref, Card.renderer, RenderObject.renderSetting, Card.SetDir(), Card.SetRenderParam(), Card.sourceCard, Cell.sourceSurface, RenderObject.tempV, Card.trait, MeshPassParam.x, SourcePref.x, MeshPassParam.y, and MeshPassParam.z.
Referenced by Draw().
NextFrame()
override void CharaRenderer.NextFrame () inline virtual
Reimplemented from CardRenderer.
Definition at line 104 of file CharaRenderer.cs.
    {
        base.NextFrame();
        owner.idleTimer = RenderObject.animeSetting.idleTime;
    }
References RenderObject.animeSetting.
OnEnterScreen()
override void CharaRenderer.OnEnterScreen () inline virtual
Reimplemented from CardRenderer.
Definition at line 69 of file CharaRenderer.cs.
    {
        base.OnEnterScreen();
        if (!ignoreFirst)
        {
            first = true;
        }
        ignoreFirst = false;
        nextframeTimer = 0f;
        if (EClass.core.config.game.haltOnSpotEnemy && owner.ExistsOnMap && !EClass._zone.IsRegion && owner.IsHostile())
        {
            EClass.player.enemySpotted = true;
        }
    }
References EClass._zone, Core.config, EClass.core, Card.ExistsOnMap, first, CoreConfig.game, CoreConfig.GameConfig.haltOnSpotEnemy, ignoreFirst, Chara.IsHostile(), Spatial.IsRegion, nextframeTimer, and owner.
Refresh()
override void CharaRenderer.Refresh () inline virtual
Reimplemented from CardRenderer.
Definition at line 426 of file CharaRenderer.cs.
    {
    }
RefreshStateIcon()
override void CharaRenderer.RefreshStateIcon () inline virtual
Reimplemented from CardRenderer.
Definition at line 382 of file CharaRenderer.cs.
    {
        if (!isSynced)
        {
            return;
        }
        TCState tCState = GetTC<TCState>();
        MultiSprite stateIcon = owner.ai.GetStateIcon();
        if (stateIcon == null)
        {
            if ((bool)tCState)
            {
                RemoveTC(tCState);
            }
            return;
        }
        if (!tCState)
        {
            tCState = AddTC<TCState>(PoolManager.Spawn(EClass.core.refs.tcs.state));
        }
        tCState.SetSprite(stateIcon);
    }
References Chara.ai, EClass.core, AIAct.GetStateIcon(), RenderObject.isSynced, owner, Core.refs, CardRenderer.RemoveTC(), TCState.SetSprite(), PoolManager.Spawn(), CoreRef.TCs.state, and CoreRef.tcs.
SetFirst() [1/2]
override void CharaRenderer.SetFirst (bool first) inline virtual
Reimplemented from CardRenderer.
Definition at line 405 of file CharaRenderer.cs.
    {
        this.first = first;
        ignoreFirst = !first;
    }
References first, and ignoreFirst.
SetFirst() [2/2]
override void CharaRenderer.SetFirst (bool first, Vector3 pos) inline virtual
Reimplemented from CardRenderer.
Definition at line 411 of file CharaRenderer.cs.
    {
        this.first = first;
        ignoreFirst = !first;
        position = pos;
        if (owner.IsPC)
        {
            EClass.player.position = position;
        }
        movePoint.Set(owner.pos);
        step = 9999999;
        isMoving = false;
        moveTimer = 0f;
    }
References first, ignoreFirst, isMoving, Chara.IsPC, movePoint, moveTimer, owner, Card.pos, CardRenderer.position, Point.Set(), and step.
SetOwner()
override void CharaRenderer.SetOwner (Card c) inline virtual
Reimplemented from CardRenderer.
Definition at line 59 of file CharaRenderer.cs.
    {
        owner = c as Chara;
        if (pccData != null)
        {
            data = ((pccData.GetBodySet2().id == "unique") ? EClass.core.refs.renderers.pcc_L : EClass.core.refs.renderers.pcc);
        }
        base.SetOwner(c);
    }
References EClass.core, RenderObject.data, owner, CoreRef.Renderers.pcc, CoreRef.Renderers.pcc_L, pccData, Core.refs, and CoreRef.renderers.
Referenced by Chara._CreateRenderer().
UpdatePosition()
override void CharaRenderer.UpdatePosition (ref Vector3 destPos, RenderParam p) inline virtual
Reimplemented from CardRenderer.
Definition at line 110 of file CharaRenderer.cs.
    {
        bool isPC = owner.IsPC;
        int num = (isPC ? _animeFramePC : (hasActor ? _animeFramePCC : _animeFrame));
        bool flag = isPC || num >= 10;
        if (num == 0 || Scene.skipAnime || first || !data.animate || (owner.IsDeadOrSleeping && pccData != null && !owner.IsPC))
        {
            first = false;
            position = destPos;
            if (isPC)
            {
                EClass.player.position = position;
            }
            movePoint.Set(owner.pos);
            step = 9999999;
            isMoving = false;
            moveTimer = 0f;
            RefreshSprite();
            p.x = position.x;
            p.y = position.y;
            p.z = position.z;
            lastShadowFix = (lastShadowFix2 = p.shadowFix);
            return;
        }
        if (!owner.pos.Equals(movePoint))
        {
            if (RenderObject.gameSpeed > 1f)
            {
                p.shadowFix = (lastShadowFix = 0f);
            }
            else
            {
                p.shadowFix = (lastShadowFix = lastShadowFix2);
            }
            movePoint.Set(owner.pos);
            orgPos = position;
            actTime = owner.actTime;
            RefreshSprite();
            step = 1;
            if (!isMoving)
            {
                isMoving = true;
                nextframeTimer = (RenderObject.animeSetting.nextFrameInterval + actTime / 4f) / 2f;
            }
            moveTimer = 0f;
        }
        if (num < 100)
        {
            num = (int)((float)num / 0.3f * actTime);
        }
        float num2 = (actTime + ((!isPC && owner.IsPCParty) ? RenderObject.animeSetting.animeExtraTimeParty : RenderObject.animeSetting.animeExtraTime) * RenderObject.gameSpeed) / (float)num;
        moveTimer += RenderObject.gameDelta;
        if (step >= num)
        {
            if (position == destPos)
            {
                if (isMoving && isPC)
                {
                    EClass.player.position = position;
                }
                isMoving = false;
                moveTimer = 0f;
            }
            else if (!flag)
            {
                position = destPos;
            }
            else if (moveTimer >= num2)
            {
                int num3 = (int)(moveTimer / num2);
                moveTimer -= (float)num3 * num2;
                if (Vector3.Distance(position, destPos) < RenderObject.animeSetting.destRadius)
                {
                    position = destPos;
                    if (isMoving && isPC)
                    {
                        EClass.player.position = position;
                    }
                    isMoving = false;
                }
                else
                {
                    position.z = destPos.z;
                    Vector3 vector = Vector3.MoveTowards(position, destPos, (float)num3 * RenderObject.animeSetting.slowSpeed / (float)step);
                    position = vector;
                }
            }
            if (owner.idleTimer > 0f)
            {
                owner.idleTimer -= RenderObject.gameDelta;
                if (flag && owner.idleTimer <= 0f)
                {
                    IdleFrame();
                    nextframeTimer = 0f;
                }
            }
            p.x = position.x;
            p.y = position.y;
            p.z = position.z;
            lastShadowFix = (lastShadowFix2 = p.shadowFix);
            if (isPC)
            {
                CellDetail detail = EClass.pc.Cell.detail;
                if (detail == null || detail.anime == null)
                {
                    position.z = destPos.z;
                    Vector3 vector2 = Vector3.MoveTowards(position, destPos, 0.1f);
                    position = vector2;
                    EClass.player.position = Vector3.Lerp(EClass.player.position, position, 0.6f);
                }
            }
            return;
        }
        if (moveTimer >= num2)
        {
            int num4 = (int)(moveTimer / num2);
            step += num4;
            moveTimer -= (float)num4 * num2;
            if (step >= num)
            {
                step = num;
            }
        }
        owner.idleTimer = RenderObject.animeSetting.idleTime;
        float num5 = (float)step / (float)num;
        p.shadowFix = p.shadowFix * num5 + lastShadowFix * (1f - num5);
        lastShadowFix2 = p.shadowFix;
        Vector3 vector3 = orgPos + (destPos - orgPos) * num5 * ((flag && smoothmove) ? RenderObject.animeSetting.fixedMove : 1f);
        if (destPos.z < orgPos.z)
        {
            vector3.z = orgPos.z + (destPos.z - orgPos.z) * RenderObject.animeSetting.gradientZForward.Evaluate(num5);
        }
        else
        {
            vector3.z = orgPos.z + (destPos.z - orgPos.z) * RenderObject.animeSetting.gradientZBack.Evaluate(num5);
        }
        position = vector3;
        if (hasActor)
        {
            if (EClass.core.config.graphic.spriteFrameMode == 0)
            {
                nextframeTimer += RenderObject.gameDelta * 0.5f;
                float nextFrameInterval = RenderObject.animeSetting.nextFrameInterval;
                if (nextframeTimer > nextFrameInterval)
                {
                    if (owner.ai is AI_Trolley)
                    {
                        actor.IdleFrame();
                    }
                    else
                    {
                        actor.NextFrame();
                    }
                    nextframeTimer -= nextFrameInterval;
                }
            }
            else
            {
                nextframeTimer += RenderObject.gameDelta;
                float num6 = RenderObject.animeSetting.nextFrameInterval + actTime / 4f * (0.5f + RenderObject.gameSpeed / 2f);
                if (nextframeTimer > num6)
                {
                    if (owner.ai is AI_Trolley)
                    {
                        actor.IdleFrame();
                    }
                    else
                    {
                        actor.NextFrame();
                    }
                    nextframeTimer -= num6;
                }
            }
        }
        p.x = position.x;
        p.y = position.y;
        p.z = position.z;
        if (isPC)
        {
            EClass.player.position = vector3;
        }
        else if (!hasActor && num >= 5 && hopCurve != null)
        {
            p.y += hopCurve.Evaluate(num5) * RenderObject.animeSetting.hopStrength;
        }
    }
References _animeFrame, _animeFramePC, _animeFramePCC, CardRenderer.actor, Chara.actTime, actTime, Chara.ai, RenderData.animate, CellDetail.anime, RenderObject.animeSetting, Card.Cell, Core.config, EClass.core, RenderObject.data, Cell.detail, Point.Equals(), first, RenderObject.gameDelta, RenderObject.gameSpeed, CoreConfig.graphic, CardRenderer.hasActor, hopCurve, CardActor.IdleFrame(), CardRenderer.IdleFrame(), Chara.idleTimer, Chara.IsDeadOrSleeping, isMoving, Chara.IsPC, Chara.IsPCParty, lastShadowFix, lastShadowFix2, movePoint, moveTimer, CardActor.NextFrame(), nextframeTimer, orgPos, owner, EClass.pc, pccData, EClass.player, Card.pos, CardRenderer.position, Player.position, CardRenderer.RefreshSprite(), Point.Set(), RenderParam.shadowFix, Scene.skipAnime, smoothmove, CoreConfig.GraphicSetting.spriteFrameMode, and step.
Member Data Documentation
_animeFrame
int CharaRenderer._animeFrame static
Definition at line 37 of file CharaRenderer.cs.
Referenced by UpdatePosition().
_animeFramePC
int CharaRenderer._animeFramePC static
Definition at line 33 of file CharaRenderer.cs.
Referenced by UpdatePosition().
_animeFramePCC
int CharaRenderer._animeFramePCC static
Definition at line 35 of file CharaRenderer.cs.
Referenced by UpdatePosition().
actTime
float CharaRenderer.actTime = 0.3f private
Definition at line 23 of file CharaRenderer.cs.
Referenced by UpdatePosition().
first
bool CharaRenderer.first = true
Definition at line 13 of file CharaRenderer.cs.
Referenced by OnEnterScreen(), SetFirst(), and UpdatePosition().
hopCurve
AnimationCurve CharaRenderer.hopCurve
Definition at line 19 of file CharaRenderer.cs.
Referenced by UpdatePosition().
ignoreFirst
bool CharaRenderer.ignoreFirst
Definition at line 15 of file CharaRenderer.cs.
Referenced by OnEnterScreen(), and SetFirst().
isMoving
bool CharaRenderer.isMoving
Definition at line 31 of file CharaRenderer.cs.
Referenced by SetFirst(), and UpdatePosition().
lastShadowFix
float CharaRenderer.lastShadowFix private
Definition at line 25 of file CharaRenderer.cs.
Referenced by UpdatePosition().
lastShadowFix2
float CharaRenderer.lastShadowFix2 private
Definition at line 27 of file CharaRenderer.cs.
Referenced by UpdatePosition().
movePoint
Point CharaRenderer.movePoint = new Point()
Definition at line 17 of file CharaRenderer.cs.
Referenced by SetFirst(), and UpdatePosition().
moveTimer
float CharaRenderer.moveTimer private
Definition at line 9 of file CharaRenderer.cs.
Referenced by SetFirst(), and UpdatePosition().
nextframeTimer
float CharaRenderer.nextframeTimer private
Definition at line 11 of file CharaRenderer.cs.
Referenced by OnEnterScreen(), and UpdatePosition().
orgPos
Vector3 CharaRenderer.orgPos
Definition at line 7 of file CharaRenderer.cs.
Referenced by UpdatePosition().
owner
new Chara CharaRenderer.owner
Definition at line 5 of file CharaRenderer.cs.
Referenced by Draw(), DrawHat(), DrawHeld(), OnEnterScreen(), RefreshStateIcon(), SetFirst(), SetOwner(), and UpdatePosition().
pccData
PCCData CharaRenderer.pccData
Definition at line 21 of file CharaRenderer.cs.
Referenced by Chara._CreateRenderer(), DrawHat(), SetOwner(), and UpdatePosition().
smoothmove
bool CharaRenderer.smoothmove static
Definition at line 39 of file CharaRenderer.cs.
Referenced by UpdatePosition().
step
int CharaRenderer.step
Definition at line 29 of file CharaRenderer.cs.
Referenced by SetFirst(), and UpdatePosition().
Property Documentation
currentDir
int CharaRenderer.currentDir get
Definition at line 41 of file CharaRenderer.cs.
    {
        get
        {
            if (!hasActor)
            {
                if (!owner.flipX)
                {
                    return 1;
                }
                return 0;
            }
            return actor.currentDir;
        }
    }
Referenced by DrawHat(), and DrawHeld().
IsMoving
override bool CharaRenderer.IsMoving get
Definition at line 57 of file CharaRenderer.cs.
The documentation for this class was generated from the following file:
Elin/CharaRenderer.cs