Elin Decompiled Documentation: Layer Class Reference
Layer Class Reference
Classes
class Option
Public Member Functions
virtual string GetTextHeader (Window window)
virtual bool HeaderIsListOf (int id)
virtual void Init ()
virtual void OnInit ()
virtual void OnAfterInit ()
virtual void ApplySkin ()
void ShowScreenLock (string id)
void UpdateInput ()
virtual void OnUpdateInput ()
virtual void OnRightClick ()
virtual bool OnBack ()
virtual void OnChangeLayer ()
virtual void OnCreate ()
void _AddLayer (string id)
Layer AddLayer (string id)
T AddLayer< T > ()
T AddLayer< T > (string id)
T AddLayerDontCloseOthers< T > ()
Layer AddLayerDontCloseOthers (Layer l)
T GetOrAddLayer< T > ()
virtual void OnBeforeAddLayer ()
virtual void OnAfterAddLayer ()
Layer AddLayer (Layer l)
void ToggleLayer (string id)
T ToggleLayer< T > (string id=null)
void WaitAndClose ()
void OnClickClose ()
virtual void Close ()
void CloseLayers ()
void RemoveLayers (bool removeImportant=false)
bool RemoveLayer< T > ()
void RemoveLayer (Layer l)
virtual void OnKill ()
Layer SetOnKill (Action action)
void DisableClose ()
void Delay (float duration=0.05f)
Layer SetDelay (float d)
Layer GetLayer (string id)
T GetLayer< T > (bool fromTop=false)
Layer GetTopLayer ()
void SwitchContent (int idWindow, int i)
virtual void OnSwitchContent (Window window)
Layer SetTitles (string langList, string idHeaderRow=null)
bool IsBlockWidgetClick ()
bool IsHideHud ()
bool IsAllowGeneralInput ()
bool IsUseBlur ()
bool IsPointerOnLayer ()
void ApplySkin ()
Static Public Member Functions
static T Create< T > ()
static T Create< T > (string path)
static Layer Create (string path)
Public Attributes
Option option
UnityEvent onKill
Anime animeIn
Anime animeOut
bool closeOthers
bool defaultActionMode = true
Button screenLock
Layer parent
string idLayer
List< Layer > layers = new List<Layer>()
Vector2 lastParentPos
List< Window > windows = new List<Window>()
string langHint
Static Public Attributes
static int skipInput
static bool closeOnRightClick
static bool rightClicked
static bool cancelKeyDown
static bool ignoreSounds
static Transform blurStopInstance
static string[] searchPath = new string[3] { "Layer", "Layer/Dialog", "Layer/LayerHome" }
Protected Member Functions
virtual void Awake ()
virtual void _Close ()
virtual void Kill ()
Protected Attributes
RectTransform _rect
bool isDestroyed
Properties
Layer TopLayer [get]
string uid [get]
virtual RectTransform rectLayers [get]
virtual bool blockWidgetClick [get]
Private Member Functions
void _RemoveLayer (Layer l)
Detailed Description
Definition at line 8 of file Layer.cs.
Member Function Documentation
_AddLayer()
void Layer._AddLayer (string id) inline
Definition at line 332 of file Layer.cs.
    {
        ToggleLayer(id);
    }
References ToggleLayer().
_Close()
virtual void Layer._Close () inline protected virtual
Reimplemented in ELayer.
Definition at line 475 of file Layer.cs.
    {
        if ((bool)parent)
        {
            parent.RemoveLayer(this);
        }
        else
        {
            Kill();
        }
        skipInput = 2;
    }
References Kill(), parent, RemoveLayer(), and skipInput.
Referenced by Close().
_RemoveLayer()
void Layer._RemoveLayer (Layer l) inline private
Definition at line 525 of file Layer.cs.
    {
        l.Kill();
        layers.Remove(l);
        if (layers.Count > 0)
        {
            Layer layer = layers.LastItem();
            if (!layer.isDestroyed)
            {
                CanvasGroup component = layer.GetComponent<CanvasGroup>();
                if (layer.option.hideOnUnfocus && (bool)component)
                {
                    component.alpha = 1f;
                }
            }
        }
        OnChangeLayer();
    }
References Layer.Option.hideOnUnfocus, isDestroyed, Kill(), layers, OnChangeLayer(), and option.
Referenced by RemoveLayer().
AddLayer() [1/2]
Layer Layer.AddLayer (Layer l) inline
Definition at line 383 of file Layer.cs.
    {
        l.OnBeforeAddLayer();
        if (l.option.persist && l.isDestroyed)
        {
            l.isDestroyed = false;
            l.gameObject.SetActive(value: true);
            layers.Add(l);
            if (!ignoreSounds)
            {
                SoundManager.current.Play(l.option.soundActivate);
            }
            return l;
        }
        l.gameObject.SetActive(value: true);
        l.parent = this;
        l.transform.SetParent(rectLayers, worldPositionStays: false);
        l.Init();
        if (l.option.hideOthers)
        {
            foreach (Layer layer in layers)
            {
                if (layer.option.hideOnUnfocus)
                {
                    CanvasGroup canvasGroup = layer.gameObject.GetComponent<CanvasGroup>();
                    if (!canvasGroup)
                    {
                        canvasGroup = layer.gameObject.AddComponent<CanvasGroup>();
                    }
                    canvasGroup.alpha = 0f;
                }
            }
        }
        layers.Add(l);
        OnChangeLayer();
        l._rect.anchorMin = Vector2.zero;
        l._rect.anchorMax = Vector2.one;
        l._rect.anchoredPosition = Vector2.zero;
        l._rect.sizeDelta = Vector2.zero;
        l.OnAfterAddLayer();
        return l;
    }
References Layer.Option.hideOnUnfocus, Layer.Option.hideOthers, ignoreSounds, Init(), isDestroyed, layers, OnAfterAddLayer(), OnBeforeAddLayer(), OnChangeLayer(), option, Layer.Option.persist, rectLayers, and Layer.Option.soundActivate.
AddLayer() [2/2]
Layer Layer.AddLayer (string id) inline
Definition at line 337 of file Layer.cs.
    {
        return AddLayer(Create(id));
    }
References AddLayer(), and Create().
Referenced by AddLayer(), AddLayer< T >(), AddLayerDontCloseOthers(), AM_NewZone.OnActivate(), StickyGacha.OnClick(), StickyHomeReport.OnClick(), GridItemCard.OnClick(), TraitBook.OnRead(), TraitNewspaper.OnRead(), TraitBookResident.OnUse(), TraitEditPlaylist.OnUse(), TraitJukeBox.OnUse(), TraitPolicyBoard.OnUse(), TraitVendingMachine.OnUse(), ActQuickCraft.Perform(), ToggleLayer(), TraitDrawingPaper.TrySetAct(), TraitHoard.TrySetAct(), TraitMirror.TrySetAct(), TraitNewspaper.TrySetAct(), TraitQuestBoard.TrySetAct(), and TraitResearchBoard.TrySetAct().
AddLayer< T >() [1/2]
T Layer.AddLayer< T > () inline
Type Constraints
T : Layer
Definition at line 342 of file Layer.cs.
                                   : Layer
    {
        return AddLayer(typeof(T).Name) as T;
    }
References AddLayer().
Referenced by GetOrAddLayer< T >(), and ToggleLayer< T >().
AddLayer< T >() [2/2]
T Layer.AddLayer< T > (string id) inline
Type Constraints
T : Layer
Definition at line 347 of file Layer.cs.
                                            : Layer
    {
        return AddLayer(id.IsEmpty(typeof(T).Name)) as T;
    }
References AddLayer().
AddLayerDontCloseOthers()
Layer Layer.AddLayerDontCloseOthers (Layer l) inline
Definition at line 357 of file Layer.cs.
    {
        l.option.screenlockType = Option.ScreenlockType.Default;
        l.closeOthers = false;
        AddLayer(l);
        return l;
    }
References AddLayer().
Referenced by AddLayerDontCloseOthers< T >(), and LayerHire.Refresh().
AddLayerDontCloseOthers< T >()
T Layer.AddLayerDontCloseOthers< T > () inline
Type Constraints
T : Layer
Definition at line 352 of file Layer.cs.
                                                  : Layer
    {
        return AddLayerDontCloseOthers(Create<T>()) as T;
    }
References AddLayerDontCloseOthers(), and Create< T >().
ApplySkin()
virtual void Layer.ApplySkin () inline virtual
Implements IUISkin.
Definition at line 203 of file Layer.cs.
    {
    }
Referenced by Init().
Awake()
virtual void Layer.Awake () inline protected virtual
Reimplemented in LayerList, LayerShippingResult, and UI.
Definition at line 146 of file Layer.cs.
    {
        _rect = this.Rect();
        foreach (Window componentsInDirectChild in this.GetComponentsInDirectChildren<Window>())
        {
            windows.Add(componentsInDirectChild);
        }
        for (int i = 0; i < windows.Count; i++)
        {
            windows[i].windowIndex = i;
        }
        if (windows.Count > 1 && windows[0].transform.position.x < windows[1].transform.position.x)
        {
            windows[0].transform.SetAsLastSibling();
        }
    }
References _rect, and windows.
Close()
virtual void Layer.Close () inline virtual
Definition at line 463 of file Layer.cs.
    {
        if ((bool)animeOut)
        {
            animeOut.Play(rectLayers).OnComplete(_Close);
        }
        else
        {
            _Close();
        }
    }
References _Close(), animeOut, Anime.Play(), and rectLayers.
Referenced by Dialog.AddButton(), LayerSleep.Advance(), LayerPeople.Confirm(), ItemGachaResult.Confirm(), MiniGame.Deactivate(), LayerNewZone.Embark(), Dialog.Gift(), Dialog.InputName(), LayerDrama.LateUpdate(), LayerEditPlaylist.ListBGM.List(), Dialog.Ok(), OnBack(), AI_UseCrafter.OnCancel(), LayerFeedback.OnCancel(), BaseListPeople.OnClick(), LayerColorPicker.OnClickCancel(), OnClickClose(), LayerColorPicker.OnClickConfirm(), LayerNewZone.OnClickExit(), Dialog.OnEnterInput(), LayerPixelPaint.OnInit(), InvOwnerDraglet.OnProcess(), LayerInventory.OnRightClick(), LayerFeedback.OnSubmit(), Dialog.OnUpdateInput(), LayerConsole.OnUpdateInput(), LayerInfo.OnUpdateInput(), LayerInventory.OnUpdateInput(), LayerMiniGame.OnUpdateInput(), LayerPause.OnUpdateInput(), LayerSkinDeco.OnUpdateInput(), Dialog.Recipe(), LayerCollectible.Refresh(), LayerTravel.Refresh(), LayerQuestBoard.RefreshQuest(), LayerFaith.RefreshSlots(), LayerPixelPaint.SetCanvas(), LayerList.SetList2< TValue >(), LayerList.SetStringList(), LayerList.Show(), LayerWorldSetting.StartGame(), Dialog.TryWarn(), Dialog.Update(), LayerProgress.Update(), UIBook.Update(), LayerSleep.Wait(), WaitAndClose(), LayerCraft.WaitUntilIdle(), and Dialog.YesNo().
CloseLayers()
void Layer.CloseLayers () inline
Definition at line 488 of file Layer.cs.
    {
        for (int num = layers.Count - 1; num >= 0; num--)
        {
            layers[num].Close();
        }
    }
References layers.
Create()
static Layer Layer.Create (string path) inline static
Definition at line 299 of file Layer.cs.
    {
        Layer layer = null;
        string text = path.Split('/').LastItem();
        string[] array = searchPath;
        foreach (string text2 in array)
        {
            layer = Resources.Load<Layer>("UI/" + text2 + "/" + path);
            if (!layer)
            {
                layer = Resources.Load<Layer>("UI/" + text2 + "/" + path + "/" + text);
            }
            if ((bool)layer)
            {
                break;
            }
        }
        if (!layer)
        {
            Debug.Log(path + " --- " + text);
        }
        layer = UnityEngine.Object.Instantiate(layer);
        Layer layer2 = layer;
        string text4 = (layer.name = text);
        layer2.idLayer = text4;
        layer.OnCreate();
        return layer;
    }
References Debug, OnCreate(), and searchPath.
Referenced by Dialog._Confetti(), LayerInventory._Create(), LayerDrama.Activate(), LayerDrama.ActivateNerun(), AddLayer(), Dialog.Choice(), LayerPeople.Create(), Create< T >(), Dialog.CreateNarration(), Dialog.Gift(), Dialog.InputName(), Dialog.Keymap(), Dialog.List< TValue >(), Dialog.Ok(), LayerGacha.PlayGacha(), Dialog.Recipe(), Dialog.TryWarn(), and Dialog.YesNo().
Create< T >() [1/2]
static T Layer.Create< T > () inline static
Type Constraints
T : Layer
Definition at line 289 of file Layer.cs.
                                        : Layer
    {
        return Create(typeof(T).Name) as T;
    }
References Create().
Referenced by AddLayerDontCloseOthers< T >().
Create< T >() [2/2]
static T Layer.Create< T > (string path) inline static
Type Constraints
T : Layer
Definition at line 294 of file Layer.cs.
                                                   : Layer
    {
        return Create(path) as T;
    }
References Create().
Delay()
void Layer.Delay (float duration = 0::05f) inline
Definition at line 597 of file Layer.cs.
    {
        foreach (Window window in windows)
        {
            window.setting.anime = null;
        }
        _rect.anchoredPosition = new Vector2(10000f, 10000f);
        TweenUtil.Tween(0.1f, delegate
        {
            BaseCore.Instance.WaitForEndOfFrame(delegate
            {
                if ((bool)this && (bool)base.gameObject)
                {
                    _rect.anchoredPosition = new Vector2(0f, 0f);
                    foreach (Window window2 in windows)
                    {
                        window2.ClampToScreen();
                    }
                    UIButton.TryShowTip();
                }
            });
        });
    }
References BaseCore.Instance, UIButton.TryShowTip(), BaseCore.WaitForEndOfFrame(), and windows.
Referenced by ActionMode.DoFunc(), and UI.ToggleAbility().
DisableClose()
void Layer.DisableClose () inline
Definition at line 588 of file Layer.cs.
    {
        option.canClose = false;
        foreach (Window window in windows)
        {
            window.buttonClose.SetActive(enable: false);
        }
    }
References Window.buttonClose, and windows.
GetLayer()
Layer Layer.GetLayer (string id) inline
Definition at line 632 of file Layer.cs.
    {
        foreach (Layer layer in layers)
        {
            if (layer.idLayer == id)
            {
                return layer;
            }
        }
        return null;
    }
References idLayer.
Referenced by InvOwnerHotbar.OnClick(), and ToggleLayer().
GetLayer< T >()
T Layer.GetLayer< T > (bool fromTop = false) inline
Type Constraints
T : Layer
Definition at line 644 of file Layer.cs.
                                                       : Layer
    {
        if (fromTop)
        {
            for (int num = layers.Count - 1; num >= 0; num--)
            {
                Layer layer = layers[num];
                if (layer is T)
                {
                    return layer as T;
                }
            }
        }
        else
        {
            foreach (Layer layer2 in layers)
            {
                if (layer2 is T)
                {
                    return layer2 as T;
                }
            }
        }
        return null;
    }
Referenced by GetOrAddLayer< T >(), and ToggleLayer< T >().
GetOrAddLayer< T >()
T Layer.GetOrAddLayer< T > () inline
Type Constraints
T : Layer
Definition at line 365 of file Layer.cs.
                                        : Layer
    {
        T val = GetLayer<T>();
        if (!val)
        {
            val = AddLayer<T>();
        }
        return val;
    }
References AddLayer< T >(), and GetLayer< T >().
GetTextHeader()
virtual string Layer.GetTextHeader (Window window) inline virtual
Reimplemented in LayerConfig, and LayerCraft.
Definition at line 131 of file Layer.cs.
    {
        string text = (window.CurrentTab?.idLang ?? window.setting.textCaption).lang();
        if (!HeaderIsListOf(window.idTab))
        {
            return text;
        }
        return "_listOf".lang(text);
    }
References Window.CurrentTab, HeaderIsListOf(), Window.idTab, Window.setting, and Window.Setting.textCaption.
Referenced by ContentFaction.OnSwitchContent(), and Window.SwitchContent().
GetTopLayer()
Layer Layer.GetTopLayer () inline
Definition at line 670 of file Layer.cs.
    {
        if (layers.Count > 0)
        {
            return layers.LastItem().GetTopLayer();
        }
        return this;
    }
References GetTopLayer().
Referenced by GetTopLayer().
HeaderIsListOf()
virtual bool Layer.HeaderIsListOf (int id) inline virtual
Reimplemented in LayerFactions, LayerHome, LayerInventory, LayerJournal, LayerLocation, and LayerPeople.
Definition at line 141 of file Layer.cs.
    {
        return false;
    }
Referenced by GetTextHeader().
Init()
virtual void Layer.Init () inline virtual
Reimplemented in ELayer.
Definition at line 163 of file Layer.cs.
    {
        if (option.screenlockType != Option.ScreenlockType.None && !screenLock)
        {
            ShowScreenLock(option.screenlockType.ToString());
        }
        OnInit();
        for (int i = 0; i < windows.Count; i++)
        {
            windows[i].Init(this);
        }
        ApplySkin();
        OnAfterInit();
        SoundManager.current.Play(option.soundActivate);
        if ((bool)animeIn)
        {
            animeIn.Play(rectLayers);
        }
        if ((bool)option.bgm)
        {
            SoundManager.current.PlayBGM(option.bgm);
        }
        if ((bool)option.playlist)
        {
            SoundManager.current.SwitchPlaylist(option.playlist);
        }
        if (option.rebuildLayout)
        {
            this.RebuildLayout(recursive: true);
        }
    }
References animeIn, ApplySkin(), Layer.Option.bgm, OnAfterInit(), OnInit(), option, Anime.Play(), Layer.Option.playlist, Layer.Option.rebuildLayout, rectLayers, screenLock, Layer.Option.screenlockType, ShowScreenLock(), Layer.Option.soundActivate, and windows.
Referenced by AddLayer(), and Widget.AddLayer().
IsAllowGeneralInput()
bool Layer.IsAllowGeneralInput () inline
Definition at line 718 of file Layer.cs.
    {
        foreach (Layer layer in layers)
        {
            if (!layer.IsAllowGeneralInput())
            {
                return false;
            }
        }
        return option.allowGeneralInput;
    }
References Layer.Option.allowGeneralInput, and IsAllowGeneralInput().
Referenced by IsAllowGeneralInput().
IsBlockWidgetClick()
bool Layer.IsBlockWidgetClick () inline
Definition at line 694 of file Layer.cs.
    {
        foreach (Layer layer in layers)
        {
            if (layer.blockWidgetClick)
            {
                return true;
            }
        }
        return blockWidgetClick;
    }
References blockWidgetClick.
IsHideHud()
bool Layer.IsHideHud () inline
Definition at line 706 of file Layer.cs.
    {
        foreach (Layer layer in layers)
        {
            if (layer.IsHideHud())
            {
                return true;
            }
        }
        return option.hideHud;
    }
References Layer.Option.hideHud, and IsHideHud().
Referenced by IsHideHud().
IsPointerOnLayer()
bool Layer.IsPointerOnLayer () inline
Definition at line 746 of file Layer.cs.
    {
        foreach (GameObject item in InputModuleEX.GetPointerEventData().hovered)
        {
            if (item.GetComponentInParent<Layer>() == this)
            {
                return true;
            }
        }
        return false;
    }
References InputModuleEX.GetPointerEventData(), and item.
IsUseBlur()
bool Layer.IsUseBlur () inline
Definition at line 730 of file Layer.cs.
    {
        if ((bool)blurStopInstance)
        {
            return false;
        }
        foreach (Layer layer in layers)
        {
            if (layer.IsUseBlur())
            {
                return true;
            }
        }
        return option.blur;
    }
References Layer.Option.blur, and IsUseBlur().
Referenced by IsUseBlur(), and UI.OnUpdate().
Kill()
virtual void Layer.Kill () inline protected virtual
Reimplemented in ELayer.
Definition at line 544 of file Layer.cs.
    {
        if (isDestroyed || base.gameObject == null)
        {
            return;
        }
        isDestroyed = true;
        foreach (Layer layer in layers)
        {
            layer.Kill();
        }
        if (windows.Count > 0)
        {
            CursorSystem.SetCursor();
            foreach (Window window in windows)
            {
                window.OnKill();
            }
        }
        OnKill();
        onKill.Invoke();
        if (option.persist)
        {
            base.gameObject.SetActive(value: false);
        }
        else
        {
            UnityEngine.Object.DestroyImmediate(base.gameObject);
        }
    }
References isDestroyed, Kill(), layers, onKill, OnKill(), Window.OnKill(), option, Layer.Option.persist, CursorSystem.SetCursor(), and windows.
Referenced by _Close(), _RemoveLayer(), and Kill().
OnAfterAddLayer()
virtual void Layer.OnAfterAddLayer () inline virtual
Reimplemented in ELayer, LayerEditBio, and LayerEmbark.
Definition at line 379 of file Layer.cs.
    {
    }
Referenced by AddLayer(), and Widget.AddLayer().
OnAfterInit()
virtual void Layer.OnAfterInit () inline virtual
Reimplemented in Dialog, LayerCollectible, LayerConsole, LayerCraft, LayerGacha, LayerHelp, LayerHire, LayerHoard, LayerInfo, LayerInventory, LayerMiniGame, and LayerSleep.
Definition at line 199 of file Layer.cs.
    {
    }
Referenced by Init().
OnBack()
virtual bool Layer.OnBack () inline virtual
Reimplemented in LayerColorPicker, LayerEmbark, and LayerMiniGame.
Definition at line 267 of file Layer.cs.
    {
        if (layers.Count > 0)
        {
            return layers.LastItem().OnBack();
        }
        if (!parent)
        {
            return false;
        }
        if (option.canClose)
        {
            Close();
            return true;
        }
        return false;
    }
References Layer.Option.canClose, Close(), layers, option, and parent.
Referenced by OnRightClick(), and UpdateInput().
OnBeforeAddLayer()
virtual void Layer.OnBeforeAddLayer () inline virtual
Reimplemented in ELayer, and LayerConfig.
Definition at line 375 of file Layer.cs.
    {
    }
Referenced by AddLayer(), and Widget.AddLayer().
OnChangeLayer()
virtual void Layer.OnChangeLayer () inline virtual
Reimplemented in UI.
Definition at line 285 of file Layer.cs.
    {
    }
Referenced by _RemoveLayer(), and AddLayer().
OnClickClose()
void Layer.OnClickClose () inline
Definition at line 455 of file Layer.cs.
    {
        if (!BaseCore.BlockInput())
        {
            Close();
        }
    }
References BaseCore.BlockInput, and Close().
Referenced by Window.Close().
OnCreate()
virtual void Layer.OnCreate () inline virtual
Definition at line 328 of file Layer.cs.
    {
    }
Referenced by Create().
OnInit()
virtual void Layer.OnInit () inline virtual
Reimplemented in LayerAbility, LayerArea, LayerConfig, LayerCraftFloat, LayerDrama, LayerEditHouse, LayerEditPlaylist, LayerEquip, LayerFeedback, LayerGlobalMap, LayerHelp, LayerHome, LayerHomeReport, LayerInteraction, LayerInventory, LayerList, LayerMapList, LayerMod, LayerNewspaper, LayerNewZone, LayerPeople, LayerPixelPaint, LayerPolicy, LayerQuestBoard, LayerQuickMenu, LayerResource, LayerSkinDeco, LayerTech, LayerTextureViewer, LayerTitle, LayerTravel, LayerUploader, LayerWidget, and LayerWorldSetting.
Definition at line 195 of file Layer.cs.
    {
    }
Referenced by Init().
OnKill()
virtual void Layer.OnKill () inline virtual
Reimplemented in Dialog, LayerArea, LayerColorPicker, LayerConfig, LayerConsole, LayerCraft, LayerDragGrid, LayerDrama, LayerEditHouse, LayerEditPCC, LayerEditPlaylist, LayerEmbark, LayerGacha, LayerHire, LayerHoard, LayerImage, LayerInfo, LayerInteraction, LayerInventory, LayerList, LayerMiniGame, LayerMod, LayerNewZone, LayerPause, LayerPeople, LayerQuestBoard, LayerRegisterHotbar, LayerResource, LayerSkinDeco, LayerTitle, LayerTravel, LayerUploader, LayerWidget, and LayerWorldSetting.
Definition at line 575 of file Layer.cs.
    {
    }
Referenced by Kill().
OnRightClick()
virtual void Layer.OnRightClick () inline virtual
Reimplemented in ELayer, LayerDragGrid, LayerHelp, and LayerInventory.
Definition at line 259 of file Layer.cs.
    {
        if (closeOnRightClick)
        {
            OnBack();
        }
    }
References closeOnRightClick, and OnBack().
Referenced by UpdateInput().
OnSwitchContent()
virtual void Layer.OnSwitchContent (Window window) inline virtual
Reimplemented in LayerAbility, LayerAdmin, LayerConfig, LayerCraftFloat, LayerDebug, LayerEditPlaylist, LayerFactions, LayerHome, LayerJournal, LayerLocation, LayerPeople, LayerQuestBoard, LayerTextureViewer, and LayerTravel.
Definition at line 684 of file Layer.cs.
    {
    }
Referenced by Window.SwitchContent().
OnUpdateInput()
virtual void Layer.OnUpdateInput () inline virtual
Reimplemented in Dialog, LayerAbility, LayerConsole, LayerCover, LayerDragGrid, LayerDrama, LayerImage, LayerInfo, LayerInspect, LayerInteraction, LayerInventory, LayerList, LayerMiniGame, LayerPause, LayerQuickMenu, LayerSkinDeco, and LayerWidget.
Definition at line 255 of file Layer.cs.
    {
    }
Referenced by UpdateInput().
RemoveLayer()
void Layer.RemoveLayer (Layer l) inline
Definition at line 520 of file Layer.cs.
    {
        _RemoveLayer(l);
    }
References _RemoveLayer().
Referenced by _Close(), RemoveLayer< T >(), RemoveLayers(), ToggleLayer(), and ToggleLayer< T >().
RemoveLayer< T >()
bool Layer.RemoveLayer< T > () inline
Definition at line 507 of file Layer.cs.
    {
        for (int num = layers.Count - 1; num >= 0; num--)
        {
            if (layers[num] is T)
            {
                RemoveLayer(layers[num]);
                return true;
            }
        }
        return false;
    }
References layers, and RemoveLayer().
RemoveLayers()
void Layer.RemoveLayers (bool removeImportant = false) inline
Definition at line 496 of file Layer.cs.
    {
        for (int num = layers.Count - 1; num >= 0; num--)
        {
            if (removeImportant || (!layers[num].option.important && !layers[num].option.persist))
            {
                RemoveLayer(layers[num]);
            }
        }
    }
References Layer.Option.important, layers, option, and RemoveLayer().
Referenced by UI.OnClickAction(), and UI.OnKillGame().
SetDelay()
Layer Layer.SetDelay (float d) inline
Definition at line 621 of file Layer.cs.
    {
        CanvasGroup cg = GetComponent<CanvasGroup>() ?? base.gameObject.AddComponent<CanvasGroup>();
        cg.alpha = 0f;
        TweenUtil.Tween(d, null, delegate
        {
            cg.alpha = 1f;
        });
        return this;
    }
SetOnKill()
Layer Layer.SetOnKill (Action action) inline
Definition at line 579 of file Layer.cs.
    {
        onKill.AddListener(delegate
        {
            action();
        });
        return this;
    }
References onKill.
Referenced by AM_Adv._OnUpdateInput(), LayerEditPCC.Activate(), MeetingManager.CallNext(), TraitCrafter.Craft(), LayerInventory.CreateBuy(), Dialog.Ok(), BaseListPeople.OnClick(), ContentConfigInput.OnInstantiate(), TraitStoryBookHome.OnRead(), Game.Pause(), LayerGacha.PlayGacha(), Dialog.Recipe(), LayerCraft.SetFactory(), Meeting.Start(), and Dialog.TryWarn().
SetTitles()
Layer Layer.SetTitles (string langList, string idHeaderRow = null) inline
Definition at line 688 of file Layer.cs.
    {
        windows[0].SetTitles(langList, idHeaderRow);
        return this;
    }
References SetTitles().
Referenced by UICharaMaker.ListAlias(), UICharaMaker.ListModes(), and SetTitles().
ShowScreenLock()
void Layer.ShowScreenLock (string id) inline
Definition at line 207 of file Layer.cs.
    {
        if ((bool)screenLock)
        {
            UnityEngine.Object.DestroyImmediate(screenLock.gameObject);
        }
        screenLock = Util.Instantiate<Button>("UI/Screenlock" + id, rectLayers);
        screenLock.transform.SetAsFirstSibling();
    }
References Button, rectLayers, screenLock, and Util.
Referenced by Init(), and DramaManager.ParseLine().
SwitchContent()
void Layer.SwitchContent (int idWindow, int i) inline
Definition at line 679 of file Layer.cs.
    {
        windows[idWindow].SwitchContent(i);
    }
ToggleLayer()
void Layer.ToggleLayer (string id) inline
Definition at line 426 of file Layer.cs.
    {
        Layer layer = GetLayer(id);
        if ((bool)layer)
        {
            RemoveLayer(layer);
        }
        else
        {
            AddLayer(id);
        }
    }
References AddLayer(), GetLayer(), and RemoveLayer().
Referenced by _AddLayer(), TraitScrollMapTreasure.OnUse(), LayerHelp.Toggle(), TraitHomeBoard.TrySetAct(), and TraitResidentBoard.TrySetAct().
ToggleLayer< T >()
T Layer.ToggleLayer< T > (string id = null) inline
Type Constraints
T : Layer
Definition at line 439 of file Layer.cs.
                                                      : Layer
    {
        T layer = GetLayer<T>();
        if ((bool)layer)
        {
            RemoveLayer(layer);
            return null;
        }
        return AddLayer<T>(id);
    }
References AddLayer< T >(), GetLayer< T >(), and RemoveLayer().
UpdateInput()
void Layer.UpdateInput () inline
Definition at line 217 of file Layer.cs.
    {
        if (skipInput > 0 || UIContextMenuManager.Instance.isActive)
        {
            skipInput--;
        }
        else if (layers.Count > 0)
        {
            layers.LastItem().UpdateInput();
        }
        else if ((EInput.leftMouse.down || (EInput.rightMouse.down && option.screenClickCloseRight)) && (((bool)screenLock && InputModuleEX.IsPointerOver(screenLock)) || (!InputModuleEX.IsPointerOverRoot(this) && !InputModuleEX.GetComponentOf<RectTransform>())))
        {
            if ((EInput.leftMouse.down && option.screenClickClose) || (EInput.rightMouse.down && option.screenClickCloseRight))
            {
                OnBack();
            }
        }
        else if (rightClicked || cancelKeyDown)
        {
            if ((bool)UIDropdown.activeInstance)
            {
                UIDropdown.activeInstance.Hide();
            }
            else if (rightClicked)
            {
                OnRightClick();
            }
            else
            {
                OnBack();
            }
        }
        else
        {
            OnUpdateInput();
        }
    }
References UIDropdown.activeInstance, cancelKeyDown, ButtonState.down, UIContextMenuManager.Instance, UIContextMenuManager.isActive, InputModuleEX.IsPointerOver(), InputModuleEX.IsPointerOverRoot(), layers, EInput.leftMouse, OnBack(), OnRightClick(), OnUpdateInput(), option, rightClicked, EInput.rightMouse, Layer.Option.screenClickClose, Layer.Option.screenClickCloseRight, screenLock, and skipInput.
WaitAndClose()
void Layer.WaitAndClose () inline
Definition at line 450 of file Layer.cs.
    {
        BaseCore.Instance.WaitForEndOfFrame(Close);
    }
References Close(), BaseCore.Instance, and BaseCore.WaitForEndOfFrame().
Member Data Documentation
_rect
RectTransform Layer._rect protected
Definition at line 96 of file Layer.cs.
Referenced by Awake().
animeIn
Anime Layer.animeIn
Definition at line 88 of file Layer.cs.
Referenced by Init().
animeOut
Anime Layer.animeOut
Definition at line 90 of file Layer.cs.
Referenced by Close().
blurStopInstance
Transform Layer.blurStopInstance static
Definition at line 82 of file Layer.cs.
cancelKeyDown
bool Layer.cancelKeyDown static
Definition at line 78 of file Layer.cs.
Referenced by UpdateInput().
closeOnRightClick
bool Layer.closeOnRightClick static
Definition at line 74 of file Layer.cs.
Referenced by OnRightClick().
closeOthers
bool Layer.closeOthers
Definition at line 92 of file Layer.cs.
Referenced by ELayer.Init().
defaultActionMode
bool Layer.defaultActionMode = true
Definition at line 94 of file Layer.cs.
Referenced by ELayer.OnBeforeAddLayer().
idLayer
string Layer.idLayer
Definition at line 107 of file Layer.cs.
Referenced by GetLayer().
ignoreSounds
bool Layer.ignoreSounds static
Definition at line 80 of file Layer.cs.
Referenced by AddLayer().
isDestroyed
bool Layer.isDestroyed protected
Definition at line 98 of file Layer.cs.
Referenced by _RemoveLayer(), AddLayer(), ELayer.Kill(), Kill(), LayerDrama.LateUpdate(), LayerNewspaper.RefreshChat(), LayerNewspaper.RefreshVote(), and LayerCraft.SetFactory().
langHint
string Layer.langHint
Definition at line 119 of file Layer.cs.
Referenced by LayerPeople.Create< T >(), LayerPeople.CreateSelect(), LayerPeople.OnInit(), and ELayer.TryShowHint().
lastParentPos
Vector2 Layer.lastParentPos
Definition at line 113 of file Layer.cs.
layers
List<Layer> Layer.layers = new List<Layer>()
Definition at line 110 of file Layer.cs.
Referenced by _RemoveLayer(), AddLayer(), UI.CheckWindowOrder(), CloseLayers(), Kill(), AM_ViewMap.OnActivate(), OnBack(), UI.OnChangeLayer(), AM_ViewMap.OnDeactivate(), UI.OnUpdate(), RemoveLayer< T >(), RemoveLayers(), TraitContainer.TryOpen(), and UpdateInput().
onKill
UnityEvent Layer.onKill
Definition at line 86 of file Layer.cs.
Referenced by Kill(), LayerEditBio.SetChara(), LayerCover.SetDuration(), and SetOnKill().
option
Option Layer.option
Definition at line 84 of file Layer.cs.
Referenced by ELayer._Close(), _RemoveLayer(), AddLayer(), Init(), Window.Init(), ELayer.Kill(), Kill(), OnBack(), UI.OnChangeLayer(), Dialog.OnUpdateInput(), RemoveLayers(), ELayer.TryShowHint(), Dialog.Update(), and UpdateInput().
parent
Layer Layer.parent
Definition at line 104 of file Layer.cs.
Referenced by _Close(), UIDynamicList.List(), and OnBack().
rightClicked
bool Layer.rightClicked static
Definition at line 76 of file Layer.cs.
Referenced by UpdateInput().
screenLock
Button Layer.screenLock
Definition at line 101 of file Layer.cs.
Referenced by Init(), ShowScreenLock(), and UpdateInput().
searchPath
string [] Layer.searchPath = new string[3] { "Layer", "Layer/Dialog", "Layer/LayerHome" } static
Definition at line 121 of file Layer.cs.
Referenced by Create().
skipInput
int Layer.skipInput static
Definition at line 72 of file Layer.cs.
Referenced by _Close(), and UpdateInput().
windows
List<Window> Layer.windows = new List<Window>()
Definition at line 116 of file Layer.cs.
Referenced by LayerEditPortrait.Activate(), LayerEditPCC.Activate(), LayerEditPlaylist.Activate(), Widget.AddLayer(), Awake(), Window.BringToTop(), LayerInventory.CreateBuy(), LayerInventory.CreateContainer(), LayerInventory.CreateContainer< T >(), LayerInventory.CreateContainerAlly(), LayerInventory.CreateContainerPC(), LayerInventory.CreatePCBackpack(), Delay(), DisableClose(), ActionMode.DoFunc(), Init(), LayerLoadGame.Init(), Card.Inspect(), UIInspector.Inspect(), Kill(), Dialog.OnAfterInit(), LayerConfig.OnBeforeAddLayer(), WidgetExp.OnClick(), WidgetExpHome.OnClick(), BaseListPeople.OnClick(), LayerCraft.OnCompleteCraft(), LayerAbility.OnInit(), LayerConfig.OnInit(), LayerEditHouse.OnInit(), LayerEquip.OnInit(), LayerMod.OnInit(), LayerPixelPaint.OnInit(), LayerQuestBoard.OnInit(), LayerResource.OnInit(), LayerTextureViewer.OnInit(), ContentFaction.OnSwitchContent(), LayerAbility.OnSwitchContent(), LayerQuestBoard.OnSwitchContent(), Scene.OnUpdate(), LayerGacha.PlayGacha(), LayerEquip.Rebuild(), LayerTravel.Refresh(), LayerAbility.RefreshConfig(), LayerFactions.RefreshFactions(), LayerLoadGame.RefreshList(), LayerCraftFloat.RefreshSize(), LayerList.RefreshSize(), LayerTech.RefreshTech(), LayerLocation.RefreshZones(), LayerInfo.Resize(), LayerInfo.SetBlock(), LayerInfo.SetElement(), LayerCraft.SetFactory(), LayerInfo.SetFloor(), LayerList.SetHeader(), LayerInventory.SetInv(), LayerInfo.SetLiquid(), LayerInfo.SetObj(), LayerList.SetPivot(), LayerList.SetSize(), LayerInfo.SetThing(), LayerList.Show(), LayerJournal.SwitchPopulation(), UI.ToggleAbility(), ELayer.TryShowHelp(), LayerCraftFloat.Update(), and ActionMode.UpdateInput().
Property Documentation
blockWidgetClick
virtual bool Layer.blockWidgetClick get
Definition at line 129 of file Layer.cs.
Referenced by IsBlockWidgetClick().
rectLayers
virtual RectTransform Layer.rectLayers get
Definition at line 127 of file Layer.cs.
Referenced by AddLayer(), Close(), Init(), and ShowScreenLock().
TopLayer
Layer Layer.TopLayer get
Definition at line 123 of file Layer.cs.
Referenced by UI.OnChangeLayer().
uid
string Layer.uid get
Definition at line 125 of file Layer.cs.
Referenced by LayerRegisterHotbar.SetItem().
The documentation for this class was generated from the following file:
Elin/Plugins.UI/Layer.cs