Elin Decompiled Documentation: ConSleep Class Reference
ConSleep Class Reference
Public Member Functions
override int GetPhase ()
override void SetOwner (Chara _owner, bool onDeserialize=false)
override void OnBeforeStart ()
override void Tick ()
override void OnRemoved ()
Public Member Functions inherited from Condition
override BaseNotification CreateNotification ()
virtual void OnStacked (int p)
Condition SetPerfume (int duration=3)
override void Tick ()
virtual void OnCalculateFov (Fov fov, ref int radius, ref float power)
virtual void OnCreateFov (Fov fov)
override void OnValueChanged ()
void Kill (bool silent=false)
Public Member Functions inherited from BaseCondition
virtual bool CanStack (Condition c)
virtual bool TryMove (Point p)
void SetElement (int id)
void SetRefVal (int a, int b)
virtual Color GetSpriteColor ()
override string ToString ()
override string GetText ()
override int GetValue ()
override Color GetColor (Gradient g)
virtual void SetOwner (Chara _owner, bool onDeserialize=false)
SourceElement.Row GetElementSource (int i)
void Start ()
bool TryNullify (Condition c)
virtual void OnBeforeStart ()
virtual void OnStart ()
virtual void OnStartOrStack ()
virtual void PlayEffect ()
virtual void PlayEndEffect ()
virtual void OnRefresh ()
void SetPhase ()
bool IsNullPhase ()
override int GetPhase ()
void PhaseMsg (bool inc)
override string GetPhaseStr ()
virtual void Tick ()
void Mod (int a, bool force=false)
virtual void OnValueChanged ()
virtual void OnChangePhase (int lastPhase, int newPhase)
virtual void OnRemoved ()
virtual int EvaluatePower (int p)
virtual int EvaluateTurn (int p)
virtual BaseNotification CreateNotification ()
Element GetDefenseAttribute (Chara c=null)
override void _WriteNote (UINote n, bool asChild=false)
virtual void OnWriteNote (List< string > list)
virtual RendererReplacer GetRendererReplacer ()
Public Member Functions inherited from BaseStats
virtual Color GetColor (Gradient gradient)
virtual Color GetColor (SkinColorProfile c)
Color GetColor ()
virtual string GetText ()
virtual string GetPhaseStr ()
virtual int GetValue ()
virtual int GetSortVal ()
virtual Sprite GetSprite ()
virtual void SetText (UIText t, SkinColorProfile cols=null)
virtual int GetPhase ()
void PopText ()
virtual void WriteNote (UINote n, Action< UINote > onWriteNote=null)
virtual void _WriteNote (UINote n, bool asChild=false)
Static Public Member Functions
static void SuccubusVisit (Chara tg)
static void SuccubusSleep (Chara tg)
Static Public Member Functions inherited from Condition
static T Create< T > (int power=100, Action< T > onCreate=null)
static Condition Create (string alias, int power=100, Action< Condition > onCreate=null)
Static Public Member Functions inherited from EClass
static int rndSeed (int a, int seed)
static int rnd (long a)
static int rnd (int a)
static int curve (int a, int start, int step, int rate=75)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Public Attributes
bool succubusChecked
int pcSleep
Thing pcBed
Thing pcPillow
ItemPosition posBed
ItemPosition posPillow
bool pickup
bool slept
int uidRide
int uidParasite
Public Attributes inherited from BaseCondition
int[] _ints = new int[5]
int phase = -1
ElementContainer elements
Chara owner
Public Attributes inherited from BaseStats
int id
SourceStat.Row _source
Properties
override Emo2 EmoIcon [get]
override bool ConsumeTurn [get]
Properties inherited from Condition
virtual bool IsKilled [get]
virtual string TextDuration [get]
Properties inherited from BaseCondition
int value [get, set]
int power [get, set]
int refVal [get, set]
int refVal2 [get, set]
bool givenByPcParty [get, set]
bool isPerfume [get, set]
override Chara Owner [get]
virtual string Name [get]
virtual bool IsToggle [get]
virtual bool WillOverride [get]
virtual bool AllowMultipleInstance [get]
virtual bool ConsumeTurn [get]
virtual bool HasDuration [get]
virtual bool PreventRegen [get]
virtual bool ShouldRefresh [get]
virtual bool CancelAI [get]
virtual bool TimeBased [get]
virtual bool SyncRide [get]
virtual bool UseElements [get]
virtual int GainResistFactor [get]
virtual int P2 [get]
SourceElement.Row sourceElement [get]
virtual bool IsElemental [get]
virtual string RefString1 [get]
virtual bool CanManualRemove [get]
Properties inherited from BaseStats
SourceStat.Row source [get]
virtual Emo2 EmoIcon [get]
virtual ConditionType Type [get]
virtual string idSprite [get]
virtual bool ShowInWidget [get]
virtual Chara Owner [get]
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Additional Inherited Members
Static Public Attributes inherited from Condition
static bool ignoreEffect
Static Public Attributes inherited from BaseStats
static Chara CC
Static Public Attributes inherited from EClass
static Core core
Detailed Description
Definition at line 3 of file ConSleep.cs.
Member Function Documentation
GetPhase()
override int ConSleep.GetPhase () inline virtual
Reimplemented from BaseCondition.
Definition at line 38 of file ConSleep.cs.
    {
        return 0;
    }
OnBeforeStart()
override void ConSleep.OnBeforeStart () inline virtual
Reimplemented from BaseCondition.
Definition at line 53 of file ConSleep.cs.
    {
        TraitPillow traitPillow = owner.pos.FindThing<TraitPillow>();
        if (traitPillow != null)
        {
            owner.Say("pillow", owner, traitPillow.owner);
        }
    }
References Point.FindThing(), BaseCondition.owner, Trait.owner, Card.pos, and Card.Say().
OnRemoved()
override void ConSleep.OnRemoved () inline virtual
Reimplemented from BaseCondition.
Definition at line 228 of file ConSleep.cs.
    {
        owner.conSleep = null;
        owner.renderer.RefreshSprite();
        owner.renderer.SetFirst(first: true, owner.pos.PositionAuto());
        if (!owner.IsPC)
        {
            owner.sleepiness.Set(0);
            return;
        }
        if (owner.IsPC)
        {
            if (uidRide != 0)
            {
                Chara chara = EClass._map.FindChara(uidRide);
                if (chara != null)
                {
                    ActRide.Ride(EClass.pc, chara, parasite: false, talk: false);
                }
            }
            if (uidParasite != 0)
            {
                Chara chara2 = EClass._map.FindChara(uidParasite);
                if (chara2 != null)
                {
                    ActRide.Ride(EClass.pc, chara2, parasite: true, talk: false);
                }
            }
        }
        if (owner.isDead)
        {
            return;
        }
        TraitPillow traitPillow = (pcPillow?.trait as TraitPillow) ?? EClass.pc.pos.FindThing<TraitPillow>();
        if (pickup)
        {
            TryPick(pcBed, posBed);
            TryPick(pcPillow, posPillow);
        }
        if (slept)
        {
            Thing thing = EClass.pc.things.Find<TraitGrimoire>();
            if (thing != null && thing.c_lockLv == 0 && !EClass._zone.IsRegion)
            {
                foreach (Thing item in thing.things.List((Thing _t) => _t.trait is TraitSpellbook || _t.trait is TraitAncientbook || _t.id == "234"))
                {
                    TraitBaseSpellbook traitBaseSpellbook = item.trait as TraitBaseSpellbook;
                    if (item.trait is TraitAncientbook && item.isOn)
                    {
                        continue;
                    }
                    int c_charges = item.c_charges;
                    for (int i = 0; i < c_charges; i++)
                    {
                        if (EClass.pc.isDead)
{
                            return;
                        }
                        int num = traitBaseSpellbook.GetActDuration(EClass.pc) + 1;
                        bool flag = false;
                        for (int j = 0; j < num; j++)
{
                            if (!traitBaseSpellbook.TryProgress(new AIProgress
{
                                owner = EClass.pc
                            }))
{
                                flag = true;
                                if (!EClass.pc.isDead)
{
                                    break;
                                }
                                return;
                            }
                        }
                        if (!flag)
{
                            traitBaseSpellbook.OnRead(EClass.pc);
                        }
                    }
                }
            }
        }
        if (EClass.pc.isDead || !slept)
        {
            return;
        }
        EClass.player.recipes.OnSleep(traitPillow is TraitPillowEhekatl);
        EClass.player.DreamSpell();
        if (traitPillow is TraitPillowGod traitPillowGod)
        {
            traitPillowGod.Deity.Talk("morning");
        }
        foreach (Chara member in EClass.pc.party.members)
        {
            if (traitPillow is TraitPillowJure)
            {
                member.SAN.Mod(-15);
            }
        }
        if (EClass.player.karma < 80 && EClass.pc.HasElement(1270))
        {
            EClass.pc.SetFeat(1270, 0, msg: true);
        }
        if (EClass.player.karma > -80 && EClass.pc.HasElement(1271))
        {
            EClass.pc.SetFeat(1271, 0, msg: true);
        }
        Rand.SetSeed(EClass.game.seed + EClass.player.stats.days);
        if (EClass.player.karma >= 80)
        {
            if (EClass.rnd(EClass.debug.enable ? 1 : 5) == 0 && !EClass.pc.HasElement(1270))
            {
                EClass.pc.SetFeat(1270, 1, msg: true);
            }
        }
        else if (EClass.player.karma <= -80 && EClass.rnd(EClass.debug.enable ? 1 : 2) == 0 && !EClass.pc.HasElement(1271))
        {
            EClass.pc.SetFeat(1271, 1, msg: true);
        }
        Rand.SetSeed();
        static void TryPick(Thing t, ItemPosition pos)
        {
            if (t != null)
            {
                t = EClass._map.FindThing(t.uid);
                if (t != null && t.ExistsOnMap && !t.isNPCProperty)
                {
                    if (pos != null)
                    {
                        Card card = ((pos.uidContainer == EClass.pc.uid) ? ((Card)EClass.pc) : ((Card)EClass.pc.things.Find(pos.uidContainer)));
                        if (card != null)
{
                            EClass.pc.PlaySound("pick_thing");
                            EClass.pc.Say("pick_thing", EClass.pc, t);
                            t = card.AddThing(t, tryStack: false, pos.invX, pos.invY);
                            t.invX = pos.invX;
                            t.invY = pos.invY;
                            LayerInventory.SetDirty(t);
                            return;
                        }
                    }
                    EClass.pc.Pick(t);
                    LayerInventory.SetDirty(t);
                }
            }
        }
    }
References EClass._map, EClass._zone, Card.c_lockLv, card, Player.Stats.days, EClass.debug, Player.DreamSpell(), CoreDebug.enable, Card.ExistsOnMap, ThingContainer.Find(), Map.FindChara(), Map.FindThing(), Point.FindThing(), EClass.game, TraitBaseSpellbook.GetActDuration(), Card.HasElement(), Card.id, ItemPosition.invX, ItemPosition.invY, Chara.isDead, Card.isNPCProperty, Spatial.IsRegion, item, Player.karma, ThingContainer.List(), Party.members, Stats.Mod(), TraitBaseSpellbook.OnRead(), RecipeManager.OnSleep(), Chara.party, EClass.pc, Chara.Pick(), EClass.player, Card.PlaySound(), Card.pos, Player.recipes, ActRide.Ride(), EClass.rnd(), Chara.SAN, Card.Say(), Game.seed, LayerInventory.SetDirty(), Chara.SetFeat(), Rand.SetSeed(), Player.stats, Card.things, Card.trait, TraitBaseSpellbook.TryProgress(), Card.uid, and ItemPosition.uidContainer.
SetOwner()
override void ConSleep.SetOwner (Chara _owner, bool onDeserialize = false) inline virtual
Reimplemented from BaseCondition.
Definition at line 43 of file ConSleep.cs.
    {
        base.SetOwner(_owner);
        owner.conSleep = this;
        if (owner.renderer != null)
        {
            owner.renderer.RefreshSprite();
        }
    }
References BaseCondition.owner, CardRenderer.RefreshSprite(), and Card.renderer.
SuccubusSleep()
static void ConSleep.SuccubusSleep (Chara tg) inline static
Definition at line 212 of file ConSleep.cs.
    {
        EClass._map.charas.ForeachReverse(delegate(Chara c)
        {
            if (c.ai is AI_Fuck { IsRunning: not false } aI_Fuck && aI_Fuck.target == tg)
            {
                aI_Fuck.Finish();
                aI_Fuck.Cancel();
                if (!c.HasCondition<ConSleep>())
                {
                    c.AddCondition<ConSleep>(100 + EClass.rnd(100), force: true);
                }
            }
        });
    }
References EClass._map, Chara.ai, Map.charas, and AI_Fuck.target.
Referenced by Tick().
SuccubusVisit()
static void ConSleep.SuccubusVisit (Chara tg) inline static
Definition at line 172 of file ConSleep.cs.
    {
        if (tg.pos.IsInSpot<TraitPillowStrange>())
        {
            return;
        }
        foreach (Chara chara in EClass._map.charas)
        {
            if (chara == tg || chara.IsPC || chara.host != null || chara.IsDisabled || !chara.IsIdle || chara.Evalue(418) > 0 || tg.Evalue(418) > 0)
            {
                continue;
            }
            Thing thing = chara.things.Find<TraitDreamBug>();
            if ((!chara.HasElement(1216) && thing == null) || (tg.Evalue(418) == 0 && (EClass.rnd(3) != 0 || (tg.IsPC && thing == null && EClass.rnd(200) != 0))))
            {
                continue;
            }
            chara.Teleport(tg.pos);
            if (chara.Dist(tg.pos) > 2)
            {
                continue;
            }
            if (thing != null)
            {
                tg.Say("dreambug_teleport", chara, tg);
                thing.ModCharge(-1);
                if (thing.c_charges <= 0)
                {
                    tg.Say("dreambug_destroy", chara, thing);
                    thing.Destroy();
                }
            }
            chara.SetAI(new AI_Fuck
            {
                target = tg,
                succubus = true
            });
        }
    }
References EClass._map, Card.c_charges, Map.charas, Card.Destroy(), Card.Dist(), Card.Evalue(), ThingContainer.Find(), Card.HasElement(), Chara.host, Chara.IsDisabled, Chara.IsIdle, Chara.IsPC, Card.ModCharge(), Card.pos, EClass.rnd(), Chara.SetAI(), Card.Teleport(), and Card.things.
Referenced by Tick().
Tick()
override void ConSleep.Tick () inline virtual
Reimplemented from Condition.
Definition at line 62 of file ConSleep.cs.
    {
        if (!succubusChecked && EClass._zone.isStarted && (base.value > 50 || pcSleep != 0))
        {
            SuccubusVisit(owner);
            succubusChecked = true;
        }
        if (owner.IsPC && pcSleep > 0)
        {
            if (!EClass._zone.IsRegion)
            {
                if (EClass.pc.ride != null)
                {
                    uidRide = EClass.pc.ride.uid;
                    ActRide.Unride(EClass.pc, parasite: false, talk: false);
                }
                if (EClass.pc.parasite != null)
                {
                    uidParasite = EClass.pc.parasite.uid;
                    ActRide.Unride(EClass.pc, parasite: true, talk: false);
                }
            }
            pcSleep--;
            if (pcSleep != 0)
            {
                return;
            }
            int num = EClass.pc.sleepiness.GetPhase();
            int num2 = ((num >= 3) ? 12 : ((num >= 2) ? 10 : ((num >= 1) ? 7 : 5)));
            num2 += EClass.pc.stamina.GetPhase() switch
            {
                2 => 2,
                1 => 3,
                0 => 4,
                _ => 0,
            };
            num2 += EClass.rnd(3) - EClass.rnd(2);
            SuccubusSleep(EClass.pc);
            if (EClass.pc.isDead)
            {
                return;
            }
            base.value = 1;
            slept = true;
            if (!EClass.pc.pos.IsInSpot<TraitPillowStrange>())
            {
                foreach (Chara chara in EClass._map.charas)
                {
                    if (chara.host != null || chara.noMove || chara.conSuspend != null || chara.isRestrained || chara.IsPC)
                    {
                        continue;
                    }
                    bool flag = chara.GetBool(123);
                    if (!flag && chara.IsPCFaction && chara.race.tag.Contains("sleepBeside") && EClass.rnd(5) == 0)
                    {
                        flag = true;
                    }
                    if (flag)
                    {
                        chara.MoveImmediate(EClass.pc.pos);
                        chara.SetDir(chara.IsPCC ? EClass.pc.dir : 0);
                        chara.Say("sleep_beside", chara, EClass.pc);
                        if (!chara.HasCondition<ConSleep>())
{
                            chara.AddCondition<ConSleep>(20 + EClass.rnd(25), force: true);
                        }
                    }
                }
            }
            foreach (Chara member in EClass.pc.party.members)
            {
                if (!member.IsPC && !member.HasCondition<ConSleep>())
                {
                    member.AddCondition<ConSleep>(5 + EClass.rnd(10), force: true);
                }
            }
            owner.RemoveCondition<ConBleed>();
            owner.RemoveCondition<ConPoison>();
            owner.RemoveCondition<ConMiasma>();
            EClass.ui.AddLayer<LayerSleep>().Sleep(num2, pcBed, pcPillow);
            return;
        }
        if (EClass.rnd(50) == 0 && !owner.IsPC)
        {
            if (EClass.rnd(10) == 0)
            {
                owner.Talk("sleepFav", (EClass.rnd(2) == 0) ? owner.GetFavCat().GetName().ToLower() : owner.GetFavFood().GetName());
                if (!owner.knowFav && owner.isSynced)
                {
                    Msg.Say("noteFav", owner);
                    owner.knowFav = true;
                }
            }
            else
            {
                owner.Talk("sleep");
            }
        }
        if (!(owner.ai is GoalSleep) || owner.CurrentSpan != TimeTable.Span.Sleep)
        {
            owner.HealHP(EClass.rnd(4) + 1);
            owner.mana.Mod(EClass.rnd(3) + 1);
            if (!owner.IsPC)
            {
                owner.stamina.Mod(EClass.rnd(2) + 1);
            }
            Mod(-1);
        }
    }
References EClass._map, EClass._zone, Chara.AddCondition(), Chara.ai, Map.charas, Chara.conSuspend, Chara.CurrentSpan, Card.dir, BaseCard.GetBool(), Chara.GetFavCat(), Chara.GetFavFood(), Stats.GetPhase(), Chara.HasCondition(), Card.HealHP(), Chara.host, Chara.isDead, Chara.IsPC, Chara.IsPCC, Chara.IsPCFaction, Spatial.IsRegion, Card.isRestrained, Zone.isStarted, Chara.isSynced, Chara.knowFav, Chara.mana, Party.members, Stats.Mod(), BaseCondition.Mod(), Card.MoveImmediate(), Card.noMove, BaseCondition.owner, Chara.parasite, Chara.party, EClass.pc, pcBed, pcPillow, pcSleep, Card.pos, Chara.race, Chara.ride, EClass.rnd(), Msg.Say(), Card.Say(), Chara.SetDir(), Sleep, Chara.sleepiness, slept, Chara.stamina, succubusChecked, SuccubusSleep(), SuccubusVisit(), Card.Talk(), EClass.ui, Card.uid, uidParasite, uidRide, and ActRide.Unride().
Member Data Documentation
pcBed
Thing ConSleep.pcBed
Definition at line 11 of file ConSleep.cs.
Referenced by Tick().
pcPillow
Thing ConSleep.pcPillow
Definition at line 14 of file ConSleep.cs.
Referenced by Tick().
pcSleep
int ConSleep.pcSleep
Definition at line 8 of file ConSleep.cs.
Referenced by Tick(), and ConTransmute.Tick().
pickup
bool ConSleep.pickup
Definition at line 23 of file ConSleep.cs.
posBed
ItemPosition ConSleep.posBed
Definition at line 17 of file ConSleep.cs.
posPillow
ItemPosition ConSleep.posPillow
Definition at line 20 of file ConSleep.cs.
slept
bool ConSleep.slept
Definition at line 26 of file ConSleep.cs.
Referenced by Tick().
succubusChecked
bool ConSleep.succubusChecked
Definition at line 5 of file ConSleep.cs.
Referenced by Tick().
uidParasite
int ConSleep.uidParasite
Definition at line 32 of file ConSleep.cs.
Referenced by Tick().
uidRide
int ConSleep.uidRide
Definition at line 29 of file ConSleep.cs.
Referenced by Tick().
Property Documentation
ConsumeTurn
override bool ConSleep.ConsumeTurn get
Definition at line 36 of file ConSleep.cs.
EmoIcon
override Emo2 ConSleep.EmoIcon get
Definition at line 34 of file ConSleep.cs.
The documentation for this class was generated from the following file:
Elin/ConSleep.cs