Elin Decompiled Documentation: Empyrean.ColorPicker.LabeledColorSlider Class Reference
Empyrean.ColorPicker.LabeledColorSlider Class Reference
Public Member Functions
void SetSliderValueAndSendEvent (float value)
void ToggleSliderMode ()
Properties
SliderType Type [get]
float Value [get, set]
Events
Action< float > ColorValueChanged
Private Member Functions
void Awake ()
char OnValidateInput (string text, int charIndex, char addedChar)
void OnValueChanged (float value)
void UpdateInputLabel (float value)
void OnInputSelected ()
void OnInputValueChanged (string stringValue)
void OnInputEndEdit (string stringValue)
void RestoreOldValue ()
int GetMaxValue ()
Private Attributes
EventAwareSlider slider
UiInputField input
Text label
SliderBackgroundController bgController
bool useSecondaryMode
float sliderValueBackup
SliderType sliderType
SliderType secondarySliderType
Detailed Description
Definition at line 8 of file LabeledColorSlider.cs.
Member Function Documentation
Awake()
void Empyrean.ColorPicker.LabeledColorSlider.Awake () inline private
Definition at line 61 of file LabeledColorSlider.cs.
    {
        slider.onValueChanged.AddListener(UpdateInputLabel);
        slider.onValueChanged.AddListener(OnValueChanged);
        bgController.Init(this);
        input.InputSelected += OnInputSelected;
        UiInputField uiInputField = input;
        uiInputField.onValidateInput = (InputField.OnValidateInput)Delegate.Combine(uiInputField.onValidateInput, new InputField.OnValidateInput(OnValidateInput));
        input.onValueChanged.AddListener(OnInputValueChanged);
        input.onEndEdit.AddListener(OnInputEndEdit);
    }
References Empyrean.ColorPicker.LabeledColorSlider.bgController, Empyrean.ColorPicker.SliderBackgroundController.Init(), Empyrean.ColorPicker.LabeledColorSlider.input, Empyrean.ColorPicker.LabeledColorSlider.OnInputEndEdit(), Empyrean.ColorPicker.LabeledColorSlider.OnInputSelected(), Empyrean.ColorPicker.LabeledColorSlider.OnInputValueChanged(), Empyrean.ColorPicker.LabeledColorSlider.OnValidateInput(), Empyrean.ColorPicker.LabeledColorSlider.OnValueChanged(), Empyrean.ColorPicker.LabeledColorSlider.slider, and Empyrean.ColorPicker.LabeledColorSlider.UpdateInputLabel().
GetMaxValue()
int Empyrean.ColorPicker.LabeledColorSlider.GetMaxValue () inline private
Definition at line 147 of file LabeledColorSlider.cs.
    {
        if (Type != SliderType.Hue)
        {
            return 255;
        }
        return 360;
    }
References Empyrean.ColorPicker.LabeledColorSlider.Type.
Referenced by Empyrean.ColorPicker.LabeledColorSlider.OnInputValueChanged(), and Empyrean.ColorPicker.LabeledColorSlider.UpdateInputLabel().
OnInputEndEdit()
void Empyrean.ColorPicker.LabeledColorSlider.OnInputEndEdit (string stringValue) inline private
Definition at line 118 of file LabeledColorSlider.cs.
    {
        if (string.IsNullOrEmpty(stringValue))
        {
            input.text = "0";
        }
        if (Input.GetKey(KeyCode.Escape))
        {
            RestoreOldValue();
        }
    }
References Empyrean.ColorPicker.LabeledColorSlider.RestoreOldValue().
Referenced by Empyrean.ColorPicker.LabeledColorSlider.Awake().
OnInputSelected()
void Empyrean.ColorPicker.LabeledColorSlider.OnInputSelected () inline private
Definition at line 97 of file LabeledColorSlider.cs.
    {
        sliderValueBackup = slider.value;
    }
References Empyrean.ColorPicker.LabeledColorSlider.slider, and Empyrean.ColorPicker.LabeledColorSlider.sliderValueBackup.
Referenced by Empyrean.ColorPicker.LabeledColorSlider.Awake().
OnInputValueChanged()
void Empyrean.ColorPicker.LabeledColorSlider.OnInputValueChanged (string stringValue) inline private
Definition at line 102 of file LabeledColorSlider.cs.
    {
        if (input.isFocused)
        {
            int value = 0;
            if (stringValue != "")
            {
                value = int.Parse(stringValue);
            }
            value = Mathf.Clamp(value, 0, GetMaxValue());
            slider.value = (float)value / (float)GetMaxValue();
            input.MoveTextEnd(shift: false);
            this.ColorValueChanged(slider.value);
        }
    }
References Empyrean.ColorPicker.LabeledColorSlider.ColorValueChanged, Empyrean.ColorPicker.LabeledColorSlider.GetMaxValue(), and Empyrean.ColorPicker.LabeledColorSlider.input.
Referenced by Empyrean.ColorPicker.LabeledColorSlider.Awake().
OnValidateInput()
char Empyrean.ColorPicker.LabeledColorSlider.OnValidateInput (string text, int charIndex, char addedChar) inline private
Definition at line 73 of file LabeledColorSlider.cs.
    {
        if (!Regex.IsMatch(addedChar.ToString(), "[0-9]"))
        {
            return '\0';
        }
        return addedChar;
    }
Referenced by Empyrean.ColorPicker.LabeledColorSlider.Awake().
OnValueChanged()
void Empyrean.ColorPicker.LabeledColorSlider.OnValueChanged (float value) inline private
Definition at line 87 of file LabeledColorSlider.cs.
    {
        this.ColorValueChanged(value);
    }
References Empyrean.ColorPicker.LabeledColorSlider.ColorValueChanged.
Referenced by Empyrean.ColorPicker.LabeledColorSlider.Awake().
RestoreOldValue()
void Empyrean.ColorPicker.LabeledColorSlider.RestoreOldValue () inline private
Definition at line 130 of file LabeledColorSlider.cs.
    {
        if (!Mathf.Approximately(slider.value, sliderValueBackup))
        {
            Value = sliderValueBackup;
        }
        input.text = ((int)(Value * 255f)).ToString();
        this.ColorValueChanged(slider.value);
    }
References Empyrean.ColorPicker.LabeledColorSlider.ColorValueChanged, Empyrean.ColorPicker.LabeledColorSlider.slider, Empyrean.ColorPicker.LabeledColorSlider.sliderValueBackup, and Empyrean.ColorPicker.LabeledColorSlider.Value.
Referenced by Empyrean.ColorPicker.LabeledColorSlider.OnInputEndEdit().
SetSliderValueAndSendEvent()
void Empyrean.ColorPicker.LabeledColorSlider.SetSliderValueAndSendEvent (float value) inline
Definition at line 82 of file LabeledColorSlider.cs.
    {
        slider.SetValue(value, sendEvent: true);
    }
References EventAwareSlider.SetValue(), and Empyrean.ColorPicker.LabeledColorSlider.slider.
ToggleSliderMode()
void Empyrean.ColorPicker.LabeledColorSlider.ToggleSliderMode () inline
Definition at line 140 of file LabeledColorSlider.cs.
    {
        useSecondaryMode = !useSecondaryMode;
        bgController.ToggleSliderMode();
        label.text = Type.ToString().Substring(0, 1);
    }
References Empyrean.ColorPicker.LabeledColorSlider.bgController, Empyrean.ColorPicker.SliderBackgroundController.ToggleSliderMode(), Empyrean.ColorPicker.LabeledColorSlider.Type, and Empyrean.ColorPicker.LabeledColorSlider.useSecondaryMode.
Referenced by Empyrean.ColorPicker.ColorPicker.OnSlidersModeButton().
UpdateInputLabel()
void Empyrean.ColorPicker.LabeledColorSlider.UpdateInputLabel (float value) inline private
Definition at line 92 of file LabeledColorSlider.cs.
    {
        input.text = ((int)(value * (float)GetMaxValue())).ToString();
    }
References Empyrean.ColorPicker.LabeledColorSlider.GetMaxValue().
Referenced by Empyrean.ColorPicker.LabeledColorSlider.Awake().
Member Data Documentation
bgController
SliderBackgroundController Empyrean.ColorPicker.LabeledColorSlider.bgController private
Definition at line 20 of file LabeledColorSlider.cs.
Referenced by Empyrean.ColorPicker.LabeledColorSlider.Awake(), and Empyrean.ColorPicker.LabeledColorSlider.ToggleSliderMode().
input
UiInputField Empyrean.ColorPicker.LabeledColorSlider.input private
Definition at line 14 of file LabeledColorSlider.cs.
Referenced by Empyrean.ColorPicker.LabeledColorSlider.Awake(), and Empyrean.ColorPicker.LabeledColorSlider.OnInputValueChanged().
label
Text Empyrean.ColorPicker.LabeledColorSlider.label private
Definition at line 17 of file LabeledColorSlider.cs.
secondarySliderType
SliderType Empyrean.ColorPicker.LabeledColorSlider.secondarySliderType private
Definition at line 30 of file LabeledColorSlider.cs.
slider
EventAwareSlider Empyrean.ColorPicker.LabeledColorSlider.slider private
Definition at line 11 of file LabeledColorSlider.cs.
Referenced by Empyrean.ColorPicker.LabeledColorSlider.Awake(), Empyrean.ColorPicker.LabeledColorSlider.OnInputSelected(), Empyrean.ColorPicker.LabeledColorSlider.RestoreOldValue(), and Empyrean.ColorPicker.LabeledColorSlider.SetSliderValueAndSendEvent().
sliderType
SliderType Empyrean.ColorPicker.LabeledColorSlider.sliderType private
Definition at line 27 of file LabeledColorSlider.cs.
sliderValueBackup
float Empyrean.ColorPicker.LabeledColorSlider.sliderValueBackup private
Definition at line 24 of file LabeledColorSlider.cs.
Referenced by Empyrean.ColorPicker.LabeledColorSlider.OnInputSelected(), and Empyrean.ColorPicker.LabeledColorSlider.RestoreOldValue().
useSecondaryMode
bool Empyrean.ColorPicker.LabeledColorSlider.useSecondaryMode private
Definition at line 22 of file LabeledColorSlider.cs.
Referenced by Empyrean.ColorPicker.LabeledColorSlider.ToggleSliderMode().
Property Documentation
Type
SliderType Empyrean.ColorPicker.LabeledColorSlider.Type get package
Definition at line 32 of file LabeledColorSlider.cs.
    {
        get
        {
            if (!useSecondaryMode)
            {
                return sliderType;
            }
            return secondarySliderType;
        }
    }
Referenced by Empyrean.ColorPicker.SliderBackgroundController.GetColorByTypeAndIndex(), Empyrean.ColorPicker.LabeledColorSlider.GetMaxValue(), and Empyrean.ColorPicker.LabeledColorSlider.ToggleSliderMode().
Value
float Empyrean.ColorPicker.LabeledColorSlider.Value get set
Definition at line 44 of file LabeledColorSlider.cs.
    {
        get
        {
            return slider.value;
        }
        set
        {
            slider.SetValue(value, sendEvent: false);
            UpdateInputLabel(value);
        }
    }
Referenced by Empyrean.ColorPicker.LabeledColorSlider.RestoreOldValue(), and Empyrean.ColorPicker.ColorPicker.UpdateColor().
Event Documentation
ColorValueChanged
Action<float> Empyrean.ColorPicker.LabeledColorSlider.ColorValueChanged
Initial value:
= delegate
    {
    }
Definition at line 57 of file LabeledColorSlider.cs.
Referenced by Empyrean.ColorPicker.LabeledColorSlider.OnInputValueChanged(), Empyrean.ColorPicker.LabeledColorSlider.OnValueChanged(), and Empyrean.ColorPicker.LabeledColorSlider.RestoreOldValue().
The documentation for this class was generated from the following file:
Elin/Plugins.UI/Empyrean/ColorPicker/LabeledColorSlider.cs