Elin Decompiled Documentation: QuestDialog Class Reference
QuestDialog Class Reference
Public Member Functions
override void ShowCompleteText ()
override bool CanStartQuest ()
override void OnDropReward ()
Public Member Functions inherited from QuestProgression
override string GetDetail (bool onJournal=false)
Public Member Functions inherited from QuestSequence
override string GetTitle ()
override void OnCompleteTask ()
Public Member Functions inherited from Quest
virtual Thing GetDestThing ()
virtual int GetExtraMoney ()
virtual int GetRewardPlat (int money)
override bool Equals (object obj)
virtual bool IsVisibleOnQuestBoard ()
virtual bool CanStartQuest ()
virtual bool CanUpdateOnTalk (Chara c)
virtual Zone CreateInstanceZone (Chara c)
virtual bool UpdateOnTalk ()
void Init ()
virtual void OnInit ()
Quest SetClient (Chara c, bool assignQuest=true)
void SetTask (QuestTask _task)
void Start ()
virtual void OnStart ()
virtual void OnEnterZone ()
virtual void OnClickQuest ()
void Fail ()
virtual void OnFail ()
virtual void ShowCompleteText ()
void Complete ()
virtual void OnBeforeComplete ()
virtual void OnDropReward ()
Thing DropReward (string id)
Thing DropReward (Thing t)
virtual void OnComplete ()
void CompleteTask ()
virtual void OnCompleteTask ()
virtual void OnGiveItem (Chara c, Thing t)
virtual void OnKillChara (Chara c)
virtual void OnModKarma (int a)
void NextPhase ()
void ChangePhase (int a)
virtual void OnChangePhase (int a)
string Parse (string s)
virtual string GetTitle ()
virtual string GetTrackerText ()
virtual string GetDetail (bool onJournal=false)
virtual string GetDetailText (bool onJournal=false)
virtual string GetTextProgress ()
string GetRewardText ()
virtual string GetTalkProgress ()
virtual string GetTalkComplete ()
void UpdateJournal ()
virtual bool IsDeliverTarget (Chara c)
virtual bool CanDeliverToClient (Chara c)
virtual bool CanDeliverToBox (Thing t)
virtual bool Deliver (Chara c, Thing t=null)
Properties
override bool RequireClientInSameZone [get]
Properties inherited from QuestProgression
override string TitlePrefix [get]
Properties inherited from QuestSequence
SourceQuest.Row originalSource [get]
override string idSource [get]
Properties inherited from Quest
Zone ClientZone [get]
Chara chara [get]
virtual SourceQuest.Row source [get]
bool Confetti [get]
bool IsExpired [get]
int Hours [get]
string TextDeadline [get]
virtual bool HasDLC [get]
virtual string idSource [get]
virtual string RewardSuffix [get]
virtual bool FameContent [get]
virtual string TextExtra [get]
virtual string TextExtra2 [get]
virtual int DangerLv [get]
virtual int AffinityGain [get]
virtual int BaseMoney [get]
virtual int KarmaOnFail [get]
virtual bool CanAbandon [get]
virtual int FameOnComplete [get]
virtual int RangeDeadLine [get]
virtual bool UseInstanceZone [get]
virtual bool ForbidTeleport [get]
virtual bool TrackOnStart [get]
virtual bool RequireClientInSameZone [get]
virtual DifficultyType difficultyType [get]
virtual Chara DestChara [get]
virtual string RefDrama1 [get]
virtual string RefDrama2 [get]
virtual string RefDrama3 [get]
virtual string RefDrama4 [get]
virtual string TitlePrefix [get]
virtual bool CanAutoAdvance [get]
virtual bool IsRandomQuest [get]
virtual string NameDeliver [get]
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Additional Inherited Members
Public Types inherited from Quest
enum DifficultyType {
Default , Deliver , Supply , Escort ,
Bulk , Meal , Farm , Music
}
enum SubReward { plat , gacha_coin , money2 , ticket_furniture }
Static Public Member Functions inherited from Quest
static Quest Create (string _id, string _idPerson=null, Chara c=null)
static List< Zone > ListDeliver ()
Static Public Member Functions inherited from EClass
static int rnd (int a)
static int curve (int a, int start, int step, int rate=75)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Public Attributes inherited from Quest
string id
int uid
int uidClientZone
int phase
int lv
int deadline
int difficulty
int rewardMoney
int bonusMoney
int startDate
int dangerLv
bool isNew
bool isComplete
bool track
Person person
QuestTask task
RefChara refChara = new RefChara()
Static Public Attributes inherited from Quest
const int PhaseComplete = 999
Static Public Attributes inherited from EClass
static Core core
Detailed Description
Definition at line 1 of file QuestDialog.cs.
Member Function Documentation
CanStartQuest()
override bool QuestDialog.CanStartQuest () inline virtual
Reimplemented from Quest.
Definition at line 18 of file QuestDialog.cs.
    {
        if (source.id == "farris_tulip")
        {
            return EClass.pc.faction.HasMember("farris");
        }
        return true;
    }
References Chara.faction, Faction.HasMember(), EClass.pc, and Quest.source.
OnDropReward()
override void QuestDialog.OnDropReward () inline virtual
Reimplemented from Quest.
Definition at line 27 of file QuestDialog.cs.
    {
        switch (source.id)
        {
        case "pre_debt":
        {
            Chara chara = EClass.game.cards.globalCharas.Find("loytel");
            if (chara.currentZone == null)
            {
                EClass.pc.homeBranch.AddMemeber(chara);
            }
            chara.MoveHome("olvina", 59, 66);
            chara.noMove = true;
            chara.AddEditorTag(EditorTag.Invulnerable);
            EClass.player.flags.loytelEscaped = true;
            EClass.game.quests.Start("pre_debt_runaway", "farris");
            break;
        }
        case "pre_debt_runaway":
            EClass.game.quests.Add("exile_meet", "quru").startDate = EClass.world.date.GetRaw() + 43200;
            break;
        case "exile_meet":
            EClass.Branch.AddMemeber(EClass._zone.AddCard(CharaGen.Create("demitas"), EClass.pc.pos.GetNearestPoint(allowBlock: false, allowChara: false)) as Chara);
            EClass.game.quests.Add("exile_quru", "quru").startDate = EClass.world.date.GetRaw() + 1440;
            break;
        case "exile_quru":
            EClass.game.quests.Add("exile_kettle", "kettle").startDate = EClass.world.date.GetRaw() + 1440;
            if (!EClass.game.quests.IsCompleted("into_darkness"))
            {
                EClass.game.quests.Add("into_darkness", "kettle").startDate = EClass.world.date.GetRaw() + 7200;
            }
            break;
        case "exile_kettle":
            EClass.game.quests.Add("exile_whisper").startDate = EClass.world.date.GetRaw() + 1440;
            break;
        case "exile_whisper":
            EClass.game.quests.Add("exile_voice").startDate = EClass.world.date.GetRaw() + 1440;
            break;
        case "fiama_reward":
            DropReward(ThingGen.CreateRecipe("workbench2"));
            DropReward(ThingGen.CreateRecipe("factory_stone"));
            DropReward(ThingGen.CreateRecipe("stonecutter"));
            EClass.game.quests.globalList.Add(Quest.Create("fiama_lock").SetClient(EClass.game.cards.globalCharas.Find("fiama"), assignQuest: false));
            break;
        case "greatDebt":
            EClass.game.quests.Add("farris_tulip", "loytel").startDate = EClass.world.date.GetRaw() + 1440;
            break;
        case "farris_tulip":
            EClass.game.quests.Add("kettle_join", "loytel").startDate = EClass.world.date.GetRaw() + 1440;
            break;
        case "kettle_join":
            EClass.Branch.AddMemeber(EClass._zone.AddCard(CharaGen.Create("kettle"), EClass.pc.pos.GetNearestPoint(allowBlock: false, allowChara: false)) as Chara);
            EClass.Branch.AddMemeber(EClass._zone.AddCard(CharaGen.Create("quru"), EClass.pc.pos.GetNearestPoint(allowBlock: false, allowChara: false)) as Chara);
            EClass.game.quests.Add("quru_morning", "loytel").startDate = EClass.world.date.GetRaw() + 1440;
            break;
        case "quru_morning":
            EClass.game.quests.Add("quru_sing", "quru").startDate = EClass.world.date.GetRaw() + 2880;
            EClass.game.quests.Add("vernis_gold", "loytel").startDate = EClass.world.date.GetRaw() + 1440;
            break;
        case "quru_sing":
            EClass.game.quests.Add("quru_past1", "kettle").startDate = EClass.world.date.GetRaw() + 1440;
            break;
        case "quru_past1":
            EClass.game.quests.Add("quru_past2", "farris").startDate = EClass.world.date.GetRaw() + 1440;
            break;
        }
    }
References EClass._zone, QuestManager.Add(), Zone.AddCard(), Card.AddEditorTag(), FactionBranch.AddMemeber(), EClass.Branch, Game.cards, Quest.chara, Quest.Create(), CharaGen.Create(), ThingGen.CreateRecipe(), Chara.currentZone, World.date, Quest.DropReward(), CardManager.GlobalCharaList.Find(), EClass.game, Point.GetNearestPoint(), Date.GetRaw(), CardManager.globalCharas, QuestManager.globalList, Chara.homeBranch, QuestManager.IsCompleted(), Chara.MoveHome(), EClass.pc, Card.pos, Game.quests, Quest.SetClient(), Quest.source, QuestManager.Start(), Quest.startDate, and EClass.world.
ShowCompleteText()
override void QuestDialog.ShowCompleteText () inline virtual
Reimplemented from Quest.
Definition at line 5 of file QuestDialog.cs.
    {
        if (id == "pre_debt_runaway")
        {
            SE.WriteJournal();
            Msg.Say("completeQuest", GetTitle());
        }
        else
        {
            base.ShowCompleteText();
        }
    }
References QuestSequence.GetTitle(), and Msg.Say().
Property Documentation
RequireClientInSameZone
override bool QuestDialog.RequireClientInSameZone get
Definition at line 3 of file QuestDialog.cs.
The documentation for this class was generated from the following file:
Elin/QuestDialog.cs