Elin Decompiled Documentation: Algorithms.PriorityQueueB< T > Class Template Reference
Algorithms.PriorityQueueB< T > Class Template Reference
Public Member Functions
PriorityQueueB ()
PriorityQueueB (IComparer< T > comparer)
PriorityQueueB (IComparer< T > comparer, int capacity)
int Push (T item)
T Pop ()
void Update (int i)
T Peek ()
void Clear ()
void RemoveLocation (T item)
int Push (T item)
T Pop ()
T Peek ()
void Update (int i)
Protected Member Functions
void SwitchElements (int i, int j)
virtual int OnCompare (int i, int j)
Protected Attributes
List< T > InnerList = new List<T>()
IComparer< T > mComparer
Properties
int Count [get]
T this[int index] [get, set]
Detailed Description
Definition at line 6 of file PriorityQueueB.cs.
Constructor & Destructor Documentation
PriorityQueueB() [1/3]
Algorithms.PriorityQueueB< T >.PriorityQueueB () inline
Definition at line 27 of file PriorityQueueB.cs.
    {
        mComparer = Comparer<T>.Default;
    }
References Algorithms.PriorityQueueB< T >.mComparer.
PriorityQueueB() [2/3]
Algorithms.PriorityQueueB< T >.PriorityQueueB (IComparer< T > comparer) inline
Definition at line 32 of file PriorityQueueB.cs.
    {
        mComparer = comparer;
    }
References Algorithms.PriorityQueueB< T >.mComparer.
PriorityQueueB() [3/3]
Algorithms.PriorityQueueB< T >.PriorityQueueB (IComparer< T > comparer, int capacity) inline
Definition at line 37 of file PriorityQueueB.cs.
    {
        mComparer = comparer;
        InnerList.Capacity = capacity;
    }
References Algorithms.PriorityQueueB< T >.mComparer.
Member Function Documentation
Clear()
void Algorithms.PriorityQueueB< T >.Clear () inline
Definition at line 148 of file PriorityQueueB.cs.
    {
        InnerList.Clear();
    }
References Algorithms.PriorityQueueB< T >.InnerList.
Referenced by Algorithms.PathFinder._FindPath().
OnCompare()
virtual int Algorithms.PriorityQueueB< T >.OnCompare (int i, int j) inline protected virtual
Definition at line 50 of file PriorityQueueB.cs.
    {
        return mComparer.Compare(InnerList[i], InnerList[j]);
    }
References Algorithms.PriorityQueueB< T >.InnerList, and Algorithms.PriorityQueueB< T >.mComparer.
Referenced by Algorithms.PriorityQueueB< T >.Pop(), Algorithms.PriorityQueueB< T >.Push(), and Algorithms.PriorityQueueB< T >.Update().
Peek()
T Algorithms.PriorityQueueB< T >.Peek () inline
Implements Algorithms.IPriorityQueue< T >.
Definition at line 139 of file PriorityQueueB.cs.
    {
        if (InnerList.Count > 0)
        {
            return InnerList[0];
        }
        return default(T);
    }
References Algorithms.PriorityQueueB< T >.InnerList.
Pop()
T Algorithms.PriorityQueueB< T >.Pop () inline
Implements Algorithms.IPriorityQueue< T >.
Definition at line 72 of file PriorityQueueB.cs.
    {
        T result = InnerList[0];
        int num = 0;
        InnerList[0] = InnerList[InnerList.Count - 1];
        InnerList.RemoveAt(InnerList.Count - 1);
        while (true)
        {
            int num2 = num;
            int num3 = 2 * num + 1;
            int num4 = 2 * num + 2;
            if (InnerList.Count > num3 && OnCompare(num, num3) > 0)
            {
                num = num3;
            }
            if (InnerList.Count > num4 && OnCompare(num, num4) > 0)
            {
                num = num4;
            }
            if (num == num2)
            {
                break;
            }
            SwitchElements(num, num2);
        }
        return result;
    }
References Algorithms.PriorityQueueB< T >.InnerList, Algorithms.PriorityQueueB< T >.OnCompare(), and Algorithms.PriorityQueueB< T >.SwitchElements().
Referenced by Algorithms.PathFinder._FindPath().
Push()
int Algorithms.PriorityQueueB< T >.Push (T item) inline
Implements Algorithms.IPriorityQueue< T >.
Definition at line 55 of file PriorityQueueB.cs.
    {
        int num = InnerList.Count;
        InnerList.Add(item);
        while (num != 0)
        {
            int num2 = (num - 1) / 2;
            if (OnCompare(num, num2) >= 0)
            {
                break;
            }
            SwitchElements(num, num2);
            num = num2;
        }
        return num;
    }
References Algorithms.PriorityQueueB< T >.InnerList, item, Algorithms.PriorityQueueB< T >.OnCompare(), and Algorithms.PriorityQueueB< T >.SwitchElements().
Referenced by Algorithms.PathFinder._FindPath().
RemoveLocation()
void Algorithms.PriorityQueueB< T >.RemoveLocation (T item) inline
Definition at line 153 of file PriorityQueueB.cs.
    {
        int num = -1;
        for (int i = 0; i < InnerList.Count; i++)
        {
            if (mComparer.Compare(InnerList[i], item) == 0)
            {
                num = i;
            }
        }
        if (num != -1)
        {
            InnerList.RemoveAt(num);
        }
    }
References Algorithms.PriorityQueueB< T >.InnerList, item, and Algorithms.PriorityQueueB< T >.mComparer.
SwitchElements()
void Algorithms.PriorityQueueB< T >.SwitchElements (int i, int j) inline protected
Definition at line 43 of file PriorityQueueB.cs.
    {
        T value = InnerList[i];
        InnerList[i] = InnerList[j];
        InnerList[j] = value;
    }
References Algorithms.PriorityQueueB< T >.InnerList.
Referenced by Algorithms.PriorityQueueB< T >.Pop(), Algorithms.PriorityQueueB< T >.Push(), and Algorithms.PriorityQueueB< T >.Update().
Update()
void Algorithms.PriorityQueueB< T >.Update (int i) inline
Implements Algorithms.IPriorityQueue< T >.
Definition at line 100 of file PriorityQueueB.cs.
    {
        int num = i;
        while (num != 0)
        {
            int num2 = (num - 1) / 2;
            if (OnCompare(num, num2) >= 0)
            {
                break;
            }
            SwitchElements(num, num2);
            num = num2;
        }
        if (num < i)
        {
            return;
        }
        while (true)
        {
            int num3 = num;
            int num4 = 2 * num + 1;
            int num2 = 2 * num + 2;
            if (InnerList.Count > num4 && OnCompare(num, num4) > 0)
            {
                num = num4;
            }
            if (InnerList.Count > num2 && OnCompare(num, num2) > 0)
            {
                num = num2;
            }
            if (num != num3)
            {
                SwitchElements(num, num3);
                continue;
            }
            break;
        }
    }
References Algorithms.PriorityQueueB< T >.InnerList, Algorithms.PriorityQueueB< T >.OnCompare(), and Algorithms.PriorityQueueB< T >.SwitchElements().
Member Data Documentation
InnerList
List<T> Algorithms.PriorityQueueB< T >.InnerList = new List<T>() protected
Definition at line 8 of file PriorityQueueB.cs.
Referenced by Algorithms.PriorityQueueB< T >.Clear(), Algorithms.PriorityQueueB< T >.OnCompare(), Algorithms.PriorityQueueB< T >.Peek(), Algorithms.PriorityQueueB< T >.Pop(), Algorithms.PriorityQueueB< T >.Push(), Algorithms.PriorityQueueB< T >.RemoveLocation(), Algorithms.PriorityQueueB< T >.SwitchElements(), and Algorithms.PriorityQueueB< T >.Update().
mComparer
IComparer<T> Algorithms.PriorityQueueB< T >.mComparer protected
Definition at line 10 of file PriorityQueueB.cs.
Referenced by Algorithms.PriorityQueueB< T >.OnCompare(), Algorithms.PriorityQueueB< T >.PriorityQueueB(), and Algorithms.PriorityQueueB< T >.RemoveLocation().
Property Documentation
Count
int Algorithms.PriorityQueueB< T >.Count get
Definition at line 12 of file PriorityQueueB.cs.
Referenced by Algorithms.PathFinder._FindPath().
this[int index]
T Algorithms.PriorityQueueB< T >.this[int index] get set
Definition at line 14 of file PriorityQueueB.cs.
    {
        get
        {
            return InnerList[index];
        }
        set
        {
            InnerList[index] = value;
            Update(index);
        }
    }
The documentation for this class was generated from the following file:
Elin/Algorithms/PriorityQueueB.cs