Elin Decompiled Documentation: LayerPolicy Class Reference
LayerPolicy Class Reference
Public Member Functions
override void OnInit ()
void RefreshPolicy ()
void RefreshPolicyList (UIList list, string cat, string plan)
void RefreshPolicyIcons ()
Public Member Functions inherited from ELayer
override void OnBeforeAddLayer ()
void InitInspector ()
sealed override void Init ()
override void OnAfterAddLayer ()
void TryShowHelp ()
void AddLayerToUI (string id)
void TryShowHint (string _langHint=null)
void TalkHomeMemeber (string id)
void TalkMaid (string id)
override void OnRightClick ()
Public Member Functions inherited from Layer
virtual string GetTextHeader (Window window)
virtual bool HeaderIsListOf (int id)
virtual void Init ()
virtual void OnInit ()
virtual void OnAfterInit ()
virtual void ApplySkin ()
void ShowScreenLock (string id)
void UpdateInput ()
virtual void OnUpdateInput ()
virtual void OnRightClick ()
virtual bool OnBack ()
virtual void OnChangeLayer ()
virtual void OnCreate ()
void _AddLayer (string id)
Layer AddLayer (string id)
T AddLayer< T > ()
T AddLayer< T > (string id)
T AddLayerDontCloseOthers< T > ()
Layer AddLayerDontCloseOthers (Layer l)
T GetOrAddLayer< T > ()
virtual void OnBeforeAddLayer ()
virtual void OnAfterAddLayer ()
Layer AddLayer (Layer l)
void ToggleLayer (string id)
T ToggleLayer< T > (string id=null)
void WaitAndClose ()
void OnClickClose ()
virtual void Close ()
void CloseLayers ()
void RemoveLayers (bool removeImportant=false)
bool RemoveLayer< T > ()
void RemoveLayer (Layer l)
virtual void OnKill ()
Layer SetOnKill (Action action)
void DisableClose ()
void Delay (float duration=0.05f)
Layer SetDelay (float d)
Layer GetLayer (string id)
T GetLayer< T > (bool fromTop=false)
Layer GetTopLayer ()
void SwitchContent (int idWindow, int i)
virtual void OnSwitchContent (Window window)
Layer SetTitles (string langList, string idHeaderRow=null)
bool IsBlockWidgetClick ()
bool IsHideHud ()
bool IsAllowGeneralInput ()
bool IsUseBlur ()
bool IsPointerOnLayer ()
void ApplySkin ()
Public Attributes
UIList listPolicyLaw
UIList listPolicyEconomy
UIList listPolicyLife
Material matGrayscale
Public Attributes inherited from Layer
Option option
UnityEvent onKill
Anime animeIn
Anime animeOut
bool closeOthers
bool defaultActionMode = true
Button screenLock
Layer parent
string idLayer
List< Layer > layers = new List<Layer>()
Vector2 lastParentPos
List< Window > windows = new List<Window>()
string langHint
Additional Inherited Members
Static Public Member Functions inherited from ELayer
static int rnd (int a)
Static Public Member Functions inherited from Layer
static T Create< T > ()
static T Create< T > (string path)
static Layer Create (string path)
Static Public Attributes inherited from Layer
static int skipInput
static bool closeOnRightClick
static bool rightClicked
static bool cancelKeyDown
static bool ignoreSounds
static Transform blurStopInstance
static string[] searchPath = new string[3] { "Layer", "Layer/Dialog", "Layer/LayerHome" }
Protected Member Functions inherited from ELayer
sealed override void _Close ()
sealed override void Kill ()
Protected Member Functions inherited from Layer
virtual void Awake ()
virtual void _Close ()
virtual void Kill ()
Protected Attributes inherited from Layer
RectTransform _rect
bool isDestroyed
Properties inherited from ELayer
static Core core [get]
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static FactionBranch Branch [get]
static Faction Home [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static CoreConfig config [get]
static GameSetting setting [get]
static ColorProfile Colors [get]
static SourceManager sources [get]
static World world [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
bool IsFloat [get]
virtual string IdHelp [get]
Properties inherited from Layer
Layer TopLayer [get]
string uid [get]
virtual RectTransform rectLayers [get]
virtual bool blockWidgetClick [get]
Detailed Description
Definition at line 4 of file LayerPolicy.cs.
Member Function Documentation
OnInit()
override void LayerPolicy.OnInit () inline virtual
Reimplemented from Layer.
Definition at line 14 of file LayerPolicy.cs.
    {
        RefreshPolicy();
    }
References RefreshPolicy().
RefreshPolicy()
void LayerPolicy.RefreshPolicy () inline
Definition at line 19 of file LayerPolicy.cs.
    {
        RefreshPolicyList(listPolicyLaw, "law", "department_law");
        RefreshPolicyList(listPolicyEconomy, "economy", "department_economy");
        RefreshPolicyList(listPolicyLife, "life", "department_life");
        RefreshPolicyIcons();
    }
References listPolicyEconomy, listPolicyLaw, listPolicyLife, RefreshPolicyIcons(), and RefreshPolicyList().
Referenced by OnInit().
RefreshPolicyIcons()
void LayerPolicy.RefreshPolicyIcons () inline
Definition at line 71 of file LayerPolicy.cs.
    {
        int num = ELayer.Branch.policies.CurrentAP();
        UIList[] array = new UIList[3] { listPolicyLaw, listPolicyLife, listPolicyEconomy };
        for (int i = 0; i < array.Length; i++)
        {
            UIButton[] componentsInChildren = array[i].GetComponentsInChildren<UIButton>();
            foreach (UIButton obj in componentsInChildren)
            {
                Policy policy = obj.refObj as Policy;
                obj.icon.material = (policy.active ? null : matGrayscale);
                obj.imageCheck.SetActive(policy.active);
                obj.subText.SetText(policy.Cost.ToString() ?? "", (num + policy.Cost <= ELayer.Branch.MaxAP || policy.active) ? FontColor.Good : FontColor.Bad);
            }
        }
    }
References Policy.active, ELayer.Branch, Policy.Cost, PolicyManager.CurrentAP(), UIButton.imageCheck, listPolicyEconomy, listPolicyLaw, listPolicyLife, matGrayscale, FactionBranch.policies, UIText.SetText(), and UIButton.subText.
Referenced by RefreshPolicy().
RefreshPolicyList()
void LayerPolicy.RefreshPolicyList (UIList list, string cat, string plan) inline
Definition at line 27 of file LayerPolicy.cs.
    {
        list.callbacks = new UIList.Callback<Policy, UIButton>
        {
            onClick = delegate
            {
            },
            onInstantiate = delegate(Policy a, UIButton b)
            {
                b.mainText.SetText(a.Name);
                b.onClick.AddListener(delegate
                {
                    if (!a.active && ELayer.Branch.policies.CurrentAP() + a.Cost > ELayer.Branch.MaxAP)
                    {
                        SE.Beep();
                    }
                    else
                    {
                        SE.ClickOk();
                        a.active = !a.active;
                        ELayer.Branch.policies.RefreshEffects();
                        RefreshPolicyIcons();
                    }
                });
                b.refObj = a;
                b.tooltip.onShowTooltip = delegate(UITooltip tp)
                {
                    a.WriteNote(tp.note);
                };
            },
            onList = delegate
            {
                foreach (Policy item in ELayer.Branch.policies.list.Where((Policy p) => p.source.categorySub == cat))
                {
                    list.Add(item);
                }
            },
            onSort = (Policy a, UIList.SortMode m) => a.GetSortVal(m),
            onRefresh = null
        };
        list.List();
        list.GetComponentInChildren<CanvasGroup>().alpha = ((list.items.Count > 0) ? 0.9f : 0.4f);
    }
References Policy.active, UIList.Add(), ELayer.Branch, Policy.Cost, PolicyManager.CurrentAP(), Policy.GetSortVal(), item, UIList.items, UIList.List(), PolicyManager.list, UIButton.mainText, FactionBranch.MaxAP, Policy.Name, UITooltip.note, FactionBranch.policies, UIText.SetText(), Policy.source, and Policy.WriteNote().
Referenced by RefreshPolicy().
Member Data Documentation
listPolicyEconomy
UIList LayerPolicy.listPolicyEconomy
Definition at line 8 of file LayerPolicy.cs.
Referenced by RefreshPolicy(), and RefreshPolicyIcons().
listPolicyLaw
UIList LayerPolicy.listPolicyLaw
Definition at line 6 of file LayerPolicy.cs.
Referenced by RefreshPolicy(), and RefreshPolicyIcons().
listPolicyLife
UIList LayerPolicy.listPolicyLife
Definition at line 10 of file LayerPolicy.cs.
Referenced by RefreshPolicy(), and RefreshPolicyIcons().
matGrayscale
Material LayerPolicy.matGrayscale
Definition at line 12 of file LayerPolicy.cs.
Referenced by RefreshPolicyIcons().
The documentation for this class was generated from the following file:
Elin/LayerPolicy.cs