Elin Decompiled Documentation: FactionGroup Class Reference
FactionGroup Class Reference
Public Member Functions
int CountMemebers ()
int CountMemebersInZone ()
float GetHappiness ()
void Add (Faction f)
void Remove (Faction f)
Public Attributes
List< Faction > list = new List<Faction>()
Additional Inherited Members
Static Public Member Functions inherited from EClass
static int rndSeed (int a, int seed)
static int rnd (int a)
static int curve (int a, int start, int step, int rate=75)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Static Public Attributes inherited from EClass
static Core core
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Detailed Description
Definition at line 4 of file FactionGroup.cs.
Member Function Documentation
Add()
void FactionGroup.Add (Faction f) inline
Definition at line 29 of file FactionGroup.cs.
    {
        list.Add(f);
    }
References list.
CountMemebers()
int FactionGroup.CountMemebers () inline
Definition at line 9 of file FactionGroup.cs.
    {
        return 0;
    }
CountMemebersInZone()
int FactionGroup.CountMemebersInZone () inline
Definition at line 14 of file FactionGroup.cs.
    {
        return 0;
    }
GetHappiness()
float FactionGroup.GetHappiness () inline
Definition at line 19 of file FactionGroup.cs.
    {
        float num = 0f;
        foreach (Faction item in list)
        {
            num += item.GetHappiness();
        }
        return num / (float)list.Count;
    }
References item, and list.
Remove()
void FactionGroup.Remove (Faction f) inline
Definition at line 34 of file FactionGroup.cs.
    {
        list.Remove(f);
    }
References list.
Member Data Documentation
list
List<Faction> FactionGroup.list = new List<Faction>()
Definition at line 7 of file FactionGroup.cs.
Referenced by Add(), GetHappiness(), and Remove().
The documentation for this class was generated from the following file:
Elin/FactionGroup.cs