Elin Decompiled Documentation: TerrainMenu Class Reference
TerrainMenu Class Reference
Public Member Functions
void Show (ActionMode _am)
void OnChangeRadius (float a)
Public Attributes
UISlider sliderRadius
ActionMode am
UISelectableGroup group
int radius
Additional Inherited Members
Static Public Member Functions inherited from EMono
static int rnd (int a)
Static Public Attributes inherited from EMono
static Core core
Properties inherited from EMono
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SoundManager Sound [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static CoreDebug debug [get]
Detailed Description
Definition at line 1 of file TerrainMenu.cs.
Member Function Documentation
OnChangeRadius()
void TerrainMenu.OnChangeRadius (float a) inline
Definition at line 44 of file TerrainMenu.cs.
    {
        am.brushRadius = (int)a;
        sliderRadius.textMain.text = "radius".lang() + ": " + am.brushRadius;
    }
References am, and ActionMode.brushRadius.
Show()
void TerrainMenu.Show (ActionMode _am) inline
Definition at line 11 of file TerrainMenu.cs.
    {
        bool useSubMenu = _am.UseSubMenu;
        am = _am;
        base.gameObject.SetActive(useSubMenu);
        if (!useSubMenu)
        {
            return;
        }
        sliderRadius.value = am.brushRadius;
        sliderRadius.transform.parent.SetActive(am.UseSubMenuSlider);
        group.checkbox = !am.SubMenuAsGroup;
        foreach (UIButton componentsInDirectChild in group.GetComponentsInDirectChildren<UIButton>())
        {
            componentsInDirectChild.SetActive(enable: true);
        }
        group.Init(am.SubMenuModeIndex, delegate(int a)
        {
            am.OnClickSubMenu(a);
        });
        for (int i = 0; i < group.list.Count; i++)
        {
            UIButton uIButton = group.list[i];
            string text = am.OnSetSubMenuButton(i, uIButton);
            uIButton.SetActive(text != null);
            if (text != null)
            {
                uIButton.mainText.SetText(text.lang());
            }
        }
        this.RebuildLayout(recursive: true);
    }
References am, ActionMode.brushRadius, group, UISelectableGroup.Init(), UISelectableGroup.list, UIButton.mainText, ActionMode.OnClickSubMenu(), ActionMode.OnSetSubMenuButton(), UIText.SetText(), sliderRadius, ActionMode.SubMenuAsGroup, ActionMode.SubMenuModeIndex, ActionMode.UseSubMenu, and ActionMode.UseSubMenuSlider.
Referenced by ActionMode.Activate().
Member Data Documentation
am
ActionMode TerrainMenu.am
Definition at line 5 of file TerrainMenu.cs.
Referenced by OnChangeRadius(), and Show().
group
UISelectableGroup TerrainMenu.group
Definition at line 7 of file TerrainMenu.cs.
Referenced by Show().
radius
int TerrainMenu.radius
Definition at line 9 of file TerrainMenu.cs.
sliderRadius
UISlider TerrainMenu.sliderRadius
Definition at line 3 of file TerrainMenu.cs.
Referenced by Show().
The documentation for this class was generated from the following file:
Elin/TerrainMenu.cs