Elin Decompiled Documentation: BaseCard Class Reference
BaseCard Class Reference
Public Member Functions
bool GetBool (int id)
void SetBool (int id, bool enable)
int GetInt (int id, int? defaultInt=null)
void AddInt (int id, int value)
void SetInt (int id, int value=0)
string GetStr (int id, string defaultStr=null)
void SetStr (int id, string value=null)
T GetObj< T > (int id)
void SetObj (int id, object o)
T SetObj< T > (int id, object o)
Public Attributes
Dictionary< int, object > mapObj = new Dictionary<int, object>()
Dictionary< int, int > mapInt = new Dictionary<int, int>()
Dictionary< int, string > mapStr = new Dictionary<int, string>()
Additional Inherited Members
Static Public Member Functions inherited from EClass
static int rndSeed (int a, int seed)
static int rnd (int a)
static int curve (int a, int start, int step, int rate=75)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Static Public Attributes inherited from EClass
static Core core
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Detailed Description
Definition at line 4 of file BaseCard.cs.
Member Function Documentation
AddInt()
void BaseCard.AddInt (int id, int value) inline
Definition at line 34 of file BaseCard.cs.
    {
        SetInt(id, GetInt(id) + value);
    }
References GetInt(), and SetInt().
GetBool()
bool BaseCard.GetBool (int id) inline
Definition at line 15 of file BaseCard.cs.
    {
        return GetInt(id) != 0;
    }
References GetInt().
Referenced by TraitAltar._OnOffer(), CharaRenderer.DrawHat(), Thing.GetName(), ZoneEventHarvest.OnLeaveZone(), InvOwnerDeliver.ShouldShowGuide(), and ConSleep.Tick().
GetInt()
int BaseCard.GetInt (int id, int? defaultInt = null) inline
Definition at line 25 of file BaseCard.cs.
    {
        if (mapInt.TryGetValue(id, out var value))
        {
            return value;
        }
        return defaultInt.GetValueOrDefault();
    }
References mapInt.
Referenced by LayerEditPortrait.Activate(), Element.AddEncNote(), AddInt(), LayerSleep.Advance(), DramaCustomSequence.Build(), ZonePreEnterBoutWin.Execute(), GetBool(), TraitScrollMapTreasure.GetDest(), Thing.GetName(), Trait.OnBarter(), BaseListPeople.OnClick(), TraitScrollMap.OnRead(), InvOwnerDeliver.PayBill(), FoodEffect.Proc(), TCOrbitChara.RefreshAll(), LayerQuestBoard.RefreshRanking(), DramaOutcome.revive_pet(), AI_Idle.Run(), AI_Steal.Run(), Portrait.SetChara(), AIWork.SetDestination(), TraitScrollMap.SetName(), GameDate.ShipPackages(), Card.SpawnLoot(), DramaActor.Talk(), TraitSwitch.TryDisarmTrap(), and GoalCombat.TryUseAbility().
GetObj< T >()
T BaseCard.GetObj< T > (int id) inline
Definition at line 78 of file BaseCard.cs.
    {
        if (mapObj == null)
        {
            return default(T);
        }
        if (mapObj.TryGetValue(id, out var value) && value is T)
        {
            return (T)value;
        }
        return default(T);
    }
References mapObj.
GetStr()
string BaseCard.GetStr (int id, string defaultStr = null) inline
Definition at line 54 of file BaseCard.cs.
    {
        if (mapStr.TryGetValue(id, out var value))
        {
            return value;
        }
        return defaultStr;
    }
References mapStr.
Referenced by SerializedCards.Add(), TraitBlueprint.CanStackTo(), TraitBook.CanStackTo(), TraitRecipe.CanStackTo(), TraitTeleporter.CanStackTo(), TraitNewZone.CreateZone(), Thing.GetName(), WindowChara.RefreshStatic(), WindowChara.SetPortraitBG(), WindowChara.SetPortraitFrame(), and AI_Shopping.TryRestock().
SetBool()
void BaseCard.SetBool (int id, bool enable) inline
Definition at line 20 of file BaseCard.cs.
    {
        SetInt(id, enable ? 1 : 0);
    }
References SetInt().
Referenced by Party.AddMemeber(), DramaOutcome.chara_hired(), and DramaOutcome.chara_hired_ticket().
SetInt()
void BaseCard.SetInt (int id, int value = 0) inline
Definition at line 39 of file BaseCard.cs.
    {
        if (value == 0)
        {
            if (mapInt.ContainsKey(id))
            {
                mapInt.Remove(id);
            }
        }
        else
        {
            mapInt[id] = value;
        }
    }
References mapInt.
Referenced by Chara._MakeAlly(), LayerEditPortrait.Activate(), AddInt(), Faction.AddReserve(), LayerSleep.Advance(), LayerEditPCC.Apply(), ZonePreEnterBoutWin.Execute(), DramaOutcome.fiama_pet(), TraitScrollMapTreasure.GetDest(), Faction.OnAdvanceMonth(), Trait.OnBarter(), TraitWell.OnBlend(), BaseListPeople.OnClick(), QuestIntroInspector.OnComplete(), QuestVernis.OnComplete(), Player.OnCreateGame(), ShopTransaction.OnEndTransaction(), Chara.OnSerializing(), FoodEffect.Proc(), ActEffect.Proc(), ActEffect.ProcAt(), InvOwner.Transaction.Process(), AI_Idle.Run(), AI_Steal.Run(), SetBool(), GameDate.ShipPackages(), Card.SpawnLoot(), and TraitSwitch.TryDisarmTrap().
SetObj()
void BaseCard.SetObj (int id, object o) inline
Definition at line 91 of file BaseCard.cs.
    {
        if (mapObj == null)
        {
            mapObj = new Dictionary<int, object>();
        }
        if (o == null)
        {
            if (mapObj.ContainsKey(id))
            {
                mapObj.Remove(id);
            }
        }
        else
        {
            mapObj[id] = o;
        }
    }
References mapObj.
Referenced by ListPeopleBuySlave.OnCreate(), and SerializedCards.Restore().
SetObj< T >()
T BaseCard.SetObj< T > (int id, object o) inline
Definition at line 110 of file BaseCard.cs.
    {
        if (mapObj == null)
        {
            mapObj = new Dictionary<int, object>();
        }
        if (o == null)
        {
            if (mapStr.ContainsKey(id))
            {
                mapObj.Remove(id);
            }
            return default(T);
        }
        mapObj[id] = o;
        return (T)o;
    }
References mapObj, and mapStr.
SetStr()
void BaseCard.SetStr (int id, string value = null) inline
Definition at line 63 of file BaseCard.cs.
    {
        if (value.IsEmpty())
        {
            if (mapStr.ContainsKey(id))
            {
                mapStr.Remove(id);
            }
        }
        else
        {
            mapStr[id] = value;
        }
    }
References mapStr.
Referenced by GameDate.AdvanceDay(), AI_Shopping.Buy(), ThingGen.CreateLetter(), ThingGen.CreateRecipe(), ThingGen.CreateRedBook(), Chara.MutateRandom(), TraitBook.OnCreate(), TraitRecipe.OnCreate(), TraitBook.OnImportMap(), TraitRadio.OnUse(), SerializedCards.Restore(), WindowChara.SetPortraitBG(), WindowChara.SetPortraitFrame(), and GameDate.ShipLetter().
Member Data Documentation
mapInt
Dictionary<int, int> BaseCard.mapInt = new Dictionary<int, int>()
Definition at line 10 of file BaseCard.cs.
Referenced by Card.Duplicate(), GetInt(), and SetInt().
mapObj
Dictionary<int, object> BaseCard.mapObj = new Dictionary<int, object>()
Definition at line 7 of file BaseCard.cs.
Referenced by SerializedCards.Add(), GetObj< T >(), SerializedCards.Restore(), SetObj(), and SetObj< T >().
mapStr
Dictionary<int, string> BaseCard.mapStr = new Dictionary<int, string>()
Definition at line 13 of file BaseCard.cs.
Referenced by Card.Duplicate(), GetStr(), SetObj< T >(), and SetStr().
The documentation for this class was generated from the following file:
Elin/BaseCard.cs