Elin Decompiled Documentation: DSVRow Class Reference
DSVRow Class Reference
Classes
class Item
Public Attributes
List< Item > items = new List<Item>()
UIItem itemHeader
RawImage bgGrid
RectTransform _rect
Private Member Functions
void Awake ()
Detailed Description
Definition at line 6 of file DSVRow.cs.
Member Function Documentation
Awake()
void DSVRow.Awake () inline private
Definition at line 24 of file DSVRow.cs.
    {
        _rect = this.Rect();
    }
References _rect.
Member Data Documentation
_rect
RectTransform DSVRow._rect
Definition at line 22 of file DSVRow.cs.
Referenced by Awake().
bgGrid
RawImage DSVRow.bgGrid
Definition at line 19 of file DSVRow.cs.
Referenced by UIDynamicList.UpdateRow().
itemHeader
UIItem DSVRow.itemHeader
Definition at line 17 of file DSVRow.cs.
Referenced by UIDynamicList.UpdateRow().
items
List<Item> DSVRow.items = new List<Item>()
Definition at line 15 of file DSVRow.cs.
Referenced by UIDynamicList.GetComp< T >(), UIDynamicList.RefreshHighlight(), UIDynamicList.Select< T >(), and UIDynamicList.UpdateRow().
The documentation for this class was generated from the following file:
Elin/Plugins.UI/DSVRow.cs