Elin Decompiled Documentation: EffectIRenderer Class Reference
EffectIRenderer Class Reference
Public Member Functions
EffectIRenderer Play (Card _card, Card _origin, Vector3 _to)
EffectIRenderer Play (Card origin, Card _card, Point from, Point to=null, float fixY=0f)
override void OnUpdate ()
override void OnKill ()
Public Member Functions inherited from Effect
void Play (float delay, Point from, float fixY=0f, Point to=null, Sprite sprite=null)
Effect Play (Point from, float fixY=0f, Point to=null, Sprite sprite=null)
Effect _Play (Point from, Vector3 fromV, float fixY=0f, Point to=null, Sprite sprite=null)
Effect Play (Vector3 v)
Effect Flip (bool x=false, bool y=false)
Effect SetStartDelay (float a)
virtual void OnPlay ()
virtual void OnUpdate ()
void Kill ()
virtual void OnKill ()
void OnDisable ()
void OnDestroy ()
Effect Emit (int num)
Effect SetParticleColor (Color c)
Effect SetParticleColor (Color color, bool changeMaterial=false, string idCol="_Color")
Effect SetScale (float a)
Public Attributes
Card card
Card origin
Point from
float snapInterval
bool follow
TransAnimeData animeData
TransAnime anime
Public Attributes inherited from Effect
Type type
float duration = 1f
float speed
float startDelay
bool lookAtTarget
bool rotate
bool pool
SpriteRenderer sr
ParticleSystem[] systems
Vector3[] dirs
Ease ease
Vector3 posFix
Vector3 randomRange
Tween moveTween
Sprite[] sprites
bool randomFlip
bool randomSpeed
bool test
bool setColor = true
Action onComplete
int spriteIndex
float timer
Vector3 fromV
Vector3 destV
bool pooled
Transform poolParent
List< Material > materialsToDestroy
Point destPos
Tween killTimer
Private Attributes
float snapTimer
Vector3 v
Additional Inherited Members
Public Types inherited from Effect
enum Type { Default , Firework }
Static Public Member Functions inherited from Effect
static Effect Get (Effect original)
static Effect Get (string id)
static T Get< T > (string id)
Static Public Member Functions inherited from EMono
static int rnd (int a)
Static Public Attributes inherited from EMono
static Core core
Protected Member Functions inherited from Effect
void Activate ()
Protected Attributes inherited from Effect
bool killed
Properties inherited from Effect
static EffectManager manager [get]
Properties inherited from EMono
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SoundManager Sound [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static CoreDebug debug [get]
Detailed Description
Definition at line 3 of file EffectIRenderer.cs.
Member Function Documentation
OnKill()
override void EffectIRenderer.OnKill () inline virtual
Reimplemented from Effect.
Definition at line 126 of file EffectIRenderer.cs.
    {
        if (card != null && card.renderer.hasActor)
        {
            card.renderer.KillActor();
        }
    }
References card, CardRenderer.hasActor, CardRenderer.KillActor(), and Card.renderer.
OnUpdate()
override void EffectIRenderer.OnUpdate () inline virtual
Reimplemented from Effect.
Definition at line 72 of file EffectIRenderer.cs.
    {
        RenderParam renderParam = card.GetRenderParam();
        renderParam.color = EMono.scene.screenElin.tileMap.GetApproximateBlocklight(from.cell);
        timer += Core.delta;
        snapTimer -= Core.delta;
        anime?.Update();
        if (snapTimer < 0f || v == Vector3.zero)
        {
            if (follow)
            {
                if (origin.renderer != null)
                {
                    Vector3 position = origin.renderer.position;
                    Vector3 vector = destV * timer / duration * speed;
                    v.x = position.x + posFix.x + vector.x;
                    v.y = position.y + posFix.y + vector.y;
                    v.z = position.z + posFix.z + vector.z;
                }
            }
            else
            {
                v.x = base.transform.position.x;
                v.y = base.transform.position.y;
                v.z = base.transform.position.z;
            }
            if (anime != null)
            {
                v.x += anime.v.x;
                v.y += anime.v.y;
                v.z += anime.v.z;
            }
            snapTimer += snapInterval;
        }
        renderParam.x = v.x;
        renderParam.y = v.y;
        renderParam.z = v.x;
        card.renderer.skip = true;
        if (card.renderer.usePass)
        {
            card.renderer.data.Draw(renderParam);
            return;
        }
        if (!card.renderer.hasActor)
        {
            card.renderer.OnEnterScreen();
        }
        if ((bool)card.renderer.actor)
        {
            card.renderer.actor.OnRender(renderParam);
            card.renderer.isSynced = false;
        }
    }
References CardRenderer.actor, anime, card, Point.cell, RenderObject.data, Core.delta, Effect.destV, RenderData.Draw(), Effect.duration, follow, from, BaseTileMap.GetApproximateBlocklight(), Card.GetRenderParam(), CardRenderer.hasActor, CardRenderer.OnEnterScreen(), CardActor.OnRender(), origin, CardRenderer.position, Card.renderer, EMono.scene, Scene.screenElin, snapInterval, snapTimer, Effect.speed, BaseGameScreen.tileMap, Effect.timer, TransAnime.Update(), RenderObject.usePass, v, and TransAnime.v.
Referenced by Play().
Play() [1/2]
EffectIRenderer EffectIRenderer.Play (Card _card, Card _origin, Vector3 _to) inline
Definition at line 23 of file EffectIRenderer.cs.
    {
        if (!EMono.core.IsGameStarted)
        {
            Kill();
            return null;
        }
        card = _card;
        origin = _origin;
        destV = _to;
        from = _origin.pos.Copy();
        snapTimer = -0.01f;
        Activate();
        OnUpdate();
        if ((bool)animeData)
        {
            anime = new TransAnime
            {
                data = animeData,
                renderer = card.renderer
            }.Init();
        }
        return this;
    }
References Effect.Activate(), anime, animeData, card, Point.Copy(), EMono.core, Effect.destV, from, Core.IsGameStarted, Effect.Kill(), OnUpdate(), origin, Card.pos, and snapTimer.
Referenced by Play(), and ActThrow.Throw().
Play() [2/2]
EffectIRenderer EffectIRenderer.Play (Card origin, Card _card, Point from, Point to = null, float fixY = 0f) inline
Definition at line 48 of file EffectIRenderer.cs.
    {
        card = _card;
        snapTimer = -0.01f;
        this.from = from.Copy();
        if (origin.ExistsOnMap)
        {
            _Play(from, origin.renderer.position, fixY, to);
        }
        else
        {
            Play(from, fixY, to);
        }
        if ((bool)animeData)
        {
            anime = new TransAnime
            {
                data = animeData,
                renderer = card.renderer
            }.Init();
        }
        return this;
    }
References Effect._Play(), anime, animeData, card, Point.Copy(), Card.ExistsOnMap, from, origin, Play(), CardRenderer.position, Card.renderer, and snapTimer.
Member Data Documentation
anime
TransAnime EffectIRenderer.anime
Definition at line 17 of file EffectIRenderer.cs.
Referenced by OnUpdate(), and Play().
animeData
TransAnimeData EffectIRenderer.animeData
Definition at line 15 of file EffectIRenderer.cs.
Referenced by Play().
card
Card EffectIRenderer.card
Definition at line 5 of file EffectIRenderer.cs.
Referenced by OnKill(), OnUpdate(), and Play().
follow
bool EffectIRenderer.follow
Definition at line 13 of file EffectIRenderer.cs.
Referenced by OnUpdate().
from
Point EffectIRenderer.from
Definition at line 9 of file EffectIRenderer.cs.
Referenced by OnUpdate(), and Play().
origin
Card EffectIRenderer.origin
Definition at line 7 of file EffectIRenderer.cs.
Referenced by OnUpdate(), and Play().
snapInterval
float EffectIRenderer.snapInterval
Definition at line 11 of file EffectIRenderer.cs.
Referenced by OnUpdate().
snapTimer
float EffectIRenderer.snapTimer private
Definition at line 19 of file EffectIRenderer.cs.
Referenced by OnUpdate(), and Play().
v
Vector3 EffectIRenderer.v private
Definition at line 21 of file EffectIRenderer.cs.
Referenced by OnUpdate().
The documentation for this class was generated from the following file:
Elin/EffectIRenderer.cs