Elin Decompiled Documentation: Props Class Reference
Props Class Reference
Public Member Functions
void Init ()
void Add (Card t)
void Remove (Card t)
void OnNumChange (Card c, int a)
bool ShouldListAsResource (Thing t)
Thing GetAvailableThing (string id, int idMat)
ThingStack ListThingStack (Recipe.Ingredient ing, StockSearchMode searchMode)
List< Thing > ListThingsInCategory (SourceCategory.Row cat)
Dictionary< string, ThingStack > ListThingStacksInCategory (SourceCategory.Row cat)
Thing Find< T > ()
Thing FindEmptyContainer< T > ()
Thing FindEmptyContainer< T > (Thing target)
Thing Find (int uid)
Thing FindShared (string id)
Thing Find (string id, string idMat)
Thing Find (string id, int idMat=-1, int refVal=-1, bool shared=false)
int GetNum (string id, bool onlyShared=false)
void Validate ()
Static Public Member Functions
static int GetNumStockedAndRoaming (string id)
Static Public Member Functions inherited from EClass
static int rndSeed (int a, int seed)
static int rnd (long a)
static int rnd (int a)
static int curve (int a, int start, int step, int rate=75)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Public Attributes
PropSet all = new PropSet()
Dictionary< string, PropSet > cardMap = new Dictionary<string, PropSet>()
Dictionary< string, PropSetCategory > categoryMap = new Dictionary<string, PropSetCategory>()
Dictionary< string, PropSet > raceMap = new Dictionary<string, PropSet>()
Dictionary< string, PropSet > workMap = new Dictionary<string, PropSet>()
TraitManager traits = new TraitManager()
List< Thing > things = new List<Thing>()
List< Thing > containers = new List<Thing>()
int maxWeight = 100
int weight
Properties
virtual bool IsStocked [get]
virtual bool IsRoaming [get]
virtual bool IsInstalled [get]
virtual PlaceState state [get]
List< Thing > Things [get]
int Count [get]
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Private Member Functions
void ListThingStacksInCategory (SourceCategory.Row cat, Dictionary< string, ThingStack > stacks, Thing t)
Additional Inherited Members
Static Public Attributes inherited from EClass
static Core core
Detailed Description
Definition at line 6 of file Props.cs.
Member Function Documentation
Add()
void Props.Add (Card t) inline
Definition at line 63 of file Props.cs.
    {
        if (all.Contains(t))
        {
            Debug.Log(t.props);
            Debug.Log(t.parent);
            Debug.Log(things.Contains(t) + "/" + cardMap.ContainsKey(t.id));
            Debug.LogError(t?.ToString() + " alreadin in " + this);
            return;
        }
        if (t.props != null)
        {
            t.props.Remove(t);
        }
        t.props = this;
        t.placeState = state;
        if (t.isChara)
        {
            raceMap.GetOrCreate(t.Chara.race.id).Add(t);
            return;
        }
        foreach (Thing thing in t.things)
        {
            if (t.placeState != 0)
            {
                EClass._map.Stocked.Add(thing);
            }
        }
        weight += t.Num;
        all.Add(t);
        things.Add(t.Thing);
        cardMap.GetOrCreate(t.id).Add(t);
        if (t.sourceCard.origin != null)
        {
            cardMap.GetOrCreate(t.sourceCard.origin.id).Add(t);
        }
        categoryMap[t.category.id].Add(t);
        if (!t.Thing.source.workTag.IsEmpty())
        {
            workMap.GetOrCreate(t.Thing.source.workTag).Add(t);
        }
        if (t.IsContainer)
        {
            containers.Add(t.Thing);
        }
        traits.OnAddCard(t);
        if (t.isDeconstructing)
        {
            EClass._map.props.deconstructing.Add(t);
        }
    }
References EClass._map, ActPlan.List.Add(), PropSet.Add(), Add(), all, cardMap, categoryMap, Card.Chara, containers, Debug, PropsManager.deconstructing, Card.id, Card.isChara, TraitManager.OnAddCard(), Card.parent, Card.props, Map.props, Chara.race, raceMap, Remove(), state, Map.Stocked, Card.things, things, traits, weight, and workMap.
Referenced by Add(), Card.AddThing(), PropsManager.OnCardAddedToZone(), and PropsManager.OnSetPlaceState().
Find() [1/3]
Thing Props.Find (int uid) inline
Definition at line 389 of file Props.cs.
    {
        foreach (Thing thing in Things)
        {
            if (thing.uid == uid)
            {
                return thing;
            }
        }
        return null;
    }
References Things, and Card.uid.
Referenced by TaskBuild._CanPerformTask(), DropdownGrid.BuildIngredients(), QuestCrafter.CanUpdateOnTalk(), FactionBranch.DailyOutcome(), Find(), FindShared(), FactionBranch.GetMailBoxPos(), Zone.GetSpawnPos(), ListThingStack(), Zone_Nymelle.OnBeforeSimulate(), Recipe.Ingredient.RefreshThing(), AI_Idle.Run(), and MeetingManager.SetRoom().
Find() [2/3]
Thing Props.Find (string id, int idMat = -1, int refVal = -1, bool shared = false) inline
Definition at line 411 of file Props.cs.
    {
        PropSet propSet = cardMap.TryGetValue(id);
        if (propSet != null)
        {
            foreach (Card item in propSet)
            {
                if ((!shared || item.parent is Thing { IsSharedContainer: not false }) && (idMat == -1 || item.material.id == idMat) && (refVal == -1 || item.refVal == refVal))
                {
                    return item as Thing;
                }
            }
        }
        return null;
    }
References cardMap, and item.
Find() [3/3]
Thing Props.Find (string id, string idMat) inline
Definition at line 406 of file Props.cs.
    {
        return Find(id, idMat.IsEmpty() ? (-1) : EClass.sources.materials.alias[idMat].id);
    }
References Find(), SourceManager.materials, and EClass.sources.
Find< T >()
Thing Props.Find< T > () inline
Type Constraints
T : Trait
Definition at line 353 of file Props.cs.
                                   : Trait
    {
        foreach (Thing thing in Things)
        {
            if (thing.trait is T)
            {
                return thing;
            }
        }
        return null;
    }
References Things, and Card.trait.
FindEmptyContainer< T >() [1/2]
Thing Props.FindEmptyContainer< T > () inline
Type Constraints
T : Trait
Definition at line 365 of file Props.cs.
                                                 : Trait
    {
        foreach (Thing thing in Things)
        {
            if (thing.trait is T && !thing.things.IsFull())
            {
                return thing;
            }
        }
        return null;
    }
References ThingContainer.IsFull(), Card.things, Things, and Card.trait.
FindEmptyContainer< T >() [2/2]
Thing Props.FindEmptyContainer< T > (Thing target) inline
Type Constraints
T : Trait
Definition at line 377 of file Props.cs.
                                                             : Trait
    {
        foreach (Thing thing in Things)
        {
            if (thing.trait is T && !thing.things.IsFull(target))
            {
                return thing;
            }
        }
        return null;
    }
References ThingContainer.IsFull(), Card.things, Things, and Card.trait.
FindShared()
Thing Props.FindShared (string id) inline
Definition at line 401 of file Props.cs.
    {
        return Find(id, -1, -1, shared: true);
    }
References Find().
GetAvailableThing()
Thing Props.GetAvailableThing (string id, int idMat) inline
Definition at line 187 of file Props.cs.
    {
        PropSet propSet = cardMap.TryGetValue(id);
        if (propSet == null)
        {
            return null;
        }
        foreach (Card item in propSet)
        {
            if (item.idMaterial == idMat)
            {
                return item as Thing;
            }
        }
        return null;
    }
References cardMap, and item.
GetNum()
int Props.GetNum (string id, bool onlyShared = false) inline
Definition at line 427 of file Props.cs.
    {
        int num = 0;
        foreach (Card item in cardMap.GetOrCreate(id))
        {
            if (!onlyShared || (item.parentThing != null && item.parentThing.IsSharedContainer))
            {
                num += item.Num;
            }
        }
        return num;
    }
References cardMap, and item.
Referenced by FactionBranch.CountPasture(), and GetNumStockedAndRoaming().
GetNumStockedAndRoaming()
static int Props.GetNumStockedAndRoaming (string id) inline static
Definition at line 440 of file Props.cs.
    {
        return EClass._map.Stocked.cardMap.GetOrCreate(id).num + EClass._map.Roaming.GetNum(id);
    }
References EClass._map, cardMap, GetNum(), Map.Roaming, and Map.Stocked.
Init()
void Props.Init () inline
Definition at line 41 of file Props.cs.
    {
        if (categoryMap.Count > 0)
        {
            return;
        }
        foreach (SourceCategory.Row row in EClass.sources.categories.rows)
        {
            categoryMap.Add(row.id, new PropSetCategory
            {
                source = row
            });
        }
        foreach (PropSetCategory value in categoryMap.Values)
        {
            if (value.source.parent != null)
            {
                value.parent = categoryMap[value.source.parent.id];
            }
        }
    }
References SourceManager.categories, categoryMap, PropSetCategory.source, and EClass.sources.
Referenced by PropsManager.Init().
ListThingsInCategory()
List< Thing > Props.ListThingsInCategory (SourceCategory::Row cat) inline
Definition at line 315 of file Props.cs.
    {
        List<Thing> list = new List<Thing>();
        foreach (Thing thing in Things)
        {
            if (thing.category.IsChildOf(cat))
            {
                list.Add(thing);
            }
        }
        return list;
    }
References Card.category, and Things.
Referenced by LayerResource.ShowThings().
ListThingStack()
ThingStack Props.ListThingStack (Recipe::Ingredient ing, StockSearchMode searchMode) inline
Definition at line 204 of file Props.cs.
    {
        string id2 = ing.id;
        int idMat = -1;
        string tag = (ing.tag.IsEmpty() ? null : ing.tag);
        ThingStack stack = new ThingStack
        {
            val = idMat
        };
        _ = EClass.pc.pos.cell.room;
        if (ing.useCat)
        {
            FindCat(id2);
            foreach (string item in ing.idOther)
            {
                FindCat(item);
            }
        }
        else
        {
            Find(id2);
            foreach (string item2 in ing.idOther)
            {
                Find(item2);
            }
        }
        if (ing.ingType == Recipe.IngType.CreativeFood)
        {
            FindAnyFood();
        }
        stack.list.Sort(UIList.SortMode.ByCategory);
        return stack;
        void Find(string id)
        {
            bool isOrigin = EClass.sources.cards.map[id].isOrigin;
            EClass.pc.things.Foreach(delegate(Thing t)
            {
                if (!t.isEquipped && (!(t.id != id) || (isOrigin && t.source._origin == id)))
                {
                    TryAdd(t);
                }
            });
            if (EClass._zone.IsPCFaction || EClass._zone is Zone_Tent || EClass.debug.enable)
            {
                foreach (Card item3 in cardMap.GetOrCreate(id))
                {
                    if (!(item3.parent is Thing thing2) || (thing2.c_lockLv == 0 && thing2.trait.CanUseContent))
                    {
                        TryAdd(item3.Thing);
                    }
                }
            }
        }
        void FindAnyFood()
        {
            EClass.pc.things.Foreach(delegate(Thing t)
            {
                if (!t.isEquipped)
                {
                    TryAdd(t);
                }
            });
            if (EClass._zone.IsPCFaction || EClass._zone is Zone_Tent || EClass.debug.enable)
            {
                foreach (Card item4 in all)
                {
                    if (!(item4.parent is Thing thing) || (thing.c_lockLv == 0 && thing.trait.CanUseContent))
                    {
                        TryAdd(item4.Thing);
                    }
                }
            }
        }
        void FindCat(string id)
        {
            SourceCategory.Row cat = EClass.sources.categories.map[id];
            EClass.pc.things.Foreach(delegate(Thing t)
            {
                if (!t.isEquipped && t.category.IsChildOf(cat.id) && !t.IsExcludeFromCraft(ing))
                {
                    stack.Add(t);
                }
            });
            if (EClass._zone.IsPCFaction || EClass._zone is Zone_Tent || EClass.debug.enable)
            {
                foreach (Thing thing3 in things)
                {
                    Card obj = thing3.parent as Card;
                    if (obj != null && obj.c_lockLv == 0 && thing3.category.IsChildOf(cat.id) && !thing3.IsExcludeFromCraft(ing))
                    {
                        stack.Add(thing3);
                    }
                }
            }
        }
        void TryAdd(Thing t)
        {
            if ((tag == null || t.Thing.material.tag.Contains(tag)) && (idMat == -1 || t.material.id == idMat) && !t.IsExcludeFromCraft(ing))
            {
                stack.Add(t.Thing);
            }
        }
        void TryAdd(Thing t)
        {
            if (t.HasElement(10) && !(t.trait is TraitFoodFishSlice) && !t.category.IsChildOf("seasoning") && !t.category.IsChildOf("meal") && !t.IsExcludeFromCraft(ing) && !stack.list.Contains(t))
            {
                stack.Add(t.Thing);
            }
        }
    }
References EClass._zone, ThingStack.Add(), all, Card.c_lockLv, cardMap, SourceManager.cards, SourceManager.categories, Card.category, Point.cell, EClass.debug, CoreDebug.enable, Find(), ThingContainer.Foreach(), Card.HasElement(), Card.id, SourceCategory.Row.id, Thing.isEquipped, Card.IsExcludeFromCraft(), Zone.IsPCFaction, item, ThingStack.list, SourceCard.map, Card.material, Card.parent, EClass.pc, Card.pos, Cell.room, Thing.source, EClass.sources, Card.Thing, Card.things, things, and Card.trait.
Referenced by QuestTrackCraft.GetDetail(), Recipe.IsCraftable(), DropdownGrid.ListIngredients(), UIRecipeInfo.RefreshList(), DropdownGrid.TrySelect(), and ButtonGrid.WriteReqMat().
ListThingStacksInCategory() [1/2]
Dictionary< string, ThingStack > Props.ListThingStacksInCategory (SourceCategory::Row cat) inline
Definition at line 328 of file Props.cs.
    {
        Dictionary<string, ThingStack> dictionary = new Dictionary<string, ThingStack>();
        foreach (Thing thing in Things)
        {
            ListThingStacksInCategory(cat, dictionary, thing);
        }
        return dictionary;
    }
References ListThingStacksInCategory(), and Things.
Referenced by ListThingStacksInCategory().
ListThingStacksInCategory() [2/2]
void Props.ListThingStacksInCategory (SourceCategory::Row cat, Dictionary< string, ThingStack > stacks, Thing t) inline private
Definition at line 338 of file Props.cs.
    {
        if (EClass.sources.categories.map[t.source.category].IsChildOf(cat))
        {
            ThingStack thingStack = stacks.TryGetValue(t.id);
            if (thingStack == null)
            {
                thingStack = new ThingStack();
                stacks.Add(t.id, thingStack);
            }
            thingStack.count += t.Num;
            thingStack.list.Add(t);
        }
    }
References ActPlan.List.Add(), SourceManager.categories, Card.id, ThingStack.list, Card.Num, Thing.source, and EClass.sources.
OnNumChange()
void Props.OnNumChange (Card c, int a) inline
Definition at line 160 of file Props.cs.
    {
        if (!c.isChara)
        {
            weight += a;
            categoryMap[c.category.id].OnChangeNum(a);
            cardMap[c.id].OnChangeNum(a);
            if (!c.Thing.source.workTag.IsEmpty())
            {
                workMap[c.Thing.source.workTag].OnChangeNum(a);
            }
        }
    }
References cardMap, Card.category, categoryMap, Card.id, Card.isChara, Thing.source, Card.Thing, weight, and workMap.
Referenced by Card.ModNum().
Remove()
void Props.Remove (Card t) inline
Definition at line 115 of file Props.cs.
    {
        t.props = null;
        t.placeState = PlaceState.roaming;
        if (t.isChara)
        {
            raceMap[t.Chara.race.id].Remove(t);
            return;
        }
        foreach (Thing thing in t.things)
        {
            if (thing.props != null)
            {
                thing.props.Remove(thing);
            }
        }
        if (!all.Contains(t))
        {
            Debug.LogError(t?.ToString() + " isn't in " + this);
            return;
        }
        weight -= t.Num;
        all.Remove(t);
        things.Remove(t.Thing);
        cardMap[t.id].Remove(t);
        if (t.sourceCard.origin != null)
        {
            cardMap[t.sourceCard.origin.id].Remove(t);
        }
        categoryMap[t.category.id].Remove(t);
        if (!t.Thing.source.workTag.IsEmpty())
        {
            workMap[t.Thing.source.workTag].Remove(t);
        }
        if (t.IsContainer)
        {
            containers.Remove(t.Thing);
        }
        traits.OnRemoveCard(t);
        if (t.isDeconstructing)
        {
            EClass._map.props.deconstructing.Remove(t);
        }
    }
References EClass._map, all, cardMap, categoryMap, Card.Chara, containers, Debug, PropsManager.deconstructing, Card.isChara, TraitManager.OnRemoveCard(), Card.props, Map.props, Chara.race, raceMap, PropSet.Remove(), Remove(), Card.things, things, traits, weight, and workMap.
Referenced by Add(), PropsManager.OnSetPlaceState(), Remove(), Card.RemoveThing(), and Card.SetPlaceState().
ShouldListAsResource()
bool Props.ShouldListAsResource (Thing t) inline
Definition at line 174 of file Props.cs.
    {
        if (!(t.parent is Card card))
        {
            return false;
        }
        if (card.isSale || !card.trait.CanUseContent)
        {
            return false;
        }
        return !t.c_isImportant;
    }
References Card.c_isImportant, card, and Card.parent.
Referenced by BuildMenu._Search(), UIDragGridIngredients.Refresh(), and BuildMenu.RefreshCategory().
Validate()
void Props.Validate () inline
Definition at line 445 of file Props.cs.
    {
        foreach (KeyValuePair<string, PropSet> item in cardMap)
        {
            int num = 0;
            foreach (Card item2 in item.Value)
            {
                num += item2.Num;
            }
            if (num != item.Value.num)
            {
                Debug.LogError("prop num:" + item.Key + " " + item.Value.num + "/" + num);
            }
        }
    }
References cardMap, Debug, item, and Card.Num.
Referenced by CoreDebug.ValidateData().
Member Data Documentation
all
PropSet Props.all = new PropSet()
Definition at line 8 of file Props.cs.
Referenced by Add(), Chara.FindBed(), ListThingStack(), PropsManager.OnSetPlaceState(), LayerHome.RefreshSpots(), Remove(), WidgetSearch.Search(), Chara.TryAssignBed(), and CoreDebug.UpdateInput().
cardMap
Dictionary<string, PropSet> Props.cardMap = new Dictionary<string, PropSet>()
Definition at line 10 of file Props.cs.
Referenced by WidgetStockTracker._Refresh(), Add(), Find(), GetAvailableThing(), GetNum(), GetNumStockedAndRoaming(), ListThingStack(), OnNumChange(), UIRecipeInfo.Refresh(), Remove(), ButtonResourceTrack.SetProp(), HitSummary.SetRecipe(), and Validate().
categoryMap
Dictionary<string, PropSetCategory> Props.categoryMap = new Dictionary<string, PropSetCategory>()
Definition at line 12 of file Props.cs.
Referenced by WidgetStockTracker._Refresh(), Add(), Init(), OnNumChange(), LayerResource.RefreshCategory(), Remove(), and ButtonResourceTrack.SetCat().
containers
List<Thing> Props.containers = new List<Thing>()
Definition at line 22 of file Props.cs.
Referenced by Add(), Remove(), Zone.TryAddThingInSharedContainer(), Zone.TryGetThingFromSharedContainer(), Chara.TryPutSharedItems(), and Chara.TryTakeSharedItems().
maxWeight
int Props.maxWeight = 100
Definition at line 25 of file Props.cs.
Referenced by LayerResource.OnInit().
raceMap
Dictionary<string, PropSet> Props.raceMap = new Dictionary<string, PropSet>()
Definition at line 14 of file Props.cs.
Referenced by Add(), GameUpdater.SurfaceUpdater.FixedUpdate(), and Remove().
things
List<Thing> Props.things = new List<Thing>()
Definition at line 20 of file Props.cs.
Referenced by Add(), Map.FindThing(), QuestDeliver.ListDestThing(), ListThingStack(), and Remove().
traits
TraitManager Props.traits = new TraitManager()
Definition at line 18 of file Props.cs.
Referenced by Add(), Zone.AddRandomVisitor(), VirtualDate.BuildSunMap(), AIAct.DoGoto< T >(), AIAct.DoGotoSpot< T >(), AI_Pray.GetAltar(), Zone.GetRandomSpot< T >(), Zone.GetSpawnPos(), AI_Grab< T >.GetTarget(), Chara.IsInSpot< T >(), Map.PutAway(), DramaOutcome.PutOutFire(), FactionBranch.Recruit(), Map.RefreshSunMap(), Remove(), AI_Bladder.Run(), AI_Cook.Run(), AI_GotoHearth.Run(), AI_Idle.Run(), AI_LeaveMap.Run(), AI_Offer.Run(), GoalSpot.Run(), and Zone.TryAddThingInSpot< T >().
weight
int Props.weight
Definition at line 27 of file Props.cs.
Referenced by Add(), LayerResource.OnInit(), OnNumChange(), and Remove().
workMap
Dictionary<string, PropSet> Props.workMap = new Dictionary<string, PropSet>()
Definition at line 16 of file Props.cs.
Referenced by Add(), Map.FindThing(), OnNumChange(), and Remove().
Property Documentation
Count
int Props.Count get
Definition at line 39 of file Props.cs.
IsInstalled
virtual bool Props.IsInstalled get
Definition at line 33 of file Props.cs.
IsRoaming
virtual bool Props.IsRoaming get
Definition at line 31 of file Props.cs.
IsStocked
virtual bool Props.IsStocked get
Definition at line 29 of file Props.cs.
state
virtual PlaceState Props.state get
Definition at line 35 of file Props.cs.
Referenced by Add().
Things
List<Thing> Props.Things get
Definition at line 37 of file Props.cs.
Referenced by BuildMenu._Search(), Zone.Deactivate(), Find(), Find< T >(), FindEmptyContainer< T >(), ListThingsInCategory(), ListThingStacksInCategory(), UIDragGridIngredients.Refresh(), and BuildMenu.RefreshCategory().
The documentation for this class was generated from the following file:
Elin/Props.cs