Elin Decompiled Documentation: SkinDecoActor Class Reference
SkinDecoActor Class Reference
Public Member Functions
void Refresh ()
Public Attributes
SkinDeco owner
Image image
Shadow shadow
Detailed Description
Definition at line 4 of file SkinDecoActor.cs.
Member Function Documentation
Refresh()
void SkinDecoActor.Refresh () inline
Definition at line 12 of file SkinDecoActor.cs.
    {
        image.SetNativeSize();
        Vector2 sizeDelta = this.Rect().sizeDelta;
        this.Rect().sizeDelta = new Vector2(sizeDelta.x * (float)owner.sx * 0.01f, sizeDelta.y * (float)owner.sy * 0.01f);
        image.color = owner.color;
        base.transform.localEulerAngles = new Vector3(0f, 0f, owner.rz * 45);
        base.transform.localScale = new Vector3((!owner.reverse) ? 1 : (-1), 1f, 1f);
        shadow.enabled = owner.shadow;
        shadow.effectDistance = new Vector2(owner.reverse ? (-3) : 3, -3f);
        if (owner.bottom)
        {
            base.transform.SetSiblingIndex(1);
        }
    }
References SkinDeco.bottom, SkinDeco.color, image, owner, SkinDeco.reverse, SkinDeco.rz, SkinDeco.shadow, SkinDeco.sx, and SkinDeco.sy.
Referenced by Widget.InstantiateDeco(), LayerSkinDeco.OnKill(), and LayerSkinDeco.OnUpdateInput().
Member Data Documentation
image
Image SkinDecoActor.image
Definition at line 8 of file SkinDecoActor.cs.
Referenced by Refresh().
owner
SkinDeco SkinDecoActor.owner
Definition at line 6 of file SkinDecoActor.cs.
Referenced by LayerSkinDeco.OnUpdateInput(), and Refresh().
shadow
Shadow SkinDecoActor.shadow
Definition at line 10 of file SkinDecoActor.cs.
The documentation for this class was generated from the following file:
Elin/Plugins.UI/SkinDecoActor.cs