Elin Decompiled Documentation: FastString Class Reference
FastString Class Reference
Public Member Functions
FastString (int initialCapacity=32)
bool IsEmpty ()
override string ToString ()
bool IsModified (int newControlValue)
bool IsModified (object newControlValue)
void Set (string str)
void Set (object str)
void Set< T1, T2 > (T1 str1, T2 str2)
void Set< T1, T2, T3 > (T1 str1, T2 str2, T3 str3)
void Set< T1, T2, T3, T4 > (T1 str1, T2 str2, T3 str3, T4 str4)
void Set (params object[] str)
FastString Clear ()
FastString Append (string value)
FastString Append (object value)
FastString Append (int value)
FastString Append (float valueF)
FastString Replace (string oldStr, string newStr)
Private Member Functions
void ReallocateIFN (int nbCharsToAdd)
Private Attributes
string m_stringGenerated = ""
bool m_isStringGenerated
char[] m_buffer
int m_bufferPos
int m_charsCapacity
List< char > m_replacement
object m_valueControl
int m_valueControlInt = int.MinValue
Detailed Description
Definition at line 4 of file FastString.cs.
Constructor & Destructor Documentation
FastString()
FastString.FastString (int initialCapacity = 32) inline
Definition at line 22 of file FastString.cs.
    {
        m_buffer = new char[m_charsCapacity = initialCapacity];
    }
References m_buffer, and m_charsCapacity.
Member Function Documentation
Append() [1/4]
FastString FastString.Append (float valueF) inline
Definition at line 164 of file FastString.cs.
    {
        double num = valueF;
        m_isStringGenerated = false;
        ReallocateIFN(32);
        if (num == 0.0)
        {
            m_buffer[m_bufferPos++] = '0';
            return this;
        }
        if (num < 0.0)
        {
            num = 0.0 - num;
            m_buffer[m_bufferPos++] = '-';
        }
        int num2 = 0;
        while (num < 1000000.0)
        {
            num *= 10.0;
            num2++;
        }
        long num3 = (long)Math.Round(num);
        int num4 = 0;
        bool flag = true;
        while (num3 != 0L || num2 >= 0)
        {
            if (num3 % 10 != 0L || num2 <= 0)
            {
                flag = false;
            }
            if (!flag)
            {
                m_buffer[m_bufferPos + num4++] = (char)(48 + num3 % 10);
            }
            if (--num2 == 0 && !flag)
            {
                m_buffer[m_bufferPos + num4++] = '.';
            }
            num3 /= 10;
        }
        m_bufferPos += num4;
        for (int num5 = num4 / 2 - 1; num5 >= 0; num5--)
        {
            char c = m_buffer[m_bufferPos - num5 - 1];
            m_buffer[m_bufferPos - num5 - 1] = m_buffer[m_bufferPos - num4 + num5];
            m_buffer[m_bufferPos - num4 + num5] = c;
        }
        return this;
    }
References m_buffer, m_bufferPos, m_isStringGenerated, and ReallocateIFN().
Append() [2/4]
FastString FastString.Append (int value) inline
Definition at line 138 of file FastString.cs.
    {
        ReallocateIFN(16);
        if (value < 0)
        {
            value = -value;
            m_buffer[m_bufferPos++] = '-';
        }
        int num = 0;
        do
        {
            m_buffer[m_bufferPos++] = (char)(48 + value % 10);
            value /= 10;
            num++;
        }
        while (value != 0);
        for (int num2 = num / 2 - 1; num2 >= 0; num2--)
        {
            char c = m_buffer[m_bufferPos - num2 - 1];
            m_buffer[m_bufferPos - num2 - 1] = m_buffer[m_bufferPos - num + num2];
            m_buffer[m_bufferPos - num + num2] = c;
        }
        m_isStringGenerated = false;
        return this;
    }
References m_buffer, m_bufferPos, m_isStringGenerated, and ReallocateIFN().
Append() [3/4]
FastString FastString.Append (object value) inline
Definition at line 132 of file FastString.cs.
    {
        Append(value.ToString());
        return this;
    }
References Append().
Append() [4/4]
FastString FastString.Append (string value) inline
Definition at line 119 of file FastString.cs.
    {
        ReallocateIFN(value.Length);
        int length = value.Length;
        for (int i = 0; i < length; i++)
        {
            m_buffer[m_bufferPos + i] = value[i];
        }
        m_bufferPos += length;
        m_isStringGenerated = false;
        return this;
    }
References m_buffer, m_bufferPos, m_isStringGenerated, and ReallocateIFN().
Referenced by WidgetStockTracker._Refresh(), Append(), ItemQuestTracker.Refresh(), WidgetTracker.Refresh(), Set(), Set< T1, T2 >(), Set< T1, T2, T3 >(), and Set< T1, T2, T3, T4 >().
Clear()
FastString FastString.Clear () inline
Definition at line 112 of file FastString.cs.
    {
        m_bufferPos = 0;
        m_isStringGenerated = false;
        return this;
    }
References m_bufferPos, and m_isStringGenerated.
Referenced by WidgetStockTracker._Refresh(), ItemQuestTracker.Refresh(), WidgetTracker.Refresh(), Set(), Set< T1, T2 >(), Set< T1, T2, T3 >(), and Set< T1, T2, T3, T4 >().
IsEmpty()
bool FastString.IsEmpty () inline
Definition at line 27 of file FastString.cs.
    {
        if (!m_isStringGenerated)
        {
            return m_bufferPos == 0;
        }
        return m_stringGenerated == null;
    }
References m_bufferPos, m_isStringGenerated, and m_stringGenerated.
Referenced by WidgetTracker.Refresh().
IsModified() [1/2]
bool FastString.IsModified (int newControlValue) inline
Definition at line 46 of file FastString.cs.
    {
        bool num = newControlValue != m_valueControlInt;
        if (num)
        {
            m_valueControlInt = newControlValue;
        }
        return num;
    }
References m_valueControlInt.
IsModified() [2/2]
bool FastString.IsModified (object newControlValue) inline
Definition at line 56 of file FastString.cs.
    {
        bool num = !newControlValue.Equals(m_valueControl);
        if (num)
        {
            m_valueControl = newControlValue;
        }
        return num;
    }
References m_valueControl.
ReallocateIFN()
void FastString.ReallocateIFN (int nbCharsToAdd) inline private
Definition at line 262 of file FastString.cs.
    {
        if (m_bufferPos + nbCharsToAdd > m_charsCapacity)
        {
            m_charsCapacity = Math.Max(m_charsCapacity + nbCharsToAdd, m_charsCapacity * 2);
            char[] array = new char[m_charsCapacity];
            m_buffer.CopyTo(array, 0);
            m_buffer = array;
        }
    }
References m_buffer, m_bufferPos, and m_charsCapacity.
Referenced by Append(), and Replace().
Replace()
FastString FastString.Replace (string oldStr, string newStr) inline
Definition at line 214 of file FastString.cs.
    {
        if (m_bufferPos == 0)
        {
            return this;
        }
        if (m_replacement == null)
        {
            m_replacement = new List<char>();
        }
        for (int i = 0; i < m_bufferPos; i++)
        {
            bool flag = false;
            if (m_buffer[i] == oldStr[0])
            {
                int j;
                for (j = 1; j < oldStr.Length && m_buffer[i + j] == oldStr[j]; j++)
                {
                }
                flag = j >= oldStr.Length;
            }
            if (flag)
            {
                i += oldStr.Length - 1;
                if (newStr != null)
                {
                    for (int k = 0; k < newStr.Length; k++)
                    {
                        m_replacement.Add(newStr[k]);
                    }
                }
            }
            else
            {
                m_replacement.Add(m_buffer[i]);
            }
        }
        ReallocateIFN(m_replacement.Count - m_bufferPos);
        for (int l = 0; l < m_replacement.Count; l++)
        {
            m_buffer[l] = m_replacement[l];
        }
        m_bufferPos = m_replacement.Count;
        m_replacement.Clear();
        m_isStringGenerated = false;
        return this;
    }
References m_buffer, m_bufferPos, m_isStringGenerated, m_replacement, and ReallocateIFN().
Set() [1/3]
void FastString.Set (object str) inline
Definition at line 74 of file FastString.cs.
    {
        Set(str.ToString());
    }
References Set().
Set() [2/3]
void FastString.Set (params object[] str) inline
Definition at line 103 of file FastString.cs.
    {
        Clear();
        for (int i = 0; i < str.Length; i++)
        {
            Append(str[i]);
        }
    }
References Append(), and Clear().
Set() [3/3]
void FastString.Set (string str) inline
Definition at line 66 of file FastString.cs.
    {
        Clear();
        Append(str);
        m_stringGenerated = str;
        m_isStringGenerated = true;
    }
References Append(), Clear(), m_isStringGenerated, and m_stringGenerated.
Referenced by WidgetStockTracker._Refresh(), ItemQuestTracker.Refresh(), WidgetTracker.Refresh(), and Set().
Set< T1, T2 >()
void FastString.Set< T1, T2 > (T1 str1, T2 str2) inline
Definition at line 79 of file FastString.cs.
    {
        Clear();
        Append(str1);
        Append(str2);
    }
References Append(), and Clear().
Set< T1, T2, T3 >()
void FastString.Set< T1, T2, T3 > (T1 str1, T2 str2, T3 str3) inline
Definition at line 86 of file FastString.cs.
    {
        Clear();
        Append(str1);
        Append(str2);
        Append(str3);
    }
References Append(), and Clear().
Set< T1, T2, T3, T4 >()
void FastString.Set< T1, T2, T3, T4 > (T1 str1, T2 str2, T3 str3, T4 str4) inline
Definition at line 94 of file FastString.cs.
    {
        Clear();
        Append(str1);
        Append(str2);
        Append(str3);
        Append(str4);
    }
References Append(), and Clear().
ToString()
override string FastString.ToString () inline
Definition at line 36 of file FastString.cs.
    {
        if (!m_isStringGenerated)
        {
            m_stringGenerated = new string(m_buffer, 0, m_bufferPos);
            m_isStringGenerated = true;
        }
        return m_stringGenerated;
    }
References m_buffer, m_bufferPos, m_isStringGenerated, and m_stringGenerated.
Referenced by WidgetStockTracker._Refresh(), ItemQuestTracker.Refresh(), and WidgetTracker.Refresh().
Member Data Documentation
m_buffer
char [] FastString.m_buffer private
Definition at line 10 of file FastString.cs.
Referenced by Append(), FastString(), ReallocateIFN(), Replace(), and ToString().
m_bufferPos
int FastString.m_bufferPos private
Definition at line 12 of file FastString.cs.
Referenced by Append(), Clear(), IsEmpty(), ReallocateIFN(), Replace(), and ToString().
m_charsCapacity
int FastString.m_charsCapacity private
Definition at line 14 of file FastString.cs.
Referenced by FastString(), and ReallocateIFN().
m_isStringGenerated
bool FastString.m_isStringGenerated private
Definition at line 8 of file FastString.cs.
Referenced by Append(), Clear(), IsEmpty(), Replace(), Set(), and ToString().
m_replacement
List<char> FastString.m_replacement private
Definition at line 16 of file FastString.cs.
Referenced by Replace().
m_stringGenerated
string FastString.m_stringGenerated = "" private
Definition at line 6 of file FastString.cs.
Referenced by IsEmpty(), Set(), and ToString().
m_valueControl
object FastString.m_valueControl private
Definition at line 18 of file FastString.cs.
Referenced by IsModified().
m_valueControlInt
int FastString.m_valueControlInt = int.MinValue private
Definition at line 20 of file FastString.cs.
Referenced by IsModified().
The documentation for this class was generated from the following file:
Elin/Plugins.basecore/FastString.cs