Elin Decompiled Documentation: UINote Class Reference
UINote Class Reference
Public Member Functions
void Clear ()
void Build ()
void Space (int sizeY=0, int sizeX=1)
UINote AddNote (string id)
UIItem AddHeader (string text, Sprite sprite=null)
UIItem AddHeaderCard (string text, Sprite sprite=null)
UIItem AddHeaderTopic (string text, Sprite sprite=null)
UIItem AddHeader (string id, string text, Sprite sprite=null)
UIItem AddText (string text, FontColor color=FontColor.DontChange)
UIItem AddText (string id, string text, FontColor color=FontColor.DontChange)
UIItem AddText (string id, string text, Color color)
UIItem AddItem (string id)
UIItem AddTopic (string id, string text, string value=null)
UIItem AddTopic (string text, string value=null)
void AddImage (Sprite sprite)
void AddImage (string idFile)
UIButton AddButton (string text, Action onClick)
UIButton AddButtonLink (string text, string url)
UIDropdown AddDropdown (string id="DropdownDefault")
UIButton AddToggle (string idLang="", bool isOn=false, Action< bool > action=null)
Transform AddPrefab (string path)
T AddExtra< T > (string path)
Public Attributes
RectTransform target
UINoteProfile prof
SkinType skinType
string idDefaultText
LayoutGroup layout
RectTransform cur
bool extraRebuild
Private Member Functions
void Awake ()
UIItem Load (string path)
T Load< T > (string path)
Private Attributes
SkinRootStatic oldTempSkin
Detailed Description
Definition at line 5 of file UINote.cs.
Member Function Documentation
AddButton()
UIButton UINote.AddButton (string text, Action onClick) inline
Definition at line 182 of file UINote.cs.
    {
        UIButton uIButton = Load<UIButton>("UI/Element/Button/ButtonNote");
        uIButton.mainText.text = text;
        uIButton.onClick.AddListener(delegate
        {
            onClick();
        });
        return uIButton;
    }
Referenced by WindowCharaMini.Refresh().
AddButtonLink()
UIButton UINote.AddButtonLink (string text, string url) inline
Definition at line 193 of file UINote.cs.
    {
        UIButton button = Load<UIItem>("UI/Element/Item/ItemNoteLink").button1;
        button.mainText.text = text;
        button.onClick.AddListener(delegate
        {
            SE.Click();
            Application.OpenURL(url);
        });
        return button;
    }
Referenced by UIBook.Page.BuildNote().
AddDropdown()
UIDropdown UINote.AddDropdown (string id = "DropdownDefault") inline
Definition at line 205 of file UINote.cs.
    {
        return Load<UIDropdown>("UI/Element/Other/" + id);
    }
AddExtra< T >()
T UINote.AddExtra< T > (string path) inline
Type Constraints
T : Component
Definition at line 223 of file UINote.cs.
                                              : Component
    {
        return Util.Instantiate<T>("UI/Element/Note/Extra/" + path, this);
    }
References Util.
AddHeader() [1/2]
UIItem UINote.AddHeader (string id, string text, Sprite sprite = null) inline
Definition at line 94 of file UINote.cs.
    {
        UIItem uIItem = Load("UI/Element/Header/" + id);
        uIItem.text1.text = text.lang();
        if ((bool)uIItem.image1)
        {
            if ((bool)sprite)
            {
                uIItem.image1.sprite = sprite;
                uIItem.image1.SetNativeSize();
            }
            else
            {
                uIItem.image1.SetActive(enable: false);
            }
        }
        return uIItem;
    }
References UIItem.image1, and Load().
AddHeader() [2/2]
UIItem UINote.AddHeader (string text, Sprite sprite = null) inline
Definition at line 79 of file UINote.cs.
    {
        return AddHeader("HeaderNote", text, sprite);
    }
References AddHeader().
Referenced by Element._WriteNote(), Thing.AddAttackEvaluation(), AddHeader(), Element.AddHeaderAbility(), AddHeaderCard(), AddHeaderTopic(), UIBook.Page.BuildNote(), Dialog.Gift(), UICharaMaker.ListJob(), UICharaMaker.ListRace(), BaseListPeople.OnInstantiate(), InvOwnerEquip.OnWriteNote(), InvOwnerGene.OnWriteNote(), Dialog.Recipe(), WindowCharaMini.Refresh(), WindowCharaMini.RefreshEquipment(), WindowChara.RefreshEquipment(), ContentCodex.RefreshInfo(), UIHomeInfo.RefreshInfo(), UIFactionInfo.SetFaction(), UIFactionInfo.SetReligion(), Faction.SetTaxTooltip(), UIFactionInfo.SetZone(), LayerInfo.SetZone(), BaseListPeople.WriteHobbies(), BaseHomeResource.WriteNote(), FortuneRollData.WriteNote(), Happiness.WriteNote(), HomeResourceSkill.WriteNote(), HomeResourceWorth.WriteNote(), ResearchPlan.WriteNote(), SourceJob.Row.WriteNote(), BaseStats.WriteNote(), Thing.WriteNote(), UIMapSelector.WriteNote(), and Feat.WritePurchaseReq().
AddHeaderCard()
UIItem UINote.AddHeaderCard (string text, Sprite sprite = null) inline
Definition at line 84 of file UINote.cs.
    {
        return AddHeader("HeaderCard", text, sprite);
    }
References AddHeader().
Referenced by UICardInfo.SetBlock(), GridItemRecipe.SetButton(), ButtonGrid.SetCraftRecipe(), UICardInfo.SetFloor(), UICardInfo.SetLiquid(), UICardInfo.SetObj(), UICardInfo.SetRecipe(), BaseArea.WriteNote(), BlockInfo.WriteNote(), Chara.WriteNote(), EloPos.WriteNote(), ObjInfo.WriteNote(), TaskPoint.WriteNote(), and Thing.WriteNote().
AddHeaderTopic()
UIItem UINote.AddHeaderTopic (string text, Sprite sprite = null) inline
Definition at line 89 of file UINote.cs.
    {
        return AddHeader("HeaderTopic", text, sprite);
    }
References AddHeader().
Referenced by UICharaMaker.Refresh(), UIHomeInfo.RefreshInfo(), UICardInfo.SetRecipe(), UIFactionInfo.SetZone(), UIZoneInfo.SetZone(), EloPos.WriteNote(), Recipe.WriteReqFactory(), ButtonGrid.WriteReqMat(), and Recipe.WriteReqSkill().
AddImage() [1/2]
void UINote.AddImage (Sprite sprite) inline
Definition at line 158 of file UINote.cs.
    {
        Image image = Load("UI/Element/Deco/ImageNote").image1;
        image.sprite = sprite;
        image.SetNativeSize();
        image.transform.parent.Rect().sizeDelta = image.Rect().sizeDelta;
        if (sprite == null)
        {
            image.transform.parent.SetActive(enable: false);
        }
    }
References UIItem.image1, and Load().
Referenced by UIBook.Page.BuildNote().
AddImage() [2/2]
void UINote.AddImage (string idFile) inline
Definition at line 170 of file UINote.cs.
    {
        Image image = Load("UI/Element/Deco/ImageNote").image1;
        Sprite sprite2 = (image.sprite = Resources.Load<Sprite>("Media/Graphics/Image/" + idFile));
        image.SetNativeSize();
        image.transform.parent.Rect().sizeDelta = image.Rect().sizeDelta;
        if (sprite2 == null)
        {
            image.transform.parent.SetActive(enable: false);
        }
    }
References UIItem.image1, and Load().
AddItem()
UIItem UINote.AddItem (string id) inline
Definition at line 139 of file UINote.cs.
    {
        return Load("UI/Element/Item/" + id);
    }
References Load().
Referenced by Element._WriteNote(), WindowCharaMini.Refresh(), and WindowChara.RefreshNote().
AddNote()
UINote UINote.AddNote (string id) inline
Definition at line 72 of file UINote.cs.
    {
        UINote componentInChildren = Load<Transform>("UI/Element/Note/" + id).gameObject.GetComponentInChildren<UINote>();
        extraRebuild = true;
        return componentInChildren;
    }
References extraRebuild.
Referenced by UIBook.Page.BuildNote().
AddPrefab()
Transform UINote.AddPrefab (string path) inline
Definition at line 218 of file UINote.cs.
    {
        return Util.Instantiate(path, this);
    }
References Util.
Referenced by LayerGacha.PlayGacha().
AddText() [1/3]
UIItem UINote.AddText (string id, string text, Color color) inline
Definition at line 132 of file UINote.cs.
    {
        UIItem uIItem = Load("UI/Element/Text/" + id.IsEmpty(idDefaultText.IsEmpty("NoteText")));
        uIItem.text1.SetText(text.lang(), color);
        return uIItem;
    }
References idDefaultText, Load(), UIText.SetText(), and UIItem.text1.
AddText() [2/3]
UIItem UINote.AddText (string id, string text, FontColor color = FontColor::DontChange) inline
Definition at line 118 of file UINote.cs.
    {
        UIItem uIItem = Load("UI/Element/Text/" + id.IsEmpty(idDefaultText.IsEmpty("NoteText")));
        if (color != 0)
        {
            uIItem.text1.SetText(text.lang(), color);
        }
        else
        {
            uIItem.text1.SetText(text.lang());
        }
        return uIItem;
    }
References idDefaultText, Load(), UIText.SetText(), and UIItem.text1.
AddText() [3/3]
UIItem UINote.AddText (string text, FontColor color = FontColor::DontChange) inline
Definition at line 113 of file UINote.cs.
    {
        return AddText(null, text, color);
    }
References AddText().
Referenced by Element._WriteNote(), Element.AddEncNote(), Element.BonusInfo.AddFix(), Element.BonusInfo.AddText(), AddText(), UIBook.Page.BuildNote(), Dialog.InputName(), UICharaMaker.ListJob(), UICharaMaker.ListRace(), Policy.ModHappiness(), ActionMode.OnShowExtraHint(), InvOwnerEquip.OnWriteNote(), InvOwnerGene.OnWriteNote(), LayerGacha.PlayGacha(), Dialog.Recipe(), UICharaMaker.Refresh(), UIRecipeInfo.Refresh(), WindowCharaMini.Refresh(), WindowCharaMini.RefreshEquipment(), WindowChara.RefreshEquipment(), UIHomeInfo.RefreshInfo(), LayerLoadGame.RefreshInfo(), WindowChara.RefreshNote(), UICardInfo.SetBlock(), ButtonGrid.SetCard(), ButtonGrid.SetCraftRecipe(), UICardInfo.SetFloor(), ButtonGrid.SetIngredient(), UICardInfo.SetLiquid(), UICardInfo.SetObj(), UICardInfo.SetRecipe(), UIFactionInfo.SetReligion(), UIFactionInfo.SetZone(), UIZoneInfo.SetZone(), LayerInfo.SetZone(), DNA.WriteNote(), Happiness.WriteNote(), HomeResourceSkill.WriteNote(), HomeResourceWorth.WriteNote(), Policy.WriteNote(), ResearchPlan.WriteNote(), SourceJob.Row.WriteNote(), UndoManager.WriteNote(), BaseStats.WriteNote(), BlockInfo.WriteNote(), Chara.WriteNote(), EloPos.WriteNote(), ObjInfo.WriteNote(), Thing.WriteNote(), TraitGene.WriteNote(), TraitItem.WriteNote(), TraitLetterOfWill.WriteNote(), TraitRecipe.WriteNote(), TraitSeed.WriteNote(), UIMapSelector.WriteNote(), Feat.WritePurchaseReq(), ButtonGrid.WriteReqMat(), and Recipe.WriteReqSkill().
AddToggle()
UIButton UINote.AddToggle (string idLang = "", bool isOn = false, Action< bool > action = null) inline
Definition at line 210 of file UINote.cs.
    {
        UIButton uIButton = Load<UIButton>("UI/Element/Button/ButtonToggle");
        uIButton.SetToggle(isOn, action);
        uIButton.mainText.text = idLang.lang().ToTitleCase();
        return uIButton;
    }
References UIButton.SetToggle().
AddTopic() [1/2]
UIItem UINote.AddTopic (string id, string text, string value = null) inline
Definition at line 144 of file UINote.cs.
    {
        UIItem uIItem = Load("UI/Element/Text/" + id);
        uIItem.text1.SetText(text.lang());
        uIItem.text2.SetText(value);
        uIItem.text2.SetActive(!value.IsEmpty());
        return uIItem;
    }
References Load(), UIText.SetText(), UIItem.text1, and UIItem.text2.
Referenced by Element._WriteNote(), Element.AddEncNote(), FortuneRollData.Prize.AddNote(), AddTopic(), UIBook.Page.BuildNote(), BaseListPeople.OnInstantiate(), RaceBonus.OnWriteNote(), UICharaMaker.Refresh(), UIHomeInfo.RefreshInfo(), LayerLoadGame.RefreshInfo(), WindowChara.RefreshNote(), UIFactionInfo.SetFaction(), Faction.SetTaxTooltip(), UIFactionInfo.SetZone(), BaseHomeResource.WriteNote(), HomeResourceWorth.WriteNote(), and UIMapSelector.WriteNote().
AddTopic() [2/2]
UIItem UINote.AddTopic (string text, string value = null) inline
Definition at line 153 of file UINote.cs.
    {
        return AddTopic("TopicDefault", text, value);
    }
References AddTopic().
Awake()
void UINote.Awake () inline private
Definition at line 25 of file UINote.cs.
    {
        if (!target)
        {
            target = this.Rect();
        }
        cur = target;
        layout = GetComponent<LayoutGroup>();
    }
References cur, layout, and target.
Build()
void UINote.Build () inline
Definition at line 49 of file UINote.cs.
    {
        if (extraRebuild)
        {
            this.RebuildLayoutTo<Layer>();
        }
        this.RebuildLayout(recursive: true);
        this.RebuildLayoutTo<Layer>();
        this.RebuildLayoutTo<UIContent>();
        this.RebuildLayoutTo<UIContent>();
        SkinManager.tempSkin = oldTempSkin;
    }
References extraRebuild, and oldTempSkin.
Referenced by UICardInfo.Build(), UIFactionInfo.Clear(), UIRecipeInfo.Clear(), UICharaMaker.ListJob(), UICharaMaker.ListRace(), BaseListPeople.OnInstantiate(), LayerGacha.PlayGacha(), ExtraHint.Refresh(), UICharaMaker.Refresh(), UIRecipeInfo.Refresh(), WindowCharaMini.Refresh(), WindowCharaMini.RefreshEquipment(), WindowChara.RefreshEquipment(), ContentCodex.RefreshInfo(), UIHomeInfo.RefreshInfo(), LayerLoadGame.RefreshInfo(), UIHomeInfo.RefreshReport(), UIRecipeInfo.SetArea(), GridItemRecipe.SetButton(), ButtonGrid.SetCraftRecipe(), UIFactionInfo.SetFaction(), ButtonGrid.SetIngredient(), UIFactionInfo.SetReligion(), UIFactionInfo.SetZone(), UIZoneInfo.SetZone(), LayerInfo.SetZone(), BaseHomeResource.WriteNote(), Happiness.WriteNote(), HomeResourceSkill.WriteNote(), HomeResourceWorth.WriteNote(), Recipe.WriteNote(), RecipeCard.WriteNote(), ResearchPlan.WriteNote(), SourceJob.Row.WriteNote(), UndoManager.WriteNote(), BaseStats.WriteNote(), BaseArea.WriteNote(), BlockInfo.WriteNote(), Chara.WriteNote(), EloPos.WriteNote(), ObjInfo.WriteNote(), TaskPoint.WriteNote(), Element.WriteNote(), UIMapSelector.WriteNote(), and Element.WriteNoteWithRef().
Clear()
void UINote.Clear () inline
Definition at line 35 of file UINote.cs.
    {
        if (!layout)
        {
            layout = GetComponent<LayoutGroup>();
        }
        layout.DestroyChildren(destroyInactive: true);
        oldTempSkin = SkinManager.tempSkin;
        if (skinType != 0)
        {
            SkinManager.tempSkin = SkinManager.CurrentSkin.GetSkin(skinType);
        }
    }
References SkinManager.CurrentSkin, SkinRootStatic.GetSkin(), layout, oldTempSkin, skinType, and SkinManager.tempSkin.
Referenced by UIFactionInfo.Clear(), UIRecipeInfo.Clear(), UICharaMaker.ListJob(), UICharaMaker.ListRace(), BaseListPeople.OnInstantiate(), InvOwnerEquip.OnWriteNote(), ExtraHint.Refresh(), UICharaMaker.Refresh(), WindowCharaMini.Refresh(), WindowCharaMini.RefreshEquipment(), WindowChara.RefreshEquipment(), ContentCodex.RefreshInfo(), UIHomeInfo.RefreshInfo(), LayerLoadGame.RefreshInfo(), WindowChara.RefreshNote(), UIHomeInfo.RefreshReport(), WindowChara.RefreshSkill(), UIRecipeInfo.SetArea(), GridItemRecipe.SetButton(), ButtonGrid.SetCraftRecipe(), UIFactionInfo.SetFaction(), ButtonGrid.SetIngredient(), UICardInfo.SetRecipe(), UIFactionInfo.SetReligion(), UIFactionInfo.SetZone(), UIZoneInfo.SetZone(), LayerInfo.SetZone(), UIBook.Show(), BaseListPeople.WriteHobbies(), BaseHomeResource.WriteNote(), FortuneRollData.WriteNote(), Happiness.WriteNote(), HomeResourceSkill.WriteNote(), HomeResourceWorth.WriteNote(), Recipe.WriteNote(), RecipeCard.WriteNote(), ResearchPlan.WriteNote(), SourceJob.Row.WriteNote(), UndoManager.WriteNote(), BaseStats.WriteNote(), BaseArea.WriteNote(), BlockInfo.WriteNote(), Chara.WriteNote(), EloPos.WriteNote(), ObjInfo.WriteNote(), TaskPoint.WriteNote(), Thing.WriteNote(), Element.WriteNote(), UIMapSelector.WriteNote(), and Element.WriteNoteWithRef().
Load()
UIItem UINote.Load (string path) inline private
Definition at line 228 of file UINote.cs.
    {
        return Load<UIItem>(path);
    }
Referenced by AddHeader(), AddImage(), AddItem(), AddText(), and AddTopic().
Load< T >()
T UINote.Load< T > (string path) inline private
Type Constraints
T : Component
Definition at line 233 of file UINote.cs.
                                           : Component
    {
        return Util.Instantiate<T>(path, layout);
    }
References layout, and Util.
Space()
void UINote.Space (int sizeY = 0, int sizeX = 1) inline
Definition at line 62 of file UINote.cs.
    {
        RectTransform rectTransform = Load<Transform>("UI/Element/Deco/Space").Rect();
        rectTransform.sizeDelta = ((sizeY == 0) ? prof.sizeSpace : new Vector2(sizeX, sizeY));
        if (sizeX != 1)
        {
            rectTransform.GetComponent<LayoutElement>().preferredWidth = sizeX;
        }
    }
References prof, and UINoteProfile.sizeSpace.
Referenced by Element._WriteNote(), UICharaMaker.AddDomain(), Element.BonusInfo.CheckFirst(), UICharaMaker.ListRace(), InvOwner.OnWriteNote(), LayerGacha.PlayGacha(), Dialog.Recipe(), UICharaMaker.Refresh(), UIRecipeInfo.Refresh(), WindowCharaMini.Refresh(), LayerCraftFloat.RefreshDisassemble(), UIHomeInfo.RefreshInfo(), LayerLoadGame.RefreshInfo(), UIInventory.RefreshList(), WindowChara.RefreshNote(), ButtonGrid.SetCard(), ButtonGrid.SetCraftRecipe(), ButtonGrid.SetIngredient(), UICardInfo.SetRecipe(), UIFactionInfo.SetZone(), UIZoneInfo.SetZone(), DNA.WriteNote(), FortuneRollData.WriteNote(), Happiness.WriteNote(), HomeResourceWorth.WriteNote(), Policy.WriteNote(), UndoManager.WriteNote(), EloPos.WriteNote(), Thing.WriteNote(), TraitBookPlan.WriteNote(), TraitBookSkill.WriteNote(), TraitItem.WriteNote(), UIMapSelector.WriteNote(), Recipe.WriteReqFactory(), and Recipe.WriteReqSkill().
Member Data Documentation
cur
RectTransform UINote.cur
Definition at line 19 of file UINote.cs.
Referenced by Awake().
extraRebuild
bool UINote.extraRebuild
Definition at line 21 of file UINote.cs.
Referenced by AddNote(), and Build().
idDefaultText
string UINote.idDefaultText
Definition at line 13 of file UINote.cs.
Referenced by AddText().
layout
LayoutGroup UINote.layout
Definition at line 16 of file UINote.cs.
Referenced by Awake(), Clear(), and Load< T >().
oldTempSkin
SkinRootStatic UINote.oldTempSkin private
Definition at line 23 of file UINote.cs.
Referenced by Build(), and Clear().
prof
UINoteProfile UINote.prof
Definition at line 9 of file UINote.cs.
Referenced by Space().
skinType
SkinType UINote.skinType
Definition at line 11 of file UINote.cs.
Referenced by Clear().
target
RectTransform UINote.target
Definition at line 7 of file UINote.cs.
Referenced by Awake().
The documentation for this class was generated from the following file:
Elin/Plugins.UI/UINote.cs