Elin Decompiled Documentation: DramaSequence Class Reference
DramaSequence Class Reference
Public Types
enum Template { Default }
Public Member Functions
void Clear ()
DramaActor GetActor (string id)
T GetEvent< T > (string idStep)
DramaActor AddActor (string id, Person person)
void AddStep (string id)
DramaEvent AddEvent (DramaEvent e)
void PlayNext ()
void Play (string id)
void Play (int eventID=0)
void Exit ()
void OnUpdate ()
Public Attributes
string id
DramaManager manager
Dictionary< string, int > steps = new Dictionary<string, int>()
Dictionary< string, DramaActor > actors = new Dictionary<string, DramaActor>()
List< DramaEvent > events = new List<DramaEvent>()
bool isLoop
bool canCancel = true
bool isExited
bool fullPortrait
DramaEventTalk firstTalk
List< DramaEvent > tempEvents = new List<DramaEvent>()
string message = ""
string skipJump
string lastStep
string lastlastStep
DramaSetup setup
Properties
DialogDrama dialog [get]
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Private Attributes
DramaEvent currentEvent
int currentEventID
Additional Inherited Members
Static Public Member Functions inherited from EClass
static int rndSeed (int a, int seed)
static int rnd (long a)
static int rnd (int a)
static int curve (int a, int start, int step, int rate=75)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Static Public Attributes inherited from EClass
static Core core
Detailed Description
Definition at line 4 of file DramaSequence.cs.
Member Enumeration Documentation
Template
enum DramaSequence.Template
Enumerator
Default
Definition at line 6 of file DramaSequence.cs.
    {
        Default
    }
Member Function Documentation
AddActor()
DramaActor DramaSequence.AddActor (string id, Person person) inline
Definition at line 94 of file DramaSequence.cs.
    {
        if (actors.ContainsKey(id))
        {
            return actors[id];
        }
        DramaActor dramaActor = Util.Instantiate(manager.moldActor, manager.actorPos);
        dramaActor.Init(this, id, person);
        actors.Add(id, dramaActor);
        return dramaActor;
    }
References DramaManager.actorPos, actors, id, DramaActor.Init(), manager, DramaManager.moldActor, and Util.
Referenced by GetActor(), DramaManager.Load(), and DramaManager.ParseLine().
AddEvent()
DramaEvent DramaSequence.AddEvent (DramaEvent e) inline
Definition at line 116 of file DramaSequence.cs.
    {
        if (!e.step.IsEmpty())
        {
            steps.Add(e.step, events.Count);
        }
        e.sequence = this;
        events.Add(e);
        return e;
    }
References events, DramaEvent.step, and steps.
Referenced by DramaManager.AddEvent().
AddStep()
void DramaSequence.AddStep (string id) inline
Definition at line 106 of file DramaSequence.cs.
    {
        steps.Add(id, events.Count);
        events.Add(new DramaEvent
        {
            sequence = this,
            step = id
        });
    }
References events, and steps.
Referenced by DramaManager.ParseLine().
Clear()
void DramaSequence.Clear () inline
Definition at line 49 of file DramaSequence.cs.
    {
        steps.Clear();
        actors.Clear();
        events.Clear();
        tempEvents.Clear();
    }
References actors, events, steps, and tempEvents.
Referenced by DramaManager.Load().
Exit()
void DramaSequence.Exit () inline
Definition at line 180 of file DramaSequence.cs.
    {
        isExited = true;
        currentEvent = null;
        manager.SetActive(enable: false);
    }
References currentEvent, isExited, and manager.
Referenced by DramaManager.AddCustomEvents(), DramaEventExit.Play(), DramaEventTalk.Play(), and Play().
GetActor()
DramaActor DramaSequence.GetActor (string id) inline
Definition at line 57 of file DramaSequence.cs.
    {
        if (actors.ContainsKey(id))
        {
            return actors[id];
        }
        if (EClass.sources.persons.map.ContainsKey(id))
        {
            return AddActor(id, new Person(id));
        }
        if (EClass.core.IsGameStarted)
        {
            Chara chara = EClass.game.cards.globalCharas.Find(id) ?? EClass._map.FindChara(id);
            if (chara != null)
            {
                return AddActor(id, new Person(chara));
            }
        }
        if (actors.Count <= 0)
        {
            return GetActor("narrator");
        }
        return actors.FirstItem();
    }
References EClass._map, actors, AddActor(), Game.cards, EClass.core, CardManager.GlobalCharaList.Find(), Map.FindChara(), EClass.game, GetActor(), CardManager.globalCharas, id, Core.IsGameStarted, SourceManager.persons, and EClass.sources.
Referenced by DramaManager.AddEvent(), and GetActor().
GetEvent< T >()
T DramaSequence.GetEvent< T > (string idStep) inline
Type Constraints
T : DramaEvent
Definition at line 82 of file DramaSequence.cs.
                                                : DramaEvent
    {
        foreach (DramaEvent @event in events)
        {
            if (@event.step == idStep)
            {
                return @event as T;
            }
        }
        return null;
    }
References events, and DramaEvent.step.
OnUpdate()
void DramaSequence.OnUpdate () inline
Definition at line 187 of file DramaSequence.cs.
    {
        if (tempEvents.Count > 0)
        {
            if (tempEvents[0].Play() && tempEvents.Count > 0)
            {
                tempEvents.RemoveAt(0);
            }
        }
        else
        {
            if (currentEvent == null)
            {
                return;
            }
            if (currentEvent is DramaEventGoto)
            {
                string text = currentEvent.idJump;
                if (text == "*")
                {
                    if (setup.step.IsEmpty())
                    {
                        PlayNext();
                        return;
                    }
                    text = setup.step;
                }
                Play(text);
            }
            else if (currentEvent.Play())
            {
                PlayNext();
            }
        }
    }
References currentEvent, DramaEvent.idJump, DramaEvent.Play(), Play(), PlayNext(), setup, DramaSetup.step, and tempEvents.
Referenced by Play(), and DramaManager.Update().
Play() [1/2]
void DramaSequence.Play (int eventID = 0) inline
Definition at line 145 of file DramaSequence.cs.
    {
        if (isExited)
        {
            return;
        }
        if (eventID >= events.Count)
        {
            if (!isLoop)
            {
                Exit();
                return;
            }
            eventID = 0;
        }
        currentEventID = eventID;
        currentEvent = events[eventID];
        currentEvent.Reset();
        string text = eventID + "/";
        foreach (KeyValuePair<string, int> step in steps)
        {
            if (step.Value == eventID)
            {
                text += step.Key;
            }
            if (step.Value == eventID && !step.Key.StartsWith("flag"))
            {
                lastlastStep = lastStep;
                lastStep = step.Key;
                break;
            }
        }
        OnUpdate();
    }
References currentEvent, currentEventID, events, Exit(), isExited, isLoop, lastlastStep, lastStep, OnUpdate(), DramaEvent.Reset(), and steps.
Play() [2/2]
void DramaSequence.Play (string id) inline
Definition at line 132 of file DramaSequence.cs.
    {
        if (id == "last")
        {
            id = lastlastStep;
        }
        if (!id.IsEmpty() && !steps.ContainsKey(id))
        {
            Debug.Log(id);
        }
        Play((!string.IsNullOrEmpty(id)) ? steps[id] : 0);
    }
References Debug, lastlastStep, Play(), and steps.
Referenced by OnUpdate(), DramaManager.ParseLine(), DramaEventMethod.Play(), DramaEventTalk.Play(), DramaManager.Play(), Play(), PlayNext(), and DramaCustomSequence.TempGoto().
PlayNext()
void DramaSequence.PlayNext () inline
Definition at line 127 of file DramaSequence.cs.
    {
        Play(currentEventID + 1);
    }
References currentEventID, and Play().
Referenced by OnUpdate(), and DramaEventTalk.Play().
Member Data Documentation
actors
Dictionary<string, DramaActor> DramaSequence.actors = new Dictionary<string, DramaActor>()
Definition at line 17 of file DramaSequence.cs.
Referenced by AddActor(), Clear(), and GetActor().
canCancel
bool DramaSequence.canCancel = true
Definition at line 23 of file DramaSequence.cs.
currentEvent
DramaEvent DramaSequence.currentEvent private
Definition at line 33 of file DramaSequence.cs.
Referenced by Exit(), OnUpdate(), and Play().
currentEventID
int DramaSequence.currentEventID private
Definition at line 45 of file DramaSequence.cs.
Referenced by Play(), and PlayNext().
events
List<DramaEvent> DramaSequence.events = new List<DramaEvent>()
Definition at line 19 of file DramaSequence.cs.
Referenced by AddEvent(), AddStep(), Clear(), GetEvent< T >(), DramaManager.ParseLine(), and Play().
firstTalk
DramaEventTalk DramaSequence.firstTalk
Definition at line 29 of file DramaSequence.cs.
Referenced by DramaEventTalk.Play().
fullPortrait
bool DramaSequence.fullPortrait
Definition at line 27 of file DramaSequence.cs.
Referenced by DramaActor.Talk().
id
string DramaSequence.id
Definition at line 11 of file DramaSequence.cs.
Referenced by AddActor(), and GetActor().
isExited
bool DramaSequence.isExited
Definition at line 25 of file DramaSequence.cs.
Referenced by Exit(), LayerDrama.LateUpdate(), and Play().
isLoop
bool DramaSequence.isLoop
Definition at line 21 of file DramaSequence.cs.
Referenced by Play().
lastlastStep
string DramaSequence.lastlastStep
Definition at line 41 of file DramaSequence.cs.
Referenced by Play().
lastStep
string DramaSequence.lastStep
Definition at line 39 of file DramaSequence.cs.
Referenced by Play().
manager
DramaManager DramaSequence.manager
Definition at line 13 of file DramaSequence.cs.
Referenced by AddActor(), DramaCustomSequence.Choice2(), Exit(), and DramaEventEndRoll.Play().
message
string DramaSequence.message = ""
Definition at line 35 of file DramaSequence.cs.
Referenced by DramaEventTalk.Play().
setup
DramaSetup DramaSequence.setup
Definition at line 43 of file DramaSequence.cs.
Referenced by DramaManager.AddCustomEvents(), OnUpdate(), and DramaManager.ParseLine().
skipJump
string DramaSequence.skipJump
Definition at line 37 of file DramaSequence.cs.
steps
Dictionary<string, int> DramaSequence.steps = new Dictionary<string, int>()
Definition at line 15 of file DramaSequence.cs.
Referenced by AddEvent(), AddStep(), Clear(), DramaManager.Load(), DramaManager.ParseLine(), and Play().
tempEvents
List<DramaEvent> DramaSequence.tempEvents = new List<DramaEvent>()
Definition at line 31 of file DramaSequence.cs.
Referenced by DramaCustomSequence._TempTalk(), Clear(), OnUpdate(), DramaEventTalk.Play(), and DramaCustomSequence.TempGoto().
Property Documentation
dialog
DialogDrama DramaSequence.dialog get
Definition at line 47 of file DramaSequence.cs.
Referenced by DramaEventMethod.Play(), and DramaEventTalk.Play().
The documentation for this class was generated from the following file:
Elin/DramaSequence.cs