Elin Decompiled Documentation: ZoneEventHarvest Class Reference
ZoneEventHarvest Class Reference
Public Member Functions
override void OnVisit ()
override ZoneInstance.Status OnReachTimeLimit ()
override void OnLeaveZone ()
Public Member Functions inherited from ZoneEventQuest
void Spawn (int num=1)
void SpawnBoss (bool evolve=false)
void AggroEnemy (int chance=100)
sealed override void OnTickRound ()
virtual void _OnTickRound ()
virtual ZoneInstance.Status OnReachTimeLimit ()
Public Member Functions inherited from ZoneEvent
virtual string GetText ()
void Tick (float delta)
void Init ()
void OnSimulateHour ()
virtual void OnVisit ()
virtual void OnInit ()
virtual void OnFirstTick ()
virtual void OnTick ()
virtual void OnTickRound ()
virtual void OnKill ()
virtual void OnCharaDie (Chara c)
virtual void OnLeaveZone ()
virtual void OnLoad ()
void Kill ()
Properties
QuestHarvest questHarvest [get]
override string TextWidgetDate [get]
override int TimeLimit [get]
Properties inherited from ZoneEventQuest
Quest quest [get]
virtual bool WarnBoss [get]
virtual bool CountEnemy [get]
virtual int TimeLimit [get]
Properties inherited from ZoneEvent
SourceQuest.Row source [get]
virtual string id [get]
virtual string TextWidgetDate [get]
virtual float roundInterval [get]
virtual Playlist playlist [get]
virtual bool debugSkip [get]
virtual string RefStr2 [get]
virtual string RefStr3 [get]
virtual int hoursToKill [get]
virtual bool HasReport [get]
string Name [get]
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Additional Inherited Members
Static Public Member Functions inherited from EClass
static int rndSeed (int a, int seed)
static int rnd (long a)
static int rnd (int a)
static int curve (int a, int start, int step, int rate=75)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Public Attributes inherited from ZoneEventQuest
int uidQuest
List< int > enemies = new List<int>()
Public Attributes inherited from ZoneEvent
float time
int rounds
int hoursElapsed
int minElapsed
Zone zone
bool firstTick = true
Static Public Attributes inherited from EClass
static Core core
Detailed Description
Definition at line 5 of file ZoneEventHarvest.cs.
Member Function Documentation
OnLeaveZone()
override void ZoneEventHarvest.OnLeaveZone () inline virtual
Reimplemented from ZoneEvent.
Definition at line 73 of file ZoneEventHarvest.cs.
    {
        if (EClass._zone.instance.status == ZoneInstance.Status.Running)
        {
            EClass._zone.instance.status = OnReachTimeLimit();
        }
        List<Thing> list = new List<Thing>();
        foreach (Chara member in EClass.pc.party.members)
        {
            member.things.Foreach(delegate(Thing t)
            {
                if (t.GetBool(115) && EClass.rnd(2) != 0)
                {
                    list.Add(t);
                }
            });
        }
        if (list.Count <= 0)
        {
            return;
        }
        Msg.Say("harvest_confiscate", list.Count.ToString() ?? "");
        foreach (Thing item in list)
        {
            item.Destroy();
        }
        EClass.player.ModKarma(-1);
    }
References EClass._zone, ThingContainer.Foreach(), BaseCard.GetBool(), Zone.instance, item, Party.members, Player.ModKarma(), OnReachTimeLimit(), Chara.party, EClass.pc, EClass.player, EClass.rnd(), Msg.Say(), ZoneInstance.status, and Card.things.
OnReachTimeLimit()
override ZoneInstance.Status ZoneEventHarvest.OnReachTimeLimit () inline virtual
Reimplemented from ZoneEventQuest.
Definition at line 63 of file ZoneEventHarvest.cs.
    {
        Msg.Say("harvest_end", Lang._weight(questHarvest.weightDelivered));
        if (questHarvest.weightDelivered < questHarvest.destWeight)
        {
            return ZoneInstance.Status.Fail;
        }
        return ZoneInstance.Status.Success;
    }
References Lang._weight(), QuestHarvest.destWeight, questHarvest, Msg.Say(), and QuestHarvest.weightDelivered.
Referenced by OnLeaveZone().
OnVisit()
override void ZoneEventHarvest.OnVisit () inline virtual
Reimplemented from ZoneEvent.
Definition at line 13 of file ZoneEventHarvest.cs.
    {
        if (EClass.game.isLoading)
        {
            return;
        }
        EClass._zone.SetBGM(17);
        Point centerPos = EClass._map.GetCenterPos();
        PartialMap.Apply("Special/farm_chest.mp", centerPos);
        GenBounds genBounds = GenBounds.Create(EClass._zone);
        genBounds.marginPartial = 2;
        genBounds.FuncCheckEmpty = (Cell cell) => cell.sourceFloor.id == 42;
        List<SourceObj.Row> crops = EClass.sources.objs.rows.Where((SourceObj.Row o) => o.tag.Contains("harvest")).ToList();
        for (int i = 0; i < 50; i++)
        {
            genBounds.TryAddMapPiece(MapPiece.Type.Farm, 0f, "", delegate(PartialMap p, GenBounds b)
            {
                List<Point> list = b.ListEmptyPoint();
                SourceObj.Row row = crops.RandomItemWeighted((SourceObj.Row o) => o.chance);
                int num = 1 + EClass.rnd(5 + base.quest.difficulty * 2);
                foreach (Point item in list)
                {
                    if (item.sourceFloor.id == 4 && EClass.rnd(4) != 0)
                    {
                        item.SetObj(row.id);
                        int num2 = item.growth.HarvestStage - EClass.rnd(4);
                        item.growth.SetStage(num2);
                        if (num2 == item.growth.HarvestStage)
{
                            EClass._map.AddPlant(item, null).size = Mathf.Clamp(num + EClass.rnd(2) - EClass.rnd(2), 0, 9) + 1;
                        }
                        item.cell.isClearSnow = true;
                    }
                }
            });
        }
        foreach (Thing thing in EClass._map.things)
        {
            thing.isNPCProperty = true;
        }
        for (int j = 0; j < 12; j++)
        {
            EClass._zone.SpawnMob();
        }
        for (int k = 0; k < 30; k++)
        {
            EClass._zone.SpawnMob(null, SpawnSetting.HomeWild(1));
        }
    }
References EClass._map, EClass._zone, Map.AddPlant(), PartialMap.Apply(), GenBounds.Create(), EClass.game, MapBounds.GetCenterPos(), SpawnSetting.HomeWild(), Game.isLoading, item, GenBounds.ListEmptyPoint(), SourceManager.objs, EClass.rnd(), Zone.SetBGM(), PlantData.size, EClass.sources, Zone.SpawnMob(), Map.things, and GenBounds.TryAddMapPiece().
Property Documentation
questHarvest
QuestHarvest ZoneEventHarvest.questHarvest get
Definition at line 7 of file ZoneEventHarvest.cs.
Referenced by OnReachTimeLimit().
TextWidgetDate
override string ZoneEventHarvest.TextWidgetDate get
Definition at line 9 of file ZoneEventHarvest.cs.
TimeLimit
override int ZoneEventHarvest.TimeLimit get
Definition at line 11 of file ZoneEventHarvest.cs.
The documentation for this class was generated from the following file:
Elin/ZoneEventHarvest.cs