Elin Decompiled Documentation: WidgetStockTracker Class Reference
WidgetStockTracker Class Reference
Public Member Functions
override void OnActivate ()
void _Refresh ()
Public Member Functions inherited from Widget
void Test ()
bool IsInRightMode ()
void Activate ()
void RefreshOrder ()
virtual void OnActivate ()
virtual object CreateExtra ()
void Deactivate ()
virtual void OnDeactivate ()
void Close ()
void Reactivate ()
virtual void OnManagerActivate ()
virtual void OnManagerDeactivate ()
void SetAnchor (RectPosition p)
void SetPivot (RectPosition p)
virtual void OnChangePivot ()
void UpdateConfig ()
virtual void OnUpdateConfig ()
void ClampToScreen ()
virtual void OnChangeResolution ()
void OnChangePosition ()
virtual void OnChangeActionMode ()
virtual void OnFlip ()
bool IsAlignTop ()
Layer AddLayer (Layer l, Transform trans)
void RefreshTipPivotPosition ()
SkinSet GetSkin ()
SkinConfig GetSkinConfig ()
void SetSkin (int id, int v=0)
void TestSkin ()
virtual void ApplySkin ()
virtual void OnApplySkin ()
void InstantiateDeco (SkinDeco deco)
void AddDeco (SkinDeco deco)
void RemoveDeco (SkinDeco deco)
virtual bool CanShowContextMenu ()
void ShowContextMenu ()
void SetBaseContextMenu (UIContextMenu m)
virtual void OnSetContextMenu (UIContextMenu m)
void SetGridContextMenu (UIContextMenu m)
void SoundActivate ()
void OnChangeResolution ()
SkinSet GetSkin ()
SkinConfig GetSkinConfig ()
Static Public Member Functions
static void Refresh ()
Static Public Member Functions inherited from EMono
static int rnd (int a)
Public Attributes
UIText text
UIText textNum
Public Attributes inherited from Widget
Image imageBG
SoundData soundActivate
UIDragPanel dragPanel
RectTransform tipPivotLeft
RectTransform tipPivotRight
Static Public Attributes
static WidgetStockTracker Instance
Static Public Attributes inherited from EMono
static Core core
Private Attributes
FastString sb = new FastString()
FastString lastSb = new FastString()
FastString sbNum = new FastString()
FastString lastSbNum = new FastString()
Additional Inherited Members
Public Types inherited from Widget
enum WidgetType { Default , ZoomMenu }
enum State { Active , Inactive }
Protected Member Functions inherited from Widget
void ClampToScreenEnsured (Component c, Vector2 anchoredPos)
void ClampToScreen (RectTransform rect, float margin=10f)
Protected Attributes inherited from Widget
bool flip
Properties inherited from Widget
string ID [get]
Config config [get]
SkinRoot skinRoot [get]
bool IsSealed [get]
virtual bool ShowStyleMenu [get]
virtual bool AlwaysTop [get]
virtual bool IsStaticPosition [get]
virtual bool AlwaysBottom [get]
virtual Type SetSiblingAfter [get]
virtual bool ShowInBuildMode [get]
virtual bool RightClickToClose [get]
virtual bool AllowRightClickToClose [get]
Properties inherited from EMono
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SoundManager Sound [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static CoreDebug debug [get]
Detailed Description
Definition at line 3 of file WidgetStockTracker.cs.
Member Function Documentation
_Refresh()
void WidgetStockTracker._Refresh () inline
Definition at line 33 of file WidgetStockTracker.cs.
    {
        sb.Clear();
        sbNum.Clear();
        HashSet<string> trackedCards = EMono.player.trackedCards;
        HashSet<string> trackedCategories = EMono.player.trackedCategories;
        if (trackedCards.Count == 0 && trackedCategories.Count == 0)
        {
            sb.Append("\n");
        }
        else
        {
            foreach (string item in trackedCards)
            {
                int num = EMono._map.Stocked.cardMap.TryGetValue(item)?.num ?? 0;
                sb.Append(EMono.sources.cards.map[item].GetName() + "\n");
                sbNum.Append(num + "\n");
            }
            foreach (string item2 in trackedCategories)
            {
                PropSetCategory propSetCategory = EMono._map.Stocked.categoryMap[item2];
                sb.Append(propSetCategory.source.GetText() + "\n");
                sbNum.Append(propSetCategory.sum + "\n");
            }
        }
        if (!sb.Equals(lastSb) || !sbNum.Equals(lastSbNum))
        {
            text.text = sb.ToString();
            textNum.text = sbNum.ToString();
            lastSb.Set(sb);
            lastSbNum.Set(sbNum);
            this.RebuildLayout();
        }
    }
References EMono._map, FastString.Append(), Props.cardMap, SourceManager.cards, Props.categoryMap, FastString.Clear(), item, lastSb, lastSbNum, SourceCard.map, EMono.player, sb, sbNum, FastString.Set(), PropSetCategory.source, EMono.sources, Map.Stocked, PropSetCategory.sum, FastString.ToString(), Player.trackedCards, and Player.trackedCategories.
Referenced by Refresh().
OnActivate()
override void WidgetStockTracker.OnActivate () inline virtual
Reimplemented from Widget.
Definition at line 19 of file WidgetStockTracker.cs.
    {
        Instance = this;
        Refresh();
    }
References Instance, and Refresh().
Refresh()
static void WidgetStockTracker.Refresh () inline static
Definition at line 25 of file WidgetStockTracker.cs.
    {
        if ((bool)Instance)
        {
            Instance._Refresh();
        }
    }
References _Refresh(), and Instance.
Referenced by OnActivate().
Member Data Documentation
Instance
WidgetStockTracker WidgetStockTracker.Instance static
Definition at line 5 of file WidgetStockTracker.cs.
Referenced by OnActivate(), and Refresh().
lastSb
FastString WidgetStockTracker.lastSb = new FastString() private
Definition at line 13 of file WidgetStockTracker.cs.
Referenced by _Refresh().
lastSbNum
FastString WidgetStockTracker.lastSbNum = new FastString() private
Definition at line 17 of file WidgetStockTracker.cs.
Referenced by _Refresh().
sb
FastString WidgetStockTracker.sb = new FastString() private
Definition at line 11 of file WidgetStockTracker.cs.
Referenced by _Refresh().
sbNum
FastString WidgetStockTracker.sbNum = new FastString() private
Definition at line 15 of file WidgetStockTracker.cs.
Referenced by _Refresh().
text
UIText WidgetStockTracker.text
Definition at line 7 of file WidgetStockTracker.cs.
textNum
UIText WidgetStockTracker.textNum
Definition at line 9 of file WidgetStockTracker.cs.
The documentation for this class was generated from the following file:
Elin/WidgetStockTracker.cs