Elin Decompiled Documentation: UIList Class Reference
UIList Class Reference
Classes
struct ButtonPair
class Callback
interface ICallback
class RefObject
Public Types
enum BGType {
none , stripe , line , dot ,
dot_long , grid , thin
}
enum SortMode {
ByNone , ByNumber , ByValue , ByCategory ,
ByEquip , ByJob , ByRace , ByLevel ,
ByWeight , ByPrice , ByElementParent , ByName ,
ByID , ByWeightSingle , ByWorkk , ByFeat
}
enum ItemHeight { DontChange , Default }
Public Member Functions
void AddCollection (ICollection collection)
override void Add (object item)
int GetIndexOf (object item)
ButtonPair GetPair (object item)
T GetPair< T > (object item)
void AddDynamic (object item)
void RemoveDynamic (object item)
override void Clear ()
bool OnClickFolder (UIButton b, Action< UIList > onFold, bool refresh=true)
void RebuildLayoutInParent ()
virtual void Refresh (bool highlightLast=false)
void NextPage ()
void PrevPage ()
void SetPage (int i)
void OnMove (object o, object select=null)
void Select (int index=0, bool invoke=false)
void Select (object obj, bool invoke=false)
void Select< T > (Func< T, bool > func, bool invoke=false)
void Sort ()
void ChangeSort (SortMode m)
override void NextSort ()
override void List ()
override void List (SortMode sort)
void List (bool refreshHighlight=false)
void List (SortMode m, bool refreshHighlight=false)
override void Redraw ()
void BuildLayout ()
T GetMold< T > ()
void OnDestroy ()
void ClearChildren ()
Public Member Functions inherited from BaseList
virtual void NextSort ()
virtual void List ()
virtual void List (UIList.SortMode sort)
virtual void Redraw ()
virtual void Clear ()
virtual void Add (object o)
void RefreshNoItem ()
void RefreshBGGrid ()
Public Attributes
string langNoItem
int rows
UISelectableGroup menu
UIListTopbar bar
bool fillEmpty
bool buildLayout
UIItem paginationTop
UIItem paginationBottom
UISelectableGroup group
LayoutGroup _layoutItems
Transform moldItem
bool selectFirst
bool invokeSelected
bool enableGroup = true
bool onlyDirectChildrenButtonForGroup
bool usePage
bool usePool
bool disableInstaClick = true
bool ignoreNullObj = true
ItemHeight itemHeight
int heightFix
int page
int maxPage
int itemsPerPage
List< object > items = new List<object>()
List< ButtonPair > buttons = new List<ButtonPair>()
string idMold
Action SETab
UIList moldList
UIList parent
Dictionary< UIButton, UIList > children = new Dictionary<UIButton, UIList>()
Public Attributes inherited from BaseList
UIList.BGType bgType
Vector2 bgFix
Vector2 bgUvFix = Vector2.one
UIList.ICallback callbacks
UIList.SortMode[] sorts
Action onBeforeRedraw
Action onAfterRedraw
bool useDefaultNoItem = true
bool numbering
SkinType skinType
RawImage bgGrid
UIList.SortMode sortMode
bool isBuilt
Static Public Attributes
const int HeightDefault = 34
static string[] strNumber
Protected Member Functions
virtual void OnRefresh ()
Properties
LayoutGroup layoutItems [get]
GridLayoutGroup gridLayout [get]
override int ItemCount [get]
override int RowCount [get]
UIList Root [get]
Properties inherited from BaseList
virtual int ItemCount [get]
virtual int RowCount [get]
SkinRootStatic Skin [get]
Private Member Functions
UIList CreateChild (UIButton button)
void RemoveChild (UIButton button)
void KillChildren ()
void OnSelect (UIList activeList)
void AfterRefresh ()
Private Attributes
bool initialized
bool reset
int highlightIndex
Additional Inherited Members
Protected Attributes inherited from BaseList
Transform transNoItem
Detailed Description
Definition at line 8 of file UIList.cs.
Member Enumeration Documentation
BGType
enum UIList.BGType
Enumerator
none
stripe
line
dot
dot_long
grid
thin
Definition at line 15 of file UIList.cs.
    {
        none,
        stripe,
        line,
        dot,
        dot_long,
        grid,
        thin
    }
ItemHeight
enum UIList.ItemHeight
Enumerator
DontChange
Default
Definition at line 46 of file UIList.cs.
    {
        DontChange,
        Default
    }
SortMode
enum UIList.SortMode
Enumerator
ByNone
ByNumber
ByValue
ByCategory
ByEquip
ByJob
ByRace
ByLevel
ByWeight
ByPrice
ByElementParent
ByName
ByID
ByWeightSingle
ByWorkk
ByFeat
Definition at line 26 of file UIList.cs.
    {
        ByNone,
        ByNumber,
        ByValue,
        ByCategory,
        ByEquip,
        ByJob,
        ByRace,
        ByLevel,
        ByWeight,
        ByPrice,
        ByElementParent,
        ByName,
        ByID,
        ByWeightSingle,
        ByWorkk,
        ByFeat
    }
Member Function Documentation
Add()
override void UIList.Add (object item) inline virtual
Reimplemented from BaseList.
Definition at line 302 of file UIList.cs.
    {
        if (item != null || !ignoreNullObj)
        {
            items.Add(item);
        }
    }
References ignoreNullObj, item, and items.
Referenced by DropdownGrid.Activate(), ContentPopulation.Add(), AddCollection(), DropdownGrid.Build(), DropdownGrid.BuildIngredients(), DramaCustomSequence.GetListGuide(), LayerInspect.GetMenuItems(), UIDragGridInfo.Init(), UIDragGridInfo.InitFuel(), LayerEditPlaylist.ListBGM.List(), Dialog.OnAfterInit(), LayerMod.OnInit(), ContentConfigInput.OnInstantiate(), ListPeopleBed.OnList(), ListPeopleBuySlave.OnList(), ListPeopleEmbark.OnList(), ListPeopleExpedition.OnList(), ListPeopleRevive.OnList(), ContentChronicle.OnSwitchContent(), ContentKeyItem.OnSwitchContent(), ContentQuest.OnSwitchContent(), ContentStatistics.OnSwitchContent(), ContentTop.OnSwitchContent(), LayerDebug.OnSwitchContent(), WidgetCurrentTool.RebuildSlots(), LayerCollectible.Refresh(), LayerHire.Refresh(), LayerTravel.Refresh(), UIDistribution.Refresh(), UIDragGridIngredients.Refresh(), UIRecipeInfo.Refresh(), WindowCharaMini.Refresh(), LayerHome.RefreshAreas(), PartialMapMenu.RefreshCategory(), LayerNewspaper.RefreshChat(), LayerEquip.RefreshEquipment(), WidgetEquip.RefreshEquipment(), LayerFactions.RefreshFactions(), ContentFaction.RefreshFactions(), LayerHome.RefreshFeat(), LayerQuestBoard.RefreshHire(), LayerMapList.RefreshList(), UIRecipeInfo.RefreshList(), LayerLoadGame.RefreshList(), ContentHomeLog.RefreshLog(), LayerEmbark.RefreshMembers(), LayerNewspaper.RefreshNews(), ContentPolicy.RefreshPolicyList(), LayerPolicy.RefreshPolicyList(), LayerQuestBoard.RefreshQuest(), LayerQuestBoard.RefreshRanking(), UIHomeInfo.RefreshReport(), ContentHomeReport.RefreshResources(), UIHomeInfo.RefreshResources(), WindowChara.RefreshSkill(), LayerHome.RefreshSpots(), WindowChara.RefreshStatic(), LayerTech.RefreshTech(), LayerHome.RefreshTech(), LayerNewspaper.RefreshVote(), LayerNewspaper.RefreshWeather(), WidgetSearch.RefreshWords(), LayerDistribution.SetContainer(), LayerDragGrid.SetInv(), LayerList.SetList2< TValue >(), LayerList.SetListCheck< TValue >(), LayerList.SetStringList(), LayerList.Show(), LayerShippingResult.Show(), and ContentRanking.SwitchRanking().
AddCollection()
void UIList.AddCollection (ICollection collection) inline
Definition at line 294 of file UIList.cs.
    {
        foreach (object item in collection)
        {
            Add(item);
        }
    }
References Add(), and item.
Referenced by LayerInspect.Refresh().
AddDynamic()
void UIList.AddDynamic (object item) inline
Definition at line 332 of file UIList.cs.
    {
    }
AfterRefresh()
void UIList.AfterRefresh () inline private
Definition at line 592 of file UIList.cs.
    {
        RefreshNoItem();
        if ((bool)paginationTop)
        {
            paginationTop.text1.text = page + 1 + " / " + maxPage;
        }
        if ((bool)paginationBottom)
        {
            paginationBottom.text1.text = page + 1 + " / " + maxPage;
        }
        callbacks.OnRefresh();
        OnRefresh();
        layoutItems.RebuildLayout();
        RefreshBGGrid();
    }
References BaseList.callbacks, layoutItems, maxPage, OnRefresh(), page, paginationBottom, paginationTop, BaseList.RefreshBGGrid(), and BaseList.RefreshNoItem().
Referenced by Refresh(), and RemoveDynamic().
BuildLayout()
void UIList.BuildLayout () inline
Definition at line 758 of file UIList.cs.
    {
        GridLayoutGroup gridLayoutGroup = layoutItems as GridLayoutGroup;
        if ((bool)gridLayoutGroup && buildLayout)
        {
            RectTransform rectTransform = layoutItems.Rect();
            RectTransform rectTransform2 = layoutItems.Rect();
            Vector2 vector2 = (layoutItems.Rect().anchorMax = new Vector2(0f, 1f));
            Vector2 pivot = (rectTransform2.anchorMin = vector2);
            rectTransform.pivot = pivot;
            rectTransform.sizeDelta = new Vector2(rectTransform.sizeDelta.x, (float)rows * gridLayoutGroup.cellSize.y);
        }
    }
References buildLayout, layoutItems, and rows.
Referenced by Refresh().
ChangeSort()
void UIList.ChangeSort (SortMode m) inline
Definition at line 705 of file UIList.cs.
    {
        sortMode = m;
        Sort();
        Refresh();
    }
References Refresh(), Sort(), and BaseList.sortMode.
Referenced by NextSort(), WindowCharaMini.Refresh(), and WindowChara.RefreshSkill().
Clear()
override void UIList.Clear () inline virtual
Reimplemented from BaseList.
Definition at line 349 of file UIList.cs.
    {
        items.Clear();
        reset = true;
    }
References items, and reset.
Referenced by DropdownGrid.Activate(), DropdownGrid.Build(), DropdownGrid.BuildIngredients(), List(), Dialog.OnAfterInit(), ContentChronicle.OnSwitchContent(), ContentTop.OnSwitchContent(), LayerDebug.OnSwitchContent(), WidgetCurrentTool.RebuildSlots(), ContentPopulation.Refresh(), LayerHire.Refresh(), LayerInspect.Refresh(), UIRecipeInfo.Refresh(), LayerResource.RefreshCategory(), PartialMapMenu.RefreshCategory(), LayerGacha.RefreshCoin(), WindowCharaMini.RefreshEquipment(), LayerEquip.RefreshEquipment(), WidgetEquip.RefreshEquipment(), WindowChara.RefreshEquipment(), LayerFactions.RefreshFactions(), ContentFaction.RefreshFactions(), LayerQuestBoard.RefreshHire(), UIRecipeInfo.RefreshList(), LayerLoadGame.RefreshList(), ContentHomeLog.RefreshLog(), LayerEmbark.RefreshMembers(), LayerQuestBoard.RefreshQuest(), LayerQuestBoard.RefreshRanking(), UIHomeInfo.RefreshReport(), ContentHomeReport.RefreshResources(), UIHomeInfo.RefreshResources(), LayerHome.RefreshSpots(), WindowChara.RefreshStatic(), UIBook.RefreshTopics(), ContentFaction.RefreshZones(), LayerFactions.RefreshZones(), LayerLocation.RefreshZones(), LayerShippingResult.Show(), and ContentRanking.SwitchRanking().
ClearChildren()
void UIList.ClearChildren () inline
Definition at line 795 of file UIList.cs.
    {
        if (usePool)
        {
            foreach (ButtonPair button in buttons)
            {
                PoolManager.TryDespawn(button.component);
            }
        }
        layoutItems.DestroyChildren();
    }
References buttons, UIList.ButtonPair.component, layoutItems, PoolManager.TryDespawn(), and usePool.
Referenced by OnDestroy(), and Refresh().
CreateChild()
UIList UIList.CreateChild (UIButton button) inline private
Definition at line 355 of file UIList.cs.
    {
        UIList uIList = Util.Instantiate(moldList, layoutItems);
        uIList.transform.SetSiblingIndex(button.transform.GetSiblingIndex() + 1);
        uIList.callbacks = callbacks;
        uIList.parent = this;
        children.Add(button, uIList);
        return uIList;
    }
References BaseList.callbacks, children, layoutItems, moldList, and Util.
Referenced by OnClickFolder().
GetIndexOf()
int UIList.GetIndexOf (object item) inline
Definition at line 310 of file UIList.cs.
    {
        return items.IndexOf(item);
    }
References item, and items.
GetMold< T >()
T UIList.GetMold< T > () inline
Type Constraints
T : Component
Definition at line 772 of file UIList.cs.
                                  : Component
    {
        if ((bool)moldItem)
        {
            T component = moldItem.GetComponent<T>();
            if ((bool)component)
            {
                layoutItems.DestroyChildren();
                return component;
            }
        }
        return layoutItems.CreateMold<T>(idMold);
    }
References idMold, layoutItems, and moldItem.
GetPair()
ButtonPair UIList.GetPair (object item) inline
Definition at line 315 of file UIList.cs.
    {
        foreach (ButtonPair button in buttons)
        {
            if (button.obj == item)
            {
                return button;
            }
        }
        return buttons[0];
    }
References buttons, item, and UIList.ButtonPair.obj.
Referenced by GetPair< T >(), and RemoveDynamic().
GetPair< T >()
T UIList.GetPair< T > (object item) inline
Type Constraints
T : Component
Definition at line 327 of file UIList.cs.
                                             : Component
    {
        return GetPair(item).component as T;
    }
References UIList.ButtonPair.component, GetPair(), and item.
KillChildren()
void UIList.KillChildren () inline private
Definition at line 390 of file UIList.cs.
    {
        foreach (UIList value in children.Values)
        {
            value.KillChildren();
        }
        UnityEngine.Object.DestroyImmediate(base.gameObject);
    }
References children, and KillChildren().
Referenced by KillChildren().
List() [1/4]
override void UIList.List () inline virtual
Reimplemented from BaseList.
Definition at line 717 of file UIList.cs.
    {
        List(sortMode);
    }
References List(), and BaseList.sortMode.
Referenced by LayerList.EnableReroll(), UIDragGridInfo.Init(), UIDragGridInfo.InitFuel(), BaseListPeople.List(), LayerEditPlaylist.ListBGM.List(), List(), LayerList.ManualList(), ListPeopleExpedition.OnClick(), ListPeopleRevive.OnClick(), LayerMod.OnInit(), ContentConfigInput.OnInstantiate(), OnMove(), ContentKeyItem.OnSwitchContent(), ContentQuest.OnSwitchContent(), LayerTravel.Refresh(), WindowCharaMini.Refresh(), LayerHome.RefreshAreas(), PartialMapMenu.RefreshCategory(), LayerNewspaper.RefreshChat(), LayerEquip.RefreshEquipment(), WidgetEquip.RefreshEquipment(), LayerMapList.RefreshList(), LayerNewspaper.RefreshNews(), LayerPolicy.RefreshPolicyList(), LayerQuestBoard.RefreshRanking(), UIHomeInfo.RefreshReport(), ContentHomeReport.RefreshResources(), UIHomeInfo.RefreshResources(), WindowChara.RefreshSkill(), LayerHome.RefreshSpots(), LayerTech.RefreshTech(), LayerHome.RefreshTech(), LayerNewspaper.RefreshVote(), LayerNewspaper.RefreshWeather(), WidgetSearch.RefreshWords(), LayerDragGrid.SetInv(), LayerList.SetList2< TValue >(), LayerList.SetListCheck< TValue >(), LayerList.SetStringList(), and LayerList.Show().
List() [2/4]
void UIList.List (bool refreshHighlight = false) inline
Definition at line 727 of file UIList.cs.
    {
        List(sortMode, refreshHighlight);
    }
References List(), and BaseList.sortMode.
List() [3/4]
void UIList.List (SortMode m, bool refreshHighlight = false) inline
Definition at line 732 of file UIList.cs.
    {
        sortMode = m;
        Clear();
        callbacks.OnList(sortMode);
        Refresh(refreshHighlight);
    }
References BaseList.callbacks, Clear(), Refresh(), and BaseList.sortMode.
List() [4/4]
override void UIList.List (SortMode sort) inline virtual
Reimplemented from BaseList.
Definition at line 722 of file UIList.cs.
    {
        List(sort);
    }
References List().
NextPage()
void UIList.NextPage () inline
Definition at line 613 of file UIList.cs.
    {
        SetPage(page + 1);
    }
References page, and SetPage().
Referenced by Refresh().
NextSort()
override void UIList.NextSort () inline virtual
Reimplemented from BaseList.
Definition at line 712 of file UIList.cs.
    {
        ChangeSort(sorts.NextItem(sortMode));
    }
References ChangeSort(), BaseList.sortMode, and BaseList.sorts.
OnClickFolder()
bool UIList.OnClickFolder (UIButton b, Action< UIList > onFold, bool refresh = true) inline
Definition at line 365 of file UIList.cs.
    {
        if (children.ContainsKey(b))
        {
            RemoveChild(b);
            return true;
        }
        UIList uIList = CreateChild(b);
        onFold(uIList);
        uIList.Refresh();
        if (refresh)
        {
            GetComponentInParent<ScrollRect>().RebuildLayout(recursive: true);
        }
        return false;
    }
References children, CreateChild(), Refresh(), and RemoveChild().
OnDestroy()
void UIList.OnDestroy () inline
Definition at line 786 of file UIList.cs.
    {
        ClearChildren();
        if ((bool)transNoItem)
        {
            UnityEngine.Object.DestroyImmediate(transNoItem.gameObject);
        }
    }
References ClearChildren(), and BaseList.transNoItem.
OnMove()
void UIList.OnMove (object o, object select = null) inline
Definition at line 637 of file UIList.cs.
    {
        List();
        Select(select ?? o);
        SE.Click();
    }
References List(), and Select().
OnRefresh()
virtual void UIList.OnRefresh () inline protected virtual
Definition at line 609 of file UIList.cs.
    {
    }
Referenced by AfterRefresh().
OnSelect()
void UIList.OnSelect (UIList activeList) inline private
Definition at line 412 of file UIList.cs.
    {
        foreach (UIList value in children.Values)
        {
            value.OnSelect(activeList);
        }
        if (this != activeList && (bool)group)
        {
            group.Select(-1);
        }
    }
References children, group, OnSelect(), and UISelectableGroup.Select().
Referenced by OnSelect(), and Refresh().
PrevPage()
void UIList.PrevPage () inline
Definition at line 618 of file UIList.cs.
    {
        SetPage(page - 1);
    }
References page, and SetPage().
Referenced by Refresh().
RebuildLayoutInParent()
void UIList.RebuildLayoutInParent () inline
Definition at line 399 of file UIList.cs.
    {
        this.RebuildLayout();
        if ((bool)parent)
        {
            parent.RebuildLayout();
        }
        else
        {
            base.transform.parent.RebuildLayout();
        }
    }
References parent.
Referenced by RemoveChild().
Redraw()
override void UIList.Redraw () inline virtual
Reimplemented from BaseList.
Definition at line 740 of file UIList.cs.
    {
        if (onBeforeRedraw != null)
        {
            onBeforeRedraw();
        }
        int num = 0;
        foreach (ButtonPair button in buttons)
        {
            callbacks.OnRedraw(button.obj, button.component, num);
            num++;
        }
        if (onAfterRedraw != null)
        {
            onAfterRedraw();
        }
    }
References buttons, BaseList.callbacks, UIList.ButtonPair.component, UIList.ButtonPair.obj, BaseList.onAfterRedraw, and BaseList.onBeforeRedraw.
Referenced by WidgetEquip._Redraw(), WidgetCurrentTool.CheckDirty(), DropdownGrid.OnChangeIngredient(), WidgetCurrentTool.RebuildSlots(), DropdownGrid.Redraw(), LayerEquip.Redraw(), UIMagicChest.Redraw(), UIInventory.RefreshAllList(), and UIRecipeInfo.RefreshImages().
Refresh()
virtual void UIList.Refresh (bool highlightLast = false) inline virtual
Reimplemented in UIListEx< T >.
Definition at line 424 of file UIList.cs.
    {
        if (!layoutItems)
        {
            return;
        }
        SkinRootStatic tempSkin = SkinManager.tempSkin;
        if (skinType != 0)
        {
            SkinManager.tempSkin = SkinManager.CurrentSkin.GetSkin(skinType);
        }
        highlightIndex = -1;
        if (highlightLast)
        {
            UIButton componentOf = InputModuleEX.GetComponentOf<UIButton>();
            if ((bool)componentOf)
            {
                Component component = componentOf.transform.parent.GetComponent<UIItem>();
                if (component == null)
                {
                    component = componentOf;
                }
                for (int i = 0; i < buttons.Count; i++)
                {
                    if (buttons[i].component == component)
                    {
                        highlightIndex = i;
                        break;
                    }
                }
            }
        }
        callbacks.SetList(this);
        if (!enableGroup && (bool)group)
        {
            UnityEngine.Object.DestroyImmediate(group);
        }
        if (!usePage)
        {
            maxPage = 9999999;
        }
        callbacks.CreateMold();
        if (itemHeight == ItemHeight.Default)
        {
            RectTransform rectTransform = callbacks.GetMold().Rect();
            rectTransform.sizeDelta = new Vector2(rectTransform.sizeDelta.x, 34 + heightFix);
        }
        if (!initialized || reset)
        {
            if (sortMode != 0)
            {
                Sort();
            }
            if (!initialized)
            {
                if ((bool)paginationTop && (bool)paginationTop.button1)
                {
                    paginationTop.button1.onClick.AddListener(PrevPage);
                    paginationTop.button2.onClick.AddListener(NextPage);
                }
                if ((bool)paginationBottom && (bool)paginationBottom.button1)
                {
                    paginationBottom.button1.onClick.AddListener(PrevPage);
                    paginationBottom.button2.onClick.AddListener(NextPage);
                }
                _ = (bool)bar;
            }
            initialized = true;
            reset = false;
        }
        children.Clear();
        buttons.Clear();
        GridLayoutGroup gridLayoutGroup = layoutItems as GridLayoutGroup;
        BuildLayout();
        if (usePage)
        {
            if ((bool)gridLayoutGroup)
            {
                itemsPerPage = gridLayoutGroup.constraintCount;
            }
            else
            {
                itemsPerPage = rows;
            }
            this.Rect().RebuildLayout();
            this.Rect().ForceUpdateRectTransforms();
            Canvas.ForceUpdateCanvases();
            float y = RectTransformUtility.PixelAdjustRect(this.Rect(), GetComponentInParent<Canvas>()).size.y;
            float y2 = callbacks.GetMold().Rect().sizeDelta.y;
            Debug.Log(y2);
            Debug.Log(y);
            itemsPerPage = (int)(y / y2);
        }
        else
        {
            itemsPerPage = 99999;
        }
        ClearChildren();
        maxPage = (items.Count - 1) / itemsPerPage + 1;
        if (usePage)
        {
            while (page > 0 && page * itemsPerPage >= items.Count)
            {
                page--;
            }
        }
        for (int j = 0; j < itemsPerPage; j++)
        {
            int num = page * itemsPerPage + j;
            if (num >= items.Count)
            {
                if (fillEmpty)
                {
                    new GameObject().AddComponent<RectTransform>().SetParent(layoutItems.transform, worldPositionStays: false);
                }
                continue;
            }
            object item = items[num];
            Component comp = callbacks.Instantiate(item, layoutItems.transform);
            callbacks.OnRedraw(item, comp, j);
            ButtonPair buttonPair = default(ButtonPair);
            buttonPair.obj = item;
            buttonPair.component = comp;
            ButtonPair item2 = buttonPair;
            UIButton uIButton = comp as UIButton;
            if (!uIButton)
            {
                UIItem uIItem = comp as UIItem;
                if ((bool)uIItem)
                {
                    uIButton = uIItem.button1;
                }
            }
            if ((bool)uIButton)
            {
                if (numbering && (bool)uIButton.keyText)
                {
                    uIButton.keyText.text = strNumber[j % strNumber.Length];
                }
                uIButton.onClick.AddListener(delegate
                {
                    Root.OnSelect(this);
                    callbacks.OnClick(item, comp);
                });
                if (highlightIndex == j)
                {
                    uIButton.DoHighlightTransition();
                }
            }
            buttons.Add(item2);
        }
        AfterRefresh();
        if ((bool)group)
        {
            group.Init((!selectFirst) ? (-1) : 0, null, onlyDirectChildrenButtonForGroup);
        }
        if (selectFirst && invokeSelected)
        {
            UIButton componentInChildren = layoutItems.GetComponentInChildren<UIButton>();
            if ((bool)componentInChildren)
            {
                componentInChildren.onClick.Invoke();
            }
        }
        isBuilt = true;
        SkinManager.tempSkin = tempSkin;
    }
References AfterRefresh(), bar, BuildLayout(), UIItem.button1, UIItem.button2, buttons, BaseList.callbacks, children, ClearChildren(), SkinManager.CurrentSkin, Debug, UIButton.DoHighlightTransition(), enableGroup, fillEmpty, SkinRootStatic.GetSkin(), group, heightFix, highlightIndex, UISelectableGroup.Init(), initialized, invokeSelected, BaseList.isBuilt, item, itemHeight, items, itemsPerPage, UIButton.keyText, layoutItems, maxPage, NextPage(), BaseList.numbering, onlyDirectChildrenButtonForGroup, OnSelect(), page, paginationBottom, paginationTop, PrevPage(), reset, Root, rows, selectFirst, BaseList.skinType, Sort(), BaseList.sortMode, strNumber, SkinManager.tempSkin, and usePage.
Referenced by DropdownGrid.Activate(), DropdownGrid.Build(), DropdownGrid.BuildIngredients(), Dialog.OnAfterInit(), OnClickFolder(), ContentChronicle.OnSwitchContent(), ContentStatistics.OnSwitchContent(), ContentTop.OnSwitchContent(), LayerDebug.OnSwitchContent(), WidgetCurrentTool.RebuildSlots(), LayerCollectible.Refresh(), LayerHire.Refresh(), LayerInspect.Refresh(), UIDistribution.Refresh(), UIRecipeInfo.Refresh(), LayerGacha.RefreshCoin(), LayerFactions.RefreshFactions(), ContentFaction.RefreshFactions(), LayerQuestBoard.RefreshHire(), UIRecipeInfo.RefreshList(), LayerLoadGame.RefreshList(), ContentHomeLog.RefreshLog(), LayerEmbark.RefreshMembers(), LayerQuestBoard.RefreshQuest(), LayerQuestBoard.RefreshRanking(), WindowChara.RefreshStatic(), LayerDistribution.SetContainer(), LayerShippingResult.Show(), and ContentRanking.SwitchRanking().
RemoveChild()
void UIList.RemoveChild (UIButton button) inline private
Definition at line 382 of file UIList.cs.
    {
        children[button].KillChildren();
        children.Remove(button);
        RebuildLayoutInParent();
        GetComponentInParent<ScrollRect>().RebuildLayout(recursive: true);
    }
References children, and RebuildLayoutInParent().
Referenced by OnClickFolder().
RemoveDynamic()
void UIList.RemoveDynamic (object item) inline
Definition at line 336 of file UIList.cs.
    {
        BaseCore.Instance.StopEventSystem(GetPair(item).component, delegate
        {
            items.Remove(item);
            ButtonPair item2 = buttons.First((ButtonPair a) => a.obj == item);
            buttons.IndexOf(item2);
            buttons.Remove(item2);
            UnityEngine.Object.DestroyImmediate(item2.component.gameObject);
            AfterRefresh();
        });
    }
References AfterRefresh(), buttons, UIList.ButtonPair.component, GetPair(), BaseCore.Instance, item, items, UIList.ButtonPair.obj, and BaseCore.StopEventSystem().
Referenced by ListOwner< T1, T2 >.MoveToOther().
Select() [1/2]
void UIList.Select (int index = 0, bool invoke = false) inline
Definition at line 644 of file UIList.cs.
    {
        if (buttons.Count < 0)
        {
            return;
        }
        ButtonPair buttonPair = buttons[Mathf.Clamp(index, 0, buttons.Count - 1)];
        UIButton uIButton = buttonPair.component as UIButton;
        if (!uIButton)
        {
            uIButton = (buttonPair.component as UIItem)?.button1;
        }
        if ((bool)uIButton)
        {
            if (invoke)
            {
                uIButton.onClick.Invoke();
            }
            if ((bool)uIButton.group)
            {
                uIButton.group.Select(uIButton);
            }
            else
            {
                uIButton.DoHighlightTransition();
            }
        }
    }
References buttons, UIButton.DoHighlightTransition(), UIButton.group, and UISelectableGroup.Select().
Referenced by PartialMapMenu.Init(), LayerResource.OnInit(), OnMove(), ContentQuest.OnSwitchContent(), PartialMapMenu.RefreshCategory(), LayerLoadGame.RefreshList(), Select(), and Select< T >().
Select() [2/2]
void UIList.Select (object obj, bool invoke = false) inline
Definition at line 673 of file UIList.cs.
    {
        for (int i = 0; i < items.Count; i++)
        {
            if (obj == items[i])
            {
                Select(i, invoke);
                break;
            }
        }
    }
References items, and Select().
Select< T >()
void UIList.Select< T > (Func< T, bool > func, bool invoke = false) inline
Definition at line 685 of file UIList.cs.
    {
        for (int i = 0; i < items.Count; i++)
        {
            if (func((T)items[i]))
            {
                Select(i, invoke);
                break;
            }
        }
    }
References items, and Select().
SetPage()
void UIList.SetPage (int i) inline
Definition at line 623 of file UIList.cs.
    {
        if (i < 0)
        {
            i = maxPage - 1;
        }
        else if (i >= maxPage)
        {
            i = 0;
        }
        page = i;
        Refresh();
    }
References maxPage, page, and Refresh().
Referenced by NextPage(), and PrevPage().
Sort()
void UIList.Sort () inline
Definition at line 697 of file UIList.cs.
    {
        if (callbacks.useSort)
        {
            items.Sort((object a, object b) => callbacks.OnSort(b, sortMode) - callbacks.OnSort(a, sortMode));
        }
    }
References BaseList.callbacks, items, and BaseList.sortMode.
Referenced by ChangeSort(), DramaCustomSequence.GetListGuide(), UIDragGridIngredients.Refresh(), Refresh(), and LayerQuestBoard.RefreshRanking().
Member Data Documentation
_layoutItems
LayoutGroup UIList._layoutItems
Definition at line 207 of file UIList.cs.
bar
UIListTopbar UIList.bar
Definition at line 195 of file UIList.cs.
Referenced by Refresh().
buildLayout
bool UIList.buildLayout
Definition at line 199 of file UIList.cs.
Referenced by BuildLayout().
buttons
List<ButtonPair> UIList.buttons = new List<ButtonPair>()
Definition at line 244 of file UIList.cs.
Referenced by AM_Adv._OnUpdateInput(), ClearChildren(), GetPair(), LayerList.OnUpdateInput(), WidgetCurrentTool.RebuildSlots(), Redraw(), LayerCollectible.Refresh(), LayerTravel.Refresh(), LayerWidget.Refresh(), Refresh(), UIInventory.RefreshGrid(), ContentQuest.RefreshTrackButtons(), LayerNewspaper.RefreshVote(), RemoveDynamic(), LayerEmbark.RerollPC(), WidgetCurrentTool.Select(), Select(), LayerAbility.SetDirty(), LayerList.SetListCheck< TValue >(), ContentRanking.SwitchRanking(), and LayerInventory.TryShowGuide().
children
Dictionary<UIButton, UIList> UIList.children = new Dictionary<UIButton, UIList>()
Definition at line 263 of file UIList.cs.
Referenced by CreateChild(), KillChildren(), OnClickFolder(), OnSelect(), Refresh(), and RemoveChild().
disableInstaClick
bool UIList.disableInstaClick = true
Definition at line 223 of file UIList.cs.
Referenced by UIList.Callback< T1, T2 >.Instantiate().
enableGroup
bool UIList.enableGroup = true
Definition at line 215 of file UIList.cs.
Referenced by Refresh().
fillEmpty
bool UIList.fillEmpty
Definition at line 197 of file UIList.cs.
Referenced by Refresh().
group
UISelectableGroup UIList.group
Definition at line 205 of file UIList.cs.
Referenced by UIRecipeInfo.OnRotate(), OnSelect(), UIRecipeInfo.Refresh(), and Refresh().
HeightDefault
const int UIList.HeightDefault = 34 static
Definition at line 253 of file UIList.cs.
heightFix
int UIList.heightFix
Definition at line 229 of file UIList.cs.
Referenced by Refresh().
highlightIndex
int UIList.highlightIndex private
Definition at line 272 of file UIList.cs.
Referenced by Refresh().
idMold
string UIList.idMold
Definition at line 247 of file UIList.cs.
Referenced by GetMold< T >().
ignoreNullObj
bool UIList.ignoreNullObj = true
Definition at line 225 of file UIList.cs.
Referenced by Add().
initialized
bool UIList.initialized private
Definition at line 255 of file UIList.cs.
Referenced by Refresh().
invokeSelected
bool UIList.invokeSelected
Definition at line 213 of file UIList.cs.
Referenced by Refresh().
itemHeight
ItemHeight UIList.itemHeight
Definition at line 227 of file UIList.cs.
Referenced by Refresh().
items
List<object> UIList.items = new List<object>()
Definition at line 241 of file UIList.cs.
Referenced by DropdownGrid.Activate(), Add(), Clear(), GetIndexOf(), ContentQuest.OnSwitchContent(), ContentPopulation.Refresh(), Refresh(), WindowCharaMini.Refresh(), PartialMapMenu.RefreshCategory(), LayerLoadGame.RefreshList(), LayerPolicy.RefreshPolicyList(), WindowChara.RefreshSkill(), RemoveDynamic(), Select(), Select< T >(), LayerList.SetStringList(), and Sort().
itemsPerPage
int UIList.itemsPerPage
Definition at line 238 of file UIList.cs.
Referenced by Refresh().
langNoItem
string UIList.langNoItem
Definition at line 189 of file UIList.cs.
maxPage
int UIList.maxPage
Definition at line 235 of file UIList.cs.
Referenced by AfterRefresh(), Refresh(), and SetPage().
menu
UISelectableGroup UIList.menu
Definition at line 193 of file UIList.cs.
moldItem
Transform UIList.moldItem
Definition at line 209 of file UIList.cs.
Referenced by GetMold< T >().
moldList
UIList UIList.moldList
Definition at line 259 of file UIList.cs.
Referenced by CreateChild().
onlyDirectChildrenButtonForGroup
bool UIList.onlyDirectChildrenButtonForGroup
Definition at line 217 of file UIList.cs.
Referenced by Refresh().
page
int UIList.page
Definition at line 232 of file UIList.cs.
Referenced by AfterRefresh(), NextPage(), PrevPage(), Refresh(), and SetPage().
paginationBottom
UIItem UIList.paginationBottom
Definition at line 203 of file UIList.cs.
Referenced by AfterRefresh(), and Refresh().
paginationTop
UIItem UIList.paginationTop
Definition at line 201 of file UIList.cs.
Referenced by AfterRefresh(), and Refresh().
parent
UIList UIList.parent
Definition at line 261 of file UIList.cs.
Referenced by UIList.Callback< T1, T2 >.Instantiate(), WindowChara.OnSwitchContent(), and RebuildLayoutInParent().
reset
bool UIList.reset private
Definition at line 257 of file UIList.cs.
Referenced by Clear(), and Refresh().
rows
int UIList.rows
Definition at line 191 of file UIList.cs.
Referenced by BuildLayout(), and Refresh().
selectFirst
bool UIList.selectFirst
Definition at line 211 of file UIList.cs.
Referenced by Refresh().
SETab
Action UIList.SETab
Initial value:
= delegate
    {
    }
Definition at line 249 of file UIList.cs.
strNumber
string [] UIList.strNumber static
Initial value:
= new string[26]
    {
        "a", "b", "c", "d", "e", "f", "g", "h", "i", "j",
        "k", "l", "m", "n", "o", "p", "q", "r", "s", "t",
        "u", "v", "w", "x", "y", "z"
    }
Definition at line 265 of file UIList.cs.
Referenced by Refresh().
usePage
bool UIList.usePage
Definition at line 219 of file UIList.cs.
Referenced by Refresh().
usePool
bool UIList.usePool
Definition at line 221 of file UIList.cs.
Referenced by ClearChildren().
Property Documentation
gridLayout
GridLayoutGroup UIList.gridLayout get
Definition at line 276 of file UIList.cs.
ItemCount
override int UIList.ItemCount get
Definition at line 278 of file UIList.cs.
layoutItems
LayoutGroup UIList.layoutItems get
Definition at line 274 of file UIList.cs.
Referenced by AfterRefresh(), BuildLayout(), ClearChildren(), CreateChild(), GetMold< T >(), and Refresh().
Root
UIList UIList.Root get
Definition at line 282 of file UIList.cs.
    {
        get
        {
            if (!parent)
            {
                return this;
            }
            return parent.Root;
        }
    }
Referenced by Refresh().
RowCount
override int UIList.RowCount get
Definition at line 280 of file UIList.cs.
The documentation for this class was generated from the following file:
Elin/Plugins.UI/UIList.cs