Elin Decompiled Documentation: LayerInspect Class Reference
LayerInspect Class Reference
Classes
class MenuItem
Public Member Functions
void SetItems (List< Thing > things)
void SetItemsOnHitPoint ()
override void OnUpdateInput ()
void Refresh ()
Public Member Functions inherited from ELayer
override void OnBeforeAddLayer ()
void InitInspector ()
sealed override void Init ()
override void OnAfterAddLayer ()
void TryShowHelp ()
void AddLayerToUI (string id)
void TryShowHint (string _langHint=null)
void TalkHomeMemeber (string id)
void TalkMaid (string id)
override void OnRightClick ()
Public Member Functions inherited from Layer
virtual string GetTextHeader (Window window)
virtual bool HeaderIsListOf (int id)
virtual void Init ()
virtual void OnInit ()
virtual void OnAfterInit ()
virtual void ApplySkin ()
void ShowScreenLock (string id)
void UpdateInput ()
virtual void OnUpdateInput ()
virtual void OnRightClick ()
virtual bool OnBack ()
virtual void OnChangeLayer ()
virtual void OnCreate ()
void _AddLayer (string id)
Layer AddLayer (string id)
T AddLayer< T > ()
T AddLayer< T > (string id)
T AddLayerDontCloseOthers< T > ()
Layer AddLayerDontCloseOthers (Layer l)
T GetOrAddLayer< T > ()
virtual void OnBeforeAddLayer ()
virtual void OnAfterAddLayer ()
Layer AddLayer (Layer l)
void ToggleLayer (string id)
T ToggleLayer< T > (string id=null)
void WaitAndClose ()
void OnClickClose ()
virtual void Close ()
void CloseLayers ()
void RemoveLayers (bool removeImportant=false)
bool RemoveLayer< T > ()
void RemoveLayer (Layer l)
virtual void OnKill ()
Layer SetOnKill (Action action)
void DisableClose ()
void Delay (float duration=0.05f)
Layer SetDelay (float d)
Layer GetLayer (string id)
T GetLayer< T > (bool fromTop=false)
Layer GetTopLayer ()
void SwitchContent (int idWindow, int i)
virtual void OnSwitchContent (Window window)
Layer SetTitles (string langList, string idHeaderRow=null)
bool IsBlockWidgetClick ()
bool IsHideHud ()
bool IsAllowGeneralInput ()
bool IsUseBlur ()
bool IsPointerOnLayer ()
void ApplySkin ()
Static Public Member Functions
static MenuItem GetItem (Card t)
static List< MenuItem > GetMenuItems ()
Static Public Member Functions inherited from ELayer
static int rnd (int a)
Static Public Member Functions inherited from Layer
static T Create< T > ()
static T Create< T > (string path)
static Layer Create (string path)
Public Attributes
bool inspectMap
UIList list
List< MenuItem > items = new List<MenuItem>()
Public Attributes inherited from Layer
Option option
UnityEvent onKill
Anime animeIn
Anime animeOut
bool closeOthers
bool defaultActionMode = true
Button screenLock
Layer parent
string idLayer
List< Layer > layers = new List<Layer>()
Vector2 lastParentPos
List< Window > windows = new List<Window>()
string langHint
Additional Inherited Members
Static Public Attributes inherited from Layer
static int skipInput
static bool closeOnRightClick
static bool rightClicked
static bool cancelKeyDown
static bool ignoreSounds
static Transform blurStopInstance
static string[] searchPath = new string[3] { "Layer", "Layer/Dialog", "Layer/LayerHome" }
Protected Member Functions inherited from ELayer
sealed override void _Close ()
sealed override void Kill ()
Protected Member Functions inherited from Layer
virtual void Awake ()
virtual void _Close ()
virtual void Kill ()
Protected Attributes inherited from Layer
RectTransform _rect
bool isDestroyed
Properties inherited from ELayer
static Core core [get]
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static FactionBranch Branch [get]
static Faction Home [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static CoreConfig config [get]
static GameSetting setting [get]
static ColorProfile Colors [get]
static SourceManager sources [get]
static World world [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
bool IsFloat [get]
virtual string IdHelp [get]
Properties inherited from Layer
Layer TopLayer [get]
string uid [get]
virtual RectTransform rectLayers [get]
virtual bool blockWidgetClick [get]
Detailed Description
Definition at line 5 of file LayerInspect.cs.
Member Function Documentation
GetItem()
static MenuItem LayerInspect.GetItem (Card t) inline static
Definition at line 93 of file LayerInspect.cs.
    {
        return new MenuItem
        {
            card = t,
            text = t.Name,
            action = delegate
            {
                if (t.isChara)
                {
                    ELayer.ui.AddLayer<LayerChara>().SetChara(t.Chara);
                }
                else
                {
                    ELayer.ui.AddLayer<LayerInfo>().Set(t);
                }
            }
        };
    }
References card, Card.Chara, Card.isChara, Card.Name, and ELayer.ui.
Referenced by GetMenuItems(), and SetItems().
GetMenuItems()
static List< MenuItem > LayerInspect.GetMenuItems () inline static
Definition at line 113 of file LayerInspect.cs.
    {
        List<MenuItem> list = new List<MenuItem>();
        Point point = Scene.HitPoint.Copy();
        if (!point.IsValid)
        {
            return list;
        }
        foreach (Card item in point.ListCards())
        {
            if (item.isSynced)
            {
                list.Add(GetItem(item));
            }
        }
        if (point.area != null)
        {
            list.Add(new MenuItem
            {
                text = point.area.Name,
                action = delegate
                {
                }
            });
        }
        if (point.cell.HasLiquid)
        {
            list.Add(new MenuItem
            {
                text = point.cell.GetLiquidName(),
                action = delegate
                {
                    ELayer.ui.AddLayer<LayerInfo>().SetLiquid(point.cell);
                },
                renderRow = point.cell.sourceEffect
            });
        }
        if (point.matBlock.id != 0)
        {
            list.Add(new MenuItem
            {
                text = point.cell.GetBlockName(),
                action = delegate
                {
                    ELayer.ui.AddLayer<LayerInfo>().SetBlock(point.cell);
                },
                renderRow = point.cell.sourceBlock
            });
        }
        if (point.matFloor.id != 0)
        {
            list.Add(new MenuItem
            {
                text = point.cell.GetFloorName(),
                action = delegate
                {
                    ELayer.ui.AddLayer<LayerInfo>().SetFloor(point.cell);
                },
                renderRow = point.cell.sourceFloor
            });
        }
        if (point.cell.obj != 0)
        {
            list.Add(new MenuItem
            {
                text = point.sourceObj.GetName(),
                action = delegate
                {
                    ELayer.ui.AddLayer<LayerInfo>().SetObj(point.cell);
                },
                renderRow = point.cell.sourceObj
            });
        }
        return list;
    }
References UIList.Add(), Point.Copy(), GetItem(), Scene.HitPoint, Point.IsValid, item, list, and ELayer.ui.
Referenced by SetItemsOnHitPoint().
OnUpdateInput()
override void LayerInspect.OnUpdateInput () inline virtual
Reimplemented from Layer.
Definition at line 42 of file LayerInspect.cs.
    {
        if (!inspectMap)
        {
            return;
        }
        if (Input.GetMouseButtonDown(0))
        {
            if (!ELayer.ui.isPointerOverUI && Scene.HitPoint.IsValid)
            {
                SetItemsOnHitPoint();
            }
        }
        else
        {
            _ = Input.anyKeyDown;
        }
    }
References Scene.HitPoint, inspectMap, Point.IsValid, SetItemsOnHitPoint(), and ELayer.ui.
Refresh()
void LayerInspect.Refresh () inline
Definition at line 61 of file LayerInspect.cs.
    {
        list.Clear();
        list.callbacks = new UIList.Callback<MenuItem, ButtonGeneral>
        {
            onClick = delegate(MenuItem a, ButtonGeneral b)
            {
                if (a.action != null)
                {
                    a.action();
                }
            },
            onInstantiate = delegate(MenuItem a, ButtonGeneral b)
            {
                if (a.card != null)
                {
                    b.SetCard(a.card);
                }
                else
                {
                    b.mainText.text = a.text;
                    if (a.renderRow != null)
                    {
                        a.renderRow.SetImage(b.icon);
                    }
                }
            }
        };
        list.AddCollection(items);
        list.Refresh();
    }
References LayerInspect.MenuItem.action, UIList.AddCollection(), LayerInspect.MenuItem.card, UIList.Clear(), UIButton.icon, items, list, UIList.Refresh(), LayerInspect.MenuItem.renderRow, ButtonGeneral.SetCard(), RenderRow.SetImage(), and LayerInspect.MenuItem.text.
Referenced by SetItems(), and SetItemsOnHitPoint().
SetItems()
void LayerInspect.SetItems (List< Thing > things) inline
Definition at line 26 of file LayerInspect.cs.
    {
        foreach (Thing thing in things)
        {
            items.Add(GetItem(thing));
        }
        Refresh();
    }
References GetItem(), items, and Refresh().
SetItemsOnHitPoint()
void LayerInspect.SetItemsOnHitPoint () inline
Definition at line 35 of file LayerInspect.cs.
    {
        inspectMap = true;
        items = GetMenuItems();
        Refresh();
    }
References GetMenuItems(), inspectMap, items, and Refresh().
Referenced by OnUpdateInput().
Member Data Documentation
inspectMap
bool LayerInspect.inspectMap
Definition at line 20 of file LayerInspect.cs.
Referenced by OnUpdateInput(), and SetItemsOnHitPoint().
items
List<MenuItem> LayerInspect.items = new List<MenuItem>()
Definition at line 24 of file LayerInspect.cs.
Referenced by Refresh(), SetItems(), and SetItemsOnHitPoint().
list
UIList LayerInspect.list
Definition at line 22 of file LayerInspect.cs.
Referenced by GetMenuItems(), and Refresh().
The documentation for this class was generated from the following file:
Elin/LayerInspect.cs