Elin Decompiled Documentation: Faction Class Reference
Faction Class Reference
Public Member Functions
void Init ()
void OnLoad ()
float GetHappiness ()
Sprite GetSprite ()
int CountTax ()
List< FactionBranch > GetChildren ()
int CountWealth ()
int CountTerritories ()
int CountMembers ()
Hostility GetHostility ()
void ModRelation (int a)
bool HasMember (string id, bool includeReserve=true)
void AddContribution (int a)
void AddReserve (Chara c)
void RemoveReserve (Chara c)
void OnAdvanceDay ()
void OnAdvanceMonth ()
void TryPayBill (Thing bill)
FactionBranch FindBranch (Chara c)
void AddGlobalPolicy (int id)
bool IsGlobalPolicyActive (int id)
void SetGlobalPolicyActive (int id, bool active)
int GetResidentTax ()
int GetRankIncome ()
int GetFactionSalary ()
int GetTotalTax (bool evasion)
int GetBaseTax (bool evasion)
int GetFameTax (bool evasion)
int EvadeTax (int v, bool evasion)
void SetTaxTooltip (UINote n)
int CountTaxFreeLand ()
Static Public Member Functions
static Faction Create (SourceFaction.Row r)
Static Public Member Functions inherited from EClass
static int rnd (int a)
static int curve (int a, int start, int step, int rate=75)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Public Attributes
FactionRelation relation = new FactionRelation()
int maxReserve = 3
string id
string uid
string name
List< HireInfo > listReserve = new List<HireInfo>()
ElementContainerZone elements = new ElementContainerZone()
HashSet< int > globalPolicies = new HashSet<int>()
ElementContainerFaction charaElements = new ElementContainerFaction()
SourceFaction.Row _source
Properties
string Name [get]
SourceFaction.Row source [get]
virtual string TextType [get]
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Additional Inherited Members
Static Public Attributes inherited from EClass
static Core core
Detailed Description
Definition at line 6 of file Faction.2.cs.
Member Function Documentation
AddContribution()
void Faction.AddContribution (int a) inline
Definition at line 179 of file Faction.2.cs.
    {
        if (a == 0 || this.relation.type != FactionRelation.RelationType.Member)
        {
            return;
        }
        this.relation.exp += a;
        Msg.Say("contribute", a.ToString() ?? "", this.Name, null, null);
    }
References relation, Msg.Say(), and FactionRelation.type.
Referenced by AI_Shopping.Buy(), Card.DamageHP(), CoreDebug.ModContribution(), ShopTransaction.OnEndTransaction(), and TraitBaseSpellbook.OnRead().
AddGlobalPolicy()
void Faction.AddGlobalPolicy (int id) inline
Definition at line 296 of file Faction.2.cs.
    {
        this.globalPolicies.Add(id);
    }
References globalPolicies.
Referenced by PolicyManager.AddPolicy().
AddReserve()
void Faction.AddReserve (Chara c) inline
Definition at line 189 of file Faction.2.cs.
    {
        if (c.memberType == FactionMemberType.Livestock)
        {
            c.SetInt(36, EClass.world.date.GetRaw(0) + 14400);
        }
        if (c.IsHomeMember())
        {
            c.homeBranch.RemoveMemeber(c);
        }
        if (c.currentZone != null)
        {
            c.currentZone.RemoveCard(c);
        }
        if (EClass.Branch.uidMaid == c.uid)
        {
            EClass.Branch.uidMaid = 0;
        }
        HireInfo item = new HireInfo
        {
            chara = c,
            isNew = true
        };
        this.listReserve.Add(item);
    }
References EClass.Branch, Chara.currentZone, World.date, Date.GetRaw(), Chara.homeBranch, Chara.IsHomeMember(), listReserve, Chara.memberType, Zone.RemoveCard(), FactionBranch.RemoveMemeber(), BaseCard.SetInt(), Card.uid, FactionBranch.uidMaid, and EClass.world.
Referenced by ItemGachaResult.Confirm(), and BaseListPeople.OnClick().
CountMembers()
int Faction.CountMembers () inline
Definition at line 116 of file Faction.2.cs.
    {
        int num = 0;
        using (Dictionary<int, Chara>.ValueCollection.Enumerator enumerator = EClass.game.cards.globalCharas.Values.GetEnumerator())
        {
            while (enumerator.MoveNext())
            {
                if (enumerator.Current.Chara.faction == this)
                {
                    num++;
                }
            }
        }
        return num;
    }
References Game.cards, EClass.game, and CardManager.globalCharas.
Referenced by LayerGlobalMap.RefreshSummary().
CountTax()
int Faction.CountTax () inline
Definition at line 68 of file Faction.2.cs.
    {
        return (int)((float)this.CountWealth() * 0.1f);
    }
References CountWealth().
CountTaxFreeLand()
int Faction.CountTaxFreeLand () inline
Definition at line 407 of file Faction.2.cs.
    {
        int num = 0;
        using (List<FactionBranch>.Enumerator enumerator = EClass.pc.faction.GetChildren().GetEnumerator())
        {
            while (enumerator.MoveNext())
            {
                if (enumerator.Current.policies.IsActive(2514, -1))
                {
                    num++;
                }
            }
        }
        return num;
    }
References Chara.faction, GetChildren(), and EClass.pc.
Referenced by FactionBranch.OnClaimZone(), and ContentPolicy.RefreshPolicyList().
CountTerritories()
int Faction.CountTerritories () inline
Definition at line 100 of file Faction.2.cs.
    {
        int num = 0;
        using (Dictionary<int, Spatial>.ValueCollection.Enumerator enumerator = EClass.game.spatials.map.Values.GetEnumerator())
        {
            while (enumerator.MoveNext())
            {
                if (enumerator.Current.mainFaction == this)
                {
                    num++;
                }
            }
        }
        return num;
    }
References EClass.game, SpatialManager.map, and Game.spatials.
Referenced by WindowChara.RefreshProfile(), and LayerGlobalMap.RefreshSummary().
CountWealth()
int Faction.CountWealth () inline
Definition at line 86 of file Faction.2.cs.
    {
        if (EClass._zone.IsPCFaction)
        {
            EClass._zone.branch.resources.Refresh();
        }
        int num = 0;
        foreach (FactionBranch factionBranch in this.GetChildren())
        {
            num += factionBranch.Worth;
        }
        return num;
    }
References EClass._zone, Zone.branch, GetChildren(), Zone.IsPCFaction, HomeResourceManager.Refresh(), FactionBranch.resources, and FactionBranch.Worth.
Referenced by CountTax(), and LayerGlobalMap.RefreshSummary().
Create()
static Faction Faction.Create (SourceFaction::Row r) inline static
Definition at line 37 of file Faction.2.cs.
    {
        Faction faction = ClassCache.Create<Faction>(r.type, "Elin");
        faction.id = r.id;
        faction.Init();
        return faction;
    }
References Create(), id, and Init().
Referenced by Create(), and FactionManager.OnCreateGame().
EvadeTax()
int Faction.EvadeTax (int v, bool evasion) inline
Definition at line 385 of file Faction.2.cs.
    {
        if (!evasion)
        {
            return v;
        }
        int num = 0;
        foreach (FactionBranch factionBranch in EClass.pc.faction.GetChildren())
        {
            num += factionBranch.Evalue(2119);
        }
        return (int)((float)(v * 100) / (100f + Mathf.Sqrt((float)(num * 5))));
    }
References FactionBranch.Evalue(), Chara.faction, GetChildren(), and EClass.pc.
Referenced by GetBaseTax(), and GetFameTax().
FindBranch()
FactionBranch Faction.FindBranch (Chara c) inline
Definition at line 284 of file Faction.2.cs.
    {
        foreach (FactionBranch factionBranch in EClass.pc.faction.GetChildren())
        {
            if (factionBranch.members.Contains(c))
            {
                return factionBranch;
            }
        }
        return null;
    }
References Chara.faction, GetChildren(), FactionBranch.members, and EClass.pc.
Referenced by FactionBranch.AddMemeber().
GetBaseTax()
int Faction.GetBaseTax (bool evasion) inline
Definition at line 372 of file Faction.2.cs.
    {
        int a = EClass.world.date.year - EClass.game.Prologue.year;
        int v = 500 + Mathf.Min(a, 10) * 500;
        return this.EvadeTax(v, evasion);
    }
References EvadeTax(), EClass.game, Game.Prologue, and Prologue.year.
Referenced by GetTotalTax().
GetChildren()
List< FactionBranch > Faction.GetChildren () inline
Definition at line 73 of file Faction.2.cs.
    {
        List<FactionBranch> list = new List<FactionBranch>();
        foreach (Spatial spatial in EClass.game.spatials.map.Values)
        {
            if (spatial.mainFaction == this)
            {
                list.Add((spatial as Zone).branch);
            }
        }
        return list;
    }
References EClass.game, Spatial.mainFaction, SpatialManager.map, and Game.spatials.
Referenced by CountTaxFreeLand(), CountWealth(), EvadeTax(), FindBranch(), RankedZoneManager.GetIncome(), GetRankIncome(), GetResidentTax(), IsGlobalPolicyActive(), OnAdvanceDay(), OnAdvanceMonth(), Game.OnLoad(), TraitBookSkill.OnRead(), TraitDeedRelocate.OnRead(), Card.PurgeDuplicateArtifact(), SetGlobalPolicyActive(), Player.SimulateFaction(), and TraitBookPlan.WriteNote().
GetFactionSalary()
int Faction.GetFactionSalary () inline
Definition at line 353 of file Faction.2.cs.
    {
        int num = 0;
        foreach (Faction faction in EClass.game.factions.dictAll.Values)
        {
            num += faction.relation.GetSalary();
        }
        if (num > 0)
        {
            Msg.Say("getFactionSalary", Lang._currency(num, "money"), null, null, null);
        }
        return num;
    }
References FactionManager.dictAll, Game.factions, EClass.game, FactionRelation.GetSalary(), relation, and Msg.Say().
Referenced by OnAdvanceMonth().
GetFameTax()
int Faction.GetFameTax (bool evasion) inline
Definition at line 379 of file Faction.2.cs.
    {
        int v = EClass.curve(EClass.player.fame * 2, 10000, 2000, 80);
        return this.EvadeTax(v, evasion);
    }
References EClass.curve(), EvadeTax(), Player.fame, and EClass.player.
Referenced by GetTotalTax().
GetHappiness()
float Faction.GetHappiness () inline
Definition at line 58 of file Faction.2.cs.
    {
        return 50f;
    }
Referenced by FactionGroup.GetHappiness().
GetHostility()
Hostility Faction.GetHostility () inline
Definition at line 132 of file Faction.2.cs.
    {
        if (this == EClass.Home || this.relation.affinity >= 200)
        {
            return Hostility.Ally;
        }
        if (this.relation.affinity >= 100)
        {
            return Hostility.Friend;
        }
        if (this.relation.affinity <= -100)
        {
            return Hostility.Enemy;
        }
        return Hostility.Neutral;
    }
References FactionRelation.affinity, EClass.Home, and relation.
Referenced by Chara.SetFaction().
GetRankIncome()
int Faction.GetRankIncome () inline
Definition at line 339 of file Faction.2.cs.
    {
        int num = 0;
        foreach (FactionBranch factionBranch in EClass.pc.faction.GetChildren())
        {
            num += EClass.game.spatials.ranks.GetIncome(factionBranch.owner);
        }
        if (num > 0)
        {
            Msg.Say("getRankIncome", Lang._currency(num, "money"), null, null, null);
        }
        return num;
    }
References Chara.faction, EClass.game, GetChildren(), RankedZoneManager.GetIncome(), FactionBranch.owner, EClass.pc, SpatialManager.ranks, Msg.Say(), and Game.spatials.
Referenced by OnAdvanceMonth().
GetResidentTax()
int Faction.GetResidentTax () inline
Definition at line 325 of file Faction.2.cs.
    {
        int num = 0;
        foreach (FactionBranch factionBranch in EClass.pc.faction.GetChildren())
        {
            num += factionBranch.GetResidentTax();
        }
        if (num > 0)
        {
            Msg.Say("getResidentTax", Lang._currency(num, "money"), null, null, null);
        }
        return num;
    }
References Chara.faction, GetChildren(), FactionBranch.GetResidentTax(), EClass.pc, and Msg.Say().
Referenced by OnAdvanceMonth().
GetSprite()
Sprite Faction.GetSprite () inline
Definition at line 63 of file Faction.2.cs.
    {
        return ResourceCache.Load<Sprite>("Media/Graphics/Image/Faction/" + this.source.id);
    }
References source.
GetTotalTax()
int Faction.GetTotalTax (bool evasion) inline
Definition at line 367 of file Faction.2.cs.
    {
        return this.GetBaseTax(evasion) + this.GetFameTax(evasion) + EClass.player.extraTax;
    }
References Player.extraTax, GetBaseTax(), GetFameTax(), and EClass.player.
Referenced by OnAdvanceMonth().
HasMember()
bool Faction.HasMember (string id, bool includeReserve = true) inline
Definition at line 154 of file Faction.2.cs.
    {
        foreach (Chara chara in EClass.game.cards.globalCharas.Values)
        {
            if (chara.id == id && chara.IsHomeMember())
            {
                return true;
            }
        }
        if (includeReserve)
        {
            using (List<HireInfo>.Enumerator enumerator2 = this.listReserve.GetEnumerator())
            {
                while (enumerator2.MoveNext())
                {
                    if (enumerator2.Current.chara.id == id)
                    {
                        return true;
                    }
                }
            }
        }
        return false;
    }
References Game.cards, EClass.game, CardManager.globalCharas, Card.id, Chara.IsHomeMember(), and listReserve.
Referenced by QuestDialog.CanStartQuest().
Init()
void Faction.Init () inline
Definition at line 45 of file Faction.2.cs.
    {
        EClass.game.factions.AssignUID(this);
        this.relation.faction = this;
        this.relation.affinity = this.source.relation;
        this.name = this.source.GetText("name", false);
    }
References FactionManager.AssignUID(), Game.factions, EClass.game, and source.
Referenced by Create().
IsGlobalPolicyActive()
bool Faction.IsGlobalPolicyActive (int id) inline
Definition at line 301 of file Faction.2.cs.
    {
        bool result = false;
        using (List<FactionBranch>.Enumerator enumerator = EClass.pc.faction.GetChildren().GetEnumerator())
        {
            while (enumerator.MoveNext())
            {
                if (enumerator.Current.policies.IsActive(id, -1))
                {
                    result = true;
                }
            }
        }
        return result;
    }
References Chara.faction, GetChildren(), and EClass.pc.
Referenced by TryPayBill(), and FactionBranch.ValidateUpgradePolicies().
ModRelation()
void Faction.ModRelation (int a) inline
Definition at line 149 of file Faction.2.cs.
    {
        this.relation.affinity += a;
    }
OnAdvanceDay()
void Faction.OnAdvanceDay () inline
Definition at line 226 of file Faction.2.cs.
    {
        foreach (FactionBranch factionBranch in EClass.pc.faction.GetChildren())
        {
            factionBranch.OnAdvanceDay();
        }
    }
References Chara.faction, GetChildren(), FactionBranch.OnAdvanceDay(), and EClass.pc.
Referenced by GameDate.AdvanceDay().
OnAdvanceMonth()
void Faction.OnAdvanceMonth () inline
Definition at line 234 of file Faction.2.cs.
    {
        if (this.GetChildren().Count == 0)
        {
            return;
        }
        int num = 0;
        num += this.GetResidentTax();
        num += this.GetRankIncome();
        num += this.GetFactionSalary();
        if (num > 0)
        {
            Thing container_deposit = EClass.game.cards.container_deposit;
            if (EClass.pc.homeBranch.policies.IsActive(2711, -1) && (container_deposit.GetCurrency("money") > 0 || !container_deposit.things.IsFull(0)))
            {
                container_deposit.ModCurrency(num, "money");
                Msg.Say("bankIncome", Lang._currency(num, "money"), null, null, null);
            }
            else
            {
                Thing thing = ThingGen.Create("money", -1, -1).SetNum(num);
                Thing p = ThingGen.CreateParcel("parcel_salary", new Thing[]
                {
                    thing
                });
                EClass.world.SendPackage(p);
            }
        }
        num = this.GetTotalTax(true);
        Thing thing2 = ThingGen.CreateBill(num, true);
        thing2.SetInt(35, EClass.player.extraTax);
        Msg.Say("getBill", Lang._currency(num, "money"), null, null, null);
        this.TryPayBill(thing2);
        Msg.Say("bills", EClass.player.taxBills.ToString() ?? "", null, null, null);
        if (EClass.player.taxBills >= 4)
        {
            EClass.player.ModKarma(-50);
        }
    }
References Game.cards, CardManager.container_deposit, ThingGen.Create(), ThingGen.CreateBill(), ThingGen.CreateParcel(), Player.extraTax, EClass.game, GetChildren(), Card.GetCurrency(), GetFactionSalary(), GetRankIncome(), GetResidentTax(), GetTotalTax(), Chara.homeBranch, PolicyManager.IsActive(), ThingContainer.IsFull(), Card.ModCurrency(), Player.ModKarma(), EClass.pc, EClass.player, FactionBranch.policies, Msg.Say(), World.SendPackage(), BaseCard.SetInt(), Card.SetNum(), Player.taxBills, Card.things, TryPayBill(), and EClass.world.
Referenced by GameDate.AdvanceMonth().
OnLoad()
void Faction.OnLoad () inline
Definition at line 53 of file Faction.2.cs.
    {
        this.relation.faction = this;
    }
Referenced by FactionManager.OnLoad().
RemoveReserve()
void Faction.RemoveReserve (Chara c) inline
Definition at line 215 of file Faction.2.cs.
    {
        this.listReserve.ForeachReverse(delegate(HireInfo i)
        {
            if (i.chara == c || i.chara.uid == c.uid)
            {
                this.listReserve.Remove(i);
            }
        });
    }
References HireInfo.chara, listReserve, and Card.uid.
Referenced by FactionBranch.AddMemeber().
SetGlobalPolicyActive()
void Faction.SetGlobalPolicyActive (int id, bool active) inline
Definition at line 317 of file Faction.2.cs.
    {
        foreach (FactionBranch factionBranch in EClass.pc.faction.GetChildren())
        {
            factionBranch.policies.SetActive(id, active);
        }
    }
References Chara.faction, GetChildren(), EClass.pc, FactionBranch.policies, and PolicyManager.SetActive().
Referenced by FactionBranch.ValidateUpgradePolicies().
SetTaxTooltip()
void Faction.SetTaxTooltip (UINote n) inline
Definition at line 399 of file Faction.2.cs.
    {
        n.AddHeader("tax", null);
        n.AddTopic("tax_base", Lang._currency(this.GetBaseTax(true), true, 14) + " (" + Lang._currency(this.GetBaseTax(false), false, 14) + ")");
        n.AddTopic("tax_fame", Lang._currency(this.GetFameTax(true), true, 14) + " (" + Lang._currency(this.GetFameTax(false), false, 14) + ")");
        n.AddTopic("tax_extra", Lang._currency(EClass.player.extraTax, true, 14));
    }
References Player.extraTax, and EClass.player.
Referenced by UIHomeInfo.RefreshReport().
TryPayBill()
void Faction.TryPayBill (Thing bill) inline
Definition at line 274 of file Faction.2.cs.
    {
        if (this.IsGlobalPolicyActive(2705) && EClass.game.cards.container_deposit.GetCurrency("money") > bill.c_bill)
        {
            InvOwnerDeliver.PayBill(bill, true);
            return;
        }
        EClass.world.SendPackage(bill);
    }
References Card.c_bill, Game.cards, CardManager.container_deposit, EClass.game, Card.GetCurrency(), IsGlobalPolicyActive(), InvOwnerDeliver.PayBill(), World.SendPackage(), and EClass.world.
Referenced by OnAdvanceMonth(), and GameDate.ShipPackages().
Member Data Documentation
_source
SourceFaction.Row Faction._source
Definition at line 449 of file Faction.2.cs.
charaElements
ElementContainerFaction Faction.charaElements = new ElementContainerFaction()
Definition at line 447 of file Faction.2.cs.
Referenced by Element._WriteNote(), FactionBranch.AddMemeber(), CharaBody.Equip(), Element.IsFactionElement(), Religion.JoinFaith(), Religion.LeaveFaith(), ElementContainer.ListElements(), AttackProcess.Perform(), FactionBranch.RemoveMemeber(), FactionBranch.SetOwner(), CharaBody.Unequip(), ElementContainer.Value(), ElementContainerCard.ValueBonus(), and Element.BonusInfo.WriteNote().
elements
ElementContainerZone Faction.elements = new ElementContainerZone()
Definition at line 442 of file Faction.2.cs.
Referenced by FactionBranch.Evalue(), and FactionBranch.Upgrade().
globalPolicies
HashSet<int> Faction.globalPolicies = new HashSet<int>()
Definition at line 445 of file Faction.2.cs.
Referenced by AddGlobalPolicy(), and FactionBranch.ValidateUpgradePolicies().
id
string Faction.id
Definition at line 430 of file Faction.2.cs.
Referenced by FactionManager.AssignUID(), Create(), FactionManager.Find(), Game.OnLoad(), and ContentFaction.RefreshFactions().
listReserve
List<HireInfo> Faction.listReserve = new List<HireInfo>()
Definition at line 439 of file Faction.2.cs.
Referenced by AddReserve(), ListPeopleCallReserve.GetInfo(), ListPeopleSelect.GetInfo(), HasMember(), BaseListPeople.OnClick(), ListPeopleCallReserve.OnList(), LayerHire.Refresh(), and RemoveReserve().
maxReserve
int Faction.maxReserve = 3
Definition at line 427 of file Faction.2.cs.
Referenced by BaseListPeople.OnClick().
name
string Faction.name
Definition at line 436 of file Faction.2.cs.
Referenced by GameIndex.Create(), CoreDebug.LOG_Spatials(), ContentTop.OnSwitchContent(), LayerFactions.RefreshFactions(), ContentFaction.RefreshFactions(), ContentHomeReport.RefreshInfo(), UIHomeInfo.RefreshInfo(), UIZoneInfo.SetZone(), ContentRanking.SwitchRanking(), and EloPos.WriteNote().
relation
FactionRelation Faction.relation = new FactionRelation()
Definition at line 424 of file Faction.2.cs.
Referenced by AddContribution(), GameLang.ConvertDrama(), QuestGuild.GetDetailText(), GetFactionSalary(), GetHostility(), QuestGuild.GetTrackerText(), DramaOutcome.guild_promote(), CalcPlat.Learn(), LayerFactions.RefreshFactions(), ContentFaction.RefreshFactions(), UIFactionInfo.SetFaction(), and CalcPlat.Train().
uid
string Faction.uid
Definition at line 433 of file Faction.2.cs.
Referenced by FactionManager.AssignUID(), and RefFaction.RefFaction().
Property Documentation
Name
string Faction.Name get
Definition at line 8 of file Faction.2.cs.
    {
        get
        {
            return this.name;
        }
    }
Referenced by GameLang.ConvertDrama(), QuestGuild.GetDetailText(), RankedZone.GetFactionName(), DramaOutcome.guild_join(), UIHomeInfo.RefreshInfo(), UIFactionInfo.SetFaction(), and UIFactionInfo.SetZone().
source
SourceFaction.Row Faction.source get
Definition at line 16 of file Faction.2.cs.
    {
        get
        {
            SourceFaction.Row result;
            if ((result = this._source) == null)
            {
                result = (this._source = EClass.sources.factions.map[this.id]);
            }
            return result;
        }
    }
Referenced by GetSprite(), and Init().
TextType
virtual string Faction.TextType get
Definition at line 29 of file Faction.2.cs.
    {
        get
        {
            return "sub_faction".lang();
        }
    }
Referenced by LayerFactions.RefreshFactions(), ContentFaction.RefreshFactions(), and UIFactionInfo.SetFaction().
The documentation for this class was generated from the following file:
Elin/Faction.2.cs