Elin Decompiled Documentation: ZoneBlueprint Class Reference
ZoneBlueprint Class Reference
Classes
struct MapGenSetting
Public Member Functions
void Create ()
virtual void OnCreate ()
void GenerateMap (Zone zone)
Public Attributes
Map map
Zone zone
ZoneProfile zoneProfile
List< Chara > charas = new List<Chara>()
List< Thing > things = new List<Thing>()
MapGenSetting genSetting
int idDebug
EloMap.TileInfo[,] surrounding
bool customMap
bool ignoreRoad
Static Public Attributes
static int debugCount
Static Public Attributes inherited from EClass
static Core core
Properties
EloMap.TileInfo tileCenter [get]
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Additional Inherited Members
Static Public Member Functions inherited from EClass
static int rndSeed (int a, int seed)
static int rnd (int a)
static int curve (int a, int start, int step, int rate=75)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Detailed Description
Definition at line 3 of file ZoneBlueprint.cs.
Member Function Documentation
Create()
void ZoneBlueprint.Create () inline
Definition at line 46 of file ZoneBlueprint.cs.
    {
        OnCreate();
    }
References OnCreate().
Referenced by Game._Create(), Zone.CreateBP(), ZoneProfile.Generate(), and UIMapPreview.GenThread.Init().
GenerateMap()
void ZoneBlueprint.GenerateMap (Zone zone) inline
Definition at line 55 of file ZoneBlueprint.cs.
    {
        this.zone = zone;
        idDebug = debugCount;
        debugCount++;
        if (map == null)
        {
            map = new Map();
        }
        zone.map = map;
        if (!zoneProfile)
        {
            zoneProfile = zone.GetProfile();
        }
        if (!genSetting.variation)
        {
            genSetting.variation = zoneProfile.variation.Instantiate();
        }
        genSetting.seed = ((zoneProfile.seeds.height == -1) ? (Rand.rnd(10000) + 1) : zoneProfile.seeds.height);
        bool flag = false;
        if (zone.IDGenerator != null)
        {
            MapGenDungen.Instance.Generate(this);
        }
        else if (zone.IsRegion)
        {
            MapGenRegion.Instance.Generate(this);
        }
        else
        {
            flag = true;
            MapGen.Instance.Generate(this);
        }
        map.SetZone(zone);
        if (flag)
        {
            MapGen.Instance.Populate(map);
        }
    }
References debugCount, BaseMapGen.Generate(), genSetting, Zone.GetProfile(), ZoneProfile.Seeds.height, idDebug, Zone.IDGenerator, MapGen.Instance, MapGenDungen.Instance, MapGenRegion.Instance, Spatial.IsRegion, map, MapGen.Populate(), Rand.rnd(), ZoneProfile.seeds, Map.SetZone(), ZoneBlueprint.MapGenSetting.variation, ZoneProfile.variation, zone, and zoneProfile.
Referenced by Zone.Generate(), and ZoneProfile.Generate().
OnCreate()
virtual void ZoneBlueprint.OnCreate () inline virtual
Reimplemented in GameBlueprint.
Definition at line 51 of file ZoneBlueprint.cs.
    {
    }
Referenced by Create().
Member Data Documentation
charas
List<Chara> ZoneBlueprint.charas = new List<Chara>()
Definition at line 18 of file ZoneBlueprint.cs.
Referenced by LayerEmbark.GetAlias(), LayerEmbark.RefreshMembers(), GameBlueprint.RerollChara(), and LayerEmbark.RerollPC().
customMap
bool ZoneBlueprint.customMap
Definition at line 30 of file ZoneBlueprint.cs.
debugCount
int ZoneBlueprint.debugCount static
Definition at line 28 of file ZoneBlueprint.cs.
Referenced by GenerateMap().
genSetting
MapGenSetting ZoneBlueprint.genSetting
Definition at line 22 of file ZoneBlueprint.cs.
Referenced by BaseMapGen.Generate(), GenerateMap(), UIMapPreview.GenerateMap(), and LayerEmbark.OnClickPreview().
idDebug
int ZoneBlueprint.idDebug
Definition at line 24 of file ZoneBlueprint.cs.
Referenced by GenerateMap().
ignoreRoad
bool ZoneBlueprint.ignoreRoad
Definition at line 32 of file ZoneBlueprint.cs.
Referenced by MapGen.MakeRoad().
map
Map ZoneBlueprint.map
Definition at line 12 of file ZoneBlueprint.cs.
Referenced by UIMapPreview.CheckThread(), Zone.Generate(), BaseMapGen.Generate(), GenerateMap(), LayerEmbark.OnAfterAddLayer(), and LayerEmbark.OnClickPreview().
surrounding
EloMap.TileInfo [,] ZoneBlueprint.surrounding
Definition at line 26 of file ZoneBlueprint.cs.
Referenced by Zone.GetProfile(), MapGen.MakeNeighbor(), and MapGen.MakeNeighbor_old().
things
List<Thing> ZoneBlueprint.things = new List<Thing>()
Definition at line 20 of file ZoneBlueprint.cs.
zone
Zone ZoneBlueprint.zone
Definition at line 14 of file ZoneBlueprint.cs.
Referenced by BaseMapGen.Generate(), and GenerateMap().
zoneProfile
ZoneProfile ZoneBlueprint.zoneProfile
Definition at line 16 of file ZoneBlueprint.cs.
Referenced by BaseMapGen.Generate(), GenerateMap(), UIMapPreview.GenerateMap(), MapGen.OnGenerateTerrain(), and MapGen.Populate().
Property Documentation
tileCenter
EloMap.TileInfo ZoneBlueprint.tileCenter get
Definition at line 34 of file ZoneBlueprint.cs.
    {
        get
        {
            if (surrounding == null)
            {
                return null;
            }
            return surrounding[1, 1];
        }
    }
Referenced by MapGen.GenerateTerrain(), and MapGen.MakeRoad().
The documentation for this class was generated from the following file:
Elin/ZoneBlueprint.cs