Elin Decompiled Documentation: Applibot.NormalDissolve Class Reference
Applibot.NormalDissolve Class Reference
Protected Member Functions
override void UpdateMaterial (Material baseMaterial)
Protected Member Functions inherited from Applibot.CustomImageBase
virtual void UpdateMaterial (Material baseMaterial)
void OnEnable ()
void OnDisable ()
void OnDestroy ()
Private Attributes
Texture2D _dissovleTex
float _dissolveAmount
float _dissolveRange
Color _glowColor
int _dissolveTexId = Shader.PropertyToID("_DissolveTex")
int _dissolveRangeId = Shader.PropertyToID("_DissolveRange")
int _dissolveAmountId = Shader.PropertyToID("_DissolveAmount")
int _glowColorId = Shader.PropertyToID("_GlowColor")
Additional Inherited Members
Public Member Functions inherited from Applibot.CustomImageBase
Material GetModifiedMaterial (Material baseMaterial)
void DestroyMaterial ()
Protected Attributes inherited from Applibot.CustomImageBase
Material material
Properties inherited from Applibot.CustomImageBase
CanvasScaler canvasScaler [get]
Graphic graphic [get]
Detailed Description
Definition at line 5 of file NormalDissolve.cs.
Member Function Documentation
UpdateMaterial()
override void Applibot.NormalDissolve.UpdateMaterial (Material baseMaterial) inline protected virtual
Reimplemented from Applibot.CustomImageBase.
Definition at line 30 of file NormalDissolve.cs.
    {
        if (material == null)
        {
            Shader shader = Shader.Find("Applibot/UI/NormalDissolve");
            material = new Material(shader);
            material.CopyPropertiesFromMaterial(baseMaterial);
            material.hideFlags = HideFlags.HideAndDontSave;
        }
        material.SetTexture(_dissolveTexId, _dissovleTex);
        material.SetFloat(_dissolveAmountId, _dissolveAmount);
        material.SetFloat(_dissolveRangeId, _dissolveRange);
        material.SetColor(_glowColorId, _glowColor);
    }
References Applibot.NormalDissolve._dissolveAmount, Applibot.NormalDissolve._dissolveAmountId, Applibot.NormalDissolve._dissolveRange, Applibot.NormalDissolve._dissolveRangeId, Applibot.NormalDissolve._dissolveTexId, Applibot.NormalDissolve._dissovleTex, Applibot.NormalDissolve._glowColor, Applibot.NormalDissolve._glowColorId, Material, and Applibot.CustomImageBase.material.
Member Data Documentation
_dissolveAmount
float Applibot.NormalDissolve._dissolveAmount private
Definition at line 12 of file NormalDissolve.cs.
Referenced by Applibot.NormalDissolve.UpdateMaterial().
_dissolveAmountId
int Applibot.NormalDissolve._dissolveAmountId = Shader.PropertyToID("_DissolveAmount") private
Definition at line 26 of file NormalDissolve.cs.
Referenced by Applibot.NormalDissolve.UpdateMaterial().
_dissolveRange
float Applibot.NormalDissolve._dissolveRange private
Definition at line 16 of file NormalDissolve.cs.
Referenced by Applibot.NormalDissolve.UpdateMaterial().
_dissolveRangeId
int Applibot.NormalDissolve._dissolveRangeId = Shader.PropertyToID("_DissolveRange") private
Definition at line 24 of file NormalDissolve.cs.
Referenced by Applibot.NormalDissolve.UpdateMaterial().
_dissolveTexId
int Applibot.NormalDissolve._dissolveTexId = Shader.PropertyToID("_DissolveTex") private
Definition at line 22 of file NormalDissolve.cs.
Referenced by Applibot.NormalDissolve.UpdateMaterial().
_dissovleTex
Texture2D Applibot.NormalDissolve._dissovleTex private
Definition at line 8 of file NormalDissolve.cs.
Referenced by Applibot.NormalDissolve.UpdateMaterial().
_glowColor
Color Applibot.NormalDissolve._glowColor private
Definition at line 20 of file NormalDissolve.cs.
Referenced by Applibot.NormalDissolve.UpdateMaterial().
_glowColorId
int Applibot.NormalDissolve._glowColorId = Shader.PropertyToID("_GlowColor") private
Definition at line 28 of file NormalDissolve.cs.
Referenced by Applibot.NormalDissolve.UpdateMaterial().
The documentation for this class was generated from the following file:
Elin/Plugins.UI/Applibot/NormalDissolve.cs