Elin Decompiled Documentation: SourceJob Class Reference
SourceJob Class Reference
Classes
class Row
Public Member Functions
override Row CreateRow ()
override Row CreateRowByMapping (IReadOnlyDictionary< string, int > mapping)
override void SetRow (Row r)
override IReadOnlyDictionary< string, int > GetRowMapping ()
override IReadOnlyDictionary< string, string > GetTypeMapping ()
override void OnInit ()
Public Member Functions inherited from SourceDataString< SourceJob.Row >
override T GetRow (string id)
Static Public Attributes
static readonly IReadOnlyDictionary< string, int > RowMapping
static readonly IReadOnlyDictionary< string, string > TypeMapping
Detailed Description
Definition at line 4 of file SourceJob.cs.
Member Function Documentation
CreateRow()
override Row SourceJob.CreateRow () inline
Definition at line 114 of file SourceJob.cs.
    {
        return new Row
        {
            id = SourceData.GetString(0),
            name_JP = SourceData.GetString(1),
            name = SourceData.GetString(2),
            playable = SourceData.GetInt(3),
            STR = SourceData.GetInt(4),
            END = SourceData.GetInt(5),
            DEX = SourceData.GetInt(6),
            PER = SourceData.GetInt(7),
            LER = SourceData.GetInt(8),
            WIL = SourceData.GetInt(9),
            MAG = SourceData.GetInt(10),
            CHA = SourceData.GetInt(11),
            SPD = SourceData.GetInt(12),
            elements = Core.ParseElements(SourceData.GetStr(14)),
            weapon = SourceData.GetStringArray(15),
            equip = SourceData.GetString(16),
            domain = Core.ParseElements(SourceData.GetStr(17)),
            detail_JP = SourceData.GetString(18),
            detail = SourceData.GetString(19)
        };
    }
References SourceData< T, T2 >.GetInt(), SourceData< T, T2 >.GetStr(), SourceData< T, T2 >.GetString(), SourceData< T, T2 >.GetStringArray(), Core.ParseElements(), and weapon.
CreateRowByMapping()
override Row SourceJob.CreateRowByMapping (IReadOnlyDictionary< string, int > mapping) inline
Definition at line 140 of file SourceJob.cs.
    {
        return new Row
        {
            id = SourceData.GetString(mapping["id"]),
            name_JP = SourceData.GetString(mapping["name_JP"]),
            name = SourceData.GetString(mapping["name"]),
            playable = SourceData.GetInt(mapping["playable"]),
            STR = SourceData.GetInt(mapping["STR"]),
            END = SourceData.GetInt(mapping["END"]),
            DEX = SourceData.GetInt(mapping["DEX"]),
            PER = SourceData.GetInt(mapping["PER"]),
            LER = SourceData.GetInt(mapping["LER"]),
            WIL = SourceData.GetInt(mapping["WIL"]),
            MAG = SourceData.GetInt(mapping["MAG"]),
            CHA = SourceData.GetInt(mapping["CHA"]),
            SPD = SourceData.GetInt(mapping["SPD"]),
            elements = Core.ParseElements(SourceData.GetStr(mapping["elements"])),
            weapon = SourceData.GetStringArray(mapping["weapon"]),
            equip = SourceData.GetString(mapping["equip"]),
            domain = Core.ParseElements(SourceData.GetStr(mapping["domain"])),
            detail_JP = SourceData.GetString(mapping["detail_JP"]),
            detail = SourceData.GetString(mapping["detail"])
        };
    }
References SourceData< T, T2 >.GetInt(), SourceData< T, T2 >.GetStr(), SourceData< T, T2 >.GetString(), SourceData< T, T2 >.GetStringArray(), Core.ParseElements(), and weapon.
GetRowMapping()
override IReadOnlyDictionary< string, int > SourceJob.GetRowMapping () inline
Definition at line 171 of file SourceJob.cs.
    {
        return RowMapping;
    }
References RowMapping.
GetTypeMapping()
override IReadOnlyDictionary< string, string > SourceJob.GetTypeMapping () inline
Definition at line 176 of file SourceJob.cs.
    {
        return TypeMapping;
    }
References TypeMapping.
OnInit()
override void SourceJob.OnInit () inline
Definition at line 181 of file SourceJob.cs.
    {
        foreach (Row row in rows)
        {
            Dictionary<int, int> dictionary = (row.elementMap = Element.GetElementMap(row.elements));
            dictionary[70] = row.STR;
            dictionary[71] = row.END;
            dictionary[72] = row.DEX;
            dictionary[73] = row.PER;
            dictionary[74] = row.LER;
            dictionary[75] = row.WIL;
            dictionary[76] = row.MAG;
            dictionary[77] = row.CHA;
            dictionary[79] = row.SPD;
        }
    }
References SourceJob.Row.CHA, SourceJob.Row.DEX, SourceJob.Row.elements, SourceJob.Row.END, Element.GetElementMap(), SourceJob.Row.LER, SourceJob.Row.MAG, SourceJob.Row.PER, SourceJob.Row.SPD, SourceJob.Row.STR, and SourceJob.Row.WIL.
SetRow()
override void SourceJob.SetRow (Row r) inline
Definition at line 166 of file SourceJob.cs.
    {
        map[r.id] = r;
    }
References SourceJob.Row.id.
Member Data Documentation
RowMapping
readonly IReadOnlyDictionary<string, int> SourceJob.RowMapping static
Initial value:
= new Dictionary<string, int>
    {
        ["id"] = 0,
        ["name_JP"] = 1,
        ["name"] = 2,
        ["playable"] = 3,
        ["STR"] = 4,
        ["END"] = 5,
        ["DEX"] = 6,
        ["PER"] = 7,
        ["LER"] = 8,
        ["WIL"] = 9,
        ["MAG"] = 10,
        ["CHA"] = 11,
        ["SPD"] = 12,
        ["elements"] = 14,
        ["weapon"] = 15,
        ["equip"] = 16,
        ["domain"] = 17,
        ["detail_JP"] = 18,
        ["detail"] = 19
    }
Definition at line 68 of file SourceJob.cs.
Referenced by GetRowMapping().
TypeMapping
readonly IReadOnlyDictionary<string, string> SourceJob.TypeMapping static
Initial value:
= new Dictionary<string, string>
    {
        ["id"] = "string",
        ["name_JP"] = "string",
        ["name"] = "string",
        ["playable"] = "int",
        ["STR"] = "int",
        ["END"] = "int",
        ["DEX"] = "int",
        ["PER"] = "int",
        ["LER"] = "int",
        ["WIL"] = "int",
        ["MAG"] = "int",
        ["CHA"] = "int",
        ["SPD"] = "int",
        ["elements"] = "elements",
        ["weapon"] = "string[]",
        ["equip"] = "string",
        ["domain"] = "elements",
        ["detail_JP"] = "string",
        ["detail"] = "string"
    }
Definition at line 91 of file SourceJob.cs.
Referenced by GetTypeMapping().
The documentation for this class was generated from the following file:
Elin/SourceJob.cs