Elin Decompiled Documentation: QuestVernis Class Reference
QuestVernis Class Reference
Public Member Functions
override void OnEnterZone ()
override void OnChangePhase (int a)
override bool CanUpdateOnTalk (Chara c)
override void OnComplete ()
override string GetTextProgress ()
Public Member Functions inherited from QuestProgression
override string GetDetail (bool onJournal=false)
Public Member Functions inherited from QuestSequence
override string GetTitle ()
override void OnCompleteTask ()
Public Member Functions inherited from Quest
virtual Thing GetDestThing ()
virtual int GetExtraMoney ()
virtual int GetRewardPlat (int money)
override bool Equals (object obj)
virtual bool IsVisibleOnQuestBoard ()
virtual bool CanStartQuest ()
virtual bool CanUpdateOnTalk (Chara c)
virtual Zone CreateInstanceZone (Chara c)
virtual bool UpdateOnTalk ()
void Init ()
virtual void OnInit ()
Quest SetClient (Chara c, bool assignQuest=true)
void SetTask (QuestTask _task)
void Start ()
virtual void OnStart ()
virtual void OnEnterZone ()
virtual void OnClickQuest ()
void Fail ()
virtual void OnFail ()
virtual void ShowCompleteText ()
void Complete ()
virtual void OnBeforeComplete ()
virtual void OnDropReward ()
Thing DropReward (string id)
Thing DropReward (Thing t)
virtual void OnComplete ()
void CompleteTask ()
virtual void OnCompleteTask ()
virtual void OnGiveItem (Chara c, Thing t)
virtual void OnKillChara (Chara c)
virtual void OnModKarma (int a)
void NextPhase ()
void ChangePhase (int a)
virtual void OnChangePhase (int a)
string Parse (string s)
virtual string GetTitle ()
virtual string GetTrackerText ()
virtual string GetDetail (bool onJournal=false)
virtual string GetDetailText (bool onJournal=false)
virtual string GetTextProgress ()
string GetRewardText ()
virtual string GetTalkProgress ()
virtual string GetTalkComplete ()
void UpdateJournal ()
virtual bool IsDeliverTarget (Chara c)
virtual bool CanDeliverToClient (Chara c)
virtual bool CanDeliverToBox (Thing t)
virtual bool Deliver (Chara c, Thing t=null)
Properties
override string TitlePrefix [get]
Properties inherited from QuestProgression
override string TitlePrefix [get]
Properties inherited from QuestSequence
SourceQuest.Row originalSource [get]
override string idSource [get]
Properties inherited from Quest
Zone ClientZone [get]
Chara chara [get]
virtual SourceQuest.Row source [get]
bool Confetti [get]
bool IsExpired [get]
int Hours [get]
string TextDeadline [get]
virtual bool HasDLC [get]
virtual string idSource [get]
virtual string RewardSuffix [get]
virtual bool FameContent [get]
virtual string TextExtra [get]
virtual string TextExtra2 [get]
virtual int DangerLv [get]
virtual int AffinityGain [get]
virtual int BaseMoney [get]
virtual int KarmaOnFail [get]
virtual bool CanAbandon [get]
virtual int FameOnComplete [get]
virtual int RangeDeadLine [get]
virtual bool UseInstanceZone [get]
virtual bool ForbidTeleport [get]
virtual bool TrackOnStart [get]
virtual bool RequireClientInSameZone [get]
virtual DifficultyType difficultyType [get]
virtual Chara DestChara [get]
virtual string RefDrama1 [get]
virtual string RefDrama2 [get]
virtual string RefDrama3 [get]
virtual string RefDrama4 [get]
virtual string TitlePrefix [get]
virtual bool CanAutoAdvance [get]
virtual bool IsRandomQuest [get]
virtual string NameDeliver [get]
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Additional Inherited Members
Public Types inherited from Quest
enum DifficultyType {
Default , Deliver , Supply , Escort ,
Bulk , Meal , Farm , Music
}
enum SubReward { plat , gacha_coin , money2 , ticket_furniture }
Static Public Member Functions inherited from Quest
static Quest Create (string _id, string _idPerson=null, Chara c=null)
static List< Zone > ListDeliver ()
Static Public Member Functions inherited from EClass
static int rndSeed (int a, int seed)
static int rnd (int a)
static int curve (int a, int start, int step, int rate=75)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Public Attributes inherited from Quest
string id
int uid
int uidClientZone
int phase
int lv
int deadline
int difficulty
int rewardMoney
int bonusMoney
int startDate
int dangerLv
bool isNew
bool isComplete
bool track
Person person
QuestTask task
RefChara refChara = new RefChara()
Static Public Attributes inherited from Quest
const int PhaseComplete = 999
Static Public Attributes inherited from EClass
static Core core
Detailed Description
Definition at line 1 of file QuestVernis.cs.
Member Function Documentation
CanUpdateOnTalk()
override bool QuestVernis.CanUpdateOnTalk (Chara c) inline virtual
Reimplemented from Quest.
Definition at line 42 of file QuestVernis.cs.
    {
        if (phase != 0 && EClass._zone.id != "vernis")
        {
            return false;
        }
        switch (phase)
        {
        case 0:
            return true;
        case 1:
            return true;
        case 2:
            return true;
        case 3:
        {
            bool valid = true;
            EClass._map.bounds.ForeachCell(delegate(Cell c)
            {
                if (c.sourceObj.id == 100)
                {
                    valid = false;
                }
            });
            return valid;
        }
        case 4:
            return EClass._zone.IsPCFaction;
        case 5:
            if (EClass.game.quests.IsCompleted("quru_past2") && EClass._zone.IsPCFaction)
            {
                return EClass.Branch.lv >= 2;
            }
            return false;
        case 6:
            return true;
        case 9:
            return EClass._zone.IsPCFaction;
        case 10:
            return true;
        default:
            return false;
        }
    }
References EClass._map, EClass._zone, Map.bounds, MapBounds.ForeachCell(), EClass.game, Spatial.id, QuestManager.IsCompleted(), Zone.IsPCFaction, Quest.phase, Game.quests, and Cell.sourceObj.
GetTextProgress()
override string QuestVernis.GetTextProgress () inline virtual
Reimplemented from Quest.
Definition at line 97 of file QuestVernis.cs.
    {
        if (phase == 3 && EClass._zone is Zone_Vernis && EClass._zone.lv == 0)
        {
            int i = 0;
            EClass._map.bounds.ForeachCell(delegate(Cell c)
            {
                if (c.sourceObj.id == 100)
                {
                    i++;
                }
            });
            return "progressVernis".lang(i.ToString() ?? "");
        }
        return base.GetTextProgress();
    }
References EClass._map, EClass._zone, Map.bounds, MapBounds.ForeachCell(), Spatial.lv, Quest.phase, and Cell.sourceObj.
OnChangePhase()
override void QuestVernis.OnChangePhase (int a) inline virtual
Reimplemented from Quest.
Definition at line 13 of file QuestVernis.cs.
    {
        switch (phase)
        {
        case 1:
            EClass.game.cards.globalCharas.Find("loytel").MoveHome("vernis");
            break;
        case 5:
        {
            Chara chara = EClass.game.cards.globalCharas.Find("quru");
            if (chara != null)
            {
                chara.MoveHome("vernis");
                EClass.Branch.AddMemeber(chara);
                EClass.game.cards.globalCharas.Find("kettle").MoveHome("vernis");
                EClass.Branch.AddMemeber(EClass.game.cards.globalCharas.Find("kettle"));
                EClass.game.cards.globalCharas.Find("farris").MoveHome("vernis");
                EClass.Branch.AddMemeber(EClass.game.cards.globalCharas.Find("farris"));
            }
            EClass.Branch.AddMemeber(EClass.game.cards.globalCharas.Find("loytel"));
            break;
        }
        case 7:
            DropReward(ThingGen.CreatePotion(8506).SetNum(3));
            DropReward(ThingGen.Create("blanket_fire"));
            break;
        }
    }
References FactionBranch.AddMemeber(), EClass.Branch, Game.cards, Quest.chara, ThingGen.Create(), ThingGen.CreatePotion(), Quest.DropReward(), CardManager.GlobalCharaList.Find(), EClass.game, CardManager.globalCharas, Chara.MoveHome(), Quest.phase, and Card.SetNum().
OnComplete()
override void QuestVernis.OnComplete () inline virtual
Reimplemented from Quest.
Definition at line 87 of file QuestVernis.cs.
    {
        Chara chara = CharaGen.Create("corgon");
        chara.SetInt(100, 1);
        EClass._zone.AddCard(chara, EClass.pc.pos.GetNearestPoint());
        EClass.Branch.AddMemeber(chara);
        EClass.game.quests.Add("mokyu", "corgon").startDate = EClass.world.date.GetRaw() + 14400;
        EClass.game.quests.Add("pre_debt", "farris").startDate = EClass.world.date.GetRaw() + 28800;
    }
References EClass._zone, QuestManager.Add(), Zone.AddCard(), FactionBranch.AddMemeber(), EClass.Branch, Quest.chara, CharaGen.Create(), World.date, EClass.game, Point.GetNearestPoint(), Date.GetRaw(), EClass.pc, Card.pos, Game.quests, BaseCard.SetInt(), Quest.startDate, and EClass.world.
OnEnterZone()
override void QuestVernis.OnEnterZone () inline virtual
Reimplemented from Quest.
Definition at line 5 of file QuestVernis.cs.
    {
        if (EClass._zone is Zone_VernisMine zone_VernisMine && phase == 7 && zone_VernisMine.IsBossLv)
        {
            UpdateOnTalk();
        }
    }
References EClass._zone, Quest.phase, and Quest.UpdateOnTalk().
Property Documentation
TitlePrefix
override string QuestVernis.TitlePrefix get
Definition at line 3 of file QuestVernis.cs.
The documentation for this class was generated from the following file:
Elin/QuestVernis.cs