Elin Decompiled Documentation: InputModuleEX Class Reference
InputModuleEX Class Reference
Static Public Member Functions
static void UpdateEventData ()
static PointerEventData GetPointerEventData (int pointerId=-1)
static List< GameObject > GetList ()
static bool IsPointerOverRoot (Component c)
static bool IsPointerOver (Component c)
static bool IsPointerChildOf (Component c)
static T GetComponentOf< T > ()
static T GetTopComponentOf< T > ()
Static Public Attributes
static PointerEventData eventData
static GameObject topGameObject
static List< GameObject > list
static InputModuleEX Instance
Protected Member Functions
override void Awake ()
Detailed Description
Definition at line 5 of file InputModuleEX.cs.
Member Function Documentation
Awake()
override void InputModuleEX.Awake () inline protected
Definition at line 97 of file InputModuleEX.cs.
    {
        base.Awake();
        Instance = this;
        UpdateEventData();
    }
References Instance, and UpdateEventData().
GetComponentOf< T >()
static T InputModuleEX.GetComponentOf< T > () inline static
Type Constraints
T : Component
Definition at line 69 of file InputModuleEX.cs.
                                                : Component
    {
        foreach (GameObject item in list)
        {
            if ((bool)item)
            {
                T component = item.GetComponent<T>();
                if ((bool)component)
                {
                    return component;
                }
            }
        }
        return null;
    }
References item, and list.
GetList()
static List< GameObject > InputModuleEX.GetList () inline static
Definition at line 27 of file InputModuleEX.cs.
    {
        return eventData.hovered;
    }
References eventData.
Referenced by Window.CursorOverCaption().
GetPointerEventData()
static PointerEventData InputModuleEX.GetPointerEventData (int pointerId = -1) inline static
Definition at line 22 of file InputModuleEX.cs.
    {
        return eventData;
    }
References eventData.
Referenced by UI.CheckWindowOrder(), Layer.IsPointerOnLayer(), UI.RefreshActiveState(), and UICharaMaker.RefreshPortraitZoom().
GetTopComponentOf< T >()
static T InputModuleEX.GetTopComponentOf< T > () inline static
Type Constraints
T : Component
Definition at line 85 of file InputModuleEX.cs.
                                                   : Component
    {
        foreach (GameObject item in list)
        {
            if ((bool)item)
            {
                return item.GetComponent<T>();
            }
        }
        return null;
    }
References item, and list.
IsPointerChildOf()
static bool InputModuleEX.IsPointerChildOf (Component c) inline static
Definition at line 57 of file InputModuleEX.cs.
    {
        foreach (GameObject item in list)
        {
            if ((bool)item && item.IsChildOf(c.gameObject))
            {
                return true;
            }
        }
        return false;
    }
References item, and list.
Referenced by Scene.OnUpdate(), and WidgetMemo.Update().
IsPointerOver()
static bool InputModuleEX.IsPointerOver (Component c) inline static
Definition at line 44 of file InputModuleEX.cs.
    {
        Transform transform = c.transform;
        foreach (GameObject item in list)
        {
            if ((bool)item && item.transform == transform)
            {
                return true;
            }
        }
        return false;
    }
References item, and list.
Referenced by WidgetHotbar.CheckAutoHide(), LayerRegisterHotbar.GetButton(), WidgetHotbar.GetSwapButton(), UIContextMenu.Hide(), LayerList.OnKill(), LayerQuickMenu.OnUpdateInput(), UI.ShowMouseHint(), TooltipManager.ShowTooltip(), LayerEditPCC.Update(), LayerTextureViewer.Update(), UIBook.Update(), Window.Update(), WidgetMascot.Update(), WidgetMemo.Update(), and Layer.UpdateInput().
IsPointerOverRoot()
static bool InputModuleEX.IsPointerOverRoot (Component c) inline static
Definition at line 32 of file InputModuleEX.cs.
    {
        foreach (GameObject item in list)
        {
            if ((bool)item && item.IsChildOf(c.gameObject))
            {
                return true;
            }
        }
        return false;
    }
References item, and list.
Referenced by Layer.UpdateInput().
UpdateEventData()
static void InputModuleEX.UpdateEventData () inline static
Definition at line 15 of file InputModuleEX.cs.
    {
        Instance.GetPointerData(-1, out eventData, create: true);
        list = eventData.hovered;
        topGameObject = ((list.Count == 0) ? null : list[list.Count - 1]);
    }
References eventData, Instance, list, and topGameObject.
Referenced by Awake(), UIButton.TryHihlight(), UIButton.TryShowTip< T >(), and Core.Update().
Member Data Documentation
eventData
PointerEventData InputModuleEX.eventData static
Definition at line 7 of file InputModuleEX.cs.
Referenced by GetList(), GetPointerEventData(), and UpdateEventData().
Instance
InputModuleEX InputModuleEX.Instance static
Definition at line 13 of file InputModuleEX.cs.
Referenced by Awake(), and UpdateEventData().
list
List<GameObject> InputModuleEX.list static
Definition at line 11 of file InputModuleEX.cs.
Referenced by GetComponentOf< T >(), GetTopComponentOf< T >(), IsPointerChildOf(), IsPointerOver(), IsPointerOverRoot(), and UpdateEventData().
topGameObject
GameObject InputModuleEX.topGameObject static
Definition at line 9 of file InputModuleEX.cs.
Referenced by UpdateEventData().
The documentation for this class was generated from the following file:
Elin/Plugins.UI/InputModuleEX.cs