Elin Decompiled Documentation: WidgetMinimap Class Reference
WidgetMinimap Class Reference
Classes
class Extra
Public Member Functions
override object CreateExtra ()
override void OnActivate ()
void OnMoveZone ()
void Reload ()
void OnPointerDown (PointerEventData e)
void OnPointerUp (PointerEventData e)
void OnInitializePotentialDrag (PointerEventData ped)
void OnDrag (PointerEventData e)
override void OnSetContextMenu (UIContextMenu m)
void RefreshStyle ()
void OnUpdate ()
void RefreshMarkers ()
void EmitParticle (Card c, ParticleSystem ps, Color col)
Public Member Functions inherited from Widget
void Test ()
bool IsInRightMode ()
void Activate ()
void RefreshOrder ()
virtual void OnActivate ()
virtual object CreateExtra ()
void Deactivate ()
virtual void OnDeactivate ()
void Close ()
void Reactivate ()
virtual void OnManagerActivate ()
virtual void OnManagerDeactivate ()
void SetAnchor (RectPosition p)
void SetPivot (RectPosition p)
virtual void OnChangePivot ()
void UpdateConfig ()
virtual void OnUpdateConfig ()
void ClampToScreen ()
virtual void OnChangeResolution ()
void OnChangePosition ()
virtual void OnChangeActionMode ()
virtual void OnFlip ()
bool IsAlignTop ()
Layer AddLayer (Layer l, Transform trans)
void RefreshTipPivotPosition ()
SkinSet GetSkin ()
SkinConfig GetSkinConfig ()
void SetSkin (int id, int v=0)
void TestSkin ()
virtual void ApplySkin ()
virtual void OnApplySkin ()
void InstantiateDeco (SkinDeco deco)
void AddDeco (SkinDeco deco)
void RemoveDeco (SkinDeco deco)
virtual bool CanShowContextMenu ()
void ShowContextMenu ()
void SetBaseContextMenu (UIContextMenu m)
virtual void OnSetContextMenu (UIContextMenu m)
void SetGridContextMenu (UIContextMenu m)
void SoundActivate ()
void OnChangeResolution ()
SkinSet GetSkin ()
SkinConfig GetSkinConfig ()
Static Public Member Functions
static void UpdateMap (List< Cell > newPoints)
static void UpdateMap (int x, int z)
static void UpdateMap ()
Static Public Member Functions inherited from EMono
static int rnd (int a)
Public Attributes
float interval
float intervalPS
float psSize
RectTransform rectAll
RectTransform rectMap
Vector2 baseSize
UIButton buttonMaptool
UIMapPreview preview
Color colorAlly
Color colorEnemy
Color colorGuest
ParticleSystem psAlly
ParticleSystem psEnemy
Transform transBound
Vector2 posPs
Transform transCam
Public Attributes inherited from Widget
Image imageBG
SoundData soundActivate
UIDragPanel dragPanel
RectTransform tipPivotLeft
RectTransform tipPivotRight
Static Public Attributes
static WidgetMinimap Instance
Static Public Attributes inherited from EMono
static Core core
Properties
override Type SetSiblingAfter [get]
Extra extra [get]
int Size [get]
override bool AlwaysBottom [get]
Properties inherited from Widget
string ID [get]
Config config [get]
SkinRoot skinRoot [get]
bool IsSealed [get]
virtual bool ShowStyleMenu [get]
virtual bool AlwaysTop [get]
virtual bool IsStaticPosition [get]
virtual bool AlwaysBottom [get]
virtual Type SetSiblingAfter [get]
virtual bool ShowInBuildMode [get]
virtual bool RightClickToClose [get]
virtual bool AllowRightClickToClose [get]
Properties inherited from EMono
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SoundManager Sound [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static CoreDebug debug [get]
Private Attributes
Point pos = new Point()
Point point = new Point()
int count
Additional Inherited Members
Public Types inherited from Widget
enum WidgetType { Default , ZoomMenu }
enum State { Active , Inactive }
Protected Member Functions inherited from Widget
void ClampToScreenEnsured (Component c, Vector2 anchoredPos)
void ClampToScreen (RectTransform rect, float margin=10f)
Protected Attributes inherited from Widget
bool flip
Detailed Description
Definition at line 6 of file WidgetMinimap.cs.
Member Function Documentation
CreateExtra()
override object WidgetMinimap.CreateExtra () inline virtual
Reimplemented from Widget.
Definition at line 71 of file WidgetMinimap.cs.
    {
        return new Extra();
    }
EmitParticle()
void WidgetMinimap.EmitParticle (Card c, ParticleSystem ps, Color col) inline
Definition at line 256 of file WidgetMinimap.cs.
    {
        int num = c.pos.x;
        int num2 = c.pos.z;
        float z = (c.IsPCFactionOrMinion ? 9f : (10f + 0.01f * (float)(c.pos.z * 200 + c.pos.x)));
        if (preview.limitBounds)
        {
            num -= EMono._map.bounds.x - preview.offsetX;
            num2 -= EMono._map.bounds.z - preview.offsetZ;
        }
        float x = (float)num / (float)Size - 0.5f;
        float y = (float)num2 / (float)Size - 0.5f;
        count++;
        ParticleSystem.EmitParams emitParams = default(ParticleSystem.EmitParams);
        emitParams.position = new Vector3(x, y, z);
        emitParams.startSize = psSize;
        emitParams.startLifetime = intervalPS;
        emitParams.startColor = col;
        ParticleSystem.EmitParams emitParams2 = emitParams;
        psAlly.Emit(emitParams2, 1);
    }
References count, intervalPS, UIMapPreview.limitBounds, UIMapPreview.offsetX, UIMapPreview.offsetZ, Card.pos, preview, psAlly, psSize, Size, Point.x, and Point.z.
Referenced by RefreshMarkers().
OnActivate()
override void WidgetMinimap.OnActivate () inline virtual
Reimplemented from Widget.
Definition at line 76 of file WidgetMinimap.cs.
    {
        Instance = this;
        preview.limitBounds = extra.limitBounds;
        preview.monoColor = extra.monoColor;
        preview.SetMap(EMono._map);
        InvokeRepeating("RefreshMarkers", 0f, interval);
        RefreshStyle();
        buttonMaptool.SetItem(new HotItemContext
        {
            id = "mapTool"
        });
    }
References EMono._map, buttonMaptool, extra, Instance, interval, WidgetMinimap.Extra.limitBounds, WidgetMinimap.Extra.monoColor, preview, RefreshStyle(), UIButton.SetItem(), and UIMapPreview.SetMap().
OnDrag()
void WidgetMinimap.OnDrag (PointerEventData e) inline
Definition at line 177 of file WidgetMinimap.cs.
    {
    }
OnInitializePotentialDrag()
void WidgetMinimap.OnInitializePotentialDrag (PointerEventData ped) inline
Definition at line 172 of file WidgetMinimap.cs.
    {
        ped.useDragThreshold = false;
    }
OnMoveZone()
void WidgetMinimap.OnMoveZone () inline
Definition at line 115 of file WidgetMinimap.cs.
    {
        preview.SetMap(EMono._map);
        RefreshStyle();
    }
References EMono._map, preview, RefreshStyle(), and UIMapPreview.SetMap().
Referenced by Player.MoveZone().
OnPointerDown()
void WidgetMinimap.OnPointerDown (PointerEventData e) inline
Definition at line 126 of file WidgetMinimap.cs.
    {
        if (!EMono.pc.HasNoGoal || EMono.game.activeZone.IsRegion || EMono.ui.IsActive)
        {
            SE.BeepSmall();
            return;
        }
        Vector2 size = rectMap.rect.size;
        RectTransformUtility.ScreenPointToLocalPointInRectangle(rectMap, e.position, e.pressEventCamera, out var localPoint);
        if (localPoint.x < 0f)
        {
            localPoint.x = 0f;
        }
        else if (localPoint.x >= size.x)
        {
            localPoint.x = size.x;
        }
        if (localPoint.y < 0f)
        {
            localPoint.y = 0f;
        }
        else if (localPoint.y >= size.y)
        {
            localPoint.y = size.y;
        }
        pos.Set((int)((float)Size * localPoint.x / size.x), (int)((float)Size * localPoint.y / size.y));
        pos.Clamp();
        if (preview.limitBounds)
        {
            pos.x += EMono._map.bounds.x - preview.offsetX;
            pos.z += EMono._map.bounds.z - preview.offsetZ;
        }
        if (pos.cell.outOfBounds || !pos.cell.isSeen)
        {
            SE.BeepSmall();
        }
        else
        {
            EMono.pc.SetAIImmediate(new AI_Goto(pos, 0));
        }
    }
References Game.activeZone, Point.cell, Point.Clamp(), EMono.game, Chara.HasNoGoal, Spatial.IsRegion, Cell.isSeen, UIMapPreview.limitBounds, UIMapPreview.offsetX, UIMapPreview.offsetZ, Cell.outOfBounds, EMono.pc, pos, preview, rectMap, Point.Set(), Chara.SetAIImmediate(), Size, and EMono.ui.
OnPointerUp()
void WidgetMinimap.OnPointerUp (PointerEventData e) inline
Definition at line 168 of file WidgetMinimap.cs.
    {
    }
OnSetContextMenu()
override void WidgetMinimap.OnSetContextMenu (UIContextMenu m) inline virtual
Reimplemented from Widget.
Definition at line 181 of file WidgetMinimap.cs.
    {
        UIContextMenu uIContextMenu = m.AddChild("setting");
        uIContextMenu.AddSlider("size", (float a) => extra.scale.ToString() ?? "", extra.scale, delegate(float a)
        {
            extra.scale = (int)a;
            RefreshStyle();
        }, 5f, 20f, isInt: true);
        uIContextMenu.AddSlider("width", (float a) => 100 + extra.width + "%", extra.width, delegate(float a)
        {
            extra.width = (int)a;
            RefreshStyle();
        }, -25f, 25f, isInt: true);
        uIContextMenu.AddSlider("alpha", (float a) => extra.alpha.ToString() ?? "", extra.alpha, delegate(float a)
        {
            extra.alpha = (int)a;
            RefreshStyle();
        }, 0f, 255f, isInt: true);
        uIContextMenu.AddToggle("rotation", extra.rotate, delegate(bool a)
        {
            extra.rotate = a;
            RefreshStyle();
        });
        uIContextMenu.AddToggle("monoColor", extra.monoColor, delegate(bool a)
        {
            extra.monoColor = (preview.monoColor = a);
            preview.SetMap(EMono._map);
            RefreshStyle();
        });
        SetBaseContextMenu(m);
    }
References EMono._map, UIContextMenu.AddChild(), UIContextMenu.AddSlider(), UIContextMenu.AddToggle(), WidgetMinimap.Extra.alpha, extra, WidgetMinimap.Extra.monoColor, preview, RefreshStyle(), WidgetMinimap.Extra.rotate, WidgetMinimap.Extra.scale, Widget.SetBaseContextMenu(), UIMapPreview.SetMap(), and WidgetMinimap.Extra.width.
OnUpdate()
void WidgetMinimap.OnUpdate () inline
Definition at line 220 of file WidgetMinimap.cs.
    {
        point.Set(EMono.screen.position);
        if (preview.limitBounds)
        {
            point.x -= EMono._map.bounds.x - preview.offsetX;
            point.z -= EMono._map.bounds.z - preview.offsetZ;
        }
        float x = (float)(point.x / Size) - 0.5f;
        float y = (float)(point.z / Size) - 0.5f;
        transBound.localScale = new Vector3(Mathf.Min((float)EMono.screen.width / (float)Size * 1.5f, 1f), Mathf.Min((float)EMono.screen.height / (float)Size / 2f, 1f), 1f);
        transBound.localPosition = new Vector3(x, y, 50f);
        transCam.localScale = new Vector3(1f / EMono.core.uiScale, 1f / EMono.core.uiScale, 1f);
    }
References EMono.core, BaseGameScreen.height, UIMapPreview.limitBounds, UIMapPreview.offsetX, UIMapPreview.offsetZ, point, BaseGameScreen.position, preview, EMono.screen, Point.Set(), Size, Core.uiScale, BaseGameScreen.width, Point.x, and Point.z.
Referenced by BaseGameScreen.RefreshPosition(), and GameScreenElona.RefreshPosition().
RefreshMarkers()
void WidgetMinimap.RefreshMarkers () inline
Definition at line 235 of file WidgetMinimap.cs.
    {
        if (!base.gameObject.activeInHierarchy)
        {
            return;
        }
        psAlly.Clear();
        EmitParticle(EMono.pc, psAlly, colorAlly);
        if (!EMono._zone.ShowEnemyOnMinimap)
        {
            return;
        }
        foreach (Chara chara in EMono._map.charas)
        {
            if (chara.IsHostile())
            {
                EmitParticle(chara, psEnemy, colorEnemy);
            }
        }
    }
References EMono._map, EMono._zone, Map.charas, colorAlly, colorEnemy, EmitParticle(), Chara.IsHostile(), EMono.pc, psAlly, psEnemy, and Zone.ShowEnemyOnMinimap.
RefreshStyle()
void WidgetMinimap.RefreshStyle () inline
Definition at line 213 of file WidgetMinimap.cs.
    {
        rectAll.localEulerAngles = ((extra.rotate && !EMono._zone.IsRegion) ? new Vector3(60f, 0f, -45f) : Vector3.zero);
        preview.matMap.SetColor("_Color", new Color(1f, 1f, 1f, (float)extra.alpha / 255f));
        this.Rect().sizeDelta = new Vector2(0.1f * baseSize.x * (float)(10 + extra.scale) * (float)(100 + extra.width) * 0.01f, 0.1f * baseSize.y * (float)(10 + extra.scale));
    }
References EMono._zone, baseSize, Color, extra, Spatial.IsRegion, UIMapPreview.matMap, preview, WidgetMinimap.Extra.scale, and WidgetMinimap.Extra.width.
Referenced by OnActivate(), OnMoveZone(), and OnSetContextMenu().
Reload()
void WidgetMinimap.Reload () inline
Definition at line 121 of file WidgetMinimap.cs.
    {
        preview.SetMap(preview.map);
    }
References UIMapPreview.map, preview, and UIMapPreview.SetMap().
UpdateMap() [1/3]
static void WidgetMinimap.UpdateMap () inline static
Definition at line 107 of file WidgetMinimap.cs.
    {
        if ((bool)Instance && Instance.preview.map.zone.IsActiveZone)
        {
            Instance.preview.SetMap(EMono._map);
        }
    }
References EMono._map, Instance, Zone.IsActiveZone, UIMapPreview.map, preview, UIMapPreview.SetMap(), and Map.zone.
UpdateMap() [2/3]
static void WidgetMinimap.UpdateMap (int x, int z) inline static
Definition at line 99 of file WidgetMinimap.cs.
    {
        if ((bool)Instance && Instance.preview.map.zone.IsActiveZone)
        {
            Instance.preview.UpdateMap(x, z);
        }
    }
References Instance, Zone.IsActiveZone, UIMapPreview.map, preview, UIMapPreview.UpdateMap(), and Map.zone.
UpdateMap() [3/3]
static void WidgetMinimap.UpdateMap (List< Cell > newPoints) inline static
Definition at line 90 of file WidgetMinimap.cs.
    {
        if ((bool)Instance && Instance.preview.map.zone.IsActiveZone)
        {
            Instance.preview.UpdateMap(newPoints);
        }
        newPoints.Clear();
    }
References Instance, Zone.IsActiveZone, UIMapPreview.map, preview, UIMapPreview.UpdateMap(), and Map.zone.
Referenced by Fov.Perform(), Map.RevealAll(), and Map.SetSeen().
Member Data Documentation
baseSize
Vector2 WidgetMinimap.baseSize
Definition at line 35 of file WidgetMinimap.cs.
Referenced by RefreshStyle().
buttonMaptool
UIButton WidgetMinimap.buttonMaptool
Definition at line 39 of file WidgetMinimap.cs.
Referenced by OnActivate().
colorAlly
Color WidgetMinimap.colorAlly
Definition at line 43 of file WidgetMinimap.cs.
Referenced by RefreshMarkers().
colorEnemy
Color WidgetMinimap.colorEnemy
Definition at line 45 of file WidgetMinimap.cs.
Referenced by RefreshMarkers().
colorGuest
Color WidgetMinimap.colorGuest
Definition at line 47 of file WidgetMinimap.cs.
count
int WidgetMinimap.count private
Definition at line 61 of file WidgetMinimap.cs.
Referenced by EmitParticle().
Instance
WidgetMinimap WidgetMinimap.Instance static
Definition at line 23 of file WidgetMinimap.cs.
Referenced by Player.MoveZone(), OnActivate(), Core.OnApplicationFocus(), BaseGameScreen.RefreshPosition(), GameScreenElona.RefreshPosition(), and UpdateMap().
interval
float WidgetMinimap.interval
Definition at line 25 of file WidgetMinimap.cs.
Referenced by OnActivate().
intervalPS
float WidgetMinimap.intervalPS
Definition at line 27 of file WidgetMinimap.cs.
Referenced by EmitParticle().
point
Point WidgetMinimap.point = new Point() private
Definition at line 59 of file WidgetMinimap.cs.
Referenced by OnUpdate().
pos
Point WidgetMinimap.pos = new Point() private
Definition at line 37 of file WidgetMinimap.cs.
Referenced by OnPointerDown().
posPs
Vector2 WidgetMinimap.posPs
Definition at line 55 of file WidgetMinimap.cs.
preview
UIMapPreview WidgetMinimap.preview
Definition at line 41 of file WidgetMinimap.cs.
Referenced by EmitParticle(), OnActivate(), OnMoveZone(), OnPointerDown(), OnSetContextMenu(), OnUpdate(), RefreshStyle(), Reload(), and UpdateMap().
psAlly
ParticleSystem WidgetMinimap.psAlly
Definition at line 49 of file WidgetMinimap.cs.
Referenced by EmitParticle(), and RefreshMarkers().
psEnemy
ParticleSystem WidgetMinimap.psEnemy
Definition at line 51 of file WidgetMinimap.cs.
Referenced by RefreshMarkers().
psSize
float WidgetMinimap.psSize
Definition at line 29 of file WidgetMinimap.cs.
Referenced by EmitParticle().
rectAll
RectTransform WidgetMinimap.rectAll
Definition at line 31 of file WidgetMinimap.cs.
rectMap
RectTransform WidgetMinimap.rectMap
Definition at line 33 of file WidgetMinimap.cs.
Referenced by OnPointerDown().
transBound
Transform WidgetMinimap.transBound
Definition at line 53 of file WidgetMinimap.cs.
transCam
Transform WidgetMinimap.transCam
Definition at line 57 of file WidgetMinimap.cs.
Property Documentation
AlwaysBottom
override bool WidgetMinimap.AlwaysBottom get
Definition at line 69 of file WidgetMinimap.cs.
extra
Extra WidgetMinimap.extra get
Definition at line 65 of file WidgetMinimap.cs.
Referenced by OnActivate(), OnSetContextMenu(), and RefreshStyle().
SetSiblingAfter
override Type WidgetMinimap.SetSiblingAfter get
Definition at line 63 of file WidgetMinimap.cs.
Size
int WidgetMinimap.Size get
Definition at line 67 of file WidgetMinimap.cs.
Referenced by EmitParticle(), OnPointerDown(), and OnUpdate().
The documentation for this class was generated from the following file:
Elin/WidgetMinimap.cs