Elin Decompiled Documentation: LayerDrama Class Reference
LayerDrama Class Reference
Public Member Functions
override void OnInit ()
override void OnUpdateInput ()
override void OnKill ()
Public Member Functions inherited from ELayer
override void OnBeforeAddLayer ()
void InitInspector ()
sealed override void Init ()
override void OnAfterAddLayer ()
void TryShowHelp ()
void AddLayerToUI (string id)
void TryShowHint (string _langHint=null)
void TalkHomeMemeber (string id)
void TalkMaid (string id)
override void OnRightClick ()
Public Member Functions inherited from Layer
virtual string GetTextHeader (Window window)
virtual bool HeaderIsListOf (int id)
virtual void Init ()
virtual void OnInit ()
virtual void OnAfterInit ()
virtual void ApplySkin ()
void ShowScreenLock (string id)
void UpdateInput ()
virtual void OnUpdateInput ()
virtual void OnRightClick ()
virtual bool OnBack ()
virtual void OnChangeLayer ()
virtual void OnCreate ()
void _AddLayer (string id)
Layer AddLayer (string id)
T AddLayer< T > ()
T AddLayer< T > (string id)
T AddLayerDontCloseOthers< T > ()
Layer AddLayerDontCloseOthers (Layer l)
T GetOrAddLayer< T > ()
virtual void OnBeforeAddLayer ()
virtual void OnAfterAddLayer ()
Layer AddLayer (Layer l)
void ToggleLayer (string id)
T ToggleLayer< T > (string id=null)
void WaitAndClose ()
void OnClickClose ()
virtual void Close ()
void CloseLayers ()
void RemoveLayers (bool removeImportant=false)
bool RemoveLayer< T > ()
void RemoveLayer (Layer l)
virtual void OnKill ()
Layer SetOnKill (Action action)
void DisableClose ()
void Delay (float duration=0.05f)
Layer SetDelay (float d)
Layer GetLayer (string id)
T GetLayer< T > (bool fromTop=false)
Layer GetTopLayer ()
void SwitchContent (int idWindow, int i)
virtual void OnSwitchContent (Window window)
Layer SetTitles (string langList, string idHeaderRow=null)
bool IsBlockWidgetClick ()
bool IsHideHud ()
bool IsAllowGeneralInput ()
bool IsUseBlur ()
bool IsPointerOnLayer ()
void ApplySkin ()
Static Public Member Functions
static bool IsActive ()
static LayerDrama ActivateMain (string idSheet, string idStep=null, Chara target=null, Card ref1=null, string tag="")
static LayerDrama Activate (string book, string idSheet, string idStep, Chara target=null, Card ref1=null, string tag="")
static LayerDrama ActivateNerun (string idText)
Static Public Member Functions inherited from ELayer
static int rnd (int a)
Static Public Member Functions inherited from Layer
static T Create< T > ()
static T Create< T > (string path)
static Layer Create (string path)
Public Attributes
DramaManager drama
CanvasGroup cg
DramaSetup setup
Public Attributes inherited from Layer
Option option
UnityEvent onKill
Anime animeIn
Anime animeOut
bool closeOthers
bool defaultActionMode = true
Button screenLock
Layer parent
string idLayer
List< Layer > layers = new List<Layer>()
Vector2 lastParentPos
List< Window > windows = new List<Window>()
string langHint
Static Public Attributes
static Quest currentQuest
static Religion currentReligion
static bool keepBGM
static bool haltPlaylist
static bool maxBGMVolume
static bool fromBook
static string forceJump
static LayerDrama Instance
static Card alwaysVisible
static Action refAction1
static Action refAction2
Static Public Attributes inherited from Layer
static int skipInput
static bool closeOnRightClick
static bool rightClicked
static bool cancelKeyDown
static bool ignoreSounds
static Transform blurStopInstance
static string[] searchPath = new string[3] { "Layer", "Layer/Dialog", "Layer/LayerHome" }
Private Member Functions
void LateUpdate ()
Additional Inherited Members
Protected Member Functions inherited from ELayer
sealed override void _Close ()
sealed override void Kill ()
Protected Member Functions inherited from Layer
virtual void Awake ()
virtual void _Close ()
virtual void Kill ()
Protected Attributes inherited from Layer
RectTransform _rect
bool isDestroyed
Properties inherited from ELayer
static Core core [get]
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static FactionBranch Branch [get]
static Faction Home [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static CoreConfig config [get]
static GameSetting setting [get]
static ColorProfile Colors [get]
static SourceManager sources [get]
static World world [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
bool IsFloat [get]
virtual string IdHelp [get]
Properties inherited from Layer
Layer TopLayer [get]
string uid [get]
virtual RectTransform rectLayers [get]
virtual bool blockWidgetClick [get]
Detailed Description
Definition at line 4 of file LayerDrama.cs.
Member Function Documentation
Activate()
static LayerDrama LayerDrama.Activate (string book, string idSheet, string idStep, Chara target = null, Card ref1 = null, string tag = "") inline static
Definition at line 66 of file LayerDrama.cs.
    {
        LayerDrama layerDrama = Layer.Create<LayerDrama>();
        layerDrama.setup = new DramaSetup
        {
            book = book,
            sheet = idSheet,
            step = idStep,
            ref1 = ref1,
            forceJump = forceJump,
            tag = tag
        };
        forceJump = null;
        if (target != null)
        {
            layerDrama.setup.person = new Person(target);
        }
        ELayer.ui.AddLayer(layerDrama);
        layerDrama.drama.Play(layerDrama.setup);
        return layerDrama;
    }
References book, Layer.Create(), drama, forceJump, DramaManager.Play(), setup, and ELayer.ui.
Referenced by Chara._ShowDialog(), ActivateMain(), MeetingManager.CallNext(), TraitStoryBookHome.OnRead(), TraitDaggerGrave.OnUse(), Player.Flags.PlayStory(), Chara.TryDropBossLoot(), and TraitAltar.TrySetAct().
ActivateMain()
static LayerDrama LayerDrama.ActivateMain (string idSheet, string idStep = null, Chara target = null, Card ref1 = null, string tag = "") inline static
Definition at line 61 of file LayerDrama.cs.
    {
        return Activate("_main", idSheet, idStep, target, ref1, tag);
    }
References Activate().
Referenced by CoreDebug.COM_PlayStartDrama(), Zone_Nymelle.OnBeforeSimulate(), StickyMenu.OnClick(), MeetingFarris.PlayDrama(), Chara.ShowDialog(), and LayerWorldSetting.StartGame().
ActivateNerun()
static LayerDrama LayerDrama.ActivateNerun (string idText) inline static
Definition at line 88 of file LayerDrama.cs.
    {
        if (ELayer.debug.skipNerun)
        {
            return null;
        }
        LayerDrama layerDrama = Layer.Create<LayerDrama>();
        layerDrama.setup = new DramaSetup
        {
            book = "_nerun",
            step = "6-1"
        };
        TextAsset textAsset = Resources.Load<TextAsset>(CorePath.Text_DialogHelp + idText);
        layerDrama.setup.textData = GameLang.Convert(textAsset?.text ?? (idText + " not found."));
        layerDrama.option.hideOthers = false;
        layerDrama.option.screenlockType = Option.ScreenlockType.DarkLight;
        ELayer.ui.AddLayer(layerDrama);
        layerDrama.drama.Play(layerDrama.setup);
        return layerDrama;
    }
References book, GameLang.Convert(), Layer.Create(), ELayer.debug, drama, DramaManager.Play(), setup, CoreDebug.skipNerun, and ELayer.ui.
Referenced by StickyTutorial.OnClick(), and ELayer.TryShowHelp().
IsActive()
static bool LayerDrama.IsActive () inline static
Definition at line 34 of file LayerDrama.cs.
    {
        return ELayer.ui.GetLayer<LayerDrama>();
    }
References ELayer.ui.
Referenced by Scene.OnUpdate().
LateUpdate()
void LayerDrama.LateUpdate () inline private
Definition at line 45 of file LayerDrama.cs.
    {
        if (drama.sequence.isExited && ELayer.ui.GetTopLayer() == this)
        {
            Close();
        }
        if (ELayer.ui.TopLayer == this && !isDestroyed)
        {
            ELayer.ui.hud.hint.cg.alpha = 0f;
        }
        else
        {
            ELayer.ui.hud.hint.cg.alpha = 1f;
        }
    }
References Layer.Close(), drama, Layer.isDestroyed, DramaSequence.isExited, DramaManager.sequence, and ELayer.ui.
OnInit()
override void LayerDrama.OnInit () inline virtual
Reimplemented from Layer.
Definition at line 39 of file LayerDrama.cs.
    {
        Instance = this;
        maxBGMVolume = false;
    }
References Instance, and maxBGMVolume.
OnKill()
override void LayerDrama.OnKill () inline virtual
Reimplemented from Layer.
Definition at line 114 of file LayerDrama.cs.
    {
        ELayer.ui.Show();
        keepBGM = false;
        haltPlaylist = false;
        fromBook = false;
        SoundManager.current.haltUpdate = false;
        SoundManager.forceBGM = false;
        ELayer.ui.hud.hint.cg.alpha = 1f;
        ELayer.scene.screenElin.focusOption = null;
        alwaysVisible = null;
        EInput.requireConfirmReset = true;
        maxBGMVolume = false;
    }
References alwaysVisible, fromBook, haltPlaylist, keepBGM, maxBGMVolume, and ELayer.ui.
OnUpdateInput()
override void LayerDrama.OnUpdateInput () inline virtual
Reimplemented from Layer.
Definition at line 109 of file LayerDrama.cs.
    {
        base.OnUpdateInput();
    }
Member Data Documentation
alwaysVisible
Card LayerDrama.alwaysVisible static
Definition at line 22 of file LayerDrama.cs.
Referenced by BaseTileMap.DrawTile(), and OnKill().
cg
CanvasGroup LayerDrama.cg
Definition at line 30 of file LayerDrama.cs.
currentQuest
Quest LayerDrama.currentQuest static
Definition at line 6 of file LayerDrama.cs.
Referenced by DramaManager.ParseLine().
currentReligion
Religion LayerDrama.currentReligion static
Definition at line 8 of file LayerDrama.cs.
Referenced by DramaActor.ConvertAdv(), and DramaManager.ParseLine().
drama
DramaManager LayerDrama.drama
Definition at line 28 of file LayerDrama.cs.
Referenced by Activate(), ActivateNerun(), and LateUpdate().
forceJump
string LayerDrama.forceJump static
Definition at line 18 of file LayerDrama.cs.
Referenced by Activate(), and Chara.ShowDialog().
fromBook
bool LayerDrama.fromBook static
Definition at line 16 of file LayerDrama.cs.
Referenced by OnKill(), and DramaManager.ParseLine().
haltPlaylist
bool LayerDrama.haltPlaylist static
Definition at line 12 of file LayerDrama.cs.
Referenced by Core.Awake(), and OnKill().
Instance
LayerDrama LayerDrama.Instance static
Definition at line 20 of file LayerDrama.cs.
Referenced by OnInit(), DramaManager.ParseLine(), Tutorial.Play(), WidgetQuestTracker.Refresh(), Meeting.Start(), LayerWorldSetting.StartGame(), Tutorial.TryPlayReserve(), and ActionMode.UpdateInput().
keepBGM
bool LayerDrama.keepBGM static
Definition at line 10 of file LayerDrama.cs.
Referenced by Core.Awake(), OnKill(), and Zone.RefreshBGM().
maxBGMVolume
bool LayerDrama.maxBGMVolume static
Definition at line 14 of file LayerDrama.cs.
Referenced by OnInit(), and OnKill().
refAction1
Action LayerDrama.refAction1 static
Definition at line 24 of file LayerDrama.cs.
Referenced by DramaManager.ParseLine().
refAction2
Action LayerDrama.refAction2 static
Definition at line 26 of file LayerDrama.cs.
Referenced by DramaManager.ParseLine().
setup
DramaSetup LayerDrama.setup
Definition at line 32 of file LayerDrama.cs.
Referenced by Activate(), and ActivateNerun().
The documentation for this class was generated from the following file:
Elin/LayerDrama.cs