Elin Decompiled Documentation: GameScreenElona Class Reference
GameScreenElona Class Reference
Public Member Functions
override void OnActivate ()
override void OnDeactivate ()
override void OnChangeHour ()
override void SetUnitSize ()
override void RefreshPosition ()
override void RefreshWeather ()
Public Member Functions inherited from BaseGameScreen
void Activate ()
virtual void OnActivate ()
void Deactivate ()
virtual void OnDeactivate ()
virtual void SetUnitSize ()
virtual void OnEndPlayerTurn ()
void Draw ()
void UpdateShaders (float time=0f)
virtual void OnChangeHour ()
virtual void RefreshPosition ()
void RefreshAll ()
void RefreshScreenSize ()
Point GetRandomPoint ()
void RefreshSky ()
virtual void RefreshWeather ()
void RefreshGrading ()
void RefreshTilt ()
void ScrollMouse (float x, float y)
void ScrollAxis (Vector3 axis, bool direct=false)
void Focus (Int3 ints)
void Focus (int x, int y)
void Focus (Card c)
void FocusCenter ()
void Focus (Point pos)
void FocusPC ()
void FocusImmediate (Point pos)
void SnapScreen (ref Vector3 v, float zoom)
void SetZoom (float z)
void SetTargetZoomIndex (int index)
void ModTargetZoomIndex (int a)
Public Attributes
EloMapActor actor
float skyRate
float zoom
Vector3 actorPos
Public Attributes inherited from BaseGameScreen
float SharpenAmount
float camSpeed2
float heightLight
float pushbackSpeed
Vector2 snapSize
Vector2 tileSize
Vector2 tileAlign
Vector2 tileWorldSize
Vector2 tileViewSize
Vector3 tileWeight
Vector3 focusFix
Vector3 tileOffsetHeight
Vector3 tileWeightHeight
Vector3 planeAngle
Vector3 planeSpeed
Vector2 paddings
Vector2 paddingOffset
Vector3 lastPos
Rect mapLimit
float Zoom
float nextMove
float focusSpeed
float focusSpeedSlow
float focusSpeedSlow2
int width
int height
int scrollX
int scrollY
int moonLevel
BaseTileMap tileMap
BaseTileSelector tileSelector
ScreenGuide guide
Grid grid
MeshRenderer overlayShadow
PCOrbit pcOrbit
float forcePrecision
bool isCameraMoving
FocusOption focusOption
Vector3? focusPos
Vector3 position
float screenFixX
float screenFixX2
float screenFixX3
float screenFixX4
float screenFixY
float screenFixY2
float screenFixY3
float screenFixY4
bool instantFocus
int targetZoomIndex
float targetZoom = 0.5f
float zoomTimer
Vector3 zoomPos
Properties
override float SkyRate [get]
override float TargetZoom [get]
Properties inherited from BaseGameScreen
bool fixFocus [get]
virtual float TargetZoom [get]
CameraSupport camSupport [get]
Transform transFocus [get]
virtual float SkyRate [get]
virtual float ViewHeight [get]
virtual bool IsGameScreen [get]
virtual bool IsLocalMap [get]
Properties inherited from EMono
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SoundManager Sound [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static CoreDebug debug [get]
Additional Inherited Members
Static Public Member Functions inherited from EMono
static int rnd (int a)
Static Public Attributes inherited from EMono
static Core core
Protected Attributes inherited from BaseGameScreen
Vector3 camPos
Vector3 pushBack
Detailed Description
Definition at line 4 of file GameScreenElona.cs.
Member Function Documentation
OnActivate()
override void GameScreenElona.OnActivate () inline virtual
Reimplemented from BaseGameScreen.
Definition at line 18 of file GameScreenElona.cs.
    {
        actor.transMap.SetActive(enable: true);
        actor.selector.hasTargetChanged = true;
        EMono.scene.skyBG.SetActive(enable: false);
        EMono.scene.cam.clearFlags = CameraClearFlags.Color;
        Tutorial.Play("region");
        actor.OnActivate();
    }
References actor, EloMapActor.OnActivate(), Tutorial.Play(), EMono.scene, Scene.skyBG, and EloMapActor.transMap.
OnChangeHour()
override void GameScreenElona.OnChangeHour () inline virtual
Reimplemented from BaseGameScreen.
Definition at line 33 of file GameScreenElona.cs.
    {
        actor.OnChangeHour();
    }
References actor, and EloMapActor.OnChangeHour().
OnDeactivate()
override void GameScreenElona.OnDeactivate () inline virtual
Reimplemented from BaseGameScreen.
Definition at line 28 of file GameScreenElona.cs.
    {
        actor.OnDeactivate();
    }
References actor, and EloMapActor.OnDeactivate().
RefreshPosition()
override void GameScreenElona.RefreshPosition () inline virtual
Reimplemented from BaseGameScreen.
Definition at line 49 of file GameScreenElona.cs.
    {
        STETilemap fogmap = actor.elomap.fogmap;
        actor.transMap.position = new Vector3((float)(-fogmap.MinGridX) * tileAlign.x + actorPos.x, (float)(-fogmap.MinGridY) * tileAlign.y + actorPos.y, actorPos.z);
        if (base.fixFocus && EMono.pc.currentZone == EMono._zone)
        {
            float z = position.z;
            targetZoom = TargetZoom;
            Vector3 b = (EMono.pc.isSynced ? EMono.pc.renderer.position : EMono.pc.pos.PositionTopdown()) + focusFix;
            if (instantFocus)
            {
                position = b;
            }
            else
            {
                position = Vector3.Lerp(position, b, focusSpeed * Core.delta);
            }
            position.z = z;
            pcOrbit.transform.position = EMono.pc.renderer.position;
        }
        else
        {
            if (ActionMode.Adv.IsActive)
            {
                targetZoom = 0.01f * (float)EMono.game.config.defaultZoom;
            }
            pushBack = Vector3.zero;
            int num = scrollX;
            int num2 = scrollY;
            if ((float)num <= mapLimit.x)
            {
                pushBack.x = mapLimit.x - (float)num;
            }
            if ((float)num2 <= mapLimit.y)
            {
                pushBack.y = mapLimit.y - (float)num2;
            }
            if ((float)num >= (float)EMono._map.Size + mapLimit.width - (float)(width / 2))
            {
                pushBack.x = (float)EMono._map.Size + mapLimit.width - (float)(width / 2) - (float)num;
            }
            if ((float)num2 >= (float)EMono._map.Size + mapLimit.height - (float)(height / 2))
            {
                pushBack.y = (float)EMono._map.Size + mapLimit.height - (float)(height / 2) - (float)num2;
            }
            position += pushBack * Core.delta * pushbackSpeed;
        }
        scrollX = Mathf.FloorToInt(position.x / tileWorldSize.x) - width / 2 + (int)paddingOffset.x;
        scrollY = Mathf.FloorToInt(position.y / tileWorldSize.y) - height / 4 + (int)paddingOffset.y;
        if (lastPos.x != (float)scrollX || lastPos.y != (float)scrollY)
        {
            lastPos.x = scrollX;
            lastPos.y = scrollY;
        }
        camPos.x = position.x;
        camPos.y = position.y;
        SnapScreen(ref camPos, Zoom);
        camPos.z = -500f;
        EMono.scene.cam.transform.localPosition = camPos;
        camPos.z = 0f;
        EMono.scene.transAudio.position = camPos + EMono.scene.posAudioListener;
        if ((bool)WidgetMinimap.Instance)
        {
            WidgetMinimap.Instance.OnUpdate();
        }
        RefreshWeather();
    }
References EMono._map, EMono._zone, actor, actorPos, ActionMode.Adv, BaseGameScreen.camPos, Game.config, Chara.currentZone, Game.Config.defaultZoom, Core.delta, EloMapActor.elomap, BaseGameScreen.focusFix, BaseGameScreen.focusSpeed, EloMap.fogmap, EMono.game, BaseGameScreen.height, if(), WidgetMinimap.Instance, BaseGameScreen.instantFocus, ActionMode.IsActive, BaseGameScreen.lastPos, BaseGameScreen.mapLimit, WidgetMinimap.OnUpdate(), BaseGameScreen.paddingOffset, EMono.pc, Card.pos, Scene.posAudioListener, BaseGameScreen.position, CardRenderer.position, Point.PositionTopdown(), BaseGameScreen.pushBack, BaseGameScreen.pushbackSpeed, RefreshWeather(), Card.renderer, EMono.scene, BaseGameScreen.scrollX, BaseGameScreen.scrollY, MapBounds.Size, BaseGameScreen.SnapScreen(), BaseGameScreen.targetZoom, TargetZoom, BaseGameScreen.tileAlign, BaseGameScreen.tileWorldSize, BaseGameScreen.width, and BaseGameScreen.Zoom.
RefreshWeather()
override void GameScreenElona.RefreshWeather () inline virtual
Reimplemented from BaseGameScreen.
Definition at line 117 of file GameScreenElona.cs.
    {
        EMono.world.weather.RefreshWeather();
        Point pos = EMono.pc.pos;
        Weather weather = EMono.world.weather;
        Weather.Condition currentCondition = weather.CurrentCondition;
        bool isRaining = weather.IsRaining;
        bool isEther = weather.IsEther;
        bool flag = currentCondition == Weather.Condition.Snow;
        EMono.scene.filterRain.enabled = isRaining && !flag && EMono.core.config.graphic.enhanceRain;
        EMono.scene.filterRain.Fade = ((currentCondition == Weather.Condition.RainHeavy) ? 0.4f : 0.3f);
        EMono.scene.rain.enableEmission = isRaining && !flag;
        ParticleSystem.EmissionModule emission = EMono.scene.rain.emission;
        emission.rateOverTime = ((currentCondition == Weather.Condition.RainHeavy) ? 700 : 200);
        EMono.scene.snow.enableEmission = flag;
        emission = EMono.scene.snow.emission;
        emission.rateOverTime = ((currentCondition == Weather.Condition.SnowHeavy) ? 120 : 35);
        EMono.scene.ether.enableEmission = isEther;
        EMono.scene.snow.SetActive(enable: true);
        EMono.scene.rain.SetActive(enable: true);
        EMono.scene.ether.SetActive(enable: true);
        EMono.scene.blossom.SetActive(enable: false);
        EMono.scene.godray.SetActive(enable: false);
        EMono.scene.godrayDust.SetActive(enable: false);
        EMono.scene.sfxRain._Volume += Core.delta * ((isRaining && !flag) ? 0.5f : (-0.5f));
        EMono.scene.sfxRain.SetVolume(EMono.scene.sfxRain._Volume);
        EMono.scene.sfxWind.SetVolume(1f);
        EMono.scene.sfxSea.SetVolume(Mathf.Lerp(0f, 1f, -0.05f * (float)(pos.x - 20)));
        ParticleSystem.MainModule main = EMono.scene.rain.main;
        ParticleSystem.MainModule main2 = EMono.scene.snow.main;
        ParticleSystem.MainModule main3 = EMono.scene.ether.main;
        bool flag3 = (main3.prewarm = false);
        bool prewarm = (main2.prewarm = flag3);
        main.prewarm = prewarm;
        ParticleSystem[] blossoms = EMono.scene.blossoms;
        for (int i = 0; i < blossoms.Length; i++)
        {
            ParticleSystem.MainModule main4 = blossoms[i].main;
            main4.prewarm = false;
        }
        bool enableEmission = currentCondition == Weather.Condition.SnowHeavy && EMono.core.config.graphic.blizzard;
        blossoms = EMono.scene.blizzards;
        for (int i = 0; i < blossoms.Length; i++)
        {
            blossoms[i].enableEmission = enableEmission;
        }
        EMono.scene.transBlizzard.localScale = new Vector3(2f, 2f, 2f);
        EMono.scene.camSupport.grading.profile.fog = EMono.setting.render.fogs[EMono._map.config.fog];
        float sceneBrightness = ((EMono._map.IsIndoor || !EMono.world.weather.IsRaining) ? 0f : ((currentCondition == Weather.Condition.RainHeavy) ? (-0.06f) : (-0.03f)));
        base.camSupport.grading.sceneBrightness = sceneBrightness;
    }
References EMono._map, CoreConfig.GraphicSetting.blizzard, Scene.blizzards, Scene.blossom, Scene.blossoms, Core.config, Map.config, EMono.core, Weather.CurrentCondition, CoreConfig.GraphicSetting.enhanceRain, Scene.ether, MapConfig.fog, GameSetting.RenderSetting.fogs, Scene.godray, Scene.godrayDust, CoreConfig.graphic, Weather.IsEther, Weather.IsRaining, EMono.pc, Card.pos, Scene.rain, Weather.RefreshWeather(), GameSetting.render, EMono.scene, EMono.setting, Scene.sfxRain, Scene.sfxSea, Scene.sfxWind, Scene.snow, World.weather, and EMono.world.
Referenced by RefreshPosition().
SetUnitSize()
override void GameScreenElona.SetUnitSize () inline virtual
Reimplemented from BaseGameScreen.
Definition at line 38 of file GameScreenElona.cs.
    {
        tileAlign = new Vector2(tileSize.x * 0.01f, tileSize.y * 0.01f);
        tileWorldSize = new Vector2(tileSize.x * 0.01f, tileSize.y * 0.01f);
        float x = tileSize.x;
        float num = 100f / x;
        float num2 = num * 100f;
        float num3 = num * 100f;
        tileViewSize = new Vector2(num2 * 0.01f, num3 * 0.01f);
    }
References BaseGameScreen.tileAlign, BaseGameScreen.tileSize, BaseGameScreen.tileViewSize, and BaseGameScreen.tileWorldSize.
Referenced by EloMapActor.Initialize().
Member Data Documentation
actor
EloMapActor GameScreenElona.actor
Definition at line 6 of file GameScreenElona.cs.
Referenced by OnActivate(), OnChangeHour(), OnDeactivate(), and RefreshPosition().
actorPos
Vector3 GameScreenElona.actorPos
Definition at line 12 of file GameScreenElona.cs.
Referenced by EloMapActor.Initialize(), and RefreshPosition().
skyRate
float GameScreenElona.skyRate
Definition at line 8 of file GameScreenElona.cs.
zoom
float GameScreenElona.zoom
Definition at line 10 of file GameScreenElona.cs.
Referenced by LayerTravel.OnInit().
Property Documentation
SkyRate
override float GameScreenElona.SkyRate get
Definition at line 14 of file GameScreenElona.cs.
TargetZoom
override float GameScreenElona.TargetZoom get
Definition at line 16 of file GameScreenElona.cs.
Referenced by RefreshPosition().
The documentation for this class was generated from the following file:
Elin/GameScreenElona.cs