Elin Decompiled Documentation: CardBlueprint Class Reference
CardBlueprint Class Reference
Static Public Member Functions
static CardBlueprint Chara (int lv, Rarity rarity=Rarity.Normal)
static void Set (CardBlueprint _bp=null)
static void SetNormalRarity (bool fixedMat=false)
static void SetRarity (Rarity q=Rarity.Normal)
Static Public Member Functions inherited from EClass
static int rndSeed (int a, int seed)
static int rnd (long a)
static int rnd (int a)
static int curve (int a, int start, int step, int rate=75)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Public Attributes
int lv = -999
int qualityBonus
string idRace
string idJob
string idEle
Rarity rarity = Rarity.Random
BlessedState? blesstedState
bool fixedMat
bool tryLevelMatTier
bool fixedQuality
bool isCraft
Static Public Attributes
static CardBlueprint current
static CardBlueprint _Default = new CardBlueprint()
static CardBlueprint CharaGenEQ
static CardBlueprint Original
static CardBlueprint DebugEQ
Static Public Attributes inherited from EClass
static Core core
Additional Inherited Members
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Detailed Description
Definition at line 1 of file CardBlueprint.cs.
Member Function Documentation
Chara()
static CardBlueprint CardBlueprint.Chara (int lv, Rarity rarity = Rarity::Normal) inline static
Definition at line 46 of file CardBlueprint.cs.
    {
        return new CardBlueprint
        {
            rarity = rarity,
            lv = lv
        };
    }
References lv, and rarity.
Referenced by Game.AddAdventurers().
Set()
static void CardBlueprint.Set (CardBlueprint _bp = null) inline static
Definition at line 55 of file CardBlueprint.cs.
    {
        current = _bp ?? _Default;
    }
References _Default, and current.
Referenced by Game.AddAdventurers(), RecipeCard.Craft(), ThingGen.CreateTreasureContent(), TaskHarvest.HarvestThing(), ActEffect.Proc(), ActEffect.ProcAt(), CoreDebug.QuickStart(), Chara.SetEQQuality(), SetNormalRarity(), SetRarity(), Card.SpawnLoot(), Zone.TryGenerateBigDaddy(), and TraitSpotBiome.Update().
SetNormalRarity()
static void CardBlueprint.SetNormalRarity (bool fixedMat = false) inline static
Definition at line 60 of file CardBlueprint.cs.
    {
        Set(new CardBlueprint
        {
            rarity = Rarity.Normal,
            fixedMat = fixedMat
        });
    }
References fixedMat, rarity, and Set().
Referenced by InvOwner.Init(), Trait.OnBarter(), DramaManager.ParseLine(), DramaOutcome.QuestDefense_0(), and ActionMode.UpdateInput().
SetRarity()
static void CardBlueprint.SetRarity (Rarity q = Rarity::Normal) inline static
Definition at line 69 of file CardBlueprint.cs.
    {
        Set(new CardBlueprint
        {
            rarity = q
        });
    }
References rarity, and Set().
Referenced by Trait.CreateStock(), and Card.SpawnLoot().
Member Data Documentation
_Default
CardBlueprint CardBlueprint._Default = new CardBlueprint() static
Definition at line 27 of file CardBlueprint.cs.
Referenced by Card.Create(), and Set().
blesstedState
BlessedState? CardBlueprint.blesstedState
Definition at line 15 of file CardBlueprint.cs.
Referenced by Thing.OnCreate().
CharaGenEQ
CardBlueprint CardBlueprint.CharaGenEQ static
Initial value:
= new CardBlueprint
    {
        tryLevelMatTier = true
    }
Definition at line 29 of file CardBlueprint.cs.
Referenced by Chara.SetEQQuality().
current
CardBlueprint CardBlueprint.current static
Definition at line 25 of file CardBlueprint.cs.
Referenced by Card.Create(), ActEffect.ProcAt(), and Set().
DebugEQ
CardBlueprint CardBlueprint.DebugEQ static
Initial value:
= new CardBlueprint
    {
        rarity = Rarity.Mythical,
        lv = int.MaxValue,
        blesstedState = ((EClass.rnd(3) == 0) ? BlessedState.Blessed : BlessedState.Cursed)
    }
Definition at line 39 of file CardBlueprint.cs.
Referenced by CoreDebug.QuickStart().
fixedMat
bool CardBlueprint.fixedMat
Definition at line 17 of file CardBlueprint.cs.
Referenced by Card.Create(), and SetNormalRarity().
fixedQuality
bool CardBlueprint.fixedQuality
Definition at line 21 of file CardBlueprint.cs.
Referenced by Card.Create().
idEle
string CardBlueprint.idEle
Definition at line 11 of file CardBlueprint.cs.
Referenced by Chara.OnCreate(), and ActEffect.ProcAt().
idJob
string CardBlueprint.idJob
Definition at line 9 of file CardBlueprint.cs.
Referenced by Chara.OnBeforeCreate().
idRace
string CardBlueprint.idRace
Definition at line 7 of file CardBlueprint.cs.
Referenced by Chara.OnBeforeCreate().
isCraft
bool CardBlueprint.isCraft
Definition at line 23 of file CardBlueprint.cs.
lv
int CardBlueprint.lv = -999
Definition at line 3 of file CardBlueprint.cs.
Referenced by Chara(), Card.Create(), and Chara.OnCreate().
Original
CardBlueprint CardBlueprint.Original static
Initial value:
= new CardBlueprint
    {
        blesstedState = BlessedState.Normal
    }
Definition at line 34 of file CardBlueprint.cs.
qualityBonus
int CardBlueprint.qualityBonus
Definition at line 5 of file CardBlueprint.cs.
Referenced by Thing.OnCreate().
rarity
Rarity CardBlueprint.rarity = Rarity.Random
Definition at line 13 of file CardBlueprint.cs.
Referenced by Chara(), Card.Create(), Thing.OnCreate(), SetNormalRarity(), and SetRarity().
tryLevelMatTier
bool CardBlueprint.tryLevelMatTier
Definition at line 19 of file CardBlueprint.cs.
Referenced by Card.Create().
The documentation for this class was generated from the following file:
Elin/CardBlueprint.cs