Elin Decompiled Documentation: Hobby Class Reference
Hobby Class Reference
Public Member Functions
AIWork GetAI (Chara c)
int GetLv (Chara c)
int GetEfficiency (Chara c)
Public Attributes
int id
Properties
SourceHobby.Row source [get]
string Name [get]
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Additional Inherited Members
Static Public Member Functions inherited from EClass
static int rnd (int a)
static int curve (int a, int start, int step, int rate=75)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Static Public Attributes inherited from EClass
static Core core
Detailed Description
Definition at line 3 of file Hobby.cs.
Member Function Documentation
GetAI()
AIWork Hobby.GetAI (Chara c) inline
Definition at line 11 of file Hobby.cs.
    {
        AIWork aIWork = null;
        string text = "AIWork_" + source.ai.IsEmpty(source.alias);
        aIWork = ((!(Type.GetType(text + ", Elin") != null)) ? new AIWork() : ClassCache.Create<AIWork>(text, "Elin"));
        aIWork.owner = c;
        aIWork.sourceWork = source;
        return aIWork;
    }
References source.
Referenced by GetEfficiency(), BaseListPeople.OnInstantiate(), Chara.PerformWork(), and GoalWork.TryWork().
GetEfficiency()
int Hobby.GetEfficiency (Chara c) inline
Definition at line 30 of file Hobby.cs.
    {
        int num = 50;
        if (c.homeBranch == null || c.currentZone != c.homeBranch.owner)
        {
            return 0;
        }
        if (c.currentZone == EClass._zone)
        {
            if ((!source.destTrait.IsEmpty() || !source.workTag.IsEmpty()) && !GetAI(c).SetDestination())
            {
                return 0;
            }
            if (c.noMove && c.pos.FindThing<TraitGeneratorWheel>() != null)
            {
                return 0;
            }
            TraitBed traitBed = c.FindBed();
            if (traitBed != null)
            {
                num += 30 + traitBed.owner.GetTotalQuality() + traitBed.owner.Evalue(750);
            }
        }
        if (source.alias == "Breeding")
        {
            num = num * c.race.breeder / 100;
        }
        num += GetLv(c);
        return num * (100 + c.homeBranch.Evalue(3708) * 10) / 100;
    }
References EClass._zone, Chara.currentZone, Card.Evalue(), FactionBranch.Evalue(), Chara.FindBed(), GetAI(), GetLv(), Card.GetTotalQuality(), Chara.homeBranch, Card.noMove, FactionBranch.owner, Trait.owner, Card.pos, and source.
Referenced by FactionBranch.AutoClean(), FactionBranch.GenerateGarbage(), Chara.GetTextHobby(), Chara.GetTextWork(), UIHomeInfo.RefreshReport(), and Chara.RefreshWorkElements().
GetLv()
int Hobby.GetLv (Chara c) inline
Definition at line 21 of file Hobby.cs.
    {
        if (!source.skill.IsEmpty())
        {
            return c.Evalue(source.skill);
        }
        return c.LV;
    }
References Card.Evalue(), Card.LV, and source.
Referenced by GetEfficiency().
Member Data Documentation
id
int Hobby.id
Definition at line 5 of file Hobby.cs.
Referenced by Chara.DiminishTempElements(), and Chara.ListAvailabeFeats().
Property Documentation
Name
string Hobby.Name get
Definition at line 9 of file Hobby.cs.
Referenced by DramaCustomSequence.Build(), Chara.GetTextHobby(), and Chara.GetTextWork().
source
SourceHobby.Row Hobby.source get
Definition at line 7 of file Hobby.cs.
Referenced by GetAI(), GetEfficiency(), GetLv(), Chara.GetWork(), Chara.PerformWork(), FactionBranch.RefreshEfficiency(), and Chara.RefreshWorkElements().
The documentation for this class was generated from the following file:
Elin/Hobby.cs