Elin Decompiled Documentation: BuildMenu Class Reference
BuildMenu Class Reference
Public Types
enum Mode {
Build , None , Hide , Area ,
PartialMap
}
Public Member Functions
void OnActivate ()
void Init ()
void Search (string s)
void ClearSearch ()
void ClearSearch (bool refresh)
void Refresh ()
void SelectCategory (string cat)
void Select (AM_Picker.Result r)
void Unselect ()
void RefreshCategoryArea ()
void RefreshCategory (string cat)
void OnClickPicker ()
Static Public Member Functions
static void Toggle ()
static void Activate ()
static void Deactivate ()
static void Show ()
static void Hide ()
Static Public Member Functions inherited from EMono
static int rnd (int a)
Public Attributes
GridLayoutGroup gridTab
UISelectableGroup groupTab
UIDynamicList list
UIDynamicList listArea
Dictionary< string, int > catDic = new Dictionary<string, int>()
UIRecipeInfo info1
UIRecipeInfo info2
RectTransform transOption
RectTransform transMain
Vector2 posInfo2
Vector2 posInfo1
Vector2 posOption
CanvasGroup cg
float hideSpeed
float intervalSearch
bool moveInfo1
TerrainMenu terrainMenu
InputField inputSearch
string currentCat
string lastCat
UIButton buttonClearSearch
string[] categories
ButtonRecipe lastButtonRecipe
Dictionary< string, int > counts = new Dictionary<string, int>()
Dictionary< string, UIButton > tabs = new Dictionary<string, UIButton>()
UIButton buttonUndo
string lastSearch
HashSet< Recipe > searchRecipes = new HashSet<Recipe>()
Static Public Attributes
static BuildMenu Instance
static bool dirtyCat
Static Public Attributes inherited from EMono
static Core core
Properties
BuildMenu.Mode mode [get]
Properties inherited from EMono
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SoundManager Sound [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static CoreDebug debug [get]
Private Member Functions
void _Search ()
void LateUpdate ()
Private Attributes
Vector2 orgPos
Vector2 orgPosOption
float timerSearch
bool firstRefresh = true
Detailed Description
Definition at line 7 of file BuildMenu.cs.
Member Enumeration Documentation
Mode
enum BuildMenu.Mode
Enumerator
Build
None
Hide
Area
PartialMap
Definition at line 723 of file BuildMenu.cs.
    {
        Build,
        None,
        Hide,
        Area,
        PartialMap
    }
Member Function Documentation
_Search()
void BuildMenu._Search () inline private
Definition at line 166 of file BuildMenu.cs.
    {
        string s = this.lastSearch;
        RecipeManager.BuildList();
        HashSet<Recipe> newRecipes = new HashSet<Recipe>();
        if (!s.IsEmpty())
        {
            foreach (RecipeSource recipeSource in RecipeManager.list)
            {
                if (!recipeSource.noListing && !recipeSource.isBridgePillar && (EMono.debug.godBuild || recipeSource.alwaysKnown || EMono.player.recipes.knownRecipes.ContainsKey(recipeSource.id)) && (recipeSource.row.GetSearchName(false).Contains(s) || recipeSource.row.GetSearchName(true).Contains(s) || recipeSource.id.Contains(s) || recipeSource.row.category.Contains(s)))
                {
                    for (int i = 0; i < ((recipeSource.row.skins == null) ? 1 : (recipeSource.row.skins.Length + 1)); i++)
                    {
                        Recipe recipe = Recipe.Create(recipeSource, -1, null);
                        recipe.idSkin = i;
                        if (recipe == null)
{
                            Debug.Log(recipeSource.Name + "/" + recipeSource.id);
                        }
                        else
{
                            newRecipes.Add(recipe);
                        }
                    }
                }
            }
            foreach (Thing thing in EMono._map.Stocked.Things)
            {
                if (EMono._map.Stocked.ShouldListAsResource(thing) && (thing.source.name.Contains(s) || thing.source.name_JP.Contains(s)))
                {
                    Recipe recipe2 = Recipe.Create(thing);
                    if (recipe2 == null)
                    {
                        Debug.Log(thing.Name + "/" + thing.id);
                    }
                    else
                    {
                        newRecipes.Add(recipe2);
                    }
                }
            }
            EMono.pc.things.Foreach(delegate(Thing t)
            {
                if (!t.trait.CanBeDropped || t.trait.CanOnlyCarry)
                {
                    return;
                }
                if (t.source.name.Contains(s) || t.source.name_JP.Contains(s))
                {
                    Recipe recipe3 = Recipe.Create(t);
                    if (recipe3 == null)
                    {
                        Debug.Log(t.Name + "/" + t.id);
                        return;
                    }
                    newRecipes.Add(recipe3);
                }
            }, true);
        }
        if (!newRecipes.SetEquals(this.searchRecipes))
        {
            this.searchRecipes = newRecipes;
            this.RefreshCategory(this.currentCat);
        }
        this.lastSearch = s;
    }
References EMono._map, RecipeSource.alwaysKnown, RecipeManager.BuildList(), Trait.CanBeDropped, Trait.CanOnlyCarry, RenderRow.category, Recipe.Create(), currentCat, EMono.debug, ThingContainer.Foreach(), RenderRow.GetSearchName(), CoreDebug.godBuild, Card.id, RecipeSource.id, RecipeSource.isBridgePillar, RecipeManager.knownRecipes, lastSearch, RecipeManager.list, Card.Name, RecipeSource.Name, RecipeSource.noListing, EMono.pc, EMono.player, Player.recipes, RefreshCategory(), RecipeSource.row, Props.ShouldListAsResource(), RenderRow.skins, Thing.source, Map.Stocked, Card.things, Props.Things, and Card.trait.
Referenced by LateUpdate().
Activate()
static void BuildMenu.Activate () inline static
Definition at line 36 of file BuildMenu.cs.
    {
        if (!BuildMenu.Instance)
        {
            BuildMenu.Instance = Util.Instantiate<BuildMenu>("UI/BuildMenu/BuildMenu", EMono.ui);
            BuildMenu.Instance.Init();
        }
        if (EMono.debug.godBuild)
        {
            EMono._map.RevealAll(true);
        }
        RecipeManager.BuildList();
        BuildMenu.Instance.OnActivate();
        EMono.screen.focusPos = null;
    }
References EMono._map, RecipeManager.BuildList(), EMono.debug, CoreDebug.godBuild, Init(), Instance, OnActivate(), Map.RevealAll(), and EMono.ui.
Referenced by ActionMode.Activate().
ClearSearch() [1/2]
void BuildMenu.ClearSearch () inline
Definition at line 233 of file BuildMenu.cs.
    {
        this.ClearSearch(true);
    }
References ClearSearch().
Referenced by ClearSearch(), Init(), and Select().
ClearSearch() [2/2]
void BuildMenu.ClearSearch (bool refresh) inline
Definition at line 238 of file BuildMenu.cs.
    {
        SE.Click();
        this.inputSearch.text = "";
        this.timerSearch = 0f;
        this.lastSearch = "";
        if (refresh)
        {
            this.RefreshCategory(this.currentCat);
        }
    }
References currentCat, and RefreshCategory().
Deactivate()
static void BuildMenu.Deactivate () inline static
Definition at line 97 of file BuildMenu.cs.
    {
        if (!BuildMenu.Instance)
        {
            return;
        }
        UnityEngine.Object.DestroyImmediate(BuildMenu.Instance.gameObject);
        if (EMono.game.altUI)
        {
            EMono._zone.RefreshBGM();
        }
        EMono.ui.ShowFloats();
        EMono.screen.RefreshAll();
    }
References EMono._zone, Game.altUI, EMono.game, Instance, BaseGameScreen.RefreshAll(), Zone.RefreshBGM(), EMono.screen, and EMono.ui.
Referenced by ActionMode.Activate(), and Scene.Init().
Hide()
static void BuildMenu.Hide () inline static
Definition at line 258 of file BuildMenu.cs.
    {
        if (BuildMenu.Instance)
        {
            BuildMenu.Instance.SetActive(false);
        }
    }
References Instance.
Referenced by LayerArea.OnInit().
Init()
void BuildMenu.Init () inline
Definition at line 112 of file BuildMenu.cs.
    {
        this.info1.Init();
        this.info2.Init();
        this.info2.transform.position = this.info1.transform.position;
        this.orgPos = this.info1.Rect().anchoredPosition;
        this.orgPosOption = this.transOption.anchoredPosition;
        for (int i = 0; i < this.categories.Length; i++)
        {
            if (!this.categories[i].IsEmpty())
            {
                this.catDic.Add(this.categories[i], i);
            }
        }
        UIButton t = this.gridTab.CreateMold(null);
        for (int j = 0; j < this.categories.Length - 1; j++)
        {
            int _i = j;
            UIButton uibutton = Util.Instantiate<UIButton>(t, this.gridTab);
            uibutton.onClick.AddListener(delegate()
            {
                this.ClearSearch(false);
                this.SelectCategory(this.categories[_i]);
            });
            uibutton.mainText.SetText(("cat_" + this.categories[j]).lang());
            this.tabs[this.categories[j]] = uibutton;
            if (this.categories[j].IsEmpty())
            {
                uibutton.mainText.SetActive(false);
                uibutton.interactable = false;
            }
        }
        this.groupTab.Init(-1, null, false);
        EMono.ui.hud.frame.SetActive(EMono.game.altUI);
        this.inputSearch.onValueChanged.AddListener(new UnityAction<string>(this.Search));
        this.inputSearch.onSubmit.AddListener(new UnityAction<string>(this.Search));
        if (EMono.game.altUI)
        {
            EMono.Sound.SwitchPlaylist(EMono.Sound.playlistBuild, true);
        }
    }
References Game.altUI, catDic, categories, ClearSearch(), EMono.game, gridTab, groupTab, info1, info2, UIRecipeInfo.Init(), inputSearch, Search, SelectCategory(), EMono.Sound, tabs, transOption, and EMono.ui.
Referenced by Activate().
LateUpdate()
void BuildMenu.LateUpdate () inline private
Definition at line 266 of file BuildMenu.cs.
    {
        this.Refresh();
        if (this.timerSearch > 0f)
        {
            this.timerSearch -= Core.delta;
            if (this.timerSearch <= 0f)
            {
                this._Search();
            }
        }
    }
References _Search(), Refresh(), and timerSearch.
OnActivate()
void BuildMenu.OnActivate () inline
Definition at line 52 of file BuildMenu.cs.
    {
        if (EMono.debug.godBuild && EMono.debug.GetDebugContainer() == null)
        {
            EMono.debug.EnableDebugResource();
        }
        EMono.ui.HideFloats();
        this.SetActive(this.mode != BuildMenu.Mode.None);
        this.transMain.SetActive(this.mode == BuildMenu.Mode.Build && (EMono.debug.godBuild || EMono._zone.elements.Has(4005)));
        BuildMenu.Mode mode = this.mode;
        if (mode != BuildMenu.Mode.Build)
        {
            if (mode == BuildMenu.Mode.Area)
            {
                this.RefreshCategoryArea();
                this.Refresh();
            }
        }
        else
        {
            string cat = EMono.player.pref.lastBuildCategory.IsEmpty("wall");
            this.SelectCategory(cat);
            this.Refresh();
            UIScrollView componentInChildren = this.cg.GetComponentInChildren<UIScrollView>();
            if (componentInChildren != null)
            {
                componentInChildren.RebuildLayout(true);
            }
            this.buttonUndo.onClick.RemoveAllListeners();
            this.buttonUndo.onClick.AddListener(delegate()
            {
                EMono._map.tasks.undo.Perform();
            });
            this.buttonUndo.SetTooltip("note", delegate(UITooltip tp)
            {
                EMono._map.tasks.undo.WriteNote(tp.note);
            }, true);
        }
        if (EMono.debug.enable)
        {
            EMono._map.ResetEditorPos();
        }
        EMono.screen.RefreshAll();
    }
References EMono._map, EMono._zone, buttonUndo, cg, EMono.debug, Zone.elements, CoreDebug.enable, CoreDebug.EnableDebugResource(), CoreDebug.GetDebugContainer(), CoreDebug.godBuild, ElementContainer.Has(), mode, UndoManager.Perform(), EMono.player, Player.pref, Refresh(), BaseGameScreen.RefreshAll(), RefreshCategoryArea(), Map.ResetEditorPos(), EMono.screen, SelectCategory(), Map.tasks, transMain, EMono.ui, TaskManager.undo, and UndoManager.WriteNote().
Referenced by Activate().
OnClickPicker()
void BuildMenu.OnClickPicker () inline
Definition at line 626 of file BuildMenu.cs.
    {
        ActionMode.Picker.Activate(true, false);
    }
References ActionMode.Activate(), and ActionMode.Picker.
Refresh()
void BuildMenu.Refresh () inline
Definition at line 279 of file BuildMenu.cs.
    {
        ButtonGrid buttonGrid = InputModuleEX.GetComponentOf<ButtonGrid>();
        if (buttonGrid && buttonGrid.recipe == null && buttonGrid.area == null)
        {
            buttonGrid = null;
        }
        bool flag = EMono.scene.actionMode.ShouldHideBuildMenu || (EMono.scene.actionMode != ActionMode.Build && EMono.scene.actionMode != ActionMode.Inspect && EMono.scene.actionMode != ActionMode.EditArea);
        this.cg.SetActive(!flag, delegate(bool enabled)
        {
            if (enabled)
            {
                this.list.RefreshHighlight(false);
                this.groupTab.RefreshButtons();
            }
        });
        this.groupTab.SetActive(EMono.scene.actionMode != ActionMode.EditArea);
        this.transOption.anchoredPosition = (this.groupTab.gameObject.activeInHierarchy ? this.orgPosOption : this.posOption);
        if (this.info1.hideMode != flag || this.firstRefresh)
        {
            this.info1.hideMode = flag;
            if (this.moveInfo1)
            {
                this.info1.Rect().anchoredPosition = (flag ? this.posInfo1 : this.orgPos);
            }
        }
        if (buttonGrid && !flag)
        {
            this.info2.transform.position = buttonGrid.transform.position;
            this.info2.Rect().anchoredPosition = new Vector2(this.info2.Rect().anchoredPosition.x + this.posInfo2.x, this.posInfo2.y);
            if (buttonGrid.area != null)
            {
                this.info2.SetArea(buttonGrid.area);
            }
            else
            {
                this.info2.SetRecipe(buttonGrid.recipe);
            }
            this.info2.SetActive(true);
        }
        else
        {
            this.info2.SetActive(false);
        }
        this.firstRefresh = false;
    }
References Scene.actionMode, ButtonGrid.area, cg, ActionMode.EditArea, groupTab, UIRecipeInfo.hideMode, info1, info2, list, moveInfo1, orgPos, posOption, ButtonGrid.recipe, EMono.scene, UIRecipeInfo.SetArea(), and UIRecipeInfo.SetRecipe().
Referenced by LateUpdate(), and OnActivate().
RefreshCategory()
void BuildMenu.RefreshCategory (string cat) inline
Definition at line 419 of file BuildMenu.cs.
    {
        cat = cat.IsEmpty(this.categories[0]);
        EMono.player.pref.lastBuildCategory = cat;
        this.currentCat = cat;
        this.list.Clear();
        object selected = null;
        this.counts.Clear();
        Action<Thing> <>9__4;
        this.list.callbacks = new UIList.Callback<Recipe, ButtonGrid>
        {
            onClick = delegate(Recipe a, ButtonGrid b)
            {
                SE.Click();
                EMono.ui.hud.hint.Refresh();
                EMono.player.pref.lastBuildRecipe = a.source.id;
                if (a.UseStock && (a.ingredients[0].uid == 0 || a.ingredients[0].thing == null))
                {
                    Debug.LogError("expection: invalid ingredient:" + a.ingredients[0].uid.ToString());
                }
                if (this.info1.recipe != a && !a.UseStock)
                {
                    foreach (Recipe.Ingredient ingredient in a.ingredients)
                    {
                        ingredient.SetThing(null);
                    }
                }
                if (a.UseStock && (a.ingredients[0].uid == 0 || a.ingredients[0].thing == null))
                {
                    Debug.LogError("expection: invalid ingredient:" + a.ingredients[0].uid.ToString());
                }
                this.info1.SetRecipe(a);
                if (a.UseStock && (a.ingredients[0].uid == 0 || a.ingredients[0].thing == null))
                {
                    Debug.LogError("expection: invalid ingredient:" + a.ingredients[0].uid.ToString());
                }
                a.OnChangeIngredient();
                ActionMode.Build.StartBuild(a, () => this.list.GetComp<ButtonGrid>(a));
                this.info1.SetRecipe(a);
                this.list.Select(a, false);
                if (a.UseStock && (a.ingredients[0].uid == 0 || a.ingredients[0].thing == null))
                {
                    Debug.LogError("expection: invalid ingredient:" + a.ingredients[0].uid.ToString());
                }
            },
            onRedraw = delegate(Recipe a, ButtonGrid b, int i)
            {
                b.SetActive(a != null);
                if (a == null)
                {
                    return;
                }
                b.SetRecipe(a);
                if (this.info1.recipe != null && a.id == this.info1.recipe.id)
                {
                    selected = a;
                }
                a.BuildIngredientList();
            },
            onList = delegate(UIList.SortMode m)
            {
                foreach (string key in this.categories)
                {
                    this.counts[key] = 0;
                }
                if (this.inputSearch.text != "")
                {
                    foreach (Recipe recipe in this.searchRecipes)
                    {
                        if (recipe.UseStock)
{
                            Thing thing = recipe.ingredients[0].thing;
                            if (thing == null || thing.isDestroyed || thing.ExistsOnMap || (thing.parentCard != null && thing.parentCard.c_lockLv > 0))
{
                                continue;
                            }
                        }
                        this.list.Add(recipe);
                    }
                    return;
                }
                foreach (RecipeSource recipeSource in RecipeManager.list)
                {
                    if (EMono.debug.godBuild || (!recipeSource.noListing && !recipeSource.row.tileType.EditorTile && EMono.player.recipes.IsKnown(recipeSource.id) && (recipeSource.row.factory.Length == 0 || !(recipeSource.row.factory[0] == "none"))))
                    {
                        Dictionary<string, int> dictionary = this.counts;
                        string recipeCat = recipeSource.recipeCat;
                        int i = dictionary[recipeCat];
                        dictionary[recipeCat] = i + 1;
                        if (!(recipeSource.recipeCat != cat))
{
                            for (int j = 0; j < ((recipeSource.row.skins == null) ? 0 : recipeSource.row.skins.Length) + 1; j++)
{
                                Recipe recipe2 = Recipe.Create(recipeSource, -1, null);
                                recipe2.idSkin = j;
                                this.list.Add(recipe2);
                            }
                        }
                    }
                }
                if (!EMono.debug.hidePCItemsInBuild)
                {
                    foreach (Thing thing2 in EMono._map.Stocked.Things)
                    {
                        if (EMono._map.Stocked.ShouldListAsResource(thing2))
{
                            Dictionary<string, int> dictionary2 = this.counts;
                            string recipeCat = thing2.trait.RecipeCat;
                            int i = dictionary2[recipeCat];
                            dictionary2[recipeCat] = i + 1;
                            if (thing2.trait.RecipeCat == cat)
{
                                Card rootCard = thing2.GetRootCard();
                                if (rootCard != null && rootCard.c_lockLv == 0)
{
                                    this.list.Add(thing2.trait.GetBuildModeRecipe());
                                }
                            }
                        }
                    }
                    ThingContainer things = EMono.pc.things;
                    Action<Thing> action;
                    if ((action = <>9__4) == null)
                    {
                        action = (<>9__4 = delegate(Thing t)
{
                            if (t.trait.CanOnlyCarry || !t.trait.CanBeDropped || t.c_isImportant)
{
                                return;
                            }
                            Dictionary<string, int> dictionary3 = this.counts;
                            string recipeCat2 = t.trait.RecipeCat;
                            int num = dictionary3[recipeCat2];
                            dictionary3[recipeCat2] = num + 1;
                            if (t.trait.RecipeCat == cat && t.invY != 1)
{
                                this.list.Add(t.trait.GetBuildModeRecipe());
                            }
                        });
                    }
                    things.Foreach(action, true);
                }
                if (cat == "other")
                {
                    this.list.objects.Sort((object a, object b) => string.Compare((a as Recipe).id, (b as Recipe).id));
                }
                else if (cat == "wall" || cat == "floor" || cat == "foundation" || cat == "obj")
                {
                    this.list.objects.Sort((object a, object b) => (a as Recipe).renderRow.sort - (b as Recipe).renderRow.sort);
                }
                else
                {
                    this.list.objects.Sort(delegate(object a, object b)
                    {
                        Recipe recipe3 = a as Recipe;
                        Recipe recipe4 = b as Recipe;
                        int num = recipe3.renderRow.sort - recipe4.renderRow.sort;
                        if (num == 0)
{
                            RecipeCard recipeCard = recipe3 as RecipeCard;
                            RecipeCard recipeCard2 = recipe4 as RecipeCard;
                            if (recipeCard != null && recipeCard2 != null)
{
                                num = string.Compare(recipeCard.sourceCard._origin.IsEmpty(recipeCard.sourceCard.id), recipeCard2.sourceCard._origin.IsEmpty(recipeCard2.sourceCard.id));
                            }
                            else
{
                                num = string.Compare(recipe3.id, recipe4.id);
                            }
                            if (num == 0)
{
                                num = (recipe3.IngAsProduct ? recipe3.ingredients[0].uid : 0) - (recipe4.IngAsProduct ? recipe4.ingredients[0].uid : 0);
                            }
                        }
                        return num;
                    });
                }
                foreach (string text in this.categories)
                {
                    if (!(text == "area") && !(text == ""))
                    {
                        if (this.counts[text] == 0)
{
                            this.tabs[text].subText.text = "";
                        }
                        else
{
                            this.tabs[text].subText.text = (this.counts[text].ToString() ?? "");
                        }
                    }
                }
            }
        };
        this.list.List();
        if (this.lastCat != this.currentCat)
        {
            this.list.Scroll(0);
        }
        this.groupTab.Select(this.catDic[cat]);
        if (selected != null)
        {
            this.list.Select(selected, false);
        }
        this.lastCat = this.currentCat;
        this.list.RebuildLayoutTo<BuildMenu>();
    }
References EMono._map, CardRow._origin, ActionMode.Build, Recipe.BuildIngredientList(), Card.c_isImportant, Card.c_lockLv, Trait.CanBeDropped, Trait.CanOnlyCarry, catDic, categories, counts, Recipe.Create(), currentCat, EMono.debug, TileType.EditorTile, Card.ExistsOnMap, RenderRow.factory, ThingContainer.Foreach(), Trait.GetBuildModeRecipe(), Card.GetRootCard(), CoreDebug.godBuild, groupTab, CoreDebug.hidePCItemsInBuild, CardRow.id, Recipe.id, RecipeSource.id, info1, Recipe.IngAsProduct, Recipe.ingredients, inputSearch, Card.invY, Card.isDestroyed, RecipeManager.IsKnown(), lastCat, list, RecipeManager.list, RecipeSource.noListing, Recipe.OnChangeIngredient(), Card.parentCard, EMono.pc, EMono.player, UIRecipeInfo.recipe, RecipeSource.recipeCat, Trait.RecipeCat, Player.recipes, Recipe.renderRow, RecipeSource.row, searchRecipes, ButtonGrid.SetRecipe(), UIRecipeInfo.SetRecipe(), Props.ShouldListAsResource(), RenderRow.skins, RenderRow.sort, Recipe.source, RecipeCard.sourceCard, AM_Build.StartBuild(), Map.Stocked, tabs, text, Card.things, Props.Things, RenderRow.tileType, Card.trait, EMono.ui, and Recipe.UseStock.
Referenced by _Search(), ClearSearch(), AM_Build.OnFinishProcessTiles(), Select(), and SelectCategory().
RefreshCategoryArea()
void BuildMenu.RefreshCategoryArea () inline
Definition at line 375 of file BuildMenu.cs.
    {
        UIDynamicList uidynamicList = this.listArea;
        List<Area> list = new List<Area>();
        foreach (SourceArea.Row row in EMono.sources.areas.rows)
        {
            Area area = Area.Create(row.id);
            area.data.name = null;
            list.Add(area);
        }
        uidynamicList.Clear();
        object selected = null;
        uidynamicList.callbacks = new UIList.Callback<Area, ButtonGrid>
        {
            onClick = delegate(Area a, ButtonGrid b)
            {
                SE.Click();
                ActionMode.CreateArea.SetArea(a);
                if (EMono.scene.actionMode != ActionMode.CreateArea)
                {
                    ActionMode.CreateArea.Activate(true, false);
                }
                EMono.ui.hud.hint.Refresh();
                this.info1.SetArea(a);
            },
            onRedraw = delegate(Area a, ButtonGrid b, int i)
            {
                b.SetRecipe(a);
                if (this.info1.area != null && a.source == this.info1.area.source)
                {
                    selected = a;
                }
            }
        };
        foreach (Area area2 in list)
        {
            if (area2.isListable)
            {
                uidynamicList.Add(area2);
            }
        }
        uidynamicList.List();
    }
References Scene.actionMode, ActionMode.Activate(), Area, UIRecipeInfo.area, SourceManager.areas, Area.Create(), ActionMode.CreateArea, info1, Area.isListable, list, listArea, EMono.scene, AM_CreateArea.SetArea(), UIRecipeInfo.SetArea(), ButtonGrid.SetRecipe(), BaseArea.source, EMono.sources, and EMono.ui.
Referenced by OnActivate().
Search()
void BuildMenu.Search (string s) inline
Definition at line 154 of file BuildMenu.cs.
    {
        s = s.ToLower();
        this.buttonClearSearch.SetActive(this.inputSearch.text != "");
        if (s == this.lastSearch)
        {
            return;
        }
        this.timerSearch = this.intervalSearch;
        this.lastSearch = s;
    }
References buttonClearSearch, inputSearch, intervalSearch, and lastSearch.
Select()
void BuildMenu.Select (AM_Picker::Result r) inline
Definition at line 337 of file BuildMenu.cs.
    {
        EInput.Consume(false, 10);
        Debug.Log(EInput.skipFrame);
        this.ClearSearch(false);
        this.RefreshCategory(r.source.recipeCat);
        foreach (object obj in this.list.objects)
        {
            Recipe recipe = obj as Recipe;
            if (r.source == recipe.source && (r.thing == null || r.thing.idSkin == recipe.idSkin))
            {
                int index = this.list.GetIndex(recipe);
                if (index != -1)
                {
                    this.list.dsv.scrollByItemIndex(index);
                    this.list.Refresh();
                    break;
                }
                break;
            }
        }
        foreach (ButtonGrid buttonGrid in this.list.GetComponentsInChildren<ButtonGrid>())
        {
            if (buttonGrid.recipe.source == r.source && (r.thing == null || r.thing.idSkin == buttonGrid.recipe.idSkin))
            {
                this.info1.lastMats[buttonGrid.recipe.id] = r.mat.id;
                buttonGrid.onClick.Invoke();
                return;
            }
        }
    }
References ClearSearch(), Recipe.id, Recipe.idSkin, info1, UIRecipeInfo.lastMats, list, ButtonGrid.recipe, RefreshCategory(), and Recipe.source.
Referenced by AM_Picker.Select().
SelectCategory()
void BuildMenu.SelectCategory (string cat) inline
Definition at line 326 of file BuildMenu.cs.
    {
        if (!BuildMenu.dirtyCat && this.currentCat == cat)
        {
            return;
        }
        BuildMenu.dirtyCat = false;
        this.groupTab.Select(this.catDic[cat]);
        this.RefreshCategory(cat);
    }
References catDic, dirtyCat, groupTab, and RefreshCategory().
Referenced by Init(), and OnActivate().
Show()
static void BuildMenu.Show () inline static
Definition at line 250 of file BuildMenu.cs.
    {
        if (BuildMenu.Instance)
        {
            BuildMenu.Instance.SetActive(true);
        }
    }
References Instance.
Referenced by LayerArea.OnKill().
Toggle()
static void BuildMenu.Toggle () inline static
Definition at line 17 of file BuildMenu.cs.
    {
        EMono.player.hotbars.ResetHotbar(3);
        EMono.player.hotbars.bars[3].dirty = true;
        EMono.player.hotbars.ResetHotbar(4);
        EMono.player.hotbars.bars[4].dirty = true;
        if (EMono.debug.godBuild || (EMono.Branch != null && EMono.Branch.elements.Has(4006)))
        {
            ActionMode.Inspect.Activate(true, false);
            return;
        }
        if (ActionMode.LastBuildMode != null)
        {
            ActionMode.LastBuildMode.Activate(true, false);
            return;
        }
        ActionMode.Terrain.Activate(true, false);
    }
References ActionMode.Activate(), AM_MoveInstalled.Activate(), HotbarManager.bars, EMono.Branch, EMono.debug, Hotbar.dirty, FactionBranch.elements, CoreDebug.godBuild, ElementContainer.Has(), Player.hotbars, ActionMode.Inspect, ActionMode.LastBuildMode, EMono.player, HotbarManager.ResetHotbar(), and ActionMode.Terrain.
Referenced by HotItemActionMode.Execute(), and TraitBuildBoard.TrySetAct().
Unselect()
void BuildMenu.Unselect () inline
Definition at line 369 of file BuildMenu.cs.
    {
        this.info1.SetRecipe(null);
        this.list.Select(null, false);
    }
References info1, list, and UIRecipeInfo.SetRecipe().
Referenced by AM_Build.OnDeactivate(), AM_CreateArea.OnDeactivate(), AM_ExpandArea.OnDeactivate(), and AM_Build.OnFinishProcessTiles().
Member Data Documentation
buttonClearSearch
UIButton BuildMenu.buttonClearSearch
Definition at line 671 of file BuildMenu.cs.
Referenced by Search().
buttonUndo
UIButton BuildMenu.buttonUndo
Definition at line 711 of file BuildMenu.cs.
Referenced by OnActivate().
catDic
Dictionary<string, int> BuildMenu.catDic = new Dictionary<string, int>()
Definition at line 639 of file BuildMenu.cs.
Referenced by Init(), RefreshCategory(), and SelectCategory().
categories
string [] BuildMenu.categories
Initial value:
= new string[]
    {
        "wall",
        "floor",
        "foundation",
        "door",
        "furniture",
        "storage",
        "spot",
        "mount",
        "facility",
        "tool",
        "deco",
        "mech",
        "light",
        "junk",
        "ext",
        "goods",
        "food",
        "obj",
        "other",
        "area"
    }
Definition at line 674 of file BuildMenu.cs.
Referenced by Init(), and RefreshCategory().
cg
CanvasGroup BuildMenu.cg
Definition at line 655 of file BuildMenu.cs.
Referenced by OnActivate(), and Refresh().
counts
Dictionary<string, int> BuildMenu.counts = new Dictionary<string, int>()
Definition at line 701 of file BuildMenu.cs.
Referenced by RefreshCategory().
currentCat
string BuildMenu.currentCat
Definition at line 667 of file BuildMenu.cs.
Referenced by _Search(), ClearSearch(), and RefreshCategory().
dirtyCat
bool BuildMenu.dirtyCat static
Definition at line 713 of file BuildMenu.cs.
Referenced by SelectCategory().
firstRefresh
bool BuildMenu.firstRefresh = true private
Definition at line 721 of file BuildMenu.cs.
gridTab
GridLayoutGroup BuildMenu.gridTab
Definition at line 631 of file BuildMenu.cs.
Referenced by Init().
groupTab
UISelectableGroup BuildMenu.groupTab
Definition at line 633 of file BuildMenu.cs.
Referenced by Init(), Refresh(), RefreshCategory(), and SelectCategory().
hideSpeed
float BuildMenu.hideSpeed
Definition at line 657 of file BuildMenu.cs.
info1
UIRecipeInfo BuildMenu.info1
Definition at line 641 of file BuildMenu.cs.
Referenced by HitSummary.Execute(), BaseTileSelector.ExecuteSummary(), Init(), Refresh(), RefreshCategory(), RefreshCategoryArea(), BaseTileSelector.RefreshSummary(), Recipe.Rotate(), RecipeCard.Rotate(), Select(), Recipe.SetDir(), and Unselect().
info2
UIRecipeInfo BuildMenu.info2
Definition at line 643 of file BuildMenu.cs.
Referenced by Init(), and Refresh().
inputSearch
InputField BuildMenu.inputSearch
Definition at line 665 of file BuildMenu.cs.
Referenced by Init(), RefreshCategory(), and Search().
Instance
BuildMenu BuildMenu.Instance static
Definition at line 709 of file BuildMenu.cs.
Referenced by Activate(), ActionMode.Activate(), Recipe.Build(), Deactivate(), HitSummary.Execute(), BaseTileSelector.ExecuteSummary(), TaskCut.GetHitResult(), TaskHarvest.GetHitResult(), Hide(), AM_Build.OnDeactivate(), AM_CreateArea.OnDeactivate(), AM_ExpandArea.OnDeactivate(), AM_Build.OnFinishProcessTiles(), LayerEditHouse.OnKill(), AM_Copy.RefreshMenu(), BaseTileSelector.RefreshSummary(), BaseGameScreen.RefreshWeather(), Recipe.Rotate(), RecipeCard.Rotate(), LayerEditHouse.SetBoard(), Recipe.SetDir(), and Show().
intervalSearch
float BuildMenu.intervalSearch
Definition at line 659 of file BuildMenu.cs.
Referenced by Search().
lastButtonRecipe
ButtonRecipe BuildMenu.lastButtonRecipe
Definition at line 699 of file BuildMenu.cs.
lastCat
string BuildMenu.lastCat
Definition at line 669 of file BuildMenu.cs.
Referenced by RefreshCategory().
lastSearch
string BuildMenu.lastSearch
Definition at line 717 of file BuildMenu.cs.
Referenced by _Search(), and Search().
list
UIDynamicList BuildMenu.list
Definition at line 635 of file BuildMenu.cs.
Referenced by Refresh(), RefreshCategory(), RefreshCategoryArea(), Select(), and Unselect().
listArea
UIDynamicList BuildMenu.listArea
Definition at line 637 of file BuildMenu.cs.
Referenced by RefreshCategoryArea().
moveInfo1
bool BuildMenu.moveInfo1
Definition at line 661 of file BuildMenu.cs.
Referenced by Refresh().
orgPos
Vector2 BuildMenu.orgPos private
Definition at line 705 of file BuildMenu.cs.
Referenced by Refresh().
orgPosOption
Vector2 BuildMenu.orgPosOption private
Definition at line 707 of file BuildMenu.cs.
posInfo1
Vector2 BuildMenu.posInfo1
Definition at line 651 of file BuildMenu.cs.
posInfo2
Vector2 BuildMenu.posInfo2
Definition at line 649 of file BuildMenu.cs.
posOption
Vector2 BuildMenu.posOption
Definition at line 653 of file BuildMenu.cs.
Referenced by Refresh().
searchRecipes
HashSet<Recipe> BuildMenu.searchRecipes = new HashSet<Recipe>()
Definition at line 719 of file BuildMenu.cs.
Referenced by RefreshCategory().
tabs
Dictionary<string, UIButton> BuildMenu.tabs = new Dictionary<string, UIButton>()
Definition at line 703 of file BuildMenu.cs.
Referenced by Init(), and RefreshCategory().
terrainMenu
TerrainMenu BuildMenu.terrainMenu
Definition at line 663 of file BuildMenu.cs.
Referenced by ActionMode.Activate(), and AM_Copy.RefreshMenu().
timerSearch
float BuildMenu.timerSearch private
Definition at line 715 of file BuildMenu.cs.
Referenced by LateUpdate().
transMain
RectTransform BuildMenu.transMain
Definition at line 647 of file BuildMenu.cs.
Referenced by OnActivate().
transOption
RectTransform BuildMenu.transOption
Definition at line 645 of file BuildMenu.cs.
Referenced by Init().
Property Documentation
mode
BuildMenu.Mode BuildMenu.mode get
Definition at line 9 of file BuildMenu.cs.
    {
        get
        {
            return EMono.scene.actionMode.buildMenuMode;
        }
    }
Referenced by OnActivate().
The documentation for this class was generated from the following file:
Elin/BuildMenu.cs