Elin Decompiled Documentation: SerializableColor Class Reference
SerializableColor Class Reference
Public Member Functions
Color Get ()
SerializableColor ()
SerializableColor (Color color)
SerializableColor (byte[] bytes)
SerializableColor (byte r, byte g, byte b, byte a=byte.MaxValue)
SerializableColor Set (Color color)
Static Public Member Functions
static void ToBytes (Color color, ref byte[] bytes, int index)
static Color FromBytes (byte[] _color, int index)
Public Attributes
byte[] _color
Detailed Description
Definition at line 7 of file SerializableColor.cs.
Constructor & Destructor Documentation
SerializableColor() [1/4]
SerializableColor.SerializableColor () inline
Definition at line 17 of file SerializableColor.cs.
    {
    }
SerializableColor() [2/4]
SerializableColor.SerializableColor (Color color) inline
Definition at line 21 of file SerializableColor.cs.
    {
        Set(color);
    }
References Set().
SerializableColor() [3/4]
SerializableColor.SerializableColor (byte[] bytes) inline
Definition at line 26 of file SerializableColor.cs.
    {
        _color = bytes;
    }
References _color.
SerializableColor() [4/4]
SerializableColor.SerializableColor (byte r, byte g, byte b, byte a = byte::MaxValue) inline
Definition at line 31 of file SerializableColor.cs.
    {
        _color = new byte[4] { r, g, b, a };
    }
References _color.
Member Function Documentation
FromBytes()
static Color SerializableColor.FromBytes (byte[] _color, int index) inline static
Definition at line 49 of file SerializableColor.cs.
    {
        return new Color32(_color[index], _color[index + 1], _color[index + 2], _color[index + 3]);
    }
References _color.
Get()
Color SerializableColor.Get () inline
Definition at line 12 of file SerializableColor.cs.
    {
        return (_color != null) ? new Color32(_color[0], _color[1], _color[2], _color[3]) : default(Color32);
    }
References _color.
Referenced by LiquidProfile.Apply(), LiquidProfile.ApplyColor(), TraitEffect.Proc(), WidgetSceneCustomizer.RefreshColor(), BaseGameScreen.RefreshGrading(), WidgetSceneCustomizer.ShowPicker(), TraitEffect.TrySetAct(), and TraitMapBoard.TrySetAct().
Set()
SerializableColor SerializableColor.Set (Color color) inline
Definition at line 36 of file SerializableColor.cs.
    {
        Color32 color2 = color;
        _color = new byte[4] { color2.r, color2.g, color2.b, color2.a };
        return this;
    }
References _color.
Referenced by SerializableColor(), TraitEffect.TrySetAct(), and TraitMapBoard.TrySetAct().
ToBytes()
static void SerializableColor.ToBytes (Color color, ref byte[] bytes, int index) inline static
Definition at line 43 of file SerializableColor.cs.
    {
        Color32 color2 = color;
        new byte[4] { color2.r, color2.g, color2.b, color2.a }.CopyTo(bytes, index);
    }
Member Data Documentation
_color
byte [] SerializableColor._color
Definition at line 10 of file SerializableColor.cs.
Referenced by FromBytes(), Get(), SerializableColor(), and Set().
The documentation for this class was generated from the following file:
Elin/Plugins.basecore/SerializableColor.cs