Elin Decompiled Documentation: RendererReplacer Class Reference
RendererReplacer Class Reference
Static Public Member Functions
static RendererReplacer CreateFrom (string id, int shift=0, int mat=-1)
Static Public Member Functions inherited from EClass
static int rndSeed (int a, int seed)
static int rnd (long a)
static int rnd (int a)
static int curve (int _a, int start, int step, int rate=75)
static int sqrt (int a)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Public Attributes
int tile = 1820
int mat = -1
RenderData data
SourcePref pref
Additional Inherited Members
Static Public Attributes inherited from EClass
static Core core
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Detailed Description
Definition at line 1 of file RendererReplacer.cs.
Member Function Documentation
CreateFrom()
static RendererReplacer RendererReplacer.CreateFrom (string id, int shift = 0, int mat = -1) inline static
Definition at line 11 of file RendererReplacer.cs.
    {
        CardRow cardRow = EClass.sources.cards.map[id];
        return new RendererReplacer
        {
            tile = cardRow._tiles[0] + shift,
            data = cardRow.renderData,
            pref = cardRow.pref,
            mat = mat
        };
    }
References RenderRow._tiles, SourceManager.cards, data, SourceCard.map, mat, pref, RenderRow.pref, RenderRow.renderData, EClass.sources, and tile.
Referenced by ConBoost.GetRendererReplacer(), ConTransmuteBat.GetRendererReplacer(), ConTransmuteBroom.GetRendererReplacer(), ConTransmuteCat.GetRendererReplacer(), ConTransmuteMimic.GetRendererReplacer(), and ConTransmutePutit.GetRendererReplacer().
Member Data Documentation
data
RenderData RendererReplacer.data
Definition at line 7 of file RendererReplacer.cs.
Referenced by Chara._CreateRenderer(), CreateFrom(), and CardRenderer.Draw().
mat
int RendererReplacer.mat = -1
Definition at line 5 of file RendererReplacer.cs.
Referenced by CreateFrom().
pref
SourcePref RendererReplacer.pref
Definition at line 9 of file RendererReplacer.cs.
Referenced by CreateFrom(), CardRenderer.Draw(), CharaRenderer.DrawHat(), and CardRenderer.GetPref().
tile
int RendererReplacer.tile = 1820
Definition at line 3 of file RendererReplacer.cs.
Referenced by CreateFrom().
The documentation for this class was generated from the following file:
Elin/RendererReplacer.cs