Elin Decompiled Documentation: DramaActor Class Reference
DramaActor Class Reference
Public Member Functions
void Init (DramaSequence _sequence, string _id, Person _owner)
void Talk (string text, List< DramaChoice > choices, bool center, bool unknown)
string ConvertAdv (string text)
Public Attributes
string id
Person owner
DramaSequence sequence
Static Public Attributes
static bool useGlitch
Static Public Attributes inherited from EMono
static Core core
Properties
DialogDrama dialog [get]
Properties inherited from EMono
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SoundManager Sound [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static CoreDebug debug [get]
Private Member Functions
void SetChoice (DramaChoice item, int index)
Private Attributes
int choiceIdx
Additional Inherited Members
Static Public Member Functions inherited from EMono
static int rnd (int a)
Detailed Description
Definition at line 5 of file DramaActor.cs.
Member Function Documentation
ConvertAdv()
string DramaActor.ConvertAdv (string text) inline
Definition at line 240 of file DramaActor.cs.
    {
        StringBuilder stringBuilder = new StringBuilder(text);
        Religion currentReligion = LayerDrama.currentReligion;
        if (currentReligion != null)
        {
            stringBuilder.Replace("#god_name", currentReligion.Name);
            stringBuilder.Replace("#god_desc", currentReligion.source.GetDetail());
            stringBuilder.Replace("#god_benefit", currentReligion.GetTextBenefit());
            stringBuilder.Replace("#godtalk_worship", currentReligion.GetGodTalk("worship"));
        }
        return stringBuilder.ToString();
    }
References LayerDrama.currentReligion, Religion.GetGodTalk(), Religion.GetTextBenefit(), Religion.Name, and Religion.source.
Referenced by SetChoice(), and Talk().
Init()
void DramaActor.Init (DramaSequence _sequence, string _id, Person _owner) inline
Definition at line 19 of file DramaActor.cs.
    {
        sequence = _sequence;
        id = _id;
        owner = _owner;
        base.gameObject.SetActive(value: false);
    }
References owner, and sequence.
Referenced by DramaSequence.AddActor().
SetChoice()
void DramaActor.SetChoice (DramaChoice item, int index) inline private
Definition at line 140 of file DramaActor.cs.
    {
        item.index = index;
        if ((!item.IF.IsEmpty() && !DramaOutcome.If(item, owner.chara)) || (item.activeCondition != null && !item.activeCondition()))
        {
            return;
        }
        DramaOutcome.idJump = null;
        string text = item.text.TrimEnd(Environment.NewLine.ToCharArray());
        text = ConvertAdv(text);
        text = GameLang.ConvertDrama(text, owner.chara);
        if (item.check != null && EMono.debug.logDice)
        {
            text = text + " (" + item.check.GetText(EMono.pc, owner.chara, inDialog: true) + ")";
        }
        Check check = null;
        string idJump = item.idJump;
        string idAction = item.idAction;
        object[] PARAMS = null;
        int? affinity = null;
        if (!item.CHECK.IsEmpty())
        {
            string[] array = item.CHECK.Split('/');
            string text2 = array[0];
            if (!(text2 == "check"))
            {
                if (text2 == "affinity")
                {
                }
            }
            else
            {
                check = Check.Get(array[1]);
            }
        }
        UIButton uIButton = dialog.AddChoice(item, text, delegate
        {
            base.gameObject.SetActive(value: false);
            DramaChoice.lastChoice = item;
            _ = check;
            if (affinity.HasValue)
            {
                bool flag = true;
                if (flag)
                {
                    idJump = idJump.Split('/')[0];
                }
                else
                {
                    idJump = idJump.Split('/')[1];
                }
                PARAMS = new object[1] { flag };
            }
            if (!idAction.IsEmpty())
            {
                typeof(DramaOutcome).GetMethod(sequence.id + "_" + idAction).Invoke(sequence.manager.outcome, PARAMS);
                if (DramaOutcome.idJump != null)
                {
                    sequence.Play(DramaOutcome.idJump);
                    return;
                }
            }
            if (item.onClick != null)
            {
                item.onClick();
            }
            sequence.tempEvents.Clear();
            if (item.onJump != null)
            {
                item.onJump();
            }
            else if (idJump.IsEmpty())
            {
                sequence.PlayNext();
            }
            else
            {
                sequence.Play(idJump);
            }
        });
        if ((bool)uIButton.subText)
        {
            uIButton.subText.SetText(choiceIdx + ".");
        }
        if (!item.sound)
        {
            uIButton.soundClick = null;
        }
        if (item.onTooltip != null)
        {
            uIButton.SetTooltip(item.onTooltip);
        }
        if (item.forceHighlight)
        {
            uIButton.DoHighlightTransition();
            item.forceHighlight = false;
        }
        choiceIdx++;
    }
References DialogDrama.AddChoice(), Person.chara, ConvertAdv(), GameLang.ConvertDrama(), EMono.debug, dialog, Check.Get(), DramaOutcome.If(), item, CoreDebug.logDice, owner, and EMono.pc.
Referenced by Talk().
Talk()
void DramaActor.Talk (string text, List< DramaChoice > choices, bool center, bool unknown) inline
Definition at line 27 of file DramaActor.cs.
    {
        Chara chara = owner.chara;
        dialog.gameObject.SetActive(value: true);
        dialog.textName.text = (unknown ? "???" : owner.GetDramaTitle());
        if ((bool)dialog.portrait)
        {
            dialog.portrait.enableFull = sequence.fullPortrait;
            dialog.portrait.SetPerson(owner);
        }
        if (!owner.HumanSpeak)
        {
            if (!text.StartsWith("("))
            {
                text = "(" + text + ")";
            }
            text = text.Replace(")", ")");
        }
        text = ConvertAdv(text);
        text = GameLang.ConvertDrama(text, owner.chara);
        if (chara != null)
        {
            if (chara.HasElement(1232))
            {
                BackerContent.GakiConvert(ref text, "babu");
            }
            else
            {
                string text2 = chara.id;
                if (!(text2 == "adv_gaki"))
                {
                    if (text2 == "corgon")
                    {
                        BackerContent.GakiConvert(ref text, "mokyu");
                    }
                }
                else
                {
                    BackerContent.GakiConvert(ref text);
                }
            }
        }
        text = text.Replace("((", "(").Replace("))", ")").Replace("", "")
            .Replace("", "");
        if ((bool)dialog.goAffinity)
        {
            dialog.layoutInterest.SetActive(chara != null);
            dialog.textNoInterest.SetActive(chara == null);
            bool flag = chara?.trait.ShowAdvRank ?? false;
            if ((bool)dialog.transFav)
            {
                dialog.transFav.SetActive(chara?.knowFav ?? false);
            }
            if ((bool)dialog.transRank)
            {
                dialog.transRank.SetActive(flag);
                if (flag)
                {
                    dialog.textRank.text = "factionRank2".lang() + " " + chara.trait.GetAdvRankText() + " " + ((chara.GetInt(111) > 0) ? "advDefeated".lang(chara.GetInt(111).ToString() ?? "") : "");
                }
            }
            if (chara != null)
            {
                dialog.textAffinity.text = ((chara.c_bossType != 0 || !chara.trait.CanChangeAffinity) ? " - " : (chara.affinity.Name + " (" + chara._affinity + ")"));
                dialog.layoutInterest.DestroyChildren();
                int num = chara.interest / 10 + 1;
                if (chara.interest <= 0)
                {
                    num = 0;
                }
                if (num > 10)
                {
                    num = 10;
                }
                for (int i = 0; i < num; i++)
                {
                    Util.Instantiate(dialog.moldInterest, dialog.layoutInterest);
                }
                dialog.layoutInterest.RebuildLayout();
                dialog.textNoInterest.SetActive(num <= 0);
                if ((bool)dialog.textFav && chara.knowFav)
                {
                    dialog.textFav.text = chara.GetFavCat().GetName().ToTitleCase() + Environment.NewLine + chara.GetFavFood().GetName().ToTitleCase();
                }
            }
            else
            {
                dialog.textAffinity.text = "???";
                dialog.textNoInterest.text = "???";
            }
        }
        if ((bool)dialog.glitch)
        {
            dialog.glitch.enabled = useGlitch;
            useGlitch = false;
        }
        dialog.SetText(text.ToTitleCase(), center);
        dialog.ClearChoice();
        choiceIdx = 1;
        for (int j = 0; j < choices.Count; j++)
        {
            SetChoice(choices[j], j);
        }
        dialog.transChoices.RebuildLayout(recursive: true);
        dialog.iconNext.SetActive(choiceIdx == 1);
        UIButton.TryHihlight();
        EMono.core.actionsNextFrame.Add(UIButton.TryHihlight);
        EMono.core.actionsNextFrame.Add(delegate
        {
            EMono.core.actionsNextFrame.Add(UIButton.TryHihlight);
        });
    }
References Chara._affinity, BaseCore.actionsNextFrame, Chara.affinity, Trait.CanChangeAffinity, Person.chara, choiceIdx, DialogDrama.ClearChoice(), ConvertAdv(), GameLang.ConvertDrama(), EMono.core, dialog, DramaSequence.fullPortrait, BackerContent.GakiConvert(), TraitChara.GetAdvRankText(), Person.GetDramaTitle(), Chara.GetFavCat(), Chara.GetFavFood(), BaseCard.GetInt(), DialogDrama.glitch, DialogDrama.goAffinity, Card.HasElement(), Person.HumanSpeak, DialogDrama.iconNext, Card.id, Chara.interest, Chara.knowFav, DialogDrama.layoutInterest, DialogDrama.moldInterest, Affinity.Name, owner, DialogDrama.portrait, sequence, SetChoice(), Portrait.SetPerson(), DialogDrama.SetText(), TraitChara.ShowAdvRank, DialogDrama.textNoInterest, Chara.trait, DialogDrama.transChoices, DialogDrama.transFav, DialogDrama.transRank, UIButton.TryHihlight(), useGlitch, and Util.
Member Data Documentation
choiceIdx
int DramaActor.choiceIdx private
Definition at line 15 of file DramaActor.cs.
Referenced by Talk().
id
string DramaActor.id
Definition at line 9 of file DramaActor.cs.
owner
Person DramaActor.owner
Definition at line 11 of file DramaActor.cs.
Referenced by Init(), SetChoice(), and Talk().
sequence
DramaSequence DramaActor.sequence
Definition at line 13 of file DramaActor.cs.
Referenced by Init(), and Talk().
useGlitch
bool DramaActor.useGlitch static
Definition at line 7 of file DramaActor.cs.
Referenced by Talk().
Property Documentation
dialog
DialogDrama DramaActor.dialog get
Definition at line 17 of file DramaActor.cs.
Referenced by SetChoice(), and Talk().
The documentation for this class was generated from the following file:
Elin/DramaActor.cs