Elin Decompiled Documentation: UIQueue Class Reference
UIQueue Class Reference
Public Member Functions
void OnAdd (Queue q, bool insert=false)
void OnRemove (Queue q)
void OnSetOwner ()
Public Attributes
LayoutGroup layout
UIButton mold
Static Public Attributes
static UIQueue Instance
Static Public Attributes inherited from EMono
static Core core
Properties
QueueManager queues [get]
Properties inherited from EMono
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SoundManager Sound [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static CoreDebug debug [get]
Private Member Functions
void OnEnable ()
void OnDisable ()
void Update ()
Additional Inherited Members
Static Public Member Functions inherited from EMono
static int rnd (int a)
Detailed Description
Definition at line 8 of file UIQueue.cs.
Member Function Documentation
OnAdd()
void UIQueue.OnAdd (Queue q, bool insert = false) inline
Definition at line 28 of file UIQueue.cs.
    {
        UIButton uibutton = q.button = Util.Instantiate<UIButton>(this.mold, this.layout);
        uibutton.onClick.AddListener(delegate()
        {
            if (q.CanCancel)
            {
                this.queues.Cancel(q);
            }
        });
        if (insert)
        {
            uibutton.transform.SetAsFirstSibling();
        }
        uibutton.tooltip.onShowTooltip = delegate(UITooltip a)
        {
            string text = q.interaction.GetType().ToString() + "\n";
            text += q.interaction.status.ToString();
            a.textMain.SetText(text);
        };
        uibutton.transform.DOScale(0f, 0.2f).From<TweenerCore<Vector3, Vector3, VectorOptions>>();
    }
References Queue.CanCancel, QueueManager.Cancel(), Queue.interaction, layout, mold, queues, AIAct.status, text, and AIAct.ToString().
Referenced by QueueManager.Add().
OnDisable()
void UIQueue.OnDisable () inline private
Definition at line 23 of file UIQueue.cs.
    {
        UIQueue.Instance = null;
    }
OnEnable()
void UIQueue.OnEnable () inline private
Definition at line 18 of file UIQueue.cs.
    {
        UIQueue.Instance = this;
    }
OnRemove()
void UIQueue.OnRemove (Queue q) inline
Definition at line 51 of file UIQueue.cs.
    {
        if (!q.button.interactable)
        {
            return;
        }
        q.button.interactable = false;
        q.button.transform.DOScale(0f, 0.3f).OnComplete(delegate
        {
            if (q.button.gameObject)
            {
                UnityEngine.Object.DestroyImmediate(q.button.gameObject);
            }
        });
    }
References Queue.button.
Referenced by QueueManager.Remove(), and Update().
OnSetOwner()
void UIQueue.OnSetOwner () inline
Definition at line 67 of file UIQueue.cs.
    {
        if (!this.mold)
        {
            this.mold = this.layout.CreateMold(null);
        }
        this.layout.DestroyChildren(false, true);
    }
References layout, and mold.
Referenced by QueueManager.SetOwner().
Update()
void UIQueue.Update () inline private
Definition at line 76 of file UIQueue.cs.
    {
        if (this.queues.list.Count > 0 && !this.queues.currentQueue.interaction.IsRunning)
        {
            this.OnRemove(this.queues.currentQueue);
        }
    }
References QueueManager.currentQueue, QueueManager.list, OnRemove(), and queues.
Member Data Documentation
Instance
UIQueue UIQueue.Instance static
Definition at line 84 of file UIQueue.cs.
layout
LayoutGroup UIQueue.layout
Definition at line 86 of file UIQueue.cs.
Referenced by OnAdd(), and OnSetOwner().
mold
UIButton UIQueue.mold
Definition at line 88 of file UIQueue.cs.
Referenced by OnAdd(), and OnSetOwner().
Property Documentation
queues
QueueManager UIQueue.queues get
Definition at line 10 of file UIQueue.cs.
    {
        get
        {
            return EMono.player.queues;
        }
    }
Referenced by OnAdd(), and Update().
The documentation for this class was generated from the following file:
Elin/UIQueue.cs