Elin Decompiled Documentation: FortuneRollData.Prize Class Reference
FortuneRollData.Prize Class Reference
Public Member Functions
int GetNum ()
void AddNote (UINote n)
Public Attributes
int grade
string id
string idRef
bool claimed
Properties
Card model [get]
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Additional Inherited Members
Static Public Member Functions inherited from EClass
static int rnd (int a)
static int curve (int a, int start, int step, int rate=75)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Static Public Attributes inherited from EClass
static Core core
Detailed Description
Definition at line 8 of file FortuneRollData.cs.
Member Function Documentation
AddNote()
void FortuneRollData.Prize.AddNote (UINote n) inline
Definition at line 65 of file FortuneRollData.cs.
        {
            string text = "_circle".lang().TagColor(EClass.sources.materials.alias[mats[grade]].GetColor()) + "  " + Lang.GetList("fortuneroll")[grade];
            string text2 = (model.IsUnique ? "★" : "") + EClass.sources.cards.map[id].GetName();
            string text3 = id;
            if (!(text3 == "panty"))
            {
                if (text3 == "mathammer")
                {
                    if (idRef.IsEmpty())
                    {
                        idRef = "iron";
                    }
                    text2 = "_of".lang(EClass.sources.materials.alias[idRef].GetName(), text2);
                }
            }
            else
            {
                string name = EClass.sources.cards.map[idRef].GetName();
                text2 = "_of".lang(name, text2);
            }
            int num = GetNum();
            if (num > 1)
            {
                text2 = text2 + " x " + num;
            }
            if (claimed)
            {
                text2 = "fortuneroll_claimed".lang();
            }
            n.AddTopic("TopicDomain", text, text2.ToTitleCase().TagColor(model.IsUnique ? FontColor.Great : FontColor.Good));
        }
References UINote.AddTopic(), SourceManager.cards, FortuneRollData.Prize.claimed, Lang.GetList(), FortuneRollData.Prize.GetNum(), FortuneRollData.Prize.grade, FortuneRollData.Prize.id, FortuneRollData.Prize.idRef, Card.IsUnique, SourceCard.map, SourceManager.materials, FortuneRollData.mats, FortuneRollData.Prize.model, and EClass.sources.
Referenced by FortuneRollData.WriteNote().
GetNum()
int FortuneRollData.Prize.GetNum () inline
Definition at line 24 of file FortuneRollData.cs.
        {
            if (id == "ration")
            {
                return 10;
            }
            if (id == "medal")
            {
                if (grade != 2)
                {
                    if (grade != 3)
                    {
                        return 1;
                    }
                    return 10;
                }
                return 3;
            }
            if (id == "plat")
            {
                if (grade != 1)
                {
                    if (grade != 2)
                    {
                        if (grade != 3)
{
                            return 1;
                        }
                        return 50;
                    }
                    return 20;
                }
                return 10;
            }
            if (id == "1165" && grade == 3)
            {
                return 3;
            }
            return 1;
        }
References FortuneRollData.Prize.grade.
Referenced by FortuneRollData.Prize.AddNote(), and FortuneRollData.GetPrize().
Member Data Documentation
claimed
bool FortuneRollData.Prize.claimed
Definition at line 20 of file FortuneRollData.cs.
Referenced by FortuneRollData.Prize.AddNote(), and FortuneRollData.GetPrize().
grade
int FortuneRollData.Prize.grade
Definition at line 11 of file FortuneRollData.cs.
Referenced by FortuneRollData.Prize.AddNote(), FortuneRollData.Prize.GetNum(), and FortuneRollData.GetPrize().
id
string FortuneRollData.Prize.id
Definition at line 14 of file FortuneRollData.cs.
Referenced by FortuneRollData.Prize.AddNote(), FortuneRollData.GetPrize(), and FortuneRollData.RefreshPrize().
idRef
string FortuneRollData.Prize.idRef
Definition at line 17 of file FortuneRollData.cs.
Referenced by FortuneRollData.Prize.AddNote(), and FortuneRollData.GetPrize().
Property Documentation
model
Card FortuneRollData.Prize.model get
Definition at line 22 of file FortuneRollData.cs.
Referenced by FortuneRollData.Prize.AddNote().
The documentation for this class was generated from the following file:
Elin/FortuneRollData.cs