Elin Decompiled Documentation: PopperManager Class Reference
PopperManager Class Reference
Public Member Functions
Popper Pop (Vector3 pos, string id, Sprite sprite)
Popper Pop (Vector3 pos, string id="Default")
Popper Pop (Func< Vector3 > func, string id="Default")
Popper Pop (Vector3 pos, Func< Vector3 > func, string id="Default")
void Kill (Popper p, bool removeFromList=true)
void KillAll ()
Public Attributes
List< Popper > list = new List<Popper>()
Detailed Description
Definition at line 6 of file PopperManager.cs.
Member Function Documentation
Kill()
void PopperManager.Kill (Popper p, bool removeFromList = true) inline
Definition at line 59 of file PopperManager.cs.
    {
        if (removeFromList)
        {
            list.Remove(p);
        }
        p.anime.onComplete.RemoveAllListeners();
        if (p.anime.onUpdate != null)
        {
            p.anime.onUpdate.RemoveAllListeners();
        }
        if (p.anime.onPlay != null)
        {
            p.anime.onPlay.RemoveAllListeners();
        }
        TweenUtil.KillTween(ref p.tweenDelay);
        PoolManager.Despawn(p);
    }
References Popper.anime, PoolManager.Despawn(), list, and Popper.tweenDelay.
Referenced by KillAll(), and Pop().
KillAll()
void PopperManager.KillAll () inline
Definition at line 78 of file PopperManager.cs.
    {
        foreach (Popper item in list)
        {
            Kill(item, removeFromList: false);
        }
        list.Clear();
    }
References item, Kill(), and list.
Pop() [1/4]
Popper PopperManager.Pop (Func< Vector3 > func, string id = "Default") inline
Definition at line 22 of file PopperManager.cs.
    {
        return Pop(func(), func, id);
    }
References Pop().
Pop() [2/4]
Popper PopperManager.Pop (Vector3 pos, Func< Vector3 > func, string id = "Default") inline
Definition at line 27 of file PopperManager.cs.
    {
        Popper p = PoolManager.Spawn<Popper>("Popper" + id, "UI/Pop/Popper" + id);
        p.SetActive(enable: true);
        if (p.useLocalPosition)
        {
            p.anime.transform.localPosition = new Vector3(p.posFix.x + p.posRandom.x * UnityEngine.Random.Range(-1f, 1f), p.posFix.y + p.posRandom.y * UnityEngine.Random.Range(-1f, 1f), p.posFix.z - 0.01f * (float)list.Count);
        }
        else
        {
            p.anime.transform.position = new Vector3(pos.x + p.posFix.x + p.posRandom.x * UnityEngine.Random.Range(-1f, 1f), pos.y + p.posFix.y + p.posRandom.y * UnityEngine.Random.Range(-1f, 1f), pos.z + p.posFix.z - 0.01f * (float)list.Count);
        }
        p.anime.onComplete.AddListener(delegate
        {
            Kill(p);
        });
        if (func != null)
        {
            p.anime.onUpdate.AddListener(delegate
            {
                p.transform.position = func();
            });
        }
        DOTweenAnimation[] componentsInChildren = p.GetComponentsInChildren<DOTweenAnimation>();
        for (int i = 0; i < componentsInChildren.Length; i++)
        {
            componentsInChildren[i].DORestart(fromHere: true);
        }
        list.Add(p);
        return p;
    }
References Popper.anime, Kill(), list, Popper.posFix, Popper.posRandom, PoolManager.Spawn(), and Popper.useLocalPosition.
Pop() [3/4]
Popper PopperManager.Pop (Vector3 pos, string id, Sprite sprite) inline
Definition at line 10 of file PopperManager.cs.
    {
        Popper popper = Pop(pos, null, id);
        popper.sr.sprite = sprite;
        return popper;
    }
References Pop().
Referenced by Card.DamageHP(), Pop(), and BaseStats.PopText().
Pop() [4/4]
Popper PopperManager.Pop (Vector3 pos, string id = "Default") inline
Definition at line 17 of file PopperManager.cs.
    {
        return Pop(pos, null, id);
    }
References Pop().
Member Data Documentation
list
List<Popper> PopperManager.list = new List<Popper>()
Definition at line 8 of file PopperManager.cs.
Referenced by Kill(), KillAll(), and Pop().
The documentation for this class was generated from the following file:
Elin/Plugins.UI/PopperManager.cs