Elin Decompiled Documentation: BackerContent Class Reference
BackerContent Class Reference
Static Public Member Functions
static string ConvertName (string s)
static void GakiConvert (ref string text, string idLang="zako")
Static Public Member Functions inherited from EClass
static int rndSeed (int a, int seed)
static int rnd (int a)
static int curve (int a, int start, int step, int rate=75)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Static Public Attributes
static int indexTree
static int indexRemain
static int indexLantern
static int indexSnail
static int indexFollower
static int indexSister
Static Public Attributes inherited from EClass
static Core core
Additional Inherited Members
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Detailed Description
Definition at line 1 of file BackerContent.cs.
Member Function Documentation
ConvertName()
static string BackerContent.ConvertName (string s) inline static
Definition at line 15 of file BackerContent.cs.
    {
        return s.Replace("『", "「");
    }
Referenced by Zone_SnowGrave.GenerateGrave(), and DramaEventEndRoll.Init().
GakiConvert()
static void BackerContent.GakiConvert (ref string text, string idLang = "zako") inline static
Definition at line 20 of file BackerContent.cs.
    {
        if (!text.IsEmpty())
        {
            if (!text.StartsWith("("))
            {
                text = idLang.lang().Split(',').RandomItem() + " (" + text + ")";
            }
            else if (idLang == "mokyu" || idLang == "babu")
            {
                text = idLang.lang().Split(',').RandomItem() + " " + text;
            }
            text = text.Replace("。)", ")");
            if (text.EndsWith("」"))
            {
                text = text.Substring(0, text.Length - 1);
            }
        }
    }
Referenced by Card.Talk(), and DramaActor.Talk().
Member Data Documentation
indexFollower
int BackerContent.indexFollower static
Definition at line 11 of file BackerContent.cs.
Referenced by Zone.TrySpawnFollower().
indexLantern
int BackerContent.indexLantern static
Definition at line 7 of file BackerContent.cs.
Referenced by TraitSpecialLantern.OnCreate().
indexRemain
int BackerContent.indexRemain static
Definition at line 5 of file BackerContent.cs.
Referenced by Map.ApplyBackerObj().
indexSister
int BackerContent.indexSister static
Definition at line 13 of file BackerContent.cs.
Referenced by Chara.OnCreate().
indexSnail
int BackerContent.indexSnail static
Definition at line 9 of file BackerContent.cs.
Referenced by Zone_Casino.OnActivate().
indexTree
int BackerContent.indexTree static
Definition at line 3 of file BackerContent.cs.
Referenced by Map.AddBackerTree(), and Map.ApplyBackerObj().
The documentation for this class was generated from the following file:
Elin/BackerContent.cs