Elin Decompiled Documentation: AI_Fuck Class Reference
AI_Fuck Class Reference
Public Types
enum FuckType { fuck , tame }
Public Types inherited from AIAct
enum Status { Running , Fail , Success }
Public Types inherited from Act
enum CostType { None , MP , SP }
Public Member Functions
override IEnumerable< Status > Run ()
void Finish ()
Public Member Functions inherited from AIAct
override string ToString ()
override MultiSprite GetStateIcon ()
virtual bool ShouldAllyAttack (Chara tg)
virtual Point GetDestination ()
AIProgress GetProgress ()
string GetCurrentActionText ()
override bool IsToolValid ()
virtual void OnStart ()
void SetOwner (Chara c)
virtual void OnSetOwner ()
void SetChild (AIAct seq, Func< Status > _onChildFail=null)
void Start ()
override bool Perform ()
Status Restart ()
Status Success (Action action=null)
virtual void OnSuccess ()
bool TryCancel (Card c)
virtual Status Cancel ()
virtual void OnCancel ()
virtual void OnCancelOrSuccess ()
virtual bool CanManualCancel ()
Status KeepRunning ()
void Reset ()
virtual void OnReset ()
Status Tick ()
virtual IEnumerable< Status > Run ()
Status TickChild ()
Status Do (AIAct _seq, Func< Status > _onChildFail=null)
Status DoGotoInteraction (Point pos, Func< Status > _onChildFail=null)
Status DoGoto (Point pos, int dist=0, bool ignoreConnection=false, Func< Status > _onChildFail=null)
Status DoGoto (Card card, Func< Status > _onChildFail=null)
Status DoGoto (Card card, int dist, Func< Status > _onChildFail=null)
Status DoGotoSpot (Card card, Func< Status > _onChildFail=null)
Status DoGoto< T > (Func< Status > _onChildFail=null)
Status DoGotoSpot< T > (Func< Status > _onChildFail=null, bool ignoreAccessType=false)
Status DoGrab (Card card, int num=-1, bool pickHeld=false, Func< Status > _onChildFail=null)
Status DoGrab< T > ()
Status DoProgress ()
Status DoIdle (int repeat=3)
Status DoWait (int count=1)
virtual AIProgress CreateProgress ()
virtual void OnCreateProgress (Progress_Custom p)
virtual bool CanProgress ()
virtual void OnBeforeProgress ()
virtual void OnProgress ()
virtual void OnProgressComplete ()
void SimulateZone (int days)
virtual void OnSimulateZone (int days)
virtual void OnSimulatePosition ()
Public Member Functions inherited from Act
virtual CursorInfo GetCursorIcon (Card c)
virtual MultiSprite GetStateIcon ()
override Sprite GetSprite ()
virtual bool ShowMouseHint (Card c)
virtual bool IsValidTC (Card c)
virtual string GetHintText (string str="")
virtual string GetText (string str="")
virtual string GetTextSmall (Card c)
bool IsTargetHostileParty ()
virtual Color GetActPlanColor ()
virtual bool Perform ()
virtual bool CanPerform ()
bool Perform (Chara _cc, Card _tc=null, Point _tp=null)
bool CanPerform (Chara _cc, Card _tc=null, Point _tp=null)
virtual bool IsToolValid ()
new void SetImage (Image image)
virtual void OnMarkMapHighlights ()
virtual bool ShouldMapHighlight (Point p)
Public Member Functions inherited from Element
virtual SourceElement.Row GetSource ()
virtual int GetSourcePotential (int v)
virtual Sprite GetSprite ()
int GetMaterialSourceValue (Thing t, int v)
virtual int GetSourceValue (int v, int lv, SourceValueType type)
virtual Sprite GetIcon (string suffix="")
bool IsActive (Card c)
int SortVal (bool charaSheet=false)
virtual bool CanLink (ElementContainer owner)
bool HasTag (string tag)
void SetImage (Image i)
virtual string GetDetail ()
bool IsFactionElement (Chara c)
Element GetParent (Card c)
void WriteNote (UINote n, ElementContainer owner=null, Action< UINote > onWriteNote=null)
void WriteNoteWithRef (UINote n, ElementContainer owner, Action< UINote > onWriteNote, Element refEle)
void _WriteNote (UINote n, Chara c, Act act)
void AddHeaderAbility (UINote n)
void _WriteNote (UINote n, ElementContainer owner, Action< UINote > onWriteNote, bool isRef, bool addHeader=true)
void AddEncNote (UINote n, Card Card, ElementContainer.NoteMode mode=ElementContainer.NoteMode.Default, Func< Element, string, string > funcText=null, Action< UINote, Element > onAddNote=null)
virtual void OnWriteNote (UINote n, ElementContainer owner)
virtual void OnChangeValue ()
void CheckLevelBonus (ElementContainer owner, UINote n=null)
int GetSortVal (UIList.SortMode m)
virtual Act.Cost GetCost (Chara c)
virtual int GetPower (Card c)
virtual void SetTextValue (UIText text)
virtual bool IsPurchaseFeatReqMet (ElementContainer owner, int lv=-1)
virtual void WritePurchaseReq (UINote n, int lv=1)
Public Attributes
Chara target
bool sell
bool bitch
bool succubus
bool ntr
int maxProgress
int progress
int totalAffinity
Public Attributes inherited from AIAct
new Chara owner
Status status
IEnumerator< Status > Enumerator
AIAct child
AIAct parent
byte restartCount
Func< Status > onChildFail
Func< bool > isFail
Public Attributes inherited from Element
SourceElement.Row _source
int id
int vBase
int vExp
int vPotential
int vTempPotential
int vLink
int vSource
int vSourcePotential
ElementContainer owner
Properties
virtual FuckType Type [get]
override bool PushChara [get]
override bool IsAutoTurn [get]
override TargetType TargetType [get]
override int MaxProgress [get]
override int CurrentProgress [get]
override bool CancelOnAggro [get]
override bool CancelWhenDamaged [get]
Properties inherited from AIAct
virtual bool IsRunning [get]
bool IsChildRunning [get]
bool IsMoveAI [get]
virtual int MaxRestart [get]
virtual new string Name [get]
virtual MultiSprite stateIcon [get]
virtual Sprite actionIcon [get]
virtual bool IsNoGoal [get]
virtual bool IsAutoTurn [get]
virtual bool IsIdle [get]
virtual bool CancelOnAggro [get]
virtual bool PushChara [get]
virtual int MaxProgress [get]
virtual bool ShowProgress [get]
virtual bool UseTurbo [get]
virtual int CurrentProgress [get]
virtual bool ShowCursor [get]
virtual bool CancelWhenDamaged [get]
virtual bool CancelWhenMoved [get]
virtual bool InformCancel [get]
virtual Thing RenderThing [get]
AIAct Current [get]
override bool IsAct [get]
override bool ShowPotential [get]
override bool UsePotential [get]
override bool ShowRelativeAttribute [get]
virtual bool HasProgress [get]
Properties inherited from Act
override bool ShowPotential [get]
override bool UsePotential [get]
override bool ShowRelativeAttribute [get]
virtual CursorInfo CursorIcon [get]
virtual string ID [get]
virtual bool IsAct [get]
virtual bool WillEndTurn [get]
virtual bool CloseLayers [get]
virtual int LeftHand [get]
virtual int RightHand [get]
virtual int ElementPowerMod [get]
virtual bool ShowMapHighlight [get]
virtual bool ShowMapHighlightBlock [get]
virtual bool PickHeldOnStart [get]
virtual bool DropHeldOnStart [get]
virtual bool CanPressRepeat [get]
virtual bool CanAutofire [get]
virtual bool ResetAxis [get]
virtual bool RequireTool [get]
virtual bool IsHostileAct [get]
virtual bool HideRightInfo [get]
virtual bool HaveLongPressAction [get]
virtual float Radius [get]
virtual int PerformDistance [get]
virtual int MaxRadius [get]
virtual TargetType TargetType [get]
virtual bool LocalAct [get]
virtual bool CanRapidFire [get]
virtual float RapidDelay [get]
virtual bool ShowAuto [get]
virtual bool IsCrime [get]
Properties inherited from Element
SourceElement.Row source [get]
virtual int DisplayValue [get]
virtual int MinValue [get]
int Value [get]
int ValueWithoutLink [get]
virtual int MinPotential [get]
int Potential [get]
virtual bool CanGainExp [get]
bool IsFlag [get]
virtual string Name [get]
virtual string FullName [get]
virtual int ExpToNext [get]
virtual bool UseExpMod [get]
virtual int CostTrain [get]
virtual int CostLearn [get]
virtual bool ShowXP [get]
virtual bool ShowMsgOnValueChanged [get]
virtual bool ShowValue [get]
virtual bool ShowPotential [get]
virtual bool UsePotential [get]
virtual bool PotentialAsStock [get]
virtual bool ShowRelativeAttribute [get]
virtual bool ShowBonuses [get]
virtual string ShortName [get]
bool IsGlobalElement [get]
bool IsFactionWideElement [get]
bool IsPartyWideElement [get]
virtual bool ShowEncNumber [get]
bool IsTrait [get]
bool IsFoodTrait [get]
bool IsFoodTraitMain [get]
bool IsMainAttribute [get]
Act act [get]
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Additional Inherited Members
Static Public Member Functions inherited from Act
static void SetReference (Chara _cc, Card _tc=null, Point _tp=null)
static void SetTool (Thing t)
Static Public Member Functions inherited from Element
static string GetName (string alias)
static SourceElement.Row Get (int id)
static Dictionary< int, int > GetElementMap (int[] list)
static Dictionary< int, int > GetElementMap (int[] list, Dictionary< int, int > map)
static SourceElement.Row GetRandomElement (int lv=1)
static Element Create (int id, int v=0)
static Element Create (string id, int v=1)
static int GetId (string alias)
static int GetResistLv (int v)
static int GetResistDamage (int dmg, int v, int power=0)
Static Public Member Functions inherited from EClass
static int rndSeed (int a, int seed)
static int rnd (int a)
static int curve (int a, int start, int step, int rate=75)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Static Public Attributes inherited from Act
static Chara CC
static Card TC
static Point TP = new Point()
static Thing TOOL
static int powerMod = 100
static bool forcePt
Static Public Attributes inherited from Element
const int Div = 5
static Element Void = new Element()
static int[] List_MainAttributes = new int[9] { 70, 72, 71, 77, 74, 75, 76, 73, 79 }
static int[] List_MainAttributesMajor = new int[8] { 70, 72, 71, 77, 74, 75, 76, 73 }
static int[] List_Body = new int[4] { 70, 72, 71, 77 }
static int[] List_Mind = new int[4] { 74, 75, 76, 73 }
static List< SourceElement.Row > ListElements = new List<SourceElement.Row>()
static List< SourceElement.Row > ListAttackElements = new List<SourceElement.Row>()
Static Public Attributes inherited from EClass
static Core core
Detailed Description
Definition at line 4 of file AI_Fuck.cs.
Member Enumeration Documentation
FuckType
enum AI_Fuck.FuckType
Enumerator
fuck
tame
Definition at line 6 of file AI_Fuck.cs.
    {
        fuck,
        tame
    }
Member Function Documentation
Finish()
void AI_Fuck.Finish () inline
Definition at line 165 of file AI_Fuck.cs.
    {
        Chara chara = (sell ? target : owner);
        Chara chara2 = (sell ? owner : target);
        if (chara.isDead || chara2.isDead)
        {
            return;
        }
        bool flag = EClass.rnd(2) == 0;
        switch (Type)
        {
        case FuckType.fuck:
        {
            for (int i = 0; i < 2; i++)
            {
                Chara chara3 = ((i == 0) ? chara : chara2);
                chara3.RemoveCondition<ConDrunk>();
                if (EClass.rnd(15) == 0 && !chara3.HasElement(1216))
                {
                    chara3.AddCondition<ConDisease>(200);
                }
                chara3.ModExp(77, 250);
                chara3.ModExp(71, 250);
                chara3.ModExp(75, 250);
            }
            if (!chara2.HasElement(1216))
            {
                if (EClass.rnd(5) == 0)
                {
                    chara2.AddCondition<ConParalyze>(500);
                }
                if (EClass.rnd(3) == 0)
                {
                    chara2.AddCondition<ConInsane>(100 + EClass.rnd(100));
                }
            }
            int num3 = CalcMoney.Whore(chara2, chara);
            chara.Talk("tail_after");
            bool flag3 = false;
            if (succubus)
            {
                chara.ShowEmo(Emo.love);
                chara2.ShowEmo(Emo.love);
                EClass.player.forceTalk = true;
                chara2.Talk("seduced");
            }
            else if (chara != EClass.pc)
            {
                Chara chara4 = chara;
                Chara chara5 = chara2;
                if (bitch)
                {
                    chara = chara5;
                    chara2 = chara4;
                }
                Debug.Log("buyer:" + chara.Name + " seller:" + chara2.Name + " money:" + num3);
                if (!chara.IsPC)
                {
                    chara.ModCurrency(EClass.rndHalf(num3));
                }
                if (!chara2.IsPC && chara.GetCurrency() < num3 && EClass.rnd(2) == 0)
                {
                    num3 = chara.GetCurrency();
                }
                Debug.Log("money:" + num3 + " buyer:" + chara.GetCurrency());
                if (chara.GetCurrency() >= num3)
                {
                    chara.Talk("tail_pay");
                }
                else
                {
                    chara.Talk("tail_nomoney");
                    num3 = chara.GetCurrency();
                    chara2.Say("angry", chara2);
                    chara2.Talk("angry");
                    flag = (sell ? true : false);
                    if (EClass.rnd(chara.IsPC ? 2 : 20) == 0)
                    {
                        flag3 = true;
                    }
                }
                chara.ModCurrency(-num3);
                if (chara2 == EClass.pc)
                {
                    if (num3 > 0)
                    {
                        EClass.player.DropReward(ThingGen.Create("money").SetNum(num3));
                        EClass.player.ModKarma(-1);
                    }
                }
                else
                {
                    int num4 = (chara2.CHA * 10 + 100) / ((chara2.IsPCFaction && chara2.memberType == FactionMemberType.Default) ? 1 : 10);
                    if (chara2.GetCurrency() - num4 > 0)
                    {
                        chara2.c_allowance += num3;
                    }
                    else
                    {
                        chara2.ModCurrency(num3);
                    }
                }
                chara = chara4;
                chara2 = chara5;
            }
            if (flag3)
            {
                chara2.DoHostileAction(chara);
            }
            if (chara.IsPCParty || chara2.IsPCParty)
            {
                chara.stamina.Mod(-5 - EClass.rnd(chara.stamina.max / 10 + (succubus ? StaminaCost(chara2, chara) : 0) + 1));
                chara2.stamina.Mod(-5 - EClass.rnd(chara2.stamina.max / 20 + (succubus ? StaminaCost(chara, chara2) : 0) + 1));
            }
            SuccubusExp(chara, chara2);
            SuccubusExp(chara2, chara);
            chara2.ModAffinity(chara, flag ? 10 : (-5));
            if (!ntr || !chara.HasElement(1239) || chara2.HasElement(1216))
            {
                break;
            }
            if (chara2.HasElement(758))
            {
                if (chara.ExistsOnMap)
                {
                    chara.stamina.Mod(-1000000);
                }
            }
            else if (chara2.ExistsOnMap)
            {
                chara2.stamina.Mod((!chara2.IsPCFaction) ? (-10000) : (chara2.IsPC ? (-25) : (-50)));
            }
            break;
        }
        case FuckType.tame:
        {
            int num = ((!chara2.IsPCFaction) ? (chara2.IsHuman ? 10 : 5) : (chara2.IsHuman ? 5 : 0));
            Msg.Say("tame_end", target);
            target.PlaySound("groomed");
            target.PlayEffect("heal_tick");
            target.hygiene.Mod(15);
            if (target == owner)
            {
                break;
            }
            if (totalAffinity > 0)
            {
                chara.Say("brush_success", target, owner);
            }
            else
            {
                chara.Say("brush_fail", target, owner);
                num *= 5;
            }
            bool num2 = TraitToolBrush.IsTamePossible(target.Chara);
            bool flag2 = num2 && chara2.affinity.CanInvite() && chara2.GetBestAttribute() < EClass.pc.CHA;
            if (num2)
            {
                if (flag2)
                {
                    chara.Say("tame_success", owner, target);
                    chara2.MakeAlly();
                }
                else
                {
                    chara.Say("tame_fail", chara, chara2);
                }
            }
            if (num > EClass.rnd(100))
            {
                chara2.DoHostileAction(chara);
                chara2.calmCheckTurn *= 3;
            }
            break;
        }
        }
        static int StaminaCost(Chara c1, Chara c2)
        {
            return (int)Mathf.Max(10f * (float)c1.END / (float)Mathf.Max(c2.END, 1), 0f);
        }
        static void SuccubusExp(Chara c, Chara tg)
        {
            if (!c.HasElement(1216))
            {
                return;
            }
            foreach (Element item in tg.elements.ListBestAttributes())
            {
                if (c.elements.ValueWithoutLink(item.id) < item.ValueWithoutLink)
                {
                    c.elements.ModTempPotential(item.id, 1 + EClass.rnd(item.ValueWithoutLink - c.elements.ValueWithoutLink(item.id) / 5 + 1));
                    c.Say("succubus_exp", c, item.Name.ToLower());
                    break;
                }
            }
        }
    }
References Chara.AddCondition(), Chara.affinity, bitch, Affinity.CanInvite(), Card.CHA, Card.Chara, ThingGen.Create(), Debug, Chara.DoHostileAction(), Player.DropReward(), Card.elements, Card.END, Card.ExistsOnMap, Card.GetBestAttribute(), Card.GetCurrency(), Card.HasElement(), Chara.hygiene, Chara.isDead, Chara.IsHuman, Chara.IsPC, Chara.IsPCFaction, Chara.IsPCParty, TraitToolBrush.IsTamePossible(), item, ElementContainer.ListBestAttributes(), Chara.MakeAlly(), Stats.max, Chara.memberType, Stats.Mod(), Chara.ModAffinity(), Card.ModCurrency(), Card.ModExp(), Player.ModKarma(), ElementContainer.ModTempPotential(), Card.Name, ntr, AIAct.owner, EClass.pc, Card.PlayEffect(), EClass.player, Card.PlaySound(), EClass.rnd(), EClass.rndHalf(), Msg.Say(), Card.Say(), sell, Card.SetNum(), Card.ShowEmo(), Chara.stamina, succubus, Card.Talk(), target, totalAffinity, Type, ElementContainer.ValueWithoutLink(), and CalcMoney.Whore().
Referenced by Run().
Run()
override IEnumerable< Status > AI_Fuck.Run () inline virtual
Reimplemented from AIAct.
Definition at line 44 of file AI_Fuck.cs.
    {
        if (target == null)
        {
            foreach (Chara chara in EClass._map.charas)
            {
                if (!chara.IsHomeMember() && !chara.IsDeadOrSleeping && chara.Dist(owner) <= 5)
                {
                    target = chara;
                    break;
                }
            }
        }
        if (target == null)
        {
            yield return Cancel();
        }
        Chara cc = (sell ? target : owner);
        Chara tc = (sell ? owner : target);
        int destDist = ((Type == FuckType.fuck) ? 1 : 1);
        yield return DoGoto(target.pos, destDist);
        cc.Say(Type.ToString() + "_start", cc, tc);
        isFail = () => !tc.IsAliveInCurrentZone || tc.Dist(owner) > 3;
        if (Type == FuckType.tame)
        {
            cc.SetTempHand(1104, -1);
        }
        maxProgress = (ntr ? 10 : 25);
        if (succubus)
        {
            cc.Talk("seduce");
        }
        for (int i = 0; i < maxProgress; i++)
        {
            progress = i;
            yield return DoGoto(target.pos, destDist);
            switch (Type)
            {
            case FuckType.fuck:
                if (ntr)
                {
                    cc.Say("ntr", cc, tc);
                }
                cc.LookAt(tc);
                tc.LookAt(cc);
                switch (i % 4)
                {
                case 0:
                    cc.renderer.PlayAnime(AnimeID.Attack, tc);
                    if (EClass.rnd(3) == 0 || sell)
                    {
                        cc.Talk("tail");
                    }
                    break;
                case 2:
                    tc.renderer.PlayAnime(AnimeID.Shiver);
                    if (EClass.rnd(3) == 0)
                    {
                        tc.Talk("tailed");
                    }
                    break;
                }
                if (EClass.rnd(3) == 0 || sell)
                {
                    target.AddCondition<ConWait>(50, force: true);
                }
                break;
            case FuckType.tame:
            {
                int num = 100;
                if (!tc.race.IsAnimal)
                {
                    num += 50;
                }
                if (tc.race.IsHuman)
                {
                    num += 50;
                }
                if (tc.IsInCombat)
                {
                    num += 100;
                }
                if (tc == cc)
                {
                    num = 50;
                }
                else if (tc.affinity.CurrentStage < Affinity.Stage.Intimate && EClass.rnd(6 * num / 100) == 0)
                {
                    tc.AddCondition<ConFear>(60);
                }
                tc.interest -= (tc.IsPCFaction ? 20 : (2 * num / 100));
                if (i == 0 || i == 10)
                {
                    cc.Talk("goodBoy");
                }
                if (i % 5 == 0)
                {
                    tc.PlaySound("brushing");
                    int num2 = cc.CHA / 2 + cc.Evalue(237) - tc.CHA * 2;
                    int num3 = ((EClass.rnd(cc.CHA / 2 + cc.Evalue(237)) <= EClass.rnd(tc.CHA * num / 100)) ? (-5 + ((!tc.IsPCFaction) ? Mathf.Clamp(num2 / 10, -30, 0) : 0)) : (5 + Mathf.Clamp(num2 / 20, 0, 20)));
                    int a = 20;
                    if (tc.IsPCFactionOrMinion && tc.affinity.CurrentStage >= Affinity.Stage.Love)
                    {
                        num3 = ((EClass.rnd(3) == 0) ? 4 : 0);
                        a = 10;
                    }
                    totalAffinity += num3;
                    tc.ModAffinity(EClass.pc, num3, show: true, showOnlyEmo: true);
                    cc.elements.ModExp(237, a);
                    if (EClass.rnd(4) == 0)
                    {
                        cc.stamina.Mod(-1);
                    }
                }
                break;
            }
            }
        }
        Finish();
    }
References EClass._map, Chara.AddCondition(), Chara.affinity, AIAct.Cancel(), Card.CHA, Map.charas, Affinity.CurrentStage, Card.Dist(), AIAct.DoGoto(), Card.elements, Card.Evalue(), Finish(), Chara.IsAliveInCurrentZone, Chara.IsDeadOrSleeping, AIAct.isFail, Chara.IsHomeMember(), Chara.IsInCombat, Chara.IsPCFaction, Card.IsPCFactionOrMinion, Chara.LookAt(), maxProgress, Stats.Mod(), Chara.ModAffinity(), ElementContainer.ModExp(), ntr, AIAct.owner, EClass.pc, CardRenderer.PlayAnime(), Card.PlaySound(), Card.pos, progress, Chara.race, Card.renderer, EClass.rnd(), Card.Say(), sell, Chara.SetTempHand(), Chara.stamina, succubus, Card.Talk(), target, totalAffinity, and Type.
Member Data Documentation
bitch
bool AI_Fuck.bitch
Definition at line 16 of file AI_Fuck.cs.
Referenced by Finish().
maxProgress
int AI_Fuck.maxProgress
Definition at line 22 of file AI_Fuck.cs.
Referenced by Run().
ntr
bool AI_Fuck.ntr
Definition at line 20 of file AI_Fuck.cs.
Referenced by Finish(), and Run().
progress
int AI_Fuck.progress
Definition at line 24 of file AI_Fuck.cs.
Referenced by Run().
sell
bool AI_Fuck.sell
Definition at line 14 of file AI_Fuck.cs.
Referenced by Finish(), and Run().
succubus
bool AI_Fuck.succubus
Definition at line 18 of file AI_Fuck.cs.
Referenced by Finish(), and Run().
target
Chara AI_Fuck.target
Definition at line 12 of file AI_Fuck.cs.
Referenced by Finish(), Run(), AI_TendAnimal.ShouldAllyAttack(), and ConSleep.SuccubusSleep().
totalAffinity
int AI_Fuck.totalAffinity
Definition at line 26 of file AI_Fuck.cs.
Referenced by Finish(), and Run().
Property Documentation
CancelOnAggro
override bool AI_Fuck.CancelOnAggro get
Definition at line 40 of file AI_Fuck.cs.
CancelWhenDamaged
override bool AI_Fuck.CancelWhenDamaged get
Definition at line 42 of file AI_Fuck.cs.
CurrentProgress
override int AI_Fuck.CurrentProgress get
Definition at line 38 of file AI_Fuck.cs.
IsAutoTurn
override bool AI_Fuck.IsAutoTurn get
Definition at line 32 of file AI_Fuck.cs.
MaxProgress
override int AI_Fuck.MaxProgress get
Definition at line 36 of file AI_Fuck.cs.
PushChara
override bool AI_Fuck.PushChara get
Definition at line 30 of file AI_Fuck.cs.
TargetType
override TargetType AI_Fuck.TargetType get
Definition at line 34 of file AI_Fuck.cs.
Type
virtual FuckType AI_Fuck.Type get
Definition at line 28 of file AI_Fuck.cs.
Referenced by Finish(), and Run().
The documentation for this class was generated from the following file:
Elin/AI_Fuck.cs