Elin Decompiled Documentation: GameBlueprint Class Reference
GameBlueprint Class Reference
Public Member Functions
override void OnCreate ()
void RerollChara ()
Public Member Functions inherited from ZoneBlueprint
void Create ()
virtual void OnCreate ()
void GenerateMap (Zone zone)
Additional Inherited Members
Static Public Member Functions inherited from EClass
static int rndSeed (int a, int seed)
static int rnd (long a)
static int rnd (int a)
static int curve (int _a, int start, int step, int rate=75)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Public Attributes inherited from ZoneBlueprint
Map map
Zone zone
ZoneProfile zoneProfile
List< Chara > charas = new List<Chara>()
List< Thing > things = new List<Thing>()
MapGenSetting genSetting
int idDebug
EloMap.TileInfo[,] surrounding
bool customMap
bool ignoreRoad
Static Public Attributes inherited from ZoneBlueprint
static int debugCount
Static Public Attributes inherited from EClass
static Core core
Properties inherited from ZoneBlueprint
EloMap.TileInfo tileCenter [get]
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Detailed Description
Definition at line 1 of file GameBlueprint.cs.
Member Function Documentation
OnCreate()
override void GameBlueprint.OnCreate () inline virtual
Reimplemented from ZoneBlueprint.
Definition at line 3 of file GameBlueprint.cs.
    {
        RerollChara();
    }
References RerollChara().
RerollChara()
void GameBlueprint.RerollChara () inline
Definition at line 8 of file GameBlueprint.cs.
    {
        charas.Clear();
        charas.Add(EClass.player.chara);
    }
References Player.chara, ZoneBlueprint.charas, and EClass.player.
Referenced by OnCreate(), and LayerEmbark.RerollMembers().
The documentation for this class was generated from the following file:
Elin/GameBlueprint.cs