Elin Decompiled Documentation: QuestTask Class Reference
QuestTask Class Reference
Public Member Functions
void SetOwner (Quest quest)
virtual bool IsComplete ()
virtual void OnInit ()
virtual void OnStart ()
virtual void OnKillChara (Chara c)
virtual void OnGiveItem (Chara c, Thing t)
virtual void OnModKarma (int a)
virtual string GetTextProgress ()
virtual void OnGetDetail (ref string detail, bool onJournal)
Public Attributes
Quest owner
Properties
virtual string RefDrama1 [get]
virtual string RefDrama2 [get]
virtual string RefDrama3 [get]
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Additional Inherited Members
Static Public Member Functions inherited from EClass
static int rndSeed (int a, int seed)
static int rnd (int a)
static int curve (int a, int start, int step, int rate=75)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Static Public Attributes inherited from EClass
static Core core
Detailed Description
Definition at line 3 of file QuestTask.cs.
Member Function Documentation
GetTextProgress()
virtual string QuestTask.GetTextProgress () inline virtual
Reimplemented in QuestTaskFlyer, QuestTaskHunt, and QuestTaskKarma.
Definition at line 44 of file QuestTask.cs.
    {
        return "";
    }
Referenced by Quest.GetTextProgress().
IsComplete()
virtual bool QuestTask.IsComplete () inline virtual
Reimplemented in QuestTaskFlyer, QuestTaskHunt, and QuestTaskKarma.
Definition at line 19 of file QuestTask.cs.
    {
        return false;
    }
Referenced by Quest.OnGiveItem(), Quest.OnKillChara(), and Quest.OnModKarma().
OnGetDetail()
virtual void QuestTask.OnGetDetail (ref string detail, bool onJournal) inline virtual
Reimplemented in QuestTaskHunt.
Definition at line 49 of file QuestTask.cs.
    {
    }
Referenced by Quest.GetDetail().
OnGiveItem()
virtual void QuestTask.OnGiveItem (Chara c, Thing t) inline virtual
Reimplemented in QuestTaskFlyer.
Definition at line 36 of file QuestTask.cs.
    {
    }
Referenced by Quest.OnGiveItem().
OnInit()
virtual void QuestTask.OnInit () inline virtual
Reimplemented in QuestTaskFlyer, QuestTaskHunt, and QuestTaskKarma.
Definition at line 24 of file QuestTask.cs.
    {
    }
Referenced by Quest.Init().
OnKillChara()
virtual void QuestTask.OnKillChara (Chara c) inline virtual
Reimplemented in QuestTaskHunt.
Definition at line 32 of file QuestTask.cs.
    {
    }
Referenced by Quest.OnKillChara().
OnModKarma()
virtual void QuestTask.OnModKarma (int a) inline virtual
Reimplemented in QuestTaskKarma.
Definition at line 40 of file QuestTask.cs.
    {
    }
Referenced by Quest.OnModKarma().
OnStart()
virtual void QuestTask.OnStart () inline virtual
Definition at line 28 of file QuestTask.cs.
    {
    }
Referenced by Quest.Start().
SetOwner()
void QuestTask.SetOwner (Quest quest) inline
Definition at line 14 of file QuestTask.cs.
    {
        owner = quest;
    }
References owner.
Referenced by Quest.SetTask().
Member Data Documentation
owner
Quest QuestTask.owner
Definition at line 6 of file QuestTask.cs.
Referenced by SetOwner().
Property Documentation
RefDrama1
virtual string QuestTask.RefDrama1 get
Definition at line 8 of file QuestTask.cs.
RefDrama2
virtual string QuestTask.RefDrama2 get
Definition at line 10 of file QuestTask.cs.
RefDrama3
virtual string QuestTask.RefDrama3 get
Definition at line 12 of file QuestTask.cs.
The documentation for this class was generated from the following file:
Elin/QuestTask.cs