Elin Decompiled Documentation: LayerAbility Class Reference
LayerAbility Class Reference
Classes
class Config
Public Member Functions
override void OnInit ()
void RefreshConfig ()
override void OnSwitchContent (Window window)
override void OnUpdateInput ()
void SelectGroup (string id)
void _Redraw ()
void OnStartDrag (UIButton b)
void OnDrag (UIButton b)
void OnEndDrag (UIButton b, bool cancel=false)
void OnDisable ()
Public Member Functions inherited from ELayer
override void OnBeforeAddLayer ()
void InitInspector ()
sealed override void Init ()
override void OnAfterAddLayer ()
void TryShowHelp ()
void AddLayerToUI (string id)
void TryShowHint (string _langHint=null)
void TalkHomeMemeber (string id)
void TalkMaid (string id)
override void OnRightClick ()
Public Member Functions inherited from Layer
virtual string GetTextHeader (Window window)
virtual bool HeaderIsListOf (int id)
virtual void Init ()
virtual void OnInit ()
virtual void OnAfterInit ()
virtual void ApplySkin ()
void ShowScreenLock (string id)
void UpdateInput ()
virtual void OnUpdateInput ()
virtual void OnRightClick ()
virtual bool OnBack ()
virtual void OnChangeLayer ()
virtual void OnCreate ()
void _AddLayer (string id)
Layer AddLayer (string id)
T AddLayer< T > ()
T AddLayer< T > (string id)
T AddLayerDontCloseOthers< T > ()
Layer AddLayerDontCloseOthers (Layer l)
T GetOrAddLayer< T > ()
virtual void OnBeforeAddLayer ()
virtual void OnAfterAddLayer ()
Layer AddLayer (Layer l)
void ToggleLayer (string id)
T ToggleLayer< T > (string id=null)
void WaitAndClose ()
void OnClickClose ()
virtual void Close ()
void CloseLayers ()
void RemoveLayers (bool removeImportant=false)
bool RemoveLayer< T > ()
void RemoveLayer (Layer l)
virtual void OnKill ()
Layer SetOnKill (Action action)
void DisableClose ()
void Delay (float duration=0.05f)
Layer SetDelay (float d)
Layer GetLayer (string id)
T GetLayer< T > (bool fromTop=false)
Layer GetTopLayer ()
void SwitchContent (int idWindow, int i)
virtual void OnSwitchContent (Window window)
Layer SetTitles (string langList, string idHeaderRow=null)
bool IsBlockWidgetClick ()
bool IsHideHud ()
bool IsAllowGeneralInput ()
bool IsUseBlur ()
bool IsPointerOnLayer ()
void ApplySkin ()
void OnStartDrag (UIButton b)
void OnDrag (UIButton b)
void OnEndDrag (UIButton b, bool cancel=false)
Static Public Member Functions
static void SetDirty (Element a)
static void ClearHotElement ()
static void Redraw ()
Static Public Member Functions inherited from ELayer
static int rnd (int a)
Static Public Member Functions inherited from Layer
static T Create< T > ()
static T Create< T > (string path)
static Layer Create (string path)
Public Attributes
UIDynamicList list
Chara chara
Transform headerRow
string[] idGroup = new string[6] { "all", "attack", "defense", "util", "ability", "favAbility" }
Public Attributes inherited from Layer
Option option
UnityEvent onKill
Anime animeIn
Anime animeOut
bool closeOthers
bool defaultActionMode = true
Button screenLock
Layer parent
string idLayer
List< Layer > layers = new List<Layer>()
Vector2 lastParentPos
List< Window > windows = new List<Window>()
string langHint
Static Public Attributes
static LayerAbility Instance
static ButtonAbility hotElement
Static Public Attributes inherited from Layer
static int skipInput
static bool closeOnRightClick
static bool rightClicked
static bool cancelKeyDown
static bool ignoreSounds
static Transform blurStopInstance
static string[] searchPath = new string[3] { "Layer", "Layer/Dialog", "Layer/LayerHome" }
Properties
new Config config [get]
Properties inherited from ELayer
static Core core [get]
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static FactionBranch Branch [get]
static Faction Home [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static CoreConfig config [get]
static GameSetting setting [get]
static ColorProfile Colors [get]
static SourceManager sources [get]
static World world [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
bool IsFloat [get]
virtual string IdHelp [get]
Properties inherited from Layer
Layer TopLayer [get]
string uid [get]
virtual RectTransform rectLayers [get]
virtual bool blockWidgetClick [get]
Additional Inherited Members
Protected Member Functions inherited from ELayer
sealed override void _Close ()
sealed override void Kill ()
Protected Member Functions inherited from Layer
virtual void Awake ()
virtual void _Close ()
virtual void Kill ()
Protected Attributes inherited from Layer
RectTransform _rect
bool isDestroyed
Detailed Description
Definition at line 5 of file LayerAbility.cs.
Member Function Documentation
_Redraw()
void LayerAbility._Redraw () inline
Definition at line 243 of file LayerAbility.cs.
    {
        list.List();
    }
References list, and UIDynamicList.List().
Referenced by Redraw().
ClearHotElement()
static void LayerAbility.ClearHotElement () inline static
Definition at line 168 of file LayerAbility.cs.
    {
        ButtonAbility buttonAbility = hotElement;
        hotElement = null;
        LayerInventory.SetDirtyAll();
        if ((bool)buttonAbility && buttonAbility.attach != null)
        {
            UnityEngine.Object.Destroy(buttonAbility.attach.gameObject);
        }
        EInput.Consume();
        ELayer.ui.hud.SetDragImage(null);
    }
References ButtonAbility.attach, EInput.Consume(), hotElement, LayerInventory.SetDirtyAll(), and ELayer.ui.
Referenced by ActionMode.UpdateInput().
OnDisable()
void LayerAbility.OnDisable () inline
Definition at line 281 of file LayerAbility.cs.
    {
        ELayer.player.pref.sortAbility = list.sortMode;
        ELayer.ui.hud.imageDrag.SetActive(enable: false);
        ELayer.ui.RemoveLayer<LayerRegisterHotbar>();
    }
References list, BaseList.sortMode, and ELayer.ui.
OnDrag()
void LayerAbility.OnDrag (UIButton b) inline
Implements IDragParent.
Definition at line 253 of file LayerAbility.cs.
    {
        ButtonAbility buttonAbility = b as ButtonAbility;
        string text = "";
        LayerRegisterHotbar layer = ELayer.ui.GetLayer<LayerRegisterHotbar>();
        if ((bool)(layer?.GetButton() ?? null))
        {
            text = "hotitemRegister";
        }
        else if (!layer)
        {
            ELayer.ui.AddLayer<LayerRegisterHotbar>().SetItem(buttonAbility.source);
        }
        ELayer.ui.hud.SetDragText(text);
    }
References LayerRegisterHotbar.GetButton(), ButtonAbility.source, and ELayer.ui.
OnEndDrag()
void LayerAbility.OnEndDrag (UIButton b, bool cancel = false) inline
Implements IDragParent.
Definition at line 269 of file LayerAbility.cs.
    {
        ELayer.ui.hud.imageDrag.SetActive(enable: false);
        _ = (b as ButtonAbility).source;
        LayerRegisterHotbar layer = ELayer.ui.GetLayer<LayerRegisterHotbar>();
        if ((bool)layer)
        {
            layer.OnEndDrag();
            ELayer.ui.RemoveLayer<LayerRegisterHotbar>();
        }
    }
References LayerRegisterHotbar.OnEndDrag(), and ELayer.ui.
OnInit()
override void LayerAbility.OnInit () inline virtual
Reimplemented from Layer.
Definition at line 36 of file LayerAbility.cs.
    {
        chara = ELayer.pc;
        string[] array = idGroup;
        foreach (string text in array)
        {
            windows[0].AddTab("cat_" + text, windows[0].CurrentContent);
        }
        Instance = this;
        list.sortMode = ELayer.player.pref.sortAbility;
        if (ELayer.game.altAbility)
        {
            UIButton buttonSort = windows[0].buttonSort;
            buttonSort.onClick.RemoveAllListeners();
            buttonSort.onClick.AddListener(delegate
            {
                UIContextMenu uIContextMenu = ELayer.ui.CreateContextMenuInteraction();
                uIContextMenu.layoutGroup.childAlignment = TextAnchor.UpperLeft;
                uIContextMenu.alwaysPopLeft = true;
                UIContextMenu uIContextMenu2 = uIContextMenu.AddChild("sort", TextAnchor.UpperRight);
                UIList.SortMode[] sorts = list.sorts;
                for (int j = 0; j < sorts.Length; j++)
                {
                    UIList.SortMode sortMode = sorts[j];
                    string text2 = ((list.sortMode == sortMode) ? "context_checker".lang() : "");
                    UIList.SortMode _sort = sortMode;
                    uIContextMenu2.AddButton(text2 + sortMode.ToString().lang(), delegate
                    {
                        list.List(_sort);
                        SE.Click();
                    });
                }
                UIContextMenu uIContextMenu3 = uIContextMenu.AddChild("config", TextAnchor.UpperRight);
                uIContextMenu3.AddSlider("alpha", (float a) => a.ToString() ?? "", config.bgAlpha, delegate(float b)
                {
                    config.bgAlpha = (int)b;
                    RefreshConfig();
                }, 0f, 100f, isInt: true, hideOther: false);
                uIContextMenu3.AddToggle("autoHideBG", config.autoHideBG, delegate(bool a)
                {
                    config.autoHideBG = a;
                    RefreshConfig();
                });
                uIContextMenu3.AddToggle("hideDepletedSpell", config.hideDepletedSpell, delegate(bool a)
                {
                    config.hideDepletedSpell = a;
                    list.List();
                });
                uIContextMenu3.AddToggle("fixedSize", config.fixedSize, delegate(bool a)
                {
                    config.fixedSize = a;
                    RefreshConfig();
                });
                uIContextMenu3.AddToggle("fixedPos", config.fixedPos, delegate(bool a)
                {
                    config.fixedPos = a;
                    RefreshConfig();
                });
                uIContextMenu.Show();
            });
        }
        windows[0].idTab = ELayer.player.pref.lastIdTabAbility;
        RefreshConfig();
    }
References UIContextMenu.AddButton(), UIContextMenu.AddChild(), UIContextMenu.AddSlider(), UIContextMenu.AddToggle(), Game.altAbility, LayerAbility.Config.autoHideBG, LayerAbility.Config.bgAlpha, chara, config, LayerAbility.Config.fixedPos, LayerAbility.Config.fixedSize, ELayer.game, LayerAbility.Config.hideDepletedSpell, idGroup, Instance, Player.Pref.lastIdTabAbility, list, UIDynamicList.List(), ELayer.pc, ELayer.player, Player.pref, RefreshConfig(), UIContextMenu.Show(), Player.Pref.sortAbility, BaseList.sorts, ELayer.ui, and Layer.windows.
OnStartDrag()
void LayerAbility.OnStartDrag (UIButton b) inline
Implements IDragParent.
Definition at line 248 of file LayerAbility.cs.
    {
        ELayer.ui.hud.SetDragImage(b.icon);
    }
References UIButton.icon, and ELayer.ui.
OnSwitchContent()
override void LayerAbility.OnSwitchContent (Window window) inline virtual
Reimplemented from Layer.
Definition at line 147 of file LayerAbility.cs.
    {
        ELayer.player.pref.lastIdTabAbility = window.idTab;
        SelectGroup(windows[0].setting.tabs[window.idTab].idLang.Replace("cat_", ""));
    }
References Window.idTab, SelectGroup(), ELayer.setting, and Layer.windows.
OnUpdateInput()
override void LayerAbility.OnUpdateInput () inline virtual
Reimplemented from Layer.
Definition at line 153 of file LayerAbility.cs.
    {
        if (EInput.middleMouse.down)
        {
            ButtonAbility componentOf = InputModuleEX.GetComponentOf<ButtonAbility>();
            if ((bool)componentOf)
            {
                ELayer.player.SetCurrentHotItem(new HotItemAct(componentOf.source));
                SE.SelectHotitem();
                return;
            }
        }
        base.OnUpdateInput();
    }
References ButtonState.down, EInput.middleMouse, ELayer.player, Player.SetCurrentHotItem(), and ButtonAbility.source.
Redraw()
static void LayerAbility.Redraw () inline static
Definition at line 235 of file LayerAbility.cs.
    {
        if ((bool)Instance)
        {
            Instance._Redraw();
        }
    }
References _Redraw(), and Instance.
Referenced by ElementContainerCard.CheckSkillActions(), and TraitBaseSpellbook.OnRead().
RefreshConfig()
void LayerAbility.RefreshConfig () inline
Definition at line 101 of file LayerAbility.cs.
    {
        Window window = windows[0];
        window.imageBG.color = Color.white.SetAlpha(0.01f * (float)config.bgAlpha);
        window.listCgFloat.Clear();
        if (config.autoHideBG)
        {
            window.listCgFloat.Add(window.cgBG);
        }
        window.cgBG.enabled = config.autoHideBG;
        window.setting.allowMove = !config.fixedPos;
        window.setting.allowResize = !config.fixedSize;
    }
References LayerAbility.Config.autoHideBG, LayerAbility.Config.bgAlpha, Window.cgBG, Color, config, LayerAbility.Config.fixedPos, LayerAbility.Config.fixedSize, Window.listCgFloat, and Layer.windows.
Referenced by OnInit().
SelectGroup()
void LayerAbility.SelectGroup (string id) inline
Definition at line 181 of file LayerAbility.cs.
    {
        list.Clear();
        list.callbacks = new UIList.Callback<Element, ButtonAbility>
        {
            onClick = delegate(Element a, ButtonAbility b)
            {
                if (ELayer.ui.IsActive)
                {
                    SE.BeepSmall();
                }
                else
                {
                    SE.Equip();
                    hotElement = b;
                    b.attach = Util.Instantiate("UI/Element/Grid/Attach/guide_ability", b.transform);
                    LayerInventory.SetDirtyAll();
                    ELayer.ui.hud.SetDragImage(b.icon);
                }
            },
            onRedraw = delegate(Element a, ButtonAbility b, int i)
            {
                b.dragParent = this;
                b.SetAct(chara, a);
            },
            onList = delegate(UIList.SortMode m)
            {
                ELayer.player.pref.sortAbility = m;
                List<Element> list = new List<Element>();
                foreach (Element value in ELayer.pc.elements.dict.Values)
                {
                    string categorySub = value.source.categorySub;
                    if (value.Value != 0 && (!config.hideDepletedSpell || !value.PotentialAsStock || value.vPotential > 0))
                    {
                        if (id == "favAbility" && ELayer.player.favAbility.Contains(value.id))
{
                            list.Add(value);
                        }
                        else if (id == categorySub || (id == "all" && idGroup.Contains(categorySub)))
{
                            list.Add(value);
                        }
                    }
                }
                list.Sort((Element a, Element b) => a.GetSortVal(m) - b.GetSortVal(m));
                foreach (Element item in list)
                {
                    this.list.Add(item);
                }
            }
        };
        list.List();
    }
References UIDynamicList.Add(), chara, UIDynamicList.Clear(), config, ElementContainer.dict, Card.elements, Player.favAbility, Element.GetSortVal(), LayerAbility.Config.hideDepletedSpell, hotElement, UIButton.icon, Element.id, idGroup, item, list, UIDynamicList.List(), ELayer.pc, ELayer.player, Element.PotentialAsStock, ButtonAbility.SetAct(), LayerInventory.SetDirtyAll(), Element.source, ELayer.ui, Util, Element.Value, and Element.vPotential.
Referenced by OnSwitchContent().
SetDirty()
static void LayerAbility.SetDirty (Element a) inline static
Definition at line 115 of file LayerAbility.cs.
    {
        if ((bool)Instance)
        {
            Instance.list.Redraw();
        }
        foreach (LayerInventory item in LayerInventory.listInv)
        {
            foreach (UIList.ButtonPair button in item.invs[0].list.buttons)
            {
                ButtonGrid buttonGrid = button.component as ButtonGrid;
                if (buttonGrid.card != null && buttonGrid.card.trait is TraitAbility)
                {
                    item.invs[0].list.callbacks.OnRedraw(buttonGrid.card, buttonGrid, buttonGrid.index);
                }
            }
        }
        if (!WidgetCurrentTool.Instance)
        {
            return;
        }
        foreach (UIList.ButtonPair button2 in WidgetCurrentTool.Instance.list.buttons)
        {
            ButtonGrid buttonGrid2 = button2.component as ButtonGrid;
            if (buttonGrid2.card != null && buttonGrid2.card.trait is TraitAbility)
            {
                WidgetCurrentTool.Instance.list.callbacks.OnRedraw(buttonGrid2.card, buttonGrid2, buttonGrid2.index);
            }
        }
        WidgetCurrentTool.RefreshCurrentHotItem();
    }
References UIList.buttons, BaseList.callbacks, ButtonGrid.card, ButtonGrid.index, Instance, WidgetCurrentTool.Instance, item, list, WidgetCurrentTool.list, LayerInventory.listInv, UIDynamicList.Redraw(), WidgetCurrentTool.RefreshCurrentHotItem(), and Card.trait.
Referenced by Chara.GainAbility(), Ability.OnChangeValue(), and Chara.UseAbility().
Member Data Documentation
chara
Chara LayerAbility.chara
Definition at line 27 of file LayerAbility.cs.
Referenced by OnInit(), and SelectGroup().
headerRow
Transform LayerAbility.headerRow
Definition at line 29 of file LayerAbility.cs.
hotElement
ButtonAbility LayerAbility.hotElement static
Definition at line 23 of file LayerAbility.cs.
Referenced by ClearHotElement(), SelectGroup(), LayerInventory.TryShowGuide(), and ActionMode.UpdateInput().
idGroup
string [] LayerAbility.idGroup = new string[6] { "all", "attack", "defense", "util", "ability", "favAbility" }
Definition at line 32 of file LayerAbility.cs.
Referenced by OnInit(), and SelectGroup().
Instance
LayerAbility LayerAbility.Instance static
Definition at line 21 of file LayerAbility.cs.
Referenced by OnInit(), Scene.OnUpdate(), Redraw(), SetDirty(), and ButtonAbility.ToggleFav().
list
UIDynamicList LayerAbility.list
Definition at line 25 of file LayerAbility.cs.
Referenced by _Redraw(), OnDisable(), OnInit(), SelectGroup(), SetDirty(), and ButtonAbility.ToggleFav().
Property Documentation
config
new Config LayerAbility.config get
Definition at line 34 of file LayerAbility.cs.
Referenced by OnInit(), RefreshConfig(), and SelectGroup().
The documentation for this class was generated from the following file:
Elin/LayerAbility.cs