Elin Decompiled Documentation: TaskList< T > Class Template Reference
TaskList< T > Class Template Reference
Public Member Functions
virtual Task GetTask (Chara chara, int radius=-1)
virtual void OnLoad ()
virtual void SetAstLastItem (Task t)
virtual bool TryAdd (Task t)
virtual void Remove (Task t)
override bool TryAdd (Task t)
override void Remove (Task t)
override void SetAstLastItem (Task t)
override void OnLoad ()
virtual void OnAdd (T t)
virtual void SetAstLastItem (T t)
override Task GetTask (Chara chara, int radius=-1)
bool HaveTask (Point p)
void DestroyAll< T1 > ()
void DestroyAll (Func< T, bool > func)
Public Attributes
List< T > items = new List<T>()
Protected Member Functions
virtual bool TryAdd (T t)
virtual void Remove (T t)
Additional Inherited Members
Static Public Member Functions inherited from EClass
static int rndSeed (int a, int seed)
static int rnd (int a)
static int curve (int a, int start, int step, int rate=75)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Static Public Attributes inherited from EClass
static Core core
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Detailed Description
Type Constraints
T : Task
Definition at line 29 of file TaskList.cs.
Member Function Documentation
DestroyAll()
void TaskList< T >.DestroyAll (Func< T, bool > func) inline
Definition at line 120 of file TaskList.cs.
    {
        foreach (T item in items.Copy())
        {
            if (func(item))
            {
                item.Destroy();
            }
        }
    }
References item, and TaskList< T >.items.
DestroyAll< T1 >()
void TaskList< T >.DestroyAll< T1 > () inline
Type Constraints
T1 : T
Definition at line 109 of file TaskList.cs.
                                          : T
    {
        foreach (T item in items.Copy())
        {
            if (item is T1)
            {
                item.Destroy();
            }
        }
    }
References item, and TaskList< T >.items.
GetTask() [1/2]
virtual Task TaskList< T >.GetTask (Chara chara, int radius = -1) inline virtual
Reimplemented in QueueList< T >.
Definition at line 7 of file TaskList.cs.
    {
        return null;
    }
Referenced by GoalTask.TryAssignAreaTask(), and GoalTask.TryAssignTask().
GetTask() [2/2]
override Task TaskList< T >.GetTask (Chara chara, int radius = -1) inline
Definition at line 81 of file TaskList.cs.
    {
        if (items.Count == 0)
        {
            return null;
        }
        foreach (T item in items)
        {
            if (item.owner == null && item.nextTry <= EClass.game.sessionMin && item.CanPerformTask(chara, radius))
            {
                return item;
            }
        }
        return null;
    }
References EClass.game, item, TaskList< T >.items, and Game.sessionMin.
HaveTask()
bool TaskList< T >.HaveTask (Point p) inline
Definition at line 97 of file TaskList.cs.
    {
        foreach (T item in items)
        {
            if ((item as TaskPoint).pos.Equals(p))
            {
                return true;
            }
        }
        return false;
    }
References item, and TaskList< T >.items.
OnAdd()
virtual void TaskList< T >.OnAdd (T t) inline virtual
Reimplemented in DesignationList< T >.
Definition at line 65 of file TaskList.cs.
    {
        t.taskList = this;
    }
Referenced by TaskList< T >.OnLoad(), and TaskList< T >.TryAdd().
OnLoad() [1/2]
virtual void TaskList< T >.OnLoad () inline virtual
Definition at line 12 of file TaskList.cs.
    {
    }
Referenced by Area.OnLoad().
OnLoad() [2/2]
override void TaskList< T >.OnLoad () inline
Definition at line 49 of file TaskList.cs.
    {
        foreach (T item in items)
        {
            OnAdd(item);
        }
    }
References item, TaskList< T >.items, and TaskList< T >.OnAdd().
Remove() [1/3]
virtual void TaskList< T >.Remove (T t) inline protected virtual
Reimplemented in DesignationList< T >.
Definition at line 70 of file TaskList.cs.
    {
        items.Remove(t);
    }
References TaskList< T >.items.
Remove() [2/3]
virtual void TaskList< T >.Remove (Task t) inline virtual
Definition at line 25 of file TaskList.cs.
    {
    }
Referenced by Task.Destroy(), and TaskList< T >.Remove().
Remove() [3/3]
override void TaskList< T >.Remove (Task t) inline
Definition at line 39 of file TaskList.cs.
    {
        Remove(t as T);
    }
References TaskList< T >.Remove().
SetAstLastItem() [1/3]
virtual void TaskList< T >.SetAstLastItem (T t) inline virtual
Definition at line 75 of file TaskList.cs.
    {
        items.Remove(t);
        items.Add(t);
    }
References TaskList< T >.items.
SetAstLastItem() [2/3]
virtual void TaskList< T >.SetAstLastItem (Task t) inline virtual
Definition at line 16 of file TaskList.cs.
    {
    }
Referenced by Task.OnReset(), and TaskList< T >.SetAstLastItem().
SetAstLastItem() [3/3]
override void TaskList< T >.SetAstLastItem (Task t) inline
Definition at line 44 of file TaskList.cs.
    {
        SetAstLastItem(t as T);
    }
References TaskList< T >.SetAstLastItem().
TryAdd() [1/3]
virtual bool TaskList< T >.TryAdd (T t) inline protected virtual
Reimplemented in DesignationList< T >.
Definition at line 57 of file TaskList.cs.
    {
        items.Add(t);
        OnAdd(t);
        t.OnAdd();
        return true;
    }
References TaskList< T >.items, and TaskList< T >.OnAdd().
TryAdd() [2/3]
virtual bool TaskList< T >.TryAdd (Task t) inline virtual
Definition at line 20 of file TaskList.cs.
    {
        return false;
    }
Referenced by TaskList< T >.TryAdd().
TryAdd() [3/3]
override bool TaskList< T >.TryAdd (Task t) inline
Definition at line 34 of file TaskList.cs.
    {
        return TryAdd(t as T);
    }
References TaskList< T >.TryAdd().
Member Data Documentation
items
List<T> TaskList< T >.items = new List<T>()
Definition at line 32 of file TaskList.cs.
Referenced by TaskList< T >.DestroyAll(), TaskList< T >.DestroyAll< T1 >(), QueueList< T >.GetTask(), TaskList< T >.GetTask(), TaskList< T >.HaveTask(), TaskList< T >.OnLoad(), Area.OnRemove(), TaskList< T >.Remove(), TaskList< T >.SetAstLastItem(), and TaskList< T >.TryAdd().
The documentation for this class was generated from the following file:
Elin/TaskList.cs