Elin Decompiled Documentation: ContentPopulation Class Reference
ContentPopulation Class Reference
Classes
class Topic
Public Member Functions
override void OnSwitchContent (int idTab)
void Refresh ()
void Add (string idTopic, Chara c, int color=1, int sortVal=0)
Public Member Functions inherited from UIContent
virtual void OnSwitchContent (int idTab)
virtual void OnInstantiate ()
Public Member Functions inherited from UINote
void Clear ()
void Build ()
void Space (int sizeY=0, int sizeX=1)
UINote AddNote (string id)
UIItem AddHeader (string text, Sprite sprite=null)
UIItem AddHeaderCard (string text, Sprite sprite=null)
UIItem AddHeaderTopic (string text, Sprite sprite=null)
UIItem AddHeader (string id, string text, Sprite sprite=null)
UIItem AddText (string text, FontColor color=FontColor.DontChange)
UIItem AddText (string id, string text, FontColor color=FontColor.DontChange)
UIItem AddText (string id, string text, Color color)
UIItem AddItem (string id)
UIItem AddTopic (string id, string text, string value=null)
UIItem AddTopic (string text, string value=null)
void AddImage (Sprite sprite)
void AddImage (string idFile)
UIButton AddButton (string text, Action onClick)
UIButton AddButtonLink (string text, string url)
UIDropdown AddDropdown (string id="DropdownDefault")
UIButton AddToggle (string idLang="", bool isOn=false, Action< bool > action=null)
Transform AddPrefab (string path)
T AddExtra< T > (string path)
Public Attributes
Color[] colors
UIList list
UISelectableGroup groupQueryTarget
UISelectableGroup groupQueryType
Dictionary< string, Topic > topics
Func< Topic, UIList.SortMode, int > onSort
Public Attributes inherited from UINote
RectTransform target
UINoteProfile prof
SkinType skinType
string idDefaultText
LayoutGroup layout
RectTransform cur
bool extraRebuild
Static Public Attributes
static ContentPopulation Instance
static int queryTarget
static int queryType
Detailed Description
Definition at line 5 of file ContentPopulation.cs.
Member Function Documentation
Add()
void ContentPopulation.Add (string idTopic, Chara c, int color = 1, int sortVal = 0) inline
Definition at line 121 of file ContentPopulation.cs.
    {
        Topic topic = topics.TryGetValue(idTopic);
        if (topic == null)
        {
            topic = new Topic
            {
                header = idTopic,
                color = color,
                sortVal = sortVal
            };
            topics.Add(idTopic, topic);
            list.Add(topic);
        }
        topic.list.Add(c);
    }
References UIList.Add(), ContentPopulation.Topic.list, list, and topics.
Referenced by Refresh().
OnSwitchContent()
override void ContentPopulation.OnSwitchContent (int idTab) inline virtual
Reimplemented from UIContent.
Definition at line 36 of file ContentPopulation.cs.
    {
        Instance = this;
        groupQueryTarget.Init(queryTarget, delegate(int a)
        {
            queryTarget = a;
            Refresh();
        });
        groupQueryType.Init(queryType, delegate(int a)
        {
            queryType = a;
            Refresh();
        });
        Refresh();
    }
References groupQueryTarget, groupQueryType, UISelectableGroup.Init(), Instance, queryTarget, queryType, and Refresh().
Refresh()
void ContentPopulation.Refresh () inline
Definition at line 52 of file ContentPopulation.cs.
    {
        this.list.Clear();
        this.list.callbacks = new UIList.Callback<Topic, ItemPopulation>
        {
            onInstantiate = delegate(Topic a, ItemPopulation b)
            {
                b.SetTopic(a);
            },
            onSort = onSort
        };
        onSort = (Topic t, UIList.SortMode m) => -this.list.items.IndexOf(t) + t.sortVal * 100;
        topics = new Dictionary<string, Topic>();
        List<Chara> list = EClass._map.ListChara((queryTarget == 0) ? EClass.Home : EClass.game.factions.Wilds);
        switch (queryType)
        {
        case 0:
            foreach (Chara item in list)
            {
                if (item.happiness > 70)
                {
                    Add("happy".lang(), item, 1, 10);
                }
                else if (item.happiness > 30)
                {
                    Add("normal".lang(), item, 0, 5);
                }
                else
                {
                    Add("unhappy".lang(), item, 2);
                }
            }
            break;
        case 1:
            foreach (Chara item2 in list)
            {
                Add("noJob".lang(), item2, 2);
            }
            break;
        case 2:
            foreach (Chara item3 in list)
            {
                Add("houseless".lang(), item3, 2);
            }
            break;
        case 3:
            foreach (Chara item4 in list)
            {
                Add(item4.faith.Name, item4);
            }
            onSort = (Topic t, UIList.SortMode m) => t.list.Count * 1000 - this.list.items.IndexOf(t);
            break;
        case 4:
            foreach (Chara item5 in list)
            {
                Add("querySingle".lang(), item5, 2);
            }
            break;
        default:
            foreach (Chara item6 in list)
            {
                Add("test", item6);
            }
            break;
        }
        this.list.Refresh();
        this.RebuildLayout(recursive: true);
    }
References EClass._map, Add(), UIList.Clear(), Game.factions, Chara.faith, EClass.game, EClass.Home, item, UIList.items, ContentPopulation.Topic.list, list, Map.ListChara(), Religion.Name, onSort, queryTarget, queryType, ItemPopulation.SetTopic(), topics, and FactionManager.Wilds.
Referenced by OnSwitchContent().
Member Data Documentation
colors
Color [] ContentPopulation.colors
Definition at line 24 of file ContentPopulation.cs.
Referenced by ItemPopulation.SetTopic().
groupQueryTarget
UISelectableGroup ContentPopulation.groupQueryTarget
Definition at line 28 of file ContentPopulation.cs.
Referenced by OnSwitchContent().
groupQueryType
UISelectableGroup ContentPopulation.groupQueryType
Definition at line 30 of file ContentPopulation.cs.
Referenced by OnSwitchContent().
Instance
ContentPopulation ContentPopulation.Instance static
Definition at line 18 of file ContentPopulation.cs.
Referenced by OnSwitchContent(), and ItemPopulation.SetTopic().
list
UIList ContentPopulation.list
Definition at line 26 of file ContentPopulation.cs.
Referenced by Add(), and Refresh().
onSort
Func<Topic, UIList.SortMode, int> ContentPopulation.onSort
Definition at line 34 of file ContentPopulation.cs.
Referenced by Refresh().
queryTarget
int ContentPopulation.queryTarget static
Definition at line 20 of file ContentPopulation.cs.
Referenced by OnSwitchContent(), and Refresh().
queryType
int ContentPopulation.queryType static
Definition at line 22 of file ContentPopulation.cs.
Referenced by OnSwitchContent(), and Refresh().
topics
Dictionary<string, Topic> ContentPopulation.topics
Definition at line 32 of file ContentPopulation.cs.
Referenced by Add(), and Refresh().
The documentation for this class was generated from the following file:
Elin/ContentPopulation.cs