Elin Decompiled Documentation: Empyrean.ColorPicker.ColorPalette Class Reference
Empyrean.ColorPicker.ColorPalette Class Reference
Public Member Functions
void SelectColor (HSVColor hsv)
void OnPointerDown (PointerEventData eventData)
void OnDrag (PointerEventData eventData)
void OnInitializePotentialDrag (PointerEventData ped)
void UpdateMarkerPosition (HSVColor hsv)
void ShowEnlargedPixels (Color[] colors)
void ShowDropperMarker (bool value)
Properties
Vector2 MarkerPosition [get]
Events
Action< Vector2 > ColorPicked
Private Member Functions
void Awake ()
void Init ()
Vector2 GetNormalisedPointerPosition (Vector2 position)
Vector2 GetClampedLocalPosition (Vector2 position)
void GeneratePaletteTexture (HSVColor hsv)
void SetMarkerPosition (Vector2 position)
Private Attributes
HSVColor current
Color[] colorArray
Texture2D texture
RawImage paletteImage
RectTransform marker
RectTransform dropperSelectionMarker
bool initiated
Detailed Description
Definition at line 9 of file ColorPalette.cs.
Member Function Documentation
Awake()
void Empyrean.ColorPicker.ColorPalette.Awake () inline private
Definition at line 34 of file ColorPalette.cs.
    {
        Init();
    }
References Empyrean.ColorPicker.ColorPalette.Init().
GeneratePaletteTexture()
void Empyrean.ColorPicker.ColorPalette.GeneratePaletteTexture (HSVColor hsv) inline private
Definition at line 90 of file ColorPalette.cs.
    {
        current = hsv;
        int width = texture.width;
        for (int i = 0; i < width; i++)
        {
            for (int num = width - 1; num > 0; num--)
            {
                colorArray[i * width - 1 + num] = Colorist.HSVtoRGB(current.h, (float)num / (float)width, (float)i / (float)width);
            }
        }
        texture.SetPixels(colorArray);
        texture.Apply();
        paletteImage.texture = texture;
    }
References Empyrean.ColorPicker.ColorPalette.colorArray, Empyrean.ColorPicker.ColorPalette.current, HSVColor.h, Empyrean.Utils.Colorist.HSVtoRGB(), and Empyrean.ColorPicker.ColorPalette.texture.
Referenced by Empyrean.ColorPicker.ColorPalette.SelectColor().
GetClampedLocalPosition()
Vector2 Empyrean.ColorPicker.ColorPalette.GetClampedLocalPosition (Vector2 position) inline private
Definition at line 82 of file ColorPalette.cs.
    {
        Vector3 vector = paletteImage.gameObject.transform.InverseTransformPoint(position);
        vector.x = Mathf.Clamp(vector.x, 0f, paletteImage.rectTransform.rect.width);
        vector.y = Mathf.Clamp(vector.y, 0f, paletteImage.rectTransform.rect.height);
        return vector;
    }
References Empyrean.ColorPicker.ColorPalette.paletteImage.
Referenced by Empyrean.ColorPicker.ColorPalette.GetNormalisedPointerPosition().
GetNormalisedPointerPosition()
Vector2 Empyrean.ColorPicker.ColorPalette.GetNormalisedPointerPosition (Vector2 position) inline private
Definition at line 71 of file ColorPalette.cs.
    {
        Vector2 clampedLocalPosition = GetClampedLocalPosition(position);
        return new Vector2(clampedLocalPosition.x / paletteImage.rectTransform.rect.width, clampedLocalPosition.y / paletteImage.rectTransform.rect.height);
    }
References Empyrean.ColorPicker.ColorPalette.GetClampedLocalPosition(), and Empyrean.ColorPicker.ColorPalette.paletteImage.
Referenced by Empyrean.ColorPicker.ColorPalette.OnDrag().
Init()
void Empyrean.ColorPicker.ColorPalette.Init () inline private
Definition at line 39 of file ColorPalette.cs.
    {
        if (!initiated)
        {
            initiated = true;
            int width = paletteImage.mainTexture.width;
            int height = paletteImage.mainTexture.height;
            texture = new Texture2D(width, height, TextureFormat.RGB24, mipChain: false);
            colorArray = new Color[width * height];
        }
    }
References Color, Empyrean.ColorPicker.ColorPalette.colorArray, Empyrean.ColorPicker.ColorPalette.initiated, Empyrean.ColorPicker.ColorPalette.paletteImage, and Empyrean.ColorPicker.ColorPalette.texture.
Referenced by Empyrean.ColorPicker.ColorPalette.Awake(), and Empyrean.ColorPicker.ColorPalette.SelectColor().
OnDrag()
void Empyrean.ColorPicker.ColorPalette.OnDrag (PointerEventData eventData) inline
Definition at line 66 of file ColorPalette.cs.
    {
        this.ColorPicked(GetNormalisedPointerPosition(eventData.position));
    }
References Empyrean.ColorPicker.ColorPalette.ColorPicked, and Empyrean.ColorPicker.ColorPalette.GetNormalisedPointerPosition().
Referenced by Empyrean.ColorPicker.ColorPalette.OnPointerDown().
OnInitializePotentialDrag()
void Empyrean.ColorPicker.ColorPalette.OnInitializePotentialDrag (PointerEventData ped) inline
Definition at line 77 of file ColorPalette.cs.
    {
        ped.useDragThreshold = false;
    }
OnPointerDown()
void Empyrean.ColorPicker.ColorPalette.OnPointerDown (PointerEventData eventData) inline
Definition at line 61 of file ColorPalette.cs.
    {
        OnDrag(eventData);
    }
References Empyrean.ColorPicker.ColorPalette.OnDrag().
SelectColor()
void Empyrean.ColorPicker.ColorPalette.SelectColor (HSVColor hsv) inline
Definition at line 51 of file ColorPalette.cs.
    {
        Init();
        if (Mathf.Approximately(current.h, current.h))
        {
            GeneratePaletteTexture(hsv);
        }
        UpdateMarkerPosition(hsv);
    }
References Empyrean.ColorPicker.ColorPalette.current, Empyrean.ColorPicker.ColorPalette.GeneratePaletteTexture(), HSVColor.h, Empyrean.ColorPicker.ColorPalette.Init(), and Empyrean.ColorPicker.ColorPalette.UpdateMarkerPosition().
Referenced by Empyrean.ColorPicker.ColorPicker.UpdateColorPicker().
SetMarkerPosition()
void Empyrean.ColorPicker.ColorPalette.SetMarkerPosition (Vector2 position) inline private
Definition at line 111 of file ColorPalette.cs.
    {
        marker.anchorMin = position;
        marker.anchorMax = position;
    }
Referenced by Empyrean.ColorPicker.ColorPalette.UpdateMarkerPosition().
ShowDropperMarker()
void Empyrean.ColorPicker.ColorPalette.ShowDropperMarker (bool value) inline
Definition at line 134 of file ColorPalette.cs.
    {
        marker.gameObject.SetActive(!value);
        dropperSelectionMarker.gameObject.SetActive(value);
    }
References Empyrean.ColorPicker.ColorPalette.dropperSelectionMarker, and Empyrean.ColorPicker.ColorPalette.marker.
Referenced by Empyrean.ColorPicker.Dropper.PickColors(), and Empyrean.ColorPicker.Dropper.Stop().
ShowEnlargedPixels()
void Empyrean.ColorPicker.ColorPalette.ShowEnlargedPixels (Color[] colors) inline
Definition at line 117 of file ColorPalette.cs.
    {
        Color[] array = new Color[texture.width * texture.height];
        for (int i = 0; i < texture.width; i++)
        {
            for (int j = 0; j < texture.width; j++)
            {
                int num = i * texture.width + j;
                int num2 = i / 32 * 16 + j / 32;
                array[num] = colors[num2];
            }
        }
        texture.SetPixels(array);
        texture.Apply();
        paletteImage.texture = texture;
    }
References Color, and Empyrean.ColorPicker.ColorPalette.texture.
Referenced by Empyrean.ColorPicker.Dropper.EnlargeAreaAroundPointer().
UpdateMarkerPosition()
void Empyrean.ColorPicker.ColorPalette.UpdateMarkerPosition (HSVColor hsv) inline
Definition at line 106 of file ColorPalette.cs.
    {
        SetMarkerPosition(new Vector2(hsv.s, hsv.v));
    }
References HSVColor.s, Empyrean.ColorPicker.ColorPalette.SetMarkerPosition(), and HSVColor.v.
Referenced by Empyrean.ColorPicker.ColorPalette.SelectColor().
Member Data Documentation
colorArray
Color [] Empyrean.ColorPicker.ColorPalette.colorArray private
Definition at line 13 of file ColorPalette.cs.
Referenced by Empyrean.ColorPicker.ColorPalette.GeneratePaletteTexture(), and Empyrean.ColorPicker.ColorPalette.Init().
current
HSVColor Empyrean.ColorPicker.ColorPalette.current private
Definition at line 11 of file ColorPalette.cs.
Referenced by Empyrean.ColorPicker.ColorPalette.GeneratePaletteTexture(), and Empyrean.ColorPicker.ColorPalette.SelectColor().
dropperSelectionMarker
RectTransform Empyrean.ColorPicker.ColorPalette.dropperSelectionMarker private
Definition at line 24 of file ColorPalette.cs.
Referenced by Empyrean.ColorPicker.ColorPalette.ShowDropperMarker().
initiated
bool Empyrean.ColorPicker.ColorPalette.initiated private
Definition at line 26 of file ColorPalette.cs.
Referenced by Empyrean.ColorPicker.ColorPalette.Init().
marker
RectTransform Empyrean.ColorPicker.ColorPalette.marker private
Definition at line 21 of file ColorPalette.cs.
Referenced by Empyrean.ColorPicker.ColorPalette.ShowDropperMarker().
paletteImage
RawImage Empyrean.ColorPicker.ColorPalette.paletteImage private
Definition at line 18 of file ColorPalette.cs.
Referenced by Empyrean.ColorPicker.ColorPalette.GetClampedLocalPosition(), Empyrean.ColorPicker.ColorPalette.GetNormalisedPointerPosition(), and Empyrean.ColorPicker.ColorPalette.Init().
texture
Texture2D Empyrean.ColorPicker.ColorPalette.texture private
Definition at line 15 of file ColorPalette.cs.
Referenced by Empyrean.ColorPicker.ColorPalette.GeneratePaletteTexture(), Empyrean.ColorPicker.ColorPalette.Init(), and Empyrean.ColorPicker.ColorPalette.ShowEnlargedPixels().
Property Documentation
MarkerPosition
Vector2 Empyrean.ColorPicker.ColorPalette.MarkerPosition get
Definition at line 28 of file ColorPalette.cs.
Referenced by Empyrean.ColorPicker.ColorPicker.UpdateColor().
Event Documentation
ColorPicked
Action<Vector2> Empyrean.ColorPicker.ColorPalette.ColorPicked
Initial value:
= delegate
    {
    }
Definition at line 30 of file ColorPalette.cs.
Referenced by Empyrean.ColorPicker.ColorPalette.OnDrag().
The documentation for this class was generated from the following file:
Elin/Plugins.UI/Empyrean/ColorPicker/ColorPalette.cs