Elin Decompiled Documentation: CardManager.GlobalCharaList Class Reference
CardManager.GlobalCharaList Class Reference
Public Member Functions
void Add (Chara c)
void Remove (Chara c)
Chara Find (string id)
Chara Find (int uid)
Detailed Description
Definition at line 8 of file CardManager.cs.
Member Function Documentation
Add()
void CardManager.GlobalCharaList.Add (Chara c) inline
Definition at line 10 of file CardManager.cs.
        {
            base[c.uid] = c;
        }
References Card.uid.
Referenced by Chara.SetGlobal().
Find() [1/2]
Chara CardManager.GlobalCharaList.Find (int uid) inline
Definition at line 32 of file CardManager.cs.
        {
            foreach (Chara value in base.Values)
            {
                if (value.uid == uid)
                {
                    return value;
                }
            }
            return null;
        }
References Card.uid.
Find() [2/2]
Chara CardManager.GlobalCharaList.Find (string id) inline
Definition at line 20 of file CardManager.cs.
        {
            foreach (Chara value in base.Values)
            {
                if (value.id == id)
                {
                    return value;
                }
            }
            return null;
        }
References Card.id.
Referenced by QuestManager.Add(), QuestManager.AddQuestAsh(), QuestManager.AddQuestFiama(), GameDate.AdvanceDay(), LayerShippingResult.Awake(), Chara.Die(), Zone_WindRest.OnAfterSimulate(), Zone_Nymelle.OnBeforeSimulate(), QuestDefense.OnChangePhase(), QuestVernis.OnChangePhase(), DramaOutcome.OnClaimLand(), QuestIntroInspector.OnComplete(), QuestSharedContainer.OnComplete(), QuestDialog.OnDropReward(), Zone_DungeonPuppy.OnGenerateMap(), TraitStoryBookHome.OnRead(), QuestDebt.OnStart(), QuestExploration.OnStart(), DramaOutcome.QuestExploration_AfterComplete(), DramaOutcome.QuestExploration_AfterCrystal(), Meeting.SetChara(), QuestManager.Start(), Game.StartNewGame(), and TraitBed.ValidateOwners().
Remove()
void CardManager.GlobalCharaList.Remove (Chara c) inline
Definition at line 15 of file CardManager.cs.
        {
            Remove(c.uid);
        }
References CardManager.GlobalCharaList.Remove(), and Card.uid.
Referenced by Card.Destroy(), CardManager.GlobalCharaList.Remove(), and Chara.RemoveGlobal().
The documentation for this class was generated from the following file:
Elin/CardManager.cs