Elin Decompiled Documentation: ActionHint Class Reference
ActionHint Class Reference
Public Member Functions
void Refresh ()
void AddToggle (string lang, bool on, Action< bool > action)
void UpdateText ()
void Show (string lang, bool icon=true)
void SetText (string s, bool anime=false)
Public Attributes
Transform extra
LayoutGroup layoutDynamic
UIText textTitle
UIText textDetail
UIButton buttonPick
UIButton buttonSavePartialMap
UIButton buttonDeletePartialMap
UISelectableGroup groupRadio
UISelectableGroup groupToggle
Anime animePop
Image iconNerun
CanvasGroup cg
bool dynamic
Properties
ActionMode mode [get]
BaseTileSelector ts [get]
Properties inherited from EMono
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SoundManager Sound [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static CoreDebug debug [get]
Private Member Functions
void Awake ()
Private Attributes
UIButton moldDynamic
Vector3 oriPos
string lastText
Additional Inherited Members
Static Public Member Functions inherited from EMono
static int rnd (int a)
Static Public Attributes inherited from EMono
static Core core
Detailed Description
Definition at line 5 of file ActionHint.cs.
Member Function Documentation
AddToggle()
void ActionHint.AddToggle (string lang, bool on, Action< bool > action) inline
Definition at line 111 of file ActionHint.cs.
    {
        UIButton uIButton = Util.Instantiate(moldDynamic, layoutDynamic);
        uIButton.mainText.SetText(lang.lang());
        uIButton.SetToggle(on, action);
        dynamic = true;
    }
References dynamic, layoutDynamic, and moldDynamic.
Awake()
void ActionHint.Awake () inline private
Definition at line 44 of file ActionHint.cs.
    {
        moldDynamic = layoutDynamic.CreateMold<UIButton>();
        oriPos = this.Rect().anchoredPosition;
    }
References layoutDynamic, moldDynamic, and oriPos.
Refresh()
void ActionHint.Refresh () inline
Definition at line 50 of file ActionHint.cs.
    {
        if (mode == null)
        {
            return;
        }
        bool flag = EMono.core.IsGameStarted && mode.ShowActionHint;
        base.gameObject.SetActive(flag);
        if (!flag)
        {
            return;
        }
        extra.SetActive(enable: true);
        bool digRamp = mode == ActionMode.Dig && ActionMode.Dig.mode == TaskDig.Mode.Ramp;
        bool mineRamp = mode == ActionMode.Mine && ActionMode.Mine.mode == TaskMine.Mode.Ramp;
        groupRadio.SetActive(digRamp || mineRamp);
        if (digRamp || mineRamp)
        {
            groupRadio.Init(0, delegate(int a)
            {
                if (digRamp)
                {
                    if (a == 0)
                    {
                        ActionMode.Dig.ramp = 3;
                    }
                    if (a == 1)
                    {
                        ActionMode.Dig.ramp = 4;
                    }
                    if (a == 2)
                    {
                        ActionMode.Dig.ramp = 5;
                    }
                    ActionMode.Dig.OnCreateMold();
                }
                if (mineRamp)
                {
                    if (a == 0)
                    {
                        ActionMode.Mine.ramp = 3;
                    }
                    if (a == 1)
                    {
                        ActionMode.Mine.ramp = 4;
                    }
                    if (a == 2)
                    {
                        ActionMode.Mine.ramp = 5;
                    }
                    ActionMode.Mine.OnCreateMold();
                }
            });
            groupRadio.ToggleInteractable(enable: true);
        }
        dynamic = false;
        layoutDynamic.DestroyChildren();
        groupToggle.SetActive(dynamic);
        UpdateText();
    }
References ActionMode.Dig, dynamic, extra, groupRadio, groupToggle, layoutDynamic, ActionMode.Mine, mode, AM_Dig.OnCreateMold(), AM_Mine.OnCreateMold(), ActionMode.ShowActionHint, and UpdateText().
Referenced by UI.OnChangeLayer().
SetText()
void ActionHint.SetText (string s, bool anime = false) inline
Definition at line 143 of file ActionHint.cs.
    {
        this.Rect().anchoredPosition = oriPos;
        textTitle.SetText(s);
        this.RebuildLayout();
        if (anime)
        {
            animePop.Play(base.transform);
        }
    }
References animePop, oriPos, and textTitle.
Referenced by Show(), and UpdateText().
Show()
void ActionHint.Show (string lang, bool icon = true) inline
Definition at line 131 of file ActionHint.cs.
    {
        string text = lang.lang();
        bool anime = text != lastText || !base.gameObject.activeSelf;
        lastText = text;
        iconNerun.SetActive(enable: false);
        base.gameObject.SetActive(value: true);
        buttonPick.SetActive(enable: false);
        extra.SetActive(enable: false);
        SetText(text, anime);
    }
References buttonPick, extra, iconNerun, lastText, and SetText().
UpdateText()
void ActionHint.UpdateText () inline
Definition at line 119 of file ActionHint.cs.
    {
        string hintText = mode.GetHintText();
        base.gameObject.SetActive(EMono.scene.actionMode.ShowActionHint && !hintText.IsEmpty());
        SetText(hintText);
        buttonPick.SetActive(mode == ActionMode.Inspect && ActionMode.Inspect.CanPutAway());
        buttonPick.SetOnClick(delegate
        {
            ActionMode.Inspect.TryPutAway();
        });
    }
References Scene.actionMode, buttonPick, AM_MoveInstalled.CanPutAway(), ActionMode.GetHintText(), ActionMode.Inspect, mode, EMono.scene, SetText(), ActionMode.ShowActionHint, and AM_MoveInstalled.TryPutAway().
Referenced by Refresh().
Member Data Documentation
animePop
Anime ActionHint.animePop
Definition at line 25 of file ActionHint.cs.
Referenced by SetText().
buttonDeletePartialMap
UIButton ActionHint.buttonDeletePartialMap
Definition at line 19 of file ActionHint.cs.
buttonPick
UIButton ActionHint.buttonPick
Definition at line 15 of file ActionHint.cs.
Referenced by Show(), and UpdateText().
buttonSavePartialMap
UIButton ActionHint.buttonSavePartialMap
Definition at line 17 of file ActionHint.cs.
cg
CanvasGroup ActionHint.cg
Definition at line 29 of file ActionHint.cs.
dynamic
bool ActionHint.dynamic
Definition at line 32 of file ActionHint.cs.
Referenced by AddToggle(), and Refresh().
extra
Transform ActionHint.extra
Definition at line 7 of file ActionHint.cs.
Referenced by Refresh(), and Show().
groupRadio
UISelectableGroup ActionHint.groupRadio
Definition at line 21 of file ActionHint.cs.
Referenced by AM_Dig.OnSelectEnd(), AM_Dig.OnSelectStart(), and Refresh().
groupToggle
UISelectableGroup ActionHint.groupToggle
Definition at line 23 of file ActionHint.cs.
Referenced by Refresh().
iconNerun
Image ActionHint.iconNerun
Definition at line 27 of file ActionHint.cs.
Referenced by Show().
lastText
string ActionHint.lastText private
Definition at line 38 of file ActionHint.cs.
Referenced by Show().
layoutDynamic
LayoutGroup ActionHint.layoutDynamic
Definition at line 9 of file ActionHint.cs.
Referenced by AddToggle(), Awake(), and Refresh().
moldDynamic
UIButton ActionHint.moldDynamic private
Definition at line 34 of file ActionHint.cs.
Referenced by AddToggle(), and Awake().
oriPos
Vector3 ActionHint.oriPos private
Definition at line 36 of file ActionHint.cs.
Referenced by Awake(), and SetText().
textDetail
UIText ActionHint.textDetail
Definition at line 13 of file ActionHint.cs.
textTitle
UIText ActionHint.textTitle
Definition at line 11 of file ActionHint.cs.
Referenced by SetText().
Property Documentation
mode
ActionMode ActionHint.mode get
Definition at line 40 of file ActionHint.cs.
Referenced by Refresh(), and UpdateText().
ts
BaseTileSelector ActionHint.ts get private
Definition at line 42 of file ActionHint.cs.
The documentation for this class was generated from the following file:
Elin/ActionHint.cs