Elin Decompiled Documentation: CharaActorPCC Class Reference
CharaActorPCC Class Reference
Public Member Functions
override void OnSetOwner ()
override void NextFrame ()
override void IdleFrame ()
override int GetFrame ()
override void NextDir ()
override void Kill ()
override void OnRender (RenderParam p)
override void RefreshSprite ()
Public Member Functions inherited from CharaActor
void SetOwnerAsChara ()
override void OnSetOwner ()
override void NextFrame ()
override void RefreshSprite ()
Public Member Functions inherited from CardActor
void SetOwner (Card t)
virtual void OnSetOwner ()
virtual void IdleFrame ()
virtual void NextFrame ()
virtual void NextDir ()
virtual int GetFrame ()
virtual void OnRender (RenderParam p)
virtual void RefreshSprite ()
virtual void Kill ()
Public Attributes
PCC pcc
SpriteProvider provider = new SpriteProvider()
Public Attributes inherited from CharaActor
new Chara owner
Public Attributes inherited from CardActor
Card owner
SpriteRenderer sr
SpriteRenderer sr2
SpriteReplacerAnimation srAnime
MaterialPropertyBlock mpb
MaterialPropertyBlock mpb2
Type type
Static Public Attributes
static Vector3 V2 = new Vector3(2f, 2f, 1f)
Static Public Attributes inherited from EMono
static Core core
Properties
override bool isPCC [get]
override int currentDir [get]
Properties inherited from CardActor
virtual bool isPCC [get]
virtual int currentDir [get]
Properties inherited from EMono
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SoundManager Sound [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static CoreDebug debug [get]
Private Attributes
float lastNextFrame
Static Private Attributes
static Vector3 org
Additional Inherited Members
Public Types inherited from CardActor
enum Type { Default , Boat , Canvas , MultiSprite }
Static Public Member Functions inherited from EMono
static int rnd (int a)
Static Protected Attributes inherited from CardActor
static Vector3 tempV
static Vector3 tempV2
Detailed Description
Definition at line 3 of file CharaActorPCC.cs.
Member Function Documentation
GetFrame()
override int CharaActorPCC.GetFrame () inline virtual
Reimplemented from CardActor.
Definition at line 52 of file CharaActorPCC.cs.
    {
        return provider.currentFrame % 2;
    }
IdleFrame()
override void CharaActorPCC.IdleFrame () inline virtual
Reimplemented from CardActor.
Definition at line 44 of file CharaActorPCC.cs.
    {
        if (!owner.isDead)
        {
            provider.SetSpriteIdle();
        }
    }
References Chara.isDead, CharaActor.owner, and provider.
Referenced by OnSetOwner().
Kill()
override void CharaActorPCC.Kill () inline virtual
Reimplemented from CardActor.
Definition at line 66 of file CharaActorPCC.cs.
    {
        base.Kill();
        pcc = null;
        provider.pcc = null;
    }
References pcc.
NextDir()
override void CharaActorPCC.NextDir () inline virtual
Reimplemented from CardActor.
Definition at line 57 of file CharaActorPCC.cs.
    {
        provider.NextDir();
        owner.angle = provider.angle;
        provider.SetDir();
        provider.SetSpriteMain();
        RefreshSprite();
    }
References provider, and RefreshSprite().
Referenced by CoreDebug.UpdateInput().
NextFrame()
override void CharaActorPCC.NextFrame () inline virtual
Reimplemented from CharaActor.
Definition at line 35 of file CharaActorPCC.cs.
    {
        if (lastNextFrame != Time.timeSinceLevelLoad)
        {
            provider.NextFrame();
            lastNextFrame = Time.timeSinceLevelLoad;
        }
    }
References lastNextFrame, and provider.
Referenced by CoreDebug.UpdateInput().
OnRender()
override void CharaActorPCC.OnRender (RenderParam p) inline virtual
Reimplemented from CardActor.
Definition at line 73 of file CharaActorPCC.cs.
    {
        base.OnRender(p);
        if (pcc.data.isUnique)
        {
            return;
        }
        org.x = p.x;
        org.y = p.y;
        org.z = p.z + owner.renderer.data.offset.z;
        bool flag = owner.combatCount <= 0 && EMono.core.config.game.hideWeapons;
        Cell cell = owner.Cell;
        if ((owner.held == null || (owner.held.trait.ShowAsTool && !HotItemHeld.disableTool)) && !owner.IsDeadOrSleeping && pcc.data.state != PCCState.Naked && (owner.Cell.isFloating || !cell.sourceSurface.tileType.IsDeepWater || cell.IsIceTile))
        {
            int num = currentDir;
            int tempLeft = pcc.data.tempLeft;
            int tempRight = pcc.data.tempRight;
            switch (tempRight)
            {
            default:
            {
                RenderData renderTempEQ = EMono.scene.screenElin.renderTempEQ;
                bool flag3 = num == 0 || num == 1;
                Vector3[] mainHandPos2 = EMono.setting.render.mainHandPos;
                Vector3[] mainHand2 = EMono.setting.render.animeWalk[provider.currentFrame].mainHand;
                p.tile = tempRight * (flag3 ? 1 : (-1));
                p.matColor = 104025f;
                p.x = org.x + mainHandPos2[num].x + mainHand2[num].x;
                p.y = org.y + mainHandPos2[num].y + mainHand2[num].y;
                p.z = org.z - renderTempEQ.offset.z + mainHandPos2[num].z + mainHand2[num].z;
                renderTempEQ.Draw(p);
                break;
            }
            case 0:
            {
                Thing thing = ((owner.IsPC && EMono.player.currentHotItem.RenderThing != null) ? EMono.player.currentHotItem.RenderThing : ((!flag && owner.body.slotMainHand?.thing != null) ? owner.body.slotMainHand.thing : null));
                if (thing != null)
                {
                    bool flag2 = num == 0 || num == 1;
                    if (thing.trait.InvertHeldSprite)
                    {
                        flag2 = !flag2;
                    }
                    Vector3[] mainHandPos = EMono.setting.render.mainHandPos;
                    Vector3[] mainHand = EMono.setting.render.animeWalk[provider.currentFrame].mainHand;
                    SourcePref pref = thing.sourceCard.pref;
                    thing.dir = ((!flag2) ? 1 : 0);
                    thing.SetRenderParam(p);
                    p.x = org.x + mainHandPos[num].x + mainHand[num].x + (flag2 ? 0.01f : (-0.01f)) * (float)pref.equipX;
                    p.y = org.y + mainHandPos[num].y + mainHand[num].y + 0.01f * (float)pref.equipY;
                    p.z = org.z - thing.renderer.data.offset.z + mainHandPos[num].z + mainHand[num].z;
                    p.v.x = p.x;
                    p.v.y = p.y;
                    p.v.z = p.z;
                    if (thing.renderer.hasActor)
                    {
                        thing.renderer.RefreshSprite();
                    }
                    thing.renderer.Draw(p, ref p.v, drawShadow: false);
                }
                break;
            }
            case -1:
                break;
            }
            switch (tempLeft)
            {
            default:
            {
                RenderData renderTempEQ2 = EMono.scene.screenElin.renderTempEQ;
                bool flag5 = num == 1 || num == 3;
                Vector3[] offHandPos2 = EMono.setting.render.offHandPos;
                Vector3[] offHand2 = EMono.setting.render.animeWalk[provider.currentFrame].offHand;
                p.tile = tempLeft * (flag5 ? 1 : (-1));
                p.matColor = 104025f;
                p.x = org.x + offHandPos2[num].x + offHand2[num].x;
                p.y = org.y + offHandPos2[num].y + offHand2[num].y;
                p.z = org.z - renderTempEQ2.offset.z + offHandPos2[num].z + offHand2[num].z;
                renderTempEQ2.Draw(p);
                break;
            }
            case 0:
            {
                if (flag || owner.body.slotOffHand == null || !EMono.core.config.game.showOffhand)
                {
                    break;
                }
                Thing thing2 = owner.body.slotOffHand.thing;
                if (thing2 != null)
                {
                    bool flag4 = num == 1 || num == 3;
                    Vector3[] offHandPos = EMono.setting.render.offHandPos;
                    Vector3[] offHand = EMono.setting.render.animeWalk[provider.currentFrame].offHand;
                    SourcePref pref2 = thing2.source.pref;
                    thing2.dir = ((!flag4) ? 1 : 0);
                    thing2.SetRenderParam(p);
                    p.x = org.x + offHandPos[num].x + offHand[num].x + (flag4 ? 0.01f : (-0.01f)) * (float)pref2.equipX;
                    p.y = org.y + offHandPos[num].y + offHand[num].y + 0.01f * (float)pref2.equipY;
                    p.z = org.z - thing2.renderer.data.offset.z + offHandPos[num].z + offHand[num].z;
                    if (thing2.renderer.hasActor)
                    {
                        thing2.renderer.RefreshSprite();
                    }
                    thing2.renderer.Draw(p);
                }
                break;
            }
            case -1:
                break;
            }
        }
        p.x = org.x;
        p.y = org.y;
        p.z = org.z - owner.renderer.data.offset.z;
    }
References GameSetting.RenderSetting.animeWalk, Chara.body, Card.Cell, Core.config, EMono.core, currentDir, Player.currentHotItem, RenderObject.data, HotItemHeld.disableTool, CardRenderer.Draw(), RenderData.Draw(), SourcePref.equipX, SourcePref.equipY, CoreConfig.game, CardRenderer.hasActor, Chara.held, CoreConfig.GameConfig.hideWeapons, Trait.InvertHeldSprite, Chara.IsDeadOrSleeping, Cell.isFloating, Cell.IsIceTile, AnimationFrame.mainHand, GameSetting.RenderSetting.mainHandPos, AnimationFrame.offHand, GameSetting.RenderSetting.offHandPos, RenderData.offset, org, CharaActor.owner, pcc, EMono.player, RenderRow.pref, provider, CardRenderer.RefreshSprite(), GameSetting.render, Card.renderer, GameScreen.renderTempEQ, HotItem.RenderThing, EMono.scene, Scene.screenElin, Thing.SetRenderParam(), EMono.setting, Trait.ShowAsTool, CoreConfig.GameConfig.showOffhand, CharaBody.slotMainHand, CharaBody.slotOffHand, Thing.source, Thing.sourceCard, Cell.sourceSurface, BodySlot.thing, Card.trait, RenderParam.v, MeshPassParam.x, MeshPassParam.y, and MeshPassParam.z.
OnSetOwner()
override void CharaActorPCC.OnSetOwner () inline virtual
Reimplemented from CharaActor.
Definition at line 19 of file CharaActorPCC.cs.
    {
        SetOwnerAsChara();
        sr.flipX = false;
        pcc = PCC.Get((owner.renderer as CharaRenderer).pccData);
        provider.onSetSprite = delegate(Sprite a)
        {
            sr.sprite = a;
            mpb.SetTexture("_MainTex", sr.sprite.texture);
        };
        provider.angle = owner.angle;
        provider.SetPCC(pcc);
        mpb.SetTexture("_MainTex", sr.sprite.texture);
        IdleFrame();
    }
References Card.angle, IdleFrame(), CardActor.mpb, CharaActor.owner, pcc, provider, Card.renderer, CharaActor.SetOwnerAsChara(), and CardActor.sr.
RefreshSprite()
override void CharaActorPCC.RefreshSprite () inline virtual
Reimplemented from CharaActor.
Definition at line 189 of file CharaActorPCC.cs.
    {
        provider.angle = owner.angle;
        provider.SetDir();
        provider.SetSpriteMain();
        base.RefreshSprite();
    }
References Card.angle, CharaActor.owner, and provider.
Referenced by CardRenderer.Draw(), NextDir(), and CoreDebug.UpdateInput().
Member Data Documentation
lastNextFrame
float CharaActorPCC.lastNextFrame private
Definition at line 11 of file CharaActorPCC.cs.
Referenced by NextFrame().
org
Vector3 CharaActorPCC.org static private
Definition at line 5 of file CharaActorPCC.cs.
Referenced by OnRender().
pcc
PCC CharaActorPCC.pcc
Definition at line 7 of file CharaActorPCC.cs.
Referenced by Kill(), OnRender(), OnSetOwner(), and CoreDebug.UpdateInput().
provider
SpriteProvider CharaActorPCC.provider = new SpriteProvider()
Definition at line 9 of file CharaActorPCC.cs.
Referenced by CardRenderer.Draw(), IdleFrame(), NextDir(), NextFrame(), OnRender(), OnSetOwner(), RefreshSprite(), and CoreDebug.UpdateInput().
V2
Vector3 CharaActorPCC.V2 = new Vector3(2f, 2f, 1f) static
Definition at line 13 of file CharaActorPCC.cs.
Property Documentation
currentDir
override int CharaActorPCC.currentDir get
Definition at line 17 of file CharaActorPCC.cs.
Referenced by OnRender().
isPCC
override bool CharaActorPCC.isPCC get
Definition at line 15 of file CharaActorPCC.cs.
The documentation for this class was generated from the following file:
Elin/CharaActorPCC.cs