Elin Decompiled Documentation: DragItem Class Reference
DragItem Class Reference
Public Member Functions
virtual Image GetDragImage ()
virtual void OnStartDrag ()
virtual void OnEndDrag ()
virtual bool OnDrag (bool execute, bool cancel=false)
virtual bool OnDragSpecial ()
Properties
virtual UIButton Button [get]
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Additional Inherited Members
Static Public Member Functions inherited from EClass
static int rndSeed (int a, int seed)
static int rnd (long a)
static int rnd (int a)
static int curve (int a, int start, int step, int rate=75)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Static Public Attributes inherited from EClass
static Core core
Detailed Description
Definition at line 3 of file DragItem.cs.
Member Function Documentation
GetDragImage()
virtual Image DragItem.GetDragImage () inline virtual
Definition at line 7 of file DragItem.cs.
    {
        return Button.icon;
    }
References Button, and UIButton.icon.
OnDrag()
virtual bool DragItem.OnDrag (bool execute, bool cancel = false) inline virtual
Reimplemented in DragItemCard.
Definition at line 20 of file DragItem.cs.
    {
        return true;
    }
Referenced by UI.EndDrag(), and UI.OnDrag().
OnDragSpecial()
virtual bool DragItem.OnDragSpecial () inline virtual
Reimplemented in DragItemCard.
Definition at line 25 of file DragItem.cs.
    {
        return false;
    }
Referenced by UI.OnDragSpecial().
OnEndDrag()
virtual void DragItem.OnEndDrag () inline virtual
Reimplemented in DragItemCard.
Definition at line 16 of file DragItem.cs.
    {
    }
Referenced by UI.EndDrag().
OnStartDrag()
virtual void DragItem.OnStartDrag () inline virtual
Reimplemented in DragItemCard.
Definition at line 12 of file DragItem.cs.
    {
    }
Property Documentation
Button
virtual UIButton DragItem.Button get
Definition at line 5 of file DragItem.cs.
Referenced by GetDragImage().
The documentation for this class was generated from the following file:
Elin/DragItem.cs