Elin Decompiled Documentation: SearchContext Class Reference
SearchContext Class Reference
Classes
class Item
Public Member Functions
void Init ()
List< Item > Search (string s)
Public Attributes
List< Item > items = new List<Item>()
List< Item > result = new List<Item>()
Static Public Attributes
static int MaxItem = 50
Detailed Description
Definition at line 5 of file SearchContext.cs.
Member Function Documentation
Init()
void SearchContext.Init () inline
Definition at line 26 of file SearchContext.cs.
    {
        FileInfo[] files = new DirectoryInfo(CorePath.CorePackage.Help).GetFiles();
        foreach (FileInfo fileInfo in files)
        {
            if (fileInfo.Extension != ".txt" || fileInfo.Name == "_topics.txt" || fileInfo.Name == "include.txt")
            {
                continue;
            }
            string[] array = IO.LoadTextArray(fileInfo.FullName);
            string idFile = fileInfo.Name.Replace(".txt", "");
            string idTopic = "";
            string[] array2 = array;
            foreach (string text in array2)
            {
                if (text.Length == 0 || text.IsEmpty() || text == Environment.NewLine)
                {
                    continue;
                }
                if (text[0] == '$')
                {
                    idTopic = text.Replace("$", "");
                    continue;
                }
                bool flag = false;
                if (text[0] == '{')
                {
                    if (text.Length < 6)
                    {
                        continue;
                    }
                    switch (text.Substring(0, 3))
                    {
                    case "{A|":
                    case "{Q|":
                        flag = true;
                        break;
                    case "{pa":
                        break;
                    default:
                        continue;
                    }
                }
                Item item = new Item();
                if (flag)
                {
                    item.textSearch = (item.text = text.Split('|')[1].Replace("}", "")).ToLower();
                }
                else
                {
                    item.text = text;
                    item.textSearch = text.ToLower();
                }
                item.idFile = idFile;
                item.idTopic = idTopic;
                items.Add(item);
            }
        }
    }
References CorePath.CorePackage.Help, item, and items.
Referenced by UIBook.Awake().
Search()
List< Item > SearchContext.Search (string s) inline
Definition at line 86 of file SearchContext.cs.
    {
        result.Clear();
        int num = 0;
        string value = s.ToLower();
        foreach (Item item in items)
        {
            if (item.textSearch.Contains(value))
            {
                result.Add(item);
                num++;
                if (num >= MaxItem)
                {
                    result.Add(new Item
                    {
                        system = true,
                        text = "maxResult".lang()
                    });
                    break;
                }
            }
        }
        if (result.Count == 0)
        {
            result.Add(new Item
            {
                system = true,
                text = "noResult".lang()
            });
        }
        return result;
    }
References item, items, MaxItem, and result.
Referenced by UIBook.Search().
Member Data Documentation
items
List<Item> SearchContext.items = new List<Item>()
Definition at line 22 of file SearchContext.cs.
Referenced by Init(), and Search().
MaxItem
int SearchContext.MaxItem = 50 static
Definition at line 20 of file SearchContext.cs.
Referenced by Search().
result
List<Item> SearchContext.result = new List<Item>()
Definition at line 24 of file SearchContext.cs.
Referenced by Search().
The documentation for this class was generated from the following file:
Elin/Plugins.UI/SearchContext.cs