Elin Decompiled Documentation: SourceZone Class Reference
SourceZone Class Reference
Classes
class Row
Public Member Functions
override Row CreateRow ()
override Row CreateRowByMapping (IReadOnlyDictionary< string, int > mapping)
override void SetRow (Row r)
override IReadOnlyDictionary< string, int > GetRowMapping ()
override IReadOnlyDictionary< string, string > GetTypeMapping ()
Public Member Functions inherited from SourceDataString< SourceZone.Row >
override T GetRow (string id)
Static Public Attributes
static readonly IReadOnlyDictionary< string, int > RowMapping
static readonly IReadOnlyDictionary< string, string > TypeMapping
Properties
override string[] ImportFields [get]
Detailed Description
Definition at line 4 of file SourceZone.cs.
Member Function Documentation
CreateRow()
override Row SourceZone.CreateRow () inline
Definition at line 129 of file SourceZone.cs.
    {
        return new Row
        {
            id = SourceData.GetString(0),
            parent = SourceData.GetString(1),
            name_JP = SourceData.GetString(2),
            name = SourceData.GetString(3),
            type = SourceData.GetString(4),
            LV = SourceData.GetInt(5),
            chance = SourceData.GetInt(6),
            faction = SourceData.GetString(7),
            value = SourceData.GetInt(8),
            idProfile = SourceData.GetString(9),
            idFile = SourceData.GetStringArray(10),
            idBiome = SourceData.GetString(11),
            idGen = SourceData.GetString(12),
            idPlaylist = SourceData.GetString(13),
            tag = SourceData.GetStringArray(14),
            cost = SourceData.GetInt(15),
            dev = SourceData.GetInt(16),
            image = SourceData.GetString(17),
            pos = SourceData.GetIntArray(18),
            questTag = SourceData.GetStringArray(19),
            textFlavor_JP = SourceData.GetString(20),
            textFlavor = SourceData.GetString(21),
            detail_JP = SourceData.GetString(22),
            detail = SourceData.GetString(23)
        };
    }
References SourceData< T, T2 >.GetInt(), SourceData< T, T2 >.GetIntArray(), SourceData< T, T2 >.GetString(), and SourceData< T, T2 >.GetStringArray().
CreateRowByMapping()
override Row SourceZone.CreateRowByMapping (IReadOnlyDictionary< string, int > mapping) inline
Definition at line 160 of file SourceZone.cs.
    {
        return new Row
        {
            id = SourceData.GetString(mapping["id"]),
            parent = SourceData.GetString(mapping["parent"]),
            name_JP = SourceData.GetString(mapping["name_JP"]),
            name = SourceData.GetString(mapping["name"]),
            type = SourceData.GetString(mapping["type"]),
            LV = SourceData.GetInt(mapping["LV"]),
            chance = SourceData.GetInt(mapping["chance"]),
            faction = SourceData.GetString(mapping["faction"]),
            value = SourceData.GetInt(mapping["value"]),
            idProfile = SourceData.GetString(mapping["idProfile"]),
            idFile = SourceData.GetStringArray(mapping["idFile"]),
            idBiome = SourceData.GetString(mapping["idBiome"]),
            idGen = SourceData.GetString(mapping["idGen"]),
            idPlaylist = SourceData.GetString(mapping["idPlaylist"]),
            tag = SourceData.GetStringArray(mapping["tag"]),
            cost = SourceData.GetInt(mapping["cost"]),
            dev = SourceData.GetInt(mapping["dev"]),
            image = SourceData.GetString(mapping["image"]),
            pos = SourceData.GetIntArray(mapping["pos"]),
            questTag = SourceData.GetStringArray(mapping["questTag"]),
            textFlavor_JP = SourceData.GetString(mapping["textFlavor_JP"]),
            textFlavor = SourceData.GetString(mapping["textFlavor"]),
            detail_JP = SourceData.GetString(mapping["detail_JP"]),
            detail = SourceData.GetString(mapping["detail"])
        };
    }
References SourceData< T, T2 >.GetInt(), SourceData< T, T2 >.GetIntArray(), SourceData< T, T2 >.GetString(), and SourceData< T, T2 >.GetStringArray().
GetRowMapping()
override IReadOnlyDictionary< string, int > SourceZone.GetRowMapping () inline
Definition at line 196 of file SourceZone.cs.
    {
        return RowMapping;
    }
References RowMapping.
GetTypeMapping()
override IReadOnlyDictionary< string, string > SourceZone.GetTypeMapping () inline
Definition at line 201 of file SourceZone.cs.
    {
        return TypeMapping;
    }
References TypeMapping.
SetRow()
override void SourceZone.SetRow (Row r) inline
Definition at line 191 of file SourceZone.cs.
    {
        map[r.id] = r;
    }
References SourceZone.Row.id.
Member Data Documentation
RowMapping
readonly IReadOnlyDictionary<string, int> SourceZone.RowMapping static
Initial value:
= new Dictionary<string, int>
    {
        ["id"] = 0,
        ["parent"] = 1,
        ["name_JP"] = 2,
        ["name"] = 3,
        ["type"] = 4,
        ["LV"] = 5,
        ["chance"] = 6,
        ["faction"] = 7,
        ["value"] = 8,
        ["idProfile"] = 9,
        ["idFile"] = 10,
        ["idBiome"] = 11,
        ["idGen"] = 12,
        ["idPlaylist"] = 13,
        ["tag"] = 14,
        ["cost"] = 15,
        ["dev"] = 16,
        ["image"] = 17,
        ["pos"] = 18,
        ["questTag"] = 19,
        ["textFlavor_JP"] = 20,
        ["textFlavor"] = 21,
        ["detail_JP"] = 22,
        ["detail"] = 23
    }
Definition at line 71 of file SourceZone.cs.
Referenced by GetRowMapping().
TypeMapping
readonly IReadOnlyDictionary<string, string> SourceZone.TypeMapping static
Initial value:
= new Dictionary<string, string>
    {
        ["id"] = "string",
        ["parent"] = "string",
        ["name_JP"] = "string",
        ["name"] = "string",
        ["type"] = "string",
        ["LV"] = "int",
        ["chance"] = "int",
        ["faction"] = "string",
        ["value"] = "int",
        ["idProfile"] = "string",
        ["idFile"] = "string[]",
        ["idBiome"] = "string",
        ["idGen"] = "string",
        ["idPlaylist"] = "string",
        ["tag"] = "string[]",
        ["cost"] = "int",
        ["dev"] = "int",
        ["image"] = "string",
        ["pos"] = "int[]",
        ["questTag"] = "string[]",
        ["textFlavor_JP"] = "string",
        ["textFlavor"] = "string",
        ["detail_JP"] = "string",
        ["detail"] = "string"
    }
Definition at line 99 of file SourceZone.cs.
Referenced by GetTypeMapping().
Property Documentation
ImportFields
override string [] SourceZone.ImportFields get
Definition at line 127 of file SourceZone.cs.
The documentation for this class was generated from the following file:
Elin/SourceZone.cs