Elin Decompiled Documentation: BiomeProfile.Style Class Reference
BiomeProfile.Style Class Reference
Public Member Functions
string GetIdLight (bool wall)
string GetIdStairs (bool upstairs)
string GetIdDoor ()
Public Attributes
float doorChance = 0.9f
DoorStyle doorStyle
int matDoor
StairsStyle stairsStyle
int matStairs
List< Cluster.ItemThing > lights
Properties
string _matDoor [get, set]
string _matStairs [get, set]
Additional Inherited Members
Public Types inherited from BiomeProfile.BaseTile
enum SubType {
None = 0 , Rnd5 = 10 , Rnd10 = 11 , Rnd20 = 12 ,
Pattern = 20
}
enum DirType { Random8 , RandomSqrt8 , RandomSqrtSqrt8 }
Protected Member Functions inherited from BiomeProfile.BaseTile
string _GetThing (string id)
void _SetThing (ref string id, string value)
IEnumerable< string > ThingRows ()
string _GetObj (int id)
void _SetObj (ref int id, string value)
IEnumerable< string > ObjRows ()
string _GetFloor (int id)
void _SetFloor (ref int id, string value)
IEnumerable< string > FloorRows ()
string _GetBlock (int id)
void _SetBlock (ref int id, string value)
IEnumerable< string > BlockRows ()
string _GetMat (int id)
void _SetMat (ref int id, string value)
IEnumerable< string > MatRows ()
string _GetSpawnList (string id)
void _SetSpawnList (ref string id, string value)
IEnumerable< string > _SpawnList ()
Detailed Description
Definition at line 297 of file BiomeProfile.cs.
Member Function Documentation
GetIdDoor()
string BiomeProfile.Style.GetIdDoor () inline
Definition at line 387 of file BiomeProfile.cs.
        {
            return doorStyle switch
            {
                DoorStyle.FirmWood => "46",
                DoorStyle.Stone => "42",
                DoorStyle.Jail => "40",
                DoorStyle.Rune => "43",
                _ => "45",
            };
        }
References BiomeProfile.Style.doorStyle.
Referenced by MapGenDungen.OnGenerateTerrain().
GetIdLight()
string BiomeProfile.Style.GetIdLight (bool wall) inline
Definition at line 337 of file BiomeProfile.cs.
        {
            if (lights.Count > 0)
            {
                foreach (Cluster.ItemThing light in lights)
                {
                    if (EClass.sources.cards.map[light.id].tileType.UseMountHeight == wall)
                    {
                        return light.id;
                    }
                }
            }
            if (!wall)
            {
                return "torch";
            }
            return "torch_wall";
        }
References SourceManager.cards, BiomeProfile.Style.lights, SourceCard.map, and EClass.sources.
Referenced by SerializedCards.Restore().
GetIdStairs()
string BiomeProfile.Style.GetIdStairs (bool upstairs) inline
Definition at line 356 of file BiomeProfile.cs.
        {
            switch (stairsStyle)
            {
            case StairsStyle.Wood:
                if (!upstairs)
                {
                    return "381";
                }
                return "376";
            case StairsStyle.Stone:
                if (!upstairs)
                {
                    return "932";
                }
                return "379";
            case StairsStyle.Rock:
                if (!upstairs)
                {
                    return "380";
                }
                return "377";
            default:
                if (!upstairs)
                {
                    return "stairsDown_cave";
                }
                return "stairs_cave";
            }
        }
References BiomeProfile.Style.stairsStyle.
Referenced by ZonePreEnterDigStairs.Execute(), MapGenDungen.OnGenerateTerrain(), and TraitStairsLocked.OnUse().
Member Data Documentation
doorChance
float BiomeProfile.Style.doorChance = 0.9f
Definition at line 299 of file BiomeProfile.cs.
Referenced by MapGenDungen.OnGenerateTerrain().
doorStyle
DoorStyle BiomeProfile.Style.doorStyle
Definition at line 301 of file BiomeProfile.cs.
Referenced by BiomeProfile.Style.GetIdDoor().
lights
List<Cluster.ItemThing> BiomeProfile.Style.lights
Definition at line 311 of file BiomeProfile.cs.
Referenced by BiomeProfile.Style.GetIdLight(), and GenRoom.Populate().
matDoor
int BiomeProfile.Style.matDoor
Definition at line 304 of file BiomeProfile.cs.
Referenced by Zone.Generate(), and MapGenDungen.OnGenerateTerrain().
matStairs
int BiomeProfile.Style.matStairs
Definition at line 309 of file BiomeProfile.cs.
Referenced by MapGenDungen.OnGenerateTerrain(), and TraitStairsLocked.OnUse().
stairsStyle
StairsStyle BiomeProfile.Style.stairsStyle
Definition at line 306 of file BiomeProfile.cs.
Referenced by BiomeProfile.Style.GetIdStairs().
Property Documentation
_matDoor
string BiomeProfile.Style._matDoor get set
Definition at line 313 of file BiomeProfile.cs.
        {
            get
            {
                return _GetMat(matDoor);
            }
            set
            {
                _SetMat(ref matDoor, value);
            }
        }
_matStairs
string BiomeProfile.Style._matStairs get set
Definition at line 325 of file BiomeProfile.cs.
        {
            get
            {
                return _GetMat(matStairs);
            }
            set
            {
                _SetMat(ref matStairs, value);
            }
        }
The documentation for this class was generated from the following file:
Elin/BiomeProfile.cs