Elin Decompiled Documentation: MsgBox Class Reference
MsgBox Class Reference
Classes
class Prefabs
Public Member Functions
void Init ()
void Append (string s, Color col)
void Append (Sprite s, bool fitLine=false)
UIItem Load (string id)
void CreateNewBlock ()
void MarkNewBlock ()
void RefreshAlpha ()
void SetBG (SpriteAsset s, Color c)
void Clear ()
void AddLog ()
void ToggleLog ()
void ToggleLog (bool show)
Public Attributes
VerticalLayoutGroup layout
VerticalLayoutGroup layoutLog
GameObject goLog
GameObject goBox
Prefabs prefabs
Image imageBg
UIDragPanel dragPanel
int maxBlock
int maxLog
bool reverseOrder
bool multiLine
bool fadeLines
bool newblock
bool isShowingLog
MsgBlock currentBlock
List< MsgBlock > blocks = new List<MsgBlock>()
List< MsgBlock > logs = new List<MsgBlock>()
Properties
float maxWidth [get]
Private Member Functions
void SetCurrentBlock ()
Private Attributes
SpriteAsset bg
Color bgColor
Detailed Description
Definition at line 7 of file MsgBox.cs.
Member Function Documentation
AddLog()
void MsgBox.AddLog () inline
Definition at line 192 of file MsgBox.cs.
    {
        MsgBlock msgBlock = blocks[0];
        blocks.RemoveAt(0);
        logs.Add(msgBlock);
        if (!isShowingLog)
        {
            msgBlock.transform.SetParent(layoutLog.transform, worldPositionStays: false);
        }
        if (logs.Count > maxLog)
        {
            msgBlock = logs[0];
            logs.RemoveAt(0);
            PoolManager.Despawn(msgBlock);
        }
    }
References blocks, PoolManager.Despawn(), isShowingLog, layoutLog, logs, and maxLog.
Referenced by CreateNewBlock().
Append() [1/2]
void MsgBox.Append (Sprite s, bool fitLine = false) inline
Definition at line 80 of file MsgBox.cs.
    {
        SetCurrentBlock();
        currentBlock.Append(s, fitLine);
    }
References MsgBlock.Append(), currentBlock, and SetCurrentBlock().
Append() [2/2]
void MsgBox.Append (string s, Color col) inline
Definition at line 74 of file MsgBox.cs.
    {
        SetCurrentBlock();
        currentBlock.Append(s, col);
    }
References MsgBlock.Append(), currentBlock, and SetCurrentBlock().
Referenced by WidgetMainText.Append().
Clear()
void MsgBox.Clear () inline
Definition at line 176 of file MsgBox.cs.
    {
        foreach (MsgBlock block in blocks)
        {
            PoolManager.Despawn(block);
        }
        foreach (MsgBlock log in logs)
        {
            PoolManager.Despawn(log);
        }
        blocks.Clear();
        logs.Clear();
        currentBlock = null;
        newblock = false;
    }
References block, blocks, currentBlock, PoolManager.Despawn(), logs, and newblock.
CreateNewBlock()
void MsgBox.CreateNewBlock () inline
Definition at line 92 of file MsgBox.cs.
    {
        currentBlock = PoolManager.Spawn(prefabs.block, layout);
        currentBlock.box = this;
        currentBlock.bg.sprite = bg.sprite;
        currentBlock.bg.Rect().sizeDelta = bg.size;
        currentBlock.bg.color = bgColor;
        currentBlock.Reset();
        newblock = false;
        if (reverseOrder)
        {
            currentBlock.transform.SetAsFirstSibling();
        }
        blocks.Add(currentBlock);
        if (blocks.Count > maxBlock)
        {
            int num = blocks.Count - maxBlock;
            for (int i = 0; i < num; i++)
            {
                AddLog();
            }
        }
        if (isShowingLog)
        {
            currentBlock.transform.SetParent(layoutLog.transform, worldPositionStays: false);
            Image image = currentBlock.bg;
            bool flag2 = (currentBlock.cg.enabled = false);
            image.enabled = flag2;
        }
        else
        {
            Image image2 = currentBlock.bg;
            bool flag2 = (currentBlock.cg.enabled = true);
            image2.enabled = flag2;
            RefreshAlpha();
        }
    }
References AddLog(), MsgBlock.bg, bg, bgColor, MsgBox.Prefabs.block, blocks, currentBlock, isShowingLog, layout, layoutLog, maxBlock, newblock, prefabs, RefreshAlpha(), MsgBlock.Reset(), reverseOrder, SpriteAsset.size, PoolManager.Spawn(), and SpriteAsset.sprite.
Referenced by MsgBlock.AddElement(), and SetCurrentBlock().
Init()
void MsgBox.Init () inline
Definition at line 68 of file MsgBox.cs.
    {
        goLog.SetActive(value: false);
        isShowingLog = false;
    }
References goLog, and isShowingLog.
Referenced by WidgetMainText.OnActivate().
Load()
UIItem MsgBox.Load (string id) inline
Definition at line 86 of file MsgBox.cs.
    {
        SetCurrentBlock();
        return currentBlock.Load(id);
    }
References currentBlock, MsgBlock.Load(), and SetCurrentBlock().
Referenced by WidgetMainText.Append().
MarkNewBlock()
void MsgBox.MarkNewBlock () inline
Definition at line 138 of file MsgBox.cs.
    {
        newblock = true;
    }
References newblock.
Referenced by WidgetMainText.NewLine().
RefreshAlpha()
void MsgBox.RefreshAlpha () inline
Definition at line 143 of file MsgBox.cs.
    {
        for (int i = 0; i < blocks.Count; i++)
        {
            float alpha = 1f;
            if (fadeLines && blocks.Count >= 3)
            {
                switch (i)
                {
                case 1:
                    alpha = 0.8f;
                    break;
                case 0:
                    alpha = 0.65f;
                    break;
                }
            }
            blocks[i].cg.alpha = alpha;
        }
    }
References blocks, and fadeLines.
Referenced by CreateNewBlock(), WidgetMainText.OnSetContextMenu(), and ToggleLog().
SetBG()
void MsgBox.SetBG (SpriteAsset s, Color c) inline
Definition at line 164 of file MsgBox.cs.
    {
        bg = s;
        bgColor = c;
        foreach (MsgBlock item in blocks.Concat(logs))
        {
            item.bg.sprite = bg.sprite;
            item.bg.color = bgColor;
            item.bg.Rect().sizeDelta = bg.size;
        }
    }
References bg, bgColor, blocks, item, logs, SpriteAsset.size, and SpriteAsset.sprite.
Referenced by WidgetMainText.RefreshBG().
SetCurrentBlock()
void MsgBox.SetCurrentBlock () inline private
Definition at line 130 of file MsgBox.cs.
    {
        if (!currentBlock || (newblock && currentBlock.countElements > 0))
        {
            CreateNewBlock();
        }
    }
References MsgBlock.countElements, CreateNewBlock(), currentBlock, and newblock.
Referenced by Append(), and Load().
ToggleLog() [1/2]
void MsgBox.ToggleLog () inline
Definition at line 209 of file MsgBox.cs.
    {
        ToggleLog(!isShowingLog);
    }
References isShowingLog, and ToggleLog().
Referenced by WidgetMainText._ToggleLog(), and ToggleLog().
ToggleLog() [2/2]
void MsgBox.ToggleLog (bool show) inline
Definition at line 214 of file MsgBox.cs.
    {
        isShowingLog = show;
        goBox.SetActive(!show);
        goLog.SetActive(show);
        if (show)
        {
            foreach (MsgBlock block in blocks)
            {
                block.transform.SetParent(layoutLog.transform, worldPositionStays: false);
            }
            MsgBlock[] componentsInChildren = layoutLog.GetComponentsInChildren<MsgBlock>();
            foreach (MsgBlock msgBlock in componentsInChildren)
            {
                CanvasGroup cg = msgBlock.cg;
                bool flag2 = (msgBlock.bg.enabled = false);
                cg.enabled = flag2;
            }
            return;
        }
        foreach (MsgBlock block2 in blocks)
        {
            block2.transform.SetParent(layout.transform, worldPositionStays: false);
            CanvasGroup cg2 = block2.cg;
            bool flag2 = (block2.bg.enabled = true);
            cg2.enabled = flag2;
        }
        RefreshAlpha();
        layout.RebuildLayout();
    }
References block, blocks, MsgBlock.cg, goBox, goLog, isShowingLog, layout, layoutLog, and RefreshAlpha().
Member Data Documentation
bg
SpriteAsset MsgBox.bg private
Definition at line 47 of file MsgBox.cs.
Referenced by CreateNewBlock(), and SetBG().
bgColor
Color MsgBox.bgColor private
Definition at line 49 of file MsgBox.cs.
Referenced by CreateNewBlock(), and SetBG().
blocks
List<MsgBlock> MsgBox.blocks = new List<MsgBlock>()
Definition at line 61 of file MsgBox.cs.
Referenced by AddLog(), Clear(), CreateNewBlock(), RefreshAlpha(), SetBG(), and ToggleLog().
currentBlock
MsgBlock MsgBox.currentBlock
Definition at line 58 of file MsgBox.cs.
Referenced by MsgBlock.AddElement(), Append(), Clear(), CreateNewBlock(), Load(), and SetCurrentBlock().
dragPanel
UIDragPanel MsgBox.dragPanel
Definition at line 35 of file MsgBox.cs.
Referenced by WidgetMainText.OnActivate().
fadeLines
bool MsgBox.fadeLines
Definition at line 45 of file MsgBox.cs.
Referenced by RefreshAlpha().
goBox
GameObject MsgBox.goBox
Definition at line 29 of file MsgBox.cs.
Referenced by ToggleLog().
goLog
GameObject MsgBox.goLog
Definition at line 27 of file MsgBox.cs.
Referenced by Init(), and ToggleLog().
imageBg
Image MsgBox.imageBg
Definition at line 33 of file MsgBox.cs.
Referenced by WidgetMainText.OnActivate().
isShowingLog
bool MsgBox.isShowingLog
Definition at line 55 of file MsgBox.cs.
Referenced by WidgetMainText._Refresh(), WidgetMainText._ToggleLog(), AddLog(), CreateNewBlock(), WidgetMainText.HideLog(), Init(), Scene.OnUpdate(), WidgetManager.Reset(), and ToggleLog().
layout
VerticalLayoutGroup MsgBox.layout
Definition at line 23 of file MsgBox.cs.
Referenced by CreateNewBlock(), and ToggleLog().
layoutLog
VerticalLayoutGroup MsgBox.layoutLog
Definition at line 25 of file MsgBox.cs.
Referenced by AddLog(), CreateNewBlock(), and ToggleLog().
logs
List<MsgBlock> MsgBox.logs = new List<MsgBlock>()
Definition at line 64 of file MsgBox.cs.
Referenced by AddLog(), Clear(), and SetBG().
maxBlock
int MsgBox.maxBlock
Definition at line 37 of file MsgBox.cs.
Referenced by CreateNewBlock(), and WidgetMainText.OnSetContextMenu().
maxLog
int MsgBox.maxLog
Definition at line 39 of file MsgBox.cs.
Referenced by AddLog().
multiLine
bool MsgBox.multiLine
Definition at line 43 of file MsgBox.cs.
newblock
bool MsgBox.newblock
Definition at line 52 of file MsgBox.cs.
Referenced by Clear(), CreateNewBlock(), MarkNewBlock(), and SetCurrentBlock().
prefabs
Prefabs MsgBox.prefabs
Definition at line 31 of file MsgBox.cs.
Referenced by MsgBlock.Append(), and CreateNewBlock().
reverseOrder
bool MsgBox.reverseOrder
Definition at line 41 of file MsgBox.cs.
Referenced by CreateNewBlock().
Property Documentation
maxWidth
float MsgBox.maxWidth get
Definition at line 66 of file MsgBox.cs.
Referenced by MsgLine.AddElement(), and MsgBlock.AddElement().
The documentation for this class was generated from the following file:
Elin/Plugins.UI/MsgBox.cs