Elin Decompiled Documentation: CustomFileContent Class Reference
CustomFileContent Class Reference abstract
Public Member Functions
bool HasFileChanged ()
virtual void OnSetLang (string lang)
void Load ()
Public Member Functions inherited from CustomContent
virtual void OnGameLoad (GameIOContext context)
virtual void OnGameSave (GameIOContext context)
override string ToString ()
Protected Member Functions
abstract void LoadContent ()
Properties
DateTime LastModified = DateTime.MinValue [get, set]
FileInfo File [get, set]
Properties inherited from CustomContent
string ContentId [get, protected set]
EMod Owner [get, protected set]
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Additional Inherited Members
Static Public Member Functions inherited from EClass
static int rndSeed (int a, int seed)
static int rnd (long a)
static int rnd (int a)
static int curve (long _a, int start, int step, int rate=75)
static int sqrt (int a)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Static Public Attributes inherited from EClass
static Core core
Detailed Description
Definition at line 6 of file CustomFileContent.cs.
Member Function Documentation
HasFileChanged()
bool CustomFileContent.HasFileChanged () inline
Definition at line 14 of file CustomFileContent.cs.
    {
        File.Refresh();
        return File.LastWriteTimeUtc != LastModified;
    }
References File, and LastModified.
Referenced by Load().
Load()
void CustomFileContent.Load () inline
Definition at line 24 of file CustomFileContent.cs.
    {
        if (!HasFileChanged())
        {
            return;
        }
        try
        {
            LoadContent();
        }
        catch (Exception message)
        {
            ModUtil.LogModError("exception while loading file '" + base.ContentId + "'", base.Owner);
            Debug.LogError(message);
        }
        finally
        {
            LastModified = File.LastWriteTimeUtc;
        }
    }
References Debug, File, HasFileChanged(), LastModified, and LoadContent().
Referenced by CustomMerchantStock.Generate(), and CustomBiographyContent.RefreshCharaBio().
LoadContent()
abstract void CustomFileContent.LoadContent () protected pure virtual
Implemented in CustomBiographyContent, and CustomMerchantStock.
Referenced by Load().
OnSetLang()
virtual void CustomFileContent.OnSetLang (string lang) inline virtual
Reimplemented in CustomBiographyContent.
Definition at line 20 of file CustomFileContent.cs.
    {
    }
Property Documentation
File
FileInfo CustomFileContent.File get set
Definition at line 12 of file CustomFileContent.cs.
{ get; set; }
Referenced by CustomBiographyContent.CreateFromId(), CustomMerchantStock.CreateFromId(), HasFileChanged(), Load(), and CustomBiographyContent.OnSetLang().
LastModified
DateTime CustomFileContent.LastModified = DateTime.MinValue get set protected
Definition at line 8 of file CustomFileContent.cs.
{ get; set; } = DateTime.MinValue;
Referenced by HasFileChanged(), and Load().
The documentation for this class was generated from the following file:
Elin/CustomFileContent.cs