Elin Decompiled Documentation: Rand Class Reference
Rand Class Reference
Static Public Member Functions
static void InitBytes (int a)
static void UseSeed (int seed, Action action)
static int rndSeed (int a, int seed)
static void SetSeed (int a=-1)
static int Range (int min, int max)
static float Range (float min, float max)
static int rnd (int max)
static float rndf (float max)
static int rndSqrt (int max)
static int rndNormal2 (int max)
static int rndNormal (int max)
Static Public Attributes
static int MaxBytes = 1111
static Random _random = new Random()
static byte[] bytes
Detailed Description
Definition at line 3 of file Rand.cs.
Member Function Documentation
InitBytes()
static void Rand.InitBytes (int a) inline static
Definition at line 11 of file Rand.cs.
    {
        SetSeed(a);
        bytes = new byte[MaxBytes];
        for (int i = 0; i < MaxBytes; i++)
        {
            bytes[i] = (byte)_random.Next(256);
        }
        SetSeed();
    }
References _random, bytes, MaxBytes, and SetSeed().
Referenced by BaseTileMap.OnActivate().
Range() [1/2]
static float Rand.Range (float min, float max) inline static
Definition at line 47 of file Rand.cs.
    {
        return (float)(_random.NextDouble() * (double)(max - min) + (double)min);
    }
References _random.
Range() [2/2]
static int Rand.Range (int min, int max) inline static
Definition at line 42 of file Rand.cs.
    {
        return _random.Next(max - min) + min;
    }
References _random.
Referenced by PartialMap.Apply(), TextConv.Apply(), EffectMeteor.Create(), Biography.GenerateBirthday(), Gender.GetRandom(), Region.GetRandomPoint(), MapGenDungen.OnGenerateTerrain(), AM_Bird.OnUpdateInput(), Chara.PerformWork(), ESoundSource.Play(), Card.PlayEffect(), GenRoom.Populate(), BiomeProfile.Populate(), ClassExtension.Random(), ColorUtil.RandomHSV(), ClassExtension.RandomItemWeighted< TValue >(), Dice.rnd(), ELayer.rnd(), ActorEx.SetOwner(), BaseTaskHarvest.SetTarget(), Zone.SpawnMob(), Expedition.Start(), BiomeProfile.ClusterObj.TryCreate(), BiomeProfile.ClusterThing.TryCreate(), and GameUpdater.Update100ms().
rnd()
static int Rand.rnd (int max) inline static
Definition at line 52 of file Rand.cs.
    {
        if (max > 0)
        {
            return _random.Next(max);
        }
        return 0;
    }
References _random.
Referenced by HoardActor.Activate(), TextConv.Apply(), ZoneBlueprint.GenerateMap(), Gender.GetRandom(), ModItemList< T >.GetRandomID(), ToneDataList.GetToneID(), TransAnime.Init(), HoardActor.MakePair(), GrowSystem.OnExceedLastStage(), ClassExtension.RandomItem< T >(), ClassExtension.RandomItem< TKey, TValue >(), ClassExtension.RandomItem< TValue >(), ActorEx.Refresh(), EClass.rnd(), EMono.rnd(), EScriptable.rnd(), EClass.rndHalf(), rndNormal(), rndNormal2(), rndSeed(), and GrowSystem.SetRandomStage().
rndf()
static float Rand.rndf (float max) inline static
Definition at line 61 of file Rand.cs.
    {
        return Range(0f, max);
    }
References Range.
Referenced by EClass.rndf().
rndNormal()
static int Rand.rndNormal (int max) inline static
Definition at line 77 of file Rand.cs.
    {
        int num = max / 2;
        return num + rnd(rnd(num) + 1) - rnd(rnd(num) + 1);
    }
References rnd().
Referenced by Biography.Generate().
rndNormal2()
static int Rand.rndNormal2 (int max) inline static
Definition at line 71 of file Rand.cs.
    {
        int num = max / 2;
        return num + rnd(rnd(rnd(num) + 1) + 1) - rnd(rnd(rnd(num) + 1) + 1);
    }
References rnd().
rndSeed()
static int Rand.rndSeed (int a, int seed) inline static
Definition at line 29 of file Rand.cs.
    {
        SetSeed(seed);
        int result = rnd(a);
        SetSeed();
        return result;
    }
References rnd(), seed, and SetSeed().
Referenced by CalcMoney.BuySlave().
rndSqrt()
static int Rand.rndSqrt (int max) inline static
Definition at line 66 of file Rand.cs.
    {
        return _random.Next(_random.Next(max) + 1);
    }
References _random.
Referenced by EClass.rndSqrt().
SetSeed()
static void Rand.SetSeed (int a = -1) inline static
Definition at line 37 of file Rand.cs.
    {
        _random = ((a == -1) ? new Random() : new Random(a));
    }
References _random, and Random.
Referenced by ZoneEventDefenseGame._OnTickRound(), TraitGodStatue._OnUse(), ElementContainer.ApplyElementMap(), ElementContainer.ApplyMaterialElementMap(), LayerShippingResult.Awake(), TraitCrafter.Craft(), RecipeCard.Craft(), Spatial.Create(), ThingGen.CreateTreasureContent(), CardRenderer.Draw(), DNA.Generate(), MapGen.GenerateTerrain(), TraitScrollMapTreasure.GetDest(), TraitGodStatue.GetManiGene(), TraitShrine.GetMaterial(), NewsList.GetNews(), GoalGraze.GetPos(), FortuneRollData.GetPrize(), Portrait.GetRandomHairColor(), BaseArea.GetRandomName(), InitBytes(), TraitSeed.LevelSeed(), Zone.ListLandFeats(), RecipeCard.MakeDish(), TraitSeed.MakeSeed(), RecipeCard.MixIngredients(), TraitDrinkMilkMother.OnDrink(), QuestRandom.OnDropReward(), RecipeManager.OnSleep(), TraitScrollMapTreasure.OnUse(), MapGen.Populate(), LayerNewspaper.RefreshAD(), FortuneRollData.RefreshPrize(), rndSeed(), AI_OpenGambleChest.Run(), AI_UseCrafter.Run(), Card.SetLv(), Portrait.SetPerson(), ResearchManager.ShowNewPlans(), Card.SpawnLoot(), Zone.TryGenerateShrine(), Thing.TryLickEnchant(), Chara.TryUpgrade(), and UseSeed().
UseSeed()
static void Rand.UseSeed (int seed, Action action) inline static
Definition at line 22 of file Rand.cs.
    {
        SetSeed(seed);
        action();
        SetSeed();
    }
References seed, and SetSeed().
Referenced by Quest.GetDetailText(), Chara.GetFavCat(), Chara.GetFavFood(), RankedZoneManager.GetList(), Thing.GetName(), Card.GetPrice(), Card.GetRandomColor(), Quest.GetTitle(), LayerNewspaper.OnInit(), TaskDig.OnProgressComplete(), Quest.Parse(), LayerNewspaper.RefreshNews(), and Zone.UpdateQuests().
Member Data Documentation
_random
Random Rand._random = new Random() static
Definition at line 7 of file Rand.cs.
Referenced by InitBytes(), Range(), rnd(), rndSqrt(), SetSeed(), and ClassExtension.Shuffle< TValue >().
bytes
byte [] Rand.bytes static
Definition at line 9 of file Rand.cs.
Referenced by BaseTileMap.DrawRoof(), BaseTileMap.DrawTile(), TileMapElona.DrawTile(), InitBytes(), and BaseTileMap.OnActivate().
MaxBytes
int Rand.MaxBytes = 1111 static
Definition at line 5 of file Rand.cs.
Referenced by BaseTileMap.DrawRoof(), BaseTileMap.DrawTile(), TileMapElona.DrawTile(), and InitBytes().
The documentation for this class was generated from the following file:
Elin/Plugins.basecore/Rand.cs