Elin Decompiled Documentation: UIMapSelector Class Reference
UIMapSelector Class Reference
Public Member Functions
void WriteNote (Zone z)
Public Attributes
UINote note
Image imageZone
Additional Inherited Members
Static Public Member Functions inherited from EMono
static int rnd (int a)
Static Public Attributes inherited from EMono
static Core core
Properties inherited from EMono
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SoundManager Sound [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static CoreDebug debug [get]
Detailed Description
Definition at line 4 of file UIMapSelector.cs.
Member Function Documentation
WriteNote()
void UIMapSelector.WriteNote (Zone z) inline
Definition at line 10 of file UIMapSelector.cs.
    {
        ZoneProfile.Load(z.source.idProfile);
        note.Clear();
        note.AddHeader(z.Name);
        note.AddText(z.source.GetDetail()).Hyphenate();
        note.Space();
        note.AddTopic("climate".lang(), "climateTemp".lang());
        _ = z.source.cost;
        note.AddTopic("ecosystem".lang(), "ecosystemTemp".lang());
        note.Build();
        imageZone.sprite = Resources.Load<Sprite>("Media/Graphics/Image/Zone/" + z.source.image.IsEmpty("default"));
    }
References UINote.AddHeader(), UINote.AddText(), UINote.AddTopic(), UINote.Build(), UINote.Clear(), UIItem.Hyphenate(), ZoneProfile.Load(), Spatial.Name, note, Spatial.source, and UINote.Space().
Referenced by LayerEmbark.SwitchMode().
Member Data Documentation
imageZone
Image UIMapSelector.imageZone
Definition at line 8 of file UIMapSelector.cs.
note
UINote UIMapSelector.note
Definition at line 6 of file UIMapSelector.cs.
Referenced by WriteNote().
The documentation for this class was generated from the following file:
Elin/UIMapSelector.cs