Elin Decompiled Documentation: CharaExtension Class Reference
CharaExtension Class Reference
Static Public Member Functions
static void RefreshSpriteRenderer (this Card card)
static void DestroyImmediate (this Chara chara)
static void SetSpriteOverride (this Chara chara, string spriteId=null)
static void SetPortraitOverride (this Chara chara, string portraitId=null)
static void SetDramaOverride (this Chara chara, string dramaId=null)
Detailed Description
Definition at line 1 of file CharaExtension.cs.
Member Function Documentation
DestroyImmediate()
static void CharaExtension.DestroyImmediate (this Chara chara) inline static
Definition at line 17 of file CharaExtension.cs.
    {
        chara.homeBranch?.BanishMember(chara, skipMsg: true);
        chara.SetFaction(EClass.Wilds);
        EClass.game.cards.listAdv.Remove(chara);
        chara.Destroy();
    }
References FactionBranch.BanishMember(), Game.cards, Card.Destroy(), EClass.game, Chara.homeBranch, CardManager.listAdv, Chara.SetFaction(), and EClass.Wilds.
RefreshSpriteRenderer()
static void CharaExtension.RefreshSpriteRenderer (this Card card) inline static
Definition at line 3 of file CharaExtension.cs.
    {
        CardActor cardActor = card.renderer?.actor;
        if (!(cardActor?.sr == null))
        {
            cardActor.sr.sprite = card.GetSprite();
            if (!(cardActor.sr.sprite == null) && cardActor.mpb != null)
            {
                cardActor.mpb.SetTexture(SpriteHelper.MainTex, cardActor.sr.sprite.texture);
                cardActor.RefreshSprite();
            }
        }
    }
References card, CardActor.mpb, CardActor.RefreshSprite(), and CardActor.sr.
SetDramaOverride()
static void CharaExtension.SetDramaOverride (this Chara chara, string dramaId = null) inline static
Definition at line 36 of file CharaExtension.cs.
    {
        chara.SetStr("drama_override", dramaId);
    }
References Card.SetStr().
SetPortraitOverride()
static void CharaExtension.SetPortraitOverride (this Chara chara, string portraitId = null) inline static
Definition at line 31 of file CharaExtension.cs.
    {
        chara.SetStr("portrait_override", portraitId);
    }
References Card.SetStr().
SetSpriteOverride()
static void CharaExtension.SetSpriteOverride (this Chara chara, string spriteId = null) inline static
Definition at line 25 of file CharaExtension.cs.
    {
        chara.SetStr("sprite_override", spriteId);
        chara.RefreshSpriteRenderer();
    }
References Card.SetStr().
The documentation for this class was generated from the following file:
Elin/CharaExtension.cs