Elin Decompiled Documentation: TraitSet Class Reference
TraitSet Class Reference
Public Member Functions
void Add (Card c)
void Remove (Card c)
Trait GetRandom ()
Trait GetRandom (Chara accessChara)
Trait GetRandom (Func< Card, bool > func)
bool Contains (Card c)
Detailed Description
Definition at line 5 of file TraitSet.cs.
Member Function Documentation
Add()
void TraitSet.Add (Card c) inline
Definition at line 7 of file TraitSet.cs.
    {
        Add(c.uid, c);
    }
References Add(), and Card.uid.
Referenced by Add().
Contains()
bool TraitSet.Contains (Card c) inline
Definition at line 36 of file TraitSet.cs.
    {
        return ContainsKey(c.uid);
    }
References Card.uid.
GetRandom() [1/3]
Trait TraitSet.GetRandom () inline
Definition at line 17 of file TraitSet.cs.
    {
        return this.RandomItem()?.trait;
    }
Referenced by AIAct.DoGoto< T >(), and GetRandom().
GetRandom() [2/3]
Trait TraitSet.GetRandom (Chara accessChara) inline
Definition at line 22 of file TraitSet.cs.
    {
        return GetRandom((Card t) => accessChara == null || accessChara.HasAccess(t));
    }
References GetRandom(), and Chara.HasAccess().
GetRandom() [3/3]
Trait TraitSet.GetRandom (Func< Card, bool > func) inline
Definition at line 27 of file TraitSet.cs.
    {
        if (func == null)
        {
            return GetRandom();
        }
        return base.Values.Where(func).RandomItem()?.trait;
    }
References GetRandom().
Remove()
void TraitSet.Remove (Card c) inline
Definition at line 12 of file TraitSet.cs.
    {
        Remove(c.uid);
    }
References Remove(), and Card.uid.
Referenced by Remove().
The documentation for this class was generated from the following file:
Elin/TraitSet.cs