Elin Decompiled Documentation: LayerCraftFloat Class Reference
LayerCraftFloat Class Reference
Public Member Functions
override void OnInit ()
override void OnSwitchContent (Window window)
void Update ()
void OnCompleteCraft ()
void RefreshCraft ()
void ShowContextMenu (Recipe a)
void RefreshDisassemble ()
void RefreshSize ()
Public Member Functions inherited from ELayer
override void OnBeforeAddLayer ()
void InitInspector ()
sealed override void Init ()
override void OnAfterAddLayer ()
void TryShowHelp ()
void AddLayerToUI (string id)
void TryShowHint (string _langHint=null)
void TalkHomeMemeber (string id)
void TalkMaid (string id)
override void OnRightClick ()
Public Member Functions inherited from Layer
virtual string GetTextHeader (Window window)
virtual bool HeaderIsListOf (int id)
virtual void Init ()
virtual void OnInit ()
virtual void OnAfterInit ()
virtual void ApplySkin ()
void ShowScreenLock (string id)
void UpdateInput ()
virtual void OnUpdateInput ()
virtual void OnRightClick ()
virtual bool OnBack ()
virtual void OnChangeLayer ()
virtual void OnCreate ()
void _AddLayer (string id)
Layer AddLayer (string id)
T AddLayer< T > ()
T AddLayer< T > (string id)
T AddLayerDontCloseOthers< T > ()
Layer AddLayerDontCloseOthers (Layer l)
T GetOrAddLayer< T > ()
virtual void OnBeforeAddLayer ()
virtual void OnAfterAddLayer ()
Layer AddLayer (Layer l)
void ToggleLayer (string id)
T ToggleLayer< T > (string id=null)
void WaitAndClose ()
void OnClickClose ()
virtual void Close ()
void CloseLayers ()
void RemoveLayers (bool removeImportant=false)
bool RemoveLayer< T > ()
void RemoveLayer (Layer l)
virtual void OnKill ()
Layer SetOnKill (Action action)
void DisableClose ()
void Delay (float duration=0.05f)
Layer SetDelay (float d)
Layer GetLayer (string id)
T GetLayer< T > (bool fromTop=false)
Layer GetTopLayer ()
void SwitchContent (int idWindow, int i)
virtual void OnSwitchContent (Window window)
Layer SetTitles (string langList, string idHeaderRow=null)
bool IsBlockWidgetClick ()
bool IsHideHud ()
bool IsAllowGeneralInput ()
bool IsUseBlur ()
bool IsPointerOnLayer ()
void ApplySkin ()
Public Attributes
UIDynamicList list
Recipe recipe
UIButton moldButtonContext
int maxSize
int paddingY
int paddingY2
string idLastRecipe
Public Attributes inherited from Layer
Option option
UnityEvent onKill
Anime animeIn
Anime animeOut
bool closeOthers
bool defaultActionMode = true
Button screenLock
Layer parent
string idLayer
List< Layer > layers = new List<Layer>()
Vector2 lastParentPos
List< Window > windows = new List<Window>()
string langHint
Static Public Attributes
static LayerCraftFloat Instance
Static Public Attributes inherited from Layer
static int skipInput
static bool closeOnRightClick
static bool rightClicked
static bool cancelKeyDown
static bool ignoreSounds
static Transform blurStopInstance
static string[] searchPath = new string[3] { "Layer", "Layer/Dialog", "Layer/LayerHome" }
Additional Inherited Members
Static Public Member Functions inherited from ELayer
static int rnd (int a)
Static Public Member Functions inherited from Layer
static T Create< T > ()
static T Create< T > (string path)
static Layer Create (string path)
Protected Member Functions inherited from ELayer
sealed override void _Close ()
sealed override void Kill ()
Protected Member Functions inherited from Layer
virtual void Awake ()
virtual void _Close ()
virtual void Kill ()
Protected Attributes inherited from Layer
RectTransform _rect
bool isDestroyed
Properties inherited from ELayer
static Core core [get]
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static FactionBranch Branch [get]
static Faction Home [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static CoreConfig config [get]
static GameSetting setting [get]
static ColorProfile Colors [get]
static SourceManager sources [get]
static World world [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
bool IsFloat [get]
virtual string IdHelp [get]
Properties inherited from Layer
Layer TopLayer [get]
string uid [get]
virtual RectTransform rectLayers [get]
virtual bool blockWidgetClick [get]
Detailed Description
Definition at line 4 of file LayerCraftFloat.cs.
Member Function Documentation
OnCompleteCraft()
void LayerCraftFloat.OnCompleteCraft () inline
Definition at line 63 of file LayerCraftFloat.cs.
    {
    }
Referenced by TaskCraft.Run().
OnInit()
override void LayerCraftFloat.OnInit () inline virtual
Reimplemented from Layer.
Definition at line 22 of file LayerCraftFloat.cs.
    {
        Instance = this;
    }
References Instance.
OnSwitchContent()
override void LayerCraftFloat.OnSwitchContent (Window window) inline virtual
Reimplemented from Layer.
Definition at line 27 of file LayerCraftFloat.cs.
    {
        if (ELayer.core.IsGameStarted)
        {
            ELayer.game.updater.recipe.Build(ELayer.pc.pos, RecipeUpdater.Mode.Immediate);
        }
    }
References RecipeUpdater.Build(), ELayer.core, ELayer.game, Core.IsGameStarted, ELayer.pc, Card.pos, GameUpdater.recipe, and Game.updater.
RefreshCraft()
void LayerCraftFloat.RefreshCraft () inline
Definition at line 67 of file LayerCraftFloat.cs.
    {
        list.callbacks = new UIList.Callback<Recipe, ButtonGrid>
        {
            onClick = delegate(Recipe a, ButtonGrid b)
            {
                ELayer.ui.RemoveLayers();
                ELayer.game.updater.recipe.Build(ELayer.pc.pos, RecipeUpdater.Mode.Validate);
                if (!RecipeUpdater.recipes.Contains(a))
                {
                    SE.BeepSmall();
                    ELayer.game.updater.recipe.Build(ELayer.pc.pos, RecipeUpdater.Mode.Immediate);
                }
                else
                {
                    a.OnChangeIngredient();
                    recipe = a;
                    idLastRecipe = recipe.id;
                    if (!ELayer.player.waitingInput)
                    {
                        SE.BeepSmall();
                    }
                    else
                    {
                        TaskCraft taskCraft = new TaskCraft
{
                            recipe = recipe,
                            num = 1,
                            repeat = false,
                            floatMode = true
                        };
                        taskCraft.ResetReq();
                        if (!taskCraft.IsIngredientsValid(destoryResources: false, taskCraft.num))
{
                            SE.Beep();
                        }
                        else
{
                            ELayer.pc.SetAI(taskCraft);
                            ActionMode.Adv.SetTurbo();
                        }
                    }
                }
            },
            onRedraw = delegate(Recipe a, ButtonGrid b, int i)
            {
                b.SetCraftRecipe(a, ButtonGrid.Mode.RecipeGrid, tooltip: true);
                if (!ELayer.player.recipes.hoveredRecipes.Contains(a.id))
                {
                    b.Attach("recipe_new", rightAttach: false);
                }
                b.onRightClick = delegate
                {
                    ShowContextMenu(a);
                };
            },
            onList = delegate
            {
                foreach (Recipe recipe in RecipeUpdater.recipes)
                {
                    list.Add(recipe);
                }
            }
        };
        list.List();
        RefreshSize();
        list.dsv.OnResize();
    }
References UIDynamicList.Add(), ActionMode.Adv, ButtonGrid.Attach(), RecipeUpdater.Build(), UIDynamicList.dsv, ELayer.game, RecipeManager.hoveredRecipes, Recipe.id, idLastRecipe, TaskCraft.IsIngredientsValid(), list, UIDynamicList.List(), TaskCraft.num, Recipe.OnChangeIngredient(), ELayer.pc, ELayer.player, Card.pos, GameUpdater.recipe, recipe, Player.recipes, RecipeUpdater.recipes, RefreshSize(), TaskCraft.ResetReq(), Chara.SetAI(), ButtonGrid.SetCraftRecipe(), AM_Adv.SetTurbo(), ShowContextMenu(), ELayer.ui, Game.updater, and Player.waitingInput.
Referenced by RecipeUpdater.RunRecipe().
RefreshDisassemble()
void LayerCraftFloat.RefreshDisassemble () inline
Definition at line 189 of file LayerCraftFloat.cs.
    {
        list.callbacks = new UIList.Callback<Thing, ButtonGrid>
        {
            onClick = delegate(Thing a, ButtonGrid b)
            {
                if (!ELayer.player.waitingInput)
                {
                    SE.BeepSmall();
                }
                else
                {
                    a.Disassemble();
                    ELayer.player.EndTurn();
                }
            },
            onRedraw = delegate(Thing a, ButtonGrid b, int i)
            {
                b.SetCard(a, ButtonGrid.Mode.RecipeGrid, delegate(UINote n)
                {
                    RecipeSource recipeSource = RecipeManager.Get(a.id);
                    if (recipeSource != null)
                    {
                        n.Space();
                        Recipe.Create(recipeSource).WriteReqSkill(n);
                    }
                });
                b.mainText.SetActive(enable: false);
            },
            onList = delegate
            {
                foreach (Thing item in RecipeUpdater.listD)
                {
                    list.Add(item);
                }
            }
        };
        list.List();
        RefreshSize();
        list.dsv.OnResize();
    }
References UIDynamicList.Add(), Recipe.Create(), Thing.Disassemble(), UIDynamicList.dsv, Player.EndTurn(), RecipeManager.Get(), Card.id, if(), item, list, UIDynamicList.List(), RecipeUpdater.listD, UIButton.mainText, ELayer.player, RefreshSize(), ButtonGrid.SetCard(), UINote.Space(), and Player.waitingInput.
Referenced by RecipeUpdater.RunDisassemble().
RefreshSize()
void LayerCraftFloat.RefreshSize () inline
Definition at line 231 of file LayerCraftFloat.cs.
    {
        list.dsv.GetComponent<UIScrollView>().enabled = list.ItemCount > 0;
        RectTransform rectTransform = windows[0].Rect();
        float x = rectTransform.sizeDelta.x;
        float num = list.Rect().sizeDelta.y;
        if (num > (float)maxSize)
        {
            num = maxSize;
        }
        rectTransform.sizeDelta = new Vector2(x, num + (float)((list.ItemCount > 0) ? paddingY : paddingY2));
        rectTransform.RebuildLayout();
    }
References UIDynamicList.dsv, UIDynamicList.ItemCount, list, maxSize, paddingY, paddingY2, and Layer.windows.
Referenced by RefreshCraft(), and RefreshDisassemble().
ShowContextMenu()
void LayerCraftFloat.ShowContextMenu (Recipe a) inline
Definition at line 136 of file LayerCraftFloat.cs.
    {
        UIContextMenu i = ELayer.ui.CreateContextMenuInteraction();
        Point point = ELayer.pc.pos.Copy();
        foreach (Recipe.Ingredient ing in a.ingredients)
        {
            UIContextMenu uIContextMenu = ((a.ingredients.Count == 1) ? i : i.AddChild(ing.GetName() + "x" + ing.req));
            List<Thing> list = new List<Thing>();
            foreach (Thing thing in ELayer.pc.things)
            {
                thing.GetIngredients(ing, list);
            }
            for (int j = point.x - 1; j < point.x + 2; j++)
            {
                if (j < 0 || j >= ELayer._map.Size)
                {
                    continue;
                }
                for (int k = point.z - 1; k < point.z + 2; k++)
                {
                    if (k < 0 || k >= ELayer._map.Size)
                    {
                        continue;
                    }
                    Cell cell = ELayer._map.cells[j, k];
                    if (cell.detail == null || cell.detail.things.Count == 0)
                    {
                        continue;
                    }
                    foreach (Thing thing2 in cell.detail.things)
                    {
                        thing2.GetIngredients(ing, list);
                    }
                }
            }
            foreach (Thing t in list)
            {
                UIButton uIButton = Util.Instantiate(moldButtonContext);
                uIContextMenu.AddGameObject(uIButton);
                t.SetImage(uIButton.icon);
                uIButton.mainText.text = t.Name + ((t.parent == ELayer.pc) ? "" : ("(" + ((t.parent == ELayer._zone) ? "ground".lang() : (t.parent as Card)?.Name) + ")"));
                uIButton.onClick.AddListener(delegate
                {
                    ing.thing = t;
                    SE.ClickOk();
                    this.list.List();
                    i.Hide();
                });
            }
        }
        i.Show();
    }
References ELayer._map, ELayer._zone, UIContextMenu.AddChild(), Map.cells, Point.Copy(), Cell.detail, Thing.GetIngredients(), UIContextMenu.Hide(), UIButton.icon, Recipe.ingredients, list, moldButtonContext, Card.parent, ELayer.pc, Card.pos, Card.SetImage(), UIContextMenu.Show(), MapBounds.Size, Card.things, CellDetail.things, ELayer.ui, Util, Point.x, and Point.z.
Referenced by RefreshCraft(), and Update().
Update()
void LayerCraftFloat.Update () inline
Definition at line 35 of file LayerCraftFloat.cs.
    {
        if (EInput.middleMouse.down)
        {
            ButtonGrid componentOf = InputModuleEX.GetComponentOf<ButtonGrid>();
            if ((bool)componentOf && componentOf.transform.IsChildOf(base.transform))
            {
                Recipe recipe = componentOf.recipe;
                if (recipe != null && windows[0].idTab == 0)
                {
                    ShowContextMenu(recipe);
                }
            }
        }
        if (Input.GetMouseButton(0))
        {
            ButtonGrid componentOf2 = InputModuleEX.GetComponentOf<ButtonGrid>();
            if ((bool)componentOf2 && componentOf2.transform.IsChildOf(base.transform) && ELayer.player.waitingInput && ELayer.pc.HasNoGoal && componentOf2.recipe.id == idLastRecipe)
            {
                list.callbacks.OnClick(componentOf2.recipe, componentOf2);
            }
        }
        else
        {
            idLastRecipe = null;
        }
    }
References BaseList.callbacks, ButtonState.down, idLastRecipe, list, EInput.middleMouse, ButtonGrid.recipe, recipe, ShowContextMenu(), and Layer.windows.
Member Data Documentation
idLastRecipe
string LayerCraftFloat.idLastRecipe
Definition at line 20 of file LayerCraftFloat.cs.
Referenced by RefreshCraft(), and Update().
Instance
LayerCraftFloat LayerCraftFloat.Instance static
Definition at line 6 of file LayerCraftFloat.cs.
Referenced by RecipeUpdater.Build(), OnInit(), TaskCraft.Run(), RecipeUpdater.RunDisassemble(), and RecipeUpdater.RunRecipe().
list
UIDynamicList LayerCraftFloat.list
Definition at line 8 of file LayerCraftFloat.cs.
Referenced by RefreshCraft(), RefreshDisassemble(), RefreshSize(), ShowContextMenu(), and Update().
maxSize
int LayerCraftFloat.maxSize
Definition at line 14 of file LayerCraftFloat.cs.
Referenced by RefreshSize().
moldButtonContext
UIButton LayerCraftFloat.moldButtonContext
Definition at line 12 of file LayerCraftFloat.cs.
Referenced by ShowContextMenu().
paddingY
int LayerCraftFloat.paddingY
Definition at line 16 of file LayerCraftFloat.cs.
Referenced by RefreshSize().
paddingY2
int LayerCraftFloat.paddingY2
Definition at line 18 of file LayerCraftFloat.cs.
Referenced by RefreshSize().
recipe
Recipe LayerCraftFloat.recipe
Definition at line 10 of file LayerCraftFloat.cs.
Referenced by RefreshCraft(), and Update().
The documentation for this class was generated from the following file:
Elin/LayerCraftFloat.cs