Elin Decompiled Documentation: LayerCollectible Class Reference
LayerCollectible Class Reference
Public Member Functions
override void OnAfterInit ()
void Refresh ()
void SetButton (Hoard.Item a, UIButton b)
void RefreshInfo (UIButton button, bool force=false)
Public Member Functions inherited from ELayer
override void OnBeforeAddLayer ()
void InitInspector ()
sealed override void Init ()
override void OnAfterAddLayer ()
void TryShowHelp ()
void AddLayerToUI (string id)
void TryShowHint (string _langHint=null)
void TalkHomeMemeber (string id)
void TalkMaid (string id)
override void OnRightClick ()
Public Member Functions inherited from Layer
virtual string GetTextHeader (Window window)
virtual bool HeaderIsListOf (int id)
virtual void Init ()
virtual void OnInit ()
virtual void OnAfterInit ()
virtual void ApplySkin ()
void ShowScreenLock (string id)
void UpdateInput ()
virtual void OnUpdateInput ()
virtual void OnRightClick ()
virtual bool OnBack ()
virtual void OnChangeLayer ()
virtual void OnCreate ()
void _AddLayer (string id)
Layer AddLayer (string id)
T AddLayer< T > ()
T AddLayer< T > (string id)
T AddLayerDontCloseOthers< T > ()
Layer AddLayerDontCloseOthers (Layer l)
T GetOrAddLayer< T > ()
virtual void OnBeforeAddLayer ()
virtual void OnAfterAddLayer ()
Layer AddLayer (Layer l)
void ToggleLayer (string id)
T ToggleLayer< T > (string id=null)
void WaitAndClose ()
void OnClickClose ()
virtual void Close ()
void CloseLayers ()
void RemoveLayers (bool removeImportant=false)
bool RemoveLayer< T > ()
void RemoveLayer (Layer l)
virtual void OnKill ()
Layer SetOnKill (Action action)
void DisableClose ()
void Delay (float duration=0.05f)
Layer SetDelay (float d)
Layer GetLayer (string id)
T GetLayer< T > (bool fromTop=false)
Layer GetTopLayer ()
void SwitchContent (int idWindow, int i)
virtual void OnSwitchContent (Window window)
Layer SetTitles (string langList, string idHeaderRow=null)
bool IsBlockWidgetClick ()
bool IsHideHud ()
bool IsAllowGeneralInput ()
bool IsUseBlur ()
bool IsPointerOnLayer ()
void ApplySkin ()
Public Attributes
UIList list
UIText textName
UIText textDetail
UIButton selected
UIButton lastShown
Image imageItem
Vector3 contextFix
Func< Hoard.Item, bool > onClick
Public Attributes inherited from Layer
Option option
UnityEvent onKill
Anime animeIn
Anime animeOut
bool closeOthers
bool defaultActionMode = true
Button screenLock
Layer parent
string idLayer
List< Layer > layers = new List<Layer>()
Vector2 lastParentPos
List< Window > windows = new List<Window>()
string langHint
Properties
Hoard hoard [get]
Properties inherited from ELayer
static Core core [get]
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static FactionBranch Branch [get]
static Faction Home [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static CoreConfig config [get]
static GameSetting setting [get]
static ColorProfile Colors [get]
static SourceManager sources [get]
static World world [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
bool IsFloat [get]
virtual string IdHelp [get]
Properties inherited from Layer
Layer TopLayer [get]
string uid [get]
virtual RectTransform rectLayers [get]
virtual bool blockWidgetClick [get]
Private Member Functions
void Update ()
Additional Inherited Members
Static Public Member Functions inherited from ELayer
static int rnd (int a)
Static Public Member Functions inherited from Layer
static T Create< T > ()
static T Create< T > (string path)
static Layer Create (string path)
Static Public Attributes inherited from Layer
static int skipInput
static bool closeOnRightClick
static bool rightClicked
static bool cancelKeyDown
static bool ignoreSounds
static Transform blurStopInstance
static string[] searchPath = new string[3] { "Layer", "Layer/Dialog", "Layer/LayerHome" }
Protected Member Functions inherited from ELayer
sealed override void _Close ()
sealed override void Kill ()
Protected Member Functions inherited from Layer
virtual void Awake ()
virtual void _Close ()
virtual void Kill ()
Protected Attributes inherited from Layer
RectTransform _rect
bool isDestroyed
Detailed Description
Definition at line 5 of file LayerCollectible.cs.
Member Function Documentation
OnAfterInit()
override void LayerCollectible.OnAfterInit () inline virtual
Reimplemented from Layer.
Definition at line 25 of file LayerCollectible.cs.
    {
        if (hoard.items.Count == 0)
        {
            hoard.Add("gold", 1);
        }
        Refresh();
    }
References Hoard.Add(), hoard, Hoard.items, and Refresh().
Refresh()
void LayerCollectible.Refresh () inline
Definition at line 34 of file LayerCollectible.cs.
    {
        ELayer.ui.GetLayer<LayerHoard>();
        list.callbacks = new UIList.Callback<Hoard.Item, UIButton>
        {
            onClick = delegate(Hoard.Item a, UIButton b)
            {
                selected = b;
                if (onClick != null)
                {
                    if (onClick(a))
                    {
                        Close();
                    }
                }
                else
                {
                    UIContextMenu uIContextMenu = ELayer.ui.contextMenu.Create("ContextHoard");
                    int max = a.num;
                    if (max > 1 && a.IsUnique)
                    {
                        max = 1;
                    }
                    uIContextMenu.AddSlider("display", (float n) => n + " / " + max, a.show, delegate(float v)
                    {
                        a.show = (int)v;
                        SetButton(a, b);
                        RefreshInfo(b, force: true);
                    }, 0f, max, isInt: true, hideOther: false);
                    uIContextMenu.AddToggle("displayRandom", a.random, delegate(bool on)
                    {
                        a.random = on;
                    });
                    uIContextMenu.Show(EInput.uiMousePosition + contextFix);
                }
            },
            onInstantiate = delegate(Hoard.Item a, UIButton b)
            {
                SetButton(a, b);
            }
        };
        foreach (SourceCollectible.Row row in ELayer.sources.collectibles.rows)
        {
            if (hoard.items.ContainsKey(row.id))
            {
                list.Add(hoard.items[row.id]);
            }
        }
        list.Refresh();
        selected = list.buttons[0].component as UIButton;
        RefreshInfo(selected);
    }
References UIList.Add(), UIContextMenu.AddSlider(), UIContextMenu.AddToggle(), UIList.buttons, Layer.Close(), SourceManager.collectibles, contextFix, hoard, Hoard.items, list, onClick, UIList.Refresh(), RefreshInfo(), selected, SetButton(), UIContextMenu.Show(), ELayer.sources, ELayer.ui, and EInput.uiMousePosition.
Referenced by OnAfterInit().
RefreshInfo()
void LayerCollectible.RefreshInfo (UIButton button, bool force = false) inline
Definition at line 113 of file LayerCollectible.cs.
    {
        if (force || (!(lastShown == button) && (bool)button))
        {
            Hoard.Item item = button.refObj as Hoard.Item;
            string text = "collectibleTitle".lang(item.Source.GetName(), item.num.ToString() ?? "", item.show.ToString() ?? "");
            if (item.IsUnique)
            {
                text += " UNIQUE";
            }
            textName.text = text;
            textDetail.text = item.Source.GetText("detail", returnNull: true).IsEmpty("none".lang());
            imageItem.sprite = hoard.GetSprite(item.id);
            imageItem.SetNativeSize();
            lastShown = button;
        }
    }
References Hoard.GetSprite(), hoard, imageItem, item, and lastShown.
Referenced by Refresh(), and Update().
SetButton()
void LayerCollectible.SetButton (Hoard::Item a, UIButton b) inline
Definition at line 100 of file LayerCollectible.cs.
    {
        string text = a.num.ToString() ?? "";
        if (a.num != a.show)
        {
            text = text + " (" + a.show + ")";
        }
        b.mainText.text = text;
        b.icon.sprite = hoard.GetSprite(a.id);
        b.icon.SetNativeSize();
        b.refObj = a;
    }
References Hoard.GetSprite(), hoard, and UIButton.icon.
Referenced by Refresh().
Update()
void LayerCollectible.Update () inline private
Definition at line 87 of file LayerCollectible.cs.
    {
        UIButton componentOf = InputModuleEX.GetComponentOf<UIButton>();
        if ((bool)componentOf && componentOf.refObj is Hoard.Item)
        {
            RefreshInfo(componentOf);
        }
        else
        {
            RefreshInfo(selected);
        }
    }
References RefreshInfo(), and selected.
Member Data Documentation
contextFix
Vector3 LayerCollectible.contextFix
Definition at line 19 of file LayerCollectible.cs.
Referenced by Refresh().
imageItem
Image LayerCollectible.imageItem
Definition at line 17 of file LayerCollectible.cs.
Referenced by RefreshInfo().
lastShown
UIButton LayerCollectible.lastShown
Definition at line 15 of file LayerCollectible.cs.
Referenced by RefreshInfo().
list
UIList LayerCollectible.list
Definition at line 7 of file LayerCollectible.cs.
Referenced by Refresh().
onClick
Func<Hoard.Item, bool> LayerCollectible.onClick
Definition at line 21 of file LayerCollectible.cs.
Referenced by Refresh().
selected
UIButton LayerCollectible.selected
Definition at line 13 of file LayerCollectible.cs.
Referenced by Refresh(), and Update().
textDetail
UIText LayerCollectible.textDetail
Definition at line 11 of file LayerCollectible.cs.
textName
UIText LayerCollectible.textName
Definition at line 9 of file LayerCollectible.cs.
Property Documentation
hoard
Hoard LayerCollectible.hoard get
Definition at line 23 of file LayerCollectible.cs.
Referenced by OnAfterInit(), Refresh(), RefreshInfo(), and SetButton().
The documentation for this class was generated from the following file:
Elin/LayerCollectible.cs