Elin Decompiled Documentation: SourceThingV Class Reference
SourceThingV Class Reference
Classes
class Row
Public Member Functions
override Row CreateRow ()
override Row CreateRowByMapping (IReadOnlyDictionary< string, int > mapping)
override void SetRow (Row r)
override IReadOnlyDictionary< string, int > GetRowMapping ()
override IReadOnlyDictionary< string, string > GetTypeMapping ()
override void RestorePref ()
override void ValidatePref ()
override void Reset ()
override void OnAfterImportData ()
virtual void OnImportRow (Row _r, SourceThing.Row c)
Public Member Functions inherited from SourceDataString< SourceThingV.Row >
override T GetRow (string id)
Static Public Attributes
static readonly IReadOnlyDictionary< string, int > RowMapping
static readonly IReadOnlyDictionary< string, string > TypeMapping
Properties
override string[] ImportFields [get]
Detailed Description
Definition at line 6 of file SourceThingV.cs.
Member Function Documentation
CreateRow()
override Row SourceThingV.CreateRow () inline
Definition at line 74 of file SourceThingV.cs.
    {
        return new Row
        {
            id = SourceData.GetString(0),
            _origin = SourceData.GetString(1),
            name_JP = SourceData.GetString(2),
            unit_JP = SourceData.GetString(3),
            name = SourceData.GetString(4),
            unit = SourceData.GetString(5),
            tiles = SourceData.GetIntArray(6),
            skins = SourceData.GetIntArray(7),
            parse = SourceData.GetStringArray(8),
            vals = SourceData.GetStringArray(9),
            trait = SourceData.GetStringArray(11),
            LV = SourceData.GetInt(12),
            chance = SourceData.GetInt(13),
            value = SourceData.GetInt(14),
            weight = SourceData.GetInt(15),
            recipeKey = SourceData.GetStringArray(16),
            factory = SourceData.GetStringArray(17),
            components = SourceData.GetStringArray(18),
            defMat = SourceData.GetString(19),
            category = SourceData.GetString(20),
            tag = SourceData.GetStringArray(21),
            detail_JP = SourceData.GetString(22),
            detail = SourceData.GetString(23)
        };
    }
References SourceData< T, T2 >.GetInt(), SourceData< T, T2 >.GetIntArray(), SourceData< T, T2 >.GetString(), and SourceData< T, T2 >.GetStringArray().
CreateRowByMapping()
override Row SourceThingV.CreateRowByMapping (IReadOnlyDictionary< string, int > mapping) inline
Definition at line 104 of file SourceThingV.cs.
    {
        return new Row
        {
            id = SourceData.GetString(mapping["id"]),
            _origin = SourceData.GetString(mapping["_origin"]),
            name_JP = SourceData.GetString(mapping["name_JP"]),
            unit_JP = SourceData.GetString(mapping["unit_JP"]),
            name = SourceData.GetString(mapping["name"]),
            unit = SourceData.GetString(mapping["unit"]),
            tiles = SourceData.GetIntArray(mapping["tiles"]),
            skins = SourceData.GetIntArray(mapping["skins"]),
            parse = SourceData.GetStringArray(mapping["parse"]),
            vals = SourceData.GetStringArray(mapping["vals"]),
            trait = SourceData.GetStringArray(mapping["trait"]),
            LV = SourceData.GetInt(mapping["LV"]),
            chance = SourceData.GetInt(mapping["chance"]),
            value = SourceData.GetInt(mapping["value"]),
            weight = SourceData.GetInt(mapping["weight"]),
            recipeKey = SourceData.GetStringArray(mapping["recipeKey"]),
            factory = SourceData.GetStringArray(mapping["factory"]),
            components = SourceData.GetStringArray(mapping["components"]),
            defMat = SourceData.GetString(mapping["defMat"]),
            category = SourceData.GetString(mapping["category"]),
            tag = SourceData.GetStringArray(mapping["tag"]),
            detail_JP = SourceData.GetString(mapping["detail_JP"]),
            detail = SourceData.GetString(mapping["detail"])
        };
    }
References SourceData< T, T2 >.GetInt(), SourceData< T, T2 >.GetIntArray(), SourceData< T, T2 >.GetString(), and SourceData< T, T2 >.GetStringArray().
GetRowMapping()
override IReadOnlyDictionary< string, int > SourceThingV.GetRowMapping () inline
Definition at line 139 of file SourceThingV.cs.
    {
        return RowMapping;
    }
References RowMapping.
GetTypeMapping()
override IReadOnlyDictionary< string, string > SourceThingV.GetTypeMapping () inline
Definition at line 144 of file SourceThingV.cs.
    {
        return TypeMapping;
    }
References TypeMapping.
OnAfterImportData()
override void SourceThingV.OnAfterImportData () inline
Definition at line 190 of file SourceThingV.cs.
    {
        Dictionary<string, SourceThing.Row> dictionary = new Dictionary<string, SourceThing.Row>();
        foreach (SourceThing.Row row2 in EClass.sources.things.rows)
        {
            dictionary[row2.id] = row2;
        }
        Dictionary<string, System.Reflection.FieldInfo> rowFields = new SourceThing.Row().GetRowFields();
        foreach (Row row3 in rows)
        {
            SourceThing.Row row = new SourceThing.Row();
            SourceThing.Row obj = dictionary[row3._origin];
            string key;
            foreach (KeyValuePair<string, System.Reflection.FieldInfo> item in rowFields)
            {
                item.Deconstruct(out key, out var value);
                string text = key;
                System.Reflection.FieldInfo fieldInfo = value;
                if (!(text == "parse"))
                {
                    fieldInfo.SetValue(row, fieldInfo.GetValue(obj));
                }
            }
            row.id = row3.id;
            row._origin = row3._origin;
            if (row3.LV != 0)
            {
                row.LV = row3.LV;
            }
            if (row3.chance != -1)
            {
                row.chance = row3.chance;
            }
            if (row3.value != -1)
            {
                row.value = row3.value;
            }
            else
            {
                row.value += EClass.rnd(row.value / 2);
            }
            if (row3.weight != -1)
            {
                row.weight = row3.weight;
            }
            if (!row3.tiles.IsEmpty())
            {
                row.tiles = row3.tiles;
            }
            if (!row3.skins.IsEmpty())
            {
                row.skins = row3.skins;
            }
            if (!row3.name.IsEmpty())
            {
                row.name = row3.name;
            }
            if (!row3.name_JP.IsEmpty())
            {
                row.name_JP = row3.name_JP;
            }
            if (!row3.detail.IsEmpty())
            {
                row.detail = row3.detail;
            }
            if (!row3.detail_JP.IsEmpty())
            {
                row.detail_JP = row3.detail_JP;
            }
            if (!row3.unit.IsEmpty())
            {
                row.unit = row3.unit;
            }
            if (!row3.unit_JP.IsEmpty())
            {
                row.unit_JP = row3.unit_JP;
            }
            if (!row3.vals.IsEmpty())
            {
                row.vals = row3.vals;
            }
            if (!row3.components.IsEmpty())
            {
                row.components = row3.components;
            }
            if (!row3.defMat.IsEmpty())
            {
                row.defMat = row3.defMat;
            }
            if (!row3.trait.IsEmpty())
            {
                row.trait = row3.trait;
            }
            if (!row3.category.IsEmpty())
            {
                row.category = row3.category;
            }
            if (!row3.factory.IsEmpty())
            {
                row.factory = row3.factory;
            }
            if (!row3.tag.IsEmpty())
            {
                row.tag = row3.tag;
            }
            row.recipeKey = row3.recipeKey;
            if (!row3.parse.IsEmpty())
            {
                key = row3._origin;
                switch (key)
                {
                case "lamp_ceil2":
                case "window":
                case "windowL":
                    row.idExtra = row3.parse[0];
                    break;
                default:
                {
                    string[] parse = row3.parse;
                    for (int i = 0; i < parse.Length; i++)
                    {
                        string[] array = parse[i].Split('/');
                        switch (array[0])
{
                        case "elec":
                            row.electricity = array[1].ToInt();
                            break;
                        case "render":
                            row._idRenderData = array[1];
                            break;
                        case "tiletype":
                            row._tileType = array[1];
                            break;
                        case "anime":
                            row.anime = ((array.Length <= 4) ? ((array.Length <= 3) ? new int[2]
{
                                array[1].ToInt(),
                                array[2].ToInt()
                            } : new int[3]
{
                                array[1].ToInt(),
                                array[2].ToInt(),
                                array[3].ToInt()
                            }) : new int[4]
{
                                array[1].ToInt(),
                                array[2].ToInt(),
                                array[3].ToInt(),
                                array[4].ToInt()
                            });
                            break;
                        case "skin":
{
                            string[] array3 = array[1].Split('|');
                            row.skins = new int[array3.Length];
                            for (int k = 0; k < array3.Length; k++)
{
                                row.skins[k] = array3[k].ToInt();
                            }
                            break;
                        }
                        case "alt":
{
                            string[] array2 = array[1].Split('|');
                            row.altTiles = new int[array2.Length];
                            for (int j = 0; j < array2.Length; j++)
{
                                row.altTiles[j] = array2[j].ToInt();
                            }
                            row.ignoreAltFix = true;
                            break;
                        }
                        case "naming":
                            row.naming = array[1];
                            break;
                        case "ex":
                            row.idActorEx = array[1];
                            break;
                        case "sound":
                            row.idSound = array[1];
                            break;
                        case "color":
                            row.colorMod = 100;
                            break;
                        case "no_color":
                            row.colorMod = 0;
                            break;
                        case "unique":
                            row.quality = 4;
                            break;
                        case "ele":
{
                            int[] second = new int[2]
{
                                Core.GetCurrent().sources.elements.alias[array[1]].id,
                                array[2].ToInt()
                            };
                            row.elements = row.elements.Concat(second).ToArray();
                            break;
                        }
                        }
                    }
                    break;
                }
                }
            }
            OnImportRow(row3, row);
            row.OnImportData(EClass.sources.things);
            EClass.sources.things.rows.Add(row);
        }
        rows.Clear();
    }
References CardRow._origin, RenderRow.category, RenderRow.chance, RenderRow.components, RenderRow.defMat, RenderRow.detail, RenderRow.detail_JP, SourceManager.elements, RenderRow.factory, Core.GetCurrent(), SourceData< T, T2 >.BaseRow.GetRowFields(), CardRow.id, item, RenderRow.LV, RenderRow.name, RenderRow.name_JP, OnImportRow(), SourceThingV.Row.parse, RenderRow.recipeKey, EClass.rnd(), RenderRow.skins, Core.sources, EClass.sources, RenderRow.tag, SourceManager.things, RenderRow.tiles, CardRow.trait, SourceThing.Row.unit, SourceThing.Row.unit_JP, CardRow.vals, RenderRow.value, and SourceThing.Row.weight.
OnImportRow()
virtual void SourceThingV.OnImportRow (Row _r, SourceThing::Row c) inline virtual
Reimplemented in SourceFood.
Definition at line 403 of file SourceThingV.cs.
    {
    }
Referenced by OnAfterImportData().
Reset()
override void SourceThingV.Reset () inline
Definition at line 184 of file SourceThingV.cs.
    {
        base.Reset();
        EClass.sources.things.Reset();
    }
References EClass.sources, and SourceManager.things.
RestorePref()
override void SourceThingV.RestorePref () inline
Definition at line 149 of file SourceThingV.cs.
    {
        foreach (SourceThing.Row row2 in EClass.sources.things.rows)
        {
            SourcePref sourcePref = EClass.sources.things._rows.TryGetValue(row2.id)?.pref;
            if (sourcePref == null && EClass.sources.asset.renames.ContainsKey(row2.id))
            {
                sourcePref = EClass.sources.things._rows.TryGetValue(EClass.sources.asset.renames[row2.id])?.pref;
            }
            row2.pref = sourcePref ?? new SourcePref();
        }
        Dictionary<string, SourceThing.Row> dictionary = new Dictionary<string, SourceThing.Row>();
        foreach (SourceThing.Row row3 in EClass.sources.things.rows)
        {
            dictionary[row3.id] = row3;
        }
        foreach (SourceThing.Row row4 in EClass.sources.things.rows)
        {
            if (!row4.pref.UsePref && !row4._origin.IsEmpty())
            {
                SourceThing.Row row = dictionary[row4._origin];
                row4.pref = IO.DeepCopy(row.pref);
                row4.pref.flags |= PrefFlag.UsePref;
            }
        }
    }
References SourceThing._rows, SourceManager.asset, UDictionary< TKey, TValue >.ContainsKey(), RenderRow.pref, SourceAsset.renames, EClass.sources, and SourceManager.things.
SetRow()
override void SourceThingV.SetRow (Row r) inline
Definition at line 134 of file SourceThingV.cs.
    {
        map[r.id] = r;
    }
References CardRow.id.
ValidatePref()
override void SourceThingV.ValidatePref () inline
Definition at line 176 of file SourceThingV.cs.
    {
        foreach (SourceThing.Row row in EClass.sources.things.rows)
        {
            row.pref.Validate();
        }
    }
References EClass.sources, and SourceManager.things.
Referenced by SourcePrefInspector.ValidatePrefs().
Member Data Documentation
RowMapping
readonly IReadOnlyDictionary<string, int> SourceThingV.RowMapping static
Initial value:
= new Dictionary<string, int>
    {
        ["id"] = 0,
        ["_origin"] = 1,
        ["name_JP"] = 2,
        ["unit_JP"] = 3,
        ["name"] = 4,
        ["unit"] = 5,
        ["tiles"] = 6,
        ["skins"] = 7,
        ["parse"] = 8,
        ["vals"] = 9,
        ["trait"] = 11,
        ["LV"] = 12,
        ["chance"] = 13,
        ["value"] = 14,
        ["weight"] = 15,
        ["recipeKey"] = 16,
        ["factory"] = 17,
        ["components"] = 18,
        ["defMat"] = 19,
        ["category"] = 20,
        ["tag"] = 21,
        ["detail_JP"] = 22,
        ["detail"] = 23
    }
Definition at line 18 of file SourceThingV.cs.
Referenced by GetRowMapping().
TypeMapping
readonly IReadOnlyDictionary<string, string> SourceThingV.TypeMapping static
Initial value:
= new Dictionary<string, string>
    {
        ["id"] = "string",
        ["_origin"] = "string",
        ["name_JP"] = "string",
        ["unit_JP"] = "string",
        ["name"] = "string",
        ["unit"] = "string",
        ["tiles"] = "int[]",
        ["skins"] = "int[]",
        ["parse"] = "string[]",
        ["vals"] = "string[]",
        ["trait"] = "string[]",
        ["LV"] = "int",
        ["chance"] = "int",
        ["value"] = "int",
        ["weight"] = "int",
        ["recipeKey"] = "string[]",
        ["factory"] = "string[]",
        ["components"] = "string[]",
        ["defMat"] = "string",
        ["category"] = "string",
        ["tag"] = "string[]",
        ["detail_JP"] = "string",
        ["detail"] = "string"
    }
Definition at line 45 of file SourceThingV.cs.
Referenced by GetTypeMapping().
Property Documentation
ImportFields
override string [] SourceThingV.ImportFields get
Definition at line 72 of file SourceThingV.cs.
The documentation for this class was generated from the following file:
Elin/SourceThingV.cs