Elin Decompiled Documentation: POIMap.Cell Class Reference
POIMap.Cell Class Reference
Public Member Functions
Point GetCenter ()
Public Attributes
int x
int z
bool occupied
Detailed Description
Definition at line 5 of file POIMap.cs.
Member Function Documentation
GetCenter()
Point POIMap.Cell.GetCenter () inline
Definition at line 13 of file POIMap.cs.
        {
            return new Point(x * cellSize + cellSize / 2, z * cellSize + cellSize / 2).Clamp();
        }
References POIMap.cellSize, Point.Clamp(), POIMap.Cell.x, and POIMap.Cell.z.
Referenced by POIMap.GetCenterOfEmptyCell(), and Zone.SpawnAltar().
Member Data Documentation
occupied
bool POIMap.Cell.occupied
Definition at line 11 of file POIMap.cs.
Referenced by POIMap.OccyupyPOI().
x
int POIMap.Cell.x
Definition at line 7 of file POIMap.cs.
Referenced by POIMap.Cell.GetCenter().
z
int POIMap.Cell.z
Definition at line 9 of file POIMap.cs.
Referenced by POIMap.Cell.GetCenter().
The documentation for this class was generated from the following file:
Elin/POIMap.cs