Elin Decompiled Documentation: Bevel Class Reference
Bevel Class Reference
Public Member Functions
override void ModifyMesh (VertexHelper vh)
Protected Member Functions
Bevel ()
void ApplyShadowZeroAlloc (List< UIVertex > verts, Color32 color, int start, int end, float x, float y)
Properties
Color highlightColor [get, set]
Color shadowColor [get, set]
Vector2 bevelDirectionAndDepth [get, set]
bool useGraphicAlpha [get, set]
Private Attributes
Color m_HighlightColor = new Color(1f, 1f, 1f, 1f)
Color m_ShadowColor = new Color(0f, 0f, 0f, 1f)
Vector2 m_BevelDirectionAndDepth = new Vector2(1f, 1f)
bool m_UseGraphicAlpha = true
List< UIVertex > m_Verts = new List<UIVertex>()
Detailed Description
Definition at line 7 of file Bevel.cs.
Constructor & Destructor Documentation
Bevel()
Bevel.Bevel () inline protected
Definition at line 90 of file Bevel.cs.
    {
    }
Member Function Documentation
ApplyShadowZeroAlloc()
void Bevel.ApplyShadowZeroAlloc (List< UIVertex > verts, Color32 color, int start, int end, float x, float y) inline protected
Definition at line 94 of file Bevel.cs.
    {
        for (int i = start; i < end; i++)
        {
            UIVertex uIVertex = verts[i];
            verts.Add(uIVertex);
            Vector3 position = uIVertex.position;
            position.x += x;
            position.y += y;
            uIVertex.position = position;
            Color32 color2 = color;
            if (useGraphicAlpha)
            {
                color2.a = (byte)(color2.a * verts[i].color.a / 255);
            }
            uIVertex.color = color2;
            verts[i] = uIVertex;
        }
    }
References useGraphicAlpha.
Referenced by ModifyMesh().
ModifyMesh()
override void Bevel.ModifyMesh (VertexHelper vh) inline
Definition at line 114 of file Bevel.cs.
    {
        if (!IsActive())
        {
            return;
        }
        vh.GetUIVertexStream(m_Verts);
        int count = m_Verts.Count;
        int num = 0;
        num = 0;
        int count2 = m_Verts.Count;
        ApplyShadowZeroAlloc(m_Verts, shadowColor, num, m_Verts.Count, bevelDirectionAndDepth.x * 0.75f, (0f - bevelDirectionAndDepth.y) * 0.75f);
        num = count2;
        int count3 = m_Verts.Count;
        ApplyShadowZeroAlloc(m_Verts, shadowColor, num, m_Verts.Count, bevelDirectionAndDepth.x, bevelDirectionAndDepth.y * 0.5f);
        num = count3;
        int count4 = m_Verts.Count;
        ApplyShadowZeroAlloc(m_Verts, shadowColor, num, m_Verts.Count, (0f - bevelDirectionAndDepth.x) * 0.5f, 0f - bevelDirectionAndDepth.y);
        num = count4;
        int count5 = m_Verts.Count;
        ApplyShadowZeroAlloc(m_Verts, highlightColor, num, m_Verts.Count, 0f - bevelDirectionAndDepth.x, bevelDirectionAndDepth.y * 0.5f);
        num = count5;
        _ = m_Verts.Count;
        ApplyShadowZeroAlloc(m_Verts, highlightColor, num, m_Verts.Count, (0f - bevelDirectionAndDepth.x) * 0.5f, bevelDirectionAndDepth.y);
        if (GetComponent<Text>().material.shader == Shader.Find("Text Effects/Fancy Text"))
        {
            for (int i = 0; i < m_Verts.Count - count; i++)
            {
                UIVertex value = m_Verts[i];
                value.uv1 = new Vector2(0f, 0f);
                m_Verts[i] = value;
            }
        }
        vh.Clear();
        vh.AddUIVertexTriangleStream(m_Verts);
    }
References ApplyShadowZeroAlloc(), bevelDirectionAndDepth, highlightColor, m_Verts, material, and shadowColor.
Member Data Documentation
m_BevelDirectionAndDepth
Vector2 Bevel.m_BevelDirectionAndDepth = new Vector2(1f, 1f) private
Definition at line 16 of file Bevel.cs.
m_HighlightColor
Color Bevel.m_HighlightColor = new Color(1f, 1f, 1f, 1f) private
Definition at line 10 of file Bevel.cs.
m_ShadowColor
Color Bevel.m_ShadowColor = new Color(0f, 0f, 0f, 1f) private
Definition at line 13 of file Bevel.cs.
m_UseGraphicAlpha
bool Bevel.m_UseGraphicAlpha = true private
Definition at line 19 of file Bevel.cs.
m_Verts
List<UIVertex> Bevel.m_Verts = new List<UIVertex>() private
Definition at line 21 of file Bevel.cs.
Referenced by ModifyMesh().
Property Documentation
bevelDirectionAndDepth
Vector2 Bevel.bevelDirectionAndDepth get set
Definition at line 55 of file Bevel.cs.
    {
        get
        {
            return m_BevelDirectionAndDepth;
        }
        set
        {
            if (!(m_BevelDirectionAndDepth == value))
            {
                m_BevelDirectionAndDepth = value;
                if (base.graphic != null)
                {
                    base.graphic.SetVerticesDirty();
                }
            }
        }
    }
Referenced by ModifyMesh().
highlightColor
Color Bevel.highlightColor get set
Definition at line 23 of file Bevel.cs.
    {
        get
        {
            return m_HighlightColor;
        }
        set
        {
            m_HighlightColor = value;
            if (base.graphic != null)
            {
                base.graphic.SetVerticesDirty();
            }
        }
    }
Referenced by ModifyMesh().
shadowColor
Color Bevel.shadowColor get set
Definition at line 39 of file Bevel.cs.
    {
        get
        {
            return m_ShadowColor;
        }
        set
        {
            m_ShadowColor = value;
            if (base.graphic != null)
            {
                base.graphic.SetVerticesDirty();
            }
        }
    }
Referenced by ModifyMesh().
useGraphicAlpha
bool Bevel.useGraphicAlpha get set
Definition at line 74 of file Bevel.cs.
    {
        get
        {
            return m_UseGraphicAlpha;
        }
        set
        {
            m_UseGraphicAlpha = value;
            if (base.graphic != null)
            {
                base.graphic.SetVerticesDirty();
            }
        }
    }
Referenced by ApplyShadowZeroAlloc().
The documentation for this class was generated from the following file:
Elin/Plugins.UI/Bevel.cs