Elin Decompiled Documentation: TooltipManager Class Reference
TooltipManager Class Reference
Public Member Functions
void ResetTooltips ()
void ShowTooltip (TooltipData data, Transform target)
void HideTooltips (bool immediate=false)
Public Attributes
UITooltip[] tooltips
string disableHide
float disableTimer
Static Public Attributes
static TooltipManager Instance
Private Member Functions
void Awake ()
void Update ()
Detailed Description
Definition at line 3 of file TooltipManager.cs.
Member Function Documentation
Awake()
void TooltipManager.Awake () inline private
Definition at line 13 of file TooltipManager.cs.
    {
        Instance = this;
    }
References Instance.
HideTooltips()
void TooltipManager.HideTooltips (bool immediate = false) inline
Definition at line 89 of file TooltipManager.cs.
    {
        UITooltip[] array = tooltips;
        foreach (UITooltip uITooltip in array)
        {
            if (immediate)
            {
                uITooltip.cg.alpha = 0f;
                uITooltip.data = null;
                uITooltip.SetActive(enable: false);
                continue;
            }
            float timer = 0f;
            uITooltip.hideFunc = delegate
            {
                timer += Time.smoothDeltaTime;
                return timer > 0.2f;
            };
        }
    }
References tooltips.
Referenced by UIDynamicList.List(), UICharaMaker.ListJob(), UICharaMaker.ListRace(), Game.Load(), LayerInfo.OnAfterInit(), LayerList.OnKill(), UIContextMenu.Show(), UI.StartDrag(), and UIButton.TryShowTip< T >().
ResetTooltips()
void TooltipManager.ResetTooltips () inline
Definition at line 18 of file TooltipManager.cs.
    {
        UITooltip[] array = tooltips;
        for (int i = 0; i < array.Length; i++)
        {
            array[i].data = null;
        }
    }
References UITooltip.data, and tooltips.
Referenced by DropdownGrid.TrySelect().
ShowTooltip()
void TooltipManager.ShowTooltip (TooltipData data, Transform target) inline
Definition at line 27 of file TooltipManager.cs.
    {
        if (disableTimer > 0f)
        {
            return;
        }
        if ((bool)UIContextMenu.Current)
        {
            UIButton componentOf = InputModuleEX.GetComponentOf<UIButton>();
            if (!componentOf || !componentOf.transform.GetComponentInParent<UIContextMenu>())
            {
                return;
            }
        }
        UITooltip uITooltip = tooltips[0];
        UITooltip[] array = tooltips;
        foreach (UITooltip uITooltip2 in array)
        {
            if (uITooltip2.name == data.id)
            {
                uITooltip = uITooltip2;
            }
        }
        uITooltip.SetActive(enable: true);
        uITooltip.SetData(data);
        if (uITooltip.cg.alpha < 0.1f)
        {
            uITooltip.cg.alpha = 1f;
        }
        float timer = 0f;
        uITooltip.hideFunc = delegate
        {
            if (target == null || !InputModuleEX.IsPointerOver(target))
            {
                timer += Time.smoothDeltaTime;
                return timer > 0.2f;
            }
            timer = 0f;
            return false;
        };
        if (uITooltip.followType == UITooltip.FollowType.None)
        {
            return;
        }
        Vector3 vector = ((uITooltip.followType == UITooltip.FollowType.Mouse) ? EInput.uiMousePosition : target.position);
        if (uITooltip.followType == UITooltip.FollowType.Pivot)
        {
            GameObject gameObject = target.FindTagInParents("PivotTooltip", includeInactive: false);
            if ((bool)gameObject)
            {
                uITooltip.Rect().pivot = gameObject.transform.Rect().pivot;
                vector = gameObject.transform.position;
            }
            else
            {
                uITooltip.Rect().pivot = uITooltip.orgPivot;
            }
        }
        uITooltip.transform.position = vector + data.offset + uITooltip.offset;
        Util.ClampToScreen(uITooltip.Rect(), 50);
    }
References UIContextMenu.Current, disableTimer, InputModuleEX.IsPointerOver(), UITooltip.SetData(), tooltips, EInput.uiMousePosition, and Util.
Referenced by HintIcon.ShowTooltip(), UIButton.ShowTooltip(), and UIButton.ShowTooltipForced().
Update()
void TooltipManager.Update () inline private
Definition at line 110 of file TooltipManager.cs.
    {
        if (disableTimer > 0f)
        {
            disableTimer -= Time.deltaTime;
        }
        UITooltip[] array = tooltips;
        foreach (UITooltip uITooltip in array)
        {
            if (!(uITooltip.name == disableHide) && uITooltip.gameObject.activeSelf)
            {
                if (uITooltip.hideFunc())
                {
                    uITooltip.cg.alpha -= Time.smoothDeltaTime * 5f;
                }
                else
                {
                    uITooltip.cg.alpha += Time.smoothDeltaTime * 5f;
                }
                if (uITooltip.cg.alpha <= 0f)
                {
                    uITooltip.data = null;
                    uITooltip.SetActive(enable: false);
                }
            }
        }
    }
References UITooltip.cg, disableHide, disableTimer, UITooltip.hideFunc, and tooltips.
Member Data Documentation
disableHide
string TooltipManager.disableHide
Definition at line 9 of file TooltipManager.cs.
Referenced by Update().
disableTimer
float TooltipManager.disableTimer
Definition at line 11 of file TooltipManager.cs.
Referenced by ShowTooltip(), and Update().
Instance
TooltipManager TooltipManager.Instance static
Definition at line 5 of file TooltipManager.cs.
Referenced by Awake(), UIDynamicList.List(), UICharaMaker.ListJob(), UICharaMaker.ListRace(), Game.Load(), LayerInfo.OnAfterInit(), LayerList.OnKill(), UIContextMenu.Show(), HintIcon.ShowTooltip(), UIButton.ShowTooltip(), UIButton.ShowTooltipForced(), UI.StartDrag(), DropdownGrid.TrySelect(), and UIButton.TryShowTip< T >().
tooltips
UITooltip [] TooltipManager.tooltips
Definition at line 7 of file TooltipManager.cs.
Referenced by HideTooltips(), ResetTooltips(), ShowTooltip(), and Update().
The documentation for this class was generated from the following file:
Elin/Plugins.UI/TooltipManager.cs