Elin Decompiled Documentation: ElementContainerCard Class Reference
ElementContainerCard Class Reference
Public Member Functions
void SetOwner (Card c, bool applyFeat)
override void OnLearn (int ele)
void CheckSkillActions ()
override void OnTrain (int ele)
override void OnModTempPotential (Element e, int v, int threshMsg)
override void OnLevelUp (Element e, int lastValue)
override void OnLevelDown (Element e, int lastValue)
override int ValueBonus (Element e)
Public Member Functions inherited from ElementContainer
void ApplyElementMap (int uid, SourceValueType type, Dictionary< int, int > map, int lv, bool invert=false, bool applyFeat=false)
void ApplyMaterialElementMap (Thing t, bool invert=false)
void ImportElementMap (Dictionary< int, int > map)
ElementContainer ImportElementMap (int[] ints)
void ApplyPotential (int mode=0)
int Value (int ele)
virtual int ValueBonus (Element e)
int ValueWithoutLink (int ele)
int ValueWithoutLink (string alias)
int GetFeatRef (int ele, int idx=0)
int Exp (int ele)
bool Has (int ele)
bool Has (SourceElement.Row row)
bool Has (string alias)
bool HasBase (int ele)
int Base (int ele)
void Learn (int ele, int v=1)
void Train (int ele, int a=10)
void ModExp (int ele, int a, bool chain=false)
virtual void OnLearn (int ele)
virtual void OnTrain (int ele)
virtual void OnLevelUp (Element e, int lastValue)
virtual void OnLevelDown (Element e, int lastValue)
Element SetBase (string alias, int v, int potential=0)
Element SetBase (int id, int v, int potential=0)
void SetTo (int id, int v)
void Remove (int id)
Element ModBase (int ele, int v)
virtual void OnChangeValue ()
Element ModPotential (int ele, int v)
Element ModTempPotential (int ele, int v, int threshMsg=0)
virtual void OnModTempPotential (Element e, int v, int threshMsg)
int GetSpellExp (Chara c, Element e, int costMod=100)
Element GetElement (string alias)
Element GetElement (int id)
Element CreateElement (int id)
Element GetOrCreateElement (Element ele)
Element GetOrCreateElement (string alias)
Element GetOrCreateElement (int id)
void SetParent (Card c)
void SetParent (ElementContainer newParent=null)
List< Element > ListElements (Func< Element, bool > shoudList=null, Comparison< Element > comparison=null)
List< Element > ListBestAttributes ()
List< Element > ListBestSkills ()
List< Element > ListGeneFeats ()
List< Element > ListLearnable (Chara c)
void CopyTo (ElementContainer container)
void AddNote (UINote n, Func< Element, bool > isValid=null, Action onAdd=null, ElementContainer.NoteMode mode=ElementContainer.NoteMode.Default, bool addRaceFeat=false, Func< Element, string, string > funcText=null, Action< UINote, Element > onAddNote=null)
void AddNoteAll (UINote n)
Public Attributes
Card owner
Public Attributes inherited from ElementContainer
Dictionary< int, Element > dict = new Dictionary<int, Element>()
ElementContainer parent
List< int > list
Properties
override Card Card [get]
override Chara Chara [get]
override bool IsMeleeWeapon [get]
Properties inherited from ElementContainer
virtual Card Card [get]
virtual Chara Chara [get]
virtual bool IsMeleeWeapon [get]
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Private Member Functions
void< CheckSkillActions > g__TryLearn (int eleAction, int reqEle, int lqlv)
Additional Inherited Members
Public Types inherited from ElementContainer
enum NoteMode {
Default , CharaMake , CharaMakeAttributes , Domain ,
Trait
}
Static Public Member Functions inherited from ElementContainer
static int GetSortVal (Element a)
Static Public Member Functions inherited from EClass
static int rnd (int a)
static int curve (int a, int start, int step, int rate=75)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Static Public Attributes inherited from ElementContainer
const int sizeElement = 5
Static Public Attributes inherited from EClass
static Core core
Static Package Functions inherited from ElementContainer
static void< ListElements > g__AddElements (ElementContainer container, ref ElementContainer.<>c__DisplayClass55_0 A_1)
Detailed Description
Definition at line 6 of file ElementContainerCard.cs.
Member Function Documentation
CheckSkillActions()
void ElementContainerCard.CheckSkillActions () inline
Definition at line 49 of file ElementContainerCard.cs.
    {
        if (this.owner.IsPC)
        {
            this.<CheckSkillActions>g__TryLearn|9_0(6011, 281, 0);
            this.<CheckSkillActions>g__TryLearn|9_0(6018, 226, 0);
            this.<CheckSkillActions>g__TryLearn|9_0(6019, 227, 0);
            this.<CheckSkillActions>g__TryLearn|9_0(6700, 1649, 0);
            this.<CheckSkillActions>g__TryLearn|9_0(6720, 1657, 0);
            this.<CheckSkillActions>g__TryLearn|9_0(6450, 132, 5);
        }
    }
References CheckSkillActions(), g__TryLearn(), Card.IsPC, and owner.
Referenced by CheckSkillActions(), OnLearn(), OnLevelUp(), Game.OnLoad(), and Player.OnStartNewGame().
g__TryLearn()
void< CheckSkillActions > ElementContainerCard.g__TryLearn (int eleAction, int reqEle, int lqlv) inline private
Definition at line 248 of file ElementContainerCard.cs.
    {
        if (base.HasBase(eleAction) || !base.HasBase(reqEle) || base.GetElement(reqEle).ValueWithoutLink < lqlv)
        {
            return;
        }
        base.SetBase(eleAction, 1, 0);
        if (!EClass.core.IsGameStarted)
        {
            return;
        }
        if (this.owner.IsPC)
        {
            LayerAbility.Redraw();
        }
        this.owner.Say("learnSkill", this.Card, EClass.sources.elements.map[eleAction].GetName(), null);
    }
References EClass.core, SourceManager.elements, Card.IsPC, owner, LayerAbility.Redraw(), Card.Say(), and EClass.sources.
Referenced by CheckSkillActions().
OnLearn()
override void ElementContainerCard.OnLearn (int ele) inline virtual
Reimplemented from ElementContainer.
Definition at line 39 of file ElementContainerCard.cs.
    {
        if (this.owner.IsPCFaction)
        {
            SE.DingSkill2();
        }
        Msg.Say("learnSkill", this.Card, EClass.sources.elements.map[ele].GetName(), null, null);
        this.CheckSkillActions();
    }
References CheckSkillActions(), SourceManager.elements, Card.IsPCFaction, owner, Msg.Say(), and EClass.sources.
OnLevelDown()
override void ElementContainerCard.OnLevelDown (Element e, int lastValue) inline virtual
Reimplemented from ElementContainer.
Definition at line 135 of file ElementContainerCard.cs.
    {
        if (!e.ShowMsgOnValueChanged)
        {
            return;
        }
        bool isPC = this.owner.IsPC;
        if (this.owner.isChara)
        {
            if (this.owner.Chara.IsPCFaction)
            {
                Msg.SetColor(Msg.colors.Negative);
                string text = e.source.GetText("textDec", true);
                if (!text.IsEmpty())
                {
                    Msg.Say(text, this.owner, null, null, null);
                }
                else
                {
                    Msg.Say("dec_skill", this.owner, e.Name, null, null);
                }
            }
            this.owner.Chara.CalculateMaxStamina();
        }
    }
References Chara.CalculateMaxStamina(), Card.Chara, Msg.colors, Card.isChara, Card.IsPC, Chara.IsPCFaction, Element.Name, owner, Msg.Say(), Msg.SetColor(), Element.ShowMsgOnValueChanged, Element.source, and text.
OnLevelUp()
override void ElementContainerCard.OnLevelUp (Element e, int lastValue) inline virtual
Reimplemented from ElementContainer.
Definition at line 82 of file ElementContainerCard.cs.
    {
        if (!e.ShowMsgOnValueChanged)
        {
            return;
        }
        if (this.owner.IsPC)
        {
            if (e.id == 287)
            {
                EClass.player.flags.canComupWithFoodRecipe = true;
            }
            SE.DingSkill2();
        }
        if (this.owner.isChara)
        {
            if (this.owner.Chara.IsPCFaction)
            {
                if (!VirtualDate.IsActive)
                {
                    if (this.owner.Chara.IsInActiveZone)
                    {
                        Msg.SetColor(Msg.colors.Ding);
                        string text = e.source.GetText("textInc", true);
                        if (!text.IsEmpty())
{
                            this.owner.Say(text, this.owner, null, null);
                        }
                        else
{
                            this.owner.Say("ding_skill", this.owner, e.Name, null);
                        }
                        this.owner.pos.TalkWitnesses(this.owner.Chara, "ding_other", 4, WitnessType.ally, null, 4 + EClass.pc.party.members.Count);
                    }
                    if (this.owner.IsPCParty)
                    {
                        WidgetPopText.Say("popDing".lang(this.owner.IsPC ? "" : this.owner.Name, e.Name, lastValue.ToString() ?? "", e.ValueWithoutLink.ToString() ?? "", null), FontColor.Good, null);
                    }
                }
                if (this.owner.Chara.homeBranch != null)
                {
                    this.owner.Chara.homeBranch.Log("bDing", this.Card, e.Name, lastValue.ToString() ?? "", e.ValueWithoutLink.ToString() ?? "");
                }
            }
            if (e is Skill)
            {
                this.owner.AddExp(10 + EClass.rnd(5));
            }
            this.owner.Chara.CalculateMaxStamina();
        }
        this.CheckSkillActions();
    }
References Card.AddExp(), Chara.CalculateMaxStamina(), Card.Chara, CheckSkillActions(), Msg.colors, Chara.homeBranch, Element.id, VirtualDate.IsActive, Card.isChara, Chara.IsInActiveZone, Card.IsPC, Chara.IsPCFaction, Card.IsPCParty, FactionBranch.Log(), Party.members, Element.Name, owner, Chara.party, EClass.pc, Card.pos, EClass.rnd(), Card.Say(), WidgetPopText.Say(), Msg.SetColor(), Element.ShowMsgOnValueChanged, Element.source, Point.TalkWitnesses(), text, and Element.ValueWithoutLink.
OnModTempPotential()
override void ElementContainerCard.OnModTempPotential (Element e, int v, int threshMsg) inline virtual
Reimplemented from ElementContainer.
Definition at line 67 of file ElementContainerCard.cs.
    {
        if (threshMsg != 0 && Mathf.Abs(v) < threshMsg)
        {
            return;
        }
        string lang = (v > 0) ? "potentialInc" : "potentialDec";
        if (this.owner.IsPCFaction && v > 0)
        {
            this.owner.PlaySound("ding_potential", 1f, true);
        }
        Msg.SetColor((v > 0) ? "positive" : "negative");
        this.owner.Say(lang, this.owner, e.Name.ToLower(), null);
    }
References Card.IsPCFaction, Element.Name, owner, Card.PlaySound(), Card.Say(), and Msg.SetColor().
OnTrain()
override void ElementContainerCard.OnTrain (int ele) inline virtual
Reimplemented from ElementContainer.
Definition at line 62 of file ElementContainerCard.cs.
    {
        Msg.Say("trainSkill", this.Card, EClass.sources.elements.map[ele].GetName(), null, null);
    }
References SourceManager.elements, Msg.Say(), and EClass.sources.
SetOwner()
void ElementContainerCard.SetOwner (Card c, bool applyFeat) inline
Definition at line 32 of file ElementContainerCard.cs.
    {
        this.owner = c;
        SourceValueType sourceValueType = (c.IsEquipmentOrRanged && c.rarity < Rarity.Artifact) ? SourceValueType.EquipmentRandom : SourceValueType.Fixed;
        base.ApplyElementMap(c.uid, sourceValueType, c.sourceCard.elementMap, (sourceValueType == SourceValueType.EquipmentRandom) ? c.LV : 1, false, applyFeat);
    }
References CardRow.elementMap, Card.sourceCard, and Card.uid.
Referenced by Card._OnDeserialized(), and Card.Create().
ValueBonus()
override int ElementContainerCard.ValueBonus (Element e) inline virtual
Reimplemented from ElementContainer.
Definition at line 161 of file ElementContainerCard.cs.
    {
        if (EClass.game == null)
        {
            return 0;
        }
        int num = 0;
        if (this.owner.IsPCFactionOrMinion)
        {
            Element element = EClass.pc.faction.charaElements.GetElement(e.id);
            if (element != null)
            {
                num += element.Value;
            }
            if (this.owner.IsPCParty)
            {
                int id = e.id;
                if (id == 70 || id - 72 <= 1)
                {
                    int num2 = 0;
                    foreach (Chara chara in EClass.pc.party.members)
                    {
                        if (chara.Evalue(1419) > 0)
{
                            num2 += chara.Evalue(1419);
                        }
                    }
                    if (num2 > 0)
                    {
                        int num3 = 0;
                        using (List<Chara>.Enumerator enumerator = EClass._map.charas.GetEnumerator())
{
                            while (enumerator.MoveNext())
{
                                if (enumerator.Current.IsHostile(EClass.pc))
{
                                    num3++;
                                }
                            }
                        }
                        if (num3 > 0)
{
                            num += Mathf.Max(1, (e.ValueWithoutLink + e.vLink) * (int)Mathf.Clamp(4f + Mathf.Sqrt((float)num3) * (float)num2 * 2f, 5f, 30f) / 100);
                        }
                    }
                }
            }
            if (e.id == 78)
            {
                num += EClass.player.CountKeyItem("lucky_coin") * 2;
                if (this.Chara != null && this.Chara.Evalue(663) > 0)
                {
                    num = num * 2 + (e.ValueWithoutLink + e.vLink);
                }
            }
            if (this.owner.Chara.race.IsMachine || this.owner.id == "android")
            {
                int num4 = this.owner.Evalue(664);
                if (num4 > 0)
                {
                    int id = e.id;
                    if (id - 64 > 1)
                    {
                        if (id == 79)
{
                            num += (e.ValueWithoutLink + e.vLink) * num4 / 100;
                        }
                    }
                    else
                    {
                        num += (e.ValueWithoutLink + e.vLink) * num4 / 2 / 100;
                    }
                }
            }
        }
        if (!e.source.aliasMtp.IsEmpty())
        {
            int num5 = this.owner.Evalue(e.source.aliasMtp);
            if (num5 != 0)
            {
                num += (e.ValueWithoutLink + e.vLink) * num5 / 100;
            }
        }
        return num;
    }
References EClass._map, Card.Chara, Faction.charaElements, Map.charas, Player.CountKeyItem(), Card.Evalue(), Chara.faction, EClass.game, ElementContainer.GetElement(), Element.id, Card.IsPCFactionOrMinion, Card.IsPCParty, Party.members, owner, Chara.party, EClass.pc, EClass.player, Chara.race, Element.source, Element.Value, Element.ValueWithoutLink, and Element.vLink.
Member Data Documentation
owner
Card ElementContainerCard.owner
Definition at line 266 of file ElementContainerCard.cs.
Referenced by CheckSkillActions(), g__TryLearn(), OnLearn(), OnLevelDown(), OnLevelUp(), OnModTempPotential(), and ValueBonus().
Property Documentation
Card
override Card ElementContainerCard.Card get
Definition at line 8 of file ElementContainerCard.cs.
    {
        get
        {
            return this.owner;
        }
    }
Chara
override Chara ElementContainerCard.Chara get
Definition at line 16 of file ElementContainerCard.cs.
    {
        get
        {
            return this.owner.Chara;
        }
    }
IsMeleeWeapon
override bool ElementContainerCard.IsMeleeWeapon get
Definition at line 24 of file ElementContainerCard.cs.
    {
        get
        {
            return this.Card.category.slot == 35 && this.Card.category.skill != 0;
        }
    }
The documentation for this class was generated from the following file:
Elin/ElementContainerCard.cs