Elin Decompiled Documentation: Policy Class Reference
Policy Class Reference
Public Member Functions
void SetOwner (FactionBranch _branch)
void OnAdvanceHour (VirtualDate date)
void RefreshEffect (UINote note=null)
void ModHappiness (int a, FactionMemberType type, UINote note)
void WriteNote (UINote n)
int GetSortVal (UIList.SortMode m)
Public Attributes
int id
int days
bool active
FactionBranch branch
Properties
Element Ele [get]
SourceElement.Row source [get]
string Name [get]
Sprite Sprite [get]
int Next [get]
int Cost [get]
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Additional Inherited Members
Static Public Member Functions inherited from EClass
static int rndSeed (int a, int seed)
static int rnd (long a)
static int rnd (int a)
static int curve (int a, int start, int step, int rate=75)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Static Public Attributes inherited from EClass
static Core core
Detailed Description
Definition at line 118 of file POLICY.cs.
Member Function Documentation
GetSortVal()
int Policy.GetSortVal (UIList::SortMode m) inline
Definition at line 200 of file POLICY.cs.
    {
        return 0;
    }
Referenced by ContentPolicy.RefreshPolicyList(), and LayerPolicy.RefreshPolicyList().
ModHappiness()
void Policy.ModHappiness (int a, FactionMemberType type, UINote note) inline
Definition at line 173 of file POLICY.cs.
    {
        if ((bool)note)
        {
            note.AddText("peHappiness".lang(("member" + type).lang(), a.ToString() ?? "").TagColorGoodBad(() => a >= 0));
        }
        else
        {
            branch.happiness.list[(int)type].modPolicy += a;
        }
    }
References UINote.AddText(), branch, FactionBranch.happiness, and HappinessManager.list.
Referenced by RefreshEffect().
OnAdvanceHour()
void Policy.OnAdvanceHour (VirtualDate date) inline
Definition at line 148 of file POLICY.cs.
    {
        EClass._zone.elements.ModExp(id, 10f);
    }
References EClass._zone, Zone.elements, and ElementContainer.ModExp().
RefreshEffect()
void Policy.RefreshEffect (UINote note = null) inline
Definition at line 153 of file POLICY.cs.
    {
        switch (source.alias)
        {
        case "humanRight":
            ModHappiness(20, FactionMemberType.Default, note);
            ModHappiness(-10, FactionMemberType.Livestock, note);
            break;
        case "nocturnalLife":
            ModHappiness(-20, FactionMemberType.Default, note);
            break;
        case "inquisition":
            break;
        case "legalDrug":
            break;
        case "prohibition":
            break;
        }
    }
References ModHappiness(), and source.
Referenced by PolicyManager.RefreshEffects().
SetOwner()
void Policy.SetOwner (FactionBranch _branch) inline
Definition at line 143 of file POLICY.cs.
    {
        branch = _branch;
    }
References branch.
Referenced by PolicyManager.AddPolicy().
WriteNote()
void Policy.WriteNote (UINote n) inline
Definition at line 185 of file POLICY.cs.
    {
        if (Ele == null)
        {
            Debug.Log(id);
            return;
        }
        Ele.WriteNote(n, EClass._zone.elements);
        if (active)
        {
            n.Space();
            n.AddText("activeFor".lang(days.ToString() ?? ""));
        }
    }
References EClass._zone, active, UINote.AddText(), days, Debug, Ele, Zone.elements, UINote.Space(), and Element.WriteNote().
Referenced by ContentPolicy.RefreshPolicyList(), and LayerPolicy.RefreshPolicyList().
Member Data Documentation
active
bool Policy.active
Definition at line 127 of file POLICY.cs.
Referenced by PolicyManager.RefreshEffects(), ContentPolicy.RefreshPolicyIcons(), LayerPolicy.RefreshPolicyIcons(), ContentPolicy.RefreshPolicyList(), LayerPolicy.RefreshPolicyList(), and WriteNote().
branch
FactionBranch Policy.branch
Definition at line 129 of file POLICY.cs.
Referenced by ModHappiness(), and SetOwner().
days
int Policy.days
Definition at line 124 of file POLICY.cs.
Referenced by WriteNote().
id
int Policy.id
Definition at line 121 of file POLICY.cs.
Referenced by PolicyManager.AddPolicy(), and ContentPolicy.RefreshPolicyList().
Property Documentation
Cost
int Policy.Cost get
Definition at line 141 of file POLICY.cs.
Referenced by ContentPolicy.RefreshPolicyIcons(), LayerPolicy.RefreshPolicyIcons(), and LayerPolicy.RefreshPolicyList().
Ele
Element Policy.Ele get
Definition at line 131 of file POLICY.cs.
Referenced by WriteNote().
Name
string Policy.Name get
Definition at line 135 of file POLICY.cs.
Referenced by ContentPolicy.RefreshPolicyList(), and LayerPolicy.RefreshPolicyList().
Next
int Policy.Next get
Definition at line 139 of file POLICY.cs.
source
SourceElement.Row Policy.source get
Definition at line 133 of file POLICY.cs.
Referenced by PolicyManager.AddPolicy(), RefreshEffect(), ContentPolicy.RefreshPolicyList(), and LayerPolicy.RefreshPolicyList().
Sprite
Sprite Policy.Sprite get
Definition at line 137 of file POLICY.cs.
The documentation for this class was generated from the following file:
Elin/POLICY.cs