Elin Decompiled Documentation: LayerEditSkin Class Reference
LayerEditSkin Class Reference
Public Member Functions
void Activate (Chara _chara)
void RefreshImage (SpriteData data=null)
void OnClickClear ()
void OnClickEdit ()
void RefreshList ()
Public Member Functions inherited from ELayer
override void OnBeforeAddLayer ()
void InitInspector ()
sealed override void Init ()
override void OnAfterAddLayer ()
void TryShowHelp ()
void AddLayerToUI (string id)
void TryShowHint (string _langHint=null)
void TalkHomeMemeber (string id)
void TalkMaid (string id)
override void OnRightClick ()
Public Member Functions inherited from Layer
virtual string GetTextHeader (Window window)
virtual bool HeaderIsListOf (int id)
virtual void Init ()
virtual void OnInit ()
virtual void OnAfterInit ()
virtual void ApplySkin ()
void ShowScreenLock (string id)
void UpdateInput ()
virtual void OnUpdateInput ()
virtual void OnRightClick ()
virtual bool OnBack ()
virtual void OnChangeLayer ()
virtual void OnCreate ()
void _AddLayer (string id)
Layer AddLayer (string id)
T AddLayer< T > ()
T AddLayer< T > (string id)
T AddLayerDontCloseOthers< T > ()
Layer AddLayerDontCloseOthers (Layer l)
T GetOrAddLayer< T > ()
virtual void OnBeforeAddLayer ()
virtual void OnAfterAddLayer ()
Layer AddLayer (Layer l)
void ToggleLayer (string id)
T ToggleLayer< T > (string id=null)
void WaitAndClose ()
void OnClickClose ()
virtual void Close ()
void CloseLayers ()
void RemoveLayers (bool removeImportant=false)
bool RemoveLayer< T > ()
void RemoveLayer (Layer l)
virtual void OnKill ()
Layer SetOnKill (Action action)
void DisableClose ()
void Delay (float duration=0.05f)
Layer SetDelay (float d)
Layer GetLayer (string id)
T GetLayer< T > (bool fromTop=false)
Layer GetTopLayer ()
void SwitchContent (int idWindow, int i)
virtual void OnSwitchContent (Window window)
Layer SetTitles (string langList, string idHeaderRow=null)
bool IsBlockWidgetClick ()
bool IsHideHud ()
bool IsAllowGeneralInput ()
bool IsUseBlur ()
bool IsPointerOnLayer ()
void ApplySkin ()
Public Attributes
Image imageSkin
Chara chara
UIDynamicList list
SpriteData currentData
Public Attributes inherited from Layer
Option option
UnityEvent onKill
Anime animeIn
Anime animeOut
bool closeOthers
bool defaultActionMode = true
Button screenLock
Layer parent
string idLayer
List< Layer > layers = new List<Layer>()
Vector2 lastParentPos
List< Window > windows = new List<Window>()
string langHint
Private Member Functions
void OnApplicationFocus (bool focus)
Additional Inherited Members
Static Public Member Functions inherited from ELayer
static int rnd (int a)
Static Public Member Functions inherited from Layer
static T Create< T > ()
static T Create< T > (string path)
static Layer Create (string path)
Static Public Attributes inherited from Layer
static int skipInput
static bool closeOnRightClick
static bool rightClicked
static bool cancelKeyDown
static bool ignoreSounds
static Transform blurStopInstance
static string[] searchPath = new string[3] { "Layer", "Layer/Dialog", "Layer/LayerHome" }
Protected Member Functions inherited from ELayer
sealed override void _Close ()
sealed override void Kill ()
Protected Member Functions inherited from Layer
virtual void Awake ()
virtual void _Close ()
virtual void Kill ()
Protected Attributes inherited from Layer
RectTransform _rect
bool isDestroyed
Properties inherited from ELayer
static Core core [get]
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static FactionBranch Branch [get]
static Faction Home [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static CoreConfig config [get]
static GameSetting setting [get]
static ColorProfile Colors [get]
static SourceManager sources [get]
static World world [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
bool IsFloat [get]
virtual string IdHelp [get]
Properties inherited from Layer
Layer TopLayer [get]
string uid [get]
virtual RectTransform rectLayers [get]
virtual bool blockWidgetClick [get]
Detailed Description
Definition at line 6 of file LayerEditSkin.cs.
Member Function Documentation
Activate()
void LayerEditSkin.Activate (Chara _chara) inline
Definition at line 16 of file LayerEditSkin.cs.
    {
        chara = _chara;
        RefreshImage();
        RefreshList();
    }
References chara, RefreshImage(), and RefreshList().
Referenced by BaseListPeople.OnClick().
OnApplicationFocus()
void LayerEditSkin.OnApplicationFocus (bool focus) inline private
Definition at line 91 of file LayerEditSkin.cs.
    {
        if (focus && currentData != null)
        {
            RefreshImage(currentData);
        }
    }
References currentData, and RefreshImage().
OnClickClear()
void LayerEditSkin.OnClickClear () inline
Definition at line 32 of file LayerEditSkin.cs.
    {
        SE.Trash();
        chara.c_idSpriteReplacer = null;
        chara._CreateRenderer();
        RefreshImage();
    }
References Chara._CreateRenderer(), chara, and RefreshImage().
OnClickEdit()
void LayerEditSkin.OnClickEdit () inline
Definition at line 40 of file LayerEditSkin.cs.
    {
        if (currentData == null)
        {
            SE.Beep();
            return;
        }
        string fileNameWithoutExtension = Path.GetFileNameWithoutExtension(currentData.path);
        string text = CorePath.custom + "Skin/" + fileNameWithoutExtension + ".pref";
        if (!File.Exists(text))
        {
            (currentData.pref ?? chara.Pref).WriteIni(text);
        }
        SE.Click();
        Util.Run(text);
    }
References chara, currentData, SpriteData.path, Chara.Pref, and Util.
RefreshImage()
void LayerEditSkin.RefreshImage (SpriteData data = null) inline
Definition at line 23 of file LayerEditSkin.cs.
    {
        data?.LoadPref();
        imageSkin.sprite = chara.GetSprite();
        imageSkin.SetNativeSize();
        WidgetRoster.SetDirty();
        currentData = data ?? chara.spriteReplacer?.data;
    }
References chara, currentData, SpriteReplacer.data, Chara.GetSprite(), imageSkin, WidgetRoster.SetDirty(), and Chara.spriteReplacer.
Referenced by Activate(), OnApplicationFocus(), OnClickClear(), and RefreshList().
RefreshList()
void LayerEditSkin.RefreshList () inline
Definition at line 57 of file LayerEditSkin.cs.
    {
        list.Clear();
        list.callbacks = new UIList.Callback<SpriteData, UIButton>
        {
            onClick = delegate(SpriteData a, UIButton b)
            {
                list.Select(a);
                SE.Click();
                chara.c_idSpriteReplacer = Path.GetFileName(a.path);
                chara._CreateRenderer();
                RefreshImage(a);
            },
            onRedraw = delegate(SpriteData a, UIButton b, int i)
            {
                b.mainText.SetText(Path.GetFileName(a.path));
                a.Init();
                b.icon.sprite = a.GetSprite();
                b.icon.SetNativeSize();
                b.tooltip.lang = a.path;
            },
            onList = delegate
            {
                List<SpriteReplacer> obj = SpriteReplacer.ListSkins().Values.ToList();
                obj.Sort((SpriteReplacer a, SpriteReplacer b) => Lang.comparer.Compare(a.data.path, b.data.path));
                foreach (SpriteReplacer item in obj)
                {
                    list.Add(item.data);
                }
            }
        };
        list.List();
    }
References Chara._CreateRenderer(), UIDynamicList.Add(), chara, UIDynamicList.Clear(), Lang.comparer, SpriteReplacer.data, SpriteData.GetSprite(), UIButton.icon, SpriteData.Init(), item, list, UIDynamicList.List(), SpriteReplacer.ListSkins(), UIButton.mainText, SpriteData.path, RefreshImage(), UIDynamicList.Select(), and UIText.SetText().
Referenced by Activate().
Member Data Documentation
chara
Chara LayerEditSkin.chara
Definition at line 10 of file LayerEditSkin.cs.
Referenced by Activate(), OnClickClear(), OnClickEdit(), RefreshImage(), and RefreshList().
currentData
SpriteData LayerEditSkin.currentData
Definition at line 14 of file LayerEditSkin.cs.
Referenced by OnApplicationFocus(), OnClickEdit(), and RefreshImage().
imageSkin
Image LayerEditSkin.imageSkin
Definition at line 8 of file LayerEditSkin.cs.
Referenced by RefreshImage().
list
UIDynamicList LayerEditSkin.list
Definition at line 12 of file LayerEditSkin.cs.
Referenced by RefreshList().
The documentation for this class was generated from the following file:
Elin/LayerEditSkin.cs