Elin Decompiled Documentation: UIAnimeGroup Class Reference
UIAnimeGroup Class Reference
Public Member Functions
override void Play (AnimePhase phase, UnityAction onComplete=null)
UIAnimeGroup AddAnime (Transform target, Anime intro, Anime outro=null, Anime loop=null)
override bool Has (AnimePhase phase)
Public Member Functions inherited from UIAnime
virtual void Play (AnimePhase phase, UnityAction onComplete=null)
virtual bool Has (AnimePhase phase)
void OnComplete (UnityAction onComplete)
Public Attributes
List< AnimeItem > animes = new List<AnimeItem>()
Public Attributes inherited from UIAnime
bool isDisableInput = true
Detailed Description
Definition at line 5 of file UIAnimeGroup.cs.
Member Function Documentation
AddAnime()
UIAnimeGroup UIAnimeGroup.AddAnime (Transform target, Anime intro, Anime outro = null, Anime loop = null) inline
Definition at line 28 of file UIAnimeGroup.cs.
    {
        animes.Add(new AnimeItem
        {
            target = target,
            intro = intro,
            outro = outro,
            loop = loop
        });
        return this;
    }
References animes.
Has()
override bool UIAnimeGroup.Has (AnimePhase phase) inline virtual
Reimplemented from UIAnime.
Definition at line 40 of file UIAnimeGroup.cs.
    {
        foreach (AnimeItem anime in animes)
        {
            if ((phase == AnimePhase.Intro && (bool)anime.intro) || (phase == AnimePhase.Outro && (bool)anime.outro))
            {
                return true;
            }
        }
        return false;
    }
References animes, AnimeItem.intro, and AnimeItem.outro.
Play()
override void UIAnimeGroup.Play (AnimePhase phase, UnityAction onComplete = null) inline virtual
Reimplemented from UIAnime.
Definition at line 9 of file UIAnimeGroup.cs.
    {
        bool flag = false;
        foreach (AnimeItem anime in animes)
        {
            if (flag)
            {
                anime.Play(phase);
                continue;
            }
            anime.Play(phase, delegate
            {
                OnComplete(onComplete);
            });
            flag = true;
        }
        base.Play(phase, onComplete);
    }
References animes, UIAnime.OnComplete(), and AnimeItem.Play().
Member Data Documentation
animes
List<AnimeItem> UIAnimeGroup.animes = new List<AnimeItem>()
Definition at line 7 of file UIAnimeGroup.cs.
Referenced by AddAnime(), Has(), and Play().
The documentation for this class was generated from the following file:
Elin/Plugins.UI/UIAnimeGroup.cs