Elin Decompiled Documentation: GridItemRecipe Class Reference
GridItemRecipe Class Reference
Public Member Functions
override void SetButton (ButtonGrid b)
override void OnClick (ButtonGrid b)
Public Member Functions inherited from GridItem
virtual void SetButton (ButtonGrid b)
virtual void OnClick (ButtonGrid b)
virtual void AutoAdd ()
Public Attributes
Recipe r
Additional Inherited Members
Static Public Member Functions inherited from EClass
static int rnd (int a)
static int curve (int a, int start, int step, int rate=75)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Static Public Attributes inherited from EClass
static Core core
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Detailed Description
Definition at line 1 of file GridItemRecipe.cs.
Member Function Documentation
OnClick()
override void GridItemRecipe.OnClick (ButtonGrid b) inline virtual
Reimplemented from GridItem.
Definition at line 32 of file GridItemRecipe.cs.
    {
    }
SetButton()
override void GridItemRecipe.SetButton (ButtonGrid b) inline virtual
Reimplemented from GridItem.
Definition at line 5 of file GridItemRecipe.cs.
    {
        b.mainText.text = "1";
        b.mainText.SetActive(enable: false);
        r.renderRow.SetImage(b.icon, null, r.GetDefaultColor());
        b.SetTooltip("note", delegate(UITooltip t)
        {
            UINote note = t.note;
            note.Clear();
            note.AddHeaderCard(r.Name);
            if (!r.GetDetail().IsEmpty())
            {
                note.AddText(r.GetDetail());
                note.Space();
            }
            if (r.source.NeedFactory)
            {
                note.AddText("reqFactory".lang(r.source.NameFactory));
            }
            else
            {
                note.AddText("reqNoFactory".lang());
            }
            note.Build();
        });
    }
References UINote.AddHeaderCard(), UINote.Build(), UINote.Clear(), Recipe.GetDefaultColor(), Recipe.GetDetail(), UIButton.icon, if(), UIButton.mainText, Recipe.Name, RecipeSource.NeedFactory, UITooltip.note, r, Recipe.renderRow, RenderRow.SetImage(), UIButton.SetTooltip(), and Recipe.source.
Member Data Documentation
r
Recipe GridItemRecipe.r
Definition at line 3 of file GridItemRecipe.cs.
Referenced by SetButton().
The documentation for this class was generated from the following file:
Elin/GridItemRecipe.cs