Elin Decompiled Documentation: SourceImporter Class Reference
SourceImporter Class Reference
Public Member Functions
SourceImporter (IReadOnlyDictionary< string, SourceData > sourceMapping)
SourceData FindSourceByName (string name)
IEnumerable< SourceData > ImportFilesCached (IEnumerable< string > imports, bool resetData=true)
Static Public Member Functions
static void HotInit (IEnumerable< SourceData > sourceData)
Static Public Member Functions inherited from EClass
static int rndSeed (int a, int seed)
static int rnd (long a)
static int rnd (int a)
static int curve (long _a, int start, int step, int rate=75)
static int sqrt (int a)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Public Attributes
Dictionary< string, EMod > fileProviders = new Dictionary<string, EMod>(PathComparer.Default)
Private Member Functions
SourceData.BaseRow[] LoadBySheetName (ISheet sheet, string file)
string ISheet[] ISheet element PrefetchWorkbook (string file)
Private Attributes
readonly IReadOnlyDictionary< string, SourceData > _sourceMapping
SourceData
string file
string ISheet[] sheets
Additional Inherited Members
Static Public Attributes inherited from EClass
static Core core
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Detailed Description
Definition at line 10 of file SourceImporter.cs.
Constructor & Destructor Documentation
SourceImporter()
SourceImporter.SourceImporter (IReadOnlyDictionary< string, SourceData > sourceMapping) inline
Definition at line 16 of file SourceImporter.cs.
    {
        _sourceMapping = sourceMapping;
    }
References _sourceMapping.
Member Function Documentation
FindSourceByName()
SourceData SourceImporter.FindSourceByName (string name) inline
Definition at line 21 of file SourceImporter.cs.
    {
        string[] array = new string[3]
        {
            "Source" + name,
            "Lang" + name,
            name
        };
        foreach (string key in array)
        {
            if (_sourceMapping.TryGetValue(key, out var value))
            {
                return value;
            }
        }
        return null;
    }
References _sourceMapping.
Referenced by ImportFilesCached(), and LoadBySheetName().
HotInit()
static void SourceImporter.HotInit (IEnumerable< SourceData > sourceData) inline static
Definition at line 186 of file SourceImporter.cs.
    {
        Debug.Log("#source resetting data...");
        foreach (SourceData sourceDatum in sourceData)
        {
            try
            {
                sourceDatum.Reset();
                sourceDatum.Init();
            }
            catch (Exception arg)
            {
                Debug.LogError($"#source failed to reset dirty data {sourceDatum.GetType().Name}\n{arg}");
            }
        }
        Debug.Log("#source initialized data");
    }
References $, Debug, SourceData< T, T2 >.Init(), and SourceData< T, T2 >.Reset().
Referenced by ModManager.ImportAllModSourceSheets(), and ImportFilesCached().
ImportFilesCached()
IEnumerable< SourceData > SourceImporter.ImportFilesCached (IEnumerable< string > imports, bool resetData = true) inline
Definition at line 85 of file SourceImporter.cs.
    {
        SourceCache[] array = imports.Select(SourceCache.GetOrCreate).Distinct().ToArray();
        Dictionary<SourceCache, (string, ISheet[], ISheet)> dictionary = (from c in array
            where c.IsDirtyOrEmpty
            select PrefetchWorkbook(c.SheetFile.FullName)).ToArray().ToDictionary(((string file, ISheet[] sheets, ISheet element) p) => SourceCache.GetOrCreate(p.file));
        SourceElement elements = EClass.sources.elements;
        HashSet<SourceData> hashSet = new HashSet<SourceData> { elements };
        SourceCache[] array2 = array;
        foreach (SourceCache sourceCache in array2)
        {
            string arg = sourceCache.SheetFile.ShortPath();
            if (fileProviders.TryGetValue(sourceCache.SheetFile.FullName, out var value))
            {
                sourceCache.SetMod(value);
            }
            SourceData.BaseRow[] rows;
            if (sourceCache.IsDirtyOrEmpty)
            {
                if (dictionary.TryGetValue(sourceCache, out var value2) && value2.Item3 != null)
                {
                    SourceData.BaseRow[] item = LoadBySheetName(value2.Item3, value2.Item1).Item2;
                    sourceCache.EmplaceCache("Element", item);
                    value?.sourceRows.UnionWith(item);
                    Debug.Log(string.Format("#source workbook {0}:{1}:{2}", arg, "Element", item.Length));
                }
            }
            else if (sourceCache.TryGetCache("Element", out rows))
            {
                int num = elements.ImportRows(rows);
                value?.sourceRows.UnionWith(rows);
                Debug.Log(string.Format("#source workbook-cache {0}:{1}:{2}", arg, "Element", num));
            }
        }
        array2 = array;
        foreach (SourceCache sourceCache2 in array2)
        {
            string text = sourceCache2.SheetFile.ShortPath();
            if (sourceCache2.IsDirtyOrEmpty)
            {
                if (!dictionary.TryGetValue(sourceCache2, out var value3) || value3.Item2.Length == 0)
                {
                    continue;
                }
                Debug.Log("#source workbook " + text);
                ISheet[] item2 = value3.Item2;
                foreach (ISheet sheet in item2)
                {
                    if (sheet.SheetName == "Element")
                    {
                        continue;
                    }
                    var (sourceData, array3) = LoadBySheetName(sheet, value3.Item1);
                    if ((object)sourceData != null)
                    {
                        int? num2 = array3?.Length;
                        if (num2.HasValue && num2.GetValueOrDefault() > 0)
{
                            sourceCache2.EmplaceCache(sheet.SheetName, array3);
                            sourceCache2.Mod?.sourceRows.UnionWith(array3);
                            hashSet.Add(sourceData);
                        }
                    }
                }
                continue;
            }
            foreach (KeyValuePair<string, SourceData.BaseRow[]> item3 in sourceCache2.Source)
            {
                item3.Deconstruct(out var key, out var value4);
                string text2 = key;
                SourceData.BaseRow[] array4 = value4;
                SourceData sourceData2 = FindSourceByName(text2);
                if (!(sourceData2 is SourceThingV))
                {
                    if (sourceData2 is SourceElement || (object)sourceData2 == null)
                    {
                        continue;
                    }
                }
                else
                {
                    sourceData2 = EClass.sources.things;
                }
                if (array4 == null)
                {
                    Debug.Log("#source cached rows are empty " + text + ":" + text2);
                    continue;
                }
                int num3 = sourceData2.ImportRows(array4);
                sourceCache2.Mod?.sourceRows.UnionWith(array4);
                Debug.Log($"#source workbook-cache {text}:{text2}:{num3}");
                hashSet.Add(sourceData2);
            }
        }
        if (resetData)
        {
            HotInit(hashSet);
        }
        return hashSet;
    }
References $, Debug, SourceManager.elements, file, fileProviders, FindSourceByName(), HotInit(), SourceData< T, T2 >.ImportRows(), item, LoadBySheetName(), PrefetchWorkbook(), sheets, EClass.sources, and SourceManager.things.
Referenced by ModManager.ImportAllModSourceSheets().
LoadBySheetName()
SourceData.BaseRow[] SourceImporter.LoadBySheetName (ISheet sheet, string file) inline private
Definition at line 39 of file SourceImporter.cs.
    {
        string sheetName = sheet.SheetName;
        try
        {
            SourceData sourceData = FindSourceByName(sheetName);
            if ((object)sourceData == null)
            {
                Debug.Log("#source skipping sheet " + sheetName);
                return (null, null);
            }
            IList list;
            if (!(sourceData is SourceThingV))
            {
                list = sourceData.GetField<IList>("rows");
            }
            else
            {
                IList rows = EClass.sources.things.rows;
                list = rows;
            }
            IList list2 = list;
            int count = list2.Count;
            Debug.Log("#source loading sheet " + sheetName);
            ExcelParser.path = file;
            string fileNameWithoutExtension = Path.GetFileNameWithoutExtension(file);
            if (!sourceData.ImportData(sheet, fileNameWithoutExtension, overwrite: true))
            {
                throw new SourceParseException("#source failed to import data " + sourceData.GetType().Name + ":" + fileNameWithoutExtension + "/" + sheetName);
            }
            SourceData.BaseRow[] item = Array.Empty<SourceData.BaseRow>();
            int num = ERROR.msg.Split('/')[^1].ToInt();
            if (num > 0)
            {
                item = list2.OfType<SourceData.BaseRow>().Skip(count).Take(num)
                    .ToArray();
            }
            return (sourceData, item);
        }
        catch (Exception arg)
        {
            Debug.LogError($"#source failed to load sheet {sheetName}\n{arg}");
        }
        return (null, null);
    }
References $, Debug, file, FindSourceByName(), SourceData< T, T2 >.ImportData(), item, ERROR.msg, EClass.sources, and SourceManager.things.
Referenced by ImportFilesCached().
PrefetchWorkbook()
string ISheet[] ISheet element SourceImporter.PrefetchWorkbook (string file) inline private
Definition at line 204 of file SourceImporter.cs.
    {
        using FileStream @is = File.Open(file, FileMode.Open, FileAccess.Read, FileShare.ReadWrite);
        XSSFWorkbook xSSFWorkbook = new XSSFWorkbook((Stream)@is);
        List<ISheet> list = new List<ISheet>();
        ISheet item = null;
        for (int i = 0; i < xSSFWorkbook.NumberOfSheets; i++)
        {
            ISheet sheetAt = xSSFWorkbook.GetSheetAt(i);
            SourceData sourceData = FindSourceByName(sheetAt.SheetName);
            if (!(sourceData is SourceElement))
            {
                if ((object)sourceData != null)
                {
                    list.Add(sheetAt);
                }
            }
            else
            {
                item = sheetAt;
            }
        }
        Debug.Log("#source workbook-prefetch " + file.ShortPath());
        return (file: file, sheets: list.ToArray(), element: item);
    }
Referenced by ImportFilesCached().
Member Data Documentation
_sourceMapping
readonly IReadOnlyDictionary<string, SourceData> SourceImporter._sourceMapping private
Definition at line 12 of file SourceImporter.cs.
Referenced by FindSourceByName(), and SourceImporter().
file
string SourceImporter.file private
Definition at line 204 of file SourceImporter.cs.
Referenced by ImportFilesCached(), and LoadBySheetName().
fileProviders
Dictionary<string, EMod> SourceImporter.fileProviders = new Dictionary<string, EMod>(PathComparer.Default)
Definition at line 14 of file SourceImporter.cs.
Referenced by ModManager.ImportAllModSourceSheets(), and ImportFilesCached().
sheets
string ISheet [] SourceImporter.sheets private
Definition at line 204 of file SourceImporter.cs.
Referenced by ImportFilesCached().
SourceData
SourceImporter.SourceData private
Definition at line 39 of file SourceImporter.cs.
The documentation for this class was generated from the following file:
Elin/SourceImporter.cs