Elin Decompiled Documentation: ShippingResult Class Reference
ShippingResult Class Reference
Classes
class Item
Public Member Functions
int GetIncome ()
Public Attributes
long[] ints = new long[10]
List< Item > items = new List<Item>()
Properties
long total [get, set]
int rawDate [get, set]
int uidZone [get, set]
int hearthLv [get, set]
int hearthExp [get, set]
int hearthExpGained [get, set]
int debt [get, set]
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Additional Inherited Members
Static Public Member Functions inherited from EClass
static int rndSeed (int a, int seed)
static int rnd (long a)
static int rnd (int a)
static int curve (int _a, int start, int step, int rate=75)
static int sqrt (int a)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Static Public Attributes inherited from EClass
static Core core
Detailed Description
Definition at line 4 of file ShippingResult.cs.
Member Function Documentation
GetIncome()
int ShippingResult.GetIncome () inline
Definition at line 126 of file ShippingResult.cs.
    {
        int num = 0;
        foreach (Item item in items)
        {
            num += item.income;
        }
        return num;
    }
References item, and items.
Referenced by LayerShippingResult.Refresh().
Member Data Documentation
ints
long [] ShippingResult.ints = new long[10]
Definition at line 37 of file ShippingResult.cs.
items
List<Item> ShippingResult.items = new List<Item>()
Definition at line 40 of file ShippingResult.cs.
Referenced by GetIncome(), and LayerShippingResult.Show().
Property Documentation
debt
int ShippingResult.debt get set
Definition at line 114 of file ShippingResult.cs.
    {
        get
        {
            return (int)ints[6];
        }
        set
        {
            ints[6] = value;
        }
    }
Referenced by LayerShippingResult.Refresh().
hearthExp
int ShippingResult.hearthExp get set
Definition at line 90 of file ShippingResult.cs.
    {
        get
        {
            return (int)ints[4];
        }
        set
        {
            ints[4] = value;
        }
    }
hearthExpGained
int ShippingResult.hearthExpGained get set
Definition at line 102 of file ShippingResult.cs.
    {
        get
        {
            return (int)ints[5];
        }
        set
        {
            ints[5] = value;
        }
    }
hearthLv
int ShippingResult.hearthLv get set
Definition at line 78 of file ShippingResult.cs.
    {
        get
        {
            return (int)ints[3];
        }
        set
        {
            ints[3] = value;
        }
    }
Referenced by LayerShippingResult.Refresh().
rawDate
int ShippingResult.rawDate get set
Definition at line 54 of file ShippingResult.cs.
    {
        get
        {
            return (int)ints[1];
        }
        set
        {
            ints[1] = value;
        }
    }
Referenced by LayerShippingResult.Show().
total
long ShippingResult.total get set
Definition at line 42 of file ShippingResult.cs.
    {
        get
        {
            return ints[0];
        }
        set
        {
            ints[0] = value;
        }
    }
Referenced by LayerShippingResult.Refresh().
uidZone
int ShippingResult.uidZone get set
Definition at line 66 of file ShippingResult.cs.
    {
        get
        {
            return (int)ints[2];
        }
        set
        {
            ints[2] = value;
        }
    }
Referenced by LayerShippingResult.Refresh(), and LayerShippingResult.Show().
The documentation for this class was generated from the following file:
Elin/ShippingResult.cs