Elin Decompiled Documentation: SourceFloor Class Reference
SourceFloor Class Reference
Classes
class Row
Public Member Functions
override Row CreateRow ()
override Row CreateRowByMapping (IReadOnlyDictionary< string, int > mapping)
override void SetRow (Row r)
override IReadOnlyDictionary< string, int > GetRowMapping ()
override IReadOnlyDictionary< string, string > GetTypeMapping ()
override void BackupPref ()
override void RestorePref ()
override void ValidatePref ()
override void OnAfterImportData ()
override void OnInit ()
void OnAfterInit ()
Public Member Functions inherited from SourceDataInt< SourceFloor.Row >
override T GetRow (string id)
Public Attributes
Dictionary< int, Row > _rows = new Dictionary<int, Row>()
Static Public Attributes
static readonly IReadOnlyDictionary< string, int > RowMapping
static readonly IReadOnlyDictionary< string, string > TypeMapping
static RenderData FallbackRenderData
Detailed Description
Definition at line 4 of file SourceFloor.cs.
Member Function Documentation
BackupPref()
override void SourceFloor.BackupPref () inline
Definition at line 237 of file SourceFloor.cs.
    {
        _rows.Clear();
        foreach (Row row in rows)
        {
            _rows[row.id] = row;
        }
    }
References _rows, and TileRow.id.
CreateRow()
override Row SourceFloor.CreateRow () inline
Definition at line 148 of file SourceFloor.cs.
    {
        return new Row
        {
            id = SourceData.GetInt(0),
            alias = SourceData.GetString(1),
            name_JP = SourceData.GetString(2),
            name = SourceData.GetString(3),
            sort = SourceData.GetInt(4),
            idBiome = SourceData.GetString(5),
            reqHarvest = SourceData.GetStringArray(6),
            hp = SourceData.GetInt(7),
            _tileType = SourceData.GetString(8),
            _idRenderData = SourceData.GetString(9),
            tiles = SourceData.GetIntArray(10),
            anime = SourceData.GetIntArray(11),
            colorMod = SourceData.GetInt(12),
            value = SourceData.GetInt(13),
            LV = SourceData.GetInt(14),
            recipeKey = SourceData.GetStringArray(15),
            factory = SourceData.GetStringArray(16),
            components = SourceData.GetStringArray(17),
            defMat = SourceData.GetString(18),
            defBlock = SourceData.GetString(19),
            bridgeBlock = SourceData.GetString(20),
            category = SourceData.GetString(21),
            edge = SourceData.GetInt(22),
            autotile = SourceData.GetInt(23),
            autotilePriority = SourceData.GetInt(24),
            autotileBrightness = SourceData.GetFloat(25),
            soundFoot = SourceData.GetString(26),
            tag = SourceData.GetStringArray(27),
            detail_JP = SourceData.GetString(28),
            detail = SourceData.GetString(29)
        };
    }
References SourceData< T, T2 >.GetFloat(), SourceData< T, T2 >.GetInt(), SourceData< T, T2 >.GetIntArray(), SourceData< T, T2 >.GetString(), and SourceData< T, T2 >.GetStringArray().
CreateRowByMapping()
override Row SourceFloor.CreateRowByMapping (IReadOnlyDictionary< string, int > mapping) inline
Definition at line 185 of file SourceFloor.cs.
    {
        return new Row
        {
            id = SourceData.GetInt(mapping["id"]),
            alias = SourceData.GetString(mapping["alias"]),
            name_JP = SourceData.GetString(mapping["name_JP"]),
            name = SourceData.GetString(mapping["name"]),
            sort = SourceData.GetInt(mapping["sort"]),
            idBiome = SourceData.GetString(mapping["idBiome"]),
            reqHarvest = SourceData.GetStringArray(mapping["reqHarvest"]),
            hp = SourceData.GetInt(mapping["hp"]),
            _tileType = SourceData.GetString(mapping["_tileType"]),
            _idRenderData = SourceData.GetString(mapping["_idRenderData"]),
            tiles = SourceData.GetIntArray(mapping["tiles"]),
            anime = SourceData.GetIntArray(mapping["anime"]),
            colorMod = SourceData.GetInt(mapping["colorMod"]),
            value = SourceData.GetInt(mapping["value"]),
            LV = SourceData.GetInt(mapping["LV"]),
            recipeKey = SourceData.GetStringArray(mapping["recipeKey"]),
            factory = SourceData.GetStringArray(mapping["factory"]),
            components = SourceData.GetStringArray(mapping["components"]),
            defMat = SourceData.GetString(mapping["defMat"]),
            defBlock = SourceData.GetString(mapping["defBlock"]),
            bridgeBlock = SourceData.GetString(mapping["bridgeBlock"]),
            category = SourceData.GetString(mapping["category"]),
            edge = SourceData.GetInt(mapping["edge"]),
            autotile = SourceData.GetInt(mapping["autotile"]),
            autotilePriority = SourceData.GetInt(mapping["autotilePriority"]),
            autotileBrightness = SourceData.GetFloat(mapping["autotileBrightness"]),
            soundFoot = SourceData.GetString(mapping["soundFoot"]),
            tag = SourceData.GetStringArray(mapping["tag"]),
            detail_JP = SourceData.GetString(mapping["detail_JP"]),
            detail = SourceData.GetString(mapping["detail"])
        };
    }
References SourceData< T, T2 >.GetFloat(), SourceData< T, T2 >.GetInt(), SourceData< T, T2 >.GetIntArray(), SourceData< T, T2 >.GetString(), and SourceData< T, T2 >.GetStringArray().
GetRowMapping()
override IReadOnlyDictionary< string, int > SourceFloor.GetRowMapping () inline
Definition at line 227 of file SourceFloor.cs.
    {
        return RowMapping;
    }
References RowMapping.
GetTypeMapping()
override IReadOnlyDictionary< string, string > SourceFloor.GetTypeMapping () inline
Definition at line 232 of file SourceFloor.cs.
    {
        return TypeMapping;
    }
References TypeMapping.
OnAfterImportData()
override void SourceFloor.OnAfterImportData () inline
Definition at line 262 of file SourceFloor.cs.
    {
        int num = 0;
        foreach (Row row in rows)
        {
            if (row.sort != 0)
            {
                num = row.sort;
            }
            row.sort = num;
            num++;
        }
        rows.Sort((Row a, Row b) => a.id - b.id);
    }
References TileRow.id, and RenderRow.sort.
OnAfterInit()
void SourceFloor.OnAfterInit () inline
Definition at line 287 of file SourceFloor.cs.
    {
        foreach (Row row in rows)
        {
            row._defBlock = EClass.sources.blocks.alias[row.defBlock];
            row._bridgeBlock = EClass.sources.blocks.alias[row.bridgeBlock];
            row.nonGradient = row.ContainsTag("nonGradient");
        }
    }
References SourceManager.blocks, SourceFloor.Row.bridgeBlock, RenderRow.ContainsTag(), SourceFloor.Row.defBlock, and EClass.sources.
Referenced by SourceManager.Init().
OnInit()
override void SourceFloor.OnInit () inline
Definition at line 277 of file SourceFloor.cs.
    {
        FallbackRenderData = ResourceCache.Load<RenderData>("Scene/Render/Data/floor");
        Cell.floorList = rows;
        foreach (Row row in rows)
        {
            row.Init();
        }
    }
References FallbackRenderData, and TileRow.Init().
RestorePref()
override void SourceFloor.RestorePref () inline
Definition at line 246 of file SourceFloor.cs.
    {
        foreach (Row row in rows)
        {
            row.pref = _rows.TryGetValue(row.id)?.pref ?? new SourcePref();
        }
    }
References _rows, and TileRow.id.
SetRow()
override void SourceFloor.SetRow (Row r) inline
Definition at line 222 of file SourceFloor.cs.
    {
        map[r.id] = r;
    }
References TileRow.id.
ValidatePref()
override void SourceFloor.ValidatePref () inline
Definition at line 254 of file SourceFloor.cs.
    {
        foreach (Row row in rows)
        {
            row.pref.Validate();
        }
    }
References RenderRow.pref, and SourcePref.Validate().
Member Data Documentation
_rows
Dictionary<int, Row> SourceFloor._rows = new Dictionary<int, Row>()
Definition at line 144 of file SourceFloor.cs.
Referenced by BackupPref(), and RestorePref().
FallbackRenderData
RenderData SourceFloor.FallbackRenderData static
Definition at line 146 of file SourceFloor.cs.
Referenced by OnInit().
RowMapping
readonly IReadOnlyDictionary<string, int> SourceFloor.RowMapping static
Definition at line 76 of file SourceFloor.cs.
Referenced by GetRowMapping().
TypeMapping
readonly IReadOnlyDictionary<string, string> SourceFloor.TypeMapping static
Definition at line 110 of file SourceFloor.cs.
Referenced by GetTypeMapping().
The documentation for this class was generated from the following file:
Elin/SourceFloor.cs