Elin Decompiled Documentation: ListPeopleEmbark Class Reference
ListPeopleEmbark Class Reference
Public Member Functions
override void OnInstantiate (Chara c, ItemGeneral i)
override void OnClick (Chara c, ItemGeneral i)
override void OnList ()
override void OnRefreshMenu ()
Public Member Functions inherited from BaseListPeople
virtual bool IsDisabled (Chara c)
override void List ()
override void OnInstantiate (Chara a, ItemGeneral b)
virtual void SetSubText (Chara a, ItemGeneral b)
override void OnClick (Chara c, ItemGeneral i)
override void OnList ()
override void OnRefreshMenu ()
Public Member Functions inherited from ListOwner< Chara, ItemGeneral >
virtual void List ()
virtual void List ()
virtual void OnCreate ()
virtual void OnCreate ()
virtual void OnSwitchContent ()
virtual void OnSwitchContent ()
virtual void OnRefreshMenu ()
virtual void OnRefreshMenu ()
void MoveToOther (object c)
void MoveToOther (object c)
virtual void OnClick (T1 a, T2 b)
virtual void OnInstantiate (T1 a, T2 b)
virtual void OnList ()
Public Attributes
List< Chara > charas
UIButton button
Public Attributes inherited from BaseListPeople
Chara owner
FactionMemberType memberType
Public Attributes inherited from ListOwner< Chara, ItemGeneral >
Layer layer
Window window
UIMultiList multi
ListOwner other
UIList list
WindowMenu menu
string textTab
string textHeader
bool main
int index
Additional Inherited Members
Static Public Member Functions inherited from EClass
static int rnd (int a)
static int curve (int a, int start, int step, int rate=75)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Static Public Attributes inherited from EClass
static Core core
Properties inherited from ListPeople
override bool ShowCharaSheet [get]
override bool ShowGoto [get]
override bool ShowHome [get]
override bool ShowShowMode [get]
Properties inherited from BaseListPeople
new LayerPeople layer [get]
override string IdHeaderRow [get]
virtual bool ShowCharaSheet [get]
virtual bool ShowShowMode [get]
virtual LayerPeople.ShowMode ShowMode [get]
virtual bool ShowGoto [get]
virtual bool ShowHome [get]
Properties inherited from ListOwner< Chara, ItemGeneral >
ListOwner Main [get]
virtual string IdTitle [get]
virtual string IdHeaderRow [get]
virtual string TextTab [get]
virtual string TextHeader [get]
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Detailed Description
Definition at line 3 of file ListPeopleEmbark.cs.
Member Function Documentation
OnClick()
override void ListPeopleEmbark.OnClick (Chara c, ItemGeneral i) inline
Definition at line 14 of file ListPeopleEmbark.cs.
    {
        charas.Remove(c);
        (other as ListPeopleEmbark).charas.Add(c);
        MoveToOther(c);
        base.Main.OnRefreshMenu();
    }
References charas, ListOwner< Chara, ItemGeneral >.MoveToOther(), and ListOwner< Chara, ItemGeneral >.other.
OnInstantiate()
override void ListPeopleEmbark.OnInstantiate (Chara c, ItemGeneral i) inline
Definition at line 9 of file ListPeopleEmbark.cs.
    {
        i.SetSubText(c.GetActionText(), 240);
    }
References Chara.GetActionText(), and ItemGeneral.SetSubText().
OnList()
override void ListPeopleEmbark.OnList () inline virtual
Reimplemented from BaseListPeople.
Definition at line 22 of file ListPeopleEmbark.cs.
    {
        foreach (Chara chara in charas)
        {
            list.Add(chara);
        }
    }
References charas, and ListOwner< Chara, ItemGeneral >.list.
OnRefreshMenu()
override void ListPeopleEmbark.OnRefreshMenu () inline virtual
Reimplemented from BaseListPeople.
Definition at line 30 of file ListPeopleEmbark.cs.
    {
        if (main)
        {
            button.interactable = charas.Count > 0 && (other as ListPeopleEmbark).charas.Count > 0;
        }
    }
References charas, ListOwner< Chara, ItemGeneral >.main, and ListOwner< Chara, ItemGeneral >.other.
Member Data Documentation
button
UIButton ListPeopleEmbark.button
Definition at line 7 of file ListPeopleEmbark.cs.
charas
List<Chara> ListPeopleEmbark.charas
Definition at line 5 of file ListPeopleEmbark.cs.
Referenced by OnClick(), OnList(), and OnRefreshMenu().
The documentation for this class was generated from the following file:
Elin/ListPeopleEmbark.cs