Elin Decompiled Documentation: ActorEx Class Reference
ActorEx Class Reference
Public Types
enum Type { Default , JukeBox }
Public Member Functions
void SetOwner (Card c)
float GetVolume ()
void Refresh ()
void Kill ()
Public Attributes
Type type
Card owner
bool alwaysOn
float outsideRoomVolume = 0.5f
float outsideLotVolume = 0.5f
int maxDistance
int minInterval = 1
int randomInterval
AudioSource audioSource
SoundData data
Private Attributes
int next
Additional Inherited Members
Static Public Member Functions inherited from EMono
static int rnd (int a)
Static Public Attributes inherited from EMono
static Core core
Properties inherited from EMono
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SoundManager Sound [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static CoreDebug debug [get]
Detailed Description
Definition at line 3 of file ActorEx.cs.
Member Enumeration Documentation
Type
enum ActorEx.Type
Enumerator
Default
JukeBox
Definition at line 5 of file ActorEx.cs.
    {
        Default,
        JukeBox
    }
Member Function Documentation
GetVolume()
float ActorEx.GetVolume () inline
Definition at line 48 of file ActorEx.cs.
    {
        if (!EMono._zone.isStarted || !owner.IsInstalled)
        {
            return 0f;
        }
        Room room = EMono.pc.Cell.room;
        Room room2 = owner.Cell.room;
        bool flag = room2 == null || room2.data.atrium || !room2.HasRoof;
        bool flag2 = room == room2 || (room2 == null && (room.data.atrium || !room.HasRoof));
        bool num = flag2 || room?.lot == room2?.lot;
        float num2 = ((alwaysOn || owner.isOn) ? 1f : 0f);
        if (!num)
        {
            num2 *= outsideLotVolume;
        }
        if (!flag2 && room2 != null)
        {
            num2 *= outsideRoomVolume;
        }
        if (num2 <= 0f)
        {
            return 0f;
        }
        if (type == Type.JukeBox)
        {
            num2 *= 0.5f + (flag ? 0.25f : 0f);
            if (flag2)
            {
                int num3 = EMono.pc.Dist(owner);
                if (num3 < 8)
                {
                    float num4 = (float)(8 - num3) * SoundManager.current.jukeboxMod - 0.2f;
                    if (num4 < SoundManager.bgmDumpMod)
                    {
                        SoundManager.bgmDumpMod = num4;
                    }
                }
            }
        }
        return num2;
    }
References EMono._zone, alwaysOn, Card.Cell, Card.Dist(), Room.HasRoof, Card.IsInstalled, Card.isOn, Zone.isStarted, Room.lot, outsideLotVolume, outsideRoomVolume, owner, EMono.pc, Cell.room, and type.
Referenced by Refresh().
Kill()
void ActorEx.Kill () inline
Definition at line 153 of file ActorEx.cs.
    {
        Object.Destroy(base.gameObject);
    }
Referenced by Scene.ClearActorEx(), and Scene.RemoveActorEx().
Refresh()
void ActorEx.Refresh () inline
Definition at line 91 of file ActorEx.cs.
    {
        if (owner.parent != EMono.pc.currentZone)
        {
            Debug.LogWarning(owner);
            return;
        }
        next--;
        if (next > 0)
        {
            return;
        }
        next = minInterval + Rand.rnd(randomInterval + 1);
        if (maxDistance != 0)
        {
            int num = EMono.pc.Dist(owner);
            if (base.gameObject.activeSelf)
            {
                if (num > maxDistance)
                {
                    base.gameObject.SetActive(value: false);
                    return;
                }
            }
            else
            {
                if (num > maxDistance)
                {
                    return;
                }
                base.gameObject.SetActive(value: true);
            }
        }
        float volume = GetVolume();
        if (maxDistance != 0)
        {
            base.gameObject.SetActive(volume > 0f);
        }
        if ((bool)audioSource)
        {
            audioSource.volume = data.volume * volume;
            if (!audioSource.isPlaying && volume > 0f)
            {
                audioSource.Play();
            }
        }
        if (!(volume <= 0f))
        {
            Vector3 vector = owner.pos.PositionCenter();
            vector.z = 0f;
            vector.x -= 0.64f;
            if ((bool)audioSource)
            {
                base.transform.position = vector;
            }
            else
            {
                SoundManager.current.Play(data, vector, volume);
            }
        }
    }
References audioSource, Chara.currentZone, data, Debug, Card.Dist(), GetVolume(), maxDistance, minInterval, next, owner, Card.parent, EMono.pc, Card.pos, Point.PositionCenter(), randomInterval, and Rand.rnd().
Referenced by Scene.RefreshActorEx(), and SetOwner().
SetOwner()
void ActorEx.SetOwner (Card c) inline
Definition at line 33 of file ActorEx.cs.
    {
        owner = c;
        if (type == Type.JukeBox)
        {
            data = EMono.core.refs.dictBGM.TryGetValue(owner.refVal);
        }
        if ((bool)audioSource)
        {
            audioSource.clip = data.clip;
            audioSource.pitch = data.pitch * (1f + ((data.randomPitch == 0f) ? 0f : Rand.Range(0f - data.randomPitch, data.randomPitch)));
        }
        Refresh();
    }
References audioSource, EMono.core, data, CoreRef.dictBGM, owner, Rand.Range(), Refresh(), Core.refs, Card.refVal, and type.
Referenced by Scene.AddActorEx().
Member Data Documentation
alwaysOn
bool ActorEx.alwaysOn
Definition at line 15 of file ActorEx.cs.
Referenced by GetVolume().
audioSource
AudioSource ActorEx.audioSource
Definition at line 29 of file ActorEx.cs.
Referenced by Refresh(), and SetOwner().
data
SoundData ActorEx.data
Definition at line 31 of file ActorEx.cs.
Referenced by Refresh(), and SetOwner().
maxDistance
int ActorEx.maxDistance
Definition at line 21 of file ActorEx.cs.
Referenced by Refresh().
minInterval
int ActorEx.minInterval = 1
Definition at line 23 of file ActorEx.cs.
Referenced by Refresh().
next
int ActorEx.next private
Definition at line 27 of file ActorEx.cs.
Referenced by Refresh().
outsideLotVolume
float ActorEx.outsideLotVolume = 0.5f
Definition at line 19 of file ActorEx.cs.
Referenced by GetVolume().
outsideRoomVolume
float ActorEx.outsideRoomVolume = 0.5f
Definition at line 17 of file ActorEx.cs.
Referenced by GetVolume().
owner
Card ActorEx.owner
Definition at line 13 of file ActorEx.cs.
Referenced by GetVolume(), Refresh(), and SetOwner().
randomInterval
int ActorEx.randomInterval
Definition at line 25 of file ActorEx.cs.
Referenced by Refresh().
type
Type ActorEx.type
Definition at line 11 of file ActorEx.cs.
Referenced by GetVolume(), and SetOwner().
The documentation for this class was generated from the following file:
Elin/ActorEx.cs