Elin Decompiled Documentation: DramaOutcome Class Reference
DramaOutcome Class Reference
Public Member Functions
void StartNewGame ()
void StartNewGame2 ()
void PutOutFire ()
void OnClaimLand ()
void AddMaid ()
void convert_Jure ()
void QuestSharedContainer_Drop1 ()
void QuestShippingChest_Drop1 ()
void QuestExploration_Drop1 ()
void QuestExploration_MeetFarris ()
void QuestExploration_MeetFarris2 ()
void QuestExploration_AfterCrystal ()
void QuestExploration_AfterComplete ()
void QuestCraft_Drop1 ()
void QuestDefense_0 ()
void QuestVernis_DropRecipe ()
void QuestDefense_1 ()
void QuestDefense_2 ()
void QuestDebt_reward ()
void Tutorial1 ()
void WelcomeMsg ()
void chara_hired ()
void chara_hired_ticket ()
void nerun_gift ()
void nerun_gift2 ()
void nerun_gift3 ()
void fiama_gold ()
void fiama_pet1 ()
void fiama_pet2 ()
void fiama_pet3 ()
void fiama_pet4 ()
void fiama_starter_gift ()
void revive_pet ()
void nasu_join ()
void melilith_friend ()
void sister_friend ()
void sister_change ()
void get_scratch ()
void duponne_capture ()
void duponne_reward ()
void poppy_found ()
void event_swordkeeper ()
void guild_trial ()
void guild_join ()
void guild_mageTrial ()
void guild_promote ()
bool check_sketch ()
int GetFelmeraRewardIndex ()
bool check_sketch2 ()
List< Thing > ListFelmeraBarter ()
void give_sketch_reward ()
void give_sketch_special ()
Static Public Member Functions
static bool If (DramaChoice item, Chara c)
Static Public Member Functions inherited from EMono
static int rnd (int a)
Public Attributes
DramaManager manager
Static Public Attributes
static string idJump
Static Public Attributes inherited from EMono
static Core core
Properties
DramaSequence sequence [get]
Person tg [get]
Chara cc [get]
Properties inherited from EMono
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SoundManager Sound [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static CoreDebug debug [get]
Private Member Functions
void fiama_pet (Chara c)
Detailed Description
Definition at line 4 of file DramaOutcome.cs.
Member Function Documentation
AddMaid()
void DramaOutcome.AddMaid () inline
Definition at line 57 of file DramaOutcome.cs.
    {
    }
Referenced by OnClaimLand().
chara_hired()
void DramaOutcome.chara_hired () inline
Definition at line 193 of file DramaOutcome.cs.
    {
        if (EMono.Branch.IsRecruit(cc))
        {
            EMono.pc.ModCurrency(-CalcGold.Hire(cc), "money2");
            cc.SetBool(18, enable: true);
        }
        EMono.Sound.Play("good");
        EMono.Branch.Recruit(cc);
    }
References EMono.Branch, cc, CalcGold.Hire(), FactionBranch.IsRecruit(), Card.ModCurrency(), EMono.pc, FactionBranch.Recruit(), BaseCard.SetBool(), and EMono.Sound.
chara_hired_ticket()
void DramaOutcome.chara_hired_ticket () inline
Definition at line 204 of file DramaOutcome.cs.
    {
        EMono.pc.things.Find("ticket_resident").ModNum(-1);
        EMono.Sound.Play("good");
        cc.SetBool(18, enable: true);
        EMono.Branch.Recruit(cc);
    }
References EMono.Branch, cc, ThingContainer.Find(), Card.ModNum(), EMono.pc, FactionBranch.Recruit(), BaseCard.SetBool(), EMono.Sound, and Card.things.
check_sketch()
bool DramaOutcome.check_sketch () inline
Definition at line 437 of file DramaOutcome.cs.
    {
        Thing thing = EMono.pc.things.Find("sketch_old");
        if (thing == null)
        {
            return false;
        }
        int num = thing.Num;
        thing.Destroy();
        bool flag = false;
        for (int i = 0; i < num; i++)
        {
            for (int j = 0; j < 5; j++)
            {
                int item = EMono.core.refs.dictSketches.Keys.RandomItem();
                if (!EMono.player.sketches.Contains(item))
                {
                    EMono.player.sketches.Add(item);
                    Msg.Say("add_sketch", item.ToString() ?? "");
                    flag = true;
                    break;
                }
            }
        }
        if (flag)
        {
            SE.WriteJournal();
            return true;
        }
        return false;
    }
References EMono.core, Card.Destroy(), CoreRef.dictSketches, ThingContainer.Find(), item, UDictionary< TKey, TValue >.Keys, Card.Num, EMono.pc, EMono.player, Core.refs, Msg.Say(), Player.sketches, and Card.things.
check_sketch2()
bool DramaOutcome.check_sketch2 () inline
Definition at line 481 of file DramaOutcome.cs.
    {
        return GetFelmeraRewardIndex() > EMono.player.lastFelmeraReward;
    }
References GetFelmeraRewardIndex(), Player.lastFelmeraReward, and EMono.player.
convert_Jure()
void DramaOutcome.convert_Jure () inline
Definition at line 61 of file DramaOutcome.cs.
    {
        EMono.game.religions.Healing.JoinFaith(EMono.pc, Religion.ConvertType.Campaign);
        if (!EMono.player.flags.gotJurePillow)
        {
            EMono.player.flags.gotJurePillow = true;
            EMono.player.DropReward(ThingGen.Create("pillow_jure"));
        }
    }
References ThingGen.Create(), Player.DropReward(), Player.flags, EMono.game, Player.Flags.gotJurePillow, ReligionManager.Healing, Religion.JoinFaith(), EMono.pc, EMono.player, and Game.religions.
duponne_capture()
void DramaOutcome.duponne_capture () inline
Definition at line 361 of file DramaOutcome.cs.
    {
        EMono.pc.things.Find("minohorn")?.ModNum(-1);
        EMono.player.DropReward(ThingGen.Create("duponneball"));
    }
References ThingGen.Create(), Player.DropReward(), ThingContainer.Find(), Card.ModNum(), EMono.pc, EMono.player, and Card.things.
duponne_reward()
void DramaOutcome.duponne_reward () inline
Definition at line 367 of file DramaOutcome.cs.
    {
        EMono.player.DropReward(ThingGen.CreateRedBook("advweek_12"), silent: true);
        EMono.player.DropReward(ThingGen.Create("crystal_earth"), silent: true);
        EMono.player.DropReward(ThingGen.Create("crystal_sun"), silent: true);
        EMono.player.DropReward(ThingGen.Create("crystal_mana"), silent: true);
        EMono.player.DropReward(ThingGen.CreateRecipe("rune_mold_earth"), silent: true);
        EMono.player.DropReward(ThingGen.CreateRecipe("rune_mold_sun"), silent: true);
        EMono.player.DropReward(ThingGen.CreateRecipe("rune_mold_mana"));
    }
References ThingGen.Create(), ThingGen.CreateRecipe(), ThingGen.CreateRedBook(), Player.DropReward(), and EMono.player.
event_swordkeeper()
void DramaOutcome.event_swordkeeper () inline
Definition at line 390 of file DramaOutcome.cs.
    {
        EMono._zone.AddChara("swordkeeper", 45, 52);
    }
References EMono._zone, and Zone.AddChara().
fiama_gold()
void DramaOutcome.fiama_gold () inline
Definition at line 233 of file DramaOutcome.cs.
    {
        EMono.player.DropReward(ThingGen.Create("money2").SetNum(10));
        if (EMono.game.idPrologue == 2)
        {
            EMono.player.DropReward(ThingGen.Create("hammer"));
        }
    }
References ThingGen.Create(), Player.DropReward(), EMono.game, Game.idPrologue, EMono.player, and Card.SetNum().
fiama_pet()
void DramaOutcome.fiama_pet (Chara c) inline private
Definition at line 266 of file DramaOutcome.cs.
    {
        EMono._zone.AddCard(c, EMono.pc.pos);
        c.MakeAlly();
        c.SetInt(100, 1);
    }
References EMono._zone, Zone.AddCard(), Chara.MakeAlly(), EMono.pc, Card.pos, and BaseCard.SetInt().
Referenced by fiama_pet1(), fiama_pet2(), fiama_pet3(), and fiama_pet4().
fiama_pet1()
void DramaOutcome.fiama_pet1 () inline
Definition at line 242 of file DramaOutcome.cs.
    {
        Chara c = CharaGen.Create("dog");
        fiama_pet(c);
    }
References CharaGen.Create(), and fiama_pet().
fiama_pet2()
void DramaOutcome.fiama_pet2 () inline
Definition at line 248 of file DramaOutcome.cs.
    {
        Chara c = CharaGen.Create("cat");
        fiama_pet(c);
    }
References CharaGen.Create(), and fiama_pet().
fiama_pet3()
void DramaOutcome.fiama_pet3 () inline
Definition at line 254 of file DramaOutcome.cs.
    {
        Chara c = CharaGen.Create("bearCub");
        fiama_pet(c);
    }
References CharaGen.Create(), and fiama_pet().
fiama_pet4()
void DramaOutcome.fiama_pet4 () inline
Definition at line 260 of file DramaOutcome.cs.
    {
        Chara c = CharaGen.Create("shojo");
        fiama_pet(c);
    }
References CharaGen.Create(), and fiama_pet().
fiama_starter_gift()
void DramaOutcome.fiama_starter_gift () inline
Definition at line 273 of file DramaOutcome.cs.
    {
        DramaChoice lastChoice = DramaChoice.lastChoice;
        Thing thing = null;
        switch (lastChoice.index)
        {
        case 0:
            thing = ThingGen.Create("ring_decorative").SetNoSell();
            thing.elements.SetBase(65, 10);
            EMono.player.DropReward(thing);
            break;
        case 1:
            EMono.player.DropReward(ThingGen.Create("ticket_resident").SetNoSell());
            EMono.player.DropReward(ThingGen.Create("1174").SetNoSell());
            break;
        case 2:
            thing = ThingGen.Create("boots_").SetNoSell();
            thing.elements.SetBase(65, 5);
            thing.elements.SetBase(407, 5);
            EMono.player.DropReward(thing);
            break;
        case 3:
            EMono.player.DropReward(ThingGen.Create("1085").SetNum(3).SetNoSell());
            break;
        case 4:
        {
            for (int i = 0; i < 10; i++)
            {
                EMono.player.DropReward(ThingGen.Create("234").SetNoSell());
            }
            break;
        }
        default:
            cc.DoHostileAction(EMono.pc, immediate: true);
            cc.calmCheckTurn = 100;
            break;
        }
    }
References cc, ThingGen.Create(), Chara.DoHostileAction(), Player.DropReward(), Card.elements, DramaChoice.index, DramaChoice.lastChoice, EMono.pc, EMono.player, ElementContainer.SetBase(), Card.SetNoSell(), and Card.SetNum().
get_scratch()
void DramaOutcome.get_scratch () inline
Definition at line 355 of file DramaOutcome.cs.
    {
        EMono._map.TrySmoothPick(EMono.pc.pos, ThingGen.Create("scratchcard"), EMono.pc);
        EMono.game.dateScratch = EMono.world.date.GetRaw(24);
    }
References EMono._map, ThingGen.Create(), World.date, Date.GetRaw(), EMono.pc, Card.pos, Map.TrySmoothPick(), and EMono.world.
GetFelmeraRewardIndex()
int DramaOutcome.GetFelmeraRewardIndex () inline
Definition at line 469 of file DramaOutcome.cs.
    {
        int count = EMono.player.sketches.Count;
        int num = count / 10;
        if (num >= 29)
        {
            num = 29;
        }
        Debug.Log(count + "/" + num + "/" + EMono.player.lastFelmeraReward);
        return num;
    }
References Debug, Player.lastFelmeraReward, EMono.player, and Player.sketches.
Referenced by check_sketch2(), give_sketch_reward(), and ListFelmeraBarter().
give_sketch_reward()
void DramaOutcome.give_sketch_reward () inline
Definition at line 499 of file DramaOutcome.cs.
    {
        int felmeraRewardIndex = GetFelmeraRewardIndex();
        for (int i = EMono.player.lastFelmeraReward; i < felmeraRewardIndex; i++)
        {
            Thing thing = ThingGen.Create("painting_reward");
            thing.idSkin = i;
            EMono.player.DropReward(thing);
        }
        EMono.player.lastFelmeraReward = felmeraRewardIndex;
    }
References ThingGen.Create(), Player.DropReward(), GetFelmeraRewardIndex(), Player.lastFelmeraReward, and EMono.player.
give_sketch_special()
void DramaOutcome.give_sketch_special () inline
Definition at line 511 of file DramaOutcome.cs.
    {
        foreach (int key in EMono.core.refs.dictSketches.Keys)
        {
            if (key >= 500 && key < 700)
            {
                EMono.player.sketches.Add(key);
            }
        }
        Msg.Say("add_sketch_special");
        SE.WriteJournal();
        EMono.pc.things.Find("sketch_special").Destroy();
    }
References EMono.core, Card.Destroy(), CoreRef.dictSketches, ThingContainer.Find(), UDictionary< TKey, TValue >.Keys, EMono.pc, EMono.player, Core.refs, Msg.Say(), Player.sketches, and Card.things.
guild_join()
void DramaOutcome.guild_join () inline
Definition at line 413 of file DramaOutcome.cs.
    {
        if (Guild.CurrentDrama != EMono.game.factions.Merchant)
        {
            (cc.trait as TraitGuildDoorman).OnJoinGuild();
        }
        Msg.Say("guild_join", Guild.CurrentDrama.Name);
        SE.Play("questComplete");
        Guild.CurrentDrama.relation.type = FactionRelation.RelationType.Member;
        Guild.CurrentDrama?.Quest.ChangePhase(10);
    }
References Quest.ChangePhase(), Guild.CurrentDrama, Game.factions, EMono.game, FactionManager.Merchant, Faction.Name, Guild.Quest, and Msg.Say().
guild_mageTrial()
void DramaOutcome.guild_mageTrial () inline
Definition at line 425 of file DramaOutcome.cs.
    {
        Guild.CurrentQuest.NextPhase();
        EMono.pc.things.Find("letter_trial")?.ModNum(-1);
    }
References Guild.CurrentQuest, ThingContainer.Find(), Card.ModNum(), Quest.NextPhase(), EMono.pc, and Card.things.
guild_promote()
void DramaOutcome.guild_promote () inline
Definition at line 431 of file DramaOutcome.cs.
    {
        Guild.CurrentDrama.relation.Promote();
        Guild.GetCurrentGuild()?.RefreshDevelopment();
    }
References Guild.CurrentDrama, Guild.GetCurrentGuild(), FactionRelation.Promote(), Guild.RefreshDevelopment(), and Faction.relation.
guild_trial()
void DramaOutcome.guild_trial () inline
Definition at line 401 of file DramaOutcome.cs.
    {
        if (Guild.CurrentDrama == EMono.game.factions.Merchant)
        {
            EMono.game.quests.Start("guild_merchant", cc, assignQuest: false);
        }
        else
        {
            (cc.trait as TraitGuildDoorman).GiveTrial();
        }
    }
References cc, Guild.CurrentDrama, Game.factions, EMono.game, FactionManager.Merchant, Game.quests, and QuestManager.Start().
If()
static bool DramaOutcome.If (DramaChoice item, Chara c) inline static
Definition at line 395 of file DramaOutcome.cs.
    {
        _ = item.IF.Split('/')[0] == "costHire";
        return true;
    }
References item.
Referenced by DramaActor.SetChoice().
ListFelmeraBarter()
List< Thing > DramaOutcome.ListFelmeraBarter () inline
Definition at line 486 of file DramaOutcome.cs.
    {
        List<Thing> list = new List<Thing>();
        int felmeraRewardIndex = GetFelmeraRewardIndex();
        for (int i = 0; i < felmeraRewardIndex; i++)
        {
            Thing thing = ThingGen.Create("painting_reward");
            thing.idSkin = i;
            list.Add(thing);
        }
        return list;
    }
References Card.Add(), ThingGen.Create(), and GetFelmeraRewardIndex().
melilith_friend()
void DramaOutcome.melilith_friend () inline
Definition at line 332 of file DramaOutcome.cs.
    {
        if (cc.id == "melilith" && EMono.game.quests.completedIDs.Contains("melilith"))
        {
            cc.MakeAlly();
        }
    }
References cc, QuestManager.completedIDs, EMono.game, Card.id, Chara.MakeAlly(), and Game.quests.
nasu_join()
void DramaOutcome.nasu_join () inline
Definition at line 324 of file DramaOutcome.cs.
    {
        if (cc.id == "fairy_nanasu")
        {
            cc.MakeAlly();
        }
    }
References cc, Card.id, and Chara.MakeAlly().
nerun_gift()
void DramaOutcome.nerun_gift () inline
Definition at line 212 of file DramaOutcome.cs.
    {
        Dialog.Gift("", true, ThingGen.Create("rp1"));
    }
References ThingGen.Create(), and Dialog.Gift().
nerun_gift2()
void DramaOutcome.nerun_gift2 () inline
Definition at line 217 of file DramaOutcome.cs.
    {
        Dialog.Gift("", true, ThingGen.Create("rp1"));
    }
References ThingGen.Create(), and Dialog.Gift().
nerun_gift3()
void DramaOutcome.nerun_gift3 () inline
Definition at line 222 of file DramaOutcome.cs.
    {
        List<Card> list = new List<Card>();
        list.Add(ThingGen.Create("rp1"));
        list.Add(ThingGen.Create("rp2"));
        list.Add(ThingGen.Create("rp3"));
        list.Add(ThingGen.Create("rp4"));
        list.Add(ThingGen.Create("rp5"));
        Dialog.Gift("", autoAdd: true, list);
    }
References ThingGen.Create(), and Dialog.Gift().
OnClaimLand()
void DramaOutcome.OnClaimLand () inline
Definition at line 47 of file DramaOutcome.cs.
    {
        Chara c = EMono.game.cards.globalCharas.Find("ashland");
        EMono.game.quests.globalList.Add(Quest.Create("sharedContainer").SetClient(c, assignQuest: false));
        EMono.game.quests.globalList.Add(Quest.Create("crafter").SetClient(c, assignQuest: false));
        EMono.game.quests.globalList.Add(Quest.Create("defense").SetClient(c, assignQuest: false));
        EMono.game.quests.Get<QuestHome>().ChangePhase(2);
        AddMaid();
    }
References AddMaid(), Game.cards, Quest.Create(), CardManager.GlobalCharaList.Find(), EMono.game, QuestManager.Get(), CardManager.globalCharas, QuestManager.globalList, Game.quests, and Quest.SetClient().
poppy_found()
void DramaOutcome.poppy_found () inline
Definition at line 378 of file DramaOutcome.cs.
    {
        if (cc.id == "poppy")
        {
            cc.MakeAlly();
        }
        EMono.game.quests.Get("puppy").NextPhase();
        Msg.Say("npc_rescue", cc);
        cc.RemoveEditorTag(EditorTag.InvulnerableToMobs);
        cc.RemoveEditorTag(EditorTag.Invulnerable);
    }
References cc, EMono.game, QuestManager.Get(), Card.id, Chara.MakeAlly(), Quest.NextPhase(), Game.quests, Card.RemoveEditorTag(), and Msg.Say().
PutOutFire()
void DramaOutcome.PutOutFire () inline
Definition at line 39 of file DramaOutcome.cs.
    {
        foreach (Card item in EMono._map.props.installed.traits.GetTraitSet<TraitHearth>())
        {
            EMono._zone.AddCard(ThingGen.Create("dish_soup"), item.pos.GetRandomNeighbor());
        }
    }
References EMono._map, EMono._zone, Zone.AddCard(), ThingGen.Create(), TraitManager.GetTraitSet(), PropsManager.installed, item, Map.props, and Props.traits.
QuestCraft_Drop1()
void DramaOutcome.QuestCraft_Drop1 () inline
Definition at line 141 of file DramaOutcome.cs.
    {
        EMono.player.DropReward(ThingGen.CreateRawMaterial(EMono.sources.materials.alias["straw"]));
    }
References ThingGen.CreateRawMaterial(), Player.DropReward(), SourceManager.materials, EMono.player, and EMono.sources.
QuestDebt_reward()
void DramaOutcome.QuestDebt_reward () inline
Definition at line 175 of file DramaOutcome.cs.
    {
        EMono.game.quests.Get<QuestDebt>().GiveReward();
    }
References EMono.game, QuestManager.Get(), and Game.quests.
QuestDefense_0()
void DramaOutcome.QuestDefense_0 () inline
Definition at line 146 of file DramaOutcome.cs.
    {
        Prologue prologue = EMono.game.Prologue;
        Chara chara = EMono._zone.AddChara("punk", prologue.posPunk.x, prologue.posPunk.y);
        chara.things.DestroyAll();
        (EMono._zone.AddThing("gallows", prologue.posPunk.x, prologue.posPunk.y).Install().trait as TraitShackle).Restrain(chara);
        CardBlueprint.SetNormalRarity();
    }
References EMono._zone, Zone.AddChara(), Zone.AddThing(), ThingContainer.DestroyAll(), EMono.game, Card.Install(), Prologue.posPunk, Game.Prologue, CardBlueprint.SetNormalRarity(), Card.things, and Card.trait.
QuestDefense_1()
void DramaOutcome.QuestDefense_1 () inline
Definition at line 160 of file DramaOutcome.cs.
    {
        Prologue prologue = EMono.game.Prologue;
        Chara tc = EMono._zone.AddChara("boar", prologue.posPunk.x + 1, prologue.posPunk.y);
        (EMono._zone.AddThing("gallows", prologue.posPunk.x + 1, prologue.posPunk.y).Install().trait as TraitShackle).Restrain(tc);
        EMono.player.DropReward(ThingGen.Create("stone").SetNum(20));
        EMono.player.DropReward(ThingGen.Create("330").SetNum(3), silent: true).Identify(show: false);
        EMono.player.DropReward(ThingGen.Create("331").SetNum(3), silent: true).Identify(show: false);
        EMono.player.DropReward(ThingGen.Create("bandage").SetNum(5));
    }
References EMono._zone, Zone.AddChara(), Zone.AddThing(), ThingGen.Create(), Player.DropReward(), EMono.game, Identify, Card.Install(), EMono.player, Prologue.posPunk, Game.Prologue, Card.SetNum(), and Card.trait.
QuestDefense_2()
void DramaOutcome.QuestDefense_2 () inline
Definition at line 171 of file DramaOutcome.cs.
    {
    }
QuestExploration_AfterComplete()
void DramaOutcome.QuestExploration_AfterComplete () inline
Definition at line 126 of file DramaOutcome.cs.
    {
        Chara chara = EMono.game.cards.globalCharas.Find("ashland");
        chara.MoveHome("lothria", 40, 49);
        EMono.game.quests.RemoveAll(chara);
        chara = EMono.game.cards.globalCharas.Find("fiama");
        chara.MoveHome("lothria", 46, 56);
        EMono.game.quests.RemoveAll(chara);
        if (EMono.game.quests.Main == null)
        {
            EMono.game.quests.Start("main");
        }
        EMono.game.quests.Main.ChangePhase(700);
    }
References Game.cards, Quest.ChangePhase(), CardManager.GlobalCharaList.Find(), EMono.game, CardManager.globalCharas, QuestManager.Main, Chara.MoveHome(), Game.quests, QuestManager.RemoveAll(), and QuestManager.Start().
QuestExploration_AfterCrystal()
void DramaOutcome.QuestExploration_AfterCrystal () inline
Definition at line 112 of file DramaOutcome.cs.
    {
        Quest quest = EMono.game.quests.Get<QuestExploration>();
        if (quest == null)
        {
            quest = EMono.game.quests.Start("exploration", EMono.game.cards.globalCharas.Find("ashland"), assignQuest: false);
        }
        quest.ChangePhase(5);
        Chara chara = EMono.game.cards.globalCharas.Find("fiama");
        EMono._zone.AddCard(ThingGen.CreateScroll(8220).Identify(show: false), chara.pos);
        chara.MoveZone(EMono.game.StartZone);
        chara.RemoveEditorTag(EditorTag.AINoMove);
    }
References EMono._zone, Zone.AddCard(), Game.cards, Quest.ChangePhase(), ThingGen.CreateScroll(), CardManager.GlobalCharaList.Find(), EMono.game, QuestManager.Get(), CardManager.globalCharas, Thing.Identify(), Chara.MoveZone(), Card.pos, Game.quests, Card.RemoveEditorTag(), QuestManager.Start(), and Game.StartZone.
QuestExploration_Drop1()
void DramaOutcome.QuestExploration_Drop1 () inline
Definition at line 81 of file DramaOutcome.cs.
    {
        EMono.player.DropReward(ThingGen.CreateScroll(8220), silent: true).c_IDTState = 0;
        EMono.player.DropReward(ThingGen.CreateScroll(8221)).c_IDTState = 0;
    }
References Card.c_IDTState, ThingGen.CreateScroll(), Player.DropReward(), and EMono.player.
QuestExploration_MeetFarris()
void DramaOutcome.QuestExploration_MeetFarris () inline
Definition at line 87 of file DramaOutcome.cs.
    {
        EMono.game.quests.Get<QuestExploration>().ChangePhase(1);
        cc.RemoveEditorTag(EditorTag.AINoMove);
        cc.RemoveEditorTag(EditorTag.InvulnerableToMobs);
        cc.RemoveEditorTag(EditorTag.Invulnerable);
        cc.homeZone = EMono.game.StartZone;
        cc.MoveZone(EMono.game.StartZone, ZoneTransition.EnterState.Return);
    }
References cc, EMono.game, QuestManager.Get(), Chara.MoveZone(), Game.quests, Card.RemoveEditorTag(), and Game.StartZone.
QuestExploration_MeetFarris2()
void DramaOutcome.QuestExploration_MeetFarris2 () inline
Definition at line 97 of file DramaOutcome.cs.
    {
        EMono.game.quests.Get<QuestExploration>().ChangePhase(2);
        if (EMono.Branch == null)
        {
            EMono._zone.ClaimZone();
        }
        EMono.Branch.Recruit(cc);
        if (EMono.game.quests.Main == null)
        {
            EMono.game.quests.Start("main");
        }
        EMono.game.quests.Main.ChangePhase(300);
    }
References EMono._zone, EMono.Branch, cc, Quest.ChangePhase(), Zone.ClaimZone(), EMono.game, QuestManager.Get(), QuestManager.Main, Game.quests, FactionBranch.Recruit(), and QuestManager.Start().
QuestSharedContainer_Drop1()
void DramaOutcome.QuestSharedContainer_Drop1 () inline
Definition at line 71 of file DramaOutcome.cs.
    {
        EMono.player.DropReward(ThingGen.Create("chest6"));
    }
References ThingGen.Create(), Player.DropReward(), and EMono.player.
QuestShippingChest_Drop1()
void DramaOutcome.QuestShippingChest_Drop1 () inline
Definition at line 76 of file DramaOutcome.cs.
    {
        Recipe.DropIngredients("container_shipping", "palm", 6);
    }
References Recipe.DropIngredients().
QuestVernis_DropRecipe()
void DramaOutcome.QuestVernis_DropRecipe () inline
Definition at line 155 of file DramaOutcome.cs.
    {
        EMono.player.DropReward(ThingGen.CreateRecipe("explosive"));
    }
References ThingGen.CreateRecipe(), Player.DropReward(), and EMono.player.
revive_pet()
void DramaOutcome.revive_pet () inline
Definition at line 312 of file DramaOutcome.cs.
    {
        foreach (Chara member in EMono.pc.homeBranch.members)
        {
            if (member.isDead && member.GetInt(100) != 0)
            {
                member.GetRevived();
            }
        }
        cc.ModAffinity(EMono.pc, -2);
    }
References cc, BaseCard.GetInt(), Chara.GetRevived(), Chara.homeBranch, Chara.isDead, FactionBranch.members, Chara.ModAffinity(), and EMono.pc.
sister_change()
void DramaOutcome.sister_change () inline
Definition at line 350 of file DramaOutcome.cs.
    {
        cc.idSkin = ((cc.idSkin != 1) ? 1 : 2);
    }
sister_friend()
void DramaOutcome.sister_friend () inline
Definition at line 340 of file DramaOutcome.cs.
    {
        if (cc.id == "olderyoungersister")
        {
            cc.MakeAlly();
        }
        EMono.pc.ModCurrency(-10000);
        cc.Say("hug", cc, EMono.pc);
    }
References cc, Card.id, Chara.MakeAlly(), Card.ModCurrency(), EMono.pc, and Card.Say().
StartNewGame()
void DramaOutcome.StartNewGame () inline
Definition at line 16 of file DramaOutcome.cs.
    {
        if ((bool)LayerTitle.actor)
        {
            EMono.game.StartNewGame();
        }
    }
References LayerTitle.actor, EMono.game, and Game.StartNewGame().
StartNewGame2()
void DramaOutcome.StartNewGame2 () inline
Definition at line 24 of file DramaOutcome.cs.
    {
        if ((bool)LayerTitle.actor)
        {
            EMono.core.actionsNextFrame.Add(LayerTitle.KillActor);
            EMono.pc.MoveZone(EMono.game.Prologue.idStartZone);
            EMono.pc.global.transition = new ZoneTransition
            {
                state = ZoneTransition.EnterState.Exact,
                x = EMono.game.Prologue.startX,
                z = EMono.game.Prologue.startZ
            };
        }
    }
References BaseCore.actionsNextFrame, LayerTitle.actor, EMono.core, EMono.game, Prologue.idStartZone, LayerTitle.KillActor(), Chara.MoveZone(), EMono.pc, Game.Prologue, and Prologue.startX.
Tutorial1()
void DramaOutcome.Tutorial1 () inline
Definition at line 180 of file DramaOutcome.cs.
    {
        Thing t = ThingGen.Create("log");
        Point point = new Point(53, 52);
        EMono._zone.AddCard(t, point).SetPlaceState(PlaceState.installed);
        t = ThingGen.Create("crimAle");
        EMono._zone.AddCard(t, point).SetPlaceState(PlaceState.installed);
    }
References EMono._zone, Zone.AddCard(), ThingGen.Create(), and Card.SetPlaceState().
WelcomeMsg()
void DramaOutcome.WelcomeMsg () inline
Definition at line 189 of file DramaOutcome.cs.
    {
    }
Member Data Documentation
idJump
string DramaOutcome.idJump static
Definition at line 6 of file DramaOutcome.cs.
manager
DramaManager DramaOutcome.manager
Definition at line 8 of file DramaOutcome.cs.
Property Documentation
cc
Chara DramaOutcome.cc get
Definition at line 14 of file DramaOutcome.cs.
Referenced by chara_hired(), chara_hired_ticket(), fiama_starter_gift(), guild_trial(), melilith_friend(), nasu_join(), poppy_found(), QuestExploration_MeetFarris(), QuestExploration_MeetFarris2(), revive_pet(), and sister_friend().
sequence
DramaSequence DramaOutcome.sequence get
Definition at line 10 of file DramaOutcome.cs.
tg
Person DramaOutcome.tg get
Definition at line 12 of file DramaOutcome.cs.
The documentation for this class was generated from the following file:
Elin/DramaOutcome.cs