Elin Decompiled Documentation: ZoneEventQuest Class Reference
ZoneEventQuest Class Reference
Public Member Functions
void Spawn (int num=1)
void SpawnBoss (bool evolve=false)
void AggroEnemy (int chance=100)
sealed override void OnTickRound ()
virtual void _OnTickRound ()
virtual ZoneInstance.Status OnReachTimeLimit ()
Public Member Functions inherited from ZoneEvent
virtual string GetText ()
void Tick (float delta)
void Init ()
void OnSimulateHour ()
virtual void OnVisit ()
virtual void OnInit ()
virtual void OnFirstTick ()
virtual void OnTick ()
virtual void OnTickRound ()
virtual void OnKill ()
virtual void OnCharaDie (Chara c)
virtual void OnLeaveZone ()
virtual void OnLoad ()
void Kill ()
Public Attributes
int uidQuest
List< int > enemies = new List<int>()
Public Attributes inherited from ZoneEvent
float time
int rounds
int hoursElapsed
int minElapsed
Zone zone
bool firstTick = true
Properties
Quest quest [get]
virtual bool WarnBoss [get]
virtual bool CountEnemy [get]
virtual int TimeLimit [get]
Properties inherited from ZoneEvent
SourceQuest.Row source [get]
virtual string id [get]
virtual string TextWidgetDate [get]
virtual float roundInterval [get]
virtual Playlist playlist [get]
virtual bool debugSkip [get]
virtual string RefStr2 [get]
virtual string RefStr3 [get]
virtual int hoursToKill [get]
virtual bool HasReport [get]
string Name [get]
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Additional Inherited Members
Static Public Member Functions inherited from EClass
static int rndSeed (int a, int seed)
static int rnd (long a)
static int rnd (int a)
static int curve (int a, int start, int step, int rate=75)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Static Public Attributes inherited from EClass
static Core core
Detailed Description
Definition at line 4 of file ZoneEventQuest.cs.
Member Function Documentation
_OnTickRound()
virtual void ZoneEventQuest._OnTickRound () inline virtual
Reimplemented in ZoneEventDefenseGame, and ZoneEventSubdue.
Definition at line 77 of file ZoneEventQuest.cs.
    {
    }
Referenced by OnTickRound().
AggroEnemy()
void ZoneEventQuest.AggroEnemy (int chance = 100) inline
Definition at line 52 of file ZoneEventQuest.cs.
    {
        foreach (Chara chara in EClass._map.charas)
        {
            if (!chara.IsPCFactionOrMinion && !chara.IsInCombat && EClass.rnd(100) <= chance)
            {
                chara.SetEnemy(EClass.pc.party.members.RandomItem());
                chara.SetAIAggro();
            }
        }
    }
References EClass._map, Map.charas, Chara.IsInCombat, Card.IsPCFactionOrMinion, Party.members, Chara.party, EClass.pc, EClass.rnd(), Chara.SetAIAggro(), and Chara.SetEnemy().
Referenced by ZoneEventDefenseGame._OnTickRound(), ZoneEventSubdue._OnTickRound(), ZoneEventDefenseGame.NextWave(), and ZoneEventSubdue.OnVisit().
OnReachTimeLimit()
virtual ZoneInstance.Status ZoneEventQuest.OnReachTimeLimit () inline virtual
Reimplemented in ZoneEventHarvest, and ZoneEventMusic.
Definition at line 81 of file ZoneEventQuest.cs.
    {
        return ZoneInstance.Status.Running;
    }
Referenced by OnTickRound().
OnTickRound()
sealed override void ZoneEventQuest.OnTickRound () inline virtual
Reimplemented from ZoneEvent.
Definition at line 64 of file ZoneEventQuest.cs.
    {
        _OnTickRound();
        if (TimeLimit != -1 && minElapsed >= TimeLimit)
        {
            EClass._zone.instance.status = OnReachTimeLimit();
            EClass.game.Pause(delegate
            {
                EClass.pc.MoveZone(EClass._zone.parent as Zone);
            });
        }
    }
References _OnTickRound(), EClass._zone, EClass.game, ZoneEvent.minElapsed, Chara.MoveZone(), OnReachTimeLimit(), Spatial.parent, Game.Pause(), EClass.pc, and TimeLimit.
Spawn()
void ZoneEventQuest.Spawn (int num = 1) inline
Definition at line 20 of file ZoneEventQuest.cs.
    {
        for (int i = 0; i < num; i++)
        {
            Point nearestPoint = EClass._map.bounds.GetRandomEdge().GetNearestPoint(allowBlock: false, allowChara: false);
            Chara chara = EClass._zone.SpawnMob(nearestPoint, SpawnSetting.DefenseEnemy(EClass._zone.DangerLv));
            Hostility hostility2 = (chara.c_originalHostility = Hostility.Enemy);
            chara.hostility = hostility2;
            if (CountEnemy)
            {
                enemies.Add(chara.uid);
            }
        }
    }
References EClass._map, EClass._zone, Map.bounds, CountEnemy, Zone.DangerLv, SpawnSetting.DefenseEnemy(), enemies, Point.GetNearestPoint(), MapBounds.GetRandomEdge(), Zone.SpawnMob(), and Card.uid.
Referenced by ZoneEventDefenseGame._OnTickRound(), ZoneEventDefenseGame.NextWave(), and ZoneEventSubdue.OnVisit().
SpawnBoss()
void ZoneEventQuest.SpawnBoss (bool evolve = false) inline
Definition at line 35 of file ZoneEventQuest.cs.
    {
        Point nearestPoint = EClass._map.bounds.GetRandomEdge().GetNearestPoint(allowBlock: false, allowChara: false);
        Chara chara = (evolve ? EClass._zone.TryGenerateEvolved(force: true, nearestPoint) : EClass._zone.SpawnMob(nearestPoint, SpawnSetting.Boss(EClass._zone.DangerLv)));
        Hostility hostility2 = (chara.c_originalHostility = Hostility.Enemy);
        chara.hostility = hostility2;
        if (CountEnemy)
        {
            enemies.Add(chara.uid);
        }
        if (WarnBoss)
        {
            Msg.Say("defense_boss", chara.Name);
            EClass.game.Pause();
        }
    }
References EClass._map, EClass._zone, SpawnSetting.Boss(), Map.bounds, CountEnemy, Zone.DangerLv, enemies, EClass.game, Point.GetNearestPoint(), MapBounds.GetRandomEdge(), Card.Name, Game.Pause(), Msg.Say(), Zone.SpawnMob(), Zone.TryGenerateEvolved(), Card.uid, and WarnBoss.
Referenced by ZoneEventDefenseGame._OnTickRound().
Member Data Documentation
enemies
List<int> ZoneEventQuest.enemies = new List<int>()
Definition at line 10 of file ZoneEventQuest.cs.
Referenced by ZoneEventSubdue.CheckClear(), ZoneEventSubdue.OnVisit(), Spawn(), and SpawnBoss().
uidQuest
int ZoneEventQuest.uidQuest
Definition at line 7 of file ZoneEventQuest.cs.
Property Documentation
CountEnemy
virtual bool ZoneEventQuest.CountEnemy get
Definition at line 16 of file ZoneEventQuest.cs.
Referenced by Spawn(), and SpawnBoss().
quest
Quest ZoneEventQuest.quest get
Definition at line 12 of file ZoneEventQuest.cs.
TimeLimit
virtual int ZoneEventQuest.TimeLimit get
Definition at line 18 of file ZoneEventQuest.cs.
Referenced by OnTickRound().
WarnBoss
virtual bool ZoneEventQuest.WarnBoss get
Definition at line 14 of file ZoneEventQuest.cs.
Referenced by SpawnBoss().
The documentation for this class was generated from the following file:
Elin/ZoneEventQuest.cs