Elin Decompiled Documentation: EffectManager.EffectList Class Reference
EffectManager.EffectList Class Reference
Public Member Functions
Effect Get (string id)
Public Member Functions inherited from DynamicAsset< Effect >
DynamicAsset ()
DynamicAsset (string groupId, bool instantiate)
T GetNew (string id, Transform parent=null)
T GetOriginal (string id)
Additional Inherited Members
Public Attributes inherited from DynamicAsset< Effect >
string groupId
List< T > list
Dictionary< string, T > map
bool usePool
bool instantiate
Detailed Description
Definition at line 7 of file EffectManager.cs.
Member Function Documentation
Get()
Effect EffectManager.EffectList.Get (string id) inline
Definition at line 9 of file EffectManager.cs.
        {
            return GetNew(id);
        }
References DynamicAsset< Effect >.GetNew().
Referenced by Effect.Get(), and Effect.Get< T >().
The documentation for this class was generated from the following file:
Elin/EffectManager.cs