Elin Decompiled Documentation: Meeting Class Reference
Meeting Class Reference
Public Member Functions
void SetOwner (FactionBranch _branch)
void SetChara (Point pos)
void Start ()
virtual void PlayDrama ()
virtual void OnEndDrama ()
Public Attributes
int dateExipire
FactionBranch branch
Chara chara
Properties
virtual bool IsGlobalChara [get]
virtual string IdChara [get]
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Additional Inherited Members
Static Public Member Functions inherited from EClass
static int rnd (int a)
static int curve (int a, int start, int step, int rate=75)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Static Public Attributes inherited from EClass
static Core core
Detailed Description
Definition at line 5 of file Meeting.cs.
Member Function Documentation
OnEndDrama()
virtual void Meeting.OnEndDrama () inline virtual
Definition at line 64 of file Meeting.cs.
    {
        if (this.chara.IsGlobal)
        {
            this.chara.MoveZone(EClass.game.spatials.Find("somewhere"), ZoneTransition.EnterState.Auto);
        }
        else
        {
            this.chara.Destroy();
        }
        EClass.Branch.meetings.CallNext();
    }
References EClass.Branch, MeetingManager.CallNext(), chara, Card.Destroy(), SpatialManager.Find(), EClass.game, Chara.IsGlobal, FactionBranch.meetings, Chara.MoveZone(), and Game.spatials.
Referenced by Start().
PlayDrama()
virtual void Meeting.PlayDrama () inline virtual
Reimplemented in MeetingFarris, and MeetingMerchant.
Definition at line 60 of file Meeting.cs.
    {
    }
Referenced by Start().
SetChara()
void Meeting.SetChara (Point pos) inline
Definition at line 28 of file Meeting.cs.
    {
        if (this.IsGlobalChara)
        {
            this.chara = EClass.game.cards.globalCharas.Find(this.IdChara);
            if (this.chara == null)
            {
                Debug.Log("creating chara for meeting:" + this.IdChara);
                this.chara = CharaGen.Create(this.IdChara, -1);
                this.chara.SetGlobal();
                EClass.game.spatials.Find("somewhere").AddCard(this.chara);
            }
        }
        else
        {
            this.chara = EClass._zone.AddCard(CharaGen.Create(this.IdChara, -1), pos).Chara;
        }
        if (this.chara.currentZone != EClass.game.activeZone)
        {
            this.chara.MoveZone(EClass.game.activeZone, ZoneTransition.EnterState.Auto);
        }
        this.chara.MoveImmediate(pos, true, true);
    }
References EClass._zone, Game.activeZone, Zone.AddCard(), Game.cards, Card.Chara, chara, CharaGen.Create(), Chara.currentZone, CardManager.Find(), SpatialManager.Find(), EClass.game, CardManager.globalCharas, IdChara, IsGlobalChara, Card.MoveImmediate(), Chara.MoveZone(), Chara.SetGlobal(), and Game.spatials.
Referenced by MeetingManager.CallNext().
SetOwner()
void Meeting.SetOwner (FactionBranch _branch) inline
Definition at line 23 of file Meeting.cs.
    {
        this.branch = _branch;
    }
Referenced by MeetingManager.SetOwner().
Start()
void Meeting.Start () inline
Definition at line 52 of file Meeting.cs.
    {
        EClass.pc.LookAt(this.chara);
        this.chara.LookAt(EClass.pc);
        this.PlayDrama();
        LayerDrama.Instance.SetOnKill(new Action(this.OnEndDrama));
    }
References chara, LayerDrama.Instance, Chara.LookAt(), OnEndDrama(), EClass.pc, and PlayDrama().
Referenced by MeetingManager.CallNext().
Member Data Documentation
branch
FactionBranch Meeting.branch
Definition at line 80 of file Meeting.cs.
chara
Chara Meeting.chara
Definition at line 82 of file Meeting.cs.
Referenced by MeetingManager.CallNext(), OnEndDrama(), MeetingFarris.PlayDrama(), MeetingMerchant.PlayDrama(), SetChara(), and Start().
dateExipire
int Meeting.dateExipire
Definition at line 78 of file Meeting.cs.
Property Documentation
IdChara
virtual string Meeting.IdChara get
Definition at line 15 of file Meeting.cs.
    {
        get
        {
            return "begger";
        }
    }
Referenced by SetChara().
IsGlobalChara
virtual bool Meeting.IsGlobalChara get
Definition at line 7 of file Meeting.cs.
    {
        get
        {
            return false;
        }
    }
Referenced by SetChara().
The documentation for this class was generated from the following file:
Elin/Meeting.cs