Elin Decompiled Documentation: SourceRecipe Class Reference
SourceRecipe Class Reference
Classes
class Row
Public Member Functions
override Row CreateRow ()
override Row CreateRowByMapping (IReadOnlyDictionary< string, int > mapping)
override void SetRow (Row r)
override IReadOnlyDictionary< string, int > GetRowMapping ()
override IReadOnlyDictionary< string, string > GetTypeMapping ()
Public Member Functions inherited from SourceDataInt< SourceRecipe.Row >
override T GetRow (string id)
Static Public Attributes
static readonly IReadOnlyDictionary< string, int > RowMapping
static readonly IReadOnlyDictionary< string, string > TypeMapping
Detailed Description
Definition at line 4 of file SourceRecipe.cs.
Member Function Documentation
CreateRow()
override Row SourceRecipe.CreateRow () inline
Definition at line 72 of file SourceRecipe.cs.
    {
        return new Row
        {
            id = SourceData.GetInt(0),
            factory = SourceData.GetString(1),
            type = SourceData.GetString(2),
            thing = SourceData.GetString(3),
            num = SourceData.GetString(4),
            sp = SourceData.GetInt(5),
            time = SourceData.GetInt(6),
            ing1 = SourceData.GetStringArray(7),
            ing2 = SourceData.GetStringArray(8),
            ing3 = SourceData.GetStringArray(9),
            tag = SourceData.GetStringArray(10)
        };
    }
References SourceData< T, T2 >.GetInt(), SourceData< T, T2 >.GetString(), and SourceData< T, T2 >.GetStringArray().
CreateRowByMapping()
override Row SourceRecipe.CreateRowByMapping (IReadOnlyDictionary< string, int > mapping) inline
Definition at line 90 of file SourceRecipe.cs.
    {
        return new Row
        {
            id = SourceData.GetInt(mapping["id"]),
            factory = SourceData.GetString(mapping["factory"]),
            type = SourceData.GetString(mapping["type"]),
            thing = SourceData.GetString(mapping["thing"]),
            num = SourceData.GetString(mapping["num"]),
            sp = SourceData.GetInt(mapping["sp"]),
            time = SourceData.GetInt(mapping["time"]),
            ing1 = SourceData.GetStringArray(mapping["ing1"]),
            ing2 = SourceData.GetStringArray(mapping["ing2"]),
            ing3 = SourceData.GetStringArray(mapping["ing3"]),
            tag = SourceData.GetStringArray(mapping["tag"])
        };
    }
References SourceData< T, T2 >.GetInt(), SourceData< T, T2 >.GetString(), and SourceData< T, T2 >.GetStringArray().
GetRowMapping()
override IReadOnlyDictionary< string, int > SourceRecipe.GetRowMapping () inline
Definition at line 113 of file SourceRecipe.cs.
    {
        return RowMapping;
    }
References RowMapping.
GetTypeMapping()
override IReadOnlyDictionary< string, string > SourceRecipe.GetTypeMapping () inline
Definition at line 118 of file SourceRecipe.cs.
    {
        return TypeMapping;
    }
References TypeMapping.
SetRow()
override void SourceRecipe.SetRow (Row r) inline
Definition at line 108 of file SourceRecipe.cs.
    {
        map[r.id] = r;
    }
References SourceRecipe.Row.id.
Member Data Documentation
RowMapping
readonly IReadOnlyDictionary<string, int> SourceRecipe.RowMapping static
Initial value:
= new Dictionary<string, int>
    {
        ["id"] = 0,
        ["factory"] = 1,
        ["type"] = 2,
        ["thing"] = 3,
        ["num"] = 4,
        ["sp"] = 5,
        ["time"] = 6,
        ["ing1"] = 7,
        ["ing2"] = 8,
        ["ing3"] = 9,
        ["tag"] = 10
    }
Definition at line 42 of file SourceRecipe.cs.
Referenced by GetRowMapping().
TypeMapping
readonly IReadOnlyDictionary<string, string> SourceRecipe.TypeMapping static
Initial value:
= new Dictionary<string, string>
    {
        ["id"] = "int",
        ["factory"] = "string",
        ["type"] = "string",
        ["thing"] = "string",
        ["num"] = "string",
        ["sp"] = "int",
        ["time"] = "int",
        ["ing1"] = "string[]",
        ["ing2"] = "string[]",
        ["ing3"] = "string[]",
        ["tag"] = "string[]"
    }
Definition at line 57 of file SourceRecipe.cs.
Referenced by GetTypeMapping().
The documentation for this class was generated from the following file:
Elin/SourceRecipe.cs