Elin Decompiled Documentation: LayerInfo Class Reference
LayerInfo Class Reference
Public Member Functions
override void OnAfterInit ()
void SetElement (Element e)
void Set (object o, bool _examine=false)
void Resize ()
void SetThing (Thing t, bool _examine=false)
void SetBlock (Cell cell)
void SetFloor (Cell cell)
void SetLiquid (Cell cell)
void SetZone (Zone z)
void SetObj (Cell cell)
override void OnKill ()
override void OnUpdateInput ()
Public Member Functions inherited from ELayer
override void OnBeforeAddLayer ()
void InitInspector ()
sealed override void Init ()
override void OnAfterAddLayer ()
void TryShowHelp ()
void AddLayerToUI (string id)
void TryShowHint (string _langHint=null)
void TalkHomeMemeber (string id)
void TalkMaid (string id)
override void OnRightClick ()
Public Member Functions inherited from Layer
virtual string GetTextHeader (Window window)
virtual bool HeaderIsListOf (int id)
virtual void Init ()
virtual void OnInit ()
virtual void OnAfterInit ()
virtual void ApplySkin ()
void ShowScreenLock (string id)
void UpdateInput ()
virtual void OnUpdateInput ()
virtual void OnRightClick ()
virtual bool OnBack ()
virtual void OnChangeLayer ()
virtual void OnCreate ()
void _AddLayer (string id)
Layer AddLayer (string id)
T AddLayer< T > ()
T AddLayer< T > (string id)
T AddLayerDontCloseOthers< T > ()
Layer AddLayerDontCloseOthers (Layer l)
T GetOrAddLayer< T > ()
virtual void OnBeforeAddLayer ()
virtual void OnAfterAddLayer ()
Layer AddLayer (Layer l)
void ToggleLayer (string id)
T ToggleLayer< T > (string id=null)
void WaitAndClose ()
void OnClickClose ()
virtual void Close ()
void CloseLayers ()
void RemoveLayers (bool removeImportant=false)
bool RemoveLayer< T > ()
void RemoveLayer (Layer l)
virtual void OnKill ()
Layer SetOnKill (Action action)
void DisableClose ()
void Delay (float duration=0.05f)
Layer SetDelay (float d)
Layer GetLayer (string id)
T GetLayer< T > (bool fromTop=false)
Layer GetTopLayer ()
void SwitchContent (int idWindow, int i)
virtual void OnSwitchContent (Window window)
Layer SetTitles (string langList, string idHeaderRow=null)
bool IsBlockWidgetClick ()
bool IsHideHud ()
bool IsAllowGeneralInput ()
bool IsUseBlur ()
bool IsPointerOnLayer ()
void ApplySkin ()
Public Attributes
UICardInfo info
UINote note
bool examine
Vector2 size
Vector2 padding
Public Attributes inherited from Layer
Option option
UnityEvent onKill
Anime animeIn
Anime animeOut
bool closeOthers
bool defaultActionMode = true
Button screenLock
Layer parent
string idLayer
List< Layer > layers = new List<Layer>()
Vector2 lastParentPos
List< Window > windows = new List<Window>()
string langHint
Additional Inherited Members
Static Public Member Functions inherited from ELayer
static int rnd (int a)
Static Public Member Functions inherited from Layer
static T Create< T > ()
static T Create< T > (string path)
static Layer Create (string path)
Static Public Attributes inherited from Layer
static int skipInput
static bool closeOnRightClick
static bool rightClicked
static bool cancelKeyDown
static bool ignoreSounds
static Transform blurStopInstance
static string[] searchPath = new string[3] { "Layer", "Layer/Dialog", "Layer/LayerHome" }
Protected Member Functions inherited from ELayer
sealed override void _Close ()
sealed override void Kill ()
Protected Member Functions inherited from Layer
virtual void Awake ()
virtual void _Close ()
virtual void Kill ()
Protected Attributes inherited from Layer
RectTransform _rect
bool isDestroyed
Properties inherited from ELayer
static Core core [get]
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static FactionBranch Branch [get]
static Faction Home [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static CoreConfig config [get]
static GameSetting setting [get]
static ColorProfile Colors [get]
static SourceManager sources [get]
static World world [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
bool IsFloat [get]
virtual string IdHelp [get]
Properties inherited from Layer
Layer TopLayer [get]
string uid [get]
virtual RectTransform rectLayers [get]
virtual bool blockWidgetClick [get]
Detailed Description
Definition at line 3 of file LayerInfo.cs.
Member Function Documentation
OnAfterInit()
override void LayerInfo.OnAfterInit () inline virtual
Reimplemented from Layer.
Definition at line 15 of file LayerInfo.cs.
    {
        base.OnAfterInit();
        TooltipManager.Instance.HideTooltips(immediate: true);
    }
References TooltipManager.HideTooltips(), and TooltipManager.Instance.
OnKill()
override void LayerInfo.OnKill () inline virtual
Reimplemented from Layer.
Definition at line 85 of file LayerInfo.cs.
    {
        base.OnKill();
        TweenUtil.Tween(0.2f, delegate
        {
            UIButton.TryShowTip<UIButton>();
        });
    }
References UIButton.TryShowTip().
OnUpdateInput()
override void LayerInfo.OnUpdateInput () inline virtual
Reimplemented from Layer.
Definition at line 94 of file LayerInfo.cs.
    {
        base.OnUpdateInput();
        if (examine && ELayer.core.config.input.altExamine)
        {
            if (!Input.GetKey(EInput.keys.examine.key))
            {
                Close();
            }
        }
        else if (Input.GetKeyDown(EInput.keys.examine.key))
        {
            Close();
        }
    }
References CoreConfig.InputSetting.altExamine, Layer.Close(), Core.config, ELayer.core, examine, EInput.KeyMapManager.examine, CoreConfig.input, EInput.KeyMap.key, and EInput.keys.
Resize()
void LayerInfo.Resize () inline
Definition at line 35 of file LayerInfo.cs.
    {
        windows[0].Rect().sizeDelta = new Vector2(Mathf.Max(info.Rect().sizeDelta.x + padding.x, size.x), size.y);
    }
References info, padding, size, and Layer.windows.
Referenced by SetBlock(), SetFloor(), SetLiquid(), SetObj(), SetThing(), and SetZone().
Set()
void LayerInfo.Set (object o, bool _examine = false) inline
Definition at line 27 of file LayerInfo.cs.
    {
        if (o is Thing)
        {
            SetThing(o as Thing, _examine);
        }
    }
References SetThing().
SetBlock()
void LayerInfo.SetBlock (Cell cell) inline
Definition at line 48 of file LayerInfo.cs.
    {
        windows[0].SetCaption(cell.GetBlockName());
        info.SetBlock(cell);
        Resize();
    }
References Cell.GetBlockName(), info, Resize(), UICardInfo.SetBlock(), and Layer.windows.
SetElement()
void LayerInfo.SetElement (Element e) inline
Definition at line 21 of file LayerInfo.cs.
    {
        windows[0].SetCaption(e.Name);
        info.SetElement(e);
    }
References info, Element.Name, UICardInfo.SetElement(), and Layer.windows.
SetFloor()
void LayerInfo.SetFloor (Cell cell) inline
Definition at line 55 of file LayerInfo.cs.
    {
        windows[0].SetCaption(cell.GetFloorName());
        info.SetFloor(cell);
        Resize();
    }
References Cell.GetFloorName(), info, Resize(), UICardInfo.SetFloor(), and Layer.windows.
SetLiquid()
void LayerInfo.SetLiquid (Cell cell) inline
Definition at line 62 of file LayerInfo.cs.
    {
        windows[0].SetCaption(cell.GetLiquidName());
        info.SetLiquid(cell);
        Resize();
    }
References Cell.GetLiquidName(), info, Resize(), UICardInfo.SetLiquid(), and Layer.windows.
SetObj()
void LayerInfo.SetObj (Cell cell) inline
Definition at line 78 of file LayerInfo.cs.
    {
        windows[0].SetCaption(cell.sourceObj.GetName());
        info.SetObj(cell);
        Resize();
    }
References SourceObj.GetName(), info, Resize(), UICardInfo.SetObj(), Cell.sourceObj, and Layer.windows.
SetThing()
void LayerInfo.SetThing (Thing t, bool _examine = false) inline
Definition at line 40 of file LayerInfo.cs.
    {
        examine = _examine;
        windows[0].SetCaption(t.NameSimple.ToTitleCase());
        info.SetThing(t);
        Resize();
    }
References examine, info, Card.NameSimple, Resize(), UICardInfo.SetThing(), and Layer.windows.
Referenced by Set().
SetZone()
void LayerInfo.SetZone (Zone z) inline
Definition at line 69 of file LayerInfo.cs.
    {
        note.Clear();
        note.AddHeader(z.Name);
        note.AddText(z.source.GetDetail());
        note.Build();
        Resize();
    }
References UINote.AddHeader(), UINote.AddText(), UINote.Build(), UINote.Clear(), Spatial.Name, note, Resize(), and Spatial.source.
Member Data Documentation
examine
bool LayerInfo.examine
Definition at line 9 of file LayerInfo.cs.
Referenced by OnUpdateInput(), and SetThing().
info
UICardInfo LayerInfo.info
Definition at line 5 of file LayerInfo.cs.
Referenced by Resize(), SetBlock(), SetElement(), SetFloor(), SetLiquid(), SetObj(), and SetThing().
note
UINote LayerInfo.note
Definition at line 7 of file LayerInfo.cs.
Referenced by SetZone().
padding
Vector2 LayerInfo.padding
Definition at line 13 of file LayerInfo.cs.
Referenced by Resize().
size
Vector2 LayerInfo.size
Definition at line 11 of file LayerInfo.cs.
Referenced by Resize().
The documentation for this class was generated from the following file:
Elin/LayerInfo.cs