Elin Decompiled Documentation: LayerPickPCC Class Reference
LayerPickPCC Class Reference
Public Member Functions
void Activate (UIPCC uiPcc, UIItemPCC uiItemPcc)
void PopulateButtons ()
Public Member Functions inherited from ELayer
override void OnBeforeAddLayer ()
void InitInspector ()
sealed override void Init ()
override void OnAfterAddLayer ()
void TryShowHelp ()
void AddLayerToUI (string id)
void TryShowHint (string _langHint=null)
void TalkHomeMemeber (string id)
void TalkMaid (string id)
override void OnRightClick ()
Public Member Functions inherited from Layer
virtual string GetTextHeader (Window window)
virtual bool HeaderIsListOf (int id)
virtual void Init ()
virtual void OnInit ()
virtual void OnAfterInit ()
virtual void ApplySkin ()
void ShowScreenLock (string id)
void UpdateInput ()
virtual void OnUpdateInput ()
virtual void OnRightClick ()
virtual bool OnBack ()
virtual void OnChangeLayer ()
virtual void OnCreate ()
void _AddLayer (string id)
Layer AddLayer (string id)
T AddLayer< T > ()
T AddLayer< T > (string id)
T AddLayerDontCloseOthers< T > ()
Layer AddLayerDontCloseOthers (Layer l)
T GetOrAddLayer< T > ()
virtual void OnBeforeAddLayer ()
virtual void OnAfterAddLayer ()
Layer AddLayer (Layer l)
void ToggleLayer (string id)
T ToggleLayer< T > (string id=null)
void WaitAndClose ()
void OnClickClose ()
virtual void Close ()
void CloseLayers ()
void RemoveLayers (bool removeImportant=false)
bool RemoveLayer< T > ()
void RemoveLayer (Layer l)
virtual void OnKill ()
Layer SetOnKill (Action action)
void DisableClose ()
void Delay (float duration=0.05f)
Layer SetDelay (float d)
Layer GetLayer (string id)
T GetLayer< T > (bool fromTop=false)
Layer GetTopLayer ()
void SwitchContent (int idWindow, int i)
virtual void OnSwitchContent (Window window)
Layer SetTitles (string langList, string idHeaderRow=null)
bool IsBlockWidgetClick ()
bool IsHideHud ()
bool IsAllowGeneralInput ()
bool IsUseBlur ()
bool IsPointerOnLayer ()
void ApplySkin ()
Static Public Member Functions
static string GetPartProviderString (PCC.Part part)
static BaseModPackage GetPartProvider (PCC.Part part)
static int PartSorter (PCC.Part lhs, PCC.Part rhs)
Static Public Member Functions inherited from ELayer
static int rnd (int a)
Static Public Member Functions inherited from Layer
static T Create< T > ()
static T Create< T > (string path)
static Layer Create (string path)
Public Attributes
UIItemPCCPart mold
LayoutGroup layoutParts
Public Attributes inherited from Layer
Option option
UnityEvent onKill
Anime animeIn
Anime animeOut
bool closeOthers
bool defaultActionMode = true
Button screenLock
Layer parent
string idLayer
List< Layer > layers = new List<Layer>()
Vector2 lastParentPos
List< Window > windows = new List<Window>()
string langHint
Private Member Functions
void Update ()
Private Attributes
UIItemPCC _uiItemPcc
UIPCC _uiPcc
List< UIItemPCCPart > _items = new List<UIItemPCCPart>()
List< Outline > _outlines = new List<Outline>()
Static Private Attributes
static readonly Dictionary< PCC.Part, BaseModPackage > _cached = new Dictionary<PCC.Part, BaseModPackage>()
static readonly Regex _idRegex = new Regex("(\\d+)|(\\D+)", RegexOptions.Compiled)
Additional Inherited Members
Static Public Attributes inherited from Layer
static int skipInput
static bool closeOnRightClick
static bool rightClicked
static bool cancelKeyDown
static bool ignoreSounds
static Transform blurStopInstance
static string[] searchPath = new string[3] { "Layer", "Layer/Dialog", "Layer/LayerHome" }
Protected Member Functions inherited from ELayer
sealed override void _Close ()
sealed override void Kill ()
Protected Member Functions inherited from Layer
virtual void Awake ()
virtual void _Close ()
virtual void Kill ()
Protected Attributes inherited from Layer
RectTransform _rect
bool isDestroyed
Properties inherited from ELayer
static Core core [get]
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static FactionBranch Branch [get]
static Faction Home [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static CoreConfig config [get]
static GameSetting setting [get]
static ColorProfile Colors [get]
static SourceManager sources [get]
static World world [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
bool IsFloat [get]
virtual string IdHelp [get]
Properties inherited from Layer
Layer TopLayer [get]
string uid [get]
virtual RectTransform rectLayers [get]
virtual bool blockWidgetClick [get]
Detailed Description
Definition at line 8 of file LayerPickPCC.cs.
Member Function Documentation
Activate()
void LayerPickPCC.Activate (UIPCC uiPcc, UIItemPCC uiItemPcc) inline
Definition at line 26 of file LayerPickPCC.cs.
    {
        _uiPcc = uiPcc;
        _uiItemPcc = uiItemPcc;
        PopulateButtons();
    }
References _uiItemPcc, _uiPcc, and PopulateButtons().
GetPartProvider()
static BaseModPackage LayerPickPCC.GetPartProvider (PCC::Part part) inline static
Definition at line 99 of file LayerPickPCC.cs.
    {
        if (part == null)
        {
            return null;
        }
        if (_cached.TryGetValue(part, out var value))
        {
            return value;
        }
        string dir = part.dir;
        value = BaseModManager.Instance.packages.FirstOrDefault((BaseModPackage p) => dir.StartsWith(p.dirInfo.FullName)) ?? new BaseModPackage
        {
            title = "unknownAuthor".lang()
        };
        return _cached[part] = value;
    }
References _cached, BaseModPackage.dirInfo, BaseModManager.Instance, BaseModManager.packages, and title.
Referenced by GetPartProviderString(), and PartSorter().
GetPartProviderString()
static string LayerPickPCC.GetPartProviderString (PCC::Part part) inline static
Definition at line 94 of file LayerPickPCC.cs.
    {
        return "ID: " + part.id + "\n<i>" + GetPartProvider(part).title.TagColor(Color.cyan) + "</i>\n" + part.dir.ShortPath();
    }
References Color, GetPartProvider(), and BaseModPackage.title.
Referenced by PopulateButtons().
PartSorter()
static int LayerPickPCC.PartSorter (PCC::Part lhs, PCC::Part rhs) inline static
Definition at line 117 of file LayerPickPCC.cs.
    {
        if (lhs == null)
        {
            if (rhs != null)
            {
                return -1;
            }
            return 0;
        }
        if (rhs == null)
        {
            return 1;
        }
        int num = GetPartSortOrder(lhs);
        int num2 = GetPartSortOrder(rhs);
        if (num != num2)
        {
            return num - num2;
        }
        string id = lhs.id;
        string id2 = rhs.id;
        if (id == id2)
        {
            return 0;
        }
        int result;
        bool flag = int.TryParse(id, out result);
        int result2;
        bool flag2 = int.TryParse(id2, out result2);
        if (flag && flag2)
        {
            return result.CompareTo(result2);
        }
        if (flag)
        {
            return -1;
        }
        if (flag2)
        {
            return 1;
        }
        MatchCollection matchCollection = _idRegex.Matches(id);
        MatchCollection matchCollection2 = _idRegex.Matches(id2);
        int num3 = Math.Min(matchCollection.Count, matchCollection2.Count);
        for (int i = 0; i < num3; i++)
        {
            string value = matchCollection[i].Value;
            string value2 = matchCollection2[i].Value;
            int result3;
            bool num4 = int.TryParse(value, out result3);
            int result4;
            bool flag3 = int.TryParse(value2, out result4);
            int num5 = ((!(num4 && flag3)) ? string.Compare(value, value2, StringComparison.OrdinalIgnoreCase) : result3.CompareTo(result4));
            if (num5 != 0)
            {
                return num5;
            }
        }
        return matchCollection.Count - matchCollection2.Count;
        static int GetPartSortOrder(PCC.Part part)
        {
            int num6 = BaseModManager.Instance.packages.IndexOf(GetPartProvider(part));
            if (num6 < 0)
            {
                return int.MaxValue;
            }
            return num6;
        }
    }
References _idRegex, GetPartProvider(), BaseModManager.Instance, and BaseModManager.packages.
Referenced by PopulateButtons().
PopulateButtons()
void LayerPickPCC.PopulateButtons () inline
Definition at line 43 of file LayerPickPCC.cs.
    {
        List<PCC.Part> list = _uiItemPcc.parts.ToList();
        list.Sort(PartSorter);
        foreach (PCC.Part part in list)
        {
            UIItemPCCPart item = Util.Instantiate(mold, layoutParts);
            if (part == _uiItemPcc.part)
            {
                SetOutline(item.outline);
            }
            if (part == null)
            {
                item.button.onClick.AddListener(delegate
                {
                    _uiItemPcc.slider.value = 0f;
                    SetOutline(item.outline);
                });
                item.button.tooltip.lang = "empty";
            }
            else
            {
                ModItem<Texture2D> modItem = part.modTextures.TryGetValue("walk");
                if (modItem == null)
                {
                    UnityEngine.Object.Destroy(item.gameObject);
                    continue;
                }
                item.button.tooltip.lang = GetPartProviderString(part);
                item.button.onClick.AddListener(delegate
                {
                    _uiItemPcc.slider.value = _uiItemPcc.parts.IndexOf(part);
                    SetOutline(item.outline);
                });
                item.SetSprites(IO.LoadPNG(modItem.fileInfo.FullName));
                Color color = _uiPcc.pcc.data.GetColor(_uiItemPcc.idPartSet);
                item.button.icon.color = _uiPcc.pccm.ApplyColorMod(color);
            }
            _items.Add(item);
        }
        void SetOutline(Outline outline)
        {
            _outlines.Add(outline);
            foreach (Outline outline in _outlines)
            {
                outline.enabled = false;
            }
            outline.enabled = true;
        }
    }
References _items, _outlines, _uiItemPcc, _uiPcc, Color, ModItem< T >.fileInfo, GetPartProviderString(), item, layoutParts, mold, Outline, PartSorter(), and Util.
Referenced by Activate().
Update()
void LayerPickPCC.Update () inline private
Definition at line 33 of file LayerPickPCC.cs.
    {
        SpriteProvider provider = _uiPcc.actor.provider;
        int frame = (provider.currentFrame + 2) % 4;
        foreach (UIItemPCCPart item in _items)
        {
            item.SetSpriteIndex(provider.currentDir, frame);
        }
    }
References _items, _uiPcc, and item.
Member Data Documentation
_cached
readonly Dictionary<PCC.Part, BaseModPackage> LayerPickPCC._cached = new Dictionary<PCC.Part, BaseModPackage>() static private
Definition at line 22 of file LayerPickPCC.cs.
Referenced by GetPartProvider().
_idRegex
readonly Regex LayerPickPCC._idRegex = new Regex("(\\d+)|(\\D+)", RegexOptions.Compiled) static private
Definition at line 24 of file LayerPickPCC.cs.
Referenced by PartSorter().
_items
List<UIItemPCCPart> LayerPickPCC._items = new List<UIItemPCCPart>() private
Definition at line 18 of file LayerPickPCC.cs.
Referenced by PopulateButtons(), and Update().
_outlines
List<Outline> LayerPickPCC._outlines = new List<Outline>() private
Definition at line 20 of file LayerPickPCC.cs.
Referenced by PopulateButtons().
_uiItemPcc
UIItemPCC LayerPickPCC._uiItemPcc private
Definition at line 14 of file LayerPickPCC.cs.
Referenced by Activate(), and PopulateButtons().
_uiPcc
UIPCC LayerPickPCC._uiPcc private
Definition at line 16 of file LayerPickPCC.cs.
Referenced by Activate(), PopulateButtons(), and Update().
layoutParts
LayoutGroup LayerPickPCC.layoutParts
Definition at line 12 of file LayerPickPCC.cs.
Referenced by PopulateButtons().
mold
UIItemPCCPart LayerPickPCC.mold
Definition at line 10 of file LayerPickPCC.cs.
Referenced by PopulateButtons().
The documentation for this class was generated from the following file:
Elin/LayerPickPCC.cs