Elin Decompiled Documentation: MiniGame Class Reference
MiniGame Class Reference
Classes
class Balance
Public Types
enum Type {
Slot , Blackjack , Scratch , Basket ,
CoinDrop
}
Public Member Functions
virtual void OnActivate ()
virtual void OnDeactivate ()
virtual void SlidePosition (float w)
void Deactivate ()
void SetAudioMixer (GameObject go)
void Say (string lang)
virtual bool CanExit ()
void Exit ()
bool OnPlay (int a)
void GetSlotReward (string id, int pay=1, int bet=1)
Static Public Member Functions
static void RegisterMiniGame (string id, MiniGame g, string _path)
static void Activate (Type type)
Public Attributes
Balance balance = new Balance()
GameObject go
AssetBundle asset
string path
bool isActive
Static Public Attributes
static Dictionary< string, MiniGame > minigames = new Dictionary<string, MiniGame>()
Properties
virtual string id [get]
Detailed Description
Definition at line 5 of file MiniGame.cs.
Member Enumeration Documentation
Type
enum MiniGame.Type
Enumerator
Slot
Blackjack
Scratch
Basket
CoinDrop
Definition at line 14 of file MiniGame.cs.
    {
        Slot,
        Blackjack,
        Scratch,
        Basket,
        CoinDrop
    }
Member Function Documentation
Activate()
static void MiniGame.Activate (Type type) inline static
Definition at line 44 of file MiniGame.cs.
    {
        if (!minigames.ContainsKey("Basket"))
        {
            minigames.Add("Basket", new MiniGame_Basket());
        }
        if (!minigames.ContainsKey("Blackjack"))
        {
            minigames.Add("Blackjack", new MiniGame_Blackjack());
        }
        Debug.Log("Activating:" + type);
        MiniGame miniGame = minigames.TryGetValue(type.ToString());
        if (miniGame == null)
        {
            Msg.Say("minigame_notSupported");
            EClass.scene.TryWarnLinuxMod();
            return;
        }
        LayerMiniGame layerMiniGame = EClass.ui.AddLayer<LayerMiniGame>();
        Debug.Log(layerMiniGame);
        Debug.Log(miniGame);
        miniGame.balance = new Balance();
        layerMiniGame.mini = miniGame;
        layerMiniGame.type = type;
        Debug.Log("aaa");
        layerMiniGame.Run();
    }
References Debug, minigames, LayerMiniGame.Run(), Msg.Say(), EClass.scene, Scene.TryWarnLinuxMod(), and EClass.ui.
Referenced by TraitBasketGame.OnActivateTrap(), TraitBJTable.OnUse(), TraitSlotMachine.OnUse(), and CoreDebug.UpdateInput().
CanExit()
virtual bool MiniGame.CanExit () inline virtual
Definition at line 115 of file MiniGame.cs.
    {
        return true;
    }
Referenced by LayerMiniGame.OnBack().
Deactivate()
void MiniGame.Deactivate () inline
Definition at line 84 of file MiniGame.cs.
    {
        OnDeactivate();
        Debug.Log(balance.lastCoin);
        Debug.Log(balance.changeCoin);
        if (balance.changeCoin != 0)
        {
            EClass.pc.ModCurrency(balance.changeCoin, "casino_coin");
        }
        LayerMiniGame layer = EClass.ui.GetLayer<LayerMiniGame>();
        if (layer != null)
        {
            layer.mini = null;
            layer.Close();
        }
    }
References balance, MiniGame.Balance.changeCoin, Layer.Close(), Debug, MiniGame.Balance.lastCoin, Card.ModCurrency(), OnDeactivate(), EClass.pc, and EClass.ui.
Referenced by LayerMiniGame.OnKill().
Exit()
void MiniGame.Exit () inline
Definition at line 120 of file MiniGame.cs.
    {
        EClass.ui.GetLayer<LayerMiniGame>()?.Close();
    }
References EClass.ui.
GetSlotReward()
void MiniGame.GetSlotReward (string id, int pay = 1, int bet = 1) inline
Definition at line 152 of file MiniGame.cs.
    {
        if (id == null)
        {
            id = new string[6] { "ehe", "wild", "cat", "larnneire", "lomias", "bread" }.RandomItem();
            Debug.Log(id);
        }
        Thing c = ThingGen.Create("casino_coin").SetNum(pay * bet);
        Msg.Say("slot_win", c);
    }
References ThingGen.Create(), Debug, Msg.Say(), and Card.SetNum().
OnActivate()
virtual void MiniGame.OnActivate () inline virtual
Definition at line 72 of file MiniGame.cs.
    {
    }
Referenced by LayerMiniGame.Run().
OnDeactivate()
virtual void MiniGame.OnDeactivate () inline virtual
Definition at line 76 of file MiniGame.cs.
    {
    }
Referenced by Deactivate().
OnPlay()
bool MiniGame.OnPlay (int a) inline
Definition at line 125 of file MiniGame.cs.
    {
        LayerMiniGame layer = EClass.ui.GetLayer<LayerMiniGame>();
        if ((bool)layer)
        {
            switch (layer.type)
            {
            case Type.Basket:
                EClass.pc.ModExp(108, 15);
                break;
            case Type.Blackjack:
                EClass.pc.ModExp(135, 10);
                break;
            case Type.Slot:
                EClass.pc.ModExp(134, 10);
                break;
            }
        }
        EClass.pc.stamina.Mod(-a);
        EClass.player.EndTurn();
        if (EClass.pc.isDead || EClass.pc.IsDisabled)
        {
            return false;
        }
        return true;
    }
References Player.EndTurn(), Chara.isDead, Chara.IsDisabled, Stats.Mod(), Card.ModExp(), EClass.pc, EClass.player, Chara.stamina, LayerMiniGame.type, and EClass.ui.
RegisterMiniGame()
static void MiniGame.RegisterMiniGame (string id, MiniGame g, string _path) inline static
Definition at line 37 of file MiniGame.cs.
    {
        g.path = new FileInfo(_path).DirectoryName;
        minigames[id] = g;
        Debug.Log("Registered:" + g?.ToString() + " at " + g.path);
    }
References Debug, id, minigames, and path.
Say()
void MiniGame.Say (string lang) inline
Definition at line 110 of file MiniGame.cs.
    {
        Msg.Say(lang);
    }
References Msg.Say().
SetAudioMixer()
void MiniGame.SetAudioMixer (GameObject go) inline
Definition at line 101 of file MiniGame.cs.
    {
        AudioSource[] componentsInChildren = go.GetComponentsInChildren<AudioSource>();
        for (int i = 0; i < componentsInChildren.Length; i++)
        {
            componentsInChildren[i].outputAudioMixerGroup = SoundManager.current.mixer.FindMatchingGroups("SFX")[0];
        }
    }
References go.
Referenced by ModMinigame< T >.Load().
SlidePosition()
virtual void MiniGame.SlidePosition (float w) inline virtual
Definition at line 80 of file MiniGame.cs.
    {
    }
Referenced by WidgetSideScreen.SlideMiniGame().
Member Data Documentation
asset
AssetBundle MiniGame.asset
Definition at line 29 of file MiniGame.cs.
Referenced by ModMinigame< T >.Kill(), and ModMinigame< T >.Load().
balance
Balance MiniGame.balance = new Balance()
Definition at line 25 of file MiniGame.cs.
Referenced by Deactivate().
go
GameObject MiniGame.go
Definition at line 27 of file MiniGame.cs.
Referenced by ModMinigame< T >.Kill(), ModMinigame< T >.Load(), and SetAudioMixer().
isActive
bool MiniGame.isActive
Definition at line 33 of file MiniGame.cs.
minigames
Dictionary<string, MiniGame> MiniGame.minigames = new Dictionary<string, MiniGame>() static
Definition at line 23 of file MiniGame.cs.
Referenced by Activate(), and RegisterMiniGame().
path
string MiniGame.path
Definition at line 31 of file MiniGame.cs.
Referenced by ModMinigame< T >.Load(), and RegisterMiniGame().
Property Documentation
id
virtual string MiniGame.id get
Definition at line 35 of file MiniGame.cs.
Referenced by RegisterMiniGame().
The documentation for this class was generated from the following file:
Elin/MiniGame.cs