Elin Decompiled Documentation: ImageExample Class Reference
ImageExample Class Reference
Classes
class DropInfo
Private Member Functions
void OnEnable ()
void OnDisable ()
void OnFiles (List< string > aFiles, POINT aPos)
void LoadImage (int aIndex, DropInfo aInfo)
void OnGUI ()
Private Attributes
Texture2D[] textures = new Texture2D[6]
DropInfo dropInfo
Detailed Description
Definition at line 6 of file ImageExample.cs.
Member Function Documentation
LoadImage()
void ImageExample.LoadImage (int aIndex, DropInfo aInfo) inline private
Definition at line 58 of file ImageExample.cs.
    {
        if (aInfo != null && GUILayoutUtility.GetLastRect().Contains(aInfo.pos))
        {
            byte[] data = File.ReadAllBytes(aInfo.file);
            Texture2D texture2D = new Texture2D(1, 1);
            texture2D.LoadImage(data);
            if (textures[aIndex] != null)
            {
                Object.Destroy(textures[aIndex]);
            }
            textures[aIndex] = texture2D;
        }
    }
References ImageExample.DropInfo.file, ImageExample.DropInfo.pos, and textures.
Referenced by OnGUI().
OnDisable()
void ImageExample.OnDisable () inline private
Definition at line 25 of file ImageExample.cs.
    {
        UnityDragAndDropHook.UninstallHook();
    }
References B83.Win32.UnityDragAndDropHook.UninstallHook().
OnEnable()
void ImageExample.OnEnable () inline private
Definition at line 19 of file ImageExample.cs.
    {
        UnityDragAndDropHook.InstallHook();
        UnityDragAndDropHook.OnDroppedFiles += OnFiles;
    }
References B83.Win32.UnityDragAndDropHook.InstallHook(), and OnFiles().
OnFiles()
void ImageExample.OnFiles (List< string > aFiles, POINT aPos) inline private
Definition at line 30 of file ImageExample.cs.
    {
        string text = "";
        foreach (string aFile in aFiles)
        {
            switch (new FileInfo(aFile).Extension.ToLower())
            {
            case ".png":
            case ".jpg":
            case ".jpeg":
                text = aFile;
                goto end_IL_0053;
            }
            continue;
            end_IL_0053:
            break;
        }
        if (text != "")
        {
            DropInfo dropInfo = new DropInfo
            {
                file = text,
                pos = new Vector2(aPos.x, aPos.y)
            };
            this.dropInfo = dropInfo;
        }
    }
References dropInfo.
Referenced by OnEnable().
OnGUI()
void ImageExample.OnGUI () inline private
Definition at line 73 of file ImageExample.cs.
    {
        DropInfo aInfo = null;
        if (Event.current.type == EventType.Repaint && dropInfo != null)
        {
            aInfo = dropInfo;
            dropInfo = null;
        }
        GUILayout.BeginHorizontal();
        for (int i = 0; i < 3; i++)
        {
            if (textures[i] != null)
            {
                GUILayout.Label(textures[i], GUILayout.Width(200f), GUILayout.Height(200f));
            }
            else
            {
                GUILayout.Box("Drag image here", GUILayout.Width(200f), GUILayout.Height(200f));
            }
            LoadImage(i, aInfo);
        }
        GUILayout.EndHorizontal();
        GUILayout.BeginHorizontal();
        for (int j = 3; j < 6; j++)
        {
            if (textures[j] != null)
            {
                GUILayout.Label(textures[j], GUILayout.Width(200f), GUILayout.Height(200f));
            }
            else
            {
                GUILayout.Box("Drag image here", GUILayout.Width(200f), GUILayout.Height(200f));
            }
            LoadImage(j, aInfo);
        }
        GUILayout.EndHorizontal();
    }
References dropInfo, LoadImage(), and textures.
Member Data Documentation
dropInfo
DropInfo ImageExample.dropInfo private
Definition at line 17 of file ImageExample.cs.
Referenced by OnFiles(), and OnGUI().
textures
Texture2D [] ImageExample.textures = new Texture2D[6] private
Definition at line 15 of file ImageExample.cs.
Referenced by LoadImage(), and OnGUI().
The documentation for this class was generated from the following file:
Elin/Plugins.basecore/ImageExample.cs