Elin Decompiled Documentation: WidgetSceneCustomizer Class Reference
WidgetSceneCustomizer Class Reference
Public Member Functions
override void OnActivate ()
void ShowPicker ()
void RefreshColor ()
void OnClickSave ()
void OnClickLoad ()
void OnClickReset ()
Public Member Functions inherited from Widget
void Test ()
bool IsInRightMode ()
void Activate ()
void RefreshOrder ()
virtual void OnActivate ()
virtual object CreateExtra ()
void Deactivate ()
virtual void OnDeactivate ()
void Close ()
void Reactivate ()
virtual void OnManagerActivate ()
virtual void OnManagerDeactivate ()
void SetAnchor (RectPosition p)
void SetPivot (RectPosition p)
virtual void OnChangePivot ()
void UpdateConfig ()
virtual void OnUpdateConfig ()
void ClampToScreen ()
virtual void OnChangeResolution ()
void OnChangePosition ()
virtual void OnChangeActionMode ()
virtual void OnFlip ()
bool IsAlignTop ()
Layer AddLayer (Layer l, Transform trans)
void RefreshTipPivotPosition ()
SkinSet GetSkin ()
SkinConfig GetSkinConfig ()
void SetSkin (int id, int v=0)
void TestSkin ()
virtual void ApplySkin ()
virtual void OnApplySkin ()
void InstantiateDeco (SkinDeco deco)
void AddDeco (SkinDeco deco)
void RemoveDeco (SkinDeco deco)
virtual bool CanShowContextMenu ()
void ShowContextMenu ()
void SetBaseContextMenu (UIContextMenu m)
virtual void OnSetContextMenu (UIContextMenu m)
void SetGridContextMenu (UIContextMenu m)
void SoundActivate ()
void OnChangeResolution ()
SkinSet GetSkin ()
SkinConfig GetSkinConfig ()
Public Attributes
UIDropdown ddLiquid
UIDropdown ddRefraction
UIDropdown ddOverlay
UIDropdown ddLut
List< LiquidProfile > liquids
List< RefractionProfile > refractions
List< OverlayProfile > overlays
List< string > luts
UIButton toggleGradientWater
UIButton buttonColorPicker
Slider sliderLutBlend
Slider sliderLutBrightness
Slider sliderLutContrast
UISlider sliderLut
Public Attributes inherited from Widget
Image imageBG
SoundData soundActivate
UIDragPanel dragPanel
RectTransform tipPivotLeft
RectTransform tipPivotRight
Additional Inherited Members
Public Types inherited from Widget
enum WidgetType { Default , ZoomMenu }
enum State { Active , Inactive }
Static Public Member Functions inherited from EMono
static int rnd (int a)
Static Public Attributes inherited from EMono
static Core core
Protected Member Functions inherited from Widget
void ClampToScreenEnsured (Component c, Vector2 anchoredPos)
void ClampToScreen (RectTransform rect, float margin=10f)
Protected Attributes inherited from Widget
bool flip
Properties inherited from Widget
string ID [get]
Config config [get]
SkinRoot skinRoot [get]
bool IsSealed [get]
virtual bool ShowStyleMenu [get]
virtual bool AlwaysTop [get]
virtual bool IsStaticPosition [get]
virtual bool AlwaysBottom [get]
virtual Type SetSiblingAfter [get]
virtual bool ShowInBuildMode [get]
virtual bool RightClickToClose [get]
virtual bool AllowRightClickToClose [get]
Properties inherited from EMono
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SoundManager Sound [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static CoreDebug debug [get]
Detailed Description
Definition at line 6 of file WidgetSceneCustomizer.cs.
Member Function Documentation
OnActivate()
override void WidgetSceneCustomizer.OnActivate () inline virtual
Reimplemented from Widget.
Definition at line 36 of file WidgetSceneCustomizer.cs.
    {
        MapConfig conf = EMono._map.config;
        ddLiquid.SetList(conf.idLiquid, liquids, (LiquidProfile a, int b) => a.name, delegate(int a, LiquidProfile b)
        {
            if (conf.idLiquid != b.name)
            {
                conf.idLiquid = b.name;
                conf.colorLiquid = null;
                EMono.scene.ApplyZoneConfig();
            }
            RefreshColor();
        });
        ddRefraction.SetList(conf.idRefraction, refractions, (RefractionProfile a, int b) => a.name, delegate(int a, RefractionProfile b)
        {
            if (conf.idRefraction != b.name)
            {
                conf.idRefraction = b.name;
                EMono.scene.ApplyZoneConfig();
            }
        });
        ddLut.SetList(conf.idLut, luts, (string a, int b) => a, delegate(int a, string b)
        {
            if (conf.idLut != b)
            {
                conf.idLut = b;
                EMono.scene.ApplyZoneConfig();
            }
        });
        sliderLutBlend.SetSlider(conf.lutBlend, delegate(float a)
        {
            conf.lutBlend = a;
            EMono.scene.ApplyZoneConfig();
            return Lang.Get("lutBlend") + "(" + (int)(a * 100f) + "%)";
        });
        sliderLutBrightness.SetSlider(conf.lutBrightness, delegate(float a)
        {
            conf.lutBrightness = a;
            EMono.scene.ApplyZoneConfig();
            return Lang.Get("lutBrightness") + "(" + (int)(a * 100f) + "%)";
        });
        sliderLutContrast.SetSlider(conf.lutContrast, delegate(float a)
        {
            conf.lutContrast = a;
            EMono.scene.ApplyZoneConfig();
            return Lang.Get("lutContrast") + "(" + (int)(a * 100f) + "%)";
        });
        List<Texture2D> list = new List<Texture2D>(Resources.LoadAll<Texture2D>("Scene/Profile/Lut/"));
        list.Insert(0, null);
        sliderLut.SetList(list.Find((Texture2D a) => (!(a == null)) ? (conf.idLut == a.name) : (conf.idLut == "None")), list, delegate(int a, Texture2D b)
        {
            conf.idLut = ((b == null) ? "None" : b.name);
            EMono.scene.ApplyZoneConfig();
        }, (Texture2D a) => (!(a == null)) ? a.name : "None");
        RefreshColor();
    }
References EMono._map, Scene.ApplyZoneConfig(), Map.config, ddLiquid, ddLut, ddRefraction, Lang.Get(), MapConfig.idLiquid, MapConfig.idLut, MapConfig.idRefraction, liquids, MapConfig.lutBlend, MapConfig.lutBrightness, MapConfig.lutContrast, luts, refractions, RefreshColor(), EMono.scene, sliderLut, sliderLutBlend, sliderLutBrightness, and sliderLutContrast.
OnClickLoad()
void WidgetSceneCustomizer.OnClickLoad () inline
Definition at line 133 of file WidgetSceneCustomizer.cs.
    {
        EMono.core.WaitForEndOfFrame(delegate
        {
            string[] array = StandaloneFileBrowser.OpenFilePanel("Load Zone Config", CorePath.SceneCustomizerSave, "json", multiselect: false);
            if (array.Length != 0)
            {
                EMono._map.config = IO.LoadFile<MapConfig>(array[0]);
                Reactivate();
            }
        });
    }
References EMono.core, if(), SFB.StandaloneFileBrowser.OpenFilePanel(), CorePath.SceneCustomizerSave, and BaseCore.WaitForEndOfFrame().
OnClickReset()
void WidgetSceneCustomizer.OnClickReset () inline
Definition at line 146 of file WidgetSceneCustomizer.cs.
    {
        EMono._map.config = new MapConfig();
        Reactivate();
    }
References Widget.Reactivate().
OnClickSave()
void WidgetSceneCustomizer.OnClickSave () inline
Definition at line 121 of file WidgetSceneCustomizer.cs.
    {
        EMono.core.WaitForEndOfFrame(delegate
        {
            string text = StandaloneFileBrowser.SaveFilePanel("Save Zone Config", CorePath.SceneCustomizerSave, "new zone config", "json");
            if (!string.IsNullOrEmpty(text))
            {
                IO.SaveFile(text, EMono._map.config);
            }
        });
    }
References EMono._map, Map.config, EMono.core, if(), SFB.StandaloneFileBrowser.SaveFilePanel(), CorePath.SceneCustomizerSave, and BaseCore.WaitForEndOfFrame().
RefreshColor()
void WidgetSceneCustomizer.RefreshColor () inline
Definition at line 113 of file WidgetSceneCustomizer.cs.
    {
        LiquidProfile liquidProfile = LiquidProfile.Get(EMono._map.config.idLiquid);
        Color color = EMono._map.config.colorLiquid?.Get() ?? liquidProfile.modColor;
        color.a = 1f;
        buttonColorPicker.icon.color = color;
    }
References EMono._map, Color, MapConfig.colorLiquid, Map.config, SerializableColor.Get(), LiquidProfile.Get(), MapConfig.idLiquid, and LiquidProfile.modColor.
Referenced by OnActivate(), and ShowPicker().
ShowPicker()
void WidgetSceneCustomizer.ShowPicker () inline
Definition at line 93 of file WidgetSceneCustomizer.cs.
    {
        MapConfig conf = EMono._map.config;
        LiquidProfile prof = LiquidProfile.Get(conf.idLiquid);
        EMono.ui.AddLayer<LayerColorPicker>().SetColor(conf.colorLiquid?.Get() ?? prof.modColor, prof.modColor, delegate(PickerState state, Color c)
        {
            prof.Apply(c);
            switch (state)
            {
            case PickerState.Confirm:
                conf.colorLiquid = new SerializableColor(c);
                RefreshColor();
                break;
            case PickerState.Cancel:
                EMono.scene.ApplyZoneConfig();
                break;
            }
        });
    }
References EMono._map, LiquidProfile.Apply(), Scene.ApplyZoneConfig(), Color, MapConfig.colorLiquid, Map.config, SerializableColor.Get(), LiquidProfile.Get(), MapConfig.idLiquid, LiquidProfile.modColor, RefreshColor(), EMono.scene, and EMono.ui.
Member Data Documentation
buttonColorPicker
UIButton WidgetSceneCustomizer.buttonColorPicker
Definition at line 26 of file WidgetSceneCustomizer.cs.
ddLiquid
UIDropdown WidgetSceneCustomizer.ddLiquid
Definition at line 8 of file WidgetSceneCustomizer.cs.
Referenced by OnActivate().
ddLut
UIDropdown WidgetSceneCustomizer.ddLut
Definition at line 14 of file WidgetSceneCustomizer.cs.
Referenced by OnActivate().
ddOverlay
UIDropdown WidgetSceneCustomizer.ddOverlay
Definition at line 12 of file WidgetSceneCustomizer.cs.
ddRefraction
UIDropdown WidgetSceneCustomizer.ddRefraction
Definition at line 10 of file WidgetSceneCustomizer.cs.
Referenced by OnActivate().
liquids
List<LiquidProfile> WidgetSceneCustomizer.liquids
Definition at line 16 of file WidgetSceneCustomizer.cs.
Referenced by OnActivate().
luts
List<string> WidgetSceneCustomizer.luts
Definition at line 22 of file WidgetSceneCustomizer.cs.
Referenced by OnActivate().
overlays
List<OverlayProfile> WidgetSceneCustomizer.overlays
Definition at line 20 of file WidgetSceneCustomizer.cs.
refractions
List<RefractionProfile> WidgetSceneCustomizer.refractions
Definition at line 18 of file WidgetSceneCustomizer.cs.
Referenced by OnActivate().
sliderLut
UISlider WidgetSceneCustomizer.sliderLut
Definition at line 34 of file WidgetSceneCustomizer.cs.
Referenced by OnActivate().
sliderLutBlend
Slider WidgetSceneCustomizer.sliderLutBlend
Definition at line 28 of file WidgetSceneCustomizer.cs.
Referenced by OnActivate().
sliderLutBrightness
Slider WidgetSceneCustomizer.sliderLutBrightness
Definition at line 30 of file WidgetSceneCustomizer.cs.
Referenced by OnActivate().
sliderLutContrast
Slider WidgetSceneCustomizer.sliderLutContrast
Definition at line 32 of file WidgetSceneCustomizer.cs.
Referenced by OnActivate().
toggleGradientWater
UIButton WidgetSceneCustomizer.toggleGradientWater
Definition at line 24 of file WidgetSceneCustomizer.cs.
The documentation for this class was generated from the following file:
Elin/WidgetSceneCustomizer.cs