Elin Decompiled Documentation: ItemNumLog Class Reference
ItemNumLog Class Reference
Public Member Functions
void SetLog (NumLog log)
Public Attributes
UIText textTitle
UIText textCurrent
UIText textLastDay
UIText textLastMonth
UIText textLastYear
LayoutGroup layout
Additional Inherited Members
Static Public Member Functions inherited from EMono
static int rnd (int a)
Static Public Attributes inherited from EMono
static Core core
Properties inherited from EMono
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SoundManager Sound [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static CoreDebug debug [get]
Detailed Description
Definition at line 5 of file ItemNumLog.cs.
Member Function Documentation
SetLog()
void ItemNumLog.SetLog (NumLog log) inline
Definition at line 19 of file ItemNumLog.cs.
    {
        textTitle.text = log.Name;
        textCurrent.text = log.Value.ToString() ?? "";
        textLastDay.text = log.lastDay.ToString() ?? "";
        textLastMonth.text = log.lastMonth.ToString() ?? "";
        textLastYear.text = log.lastYear.ToString() ?? "";
        if (!layout)
        {
            return;
        }
        UIItem mold = layout.CreateMold<UIItem>();
        List<Gross.Mod> mods = log.gross.GetMods();
        Action<string> action = delegate(string a)
        {
            Util.Instantiate(mold, layout).text1.text = a;
        };
        if (mods.Count == 0)
        {
            action(Lang.Get("noMod"));
            return;
        }
        foreach (Gross.Mod item in mods)
        {
            _ = item;
            action("");
        }
    }
References Lang.Get(), Gross.GetMods(), NumLog.gross, item, NumLog.lastDay, NumLog.lastMonth, NumLog.lastYear, layout, NumLog.Name, and NumLog.Value.
Referenced by ContentStatistics.OnSwitchContent().
Member Data Documentation
layout
LayoutGroup ItemNumLog.layout
Definition at line 17 of file ItemNumLog.cs.
Referenced by SetLog().
textCurrent
UIText ItemNumLog.textCurrent
Definition at line 9 of file ItemNumLog.cs.
textLastDay
UIText ItemNumLog.textLastDay
Definition at line 11 of file ItemNumLog.cs.
textLastMonth
UIText ItemNumLog.textLastMonth
Definition at line 13 of file ItemNumLog.cs.
textLastYear
UIText ItemNumLog.textLastYear
Definition at line 15 of file ItemNumLog.cs.
textTitle
UIText ItemNumLog.textTitle
Definition at line 7 of file ItemNumLog.cs.
The documentation for this class was generated from the following file:
Elin/ItemNumLog.cs