Elin Decompiled Documentation: UIResourceTrack Class Reference
UIResourceTrack Class Reference
Public Member Functions
void OnActivate ()
void OnMoveZone ()
void _Refresh ()
Static Public Member Functions
static void Refresh ()
Static Public Member Functions inherited from EMono
static int rnd (int a)
Public Attributes
LayoutGroup layout
ButtonResourceTrack mold
UIButton buttonAdd
Dictionary< string, ButtonResourceTrack > dictProp = new Dictionary<string, ButtonResourceTrack>()
Dictionary< string, ButtonResourceTrack > dictCat = new Dictionary<string, ButtonResourceTrack>()
Static Public Attributes
static UIResourceTrack Instance
Static Public Attributes inherited from EMono
static Core core
Private Attributes
List< string > listRemove = new List<string>()
bool dirtyLayout
Additional Inherited Members
Properties inherited from EMono
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SoundManager Sound [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static CoreDebug debug [get]
Detailed Description
Definition at line 5 of file UIResourceTrack.cs.
Member Function Documentation
_Refresh()
void UIResourceTrack._Refresh () inline
Definition at line 53 of file UIResourceTrack.cs.
    {
        dirtyLayout = false;
        HashSet<string> trackedCards = EMono.player.trackedCards;
        HashSet<string> trackedCategories = EMono.player.trackedCategories;
        foreach (string item in trackedCards)
        {
            if (dictProp.ContainsKey(item))
            {
                dictProp[item].Refresh();
                continue;
            }
            ButtonResourceTrack buttonResourceTrack = Util.Instantiate(mold, layout);
            buttonResourceTrack.SetProp(item);
            dictProp.Add(item, buttonResourceTrack);
            dirtyLayout = true;
        }
        foreach (string item2 in trackedCategories)
        {
            if (dictCat.ContainsKey(item2))
            {
                dictCat[item2].Refresh();
                continue;
            }
            ButtonResourceTrack buttonResourceTrack2 = Util.Instantiate(mold, layout);
            buttonResourceTrack2.SetCat(item2);
            dictCat.Add(item2, buttonResourceTrack2);
            dirtyLayout = true;
        }
        listRemove.Clear();
        foreach (string key in dictProp.Keys)
        {
            if (!trackedCards.Contains(key))
            {
                listRemove.Add(key);
            }
        }
        foreach (string item3 in listRemove)
        {
            Object.DestroyImmediate(dictProp[item3].gameObject);
            dictProp.Remove(item3);
            dirtyLayout = true;
        }
        listRemove.Clear();
        foreach (string key2 in dictCat.Keys)
        {
            if (!trackedCategories.Contains(key2))
            {
                listRemove.Add(key2);
            }
        }
        foreach (string item4 in listRemove)
        {
            Object.DestroyImmediate(dictCat[item4].gameObject);
            dictCat.Remove(item4);
            dirtyLayout = true;
        }
        if (dirtyLayout)
        {
            buttonAdd.transform.SetAsLastSibling();
            layout.RebuildLayout(recursive: true);
        }
    }
References buttonAdd, dictCat, dictProp, dirtyLayout, layout, listRemove, mold, EMono.player, ButtonResourceTrack.SetCat(), ButtonResourceTrack.SetProp(), Player.trackedCards, and Player.trackedCategories.
Referenced by OnActivate(), OnMoveZone(), Refresh(), ButtonResourceTrack.SetCat(), and ButtonResourceTrack.SetProp().
OnActivate()
void UIResourceTrack.OnActivate () inline
Definition at line 31 of file UIResourceTrack.cs.
    {
        Instance = this;
        buttonAdd.SetOnClick(delegate
        {
            EMono.ui.AddLayer<LayerResource>();
        });
        if (!mold)
        {
            mold = layout.CreateMold<ButtonResourceTrack>();
        }
        _Refresh();
    }
References _Refresh(), buttonAdd, Instance, layout, mold, and EMono.ui.
OnMoveZone()
void UIResourceTrack.OnMoveZone () inline
Definition at line 45 of file UIResourceTrack.cs.
    {
        dictProp.Clear();
        dictCat.Clear();
        layout.DestroyChildren();
        _Refresh();
    }
References _Refresh(), dictCat, dictProp, and layout.
Referenced by Player.MoveZone().
Refresh()
static void UIResourceTrack.Refresh () inline static
Definition at line 23 of file UIResourceTrack.cs.
    {
        if ((bool)Instance)
        {
            Instance._Refresh();
        }
    }
References _Refresh(), and Instance.
Referenced by LayerResource.RefreshCategory(), LayerResource.ShowThings(), and GameUpdater.Update().
Member Data Documentation
buttonAdd
UIButton UIResourceTrack.buttonAdd
Definition at line 13 of file UIResourceTrack.cs.
Referenced by _Refresh(), and OnActivate().
dictCat
Dictionary<string, ButtonResourceTrack> UIResourceTrack.dictCat = new Dictionary<string, ButtonResourceTrack>()
Definition at line 17 of file UIResourceTrack.cs.
Referenced by _Refresh(), and OnMoveZone().
dictProp
Dictionary<string, ButtonResourceTrack> UIResourceTrack.dictProp = new Dictionary<string, ButtonResourceTrack>()
Definition at line 15 of file UIResourceTrack.cs.
Referenced by _Refresh(), and OnMoveZone().
dirtyLayout
bool UIResourceTrack.dirtyLayout private
Definition at line 21 of file UIResourceTrack.cs.
Referenced by _Refresh().
Instance
UIResourceTrack UIResourceTrack.Instance static
Definition at line 7 of file UIResourceTrack.cs.
Referenced by Player.MoveZone(), OnActivate(), and Refresh().
layout
LayoutGroup UIResourceTrack.layout
Definition at line 9 of file UIResourceTrack.cs.
Referenced by _Refresh(), OnActivate(), and OnMoveZone().
listRemove
List<string> UIResourceTrack.listRemove = new List<string>() private
Definition at line 19 of file UIResourceTrack.cs.
Referenced by _Refresh().
mold
ButtonResourceTrack UIResourceTrack.mold
Definition at line 11 of file UIResourceTrack.cs.
Referenced by _Refresh(), and OnActivate().
The documentation for this class was generated from the following file:
Elin/UIResourceTrack.cs