Elin Decompiled Documentation: Affinity Class Reference
Affinity Class Reference
Public Types
enum Stage {
Foe , Hate , Annoying , Normal ,
Approved , Friendly , Respected , Intimate ,
Fond , Love , LoveLove , LoveLoveLove
}
Public Member Functions
bool CanForceTradeEquip ()
bool CanInvite ()
bool CanGiveCard ()
bool CanMarry ()
bool CanSleepBeside ()
int GetLunchChance ()
Sprite GetIcon ()
Thing OnGift (Thing t)
void OnTalkRumor ()
int Mod (int a)
Static Public Member Functions
static Affinity Get (Chara c)
Static Public Member Functions inherited from EClass
static int rndSeed (int a, int seed)
static int rnd (long a)
static int rnd (int a)
static int curve (int a, int start, int step, int rate=75)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Public Attributes
int value
int difficulty
Static Public Attributes
static Chara CC
Static Public Attributes inherited from EClass
static Core core
Properties
static List< Affinity > list [get]
Stage CurrentStage [get]
string Name [get]
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Detailed Description
Definition at line 6 of file Affinity.cs.
Member Enumeration Documentation
Stage
enum Affinity.Stage
Enumerator
Foe
Hate
Annoying
Normal
Approved
Friendly
Respected
Intimate
Fond
Love
LoveLove
LoveLoveLove
Definition at line 8 of file Affinity.cs.
    {
        Foe,
        Hate,
        Annoying,
        Normal,
        Approved,
        Friendly,
        Respected,
        Intimate,
        Fond,
        Love,
        LoveLove,
        LoveLoveLove
    }
Member Function Documentation
CanForceTradeEquip()
bool Affinity.CanForceTradeEquip () inline
Definition at line 49 of file Affinity.cs.
    {
        return CurrentStage >= Stage.Respected;
    }
References CurrentStage.
Referenced by InvOwner.AllowHold().
CanGiveCard()
bool Affinity.CanGiveCard () inline
Definition at line 63 of file Affinity.cs.
    {
        return CurrentStage >= Stage.Love;
    }
References CurrentStage.
Referenced by Trait.OnBarter(), TCOrbitChara.RefreshAll(), and Chara.ShowDialog().
CanInvite()
bool Affinity.CanInvite () inline
Definition at line 54 of file Affinity.cs.
    {
        if (!EClass.debug.inviteAnytime)
        {
            return CurrentStage >= Stage.Respected;
        }
        return true;
    }
References CurrentStage, EClass.debug, and CoreDebug.inviteAnytime.
Referenced by DramaCustomSequence.Build(), and AI_Fuck.Finish().
CanMarry()
bool Affinity.CanMarry () inline
Definition at line 68 of file Affinity.cs.
    {
        if (!EClass.debug.marryAnytime)
        {
            return CurrentStage >= Stage.Love;
        }
        return true;
    }
References CurrentStage, EClass.debug, and CoreDebug.marryAnytime.
CanSleepBeside()
bool Affinity.CanSleepBeside () inline
Definition at line 77 of file Affinity.cs.
    {
        if (!EClass.debug.marryAnytime)
        {
            return CurrentStage >= Stage.Fond;
        }
        return true;
    }
References CurrentStage, EClass.debug, and CoreDebug.marryAnytime.
Referenced by Chara.CanBloom(), Chara.GetSubPassData(), and TraitBed.TrySetAct().
Get()
static Affinity Affinity.Get (Chara c) inline static
Definition at line 36 of file Affinity.cs.
    {
        CC = c;
        foreach (Affinity item in list)
        {
            if (c._affinity < item.value)
            {
                return item;
            }
        }
        return list.LastItem();
    }
References CC, item, and list.
Referenced by Mod().
GetIcon()
Sprite Affinity.GetIcon () inline
Definition at line 107 of file Affinity.cs.
    {
        int affinity = CC._affinity;
        if (affinity <= -100)
        {
            return EClass.core.refs.icons.affnity.hate;
        }
        if (affinity <= -10)
        {
            return EClass.core.refs.icons.affnity.dontLike;
        }
        if (CurrentStage >= Stage.Love)
        {
            return EClass.core.refs.icons.affnity.love;
        }
        if (CurrentStage >= Stage.Respected)
        {
            return EClass.core.refs.icons.affnity.like;
        }
        return null;
    }
References Chara._affinity, CoreRef.Icons.affnity, CC, EClass.core, CurrentStage, CoreRef.Icons.Affinity.dontLike, CoreRef.Icons.Affinity.hate, CoreRef.icons, CoreRef.Icons.Affinity.like, CoreRef.Icons.Affinity.love, and Core.refs.
Referenced by BaseListPeople.OnInstantiate().
GetLunchChance()
int Affinity.GetLunchChance () inline
Definition at line 86 of file Affinity.cs.
    {
        if (!EClass.debug.enable)
        {
            if (CurrentStage < Stage.LoveLoveLove)
            {
                if (CurrentStage < Stage.LoveLove)
                {
                    if (CurrentStage < Stage.Love)
                    {
                        return 0;
                    }
                    return 10;
                }
                return 40;
            }
            return 80;
        }
        return 100;
    }
References CurrentStage, EClass.debug, and CoreDebug.enable.
Referenced by LayerSleep.Advance(), and Chara.ModAffinity().
Mod()
int Affinity.Mod (int a) inline
Definition at line 192 of file Affinity.cs.
    {
        if (a < 0)
        {
            CC._affinity += a;
            return a;
        }
        int num = 0;
        for (int i = 0; i < a; i++)
        {
            Affinity affinity = Get(CC);
            if (EClass.rnd(100 + affinity.difficulty) < 100)
            {
                CC._affinity++;
                num++;
            }
        }
        return num;
    }
References Chara._affinity, CC, difficulty, Get(), and EClass.rnd().
Referenced by Chara.ModAffinity().
OnGift()
Thing Affinity.OnGift (Thing t) inline
Definition at line 129 of file Affinity.cs.
    {
        t.CheckJustCooked();
        Thing result = CC.AddThing(t.Thing);
        EClass.pc.PlaySound("build_resource");
        int num = 0;
        bool flag = t.HasTag(CTAG.gift);
        if (t.trait is TraitFoodChuryu && CC.IsCat)
        {
            flag = true;
        }
        bool flag2 = t.category.IsChildOf(CC.GetFavCat());
        bool flag3 = t.id == CC.GetFavFood().id;
        if (EClass.debug.alwaysFavFood && t.trait is TraitFood)
        {
            flag3 = true;
        }
        num = Mathf.Clamp(t.GetPrice() / (flag3 ? 10 : (flag2 ? 20 : 200)), 0, 50) + (flag3 ? 20 : (flag2 ? 5 : 0));
        num = num * (100 + (t.HasElement(757) ? 50 : 0)) / (100 + CC.LV * 10);
        if (flag)
        {
            num += 100;
            CC.Say("give_ring", CC);
            CC.Talk("thanks3");
        }
        else if (flag3 || num > 20)
        {
            CC.Talk("thanks3");
        }
        else if (flag2 || num > 10)
        {
            CC.Talk("thanks");
        }
        else
        {
            CC.Talk("thanks2");
        }
        CC.ModAffinity(EClass.pc, num);
        return result;
    }
References Card.AddThing(), CoreDebug.alwaysFavFood, Card.category, CC, Card.CheckJustCooked(), EClass.debug, Chara.GetFavCat(), Chara.GetFavFood(), Card.GetPrice(), Card.HasElement(), Card.HasTag(), Chara.IsCat, Chara.ModAffinity(), EClass.pc, Card.PlaySound(), Card.Say(), Card.Talk(), Card.Thing, and Card.trait.
Referenced by Chara.GiveGift().
OnTalkRumor()
void Affinity.OnTalkRumor () inline
Definition at line 170 of file Affinity.cs.
    {
        bool flag = EClass.rnd(60 + EClass.pc.CHA * 2 + EClass.pc.Evalue(291) * 3) > 50 + difficulty + EClass.rnd(CC.CHA + 1);
        if (!EClass.debug.unlimitedInterest)
        {
            CC.interest -= 10 + EClass.rnd(10);
        }
        if (CC.IsPCFactionOrMinion && CurrentStage >= Stage.Love)
        {
            if (EClass.rnd(4) == 0)
            {
                CC.ModAffinity(EClass.pc, flag ? 1 : 0, show: false);
                EClass.pc.ModExp(291, 5);
            }
        }
        else
        {
            CC.ModAffinity(EClass.pc, flag ? (EClass.rnd(4) + 1) : (-EClass.rnd(4) - 1), show: false);
            EClass.pc.ModExp(291, 20);
        }
    }
References CC, Card.CHA, CurrentStage, EClass.debug, difficulty, Card.Evalue(), Card.IsPCFactionOrMinion, Chara.ModAffinity(), Card.ModExp(), EClass.pc, EClass.rnd(), and CoreDebug.unlimitedInterest.
Referenced by DramaCustomSequence.Build().
Member Data Documentation
CC
Chara Affinity.CC static
Definition at line 24 of file Affinity.cs.
Referenced by Get(), GetIcon(), Mod(), OnGift(), and OnTalkRumor().
difficulty
int Affinity.difficulty
Definition at line 28 of file Affinity.cs.
Referenced by Mod(), and OnTalkRumor().
value
int Affinity.value
Definition at line 26 of file Affinity.cs.
Referenced by Card.GetAffinityExpBonus(), and Hobby.GetEfficiency().
Property Documentation
CurrentStage
Stage Affinity.CurrentStage get
Definition at line 32 of file Affinity.cs.
Referenced by CanForceTradeEquip(), CanGiveCard(), CanInvite(), CanMarry(), CanSleepBeside(), TraitToolBrush.GetHeldEmo(), GetIcon(), GetLunchChance(), OnTalkRumor(), and AI_Fuck.Run().
list
List<Affinity> Affinity.list static get
Definition at line 30 of file Affinity.cs.
Referenced by Get().
Name
string Affinity.Name get
Definition at line 34 of file Affinity.cs.
Referenced by WindowChara.RefreshNote(), and DramaActor.Talk().
The documentation for this class was generated from the following file:
Elin/Affinity.cs