Elin Decompiled Documentation: Widget Class Reference
Widget Class Reference
Classes
class Config
class Meta
Public Types
enum WidgetType { Default , ZoomMenu }
enum State { Active , Inactive }
Public Member Functions
void Test ()
bool IsInRightMode ()
void Activate ()
virtual void OnActivate ()
virtual object CreateExtra ()
void Deactivate ()
virtual void OnDeactivate ()
void Close ()
void Reactivate ()
virtual void OnManagerActivate ()
virtual void OnManagerDeactivate ()
void SetAnchor (RectPosition p)
void SetPivot (RectPosition p)
virtual void OnChangePivot ()
void UpdateConfig ()
virtual void OnUpdateConfig ()
void ClampToScreen ()
virtual void OnChangeResolution ()
void OnChangePosition ()
virtual void OnChangeActionMode ()
virtual void OnFlip ()
bool IsAlignTop ()
Layer AddLayer (Layer l, Transform trans)
void RefreshTipPivotPosition ()
SkinSet GetSkin ()
SkinConfig GetSkinConfig ()
void SetSkin (int id, int v=0)
void TestSkin ()
virtual void ApplySkin ()
virtual void OnApplySkin ()
void InstantiateDeco (SkinDeco deco)
void AddDeco (SkinDeco deco)
void RemoveDeco (SkinDeco deco)
virtual bool CanShowContextMenu ()
void ShowContextMenu ()
void SetBaseContextMenu (UIContextMenu m)
virtual void OnSetContextMenu (UIContextMenu m)
void SetGridContextMenu (UIContextMenu m)
void SoundActivate ()
Public Attributes
Image imageBG
SoundData soundActivate
UIDragPanel dragPanel
RectTransform tipPivotLeft
RectTransform tipPivotRight
Protected Member Functions
void ClampToScreenEnsured (Component c, Vector2 anchoredPos)
void ClampToScreen (RectTransform rect, float margin=10f)
Protected Attributes
bool flip
Properties
string ID [get]
Widget.Config config [get]
SkinRoot skinRoot [get]
bool IsSealed [get]
virtual bool ShowStyleMenu [get]
virtual bool AlwaysTop [get]
virtual bool IsStaticPosition [get]
virtual bool AlwaysBottom [get]
virtual Type SetSiblingAfter [get]
virtual bool ShowInBuildMode [get]
virtual bool RightClickToClose [get]
virtual bool AllowRightClickToClose [get]
Properties inherited from EMono
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SoundManager Sound [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static CoreDebug debug [get]
Private Attributes
string _ID
Widget.Config _config
RectTransform _rect
SkinRoot _skinRoot
GameObject goCover
Additional Inherited Members
Static Public Member Functions inherited from EMono
static int rnd (int a)
Static Public Attributes inherited from EMono
static Core core
Detailed Description
Definition at line 7 of file Widget.cs.
Member Enumeration Documentation
State
enum Widget.State
Enumerator
Active
Inactive
Definition at line 774 of file Widget.cs.
    {
        Active,
        Inactive
    }
WidgetType
enum Widget.WidgetType
Enumerator
Default
ZoomMenu
Definition at line 679 of file Widget.cs.
    {
        Default,
        ZoomMenu
    }
Member Function Documentation
Activate()
void Widget.Activate () inline
Definition at line 128 of file Widget.cs.
    {
        this._rect = this.Rect();
        this.config.state = Widget.State.Active;
        if (this.config.extra == null)
        {
            this.config.extra = this.CreateExtra();
        }
        if (!this.dragPanel)
        {
            this.dragPanel = base.GetComponentInChildren<UIDragPanel>();
        }
        if (this.IsStaticPosition)
        {
            this.dragPanel.enable = false;
        }
        else
        {
            this.dragPanel.autoAnchor = (this.config.userAnchor == RectPosition.Auto);
            if (this.config.userAnchor != RectPosition.Auto)
            {
                this._rect.SetAnchor(this.config.userAnchor);
            }
            else
            {
                this._rect.SetAnchor(this.config.anchor);
            }
            this._rect.anchoredPosition = new Vector2(this.config.x, this.config.y);
            this.dragPanel.onDrag = new Action(this.OnChangePosition);
        }
        this.SetPivot(this.config.pivot);
        this.OnActivate();
        if (this == null)
        {
            return;
        }
        this.flip = (this._rect.position.x > (float)Screen.width * 0.5f);
        this.OnFlip();
        this.OnChangePosition();
        this.ClampToScreen();
        foreach (SkinDeco deco in this.config.skin.decos)
        {
            this.InstantiateDeco(deco);
        }
    }
References _rect, ClampToScreen(), config, CreateExtra(), dragPanel, InstantiateDeco(), IsStaticPosition, OnActivate(), OnChangePosition(), OnFlip(), and SetPivot().
Referenced by WidgetManager.ActivateWidget().
AddDeco()
void Widget.AddDeco (SkinDeco deco) inline
Definition at line 455 of file Widget.cs.
    {
        this.config.skin.decos.Add(deco);
        this.InstantiateDeco(deco);
    }
References config, and InstantiateDeco().
Referenced by LayerSkinDeco.OnUpdateInput().
AddLayer()
Layer Widget.AddLayer (Layer l, Transform trans) inline
Definition at line 361 of file Widget.cs.
    {
        l.OnBeforeAddLayer();
        l.gameObject.SetActive(true);
        l.transform.SetParent(trans, false);
        l.Init();
        l.OnAfterAddLayer();
        Window window = l.windows[0];
        RectTransform rectTransform = l.Rect();
        RectTransform rectTransform2 = window.Rect();
        rectTransform.sizeDelta = window.Rect().sizeDelta;
        rectTransform.SetPivot(0.5f, 0.5f);
        rectTransform.SetAnchor(0.5f, 0.5f, 0.5f, 0.5f);
        rectTransform2.SetPivot(0.5f, 0.5f);
        rectTransform2.SetAnchor(0.5f, 0.5f, 0.5f, 0.5f);
        rectTransform2.anchoredPosition = Vector2.zero;
        window.setting.allowMove = (window.setting.allowResize = false);
        window.setting.saveWindow = false;
        window.bgCollider.SetActive(false);
        return l;
    }
ApplySkin()
virtual void Widget.ApplySkin () inline virtual
Definition at line 425 of file Widget.cs.
    {
        SkinRoot component = base.GetComponent<SkinRoot>();
        if (!component)
        {
            return;
        }
        component.Reset();
        IUISkin[] componentsInChildren = base.GetComponentsInChildren<IUISkin>(true);
        for (int i = 0; i < componentsInChildren.Length; i++)
        {
            componentsInChildren[i].ApplySkin();
        }
        this.OnApplySkin();
    }
References OnApplySkin().
Referenced by WidgetCurrentTool.OnActivate(), BaseWidgetNotice.OnSetContextMenu(), WidgetInspector.OnSetContextMenu(), WidgetMenuPanel.OnSetContextMenu(), WidgetRoster.OnSetContextMenu(), WidgetSideMenu.OnSetContextMenu(), WidgetSticky.OnSetContextMenu(), SetBaseContextMenu(), SetGridContextMenu(), SetSkin(), and TestSkin().
CanShowContextMenu()
virtual bool Widget.CanShowContextMenu () inline virtual
Reimplemented in WidgetCurrentTool, WidgetEquip, and WidgetHotbar.
Definition at line 467 of file Widget.cs.
    {
        return true;
    }
Referenced by ActionMode.TryShowWidgetMenu().
ClampToScreen() [1/2]
void Widget.ClampToScreen () inline
Definition at line 309 of file Widget.cs.
    {
        this.ClampToScreen(this.Rect(), 10f);
    }
References ClampToScreen().
Referenced by Activate(), ClampToScreen(), ClampToScreenEnsured(), OnChangeResolution(), WidgetHotbar.OnSetContextMenu(), and SetPivot().
ClampToScreen() [2/2]
void Widget.ClampToScreen (RectTransform rect, float margin = 10f) inline protected
Definition at line 314 of file Widget.cs.
    {
        if (this.IsStaticPosition || this.config.userAnchor != RectPosition.Auto)
        {
            return;
        }
        Vector3 position = rect.position;
        Vector2 a = new Vector2(margin, margin);
        Vector2 a2 = new Vector2((float)Screen.width - margin, (float)Screen.height - margin);
        Vector3 vector = a - rect.rect.min;
        Vector3 vector2 = a2 - rect.rect.max;
        position.x = (float)((int)Mathf.Clamp(position.x, vector.x - 20f, vector2.x + 20f));
        position.y = (float)((int)Mathf.Clamp(position.y, vector.y - 20f, vector2.y + 20f));
        rect.position = position;
    }
References config, and IsStaticPosition.
ClampToScreenEnsured()
void Widget.ClampToScreenEnsured (Component c, Vector2 anchoredPos) inline protected
Definition at line 296 of file Widget.cs.
    {
        RectTransform rectTransform = c.Rect();
        rectTransform.anchoredPosition = anchoredPos;
        rectTransform.RebuildLayout(false);
        rectTransform.ForceUpdateRectTransforms();
        this.ClampToScreen(rectTransform, 10f);
        rectTransform.anchoredPosition = anchoredPos;
        rectTransform.RebuildLayout(false);
        rectTransform.ForceUpdateRectTransforms();
        this.ClampToScreen(rectTransform, 10f);
    }
References ClampToScreen().
Close()
void Widget.Close () inline
Definition at line 195 of file Widget.cs.
    {
        EMono.ui.widgets.DeactivateWidget(this);
    }
References EMono.ui.
Referenced by WidgetInspector.Hide(), WidgetTracker.Toggle(), ActionMode.TryRightClickCloseWidget(), and ActionMode.TryShowWidgetMenu().
CreateExtra()
virtual object Widget.CreateExtra () inline virtual
Reimplemented in WidgetBottomBar, WidgetCurrentTool, WidgetDate, WidgetEquip, WidgetExp, WidgetExpHome, WidgetFeed, WidgetHotbar, WidgetHP, WidgetInspector, WidgetMainText, WidgetMenuPanel, WidgetMinimap, WidgetNotice, WidgetRoster, WidgetSearch, WidgetSideScreen, WidgetStatsBar, WidgetSticky, and WidgetTracker.
Definition at line 178 of file Widget.cs.
    {
        return null;
    }
Referenced by Activate().
Deactivate()
void Widget.Deactivate () inline
Definition at line 183 of file Widget.cs.
    {
        this.OnDeactivate();
        this.config.state = Widget.State.Inactive;
        this.UpdateConfig();
        UnityEngine.Object.DestroyImmediate(base.gameObject);
    }
References OnDeactivate(), and UpdateConfig().
Referenced by WidgetManager.DeactivateWidget().
GetSkin()
SkinSet Widget.GetSkin () inline
Definition at line 396 of file Widget.cs.
    {
        return SkinManager.Instance.skinSets[this.config.skin.id];
    }
References config.
GetSkinConfig()
SkinConfig Widget.GetSkinConfig () inline
Definition at line 401 of file Widget.cs.
    {
        return this.config.skin;
    }
References config.
InstantiateDeco()
void Widget.InstantiateDeco (SkinDeco deco) inline
Definition at line 445 of file Widget.cs.
    {
        SkinDecoActor skinDecoActor = Util.Instantiate<SkinDecoActor>("UI/Widget/SkinDecoActor", base.transform);
        deco.actor = skinDecoActor;
        skinDecoActor.owner = deco;
        skinDecoActor.image.sprite = ResourceCache.Load<Sprite>("Media/Graphics/Deco/deco" + deco.id.ToString());
        skinDecoActor.Rect().anchoredPosition = new Vector2((float)deco.x, (float)deco.y);
        skinDecoActor.Refresh();
    }
Referenced by Activate(), and AddDeco().
IsAlignTop()
bool Widget.IsAlignTop () inline
Definition at line 355 of file Widget.cs.
    {
        RectPosition anchor = this.Rect().GetAnchor();
        return anchor == RectPosition.TopCenter || anchor == RectPosition.TopLEFT || anchor == RectPosition.TopRIGHT;
    }
IsInRightMode()
bool Widget.IsInRightMode () inline
Definition at line 123 of file Widget.cs.
    {
        return (EMono.scene.actionMode.ShowBuildWidgets && this.ShowInBuildMode) || this.config.IsInRightMode();
    }
References Scene.actionMode, config, IsInRightMode(), EMono.scene, and ActionMode.ShowBuildWidgets.
Referenced by IsInRightMode(), OnChangeActionMode(), and WidgetManager.Show().
OnActivate()
virtual void Widget.OnActivate () inline virtual
Reimplemented in BaseWidgetNotice, WidgetArtTool, WidgetBottomBar, WidgetCodex, WidgetCurrentTool, WidgetDate, WidgetDebug, WidgetEquip, WidgetExp, WidgetExpHome, WidgetFeed, WidgetHotbar, WidgetHP, WidgetInspector, WidgetMainText, WidgetMascot, WidgetMemo, WidgetMenuPanel, WidgetMinimap, WidgetMouseover, WidgetPopText, WidgetPopup, WidgetQuestTracker, WidgetRoster, WidgetSceneCustomizer, WidgetSearch, WidgetSideMenu, WidgetSideScreen, WidgetStatsBar, WidgetSticky, WidgetStockTracker, WidgetSystemIndicator, WidgetTracker, WidgetTutorial, and WidgetUnityChan.
Definition at line 174 of file Widget.cs.
    {
    }
Referenced by Activate().
OnApplySkin()
virtual void Widget.OnApplySkin () inline virtual
Reimplemented in BaseWidgetNotice, and WidgetStatsBar.
Definition at line 441 of file Widget.cs.
    {
    }
Referenced by ApplySkin().
OnChangeActionMode()
virtual void Widget.OnChangeActionMode () inline virtual
Reimplemented in WidgetHotbar.
Definition at line 346 of file Widget.cs.
    {
        this.SetActive(this.IsInRightMode());
    }
References IsInRightMode().
Referenced by WidgetManager.OnChangeActionMode().
OnChangePivot()
virtual void Widget.OnChangePivot () inline virtual
Reimplemented in WidgetDate.
Definition at line 280 of file Widget.cs.
    {
    }
Referenced by SetPivot().
OnChangePosition()
void Widget.OnChangePosition () inline
Definition at line 335 of file Widget.cs.
    {
        bool flag = this.Rect().position.x > (float)Screen.width * 0.5f;
        if (this.flip != flag)
        {
            this.flip = flag;
            this.OnFlip();
        }
        this.RefreshTipPivotPosition();
    }
References flip, OnFlip(), and RefreshTipPivotPosition().
Referenced by Activate(), and OnManagerActivate().
OnChangeResolution()
virtual void Widget.OnChangeResolution () inline virtual
Reimplemented in WidgetBottomBar, WidgetMainText, WidgetMenuPanel, and WidgetSideScreen.
Definition at line 330 of file Widget.cs.
    {
        this.ClampToScreen(this.Rect(), 10f);
    }
References ClampToScreen().
Referenced by WidgetRoster.Build().
OnDeactivate()
virtual void Widget.OnDeactivate () inline virtual
Reimplemented in WidgetFeed, WidgetInspector, WidgetMemo, and WidgetSearch.
Definition at line 191 of file Widget.cs.
    {
    }
Referenced by Deactivate().
OnFlip()
virtual void Widget.OnFlip () inline virtual
Reimplemented in BaseWidgetNotice, WidgetMascot, and WidgetSystemIndicator.
Definition at line 351 of file Widget.cs.
    {
    }
Referenced by Activate(), and OnChangePosition().
OnManagerActivate()
virtual void Widget.OnManagerActivate () inline virtual
Reimplemented in WidgetMouseover.
Definition at line 206 of file Widget.cs.
    {
        this.goCover = Util.Instantiate("UI/Widget/CoverWidget", base.transform).gameObject;
        RectTransform rectTransform = this.goCover.transform.Rect();
        RectTransform rectTransform2 = this.dragPanel.Rect();
        rectTransform.pivot = rectTransform2.pivot;
        rectTransform.anchorMin = rectTransform2.anchorMin;
        rectTransform.anchorMax = rectTransform2.anchorMax;
        rectTransform.anchoredPosition = rectTransform2.anchoredPosition;
        rectTransform.sizeDelta = rectTransform2.sizeDelta;
        UIDragPanel componentInChildren = this.goCover.GetComponentInChildren<UIDragPanel>();
        componentInChildren.autoAnchor = (this.config.userAnchor == RectPosition.Auto);
        componentInChildren.onDrag = new Action(this.OnChangePosition);
        componentInChildren.container = this.dragPanel.container;
        componentInChildren.target = this.dragPanel.target;
        componentInChildren.bound = this.dragPanel.bound;
        if (this is WidgetSideScreen)
        {
            componentInChildren.enable = false;
        }
        this.goCover.GetComponentInChildren<UIText>().SetText(("Widget" + this.ID).lang());
    }
References dragPanel, goCover, ID, and OnChangePosition().
Referenced by WidgetManager.ActivateWidget().
OnManagerDeactivate()
virtual void Widget.OnManagerDeactivate () inline virtual
Reimplemented in WidgetMouseover.
Definition at line 229 of file Widget.cs.
    {
        UnityEngine.Object.DestroyImmediate(this.goCover);
    }
References goCover.
Referenced by LayerWidget.OnKill().
OnSetContextMenu()
virtual void Widget.OnSetContextMenu (UIContextMenu m) inline virtual
Reimplemented in BaseWidgetNotice, WidgetBottomBar, WidgetCurrentTool, WidgetDate, WidgetEquip, WidgetFeed, WidgetHotbar, WidgetHP, WidgetInspector, WidgetMainText, WidgetMascot, WidgetMenuPanel, WidgetMinimap, WidgetNotice, WidgetRoster, WidgetSideMenu, WidgetSideScreen, WidgetStatsBar, WidgetSticky, WidgetTracker, and WidgetUnityChan.
Definition at line 596 of file Widget.cs.
    {
        this.SetBaseContextMenu(m);
    }
References SetBaseContextMenu().
Referenced by ShowContextMenu().
OnUpdateConfig()
virtual void Widget.OnUpdateConfig () inline virtual
Reimplemented in WidgetMemo.
Definition at line 292 of file Widget.cs.
    {
    }
Referenced by UpdateConfig().
Reactivate()
void Widget.Reactivate () inline
Definition at line 200 of file Widget.cs.
    {
        EMono.ui.widgets.DeactivateWidget(this);
        EMono.ui.widgets.ActivateWidget(this.config);
    }
References config, and EMono.ui.
RefreshTipPivotPosition()
void Widget.RefreshTipPivotPosition () inline
Definition at line 383 of file Widget.cs.
    {
        bool flag = (float)(Screen.width / 2 - 40) > base.transform.position.x;
        if (this.tipPivotLeft)
        {
            this.tipPivotLeft.SetActive(!flag || !this.tipPivotRight);
        }
        if (this.tipPivotRight)
        {
            this.tipPivotRight.SetActive(flag || !this.tipPivotLeft);
        }
    }
References tipPivotLeft, and tipPivotRight.
Referenced by OnChangePosition().
RemoveDeco()
void Widget.RemoveDeco (SkinDeco deco) inline
Definition at line 461 of file Widget.cs.
    {
        this.config.skin.decos.Remove(deco);
        UnityEngine.Object.DestroyImmediate(deco.actor.gameObject);
    }
References config.
Referenced by LayerSkinDeco.OnUpdateInput().
SetAnchor()
void Widget.SetAnchor (RectPosition p) inline
Definition at line 234 of file Widget.cs.
    {
        this.config.userAnchor = p;
        this.dragPanel.autoAnchor = (p == RectPosition.Auto);
        this._rect.SetAnchor(p);
    }
References _rect.
Referenced by SetBaseContextMenu().
SetBaseContextMenu()
void Widget.SetBaseContextMenu (UIContextMenu m) inline
Definition at line 479 of file Widget.cs.
    {
        UIContextMenu uicontextMenu = m.AddChild("anchor");
        SkinConfig cfg = this.config.skin;
        using (List<RectPosition>.Enumerator enumerator = Util.EnumToList<RectPosition>().GetEnumerator())
        {
            while (enumerator.MoveNext())
            {
                RectPosition p = enumerator.Current;
                uicontextMenu.AddButton(((this.config.userAnchor == p) ? " " : "") + p.ToString().lang(), delegate()
                {
                    this.SetAnchor(p);
                    SE.ClickGeneral();
                    m.Hide();
                }, true);
            }
        }
        uicontextMenu = m.AddChild("pivot");
        using (List<RectPosition>.Enumerator enumerator = Util.EnumToList<RectPosition>().GetEnumerator())
        {
            while (enumerator.MoveNext())
            {
                RectPosition p = enumerator.Current;
                uicontextMenu.AddButton(((this.config.pivot == p) ? " " : "") + p.ToString().lang(), delegate()
                {
                    this.SetPivot(p);
                    SE.ClickGeneral();
                    m.Hide();
                }, true);
            }
        }
        UIContextMenuItem sliderB = null;
        Action Refresh = delegate()
        {
            int num = EMono.ui.skins.skinSets[cfg.id].bgs.Count - 1;
            sliderB.slider.maxValue = (float)num;
            sliderB.slider.value = (float)cfg.bg;
            sliderB.textSlider.text = cfg.bg.ToString() + "/" + (EMono.ui.skins.skinSets[cfg.id].bgs.Count - 1).ToString();
        };
        if (this.ShowStyleMenu)
        {
            UIContextMenu uicontextMenu2 = m.AddOrGetChild("style");
            sliderB = uicontextMenu2.AddSlider("changeBG", (float n) => n.ToString() + "/" + (EMono.ui.skins.skinSets[cfg.id].bgs.Count - 1).ToString(), (float)cfg.bg, delegate(float a)
            {
                this.SetSkin(cfg.id, (int)a);
                Refresh();
            }, 0f, (float)(EMono.ui.skins.skinSets[cfg.id].bgs.Count - 1), true, true, false);
            uicontextMenu2.AddSlider("bgSize", (float n) => n.ToString() ?? "", (float)cfg.bgSize, delegate(float a)
            {
                cfg.bgSize = (int)a;
                this.ApplySkin();
            }, -50f, 50f, true, true, false);
            Action<PickerState, Color> <>9__13;
            uicontextMenu2.AddButton("colorBG", delegate()
            {
                if (EMono.ui.skins.skinSets[cfg.id].bgs[cfg.bg].redirect != SkinAssetRedirect.None)
                {
                    SE.Beep();
                    return;
                }
                LayerColorPicker layerColorPicker = EMono.ui.AddLayer<LayerColorPicker>();
                Color bgColor = cfg.bgColor;
                Color color = EMono.ui.skins.skinSets[cfg.id].bgs[cfg.bg].color;
                Action<PickerState, Color> onChangeColor;
                if ((onChangeColor = <>9__13) == null)
                {
                    onChangeColor = (<>9__13 = delegate(PickerState state, Color _c)
                    {
                        cfg.bgColor = _c;
                        this.ApplySkin();
                    });
                }
                layerColorPicker.SetColor(bgColor, color, onChangeColor);
            }, true);
            uicontextMenu2.AddButton("editDeco", delegate()
            {
                EMono.ui.AddLayer<LayerSkinDeco>().SetWidget(this);
            }, true);
        }
        if (this.AllowRightClickToClose)
        {
            m.AddToggle("RC_widget", this.config.RC, delegate(bool a)
            {
                this.config.RC = a;
            });
        }
        m.AddButton(() => (this.config.locked ? "unlockWidget" : "lockWidget").lang(), delegate()
        {
            EMono.ui.widgets.ToggleLock(this.config);
            SE.ClickGeneral();
            m.Hide();
            LayerWidget layer = EMono.ui.GetLayer<LayerWidget>(false);
            if (layer == null)
            {
                return;
            }
            layer.Refresh();
        });
        if (!this.IsSealed)
        {
            m.AddButton("closeWidget", delegate()
            {
                if (this is WidgetQuestTracker)
                {
                    EMono.player.questTracker = false;
                }
                EMono.ui.widgets.DeactivateWidget(this);
                LayerWidget layer = EMono.ui.GetLayer<LayerWidget>(false);
                if (layer == null)
                {
                    return;
                }
                layer.Refresh();
            }, true);
        }
    }
References AllowRightClickToClose, ApplySkin(), Color, config, IsSealed, LayerWidget.Refresh(), SetAnchor(), LayerColorPicker.SetColor(), SetPivot(), SetSkin(), ShowStyleMenu, and EMono.ui.
Referenced by OnSetContextMenu().
SetGridContextMenu()
void Widget.SetGridContextMenu (UIContextMenu m) inline
Definition at line 601 of file Widget.cs.
    {
        SkinConfig cfg = this.config.skin;
        m.AddSlider("skinGrid", (float n) => n.ToString() ?? "", (float)cfg.grid, delegate(float a)
        {
            cfg.grid = (int)a;
            cfg.gridColor = cfg.Grid.color;
            this.ApplySkin();
        }, 0f, (float)(cfg.Skin.bgGrid.Count - 1), true, true, false);
        Action<PickerState, Color> <>9__3;
        m.AddButton("colorGrid", delegate()
        {
            LayerColorPicker layerColorPicker = EMono.ui.AddLayer<LayerColorPicker>();
            Color gridColor = cfg.gridColor;
            Color color = cfg.Grid.color;
            Action<PickerState, Color> onChangeColor;
            if ((onChangeColor = <>9__3) == null)
            {
                onChangeColor = (<>9__3 = delegate(PickerState state, Color _c)
                {
                    cfg.gridColor = _c;
                    this.ApplySkin();
                });
            }
            layerColorPicker.SetColor(gridColor, color, onChangeColor);
        }, true);
    }
References ApplySkin(), Color, config, LayerColorPicker.SetColor(), and EMono.ui.
SetPivot()
void Widget.SetPivot (RectPosition p) inline
Definition at line 241 of file Widget.cs.
    {
        this.config.pivot = p;
        RectTransform rectTransform = this.Rect();
        Vector3 position = base.transform.position;
        switch (p)
        {
        case RectPosition.TopLEFT:
            rectTransform.pivot = new Vector2(0f, 1f);
            goto IL_126;
        case RectPosition.TopCenter:
            rectTransform.pivot = new Vector2(0.5f, 1f);
            goto IL_126;
        case RectPosition.TopRIGHT:
            rectTransform.pivot = new Vector2(1f, 1f);
            goto IL_126;
        case RectPosition.Left:
            rectTransform.pivot = new Vector2(0f, 0.5f);
            goto IL_126;
        case RectPosition.Right:
            rectTransform.pivot = new Vector2(1f, 0.5f);
            goto IL_126;
        case RectPosition.BottomLEFT:
            rectTransform.pivot = new Vector2(0f, 0f);
            goto IL_126;
        case RectPosition.BottomCenter:
            rectTransform.pivot = new Vector2(0.5f, 0f);
            goto IL_126;
        case RectPosition.BottomRIGHT:
            rectTransform.pivot = new Vector2(1f, 0f);
            goto IL_126;
        }
        rectTransform.pivot = new Vector2(0.5f, 0.5f);
        IL_126:
        base.transform.position = position;
        this.OnChangePivot();
        this.ClampToScreen();
    }
References ClampToScreen(), and OnChangePivot().
Referenced by Activate(), and SetBaseContextMenu().
SetSkin()
void Widget.SetSkin (int id, int v = 0) inline
Definition at line 406 of file Widget.cs.
    {
        SkinConfig skin = this.config.skin;
        if (skin.id != id)
        {
            skin.SetID(id);
        }
        skin.id = id;
        skin.bg = v;
        skin.bgColor = skin.BG.color;
        this.ApplySkin();
    }
References ApplySkin(), and config.
Referenced by SetBaseContextMenu().
ShowContextMenu()
void Widget.ShowContextMenu () inline
Definition at line 472 of file Widget.cs.
    {
        UIContextMenu uicontextMenu = EMono.ui.CreateContextMenu("ContextMenu");
        this.OnSetContextMenu(uicontextMenu);
        uicontextMenu.Show();
    }
References OnSetContextMenu(), and EMono.ui.
Referenced by HotItem.OnRightClick(), WidgetHotbar.OnSetContextMenu(), LayerWidget.OnUpdateInput(), and ActionMode.TryShowWidgetMenu().
SoundActivate()
void Widget.SoundActivate () inline
Definition at line 629 of file Widget.cs.
    {
        EMono.Sound.Play(this.soundActivate);
    }
References EMono.Sound, and soundActivate.
Referenced by AM_Adv._OnUpdateInput(), ActionMode.DoFunc(), HotItemWidget.OnClick(), LayerWidget.OnInit(), and WidgetQuestTracker.TryShow().
Test()
void Widget.Test () inline
Definition at line 9 of file Widget.cs.
    {
    }
TestSkin()
void Widget.TestSkin () inline
Definition at line 419 of file Widget.cs.
    {
        this.config.skin.SetID();
        this.ApplySkin();
    }
References ApplySkin(), and config.
UpdateConfig()
void Widget.UpdateConfig () inline
Definition at line 284 of file Widget.cs.
    {
        this.config.anchor = this._rect.GetAnchor();
        this.config.x = this._rect.anchoredPosition.x;
        this.config.y = this._rect.anchoredPosition.y;
        this.OnUpdateConfig();
    }
References _rect, and OnUpdateConfig().
Referenced by Deactivate(), and WidgetManager.UpdateConfigs().
Member Data Documentation
_config
Widget.Config Widget._config private
Definition at line 636 of file Widget.cs.
_ID
string Widget._ID private
Definition at line 634 of file Widget.cs.
_rect
RectTransform Widget._rect private
Definition at line 644 of file Widget.cs.
Referenced by Activate(), SetAnchor(), and UpdateConfig().
_skinRoot
SkinRoot Widget._skinRoot private
Definition at line 650 of file Widget.cs.
dragPanel
UIDragPanel Widget.dragPanel
Definition at line 642 of file Widget.cs.
Referenced by Activate(), OnManagerActivate(), WidgetManager.RefreshWidget(), and WidgetHotbar.SetVisible().
flip
bool Widget.flip protected
Definition at line 652 of file Widget.cs.
Referenced by OnChangePosition(), BaseWidgetNotice.OnFlip(), WidgetMascot.OnFlip(), and WidgetSystemIndicator.OnFlip().
goCover
GameObject Widget.goCover private
Definition at line 654 of file Widget.cs.
Referenced by OnManagerActivate(), and OnManagerDeactivate().
imageBG
Image Widget.imageBG
Definition at line 638 of file Widget.cs.
Referenced by WidgetHotbar.ToggleVisible().
soundActivate
SoundData Widget.soundActivate
Definition at line 640 of file Widget.cs.
Referenced by SoundActivate().
tipPivotLeft
RectTransform Widget.tipPivotLeft
Definition at line 646 of file Widget.cs.
Referenced by RefreshTipPivotPosition().
tipPivotRight
RectTransform Widget.tipPivotRight
Definition at line 648 of file Widget.cs.
Referenced by RefreshTipPivotPosition().
Property Documentation
AllowRightClickToClose
virtual bool Widget.AllowRightClickToClose get
Definition at line 115 of file Widget.cs.
    {
        get
        {
            return false;
        }
    }
Referenced by SetBaseContextMenu().
AlwaysBottom
virtual bool Widget.AlwaysBottom get
Definition at line 83 of file Widget.cs.
    {
        get
        {
            return false;
        }
    }
Referenced by WidgetManager.ActivateWidget(), and UI.CheckWindowOrder().
AlwaysTop
virtual bool Widget.AlwaysTop get
Definition at line 67 of file Widget.cs.
    {
        get
        {
            return false;
        }
    }
config
Widget.Config Widget.config get
Definition at line 25 of file Widget.cs.
    {
        get
        {
            Widget.Config result;
            if ((result = this._config) == null)
            {
                result = (this._config = EMono.player.widgets.dict[this.ID]);
            }
            return result;
        }
    }
Referenced by Activate(), AddDeco(), ClampToScreen(), GetSkin(), GetSkinConfig(), IsInRightMode(), Reactivate(), WidgetManager.RefreshWidget(), RemoveDeco(), SetBaseContextMenu(), SetGridContextMenu(), SetSkin(), and TestSkin().
ID
string Widget.ID get
Definition at line 13 of file Widget.cs.
    {
        get
        {
            if (this._ID == null)
            {
                return this._ID = base.name.Replace("Widget", "").Replace("(Clone)", "");
            }
            return this._ID;
        }
    }
Referenced by OnManagerActivate().
IsSealed
bool Widget.IsSealed get
Definition at line 51 of file Widget.cs.
    {
        get
        {
            return this.config.meta.system && !EMono.core.config.test.unsealWidgets;
        }
    }
Referenced by ButtonHotItem.RefreshItem(), and SetBaseContextMenu().
IsStaticPosition
virtual bool Widget.IsStaticPosition get
Definition at line 75 of file Widget.cs.
    {
        get
        {
            return false;
        }
    }
Referenced by Activate(), and ClampToScreen().
RightClickToClose
virtual bool Widget.RightClickToClose get
Definition at line 107 of file Widget.cs.
    {
        get
        {
            return this.config.RC;
        }
    }
Referenced by ActionMode.TryRightClickCloseWidget(), and ActionMode.TryShowWidgetMenu().
SetSiblingAfter
virtual Type Widget.SetSiblingAfter get
Definition at line 91 of file Widget.cs.
    {
        get
        {
            return null;
        }
    }
Referenced by WidgetManager.ActivateWidget().
ShowInBuildMode
virtual bool Widget.ShowInBuildMode get
Definition at line 99 of file Widget.cs.
    {
        get
        {
            return this.config.mode.HasFlag(GameMode.Build);
        }
    }
ShowStyleMenu
virtual bool Widget.ShowStyleMenu get
Definition at line 59 of file Widget.cs.
    {
        get
        {
            return true;
        }
    }
Referenced by SetBaseContextMenu().
skinRoot
SkinRoot Widget.skinRoot get
Definition at line 38 of file Widget.cs.
    {
        get
        {
            SkinRoot result;
            if ((result = this._skinRoot) == null)
            {
                result = (this._skinRoot = base.GetComponent<SkinRoot>());
            }
            return result;
        }
    }
The documentation for this class was generated from the following file:
Elin/Widget.cs