Elin Decompiled Documentation: CustomSourceContent Class Reference
CustomSourceContent Class Reference
Static Public Member Functions
static string string string[] kv GetParams (string tag)
Static Public Member Functions inherited from EClass
static int rndSeed (int a, int seed)
static int rnd (long a)
static int rnd (int a)
static int curve (long _a, int start, int step, int rate=75)
static int sqrt (int a)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Static Public Attributes
static string action
static string string spec
Static Public Attributes inherited from EClass
static Core core
Properties
virtual string SourceType [get]
string SourceId [get, set]
Properties inherited from CustomContent
string ContentId [get, protected set]
EMod Owner [get, protected set]
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Additional Inherited Members
Public Member Functions inherited from CustomContent
virtual void OnGameLoad (GameIOContext context)
virtual void OnGameSave (GameIOContext context)
override string ToString ()
Detailed Description
Definition at line 4 of file CustomSourceContent.cs.
Member Function Documentation
GetParams()
static string string string[] kv CustomSourceContent.GetParams (string tag) inline static
Definition at line 12 of file CustomSourceContent.cs.
    {
        if (tag.IsEmpty())
        {
            return (action: string.Empty, spec: string.Empty, kv: Array.Empty<string>());
        }
        int num = tag.IndexOf('(');
        string text;
        string text2;
        if (num >= 0)
        {
            text = tag[..num];
            text2 = tag.ExtractInBetween('(', ')');
        }
        else
        {
            text = tag.Split('_')[0];
            text2 = tag[text.Length..].TrimStart('_');
        }
        string[] item = text2.Split('=');
        return (action: text, spec: text2, kv: item);
    }
Referenced by CustomCharaContent.CreateFromRow(), CustomElementContent.CreateFromRow(), CustomThingContent.CreateFromRow(), and CustomZoneContent.CreateFromRow().
Member Data Documentation
action
string CustomSourceContent.action static
Definition at line 12 of file CustomSourceContent.cs.
spec
string string CustomSourceContent.spec static
Definition at line 12 of file CustomSourceContent.cs.
Property Documentation
SourceId
string CustomSourceContent.SourceId get set
Definition at line 10 of file CustomSourceContent.cs.
{ get; set; }
Referenced by CustomCharaContent.CreateFromRow(), CustomElementContent.CreateFromRow(), CustomMaterialContent.CreateFromRow(), CustomStatContent.CreateFromRow(), CustomThingContent.CreateFromRow(), and CustomZoneContent.CreateFromRow().
SourceType
virtual string CustomSourceContent.SourceType get
Definition at line 7 of file CustomSourceContent.cs.
{ get; }
The documentation for this class was generated from the following file:
Elin/CustomSourceContent.cs