Elin Decompiled Documentation: Element.BonusInfo Class Reference
Element.BonusInfo Class Reference
Public Member Functions
void AddText (int v, string text, string textBad=null)
void AddFix (int v, string text)
void WriteNote ()
void CheckFirst ()
void AddText (string text)
void AddText (int v, string text, string textBad=null)
void AddFix (int v, string text)
void WriteNote ()
Public Attributes
Element ele
UINote n
Chara c
bool first = true
int total
Detailed Description
Definition at line 919 of file Element.2.cs.
Member Function Documentation
AddFix() [1/2]
void Element.BonusInfo.AddFix (int v, string text) inline
Definition at line 948 of file Element.2.cs.
        {
            if (v == 0)
            {
                return;
            }
            if (this.first)
            {
                this.first = false;
                this.n.Space(8, 1);
            }
            this.n.AddText(string.Concat(new string[]
            {
                "_bullet".lang(),
                text,
                " ",
                (v > 0) ? "+" : "",
                v.ToString(),
                "%"
            }), (v > 0) ? FontColor.Good : FontColor.Bad);
        }
References Element.BonusInfo.first, and Element.BonusInfo.n.
Referenced by Element.BonusInfo.WriteNote().
AddFix() [2/2]
void Element.BonusInfo.AddFix (int v, string text) inline
Definition at line 119 of file ELEMENT.cs.
        {
            if (v != 0)
            {
                CheckFirst();
                n.AddText("_bullet".lang() + text + " " + ((v > 0) ? "+" : "") + v + "%", (v > 0) ? FontColor.Good : FontColor.Bad);
            }
        }
References Element.BonusInfo.CheckFirst(), and Element.BonusInfo.n.
AddText() [1/3]
void Element.BonusInfo.AddText (int v, string text, string textBad = null) inline
Definition at line 921 of file Element.2.cs.
        {
            if (v == 0)
            {
                return;
            }
            string text2 = text;
            if (!textBad.IsEmpty() && v < 0)
            {
                text2 = textBad;
            }
            if (this.first)
            {
                this.first = false;
                this.n.Space(8, 1);
            }
            this.total += v;
            this.n.AddText(string.Concat(new string[]
            {
                "_bullet".lang(),
                text2,
                " ",
                (v > 0) ? "+" : "",
                v.ToString()
            }), (v > 0) ? FontColor.Good : FontColor.Bad);
        }
References Element.BonusInfo.first, and Element.BonusInfo.n.
Referenced by Element.BonusInfo.WriteNote().
AddText() [2/3]
void Element.BonusInfo.AddText (int v, string text, string textBad = null) inline
Definition at line 104 of file ELEMENT.cs.
        {
            if (v != 0)
            {
                string text2 = text;
                if (!textBad.IsEmpty() && v < 0)
                {
                    text2 = textBad;
                }
                CheckFirst();
                total += v;
                n.AddText("_bullet".lang() + text2 + " " + ((v > 0) ? "+" : "") + v, (v > 0) ? FontColor.Good : FontColor.Bad);
            }
        }
References Element.BonusInfo.CheckFirst(), Element.BonusInfo.n, and Element.BonusInfo.total.
AddText() [3/3]
void Element.BonusInfo.AddText (string text) inline
Definition at line 98 of file ELEMENT.cs.
        {
            CheckFirst();
            n.AddText("_bullet".lang() + text, FontColor.Warning);
        }
References Element.BonusInfo.CheckFirst(), and Element.BonusInfo.n.
CheckFirst()
void Element.BonusInfo.CheckFirst () inline
Definition at line 89 of file ELEMENT.cs.
        {
            if (first)
            {
                first = false;
                n.Space(8);
            }
        }
References Element.BonusInfo.first, and Element.BonusInfo.n.
Referenced by Element.BonusInfo.AddFix(), and Element.BonusInfo.AddText().
WriteNote() [1/2]
void Element.BonusInfo.WriteNote () inline
Definition at line 970 of file Element.2.cs.
        {
            int id = this.ele.id;
            int num = 0;
            foreach (BodySlot bodySlot in this.c.body.slots)
            {
                if (bodySlot.elementId != 44 && bodySlot.thing != null && ((id != 67 && id != 66) || bodySlot.elementId != 35))
                {
                    Element orCreateElement = bodySlot.thing.elements.GetOrCreateElement(id);
                    if (orCreateElement != null && !orCreateElement.IsGlobalElement)
                    {
                        num += orCreateElement.Value;
                    }
                }
            }
            this.AddText(num, "equipment".lang(), null);
            if (this.c.IsPCFaction)
            {
                Element element = EClass.pc.faction.charaElements.GetElement(id);
                if (element != null)
                {
                    this.AddText(element.Value, "sub_faction".lang(), null);
                }
            }
            foreach (Condition condition in this.c.conditions)
            {
                if (condition.elements != null)
                {
                    this.AddText(condition.elements.Value(id), condition.Name, null);
                }
            }
            if (this.c.tempElements != null)
            {
                this.AddText(this.c.tempElements.Value(id), "tempStrengthen".lang(), "tempWeaken".lang());
            }
            try
            {
                if (this.c.faithElements != null)
                {
                    Element element2 = this.c.elements.GetElement("featGod_" + this.c.faith.id + "1");
                    if (element2 != null)
                    {
                        this.AddText(this.c.faithElements.Value(id), element2.Name, null);
                    }
                }
            }
            catch
            {
            }
            int value = this.ele.Value;
            int num2 = this.ele.ValueWithoutLink + this.total;
            foreach (Element element3 in this.c.elements.dict.Values)
            {
                if (element3.HasTag("multiplier") && element3.source.aliasRef == this.ele.source.alias)
                {
                    this.AddFix(element3.Value, element3.Name);
                }
            }
            if (id == 79)
            {
                this.c.RefreshSpeed(this);
            }
            if (this.c.race.IsMachine || this.c.id == "android")
            {
                int num3 = this.c.Evalue(664);
                if (num3 > 0)
                {
                    if (id - 64 <= 1)
                    {
                        this.AddFix(num3 / 2, EClass.sources.elements.map[664].GetName());
                        return;
                    }
                    if (id != 79)
                    {
                        return;
                    }
                    this.AddFix(num3, EClass.sources.elements.map[664].GetName());
                }
            }
        }
References Element.BonusInfo.AddFix(), Element.BonusInfo.AddText(), Chara.body, Element.BonusInfo.c, Faction.charaElements, Chara.conditions, ElementContainer.dict, Element.BonusInfo.ele, BodySlot.elementId, BaseCondition.elements, Card.elements, SourceManager.elements, Card.Evalue(), Chara.faction, Chara.faith, Chara.faithElements, ElementContainer.GetElement(), ElementContainer.GetOrCreateElement(), Element.HasTag(), Element.id, Religion.id, Element.IsGlobalElement, Chara.IsPCFaction, BaseCondition.Name, Element.Name, EClass.pc, Chara.race, Chara.RefreshSpeed(), CharaBody.slots, Element.source, EClass.sources, Chara.tempElements, BodySlot.thing, Element.BonusInfo.total, Element.Value, and ElementContainer.Value().
Referenced by Element._WriteNote().
WriteNote() [2/2]
void Element.BonusInfo.WriteNote () inline
Definition at line 128 of file ELEMENT.cs.
        {
            int id = ele.id;
            int num = 0;
            foreach (BodySlot slot in c.body.slots)
            {
                if (slot.elementId != 44 && slot.thing != null && ((id != 67 && id != 66) || slot.elementId != 35))
                {
                    Element orCreateElement = slot.thing.elements.GetOrCreateElement(id);
                    if (orCreateElement != null && !orCreateElement.IsGlobalElement)
                    {
                        num += orCreateElement.Value;
                    }
                }
            }
            AddText(num, "equipment".lang());
            if (c.IsPCFaction)
            {
                Element element = EClass.pc.faction.charaElements.GetElement(id);
                if (element != null)
                {
                    AddText(element.Value, "sub_faction".lang());
                }
            }
            foreach (Condition condition in c.conditions)
            {
                if (condition.elements != null)
                {
                    AddText(condition.elements.Value(id), condition.Name);
                }
            }
            if (c.tempElements != null)
            {
                AddText(c.tempElements.Value(id), "tempStrengthen".lang(), "tempWeaken".lang());
            }
            try
            {
                if (c.faithElements != null)
                {
                    Element element2 = c.elements.GetElement("featGod_" + c.faith.id + "1");
                    if (element2 != null)
                    {
                        AddText(c.faithElements.Value(id), element2.Name);
                    }
                }
            }
            catch
            {
            }
            _ = ele.Value;
            _ = ele.ValueWithoutLink + total;
            foreach (Element value in c.elements.dict.Values)
            {
                if (value.HasTag("multiplier") && value.source.aliasRef == ele.source.alias)
                {
                    AddFix(value.Value, value.Name);
                }
            }
            if (id == 79)
            {
                c.RefreshSpeed(this);
            }
            if (!c.race.IsMachine && !(c.id == "android"))
            {
                return;
            }
            int num2 = c.Evalue(664);
            if (num2 > 0)
            {
                switch (id)
                {
                case 64:
                case 65:
                    AddFix(num2 / 2, EClass.sources.elements.map[664].GetName());
                    break;
                case 79:
                    AddFix(num2, EClass.sources.elements.map[664].GetName());
                    break;
                }
            }
        }
References Element.BonusInfo.AddFix(), Element.BonusInfo.AddText(), Chara.body, Element.BonusInfo.c, Faction.charaElements, Chara.conditions, ElementContainer.dict, Element.BonusInfo.ele, BodySlot.elementId, BaseCondition.elements, Card.elements, SourceManager.elements, Card.Evalue(), Chara.faction, Chara.faith, Chara.faithElements, ElementContainer.GetElement(), ElementContainer.GetOrCreateElement(), Element.HasTag(), Card.id, Element.id, Religion.id, Element.IsGlobalElement, Chara.IsPCFaction, BaseCondition.Name, Element.Name, EClass.pc, Chara.race, Chara.RefreshSpeed(), CharaBody.slots, Element.source, EClass.sources, Chara.tempElements, BodySlot.thing, Element.BonusInfo.total, Element.Value, and ElementContainer.Value().
Member Data Documentation
c
Chara Element.BonusInfo.c
Definition at line 1055 of file Element.2.cs.
Referenced by Element.BonusInfo.WriteNote().
ele
Element Element.BonusInfo.ele
Definition at line 1051 of file Element.2.cs.
Referenced by Element.BonusInfo.WriteNote().
first
bool Element.BonusInfo.first = true
Definition at line 1057 of file Element.2.cs.
Referenced by Element.BonusInfo.AddFix(), Element.BonusInfo.AddText(), and Element.BonusInfo.CheckFirst().
n
UINote Element.BonusInfo.n
Definition at line 1053 of file Element.2.cs.
Referenced by Element.BonusInfo.AddFix(), Element.BonusInfo.AddText(), and Element.BonusInfo.CheckFirst().
total
int Element.BonusInfo.total
Definition at line 1059 of file Element.2.cs.
Referenced by Element.BonusInfo.AddText(), and Element.BonusInfo.WriteNote().
The documentation for this class was generated from the following files:
Elin/Element.2.cs
Elin/ELEMENT.cs