Elin Decompiled Documentation: ListPeopleBuySlave Class Reference
ListPeopleBuySlave Class Reference
Public Member Functions
override bool IsDisabled (Chara c)
override void OnCreate ()
override void OnInstantiate (Chara a, ItemGeneral b)
override void OnClick (Chara c, ItemGeneral i)
int Cost (Chara c)
override void OnList ()
Public Member Functions inherited from BaseListPeople
virtual bool IsDisabled (Chara c)
override void List ()
override void OnInstantiate (Chara a, ItemGeneral b)
void AddSubButtonWork (ItemGeneral b, Chara a)
void WriteHobbies (UITooltip t, Chara a, BaseArea roomWork)
virtual void SetSubText (Chara a, ItemGeneral b)
override void OnClick (Chara c, ItemGeneral i)
override void OnList ()
override void OnRefreshMenu ()
Public Member Functions inherited from ListOwner< Chara, ItemGeneral >
virtual void OnClick (T1 a, T2 b)
virtual void OnInstantiate (T1 a, T2 b)
virtual void OnList ()
virtual void List ()
virtual void OnCreate ()
virtual void OnSwitchContent ()
virtual void OnRefreshMenu ()
void RefreshTab ()
void MoveToOther (object c)
Properties
SlaverData data [get]
override LayerPeople.ShowMode ShowMode [get]
Properties inherited from BaseListPeople
new LayerPeople layer [get]
override string IdHeaderRow [get]
virtual bool ShowCharaSheet [get]
virtual bool ShowShowMode [get]
virtual LayerPeople.ShowMode ShowMode [get]
virtual bool ShowGoto [get]
virtual bool ShowHome [get]
Properties inherited from ListOwner< Chara, ItemGeneral >
ListOwner Main [get]
virtual string IdTitle [get]
virtual string IdHeaderRow [get]
virtual string TextTab [get]
virtual string TextHeader [get]
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Additional Inherited Members
Static Public Member Functions inherited from EClass
static int rndSeed (int a, int seed)
static int rnd (long a)
static int rnd (int a)
static int curve (int _a, int start, int step, int rate=75)
static int sqrt (int a)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Public Attributes inherited from BaseListPeople
Chara owner
FactionMemberType memberType
Public Attributes inherited from ListOwner< Chara, ItemGeneral >
Layer layer
Window window
UIMultiList multi
ListOwner other
UIList list
WindowMenu menu
Window.Setting.Tab tab
string textTab
string textHeader
bool main
int index
Static Public Attributes inherited from EClass
static Core core
Detailed Description
Definition at line 1 of file ListPeopleBuySlave.cs.
Member Function Documentation
Cost()
int ListPeopleBuySlave.Cost (Chara c) inline
Definition at line 34 of file ListPeopleBuySlave.cs.
    {
        return CalcMoney.BuySlave(c);
    }
References CalcMoney.BuySlave().
Referenced by OnInstantiate().
IsDisabled()
override bool ListPeopleBuySlave.IsDisabled (Chara c) inline virtual
Reimplemented from BaseListPeople.
Definition at line 7 of file ListPeopleBuySlave.cs.
    {
        return false;
    }
OnClick()
override void ListPeopleBuySlave.OnClick (Chara c, ItemGeneral i) inline
Definition at line 28 of file ListPeopleBuySlave.cs.
    {
        LayerPeople.slaveToBuy = c;
        base.layer.Close();
    }
OnCreate()
override void ListPeopleBuySlave.OnCreate () inline virtual
Reimplemented from ListOwner< Chara, ItemGeneral >.
Definition at line 12 of file ListPeopleBuySlave.cs.
    {
        if (data == null)
        {
            owner.SetObj(5, new SlaverData());
        }
        data.TryRefresh(owner);
    }
References data, BaseListPeople.owner, BaseCard.SetObj(), and SlaverData.TryRefresh().
OnInstantiate()
override void ListPeopleBuySlave.OnInstantiate (Chara a, ItemGeneral b) inline
Definition at line 21 of file ListPeopleBuySlave.cs.
    {
        base.OnInstantiate(a, b);
        int money = EClass.pc.GetCurrency();
        b.AddPrefab<UIItem>("costMoney").text1.SetText((Cost(a).ToString() ?? "").TagColorGoodBad(() => money >= Cost(a)));
    }
References Cost(), Card.GetCurrency(), money, and EClass.pc.
OnList()
override void ListPeopleBuySlave.OnList () inline virtual
Reimplemented from BaseListPeople.
Definition at line 39 of file ListPeopleBuySlave.cs.
    {
        foreach (Chara item in data.list)
        {
            list.Add(item);
        }
    }
References UIList.Add(), data, item, ListOwner< Chara, ItemGeneral >.list, and SlaverData.list.
Property Documentation
data
SlaverData ListPeopleBuySlave.data get
Definition at line 3 of file ListPeopleBuySlave.cs.
Referenced by OnCreate(), and OnList().
ShowMode
override LayerPeople.ShowMode ListPeopleBuySlave.ShowMode get
Definition at line 5 of file ListPeopleBuySlave.cs.
The documentation for this class was generated from the following file:
Elin/ListPeopleBuySlave.cs