Elin Decompiled Documentation: Applibot.DissolveImage Class Reference
Applibot.DissolveImage Class Reference
Protected Member Functions
override void UpdateMaterial (Material baseMaterial)
Protected Member Functions inherited from Applibot.CustomImageBase
virtual void UpdateMaterial (Material baseMaterial)
void OnEnable ()
void OnDisable ()
void OnDestroy ()
Private Attributes
Texture2D _dissovleTex
Color _glowColor
float _yAmount = 0.5f
float _yRange = 0.5f
float _dissolveRange
float _distortion = 0.1f
Vector2 _scroll = new Vector2(0f, 0f)
int _dissolveTexId = Shader.PropertyToID("_DissolveTex")
int _dissolveRangeId = Shader.PropertyToID("_DissolveRange")
int _yAmountId = Shader.PropertyToID("_YAmount")
int _yRangeId = Shader.PropertyToID("_YRange")
int _scrollId = Shader.PropertyToID("_Scroll")
int _glowColorId = Shader.PropertyToID("_GlowColor")
int _distortionId = Shader.PropertyToID("_Distortion")
Additional Inherited Members
Public Member Functions inherited from Applibot.CustomImageBase
Material GetModifiedMaterial (Material baseMaterial)
void DestroyMaterial ()
Protected Attributes inherited from Applibot.CustomImageBase
Material material
Properties inherited from Applibot.CustomImageBase
CanvasScaler canvasScaler [get]
Graphic graphic [get]
Detailed Description
Definition at line 5 of file DissolveImage.cs.
Member Function Documentation
UpdateMaterial()
override void Applibot.DissolveImage.UpdateMaterial (Material baseMaterial) inline protected virtual
Reimplemented from Applibot.CustomImageBase.
Definition at line 47 of file DissolveImage.cs.
    {
        if (material == null)
        {
            material = new Material(Shader.Find("Applibot/UI/Dissolve"));
            material.hideFlags = HideFlags.HideAndDontSave;
        }
        material.SetTexture(_dissolveTexId, _dissovleTex);
        material.SetFloat(_dissolveRangeId, _dissolveRange);
        material.SetFloat(_yAmountId, _yAmount);
        material.SetFloat(_yRangeId, _yRange);
        material.SetVector(_scrollId, _scroll);
        material.SetColor(_glowColorId, _glowColor);
        material.SetFloat(_distortionId, _distortion);
    }
References Applibot.DissolveImage._dissolveRange, Applibot.DissolveImage._dissolveRangeId, Applibot.DissolveImage._dissolveTexId, Applibot.DissolveImage._dissovleTex, Applibot.DissolveImage._distortion, Applibot.DissolveImage._distortionId, Applibot.DissolveImage._glowColor, Applibot.DissolveImage._glowColorId, Applibot.DissolveImage._scroll, Applibot.DissolveImage._scrollId, Applibot.DissolveImage._yAmount, Applibot.DissolveImage._yAmountId, Applibot.DissolveImage._yRange, Applibot.DissolveImage._yRangeId, Material, and Applibot.CustomImageBase.material.
Member Data Documentation
_dissolveRange
float Applibot.DissolveImage._dissolveRange private
Definition at line 24 of file DissolveImage.cs.
Referenced by Applibot.DissolveImage.UpdateMaterial().
_dissolveRangeId
int Applibot.DissolveImage._dissolveRangeId = Shader.PropertyToID("_DissolveRange") private
Definition at line 35 of file DissolveImage.cs.
Referenced by Applibot.DissolveImage.UpdateMaterial().
_dissolveTexId
int Applibot.DissolveImage._dissolveTexId = Shader.PropertyToID("_DissolveTex") private
Definition at line 33 of file DissolveImage.cs.
Referenced by Applibot.DissolveImage.UpdateMaterial().
_dissovleTex
Texture2D Applibot.DissolveImage._dissovleTex private
Definition at line 8 of file DissolveImage.cs.
Referenced by Applibot.DissolveImage.UpdateMaterial().
_distortion
float Applibot.DissolveImage._distortion = 0.1f private
Definition at line 28 of file DissolveImage.cs.
Referenced by Applibot.DissolveImage.UpdateMaterial().
_distortionId
int Applibot.DissolveImage._distortionId = Shader.PropertyToID("_Distortion") private
Definition at line 45 of file DissolveImage.cs.
Referenced by Applibot.DissolveImage.UpdateMaterial().
_glowColor
Color Applibot.DissolveImage._glowColor private
Definition at line 12 of file DissolveImage.cs.
Referenced by Applibot.DissolveImage.UpdateMaterial().
_glowColorId
int Applibot.DissolveImage._glowColorId = Shader.PropertyToID("_GlowColor") private
Definition at line 43 of file DissolveImage.cs.
Referenced by Applibot.DissolveImage.UpdateMaterial().
_scroll
Vector2 Applibot.DissolveImage._scroll = new Vector2(0f, 0f) private
Definition at line 31 of file DissolveImage.cs.
Referenced by Applibot.DissolveImage.UpdateMaterial().
_scrollId
int Applibot.DissolveImage._scrollId = Shader.PropertyToID("_Scroll") private
Definition at line 41 of file DissolveImage.cs.
Referenced by Applibot.DissolveImage.UpdateMaterial().
_yAmount
float Applibot.DissolveImage._yAmount = 0.5f private
Definition at line 16 of file DissolveImage.cs.
Referenced by Applibot.DissolveImage.UpdateMaterial().
_yAmountId
int Applibot.DissolveImage._yAmountId = Shader.PropertyToID("_YAmount") private
Definition at line 37 of file DissolveImage.cs.
Referenced by Applibot.DissolveImage.UpdateMaterial().
_yRange
float Applibot.DissolveImage._yRange = 0.5f private
Definition at line 20 of file DissolveImage.cs.
Referenced by Applibot.DissolveImage.UpdateMaterial().
_yRangeId
int Applibot.DissolveImage._yRangeId = Shader.PropertyToID("_YRange") private
Definition at line 39 of file DissolveImage.cs.
Referenced by Applibot.DissolveImage.UpdateMaterial().
The documentation for this class was generated from the following file:
Elin/Plugins.UI/Applibot/DissolveImage.cs