Elin Decompiled Documentation: ConTransmuteBat Class Reference
ConTransmuteBat Class Reference
Public Member Functions
override RendererReplacer GetRendererReplacer ()
override void Tick ()
void CheckSeen ()
override void OnStart ()
override void OnRemoved ()
override void Tick ()
override void OnStart ()
override void OnRemoved ()
Public Member Functions inherited from BaseBuff
override int GetPhase ()
override bool CanStack (Condition c)
Public Member Functions inherited from BaseDebuff
override bool ShouldOverride (Condition c)
override int GetPhase ()
override BaseNotification CreateNotification ()
Public Member Functions inherited from Condition
override BaseNotification CreateNotification ()
virtual void OnStacked (int p)
Condition SetPerfume (int duration=3)
override void Tick ()
virtual void OnCalculateFov (Fov fov, ref int radius, ref float power)
virtual void OnCreateFov (Fov fov)
override void OnValueChanged ()
void Kill (bool silent=false)
Public Member Functions inherited from BaseCondition
virtual bool CanStack (Condition c)
virtual bool ShouldOverride (Condition c)
virtual bool IsOverrideConditionMet (Condition c, int turn)
virtual bool TryMove (Point p)
virtual ElementContainer GetElementContainer ()
void SetElement (int id)
void SetRefVal (int a, int b)
virtual Color GetSpriteColor ()
override string ToString ()
override string GetText ()
override int GetValue ()
override Color GetColor (Gradient g)
virtual void SetOwner (Chara _owner, bool onDeserialize=false)
SourceElement.Row GetElementSource (int i)
void Start ()
bool TryNullify (Condition c)
virtual void OnBeforeStart ()
virtual void OnStart ()
virtual void OnStartOrStack ()
virtual void PlayEffect ()
virtual void PlayEndEffect ()
virtual void OnRefresh ()
void SetPhase ()
bool IsNullPhase ()
override int GetPhase ()
void PhaseMsg (bool inc)
override string GetPhaseStr ()
virtual void Tick ()
void Mod (int a, bool force=false)
virtual void OnValueChanged ()
virtual void OnChangePhase (int lastPhase, int newPhase)
virtual void OnRemoved ()
virtual int EvaluatePower (int p)
virtual int EvaluateTurn (int p)
virtual BaseNotification CreateNotification ()
Element GetDefenseAttribute (Chara c=null)
override void _WriteNote (UINote n, bool asChild=false)
virtual void OnWriteNote (List< string > list)
virtual RendererReplacer GetRendererReplacer ()
Public Member Functions inherited from BaseStats
virtual Color GetColor (Gradient gradient)
virtual Color GetColor (SkinColorProfile c)
Color GetColor ()
virtual string GetText ()
virtual string GetPhaseStr ()
virtual int GetValue ()
virtual int GetSortVal ()
virtual Sprite GetSprite ()
virtual void SetText (UIText t, SkinColorProfile cols=null)
virtual int GetPhase ()
void PopText ()
virtual void WriteNote (UINote n, Action< UINote > onWriteNote=null)
virtual void _WriteNote (UINote n, bool asChild=false)
Properties
override bool HasDuration [get]
override bool CanManualRemove [get]
Properties inherited from ConTransmute
override bool IsToggle [get]
override bool ShouldRefresh [get]
Properties inherited from BaseBuff
override bool CanManualRemove [get]
Properties inherited from Condition
virtual bool IsKilled [get]
virtual string TextDuration [get]
Properties inherited from BaseCondition
int value [get, set]
int power [get, set]
int refVal [get, set]
int refVal2 [get, set]
bool givenByPcParty [get, set]
bool isPerfume [get, set]
override Chara Owner [get]
virtual string Name [get]
virtual bool IsToggle [get]
virtual bool AllowMultipleInstance [get]
virtual bool ConsumeTurn [get]
virtual bool HasDuration [get]
virtual bool PreventRegen [get]
virtual bool ShouldRefresh [get]
virtual bool CancelAI [get]
virtual bool TimeBased [get]
virtual bool SyncRide [get]
virtual bool UseElements [get]
virtual int GainResistFactor [get]
virtual int P2 [get]
SourceElement.Row sourceElement [get]
virtual bool IsElemental [get]
virtual string RefString1 [get]
virtual bool CanManualRemove [get]
Properties inherited from BaseStats
SourceStat.Row source [get]
virtual Emo2 EmoIcon [get]
virtual ConditionType Type [get]
virtual string idSprite [get]
virtual bool ShowInWidget [get]
virtual Chara Owner [get]
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Additional Inherited Members
Static Public Member Functions inherited from Condition
static T Create< T > (int power=100, Action< T > onCreate=null)
static Condition Create (string alias, int power=100, Action< Condition > onCreate=null)
Static Public Member Functions inherited from EClass
static int rndSeed (int a, int seed)
static int rnd (long a)
static int rnd (int a)
static int curve (int _a, int start, int step, int rate=75)
static int sqrt (int a)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Public Attributes inherited from BaseCondition
int[] _ints = new int[5]
int phase = -1
ElementContainer elements
Chara owner
Public Attributes inherited from BaseStats
int id
SourceStat.Row _source
Static Public Attributes inherited from Condition
static bool ignoreEffect
Static Public Attributes inherited from BaseStats
static Chara CC
Static Public Attributes inherited from EClass
static Core core
Detailed Description
Definition at line 1 of file ConTransmuteBat.cs.
Member Function Documentation
CheckSeen()
void ConTransmuteBat.CheckSeen () inline
Definition at line 16 of file ConTransmuteBat.cs.
    {
        if (!EClass._zone.IsPCFactionOrTent && owner.pos.TryWitnessCrime(owner))
        {
            Msg.Say("transform_seen", owner);
            if (owner == EClass.pc)
            {
                EClass.player.ModKarma(-1);
            }
        }
    }
References EClass._zone, Zone.IsPCFactionOrTent, Player.ModKarma(), BaseCondition.owner, EClass.pc, EClass.player, Card.pos, Msg.Say(), and Point.TryWitnessCrime().
Referenced by OnRemoved(), and OnStart().
GetRendererReplacer()
override RendererReplacer ConTransmuteBat.GetRendererReplacer () inline virtual
Reimplemented from BaseCondition.
Definition at line 7 of file ConTransmuteBat.cs.
    {
        return RendererReplacer.CreateFrom("bat_trans");
    }
References RendererReplacer.CreateFrom().
OnRemoved()
override void ConTransmuteBat.OnRemoved () inline virtual
Reimplemented from ConTransmute.
Definition at line 35 of file ConTransmuteBat.cs.
    {
        base.OnRemoved();
        owner.HealHP(owner.MaxHP, HealSource.Item);
        owner.SetCooldown(8793);
        CheckSeen();
    }
References CheckSeen(), Card.HealHP(), Chara.MaxHP, BaseCondition.owner, and Chara.SetCooldown().
OnStart()
override void ConTransmuteBat.OnStart () inline virtual
Reimplemented from ConTransmute.
Definition at line 28 of file ConTransmuteBat.cs.
    {
        base.OnStart();
        owner.PlaySound("bat");
        CheckSeen();
    }
References CheckSeen(), BaseCondition.owner, and Card.PlaySound().
Tick()
override void ConTransmuteBat.Tick () inline virtual
Reimplemented from ConTransmute.
Definition at line 12 of file ConTransmuteBat.cs.
    {
    }
Property Documentation
CanManualRemove
override bool ConTransmuteBat.CanManualRemove get
Definition at line 5 of file ConTransmuteBat.cs.
HasDuration
override bool ConTransmuteBat.HasDuration get
Definition at line 3 of file ConTransmuteBat.cs.
The documentation for this class was generated from the following file:
Elin/ConTransmuteBat.cs