Elin Decompiled Documentation: WidgetInspector Class Reference
WidgetInspector Class Reference
Classes
class Extra
Public Member Functions
override object CreateExtra ()
override void OnActivate ()
override void OnDeactivate ()
void OnUpdateInput ()
void _Show ()
void SwitchPage (int _index)
void Refresh ()
void AddLog (string text, Color c=default(Color))
void AddButton (string id="test", Action action=null)
override void OnSetContextMenu (UIContextMenu m)
Public Member Functions inherited from Widget
void Test ()
bool IsInRightMode ()
void Activate ()
void RefreshOrder ()
virtual void OnActivate ()
virtual object CreateExtra ()
void Deactivate ()
virtual void OnDeactivate ()
void Close ()
void Reactivate ()
virtual void OnManagerActivate ()
virtual void OnManagerDeactivate ()
void SetAnchor (RectPosition p)
void SetPivot (RectPosition p)
virtual void OnChangePivot ()
void UpdateConfig ()
virtual void OnUpdateConfig ()
void ClampToScreen ()
virtual void OnChangeResolution ()
void OnChangePosition ()
virtual void OnChangeActionMode ()
virtual void OnFlip ()
bool IsAlignTop ()
Layer AddLayer (Layer l, Transform trans)
void RefreshTipPivotPosition ()
SkinSet GetSkin ()
SkinConfig GetSkinConfig ()
void SetSkin (int id, int v=0)
void TestSkin ()
virtual void ApplySkin ()
virtual void OnApplySkin ()
void InstantiateDeco (SkinDeco deco)
void AddDeco (SkinDeco deco)
void RemoveDeco (SkinDeco deco)
virtual bool CanShowContextMenu ()
void ShowContextMenu ()
void SetBaseContextMenu (UIContextMenu m)
virtual void OnSetContextMenu (UIContextMenu m)
void SetGridContextMenu (UIContextMenu m)
void SoundActivate ()
void OnChangeResolution ()
SkinSet GetSkin ()
SkinConfig GetSkinConfig ()
Static Public Member Functions
static void OnClickPoint ()
static void Show ()
static void Hide ()
Static Public Member Functions inherited from EMono
static int rnd (int a)
Public Attributes
LayoutGroup layoutButton
LayoutGroup layoutLog
UIText textTitle
Image iconCard
Image iconArea
int maxLog
int index
Vector3 posFix
List< object > list
Sprite spriteArea
bool selected
Public Attributes inherited from Widget
Image imageBG
SoundData soundActivate
UIDragPanel dragPanel
RectTransform tipPivotLeft
RectTransform tipPivotRight
Static Public Attributes
static WidgetInspector Instance
static object target
Static Public Attributes inherited from EMono
static Core core
Properties
static PointTarget mouseTarget [get]
Extra extra [get]
Properties inherited from Widget
string ID [get]
Config config [get]
SkinRoot skinRoot [get]
bool IsSealed [get]
virtual bool ShowStyleMenu [get]
virtual bool AlwaysTop [get]
virtual bool IsStaticPosition [get]
virtual bool AlwaysBottom [get]
virtual Type SetSiblingAfter [get]
virtual bool ShowInBuildMode [get]
virtual bool RightClickToClose [get]
virtual bool AllowRightClickToClose [get]
Properties inherited from EMono
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SoundManager Sound [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static CoreDebug debug [get]
Private Attributes
List< UIText > texts = new List<UIText>()
UIButton moldButton
UIText moldText
Additional Inherited Members
Public Types inherited from Widget
enum WidgetType { Default , ZoomMenu }
enum State { Active , Inactive }
Protected Member Functions inherited from Widget
void ClampToScreenEnsured (Component c, Vector2 anchoredPos)
void ClampToScreen (RectTransform rect, float margin=10f)
Protected Attributes inherited from Widget
bool flip
Detailed Description
Definition at line 7 of file WidgetInspector.cs.
Member Function Documentation
_Show()
void WidgetInspector._Show () inline
Definition at line 100 of file WidgetInspector.cs.
    {
        base.gameObject.SetActive(value: true);
        if (extra.moveToMouse)
        {
            base.transform.position = Input.mousePosition + posFix;
            ClampToScreen();
        }
        EMono.Sound.Play("pop_inspector");
        SwitchPage(0);
    }
References Widget.ClampToScreen(), extra, WidgetInspector.Extra.moveToMouse, posFix, EMono.Sound, and SwitchPage().
Referenced by OnUpdateInput().
AddButton()
void WidgetInspector.AddButton (string id = "test", Action action = null) inline
Definition at line 176 of file WidgetInspector.cs.
    {
        UIButton uIButton = Util.Instantiate(moldButton, layoutButton);
        uIButton.icon.sprite = SpriteSheet.Get("icon_" + id) ?? uIButton.icon.sprite;
        uIButton.mainText.SetText(id.lang());
        if (action != null)
        {
            uIButton.onClick.AddListener(delegate
            {
                action();
            });
        }
    }
References SpriteSheet.Get(), UIButton.icon, layoutButton, UIButton.mainText, moldButton, UIText.SetText(), and Util.
Referenced by SwitchPage().
AddLog()
void WidgetInspector.AddLog (string text, Color c = default(Color)) inline
Definition at line 164 of file WidgetInspector.cs.
    {
        UIText uIText = Util.Instantiate(moldText, layoutLog);
        texts.Add(uIText);
        uIText.SetText(text);
        if (texts.Count > maxLog)
        {
            UnityEngine.Object.DestroyImmediate(texts[0].gameObject);
            texts.Remove(texts[0]);
        }
    }
References layoutLog, maxLog, moldText, UIText.SetText(), texts, and Util.
Referenced by SwitchPage().
CreateExtra()
override object WidgetInspector.CreateExtra () inline virtual
Reimplemented from Widget.
Definition at line 51 of file WidgetInspector.cs.
    {
        return new Extra();
    }
Hide()
static void WidgetInspector.Hide () inline static
Definition at line 64 of file WidgetInspector.cs.
    {
        if ((bool)Instance)
        {
            Instance.Close();
        }
    }
References Widget.Close(), and Instance.
Referenced by AM_Sim._OnUpdateInput().
OnActivate()
override void WidgetInspector.OnActivate () inline virtual
Reimplemented from Widget.
Definition at line 72 of file WidgetInspector.cs.
    {
        Instance = this;
        moldButton = layoutButton.CreateMold<UIButton>();
        moldText = layoutLog.CreateMold<UIText>();
    }
References Instance, layoutButton, layoutLog, moldButton, and moldText.
OnClickPoint()
static void WidgetInspector.OnClickPoint () inline static
Definition at line 56 of file WidgetInspector.cs.
    {
    }
OnDeactivate()
override void WidgetInspector.OnDeactivate () inline virtual
Reimplemented from Widget.
Definition at line 79 of file WidgetInspector.cs.
    {
        target = null;
    }
References target.
OnSetContextMenu()
override void WidgetInspector.OnSetContextMenu (UIContextMenu m) inline virtual
Reimplemented from Widget.
Definition at line 190 of file WidgetInspector.cs.
    {
        m.AddChild("setting").AddToggle("moveToMouse", extra.moveToMouse, delegate(bool a)
        {
            extra.moveToMouse = a;
        });
        m.AddChild("style").AddSlider("toggleButtonBG", (float a) => a.ToString() ?? "", base.config.skin.button, delegate(float a)
        {
            base.config.skin.button = (int)a;
            ApplySkin();
        }, 0f, base.config.skin.Skin.buttons.Count - 1, isInt: true);
        SetBaseContextMenu(m);
    }
References UIContextMenu.AddChild(), UIContextMenu.AddSlider(), UIContextMenu.AddToggle(), Widget.ApplySkin(), extra, WidgetInspector.Extra.moveToMouse, and Widget.SetBaseContextMenu().
OnUpdateInput()
void WidgetInspector.OnUpdateInput () inline
Definition at line 84 of file WidgetInspector.cs.
    {
        if (!selected)
        {
            if (mouseTarget.hasValidTarget)
            {
                _Show();
            }
            else if (target != null)
            {
                target = null;
                base.gameObject.SetActive(value: false);
            }
        }
    }
References _Show(), PointTarget.hasValidTarget, mouseTarget, selected, and target.
Refresh()
void WidgetInspector.Refresh () inline
Definition at line 156 of file WidgetInspector.cs.
    {
        if (target is Chara)
        {
            _ = target;
        }
    }
References target.
Referenced by SwitchPage().
Show()
static void WidgetInspector.Show () inline static
Definition at line 60 of file WidgetInspector.cs.
    {
    }
SwitchPage()
void WidgetInspector.SwitchPage (int _index) inline
Definition at line 112 of file WidgetInspector.cs.
    {
        index = _index;
        target = list[index];
        string text = "";
        layoutButton.DestroyChildren();
        layoutLog.DestroyChildren();
        texts.Clear();
        if (target is Chara)
        {
            Chara c = target as Chara;
            text = c.Name;
            c.SetImage(iconCard);
            if (c.IsHomeMember())
            {
                AddButton("detail", delegate
                {
                    EMono.ui.AddLayer<LayerChara>().SetChara(c);
                });
            }
        }
        else if (target is Thing)
        {
            Thing t = target as Thing;
            text = t.Name;
            t.SetImage(iconCard);
            AddButton("detail", delegate
            {
                EMono.ui.AddLayer<LayerInfo>().Set(t);
            });
        }
        else
        {
            text = (target as Area).Name;
        }
        iconCard.rectTransform.pivot = new Vector2(1f, 0f);
        iconCard.SetActive(target is Card);
        iconArea.SetActive(target is Area);
        AddLog(target.ToString());
        textTitle.SetText(text);
        Refresh();
        this.RebuildLayout(recursive: true);
    }
References AddButton(), AddLog(), iconArea, iconCard, index, Chara.IsHomeMember(), layoutButton, layoutLog, list, Card.Name, Refresh(), Card.SetImage(), UIText.SetText(), target, texts, textTitle, and EMono.ui.
Referenced by _Show().
Member Data Documentation
iconArea
Image WidgetInspector.iconArea
Definition at line 27 of file WidgetInspector.cs.
Referenced by SwitchPage().
iconCard
Image WidgetInspector.iconCard
Definition at line 25 of file WidgetInspector.cs.
Referenced by SwitchPage().
index
int WidgetInspector.index
Definition at line 31 of file WidgetInspector.cs.
Referenced by SwitchPage().
Instance
WidgetInspector WidgetInspector.Instance static
Definition at line 15 of file WidgetInspector.cs.
Referenced by Hide(), and OnActivate().
layoutButton
LayoutGroup WidgetInspector.layoutButton
Definition at line 19 of file WidgetInspector.cs.
Referenced by AddButton(), OnActivate(), and SwitchPage().
layoutLog
LayoutGroup WidgetInspector.layoutLog
Definition at line 21 of file WidgetInspector.cs.
Referenced by AddLog(), OnActivate(), and SwitchPage().
list
List<object> WidgetInspector.list
Definition at line 35 of file WidgetInspector.cs.
Referenced by SwitchPage().
maxLog
int WidgetInspector.maxLog
Definition at line 29 of file WidgetInspector.cs.
Referenced by AddLog().
moldButton
UIButton WidgetInspector.moldButton private
Definition at line 43 of file WidgetInspector.cs.
Referenced by AddButton(), and OnActivate().
moldText
UIText WidgetInspector.moldText private
Definition at line 45 of file WidgetInspector.cs.
Referenced by AddLog(), and OnActivate().
posFix
Vector3 WidgetInspector.posFix
Definition at line 33 of file WidgetInspector.cs.
Referenced by _Show().
selected
bool WidgetInspector.selected
Definition at line 39 of file WidgetInspector.cs.
Referenced by OnUpdateInput().
spriteArea
Sprite WidgetInspector.spriteArea
Definition at line 37 of file WidgetInspector.cs.
target
object WidgetInspector.target static
Definition at line 17 of file WidgetInspector.cs.
Referenced by OnDeactivate(), OnUpdateInput(), Refresh(), and SwitchPage().
texts
List<UIText> WidgetInspector.texts = new List<UIText>() private
Definition at line 41 of file WidgetInspector.cs.
Referenced by AddLog(), and SwitchPage().
textTitle
UIText WidgetInspector.textTitle
Definition at line 23 of file WidgetInspector.cs.
Referenced by SwitchPage().
Property Documentation
extra
Extra WidgetInspector.extra get
Definition at line 49 of file WidgetInspector.cs.
Referenced by _Show(), and OnSetContextMenu().
mouseTarget
PointTarget WidgetInspector.mouseTarget static get private
Definition at line 47 of file WidgetInspector.cs.
Referenced by OnUpdateInput().
The documentation for this class was generated from the following file:
Elin/WidgetInspector.cs