Elin Decompiled Documentation: GlobalGoalAdv Class Reference
GlobalGoalAdv Class Reference
Public Member Functions
override void OnAdvanceHour ()
Public Member Functions inherited from GlobalGoal
void SetOwner (Chara c)
void Start ()
virtual void OnStart ()
void AdvanceHour ()
virtual void OnAdvanceHour ()
void Kill ()
void Complete ()
virtual void OnComplete ()
Additional Inherited Members
Static Public Member Functions inherited from EClass
static int rndSeed (int a, int seed)
static int rnd (long a)
static int rnd (int a)
static int curve (int a, int start, int step, int rate=75)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Public Attributes inherited from GlobalGoal
int hours
Chara owner
Static Public Attributes inherited from EClass
static Core core
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Detailed Description
Definition at line 1 of file GlobalGoalAdv.cs.
Member Function Documentation
OnAdvanceHour()
override void GlobalGoalAdv.OnAdvanceHour () inline virtual
Reimplemented from GlobalGoal.
Definition at line 3 of file GlobalGoalAdv.cs.
    {
        if (!owner.isDead && !owner.IsPCFaction && owner.currentZone != EClass._zone && ((EClass.debug.enable && EClass.rnd(24) == 0) || (hours > 720 && EClass.rnd(720) == 0)))
        {
            Zone randomTown = EClass.world.region.GetRandomTown();
            if (randomTown != owner.currentZone)
            {
                owner.MoveZone(randomTown, ZoneTransition.EnterState.RandomVisit);
            }
        }
    }
References EClass._zone, Chara.currentZone, EClass.debug, CoreDebug.enable, Region.GetRandomTown(), GlobalGoal.hours, Chara.isDead, Chara.IsPCFaction, Chara.MoveZone(), GlobalGoal.owner, World.region, EClass.rnd(), and EClass.world.
The documentation for this class was generated from the following file:
Elin/GlobalGoalAdv.cs