Elin Decompiled Documentation: Game Class Reference
Game Class Reference
Classes
class Config
class Flags
Public Member Functions
void OnUpdate ()
void OnLoad ()
void OnGameInstantiated ()
void _Create ()
void StartNewGame ()
void AddAdventurers ()
void AddAdventurer (string id, Zone z=null)
void GotoTitle (bool showDialog=true)
void Quit ()
bool Save (bool isAutoSave=false, bool silent=false)
void OnBeforeSave ()
void Kill ()
void Pause (Action onUnpause=null)
Static Public Member Functions
static new void Wait (float a, Point p)
static new void Wait (float a, Card c)
static void Wait (float a)
static bool TryLoad (string id, bool cloud, Action onLoad)
static void Load (string id, bool cloud)
static void Create (string _id=null, bool cloud=false)
static void OnBeforeInstantiate ()
Static Public Member Functions inherited from EClass
static int rndSeed (int a, int seed)
static int rnd (int a)
static int curve (int a, int start, int step, int rate=75)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Public Attributes
SpatialManager spatials = new SpatialManager()
CardManager cards = new CardManager()
ReligionManager religions = new ReligionManager()
FactionManager factions = new FactionManager()
DomainManager domains = new DomainManager()
Version version
PartyManager parties = new PartyManager()
new World world
new Player player = new Player()
QuestManager quests = new QuestManager()
RelationManager relations = new RelationManager()
MsgLog log
PCCUniformManager uniforms = new PCCUniformManager()
TeleportManager teleports = new TeleportManager()
int seed
int idPrologue
int idDifficulty
int dateScratch
double backupTime
Flags flags = new Flags()
Config config = new Config()
List< Thing > lostThings = new List<Thing>()
GamePrincipal principal = new GamePrincipal()
int gameSpeedIndex = 1
int lastGameSpeedIndex = 1
int sessionMin
int countLoadedMaps
int saveCount
float timeSinceStart
bool isLoading
bool isKilling
bool isCloud
GameBlueprint bp
GameUpdater updater = new GameUpdater()
Zone activeZone
Zone lastActiveZone
Dictionary< string, IGlobalValue > referenceMap = new Dictionary<string, IGlobalValue>()
HashSet< Texture2D > loadedTextures = new HashSet<Texture2D>()
Static Public Attributes
static Game Instance
static float waitTimer
static string id
static bool isPaused
Static Public Attributes inherited from EClass
static Core core
Properties
static bool IsWaiting [get]
Prologue Prologue [get]
bool UseGrid [get]
bool altUI [get]
bool altInv [get]
bool altCraft [get]
bool altAbility [get]
Zone StartZone [get]
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Private Member Functions
void OnSerializing (StreamingContext context)
void OnDeserializing (StreamingContext context)
Private Attributes
float welcomeTimer
Detailed Description
Definition at line 7 of file Game.cs.
Member Function Documentation
_Create()
void Game._Create () inline
Definition at line 727 of file Game.cs.
    {
        principal = IO.DeepCopy(EClass.setting.start.principals[0]);
        idDifficulty = 1;
        config.snapFreePos = (config.slope = (config.autoWall = true));
        config.autoCombat.abortOnAllyDead = true;
        config.autoCombat.abortOnHalfHP = true;
        config.autoCombat.bUseHotBar = true;
        config.autoCombat.bUseInventory = true;
        config.autoCombat.bDontChangeTarget = true;
        config.autoCombat.abortOnKill = true;
        config.autoCombat.abortOnItemLoss = true;
        seed = EClass.rnd(10000);
        Debug.Log("creating game: " + id + " seed:" + seed);
        uniforms.Import();
        religions.OnCreateGame();
        factions.OnCreateGame();
        world = SpatialGen.CreateRecursive("world") as World;
        domains.OnCreateGame();
        foreach (Spatial value in spatials.map.Values)
        {
            value.SetMainFaction(factions.Find(value.source.faction.IsEmpty("wilds")));
        }
        player.OnCreateGame();
        cards.container_shipping = ThingGen.Create("container_shipping");
        cards.container_deliver = ThingGen.Create("container_delivery");
        cards.container_deposit = ThingGen.Create("container_deposit");
        bp = new GameBlueprint();
        bp.Create();
    }
References ZoneBlueprint.Create(), ThingGen.Create(), SpatialGen.CreateRecursive(), Debug, FactionManager.Find(), SpatialManager.map, DomainManager.OnCreateGame(), FactionManager.OnCreateGame(), Player.OnCreateGame(), ReligionManager.OnCreateGame(), GameSetting.StartSetting.principals, EClass.rnd(), seed, Spatial.SetMainFaction(), EClass.setting, Spatial.source, GameSetting.start, and world.
Referenced by Create().
AddAdventurer()
void Game.AddAdventurer (string id, Zone z = null) inline
Definition at line 923 of file Game.cs.
    {
        if (z == null)
        {
            List<Zone> source = world.region.ListTowns();
            do
            {
                z = source.RandomItem();
            }
            while ((z is Zone_SubTown && EClass.rnd(5) != 0) || z == EClass.pc.currentZone);
        }
        Chara chara = CharaGen.Create(id);
        chara.SetHomeZone(z);
        chara.global.transition = new ZoneTransition
        {
            state = ZoneTransition.EnterState.RandomVisit
        };
        z.AddCard(chara);
        cards.listAdv.Add(chara);
    }
References CharaGen.Create(), Chara.currentZone, CardManager.listAdv, EClass.pc, EClass.rnd(), Chara.SetHomeZone(), and world.
AddAdventurers()
void Game.AddAdventurers () inline
Definition at line 896 of file Game.cs.
    {
        List<Zone> source = world.region.ListTowns();
        string[] array = new string[7] { "adv_kiria", "adv_gaki", "adv_wini", "adv_verna", "adv_ivory", "adv_mesherada", "adv_yukiimo" };
        for (int i = 0; i < EClass.setting.balance.numAdv; i++)
        {
            Zone zone = source.RandomItem();
            if (zone is Zone_SubTown && EClass.rnd(5) != 0)
            {
                i--;
                continue;
            }
            if (i >= array.Length && i < array.Length + 2)
            {
                CardBlueprint.Set(CardBlueprint.Chara(i * 15));
            }
            Chara chara = CharaGen.Create((i < array.Length) ? array[i] : ((EClass.rnd(10) == 0) ? "adv_fairy" : "adv"));
            chara.SetHomeZone(zone);
            chara.global.transition = new ZoneTransition
            {
                state = ZoneTransition.EnterState.RandomVisit
            };
            zone.AddCard(chara);
            cards.listAdv.Add(chara);
        }
    }
References Zone.AddCard(), GameSetting.balance, CardBlueprint.Chara(), CharaGen.Create(), CardManager.listAdv, GameSetting.BalanceSetting.numAdv, EClass.rnd(), CardBlueprint.Set(), Chara.SetHomeZone(), EClass.setting, and world.
Referenced by OnLoad().
Create()
static void Game.Create (string _id = null, bool cloud = false) inline static
Definition at line 685 of file Game.cs.
    {
        id = _id ?? GameIO.GetNewId(cloud ? CorePath.RootSaveCloud : CorePath.RootSave, "world_");
        OnBeforeInstantiate();
        EClass.core.game = (Instance = new Game());
        EClass.core.game.isCloud = cloud;
        GameIO.ResetTemp();
        EClass.core.game.OnGameInstantiated();
        EClass.core.game._Create();
    }
References _Create(), EClass.core, Core.game, GameIO.GetNewId(), OnGameInstantiated(), GameIO.ResetTemp(), CorePath.RootSave, and CorePath.RootSaveCloud.
Referenced by LayerEditBio.OnAfterAddLayer(), LayerEmbark.OnAfterAddLayer(), and CoreDebug.QuickStart().
GotoTitle()
void Game.GotoTitle (bool showDialog = true) inline
Definition at line 944 of file Game.cs.
    {
        if (showDialog)
        {
            Dialog.YesNo("dialog_gotoTitle", delegate
            {
                if (EClass.game.Save(isAutoSave: true))
                {
                    EClass.scene.Init(Scene.Mode.Title);
                }
            });
        }
        else
        {
            EClass.scene.Init(Scene.Mode.Title);
        }
    }
References EClass.game, Scene.Init(), Save(), EClass.scene, and Dialog.YesNo().
Referenced by LayerPauseMenu.OnClickTitle(), and HotItemContext.Show().
Kill()
void Game.Kill () inline
Definition at line 1043 of file Game.cs.
    {
        isKilling = true;
        Debug.Log("Killing Game: IsStarted? " + EClass.core.IsGameStarted);
        if (EClass.core.IsGameStarted)
        {
            EClass.ui.OnKillGame();
            EClass.scene.OnKillGame();
            activeZone.OnKillGame();
        }
        EClass.core.game = (Instance = null);
        EClass.Sound.currentPlaylist = null;
        Window.dictTab.Clear();
        foreach (Texture2D loadedTexture in loadedTextures)
        {
            if (loadedTexture != null)
            {
                UnityEngine.Object.Destroy(loadedTexture);
            }
        }
    }
References EClass.core, Debug, Window.dictTab, Core.IsGameStarted, Scene.OnKillGame(), Zone.OnKillGame(), EClass.scene, and EClass.ui.
Referenced by Scene.Init(), Load(), and Core.SetLang().
Load()
static void Game.Load (string id, bool cloud) inline static
Definition at line 313 of file Game.cs.
    {
        string text = (cloud ? CorePath.RootSaveCloud : CorePath.RootSave) + id;
        Debug.Log("Loading: " + id + ": " + text);
        if (EClass.game != null)
        {
            EClass.game.Kill();
        }
        OnBeforeInstantiate();
        EClass.core.game = GameIO.LoadGame(id, text, cloud);
        EClass.game.isCloud = cloud;
        EClass.game.isLoading = true;
        GameIO.ClearTemp();
        EClass.game.OnGameInstantiated();
        EClass.game.OnLoad();
        EClass.scene.Init(Scene.Mode.StartGame);
        if (EClass.game.altInv)
        {
            SoundManager.ignoreSounds = true;
            if (EClass.game.player.pref.layerInventory)
            {
                EClass.ui.OpenFloatInv();
            }
            SoundManager.ignoreSounds = true;
            if (EClass.game.player.pref.layerAbility)
            {
                EClass.ui.ToggleAbility();
            }
            SoundManager.ignoreSounds = false;
            TooltipManager.Instance.HideTooltips(immediate: true);
        }
        if ((bool)WidgetSideScreen.Instance)
        {
            WidgetSideScreen.Instance.OnChangeResolution();
        }
        EClass.game.isLoading = false;
    }
References altInv, GameIO.ClearTemp(), Debug, EClass.game, TooltipManager.HideTooltips(), Scene.Init(), TooltipManager.Instance, WidgetSideScreen.Instance, Kill(), Player.Pref.layerAbility, Player.Pref.layerInventory, GameIO.LoadGame(), OnBeforeInstantiate(), WidgetSideScreen.OnChangeResolution(), OnGameInstantiated(), OnLoad(), player, Player.pref, CorePath.RootSave, EClass.scene, and EClass.ui.
Referenced by AM_Adv._OnUpdateInput(), Map.Reload(), and CoreDebug.UpdateInput().
OnBeforeInstantiate()
static void Game.OnBeforeInstantiate () inline static
Definition at line 696 of file Game.cs.
    {
        Player.seedHallucination = 0;
    }
Referenced by Load().
OnBeforeSave()
void Game.OnBeforeSave () inline
Definition at line 1029 of file Game.cs.
    {
        foreach (Zone zone in spatials.Zones)
        {
            zone.OnBeforeSave();
        }
        player.OnBeforeSave();
        foreach (Spatial item in spatials.listDestryoed)
        {
            item.DeleteMapRecursive();
        }
        spatials.listDestryoed.Clear();
    }
References item, SpatialManager.listDestryoed, Player.OnBeforeSave(), Spatial.OnBeforeSave(), and SpatialManager.Zones.
OnDeserializing()
void Game.OnDeserializing (StreamingContext context) inline private
Definition at line 1090 of file Game.cs.
    {
        Debug.Log("#io game OnDeserializing");
        Instance = this;
    }
References Debug.
OnGameInstantiated()
void Game.OnGameInstantiated () inline
Definition at line 701 of file Game.cs.
    {
        HotItemHeld.taskBuild = null;
        InvOwner.Trader = (InvOwner.Main = null);
        LayerDrama.currentQuest = null;
        BookList.Init();
        ContentGallery.lastPage = 0;
        ContentGallery.listMode = false;
        if (!Application.isEditor || !EClass.debug.enable)
        {
            RecipeManager.BuildList();
        }
        foreach (Chara value in cards.globalCharas.Values)
        {
            if (value.uid == player.uidChara)
            {
                player.chara = value;
                break;
            }
        }
        ActionMode.OnGameInstantiated();
        EClass.ui.widgets.OnGameInstantiated();
        EClass.Sound.ResetPlaylist();
        EClass.core.config.ApplyFPS(force: true);
    }
References CoreConfig.ApplyFPS(), RecipeManager.BuildList(), Core.config, EClass.core, EClass.debug, CoreDebug.enable, CardManager.globalCharas, BookList.Init(), ActionMode.OnGameInstantiated(), EClass.Sound, EClass.ui, Card.uid, and Player.uidChara.
Referenced by Create(), and Load().
OnLoad()
void Game.OnLoad () inline
Definition at line 351 of file Game.cs.
    {
        domains.OnLoad();
        religions.OnLoad();
        factions.OnLoad();
        world._OnLoad();
        player.OnLoad();
        if (EClass.pc.currentZone == null || EClass.pc.currentZone.destryoed)
        {
            EClass.pc.party.members.ForEach(delegate(Chara c)
            {
                c.currentZone = EClass.pc.homeZone;
                c.global.transition = new ZoneTransition
                {
                    state = ZoneTransition.EnterState.Return
                };
            });
        }
        player.zone = EClass.pc.currentZone;
        EClass.pc.currentZone.lastActive = world.date.GetRaw();
        if (spatials.Find("somewhere") == null)
        {
            SpatialGen.Create("somewhere", world.region, register: true);
        }
        EClass.pc.homeZone.isKnown = true;
        EClass.debug.OnLoad();
        EClass.pc.things.RefreshGridRecursive();
        foreach (Thing item in EClass.pc.things.List((Thing t) => t.Num <= 0 || t.isDestroyed))
        {
            item.parent.RemoveCard(item);
        }
        foreach (Thing item2 in EClass.pc.things.List((Thing t) => t.trait is TraitChestMerchant))
        {
            item2.Destroy();
        }
        foreach (Thing item3 in EClass.pc.things.List((Thing t) => t.invY == 1 && t.invX == -1))
        {
            item3.invY = 0;
        }
        foreach (Chara value in EClass.game.cards.globalCharas.Values)
        {
            if (value.id == "demitas" && value.faction.id == "wilds")
            {
                EClass.pc.homeBranch.AddMemeber(value);
            }
            if (value.memberType == FactionMemberType.Livestock && !value.IsPCFaction)
            {
                value.memberType = FactionMemberType.Default;
            }
            if (!value.isDyed && value.HasTag(CTAG.random_color))
            {
                value.DyeRandom();
            }
        }
        foreach (FactionBranch child in EClass.pc.faction.GetChildren())
        {
            foreach (Chara member in child.members)
            {
                if (!member.isDead && (member.currentZone == null || member.currentZone.id == "somewhere"))
                {
                    Debug.Log("exception: Moving invalid chara: " + member.Name + "/" + member.currentZone?.ToString() + "/" + member.homeBranch?.ToString() + "/" + member.faction);
                    member.MoveZone(child.owner, ZoneTransition.EnterState.RandomVisit);
                }
                member.RefreshWorkElements(child.owner.elements);
                member.Refresh();
            }
        }
        EClass.pc.angle = player.angle;
        EClass.pc.elements.CheckSkillActions();
        if (cards.listAdv.Count == 0)
        {
            AddAdventurers();
        }
        quests.list.ForeachReverse(delegate(Quest q)
        {
            if (!(q is QuestRandom))
            {
                foreach (Quest item4 in quests.list)
                {
                    if (q != item4 && item4.id == q.id)
                    {
                        quests.list.Remove(item4);
                        break;
                    }
                }
            }
        });
        quests.globalList.ForeachReverse(delegate(Quest q)
        {
            if (!(q is QuestRandom))
            {
                foreach (Quest global in quests.globalList)
                {
                    if (q != global && global.id == q.id)
                    {
                        quests.globalList.Remove(global);
                        break;
                    }
                }
            }
        });
        TryAddQuest("into_darkness", "exile_kettle");
        if (version.IsBelow(0, 23, 155))
        {
            AddAdventurer("adv_yukiimo");
        }
        if (version.IsBelow(0, 23, 100))
        {
            int num = player.recipes.knownRecipes.TryGetValue("trainingDummy_heavy", 0);
            if (num != 0)
            {
                player.recipes.knownRecipes["trainingDummy_heavy1"] = num;
            }
        }
        if (version.IsBelow(0, 23, 96))
        {
            EClass.game.principal = IO.DeepCopy(EClass.setting.start.principals[0]);
            player.resetPrincipal = true;
        }
        if (player.resetPrincipal)
        {
            GameDifficultySetting gameDifficultySetting = EClass.setting.start.difficulties[idDifficulty];
            EClass.game.principal.id = -1;
            EClass.game.principal.permadeath = gameDifficultySetting.deleteGameOnDeath;
            EClass.game.principal.disableManualSave = !gameDifficultySetting.allowManualSave;
            EClass.core.actionsNextFrame.Add(delegate
            {
                EClass.ui.AddLayer<LayerWorldSetting>();
            });
        }
        if (version.IsBelow(0, 23, 93))
        {
            RecipeManager.BuildList();
            Debug.Log("feafefaeffaeaffeaaeaefseasfaefaef");
            while (TryAddRecipe())
            {
            }
        }
        if (version.IsBelow(0, 23, 72))
        {
            foreach (Chara value2 in EClass.game.cards.globalCharas.Values)
            {
                if (!value2.isDead)
                {
                    value2.c_wasInPcParty = false;
                }
            }
        }
        if (version.IsBelow(0, 23, 59))
        {
            while (TryDestroy())
            {
            }
        }
        if (version.IsBelow(0, 23, 52))
        {
            player.flags.toggleHotbarHighlightActivated = true;
        }
        if (version.IsBelow(0, 23, 51))
        {
            foreach (Chara value3 in EClass.game.cards.globalCharas.Values)
            {
                if (!(value3.id != "adv") && value3.IsPCFaction)
                {
                    value3.idSkin = value3.uid % (value3.source._tiles.Length - 4) / 2 * 2 + ((!value3.IsMale) ? 1 : 0);
                }
            }
        }
        if (version.IsBelow(0, 22, 91))
        {
            TryAddQuestIfActive("demitas_spellwriter", "into_darkness");
        }
        if (version.IsBelow(0, 22, 86))
        {
            Chara chara = cards.globalCharas.Find("demitas");
            if (chara != null && chara._works != null && chara._works.Count > 0)
            {
                chara._works[0] = 51;
            }
        }
        if (version.IsBelow(0, 22, 86))
        {
            TryAddQuest("farris_tulip", "greatDebt");
        }
        if (version.IsBelow(0, 22, 86))
        {
            TryAddQuest("exile_whisper", "exile_kettle");
        }
        if (version.IsBelow(0, 22, 85))
        {
            TryAddQuest("exile_meet", "pre_debt");
        }
        if (version.IsBelow(0, 22, 60) && EClass.game.quests.Get<QuestDebt>() != null)
        {
            Chara chara2 = cards.globalCharas.Find("loytel");
            Debug.Log("Loytelfix: " + chara2.homeZone);
            if (chara2.homeZone == null || !chara2.homeZone.IsPCFaction)
            {
                EClass.pc.homeBranch.AddMemeber(chara2);
                chara2.homeZone = EClass.pc.homeBranch.owner;
                chara2.RemoveEditorTag(EditorTag.Invulnerable);
            }
        }
        if (version.IsBelow(0, 22, 52) && quests.completedIDs.Contains("vernis_gold"))
        {
            quests.Add("pre_debt", "farris");
        }
        if (quests.completedIDs.Contains("farris_tulip"))
        {
            quests.globalList.ForeachReverse(delegate(Quest q)
            {
                if (q.id == "farris_tulip")
                {
                    quests.globalList.Remove(q);
                }
            });
        }
        quests.list.ForeachReverse(delegate(Quest q)
        {
            if (q is QuestDialog && quests.completedIDs.Contains(q.id))
            {
                quests.list.Remove(q);
            }
        });
        if (version.IsBelow(0, 22, 20))
        {
            foreach (Chara value4 in cards.globalCharas.Values)
            {
                value4.SetBool(18, enable: false);
            }
        }
        if (version.IsBelow(0, 22, 22))
        {
            if (EClass.pc.faithElements != null)
            {
                EClass.pc.faithElements.SetParent();
            }
            foreach (Element item5 in EClass.pc.elements.ListElements((Element e) => e.source.categorySub == "god"))
            {
                EClass.pc.SetFeat(item5.id, 0);
            }
            EClass.pc.RefreshFaithElement();
        }
        if (version.IsBelow(0, 22, 45))
        {
            player.debt = 20000000;
        }
        if (!version.Equals(EClass.core.version))
        {
            player.recipes.OnVersionUpdate();
        }
        if (cards.container_deposit == null)
        {
            cards.container_deposit = ThingGen.Create("container_deposit");
            if (player.bankMoney > 0)
            {
                cards.container_deposit.Add("money", player.bankMoney);
            }
        }
        foreach (Quest item6 in quests.list)
        {
            if (item6 is QuestSequence && !EClass.sources.quests.map.ContainsKey(item6.idSource))
            {
                item6.phase = 0;
            }
        }
        foreach (Quest global2 in quests.globalList)
        {
            if (global2 is QuestSequence && !EClass.sources.quests.map.ContainsKey(global2.idSource))
            {
                global2.phase = 0;
            }
        }
        void TryAddQuest(string idQuest, string idReqQuest)
        {
            if (quests.completedIDs.Contains(idReqQuest) && !quests.completedIDs.Contains(idQuest) && quests.GetGlobal(idQuest) == null && quests.Get(idQuest) == null)
            {
                quests.Add(idQuest);
            }
        }
        void TryAddQuestIfActive(string idQuest, string idReqQuest)
        {
            if (quests.Get(idReqQuest) != null && !quests.completedIDs.Contains(idQuest) && quests.GetGlobal(idQuest) == null && quests.Get(idQuest) == null)
            {
                quests.Add(idQuest);
            }
        }
        bool TryAddRecipe()
        {
            foreach (string key in player.recipes.knownRecipes.Keys)
            {
                if (key.Length > 1 && key[0] == 'b')
                {
                    RecipeSource recipeSource = RecipeManager.Get(key + "-p");
                    if (recipeSource != null && !player.recipes.knownRecipes.ContainsKey(recipeSource.id))
                    {
                        Debug.Log(recipeSource.id);
                        player.recipes.Add(recipeSource.id, showEffect: false);
                        return true;
                    }
                    recipeSource = RecipeManager.Get(key.Replace("-p", ""));
                    if (recipeSource != null && !player.recipes.knownRecipes.ContainsKey(recipeSource.id))
                    {
                        Debug.Log(recipeSource.id);
                        player.recipes.Add(recipeSource.id, showEffect: false);
                        return true;
                    }
                }
            }
            return false;
        }
        static bool TryDestroy()
        {
            for (int i = 0; i < EClass.pc.party.members.Count; i++)
            {
                Chara chara3 = EClass.pc.party.members[i];
                Debug.Log(chara3.id + "/" + chara3.uid + "/" + chara3._cints[1]);
                for (int j = 0; j < EClass.pc.party.members.Count; j++)
                {
                    Chara chara4 = EClass.pc.party.members[j];
                    if (i != j && chara3.uid == chara4.uid)
                    {
                        EClass.pc.party.uidMembers.RemoveAt(j);
                        EClass.pc.party.members.RemoveAt(j);
                        chara4.Destroy();
                        Debug.Log("Destroyed");
                        return true;
                    }
                }
            }
            return false;
        }
    }
References Spatial._OnLoad(), AddAdventurers(), FactionBranch.AddMemeber(), Player.angle, cards, ElementContainerCard.CheckSkillActions(), SpatialGen.Create(), Chara.currentZone, World.date, EClass.debug, Debug, Card.Destroy(), Spatial.destryoed, domains, Card.DyeRandom(), Card.elements, Zone.elements, Chara.faction, factions, SpatialManager.Find(), EClass.game, Faction.GetChildren(), Date.GetRaw(), CardManager.globalCharas, Card.HasTag(), Chara.homeBranch, Chara.homeZone, Card.id, Faction.id, Spatial.id, Card.invX, Card.invY, Chara.isDead, Card.isDestroyed, Card.isDyed, Chara.IsPCFaction, item, QuestManager.list, ThingContainer.List(), CardManager.listAdv, FactionBranch.members, Party.members, Chara.memberType, Chara.MoveZone(), Card.Name, Card.Num, CoreDebug.OnLoad(), DomainManager.OnLoad(), FactionManager.OnLoad(), Player.OnLoad(), ReligionManager.OnLoad(), FactionBranch.owner, Chara.party, EClass.pc, player, quests, Chara.Refresh(), ThingContainer.RefreshGridRecursive(), Chara.RefreshWorkElements(), World.region, religions, spatials, Card.things, Zone.ToString(), Card.trait, and world.
Referenced by Load().
OnSerializing()
void Game.OnSerializing (StreamingContext context) inline private
Definition at line 1084 of file Game.cs.
    {
        Debug.Log("#io game OnSerializing");
    }
References Debug.
OnUpdate()
void Game.OnUpdate () inline
Definition at line 289 of file Game.cs.
    {
        backupTime += Time.deltaTime;
        waitTimer -= Time.deltaTime;
        timeSinceStart += Time.deltaTime;
        player.stats.timeElapsed += Time.deltaTime;
        if (!flags.IsWelcomeMessageShown && player.stats.timeElapsed > 2.0)
        {
            flags.IsWelcomeMessageShown = true;
        }
        updater.FixedUpdate();
    }
References backupTime, GameUpdater.FixedUpdate(), flags, Game.Flags.IsWelcomeMessageShown, player, Player.stats, Player.Stats.timeElapsed, timeSinceStart, updater, and waitTimer.
Referenced by Core.Update().
Pause()
void Game.Pause (Action onUnpause = null) inline
Definition at line 1065 of file Game.cs.
    {
        isPaused = true;
        LayerPause layerPause = EClass.ui.AddLayer<LayerPause>();
        Game lastGame = EClass.game;
        if (onUnpause == null)
        {
            return;
        }
        layerPause.SetOnKill(delegate
        {
            if (EClass.core.IsGameStarted && lastGame == EClass.game)
            {
                onUnpause();
            }
        });
    }
References EClass.core, EClass.game, Core.IsGameStarted, Layer.SetOnKill(), and EClass.ui.
Referenced by ZoneEventQuest.OnTickRound(), and ZoneEventQuest.SpawnBoss().
Quit()
void Game.Quit () inline
Definition at line 962 of file Game.cs.
    {
        Dialog.YesNo("dialog_quit", delegate
        {
            if (EClass.game.Save())
            {
                EClass.core.Quit();
            }
        });
    }
References EClass.game, Save(), and Dialog.YesNo().
Referenced by EUtil.ExitGame(), LayerPauseMenu.OnClickExit(), and HotItemContext.Show().
Save()
bool Game.Save (bool isAutoSave = false, bool silent = false) inline
Definition at line 973 of file Game.cs.
    {
        if (EClass.ui.IsDragging)
        {
            EClass.ui.EndDrag(canceled: true);
        }
        if (isAutoSave && EClass.debug.ignoreAutoSave)
        {
            return true;
        }
        bool flag = EClass.core.config.game.autoBackup && backupTime >= (double)(EClass.core.config.game.backupInterval * 60 * 30);
        if (flag)
        {
            backupTime = 0.0;
        }
        EClass.core.config.TryUpdatePlayedHour();
        countLoadedMaps = 0;
        player.pref.layerInventory = EClass.ui.layerFloat.GetLayer<LayerInventory>();
        if (player.pref.layerInventory)
        {
            player.pref.layerAbility = EClass.ui.layerFloat.GetLayer<LayerAbility>();
        }
        player.pref.layerCraft = EClass.ui.layerFloat.GetLayer<LayerCraftFloat>();
        player.angle = EClass.pc.angle;
        version = EClass.core.version;
        EClass.ui.widgets.UpdateConfigs();
        GameIndex gameIndex = null;
        try
        {
            OnBeforeSave();
            gameIndex = GameIO.SaveGame();
        }
        catch (Exception ex)
        {
            EClass.ui.Say(ex.Message);
            SE.Beep();
            Msg.Say("error_save");
            return false;
        }
        if (flag)
        {
            GameIO.MakeBackup(gameIndex);
            EClass.ui.Say("backupDone");
        }
        if (!silent)
        {
            if (!isAutoSave)
            {
                SE.WriteJournal();
            }
            Msg.Say("saved");
        }
        saveCount++;
        return true;
    }
References Card.angle, CoreConfig.GameConfig.backupInterval, Core.config, EClass.core, EClass.debug, CoreConfig.game, CoreDebug.ignoreAutoSave, Player.Pref.layerInventory, GameIO.MakeBackup(), EClass.pc, Player.pref, GameIO.SaveGame(), Msg.Say(), CoreConfig.TryUpdatePlayedHour(), EClass.ui, and BaseCore.version.
Referenced by AM_Adv._OnUpdateInput(), LayerSleep.Advance(), LayerNewZone.Embark(), GotoTitle(), Scene.Init(), Chara.MoveZone(), LayerPauseMenu.OnClickSave(), TraitDeedRelocate.OnRead(), DramaManager.ParseLine(), Quit(), Map.Reload(), HotItemContext.Show(), and CoreDebug.UpdateInput().
StartNewGame()
void Game.StartNewGame () inline
Definition at line 758 of file Game.cs.
    {
        EClass.pc.homeZone = StartZone;
        EClass.pc.SetGlobal();
        parties.Create(EClass.pc);
        Prologue prologue = EClass.game.Prologue;
        CharaGen.Create("fiama").SetGlobal(EClass.game.StartZone, prologue.posFiama.x, prologue.posFiama.y);
        CharaGen.Create("ashland").SetGlobal(EClass.game.StartZone, prologue.posAsh.x, prologue.posAsh.y);
        if ((bool)LayerTitle.actor)
        {
            world.date.hour = EClass.game.Prologue.hour;
            EClass.core.actionsNextFrame.Add(LayerTitle.KillActor);
            Player obj = player;
            Chara chara = EClass.pc;
            Zone zone2 = (EClass.pc.homeZone = EClass.game.spatials.Find(EClass.game.Prologue.idStartZone));
            Zone zone4 = (chara.currentZone = zone2);
            obj.zone = zone4;
            EClass.pc.global.transition = new ZoneTransition
            {
                state = ZoneTransition.EnterState.Exact,
                x = EClass.game.Prologue.startX,
                z = EClass.game.Prologue.startZ
            };
            EClass.pc.hp = EClass.pc.MaxHP;
            EClass.pc.mana.Set(EClass.pc.mana.max / 2);
            EClass.pc.stamina.Set(EClass.pc.stamina.max / 2);
            EClass.pc.AddCondition<ConFaint>(200, force: true);
        }
        else
        {
            EClass.pc.homeZone = EClass.game.spatials.Find(EClass.game.Prologue.idStartZone);
            Zone zone5 = null;
            ZoneTransition transition = new ZoneTransition
            {
                state = ZoneTransition.EnterState.Auto
            };
            Chara c = EClass.game.cards.globalCharas.Find("ashland");
            switch (EClass.debug.startScene)
            {
            case CoreDebug.StartScene.Zone:
                zone5 = EClass.game.spatials.Find(EClass.debug.startZone);
                transition = new ZoneTransition
                {
                    state = ZoneTransition.EnterState.Exact,
                    x = EClass.game.Prologue.startX,
                    z = EClass.game.Prologue.startZ
                };
                break;
            case CoreDebug.StartScene.Home:
            case CoreDebug.StartScene.Story_Test:
                zone5 = EClass.game.spatials.Find(EClass.game.Prologue.idStartZone);
                transition = new ZoneTransition
                {
                    state = ZoneTransition.EnterState.Exact,
                    x = EClass.game.Prologue.startX,
                    z = EClass.game.Prologue.startZ
                };
                break;
            case CoreDebug.StartScene.Home_Cave:
                EClass.game.idPrologue = 2;
                zone5 = EClass.game.spatials.Find(EClass.game.Prologue.idStartZone);
                transition = new ZoneTransition
                {
                    state = ZoneTransition.EnterState.Exact,
                    x = EClass.game.Prologue.startX,
                    z = EClass.game.Prologue.startZ
                };
                break;
            case CoreDebug.StartScene.MeetFarris:
            {
                Zone parent4 = EClass.game.spatials.Find("nymelle");
                zone5 = SpatialGen.Create("nymelle", parent4, register: true) as Zone;
                zone5.lv = -2;
                EClass.game.quests.Start("exploration", c, assignQuest: false);
                break;
            }
            case CoreDebug.StartScene.NymelleBoss:
            {
                Zone parent3 = EClass.game.spatials.Find("nymelle");
                zone5 = SpatialGen.Create("nymelle_boss", parent3, register: true) as Zone;
                zone5.lv = -5;
                EClass.game.quests.Start("exploration", c, assignQuest: false).ChangePhase(2);
                break;
            }
            case CoreDebug.StartScene.AfterNymelle:
                zone5 = EClass.game.spatials.Find(EClass.game.Prologue.idStartZone);
                transition = new ZoneTransition
                {
                    state = ZoneTransition.EnterState.Exact,
                    x = EClass.game.Prologue.startX,
                    z = EClass.game.Prologue.startZ
                };
                EClass.game.quests.Start("exploration", c, assignQuest: false).ChangePhase(5);
                EClass.game.quests.globalList.Add(Quest.Create("sharedContainer").SetClient(c, assignQuest: false));
                EClass.game.quests.globalList.Add(Quest.Create("crafter").SetClient(c, assignQuest: false));
                EClass.game.quests.globalList.Add(Quest.Create("defense").SetClient(c, assignQuest: false));
                break;
            case CoreDebug.StartScene.Melilith:
            {
                Zone parent2 = EClass.game.spatials.Find("cursed_manor");
                zone5 = SpatialGen.Create("cursed_manor_dungeon", parent2, register: true) as Zone;
                zone5.lv = -5;
                break;
            }
            case CoreDebug.StartScene.Tefra:
            {
                Zone parent = EClass.game.spatials.Find("vernis");
                zone5 = SpatialGen.Create("vernis_mine", parent, register: true) as Zone;
                zone5.lv = -7;
                break;
            }
            }
            if (zone5 != null)
            {
                Player obj2 = player;
                Chara chara2 = EClass.pc;
                Zone zone2 = (EClass.pc.homeZone = zone5);
                Zone zone4 = (chara2.currentZone = zone2);
                obj2.zone = zone4;
                EClass.pc.global.transition = transition;
            }
            else
            {
                Player obj3 = player;
                Zone zone4 = (EClass.pc.currentZone = EClass.game.spatials.Find(EClass.debug.startZone));
                obj3.zone = zone4;
                EClass.pc.global.transition = new ZoneTransition
                {
                    state = ZoneTransition.EnterState.Return
                };
            }
        }
        EClass.pc.homeZone.isKnown = true;
        AddAdventurers();
        player.OnStartNewGame();
        EClass.scene.Init(Scene.Mode.StartGame);
    }
References BaseCore.actionsNextFrame, LayerTitle.actor, Chara.AddCondition(), cards, Quest.ChangePhase(), EClass.core, PartyManager.Create(), Quest.Create(), CharaGen.Create(), SpatialGen.Create(), EClass.debug, CardManager.GlobalCharaList.Find(), SpatialManager.Find(), EClass.game, CardManager.globalCharas, QuestManager.globalList, Prologue.hour, Prologue.idStartZone, Scene.Init(), LayerTitle.KillActor(), Chara.mana, Stats.max, Chara.MaxHP, Player.OnStartNewGame(), EClass.pc, Prologue.posAsh, Prologue.posFiama, Prologue, quests, EClass.scene, Stats.Set(), Quest.SetClient(), Chara.SetGlobal(), spatials, Chara.stamina, QuestManager.Start(), CoreDebug.startScene, Prologue.startX, CoreDebug.startZone, and StartZone.
Referenced by CoreDebug.QuickStart(), and DramaOutcome.StartNewGame().
TryLoad()
static bool Game.TryLoad (string id, bool cloud, Action onLoad) inline static
Definition at line 302 of file Game.cs.
    {
        if (GameIO.CanLoad((cloud ? CorePath.RootSaveCloud : CorePath.RootSave) + id))
        {
            onLoad();
            return true;
        }
        EClass.ui.Say("incompatible");
        return false;
    }
References GameIO.CanLoad(), CorePath.RootSave, CorePath.RootSaveCloud, and EClass.ui.
Referenced by AM_Adv._OnUpdateInput().
Wait() [1/3]
static void Game.Wait (float a) inline static
Definition at line 284 of file Game.cs.
    {
        waitTimer = a * (float)(EClass.core.config.game.waiter * 25) / 100f;
    }
References Core.config, EClass.core, CoreConfig.game, CoreConfig.GameConfig.waiter, and waitTimer.
Wait() [2/3]
static new void Game.Wait (float a, Card c) inline static
Definition at line 276 of file Game.cs.
    {
        if (c != null && c.isSynced && !c.IsPC)
        {
            Wait(a);
        }
    }
References Card.IsPC, and Card.isSynced.
Wait() [3/3]
static new void Game.Wait (float a, Point p) inline static
Definition at line 271 of file Game.cs.
    {
        _ = p?.IsSync;
    }
References Point.IsSync.
Referenced by EClass.Wait().
Member Data Documentation
activeZone
Zone Game.activeZone
Definition at line 245 of file Game.cs.
Referenced by WidgetDate._Refresh(), Zone.Activate(), Card.AddThing(), GameDate.AdvanceHour(), Zone.Deactivate(), BaseGameScreen.Draw(), CardRenderer.Draw(), BaseGameScreen.FocusPC(), CoreConfig.GetPostEffectProfile(), Chara.IsBranchMember(), GlobalGoalVisitAndStay.OnAdvanceHour(), Chara.OnCreate(), WidgetMinimap.OnPointerDown(), Scene.OnUpdate(), HotItemFocusPos.Perform(), LayerTravel.Refresh(), UIHomeInfo.RefreshReport(), Meeting.SetChara(), WidgetHotbar.SetShortcutMenu(), Chara.Tick(), GameUpdater.Update(), GameUpdater.Update100ms(), WidgetDebug.UpdateText(), and ElementContainerCard.ValueBonus().
backupTime
double Game.backupTime
Definition at line 209 of file Game.cs.
Referenced by OnUpdate().
bp
GameBlueprint Game.bp
Definition at line 241 of file Game.cs.
cards
CardManager Game.cards = new CardManager()
Definition at line 155 of file Game.cs.
Referenced by QuestManager.Add(), Zone.AddGlobalCharasOnActivate(), QuestManager.AddQuestAsh(), QuestManager.AddQuestFiama(), Zone.AddRandomVisitor(), GameDate.AdvanceDay(), GameDate.AdvanceHour(), LayerShippingResult.Awake(), TraitSalesTag.CanTagSale(), ElementContainerFaction.CheckDirty(), Faction.CountMembers(), Card.Create(), LayerInventory.CreateContainer(), Card.Destroy(), Chara.Die(), CoreDebug.Fix_RemoveDemitas(), RefChara.Get(), RefChara.GetAndCache(), Faction.HasMember(), TaskDump.IsValidContainer(), Faction.IsWearingPanty(), TaskDump.ListThingsToPut(), Faction.OnAdvanceMonth(), Zone_WindRest.OnAfterSimulate(), Zone_Nymelle.OnBeforeSimulate(), QuestDefense.OnChangePhase(), QuestVernis.OnChangePhase(), DramaOutcome.OnClaimLand(), QuestIntroInspector.OnComplete(), QuestSharedContainer.OnComplete(), TraitDrinkMilkMother.OnDrink(), QuestDialog.OnDropReward(), Zone_DungeonPuppy.OnGenerateMap(), ElementContainerFaction.OnJoinFaith(), ElementContainerFaction.OnLeaveFaith(), ZoneInstanceBout.OnLeaveZone(), ListPeopleRevive.OnList(), OnLoad(), TraitStoryBookHome.OnRead(), QuestDebt.OnStart(), QuestExploration.OnStart(), InvOwnerDeliver.PayBill(), DramaOutcome.QuestExploration_AfterComplete(), DramaOutcome.QuestExploration_AfterCrystal(), FactionBranch.ReceivePackages(), WindowChara.RefreshProfile(), LayerQuestBoard.RefreshRanking(), Chara.RemoveGlobal(), CoreDebug.ResetPetUpgrades(), SerializedCards.Restore(), Zone.Revive(), AI_Idle.Run(), TaskDump.Run(), World.SendPackage(), Meeting.SetChara(), Chara.SetGlobal(), FactionBranch.SetOwner(), UIFactionInfo.SetZone(), UIZoneInfo.SetZone(), GameDate.ShipGoods(), GameDate.ShipPackages(), QuestManager.Start(), StartNewGame(), Zone.TryAddThingInSharedContainer(), Faction.TryPayBill(), GrowSystem.TryPick(), TraitBed.ValidateOwners(), and EloPos.WriteNote().
config
Config Game.config = new Config()
Definition at line 215 of file Game.cs.
Referenced by Chara._Move(), AM_Adv._OnUpdateInput(), WidgetSystemIndicator._Refresh(), ActPlan._Update(), CoreDebug.CheatEnabled(), Chara.Die(), ActionMode.DoFunc(), BaseTileMap.Draw(), TileMapElona.Draw(), Chara.FindNewEnemy(), ContentCodex.OnClickGetCard(), AI_Fish.ProgressFish.OnProgressComplete(), AM_Adv.OnRenderTile(), HotItemHeld.OnRenderTile(), ContentCodex.OnSwitchContent(), Chara.Pick(), ContentTactics.Refresh(), UIPlaceHelper.Refresh(), UIInventory.RefreshGrid(), BaseTileMap.RefreshHeight(), UIInventory.RefreshMenu(), GameScreenElona.RefreshPosition(), BaseGameScreen.RefreshTilt(), AI_Idle.Run(), AI_PlayMusic.Run(), GoalCombat.Run(), Card.SetFreePos(), HotItemToggle.ShouldHighlight(), HotItemContext.Show(), Chara.Tick(), WindowChara.ToggleFeatMode(), Scene.ToggleFreePos(), Scene.ToggleHighlightArea(), Scene.ToggleLight(), Scene.ToggleRoof(), Scene.ToggleShowRoof(), Scene.ToggleShowWall(), Scene.ToggleSlope(), Scene.ToggleSnapFreePos(), Scene.ToggleTilt(), Chara.TryGetThrowable(), Chara.TrySetEnemy(), and BaseGameScreen.UpdateShaders().
countLoadedMaps
int Game.countLoadedMaps
Definition at line 229 of file Game.cs.
Referenced by Zone.Activate(), and Scene.Init().
dateScratch
int Game.dateScratch
Definition at line 206 of file Game.cs.
domains
DomainManager Game.domains = new DomainManager()
Definition at line 164 of file Game.cs.
Referenced by OnLoad().
factions
FactionManager Game.factions = new FactionManager()
Definition at line 161 of file Game.cs.
Referenced by Faction.GetFactionSalary(), DramaOutcome.guild_join(), DramaOutcome.guild_trial(), Faction.Init(), OnLoad(), ContentPopulation.Refresh(), LayerFactions.RefreshFactions(), ContentFaction.RefreshFactions(), and FactionBranch.RemoveMemeber().
flags
Flags Game.flags = new Flags()
Definition at line 212 of file Game.cs.
Referenced by OnUpdate().
gameSpeedIndex
int Game.gameSpeedIndex = 1
Definition at line 223 of file Game.cs.
Referenced by ActionMode.ChangeGameSpeed(), HotItemSpeed.ShouldHighlight(), and ActionMode.TogglePause().
id
string Game.id static
Definition at line 147 of file Game.cs.
Referenced by AM_Adv._OnUpdateInput(), LayerFeedback.OnInit(), Scene.OnUpdate(), LayerLoadGame.RefreshInfo(), LayerLoadGame.RefreshList(), Map.Reload(), GameIO.SaveGame(), and CoreDebug.UpdateInput().
idDifficulty
int Game.idDifficulty
Definition at line 203 of file Game.cs.
idPrologue
int Game.idPrologue
Definition at line 200 of file Game.cs.
Referenced by DramaOutcome.fiama_gold(), UICharaMaker.ListModes(), and UICharaMaker.SetChara().
Instance
Game Game.Instance static
Definition at line 143 of file Game.cs.
isCloud
bool Game.isCloud
Definition at line 239 of file Game.cs.
Referenced by AM_Adv._OnUpdateInput(), LayerFeedback.CollectFiles(), LayerFeedback.OnInit(), Scene.OnUpdate(), Map.Reload(), and GameIO.SaveGame().
isKilling
bool Game.isKilling
Definition at line 237 of file Game.cs.
Referenced by LayerInventory.OnKill().
isLoading
bool Game.isLoading
Definition at line 235 of file Game.cs.
Referenced by RecipeCard.BuildIngredientList(), FactionBranch.OnAfterSimulate(), Zone.OnVisit(), ZoneEventDefenseGame.OnVisit(), ZoneEventHarvest.OnVisit(), ZoneEventMusic.OnVisit(), ZoneEventSubdue.OnVisit(), WidgetHP.Refresh(), and Zone.Simulate().
isPaused
bool Game.isPaused static
Definition at line 149 of file Game.cs.
Referenced by GameUpdater.CharaUpdater.FixedUpdate().
lastActiveZone
Zone Game.lastActiveZone
Definition at line 247 of file Game.cs.
Referenced by LayerPeople.CreateSelectEmbarkMembers().
lastGameSpeedIndex
int Game.lastGameSpeedIndex = 1
Definition at line 225 of file Game.cs.
Referenced by ActionMode.UnPause().
loadedTextures
HashSet<Texture2D> Game.loadedTextures = new HashSet<Texture2D>()
Definition at line 251 of file Game.cs.
Referenced by Card.GetPaintSprite().
log
MsgLog Game.log
Initial value:
= new MsgLog
    {
        id = "log"
    }
Definition at line 185 of file Game.cs.
Referenced by ContentChronicle.OnSwitchContent(), and Msg.SayRaw().
lostThings
List<Thing> Game.lostThings = new List<Thing>()
Definition at line 218 of file Game.cs.
parties
PartyManager Game.parties = new PartyManager()
Definition at line 170 of file Game.cs.
player
new Player Game.player = new Player()
Definition at line 176 of file Game.cs.
Referenced by Core.Awake(), GameIndex.Create(), Load(), OnLoad(), OnUpdate(), and ItemCulture.Refresh().
principal
GamePrincipal Game.principal = new GamePrincipal()
Definition at line 221 of file Game.cs.
Referenced by AM_Adv._OnUpdateInput(), LayerWorldSetting.Apply(), GameIndex.Create(), Card.DamageHP(), Map.DropBlockComponent(), Card.GetExpMtp(), GamePrincipal.Item.IsModified(), GamePrincipal.Item.IsSealed(), ActEffect.LoveMiracle(), Map.MineBlock(), Map.MineObj(), Faction.OnAdvanceMonth(), TaskHarvest.OnCreateProgress(), LayerWorldSetting.OnInit(), Scene.OnUpdate(), GrowSystem.PopMineObj(), Chara.RefreshSpeed(), CoreDebug.ResetPrincipalSeals(), Chara.Revive(), HotItemContext.Show(), Card.SpawnLoot(), GrowSystem.TryPopSeed(), and GamePrincipal.Item.WasSealed().
quests
QuestManager Game.quests = new QuestManager()
Definition at line 179 of file Game.cs.
Referenced by InvOwnerDeliver._OnProcess(), ActPlan._Update(), QuestManager.Add(), GameDate.AdvanceDay(), GameDate.AdvanceHour(), DramaCustomSequence.Build(), QuestVernis.CanUpdateOnTalk(), Quest.Complete(), QuestCraft.Deliver(), QuestDeliver.Deliver(), AI_PlayMusic.Evaluate(), ZonePreEnterOnCompleteQuestInstance.Execute(), Player.ExitBorder(), Quest.Fail(), Recipe.GetQuestTrack(), Chara.GiveGift(), TraitDoorman_Fighter.GiveTrial(), TraitDoorman_Mage.GiveTrial(), TraitDoorman_Thief.GiveTrial(), DramaOutcome.guild_trial(), Quest.Init(), Scene.Init(), Chara.IsEscorted(), RecipeManager.ListSources(), DramaOutcome.melilith_friend(), Player.ModKarma(), Zone_Exile.OnActivate(), Trait.OnBarter(), QuestDefense.OnChangePhase(), DramaOutcome.OnClaimLand(), ItemQuestTracker.OnClickClose(), QuestIntroInspector.OnComplete(), QuestLoytelFarm.OnComplete(), QuestSharedContainer.OnComplete(), QuestShippingChest.OnComplete(), QuestVernis.OnComplete(), Quest.OnCompleteTask(), TCExtra.OnDraw(), QuestDialog.OnDropReward(), Zone_DungeonPuppy.OnGenerateMap(), OnLoad(), TraitStoryBookHome.OnRead(), QuestExploration.OnStart(), QuestIntoDarkness.OnStart(), Player.OnStartNewGame(), ContentQuest.OnSwitchContent(), DramaManager.ParseLine(), InvOwnerDeliver.PayBill(), DramaOutcome.poppy_found(), DramaOutcome.QuestDebt_reward(), DramaOutcome.QuestExploration_AfterComplete(), DramaOutcome.QuestExploration_AfterCrystal(), DramaOutcome.QuestExploration_MeetFarris(), DramaOutcome.QuestExploration_MeetFarris2(), CoreDebug.QuickStart(), ItemQuestTracker.Refresh(), LayerShippingResult.Refresh(), WidgetQuestTracker.Refresh(), TCOrbitChara.RefreshAll(), LayerQuestBoard.RefreshQuest(), CoreDebug.Reset_LoytelDebt(), RecipeUpdater.RunRecipe(), ItemQuest.SetQuest(), Chara.ShowDialog(), StartNewGame(), Chara.Tick(), Recipe.ToggleTrack(), Chara.TryDropBossLoot(), WidgetQuestTracker.TryShow(), TraitTeleporter.TryTeleport(), CoreDebug.UpdateInput(), and Zone.UpdateQuests().
referenceMap
Dictionary<string, IGlobalValue> Game.referenceMap = new Dictionary<string, IGlobalValue>()
Definition at line 249 of file Game.cs.
relations
RelationManager Game.relations = new RelationManager()
Definition at line 182 of file Game.cs.
Referenced by GameDate.AdvanceDay().
religions
ReligionManager Game.religions = new ReligionManager()
Definition at line 158 of file Game.cs.
Referenced by LayerFaith.Activate(), DramaOutcome.convert_Jure(), GameLang.ConvertDrama(), Chara.Cuddle(), Card.GetPrice(), Religion.IsValidArtifact(), Religion.JoinFaith(), Religion.LeaveFaith(), Zone_Aquli.OnActivate(), Zone_Mifu.OnActivate(), Zone_Nefu.OnActivate(), Chara.OnCreate(), TraitAltar.OnCreate(), TraitBaseSpellbook.OnCreate(), TraitFollower.OnCreate(), FactionBranch.OnCreate(), Player.OnCreateGame(), Zone_SubTown.OnGenerateRooms(), TraitAltar.OnImportMap(), OnLoad(), TraitBaseSpellbook.OnRead(), FactionBranch.OnSimulateDay(), Player.OnStartNewGame(), ActEffect.Proc(), Religion.Punish(), Religion.Reforge(), LayerFactions.RefreshFactions(), ContentFaction.RefreshFactions(), Chara.SetFaith(), TraitBaseSpellbook.SetName(), Chara.ShowDialog(), Zone.SpawnAltar(), CoreDebug.Test_GodTalk(), Zone.TrySpawnFollower(), ActEffect.Wish(), and Thing.WriteNote().
saveCount
int Game.saveCount
Definition at line 231 of file Game.cs.
seed
int Game.seed
Definition at line 197 of file Game.cs.
Referenced by LayerShippingResult.Awake(), ThingGen.CreateTreasureContent(), Chara.GetFavCat(), Chara.GetFavFood(), Thing.GetName(), Zone.GetOrCreateFortuneRollData(), RecipeManager.OnSleep(), FortuneRollData.RefreshPrize(), AI_OpenGambleChest.Run(), and ResearchManager.ShowNewPlans().
sessionMin
int Game.sessionMin
Definition at line 227 of file Game.cs.
Referenced by QueueList< T >.GetTask(), and TaskList< T >.GetTask().
spatials
SpatialManager Game.spatials = new SpatialManager()
Definition at line 152 of file Game.cs.
Referenced by AM_Adv._OnUpdateInput(), Zone.CanDestroy(), Faction.CountTerritories(), ThingGen.CreateCardboardBox(), Zone.Destroy(), RefZone.Get(), Faction.GetChildren(), RankedZoneManager.GetList(), Faction.GetRankIncome(), TeleportManager.GetTeleportZone(), Quest.ListDeliver(), Region.ListTowns(), Region.ListTravelZones(), Region.ListZonesInRadius(), TraitMoongate.LoadMap(), Chara.MoveZone(), Chara.OnBanish(), Trait.OnBarter(), Meeting.OnEndDrama(), ZoneInstanceBout.OnLeaveZone(), OnLoad(), Scene.OnUpdate(), DramaManager.ParseLine(), ActEffect.Proc(), CoreDebug.QuickStart(), ContentHomeRanking.Refresh(), LayerShippingResult.Refresh(), UIHomeInfo.RefreshInfo(), LayerMapList.RefreshList(), WindowChara.RefreshProfile(), ContentFaction.RefreshZones(), LayerFactions.RefreshZones(), LayerLocation.RefreshZones(), Spatial.Register(), GameIO.SaveGame(), Meeting.SetChara(), UIFactionInfo.SetZone(), TraitTicketFurniture.SetZone(), GameDate.ShipGoods(), LayerShippingResult.Show(), StartNewGame(), Chara.Tick(), TraitMapBoard.TrySetAct(), GameUpdater.Update(), HomeResourceWorth.UpdateRank(), and TraitMoongate.UseMoongate().
teleports
TeleportManager Game.teleports = new TeleportManager()
Definition at line 194 of file Game.cs.
Referenced by TraitTeleporter.OnChangePlaceState(), TraitTeleporter.TrySetAct(), and TraitTeleporter.TryTeleport().
timeSinceStart
float Game.timeSinceStart
Definition at line 233 of file Game.cs.
Referenced by OnUpdate().
uniforms
PCCUniformManager Game.uniforms = new PCCUniformManager()
Definition at line 191 of file Game.cs.
Referenced by LayerEditPCC.Activate(), LayerEditPCC.Apply(), and Chara.ApplyJob().
updater
GameUpdater Game.updater = new GameUpdater()
Definition at line 243 of file Game.cs.
Referenced by AM_Adv._OnUpdateInput(), Scene.Init(), AM_Adv.OnBecomeNoGoal(), LayerCraftFloat.OnSwitchContent(), OnUpdate(), Scene.OnUpdate(), LayerCraftFloat.RefreshCraft(), Core.Update100ms(), CoreDebug.UpdateInput(), and WidgetDebug.UpdateText().
version
Version Game.version
Definition at line 167 of file Game.cs.
waitTimer
float Game.waitTimer static
Definition at line 145 of file Game.cs.
Referenced by OnUpdate(), and Wait().
welcomeTimer
float Game.welcomeTimer private
Definition at line 253 of file Game.cs.
world
new World Game.world
Definition at line 173 of file Game.cs.
Referenced by GameIndex.Create(), ThingGen.CreateMap(), Chara.MoveHome(), OnLoad(), HotItemContext.Show(), and CoreDebug.UpdateInput().
Property Documentation
altAbility
bool Game.altAbility get
Definition at line 267 of file Game.cs.
Referenced by LayerAbility.OnInit(), ButtonAbility.SetAct(), and UI.ToggleAbility().
altCraft
bool Game.altCraft get
Definition at line 265 of file Game.cs.
Referenced by Scene.Init().
altInv
bool Game.altInv get
Definition at line 263 of file Game.cs.
Referenced by LayerInventory._Create(), Load(), UIInventory.RefreshHighlight(), and LayerInventory.SetDirty().
altUI
bool Game.altUI get
Definition at line 261 of file Game.cs.
Referenced by ActionMode.Activate(), BuildMenu.Deactivate(), and BuildMenu.Init().
IsWaiting
bool Game.IsWaiting static get
Definition at line 255 of file Game.cs.
Referenced by Scene.OnUpdate().
Prologue
Prologue Game.Prologue get
Definition at line 257 of file Game.cs.
Referenced by Faction.GetBaseTax(), UICharaMaker.ListModes(), World.OnCreate(), Player.Flags.OnEnterZone(), DramaOutcome.QuestDefense_0(), DramaOutcome.QuestDefense_1(), CoreDebug.QuickStart(), UICharaMaker.Refresh(), StartNewGame(), and DramaOutcome.StartNewGame2().
StartZone
Zone Game.StartZone get
Definition at line 269 of file Game.cs.
Referenced by Zone.AbandonZone(), GameDate.AdvanceDay(), Player.CanExitBorder(), Zone.ClaimZone(), Player.EnterLocalZone(), FactionBranch.OnClaimZone(), TraitDeed.OnRead(), DramaOutcome.QuestExploration_AfterCrystal(), DramaOutcome.QuestExploration_MeetFarris(), RegionPoint.SetRegionPoint(), StartNewGame(), and TraitCoreZone.TrySetAct().
UseGrid
bool Game.UseGrid get
Definition at line 259 of file Game.cs.
Referenced by InvOwner.OnDrag(), and InvOwner.Transaction.Process().
The documentation for this class was generated from the following file:
Elin/Game.cs