Elin Decompiled Documentation: AM_Picker Class Reference
AM_Picker Class Reference
Classes
struct Result
Public Member Functions
override void OnUpdateCursor ()
override HitResult HitTest (Point point, Point start)
override void OnProcessTiles (Point point, int dir)
override void OnRenderTile (Point point, HitResult result, int dir)
Result TestBlock (Point point)
Result TestObj (Point point)
Result TestFloor (Point point)
Result TestThing (Thing t)
Result Test (Point point, bool select=false)
RecipeSource TryGetRecipe (string id)
new bool Select (Result r)
Public Member Functions inherited from ActionMode
virtual int TopHeight (Point p)
virtual void SEExecuteSummary ()
virtual bool HighlightWall (Point p)
virtual void OnClickSubMenu (int a)
virtual string OnSetSubMenuButton (int a, UIButton b)
virtual bool IsRoofEditMode (Card c=null)
virtual bool IsFillMode ()
virtual int GetDefaultTile (Point p)
virtual void OnShowExtraHint (UINote n)
void Activate (bool toggle=true, bool forceActivate=false)
virtual void OnActivate ()
void RefreshTexts ()
virtual string GetSimpleText (Card c)
void ClearSimpleTexts ()
void Deactivate ()
virtual void OnDeactivate ()
virtual void OnCancel ()
virtual void OnBeforeUpdate ()
virtual void OnAfterUpdate ()
virtual void OnUpdateCursor ()
void OnRotate ()
void SetCursorOnMap (CursorInfo cursor)
void UpdateInput ()
void InputMovement ()
virtual void InputWheel (int wheel)
virtual void OnUpdateInput ()
void DoFunc (CoreConfig.GameFuncBuild func)
bool IsFuncPressed (CoreConfig.GameFunc func)
void DoFunc (CoreConfig.GameFunc func)
virtual void OnScroll ()
void TryRightClickCloseWidget ()
bool TryShowWidgetMenu ()
HitResult _HitTest (Point point, Point start)
virtual HitResult HitTest (Point point, Point start)
virtual void OnSelectStart (Point point)
virtual void OnSelectEnd (bool cancel)
virtual MeshPass GetGuidePass (Point point)
virtual void OnRenderTile (Point point, HitResult result, int dir)
void OnRenderTileFloor (Point point, HitResult result)
virtual bool CanProcessTiles ()
virtual void OnBeforeProcessTiles ()
virtual void OnProcessTiles (Point point, int dir)
virtual void OnAfterProcessTiles (Point start, Point end)
virtual void OnFinishProcessTiles ()
virtual void OnRefreshSummary (Point point, HitResult result, HitSummary summary)
void ShowLayer ()
virtual Layer OnShowLayer ()
void HideLayer ()
virtual void OnHideLayer ()
virtual string GetHintText ()
virtual void RotateUnderMouse ()
virtual ref string SetMouseInfo (ref string s)
void TogglePause ()
void Pause (bool sound=false)
void UnPause (bool sound=false)
void ChangeGameSpeed (int a, bool sound=false)
Properties
override bool IsBuildMode [get]
override BaseTileSelector.HitType hitType [get]
override BaseTileSelector.SelectType selectType [get]
BuildMenu BM [get]
bool CanActivate [get]
Properties inherited from AM_BaseTileSelect
override CursorInfo DefaultCursor [get]
override bool enableMouseInfo [get]
override bool ShowMouseoverTarget [get]
override bool CanSelectTile [get]
override AreaHighlightMode AreaHihlight [get]
TaskManager.Designations Designations [get]
override string idSound [get]
override bool AllowMiddleClickFunc [get]
override bool ShowMaskedThings [get]
Properties inherited from ActionMode
static AM_Adv AdvOrRegion [get]
static bool IsAdv [get]
virtual float gameSpeed [get]
bool IsActive [get]
virtual BaseTileSelector.HitType hitType [get]
virtual BaseTileSelector.SelectType selectType [get]
virtual BaseTileSelector.BoxType boxType [get]
virtual bool ContinuousClick [get]
virtual int hitW [get]
virtual int hitH [get]
HitSummary Summary [get]
bool Multisize [get]
virtual string id [get]
virtual CursorInfo DefaultCursor [get]
virtual string idHelpTopic [get]
virtual string idSound [get]
virtual bool enableMouseInfo [get]
virtual bool hideBalloon [get]
virtual string textHintTitle [get]
virtual bool AllowAutoClick [get]
virtual bool ShowActionHint [get]
virtual bool ShowMouseoverTarget [get]
virtual AreaHighlightMode AreaHihlight [get]
virtual bool CanSelectTile [get]
virtual bool CanTargetOutsideBounds [get]
virtual bool ShouldPauseGame [get]
virtual bool FixFocus [get]
virtual bool HideSubWidgets [get]
virtual bool IsBuildMode [get]
virtual bool ShowBuildWidgets [get]
virtual BuildMenu.Mode buildMenuMode [get]
virtual bool ShouldHideBuildMenu [get]
virtual bool CanTargetFog [get]
virtual int CostMoney [get]
virtual bool AllowBuildModeShortcuts [get]
virtual bool AllowMiddleClickFunc [get]
virtual bool AllowHotbar [get]
virtual bool AllowGeneralInput [get]
virtual bool ShowMaskedThings [get]
virtual int SelectorHeight [get]
virtual bool AllowWheelZoom [get]
virtual float TargetZoom [get]
virtual BaseTileMap.CardIconMode cardIconMode [get]
virtual BaseGameScreen TargetGameScreen [get]
virtual bool IsNoMap [get]
virtual bool UseSubMenu [get]
virtual bool UseSubMenuSlider [get]
virtual bool SubMenuAsGroup [get]
virtual int SubMenuModeIndex [get]
virtual bool ShowExtraHint [get]
BaseTileSelector tileSelector [get]
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Additional Inherited Members
Static Public Member Functions inherited from ActionMode
static void OnGameInstantiated ()
Static Public Member Functions inherited from EClass
static int rndSeed (int a, int seed)
static int rnd (long a)
static int rnd (int a)
static int curve (int _a, int start, int step, int rate=75)
static int sqrt (int a)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Public Attributes inherited from ActionMode
Layer layer
int brushRadius = 4
Static Public Attributes inherited from ActionMode
static ActionMode DefaultMode
static AM_Title Title = new AM_Title()
static AM_Sim Sim
static AM_ViewZone View
static AM_Adv Adv
static AM_Region Region
static AM_ADV_Target AdvTarget
static AM_EloMap EloMap
static AM_Inspect Inspect
static AM_NoMap NoMap
static AM_MiniGame MiniGame
static AM_NewZone NewZone
static AM_Bird Bird
static AM_Mine Mine
static AM_Dig Dig
static AM_Harvest Harvest
static AM_Cut Cut
static AM_StateEditor StateEditor
static AM_Picker Picker
static AM_Copy Copy
static AM_Blueprint Blueprint
static AM_Build Build
static AM_CreateArea CreateArea
static AM_EditArea EditArea
static AM_ExpandArea ExpandArea
static AM_Deconstruct Deconstruct
static AM_Select Select
static AM_RemoveDesignation RemoveDesignation
static AM_ViewMap ViewMap
static AM_Terrain Terrain
static AM_Populate Populate
static AM_EditMarker EditMarker
static AM_Visibility Visibility
static AM_Cinema Cinema
static AM_Paint Paint
static AM_FlagCell FlagCell
static ActionMode LastBuildMode
static SourceMaterial.Row lastEditorMat
static bool ignoreSound
static float[] GameSpeeds = new float[4] { 0f, 1f, 2f, 5f }
static List< TCSimpleText > simpleTexts = new List<TCSimpleText>()
static float hotElementTimer
Static Public Attributes inherited from EClass
static Core core
Static Protected Attributes inherited from ActionMode
static Vector3 mpos
Detailed Description
Definition at line 4 of file AM_Picker.cs.
Member Function Documentation
HitTest()
override HitResult AM_Picker.HitTest (Point point, Point start) inline virtual
Reimplemented from ActionMode.
Definition at line 57 of file AM_Picker.cs.
    {
        if (!Test(point).IsValid)
        {
            return HitResult.Default;
        }
        return HitResult.Valid;
    }
References Test.
OnProcessTiles()
override void AM_Picker.OnProcessTiles (Point point, int dir) inline virtual
Reimplemented from ActionMode.
Definition at line 66 of file AM_Picker.cs.
    {
        Test(point, select: true);
    }
References Test.
OnRenderTile()
override void AM_Picker.OnRenderTile (Point point, HitResult result, int dir) inline virtual
Reimplemented from ActionMode.
Definition at line 71 of file AM_Picker.cs.
    {
        if (point.cell.HasWallOrFence && (result == HitResult.Valid || result == HitResult.Invalid))
        {
            EClass.screen.guide.DrawWall(point, (result == HitResult.Valid) ? EClass.Colors.blockColors.Valid : EClass.Colors.blockColors.Warning);
        }
        else
        {
            base.OnRenderTile(point, result, dir);
        }
    }
References ColorProfile.blockColors, Point.cell, EClass.Colors, ScreenGuide.DrawWall(), BaseGameScreen.guide, Cell.HasWallOrFence, EClass.screen, ColorProfile.BlockColors.Valid, and ColorProfile.BlockColors.Warning.
OnUpdateCursor()
override void AM_Picker.OnUpdateCursor () inline virtual
Reimplemented from ActionMode.
Definition at line 52 of file AM_Picker.cs.
    {
        SetCursorOnMap(CursorSystem.Picker);
    }
References CursorSystem.Picker, and ActionMode.SetCursorOnMap().
Select()
new bool AM_Picker.Select (Result r) inline
Definition at line 195 of file AM_Picker.cs.
    {
        ActionMode.ignoreSound = true;
        BM.Select(r);
        return true;
    }
References BM, and BuildMenu.Select().
Referenced by InspectGroupBlock.OnSetActions(), and InspectGroupThing.OnSetActions().
Test()
Result AM_Picker.Test (Point point, bool select = false) inline
Definition at line 128 of file AM_Picker.cs.
    {
        List<Card> list = point.ListCards(includeMasked: true);
        for (int num = list.Count - 1; num >= 0; num--)
        {
            Card card = list[num];
            if (card.isThing)
            {
                Result result = TestThing(card.Thing);
                if (result.IsValid)
                {
                    if (select)
                    {
                        Select(result);
                    }
                    if (card.trait is TraitHouseBoard houseBoard)
                    {
                        ActionMode.Build.houseBoard = houseBoard;
                    }
                    return result;
                }
            }
        }
        if (point.HasBlock)
        {
            Result result2 = TestBlock(point);
            if (result2.IsValid)
            {
                if (select)
                {
                    Select(result2);
                }
                return result2;
            }
        }
        if (EClass.debug.godBuild && point.HasObj)
        {
            Result result3 = TestObj(point);
            if (result3.IsValid)
            {
                if (select)
                {
                    Select(result3);
                }
                return result3;
            }
        }
        if (point.HasFloor)
        {
            Result result4 = TestFloor(point);
            if (result4.IsValid)
            {
                if (select)
                {
                    Select(result4);
                }
                return result4;
            }
        }
        return default(Result);
    }
References card, EClass.debug, CoreDebug.godBuild, Point.HasBlock, Point.HasFloor, Point.HasObj, AM_Picker.Result.IsValid, Point.ListCards(), ActionMode.Select, TestBlock(), TestFloor(), TestObj(), and TestThing().
Referenced by BaseTileSelector.RefreshMouseInfo().
TestBlock()
Result AM_Picker.TestBlock (Point point) inline
Definition at line 83 of file AM_Picker.cs.
    {
        Result result = default(Result);
        result.mat = point.matBlock;
        result.source = TryGetRecipe(point.sourceBlock.RecipeID);
        return result;
    }
References Point.matBlock, Point.sourceBlock, and TryGetRecipe().
Referenced by InspectGroupBlock.OnSetActions(), and Test().
TestFloor()
Result AM_Picker.TestFloor (Point point) inline
Definition at line 99 of file AM_Picker.cs.
    {
        Result result = default(Result);
        if (point.cell._bridge == 0)
        {
            result.mat = point.matFloor;
            result.source = TryGetRecipe(point.sourceFloor.RecipeID);
        }
        else
        {
            result.mat = point.cell.matBridge;
            result.source = TryGetRecipe(point.cell.sourceBridge.RecipeID + "-b");
        }
        return result;
    }
References Cell._bridge, Point.cell, Cell.matBridge, Point.matFloor, Cell.sourceBridge, Point.sourceFloor, and TryGetRecipe().
Referenced by Test().
TestObj()
Result AM_Picker.TestObj (Point point) inline
Definition at line 91 of file AM_Picker.cs.
    {
        Result result = default(Result);
        result.mat = point.cell.matObj;
        result.source = TryGetRecipe(point.sourceObj.RecipeID);
        return result;
    }
References Point.cell, Cell.matObj, Point.sourceObj, and TryGetRecipe().
Referenced by Test().
TestThing()
Result AM_Picker.TestThing (Thing t) inline
Definition at line 115 of file AM_Picker.cs.
    {
        Result result = default(Result);
        if (t.trait.IsGround)
        {
            return result;
        }
        result.mat = t.material;
        result.source = TryGetRecipe(t.sourceCard.RecipeID);
        result.thing = t;
        return result;
    }
References Trait.IsGround, Card.material, RenderRow.RecipeID, Thing.sourceCard, Card.trait, and TryGetRecipe().
Referenced by InspectGroupThing.OnSetActions(), and Test().
TryGetRecipe()
RecipeSource AM_Picker.TryGetRecipe (string id) inline
Definition at line 190 of file AM_Picker.cs.
    {
        return EClass.player.recipes.GetSource(id);
    }
References RecipeManager.GetSource(), EClass.player, and Player.recipes.
Referenced by TestBlock(), TestFloor(), TestObj(), and TestThing().
Property Documentation
BM
BuildMenu AM_Picker.BM get
Definition at line 30 of file AM_Picker.cs.
Referenced by Select().
CanActivate
bool AM_Picker.CanActivate get
Definition at line 32 of file AM_Picker.cs.
    {
        get
        {
            if (!base.IsActive)
            {
                if (!EClass.debug.godBuild)
                {
                    if (EClass.Branch != null)
                    {
                        return EClass.Branch.elements.Has(4005);
                    }
                    return false;
                }
                return true;
            }
            return false;
        }
    }
Referenced by ActionMode.DoFunc(), and ActionMode.UpdateInput().
hitType
override BaseTileSelector.HitType AM_Picker.hitType get
Definition at line 26 of file AM_Picker.cs.
IsBuildMode
override bool AM_Picker.IsBuildMode get
Definition at line 24 of file AM_Picker.cs.
selectType
override BaseTileSelector.SelectType AM_Picker.selectType get
Definition at line 28 of file AM_Picker.cs.
The documentation for this class was generated from the following file:
Elin/AM_Picker.cs