Elin Decompiled Documentation: ModifiedShadow Class Reference
ModifiedShadow Class Reference
Public Member Functions
override void ModifyMesh (VertexHelper vh)
virtual void ModifyVertices (List< UIVertex > verts)
Detailed Description
Definition at line 5 of file ModifiedShadow.cs.
Member Function Documentation
ModifyMesh()
override void ModifiedShadow.ModifyMesh (VertexHelper vh) inline
Definition at line 7 of file ModifiedShadow.cs.
    {
        if (IsActive())
        {
            List<UIVertex> list = ListPool<UIVertex>.Get();
            vh.GetUIVertexStream(list);
            ModifyVertices(list);
            vh.Clear();
            vh.AddUIVertexTriangleStream(list);
            ListPool<UIVertex>.Release(list);
        }
    }
References ListPool< T >.Get(), ModifyVertices(), and ListPool< T >.Release().
ModifyVertices()
virtual void ModifiedShadow.ModifyVertices (List< UIVertex > verts) inline virtual
Reimplemented in BoxOutline, CircleOutline, and Outline8.
Definition at line 20 of file ModifiedShadow.cs.
    {
    }
Referenced by ModifyMesh().
The documentation for this class was generated from the following file:
Elin/Plugins.UI/ModifiedShadow.cs