Elin Decompiled Documentation: SourceCollectible Class Reference
SourceCollectible Class Reference
Classes
class Row
Public Member Functions
override Row CreateRow ()
override Row CreateRowByMapping (IReadOnlyDictionary< string, int > mapping)
override void SetRow (Row r)
override IReadOnlyDictionary< string, int > GetRowMapping ()
Public Member Functions inherited from SourceDataString< SourceCollectible.Row >
override T GetRow (string id)
Static Public Attributes
static readonly IReadOnlyDictionary< string, int > RowMapping
Detailed Description
Definition at line 4 of file SourceCollectible.cs.
Member Function Documentation
CreateRow()
override Row SourceCollectible.CreateRow () inline
Definition at line 57 of file SourceCollectible.cs.
    {
        return new Row
        {
            id = SourceData.GetString(0),
            name_JP = SourceData.GetString(1),
            name = SourceData.GetString(2),
            rarity = SourceData.GetInt(3),
            prefab = SourceData.GetString(4),
            num = SourceData.GetInt(5),
            filter = SourceData.GetString(6),
            tag = SourceData.GetStringArray(7),
            sound = SourceData.GetString(8),
            detail_JP = SourceData.GetString(9),
            detail = SourceData.GetString(10)
        };
    }
References SourceData< T, T2 >.GetInt(), SourceData< T, T2 >.GetString(), and SourceData< T, T2 >.GetStringArray().
CreateRowByMapping()
override Row SourceCollectible.CreateRowByMapping (IReadOnlyDictionary< string, int > mapping) inline
Definition at line 75 of file SourceCollectible.cs.
    {
        return new Row
        {
            id = SourceData.GetString(mapping["id"]),
            name_JP = SourceData.GetString(mapping["name_JP"]),
            name = SourceData.GetString(mapping["name"]),
            rarity = SourceData.GetInt(mapping["rarity"]),
            prefab = SourceData.GetString(mapping["prefab"]),
            num = SourceData.GetInt(mapping["num"]),
            filter = SourceData.GetString(mapping["filter"]),
            tag = SourceData.GetStringArray(mapping["tag"]),
            sound = SourceData.GetString(mapping["sound"]),
            detail_JP = SourceData.GetString(mapping["detail_JP"]),
            detail = SourceData.GetString(mapping["detail"])
        };
    }
References SourceData< T, T2 >.GetInt(), SourceData< T, T2 >.GetString(), and SourceData< T, T2 >.GetStringArray().
GetRowMapping()
override IReadOnlyDictionary< string, int > SourceCollectible.GetRowMapping () inline
Definition at line 98 of file SourceCollectible.cs.
    {
        return RowMapping;
    }
References RowMapping.
SetRow()
override void SourceCollectible.SetRow (Row r) inline
Definition at line 93 of file SourceCollectible.cs.
    {
        map[r.id] = r;
    }
References SourceCollectible.Row.id.
Member Data Documentation
RowMapping
readonly IReadOnlyDictionary<string, int> SourceCollectible.RowMapping static
Initial value:
= new Dictionary<string, int>
    {
        ["id"] = 0,
        ["name_JP"] = 1,
        ["name"] = 2,
        ["rarity"] = 3,
        ["prefab"] = 4,
        ["num"] = 5,
        ["filter"] = 6,
        ["tag"] = 7,
        ["sound"] = 8,
        ["detail_JP"] = 9,
        ["detail"] = 10
    }
Definition at line 42 of file SourceCollectible.cs.
Referenced by GetRowMapping().
The documentation for this class was generated from the following file:
Elin/SourceCollectible.cs