Elin Decompiled Documentation: ButtonAbility Class Reference
ButtonAbility Class Reference
Public Member Functions
void SetAct (Chara _chara, Element e)
void OnDrag (PointerEventData data)
override void OnPointerUp (PointerEventData eventData)
void Use ()
void HoldAbility ()
bool CanAutoUse (Act _act)
bool ShowMouseHintLeft ()
string GetTextMouseHintLeft ()
bool ShowMouseHintRight ()
string GetTextMouseHintRight ()
override bool CanMiddleClick ()
override void OnMiddleClick (bool forceClick)
void ToggleFav ()
void RefreshFavIcon ()
Public Member Functions inherited from UIButton
virtual bool CanMiddleClick ()
virtual void OnMiddleClick (bool forceClick)
void SetItem (Item i)
virtual void RefreshItem ()
virtual void OnHover ()
void Toggle ()
void ToggleCheck ()
void SetCheck (bool check)
void SetToggle (bool isOn, Action< bool > onToggle=null)
void SetToggleWithScore (bool isOn, Action< bool > onToggle, int? score)
void SetTooltip (Action< UITooltip > onShowTooltip=null, bool enable=true)
void SetTooltip (string id, Action< UITooltip > onShowTooltip=null, bool enable=true)
void SetTooltipLang (string lang=null)
virtual void ShowTooltip ()
void ShowTooltipForced (bool ignoreWhenRightClick=true)
override void OnPointerDown (PointerEventData eventData)
override void OnPointerClick (PointerEventData eventData)
override void OnPointerUp (PointerEventData eventData)
void OnPointerUpOnDrag (PointerEventData eventData)
void _OnPress ()
void OnPress ()
void AddHighlight (Func< bool > killCondition)
void DoHighlightTransition (bool instant=false)
void DoNormalTransition (bool instant=true)
override Selectable FindSelectableOnDown ()
override Selectable FindSelectableOnUp ()
override Selectable FindSelectableOnLeft ()
override Selectable FindSelectableOnRight ()
void SetNavigation (UIButton up, UIButton down=null, UIButton left=null, UIButton right=null)
override bool IsActive ()
void SetInteractableWithAlpha (bool enable)
virtual void ApplySkin ()
void ApplySkin ()
bool ShowMouseHintLeft ()
string GetTextMouseHintLeft ()
bool ShowMouseHintRight ()
string GetTextMouseHintRight ()
Static Public Member Functions
static bool TryUse (Act act, Card tg=null, Point pos=null, Card catalyst=null, bool first=true, bool mouse=true)
static bool SpecialHoldAction (Act act)
Static Public Member Functions inherited from UIButton
static void UpdateButtons ()
static void TryHihlight ()
static void TryShowTip (Transform root=null, bool highlight=true, bool ignoreWhenRightClick=true)
static void TryShowTip< T > (Transform root=null, bool highlight=true, bool ignoreWhenRightClick=false)
Public Attributes
SourceElement.Row source
IDragParent dragParent
UIText textStock
Image imageType
Image imageFav
Transform attach
Transform transFav
Chara chara
Act act
bool dragged
Public Attributes inherited from UIButton
UIText mainText
UIText subText
UIText subText2
UIText keyText
Image icon
Image imageCheck
Graphic[] targetGraphics
float scaleIcon = 1f
float slideX
float navigationFix
bool isChecked
bool instantClick = true
UISelectableGroup group
TooltipData tooltip
SoundData soundClick
SoundData soundHighlight
Transform animeTarget
Anime animeClick
Anime animeHold
ButtonType buttonType
BaseSkinRoot skinRoot
Action onDoubleClick
Action onRightClick
Action< int > onInputWheel
object refObj
int refInt
string refStr
bool animating
bool selected
Vector3 originalIconScale = Vector3.one
UIButton highlightTarget
Item item
Static Public Attributes
static Act hotkeyAct
static float hotkeyTimer
static bool usedMouseKey
static bool lockUse
Static Public Attributes inherited from UIButton
static bool DoSlide
static bool locked
static UIButton lastButton
static UIButton lastHovered
static UIButton currentHighlight
static UIButton currentPressedButton
static float lastClicked
static float doubleClickTime = 0.4f
static Vector2 buttonPos
static Action onPressed
static List< UIButton > buttons = new List<UIButton>()
static Action actionTooltip
Additional Inherited Members
Protected Member Functions inherited from UIButton
override void Awake ()
override void OnEnable ()
override void DoStateTransition (SelectionState state, bool instant)
Properties inherited from UIButton
List< Graphic > Graphics [get]
virtual bool CanDragLeftButton [get]
Detailed Description
Definition at line 6 of file ButtonAbility.cs.
Member Function Documentation
CanAutoUse()
bool ButtonAbility.CanAutoUse (Act _act) inline
Definition at line 250 of file ButtonAbility.cs.
    {
        if (_act.TargetType.CanSelectSelf)
        {
            if (EClass._zone.IsRegion)
            {
                return !_act.LocalAct;
            }
            return true;
        }
        return false;
    }
References EClass._zone, TargetType.CanSelectSelf, Spatial.IsRegion, Act.LocalAct, and Act.TargetType.
Referenced by ShowMouseHintRight(), and Use().
CanMiddleClick()
override bool ButtonAbility.CanMiddleClick () inline virtual
Reimplemented from UIButton.
Definition at line 283 of file ButtonAbility.cs.
    {
        return EClass.ui.AllowInventoryInteractions;
    }
References EClass.ui.
GetTextMouseHintLeft()
string ButtonAbility.GetTextMouseHintLeft () inline
Implements IMouseHint.
Definition at line 268 of file ButtonAbility.cs.
    {
        return "";
    }
GetTextMouseHintRight()
string ButtonAbility.GetTextMouseHintRight () inline
Implements IMouseHint.
Definition at line 278 of file ButtonAbility.cs.
    {
        return "actUse".lang();
    }
HoldAbility()
void ButtonAbility.HoldAbility () inline
Definition at line 244 of file ButtonAbility.cs.
    {
        EClass.player.SetCurrentHotItem(new HotItemAct(source));
        SE.SelectHotitem();
    }
References EClass.player, Player.SetCurrentHotItem(), and source.
Referenced by OnMiddleClick(), and Use().
OnDrag()
void ButtonAbility.OnDrag (PointerEventData data) inline
Definition at line 80 of file ButtonAbility.cs.
    {
        if (dragParent != null && data.button == PointerEventData.InputButton.Left)
        {
            if (!dragged)
            {
                dragged = true;
                dragParent.OnStartDrag(this);
                OnPointerUpOnDrag(data);
            }
            else
            {
                dragParent.OnDrag(this);
            }
        }
    }
References dragged, dragParent, IDragParent.OnDrag(), UIButton.OnPointerUpOnDrag(), and IDragParent.OnStartDrag().
OnMiddleClick()
override void ButtonAbility.OnMiddleClick (bool forceClick) inline virtual
Reimplemented from UIButton.
Definition at line 288 of file ButtonAbility.cs.
    {
        if (EInput.middleMouse.clicked)
        {
            ToggleFav();
        }
        EInput.middleMouse.pressedLongAction = delegate
        {
            if (EClass.ui.AllowInventoryInteractions)
            {
                HoldAbility();
                EInput.Consume();
            }
        };
    }
References ButtonState.clicked, EInput.Consume(), HoldAbility(), EInput.middleMouse, ToggleFav(), and EClass.ui.
OnPointerUp()
override void ButtonAbility.OnPointerUp (PointerEventData eventData) inline
Definition at line 97 of file ButtonAbility.cs.
    {
        if (dragged)
        {
            dragged = false;
            dragParent.OnEndDrag(this);
        }
        else
        {
            base.OnPointerUp(eventData);
        }
    }
References dragged, dragParent, and IDragParent.OnEndDrag().
RefreshFavIcon()
void ButtonAbility.RefreshFavIcon () inline
Definition at line 320 of file ButtonAbility.cs.
    {
        bool enable = EClass.player.favAbility.Contains(source.id);
        imageFav.SetActive(enable);
    }
References Player.favAbility, imageFav, EClass.player, and source.
Referenced by SetAct(), and ToggleFav().
SetAct()
void ButtonAbility.SetAct (Chara _chara, Element e) inline
Definition at line 37 of file ButtonAbility.cs.
    {
        source = e.source;
        chara = _chara;
        act = ACT.Create(source);
        if (act == null)
        {
            Debug.Log(source.alias);
        }
        Sprite iconType = act.TargetType.IconType;
        imageType.SetActive(iconType);
        imageType.sprite = iconType;
        act.SetImage(icon);
        if (EClass.game.altAbility)
        {
            textStock.SetActive(e is Spell);
            textStock.text = e.vPotential.ToShortNumber();
            onRightClick = delegate
            {
                if (EClass.ui.IsActive)
                {
                    SE.BeepSmall();
                }
                else
                {
                    Use();
                }
            };
        }
        else
        {
            mainText.SetText(e.Name);
        }
        SetTooltip("note", delegate(UITooltip t)
        {
            e.WriteNote(t.note, chara.elements, delegate
            {
                e._WriteNote(t.note, chara, act);
            });
        });
        RefreshFavIcon();
    }
References act, Game.altAbility, chara, ACT.Create(), Debug, Card.elements, EClass.game, UIButton.icon, TargetType.IconType, imageType, UIButton.mainText, Element.Name, UITooltip.note, UIButton.onRightClick, RefreshFavIcon(), Act.SetImage(), UIText.SetText(), UIButton.SetTooltip(), source, Element.source, Act.TargetType, textStock, EClass.ui, Use(), Element.vPotential, and Element.WriteNote().
Referenced by LayerAbility.SelectGroup().
ShowMouseHintLeft()
bool ButtonAbility.ShowMouseHintLeft () inline
Implements IMouseHint.
Definition at line 263 of file ButtonAbility.cs.
    {
        return false;
    }
ShowMouseHintRight()
bool ButtonAbility.ShowMouseHintRight () inline
Implements IMouseHint.
Definition at line 273 of file ButtonAbility.cs.
    {
        return CanAutoUse(ACT.Create(source));
    }
References CanAutoUse(), ACT.Create(), and source.
SpecialHoldAction()
static bool ButtonAbility.SpecialHoldAction (Act act) inline static
Definition at line 209 of file ButtonAbility.cs.
    {
        if (!(EClass.pc.elements.GetElement(act.id) is Act { id: var id } act2))
        {
            return false;
        }
        if (id == 8230 || id == 8232)
        {
            bool flag = true;
            int num = 0;
            foreach (Thing item in EClass.pc.things.List((Thing t) => true, onlyAccessible: true))
            {
                if (!item.IsIdentified)
                {
                    if ((EClass.pc.mana.value < act2.GetCost(EClass.pc).cost && !flag) || act2.vPotential <= 0)
                    {
                        break;
                    }
                    if (item.rarity < Rarity.Mythical || act2.id != 8230)
                    {
                        EClass.pc.UseAbility(act.source.alias, item, EClass.pc.pos);
                        num++;
                        flag = false;
                    }
                }
            }
            if (num == 0)
            {
                Msg.Say("identify_nothing");
            }
            return true;
        }
        return false;
    }
References act, Card.elements, ElementContainer.GetElement(), Element.id, UIButton.item, ThingContainer.List(), Chara.mana, EClass.pc, Card.pos, Msg.Say(), Element.source, Card.things, Chara.UseAbility(), and Stats.value.
Referenced by TryUse().
ToggleFav()
void ButtonAbility.ToggleFav () inline
Definition at line 304 of file ButtonAbility.cs.
    {
        if (EClass.player.favAbility.Contains(source.id))
        {
            EClass.player.favAbility.Remove(source.id);
            SE.Tab();
        }
        else
        {
            EClass.player.favAbility.Add(source.id);
            SE.Tab();
        }
        RefreshFavIcon();
        LayerAbility.Instance.list.Redraw();
    }
References Player.favAbility, LayerAbility.Instance, LayerAbility.list, EClass.player, UIDynamicList.Redraw(), RefreshFavIcon(), and source.
Referenced by OnMiddleClick().
TryUse()
static bool ButtonAbility.TryUse (Act act, Card tg = null, Point pos = null, Card catalyst = null, bool first = true, bool mouse = true) inline static
Definition at line 129 of file ButtonAbility.cs.
    {
        if (lockUse && first)
        {
            return false;
        }
        bool flag = false;
        if (tg == null)
        {
            tg = EClass.pc;
        }
        if (pos == null)
        {
            pos = EClass.pc.pos.Copy();
        }
        if (first)
        {
            lockUse = true;
            hotkeyAct = act;
            if (EInput.GetHotkey() != -1)
            {
                mouse = false;
                hotkeyTimer = 0f;
            }
            else
            {
                usedMouseKey = EInput.rightMouse.usedKey;
            }
        }
        if (act.HaveLongPressAction && act == hotkeyAct)
        {
            if ((mouse && EInput.rightMouse.pressedLong) || (!mouse && hotkeyTimer >= 0.45f))
            {
                EInput.rightMouse.Consume();
                flag = true;
                hotkeyTimer = 1f;
            }
            if ((mouse && EInput.rightMouse.pressing) || (!mouse && EInput.GetHotkey() != -1 && hotkeyTimer < 1f))
            {
                hotkeyTimer += Core.delta;
                EClass.core.actionsNextFrame.Add(delegate
                {
                    TryUse(act, tg, pos, catalyst, first: false, mouse);
                });
                if (first)
                {
                    EClass.core.actionsNextFrame.Add(delegate
                    {
                        EInput.rightMouse.down = false;
                        EInput.rightMouse.consumed = false;
                        EInput.rightMouse.pressing = true;
                        if (usedMouseKey)
{
                            EInput.rightMouse.usedKey = true;
                        }
                        else
{
                            EInput.rightMouse.usedMouse = true;
                        }
                    });
                }
                return false;
            }
        }
        lockUse = false;
        if (flag && SpecialHoldAction(act))
        {
            EClass.player.EndTurn();
        }
        else if (EClass.pc.UseAbility(act.source.alias, tg, pos, flag) && EClass.pc.HasNoGoal)
        {
            EClass.player.EndTurn();
        }
        if (catalyst != null)
        {
            LayerInventory.SetDirty(catalyst.Thing);
        }
        return false;
    }
References act, BaseCore.actionsNextFrame, ButtonState.Consume(), Point.Copy(), EClass.core, Core.delta, Player.EndTurn(), EInput.GetHotkey(), Chara.HasNoGoal, Act.HaveLongPressAction, hotkeyAct, hotkeyTimer, lockUse, EClass.pc, EClass.player, Card.pos, ButtonState.pressedLong, ButtonState.pressing, EInput.rightMouse, LayerInventory.SetDirty(), Element.source, SpecialHoldAction(), TryUse(), Chara.UseAbility(), ButtonState.usedKey, and usedMouseKey.
Referenced by TraitCatalyst.OnUse(), HotItemAct.TrySetAct(), TraitCatalyst.TrySetHeldAct(), TryUse(), and Use().
Use()
void ButtonAbility.Use () inline
Definition at line 110 of file ButtonAbility.cs.
    {
        if (!EClass.pc.HasNoGoal)
        {
            SE.BeepSmall();
        }
        else if (CanAutoUse(act))
        {
            if (TryUse(act) && EClass.pc.ai.IsNoGoal)
            {
                EClass.player.EndTurn();
            }
        }
        else
        {
            HoldAbility();
        }
    }
References act, Chara.ai, CanAutoUse(), Player.EndTurn(), Chara.HasNoGoal, HoldAbility(), AIAct.IsNoGoal, EClass.pc, EClass.player, and TryUse().
Referenced by SetAct().
Member Data Documentation
act
Act ButtonAbility.act
Definition at line 24 of file ButtonAbility.cs.
Referenced by SetAct(), SpecialHoldAction(), TryUse(), and Use().
attach
Transform ButtonAbility.attach
Definition at line 18 of file ButtonAbility.cs.
Referenced by LayerAbility.ClearHotElement().
chara
Chara ButtonAbility.chara
Definition at line 22 of file ButtonAbility.cs.
Referenced by SetAct().
dragged
bool ButtonAbility.dragged
Definition at line 27 of file ButtonAbility.cs.
Referenced by OnDrag(), and OnPointerUp().
dragParent
IDragParent ButtonAbility.dragParent
Definition at line 10 of file ButtonAbility.cs.
Referenced by OnDrag(), and OnPointerUp().
hotkeyAct
Act ButtonAbility.hotkeyAct static
Definition at line 29 of file ButtonAbility.cs.
Referenced by TryUse().
hotkeyTimer
float ButtonAbility.hotkeyTimer static
Definition at line 31 of file ButtonAbility.cs.
Referenced by TryUse().
imageFav
Image ButtonAbility.imageFav
Definition at line 16 of file ButtonAbility.cs.
Referenced by RefreshFavIcon().
imageType
Image ButtonAbility.imageType
Definition at line 14 of file ButtonAbility.cs.
Referenced by SetAct().
lockUse
bool ButtonAbility.lockUse static
Definition at line 35 of file ButtonAbility.cs.
Referenced by TryUse().
source
SourceElement.Row ButtonAbility.source
Definition at line 8 of file ButtonAbility.cs.
Referenced by HoldAbility(), LayerAbility.OnDrag(), LayerAbility.OnUpdateInput(), RefreshFavIcon(), SetAct(), ShowMouseHintRight(), ToggleFav(), and ActionMode.UpdateInput().
textStock
UIText ButtonAbility.textStock
Definition at line 12 of file ButtonAbility.cs.
Referenced by SetAct().
transFav
Transform ButtonAbility.transFav
Definition at line 20 of file ButtonAbility.cs.
usedMouseKey
bool ButtonAbility.usedMouseKey static
Definition at line 33 of file ButtonAbility.cs.
Referenced by TryUse().
The documentation for this class was generated from the following file:
Elin/ButtonAbility.cs