Elin Decompiled Documentation: SourceBacker Class Reference
SourceBacker Class Reference
Classes
class Row
Public Member Functions
override Row CreateRow ()
override Row CreateRowByMapping (IReadOnlyDictionary< string, int > mapping)
override void SetRow (Row r)
override IReadOnlyDictionary< string, int > GetRowMapping ()
override IReadOnlyDictionary< string, string > GetTypeMapping ()
override void OnInit ()
Public Member Functions inherited from SourceDataInt< SourceBacker.Row >
override T GetRow (string id)
Public Attributes
List< Row > listRemain = new List<Row>()
List< Row > listLantern = new List<Row>()
List< Row > listTree = new List<Row>()
List< Row > listPet = new List<Row>()
List< Row > listSister = new List<Row>()
List< Row > listFollower = new List<Row>()
List< Row > listSnail = new List<Row>()
Static Public Attributes
static readonly IReadOnlyDictionary< string, int > RowMapping
static readonly IReadOnlyDictionary< string, string > TypeMapping
Detailed Description
Definition at line 4 of file SourceBacker.cs.
Member Function Documentation
CreateRow()
override Row SourceBacker.CreateRow () inline
Definition at line 127 of file SourceBacker.cs.
    {
        return new Row
        {
            id = SourceData.GetInt(0),
            valid = SourceData.GetBool(3),
            lang = SourceData.GetString(7),
            name = SourceData.GetString(8),
            text = SourceData.GetString(9),
            type = SourceData.GetInt(10),
            skin = SourceData.GetInt(11),
            gender = SourceData.GetInt(12),
            tree = SourceData.GetString(13),
            deity = SourceData.GetString(14),
            chara = SourceData.GetString(15),
            loot = SourceData.GetString(16),
            isStatic = SourceData.GetInt(17),
            done = SourceData.GetBool(18),
            loc = SourceData.GetString(19),
            original = SourceData.GetString(20)
        };
    }
References SourceData< T, T2 >.GetBool(), SourceData< T, T2 >.GetInt(), and SourceData< T, T2 >.GetString().
CreateRowByMapping()
override Row SourceBacker.CreateRowByMapping (IReadOnlyDictionary< string, int > mapping) inline
Definition at line 150 of file SourceBacker.cs.
    {
        return new Row
        {
            id = SourceData.GetInt(mapping["id"]),
            valid = SourceData.GetBool(mapping["valid"]),
            lang = SourceData.GetString(mapping["lang"]),
            name = SourceData.GetString(mapping["name"]),
            text = SourceData.GetString(mapping["text"]),
            type = SourceData.GetInt(mapping["type"]),
            skin = SourceData.GetInt(mapping["skin"]),
            gender = SourceData.GetInt(mapping["gender"]),
            tree = SourceData.GetString(mapping["tree"]),
            deity = SourceData.GetString(mapping["deity"]),
            chara = SourceData.GetString(mapping["chara"]),
            loot = SourceData.GetString(mapping["loot"]),
            isStatic = SourceData.GetInt(mapping["isStatic"]),
            done = SourceData.GetBool(mapping["done"]),
            loc = SourceData.GetString(mapping["loc"]),
            original = SourceData.GetString(mapping["original"])
        };
    }
References SourceData< T, T2 >.GetBool(), SourceData< T, T2 >.GetInt(), and SourceData< T, T2 >.GetString().
GetRowMapping()
override IReadOnlyDictionary< string, int > SourceBacker.GetRowMapping () inline
Definition at line 178 of file SourceBacker.cs.
    {
        return RowMapping;
    }
References RowMapping.
GetTypeMapping()
override IReadOnlyDictionary< string, string > SourceBacker.GetTypeMapping () inline
Definition at line 183 of file SourceBacker.cs.
    {
        return TypeMapping;
    }
References TypeMapping.
OnInit()
override void SourceBacker.OnInit () inline
Definition at line 188 of file SourceBacker.cs.
    {
        foreach (Row row in rows)
        {
            if (row.isStatic == 0 && row.valid)
            {
                switch (row.type)
                {
                case 1:
                    listRemain.Add(row);
                    break;
                case 2:
                    listLantern.Add(row);
                    break;
                case 3:
                    listTree.Add(row);
                    break;
                case 4:
                    listPet.Add(row);
                    break;
                case 5:
                    listSister.Add(row);
                    break;
                case 6:
                    listFollower.Add(row);
                    break;
                case 7:
                    listSnail.Add(row);
                    break;
                }
            }
        }
        listRemain.Shuffle();
        listLantern.Shuffle();
        listTree.Shuffle();
        listPet.Shuffle();
        listSister.Shuffle();
        listFollower.Shuffle();
        listSnail.Shuffle();
    }
References SourceBacker.Row.isStatic, listFollower, listLantern, listPet, listRemain, listSister, listSnail, listTree, SourceBacker.Row.type, and SourceBacker.Row.valid.
SetRow()
override void SourceBacker.SetRow (Row r) inline
Definition at line 173 of file SourceBacker.cs.
    {
        map[r.id] = r;
    }
References SourceBacker.Row.id.
Member Data Documentation
listFollower
List<Row> SourceBacker.listFollower = new List<Row>()
Definition at line 122 of file SourceBacker.cs.
Referenced by OnInit(), and Zone.TrySpawnFollower().
listLantern
List<Row> SourceBacker.listLantern = new List<Row>()
Definition at line 110 of file SourceBacker.cs.
Referenced by TraitSpecialLantern.OnCreate(), and OnInit().
listPet
List<Row> SourceBacker.listPet = new List<Row>()
Definition at line 116 of file SourceBacker.cs.
Referenced by Zone.ApplyBackerPet(), and OnInit().
listRemain
List<Row> SourceBacker.listRemain = new List<Row>()
Definition at line 107 of file SourceBacker.cs.
Referenced by Map.ApplyBackerObj(), and OnInit().
listSister
List<Row> SourceBacker.listSister = new List<Row>()
Definition at line 119 of file SourceBacker.cs.
Referenced by Chara.OnCreate(), and OnInit().
listSnail
List<Row> SourceBacker.listSnail = new List<Row>()
Definition at line 125 of file SourceBacker.cs.
Referenced by Zone_Casino.OnActivate(), and OnInit().
listTree
List<Row> SourceBacker.listTree = new List<Row>()
Definition at line 113 of file SourceBacker.cs.
Referenced by Map.AddBackerTree(), Map.ApplyBackerObj(), and OnInit().
RowMapping
readonly IReadOnlyDictionary<string, int> SourceBacker.RowMapping static
Initial value:
= new Dictionary<string, int>
    {
        ["id"] = 0,
        ["valid"] = 3,
        ["lang"] = 7,
        ["name"] = 8,
        ["text"] = 9,
        ["type"] = 10,
        ["skin"] = 11,
        ["gender"] = 12,
        ["tree"] = 13,
        ["deity"] = 14,
        ["chara"] = 15,
        ["loot"] = 16,
        ["isStatic"] = 17,
        ["done"] = 18,
        ["loc"] = 19,
        ["original"] = 20
    }
Definition at line 66 of file SourceBacker.cs.
Referenced by GetRowMapping().
TypeMapping
readonly IReadOnlyDictionary<string, string> SourceBacker.TypeMapping static
Initial value:
= new Dictionary<string, string>
    {
        ["id"] = "int",
        ["valid"] = "bool",
        ["lang"] = "string",
        ["name"] = "string",
        ["text"] = "string",
        ["type"] = "int",
        ["skin"] = "int",
        ["gender"] = "int",
        ["tree"] = "string",
        ["deity"] = "string",
        ["chara"] = "string",
        ["loot"] = "string",
        ["isStatic"] = "int",
        ["done"] = "bool",
        ["loc"] = "string",
        ["original"] = "string"
    }
Definition at line 86 of file SourceBacker.cs.
Referenced by GetTypeMapping().
The documentation for this class was generated from the following file:
Elin/SourceBacker.cs