Elin Decompiled Documentation: GradientEffect Class Reference
GradientEffect Class Reference
Public Member Functions
override void ModifyMesh (VertexHelper vh)
void ModifyVertices (List< UIVertex > vertexList)
Public Attributes
GradientMode gradientMode
GradientDir gradientDir
bool overwriteAllColor
Color vertex1 = Color.white
Color vertex2 = Color.black
Properties
Graphic targetGraphic [get]
Private Member Functions
bool CompareCarefully (Color col1, Color col2)
Private Attributes
Graphic _targetGraphic
Detailed Description
Definition at line 6 of file GradientEffect.cs.
Member Function Documentation
CompareCarefully()
bool GradientEffect.CompareCarefully (Color col1, Color col2) inline private
Definition at line 109 of file GradientEffect.cs.
    {
        if (Mathf.Abs(col1.r - col2.r) < 0.003f && Mathf.Abs(col1.g - col2.g) < 0.003f && Mathf.Abs(col1.b - col2.b) < 0.003f && Mathf.Abs(col1.a - col2.a) < 0.003f)
        {
            return true;
        }
        return false;
    }
Referenced by ModifyVertices().
ModifyMesh()
override void GradientEffect.ModifyMesh (VertexHelper vh) inline
Definition at line 32 of file GradientEffect.cs.
    {
        if (IsActive())
        {
            List<UIVertex> list = new List<UIVertex>();
            vh.GetUIVertexStream(list);
            ModifyVertices(list);
            vh.Clear();
            vh.AddUIVertexTriangleStream(list);
        }
    }
References ModifyVertices().
ModifyVertices()
void GradientEffect.ModifyVertices (List< UIVertex > vertexList) inline
Definition at line 44 of file GradientEffect.cs.
    {
        if (!IsActive() || vertexList.Count == 0)
        {
            return;
        }
        int count = vertexList.Count;
        UIVertex uIVertex = vertexList[0];
        if (gradientMode == GradientMode.Global)
        {
            if (gradientDir == GradientDir.DiagonalLeftToRight || gradientDir == GradientDir.DiagonalRightToLeft)
            {
                gradientDir = GradientDir.Vertical;
            }
            float num = ((gradientDir == GradientDir.Vertical) ? vertexList[vertexList.Count - 1].position.y : vertexList[vertexList.Count - 1].position.x);
            float num2 = ((gradientDir == GradientDir.Vertical) ? vertexList[0].position.y : vertexList[0].position.x) - num;
            for (int i = 0; i < count; i++)
            {
                uIVertex = vertexList[i];
                if (overwriteAllColor || !(uIVertex.color != targetGraphic.color))
                {
                    ref Color32 color = ref uIVertex.color;
                    color *= Color.Lerp(vertex2, vertex1, (((gradientDir == GradientDir.Vertical) ? uIVertex.position.y : uIVertex.position.x) - num) / num2);
                    vertexList[i] = uIVertex;
                }
            }
            return;
        }
        for (int j = 0; j < count; j++)
        {
            uIVertex = vertexList[j];
            if (overwriteAllColor || CompareCarefully(uIVertex.color, targetGraphic.color))
            {
                switch (gradientDir)
                {
                case GradientDir.Vertical:
                {
                    ref Color32 color4 = ref uIVertex.color;
                    color4 *= ((j % 4 == 0 || (j - 1) % 4 == 0) ? vertex1 : vertex2);
                    break;
                }
                case GradientDir.Horizontal:
                {
                    ref Color32 color5 = ref uIVertex.color;
                    color5 *= ((j % 4 == 0 || (j - 3) % 4 == 0) ? vertex1 : vertex2);
                    break;
                }
                case GradientDir.DiagonalLeftToRight:
                {
                    ref Color32 color3 = ref uIVertex.color;
                    color3 *= ((j % 4 == 0) ? vertex1 : (((j - 2) % 4 == 0) ? vertex2 : Color.Lerp(vertex2, vertex1, 0.5f)));
                    break;
                }
                case GradientDir.DiagonalRightToLeft:
                {
                    ref Color32 color2 = ref uIVertex.color;
                    color2 *= (((j - 1) % 4 == 0) ? vertex1 : (((j - 3) % 4 == 0) ? vertex2 : Color.Lerp(vertex2, vertex1, 0.5f)));
                    break;
                }
                }
                vertexList[j] = uIVertex;
            }
        }
    }
References Color, CompareCarefully(), gradientDir, gradientMode, overwriteAllColor, targetGraphic, vertex1, and vertex2.
Referenced by ModifyMesh().
Member Data Documentation
_targetGraphic
Graphic GradientEffect._targetGraphic private
Definition at line 18 of file GradientEffect.cs.
gradientDir
GradientDir GradientEffect.gradientDir
Definition at line 10 of file GradientEffect.cs.
Referenced by ModifyVertices().
gradientMode
GradientMode GradientEffect.gradientMode
Definition at line 8 of file GradientEffect.cs.
Referenced by ModifyVertices().
overwriteAllColor
bool GradientEffect.overwriteAllColor
Definition at line 12 of file GradientEffect.cs.
Referenced by ModifyVertices().
vertex1
Color GradientEffect.vertex1 = Color.white
Definition at line 14 of file GradientEffect.cs.
Referenced by ModifyVertices().
vertex2
Color GradientEffect.vertex2 = Color.black
Definition at line 16 of file GradientEffect.cs.
Referenced by ModifyVertices().
Property Documentation
targetGraphic
Graphic GradientEffect.targetGraphic get private
Definition at line 20 of file GradientEffect.cs.
    {
        get
        {
            if (_targetGraphic == null)
            {
                _targetGraphic = GetComponent<Graphic>();
            }
            return _targetGraphic;
        }
    }
Referenced by ModifyVertices().
The documentation for this class was generated from the following file:
Elin/Plugins.UI/GradientEffect.cs