Elin Decompiled Documentation: CardManager Class Reference
CardManager Class Reference
Classes
class GlobalCharaList
Public Member Functions
void AssignUID (Card c)
void AssignUIDRecursive (Card c)
List< Chara > ListGlobalChara (Zone z)
Chara Find (int uid)
Public Attributes
GlobalCharaList globalCharas = new GlobalCharaList()
int uidNext = 1
Thing container_shipping
Thing container_deliver
Thing container_deposit
List< Thing > listPackage = new List<Thing>()
List< Chara > listAdv = new List<Chara>()
Private Member Functions
void OnDeserializing (StreamingContext context)
void OnDeserialized (StreamingContext context)
Additional Inherited Members
Static Public Member Functions inherited from EClass
static int rndSeed (int a, int seed)
static int rnd (long a)
static int rnd (int a)
static int curve (int _a, int start, int step, int rate=75)
static int sqrt (int a)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Static Public Attributes inherited from EClass
static Core core
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Detailed Description
Definition at line 6 of file CardManager.cs.
Member Function Documentation
AssignUID()
void CardManager.AssignUID (Card c) inline
Definition at line 78 of file CardManager.cs.
    {
        if (globalCharas.ContainsKey(uidNext))
        {
            while (globalCharas.ContainsKey(uidNext))
            {
                uidNext++;
            }
        }
        c.uid = uidNext;
        uidNext++;
    }
References globalCharas, and uidNext.
Referenced by AssignUIDRecursive(), and Card.Create().
AssignUIDRecursive()
void CardManager.AssignUIDRecursive (Card c) inline
Definition at line 91 of file CardManager.cs.
    {
        if (c.things.Count > 0)
        {
            foreach (Thing thing in c.things)
            {
                AssignUIDRecursive(thing);
            }
        }
        AssignUID(c);
    }
References AssignUID(), AssignUIDRecursive(), and Card.things.
Referenced by AssignUIDRecursive().
Find()
Chara CardManager.Find (int uid) inline
Definition at line 116 of file CardManager.cs.
    {
        foreach (Chara value in globalCharas.Values)
        {
            if (value.uid == uid)
            {
                return value;
            }
        }
        return null;
    }
References globalCharas, and Card.uid.
Referenced by ZoneInstanceBout.OnLeaveZone().
ListGlobalChara()
List< Chara > CardManager.ListGlobalChara (Zone z) inline
Definition at line 103 of file CardManager.cs.
    {
        List<Chara> list = new List<Chara>();
        foreach (Chara value in globalCharas.Values)
        {
            if (value.currentZone == z)
            {
                list.Add(value);
            }
        }
        return list;
    }
References Chara.currentZone, and globalCharas.
Referenced by Zone.AddRandomVisitor().
OnDeserialized()
void CardManager.OnDeserialized (StreamingContext context) inline private
Definition at line 73 of file CardManager.cs.
    {
        Debug.Log("#io CardManager OnDeserialized:" + globalCharas.Count);
    }
References Debug, and globalCharas.
OnDeserializing()
void CardManager.OnDeserializing (StreamingContext context) inline private
Definition at line 67 of file CardManager.cs.
    {
        Debug.Log("#io CardManager OnDeserializing:");
    }
References Debug.
Member Data Documentation
container_deliver
Thing CardManager.container_deliver
Definition at line 55 of file CardManager.cs.
Referenced by LayerInventory.CreateContainer(), and GameDate.ShipPackages().
container_deposit
Thing CardManager.container_deposit
Definition at line 58 of file CardManager.cs.
Referenced by Faction.OnAdvanceMonth(), InvOwnerDeliver.PayBill(), WindowChara.RefreshProfile(), and Faction.TryPayBill().
container_shipping
Thing CardManager.container_shipping
Definition at line 52 of file CardManager.cs.
Referenced by LayerInventory.CreateContainer(), TaskDump.IsValidContainer(), TaskDump.ListThingsToPut(), TaskDump.Run(), GameDate.ShipGoods(), Zone.TryAddThingInSharedContainer(), and GrowSystem.TryPick().
globalCharas
GlobalCharaList CardManager.globalCharas = new GlobalCharaList()
Definition at line 46 of file CardManager.cs.
Referenced by ReligionManager.(), QuestManager.Add(), Zone.AddGlobalCharasOnActivate(), QuestManager.AddQuestAsh(), QuestManager.AddQuestFiama(), GameDate.AdvanceDay(), GameDate.AdvanceHour(), AssignUID(), LayerShippingResult.Awake(), ElementContainerFaction.CheckDirty(), SurvivalManager.CheckLoytelDebt(), Faction.CountMembers(), Card.Destroy(), Chara.Die(), Find(), CoreDebug.Fix_RemoveAshland(), CoreDebug.Fix_RemoveDemitas(), RefChara.Get(), DramaSequence.GetActor(), RefChara.GetAndCache(), Faction.HasMember(), Faction.IsWearingPanty(), ListGlobalChara(), Zone_Specwing.OnActivate(), Zone_WindRest.OnAfterSimulate(), Zone_Nymelle.OnBeforeSimulate(), QuestDefense.OnChangePhase(), QuestVernis.OnChangePhase(), DramaOutcome.OnClaimLand(), Quest.OnClickQuest(), QuestIntroInspector.OnComplete(), QuestSharedContainer.OnComplete(), OnDeserialized(), QuestDialog.OnDropReward(), SurvivalManager.OnExpandFloor(), Game.OnGameInstantiated(), Zone_DungeonPuppy.OnGenerateMap(), ElementContainerFaction.OnJoinFaith(), ElementContainerFaction.OnLeaveFaith(), ListPeopleRevive.OnList(), Game.OnLoad(), TraitStoryBookHome.OnRead(), QuestDebt.OnStart(), QuestExploration.OnStart(), DramaManager.ParseLine(), ActEffect.Proc(), DramaOutcome.QuestExploration_AfterComplete(), DramaOutcome.QuestExploration_AfterCrystal(), CoreDebug.QuickStart(), LayerQuestBoard.RefreshRanking(), Chara.RemoveGlobal(), CoreDebug.ResetPetUpgrades(), SerializedCards.Restore(), Zone.Revive(), AI_Idle.Run(), Meeting.SetChara(), Chara.SetGlobal(), FactionBranch.SetOwner(), UIFactionInfo.SetZone(), UIZoneInfo.SetZone(), QuestManager.Start(), Game.StartNewGame(), TraitBed.ValidateOwners(), and EloPos.WriteNote().
listAdv
List<Chara> CardManager.listAdv = new List<Chara>()
Definition at line 64 of file CardManager.cs.
Referenced by Game.AddAdventurer(), Game.AddAdventurers(), GameDate.AdvanceDay(), TraitSalesTag.CanTagSale(), Game.OnLoad(), and FactionBranch.RemoveMemeber().
listPackage
List<Thing> CardManager.listPackage = new List<Thing>()
Definition at line 61 of file CardManager.cs.
Referenced by GameDate.AdvanceHour(), FactionBranch.ReceivePackages(), and World.SendPackage().
uidNext
int CardManager.uidNext = 1
Definition at line 49 of file CardManager.cs.
Referenced by AssignUID(), and TraitDrinkMilkMother.OnDrink().
The documentation for this class was generated from the following file:
Elin/CardManager.cs