Elin Decompiled Documentation: ContentHomeLog Class Reference
ContentHomeLog Class Reference
Public Member Functions
override void OnSwitchContent (int idTab)
void RefreshLog ()
Public Attributes
UIList listLog
ItemStatistics stat
ItemStatistics statLast
Detailed Description
Definition at line 3 of file ContentHomeLog.cs.
Member Function Documentation
OnSwitchContent()
override void ContentHomeLog.OnSwitchContent (int idTab) inline
Definition at line 5 of file ContentHomeLog.cs.
    {
        this.stat.Refresh(EClass.Branch.statistics);
        this.RefreshLog();
    }
References EClass.Branch, ItemStatistics.Refresh(), RefreshLog(), stat, and FactionBranch.statistics.
RefreshLog()
void ContentHomeLog.RefreshLog () inline
Definition at line 11 of file ContentHomeLog.cs.
    {
        UIList uilist = this.listLog;
        BaseList baseList = uilist;
        UIList.Callback<MsgLog.Data, UIItem> callback = new UIList.Callback<MsgLog.Data, UIItem>();
        callback.onInstantiate = delegate(MsgLog.Data a, UIItem b)
        {
            b.text1.text = a.text.ToTitleCase(false);
            if (!a.col.IsEmpty())
            {
                b.text1.SetColor(a.col.ToEnum(true));
            }
            b.text2.text = string.Concat(new string[]
            {
                a.date.month.ToString(),
                "/",
                a.date.day.ToString(),
                " ",
                a.date.hour.ToString(),
                ":",
                a.date.min.ToString()
            });
        };
        baseList.callbacks = callback;
        uilist.Clear();
        foreach (MsgLog.Data o in EClass.Branch.log.GetList(true))
        {
            uilist.Add(o);
        }
        uilist.Refresh(false);
        this.RebuildLayout(true);
    }
References EClass.Branch, MsgLog.GetList(), listLog, FactionBranch.log, and MsgLog.Data.text.
Referenced by OnSwitchContent().
Member Data Documentation
listLog
UIList ContentHomeLog.listLog
Definition at line 44 of file ContentHomeLog.cs.
Referenced by RefreshLog().
stat
ItemStatistics ContentHomeLog.stat
Definition at line 46 of file ContentHomeLog.cs.
Referenced by OnSwitchContent().
statLast
ItemStatistics ContentHomeLog.statLast
Definition at line 48 of file ContentHomeLog.cs.
The documentation for this class was generated from the following file:
Elin/ContentHomeLog.cs