Elin Decompiled Documentation: Happiness Class Reference
Happiness Class Reference
Public Member Functions
void SetOwner (FactionBranch _branch, FactionMemberType _type)
void OnAdvanceDay ()
void OnRefreshEffect ()
int GetTargetValue ()
string GetText ()
int CountMembers ()
void WriteNote (UINote n)
Public Attributes
int value
int lastValue
int modPolicy
FactionBranch branch
FactionMemberType type
Properties
string Name [get]
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Additional Inherited Members
Static Public Member Functions inherited from EClass
static int rnd (int a)
static int curve (int a, int start, int step, int rate=75)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Static Public Attributes inherited from EClass
static Core core
Detailed Description
Definition at line 6 of file Happiness.cs.
Member Function Documentation
CountMembers()
int Happiness.CountMembers () inline
Definition at line 88 of file Happiness.cs.
    {
        int num = 0;
        using (List<Chara>.Enumerator enumerator = this.branch.members.GetEnumerator())
        {
            while (enumerator.MoveNext())
            {
                if (enumerator.Current.memberType == this.type)
                {
                    num++;
                }
            }
        }
        return num;
    }
References branch, and FactionBranch.members.
Referenced by GetText().
GetTargetValue()
int Happiness.GetTargetValue () inline
Definition at line 33 of file Happiness.cs.
    {
        int num = 50;
        if (this.branch.resources.food.value < 0)
        {
            num -= 100;
        }
        num += (this.branch.resources.fun.value - 50) / 4;
        num += (this.branch.resources.culture.value - 50) / 4;
        num += (this.branch.resources.medicine.value - 50) / 4;
        num += (this.branch.resources.safety.value - 50) / 4;
        foreach (Chara chara in this.branch.members)
        {
        }
        foreach (BaseHomeResource baseHomeResource in this.branch.resources.list)
        {
        }
        foreach (Policy policy in this.branch.policies.list)
        {
        }
        num += this.modPolicy;
        return num;
    }
References branch, HomeResourceManager.food, HomeResourceManager.list, PolicyManager.list, FactionBranch.members, modPolicy, FactionBranch.policies, FactionBranch.resources, and BaseHomeResource.value.
Referenced by OnAdvanceDay(), and WriteNote().
GetText()
string Happiness.GetText () inline
Definition at line 57 of file Happiness.cs.
    {
        if (this.CountMembers() == 0)
        {
            return " - %".TagColor(FontColor.Passive, null);
        }
        string text = this.value.ToString() + "%";
        int num = this.value - this.lastValue;
        if (num != 0)
        {
        }
        if (this.value <= 30)
        {
            text = text.TagColor(FontColor.Bad, null);
        }
        else if (this.value >= 70)
        {
            text = text.TagColor(FontColor.Good, null);
        }
        string str = "";
        if (num > 0)
        {
            str = "↑".TagColor(FontColor.Good, null);
        }
        else if (num < 0)
        {
            str = "↓".TagColor(FontColor.Bad, null);
        }
        return text + " " + str;
    }
References CountMembers(), lastValue, text, and value.
Referenced by ContentHomeReport.RefreshInfo(), and UIHomeInfo.RefreshInfo().
OnAdvanceDay()
void Happiness.OnAdvanceDay () inline
Definition at line 22 of file Happiness.cs.
    {
        this.lastValue = this.value;
        this.value = (int)Mathf.Lerp((float)this.value, (float)this.GetTargetValue(), 0.1f);
    }
References GetTargetValue(), and value.
Referenced by HappinessManager.OnSimulateDay().
OnRefreshEffect()
void Happiness.OnRefreshEffect () inline
Definition at line 28 of file Happiness.cs.
    {
        this.modPolicy = 0;
    }
Referenced by PolicyManager.RefreshEffects().
SetOwner()
void Happiness.SetOwner (FactionBranch _branch, FactionMemberType _type) inline
Definition at line 16 of file Happiness.cs.
    {
        this.branch = _branch;
        this.type = _type;
    }
WriteNote()
void Happiness.WriteNote (UINote n) inline
Definition at line 104 of file Happiness.cs.
    {
        n.Clear();
        n.AddHeader(this.Name, null);
        n.Space(0, 1);
        n.AddText("vTarget".lang() + this.GetTargetValue().ToString(), FontColor.DontChange);
        n.AddText("vCurrent".lang() + this.value.ToString(), FontColor.DontChange);
        n.AddText("vLast".lang() + this.lastValue.ToString(), FontColor.DontChange);
        n.Space(0, 1);
        n.AddText("policyHappiness".lang(this.modPolicy.ToString() ?? "", null, null, null, null), FontColor.DontChange);
        n.Build();
    }
References GetTargetValue(), lastValue, modPolicy, Name, and value.
Referenced by ContentHomeReport.RefreshInfo(), and UIHomeInfo.RefreshInfo().
Member Data Documentation
branch
FactionBranch Happiness.branch
Definition at line 125 of file Happiness.cs.
Referenced by CountMembers(), and GetTargetValue().
lastValue
int Happiness.lastValue
Definition at line 121 of file Happiness.cs.
Referenced by GetText(), and WriteNote().
modPolicy
int Happiness.modPolicy
Definition at line 123 of file Happiness.cs.
Referenced by GetTargetValue(), and WriteNote().
type
FactionMemberType Happiness.type
Definition at line 127 of file Happiness.cs.
value
int Happiness.value
Definition at line 118 of file Happiness.cs.
Referenced by GetText(), OnAdvanceDay(), and WriteNote().
Property Documentation
Name
string Happiness.Name get
Definition at line 8 of file Happiness.cs.
    {
        get
        {
            return ("member" + this.type.ToString()).lang();
        }
    }
Referenced by WriteNote().
The documentation for this class was generated from the following file:
Elin/Happiness.cs