Elin Decompiled Documentation: WidgetHotbar Class Reference
WidgetHotbar Class Reference
Classes
class Extra
Public Member Functions
override object CreateExtra ()
override bool CanShowContextMenu ()
override void OnActivate ()
override void OnChangeActionMode ()
void Rebuild ()
void RebuildPage (int page=-1)
void SwitchPage ()
HotItem GetItem (int index)
void TryUse (int index)
void OnClickEmptyItem (ButtonHotItem b)
override void OnSetContextMenu (UIContextMenu m)
void SetShortcutMenu (ButtonHotItem b, UIContextMenu m)
void SetItem (ButtonHotItem b, HotItem item)
bool RefreshHighlight ()
void _OnDirtyInventory ()
void SetVisible ()
void ToggleVisible ()
void CheckAutoHide ()
void OnStartDrag (UIButton b)
void OnDrag (UIButton b)
ButtonHotItem GetSwapButton (UIButton b)
void OnEndDrag (UIButton b, bool cancel=false)
Public Member Functions inherited from Widget
void Test ()
bool IsInRightMode ()
void Activate ()
virtual void OnActivate ()
virtual object CreateExtra ()
void Deactivate ()
virtual void OnDeactivate ()
void Close ()
void Reactivate ()
virtual void OnManagerActivate ()
virtual void OnManagerDeactivate ()
void SetAnchor (RectPosition p)
void SetPivot (RectPosition p)
virtual void OnChangePivot ()
void UpdateConfig ()
virtual void OnUpdateConfig ()
void ClampToScreen ()
virtual void OnChangeResolution ()
void OnChangePosition ()
virtual void OnChangeActionMode ()
virtual void OnFlip ()
bool IsAlignTop ()
Layer AddLayer (Layer l, Transform trans)
void RefreshTipPivotPosition ()
SkinSet GetSkin ()
SkinConfig GetSkinConfig ()
void SetSkin (int id, int v=0)
void TestSkin ()
virtual void ApplySkin ()
virtual void OnApplySkin ()
void InstantiateDeco (SkinDeco deco)
void AddDeco (SkinDeco deco)
void RemoveDeco (SkinDeco deco)
virtual bool CanShowContextMenu ()
void ShowContextMenu ()
void SetBaseContextMenu (UIContextMenu m)
virtual void OnSetContextMenu (UIContextMenu m)
void SetGridContextMenu (UIContextMenu m)
void SoundActivate ()
Static Public Member Functions
static void RebuildPages ()
static void RefreshHighlights ()
static void RefreshButtons ()
Static Public Member Functions inherited from EMono
static int rnd (int a)
Public Attributes
int idHotbar
GridLayoutGroup layout
ButtonHotItem mold
RawImage imageGrid
Image imageSelect
Hotbar.Type type
bool useMask
List< ButtonHotItem > buttons = new List<ButtonHotItem>()
Public Attributes inherited from Widget
Image imageBG
SoundData soundActivate
UIDragPanel dragPanel
RectTransform tipPivotLeft
RectTransform tipPivotRight
Static Public Attributes
static bool registering
static bool dirtyCurrentItem
static HotItem registeringItem
static WidgetHotbar HotbarBuild
static WidgetHotbar HotBarMainMenu
static WidgetHotbar HotbarExtra
Static Public Attributes inherited from EMono
static Core core
Properties
WidgetHotbar.Extra extra [get]
Hotbar hotbar [get]
bool Visible [get, set]
override bool ShowInBuildMode [get]
bool IsHotbarSpeed [get]
bool CanRegisterItem [get]
Properties inherited from Widget
string ID [get]
Widget.Config config [get]
SkinRoot skinRoot [get]
bool IsSealed [get]
virtual bool ShowStyleMenu [get]
virtual bool AlwaysTop [get]
virtual bool IsStaticPosition [get]
virtual bool AlwaysBottom [get]
virtual Type SetSiblingAfter [get]
virtual bool ShowInBuildMode [get]
virtual bool RightClickToClose [get]
virtual bool AllowRightClickToClose [get]
Properties inherited from EMono
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SoundManager Sound [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static CoreDebug debug [get]
Private Attributes
bool showThisWidget
float timeSinceBecomeVisible
Additional Inherited Members
Public Types inherited from Widget
enum WidgetType { Default , ZoomMenu }
enum State { Active , Inactive }
Protected Member Functions inherited from Widget
void ClampToScreenEnsured (Component c, Vector2 anchoredPos)
void ClampToScreen (RectTransform rect, float margin=10f)
Protected Attributes inherited from Widget
bool flip
Detailed Description
Definition at line 9 of file WidgetHotbar.cs.
Member Function Documentation
_OnDirtyInventory()
void WidgetHotbar._OnDirtyInventory () inline
Definition at line 500 of file WidgetHotbar.cs.
    {
        foreach (ButtonHotItem buttonHotItem in this.buttons)
        {
            if (buttonHotItem.item != null)
            {
                buttonHotItem.Refresh();
            }
        }
    }
References buttons, and ButtonHotItem.Refresh().
CanShowContextMenu()
override bool WidgetHotbar.CanShowContextMenu () inline virtual
Reimplemented from Widget.
Definition at line 68 of file WidgetHotbar.cs.
    {
        if (this.hotbar.IsUserHotbar)
        {
            ButtonHotItem componentOf = InputModuleEX.GetComponentOf<ButtonHotItem>();
            if (componentOf && componentOf.item != null)
            {
                return true;
            }
        }
        return base.CanShowContextMenu();
    }
References hotbar, and Hotbar.IsUserHotbar.
CheckAutoHide()
void WidgetHotbar.CheckAutoHide () inline
Definition at line 577 of file WidgetHotbar.cs.
    {
        if (!this.Visible)
        {
            return;
        }
        this.timeSinceBecomeVisible += 0.2f;
        if (this.timeSinceBecomeVisible < 1f)
        {
            return;
        }
        if (Input.GetMouseButton(0) || EMono.ui.contextMenu.currentMenu != null || WidgetHotbar.registering)
        {
            this.timeSinceBecomeVisible = 0f;
            return;
        }
        if (InputModuleEX.IsPointerOver(base.transform))
        {
            this.timeSinceBecomeVisible = 0f;
            return;
        }
        foreach (ButtonHotItem buttonHotItem in this.buttons)
        {
            if (buttonHotItem.item != null && buttonHotItem.item.KeepVisibleWhenHighlighted && buttonHotItem.item.ShouldHighlight())
            {
                return;
            }
        }
        this.ToggleVisible();
    }
References buttons, registering, timeSinceBecomeVisible, ToggleVisible(), EMono.ui, and Visible.
CreateExtra()
override object WidgetHotbar.CreateExtra () inline virtual
Reimplemented from Widget.
Definition at line 11 of file WidgetHotbar.cs.
    {
        return new WidgetHotbar.Extra();
    }
GetItem()
HotItem WidgetHotbar.GetItem (int index) inline
Definition at line 185 of file WidgetHotbar.cs.
    {
        return this.hotbar.CurrentPage.items.TryGet(index, true);
    }
References Hotbar.CurrentPage, and hotbar.
Referenced by TryUse(), and WidgetCodex.Update().
GetSwapButton()
ButtonHotItem WidgetHotbar.GetSwapButton (UIButton b) inline
Definition at line 627 of file WidgetHotbar.cs.
    {
        foreach (Widget widget in EMono.ui.widgets.list)
        {
            WidgetHotbar widgetHotbar = widget as WidgetHotbar;
            if (!(widgetHotbar == null))
            {
                foreach (ButtonHotItem buttonHotItem in widgetHotbar.buttons)
                {
                    if (InputModuleEX.IsPointerOver(buttonHotItem) && b != buttonHotItem)
                    {
                        return buttonHotItem;
                    }
                }
            }
        }
        return null;
    }
References buttons, and EMono.ui.
Referenced by OnDrag(), and OnEndDrag().
OnActivate()
override void WidgetHotbar.OnActivate () inline virtual
Reimplemented from Widget.
Definition at line 81 of file WidgetHotbar.cs.
    {
        this.mold = this.layout.CreateMold(null);
        if (this.idHotbar == 2)
        {
            WidgetHotbar.HotBarMainMenu = this;
        }
        if (this.idHotbar == 3)
        {
            WidgetHotbar.HotbarBuild = this;
        }
        if (this.idHotbar == 5)
        {
            WidgetHotbar.HotbarExtra = this;
        }
        if (this.extra.rows == 0)
        {
            this.extra.rows = this.hotbar.itemsPerPage;
        }
        this.hotbar.actor = this;
        this.Rebuild();
    }
References extra, hotbar, idHotbar, Hotbar.itemsPerPage, layout, and Rebuild().
OnChangeActionMode()
override void WidgetHotbar.OnChangeActionMode () inline virtual
Reimplemented from Widget.
Definition at line 104 of file WidgetHotbar.cs.
    {
        base.OnChangeActionMode();
        if (this.hotbar.dirty)
        {
            this.hotbar.dirty = false;
            this.Rebuild();
        }
        this.RefreshHighlight();
    }
References Hotbar.dirty, hotbar, Rebuild(), and RefreshHighlight().
OnClickEmptyItem()
void WidgetHotbar.OnClickEmptyItem (ButtonHotItem b) inline
Definition at line 201 of file WidgetHotbar.cs.
    {
        UIContextMenu uicontextMenu = EMono.ui.CreateContextMenu("ContextMenu");
        this.SetShortcutMenu(b, uicontextMenu);
        uicontextMenu.Show();
    }
References SetShortcutMenu(), and EMono.ui.
OnDrag()
void WidgetHotbar.OnDrag (UIButton b) inline
Definition at line 613 of file WidgetHotbar.cs.
    {
        string text = "";
        if (this.GetSwapButton(b))
        {
            text = "hotitemSwap";
        }
        else if (!EMono.ui.isPointerOverUI)
        {
            text = "hotitemTrash";
        }
        EMono.ui.hud.SetDragText(text, null);
    }
References GetSwapButton(), text, and EMono.ui.
OnEndDrag()
void WidgetHotbar.OnEndDrag (UIButton b, bool cancel = false) inline
Definition at line 646 of file WidgetHotbar.cs.
    {
        EMono.ui.hud.imageDrag.SetActive(false);
        ButtonHotItem swapButton = this.GetSwapButton(b);
        if (swapButton)
        {
            SE.SelectHotitem();
            ButtonHotItem buttonHotItem = b as ButtonHotItem;
            HotItem hotItem = (HotItem)swapButton.item;
            HotItem hotItem2 = (HotItem)buttonHotItem.item;
            Hotbar hotbar = swapButton.widget.hotbar;
            Hotbar hotbar2 = buttonHotItem.widget.hotbar;
            hotbar.actor.SetItem(swapButton, hotItem2);
            hotbar2.actor.SetItem(buttonHotItem, hotItem);
            if (hotItem != null)
            {
                hotItem.button = buttonHotItem;
                hotItem.hotbar = hotbar2;
            }
            if (hotItem2 != null)
            {
                hotItem2.button = swapButton;
                hotItem2.hotbar = hotbar;
            }
            UIInventory.RefreshAllList();
            return;
        }
        if (EMono.ui.isPointerOverUI)
        {
            SE.Beep();
            return;
        }
        SE.Trash();
        this.SetItem(b as ButtonHotItem, null);
        UIInventory.RefreshAllList();
    }
References Hotbar.actor, GetSwapButton(), hotbar, UIInventory.RefreshAllList(), SetItem(), EMono.ui, and ButtonHotItem.widget.
OnSetContextMenu()
override void WidgetHotbar.OnSetContextMenu (UIContextMenu m) inline virtual
Reimplemented from Widget.
Definition at line 208 of file WidgetHotbar.cs.
    {
        ButtonHotItem b = InputModuleEX.GetComponentOf<ButtonHotItem>();
        if (this.showThisWidget || !b || b.item == null || base.IsSealed || b.widget.hotbar.IsLocked)
        {
            this.showThisWidget = false;
            SkinSet skin = base.config.skin.Skin;
            UIContextMenu uicontextMenu = m.AddChild("setting");
            UIContextMenu uicontextMenu2 = m.AddChild("style");
            if (!base.IsSealed)
            {
                uicontextMenu.AddSlider("numSlot", (float n) => n.ToString() ?? "", (float)this.extra.rows, delegate(float a)
                {
                    this.extra.rows = (int)a;
                    this.hotbar.SetSlotNum((int)a);
                    this.Rebuild();
                    this.ClampToScreen();
                }, 1f, 20f, true, false, false);
            }
            uicontextMenu2.AddSlider("iconSize", (float n) => n.ToString() ?? "", (float)this.extra.iconSize, delegate(float a)
            {
                this.extra.iconSize = (int)a;
                this.Rebuild();
                this.ClampToScreen();
            }, 0f, (float)(EMono.setting.ui.iconSizes.Count - 1), true, true, false);
            base.SetGridContextMenu(uicontextMenu2);
            uicontextMenu.AddToggle("vertical", this.extra.vertical, delegate(bool a)
            {
                this.extra.vertical = a;
                this.Rebuild();
                this.ClampToScreen();
            });
            uicontextMenu.AddToggle("doubleBar", this.extra.width == 2, delegate(bool a)
            {
                this.extra.width = (a ? 2 : 1);
                this.Rebuild();
                this.ClampToScreen();
            });
            uicontextMenu.AddToggle("reverseOrder", this.extra.reverse, delegate(bool a)
            {
                this.extra.reverse = a;
                this.Rebuild();
                this.ClampToScreen();
            });
            if (!base.IsSealed)
            {
                uicontextMenu.AddToggle("alwaysShow2", this.extra.alwaysShow, delegate(bool a)
                {
                    this.extra.alwaysShow = a;
                });
            }
            base.SetBaseContextMenu(m);
            if (!base.IsSealed)
            {
                Action <>9__12;
                m.AddButton("resetHotbar", delegate()
                {
                    string langDetail = "dialogResetHotbar";
                    Action actionYes;
                    if ((actionYes = <>9__12) == null)
                    {
                        actionYes = (<>9__12 = delegate()
{
                            EMono.player.hotbars.ResetHotbar(this.hotbar.id);
                            SE.Trash();
                        });
                    }
                    Dialog.YesNo(langDetail, actionYes, null, "yes", "no");
                }, true);
                return;
            }
        }
        else
        {
            m.AddButton("removeHotItem", delegate()
            {
                this.hotbar.SetItem(null, b.index, -1, false);
                this.RebuildPage(-1);
            }, true);
            b.item.OnShowContextMenu(m);
            m.AddToggle("alwaysShow", b.item.always, delegate(bool on)
            {
                b.item.always = on;
            });
            Action <>9__13;
            m.AddButton("thisWidget", delegate()
            {
                this.showThisWidget = true;
                List<Action> actionsNextFrame = EMono.core.actionsNextFrame;
                Action item;
                if ((item = <>9__13) == null)
                {
                    item = (<>9__13 = delegate()
                    {
                        this.ShowContextMenu();
                    });
                }
                actionsNextFrame.Add(item);
            }, true);
        }
    }
References Widget.ClampToScreen(), EMono.core, extra, hotbar, Player.hotbars, Hotbar.id, ButtonHotItem.index, Hotbar.IsLocked, EMono.player, Rebuild(), RebuildPage(), HotbarManager.ResetHotbar(), Hotbar.SetItem(), Hotbar.SetSlotNum(), EMono.setting, Widget.ShowContextMenu(), showThisWidget, GameSetting.ui, ButtonHotItem.widget, and Dialog.YesNo().
OnStartDrag()
void WidgetHotbar.OnStartDrag (UIButton b) inline
Definition at line 608 of file WidgetHotbar.cs.
    {
        EMono.ui.hud.SetDragImage(b.icon, null, null);
    }
References EMono.ui.
Rebuild()
void WidgetHotbar.Rebuild () inline
Definition at line 115 of file WidgetHotbar.cs.
    {
        this.buttons.Clear();
        this.layout.cellSize = EMono.setting.ui.iconSizes[this.extra.iconSize];
        this.layout.constraintCount = this.extra.width;
        this.layout.constraint = (this.extra.vertical ? GridLayoutGroup.Constraint.FixedColumnCount : GridLayoutGroup.Constraint.FixedRowCount);
        this.layout.startCorner = (this.extra.reverse ? GridLayoutGroup.Corner.LowerRight : GridLayoutGroup.Corner.UpperLeft);
        int num = this.extra.rows;
        if (this.extra.autoSize)
        {
            num = 0;
            int num2 = 0;
            while (num2 < this.hotbar.CurrentPage.items.Count && this.hotbar.CurrentPage.items[num2] != null)
            {
                num++;
                num2++;
            }
        }
        int num3 = (num - 1) / this.extra.width + 1;
        int num4 = this.extra.vertical ? this.extra.width : num3;
        int num5 = this.extra.vertical ? num3 : this.extra.width;
        this.imageGrid.uvRect = new Rect(1f, 1f, (float)num4, (float)num5);
        this.layout.DestroyChildren(false, true);
        for (int i = 0; i < num; i++)
        {
            ButtonHotItem buttonHotItem = Util.Instantiate<ButtonHotItem>(this.mold, this.layout);
            buttonHotItem.index = i;
            buttonHotItem.mainText.text = ((i > 10) ? "" : ((i + 1).ToString() ?? ""));
            buttonHotItem.widget = this;
            this.buttons.Add(buttonHotItem);
            if (this.useMask)
            {
                buttonHotItem.gameObject.AddComponent<RectMask2D>();
            }
        }
        this.layout.RebuildLayout(false);
        this.RebuildLayout(false);
        this.RebuildPage(-1);
    }
References buttons, Hotbar.CurrentPage, extra, hotbar, imageGrid, layout, mold, RebuildPage(), EMono.setting, GameSetting.ui, and useMask.
Referenced by OnActivate(), OnChangeActionMode(), OnSetContextMenu(), and HotbarManager.ResetHotbar().
RebuildPage()
void WidgetHotbar.RebuildPage (int page = -1) inline
Definition at line 155 of file WidgetHotbar.cs.
    {
        this.hotbar.SetPage((page == -1) ? this.hotbar.currentPage : page);
        foreach (ButtonHotItem buttonHotItem in this.buttons)
        {
            HotItem item = this.hotbar.GetItem(buttonHotItem.index, -1);
            buttonHotItem.SetItem(item);
        }
        this.SetVisible();
        this.RefreshHighlight();
    }
References buttons, Hotbar.currentPage, Hotbar.GetItem(), hotbar, ButtonHotItem.index, RefreshHighlight(), ButtonGrid.SetItem(), Hotbar.SetPage(), and SetVisible().
Referenced by CoreDebug.EnableDebugResource(), OnSetContextMenu(), Rebuild(), RebuildPages(), Hotbar.SetItem(), and SwitchPage().
RebuildPages()
static void WidgetHotbar.RebuildPages () inline static
Definition at line 167 of file WidgetHotbar.cs.
    {
        foreach (Widget widget in EMono.ui.widgets.list)
        {
            WidgetHotbar widgetHotbar = widget as WidgetHotbar;
            if (widgetHotbar)
            {
                widgetHotbar.RebuildPage(-1);
            }
        }
    }
References RebuildPage(), and EMono.ui.
Referenced by ContentConfigTest.OnInstantiate().
RefreshButtons()
static void WidgetHotbar.RefreshButtons () inline static
Definition at line 448 of file WidgetHotbar.cs.
    {
        foreach (Widget widget in EMono.ui.widgets.list)
        {
            WidgetHotbar widgetHotbar = widget as WidgetHotbar;
            if (widgetHotbar)
            {
                foreach (ButtonHotItem buttonHotItem in widgetHotbar.buttons)
                {
                    buttonHotItem.RefreshItem();
                }
            }
        }
    }
References buttons, ButtonHotItem.RefreshItem(), and EMono.ui.
Referenced by LayerWidget.OnInit(), and LayerCraft.RefreshTrackButton().
RefreshHighlight()
bool WidgetHotbar.RefreshHighlight () inline
Definition at line 463 of file WidgetHotbar.cs.
    {
        bool result = false;
        foreach (ButtonHotItem buttonHotItem in this.buttons)
        {
            if (buttonHotItem.item != null)
            {
                if (buttonHotItem.item.UseIconForHighlight)
                {
                    if (buttonHotItem.item.ShouldHighlight())
                    {
                        result = true;
                        buttonHotItem.icon.sprite = buttonHotItem.item.GetSprite(true);
                    }
                    else
                    {
                        buttonHotItem.icon.sprite = buttonHotItem.item.GetSprite();
                    }
                }
                else if (buttonHotItem.item.ShouldHighlight())
                {
                    result = true;
                    buttonHotItem.image.sprite = buttonHotItem.item.SpriteHighlight;
                    if (!this.Visible && buttonHotItem.item.KeepVisibleWhenHighlighted)
                    {
                        this.ToggleVisible();
                    }
                }
                else
                {
                    buttonHotItem.image.sprite = EMono.core.refs.spritesHighlight[0];
                }
            }
        }
        return result;
    }
References buttons, EMono.core, ToggleVisible(), and Visible.
Referenced by OnChangeActionMode(), HotItemToggle.OnClick(), HotItemToggleVisible.OnClick(), RebuildPage(), RefreshHighlights(), and SetItem().
RefreshHighlights()
static void WidgetHotbar.RefreshHighlights () inline static
Definition at line 436 of file WidgetHotbar.cs.
    {
        foreach (Widget widget in EMono.ui.widgets.list)
        {
            WidgetHotbar widgetHotbar = widget as WidgetHotbar;
            if (widgetHotbar)
            {
                widgetHotbar.RefreshHighlight();
            }
        }
    }
References RefreshHighlight(), and EMono.ui.
Referenced by BaseGameScreen.Activate(), ActionMode.ChangeGameSpeed(), ActionMode.DoFunc(), and Scene.OnToggle().
SetItem()
void WidgetHotbar.SetItem (ButtonHotItem b, HotItem item) inline
Definition at line 428 of file WidgetHotbar.cs.
    {
        item = this.hotbar.SetItem(item, b.index, -1, false);
        b.SetItem(item);
        this.RefreshHighlight();
        this.SetVisible();
    }
References hotbar, ButtonHotItem.index, RefreshHighlight(), ButtonGrid.SetItem(), Hotbar.SetItem(), and SetVisible().
Referenced by OnEndDrag(), ButtonHotItem.RegisterHotbar(), and SetShortcutMenu().
SetShortcutMenu()
void WidgetHotbar.SetShortcutMenu (ButtonHotItem b, UIContextMenu m) inline
Definition at line 310 of file WidgetHotbar.cs.
    {
        Action<UIContextMenu, HotItem> action = delegate(UIContextMenu _m, HotItem i)
        {
            _m.AddButton(i.Name, delegate()
            {
                this.SetItem(b, i);
            }, true);
        };
        UIContextMenu arg = m.AddChild("layerShortcuts");
        action(arg, new HotItemLayer
        {
            id = "LayerHelp"
        });
        action(arg, new HotItemLayer
        {
            id = "stash"
        });
        action(arg, new HotItemLayer
        {
            id = "LayerAbility"
        });
        action(arg, new HotItemLayer
        {
            id = "LayerChara"
        });
        action(arg, new HotItemLayer
        {
            id = "LayerJournal"
        });
        action(arg, new HotItemWidget
        {
            id = "Roster"
        });
        action(arg, new HotItemWidget
        {
            id = "Codex"
        });
        action(arg, new HotItemWidget
        {
            id = "Search"
        });
        action(arg, new HotItemWidget
        {
            id = "Tracker"
        });
        action(arg, new HotItemWidget
        {
            id = "Memo"
        });
        action(arg, new HotItemWidget
        {
            id = "QuestTracker"
        });
        arg = m.AddChild("utilShortcuts");
        action(arg, new HotItemToggle
        {
            type = HotItemToggle.Type.ToggleNoRoof
        });
        action(arg, new HotItemToggle
        {
            type = HotItemToggle.Type.muteBGM
        });
        action(arg, new HotItemToggle
        {
            type = HotItemToggle.Type.showBalloon
        });
        action(arg, new HotItemActionAudoDump());
        if (EMono.core.config.test.unsealWidgets)
        {
            arg = m.AddChild("menuShortcuts");
            action(arg, new HotItemContext
            {
                id = "system"
            });
            if (this == this.IsHotbarSpeed)
            {
                arg = m.AddChild("uniqueShortcuts");
                action(arg, new HotItemSpeed
                {
                    id = 0
                });
                action(arg, new HotItemSpeed
                {
                    id = 1
                });
                action(arg, new HotItemSpeed
                {
                    id = 2
                });
                action(arg, new HotItemSpeed
                {
                    id = 3
                });
            }
        }
        arg = m.AddChild("specialShortcuts");
        action(arg, new HotItemTogglePage());
        action(arg, new HotItemToggleVisible());
        m.AddButton("registerPos".lang(), delegate()
        {
            this.SetItem(b, new HotItemFocusPos
            {
                zone = EMono.game.activeZone,
                x = EMono.pc.pos.x,
                y = EMono.pc.pos.z
            });
        }, true);
        m.AddButton("hotActionEQSet".lang(), delegate()
        {
            this.SetItem(b, new HotItemEQSet().Register());
        }, true);
        m.AddButton("hotActionSleep".lang(), delegate()
        {
            this.SetItem(b, new HotItemActionSleep());
        }, true);
    }
References Game.activeZone, EMono.core, EMono.game, IsHotbarSpeed, EMono.pc, Card.pos, SetItem(), type, and Point.x.
Referenced by OnClickEmptyItem().
SetVisible()
void WidgetHotbar.SetVisible () inline
Definition at line 511 of file WidgetHotbar.cs.
    {
        UIButton componentOf = InputModuleEX.GetComponentOf<UIButton>();
        int num = 0;
        bool flag = false;
        foreach (ButtonHotItem buttonHotItem in this.buttons)
        {
            bool flag2 = buttonHotItem.item is HotItemToggleVisible;
            bool flag3 = this.Visible || flag2 || (buttonHotItem.item != null && buttonHotItem.item.always);
            buttonHotItem.image.enabled = flag3;
            buttonHotItem.mainText.enabled = flag3;
            buttonHotItem.icon.SetActive(flag3);
            if (!flag2 && buttonHotItem != componentOf)
            {
                buttonHotItem.DoNormalTransition(true);
            }
            if (flag3)
            {
                num++;
            }
            if (flag2)
            {
                flag = true;
            }
        }
        if (num == 0 && !this.Visible)
        {
            this.Visible = true;
            this.SetVisible();
        }
        base.CancelInvoke("CheckAutoHide");
        if (flag)
        {
            this.timeSinceBecomeVisible = 0f;
            base.InvokeRepeating("CheckAutoHide", 0.1f, 0.2f);
        }
        this.imageBG.enabled = (this.imageGrid.enabled = this.extra.visible);
        this.dragPanel.SetActive(this.extra.visible);
    }
References buttons, Widget.dragPanel, extra, SetVisible(), and Visible.
Referenced by RebuildPage(), SetItem(), SetVisible(), and ToggleVisible().
SwitchPage()
void WidgetHotbar.SwitchPage () inline
Definition at line 179 of file WidgetHotbar.cs.
    {
        SE.ClickGeneral();
        this.RebuildPage((this.hotbar.currentPage == 0) ? 1 : 0);
    }
References Hotbar.currentPage, hotbar, and RebuildPage().
Referenced by HotItemTogglePage.OnClick().
ToggleVisible()
void WidgetHotbar.ToggleVisible () inline
Definition at line 551 of file WidgetHotbar.cs.
    {
        this.extra.visible = !this.extra.visible;
        this.SetVisible();
        if (this.Visible)
        {
            this.imageBG.transform.localScale = new Vector3(0.6f, 0.6f, 1f);
            this.imageBG.transform.DOScale(1f, 0.12f).SetEase(Ease.Linear);
            this.imageGrid.transform.localScale = new Vector3(0.6f, 0.6f, 1f);
            this.imageGrid.transform.DOScale(1f, 0.12f).SetEase(Ease.Linear);
            foreach (ButtonHotItem buttonHotItem in this.buttons)
            {
                if (!(buttonHotItem.item is HotItemToggleVisible) && (buttonHotItem.item == null || !buttonHotItem.item.always))
                {
                    buttonHotItem.transform.localScale = new Vector3(0.6f, 0.6f, 1f);
                    buttonHotItem.transform.DOScale(1f, 0.12f).SetEase(Ease.Linear);
                }
            }
            this.imageBG.SetAlpha(0f);
            this.imageGrid.SetAlpha(0f);
            SkinConfig skin = base.config.skin;
            this.imageBG.DOFade(skin.bgColor.a, 0.4f).SetEase(Ease.OutQuint);
            this.imageGrid.DOFade(skin.gridColor.a, 0.4f).SetEase(Ease.OutQuint);
        }
    }
References buttons, extra, Widget.imageBG, imageGrid, SetVisible(), and Visible.
Referenced by CheckAutoHide(), HotItemToggleVisible.OnClick(), RefreshHighlight(), ButtonHotItem.RefreshItem(), and LayerRegisterHotbar.Show().
TryUse()
void WidgetHotbar.TryUse (int index) inline
Definition at line 190 of file WidgetHotbar.cs.
    {
        HotItem item = this.GetItem(index);
        if (item == null)
        {
            SE.BeepSmall();
            return;
        }
        item.OnClick(item.button, this.hotbar);
    }
References HotItem.button, GetItem(), and HotItem.OnClick().
Referenced by ActionMode.UpdateInput().
Member Data Documentation
buttons
List<ButtonHotItem> WidgetHotbar.buttons = new List<ButtonHotItem>()
Definition at line 710 of file WidgetHotbar.cs.
Referenced by _OnDirtyInventory(), CheckAutoHide(), LayerRegisterHotbar.GetButton(), GetSwapButton(), Rebuild(), RebuildPage(), RefreshButtons(), RefreshHighlight(), SetVisible(), and ToggleVisible().
dirtyCurrentItem
bool WidgetHotbar.dirtyCurrentItem static
Definition at line 685 of file WidgetHotbar.cs.
Referenced by Scene.OnUpdate().
HotbarBuild
WidgetHotbar WidgetHotbar.HotbarBuild static
Definition at line 689 of file WidgetHotbar.cs.
Referenced by CoreDebug.EnableDebugResource().
HotbarExtra
WidgetHotbar WidgetHotbar.HotbarExtra static
Definition at line 693 of file WidgetHotbar.cs.
Referenced by WidgetCodex.Update(), and ActionMode.UpdateInput().
HotBarMainMenu
WidgetHotbar WidgetHotbar.HotBarMainMenu static
Definition at line 691 of file WidgetHotbar.cs.
idHotbar
int WidgetHotbar.idHotbar
Definition at line 695 of file WidgetHotbar.cs.
Referenced by OnActivate().
imageGrid
RawImage WidgetHotbar.imageGrid
Definition at line 701 of file WidgetHotbar.cs.
Referenced by Rebuild(), and ToggleVisible().
imageSelect
Image WidgetHotbar.imageSelect
Definition at line 703 of file WidgetHotbar.cs.
layout
GridLayoutGroup WidgetHotbar.layout
Definition at line 697 of file WidgetHotbar.cs.
Referenced by OnActivate(), and Rebuild().
mold
ButtonHotItem WidgetHotbar.mold
Definition at line 699 of file WidgetHotbar.cs.
Referenced by Rebuild().
registering
bool WidgetHotbar.registering static
Definition at line 683 of file WidgetHotbar.cs.
Referenced by CheckAutoHide(), ButtonHotItem.OnHover(), and ButtonHotItem.RefreshItem().
registeringItem
HotItem WidgetHotbar.registeringItem static
Definition at line 687 of file WidgetHotbar.cs.
Referenced by ButtonHotItem.RegisterHotbar().
showThisWidget
bool WidgetHotbar.showThisWidget private
Definition at line 712 of file WidgetHotbar.cs.
Referenced by OnSetContextMenu().
timeSinceBecomeVisible
float WidgetHotbar.timeSinceBecomeVisible private
Definition at line 714 of file WidgetHotbar.cs.
Referenced by CheckAutoHide().
type
Hotbar.Type WidgetHotbar.type
Definition at line 705 of file WidgetHotbar.cs.
Referenced by SetShortcutMenu().
useMask
bool WidgetHotbar.useMask
Definition at line 707 of file WidgetHotbar.cs.
Referenced by Rebuild().
Property Documentation
CanRegisterItem
bool WidgetHotbar.CanRegisterItem get
Definition at line 60 of file WidgetHotbar.cs.
    {
        get
        {
            return this.hotbar.IsUserHotbar;
        }
    }
Referenced by ButtonHotItem.RefreshItem(), and LayerRegisterHotbar.Show().
extra
WidgetHotbar.Extra WidgetHotbar.extra get
Definition at line 16 of file WidgetHotbar.cs.
    {
        get
        {
            return base.config.extra as WidgetHotbar.Extra;
        }
    }
Referenced by OnActivate(), OnSetContextMenu(), Rebuild(), ButtonHotItem.RefreshItem(), SetVisible(), and ToggleVisible().
hotbar
Hotbar WidgetHotbar.hotbar get
Definition at line 24 of file WidgetHotbar.cs.
    {
        get
        {
            return EMono.player.hotbars.bars[this.idHotbar];
        }
    }
Referenced by CanShowContextMenu(), GetItem(), OnActivate(), OnChangeActionMode(), OnEndDrag(), HotItemToggleVisible.OnHover(), OnSetContextMenu(), Rebuild(), RebuildPage(), ButtonHotItem.RefreshItem(), SetItem(), LayerRegisterHotbar.Show(), and SwitchPage().
IsHotbarSpeed
bool WidgetHotbar.IsHotbarSpeed get
Definition at line 52 of file WidgetHotbar.cs.
    {
        get
        {
            return this.idHotbar == 7;
        }
    }
Referenced by SetShortcutMenu().
ShowInBuildMode
override bool WidgetHotbar.ShowInBuildMode get
Definition at line 44 of file WidgetHotbar.cs.
    {
        get
        {
            return this.extra.alwaysShow;
        }
    }
Visible
bool WidgetHotbar.Visible get set
Definition at line 32 of file WidgetHotbar.cs.
    {
        get
        {
            return this.extra.visible;
        }
        set
        {
            this.extra.visible = value;
        }
    }
Referenced by CheckAutoHide(), HotItemToggleVisible.OnClick(), HotItemToggleVisible.OnHover(), RefreshHighlight(), ButtonHotItem.RefreshItem(), SetVisible(), LayerRegisterHotbar.Show(), and ToggleVisible().
The documentation for this class was generated from the following file:
Elin/WidgetHotbar.cs