Elin Decompiled Documentation: Check Class Reference
Check Class Reference
Public Types
enum Result { CriticalPass , Pass , Fail , CriticalFail }
enum Output { None , Default }
Public Member Functions
string GetText (Chara p, Card tg, bool inDialog=false)
int GetDC (Card tg=null)
int GetFinalDC (Chara p, Card tg=null)
Result Perform (Chara p, Card tg=null)
Result Perform (Chara p, Card tg, Action< Result > action)
Static Public Member Functions
static Check Get (string id, float dcMod=1f)
Static Public Member Functions inherited from EClass
static int rnd (int a)
static int curve (int a, int start, int step, int rate=75)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Public Attributes
SourceCheck.Row _source
string id
float dcMod
Properties
SourceCheck.Row source [get]
string mainElementName [get]
int baseDC [get]
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Additional Inherited Members
Static Public Attributes inherited from EClass
static Core core
Detailed Description
Definition at line 4 of file Check.cs.
Member Enumeration Documentation
Output
enum Check.Output
Enumerator
None
Default
Definition at line 14 of file Check.cs.
    {
        None,
        Default
    }
Result
enum Check.Result
Enumerator
CriticalPass
Pass
Fail
CriticalFail
Definition at line 6 of file Check.cs.
    {
        CriticalPass,
        Pass,
        Fail,
        CriticalFail
    }
Member Function Documentation
Get()
static Check Check.Get (string id, float dcMod = 1f) inline static
Definition at line 32 of file Check.cs.
    {
        return new Check
        {
            id = id,
            dcMod = dcMod
        };
    }
References dcMod, and id.
Referenced by DramaActor.SetChoice().
GetDC()
int Check.GetDC (Card tg = null) inline
Definition at line 54 of file Check.cs.
    {
        float num = (float)baseDC * dcMod;
        if (tg == null)
        {
            return (int)num;
        }
        num += source.lvMod * (float)tg.LV;
        if (source.targetElement != 0)
        {
            Element element = tg.elements.GetElement(source.element);
            if (element != null)
            {
                num += (float)element.Value;
                if (source.targetSubFactor > 0f && !element.source.aliasParent.IsEmpty())
                {
                    Element element2 = tg.elements.GetElement(element.source.aliasParent);
                    if (element2 != null)
                    {
                        num += source.targetSubFactor * (float)element2.Value;
                    }
                }
            }
        }
        return (int)num;
    }
References baseDC, dcMod, if(), source, Element.source, and Element.Value.
Referenced by GetFinalDC(), and GetText().
GetFinalDC()
int Check.GetFinalDC (Chara p, Card tg = null) inline
Definition at line 81 of file Check.cs.
    {
        int num = GetDC(tg);
        if (source.element != 0)
        {
            Element element = p.elements.GetElement(source.element);
            if (element != null)
            {
                num -= element.Value;
                if (source.subFactor > 0f && !element.source.aliasParent.IsEmpty())
                {
                    Element element2 = p.elements.GetElement(element.source.aliasParent);
                    if (element2 != null)
                    {
                        num -= (int)(source.subFactor * (float)element2.Value);
                    }
                }
            }
        }
        if (num > 14)
        {
            num = 14 + (int)Mathf.Sqrt(num - 14);
        }
        else if (num < 6)
        {
            num = 6 - (int)Mathf.Sqrt(6 - num);
        }
        return num;
    }
References Card.elements, GetDC(), ElementContainer.GetElement(), source, Element.source, and Element.Value.
Referenced by GetText(), and Perform().
GetText()
string Check.GetText (Chara p, Card tg, bool inDialog = false) inline
Definition at line 41 of file Check.cs.
    {
        string text = "";
        int finalDC = GetFinalDC(p, tg);
        string text2 = ((finalDC > 20) ? "" : ((finalDC > 17) ? "" : ((finalDC > 14) ? "" : ((finalDC > 11) ? "" : ((finalDC > 8) ? "" : ((finalDC > 5) ? "" : ((finalDC > 2) ? "" : "")))))));
        if (finalDC <= 20 && finalDC <= 15 && finalDC <= 10)
        {
            _ = 5;
        }
        text = text + "DC " + GetDC(tg) + " " + mainElementName + " " + text2;
        return text + " " + source.element + "/" + EClass.sources.elements.map[source.element].alias;
    }
References SourceManager.elements, GetDC(), GetFinalDC(), mainElementName, source, and EClass.sources.
Perform() [1/2]
Result Check.Perform (Chara p, Card tg, Action< Result > action) inline
Definition at line 140 of file Check.cs.
    {
        Result result = Perform(p, tg);
        action?.Invoke(result);
        return result;
    }
References Perform().
Perform() [2/2]
Result Check.Perform (Chara p, Card tg = null) inline
Definition at line 111 of file Check.cs.
    {
        int finalDC = GetFinalDC(p, tg);
        int num = Dice.Roll(1, 20);
        if (EClass.debug.logDice)
        {
            string text = "Check:" + source.id + " dc=" + finalDC + " roll=" + num + "  ";
            Debug.Log(num switch
            {
                20 => text + "CriticalPass",
                1 => text + "CriticalFail",
                _ => (num < finalDC) ? (text + "Fail") : (text + "Pass"),
            });
        }
        switch (num)
        {
        case 20:
            return Result.CriticalPass;
        case 1:
            return Result.CriticalFail;
        default:
            if (num >= finalDC)
            {
                return Result.Pass;
            }
            return Result.Fail;
        }
    }
References EClass.debug, Debug, GetFinalDC(), CoreDebug.logDice, and Dice.Roll().
Referenced by Perform().
Member Data Documentation
_source
SourceCheck.Row Check._source
Definition at line 20 of file Check.cs.
dcMod
float Check.dcMod
Definition at line 24 of file Check.cs.
Referenced by Get(), and GetDC().
id
string Check.id
Definition at line 22 of file Check.cs.
Referenced by Get().
Property Documentation
baseDC
int Check.baseDC get
Definition at line 30 of file Check.cs.
Referenced by GetDC().
mainElementName
string Check.mainElementName get
Definition at line 28 of file Check.cs.
Referenced by GetText().
source
SourceCheck.Row Check.source get
Definition at line 26 of file Check.cs.
Referenced by GetDC(), GetFinalDC(), and GetText().
The documentation for this class was generated from the following file:
Elin/Check.cs