Elin Decompiled Documentation: TaskHarvest Class Reference
TaskHarvest Class Reference
Public Member Functions
override bool CanManualCancel ()
override string GetBaseText (string str)
override string GetTextSmall (Card c)
override bool CanProgress ()
override HitResult GetHitResult ()
override void OnCreateProgress (Progress_Custom p)
string GetIdDismantled ()
bool ShouldGenerateDismantled (string dest)
bool HaveHarvestThing ()
void HarvestThing ()
Public Member Functions inherited from BaseTaskHarvest
virtual string GetBaseText (string str)
override string GetTextSmall (Card c)
override string GetText (string str="")
void SetTarget (Chara c, Thing _tool=null)
int GetToolEfficiency (Thing t, SourceMaterial.Row mat)
override bool CanProgress ()
int[] GetToolEfficiency (SourceMaterial.Row mat)
string GetTextDifficulty ()
Public Member Functions inherited from TaskDesignation
virtual string GetTextOrbit ()
bool PointHasOtherDesignation ()
virtual void DrawMarker (int x, int z, RenderParam p)
virtual void Draw (int x, int z, RenderParam p)
virtual void OnEnterScreen ()
virtual void OnLeaveScreen ()
virtual void TrySpawnOrbit ()
void DespawnOrbit ()
Public Member Functions inherited from TaskPoint
override bool CanManualCancel ()
override bool CanPerform ()
override bool _CanPerformTask (Chara chara, int radius)
override IEnumerable< Status > Run ()
void OnInspect ()
void WriteNote (UINote n, Action< UINote > onWriteNote=null, IInspect.NoteMode mode=IInspect.NoteMode.Default, Recipe recipe=null)
Public Member Functions inherited from Task
virtual HitResult GetHitResult ()
override void OnSuccess ()
void TryLater (int min=30)
Status Destroy ()
virtual void OnDestroy ()
override Status Cancel ()
override void OnReset ()
override bool CanProgress ()
bool CanPerformTask (Chara chara, int radius)
virtual bool _CanPerformTask (Chara chara, int radius)
virtual void OnAdd ()
void ToggleSuspend ()
Public Member Functions inherited from AIAct
override string ToString ()
override MultiSprite GetStateIcon ()
virtual bool ShouldAllyAttack (Chara tg)
virtual Point GetDestination ()
AIProgress GetProgress ()
string GetCurrentActionText ()
override bool IsToolValid ()
virtual void OnStart ()
void SetOwner (Chara c)
virtual void OnSetOwner ()
void SetChild (AIAct seq, Func< Status > _onChildFail=null)
void Start ()
override bool Perform ()
Status Restart ()
Status Success (Action action=null)
virtual void OnSuccess ()
bool TryCancel (Card c)
virtual Status Cancel ()
virtual void OnCancel ()
virtual void OnCancelOrSuccess ()
virtual bool CanManualCancel ()
Status KeepRunning ()
void Reset ()
virtual void OnReset ()
Status Tick ()
virtual IEnumerable< Status > Run ()
Status TickChild ()
Status Do (AIAct _seq, Func< Status > _onChildFail=null)
Status DoGotoInteraction (Point pos, Func< Status > _onChildFail=null)
Status DoGoto (Point pos, int dist=0, bool ignoreConnection=false, Func< Status > _onChildFail=null)
Status DoGoto (Card card, Func< Status > _onChildFail=null)
Status DoGoto (Card card, int dist, Func< Status > _onChildFail=null)
Status DoGotoSpot (Card card, Func< Status > _onChildFail=null)
Status DoGoto< T > (Func< Status > _onChildFail=null)
Status DoGotoSpot< T > (Func< Status > _onChildFail=null, bool ignoreAccessType=false)
Status DoGrab (Card card, int num=-1, bool pickHeld=false, Func< Status > _onChildFail=null)
Status DoGrab< T > ()
Status DoProgress ()
Status DoIdle (int repeat=3)
Status DoWait (int count=1)
virtual AIProgress CreateProgress ()
virtual void OnCreateProgress (Progress_Custom p)
virtual bool CanProgress ()
virtual void OnBeforeProgress ()
virtual void OnProgress ()
virtual void OnProgressComplete ()
void SimulateZone (int days)
virtual void OnSimulateZone (int days)
virtual void OnSimulatePosition ()
Public Member Functions inherited from Act
virtual CursorInfo GetCursorIcon (Card c)
virtual MultiSprite GetStateIcon ()
override Sprite GetSprite ()
virtual bool ShowMouseHint (Card c)
virtual bool IsValidTC (Card c)
virtual string GetHintText (string str="")
virtual string GetText (string str="")
virtual string GetTextSmall (Card c)
bool IsTargetHostileParty ()
virtual Color GetActPlanColor ()
virtual bool Perform ()
virtual bool CanPerform ()
bool Perform (Chara _cc, Card _tc=null, Point _tp=null)
bool CanPerform (Chara _cc, Card _tc=null, Point _tp=null)
virtual bool IsToolValid ()
new void SetImage (Image image)
virtual void OnMarkMapHighlights ()
virtual bool ShouldMapHighlight (Point p)
Public Member Functions inherited from Element
virtual SourceElement.Row GetSource ()
virtual int GetSourcePotential (int v)
virtual Sprite GetSprite ()
int GetMaterialSourceValue (Thing t, int v)
virtual int GetSourceValue (int v, int lv, SourceValueType type)
virtual Sprite GetIcon (string suffix="")
bool IsActive (Card c)
int SortVal (bool charaSheet=false)
virtual bool CanLink (ElementContainer owner)
bool HasTag (string tag)
void SetImage (Image i)
virtual string GetDetail ()
bool IsFactionElement (Chara c)
Element GetParent (Card c)
void WriteNote (UINote n, ElementContainer owner=null, Action< UINote > onWriteNote=null)
void WriteNoteWithRef (UINote n, ElementContainer owner, Action< UINote > onWriteNote, Element refEle)
void _WriteNote (UINote n, Chara c, Act act)
void AddHeaderAbility (UINote n)
void _WriteNote (UINote n, ElementContainer owner, Action< UINote > onWriteNote, bool isRef, bool addHeader=true)
void AddEncNote (UINote n, Card Card, ElementContainer.NoteMode mode=ElementContainer.NoteMode.Default, Func< Element, string, string > funcText=null, Action< UINote, Element > onAddNote=null)
virtual void OnWriteNote (UINote n, ElementContainer owner)
virtual void OnChangeValue ()
void CheckLevelBonus (ElementContainer owner, UINote n=null)
int GetSortVal (UIList.SortMode m)
virtual Act.Cost GetCost (Chara c)
virtual int GetPower (Card c)
virtual void SetTextValue (UIText text)
virtual bool IsPurchaseFeatReqMet (ElementContainer owner, int lv=-1)
virtual void WritePurchaseReq (UINote n, int lv=1)
void WriteNote (UINote n, Action< UINote > onWriteNote=null, NoteMode mode=NoteMode.Default, Recipe recipe=null)
void OnInspect ()
void OnEnterScreen ()
void OnLeaveScreen ()
Static Public Member Functions
static TaskHarvest TryGetAct (Chara c, Point p)
Static Public Member Functions inherited from BaseTaskHarvest
static Thing GetBestTool (Chara c, Point p)
static int GetReqEle (string _raw)
Static Public Member Functions inherited from Act
static void SetReference (Chara _cc, Card _tc=null, Point _tp=null)
static void SetTool (Thing t)
Static Public Member Functions inherited from Element
static string GetName (string alias)
static SourceElement.Row Get (int id)
static Dictionary< int, int > GetElementMap (int[] list)
static Dictionary< int, int > GetElementMap (int[] list, Dictionary< int, int > map)
static SourceElement.Row GetRandomElement (int lv=1, bool useWeight=true)
static Element Create (int id, int v=0)
static Element Create (string id, int v=1)
static int GetId (string alias)
static int GetResistLv (int v)
static int GetResistDamage (int dmg, int v, int power=0)
Static Public Member Functions inherited from EClass
static int rndSeed (int a, int seed)
static int rnd (long a)
static int rnd (int a)
static int curve (int a, int start, int step, int rate=75)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Public Attributes
bool wasReapSeed
bool wasCrime
bool harvestingCrop
HarvestType mode = HarvestType.Obj
Public Attributes inherited from BaseTaskHarvest
Thing target
Element reqElement
int matHardness
int idEle
int reqLv
int toolLv
int maxProgress
int efficiency
int difficulty
int effectFrame = 1
bool isToolRequired
Thing tool
Public Attributes inherited from TaskDesignation
long sync
bool isSynced
TCOrbitTask orbit
Public Attributes inherited from TaskPoint
Point pos = new Point()
bool isRepeated
Public Attributes inherited from Task
TaskList taskList
bool isDestroyed
int nextTry
bool suspended
Public Attributes inherited from AIAct
new Chara owner
Status status
IEnumerator< Status > Enumerator
AIAct child
AIAct parent
byte restartCount
Func< Status > onChildFail
Func< bool > isFail
Public Attributes inherited from Element
SourceElement.Row _source
int id
int vBase
int vExp
int vPotential
int vTempPotential
int vLink
int vSource
int vSourcePotential
ElementContainer owner
Properties
bool IsObj [get]
bool IsReapSeed [get]
override HarvestType harvestType [get]
override int RightHand [get]
override int destDist [get]
override bool IsGrowth [get]
override bool IsHostileAct [get]
override bool Loop [get]
Properties inherited from BaseTaskHarvest
bool IsTooHard [get]
bool IsHarvest [get]
virtual bool CanReapSeed [get]
virtual HarvestType harvestType [get]
virtual bool IsGrowth [get]
override bool CanPressRepeat [get]
override int LeftHand [get]
override CursorInfo CursorIcon [get]
Properties inherited from TaskDesignation
override bool HasProgress [get]
virtual int idMarker [get]
virtual int W [get]
virtual int H [get]
virtual bool ShowOrbit [get]
virtual bool Working [get]
override bool ShowAuto [get]
override CursorInfo CursorIcon [get]
TaskManager.Designations Designations [get]
long Sync [get]
Properties inherited from TaskPoint
override bool HasProgress [get]
virtual int destDist [get]
virtual bool destIgnoreConnection [get]
virtual bool isBlock [get]
virtual bool Loop [get]
bool CanInspect [get]
string InspectName [get]
Point InspectPoint [get]
Vector3 InspectPosition [get]
Properties inherited from Task
override TargetType TargetType [get]
Properties inherited from AIAct
virtual bool IsRunning [get]
bool IsChildRunning [get]
bool IsMoveAI [get]
virtual int MaxRestart [get]
virtual new string Name [get]
virtual MultiSprite stateIcon [get]
virtual Sprite actionIcon [get]
virtual bool IsNoGoal [get]
virtual bool IsAutoTurn [get]
virtual bool IsIdle [get]
virtual bool CancelOnAggro [get]
virtual bool PushChara [get]
virtual int MaxProgress [get]
virtual bool ShowProgress [get]
virtual bool UseTurbo [get]
virtual int CurrentProgress [get]
virtual bool ShowCursor [get]
virtual bool CancelWhenDamaged [get]
virtual bool CancelWhenMoved [get]
virtual bool InformCancel [get]
virtual Thing RenderThing [get]
AIAct Current [get]
override bool IsAct [get]
override bool ShowPotential [get]
override bool UsePotential [get]
override bool ShowRelativeAttribute [get]
virtual bool HasProgress [get]
Properties inherited from Act
override bool ShowPotential [get]
override bool UsePotential [get]
override bool ShowRelativeAttribute [get]
virtual CursorInfo CursorIcon [get]
virtual string ID [get]
virtual bool IsAct [get]
virtual bool WillEndTurn [get]
virtual bool CloseLayers [get]
virtual int LeftHand [get]
virtual int RightHand [get]
virtual int ElementPowerMod [get]
virtual bool ShowMapHighlight [get]
virtual bool ShowMapHighlightBlock [get]
virtual bool PickHeldOnStart [get]
virtual bool DropHeldOnStart [get]
virtual bool CanPressRepeat [get]
virtual bool CanAutofire [get]
virtual bool ResetAxis [get]
virtual bool RequireTool [get]
virtual bool IsHostileAct [get]
virtual bool HideRightInfo [get]
virtual bool HaveLongPressAction [get]
virtual float Radius [get]
virtual int PerformDistance [get]
virtual int MaxRadius [get]
virtual TargetType TargetType [get]
virtual bool LocalAct [get]
virtual bool CanRapidFire [get]
virtual float RapidDelay [get]
virtual bool ShowAuto [get]
virtual bool IsCrime [get]
Properties inherited from Element
SourceElement.Row source [get]
virtual int DisplayValue [get]
virtual int MinValue [get]
int Value [get]
int ValueWithoutLink [get]
virtual int MinPotential [get]
int Potential [get]
virtual bool CanGainExp [get]
bool IsFlag [get]
virtual string Name [get]
virtual string FullName [get]
virtual int ExpToNext [get]
virtual bool UseExpMod [get]
virtual int CostTrain [get]
virtual int CostLearn [get]
virtual bool ShowXP [get]
virtual bool ShowMsgOnValueChanged [get]
virtual bool ShowValue [get]
virtual bool ShowPotential [get]
virtual bool UsePotential [get]
virtual bool PotentialAsStock [get]
virtual bool ShowRelativeAttribute [get]
virtual bool ShowBonuses [get]
virtual string ShortName [get]
bool IsGlobalElement [get]
bool IsFactionWideElement [get]
bool IsPartyWideElement [get]
virtual bool ShowEncNumber [get]
bool IsTrait [get]
bool IsFoodTrait [get]
bool IsFoodTraitMain [get]
bool IsMainAttribute [get]
Act act [get]
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Properties inherited from IInspect
bool CanInspect [get]
string InspectName [get]
Point InspectPoint [get]
Vector3 InspectPosition [get]
Properties inherited from ISyncScreen
long Sync [get]
Additional Inherited Members
Public Types inherited from BaseTaskHarvest
enum HarvestType {
Floor , Block , Obj , Thing ,
Disassemble
}
Public Types inherited from AIAct
enum Status { Running , Fail , Success }
Public Types inherited from Act
enum CostType { None , MP , SP }
Public Types inherited from IInspect
enum NoteMode { Default , Recipe , Product , Info }
Static Public Attributes inherited from Act
static Chara CC
static Card TC
static Point TP = new Point()
static Thing TOOL
static int powerMod = 100
static bool forcePt
static Act CurrentAct
Static Public Attributes inherited from Element
const int Div = 5
static Element Void = new Element()
static int[] List_MainAttributes = new int[9] { 70, 72, 71, 77, 74, 75, 76, 73, 79 }
static int[] List_MainAttributesMajor = new int[8] { 70, 72, 71, 77, 74, 75, 76, 73 }
static int[] List_Body = new int[4] { 70, 72, 71, 77 }
static int[] List_Mind = new int[4] { 74, 75, 76, 73 }
static List< SourceElement.Row > ListElements = new List<SourceElement.Row>()
static List< SourceElement.Row > ListAttackElements = new List<SourceElement.Row>()
Static Public Attributes inherited from EClass
static Core core
Detailed Description
Definition at line 3 of file TaskHarvest.cs.
Member Function Documentation
CanManualCancel()
override bool TaskHarvest.CanManualCancel () inline virtual
Reimplemented from AIAct.
Definition at line 85 of file TaskHarvest.cs.
    {
        return true;
    }
CanProgress()
override bool TaskHarvest.CanProgress () inline virtual
Reimplemented from BaseTaskHarvest.
Definition at line 208 of file TaskHarvest.cs.
    {
        if (tool != null && tool.trait is TraitToolSickle && !pos.cell.CanReapSeed())
        {
            return false;
        }
        if (IsObj)
        {
            SetTarget(owner ?? EClass.pc);
            if (base.CanProgress())
            {
                return pos.HasObj;
            }
            return false;
        }
        if (target == null || !target.ExistsOnMap)
        {
            return false;
        }
        return base.CanProgress();
    }
References Cell.CanReapSeed(), Point.cell, Card.ExistsOnMap, Point.HasObj, IsObj, AIAct.owner, EClass.pc, TaskPoint.pos, BaseTaskHarvest.SetTarget(), BaseTaskHarvest.target, BaseTaskHarvest.tool, and Card.trait.
GetBaseText()
override string TaskHarvest.GetBaseText (string str) inline virtual
Reimplemented from BaseTaskHarvest.
Definition at line 90 of file TaskHarvest.cs.
    {
        if (IsReapSeed)
        {
            return "TaskHarvestSeed".lang();
        }
        if (mode == HarvestType.Disassemble)
        {
            string text = (HaveHarvestThing() ? "TaskDisassemble" : "TaskDisassemble_destroy").lang();
            string idRecipe = (IsObj ? pos.sourceObj.RecipeID : ((target != null) ? target.source.RecipeID : ""));
            if (EClass.debug.enable && EClass.player.recipes.CanCeomUpWithRecipe(idRecipe))
            {
                text = text + " " + "TaskDisassemble_newrecipe".lang();
            }
            return text;
        }
        if (!base.IsHarvest)
        {
            return base.GetBaseText(str);
        }
        return "actHarvest".lang();
    }
References RecipeManager.CanCeomUpWithRecipe(), EClass.debug, CoreDebug.enable, HaveHarvestThing(), IsObj, IsReapSeed, mode, EClass.player, Player.recipes, Thing.source, and BaseTaskHarvest.target.
GetHitResult()
override HitResult TaskHarvest.GetHitResult () inline virtual
Reimplemented from Task.
Definition at line 230 of file TaskHarvest.cs.
    {
        if (harvestingCrop && !base.IsHarvest)
        {
            return HitResult.Default;
        }
        if (IsObj)
        {
            if (base.IsHarvest)
            {
                return HitResult.Valid;
            }
            if (pos.HasObj)
            {
                return HitResult.Valid;
            }
            if (pos.HasDecal && EClass.debug.godBuild && (bool)BuildMenu.Instance)
            {
                return HitResult.Valid;
            }
            return HitResult.Default;
        }
        if (target == null || !target.ExistsOnMap)
        {
            return HitResult.Default;
        }
        return HitResult.Valid;
    }
References EClass.debug, Card.ExistsOnMap, CoreDebug.godBuild, harvestingCrop, Point.HasDecal, Point.HasObj, BuildMenu.Instance, IsObj, TaskPoint.pos, and BaseTaskHarvest.target.
GetIdDismantled()
string TaskHarvest.GetIdDismantled () inline
Definition at line 484 of file TaskHarvest.cs.
    {
        if (target.HasElement(707))
        {
            return "fish_slice";
        }
        string[] array = target.source.components[0].Split('|');
        for (int i = 0; i < array.Length; i++)
        {
            array[i] = array[i].Split('/')[0];
        }
        string result = array[0];
        if (array.Length > 1)
        {
            string category = target.material.category;
            bool flag = category == "rock" || category == "ore" || category == "gem";
            if (array[0] == "ingot" && array[1] == "log" && !flag)
            {
                result = array[1];
            }
        }
        if (target.IsEquipmentOrRangedOrAmmo)
        {
            result = target.material.thing;
        }
        return result;
    }
References Card.HasElement(), Card.IsEquipmentOrRangedOrAmmo, Card.material, Thing.source, and BaseTaskHarvest.target.
Referenced by HarvestThing(), and HaveHarvestThing().
GetTextSmall()
override string TaskHarvest.GetTextSmall (Card c) inline virtual
Reimplemented from BaseTaskHarvest.
Definition at line 113 of file TaskHarvest.cs.
    {
        if (IsObj)
        {
            return base.GetTextSmall(c);
        }
        if (target == null)
        {
            return "";
        }
        return target.Name;
    }
References IsObj, Card.Name, and BaseTaskHarvest.target.
HarvestThing()
void TaskHarvest.HarvestThing () inline
Definition at line 547 of file TaskHarvest.cs.
    {
        string text = GetIdDismantled();
        float num = target.Num;
        float num2 = 1.0999999f;
        if (target.trait.CraftNum > 1)
        {
            num2 = (float)target.trait.CraftNum * 1.35f;
        }
        switch (text)
        {
        case "log":
        case "rock":
            num2 = 2.1999998f;
            break;
        case "fish_slice":
            num2 = 4.4f;
            break;
        }
        string text2 = target.id;
        if (text2 == "glass" || text2 == "brick")
        {
            num2 = 2.1999998f;
        }
        float num3 = num % num2;
        num /= num2;
        Debug.Log("num:" + num + " div:" + num3 + " chance:" + num2 + " check:" + (num2 - num3 + 1f));
        if (num3 > 0f && EClass.rndf(num2 - num3 + 1f) < 1f)
        {
            num += 1f;
        }
        if (target.sockets != null)
        {
            target.EjectSockets();
        }
        int decay = target.decay;
        int lV = target.LV;
        target.Die(null, EClass.pc);
        if ((int)num <= 0 || !ShouldGenerateDismantled(text))
        {
            return;
        }
        if (target.isCopy || target.HasElement(764))
        {
            text = "ash3";
        }
        CardBlueprint.Set(new CardBlueprint
        {
            fixedQuality = true
        });
        Thing thing = ThingGen.Create(text, 1, Mathf.Max(1, lV * 2 / 3));
        if (thing == null)
        {
            return;
        }
        if (EClass._zone.IsUserZone && target.isNPCProperty && (thing.trait is TraitPotionLove || thing.HasTag(CTAG.rareResource)))
        {
            Msg.Say("spellbookCrumble", thing);
            thing.Destroy();
            return;
        }
        thing.SetNum((int)num);
        thing.ChangeMaterial(target.material);
        thing.decay = decay;
        if (thing.IsDecayed && thing.IsFood)
        {
            thing.elements.SetBase(73, -10);
        }
        EClass._map.TrySmoothPick(pos.IsBlocked ? owner.pos : pos, thing, EClass.pc);
    }
References EClass._map, EClass._zone, Card.ChangeMaterial(), Trait.CraftNum, ThingGen.Create(), Debug, Card.decay, Card.Destroy(), Card.Die(), Card.EjectSockets(), Card.elements, GetIdDismantled(), Card.HasElement(), Card.HasTag(), Card.id, Point.IsBlocked, Card.isCopy, Card.IsDecayed, Card.IsFood, Card.isNPCProperty, Zone.IsUserZone, Card.LV, Card.material, Card.Num, AIAct.owner, EClass.pc, Card.pos, TaskPoint.pos, EClass.rndf(), Msg.Say(), CardBlueprint.Set(), ElementContainer.SetBase(), Card.SetNum(), ShouldGenerateDismantled(), Card.sockets, BaseTaskHarvest.target, Card.trait, and Map.TrySmoothPick().
Referenced by OnCreateProgress().
HaveHarvestThing()
bool TaskHarvest.HaveHarvestThing () inline
Definition at line 541 of file TaskHarvest.cs.
    {
        string idDismantled = GetIdDismantled();
        return ShouldGenerateDismantled(idDismantled);
    }
References GetIdDismantled(), and ShouldGenerateDismantled().
Referenced by GetBaseText().
OnCreateProgress()
override void TaskHarvest.OnCreateProgress (Progress_Custom p) inline virtual
Reimplemented from AIAct.
Definition at line 259 of file TaskHarvest.cs.
    {
        SetTarget(owner);
        string i = (IsObj ? pos.cell.GetObjName() : target.Name);
        SourceMaterial.Row mat = (IsObj ? pos.cell.matObj : target.material);
        GrowSystem growth = pos.growth;
        float num = (base.IsHarvest ? 0.5f : ((!IsObj) ? 1f : ((growth != null) ? growth.MtpProgress : 1f)));
        int exp = 50;
        wasReapSeed = IsReapSeed;
        wasCrime = IsHostileAct;
        p.textHint = i;
        p.maxProgress = (int)((float)(maxProgress * 150) * num / 100f);
        p.interval = 1;
        p.onProgressBegin = delegate
        {
            if (TryGetAct(owner, pos) == null)
            {
                p.Cancel();
            }
            else if (base.IsTooHard)
            {
                owner.Say((mode == HarvestType.Disassemble) ? "tooHardToDisassemble" : "tooHardToHarvest", owner, i);
                p.Cancel();
            }
            else if (mode == HarvestType.Disassemble)
            {
                owner.Say("disassemble_start", owner, owner.Tool, i);
            }
            else if (owner.Tool == null)
            {
                owner.Say("harvestHand_start", owner, i);
            }
            else
            {
                owner.Say("harvest_start", owner, owner.Tool, i);
            }
        };
        p.onProgress = delegate(Progress_Custom _p)
        {
            owner.LookAt(pos);
            owner.renderer.NextFrame();
            if (_p.progress % 2 == 0)
            {
                if (IsObj)
                {
                    if (base.IsHarvest && growth != null)
                    {
                        owner.PlaySound(growth.GetSoundProgress());
                        if (growth.AnimeProgress != 0)
{
                            pos.Animate(growth.AnimeProgress);
                        }
                        return;
                    }
                    pos.Animate(AnimeID.HitObj);
                }
                else
                {
                    target.PlayAnime(AnimeID.HitObj);
                }
                pos.PlaySound(mat.GetSoundImpact());
                mat.PlayHitEffect(pos);
                mat.AddBlood(pos);
                effectFrame += maxProgress / 4 + 1;
                if (EClass._zone.IsCrime(owner, this))
                {
                    owner.pos.TryWitnessCrime(owner);
                }
            }
        };
        p.onProgressComplete = delegate
        {
            string idRecipe = (IsObj ? pos.sourceObj.RecipeID : ((target != null) ? target.source.RecipeID : ""));
            SourceBacker.Row backerObj = EClass._map.GetBackerObj(pos);
            int num2 = ((EClass.rnd(3) != 0) ? 1 : 0);
            if (IsObj)
            {
                SourceObj.Row sourceObj = pos.sourceObj;
                bool flag = false;
                if (difficulty >= 0 && EClass.rnd(6) == 0)
                {
                    flag = true;
                }
                if (difficulty >= 2 && EClass.rnd(3) == 0)
                {
                    flag = true;
                }
                if (flag && growth != null)
                {
                    growth.OnHitFail(owner);
                }
                if (EClass._zone is Zone_Harvest && !base.IsHarvest && pos.IsFarmField)
                {
                    EClass._map.DestroyObj(pos);
                    pos.SetObj();
                }
                else
                {
                    if (base.IsHarvest && !IsReapSeed)
                    {
                        if (pos.growth.CanHarvest())
{
                            harvestingCrop = true;
                        }
                        pos.growth.Harvest(owner);
                    }
                    else if (growth != null && !IsReapSeed)
                    {
                        growth.OnProgressComplete(owner);
                    }
                    else
                    {
                        EClass._map.MineObj(pos, this);
                    }
                    if (sourceObj.alias == "mound")
                    {
                        if (EClass.rnd(7) == 0)
{
                            EClass._zone.AddThing("plat", pos);
                        }
                        else if (EClass.rnd(3) == 0)
{
                            EClass._zone.AddCard(ThingGen.CreateFromCategory("junk"), pos);
                        }
                        else
{
                            EClass._zone.AddThing("bone", pos);
                        }
                    }
                }
            }
            else
            {
                exp = target.Num * 5;
                num2 = target.Num / 3 + EClass.rnd(target.Num / 3 + 2);
                if (!EClass._zone.IsUserZone || !EClass.game.principal.disableUsermapBenefit || !target.isNPCProperty)
                {
                    HarvestThing();
                }
            }
            if (EClass._zone.IsCrime(owner, this) && EClass.rnd(3) != 0)
            {
                EClass.player.ModKarma(-1);
            }
            if (backerObj != null)
            {
                if (backerObj != null && !backerObj.loot.IsEmpty() && !EClass.player.doneBackers.Contains(backerObj.id))
                {
                    if (EClass.sources.cards.map.ContainsKey(backerObj.loot))
                    {
                        Thing thing = ThingGen.Create(backerObj.loot);
                        switch (backerObj.id)
{
                        case 490:
                        case 867:
                        case 5160:
                            thing.c_charges = 0;
                            thing.c_priceFix = -100;
                            break;
                        case 2531:
                            thing.MakeFoodFrom("cloud_electric");
                            break;
                        case 1027:
                            thing.ChangeMaterial(25);
                            thing.SetBlessedState(BlessedState.Doomed);
                            thing.ChangeRarity(Rarity.Legendary);
                            break;
                        case 4565:
                            EClass._zone.AddThing("rod", pos);
                            EClass._zone.AddThing("money", pos).SetNum(121);
                            break;
                        case 5367:
                            thing.Dye("obsidian");
                            break;
                        case 471:
                        case 1828:
                        case 5765:
                            thing.SetBlessedState(BlessedState.Cursed);
                            break;
                        case 5529:
                            thing.ChangeMaterial(25);
                            break;
                        case 1854:
                            thing.decay = 10000;
                            break;
                        case 4788:
                            thing.SetEncLv(1);
                            break;
                        case 4615:
                            thing.ChangeMaterial("meat");
                            break;
                        }
                        EClass._zone.AddCard(thing, pos);
                    }
                    else
                    {
                        Debug.LogError("exception: Backer Loot not valid:" + backerObj.id + "/" + backerObj.loot);
                    }
                    Debug.Log(backerObj.id + "/" + backerObj.Name + "/" + backerObj.loot);
                }
                EClass.player.doneBackers.Add(backerObj.id);
                if (!backerObj.Text.IsEmpty() && EClass.core.config.backer.Show(backerObj))
                {
                    bool num3 = backerObj.type == 1;
                    Msg.Say(num3 ? "backerRemain_read" : "backerTree_read");
                    Msg.Say(num3 ? "backerRemain" : "backerTree", backerObj.Text);
                }
            }
            if (owner.IsPC)
            {
                EClass.pc.CalculateFOV();
            }
            owner.elements.ModExp(idEle, exp);
            if (wasReapSeed)
            {
                owner.ModExp(286, 20);
            }
            owner.stamina.Mod(-num2);
            if (owner != null && owner.IsPC)
            {
                EClass.player.recipes.ComeUpWithRecipe(idRecipe, 30);
            }
        };
    }
References EClass._map, EClass._zone, SourceMaterial.Row.AddBlood(), Zone.AddCard(), Zone.AddThing(), TileRow.alias, Point.Animate(), GrowSystem.AnimeProgress, CoreConfig.backer, Card.CalculateFOV(), AIAct.Cancel(), GrowSystem.CanHarvest(), SourceManager.cards, Point.cell, Card.ChangeMaterial(), Card.ChangeRarity(), RecipeManager.ComeUpWithRecipe(), Core.config, EClass.core, ThingGen.Create(), ThingGen.CreateFromCategory(), Debug, Map.DestroyObj(), BaseTaskHarvest.difficulty, GamePrincipal.disableUsermapBenefit, Player.doneBackers, Card.Dye(), BaseTaskHarvest.effectFrame, Card.elements, EClass.game, Map.GetBackerObj(), Cell.GetObjName(), SourceMaterial.Row.GetSoundImpact(), GrowSystem.GetSoundProgress(), Point.growth, GrowSystem.Harvest(), harvestingCrop, HarvestThing(), SourceBacker.Row.id, BaseTaskHarvest.idEle, Zone.IsCrime(), Point.IsFarmField, IsHostileAct, Card.isNPCProperty, IsObj, Chara.IsPC, IsReapSeed, Zone.IsUserZone, Chara.LookAt(), SourceBacker.Row.loot, Card.MakeFoodFrom(), SourceCard.map, Card.material, BaseTaskHarvest.maxProgress, Map.MineObj(), Stats.Mod(), mode, ElementContainer.ModExp(), Card.ModExp(), Player.ModKarma(), Card.Name, SourceBacker.Row.Name, CardRenderer.NextFrame(), Card.Num, GrowSystem.OnHitFail(), GrowSystem.OnProgressComplete(), AIAct.owner, EClass.pc, Card.PlayAnime(), EClass.player, SourceMaterial.Row.PlayHitEffect(), Point.PlaySound(), Card.PlaySound(), Card.pos, TaskPoint.pos, Game.principal, AIProgress.progress, Player.recipes, Card.renderer, EClass.rnd(), Msg.Say(), Card.Say(), Card.SetBlessedState(), Card.SetEncLv(), Card.SetNum(), Point.SetObj(), BaseTaskHarvest.SetTarget(), CoreConfig.BackerContentConfig.Show(), Thing.source, Point.sourceObj, EClass.sources, Chara.stamina, BaseTaskHarvest.target, SourceBacker.Row.Text, Card.Tool, TryGetAct(), Point.TryWitnessCrime(), wasCrime, and wasReapSeed.
ShouldGenerateDismantled()
bool TaskHarvest.ShouldGenerateDismantled (string dest) inline
Definition at line 512 of file TaskHarvest.cs.
    {
        if (target.trait is TraitFakeBlock)
        {
            return false;
        }
        if (target.trait is TraitGrave)
        {
            return false;
        }
        if (target.trait is TraitFoodFishSlice)
        {
            return false;
        }
        if (dest.Contains("$") || dest.Contains("#") || dest.Contains("@") || dest.Contains("-"))
        {
            return false;
        }
        if (dest == target.id || !EClass.sources.cards.map.ContainsKey(dest))
        {
            return false;
        }
        if (target.source.components.IsEmpty())
        {
            return false;
        }
        return true;
    }
References SourceManager.cards, Card.id, SourceCard.map, Thing.source, EClass.sources, BaseTaskHarvest.target, and Card.trait.
Referenced by HarvestThing(), and HaveHarvestThing().
TryGetAct()
static TaskHarvest TaskHarvest.TryGetAct (Chara c, Point p) inline static
Definition at line 126 of file TaskHarvest.cs.
    {
        Thing t = c.Tool;
        bool hasTool = t != null && (t.HasElement(225) || t.HasElement(220));
        bool hasDiggingTool = t != null && t.HasElement(230);
        if (t != null)
        {
            if (t.trait is TraitToolBrush)
            {
                return null;
            }
            if (t.trait is TraitToolShears)
            {
                return null;
            }
            if (t.trait is TraitToolWaterCan)
            {
                return null;
            }
            if (t.trait is TraitToolMusic)
            {
                return null;
            }
            if (t.trait is TraitToolSickle && !p.cell.CanReapSeed())
            {
                return null;
            }
        }
        if (p.HasObj && IsValidTarget(p.sourceObj.reqHarvest))
        {
            return new TaskHarvest
            {
                pos = p.Copy()
            };
        }
        if (p.HasThing)
        {
            for (int num = p.Things.Count - 1; num >= 0; num--)
            {
                t = p.Things[num];
                if (t.trait.ReqHarvest != null && IsValidTarget(t.trait.ReqHarvest.Split(',')))
                {
                    return new TaskHarvest
                    {
                        pos = p.Copy(),
                        mode = HarvestType.Thing,
                        target = t
                    };
                }
            }
            for (int num2 = p.Things.Count - 1; num2 >= 0; num2--)
            {
                t = p.Things[num2];
                if (!t.isHidden && !t.isMasked && t.trait.CanBeDisassembled && c.Tool?.trait is TraitToolHammer)
                {
                    return new TaskHarvest
                    {
                        pos = p.Copy(),
                        mode = HarvestType.Disassemble,
                        target = t
                    };
                }
            }
        }
        return null;
        bool IsValidTarget(string[] raw)
        {
            if (raw[0] == "digging")
            {
                return hasDiggingTool;
            }
            bool num3 = p.cell.CanHarvest();
            int num4 = (num3 ? 250 : EClass.sources.elements.alias[raw[0]].id);
            bool flag = ((!num3 && num4 != 250) ? true : false);
            if (!flag && t != null && !t.trait.CanHarvest)
            {
                return false;
            }
            return !flag || hasTool;
        }
    }
References Trait.CanBeDisassembled, Cell.CanHarvest(), Trait.CanHarvest, Cell.CanReapSeed(), Point.cell, Point.Copy(), SourceManager.elements, Card.HasElement(), Point.HasObj, Point.HasThing, Card.isHidden, Card.isMasked, mode, TaskPoint.pos, Trait.ReqHarvest, Point.sourceObj, EClass.sources, BaseTaskHarvest.target, Point.Things, Card.Tool, and Card.trait.
Referenced by OnCreateProgress(), and HotItemHeld.TrySetToolAct().
Member Data Documentation
harvestingCrop
bool TaskHarvest.harvestingCrop
Definition at line 9 of file TaskHarvest.cs.
Referenced by GetHitResult(), and OnCreateProgress().
mode
HarvestType TaskHarvest.mode = HarvestType.Obj
Definition at line 11 of file TaskHarvest.cs.
Referenced by GetBaseText(), OnCreateProgress(), and TryGetAct().
wasCrime
bool TaskHarvest.wasCrime
Definition at line 7 of file TaskHarvest.cs.
Referenced by OnCreateProgress().
wasReapSeed
bool TaskHarvest.wasReapSeed
Definition at line 5 of file TaskHarvest.cs.
Referenced by OnCreateProgress().
Property Documentation
destDist
override int TaskHarvest.destDist get
Definition at line 35 of file TaskHarvest.cs.
harvestType
override HarvestType TaskHarvest.harvestType get
Definition at line 31 of file TaskHarvest.cs.
IsGrowth
override bool TaskHarvest.IsGrowth get
Definition at line 37 of file TaskHarvest.cs.
IsHostileAct
override bool TaskHarvest.IsHostileAct get
Definition at line 39 of file TaskHarvest.cs.
    {
        get
        {
            if (!wasCrime)
            {
                if (mode == HarvestType.Disassemble)
                {
                    Thing thing = target;
                    if (thing != null && thing.isNPCProperty)
                    {
                        goto IL_007b;
                    }
                }
                if (mode == HarvestType.Obj)
                {
                    if (!pos.sourceObj.ContainsTag("crime"))
                    {
                        if (pos.growth != null && pos.growth.IsCrimeToHarvest)
{
                            return !(EClass._zone is Zone_Harvest);
                        }
                        return false;
                    }
                    return true;
                }
                return false;
            }
            goto IL_007b;
            IL_007b:
            return true;
        }
    }
Referenced by OnCreateProgress().
IsObj
bool TaskHarvest.IsObj get
Definition at line 13 of file TaskHarvest.cs.
Referenced by CanProgress(), GetBaseText(), GetHitResult(), GetTextSmall(), and OnCreateProgress().
IsReapSeed
bool TaskHarvest.IsReapSeed get
Definition at line 15 of file TaskHarvest.cs.
    {
        get
        {
            if (IsObj && CanReapSeed && owner.Tool != null)
            {
                if (!(owner.Tool.trait is TraitToolSickle))
                {
                    return owner.Tool.category.IsChildOf("scythe");
                }
                return true;
            }
            return false;
        }
    }
Referenced by GetBaseText(), and OnCreateProgress().
Loop
override bool TaskHarvest.Loop get
Definition at line 73 of file TaskHarvest.cs.
    {
        get
        {
            if (EClass.game.IsSurvival && EClass._zone is Zone_StartSite)
            {
                return CanProgress();
            }
            return false;
        }
    }
RightHand
override int TaskHarvest.RightHand get
Definition at line 33 of file TaskHarvest.cs.
The documentation for this class was generated from the following file:
Elin/TaskHarvest.cs