Elin Decompiled Documentation: UIDropdown Class Reference
UIDropdown Class Reference
Public Member Functions
override void OnCancel (BaseEventData eventData)
void SetList< TValue > (string name, IList< TValue > list, Func< TValue, int, string > getName, Action< int, TValue > onChange, bool notify=true)
void SetList< TValue > (int _index, IList< TValue > list, Func< TValue, int, string > getName, Action< int, TValue > onChange, bool notify=true)
void Next ()
void Prev ()
Public Attributes
UIButton bl
Static Public Attributes
static UIDropdown activeInstance
Protected Member Functions
override void OnEnable ()
override GameObject CreateBlocker (Canvas rootCanvas)
override void DestroyBlocker (GameObject blocker)
Private Member Functions
void Update ()
Detailed Description
Definition at line 7 of file UIDropdown.cs.
Member Function Documentation
CreateBlocker()
override GameObject UIDropdown.CreateBlocker (Canvas rootCanvas) inline protected
Definition at line 32 of file UIDropdown.cs.
    {
        activeInstance = this;
        return base.CreateBlocker(rootCanvas);
    }
References activeInstance, and CreateBlocker().
Referenced by CreateBlocker().
DestroyBlocker()
override void UIDropdown.DestroyBlocker (GameObject blocker) inline protected
Definition at line 38 of file UIDropdown.cs.
    {
        activeInstance = null;
        if ((bool)bl)
        {
            UnityEngine.Object.Destroy(bl.gameObject);
            bl = null;
        }
        base.DestroyBlocker(blocker);
    }
References activeInstance, and bl.
Next()
void UIDropdown.Next () inline
Definition at line 89 of file UIDropdown.cs.
    {
        if (base.value < base.options.Count - 1)
        {
            base.value++;
        }
    }
Referenced by Scene.OnUpdate().
OnCancel()
override void UIDropdown.OnCancel (BaseEventData eventData) inline
Definition at line 14 of file UIDropdown.cs.
    {
    }
OnEnable()
override void UIDropdown.OnEnable () inline protected
Definition at line 26 of file UIDropdown.cs.
    {
        base.OnEnable();
        base.template.GetComponentInChildren<ScrollRect>().scrollSensitivity = UIScrollView.sensitivity;
    }
References UIScrollView.sensitivity.
Prev()
void UIDropdown.Prev () inline
Definition at line 97 of file UIDropdown.cs.
    {
        if (base.value > 0)
        {
            base.value--;
        }
    }
Referenced by Scene.OnUpdate().
SetList< TValue >() [1/2]
void UIDropdown.SetList< TValue > (int _index, IList< TValue > list, Func< TValue, int, string > getName, Action< int, TValue > onChange, bool notify = true) inline
Definition at line 63 of file UIDropdown.cs.
    {
        base.options.Clear();
        for (int i = 0; i < list.Count; i++)
        {
            base.options.Add(new OptionData
            {
                text = getName(list[i], i)
            });
        }
        base.onValueChanged.RemoveAllListeners();
        base.onValueChanged.AddListener(delegate(int a)
        {
            onChange(a, list[a]);
        });
        if (notify)
        {
            base.value = _index;
        }
        else
        {
            SetValueWithoutNotify(_index);
        }
        RefreshShownValue();
    }
SetList< TValue >() [2/2]
void UIDropdown.SetList< TValue > (string name, IList< TValue > list, Func< TValue, int, string > getName, Action< int, TValue > onChange, bool notify = true) inline
Definition at line 49 of file UIDropdown.cs.
    {
        int index = 0;
        for (int i = 0; i < list.Count; i++)
        {
            if (getName(list[i], i) == name)
            {
                index = i;
                break;
            }
        }
        SetList(index, list, getName, onChange, notify);
    }
Update()
void UIDropdown.Update () inline private
Definition at line 18 of file UIDropdown.cs.
    {
        if (activeInstance == this && Input.GetMouseButtonDown(1))
        {
            Hide();
        }
    }
References activeInstance.
Member Data Documentation
activeInstance
UIDropdown UIDropdown.activeInstance static
Definition at line 12 of file UIDropdown.cs.
Referenced by CreateBlocker(), DestroyBlocker(), Scene.OnUpdate(), Update(), and Layer.UpdateInput().
bl
UIButton UIDropdown.bl
Definition at line 10 of file UIDropdown.cs.
Referenced by DestroyBlocker().
The documentation for this class was generated from the following file:
Elin/Plugins.UI/UIDropdown.cs