Elin Decompiled Documentation: StatsMana Class Reference
StatsMana Class Reference
Public Member Functions
override void Mod (int a)
Public Member Functions inherited from Stats
override int GetValue ()
override string ToString ()
override string GetText ()
override Color GetColor (Gradient g)
Stats Set (int[] _raw, int _rawIndex, Chara _CC)
override int GetPhase ()
virtual void Set (int a)
virtual void Mod (int a)
virtual void OnChangePhase (int phase, int lastPhase)
Public Member Functions inherited from BaseStats
virtual Color GetColor (Gradient gradient)
virtual Color GetColor (SkinColorProfile c)
Color GetColor ()
virtual string GetText ()
virtual string GetPhaseStr ()
virtual int GetValue ()
virtual Sprite GetSprite ()
virtual void SetText (UIText t, SkinColorProfile cols=null)
virtual int GetPhase ()
void PopText ()
virtual void WriteNote (UINote n, Action< UINote > onWriteNote=null)
virtual void _WriteNote (UINote n, bool asChild=false)
Properties
override int max [get]
override int min [get]
Properties inherited from Stats
virtual int value [get, set]
virtual int max [get, set]
string name [get]
virtual bool TrackPhaseChange [get]
virtual int min [get]
Properties inherited from BaseStats
SourceStat.Row source [get]
virtual Emo2 EmoIcon [get]
virtual ConditionType Type [get]
virtual string idSprite [get]
virtual bool ShowInWidget [get]
virtual Chara Owner [get]
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Additional Inherited Members
Static Public Member Functions inherited from EClass
static int rndSeed (int a, int seed)
static int rnd (int a)
static int curve (int a, int start, int step, int rate=75)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Public Attributes inherited from Stats
int rawIndex
int[] raw
Public Attributes inherited from BaseStats
int id
SourceStat.Row _source
Static Public Attributes inherited from Stats
static StatsHunger Hunger
static StatsBurden Burden
static StatsStamina Stamina
static StatsSleepiness Sleepiness
static Stats Depression
static Stats Bladder
static StatsHygiene Hygiene
static StatsMana Mana
static StatsSAN SAN
Static Public Attributes inherited from BaseStats
static Chara CC
Static Public Attributes inherited from EClass
static Core core
Detailed Description
Definition at line 3 of file StatsMana.cs.
Member Function Documentation
Mod()
override void StatsMana.Mod (int a) inline virtual
Reimplemented from Stats.
Definition at line 9 of file StatsMana.cs.
    {
        if (BaseStats.CC.IsPC && EClass.debug.godMode && a < 0)
        {
            return;
        }
        if (a < 0 && BaseStats.CC.HasElement(1330))
        {
            if (a == -1 && EClass.rnd(4) == 0)
            {
                return;
            }
            a = -EClass.rnd(-a * 130 / 100 + 2);
        }
        base.Mod(a);
        if (a >= 0)
        {
            return;
        }
        if (!BaseStats.CC.IsPCFaction)
        {
            a /= 10;
        }
        _ = BaseStats.CC.ShouldShowMsg;
        if (value >= 0)
        {
            return;
        }
        int num = -value * 400 / (100 + BaseStats.CC.EvalueMax(303, -5) * 10);
        if (BaseStats.CC.HasElement(1201))
        {
            num /= 3;
        }
        if (!BaseStats.CC.IsPC)
        {
            num /= 5;
            if (num < 10)
            {
                return;
            }
        }
        BaseStats.CC.Say("mana_overflow", BaseStats.CC);
        BaseStats.CC.DamageHP(num, 921, 100, AttackSource.ManaBackfire);
        Chara cC = BaseStats.CC;
        if (cC.IsAliveInCurrentZone)
        {
            cC.elements.ModExp(303, Mathf.Clamp(-a * 10, 10, 200));
        }
    }
References BaseStats.CC, Card.DamageHP(), EClass.debug, Card.elements, Card.EvalueMax(), CoreDebug.godMode, Card.HasElement(), Chara.IsAliveInCurrentZone, Chara.IsPC, Chara.IsPCFaction, ElementContainer.ModExp(), EClass.rnd(), Card.Say(), Card.ShouldShowMsg, and Stats.value.
Property Documentation
max
override int StatsMana.max get
Definition at line 5 of file StatsMana.cs.
min
override int StatsMana.min get
Definition at line 7 of file StatsMana.cs.
The documentation for this class was generated from the following file:
Elin/StatsMana.cs