Elin Decompiled Documentation: TimeTable Class Reference
TimeTable Class Reference
Public Types
enum Span { Free , Eat , Work , Sleep }
Public Member Functions
Span GetSpan (int hour)
Static Public Member Functions
static void Init ()
static TimeTable Add (string raw, string id)
static TimeTable GetTimeTable (string id)
static Span GetSpan (string id, int hour)
Static Public Member Functions inherited from EClass
static int rndSeed (int a, int seed)
static int rnd (long a)
static int rnd (int a)
static int curve (int a, int start, int step, int rate=75)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Public Attributes
Span[] spans = new Span[24]
Static Public Attributes
static Dictionary< string, TimeTable > dict = new Dictionary<string, TimeTable>()
Static Public Attributes inherited from EClass
static Core core
Static Private Member Functions
static Span GetSpan (char s)
Static Private Attributes
static bool unityInit
Additional Inherited Members
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Detailed Description
Definition at line 3 of file TimeTable.cs.
Member Enumeration Documentation
Span
enum TimeTable.Span
Enumerator
Free
Eat
Work
Sleep
Definition at line 5 of file TimeTable.cs.
    {
        Free,
        Eat,
        Work,
        Sleep
    }
Member Function Documentation
Add()
static TimeTable TimeTable.Add (string raw, string id) inline static
Definition at line 29 of file TimeTable.cs.
    {
        TimeTable timeTable = new TimeTable();
        for (int i = 0; i < 24; i++)
        {
            timeTable.spans[i] = GetSpan(raw[i]);
        }
        dict.Add(id, timeTable);
        return timeTable;
    }
References dict, GetSpan(), and spans.
Referenced by Init().
GetSpan() [1/3]
static Span TimeTable.GetSpan (char s) inline static private
Definition at line 50 of file TimeTable.cs.
    {
        return s switch
        {
            'z' => Span.Sleep,
            'e' => Span.Eat,
            'w' => Span.Work,
            _ => Span.Free,
        };
    }
GetSpan() [2/3]
Span TimeTable.GetSpan (int hour) inline
Definition at line 61 of file TimeTable.cs.
    {
        return Span.Free;
    }
GetSpan() [3/3]
static Span TimeTable.GetSpan (string id, int hour) inline static
Definition at line 45 of file TimeTable.cs.
    {
        return dict[id].spans[hour];
    }
References dict.
Referenced by Add(), Chara.GetGoalFromTimeTable(), and Chara.TickWork().
GetTimeTable()
static TimeTable TimeTable.GetTimeTable (string id) inline static
Definition at line 40 of file TimeTable.cs.
    {
        return dict[id];
    }
References dict.
Init()
static void TimeTable.Init () inline static
Definition at line 19 of file TimeTable.cs.
    {
        if (!unityInit)
        {
            Add("zzzzzz  ewwwwwwwwwwe    z", "default");
            Add("zzzzzz  ewwwwwwwwwwe    z", "owl");
            unityInit = true;
        }
    }
References Add(), and unityInit.
Referenced by SourceManager.Init().
Member Data Documentation
dict
Dictionary<string, TimeTable> TimeTable.dict = new Dictionary<string, TimeTable>() static
Definition at line 13 of file TimeTable.cs.
Referenced by Add(), GetSpan(), and GetTimeTable().
spans
Span [] TimeTable.spans = new Span[24]
Definition at line 17 of file TimeTable.cs.
Referenced by Add().
unityInit
bool TimeTable.unityInit static private
Definition at line 15 of file TimeTable.cs.
Referenced by Init().
The documentation for this class was generated from the following file:
Elin/TimeTable.cs