Elin Decompiled Documentation: InvOwnerMod Class Reference
InvOwnerMod Class Reference
Public Member Functions
InvOwnerMod (Card owner=null, Card container=null, CurrencyType _currency=CurrencyType.None)
override bool ShouldShowGuide (Thing t)
override void _OnProcess (Thing t)
Public Member Functions inherited from InvOwnerDraglet
override bool AllowHold (Thing t)
InvOwnerDraglet (Card owner=null, Card container=null, CurrencyType _currency=CurrencyType.Money)
override void OnInit ()
override void OnClick (ButtonGrid button)
override void OnRightClick (ButtonGrid button)
override int GetPrice (Thing t, CurrencyType currency, int num, bool sell)
override string GetTextDetail (Thing t, CurrencyType currency, int num, bool sell)
virtual void OnWriteNote (Thing t, UINote n)
sealed override void OnProcess (Thing t)
virtual void _OnProcess (Thing t)
virtual void OnAfterRefuel ()
void RedrawButton ()
override void BuildUICurrency (UICurrency uiCurrency, bool canReroll=false)
Public Member Functions inherited from InvOwner
virtual bool AllowHold (Thing t)
virtual bool AllowMoved (Thing t)
virtual bool ShouldShowGuide (Thing t)
virtual bool AllowDrop (Thing t)
virtual Thing CreateDefaultContainer ()
virtual void BuildUICurrency (UICurrency uiCurrency, bool canReroll=false)
bool IsWeightOver (Thing t)
InvOwner (Card owner, Card container=null, CurrencyType _currency=CurrencyType.None, PriceType _price=PriceType.Default)
void Init ()
virtual void OnInit ()
virtual void OnClick (ButtonGrid button)
virtual void OnRightClick (ButtonGrid button)
virtual void OnRightPressed (ButtonGrid button)
InvOwner GetShitDestOwner (ButtonGrid b, bool rightMouse=false)
virtual void OnShiftClick (ButtonGrid b, bool rightMouse=false)
virtual bool CanShiftClick (ButtonGrid b, bool rightMouse=false)
virtual string GetTextShiftClick (ButtonGrid b)
virtual void OnCtrlClick (ButtonGrid button)
virtual bool CanCtrlClick (ButtonGrid b)
virtual string GetTextCtrlClick (ButtonGrid b)
virtual void OnAltClick (ButtonGrid button)
virtual bool CanAltClick (ButtonGrid b)
virtual string GetTextAltClick (ButtonGrid b)
void Grab (DragItemCard.DragInfo from)
Thing PutBack (DragItemCard.DragInfo from)
void OnStartDrag (DragItemCard.DragInfo from)
virtual bool OnCancelDrag (DragItemCard.DragInfo from)
virtual bool OnDrag (DragItemCard.DragInfo from, DragItemCard.DragInfo to, bool execute, bool cancel=false)
virtual void OnProcess (Thing t)
bool CanOpenContainer (Thing t)
ListInteraction ListInteractions (ButtonGrid b, bool context)
bool TryHold (Thing t)
virtual void ListInteractions (ListInteraction list, Thing t, Trait trait, ButtonGrid b, bool context)
virtual string GetAutoUseLang (ButtonGrid button)
void AutoUse (ButtonGrid button, bool repeat=false)
void ShowContextMenu (ButtonGrid button)
virtual int GetPrice (Thing t, CurrencyType currency, int num, bool sell)
virtual string GetTextDetail (Thing t, CurrencyType currency, int num, bool sell)
virtual void OnWriteNote (ButtonGrid button, UINote n)
virtual string IDCostIcon (Thing t)
virtual bool IsFailByCurse (Thing t)
Static Public Member Functions
static bool IsValidRangedMod (Thing t, SourceElement.Row row)
Static Public Member Functions inherited from EClass
static int rndSeed (int a, int seed)
static int rnd (long a)
static int rnd (int a)
static int curve (int a, int start, int step, int rate=75)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Properties
override bool CanTargetAlly [get]
override ProcessType processType [get]
override string langTransfer [get]
Properties inherited from InvOwnerDraglet
virtual ProcessType processType [get]
virtual bool ShowFuel [get]
virtual bool CanTargetAlly [get]
virtual string langWhat [get]
virtual bool AllowStockIngredients [get]
override bool AllowTransfer [get]
override bool AllowAutouse [get]
override bool AllowContext [get]
override bool UseGuide [get]
override bool CopyOnTransfer [get]
override bool InvertSell [get]
override bool DenyImportant [get]
LayerDragGrid dragGrid [get]
Properties inherited from InvOwner
static bool HasTrader [get]
static bool FreeTransfer [get]
virtual bool AllowAutouse [get]
virtual bool AllowContext [get]
virtual bool AllowSell [get]
virtual bool AlwaysShowTooltip [get]
virtual bool UseGuide [get]
virtual bool AllowTransfer [get]
virtual bool AllowDropOnDrag [get]
virtual string langTransfer [get]
virtual int destInvY [get]
virtual bool HasTransaction [get]
virtual bool CopyOnTransfer [get]
virtual bool SingleTarget [get]
bool UseHomeResource [get]
bool IsMagicChest [get]
List< Thing > Things [get]
Chara Chara [get]
ContainerType ContainerType [get]
virtual bool InvertSell [get]
virtual int numDragGrid [get]
virtual bool ShowNew [get]
virtual bool DenyImportant [get]
InvOwner destInvOwner [get]
string IDCurrency [get]
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Additional Inherited Members
Public Types inherited from InvOwnerDraglet
enum ProcessType { None , Consume }
Public Attributes inherited from InvOwnerDraglet
int count = -1
BlessedState state
int price
Public Attributes inherited from InvOwner
bool includeChildren
CurrencyType currency
PriceType priceType
HomeResource homeResource
Card owner
Card Container
List< ButtonGrid > buttons = new List<ButtonGrid>()
Static Public Attributes inherited from InvOwner
static ForceGiveData forceGive = new ForceGiveData()
static InvOwner Trader
static InvOwner Main
static float clickTimer
Static Public Attributes inherited from EClass
static Core core
Detailed Description
Definition at line 1 of file InvOwnerMod.cs.
Constructor & Destructor Documentation
InvOwnerMod()
InvOwnerMod.InvOwnerMod (Card owner = null, Card container = null, CurrencyType _currency = CurrencyType::None) inline
Definition at line 22 of file InvOwnerMod.cs.
        : base(owner, container, _currency)
    {
        count = 1;
    }
References InvOwnerDraglet.count.
Member Function Documentation
_OnProcess()
override void InvOwnerMod._OnProcess (Thing t) inline virtual
Reimplemented from InvOwnerDraglet.
Definition at line 56 of file InvOwnerMod.cs.
    {
        Msg.Say("modded", t, owner);
        if (owner.trait is TraitRune)
        {
            SE.Play("intonation");
            EClass.pc.PlayEffect("intonation");
            t.AddRune(owner);
            owner.ModNum(-1);
        }
        else
        {
            SE.Play("reloaded");
            EClass.pc.PlayEffect("identify");
            t.ApplySocket(owner.Thing);
        }
    }
References Card.AddRune(), Card.ApplySocket(), Card.ModNum(), InvOwner.owner, EClass.pc, Card.PlayEffect(), Msg.Say(), Card.Thing, and Card.trait.
IsValidRangedMod()
static bool InvOwnerMod.IsValidRangedMod (Thing t, SourceElement::Row row) inline static
Definition at line 9 of file InvOwnerMod.cs.
    {
        if (t.trait is TraitToolRangeCane && !row.tag.Contains("modCane"))
        {
            return false;
        }
        if ((t.trait is TraitToolRangeBow || t.trait is TraitToolRangeCrossbow) && row.id == 601)
        {
            return false;
        }
        return true;
    }
References Trait.Contains(), and Card.trait.
Referenced by Thing.OnCreate(), and ShouldShowGuide().
ShouldShowGuide()
override bool InvOwnerMod.ShouldShowGuide (Thing t) inline virtual
Reimplemented from InvOwner.
Definition at line 28 of file InvOwnerMod.cs.
    {
        TraitMod traitMod = owner.trait as TraitMod;
        if (traitMod is TraitRune)
        {
            if (!t.CanAddRune(traitMod))
            {
                return false;
            }
            return true;
        }
        if (!IsValidRangedMod(t, traitMod.source))
        {
            return false;
        }
        if (t.sockets != null)
        {
            foreach (int socket in t.sockets)
            {
                if (socket == 0)
                {
                    return true;
                }
            }
        }
        return false;
    }
References Card.CanAddRune(), IsValidRangedMod(), Card.sockets, and TraitMod.source.
Property Documentation
CanTargetAlly
override bool InvOwnerMod.CanTargetAlly get
Definition at line 3 of file InvOwnerMod.cs.
langTransfer
override string InvOwnerMod.langTransfer get
Definition at line 7 of file InvOwnerMod.cs.
processType
override ProcessType InvOwnerMod.processType get
Definition at line 5 of file InvOwnerMod.cs.
The documentation for this class was generated from the following file:
Elin/InvOwnerMod.cs