Elin Decompiled Documentation: LogicalPointManager Class Reference
LogicalPointManager Class Reference
Public Member Functions
virtual LogicalPoint Create ()
LogicalPoint GetOrCreate (Point point)
LogicalPoint Refresh (Point point)
void Remove (int key)
Public Attributes
List< LogicalPoint > list = new List<LogicalPoint>()
Dictionary< int, LogicalPoint > dict = new Dictionary<int, LogicalPoint>()
HashSet< Point > refreshList = new HashSet<Point>()
Properties
virtual bool AllowBlock [get]
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Additional Inherited Members
Static Public Member Functions inherited from EClass
static int rndSeed (int a, int seed)
static int rnd (int a)
static int curve (int a, int start, int step, int rate=75)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Static Public Attributes inherited from EClass
static Core core
Detailed Description
Definition at line 3 of file LogicalPointManager.cs.
Member Function Documentation
Create()
virtual LogicalPoint LogicalPointManager.Create () inline virtual
Reimplemented in CellEffectManager.
Definition at line 13 of file LogicalPointManager.cs.
    {
        return null;
    }
Referenced by GetOrCreate().
GetOrCreate()
LogicalPoint LogicalPointManager.GetOrCreate (Point point) inline
Definition at line 18 of file LogicalPointManager.cs.
    {
        if (!point.IsValid)
        {
            return null;
        }
        int index = point.index;
        LogicalPoint logicalPoint = dict.TryGetValue(index);
        if (logicalPoint == null)
        {
            if (!AllowBlock && point.cell.HasBlock)
            {
                return null;
            }
            logicalPoint = Create();
            logicalPoint.Set(point);
            list.Add(logicalPoint);
            dict.Add(index, logicalPoint);
        }
        return logicalPoint;
    }
References AllowBlock, Point.cell, Create(), dict, Cell.HasBlock, Point.index, Point.IsValid, list, and LogicalPoint.Set().
Referenced by Map.Load(), Map.ModFire(), Refresh(), and LogicalFire.Update().
Refresh()
LogicalPoint LogicalPointManager.Refresh (Point point) inline
Definition at line 40 of file LogicalPointManager.cs.
    {
        return GetOrCreate(point);
    }
References GetOrCreate().
Remove()
void LogicalPointManager.Remove (int key) inline
Definition at line 45 of file LogicalPointManager.cs.
    {
        LogicalPoint item = dict[key];
        list.Remove(item);
        dict.Remove(key);
    }
References dict, item, and list.
Referenced by LogicalPoint.Kill().
Member Data Documentation
dict
Dictionary<int, LogicalPoint> LogicalPointManager.dict = new Dictionary<int, LogicalPoint>()
Definition at line 7 of file LogicalPointManager.cs.
Referenced by GetOrCreate(), and Remove().
list
List<LogicalPoint> LogicalPointManager.list = new List<LogicalPoint>()
Definition at line 5 of file LogicalPointManager.cs.
Referenced by GameUpdater.LogicUpdater.FixedUpdate(), GetOrCreate(), and Remove().
refreshList
HashSet<Point> LogicalPointManager.refreshList = new HashSet<Point>()
Definition at line 9 of file LogicalPointManager.cs.
Referenced by GameUpdater.LogicUpdater.FixedUpdate(), and LogicalFire.Update().
Property Documentation
AllowBlock
virtual bool LogicalPointManager.AllowBlock get
Definition at line 11 of file LogicalPointManager.cs.
Referenced by GetOrCreate().
The documentation for this class was generated from the following file:
Elin/LogicalPointManager.cs