Elin Decompiled Documentation: LayerMapList Class Reference
LayerMapList Class Reference
Public Member Functions
override void OnInit ()
void RefreshList ()
Public Member Functions inherited from ELayer
override void OnBeforeAddLayer ()
void InitInspector ()
sealed override void Init ()
override void OnAfterAddLayer ()
void TryShowHelp ()
void AddLayerToUI (string id)
void TryShowHint (string _langHint=null)
void TalkHomeMemeber (string id)
void TalkMaid (string id)
override void OnRightClick ()
Public Attributes
UIList list
Additional Inherited Members
Static Public Member Functions inherited from ELayer
static int rnd (int a)
Protected Member Functions inherited from ELayer
sealed override void _Close ()
sealed override void Kill ()
Properties inherited from ELayer
static Core core [get]
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static FactionBranch Branch [get]
static Faction Home [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static CoreConfig config [get]
static GameSetting setting [get]
static ColorProfile Colors [get]
static SourceManager sources [get]
static World world [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
bool IsFloat [get]
virtual string IdHelp [get]
Detailed Description
Definition at line 3 of file LayerMapList.cs.
Member Function Documentation
OnInit()
override void LayerMapList.OnInit () inline
Definition at line 5 of file LayerMapList.cs.
    {
        this.RefreshList();
    }
References RefreshList().
RefreshList()
void LayerMapList.RefreshList () inline
Definition at line 10 of file LayerMapList.cs.
    {
        this.list.sortMode = ELayer.player.pref.sortResearch;
        BaseList baseList = this.list;
        UIList.Callback<Zone, ItemGeneral> callback = new UIList.Callback<Zone, ItemGeneral>();
        callback.onInstantiate = delegate(Zone a, ItemGeneral b)
        {
            b.SetMainText(a.Name, null, true);
            b.Build();
        };
        callback.onList = delegate(UIList.SortMode m)
        {
            foreach (Zone zone in ELayer.game.spatials.Zones)
            {
                if (zone.isKnown)
                {
                    this.list.Add(zone);
                }
            }
        };
        baseList.callbacks = callback;
        this.list.List(false);
    }
References ItemGeneral.Build(), ELayer.game, Spatial.isKnown, list, Spatial.Name, ELayer.player, Player.pref, ItemGeneral.SetMainText(), Game.spatials, and SpatialManager.Zones.
Referenced by OnInit().
Member Data Documentation
list
UIList LayerMapList.list
Definition at line 34 of file LayerMapList.cs.
Referenced by RefreshList().
The documentation for this class was generated from the following file:
Elin/LayerMapList.cs