Elin Decompiled Documentation: PartialMap Class Reference
PartialMap Class Reference
Classes
class Result
Public Types
enum ApplyMode { Render , HitTest , Apply , Evaluate }
Public Member Functions
void Rotate ()
void ClearMarkedCells ()
void Apply (Point _point, ApplyMode mode)
int FixWall (Cell c)
void Update ()
void Save (int _x, int _z, int _w, int _h)
void _Load ()
Static Public Member Functions
static PartialMap Apply (string path, Point pos)
static PartialMap Load (string path=null)
static void Delete (string path)
static void ExportDialog (string dir=null)
static void SavePreview (string path, string pathDest)
Static Public Member Functions inherited from EClass
static int rndSeed (int a, int seed)
static int rnd (int a)
static int curve (int a, int start, int step, int rate=75)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Public Attributes
string name
int offsetX
int offsetZ
int w
int h
int dir
int baseHeight
int baseHeightWater
int value
bool allowRotate
bool ignoreBlock
int localOffsetX
int localOffsetZ
int destX
int destZ
string path
bool editMode
bool procedural
float ruinChance
Map map
ZoneExportData exportData
List< Cell > cellsMarked = new List<Cell>()
HashSet< int > validPoints = new HashSet<int>()
Result result = new Result()
Static Public Attributes
static bool relative
Static Public Attributes inherited from EClass
static Core core
Properties
static string PathTemp [get]
bool altDirPosition [get]
string ID [get]
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Detailed Description
Definition at line 8 of file PartialMap.cs.
Member Enumeration Documentation
ApplyMode
enum PartialMap.ApplyMode
Enumerator
Render
HitTest
Apply
Evaluate
Definition at line 10 of file PartialMap.cs.
    {
        Render,
        HitTest,
        Apply,
        Evaluate
    }
Member Function Documentation
_Load()
void PartialMap._Load () inline
Definition at line 474 of file PartialMap.cs.
    {
        map = GameIO.LoadFile<Map>(EClass._zone.pathTemp + "map");
        map.Load(EClass._zone.pathTemp, import: false, this);
        if (map == null)
        {
            Debug.Log("Map is null:" + name + "/" + PathTemp);
            return;
        }
        EClass._map.SetReference();
        baseHeight = 255;
        baseHeightWater = 255;
        for (int i = 0; i < w; i++)
        {
            for (int j = 0; j < h; j++)
            {
                Cell cell = map.cells[i, j];
                if (cell.height < baseHeight)
                {
                    baseHeightWater = cell.height;
                }
                if (cell.height < baseHeight && !cell.IsFloorWater)
                {
                    baseHeight = cell.height;
                }
            }
        }
        if (baseHeight == 255)
        {
            baseHeight = 0;
        }
    }
References EClass._map, EClass._zone, baseHeight, baseHeightWater, Map.cells, Debug, h, Cell.height, Cell.IsFloorWater, Map.Load(), map, name, PathTemp, Zone.pathTemp, Map.SetReference(), and w.
Referenced by Load().
Apply() [1/2]
void PartialMap.Apply (Point _point, ApplyMode mode) inline
Definition at line 112 of file PartialMap.cs.
    {
        byte height = _point.cell.height;
        int num = (_point.cell.IsFloorWater ? baseHeightWater : baseHeight);
        Point point = new Point(_point);
        point.x += localOffsetX;
        point.z += localOffsetZ;
        if (altDirPosition)
        {
            switch (dir)
            {
            case 1:
                point.z += w - 1;
                break;
            case 2:
                point.x += w - 1;
                point.z += h - 1;
                break;
            case 3:
                point.x += h - 1;
                break;
            }
        }
        destX = point.x;
        destZ = point.z;
        Point p = new Point();
        if (mode == ApplyMode.Render)
        {
            ClearMarkedCells();
        }
        if (mode == ApplyMode.Evaluate)
        {
            value = 0;
        }
        int num2 = 0;
        int num3 = 0;
        int minX = point.x;
        int minZ = point.z;
        int maxX = point.x + w;
        int maxZ = point.z + h;
        switch (dir)
        {
        case 1:
            minX = point.x;
            maxX = point.x + h;
            minZ = point.z - w + 1;
            maxZ = point.z + 1;
            break;
        case 2:
            minX = point.x - w + 1;
            maxX = point.x + 1;
            minZ = point.z - h + 1;
            maxZ = point.z + 1;
            break;
        case 3:
            minX = point.x - h + 1;
            maxX = point.x + 1;
            minZ = point.z;
            maxZ = point.z + w;
            break;
        }
        EClass.pc.GetCurrency();
        BiomeProfile.TileGroup interior = EClass._zone.biome.interior;
        BiomeProfile.TileGroup exterior = EClass._zone.biome.exterior;
        this.result.ruined.Clear();
        Cell c1;
        HitResult result;
        for (int i = 0; i < w; i++)
        {
            for (int j = 0; j < h; j++)
            {
                Cell cell = map.cells[i, j];
                p.Set(point.x + num2, point.z + num3);
                if (EClass._map.Contains(p))
                {
                    c1 = EClass._map.cells[p.x, p.z];
                    result = HitResult.Valid;
                    if (c1.isFloating)
                    {
                        result = HitResult.Invalid;
                    }
                    if (result == HitResult.Valid)
                    {
                        validPoints.Add(p.index);
                    }
                    if (mode == ApplyMode.Render)
                    {
                        c1.skipRender = true;
                        cellsMarked.Add(c1);
                        if (result != HitResult.Valid)
{
                            MeshPass guidePass = ActionMode.Copy.GetGuidePass(point);
                            int num4 = (int)result;
                            Vector3 vector = p.Position();
                            guidePass.Add(vector.x, vector.y, vector.z - 0.01f, num4, 0.3f);
                        }
                        else
{
                            Render(cell.sourceFloor, cell.floorDir, 0);
                            Render(cell.sourceBlock, cell.HasWall ? FixWall(cell) : cell.blockDir, 0);
                            Render(cell.sourceObj, cell.objDir, 0);
                            Render(cell.sourceBridge, cell.floorDir, (cell.bridgeHeight != 0) ? (cell.bridgeHeight - cell.height) : 0);
                            foreach (SerializedCards.Data card in exportData.serializedCards.cards)
{
                                Recipe orCreate = Recipe.GetOrCreate(EClass.sources.cards.map[card.id].RecipeID);
                                if (card.x - offsetX == i && card.z - offsetZ == j)
{
                                    if (relative)
{
                                        orCreate?.OnRenderMarker(p, active: true, result, main: true, card.dir, height + cell.height - num);
                                    }
                                    else
{
                                        orCreate?.OnRenderMarker(p, active: true, result, main: true, card.dir, cell.height);
                                    }
                                }
                            }
                            Critter.RebuildCritter(c1);
                        }
                    }
                    if (mode == ApplyMode.Apply && result == HitResult.Valid)
                    {
                        if (Rand.Range(0f, 1f) < ruinChance)
{
                            this.result.ruined.Add(p.index);
                        }
                        else if (cell._floor != 77 || editMode)
{
                            if (cell._block == 149 && !editMode)
{
                                c1._block = (byte)interior.block.id;
                                c1._blockMat = (byte)interior.block.mat;
                            }
                            else if (cell._block == 150 && !editMode)
{
                                c1._block = (byte)exterior.block.id;
                                c1._blockMat = (byte)exterior.block.mat;
                            }
                            else
{
                                c1._block = cell._block;
                                c1._blockMat = cell._blockMat;
                            }
                            if (cell._floor == 2 && !editMode)
{
                                c1._floor = (byte)interior.floor.id;
                                c1._floorMat = (byte)interior.floor.mat;
                            }
                            else if (cell._floor == 3 && !editMode)
{
                                c1._floor = (byte)exterior.floor.id;
                                c1._floorMat = (byte)exterior.floor.mat;
                            }
                            else
{
                                c1._floor = cell._floor;
                                c1._floorMat = cell._floorMat;
                            }
                            c1._roofBlock = cell._roofBlock;
                            c1._roofBlockMat = cell._roofBlockMat;
                            c1.obj = cell.obj;
                            c1.objMat = cell.objMat;
                            c1.objVal = cell.objVal;
                            c1.decal = cell.decal;
                            c1._dirs = cell._dirs;
                            c1._bridge = cell._bridge;
                            c1._bridgeMat = cell._bridgeMat;
                            c1.bridgePillar = cell.bridgePillar;
                            c1.isModified = true;
                            if (c1.HasWall)
{
                                c1.blockDir = FixWall(c1);
                            }
                            if (relative || procedural)
{
                                c1.height = (byte)Mathf.Clamp(height + cell.height - num, 0, 255);
                                c1.bridgeHeight = (byte)Mathf.Clamp((cell.bridgeHeight != 0) ? (c1.height + (cell.bridgeHeight - cell.height)) : 0, 0, 255);
                            }
                            else
{
                                c1.height = cell.height;
                                c1.bridgeHeight = cell.bridgeHeight;
                            }
                        }
                    }
                }
                switch (dir)
                {
                case 0:
                    num3++;
                    if (num3 >= h)
                    {
                        num3 = 0;
                        num2++;
                    }
                    break;
                case 1:
                    num2++;
                    if (num2 >= h)
                    {
                        num2 = 0;
                        num3--;
                    }
                    break;
                case 2:
                    num3--;
                    if (num3 <= -h)
                    {
                        num3 = 0;
                        num2--;
                    }
                    break;
                case 3:
                    num2--;
                    if (num2 <= -h)
                    {
                        num2 = 0;
                        num3++;
                    }
                    break;
                }
            }
        }
        if (mode != ApplyMode.Apply)
        {
            return;
        }
        p.Set(point.x, point.z);
        EClass._map.SetReference();
        EClass._map.things.ForeachReverse(delegate(Thing t)
        {
            if (validPoints.Contains(t.pos.index) && t.pos.x >= minX && t.pos.z >= minZ && t.pos.x < maxX && t.pos.z < maxZ && t.trait.CanBeDestroyed)
            {
                t.Destroy();
            }
        });
        if (exportData != null)
        {
            exportData.serializedCards.Restore(EClass._map, null, addToZone: true, this);
        }
        EClass._map.RefreshAllTiles();
        EClass._map.RefreshAllTiles();
        void Render(TileRow row, int dir, int bridgeHeight)
        {
            if (row.id != 0)
            {
                Recipe orCreate2 = Recipe.GetOrCreate(row.RecipeID);
                if (relative)
                {
                    orCreate2?.OnRenderMarker(p, active: true, result, main: true, dir, c1.height + bridgeHeight);
                }
                else
                {
                    orCreate2?.OnRenderMarker(p, active: true, result, main: true, dir, c1.height + bridgeHeight);
                }
            }
        }
    }
References Cell._block, Cell._blockMat, Cell._bridge, Cell._bridgeMat, Cell._dirs, Cell._floor, Cell._floorMat, EClass._map, Cell._roofBlock, Cell._roofBlockMat, EClass._zone, MeshPass.Add(), altDirPosition, baseHeight, baseHeightWater, Zone.biome, BiomeProfile.TileGroup.block, Cell.blockDir, Cell.bridgeHeight, Cell.bridgePillar, Trait.CanBeDestroyed, card, SerializedCards.cards, SourceManager.cards, Point.cell, Map.cells, cellsMarked, ClearMarkedCells(), MapBounds.Contains(), ActionMode.Copy, Cell.decal, Card.Destroy(), destX, destZ, dir, editMode, exportData, BiomeProfile.exterior, FixWall(), BiomeProfile.TileGroup.floor, Cell.floorDir, Card.GetCurrency(), ActionMode.GetGuidePass(), Recipe.GetOrCreate(), h, Cell.HasWall, Cell.height, BiomeProfile.Tile.id, TileRow.id, Point.index, BiomeProfile.interior, Cell.isFloating, localOffsetX, localOffsetZ, map, SourceCard.map, BiomeProfile.Tile.mat, Cell.obj, Cell.objDir, Cell.objMat, Cell.objVal, offsetX, offsetZ, Recipe.OnRenderMarker(), EClass.pc, Card.pos, Point.Position(), procedural, Rand.Range(), Critter.RebuildCritter(), RenderRow.RecipeID, Map.RefreshAllTiles(), relative, Render, SerializedCards.Restore(), result, ruinChance, PartialMap.Result.ruined, ZoneExportData.serializedCards, Point.Set(), Map.SetReference(), Cell.sourceBlock, Cell.sourceBridge, Cell.sourceFloor, Cell.sourceObj, EClass.sources, Map.things, Card.trait, validPoints, value, w, Point.x, and Point.z.
Referenced by Apply(), AM_Copy.OnAfterProcessTiles(), AM_Copy.OnRenderTile(), ZoneEventHarvest.OnVisit(), and GenBounds.TryAddMapPiece().
Apply() [2/2]
static PartialMap PartialMap.Apply (string path, Point pos) inline static
Definition at line 440 of file PartialMap.cs.
    {
        PartialMap partialMap = Load(CorePath.MapPieceSave + path);
        partialMap.ruinChance = 0f;
        partialMap.Apply(pos, ApplyMode.Apply);
        return partialMap;
    }
References Apply(), Load(), CorePath.MapPieceSave, and path.
ClearMarkedCells()
void PartialMap.ClearMarkedCells () inline
Definition at line 103 of file PartialMap.cs.
    {
        foreach (Cell item in cellsMarked)
        {
            item.skipRender = false;
        }
        cellsMarked.Clear();
    }
References cellsMarked, and item.
Referenced by Apply(), AM_Copy.Clear(), and AM_Copy.OnDeactivate().
Delete()
static void PartialMap.Delete (string path) inline static
Definition at line 507 of file PartialMap.cs.
    {
        string fullFileNameWithoutExtension = path.GetFullFileNameWithoutExtension();
        IO.DeleteFile(path);
        IO.DeleteFile(fullFileNameWithoutExtension + ".jpg");
        IO.DeleteFile(fullFileNameWithoutExtension + ".txt");
    }
References path.
Referenced by UIScreenshot.Activate(), and AM_Copy.RefreshMenu().
ExportDialog()
static void PartialMap.ExportDialog (string dir = null) inline static
Definition at line 515 of file PartialMap.cs.
    {
        EClass.core.WaitForEndOfFrame(delegate
        {
            string pathDest = StandaloneFileBrowser.SaveFilePanel("Export Map Piece", dir ?? CorePath.MapPieceSaveUser, "new map piece", "mp");
            if (!string.IsNullOrEmpty(pathDest))
            {
                SavePreview(PathTemp, pathDest);
                Msg.SayRaw("Exported Zone");
            }
        });
    }
References EClass.core, dir, if(), CorePath.MapPieceSaveUser, PathTemp, SFB.StandaloneFileBrowser.SaveFilePanel(), SavePreview(), Msg.SayRaw(), and BaseCore.WaitForEndOfFrame().
Referenced by AM_Copy.OnUpdateInput().
FixWall()
int PartialMap.FixWall (Cell c) inline
Definition at line 371 of file PartialMap.cs.
    {
        switch (dir)
        {
        case 1:
            if (c.blockDir == 0)
            {
                return 1;
            }
            if (c.blockDir == 1)
            {
                return 0;
            }
            break;
        case 3:
            if (c.blockDir == 0)
            {
                return 1;
            }
            if (c.blockDir == 1)
            {
                return 0;
            }
            if (c.blockDir == 2)
            {
                return 0;
            }
            break;
        }
        return c.blockDir;
    }
References Cell.blockDir, and dir.
Referenced by Apply().
Load()
static PartialMap PartialMap.Load (string path = null) inline static
Definition at line 448 of file PartialMap.cs.
    {
        bool flag = path.IsEmpty();
        if (flag)
        {
            path = PathTemp;
        }
        if (!File.Exists(path))
        {
            return null;
        }
        MapMetaData metaData = Map.GetMetaData(path);
        if (metaData == null || metaData.partial == null)
        {
            return null;
        }
        PartialMap partial = metaData.partial;
        if (!flag)
        {
            partial.path = path;
        }
        partial.exportData = EClass._zone.Import(path);
        partial._Load();
        return partial;
    }
References _Load(), EClass._zone, Map.GetMetaData(), Zone.Import(), MapMetaData.partial, path, and PathTemp.
Referenced by Apply(), MapPiece.GetMap(), AM_Copy.Import(), and AM_Copy.OnAfterProcessTiles().
Rotate()
void PartialMap.Rotate () inline
Definition at line 92 of file PartialMap.cs.
    {
        dir++;
        if (dir > 3)
        {
            dir = 0;
        }
        SE.Rotate();
        localOffsetX = (localOffsetZ = 0);
    }
References dir, localOffsetX, and localOffsetZ.
Referenced by AM_Copy.RotateUnderMouse().
Save()
void PartialMap.Save (int _x, int _z, int _w, int _h) inline
Definition at line 411 of file PartialMap.cs.
    {
        offsetX = _x;
        offsetZ = _z;
        w = _w;
        h = _h;
        value = 0;
        for (int i = _x; i < _x + w; i++)
        {
            for (int j = _z; j < _z + h; j++)
            {
                Cell cell = EClass._map.cells[i, j];
                value += Card.GetTilePrice(cell.sourceBlock, cell.matBlock);
                value += Card.GetTilePrice(cell.sourceFloor, cell.matFloor);
                value += Card.GetTilePrice(cell.sourceObj, cell.matObj);
                value += Card.GetTilePrice(cell.sourceBridge, cell.matBridge);
                value += Card.GetTilePrice(cell.sourceRoofBlock, cell.matRoofBlock);
            }
        }
        foreach (Thing thing in EClass._map.things)
        {
            if (thing.trait.CanCopyInBlueprint && thing.pos.Within(_x, _z, _w, _h) && thing.IsInstalled)
            {
                value += thing.GetPrice() * thing.Num;
            }
        }
        EClass._zone.Export(PathTemp, this);
    }
References EClass._map, EClass._zone, Trait.CanCopyInBlueprint, Map.cells, Zone.Export(), Card.GetPrice(), Card.GetTilePrice(), h, Card.IsInstalled, Cell.matBlock, Cell.matBridge, Cell.matFloor, Cell.matObj, Cell.matRoofBlock, Card.Num, offsetX, offsetZ, PathTemp, Card.pos, Cell.sourceBlock, Cell.sourceBridge, Cell.sourceFloor, Cell.sourceObj, Cell.sourceRoofBlock, Map.things, Card.trait, value, w, and Point.Within().
Referenced by AM_Copy.OnAfterProcessTiles().
SavePreview()
static void PartialMap.SavePreview (string path, string pathDest) inline static
Definition at line 528 of file PartialMap.cs.
    {
        EClass.core.actionsNextFrame.Add(delegate
        {
            string fileName = CorePath.Temp + "preview.jpg";
            Texture2D texture2D = ScreenCapture.CaptureScreenshotAsTexture();
            int num = 200;
            int num2 = 100;
            RenderTexture renderTexture = new RenderTexture(num, num2, 0);
            renderTexture.Create();
            RenderTexture active = RenderTexture.active;
            RenderTexture.active = renderTexture;
            Graphics.Blit(texture2D, renderTexture);
            Texture2D texture2D2 = new Texture2D(num, num2, texture2D.format, mipChain: false);
            texture2D2.ReadPixels(new Rect(0f, 0f, num, num2), 0, 0);
            texture2D2.Apply();
            RenderTexture.active = active;
            renderTexture.Release();
            File.WriteAllBytes(fileName, texture2D2.EncodeToJPG());
            ZipFile zipFile = ZipFile.Read(path);
            zipFile.ExtractExistingFile = ExtractExistingFileAction.OverwriteSilently;
            zipFile.AddFile(fileName, "");
            zipFile.Save(pathDest);
            zipFile.Dispose();
            IO.DeleteFile(fileName);
            Object.Destroy(texture2D2);
            Object.Destroy(texture2D);
            Object.Destroy(renderTexture);
        });
    }
References BaseCore.actionsNextFrame, EClass.core, and path.
Referenced by ExportDialog().
Update()
void PartialMap.Update () inline
Definition at line 403 of file PartialMap.cs.
    {
        if (!path.IsEmpty())
        {
            Map.UpdateMetaData(path, this);
        }
    }
References path, and Map.UpdateMetaData().
Referenced by PartialMapMenu.RefreshOptions().
Member Data Documentation
allowRotate
bool PartialMap.allowRotate
Definition at line 55 of file PartialMap.cs.
Referenced by MapPiece.GetMap(), PartialMapMenu.RefreshOptions(), and AM_Copy.RotateUnderMouse().
baseHeight
int PartialMap.baseHeight
Definition at line 46 of file PartialMap.cs.
Referenced by _Load(), and Apply().
baseHeightWater
int PartialMap.baseHeightWater
Definition at line 49 of file PartialMap.cs.
Referenced by _Load(), and Apply().
cellsMarked
List<Cell> PartialMap.cellsMarked = new List<Cell>()
Definition at line 80 of file PartialMap.cs.
Referenced by Apply(), and ClearMarkedCells().
destX
int PartialMap.destX
Definition at line 64 of file PartialMap.cs.
Referenced by Apply().
destZ
int PartialMap.destZ
Definition at line 66 of file PartialMap.cs.
Referenced by Apply().
dir
int PartialMap.dir
Definition at line 43 of file PartialMap.cs.
Referenced by Apply(), ExportDialog(), FixWall(), and Rotate().
editMode
bool PartialMap.editMode
Definition at line 70 of file PartialMap.cs.
Referenced by Apply().
exportData
ZoneExportData PartialMap.exportData
Definition at line 78 of file PartialMap.cs.
Referenced by Apply().
h
int PartialMap.h
Definition at line 40 of file PartialMap.cs.
Referenced by _Load(), Apply(), Save(), and GenBounds.TryAddMapPiece().
ignoreBlock
bool PartialMap.ignoreBlock
Definition at line 58 of file PartialMap.cs.
Referenced by PartialMapMenu.RefreshOptions(), and GenBounds.TryAddMapPiece().
localOffsetX
int PartialMap.localOffsetX
Definition at line 60 of file PartialMap.cs.
Referenced by Apply(), and Rotate().
localOffsetZ
int PartialMap.localOffsetZ
Definition at line 62 of file PartialMap.cs.
Referenced by Apply(), and Rotate().
map
Map PartialMap.map
Definition at line 76 of file PartialMap.cs.
Referenced by _Load(), and Apply().
name
string PartialMap.name
Definition at line 28 of file PartialMap.cs.
Referenced by _Load(), UIScreenshot.Activate(), and AM_Blueprint.OnSave().
offsetX
int PartialMap.offsetX
Definition at line 31 of file PartialMap.cs.
Referenced by Apply(), and Save().
offsetZ
int PartialMap.offsetZ
Definition at line 34 of file PartialMap.cs.
Referenced by Apply(), and Save().
path
string PartialMap.path
Definition at line 68 of file PartialMap.cs.
Referenced by UIScreenshot.Activate(), Apply(), Delete(), Load(), AM_Blueprint.OnSave(), AM_Copy.RefreshMenu(), SavePreview(), GenBounds.TryAddMapPiece(), and Update().
procedural
bool PartialMap.procedural
Definition at line 72 of file PartialMap.cs.
Referenced by Apply().
relative
bool PartialMap.relative static
Definition at line 25 of file PartialMap.cs.
Referenced by Apply(), AM_Copy.OnClickSubMenu(), and AM_Copy.OnSetSubMenuButton().
result
Result PartialMap.result = new Result()
Definition at line 84 of file PartialMap.cs.
Referenced by Apply(), and GenRoom.Populate().
ruinChance
float PartialMap.ruinChance
Definition at line 74 of file PartialMap.cs.
Referenced by Apply().
validPoints
HashSet<int> PartialMap.validPoints = new HashSet<int>()
Definition at line 82 of file PartialMap.cs.
Referenced by Apply().
value
int PartialMap.value
Definition at line 52 of file PartialMap.cs.
Referenced by Apply(), PartialMapMenu.Refresh(), and Save().
w
int PartialMap.w
Definition at line 37 of file PartialMap.cs.
Referenced by _Load(), Apply(), Save(), and GenBounds.TryAddMapPiece().
Property Documentation
altDirPosition
bool PartialMap.altDirPosition get
Definition at line 88 of file PartialMap.cs.
Referenced by Apply().
ID
string PartialMap.ID get
Definition at line 90 of file PartialMap.cs.
PathTemp
string PartialMap.PathTemp static get
Definition at line 86 of file PartialMap.cs.
Referenced by _Load(), UIScreenshot.Activate(), ExportDialog(), Load(), AM_Copy.OnAfterProcessTiles(), and Save().
The documentation for this class was generated from the following file:
Elin/PartialMap.cs