Elin Decompiled Documentation: InvOwnerDraglet Class Reference
InvOwnerDraglet Class Reference
Public Types
enum ProcessType { None , Consume }
Public Member Functions
override bool AllowHold (Thing t)
InvOwnerDraglet (Card owner=null, Card container=null, CurrencyType _currency=CurrencyType.Money)
override void OnInit ()
override void OnClick (ButtonGrid button)
override void OnRightClick (ButtonGrid button)
override int GetPrice (Thing t, CurrencyType currency, int num, bool sell)
override string GetTextDetail (Thing t, CurrencyType currency, int num, bool sell)
virtual void OnWriteNote (Thing t, UINote n)
sealed override void OnProcess (Thing t)
virtual void _OnProcess (Thing t)
virtual void OnAfterRefuel ()
void RedrawButton ()
override void BuildUICurrency (UICurrency uiCurrency, bool canReroll=false)
Public Member Functions inherited from InvOwner
virtual bool AllowHold (Thing t)
virtual bool AllowMoved (Thing t)
virtual bool ShouldShowGuide (Thing t)
virtual bool AllowDrop (Thing t)
virtual Thing CreateDefaultContainer ()
virtual void BuildUICurrency (UICurrency uiCurrency, bool canReroll=false)
bool IsWeightOver (Thing t)
InvOwner (Card owner, Card container=null, CurrencyType _currency=CurrencyType.None, PriceType _price=PriceType.Default)
void Init ()
virtual void OnInit ()
virtual void OnClick (ButtonGrid button)
virtual void OnRightClick (ButtonGrid button)
virtual void OnRightPressed (ButtonGrid button)
InvOwner GetShitDestOwner (ButtonGrid b, bool rightMouse=false)
virtual void OnShiftClick (ButtonGrid b, bool rightMouse=false)
virtual bool CanShiftClick (ButtonGrid b, bool rightMouse=false)
virtual string GetTextShiftClick (ButtonGrid b)
virtual void OnCtrlClick (ButtonGrid button)
virtual bool CanCtrlClick (ButtonGrid b)
virtual string GetTextCtrlClick (ButtonGrid b)
virtual void OnAltClick (ButtonGrid button)
virtual bool CanAltClick (ButtonGrid b)
virtual string GetTextAltClick (ButtonGrid b)
void Grab (DragItemCard.DragInfo from)
Thing PutBack (DragItemCard.DragInfo from)
void OnStartDrag (DragItemCard.DragInfo from)
virtual bool OnCancelDrag (DragItemCard.DragInfo from)
virtual bool OnDrag (DragItemCard.DragInfo from, DragItemCard.DragInfo to, bool execute, bool cancel=false)
virtual void OnProcess (Thing t)
bool CanOpenContainer (Thing t)
ListInteraction ListInteractions (ButtonGrid b, bool context)
bool TryHold (Thing t)
virtual void ListInteractions (ListInteraction list, Thing t, Trait trait, ButtonGrid b, bool context)
virtual string GetAutoUseLang (ButtonGrid button)
void AutoUse (ButtonGrid button, bool repeat=false)
void ShowContextMenu (ButtonGrid button)
virtual int GetPrice (Thing t, CurrencyType currency, int num, bool sell)
virtual string GetTextDetail (Thing t, CurrencyType currency, int num, bool sell)
virtual void OnWriteNote (ButtonGrid button, UINote n)
virtual string IDCostIcon (Thing t)
virtual bool IsFailByCurse (Thing t)
Public Attributes
int count = -1
BlessedState state
int price
Public Attributes inherited from InvOwner
bool includeChildren
CurrencyType currency
PriceType priceType
HomeResource homeResource
Card owner
Card Container
List< ButtonGrid > buttons = new List<ButtonGrid>()
Properties
virtual ProcessType processType [get]
virtual bool ShowFuel [get]
virtual bool CanTargetAlly [get]
virtual string langWhat [get]
virtual bool AllowStockIngredients [get]
override bool AllowTransfer [get]
override bool AllowAutouse [get]
override bool AllowContext [get]
override bool UseGuide [get]
override bool CopyOnTransfer [get]
override bool InvertSell [get]
override bool DenyImportant [get]
LayerDragGrid dragGrid [get]
Properties inherited from InvOwner
static bool HasTrader [get]
static bool FreeTransfer [get]
virtual bool AllowAutouse [get]
virtual bool AllowContext [get]
virtual bool AllowSell [get]
virtual bool AlwaysShowTooltip [get]
virtual bool UseGuide [get]
virtual bool AllowTransfer [get]
virtual bool AllowDropOnDrag [get]
virtual string langTransfer [get]
virtual int destInvY [get]
virtual bool HasTransaction [get]
virtual bool CopyOnTransfer [get]
virtual bool SingleTarget [get]
bool UseHomeResource [get]
bool IsMagicChest [get]
List< Thing > Things [get]
Chara Chara [get]
ContainerType ContainerType [get]
virtual bool InvertSell [get]
virtual int numDragGrid [get]
virtual bool ShowNew [get]
virtual bool DenyImportant [get]
InvOwner destInvOwner [get]
string IDCurrency [get]
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Additional Inherited Members
Static Public Member Functions inherited from EClass
static int rndSeed (int a, int seed)
static int rnd (int a)
static int curve (int a, int start, int step, int rate=75)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Static Public Attributes inherited from InvOwner
static ForceGiveData forceGive = new ForceGiveData()
static InvOwner Trader
static InvOwner Main
static float clickTimer
Static Public Attributes inherited from EClass
static Core core
Detailed Description
Definition at line 4 of file InvOwnerDraglet.cs.
Member Enumeration Documentation
ProcessType
enum InvOwnerDraglet.ProcessType
Enumerator
None
Consume
Definition at line 6 of file InvOwnerDraglet.cs.
    {
        None,
        Consume
    }
Constructor & Destructor Documentation
InvOwnerDraglet()
InvOwnerDraglet.InvOwnerDraglet (Card owner = null, Card container = null, CurrencyType _currency = CurrencyType::Money) inline
Definition at line 49 of file InvOwnerDraglet.cs.
        : base(owner, container, _currency)
    {
    }
Member Function Documentation
_OnProcess()
virtual void InvOwnerDraglet._OnProcess (Thing t) inline virtual
Reimplemented in InvOwnerBlend, InvOwnerChangeMaterial, InvOwnerChaosOffering, InvOwnerCraft, InvOwnerDeliver, InvOwnerDeliverBox, InvOwnerEnchant, InvOwnerGacha, InvOwnerGene, InvOwnerGive, InvOwnerIdentify, InvOwnerLighten, InvOwnerMod, InvOwnerOffering, InvOwnerReconstruction, InvOwnerRecycle, InvOwnerRefuel, and InvOwnerUncurse.
Definition at line 157 of file InvOwnerDraglet.cs.
    {
    }
Referenced by OnProcess(), and LayerDragGrid.TryProc().
AllowHold()
override bool InvOwnerDraglet.AllowHold (Thing t) inline virtual
Reimplemented from InvOwner.
Definition at line 44 of file InvOwnerDraglet.cs.
    {
        return false;
    }
BuildUICurrency()
override void InvOwnerDraglet.BuildUICurrency (UICurrency uiCurrency, bool canReroll = false) inline virtual
Reimplemented from InvOwner.
Reimplemented in InvOwnerRecycle.
Definition at line 171 of file InvOwnerDraglet.cs.
    {
        base.BuildUICurrency(uiCurrency);
        uiCurrency.SetActive(price != 0);
    }
References price.
Referenced by LayerDragGrid.SetInv().
GetPrice()
override int InvOwnerDraglet.GetPrice (Thing t, CurrencyType currency, int num, bool sell) inline virtual
Reimplemented from InvOwner.
Definition at line 94 of file InvOwnerDraglet.cs.
    {
        return price;
    }
References price.
Referenced by GetTextDetail().
GetTextDetail()
override string InvOwnerDraglet.GetTextDetail (Thing t, CurrencyType currency, int num, bool sell) inline virtual
Reimplemented from InvOwner.
Definition at line 99 of file InvOwnerDraglet.cs.
    {
        int num2 = GetPrice(t, currency, num, sell);
        return "invInteraction2".lang(num.ToString() ?? "", langTransfer.lang()) + ((num2 == 0) ? "" : "invInteraction3".lang(num2.ToString() ?? "", EClass.sources.things.map[base.IDCurrency].GetName()));
    }
References InvOwner.currency, GetPrice(), InvOwner.langTransfer, EClass.sources, and SourceManager.things.
OnAfterRefuel()
virtual void InvOwnerDraglet.OnAfterRefuel () inline virtual
Reimplemented in InvOwnerCraft.
Definition at line 161 of file InvOwnerDraglet.cs.
    {
    }
OnClick()
override void InvOwnerDraglet.OnClick (ButtonGrid button) inline virtual
Reimplemented from InvOwner.
Definition at line 66 of file InvOwnerDraglet.cs.
    {
        if (button.card != null)
        {
            if (button.index == 0)
            {
                dragGrid.ClearButtons();
            }
            else
            {
                button.SetCard(null);
                dragGrid.RefreshCurrentGrid();
            }
            dragGrid.TryPutBack();
            dragGrid.uiIngredients.Refresh();
            SE.Equip();
            if (EClass.pc.ai is AI_UseCrafter && EClass.pc.ai.IsRunning)
            {
                EClass.pc.ai.Success();
            }
        }
    }
References Chara.ai, ButtonGrid.card, LayerDragGrid.ClearButtons(), dragGrid, ButtonGrid.index, AIAct.IsRunning, EClass.pc, UIDragGridIngredients.Refresh(), LayerDragGrid.RefreshCurrentGrid(), ButtonGrid.SetCard(), AIAct.Success(), LayerDragGrid.TryPutBack(), and LayerDragGrid.uiIngredients.
Referenced by OnRightClick().
OnInit()
override void InvOwnerDraglet.OnInit () inline virtual
Reimplemented from InvOwner.
Definition at line 54 of file InvOwnerDraglet.cs.
    {
        if (price == 0)
        {
            currency = CurrencyType.None;
        }
        if (!langWhat.IsEmpty())
        {
            Msg.Say(langWhat);
        }
    }
References InvOwner.currency, langWhat, price, and Msg.Say().
OnProcess()
sealed override void InvOwnerDraglet.OnProcess (Thing t) inline virtual
Reimplemented from InvOwner.
Definition at line 109 of file InvOwnerDraglet.cs.
    {
        if (!dragGrid.IsAllGridSet())
        {
            dragGrid.RefreshCurrentGrid();
            dragGrid.uiIngredients.Refresh();
            t.PlaySoundDrop(spatial: false);
            return;
        }
        _OnProcess(t);
        UIButton.TryShowTip();
        LayerInventory.SetDirty(t);
        if (processType == ProcessType.Consume)
        {
            EInput.haltInput = true;
            foreach (ButtonGrid b in dragGrid.buttons)
            {
                b.icon.rectTransform.DOScale(0f, 0.3f).SetEase(Ease.InBack).OnComplete(delegate
                {
                    if (b.transform != null)
                    {
                        b.icon.rectTransform.localScale = Vector3.one;
                        b.SetCardGrid(null, b.invOwner);
                        RedrawButton();
                    }
                    EInput.haltInput = false;
                });
            }
        }
        else
        {
            RedrawButton();
        }
        dragGrid.uiIngredients.Refresh();
        if (count > 0)
        {
            count--;
            if (count == 0)
            {
                dragGrid.Close();
            }
            else if (!langWhat.IsEmpty())
            {
                Msg.Say(langWhat);
            }
        }
    }
References _OnProcess(), LayerDragGrid.buttons, Layer.Close(), count, dragGrid, EInput.haltInput, UIButton.icon, LayerDragGrid.IsAllGridSet(), langWhat, Card.PlaySoundDrop(), processType, RedrawButton(), UIDragGridIngredients.Refresh(), LayerDragGrid.RefreshCurrentGrid(), Msg.Say(), LayerInventory.SetDirty(), UIButton.TryShowTip(), and LayerDragGrid.uiIngredients.
Referenced by UIDragGridIngredients.Refresh(), and UIDragGridIngredients.Update().
OnRightClick()
override void InvOwnerDraglet.OnRightClick (ButtonGrid button) inline virtual
Reimplemented from InvOwner.
Definition at line 89 of file InvOwnerDraglet.cs.
    {
        OnClick(button);
    }
References OnClick().
OnWriteNote()
virtual void InvOwnerDraglet.OnWriteNote (Thing t, UINote n) inline virtual
Reimplemented in InvOwnerGene.
Definition at line 105 of file InvOwnerDraglet.cs.
    {
    }
RedrawButton()
void InvOwnerDraglet.RedrawButton () inline
Definition at line 165 of file InvOwnerDraglet.cs.
    {
        dragGrid.RefreshCost();
        dragGrid.RefreshCurrentGrid();
    }
References dragGrid, LayerDragGrid.RefreshCost(), and LayerDragGrid.RefreshCurrentGrid().
Referenced by OnProcess().
Member Data Documentation
count
int InvOwnerDraglet.count = -1
Definition at line 12 of file InvOwnerDraglet.cs.
Referenced by InvOwnerChaosOffering._OnProcess(), InvOwnerGene.InvOwnerGene(), InvOwnerMod.InvOwnerMod(), OnProcess(), and LayerDragGrid.TryProc().
price
int InvOwnerDraglet.price
Definition at line 16 of file InvOwnerDraglet.cs.
Referenced by BuildUICurrency(), LayerDragGrid.GetPrice(), GetPrice(), and OnInit().
state
BlessedState InvOwnerDraglet.state
Definition at line 14 of file InvOwnerDraglet.cs.
Referenced by InvOwnerChangeMaterial._OnProcess(), InvOwnerEnchant._OnProcess(), InvOwnerIdentify._OnProcess(), InvOwnerLighten._OnProcess(), InvOwnerReconstruction._OnProcess(), InvOwnerUncurse._OnProcess(), and InvOwnerLighten.ShouldShowGuide().
Property Documentation
AllowAutouse
override bool InvOwnerDraglet.AllowAutouse get
Definition at line 30 of file InvOwnerDraglet.cs.
AllowContext
override bool InvOwnerDraglet.AllowContext get
Definition at line 32 of file InvOwnerDraglet.cs.
AllowStockIngredients
virtual bool InvOwnerDraglet.AllowStockIngredients get
Definition at line 26 of file InvOwnerDraglet.cs.
Referenced by UIDragGridIngredients.Refresh(), and LayerDragGrid.SetInv().
AllowTransfer
override bool InvOwnerDraglet.AllowTransfer get
Definition at line 28 of file InvOwnerDraglet.cs.
CanTargetAlly
virtual bool InvOwnerDraglet.CanTargetAlly get
Definition at line 22 of file InvOwnerDraglet.cs.
Referenced by LayerDragGrid.SetInv().
CopyOnTransfer
override bool InvOwnerDraglet.CopyOnTransfer get
Definition at line 36 of file InvOwnerDraglet.cs.
DenyImportant
override bool InvOwnerDraglet.DenyImportant get
Definition at line 40 of file InvOwnerDraglet.cs.
dragGrid
LayerDragGrid InvOwnerDraglet.dragGrid get
Definition at line 42 of file InvOwnerDraglet.cs.
Referenced by OnClick(), OnProcess(), and RedrawButton().
InvertSell
override bool InvOwnerDraglet.InvertSell get
Definition at line 38 of file InvOwnerDraglet.cs.
langWhat
virtual string InvOwnerDraglet.langWhat get
Definition at line 24 of file InvOwnerDraglet.cs.
Referenced by OnInit(), and OnProcess().
processType
virtual ProcessType InvOwnerDraglet.processType get
Definition at line 18 of file InvOwnerDraglet.cs.
Referenced by OnProcess().
ShowFuel
virtual bool InvOwnerDraglet.ShowFuel get
Definition at line 20 of file InvOwnerDraglet.cs.
Referenced by LayerDragGrid.SetInv().
UseGuide
override bool InvOwnerDraglet.UseGuide get
Definition at line 34 of file InvOwnerDraglet.cs.
The documentation for this class was generated from the following file:
Elin/InvOwnerDraglet.cs