Elin Decompiled Documentation: LayerHoard Class Reference
LayerHoard Class Reference
Public Member Functions
override void OnAfterInit ()
void Reset ()
override void OnKill ()
void AddRandom ()
void Generate ()
void OnClickClear ()
void OnClickNextMode ()
void OnClickConfig ()
Public Member Functions inherited from ELayer
override void OnBeforeAddLayer ()
void InitInspector ()
sealed override void Init ()
override void OnAfterAddLayer ()
void TryShowHelp ()
void AddLayerToUI (string id)
void TryShowHint (string _langHint=null)
void TalkHomeMemeber (string id)
void TalkMaid (string id)
override void OnRightClick ()
Public Member Functions inherited from Layer
virtual string GetTextHeader (Window window)
virtual bool HeaderIsListOf (int id)
virtual void Init ()
virtual void OnInit ()
virtual void OnAfterInit ()
virtual void ApplySkin ()
void ShowScreenLock (string id)
void UpdateInput ()
virtual void OnUpdateInput ()
virtual void OnRightClick ()
virtual bool OnBack ()
virtual void OnChangeLayer ()
virtual void OnCreate ()
void _AddLayer (string id)
Layer AddLayer (string id)
T AddLayer< T > ()
T AddLayer< T > (string id)
T AddLayerDontCloseOthers< T > ()
Layer AddLayerDontCloseOthers (Layer l)
T GetOrAddLayer< T > ()
virtual void OnBeforeAddLayer ()
virtual void OnAfterAddLayer ()
Layer AddLayer (Layer l)
void ToggleLayer (string id)
T ToggleLayer< T > (string id=null)
void WaitAndClose ()
void OnClickClose ()
virtual void Close ()
void CloseLayers ()
void RemoveLayers (bool removeImportant=false)
bool RemoveLayer< T > ()
void RemoveLayer (Layer l)
virtual void OnKill ()
Layer SetOnKill (Action action)
void DisableClose ()
void Delay (float duration=0.05f)
Layer SetDelay (float d)
Layer GetLayer (string id)
T GetLayer< T > (bool fromTop=false)
Layer GetTopLayer ()
void SwitchContent (int idWindow, int i)
virtual void OnSwitchContent (Window window)
Layer SetTitles (string langList, string idHeaderRow=null)
bool IsBlockWidgetClick ()
bool IsHideHud ()
bool IsAllowGeneralInput ()
bool IsUseBlur ()
bool IsPointerOnLayer ()
void ApplySkin ()
Public Attributes
HoardActor actor
bool autoList
int autoNum
float idleTimer
float fadeSpeed
CanvasGroup cg
UIText textMode
UIText textScore
UIText textTime
UIButton[] debugButtons
LayoutGroup layoutMenu
int v
Public Attributes inherited from Layer
Option option
UnityEvent onKill
Anime animeIn
Anime animeOut
bool closeOthers
bool defaultActionMode = true
Button screenLock
Layer parent
string idLayer
List< Layer > layers = new List<Layer>()
Vector2 lastParentPos
List< Window > windows = new List<Window>()
string langHint
Properties
Hoard hoard [get]
Properties inherited from ELayer
static Core core [get]
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static FactionBranch Branch [get]
static Faction Home [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static CoreConfig config [get]
static GameSetting setting [get]
static ColorProfile Colors [get]
static SourceManager sources [get]
static World world [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
bool IsFloat [get]
virtual string IdHelp [get]
Properties inherited from Layer
Layer TopLayer [get]
string uid [get]
virtual RectTransform rectLayers [get]
virtual bool blockWidgetClick [get]
Private Member Functions
void Update ()
void UpdateMousePos ()
Private Attributes
int lastScore
Vector3 lastMousePos
bool hasMouseMoved
Additional Inherited Members
Static Public Member Functions inherited from ELayer
static int rnd (int a)
Static Public Member Functions inherited from Layer
static T Create< T > ()
static T Create< T > (string path)
static Layer Create (string path)
Static Public Attributes inherited from Layer
static int skipInput
static bool closeOnRightClick
static bool rightClicked
static bool cancelKeyDown
static bool ignoreSounds
static Transform blurStopInstance
static string[] searchPath = new string[3] { "Layer", "Layer/Dialog", "Layer/LayerHome" }
Protected Member Functions inherited from ELayer
sealed override void _Close ()
sealed override void Kill ()
Protected Member Functions inherited from Layer
virtual void Awake ()
virtual void _Close ()
virtual void Kill ()
Protected Attributes inherited from Layer
RectTransform _rect
bool isDestroyed
Detailed Description
Definition at line 5 of file LayerHoard.cs.
Member Function Documentation
AddRandom()
void LayerHoard.AddRandom () inline
Definition at line 157 of file LayerHoard.cs.
    {
        foreach (SourceCollectible.Row row in ELayer.sources.collectibles.rows)
        {
            if (!row.tag.Contains("noSpawn"))
            {
                int num = ((row.num == 0) ? 10 : row.num);
                hoard.Add(row.id, ELayer.rnd(ELayer.rnd(ELayer.rnd(ELayer.rnd(num + 1) + 1) + 1) + 1));
            }
        }
        Reset();
    }
References Hoard.Add(), SourceManager.collectibles, hoard, Reset(), ELayer.rnd(), and ELayer.sources.
Generate()
void LayerHoard.Generate () inline
Definition at line 170 of file LayerHoard.cs.
    {
        hoard.Clear();
        foreach (SourceCollectible.Row row in ELayer.sources.collectibles.rows)
        {
            if (!row.tag.Contains("noSpawn"))
            {
                hoard.Add(row.id);
            }
        }
        hoard.mode = Hoard.Mode.lux;
        Reset();
    }
References Hoard.Add(), Hoard.Clear(), SourceManager.collectibles, hoard, Reset(), and ELayer.sources.
OnAfterInit()
override void LayerHoard.OnAfterInit () inline virtual
Reimplemented from Layer.
Definition at line 39 of file LayerHoard.cs.
    {
        ELayer.sources.collectibles.Init();
        Msg.TalkHomeMemeber("layerHoard");
        ActionMode.NoMap.Activate();
        actor = Util.Instantiate(actor);
        if (hoard.items.Count == 0)
        {
            OnClickClear();
        }
        else
        {
            Reset();
        }
        InvokeRepeating("UpdateMousePos", 0f, 0.1f);
        if (!ELayer.debug.debugHoard)
        {
            UIButton[] array = debugButtons;
            for (int i = 0; i < array.Length; i++)
            {
                array[i].SetActive(enable: false);
            }
        }
        layoutMenu.RebuildLayout(recursive: true);
        SoundManager.disableSpread = true;
        ELayer.Sound.zone.enabled = false;
        ELayer.scene.cam.enabled = false;
    }
References ActionMode.Activate(), actor, SourceManager.collectibles, ELayer.debug, debugButtons, CoreDebug.debugHoard, hoard, Hoard.items, layoutMenu, ActionMode.NoMap, OnClickClear(), Reset(), ELayer.sources, Msg.TalkHomeMemeber(), and Util.
OnClickClear()
void LayerHoard.OnClickClear () inline
Definition at line 184 of file LayerHoard.cs.
    {
        hoard.Clear();
        hoard.Add("gold", 1);
        Reset();
    }
References Hoard.Add(), Hoard.Clear(), hoard, and Reset().
Referenced by OnAfterInit().
OnClickConfig()
void LayerHoard.OnClickConfig () inline
Definition at line 198 of file LayerHoard.cs.
    {
        UIContextMenu uIContextMenu = ELayer.ui.contextMenu.Create("ContextHoard");
        int max = actor.bgs.Length - 1;
        uIContextMenu.AddSlider("room", (float n) => n + " / " + max, hoard.bg, delegate(float v)
        {
            hoard.bg = (int)v;
            actor.RefreshBG();
        }, 0f, max, isInt: true, hideOther: false);
        uIContextMenu.AddSlider("reflection", (float n) => n + " %", hoard.reflection, delegate(float v)
        {
            hoard.reflection = (int)v;
            actor.RefreshBG();
        }, 0f, 300f, isInt: true, hideOther: false);
        uIContextMenu.AddSlider("maxSounds", (float n) => n.ToString() ?? "", hoard.maxSounds, delegate(float v)
        {
            hoard.maxSounds = (int)v;
        }, 0f, 64f, isInt: true, hideOther: false);
        uIContextMenu.AddSlider("volume", (float n) => n.ToString() ?? "", hoard.volume, delegate(float v)
        {
            hoard.volume = (int)v;
        }, 0f, 200f, isInt: true, hideOther: false);
        uIContextMenu.AddToggle("voice", hoard.voice, delegate(bool on)
        {
            hoard.voice = on;
        });
        uIContextMenu.AddToggle("shadow", hoard.shadow, delegate(bool on)
        {
            hoard.shadow = on;
        });
        uIContextMenu.AddToggle("pixelPerfect", hoard.pixelPerfect, delegate(bool on)
        {
            hoard.pixelPerfect = on;
            actor.RefreshZoom();
        });
        uIContextMenu.Show();
    }
References actor, UIContextMenu.AddSlider(), UIContextMenu.AddToggle(), Hoard.bg, hoard, Hoard.maxSounds, Hoard.pixelPerfect, Hoard.reflection, HoardActor.RefreshBG(), HoardActor.RefreshZoom(), Hoard.shadow, UIContextMenu.Show(), ELayer.ui, v, Hoard.voice, and Hoard.volume.
OnClickNextMode()
void LayerHoard.OnClickNextMode () inline
Definition at line 191 of file LayerHoard.cs.
    {
        hoard.mode = hoard.mode.NextEnum();
        Msg.Nerun("h_filter".lang(("h_" + hoard.mode).lang()));
        Reset();
    }
References hoard, Hoard.mode, Msg.Nerun(), and Reset().
OnKill()
override void LayerHoard.OnKill () inline virtual
Reimplemented from Layer.
Definition at line 74 of file LayerHoard.cs.
    {
        actor.Clear();
        Object.DestroyImmediate(actor.gameObject);
        ActionMode.DefaultMode.Activate();
        ELayer.ui.cg.alpha = 1f;
        ELayer.Sound.maxSounds = ELayer.Sound._maxSounds;
        SoundManager.disableSpread = false;
        ELayer.Sound.zone.enabled = true;
        ELayer.scene.cam.enabled = true;
    }
References ActionMode.Activate(), actor, HoardActor.Clear(), ActionMode.DefaultMode, and ELayer.Sound.
Reset()
void LayerHoard.Reset () inline
Definition at line 68 of file LayerHoard.cs.
    {
        actor.Activate();
        textMode.text = "[" + ("h_" + hoard.mode).lang() + "]";
    }
References HoardActor.Activate(), actor, hoard, and Hoard.mode.
Referenced by AddRandom(), Generate(), OnAfterInit(), OnClickClear(), OnClickNextMode(), and Update().
Update()
void LayerHoard.Update () inline private
Definition at line 86 of file LayerHoard.cs.
    {
        if (textScore.gameObject.activeSelf && hoard.score != lastScore)
        {
            textScore.text = hoard.score + " / " + hoard.hiScore;
            lastScore = hoard.score;
        }
        if (Input.GetMouseButtonDown(2))
        {
            Reset();
        }
        if (ELayer.debug.enable)
        {
            if (Input.GetKeyDown(KeyCode.H))
            {
                hoard.hentai = true;
                hoard.Add("lulu", 2);
                hoard.Add("tentacle", 1);
                hoard.Add("tentacle2", 1);
                hoard.Add("tentacle3", 1);
                hoard.Add("tentacle4", 2);
                Msg.SayPic("UN_farris", "");
                Reset();
            }
            if (Input.GetKeyDown(KeyCode.M))
            {
                try
                {
                    CollectibleActor collectibleActor = actor.actors.FirstOrDefault((CollectibleActor a) => a.item.id == "mani");
                    if ((bool)collectibleActor && collectibleActor.gameObject.activeInHierarchy)
                    {
                        Msg.Nerun("");
                        RigidExplode rigidExplode = collectibleActor.gameObject.AddComponent<RigidExplode>();
                        rigidExplode.particle = actor.psExplode;
                        rigidExplode.radius *= 10f;
                        rigidExplode.force *= 10f;
                        rigidExplode.chance = 1f;
                        rigidExplode.intervalMin = (rigidExplode.intervalMax = 2f);
                        rigidExplode.rb = collectibleActor.GetComponent<Rigidbody2D>();
                        actor.updates.Add(rigidExplode);
                    }
                }
                catch
                {
                }
            }
        }
        UIButton componentOf = InputModuleEX.GetComponentOf<UIButton>();
        if (ELayer.ui.GetTopLayer() != this || ((bool)componentOf && componentOf.transform.IsChildOf(base.transform)) || hasMouseMoved)
        {
            idleTimer = 0f;
            v = 1;
        }
        else
        {
            idleTimer += Time.deltaTime;
            if (idleTimer > 1f)
            {
                v = -1;
            }
        }
        (cg ?? ELayer.ui.cg).alpha += (float)v * Time.deltaTime * fadeSpeed;
        ELayer.Sound.maxSounds = hoard.maxSounds;
    }
References actor, HoardActor.actors, Hoard.Add(), cg, ELayer.debug, CoreDebug.enable, fadeSpeed, hasMouseMoved, Hoard.hiScore, hoard, idleTimer, CollectibleActor.item, lastScore, Hoard.maxSounds, Msg.Nerun(), HoardActor.psExplode, Reset(), Msg.SayPic(), Hoard.score, textScore, ELayer.ui, HoardActor.updates, and v.
UpdateMousePos()
void LayerHoard.UpdateMousePos () inline private
Definition at line 151 of file LayerHoard.cs.
    {
        hasMouseMoved = (Input.mousePosition - lastMousePos).magnitude > 15f;
        lastMousePos = Input.mousePosition;
    }
References hasMouseMoved, and lastMousePos.
Member Data Documentation
actor
HoardActor LayerHoard.actor
Definition at line 7 of file LayerHoard.cs.
Referenced by OnAfterInit(), OnClickConfig(), OnKill(), Reset(), and Update().
autoList
bool LayerHoard.autoList
Definition at line 9 of file LayerHoard.cs.
autoNum
int LayerHoard.autoNum
Definition at line 11 of file LayerHoard.cs.
cg
CanvasGroup LayerHoard.cg
Definition at line 17 of file LayerHoard.cs.
Referenced by Update().
debugButtons
UIButton [] LayerHoard.debugButtons
Definition at line 25 of file LayerHoard.cs.
Referenced by OnAfterInit().
fadeSpeed
float LayerHoard.fadeSpeed
Definition at line 15 of file LayerHoard.cs.
Referenced by Update().
hasMouseMoved
bool LayerHoard.hasMouseMoved private
Definition at line 35 of file LayerHoard.cs.
Referenced by Update(), and UpdateMousePos().
idleTimer
float LayerHoard.idleTimer
Definition at line 13 of file LayerHoard.cs.
Referenced by Update().
lastMousePos
Vector3 LayerHoard.lastMousePos private
Definition at line 33 of file LayerHoard.cs.
Referenced by UpdateMousePos().
lastScore
int LayerHoard.lastScore private
Definition at line 29 of file LayerHoard.cs.
Referenced by Update().
layoutMenu
LayoutGroup LayerHoard.layoutMenu
Definition at line 27 of file LayerHoard.cs.
Referenced by OnAfterInit().
textMode
UIText LayerHoard.textMode
Definition at line 19 of file LayerHoard.cs.
textScore
UIText LayerHoard.textScore
Definition at line 21 of file LayerHoard.cs.
Referenced by Update().
textTime
UIText LayerHoard.textTime
Definition at line 23 of file LayerHoard.cs.
v
int LayerHoard.v
Definition at line 31 of file LayerHoard.cs.
Referenced by OnClickConfig(), and Update().
Property Documentation
hoard
Hoard LayerHoard.hoard get
Definition at line 37 of file LayerHoard.cs.
Referenced by AddRandom(), Generate(), OnAfterInit(), OnClickClear(), OnClickConfig(), OnClickNextMode(), Reset(), and Update().
The documentation for this class was generated from the following file:
Elin/LayerHoard.cs