Elin Decompiled Documentation: Effect Class Reference
Effect Class Reference
Public Types
enum Type { Default , Firework }
Public Member Functions
void Play (float delay, Point from, float fixY=0f, Point to=null, Sprite sprite=null)
Effect Play (Point from, float fixY=0f, Point to=null, Sprite sprite=null)
Effect _Play (Point from, Vector3 fromV, float fixY=0f, Point to=null, Sprite sprite=null)
Effect Play (Vector3 v)
Effect Flip (bool x=false, bool y=false)
Effect SetStartDelay (float a)
virtual void OnPlay ()
virtual void OnUpdate ()
void Kill ()
void OnDisable ()
void OnDestroy ()
Effect Emit (int num)
Effect SetParticleColor (Color c)
Effect SetParticleColor (Color color, bool changeMaterial=false, string idCol="_Color")
Effect SetScale (float a)
Static Public Member Functions
static Effect Get (Effect original)
static Effect Get (string id)
static T Get< T > (string id)
Static Public Member Functions inherited from EMono
static int rnd (int a)
Public Attributes
Type type
float duration = 1f
float speed
float startDelay
bool lookAtTarget
bool rotate
bool pool
SpriteRenderer sr
ParticleSystem[] systems
Vector3[] dirs
Ease ease
Vector3 posFix
Vector3 randomRange
Tween moveTween
Sprite[] sprites
bool randomFlip
bool randomSpeed
bool test
bool setColor = true
Action onComplete
int spriteIndex
float timer
Vector3 fromV
Vector3 destV
bool pooled
Transform poolParent
List< Material > materialsToDestroy
Point destPos
Tween killTimer
Protected Member Functions
void Activate ()
Protected Attributes
bool killed
Properties
static EffectManager manager [get]
Properties inherited from EMono
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SoundManager Sound [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static CoreDebug debug [get]
Additional Inherited Members
Static Public Attributes inherited from EMono
static Core core
Detailed Description
Definition at line 6 of file Effect.cs.
Member Enumeration Documentation
Type
enum Effect.Type
Enumerator
Default
Firework
Definition at line 8 of file Effect.cs.
    {
        Default,
        Firework
    }
Member Function Documentation
_Play()
Effect Effect._Play (Point from, Vector3 fromV, float fixY = 0f, Point to = null, Sprite sprite = null) inline
Definition at line 115 of file Effect.cs.
    {
        if (!EMono.core.IsGameStarted)
        {
            Kill();
            return null;
        }
        if ((bool)sprite)
        {
            sr.sprite = sprite;
        }
        if (setColor)
        {
            float num = 0.07f * (float)(int)from.cell.light + EMono.core.screen.tileMap._baseBrightness;
            num += ((from.cell.HasRoof || from.cell.isShadowed) ? (-0.2f) : 0f);
            if ((bool)sr)
            {
                sr.material.SetVector("_Color", new Vector4(num, num, num, 1f));
            }
        }
        fromV += posFix;
        fromV.y += fixY;
        if (to == null)
        {
            fromV += randomRange.Random();
        }
        this.fromV = fromV;
        destPos = to ?? from;
        base.transform.position = fromV;
        if (randomFlip)
        {
            sr.flipX = EMono.rnd(2) == 0;
        }
        if (to != null)
        {
            float num2 = Mathf.Min(speed * (float)from.Distance(to), duration);
            destV = to.Position() + posFix + randomRange.Random();
            if (rotate)
            {
                base.transform.rotation = from.GetRotation(to);
            }
            moveTween = base.transform.DOMove(destV, num2).SetEase(Ease.Linear).SetDelay(startDelay);
        }
        Activate();
        OnPlay();
        OnUpdate();
        return this;
    }
References BaseTileMap._baseBrightness, Activate(), Point.cell, EMono.core, destPos, destV, Point.Distance(), duration, fromV, Point.GetRotation(), Core.IsGameStarted, Cell.isShadowed, Kill(), moveTween, OnPlay(), OnUpdate(), posFix, randomFlip, randomRange, EMono.rnd(), rotate, Core.screen, setColor, speed, sr, startDelay, and BaseGameScreen.tileMap.
Referenced by EffectIRenderer.Play(), Play(), Card.PlayEffect(), and AttackProcess.PlayRangedAnime().
Activate()
void Effect.Activate () inline protected
Definition at line 179 of file Effect.cs.
    {
        if (sprites.Length != 0 && type != Type.Firework)
        {
            sr.enabled = false;
        }
        manager.Add(this);
        killTimer = TweenUtil.Tween(startDelay + duration + 0.01f + (float)sprites.Length * 0.01f, null, Kill);
    }
References EffectManager.Add(), duration, Kill(), killTimer, manager, sprites, startDelay, and type.
Referenced by _Play(), EffectIRenderer.Play(), and Play().
Emit()
Effect Effect.Emit (int num) inline
Definition at line 274 of file Effect.cs.
    {
        ParticleSystem[] array = systems;
        for (int i = 0; i < array.Length; i++)
        {
            array[i].Emit(num);
        }
        return this;
    }
References systems.
Referenced by Card.DamageHP(), Card.Die(), and AttackProcess.PlayRangedAnime().
Flip()
Effect Effect.Flip (bool x = false, bool y = false) inline
Definition at line 189 of file Effect.cs.
    {
        if ((bool)sr)
        {
            sr.flipX = (sr.flipX ? (!x) : x);
            sr.flipY = (sr.flipY ? (!y) : y);
        }
        return this;
    }
References sr.
Get() [1/2]
static Effect Effect.Get (Effect original) inline static
Definition at line 85 of file Effect.cs.
    {
        return UnityEngine.Object.Instantiate(original);
    }
Referenced by Chara._Move(), Zone.ClaimZone(), EffectMeteor.Create(), ActEffect.DamageEle(), Map.DestroyObj(), Chara.Die(), Map.MineBlock(), Map.MineFloor(), Map.MineRamp(), TaskDrawWater.OnCreateProgress(), TaskPlow.OnCreateProgress(), TaskPourWater.OnCreateProgress(), TraitAltar.OnOffer(), TaskBuild.OnProgressComplete(), TaskCraft.OnProgressComplete(), TraitDaggerGrave.OnUse(), DramaManager.ParseLine(), ActSummonGuard.Perform(), Point.PlayEffect(), Card.PlayEffect(), SourceMaterial.Row.PlayHitEffect(), AttackProcess.PlayRangedAnime(), TraitEffect.Proc(), AI_Fish.ProgressFish.Ripple(), AI_UseCrafter.Run(), ActThrow.Throw(), TraitCoreZone.TrySetAct(), and TraitWaystone.TrySetAct().
Get() [2/2]
static Effect Effect.Get (string id) inline static
Definition at line 90 of file Effect.cs.
    {
        return manager.effects.Get(id);
    }
References EffectManager.effects, EffectManager.EffectList.Get(), and manager.
Get< T >()
static T Effect.Get< T > (string id) inline static
Type Constraints
T : Effect
Definition at line 95 of file Effect.cs.
                                              : Effect
    {
        return manager.effects.Get(id) as T;
    }
References EffectManager.effects, EffectManager.EffectList.Get(), and manager.
Kill()
void Effect.Kill () inline
Definition at line 238 of file Effect.cs.
    {
        TweenUtil.KillTween(ref killTimer);
        TweenUtil.KillTween(ref moveTween);
        killed = true;
        manager.Remove(this);
        if (pool && manager.effects.usePool)
        {
            PoolManager.DespawnOrDestroy(base.transform);
        }
        else if ((bool)base.gameObject)
        {
            UnityEngine.Object.Destroy(base.gameObject);
        }
    }
References PoolManager.DespawnOrDestroy(), EffectManager.effects, killed, killTimer, manager, moveTween, pool, EffectManager.Remove(), and DynamicAsset< T >.usePool.
Referenced by _Play(), Activate(), OnDisable(), OnUpdate(), EffectIRenderer.Play(), and Play().
OnDestroy()
void Effect.OnDestroy () inline
Definition at line 262 of file Effect.cs.
    {
        if (materialsToDestroy == null)
        {
            return;
        }
        foreach (Material item in materialsToDestroy)
        {
            UnityEngine.Object.Destroy(item);
        }
    }
References item, Material, and materialsToDestroy.
OnDisable()
void Effect.OnDisable () inline
Definition at line 254 of file Effect.cs.
    {
        if ((bool)base.transform.parent && !test)
        {
            Kill();
        }
    }
References Kill(), and test.
OnPlay()
virtual void Effect.OnPlay () inline virtual
Reimplemented in EffectMeteor.
Definition at line 205 of file Effect.cs.
    {
    }
Referenced by _Play(), and Play().
OnUpdate()
virtual void Effect.OnUpdate () inline virtual
Reimplemented in EffectIRenderer.
Definition at line 209 of file Effect.cs.
    {
        if (!base.gameObject.activeSelf)
        {
            base.gameObject.SetActive(value: true);
        }
        timer += (randomSpeed ? UnityEngine.Random.Range(Time.deltaTime, Time.deltaTime * 1.5f) : Time.deltaTime);
        if (startDelay != 0f)
        {
            if (timer < startDelay)
            {
                return;
            }
            timer = (startDelay = 0f);
        }
        if (sprites.Length != 0 && type != Type.Firework && timer > duration / (float)sprites.Length)
        {
            timer = 0f;
            spriteIndex++;
            if (spriteIndex >= sprites.Length)
            {
                Kill();
                return;
            }
            sr.enabled = true;
            sr.sprite = sprites[spriteIndex];
        }
    }
References duration, Kill(), randomSpeed, spriteIndex, sprites, startDelay, timer, and type.
Referenced by _Play(), and Play().
Play() [1/3]
void Effect.Play (float delay, Point from, float fixY = 0f, Point to = null, Sprite sprite = null) inline
Definition at line 100 of file Effect.cs.
    {
        Point _from = from.Copy();
        Point _to = to?.Copy() ?? null;
        TweenUtil.Tween(delay, delegate
        {
            Play(_from, fixY, _to, sprite);
        });
    }
References Point.Copy(), and Play().
Referenced by Chara._Move(), Zone.ClaimZone(), EffectMeteor.Create(), ActEffect.DamageEle(), Map.DestroyObj(), Chara.Die(), Map.MineBlock(), Map.MineFloor(), Map.MineRamp(), TaskDrawWater.OnCreateProgress(), TaskPlow.OnCreateProgress(), TaskPourWater.OnCreateProgress(), TraitAltar.OnOffer(), TaskBuild.OnProgressComplete(), TaskCraft.OnProgressComplete(), TraitDaggerGrave.OnUse(), TraitPowerStatue.OnUse(), DramaManager.ParseLine(), ActSummonGuard.Perform(), Play(), Point.PlayEffect(), SourceMaterial.Row.PlayHitEffect(), TraitEffect.Proc(), AI_Fish.ProgressFish.Ripple(), and AI_UseCrafter.Run().
Play() [2/3]
Effect Effect.Play (Point from, float fixY = 0f, Point to = null, Sprite sprite = null) inline
Definition at line 110 of file Effect.cs.
    {
        return _Play(from, from.Position(), fixY, to, sprite);
    }
References _Play(), and Point.Position().
Play() [3/3]
Effect Effect.Play (Vector3 v) inline
Definition at line 164 of file Effect.cs.
    {
        if (!EMono.core.IsGameStarted)
        {
            Kill();
            return null;
        }
        fromV = v;
        base.transform.position = fromV + posFix;
        Activate();
        OnPlay();
        OnUpdate();
        return this;
    }
References Activate(), EMono.core, fromV, Core.IsGameStarted, Kill(), OnPlay(), OnUpdate(), and posFix.
SetParticleColor() [1/2]
Effect Effect.SetParticleColor (Color c) inline
Definition at line 284 of file Effect.cs.
    {
        ParticleSystem[] array = systems;
        for (int i = 0; i < array.Length; i++)
        {
            ParticleSystem.MainModule main = array[i].main;
            main.startColor = c;
        }
        return this;
    }
References systems.
Referenced by ActEffect.DamageEle(), Card.DamageHP(), Card.Die(), and TraitEffect.Proc().
SetParticleColor() [2/2]
Effect Effect.SetParticleColor (Color color, bool changeMaterial = false, string idCol = "_Color") inline
Definition at line 295 of file Effect.cs.
    {
        if (changeMaterial)
        {
            materialsToDestroy = new List<Material>();
        }
        ParticleSystem[] array = systems;
        foreach (ParticleSystem particleSystem in array)
        {
            if (changeMaterial)
            {
                Material material = particleSystem.GetComponent<ParticleSystemRenderer>().material;
                materialsToDestroy.Add(material);
                material.SetColor(idCol, color);
            }
            else
            {
                ParticleSystem.MainModule main = particleSystem.main;
                main.startColor = color;
            }
        }
        return this;
    }
References material, Material, materialsToDestroy, and systems.
SetScale()
Effect Effect.SetScale (float a) inline
Definition at line 319 of file Effect.cs.
    {
        base.transform.localScale *= a;
        return this;
    }
SetStartDelay()
Effect Effect.SetStartDelay (float a) inline
Definition at line 199 of file Effect.cs.
    {
        startDelay = a;
        return this;
    }
References startDelay.
Referenced by ActEffect.DamageEle().
Member Data Documentation
destPos
Point Effect.destPos
Definition at line 76 of file Effect.cs.
Referenced by _Play(), and EffectMeteor.OnPlay().
destV
Vector3 Effect.destV
Definition at line 64 of file Effect.cs.
Referenced by _Play(), EffectMeteor.OnPlay(), EffectIRenderer.OnUpdate(), and EffectIRenderer.Play().
dirs
Vector3 [] Effect.dirs
Definition at line 32 of file Effect.cs.
Referenced by TraitEffect.Proc().
duration
float Effect.duration = 1f
Definition at line 16 of file Effect.cs.
Referenced by _Play(), Activate(), OnUpdate(), and EffectIRenderer.OnUpdate().
ease
Ease Effect.ease
Definition at line 34 of file Effect.cs.
fromV
Vector3 Effect.fromV
Definition at line 61 of file Effect.cs.
Referenced by _Play(), EffectMeteor.OnPlay(), and Play().
killed
bool Effect.killed protected
Definition at line 78 of file Effect.cs.
Referenced by Kill().
killTimer
Tween Effect.killTimer
Definition at line 81 of file Effect.cs.
Referenced by Activate(), and Kill().
lookAtTarget
bool Effect.lookAtTarget
Definition at line 22 of file Effect.cs.
materialsToDestroy
List<Material> Effect.materialsToDestroy
Definition at line 73 of file Effect.cs.
Referenced by OnDestroy(), and SetParticleColor().
moveTween
Tween Effect.moveTween
Definition at line 40 of file Effect.cs.
Referenced by _Play(), Kill(), and EffectMeteor.OnPlay().
onComplete
Action Effect.onComplete
Definition at line 52 of file Effect.cs.
Referenced by EffectMeteor.Create(), and EffectMeteor.OnPlay().
pool
bool Effect.pool
Definition at line 26 of file Effect.cs.
Referenced by Kill().
pooled
bool Effect.pooled
Definition at line 67 of file Effect.cs.
poolParent
Transform Effect.poolParent
Definition at line 70 of file Effect.cs.
posFix
Vector3 Effect.posFix
Definition at line 36 of file Effect.cs.
Referenced by _Play(), EffectText.Play(), and Play().
randomFlip
bool Effect.randomFlip
Definition at line 44 of file Effect.cs.
Referenced by _Play().
randomRange
Vector3 Effect.randomRange
Definition at line 38 of file Effect.cs.
Referenced by _Play(), and EffectText.Play().
randomSpeed
bool Effect.randomSpeed
Definition at line 46 of file Effect.cs.
Referenced by OnUpdate().
rotate
bool Effect.rotate
Definition at line 24 of file Effect.cs.
Referenced by _Play().
setColor
bool Effect.setColor = true
Definition at line 50 of file Effect.cs.
Referenced by _Play().
speed
float Effect.speed
Definition at line 18 of file Effect.cs.
Referenced by _Play(), and EffectIRenderer.OnUpdate().
spriteIndex
int Effect.spriteIndex
Definition at line 55 of file Effect.cs.
Referenced by OnUpdate().
sprites
Sprite [] Effect.sprites
Definition at line 42 of file Effect.cs.
Referenced by Activate(), OnUpdate(), TraitEffect.Proc(), and TraitEffect.TrySetAct().
sr
SpriteRenderer Effect.sr
Definition at line 28 of file Effect.cs.
Referenced by _Play(), and Flip().
startDelay
float Effect.startDelay
Definition at line 20 of file Effect.cs.
Referenced by _Play(), Activate(), EffectMeteor.OnPlay(), OnUpdate(), and SetStartDelay().
systems
ParticleSystem [] Effect.systems
Definition at line 30 of file Effect.cs.
Referenced by Emit(), SetParticleColor(), and TraitEffect.TrySetAct().
test
bool Effect.test
Definition at line 48 of file Effect.cs.
Referenced by OnDisable().
timer
float Effect.timer
Definition at line 58 of file Effect.cs.
Referenced by OnUpdate(), and EffectIRenderer.OnUpdate().
type
Type Effect.type
Definition at line 14 of file Effect.cs.
Referenced by Activate(), and OnUpdate().
Property Documentation
manager
EffectManager Effect.manager static get
Definition at line 83 of file Effect.cs.
Referenced by Activate(), Get(), Get< T >(), and Kill().
The documentation for this class was generated from the following file:
Elin/Effect.cs