Elin Decompiled Documentation: AM_Mine Class Reference
AM_Mine Class Reference
Public Member Functions
override bool IsRoofEditMode (Card c=null)
override void OnUpdateCursor ()
override bool ForcedInstaComplete (TaskMine t)
override MeshPass GetGuidePass (Point point)
void Activate (TaskMine.Mode _mode)
override void OnActivate ()
override void OnSelectStart (Point point)
override void OnSelectEnd (bool cancel)
override void OnCreateMold (bool processing=false)
override void OnRenderTile (Point point, HitResult result, int dir)
Public Member Functions inherited from AM_Designation< TaskMine >
virtual bool CanInstaComplete (T t)
virtual bool ForcedInstaComplete (T t)
virtual HitResult HitResultOnDesignation (Point p)
override void OnActivate ()
void CreateNewMold (bool processing=false)
virtual void OnCreateMold (bool processing=false)
override HitResult HitTest (Point point, Point start)
override bool CanProcessTiles ()
override void OnBeforeProcessTiles ()
override void OnProcessTiles (Point point, int dir)
override void OnAfterProcessTiles (Point start, Point end)
override void OnRefreshSummary (Point point, HitResult result, HitSummary summary)
Public Attributes
TaskMine.Mode mode
int ramp = 3
Public Attributes inherited from AM_Designation< TaskMine >
TaskList< T > list
T mold
Properties
override int CostMoney [get]
override BaseTileSelector.HitType hitType [get]
override string id [get]
override bool AllowAutoClick [get]
override bool CanTargetFog [get]
Properties inherited from AM_Designation< TaskMine >
override string idSound [get]
override bool IsBuildMode [get]
Detailed Description
Definition at line 3 of file AM_Mine.cs.
Member Function Documentation
Activate()
void AM_Mine.Activate (TaskMine::Mode _mode) inline
Definition at line 43 of file AM_Mine.cs.
    {
        mode = _mode;
        ramp = 3;
        Activate();
    }
References Activate(), mode, and ramp.
Referenced by Activate(), and HotItemActionMode.Execute().
ForcedInstaComplete()
override bool AM_Mine.ForcedInstaComplete (TaskMine t) inline
Definition at line 29 of file AM_Mine.cs.
    {
        return t.pos.sourceBlock.tileType.CanInstaComplete;
    }
References TaskPoint.pos, and Point.sourceBlock.
GetGuidePass()
override MeshPass AM_Mine.GetGuidePass (Point point) inline
Definition at line 34 of file AM_Mine.cs.
    {
        if ((IsRoofEditMode() && point.cell._roofBlock != 0) || (!IsRoofEditMode() && point.HasWallOrFence))
        {
            return EClass.screen.guide.passGuideBlock;
        }
        return base.GetGuidePass(point);
    }
References Cell._roofBlock, Point.cell, BaseGameScreen.guide, Point.HasWallOrFence, IsRoofEditMode(), ScreenGuide.passGuideBlock, and EClass.screen.
IsRoofEditMode()
override bool AM_Mine.IsRoofEditMode (Card c = null) inline
Definition at line 19 of file AM_Mine.cs.
    {
        return Input.GetKey(KeyCode.LeftAlt);
    }
Referenced by TaskMine.DrawMarker(), GetGuidePass(), TaskMine.GetHitResult(), Map.MineBlock(), TaskMine.OnProgressComplete(), and OnRenderTile().
OnActivate()
override void AM_Mine.OnActivate () inline
Definition at line 50 of file AM_Mine.cs.
    {
        list = base.Designations.mine;
        base.OnActivate();
    }
References AM_Designation< TaskMine >.list.
OnCreateMold()
override void AM_Mine.OnCreateMold (bool processing = false) inline virtual
Reimplemented from AM_Designation< TaskMine >.
Definition at line 66 of file AM_Mine.cs.
    {
        mold.mode = mode;
        mold.ramp = ramp;
    }
References mode, and ramp.
Referenced by ActionHint.Refresh().
OnRenderTile()
override void AM_Mine.OnRenderTile (Point point, HitResult result, int dir) inline
Definition at line 72 of file AM_Mine.cs.
    {
        if (!IsRoofEditMode() && point.cell.HasWallOrFence && (result == HitResult.Valid || result == HitResult.Invalid))
        {
            EClass.screen.guide.DrawWall(point, (result == HitResult.Valid) ? EClass.Colors.blockColors.Valid : EClass.Colors.blockColors.Warning);
        }
        else
        {
            base.OnRenderTile(point, result, dir);
        }
    }
References ColorProfile.blockColors, Point.cell, EClass.Colors, ScreenGuide.DrawWall(), BaseGameScreen.guide, Cell.HasWallOrFence, IsRoofEditMode(), EClass.screen, ColorProfile.BlockColors.Valid, and ColorProfile.BlockColors.Warning.
OnSelectEnd()
override void AM_Mine.OnSelectEnd (bool cancel) inline
Definition at line 61 of file AM_Mine.cs.
    {
        EClass.ui.hud.hint.groupRadio.ToggleInteractable(enable: true);
    }
References EClass.ui.
OnSelectStart()
override void AM_Mine.OnSelectStart (Point point) inline
Definition at line 56 of file AM_Mine.cs.
    {
        EClass.ui.hud.hint.groupRadio.ToggleInteractable(enable: false);
    }
References EClass.ui.
OnUpdateCursor()
override void AM_Mine.OnUpdateCursor () inline
Definition at line 24 of file AM_Mine.cs.
    {
        SetCursorOnMap(CursorSystem.Mine);
    }
References CursorSystem.Mine.
Member Data Documentation
mode
TaskMine.Mode AM_Mine.mode
Definition at line 5 of file AM_Mine.cs.
Referenced by Activate(), and OnCreateMold().
ramp
int AM_Mine.ramp = 3
Definition at line 7 of file AM_Mine.cs.
Referenced by Activate(), and OnCreateMold().
Property Documentation
AllowAutoClick
override bool AM_Mine.AllowAutoClick get
Definition at line 15 of file AM_Mine.cs.
CanTargetFog
override bool AM_Mine.CanTargetFog get
Definition at line 17 of file AM_Mine.cs.
CostMoney
override int AM_Mine.CostMoney get
Definition at line 9 of file AM_Mine.cs.
hitType
override BaseTileSelector.HitType AM_Mine.hitType get
Definition at line 11 of file AM_Mine.cs.
id
override string AM_Mine.id get
Definition at line 13 of file AM_Mine.cs.
The documentation for this class was generated from the following file:
Elin/AM_Mine.cs