Elin Decompiled Documentation: ObjectPool< T > Class Template Reference
ObjectPool< T > Class Template Reference
Classes
interface IItem
class Item
Public Member Functions
ObjectPool (UnityAction< T > actionOnGet, UnityAction< T > actionOnRelease)
T Get ()
void Release (T element)
Static Public Member Functions
static Item< T > Create< T > (int max=100, int addsPerUpdate=10, Action< T > _onCreate=null)
Public Attributes
List< IItem > items = new List<IItem>()
Static Public Attributes
static ObjectPool Instance
Properties
int countAll [get, private set]
int countActive [get]
int countInactive [get]
Private Member Functions
void Awake ()
void Update ()
Private Attributes
readonly Stack< T > m_Stack = new Stack<T>()
readonly UnityAction< T > m_ActionOnGet
readonly UnityAction< T > m_ActionOnRelease
Detailed Description
Type Constraints
T : new()
Definition at line 5 of file ObjectPool.cs.
Constructor & Destructor Documentation
ObjectPool()
ObjectPool< T >.ObjectPool (UnityAction< T > actionOnGet, UnityAction< T > actionOnRelease) inline
Definition at line 19 of file ObjectPool.cs.
    {
        m_ActionOnGet = actionOnGet;
        m_ActionOnRelease = actionOnRelease;
    }
References ObjectPool< T >.m_ActionOnGet, and ObjectPool< T >.m_ActionOnRelease.
Member Function Documentation
Awake()
void ObjectPool< T >.Awake () inline private
Definition at line 100 of file ObjectPool.cs.
    {
        Instance = this;
    }
References ObjectPool< T >.Instance.
Create< T >()
static Item< T > ObjectPool< T >.Create< T > (int max = 100, int addsPerUpdate = 10, Action< T > _onCreate = null) inline static
Type Constraints
T : new()
Definition at line 113 of file ObjectPool.cs.
                                                                                                               : new()
    {
        Item<T> item = new Item<T>();
        item.Create(max, addsPerUpdate);
        item.onCreate = _onCreate;
        Instance.items.Add(item);
        return item;
    }
References ObjectPool< T >.Instance, item, and ObjectPool< T >.items.
Get()
T ObjectPool< T >.Get () inline
Definition at line 25 of file ObjectPool.cs.
    {
        T val;
        if (m_Stack.Count == 0)
        {
            val = new T();
            countAll++;
        }
        else
        {
            val = m_Stack.Pop();
        }
        if (m_ActionOnGet != null)
        {
            m_ActionOnGet(val);
        }
        return val;
    }
References ObjectPool< T >.countAll, ObjectPool< T >.m_ActionOnGet, and ObjectPool< T >.m_Stack.
Referenced by ListPool< T >.Get().
Release()
void ObjectPool< T >.Release (T element) inline
Definition at line 44 of file ObjectPool.cs.
    {
        if (m_Stack.Count > 0 && (object)m_Stack.Peek() == (object)element)
        {
            Debug.LogError("Internal error. Trying to destroy object that is already released to pool.");
        }
        if (m_ActionOnRelease != null)
        {
            m_ActionOnRelease(element);
        }
        m_Stack.Push(element);
    }
References Debug, ObjectPool< T >.m_ActionOnRelease, and ObjectPool< T >.m_Stack.
Referenced by ListPool< T >.Release().
Update()
void ObjectPool< T >.Update () inline private
Definition at line 105 of file ObjectPool.cs.
    {
        foreach (IItem item in items)
        {
            item.Update();
        }
    }
References item, and ObjectPool< T >.items.
Member Data Documentation
Instance
ObjectPool ObjectPool< T >.Instance static
Definition at line 96 of file ObjectPool.cs.
Referenced by ObjectPool< T >.Awake(), ObjectPool< T >.Item< T >.Create(), and ObjectPool< T >.Create< T >().
items
List<IItem> ObjectPool< T >.items = new List<IItem>()
Definition at line 98 of file ObjectPool.cs.
Referenced by ObjectPool< T >.Create< T >(), and ObjectPool< T >.Update().
m_ActionOnGet
readonly UnityAction<T> ObjectPool< T >.m_ActionOnGet private
Definition at line 9 of file ObjectPool.cs.
Referenced by ObjectPool< T >.Get(), and ObjectPool< T >.ObjectPool().
m_ActionOnRelease
readonly UnityAction<T> ObjectPool< T >.m_ActionOnRelease private
Definition at line 11 of file ObjectPool.cs.
Referenced by ObjectPool< T >.ObjectPool(), and ObjectPool< T >.Release().
m_Stack
readonly Stack<T> ObjectPool< T >.m_Stack = new Stack<T>() private
Definition at line 7 of file ObjectPool.cs.
Referenced by ObjectPool< T >.Get(), and ObjectPool< T >.Release().
Property Documentation
countActive
int ObjectPool< T >.countActive get
Definition at line 15 of file ObjectPool.cs.
countAll
int ObjectPool< T >.countAll get private set
Definition at line 13 of file ObjectPool.cs.
{ get; private set; }
Referenced by ObjectPool< T >.Get().
countInactive
int ObjectPool< T >.countInactive get
Definition at line 17 of file ObjectPool.cs.
The documentation for this class was generated from the following files:
Elin/Plugins.basecore/ObjectPool.cs
Elin/Plugins.UI/ObjectPool.cs