Elin Decompiled Documentation: HomeResourceWorth Class Reference
HomeResourceWorth Class Reference
Public Member Functions
void UpdateRank ()
override void Refresh ()
int GetPrice (Thing t, bool top=false)
override int GetDestValue ()
List< Thing > ListHeirloom ()
override void WriteNote (UINote n)
Public Member Functions inherited from HomeResourceRate
override void Refresh ()
override void OnAdvanceDay ()
virtual int GetDestValue ()
Public Member Functions inherited from BaseHomeResource
virtual T Create< T > (HomeResourceType _type, int _value)
virtual void Mod (int a, bool popText=true)
virtual void Refresh ()
void OnRefreshEffect ()
virtual void OnAdvanceHour ()
virtual void OnAdvanceDay ()
virtual void WriteNote (UINote n)
Public Attributes
int bestRank
Public Attributes inherited from BaseHomeResource
HomeResourceType type
int value
int lastValue
FactionBranch branch
Properties
override bool IsAvailable [get]
Properties inherited from HomeResourceRate
override bool IsAvailable [get]
override BaseHomeResource.ResourceGroup Group [get]
Properties inherited from BaseHomeResource
SourceHomeResource.Row source [get]
virtual int Min [get]
virtual int Max [get]
bool IsCurrency [get]
bool IsRate [get]
bool IsSkill [get]
virtual bool IsAvailable [get]
virtual float ExpRatio [get]
virtual BaseHomeResource.ResourceGroup Group [get]
string Name [get]
Sprite Sprite [get]
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Additional Inherited Members
Public Types inherited from BaseHomeResource
enum ResourceGroup { Currency , Skill , Rate , None }
Static Public Member Functions inherited from EClass
static int rnd (int a)
static int curve (int a, int start, int step, int rate=75)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Static Public Attributes inherited from EClass
static Core core
Detailed Description
Definition at line 6 of file HomeResourceWorth.cs.
Member Function Documentation
GetDestValue()
override int HomeResourceWorth.GetDestValue () inline virtual
Reimplemented from HomeResourceRate.
Definition at line 51 of file HomeResourceWorth.cs.
    {
        List<Thing> list = this.ListHeirloom();
        int num = 0;
        foreach (Thing thing in list)
        {
            num += this.GetPrice(thing, list[0] == thing);
        }
        return num;
    }
References GetPrice(), and ListHeirloom().
GetPrice()
int HomeResourceWorth.GetPrice (Thing t, bool top = false) inline
Definition at line 37 of file HomeResourceWorth.cs.
    {
        int num = t.GetPrice(CurrencyType.Money, false, PriceType.Tourism, null);
        if (t.noSell)
        {
            num /= 50;
        }
        if (top && this.branch.policies.IsActive(2821, -1))
        {
            num = num * (150 + (int)Mathf.Sqrt((float)this.branch.Evalue(2821)) * 5) / 100;
        }
        return num;
    }
References BaseHomeResource.branch, FactionBranch.Evalue(), Card.GetPrice(), PolicyManager.IsActive(), Card.noSell, and FactionBranch.policies.
Referenced by GetDestValue(), ListHeirloom(), and WriteNote().
ListHeirloom()
List< Thing > HomeResourceWorth.ListHeirloom () inline
Definition at line 62 of file HomeResourceWorth.cs.
    {
        List<Thing> list = new List<Thing>();
        List<Thing> list2 = new List<Thing>();
        HashSet<string> hashSet = new HashSet<string>();
        int[] array = new int[EClass._map.SizeXZ];
        int num = 0;
        int num2 = this.branch.Evalue(2814);
        int num3 = this.branch.Evalue(2823);
        foreach (Thing thing in EClass._map.things)
        {
            if (thing.IsInstalled)
            {
                if (thing.HasTag(CTAG.tourism))
                {
                    bool flag = thing.trait is TraitFigure;
                    if (flag)
                    {
                        if (array[thing.pos.index] != 0)
{
                            continue;
                        }
                        array[thing.pos.index]++;
                    }
                    int num4 = 1;
                    string item;
                    if (flag)
                    {
                        item = "figure_" + thing.c_idRefCard;
                        num4 = 2;
                    }
                    else
                    {
                        item = thing.id + "_" + thing.idSkin.ToString();
                    }
                    if (!hashSet.Contains(item))
                    {
                        int num5 = this.GetPrice(thing, false) * num4;
                        if (num3 > 0)
{
                            num5 = num5 * (110 + (int)Mathf.Sqrt((float)num3) * 4) / 100;
                        }
                        num += num5;
                        hashSet.Add(item);
                    }
                    else if (num2 > 0)
                    {
                        int num6 = this.GetPrice(thing, false) * num4 / Mathf.Max(20, 30 - (int)Mathf.Sqrt((float)num2));
                        if (num6 > 0)
{
                            num += num6;
                        }
                    }
                }
                if (thing.IsFurniture || thing.trait is TraitToolMusic)
                {
                    list2.Add(thing);
                }
            }
        }
        int num7 = this.branch.Evalue(3780) + this.branch.Evalue(3781) + this.branch.Evalue(3782) + this.branch.Evalue(3783) + this.branch.Evalue(3784);
        this.branch.tourism = (100 + num) * (100 + num7 * 15) / 100;
        list2.Sort((Thing a, Thing b) => this.GetPrice(b, false) - this.GetPrice(a, false));
        int num8 = 0;
        while (num8 < this.branch.NumHeirloom && num8 < list2.Count)
        {
            list.Add(list2[num8]);
            num8++;
        }
        return list;
    }
References EClass._map, BaseHomeResource.branch, Card.c_idRefCard, FactionBranch.Evalue(), GetPrice(), Card.HasTag(), Card.idSkin, Point.index, Card.IsFurniture, Card.IsInstalled, FactionBranch.NumHeirloom, Card.pos, Map.SizeXZ, Map.things, and Card.trait.
Referenced by GetDestValue(), and WriteNote().
Refresh()
override void HomeResourceWorth.Refresh () inline virtual
Reimplemented from HomeResourceRate.
Definition at line 31 of file HomeResourceWorth.cs.
    {
        base.Refresh();
        this.UpdateRank();
    }
References UpdateRank().
UpdateRank()
void HomeResourceWorth.UpdateRank () inline
Definition at line 16 of file HomeResourceWorth.cs.
    {
        int rank = EClass.game.spatials.ranks.GetRank(this.branch.owner);
        if (this.bestRank == 0)
        {
            this.bestRank = rank;
        }
        if (rank < this.bestRank)
        {
            this.bestRank = rank;
            EClass.Sound.Play((rank <= 50) ? "clap3" : ((rank <= 100) ? "clap2" : "clap1"));
            Msg.Say("homerank_up", EClass.game.spatials.ranks.GetRankText(this.branch.owner), null, null, null);
        }
    }
References bestRank, BaseHomeResource.branch, EClass.game, RankedZoneManager.GetRank(), RankedZoneManager.GetRankText(), FactionBranch.owner, SpatialManager.ranks, Msg.Say(), EClass.Sound, and Game.spatials.
Referenced by Refresh().
WriteNote()
override void HomeResourceWorth.WriteNote (UINote n) inline virtual
Reimplemented from BaseHomeResource.
Definition at line 134 of file HomeResourceWorth.cs.
    {
        n.Clear();
        n.AddHeader(base.Name, null);
        n.AddTopic("TopicLeft", "vCurrent".lang(), this.value.ToFormat() ?? "");
        n.AddTopic("TopicLeft", "tourism_value".lang(), this.branch.tourism.ToFormat() ?? "");
        n.Space(0, 1);
        n.AddHeader("HeaderTopic", "heirloom_list".lang(this.branch.NumHeirloom.ToString() ?? "", null, null, null, null), null);
        n.Space(1, 1);
        List<Thing> list = this.ListHeirloom();
        for (int i = 0; i < list.Count; i++)
        {
            Thing thing = list[i];
            string str = (i + 1).ToString();
            string str2 = ": ";
            string name = thing.Name;
            object obj = EClass.debug.showExtra ? this.GetPrice(thing, i == 0) : "";
            n.AddText(str + str2 + name + ((obj != null) ? obj.ToString() : null), FontColor.DontChange);
        }
        n.Build();
    }
References BaseHomeResource.branch, GetPrice(), ListHeirloom(), Card.Name, FactionBranch.NumHeirloom, FactionBranch.tourism, and BaseHomeResource.value.
Referenced by UIHomeInfo.RefreshInfo().
Member Data Documentation
bestRank
int HomeResourceWorth.bestRank
Definition at line 157 of file HomeResourceWorth.cs.
Referenced by TraitCoreZone.TrySetAct(), and UpdateRank().
Property Documentation
IsAvailable
override bool HomeResourceWorth.IsAvailable get
Definition at line 8 of file HomeResourceWorth.cs.
    {
        get
        {
            return false;
        }
    }
The documentation for this class was generated from the following file:
Elin/HomeResourceWorth.cs