Elin Decompiled Documentation: ZoneEventRaid Class Reference
ZoneEventRaid Class Reference
Public Member Functions
override void OnInit ()
override Point GetSpawnPos ()
override void OnKill ()
Public Member Functions inherited from ZoneEventSiege
virtual Chara CreateChara (Point p, bool boss=false)
override void OnInit ()
override void OnVisit ()
void SpawnMob ()
virtual Point GetSpawnPos ()
override void OnTickRound ()
override void OnCharaDie (Chara c)
bool ShouldEnd ()
override void OnKill ()
Public Member Functions inherited from ZoneEvent
virtual string GetText ()
void Tick (float delta)
void Init ()
void OnSimulateHour ()
virtual void OnVisit ()
virtual void OnInit ()
virtual void OnFirstTick ()
virtual void OnTick ()
virtual void OnTickRound ()
virtual void OnKill ()
virtual void OnCharaDie (Chara c)
virtual void OnLeaveZone ()
virtual void OnLoad ()
void Kill ()
Additional Inherited Members
Static Public Member Functions inherited from EClass
static int rndSeed (int a, int seed)
static int rnd (long a)
static int rnd (int a)
static int curve (int a, int start, int step, int rate=75)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Public Attributes inherited from ZoneEventSiege
List< int > uids = new List<int>()
int lv = 10
int idx
int max = 10
List< Chara > members = new List<Chara>()
Public Attributes inherited from ZoneEvent
float time
int rounds
int hoursElapsed
int minElapsed
Zone zone
bool firstTick = true
Static Public Attributes inherited from EClass
static Core core
Properties inherited from ZoneEventSiege
override string id [get]
override float roundInterval [get]
override Playlist playlist [get]
Properties inherited from ZoneEvent
SourceQuest.Row source [get]
virtual string id [get]
virtual string TextWidgetDate [get]
virtual float roundInterval [get]
virtual Playlist playlist [get]
virtual bool debugSkip [get]
virtual string RefStr2 [get]
virtual string RefStr3 [get]
virtual int hoursToKill [get]
virtual bool HasReport [get]
string Name [get]
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Detailed Description
Definition at line 3 of file ZoneEventRaid.cs.
Member Function Documentation
GetSpawnPos()
override Point ZoneEventRaid.GetSpawnPos () inline virtual
Reimplemented from ZoneEventSiege.
Definition at line 12 of file ZoneEventRaid.cs.
    {
        Trait trait = EClass._map.FindThing<TraitVoidgate>();
        if (trait != null)
        {
            trait.Toggle(on: true, silent: true);
        }
        else
        {
            trait = EClass._map.FindThing<TraitCoreDefense>();
        }
        Point point = ((trait != null) ? trait.owner.pos : EClass.pc.pos);
        return point.GetNearestPoint(allowBlock: false, allowChara: false) ?? point;
    }
References EClass._map, Map.FindThing(), Point.GetNearestPoint(), Trait.owner, EClass.pc, Card.pos, and Trait.Toggle().
OnInit()
override void ZoneEventRaid.OnInit () inline virtual
Reimplemented from ZoneEvent.
Definition at line 5 of file ZoneEventRaid.cs.
    {
        lv = Mathf.Max(1, EClass.game.survival.flags.raidLv);
        max = 5 + lv / 5;
        base.OnInit();
    }
References SurvivalManager.flags, EClass.game, ZoneEventSiege.lv, ZoneEventSiege.max, SurvivalManager.Flags.raidLv, and Game.survival.
OnKill()
override void ZoneEventRaid.OnKill () inline virtual
Reimplemented from ZoneEvent.
Definition at line 27 of file ZoneEventRaid.cs.
    {
        base.OnKill();
        EClass.game.survival.flags.raidRound++;
        EClass.game.survival.flags.raidLv += 5;
        EClass.game.survival.flags.dateNextRaid = EClass.world.date.GetRaw(168);
        Point pos = EClass.game.survival.GetRandomPoint() ?? EClass.pc.pos;
        string text = ((EClass.game.survival.flags.raidLv >= 50 && EClass.rnd(3) == 0) ? "statue_god" : ((EClass.game.survival.flags.raidLv >= 25 && EClass.rnd(2) == 0) ? "statue_power" : "altar"));
        EClass.game.survival.MeteorThing(pos, text, install: true);
    }
References World.date, SurvivalManager.flags, EClass.game, SurvivalManager.GetRandomPoint(), Date.GetRaw(), SurvivalManager.MeteorThing(), EClass.pc, Card.pos, SurvivalManager.Flags.raidLv, SurvivalManager.Flags.raidRound, EClass.rnd(), Game.survival, and EClass.world.
The documentation for this class was generated from the following file:
Elin/ZoneEventRaid.cs