Elin Decompiled Documentation: SpriteReplacer Class Reference
SpriteReplacer Class Reference
Public Member Functions
Sprite GetSprite (string suffix="")
Sprite GetSprite (int dir, int skin, bool snow)
void Validate ()
void ReloadBuiltInTextures ()
void BuildSuffixData (string id, Dictionary< string, string > dictTexItems)
void Reload (string id, RenderData renderData=null)
bool HasSprite (string id, RenderData renderData=null)
Static Public Member Functions
static Dictionary< string, SpriteReplacer > ListSkins ()
Public Attributes
SpriteData data
Dictionary< string, SpriteData > suffixes = new Dictionary<string, SpriteData>()
Dictionary< string, bool > isChecked = new Dictionary<string, bool>()
Static Public Attributes
static Dictionary< string, SpriteReplacer > dictSkins = new Dictionary<string, SpriteReplacer>()
static Dictionary< string, string > dictModItems = new Dictionary<string, string>()
static Dictionary< string, string > dictTextureItems = new Dictionary<string, string>()
Detailed Description
Definition at line 7 of file SpriteReplacer.cs.
Member Function Documentation
BuildSuffixData()
void SpriteReplacer.BuildSuffixData (string id, Dictionary< string, string > dictTexItems) inline
Definition at line 112 of file SpriteReplacer.cs.
    {
        foreach (var (text3, path) in dictTexItems)
        {
            if (text3.StartsWith(id))
            {
                string text4 = text3[id.Length..];
                SpriteData spriteData = new SpriteData
                {
                    path = path
                };
                spriteData.Init();
                suffixes[text4] = spriteData;
                Debug.Log("#sprite replacer init '" + text4 + "' at " + path.ShortPath());
            }
        }
    }
References Debug, SpriteData.Init(), and suffixes.
Referenced by Reload().
GetSprite() [1/2]
Sprite SpriteReplacer.GetSprite (int dir, int skin, bool snow) inline
Definition at line 71 of file SpriteReplacer.cs.
    {
        foreach (string item in new List<string>
        {
            $"_skin{skin}_dir{dir}",
            $"_skin{skin}",
            $"_dir{dir}",
            ""
        })
        {
            Sprite sprite = null;
            if (snow)
            {
                sprite = GetSprite(item + "_snow");
            }
            if ((object)sprite == null)
            {
                sprite = GetSprite(item);
            }
            if ((bool)sprite)
            {
                return sprite;
            }
        }
        return data?.GetSprite();
    }
References $, data, SpriteData.GetSprite(), GetSprite(), and item.
GetSprite() [2/2]
Sprite SpriteReplacer.GetSprite (string suffix = "") inline
Definition at line 62 of file SpriteReplacer.cs.
    {
        if (!suffixes.TryGetValue(suffix, out var value))
        {
            return null;
        }
        return value.GetSprite();
    }
References suffixes.
Referenced by GetSprite(), Chara.GetSprite(), and RenderRow.GetSprite().
HasSprite()
bool SpriteReplacer.HasSprite (string id, RenderData renderData = null) inline
Definition at line 169 of file SpriteReplacer.cs.
    {
        if (!isChecked.GetValueOrDefault(id) || (data != null && data.id != id))
        {
            Reload(id, renderData);
        }
        return data != null;
    }
References data, SpriteData.id, isChecked, and Reload().
Referenced by RenderRow.GetSprite(), and CardActor.OnRender().
ListSkins()
static Dictionary< string, SpriteReplacer > SpriteReplacer.ListSkins () inline static
Definition at line 21 of file SpriteReplacer.cs.
    {
        List<string> list = new List<string>();
        foreach (KeyValuePair<string, SpriteReplacer> dictSkin in dictSkins)
        {
            if (!File.Exists(dictSkin.Value.data.path + ".png"))
            {
                list.Add(dictSkin.Key);
            }
        }
        foreach (string item in list)
        {
            dictSkins.Remove(item);
        }
        Dictionary<string, string> dictionary = new DirectoryInfo(CorePath.custom + "Skin").GetFiles("*.png").ToDictionary((FileInfo f) => Path.GetFileNameWithoutExtension(f.Name), (FileInfo f) => Path.ChangeExtension(f.FullName, null));
        string key2;
        foreach (KeyValuePair<string, string> item2 in dictionary)
        {
            item2.Deconstruct(out var key, out key2);
            string key3 = key;
            string path = key2;
            if (!dictSkins.ContainsKey(key3))
            {
                dictSkins[key3] = new SpriteReplacer
                {
                    data = new SpriteData
                    {
                        path = path
                    }
                };
            }
        }
        foreach (KeyValuePair<string, SpriteReplacer> dictSkin2 in dictSkins)
        {
            dictSkin2.Deconstruct(out key2, out var value);
            string id = key2;
            value.BuildSuffixData(id, dictionary);
        }
        return dictSkins;
    }
References CorePath.custom, data, dictSkins, and item.
Referenced by LayerEditSkin.RefreshList().
Reload()
void SpriteReplacer.Reload (string id, RenderData renderData = null) inline
Definition at line 130 of file SpriteReplacer.cs.
    {
        data = null;
        suffixes.Clear();
        try
        {
            if (dictModItems.ContainsKey(id))
            {
                BuildSuffixData(id, dictModItems);
            }
            else
            {
                if (dictTextureItems.Count == 0)
                {
                    ReloadBuiltInTextures();
                }
                string text = dictTextureItems.TryGetValue(id);
                if (text == null && renderData != null)
                {
                    text = dictTextureItems.TryGetValue(renderData.name);
                }
                if (text != null)
                {
                    BuildSuffixData(id, dictTextureItems);
                }
            }
            data = suffixes.TryGetValue("");
            if (data != null)
            {
                Debug.Log(id + ":" + data.path);
            }
        }
        catch (Exception ex)
        {
            Debug.LogError("#sprite error fetching sprite replacer:" + ex);
        }
        isChecked[id] = true;
    }
References BuildSuffixData(), data, Debug, dictModItems, dictTextureItems, isChecked, SpriteData.path, ReloadBuiltInTextures(), and suffixes.
Referenced by HasSprite().
ReloadBuiltInTextures()
void SpriteReplacer.ReloadBuiltInTextures () inline
Definition at line 107 of file SpriteReplacer.cs.
    {
        dictTextureItems = new DirectoryInfo(CorePath.packageCore + "Texture/Item").GetFiles("*.png").ToDictionary((FileInfo f) => Path.GetFileNameWithoutExtension(f.Name), (FileInfo f) => Path.ChangeExtension(f.FullName, null));
    }
References dictTextureItems, and CorePath.packageCore.
Referenced by Reload().
Validate()
void SpriteReplacer.Validate () inline
Definition at line 98 of file SpriteReplacer.cs.
    {
        data?.Validate();
        foreach (SpriteData value in suffixes.Values)
        {
            value?.Validate();
        }
    }
References data, suffixes, and SpriteData.Validate().
Member Data Documentation
data
SpriteData SpriteReplacer.data
Definition at line 15 of file SpriteReplacer.cs.
Referenced by CardRenderer.GetPref(), GetSprite(), HasSprite(), ListSkins(), CardActor.OnRender(), LayerEditSkin.RefreshImage(), LayerEditSkin.RefreshList(), Reload(), Card.SetImage(), CharaRenderer.SetOwner(), and Validate().
dictModItems
Dictionary<string, string> SpriteReplacer.dictModItems = new Dictionary<string, string>() static
Definition at line 11 of file SpriteReplacer.cs.
Referenced by ModPackage.ParseTexture(), and Reload().
dictSkins
Dictionary<string, SpriteReplacer> SpriteReplacer.dictSkins = new Dictionary<string, SpriteReplacer>() static
Definition at line 9 of file SpriteReplacer.cs.
Referenced by ListSkins(), Core.OnApplicationFocus(), Card.SetImage(), and CharaRenderer.SetOwner().
dictTextureItems
Dictionary<string, string> SpriteReplacer.dictTextureItems = new Dictionary<string, string>() static
Definition at line 13 of file SpriteReplacer.cs.
Referenced by Reload(), and ReloadBuiltInTextures().
isChecked
Dictionary<string, bool> SpriteReplacer.isChecked = new Dictionary<string, bool>()
Definition at line 19 of file SpriteReplacer.cs.
Referenced by HasSprite(), and Reload().
suffixes
Dictionary<string, SpriteData> SpriteReplacer.suffixes = new Dictionary<string, SpriteData>()
Definition at line 17 of file SpriteReplacer.cs.
Referenced by BuildSuffixData(), GetSprite(), CardActor.OnRender(), Reload(), and Validate().
The documentation for this class was generated from the following file:
Elin/SpriteReplacer.cs