Elin Decompiled Documentation: ResearchManager Class Reference
ResearchManager Class Reference
Public Member Functions
void SetOwner (FactionBranch _branch)
void OnSimulateDay ()
void TryAddPlans (string idResource, int lv)
bool IsListBarter (string idPlan)
bool HasPlan (string idPlan)
bool IsComplete (string id, int rank=-1)
void AddPlan (string id)
void AddPlan (ResearchPlan p)
bool CanCompletePlan (ResearchPlan p)
void CompletePlan (ResearchPlan p)
void ShowNewPlans (Action onComplete=null)
Public Attributes
List< ResearchPlan > plans = new List<ResearchPlan>()
List< ResearchPlan > finished = new List<ResearchPlan>()
List< ResearchPlan > newPlans = new List<ResearchPlan>()
ResearchPlan focused
FactionBranch branch
Additional Inherited Members
Static Public Member Functions inherited from EClass
static int rnd (int a)
static int curve (int a, int start, int step, int rate=75)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Static Public Attributes inherited from EClass
static Core core
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Detailed Description
Definition at line 6 of file ResearchManager.cs.
Member Function Documentation
AddPlan() [1/2]
void ResearchManager.AddPlan (ResearchPlan p) inline
Definition at line 92 of file ResearchManager.cs.
    {
        p.SetOwner(this.branch);
        this.plans.Add(p);
        this.newPlans.Add(p);
        WidgetPopText.Say("rewardPlan".lang(p.Name, null, null, null, null), FontColor.Default, null);
    }
References branch, ResearchPlan.Name, newPlans, plans, WidgetPopText.Say(), and ResearchPlan.SetOwner().
AddPlan() [2/2]
void ResearchManager.AddPlan (string id) inline
Definition at line 87 of file ResearchManager.cs.
    {
        this.AddPlan(ResearchPlan.Create(id));
    }
References AddPlan(), and ResearchPlan.Create().
Referenced by AddPlan(), ShowNewPlans(), and TryAddPlans().
CanCompletePlan()
bool ResearchManager.CanCompletePlan (ResearchPlan p) inline
Definition at line 100 of file ResearchManager.cs.
    {
        return this.branch.resources.knowledge.value >= p.source.tech;
    }
References ResearchPlan.source.
Referenced by ItemResearch.SetPlan().
CompletePlan()
void ResearchManager.CompletePlan (ResearchPlan p) inline
Definition at line 105 of file ResearchManager.cs.
    {
        if (this.focused == p)
        {
            this.focused = null;
        }
        p.OnComplete();
        WidgetPopText.Say("completePlan".lang(p.Name, null, null, null, null), FontColor.Great, null);
        if (p.source.maxLv > p.rank)
        {
            p.rank++;
            p.exp = (p.lastExp = 0);
            SE.Play("good");
            return;
        }
        this.plans.Remove(p);
        this.finished.Add(p);
        SE.Play("good");
    }
References finished, focused, ResearchPlan.Name, ResearchPlan.OnComplete(), plans, ResearchPlan.rank, WidgetPopText.Say(), and ResearchPlan.source.
Referenced by ItemResearch.SetPlan().
HasPlan()
bool ResearchManager.HasPlan (string idPlan) inline
Definition at line 47 of file ResearchManager.cs.
    {
        using (IEnumerator<ResearchPlan> enumerator = this.plans.Concat(this.finished).GetEnumerator())
        {
            while (enumerator.MoveNext())
            {
                if (enumerator.Current.id == idPlan)
                {
                    return true;
                }
            }
        }
        return false;
    }
References finished, and plans.
Referenced by IsListBarter().
IsComplete()
bool ResearchManager.IsComplete (string id, int rank = -1) inline
Definition at line 62 of file ResearchManager.cs.
    {
        using (List<ResearchPlan>.Enumerator enumerator = this.finished.GetEnumerator())
        {
            while (enumerator.MoveNext())
            {
                if (enumerator.Current.source.id == id)
                {
                    return true;
                }
            }
        }
        if (rank != -1)
        {
            foreach (ResearchPlan researchPlan in this.plans)
            {
                if (researchPlan.source.id == id && researchPlan.rank >= rank)
                {
                    return true;
                }
            }
        }
        return false;
    }
References finished, plans, ResearchPlan.rank, and ResearchPlan.source.
IsListBarter()
bool ResearchManager.IsListBarter (string idPlan) inline
Definition at line 41 of file ResearchManager.cs.
    {
        SourceResearch.Row row = EClass.sources.researches.map[idPlan];
        return row.money > 0 && !this.branch.researches.HasPlan(row.id);
    }
References branch, HasPlan(), SourceResearch.Row.id, FactionBranch.researches, SourceManager.researches, and EClass.sources.
OnSimulateDay()
void ResearchManager.OnSimulateDay () inline
Definition at line 21 of file ResearchManager.cs.
    {
        this.newPlans.Clear();
    }
References newPlans.
SetOwner()
void ResearchManager.SetOwner (FactionBranch _branch) inline
Definition at line 8 of file ResearchManager.cs.
    {
        this.branch = _branch;
        foreach (ResearchPlan researchPlan in this.plans)
        {
            researchPlan.SetOwner(_branch);
        }
        foreach (ResearchPlan researchPlan2 in this.finished)
        {
            researchPlan2.SetOwner(_branch);
        }
    }
References finished, plans, and ResearchPlan.SetOwner().
Referenced by FactionBranch.SetOwner().
ShowNewPlans()
void ResearchManager.ShowNewPlans (Action onComplete = null) inline
Definition at line 125 of file ResearchManager.cs.
    {
        Rand.SetSeed(EClass.game.seed + this.branch.seedPlan);
        List<ResearchPlan> list = new List<ResearchPlan>();
        foreach (SourceResearch.Row row in EClass.sources.researches.rows)
        {
            list.Add(ResearchPlan.Create(row.id));
        }
        Rand.SetSeed(-1);
        foreach (ResearchPlan researchPlan in list)
        {
        }
        EClass.core.ui.AddLayer<LayerList>().SetSize(450f, -1f).SetList2<ResearchPlan>(list, (ResearchPlan p) => p.Name, delegate(ResearchPlan p, ItemGeneral b)
        {
            this.branch.seedPlan++;
            this.branch.researches.AddPlan(p);
            Action onComplete2 = onComplete;
            if (onComplete2 == null)
            {
                return;
            }
            onComplete2();
        }, delegate(ResearchPlan p, ItemGeneral b)
        {
        }, true);
    }
References AddPlan(), branch, EClass.core, ResearchPlan.Create(), EClass.game, FactionBranch.researches, SourceManager.researches, Game.seed, FactionBranch.seedPlan, and EClass.sources.
TryAddPlans()
void ResearchManager.TryAddPlans (string idResource, int lv) inline
Definition at line 26 of file ResearchManager.cs.
    {
        IEnumerable<SourceResearch.Row> rows = EClass.sources.researches.rows;
        Func<SourceResearch.Row, bool> <>9__0;
        Func<SourceResearch.Row, bool> predicate;
        if ((predicate = <>9__0) == null)
        {
            predicate = (<>9__0 = ((SourceResearch.Row r) => r.resource.Length > 1 && r.resource[0] == idResource && r.resource[1].ToInt() == lv));
        }
        foreach (SourceResearch.Row row in rows.Where(predicate))
        {
            this.AddPlan(row.id);
        }
    }
References AddPlan(), SourceManager.researches, and EClass.sources.
Member Data Documentation
branch
FactionBranch ResearchManager.branch
Definition at line 164 of file ResearchManager.cs.
Referenced by AddPlan(), IsListBarter(), and ShowNewPlans().
finished
List<ResearchPlan> ResearchManager.finished = new List<ResearchPlan>()
Definition at line 156 of file ResearchManager.cs.
Referenced by CompletePlan(), HasPlan(), IsComplete(), LayerTech.RefreshTech(), LayerHome.RefreshTech(), and SetOwner().
focused
ResearchPlan ResearchManager.focused
Definition at line 162 of file ResearchManager.cs.
Referenced by CompletePlan(), LayerHome.RefreshFocus(), LayerTech.RefreshFocus(), and ItemResearch.SetPlan().
newPlans
List<ResearchPlan> ResearchManager.newPlans = new List<ResearchPlan>()
Definition at line 159 of file ResearchManager.cs.
Referenced by AddPlan(), OnSimulateDay(), and UIHomeInfo.RefreshReport().
plans
List<ResearchPlan> ResearchManager.plans = new List<ResearchPlan>()
Definition at line 153 of file ResearchManager.cs.
Referenced by AddPlan(), CompletePlan(), HasPlan(), IsComplete(), UIHomeInfo.RefreshReport(), LayerTech.RefreshTech(), SetOwner(), and ItemResearch.SetPlan().
The documentation for this class was generated from the following file:
Elin/ResearchManager.cs