Elin Decompiled Documentation: ResearchPlan Class Reference
ResearchPlan Class Reference
Public Member Functions
void SetOwner (FactionBranch _branch)
void GainExp (int a)
int GetSortVal (UIList.SortMode m)
void WriteNote (UINote n)
void OnComplete ()
void ParseReward (UINote n=null)
Static Public Member Functions
static ResearchPlan Create (string id)
Static Public Member Functions inherited from EClass
static int rndSeed (int a, int seed)
static int rnd (int a)
static int curve (int a, int start, int step, int rate=75)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Public Attributes
string id
int exp
int lastExp
int rank = 1
FactionBranch branch
Properties
SourceResearch.Row source [get]
string Name [get]
int MaxExp [get]
bool IsComplete [get]
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Additional Inherited Members
Static Public Attributes inherited from EClass
static Core core
Detailed Description
Definition at line 7 of file ResearchPlan.cs.
Member Function Documentation
Create()
static ResearchPlan ResearchPlan.Create (string id) inline static
Definition at line 131 of file ResearchPlan.cs.
    {
        return new ResearchPlan
        {
            id = id
        };
    }
Referenced by ResearchManager.AddPlan(), and ResearchManager.ShowNewPlans().
GainExp()
void ResearchPlan.GainExp (int a) inline
Definition at line 36 of file ResearchPlan.cs.
    {
        exp += a;
        if (exp > MaxExp)
        {
            exp = MaxExp;
        }
    }
References exp, and MaxExp.
GetSortVal()
int ResearchPlan.GetSortVal (UIList::SortMode m) inline
Definition at line 45 of file ResearchPlan.cs.
    {
        if (IsComplete)
        {
            return 0;
        }
        return -10;
    }
References IsComplete.
Referenced by LayerTech.RefreshTech(), and LayerHome.RefreshTech().
OnComplete()
void ResearchPlan.OnComplete () inline
Definition at line 65 of file ResearchPlan.cs.
    {
        ParseReward();
    }
References ParseReward().
Referenced by ResearchManager.CompletePlan().
ParseReward()
void ResearchPlan.ParseReward (UINote n = null) inline
Definition at line 70 of file ResearchPlan.cs.
    {
        bool flag = n == null;
        string reward = source.reward;
        if (reward.IsEmpty())
        {
            return;
        }
        string[] array = reward.Split(Environment.NewLine.ToCharArray());
        string text = array[0];
        string[] array2 = array;
        foreach (string text2 in array2)
        {
            if (text2.Split(',')[0].ToInt() <= rank)
            {
                text = text2;
            }
        }
        List<string> list = text.Split(',').ToList();
        list.RemoveAt(0);
        foreach (string item in list)
        {
            string[] array3 = item.Split('/');
            string text3 = "";
            switch (array3[0])
            {
            case "r":
                text3 = "rewardRecipe".lang(EClass.sources.cards.map[array3[1]].GetName());
                if (flag)
                {
                    EClass.player.recipes.Add(array3[1]);
                }
                break;
            case "p":
                text3 = "rewardPolicy".lang(EClass.sources.elements.alias[array3[1]].GetName());
                if (flag)
                {
                    branch.policies.AddPolicy(array3[1]);
                }
                break;
            case "e":
            {
                Element element = Element.Create(array3[1], array3[2].ToInt());
                text3 = "rewardElement".lang(EClass.sources.elements.alias[array3[1]].GetName(), array3[2]);
                if (flag)
                {
                    branch.AddFeat(element.id, element.Value);
                }
                break;
            }
            case "department":
                text3 = "rewardDepartment".lang(source.GetName());
                break;
            }
            if (n != null)
            {
                n.AddText(text3);
            }
        }
    }
References RecipeManager.Add(), FactionBranch.AddFeat(), PolicyManager.AddPolicy(), branch, SourceManager.cards, Element.Create(), SourceManager.elements, Element.id, item, SourceCard.map, EClass.player, FactionBranch.policies, rank, Player.recipes, source, EClass.sources, and Element.Value.
Referenced by OnComplete(), and WriteNote().
SetOwner()
void ResearchPlan.SetOwner (FactionBranch _branch) inline
Definition at line 31 of file ResearchPlan.cs.
    {
        branch = _branch;
    }
References branch.
Referenced by ResearchManager.AddPlan(), and ResearchManager.SetOwner().
WriteNote()
void ResearchPlan.WriteNote (UINote n) inline
Definition at line 54 of file ResearchPlan.cs.
    {
        n.Clear();
        n.AddHeader(Name);
        n.AddText("vRank".lang() + rank + " (" + Mathf.Clamp(exp * 100 / MaxExp, 0, 100) + "%)");
        n.AddText("vMaxRank".lang() + source.maxLv);
        n.AddHeader("researchEffect");
        ParseReward(n);
        n.Build();
    }
References UINote.AddHeader(), UINote.AddText(), UINote.Build(), UINote.Clear(), exp, MaxExp, Name, ParseReward(), rank, and source.
Referenced by ItemResearch.SetPlan().
Member Data Documentation
branch
FactionBranch ResearchPlan.branch
Definition at line 21 of file ResearchPlan.cs.
Referenced by ParseReward(), and SetOwner().
exp
int ResearchPlan.exp
Definition at line 13 of file ResearchPlan.cs.
Referenced by GainExp(), UIHomeInfo.RefreshReport(), and WriteNote().
id
string ResearchPlan.id
Definition at line 10 of file ResearchPlan.cs.
lastExp
int ResearchPlan.lastExp
Definition at line 16 of file ResearchPlan.cs.
rank
int ResearchPlan.rank = 1
Definition at line 19 of file ResearchPlan.cs.
Referenced by ResearchManager.CompletePlan(), ResearchManager.IsComplete(), ParseReward(), and WriteNote().
Property Documentation
IsComplete
bool ResearchPlan.IsComplete get
Definition at line 29 of file ResearchPlan.cs.
Referenced by GetSortVal().
MaxExp
int ResearchPlan.MaxExp get
Definition at line 27 of file ResearchPlan.cs.
Referenced by GainExp(), UIHomeInfo.RefreshReport(), and WriteNote().
Name
string ResearchPlan.Name get
Definition at line 25 of file ResearchPlan.cs.
Referenced by ResearchManager.AddPlan(), ResearchManager.CompletePlan(), UIHomeInfo.RefreshReport(), ItemResearch.SetPlan(), ResearchManager.ShowNewPlans(), and WriteNote().
source
SourceResearch.Row ResearchPlan.source get
Definition at line 23 of file ResearchPlan.cs.
Referenced by ResearchManager.CanCompletePlan(), ResearchManager.CompletePlan(), ResearchManager.IsComplete(), ParseReward(), ItemResearch.SetPlan(), and WriteNote().
The documentation for this class was generated from the following file:
Elin/ResearchPlan.cs