Elin Decompiled Documentation: CardRenderer Class Reference
CardRenderer Class Reference
Public Member Functions
Vector3 PositionCenter ()
virtual void SetOwner (Card c)
override void Draw (RenderParam p)
override void RenderToRenderCam (RenderParam p)
override void Draw (RenderParam p, ref Vector3 v, bool drawShadow)
virtual void UpdatePosition (ref Vector3 destPos, RenderParam p)
virtual void DrawHeld ()
void RefreshSprite ()
override void OnEnterScreen ()
void AddExtra (string id)
void RefreshExtra ()
void RemoveExtra (string id)
override void OnLeaveScreen ()
void KillActor ()
void PlayAnime (AnimeID id, bool force)
void PlayAnime (AnimeID id, Card dest)
void PlayAnime (AnimeID id, Point dest)
void PlayAnime (AnimeID id, Vector3 dest=default(Vector3), bool force=false)
virtual void KillAnime ()
virtual void IdleFrame ()
virtual void NextFrame ()
virtual void NextDir ()
T AddTC< T > (TC tc)
T GetTC< T > ()
TC GetTC (string id)
T GetOrCreateTC< T > (Func< T > func)
void RemoveTC< T > ()
void RemoveTC (TC tc)
void RemoveTC (int index)
void TrySpawnOrbit ()
bool IsTalking ()
TCSimpleText SpawnSimpleText ()
void DespawnSimpleText ()
void SetCensored (bool enable)
virtual void RefreshStateIcon ()
void Say (string text, Color c=default(Color), float duration=0f)
void ShowEmo (Emo emo, float duration=0f)
virtual void SetFirst (bool first, Vector3 pos)
virtual void SetFirst (bool first)
virtual void Refresh ()
virtual void OnEnterScreen ()
virtual void OnLeaveScreen ()
virtual void RenderToRenderCam (RenderParam p)
virtual void Draw (RenderParam p)
virtual void Draw (RenderParam p, ref Vector3 v, bool drawShadow)
void RenderToRenderCam (RenderParam p)
void Draw (RenderParam p)
void OnEnterScreen ()
void OnLeaveScreen ()
Public Attributes
TCOrbit orbit
Card owner
CardActor actor
bool hasActor
bool hasText
bool isChara
bool skip
Vector3 position
TransAnime anime
List< TC > listTC = new List<TC>()
TCSimpleText simpleText
RendererReplacer replacer
Public Attributes inherited from RenderObject
bool usePass
bool isSynced
long sync
RenderData data
Properties
virtual bool IsMoving [get]
Properties inherited from RenderObject
long Sync [get]
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Properties inherited from ISyncScreen
long Sync [get]
Additional Inherited Members
Static Public Member Functions inherited from EClass
static int rnd (int a)
static int curve (int a, int start, int step, int rate=75)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Static Public Attributes inherited from RenderObject
static float gameDelta
static float gameSpeed
static float altitudeFix
static GameSetting.RenderSetting.AnimeSetting animeSetting
static GameSetting.RenderSetting renderSetting
static RenderParam shared = new RenderParam()
static RenderParam currentParam
static Vector3 tempV
static bool enableAnime
static List< ISyncScreen > syncList
static long syncFrame
Static Public Attributes inherited from EClass
static Core core
Detailed Description
Definition at line 5 of file CardRenderer.cs.
Member Function Documentation
AddExtra()
void CardRenderer.AddExtra (string id) inline
Definition at line 406 of file CardRenderer.cs.
    {
        if (GetTC(id) == null)
        {
            TC tC = AddTC<TC>(PoolManager.Spawn<TC>("tcExtra_" + id, "Scene/Render/Actor/Component/Extra/" + id));
            if (tC.isUI)
            {
                tC.transform.SetParent(EClass.ui.rectDynamic, worldPositionStays: false);
            }
            tC.name = id;
        }
    }
References GetTC(), TC.isUI, PoolManager.Spawn(), and EClass.ui.
Referenced by RefreshExtra(), Trait.RefreshRenderer(), and TraitToolTorch.RefreshRenderer().
AddTC< T >()
T CardRenderer.AddTC< T > (TC tc) inline
Type Constraints
T : TC
Definition at line 548 of file CardRenderer.cs.
                                     : TC
    {
        listTC.Add(tc);
        tc.SetOwner(this);
        return tc as T;
    }
References listTC.
Referenced by GetOrCreateTC< T >().
DespawnSimpleText()
void CardRenderer.DespawnSimpleText () inline
Definition at line 663 of file CardRenderer.cs.
    {
        if (hasText)
        {
            PoolManager.Despawn(simpleText);
            hasText = false;
        }
    }
References PoolManager.Despawn(), hasText, and simpleText.
Referenced by OnLeaveScreen().
Draw() [1/2]
override void CardRenderer.Draw (RenderParam p) inline virtual
Reimplemented from RenderObject.
Definition at line 49 of file CardRenderer.cs.
    {
        Vector3 v = p.NewVector3;
        Draw(p, ref v, drawShadow: true);
    }
References Draw, and RenderParam.NewVector3.
Referenced by Draw(), CharaRenderer.DrawHeld(), BaseTileMap.DrawTile(), TileMapElona.DrawTile(), CharaActorPCC.OnRender(), and Card.RenderMarker().
Draw() [2/2]
override void CardRenderer.Draw (RenderParam p, ref Vector3 v, bool drawShadow) inline virtual
Reimplemented from RenderObject.
Reimplemented in CharaRenderer.
Definition at line 68 of file CardRenderer.cs.
    {
        if (skip)
        {
            skip = false;
            return;
        }
        sync = RenderObject.syncFrame;
        RenderObject.currentParam = p;
        p.dir = owner.dir;
        if (!isSynced)
        {
            OnEnterScreen();
            RenderObject.syncList.Add(this);
        }
        if ((bool)orbit)
        {
            orbit.Refresh();
        }
        else
        {
            TrySpawnOrbit();
        }
        if (isChara && owner.parent == EClass.game.activeZone)
        {
            if (owner.Chara.bossText && !EClass.ui.IsActive && !SplashText.Instance)
            {
                SplashText splashText = Util.Instantiate<SplashText>("Media/Text/SplashText_boss2", EClass.ui.rectDynamic);
                string text = owner.Chara.Aka.ToTitleCase(wholeText: true);
                string text2 = owner.Chara.NameSimple.ToTitleCase();
                if (!Lang.isBuiltin && Lang.langCode != "CN")
                {
                    text = owner.Chara.source.aka.ToTitleCase(wholeText: true);
                    text2 = owner.Chara.source.name.ToTitleCase();
                }
                splashText.textSmall.text = text;
                splashText.textBig.text = text2;
                owner.Chara.bossText = false;
            }
            if (owner.Chara.host == null)
            {
                UpdatePosition(ref v, p);
            }
            if (owner.Chara.ai is AI_Trolley { IsRunning: not false } aI_Trolley)
            {
                drawShadow = false;
                if (aI_Trolley.trolley.HideChara)
                {
                    if (hasActor)
                    {
                        actor.SetActive(enable: false);
                    }
                    return;
                }
            }
            if (hasActor)
            {
                actor.SetActive(enable: true);
            }
        }
        else
        {
            p.x = (position.x = v.x);
            p.y = (position.y = v.y);
            p.z = (position.z = v.z);
        }
        if (anime != null)
        {
            anime.Update();
        }
        if (!isChara && !owner.IsInstalled && owner.category.tileDummy != 0 && !owner.isRoofItem && owner.ExistsOnMap && owner.trait.UseDummyTile)
        {
            SubPassData.Current = SubPassData.Default;
            RenderDataObjDummy rendererObjDummy = EClass.scene.screenElin.tileMap.rendererObjDummy;
            p.tile = rendererObjDummy.tile;
            p.dir = 0;
            if (hasActor)
            {
                actor.SetActive(enable: false);
            }
            rendererObjDummy.Draw(p);
            if (drawShadow && !owner.pos.cell.ignoreObjShadow)
            {
                EClass.scene.screenElin.tileMap.passShadow.AddShadow(position.x + rendererObjDummy.offsetShadow.x, position.y + rendererObjDummy.offsetShadow.y + p.shadowFix, position.z + rendererObjDummy.offsetShadow.z, ShadowData.Instance.items[rendererObjDummy.shadowPref.shadow], rendererObjDummy.shadowPref, 0, p.snow);
            }
        }
        else
        {
            SubPassData.Current = owner.GetSubPassData();
            SourcePref pref = owner.Pref;
            RenderData renderData = data;
            int prefIndex = owner.PrefIndex;
            if (Player.seedHallucination != 0 && CanBeHallucinated())
            {
                Rand.SetSeed(Player.seedHallucination + owner.uid);
                CardRow cardRow = null;
                bool flag = false;
                for (int i = 0; i < 20; i++)
                {
                    if (owner.isChara)
                    {
                        cardRow = EClass.sources.charas.rows.RandomItem();
                        if (cardRow.multisize)
{
                            continue;
                        }
                    }
                    else
                    {
                        cardRow = EClass.sources.things.rows.RandomItem();
                        if (cardRow.tileType != owner.TileType)
{
                            continue;
                        }
                    }
                    if (cardRow.chance != 0 && cardRow._tiles.Length != 0 && cardRow.idActor.IsEmpty() && cardRow.idExtra.IsEmpty() && SubPassData.Current == SubPassData.Default && !(cardRow._idRenderData != owner.sourceCard._idRenderData))
                    {
                        flag = true;
                        break;
                    }
                }
                if (flag)
                {
                    renderData = cardRow.renderData;
                    pref = cardRow.pref;
                    cardRow.model.dir = owner.dir;
                    cardRow.model.SetRenderParam(p);
                    prefIndex = cardRow.model.PrefIndex;
                }
                Rand.SetSeed();
            }
            if (owner.trait is TraitFigure)
            {
                if (!owner.c_idRefCard.IsEmpty() && (owner.IsInstalled || EClass.pc.held == owner || !owner.ExistsOnMap || owner.isRoofItem))
                {
                    TraitFigure traitFigure = owner.trait as TraitFigure;
                    SourceChara.Row row = EClass.sources.charas.map.TryGetValue(owner.c_idRefCard) ?? EClass.sources.charas.map["putty"];
                    renderData = row.renderData;
                    pref = row.pref;
                    if (row._tiles.Length == 0 || data.pass == null)
                    {
                        renderData = owner.sourceCard.renderData;
                        pref = owner.sourceCard.pref;
                    }
                    else
                    {
                        p.tile = row._tiles[owner.refVal % row._tiles.Length] * ((owner.dir % 2 == 0) ? 1 : (-1));
                        p.matColor = traitFigure.GetMatColor();
                        drawShadow = traitFigure.ShowShadow;
                        pref = row.pref;
                    }
                    if (renderData.pass != null && renderData.pass.name == "pass charaL" && EClass.pc.held == owner)
                    {
                        int num = (int)renderData.pass.pmesh.tiling.x;
                        p.tile = (int)p.tile / num * num * 2 + (int)p.tile % num;
                    }
                }
                else
                {
                    renderData = owner.sourceCard.renderData;
                }
            }
            if (replacer != null)
            {
                renderData = replacer.data;
                pref = replacer.pref;
                SubPassData.Current = SubPassData.Default;
            }
            int shadow = pref.shadow;
            bool flag2 = isChara && owner.isHidden && !EClass.pc.canSeeInvisible && (!EClass.pc.hasTelepathy || !owner.Chara.race.visibleWithTelepathy);
            if (isChara)
            {
                p.x += pref.x * (float)((!owner.flipX) ? 1 : (-1));
            }
            p.y += pref.y;
            if (drawShadow && shadow != 1 && SubPassData.Current.shadow && (!flag2 || owner.IsPC))
            {
                bool flag3 = ((!isChara) ? (owner.dir % 2 == 1) : (owner.dir == 1 || owner.dir == 2));
                EClass.scene.screenElin.tileMap.passShadow.AddShadow(position.x + (flag3 ? (-1f) : 1f) * renderData.offsetShadow.x, position.y + renderData.offsetShadow.y + (owner.TileType.UseMountHeight ? 0f : p.shadowFix) - RenderObject.altitudeFix * (float)owner.altitude, position.z + renderData.offsetShadow.z, ShadowData.Instance.items[shadow], pref, prefIndex, p.snow);
            }
            if (usePass)
            {
                if (owner.noSnow)
                {
                    p.snow = false;
                }
                if (!flag2)
                {
                    renderData.Draw(p);
                }
            }
            else if (hasActor)
            {
                if (owner.isChara && owner.Chara.ride != null && (EClass.core.config.game.showRide == 2 || (EClass.core.config.game.showRide == 1 && !owner.Cell.HasRoof && !EClass._map.IsIndoor)) && !owner.IsDeadOrSleeping)
                {
                    Chara ride = owner.Chara.ride;
                    CharaActorPCC charaActorPCC = ride.renderer.actor as CharaActorPCC;
                    CharaActorPCC charaActorPCC2 = actor as CharaActorPCC;
                    ride.angle = owner.angle;
                    if (charaActorPCC != null && charaActorPCC2 != null)
                    {
                        charaActorPCC.provider.currentDir = charaActorPCC2.provider.currentDir;
                        charaActorPCC.provider.currentFrame = charaActorPCC2.provider.currentFrame;
                        charaActorPCC.provider.SetSpriteMain();
                        charaActorPCC.RefreshSprite();
                    }
                    PCCData.RideData ride2 = (ride.renderer as CharaRenderer).pccData.ride;
                    float x = p.x;
                    float y = p.y;
                    float z = p.z;
                    Vector3 v2 = new Vector3(v.x, v.y, v.z);
                    ride.renderer.Draw(p, ref v2, drawShadow: false);
                    int currentDir = actor.currentDir;
                    p.x = x + RenderObject.renderSetting.ridePos[currentDir].x + ride2.x * (float)(currentDir switch
                    {
                        2 => -1,
                        1 => 1,
                        _ => 0,
                    });
                    p.y = y + RenderObject.renderSetting.ridePos[currentDir].y + ride2.y + ride2.jump * (float)((actor.GetFrame() % 2 == 1) ? 1 : 0);
                    p.z = z + RenderObject.renderSetting.ridePos[currentDir].z - ride2.z;
                }
                if (flag2)
                {
                    actor.SetActive(enable: false);
                }
                else
                {
                    actor.SetActive(enable: true);
                    actor.OnRender(p);
                }
            }
            if (isChara)
            {
                if (owner.Chara.parasite != null)
                {
                    owner.Chara.parasite.renderer.position = position;
                }
                if (owner.Chara.ride != null)
                {
                    owner.Chara.ride.renderer.position = position;
                }
            }
            SubPassData.Current = SubPassData.Default;
        }
        if (listTC.Count > 0)
        {
            RenderObject.tempV = position;
            RenderObject.tempV.y += data.offset.y + data.size.y;
            for (int num2 = listTC.Count - 1; num2 >= 0; num2--)
            {
                listTC[num2].OnDraw(ref RenderObject.tempV);
            }
        }
        if (owner.trait.RenderExtra)
        {
            owner.trait.OnRenderExtra(p);
        }
        bool CanBeHallucinated()
        {
            if (!usePass || !owner.ExistsOnMap || !owner.trait.CanBeHallucinated)
            {
                return false;
            }
            if (owner.isThing)
            {
                if (owner.altitude != 0 || owner.TileType.UseMountHeight || owner.pos.LastThing != owner)
                {
                    return false;
                }
                if (listTC.Count > 0)
                {
                    return false;
                }
            }
            return true;
        }
    }
References RenderRow._idRenderData, EClass._map, RenderRow._tiles, Game.activeZone, actor, MeshPass.AddShadow(), Chara.ai, Chara.Aka, Card.altitude, Card.angle, anime, Chara.bossText, Card.c_idRefCard, Trait.CanBeHallucinated, Card.category, Card.Cell, Point.cell, RenderRow.chance, Card.Chara, SourceManager.charas, Core.config, EClass.core, SubPassData.Current, CardActor.currentDir, RendererReplacer.data, RenderObject.data, SubPassData.Default, Card.dir, Draw(), RenderDataObj.Draw(), RenderData.Draw(), Card.ExistsOnMap, Card.flipX, CoreConfig.game, EClass.game, CardActor.GetFrame(), TraitFigure.GetMatColor(), Card.GetSubPassData(), hasActor, Cell.HasRoof, Chara.held, Chara.host, CardRow.idActor, CardRow.idExtra, Cell.ignoreObjShadow, ShadowData.Instance, SplashText.Instance, Lang.isBuiltin, Card.isChara, isChara, Card.IsDeadOrSleeping, Map.IsIndoor, Card.IsInstalled, Card.IsPC, Card.isRoofItem, RenderObject.isSynced, Card.isThing, ShadowData.items, Lang.langCode, Point.LastThing, listTC, CardRow.model, RenderRow.multisize, Card.NameSimple, Card.noSnow, RenderData.offsetShadow, OnEnterScreen(), CardActor.OnRender(), Trait.OnRenderExtra(), orbit, owner, Chara.parasite, Card.parent, RenderData.pass, BaseTileMap.passShadow, EClass.pc, MeshPass.pmesh, Card.pos, position, Card.Pref, RendererReplacer.pref, RenderRow.pref, Card.PrefIndex, CharaActorPCC.provider, Chara.race, TCOrbit.Refresh(), CharaActorPCC.RefreshSprite(), RenderRow.renderData, Card.renderer, BaseTileMap.rendererObjDummy, Trait.RenderExtra, RenderObject.renderSetting, replacer, Chara.ride, EClass.scene, Scene.screenElin, Player.seedHallucination, Card.SetRenderParam(), Rand.SetSeed(), SourcePref.shadow, SubPassData.shadow, RenderParam.shadowFix, RenderData.shadowPref, CoreConfig.GameConfig.showRide, TraitFigure.ShowShadow, RenderData.size, skip, MeshPassParam.snow, Chara.source, Card.sourceCard, EClass.sources, RenderObject.sync, RenderObject.syncFrame, RenderObject.syncList, RenderObject.tempV, SourceManager.things, MeshPassParam.tile, RenderDataObjDummy.tile, BaseGameScreen.tileMap, Card.TileType, RenderRow.tileType, ProceduralMesh.tiling, Card.trait, TrySpawnOrbit(), EClass.ui, Card.uid, TransAnime.Update(), UpdatePosition(), Trait.UseDummyTile, TileType.UseMountHeight, RenderObject.usePass, MeshPassParam.x, MeshPassParam.y, SourcePref.y, and MeshPassParam.z.
DrawHeld()
virtual void CardRenderer.DrawHeld () inline virtual
Reimplemented in CharaRenderer.
Definition at line 351 of file CardRenderer.cs.
    {
    }
GetOrCreateTC< T >()
T CardRenderer.GetOrCreateTC< T > (Func< T > func) inline
Type Constraints
T : TC
Definition at line 587 of file CardRenderer.cs.
                                                    : TC
    {
        return GetTC<T>() ?? AddTC<T>(func());
    }
References AddTC< T >(), and GetTC< T >().
GetTC()
TC CardRenderer.GetTC (string id) inline
Definition at line 571 of file CardRenderer.cs.
    {
        if (listTC.Count == 0)
        {
            return null;
        }
        for (int num = listTC.Count - 1; num >= 0; num--)
        {
            if (listTC[num].name == id)
            {
                return listTC[num];
            }
        }
        return null;
    }
References listTC.
Referenced by ActPlan._Update(), AddExtra(), RemoveExtra(), and AI_Idle.Run().
GetTC< T >()
T CardRenderer.GetTC< T > () inline
Type Constraints
T : TC
Definition at line 555 of file CardRenderer.cs.
                                : TC
    {
        if (listTC.Count == 0)
        {
            return null;
        }
        for (int num = listTC.Count - 1; num >= 0; num--)
        {
            if (listTC[num] is T)
            {
                return listTC[num] as T;
            }
        }
        return null;
    }
References listTC.
Referenced by GetOrCreateTC< T >().
IdleFrame()
virtual void CardRenderer.IdleFrame () inline virtual
Definition at line 524 of file CardRenderer.cs.
    {
        if (hasActor)
        {
            actor.IdleFrame();
        }
    }
References actor, hasActor, and CardActor.IdleFrame().
Referenced by CharaRenderer.UpdatePosition().
IsTalking()
bool CardRenderer.IsTalking () inline
Definition at line 639 of file CardRenderer.cs.
    {
        TCText tC = GetTC<TCText>();
        if ((bool)tC)
        {
            return tC.pop.items.Count > 0;
        }
        return false;
    }
KillActor()
void CardRenderer.KillActor () inline
Definition at line 474 of file CardRenderer.cs.
    {
        actor.Kill();
        hasActor = false;
        actor = null;
    }
References actor, hasActor, and CardActor.Kill().
Referenced by Card.Destroy(), Map.OnDeactivate(), Zone.OnKillGame(), and OnLeaveScreen().
KillAnime()
virtual void CardRenderer.KillAnime () inline virtual
Definition at line 519 of file CardRenderer.cs.
    {
        anime = null;
    }
References anime.
Referenced by Card.KillAnime().
NextDir()
virtual void CardRenderer.NextDir () inline virtual
Definition at line 540 of file CardRenderer.cs.
    {
        if (hasActor)
        {
            actor.NextDir();
        }
    }
References actor, hasActor, and CardActor.NextDir().
NextFrame()
virtual void CardRenderer.NextFrame () inline virtual
Reimplemented in CharaRenderer.
Definition at line 532 of file CardRenderer.cs.
    {
        if (hasActor)
        {
            actor.NextFrame();
        }
    }
References actor, hasActor, and CardActor.NextFrame().
Referenced by Chara._Move(), ActMelee.Attack(), TaskChopWoord.OnCreateProgress(), TaskDig.OnCreateProgress(), TaskHarvest.OnCreateProgress(), TaskMine.OnCreateProgress(), TaskPlow.OnCreateProgress(), ActRanged.Perform(), GoalWait.Run(), ActThrow.Throw(), and Player.TooHeavyToMove().
OnEnterScreen()
override void CardRenderer.OnEnterScreen () inline virtual
Reimplemented from RenderObject.
Reimplemented in CharaRenderer.
Definition at line 363 of file CardRenderer.cs.
    {
        if (isSynced)
        {
            Debug.LogError("renderer alraedy synced:" + owner);
        }
        isSynced = true;
        if (!usePass)
        {
            if (hasActor)
            {
                if (!data.persistActor)
                {
                    Debug.LogError("renderer alraedy have actor:" + owner);
                }
            }
            else
            {
                actor = data.CreateActor();
                if (actor == null)
                {
                    if (owner.sourceCard.idActor.IsEmpty())
                    {
                        actor = PoolManager.Spawn(Resources.Load<CardActor>("Scene/Render/Actor/" + (owner.isChara ? "CharaActor" : "ThingActor")));
                    }
                    else
                    {
                        actor = PoolManager.Spawn(Resources.Load<CardActor>("Scene/Render/Actor/" + owner.sourceCard.idActor[0]));
                    }
                }
                hasActor = true;
            }
            actor.SetOwner(owner);
        }
        RefreshStateIcon();
        RefreshExtra();
        if (owner.isCensored)
        {
            SetCensored(enable: true);
        }
        owner.trait.OnEnterScreen();
    }
References actor, RenderData.CreateActor(), RenderObject.data, Debug, hasActor, CardRow.idActor, Card.isCensored, Card.isChara, RenderObject.isSynced, Trait.OnEnterScreen(), owner, RenderData.persistActor, RefreshExtra(), RefreshStateIcon(), SetCensored(), CardActor.SetOwner(), Card.sourceCard, PoolManager.Spawn(), Card.trait, and RenderObject.usePass.
Referenced by Draw(), BaseListPeople.OnClick(), and EffectIRenderer.OnUpdate().
OnLeaveScreen()
override void CardRenderer.OnLeaveScreen () inline virtual
Reimplemented from RenderObject.
Definition at line 448 of file CardRenderer.cs.
    {
        if (!isSynced)
        {
            Debug.LogWarning("renderer alraedy not synced:" + owner);
        }
        isSynced = false;
        if (hasActor && (!owner.ExistsOnMap || !data.persistActor))
        {
            KillActor();
        }
        for (int num = listTC.Count - 1; num >= 0; num--)
        {
            RemoveTC(num);
        }
        if (hasText)
        {
            DespawnSimpleText();
        }
        if ((bool)orbit)
        {
            PoolManager.Despawn(orbit);
            orbit = null;
        }
    }
References RenderObject.data, Debug, PoolManager.Despawn(), DespawnSimpleText(), Card.ExistsOnMap, hasActor, hasText, RenderObject.isSynced, KillActor(), listTC, orbit, owner, RenderData.persistActor, and RemoveTC().
Referenced by BaseListPeople.OnClick(), and Zone.RemoveCard().
PlayAnime() [1/4]
void CardRenderer.PlayAnime (AnimeID id, bool force) inline
Definition at line 481 of file CardRenderer.cs.
    {
        PlayAnime(id, default(Vector3), force);
    }
References PlayAnime().
Referenced by Chara._Move(), ActMelee.Attack(), Card.DamageHP(), GrowSystemTree.OnHitFail(), AI_Fish.ProgressFish.OnProgress(), AI_Fish.ProgressFish.OnProgressComplete(), TaskBuild.OnProgressComplete(), ActBash.Perform(), PlayAnime(), Card.PlayAnime(), Card.PlayAnimeLoot(), Trait.Refuel(), AI_Bladder.Run(), AI_Deconstruct.Run(), AI_Fuck.Run(), AI_Massage.Run(), AI_OpenGambleChest.Run(), AI_Paint.Run(), AI_PlayMusic.Run(), AI_Shear.Run(), AI_Steal.Run(), AI_UseCrafter.Run(), NoGoal.Run(), LayerPixelPaint.SetCanvas(), and CoreDebug.UpdateInput().
PlayAnime() [2/4]
void CardRenderer.PlayAnime (AnimeID id, Card dest) inline
Definition at line 486 of file CardRenderer.cs.
    {
        PlayAnime(id, (dest.renderer.position - position).normalized);
    }
References PlayAnime(), position, and Card.renderer.
PlayAnime() [3/4]
void CardRenderer.PlayAnime (AnimeID id, Point dest) inline
Definition at line 491 of file CardRenderer.cs.
    {
        PlayAnime(id, (dest.PositionAuto() - position).normalized);
    }
References PlayAnime(), position, and Point.PositionAuto().
PlayAnime() [4/4]
void CardRenderer.PlayAnime (AnimeID id, Vector3 dest = default(Vector3), bool force = false) inline
Definition at line 496 of file CardRenderer.cs.
    {
        if (!force && owner.parent is Zone && (!owner.pos.IsValid || !owner.pos.IsSync))
        {
            return;
        }
        TransAnimeData transAnimeData = ResourceCache.Load<TransAnimeData>("Scene/Render/Anime/" + id);
        if (transAnimeData == null)
        {
            anime = null;
            return;
        }
        anime = new TransAnime
        {
            data = transAnimeData,
            renderer = this
        }.Init();
        if (id == AnimeID.Attack || (uint)(id - 18) <= 1u)
        {
            anime.dest = dest;
        }
    }
References anime, RenderObject.data, Point.IsSync, Point.IsValid, owner, Card.parent, and Card.pos.
PositionCenter()
Vector3 CardRenderer.PositionCenter () inline
Definition at line 33 of file CardRenderer.cs.
    {
        return new Vector3(position.x + data.size.x + data.offset.x * 0.5f, position.y + data.size.y + data.offset.y, position.z);
    }
References RenderObject.data, RenderData.offset, position, and RenderData.size.
Referenced by Card.DamageHP(), and BaseStats.PopText().
Refresh()
virtual void CardRenderer.Refresh () inline virtual
Reimplemented in CharaRenderer.
Definition at line 713 of file CardRenderer.cs.
    {
    }
RefreshExtra()
void CardRenderer.RefreshExtra () inline
Definition at line 419 of file CardRenderer.cs.
    {
        string idExtra = owner.sourceCard.idExtra;
        if (!idExtra.IsEmpty())
        {
            AddExtra(idExtra);
        }
        if (isChara && owner.rarity >= Rarity.Legendary && owner.rarity != Rarity.Artifact && !owner.Chara.IsHomeMember())
        {
            if (owner.c_bossType == BossType.Evolved)
            {
                AddExtra("c_unique_evolved");
            }
            else
            {
                AddExtra("c_unique");
            }
        }
    }
References AddExtra(), Card.c_bossType, Card.Chara, CardRow.idExtra, isChara, Chara.IsHomeMember(), owner, Card.rarity, and Card.sourceCard.
Referenced by Chara.ChangeRarity(), TraitGodStatue.OnChangeMaterial(), OnEnterScreen(), and TraitPowerStatue.OnUse().
RefreshSprite()
void CardRenderer.RefreshSprite () inline
Definition at line 355 of file CardRenderer.cs.
    {
        if (hasActor)
        {
            actor.RefreshSprite();
        }
    }
References actor, hasActor, and CardActor.RefreshSprite().
Referenced by GameDate.AdvanceMonth(), RecipeCard.Build(), AM_MoveInstalled.OnProcessTiles(), ConFaint.OnRemoved(), CharaActorPCC.OnRender(), Card.Rotate(), TraitDoor.RotateDoor(), LayerPixelPaint.SetCanvas(), Card.SetDir(), ConFaint.SetOwner(), ConSleep.SetOwner(), and CharaRenderer.UpdatePosition().
RefreshStateIcon()
virtual void CardRenderer.RefreshStateIcon () inline virtual
Reimplemented in CharaRenderer.
Definition at line 688 of file CardRenderer.cs.
    {
    }
Referenced by OnEnterScreen().
RemoveExtra()
void CardRenderer.RemoveExtra (string id) inline
Definition at line 439 of file CardRenderer.cs.
    {
        TC tC = GetTC(id);
        if (tC != null)
        {
            RemoveTC(tC);
        }
    }
References GetTC(), and RemoveTC().
Referenced by Trait.RefreshRenderer(), and TraitToolTorch.RefreshRenderer().
RemoveTC() [1/2]
void CardRenderer.RemoveTC (int index) inline
Definition at line 614 of file CardRenderer.cs.
    {
        if (index != -1)
        {
            listTC[index].Kill();
            listTC.RemoveAt(index);
        }
    }
References listTC.
RemoveTC() [2/2]
void CardRenderer.RemoveTC (TC tc) inline
Definition at line 609 of file CardRenderer.cs.
    {
        RemoveTC(listTC.IndexOf(tc));
    }
References listTC, and RemoveTC().
Referenced by OnLeaveScreen(), CharaRenderer.RefreshStateIcon(), RemoveExtra(), and RemoveTC().
RemoveTC< T >()
void CardRenderer.RemoveTC< T > () inline
Type Constraints
T : TC
Definition at line 592 of file CardRenderer.cs.
                                      : TC
    {
        if (listTC.Count == 0)
        {
            return;
        }
        for (int num = listTC.Count - 1; num >= 0; num--)
        {
            if (listTC[num] is T)
            {
                listTC[num].Kill();
                listTC.RemoveAt(num);
                break;
            }
        }
    }
References listTC.
RenderToRenderCam()
override void CardRenderer.RenderToRenderCam (RenderParam p) inline virtual
Reimplemented from RenderObject.
Definition at line 55 of file CardRenderer.cs.
    {
        Vector3 v = EClass.scene.camSupport.renderPos;
        if (data.multiSize)
        {
            v.y -= 0.8f;
        }
        p.x = v.x;
        p.y = v.y;
        p.z = v.z;
        Draw(p, ref v, drawShadow: false);
    }
References Scene.camSupport, RenderObject.data, Draw, RenderData.multiSize, CameraSupport.renderPos, and EClass.scene.
Say()
void CardRenderer.Say (string text, Color c = default(Color), float duration = 0f) inline
Definition at line 692 of file CardRenderer.cs.
    {
        (GetTC<TCText>() ?? AddTC<TCText>(PoolManager.Spawn(EClass.core.refs.tcs.text, EClass.ui.rectDynamic))).Say(text, duration);
    }
References EClass.core, Core.refs, Say(), PoolManager.Spawn(), CoreRef.tcs, CoreRef.TCs.text, and EClass.ui.
Referenced by Say(), Card.SayRaw(), and Card.TalkRaw().
SetCensored()
void CardRenderer.SetCensored (bool enable) inline
Definition at line 672 of file CardRenderer.cs.
    {
        if (!isSynced)
        {
            return;
        }
        if (enable)
        {
            GetOrCreateTC(() => PoolManager.Spawn(EClass.core.refs.tcs.censored));
        }
        else
        {
            RemoveTC<TCCensored>();
        }
    }
References CoreRef.TCs.censored, EClass.core, RenderObject.isSynced, Core.refs, PoolManager.Spawn(), and CoreRef.tcs.
Referenced by OnEnterScreen(), and Card.SetCensored().
SetFirst() [1/2]
virtual void CardRenderer.SetFirst (bool first) inline virtual
Reimplemented in CharaRenderer.
Definition at line 709 of file CardRenderer.cs.
    {
    }
SetFirst() [2/2]
virtual void CardRenderer.SetFirst (bool first, Vector3 pos) inline virtual
Reimplemented in CharaRenderer.
Definition at line 705 of file CardRenderer.cs.
    {
    }
Referenced by BaseTileMap.DrawTile(), Card.MoveImmediate(), AM_Adv.OnActivate(), TaskBuild.OnProgressComplete(), Card.Teleport(), and Card.TryUnrestrain().
SetOwner()
virtual void CardRenderer.SetOwner (Card c) inline virtual
Reimplemented in CharaRenderer.
Definition at line 38 of file CardRenderer.cs.
    {
        owner = c;
        if (data == null)
        {
            data = owner.sourceCard.renderData;
        }
        isChara = c.isChara;
        usePass = data.pass != null;
    }
References RenderObject.data, Card.isChara, isChara, owner, RenderRow.renderData, Card.sourceCard, and RenderObject.usePass.
Referenced by Card._CreateRenderer().
ShowEmo()
void CardRenderer.ShowEmo (Emo emo, float duration = 0f) inline
Definition at line 697 of file CardRenderer.cs.
    {
        if (isSynced)
        {
            (GetTC<TCText>() ?? AddTC<TCText>(PoolManager.Spawn(EClass.core.refs.tcs.text, EClass.ui.rectDynamic))).ShowEmo(emo, duration);
        }
    }
References EClass.core, RenderObject.isSynced, Core.refs, ShowEmo(), PoolManager.Spawn(), CoreRef.tcs, CoreRef.TCs.text, and EClass.ui.
Referenced by Card.ShowEmo(), and ShowEmo().
SpawnSimpleText()
TCSimpleText CardRenderer.SpawnSimpleText () inline
Definition at line 649 of file CardRenderer.cs.
    {
        if (!hasText)
        {
            hasText = true;
            simpleText = PoolManager.Spawn(EClass.core.refs.tcs.simpleText, EClass.screen);
        }
        RenderObject.tempV.x = position.x + TC._setting.simpleTextPos.x;
        RenderObject.tempV.y = position.y + TC._setting.simpleTextPos.y;
        RenderObject.tempV.z = position.z + TC._setting.simpleTextPos.z;
        simpleText.transform.position = RenderObject.tempV;
        return simpleText;
    }
References TC._setting, EClass.core, hasText, Core.refs, EClass.screen, simpleText, CoreRef.TCs.simpleText, PoolManager.Spawn(), CoreRef.tcs, and RenderObject.tempV.
TrySpawnOrbit()
void CardRenderer.TrySpawnOrbit () inline
Definition at line 623 of file CardRenderer.cs.
    {
        if (owner.isChara)
        {
            string text = (owner.IsPC ? "tcOrbitPC" : "tcOrbitChara");
            orbit = PoolManager.Spawn<TCOrbitChara>(text, "Scene/Render/Actor/Component/" + text);
            orbit.SetOwner(this);
        }
        else if (owner.trait.ShowOrbit)
        {
            string text2 = "tcOrbitThing";
            orbit = PoolManager.Spawn<TCOrbitThing>(text2, "Scene/Render/Actor/Component/" + text2);
            orbit.SetOwner(this);
        }
    }
References Card.isChara, orbit, owner, TC.SetOwner(), Trait.ShowOrbit, PoolManager.Spawn(), and Card.trait.
Referenced by Draw().
UpdatePosition()
virtual void CardRenderer.UpdatePosition (ref Vector3 destPos, RenderParam p) inline virtual
Reimplemented in CharaRenderer.
Definition at line 347 of file CardRenderer.cs.
    {
    }
Referenced by Draw().
Member Data Documentation
actor
CardActor CardRenderer.actor
Definition at line 11 of file CardRenderer.cs.
Referenced by Chara._Move(), Draw(), CharaRenderer.DrawHat(), CharaRenderer.DrawHeld(), IdleFrame(), KillActor(), NextDir(), NextFrame(), OnEnterScreen(), EffectIRenderer.OnUpdate(), AttackProcess.PlayRangedAnime(), RefreshSprite(), Card.RenderMarker(), CharaRenderer.UpdatePosition(), and WidgetDebug.UpdateText().
anime
TransAnime CardRenderer.anime
Definition at line 23 of file CardRenderer.cs.
Referenced by Chara._Move(), Draw(), KillAnime(), and PlayAnime().
hasActor
bool CardRenderer.hasActor
Definition at line 13 of file CardRenderer.cs.
Referenced by Chara._Move(), GameDate.AdvanceMonth(), Card.Destroy(), Draw(), CharaRenderer.DrawHeld(), IdleFrame(), KillActor(), NextDir(), NextFrame(), Map.OnDeactivate(), OnEnterScreen(), Zone.OnKillGame(), OnLeaveScreen(), AM_MoveInstalled.OnProcessTiles(), CharaActorPCC.OnRender(), EffectIRenderer.OnUpdate(), AttackProcess.PlayRangedAnime(), RefreshSprite(), Zone.RemoveCard(), Card.RenderMarker(), and CharaRenderer.UpdatePosition().
hasText
bool CardRenderer.hasText
Definition at line 15 of file CardRenderer.cs.
Referenced by DespawnSimpleText(), OnLeaveScreen(), and SpawnSimpleText().
isChara
bool CardRenderer.isChara
Definition at line 17 of file CardRenderer.cs.
Referenced by Draw(), RefreshExtra(), and SetOwner().
listTC
List<TC> CardRenderer.listTC = new List<TC>()
Definition at line 25 of file CardRenderer.cs.
Referenced by AddTC< T >(), Draw(), GetTC(), GetTC< T >(), OnLeaveScreen(), RemoveTC(), and RemoveTC< T >().
orbit
TCOrbit CardRenderer.orbit
Definition at line 7 of file CardRenderer.cs.
Referenced by BaseGameScreen.Draw(), Draw(), OnLeaveScreen(), and TrySpawnOrbit().
owner
Card CardRenderer.owner
Definition at line 9 of file CardRenderer.cs.
Referenced by Draw(), OnEnterScreen(), OnLeaveScreen(), PlayAnime(), RefreshExtra(), SetOwner(), and TrySpawnOrbit().
position
Vector3 CardRenderer.position
Definition at line 21 of file CardRenderer.cs.
Referenced by Draw(), BaseTileMap.DrawTile(), EffectIRenderer.OnUpdate(), EffectIRenderer.Play(), PlayAnime(), Card.PlayEffect(), AttackProcess.PlayRangedAnime(), PositionCenter(), TraitEffect.Proc(), TCOrbitChara.Refresh(), TCOrbitThing.Refresh(), BaseGameScreen.RefreshPosition(), GameScreenElona.RefreshPosition(), Card.RenderMarker(), CharaRenderer.SetFirst(), ActThrow.Throw(), and CharaRenderer.UpdatePosition().
replacer
RendererReplacer CardRenderer.replacer
Definition at line 29 of file CardRenderer.cs.
Referenced by Chara._CreateRenderer(), Chara._Move(), Draw(), and CharaRenderer.DrawHat().
simpleText
TCSimpleText CardRenderer.simpleText
Definition at line 27 of file CardRenderer.cs.
Referenced by DespawnSimpleText(), and SpawnSimpleText().
skip
bool CardRenderer.skip
Definition at line 19 of file CardRenderer.cs.
Referenced by Draw().
Property Documentation
IsMoving
virtual bool CardRenderer.IsMoving get
Definition at line 31 of file CardRenderer.cs.
Referenced by BaseTileMap.DrawTile(), and AM_Adv.OnBeforeUpdate().
The documentation for this class was generated from the following file:
Elin/CardRenderer.cs