Elin Decompiled Documentation: Stats Class Reference
Stats Class Reference
Public Member Functions
override int GetValue ()
override string ToString ()
override string GetText ()
override Color GetColor (Gradient g)
Stats Set (int[] _raw, int _rawIndex, Chara _CC)
override int GetPhase ()
virtual void Set (int a)
virtual void Mod (int a)
virtual void Validate ()
virtual void OnChangePhase (int phase, int lastPhase)
Public Member Functions inherited from BaseStats
virtual Color GetColor (Gradient gradient)
virtual Color GetColor (SkinColorProfile c)
Color GetColor ()
virtual string GetText ()
virtual string GetPhaseStr ()
virtual int GetValue ()
virtual int GetSortVal ()
virtual Sprite GetSprite ()
virtual void SetText (UIText t, SkinColorProfile cols=null)
virtual int GetPhase ()
void PopText ()
virtual void WriteNote (UINote n, Action< UINote > onWriteNote=null)
virtual void _WriteNote (UINote n, bool asChild=false)
Public Attributes
int rawIndex
int[] raw
Public Attributes inherited from BaseStats
int id
SourceStat.Row _source
Static Public Attributes
static StatsHunger Hunger
static StatsBurden Burden
static StatsStamina Stamina
static StatsSleepiness Sleepiness
static Stats Depression
static Stats Bladder
static StatsHygiene Hygiene
static StatsMana Mana
static StatsSAN SAN
Static Public Attributes inherited from BaseStats
static Chara CC
Static Public Attributes inherited from EClass
static Core core
Properties
virtual int value [get, set]
virtual int max [get, set]
string name [get]
virtual bool TrackPhaseChange [get]
virtual int min [get]
Properties inherited from BaseStats
SourceStat.Row source [get]
virtual Emo2 EmoIcon [get]
virtual ConditionType Type [get]
virtual string idSprite [get]
virtual bool ShowInWidget [get]
virtual Chara Owner [get]
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Additional Inherited Members
Static Public Member Functions inherited from EClass
static int rndSeed (int a, int seed)
static int rnd (long a)
static int rnd (int a)
static int curve (int a, int start, int step, int rate=75)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Detailed Description
Definition at line 4 of file Stats.cs.
Member Function Documentation
GetColor()
override Color Stats.GetColor (Gradient g) inline virtual
Reimplemented from BaseStats.
Definition at line 104 of file Stats.cs.
    {
        return g.Evaluate((float)value / (float)max);
    }
References max, and value.
Referenced by WindowChara.AddNeeds().
GetPhase()
override int Stats.GetPhase () inline virtual
Reimplemented from BaseStats.
Reimplemented in StatsBurden, and StatsStamina.
Definition at line 117 of file Stats.cs.
    {
        return base.source.phase[(int)Mathf.Clamp(10f * (float)value / (float)max, 0f, 9f)];
    }
References max, and value.
Referenced by Chara._Move(), Chara.CanSleep(), GetText(), TraitMoongate.LoadMap(), Mod(), Chara.ModAffinity(), Scene.OnUpdate(), FoodEffect.Proc(), LayerTravel.Refresh(), Chara.RefreshSpeed(), AI_Eat.Run(), AI_Idle.Run(), Chara.Tick(), ConSleep.Tick(), Chara.TickConditions(), ToString(), Chara.TryUse(), and Chara.Vomit().
GetText()
override string Stats.GetText () inline virtual
Reimplemented from BaseStats.
Definition at line 94 of file Stats.cs.
    {
        string text = base.source.GetTextArray("strPhase")[GetPhase()];
        if (!(text == "#"))
        {
            return text;
        }
        return "";
    }
References GetPhase().
Referenced by WindowChara.AddNeeds().
GetValue()
override int Stats.GetValue () inline virtual
Reimplemented from BaseStats.
Definition at line 84 of file Stats.cs.
    {
        return value;
    }
References value.
Mod()
virtual void Stats.Mod (int a) inline virtual
Reimplemented in StatsMana, and StatsStamina.
Definition at line 135 of file Stats.cs.
    {
        if (BaseStats.CC.IsAgent)
        {
            return;
        }
        if (TrackPhaseChange)
        {
            int phase = GetPhase();
            value += a;
            if (value < min)
            {
                value = min;
            }
            else if (value > max)
            {
                value = max;
            }
            int phase2 = GetPhase();
            if (phase2 != phase)
            {
                OnChangePhase(phase2, phase);
            }
        }
        else
        {
            value += a;
            if (value < min)
            {
                value = min;
            }
            else if (value > max)
            {
                value = max;
            }
        }
    }
References BaseStats.CC, GetPhase(), Card.IsAgent, max, min, OnChangePhase(), TrackPhaseChange, and value.
Referenced by TraitShrine._OnUse(), Card.ApplyElementEffect(), AI_PracticeDummy.CreateProgress(), Chara.Cure(), ActEffect.DamageEle(), Chara.Drink(), AI_Fish.ProgressFish.Fail(), AI_Fuck.Finish(), AI_Massage.Finish(), Chara.GiveGift(), TaskChopWood.OnCreateProgress(), TaskDrawWater.OnCreateProgress(), TaskHarvest.OnCreateProgress(), TaskPlow.OnCreateProgress(), TaskPourWater.OnCreateProgress(), MiniGame.OnPlay(), AI_Fish.ProgressFish.OnProgressComplete(), TaskCraft.OnProgressComplete(), TaskDig.OnProgressComplete(), TaskMine.OnProgressComplete(), TraitBaseSpellbook.OnRead(), ConSleep.OnRemoved(), Chara.OnSleep(), ConAwakening.OnStart(), LayerMiniGame.OnUpdateInput(), ActRanged.Perform(), ActPray.Pray(), FoodEffect.Proc(), ActEffect.Proc(), TraitBaseSpellbook.ReadFailEffect(), AI_Bladder.Run(), AI_Craft_Snowman.Run(), AI_Fuck.Run(), AI_Idle.Run(), AI_OpenGambleChest.Run(), AI_PassTime.Run(), AI_PlayMusic.Run(), AI_Shear.Run(), AI_Slaughter.Run(), AI_Steal.Run(), AI_UseCrafter.Run(), TaskClean.Run(), Zone.Simulate(), ActThrow.Throw(), ConSleep.Tick(), ConSmoking.Tick(), Chara.TickConditions(), Chara.TryAbsorbRod(), Trait.TryOpenLock(), Chara.UseAbility(), and Chara.Vomit().
OnChangePhase()
virtual void Stats.OnChangePhase (int phase, int lastPhase) inline virtual
Definition at line 178 of file Stats.cs.
    {
        bool flag = phase > lastPhase;
        if (base.source.invert)
        {
            flag = !flag;
        }
        string[] array = (flag ? base.source.GetText("textPhase") : base.source.GetText("textPhase2")).Split(Environment.NewLine.ToCharArray());
        if (array.Length > phase)
        {
            if (flag)
            {
                Msg.SetColor("negative");
            }
            BaseStats.CC.Say(array[phase].Split('|').RandomItem(), BaseStats.CC);
            if (BaseStats.CC.ShouldShowMsg)
            {
                PopText();
            }
        }
    }
References BaseStats.CC, BaseStats.PopText(), Card.Say(), Msg.SetColor(), and Card.ShouldShowMsg.
Referenced by Mod().
Set() [1/2]
virtual void Stats.Set (int a) inline virtual
Definition at line 122 of file Stats.cs.
    {
        value = a;
        if (value < min)
        {
            value = min;
        }
        else if (value > max)
        {
            value = max;
        }
    }
References max, min, and value.
Set() [2/2]
Stats Stats.Set (int[] _raw, int _rawIndex, Chara _CC) inline
Definition at line 109 of file Stats.cs.
    {
        raw = _raw;
        rawIndex = _rawIndex;
        BaseStats.CC = _CC;
        return this;
    }
References raw, and rawIndex.
Referenced by Chara.CalcBurden(), Chara.OnSleep(), and Game.StartNewGame().
ToString()
override string Stats.ToString () inline
Definition at line 89 of file Stats.cs.
    {
        return name + " " + value + " " + GetPhase();
    }
References GetPhase(), name, and value.
Validate()
virtual void Stats.Validate () inline virtual
Definition at line 173 of file Stats.cs.
    {
        value = Mathf.Clamp(value, min, max);
    }
References max, min, and value.
Referenced by BaseSong.OnStart().
Member Data Documentation
Bladder
Stats Stats.Bladder static
Initial value:
= new Stats
    {
        id = 6
    }
Definition at line 31 of file Stats.cs.
Burden
StatsBurden Stats.Burden static
Initial value:
= new StatsBurden
    {
        id = 1
    }
Definition at line 11 of file Stats.cs.
Depression
Stats Stats.Depression static
Initial value:
= new Stats
    {
        id = 5
    }
Definition at line 26 of file Stats.cs.
Hunger
StatsHunger Stats.Hunger static
Initial value:
= new StatsHunger
    {
        id = 0
    }
Definition at line 6 of file Stats.cs.
Hygiene
StatsHygiene Stats.Hygiene static
Initial value:
= new StatsHygiene
    {
        id = 7
    }
Definition at line 36 of file Stats.cs.
Mana
StatsMana Stats.Mana static
Initial value:
= new StatsMana
    {
        id = 8
    }
Definition at line 41 of file Stats.cs.
raw
int [] Stats.raw
Definition at line 53 of file Stats.cs.
Referenced by Set().
rawIndex
int Stats.rawIndex
Definition at line 51 of file Stats.cs.
Referenced by Set().
SAN
StatsSAN Stats.SAN static
Initial value:
= new StatsSAN
    {
        id = 13
    }
Definition at line 46 of file Stats.cs.
Sleepiness
StatsSleepiness Stats.Sleepiness static
Initial value:
= new StatsSleepiness
    {
        id = 4
    }
Definition at line 21 of file Stats.cs.
Stamina
StatsStamina Stats.Stamina static
Initial value:
= new StatsStamina
    {
        id = 3
    }
Definition at line 16 of file Stats.cs.
Property Documentation
max
virtual int Stats.max get set
Definition at line 67 of file Stats.cs.
    {
        get
        {
            return 100;
        }
        set
        {
        }
    }
Referenced by TraitShrine._OnUse(), FactionBranch.AddMemeber(), WindowChara.AddNeeds(), AI_Fuck.Finish(), AI_Massage.Finish(), GetColor(), Element.GetCost(), GetPhase(), Chara.HealAll(), Chara.IsCriticallyWounded(), Mod(), Chara.OnCreate(), ActEffect.Proc(), CoreDebug.QuickStart(), TraitBaseSpellbook.ReadFailEffect(), WidgetHP.Refresh(), WindowChara.RefreshStatic(), AI_Idle.Run(), AI_Torture.Run(), Set(), Card.SetLv(), Zone.Simulate(), Game.StartNewGame(), Chara.Stumble(), Chara.TickConditions(), GoalCombat.TryUseAbility(), and Validate().
min
virtual int Stats.min get
Definition at line 82 of file Stats.cs.
Referenced by Mod(), Set(), and Validate().
name
string Stats.name get
Definition at line 78 of file Stats.cs.
Referenced by ToString().
TrackPhaseChange
virtual bool Stats.TrackPhaseChange get
Definition at line 80 of file Stats.cs.
Referenced by Mod().
value
virtual int Stats.value get set
Definition at line 55 of file Stats.cs.
    {
        get
        {
            return raw[rawIndex];
        }
        set
        {
            raw[rawIndex] = value;
        }
    }
Referenced by AM_Adv._OnUpdateInput(), Element._WriteNote(), FactionBranch.AddMemeber(), WindowChara.AddNeeds(), AI_PracticeDummy.CreateProgress(), ActEffect.DamageEle(), Card.DamageHP(), Chara.Duplicate(), GetColor(), Chara.GetGoalFromTimeTable(), Chara.GetHoverText2(), GetPhase(), StatsBurden.GetPhase(), StatsStamina.GetPhase(), GetValue(), GoalAutoCombat.GoalAutoCombat(), Mod(), StatsMana.Mod(), StatsStamina.Mod(), Chara.OnSleep(), ActRanged.Perform(), FoodEffect.Proc(), ActEffect.Proc(), Religion.PunishTakeOver(), WidgetHP.Refresh(), UIRecipeInfo.RefreshBalance(), WindowChara.RefreshProfile(), Chara.Revive(), AI_Idle.Run(), AI_Torture.Run(), GoalNeeds.Run(), Set(), Zone.Simulate(), ButtonAbility.SpecialHoldAction(), Chara.Tick(), Chara.TickConditions(), ToString(), GoalCombat.TryUseAbility(), Chara.UseAbility(), and Validate().
The documentation for this class was generated from the following file:
Elin/Stats.cs