Elin Decompiled Documentation: GameDate Class Reference
GameDate Class Reference
Public Member Functions
void AdvanceSec (int a)
void AdvanceMin (int a)
void AdvanceHour ()
void AdvanceDay ()
void AdvanceMonth ()
void AdvanceYear ()
void ShipGoods ()
void ShipPackages ()
void ShipLetter ()
void ShipRandomPackages ()
Public Member Functions inherited from Date
Date Copy ()
override string ToString ()
void AddHour (int a)
void AddDay (int a)
void AddMonth (int a)
string GetText (Date.TextFormat format)
int GetRawReal (int offsetHours=0)
int GetRaw (int offsetHours=0)
int GetRawDay ()
bool IsExpired (int time)
int GetRemainingHours (int rawDeadLine)
int GetRemainingSecs (int rawDeadLine)
int GetElapsedMins (int rawDate)
int GetElapsedHour (int rawDate)
Public Attributes
bool shaken
Public Attributes inherited from Date
int[] raw = new int[6]
Static Public Attributes
const int minPerRound = 5
Static Public Attributes inherited from Date
const int ShippingHour = 5
const int HourToken = 60
const int DayToken = 1440
const int MonthToken = 43200
const int YearToken = 518400
const int HourTokenReal = 60
const int DayTokenReal = 1440
const int MonthTokenReal = 46080
const int YearTokenReal = 552960
Static Public Attributes inherited from EClass
static Core core
Static Package Functions
static void< ShipRandomPackages > g__Add (string id, int num, ref GameDate.<>c__DisplayClass11_0 A_2)
static void< ShipRandomPackages > g__AddThing (Thing t, int num, ref GameDate.<>c__DisplayClass11_0 A_2)
Additional Inherited Members
Public Types inherited from Date
enum TextFormat {
Default , Log , Widget , Schedule ,
Travel , YearMonthDay , LogPlusYear
}
Static Public Member Functions inherited from Date
static string GetText (int raw, Date.TextFormat format)
static string GetText (int hour)
static string GetText2 (int hour)
static string SecToDate (int sec)
static string MinToDayAndHour (int min)
static int[] GetDateArray (int raw)
static Date ToDate (int raw)
Static Public Member Functions inherited from EClass
static int rnd (int a)
static int curve (int a, int start, int step, int rate=75)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Properties inherited from Date
int year [get, set]
int month [get, set]
int day [get, set]
int hour [get, set]
int min [get, set]
int sec [get, set]
bool IsDay [get]
bool IsNight [get]
PeriodOfDay periodOfDay [get]
string NameMonth [get]
string NameMonthShort [get]
string NameTime [get]
bool IsSpring [get]
bool IsSummer [get]
bool IsAutumn [get]
bool IsWinter [get]
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Detailed Description
Definition at line 7 of file GameDate.cs.
Member Function Documentation
AdvanceDay()
void GameDate.AdvanceDay () inline
Definition at line 138 of file GameDate.cs.
    {
        int num = base.day;
        base.day = num + 1;
        base.min = 0;
        EClass.player.stats.days++;
        if (EClass.player.stats.days >= 90)
        {
            Tutorial.Reserve("death_penalty", null);
        }
        if (base.day > 30)
        {
            base.day = 1;
            this.AdvanceMonth();
        }
        EClass.world.CreateDayData();
        EClass.Sound.Play("owl");
        if (!EClass.player.prayed && EClass.pc.Evalue(1655) > 0)
        {
            ActPray.TryPray(EClass.pc, true);
        }
        Msg.Say("endDay");
        this.shaken = false;
        EClass.player.OnAdvanceDay();
        EClass.game.relations.UpdateRelations();
        EClass.pc.faction.OnAdvanceDay();
        foreach (Chara chara in EClass.game.cards.listAdv)
        {
            if (!chara.IsPCFaction && EClass.rnd(10) == 0 && (chara.isDead || chara.currentZone == null || chara.currentZone.id == "somewhere"))
            {
                chara.SetHomeZone(EClass.world.region.ListTowns().RandomItem<Zone>());
                chara.Revive(null, false);
                chara.MoveZone(chara.homeZone, ZoneTransition.EnterState.Auto);
            }
        }
        if (EClass.pc.homeZone != null && EClass.pc.homeZone.mainFaction == EClass.pc.faction)
        {
            WidgetSticky.Add(new StickyHomeReport(), true);
        }
        if (EClass.player.stats.days >= 7 && EClass.game.cards.globalCharas.Find("fiama").currentZone == EClass.game.StartZone && EClass.game.quests.GetGlobal("fiama_starter_gift") == null && !EClass.game.quests.IsCompleted("fiama_starter_gift"))
        {
            EClass.game.quests.Add("fiama_starter_gift", "fiama");
        }
        if (EClass.game.quests.IsCompleted("exploration"))
        {
            Player.Flags flags = EClass.player.flags;
            num = flags.daysAfterQuestExploration;
            flags.daysAfterQuestExploration = num + 1;
            if (EClass.player.flags.daysAfterQuestExploration >= 7 && !EClass.player.flags.magicChestSent)
            {
                EClass.player.flags.magicChestSent = true;
                Thing thing = ThingGen.Create("parchment", -1, -1);
                thing.SetStr(53, "letter_magic_chest");
                Thing p = ThingGen.CreateParcel(null, new Thing[]
                {
                    ThingGen.Create("container_magic", -1, -1),
                    thing
                });
                EClass.world.SendPackage(p);
            }
        }
    }
References WidgetSticky.Add(), QuestManager.Add(), AdvanceMonth(), Game.cards, ThingGen.Create(), World.CreateDayData(), ThingGen.CreateParcel(), Chara.currentZone, Player.Flags.daysAfterQuestExploration, Card.Evalue(), Chara.faction, CardManager.Find(), Player.flags, EClass.game, QuestManager.GetGlobal(), CardManager.globalCharas, Chara.homeZone, Spatial.id, QuestManager.IsCompleted(), Chara.isDead, Chara.IsPCFaction, CardManager.listAdv, Region.ListTowns(), Spatial.mainFaction, Chara.MoveZone(), Faction.OnAdvanceDay(), Player.OnAdvanceDay(), EClass.pc, EClass.player, Player.prayed, Game.quests, World.region, Game.relations, Tutorial.Reserve(), Chara.Revive(), EClass.rnd(), Msg.Say(), World.SendPackage(), Chara.SetHomeZone(), BaseCard.SetStr(), EClass.Sound, Game.StartZone, Player.stats, ActPray.TryPray(), RelationManager.UpdateRelations(), and EClass.world.
Referenced by AdvanceHour(), and HotItemContext.Show().
AdvanceHour()
void GameDate.AdvanceHour () inline
Definition at line 68 of file GameDate.cs.
    {
        new VirtualDate(0)
        {
            IsRealTime = true
        }.SimulateHour();
        int hour = base.hour;
        base.hour = hour + 1;
        if (base.hour >= 24)
        {
            base.hour = 0;
            this.AdvanceDay();
        }
        if (!this.shaken && EClass.rnd(24) == 0 && !EClass._zone.IsRegion)
        {
            Msg.Say("earthquake");
            if (!EClass.core.config.graphic.disableShake)
            {
                Shaker.ShakeCam("earthquake", 1f);
            }
            this.shaken = true;
        }
        EClass.scene.OnChangeHour();
        EClass.world.weather.OnChangeHour();
        EClass.player.OnAdvanceHour();
        EClass.game.quests.OnAdvanceHour();
        EClass._zone.OnAdvanceHour();
        if (EClass._zone.IsRegion)
        {
            EClass._zone.Region.CheckRandomSites();
        }
        foreach (Chara chara in EClass.game.cards.globalCharas.Values)
        {
            if (!chara.IsPCParty && chara.currentZone != EClass.game.activeZone && chara.trait.UseGlobalGoal)
            {
                if (chara.global.goal == null && !chara.IsPCFaction)
                {
                    GlobalGoalAdv globalGoalAdv = new GlobalGoalAdv();
                    globalGoalAdv.SetOwner(chara);
                    globalGoalAdv.Start();
                }
                if (chara.global.goal != null)
                {
                    chara.global.goal.AdvanceHour();
                }
            }
        }
        EClass.pc.RecalculateFOV();
        if (base.hour == 5)
        {
            this.ShipGoods();
            this.ShipPackages();
            this.ShipLetter();
            if (EClass.rnd(30) == 0 && EClass.game.cards.listPackage.Count <= 2)
            {
                this.ShipRandomPackages();
            }
            if (base.month == 10)
            {
                Tutorial.Reserve("season", null);
            }
            if (base.month == 11)
            {
                Tutorial.Reserve("season2", null);
                return;
            }
            Tutorial.Remove("season2");
        }
    }
References EClass._zone, Game.activeZone, AdvanceDay(), GlobalGoal.AdvanceHour(), Game.cards, Region.CheckRandomSites(), EClass.core, Chara.currentZone, EClass.game, Chara.global, CardManager.globalCharas, GlobalData.goal, Date.hour, Chara.IsPCFaction, Chara.IsPCParty, Spatial.IsRegion, CardManager.listPackage, Player.OnAdvanceHour(), QuestManager.OnAdvanceHour(), Zone.OnAdvanceHour(), Scene.OnChangeHour(), Weather.OnChangeHour(), EClass.pc, EClass.player, Game.quests, Card.RecalculateFOV(), Zone.Region, Tutorial.Remove(), Tutorial.Reserve(), EClass.rnd(), Msg.Say(), EClass.scene, GlobalGoal.SetOwner(), shaken, ShipGoods(), ShipLetter(), ShipPackages(), ShipRandomPackages(), VirtualDate.SimulateHour(), GlobalGoal.Start(), Chara.trait, TraitChara.UseGlobalGoal, World.weather, and EClass.world.
Referenced by AdvanceMin(), WidgetArtTool.OnActivate(), and LayerTravel.Refresh().
AdvanceMin()
void GameDate.AdvanceMin (int a) inline
Definition at line 19 of file GameDate.cs.
    {
        EClass.game.sessionMin += a;
        EClass.player.stats.mins += a;
        base.min += a;
        if (base.min >= 60)
        {
            while (base.min >= 60)
            {
                base.min -= 60;
                this.AdvanceHour();
            }
            EClass.screen.RefreshGrading();
        }
        else if (base.min % 3 == 2)
        {
            EClass.screen.RefreshGrading();
        }
        if (EClass._map.footmarks.Count > 0)
        {
            for (int i = EClass._map.footmarks.Count - 1; i >= 0; i--)
            {
                Footmark footmark = EClass._map.footmarks[i];
                footmark.remaining--;
                if (footmark.remaining <= 0)
                {
                    CellDetail detail = footmark.pos.detail;
                    if (detail != null && detail.footmark == footmark)
                    {
                        detail.footmark = null;
                        footmark.pos.cell.TryDespawnDetail();
                    }
                    EClass._map.footmarks.RemoveAt(i);
                }
            }
        }
        EClass.player.countNewline++;
        if (EClass.player.countNewline > EClass.core.config.game.newlineCount)
        {
            Msg.NewLine();
            EClass.player.countNewline = 0;
        }
        EClass.screen.pcOrbit.OnChangeMin();
        foreach (ZoneEvent zoneEvent in EClass._zone.events.list)
        {
            zoneEvent.minElapsed += a;
        }
    }
References EClass._map, EClass._zone, AdvanceHour(), Point.cell, EClass.core, Player.countNewline, Point.detail, Zone.events, CellDetail.footmark, Map.footmarks, ZoneEventManager.list, Msg.NewLine(), PCOrbit.OnChangeMin(), BaseGameScreen.pcOrbit, EClass.player, Footmark.pos, BaseGameScreen.RefreshGrading(), Footmark.remaining, EClass.screen, and Cell.TryDespawnDetail().
Referenced by Chara._Move(), LayerSleep.Advance(), AdvanceSec(), GameUpdater.Update(), and CoreDebug.UpdateInput().
AdvanceMonth()
void GameDate.AdvanceMonth () inline
Definition at line 201 of file GameDate.cs.
    {
        int month = base.month;
        base.month = month + 1;
        if (base.month > 12)
        {
            base.month = 1;
            this.AdvanceYear();
        }
        EClass.player.stats.months++;
        EClass.player.nums.OnAdvanceMonth();
        if (base.month % 2 == 0)
        {
            EClass.player.holyWell++;
        }
        EClass._map.RefreshAllTiles();
        foreach (Thing thing in EClass._map.things)
        {
            if (thing.renderer.hasActor)
            {
                thing.renderer.RefreshSprite();
            }
        }
        EClass.pc.faction.OnAdvanceMonth();
    }
References EClass._map, AdvanceYear(), Chara.faction, CardRenderer.hasActor, Player.holyWell, Date.month, Player.nums, Faction.OnAdvanceMonth(), NumLogManager.OnAdvanceMonth(), EClass.pc, EClass.player, Map.RefreshAllTiles(), CardRenderer.RefreshSprite(), Card.renderer, Player.stats, and Map.things.
Referenced by AdvanceDay().
AdvanceSec()
void GameDate.AdvanceSec (int a) inline
Definition at line 9 of file GameDate.cs.
    {
        base.sec += a;
        if (base.sec >= 60)
        {
            this.AdvanceMin(base.sec / 60);
            base.sec %= 60;
        }
    }
References AdvanceMin().
AdvanceYear()
void GameDate.AdvanceYear () inline
Definition at line 227 of file GameDate.cs.
    {
        int year = base.year;
        base.year = year + 1;
        EClass.player.wellWished = false;
        EClass.player.nums.OnAdvanceYear();
        EClass.world.SendPackage(ThingGen.Create("gift_newyear", -1, -1));
    }
References ThingGen.Create(), Player.nums, NumLogManager.OnAdvanceYear(), EClass.player, World.SendPackage(), EClass.world, and Date.year.
Referenced by AdvanceMonth().
g__Add()
static void< ShipRandomPackages > GameDate.g__Add (string id, int num, ref GameDate::<>c__DisplayClass11_0 A_2) inline static package
Definition at line 499 of file GameDate.cs.
    {
        GameDate.<ShipRandomPackages>g__AddThing|11_1(ThingGen.Create(id, -1, -1), num, ref A_2);
    }
References ThingGen.Create(), g__AddThing(), and ShipRandomPackages().
Referenced by ShipRandomPackages().
g__AddThing()
static void< ShipRandomPackages > GameDate.g__AddThing (Thing t, int num, ref GameDate::<>c__DisplayClass11_0 A_2) inline static package
Definition at line 505 of file GameDate.cs.
    {
        t.SetNum(num);
        A_2.box.AddCard(t);
    }
References Card.AddCard(), and Card.SetNum().
Referenced by g__Add(), and ShipRandomPackages().
ShipGoods()
void GameDate.ShipGoods () inline
Definition at line 236 of file GameDate.cs.
    {
        Thing container_shipping = EClass.game.cards.container_shipping;
        if (container_shipping.things.Count == 0)
        {
            return;
        }
        int num = 0;
        int num2 = 0;
        int num3 = 0;
        int num4 = 0;
        List<Thing> list = new List<Thing>();
        List<string> list2 = new List<string>();
        Zone zone = EClass.game.spatials.Find(EClass.player.uidLastShippedZone);
        if (zone == null || zone.branch == null)
        {
            zone = EClass.pc.homeZone;
        }
        ShippingResult shippingResult = new ShippingResult();
        shippingResult.rawDate = EClass.world.date.GetRaw(0);
        shippingResult.uidZone = zone.uid;
        shippingResult.total = EClass.player.stats.shipMoney;
        shippingResult.hearthLv = zone.branch.lv;
        shippingResult.hearthExp = zone.branch.exp;
        shippingResult.debt = EClass.player.debt;
        foreach (Thing thing in container_shipping.things)
        {
            if (thing.trait.CanBeShipped)
            {
                int price = thing.GetPrice(CurrencyType.Money, true, PriceType.Shipping, null);
                int num5 = price * thing.Num;
                num3 += num5;
                num += thing.Num;
                num2 += EClass.rndHalf(thing.Num * Mathf.Min(15 + price, 10000) / 100 + 1);
                list.Add(thing);
                shippingResult.items.Add(new ShippingResult.Item
                {
                    text = thing.Name,
                    income = num5
                });
            }
        }
        if (list.Count == 0)
        {
            return;
        }
        num2 = num2 / 2 + 1;
        shippingResult.hearthExpGained = num2;
        EClass.pc.homeBranch.log.Add(Msg.Say("shipped_collect"), null);
        foreach (string text in list2)
        {
            EClass.pc.homeBranch.log.Add(text, null);
        }
        int shippingBonus = EClass.player.stats.GetShippingBonus(EClass.player.stats.shipMoney);
        EClass.player.stats.shipNum += num;
        EClass.player.stats.shipMoney += num3;
        int shippingBonus2 = EClass.player.stats.GetShippingBonus(EClass.player.stats.shipMoney);
        if (shippingBonus2 > shippingBonus)
        {
            num4 = shippingBonus2 - shippingBonus;
        }
        foreach (Thing thing2 in list)
        {
            thing2.Destroy();
        }
        Thing thing3 = null;
        Thing thing4 = null;
        string text2 = "";
        if (num3 != 0)
        {
            thing3 = ThingGen.Create("money", -1, -1).SetNum(num3);
        }
        if (num4 != 0)
        {
            thing4 = ThingGen.Create("money2", -1, -1).SetNum(num4);
        }
        if (thing3 != null && thing4 != null)
        {
            text2 = "_and".lang(thing3.Name, thing4.Name, null, null, null);
            SE.Pay();
        }
        else if (thing3 != null || thing4 != null)
        {
            text2 = ((thing3 != null) ? thing3 : thing4).Name;
        }
        EClass.pc.homeBranch.log.Add(Msg.Say((text2 == "") ? "shipped_none" : "shipped", num.ToString() ?? "", text2, null, null), FontColor.Good);
        EClass.player.shippingResults.Add(shippingResult);
        EClass.player.showShippingResult = EClass.core.config.game.showShippingResult;
        for (int i = 0; i < EClass.player.shippingResults.Count - 10; i++)
        {
            EClass.player.shippingResults.RemoveAt(0);
        }
        zone.branch.statistics.ship += num3;
        zone.branch.ModExp(num2);
        if (thing3 != null)
        {
            EClass.pc.Pick(thing3, true, true);
        }
        if (thing4 != null)
        {
            EClass.pc.Pick(thing4, true, true);
        }
    }
References MsgLog.Add(), Zone.branch, Trait.CanBeShipped, Game.cards, CardManager.container_shipping, EClass.core, ThingGen.Create(), World.date, Player.debt, Card.Destroy(), FactionBranch.exp, SpatialManager.Find(), EClass.game, Card.GetPrice(), Date.GetRaw(), Chara.homeBranch, Chara.homeZone, FactionBranch.log, FactionBranch.lv, Card.Name, Card.Num, EClass.pc, Chara.Pick(), EClass.player, EClass.rndHalf(), Msg.Say(), Card.SetNum(), Player.shippingResults, Game.spatials, Player.stats, text, Card.things, Card.trait, Spatial.uid, Player.uidLastShippedZone, and EClass.world.
Referenced by AdvanceHour().
ShipLetter()
void GameDate.ShipLetter () inline
Definition at line 385 of file GameDate.cs.
    {
        int num = -1;
        int lutz = EClass.player.flags.lutz;
        if (EClass.player.stats.days >= 2 && lutz <= 0)
        {
            num = 1;
        }
        else if (EClass.player.stats.days >= 5 && lutz <= 1)
        {
            num = 2;
        }
        else if (EClass.player.stats.days >= 8 && lutz <= 2)
        {
            num = 3;
        }
        else if (EClass.player.stats.days >= 11 && lutz <= 3)
        {
            num = 4;
        }
        else if (EClass.player.stats.days >= 15 && lutz <= 4)
        {
            num = 5;
        }
        else if (EClass.player.stats.days >= 17 && lutz <= 5)
        {
            num = 6;
        }
        else if (EClass.player.stats.days >= 30 && lutz <= 6)
        {
            num = 7;
        }
        else if (EClass.player.stats.days >= 50 && lutz <= 7)
        {
            num = 8;
        }
        if (num != -1)
        {
            EClass.player.flags.lutz = num;
            Thing thing = ThingGen.Create("letter", -1, -1);
            thing.SetStr(53, "lutz_" + num.ToString());
            EClass.world.SendPackage(thing);
        }
    }
References ThingGen.Create(), Player.flags, EClass.player, World.SendPackage(), BaseCard.SetStr(), Player.stats, and EClass.world.
Referenced by AdvanceHour().
ShipPackages()
void GameDate.ShipPackages () inline
Definition at line 340 of file GameDate.cs.
    {
        Thing container_deliver = EClass.game.cards.container_deliver;
        if (container_deliver.things.Count == 0)
        {
            return;
        }
        int num = 0;
        while (container_deliver.things.Count > 0)
        {
            num++;
            if (num > 100)
            {
                Debug.Log("too many tries");
                return;
            }
            int uidZone = 0;
            foreach (Thing thing in container_deliver.things)
            {
                int @int = thing.GetInt(102, null);
                if (@int != 0)
                {
                    uidZone = @int;
                    thing.SetInt(102, 0);
                    break;
                }
            }
            int num2 = 20;
            Thing thing2 = ThingGen.CreateCardboardBox(uidZone);
            for (int i = container_deliver.things.Count - 1; i >= 0; i--)
            {
                Thing c = container_deliver.things[i];
                thing2.AddCard(c);
                num2 += 5;
                if (thing2.things.IsFull(0))
                {
                    break;
                }
            }
            EClass.world.SendPackage(thing2);
            Thing bill = ThingGen.CreateBill(num2, false);
            EClass.pc.faction.TryPayBill(bill);
        }
    }
References Card.AddCard(), Game.cards, CardManager.container_deliver, ThingGen.CreateBill(), ThingGen.CreateCardboardBox(), Chara.faction, EClass.game, BaseCard.GetInt(), ThingContainer.IsFull(), EClass.pc, World.SendPackage(), BaseCard.SetInt(), Card.things, Faction.TryPayBill(), and EClass.world.
Referenced by AdvanceHour().
ShipRandomPackages()
void GameDate.ShipRandomPackages () inline
Definition at line 430 of file GameDate.cs.
    {
        GameDate.<>c__DisplayClass11_0 CS$<>8__locals1;
        CS$<>8__locals1.box = ThingGen.CreateCardboardBox(-1);
        TraitContainer traitContainer = CS$<>8__locals1.box.trait as TraitContainer;
        bool flag = EClass.pc.homeBranch.policies.IsActive(2708, -1);
        if (EClass.rnd(EClass.debug.enable ? 1 : 100) == 0 && !EClass.player.flags.statueShipped)
        {
            EClass.player.flags.statueShipped = true;
            GameDate.<ShipRandomPackages>g__Add|11_0("statue_weird", 1, ref CS$<>8__locals1);
            flag = false;
        }
        else if (EClass.rnd(10) == 0)
        {
            GameDate.<ShipRandomPackages>g__Add|11_0("234", 1, ref CS$<>8__locals1);
        }
        else if (EClass.rnd(5) == 0)
        {
            GameDate.<ShipRandomPackages>g__AddThing|11_1(ThingGen.CreateFromCategory("junk", -1), 1, ref CS$<>8__locals1);
        }
        else if (EClass.rnd(10) == 0)
        {
            GameDate.<ShipRandomPackages>g__AddThing|11_1(ThingGen.CreateFromTag("garbage", -1), 1, ref CS$<>8__locals1);
        }
        else if (EClass.rnd(8) == 0)
        {
            CardRow cardRow = SpawnList.Get("chara", null, null).Select(EClass.pc.LV + 10, -1);
            traitContainer.PutChara(cardRow.id);
            flag = false;
        }
        else if (EClass.rnd(8) == 0)
        {
            GameDate.<ShipRandomPackages>g__Add|11_0("plat", 1 + EClass.rnd(4), ref CS$<>8__locals1);
            flag = false;
        }
        else if (EClass.rnd(8) == 0)
        {
            GameDate.<ShipRandomPackages>g__Add|11_0("money2", 1 + EClass.rnd(4), ref CS$<>8__locals1);
            flag = false;
        }
        else
        {
            string id = "trash2";
            if (EClass.rnd(3) == 0)
            {
                id = "trash1";
            }
            if (EClass.rnd(3) == 0)
            {
                id = ((EClass.rnd(3) == 0) ? "529" : "1170");
            }
            if (EClass.rnd(5) == 0)
            {
                id = "_poop";
            }
            if (EClass.rnd(100) == 0)
            {
                id = "goodness";
                flag = false;
            }
            GameDate.<ShipRandomPackages>g__Add|11_0(id, 1, ref CS$<>8__locals1);
        }
        if (!flag)
        {
            EClass.world.SendPackage(CS$<>8__locals1.box);
        }
    }
References ThingGen.CreateCardboardBox(), ThingGen.CreateFromCategory(), ThingGen.CreateFromTag(), EClass.debug, CoreDebug.enable, Player.flags, g__Add(), g__AddThing(), SpawnList.Get(), Chara.homeBranch, CardRow.id, PolicyManager.IsActive(), Card.LV, EClass.pc, EClass.player, FactionBranch.policies, TraitBaseContainer.PutChara(), EClass.rnd(), SpawnList.Select(), World.SendPackage(), ShipRandomPackages(), and EClass.world.
Referenced by AdvanceHour(), g__Add(), and ShipRandomPackages().
Member Data Documentation
minPerRound
const int GameDate.minPerRound = 5 static
Definition at line 514 of file GameDate.cs.
shaken
bool GameDate.shaken
Definition at line 512 of file GameDate.cs.
Referenced by AdvanceHour().
The documentation for this class was generated from the following file:
Elin/GameDate.cs