Elin Decompiled Documentation: Empyrean.ColorPicker.HueSlider Class Reference
Empyrean.ColorPicker.HueSlider Class Reference
Public Member Functions
void Init ()
void OnValueChanged (float value)
void SetSliderValueAndSendEvent (float value)
Static Public Member Functions
static Color[] GenerateHsvSpectrum ()
Public Attributes
EventAwareSlider slider
Properties
float value [get, set]
Events
Action< float > HueValueChanged
Private Member Functions
void GenerateSliderTexture ()
Private Attributes
RawImage hueSliderBackground
Detailed Description
Definition at line 8 of file HueSlider.cs.
Member Function Documentation
GenerateHsvSpectrum()
static Color[] Empyrean.ColorPicker.HueSlider.GenerateHsvSpectrum () inline static
Definition at line 55 of file HueSlider.cs.
    {
        Color[] array = new Color[360];
        for (int i = 0; i < 360; i++)
        {
            array[i] = Colorist.HSVtoRGB(i, 1f, 1f);
        }
        return array;
    }
References Color, and Empyrean.Utils.Colorist.HSVtoRGB().
Referenced by Empyrean.ColorPicker.HueSlider.GenerateSliderTexture(), and Empyrean.ColorPicker.SliderBackgroundController.GenerateSliderTexture().
GenerateSliderTexture()
void Empyrean.ColorPicker.HueSlider.GenerateSliderTexture () inline private
Definition at line 43 of file HueSlider.cs.
    {
        Color[] array = GenerateHsvSpectrum();
        Texture2D texture2D = new Texture2D(1, array.Length);
        for (int i = 0; i < texture2D.height; i++)
        {
            texture2D.SetPixel(1, i, array[i]);
        }
        texture2D.Apply();
        hueSliderBackground.texture = texture2D;
    }
References Color, and Empyrean.ColorPicker.HueSlider.GenerateHsvSpectrum().
Referenced by Empyrean.ColorPicker.HueSlider.Init().
Init()
void Empyrean.ColorPicker.HueSlider.Init () inline
Definition at line 32 of file HueSlider.cs.
    {
        slider.onValueChanged.AddListener(OnValueChanged);
        GenerateSliderTexture();
    }
References Empyrean.ColorPicker.HueSlider.GenerateSliderTexture(), Empyrean.ColorPicker.HueSlider.OnValueChanged(), and Empyrean.ColorPicker.HueSlider.slider.
Referenced by Empyrean.ColorPicker.ColorPicker.Init().
OnValueChanged()
void Empyrean.ColorPicker.HueSlider.OnValueChanged (float value) inline
Definition at line 38 of file HueSlider.cs.
    {
        this.HueValueChanged(value);
    }
References Empyrean.ColorPicker.HueSlider.HueValueChanged.
Referenced by Empyrean.ColorPicker.HueSlider.Init().
SetSliderValueAndSendEvent()
void Empyrean.ColorPicker.HueSlider.SetSliderValueAndSendEvent (float value) inline
Definition at line 65 of file HueSlider.cs.
    {
        slider.SetValue(value, sendEvent: true);
    }
References EventAwareSlider.SetValue(), Empyrean.ColorPicker.HueSlider.slider, and Empyrean.ColorPicker.HueSlider.value.
Member Data Documentation
hueSliderBackground
RawImage Empyrean.ColorPicker.HueSlider.hueSliderBackground private
Definition at line 14 of file HueSlider.cs.
slider
EventAwareSlider Empyrean.ColorPicker.HueSlider.slider
Definition at line 11 of file HueSlider.cs.
Referenced by Empyrean.ColorPicker.HueSlider.Init(), and Empyrean.ColorPicker.HueSlider.SetSliderValueAndSendEvent().
Property Documentation
value
float Empyrean.ColorPicker.HueSlider.value get set
Definition at line 16 of file HueSlider.cs.
    {
        get
        {
            return slider.value;
        }
        set
        {
            slider.SetValue(value, sendEvent: false);
        }
    }
Referenced by Empyrean.ColorPicker.ColorPicker.OnColorPickedFromPalette(), Empyrean.ColorPicker.HueSlider.SetSliderValueAndSendEvent(), and Empyrean.ColorPicker.ColorPicker.UpdateColor().
Event Documentation
HueValueChanged
Action<float> Empyrean.ColorPicker.HueSlider.HueValueChanged
Initial value:
= delegate
    {
    }
Definition at line 28 of file HueSlider.cs.
Referenced by Empyrean.ColorPicker.HueSlider.OnValueChanged().
The documentation for this class was generated from the following file:
Elin/Plugins.UI/Empyrean/ColorPicker/HueSlider.cs