Elin Decompiled Documentation: ReligionManager Class Reference
ReligionManager Class Reference
Public Member Functions
void SetOwner ()
void OnCreateGame ()
void OnLoad ()
Religion Find (string id)
Religion GetRandomReligion (bool onlyJoinable=true, bool includeMinor=false)
Public Attributes
Dictionary< string, Religion > dictAll = new Dictionary<string, Religion>()
List< Religion > list = new List<Religion>()
ReligionEyth Eyth = new ReligionEyth()
ReligionWind Wind = new ReligionWind()
ReligionEarth Earth = new ReligionEarth()
ReligionHealing Healing = new ReligionHealing()
ReligionLuck Luck = new ReligionLuck()
ReligionMachine Machine = new ReligionMachine()
ReligionElement Element = new ReligionElement()
ReligionHarvest Harvest = new ReligionHarvest()
ReligionOblivion Oblivion = new ReligionOblivion()
ReligionHarmony Harmony = new ReligionHarmony()
ReligionTrickery Trickery = new ReligionTrickery()
ReligionMoonShadow MoonShadow = new ReligionMoonShadow()
ReligionStrife Strife = new ReligionStrife()
Additional Inherited Members
Static Public Member Functions inherited from EClass
static int rnd (int a)
static int curve (int a, int start, int step, int rate=75)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Static Public Attributes inherited from EClass
static Core core
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Detailed Description
Definition at line 5 of file ReligionManager.cs.
Member Function Documentation
Find()
Religion ReligionManager.Find (string id) inline
Definition at line 81 of file ReligionManager.cs.
    {
        foreach (Religion value in dictAll.Values)
        {
            if (value.id == id)
            {
                return value;
            }
        }
        return null;
    }
References dictAll, and Religion.id.
Referenced by Thing.WriteNote().
GetRandomReligion()
Religion ReligionManager.GetRandomReligion (bool onlyJoinable = true, bool includeMinor = false) inline
Definition at line 93 of file ReligionManager.cs.
    {
        return list.Where((Religion a) => (!onlyJoinable || a.CanJoin) && (includeMinor || !a.IsMinorGod)).RandomItem();
    }
References Religion.CanJoin, Religion.IsMinorGod, and list.
Referenced by GameLang.ConvertDrama(), Chara.OnCreate(), TraitAltar.OnCreate(), TraitAltar.OnImportMap(), and Zone.SpawnAltar().
OnCreateGame()
void ReligionManager.OnCreateGame () inline
Definition at line 63 of file ReligionManager.cs.
    {
        SetOwner();
        foreach (Religion item in list)
        {
            item.Init();
        }
    }
References item, list, and SetOwner().
Referenced by Game._Create().
OnLoad()
void ReligionManager.OnLoad () inline
Definition at line 72 of file ReligionManager.cs.
    {
        SetOwner();
        foreach (Religion value in dictAll.Values)
        {
            value.OnLoad();
        }
    }
References dictAll, Religion.OnLoad(), and SetOwner().
Referenced by Game.OnLoad().
SetOwner()
void ReligionManager.SetOwner () inline
Definition at line 50 of file ReligionManager.cs.
    {
        list = new List<Religion>
        {
            Eyth, Wind, Earth, Healing, Luck, Machine, Element, Harvest, Oblivion, Harmony,
            Trickery, MoonShadow, Strife
        };
        foreach (Religion item in list)
        {
            dictAll.Add(item.id, item);
        }
    }
References dictAll, Earth, Element, Eyth, Harmony, Harvest, Healing, item, list, Luck, Machine, MoonShadow, Oblivion, Strife, Trickery, and Wind.
Referenced by OnCreateGame(), and OnLoad().
Member Data Documentation
dictAll
Dictionary<string, Religion> ReligionManager.dictAll = new Dictionary<string, Religion>()
Definition at line 7 of file ReligionManager.cs.
Referenced by Find(), TraitBaseSpellbook.OnCreate(), TraitFollower.OnCreate(), OnLoad(), TraitBaseSpellbook.OnRead(), LayerFactions.RefreshFactions(), ContentFaction.RefreshFactions(), Chara.SetFaith(), TraitBaseSpellbook.SetName(), SetOwner(), CoreDebug.Test_GodTalk(), and Zone.TrySpawnFollower().
Earth
ReligionEarth ReligionManager.Earth = new ReligionEarth()
Definition at line 18 of file ReligionManager.cs.
Referenced by Religion.IsValidArtifact(), Religion.Reforge(), and SetOwner().
Element
ReligionElement ReligionManager.Element = new ReligionElement()
Definition at line 30 of file ReligionManager.cs.
Referenced by Religion.IsValidArtifact(), ActEffect.Proc(), Religion.Reforge(), and SetOwner().
Eyth
ReligionEyth ReligionManager.Eyth = new ReligionEyth()
Definition at line 12 of file ReligionManager.cs.
Referenced by FactionBranch.OnCreate(), Player.OnCreateGame(), TraitBaseSpellbook.OnRead(), SetOwner(), and Thing.WriteNote().
Harmony
ReligionHarmony ReligionManager.Harmony = new ReligionHarmony()
Definition at line 39 of file ReligionManager.cs.
Referenced by SetOwner().
Harvest
ReligionHarvest ReligionManager.Harvest = new ReligionHarvest()
Definition at line 33 of file ReligionManager.cs.
Referenced by Card.GetPrice(), Religion.IsValidArtifact(), Religion.Reforge(), and SetOwner().
Healing
ReligionHealing ReligionManager.Healing = new ReligionHealing()
Definition at line 21 of file ReligionManager.cs.
Referenced by DramaOutcome.convert_Jure(), Religion.IsValidArtifact(), Religion.Reforge(), SetOwner(), and Chara.ShowDialog().
list
List<Religion> ReligionManager.list = new List<Religion>()
Definition at line 9 of file ReligionManager.cs.
Referenced by LayerFaith.Activate(), GetRandomReligion(), OnCreateGame(), Player.OnStartNewGame(), Religion.Punish(), SetOwner(), and ActEffect.Wish().
Luck
ReligionLuck ReligionManager.Luck = new ReligionLuck()
Definition at line 24 of file ReligionManager.cs.
Referenced by Religion.IsValidArtifact(), FactionBranch.OnSimulateDay(), Religion.Reforge(), and SetOwner().
Machine
ReligionMachine ReligionManager.Machine = new ReligionMachine()
Definition at line 27 of file ReligionManager.cs.
Referenced by Religion.IsValidArtifact(), Religion.Reforge(), and SetOwner().
MoonShadow
ReligionMoonShadow ReligionManager.MoonShadow = new ReligionMoonShadow()
Definition at line 45 of file ReligionManager.cs.
Referenced by Chara.Cuddle(), Religion.IsValidArtifact(), Religion.LeaveFaith(), Chara.OnCreate(), Religion.Reforge(), and SetOwner().
Oblivion
ReligionOblivion ReligionManager.Oblivion = new ReligionOblivion()
Definition at line 36 of file ReligionManager.cs.
Referenced by SetOwner().
Strife
ReligionStrife ReligionManager.Strife = new ReligionStrife()
Definition at line 48 of file ReligionManager.cs.
Referenced by Religion.IsValidArtifact(), Religion.Reforge(), and SetOwner().
Trickery
ReligionTrickery ReligionManager.Trickery = new ReligionTrickery()
Definition at line 42 of file ReligionManager.cs.
Referenced by Religion.IsValidArtifact(), Religion.LeaveFaith(), Chara.OnCreate(), Zone_SubTown.OnGenerateRooms(), Religion.Reforge(), and SetOwner().
Wind
ReligionWind ReligionManager.Wind = new ReligionWind()
Definition at line 15 of file ReligionManager.cs.
Referenced by Religion.IsValidArtifact(), Religion.Reforge(), and SetOwner().
The documentation for this class was generated from the following file:
Elin/ReligionManager.cs