Elin Decompiled Documentation: Applibot.CustomImageBase Class Reference
Applibot.CustomImageBase Class Reference
Public Member Functions
Material GetModifiedMaterial (Material baseMaterial)
void DestroyMaterial ()
Protected Member Functions
virtual void UpdateMaterial (Material baseMaterial)
void OnEnable ()
void OnDisable ()
void OnDestroy ()
Protected Attributes
Material material
Properties
CanvasScaler canvasScaler [get]
Graphic graphic [get]
Private Member Functions
void OnDidApplyAnimationProperties ()
void SetAtlasInfo ()
Private Attributes
Graphic _graphic
Image _image
CanvasScaler _canvasScaler
int _textureRectId = Shader.PropertyToID("_textureRect")
Detailed Description
Definition at line 9 of file CustomImageBase.cs.
Member Function Documentation
DestroyMaterial()
void Applibot.CustomImageBase.DestroyMaterial () inline
Definition at line 115 of file CustomImageBase.cs.
    {
        UnityEngine.Object.Destroy(material);
        material = null;
    }
References Applibot.CustomImageBase.material.
Referenced by Applibot.OutlineImage.Capture(), Applibot.CustomImageBase.OnDestroy(), and Applibot.CustomImageBase.OnDisable().
GetModifiedMaterial()
Material Applibot.CustomImageBase.GetModifiedMaterial (Material baseMaterial) inline
Definition at line 47 of file CustomImageBase.cs.
    {
        if (!base.isActiveAndEnabled || graphic == null)
        {
            return baseMaterial;
        }
        UpdateMaterial(baseMaterial);
        SetAtlasInfo();
        return material;
    }
References Applibot.CustomImageBase.graphic, Applibot.CustomImageBase.material, Applibot.CustomImageBase.SetAtlasInfo(), and Applibot.CustomImageBase.UpdateMaterial().
OnDestroy()
void Applibot.CustomImageBase.OnDestroy () inline protected
Definition at line 107 of file CustomImageBase.cs.
    {
        if (material != null)
        {
            DestroyMaterial();
        }
    }
References Applibot.CustomImageBase.DestroyMaterial(), and Applibot.CustomImageBase.material.
OnDidApplyAnimationProperties()
void Applibot.CustomImageBase.OnDidApplyAnimationProperties () inline private
Definition at line 58 of file CustomImageBase.cs.
    {
        if (base.isActiveAndEnabled && !(graphic == null))
        {
            graphic.SetMaterialDirty();
        }
    }
References Applibot.CustomImageBase.graphic.
OnDisable()
void Applibot.CustomImageBase.OnDisable () inline protected
Definition at line 95 of file CustomImageBase.cs.
    {
        if (material != null)
        {
            DestroyMaterial();
        }
        if (graphic != null)
        {
            graphic.SetMaterialDirty();
        }
    }
References Applibot.CustomImageBase.DestroyMaterial(), Applibot.CustomImageBase.graphic, and Applibot.CustomImageBase.material.
OnEnable()
void Applibot.CustomImageBase.OnEnable () inline protected
Definition at line 86 of file CustomImageBase.cs.
    {
        if (!(graphic == null))
        {
            _image = graphic as Image;
            graphic.SetMaterialDirty();
        }
    }
References Applibot.CustomImageBase._image, and Applibot.CustomImageBase.graphic.
SetAtlasInfo()
void Applibot.CustomImageBase.SetAtlasInfo () inline private
Definition at line 70 of file CustomImageBase.cs.
    {
        if (!(_image == null))
        {
            if (!_image.sprite.packed)
            {
                material.DisableKeyword("USE_ATLAS");
                return;
            }
            Rect textureRect = _image.sprite.textureRect;
            Vector4 value = new Vector4(textureRect.x, textureRect.y, textureRect.width, textureRect.height);
            material.SetVector(_textureRectId, value);
            material.EnableKeyword("USE_ATLAS");
        }
    }
References Applibot.CustomImageBase._image, Applibot.CustomImageBase._textureRectId, and Applibot.CustomImageBase.material.
Referenced by Applibot.CustomImageBase.GetModifiedMaterial().
UpdateMaterial()
virtual void Applibot.CustomImageBase.UpdateMaterial (Material baseMaterial) inline protected virtual
Reimplemented in Applibot.DissolveImage, Applibot.Glitch, Applibot.NormalDissolve, Applibot.OutlineImage, Applibot.RadialBlurImage, and Applibot.UICustomBlend.
Definition at line 66 of file CustomImageBase.cs.
    {
    }
Referenced by Applibot.CustomImageBase.GetModifiedMaterial().
Member Data Documentation
_canvasScaler
CanvasScaler Applibot.CustomImageBase._canvasScaler private
Definition at line 19 of file CustomImageBase.cs.
_graphic
Graphic Applibot.CustomImageBase._graphic private
Definition at line 12 of file CustomImageBase.cs.
_image
Image Applibot.CustomImageBase._image private
Definition at line 15 of file CustomImageBase.cs.
Referenced by Applibot.CustomImageBase.OnEnable(), and Applibot.CustomImageBase.SetAtlasInfo().
_textureRectId
int Applibot.CustomImageBase._textureRectId = Shader.PropertyToID("_textureRect") private
Definition at line 21 of file CustomImageBase.cs.
Referenced by Applibot.CustomImageBase.SetAtlasInfo().
material
Material Applibot.CustomImageBase.material protected
Definition at line 17 of file CustomImageBase.cs.
Referenced by Applibot.OutlineImage.Capture(), Applibot.CustomImageBase.DestroyMaterial(), Applibot.CustomImageBase.GetModifiedMaterial(), Applibot.CustomImageBase.OnDestroy(), Applibot.CustomImageBase.OnDisable(), Applibot.CustomImageBase.SetAtlasInfo(), Applibot.DissolveImage.UpdateMaterial(), Applibot.Glitch.UpdateMaterial(), Applibot.NormalDissolve.UpdateMaterial(), Applibot.OutlineImage.UpdateMaterial(), Applibot.RadialBlurImage.UpdateMaterial(), and Applibot.UICustomBlend.UpdateMaterial().
Property Documentation
canvasScaler
CanvasScaler Applibot.CustomImageBase.canvasScaler get protected
Definition at line 23 of file CustomImageBase.cs.
    {
        get
        {
            if (_canvasScaler == null)
            {
                _canvasScaler = graphic.canvas.GetComponent<CanvasScaler>();
            }
            return _canvasScaler;
        }
    }
graphic
Graphic Applibot.CustomImageBase.graphic get
Definition at line 35 of file CustomImageBase.cs.
    {
        get
        {
            if (_graphic == null)
            {
                _graphic = GetComponent<Graphic>();
            }
            return _graphic;
        }
    }
Referenced by Applibot.CustomImageBase.GetModifiedMaterial(), Applibot.CustomImageBase.OnDidApplyAnimationProperties(), Applibot.CustomImageBase.OnDisable(), and Applibot.CustomImageBase.OnEnable().
The documentation for this class was generated from the following file:
Elin/Plugins.UI/Applibot/CustomImageBase.cs