Elin Decompiled Documentation: MapSubset Class Reference
MapSubset Class Reference
Public Member Functions
void OnSave (string _id)
void Apply ()
Static Public Member Functions
static bool Exist (string id)
static void Save (string id)
static MapSubset Load (string id)
Static Public Member Functions inherited from EClass
static int rndSeed (int a, int seed)
static int rnd (long a)
static int rnd (int a)
static int curve (int a, int start, int step, int rate=75)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Public Attributes
string id
List< int > listClear = new List<int>()
SerializedCards serializedCards = new SerializedCards()
Additional Inherited Members
Static Public Attributes inherited from EClass
static Core core
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Detailed Description
Definition at line 6 of file MapSubset.cs.
Member Function Documentation
Apply()
void MapSubset.Apply () inline
Definition at line 60 of file MapSubset.cs.
    {
        Debug.Log(listClear.Count);
        foreach (int item in listClear)
        {
            Cell cell = EClass._map.GetCell(item);
            cell.isClearArea = true;
            cell.Things.ForeachReverse(delegate(Thing t)
            {
                t.Destroy();
            });
        }
        serializedCards.Restore(EClass._map, null, addToZone: true);
    }
References EClass._map, Debug, Card.Destroy(), Map.GetCell(), item, listClear, SerializedCards.Restore(), serializedCards, and Cell.Things.
Exist()
static bool MapSubset.Exist (string id) inline static
Definition at line 17 of file MapSubset.cs.
    {
        return File.Exists(CorePath.ZoneSave + EClass._zone.idExport + "_" + id + ".s");
    }
References EClass._zone, Zone.idExport, and CorePath.ZoneSave.
Referenced by CoreDebug.UpdateInput().
Load()
static MapSubset MapSubset.Load (string id) inline static
Definition at line 33 of file MapSubset.cs.
    {
        return GameIO.LoadFile<MapSubset>(CorePath.ZoneSave + EClass._zone.idExport + "_" + id + ".s");
    }
OnSave()
void MapSubset.OnSave (string _id) inline
Definition at line 38 of file MapSubset.cs.
    {
        id = _id;
        listClear.Clear();
        EClass._map.ForeachCell(delegate(Cell c)
        {
            if (c.isClearArea)
            {
                listClear.Add(c.index);
            }
        });
        serializedCards.cards.Clear();
        foreach (Card card in EClass._map.Cards)
        {
            if (card.isSubsetCard)
            {
                serializedCards.Add(card);
            }
        }
        Debug.Log(listClear.Count);
    }
References EClass._map, SerializedCards.Add(), card, Map.Cards, SerializedCards.cards, Debug, Map.ForeachCell(), Cell.isClearArea, listClear, and serializedCards.
Referenced by Save().
Save()
static void MapSubset.Save (string id) inline static
Definition at line 22 of file MapSubset.cs.
    {
        if (EClass._zone.subset == null)
        {
            EClass._zone.subset = new MapSubset();
        }
        EClass._zone.subset.OnSave(id);
        EClass._zone.idCurrentSubset = id;
        GameIO.SaveFile(CorePath.ZoneSave + EClass._zone.idExport + "_" + id + ".s", EClass._zone.subset);
    }
References EClass._zone, id, Zone.idExport, OnSave(), GameIO.SaveFile(), Zone.subset, and CorePath.ZoneSave.
Referenced by CoreDebug.UpdateInput().
Member Data Documentation
id
string MapSubset.id
Definition at line 9 of file MapSubset.cs.
Referenced by Save().
listClear
List<int> MapSubset.listClear = new List<int>()
Definition at line 12 of file MapSubset.cs.
Referenced by Apply(), and OnSave().
serializedCards
SerializedCards MapSubset.serializedCards = new SerializedCards()
Definition at line 15 of file MapSubset.cs.
Referenced by Apply(), and OnSave().
The documentation for this class was generated from the following file:
Elin/MapSubset.cs