Elin Decompiled Documentation: ZoneEventDefenseGame Class Reference
ZoneEventDefenseGame Class Reference
Public Member Functions
virtual Chara CreateChara ()
override void OnVisit ()
void NextWave (int add=0)
override void _OnTickRound ()
void Horn_Next ()
void Horn_Retreat ()
void Horn_Ally ()
override void OnCharaDie (Chara c)
Public Member Functions inherited from ZoneEventQuest
void Spawn (int num=1)
void SpawnBoss (bool evolve=false)
void AggroEnemy (int chance=100)
sealed override void OnTickRound ()
virtual void _OnTickRound ()
virtual ZoneInstance.Status OnReachTimeLimit ()
Public Member Functions inherited from ZoneEvent
virtual string GetText ()
void Tick (float delta)
void Init ()
void OnSimulateHour ()
virtual void OnVisit ()
virtual void OnInit ()
virtual void OnFirstTick ()
virtual void OnTick ()
virtual void OnTickRound ()
virtual void OnKill ()
virtual void OnCharaDie (Chara c)
virtual void OnLeaveZone ()
virtual void OnLoad ()
void Kill ()
Public Attributes
int wave
int turns
int hornTimer
int kills
int allyCall
int allyTimer
int bonus
bool retreated
Public Attributes inherited from ZoneEventQuest
int uidQuest
List< int > enemies = new List<int>()
Public Attributes inherited from ZoneEvent
float time
int rounds
int hoursElapsed
int minElapsed
Zone zone
bool firstTick = true
Properties
ZoneInstanceRandomQuest instance [get]
bool CanRetreat [get]
bool CanCallAlly [get]
override string TextWidgetDate [get]
Properties inherited from ZoneEventQuest
Quest quest [get]
virtual bool WarnBoss [get]
virtual bool CountEnemy [get]
virtual int TimeLimit [get]
Properties inherited from ZoneEvent
SourceQuest.Row source [get]
virtual string id [get]
virtual string TextWidgetDate [get]
virtual float roundInterval [get]
virtual Playlist playlist [get]
virtual bool debugSkip [get]
virtual string RefStr2 [get]
virtual string RefStr3 [get]
virtual int hoursToKill [get]
virtual bool HasReport [get]
string Name [get]
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Additional Inherited Members
Static Public Member Functions inherited from EClass
static int rndSeed (int a, int seed)
static int rnd (long a)
static int rnd (int a)
static int curve (int a, int start, int step, int rate=75)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Static Public Attributes inherited from EClass
static Core core
Detailed Description
Definition at line 4 of file ZoneEventDefenseGame.cs.
Member Function Documentation
_OnTickRound()
override void ZoneEventDefenseGame._OnTickRound () inline virtual
Reimplemented from ZoneEventQuest.
Definition at line 94 of file ZoneEventDefenseGame.cs.
    {
        QuestDefenseGame.lastWave = wave;
        QuestDefenseGame.bonus = bonus;
        Debug.Log("wave:" + wave + " turns:" + turns + " rounds:" + rounds);
        turns++;
        if (hornTimer > 0)
        {
            hornTimer--;
        }
        if (turns <= 3 + base.quest.difficulty)
        {
            Spawn();
        }
        if (turns == 10 && wave % 5 == 0)
        {
            Rand.SetSeed(wave + base.quest.uid);
            SpawnBoss(((wave >= 10) ? (wave * 2) : 0) > EClass.rnd(100));
            Rand.SetSeed();
        }
        if (turns == 20)
        {
            NextWave();
        }
        AggroEnemy();
        if (allyTimer > 0)
        {
            allyTimer--;
            if (allyTimer == 0)
            {
                allyCall--;
            }
        }
    }
References ZoneEventQuest.AggroEnemy(), allyCall, allyTimer, bonus, Debug, hornTimer, NextWave(), EClass.rnd(), ZoneEvent.rounds, Rand.SetSeed(), ZoneEventQuest.Spawn(), ZoneEventQuest.SpawnBoss(), turns, and wave.
CreateChara()
virtual Chara ZoneEventDefenseGame.CreateChara () inline virtual
Definition at line 58 of file ZoneEventDefenseGame.cs.
    {
        return CharaGen.CreateFromFilter("c_wilds");
    }
References CharaGen.CreateFromFilter().
Horn_Ally()
void ZoneEventDefenseGame.Horn_Ally () inline
Definition at line 157 of file ZoneEventDefenseGame.cs.
    {
        SE.Play("warhorn");
        Msg.Say("warhorn");
        ActEffect.ProcAt(EffectId.Summon, 100, BlessedState.Normal, EClass.pc, EClass.pc, EClass.pc.pos, isNeg: false, new ActRef
        {
            n1 = "special_force"
        });
        allyCall++;
        allyTimer += 100;
    }
References allyCall, allyTimer, EClass.pc, Card.pos, ActEffect.ProcAt(), and Msg.Say().
Referenced by TraitCoreDefense.TrySetAct().
Horn_Next()
void ZoneEventDefenseGame.Horn_Next () inline
Definition at line 129 of file ZoneEventDefenseGame.cs.
    {
        Msg.Say("defense_start");
        int add = 0;
        if (turns <= 3)
        {
            Msg.Say("defense_bonus", bonus.ToString() ?? "");
            bonus++;
            add = 1 + base.quest.difficulty;
        }
        NextWave(add);
        hornTimer += 10;
        if (hornTimer > 100)
        {
            hornTimer = 100;
        }
    }
References bonus, hornTimer, NextWave(), Msg.Say(), and turns.
Referenced by TraitCoreDefense.TrySetAct().
Horn_Retreat()
void ZoneEventDefenseGame.Horn_Retreat () inline
Definition at line 147 of file ZoneEventDefenseGame.cs.
    {
        SE.Play("warhorn");
        Msg.Say("warhorn");
        Msg.Say("defense_retreat");
        retreated = true;
        instance.status = ZoneInstance.Status.Success;
        ActEffect.Proc(EffectId.Evac, EClass.pc);
    }
References EClass.pc, ActEffect.Proc(), retreated, and Msg.Say().
Referenced by TraitCoreDefense.TrySetAct().
NextWave()
void ZoneEventDefenseGame.NextWave (int add = 0) inline
Definition at line 82 of file ZoneEventDefenseGame.cs.
    {
        wave++;
        turns = 0;
        EClass._zone._dangerLv += ((EClass._zone.DangerLv >= 100) ? (EClass._zone.DangerLv / 100 * 5 + 5) : 5);
        SE.Play("warhorn");
        Msg.Say("warhorn");
        Msg.Say("defense_wave", wave.ToString() ?? "", EClass._zone.DangerLv.ToString() ?? "");
        Spawn(2 + base.quest.difficulty + add);
        AggroEnemy();
    }
References EClass._zone, ZoneEventQuest.AggroEnemy(), Zone.DangerLv, Msg.Say(), ZoneEventQuest.Spawn(), turns, and wave.
Referenced by _OnTickRound(), Horn_Next(), and OnVisit().
OnCharaDie()
override void ZoneEventDefenseGame.OnCharaDie (Chara c) inline virtual
Reimplemented from ZoneEvent.
Definition at line 169 of file ZoneEventDefenseGame.cs.
    {
        if (!c.IsPCParty && !c.IsPCPartyMinion)
        {
            kills++;
        }
    }
References Chara.IsPCParty, Chara.IsPCPartyMinion, and kills.
OnVisit()
override void ZoneEventDefenseGame.OnVisit () inline virtual
Reimplemented from ZoneEvent.
Definition at line 63 of file ZoneEventDefenseGame.cs.
    {
        if (EClass.game.isLoading)
        {
            QuestDefenseGame.lastWave = wave;
            QuestDefenseGame.bonus = bonus;
            return;
        }
        int num = (base.quest.FameContent ? (EClass.pc.FameLv / 100 * 50) : 0);
        EClass._zone._dangerLv = 5 + num;
        bonus += num / 10;
        Point nearestPoint = EClass._map.GetCenterPos().GetNearestPoint(allowBlock: false, allowChara: false);
        EClass._zone.AddCard(ThingGen.Create("stone_defense"), nearestPoint).Install().isNPCProperty = true;
        EClass._zone.AddCard(ThingGen.Create("core_defense"), nearestPoint).Install().isNPCProperty = false;
        EClass._zone.SetBGM(107);
        Msg.Say("defense_start");
        NextWave();
    }
References EClass._map, EClass._zone, Zone.AddCard(), bonus, ThingGen.Create(), EClass.game, MapBounds.GetCenterPos(), Point.GetNearestPoint(), Game.isLoading, Card.isNPCProperty, NextWave(), Msg.Say(), Zone.SetBGM(), and wave.
Member Data Documentation
allyCall
int ZoneEventDefenseGame.allyCall
Definition at line 19 of file ZoneEventDefenseGame.cs.
Referenced by _OnTickRound(), and Horn_Ally().
allyTimer
int ZoneEventDefenseGame.allyTimer
Definition at line 22 of file ZoneEventDefenseGame.cs.
Referenced by _OnTickRound(), and Horn_Ally().
bonus
int ZoneEventDefenseGame.bonus
Definition at line 25 of file ZoneEventDefenseGame.cs.
Referenced by _OnTickRound(), Horn_Next(), and OnVisit().
hornTimer
int ZoneEventDefenseGame.hornTimer
Definition at line 13 of file ZoneEventDefenseGame.cs.
Referenced by _OnTickRound(), and Horn_Next().
kills
int ZoneEventDefenseGame.kills
Definition at line 16 of file ZoneEventDefenseGame.cs.
Referenced by OnCharaDie().
retreated
bool ZoneEventDefenseGame.retreated
Definition at line 28 of file ZoneEventDefenseGame.cs.
Referenced by Horn_Retreat(), and TraitCoreDefense.TrySetAct().
turns
int ZoneEventDefenseGame.turns
Definition at line 10 of file ZoneEventDefenseGame.cs.
Referenced by _OnTickRound(), Horn_Next(), and NextWave().
wave
int ZoneEventDefenseGame.wave
Definition at line 7 of file ZoneEventDefenseGame.cs.
Referenced by _OnTickRound(), NextWave(), OnVisit(), and TraitCoreDefense.TrySetAct().
Property Documentation
CanCallAlly
bool ZoneEventDefenseGame.CanCallAlly get
Definition at line 44 of file ZoneEventDefenseGame.cs.
    {
        get
        {
            if (allyCall == 0)
            {
                return rounds >= 50;
            }
            return false;
        }
    }
Referenced by TraitCoreDefense.TrySetAct().
CanRetreat
bool ZoneEventDefenseGame.CanRetreat get
Definition at line 32 of file ZoneEventDefenseGame.cs.
    {
        get
        {
            if (rounds >= 100)
            {
                return hornTimer <= 0;
            }
            return false;
        }
    }
Referenced by TraitCoreDefense.TrySetAct().
instance
ZoneInstanceRandomQuest ZoneEventDefenseGame.instance get
Definition at line 30 of file ZoneEventDefenseGame.cs.
TextWidgetDate
override string ZoneEventDefenseGame.TextWidgetDate get
Definition at line 56 of file ZoneEventDefenseGame.cs.
The documentation for this class was generated from the following file:
Elin/ZoneEventDefenseGame.cs