Elin Decompiled Documentation: RegionPoint Class Reference
RegionPoint Class Reference
Public Member Functions
RegionPoint (Point p)
void SetRegionPoint (int _x, int _z)
Public Member Functions inherited from Point
bool Within (int _x, int _z, int _w, int _h)
Chara FirstVisibleChara ()
bool HasRoomOrArea (BaseArea a)
bool IsInSpot< T > ()
bool IsPublicSpace ()
Point ()
Point (Point p)
Point (int _x, int _z)
Point (int _index)
Point Copy ()
T Copy< T > ()
Point Set (int _x, int _z)
Point Set (int index)
Point Set (Point point)
override string ToString ()
void Set (Vector3 v)
ref Vector3 PositionAuto ()
ref Vector3 Position (int height)
ref Vector3 Position ()
ref Vector3 PositionTopdown ()
ref Vector3 PositionTopdownTreasure ()
ref Vector3 PositionCenter ()
Quaternion GetRotation (Point to)
float GetAngle (Point to)
float GetAngle2 (Point to)
Point GetNearestPoint (bool allowBlock=false, bool allowChara=true, bool allowInstalled=true, bool ignoreCenter=false, int minRadius=0)
bool ForeachNearestPoint (Func< Point, bool > endFunc, bool allowBlock=false, bool allowChara=true, bool allowInstalled=true, bool ignoreCenter=false, int maxRange=30)
Point GetRandomNeighbor ()
Point GetRandomPoint (int radius, bool requireLos=true, bool allowChara=true, bool allowBlocked=false, int tries=100)
Point GetRandomPointInRadius (int minRadius, int maxRadius, bool requireLos=true, bool allowChara=true, bool allowBlocked=false, int tries=2000)
Point GetPointTowards (Point dest)
void TalkWitnesses (Chara criminal, string idTalk, int radius=4, WitnessType type=WitnessType.everyone, Func< Chara, bool > talkIf=null, int chance=3)
List< Chara > ListWitnesses (Chara criminal, int radius=4, WitnessType type=WitnessType.crime, Chara target=null)
bool TryWitnessCrime (Chara criminal, Chara target=null, int radius=4, Func< Chara, bool > funcWitness=null)
void CallGuard (Chara criminal, Chara caller)
void SetBlock (int idMat=0, int idBlock=0)
void SetFloor (int idMat=0, int idFloor=0)
void SetObj (int id=0, int value=1, int dir=0)
void ModFire (int value, bool extinguish=false)
void Plow ()
bool Equals (int _x, int _z)
override bool Equals (object obj)
override int GetHashCode ()
int Distance (Point p)
int Distance (int tx, int tz)
bool IsBlockByHeight (Point p)
Point Clamp (bool useBounds=false)
List< Card > ListCards (bool includeMasked=false)
List< Card > ListVisibleCards ()
Card FindAttackTarget ()
Chara FindChara (Func< Chara, bool > func)
T FindThing< T > ()
Thing FindThing (Func< Thing, bool > func)
List< Card > ListThings< T > (bool onlyInstalled=true)
List< Chara > ListCharas ()
List< Chara > ListVisibleCharas ()
List< Chara > ListCharasInNeighbor (Func< Chara, bool > func)
List< Chara > ListCharasInRadius (Chara cc, int dist, Func< Chara, bool > func, bool onlyVisible=true)
T GetInstalled< T > ()
Effect PlayEffect (string id)
SoundSource PlaySound (string id, bool synced=true, float v=1f, bool spatial=true)
void RefreshNeighborTiles ()
void RefreshTile ()
bool HasNonHomeProperty (Thing exclude=null)
void Animate (AnimeID id, bool animeBlock=false)
RenderParam ApplyAnime (RenderParam p)
Vector3 ApplyAnime (ref Vector3 p)
List< IInspect > ListInspectorTargets ()
void ForeachMultiSize (int w, int h, Action< Point, bool > action)
void ForeachNeighbor (Action< Point > action, bool diagonal=true)
Point ToRegionPos ()
void SetHighlight (int id)
Public Attributes
int dangerLv
EloMap.TileInfo tile
BiomeProfile biome
Public Attributes inherited from Point
int x
int z
Additional Inherited Members
Static Public Member Functions inherited from Point
static Point GetShared (int x, int z)
Static Public Member Functions inherited from EClass
static int rndSeed (int a, int seed)
static int rnd (long a)
static int rnd (int a)
static int curve (int a, int start, int step, int rate=75)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Static Public Attributes inherited from Point
static readonly XY[] Surrounds
static Vector3 fixedPos
static Point shared = new Point()
static Point shared2 = new Point()
static Point shared3 = new Point()
static Map map
static Point Invalid
static Point Zero = new Point()
static BaseGameScreen _screen
Static Public Attributes inherited from EClass
static Core core
Properties inherited from Point
int index [get]
Cell cell [get]
SourceMaterial.Row matRoofBlock [get]
SourceMaterial.Row matBlock [get]
SourceMaterial.Row matFloor [get]
SourceMaterial.Row matBridge [get]
SourceBlock.Row sourceRoofBlock [get]
SourceBlock.Row sourceBlock [get]
SourceFloor.Row sourceFloor [get]
SourceFloor.Row sourceBridge [get]
SourceObj.Row sourceObj [get]
CellDetail detail [get]
Area area [get]
Point Front [get]
GrowSystem growth [get]
int eloX [get]
int eloY [get]
bool HasDesignation [get]
bool HasDirt [get]
bool IsValid [get, set]
bool IsInBounds [get]
bool IsInBoundsPlus [get]
bool IsFarmField [get]
bool IsWater [get]
bool HasRamp [get]
bool HasRail [get]
bool HasRampOrLadder [get]
bool HasObj [get]
bool HasDecal [get]
bool HasBlock [get]
bool HasMinableBlock [get]
bool HasWallOrFence [get]
bool HasWall [get]
bool HasFence [get]
bool HasNonWallBlock [get]
bool HasTaskBuild [get]
bool HasBlockRecipe [get]
bool HasFloor [get]
bool HasBridge [get]
bool IsSky [get]
bool HasArea [get]
bool HasChara [get]
bool HasThing [get]
bool HasMultipleChara [get]
bool IsDeepWater [get]
Chara FirstChara [get]
Thing FirstThing [get]
Thing LastThing [get]
Thing Installed [get]
List< Thing > Things [get]
List< Chara > Charas [get]
bool IsSeen [get]
bool IsSync [get]
bool IsHidden [get]
bool IsBlocked [get]
bool IsHotSpring [get]
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Detailed Description
Definition at line 3 of file RegionPoint.cs.
Constructor & Destructor Documentation
RegionPoint()
RegionPoint.RegionPoint (Point p) inline
Definition at line 11 of file RegionPoint.cs.
    {
        SetRegionPoint(p.x, p.z);
    }
References SetRegionPoint(), Point.x, and Point.z.
Member Function Documentation
SetRegionPoint()
void RegionPoint.SetRegionPoint (int _x, int _z) inline
Definition at line 16 of file RegionPoint.cs.
    {
        Set(_x + EClass.scene.elomap.minX, _z + EClass.scene.elomap.minY);
        EClass._zone.Region.GetZoneAt(x, z);
        int roadDist = EClass.scene.elomap.GetRoadDist(x, z);
        int num = ((EClass.pc.homeBranch != null) ? EClass.pc.pos.Distance(EClass.game.StartZone.mapX, EClass.game.StartZone.mapY) : 0);
        tile = EClass.scene.elomapActor.elomap.GetTileInfo(x, z);
        string key = tile.source.idBiome.IsEmpty("Plain");
        biome = EClass.core.refs.biomes.dict[key];
        int num2 = Mathf.Clamp(roadDist - 4, 0, 200) + Mathf.Clamp(num / 4, 0, 10);
        if (roadDist > 20)
        {
            num2 += roadDist - 20;
        }
        if (num2 >= 100)
        {
            num2 = 100;
        }
        Mathf.Min(num2 / 10, 4);
        EClass.rnd(3 + Mathf.Min(num2 / 10, 4));
        _ = 5;
        dangerLv = num2 + 5;
    }
References EClass._zone, biome, CoreRef.biomes, EClass.core, dangerLv, CoreRef.Biomes.dict, Point.Distance(), EloMapActor.elomap, Scene.elomap, Scene.elomapActor, EClass.game, EloMap.GetRoadDist(), EloMap.GetTileInfo(), Zone.GetZoneAt(), Spatial.mapX, Spatial.mapY, EloMap.minX, EloMap.minY, EClass.pc, Card.pos, Core.refs, Zone.Region, EClass.rnd(), EClass.scene, Point.Set(), Game.StartZone, tile, Point.x, and Point.z.
Referenced by RegionPoint().
Member Data Documentation
biome
BiomeProfile RegionPoint.biome
Definition at line 9 of file RegionPoint.cs.
Referenced by Region.OnAdvanceHour(), and SetRegionPoint().
dangerLv
int RegionPoint.dangerLv
Definition at line 5 of file RegionPoint.cs.
Referenced by SetRegionPoint().
tile
EloMap.TileInfo RegionPoint.tile
Definition at line 7 of file RegionPoint.cs.
Referenced by SetRegionPoint().
The documentation for this class was generated from the following file:
Elin/RegionPoint.cs