Elin Decompiled Documentation: SerializedCards Class Reference
SerializedCards Class Reference
Classes
class Data
Public Member Functions
void Add (Card c)
void Restore (Map map, Map orgMap, bool addToZone, PartialMap partial=null)
Public Attributes
List< Data > cards = new List<Data>()
int version = 2
List< Card > importedCards = new List<Card>()
Additional Inherited Members
Static Public Member Functions inherited from EClass
static int rndSeed (int a, int seed)
static int rnd (long a)
static int rnd (int a)
static int curve (int a, int start, int step, int rate=75)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Static Public Attributes inherited from EClass
static Core core
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Detailed Description
Definition at line 6 of file SerializedCards.cs.
Member Function Documentation
Add()
void SerializedCards.Add (Card c) inline
Definition at line 465 of file SerializedCards.cs.
    {
        Data data = new Data
        {
            id = c.id,
            idEditor = c.c_idEditor,
            idRefCard = c.c_idRefCard,
            idTrait = c.c_idTrait,
            tags = c.c_editorTags,
            traitVals = c.c_editorTraitVal,
            obj = c.mapObj,
            idMat = c.material.id,
            x = c.pos.x,
            z = c.pos.z,
            placeState = (int)c.placeState,
            dir = c.dir,
            altitude = c.altitude,
            fx = (int)(c.fx * 1000f),
            fy = (int)(c.fy * 1000f),
            lightColor = c.c_lightColor,
            bits1 = c._bits1.ToInt(),
            bits2 = c._bits2.ToInt(),
            tile = c.sourceCard.tiles[0],
            idRender = c.sourceCard.idRenderData,
            refVal = c.refVal,
            idSkin = c.idSkin,
            idDeity = c.c_idDeity,
            isEmpty = (c.things.Count == 0 && c.c_lockLv == 0),
            encLv = c.encLV,
            cText = c.c_refText,
            cNote = c.c_note,
            idtState = c.c_IDTState,
            idRefName = c.c_idRefName,
            idTeleport = c.GetStr(31)
        };
        if (c.c_idBacker != 0)
        {
            SourceBacker.Row row = EClass.sources.backers.map.TryGetValue(c.c_idBacker);
            if (row != null && row.isStatic != 0)
            {
                data.idBacker = c.c_idBacker;
            }
        }
        if (c.material.id == c.DefaultMaterial.id)
        {
            data.idMat = -1;
        }
        data.idDyeMat = (c.isDyed ? c.c_dyeMat : (-1));
        if (c.isChara)
        {
            Point orgPos = c.Chara.orgPos;
            if (orgPos != null)
            {
                data.x = orgPos.x;
                data.z = orgPos.z;
            }
            if (c.Chara.isDead)
            {
                data.isDead = true;
            }
            if (c.Chara.uidEditor == 0)
            {
                int num = 1;
                foreach (Chara item in EClass._map.charas.Concat(EClass._map.deadCharas))
                {
                    if (item.uidEditor >= num)
                    {
                        num = item.uidEditor + 1;
                    }
                }
                c.Chara.uidEditor = num;
            }
            data.lv = c.LV;
            data.element = c.c_idMainElement;
            data.uidEditor = c.Chara.uidEditor;
        }
        TryAddStr(52);
        cards.Add(data);
        data.ints[0] = data._bits1.ToInt();
        void TryAddStr(int key)
        {
            string str = c.GetStr(key);
            if (!str.IsEmpty())
            {
                if (data.cstr == null)
                {
                    data.cstr = new Dictionary<int, string>();
                }
                data.cstr[key] = str;
            }
        }
    }
References Card._bits1, SerializedCards.Data._bits1, Card._bits2, EClass._map, Card.altitude, SourceManager.backers, Card.c_editorTags, Card.c_editorTraitVal, Card.c_idBacker, Card.c_idDeity, Card.c_idEditor, Card.c_idMainElement, Card.c_idRefCard, Card.c_idRefName, Card.c_idTrait, Card.c_IDTState, Card.c_lightColor, Card.c_note, Card.c_refText, cards, Card.Chara, Map.charas, SerializedCards.Data.cstr, Map.deadCharas, Card.DefaultMaterial, Card.dir, Card.encLV, BaseCard.GetStr(), Card.id, CardRow.idRenderData, Card.idSkin, SerializedCards.Data.ints, Card.isChara, Chara.isDead, SourceBacker.Row.isStatic, item, Card.LV, BaseCard.mapObj, Card.material, Chara.orgPos, Card.placeState, Card.pos, Card.refVal, Card.sourceCard, EClass.sources, RenderRow.tiles, BitArray32.ToInt(), Chara.uidEditor, Point.x, and Point.z.
Referenced by MapSubset.OnSave().
Restore()
void SerializedCards.Restore (Map map, Map orgMap, bool addToZone, PartialMap partial = null) inline
Definition at line 558 of file SerializedCards.cs.
    {
        List<Thing> things = map.things;
        List<Chara> serializedCharas = map.serializedCharas;
        bool isUserZone = EClass._zone.IsUserZone;
        Dictionary<int, int> dictionary = new Dictionary<int, int>();
        Dictionary<int, int> dictionary2 = new Dictionary<int, int>();
        importedCards.Clear();
        foreach (Data card4 in cards)
        {
            int num = card4.dir;
            Point point = new Point(card4.x, card4.z);
            int index = point.index;
            if (partial != null)
            {
                if (partial.result.ruined.Contains(point.index))
                {
                    continue;
                }
                num -= partial.dir;
                int num2 = point.x - partial.offsetX;
                int num3 = point.z - partial.offsetZ;
                switch (partial.dir)
                {
                case 1:
                {
                    int num5 = num2;
                    num2 = num3;
                    num3 = -num5;
                    break;
                }
                case 2:
                    num2 = -num2;
                    num3 = -num3;
                    break;
                case 3:
                {
                    int num4 = num2;
                    num2 = -num3;
                    num3 = num4;
                    break;
                }
                }
                point.x = num2 + partial.destX;
                point.z = num3 + partial.destZ;
                if (!partial.validPoints.Contains(point.index) || !point.IsValid)
                {
                    continue;
                }
                if (!partial.editMode)
                {
                    Card card = null;
                    string id = card4.id;
                    if (!(id == "sign_spawnThing"))
                    {
                        if (id == "sign_spawnChara")
{
                            card = CharaGen.CreateFromFilter(card4.idRefCard.IsEmpty(EClass._zone.biome.spawn.GetRandomCharaId()), EClass._zone.DangerLv);
                        }
                    }
                    else
                    {
                        card = ThingGen.CreateFromFilter(card4.idRefCard.IsEmpty(EClass._zone.biome.spawn.GetRandomThingId()), EClass._zone.DangerLv);
                    }
                    if (card != null)
                    {
                        card.pos = point;
                        EClass._zone.AddCard(card, card.pos);
                        if (card.trait.IsDoor)
{
                            EClass._map.OnSetBlockOrDoor(card.pos.x, card.pos.z);
                        }
                        continue;
                    }
                }
            }
            card4._bits1.SetInt(card4.ints[0]);
            string text = card4.id;
            if (card4.idV != 0)
            {
                text = card4.idV.ToString() ?? "";
            }
            if (addToZone && partial != null && !partial.editMode)
            {
                string id = card4.id;
                if (!(id == "editor_torch"))
                {
                    if (id == "editor_torch_wall")
                    {
                        text = EClass._zone.biome.style.GetIdLight(wall: true);
                    }
                }
                else
                {
                    text = EClass._zone.biome.style.GetIdLight(wall: false);
                }
            }
            CardRow source = EClass.sources.cards.map.TryGetValue(text);
            if (source == null)
            {
                continue;
            }
            Card card2 = null;
            if (source.isChara)
            {
                if (orgMap != null)
                {
                    bool flag = false;
                    if (source.quality >= 4)
                    {
                        foreach (Chara value2 in EClass.game.cards.globalCharas.Values)
{
                            if (value2.id == text)
{
                                flag = true;
                                break;
                            }
                        }
                    }
                    if (!flag)
                    {
                        foreach (Chara item in orgMap.charas.Concat(orgMap.serializedCharas).Concat(orgMap.deadCharas))
{
                            if (source.quality >= 4 && item.id == text)
{
                                flag = true;
                                break;
                            }
                            if (item.id == text && item.orgPos != null && item.orgPos.Equals(point))
{
                                flag = true;
                                break;
                            }
                        }
                    }
                    if (flag)
                    {
                        continue;
                    }
                }
                if (isUserZone && ClassExtension.TryGetValue<int, int>((IDictionary<int, int>)dictionary, index, 0) >= 3)
                {
                    continue;
                }
                card2 = CharaGen.Create(text);
                if (card4.ints.Length > 20)
                {
                    if (isUserZone)
                    {
                        card2.Chara.SetLv(card4.lv);
                    }
                    if (card4.element != 0)
                    {
                        card2.Chara.SetMainElement(card4.element);
                    }
                }
                card2.Chara.orgPos = point.Copy();
                if (card4.isDead)
                {
                    card2.hp = -1;
                    card2.Chara.isDead = true;
                }
                card2.Chara.hunger.value = EClass.rnd(EClass.rnd(20) + 1);
                if (!addToZone)
                {
                    serializedCharas.Add(card2.Chara);
                }
                if (isUserZone)
                {
                    dictionary[index] = ClassExtension.TryGetValue<int, int>((IDictionary<int, int>)dictionary, index, 0) + 1;
                }
            }
            else
            {
                PlaceState placeState = card4.placeState.ToEnum<PlaceState>();
                if (isUserZone && ((ClassExtension.TryGetValue<int, int>((IDictionary<int, int>)dictionary2, index, 0) >= 20 && text != "waystone" && text != "core_zone") || (placeState != PlaceState.installed && !card4.bits1.IsOn(13)) || text == "medal"))
                {
                    continue;
                }
                if (source.isOrigin)
                {
                    text = SpawnListThing.Get("origin_" + text, (SourceThing.Row a) => a.origin == source).GetFirst().id;
                }
                card2 = ThingGen.Create(text, -1, EClass._zone.DangerLv);
                card2.ChangeMaterial((card4.idMat == -1) ? card2.DefaultMaterial.id : card4.idMat);
                if (!addToZone)
                {
                    things.Add(card2.Thing);
                }
                card2.altitude = card4.altitude;
                card2.placeState = placeState;
                card2.c_lightColor = card4.lightColor;
                if (isUserZone)
                {
                    dictionary2[index] = ClassExtension.TryGetValue<int, int>((IDictionary<int, int>)dictionary2, index, 0) + 1;
                }
            }
            if (num < 0)
            {
                num = Mathf.Abs(card2.sourceCard.tiles.Length + num);
            }
            card2.pos = point;
            card2.dir = num;
            card2._bits1.SetInt(card4.bits1);
            card2._bits2.SetInt(card4.bits2);
            card2.isPlayerCreation = true;
            card2.autoRefuel = true;
            card2.c_editorTraitVal = card4.traitVals;
            card2.c_idRefCard = card4.idRefCard;
            card2.isImported = true;
            card2.refVal = card4.refVal;
            card2.idSkin = card4.idSkin;
            card2.c_idDeity = card4.idDeity;
            card2.c_refText = card4.cText;
            card2.c_note = card4.cNote;
            if (card4.idBacker != 0)
            {
                Debug.Log(card4.idBacker);
                card2.c_idBacker = card4.idBacker;
            }
            if (version >= 2 && card4.idDyeMat != -1)
            {
                card2.Dye(EClass.sources.materials.rows.TryGet(card4.idDyeMat, 1));
            }
            card2.mapObj = card4.obj;
            if (card2.mapObj?.TryGetValue(2) != null)
            {
                card2.mapObj.Remove(2);
            }
            if (card4.cstr != null)
            {
                foreach (KeyValuePair<int, string> item2 in card4.cstr)
                {
                    card2.SetStr(item2.Key, item2.Value);
                }
            }
            if (card2.freePos)
            {
                card2.fx = (float)card4.fx * 0.001f;
                card2.fy = (float)card4.fy * 0.001f;
            }
            if (!card4.idEditor.IsEmpty())
            {
                card2.c_idEditor = card4.idEditor;
            }
            if (!card4.idTrait.IsEmpty())
            {
                card2.c_idTrait = card4.idTrait;
                card2.ApplyTrait();
                card2.trait.OnCreate(EClass._zone.lv);
            }
            if (!card4.tags.IsEmpty())
            {
                card2.c_editorTags = card4.tags;
                try
                {
                    string[] array = card4.tags.Split(',');
                    foreach (string value in array)
                    {
                        card2.ApplyEditorTags(value.ToEnum<EditorTag>());
                    }
                }
                catch
                {
                    Debug.LogWarning("Could not convert editor tag:" + card2.Name + "/" + card4.tags);
                }
            }
            if (isUserZone)
            {
                if ((card2.isHidden || card2.isMasked) && ((card2.TileType.IsBlockPass && card2.IsInstalled) || card2.trait is TraitCoreZone || card2.trait is TraitWaystone))
                {
                    Card card3 = card2;
                    bool isHidden = (card2.isMasked = false);
                    card3.isHidden = isHidden;
                }
                if (card2.IsContainer)
                {
                    if (card4.isEmpty)
                    {
                        card2.things.DestroyAll();
                        card2.c_lockLv = 0;
                    }
                    else
                    {
                        card2.c_lockLv = 1;
                    }
                }
                if (card4.ints.Length > 20 && card4.encLv != 0)
                {
                    card2.SetEncLv(card4.encLv);
                }
                if (card4.strs.Length > 10)
                {
                    if (!card4.idRefName.IsEmpty())
                    {
                        card2.c_idRefName = card4.idRefName;
                    }
                    if (!card4.idTeleport.IsEmpty())
                    {
                        card2.SetStr(31, card4.idTeleport);
                    }
                }
                card2.c_IDTState = card4.idtState;
            }
            if (card2.isChara)
            {
                card2.Chara.homeZone = EClass._zone;
                card2.Chara.uidEditor = card4.uidEditor;
                if (card2.isBackerContent)
                {
                    card2.ApplyBacker(card2.c_idBacker);
                }
                card2.SetObj(5, null);
                if (EClass._zone.ShouldScaleImportedChara(card2.Chara))
                {
                    card2.Chara.ScaleByPrincipal();
                }
            }
            if (card2.trait is TraitFakeBlock)
            {
                card2._CreateRenderer();
            }
            if (addToZone)
            {
                EClass._zone.AddCard(card2, card2.pos);
                if (card2.trait.IsDoor)
                {
                    EClass._map.OnSetBlockOrDoor(card2.pos.x, card2.pos.z);
                }
                if (partial != null && !card2.sourceCard.lightData.IsEmpty())
                {
                    partial.result.hasLight = true;
                }
            }
            importedCards.Add(card2);
        }
        foreach (Card importedCard in importedCards)
        {
            if (importedCard.trait is TraitShackle)
            {
                foreach (Card importedCard2 in importedCards)
                {
                    if (importedCard2.isRestrained && importedCard2.pos.Equals(importedCard.pos))
                    {
                        importedCard.c_uidRefCard = importedCard2.uid;
                    }
                }
            }
            importedCard.trait.OnImportMap();
        }
    }
References Card._bits1, SerializedCards.Data._bits1, Card._bits2, Card._CreateRenderer(), EClass._map, EClass._zone, Card.Add(), Zone.AddCard(), SerializedCards.Data.altitude, Card.ApplyBacker(), Card.ApplyEditorTags(), Card.ApplyTrait(), Zone.biome, SerializedCards.Data.bits1, SerializedCards.Data.bits2, Card.c_idBacker, card, Game.cards, cards, SourceManager.cards, Card.ChangeMaterial(), Card.Chara, SerializedCards.Data.cNote, Point.Copy(), ThingGen.Create(), CharaGen.Create(), ThingGen.CreateFromFilter(), CharaGen.CreateFromFilter(), SerializedCards.Data.cstr, SerializedCards.Data.cText, Zone.DangerLv, Debug, ThingContainer.DestroyAll(), SerializedCards.Data.dir, Card.Dye(), SerializedCards.Data.element, SerializedCards.Data.encLv, Point.Equals(), Card.freePos, SerializedCards.Data.fx, Card.fy, EClass.game, SpawnListThing.Get(), BiomeProfile.Style.GetIdLight(), BiomeProfile.Spawns.GetRandomCharaId(), BiomeProfile.Spawns.GetRandomThingId(), CardManager.globalCharas, Card.id, SerializedCards.Data.id, SpawnList.id, SerializedCards.Data.idBacker, SerializedCards.Data.idDeity, SerializedCards.Data.idDyeMat, SerializedCards.Data.idEditor, SerializedCards.Data.idMat, SerializedCards.Data.idRefCard, SerializedCards.Data.idRefName, SerializedCards.Data.idSkin, SerializedCards.Data.idTeleport, SerializedCards.Data.idTrait, SerializedCards.Data.idtState, SerializedCards.Data.idV, importedCards, Point.index, SerializedCards.Data.ints, Card.isBackerContent, Card.isChara, CardRow.isChara, Card.IsContainer, SerializedCards.Data.isDead, Trait.IsDoor, SerializedCards.Data.isEmpty, Card.isHidden, Card.IsInstalled, Card.isMasked, CardRow.isOrigin, Card.isRestrained, Zone.IsUserZone, Point.IsValid, item, SerializedCards.Data.lightColor, CardRow.lightData, SerializedCards.Data.lv, Spatial.lv, SourceCard.map, BaseCard.mapObj, SourceManager.materials, Card.Name, SerializedCards.Data.obj, Trait.OnCreate(), Trait.OnImportMap(), Map.OnSetBlockOrDoor(), SerializedCards.Data.placeState, Card.pos, CardRow.quality, SerializedCards.Data.refVal, EClass.rnd(), Chara.ScaleByPrincipal(), Map.serializedCharas, Card.SetEncLv(), BitArray32.SetInt(), Card.SetLv(), Chara.SetMainElement(), BaseCard.SetObj(), BaseCard.SetStr(), Zone.ShouldScaleImportedChara(), Card.sourceCard, EClass.sources, BiomeProfile.spawn, SerializedCards.Data.strs, BiomeProfile.style, SerializedCards.Data.tags, Card.Thing, Card.things, Map.things, RenderRow.tiles, Card.trait, SerializedCards.Data.traitVals, Card.uid, SerializedCards.Data.uidEditor, version, Point.x, SerializedCards.Data.x, Point.z, and SerializedCards.Data.z.
Referenced by MapSubset.Apply(), PartialMap.Apply(), and Map.OnImport().
Member Data Documentation
cards
List<Data> SerializedCards.cards = new List<Data>()
Definition at line 458 of file SerializedCards.cs.
Referenced by Add(), PartialMap.Apply(), MapSubset.OnSave(), and Restore().
importedCards
List<Card> SerializedCards.importedCards = new List<Card>()
Definition at line 463 of file SerializedCards.cs.
Referenced by Restore().
version
int SerializedCards.version = 2
Definition at line 461 of file SerializedCards.cs.
Referenced by Restore().
The documentation for this class was generated from the following file:
Elin/SerializedCards.cs