Elin Decompiled Documentation: ContentFaction Class Reference
ContentFaction Class Reference
Public Member Functions
override void OnSwitchContent (int idTab)
void RefreshFactions (bool religion)
void RefreshZones ()
Public Member Functions inherited from UIContent
virtual void OnSwitchContent (int idTab)
virtual void OnInstantiate ()
Public Member Functions inherited from UINote
void Clear ()
void Build ()
void Space (int sizeY=0, int sizeX=1)
UINote AddNote (string id)
UIItem AddHeader (string text, Sprite sprite=null)
UIItem AddHeaderCard (string text, Sprite sprite=null)
UIItem AddHeaderTopic (string text, Sprite sprite=null)
UIItem AddHeader (string id, string text, Sprite sprite=null)
UIItem AddText (string text, FontColor color=FontColor.DontChange)
UIItem AddText (string id, string text, FontColor color=FontColor.DontChange)
UIItem AddText (string id, string text, Color color)
UIItem AddItem (string id)
UIItem AddTopic (string id, string text, string value=null)
UIItem AddTopic (string text, string value=null)
void AddImage (Sprite sprite)
void AddImage (string idFile)
UIButton AddButton (string text, Action onClick)
UIButton AddButtonLink (string text, string url)
UIDropdown AddDropdown (string id="DropdownDefault")
UIButton AddToggle (string idLang="", bool isOn=false, Action< bool > action=null)
Transform AddPrefab (string path)
T AddExtra< T > (string path)
Public Attributes
UIList listFaction
UIFactionInfo info
Sprite spriteFaction
Sprite spriteFaith
UIText textHeader
Public Attributes inherited from UINote
RectTransform target
UINoteProfile prof
SkinType skinType
string idDefaultText
LayoutGroup layout
RectTransform cur
bool extraRebuild
Detailed Description
Definition at line 3 of file ContentFaction.cs.
Member Function Documentation
OnSwitchContent()
override void ContentFaction.OnSwitchContent (int idTab) inline virtual
Reimplemented from UIContent.
Definition at line 15 of file ContentFaction.cs.
    {
        if (idTab == 2)
        {
            RefreshZones();
        }
        else
        {
            RefreshFactions(idTab == 4);
        }
        LayerJournal componentInParent = GetComponentInParent<LayerJournal>();
        textHeader.SetText(componentInParent.GetTextHeader(componentInParent.windows[0]));
    }
References Layer.GetTextHeader(), RefreshFactions(), RefreshZones(), UIText.SetText(), textHeader, and Layer.windows.
RefreshFactions()
void ContentFaction.RefreshFactions (bool religion) inline
Definition at line 29 of file ContentFaction.cs.
    {
        UIList uIList = listFaction;
        uIList.Clear();
        if (religion)
        {
            uIList.callbacks = new UIList.Callback<Religion, ItemGeneral>
            {
                onClick = delegate(Religion a, ItemGeneral b)
                {
                    info.SetReligion(a);
                },
                onInstantiate = delegate(Religion a, ItemGeneral b)
                {
                    b.SetSound();
                    b.SetMainText(a.Name, spriteFaith);
                    b.SetSubText(a.TextType, 260, FontColor.Default, TextAnchor.MiddleRight);
                    a.SetTextRelation(b.button1.subText);
                    b.Build();
                    b.button1.refStr = a.id;
                }
            };
            foreach (Religion value in EClass.game.religions.dictAll.Values)
            {
                if (!value.IsMinorGod)
                {
                    uIList.Add(value);
                }
            }
        }
        else
        {
            uIList.callbacks = new UIList.Callback<Faction, ItemGeneral>
            {
                onClick = delegate(Faction a, ItemGeneral b)
                {
                    info.SetFaction(a);
                },
                onInstantiate = delegate(Faction a, ItemGeneral b)
                {
                    b.SetSound();
                    b.SetMainText(a.name, spriteFaction);
                    b.SetSubText(a.TextType, 260, FontColor.Default, TextAnchor.MiddleRight);
                    a.relation.SetTextHostility(b.button1.subText);
                    b.Build();
                    b.button1.refStr = a.id;
                }
            };
            foreach (Faction value2 in EClass.game.factions.dictAll.Values)
            {
                uIList.Add(value2);
            }
        }
        uIList.Refresh();
    }
References UIList.Add(), ItemGeneral.Build(), UIItem.button1, UIList.Clear(), FactionManager.dictAll, ReligionManager.dictAll, Game.factions, EClass.game, Faction.id, Religion.id, info, Religion.IsMinorGod, listFaction, Faction.name, Religion.Name, UIList.Refresh(), Faction.relation, religion, Game.religions, UIFactionInfo.SetFaction(), ItemGeneral.SetMainText(), UIFactionInfo.SetReligion(), ItemGeneral.SetSound(), ItemGeneral.SetSubText(), FactionRelation.SetTextHostility(), Religion.SetTextRelation(), spriteFaction, spriteFaith, UIButton.subText, Faction.TextType, and Religion.TextType.
Referenced by OnSwitchContent().
RefreshZones()
void ContentFaction.RefreshZones () inline
Definition at line 85 of file ContentFaction.cs.
    {
        UIList uIList = listFaction;
        uIList.Clear();
        uIList.callbacks = new UIList.Callback<Spatial, ItemGeneral>
        {
            onClick = delegate(Spatial a, ItemGeneral b)
            {
                if (a is Zone)
                {
                    info.SetZone(a as Zone);
                }
            },
            onInstantiate = delegate(Spatial a, ItemGeneral b)
            {
                b.SetSound();
                b.SetMainText(a.Name);
                b.Build();
            }
        };
        foreach (Spatial value in EClass.game.spatials.map.Values)
        {
            if (value is Zone && value.parent == EClass.pc.currentZone.Region && value.mainFaction == EClass.pc.faction)
            {
                uIList.Add(value);
            }
        }
        uIList.Refresh();
        if (uIList.items.Count == 0)
        {
            info.Clear();
        }
    }
References ItemGeneral.Build(), UIList.Clear(), UIFactionInfo.Clear(), Chara.currentZone, Chara.faction, EClass.game, info, listFaction, Spatial.mainFaction, SpatialManager.map, Spatial.Name, Spatial.parent, EClass.pc, Zone.Region, ItemGeneral.SetMainText(), ItemGeneral.SetSound(), UIFactionInfo.SetZone(), and Game.spatials.
Referenced by OnSwitchContent().
Member Data Documentation
info
UIFactionInfo ContentFaction.info
Definition at line 7 of file ContentFaction.cs.
Referenced by RefreshFactions(), and RefreshZones().
listFaction
UIList ContentFaction.listFaction
Definition at line 5 of file ContentFaction.cs.
Referenced by RefreshFactions(), and RefreshZones().
spriteFaction
Sprite ContentFaction.spriteFaction
Definition at line 9 of file ContentFaction.cs.
Referenced by RefreshFactions().
spriteFaith
Sprite ContentFaction.spriteFaith
Definition at line 11 of file ContentFaction.cs.
Referenced by RefreshFactions().
textHeader
UIText ContentFaction.textHeader
Definition at line 13 of file ContentFaction.cs.
Referenced by OnSwitchContent().
The documentation for this class was generated from the following file:
Elin/ContentFaction.cs