Elin Decompiled Documentation: GameUpdater.SurfaceUpdater Class Reference
GameUpdater.SurfaceUpdater Class Reference
Public Member Functions
override void FixedUpdate ()
Public Member Functions inherited from GameUpdater.Updater
virtual void FixedUpdate ()
void SetUpdatesPerFrame (int _maxcount, float _duration)
Public Attributes
int x
int z
Public Attributes inherited from GameUpdater.Updater
int index
int updatesPerFrame
int maxCount
float duration = 1f
float _updatesPerFrame
Point pos = new Point()
Properties
int SizeXZ [get]
int Size [get]
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Additional Inherited Members
Static Public Member Functions inherited from EClass
static int rnd (int a)
static int curve (int a, int start, int step, int rate=75)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Static Public Attributes inherited from EClass
static Core core
Detailed Description
Definition at line 322 of file GameUpdater.cs.
Member Function Documentation
FixedUpdate()
override void GameUpdater.SurfaceUpdater.FixedUpdate () inline virtual
Reimplemented from GameUpdater.Updater.
Reimplemented in GameUpdater.FastSurfaceUpdater.
Definition at line 340 of file GameUpdater.cs.
        {
            if (!this.pos.Set(this.x, this.z).IsValid)
            {
                this.x = (this.z = 0);
            }
            base.SetUpdatesPerFrame(this.SizeXZ, 20f);
            PropSet propSet = EClass._map.Roaming.raceMap.TryGetValue("fish", null);
            if (propSet != null)
            {
                int num = propSet.num;
            }
            bool isRaining = EClass.world.weather.IsRaining;
            for (int i = 0; i < this.updatesPerFrame; i++)
            {
                this.pos.Set(this.x, this.z);
                SourceObj.Row sourceObj = this.pos.sourceObj;
                bool flag = this.pos.sourceBlock.id != 0;
                Cell cell = this.pos.cell;
                bool flag2 = EClass._map.IsIndoor || cell.HasRoof;
                if (cell.effect != null)
                {
                    if (cell.HasFire)
                    {
                        if (isRaining)
{
                            this.pos.ModFire(-5);
                        }
                        else if (EClass.rnd(2) == 0)
{
                            this.pos.ModFire(-2);
                        }
                    }
                    else if (cell.HasLiquid && (!isRaining || cell.IsTopWater || cell.HasRoof))
                    {
                        EClass._map.ModLiquid(this.pos.x, this.pos.z, -1);
                    }
                }
                if (isRaining)
                {
                    if (!flag2)
                    {
                        if (cell.IsFarmField)
{
                            cell.isWatered = true;
                        }
                        if (EClass.rnd(500) == 0 && !flag && !cell.blocked && !cell.HasObj && !cell.IsTopWaterAndNoSnow && !EClass._zone.IsRegion)
{
                            EClass._map.SetLiquid(this.pos.x, this.pos.z, 1, EClass.rnd(3) + 1);
                        }
                    }
                    if (EClass.rnd(50) == 0 && cell.decal != 0)
                    {
                        cell.decal = 0;
                    }
                }
                this.x++;
                if (this.x >= this.Size)
                {
                    this.x = 0;
                    this.z++;
                    if (this.z >= this.Size)
                    {
                        this.z = 0;
                    }
                }
            }
        }
References EClass._map, EClass._zone, Point.cell, Cell.effect, Cell.HasFire, Cell.HasLiquid, Cell.HasRoof, Cell.IsFarmField, Weather.IsRaining, Spatial.IsRegion, Cell.IsTopWater, Point.IsValid, Point.ModFire(), Map.ModLiquid(), PropSet.num, GameUpdater.Updater.pos, Props.raceMap, EClass.rnd(), Map.Roaming, Point.Set(), Map.SetLiquid(), GameUpdater.SurfaceUpdater.Size, GameUpdater.SurfaceUpdater.SizeXZ, Point.sourceObj, GameUpdater.Updater.updatesPerFrame, World.weather, EClass.world, GameUpdater.SurfaceUpdater.x, Point.x, and GameUpdater.SurfaceUpdater.z.
Member Data Documentation
x
int GameUpdater.SurfaceUpdater.x
Definition at line 409 of file GameUpdater.cs.
Referenced by GameUpdater.SurfaceUpdater.FixedUpdate(), and GameUpdater.FastSurfaceUpdater.FixedUpdate().
z
int GameUpdater.SurfaceUpdater.z
Definition at line 411 of file GameUpdater.cs.
Referenced by GameUpdater.SurfaceUpdater.FixedUpdate(), and GameUpdater.FastSurfaceUpdater.FixedUpdate().
Property Documentation
Size
int GameUpdater.SurfaceUpdater.Size get
Definition at line 332 of file GameUpdater.cs.
        {
            get
            {
                return EClass._map.Size;
            }
        }
Referenced by GameUpdater.SurfaceUpdater.FixedUpdate().
SizeXZ
int GameUpdater.SurfaceUpdater.SizeXZ get
Definition at line 324 of file GameUpdater.cs.
        {
            get
            {
                return EClass._map.SizeXZ;
            }
        }
Referenced by GameUpdater.SurfaceUpdater.FixedUpdate().
The documentation for this class was generated from the following file:
Elin/GameUpdater.cs