Elin Decompiled Documentation: ExcelData Class Reference
ExcelData Class Reference
Classes
class Sheet
Public Member Functions
ExcelData ()
ExcelData (string _path, int _index)
ExcelData (string _path)
void LoadBook ()
bool IsModified ()
virtual void BuildMap (string sheetName="_default")
List< Dictionary< string, string > > BuildList (string sheetName="_default")
void Override (Dictionary< string, SourceData > sources, bool canAddData=true)
string GetText (string id, string topic="text")
Public Attributes
int startIndex = 5
XSSFWorkbook book
IRow rowIndex
Dictionary< string, Sheet > sheets = new Dictionary<string, Sheet>()
string path
int maxEmptyRows
DateTime lastModified
Detailed Description
Definition at line 10 of file ExcelData.cs.
Constructor & Destructor Documentation
ExcelData() [1/3]
ExcelData.ExcelData () inline
Definition at line 33 of file ExcelData.cs.
    {
    }
ExcelData() [2/3]
ExcelData.ExcelData (string _path, int _index) inline
Definition at line 37 of file ExcelData.cs.
    {
        path = _path;
        startIndex = _index;
        BuildMap();
    }
References BuildMap(), path, and startIndex.
ExcelData() [3/3]
ExcelData.ExcelData (string _path) inline
Definition at line 44 of file ExcelData.cs.
    {
        path = _path;
    }
References path.
Member Function Documentation
BuildList()
List< Dictionary< string, string > > ExcelData.BuildList (string sheetName = "_default") inline
Definition at line 92 of file ExcelData.cs.
    {
        LoadBook();
        if (sheetName.IsEmpty())
        {
            sheetName = "_default";
        }
        Sheet sheet = sheets.TryGetValue(sheetName);
        if (sheet == null)
        {
            sheet = new Sheet();
            sheets[sheetName] = sheet;
        }
        if (sheet.list != null)
        {
            return sheet.list;
        }
        sheet.list = new List<Dictionary<string, string>>();
        ISheet sheet2 = (string.IsNullOrEmpty(sheetName) ? book.GetSheetAt(0) : (book.GetSheet(sheetName) ?? book.GetSheetAt(0)));
        rowIndex = sheet2.GetRow(0);
        int num = 0;
        for (int i = startIndex - 1; i <= sheet2.LastRowNum; i++)
        {
            IRow row = sheet2.GetRow(i);
            if (row == null)
            {
                if (i >= 5)
                {
                    num++;
                    if (num > maxEmptyRows)
                    {
                        break;
                    }
                }
                continue;
            }
            num = 0;
            Dictionary<string, string> dictionary = new Dictionary<string, string>();
            for (int j = 0; j < rowIndex.LastCellNum; j++)
            {
                ICell cell = row.GetCell(j);
                string text = rowIndex.GetCell(j).ToString();
                if (text.IsEmpty())
                {
                    break;
                }
                try
                {
                    dictionary.Add(text, (cell == null) ? "" : cell.ToString());
                }
                catch
                {
                }
            }
            sheet.list.Add(dictionary);
        }
        return sheet.list;
    }
References book, ExcelData.Sheet.list, LoadBook(), maxEmptyRows, rowIndex, sheets, and startIndex.
Referenced by BuildMap(), Zone_SnowGrave.GenerateGrave(), Player.Flags.GetStoryExcelData(), DramaEventEndRoll.Init(), DramaManager.Load(), Zone_WindRest.OnGenerateMap(), and TraitStoryBook.OnRead().
BuildMap()
virtual void ExcelData.BuildMap (string sheetName = "_default") inline virtual
Reimplemented in TextConv.
Definition at line 77 of file ExcelData.cs.
    {
        BuildList(sheetName);
        Sheet sheet = sheets[sheetName];
        if (sheet.map != null)
        {
            return;
        }
        sheet.map = new Dictionary<string, Dictionary<string, string>>();
        foreach (Dictionary<string, string> item in sheet.list)
        {
            sheet.map[item["id"]] = item;
        }
    }
References BuildList(), item, ExcelData.Sheet.map, and sheets.
Referenced by ExcelData(), Lang.GetDialog(), GetText(), and DramaCustomSequence.HasTopic().
GetText()
string ExcelData.GetText (string id, string topic = "text") inline
Definition at line 209 of file ExcelData.cs.
    {
        BuildMap();
        return sheets["_default"].map.TryGetValue(topic)?[id];
    }
References BuildMap(), and sheets.
Referenced by Religion.GetGodTalk().
IsModified()
bool ExcelData.IsModified () inline
Definition at line 72 of file ExcelData.cs.
    {
        return !lastModified.Equals(File.GetLastWriteTime(path));
    }
References lastModified, and path.
Referenced by DramaManager.Load().
LoadBook()
void ExcelData.LoadBook () inline
Definition at line 49 of file ExcelData.cs.
    {
        if (book != null)
        {
            if (lastModified.Equals(File.GetLastWriteTime(path)))
            {
                return;
            }
            Debug.Log("Excel file modified:" + path);
            sheets.Clear();
        }
        lastModified = File.GetLastWriteTime(path);
        TextAsset textAsset = Resources.Load(path) as TextAsset;
        if ((bool)textAsset)
        {
            Stream @is = new MemoryStream(textAsset.bytes);
            book = new XSSFWorkbook(@is);
            return;
        }
        using FileStream is2 = File.Open(path, FileMode.Open, FileAccess.Read, FileShare.ReadWrite);
        book = new XSSFWorkbook((Stream)is2);
    }
References book, Debug, lastModified, path, and sheets.
Referenced by BuildList(), and TextConv.BuildMap().
Override()
void ExcelData.Override (Dictionary< string, SourceData > sources, bool canAddData = true) inline
Definition at line 151 of file ExcelData.cs.
    {
        using FileStream @is = File.Open(path, FileMode.Open, FileAccess.Read, FileShare.ReadWrite);
        book = new XSSFWorkbook((Stream)@is);
        for (int i = 0; i < book.NumberOfSheets; i++)
        {
            ISheet sheetAt = book.GetSheetAt(i);
            ExcelParser.rowDefault = sheetAt.GetRow(2);
            SourceData value = null;
            if (!sources.TryGetValue(sheetAt.SheetName, out value))
            {
                Debug.Log(sheetAt.SheetName + " does not exist in sourceMap.");
                continue;
            }
            Type type = value.GetType();
            IList list = type.GetField("rows").GetValue(value) as IList;
            IDictionary dictionary = type.GetField("map").GetValue(value) as IDictionary;
            Type type2 = list.GetType().GetGenericArguments()[0];
            List<FieldInfo> list2 = new List<FieldInfo>();
            List<ExcelIndex> index = ExcelIndex.GetIndex(sheetAt);
            for (int j = 0; j < index.Count; j++)
            {
                list2.Add(type2.GetField(index[j].name));
            }
            for (int k = startIndex - 1; k <= sheetAt.LastRowNum; k++)
            {
                string stringCellValue = (ExcelParser.row = sheetAt.GetRow(k)).GetCell(0).StringCellValue;
                bool flag = true;
                object obj;
                if (dictionary.Contains(stringCellValue))
                {
                    obj = dictionary[stringCellValue];
                    flag = false;
                }
                else
                {
                    if (!canAddData)
                    {
                        continue;
                    }
                    obj = Activator.CreateInstance(type2);
                }
                for (int l = 0; l < index.Count; l++)
                {
                    string type3 = index[l].type;
                    if (type3 == "str" || type3 == "string")
                    {
                        list2[l].SetValue(obj, ExcelParser.GetString(l));
                    }
                }
                if (flag)
                {
                    list.Add(obj);
                }
            }
        }
    }
References book, Debug, ExcelIndex.GetIndex(), ExcelParser.GetString(), path, and startIndex.
Member Data Documentation
book
XSSFWorkbook ExcelData.book
Definition at line 21 of file ExcelData.cs.
Referenced by BuildList(), TextConv.BuildMap(), LoadBook(), and Override().
lastModified
DateTime ExcelData.lastModified
Definition at line 31 of file ExcelData.cs.
Referenced by IsModified(), and LoadBook().
maxEmptyRows
int ExcelData.maxEmptyRows
Definition at line 29 of file ExcelData.cs.
Referenced by BuildList().
path
string ExcelData.path
Definition at line 27 of file ExcelData.cs.
Referenced by TextConv.BuildMap(), ExcelData(), IsModified(), LoadBook(), and Override().
rowIndex
IRow ExcelData.rowIndex
Definition at line 23 of file ExcelData.cs.
Referenced by BuildList().
sheets
Dictionary<string, Sheet> ExcelData.sheets = new Dictionary<string, Sheet>()
Definition at line 25 of file ExcelData.cs.
Referenced by BuildList(), BuildMap(), Lang.GetDialog(), GetText(), DramaCustomSequence.HasTopic(), LoadBook(), and TraitStoryBook.OnRead().
startIndex
int ExcelData.startIndex = 5
Definition at line 19 of file ExcelData.cs.
Referenced by BuildList(), ExcelData(), and Override().
The documentation for this class was generated from the following file:
Elin/Plugins.basecore/ExcelData.cs