Elin Decompiled Documentation: Quest Class Reference
Quest Class Reference
Public Types
enum DifficultyType {
Default , Deliver , Supply , Escort ,
Bulk , Meal , Farm , Music
}
enum SubReward { plat , gacha_coin , money2 , ticket_furniture }
Public Member Functions
virtual Thing GetDestThing ()
virtual int GetExtraMoney ()
virtual int GetRewardPlat (int money)
override bool Equals (object obj)
virtual bool IsVisibleOnQuestBoard ()
virtual bool CanStartQuest ()
virtual bool CanUpdateOnTalk (Chara c)
virtual Zone CreateInstanceZone (Chara c)
virtual bool UpdateOnTalk ()
void Init ()
virtual void OnInit ()
Quest SetClient (Chara c, bool assignQuest=true)
void SetTask (QuestTask _task)
void Start ()
virtual void OnStart ()
virtual void OnEnterZone ()
virtual void OnClickQuest ()
void Fail ()
virtual void OnFail ()
virtual void ShowCompleteText ()
void Complete ()
virtual void OnBeforeComplete ()
virtual void OnDropReward ()
Thing DropReward (string id)
Thing DropReward (Thing t)
virtual void OnComplete ()
void CompleteTask ()
virtual void OnCompleteTask ()
virtual void OnGiveItem (Chara c, Thing t)
virtual void OnKillChara (Chara c)
virtual void OnModKarma (int a)
void NextPhase ()
void ChangePhase (int a)
virtual void OnChangePhase (int a)
string Parse (string s)
virtual string GetTitle ()
virtual string GetTrackerText ()
virtual string GetDetail (bool onJournal=false)
virtual string GetDetailText (bool onJournal=false)
virtual string GetTextProgress ()
string GetRewardText ()
virtual string GetTalkProgress ()
virtual string GetTalkComplete ()
void UpdateJournal ()
virtual bool IsDeliverTarget (Chara c)
virtual bool CanDeliverToClient (Chara c)
virtual bool CanDeliverToBox (Thing t)
virtual bool Deliver (Chara c, Thing t=null)
Static Public Member Functions
static Quest Create (string _id, string _idPerson=null, Chara c=null)
static List< Zone > ListDeliver ()
Static Public Member Functions inherited from EClass
static int rnd (int a)
static int curve (int a, int start, int step, int rate=75)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Public Attributes
string id
int uid
int uidClientZone
int phase
int lv
int deadline
int difficulty
int rewardMoney
int bonusMoney
int startDate
int dangerLv
bool isNew
bool isComplete
bool track
Person person
QuestTask task
RefChara refChara = new RefChara()
Static Public Attributes
const int PhaseComplete = 999
Static Public Attributes inherited from EClass
static Core core
Properties
Zone ClientZone [get]
Chara chara [get]
SourceQuest.Row source [get]
bool Confetti [get]
bool IsExpired [get]
int Hours [get]
string TextDeadline [get]
virtual bool HasDLC [get]
virtual string idSource [get]
virtual string RewardSuffix [get]
virtual bool FameContent [get]
virtual string TextExtra [get]
virtual string TextExtra2 [get]
virtual int DangerLv [get]
virtual int AffinityGain [get]
virtual int BaseMoney [get]
virtual int KarmaOnFail [get]
virtual bool CanAbandon [get]
virtual int FameOnComplete [get]
virtual int RangeDeadLine [get]
virtual bool UseInstanceZone [get]
virtual bool ForbidTeleport [get]
virtual bool RequireClientInSameZone [get]
virtual Quest.DifficultyType difficultyType [get]
virtual Chara DestChara [get]
virtual string RefDrama1 [get]
virtual string RefDrama2 [get]
virtual string RefDrama3 [get]
virtual string RefDrama4 [get]
virtual string TitlePrefix [get]
virtual bool CanAutoAdvance [get]
virtual bool IsRandomQuest [get]
virtual string NameDeliver [get]
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Detailed Description
Definition at line 6 of file Quest.cs.
Member Enumeration Documentation
DifficultyType
enum Quest.DifficultyType
Enumerator
Default
Deliver
Supply
Escort
Bulk
Meal
Farm
Music
Definition at line 818 of file Quest.cs.
    {
        Default,
        Deliver,
        Supply,
        Escort,
        Bulk,
        Meal,
        Farm,
        Music
    }
SubReward
enum Quest.SubReward
Enumerator
plat
gacha_coin
money2
ticket_furniture
Definition at line 830 of file Quest.cs.
    {
        plat,
        gacha_coin,
        money2,
        ticket_furniture
    }
Member Function Documentation
CanDeliverToBox()
virtual bool Quest.CanDeliverToBox (Thing t) inline virtual
Reimplemented in QuestDeliver.
Definition at line 748 of file Quest.cs.
    {
        return false;
    }
CanDeliverToClient()
virtual bool Quest.CanDeliverToClient (Chara c) inline virtual
Reimplemented in QuestCraft, and QuestDeliver.
Definition at line 743 of file Quest.cs.
    {
        return false;
    }
CanStartQuest()
virtual bool Quest.CanStartQuest () inline virtual
Reimplemented in QuestDialog.
Definition at line 348 of file Quest.cs.
    {
        return true;
    }
Referenced by IsVisibleOnQuestBoard().
CanUpdateOnTalk()
virtual bool Quest.CanUpdateOnTalk (Chara c) inline virtual
Reimplemented in QuestCompanion, QuestCouncil, QuestCrafter, QuestDebt, QuestDefense, QuestExploration, QuestFarrisSister, QuestFiamaLock, QuestIntoDarkness, QuestLoytelFarm, QuestPuppy, QuestSharedContainer, QuestShippingChest, QuestTax, and QuestVernis.
Definition at line 353 of file Quest.cs.
    {
        return false;
    }
Referenced by QuestManager.OnShowDialog().
ChangePhase()
void Quest.ChangePhase (int a) inline
Definition at line 620 of file Quest.cs.
    {
        this.phase = a;
        this.UpdateJournal();
        this.OnChangePhase(a);
    }
References OnChangePhase(), and UpdateJournal().
Referenced by DramaOutcome.guild_join(), NextPhase(), DramaOutcome.QuestExploration_AfterComplete(), DramaOutcome.QuestExploration_AfterCrystal(), DramaOutcome.QuestExploration_MeetFarris2(), Game.StartNewGame(), and Chara.TryDropBossLoot().
Complete()
void Quest.Complete () inline
Definition at line 516 of file Quest.cs.
    {
        this.OnBeforeComplete();
        EClass.game.quests.Remove(this);
        EClass.game.quests.completedIDs.Add(this.id);
        EClass.game.quests.completedTypes.Add(base.GetType().ToString());
        this.ShowCompleteText();
        this.OnDropReward();
        if (this.Confetti)
        {
            EClass.Sound.Play("confetti");
            ScreenEffect.Play("Firework");
        }
        if (this.chara != null && this.chara.quest != null && this.chara.quest.uid == this.uid)
        {
            this.chara.quest = null;
        }
        if (this.DestChara != null && this.DestChara.IsAliveInCurrentZone && this.AffinityGain != 0)
        {
            this.DestChara.ModAffinity(EClass.pc, this.AffinityGain, true);
        }
        if (this.ClientZone != null)
        {
            this.ClientZone.completedQuests.Add(this.uid);
        }
        this.OnComplete();
        EClass.player.ModKarma(1);
        this.isComplete = true;
    }
References chara, ClientZone, QuestManager.completedIDs, Zone.completedQuests, QuestManager.completedTypes, Confetti, DestChara, EClass.game, Chara.IsAliveInCurrentZone, Chara.ModAffinity(), Player.ModKarma(), OnBeforeComplete(), OnComplete(), OnDropReward(), EClass.pc, ScreenEffect.Play(), EClass.player, Chara.quest, Game.quests, QuestManager.Remove(), ShowCompleteText(), EClass.Sound, and uid.
Referenced by QuestManager.Complete(), ZonePreEnterOnCompleteQuestInstance.Execute(), ContentQuest.OnSwitchContent(), and Chara.ShowDialog().
CompleteTask()
void Quest.CompleteTask () inline
Definition at line 568 of file Quest.cs.
    {
        this.OnCompleteTask();
        this.task = null;
    }
References OnCompleteTask().
Referenced by OnGiveItem(), OnKillChara(), and OnModKarma().
Create()
static Quest Quest.Create (string _id, string _idPerson = null, Chara c = null) inline static
Definition at line 8 of file Quest.cs.
    {
        Quest quest = ClassCache.Create<Quest>(EClass.sources.quests.map[_id].type.IsEmpty("Quest"), "Elin");
        quest.id = _id;
        quest.person = new Person(_idPerson, null);
        QuestDestZone questDestZone = quest as QuestDestZone;
        if (questDestZone != null && questDestZone.IsDeliver)
        {
            Zone zone = Quest.ListDeliver().RandomItem<Zone>();
            questDestZone.SetDest(zone, zone.dictCitizen.Keys.RandomItem<int>());
        }
        if (c != null)
        {
            quest.SetClient(c, true);
        }
        quest.Init();
        return quest;
    }
References Create(), Zone.dictCitizen, Init(), QuestDestZone.IsDeliver, ListDeliver(), SourceManager.quests, SetClient(), QuestDestZone.SetDest(), and EClass.sources.
Referenced by QuestManager.Add(), QuestManager.AddQuestAsh(), QuestManager.AddQuestFiama(), Create(), QuestDefense.OnChangePhase(), DramaOutcome.OnClaimLand(), QuestCraft.OnComplete(), QuestIntroInspector.OnComplete(), QuestSharedContainer.OnComplete(), QuestDialog.OnDropReward(), QuestExploration.OnStart(), LayerCraft.RefreshTrackButton(), QuestManager.Start(), and Game.StartNewGame().
CreateInstanceZone()
virtual Zone Quest.CreateInstanceZone (Chara c) inline virtual
Reimplemented in QuestInstance.
Definition at line 374 of file Quest.cs.
    {
        return null;
    }
Deliver()
virtual bool Quest.Deliver (Chara c, Thing t = null) inline virtual
Reimplemented in QuestCraft, and QuestDeliver.
Definition at line 753 of file Quest.cs.
    {
        return false;
    }
DropReward() [1/2]
Thing Quest.DropReward (string id) inline
Definition at line 554 of file Quest.cs.
    {
        return this.DropReward(ThingGen.Create(id, -1, -1));
    }
References ThingGen.Create(), and DropReward().
Referenced by DropReward().
DropReward() [2/2]
Thing Quest.DropReward (Thing t) inline
Definition at line 559 of file Quest.cs.
    {
        return EClass.player.DropReward(t, false);
    }
References Player.DropReward(), and EClass.player.
Equals()
override bool Quest.Equals (object obj) inline
Definition at line 335 of file Quest.cs.
    {
        int num = this.uid;
        Quest quest = obj as Quest;
        int? num2 = (quest != null) ? new int?(quest.uid) : null;
        return num == num2.GetValueOrDefault() & num2 != null;
    }
References uid.
Fail()
void Quest.Fail () inline
Definition at line 486 of file Quest.cs.
    {
        EClass.Sound.Play("questFail");
        if (!(this is QuestTrackCraft))
        {
            EClass.player.ModFame(-10 - (int)((float)EClass.player.fame * 0.05f));
            EClass.player.ModKarma(this.KarmaOnFail);
        }
        EClass.game.quests.Remove(this);
        if (this.chara != null && this.chara.quest != null && this.chara.quest.uid == this.uid)
        {
            this.chara.quest = null;
        }
        if (this.ClientZone != null)
        {
            this.ClientZone.completedQuests.Add(this.uid);
        }
        this.OnFail();
    }
References chara, ClientZone, Zone.completedQuests, Player.fame, EClass.game, KarmaOnFail, Player.ModFame(), Player.ModKarma(), OnFail(), EClass.player, Chara.quest, Game.quests, QuestManager.Remove(), EClass.Sound, and uid.
Referenced by ZonePreEnterOnCompleteQuestInstance.Execute(), and ContentQuest.SelectQuest().
GetDestThing()
virtual Thing Quest.GetDestThing () inline virtual
Reimplemented in QuestDeliver.
Definition at line 260 of file Quest.cs.
    {
        return null;
    }
GetDetail()
virtual string Quest.GetDetail (bool onJournal = false) inline virtual
Reimplemented in QuestProgression, and QuestTrackCraft.
Definition at line 674 of file Quest.cs.
    {
        string text = this.Parse(this.GetDetailText(onJournal));
        if (onJournal)
        {
            string textProgress = this.GetTextProgress();
            if (!textProgress.IsEmpty())
            {
                text = text + "\n\n" + textProgress;
            }
        }
        if (this.task != null)
        {
            this.task.OnGetDetail(ref text, onJournal);
        }
        text = GameLang.Convert(text);
        return text;
    }
References GameLang.Convert(), GetDetailText(), GetTextProgress(), QuestTask.OnGetDetail(), Parse(), task, and text.
Referenced by GetTrackerText(), ContentQuest.SelectQuest(), and ItemQuest.SetQuest().
GetDetailText()
virtual string Quest.GetDetailText (bool onJournal = false) inline virtual
Reimplemented in QuestCraft, and QuestGuild.
Definition at line 693 of file Quest.cs.
    {
        string s = "";
        Rand.UseSeed(this.uid, delegate
        {
            s = this.source.GetText("detail", false).Split(Environment.NewLine.ToCharArray()).RandomItem<string>();
        });
        return s.ToTitleCase(false);
    }
References source, and uid.
Referenced by GetDetail().
GetExtraMoney()
virtual int Quest.GetExtraMoney () inline virtual
Reimplemented in QuestDeliver, QuestEscort, and QuestSupplySpecific.
Definition at line 265 of file Quest.cs.
    {
        return 0;
    }
Referenced by Init().
GetRewardPlat()
virtual int Quest.GetRewardPlat (int money) inline virtual
Reimplemented in QuestMusic.
Definition at line 270 of file Quest.cs.
    {
        return 1 + EClass.rnd(2) + EClass.rndHalf((int)Mathf.Sqrt((float)(money / 200)));
    }
References money, EClass.rnd(), and EClass.rndHalf().
Referenced by QuestRandom.OnDropReward().
GetRewardText()
string Quest.GetRewardText () inline
Definition at line 712 of file Quest.cs.
    {
        string result = "-";
        if (this.rewardMoney != 0 || this is QuestRandom)
        {
            result = ("qReward" + this.RewardSuffix).lang(this.rewardMoney.ToString() ?? "", null, null, null, null);
        }
        return result;
    }
References rewardMoney, and RewardSuffix.
Referenced by ContentQuest.SelectQuest(), and ItemQuest.SetQuest().
GetTalkComplete()
virtual string Quest.GetTalkComplete () inline virtual
Reimplemented in QuestCraft.
Definition at line 727 of file Quest.cs.
    {
        return this.Parse(this.source.GetText("talkComplete", true));
    }
References Parse(), and source.
GetTalkProgress()
virtual string Quest.GetTalkProgress () inline virtual
Reimplemented in QuestCraft.
Definition at line 722 of file Quest.cs.
    {
        return this.Parse(this.source.GetText("talkProgress", true));
    }
References Parse(), and source.
GetTextProgress()
virtual string Quest.GetTextProgress () inline virtual
Reimplemented in QuestCompanion, QuestCraft, QuestDebt, QuestDefense, QuestDefenseGame, QuestDeliver, QuestEscort, QuestHarvest, QuestMusic, QuestSubdue, QuestSupplyCat, and QuestVernis.
Definition at line 703 of file Quest.cs.
    {
        if (this.task != null)
        {
            return this.task.GetTextProgress();
        }
        return "";
    }
References QuestTask.GetTextProgress(), and task.
Referenced by GetDetail(), QuestProgression.GetDetail(), and GetTrackerText().
GetTitle()
virtual string Quest.GetTitle () inline virtual
Reimplemented in QuestSequence, and QuestTrackCraft.
Definition at line 654 of file Quest.cs.
    {
        string s = "";
        Rand.UseSeed(this.uid, delegate
        {
            s = this.source.GetText("name", false).Split(Environment.NewLine.ToCharArray()).RandomItem<string>();
        });
        return s;
    }
References source, and uid.
Referenced by ContentQuest.OnSwitchContent(), ItemQuestTracker.Refresh(), ContentQuest.SelectQuest(), ItemQuest.SetQuest(), ShowCompleteText(), and UpdateJournal().
GetTrackerText()
virtual string Quest.GetTrackerText () inline virtual
Reimplemented in QuestGuild.
Definition at line 664 of file Quest.cs.
    {
        string text = this.GetTextProgress();
        if (text.IsEmpty() && !this.IsRandomQuest)
        {
            text = this.GetDetail(true);
        }
        return text;
    }
References GetDetail(), GetTextProgress(), and text.
Referenced by ItemQuestTracker.Refresh().
Init()
void Quest.Init () inline
Definition at line 386 of file Quest.cs.
    {
        if (this.RangeDeadLine != 0)
        {
            this.deadline = EClass.world.date.GetRaw(0) + (36 + EClass.rnd(12)) * 60 + EClass.rnd(this.RangeDeadLine) * 1440;
        }
        this.uid = EClass.game.quests.uid;
        EClass.game.quests.uid++;
        this.isNew = true;
        this.track = true;
        switch (this.difficultyType)
        {
        case Quest.DifficultyType.Deliver:
        case Quest.DifficultyType.Supply:
        case Quest.DifficultyType.Escort:
            this.difficulty = Mathf.Clamp(6 - this.Hours / 48, 1, 6);
            goto IL_160;
        case Quest.DifficultyType.Bulk:
            this.difficulty = Mathf.Clamp(EClass.rnd(EClass.rnd(((EClass._zone.branch != null) ? EClass._zone.branch.lv : 1) + 3)) + 1, 1, 6);
            goto IL_160;
        case Quest.DifficultyType.Farm:
            this.difficulty = 1 + EClass.rnd(3 + EClass.pc.Evalue(250) / 10);
            goto IL_160;
        case Quest.DifficultyType.Music:
            this.difficulty = 1 + EClass.rnd(3 + EClass.pc.Evalue(241) / 10);
            goto IL_160;
        }
        this.difficulty = 3 + EClass.rnd(EClass.rnd(4)) - EClass.rnd(4);
        IL_160:
        this.difficulty = Mathf.Clamp(this.difficulty, 1, 7);
        this.OnInit();
        if (this.task != null)
        {
            this.task.OnInit();
        }
        int fameLv = EClass.pc.FameLv;
        this.dangerLv = Mathf.Max(fameLv + EClass.rnd(fameLv / 10 + 5) - EClass.rnd(fameLv / 10 + 5), 1);
        this.rewardMoney = (this.BaseMoney + EClass.rnd(this.BaseMoney / 4) + this.GetExtraMoney()) * (55 + this.difficulty * 15) / 100;
    }
References EClass._zone, BaseMoney, Zone.branch, World.date, difficulty, difficultyType, Card.Evalue(), Card.FameLv, EClass.game, GetExtraMoney(), Date.GetRaw(), Hours, FactionBranch.lv, OnInit(), QuestTask.OnInit(), EClass.pc, Game.quests, RangeDeadLine, EClass.rnd(), task, QuestManager.uid, and EClass.world.
Referenced by Create().
IsDeliverTarget()
virtual bool Quest.IsDeliverTarget (Chara c) inline virtual
Reimplemented in QuestDeliver.
Definition at line 738 of file Quest.cs.
    {
        return false;
    }
IsVisibleOnQuestBoard()
virtual bool Quest.IsVisibleOnQuestBoard () inline virtual
Definition at line 343 of file Quest.cs.
    {
        return (!this.RequireClientInSameZone || (this.chara != null && this.chara.IsAliveInCurrentZone && this.chara.conSuspend == null)) && EClass.world.date.GetRaw(0) >= this.startDate && this.CanStartQuest() && ((!this.chara.IsPCFaction && this is QuestRandom) || EClass._zone.IsPCFaction) && (this.chara == null || !(this.chara.trait is TraitLoytel) || this.chara.currentZone == null || this.chara.currentZone.IsPCFaction);
    }
References EClass._zone, CanStartQuest(), chara, Chara.currentZone, World.date, Date.GetRaw(), Chara.IsAliveInCurrentZone, Zone.IsPCFaction, RequireClientInSameZone, and EClass.world.
Referenced by TCExtra.OnDraw(), and LayerQuestBoard.RefreshQuest().
ListDeliver()
static List< Zone > Quest.ListDeliver () inline static
Definition at line 27 of file Quest.cs.
    {
        List<Zone> list = new List<Zone>();
        foreach (Zone zone in EClass.game.spatials.Zones)
        {
            if (zone != EClass._zone && zone.IsTown && !zone.IsClosed && !zone.IsPCFaction && zone.dictCitizen.Count > 0 && zone.CanBeDeliverDestination)
            {
                list.Add(zone);
            }
        }
        return list;
    }
References EClass._zone, Zone.CanBeDeliverDestination, Zone.dictCitizen, EClass.game, Spatial.IsClosed, Zone.IsPCFaction, Zone.IsTown, Game.spatials, and SpatialManager.Zones.
Referenced by Create().
NextPhase()
void Quest.NextPhase () inline
Definition at line 615 of file Quest.cs.
    {
        this.ChangePhase(this.phase + 1);
    }
References ChangePhase(), and phase.
Referenced by DramaOutcome.guild_mageTrial(), ContentQuest.OnSwitchContent(), DramaManager.ParseLine(), DramaOutcome.poppy_found(), and UpdateOnTalk().
OnBeforeComplete()
virtual void Quest.OnBeforeComplete () inline virtual
Reimplemented in QuestDefenseGame, and QuestHarvest.
Definition at line 546 of file Quest.cs.
    {
    }
Referenced by Complete().
OnChangePhase()
virtual void Quest.OnChangePhase (int a) inline virtual
Reimplemented in QuestDefense, QuestGuildFighter, and QuestVernis.
Definition at line 627 of file Quest.cs.
    {
    }
Referenced by ChangePhase().
OnClickQuest()
virtual void Quest.OnClickQuest () inline virtual
Definition at line 472 of file Quest.cs.
    {
        if (!this.source.drama.IsEmpty())
        {
            LayerDrama.currentQuest = this;
            SoundManager.ForceBGM();
            this.chara.ShowDialog(this.source.drama[0], (this.source.drama.Length > 1) ? this.source.drama[1] : ("quest_" + this.source.id), "");
            return;
        }
        LayerDrama.currentQuest = this;
        LayerDrama.forceJump = "_quest";
        this.chara.ShowDialog();
    }
References chara, Chara.ShowDialog(), and source.
Referenced by LayerQuestBoard.RefreshQuest(), and UpdateOnTalk().
OnComplete()
virtual void Quest.OnComplete () inline virtual
Reimplemented in QuestCraft, QuestIntroInspector, QuestLoytelFarm, QuestSharedContainer, QuestShippingChest, QuestTax, and QuestVernis.
Definition at line 564 of file Quest.cs.
    {
    }
Referenced by Complete().
OnCompleteTask()
virtual void Quest.OnCompleteTask () inline virtual
Reimplemented in QuestSequence.
Definition at line 574 of file Quest.cs.
    {
        EClass.game.quests.Complete(this);
    }
References QuestManager.Complete(), EClass.game, and Game.quests.
Referenced by CompleteTask().
OnDropReward()
virtual void Quest.OnDropReward () inline virtual
Reimplemented in QuestCompanion, QuestCraft, QuestCrafter, QuestDefense, QuestDialog, QuestPuppy, QuestRandom, and QuestTax.
Definition at line 550 of file Quest.cs.
    {
    }
Referenced by Complete().
OnEnterZone()
virtual void Quest.OnEnterZone () inline virtual
Reimplemented in QuestDeliver, QuestEscort, and QuestVernis.
Definition at line 468 of file Quest.cs.
    {
    }
Referenced by QuestManager.OnEnterZone().
OnFail()
virtual void Quest.OnFail () inline virtual
Reimplemented in QuestEscort.
Definition at line 506 of file Quest.cs.
    {
    }
Referenced by Fail().
OnGiveItem()
virtual void Quest.OnGiveItem (Chara c, Thing t) inline virtual
Definition at line 579 of file Quest.cs.
    {
        if (this.task != null)
        {
            this.task.OnGiveItem(c, t);
            if (this.task.IsComplete())
            {
                this.CompleteTask();
            }
        }
    }
References CompleteTask(), QuestTask.IsComplete(), QuestTask.OnGiveItem(), and task.
Referenced by Chara.GiveGift().
OnInit()
virtual void Quest.OnInit () inline virtual
Reimplemented in QuestDefenseGame, QuestDeliver, QuestGuildFighter, QuestGuildMerchant, QuestGuildThief, QuestHarvest, QuestHunt, QuestHuntRace, and QuestMusic.
Definition at line 426 of file Quest.cs.
    {
    }
Referenced by Init().
OnKillChara()
virtual void Quest.OnKillChara (Chara c) inline virtual
Definition at line 591 of file Quest.cs.
    {
        if (this.task != null)
        {
            this.task.OnKillChara(c);
            if (this.task.IsComplete())
            {
                this.CompleteTask();
            }
        }
    }
References CompleteTask(), QuestTask.IsComplete(), QuestTask.OnKillChara(), and task.
Referenced by Card.DamageHP().
OnModKarma()
virtual void Quest.OnModKarma (int a) inline virtual
Definition at line 603 of file Quest.cs.
    {
        if (this.task != null)
        {
            this.task.OnModKarma(a);
            if (this.task.IsComplete())
            {
                this.CompleteTask();
            }
        }
    }
References CompleteTask(), QuestTask.IsComplete(), QuestTask.OnModKarma(), and task.
Referenced by Player.ModKarma().
OnStart()
virtual void Quest.OnStart () inline virtual
Reimplemented in QuestDebt, QuestDeliver, QuestEscort, QuestExploration, QuestFiamaLock, QuestHuntRace, and QuestIntoDarkness.
Definition at line 464 of file Quest.cs.
    {
    }
Referenced by Start().
Parse()
string Quest.Parse (string s) inline
Definition at line 631 of file Quest.cs.
    {
        if (s.IsEmpty())
        {
            return s;
        }
        GameLang.refDrama1 = this.RefDrama1.TagColor(FontColor.QuestObjective, null);
        GameLang.refDrama2 = this.RefDrama2.TagColor(FontColor.QuestObjective, null);
        GameLang.refDrama3 = this.RefDrama3.TagColor(FontColor.QuestObjective, null);
        GameLang.refDrama4 = this.RefDrama4.TagColor(FontColor.QuestObjective, null);
        Rand.UseSeed(this.uid, delegate
        {
            s = GameLang.ConvertDrama(s, this.chara);
            if (this.chara != null)
            {
                s = this.chara.ApplyTone(s, false);
                return;
            }
            s = Card.ApplyTone(this.chara, ref s, this.person.tones, this.person.gender, false);
        });
        return s;
    }
References Card.ApplyTone(), chara, GameLang.ConvertDrama(), person, RefDrama1, RefDrama2, RefDrama3, RefDrama4, Person.tones, and uid.
Referenced by GetDetail(), GetTalkComplete(), and GetTalkProgress().
SetClient()
Quest Quest.SetClient (Chara c, bool assignQuest = true) inline
Definition at line 430 of file Quest.cs.
    {
        if (c == null)
        {
            this.person = new Person();
            return this;
        }
        if (assignQuest)
        {
            c.quest = this;
        }
        if (c.currentZone != null)
        {
            this.uidClientZone = c.currentZone.uid;
        }
        this.person = new Person(c);
        return this;
    }
References Chara.currentZone, and Spatial.uid.
Referenced by QuestManager.Add(), QuestManager.AddQuestAsh(), QuestManager.AddQuestFiama(), Create(), QuestDefense.OnChangePhase(), DramaOutcome.OnClaimLand(), QuestCraft.OnComplete(), QuestIntroInspector.OnComplete(), QuestSharedContainer.OnComplete(), QuestDialog.OnDropReward(), QuestExploration.OnStart(), QuestManager.Start(), and Game.StartNewGame().
SetTask()
void Quest.SetTask (QuestTask _task) inline
Definition at line 449 of file Quest.cs.
    {
        this.task = _task;
        this.task.SetOwner(this);
    }
References QuestTask.SetOwner(), and task.
ShowCompleteText()
virtual void Quest.ShowCompleteText () inline virtual
Reimplemented in QuestDialog.
Definition at line 510 of file Quest.cs.
    {
        EClass.Sound.Play("questComplete");
        Msg.Say("completeQuest", this.GetTitle(), null, null, null);
    }
References GetTitle(), Msg.Say(), and EClass.Sound.
Referenced by Complete().
Start()
void Quest.Start () inline
Definition at line 455 of file Quest.cs.
    {
        this.OnStart();
        if (this.task != null)
        {
            this.task.OnStart();
        }
    }
References OnStart(), QuestTask.OnStart(), and task.
Referenced by QuestManager.Start().
UpdateJournal()
void Quest.UpdateJournal () inline
Definition at line 732 of file Quest.cs.
    {
        SE.WriteJournal();
        Msg.Say("journalUpdate2", this.GetTitle(), null, null, null);
    }
References GetTitle(), and Msg.Say().
Referenced by ChangePhase(), InvOwnerDeliver.PayBill(), and QuestManager.Start().
UpdateOnTalk()
virtual bool Quest.UpdateOnTalk () inline virtual
Reimplemented in QuestGuild.
Definition at line 379 of file Quest.cs.
    {
        this.NextPhase();
        this.OnClickQuest();
        return true;
    }
References NextPhase(), and OnClickQuest().
Referenced by QuestVernis.OnEnterZone(), and QuestManager.OnShowDialog().
Member Data Documentation
bonusMoney
int Quest.bonusMoney
Definition at line 793 of file Quest.cs.
dangerLv
int Quest.dangerLv
Definition at line 799 of file Quest.cs.
deadline
int Quest.deadline
Definition at line 784 of file Quest.cs.
Referenced by ItemQuestTracker.Refresh(), and QuestManager.Remove().
difficulty
int Quest.difficulty
Definition at line 787 of file Quest.cs.
Referenced by QuestSupplyBulkJunk.GetDestNum(), Init(), ZoneEventHarvest.OnVisit(), ZoneEventMusic.OnVisit(), and ItemQuest.SetQuest().
id
string Quest.id
Definition at line 769 of file Quest.cs.
Referenced by QuestManager.Get(), QuestManager.GetGlobal(), QuestSequence.GetTitle(), QuestCraft.OnComplete(), QuestCraft.OnDropReward(), QuestCraft.OnProgressComplete(), QuestCraft.Req.Req(), and QuestSupplySpecific.SetIdThing().
isComplete
bool Quest.isComplete
Definition at line 805 of file Quest.cs.
isNew
bool Quest.isNew
Definition at line 802 of file Quest.cs.
Referenced by TCExtra.OnDraw(), and ItemQuest.SetQuest().
lv
int Quest.lv
Definition at line 781 of file Quest.cs.
person
Person Quest.person
Definition at line 811 of file Quest.cs.
Referenced by QuestDeliver.CanDeliverToClient(), QuestManager.OnShowDialog(), Parse(), ItemQuestTracker.Refresh(), ContentQuest.SelectQuest(), and ItemQuest.SetQuest().
phase
int Quest.phase
Definition at line 778 of file Quest.cs.
Referenced by QuestCompanion.CanUpdateOnTalk(), QuestCouncil.CanUpdateOnTalk(), QuestCrafter.CanUpdateOnTalk(), QuestDebt.CanUpdateOnTalk(), QuestDefense.CanUpdateOnTalk(), QuestLoytelFarm.CanUpdateOnTalk(), QuestSharedContainer.CanUpdateOnTalk(), QuestShippingChest.CanUpdateOnTalk(), QuestTax.CanUpdateOnTalk(), QuestVernis.CanUpdateOnTalk(), QuestManager.GetPhase< T >(), QuestCompanion.GetTextProgress(), QuestDefense.GetTextProgress(), QuestVernis.GetTextProgress(), QuestSequence.GetTitle(), NextPhase(), QuestDefense.OnChangePhase(), QuestVernis.OnChangePhase(), QuestVernis.OnEnterZone(), Zone_DungeonPuppy.OnGenerateMap(), and ContentQuest.OnSwitchContent().
PhaseComplete
const int Quest.PhaseComplete = 999 static
Definition at line 766 of file Quest.cs.
refChara
RefChara Quest.refChara = new RefChara()
Definition at line 816 of file Quest.cs.
rewardMoney
int Quest.rewardMoney
Definition at line 790 of file Quest.cs.
Referenced by QuestSupplySpecific.GetBonus(), and GetRewardText().
startDate
int Quest.startDate
Definition at line 796 of file Quest.cs.
Referenced by QuestLoytelFarm.OnComplete(), QuestShippingChest.OnComplete(), QuestVernis.OnComplete(), QuestDialog.OnDropReward(), and QuestIntoDarkness.OnStart().
task
QuestTask Quest.task
Definition at line 814 of file Quest.cs.
Referenced by GetDetail(), GetTextProgress(), Init(), OnGiveItem(), OnKillChara(), OnModKarma(), ContentQuest.OnSwitchContent(), SetTask(), and Start().
track
bool Quest.track
Definition at line 808 of file Quest.cs.
Referenced by ContentQuest.OnSwitchContent(), ItemQuestTracker.Refresh(), WidgetQuestTracker.Refresh(), and ContentQuest.RefreshTrackButtons().
uid
int Quest.uid
Definition at line 772 of file Quest.cs.
Referenced by QuestDeliver.CanDeliverToClient(), Complete(), QuestInstance.CreateInstanceZone(), Equals(), ZonePreEnterOnCompleteQuestInstance.Execute(), Fail(), QuestManager.Get(), GetDetailText(), GetTitle(), QuestDeliver.IsDeliverTarget(), QuestRandom.OnDropReward(), Parse(), QuestManager.Remove(), and Zone.UpdateQuests().
uidClientZone
int Quest.uidClientZone
Definition at line 775 of file Quest.cs.
Property Documentation
AffinityGain
virtual int Quest.AffinityGain get
Definition at line 180 of file Quest.cs.
    {
        get
        {
            return 20;
        }
    }
BaseMoney
virtual int Quest.BaseMoney get
Definition at line 188 of file Quest.cs.
    {
        get
        {
            return this.source.money;
        }
    }
Referenced by Init().
CanAbandon
virtual bool Quest.CanAbandon get
Definition at line 204 of file Quest.cs.
    {
        get
        {
            return this.IsRandomQuest;
        }
    }
Referenced by ContentQuest.SelectQuest().
CanAutoAdvance
virtual bool Quest.CanAutoAdvance get
Definition at line 358 of file Quest.cs.
    {
        get
        {
            return true;
        }
    }
Referenced by QuestManager.OnShowDialog(), and ContentQuest.OnSwitchContent().
chara
Chara Quest.chara get
Definition at line 64 of file Quest.cs.
    {
        get
        {
            return this.person.chara;
        }
    }
Referenced by QuestDeliver.CanDeliverToClient(), QuestDefense.CanUpdateOnTalk(), Complete(), Fail(), IsVisibleOnQuestBoard(), QuestVernis.OnChangePhase(), OnClickQuest(), QuestIntroInspector.OnComplete(), QuestVernis.OnComplete(), QuestDialog.OnDropReward(), QuestDeliver.OnEnterZone(), QuestDebt.OnStart(), QuestEscort.OnStart(), and Parse().
ClientZone
Zone Quest.ClientZone get
Definition at line 40 of file Quest.cs.
    {
        get
        {
            Zone result;
            if (this.chara == null || !this.chara.IsGlobal || this.chara.currentZone == null)
            {
                if ((result = RefZone.Get(this.uidClientZone)) == null)
                {
                    if (this.source.idZone.IsEmpty())
                    {
                        return EClass.game.StartZone;
                    }
                    return EClass.game.spatials.Find(this.source.idZone);
                }
            }
            else
            {
                result = this.chara.currentZone;
            }
            return result;
        }
    }
Referenced by Complete(), Fail(), and ContentQuest.SelectQuest().
Confetti
bool Quest.Confetti get
Definition at line 80 of file Quest.cs.
    {
        get
        {
            return false;
        }
    }
Referenced by Complete().
DangerLv
virtual int Quest.DangerLv get
Definition at line 172 of file Quest.cs.
    {
        get
        {
            return this.dangerLv;
        }
    }
DestChara
virtual Chara Quest.DestChara get
Definition at line 275 of file Quest.cs.
    {
        get
        {
            return this.chara;
        }
    }
Referenced by Complete().
difficultyType
virtual Quest.DifficultyType Quest.difficultyType get
Definition at line 252 of file Quest.cs.
    {
        get
        {
            return Quest.DifficultyType.Default;
        }
    }
Referenced by Init().
FameContent
virtual bool Quest.FameContent get
Definition at line 144 of file Quest.cs.
    {
        get
        {
            return false;
        }
    }
FameOnComplete
virtual int Quest.FameOnComplete get
Definition at line 212 of file Quest.cs.
    {
        get
        {
            return 0;
        }
    }
ForbidTeleport
virtual bool Quest.ForbidTeleport get
Definition at line 236 of file Quest.cs.
    {
        get
        {
            return false;
        }
    }
HasDLC
virtual bool Quest.HasDLC get
Definition at line 120 of file Quest.cs.
    {
        get
        {
            return true;
        }
    }
Hours
int Quest.Hours get
Definition at line 96 of file Quest.cs.
    {
        get
        {
            if (this.deadline != 0)
            {
                return EClass.world.date.GetRemainingHours(this.deadline);
            }
            return -1;
        }
    }
Referenced by Init(), QuestManager.Remove(), and ItemQuest.SetQuest().
idSource
virtual string Quest.idSource get
Definition at line 128 of file Quest.cs.
    {
        get
        {
            return this.id;
        }
    }
IsExpired
bool Quest.IsExpired get
Definition at line 88 of file Quest.cs.
    {
        get
        {
            return (this.deadline > 0 && this.Hours < 0) || this.isComplete;
        }
    }
Referenced by QuestManager.OnAdvanceHour(), and Zone.UpdateQuests().
IsRandomQuest
virtual bool Quest.IsRandomQuest get
Definition at line 366 of file Quest.cs.
    {
        get
        {
            return false;
        }
    }
Referenced by QuestManager.Remove(), and ItemQuest.SetQuest().
KarmaOnFail
virtual int Quest.KarmaOnFail get
Definition at line 196 of file Quest.cs.
    {
        get
        {
            return 0;
        }
    }
Referenced by Fail().
NameDeliver
virtual string Quest.NameDeliver get
Definition at line 758 of file Quest.cs.
    {
        get
        {
            return "";
        }
    }
RangeDeadLine
virtual int Quest.RangeDeadLine get
Definition at line 220 of file Quest.cs.
    {
        get
        {
            return 0;
        }
    }
Referenced by Init().
RefDrama1
virtual string Quest.RefDrama1 get
Definition at line 283 of file Quest.cs.
    {
        get
        {
            if (this.task == null)
            {
                return "";
            }
            return this.task.RefDrama1;
        }
    }
Referenced by Parse().
RefDrama2
virtual string Quest.RefDrama2 get
Definition at line 295 of file Quest.cs.
    {
        get
        {
            if (this.task == null)
            {
                return "";
            }
            return this.task.RefDrama2;
        }
    }
Referenced by Parse().
RefDrama3
virtual string Quest.RefDrama3 get
Definition at line 307 of file Quest.cs.
    {
        get
        {
            if (this.task == null)
            {
                return "";
            }
            return this.task.RefDrama3;
        }
    }
Referenced by Parse().
RefDrama4
virtual string Quest.RefDrama4 get
Definition at line 319 of file Quest.cs.
    {
        get
        {
            return "";
        }
    }
Referenced by Parse().
RequireClientInSameZone
virtual bool Quest.RequireClientInSameZone get
Definition at line 244 of file Quest.cs.
    {
        get
        {
            return true;
        }
    }
Referenced by IsVisibleOnQuestBoard().
RewardSuffix
virtual string Quest.RewardSuffix get
Definition at line 136 of file Quest.cs.
    {
        get
        {
            return "";
        }
    }
Referenced by GetRewardText().
source
SourceQuest.Row Quest.source get
Definition at line 72 of file Quest.cs.
    {
        get
        {
            return EClass.sources.quests.map[this.idSource];
        }
    }
Referenced by QuestManager.Add(), GetDetailText(), GetTalkComplete(), GetTalkProgress(), GetTitle(), OnClickQuest(), ContentQuest.OnSwitchContent(), QuestManager.Remove(), and QuestSupplyCat.SetIdThing().
TextDeadline
string Quest.TextDeadline get
Definition at line 108 of file Quest.cs.
    {
        get
        {
            if (this.deadline != 0)
            {
                return Date.GetText((this.Hours < 0) ? 0 : this.Hours);
            }
            return "dateDayVoid".lang();
        }
    }
Referenced by ContentQuest.OnSwitchContent(), ItemQuestTracker.Refresh(), and ContentQuest.SelectQuest().
TextExtra
virtual string Quest.TextExtra get
Definition at line 152 of file Quest.cs.
    {
        get
        {
            return null;
        }
    }
Referenced by ItemQuest.SetQuest().
TextExtra2
virtual string Quest.TextExtra2 get
Definition at line 160 of file Quest.cs.
    {
        get
        {
            if (!this.FameContent)
            {
                return null;
            }
            return "dangerLv".lang(this.DangerLv.ToString() ?? "", null, null, null, null);
        }
    }
Referenced by QuestDeliver.GetTextProgress(), and ItemQuest.SetQuest().
TitlePrefix
virtual string Quest.TitlePrefix get
Definition at line 327 of file Quest.cs.
    {
        get
        {
            return "";
        }
    }
Referenced by ContentQuest.OnSwitchContent(), and ItemQuest.SetQuest().
UseInstanceZone
virtual bool Quest.UseInstanceZone get
Definition at line 228 of file Quest.cs.
    {
        get
        {
            return false;
        }
    }
The documentation for this class was generated from the following file:
Elin/Quest.cs