Elin Decompiled Documentation: LayerResource Class Reference
LayerResource Class Reference
Public Member Functions
override void OnInit ()
override void OnKill ()
void RefreshCategory ()
void ShowThings (SourceCategory.Row cat)
Public Member Functions inherited from ELayer
override void OnBeforeAddLayer ()
void InitInspector ()
sealed override void Init ()
override void OnAfterAddLayer ()
void TryShowHelp ()
void AddLayerToUI (string id)
void TryShowHint (string _langHint=null)
void TalkHomeMemeber (string id)
void TalkMaid (string id)
override void OnRightClick ()
Public Member Functions inherited from Layer
virtual string GetTextHeader (Window window)
virtual bool HeaderIsListOf (int id)
virtual void Init ()
virtual void OnInit ()
virtual void OnAfterInit ()
virtual void ApplySkin ()
void ShowScreenLock (string id)
void UpdateInput ()
virtual void OnUpdateInput ()
virtual void OnRightClick ()
virtual bool OnBack ()
virtual void OnChangeLayer ()
virtual void OnCreate ()
void _AddLayer (string id)
Layer AddLayer (string id)
T AddLayer< T > ()
T AddLayer< T > (string id)
T AddLayerDontCloseOthers< T > ()
Layer AddLayerDontCloseOthers (Layer l)
T GetOrAddLayer< T > ()
virtual void OnBeforeAddLayer ()
virtual void OnAfterAddLayer ()
Layer AddLayer (Layer l)
void ToggleLayer (string id)
T ToggleLayer< T > (string id=null)
void WaitAndClose ()
void OnClickClose ()
virtual void Close ()
void CloseLayers ()
void RemoveLayers (bool removeImportant=false)
bool RemoveLayer< T > ()
void RemoveLayer (Layer l)
virtual void OnKill ()
Layer SetOnKill (Action action)
void DisableClose ()
void Delay (float duration=0.05f)
Layer SetDelay (float d)
Layer GetLayer (string id)
T GetLayer< T > (bool fromTop=false)
Layer GetTopLayer ()
void SwitchContent (int idWindow, int i)
virtual void OnSwitchContent (Window window)
Layer SetTitles (string langList, string idHeaderRow=null)
bool IsBlockWidgetClick ()
bool IsHideHud ()
bool IsAllowGeneralInput ()
bool IsUseBlur ()
bool IsPointerOnLayer ()
void ApplySkin ()
Public Attributes
UIList list
UIDynamicList list2
UICardInfo info
UINote noteOverview
Public Attributes inherited from Layer
Option option
UnityEvent onKill
Anime animeIn
Anime animeOut
bool closeOthers
bool defaultActionMode = true
Button screenLock
Layer parent
string idLayer
List< Layer > layers = new List<Layer>()
Vector2 lastParentPos
List< Window > windows = new List<Window>()
string langHint
Static Public Attributes
static string selectCat
Static Public Attributes inherited from Layer
static int skipInput
static bool closeOnRightClick
static bool rightClicked
static bool cancelKeyDown
static bool ignoreSounds
static Transform blurStopInstance
static string[] searchPath = new string[3] { "Layer", "Layer/Dialog", "Layer/LayerHome" }
Additional Inherited Members
Static Public Member Functions inherited from ELayer
static int rnd (int a)
Static Public Member Functions inherited from Layer
static T Create< T > ()
static T Create< T > (string path)
static Layer Create (string path)
Protected Member Functions inherited from ELayer
sealed override void _Close ()
sealed override void Kill ()
Protected Member Functions inherited from Layer
virtual void Awake ()
virtual void _Close ()
virtual void Kill ()
Protected Attributes inherited from Layer
RectTransform _rect
bool isDestroyed
Properties inherited from ELayer
static Core core [get]
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static FactionBranch Branch [get]
static Faction Home [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static CoreConfig config [get]
static GameSetting setting [get]
static ColorProfile Colors [get]
static SourceManager sources [get]
static World world [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
bool IsFloat [get]
virtual string IdHelp [get]
Properties inherited from Layer
Layer TopLayer [get]
string uid [get]
virtual RectTransform rectLayers [get]
virtual bool blockWidgetClick [get]
Detailed Description
Definition at line 3 of file LayerResource.cs.
Member Function Documentation
OnInit()
override void LayerResource.OnInit () inline virtual
Reimplemented from Layer.
Definition at line 15 of file LayerResource.cs.
    {
        list2.sortMode = ELayer.player.pref.sortResources;
        RefreshCategory();
        if (!selectCat.IsEmpty())
        {
            list.Select((SourceCategory.Row a) => a.id == selectCat, invoke: true);
        }
        else
        {
            list.Select(0, invoke: true);
        }
        selectCat = null;
        WindowMenu menuRight = windows[0].menuRight;
        menuRight.AddButton2Line("sort", () => list2.sortMode.ToString(), delegate
        {
            list2.NextSort();
        });
        menuRight.AddButton2Line("stockCapacity", () => ELayer._map.Stocked.weight + "/" + ELayer._map.Stocked.maxWeight);
    }
References ELayer._map, WindowMenu.AddButton2Line(), list, list2, Props.maxWeight, ELayer.player, Player.pref, RefreshCategory(), UIList.Select(), selectCat, BaseList.sortMode, Player.Pref.sortResources, Map.Stocked, Props.weight, and Layer.windows.
OnKill()
override void LayerResource.OnKill () inline virtual
Reimplemented from Layer.
Definition at line 36 of file LayerResource.cs.
    {
        ELayer.player.pref.sortResources = list2.sortMode;
    }
References list2, and BaseList.sortMode.
RefreshCategory()
void LayerResource.RefreshCategory () inline
Definition at line 41 of file LayerResource.cs.
    {
        HashSet<string> track = ELayer.player.trackedCategories;
        list.Clear();
        list.callbacks = new UIList.Callback<SourceCategory.Row, ButtonCategory>
        {
            onClick = delegate(SourceCategory.Row a, ButtonCategory b)
            {
                ShowThings(a);
            },
            onInstantiate = delegate(SourceCategory.Row cat, ButtonCategory b)
            {
                b.toggle.SetActive(enable: true);
                b.toggle.isOn = track.Contains(cat.id);
                b.toggle.onValueChanged.AddListener(delegate(bool isOn)
                {
                    SE.ClickGeneral();
                    if (isOn)
                    {
                        track.Add(cat.id);
                    }
                    else
                    {
                        track.Remove(cat.id);
                    }
                    UIResourceTrack.Refresh();
                });
                int sum = ELayer._map.Stocked.categoryMap[cat.id].sum;
                b.mainText.text = cat.GetText().ToTitleCase() + " (" + sum + ")";
                b.SetFold(cat.children.Count > 0, folded: true, delegate(UIList l)
                {
                    foreach (SourceCategory.Row row in ELayer.sources.categories.rows)
                    {
                        if (row.parent == cat)
{
                            l.Add(row);
                        }
                    }
                });
            },
            onRefresh = null
        };
        foreach (SourceCategory.Row row2 in ELayer.sources.categories.rows)
        {
            if (!(row2.id == "new") && !(row2.id == "stash") && row2.parent == null)
            {
                list.Add(row2);
            }
        }
        list.Refresh();
        UIResourceTrack.Refresh();
    }
References ELayer._map, SourceManager.categories, Props.categoryMap, UIList.Clear(), list, ELayer.player, UIResourceTrack.Refresh(), ButtonCategory.SetFold(), ShowThings(), ELayer.sources, Map.Stocked, ButtonCategory.toggle, and Player.trackedCategories.
Referenced by OnInit().
ShowThings()
void LayerResource.ShowThings (SourceCategory::Row cat) inline
Definition at line 94 of file LayerResource.cs.
    {
        HashSet<string> track = ELayer.player.trackedCards;
        list2.callbacks = new UIList.Callback<Thing, ButtonGrid>
        {
            onRedraw = delegate(Thing a, ButtonGrid b, int i)
            {
                b.SetCard(a);
                bool check = track.Contains(a.source.id);
                b.SetCheck(check);
            },
            onClick = delegate(Thing a, ButtonGrid b)
            {
                if (!track.Contains(a.source.id))
                {
                    track.Add(a.source.id);
                }
                else
                {
                    track.Remove(a.source.id);
                }
                UIResourceTrack.Refresh();
                list2.dsv.refresh();
                SE.Tab();
            },
            onList = delegate(UIList.SortMode m)
            {
                List<Thing> list = new List<Thing>();
                list = ELayer._map.Stocked.ListThingsInCategory(cat);
                for (int j = 0; j < list.Count; j++)
                {
                    list[j].SetSortVal(m);
                }
                list.Sort((Thing a, Thing b) => a.sortVal - b.sortVal);
                int num = 0;
                int num2 = 0;
                foreach (Thing item in list)
                {
                    list2.Add(item);
                    num += item.Num;
                    num2 += item.Num;
                }
                windows[0].textStats.SetText("statsTotal".lang(list.Count.ToString() ?? "", num.ToString() ?? "", num2.ToString() ?? ""));
            }
        };
        list2.List();
    }
References ELayer._map, UIDynamicList.Add(), UIDynamicList.dsv, item, UIDynamicList.List(), Props.ListThingsInCategory(), ELayer.player, UIResourceTrack.Refresh(), ButtonGrid.SetCard(), UIButton.SetCheck(), Card.sortVal, Thing.source, Map.Stocked, and Player.trackedCards.
Referenced by RefreshCategory().
Member Data Documentation
info
UICardInfo LayerResource.info
Definition at line 9 of file LayerResource.cs.
list
UIList LayerResource.list
Definition at line 5 of file LayerResource.cs.
Referenced by OnInit(), and RefreshCategory().
list2
UIDynamicList LayerResource.list2
Definition at line 7 of file LayerResource.cs.
Referenced by OnInit(), and OnKill().
noteOverview
UINote LayerResource.noteOverview
Definition at line 11 of file LayerResource.cs.
selectCat
string LayerResource.selectCat static
Definition at line 13 of file LayerResource.cs.
Referenced by OnInit().
The documentation for this class was generated from the following file:
Elin/LayerResource.cs