Elin Decompiled Documentation: Zone Class Reference
Zone Class Reference
Classes
class PortalReturnData
Public Member Functions
virtual string GetDungenID ()
virtual string GetNewZoneID (int level)
override string ToString ()
string TextLevel (int _lv)
override void OnCreate ()
override void OnAfterCreate ()
void Activate ()
void RefreshHat ()
void OnVisit ()
void Revive ()
virtual void OnRegenerate ()
virtual void OnActivate ()
virtual void OnBeforeDeactivate ()
virtual void OnDeactivate ()
virtual void OnBeforeSimulate ()
virtual void OnVisitNewMapOrRegenerate ()
virtual void OnAfterSimulate ()
virtual void OnAdvanceHour ()
void Simulate ()
Point GetSpawnPos (Chara c, ZoneTransition.EnterState destState=ZoneTransition.EnterState.Auto)
Point GetRandomVisitPos (Chara c)
void AddGlobalCharasOnActivate ()
void Deactivate ()
void OnKillGame ()
void UnloadMap ()
void ClaimZone (bool debug=false)
void AbandonZone ()
bool CanDestroy ()
override void _OnBeforeSave ()
override void OnLoad ()
override void Destroy ()
void ClearZones (Zone current=null)
void OnChildNumChange (Card c)
ICardParent GetRoot ()
Zone GetTopZone ()
Card AddCardSplinkle (Card t, Point center, int radius=4)
Card AddChara (string id, int x, int z)
Card AddThing (string id, int x, int z)
Card AddThing (string id, Point p)
Card AddCard (Card t, Point point)
Card AddCard (Card t)
Card AddCard (Card t, int x, int z)
void RemoveCard (Card t)
T GetRandomSpot< T > ()
bool TryAddThingInSpot< T > (Thing t, bool useContainer=true, bool putRandomPosIfNoSpot=true)
List< Thing > TryListThingsInSpot< T > (Func< Thing, bool > func=null)
bool TryAddThingInSharedContainer (Thing t, List< Thing > containers=null, bool add=true, bool msg=false, Chara chara=null, bool sharedOnly=true)
bool TryAddThing (Thing target, Point p, bool destroyIfFail=false)
Thing TryGetThingFromSharedContainer (Func< Thing, bool > func)
Thing TryGetRestock< T > (string idCat)
ZoneProfile GetProfile ()
void CreateBP ()
virtual void OnCreateBP ()
void Generate ()
void TrySpawnFollower ()
void SpawnAltar ()
virtual void OnGenerateMap ()
void TryGenerateOre ()
Chara TryGenerateEvolved (bool force=false, Point p=null)
void TryGenerateBigDaddy ()
void TryGenerateShrine ()
void ResetHostility ()
virtual void OnGenerateRooms (BaseMapGen gen)
Point GetSpawnPos (SpawnPosition type, int tries=100)
Chara SpawnMob (Point pos=null, SpawnSetting setting=null)
void RefreshElectricity ()
int GetElectricity (bool cost=false)
void SetBGM (List< int > ids, bool refresh=true)
void SetBGM (int id=-1, bool refresh=true)
void RefreshPlaylist ()
void RefreshBGM ()
Playlist CreatePlaylist (ref List< int > list, Playlist mold=null)
Chara FindChara (string id)
Chara FindChara (int uid)
int GetDeepestLv ()
int GetDeepestLv (ref int max)
List< Element > ListLandFeats ()
ZoneExportData Import (string path)
void Export (string path, PartialMap partial=null, bool usermap=false)
void ExportDialog (string dir=null)
void ImportDialog (string dir=null)
void Export ()
void WriteNote (UINote n, Action< UINote > onWriteNote=null, IInspect.NoteMode mode=IInspect.NoteMode.Default, Recipe recipe=null)
void OnInspect ()
int GetSortVal ()
Chara AddRandomVisitor (bool guest=false)
void OnSimulateHour (VirtualDate date)
void OnSimulateDay (VirtualDate date)
void OnSimulateMonth (VirtualDate date)
void RainWater ()
void GrowPlants (VirtualDate date)
Zone GetZoneAt (int _x, int _y)
bool IsCrime (Chara c, Act act)
void RefreshCriminal ()
void RefreshListCitizen ()
void ModInfluence (int a)
void ModDevelopment (int a)
void UpdateQuests (bool force=false)
int CountMinions (Chara c)
int GetSoilCost ()
void SpawnLostItems ()
void ApplyBackerPet (bool draw)
Public Member Functions inherited from Spatial
int GetInt (int id, int? defaultInt=null)
void AddInt (int id, int value)
void SetInt (int id, int value=0)
override string ToString ()
void Create (string _id, int _x, int _y, int _icon)
void Register ()
virtual void OnCreate ()
virtual void OnAfterCreate ()
virtual void SetMainFaction (Faction f)
Zone GetFirstZone ()
void OnBeforeSave ()
virtual void _OnBeforeSave ()
void _OnLoad ()
virtual void OnLoad ()
virtual void Destroy ()
void DeleteMapRecursive ()
virtual void AddChild (Spatial child)
void RemoveChild (Spatial child)
Zone FindDeepestZone ()
Zone FindZone (int lv)
Zone FindZone (string _id)
virtual bool CanKill ()
int Dist (Point p)
int Dist (Spatial s)
void MakeGameObject (GameObject parentGo)
ICardParent GetRoot ()
void RemoveCard (Card c)
void OnChildNumChange (Card c)
void WriteNote (UINote n, Action< UINote > onWriteNote=null, IInspect.NoteMode mode=IInspect.NoteMode.Default, Recipe recipe=null)
void OnInspect ()
Static Public Member Functions
static bool IsImportValid (string path)
Static Public Member Functions inherited from EClass
static int rnd (int a)
static int curve (int a, int start, int step, int rate=75)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Public Attributes
FactionBranch branch
HashSet< int > completedQuests = new HashSet<int>()
ZoneEventManager events = new ZoneEventManager()
ElementContainerZone elements = new ElementContainerZone()
MapBounds bounds
Dictionary< int, string > dictCitizen = new Dictionary<int, string>()
ZoneInstance instance
List< int > landFeats
Map map
MapSubset subset
ZoneBlueprint bp
int fileVariation
bool dirtyElectricity
bool isStarted
bool isSimulating
int tempDist
BiomeProfile _biome
Public Attributes inherited from Spatial
Spatial parent
string id
string idUser
string name
string idMainFaction
string idProfile
string idCurrentSubset
string idHat
int[] _ints = new int[30]
List< Spatial > children = new List<Spatial>()
List< Spatial > connections = new List<Spatial>()
Dictionary< int, int > mapInt = new Dictionary<int, int>()
bool destryoed
bool isImported
BitArray32 bits
Static Public Attributes
static bool forceRegenerate
static string forceSubset
static CardRow sourceHat
static int okaerinko = 0
static bool ignoreSpawnAnime
static List< Thing > Suckers = new List<Thing>()
Static Public Attributes inherited from EClass
static Core core
Static Package Functions
static Thing< TryAddThingInSharedContainer > g__SearchDest (ref Zone.<>c__DisplayClass256_0 A_0)
static Point< SpawnLostItems > g__GetPos ()
Properties
Chara Boss [get, set]
override int DangerLv [get]
virtual bool DisableRooms [get]
int HourSinceLastActive [get]
int MinsSinceLastActive [get]
virtual string pathExport [get]
BiomeProfile biome [get]
virtual string IdBiome [get]
virtual string IDGenerator [get]
virtual string TextWidgetDate [get]
MapGenerator Generator [get]
virtual string IdProfile [get]
virtual string IDPlayList [get]
virtual string IDPlaylistOverwrite [get]
virtual string IDHat [get]
virtual string IDBaseLandFeat [get]
virtual string idExport [get]
string pathTemp [get]
Region Region [get]
Zone ParentZone [get]
virtual ActionMode DefaultActionMode [get]
virtual bool BlockBorderExit [get]
virtual int ExpireDays [get]
virtual ZoneTransition.EnterState RegionEnterState [get]
virtual ZoneFeatureType FeatureType [get]
virtual string IDAmbience [get]
virtual string IDSceneTemplate [get]
virtual bool IsFestival [get]
virtual string IDSubset [get]
virtual bool IsTown [get]
virtual bool CanBeDeliverDestination [get]
virtual bool CountDeepestLevel [get]
virtual bool HasLaw [get]
virtual bool MakeEnemiesNeutral [get]
virtual bool MakeTownProperties [get]
virtual bool AllowCriminal [get]
virtual bool AllowNewZone [get]
virtual bool WillAutoSave [get]
virtual bool RegenerateOnEnter [get]
virtual bool IsSkyLevel [get]
virtual bool IsUserZone [get]
virtual bool CanDigUnderground [get]
virtual bool LockExit [get]
virtual bool CanUnlockExit [get]
virtual int MaxLv [get]
virtual int MinLv [get]
virtual bool AddPrefix [get]
virtual bool IsNefia [get]
virtual bool PetFollow [get]
virtual bool RestrictBuild [get]
virtual bool KeepAllyDistance [get]
virtual int MaxSpawn [get]
int MaxRespawn [get]
virtual float RuinChance [get]
virtual float OreChance [get]
virtual float BigDaddyChance [get]
virtual float EvolvedChance [get]
virtual float ShrineChance [get]
virtual float PrespawnRate [get]
virtual float RespawnRate [get]
bool ShowEnemyOnMinimap [get]
virtual int RespawnPerHour [get]
virtual float ChanceSpawnNeutral [get]
virtual bool GrowPlant [get]
virtual bool GrowWeed [get]
virtual bool IsExplorable [get]
virtual bool IsReturnLocation [get]
virtual bool ShouldMakeExit [get]
virtual bool ShouldRegenerate [get]
virtual bool ShouldAutoRevive [get]
virtual bool UseFog [get]
virtual bool RevealRoom [get]
virtual bool AlwaysLowblock [get]
virtual bool UseLight [get]
virtual int StartLV [get]
virtual bool ScaleMonsterLevel [get]
virtual bool HiddenInRegionMap [get]
virtual FlockController.SpawnType FlockType [get]
override string NameSuffix [get]
string NameWithLevel [get]
string TextDeepestLv [get]
bool CanEnterBuildMode [get]
bool CanEnterBuildModeAnywhere [get]
bool IsPCFaction [get]
bool IsStartZone [get]
bool IsInstance [get]
bool IsLoaded [get]
virtual int BaseElectricity [get]
bool IsActiveZone [get]
bool CanInspect [get]
string InspectName [get]
Point InspectPoint [get]
Vector3 InspectPosition [get]
Properties inherited from Spatial
int _bits [get, set]
int uid [get, set]
int icon [get, set]
int x [get, set]
int y [get, set]
int lastActive [get, set]
int idPrefix [get, set]
int lv [get, set]
int visitCount [get, set]
int dateExpire [get, set]
int dateRevive [get, set]
int _dangerLv [get, set]
int dateRegenerate [get, set]
int influence [get, set]
int investment [get, set]
int development [get, set]
int electricity [get, set]
int dateHat [get, set]
int uidBoss [get, set]
int dateQuest [get, set]
int version [get, set]
bool isGenerated [get, set]
bool isShore [get, set]
bool isRandomSite [get, set]
bool isKnown [get, set]
bool isMapSaved [get, set]
bool isExternalZone [get, set]
bool isConquered [get, set]
bool isBeach [get, set]
bool isPeace [get, set]
bool isDeathLocation [get, set]
Faction mainFaction [get, set]
SourceZone.Row source [get]
bool IsPlayerFaction [get]
bool IsClosed [get]
int mapX [get]
int mapY [get]
virtual int DangerLv [get]
virtual int DangerLvFix [get]
virtual float VolumeSea [get]
virtual bool ShowDangerLv [get]
virtual bool CanSpawnAdv [get]
string pathSave [get]
virtual string Name [get]
string NameWithDangerLevel [get]
virtual string NameSuffix [get]
virtual bool IsRegion [get]
virtual bool CanFastTravel [get]
EloMap.TileInfo Tile [get]
virtual bool IsSnowZone [get]
virtual bool IsSnowCovered [get]
virtual Point RegionPos [get]
virtual bool isClaimable [get]
int Seed [get]
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Properties inherited from IInspect
bool CanInspect [get]
string InspectName [get]
Point InspectPoint [get]
Vector3 InspectPosition [get]
Additional Inherited Members
Public Types inherited from IInspect
enum NoteMode { Default , Recipe , Product , Info }
Protected Member Functions inherited from Spatial
Zone _FindZone (string _id)
Protected Attributes inherited from Spatial
Point _regionPos = new Point()
Detailed Description
Definition at line 12 of file Zone.cs.
Member Function Documentation
_OnBeforeSave()
override void Zone._OnBeforeSave () inline virtual
Reimplemented from Spatial.
Definition at line 2139 of file Zone.cs.
    {
        if (this.CanDestroy())
        {
            Debug.Log("Deleting Zone:" + ((this != null) ? this.ToString() : null));
            if (!this.destryoed)
            {
                this.Destroy();
            }
            return;
        }
        if (this.map != null)
        {
            Debug.Log("Saving Zone:" + ((this != null) ? this.ToString() : null));
            this.map.Save(base.pathSave, null, null);
            if (!base.isMapSaved)
            {
                base.isMapSaved = true;
                IO.DeleteDirectory(base.pathSave + "Texture Replace");
                IO.CopyDir(this.pathTemp + "Texture Replace", base.pathSave + "/Texture Replace", null);
            }
            if (!this.IsActiveZone)
            {
                this.UnloadMap();
            }
        }
    }
References CanDestroy(), Destroy(), Spatial.destryoed, IsActiveZone, map, pathTemp, Map.Save(), ToString(), and UnloadMap().
AbandonZone()
void Zone.AbandonZone () inline
Definition at line 2105 of file Zone.cs.
    {
        FactionBranch destBranch = (EClass.pc.homeBranch == this.branch) ? EClass.game.StartZone.branch : EClass.pc.homeBranch;
        this.branch.members.ForeachReverse(delegate(Chara m)
        {
            destBranch.AddMemeber(m);
            if (!m.IsPCParty)
            {
                m.MoveZone(destBranch.owner, ZoneTransition.EnterState.Auto);
            }
        });
        EClass.Branch.OnUnclaimZone();
        this.SetMainFaction(null);
        base.dateExpire = EClass.world.date.GetRaw(0) + 10080;
    }
References FactionBranch.AddMemeber(), EClass.Branch, branch, World.date, EClass.game, Date.GetRaw(), Chara.homeBranch, Chara.IsPCParty, FactionBranch.members, Chara.MoveZone(), FactionBranch.OnUnclaimZone(), FactionBranch.owner, EClass.pc, Spatial.SetMainFaction(), Game.StartZone, and EClass.world.
Referenced by TraitCoreZone.TrySetAct().
Activate()
void Zone.Activate () inline
Definition at line 863 of file Zone.cs.
    {
        if (this.IsRegion)
        {
            EClass.scene.elomapActor.Initialize(this.Region.elomap);
        }
        this.isStarted = (this.isSimulating = false);
        base.isKnown = true;
        EClass.game.config.reverseSnow = false;
        if (this.RegenerateOnEnter && EClass.game.activeZone != null && EClass.game.activeZone.GetTopZone() != this.GetTopZone() && EClass.world.date.IsExpired(base.dateExpire))
        {
            Msg.Say("regenerateZone", this.Name, null, null, null);
            this.ClearZones(null);
            if (EClass.pc.global.transition != null)
            {
                EClass.pc.global.transition.uidLastZone = 0;
            }
        }
        Zone activeZone = EClass.game.activeZone;
        if (EClass.game.activeZone != null)
        {
            EClass.game.activeZone.Deactivate();
        }
        EClass.game.activeZone = this;
        ZoneExportData zoneExportData = null;
        Debug.Log(string.Concat(new string[]
        {
            this.NameWithLevel,
            "/",
            this.id,
            "/",
            base.uid.ToString(),
            "/",
            base.isGenerated.ToString(),
            "/",
            this.IsLoaded.ToString(),
            "/",
            File.Exists(base.pathSave + "map").ToString()
        }));
        if (base.isGenerated && !this.IsLoaded && !File.Exists(base.pathSave + "map"))
        {
            Debug.Log("(Bug) File does not exist:" + this.destryoed.ToString() + "/" + base.pathSave);
            base.isGenerated = false;
        }
        bool flag = false;
        Debug.Log(this.idCurrentSubset + "/" + this.IDSubset);
        bool flag2 = this.idCurrentSubset != this.IDSubset || Zone.forceSubset != null;
        if (flag2 && this.map != null)
        {
            this.UnloadMap();
        }
        Debug.Log(string.Concat(new string[]
        {
            this.idExport,
            "/",
            File.Exists(this.pathExport).ToString(),
            "/",
            this.pathExport
        }));
        if (!base.isGenerated && (this.idExport.IsEmpty() || !File.Exists(this.pathExport)))
        {
            Debug.Log("generating random map");
            flag = true;
            base.dateExpire = EClass.world.date.GetRaw(0) + 1440 * this.ExpireDays;
            this.Generate();
            this.OnGenerateMap();
            if (this.instance != null)
            {
                this.instance.OnGenerateMap();
            }
            if (!this.UseFog)
            {
                this.map.ForeachCell(delegate(global::Cell c)
                {
                    c.isSeen = true;
                });
            }
            if (!(this.bp is GameBlueprint))
            {
                this.AddGlobalCharasOnActivate();
            }
        }
        else if (this.IsLoaded)
        {
            Debug.Log("zone is already loaded");
            this.map.SetZone(this);
            EClass.core.textures.ApplyLocalReplace(base.isMapSaved ? base.pathSave : this.pathTemp);
            this.AddGlobalCharasOnActivate();
        }
        else
        {
            this.subset = null;
            bool flag3 = (base.isGenerated && flag2) || (base.isGenerated && !this.IsInstance && !this.IsPCFaction && this.ShouldRegenerate && EClass.world.date.IsExpired(base.dateRegenerate)) || Zone.forceRegenerate;
            if (this.pathExport.IsEmpty() || !File.Exists(this.pathExport) || EClass.game.isLoading || EClass.player.simulatingZone)
            {
                flag3 = false;
                flag2 = false;
            }
            Debug.Log(string.Concat(new string[]
            {
                base.isGenerated.ToString(),
                "/",
                flag3.ToString(),
                "/",
                flag2.ToString(),
                "/",
                this.IDSubset
            }));
            if (!base.isGenerated || flag3 || flag2)
            {
                Debug.Log("importing map:" + this.pathExport);
                flag = true;
                base.dateRegenerate = EClass.world.date.GetRaw(0) + 1440 * EClass.setting.balance.dateRegenerateZone;
                if (!flag3)
                {
                    IO.DeleteDirectory(this.pathTemp + "Texture Replace");
                    Debug.Log(this.pathTemp);
                }
                zoneExportData = this.Import(this.pathExport);
                base.isGenerated = true;
                this.isImported = true;
                if (flag3)
                {
                    zoneExportData.orgMap = GameIO.LoadFile<Map>(base.pathSave + "map");
                }
            }
            EClass.game.countLoadedMaps++;
            Debug.Log("loading map: imported? " + this.isImported.ToString() + " regenerate? " + flag3.ToString());
            this.map = GameIO.LoadFile<Map>((this.isImported ? this.pathTemp : base.pathSave) + "map");
            if (this.map == null)
            {
                EClass.ui.Say(string.Concat(new string[]
                {
                    "System.IO.EndOfStreamException: Unexpected end of stream:",
                    Environment.NewLine,
                    "File may be corrupted. Try replacing the following file if you have a backup:",
                    Environment.NewLine,
                    this.isImported ? this.pathTemp : base.pathSave,
                    "map"
                }), null);
                return;
            }
            this.map.SetZone(this);
            this.map.Load(this.isImported ? this.pathTemp : base.pathSave, this.isImported, null);
            this.map.SetReference();
            EClass.core.textures.ApplyLocalReplace(base.isMapSaved ? base.pathSave : this.pathTemp);
            if (this.isImported)
            {
                this.map.deadCharas.Clear();
                this.map.OnImport(zoneExportData);
                if (this.UseFog && !flag3)
                {
                    this.map.ForeachCell(delegate(global::Cell c)
                    {
                        c.isSeen = false;
                    });
                }
                if (zoneExportData.orgMap != null)
                {
                    Map orgMap = zoneExportData.orgMap;
                    List<Chara> serializedCharas = this.map.serializedCharas;
                    this.map.charas = orgMap.charas;
                    this.map.serializedCharas = orgMap.serializedCharas;
                    this.map.deadCharas = orgMap.deadCharas;
                    byte[] array = orgMap.TryLoadFile(base.pathSave, "flags", EClass._map.Size * EClass._map.Size);
                    if (array != null && array.Length == EClass._map.Size * EClass._map.Size)
                    {
                        for (int i = 0; i < EClass._map.Size; i++)
{
                            for (int j = 0; j < EClass._map.Size; j++)
{
                                this.map.cells[i, j].isSeen = array[i * EClass._map.Size + j].GetBit(1);
                            }
                        }
                    }
                    foreach (Chara chara in serializedCharas)
                    {
                        string[] array2 = new string[6];
                        array2[0] = "Importing New Chara:";
                        array2[1] = chara.id;
                        array2[2] = "/";
                        array2[3] = chara.Name;
                        array2[4] = "/";
                        int num = 5;
                        Point orgPos = chara.orgPos;
                        array2[num] = ((orgPos != null) ? orgPos.ToString() : null);
                        Debug.Log(string.Concat(array2));
                        this.map.serializedCharas.Add(chara);
                    }
                    this.map.things.ForeachReverse(delegate(Thing t)
                    {
                        if (t.trait is TraitNewZone)
{
                            foreach (Thing thing4 in orgMap.things)
{
                                if (t.id == thing4.id && t.pos.Equals(thing4.pos))
{
                                    this.RemoveCard(t);
                                    this.map.things.Insert(0, thing4);
                                    thing4.stackOrder = 0;
                                    return;
                                }
                            }
                            return;
                        }
                        if (t.trait is TraitStairsLocked)
{
                            foreach (Thing thing5 in orgMap.things)
{
                                if (thing5.trait is TraitNewZone && t.pos.Equals(thing5.pos))
{
                                    this.RemoveCard(t);
                                    this.map.things.Add(thing5);
                                    return;
                                }
                            }
                            return;
                        }
                        if (t.id == "medal" || t.id == "856")
{
                            foreach (Thing thing6 in orgMap.things)
{
                                if (t.id == thing6.id && t.pos.Equals(thing6.pos))
{
                                    return;
                                }
                            }
                            this.RemoveCard(t);
                        }
                    });
                    foreach (KeyValuePair<int, int> keyValuePair in EClass._map.backerObjs.ToList<KeyValuePair<int, int>>())
                    {
                        EClass._map.GetCell(keyValuePair.Key);
                        SourceBacker.Row row = EClass.sources.backers.map[keyValuePair.Value];
                        if (EClass.player.doneBackers.Contains(row.id) && !EClass.core.config.test.ignoreBackerDestoryFlag)
{
                            this.map.backerObjs.Remove(keyValuePair.Key);
                        }
                    }
                    foreach (Chara chara2 in this.map.serializedCharas)
                    {
                        if (chara2.orgPos != null && chara2.orgPos.IsValid)
{
                            chara2.pos.Set(chara2.orgPos);
                        }
                    }
                    foreach (Thing thing in orgMap.things)
                    {
                        if (thing.trait is TraitTent && !thing.isNPCProperty)
{
                            thing.AddEditorTag(EditorTag.NoNpcProperty);
                            thing.isSubsetCard = false;
                            this.map.things.Add(thing);
                            Debug.Log(thing);
                        }
                    }
                }
            }
            foreach (Thing c2 in this.map.things)
            {
                this.map.AddCardOnActivate(c2);
            }
            foreach (Chara chara3 in this.map.serializedCharas)
            {
                this.map.charas.Add(chara3);
                this.map.AddCardOnActivate(chara3);
            }
            this.map.serializedCharas.Clear();
            if (this.isImported && this.IsTown)
            {
                this.RefreshListCitizen();
            }
            this.map.RefreshAllTiles();
            this.AddGlobalCharasOnActivate();
            this.map.OnLoad();
            if (flag3)
            {
                foreach (Card card in this.map.Cards.ToList<Card>())
                {
                    if (card.isSubsetCard)
                    {
                        card.Destroy();
                    }
                }
            }
            if (this.isImported)
            {
                this.idCurrentSubset = (Zone.forceSubset ?? this.IDSubset);
                if (this.idCurrentSubset != null)
                {
                    this.subset = MapSubset.Load(this.idCurrentSubset);
                    this.subset.Apply();
                }
            }
            if (this.isImported)
            {
                if (this.MakeTownProperties)
                {
                    using (List<Thing>.Enumerator enumerator3 = this.map.things.GetEnumerator())
                    {
                        while (enumerator3.MoveNext())
{
                            Thing thing2 = enumerator3.Current;
                            thing2.isNPCProperty = (!thing2.isHidden && !thing2.HasEditorTag(EditorTag.NoNpcProperty));
                        }
                        goto IL_C24;
                    }
                }
                foreach (Thing thing3 in this.map.things)
                {
                    thing3.isNPCProperty = false;
                }
                IL_C24:
                this.OnGenerateMap();
                if (this.instance != null)
                {
                    this.instance.OnGenerateMap();
                }
            }
            if (this.isImported && !flag3 && !this.RevealRoom)
            {
                foreach (global::Room room in this.map.rooms.listRoom)
                {
                    if (room.HasRoof && !room.data.atrium)
                    {
                        foreach (Point point in room.points)
{
                            point.cell.isSeen = false;
                        }
                    }
                }
            }
            if (flag3)
            {
                this.OnRegenerate();
            }
        }
        PathManager.Instance._pathfinder.PunishChangeDirection = false;
        this.isImported = false;
        if (flag && this.IsTown && base.lv == 0)
        {
            this.SpawnLostItems();
        }
        if (base.visitCount == 0)
        {
            base.dateRevive = EClass.world.date.GetRaw(0) + 1440 * EClass.setting.balance.dateRevive;
        }
        this.map.ForeachCell(delegate(global::Cell c)
        {
            if (c.HasFire)
            {
                this.map.effectManager.GetOrCreate(c.GetSharedPoint());
            }
            if (this.IsRegion)
            {
                c.decal = 0;
            }
        });
        if (EClass.world.weather.IsRaining)
        {
            this.RainWater();
        }
        if (EClass.debug.revealMap)
        {
            this.map.ForeachCell(delegate(global::Cell c)
            {
                c.isSeen = true;
            });
        }
        this.isStarted = true;
        this.map.RefreshAllTiles();
        if (this.events.listPreEnter.Count > 0)
        {
            foreach (ZonePreEnterEvent zonePreEnterEvent in this.events.listPreEnter)
            {
                zonePreEnterEvent.Execute();
            }
            this.events.listPreEnter.Clear();
        }
        foreach (Card card2 in this.map.Cards)
        {
            card2.CalculateFOV();
            if (card2.isChara)
            {
                Chara chara4 = card2.Chara;
                if (card2.IsUnique && !card2.IsPCFaction && !card2.IsPCParty)
                {
                    Point point2 = chara4.orgPos ?? card2.pos;
                    card2.c_uniqueData = new UniqueData
                    {
                        x = point2.x,
                        y = point2.z,
                        uidZone = base.uid
                    };
                }
                int @int = card2.GetInt(55, null);
                if (@int != 0)
                {
                    foreach (Chara chara5 in this.map.charas)
                    {
                        if (chara5.uid == @int)
{
                            if (!chara4.IsHostile(chara5))
{
                                break;
                            }
                            chara4.enemy = chara5;
                            chara4.SetAI(new GoalCombat());
                            chara4.calmCheckTurn = 20 + EClass.rnd(30);
                            break;
                        }
                    }
                    card2.SetInt(55, 0);
                }
                if (card2.pos.cell.IsBlocked && !card2.isRestrained && !card2.HasCondition<ConSuspend>())
                {
                    card2.MoveImmediate(card2.pos.GetNearestPoint(false, true, true, false) ?? card2.pos, true, true);
                }
                chara4.SyncRide();
                if (card2.c_uidMaster != 0 && chara4.master == null)
                {
                    chara4.FindMaster();
                }
                if (!EClass.game.isLoading)
                {
                    chara4.enemy = null;
                    if (chara4.IsInCombat)
                    {
                        chara4.SetNoGoal();
                    }
                }
            }
            else if (card2.IsInstalled)
            {
                TraitDoor traitDoor = card2.trait as TraitDoor;
                if (traitDoor != null && card2.pos.HasChara && !traitDoor.IsOpen())
                {
                    traitDoor.ToggleDoor(false, false);
                }
            }
        }
        this.RefreshHat();
        Zone.forceRegenerate = false;
        Zone.forceSubset = null;
        EClass.ui.OnActivateZone();
        EClass.scene.RebuildActorEx();
        EClass.Sound.LoadAmbience(this.IDAmbience);
        if (EClass.Branch != null)
        {
            EClass.Branch.OnActivateZone();
        }
        this.OnVisit();
        if (flag)
        {
            this.OnVisitNewMapOrRegenerate();
        }
        Guild currentGuild = Guild.GetCurrentGuild();
        if (currentGuild != null)
        {
            currentGuild.RefreshDevelopment();
        }
        if (this.IsPCFaction)
        {
            EClass.player.uidLastTown = 0;
        }
        else if (this.IsTown && base.lv == 0)
        {
            EClass.player.uidLastTown = base.uid;
        }
        this.RefreshBGM();
        Rand.InitBytes(this.map.seed + 1);
        this.RefreshElectricity();
        Zone.okaerinko = 0;
        if (EClass.debug.enable)
        {
            this.ModInfluence(2000);
        }
        if (this is Zone_TinkerCamp)
        {
            Tutorial.Reserve("tinker", null);
            return;
        }
        if (this is Zone_Town && !(this is Zone_SubTown))
        {
            Tutorial.Reserve("town", null);
        }
    }
References EClass._map, Game.activeZone, ActPlan.List.Add(), Map.AddCardOnActivate(), Card.AddEditorTag(), AddGlobalCharasOnActivate(), MapSubset.Apply(), Map.backerObjs, SourceManager.backers, GameSetting.balance, bp, EClass.Branch, Card.c_uidMaster, Card.CalculateFOV(), Map.Cards, Point.cell, Map.cells, Card.Chara, Map.charas, ClearZones(), EClass.core, Game.countLoadedMaps, World.date, Deactivate(), Map.deadCharas, EClass.debug, Card.Destroy(), Spatial.destryoed, Player.doneBackers, Region.elomap, Scene.elomapActor, CoreDebug.enable, Point.Equals(), events, ZonePreEnterEvent.Execute(), ExpireDays, Chara.FindMaster(), forceRegenerate, Map.ForeachCell(), EClass.game, Generate(), Map.GetCell(), Guild.GetCurrentGuild(), BaseCard.GetInt(), Point.GetNearestPoint(), Date.GetRaw(), GetTopZone(), Chara.global, Point.HasChara, Card.HasEditorTag(), Card.id, SourceBacker.Row.id, Spatial.id, IDAmbience, Spatial.idCurrentSubset, idExport, IDSubset, Import(), EloMapActor.Initialize(), instance, Cell.IsBlocked, Card.isChara, Date.IsExpired(), Chara.IsHostile(), Spatial.isImported, Chara.IsInCombat, Card.IsInstalled, IsLoaded, Game.isLoading, Card.isNPCProperty, TraitDoor.IsOpen(), Card.IsPCFaction, IsPCFaction, Card.IsPCParty, Weather.IsRaining, Spatial.IsRegion, Card.isRestrained, Cell.isSeen, Card.isSubsetCard, IsTown, Card.IsUnique, Point.IsValid, ZoneEventManager.listPreEnter, RoomManager.listRoom, MapSubset.Load(), Map.Load(), MakeTownProperties, map, Chara.master, ModInfluence(), Card.MoveImmediate(), Card.Name, Spatial.Name, NameWithLevel, FactionBranch.OnActivateZone(), OnGenerateMap(), ZoneInstance.OnGenerateMap(), Map.OnImport(), Map.OnLoad(), OnRegenerate(), OnVisit(), OnVisitNewMapOrRegenerate(), ZoneExportData.orgMap, Chara.orgPos, pathExport, pathTemp, EClass.pc, EClass.player, Card.pos, RainWater(), Scene.RebuildActorEx(), Map.RefreshAllTiles(), RefreshBGM(), Guild.RefreshDevelopment(), RefreshElectricity(), RefreshHat(), RefreshListCitizen(), RegenerateOnEnter, RemoveCard(), Tutorial.Reserve(), CoreDebug.revealMap, RevealRoom, EClass.rnd(), Map.rooms, Msg.Say(), EClass.scene, Map.seed, Map.serializedCharas, Point.Set(), Chara.SetAI(), BaseCard.SetInt(), Chara.SetNoGoal(), Map.SetReference(), EClass.setting, Map.SetZone(), Player.simulatingZone, MapBounds.Size, EClass.Sound, EClass.sources, SpawnLostItems(), subset, Chara.SyncRide(), Card.things, Map.things, TraitDoor.ToggleDoor(), Point.ToString(), ToString(), Card.trait, GlobalData.transition, Map.TryLoadFile(), EClass.ui, Card.uid, UnloadMap(), UseFog, World.weather, EClass.world, Point.x, Spatial.x, Spatial.y, and Point.z.
Referenced by Scene.Init(), and HotItemContext.Show().
AddCard() [1/3]
Card Zone.AddCard (Card t) inline
Definition at line 2270 of file Zone.cs.
    {
        return this.AddCard(t, 0, 0);
    }
References AddCard().
AddCard() [2/3]
Card Zone.AddCard (Card t, int x, int z) inline
Definition at line 2275 of file Zone.cs.
    {
        if (t.parent != null)
        {
            t.parent.RemoveCard(t);
        }
        t.parent = this;
        Chara chara = t.Chara;
        if (chara != null)
        {
            chara.currentZone = this;
            chara.SetAI(new NoGoal());
        }
        if (this.IsActiveZone)
        {
            this.map.OnCardAddedToZone(t, x, z);
            if (this.isStarted && t.isThing && t.placeState == PlaceState.roaming && !Zone.ignoreSpawnAnime)
            {
                t.PlayAnimeLoot();
            }
            Zone.ignoreSpawnAnime = false;
        }
        return t;
    }
References Card.Chara, ignoreSpawnAnime, IsActiveZone, isStarted, Card.isThing, map, Map.OnCardAddedToZone(), Card.parent, Card.placeState, Card.PlayAnimeLoot(), ICardParent.RemoveCard(), Chara.SetAI(), and Spatial.x.
AddCard() [3/3]
Card Zone.AddCard (Card t, Point point) inline
Definition at line 2265 of file Zone.cs.
    {
        return this.AddCard(t, point.x, point.z);
    }
References AddCard(), Point.x, and Point.z.
Referenced by TraitShrine._OnUse(), Game.AddAdventurers(), AddCard(), AddCardSplinkle(), AddChara(), ZoneUtil.AddMerchant(), AddThing(), Chara.ApplyDeathPenalty(), RecipeCard.Build(), Map.Burn(), AI_Shopping.Buy(), ClaimZone(), Card.Die(), Chara.Die(), Chara.DropHeld(), Player.DropReward(), Chara.DropThing(), ZonePreEnterDigStairs.Execute(), ZonePreEnterEncounter.Execute(), DramaOutcome.fiama_pet(), FactionBranch.g__Add(), CoreDebug.g__AddParty(), Zone_Dungeon.g__TryPlaceRail(), Zone_WindRest.g__TryRevive(), Generate(), Zone_SnowGrave.GenerateGrave(), GrowSystem.Grow(), TraitFoodEggFertilized.Incubate(), Chara.MakeGrave(), Chara.MoveHome(), Chara.MoveZone(), Zone_Nymelle.OnBeforeSimulate(), QuestIntroInspector.OnComplete(), QuestVernis.OnComplete(), TaskHarvest.OnCreateProgress(), TaskBuild.OnDestroy(), QuestDialog.OnDropReward(), ZoneEventSiege.OnFirstTick(), Zone_DungeonPuppy.OnGenerateMap(), Zone_TestRoom.OnGenerateMap(), MapGenDungen.OnGenerateTerrain(), GrowSystemTree.OnHitFail(), GenRoom.OnPopulate(), AI_Fish.ProgressFish.OnProgressComplete(), QuestCraft.OnProgressComplete(), TaskMoveInstalled.OnProgressComplete(), TraitDiary.OnRead(), QuestEscort.OnStart(), TraitFarmChest.OnUse(), TraitGiftNewYear.OnUse(), TraitStairsLocked.OnUse(), ZoneEventDefenseGame.OnVisit(), TraitContainer.Open(), ActRestrain.Perform(), HotItemActionSleep.Perform(), GrowSystem.Perish(), Chara.Pick(), Chara.PickOrDrop(), GenRoom.Populate(), ActEffect.Proc(), ActEffect.ProcAt(), FactionBranch.PutInMailBox(), DramaOutcome.PutOutFire(), TaskCraft.PutOutResources(), DramaOutcome.QuestExploration_AfterCrystal(), CoreDebug.QuickStart(), TraitBaseSpellbook.ReadFailEffect(), FactionBranch.Recruit(), Religion.Reforge(), Map.ReloadRoom(), SerializedCards.Restore(), Revive(), Chara.Revive(), AI_UseCrafter.Run(), Meeting.SetChara(), Chara.SetGlobal(), Simulate(), ZoneEventMusic.Spawn(), CoreDebug.Spawn(), SpawnAltar(), SpawnLostItems(), ActThrow.Throw(), TryAddThing(), TryAddThingInSpot< T >(), BiomeProfile.ClusterThing.TryCreate(), Chara.TryDropBossLoot(), TryGenerateBigDaddy(), TryGenerateShrine(), Religion.TryGetGift(), Chara.TryHoldCard(), Chara.TryPutShared(), AI_Shopping.TryRestock(), Map.TryShatter(), Map.TrySmoothPick(), TrySpawnFollower(), DramaOutcome.Tutorial1(), TraitFoodEgg.Update(), CoreDebug.UpdateInput(), Chara.Vomit(), and ActEffect.Wish().
AddCardSplinkle()
Card Zone.AddCardSplinkle (Card t, Point center, int radius = 4) inline
Definition at line 2235 of file Zone.cs.
    {
        Point point = new Point(center);
        for (int i = 0; i < 1000; i++)
        {
            point.x = center.x + EClass.rnd(radius) - EClass.rnd(radius);
            point.z = center.z + EClass.rnd(radius) - EClass.rnd(radius);
            if (point.IsValid && !point.IsBlocked && !point.HasChara)
            {
                return this.AddCard(t, point);
            }
        }
        return this.AddCard(t, center);
    }
References AddCard(), Point.HasChara, Point.IsBlocked, Point.IsValid, and EClass.rnd().
Referenced by ZoneUtil.AddBandits().
AddChara()
Card Zone.AddChara (string id, int x, int z) inline
Definition at line 2250 of file Zone.cs.
    {
        return this.AddCard(CharaGen.Create(id, -1), x, z);
    }
References AddCard(), CharaGen.Create(), and Spatial.x.
Referenced by DramaOutcome.event_swordkeeper(), Zone_Nymelle.OnBeforeSimulate(), DramaOutcome.QuestDefense_0(), and DramaOutcome.QuestDefense_1().
AddGlobalCharasOnActivate()
void Zone.AddGlobalCharasOnActivate () inline
Definition at line 1875 of file Zone.cs.
    {
        Point spawnPosPC = null;
        if (EClass.pc.currentZone == this)
        {
            spawnPosPC = this.GetSpawnPos(EClass.pc, ZoneTransition.EnterState.Auto);
        }
        if (spawnPosPC == null)
        {
            spawnPosPC = this.map.GetCenterPos();
        }
        if (spawnPosPC.IsValid && EClass.pc.global.transition != null && spawnPosPC.HasBlock)
        {
            spawnPosPC = spawnPosPC.GetNearestPoint(false, true, true, false);
        }
        spawnPosPC = spawnPosPC.Clamp(true).GetNearestPoint(false, true, true, false);
        using (Dictionary<int, Chara>.ValueCollection.Enumerator enumerator = EClass.game.cards.globalCharas.Values.GetEnumerator())
        {
            while (enumerator.MoveNext())
            {
                Chara c = enumerator.Current;
                if (c.currentZone == this)
                {
                    if (c.parent is Chara)
                    {
                        Chara chara = c.parent as Chara;
                        c.currentZone = chara.currentZone;
                    }
                    else
                    {
                        c.isRestrained = false;
                        if (!c.isDead)
{
                            if (c.global.transition != null)
{
                                Point pos = c.IsPC ? spawnPosPC : (c.IsPCParty ? spawnPosPC.GetNearestPoint(false, false, true, true) : this.GetSpawnPos(c, ZoneTransition.EnterState.Auto));
                                if (c.IsPCParty && !c.IsPC)
{
                                    if (c.host == EClass.pc)
{
                                        pos.Set(spawnPosPC);
                                    }
                                    else if (pos.Equals(spawnPosPC) || !PathManager.Instance.IsPathClear(spawnPosPC, pos, c, 5))
{
                                        c.pos.Set(spawnPosPC);
                                        if (!spawnPosPC.ForeachNearestPoint(delegate(Point p)
{
                                            if (PathManager.Instance.IsPathClear(spawnPosPC, p, c, 5) && !p.Equals(spawnPosPC))
{
                                                pos.Set(p);
                                                return true;
                                            }
                                            return false;
                                        }, false, EClass.pc.party.members.Count >= 12, true, true))
{
                                            pos.Set(spawnPosPC);
                                        }
                                    }
                                }
                                c.pos.Set(pos);
                                c.global.transition = null;
                            }
                            this.map.charas.Add(c);
                            this.map.AddCardOnActivate(c);
                        }
                    }
                }
            }
        }
        foreach (Chara chara2 in EClass.player.listSummon)
        {
            Point nearestPoint = spawnPosPC.GetNearestPoint(false, false, true, true);
            chara2.enemy = null;
            chara2.pos.Set(nearestPoint);
            this.map.charas.Add(chara2);
            this.map.AddCardOnActivate(chara2);
        }
        EClass.player.listSummon.Clear();
    }
References Map.AddCardOnActivate(), Game.cards, Map.charas, Point.Clamp(), Chara.currentZone, Point.Equals(), Point.ForeachNearestPoint(), EClass.game, MapBounds.GetCenterPos(), Point.GetNearestPoint(), GetSpawnPos(), Chara.global, CardManager.globalCharas, Point.HasBlock, Chara.host, PathManager.Instance, Chara.isDead, PathManager.IsPathClear(), Chara.IsPC, Chara.IsPCParty, Point.IsValid, Player.listSummon, map, Card.parent, EClass.pc, EClass.player, Card.pos, Point.Set(), and GlobalData.transition.
Referenced by Activate().
AddRandomVisitor()
Chara Zone.AddRandomVisitor (bool guest = false) inline
Definition at line 3316 of file Zone.cs.
    {
        Trait random = this.map.Installed.traits.GetTraitSet<TraitSpotExit>().GetRandom();
        if (random == null)
        {
            return null;
        }
        Point point = random.GetPoint();
        Chara chara;
        if (guest)
        {
            Zone z = EClass.world.FindZone("wilds");
            chara = EClass.game.cards.ListGlobalChara(z).RandomItem<Chara>();
            if (chara != null)
            {
                this.AddCard(chara, point);
                Msg.Say("guestArrive", chara, null, null, null);
                chara.visitorState = VisitorState.Arrived;
            }
        }
        else
        {
            chara = CharaGen.CreateFromFilter("c_wilds", -1, -1);
            this.AddCard(chara, point);
            chara.goalListType = GoalListType.Enemy;
        }
        return chara;
    }
References Game.cards, CharaGen.CreateFromFilter(), Spatial.FindZone(), EClass.game, Trait.GetPoint(), guest, CardManager.ListGlobalChara(), Msg.Say(), and EClass.world.
AddThing() [1/2]
Card Zone.AddThing (string id, int x, int z) inline
Definition at line 2255 of file Zone.cs.
    {
        return this.AddCard(ThingGen.Create(id, -1, -1), x, z);
    }
References AddCard(), ThingGen.Create(), and Spatial.x.
Referenced by AddThing(), Zone_SnowGrave.GenerateGrave(), CoreDebug.GetOrCreateDebugContainer(), TaskHarvest.OnCreateProgress(), TaskMine.OnProgressComplete(), DramaOutcome.QuestDefense_0(), DramaOutcome.QuestDefense_1(), and TrySpawnFollower().
AddThing() [2/2]
Card Zone.AddThing (string id, Point p) inline
Definition at line 2260 of file Zone.cs.
    {
        return this.AddThing(id, p.x, p.z);
    }
References AddThing(), Point.x, and Point.z.
ApplyBackerPet()
void Zone.ApplyBackerPet (bool draw) inline
Definition at line 3713 of file Zone.cs.
    {
        bool flag = this is Zone_Yowyn && base.lv == -1;
        IList<SourceBacker.Row> list = EClass.sources.backers.listPet.Copy<SourceBacker.Row>();
        list.Shuffle<SourceBacker.Row>();
        if (!EClass.core.config.test.ignoreBackerDestoryFlag)
        {
            list.ForeachReverse(delegate(SourceBacker.Row a)
            {
                if (EClass.player.doneBackers.Contains(a.id))
                {
                    list.Remove(a);
                }
            });
        }
        foreach (Chara chara in EClass._map.charas)
        {
            if (!chara.IsGlobal && !chara.IsMinion)
            {
                if (chara.isBackerContent)
                {
                    if (chara.sourceBacker.isStatic != 0)
                    {
                        continue;
                    }
                    if (chara.id != "follower")
                    {
                        chara.RemoveBacker();
                    }
                }
                if ((!flag || !(chara.race.id != "cat")) && EClass.rnd(flag ? (draw ? 1 : 2) : (draw ? 3 : 10)) == 0)
                {
                    foreach (SourceBacker.Row row in list)
                    {
                        if (row.chara == chara.id)
{
                            chara.ApplyBacker(row.id);
                            list.Remove(row);
                            break;
                        }
                    }
                }
            }
        }
    }
References EClass._map, Card.ApplyBacker(), SourceManager.backers, Map.charas, EClass.core, Player.doneBackers, Card.id, SourceQuest.Row.id, Card.isBackerContent, Chara.IsGlobal, Chara.IsMinion, SourceBacker.listPet, EClass.player, Chara.race, Card.RemoveBacker(), EClass.rnd(), Card.sourceBacker, and EClass.sources.
CanDestroy()
bool Zone.CanDestroy () inline
Definition at line 2121 of file Zone.cs.
    {
        if (this.IsActiveZone || this.IsPCFaction || EClass.player.simulatingZone)
        {
            return false;
        }
        if (this.IsInstance)
        {
            return true;
        }
        if (base.dateExpire == 0 || !EClass.world.date.IsExpired(base.dateExpire))
        {
            return false;
        }
        Zone topZone = this.GetTopZone();
        return (base.isRandomSite || this is Zone_Field || (topZone != null && topZone != this && topZone.FindDeepestZone() != this)) && EClass.pc.currentZone != null && !(EClass.pc.currentZone is Zone_Tent) && topZone != EClass.pc.currentZone.GetTopZone() && (EClass.player.nextZone == null || topZone != EClass.player.nextZone.GetTopZone());
    }
References Chara.currentZone, World.date, Spatial.FindDeepestZone(), GetTopZone(), IsActiveZone, Date.IsExpired(), IsInstance, IsPCFaction, Player.nextZone, EClass.pc, EClass.player, Player.simulatingZone, and EClass.world.
Referenced by _OnBeforeSave(), and Region.OnActivate().
ClaimZone()
void Zone.ClaimZone (bool debug = false) inline
Definition at line 2048 of file Zone.cs.
    {
        EClass._map.RevealAll(true);
        this.SetMainFaction(EClass.pc.faction);
        this.branch = new FactionBranch();
        this.branch.OnCreate(this);
        if (base.icon == 0)
        {
            base.icon = 332;
        }
        this.instance = null;
        base.dateExpire = 0;
        base.SetInt(2, EClass.world.date.GetRaw(0));
        base.Register();
        foreach (Thing thing in this.map.things)
        {
            thing.isNPCProperty = false;
        }
        EClass.Branch.OnClaimZone();
        EClass.scene.elomap.SetZone(EClass._zone.x, EClass._zone.y, EClass._zone, true);
        if (debug)
        {
            for (int i = 0; i < 7; i++)
            {
                Chara chara = CharaGen.CreateFromFilter("c_neutral", -1, -1);
                EClass._zone.AddCard(chara, EClass._map.bounds.GetRandomPoint().GetNearestPoint(false, false, false, false));
                this.branch.AddMemeber(chara);
            }
        }
        else
        {
            Msg.Say("claimedZone");
            EClass.Branch.Log("claimedZone", null, null, null, null);
            EClass.Sound.Play("jingle_embark");
            EClass.pc.PlaySound("build", 1f, true);
            Effect.Get("aura_heaven").Play(EClass.pc.pos, 0f, null, null);
            Point nearestPoint = EClass.pc.pos.GetNearestPoint(false, true, false, false);
            EClass._zone.AddCard(ThingGen.Create("core_zone", -1, -1), nearestPoint).SetPlaceState(PlaceState.installed, false);
        }
        base.idPrefix = 0;
        if (EClass._zone == EClass.game.StartZone)
        {
            EClass.player.spawnZone = EClass._zone;
        }
        if (EClass._zone != EClass.game.StartZone && !(EClass._zone is Zone_Vernis))
        {
            EClass._zone.SetBGM(new List<int>
            {
                41,
                90,
                44,
                43
            }, true);
            EClass._zone.RefreshPlaylist();
        }
    }
References EClass._map, EClass._zone, AddCard(), FactionBranch.AddMemeber(), Map.bounds, EClass.Branch, branch, ThingGen.Create(), CharaGen.CreateFromFilter(), World.date, EClass.debug, Scene.elomap, Chara.faction, EClass.game, Effect.Get(), Point.GetNearestPoint(), MapBounds.GetRandomPoint(), Date.GetRaw(), FactionBranch.Log(), map, FactionBranch.OnClaimZone(), FactionBranch.OnCreate(), EClass.pc, Effect.Play(), Card.PlaySound(), Card.pos, RefreshPlaylist(), Map.RevealAll(), Msg.Say(), EClass.scene, SetBGM(), Spatial.SetMainFaction(), Card.SetPlaceState(), EloMap.SetZone(), EClass.Sound, Game.StartZone, Map.things, EClass.world, Spatial.x, and Spatial.y.
Referenced by TraitDeed.OnRead(), DramaOutcome.QuestExploration_MeetFarris2(), and CoreDebug.QuickStart().
ClearZones()
void Zone.ClearZones (Zone current = null) inline
Definition at line 2195 of file Zone.cs.
    {
        if (this.map != null)
        {
            this.UnloadMap();
        }
        base.isGenerated = false;
        Zone topZone = this.GetTopZone();
        if (topZone != this)
        {
            topZone.ClearZones(this);
            return;
        }
        this.children.ForeachReverse(delegate(Spatial c)
        {
            if (c != current)
            {
                c.Destroy();
            }
        });
    }
References Spatial.children, ClearZones(), Spatial.Destroy(), GetTopZone(), map, and UnloadMap().
Referenced by Activate(), and ClearZones().
CountMinions()
int Zone.CountMinions (Chara c) inline
Definition at line 3657 of file Zone.cs.
    {
        int num = 0;
        foreach (Chara chara in EClass._map.charas)
        {
            if (chara.c_uidMaster == c.uid && chara.c_minionType == MinionType.Default)
            {
                num++;
            }
        }
        return num;
    }
References EClass._map, Card.c_minionType, Card.c_uidMaster, and Map.charas.
Referenced by Chara.CanBeTempAlly(), ActEffect.ProcAt(), and GoalCombat.TryUseAbility().
CreateBP()
void Zone.CreateBP () inline
Definition at line 2577 of file Zone.cs.
    {
        this.bp = new ZoneBlueprint();
        this.bp.Create();
        this.bp.genSetting.seed = base.Seed;
        this.OnCreateBP();
    }
References bp, ZoneBlueprint.Create(), and OnCreateBP().
Referenced by Generate().
CreatePlaylist()
Playlist Zone.CreatePlaylist (ref List< int > list, Playlist mold = null) inline
Definition at line 3085 of file Zone.cs.
    {
        Playlist playlist = EClass.Sound.plBlank.Instantiate<Playlist>();
        if (list.Count == 0 && mold)
        {
            list = mold.ToInts();
            playlist.shuffle = mold.shuffle;
            playlist.minSwitchTime = mold.minSwitchTime;
            playlist.nextBGMOnSwitch = mold.nextBGMOnSwitch;
            playlist.ignoreLoop = mold.ignoreLoop;
            playlist.keepBGMifSamePlaylist = mold.keepBGMifSamePlaylist;
            playlist.name = mold.name;
        }
        foreach (int key in list)
        {
            playlist.list.Add(new Playlist.Item
            {
                data = EClass.core.refs.dictBGM[key]
            });
        }
        return playlist;
    }
References EClass.core, and EClass.Sound.
Referenced by Generate().
Deactivate()
void Zone.Deactivate () inline
Definition at line 1955 of file Zone.cs.
    {
        if (!this.IsUserZone && !this.IsPCFaction && this.map != null)
        {
            List<Thing> list = new List<Thing>();
            foreach (Thing thing in this.map.things)
            {
                if (thing.rarity >= Rarity.Artifact && thing.HasTag(CTAG.godArtifact))
                {
                    list.Add(thing);
                }
            }
            if (this is Zone_Tent)
            {
                foreach (Thing thing2 in this.map.props.stocked.Things.Concat(this.map.props.roaming.Things))
                {
                    if (thing2.IsContainer)
                    {
                        foreach (Thing thing3 in thing2.things)
{
                            if (thing3.trait is TraitTent)
{
                                list.Add(thing3);
                            }
                        }
                    }
                    if (thing2.trait is TraitTent)
                    {
                        list.Add(thing2);
                    }
                }
            }
            if (list.Count > 0)
            {
                Msg.Say("pick_valuable");
                foreach (Thing thing4 in list)
                {
                    Msg.Say("pick_valuable2", thing4, null, null, null);
                    EClass.pc.AddCard(thing4);
                }
            }
        }
        base.isPeace = false;
        this.OnBeforeDeactivate();
        if (this.IsPCFaction)
        {
            foreach (Chara chara in this.branch.members)
            {
                chara.ValidateWorks();
            }
        }
        EClass.game.lastActiveZone = EClass.game.activeZone;
        base.lastActive = EClass.world.date.GetRaw(0);
        this.map.OnDeactivate();
        EClass.scene.Clear();
        EClass.game.activeZone = null;
        if (this.IsInstance)
        {
            this.UnloadMap();
            base.isGenerated = false;
        }
        if (Zone.forceRegenerate)
        {
            this.UnloadMap();
        }
        this.OnDeactivate();
    }
References Game.activeZone, Card.AddCard(), branch, Scene.Clear(), World.date, forceRegenerate, EClass.game, Date.GetRaw(), Card.HasTag(), Card.IsContainer, IsInstance, IsPCFaction, IsUserZone, map, FactionBranch.members, OnBeforeDeactivate(), Map.OnDeactivate(), OnDeactivate(), EClass.pc, Map.props, Card.rarity, Msg.Say(), EClass.scene, PropsManager.stocked, Card.things, Map.things, Props.Things, Card.trait, UnloadMap(), Chara.ValidateWorks(), and EClass.world.
Referenced by Activate().
Destroy()
override void Zone.Destroy () inline virtual
Reimplemented from Spatial.
Definition at line 2176 of file Zone.cs.
    {
        this.children.ForeachReverse(delegate(Spatial z)
        {
            z.Destroy();
        });
        if (this.map != null)
        {
            this.UnloadMap();
        }
        if (this.parent != null && this.parent.IsRegion && this.instance == null)
        {
            EClass.scene.elomap.SetZone(base.x, base.y, null, true);
        }
        EClass.game.spatials.Remove(this);
        this.destryoed = true;
        base.isGenerated = false;
    }
References Spatial.children, Spatial.Destroy(), Scene.elomap, EClass.game, Spatial.IsRegion, map, Spatial.parent, SpatialManager.Remove(), EClass.scene, EloMap.SetZone(), Game.spatials, and UnloadMap().
Referenced by _OnBeforeSave(), and TraitDeedRelocate.OnRead().
Export() [1/2]
void Zone.Export () inline
Definition at line 3286 of file Zone.cs.
    {
        EClass._map.ResetEditorPos();
        string pathExport = this.pathExport;
        IO.Copy(pathExport, CorePath.ZoneSave + "Backup/");
        this.Export(pathExport, null, false);
        Msg.Say("Exported Map:" + pathExport);
    }
References EClass._map, Map.ResetEditorPos(), and Msg.Say().
Export() [2/2]
void Zone.Export (string path, PartialMap partial = null, bool usermap = false) inline
Definition at line 3199 of file Zone.cs.
    {
        if (this.subset != null)
        {
            SE.Beep();
            return;
        }
        try
        {
            ZoneExportData zoneExportData = new ZoneExportData
            {
                name = this.name,
                usermap = usermap
            };
            IO.CreateTempDirectory(null);
            if (!this.map.config.retainDecal)
            {
                this.map.ClearRainAndDecal();
            }
            this.map.Save(IO.TempPath + "/", zoneExportData, partial);
            this.map.ExportMetaData(IO.TempPath + "/", Path.GetFileNameWithoutExtension(path), partial);
            if (partial == null)
            {
                IO.CopyDir(base.pathSave + "Texture Replace", IO.TempPath + "/Texture Replace", null);
            }
            IO.SaveFile(IO.TempPath + "/export", zoneExportData, true, null);
            using (ZipFile zipFile = new ZipFile())
            {
                zipFile.ExtractExistingFile = ExtractExistingFileAction.OverwriteSilently;
                zipFile.AddDirectory(IO.TempPath);
                zipFile.Save(path);
                zipFile.Dispose();
            }
            IO.DeleteTempDirectory(null);
        }
        catch (Exception ex)
        {
            EClass.ui.Say(ex.Message + ":" + path, null);
        }
    }
References EClass.ui.
Referenced by ZoneInspector.Export(), LayerUploader.ExportMap(), CoreDebug.InitDebugCommands(), and PartialMap.Save().
ExportDialog()
void Zone.ExportDialog (string dir = null) inline
Definition at line 3240 of file Zone.cs.
    {
        EClass.core.WaitForEndOfFrame(delegate
        {
            string text = StandaloneFileBrowser.SaveFilePanel("Export Zone", dir ?? CorePath.ZoneSave, "new zone", "z");
            if (!string.IsNullOrEmpty(text))
            {
                this.Export(text, null, false);
                Msg.SayRaw("Exported Zone");
            }
        });
    }
References EClass.core, Msg.SayRaw(), and text.
Referenced by CoreDebug.InitDebugCommands().
FindChara() [1/2]
Chara Zone.FindChara (int uid) inline
Definition at line 3113 of file Zone.cs.
    {
        return this.map.charas.Find((Chara c) => c.uid == uid);
    }
References Card.uid.
FindChara() [2/2]
Chara Zone.FindChara (string id) inline
Definition at line 3108 of file Zone.cs.
    {
        return this.map.charas.Find((Chara c) => c.id == id);
    }
References Card.id.
g__GetPos()
static Point< SpawnLostItems > Zone.g__GetPos () inline static package
Definition at line 3833 of file Zone.cs.
    {
        for (int i = 0; i < 10; i++)
        {
            Point randomPoint = EClass._zone.bounds.GetRandomPoint();
            if (!randomPoint.IsBlocked && !randomPoint.HasThing && !randomPoint.HasObj && !randomPoint.HasBlock)
            {
                return randomPoint;
            }
        }
        return null;
    }
References EClass._zone, bounds, MapBounds.GetRandomPoint(), Point.HasBlock, Point.HasObj, Point.HasThing, and Point.IsBlocked.
g__SearchDest()
static Thing< TryAddThingInSharedContainer > Zone.g__SearchDest (ref Zone::<>c__DisplayClass256_0 A_0) inline static package
Definition at line 3760 of file Zone.cs.
    {
        foreach (Thing thing in A_0.containers)
        {
            if (thing.trait is TraitShippingChest)
            {
                thing = EClass.game.cards.container_shipping;
            }
            if (!A_0.sharedOnly || thing.IsSharedContainer)
            {
                if (A_0.add)
                {
                    Thing thing2 = thing.things.TryStack(A_0.t.Thing, -1, -1);
                    if (thing2 != A_0.t)
                    {
                        if (A_0.msg)
{
                            A_0.chara.Say("putSharedItem", A_0.chara, thing, thing2.GetName(NameStyle.Full, -1), null);
                        }
                        return thing2;
                    }
                }
                else if (thing.things.CanStack(A_0.t, -1, -1) != A_0.t)
                {
                    return thing;
                }
                if (thing.things.Count < thing.things.MaxCapacity)
                {
                    Window.SaveData windowSaveData = thing.GetWindowSaveData();
                    if (windowSaveData != null)
                    {
                        if (windowSaveData.priority <= A_0.priority || (windowSaveData.noRotten && A_0.t.IsDecayed) || (windowSaveData.onlyRottable && A_0.t.trait.Decay == 0) || (windowSaveData.userFilter && !windowSaveData.IsFilterPass(A_0.t.GetName(NameStyle.Full, 1))))
{
                            continue;
                        }
                        if (windowSaveData.advDistribution)
{
                            bool flag = false;
                            foreach (int num in windowSaveData.cats)
{
                                if (A_0.t.category.uid == num)
{
                                    flag = true;
                                    break;
                                }
                            }
                            if (!flag)
{
                                continue;
                            }
                        }
                        else if (windowSaveData.flag.HasFlag(A_0.flag))
{
                            continue;
                        }
                        A_0.priority = windowSaveData.priority;
                    }
                    else
                    {
                        if (A_0.priority != -1)
{
                            continue;
                        }
                        A_0.priority = 0;
                    }
                    A_0.dest = thing;
                }
            }
        }
        return null;
    }
References ThingContainer.CanStack(), Game.cards, CardManager.container_shipping, EClass.game, Thing.GetName(), Card.GetWindowSaveData(), Thing.IsSharedContainer, ThingContainer.MaxCapacity, Card.Say(), Card.things, Card.trait, and ThingContainer.TryStack().
Referenced by TryAddThingInSharedContainer().
Generate()
void Zone.Generate () inline
Definition at line 2589 of file Zone.cs.
    {
        base.isGenerated = true;
        if (this.bp == null)
        {
            this.CreateBP();
        }
        if (this.bp.map == null)
        {
            this.bp.GenerateMap(this);
        }
        this.map.SetZone(this);
        if (this is Zone_Field)
        {
            if (EClass.rnd(3) == 0)
            {
                int num = EClass.rnd(2);
                for (int i = 0; i < num; i++)
                {
                    Point randomSurface = EClass._map.bounds.GetRandomSurface(false, true, false);
                    if (!randomSurface.HasObj)
                    {
                        Card t = ThingGen.Create("chest3", -1, -1).ChangeMaterial(this.biome.style.matDoor);
                        EClass._zone.AddCard(t, randomSurface).Install();
                    }
                }
            }
            if (EClass.rnd(8) == 0)
            {
                this.SpawnAltar();
            }
            this.TrySpawnFollower();
        }
        this.map.plDay = this.CreatePlaylist(ref this.map._plDay, EClass.Sound.GetPlaylist(this.IDPlayList) ?? EClass.Sound.GetPlaylist("Day"));
    }
References EClass._map, Map._plDay, EClass._zone, AddCard(), biome, Map.bounds, bp, Card.ChangeMaterial(), ThingGen.Create(), CreateBP(), CreatePlaylist(), ZoneBlueprint.GenerateMap(), MapBounds.GetRandomSurface(), Point.HasObj, Card.Install(), map, ZoneBlueprint.map, EClass.rnd(), Map.SetZone(), EClass.Sound, SpawnAltar(), BiomeProfile.style, and TrySpawnFollower().
Referenced by Activate().
GetDeepestLv() [1/2]
int Zone.GetDeepestLv () inline
Definition at line 3118 of file Zone.cs.
    {
        int lv = base.lv;
        return this.GetDeepestLv(ref lv);
    }
Referenced by WindowChara.RefreshProfile().
GetDeepestLv() [2/2]
int Zone.GetDeepestLv (ref int max) inline
Definition at line 3124 of file Zone.cs.
    {
        if (Mathf.Abs(base.lv) > Mathf.Abs(max))
        {
            max = base.lv;
        }
        foreach (Spatial spatial in this.children)
        {
            (spatial as Zone).GetDeepestLv(ref max);
        }
        return max;
    }
GetDungenID()
virtual string Zone.GetDungenID () inline virtual
Reimplemented in Zone_CursedManorDungeon, Zone_Dungeon, and Zone_VernisMine.
Definition at line 91 of file Zone.cs.
    {
        return null;
    }
GetElectricity()
int Zone.GetElectricity (bool cost = false) inline
Definition at line 2976 of file Zone.cs.
    {
        int num = 0;
        foreach (Thing thing in EClass._map.things)
        {
            if (thing.IsInstalled && thing.trait.Electricity != 0)
            {
                if (cost)
                {
                    if (thing.trait.Electricity < 0)
                    {
                        num += -thing.trait.Electricity;
                    }
                }
                else if (thing.trait.Electricity > 0)
                {
                    num += thing.trait.Electricity;
                }
            }
        }
        if (!cost)
        {
            num += this.elements.Value(2201) * 10;
        }
        return num;
    }
References EClass._map, Trait.Electricity, Card.IsInstalled, Map.things, and Card.trait.
Referenced by UIHomeInfo.RefreshInfo().
GetNewZoneID()
virtual string Zone.GetNewZoneID (int level) inline virtual
Reimplemented in Zone_CursedManor, Zone_Nymelle, and Zone_Vernis.
Definition at line 672 of file Zone.cs.
    {
        return base.source.id;
    }
Referenced by TraitNewZone.CreateZone().
GetProfile()
ZoneProfile Zone.GetProfile () inline
Definition at line 2537 of file Zone.cs.
    {
        string text = this.IdProfile;
        if (text.IsEmpty())
        {
            Region region = this.parent as Region;
            if (base.lv != 0)
            {
                text = ((base.lv < 0) ? "Underground" : "Sky");
            }
            else if (region != null)
            {
                EClass.scene.elomapActor.Initialize(region.elomap);
                text = EClass.scene.elomapActor.elomap.GetTileInfo(base.x, base.y).idZoneProfile;
                if (this.bp != null)
                {
                    this.name = Lang.GetList("zone_" + text.Split('/', StringSplitOptions.None)[1]).RandomItem<string>();
                    this.bp.surrounding = new EloMap.TileInfo[3, 3];
                    for (int i = 0; i < 3; i++)
                    {
                        for (int j = 0; j < 3; j++)
{
                            this.bp.surrounding[j, i] = EClass.scene.elomapActor.elomap.GetTileInfo(base.x - 1 + j, base.y - 1 + i);
                        }
                    }
                    if (text == "Random/R_Shore")
                    {
                        base.isBeach = true;
                    }
                }
            }
            else
            {
                text = "Random";
            }
            this.idProfile = text;
        }
        return ZoneProfile.Load(text);
    }
References bp, EloMapActor.elomap, Region.elomap, Scene.elomapActor, EloMap.GetTileInfo(), IdProfile, EloMapActor.Initialize(), ZoneProfile.Load(), Region, EClass.scene, ZoneBlueprint.surrounding, and text.
Referenced by ZoneBlueprint.GenerateMap().
GetRandomSpot< T >()
T Zone.GetRandomSpot< T > () inline
Type Constraints
T : Trait
Definition at line 2321 of file Zone.cs.
                                        : Trait
    {
        return EClass._map.props.installed.traits.GetRandomThing<T>() as T;
    }
References EClass._map, PropsManager.installed, Map.props, and Props.traits.
GetRandomVisitPos()
Point Zone.GetRandomVisitPos (Chara c) inline
Definition at line 1851 of file Zone.cs.
    {
        Point point = null;
        if (EClass.rnd(3) == 0 && this.map.rooms.listRoom.Count > 0)
        {
            point = this.map.rooms.listRoom.RandomItem<global::Room>().points.RandomItem<Point>();
        }
        if (point == null && EClass.rnd(4) != 0)
        {
            IEnumerable<Chara> enumerable = from t in this.map.charas
            where t.trait.ShopType != ShopType.None && t.pos != null && t.pos.IsValid
            select t;
            if (enumerable.Count<Chara>() > 0)
            {
                point = enumerable.RandomItem<Chara>().pos.GetRandomPoint(3, true, true, false, 100);
            }
        }
        if (point == null)
        {
            point = (this.map.bounds.GetRandomSurface(false, true, !this.IsPCFaction && !(this is Zone_Civilized)) ?? this.map.bounds.GetRandomPoint());
        }
        return point.GetNearestPoint(false, false, false, false) ?? EClass._map.GetCenterPos();
    }
References EClass._map, Map.bounds, MapBounds.GetCenterPos(), Point.GetNearestPoint(), MapBounds.GetRandomPoint(), MapBounds.GetRandomSurface(), IsPCFaction, RoomManager.listRoom, map, EClass.rnd(), and Map.rooms.
Referenced by GetSpawnPos().
GetRoot()
ICardParent Zone.GetRoot () inline
Implements ICardParent.
Definition at line 2221 of file Zone.cs.
    {
        return this;
    }
GetSoilCost()
int Zone.GetSoilCost () inline
Definition at line 3670 of file Zone.cs.
    {
        int n = 0;
        EClass._map.bounds.ForeachCell(delegate(global::Cell c)
        {
            n += c.sourceObj.costSoil;
        });
        return n / 10;
    }
References EClass._map, Map.bounds, and MapBounds.ForeachCell().
Referenced by FactionBranch.DailyOutcome(), Map.MineObj(), GrowSystem.PopHarvest(), UIHomeInfo.RefreshInfo(), and GrowSystem.TryPopSeed().
GetSortVal()
int Zone.GetSortVal () inline
Definition at line 3303 of file Zone.cs.
    {
        if (this.IsPCFaction)
        {
            return -100000 + base.uid;
        }
        if (this is Zone_Civilized)
        {
            return -90000 + base.uid;
        }
        return base.uid;
    }
Referenced by SpatialManager.ListReturnLocations().
GetSpawnPos() [1/2]
Point Zone.GetSpawnPos (Chara c, ZoneTransition::EnterState destState = ZoneTransition::EnterState::Auto) inline
Definition at line 1622 of file Zone.cs.
    {
        GlobalData global = c.global;
        ZoneTransition zoneTransition = (global != null) ? global.transition : null;
        Zone zone = (zoneTransition != null) ? zoneTransition.lastZone : null;
        ZoneTransition.EnterState enterState = (zoneTransition != null) ? zoneTransition.state : destState;
        bool flag = zone == null || zone.lv > base.lv;
        if (this.IsRegion)
        {
            if (zone != null && !EClass.player.simulatingZone)
            {
                Zone topZone = zone.GetTopZone();
                if (this.GetZoneAt(topZone.x, topZone.y) != null)
                {
                    return new Point(topZone.mapX, topZone.mapY);
                }
            }
        }
        else if (c.IsPC && EClass.player.lastZonePos != null && zone != null && zone.IsRegion && (enterState == ZoneTransition.EnterState.Left || enterState == ZoneTransition.EnterState.Right || enterState == ZoneTransition.EnterState.Top || enterState == ZoneTransition.EnterState.Bottom))
        {
            return EClass.player.lastZonePos;
        }
        if (enterState == ZoneTransition.EnterState.Region)
        {
            enterState = this.RegionEnterState;
        }
        if (this is Zone_Kapul && enterState == ZoneTransition.EnterState.Left)
        {
            enterState = ZoneTransition.EnterState.Right;
        }
        float rate = (zoneTransition == null) ? -1f : zoneTransition.ratePos;
        if (this.IsPCFaction)
        {
            if (enterState - ZoneTransition.EnterState.Dir <= 4 || enterState == ZoneTransition.EnterState.Return)
            {
                Thing spot = EClass._map.props.installed.Find<TraitSpotGuidePC>();
                if (spot != null)
                {
                    Point nearestPoint = (spot.trait as TraitSpotGuidePC).GetRandomPoint((Point p) => !p.IsBlocked && !p.Equals(spot.pos), null).GetNearestPoint(false, true, true, false);
                    if (nearestPoint != null && nearestPoint.IsValid)
                    {
                        return nearestPoint;
                    }
                }
            }
        }
        Thing randomThing;
        Thing randomThing2;
        Thing randomThing3;
        for (;;)
        {
            switch (enterState)
            {
            case ZoneTransition.EnterState.Center:
            case ZoneTransition.EnterState.Encounter:
                goto IL_4B7;
            case ZoneTransition.EnterState.Top:
                goto IL_504;
            case ZoneTransition.EnterState.Right:
                goto IL_520;
            case ZoneTransition.EnterState.Bottom:
                goto IL_53C;
            case ZoneTransition.EnterState.Left:
                goto IL_558;
            case ZoneTransition.EnterState.Dead:
            case ZoneTransition.EnterState.Exact:
            case ZoneTransition.EnterState.PortalReturn:
            case ZoneTransition.EnterState.Fall:
                goto IL_574;
            case ZoneTransition.EnterState.RandomVisit:
                goto IL_5C5;
            case ZoneTransition.EnterState.Down:
                goto IL_5CD;
            case ZoneTransition.EnterState.Up:
                goto IL_5D1;
            case ZoneTransition.EnterState.Return:
            case ZoneTransition.EnterState.Teleport:
            case ZoneTransition.EnterState.Elevator:
            case ZoneTransition.EnterState.Moongate:
                if (enterState == ZoneTransition.EnterState.Teleport)
                {
                    foreach (Thing thing in this.map.things)
                    {
                        if (thing.IsInstalled)
{
                            TraitTeleporter traitTeleporter = thing.trait as TraitTeleporter;
                            if (traitTeleporter != null)
{
                                Debug.Log(string.Concat(new string[]
{
                                    zoneTransition.idTele,
                                    "/",
                                    traitTeleporter.id.IsEmpty(traitTeleporter.GetParam(3, null)),
                                    "/",
                                    traitTeleporter.GetParam(3, null)
                                }));
                            }
                            if (traitTeleporter != null && !zoneTransition.idTele.IsEmpty() && zoneTransition.idTele == traitTeleporter.id.IsEmpty(traitTeleporter.GetParam(3, null)))
{
                                return thing.pos.GetNearestPoint(false, true, true, false);
                            }
                        }
                    }
                    foreach (Thing thing2 in this.map.things)
                    {
                        if (thing2.IsInstalled)
{
                            TraitTeleporter traitTeleporter2 = thing2.trait as TraitTeleporter;
                            if (traitTeleporter2 != null && traitTeleporter2.IsFor(zoneTransition.lastZone))
{
                                return thing2.pos.GetNearestPoint(false, true, true, false);
                            }
                        }
                    }
                    randomThing = EClass._map.props.installed.traits.GetRandomThing<TraitTeleporter>();
                    if (randomThing != null)
                    {
                        goto Block_29;
                    }
                }
                if (enterState == ZoneTransition.EnterState.Elevator)
                {
                    foreach (Thing thing3 in this.map.things)
                    {
                        if (thing3.IsInstalled)
{
                            TraitElevator traitElevator = thing3.trait as TraitElevator;
                            if (traitElevator != null && traitElevator.IsFor(zoneTransition.lastZone))
{
                                return thing3.pos.GetNearestPoint(false, true, true, false);
                            }
                        }
                    }
                    randomThing2 = EClass._map.props.installed.traits.GetRandomThing<TraitElevator>();
                    if (randomThing2 != null)
                    {
                        goto Block_32;
                    }
                }
                randomThing3 = this.map.props.installed.traits.GetRandomThing<TraitWaystone>();
                if (randomThing3 != null)
                {
                    goto Block_33;
                }
                randomThing3 = this.map.props.installed.traits.GetRandomThing<TraitCoreZone>();
                if (randomThing3 != null)
                {
                    goto Block_34;
                }
                if (base.lv == 0)
                {
                    enterState = ZoneTransition.EnterState.Center;
                    continue;
                }
                goto IL_4A0;
            case ZoneTransition.EnterState.UndergroundOrSky:
                goto IL_1CB;
            }
            break;
        }
        goto IL_5D3;
        IL_1CB:
        return new Point(zoneTransition.x, zoneTransition.z);
        Block_29:
        return randomThing.pos.GetNearestPoint(false, true, true, false);
        Block_32:
        return randomThing2.pos.GetNearestPoint(false, true, true, false);
        Block_33:
        return randomThing3.pos.GetNearestPoint(false, true, true, false);
        Block_34:
        return randomThing3.pos.GetNearestPoint(false, true, true, false);
        IL_4A0:
        flag = (base.lv <= 0);
        goto IL_5D3;
        IL_4B7:
        if (this.map.config.embarkX != 0)
        {
            return new Point(this.map.config.embarkX, this.map.config.embarkY);
        }
        return this.map.GetCenterPos().GetNearestPoint(false, false, true, false);
        IL_504:
        return this.map.bounds.GetTopPos(rate).GetNearestPoint(false, false, true, false);
        IL_520:
        return this.map.bounds.GetRightPos(rate).GetNearestPoint(false, false, true, false);
        IL_53C:
        return this.map.bounds.GetBottomPos(rate).GetNearestPoint(false, false, true, false);
        IL_558:
        return this.map.bounds.GetLeftPos(rate).GetNearestPoint(false, false, true, false);
        IL_574:
        if (zoneTransition.x == 0 && EClass._map.bounds.x != 0)
        {
            return new Point(this.map.config.embarkX, this.map.config.embarkY);
        }
        return new Point(zoneTransition.x, zoneTransition.z);
        IL_5C5:
        return this.GetRandomVisitPos(c);
        IL_5CD:
        flag = true;
        goto IL_5D3;
        IL_5D1:
        flag = false;
        IL_5D3:
        foreach (Thing thing4 in this.map.things)
        {
            TraitNewZone traitNewZone = thing4.trait as TraitNewZone;
            if (traitNewZone != null && traitNewZone.zone != null && zone != null && traitNewZone.zone.uid == zone.uid)
            {
                if (c != null && enterState != ZoneTransition.EnterState.Auto)
                {
                    c.SetDir(traitNewZone.owner.dir);
                }
                return traitNewZone.GetExitPos();
            }
        }
        foreach (Thing thing5 in this.map.things)
        {
            TraitNewZone traitNewZone2 = thing5.trait as TraitNewZone;
            if (traitNewZone2 != null && ((flag && traitNewZone2.IsUpstairs) || (!flag && traitNewZone2.IsDownstairs)))
            {
                if (c != null && enterState != ZoneTransition.EnterState.Auto)
                {
                    c.SetDir(traitNewZone2.owner.dir);
                }
                return traitNewZone2.GetExitPos();
            }
        }
        return this.GetRandomVisitPos(c);
    }
References EClass._map, Map.bounds, Map.config, Card.dir, MapConfig.embarkX, Point.Equals(), Props.Find(), MapBounds.GetBottomPos(), MapBounds.GetCenterPos(), TraitNewZone.GetExitPos(), MapBounds.GetLeftPos(), Point.GetNearestPoint(), Trait.GetParam(), GetRandomVisitPos(), MapBounds.GetRightPos(), MapBounds.GetTopPos(), GetTopZone(), GetZoneAt(), Chara.global, TraitTeleporter.id, ZoneTransition.idTele, PropsManager.installed, TraitNewZone.IsDownstairs, TraitNewZone.IsFor(), Card.IsInstalled, Chara.IsPC, IsPCFaction, Spatial.IsRegion, TraitNewZone.IsUpstairs, Point.IsValid, ZoneTransition.lastZone, Player.lastZonePos, map, Spatial.mapX, Spatial.mapY, Trait.owner, EClass.player, Card.pos, Map.props, ZoneTransition.ratePos, RegionEnterState, Player.simulatingZone, ZoneTransition.state, Map.things, Props.traits, GlobalData.transition, Spatial.uid, MapBounds.x, Spatial.x, ZoneTransition.x, Spatial.y, ZoneTransition.z, and TraitNewZone.zone.
Referenced by AddGlobalCharasOnActivate(), Chara.MoveZone(), Scene.OnUpdate(), and Revive().
GetSpawnPos() [2/2]
Point Zone.GetSpawnPos (SpawnPosition type, int tries = 100) inline
Definition at line 2845 of file Zone.cs.
    {
        Point point = new Point();
        for (int i = 0; i < tries; i++)
        {
            point = EClass._map.bounds.GetRandomSurface(false, true, true);
            if (point.IsValid && !point.cell.hasDoor && !point.IsSync && (type != SpawnPosition.Outside || (!point.cell.HasRoof && point.cell.light <= 0)))
            {
                return point;
            }
        }
        return null;
    }
References EClass._map, Map.bounds, Point.cell, MapBounds.GetRandomSurface(), Cell.hasDoor, Cell.HasRoof, Point.IsSync, Point.IsValid, and Cell.light.
GetTopZone()
Zone Zone.GetTopZone () inline
Definition at line 2226 of file Zone.cs.
    {
        if (this.parent == null || this.parent.IsRegion)
        {
            return this;
        }
        return this.parent as Zone;
    }
References Spatial.IsRegion, and Spatial.parent.
Referenced by Activate(), CanDestroy(), ClearZones(), SpatialGen.CreateInstance(), Chara.FallFromZone(), GetSpawnPos(), SpatialManager.ListReturnLocations(), TraitNewZone.MoveZone(), Chara.MoveZone(), OnAfterCreate(), QuestRandom.OnDropReward(), MapGen.OnGenerateTerrain(), TraitTicketFurniture.SetZone(), Simulate(), Chara.TryDropBossLoot(), TraitElevator.TrySetAct(), and TraitTicketFurniture.TrySetHeldAct().
GetZoneAt()
Zone Zone.GetZoneAt (int _x, int _y) inline
Definition at line 3478 of file Zone.cs.
    {
        if (this.IsRegion)
        {
            foreach (Spatial spatial in this.children)
            {
                if (!(spatial is Zone_Field) && _x == spatial.x && _y == spatial.y)
                {
                    return spatial as Zone;
                }
            }
        }
        foreach (Spatial spatial2 in this.children)
        {
            if (_x == spatial2.x && _y == spatial2.y)
            {
                return spatial2 as Zone;
            }
        }
        return null;
    }
References Spatial.x, and Spatial.y.
Referenced by Player.EnterLocalZone(), GetSpawnPos(), and RegionPoint.SetRegionPoint().
GrowPlants()
void Zone.GrowPlants (VirtualDate date) inline
Definition at line 3438 of file Zone.cs.
    {
        Zone.<>c__DisplayClass302_0 CS$<>8__locals1 = new Zone.<>c__DisplayClass302_0();
        CS$<>8__locals1.date = date;
        CS$<>8__locals1.<>4__this = this;
        bool flag = EClass.player.isAutoFarming = (this.IsPCFaction && EClass.Branch.policies.IsActive(2707, -1));
        CS$<>8__locals1.weedChance = 1;
        if (this.IsPCFaction && EClass.Branch.policies.IsActive(2703, -1))
        {
            CS$<>8__locals1.weedChance += (EClass.debug.enable ? 100000 : 20) + EClass.Branch.Evalue(2703) * 10;
        }
        if (CS$<>8__locals1.date.sunMap == null)
        {
            CS$<>8__locals1.date.BuildSunMap();
        }
        if (flag)
        {
            HashSet<int> hashSet = new HashSet<int>();
            foreach (Thing thing in EClass._map.things)
            {
                if (thing.IsInstalled)
                {
                    TraitSpotFarm traitSpotFarm = thing.trait as TraitSpotFarm;
                    if (traitSpotFarm != null)
                    {
                        foreach (Point point in traitSpotFarm.ListPoints(null, false))
{
                            hashSet.Add(point.index);
                        }
                    }
                }
            }
            CS$<>8__locals1.<GrowPlants>g__Perform|0(hashSet);
            EClass.player.isAutoFarming = false;
            CS$<>8__locals1.<GrowPlants>g__Perform|0(hashSet);
            return;
        }
        CS$<>8__locals1.<GrowPlants>g__Perform|0(null);
    }
References EClass._map, EClass.Branch, FactionBranch.Evalue(), Point.index, PolicyManager.IsActive(), Card.IsInstalled, Trait.ListPoints(), FactionBranch.policies, and Map.things.
Import()
ZoneExportData Zone.Import (string path) inline
Definition at line 3190 of file Zone.cs.
    {
        ZipFile zipFile = ZipFile.Read(path);
        zipFile.ExtractExistingFile = ExtractExistingFileAction.OverwriteSilently;
        zipFile.ExtractAll(this.pathTemp);
        zipFile.Dispose();
        return IO.LoadFile<ZoneExportData>(this.pathTemp + "export", false, null) ?? new ZoneExportData();
    }
Referenced by Activate(), and PartialMap.Load().
ImportDialog()
void Zone.ImportDialog (string dir = null) inline
Definition at line 3253 of file Zone.cs.
    {
        EClass.core.WaitForEndOfFrame(delegate
        {
            string[] array = StandaloneFileBrowser.OpenFilePanel("Import Zone", dir ?? CorePath.ZoneSave, "z", false);
            if (array.Length != 0)
            {
                Zone_User zone_User = SpatialGen.Create("user", EClass.world.region, true, -99999, -99999, 0) as Zone_User;
                zone_User.path = array[0];
                Thing thing = ThingGen.Create("teleporter", -1, -1);
                thing.c_uidZone = zone_User.uid;
                EClass._zone.AddCard(thing, EClass.pc.pos);
                return;
            }
        });
    }
References EClass.core.
Referenced by CoreDebug.InitDebugCommands().
IsCrime()
bool Zone.IsCrime (Chara c, Act act) inline
Definition at line 3500 of file Zone.cs.
    {
        return act.IsHostileAct && this.HasLaw && !this.IsPCFaction && c.IsPC;
    }
References Chara.IsPC.
Referenced by TaskDig.OnCreateProgress(), TaskHarvest.OnCreateProgress(), TaskMine.OnCreateProgress(), TaskDig.OnProgressComplete(), TaskMine.OnProgressComplete(), ActPlan.Item.Perform(), HotItemAct.TrySetAct(), and TraitCatalyst.TrySetHeldAct().
IsImportValid()
static bool Zone.IsImportValid (string path) inline static
Definition at line 3270 of file Zone.cs.
    {
        bool result;
        try
        {
            MapMetaData metaData = Map.GetMetaData(path);
            result = (metaData != null && metaData.IsValidVersion());
        }
        catch (Exception ex)
        {
            EClass.ui.Say(ex.Message, null);
            result = false;
        }
        return result;
    }
References Map.GetMetaData(), MapMetaData.IsValidVersion(), and EClass.ui.
ListLandFeats()
List< Element > Zone.ListLandFeats () inline
Definition at line 3137 of file Zone.cs.
    {
        if (this.landFeats == null)
        {
            this.landFeats = new List<int>();
            Rand.SetSeed(EClass._zone.uid);
            string[] listBase = this.IDBaseLandFeat.Split(',', StringSplitOptions.None);
            foreach (string text in listBase)
            {
                if (!text.IsEmpty())
                {
                    this.landFeats.Add(EClass.sources.elements.alias[text].id);
                }
            }
            if (listBase.Length == 1)
            {
                List<SourceElement.Row> list = EClass.sources.elements.rows.Where(delegate(SourceElement.Row e)
                {
                    if (e.category != "landfeat" || e.chance == 0)
                    {
                        return false;
                    }
                    bool result = true;
                    foreach (string text2 in e.tag)
                    {
                        if (text2.StartsWith("bf"))
{
                            result = false;
                            if (listBase[0] == text2)
{
                                result = true;
                                break;
                            }
                        }
                    }
                    return result;
                }).ToList<SourceElement.Row>();
                SourceElement.Row row = list.RandomItemWeighted((SourceElement.Row e) => (float)e.chance);
                this.landFeats.Add(row.id);
                list.Remove(row);
                row = list.RandomItemWeighted((SourceElement.Row e) => (float)e.chance);
                this.landFeats.Add(row.id);
            }
            Rand.SetSeed(-1);
        }
        List<Element> list2 = new List<Element>();
        foreach (int id in this.landFeats)
        {
            list2.Add(Element.Create(id, 0));
        }
        return list2;
    }
References EClass._zone, SourceManager.elements, SourceElement.Row.id, EClass.sources, text, and Spatial.uid.
Referenced by WidgetDate._Refresh(), FactionBranch.OnClaimZone(), and UIFactionInfo.SetZone().
ModDevelopment()
void Zone.ModDevelopment (int a) inline
Definition at line 3548 of file Zone.cs.
    {
        base.development += a;
        if (a > 0)
        {
            Msg.Say("gainDevelopment", this.Name, a.ToString() ?? "", null, null);
        }
    }
References Msg.Say().
ModInfluence()
void Zone.ModInfluence (int a) inline
Definition at line 3538 of file Zone.cs.
    {
        base.influence += a;
        if (a > 0)
        {
            Msg.Say("gainInfluence", this.Name, a.ToString() ?? "", null, null);
        }
        Tutorial.Reserve("influence", null);
    }
References Tutorial.Reserve(), and Msg.Say().
Referenced by Activate(), Card.ModCurrency(), QuestRandom.OnDropReward(), and ActThrow.Throw().
OnActivate()
virtual void Zone.OnActivate () inline virtual
Reimplemented in Region, Zone_Casino, Zone_LumiestRuin, Zone_Olvina, and Zone_SisterHouse.
Definition at line 1441 of file Zone.cs.
    {
    }
Referenced by OnVisit().
OnAdvanceHour()
virtual void Zone.OnAdvanceHour () inline virtual
Reimplemented in Region.
Definition at line 1465 of file Zone.cs.
    {
    }
Referenced by GameDate.AdvanceHour().
OnAfterCreate()
override void Zone.OnAfterCreate () inline virtual
Reimplemented from Spatial.
Definition at line 850 of file Zone.cs.
    {
        if (this.AddPrefix)
        {
            if (this.GetTopZone() == this)
            {
                base.idPrefix = EClass.sources.zoneAffixes.rows.RandomItem<SourceZoneAffix.Row>().id;
                return;
            }
            base.idPrefix = this.GetTopZone().idPrefix;
        }
    }
References AddPrefix, GetTopZone(), Spatial.idPrefix, EClass.sources, and SourceManager.zoneAffixes.
OnAfterSimulate()
virtual void Zone.OnAfterSimulate () inline virtual
Reimplemented in Zone_WindRest.
Definition at line 1461 of file Zone.cs.
    {
    }
Referenced by OnVisit().
OnBeforeDeactivate()
virtual void Zone.OnBeforeDeactivate () inline virtual
Reimplemented in Zone_Tent.
Definition at line 1445 of file Zone.cs.
    {
    }
Referenced by Deactivate().
OnBeforeSimulate()
virtual void Zone.OnBeforeSimulate () inline virtual
Reimplemented in Zone_DungeonPuppy, and Zone_Nymelle.
Definition at line 1453 of file Zone.cs.
    {
    }
Referenced by OnVisit().
OnChildNumChange()
void Zone.OnChildNumChange (Card c) inline
Implements ICardParent.
Definition at line 2217 of file Zone.cs.
    {
    }
OnCreate()
override void Zone.OnCreate () inline virtual
Reimplemented from Spatial.
Definition at line 844 of file Zone.cs.
    {
        this.events.zone = this;
        base.lv = this.StartLV;
    }
References StartLV.
OnCreateBP()
virtual void Zone.OnCreateBP () inline virtual
Reimplemented in Zone_Arena2, and Zone_Harvest.
Definition at line 2585 of file Zone.cs.
    {
    }
Referenced by CreateBP().
OnDeactivate()
virtual void Zone.OnDeactivate () inline virtual
Definition at line 1449 of file Zone.cs.
    {
    }
Referenced by Deactivate().
OnGenerateMap()
virtual void Zone.OnGenerateMap () inline virtual
Reimplemented in Zone_Arena2, Zone_CursedManor, Zone_CursedManorDungeon, Zone_Dungeon, Zone_DungeonPuppy, Zone_Field, Zone_Harvest, Zone_RandomDungeon, Zone_RandomDungeonFactory, Zone_SnowGrave, Zone_TestRoom, Zone_VernisMine, Zone_Void, and Zone_WindRest.
Definition at line 2700 of file Zone.cs.
    {
        if (this.MakeEnemiesNeutral)
        {
            foreach (Chara chara in EClass._map.charas)
            {
                if (!chara.IsGlobal && chara.hostility < Hostility.Neutral && chara.OriginalHostility < Hostility.Friend)
                {
                    chara.hostility = (chara.c_originalHostility = Hostility.Neutral);
                }
            }
        }
        if (this.PrespawnRate != 0f && !this.IsSkyLevel)
        {
            for (int i = 0; i < (int)((float)this.MaxSpawn * this.PrespawnRate); i++)
            {
                this.SpawnMob(null, null);
            }
        }
        this.TryGenerateOre();
        this.TryGenerateBigDaddy();
        this.TryGenerateEvolved(false, null);
        this.TryGenerateShrine();
    }
References EClass._map, Map.charas, Chara.hostility, Chara.IsGlobal, and Chara.OriginalHostility.
Referenced by Activate().
OnGenerateRooms()
virtual void Zone.OnGenerateRooms (BaseMapGen gen) inline virtual
Reimplemented in Zone_CaveMonster, and Zone_SubTown.
Definition at line 2841 of file Zone.cs.
    {
    }
Referenced by MapGenDungen.OnGenerateTerrain().
OnInspect()
void Zone.OnInspect () inline
Implements IInspect.
Definition at line 3299 of file Zone.cs.
    {
    }
OnKillGame()
void Zone.OnKillGame () inline
Definition at line 2023 of file Zone.cs.
    {
        foreach (Thing thing in this.map.things)
        {
            if (thing.renderer.hasActor)
            {
                thing.renderer.KillActor();
            }
        }
    }
References CardRenderer.hasActor, CardRenderer.KillActor(), map, Card.renderer, and Map.things.
OnLoad()
override void Zone.OnLoad () inline virtual
Reimplemented from Spatial.
Definition at line 2167 of file Zone.cs.
    {
        if (this.branch != null)
        {
            this.branch.SetOwner(this);
        }
        this.events.OnLoad(this);
    }
References branch, events, ZoneEventManager.OnLoad(), and FactionBranch.SetOwner().
OnRegenerate()
virtual void Zone.OnRegenerate () inline virtual
Reimplemented in Zone_LittleGarden.
Definition at line 1437 of file Zone.cs.
    {
    }
Referenced by Activate().
OnSimulateDay()
void Zone.OnSimulateDay (VirtualDate date) inline
Definition at line 3403 of file Zone.cs.
    {
        if (base.IsPlayerFaction)
        {
            this.branch.OnSimulateDay(date);
        }
    }
Referenced by VirtualDate.SimulateDay().
OnSimulateHour()
void Zone.OnSimulateHour (VirtualDate date) inline
Definition at line 3345 of file Zone.cs.
    {
        if (base.IsPlayerFaction)
        {
            this.branch.OnSimulateHour(date);
        }
        this.events.OnSimulateHour();
        if (date.IsRealTime)
        {
            foreach (Thing thing in EClass._map.things)
            {
                if (thing.IsInstalled)
                {
                    thing.trait.TryToggle();
                }
            }
            EClass.pc.DecayNatural(1);
        }
        EClass._map.things.ForeachReverse(delegate(Thing t)
        {
            t.OnSimulateHour(date);
        });
        foreach (Thing thing2 in Zone.Suckers)
        {
            thing2.Destroy();
        }
        Zone.Suckers.Clear();
        if (this.RespawnRate != 0f)
        {
            int num = 0;
            using (List<Chara>.Enumerator enumerator2 = this.map.charas.GetEnumerator())
            {
                while (enumerator2.MoveNext())
                {
                    if (!enumerator2.Current.IsGlobal)
                    {
                        num++;
                    }
                }
            }
            if (num < this.MaxRespawn)
            {
                for (int i = 0; i < this.RespawnPerHour; i++)
                {
                    this.SpawnMob(null, null);
                }
            }
        }
        if (!date.IsRealTime && EClass.rnd(24) == 0)
        {
            this.RainWater();
        }
        if (date.hour == 6)
        {
            this.GrowPlants(date);
        }
    }
References EClass._map, Card.DecayNatural(), Card.Destroy(), Card.IsInstalled, VirtualDate.IsRealTime, Card.OnSimulateHour(), EClass.pc, EClass.rnd(), Suckers, Map.things, Card.trait, and Trait.TryToggle().
Referenced by VirtualDate.SimulateHour().
OnSimulateMonth()
void Zone.OnSimulateMonth (VirtualDate date) inline
Definition at line 3411 of file Zone.cs.
    {
        if (base.IsPlayerFaction)
        {
            this.branch.OnSimulateMonth(date);
        }
        if (date.IsRealTime)
        {
            EClass._map.RefreshAllTiles();
        }
    }
References EClass._map, VirtualDate.IsRealTime, and Map.RefreshAllTiles().
Referenced by VirtualDate.SimulateMonth().
OnVisit()
void Zone.OnVisit () inline
Definition at line 1361 of file Zone.cs.
    {
        if (this.CountDeepestLevel && this.DangerLv > EClass.player.stats.deepest)
        {
            EClass.player.stats.deepest = this.DangerLv;
        }
        if (EClass.world.date.IsExpired(base.dateRevive))
        {
            this.ResetHostility();
            this.Revive();
            foreach (Chara chara in EClass._map.charas)
            {
                chara.TryRestock(false);
                if (!chara.IsPCFaction)
                {
                    chara.c_fur = 0;
                }
            }
        }
        this.RefreshCriminal();
        EClass._map.rooms.AssignCharas();
        this.events.OnVisit();
        this.OnActivate();
        this.UpdateQuests(false);
        this.OnBeforeSimulate();
        this.isSimulating = true;
        this.Simulate();
        this.isSimulating = false;
        this.OnAfterSimulate();
        if (EClass.Branch != null)
        {
            EClass.Branch.OnAfterSimulate();
        }
        base.lastActive = EClass.world.date.GetRaw(0);
        if (!EClass.game.isLoading)
        {
            int visitCount = base.visitCount;
            base.visitCount = visitCount + 1;
        }
        base.version = EClass.core.version.GetInt();
    }
References EClass._map, RoomManager.AssignCharas(), EClass.Branch, Map.charas, EClass.core, CountDeepestLevel, DangerLv, World.date, events, EClass.game, Date.GetRaw(), Date.IsExpired(), Game.isLoading, Chara.IsPCFaction, OnActivate(), FactionBranch.OnAfterSimulate(), OnAfterSimulate(), OnBeforeSimulate(), ZoneEventManager.OnVisit(), EClass.player, RefreshCriminal(), ResetHostility(), Revive(), Map.rooms, Simulate(), Player.stats, Chara.TryRestock(), UpdateQuests(), Spatial.visitCount, and EClass.world.
Referenced by Activate().
OnVisitNewMapOrRegenerate()
virtual void Zone.OnVisitNewMapOrRegenerate () inline virtual
Reimplemented in Zone_Yowyn.
Definition at line 1457 of file Zone.cs.
    {
    }
Referenced by Activate().
RainWater()
void Zone.RainWater () inline
Definition at line 3423 of file Zone.cs.
    {
        if (EClass._map.IsIndoor || !this.IsPCFaction)
        {
            return;
        }
        EClass._map.bounds.ForeachCell(delegate(global::Cell c)
        {
            if (c.IsFarmField && !c.HasRoof)
            {
                c.isWatered = true;
            }
        });
    }
References EClass._map, Map.bounds, MapBounds.ForeachCell(), and Map.IsIndoor.
Referenced by Activate(), and Weather.SetCondition().
RefreshBGM()
void Zone.RefreshBGM () inline
Definition at line 3042 of file Zone.cs.
    {
        if (!EClass.pc.IsInActiveZone || EClass.player.simulatingZone)
        {
            return;
        }
        this.RefreshPlaylist();
        Playlist playlist = this.map.plDay;
        foreach (ZoneEvent zoneEvent in this.events.list)
        {
            if (zoneEvent.playlist != null)
            {
                playlist = zoneEvent.playlist;
            }
        }
        if (this.IDPlaylistOverwrite != null)
        {
            playlist = EClass.Sound.GetPlaylist(this.IDPlaylistOverwrite);
        }
        if (EClass.pc.IsInActiveZone)
        {
            global::Room room = EClass.pc.pos.cell.room;
            if (room != null && room.lot != null && room.lot.idBGM != 0)
            {
                playlist = EClass.Sound.plLot;
                BGMData data = playlist.list[0].data;
                int? num = (data != null) ? new int?(data.id) : null;
                int idBGM = room.lot.idBGM;
                if (!(num.GetValueOrDefault() == idBGM & num != null))
                {
                    playlist.list[0].data = EClass.core.refs.dictBGM.TryGetValue(room.lot.idBGM, null);
                    playlist.Reset();
                    if (!LayerDrama.keepBGM)
                    {
                        EClass.Sound.StopBGM(1f, false);
                    }
                }
            }
        }
        EClass.core.config.SetBGMInterval();
        EClass.Sound.SwitchPlaylist(playlist, !LayerDrama.keepBGM);
    }
References Point.cell, EClass.core, Chara.IsInActiveZone, LayerDrama.keepBGM, EClass.pc, EClass.player, ZoneEvent.playlist, Card.pos, Cell.room, Player.simulatingZone, and EClass.Sound.
Referenced by Activate(), BuildMenu.Deactivate(), BaseTileMap.Draw(), TileMapElona.Draw(), LayerNewZone.Embark(), ELayer.Kill(), ZoneEventSiege.OnFirstTick(), LayerEditPlaylist.OnKill(), and ZoneEventSiege.OnKill().
RefreshCriminal()
void Zone.RefreshCriminal () inline
Definition at line 3505 of file Zone.cs.
    {
        bool flag = EClass.player.IsCriminal && (this.HasLaw && !this.AllowCriminal) && !this.IsPCFaction;
        Hostility hostility = flag ? Hostility.Neutral : Hostility.Friend;
        foreach (Chara chara in EClass._map.charas)
        {
            if (chara.trait is TraitGuard)
            {
                chara.hostility = hostility;
                if (!flag && chara.enemy != null && chara.enemy.IsPCParty)
                {
                    chara.SetEnemy(null);
                }
            }
        }
    }
References EClass._map, Map.charas, Chara.enemy, Chara.IsPCParty, Chara.SetEnemy(), and Chara.trait.
Referenced by Player.ModKarma(), ConIncognito.OnRemoved(), ConIncognito.OnStart(), and OnVisit().
RefreshElectricity()
void Zone.RefreshElectricity () inline
Definition at line 2956 of file Zone.cs.
    {
        this.dirtyElectricity = false;
        base.electricity = this.elements.Value(2201) * 10 + this.BaseElectricity;
        foreach (Thing thing in EClass._map.things)
        {
            if (thing.IsInstalled && thing.trait.Electricity != 0 && (thing.isOn || thing.trait.Electricity > 0))
            {
                base.electricity += thing.trait.Electricity;
            }
        }
        foreach (Thing thing2 in EClass._map.things)
        {
            if (thing2.IsInstalled)
            {
                thing2.trait.TryToggle();
            }
        }
    }
References EClass._map, Trait.Electricity, Card.IsInstalled, Card.isOn, Map.things, Card.trait, and Trait.TryToggle().
Referenced by Activate(), TraitLeverBreaker.OnToggle(), Scene.OnUpdate(), TraitGenerator.Recover(), UIHomeInfo.Refresh(), TraitGenerator.ShortOut(), and TraitWrench.TrySetHeldAct().
RefreshHat()
void Zone.RefreshHat () inline
Definition at line 1351 of file Zone.cs.
    {
        if (this.idHat != null && EClass.world.date.IsExpired(base.dateHat))
        {
            this.idHat = null;
            base.dateHat = 0;
        }
        Zone.sourceHat = ((this.idHat != null) ? EClass.sources.cards.map[this.idHat] : ((this.IDHat != null) ? EClass.sources.cards.map[this.IDHat] : null));
    }
References SourceManager.cards, World.date, Spatial.idHat, IDHat, Date.IsExpired(), SourceCard.map, EClass.sources, and EClass.world.
Referenced by Activate(), and TraitHat.OnUse().
RefreshListCitizen()
void Zone.RefreshListCitizen () inline
Definition at line 3522 of file Zone.cs.
    {
        if (base.lv != 0)
        {
            return;
        }
        this.dictCitizen.Clear();
        foreach (Chara chara in this.map.charas.Concat(this.map.deadCharas))
        {
            if (chara.trait.IsCitizen && !chara.IsGlobal && !chara.isSubsetCard)
            {
                this.dictCitizen[chara.uid] = chara.Name;
            }
        }
    }
References TraitChara.IsCitizen, Chara.IsGlobal, Card.isSubsetCard, Card.Name, Chara.trait, and Card.uid.
Referenced by Activate(), and Chara.MakeAlly().
RefreshPlaylist()
void Zone.RefreshPlaylist () inline
Definition at line 3034 of file Zone.cs.
    {
        if (this.map.plDay == null)
        {
            this.map.plDay = this.CreatePlaylist(ref this.map._plDay, EClass.Sound.GetPlaylist(this.IDPlayList));
        }
    }
References EClass.Sound.
Referenced by ClaimZone(), and LayerEditPlaylist.OnKill().
RemoveCard()
void Zone.RemoveCard (Card t) inline
Implements ICardParent.
Definition at line 2300 of file Zone.cs.
    {
        if (this.IsActiveZone)
        {
            this.map.OnCardRemovedFromZone(t);
        }
        t.parent = null;
        if (t.isChara)
        {
            t.Chara.currentZone = null;
        }
        if (t.isThing && !t.trait.IDActorEx.IsEmpty())
        {
            EClass.scene.RemoveActorEx(t);
        }
        if (t.renderer.hasActor)
        {
            t.renderer.OnLeaveScreen();
        }
    }
References CardRenderer.hasActor, Trait.IDActorEx, IsActiveZone, Card.isChara, Card.isThing, map, Map.OnCardRemovedFromZone(), CardRenderer.OnLeaveScreen(), Scene.RemoveActorEx(), Card.renderer, EClass.scene, and Card.trait.
Referenced by Activate(), Faction.AddReserve(), Chara.MoveZone(), Map.OnDeactivate(), TaskMoveInstalled.OnProgressComplete(), Map.ReloadRoom(), Simulate(), ActThrow.Throw(), Chara.Tick(), and CoreDebug.UpdateInput().
ResetHostility()
void Zone.ResetHostility () inline
Definition at line 2825 of file Zone.cs.
    {
        foreach (Chara chara in EClass._map.charas)
        {
            if (!chara.source.hostility.IsEmpty() && chara.source.hostility.ToEnum(true) >= Hostility.Friend && !chara.IsPCFactionOrMinion)
            {
                chara.c_originalHostility = (Hostility)0;
            }
            chara.hostility = chara.OriginalHostility;
            if (chara.enemy != null && (chara.enemy.IsPCFaction || chara.IsPCFaction))
            {
                chara.SetEnemy(null);
            }
        }
    }
References EClass._map, Map.charas, Chara.enemy, Chara.IsPCFaction, Card.IsPCFactionOrMinion, Chara.OriginalHostility, Chara.SetEnemy(), and Chara.source.
Referenced by Chara.Die(), ConIncognito.OnStart(), and OnVisit().
Revive()
void Zone.Revive () inline
Definition at line 1403 of file Zone.cs.
    {
        base.dateRevive = EClass.world.date.GetRaw(0) + 1440 * EClass.setting.balance.dateRevive;
        if (this.ShouldAutoRevive)
        {
            foreach (Chara chara in this.map.deadCharas)
            {
                if (chara.trait.CanAutoRevive)
                {
                    chara.Revive(null, false);
                    if (chara.isBackerContent && EClass.player.doneBackers.Contains(chara.c_idBacker) && !EClass.core.config.test.ignoreBackerDestoryFlag)
                    {
                        chara.RemoveBacker();
                    }
                    EClass._zone.AddCard(chara, (chara.orgPos != null && chara.orgPos.IsInBounds) ? chara.orgPos : chara.pos);
                }
            }
        }
        foreach (Chara chara2 in EClass.game.cards.globalCharas.Values)
        {
            if (chara2.isDead && chara2.homeZone == this)
            {
                chara2.Revive(null, false);
                Point point = this.GetSpawnPos(chara2, ZoneTransition.EnterState.Auto);
                if (chara2.orgPos != null && chara2.orgPos.IsInBounds)
                {
                    point = (chara2.orgPos.GetNearestPoint(false, true, true, false) ?? point);
                }
                EClass._zone.AddCard(chara2, point);
            }
        }
        this.map.deadCharas.Clear();
    }
References EClass._zone, AddCard(), GameSetting.balance, Card.c_idBacker, TraitChara.CanAutoRevive, Game.cards, EClass.core, World.date, Map.deadCharas, Player.doneBackers, EClass.game, Point.GetNearestPoint(), Date.GetRaw(), GetSpawnPos(), CardManager.globalCharas, Chara.homeZone, Card.isBackerContent, Chara.isDead, Point.IsInBounds, map, Chara.orgPos, EClass.player, Card.pos, Card.RemoveBacker(), Chara.Revive(), EClass.setting, ShouldAutoRevive, Chara.trait, and EClass.world.
Referenced by OnVisit(), and Map.ResetEditorPos().
SetBGM() [1/2]
void Zone.SetBGM (int id = -1, bool refresh = true) inline
Definition at line 3026 of file Zone.cs.
    {
        this.SetBGM(new List<int>
        {
            id
        }, refresh);
    }
SetBGM() [2/2]
void Zone.SetBGM (List< int > ids, bool refresh = true) inline
Definition at line 3003 of file Zone.cs.
    {
        this.map._plDay.Clear();
        if (ids.Count > 0)
        {
            foreach (int num in ids)
            {
                if (num != -1)
                {
                    this.map._plDay.Add(num);
                }
            }
        }
        UnityEngine.Object.DestroyImmediate(this.map.plDay);
        this.map.plDay = null;
        this.RefreshPlaylist();
        if (refresh)
        {
            EClass.Sound.StopBGM(0f, false);
            this.RefreshBGM();
        }
    }
References EClass.Sound.
Referenced by ZoneEventSubdue.CheckClear(), ClaimZone(), ZoneEventDefenseGame.OnVisit(), ZoneEventHarvest.OnVisit(), ZoneEventSubdue.OnVisit(), GoalCombat.Run(), and Chara.TryDropBossLoot().
Simulate()
void Zone.Simulate () inline
Definition at line 1469 of file Zone.cs.
    {
        if (!EClass.game.isLoading && base.visitCount > 0)
        {
            if (this.Boss != null && this.IsNefia)
            {
                Msg.Say("bossLeave", this.Boss.Name.ToTitleCase(false), EClass._zone.Name, null, null);
                EClass._zone.RemoveCard(this.Boss);
                EClass._zone.GetTopZone().isConquered = true;
            }
            int num = Mathf.Clamp(this.MinsSinceLastActive, 1, 10000);
            foreach (Chara chara in EClass._map.charas)
            {
                if (chara.hp < 0)
                {
                    chara.hp = 0;
                }
                if (!chara.IsPCParty)
                {
                    if (chara.mana.value < 0)
                    {
                        chara.mana.value = 0;
                    }
                    if (chara.stamina.value < 0)
                    {
                        chara.stamina.value = 0;
                    }
                }
                if (num > 60)
                {
                    chara.resistCon = null;
                }
                if (chara.rarity >= Rarity.Legendary && !chara.IsPCFaction && num > 0)
                {
                    Msg.ignoreAll = true;
                    chara.Cure(CureType.Boss, 20 + num * 10, BlessedState.Normal);
                    chara.HealHP(Mathf.Max(1, chara.MaxHP) * num / 20, HealSource.None);
                    chara.mana.Mod(Mathf.Max(1, chara.mana.max) * num / 20);
                    chara.stamina.Mod(Mathf.Max(1, chara.stamina.max) * num / 20);
                    Msg.ignoreAll = false;
                }
            }
        }
        if (this.HourSinceLastActive <= 1)
        {
            return;
        }
        Debug.Log(this.Name + " Simulate:" + this.HourSinceLastActive.ToString() + " hours");
        VirtualDate virtualDate = new VirtualDate(this.HourSinceLastActive);
        List<Chara> list = EClass._map.charas.ToList<Chara>();
        int num2 = this.HourSinceLastActive / 24;
        if (num2 > 0)
        {
            foreach (Chara chara2 in list)
            {
                if (!chara2.IsPCParty)
                {
                    chara2.OnSleep(200, num2);
                    if (chara2.conSleep != null)
                    {
                        chara2.conSleep.Kill(false);
                    }
                    if (EClass.rnd(EClass.world.date.IsNight ? 20 : 200) == 0 && !chara2.IsPCFaction)
                    {
                        chara2.AddCondition<ConSleep>(1000 + EClass.rnd(1000), true);
                    }
                    if (chara2.things.Count > 20)
                    {
                        chara2.ClearInventory(ClearInventoryType.Purge);
                    }
                }
            }
        }
        EClass._map.things.ForeachReverse(delegate(Thing t)
        {
            t.DecayNatural(this.HourSinceLastActive);
        });
        VirtualDate.current = virtualDate;
        for (int i = 0; i < this.HourSinceLastActive; i++)
        {
            virtualDate.SimulateHour();
        }
        VirtualDate.current = null;
        if (!this.IsPCFaction)
        {
            return;
        }
        int num3 = 0;
        foreach (Chara chara3 in list)
        {
            if (!chara3.IsPCParty)
            {
                if (!chara3.IsHomeMember())
                {
                    if (chara3.id == "bee")
                    {
                        num3++;
                    }
                    if (num2 > 0 && chara3.IsGuest())
                    {
                        chara3.ChooseNewGoal();
                        chara3.ai.SimulateZone(num2);
                    }
                }
                else
                {
                    if (num2 > 0)
                    {
                        Goal goal = chara3.GetGoalWork();
                        chara3.SetAI(goal);
                        if (goal is GoalWork)
{
                            (goal as GoalWork).FindWork(chara3, true);
                        }
                        chara3.ai.SimulateZone(num2);
                        goal = chara3.GetGoalHobby();
                        chara3.SetAI(goal);
                        if (goal is GoalWork)
{
                            (goal as GoalWork).FindWork(chara3, true);
                        }
                        chara3.ai.SimulateZone(num2);
                    }
                    chara3.ChooseNewGoal();
                    if (chara3.conSuspend == null)
                    {
                        chara3.ai.OnSimulatePosition();
                    }
                }
            }
        }
        List<Thing> list2 = new List<Thing>();
        foreach (Thing thing in this.map.things)
        {
            if (thing.IsInstalled && thing.trait is TraitBeekeep)
            {
                list2.Add(thing);
            }
        }
        if (num3 < list2.Count)
        {
            for (int j = num3; j < list2.Count; j++)
            {
                if (EClass.rnd(200) <= this.HourSinceLastActive)
                {
                    Chara chara4 = CharaGen.Create("bee", -1);
                    this.AddCard(chara4, list2.RandomItem<Thing>().pos);
                    chara4.c_originalHostility = (chara4.hostility = Hostility.Neutral);
                }
            }
        }
    }
References EClass._map, EClass._zone, AddCard(), Chara.AddCondition(), Chara.ai, Boss, Map.charas, Chara.ChooseNewGoal(), Chara.ClearInventory(), Chara.conSleep, Chara.conSuspend, CharaGen.Create(), Chara.Cure(), World.date, Card.DecayNatural(), EClass.game, Chara.GetGoalHobby(), Chara.GetGoalWork(), GetTopZone(), Card.HealHP(), HourSinceLastActive, Card.hp, Card.id, Spatial.isConquered, Chara.IsGuest(), Chara.IsHomeMember(), Card.IsInstalled, Game.isLoading, IsNefia, Date.IsNight, Chara.IsPCFaction, IsPCFaction, Chara.IsPCParty, Condition.Kill(), Chara.mana, map, Stats.max, Chara.MaxHP, MinsSinceLastActive, Stats.Mod(), Card.Name, Spatial.Name, AIAct.OnSimulatePosition(), Chara.OnSleep(), Card.pos, Card.rarity, RemoveCard(), EClass.rnd(), Msg.Say(), Chara.SetAI(), VirtualDate.SimulateHour(), AIAct.SimulateZone(), Chara.stamina, Card.things, Map.things, Card.trait, Stats.value, and EClass.world.
Referenced by OnVisit().
SpawnAltar()
void Zone.SpawnAltar () inline
Definition at line 2661 of file Zone.cs.
    {
        EClass.core.refs.crawlers.start.CrawlUntil(this.map, () => this.map.poiMap.GetCenterCell(1).GetCenter(), 1, delegate(Crawler.Result r)
        {
            if (r.points.Count <= 4)
            {
                return false;
            }
            this.map.poiMap.OccyupyPOI(r.points[0], 0);
            List<Point> points = r.points;
            Religion randomReligion = EClass.game.religions.GetRandomReligion(true, false);
            "altarPoint".lang(randomReligion.NameDomain.lang(), null, null, null, null);
            Thing thing = ThingGen.Create("altar", -1, -1);
            (thing.trait as TraitAltar).SetDeity(randomReligion.id);
            Chara t = CharaGen.Create("twintail", -1);
            EClass._zone.AddCard(t, points.RandomItem<Point>());
            for (int i = 0; i < 2 + EClass.rnd(2); i++)
            {
                Chara t2 = CharaGen.Create("twintail", -1);
                EClass._zone.AddCard(t2, points.RandomItem<Point>());
            }
            if (points[0].Installed == null)
            {
                EClass._zone.AddCard(thing, points[0]).Install();
            }
            foreach (Point point in points)
            {
                if (point.x % 3 == 0 && point.z % 2 == 0 && point != points[0] && !point.Equals(points[0].Front) && point.Installed == null)
                {
                    thing = ThingGen.Create("pillar1", -1, -1);
                    EClass._zone.AddCard(thing, point).Install();
                }
                point.SetObj(0, 1, 0);
                point.SetFloor(3, 6);
            }
            return true;
        }, null);
    }
References EClass._zone, AddCard(), EClass.core, ThingGen.Create(), CharaGen.Create(), Point.Equals(), EClass.game, POIMap.GetCenterCell(), ReligionManager.GetRandomReligion(), Point.Installed, map, POIMap.OccyupyPOI(), Map.poiMap, Game.religions, EClass.rnd(), Point.SetFloor(), Point.SetObj(), Card.trait, Point.x, and Point.z.
Referenced by Generate().
SpawnLostItems()
void Zone.SpawnLostItems () inline
Definition at line 3680 of file Zone.cs.
    {
        for (int i = 0; i < 2 + EClass.rnd(4); i++)
        {
            Point point = Zone.<SpawnLostItems>g__GetPos|312_0();
            if (point != null)
            {
                if (EClass.rnd(30) == 0)
                {
                    Thing thing = ThingGen.Create("purse", -1, -1);
                    thing.isLostProperty = true;
                    thing.things.DestroyAll(null);
                    int num = EClass.rndHalf(Mathf.Min(base.development / 10 + 10, 50));
                    thing.c_lockLv = num;
                    thing.Add("money", EClass.rndHalf(num * 60 + 1000), 1);
                    if (EClass.rnd(2) == 0)
                    {
                        thing.Add("plat", EClass.rnd(4), 1);
                    }
                    else
                    {
                        thing.Add("medal", EClass.rnd(2), 1);
                    }
                    EClass._zone.AddCard(thing, point);
                }
                else
                {
                    EClass._zone.AddCard(ThingGen.CreateFromCategory("junk", -1), point);
                }
            }
        }
    }
References EClass._zone, Card.Add(), AddCard(), ThingGen.Create(), ThingGen.CreateFromCategory(), ThingContainer.DestroyAll(), EClass.rnd(), EClass.rndHalf(), and Card.things.
Referenced by Activate().
SpawnMob()
Chara Zone.SpawnMob (Point pos = null, SpawnSetting setting = null) inline
Definition at line 2859 of file Zone.cs.
    {
        if (setting == null)
        {
            setting = SpawnSetting.Default;
        }
        if (pos == null)
        {
            pos = this.GetSpawnPos(setting.position, setting.tries);
            if (pos == null)
            {
                pos = this.GetSpawnPos(SpawnPosition.Random, setting.tries);
                if (pos == null)
                {
                    return null;
                }
            }
        }
        BiomeProfile biome = pos.cell.biome;
        SpawnList spawnList;
        if (setting.idSpawnList != null)
        {
            spawnList = SpawnList.Get(setting.idSpawnList, null, null);
        }
        else if (setting.hostility == SpawnHostility.Neutral || (setting.hostility != SpawnHostility.Enemy && Rand.Range(0f, 1f) < this.ChanceSpawnNeutral))
        {
            spawnList = SpawnList.Get("c_neutral", null, null);
        }
        else if (biome.spawn.chara.Count > 0)
        {
            spawnList = SpawnList.Get(biome.spawn.GetRandomCharaId(), null, null);
        }
        else
        {
            spawnList = SpawnList.Get(biome.name, "chara", new CharaFilter
            {
                ShouldPass = ((SourceChara.Row s) => !(s.hostility != "") && (s.biome == biome.name || s.biome.IsEmpty()))
            });
        }
        int dangerLv = this.DangerLv;
        CardBlueprint cardBlueprint = new CardBlueprint
        {
            rarity = Rarity.Normal
        };
        int lv = (setting.filterLv == -1) ? dangerLv : setting.filterLv;
        if (this.ScaleMonsterLevel)
        {
            lv = ((dangerLv - 1) % 50 + 5) * 150 / 100;
        }
        CardRow cardRow = setting.id.IsEmpty() ? spawnList.Select(lv, setting.levelRange) : EClass.sources.cards.map[setting.id];
        int num = (setting.fixedLv == -1) ? cardRow.LV : setting.fixedLv;
        if (this.ScaleMonsterLevel)
        {
            num = (50 + cardRow.LV) * Mathf.Max(1, (dangerLv - 1) / 50);
        }
        if (setting.rarity == Rarity.Random)
        {
            if (EClass.rnd(100) == 0)
            {
                cardBlueprint.rarity = Rarity.Legendary;
                num = num * 125 / 100;
            }
        }
        else
        {
            cardBlueprint.rarity = setting.rarity;
        }
        if (setting.isBoss)
        {
            num = num * 150 / 100;
        }
        if (setting.isEvolved)
        {
            num = num * 2 + 20;
        }
        if (num != cardRow.LV)
        {
            cardBlueprint.lv = num;
        }
        CardBlueprint.Set(cardBlueprint);
        Chara chara = CharaGen.Create(cardRow.id, lv);
        this.AddCard(chara, pos);
        if (setting.forcedHostility != null)
        {
            chara.c_originalHostility = (chara.hostility = setting.forcedHostility.Value);
        }
        if (setting.isBoss)
        {
            chara.c_bossType = BossType.Boss;
        }
        if (setting.isEvolved)
        {
            chara.c_bossType = BossType.Evolved;
        }
        return chara;
    }
References SourceManager.cards, CharaGen.Create(), SpawnSetting.Default, SpawnList.Get(), CardRow.id, RenderRow.LV, SourceCard.map, EClass.rnd(), SpawnList.Select(), CardBlueprint.Set(), EClass.sources, and BiomeProfile.spawn.
Referenced by TraitShrine._OnUse(), ZonePreEnterEncounter.Execute(), ZoneEventHarvest.OnVisit(), ZoneEventQuest.Spawn(), ZoneEventQuest.SpawnBoss(), GenRoom.SpawnMob(), CoreDebug.TestSpawn(), TraitSpotSpawn.Update(), and CoreDebug.UpdateInput().
TextLevel()
string Zone.TextLevel (int _lv) inline
Definition at line 723 of file Zone.cs.
    {
        if (_lv == 0)
        {
            return "";
        }
        if (base.lv <= 0)
        {
            return " " + "zoneLevelB".lang((_lv * -1).ToString() ?? "", null, null, null, null);
        }
        return " " + "zoneLevel".lang((_lv + 1).ToString() ?? "", null, null, null, null);
    }
References ToString().
ToString()
override string Zone.ToString () inline
Definition at line 685 of file Zone.cs.
    {
        string[] array = new string[10];
        array[0] = this.Name;
        array[1] = "(";
        array[2] = base.uid.ToString();
        array[3] = ")(";
        int num = 4;
        Point regionPos = this._regionPos;
        array[num] = ((regionPos != null) ? regionPos.ToString() : null);
        array[5] = ") instance?";
        array[6] = this.IsInstance.ToString();
        array[7] = "/";
        array[8] = EClass.world.date.GetRemainingHours(base.dateExpire).ToString();
        array[9] = "h";
        return string.Concat(array);
    }
References Spatial._regionPos, World.date, Date.GetRemainingHours(), IsInstance, Spatial.Name, Point.ToString(), and EClass.world.
Referenced by _OnBeforeSave(), Activate(), TraitNewZone.CreateZone(), Game.OnLoad(), TextLevel(), and UnloadMap().
TryAddThing()
bool Zone.TryAddThing (Thing target, Point p, bool destroyIfFail = false) inline
Definition at line 2447 of file Zone.cs.
    {
        int num = 0;
        if (p.cell.detail != null)
        {
            foreach (Thing thing in p.cell.detail.things)
            {
                if (thing.placeState == PlaceState.roaming)
                {
                    if (target.TryStackTo(thing))
                    {
                        return true;
                    }
                    num++;
                }
            }
        }
        if (num == 0 || !destroyIfFail)
        {
            EClass._zone.AddCard(target, p);
            return true;
        }
        target.Destroy();
        return false;
    }
References EClass._zone, AddCard(), Point.cell, Card.Destroy(), Cell.detail, Card.placeState, CellDetail.things, and Card.TryStackTo().
Referenced by FactionBranch.g__Add(), and Chara.GiveBirth().
TryAddThingInSharedContainer()
bool Zone.TryAddThingInSharedContainer (Thing t, List< Thing > containers = null, bool add = true, bool msg = false, Chara chara = null, bool sharedOnly = true) inline
Definition at line 2408 of file Zone.cs.
    {
        Zone.<>c__DisplayClass256_0 CS$<>8__locals1;
        CS$<>8__locals1.containers = containers;
        CS$<>8__locals1.sharedOnly = sharedOnly;
        CS$<>8__locals1.add = add;
        CS$<>8__locals1.t = t;
        CS$<>8__locals1.msg = msg;
        CS$<>8__locals1.chara = chara;
        CS$<>8__locals1.dest = null;
        CS$<>8__locals1.priority = -1;
        CS$<>8__locals1.flag = CS$<>8__locals1.t.category.GetRoot().id.ToEnum(true);
        if (CS$<>8__locals1.flag == ContainerFlag.none)
        {
            CS$<>8__locals1.flag = ContainerFlag.other;
        }
        if (CS$<>8__locals1.containers == null)
        {
            CS$<>8__locals1.containers = EClass._map.props.installed.containers;
        }
        if (Zone.<TryAddThingInSharedContainer>g__SearchDest|256_0(ref CS$<>8__locals1) != null)
        {
            return true;
        }
        if (CS$<>8__locals1.dest == null)
        {
            return false;
        }
        if (CS$<>8__locals1.add)
        {
            if (CS$<>8__locals1.msg)
            {
                CS$<>8__locals1.chara.Say("putSharedItem", CS$<>8__locals1.chara, CS$<>8__locals1.t, CS$<>8__locals1.dest.GetName(NameStyle.Full, -1), null);
            }
            CS$<>8__locals1.dest.AddThing(CS$<>8__locals1.t, true, -1, -1);
        }
        return true;
    }
References EClass._map, Card.category, Props.containers, g__SearchDest(), PropsManager.installed, Map.props, and TryAddThingInSharedContainer().
Referenced by FactionBranch.AutoClean(), AI_Haul.GetThingToClean(), AI_Haul.Run(), TryAddThingInSharedContainer(), TryAddThingInSpot< T >(), GrowSystem.TryPick(), Chara.TryPutShared(), and Chara.TryPutSharedItems().
TryAddThingInSpot< T >()
bool Zone.TryAddThingInSpot< T > (Thing t, bool useContainer = true, bool putRandomPosIfNoSpot = true) inline
Type Constraints
T : Trait
Definition at line 2326 of file Zone.cs.
                                                                                                                  : Trait
    {
        Thing randomThing = EClass._map.props.installed.traits.GetRandomThing<T>();
        if (randomThing != null)
        {
            if (useContainer && (!t.IsContainer || t.things.Count == 0))
            {
                List<Thing> list = new List<Thing>();
                foreach (Point point in randomThing.trait.ListPoints(null, false))
                {
                    foreach (Card card in point.ListCards(false))
                    {
                        if (card.IsContainer)
{
                            list.Add(card.Thing);
                        }
                    }
                }
                if (this.TryAddThingInSharedContainer(t, list, true, false, null, false))
                {
                    return true;
                }
            }
            this.AddCard(t, randomThing.trait.GetRandomPoint(null, null));
            return true;
        }
        if (putRandomPosIfNoSpot)
        {
            this.AddCard(t, EClass._map.bounds.GetRandomSurface(false, true, false));
            return true;
        }
        return false;
    }
References EClass._map, AddCard(), Map.bounds, Trait.GetRandomPoint(), MapBounds.GetRandomSurface(), PropsManager.installed, Card.IsContainer, Point.ListCards(), Trait.ListPoints(), Map.props, Card.Thing, Card.things, Card.trait, Props.traits, and TryAddThingInSharedContainer().
TryGenerateBigDaddy()
void Zone.TryGenerateBigDaddy () inline
Definition at line 2773 of file Zone.cs.
    {
        if (this.BigDaddyChance <= EClass.rndf(1f))
        {
            return;
        }
        int num = this.DangerLv * 125 / 100;
        if (num >= 30)
        {
            CardBlueprint.Set(new CardBlueprint
            {
                lv = num
            });
        }
        Chara t = CharaGen.Create("big_daddy", -1);
        EClass._zone.AddCard(t, this.GetSpawnPos(SpawnPosition.Random, 10000));
        Msg.Say("sign_bigdaddy");
    }
References EClass._zone, AddCard(), CharaGen.Create(), EClass.rndf(), Msg.Say(), and CardBlueprint.Set().
TryGenerateEvolved()
Chara Zone.TryGenerateEvolved (bool force = false, Point p = null) inline
Definition at line 2754 of file Zone.cs.
    {
        if (!force && this.EvolvedChance <= EClass.rndf(1f))
        {
            return null;
        }
        Chara chara = this.SpawnMob(p, SpawnSetting.Evolved(-1));
        for (int i = 0; i < 2 + EClass.rnd(2); i++)
        {
            chara.ability.AddRandom();
        }
        chara.AddThing(chara.MakeGene(new DNA.Type?(DNA.Type.Default)), true, -1, -1);
        if (EClass.rnd(2) == 0)
        {
            chara.AddThing(chara.MakeGene(new DNA.Type?(DNA.Type.Superior)), true, -1, -1);
        }
        return chara;
    }
References Chara.ability, CharaAbility.AddRandom(), Card.AddThing(), SpawnSetting.Evolved(), Chara.MakeGene(), EClass.rnd(), and EClass.rndf().
Referenced by ZoneEventQuest.SpawnBoss(), and CoreDebug.UpdateInput().
TryGenerateOre()
void Zone.TryGenerateOre () inline
Definition at line 2725 of file Zone.cs.
    {
        if (this.OreChance <= 0f)
        {
            return;
        }
        Crawler crawler = Crawler.Create("ore");
        int tries = EClass.rnd((int)((float)(this.map.bounds.Width * this.map.bounds.Height / 200 + 1) * this.OreChance + 2f));
        crawler.CrawlUntil(EClass._map, () => EClass._map.bounds.GetRandomPoint(), tries, delegate(Crawler.Result r)
        {
            byte b = 18;
            string group = "ore";
            if (EClass.rnd(5) == 0)
            {
                b += 1;
                group = "gem";
            }
            SourceMaterial.Row randomMaterial = MATERIAL.GetRandomMaterial(this.DangerLv, group, false);
            foreach (Point point in r.points)
            {
                if (point.sourceBlock.ContainsTag("ore"))
                {
                    this.map.SetObj(point.x, point.z, randomMaterial.id, (int)b, 1, 0);
                }
            }
            return false;
        }, null);
    }
References EClass._map, Map.bounds, Crawler.CrawlUntil(), Crawler.Create(), MATERIAL.GetRandomMaterial(), MapBounds.GetRandomPoint(), and EClass.rnd().
TryGenerateShrine()
void Zone.TryGenerateShrine () inline
Definition at line 2792 of file Zone.cs.
    {
        for (int i = 0; i < 3; i++)
        {
            Rand.SetSeed(base.uid + i);
            if (this.ShrineChance > EClass.rndf(1f))
            {
                Point randomSpace = EClass._map.GetRandomSpace(3, 3, 100);
                if (randomSpace != null)
                {
                    randomSpace.x++;
                    randomSpace.z++;
                    if (!randomSpace.HasThing && !randomSpace.HasChara)
                    {
                        randomSpace.SetObj(0, 1, 0);
                        Rand.SetSeed(EClass.player.seedShrine);
                        EClass.player.seedShrine++;
                        if (EClass.rnd(EClass.debug.test ? 2 : 15) == 0)
{
                            EClass._zone.AddCard(ThingGen.Create("pedestal_power", -1, -1), randomSpace).Install();
                            EClass._zone.AddCard(ThingGen.Create(EClass.gamedata.godStatues.RandomItemWeighted((GodStatueData a) => a.chance).idThing, -1, this.DangerLv), randomSpace).Install();
                        }
                        else
{
                            EClass._zone.AddCard(ThingGen.Create("statue_power", -1, this.DangerLv), randomSpace).Install().SetRandomDir();
                        }
                    }
                }
            }
        }
        Rand.SetSeed(-1);
    }
References EClass._map, EClass._zone, AddCard(), GodStatueData.chance, ThingGen.Create(), EClass.debug, EClass.gamedata, MapBounds.GetRandomSpace(), GameData.godStatues, Point.HasChara, Point.HasThing, Card.Install(), EClass.player, EClass.rnd(), EClass.rndf(), Player.seedShrine, Point.SetObj(), Card.SetRandomDir(), CoreDebug.test, Point.x, and Point.z.
TryGetRestock< T >()
Thing Zone.TryGetRestock< T > (string idCat) inline
Type Constraints
T : TraitSpot
Definition at line 2489 of file Zone.cs.
                                                        : TraitSpot
    {
        Zone.<>c__DisplayClass259_0<T> CS$<>8__locals1 = new Zone.<>c__DisplayClass259_0<T>();
        CS$<>8__locals1.idCat = idCat;
        List<T> list = new List<T>();
        foreach (Thing thing in EClass._map.things)
        {
            if (thing.IsInstalled && thing.trait is T)
            {
                list.Add(thing.trait as T);
            }
        }
        foreach (T t in list)
        {
            foreach (Point point in t.ListPoints(null, false))
            {
                foreach (Thing thing2 in point.Things)
                {
                    if (thing2.IsInstalled && !thing2.isSale)
                    {
                        if (thing2.things.Count == 0)
{
                            if (CS$<>8__locals1.<TryGetRestock>g__IsValid|0(thing2, false))
{
                                return thing2;
                            }
                        }
                        else
{
                            ThingContainer things = thing2.things;
                            Func<Thing, bool> func;
                            if ((func = CS$<>8__locals1.<>9__1) == null)
{
                                func = (CS$<>8__locals1.<>9__1 = ((Thing _t) => base.<TryGetRestock>g__IsValid|0(_t, true)));
                            }
                            Thing thing3 = things.Find(func, true);
                            if (thing3 != null)
{
                                return thing3;
                            }
                        }
                    }
                }
            }
        }
        return null;
    }
References EClass._map, ThingContainer.Find(), Card.IsInstalled, Card.isSale, Card.things, Map.things, Point.Things, and Card.trait.
TryGetThingFromSharedContainer()
Thing Zone.TryGetThingFromSharedContainer (Func< Thing, bool > func) inline
Definition at line 2473 of file Zone.cs.
    {
        foreach (Thing thing in EClass._map.props.installed.containers)
        {
            if (thing.IsSharedContainer)
            {
                Thing thing2 = thing.things.Find(func, true);
                if (thing2 != null)
                {
                    return thing2;
                }
            }
        }
        return null;
    }
References EClass._map, Props.containers, ThingContainer.Find(), PropsManager.installed, Thing.IsSharedContainer, Map.props, and Card.things.
Referenced by FactionBranch.GetMeal().
TryListThingsInSpot< T >()
List< Thing > Zone.TryListThingsInSpot< T > (Func< Thing, bool > func = null) inline
Type Constraints
T : TraitSpot
Definition at line 2360 of file Zone.cs.
                                                                                     : TraitSpot
    {
        Zone.<>c__DisplayClass255_0<T> CS$<>8__locals1 = new Zone.<>c__DisplayClass255_0<T>();
        CS$<>8__locals1.func = func;
        List<T> list = new List<T>();
        List<Thing> list2 = new List<Thing>();
        foreach (Thing thing in EClass._map.things)
        {
            if (thing.IsInstalled && thing.trait is T)
            {
                list.Add(thing.trait as T);
            }
        }
        foreach (T t in list)
        {
            foreach (Point point in t.ListPoints(null, false))
            {
                foreach (Thing thing2 in point.Things)
                {
                    if (thing2.IsInstalled)
                    {
                        if (thing2.things.Count == 0)
{
                            if (CS$<>8__locals1.<TryListThingsInSpot>g__IsValid|0(thing2))
{
                                list2.Add(thing2);
                            }
                        }
                        else
{
                            ThingContainer things = thing2.things;
                            Func<Thing, bool> func2;
                            if ((func2 = CS$<>8__locals1.<>9__1) == null)
{
                                func2 = (CS$<>8__locals1.<>9__1 = ((Thing _t) => base.<TryListThingsInSpot>g__IsValid|0(_t)));
                            }
                            foreach (Thing item in things.List(func2, false))
{
                                list2.Add(item);
                            }
                        }
                    }
                }
            }
        }
        return list2;
    }
References EClass._map, ActPlan.List.Add(), Card.IsInstalled, Card.things, Map.things, Point.Things, and Card.trait.
TrySpawnFollower()
void Zone.TrySpawnFollower () inline
Definition at line 2625 of file Zone.cs.
    {
        bool flag = EClass.pc.HasCondition<ConDrawBacker>();
        if (!EClass.debug.enable && EClass.rnd(flag ? 3 : 20) != 0)
        {
            return;
        }
        Point randomSurface = EClass._map.bounds.GetRandomSurface(false, true, false);
        if (!randomSurface.IsValid)
        {
            return;
        }
        Chara c = CharaGen.Create("follower", -1);
        EClass._zone.AddCard(c, randomSurface);
        (EClass._zone.AddThing("gallows", randomSurface).Install().trait as TraitShackle).Restrain(c, false);
        c.c_rescueState = RescueState.WaitingForRescue;
        if (EClass.rnd(flag ? 1 : 2) == 0 || EClass.debug.enable)
        {
            SourceBacker.Row row = EClass.sources.backers.listFollower.NextItem(ref BackerContent.indexFollower);
            if (row != null)
            {
                c.ApplyBacker(row.id);
            }
        }
        Religion faith = (from a in EClass.game.religions.dictAll.Values
        where a != c.faith
        select a).RandomItem<Religion>();
        for (int i = 0; i < 3 + EClass.rnd(4); i++)
        {
            Chara chara = CharaGen.Create("fanatic", -1);
            chara.SetFaith(faith);
            Point point = randomSurface.GetRandomPoint(4, true, true, false, 100) ?? randomSurface.GetNearestPoint(false, true, true, false);
            EClass._zone.AddCard(chara, point);
        }
    }
References EClass._map, EClass._zone, AddCard(), AddThing(), Card.ApplyBacker(), SourceManager.backers, Map.bounds, CharaGen.Create(), EClass.debug, CoreDebug.enable, faith, Point.GetNearestPoint(), Point.GetRandomPoint(), MapBounds.GetRandomSurface(), Chara.HasCondition(), SourceBacker.Row.id, BackerContent.indexFollower, Card.Install(), Point.IsValid, SourceBacker.listFollower, EClass.pc, EClass.rnd(), Chara.SetFaith(), EClass.sources, and Card.trait.
Referenced by Generate().
UnloadMap()
void Zone.UnloadMap () inline
Definition at line 2034 of file Zone.cs.
    {
        this.map = null;
        if (this.bp != null)
        {
            this.bp.map = null;
        }
        if (this.branch != null)
        {
            this.branch.OnUnloadMap();
        }
        Debug.Log("Unloaded Map:" + ((this != null) ? this.ToString() : null));
    }
References bp, branch, FactionBranch.OnUnloadMap(), and ToString().
Referenced by _OnBeforeSave(), Activate(), ClearZones(), Deactivate(), and Destroy().
UpdateQuests()
void Zone.UpdateQuests (bool force = false) inline
Definition at line 3557 of file Zone.cs.
    {
        if (!this.IsPCFaction && (!(this is Zone_Town) || base.lv != 0))
        {
            return;
        }
        Debug.Log("Updating Quest:" + force.ToString());
        List<SourceQuest.Row> list = (from a in EClass.sources.quests.rows
        where a.@group == "random"
        select a).ToList<SourceQuest.Row>();
        int num = 0;
        foreach (Chara chara in this.map.charas.Concat(this.map.deadCharas))
        {
            if (chara.quest != null && !EClass.game.quests.list.Contains(chara.quest))
            {
                if (chara.quest.IsExpired || this.completedQuests.Contains(chara.quest.uid) || force)
                {
                    chara.quest = null;
                }
                else
                {
                    num++;
                }
            }
        }
        if (EClass._zone.dateQuest > EClass.world.date.GetRaw(0) && !force)
        {
            return;
        }
        EClass._zone.dateQuest = EClass.world.date.GetRaw(0) + 1440;
        int maxQuest = 3;
        Rand.UseSeed(base.uid + EClass.player.stats.days / 7 % 100, delegate
        {
            maxQuest = 4 + EClass.rnd(4);
        });
        this.completedQuests.Clear();
        List<Zone> list2 = Quest.ListDeliver();
        List<Tuple<string, int>> listTag = new List<Tuple<string, int>>();
        string[] array = EClass._zone.source.questTag;
        if (EClass._zone.IsPCFaction)
        {
            array = new string[]
            {
                "supply/8",
                "deliver/7",
                "food/8",
                "escort/4",
                "deliver/4",
                "monster/0",
                "war/0",
                "farm/0",
                "music/0"
            };
        }
        string[] array2 = array;
        for (int i = 0; i < array2.Length; i++)
        {
            string[] array3 = array2[i].Split('/', StringSplitOptions.None);
            listTag.Add(new Tuple<string, int>(array3[0], array3[1].ToInt()));
        }
        int num2 = 0;
        Func<SourceQuest.Row, float> <>9__2;
        while (num2 < this.map.charas.Count * 2 && num <= maxQuest && num <= 15)
        {
            Chara chara2 = this.map.charas.RandomItem<Chara>();
            if (chara2.trait.CanGiveRandomQuest && !chara2.isSubsetCard && chara2.homeZone == EClass._zone && !chara2.IsGuest() && chara2.memberType != FactionMemberType.Livestock && (chara2.quest == null || force))
            {
                IList<SourceQuest.Row> source = list;
                Func<SourceQuest.Row, float> getWeight;
                if ((getWeight = <>9__2) == null)
                {
                    getWeight = (<>9__2 = delegate(SourceQuest.Row a)
                    {
                        int num3 = 1;
                        foreach (Tuple<string, int> tuple in listTag)
{
                            if (a.tags.Contains(tuple.Item1))
{
                                num3 = tuple.Item2;
                                break;
                            }
                        }
                        if (!EClass._zone.IsPCFaction && a.tags.Contains("bulk"))
{
                            num3 = 0;
                        }
                        return (float)(a.chance * num3);
                    });
                }
                SourceQuest.Row row = source.RandomItemWeighted(getWeight);
                if ((!row.tags.Contains("needDestZone") || list2.Count >= 2) && (row.minFame <= 0 || row.minFame < EClass.player.fame || EClass.debug.enable))
                {
                    Quest.Create(row.id, null, chara2);
                    num++;
                }
            }
            num2++;
        }
    }
References EClass._zone, World.date, Spatial.dateQuest, EClass.game, Date.GetRaw(), Quest.IsExpired, QuestManager.list, EClass.player, Chara.quest, Game.quests, EClass.rnd(), Player.stats, Quest.uid, and EClass.world.
Referenced by LayerQuestBoard.OnSwitchContent(), OnVisit(), and LayerQuestBoard.RefreshQuest().
WriteNote()
void Zone.WriteNote (UINote n, Action< UINote > onWriteNote = null, IInspect::NoteMode mode = IInspect::NoteMode::Default, Recipe recipe = null) inline
Implements IInspect.
Definition at line 3295 of file Zone.cs.
    {
    }
Member Data Documentation
_biome
BiomeProfile Zone._biome
Definition at line 3894 of file Zone.cs.
bounds
MapBounds Zone.bounds
Definition at line 3867 of file Zone.cs.
Referenced by FactionBranch.g__Add(), g__GetPos(), Zone_SnowGrave.GenerateGrave(), and MapGen.OnGenerateTerrain().
bp
ZoneBlueprint Zone.bp
Definition at line 3882 of file Zone.cs.
Referenced by Activate(), CreateBP(), Generate(), GetProfile(), and UnloadMap().
branch
FactionBranch Zone.branch
Definition at line 3855 of file Zone.cs.
Referenced by AbandonZone(), ClaimZone(), Faction.CountWealth(), ActEffect.DamageEle(), Deactivate(), RankedZoneManager.GetIncome(), Quest.Init(), LayerQuestBoard.OnInit(), OnLoad(), ContentHomeReport.OnSwitchContent(), ItemCulture.Refresh(), UIHomeInfo.Refresh(), TraitGeneratorWheel.Refresh(), UIHomeInfo.RefreshReport(), AI_Idle.Run(), UIFactionInfo.SetZone(), GameDate.ShipGoods(), LayerShippingResult.Show(), TraitTeleporter.TryTeleport(), and UnloadMap().
completedQuests
HashSet<int> Zone.completedQuests = new HashSet<int>()
Definition at line 3858 of file Zone.cs.
Referenced by Quest.Complete(), and Quest.Fail().
dictCitizen
Dictionary<int, string> Zone.dictCitizen = new Dictionary<int, string>()
Definition at line 3870 of file Zone.cs.
Referenced by Quest.Create(), and Quest.ListDeliver().
dirtyElectricity
bool Zone.dirtyElectricity
Definition at line 3886 of file Zone.cs.
Referenced by Scene.OnUpdate().
elements
ElementContainerZone Zone.elements = new ElementContainerZone()
Definition at line 3864 of file Zone.cs.
Referenced by CoreDebug.COM_MaxConstruction(), BuildMenu.OnActivate(), Policy.OnAdvanceHour(), Game.OnLoad(), TraitGeneratorWheel.Refresh(), AI_PassTime.Run(), TraitFoodEgg.Update(), and Policy.WriteNote().
events
ZoneEventManager Zone.events = new ZoneEventManager()
Definition at line 3861 of file Zone.cs.
Referenced by WidgetDate._Refresh(), WidgetMascot._Update(), Activate(), GameDate.AdvanceMin(), Chara.CanSleep(), QuestInstance.CreateInstanceZone(), Chara.Die(), Player.EnterLocalZone(), QuestSubdue.GetTextProgress(), ZoneEvent.Kill(), TraitNewZone.MoveZone(), OnLoad(), AI_Sleep.OnProgressComplete(), TraitPhone.OnSimulateHour(), QuestFiamaLock.OnStart(), OnVisit(), HotItemActionSleep.Perform(), UIHomeInfo.RefreshReport(), Card.SpawnLoot(), CoreDebug.Test_Siege(), CoreDebug.Test_SiegeGuard(), TraitCoreDefense.TrySetAct(), GameUpdater.Update(), and WidgetDebug.UpdateText().
fileVariation
int Zone.fileVariation
Definition at line 3884 of file Zone.cs.
forceRegenerate
bool Zone.forceRegenerate static
Definition at line 3846 of file Zone.cs.
Referenced by Activate(), and Deactivate().
forceSubset
string Zone.forceSubset static
Definition at line 3848 of file Zone.cs.
ignoreSpawnAnime
bool Zone.ignoreSpawnAnime static
Definition at line 3896 of file Zone.cs.
Referenced by AddCard().
instance
ZoneInstance Zone.instance
Definition at line 3873 of file Zone.cs.
Referenced by ActPlan._Update(), Activate(), ZoneEventSubdue.CheckClear(), Player.ExitBorder(), EloMap.GetZone(), Chara.IsHostile(), Chara.MoveZone(), ZoneEventHarvest.OnLeaveZone(), TraitDeed.OnRead(), and ActEffect.Proc().
isSimulating
bool Zone.isSimulating
Definition at line 3890 of file Zone.cs.
Referenced by Chara.GetGoalFromTimeTable().
isStarted
bool Zone.isStarted
Definition at line 3888 of file Zone.cs.
Referenced by AddCard(), Card.CalculateFOV(), ActorEx.GetVolume(), Trait.Install(), WidgetCodex.OnActivate(), TextureManager.RefreshTextures(), ConSleep.Tick(), and Trait.Toggle().
landFeats
List<int> Zone.landFeats
Definition at line 3876 of file Zone.cs.
map
Map Zone.map
Definition at line 3878 of file Zone.cs.
Referenced by Chara._Move(), _OnBeforeSave(), Activate(), AddCard(), AddGlobalCharasOnActivate(), Party.AddMemeber(), ClaimZone(), ClearZones(), GenBounds.Create(), LayerPeople.CreateSelectEmbarkMembers(), Deactivate(), Destroy(), BaseTileMap.Draw(), TileMapElona.Draw(), Generate(), Region.GetRandomPoint(), GetRandomVisitPos(), GetSpawnPos(), Zone_Field.OnGenerateMap(), OnKillGame(), RemoveCard(), FactionBranch.RemoveMemeber(), Revive(), Simulate(), and SpawnAltar().
okaerinko
int Zone.okaerinko = 0 static
Definition at line 3852 of file Zone.cs.
Referenced by AI_Idle.Run().
sourceHat
CardRow Zone.sourceHat static
Definition at line 3850 of file Zone.cs.
Referenced by CharaRenderer.Draw(), and CharaRenderer.DrawHat().
subset
MapSubset Zone.subset
Definition at line 3880 of file Zone.cs.
Referenced by Activate(), and MapSubset.Save().
Suckers
List<Thing> Zone.Suckers = new List<Thing>() static
Definition at line 3898 of file Zone.cs.
Referenced by OnSimulateHour(), and TraitSeed.TrySprout().
tempDist
int Zone.tempDist
Definition at line 3892 of file Zone.cs.
Referenced by LayerTravel.GetTravelFood(), and LayerTravel.Refresh().
Property Documentation
AddPrefix
virtual bool Zone.AddPrefix get
Definition at line 424 of file Zone.cs.
    {
        get
        {
            return false;
        }
    }
Referenced by OnAfterCreate().
AllowCriminal
virtual bool Zone.AllowCriminal get
Definition at line 336 of file Zone.cs.
    {
        get
        {
            return !this.HasLaw;
        }
    }
AllowNewZone
virtual bool Zone.AllowNewZone get
Definition at line 344 of file Zone.cs.
    {
        get
        {
            return true;
        }
    }
Referenced by TraitNewZone.TrySetAct().
AlwaysLowblock
virtual bool Zone.AlwaysLowblock get
Definition at line 632 of file Zone.cs.
    {
        get
        {
            return this.map.IsIndoor;
        }
    }
Referenced by BaseTileMap.Draw().
BaseElectricity
virtual int Zone.BaseElectricity get
Definition at line 796 of file Zone.cs.
    {
        get
        {
            return 0;
        }
    }
BigDaddyChance
virtual float Zone.BigDaddyChance get
Definition at line 496 of file Zone.cs.
    {
        get
        {
            return 0f;
        }
    }
biome
BiomeProfile Zone.biome get
Definition at line 70 of file Zone.cs.
    {
        get
        {
            BiomeProfile result;
            if ((result = this._biome) == null)
            {
                result = (this._biome = EClass.core.refs.biomes.dict[this.IdBiome]);
            }
            return result;
        }
    }
Referenced by WidgetDate._Refresh(), PartialMap.Apply(), ZonePreEnterDigStairs.Execute(), MapGenDungen.g__SetRoom(), Generate(), Region.OnAdvanceHour(), MapGenDungen.OnGenerateTerrain(), GenRoom.OnPopulate(), TraitStairsLocked.OnUse(), GenRoom.Populate(), SerializedCards.Restore(), and BaseGameScreen.UpdateShaders().
BlockBorderExit
virtual bool Zone.BlockBorderExit get
Definition at line 204 of file Zone.cs.
    {
        get
        {
            return base.lv != 0;
        }
    }
Boss
Chara Zone.Boss get set
Definition at line 14 of file Zone.cs.
    {
        get
        {
            return EClass._map.FindChara(base.uidBoss);
        }
        set
        {
            base.uidBoss = ((value != null) ? value.uid : 0);
        }
    }
Referenced by Scene.Init(), TraitNewZone.MoveZone(), ActEffect.Proc(), AI_Idle.Run(), Simulate(), and Chara.TryDropBossLoot().
CanBeDeliverDestination
virtual bool Zone.CanBeDeliverDestination get
Definition at line 296 of file Zone.cs.
    {
        get
        {
            return this.IsTown;
        }
    }
Referenced by Quest.ListDeliver().
CanDigUnderground
virtual bool Zone.CanDigUnderground get
Definition at line 384 of file Zone.cs.
    {
        get
        {
            return false;
        }
    }
Referenced by TaskMine.GetHitResult().
CanEnterBuildMode
bool Zone.CanEnterBuildMode get
Definition at line 748 of file Zone.cs.
    {
        get
        {
            return EClass.debug.godBuild || EClass.debug.ignoreBuildRule || base.mainFaction == EClass.pc.faction;
        }
    }
CanEnterBuildModeAnywhere
bool Zone.CanEnterBuildModeAnywhere get
Definition at line 756 of file Zone.cs.
    {
        get
        {
            return EClass.debug.godBuild || EClass.debug.ignoreBuildRule || (base.mainFaction == EClass.pc.faction && EClass.Branch.elements.Has(4003));
        }
    }
Referenced by WidgetMenuPanel._OnChangeMode(), ActionMode.DoFunc(), and HotbarManager.ResetHotbar().
CanInspect
bool Zone.CanInspect get
Implements IInspect.
Definition at line 812 of file Zone.cs.
    {
        get
        {
            return !this.IsInstance && !this.HiddenInRegionMap;
        }
    }
CanUnlockExit
virtual bool Zone.CanUnlockExit get
Definition at line 400 of file Zone.cs.
    {
        get
        {
            return !this.LockExit;
        }
    }
Referenced by TraitStairsLocked.OnUse().
ChanceSpawnNeutral
virtual float Zone.ChanceSpawnNeutral get
Definition at line 552 of file Zone.cs.
    {
        get
        {
            return 0.05f;
        }
    }
CountDeepestLevel
virtual bool Zone.CountDeepestLevel get
Definition at line 304 of file Zone.cs.
    {
        get
        {
            return false;
        }
    }
Referenced by OnVisit().
DangerLv
override int Zone.DangerLv get
Definition at line 26 of file Zone.cs.
    {
        get
        {
            if (this.GetTopZone() != this)
            {
                return this.GetTopZone().DangerLv + Mathf.Abs(base.lv) - 1;
            }
            return (int)Mathf.Max(1f, (float)base._dangerLv + MathF.Abs((float)base.lv) + (float)this.DangerLvFix);
        }
    }
Referenced by Chara._Move(), WidgetDate._Refresh(), RecipeCard.Build(), ZonePreEnterEncounter.Execute(), Map.MineBlock(), ZoneEventDefenseGame.NextWave(), MapGenDungen.OnGenerateTerrain(), TraitNote.OnImportMap(), GenRoom.OnPopulate(), OnVisit(), ActEffect.ProcAt(), TraitBaseSpellbook.ReadFailEffect(), SerializedCards.Restore(), Map.SetObj(), ZoneEventQuest.Spawn(), ZoneEventQuest.SpawnBoss(), Chara.TryDropBossLoot(), and Card.TryMakeRandomItem().
DefaultActionMode
virtual ActionMode Zone.DefaultActionMode get
Definition at line 196 of file Zone.cs.
    {
        get
        {
            return ActionMode.Adv;
        }
    }
DisableRooms
virtual bool Zone.DisableRooms get
Definition at line 38 of file Zone.cs.
    {
        get
        {
            return false;
        }
    }
Referenced by Map.TryAddRoom().
EvolvedChance
virtual float Zone.EvolvedChance get
Definition at line 504 of file Zone.cs.
    {
        get
        {
            return 0f;
        }
    }
ExpireDays
virtual int Zone.ExpireDays get
Definition at line 212 of file Zone.cs.
    {
        get
        {
            return EClass.setting.balance.dateExpireRandomMap;
        }
    }
Referenced by Activate().
FeatureType
virtual ZoneFeatureType Zone.FeatureType get
Definition at line 228 of file Zone.cs.
    {
        get
        {
            return ZoneFeatureType.Default;
        }
    }
FlockType
virtual FlockController.SpawnType Zone.FlockType get
Definition at line 677 of file Zone.cs.
    {
        get
        {
            return FlockController.SpawnType.Default;
        }
    }
Referenced by Scene.Init().
Generator
MapGenerator Zone.Generator get
Definition at line 112 of file Zone.cs.
    {
        get
        {
            return ResourceCache.Load<MapGenerator>("DunGenProfile/Generator_" + this.GetDungenID());
        }
    }
Referenced by MapGenDungen.OnGenerateTerrain().
GrowPlant
virtual bool Zone.GrowPlant get
Definition at line 560 of file Zone.cs.
    {
        get
        {
            return base.mainFaction == EClass.pc.faction;
        }
    }
GrowWeed
virtual bool Zone.GrowWeed get
Definition at line 568 of file Zone.cs.
    {
        get
        {
            return this.GrowPlant;
        }
    }
HasLaw
virtual bool Zone.HasLaw get
Definition at line 312 of file Zone.cs.
    {
        get
        {
            return false;
        }
    }
Referenced by Chara.Die(), and QuestManager.HasFarAwayEscort().
HiddenInRegionMap
virtual bool Zone.HiddenInRegionMap get
Definition at line 664 of file Zone.cs.
    {
        get
        {
            return false;
        }
    }
Referenced by Chara._Move().
HourSinceLastActive
int Zone.HourSinceLastActive get
Definition at line 46 of file Zone.cs.
    {
        get
        {
            return EClass.world.date.GetElapsedHour(base.lastActive);
        }
    }
Referenced by Simulate().
IDAmbience
virtual string Zone.IDAmbience get
Definition at line 236 of file Zone.cs.
    {
        get
        {
            if (this.IsRegion || this.map.IsIndoor)
            {
                return null;
            }
            if (!this.IsTown)
            {
                return "forest";
            }
            return "town";
        }
    }
Referenced by Activate().
IDBaseLandFeat
virtual string Zone.IDBaseLandFeat get
Definition at line 152 of file Zone.cs.
    {
        get
        {
            return base.Tile.source.trait[0];
        }
    }
IdBiome
virtual string Zone.IdBiome get
Definition at line 83 of file Zone.cs.
    {
        get
        {
            return this.map.config.idBiome.IsEmpty(base.source.idBiome);
        }
    }
idExport
virtual string Zone.idExport get
Definition at line 160 of file Zone.cs.
    {
        get
        {
            if (base.source.idFile.Length != 0)
            {
                return base.source.idFile[this.fileVariation] + ((base.lv == 0) ? "" : ("_F" + base.lv.ToString()));
            }
            return "";
        }
    }
Referenced by Activate(), MapSubset.Exist(), MapSubset.Load(), Zone_Dungeon.OnGenerateMap(), and MapSubset.Save().
IDGenerator
virtual string Zone.IDGenerator get
Definition at line 96 of file Zone.cs.
    {
        get
        {
            return null;
        }
    }
Referenced by ZoneBlueprint.GenerateMap(), and TraitNewZone.MoveZone().
IDHat
virtual string Zone.IDHat get
Definition at line 144 of file Zone.cs.
    {
        get
        {
            return null;
        }
    }
Referenced by RefreshHat().
IDPlayList
virtual string Zone.IDPlayList get
Definition at line 128 of file Zone.cs.
    {
        get
        {
            return base.source.idPlaylist.IsEmpty((base.lv != 0) ? "Underground" : null);
        }
    }
IDPlaylistOverwrite
virtual string Zone.IDPlaylistOverwrite get
Definition at line 136 of file Zone.cs.
    {
        get
        {
            return null;
        }
    }
IdProfile
virtual string Zone.IdProfile get
Definition at line 120 of file Zone.cs.
    {
        get
        {
            return this.idProfile.IsEmpty(base.source.idProfile);
        }
    }
Referenced by GetProfile().
IDSceneTemplate
virtual string Zone.IDSceneTemplate get
Definition at line 252 of file Zone.cs.
    {
        get
        {
            if (EClass._map.IsIndoor)
            {
                return "Indoor";
            }
            if (!this.IsSnowZone)
            {
                return "Default";
            }
            return "Snow";
        }
    }
Referenced by BaseGameScreen.RefreshGrading().
IDSubset
virtual string Zone.IDSubset get
Definition at line 276 of file Zone.cs.
    {
        get
        {
            if (!this.IsFestival)
            {
                return null;
            }
            return "festival";
        }
    }
Referenced by Activate().
InspectName
string Zone.InspectName get
Implements IInspect.
Definition at line 820 of file Zone.cs.
    {
        get
        {
            return this.Name + ((this.IsTown || this.IsPCFaction || this is Zone_Civilized) ? "" : "dangerLv".lang(this.DangerLv.ToString() ?? "", null, null, null, null));
        }
    }
InspectPoint
Point Zone.InspectPoint get
Implements IInspect.
Definition at line 828 of file Zone.cs.
    {
        get
        {
            return null;
        }
    }
InspectPosition
Vector3 Zone.InspectPosition get
Implements IInspect.
Definition at line 836 of file Zone.cs.
    {
        get
        {
            return default(Vector3);
        }
    }
IsActiveZone
bool Zone.IsActiveZone get
Definition at line 804 of file Zone.cs.
    {
        get
        {
            return EClass.game.activeZone == this;
        }
    }
Referenced by _OnBeforeSave(), AddCard(), ZoneEventManager.AddPreEnter(), CanDestroy(), Chara.MoveHome(), Chara.MoveZone(), AM_BaseGameMode.OnUpdateInput(), RemoveCard(), and WidgetMinimap.UpdateMap().
IsExplorable
virtual bool Zone.IsExplorable get
Definition at line 576 of file Zone.cs.
    {
        get
        {
            return !base.isRandomSite;
        }
    }
IsFestival
virtual bool Zone.IsFestival get
Definition at line 268 of file Zone.cs.
    {
        get
        {
            return false;
        }
    }
Referenced by GameLang.ConvertDrama(), Trait.CreateStock(), Trait.g__IsFestival(), Trait.OnBarter(), and TraitSpecialLantern.OnCreate().
IsInstance
bool Zone.IsInstance get
Definition at line 780 of file Zone.cs.
    {
        get
        {
            return this.instance != null;
        }
    }
Referenced by WidgetDate._Refresh(), LayerSleep.Advance(), CanDestroy(), Deactivate(), QuestManager.HasFarAwayEscort(), EloMap.Init(), Region.ListTravelZones(), Region.OnActivate(), Scene.OnUpdate(), ToString(), TraitNewZone.TrySetAct(), and TraitWaystone.TrySetAct().
IsLoaded
bool Zone.IsLoaded get
Definition at line 788 of file Zone.cs.
    {
        get
        {
            return this.map != null;
        }
    }
Referenced by Activate().
IsNefia
virtual bool Zone.IsNefia get
Definition at line 432 of file Zone.cs.
    {
        get
        {
            return false;
        }
    }
Referenced by TraitNewZone.MoveZone(), AI_Idle.Run(), Simulate(), and Chara.TryDropBossLoot().
IsPCFaction
bool Zone.IsPCFaction get
Definition at line 764 of file Zone.cs.
    {
        get
        {
            return base.mainFaction == EClass.pc.faction;
        }
    }
Referenced by Chara._Move(), WidgetDate._Refresh(), Map._ValidateInstalled(), Activate(), LayerSleep.Advance(), CanDestroy(), ActRestrain.CanPerform(), HotItemHeld.CanRotate(), QuestVernis.CanUpdateOnTalk(), TraitLoytelMart.CanUse(), GameLang.ConvertDrama(), Faction.CountWealth(), Card.Create(), ActEffect.DamageEle(), Card.DamageHP(), Deactivate(), Chara.DoHostileAction(), BaseTileMap.DrawTile(), RankedZone.GetFactionName(), TaskBuild.GetHitResult(), TaskDig.GetHitResult(), Card.GetPrice(), GetRandomVisitPos(), Chara.GetRevived(), GetSpawnPos(), Chara.HasAccess(), QuestManager.HasFarAwayEscort(), TraitFoodEggFertilized.Incubate(), Quest.IsVisibleOnQuestBoard(), Quest.ListDeliver(), QuestDeliver.ListDestThing(), Map.MineObj(), Chara.MoveZone(), Region.OnActivate(), TraitHitchingPost.OnActivateTrap(), QuestRandom.OnDropReward(), Player.Flags.OnEnterZone(), LayerQuestBoard.OnInit(), ElementContainerZone.OnLevelUp(), TraitBlueprint.OnRead(), TraitBookSkill.OnRead(), TraitDeedRelocate.OnRead(), AM_Adv.OnRenderTile(), GoalSleep.OnSimulatePosition(), TraitFloorSwitch.OnStepped(), TraitBookResident.OnUse(), TraitFarmChest.OnUse(), TraitPolicyBoard.OnUse(), ActRestrain.Perform(), GrowSystem.PopHarvest(), ActEffect.Proc(), Map.PutAway(), ContentHomeRanking.Refresh(), UIInventory.RefreshMenu(), AI_Eat.Run(), AI_Idle.Run(), WidgetSearch.Search(), Card.SetPlaceState(), TraitTicketFurniture.SetZone(), TraitGeneratorWheel.ShouldWork(), Simulate(), Card.SpawnLoot(), Chara.Tick(), TaskDump.TryPerform(), GrowSystem.TryPopSeed(), TraitBed.TrySetAct(), TraitBuildBoard.TrySetAct(), TraitCoreZone.TrySetAct(), TraitCrafter.TrySetAct(), TraitFactionBoard.TrySetAct(), TraitHomeBoard.TrySetAct(), TraitHouseBoard.TrySetAct(), TraitMapBoard.TrySetAct(), TraitPaintBoard.TrySetAct(), TraitResearchBoard.TrySetAct(), TraitResidentBoard.TrySetAct(), TraitRoomPlate.TrySetAct(), TraitSwitch.TrySetAct(), TraitWaystone.TrySetAct(), TraitSalesTag.TrySetHeldAct(), Trait.TrySetToggleAct(), Map.TryShatter(), AI_Shopping.TryShop(), TraitTeleporter.TryTeleport(), GoalCombat.TryUseAbility(), TraitGeneratorWheel.Update(), GameUpdater.Update100ms(), and Chara.Vomit().
IsReturnLocation
virtual bool Zone.IsReturnLocation get
Definition at line 584 of file Zone.cs.
    {
        get
        {
            return EClass.pc.homeZone == this || base.source.tag.Contains("return");
        }
    }
IsSkyLevel
virtual bool Zone.IsSkyLevel get
Definition at line 368 of file Zone.cs.
    {
        get
        {
            return base.lv > 0;
        }
    }
Referenced by BaseTileMap.Draw(), ZonePreEnterDigStairs.Execute(), TaskDig.GetHitResult(), Map.MineFloor(), and TaskDig.OnProgressComplete().
IsStartZone
bool Zone.IsStartZone get
Definition at line 772 of file Zone.cs.
    {
        get
        {
            return this == EClass.game.StartZone;
        }
    }
IsTown
virtual bool Zone.IsTown get
Definition at line 288 of file Zone.cs.
    {
        get
        {
            return false;
        }
    }
Referenced by Activate(), QuestManager.HasFarAwayEscort(), Quest.ListDeliver(), Chara.MakeAlly(), QuestRandom.OnDropReward(), TraitLeverBreaker.OnToggle(), AI_Idle.Run(), GoalIdle.Run(), WidgetSearch.Search(), TraitTicketFurniture.SetZone(), TraitWaystone.TrySetAct(), and GoalCombat.TryUseAbility().
IsUserZone
virtual bool Zone.IsUserZone get
Definition at line 376 of file Zone.cs.
    {
        get
        {
            return false;
        }
    }
Referenced by ActPlan._Update(), GrowSystem.ApplySeed(), TraitPowerStatue.CanUse(), Deactivate(), Card.Die(), Chara.MakeMilk(), TraitSeed.MakeSeed(), TraitGeneMachine.OnUse(), SerializedCards.Restore(), AI_PlayMusic.Run(), ActWait.SearchMedal(), Card.SpawnLoot(), ActThrow.Throw(), AI_PlayMusic.ThrowReward(), ConChampagne.Tick(), TraitCoreZone.TrySetAct(), and TraitWaystone.TrySetAct().
KeepAllyDistance
virtual bool Zone.KeepAllyDistance get
Definition at line 456 of file Zone.cs.
    {
        get
        {
            return this.HasLaw || this.IsPCFaction;
        }
    }
Referenced by Chara._Move(), and ConfigTactics.AllyDistance().
LockExit
virtual bool Zone.LockExit get
Definition at line 392 of file Zone.cs.
    {
        get
        {
            return true;
        }
    }
Referenced by MapGenDungen.OnGenerateTerrain().
MakeEnemiesNeutral
virtual bool Zone.MakeEnemiesNeutral get
Definition at line 320 of file Zone.cs.
    {
        get
        {
            return this.IsTown || this.HasLaw;
        }
    }
MakeTownProperties
virtual bool Zone.MakeTownProperties get
Definition at line 328 of file Zone.cs.
    {
        get
        {
            return this.HasLaw;
        }
    }
Referenced by Activate().
MaxLv
virtual int Zone.MaxLv get
Definition at line 408 of file Zone.cs.
    {
        get
        {
            return 99999;
        }
    }
MaxRespawn
int Zone.MaxRespawn get
Definition at line 472 of file Zone.cs.
    {
        get
        {
            return (int)((float)this.MaxSpawn * this.RespawnRate) + 1;
        }
    }
MaxSpawn
virtual int Zone.MaxSpawn get
Definition at line 464 of file Zone.cs.
    {
        get
        {
            return this.map.bounds.Width * this.map.bounds.Height / 175 + 2;
        }
    }
MinLv
virtual int Zone.MinLv get
Definition at line 416 of file Zone.cs.
    {
        get
        {
            return -99999;
        }
    }
MinsSinceLastActive
int Zone.MinsSinceLastActive get
Definition at line 54 of file Zone.cs.
    {
        get
        {
            return EClass.world.date.GetElapsedMins(base.lastActive);
        }
    }
Referenced by Simulate().
NameSuffix
override string Zone.NameSuffix get
Definition at line 703 of file Zone.cs.
    {
        get
        {
            if (!this.IsNefia || !this.GetTopZone().isConquered)
            {
                return "";
            }
            return "conquered".lang();
        }
    }
NameWithLevel
string Zone.NameWithLevel get
Definition at line 715 of file Zone.cs.
    {
        get
        {
            return this.Name + this.TextLevel(base.lv);
        }
    }
Referenced by WidgetDate._Refresh(), and Activate().
OreChance
virtual float Zone.OreChance get
Definition at line 488 of file Zone.cs.
    {
        get
        {
            return 1f;
        }
    }
ParentZone
Zone Zone.ParentZone get
Definition at line 188 of file Zone.cs.
    {
        get
        {
            return this.parent as Zone;
        }
    }
Referenced by Player.ExitBorder(), Player.OnExitBorder(), TraitWaystone.OnUse(), TraitCoreZone.TrySetAct(), and TraitWaystone.TrySetAct().
pathExport
virtual string Zone.pathExport get
Definition at line 62 of file Zone.cs.
    {
        get
        {
            return CorePath.ZoneSave + this.idExport.IsEmpty("_new") + ".z";
        }
    }
Referenced by Activate().
pathTemp
string Zone.pathTemp get
Definition at line 172 of file Zone.cs.
    {
        get
        {
            return GameIO.pathTemp + base.uid.ToString() + "/";
        }
    }
Referenced by PartialMap._Load(), _OnBeforeSave(), and Activate().
PetFollow
virtual bool Zone.PetFollow get
Definition at line 440 of file Zone.cs.
    {
        get
        {
            return true;
        }
    }
Referenced by Chara._Move(), and AI_Idle.Run().
PrespawnRate
virtual float Zone.PrespawnRate get
Definition at line 520 of file Zone.cs.
    {
        get
        {
            return 0f;
        }
    }
RegenerateOnEnter
virtual bool Zone.RegenerateOnEnter get
Definition at line 360 of file Zone.cs.
    {
        get
        {
            return false;
        }
    }
Referenced by Activate(), and TraitNewZone.TrySetAct().
Region
Region Zone.Region get
Definition at line 180 of file Zone.cs.
    {
        get
        {
            return (this as Region) ?? (this.parent as Region);
        }
    }
Referenced by LayerSleep.Advance(), GameDate.AdvanceHour(), SpatialGen.CreateInstance(), Player.EnterLocalZone(), GetProfile(), MapGenRegion.OnGenerateTerrain(), LayerTravel.Refresh(), LayerGlobalMap.RefreshSummary(), ContentFaction.RefreshZones(), LayerFactions.RefreshZones(), LayerLocation.RefreshZones(), and RegionPoint.SetRegionPoint().
RegionEnterState
virtual ZoneTransition.EnterState Zone.RegionEnterState get
Definition at line 220 of file Zone.cs.
    {
        get
        {
            return ZoneTransition.EnterState.Dir;
        }
    }
Referenced by Player.EnterLocalZone(), GetSpawnPos(), and LayerTravel.Refresh().
RespawnPerHour
virtual int Zone.RespawnPerHour get
Definition at line 544 of file Zone.cs.
    {
        get
        {
            return this.MaxSpawn / 5 + 1;
        }
    }
RespawnRate
virtual float Zone.RespawnRate get
Definition at line 528 of file Zone.cs.
    {
        get
        {
            return this.PrespawnRate * 0.5f;
        }
    }
RestrictBuild
virtual bool Zone.RestrictBuild get
Definition at line 448 of file Zone.cs.
    {
        get
        {
            return this is Zone_Civilized && !this.IsPCFaction;
        }
    }
Referenced by HotItemHeld.CanRotate(), and TaskBuild.GetHitResult().
RevealRoom
virtual bool Zone.RevealRoom get
Definition at line 624 of file Zone.cs.
    {
        get
        {
            return false;
        }
    }
Referenced by Activate().
RuinChance
virtual float Zone.RuinChance get
Definition at line 480 of file Zone.cs.
    {
        get
        {
            return 0.1f;
        }
    }
Referenced by GenBounds.TryAddMapPiece().
ScaleMonsterLevel
virtual bool Zone.ScaleMonsterLevel get
Definition at line 656 of file Zone.cs.
    {
        get
        {
            return false;
        }
    }
ShouldAutoRevive
virtual bool Zone.ShouldAutoRevive get
Definition at line 608 of file Zone.cs.
    {
        get
        {
            return this.ShouldRegenerate || this.IsPCFaction;
        }
    }
Referenced by Revive().
ShouldMakeExit
virtual bool Zone.ShouldMakeExit get
Definition at line 592 of file Zone.cs.
    {
        get
        {
            return base.lv > this.MinLv && base.lv < this.MaxLv;
        }
    }
Referenced by MapGenDungen.OnGenerateTerrain().
ShouldRegenerate
virtual bool Zone.ShouldRegenerate get
Definition at line 600 of file Zone.cs.
    {
        get
        {
            return false;
        }
    }
ShowEnemyOnMinimap
bool Zone.ShowEnemyOnMinimap get
Definition at line 536 of file Zone.cs.
    {
        get
        {
            return this.instance != null && this.instance.ShowEnemyOnMinimap;
        }
    }
Referenced by WidgetMinimap.RefreshMarkers().
ShrineChance
virtual float Zone.ShrineChance get
Definition at line 512 of file Zone.cs.
    {
        get
        {
            return 0f;
        }
    }
StartLV
virtual int Zone.StartLV get
Definition at line 648 of file Zone.cs.
    {
        get
        {
            return 0;
        }
    }
Referenced by OnCreate().
TextDeepestLv
string Zone.TextDeepestLv get
Definition at line 736 of file Zone.cs.
    {
        get
        {
            if (this.GetDeepestLv() != 0)
            {
                return "zoneLevelMax".lang(this.TextLevel(this.GetDeepestLv()), null, null, null, null);
            }
            return "";
        }
    }
Referenced by AM_Adv._OnUpdateInput().
TextWidgetDate
virtual string Zone.TextWidgetDate get
Definition at line 104 of file Zone.cs.
    {
        get
        {
            return "";
        }
    }
Referenced by WidgetDate._Refresh().
UseFog
virtual bool Zone.UseFog get
Definition at line 616 of file Zone.cs.
    {
        get
        {
            return base.lv < 0;
        }
    }
Referenced by Activate(), BaseTileMap.DrawTile(), and Fov.Perform().
UseLight
virtual bool Zone.UseLight get
Definition at line 640 of file Zone.cs.
    {
        get
        {
            return base.mainFaction == EClass.pc.faction || base.source.tag.Contains("light");
        }
    }
Referenced by EloMap.Init(), and EloMap.SetZone().
WillAutoSave
virtual bool Zone.WillAutoSave get
Definition at line 352 of file Zone.cs.
    {
        get
        {
            return true;
        }
    }
Referenced by Chara.MoveZone().
The documentation for this class was generated from the following file:
Elin/Zone.cs