Elin Decompiled Documentation: Task Class Reference
Task Class Reference
Public Member Functions
virtual HitResult GetHitResult ()
override void OnSuccess ()
void TryLater (int min=30)
Status Destroy ()
virtual void OnDestroy ()
override Status Cancel ()
override void OnReset ()
override bool CanProgress ()
bool CanPerformTask (Chara chara, int radius)
virtual bool _CanPerformTask (Chara chara, int radius)
virtual void OnAdd ()
void ToggleSuspend ()
Public Member Functions inherited from AIAct
override string ToString ()
override MultiSprite GetStateIcon ()
virtual bool ShouldAllyAttack (Chara tg)
virtual Point GetDestination ()
AIProgress GetProgress ()
string GetCurrentActionText ()
override bool IsToolValid ()
virtual void OnStart ()
void SetOwner (Chara c)
virtual void OnSetOwner ()
void SetChild (AIAct seq, Func< Status > _onChildFail=null)
void Start ()
override bool Perform ()
Status Restart ()
Status Success (Action action=null)
virtual void OnSuccess ()
bool TryCancel (Card c)
virtual Status Cancel ()
virtual void OnCancel ()
virtual void OnCancelOrSuccess ()
virtual bool CanManualCancel ()
Status KeepRunning ()
void Reset ()
virtual void OnReset ()
Status Tick ()
virtual IEnumerable< Status > Run ()
Status TickChild ()
Status Do (AIAct _seq, Func< Status > _onChildFail=null)
Status DoGotoInteraction (Point pos, Func< Status > _onChildFail=null)
Status DoGoto (Point pos, int dist=0, bool ignoreConnection=false, Func< Status > _onChildFail=null)
Status DoGoto (Card card, Func< Status > _onChildFail=null)
Status DoGoto (Card card, int dist, Func< Status > _onChildFail=null)
Status DoGotoSpot (Card card, Func< Status > _onChildFail=null)
Status DoGoto< T > (Func< Status > _onChildFail=null)
Status DoGotoSpot< T > (Func< Status > _onChildFail=null, bool ignoreAccessType=false)
Status DoGrab (Card card, int num=-1, bool pickHeld=false, Func< Status > _onChildFail=null)
Status DoGrab< T > ()
Status DoProgress ()
Status DoIdle (int repeat=3)
Status DoWait (int count=1)
virtual AIProgress CreateProgress ()
virtual void OnCreateProgress (Progress_Custom p)
virtual bool CanProgress ()
virtual void OnBeforeProgress ()
virtual void OnProgress ()
virtual void OnProgressComplete ()
void SimulateZone (int days)
virtual void OnSimulateZone (int days)
virtual void OnSimulatePosition ()
Public Member Functions inherited from Act
virtual CursorInfo GetCursorIcon (Card c)
virtual MultiSprite GetStateIcon ()
override Sprite GetSprite ()
virtual bool ShowMouseHint (Card c)
virtual bool IsValidTC (Card c)
virtual string GetHintText (string str="")
virtual string GetText (string str="")
virtual string GetTextSmall (Card c)
bool IsTargetHostileParty ()
virtual Color GetActPlanColor ()
virtual bool Perform ()
virtual bool CanPerform ()
bool Perform (Chara _cc, Card _tc=null, Point _tp=null)
bool CanPerform (Chara _cc, Card _tc=null, Point _tp=null)
virtual bool IsToolValid ()
new void SetImage (Image image)
virtual void OnMarkMapHighlights ()
virtual bool ShouldMapHighlight (Point p)
Public Member Functions inherited from Element
virtual SourceElement.Row GetSource ()
virtual int GetSourcePotential (int v)
virtual Sprite GetSprite ()
int GetMaterialSourceValue (Thing t, int v)
virtual long GetSourceValue (long v, int lv, SourceValueType type)
virtual Sprite GetIcon (string suffix="")
bool IsActive (Card c)
int SortVal (bool charaSheet=false)
virtual bool CanLink (ElementContainer owner)
bool HasTag (string tag)
void SetImage (Image i)
virtual string GetDetail ()
bool IsFactionElement (Chara c)
Element GetParent (Card c)
void WriteNote (UINote n, ElementContainer owner=null, Action< UINote > onWriteNote=null)
void WriteNoteWithRef (UINote n, ElementContainer owner, Action< UINote > onWriteNote, Element refEle)
void _WriteNote (UINote n, Chara c, Act act)
void AddHeaderAbility (UINote n)
void _WriteNote (UINote n, ElementContainer owner, Action< UINote > onWriteNote, bool isRef, bool addHeader=true)
void AddEncNote (UINote n, Card Card, ElementContainer.NoteMode mode=ElementContainer.NoteMode.Default, Func< Element, string, string > funcText=null, Action< UINote, Element > onAddNote=null)
virtual void OnWriteNote (UINote n, ElementContainer owner)
virtual void OnChangeValue ()
void CheckLevelBonus (ElementContainer owner, UINote n=null)
int GetSortVal (UIList.SortMode m)
virtual Act.Cost GetCost (Chara c)
virtual int GetPower (Card c)
virtual void SetTextValue (UIText text)
virtual bool IsPurchaseFeatReqMet (ElementContainer owner, int lv=-1)
virtual void WritePurchaseReq (UINote n, int lv=1)
Public Attributes
TaskList taskList
bool isDestroyed
int nextTry
bool suspended
Public Attributes inherited from AIAct
new Chara owner
Status status
IEnumerator< Status > Enumerator
AIAct child
AIAct parent
byte restartCount
Func< Status > onChildFail
Func< bool > isFail
Public Attributes inherited from Element
SourceElement.Row _source
int id
int vBase
int vExp
int vPotential
int vTempPotential
int vLink
int vSource
int vSourcePotential
ElementContainer owner
Properties
override TargetType TargetType [get]
Properties inherited from AIAct
virtual bool IsRunning [get]
bool IsChildRunning [get]
bool IsMoveAI [get]
virtual int MaxRestart [get]
virtual new string Name [get]
virtual MultiSprite stateIcon [get]
virtual Sprite actionIcon [get]
virtual bool IsNoGoal [get]
virtual bool IsAutoTurn [get]
virtual bool IsIdle [get]
virtual bool CancelOnAggro [get]
virtual bool PushChara [get]
virtual int MaxProgress [get]
virtual bool ShowProgress [get]
virtual bool UseTurbo [get]
virtual int CurrentProgress [get]
virtual bool ShowCursor [get]
virtual bool CancelWhenDamaged [get]
virtual bool CancelWhenMoved [get]
virtual bool InformCancel [get]
virtual Thing RenderThing [get]
AIAct Current [get]
override bool IsAct [get]
override bool ShowPotential [get]
override bool UsePotential [get]
override bool ShowRelativeAttribute [get]
virtual bool HasProgress [get]
Properties inherited from Act
override bool ShowPotential [get]
override bool UsePotential [get]
override bool ShowRelativeAttribute [get]
virtual CursorInfo CursorIcon [get]
virtual string ID [get]
virtual bool IsAct [get]
virtual bool WillEndTurn [get]
virtual bool CloseLayers [get]
virtual int LeftHand [get]
virtual int RightHand [get]
virtual int ElementPowerMod [get]
virtual bool ShowMapHighlight [get]
virtual bool ShowMapHighlightBlock [get]
virtual bool PickHeldOnStart [get]
virtual bool DropHeldOnStart [get]
virtual bool CanPressRepeat [get]
virtual bool CanAutofire [get]
virtual bool ResetAxis [get]
virtual bool RequireTool [get]
virtual bool IsHostileAct [get]
virtual bool HideRightInfo [get]
virtual bool HaveLongPressAction [get]
virtual float Radius [get]
virtual int PerformDistance [get]
virtual int MaxRadius [get]
virtual TargetType TargetType [get]
virtual bool LocalAct [get]
virtual bool CanRapidFire [get]
virtual float RapidDelay [get]
virtual bool ShowAuto [get]
virtual bool IsCrime [get]
Properties inherited from Element
SourceElement.Row source [get]
virtual int DisplayValue [get]
virtual int MinValue [get]
int Value [get]
int ValueWithoutLink [get]
virtual int MinPotential [get]
int Potential [get]
virtual bool CanGainExp [get]
bool IsFlag [get]
virtual string Name [get]
virtual string FullName [get]
virtual int ExpToNext [get]
virtual bool UseExpMod [get]
virtual int CostTrain [get]
virtual int CostLearn [get]
virtual bool ShowXP [get]
virtual bool ShowMsgOnValueChanged [get]
virtual bool ShowValue [get]
virtual bool ShowPotential [get]
virtual bool UsePotential [get]
virtual bool PotentialAsStock [get]
virtual bool ShowRelativeAttribute [get]
virtual bool ShowBonuses [get]
virtual string ShortName [get]
bool IsGlobalElement [get]
bool IsFactionWideElement [get]
bool IsPartyWideElement [get]
virtual bool ShowEncNumber [get]
bool IsTrait [get]
bool IsFoodTrait [get]
bool IsFoodTraitMain [get]
bool IsMainAttribute [get]
Act act [get]
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Additional Inherited Members
Public Types inherited from AIAct
enum Status { Running , Fail , Success }
Public Types inherited from Act
enum CostType { None , MP , SP }
Static Public Member Functions inherited from Act
static void SetReference (Chara _cc, Card _tc=null, Point _tp=null)
static void SetTool (Thing t)
Static Public Member Functions inherited from Element
static string GetName (string alias)
static SourceElement.Row Get (int id)
static Dictionary< int, int > GetElementMap (int[] list)
static Dictionary< int, int > GetElementMap (int[] list, Dictionary< int, int > map)
static SourceElement.Row GetRandomElement (int lv=1, bool useWeight=true)
static Element Create (int id, int v=0)
static Element Create (string id, int v=1)
static int GetId (string alias)
static int GetResistLv (int v)
static int GetResistDamage (int dmg, int v, int power=0)
Static Public Member Functions inherited from EClass
static int rndSeed (int a, int seed)
static int rnd (long a)
static int rnd (int a)
static int curve (int _a, int start, int step, int rate=75)
static int sqrt (int a)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Static Public Attributes inherited from Act
static Chara CC
static Card TC
static Point TP = new Point()
static Thing TOOL
static int powerMod = 100
static bool forcePt
static Act CurrentAct
Static Public Attributes inherited from Element
const int Div = 5
static Element Void = new Element()
static int[] List_MainAttributes = new int[9] { 70, 72, 71, 77, 74, 75, 76, 73, 79 }
static int[] List_MainAttributesMajor = new int[8] { 70, 72, 71, 77, 74, 75, 76, 73 }
static int[] List_Body = new int[4] { 70, 72, 71, 77 }
static int[] List_Mind = new int[4] { 74, 75, 76, 73 }
static List< SourceElement.Row > ListElements = new List<SourceElement.Row>()
static List< SourceElement.Row > ListAttackElements = new List<SourceElement.Row>()
Static Public Attributes inherited from EClass
static Core core
Detailed Description
Definition at line 3 of file Task.cs.
Member Function Documentation
_CanPerformTask()
virtual bool Task._CanPerformTask (Chara chara, int radius) inline virtual
Reimplemented in TaskBuild, TaskCraft, and TaskPoint.
Definition at line 91 of file Task.cs.
    {
        return true;
    }
Referenced by CanPerformTask().
Cancel()
override Status Task.Cancel () inline virtual
Reimplemented from AIAct.
Definition at line 54 of file Task.cs.
    {
        TryLater();
        return base.Cancel();
    }
References TryLater().
Referenced by AI_HaulResource.Run(), TaskClean.Run(), TaskCraft.Run(), TaskCullLife.Run(), TaskMoveInstalled.Run(), TaskPoint.Run(), TaskWater.Run(), and ToggleSuspend().
CanPerformTask()
bool Task.CanPerformTask (Chara chara, int radius) inline
Definition at line 82 of file Task.cs.
    {
        if (!suspended)
        {
            return _CanPerformTask(chara, radius);
        }
        return false;
    }
References _CanPerformTask(), and suspended.
CanProgress()
override bool Task.CanProgress () inline virtual
Reimplemented from AIAct.
Reimplemented in TaskChopWood, TaskCraft, TaskDrawWater, TaskHarvest, TaskPlow, and TaskPourWater.
Definition at line 68 of file Task.cs.
    {
        if (isDestroyed)
        {
            return false;
        }
        HitResult hitResult = GetHitResult();
        if (hitResult != HitResult.Valid)
        {
            return hitResult == HitResult.Warning;
        }
        return true;
    }
References GetHitResult(), and isDestroyed.
Referenced by HotItemHeld.OnRenderTile(), and TaskPoint.Run().
Destroy()
Status Task.Destroy () inline
Definition at line 31 of file Task.cs.
    {
        if (status == Status.Running)
        {
            status = Status.Fail;
        }
        if (isDestroyed)
        {
            return status;
        }
        isDestroyed = true;
        if (taskList != null)
        {
            taskList.Remove(this);
        }
        OnDestroy();
        return status;
    }
References isDestroyed, OnDestroy(), TaskList< T >.Remove(), AIAct.status, and taskList.
Referenced by AM_Build.OnProcessTiles(), Area.OnRemove(), FactoryData.OnRemoveFromMap(), InspectGroupBlock.OnSetActions(), InspectGroupObj.OnSetActions(), InspectGroupTask.OnSetActions(), OnSuccess(), TaskMoveInstalled.Run(), TaskPoint.Run(), AM_MoveInstalled.SetTarget(), and TaskManager.Designations.TryRemoveDesignation().
GetHitResult()
virtual HitResult Task.GetHitResult () inline virtual
Reimplemented in TaskBuild, TaskChopWood, TaskCut, TaskDig, TaskDrawWater, TaskHarvest, TaskMine, TaskMoveInstalled, TaskPlow, and TaskPourWater.
Definition at line 16 of file Task.cs.
    {
        return HitResult.Valid;
    }
Referenced by TaskPoint.CanPerform(), and CanProgress().
OnAdd()
virtual void Task.OnAdd () inline virtual
Reimplemented in TaskBuild.
Definition at line 96 of file Task.cs.
    {
    }
OnDestroy()
virtual void Task.OnDestroy () inline virtual
Reimplemented in TaskBuild.
Definition at line 50 of file Task.cs.
    {
    }
Referenced by Destroy().
OnReset()
override void Task.OnReset () inline virtual
Reimplemented from AIAct.
Definition at line 60 of file Task.cs.
    {
        if (!isDestroyed && taskList != null)
        {
            taskList.SetAstLastItem(this);
        }
    }
References isDestroyed, TaskList< T >.SetAstLastItem(), and taskList.
OnSuccess()
override void Task.OnSuccess () inline virtual
Reimplemented from AIAct.
Definition at line 21 of file Task.cs.
    {
        Destroy();
    }
References Destroy().
ToggleSuspend()
void Task.ToggleSuspend () inline
Definition at line 100 of file Task.cs.
    {
        suspended = !suspended;
        if (suspended && IsRunning)
        {
            Cancel();
        }
    }
References Cancel(), AIAct.IsRunning, and suspended.
TryLater()
void Task.TryLater (int min = 30) inline
Definition at line 26 of file Task.cs.
    {
        nextTry = EClass.game.sessionMin + min;
    }
References nextTry.
Referenced by TaskBuild._CanPerformTask(), and Cancel().
Member Data Documentation
isDestroyed
bool Task.isDestroyed
Definition at line 7 of file Task.cs.
Referenced by CanProgress(), Destroy(), and OnReset().
nextTry
int Task.nextTry
Definition at line 9 of file Task.cs.
Referenced by TryLater().
suspended
bool Task.suspended
Definition at line 12 of file Task.cs.
Referenced by CanPerformTask(), and ToggleSuspend().
taskList
TaskList Task.taskList
Definition at line 5 of file Task.cs.
Referenced by Destroy(), and OnReset().
Property Documentation
TargetType
override TargetType Task.TargetType get
Definition at line 14 of file Task.cs.
The documentation for this class was generated from the following file:
Elin/Task.cs