Elin Decompiled Documentation: GameLang Class Reference
GameLang Class Reference
Static Public Member Functions
static string ConvertDrama (string text, Chara c=null)
static string Convert (string text)
static string Convert (StringBuilder sb)
static string Parse (string text, bool thirdPerson, string val1, string val2=null, string val3=null, string val4=null)
static string ConvertThirdPerson (string text, bool thirdPerson)
Static Public Member Functions inherited from EClass
static int rndSeed (int a, int seed)
static int rnd (long a)
static int rnd (int a)
static int curve (int a, int start, int step, int rate=75)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Static Public Attributes
static string refDrama1
static string refDrama2
static string refDrama3
static string refDrama4
Static Public Attributes inherited from EClass
static Core core
Additional Inherited Members
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Detailed Description
Definition at line 4 of file GameLang.cs.
Member Function Documentation
Convert() [1/2]
static string GameLang.Convert (string text) inline static
Definition at line 124 of file GameLang.cs.
    {
        StringBuilder stringBuilder = new StringBuilder();
        stringBuilder.Append(text);
        return Convert(stringBuilder);
    }
References Convert().
Referenced by LayerDrama.ActivateNerun(), PopupManager.Add(), Convert(), ConvertDrama(), ConvertThirdPerson(), Quest.GetDetail(), QuestProgression.GetDetail(), Msg.Nerun(), Parse(), Msg.SayHomeMember(), Msg.SayPic(), Msg.Talk(), and WidgetFeed.Talk().
Convert() [2/2]
static string GameLang.Convert (StringBuilder sb) inline static
Definition at line 131 of file GameLang.cs.
    {
        sb.Replace("#player", EClass.player.title);
        sb.Replace("#pc_him", EClass.pc.IsMale ? "him".lang() : "her".lang());
        sb.Replace("#pc_his", EClass.pc.IsMale ? "his".lang() : "her".lang());
        sb.Replace("#pc_race", EClass.pc.race.GetName());
        sb.Replace("#pc", EClass.pc.NameSimple);
        return sb.ToString();
    }
References Card.IsMale, Card.NameSimple, EClass.pc, EClass.player, Chara.race, and Player.title.
ConvertDrama()
static string GameLang.ConvertDrama (string text, Chara c = null) inline static
Definition at line 14 of file GameLang.cs.
    {
        if (!EClass.core.IsGameStarted)
        {
            return text;
        }
        StringBuilder stringBuilder = new StringBuilder();
        string newValue = "";
        string newValue2 = "";
        string name = EClass.game.religions.GetRandomReligion(onlyJoinable: false).Name;
        string @ref = "-";
        if (c != null)
        {
            newValue = c.NameBraced;
            newValue2 = (c.IsMale ? "his" : "her").lang();
            name = c.faith.Name;
            @ref = CalcGold.Hire(c).ToString() ?? "";
        }
        bool flag = false;
        string text2 = "";
        for (int i = 0; i < text.Length; i++)
        {
            if (flag)
            {
                if (text[i] == ']')
                {
                    flag = false;
                    if (text2 == "qFriend" && EClass._zone.IsPCFaction)
                    {
                        text2 = "qFriendHome";
                    }
                    string[] list = Lang.GetList(text2);
                    if (list != null)
                    {
                        stringBuilder.Append(list.RandomItem());
                    }
                    else
                    {
                        stringBuilder.Append(text2);
                    }
                }
                else
                {
                    text2 += text[i];
                }
            }
            else if (text[i] == '[')
            {
                text2 = "";
                flag = true;
            }
            else
            {
                stringBuilder.Append(text[i]);
            }
        }
        if (DramaManager.TG != null)
        {
            stringBuilder.Replace("#tg", DramaManager.TG.Name);
        }
        if (DramaChoice.lastChoice != null)
        {
            stringBuilder.Replace("#last_choice", DramaChoice.lastChoice.text);
        }
        stringBuilder.Replace("#newline", Environment.NewLine);
        stringBuilder.Replace("#costHire", "costHire".lang(@ref));
        stringBuilder.Replace("#self", newValue);
        stringBuilder.Replace("#his", newValue2);
        stringBuilder.Replace("#me", newValue);
        if (int.TryParse(refDrama1, out var result))
        {
            refDrama1 = result.ToFormat();
        }
        if (int.TryParse(refDrama2, out var result2))
        {
            refDrama2 = result2.ToFormat();
        }
        if (int.TryParse(refDrama3, out var result3))
        {
            refDrama3 = result3.ToFormat();
        }
        if (int.TryParse(refDrama4, out var result4))
        {
            refDrama4 = result4.ToFormat();
        }
        stringBuilder.Replace("#1", refDrama1);
        stringBuilder.Replace("#2", refDrama2);
        stringBuilder.Replace("#3", refDrama3);
        stringBuilder.Replace("#4", refDrama4);
        stringBuilder.Replace("#god", name);
        stringBuilder.Replace("#player", EClass.player.title);
        stringBuilder.Replace("#title", EClass.player.title);
        stringBuilder.Replace("#zone", EClass._zone.Name);
        stringBuilder.Replace("#guild_title", Guild.CurrentDrama.relation.TextTitle);
        stringBuilder.Replace("#guild", Guild.CurrentDrama.Name);
        stringBuilder.Replace("#race", EClass.pc.race.GetName());
        stringBuilder.Replace("#pc", EClass.pc.NameSimple);
        stringBuilder.Replace("#aka", EClass.pc.Aka);
        stringBuilder.Replace("#bigdaddy", "bigdaddy".lang());
        stringBuilder.Replace("#festival", EClass._zone.IsFestival ? (EClass._zone.id + "_festival").lang() : "_festival".lang());
        stringBuilder.Replace("#brother2", (EClass.pc.IsMale ? "brother" : "sister").lang());
        stringBuilder.Replace("#brother", Lang.GetList(EClass.pc.IsMale ? "bro" : "sis").RandomItem());
        stringBuilder.Replace("#onii2", Lang.GetList(EClass.pc.IsMale ? "onii2" : "onee2").RandomItem());
        stringBuilder.Replace("#onii", Lang.GetList(EClass.pc.IsMale ? "onii" : "onee").RandomItem());
        stringBuilder.Replace("#gender", Lang.GetList("gendersDrama")[EClass.pc.bio.gender]);
        stringBuilder.Replace("#he", ((EClass.pc.bio.gender == 2) ? "he" : "she").lang());
        stringBuilder.Replace("#He", ((EClass.pc.bio.gender == 2) ? "he" : "she").lang().ToTitleCase());
        return Convert(stringBuilder);
    }
References EClass._zone, Chara.Aka, Card.bio, Convert(), EClass.core, Guild.CurrentDrama, EClass.game, Biography.gender, Lang.GetList(), ReligionManager.GetRandomReligion(), CalcGold.Hire(), Spatial.id, Zone.IsFestival, Core.IsGameStarted, Card.IsMale, Zone.IsPCFaction, DramaChoice.lastChoice, Card.Name, Faction.Name, Religion.Name, Spatial.Name, Card.NameSimple, EClass.pc, EClass.player, Chara.race, refDrama1, refDrama2, refDrama3, refDrama4, Faction.relation, Game.religions, DramaChoice.text, FactionRelation.TextTitle, DramaManager.TG, and Player.title.
Referenced by Card.ApplyTone(), Quest.Parse(), DramaActor.SetChoice(), and DramaActor.Talk().
ConvertThirdPerson()
static string GameLang.ConvertThirdPerson (string text, bool thirdPerson) inline static
Definition at line 206 of file GameLang.cs.
    {
        string[] array = text.Split(' ');
        StringBuilder stringBuilder = new StringBuilder();
        bool flag = true;
        string[] array2 = array;
        foreach (string text2 in array2)
        {
            if (flag)
            {
                flag = false;
            }
            else
            {
                stringBuilder.Append(' ');
            }
            if (text2.Contains('/') && !text2.Contains('<'))
            {
                string[] array3 = text2.Split('/');
                stringBuilder.Append(thirdPerson ? array3[1] : array3[0]);
            }
            else
            {
                stringBuilder.Append(text2);
            }
        }
        stringBuilder.Replace("(s)", thirdPerson ? "s" : "");
        stringBuilder.Replace("(es)", thirdPerson ? "es" : "");
        return Convert(stringBuilder);
    }
References Convert().
Referenced by Parse().
Parse()
static string GameLang.Parse (string text, bool thirdPerson, string val1, string val2 = null, string val3 = null, string val4 = null) inline static
Definition at line 141 of file GameLang.cs.
    {
        StringBuilder stringBuilder = new StringBuilder(text);
        if (val1 != null)
        {
            if (Lang.articlesToRemove.Count > 0)
            {
                string text2 = val1;
                foreach (char[] item in Lang.articlesToRemove)
                {
                    text2 = text2.TrimStart(item);
                }
                stringBuilder.Replace("-#1", text2);
            }
            stringBuilder.Replace("#1", val1 ?? "");
        }
        if (val2 != null)
        {
            if (Lang.articlesToRemove.Count > 0)
            {
                string text3 = val2;
                foreach (char[] item2 in Lang.articlesToRemove)
                {
                    text3 = text3.TrimStart(item2);
                }
                stringBuilder.Replace("-#2", text3);
            }
            stringBuilder.Replace("#2", val2);
        }
        if (val3 != null)
        {
            stringBuilder.Replace("#3", val3);
        }
        if (val4 != null)
        {
            stringBuilder.Replace("#4", val4);
        }
        if (int.TryParse(val1, out var result))
        {
            stringBuilder.Replace("#(s)", (result <= 1) ? "" : "_s".lang());
        }
        if (Msg.thirdPerson2.active)
        {
            stringBuilder.Replace("#your2", Msg.thirdPerson2.your);
            stringBuilder.Replace("#himself2", Msg.thirdPerson2.himself);
            stringBuilder.Replace("#him2", Msg.thirdPerson2.him);
            stringBuilder.Replace("#his2", Msg.thirdPerson2.his);
            stringBuilder.Replace("#he2", Msg.thirdPerson2.he);
            stringBuilder.Replace("(s2)", Msg.thirdPerson2.thirdperson ? "s" : "");
        }
        if (Msg.thirdPerson1.active)
        {
            stringBuilder.Replace("#your", Msg.thirdPerson1.your);
            stringBuilder.Replace("#himself", Msg.thirdPerson1.himself);
            stringBuilder.Replace("#him", Msg.thirdPerson1.him);
            stringBuilder.Replace("#his", Msg.thirdPerson1.his);
            stringBuilder.Replace("#he", Msg.thirdPerson1.he);
        }
        if (Lang.setting.thirdperson)
        {
            return ConvertThirdPerson(stringBuilder.ToString(), thirdPerson);
        }
        return Convert(stringBuilder);
    }
References ThirstPersonInfo.active, Lang.articlesToRemove, Convert(), ConvertThirdPerson(), ThirstPersonInfo.he, ThirstPersonInfo.him, ThirstPersonInfo.himself, ThirstPersonInfo.his, item, Lang.setting, LangSetting.thirdperson, ThirstPersonInfo.thirdperson, Msg.thirdPerson1, Msg.thirdPerson2, and ThirstPersonInfo.your.
Referenced by Chara.Die(), Msg.GetRawText(), Msg.Say(), and ActEffect.Wish().
Member Data Documentation
refDrama1
string GameLang.refDrama1 static
Definition at line 6 of file GameLang.cs.
Referenced by ConvertDrama().
refDrama2
string GameLang.refDrama2 static
Definition at line 8 of file GameLang.cs.
Referenced by ConvertDrama().
refDrama3
string GameLang.refDrama3 static
Definition at line 10 of file GameLang.cs.
Referenced by ConvertDrama().
refDrama4
string GameLang.refDrama4 static
Definition at line 12 of file GameLang.cs.
Referenced by ConvertDrama().
The documentation for this class was generated from the following file:
Elin/GameLang.cs