Elin Decompiled Documentation: ContentKeyItem Class Reference
ContentKeyItem Class Reference
Public Member Functions
override void OnSwitchContent (int idTab)
void SelectItem (SourceKeyItem.Row q)
Public Member Functions inherited from UIContent
virtual void OnSwitchContent (int idTab)
virtual void OnInstantiate ()
Public Member Functions inherited from UINote
void Clear ()
void Build ()
void Space (int sizeY=0, int sizeX=1)
UINote AddNote (string id)
UIItem AddHeader (string text, Sprite sprite=null)
UIItem AddHeaderCard (string text, Sprite sprite=null)
UIItem AddHeaderTopic (string text, Sprite sprite=null)
UIItem AddHeader (string id, string text, Sprite sprite=null)
UIItem AddText (string text, FontColor color=FontColor.DontChange)
UIItem AddText (string id, string text, FontColor color=FontColor.DontChange)
UIItem AddText (string id, string text, Color color)
UIItem AddItem (string id)
UIItem AddTopic (string id, string text, string value=null)
UIItem AddTopic (string text, string value=null)
void AddImage (Sprite sprite)
void AddImage (string idFile)
UIButton AddButton (string text, Action onClick)
UIButton AddButtonLink (string text, string url)
UIDropdown AddDropdown (string id="DropdownDefault")
UIButton AddToggle (string idLang="", bool isOn=false, Action< bool > action=null)
Transform AddPrefab (string path)
T AddExtra< T > (string path)
Public Attributes
UIList list
UIText textClient
UIText textTitle
UIText textDetail
Image imageItem
Public Attributes inherited from UINote
RectTransform target
UINoteProfile prof
SkinType skinType
string idDefaultText
LayoutGroup layout
RectTransform cur
bool extraRebuild
Detailed Description
Definition at line 4 of file ContentKeyItem.cs.
Member Function Documentation
OnSwitchContent()
override void ContentKeyItem.OnSwitchContent (int idTab) inline virtual
Reimplemented from UIContent.
Definition at line 16 of file ContentKeyItem.cs.
    {
        list.sortMode = UIList.SortMode.ByValue;
        list.callbacks = new UIList.Callback<SourceKeyItem.Row, ItemGeneral>
        {
            onInstantiate = delegate(SourceKeyItem.Row a, ItemGeneral b)
            {
                b.SetSound();
                b.button1.mainText.SetText(a.GetName());
                b.SetSubText(EClass.player.CountKeyItem(a.id).ToString() ?? "", 260, FontColor.Default, TextAnchor.MiddleRight);
            },
            onClick = delegate(SourceKeyItem.Row a, ItemGeneral b)
            {
                SelectItem(a);
            },
            onList = delegate
            {
                foreach (int key in EClass.player.keyItems.Keys)
                {
                    if (EClass.player.CountKeyItem(key) > 0)
                    {
                        list.Add(EClass.sources.keyItems.map[key]);
                    }
                }
            }
        };
        list.List();
        SelectItem(EClass.sources.keyItems.rows[0]);
    }
References UIList.Add(), UIItem.button1, Player.CountKeyItem(), Player.keyItems, SourceManager.keyItems, list, UIList.List(), UIButton.mainText, EClass.player, SelectItem(), ItemGeneral.SetSound(), ItemGeneral.SetSubText(), UIText.SetText(), and EClass.sources.
SelectItem()
void ContentKeyItem.SelectItem (SourceKeyItem::Row q) inline
Definition at line 46 of file ContentKeyItem.cs.
    {
        textTitle.SetText(q.GetName());
        string detail = q.GetDetail();
        textDetail.SetText(detail);
        Sprite sprite = Resources.Load<Sprite>("Media/Graphics/Image/KeyItem/" + q.alias);
        if ((bool)sprite)
        {
            imageItem.sprite = sprite;
        }
        imageItem.SetNativeSize();
        imageItem.SetActive(sprite);
        this.RebuildLayout(recursive: true);
    }
References imageItem, UIText.SetText(), textDetail, and textTitle.
Referenced by OnSwitchContent().
Member Data Documentation
imageItem
Image ContentKeyItem.imageItem
Definition at line 14 of file ContentKeyItem.cs.
Referenced by SelectItem().
list
UIList ContentKeyItem.list
Definition at line 6 of file ContentKeyItem.cs.
Referenced by OnSwitchContent().
textClient
UIText ContentKeyItem.textClient
Definition at line 8 of file ContentKeyItem.cs.
textDetail
UIText ContentKeyItem.textDetail
Definition at line 12 of file ContentKeyItem.cs.
Referenced by SelectItem().
textTitle
UIText ContentKeyItem.textTitle
Definition at line 10 of file ContentKeyItem.cs.
Referenced by SelectItem().
The documentation for this class was generated from the following file:
Elin/ContentKeyItem.cs