Elin Decompiled Documentation: ItemHomeResource Class Reference
ItemHomeResource Class Reference
Public Member Functions
void SetResource (BaseHomeResource _r)
Public Attributes
UIButton button
Image imageExp
Additional Inherited Members
Static Public Member Functions inherited from EMono
static int rnd (int a)
Static Public Attributes inherited from EMono
static Core core
Properties inherited from EMono
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SoundManager Sound [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static CoreDebug debug [get]
Detailed Description
Definition at line 3 of file ItemHomeResource.cs.
Member Function Documentation
SetResource()
void ItemHomeResource.SetResource (BaseHomeResource _r) inline
Definition at line 9 of file ItemHomeResource.cs.
    {
        switch (_r.Group)
        {
        case BaseHomeResource.ResourceGroup.Currency:
        {
            HomeResource homeResource = _r as HomeResource;
            int num2 = homeResource.value - homeResource.lastValue;
            FontColor fontColor = ((num2 == 0) ? FontColor.Passive : ((num2 > 0) ? FontColor.Good : FontColor.Bad));
            string text3 = homeResource.value.ToString() ?? "";
            if (homeResource.value < 0)
            {
                text3 = text3.TagColor(FontColor.Bad);
            }
            string text4 = text3;
            button.mainText.text = text4;
            fontColor = ((num2 == 0) ? FontColor.Passive : ((num2 > 0) ? FontColor.Good : FontColor.Bad));
            button.subText.text = ((((num2 > 0) ? "+" : "") + num2).TagColor(fontColor) + "dailyIncome".lang()).TagSize(13);
            break;
        }
        case BaseHomeResource.ResourceGroup.Rate:
        {
            HomeResourceRate homeResourceRate = _r as HomeResourceRate;
            int num = homeResourceRate.value - homeResourceRate.lastValue;
            if (num != 0)
            {
                _ = 0;
            }
            string text = "";
            if (num > 0)
            {
                text = "↑".TagColor(FontColor.Good);
            }
            else if (num < 0)
            {
                text = "↓".TagColor(FontColor.Bad);
            }
            string text2 = homeResourceRate.value + " " + text;
            button.mainText.text = text2;
            button.subText.SetActive(enable: false);
            break;
        }
        default:
            button.mainText.text = "Lv." + _r.value;
            button.subText.SetActive(enable: false);
            break;
        }
        imageExp.SetActive(_r.IsSkill);
        imageExp.fillAmount = _r.ExpRatio;
        button.icon.sprite = _r.Sprite;
        button.tooltip.onShowTooltip = delegate(UITooltip tp)
        {
            _r.WriteNote(tp.note);
        };
    }
References button, BaseHomeResource.ExpRatio, BaseHomeResource.Group, imageExp, BaseHomeResource.IsSkill, BaseHomeResource.lastValue, UITooltip.note, BaseHomeResource.Sprite, UIButton.subText, BaseHomeResource.value, and BaseHomeResource.WriteNote().
Referenced by ContentHomeReport.RefreshResources(), and UIHomeInfo.RefreshResources().
Member Data Documentation
button
UIButton ItemHomeResource.button
Definition at line 5 of file ItemHomeResource.cs.
Referenced by SetResource().
imageExp
Image ItemHomeResource.imageExp
Definition at line 7 of file ItemHomeResource.cs.
Referenced by SetResource().
The documentation for this class was generated from the following file:
Elin/ItemHomeResource.cs