Elin Decompiled Documentation: TraitManager Class Reference
TraitManager Class Reference
Public Member Functions
void OnAddCard (Card c)
void OnRemoveCard (Card c)
Thing GetRandomThing< T > ()
List< T > List< T > (Func< T, bool > func=null)
TraitSet GetTraitSet< T > ()
TraitSet GetTraitSet (Type t)
Public Attributes
Dictionary< Type, TraitSet > typeMap = new Dictionary<Type, TraitSet>()
TraitMap altars = new TraitMap()
TraitMap restSpots = new TraitMap()
TraitMap chairs = new TraitMap()
TraitMap suns = new TraitMap()
Additional Inherited Members
Static Public Member Functions inherited from EClass
static int rnd (int a)
static int curve (int a, int start, int step, int rate=75)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Static Public Attributes inherited from EClass
static Core core
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Detailed Description
Definition at line 4 of file TraitManager.cs.
Member Function Documentation
GetRandomThing< T >()
Thing TraitManager.GetRandomThing< T > () inline
Type Constraints
T : Trait
Definition at line 60 of file TraitManager.cs.
                                             : Trait
    {
        return GetTraitSet<T>().RandomItem()?.Thing;
    }
References GetTraitSet< T >().
GetTraitSet()
TraitSet TraitManager.GetTraitSet (Type t) inline
Definition at line 94 of file TraitManager.cs.
    {
        return typeMap.GetOrCreate(t);
    }
References typeMap.
Referenced by Zone.AddRandomVisitor(), AIAct.DoGoto< T >(), AIAct.DoGotoSpot< T >(), AI_Grab< T >.GetTarget(), DramaOutcome.PutOutFire(), FactionBranch.Recruit(), AI_Bladder.Run(), AI_GotoHearth.Run(), AI_LeaveMap.Run(), and GoalSpot.Run().
GetTraitSet< T >()
TraitSet TraitManager.GetTraitSet< T > () inline
Type Constraints
T : Trait
Definition at line 89 of file TraitManager.cs.
                                             : Trait
    {
        return typeMap.GetOrCreate(typeof(T));
    }
References typeMap.
Referenced by GetRandomThing< T >(), and List< T >().
List< T >()
List< T > TraitManager.List< T > (Func< T, bool > func = null) inline
Type Constraints
T : Trait
Definition at line 65 of file TraitManager.cs.
                                                              : Trait
    {
        TraitSet traitSet = GetTraitSet<T>();
        List<T> list = new List<T>();
        if (func == null)
        {
            foreach (Card value in traitSet.Values)
            {
                list.Add(value.trait as T);
            }
        }
        else
        {
            foreach (Card value2 in traitSet.Values)
            {
                if (func(value2.trait as T))
                {
                    list.Add(value2.trait as T);
                }
            }
        }
        return list;
    }
References GetTraitSet< T >(), List< T >(), and Card.trait.
Referenced by List< T >().
OnAddCard()
void TraitManager.OnAddCard (Card c) inline
Definition at line 16 of file TraitManager.cs.
    {
        Trait trait = c.trait;
        typeMap.GetOrCreate(trait.GetType()).Add(c);
        if (trait.IsAltar)
        {
            altars.Add(c);
        }
        if (trait.IsRestSpot)
        {
            restSpots.Add(c);
        }
        if (trait is TraitChair)
        {
            chairs.Add(c);
        }
        if (trait is TraitLightSun)
        {
            suns.Add(c);
        }
    }
References TraitMap.Add(), altars, chairs, Trait.IsAltar, Trait.IsRestSpot, restSpots, suns, Card.trait, and typeMap.
Referenced by Props.Add().
OnRemoveCard()
void TraitManager.OnRemoveCard (Card c) inline
Definition at line 38 of file TraitManager.cs.
    {
        Trait trait = c.trait;
        typeMap[trait.GetType()].Remove(c);
        if (trait.IsAltar)
        {
            altars.Remove(c);
        }
        if (trait.IsRestSpot)
        {
            restSpots.Remove(c);
        }
        if (trait is TraitChair)
        {
            chairs.Remove(c);
        }
        if (trait is TraitLightSun)
        {
            suns.Remove(c);
        }
    }
References altars, chairs, Trait.IsAltar, Trait.IsRestSpot, TraitMap.Remove(), restSpots, suns, Card.trait, and typeMap.
Referenced by Props.Remove().
Member Data Documentation
altars
TraitMap TraitManager.altars = new TraitMap()
Definition at line 8 of file TraitManager.cs.
Referenced by OnAddCard(), OnRemoveCard(), and AI_Offer.Run().
chairs
TraitMap TraitManager.chairs = new TraitMap()
Definition at line 12 of file TraitManager.cs.
Referenced by OnAddCard(), and OnRemoveCard().
restSpots
TraitMap TraitManager.restSpots = new TraitMap()
Definition at line 10 of file TraitManager.cs.
Referenced by OnAddCard(), OnRemoveCard(), and AI_Idle.Run().
suns
TraitMap TraitManager.suns = new TraitMap()
Definition at line 14 of file TraitManager.cs.
Referenced by VirtualDate.BuildSunMap(), OnAddCard(), OnRemoveCard(), and Map.RefreshSunMap().
typeMap
Dictionary<Type, TraitSet> TraitManager.typeMap = new Dictionary<Type, TraitSet>()
Definition at line 6 of file TraitManager.cs.
Referenced by GetTraitSet(), GetTraitSet< T >(), OnAddCard(), and OnRemoveCard().
The documentation for this class was generated from the following file:
Elin/TraitManager.cs