Elin Decompiled Documentation: TraitBaseContainer Class Reference
TraitBaseContainer Class Reference
Public Member Functions
override void OnCreate (int lv)
virtual void Prespawn (int lv)
void PutChara (string id)
override void SetName (ref string s)
Public Member Functions inherited from Trait
string GetParam (int i, string def=null)
int GetParamInt (int i, int def)
virtual bool Contains (RecipeSource r)
virtual int GetValue ()
virtual bool CanStackTo (Thing to)
virtual string GetHoverText ()
virtual Action GetHealAction (Chara c)
virtual bool CanBlend (Thing t)
virtual void OnBlend (Thing t, Chara c)
virtual int GetActDuration (Chara c)
virtual SourceElement.Row GetRefElement ()
virtual Sprite GetRefSprite ()
virtual void OnRenderExtra (RenderParam p)
virtual Emo2 GetHeldEmo (Chara c)
virtual void SetOwner (Card _owner)
virtual bool IdleUse (Chara c, int dist)
virtual void OnSetOwner ()
virtual void OnImportMap ()
virtual void SetParams (params string[] s)
virtual void OnCrafted (Recipe recipe, List< Thing > ings)
virtual void OnCreate (int lv)
virtual void OnEquip (Chara c, bool onSetOwner)
virtual void OnUnequip (Chara c)
virtual void OnChangePlaceState (PlaceState state)
virtual void OnAddedToZone ()
virtual void OnRemovedFromZone ()
virtual void OnSimulateHour (VirtualDate date)
virtual string GetName ()
virtual void SetName (ref string s)
virtual void OnRenderTile (Point point, HitResult result, int dir)
virtual int CompareTo (Card b)
virtual bool CanBuiltAt (Point p)
virtual void Update ()
Point GetPoint ()
Point GetRandomPoint (Func< Point, bool > func=null, Chara accessChara=null)
virtual List< Point > ListPoints (Point center=null, bool onlyPassable=true)
virtual Recipe GetRecipe ()
virtual Recipe GetBuildModeRecipe ()
virtual bool CanCook (Card c)
void CookProgress ()
virtual bool CanOffer (Card tg)
void OfferProcess (Chara cc)
void Offer (Chara cc)
virtual bool TryProgress (AIProgress p)
virtual LockOpenState TryOpenLock (Chara cc, bool msgFail=true)
virtual void WriteNote (UINote n, bool identified)
int GetSortVal (UIList.SortMode m)
virtual HotItem GetHotItem ()
virtual bool CanRead (Chara c)
virtual void OnRead (Chara c)
virtual bool CanEat (Chara c)
virtual void OnEat (Chara c)
virtual bool CanDrink (Chara c)
virtual void OnDrink (Chara c)
virtual void OnThrowGround (Chara c, Point p)
virtual bool CanUse (Chara c)
virtual bool CanUse (Chara c, Card tg)
virtual bool CanUse (Chara c, Point p)
virtual bool OnUse (Chara c)
virtual bool OnUse (Chara c, Card tg)
virtual bool OnUse (Chara c, Point p)
virtual void TrySetAct (ActPlan p)
virtual void TrySetHeldAct (ActPlan p)
virtual void OnHeld ()
virtual void OnTickHeld ()
virtual void OnSetCurrentItem ()
virtual void OnUnsetCurrentItem ()
virtual bool OnChildDecay (Card c, bool firstDecay)
virtual bool CanChildDecay (Card c)
virtual void OnSetCardGrid (ButtonGrid b)
virtual void OnStepped (Chara c)
virtual void OnSteppedOut (Chara c)
virtual void OnOpenDoor (Chara c)
void Install (bool byPlayer)
void Uninstall ()
virtual void OnInstall (bool byPlayer)
virtual void OnUninstall ()
virtual void TryToggle ()
virtual void Toggle (bool on, bool silent=false)
virtual void PlayToggleEffect (bool silent)
virtual void OnToggle ()
virtual void TrySetToggleAct (ActPlan p)
bool IsFuelEnough (int num=1, List< Thing > excludes=null, bool tryRefuel=true)
bool IsFuel (string s)
bool IsFuel (Thing t)
int GetFuelValue (Thing t)
int GetFuelValue (string id)
void Refuel (Thing t)
void TryRefuel (int dest, List< Thing > excludes)
virtual void OnEnterScreen ()
virtual void RefreshRenderer ()
virtual void SetMainText (UIText t, bool hotitem)
virtual bool CanCopy (Thing t)
string GetTextRestock (string lang, bool pet)
Emo2 GetRestockedIcon ()
void OnBarter (bool reroll=false)
Thing CreateStock ()
Properties
bool HasChara [get]
override bool ShowChildrenNumber [get]
override string IDInvStyle [get]
override RefCardName RefCardName [get]
string idContainer [get]
int Width [get]
int Height [get]
virtual string DefaultIdInvStyle [get]
virtual string DefaultIdContainer [get]
virtual int DefaultWidth [get]
virtual int DefaultHeight [get]
virtual int ChanceLock [get]
virtual int ChanceMedal [get]
override int DecaySpeedChild [get]
override bool IsContainer [get]
virtual bool ShowOpenActAsCrime [get]
override bool UseAltTiles [get]
Properties inherited from Trait
string[] Params [get]
virtual byte WeightMod [get]
virtual int IdSkin [get]
virtual string Name [get]
virtual TileType tileType [get]
virtual RefCardName RefCardName [get]
virtual bool IsBlockPath [get]
virtual bool IsBlockSight [get]
virtual bool IsDoor [get]
virtual bool IsOpenSight [get]
virtual bool IsOpenPath [get]
virtual bool IsFloating [get]
virtual bool IsNoShop [get]
virtual bool IsGround [get]
virtual bool IsOnlyUsableByPc [get]
virtual bool InvertHeldSprite [get]
virtual bool IsChangeFloorHeight [get]
virtual bool ShouldRefreshTile [get]
virtual bool ShouldTryRefreshRoom [get]
virtual int InstallBottomPriority [get]
virtual bool CanHarvest [get]
virtual int radius [get]
virtual TraitRadiusType radiusType [get]
virtual bool CanUseRoomRadius [get]
virtual int GuidePriotiy [get]
virtual int OriginalElectricity [get]
virtual int Electricity [get]
virtual bool IgnoreLastStackHeight [get]
virtual int Decay [get]
virtual int DecaySpeed [get]
virtual int DecaySpeedChild [get]
virtual bool IsFridge [get]
virtual int DefaultStock [get]
virtual bool HoldAsDefaultInteraction [get]
virtual int CraftNum [get]
virtual bool ShowOrbit [get]
virtual bool HaveUpdate [get]
virtual bool IsSpot [get]
virtual bool IsFactory [get]
virtual bool CanAutofire [get]
virtual bool CanName [get]
virtual bool CanPutAway [get]
virtual bool CanChangeHeight [get]
virtual bool CanStack [get]
virtual bool CanCopyInBlueprint [get]
virtual bool CanBeAttacked [get]
virtual bool CanBeTeleported [get]
virtual bool CanExtendBuild [get]
virtual string langNote [get]
virtual string IDInvStyle [get]
virtual string IDActorEx [get]
virtual bool MaskOnBuild [get]
virtual bool ShowContextOnPick [get]
virtual bool IsThrowMainAction [get]
virtual bool LevelAsQuality [get]
virtual bool UseDummyTile [get]
virtual bool RequireFullStackCheck [get]
virtual bool DisableAutoCombat [get]
virtual InvGridSize InvGridSize [get]
virtual bool IsContainer [get]
virtual bool CanUseContent [get]
virtual bool CanSearchContent [get]
virtual bool CanOpenContainer [get]
virtual bool IsSpecialContainer [get]
virtual ContainerType ContainerType [get]
virtual ThrowType ThrowType [get]
virtual EffectDead EffectDead [get]
virtual bool IsHomeItem [get]
virtual bool IsAltar [get]
virtual bool IsRestSpot [get]
virtual bool CanBeMasked [get]
virtual bool IsLocalAct [get]
virtual bool IsBlendBase [get]
virtual bool CanBeOnlyBuiltInHome [get]
virtual bool CanBuildInTown [get]
virtual bool CanBeHeld [get]
virtual bool CanBeStolen [get]
virtual bool CanOnlyCarry [get]
virtual bool CanBeDestroyed [get]
virtual bool CanBeSmashedToDeath [get]
virtual bool CanBeHallucinated [get]
virtual bool CanBeDropped [get]
virtual string ReqHarvest [get]
virtual bool CanBeDisassembled [get]
virtual bool CanBeShipped [get]
virtual bool HasCharges [get]
virtual bool ShowCharges [get]
virtual bool ShowChildrenNumber [get]
virtual bool ShowAsTool [get]
virtual bool CanBeHeldAsFurniture [get]
virtual bool HideInAdv [get]
virtual bool NoHeldDir [get]
virtual bool AlwaysHideOnLowWall [get]
bool ExistsOnMap [get]
virtual bool RenderExtra [get]
virtual float DropChance [get]
virtual string IdNoRestock [get]
virtual int IdleUseChance [get]
virtual string RecipeCat [get]
virtual bool IsTool [get]
virtual string LangUse [get]
virtual bool IgnoreOnSteppedWhenMoving [get]
virtual bool IsOn [get]
virtual bool IsAnimeOn [get]
bool IsToggle [get]
virtual bool AutoToggle [get]
bool IsLighting [get]
virtual bool IsLightOn [get]
virtual bool IsNightOnlyLight [get]
virtual TileMode tileMode [get]
virtual bool UseAltTiles [get]
virtual bool UseLowblock [get]
virtual bool UseExtra [get]
virtual bool UseLightColor [get]
virtual ? Color ColorExtra [get]
virtual int MaxFuel [get]
virtual int FuelCost [get]
virtual bool ShowFuelWindow [get]
bool IsRequireFuel [get]
string IdToggleExtra [get]
virtual ToggleType ToggleType [get]
virtual string IdSoundToggleOn [get]
virtual string IdSoundToggleOff [get]
virtual int ShopLv [get]
virtual CopyShopType CopyShop [get]
virtual int NumCopyItem [get]
virtual ShopType ShopType [get]
virtual CurrencyType CurrencyType [get]
virtual PriceType PriceType [get]
virtual bool AllowSell [get]
virtual int CostRerollShop [get]
virtual bool AllowCriminal [get]
virtual int RestockDay [get]
virtual SlaverType SlaverType [get]
virtual string LangBarter [get]
virtual bool RemoveGlobalOnBanish [get]
virtual bool CanChangeAffinity [get]
string TextNextRestock [get]
string TextNextRestockPet [get]
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Additional Inherited Members
Public Types inherited from Trait
enum TileMode {
Default , Door , Illumination , DefaultNoAnime ,
SignalAnime , FakeBlock
}
enum CopyShopType { None , Item , Spellbook }
Static Public Member Functions inherited from EClass
static int rndSeed (int a, int seed)
static int rnd (long a)
static int rnd (int a)
static int curve (int _a, int start, int step, int rate=75)
static int sqrt (int a)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Public Attributes inherited from Trait
Card owner
Static Public Attributes inherited from Trait
static TraitSelfFactory SelfFactory = new TraitSelfFactory()
Static Public Attributes inherited from EClass
static Core core
Static Protected Attributes inherited from Trait
static List< Point > listRadiusPoints = new List<Point>()
Detailed Description
Definition at line 3 of file TraitBaseContainer.cs.
Member Function Documentation
OnCreate()
override void TraitBaseContainer.OnCreate (int lv) inline virtual
Reimplemented from Trait.
Reimplemented in TraitChestPractice.
Definition at line 99 of file TraitBaseContainer.cs.
    {
        owner.things.SetSize(Width, Height);
        if (ChanceLock > 0 && ChanceLock > EClass.rnd(100))
        {
            lv += 10;
            owner.c_lockLv = EClass.curve(5 + lv / 2 + EClass.rnd(lv / 2), 50, 10, 80);
        }
        Prespawn(lv);
    }
References ChanceLock, EClass.curve(), Height, Trait.owner, Prespawn(), EClass.rnd(), ThingContainer.SetSize(), Card.things, and Width.
Prespawn()
virtual void TraitBaseContainer.Prespawn (int lv) inline virtual
Reimplemented in TraitChest, TraitChestMerchant, TraitChestOyster, TraitChestPractice, TraitContainerCurrency, TraitContainerShared, TraitDeliveryChest, TraitDeposit, TraitSalaryChest, TraitShippingChest, and TraitToolBelt.
Definition at line 110 of file TraitBaseContainer.cs.
    {
        if (!CanOpenContainer)
        {
            return;
        }
        int num = 1 + EClass.rnd(2);
        int num2 = EClass.curve(lv, 20, 15);
        for (int i = 0; i < num; i++)
        {
            Thing thing = null;
            if (EClass.sources.spawnLists.map.ContainsKey(idContainer))
            {
                thing = ThingGen.CreateFromFilter(idContainer);
            }
            else if (EClass.sources.categories.map.ContainsKey(idContainer))
            {
                thing = ThingGen.CreateFromCategory(idContainer);
            }
            else
            {
                string text = idContainer;
                thing = ((!(text == "money")) ? ((!(text == "provision")) ? ((!EClass.sources.things.map.ContainsKey(idContainer)) ? ThingGen.CreateFromFilter("container_general", (lv + owner.c_lockLv > 0) ? 5 : 0) : ThingGen.Create(idContainer)) : ThingGen.CreateFromCategory((EClass.rnd(2) == 0) ? "preserved" : "drink")) : ((EClass.rnd(2) == 0) ? ThingGen.Create("money").SetNum(10 + EClass.rnd(50 + num2 * 25)) : ((EClass.rnd(2) != 0) ? ThingGen.Create("plat") : ThingGen.Create("money2").SetNum(1 + EClass.rnd(Mathf.Min(2 + num2 / 50, 5))))));
            }
            if (thing != null)
            {
                owner.AddCard(thing);
            }
        }
        if (EClass.rnd(ChanceMedal) == 0)
        {
            owner.Add("medal");
        }
    }
References Card.Add(), Card.AddCard(), Card.c_lockLv, Trait.CanOpenContainer, SourceManager.categories, ChanceMedal, ThingGen.Create(), ThingGen.CreateFromCategory(), ThingGen.CreateFromFilter(), EClass.curve(), idContainer, Trait.owner, EClass.rnd(), Card.SetNum(), EClass.sources, SourceManager.spawnLists, and SourceManager.things.
Referenced by OnCreate().
PutChara()
void TraitBaseContainer.PutChara (string id) inline
Definition at line 145 of file TraitBaseContainer.cs.
    {
        owner.c_idRefCard = id;
        owner.AddCard(ThingGen.Create("junk"));
    }
References Card.AddCard(), ThingGen.Create(), and Trait.owner.
Referenced by GameDate.ShipRandomPackages().
SetName()
override void TraitBaseContainer.SetName (ref string s) inline virtual
Reimplemented from Trait.
Reimplemented in TraitMagicChest.
Definition at line 151 of file TraitBaseContainer.cs.
    {
        if (owner.Thing.IsSharedContainer)
        {
            s = "_shared".lang(s);
        }
        if (!owner.c_idRefName.IsEmpty() && owner.c_altName.IsEmpty())
        {
            s = "_written".lang(owner.c_idRefName, s);
        }
    }
References Card.c_altName, Card.c_idRefName, Thing.IsSharedContainer, Trait.owner, and Card.Thing.
Property Documentation
ChanceLock
virtual int TraitBaseContainer.ChanceLock get
Definition at line 77 of file TraitBaseContainer.cs.
Referenced by OnCreate().
ChanceMedal
virtual int TraitBaseContainer.ChanceMedal get
Definition at line 79 of file TraitBaseContainer.cs.
Referenced by Prespawn().
DecaySpeedChild
override int TraitBaseContainer.DecaySpeedChild get
Definition at line 81 of file TraitBaseContainer.cs.
DefaultHeight
virtual int TraitBaseContainer.DefaultHeight get
Definition at line 75 of file TraitBaseContainer.cs.
DefaultIdContainer
virtual string TraitBaseContainer.DefaultIdContainer get
Definition at line 71 of file TraitBaseContainer.cs.
DefaultIdInvStyle
virtual string TraitBaseContainer.DefaultIdInvStyle get
Definition at line 69 of file TraitBaseContainer.cs.
DefaultWidth
virtual int TraitBaseContainer.DefaultWidth get
Definition at line 73 of file TraitBaseContainer.cs.
HasChara
bool TraitBaseContainer.HasChara get
Definition at line 5 of file TraitBaseContainer.cs.
Height
int TraitBaseContainer.Height get
Definition at line 57 of file TraitBaseContainer.cs.
    {
        get
        {
            if (owner.sourceCard.trait.Length <= 2)
            {
                return DefaultHeight;
            }
            return GetParam(2).ToInt();
        }
    }
Referenced by OnCreate(), and TraitWrench.Upgrade().
idContainer
string TraitBaseContainer.idContainer get
Definition at line 33 of file TraitBaseContainer.cs.
    {
        get
        {
            if (GetParam(4) != null)
            {
                return GetParam(4);
            }
            return DefaultIdContainer;
        }
    }
Referenced by Prespawn().
IDInvStyle
override string TraitBaseContainer.IDInvStyle get
Definition at line 19 of file TraitBaseContainer.cs.
    {
        get
        {
            if (GetParam(3) != null)
            {
                return GetParam(3);
            }
            return DefaultIdInvStyle;
        }
    }
IsContainer
override bool TraitBaseContainer.IsContainer get
Definition at line 83 of file TraitBaseContainer.cs.
RefCardName
override RefCardName TraitBaseContainer.RefCardName get
Definition at line 31 of file TraitBaseContainer.cs.
ShowChildrenNumber
override bool TraitBaseContainer.ShowChildrenNumber get
Definition at line 7 of file TraitBaseContainer.cs.
    {
        get
        {
            if (!HasChara)
            {
                return base.ShowChildrenNumber;
            }
            return false;
        }
    }
ShowOpenActAsCrime
virtual bool TraitBaseContainer.ShowOpenActAsCrime get
Definition at line 85 of file TraitBaseContainer.cs.
Referenced by TraitContainer.TrySetAct().
UseAltTiles
override bool TraitBaseContainer.UseAltTiles get
Definition at line 87 of file TraitBaseContainer.cs.
    {
        get
        {
            if (owner.things.Count == 0)
            {
                return owner.c_lockLv == 0;
            }
            return false;
        }
    }
Width
int TraitBaseContainer.Width get
Definition at line 45 of file TraitBaseContainer.cs.
    {
        get
        {
            if (owner.sourceCard.trait.Length <= 1)
            {
                return DefaultWidth;
            }
            return GetParam(1).ToInt();
        }
    }
Referenced by OnCreate(), and TraitWrench.Upgrade().
The documentation for this class was generated from the following file:
Elin/TraitBaseContainer.cs