Elin Decompiled Documentation: MapPiece Class Reference
MapPiece Class Reference
Classes
class Item
class MapPath
Public Types
enum Type {
Any , Deco , Treasure , Trap ,
Concert , Farm
}
Public Member Functions
PartialMap GetMap (MapPiece.Type type, string tag, float ruin)
void Init ()
void Reset ()
Public Attributes
List< MapPiece.Item > items
Static Public Attributes
static bool initialized
static Dictionary< string, PartialMap > CacheMap = new Dictionary<string, PartialMap>()
Properties
static MapPiece Instance [get]
static bool IsEditor [get]
Static Private Attributes
static MapPiece _Instance
Additional Inherited Members
Static Public Member Functions inherited from EScriptable
static int rnd (int a)
Detailed Description
Definition at line 6 of file MapPiece.cs.
Member Enumeration Documentation
Type
enum MapPiece.Type
Enumerator
Any
Deco
Treasure
Trap
Concert
Farm
Definition at line 121 of file MapPiece.cs.
    {
        Any,
        Deco,
        Treasure,
        Trap,
        Concert,
        Farm
    }
Member Function Documentation
GetMap()
PartialMap MapPiece.GetMap (MapPiece::Type type, string tag, float ruin) inline
Definition at line 29 of file MapPiece.cs.
    {
        this.Init();
        MapPiece.Item item = this.items.RandomItemWeighted(delegate(MapPiece.Item a)
        {
            if (a.chance != 0f || !(type.ToString() == a.id))
            {
                return a.chance * (float)((type == MapPiece.Type.Any || type.ToString() == a.id) ? 1 : 0);
            }
            return 1f;
        });
        if (item.paths.Count == 0)
        {
            Debug.Log("no path");
            return null;
        }
        string[] array = tag.IsEmpty() ? null : tag.Split(',', StringSplitOptions.None);
        List<MapPiece.MapPath> list = new List<MapPiece.MapPath>();
        foreach (MapPiece.MapPath mapPath in item.paths)
        {
            if (mapPath.tag.IsEmpty() || (array != null && array.Contains(tag)))
            {
                list.Add(mapPath);
            }
        }
        if (list.Count == 0)
        {
            return null;
        }
        string path = list.RandomItem<MapPiece.MapPath>().path;
        Debug.Log("Loading PartialMap:" + path);
        PartialMap partialMap = MapPiece.CacheMap.TryGetValue(path, null);
        if (partialMap == null)
        {
            partialMap = PartialMap.Load(path);
            MapPiece.CacheMap.Add(path, partialMap);
        }
        if (partialMap.allowRotate)
        {
            partialMap.dir = EScriptable.rnd(4);
        }
        partialMap.procedural = true;
        partialMap.ruinChance = ruin;
        return partialMap;
    }
References Init(), and items.
Referenced by GenBounds.TryAddMapPiece().
Init()
void MapPiece.Init () inline
Definition at line 75 of file MapPiece.cs.
    {
        if (MapPiece.initialized)
        {
            return;
        }
        foreach (MapPiece.Item item in this.items)
        {
            item.paths.Clear();
            foreach (string text in Directory.GetFiles(CorePath.MapPieceSave + item.id, "*", SearchOption.AllDirectories))
            {
                if (text.EndsWith("mp"))
                {
                    DirectoryInfo directory = new FileInfo(text).Directory;
                    string tag = (directory.Parent.Name != item.id) ? "" : directory.Name;
                    item.paths.Add(new MapPiece.MapPath
                    {
                        path = text,
                        tag = tag
                    });
                }
            }
        }
        MapPiece.initialized = true;
    }
References initialized, and text.
Referenced by GetMap().
Reset()
void MapPiece.Reset () inline
Definition at line 101 of file MapPiece.cs.
    {
        MapPiece.initialized = false;
    }
Member Data Documentation
_Instance
MapPiece MapPiece._Instance static private
Definition at line 106 of file MapPiece.cs.
CacheMap
Dictionary<string, PartialMap> MapPiece.CacheMap = new Dictionary<string, PartialMap>() static
Definition at line 112 of file MapPiece.cs.
Referenced by PartialMapMenu.Activate().
initialized
bool MapPiece.initialized static
Definition at line 108 of file MapPiece.cs.
Referenced by Init().
items
List<MapPiece.Item> MapPiece.items
Definition at line 110 of file MapPiece.cs.
Referenced by GetMap().
Property Documentation
Instance
MapPiece MapPiece.Instance static get
Definition at line 8 of file MapPiece.cs.
    {
        get
        {
            MapPiece result;
            if ((result = MapPiece._Instance) == null)
            {
                result = (MapPiece._Instance = Resources.Load<MapPiece>("World/Map/MapPiece"));
            }
            return result;
        }
    }
Referenced by GenBounds.TryAddMapPiece().
IsEditor
bool MapPiece.IsEditor static get
Definition at line 21 of file MapPiece.cs.
    {
        get
        {
            return EClass.debug.enableMapPieceEditor;
        }
    }
Referenced by UIScreenshot.Activate(), AM_Copy.OnAfterProcessTiles(), and AM_Copy.OnSave().
The documentation for this class was generated from the following file:
Elin/MapPiece.cs