Elin Decompiled Documentation: BaseTileSelector Class Reference
BaseTileSelector Class Reference
Public Types
enum SelectType { Single , Multiple , None }
enum HitType {
None , Default , Floor , Block ,
Inspect
}
enum BoxType { Box , Fence }
enum ProcessMode { Render , Prpcess , Summary }
Public Member Functions
void OnChangeActionMode ()
virtual void OnRenderTile (Point point, HitResult result, bool shouldHide)
void OnUpdate ()
void TryProcessTiles (Point _end)
void ProcessTiles (Point start, Point end, BaseTileSelector.ProcessMode processMode)
void ProcessFillTiles (Point start, BaseTileSelector.ProcessMode processMode)
bool IsInRange (int x, int z, Point end)
unsafe void RefreshMouseInfo (bool force=false)
void ExecuteSummary ()
void RefreshSummary ()
Public Attributes
BaseTileSelector.HitType inspectHitType
bool inspectorHighlight
HitSummary summary = new HitSummary()
Point start
Point temp = new Point()
Point lastPoint = new Point()
Point lastClickPoint = new Point()
bool processing
bool autoClick
bool firstInMulti
Properties
ActionMode mode [get]
BaseTileSelector.SelectType selectType [get]
BaseTileSelector.HitType hitType [get]
BaseTileSelector.BoxType boxType [get]
int hitW [get]
int hitH [get]
bool multisize [get]
int Width [get]
int Height [get]
Properties inherited from EMono
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SoundManager Sound [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static CoreDebug debug [get]
Private Member Functions
void _ProcessTile (Point start, Point dest, BaseTileSelector.ProcessMode processMode, int dir=-1)
Additional Inherited Members
Static Public Member Functions inherited from EMono
static int rnd (int a)
Static Public Attributes inherited from EMono
static Core core
Detailed Description
Definition at line 4 of file BaseTileSelector.cs.
Member Enumeration Documentation
BoxType
enum BaseTileSelector.BoxType
Enumerator
Box
Fence
Definition at line 533 of file BaseTileSelector.cs.
    {
        Box,
        Fence
    }
HitType
enum BaseTileSelector.HitType
Enumerator
None
Default
Floor
Block
Inspect
Definition at line 524 of file BaseTileSelector.cs.
    {
        None,
        Default,
        Floor,
        Block,
        Inspect
    }
ProcessMode
enum BaseTileSelector.ProcessMode
Enumerator
Render
Prpcess
Summary
Definition at line 539 of file BaseTileSelector.cs.
    {
        Render,
        Prpcess,
        Summary
    }
SelectType
enum BaseTileSelector.SelectType
Enumerator
Single
Multiple
None
Definition at line 517 of file BaseTileSelector.cs.
    {
        Single,
        Multiple,
        None
    }
Member Function Documentation
_ProcessTile()
void BaseTileSelector._ProcessTile (Point start, Point dest, BaseTileSelector::ProcessMode processMode, int dir = -1) inline private
Definition at line 333 of file BaseTileSelector.cs.
    {
        if (!dest.IsValid)
        {
            return;
        }
        HitResult hitResult = this.mode._HitTest(dest, start);
        switch (processMode)
        {
        case BaseTileSelector.ProcessMode.Render:
            this.mode.OnRenderTile(dest, hitResult, dir);
            this.firstInMulti = false;
            return;
        case BaseTileSelector.ProcessMode.Prpcess:
            if (hitResult == HitResult.Valid || hitResult == HitResult.Warning)
            {
                this.mode.OnProcessTiles(dest, dir);
                return;
            }
            break;
        case BaseTileSelector.ProcessMode.Summary:
            this.mode.OnRefreshSummary(dest, hitResult, this.summary);
            break;
        default:
            return;
        }
    }
References ActionMode._HitTest(), Point.IsValid, mode, ActionMode.OnProcessTiles(), ActionMode.OnRefreshSummary(), ActionMode.OnRenderTile(), start, and summary.
Referenced by ProcessFillTiles(), and ProcessTiles().
ExecuteSummary()
void BaseTileSelector.ExecuteSummary () inline
Definition at line 468 of file BaseTileSelector.cs.
    {
        if (!BuildMenu.Instance)
        {
            return;
        }
        this.summary.Execute();
        BuildMenu.Instance.info1.Refresh();
        this.RefreshSummary();
        this.mode.SEExecuteSummary();
    }
References HitSummary.Execute(), BuildMenu.info1, BuildMenu.Instance, mode, UIRecipeInfo.Refresh(), RefreshSummary(), ActionMode.SEExecuteSummary(), and summary.
Referenced by TryProcessTiles().
IsInRange()
bool BaseTileSelector.IsInRange (int x, int z, Point end) inline
Definition at line 361 of file BaseTileSelector.cs.
    {
        if (this.start.x > end.x)
        {
            if (x > this.start.x || x < end.x)
            {
                return false;
            }
        }
        else if (x < this.start.x || x > end.x)
        {
            return false;
        }
        if (this.start.z > end.z)
        {
            if (z > this.start.z || z < end.z)
            {
                return false;
            }
        }
        else if (z < this.start.z || z > end.z)
        {
            return false;
        }
        return true;
    }
References start, Point.x, and Point.z.
OnChangeActionMode()
void BaseTileSelector.OnChangeActionMode () inline
Definition at line 94 of file BaseTileSelector.cs.
    {
        this.start = null;
        this.RefreshMouseInfo(true);
    }
References RefreshMouseInfo().
OnRenderTile()
virtual void BaseTileSelector.OnRenderTile (Point point, HitResult result, bool shouldHide) inline virtual
Reimplemented in TileSelectorElona.
Definition at line 100 of file BaseTileSelector.cs.
    {
    }
Referenced by AM_Region.OnRenderTile().
OnUpdate()
void BaseTileSelector.OnUpdate () inline
Definition at line 104 of file BaseTileSelector.cs.
    {
        Point hitPoint = Scene.HitPoint;
        if (!ActionMode.Adv.IsActive)
        {
            this.RefreshMouseInfo(true);
        }
        if (EInput.leftMouse.pressedLong && this.mode.AllowAutoClick)
        {
            this.autoClick = true;
        }
        if (this.autoClick && !EInput.leftMouse.pressing)
        {
            this.autoClick = false;
            if (this.start != null)
            {
                this.mode.OnSelectEnd(true);
                this.start = null;
                this.RefreshSummary();
                this.RefreshMouseInfo(true);
            }
        }
        if (this.autoClick && hitPoint.Distance(this.lastClickPoint) > 1 && this.selectType == BaseTileSelector.SelectType.Multiple && this.start != null)
        {
            this.start = hitPoint.Copy();
            this.mode.OnSelectStart(this.start);
            this.RefreshMouseInfo(true);
            this.lastClickPoint.Set(hitPoint);
        }
        if (((EInput.rightScroll && EInput.rightMouse.clicked) || (!EInput.rightScroll && EInput.rightMouse.down) || Input.GetKeyDown(KeyCode.Escape)) && !EMono.ui.wasActive)
        {
            if (this.selectType == BaseTileSelector.SelectType.Multiple && this.start != null)
            {
                this.mode.OnSelectEnd(true);
                this.start = null;
                this.RefreshSummary();
                this.RefreshMouseInfo(true);
            }
            else
            {
                this.mode.OnCancel();
            }
            EMono.ui.hud.hint.UpdateText();
        }
        if (!hitPoint.IsValid || EMono.ui.isPointerOverUI || EMono.ui.wasActive || this.mode.selectType == BaseTileSelector.SelectType.None || !EMono.pc.ai.ShowCursor)
        {
            return;
        }
        if (this.mode.hitType != BaseTileSelector.HitType.None)
        {
            if (this.mode.IsFillMode())
            {
                this.start = null;
                this.ProcessFillTiles(hitPoint, BaseTileSelector.ProcessMode.Render);
            }
            else
            {
                this.ProcessTiles(this.start ?? hitPoint, hitPoint, BaseTileSelector.ProcessMode.Render);
            }
        }
        if (this.start == null && (this.mode.AreaHihlight == AreaHighlightMode.Edit || this.mode.AreaHihlight == AreaHighlightMode.Sim) && hitPoint.area != null)
        {
            hitPoint.area.OnHoverArea(EMono.screen.guide.passArea);
        }
        if ((this.autoClick || EInput.leftMouse.down || (this.mode.ContinuousClick && EInput.leftMouse.pressing)) && this.mode.CanSelectTile)
        {
            if (this.start != null || hitPoint.IsSeen)
            {
                if (this.mode.IsFillMode())
                {
                    this.TryProcessTiles(hitPoint);
                }
                else if (this.selectType == BaseTileSelector.SelectType.Single)
                {
                    HitResult hitResult = this.mode._HitTest(this.temp, this.start);
                    if ((hitResult == HitResult.Valid || hitResult == HitResult.Warning) && this.mode.CanProcessTiles())
                    {
                        this.TryProcessTiles(hitPoint);
                    }
                    else if (!this.autoClick)
                    {
                        SE.Beep();
                    }
                }
                else
                {
                    if (this.start == null)
                    {
                        this.start = hitPoint.Copy();
                        this.mode.OnSelectStart(this.start);
                        this.RefreshMouseInfo(true);
                        if (this.autoClick)
{
                            this.TryProcessTiles(hitPoint);
                        }
                    }
                    else
                    {
                        this.TryProcessTiles(hitPoint);
                    }
                    if (this.autoClick)
                    {
                        this.start = hitPoint.Copy();
                        this.mode.OnSelectStart(this.start);
                        this.RefreshMouseInfo(true);
                    }
                }
            }
            this.lastClickPoint.Set(hitPoint);
            EMono.ui.hud.hint.UpdateText();
        }
    }
References ActionMode._HitTest(), ActionMode.Adv, Chara.ai, Point.area, ActionMode.AreaHihlight, autoClick, Point.Copy(), Point.Distance(), BaseGameScreen.guide, Scene.HitPoint, ActionMode.hitType, ActionMode.IsActive, ActionMode.IsFillMode(), Point.IsSeen, Point.IsValid, lastClickPoint, mode, ActionMode.OnCancel(), Area.OnHoverArea(), ActionMode.OnSelectEnd(), ActionMode.OnSelectStart(), ScreenGuide.passArea, EMono.pc, ProcessFillTiles(), ProcessTiles(), RefreshMouseInfo(), RefreshSummary(), EMono.screen, selectType, Point.Set(), AIAct.ShowCursor, start, temp, TryProcessTiles(), and EMono.ui.
ProcessFillTiles()
void BaseTileSelector.ProcessFillTiles (Point start, BaseTileSelector::ProcessMode processMode) inline
Definition at line 321 of file BaseTileSelector.cs.
    {
        EMono._map.ForeachPoint(delegate(Point dest)
        {
            if (!start.Equals(dest))
            {
                this._ProcessTile(start, dest, processMode, -1);
            }
        });
        this._ProcessTile(start, start, processMode, -1);
    }
References EMono._map, _ProcessTile(), Point.Equals(), Map.ForeachPoint(), and start.
Referenced by OnUpdate(), and TryProcessTiles().
ProcessTiles()
void BaseTileSelector.ProcessTiles (Point start, Point end, BaseTileSelector::ProcessMode processMode) inline
Definition at line 258 of file BaseTileSelector.cs.
    {
        new Point();
        object obj = (start.x > end.x) ? start.x : end.x;
        int num = (start.z < end.z) ? start.z : end.z;
        int num2 = (start.x > end.x) ? end.x : start.x;
        int num3 = (start.z < end.z) ? end.z : start.z;
        object obj2 = obj;
        int num4 = obj2 - num2 + 1;
        int num5 = num3 - num + 1;
        BaseTileSelector.BoxType boxType = this.boxType;
        int num6 = -1;
        int num7 = 0;
        this.firstInMulti = false;
        if (this.multisize && this.selectType == BaseTileSelector.SelectType.Single && processMode != BaseTileSelector.ProcessMode.Prpcess)
        {
            num2 -= this.hitW - 1;
            num3 += this.hitH - 1;
            num4 += this.hitW - 1;
            num5 += this.hitH - 1;
        }
        if (processMode == BaseTileSelector.ProcessMode.Prpcess)
        {
            this.processing = true;
        }
        for (int i = obj2; i > num2 - 1; i--)
        {
            int j = num;
            while (j < num3 + 1)
            {
                if (boxType != BaseTileSelector.BoxType.Fence || (num4 <= 1 && num5 <= 1))
                {
                    goto IL_12A;
                }
                num6 = ((num4 > num5) ? 0 : 1);
                if ((num6 != 0 || j == start.z) && (num6 != 1 || i == start.x))
                {
                    goto IL_12A;
                }
                IL_15E:
                j++;
                continue;
                IL_12A:
                this.temp.Set(i, j);
                if (start.x != i || start.z != j)
                {
                    this._ProcessTile(start, this.temp, processMode, num6);
                    goto IL_15E;
                }
                goto IL_15E;
            }
            num7++;
            if (num7 > 30000)
            {
                Debug.Log(num7);
                break;
            }
        }
        this.firstInMulti = true;
        this._ProcessTile(start, start, processMode, num6);
        this.processing = false;
    }
References _ProcessTile(), boxType, multisize, selectType, Point.Set(), start, temp, Point.x, and Point.z.
Referenced by OnUpdate(), RefreshSummary(), and TryProcessTiles().
RefreshMouseInfo()
unsafe void BaseTileSelector.RefreshMouseInfo (bool force = false) inline
Definition at line 388 of file BaseTileSelector.cs.
    {
        bool enable = true;
        Point hitPoint = Scene.HitPoint;
        if (EMono.ui.IsActive || EMono.ui.isPointerOverUI || !this.mode.enableMouseInfo || !hitPoint.IsValid)
        {
            enable = false;
        }
        else if (!hitPoint.Equals(this.lastPoint) || force)
        {
            if (this.start != null && !hitPoint.Equals(this.lastPoint))
            {
                SE.Play("highlight3");
            }
            this.RefreshSummary();
            string text = "";
            int num = 0;
            if (this.start != null)
            {
                int num2 = Mathf.Abs(hitPoint.x - this.start.x) + 1;
                int num3 = Mathf.Abs(hitPoint.z - this.start.z) + 1;
                if (!hitPoint.IsValid)
                {
                    num2 = 0;
                    num3 = 0;
                }
                text = string.Concat(new string[]
                {
                    text,
                    "(",
                    num2.ToString(),
                    " x ",
                    num3.ToString(),
                    ")"
                });
            }
            else if (this.selectType == BaseTileSelector.SelectType.Multiple)
            {
                text += "selectRange".lang();
            }
            if (this.selectType == BaseTileSelector.SelectType.Single)
            {
                num = this.mode.CostMoney;
            }
            else if (this.start != null)
            {
                num = this.summary.money;
            }
            EMono.ui.mouseInfo.textCost.SetActive(num != 0);
            if (num != 0)
            {
                EMono.ui.mouseInfo.textCost.text = (num.ToString() ?? "");
            }
            if (this.mode.TopHeight(hitPoint) != -1)
            {
                text += "hintAltitude".lang(this.mode.TopHeight(hitPoint).ToString() ?? "", null, null, null, null);
            }
            if (EMono.scene.actionMode == ActionMode.Picker)
            {
                AM_Picker.Result result = ActionMode.Picker.Test(hitPoint, false);
                if (result.IsValid)
                {
                    text += result.GetText();
                }
            }
            if (this.mode.IsRoofEditMode(null))
            {
                text = text + Environment.NewLine + "roofEdit".lang();
            }
            else if (this.mode.IsFillMode())
            {
                text = text + Environment.NewLine + "fillMode".lang();
            }
            text += "\n";
            EMono.ui.mouseInfo.text.SetText(*this.mode.SetMouseInfo(ref text));
        }
        EMono.ui.mouseInfo.SetActive(enable);
        this.lastPoint.Set(hitPoint);
    }
References Scene.actionMode, ActionMode.CostMoney, Point.Equals(), AM_Picker.Result.GetText(), Scene.HitPoint, ActionMode.IsFillMode(), ActionMode.IsRoofEditMode(), AM_Picker.Result.IsValid, Point.IsValid, lastPoint, mode, HitSummary.money, ActionMode.Picker, RefreshSummary(), EMono.scene, selectType, Point.Set(), ActionMode.SetMouseInfo(), start, summary, AM_Picker.Test(), text, ActionMode.TopHeight(), EMono.ui, Point.x, and Point.z.
Referenced by AM_Build.InputWheel(), OnChangeActionMode(), OnUpdate(), and TryProcessTiles().
RefreshSummary()
void BaseTileSelector.RefreshSummary () inline
Definition at line 480 of file BaseTileSelector.cs.
    {
        Point hitPoint = Scene.HitPoint;
        this.summary.Clear();
        this.ProcessTiles(this.start ?? hitPoint, hitPoint, BaseTileSelector.ProcessMode.Summary);
        if (BuildMenu.Instance)
        {
            BuildMenu.Instance.info1.RefreshBalance();
        }
    }
References HitSummary.Clear(), Scene.HitPoint, BuildMenu.info1, BuildMenu.Instance, ProcessTiles(), UIRecipeInfo.RefreshBalance(), start, and summary.
Referenced by ExecuteSummary(), OnUpdate(), and RefreshMouseInfo().
TryProcessTiles()
void BaseTileSelector.TryProcessTiles (Point _end) inline
Definition at line 217 of file BaseTileSelector.cs.
    {
        if (EInput.skipFrame > 0)
        {
            return;
        }
        if (!this.mode.CanProcessTiles())
        {
            if (!EMono.screen.tileSelector.autoClick)
            {
                SE.Beep();
            }
            return;
        }
        Point point = _end.Copy();
        ActionMode mode = this.mode;
        this.mode.OnBeforeProcessTiles();
        if (this.mode.IsFillMode())
        {
            this.ProcessFillTiles(point, BaseTileSelector.ProcessMode.Prpcess);
        }
        else if (this.start == null)
        {
            this.mode.OnProcessTiles(point, -1);
        }
        else
        {
            this.ProcessTiles(this.start, point, BaseTileSelector.ProcessMode.Prpcess);
            this.mode.OnSelectEnd(false);
        }
        if (this.mode != mode)
        {
            return;
        }
        this.mode.OnAfterProcessTiles(this.start, point);
        this.start = null;
        this.ExecuteSummary();
        this.RefreshMouseInfo(true);
        this.mode.OnFinishProcessTiles();
    }
References autoClick, ActionMode.CanProcessTiles(), Point.Copy(), ExecuteSummary(), ActionMode.IsFillMode(), mode, ActionMode.OnAfterProcessTiles(), ActionMode.OnBeforeProcessTiles(), ActionMode.OnFinishProcessTiles(), ActionMode.OnProcessTiles(), ActionMode.OnSelectEnd(), ProcessFillTiles(), ProcessTiles(), RefreshMouseInfo(), EMono.screen, start, and BaseGameScreen.tileSelector.
Referenced by OnUpdate().
Member Data Documentation
autoClick
bool BaseTileSelector.autoClick
Definition at line 513 of file BaseTileSelector.cs.
Referenced by OnUpdate(), and TryProcessTiles().
firstInMulti
bool BaseTileSelector.firstInMulti
Definition at line 515 of file BaseTileSelector.cs.
inspectHitType
BaseTileSelector.HitType BaseTileSelector.inspectHitType
Definition at line 491 of file BaseTileSelector.cs.
inspectorHighlight
bool BaseTileSelector.inspectorHighlight
Definition at line 493 of file BaseTileSelector.cs.
lastClickPoint
Point BaseTileSelector.lastClickPoint = new Point()
Definition at line 507 of file BaseTileSelector.cs.
Referenced by OnUpdate().
lastPoint
Point BaseTileSelector.lastPoint = new Point()
Definition at line 504 of file BaseTileSelector.cs.
Referenced by AM_Sim._OnUpdateInput(), and RefreshMouseInfo().
processing
bool BaseTileSelector.processing
Definition at line 510 of file BaseTileSelector.cs.
Referenced by HitSummary.CanExecute().
start
Point BaseTileSelector.start
Definition at line 498 of file BaseTileSelector.cs.
Referenced by _ProcessTile(), ActionMode.GetHintText(), IsInRange(), ActionMode.OnRenderTile(), AM_Build.OnRenderTile(), ActionMode.OnRenderTileFloor(), OnUpdate(), ProcessFillTiles(), ProcessTiles(), RefreshMouseInfo(), RefreshSummary(), and TryProcessTiles().
summary
HitSummary BaseTileSelector.summary = new HitSummary()
Definition at line 495 of file BaseTileSelector.cs.
Referenced by _ProcessTile(), ExecuteSummary(), DropdownRecipe.GetLabel(), RefreshMouseInfo(), RefreshSummary(), and ButtonGrid.SetIngredient().
temp
Point BaseTileSelector.temp = new Point()
Definition at line 501 of file BaseTileSelector.cs.
Referenced by OnUpdate(), and ProcessTiles().
Property Documentation
boxType
BaseTileSelector.BoxType BaseTileSelector.boxType get
Definition at line 30 of file BaseTileSelector.cs.
    {
        get
        {
            return this.mode.boxType;
        }
    }
Referenced by ProcessTiles().
Height
int BaseTileSelector.Height get
Definition at line 78 of file BaseTileSelector.cs.
    {
        get
        {
            if (!Scene.HitPoint.IsValid)
            {
                return 0;
            }
            if (this.start != null)
            {
                return Mathf.Abs(Scene.HitPoint.z - this.start.z) + 1;
            }
            return 1;
        }
    }
hitH
int BaseTileSelector.hitH get
Definition at line 46 of file BaseTileSelector.cs.
    {
        get
        {
            return this.mode.hitH;
        }
    }
hitType
BaseTileSelector.HitType BaseTileSelector.hitType get
Definition at line 22 of file BaseTileSelector.cs.
    {
        get
        {
            return this.mode.hitType;
        }
    }
hitW
int BaseTileSelector.hitW get
Definition at line 38 of file BaseTileSelector.cs.
    {
        get
        {
            return this.mode.hitW;
        }
    }
mode
ActionMode BaseTileSelector.mode get
Definition at line 6 of file BaseTileSelector.cs.
    {
        get
        {
            return EMono.scene.actionMode;
        }
    }
Referenced by _ProcessTile(), ExecuteSummary(), OnUpdate(), RefreshMouseInfo(), and TryProcessTiles().
multisize
bool BaseTileSelector.multisize get
Definition at line 54 of file BaseTileSelector.cs.
    {
        get
        {
            return this.hitW != 1 || this.hitH != 1;
        }
    }
Referenced by ProcessTiles().
selectType
BaseTileSelector.SelectType BaseTileSelector.selectType get
Definition at line 14 of file BaseTileSelector.cs.
    {
        get
        {
            return this.mode.selectType;
        }
    }
Referenced by OnUpdate(), ProcessTiles(), and RefreshMouseInfo().
Width
int BaseTileSelector.Width get
Definition at line 62 of file BaseTileSelector.cs.
    {
        get
        {
            if (!Scene.HitPoint.IsValid)
            {
                return 0;
            }
            if (this.start != null)
            {
                return Mathf.Abs(Scene.HitPoint.x - this.start.x) + 1;
            }
            return 1;
        }
    }
The documentation for this class was generated from the following file:
Elin/BaseTileSelector.cs