Elin Decompiled Documentation: QuickMenu Class Reference
QuickMenu Class Reference
Classes
class Item
Public Member Functions
void Build ()
void Add (string id, int slot, Action action=null)
Public Attributes
List< Item > items = new List<Item>()
Detailed Description
Definition at line 5 of file QuickMenu.cs.
Member Function Documentation
Add()
void QuickMenu.Add (string id, int slot, Action action = null) inline
Definition at line 37 of file QuickMenu.cs.
    {
        items.Add(new Item
        {
            id = id,
            slot = slot,
            action = action
        });
    }
References items.
Referenced by Build().
Build()
void QuickMenu.Build () inline
Definition at line 22 of file QuickMenu.cs.
    {
        items.Clear();
        Add("Banner", 11, SE.Beep);
        Add("RemoveDesignation", 10);
        Add("Picker", 8);
        Add("StateEditor", 9);
        Add("EditArea", 3);
        Add("Inspect", 1);
        Add("Cut", 2);
        Add("Mine", 4);
        Add("Dig", 7);
        Add("DigFloor", 6);
    }
References Add(), and items.
Referenced by LayerQuickMenu.OnInit().
Member Data Documentation
items
List<Item> QuickMenu.items = new List<Item>()
Definition at line 20 of file QuickMenu.cs.
Referenced by Add(), Build(), and LayerQuickMenu.OnInit().
The documentation for this class was generated from the following file:
Elin/QuickMenu.cs