Elin Decompiled Documentation: LayerGacha Class Reference
LayerGacha Class Reference
Public Member Functions
override void OnAfterInit ()
void OnClickGoldGacha (int num)
void OnClickSilverGacha (int num)
void PlayGacha (bool gold, int num)
void RefreshCoin ()
void OnClickBuyCoin ()
override void OnKill ()
Public Member Functions inherited from ELayer
override void OnBeforeAddLayer ()
void InitInspector ()
sealed override void Init ()
override void OnAfterAddLayer ()
void TryShowHelp ()
void AddLayerToUI (string id)
void TryShowHint (string _langHint=null)
void TalkHomeMemeber (string id)
void TalkMaid (string id)
override void OnRightClick ()
Public Member Functions inherited from Layer
virtual string GetTextHeader (Window window)
virtual bool HeaderIsListOf (int id)
virtual void Init ()
virtual void OnInit ()
virtual void OnAfterInit ()
virtual void ApplySkin ()
void ShowScreenLock (string id)
void UpdateInput ()
virtual void OnUpdateInput ()
virtual void OnRightClick ()
virtual bool OnBack ()
virtual void OnChangeLayer ()
virtual void OnCreate ()
void _AddLayer (string id)
Layer AddLayer (string id)
T AddLayer< T > ()
T AddLayer< T > (string id)
T AddLayerDontCloseOthers< T > ()
Layer AddLayerDontCloseOthers (Layer l)
T GetOrAddLayer< T > ()
virtual void OnBeforeAddLayer ()
virtual void OnAfterAddLayer ()
Layer AddLayer (Layer l)
void ToggleLayer (string id)
T ToggleLayer< T > (string id=null)
void WaitAndClose ()
void OnClickClose ()
virtual void Close ()
void CloseLayers ()
void RemoveLayers (bool removeImportant=false)
bool RemoveLayer< T > ()
void RemoveLayer (Layer l)
virtual void OnKill ()
Layer SetOnKill (Action action)
void DisableClose ()
void Delay (float duration=0.05f)
Layer SetDelay (float d)
Layer GetLayer (string id)
T GetLayer< T > (bool fromTop=false)
Layer GetTopLayer ()
void SwitchContent (int idWindow, int i)
virtual void OnSwitchContent (Window window)
Layer SetTitles (string langList, string idHeaderRow=null)
bool IsBlockWidgetClick ()
bool IsHideHud ()
bool IsAllowGeneralInput ()
bool IsUseBlur ()
bool IsPointerOnLayer ()
void ApplySkin ()
Public Attributes
GameObject goFree
Color colorC
Color colorR
Color colorSR
Color colorSSR
Color colorLE
DOTweenAnimation[] randomAnimes
bool alt
UIList listCoin
Public Attributes inherited from Layer
Option option
UnityEvent onKill
Anime animeIn
Anime animeOut
bool closeOthers
bool defaultActionMode = true
Button screenLock
Layer parent
string idLayer
List< Layer > layers = new List<Layer>()
Vector2 lastParentPos
List< Window > windows = new List<Window>()
string langHint
Static Public Attributes
static GameObject slot
Static Public Attributes inherited from Layer
static int skipInput
static bool closeOnRightClick
static bool rightClicked
static bool cancelKeyDown
static bool ignoreSounds
static Transform blurStopInstance
static string[] searchPath = new string[3] { "Layer", "Layer/Dialog", "Layer/LayerHome" }
Private Member Functions
void RandomAnime ()
Additional Inherited Members
Static Public Member Functions inherited from ELayer
static int rnd (int a)
Static Public Member Functions inherited from Layer
static T Create< T > ()
static T Create< T > (string path)
static Layer Create (string path)
Protected Member Functions inherited from ELayer
sealed override void _Close ()
sealed override void Kill ()
Protected Member Functions inherited from Layer
virtual void Awake ()
virtual void _Close ()
virtual void Kill ()
Protected Attributes inherited from Layer
RectTransform _rect
bool isDestroyed
Properties inherited from ELayer
static Core core [get]
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static FactionBranch Branch [get]
static Faction Home [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static CoreConfig config [get]
static GameSetting setting [get]
static ColorProfile Colors [get]
static SourceManager sources [get]
static World world [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
bool IsFloat [get]
virtual string IdHelp [get]
Properties inherited from Layer
Layer TopLayer [get]
string uid [get]
virtual RectTransform rectLayers [get]
virtual bool blockWidgetClick [get]
Detailed Description
Definition at line 4 of file LayerGacha.cs.
Member Function Documentation
OnAfterInit()
override void LayerGacha.OnAfterInit () inline virtual
Reimplemented from Layer.
Definition at line 26 of file LayerGacha.cs.
    {
        Msg.TalkHomeMemeber("layerGacha");
        if (alt)
        {
            ActionMode.NoMap.Activate();
        }
        RefreshCoin();
        InvokeRepeating("RandomAnime", 2f, 2f);
    }
References ActionMode.Activate(), alt, ActionMode.NoMap, RefreshCoin(), and Msg.TalkHomeMemeber().
OnClickBuyCoin()
void LayerGacha.OnClickBuyCoin () inline
Definition at line 172 of file LayerGacha.cs.
    {
        SE.Beep();
    }
OnClickGoldGacha()
void LayerGacha.OnClickGoldGacha (int num) inline
Definition at line 42 of file LayerGacha.cs.
    {
        PlayGacha(gold: true, num);
    }
References PlayGacha().
OnClickSilverGacha()
void LayerGacha.OnClickSilverGacha (int num) inline
Definition at line 47 of file LayerGacha.cs.
    {
        PlayGacha(gold: false, num);
    }
References PlayGacha().
OnKill()
override void LayerGacha.OnKill () inline virtual
Reimplemented from Layer.
Definition at line 177 of file LayerGacha.cs.
    {
        if (alt)
        {
            ActionMode.DefaultMode.Activate();
        }
    }
References ActionMode.Activate(), alt, and ActionMode.DefaultMode.
PlayGacha()
void LayerGacha.PlayGacha (bool gold, int num) inline
Definition at line 52 of file LayerGacha.cs.
    {
        Thing thing = null;
        if (ELayer.player.dailyGacha && !gold && num == 1)
        {
            ELayer.player.dailyGacha = false;
        }
        else
        {
            thing = ELayer.pc.things.Find("gacha_coin", gold ? "gold" : "silver");
            if (thing == null || thing.Num < num)
            {
                SE.Beep();
                return;
            }
            thing.ModNum(-num);
        }
        RefreshCoin();
        Dialog d = Layer.Create("DialogGacha") as Dialog;
        d.windows[0].setting.textCaption = "confirm".lang();
        d.note.AddPrefab("Media/Graphics/Image/IllustGacha");
        d.note.Space();
        bool lose = true;
        for (int i = 0; i < num; i++)
        {
            int num2 = 1;
            if (ELayer.rnd(6) == 0)
            {
                num2 = 2;
            }
            if (ELayer.rnd(30) == 0)
            {
                num2 = 3;
            }
            if (ELayer.rnd(100) == 0)
            {
                num2 = 4;
            }
            if (ELayer.rnd(1000) == 0)
            {
                num2 = 5;
            }
            if (gold)
            {
                num2++;
            }
            if (i == 9)
            {
                if (gold)
                {
                    if (num2 < 4)
                    {
                        num2 = 4;
                    }
                }
                else if (num2 < 3)
                {
                    num2 = 3;
                }
            }
            if (num2 > 5)
            {
                num2 = 5;
            }
            Hoard.Item item = ELayer.player.hoard.AddRandom(num2);
            int rarity = item.Source.rarity;
            if (rarity == 4 || rarity == 5)
            {
                lose = false;
            }
            d.note.AddText(null, item.Name(1), ELayer.Colors.GetRarityColor(rarity));
        }
        d.note.Space();
        if (thing == null)
        {
            d.note.AddText("dailyGacha".lang() + "  1 > 0");
        }
        else
        {
            d.note.AddText(thing.NameSimple + "  " + (thing.Num + num) + " > " + thing.Num);
        }
        d.note.Build();
        d.windows[0].Find<Transform>("GachaAnime").SetActive(enable: true);
        d.list.AddButton(null, Lang.Get("ok"), delegate
        {
            d.Close();
        });
        ELayer.ui.AddLayer(d);
        ELayer.Sound.Play("gacha");
        TweenUtil.Delay(0.5f, delegate
        {
            ELayer.Sound.Play(lose ? "gacha_lose" : "gacha_win");
        });
        d.SetOnKill(delegate
        {
            if (!lose)
            {
                Msg.TalkHomeMemeber("ding_other");
            }
        });
    }
References UIButtonList.AddButton(), UINote.AddPrefab(), Hoard.AddRandom(), UINote.AddText(), UINote.Build(), ELayer.Colors, Layer.Create(), Player.dailyGacha, ThingContainer.Find(), Lang.Get(), ColorProfile.GetRarityColor(), Player.hoard, item, Dialog.list, Card.ModNum(), Card.NameSimple, Dialog.note, Card.Num, ELayer.pc, ELayer.player, RefreshCoin(), ELayer.rnd(), Layer.SetOnKill(), ELayer.Sound, UINote.Space(), Msg.TalkHomeMemeber(), Card.things, ELayer.ui, and Layer.windows.
Referenced by OnClickGoldGacha(), and OnClickSilverGacha().
RandomAnime()
void LayerGacha.RandomAnime () inline private
Definition at line 37 of file LayerGacha.cs.
    {
        randomAnimes.RandomItem().DORestart();
    }
References randomAnimes.
RefreshCoin()
void LayerGacha.RefreshCoin () inline
Definition at line 154 of file LayerGacha.cs.
    {
        goFree.SetActive(ELayer.player.dailyGacha);
        listCoin.Clear();
        listCoin.callbacks = new UIList.Callback<Thing, ButtonGrid>
        {
            onInstantiate = delegate(Thing a, ButtonGrid b)
            {
                b.SetCard(a);
            },
            onClick = delegate(Thing a, ButtonGrid b)
            {
                ELayer.ui.AddLayer<LayerInfo>().Set(a);
            }
        };
        listCoin.Refresh();
    }
References UIList.Clear(), Player.dailyGacha, goFree, listCoin, ELayer.player, UIList.Refresh(), ButtonGrid.SetCard(), and ELayer.ui.
Referenced by OnAfterInit(), and PlayGacha().
Member Data Documentation
alt
bool LayerGacha.alt
Definition at line 22 of file LayerGacha.cs.
Referenced by OnAfterInit(), and OnKill().
colorC
Color LayerGacha.colorC
Definition at line 10 of file LayerGacha.cs.
colorLE
Color LayerGacha.colorLE
Definition at line 18 of file LayerGacha.cs.
colorR
Color LayerGacha.colorR
Definition at line 12 of file LayerGacha.cs.
colorSR
Color LayerGacha.colorSR
Definition at line 14 of file LayerGacha.cs.
colorSSR
Color LayerGacha.colorSSR
Definition at line 16 of file LayerGacha.cs.
goFree
GameObject LayerGacha.goFree
Definition at line 8 of file LayerGacha.cs.
Referenced by RefreshCoin().
listCoin
UIList LayerGacha.listCoin
Definition at line 24 of file LayerGacha.cs.
Referenced by RefreshCoin().
randomAnimes
DOTweenAnimation [] LayerGacha.randomAnimes
Definition at line 20 of file LayerGacha.cs.
Referenced by RandomAnime().
slot
GameObject LayerGacha.slot static
Definition at line 6 of file LayerGacha.cs.
The documentation for this class was generated from the following file:
Elin/LayerGacha.cs