Elin Decompiled Documentation: WidgetStatsBar Class Reference
WidgetStatsBar Class Reference
Classes
class Extra
class Item
Public Member Functions
override object CreateExtra ()
override void OnActivate ()
void Build ()
UIItem Add (Element ele, string id="", Sprite sprite=null, Func< string > func=null, Func< FontColor > funcCol=null, Func< bool > funcShow=null)
void Refresh ()
override void OnSetContextMenu (UIContextMenu m)
override void OnApplySkin ()
Public Member Functions inherited from Widget
void Test ()
bool IsInRightMode ()
void Activate ()
void RefreshOrder ()
virtual void OnActivate ()
virtual object CreateExtra ()
void Deactivate ()
virtual void OnDeactivate ()
void Close ()
void Reactivate ()
virtual void OnManagerActivate ()
virtual void OnManagerDeactivate ()
void SetAnchor (RectPosition p)
void SetPivot (RectPosition p)
virtual void OnChangePivot ()
void UpdateConfig ()
virtual void OnUpdateConfig ()
void ClampToScreen ()
virtual void OnChangeResolution ()
void OnChangePosition ()
virtual void OnChangeActionMode ()
virtual void OnFlip ()
bool IsAlignTop ()
Layer AddLayer (Layer l, Transform trans)
void RefreshTipPivotPosition ()
SkinSet GetSkin ()
SkinConfig GetSkinConfig ()
void SetSkin (int id, int v=0)
void TestSkin ()
virtual void ApplySkin ()
virtual void OnApplySkin ()
void InstantiateDeco (SkinDeco deco)
void AddDeco (SkinDeco deco)
void RemoveDeco (SkinDeco deco)
virtual bool CanShowContextMenu ()
void ShowContextMenu ()
void SetBaseContextMenu (UIContextMenu m)
virtual void OnSetContextMenu (UIContextMenu m)
void SetGridContextMenu (UIContextMenu m)
void SoundActivate ()
void OnChangeResolution ()
SkinSet GetSkin ()
SkinConfig GetSkinConfig ()
Public Attributes
LayoutGroup layout
List< Item > items = new List<Item>()
Sprite iconMoney
Sprite iconMoney2
Sprite iconPlat
Sprite iconMedal
Sprite iconKarma
Sprite iconWeight
Sprite iconInfluence
Sprite iconMaxAlly
Sprite iconGodMood
Sprite iconHearth
Sprite iconTourismValue
Sprite iconFame
Sprite iconDvPv
Sprite iconMaxMinion
Sprite iconFertility
Sprite iconElec
Public Attributes inherited from Widget
Image imageBG
SoundData soundActivate
UIDragPanel dragPanel
RectTransform tipPivotLeft
RectTransform tipPivotRight
Static Public Attributes
static WidgetStatsBar Instance
Static Public Attributes inherited from EMono
static Core core
Properties
Extra extra [get]
Color colorDefault [get]
Color colorBad [get]
Color colorVeryBad [get]
Properties inherited from Widget
string ID [get]
Config config [get]
SkinRoot skinRoot [get]
bool IsSealed [get]
virtual bool ShowStyleMenu [get]
virtual bool AlwaysTop [get]
virtual bool IsStaticPosition [get]
virtual bool AlwaysBottom [get]
virtual Type SetSiblingAfter [get]
virtual bool ShowInBuildMode [get]
virtual bool RightClickToClose [get]
virtual bool AllowRightClickToClose [get]
Properties inherited from EMono
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SoundManager Sound [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static CoreDebug debug [get]
Private Attributes
UIItem mold
Additional Inherited Members
Public Types inherited from Widget
enum WidgetType { Default , ZoomMenu }
enum State { Active , Inactive }
Static Public Member Functions inherited from EMono
static int rnd (int a)
Protected Member Functions inherited from Widget
void ClampToScreenEnsured (Component c, Vector2 anchoredPos)
void ClampToScreen (RectTransform rect, float margin=10f)
Protected Attributes inherited from Widget
bool flip
Detailed Description
Definition at line 6 of file WidgetStatsBar.cs.
Member Function Documentation
Add()
UIItem WidgetStatsBar.Add (Element ele, string id = "", Sprite sprite = null, Func< string > func = null, Func< FontColor > funcCol = null, Func< bool > funcShow = null) inline
Definition at line 229 of file WidgetStatsBar.cs.
    {
        UIItem uIItem = Util.Instantiate(mold, layout);
        Item item = new Item
        {
            ele = ele,
            component = uIItem,
            id = id,
            func = func,
            funcCol = funcCol,
            funcShow = funcShow
        };
        if ((bool)sprite)
        {
            uIItem.image1.sprite = sprite;
        }
        else
        {
            uIItem.image1.sprite = ele.GetIcon("_m");
        }
        uIItem.image1.SetNativeSize();
        uIItem.text1.skinRoot = base.skinRoot;
        Shadow component = uIItem.text1.GetComponent<Shadow>();
        if ((bool)component)
        {
            component.enabled = base.config.skin.BG.textShadow;
        }
        items.Add(item);
        return uIItem;
    }
References Element.GetIcon(), UIItem.image1, item, UIItem.text1, and Util.
Referenced by Build().
Build()
void WidgetStatsBar.Build () inline
Definition at line 129 of file WidgetStatsBar.cs.
    {
        items.Clear();
        layout.DestroyChildren();
        if (extra.attributes)
        {
            foreach (Element item in EMono.pc.elements.ListElements((Element e) => e.HasTag("primary")))
            {
                Add(item);
            }
            Add(EMono.pc.elements.GetElement(79));
        }
        if (extra.dv)
        {
            Add(null, "dvpv", iconDvPv, () => EMono.pc.DV + "/" + EMono.pc.PV);
        }
        if (extra.maxAlly)
        {
            Add(null, "maxAlly", iconMaxAlly, () => EMono.pc.party.members.Count - 1 + "/" + EMono.player.MaxAlly, () => (EMono.player.lastEmptyAlly >= 0) ? FontColor.Default : FontColor.Bad);
        }
        if (extra.maxMinion)
        {
            Add(null, "maxMinion", iconMaxMinion, () => EMono._zone.CountMinions(EMono.pc) + "/" + EMono.pc.MaxSummon, () => (EMono.pc.MaxSummon - EMono._zone.CountMinions(EMono.pc) >= 0) ? FontColor.Default : FontColor.Bad);
        }
        if (extra.money)
        {
            Add(null, "money", iconMoney, () => EMono.pc.GetCurrency().ToString("#,0") ?? "");
        }
        if (extra.money2)
        {
            Add(null, "money2", iconMoney2, () => EMono.pc.GetCurrency("money2").ToString("#,0") ?? "");
        }
        if (extra.plat)
        {
            Add(null, "plat", iconPlat, () => EMono.pc.GetCurrency("plat").ToString("#,0") ?? "");
        }
        if (extra.medal)
        {
            Add(null, "medal", iconMedal, () => EMono.pc.GetCurrency("medal").ToString("#,0") ?? "");
        }
        if (extra.karma)
        {
            Add(null, "karma", iconKarma, () => EMono.player.karma.ToString() ?? "");
        }
        if (extra.mood)
        {
            Add(null, "mood", iconGodMood, () => EMono.pc.faith.TextMood ?? "");
        }
        if (extra.fame)
        {
            Add(null, "fame", iconFame, () => EMono.player.fame.ToFormat());
        }
        if (extra.influence)
        {
            Add(null, "influence", iconInfluence, () => EMono._zone.influence.ToFormat(), null, () => EMono._zone.influence != 0);
        }
        if (extra.tourism_value)
        {
            Add(null, "tourism_value", iconTourismValue, () => (EMono.Branch != null) ? EMono.Branch.tourism.ToFormat() : "", null, () => EMono._zone.IsPCFaction);
        }
        if (extra.hearthLv)
        {
            Add(null, "hearth_lv", iconHearth, () => (EMono.Branch != null) ? EMono.Branch.TextLv : "", () => (EMono.Branch != null && EMono.Branch.exp < EMono.Branch.GetNextExp()) ? FontColor.Default : FontColor.Good, () => EMono._zone.IsPCFaction);
        }
        if (extra.fertility)
        {
            Add(null, "fertility", iconFertility, delegate
            {
                object obj;
                if (EMono.Branch != null || EMono._zone is Zone_Tent)
                {
                    obj = (EMono._zone.MaxSoil - EMono._zone.GetSoilCost()).ToString();
                    if (obj == null)
                    {
                        return "";
                    }
                }
                else
                {
                    obj = "";
                }
                return (string)obj;
            }, () => ((EMono.Branch == null && !(EMono._zone is Zone_Tent)) || EMono._zone.MaxSoil - EMono._zone.GetSoilCost() >= 0) ? FontColor.Default : FontColor.Bad, () => EMono._zone.IsPCFaction || EMono._zone is Zone_Tent);
        }
        if (extra.elec)
        {
            Add(null, "elec", iconElec, () => (EMono.Branch != null || EMono._zone is Zone_Tent) ? (EMono._zone.GetElectricity(cost: true) + " / " + EMono._zone.GetElectricity()) : "", () => ((EMono.Branch == null && !(EMono._zone is Zone_Tent)) || EMono._zone.GetElectricity() - EMono._zone.GetElectricity(cost: true) >= 0) ? FontColor.Default : FontColor.Bad, () => EMono._zone.IsPCFaction || EMono._zone is Zone_Tent);
        }
        if (extra.weight)
        {
            Add(null, "weight", iconWeight, () => ((float)EMono.pc.ChildrenWeight / 1000f).ToString("F1") + " / " + ((float)EMono.pc.WeightLimit / 1000f).ToString("F1"), () => EMono.pc.burden.GetPhase() switch
            {
                1 => FontColor.Warning,
                0 => FontColor.Default,
                _ => FontColor.Bad,
            });
        }
        Refresh();
    }
References EMono._zone, Add(), WidgetStatsBar.Extra.attributes, EMono.Branch, Zone.CountMinions(), Chara.DV, WidgetStatsBar.Extra.dv, Card.elements, FactionBranch.exp, extra, Chara.faith, Player.fame, WidgetStatsBar.Extra.fame, WidgetStatsBar.Extra.fertility, Card.GetCurrency(), ElementContainer.GetElement(), FactionBranch.GetNextExp(), Zone.GetSoilCost(), Element.HasTag(), WidgetStatsBar.Extra.hearthLv, iconDvPv, iconFame, iconFertility, iconGodMood, iconHearth, iconInfluence, iconKarma, iconMaxAlly, iconMaxMinion, iconMedal, iconMoney, iconMoney2, iconPlat, iconTourismValue, Spatial.influence, WidgetStatsBar.Extra.influence, Zone.IsPCFaction, item, items, Player.karma, WidgetStatsBar.Extra.karma, Player.lastEmptyAlly, layout, ElementContainer.ListElements(), Player.MaxAlly, WidgetStatsBar.Extra.maxAlly, WidgetStatsBar.Extra.maxMinion, Zone.MaxSoil, Chara.MaxSummon, WidgetStatsBar.Extra.medal, Party.members, WidgetStatsBar.Extra.money, WidgetStatsBar.Extra.money2, WidgetStatsBar.Extra.mood, Chara.party, EMono.pc, WidgetStatsBar.Extra.plat, EMono.player, Chara.PV, FactionBranch.TextLv, Religion.TextMood, FactionBranch.tourism, and WidgetStatsBar.Extra.tourism_value.
Referenced by OnActivate().
CreateExtra()
override object WidgetStatsBar.CreateExtra () inline virtual
Reimplemented from Widget.
Definition at line 112 of file WidgetStatsBar.cs.
    {
        return new Extra();
    }
Referenced by OnActivate().
OnActivate()
override void WidgetStatsBar.OnActivate () inline virtual
Reimplemented from Widget.
Definition at line 117 of file WidgetStatsBar.cs.
    {
        Instance = this;
        mold = layout.CreateMold<UIItem>();
        if (extra == null)
        {
            base.config.extra = CreateExtra();
        }
        Build();
        InvokeRepeating("Refresh", 0.2f, 0.2f);
    }
References Build(), CreateExtra(), extra, Instance, layout, and mold.
OnApplySkin()
override void WidgetStatsBar.OnApplySkin () inline virtual
Reimplemented from Widget.
Definition at line 407 of file WidgetStatsBar.cs.
    {
        base.OnApplySkin();
        Build();
    }
References Build.
OnSetContextMenu()
override void WidgetStatsBar.OnSetContextMenu (UIContextMenu m) inline virtual
Reimplemented from Widget.
Definition at line 313 of file WidgetStatsBar.cs.
    {
        UIContextMenu uIContextMenu = m.AddChild("setting");
        uIContextMenu.AddToggle("attributes", extra.attributes, delegate(bool a)
        {
            extra.attributes = a;
            Build();
        });
        uIContextMenu.AddToggle("dvpv", extra.dv, delegate(bool a)
        {
            extra.dv = a;
            Build();
        });
        uIContextMenu.AddToggle("maxAlly", extra.maxAlly, delegate(bool a)
        {
            extra.maxAlly = a;
            Build();
        });
        uIContextMenu.AddToggle("maxMinion", extra.maxMinion, delegate(bool a)
        {
            extra.maxMinion = a;
            Build();
        });
        uIContextMenu.AddToggle("money", extra.money, delegate(bool a)
        {
            extra.money = a;
            Build();
        });
        uIContextMenu.AddToggle("money2", extra.money2, delegate(bool a)
        {
            extra.money2 = a;
            Build();
        });
        uIContextMenu.AddToggle("plat", extra.plat, delegate(bool a)
        {
            extra.plat = a;
            Build();
        });
        uIContextMenu.AddToggle("medal", extra.medal, delegate(bool a)
        {
            extra.medal = a;
            Build();
        });
        uIContextMenu.AddToggle("karma", extra.karma, delegate(bool a)
        {
            extra.karma = a;
            Build();
        });
        uIContextMenu.AddToggle("fame", extra.fame, delegate(bool a)
        {
            extra.fame = a;
            Build();
        });
        uIContextMenu.AddToggle("influence", extra.influence, delegate(bool a)
        {
            extra.influence = a;
            Build();
        });
        if ((bool)EMono.debug)
        {
            uIContextMenu.AddToggle("godMood", extra.mood, delegate(bool a)
            {
                extra.mood = a;
                Build();
            });
        }
        uIContextMenu.AddToggle("tourism_value", extra.tourism_value, delegate(bool a)
        {
            extra.tourism_value = a;
            Build();
        });
        uIContextMenu.AddToggle("hearth_lv", extra.hearthLv, delegate(bool a)
        {
            extra.hearthLv = a;
            Build();
        });
        uIContextMenu.AddToggle("fertility", extra.fertility, delegate(bool a)
        {
            extra.fertility = a;
            Build();
        });
        uIContextMenu.AddToggle("elec", extra.elec, delegate(bool a)
        {
            extra.elec = a;
            Build();
        });
        uIContextMenu.AddToggle("invWeight", extra.weight, delegate(bool a)
        {
            extra.weight = a;
            Build();
        });
        SetBaseContextMenu(m);
    }
References UIContextMenu.AddChild(), UIContextMenu.AddToggle(), WidgetStatsBar.Extra.attributes, Build, EMono.debug, WidgetStatsBar.Extra.dv, WidgetStatsBar.Extra.elec, WidgetStatsBar.Extra.fame, WidgetStatsBar.Extra.fertility, WidgetStatsBar.Extra.hearthLv, WidgetStatsBar.Extra.influence, WidgetStatsBar.Extra.karma, WidgetStatsBar.Extra.maxAlly, WidgetStatsBar.Extra.maxMinion, WidgetStatsBar.Extra.medal, WidgetStatsBar.Extra.money, WidgetStatsBar.Extra.money2, WidgetStatsBar.Extra.mood, WidgetStatsBar.Extra.plat, WidgetStatsBar.Extra.tourism_value, and WidgetStatsBar.Extra.weight.
Refresh()
void WidgetStatsBar.Refresh () inline
Definition at line 260 of file WidgetStatsBar.cs.
    {
        bool flag = false;
        foreach (Item item in items)
        {
            string text = item.component.text1.text;
            string text2 = "";
            FontColor fontColor = FontColor.Default;
            if (!item.id.IsEmpty())
            {
                text2 = item.func();
                if (item.funcCol != null)
                {
                    fontColor = item.funcCol();
                }
            }
            else
            {
                Element ele = item.ele;
                text2 = ele.DisplayValue.ToString() ?? "";
                if (ele.DisplayValue < ele.ValueWithoutLink)
                {
                    text2 = text2 + " (" + ele.ValueWithoutLink + ")";
                }
                int num = ((EMono.pc.tempElements != null) ? EMono.pc.tempElements.Value(ele.id) : 0);
                if (ele.DisplayValue < ele.ValueWithoutLink || num < 0)
                {
                    fontColor = FontColor.Bad;
                }
                else if (num > 0)
                {
                    fontColor = FontColor.Good;
                }
            }
            if (text2 != text || item.lastColor != fontColor)
            {
                item.component.text1.SetText(text2, fontColor);
                item.component.RebuildLayout();
                flag = true;
                item.lastColor = fontColor;
            }
            if (item.funcShow != null)
            {
                item.component.SetActive(item.funcShow());
            }
        }
        if (flag)
        {
            layout.RebuildLayout();
            this.RebuildLayout();
        }
    }
References Element.DisplayValue, Element.id, item, EMono.pc, Chara.tempElements, ElementContainer.Value(), and Element.ValueWithoutLink.
Member Data Documentation
iconDvPv
Sprite WidgetStatsBar.iconDvPv
Definition at line 94 of file WidgetStatsBar.cs.
Referenced by Build().
iconElec
Sprite WidgetStatsBar.iconElec
Definition at line 100 of file WidgetStatsBar.cs.
iconFame
Sprite WidgetStatsBar.iconFame
Definition at line 92 of file WidgetStatsBar.cs.
Referenced by Build().
iconFertility
Sprite WidgetStatsBar.iconFertility
Definition at line 98 of file WidgetStatsBar.cs.
Referenced by Build().
iconGodMood
Sprite WidgetStatsBar.iconGodMood
Definition at line 86 of file WidgetStatsBar.cs.
Referenced by Build().
iconHearth
Sprite WidgetStatsBar.iconHearth
Definition at line 88 of file WidgetStatsBar.cs.
Referenced by Build().
iconInfluence
Sprite WidgetStatsBar.iconInfluence
Definition at line 82 of file WidgetStatsBar.cs.
Referenced by Build().
iconKarma
Sprite WidgetStatsBar.iconKarma
Definition at line 78 of file WidgetStatsBar.cs.
Referenced by Build().
iconMaxAlly
Sprite WidgetStatsBar.iconMaxAlly
Definition at line 84 of file WidgetStatsBar.cs.
Referenced by Build().
iconMaxMinion
Sprite WidgetStatsBar.iconMaxMinion
Definition at line 96 of file WidgetStatsBar.cs.
Referenced by Build().
iconMedal
Sprite WidgetStatsBar.iconMedal
Definition at line 76 of file WidgetStatsBar.cs.
Referenced by Build().
iconMoney
Sprite WidgetStatsBar.iconMoney
Definition at line 70 of file WidgetStatsBar.cs.
Referenced by Build().
iconMoney2
Sprite WidgetStatsBar.iconMoney2
Definition at line 72 of file WidgetStatsBar.cs.
Referenced by Build().
iconPlat
Sprite WidgetStatsBar.iconPlat
Definition at line 74 of file WidgetStatsBar.cs.
Referenced by Build().
iconTourismValue
Sprite WidgetStatsBar.iconTourismValue
Definition at line 90 of file WidgetStatsBar.cs.
Referenced by Build().
iconWeight
Sprite WidgetStatsBar.iconWeight
Definition at line 80 of file WidgetStatsBar.cs.
Instance
WidgetStatsBar WidgetStatsBar.Instance static
Definition at line 64 of file WidgetStatsBar.cs.
Referenced by OnActivate().
items
List<Item> WidgetStatsBar.items = new List<Item>()
Definition at line 68 of file WidgetStatsBar.cs.
Referenced by Build().
layout
LayoutGroup WidgetStatsBar.layout
Definition at line 66 of file WidgetStatsBar.cs.
Referenced by Build(), and OnActivate().
mold
UIItem WidgetStatsBar.mold private
Definition at line 102 of file WidgetStatsBar.cs.
Referenced by OnActivate().
Property Documentation
colorBad
Color WidgetStatsBar.colorBad get
Definition at line 108 of file WidgetStatsBar.cs.
colorDefault
Color WidgetStatsBar.colorDefault get
Definition at line 106 of file WidgetStatsBar.cs.
colorVeryBad
Color WidgetStatsBar.colorVeryBad get
Definition at line 110 of file WidgetStatsBar.cs.
extra
Extra WidgetStatsBar.extra get
Definition at line 104 of file WidgetStatsBar.cs.
Referenced by Build(), and OnActivate().
The documentation for this class was generated from the following file:
Elin/WidgetStatsBar.cs