Elin Decompiled Documentation: LayerFeedback Class Reference
LayerFeedback Class Reference
Public Member Functions
override void OnInit ()
void Validate ()
void CollectFiles ()
void OnCancel ()
void Submit ()
void OnSubmit ()
string GetSystemText ()
Public Member Functions inherited from ELayer
override void OnBeforeAddLayer ()
void InitInspector ()
sealed override void Init ()
override void OnAfterAddLayer ()
void TryShowHelp ()
void AddLayerToUI (string id)
void TryShowHint (string _langHint=null)
void TalkHomeMemeber (string id)
void TalkMaid (string id)
override void OnRightClick ()
Public Attributes
UIText textProgress
InputField inputVersion
InputField inputName
InputField inputEmail
InputField inputLang
InputField inputSummary
InputField inputDetail
FeedbackForm form
DebugLogCollector collector
Transform transUpload
UIDropdown ddSave
Toggle toggleSave
Toggle toggleScreenshot
GameIndex saveIndex
CanvasGroup cgForm
CategoryDropdown category
Button buttonSubmit
UIButton buttonLinkFAQ
UIButton buttonLinkDiscord
Static Public Attributes
static string lastSummary = ""
static string lastDetail = ""
static string steamName = ""
static string userName = ""
static string backerId = ""
static int playedHours
Static Package Functions
static void< OnInit > g__Append (string text, ref LayerFeedback.<>c__DisplayClass25_0 A_1)
static void< CollectFiles > g__ParseLog (string path, ref LayerFeedback.<>c__DisplayClass27_0 A_1)
static int< CollectFiles > g__CountString (string s, string c)
static void< GetSystemText > g__Append (string s, ref LayerFeedback.<>c__DisplayClass31_0 A_1)
Additional Inherited Members
Static Public Member Functions inherited from ELayer
static int rnd (int a)
Protected Member Functions inherited from ELayer
sealed override void _Close ()
sealed override void Kill ()
Properties inherited from ELayer
static Core core [get]
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static FactionBranch Branch [get]
static Faction Home [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static CoreConfig config [get]
static GameSetting setting [get]
static ColorProfile Colors [get]
static SourceManager sources [get]
static World world [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
bool IsFloat [get]
virtual string IdHelp [get]
Detailed Description
Definition at line 14 of file LayerFeedback.cs.
Member Function Documentation
CollectFiles()
void LayerFeedback.CollectFiles () inline
Definition at line 148 of file LayerFeedback.cs.
    {
        ReportTitle.ignore = false;
        ReportTitle.strAdd = "";
        TextField.strAddText = "";
        string str = Application.persistentDataPath + "/";
        string text = str + "_temp";
        string text2 = text + "/log.zip";
        IO.CreateDirectory(text);
        IO.Copy(str + "Player.log", text);
        IO.Copy(str + "Player-prev.log", text);
        IO.SaveText(text + "/System.txt", this.GetSystemText());
        LayerFeedback.<>c__DisplayClass27_0 CS$<>8__locals1;
        CS$<>8__locals1.errors = 0;
        LayerFeedback.<CollectFiles>g__ParseLog|27_0(text + "/Player.log", ref CS$<>8__locals1);
        LayerFeedback.<CollectFiles>g__ParseLog|27_0(text + "/Player-prev.log", ref CS$<>8__locals1);
        ReportTitle.strAdd = ((CS$<>8__locals1.errors == 0) ? "" : ("(" + CS$<>8__locals1.errors.ToString() + ")"));
        if (ELayer.debug.enable)
        {
            ReportTitle.strAdd += "(debug)";
        }
        string text3 = this.inputDetail.text;
        int num = 0;
        foreach (string c in new string[]
        {
            "シーラカンス",
            "ナーフ",
            "つまらない",
            "面白くない",
            "不合理",
            "やめて",
            "無駄",
            "弱体化",
            "不親切",
            "クソ",
            "糞",
            "バカ",
            "馬鹿",
            "coelacanth",
            "nerf",
            "boring",
            "please don't",
            "waste",
            "fuck",
            "suck",
            "tbh",
            "shit",
            "stupid"
        })
        {
            num += LayerFeedback.<CollectFiles>g__CountString|27_1(text3, c);
        }
        if (num > 0)
        {
            ReportTitle.strAdd = "[ignore:" + num.ToString() + "]";
            ReportTitle.strAdd = string.Concat(new string[]
            {
                ReportTitle.strAdd,
                " ",
                LayerFeedback.steamName,
                "/",
                LayerFeedback.userName,
                "/",
                LayerFeedback.backerId
            });
            ReportTitle.ignore = true;
        }
        using (ZipFile zipFile = new ZipFile())
        {
            zipFile.ExtractExistingFile = ExtractExistingFileAction.OverwriteSilently;
            zipFile.AddDirectory(text);
            zipFile.Save(text2);
        }
        this.form.CurrentReport.AttachFile("log.zip", File.ReadAllBytes(text2));
        if (this.toggleSave.isOn)
        {
            string text4 = text + "/save.zip";
            using (ZipFile zipFile2 = new ZipFile())
            {
                zipFile2.ExtractExistingFile = ExtractExistingFileAction.OverwriteSilently;
                zipFile2.AddDirectory(GameIO.pathSaveRoot + this.saveIndex.id);
                zipFile2.Save(text4);
            }
            this.form.CurrentReport.AttachFile(this.saveIndex.id + ".zip", File.ReadAllBytes(text4));
        }
        IO.DeleteDirectory(text);
    }
References CollectFiles(), ELayer.debug, CoreDebug.enable, form, g__CountString(), g__ParseLog(), GetSystemText(), GameIndex.id, inputDetail, GameIO.pathSaveRoot, saveIndex, steamName, text, toggleSave, and userName.
Referenced by CollectFiles(), and OnInit().
g__Append() [1/2]
static void< GetSystemText > LayerFeedback.g__Append (string s, ref LayerFeedback::<>c__DisplayClass31_0 A_1) inline static package
Definition at line 349 of file LayerFeedback.cs.
    {
        A_1.txt = A_1.txt + s + Environment.NewLine;
    }
g__Append() [2/2]
static void< OnInit > LayerFeedback.g__Append (string text, ref LayerFeedback::<>c__DisplayClass25_0 A_1) inline static package
Definition at line 303 of file LayerFeedback.cs.
    {
        if (text != null)
        {
            A_1.s = A_1.s + text + Environment.NewLine;
        }
    }
References text.
Referenced by GetSystemText(), and OnInit().
g__CountString()
static int< CollectFiles > LayerFeedback.g__CountString (string s, string c) inline static package
Definition at line 342 of file LayerFeedback.cs.
    {
        string newValue = c.Substring(0, c.Length - 1);
        return s.Length - s.Replace(c, newValue).Length;
    }
Referenced by CollectFiles().
g__ParseLog()
static void< CollectFiles > LayerFeedback.g__ParseLog (string path, ref LayerFeedback::<>c__DisplayClass27_0 A_1) inline static package
Definition at line 312 of file LayerFeedback.cs.
    {
        if (!File.Exists(path))
        {
            return;
        }
        foreach (string text in IO.LoadTextArray(path))
        {
            if (!(text == "InvalidOperationException: Steamworks is not initialized."))
            {
                if (text == "InvalidOperationException: Collection was modified; enumeration operation may not execute." || text == "NullReferenceException: Object reference not set to an instance of an object")
                {
                    int errors = A_1.errors;
                    A_1.errors = errors + 1;
                }
                else if (text.Contains("exception"))
                {
                    int errors = A_1.errors;
                    A_1.errors = errors + 1;
                }
                else if (text.Contains("Exception"))
                {
                    int errors = A_1.errors;
                    A_1.errors = errors + 1;
                }
            }
        }
    }
References text.
Referenced by CollectFiles().
GetSystemText()
string LayerFeedback.GetSystemText () inline
Definition at line 285 of file LayerFeedback.cs.
    {
        LayerFeedback.<>c__DisplayClass31_0 CS$<>8__locals1;
        CS$<>8__locals1.txt = "";
        LayerFeedback.<GetSystemText>g__Append|31_0("OS: " + SystemInfo.operatingSystem, ref CS$<>8__locals1);
        LayerFeedback.<GetSystemText>g__Append|31_0("Processor: " + SystemInfo.processorType, ref CS$<>8__locals1);
        LayerFeedback.<GetSystemText>g__Append|31_0("Memory: " + SystemInfo.systemMemorySize.ToString(), ref CS$<>8__locals1);
        LayerFeedback.<GetSystemText>g__Append|31_0("Graphics API: " + SystemInfo.graphicsDeviceType.ToString(), ref CS$<>8__locals1);
        LayerFeedback.<GetSystemText>g__Append|31_0("Graphics Processor: " + SystemInfo.graphicsDeviceName, ref CS$<>8__locals1);
        LayerFeedback.<GetSystemText>g__Append|31_0("Graphics Memory: " + SystemInfo.graphicsMemorySize.ToString(), ref CS$<>8__locals1);
        LayerFeedback.<GetSystemText>g__Append|31_0("Graphics Vendor: " + SystemInfo.graphicsDeviceVendor, ref CS$<>8__locals1);
        LayerFeedback.<GetSystemText>g__Append|31_0("Quality Level: " + QualitySettings.names[QualitySettings.GetQualityLevel()], ref CS$<>8__locals1);
        LayerFeedback.<GetSystemText>g__Append|31_0("Resolution: " + Screen.width.ToString() + "x" + Screen.height.ToString(), ref CS$<>8__locals1);
        LayerFeedback.<GetSystemText>g__Append|31_0("Full Screen: " + Screen.fullScreen.ToString(), ref CS$<>8__locals1);
        return CS$<>8__locals1.txt;
    }
References g__Append(), and GetSystemText().
Referenced by CollectFiles(), and GetSystemText().
OnCancel()
void LayerFeedback.OnCancel () inline
Definition at line 236 of file LayerFeedback.cs.
    {
        LayerFeedback.lastDetail = this.inputDetail.text;
        LayerFeedback.lastSummary = this.inputSummary.text;
        this.form.Clean();
        this.Close();
    }
References form, inputDetail, and inputSummary.
OnInit()
override void LayerFeedback.OnInit () inline
Definition at line 16 of file LayerFeedback.cs.
    {
        this.inputVersion.text = string.Concat(new string[]
        {
            ELayer.core.version.GetText(),
            "/",
            ELayer.config.lang,
            " ",
            LayerFeedback.steamName,
            "/",
            LayerFeedback.userName,
            " hours:",
            LayerFeedback.playedHours.ToString(),
            " backer:",
            LayerFeedback.backerId
        });
        TextField.onAddEmail = delegate()
        {
            LayerFeedback.<>c__DisplayClass25_0 CS$<>8__locals1;
            CS$<>8__locals1.s = "";
            foreach (BaseModPackage baseModPackage in ELayer.core.mods.packages)
            {
                if (!baseModPackage.builtin)
                {
                    LayerFeedback.<OnInit>g__Append|25_8(baseModPackage.id + "/" + baseModPackage.activated.ToString(), ref CS$<>8__locals1);
                }
            }
            LayerFeedback.<OnInit>g__Append|25_8("", ref CS$<>8__locals1);
            LayerFeedback.<OnInit>g__Append|25_8("Save Path: " + CorePath.RootSave, ref CS$<>8__locals1);
            LayerFeedback.<OnInit>g__Append|25_8("EXE Path: " + CorePath.rootExe, ref CS$<>8__locals1);
            LayerFeedback.<OnInit>g__Append|25_8("OS: " + SystemInfo.operatingSystem, ref CS$<>8__locals1);
            LayerFeedback.<OnInit>g__Append|25_8("Processor: " + SystemInfo.processorType, ref CS$<>8__locals1);
            LayerFeedback.<OnInit>g__Append|25_8("Memory: " + SystemInfo.systemMemorySize.ToString(), ref CS$<>8__locals1);
            LayerFeedback.<OnInit>g__Append|25_8("Graphics API: " + SystemInfo.graphicsDeviceType.ToString(), ref CS$<>8__locals1);
            LayerFeedback.<OnInit>g__Append|25_8("Graphics Processor: " + SystemInfo.graphicsDeviceName, ref CS$<>8__locals1);
            LayerFeedback.<OnInit>g__Append|25_8("Graphics Memory: " + SystemInfo.graphicsMemorySize.ToString(), ref CS$<>8__locals1);
            LayerFeedback.<OnInit>g__Append|25_8("Graphics Vendor: " + SystemInfo.graphicsDeviceVendor, ref CS$<>8__locals1);
            LayerFeedback.<OnInit>g__Append|25_8("Quality Level: " + QualitySettings.names[QualitySettings.GetQualityLevel()], ref CS$<>8__locals1);
            LayerFeedback.<OnInit>g__Append|25_8("Resolution: " + Screen.width.ToString() + "x" + Screen.height.ToString(), ref CS$<>8__locals1);
            LayerFeedback.<OnInit>g__Append|25_8("Full Screen: " + Screen.fullScreen.ToString(), ref CS$<>8__locals1);
            LayerFeedback.<OnInit>g__Append|25_8("regionName: " + RegionInfo.CurrentRegion.Name, ref CS$<>8__locals1);
            LayerFeedback.<OnInit>g__Append|25_8("cultureName: " + CultureInfo.CurrentCulture.Name, ref CS$<>8__locals1);
            LayerFeedback.<OnInit>g__Append|25_8("cname: " + Thread.CurrentThread.CurrentCulture.Name, ref CS$<>8__locals1);
            LayerFeedback.<OnInit>g__Append|25_8("uiname: " + Thread.CurrentThread.CurrentUICulture.Name, ref CS$<>8__locals1);
            LayerFeedback.<OnInit>g__Append|25_8("device identifier: " + SystemInfo.deviceUniqueIdentifier, ref CS$<>8__locals1);
            return Environment.NewLine + Environment.NewLine + CS$<>8__locals1.s;
        };
        this.buttonLinkFAQ.SetOnClick(delegate
        {
            LayerHelp.Toggle("general", "FAQ");
        });
        this.buttonLinkDiscord.SetOnClick(delegate
        {
            SE.Click();
            Application.OpenURL("https://discord.gg/elona");
        });
        this.transUpload.SetActive(false);
        this.buttonSubmit.interactable = false;
        if (!ELayer.config.nameReport.IsEmpty())
        {
            this.inputName.text = ELayer.config.nameReport;
        }
        else if (ELayer.core.IsGameStarted)
        {
            this.inputName.text = "nameBraced".lang(ELayer.pc.NameSimple, ELayer.pc.Aka, null, null, null);
        }
        if (!ELayer.config.emailReport.IsEmpty())
        {
            this.inputEmail.text = ELayer.config.emailReport;
        }
        this.inputLang.text = ELayer.config.lang;
        this.inputDetail.text = LayerFeedback.lastDetail;
        this.inputSummary.text = LayerFeedback.lastSummary;
        this.collector.onSubmit = delegate()
        {
            this.CollectFiles();
        };
        this.category.Init((string s) => ("form_" + s).lang());
        List<GameIndex> gameList = GameIO.GetGameList(GameIO.pathSaveRoot, false);
        if (gameList.Count > 0)
        {
            int index = 0;
            this.saveIndex = gameList[0];
            for (int i = 0; i < gameList.Count; i++)
            {
                if (ELayer.core.IsGameStarted && gameList[i].id == Game.id)
                {
                    index = i;
                    this.saveIndex = gameList[i];
                }
            }
            this.ddSave.SetList<GameIndex>(index, gameList, (GameIndex a, int b) => ((ELayer.core.IsGameStarted && a.id == Game.id) ? "currentSave".lang() : "") + a.FormTitle, delegate(int a, GameIndex b)
            {
                this.saveIndex = b;
            }, true);
        }
        else
        {
            this.toggleSave.SetActive(false);
        }
        this.toggleSave.onValueChanged.AddListener(delegate(bool a)
        {
            this.ddSave.SetActive(a);
        });
        this.toggleSave.isOn = false;
        this.ddSave.SetActive(this.toggleSave.isOn);
        this.form.Init();
        this.inputDetail.onValueChanged.AddListener(delegate(string a)
        {
            this.Validate();
        });
        this.inputSummary.onValueChanged.AddListener(delegate(string a)
        {
            this.Validate();
        });
        this.Validate();
    }
References Chara.Aka, backerId, buttonLinkDiscord, buttonLinkFAQ, category, CollectFiles(), ELayer.config, ELayer.core, ddSave, CoreConfig.emailReport, form, g__Append(), GameIO.GetGameList(), Game.id, inputDetail, inputSummary, CoreConfig.lang, lastDetail, lastSummary, CoreConfig.nameReport, Card.NameSimple, OnInit(), GameIO.pathSaveRoot, ELayer.pc, playedHours, steamName, LayerHelp.Toggle(), toggleSave, transUpload, userName, and Validate().
Referenced by OnInit().
OnSubmit()
void LayerFeedback.OnSubmit () inline
Definition at line 267 of file LayerFeedback.cs.
    {
        if (!this.inputEmail.text.IsEmpty())
        {
            ELayer.config.emailReport = this.inputEmail.text;
        }
        if (!this.inputName.text.IsEmpty())
        {
            ELayer.config.nameReport = this.inputName.text;
        }
        this.transUpload.SetActive(true);
        this.form.IncludeScreenshot = this.toggleScreenshot.isOn;
        this.cgForm.alpha = 0.5f;
        this.form.transform.SetParent(ELayer.ui.transform, false);
        this.Close();
        LayerFeedback.lastDetail = (LayerFeedback.lastSummary = "");
    }
References form, inputEmail, inputName, toggleScreenshot, transUpload, and ELayer.ui.
Submit()
void LayerFeedback.Submit () inline
Definition at line 244 of file LayerFeedback.cs.
    {
        int num = 0;
        foreach (BaseModPackage baseModPackage in ELayer.core.mods.packages)
        {
            if (!baseModPackage.builtin && baseModPackage.activated)
            {
                num++;
            }
        }
        if (num > 0)
        {
            Dialog.YesNo("warn_mod".lang(num.ToString() ?? "", null, null, null, null), delegate
            {
            }, delegate
            {
                this.form.Submit();
            }, "warn_mod_yes", "warn_mod_no");
            return;
        }
        this.form.Submit();
    }
References ELayer.core, form, and Dialog.YesNo().
Validate()
void LayerFeedback.Validate () inline
Definition at line 134 of file LayerFeedback.cs.
    {
        bool interactable = true;
        if (this.inputSummary.text.Length < 4)
        {
            interactable = false;
        }
        if (this.inputDetail.text.Length < 4)
        {
            interactable = false;
        }
        this.buttonSubmit.interactable = interactable;
    }
References inputDetail, and inputSummary.
Referenced by OnInit().
Member Data Documentation
backerId
string LayerFeedback.backerId = "" static
Definition at line 362 of file LayerFeedback.cs.
Referenced by OnInit().
buttonLinkDiscord
UIButton LayerFeedback.buttonLinkDiscord
Definition at line 402 of file LayerFeedback.cs.
Referenced by OnInit().
buttonLinkFAQ
UIButton LayerFeedback.buttonLinkFAQ
Definition at line 400 of file LayerFeedback.cs.
Referenced by OnInit().
buttonSubmit
Button LayerFeedback.buttonSubmit
Definition at line 398 of file LayerFeedback.cs.
category
CategoryDropdown LayerFeedback.category
Definition at line 396 of file LayerFeedback.cs.
Referenced by OnInit().
cgForm
CanvasGroup LayerFeedback.cgForm
Definition at line 394 of file LayerFeedback.cs.
collector
DebugLogCollector LayerFeedback.collector
Definition at line 382 of file LayerFeedback.cs.
ddSave
UIDropdown LayerFeedback.ddSave
Definition at line 386 of file LayerFeedback.cs.
Referenced by OnInit().
form
FeedbackForm LayerFeedback.form
Definition at line 380 of file LayerFeedback.cs.
Referenced by CollectFiles(), OnCancel(), OnInit(), OnSubmit(), and Submit().
inputDetail
InputField LayerFeedback.inputDetail
Definition at line 378 of file LayerFeedback.cs.
Referenced by CollectFiles(), OnCancel(), OnInit(), and Validate().
inputEmail
InputField LayerFeedback.inputEmail
Definition at line 372 of file LayerFeedback.cs.
Referenced by OnSubmit().
inputLang
InputField LayerFeedback.inputLang
Definition at line 374 of file LayerFeedback.cs.
inputName
InputField LayerFeedback.inputName
Definition at line 370 of file LayerFeedback.cs.
Referenced by OnSubmit().
inputSummary
InputField LayerFeedback.inputSummary
Definition at line 376 of file LayerFeedback.cs.
Referenced by OnCancel(), OnInit(), and Validate().
inputVersion
InputField LayerFeedback.inputVersion
Definition at line 368 of file LayerFeedback.cs.
lastDetail
string LayerFeedback.lastDetail = "" static
Definition at line 356 of file LayerFeedback.cs.
Referenced by OnInit().
lastSummary
string LayerFeedback.lastSummary = "" static
Definition at line 354 of file LayerFeedback.cs.
Referenced by OnInit().
playedHours
int LayerFeedback.playedHours static
Definition at line 364 of file LayerFeedback.cs.
Referenced by OnInit().
saveIndex
GameIndex LayerFeedback.saveIndex
Definition at line 392 of file LayerFeedback.cs.
Referenced by CollectFiles().
steamName
string LayerFeedback.steamName = "" static
Definition at line 358 of file LayerFeedback.cs.
Referenced by CollectFiles(), and OnInit().
textProgress
UIText LayerFeedback.textProgress
Definition at line 366 of file LayerFeedback.cs.
toggleSave
Toggle LayerFeedback.toggleSave
Definition at line 388 of file LayerFeedback.cs.
Referenced by CollectFiles(), and OnInit().
toggleScreenshot
Toggle LayerFeedback.toggleScreenshot
Definition at line 390 of file LayerFeedback.cs.
Referenced by OnSubmit().
transUpload
Transform LayerFeedback.transUpload
Definition at line 384 of file LayerFeedback.cs.
Referenced by OnInit(), and OnSubmit().
userName
string LayerFeedback.userName = "" static
Definition at line 360 of file LayerFeedback.cs.
Referenced by CollectFiles(), and OnInit().
The documentation for this class was generated from the following file:
Elin/LayerFeedback.cs