Elin Decompiled Documentation: B83.Win32.UnityDragAndDropHook Class Reference
B83.Win32.UnityDragAndDropHook Class Reference
Public Member Functions
delegate void DroppedFilesEvent (List< string > aPathNames, POINT aDropPoint)
Static Public Member Functions
static void InstallHook ()
static void UninstallHook ()
Events
static DroppedFilesEvent OnDroppedFiles
Static Private Member Functions
static bool EnumCallback (IntPtr W, IntPtr _)
static IntPtr Callback (int code, IntPtr wParam, ref MSG lParam)
Static Private Attributes
static uint threadId
static IntPtr mainWindow = IntPtr.Zero
static IntPtr m_Hook
static string m_ClassName = "UnityWndClass"
Detailed Description
Definition at line 8 of file UnityDragAndDropHook.cs.
Member Function Documentation
Callback()
static IntPtr B83.Win32.UnityDragAndDropHook.Callback (int code, IntPtr wParam, ref MSG lParam) inline static private
Definition at line 52 of file UnityDragAndDropHook.cs.
    {
        if (code == 0 && lParam.message == WM.DROPFILES)
        {
            WinAPI.DragQueryPoint(lParam.wParam, out var pos);
            uint num = WinAPI.DragQueryFile(lParam.wParam, uint.MaxValue, null, 0u);
            StringBuilder stringBuilder = new StringBuilder(1024);
            List<string> list = new List<string>();
            for (uint num2 = 0u; num2 < num; num2++)
            {
                int num3 = (int)WinAPI.DragQueryFile(lParam.wParam, num2, stringBuilder, 1024u);
                list.Add(stringBuilder.ToString(0, num3));
                stringBuilder.Length = 0;
            }
            WinAPI.DragFinish(lParam.wParam);
            if (UnityDragAndDropHook.OnDroppedFiles != null)
            {
                UnityDragAndDropHook.OnDroppedFiles(list, pos);
            }
        }
        return WinAPI.CallNextHookEx(m_Hook, code, wParam, ref lParam);
    }
References B83.Win32.WinAPI.CallNextHookEx(), B83.Win32.WinAPI.DragFinish(), B83.Win32.WinAPI.DragQueryFile(), B83.Win32.WinAPI.DragQueryPoint(), B83.Win32.UnityDragAndDropHook.m_Hook, and B83.Win32.UnityDragAndDropHook.OnDroppedFiles.
Referenced by B83.Win32.UnityDragAndDropHook.InstallHook().
DroppedFilesEvent()
delegate void B83.Win32.UnityDragAndDropHook.DroppedFilesEvent (List< string > aPathNames, POINT aDropPoint)
EnumCallback()
static bool B83.Win32.UnityDragAndDropHook.EnumCallback (IntPtr W, IntPtr _) inline static private
Definition at line 23 of file UnityDragAndDropHook.cs.
    {
        if (Window.IsWindowVisible(W) && (mainWindow == IntPtr.Zero || (m_ClassName != null && Window.GetClassName(W) == m_ClassName)))
        {
            mainWindow = W;
        }
        return true;
    }
References B83.Win32.Window.GetClassName(), B83.Win32.Window.IsWindowVisible(), B83.Win32.UnityDragAndDropHook.m_ClassName, and B83.Win32.UnityDragAndDropHook.mainWindow.
Referenced by B83.Win32.UnityDragAndDropHook.InstallHook().
InstallHook()
static void B83.Win32.UnityDragAndDropHook.InstallHook () inline static
Definition at line 32 of file UnityDragAndDropHook.cs.
    {
        threadId = WinAPI.GetCurrentThreadId();
        if (threadId != 0)
        {
            Window.EnumThreadWindows(threadId, EnumCallback, IntPtr.Zero);
        }
        IntPtr moduleHandle = WinAPI.GetModuleHandle(null);
        m_Hook = WinAPI.SetWindowsHookEx(HookType.WH_GETMESSAGE, Callback, moduleHandle, threadId);
        WinAPI.DragAcceptFiles(mainWindow, fAccept: true);
    }
References B83.Win32.UnityDragAndDropHook.Callback(), B83.Win32.WinAPI.DragAcceptFiles(), B83.Win32.UnityDragAndDropHook.EnumCallback(), B83.Win32.Window.EnumThreadWindows(), B83.Win32.WinAPI.GetCurrentThreadId(), B83.Win32.WinAPI.GetModuleHandle(), B83.Win32.UnityDragAndDropHook.m_Hook, B83.Win32.UnityDragAndDropHook.mainWindow, B83.Win32.WinAPI.SetWindowsHookEx(), and B83.Win32.UnityDragAndDropHook.threadId.
Referenced by FileDragAndDrop.OnEnable(), and ImageExample.OnEnable().
UninstallHook()
static void B83.Win32.UnityDragAndDropHook.UninstallHook () inline static
Definition at line 44 of file UnityDragAndDropHook.cs.
    {
        WinAPI.UnhookWindowsHookEx(m_Hook);
        WinAPI.DragAcceptFiles(mainWindow, fAccept: false);
        m_Hook = IntPtr.Zero;
    }
References B83.Win32.WinAPI.DragAcceptFiles(), B83.Win32.UnityDragAndDropHook.m_Hook, B83.Win32.UnityDragAndDropHook.mainWindow, and B83.Win32.WinAPI.UnhookWindowsHookEx().
Referenced by FileDragAndDrop.OnDisable(), and ImageExample.OnDisable().
Member Data Documentation
m_ClassName
string B83.Win32.UnityDragAndDropHook.m_ClassName = "UnityWndClass" static private
Definition at line 18 of file UnityDragAndDropHook.cs.
Referenced by B83.Win32.UnityDragAndDropHook.EnumCallback().
m_Hook
IntPtr B83.Win32.UnityDragAndDropHook.m_Hook static private
Definition at line 16 of file UnityDragAndDropHook.cs.
Referenced by B83.Win32.UnityDragAndDropHook.Callback(), B83.Win32.UnityDragAndDropHook.InstallHook(), and B83.Win32.UnityDragAndDropHook.UninstallHook().
mainWindow
IntPtr B83.Win32.UnityDragAndDropHook.mainWindow = IntPtr.Zero static private
Definition at line 14 of file UnityDragAndDropHook.cs.
Referenced by B83.Win32.UnityDragAndDropHook.EnumCallback(), B83.Win32.UnityDragAndDropHook.InstallHook(), and B83.Win32.UnityDragAndDropHook.UninstallHook().
threadId
uint B83.Win32.UnityDragAndDropHook.threadId static private
Definition at line 12 of file UnityDragAndDropHook.cs.
Referenced by B83.Win32.UnityDragAndDropHook.InstallHook().
Event Documentation
OnDroppedFiles
DroppedFilesEvent B83.Win32.UnityDragAndDropHook.OnDroppedFiles static
Definition at line 20 of file UnityDragAndDropHook.cs.
Referenced by B83.Win32.UnityDragAndDropHook.Callback().
The documentation for this class was generated from the following file:
Elin/Plugins.basecore/B83/Win32/UnityDragAndDropHook.cs