Elin Decompiled Documentation: Point Class Reference
Point Class Reference
Public Member Functions
bool Within (int _x, int _z, int _w, int _h)
Chara FirstVisibleChara ()
bool HasRoomOrArea (BaseArea a)
bool IsInSpot< T > ()
bool IsPublicSpace ()
Point ()
Point (Point p)
Point (int _x, int _z)
Point (int _index)
Point Copy ()
T Copy< T > ()
Point Set (int _x, int _z)
Point Set (int index)
Point Set (Point point)
override string ToString ()
void Set (Vector3 v)
ref Vector3 PositionAuto ()
ref Vector3 Position (int height)
ref Vector3 Position ()
ref Vector3 PositionTopdown ()
ref Vector3 PositionTopdownTreasure ()
ref Vector3 PositionCenter ()
Quaternion GetRotation (Point to)
unsafe float GetAngle (Point to)
float GetAngle2 (Point to)
Point GetNearestPoint (bool allowBlock=false, bool allowChara=true, bool allowInstalled=true, bool ignoreCenter=false)
bool ForeachNearestPoint (Func< Point, bool > endFunc, bool allowBlock=false, bool allowChara=true, bool allowInstalled=true, bool ignoreCenter=false)
Point GetRandomNeighbor ()
Point GetRandomPoint (int radius, bool requireLos=true, bool allowChara=true, bool allowBlocked=false, int tries=100)
Point GetRandomPointInRadius (int minRadius, int maxRadius, bool requireLos=true, bool allowChara=true, bool allowBlocked=false, int tries=2000)
Point GetPointTowards (Point dest)
void TalkWitnesses (Chara criminal, string idTalk, int radius=4, WitnessType type=WitnessType.everyone, Func< Chara, bool > talkIf=null, int chance=3)
List< Chara > ListWitnesses (Chara criminal, int radius=4, WitnessType type=WitnessType.crime, Chara target=null)
bool TryWitnessCrime (Chara criminal, Chara target=null, int radius=4, Func< Chara, bool > funcWitness=null)
void CallGuard (Chara criminal, Chara caller)
void SetBlock (int idMat=0, int idBlock=0)
void SetFloor (int idMat=0, int idFloor=0)
void SetObj (int id=0, int value=1, int dir=0)
void ModFire (int value)
void Plow ()
bool Equals (int _x, int _z)
override bool Equals (object obj)
override int GetHashCode ()
int Distance (Point p)
int Distance (int tx, int tz)
bool IsBlockByHeight (Point p)
Point Clamp (bool useBounds=false)
List< Card > ListCards (bool includeMasked=false)
List< Card > ListVisibleCards ()
Card FindAttackTarget ()
Chara FindChara (Func< Chara, bool > func)
T FindThing< T > ()
List< Card > ListThings< T > (bool onlyInstalled=true)
List< Chara > ListCharas ()
List< Chara > ListVisibleCharas ()
List< Chara > ListCharasInNeighbor (Func< Chara, bool > func)
List< Chara > ListCharasInRadius (Chara cc, int dist, Func< Chara, bool > func)
T GetInstalled< T > ()
Effect PlayEffect (string id)
unsafe SoundSource PlaySound (string id, bool synced=true, float v=1f, bool spatial=true)
void RefreshNeighborTiles ()
void RefreshTile ()
bool HasNonHomeProperty (Thing exclude=null)
void Animate (AnimeID id, bool animeBlock=false)
RenderParam ApplyAnime (RenderParam p)
Vector3 ApplyAnime (ref Vector3 p)
List< IInspect > ListInspectorTargets ()
void ForeachMultiSize (int w, int h, Action< Point, bool > action)
void ForeachNeighbor (Action< Point > action, bool diagonal=true)
Point ToRegionPos ()
Static Public Member Functions
static Point GetShared (int x, int z)
Static Public Member Functions inherited from EClass
static int rnd (int a)
static int curve (int a, int start, int step, int rate=75)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Public Attributes
int x
int z
Static Public Attributes
static readonly XY[] Surrounds
static Vector3 fixedPos
static Point shared = new Point()
static Point shared2 = new Point()
static Point shared3 = new Point()
static Map map
static Point Invalid
static Point Zero = new Point()
static BaseGameScreen _screen
Static Public Attributes inherited from EClass
static Core core
Properties
int index [get]
Cell cell [get]
SourceMaterial.Row matRoofBlock [get]
SourceMaterial.Row matBlock [get]
SourceMaterial.Row matFloor [get]
SourceMaterial.Row matBridge [get]
SourceBlock.Row sourceRoofBlock [get]
SourceBlock.Row sourceBlock [get]
SourceFloor.Row sourceFloor [get]
SourceFloor.Row sourceBridge [get]
SourceObj.Row sourceObj [get]
CellDetail detail [get]
Area area [get]
Point Front [get]
GrowSystem growth [get]
int eloX [get]
int eloY [get]
bool HasDesignation [get]
bool HasDirt [get]
bool IsValid [get, set]
bool IsInBounds [get]
bool IsInBoundsPlus [get]
bool IsFarmField [get]
bool IsWater [get]
bool HasRamp [get]
bool HasRail [get]
bool HasRampOrLadder [get]
bool HasObj [get]
bool HasDecal [get]
bool HasBlock [get]
bool HasMinableBlock [get]
bool HasWallOrFence [get]
bool HasWall [get]
bool HasFence [get]
bool HasNonWallBlock [get]
bool HasTaskBuild [get]
bool HasBlockRecipe [get]
bool HasFloor [get]
bool HasBridge [get]
bool IsSky [get]
bool HasArea [get]
bool HasChara [get]
bool HasThing [get]
bool HasMultipleChara [get]
Chara FirstChara [get]
Thing FirstThing [get]
Thing LastThing [get]
Thing Installed [get]
List< Thing > Things [get]
List< Chara > Charas [get]
bool IsSeen [get]
bool IsSync [get]
bool IsHidden [get]
bool IsBlocked [get]
bool IsHotSpring [get]
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Private Member Functions
bool< GetNearestPoint > g__IsValid (int dx, int dz, ref Point.<>c__DisplayClass149_0 A_3)
bool< ForeachNearestPoint > g__IsValid (int dx, int dz, ref Point.<>c__DisplayClass150_0 A_3)
Private Attributes
Vector3 vCache
Static Private Attributes
static List< Card > listCard = new List<Card>()
static List< Chara > listChara = new List<Chara>()
Detailed Description
Definition at line 9 of file Point.cs.
Constructor & Destructor Documentation
Point() [1/4]
Point.Point () inline
Definition at line 544 of file Point.cs.
    {
    }
Referenced by Copy(), Equals(), ForeachNearestPoint(), GetNearestPoint(), GetPointTowards(), GetRandomNeighbor(), GetRandomPoint(), and GetRandomPointInRadius().
Point() [2/4]
Point.Point (Point p) inline
Definition at line 548 of file Point.cs.
    {
        this.x = p.x;
        this.z = p.z;
    }
References x, and z.
Point() [3/4]
Point.Point (int _x, int _z) inline
Definition at line 554 of file Point.cs.
    {
        this.x = _x;
        this.z = _z;
    }
Point() [4/4]
Point.Point (int _index) inline
Definition at line 560 of file Point.cs.
    {
        this.Set(_index);
    }
References Set().
Member Function Documentation
Animate()
void Point.Animate (AnimeID id, bool animeBlock = false) inline
Definition at line 1348 of file Point.cs.
    {
        if (!this.IsValid)
        {
            return;
        }
        CellDetail orCreateDetail = this.cell.GetOrCreateDetail();
        if (orCreateDetail.anime != null)
        {
            return;
        }
        TransAnime transAnime = new TransAnime
        {
            data = ResourceCache.Load<TransAnimeData>("Scene/Render/Anime/" + id.ToString()),
            point = this,
            animeBlock = animeBlock
        }.Init();
        orCreateDetail.anime = transAnime;
        EClass._map.pointAnimes.Add(transAnime);
        if (id == AnimeID.Quake)
        {
            transAnime.drawBlock = true;
        }
    }
References EClass._map, CellDetail.anime, and Map.pointAnimes.
Referenced by ActEffect.DamageEle(), TaskDrawWater.OnCreateProgress(), TaskHarvest.OnCreateProgress(), TaskMine.OnCreateProgress(), TaskPlow.OnCreateProgress(), TaskPourWater.OnCreateProgress(), EffectMeteor.OnPlay(), TaskCut.OnProgress(), TaskDig.OnProgressComplete(), ActBash.Perform(), and Map.Quake().
ApplyAnime() [1/2]
Vector3 Point.ApplyAnime (ref Vector3 p) inline
Definition at line 1388 of file Point.cs.
    {
        if (this.detail == null || this.detail.anime == null)
        {
            return p;
        }
        p.x += this.detail.anime.v.x;
        p.y += this.detail.anime.v.y;
        p.z += this.detail.anime.v.z;
        return p;
    }
ApplyAnime() [2/2]
RenderParam Point.ApplyAnime (RenderParam p) inline
Definition at line 1373 of file Point.cs.
    {
        if (this.detail == null || this.detail.anime == null)
        {
            return p;
        }
        p.x += this.detail.anime.v.x;
        p.y += this.detail.anime.v.y;
        p.z += this.detail.anime.v.z;
        p.v.x = p.v.x + this.detail.anime.v.x;
        p.v.y = p.v.y + this.detail.anime.v.y;
        p.v.z = p.v.z + this.detail.anime.v.z;
        return p;
    }
References RenderParam.v.
Referenced by Recipe.OnRenderMarker(), and Card.RenderMarker().
CallGuard()
void Point.CallGuard (Chara criminal, Chara caller) inline
Definition at line 979 of file Point.cs.
    {
        caller.Talk("callGuards", null, null, false);
        List<Chara> list = (from c in EClass._map.charas
        where c.trait is TraitGuard && !c.IsInCombat
        select c).ToList<Chara>();
        if (list.Count > 0)
        {
            Chara chara = list.RandomItem<Chara>();
            caller.Say("calledGuard", caller, null, null);
            chara.DoHostileAction(criminal, false);
        }
    }
References Chara.DoHostileAction(), Card.Say(), and Card.Talk().
Referenced by TryWitnessCrime().
Clamp()
Point Point.Clamp (bool useBounds = false) inline
Definition at line 1069 of file Point.cs.
    {
        if (useBounds)
        {
            if (this.x < Point.map.bounds.x)
            {
                this.x = Point.map.bounds.x;
            }
            else if (this.x >= Point.map.bounds.maxX)
            {
                this.x = Point.map.bounds.maxX;
            }
            if (this.z < Point.map.bounds.z)
            {
                this.z = Point.map.bounds.z;
            }
            else if (this.z >= Point.map.bounds.maxZ)
            {
                this.z = Point.map.bounds.maxZ;
            }
        }
        else
        {
            if (this.x < 0)
            {
                this.x = 0;
            }
            else if (this.x >= Point.map.Size)
            {
                this.x = Point.map.Size - 1;
            }
            if (this.z < 0)
            {
                this.z = 0;
            }
            else if (this.z >= Point.map.Size)
            {
                this.z = Point.map.Size - 1;
            }
        }
        return this;
    }
References Map.bounds, map, MapBounds.maxX, MapBounds.maxZ, MapBounds.Size, MapBounds.x, x, MapBounds.z, and z.
Referenced by Zone.AddGlobalCharasOnActivate(), Crawler.Crawl(), BaseTileMap.Draw(), MapGen.g___MakeNeighbor(), POIMap.Cell.GetCenter(), FactionBranch.GetMailBoxPos(), Map.GetRandomPoint(), MapBounds.GetSurface(), WidgetMinimap.OnPointerDown(), AM_Cinema.OnUpdateInput(), and GameUpdater.Update().
Copy()
Point Point.Copy () inline
Definition at line 565 of file Point.cs.
    {
        return new Point(this.x, this.z);
    }
References Point(), x, and z.
Referenced by AM_Sim._OnUpdateInput(), RoomManager.AddArea(), ActMelee.Attack(), AM_Adv.AxisMove(), AI_Shopping.Buy(), GoalManualMove.CanMove(), CoreDebug.COM_Teleport(), Crawler.Crawl(), EffectMeteor.Create(), ActEffect.DamageEle(), Player.EnterLocalZone(), AreaTypeFarm.GetAI(), Chara.GetDestination(), PathManager.GetFirstStep(), LayerInspect.GetMenuItems(), AIWork_Fish.GetWork(), Trait.ListPoints(), TraitLightSun.ListPoints(), Los.ListVisible(), Chara.MoveNeighborDefinitely(), TraitNewZone.MoveZone(), ActRush.OnMarkMapHighlights(), AM_ExpandArea.OnProcessTiles(), AM_MoveInstalled.OnProcessTiles(), TaskBuild.OnProgressComplete(), InspectGroupBlock.OnSetActions(), InspectGroupObj.OnSetActions(), BaseTileSelector.OnUpdate(), DramaManager.ParseLine(), ActRanged.Perform(), ActPlan.Item.Perform(), EffectIRenderer.Play(), Effect.Play(), AttackProcess.PlayRangedAnime(), ActEffect.ProcAt(), Map.Quake(), Religion.Reforge(), WidgetSearch.RefreshList(), SerializedCards.Restore(), AI_Fish.Run(), TaskDump.Run(), AM_Adv.SetPressedAction(), LayerCraftFloat.ShowContextMenu(), Player.SimulateFaction(), ActThrow.Throw(), RoomManager.TryAddArea(), TaskHarvest.TryGetAct(), Chara.TryMoveFrom(), BaseTileSelector.TryProcessTiles(), ActPlan.TrySetAct(), HotItemHeld.TrySetAct(), ButtonAbility.TryUse(), WidgetDebug.UpdateText(), and VirtualRoom.VirtualRoom().
Copy< T >()
T Point.Copy< T > () inline
Type Constraints
T : Point
Definition at line 570 of file Point.cs.
                               : Point
    {
        T t = Activator.CreateInstance<T>();
        t.Set(this);
        return t;
    }
References Set().
Distance() [1/2]
int Point.Distance (int tx, int tz) inline
Definition at line 1059 of file Point.cs.
    {
        return Fov.Distance(tx, tz, this.x, this.z);
    }
References Fov.Distance(), x, and z.
Distance() [2/2]
int Point.Distance (Point p) inline
Definition at line 1054 of file Point.cs.
    {
        return Fov.Distance(p.x, p.z, this.x, this.z);
    }
References Fov.Distance(), x, and z.
Referenced by TaskPoint._CanPerformTask(), PathManager._GetFirstStep(), Chara._Move(), AM_Adv._OnUpdateInput(), Effect._Play(), ActPlan._Update(), ActBash.CanPerform(), ActKick.CanPerform(), Chara.CanPick(), Chara.CanSeeLos(), Crawler.Crawl(), ActEffect.DamageEle(), Player.EnterLocalZone(), Card.g__DistMulti(), Zone_Dungeon.g__TryPlaceRail(), Zone_SnowGrave.GenerateGrave(), Los.GetNearestNeighbor(), Region.GetRandomPoint(), GetRandomPointInRadius(), Los.GetRushPoint(), ActEffect.GetTeleportPos(), AI_Haul.GetThingToClean(), AI_Goto.IsDestinationReached(), MapGen.MakeRiver(), ActRush.OnMarkMapHighlights(), AM_Terrain.OnProcessTiles(), TaskBuild.OnProgressComplete(), BaseTileSelector.OnUpdate(), AM_Cinema.OnUpdateInput(), ActPlan.Item.Perform(), AttackProcess.Prepare(), AM_Adv.RefreshArrow(), AM_Region.RefreshArrow(), Map.Reveal(), AI_Goto.Run(), GoalCombat.Run(), TaskPoint.Run(), TaskWater.Run(), AM_Adv.SetPressedAction(), RegionPoint.SetRegionPoint(), AM_Adv.ShowAllAction(), Chara.TryMoveTowards(), and AM_Adv.UpdateLangWheel().
Equals() [1/2]
bool Point.Equals (int _x, int _z) inline
Definition at line 1029 of file Point.cs.
    {
        return this.x == _x && this.z == _z;
    }
Referenced by ActPlan._Update(), Zone.Activate(), Zone.AddGlobalCharasOnActivate(), ActMelee.Attack(), GoalManualMove.CanMove(), Chara.CanReplace(), PointTarget.CheckLastTarget(), EffectMeteor.Create(), ActEffect.DamageEle(), ActionMode.DoFunc(), ActPlan.GetAction(), AI_Trolley.GetPoint(), Los.GetRushPoint(), Zone.GetSpawnPos(), ObjInfo.GetTemp(), BlockInfo.GetTempList(), ObjInfo.GetTempList(), TaskDig.GetTreasureMap(), AM_Build.HitTest(), IsInSpot< T >(), TraitShackle.IsRestraining(), Chara.MoveNeighborDefinitely(), Chara.MoveRandom(), ActRush.OnMarkMapHighlights(), TraitNewZone.OnStepped(), TraitGeneMachine.OnUse(), ActRanged.Perform(), AM_Adv.PressedActionMove(), ActEffect.Proc(), BaseTileSelector.ProcessFillTiles(), WidgetMouseover.Refresh(), AM_Adv.RefreshArrow(), BaseTileSelector.RefreshMouseInfo(), Area.RemovePoint(), SerializedCards.Restore(), AI_Idle.Run(), GoalManualMove.Run(), AM_Adv.SetPressedAction(), Zone.SpawnAltar(), Chara.Stumble(), Chara.SyncRide(), Player.TargetRanged(), ActThrow.Throw(), Chara.Tick(), AI_Goto.TryGoTo(), MapGen.TryMakeRiver(), GoalManualMove.TryMove(), Chara.TryMoveTowards(), HotItemHeld.TrySetAct(), Map.TrySmoothPick(), and CharaRenderer.UpdatePosition().
Equals() [2/2]
override bool Point.Equals (object obj) inline
Definition at line 1034 of file Point.cs.
    {
        Point point = obj as Point;
        if (point == null)
        {
            Point point2 = point;
            string str = (point2 != null) ? point2.ToString() : null;
            string str2 = ":";
            Type type = point.GetType();
            Debug.Log(str + str2 + ((type != null) ? type.ToString() : null) + "is not Point");
            return false;
        }
        return this.x == point.x && this.z == point.z;
    }
References Point(), ToString(), and z.
FindAttackTarget()
Card Point.FindAttackTarget () inline
Definition at line 1159 of file Point.cs.
    {
        foreach (Card card in this.ListCards(false))
        {
            if (card.isChara || card.trait.CanBeAttacked)
            {
                return card;
            }
        }
        return null;
    }
References Trait.CanBeAttacked, Card.isChara, ListCards(), and Card.trait.
Referenced by ActRanged.Perform(), ActThrow.Throw(), HotItemHeld.TrySetAct(), and HotItemHeld.TrySetToolAct().
FindChara()
Chara Point.FindChara (Func< Chara, bool > func) inline
Definition at line 1171 of file Point.cs.
    {
        if (this.detail != null)
        {
            foreach (Chara chara in this.detail.charas)
            {
                if (func(chara))
                {
                    return chara;
                }
            }
        }
        return null;
    }
References CellDetail.charas, and detail.
Referenced by TaskCullLife.CanPerform(), and TaskCullLife.Run().
FindThing< T >()
T Point.FindThing< T > () inline
Type Constraints
T : Trait
Definition at line 1186 of file Point.cs.
                                    : Trait
    {
        if (this.detail != null)
        {
            foreach (Thing thing in this.detail.things)
            {
                if (thing.trait is T)
                {
                    return thing.trait as T;
                }
            }
        }
        return default(T);
    }
References detail, CellDetail.things, and Card.trait.
FirstVisibleChara()
Chara Point.FirstVisibleChara () inline
Definition at line 403 of file Point.cs.
    {
        if (this.detail != null)
        {
            foreach (Chara chara in this.detail.charas)
            {
                if (EClass.pc.CanSee(chara))
                {
                    return chara;
                }
            }
        }
        return null;
    }
References Chara.CanSee(), CellDetail.charas, detail, and EClass.pc.
Referenced by HotItemHeld.TrySetAct().
ForeachMultiSize()
void Point.ForeachMultiSize (int w, int h, Action< Point, bool > action) inline
Definition at line 1433 of file Point.cs.
    {
        for (int i = 0; i < h; i++)
        {
            for (int j = 0; j < w; j++)
            {
                Point.shared3.Set(this.x - j, this.z + i);
                action(Point.shared3, j == 0 && i == 0);
            }
        }
    }
References Set(), and shared3.
Referenced by Chara.DestroyPath(), UIInspector.DrawHighlight(), TraitBoat.ForeachDeck(), HotItemHeld.OnRenderTile(), AI_HaulResource.Run(), and TaskMoveInstalled.Run().
ForeachNearestPoint()
bool Point.ForeachNearestPoint (Func< Point, bool > endFunc, bool allowBlock = false, bool allowChara = true, bool allowInstalled = true, bool ignoreCenter = false) inline
Definition at line 761 of file Point.cs.
    {
        Point.<>c__DisplayClass150_0 CS$<>8__locals1;
        CS$<>8__locals1.ignoreCenter = ignoreCenter;
        CS$<>8__locals1.<>4__this = this;
        CS$<>8__locals1.allowBlock = allowBlock;
        CS$<>8__locals1.allowChara = allowChara;
        CS$<>8__locals1.allowInstalled = allowInstalled;
        CS$<>8__locals1.p = new Point();
        int num = 1;
        int num2 = this.x;
        int num3 = this.z;
        if (this.<ForeachNearestPoint>g__IsValid|150_0(num2, num3, ref CS$<>8__locals1) && endFunc(CS$<>8__locals1.p))
        {
            return true;
        }
        if (this.<ForeachNearestPoint>g__IsValid|150_0(num2, num3 + 1, ref CS$<>8__locals1) && endFunc(CS$<>8__locals1.p))
        {
            return true;
        }
        for (int i = 0; i < 30; i++)
        {
            for (int j = 0; j < num; j++)
            {
                num2++;
                if (this.<ForeachNearestPoint>g__IsValid|150_0(num2, num3, ref CS$<>8__locals1) && endFunc(CS$<>8__locals1.p))
                {
                    return true;
                }
            }
            num++;
            for (int k = 0; k < num; k++)
            {
                num3++;
                if (this.<ForeachNearestPoint>g__IsValid|150_0(num2, num3, ref CS$<>8__locals1) && endFunc(CS$<>8__locals1.p))
                {
                    return true;
                }
            }
            for (int l = 0; l < num; l++)
            {
                num2--;
                if (this.<ForeachNearestPoint>g__IsValid|150_0(num2, num3, ref CS$<>8__locals1) && endFunc(CS$<>8__locals1.p))
                {
                    return true;
                }
            }
            num++;
            for (int m = 0; m < num; m++)
            {
                num3--;
                if (this.<ForeachNearestPoint>g__IsValid|150_0(num2, num3, ref CS$<>8__locals1) && endFunc(CS$<>8__locals1.p))
                {
                    return true;
                }
            }
        }
        Debug.Log("ForeachNearestPoint Fail:" + ((this != null) ? this.ToString() : null));
        return false;
    }
References ForeachNearestPoint(), g__IsValid(), Point(), ToString(), x, and z.
Referenced by Zone.AddGlobalCharasOnActivate(), and ForeachNearestPoint().
ForeachNeighbor()
void Point.ForeachNeighbor (Action< Point > action, bool diagonal = true) inline
Definition at line 1445 of file Point.cs.
    {
        Point point = new Point();
        for (int i = this.x - 1; i <= this.x + 1; i++)
        {
            for (int j = this.z - 1; j <= this.z + 1; j++)
            {
                if (diagonal || i == this.x || j == this.z)
                {
                    point.Set(i, j);
                    if (point.IsValid)
                    {
                        action(point);
                    }
                }
            }
        }
    }
References IsValid, and Set().
Referenced by GrowSystem.EqualizePlants(), ListCharasInNeighbor(), Chara.MoveNeighborDefinitely(), ActRanged.Perform(), and AI_Idle.Run().
g__IsValid() [1/2]
bool< GetNearestPoint > Point.g__IsValid (int dx, int dz, ref Point::<>c__DisplayClass149_0 A_3) inline private
Definition at line 1473 of file Point.cs.
    {
        A_3.p.Set(dx, dz);
        return A_3.p.IsInBounds && Point.map.Contains(dx, dz) && (!A_3.ignoreCenter || dx != this.x || dz != this.z) && (A_3.allowBlock || (!A_3.p.cell.blocked && !A_3.p.cell.hasDoor && (A_3.p.cell.growth == null || !A_3.p.cell.growth.IsTree))) && (A_3.allowChara || !A_3.p.HasChara) && (A_3.allowInstalled || A_3.p.Installed == null);
    }
References MapBounds.Contains(), map, and Set().
Referenced by ForeachNearestPoint(), and GetNearestPoint().
g__IsValid() [2/2]
bool< ForeachNearestPoint > Point.g__IsValid (int dx, int dz, ref Point::<>c__DisplayClass150_0 A_3) inline private
Definition at line 1480 of file Point.cs.
    {
        A_3.p.Set(dx, dz);
        return A_3.p.IsInBounds && Point.map.Contains(dx, dz) && (!A_3.ignoreCenter || dx != this.x || dz != this.z) && (A_3.allowBlock || (!A_3.p.cell.blocked && !A_3.p.cell.hasDoor && (A_3.p.cell.growth == null || !A_3.p.cell.growth.IsTree))) && (A_3.allowChara || !A_3.p.HasChara) && (A_3.allowInstalled || A_3.p.Installed == null);
    }
References MapBounds.Contains(), and map.
GetAngle()
unsafe float Point.GetAngle (Point to) inline
Definition at line 688 of file Point.cs.
    {
        Vector3 vector = *to.Position() - *this.Position();
        return Mathf.Atan2(vector.y, vector.x) * 57.29578f;
    }
References Position().
Referenced by Chara._Move(), and GetRotation().
GetAngle2()
float Point.GetAngle2 (Point to) inline
Definition at line 694 of file Point.cs.
    {
        int num = to.x - this.x;
        return Mathf.Atan2((float)(to.z - this.z), (float)num) * 57.29578f;
    }
References x, and z.
Referenced by Map.ListPointsInArc().
GetHashCode()
override int Point.GetHashCode () inline
Definition at line 1049 of file Point.cs.
    {
        return this.x + this.z * Point.map.Size;
    }
References map, and MapBounds.Size.
GetInstalled< T >()
T Point.GetInstalled< T > () inline
Type Constraints
T : Trait
Definition at line 1279 of file Point.cs.
                                       : Trait
    {
        if (this.detail != null)
        {
            foreach (Thing thing in this.detail.things)
            {
                if (thing.IsInstalled && thing.trait is T)
                {
                    return thing.trait as T;
                }
            }
        }
        return default(T);
    }
References Card.IsInstalled, Card.things, and Card.trait.
GetNearestPoint()
Point Point.GetNearestPoint (bool allowBlock = false, bool allowChara = true, bool allowInstalled = true, bool ignoreCenter = false) inline
Definition at line 700 of file Point.cs.
    {
        Point.<>c__DisplayClass149_0 CS$<>8__locals1;
        CS$<>8__locals1.ignoreCenter = ignoreCenter;
        CS$<>8__locals1.<>4__this = this;
        CS$<>8__locals1.allowBlock = allowBlock;
        CS$<>8__locals1.allowChara = allowChara;
        CS$<>8__locals1.allowInstalled = allowInstalled;
        CS$<>8__locals1.p = new Point();
        int num = 1;
        int num2 = this.x;
        int num3 = this.z;
        if (this.<GetNearestPoint>g__IsValid|149_0(num2, num3, ref CS$<>8__locals1))
        {
            return CS$<>8__locals1.p;
        }
        if (this.<GetNearestPoint>g__IsValid|149_0(num2, num3 + 1, ref CS$<>8__locals1))
        {
            return CS$<>8__locals1.p;
        }
        for (int i = 0; i < 30; i++)
        {
            for (int j = 0; j < num; j++)
            {
                num2++;
                if (this.<GetNearestPoint>g__IsValid|149_0(num2, num3, ref CS$<>8__locals1))
                {
                    return CS$<>8__locals1.p;
                }
            }
            num++;
            for (int k = 0; k < num; k++)
            {
                num3++;
                if (this.<GetNearestPoint>g__IsValid|149_0(num2, num3, ref CS$<>8__locals1))
                {
                    return CS$<>8__locals1.p;
                }
            }
            for (int l = 0; l < num; l++)
            {
                num2--;
                if (this.<GetNearestPoint>g__IsValid|149_0(num2, num3, ref CS$<>8__locals1))
                {
                    return CS$<>8__locals1.p;
                }
            }
            num++;
            for (int m = 0; m < num; m++)
            {
                num3--;
                if (this.<GetNearestPoint>g__IsValid|149_0(num2, num3, ref CS$<>8__locals1))
                {
                    return CS$<>8__locals1.p;
                }
            }
        }
        CS$<>8__locals1.p.Set(this);
        return CS$<>8__locals1.p;
    }
References g__IsValid(), GetNearestPoint(), Point(), x, and z.
Referenced by TraitShrine._OnUse(), Zone.Activate(), Zone.AddGlobalCharasOnActivate(), Recipe.Build(), Zone.ClaimZone(), ZonePreEnterBout.Execute(), CoreDebug.g__AddParty(), FactionBranch.GetMailBoxPos(), GetNearestPoint(), MapBounds.GetRandomSpawnPos(), Zone.GetRandomVisitPos(), Chara.GetRevived(), Zone.GetSpawnPos(), ActEffect.GetTeleportPos(), TraitFoodEggFertilized.Incubate(), Chara.Kick(), Chara.MoveHome(), FactionBranch.OnActivateZone(), QuestIntroInspector.OnComplete(), QuestVernis.OnComplete(), QuestDialog.OnDropReward(), GrowSystemTree.OnHitFail(), TraitDiary.OnRead(), QuestEscort.OnStart(), ZoneEventDefenseGame.OnVisit(), ActSummonGuard.Perform(), ActEffect.Proc(), ActEffect.ProcAt(), CoreDebug.QuickStart(), TraitBaseSpellbook.ReadFailEffect(), Chara.RequestProtection(), Zone.Revive(), Chara.Revive(), AI_Idle.Run(), ZoneEventQuest.Spawn(), ZoneEventQuest.SpawnBoss(), CoreDebug.TestSpawn(), Chara.TryDropBossLoot(), Religion.TryGetGift(), and Zone.TrySpawnFollower().
GetPointTowards()
Point Point.GetPointTowards (Point dest) inline
Definition at line 864 of file Point.cs.
    {
        Point point = new Point(this);
        int num = dest.x - point.x;
        int num2 = dest.z - point.z;
        if (Mathf.Abs(num) > 1 || Mathf.Abs(num2) > 1)
        {
            int num3 = Mathf.Max(Mathf.Abs(num), Mathf.Abs(num2));
            point.x += num / num3;
            point.z += num2 / num3;
        }
        return point;
    }
References Point(), x, and z.
Referenced by Chara.TryMoveTowards().
GetRandomNeighbor()
Point Point.GetRandomNeighbor () inline
Definition at line 822 of file Point.cs.
    {
        int num = (EClass.rnd(2) == 0) ? 1 : -1;
        if (EClass.rnd(2) == 0)
        {
            return new Point(Mathf.Clamp(this.x + num, 0, Point.map.Size - 1), this.z);
        }
        return new Point(this.x, Mathf.Clamp(this.z + num, 0, Point.map.Size - 1));
    }
References map, Point(), EClass.rnd(), MapBounds.Size, and x.
Referenced by Chara._Move(), ActEffect.GetTeleportPos(), Chara.MoveRandom(), GrowSystem.OnExceedLastStage(), and DramaOutcome.PutOutFire().
GetRandomPoint()
Point Point.GetRandomPoint (int radius, bool requireLos = true, bool allowChara = true, bool allowBlocked = false, int tries = 100) inline
Definition at line 832 of file Point.cs.
    {
        Point point = new Point();
        for (int i = 0; i < tries; i++)
        {
            point.Set(this.x - radius + EClass.rnd(radius * 2 + 1), this.z - radius + EClass.rnd(radius * 2 + 1));
            if (point.IsValid && (allowBlocked || !point.IsBlocked) && (!requireLos || Los.IsVisible(this, point, null)) && (allowChara || !point.HasChara))
            {
                return point;
            }
        }
        return null;
    }
References HasChara, IsBlocked, IsValid, Los.IsVisible(), Point(), EClass.rnd(), Set(), and x.
Referenced by ZonePreEnterEncounter.Execute(), AI_Idle.g__FindMovePoint(), ActEffect.Proc(), ActEffect.ProcAt(), ActThrow.Throw(), ConMiasma.Tick(), AI_Idle.TryPerformIdleUse(), and Zone.TrySpawnFollower().
GetRandomPointInRadius()
Point Point.GetRandomPointInRadius (int minRadius, int maxRadius, bool requireLos = true, bool allowChara = true, bool allowBlocked = false, int tries = 2000) inline
Definition at line 846 of file Point.cs.
    {
        Point point = new Point();
        for (int i = 0; i < tries; i++)
        {
            point.Set(this.x - maxRadius + EClass.rnd(maxRadius * 2 + 1), this.z - maxRadius + EClass.rnd(maxRadius * 2 + 1));
            if (point.IsValid && (allowBlocked || !point.IsBlocked) && (allowChara || !point.HasChara))
            {
                int num = point.Distance(this);
                if (num >= minRadius && num <= maxRadius && (!requireLos || Los.IsVisible(this, point, null)))
                {
                    return point;
                }
            }
        }
        return null;
    }
References Distance(), HasChara, IsBlocked, IsValid, Los.IsVisible(), Point(), EClass.rnd(), Set(), and x.
Referenced by ZonePreEnterEncounter.Execute().
GetRotation()
Quaternion Point.GetRotation (Point to) inline
Definition at line 683 of file Point.cs.
    {
        return Quaternion.Euler(0f, 0f, this.GetAngle(to));
    }
References GetAngle().
Referenced by Effect._Play().
GetShared()
static Point Point.GetShared (int x, int z) inline static
Definition at line 11 of file Point.cs.
    {
        Point.shared.x = x;
        Point.shared.z = z;
        return Point.shared;
    }
References shared, x, and z.
Referenced by Zone_Dungeon.g__TryPlaceRail(), and AI_Goto.TryGoTo().
HasNonHomeProperty()
bool Point.HasNonHomeProperty (Thing exclude = null) inline
Definition at line 1332 of file Point.cs.
    {
        if (this.FirstThing == null)
        {
            return false;
        }
        foreach (Thing thing in this.detail.things)
        {
            if (thing != exclude && thing.isNPCProperty)
            {
                return true;
            }
        }
        return false;
    }
References Card.isNPCProperty, and Card.things.
HasRoomOrArea()
bool Point.HasRoomOrArea (BaseArea a) inline
Definition at line 512 of file Point.cs.
    {
        return this.area == a || this.cell.room == a;
    }
Referenced by Map.FindThing(), and Map.g__Find().
IsBlockByHeight()
bool Point.IsBlockByHeight (Point p) inline
Definition at line 1064 of file Point.cs.
    {
        return Mathf.Abs((int)(p.cell.minHeight - this.cell.topHeight)) > 8 && Mathf.Abs((int)(p.cell.topHeight - this.cell.minHeight)) > 8;
    }
References cell, Cell.minHeight, and Cell.topHeight.
IsInSpot< T >()
bool Point.IsInSpot< T > () inline
Type Constraints
T : TraitSpot
Definition at line 517 of file Point.cs.
                                      : TraitSpot
    {
        foreach (Thing thing in EClass._map.things)
        {
            if (thing.trait is T)
            {
                foreach (Point obj in thing.trait.ListPoints(null, true))
                {
                    if (this.Equals(obj))
                    {
                        return true;
                    }
                }
            }
        }
        return false;
    }
References EClass._map, Equals(), Trait.ListPoints(), Map.things, and Card.trait.
IsPublicSpace()
bool Point.IsPublicSpace () inline
Definition at line 535 of file Point.cs.
    {
        if (this.area != null)
        {
            return this.area.type.IsPublicArea;
        }
        return this.cell.room == null || this.cell.room.type.IsPublicArea;
    }
References area, cell, AreaType.IsPublicArea, Cell.room, and BaseArea.type.
Referenced by Map.FindThing().
ListCards()
List< Card > Point.ListCards (bool includeMasked = false) inline
Definition at line 1112 of file Point.cs.
    {
        Point.listCard.Clear();
        bool flag = EClass.scene.actionMode != null && EClass.scene.actionMode.IsRoofEditMode(null);
        if (this.detail != null)
        {
            foreach (Thing thing in this.detail.things)
            {
                if (!thing.isHidden && (includeMasked || !thing.isMasked) && thing.isRoofItem == flag)
                {
                    Point.listCard.Add(thing);
                }
            }
            if (!flag)
            {
                foreach (Chara item in this.detail.charas)
                {
                    Point.listCard.Add(item);
                }
            }
        }
        return Point.listCard;
    }
References Scene.actionMode, CellDetail.charas, detail, Card.isHidden, Card.isMasked, ActionMode.IsRoofEditMode(), Card.isRoofItem, listCard, EClass.scene, and CellDetail.things.
Referenced by Chara._Move(), ActPlan._Update(), Map._ValidateInstalled(), Recipe.Build(), Trait.CookProgress(), ActEffect.DamageEle(), FindAttackTarget(), MapGenDungen.g__ClearPos(), AI_Clean.GetCleanPoint(), Trait.Offer(), Trait.OfferProcess(), TraitFertilizer.OnSimulateHour(), ActPick.Perform(), AM_Deconstruct.Perform(), Map.RefreshFOV(), AI_Clean.Run(), RecipeUpdater.RunDisassemble(), AM_Picker.Test(), Zone.TryAddThingInSpot< T >(), TraitCatalyst.TrySetHeldAct(), TraitLeash.TrySetHeldAct(), TraitSalesTag.TrySetHeldAct(), TraitStethoscope.TrySetHeldAct(), TraitToolTorch.TrySetHeldAct(), TraitWhipLove.TrySetHeldAct(), Map.TryShatter(), and CoreDebug.UpdateInput().
ListCharas()
List< Chara > Point.ListCharas () inline
Definition at line 1217 of file Point.cs.
    {
        Point.listChara.Clear();
        if (this.detail != null)
        {
            foreach (Chara item in this.detail.charas)
            {
                Point.listChara.Add(item);
            }
        }
        return Point.listChara;
    }
References CellDetail.charas, detail, and listChara.
Referenced by AM_Adv._OnUpdateInput(), Recipe.Build(), AM_Adv.OnRenderTile(), ActRide.Perform(), and ActEffect.Proc().
ListCharasInNeighbor()
List< Chara > Point.ListCharasInNeighbor (Func< Chara, bool > func) inline
Definition at line 1246 of file Point.cs.
    {
        Point.listChara.Clear();
        this.ForeachNeighbor(delegate(Point p)
        {
            if (p.detail == null)
            {
                return;
            }
            foreach (Chara chara in p.detail.charas)
            {
                if (func(chara))
                {
                    Point.listChara.Add(chara);
                }
            }
        }, true);
        return Point.listChara;
    }
References CellDetail.charas, detail, ForeachNeighbor(), and listChara.
Referenced by AI_Idle.DoSomethingToNearChara().
ListCharasInRadius()
List< Chara > Point.ListCharasInRadius (Chara cc, int dist, Func< Chara, bool > func) inline
Definition at line 1266 of file Point.cs.
    {
        Point.listChara.Clear();
        foreach (Chara chara in EClass._map.charas)
        {
            if (func(chara) && chara.Dist(cc) < dist && Los.IsVisible(chara, cc))
            {
                Point.listChara.Add(chara);
            }
        }
        return Point.listChara;
    }
References EClass._map, Map.charas, Card.Dist(), Los.IsVisible(), and listChara.
Referenced by AI_Idle.DoSomethingToCharaInRadius(), and Card.TryUnrestrain().
ListInspectorTargets()
List< IInspect > Point.ListInspectorTargets () inline
Definition at line 1400 of file Point.cs.
    {
        List<IInspect> list = new List<IInspect>();
        CellDetail detail = this.detail;
        if (detail != null)
        {
            foreach (Chara chara in detail.charas)
            {
                if (chara.isSynced)
                {
                    list.Add(chara);
                }
            }
            foreach (Thing item in detail.things)
            {
                list.Add(item);
            }
            if (detail.designation != null && !(detail.designation is TaskCut) && !(detail.designation is TaskMine))
            {
                list.Add(detail.designation);
            }
        }
        if (ObjInfo._CanInspect(this))
        {
            list.Add(ObjInfo.GetTempList(this));
        }
        if (BlockInfo._CanInspect(this))
        {
            list.Add(BlockInfo.GetTempList(this));
        }
        return list;
    }
References BlockInfo._CanInspect(), ObjInfo._CanInspect(), CellDetail.charas, CellDetail.designation, BlockInfo.GetTempList(), ObjInfo.GetTempList(), Chara.isSynced, and CellDetail.things.
Referenced by UIInspector.InspectUnderMouse(), and LayerInteraction.TryShow().
ListThings< T >()
List< Card > Point.ListThings< T > (bool onlyInstalled = true) inline
Type Constraints
T : Trait
Definition at line 1201 of file Point.cs.
                                                                       : Trait
    {
        Point.listCard.Clear();
        if (this.detail != null)
        {
            foreach (Thing thing in this.detail.things)
            {
                if (!thing.isHidden && !thing.isRoofItem && !thing.isMasked && (!onlyInstalled || thing.IsInstalled) && thing.trait is T)
                {
                    Point.listCard.Add(thing);
                }
            }
        }
        return Point.listCard;
    }
References detail, Card.isHidden, Card.IsInstalled, Card.isMasked, Card.isRoofItem, listCard, CellDetail.things, and Card.trait.
ListVisibleCards()
List< Card > Point.ListVisibleCards () inline
Definition at line 1136 of file Point.cs.
    {
        Point.listCard.Clear();
        if (this.detail != null)
        {
            foreach (Thing thing in this.detail.things)
            {
                if (!thing.isHidden && !thing.isMasked && !thing.isRoofItem)
                {
                    Point.listCard.Add(thing);
                }
            }
            foreach (Chara chara in this.detail.charas)
            {
                if (EClass.pc.CanSee(chara))
                {
                    Point.listCard.Add(chara);
                }
            }
        }
        return Point.listCard;
    }
References Chara.CanSee(), CellDetail.charas, detail, Card.isHidden, Card.isMasked, Card.isRoofItem, listCard, EClass.pc, and CellDetail.things.
Referenced by HotItemNoItem._TrySetAct(), and HotItemAct.TrySetAct().
ListVisibleCharas()
List< Chara > Point.ListVisibleCharas () inline
Definition at line 1230 of file Point.cs.
    {
        Point.listChara.Clear();
        if (this.detail != null)
        {
            foreach (Chara chara in this.detail.charas)
            {
                if (EClass.pc.CanSee(chara))
                {
                    Point.listChara.Add(chara);
                }
            }
        }
        return Point.listChara;
    }
References Chara.CanSee(), CellDetail.charas, detail, listChara, and EClass.pc.
Referenced by HotItemHeld.TrySetToolAct().
ListWitnesses()
List< Chara > Point.ListWitnesses (Chara criminal, int radius = 4, WitnessType type = WitnessType::crime, Chara target = null) inline
Definition at line 893 of file Point.cs.
    {
        List<Chara> list = new List<Chara>();
        foreach (Point point in Point.map.ListPointsInCircle(this, (float)radius, false, true))
        {
            CellDetail detail = point.detail;
            List<Chara> list2 = (detail != null) ? detail.charas : null;
            if (list2 != null && list2.Count != 0)
            {
                foreach (Chara chara in list2)
                {
                    if (chara != criminal && !chara.IsPC && (chara == target || chara.CanWitness) && (!chara.HasCondition<ConDim>() || EClass.rnd(2) != 0) && chara.conSuspend == null && !chara.isParalyzed && !chara.IsDisabled)
                    {
                        switch (type)
{
                        case WitnessType.crime:
                            if (criminal == null || chara.isBlind || chara.isConfused || (criminal.IsPCParty && (chara.IsPCFaction || chara.IsPCFactionMinion)))
{
                                continue;
                            }
                            if (target == null)
{
                                if (chara.OriginalHostility < Hostility.Neutral)
{
                                    continue;
                                }
                            }
                            else if (!target.IsFriendOrAbove(chara))
{
                                continue;
                            }
                            break;
                        case WitnessType.music:
                            if (chara.hostility <= Hostility.Enemy)
{
                                continue;
                            }
                            break;
                        case WitnessType.ally:
                            if (!criminal.IsPCFaction)
{
                                continue;
                            }
                            if (chara.hostility <= Hostility.Neutral)
{
                                continue;
                            }
                            break;
                        }
                        list.Add(chara);
                    }
                }
            }
        }
        return list;
    }
References Chara.CanWitness, CellDetail.charas, Chara.conSuspend, detail, Chara.HasCondition(), Chara.hostility, Chara.isBlind, Chara.isConfused, Chara.IsDisabled, Chara.isParalyzed, Chara.IsPC, Chara.IsPCFaction, Chara.IsPCFactionMinion, Map.ListPointsInCircle(), map, Chara.OriginalHostility, and EClass.rnd().
Referenced by AI_PlayMusic.Run(), AI_Steal.Run(), TalkWitnesses(), and TryWitnessCrime().
ModFire()
void Point.ModFire (int value) inline
Definition at line 1008 of file Point.cs.
    {
        Point.map.ModFire(this.x, this.z, value);
    }
References map, Map.ModFire(), x, and z.
Referenced by GameUpdater.SurfaceUpdater.FixedUpdate(), ActThrow.Throw(), and LogicalFire.Transfer().
PlayEffect()
Effect Point.PlayEffect (string id) inline
Definition at line 1294 of file Point.cs.
    {
        return Effect.Get(id).Play(this, 0f, null, null);
    }
References Effect.Get(), and Effect.Play().
Referenced by ActPlan._Update(), Card.Die(), ActRush.Perform(), TraitBaseSpellbook.ReadFailEffect(), AI_Clean.Run(), and TraitBroom.TrySetHeldAct().
PlaySound()
unsafe SoundSource Point.PlaySound (string id, bool synced = true, float v = 1f, bool spatial = true) inline
Definition at line 1299 of file Point.cs.
    {
        Vector3 vector = default(Vector3);
        if (spatial)
        {
            if (!this.IsValid)
            {
                return null;
            }
            vector = (EClass._zone.IsRegion ? (*this.PositionTopdown()) : (*this.Position()));
            vector.z = 0f;
            if (Vector3.Distance(vector, EClass.scene.transAudio.position) > EClass.core.gameSetting.audio.maxRange)
            {
                return null;
            }
            if (!synced)
            {
                v -= 0.4f;
            }
        }
        return EClass.Sound.Play(id, vector, (!spatial) ? 1f : (v * ((EClass.screen.Zoom >= 1f) ? 1f : EClass.screen.Zoom)));
    }
References EClass.core, EClass.scene, EClass.screen, EClass.Sound, Scene.transAudio, and BaseGameScreen.Zoom.
Referenced by ActPlan._Update(), Map.DestroyObj(), Card.Die(), Map.MineBlock(), Map.MineFloor(), Map.MineObjSound(), TaskHarvest.OnCreateProgress(), TaskPlow.OnCreateProgress(), TaskCut.OnProgress(), TaskMoveInstalled.OnProgressComplete(), ActEffect.ProcAt(), and AI_Fish.ProgressFish.Ripple().
Plow()
void Point.Plow () inline
Definition at line 1013 of file Point.cs.
    {
        if (this.IsFarmField)
        {
            if (this.cell.Right.HasWallOrFence)
            {
                this.Set(this.cell.Right.GetPoint());
            }
            else if (this.cell.Front.HasWallOrFence)
            {
                this.Set(this.cell.Front.GetPoint());
            }
        }
        this.SetFloor(4, 4);
    }
References cell, Cell.Front, Cell.GetPoint(), Cell.HasWallOrFence, IsFarmField, Cell.Right, Set(), and SetFloor().
Position() [1/2]
ref Vector3 Point.Position () inline
Definition at line 641 of file Point.cs.
    {
        byte b = (this.cell.bridgeHeight == 0) ? this.cell.height : this.cell.bridgeHeight;
        this.vCache.x = (float)(this.x + this.z) * Point._screen.tileAlign.x;
        this.vCache.y = (float)(this.z - this.x) * Point._screen.tileAlign.y + (float)b * Point._screen.tileMap._heightMod.y;
        this.vCache.z = 1000f + this.vCache.x * Point._screen.tileWeight.x + this.vCache.y * Point._screen.tileWeight.z + (float)b * Point._screen.tileMap._heightMod.z;
        return ref this.vCache;
    }
References BaseTileMap._heightMod, _screen, cell, Cell.height, BaseGameScreen.tileAlign, BaseGameScreen.tileMap, x, and z.
Referenced by GetAngle(), Position(), PositionAuto(), and PositionCenter().
Position() [2/2]
ref Vector3 Point.Position (int height) inline
Definition at line 629 of file Point.cs.
    {
        if (height == -1)
        {
            return this.Position();
        }
        this.vCache.x = (float)(this.x + this.z) * Point._screen.tileAlign.x;
        this.vCache.y = (float)(this.z - this.x) * Point._screen.tileAlign.y + (float)height * Point._screen.tileMap._heightMod.y;
        this.vCache.z = 1000f + this.vCache.x * Point._screen.tileWeight.x + this.vCache.y * Point._screen.tileWeight.z + (float)height * Point._screen.tileMap._heightMod.z;
        return ref this.vCache;
    }
References BaseTileMap._heightMod, _screen, Position(), BaseGameScreen.tileAlign, BaseGameScreen.tileMap, BaseGameScreen.tileWeight, vCache, x, and z.
Referenced by MeshPass.Add(), BaseGameScreen.Draw(), BaseTileMap.Draw(), UIInspector.DrawHighlight(), ScreenGuide.DrawWall(), GetAngle(), TileTypeWallHang.GetMountHeight(), Chara.HasHigherGround(), Recipe.OnRenderMarker(), ActionMode.OnRenderTile(), AM_Adv.OnRenderTile(), AM_Build.OnRenderTile(), HotItemHeld.OnRenderTile(), Trait.OnRenderTile(), TraitRoadSign.OnRenderTile(), ActionMode.OnRenderTileFloor(), Effect.Play(), BaseGameScreen.RefreshPosition(), ActionMode.RefreshTexts(), Card.RenderMarker(), Card.SetFreePos(), TCOrbitTask.SetOwner(), UISong.SetSong(), and GameUpdater.Update().
PositionAuto()
ref Vector3 Point.PositionAuto () inline
Definition at line 620 of file Point.cs.
    {
        if (EClass._zone.IsRegion)
        {
            return this.PositionTopdown();
        }
        return this.Position();
    }
References EClass._zone, Spatial.IsRegion, Position(), and PositionTopdown().
Referenced by AM_Adv.OnAfterUpdate(), and CardRenderer.PlayAnime().
PositionCenter()
ref Vector3 Point.PositionCenter () inline
Definition at line 668 of file Point.cs.
    {
        if (EClass._zone.IsRegion)
        {
            this.PositionTopdown();
        }
        else
        {
            this.Position();
        }
        this.vCache.x = this.vCache.x + EClass.screen.tileWorldSize.x * 0.5f;
        this.vCache.y = this.vCache.y + EClass.screen.tileWorldSize.y * 0.75f;
        return ref this.vCache;
    }
References EClass._zone, Spatial.IsRegion, Position(), PositionTopdown(), and vCache.
Referenced by BaseGameScreen.Focus(), Card.MoveImmediate(), AM_Adv.OnActivate(), AM_MoveInstalled.OnRenderTile(), Scene.OnUpdate(), AM_Cinema.OnUpdateInput(), ActorEx.Refresh(), AM_Adv.RefreshArrow(), and GameUpdater.Update100ms().
PositionTopdown()
ref Vector3 Point.PositionTopdown () inline
Definition at line 650 of file Point.cs.
    {
        byte b = (this.cell.bridgeHeight == 0) ? this.cell.height : this.cell.bridgeHeight;
        this.vCache.x = (float)this.x * Point._screen.tileAlign.x;
        this.vCache.y = (float)this.z * Point._screen.tileAlign.y + (float)b * Point._screen.tileMap._heightMod.y;
        this.vCache.z = 1000f + this.vCache.x * Point._screen.tileWeight.x + this.vCache.y * Point._screen.tileWeight.z + (float)b * Point._screen.tileMap._heightMod.z;
        return ref this.vCache;
    }
References BaseTileMap._heightMod, _screen, cell, Cell.height, BaseGameScreen.tileAlign, BaseGameScreen.tileMap, and z.
Referenced by TileSelectorElona.OnRenderTile(), PositionAuto(), PositionCenter(), GameScreenElona.RefreshPosition(), ActionMode.RefreshTexts(), and GameUpdater.Update().
PositionTopdownTreasure()
ref Vector3 Point.PositionTopdownTreasure () inline
Definition at line 659 of file Point.cs.
    {
        GameScreenElona screenElona = EClass.scene.screenElona;
        this.vCache.x = (float)(this.x - EClass.scene.elomap.minX) * screenElona.tileAlign.x;
        this.vCache.y = (float)(this.z - EClass.scene.elomap.minY) * screenElona.tileAlign.y;
        this.vCache.z = 1400f;
        return ref this.vCache;
    }
References Scene.elomap, EloMap.minX, EloMap.minY, EClass.scene, Scene.screenElona, BaseGameScreen.tileAlign, vCache, x, and z.
Referenced by LayerTreasureMap.SetMap().
RefreshNeighborTiles()
void Point.RefreshNeighborTiles () inline
Definition at line 1322 of file Point.cs.
    {
        Point.map.RefreshNeighborTiles(this.x, this.z);
    }
References map, and Map.RefreshNeighborTiles().
Referenced by Cell.AddCard(), TaskDrawWater.g__ChangeFloor(), TaskPourWater.g__ChangeFloor(), AM_FlagCell.OnProcessTiles(), AM_Terrain.OnProcessTiles(), Cell.RemoveCard(), Cell.RotateAll(), Card.SetPlaceState(), and Trait.Toggle().
RefreshTile()
void Point.RefreshTile () inline
Definition at line 1327 of file Point.cs.
    {
        Point.map.RefreshSingleTile(this.x, this.z);
    }
References map, and Map.RefreshSingleTile().
Referenced by TaskBuild.OnProgressComplete().
Set() [1/4]
Point Point.Set (int _x, int _z) inline
Definition at line 577 of file Point.cs.
    {
        this.x = _x;
        this.z = _z;
        return this;
    }
Referenced by Map._AddCard(), Chara._Move(), Card._OnDeserialized(), AM_Sim._OnUpdateInput(), ActPlan._Update(), Map._ValidateInstalled(), Zone.Activate(), Map.AddCardOnActivate(), Zone.AddGlobalCharasOnActivate(), AI_Goto.AI_Goto(), RecipeUpdater.Build(), GoalManualMove.CanMove(), ActRush.CanPerform(), ActThrow.CanPerform(), TaskPoint.CanPerform(), Act.CanPerform(), PointTarget.CheckLastTarget(), Copy< T >(), Crawler.Crawl(), EffectMeteor.Create(), BaseTileMap.Draw(), TaskBuild.DrawMarker(), BaseTileMap.DrawTile(), TileMapElona.DrawTile(), Player.EnterLocalZone(), GameUpdater.SurfaceUpdater.FixedUpdate(), GameUpdater.FastSurfaceUpdater.FixedUpdate(), Card.ForeachFOV(), ForeachMultiSize(), ForeachNeighbor(), Map.ForeachNeighbor(), Map.ForeachPoint(), MapBounds.ForeachPoint(), Map.ForeachSphere(), MapGen.g___MakeNeighbor(), MapGen.g___MakeRoad(), g__IsValid(), Zone_Dungeon.g__TryPlaceRail(), Zone_SnowGrave.GenerateGrave(), AI_Clean.GetCleanPoint(), AI_Fish.GetFishingPoint(), TaskBuild.GetHitResult(), TileTypeWallHang.GetMountHeight(), AI_Trolley.GetPoint(), BaseGameScreen.GetRandomPoint(), GetRandomPoint(), GetRandomPointInRadius(), MapBounds.GetRandomSpace(), Cell.GetSharedPoint(), MapBounds.GetSpawnPos(), ActEffect.GetTeleportPos(), BlockInfo.GetTemp(), ObjInfo.GetTemp(), BlockInfo.GetTempList(), ObjInfo.GetTempList(), Los.IsBlocked(), Los.IsVisible(), Los.ListVisible(), MapGenDungen.OnGenerateTerrain(), WidgetMinimap.OnPointerDown(), AM_Designation< T >.OnProcessTiles(), AM_MoveInstalled.OnProcessTiles(), HotItemHeld.OnRenderTile(), BaseTileSelector.OnUpdate(), WidgetMinimap.OnUpdate(), AM_Cinema.OnUpdateInput(), Act.Perform(), ActRanged.Perform(), ActRush.Perform(), ActThrow.Perform(), ActPlan.Item.Perform(), Plow(), Point(), GenRoom.Populate(), MapGen.Populate(), AM_Adv.PressedActionMove(), BaseTileSelector.ProcessTiles(), Religion.Reforge(), BaseTileSelector.RefreshMouseInfo(), PathProgress.RequestPath(), PathProgress.RequestPathImmediate(), AI_Fish.Run(), AI_Goto.Run(), GoalManualMove.Run(), TaskPoint.Run(), TaskWater.Run(), CharaRenderer.SetFirst(), Map.SetFoormark(), Act.SetReference(), LayerInteraction.Show(), ActThrow.Throw(), AI_Goto.TryGoTo(), GoalManualMove.TryMove(), Chara.TryMoveFrom(), Chara.TryMoveTowards(), GameUpdater.Update(), LogicalFire.Update(), PointTarget.Update(), CharaRenderer.UpdatePosition(), and Chara.UpdateSight().
Set() [2/4]
Point Point.Set (int index) inline
Definition at line 584 of file Point.cs.
    {
        this.x = index % Point.map.Size;
        this.z = index % Point.map.SizeXZ / Point.map.Size;
        return this;
    }
References index, map, and MapBounds.Size.
Set() [3/4]
Point Point.Set (Point point) inline
Definition at line 591 of file Point.cs.
    {
        this.x = point.x;
        this.z = point.z;
        return this;
    }
References x, and z.
Set() [4/4]
void Point.Set (Vector3 v) inline
Definition at line 610 of file Point.cs.
    {
        v.x -= 0.64f;
        v.y -= 0.64f;
        int num = Mathf.RoundToInt(v.x / Point._screen.tileAlign.x);
        int num2 = Mathf.RoundToInt(v.y / Point._screen.tileAlign.y);
        this.x = (num2 - num) / 2 * -1;
        this.z = num - this.x;
    }
References _screen, BaseGameScreen.tileAlign, and x.
SetBlock()
void Point.SetBlock (int idMat = 0, int idBlock = 0) inline
Definition at line 993 of file Point.cs.
    {
        Point.map.SetBlock(this.x, this.z, idMat, idBlock);
    }
References map, Map.SetBlock(), x, and z.
Referenced by ZonePreEnterDigStairs.Execute(), Zone_Dungeon.g__TryPlaceRail(), Map.MineBlock(), Chara.TryDropBossLoot(), and MapGen.TryMakeRiver().
SetFloor()
void Point.SetFloor (int idMat = 0, int idFloor = 0) inline
Definition at line 998 of file Point.cs.
    {
        Point.map.SetFloor(this.x, this.z, idMat, idFloor);
    }
References map, Map.SetFloor(), x, and z.
Referenced by MapGen.g___MakeRoad(), Map.MineFloor(), TraitBoat.OnChangePlaceState(), TaskPlow.OnCreateProgress(), MapGenDungen.OnGenerateTerrain(), TraitBoat.OnRemovedFromZone(), Plow(), and Zone.SpawnAltar().
SetObj()
void Point.SetObj (int id = 0, int value = 1, int dir = 0) inline
Definition at line 1003 of file Point.cs.
    {
        Point.map.SetObj(this.x, this.z, id, value, dir);
    }
References map, Map.SetObj(), x, and z.
Referenced by ZonePreEnterDigStairs.Execute(), Zone_Dungeon.g__TryPlaceRail(), GrowSystem.Grow(), TaskHarvest.OnCreateProgress(), GrowSystem.OnExceedLastStage(), Zone_RandomDungeonFactory.OnGenerateMap(), Zone_VernisMine.OnGenerateMap(), ZoneEventHarvest.OnVisit(), Zone.SpawnAltar(), BiomeProfile.ClusterObj.TryCreate(), Chara.TryDropBossLoot(), Zone.TryGenerateShrine(), and TraitSeed.TrySprout().
TalkWitnesses()
void Point.TalkWitnesses (Chara criminal, string idTalk, int radius = 4, WitnessType type = WitnessType::everyone, Func< Chara, bool > talkIf = null, int chance = 3) inline
Definition at line 878 of file Point.cs.
    {
        if (talkIf == null)
        {
            talkIf = ((Chara c) => EClass.rnd(chance) == 0);
        }
        foreach (Chara chara in this.ListWitnesses(criminal, radius, type, null))
        {
            if (talkIf(chara) && !chara.renderer.IsTalking())
            {
                chara.Talk(idTalk, null, null, false);
            }
        }
    }
References CardRenderer.IsTalking(), ListWitnesses(), Card.renderer, EClass.rnd(), and Card.Talk().
Referenced by ElementContainerCard.OnLevelUp(), ElementContainerZone.OnLevelUp(), and AI_Bladder.Run().
ToRegionPos()
Point Point.ToRegionPos () inline
Definition at line 1464 of file Point.cs.
    {
        Point point = new Point(this.x, this.z);
        point.x += EClass.scene.elomap.minX;
        point.z += EClass.scene.elomap.minY;
        return point;
    }
References Scene.elomap, EloMap.minX, EloMap.minY, and EClass.scene.
Referenced by TraitDeedRelocate.OnRead().
ToString()
override string Point.ToString () inline
Definition at line 598 of file Point.cs.
    {
        return string.Concat(new string[]
        {
            "(",
            this.x.ToString(),
            " / ",
            this.z.ToString(),
            ")"
        });
    }
References x, and z.
Referenced by Algorithms.PathFinder._FindPath(), Zone.Activate(), Equals(), ZonePreEnterBout.Execute(), ForeachNearestPoint(), Map.GetRandomPoint(), TraitHouseBoard.OnChangePlaceState(), TaskPoint.Run(), Chara.SyncRide(), Card.ToString(), Chara.ToString(), Zone.ToString(), HotItemAct.TrySetAct(), and WidgetDebug.UpdateText().
TryWitnessCrime()
bool Point.TryWitnessCrime (Chara criminal, Chara target = null, int radius = 4, Func< Chara, bool > funcWitness = null) inline
Definition at line 950 of file Point.cs.
    {
        List<Chara> list = this.ListWitnesses(criminal, radius, WitnessType.crime, target);
        bool result = false;
        if (funcWitness == null)
        {
            funcWitness = ((Chara c) => EClass.rnd(10) == 0);
        }
        foreach (Chara chara in list)
        {
            if (funcWitness(chara))
            {
                this.CallGuard(criminal, chara);
                result = true;
                if (target != null)
                {
                    target.DoHostileAction(criminal, false);
                }
                if (chara != target)
                {
                    chara.DoHostileAction(criminal, false);
                    break;
                }
                break;
            }
        }
        return result;
    }
References CallGuard(), Chara.DoHostileAction(), ListWitnesses(), and EClass.rnd().
Referenced by Player.ModKarma(), TaskDig.OnCreateProgress(), TaskHarvest.OnCreateProgress(), TaskMine.OnCreateProgress(), InvOwner.Transaction.Process(), and AI_Steal.Run().
Within()
bool Point.Within (int _x, int _z, int _w, int _h) inline
Definition at line 204 of file Point.cs.
    {
        return this.x >= _x && this.z >= _z && this.x < _x + _w && this.z < _z + _h;
    }
Referenced by PartialMap.Save().
Member Data Documentation
_screen
BaseGameScreen Point._screen static
Definition at line 1519 of file Point.cs.
Referenced by Position(), PositionTopdown(), and Set().
fixedPos
Vector3 Point.fixedPos static
Definition at line 1494 of file Point.cs.
Invalid
Point Point.Invalid static
Initial value:
= new Point
    {
        IsValid = false
    }
Definition at line 1504 of file Point.cs.
Referenced by PathManager._GetFirstStep(), AM_Sim._OnUpdateInput(), GoalManualMove.CanMove(), POIMap.GetCenterOfEmptyCell(), PathManager.GetFirstStep(), AI_Fish.GetFishingPoint(), TaskBuild.GetHitResult(), Map.GetNearbyResourcePoint(), MapBounds.GetSurface(), and GoalManualMove.Run().
listCard
List<Card> Point.listCard = new List<Card>() static private
Definition at line 1521 of file Point.cs.
Referenced by ListCards(), ListThings< T >(), and ListVisibleCards().
listChara
List<Chara> Point.listChara = new List<Chara>() static private
Definition at line 1523 of file Point.cs.
Referenced by ListCharas(), ListCharasInNeighbor(), ListCharasInRadius(), and ListVisibleCharas().
map
Map Point.map static
Definition at line 1502 of file Point.cs.
Referenced by Clamp(), g__IsValid(), GetHashCode(), GetRandomNeighbor(), ListWitnesses(), ModFire(), RefreshNeighborTiles(), RefreshTile(), Set(), SetBlock(), SetFloor(), and SetObj().
shared
Point Point.shared = new Point() static
Definition at line 1496 of file Point.cs.
Referenced by Map._ValidateInstalled(), TaskBuild.DrawMarker(), BaseTileMap.DrawTile(), TileMapElona.DrawTile(), GetShared(), Cell.GetSharedPoint(), HotItemHeld.OnRenderTile(), AM_Adv.PressedActionMove(), AI_Fish.Run(), GoalManualMove.TryMove(), GameUpdater.Update(), and LogicalFire.Update().
shared2
Point Point.shared2 = new Point() static
Definition at line 1498 of file Point.cs.
Referenced by TileTypeWallHang.GetMountHeight().
shared3
Point Point.shared3 = new Point() static
Definition at line 1500 of file Point.cs.
Referenced by ForeachMultiSize().
Surrounds
readonly XY [] Point.Surrounds static
Initial value:
= new XY[]
    {
        new XY(0, -1),
        new XY(1, 0),
        new XY(0, 1),
        new XY(-1, 0)
    }
Definition at line 1486 of file Point.cs.
Referenced by LogicalFire.Update().
vCache
Vector3 Point.vCache private
Definition at line 1517 of file Point.cs.
Referenced by Position(), PositionCenter(), and PositionTopdownTreasure().
x
int Point.x
Definition at line 1512 of file Point.cs.
Referenced by Algorithms.PathFinder._FindPath(), PathManager._GetFirstStep(), Chara._Move(), Card._OnSerializing(), Zone.Activate(), SerializedCards.Add(), SourceMaterial.Row.AddBlood(), Zone.AddCard(), Map.AddCardOnActivate(), Lot.AddConnectedRooms(), Zone.AddThing(), PartialMap.Apply(), AM_Adv.AxisMove(), Recipe.Build(), Region.CanCreateZone(), Chara.CanInteractTo(), Chara.CanMoveTo(), Clamp(), MapBounds.Contains(), Copy(), RecipeCard.Craft(), EffectMeteor.Create(), SpatialGen.CreateInstance(), Region.CreateRandomSite(), Region.CreateZone(), TraitNewZone.CreateZone(), ActEffect.DamageEle(), Spatial.Dist(), Distance(), BaseTileMap.Draw(), TileMapElona.Draw(), TaskBuild.DrawMarker(), BaseTileMap.DrawTile(), TileMapElona.DrawTile(), WidgetMinimap.EmitParticle(), Player.EnterLocalZone(), ZonePreEnterBout.Execute(), ZonePreEnterDigStairs.Execute(), Chara.FindNewEnemy(), Algorithms.PathFinder.FindPath(), GameUpdater.SurfaceUpdater.FixedUpdate(), GameUpdater.FastSurfaceUpdater.FixedUpdate(), GameUpdater.LogicUpdater.FixedUpdate(), TraitBoat.ForeachDeck(), ForeachNearestPoint(), Map.ForeachNeighbor(), MapGen.g___MakeNeighbor(), MapGen.g___MakeRoad(), TaskDrawWater.g__ChangeFloor(), TaskPourWater.g__ChangeFloor(), Zone_Dungeon.g__TryPlaceRail(), Zone_SnowGrave.GenerateGrave(), GetAngle2(), EloMap.GetCell(), TraitScrollMapTreasure.GetDest(), TraitNewZone.GetExitPos(), AI_Fish.GetFishingPoint(), TaskBuild.GetHitResult(), TileTypeWallHang.GetMountHeight(), GetNearestPoint(), AI_Trolley.GetPoint(), GetPointTowards(), GetRandomNeighbor(), Region.GetRandomPoint(), GetRandomPoint(), GetRandomPointInRadius(), MapBounds.GetRandomSpace(), GetShared(), MapBounds.GetSpawnPos(), EloMap.GetZone(), AM_MoveInstalled.HitTest(), AI_Goto.IsDestinationReached(), PathProgress.IsDestinationReached(), BaseTileSelector.IsInRange(), Los.IsVisible(), Map.ListPointsInArc(), Map.ListPointsInCircle(), Los.ListVisible(), Chara.LookAt(), MapGen.MakeRiver(), Map.MineBlock(), Map.MineFloor(), Map.MineRamp(), ModFire(), Map.MoveCard(), Chara.MoveHome(), TraitNewZone.MoveZone(), TraitMoongate.MoveZone(), POIMap.OccyupyPOI(), WidgetArtTool.OnActivate(), Region.OnAdvanceHour(), AM_Copy.OnAfterProcessTiles(), Zone_Nymelle.OnBeforeSimulate(), Player.OnExitBorder(), ZoneEventSiege.OnFirstTick(), Act.OnMarkMapHighlights(), AIWork_Clean.OnPerformWork(), GenRoom.OnPopulate(), AM_Populate.OnProcessTiles(), AM_Terrain.OnProcessTiles(), AI_Water.OnProgressComplete(), TaskBuild.OnProgressComplete(), TaskCut.OnProgressComplete(), TaskDig.OnProgressComplete(), TaskMine.OnProgressComplete(), TaskMoveInstalled.OnProgressComplete(), TraitDeedRelocate.OnRead(), Recipe.OnRenderMarker(), AM_BaseTerrain.OnRenderTile(), HotItemHeld.OnRenderTile(), PointList.OnSerializing(), TraitFertilizer.OnSimulateHour(), TraitDrink.OnThrowGround(), WidgetMinimap.OnUpdate(), TraitStairsLocked.OnUse(), Point(), Position(), PositionTopdownTreasure(), AM_Adv.PressedActionMove(), ActEffect.ProcAt(), BaseTileSelector.ProcessTiles(), Room.Refresh(), AM_Region.RefreshArrow(), BaseTileSelector.RefreshMouseInfo(), GameScreenElona.RefreshWeather(), Weather.RefreshWeather(), RegionPoint.RegionPoint(), Card.RenderMarker(), Map.Resize(), SerializedCards.Restore(), Map.Reveal(), AI_Bladder.Run(), AI_Clean.Run(), AI_Fish.Run(), GoalCombat.Run(), TaskWater.Run(), RecipeUpdater.RunRecipe(), ActWait.Search(), LogicalPoint.Set(), Set(), SetBlock(), SetFloor(), SetObj(), Card.SetPlaceState(), RegionPoint.SetRegionPoint(), WidgetHotbar.SetShortcutMenu(), LayerCraftFloat.ShowContextMenu(), Zone.SpawnAltar(), TraitDoor.ToggleDoor(), TraitDoorSwing.ToggleDoor(), ToString(), Zone.TryGenerateShrine(), AI_Goto.TryGoTo(), MapGen.TryMakeRiver(), Chara.TryMoveFrom(), Chara.TryPush(), TraitNewZone.TrySetAct(), TraitBroom.TrySetHeldAct(), GameUpdater.Update(), LogicalFire.Update(), CoreDebug.UpdateInput(), WidgetDebug.UpdateText(), Map.ValidateInstalled(), and VirtualRoom.VirtualRoom().
z
int Point.z
Definition at line 1515 of file Point.cs.
Referenced by Algorithms.PathFinder._FindPath(), PathManager._GetFirstStep(), Chara._Move(), Card._OnSerializing(), Zone.Activate(), SerializedCards.Add(), SourceMaterial.Row.AddBlood(), Zone.AddCard(), Map.AddCardOnActivate(), Lot.AddConnectedRooms(), Zone.AddThing(), PartialMap.Apply(), AM_Adv.AxisMove(), Recipe.Build(), Region.CanCreateZone(), Chara.CanInteractTo(), GoalManualMove.CanMove(), Chara.CanMoveTo(), Clamp(), MapBounds.Contains(), Copy(), RecipeCard.Craft(), EffectMeteor.Create(), SpatialGen.CreateInstance(), Region.CreateRandomSite(), Region.CreateZone(), Spatial.Dist(), Distance(), BaseTileMap.Draw(), TileMapElona.Draw(), BaseTileMap.DrawTile(), TileMapElona.DrawTile(), WidgetMinimap.EmitParticle(), Player.EnterLocalZone(), Equals(), ZonePreEnterBout.Execute(), ZonePreEnterDigStairs.Execute(), Chara.FindNewEnemy(), Algorithms.PathFinder.FindPath(), GameUpdater.LogicUpdater.FixedUpdate(), TraitBoat.ForeachDeck(), ForeachNearestPoint(), Map.ForeachNeighbor(), MapGen.g___MakeNeighbor(), MapGen.g___MakeRoad(), Zone_Dungeon.g__TryPlaceRail(), Zone_SnowGrave.GenerateGrave(), GetAngle2(), EloMap.GetCell(), AI_Clean.GetCleanPoint(), TraitScrollMapTreasure.GetDest(), TraitNewZone.GetExitPos(), AI_Fish.GetFishingPoint(), TileTypeWallHang.GetMountHeight(), GetNearestPoint(), AI_Trolley.GetPoint(), GetPointTowards(), Region.GetRandomPoint(), MapBounds.GetRandomSpace(), GetShared(), MapBounds.GetSpawnPos(), EloMap.GetZone(), AM_MoveInstalled.HitTest(), PathProgress.IsDestinationReached(), BaseTileSelector.IsInRange(), Los.IsVisible(), Map.ListPointsInArc(), Map.ListPointsInCircle(), Los.ListVisible(), Chara.LookAt(), MapGen.MakeRiver(), Map.MineBlock(), Map.MineFloor(), Map.MineRamp(), ModFire(), Map.MoveCard(), POIMap.OccyupyPOI(), WidgetArtTool.OnActivate(), Region.OnAdvanceHour(), AM_Copy.OnAfterProcessTiles(), Zone_Nymelle.OnBeforeSimulate(), Player.OnExitBorder(), ZoneEventSiege.OnFirstTick(), Act.OnMarkMapHighlights(), AIWork_Clean.OnPerformWork(), GenRoom.OnPopulate(), AM_Populate.OnProcessTiles(), AM_Terrain.OnProcessTiles(), TraitDeedRelocate.OnRead(), Recipe.OnRenderMarker(), AM_BaseTerrain.OnRenderTile(), HotItemHeld.OnRenderTile(), PointList.OnSerializing(), TraitDrink.OnThrowGround(), WidgetMinimap.OnUpdate(), Point(), Position(), PositionTopdown(), PositionTopdownTreasure(), AM_Adv.PressedActionMove(), ActEffect.ProcAt(), BaseTileSelector.ProcessTiles(), Room.Refresh(), AM_Region.RefreshArrow(), BaseTileSelector.RefreshMouseInfo(), Weather.RefreshWeather(), RegionPoint.RegionPoint(), Card.RenderMarker(), Map.Resize(), SerializedCards.Restore(), Map.Reveal(), AI_Fish.Run(), GoalCombat.Run(), GoalManualMove.Run(), TaskWater.Run(), RecipeUpdater.RunRecipe(), ActWait.Search(), LogicalPoint.Set(), Set(), SetBlock(), SetFloor(), SetObj(), RegionPoint.SetRegionPoint(), LayerCraftFloat.ShowContextMenu(), Zone.SpawnAltar(), ToString(), Zone.TryGenerateShrine(), AI_Goto.TryGoTo(), MapGen.TryMakeRiver(), Chara.TryMoveFrom(), TraitNewZone.TrySetAct(), TraitBroom.TrySetHeldAct(), GameUpdater.Update(), LogicalFire.Update(), CoreDebug.UpdateInput(), WidgetDebug.UpdateText(), Map.ValidateInstalled(), and VirtualRoom.VirtualRoom().
Zero
Point Point.Zero = new Point() static
Definition at line 1509 of file Point.cs.
Property Documentation
area
Area Point.area get
Definition at line 114 of file Point.cs.
    {
        get
        {
            CellDetail detail = this.detail;
            if (detail == null)
            {
                return null;
            }
            return detail.area;
        }
    }
Referenced by WidgetDate._Refresh(), RoomManager.GetHitResult(), Map.GetNearbyResourcePoint(), AM_EditArea.HitTest(), AM_ExpandArea.HitTest(), IsPublicSpace(), AM_EditArea.OnProcessTiles(), BaseTileSelector.OnUpdate(), Card.SetPlaceState(), RoomManager.TryAddArea(), and CoreDebug.UpdateInput().
cell
Cell Point.cell get
Definition at line 26 of file Point.cs.
    {
        get
        {
            return Point.map.cells[this.x, this.z];
        }
    }
Referenced by Map._AddCard(), TaskPoint._CanPerformTask(), AIWork._FuncWorkPoint(), PathManager._GetFirstStep(), ActionMode._HitTest(), TileType._HitTest(), Chara._Move(), Effect._Play(), Map._RemoveCard(), ActPlan._Update(), Map._ValidateInstalled(), Zone.Activate(), SourceMaterial.Row.AddBlood(), Area.AddPoint(), GameDate.AdvanceMin(), PartialMap.Apply(), TraitHouseBoard.ApplyData(), ActMelee.Attack(), RecipeBridgePillar.Build(), AI_Fish.CanPerform(), Player.CanSee(), TraitPotionEmpty.CanUse(), CoreDebug.COM_Teleport(), RecipeCard.Craft(), Crawler.Crawl(), Map.DestroyObj(), AIAct.DoGoto(), BaseGameScreen.Draw(), BaseTileMap.Draw(), TileMapElona.Draw(), CardRenderer.Draw(), ScreenGuide.DrawWall(), Chara.FindRoom(), AM_Build.FixBridge(), GameUpdater.SurfaceUpdater.FixedUpdate(), GameUpdater.FastSurfaceUpdater.FixedUpdate(), AI_Idle.g__FindMovePoint(), Zone_Dungeon.g__TryPlaceRail(), AI_Clean.GetCleanPoint(), TileTypeVine.GetDesiredDir(), TileTypeWallHang.GetDesiredDir(), AI_Fish.GetFishingPoint(), AM_Mine.GetGuidePass(), TaskBuild.GetHitResult(), TaskDrawWater.GetHitResult(), TaskMine.GetHitResult(), TaskPlow.GetHitResult(), Map.GetNearbyResourcePoint(), LogicalPointManager.GetOrCreate(), Map.GetRandomPoint(), MapBounds.GetRandomSpace(), MapBounds.GetRandomSpawnPos(), Zone.GetSpawnPos(), MapBounds.GetSurface(), ActEffect.GetTeleportPos(), TaskWater.GetText(), BaseTaskHarvest.GetTextSmall(), TaskDig.GetTextSmall(), TaskMine.GetTextSmall(), BaseTileMap.GetThingPosition(), TraitBoat.GetWaterMat(), Chara.HasAccess(), Recipe.HasSameTile(), AM_Build.HitTest(), AM_Copy.HitTest(), AM_FlagCell.HitTest(), TileTypeBridgePillar.HitTest(), TileTypeRoof.HitTest(), IsBlockByHeight(), TraitDoor.IsOpen(), IsPublicSpace(), TraitDoor.IsValid(), Trait.ListPoints(), Map.ListPointsInCircle(), Props.ListThingStack(), MapGen.MakeRiver(), Map.MineBlock(), Map.MineFloor(), Map.MineObjSound(), Map.MineRamp(), DesignationList< T >.OnAdd(), TaskDig.OnCreateProgress(), TaskDrawWater.OnCreateProgress(), TaskHarvest.OnCreateProgress(), TaskMine.OnCreateProgress(), TaskPlow.OnCreateProgress(), TaskPourWater.OnCreateProgress(), GrowSystem.OnExceedLastStage(), BaseListPeople.OnInstantiate(), ActRush.OnMarkMapHighlights(), WidgetMinimap.OnPointerDown(), AM_FlagCell.OnProcessTiles(), AM_Populate.OnProcessTiles(), AM_Terrain.OnProcessTiles(), TaskCut.OnProgress(), TaskBuild.OnProgressComplete(), Area.OnRemove(), Recipe.OnRenderMarker(), RecipeCard.OnRenderMarker(), ActionMode.OnRenderTile(), AM_Build.OnRenderTile(), AM_Mine.OnRenderTile(), AM_Picker.OnRenderTile(), TraitRoadSign.OnRenderTile(), ActionMode.OnRenderTileFloor(), TaskCut.OnStart(), TraitDye.OnThrowGround(), ActWater.Perform(), Plow(), GenRoom.Populate(), MapGen.Populate(), BiomeProfile.Populate(), Position(), PositionTopdown(), ActEffect.ProcAt(), Room.Refresh(), UIInspector.Refresh(), Zone.RefreshBGM(), ActionMode.RefreshTexts(), BaseGameScreen.RefreshWeather(), DesignationList< T >.Remove(), Area.RemovePoint(), Card.RenderMarker(), ActionMode.RotateUnderMouse(), AI_Fish.Run(), AI_Idle.Run(), TaskWater.Run(), RecipeUpdater.RunRecipe(), Map.SetFoormark(), Card.SetPlaceState(), AM_Adv.SetPressedAction(), BaseTaskHarvest.SetTarget(), TaskWater.ShouldWater(), AM_Picker.TestFloor(), AM_Terrain.TopHeight(), LogicalFire.Transfer(), Zone.TryAddThing(), BiomeProfile.ClusterObj.TryCreate(), BiomeProfile.ClusterThing.TryCreate(), AI_Goto.TryGoTo(), HotItemHeld.TrySetAct(), TraitHouseBoard.TrySetAct(), TraitRoomPlate.TrySetAct(), TraitBroom.TrySetHeldAct(), HotItemHeld.TrySetToolAct(), Map.TryShatter(), TraitSeed.TrySprout(), LogicalFire.Update(), TransAnime.Update(), GameUpdater.Update100ms(), ActionMode.UpdateInput(), Chara.UpdateSight(), WidgetDebug.UpdateText(), and BlockInfo.WriteNote().
Charas
List<Chara> Point.Charas get
Definition at line 464 of file Point.cs.
    {
        get
        {
            return this.cell.Charas;
        }
    }
Referenced by Chara._Move(), TraitGeneMachine.GetTarget(), TraitShackle.IsRestraining(), TraitHitchingPost.OnActivateTrap(), ActWater.Perform(), TraitGeneratorWheel.ShouldWork(), ConMiasma.Tick(), Chara.TryPush(), TraitSyringeGene.TrySetHeldAct(), TraitSyringeHeaven.TrySetHeldAct(), and TraitToolShears.TrySetHeldAct().
detail
CellDetail Point.detail get
Definition at line 106 of file Point.cs.
    {
        get
        {
            return this.cell.detail;
        }
    }
Referenced by GameDate.AdvanceMin(), FindChara(), FindThing< T >(), FirstVisibleChara(), AM_Build.HitResultOnDesignation(), Chara.IsEnemyOnPath(), ListCards(), ListCharas(), Map.ListCharasInCircle(), ListCharasInNeighbor(), ListThings< T >(), ListVisibleCards(), ListVisibleCharas(), ListWitnesses(), AM_Build.OnProcessTiles(), InspectGroupBlock.OnSetActions(), InspectGroupObj.OnSetActions(), ActWait.Search(), ActWait.SearchMedal(), Card.SetPlaceState(), AI_Idle.TryPerformIdleUse(), PointTarget.Update(), and CoreDebug.UpdateInput().
eloX
int Point.eloX get
Definition at line 143 of file Point.cs.
    {
        get
        {
            return EClass.scene.elomap.minX + this.x;
        }
    }
Referenced by Chara.Tick().
eloY
int Point.eloY get
Definition at line 151 of file Point.cs.
    {
        get
        {
            return EClass.scene.elomap.minY + this.z;
        }
    }
Referenced by Chara.Tick().
FirstChara
Chara Point.FirstChara get
Definition at line 390 of file Point.cs.
    {
        get
        {
            CellDetail detail = this.detail;
            if (detail == null || detail.charas.Count <= 0)
            {
                return null;
            }
            return this.detail.charas[0];
        }
    }
Referenced by TileType._HitTest(), ActMelee.Attack(), Chara.CanMoveTo(), ActRestrain.CanPerform(), Act.CanPerform(), TraitShackle.CanUse(), ActEffect.DamageEle(), AM_EditMarker.GetTarget(), ActRanged.Perform(), ActRestrain.Perform(), TraitShackle.TrySetHeldAct(), and HotItemHeld.TrySetToolAct().
FirstThing
Thing Point.FirstThing get
Definition at line 418 of file Point.cs.
    {
        get
        {
            CellDetail detail = this.detail;
            if (detail == null || detail.things.Count <= 0)
            {
                return null;
            }
            return this.detail.things[0];
        }
    }
Referenced by CoreDebug.UpdateInput().
Front
Point Point.Front get
Definition at line 127 of file Point.cs.
    {
        get
        {
            return new Point(this.x + 1, this.z - 1);
        }
    }
growth
GrowSystem Point.growth get
Definition at line 135 of file Point.cs.
    {
        get
        {
            return this.cell.growth;
        }
    }
Referenced by Recipe.Build(), AIWork_Lumberjack.FuncWorkPoint(), AIWork_Lumberjack.GetWork(), Recipe.HasSameTile(), TaskHarvest.OnCreateProgress(), TraitFertilizer.OnSimulateHour(), ZoneEventHarvest.OnVisit(), ActionMode.RotateUnderMouse(), and BaseTaskHarvest.SetTarget().
HasArea
bool Point.HasArea get
Definition at line 355 of file Point.cs.
    {
        get
        {
            CellDetail detail = this.detail;
            return ((detail != null) ? detail.area : null) != null;
        }
    }
Referenced by TileType._HitTest().
HasBlock
bool Point.HasBlock get
Definition at line 265 of file Point.cs.
    {
        get
        {
            return this.cell._block > 0;
        }
    }
Referenced by TileType._HitTest(), Zone.AddGlobalCharasOnActivate(), TaskMine.CanMine(), Crawler.CrawlUntil(), Card.DamageHP(), Chara.DestroyPath(), ZonePreEnterDigStairs.Execute(), Zone.g__GetPos(), Zone_SnowGrave.GenerateGrave(), TaskBuild.GetHitResult(), RoomManager.GetHitResult(), Act.OnMarkMapHighlights(), AM_Populate.OnProcessTiles(), TaskMine.OnProgressComplete(), ZoneEventMusic.OnVisit(), GenRoom.Populate(), ActEffect.ProcAt(), AI_HaulResource.Run(), BaseTaskHarvest.SetTarget(), AM_Picker.Test(), and HotItemHeld.TrySetAct().
HasBlockRecipe
bool Point.HasBlockRecipe get
Definition at line 321 of file Point.cs.
    {
        get
        {
            CellDetail detail = this.cell.detail;
            TaskBuild taskBuild = ((detail != null) ? detail.designation : null) as TaskBuild;
            return taskBuild != null && taskBuild.isBlock;
        }
    }
Referenced by UIInspector.DrawHighlight(), and ActionMode.GetGuidePass().
HasBridge
bool Point.HasBridge get
Definition at line 339 of file Point.cs.
    {
        get
        {
            return this.cell._bridge > 0;
        }
    }
Referenced by TaskDrawWater.g__ChangeFloor(), TaskPourWater.g__ChangeFloor(), TaskDig.GetHitResult(), TaskPourWater.GetHitResult(), Map.MineFloor(), TaskDrawWater.OnCreateProgress(), TaskPlow.OnCreateProgress(), and HotItemHeld.TrySetToolAct().
HasChara
bool Point.HasChara get
Definition at line 364 of file Point.cs.
    {
        get
        {
            CellDetail detail = this.detail;
            return detail != null && detail.charas.Count > 0;
        }
    }
Referenced by TileType._HitTest(), Chara._Move(), Zone.Activate(), Zone.AddCardSplinkle(), Recipe.Build(), TraitDoor.CanClose(), Chara.CanMoveTo(), TraitGeneratorWheel.CanUse(), BaseArea.GetEmptySeat(), Los.GetNearestNeighbor(), BaseArea.GetRandomPoint(), GetRandomPoint(), GetRandomPointInRadius(), Los.GetRushPoint(), AM_MoveInstalled.HitTest(), GenBounds.ListEmptyPoint(), ActRush.OnMarkMapHighlights(), Recipe.OnRenderMarker(), GoalSleep.OnSimulatePosition(), TraitSwing.OnSteppedOut(), ZoneEventMusic.OnVisit(), Card.RenderMarker(), GoalCombat.Run(), Player.TargetRanged(), Zone.TryGenerateShrine(), AI_Goto.TryGoTo(), Chara.TryMoveFrom(), and HotItemHeld.TrySetToolAct().
HasDecal
bool Point.HasDecal get
Definition at line 257 of file Point.cs.
    {
        get
        {
            return this.cell.decal > 0;
        }
    }
Referenced by TaskCut.GetHitResult(), TaskHarvest.GetHitResult(), and AIWork_Clean.OnPerformWork().
HasDesignation
bool Point.HasDesignation get
Definition at line 159 of file Point.cs.
    {
        get
        {
            CellDetail detail = this.cell.detail;
            return ((detail != null) ? detail.designation : null) != null;
        }
    }
Referenced by AM_Designation< T >.HitTest(), and AM_Build.OnProcessTiles().
HasDirt
bool Point.HasDirt get
Definition at line 168 of file Point.cs.
    {
        get
        {
            return this.cell.decal > 0;
        }
    }
Referenced by AI_Clean.GetCleanPoint(), AI_Clean.Run(), and TraitBroom.TrySetHeldAct().
HasFence
bool Point.HasFence get
Definition at line 297 of file Point.cs.
    {
        get
        {
            return this.cell._block != 0 && this.cell.sourceBlock.tileType.IsFence;
        }
    }
HasFloor
bool Point.HasFloor get
Definition at line 331 of file Point.cs.
    {
        get
        {
            return this.cell._floor > 0;
        }
    }
Referenced by CoreDebug.COM_Teleport(), Map.MineFloor(), and AM_Picker.Test().
HasMinableBlock
bool Point.HasMinableBlock get
Definition at line 273 of file Point.cs.
    {
        get
        {
            return this.HasObj && this.sourceBlock.tileType.IsFullBlock;
        }
    }
Referenced by AI_HaulResource.Run().
HasMultipleChara
bool Point.HasMultipleChara get
Definition at line 382 of file Point.cs.
    {
        get
        {
            return this.detail != null && this.detail.charas.Count > 1;
        }
    }
Referenced by GoalSleep.Run().
HasNonWallBlock
bool Point.HasNonWallBlock get
Definition at line 305 of file Point.cs.
    {
        get
        {
            return this.HasBlock && !this.cell.sourceBlock.tileType.IsWallOrFence;
        }
    }
Referenced by BlockInfo._CanInspect(), ActionMode.GetGuidePass(), and Recipe.OnRenderMarker().
HasObj
bool Point.HasObj get
Definition at line 249 of file Point.cs.
    {
        get
        {
            return this.cell.obj > 0;
        }
    }
Referenced by Chara._Move(), Map.ApplyBackerObj(), Recipe.Build(), TaskMine.CanMine(), TaskHarvest.CanProgress(), Chara.DestroyPath(), ZonePreEnterDigStairs.Execute(), Zone.g__GetPos(), Zone.Generate(), Zone_SnowGrave.GenerateGrave(), AreaTypeFarm.GetAI(), TaskCut.GetHitResult(), TaskDig.GetHitResult(), TaskHarvest.GetHitResult(), TaskMine.GetHitResult(), AreaTypeFarm.GetPlowPos(), TileType.HitTest(), TileTypeRoof.HitTest(), TileTypeWallMount.HitTest(), AM_Populate.OnProcessTiles(), Recipe.OnRenderMarker(), TraitFertilizer.OnSimulateHour(), TraitDye.OnThrowGround(), GenRoom.Populate(), Card.RenderMarker(), AI_HaulResource.Run(), TaskMoveInstalled.Run(), TraitSeed.TrySprout(), and ActionMode.UpdateInput().
HasRail
bool Point.HasRail get
Definition at line 233 of file Point.cs.
    {
        get
        {
            return this.sourceObj.tag.Contains("rail");
        }
    }
Referenced by TraitTrolley.CanActivate(), and AI_Trolley.GetPoint().
HasRamp
bool Point.HasRamp get
Definition at line 225 of file Point.cs.
    {
        get
        {
            return this.cell.HasRamp;
        }
    }
HasRampOrLadder
bool Point.HasRampOrLadder get
Definition at line 241 of file Point.cs.
    {
        get
        {
            return this.cell.HasRampOrLadder;
        }
    }
HasTaskBuild
bool Point.HasTaskBuild get
Definition at line 313 of file Point.cs.
    {
        get
        {
            return this.cell.detail != null && this.cell.detail.designation is TaskBuild;
        }
    }
HasThing
bool Point.HasThing get
Definition at line 373 of file Point.cs.
    {
        get
        {
            CellDetail detail = this.detail;
            return detail != null && detail.things.Count > 0;
        }
    }
Referenced by Chara._Move(), Zone.g__GetPos(), Zone_Dungeon.g__TryPlaceRail(), and Zone.TryGenerateShrine().
HasWall
bool Point.HasWall get
Definition at line 289 of file Point.cs.
    {
        get
        {
            return this.cell._block != 0 && this.cell.sourceBlock.tileType.IsWall;
        }
    }
HasWallOrFence
bool Point.HasWallOrFence get
Definition at line 281 of file Point.cs.
    {
        get
        {
            return this.cell.HasWallOrFence;
        }
    }
Referenced by TileType._HitTest(), AM_Mine.GetGuidePass(), TileTypeWallHang.GetMountHeight(), TaskBuild.OnProgressComplete(), and ActionMode.OnRenderTile().
index
int Point.index get
Definition at line 18 of file Point.cs.
    {
        get
        {
            return this.x + this.z * Point.map.Size;
        }
    }
Referenced by Map.AddPlant(), PartialMap.Apply(), Map.ApplyBackerObj(), VirtualDate.BuildSunMap(), DesignationList< T >.CanAdd(), TaskManager.Designations.CanRemoveDesignation(), Chara.CanSee(), Chara.CanSeeLos(), Chara.CanSeeSimple(), Map.GetBackerObj(), AM_RemoveDesignation.GetGuidePass(), LogicalPointManager.GetOrCreate(), Zone.GrowPlants(), HomeResourceWorth.ListHeirloom(), DesignationList< T >.OnAdd(), TaskDesignation.PointHasOtherDesignation(), Map.RefreshSunMap(), BackerContentInspector.ContentObj.Remove(), DesignationList< T >.Remove(), Map.RemovePlant(), SerializedCards.Restore(), Set(), Map.TryGetPlant(), and TaskManager.Designations.TryRemoveDesignation().
Installed
Thing Point.Installed get
Definition at line 444 of file Point.cs.
    {
        get
        {
            if (this.detail == null || this.detail.things.Count <= 0 || !this.detail.things[0].IsInstalled)
            {
                return null;
            }
            return this.detail.things[0];
        }
    }
Referenced by TaskBuild._GetHitResult(), TileType._HitTest(), Crawler.CrawlUntil(), GrowSystem.EqualizePlants(), Zone_SnowGrave.GenerateGrave(), TaskMine.OnProgressComplete(), ActionMode.OnRenderTile(), AM_Adv.OnRenderTile(), GenRoom.Populate(), ActionMode.RotateUnderMouse(), Zone.SpawnAltar(), and HotItemHeld.TrySetAct().
IsBlocked
bool Point.IsBlocked get
Definition at line 496 of file Point.cs.
    {
        get
        {
            return !this.IsValid || this.cell.blocked;
        }
    }
Referenced by Zone.AddCardSplinkle(), Chara.DestroyPath(), Card.EjectSockets(), Zone.g__GetPos(), AI_Trolley.GetPoint(), BaseArea.GetRandomFreePos(), BaseArea.GetRandomPoint(), Region.GetRandomPoint(), GetRandomPoint(), GetRandomPointInRadius(), MapBounds.GetRandomSpace(), Los.GetRushPoint(), TaskHarvest.HarvestThing(), AM_MoveInstalled.HitTest(), Chara.Kick(), Map.ListPointsInArc(), ActRush.OnMarkMapHighlights(), and AI_PlayMusic.Run().
IsFarmField
bool Point.IsFarmField get
Definition at line 209 of file Point.cs.
    {
        get
        {
            return (this.HasBridge ? this.sourceBridge : this.sourceFloor).alias == "field";
        }
    }
Referenced by TaskPlow.CanProgress(), AreaTypeFarm.GetPlowPos(), GrowSystem.OnExceedLastStage(), GrowSystemTree.OnMineObj(), Plow(), and TaskWater.ShouldWater().
IsHidden
bool Point.IsHidden get
Definition at line 488 of file Point.cs.
    {
        get
        {
            return !this.cell.isSeen || (this.cell.room != null && !EClass.screen.tileMap.hideRoomFog && !this.cell.hasDoor && this.cell.HasRoof);
        }
    }
Referenced by ActPlan._Update(), HotItemHeld.TrySetToolAct(), and PointTarget.Update().
IsHotSpring
bool Point.IsHotSpring get
Definition at line 504 of file Point.cs.
    {
        get
        {
            return this.cell.IsTopWaterAndNoSnow && (EClass._zone.elements.Has(3701) || this.IsInSpot<TraitGeyser>());
        }
    }
Referenced by AI_Idle.Run(), AI_PassTime.Run(), and TraitFoodEgg.Update().
IsInBounds
bool Point.IsInBounds get
Definition at line 188 of file Point.cs.
    {
        get
        {
            return this.x >= Point.map.bounds.x && this.z >= Point.map.bounds.z && this.x <= Point.map.bounds.maxX && this.z <= Point.map.bounds.maxZ;
        }
    }
Referenced by Map.AddCardOnActivate(), Chara.CanMoveTo(), QuestDefense.CanUpdateOnTalk(), AI_Idle.g__FindMovePoint(), AI_Trolley.GetPoint(), ActEffect.GetTeleportPos(), FactionBranch.OnActivateZone(), AM_Adv.PressedActionMove(), Zone.Revive(), AI_Idle.Run(), GoalManualMove.Run(), TaskDump.Run(), GoalManualMove.TryMove(), and TraitTeleporter.TryTeleport().
IsInBoundsPlus
bool Point.IsInBoundsPlus get
Definition at line 196 of file Point.cs.
    {
        get
        {
            return this.x >= 0 && this.z >= 0 && this.x <= Point.map.Size - 1 && this.z <= Point.map.Size - 1;
        }
    }
Referenced by ActionMode._HitTest().
IsSeen
bool Point.IsSeen get
Definition at line 472 of file Point.cs.
    {
        get
        {
            return this.cell.isSeen;
        }
    }
Referenced by ActionMode.GetGuidePass(), AM_Select.OnRefreshSummary(), ActionMode.OnRenderTile(), ActionMode.OnRenderTileFloor(), and BaseTileSelector.OnUpdate().
IsSky
bool Point.IsSky get
Definition at line 347 of file Point.cs.
    {
        get
        {
            return this.sourceFloor.tileType == TileType.Sky && !this.HasBridge;
        }
    }
Referenced by Map.MineFloor(), and GameUpdater.Update100ms().
IsSync
bool Point.IsSync get
Definition at line 480 of file Point.cs.
    {
        get
        {
            return this.cell.pcSync;
        }
    }
Referenced by ActEffect.DamageEle(), Card.Die(), AM_Adv.GetDefaultTile(), Zone.GetSpawnPos(), ActThrow.Throw(), and Game.Wait().
IsValid
bool Point.IsValid get set
Definition at line 176 of file Point.cs.
    {
        get
        {
            return this.x >= 0 && this.z >= 0 && this.x < Point.map.Size && this.z < Point.map.Size;
        }
        set
        {
            this.x = (value ? 0 : -999);
        }
    }
Referenced by PathManager._GetFirstStep(), ActionMode._HitTest(), AM_Sim._OnUpdateInput(), BaseTileSelector._ProcessTile(), ActPlan._Update(), Map._ValidateInstalled(), Zone.Activate(), Map.AddCardOnActivate(), Zone.AddCardSplinkle(), Zone.AddGlobalCharasOnActivate(), AM_Adv.AxisMove(), Chara.CanInteractTo(), Chara.CanMoveTo(), Chara.CanSee(), CoreDebug.COM_Teleport(), Chara.DestroyPath(), Card.Die(), AIAct.DoGoto(), AIAct.DoGotoInteraction(), BaseTileMap.Draw(), ZonePreEnterDigStairs.Execute(), GameUpdater.SurfaceUpdater.FixedUpdate(), GameUpdater.FastSurfaceUpdater.FixedUpdate(), ForeachNeighbor(), MapGen.g___MakeNeighbor(), MapGen.g___MakeRoad(), AI_Clean.GetCleanPoint(), PathManager.GetFirstStep(), AI_Fish.GetFishingPoint(), TaskBuild.GetHitResult(), LayerInspect.GetMenuItems(), Map.GetNearbyResourcePoint(), LogicalPointManager.GetOrCreate(), AI_Trolley.GetPoint(), Map.GetRandomEdge(), MapBounds.GetRandomEdge(), Trait.GetRandomPoint(), GetRandomPoint(), GetRandomPointInRadius(), MapBounds.GetRandomSpawnPos(), MapBounds.GetRandomSurface(), Zone.GetSpawnPos(), ActEffect.GetTeleportPos(), AM_BaseTerrain.HitTest(), UIInspector.InspectUnderMouse(), Chara.IsEnemyOnPath(), Map.MineBlock(), Map.MineFloor(), Map.MineRamp(), ActRush.OnMarkMapHighlights(), TileSelectorElona.OnRenderTile(), ActionMode.OnRenderTile(), AM_BaseTerrain.OnRenderTile(), ActionMode.OnRenderTileFloor(), BaseTileSelector.OnUpdate(), AM_BaseGameMode.OnUpdateInput(), LayerInspect.OnUpdateInput(), AM_Adv.PressedActionMove(), ActEffect.ProcAt(), WidgetSearch.RefreshList(), BaseTileSelector.RefreshMouseInfo(), Chara.RequestProtection(), SerializedCards.Restore(), ActionMode.RotateUnderMouse(), AI_Fish.Run(), AI_Idle.Run(), GoalCombat.Run(), GoalManualMove.Run(), TaskDump.Run(), Player.TargetRanged(), Chara.TryMoveFrom(), LayerInteraction.TryShow(), Zone.TrySpawnFollower(), GameUpdater.Update(), LogicalFire.Update(), PointTarget.Update(), GameUpdater.Update100ms(), ActionMode.UpdateInput(), CoreDebug.UpdateInput(), Chara.UpdateSight(), and WidgetDebug.UpdateText().
IsWater
bool Point.IsWater get
Definition at line 217 of file Point.cs.
    {
        get
        {
            return this.cell.IsTopWater;
        }
    }
Referenced by AIWork_Fish.FuncWorkPoint(), TaskDig.GetHitResult(), MapBounds.GetRandomSurface(), and MapGen.TryMakeRiver().
LastThing
Thing Point.LastThing get
Definition at line 431 of file Point.cs.
    {
        get
        {
            CellDetail detail = this.detail;
            if (detail == null || detail.things.Count <= 0)
            {
                return null;
            }
            return this.detail.things.LastItem<Thing>();
        }
    }
Referenced by AM_EditMarker.GetTarget(), AM_Visibility.GetTarget(), and AM_Adv.ShowAllAction().
matBlock
SourceMaterial.Row Point.matBlock get
Definition at line 42 of file Point.cs.
    {
        get
        {
            return this.cell.matBlock;
        }
    }
Referenced by TaskMine.CanMine(), ScreenGuide.DrawWall(), Recipe.HasSameTile(), Map.MineBlock(), Map.MineRamp(), TaskMine.OnCreateProgress(), TaskBuild.OnProgressComplete(), TaskMine.OnProgressComplete(), Room.Refresh(), BaseTaskHarvest.SetTarget(), and AM_Picker.TestBlock().
matBridge
SourceMaterial.Row Point.matBridge get
Definition at line 58 of file Point.cs.
    {
        get
        {
            return this.cell.matBridge;
        }
    }
Referenced by Recipe.HasSameTile(), Map.MineFloor(), and BaseTaskHarvest.SetTarget().
matFloor
SourceMaterial.Row Point.matFloor get
Definition at line 50 of file Point.cs.
    {
        get
        {
            return this.cell.matFloor;
        }
    }
Referenced by Chara._Move(), TaskDig.GetHitResult(), Recipe.HasSameTile(), Map.MineFloor(), TaskPlow.OnCreateProgress(), TaskDig.OnProgressComplete(), BaseTaskHarvest.SetTarget(), and AM_Picker.TestFloor().
matRoofBlock
SourceMaterial.Row Point.matRoofBlock get
Definition at line 34 of file Point.cs.
    {
        get
        {
            return this.cell.matRoofBlock;
        }
    }
sourceBlock
SourceBlock.Row Point.sourceBlock get
Definition at line 74 of file Point.cs.
    {
        get
        {
            return this.cell.sourceBlock;
        }
    }
Referenced by TileType._HitTest(), Chara._Move(), Crawler.CrawlUntil(), ScreenGuide.DrawWall(), AM_Mine.ForcedInstaComplete(), ActionMode.GetGuidePass(), TaskMine.GetHitResult(), TileTypeWallHang.GetMountHeight(), TileTypeWallMount.GetMountHeight(), Recipe.HasSameTile(), TileTypeWallMount.HitTest(), Chara.MoveByForce(), TaskMine.OnProgressComplete(), Room.Refresh(), BaseTaskHarvest.SetTarget(), AM_Picker.TestBlock(), and PointTarget.Update().
sourceBridge
SourceFloor.Row Point.sourceBridge get
Definition at line 90 of file Point.cs.
    {
        get
        {
            return this.cell.sourceBridge;
        }
    }
Referenced by Recipe.HasSameTile(), Map.MineFloor(), and BaseTaskHarvest.SetTarget().
sourceFloor
SourceFloor.Row Point.sourceFloor get
Definition at line 82 of file Point.cs.
    {
        get
        {
            return this.cell.sourceFloor;
        }
    }
Referenced by Chara._Move(), ZonePreEnterDigStairs.Execute(), AreaTypeFarm.GetPlowPos(), Recipe.HasSameTile(), Map.MineFloor(), TaskDrawWater.OnCreateProgress(), TaskPourWater.OnCreateProgress(), TaskDig.OnProgressComplete(), ZoneEventHarvest.OnVisit(), BaseTaskHarvest.SetTarget(), and AM_Picker.TestFloor().
sourceObj
SourceObj.Row Point.sourceObj get
Definition at line 98 of file Point.cs.
    {
        get
        {
            return this.cell.sourceObj;
        }
    }
Referenced by ObjInfo._CanInspect(), Recipe.Build(), TaskMine.CanMine(), ActBash.CanPerform(), GameUpdater.SurfaceUpdater.FixedUpdate(), Zone_Dungeon.g__TryPlaceRail(), Recipe.HasSameTile(), Map.MineBlock(), TaskHarvest.OnCreateProgress(), GrowSystemTree.OnMineObj(), TaskCut.OnProgressComplete(), ActBash.Perform(), and BaseTaskHarvest.SetTarget().
sourceRoofBlock
SourceBlock.Row Point.sourceRoofBlock get
Definition at line 66 of file Point.cs.
    {
        get
        {
            return this.cell.sourceRoofBlock;
        }
    }
Referenced by TaskBuild.OnProgressComplete().
Things
List<Thing> Point.Things get
Definition at line 456 of file Point.cs.
    {
        get
        {
            return this.cell.Things;
        }
    }
Referenced by TaskBuild._GetHitResult(), Chara._Move(), TraitDoor.CanClose(), Chara.DestroyPath(), ZonePreEnterDigStairs.Execute(), Zone_Dungeon.g__TryPlaceRail(), BaseArea.GetEmptySeat(), AI_Trolley.GetPoint(), MapBounds.GetSpawnPos(), AM_FlagCell.HitTest(), BaseArea.ListRoomNames(), AM_FlagCell.OnProcessTiles(), AM_MoveInstalled.OnProcessTiles(), AI_Idle.Run(), TaskWater.ShouldWater(), TraitGeneratorWheel.ShouldWork(), TaskHarvest.TryGetAct(), Zone.TryGetRestock< T >(), Zone.TryListThingsInSpot< T >(), TraitEcoMark.TrySetHeldAct(), TraitTicketFurniture.TrySetHeldAct(), and TraitWrench.TrySetHeldAct().
The documentation for this class was generated from the following file:
Elin/Point.cs