Elin Decompiled Documentation: Weather.WeatherForecast Class Reference
Weather.WeatherForecast Class Reference
Public Member Functions
void Add (Weather.Condition con, int h)
void Finish ()
Public Attributes
Date date
Dictionary< Weather.Condition, int > cons = new Dictionary<Weather.Condition, int>()
Detailed Description
Definition at line 317 of file Weather.cs.
Member Function Documentation
Add()
void Weather.WeatherForecast.Add (Weather::Condition con, int h) inline
Definition at line 319 of file Weather.cs.
        {
            if (this.cons.ContainsKey(con))
            {
                Dictionary<Weather.Condition, int> dictionary = this.cons;
                dictionary[con] += h;
                return;
            }
            this.cons[con] = h;
        }
References Weather.WeatherForecast.cons.
Referenced by Weather.GetWeatherForecast().
Finish()
void Weather.WeatherForecast.Finish () inline
Definition at line 330 of file Weather.cs.
        {
            if (this.cons.Count == 0)
            {
                return;
            }
            int num = this.cons.Sum((KeyValuePair<Weather.Condition, int> c) => c.Value);
            if (num != 0)
            {
                foreach (Weather.Condition key in this.cons.Keys.ToList<Weather.Condition>())
                {
                    this.cons[key] = this.cons[key] * 100 / num;
                }
            }
        }
References Weather.WeatherForecast.cons.
Referenced by Weather.GetWeatherForecast().
Member Data Documentation
cons
Dictionary<Weather.Condition, int> Weather.WeatherForecast.cons = new Dictionary<Weather.Condition, int>()
Definition at line 348 of file Weather.cs.
Referenced by Weather.WeatherForecast.Add(), and Weather.WeatherForecast.Finish().
date
Date Weather.WeatherForecast.date
Definition at line 346 of file Weather.cs.
Referenced by Weather.GetWeatherForecast().
The documentation for this class was generated from the following file:
Elin/Weather.cs