Elin Decompiled Documentation: LayerTreasureMap Class Reference
LayerTreasureMap Class Reference
Public Member Functions
void SetMap (TraitScrollMapTreasure trait)
Public Member Functions inherited from ELayer
override void OnBeforeAddLayer ()
void InitInspector ()
sealed override void Init ()
override void OnAfterAddLayer ()
void TryShowHelp ()
void AddLayerToUI (string id)
void TryShowHint (string _langHint=null)
void TalkHomeMemeber (string id)
void TalkMaid (string id)
override void OnRightClick ()
Public Attributes
RawImage image
Vector3 fix
Additional Inherited Members
Static Public Member Functions inherited from ELayer
static int rnd (int a)
Protected Member Functions inherited from ELayer
sealed override void _Close ()
sealed override void Kill ()
Properties inherited from ELayer
static Core core [get]
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static FactionBranch Branch [get]
static Faction Home [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static CoreConfig config [get]
static GameSetting setting [get]
static ColorProfile Colors [get]
static SourceManager sources [get]
static World world [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
bool IsFloat [get]
virtual string IdHelp [get]
Detailed Description
Definition at line 4 of file LayerTreasureMap.cs.
Member Function Documentation
SetMap()
void LayerTreasureMap.SetMap (TraitScrollMapTreasure trait) inline
Definition at line 10 of file LayerTreasureMap.cs.
    {
        ELayer.scene.elomapActor.Initialize(ELayer.world.region.elomap);
        if (!ELayer._zone.IsRegion)
        {
            ELayer.scene.elomapActor.transMap.SetActive(enable: true);
        }
        Point dest = trait.GetDest();
        ELayer.scene.camTreasure.transform.position = dest.PositionTopdownTreasure() + fix;
        ELayer.screen.UpdateShaders(1f);
        ELayer.scene.camTreasure.Render();
        ELayer.screen.UpdateShaders(ELayer.scene.timeRatio);
        if (!ELayer._zone.IsRegion)
        {
            ELayer.scene.elomapActor.transMap.SetActive(enable: false);
        }
    }
References ELayer._zone, Scene.camTreasure, Region.elomap, Scene.elomapActor, fix, TraitScrollMapTreasure.GetDest(), EloMapActor.Initialize(), Spatial.IsRegion, Point.PositionTopdownTreasure(), World.region, ELayer.scene, ELayer.screen, Scene.timeRatio, EloMapActor.transMap, BaseGameScreen.UpdateShaders(), and ELayer.world.
Member Data Documentation
fix
Vector3 LayerTreasureMap.fix
Definition at line 8 of file LayerTreasureMap.cs.
Referenced by SetMap().
image
RawImage LayerTreasureMap.image
Definition at line 6 of file LayerTreasureMap.cs.
The documentation for this class was generated from the following file:
Elin/LayerTreasureMap.cs