Elin Decompiled Documentation: BaseGameScreen Class Reference
BaseGameScreen Class Reference
Classes
class FocusOption
Public Member Functions
void Activate ()
virtual void OnActivate ()
void Deactivate ()
virtual void OnDeactivate ()
virtual void SetUnitSize ()
virtual void OnEndPlayerTurn ()
void Draw ()
void UpdateShaders (float time=0f)
virtual void OnChangeHour ()
virtual void RefreshPosition ()
void RefreshAll ()
void RefreshScreenSize ()
Point GetRandomPoint ()
void RefreshSky ()
virtual void RefreshWeather ()
void RefreshGrading ()
void RefreshTilt ()
void ScrollMouse (float x, float y)
void ScrollAxis (Vector3 axis, bool direct=false)
void Focus (Int3 ints)
void Focus (int x, int y)
void Focus (Card c)
void FocusCenter ()
void Focus (Point pos)
void FocusPC ()
void FocusImmediate (Point pos)
void SnapScreen (ref Vector3 v, float zoom)
void SetZoom (float z)
void SetTargetZoomIndex (int index)
void ModTargetZoomIndex (int a)
Public Attributes
float SharpenAmount
float camSpeed2
float heightLight
float pushbackSpeed
Vector2 snapSize
Vector2 tileSize
Vector2 tileAlign
Vector2 tileWorldSize
Vector2 tileViewSize
Vector3 tileWeight
Vector3 focusFix
Vector3 tileOffsetHeight
Vector3 tileWeightHeight
Vector3 planeAngle
Vector3 planeSpeed
Vector2 paddings
Vector2 paddingOffset
Vector3 lastPos
Rect mapLimit
float Zoom
float nextMove
float focusSpeed
float focusSpeedSlow
float focusSpeedSlow2
int width
int height
int scrollX
int scrollY
int moonLevel
BaseTileMap tileMap
BaseTileSelector tileSelector
ScreenGuide guide
Grid grid
MeshRenderer overlayShadow
PCOrbit pcOrbit
float forcePrecision
bool isCameraMoving
FocusOption focusOption
Vector3? focusPos
Vector3 position
float screenFixX
float screenFixX2
float screenFixX3
float screenFixX4
float screenFixY
float screenFixY2
float screenFixY3
float screenFixY4
bool instantFocus
int targetZoomIndex
float targetZoom = 0.5f
float zoomTimer
Vector3 zoomPos
Protected Attributes
Vector3 camPos
Vector3 pushBack
Properties
bool fixFocus [get]
virtual float TargetZoom [get]
CameraSupport camSupport [get]
Transform transFocus [get]
virtual float SkyRate [get]
virtual float ViewHeight [get]
virtual bool IsGameScreen [get]
virtual bool IsLocalMap [get]
Properties inherited from EMono
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SoundManager Sound [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static CoreDebug debug [get]
Private Attributes
readonly int _BackDrawPower = Shader.PropertyToID("_BackDrawPower")
readonly int _Snow = Shader.PropertyToID("_Snow")
readonly int _SkyLevel = Shader.PropertyToID("_SkyLevel")
readonly int _NightRate = Shader.PropertyToID("_NightRate")
readonly int _ViewHeight = Shader.PropertyToID("_ViewHeight")
readonly int _FogStrength = Shader.PropertyToID("_FogStrength")
readonly int _FogColor = Shader.PropertyToID("_FogColor")
readonly int _FowColor = Shader.PropertyToID("_FowColor")
readonly int _SunColor = Shader.PropertyToID("_SunColor")
readonly int _SeaColor = Shader.PropertyToID("_SeaColor")
readonly int _SkyColor = Shader.PropertyToID("_SkyColor")
readonly int _SkyBGColor = Shader.PropertyToID("_SkyBGColor")
readonly int _Offset = Shader.PropertyToID("_Offset")
readonly int _Zoom = Shader.PropertyToID("_Zoom")
readonly int _LightPower = Shader.PropertyToID("_LightPower")
readonly int _AnimeSpeedGlobal = Shader.PropertyToID("_AnimeSpeedGlobal")
readonly int _ScreenFlash = Shader.PropertyToID("_ScreenFlash")
Vector3 _camPos
Point _randomPoint = new Point()
Additional Inherited Members
Static Public Member Functions inherited from EMono
static int rnd (int a)
Static Public Attributes inherited from EMono
static Core core
Detailed Description
Definition at line 4 of file BaseGameScreen.cs.
Member Function Documentation
Activate()
void BaseGameScreen.Activate () inline
Definition at line 192 of file BaseGameScreen.cs.
    {
        if (!(EMono.core.screen == this))
        {
            if (EMono.core.screen != null)
            {
                EMono.core.screen.Deactivate();
            }
            SetUnitSize();
            EMono.core.screen = this;
            Point._screen = this;
            base.gameObject.SetActive(value: true);
            EMono.scene.flock.SetActive(IsLocalMap);
            EMono.scene.fireflyNight.SetActive(IsLocalMap);
            EMono.scene.firefly.SetActive(IsLocalMap);
            EMono.scene.star.SetActive(IsLocalMap);
            EMono.scene.sfxRain.SetActive(IsGameScreen);
            EMono.scene.sfxSea.SetActive(IsGameScreen);
            EMono.scene.sfxWind.SetActive(IsGameScreen);
            EMono.scene.sfxFire.SetActive(IsGameScreen);
            EMono.scene.sfxUnderwater.SetActive(IsLocalMap && EMono.core.IsGameStarted && EMono._zone.IsUnderwater);
            OnActivate();
            ParticleSystem.MainModule main = EMono.scene.rain.main;
            ParticleSystem.MainModule main2 = EMono.scene.snow.main;
            ParticleSystem.MainModule main3 = EMono.scene.ether.main;
            bool flag2 = (main3.prewarm = true);
            bool prewarm = (main2.prewarm = flag2);
            main.prewarm = prewarm;
            ParticleSystem[] blossoms = EMono.scene.blossoms;
            for (int i = 0; i < blossoms.Length; i++)
            {
                ParticleSystem.MainModule main4 = blossoms[i].main;
                main4.prewarm = true;
            }
            if ((bool)overlayShadow)
            {
                overlayShadow.SetActive(EMono.scene.profile.matOverlay);
                overlayShadow.sharedMaterial = EMono.scene.profile.matOverlay;
            }
            EMono.scene.camSupport.grading.material = EMono.scene.profile.matGrading;
            if (IsGameScreen)
            {
                EMono.scene.OnChangeHour();
                EMono.scene.ApplyZoneConfig();
                RefreshAll();
                tileMap.OnActivate(this);
                WidgetHotbar.RefreshHighlights();
            }
            else if (EMono.core.config != null)
            {
                EMono.core.config.RefreshUIBrightness();
            }
        }
    }
References EMono._zone, Scene.ApplyZoneConfig(), Scene.blossoms, Core.config, EMono.core, Deactivate(), Scene.ether, Scene.firefly, Scene.fireflyNight, Scene.flock, IsGameScreen, Core.IsGameStarted, IsLocalMap, Zone.IsUnderwater, SceneProfile.matGrading, SceneProfile.matOverlay, OnActivate(), BaseTileMap.OnActivate(), Scene.OnChangeHour(), overlayShadow, Scene.profile, Scene.rain, RefreshAll(), WidgetHotbar.RefreshHighlights(), CoreConfig.RefreshUIBrightness(), EMono.scene, Core.screen, SetUnitSize(), Scene.sfxFire, Scene.sfxRain, Scene.sfxSea, Scene.sfxUnderwater, Scene.sfxWind, Scene.snow, Scene.star, and tileMap.
Referenced by ActionMode.Activate(), Core.Awake(), and Scene.Init().
Deactivate()
void BaseGameScreen.Deactivate () inline
Definition at line 251 of file BaseGameScreen.cs.
    {
        OnDeactivate();
        base.gameObject.SetActive(value: false);
        EMono.core.screen = null;
    }
References OnDeactivate().
Referenced by Activate(), Scene.Init(), and ZoneInspector.RefreshScreen().
Draw()
void BaseGameScreen.Draw () inline
Definition at line 270 of file BaseGameScreen.cs.
    {
        if (!IsGameScreen)
        {
            return;
        }
        if (Zoom != targetZoom)
        {
            bool flag = EMono.scene.actionMode == ActionMode.Bird;
            CoreConfig.CameraConfig camera = EMono.core.config.camera;
            float num = camera.zoomSpeed * (flag ? 0.05f : (camera.linearZoom ? 2f : 1f)) * Core.delta;
            zoomTimer += num * 0.3f;
            float t = ((flag || !camera.linearZoom) ? num : zoomTimer);
            float num2 = Mathf.Lerp(EMono.screen.Zoom, targetZoom, t);
            if (Mathf.Abs(num2 - targetZoom) < (flag ? 0.0005f : 0.003f))
            {
                num2 = targetZoom;
            }
            if (camera.zoomToMouse && zoomPos != Vector3.zero)
            {
                position = Vector3.Lerp(position, zoomPos, t);
            }
            EMono.core.config.ApplyZoom(num2);
        }
        RenderObject.gameSpeed = EMono.scene.actionMode.gameSpeed;
        RenderObject.gameDelta = Core.gameDeltaNoPause;
        if (EMono.pc.currentZone == EMono._zone && !EMono._zone.IsRegion && focusOption == null && !focusPos.HasValue && !transFocus && fixFocus && (instantFocus || !EMono.core.config.camera.smoothFollow))
        {
            if (Zoom != targetZoom)
            {
                EMono.core.config.ApplyZoom(TargetZoom);
            }
            Vector3 vector = (EMono.pc.isSynced ? EMono.player.position : EMono.pc.pos.Position()) + focusFix;
            position = vector;
            scrollX = Mathf.FloorToInt(position.x / tileWorldSize.x) - width / 2 + (int)paddingOffset.x;
            scrollY = Mathf.FloorToInt(position.y / tileWorldSize.y) - height / 4 + (int)paddingOffset.y;
        }
        tileMap.Draw();
        if (instantFocus)
        {
            instantFocus = false;
        }
        RefreshPosition();
        if (EMono.game.activeZone != null)
        {
            for (int num3 = EMono._map.pointAnimes.Count - 1; num3 >= 0; num3--)
            {
                if (EMono._map.pointAnimes[num3].Update())
                {
                    EMono._map.pointAnimes.RemoveAt(num3);
                }
            }
        }
        UpdateShaders(EMono.scene.timeRatio);
        if (Scene.skipAnime)
        {
            EffectManager.Instance.KillAll();
            Scene.skipAnime = false;
        }
        EffectManager.Instance.UpdateEffects();
        FlockController flock = EMono.scene.flock;
        int visible;
        if (targetZoom <= 1.25f)
        {
            Room room = EMono.pc.pos.cell.room;
            visible = ((room == null || !room.HasRoof) ? 1 : 0);
        }
        else
        {
            visible = 0;
        }
        flock.UpdateVisible((byte)visible != 0);
        if (EMono.pc.isSynced && (bool)EMono.pc.renderer.orbit)
        {
            EMono.pc.renderer.orbit.Refresh();
        }
    }
References EMono._map, EMono._zone, Scene.actionMode, Game.activeZone, CoreConfig.ApplyZoom(), ActionMode.Bird, CoreConfig.camera, Point.cell, Core.config, EMono.core, Chara.currentZone, Core.delta, BaseTileMap.Draw(), fixFocus, Scene.flock, focusFix, focusOption, focusPos, EMono.game, Core.gameDeltaNoPause, ActionMode.gameSpeed, Room.HasRoof, height, EffectManager.Instance, instantFocus, IsGameScreen, Spatial.IsRegion, Chara.isSynced, EffectManager.KillAll(), CoreConfig.CameraConfig.linearZoom, CardRenderer.orbit, paddingOffset, EMono.pc, Map.pointAnimes, Card.pos, position, Point.Position(), TCOrbit.Refresh(), RefreshPosition(), Card.renderer, Cell.room, EMono.scene, EMono.screen, scrollX, scrollY, Scene.skipAnime, CoreConfig.CameraConfig.smoothFollow, targetZoom, TargetZoom, tileMap, tileWorldSize, Scene.timeRatio, transFocus, EffectManager.UpdateEffects(), UpdateShaders(), width, Zoom, zoomPos, zoomTimer, and CoreConfig.CameraConfig.zoomToMouse.
Referenced by Scene.OnUpdate().
Focus() [1/4]
void BaseGameScreen.Focus (Card c) inline
Definition at line 750 of file BaseGameScreen.cs.
    {
        if (c != null)
        {
            Focus(c.GetRootCard().pos);
        }
    }
References Focus(), Card.GetRootCard(), and Card.pos.
Focus() [2/4]
void BaseGameScreen.Focus (int x, int y) inline
Definition at line 739 of file BaseGameScreen.cs.
    {
        if (EMono.AdvMode)
        {
            SE.Beep();
            return;
        }
        position.x = (scrollX = x);
        position.y = (scrollY = y);
    }
References EMono.AdvMode, scrollX, and scrollY.
Focus() [3/4]
void BaseGameScreen.Focus (Int3 ints) inline
Definition at line 734 of file BaseGameScreen.cs.
    {
        position = new Vector3(ints.x, ints.y, ints.z);
    }
References position, Int3.x, Int3.y, and Int3.z.
Referenced by WidgetMainText.Append(), LayerNewZone.Embark(), Focus(), Scene.FocusAndPause(), FocusCenter(), FocusImmediate(), FocusPC(), NotificationBattle.OnClick(), NotificationGuest.OnClick(), and HotItemFocusChara.OnClick().
Focus() [4/4]
void BaseGameScreen.Focus (Point pos) inline
Definition at line 764 of file BaseGameScreen.cs.
    {
        position = pos.PositionCenter();
    }
References position, and Point.PositionCenter().
FocusCenter()
void BaseGameScreen.FocusCenter () inline
Definition at line 758 of file BaseGameScreen.cs.
    {
        Point pos = new Point(EMono._map.Size / 2, EMono._map.Size / 2);
        Focus(pos);
    }
References EMono._map, Focus(), and MapBounds.Size.
FocusImmediate()
void BaseGameScreen.FocusImmediate (Point pos) inline
Definition at line 777 of file BaseGameScreen.cs.
    {
        focusPos = null;
        Focus(pos);
        instantFocus = true;
        RefreshPosition();
        RefreshPosition();
    }
References Focus(), focusPos, instantFocus, and RefreshPosition().
FocusPC()
void BaseGameScreen.FocusPC () inline
Definition at line 769 of file BaseGameScreen.cs.
    {
        focusPos = null;
        Focus((EMono.pc.currentZone == EMono.game.activeZone) ? EMono.pc.pos : EMono._map.bounds.GetCenterPos());
        instantFocus = true;
        RefreshPosition();
    }
References EMono._map, Game.activeZone, Map.bounds, Chara.currentZone, Focus(), focusPos, EMono.game, MapBounds.GetCenterPos(), instantFocus, EMono.pc, Card.pos, and RefreshPosition().
Referenced by Scene.Init(), Card.MoveImmediate(), AM_Adv.OnActivate(), and Card.Teleport().
GetRandomPoint()
Point BaseGameScreen.GetRandomPoint () inline
Definition at line 578 of file BaseGameScreen.cs.
    {
        int num = EMono.screen.scrollX - EMono.screen.scrollY + width / 2 - (height / 2 + 1) / 2;
        int num2 = EMono.screen.scrollY + EMono.screen.scrollX + width / 2 + height / 2 / 2;
        num = num - 20 + EMono.rnd(40);
        num2 = num2 - 20 + EMono.rnd(40);
        return _randomPoint.Set(num, num2);
    }
References _randomPoint, height, EMono.rnd(), Point.Set(), and width.
Referenced by GameUpdater.Update100ms().
ModTargetZoomIndex()
void BaseGameScreen.ModTargetZoomIndex (int a) inline
Definition at line 859 of file BaseGameScreen.cs.
    {
        if (!EMono.scene.elomapActor.IsActive)
        {
            int num = targetZoomIndex;
            targetZoomIndex -= a;
            int num2 = ((!EMono.core.config.camera.extendZoomMin) ? 1 : 0);
            int num3 = (EMono.core.config.camera.extendZoomMax ? 4 : 3);
            if (targetZoomIndex < num2)
            {
                targetZoomIndex = num2;
            }
            else if (targetZoomIndex >= num3)
            {
                targetZoomIndex = num3;
            }
            if (targetZoomIndex > num && EInput.buttonScroll != null && !EInput.buttonScroll.pressing)
            {
                zoomPos = EInput.mposWorld;
            }
            SetTargetZoomIndex(targetZoomIndex);
        }
    }
References EInput.buttonScroll, CoreConfig.camera, Core.config, EMono.core, Scene.elomapActor, CoreConfig.CameraConfig.extendZoomMin, EloMapActor.IsActive, EInput.mposWorld, ButtonState.pressing, EMono.scene, SetTargetZoomIndex(), targetZoomIndex, and zoomPos.
Referenced by ActionMode.InputWheel().
OnActivate()
virtual void BaseGameScreen.OnActivate () inline virtual
Reimplemented in GameScreen, and GameScreenElona.
Definition at line 247 of file BaseGameScreen.cs.
    {
    }
Referenced by Activate().
OnChangeHour()
virtual void BaseGameScreen.OnChangeHour () inline virtual
Reimplemented in GameScreenElona.
Definition at line 403 of file BaseGameScreen.cs.
    {
    }
Referenced by Scene.OnChangeHour().
OnDeactivate()
virtual void BaseGameScreen.OnDeactivate () inline virtual
Reimplemented in GameScreenElona.
Definition at line 258 of file BaseGameScreen.cs.
    {
    }
Referenced by Deactivate().
OnEndPlayerTurn()
virtual void BaseGameScreen.OnEndPlayerTurn () inline virtual
Definition at line 266 of file BaseGameScreen.cs.
    {
    }
RefreshAll()
void BaseGameScreen.RefreshAll () inline
Definition at line 521 of file BaseGameScreen.cs.
    {
        RefreshScreenSize();
        bool indoor = EMono._map.config.indoor;
        ScreenGrading grading = camSupport.grading;
        EMono.scene.flock.SetActive(!indoor);
        if (indoor)
        {
            grading.material.DisableKeyword("CLOUD_ON");
        }
        else
        {
            grading.material.EnableKeyword("CLOUD_ON");
        }
        if (EMono.core.config.graphic.floorEx)
        {
            EMono.scene.matFloorEx.EnableKeyword("EX_ON");
        }
        else
        {
            EMono.scene.matFloorEx.DisableKeyword("EX_ON");
        }
        grading.profile.vignette.enable = EMono.scene.profile.light.vignette;
        grading.profile.vignette.vignetteColor = EMono.scene.profile.light.vignetteColor;
        RefreshSky();
        RefreshTilt();
    }
References EMono._map, camSupport, Core.config, Map.config, EMono.core, Scene.flock, CoreConfig.GraphicSetting.floorEx, CameraSupport.grading, CoreConfig.graphic, MapConfig.indoor, SceneProfile.light, Scene.matFloorEx, Scene.profile, RefreshScreenSize(), RefreshSky(), RefreshTilt(), EMono.scene, SceneLightProfile.vignette, and SceneLightProfile.vignetteColor.
Referenced by Activate(), CoreDebug.COM_PlayStartDrama(), BuildMenu.Deactivate(), BuildMenu.OnActivate(), WidgetArtTool.OnActivate(), HotItemContext.Show(), and TraitMapBoard.TrySetAct().
RefreshGrading()
void BaseGameScreen.RefreshGrading () inline
Definition at line 676 of file BaseGameScreen.cs.
    {
        float timeRatio = (EMono.core.IsGameStarted ? EMono.scene.timeRatio : 0f);
        if ((bool)camSupport.grading.profile.overlay)
        {
            camSupport.grading.profile.overlay.Refresh(timeRatio, EMono._zone.IsSnowCovered);
        }
        ScreenGrading.blind = EMono.pc.isBlind;
        camSupport.grading.profile.sharpen.enable = EMono.core.config.graphic.sharpen > 0;
        camSupport.grading.profile.sharpen.Strength = Mathf.Clamp(0.1f * (float)EMono.core.config.graphic.sharpen, 0f, (this is GameScreen) ? 10f : 1f);
        camSupport.beautify.sharpen = Mathf.Clamp(0.01f * (float)EMono.core.config.graphic.sharpen2, 0f, (this is GameScreen) ? 10f : 0.5f);
        camSupport.grading.SetGrading();
        SceneTemplate sceneTemplate = SceneTemplate.Load(EMono._map.config.idSceneTemplate.IsEmpty(EMono._zone.IDSceneTemplate));
        Color tintColor = EMono._map.config.colorScreen.Get();
        if (tintColor.a == 0f)
        {
            tintColor = sceneTemplate.colorScreen;
        }
        camSupport.beautify.tintColor = tintColor;
        tintColor = EMono._map.config.colorSea.Get();
        MATERIAL.sourceWaterSea.matColor = ((tintColor.a == 0f) ? MATERIAL.sourceWaterSea.GetColor() : tintColor);
        EMono.core.config.RefreshUIBrightness();
        float num = 0f;
        if (!EMono._map.IsIndoor)
        {
            num += 0.01f * EMono.core.config.test.brightnessNight * EMono.scene.profile.light.nightRatioCurve.Evaluate(EMono.scene.timeRatio);
        }
        camSupport.grading.nightBrightness = num;
    }
References EMono._map, EMono._zone, camSupport, Color, MapConfig.colorScreen, SceneTemplate.colorScreen, MapConfig.colorSea, Core.config, Map.config, EMono.core, SerializableColor.Get(), CameraSupport.grading, CoreConfig.graphic, MapConfig.idSceneTemplate, Zone.IDSceneTemplate, Chara.isBlind, Map.IsIndoor, Spatial.IsSnowCovered, SceneProfile.light, SceneTemplate.Load(), SceneLightProfile.nightRatioCurve, EMono.pc, Scene.profile, CoreConfig.RefreshUIBrightness(), EMono.scene, CoreConfig.GraphicSetting.sharpen, CoreConfig.GraphicSetting.sharpen2, MATERIAL.sourceWaterSea, and Scene.timeRatio.
Referenced by GameDate.AdvanceMin(), CoreConfig.ApplyGrading(), RefreshSky(), and TraitMapBoard.TrySetAct().
RefreshPosition()
virtual void BaseGameScreen.RefreshPosition () inline virtual
Reimplemented in GameScreenElona.
Definition at line 407 of file BaseGameScreen.cs.
    {
        if (EMono.pc.currentZone != EMono._zone)
        {
            return;
        }
        if (focusOption != null)
        {
            Vector3 vector = (focusOption.player ? (EMono.pc.pos.Position() + focusFix) : focusOption.pos.PositionCenter());
            vector.z = position.z;
            if (focusOption.linear)
            {
                position = Vector3.MoveTowards(position, vector, focusOption.speed * Core.delta);
            }
            else
            {
                position = Vector3.Lerp(position, vector, focusOption.speed * Core.delta);
            }
        }
        else if (focusPos.HasValue)
        {
            Vector3 obj = focusPos ?? position;
            float x = obj.x;
            Vector3 obj2 = focusPos ?? position;
            focusPos = new Vector3(x, obj2.y, position.z);
            position = Vector3.Lerp(position, focusPos ?? position, focusSpeedSlow * Core.delta);
            if (Vector3.Distance(position, focusPos ?? position) < 0.1f)
            {
                focusPos = null;
            }
        }
        else if ((bool)transFocus)
        {
            pushBack = Vector3.zero;
            position.x = transFocus.position.x;
            position.y = transFocus.position.y;
        }
        else if (fixFocus)
        {
            float z = position.z;
            targetZoom = TargetZoom;
            for (int i = 0; i < EMono.core.config.camera.zooms.Length; i++)
            {
                if (targetZoom == EMono.core.config.camera.zooms[i])
                {
                    targetZoomIndex = i;
                }
            }
            Vector3 b = (EMono.pc.isSynced ? EMono.player.position : EMono.pc.pos.Position()) + focusFix;
            if (instantFocus)
            {
                position = b;
            }
            else if (EMono.core.config.camera.smoothFollow)
            {
                position = Vector3.Lerp(position, b, focusSpeed * Core.delta * Mathf.Lerp(0.2f, 1f, 1f - Mathf.Clamp(ActionMode.Adv.rightMouseTimer, 0f, 1f)));
            }
            else
            {
                position = b;
            }
            position.z = z;
            pcOrbit.transform.position = EMono.pc.renderer.position;
        }
        else
        {
            if (ActionMode.Adv.IsActive)
            {
                targetZoom = ActionMode.Adv.TargetZoom;
            }
            pushBack = Vector3.zero;
            int num = scrollX - scrollY;
            int num2 = scrollY + scrollX;
            if ((float)num <= mapLimit.x)
            {
                pushBack.x = mapLimit.x - (float)num;
            }
            if ((float)num2 <= mapLimit.y)
            {
                pushBack.y = mapLimit.y - (float)num2;
            }
            if ((float)num >= (float)EMono._map.Size + mapLimit.width - (float)(width / 2))
            {
                pushBack.x = (float)EMono._map.Size + mapLimit.width - (float)(width / 2) - (float)num;
            }
            if ((float)num2 >= (float)EMono._map.Size + mapLimit.height - (float)(height / 2))
            {
                pushBack.y = (float)EMono._map.Size + mapLimit.height - (float)(height / 2) - (float)num2;
            }
            position += Quaternion.Euler(planeAngle) * pushBack * Core.delta * pushbackSpeed;
        }
        scrollX = Mathf.FloorToInt(position.x / tileWorldSize.x) - width / 2 + (int)paddingOffset.x;
        scrollY = Mathf.FloorToInt(position.y / tileWorldSize.y) - height / 4 + (int)paddingOffset.y;
        if (lastPos.x != (float)scrollX || lastPos.y != (float)scrollY)
        {
            lastPos.x = scrollX;
            lastPos.y = scrollY;
        }
        camPos.x = position.x;
        camPos.y = position.y;
        SnapScreen(ref camPos, Zoom);
        camPos.z = -500f;
        _camPos.x = camPos.x + screenFixX2 + screenFixX4;
        _camPos.y = camPos.y + screenFixY2 + screenFixY4;
        _camPos.z = camPos.z;
        EMono.scene.cam.transform.localPosition = _camPos;
        camPos.z = 0f;
        EMono.scene.transAudio.position = camPos + EMono.scene.posAudioListener;
        if ((bool)WidgetMinimap.Instance)
        {
            WidgetMinimap.Instance.OnUpdate();
        }
    }
References _camPos, EMono._map, EMono._zone, ActionMode.Adv, CoreConfig.camera, camPos, Core.config, EMono.core, Chara.currentZone, Core.delta, fixFocus, focusFix, focusOption, focusPos, focusSpeed, focusSpeedSlow, height, if(), WidgetMinimap.Instance, instantFocus, ActionMode.IsActive, lastPos, BaseGameScreen.FocusOption.linear, mapLimit, WidgetMinimap.OnUpdate(), paddingOffset, EMono.pc, planeAngle, BaseGameScreen.FocusOption.pos, Card.pos, Scene.posAudioListener, position, CardRenderer.position, Point.Position(), Point.PositionCenter(), pushBack, pushbackSpeed, Card.renderer, AM_Adv.rightMouseTimer, EMono.scene, screenFixX2, screenFixX4, screenFixY2, screenFixY4, scrollX, scrollY, MapBounds.Size, CoreConfig.CameraConfig.smoothFollow, SnapScreen(), BaseGameScreen.FocusOption.speed, AM_Adv.TargetZoom, targetZoom, TargetZoom, targetZoomIndex, tileWorldSize, transFocus, width, Zoom, and CoreConfig.CameraConfig.zooms.
Referenced by Draw(), FocusImmediate(), FocusPC(), Card.MoveImmediate(), AM_Adv.OnActivate(), ScrollMouse(), and Card.Teleport().
RefreshScreenSize()
void BaseGameScreen.RefreshScreenSize () inline
Definition at line 549 of file BaseGameScreen.cs.
    {
        Zoom = EMono.scene.camSupport.Zoom;
        width = (int)((float)Screen.width / tileSize.x / Zoom) + (int)paddings.x + 2 + EMono.core.config.test.screenExtraWidth;
        height = (int)((float)Screen.height / (tileSize.y / 2f) / Zoom) + (int)paddings.y + 4 + EMono.core.config.test.screenExtraHeight;
        camSupport.divier = EMono.core.config.fix.divider;
        camSupport.ResizeCameraToPixelPerfect();
        Vector3 localScale = new Vector3(EMono.scene.cam.orthographicSize * ((float)Screen.width / (float)Screen.height) * 2.5f, EMono.scene.cam.orthographicSize * 2.5f, 1f);
        if (EMono.core.IsGameStarted)
        {
            EMono.scene.skyBG.transform.localScale = localScale;
            float num = ((ActionMode.IsAdv || Zoom >= 1f || EMono._map.IsIndoor) ? 0f : (0.4f / Zoom));
            if (EMono.world.weather.CurrentCondition == Weather.Condition.SnowHeavy)
            {
                num += 0.8f;
            }
            if (!EMono.player.simulatingZone)
            {
                EMono.scene.sfxWind.SetVolume(Mathf.Min(num, 1f));
            }
        }
        Vector3 vector = EMono.scene.cam.transform.position;
        EMono.scene.cam.transform.position = Vector3.zero;
        Vector3 vector2 = EMono.scene.cam.WorldToScreenPoint(Vector3.zero);
        screenFixX2 = vector2.x % screenFixX * screenFixX3;
        screenFixY2 = vector2.y % screenFixY * screenFixY3;
        EMono.scene.cam.transform.position = vector;
    }
References EMono._map, Scene.cam, camSupport, Scene.camSupport, Core.config, EMono.core, Weather.CurrentCondition, CoreConfig.Fix.divider, CameraSupport.divier, CoreConfig.fix, height, Core.IsGameStarted, Map.IsIndoor, paddings, EMono.player, CameraSupport.ResizeCameraToPixelPerfect(), EMono.scene, CoreConfig.Test.screenExtraHeight, CoreConfig.Test.screenExtraWidth, screenFixX, screenFixX2, screenFixX3, screenFixY, screenFixY2, screenFixY3, Scene.sfxWind, Player.simulatingZone, CoreConfig.test, World.weather, width, EMono.world, Zoom, and CameraSupport.Zoom.
Referenced by CoreConfig.Apply(), CoreConfig.ApplyZoom(), Core.OnChangeResolution(), RefreshAll(), and ZoneInspector.RefreshScreen().
RefreshSky()
void BaseGameScreen.RefreshSky () inline
Definition at line 587 of file BaseGameScreen.cs.
    {
        CoreConfig.GraphicSetting graphic = EMono.core.config.graphic;
        bool indoor = EMono._map.config.indoor;
        EMono.scene.firefly.baseParticleCount = graphic.fireflyCount;
        EMono.scene.fireflyNight.baseParticleCount = graphic.fireflyCount * 10;
        EMono.scene.star.baseParticleCount = graphic.starCount;
        EMono.scene.star.gameObject.GetComponent<ParticleSystemRenderer>().enabled = EMono.world.date.IsNight;
        EMono.scene.star.SetActive(IsLocalMap && !indoor);
        EMono.scene.firefly.SetActive(IsLocalMap && graphic.firefly && !indoor);
        EMono.scene.fireflyNight.SetActive(IsLocalMap && graphic.firefly && !indoor);
        if ((bool)overlayShadow && (bool)EMono.scene.profile.matOverlay && this is GameScreen)
        {
            overlayShadow.sharedMaterial.SetFloat("_ShadowStrength", EMono._map.config.shadowStrength * (EMono._zone.IsSnowCovered ? 0.5f : 1f) * EMono.setting.render.shadowStrength);
        }
        RefreshWeather();
        RefreshGrading();
    }
References EMono._map, EMono._zone, Core.config, Map.config, EMono.core, World.date, CoreConfig.GraphicSetting.firefly, Scene.firefly, CoreConfig.GraphicSetting.fireflyCount, Scene.fireflyNight, CoreConfig.graphic, MapConfig.indoor, IsLocalMap, Date.IsNight, Spatial.IsSnowCovered, SceneProfile.matOverlay, overlayShadow, Scene.profile, RefreshGrading(), RefreshWeather(), GameSetting.render, EMono.scene, EMono.setting, GameSetting.RenderSetting.shadowStrength, MapConfig.shadowStrength, Scene.star, CoreConfig.GraphicSetting.starCount, and EMono.world.
Referenced by Scene.OnChangeHour(), RefreshAll(), and Weather.SetCondition().
RefreshTilt()
void BaseGameScreen.RefreshTilt () inline
Definition at line 706 of file BaseGameScreen.cs.
    {
        camSupport.tiltShift.enabled = ((ActionMode.Bird.IsActive || EMono._zone.IsRegion) ? EMono.game.config.tiltRegion : EMono.game.config.tilt);
        camSupport.tiltShift.blurArea = (ActionMode.Bird.IsActive ? 12f : (0.1f * (float)(EMono._zone.IsRegion ? EMono.game.config.tiltPowerRegion : EMono.game.config.tiltPower)));
    }
References EMono._zone, Game.config, EMono.game, Spatial.IsRegion, Game.Config.tilt, Game.Config.tiltPower, Game.Config.tiltPowerRegion, and Game.Config.tiltRegion.
Referenced by AM_Bird.OnActivate(), AM_Bird.OnDeactivate(), RefreshAll(), and Scene.ToggleTilt().
RefreshWeather()
virtual void BaseGameScreen.RefreshWeather () inline virtual
Reimplemented in GameScreenElona.
Definition at line 606 of file BaseGameScreen.cs.
    {
        bool flag = EMono._map.config.indoor || (EMono.pc.IsInActiveZone && (EMono.pc.pos.cell.room?.HasRoof ?? false));
        bool flag2 = EMono.pc.pos.cell.room?.data.atrium ?? false;
        Weather weather = EMono.world.weather;
        Weather.Condition currentCondition = weather.CurrentCondition;
        EMono.scene.filterRain.enabled = !flag && weather.IsRaining && EMono.core.config.graphic.enhanceRain;
        EMono.scene.filterRain.Fade = ((currentCondition == Weather.Condition.RainHeavy) ? 0.4f : 0.3f);
        EMono.scene.rain.enableEmission = !flag && weather.IsRaining;
        ParticleSystem.EmissionModule emission = EMono.scene.rain.emission;
        emission.rateOverTime = ((currentCondition == Weather.Condition.RainHeavy) ? 750 : 200);
        EMono.scene.snow.enableEmission = !flag && currentCondition == Weather.Condition.Snow;
        EMono.scene.ether.enableEmission = !flag && weather.IsEther;
        bool enableEmission = !flag && weather.IsBlossom;
        ParticleSystem[] blossoms = EMono.scene.blossoms;
        for (int i = 0; i < blossoms.Length; i++)
        {
            blossoms[i].enableEmission = enableEmission;
        }
        enableEmission = !flag && currentCondition == Weather.Condition.SnowHeavy && EMono.core.config.graphic.blizzard;
        blossoms = EMono.scene.blizzards;
        for (int i = 0; i < blossoms.Length; i++)
        {
            blossoms[i].enableEmission = enableEmission;
        }
        EMono.scene.transBlizzard.localScale = new Vector3(1f, 1f, 1f);
        bool flag3 = (EMono._zone.IsUnderwater || EMono._map.config.forceGodRay || (EMono.core.config.graphic.godray && !flag && (currentCondition == Weather.Condition.Fine || currentCondition == Weather.Condition.Snow))) && !BuildMenu.Instance;
        EMono.scene.godray.SetActive(flag3, delegate(bool enabled)
        {
            if (!enabled)
            {
                EMono.scene.godray.Clear();
            }
        });
        EMono.scene.godrayDust.SetActive(flag3 && EMono.world.date.IsNight);
        EMono.scene.snow.SetActive(enable: true);
        EMono.scene.rain.SetActive(enable: true);
        EMono.scene.ether.SetActive(enable: true);
        EMono.scene.blossom.SetActive(enable: true);
        Zone zone = EMono._zone;
        if (EMono._zone is Zone_Tent)
        {
            zone = (EMono._zone.parent as Zone) ?? EMono._zone;
        }
        float num = ((zone.lv <= -2 || zone.IsUnderwater) ? 0f : ((zone.lv <= -1) ? 0.3f : ((flag && !flag2) ? 0.6f : 1f)));
        EMono.scene.sfxRain.SetVolume(weather.IsRaining ? num : 0f);
        EMono.scene.sfxSea.SetVolume(EMono._zone.VolumeSea * num);
        EMono.scene.camSupport.grading.profile.fog = EMono.setting.render.fogs[EMono._map.config.fog];
        EMono.scene.camSupport.grading.userFog = ((!EMono._map.config.indoor && flag) ? 0f : 1f);
        float num2 = ((EMono._map.IsIndoor || !EMono.world.weather.IsRaining) ? 0f : ((currentCondition == Weather.Condition.RainHeavy) ? (-0.08f) : (-0.04f)));
        if (EMono._zone.IsSnowCovered)
        {
            num2 += EMono.scene.profile.global.snowBrightness;
        }
        camSupport.grading.sceneBrightness = num2;
        ParticleSystem.MainModule main = EMono.scene.rain.main;
        ParticleSystem.MainModule main2 = EMono.scene.snow.main;
        ParticleSystem.MainModule main3 = EMono.scene.ether.main;
        bool flag5 = (main3.prewarm = false);
        bool prewarm = (main2.prewarm = flag5);
        main.prewarm = prewarm;
        blossoms = EMono.scene.blossoms;
        for (int i = 0; i < blossoms.Length; i++)
        {
            ParticleSystem.MainModule main4 = blossoms[i].main;
            main4.prewarm = false;
        }
        camSupport.grading.SetGrading();
    }
References EMono._map, EMono._zone, AreaData.atrium, CoreConfig.GraphicSetting.blizzard, Scene.blizzards, Scene.blossom, Scene.blossoms, camSupport, Point.cell, Core.config, Map.config, EMono.core, Weather.CurrentCondition, BaseArea.data, World.date, CoreConfig.GraphicSetting.enhanceRain, Scene.ether, MapConfig.fog, GameSetting.RenderSetting.fogs, SceneProfile.global, Scene.godray, Scene.godrayDust, CameraSupport.grading, CoreConfig.graphic, Room.HasRoof, BuildMenu.Instance, Weather.IsBlossom, Weather.IsEther, Date.IsNight, Weather.IsRaining, Spatial.IsSnowCovered, Zone.IsUnderwater, Spatial.lv, EMono.pc, Card.pos, Scene.profile, Scene.rain, GameSetting.render, Cell.room, EMono.scene, EMono.setting, Scene.sfxRain, Scene.sfxSea, Scene.snow, Spatial.VolumeSea, World.weather, and EMono.world.
Referenced by BaseTileMap.Draw(), TileMapElona.Draw(), Religion.JoinFaith(), and RefreshSky().
ScrollAxis()
void BaseGameScreen.ScrollAxis (Vector3 axis, bool direct = false) inline
Definition at line 722 of file BaseGameScreen.cs.
    {
        if (direct)
        {
            position += axis;
        }
        else
        {
            position += axis * Core.delta * camSpeed2 * EMono.core.config.camera.senseKeyboard / Zoom;
        }
    }
References camSpeed2, position, and Zoom.
Referenced by ActionMode.InputMovement().
ScrollMouse()
void BaseGameScreen.ScrollMouse (float x, float y) inline
Definition at line 712 of file BaseGameScreen.cs.
    {
        position.x += x / Zoom;
        position.y += y / Zoom;
        if (x > 0.1f || x < -0.1f || y > 0.1f || y < 0.1f)
        {
            RefreshPosition();
        }
    }
References RefreshPosition(), and Zoom.
Referenced by ActionMode.InputMovement().
SetTargetZoomIndex()
void BaseGameScreen.SetTargetZoomIndex (int index) inline
Definition at line 848 of file BaseGameScreen.cs.
    {
        targetZoomIndex = index;
        float num = targetZoom;
        targetZoom = EMono.core.config.camera.zooms[targetZoomIndex];
        if (num != targetZoom)
        {
            zoomTimer = 0f;
        }
    }
References CoreConfig.camera, Core.config, EMono.core, targetZoom, targetZoomIndex, CoreConfig.CameraConfig.zooms, and zoomTimer.
Referenced by ModTargetZoomIndex(), AM_Bird.OnActivate(), and AM_Bird.OnDeactivate().
SetUnitSize()
virtual void BaseGameScreen.SetUnitSize () inline virtual
Reimplemented in GameScreen, and GameScreenElona.
Definition at line 262 of file BaseGameScreen.cs.
    {
    }
Referenced by Activate().
SetZoom()
void BaseGameScreen.SetZoom (float z) inline
Definition at line 841 of file BaseGameScreen.cs.
    {
        targetZoom = (Zoom = z);
        EMono.core.config.ApplyZoom(targetZoom);
        zoomTimer = 0f;
    }
References CoreConfig.ApplyZoom(), Core.config, EMono.core, targetZoom, Zoom, and zoomTimer.
Referenced by Scene.Init(), LayerTravel.OnInit(), LayerTravel.OnKill(), and ZoneInspector.RefreshScreen().
SnapScreen()
void BaseGameScreen.SnapScreen (ref Vector3 v, float zoom) inline
Definition at line 786 of file BaseGameScreen.cs.
    {
        float num = snapSize.x / zoom;
        float num2 = snapSize.y / zoom;
        switch (EMono.core.config.fix.snapType)
        {
        case CoreConfig.ScreenSnapType.Default:
            v.x = num * (float)Mathf.RoundToInt(v.x / num);
            v.y = num2 * (float)Mathf.RoundToInt(v.y / num2);
            break;
        case CoreConfig.ScreenSnapType.Floor:
            v.x = num * (float)Mathf.FloorToInt(v.x / num);
            v.y = num2 * (float)Mathf.FloorToInt(v.y / num2);
            break;
        case CoreConfig.ScreenSnapType.Ceil:
            v.x = num * (float)Mathf.CeilToInt(v.x / num);
            v.y = num2 * (float)Mathf.CeilToInt(v.y / num2);
            break;
        case CoreConfig.ScreenSnapType.Hack3:
            num = snapSize.x;
            num2 = snapSize.y;
            v.x = num * (float)Mathf.RoundToInt(v.x / num);
            v.y = num2 * (float)Mathf.RoundToInt(v.y / num2);
            break;
        case CoreConfig.ScreenSnapType.Hack4:
            num = snapSize.x;
            num2 = snapSize.y;
            v.x = num * (float)Mathf.FloorToInt(v.x / num);
            v.y = num2 * (float)Mathf.FloorToInt(v.y / num2);
            break;
        case CoreConfig.ScreenSnapType.Hack5:
            num = snapSize.x;
            num2 = snapSize.y;
            v.x = num * (float)Mathf.CeilToInt(v.x / num);
            v.y = num2 * (float)Mathf.CeilToInt(v.y / num2);
            break;
        case CoreConfig.ScreenSnapType.Hack6:
            v.x = 0.01f * (float)Mathf.FloorToInt(v.x * 100f) + 0.001f;
            v.y = 0.01f * (float)Mathf.FloorToInt(v.y * 100f) + 0.001f;
            break;
        case CoreConfig.ScreenSnapType.Hack7:
            v.x = 0.01f * (float)Mathf.FloorToInt(v.x * 100f) - 0.001f;
            v.y = 0.01f * (float)Mathf.FloorToInt(v.y * 100f) - 0.001f;
            break;
        case CoreConfig.ScreenSnapType.Hack8:
            v.x = 0.01f * (float)Mathf.RoundToInt(v.x * 100f) + 0.005f;
            v.y = 0.01f * (float)Mathf.RoundToInt(v.y * 100f) + 0.005f;
            break;
        case CoreConfig.ScreenSnapType.Hack9:
            v.x = 0.01f * (float)Mathf.RoundToInt(v.x * 100f) + 0.025f;
            v.y = 0.01f * (float)Mathf.RoundToInt(v.y * 100f) + 0.025f;
            break;
        }
    }
References Core.config, EMono.core, CoreConfig.fix, snapSize, and CoreConfig.Fix.snapType.
Referenced by RefreshPosition(), and GameScreenElona.RefreshPosition().
UpdateShaders()
void BaseGameScreen.UpdateShaders (float time = 0f) inline
Definition at line 348 of file BaseGameScreen.cs.
    {
        SceneProfile profile = EMono.scene.profile;
        SceneColorProfile color = profile.color;
        SceneLightProfile light = profile.light;
        Color value = color.fog.Evaluate(time);
        float value2 = light.nightRatioCurve.Evaluate(time);
        Shader.SetGlobalFloat(_Snow, EMono._zone.IsSnowCovered ? 1f : 0f);
        Shader.SetGlobalFloat(_BackDrawPower, (!ActionMode.Cinema.IsActive) ? EMono.game.config.backDrawAlpha : 0);
        Shader.SetGlobalFloat(_SkyLevel, SkyRate);
        Shader.SetGlobalFloat(_NightRate, value2);
        Shader.SetGlobalFloat(_ViewHeight, ViewHeight);
        Shader.SetGlobalFloat(_FogStrength, value.a * 0.1f);
        Shader.SetGlobalColor(_FogColor, value);
        FowProfile fowProfile = EMono._zone.biome.fowProfile;
        if ((bool)EMono._map.fowProfile)
        {
            fowProfile = EMono._map.fowProfile;
        }
        if ((bool)fowProfile)
        {
            switch (fowProfile.type)
            {
            case FOWType.Color:
                Shader.SetGlobalColor(_FowColor, fowProfile.color);
                break;
            case FOWType.ColorAdd:
                Shader.SetGlobalColor(_FowColor, fowProfile.color * color.fow.Evaluate(time));
                break;
            default:
                Shader.SetGlobalColor(_FowColor, color.fow.Evaluate(time));
                break;
            }
        }
        else
        {
            Shader.SetGlobalColor(_FowColor, color.fow.Evaluate(time));
        }
        Shader.SetGlobalColor(_SunColor, EMono._zone.IsSnowCovered ? color.sunSnow.Evaluate(time) : color.sun.Evaluate(time));
        Shader.SetGlobalColor(_SeaColor, color.sea.Evaluate(time));
        Shader.SetGlobalColor(_SkyColor, color.sky.Evaluate(time));
        Shader.SetGlobalColor(_SkyBGColor, color.skyBG.Evaluate(time));
        Shader.SetGlobalVector(_Offset, EMono.core.config.camera.extendZoomMin ? (position * 0.3f) : (position * 0.5f));
        Shader.SetGlobalFloat(_Zoom, Zoom);
        Shader.SetGlobalFloat(_LightPower, light.lightPower.Evaluate(time) * light.lightPowerMod);
        Shader.SetGlobalFloat(_AnimeSpeedGlobal, EMono.game.config.animeSpeed);
        Shader.SetGlobalColor(_ScreenFlash, ScreenFlash.currentColor);
        ParticleSystem.MainModule main = EMono.scene.godray.main;
        main.startColor = (EMono._zone.IsSnowCovered ? color.godraySnow.Evaluate(time) : color.godray.Evaluate(time));
        camSupport.grading.vignettePower = light.vignetteCurve.Evaluate(time);
        camSupport.grading.UpdateVignette();
        camSupport.bloom.threshold = light.bloomCurve.Evaluate(time);
        camSupport.beautify.bloomIntensity = light.bloomCurve2.Evaluate(time);
    }
References _AnimeSpeedGlobal, _BackDrawPower, _FogColor, _FogStrength, _FowColor, _LightPower, EMono._map, _NightRate, _Offset, _ScreenFlash, _SeaColor, _SkyBGColor, _SkyColor, _SkyLevel, _Snow, _SunColor, _ViewHeight, EMono._zone, _Zoom, Game.Config.animeSpeed, Game.Config.backDrawAlpha, Zone.biome, SceneLightProfile.bloomCurve, SceneLightProfile.bloomCurve2, CoreConfig.camera, camSupport, ActionMode.Cinema, FowProfile.color, Color, SceneProfile.color, Core.config, Game.config, EMono.core, ScreenFlash.currentColor, CoreConfig.CameraConfig.extendZoomMin, SceneColorProfile.fog, SceneColorProfile.fow, BiomeProfile.fowProfile, Map.fowProfile, EMono.game, Scene.godray, SceneColorProfile.godray, SceneColorProfile.godraySnow, CameraSupport.grading, ActionMode.IsActive, Spatial.IsSnowCovered, SceneProfile.light, SceneLightProfile.lightPower, SceneLightProfile.lightPowerMod, SceneLightProfile.nightRatioCurve, position, Scene.profile, EMono.scene, SceneColorProfile.sea, SceneColorProfile.sky, SceneColorProfile.skyBG, SkyRate, SceneColorProfile.sun, SceneColorProfile.sunSnow, FowProfile.type, ViewHeight, SceneLightProfile.vignetteCurve, and Zoom.
Referenced by Draw(), Scene.OnUpdate(), and LayerTreasureMap.SetMap().
Member Data Documentation
_AnimeSpeedGlobal
readonly int BaseGameScreen._AnimeSpeedGlobal = Shader.PropertyToID("_AnimeSpeedGlobal") private
Definition at line 47 of file BaseGameScreen.cs.
Referenced by UpdateShaders().
_BackDrawPower
readonly int BaseGameScreen._BackDrawPower = Shader.PropertyToID("_BackDrawPower") private
Definition at line 17 of file BaseGameScreen.cs.
Referenced by UpdateShaders().
_camPos
Vector3 BaseGameScreen._camPos private
Definition at line 161 of file BaseGameScreen.cs.
Referenced by RefreshPosition().
_FogColor
readonly int BaseGameScreen._FogColor = Shader.PropertyToID("_FogColor") private
Definition at line 29 of file BaseGameScreen.cs.
Referenced by UpdateShaders().
_FogStrength
readonly int BaseGameScreen._FogStrength = Shader.PropertyToID("_FogStrength") private
Definition at line 27 of file BaseGameScreen.cs.
Referenced by UpdateShaders().
_FowColor
readonly int BaseGameScreen._FowColor = Shader.PropertyToID("_FowColor") private
Definition at line 31 of file BaseGameScreen.cs.
Referenced by UpdateShaders().
_LightPower
readonly int BaseGameScreen._LightPower = Shader.PropertyToID("_LightPower") private
Definition at line 45 of file BaseGameScreen.cs.
Referenced by UpdateShaders().
_NightRate
readonly int BaseGameScreen._NightRate = Shader.PropertyToID("_NightRate") private
Definition at line 23 of file BaseGameScreen.cs.
Referenced by UpdateShaders().
_Offset
readonly int BaseGameScreen._Offset = Shader.PropertyToID("_Offset") private
Definition at line 41 of file BaseGameScreen.cs.
Referenced by UpdateShaders().
_randomPoint
Point BaseGameScreen._randomPoint = new Point() private
Definition at line 163 of file BaseGameScreen.cs.
Referenced by GetRandomPoint().
_ScreenFlash
readonly int BaseGameScreen._ScreenFlash = Shader.PropertyToID("_ScreenFlash") private
Definition at line 49 of file BaseGameScreen.cs.
Referenced by UpdateShaders().
_SeaColor
readonly int BaseGameScreen._SeaColor = Shader.PropertyToID("_SeaColor") private
Definition at line 35 of file BaseGameScreen.cs.
Referenced by UpdateShaders().
_SkyBGColor
readonly int BaseGameScreen._SkyBGColor = Shader.PropertyToID("_SkyBGColor") private
Definition at line 39 of file BaseGameScreen.cs.
Referenced by UpdateShaders().
_SkyColor
readonly int BaseGameScreen._SkyColor = Shader.PropertyToID("_SkyColor") private
Definition at line 37 of file BaseGameScreen.cs.
Referenced by UpdateShaders().
_SkyLevel
readonly int BaseGameScreen._SkyLevel = Shader.PropertyToID("_SkyLevel") private
Definition at line 21 of file BaseGameScreen.cs.
Referenced by UpdateShaders().
_Snow
readonly int BaseGameScreen._Snow = Shader.PropertyToID("_Snow") private
Definition at line 19 of file BaseGameScreen.cs.
Referenced by UpdateShaders().
_SunColor
readonly int BaseGameScreen._SunColor = Shader.PropertyToID("_SunColor") private
Definition at line 33 of file BaseGameScreen.cs.
Referenced by UpdateShaders().
_ViewHeight
readonly int BaseGameScreen._ViewHeight = Shader.PropertyToID("_ViewHeight") private
Definition at line 25 of file BaseGameScreen.cs.
Referenced by UpdateShaders().
_Zoom
readonly int BaseGameScreen._Zoom = Shader.PropertyToID("_Zoom") private
Definition at line 43 of file BaseGameScreen.cs.
Referenced by UpdateShaders().
camPos
Vector3 BaseGameScreen.camPos protected
Definition at line 141 of file BaseGameScreen.cs.
Referenced by RefreshPosition(), and GameScreenElona.RefreshPosition().
camSpeed2
float BaseGameScreen.camSpeed2
Definition at line 53 of file BaseGameScreen.cs.
Referenced by ScrollAxis().
focusFix
Vector3 BaseGameScreen.focusFix
Definition at line 71 of file BaseGameScreen.cs.
Referenced by Draw(), RefreshPosition(), and GameScreenElona.RefreshPosition().
focusOption
FocusOption BaseGameScreen.focusOption
Definition at line 133 of file BaseGameScreen.cs.
Referenced by Draw(), and RefreshPosition().
focusPos
Vector3? BaseGameScreen.focusPos
Definition at line 136 of file BaseGameScreen.cs.
Referenced by Draw(), FocusImmediate(), FocusPC(), and RefreshPosition().
focusSpeed
float BaseGameScreen.focusSpeed
Definition at line 96 of file BaseGameScreen.cs.
Referenced by RefreshPosition(), and GameScreenElona.RefreshPosition().
focusSpeedSlow
float BaseGameScreen.focusSpeedSlow
Definition at line 99 of file BaseGameScreen.cs.
Referenced by RefreshPosition().
focusSpeedSlow2
float BaseGameScreen.focusSpeedSlow2
Definition at line 102 of file BaseGameScreen.cs.
forcePrecision
float BaseGameScreen.forcePrecision
Definition at line 127 of file BaseGameScreen.cs.
grid
Grid BaseGameScreen.grid
Definition at line 120 of file BaseGameScreen.cs.
Referenced by BaseTileMap.Draw(), and AM_Cinema.OnUpdateInput().
guide
ScreenGuide BaseGameScreen.guide
Definition at line 118 of file BaseGameScreen.cs.
Referenced by UIInspector.DrawHighlight(), TaskMine.DrawMarker(), Scene.DrawPass(), BaseTileMap.DrawTile(), ScreenGuide.DrawWall(), ActionMode.GetGuidePass(), AM_BaseTerrain.GetGuidePass(), AM_Build.GetGuidePass(), AM_Deconstruct.GetGuidePass(), AM_Mine.GetGuidePass(), AM_MoveInstalled.GetGuidePass(), AM_RemoveDesignation.GetGuidePass(), Core.OnEndOfFrame(), Recipe.OnRenderMarker(), ActionMode.OnRenderTile(), AM_Adv.OnRenderTile(), AM_Build.OnRenderTile(), AM_Mine.OnRenderTile(), AM_MoveInstalled.OnRenderTile(), AM_Picker.OnRenderTile(), HotItemHeld.OnRenderTile(), Trait.OnRenderTile(), TraitRoadSign.OnRenderTile(), BaseTileSelector.OnUpdate(), Card.RenderMarker(), and LayerInteraction.Update().
height
int BaseGameScreen.height
Definition at line 106 of file BaseGameScreen.cs.
Referenced by Draw(), BaseTileMap.Draw(), TileMapElona.Draw(), GetRandomPoint(), WidgetMinimap.OnUpdate(), RefreshPosition(), GameScreenElona.RefreshPosition(), and RefreshScreenSize().
heightLight
float BaseGameScreen.heightLight
Definition at line 55 of file BaseGameScreen.cs.
instantFocus
bool BaseGameScreen.instantFocus
Definition at line 166 of file BaseGameScreen.cs.
Referenced by Draw(), FocusImmediate(), FocusPC(), RefreshPosition(), and GameScreenElona.RefreshPosition().
isCameraMoving
bool BaseGameScreen.isCameraMoving
Definition at line 130 of file BaseGameScreen.cs.
lastPos
Vector3 BaseGameScreen.lastPos
Definition at line 85 of file BaseGameScreen.cs.
Referenced by RefreshPosition(), and GameScreenElona.RefreshPosition().
mapLimit
Rect BaseGameScreen.mapLimit
Definition at line 87 of file BaseGameScreen.cs.
Referenced by RefreshPosition(), and GameScreenElona.RefreshPosition().
moonLevel
int BaseGameScreen.moonLevel
Definition at line 112 of file BaseGameScreen.cs.
Referenced by GameScreen.OnActivate().
nextMove
float BaseGameScreen.nextMove
Definition at line 93 of file BaseGameScreen.cs.
overlayShadow
MeshRenderer BaseGameScreen.overlayShadow
Definition at line 122 of file BaseGameScreen.cs.
Referenced by Activate(), and RefreshSky().
paddingOffset
Vector2 BaseGameScreen.paddingOffset
Definition at line 83 of file BaseGameScreen.cs.
Referenced by Draw(), RefreshPosition(), and GameScreenElona.RefreshPosition().
paddings
Vector2 BaseGameScreen.paddings
Definition at line 81 of file BaseGameScreen.cs.
Referenced by RefreshScreenSize().
pcOrbit
PCOrbit BaseGameScreen.pcOrbit
Definition at line 124 of file BaseGameScreen.cs.
Referenced by Chara._Move(), GameDate.AdvanceMin(), UIInspector.DrawHighlight(), and Scene.OnChangeHour().
planeAngle
Vector3 BaseGameScreen.planeAngle
Definition at line 77 of file BaseGameScreen.cs.
Referenced by RefreshPosition().
planeSpeed
Vector3 BaseGameScreen.planeSpeed
Definition at line 79 of file BaseGameScreen.cs.
Referenced by GameScreen.OnActivate().
position
Vector3 BaseGameScreen.position
Definition at line 139 of file BaseGameScreen.cs.
Referenced by Draw(), Focus(), WidgetMinimap.OnUpdate(), AM_Cinema.OnUpdateInput(), RefreshPosition(), GameScreenElona.RefreshPosition(), ScrollAxis(), Scene.UpdateCursor(), and UpdateShaders().
pushBack
Vector3 BaseGameScreen.pushBack protected
Definition at line 143 of file BaseGameScreen.cs.
Referenced by RefreshPosition(), and GameScreenElona.RefreshPosition().
pushbackSpeed
float BaseGameScreen.pushbackSpeed
Definition at line 57 of file BaseGameScreen.cs.
Referenced by RefreshPosition(), and GameScreenElona.RefreshPosition().
screenFixX
float BaseGameScreen.screenFixX
Definition at line 145 of file BaseGameScreen.cs.
Referenced by RefreshScreenSize().
screenFixX2
float BaseGameScreen.screenFixX2
Definition at line 147 of file BaseGameScreen.cs.
Referenced by RefreshPosition(), and RefreshScreenSize().
screenFixX3
float BaseGameScreen.screenFixX3
Definition at line 149 of file BaseGameScreen.cs.
Referenced by RefreshScreenSize().
screenFixX4
float BaseGameScreen.screenFixX4
Definition at line 151 of file BaseGameScreen.cs.
Referenced by RefreshPosition().
screenFixY
float BaseGameScreen.screenFixY
Definition at line 153 of file BaseGameScreen.cs.
Referenced by RefreshScreenSize().
screenFixY2
float BaseGameScreen.screenFixY2
Definition at line 155 of file BaseGameScreen.cs.
Referenced by RefreshPosition(), and RefreshScreenSize().
screenFixY3
float BaseGameScreen.screenFixY3
Definition at line 157 of file BaseGameScreen.cs.
Referenced by RefreshScreenSize().
screenFixY4
float BaseGameScreen.screenFixY4
Definition at line 159 of file BaseGameScreen.cs.
Referenced by RefreshPosition().
scrollX
int BaseGameScreen.scrollX
Definition at line 108 of file BaseGameScreen.cs.
Referenced by Draw(), Focus(), RefreshPosition(), and GameScreenElona.RefreshPosition().
scrollY
int BaseGameScreen.scrollY
Definition at line 110 of file BaseGameScreen.cs.
Referenced by Draw(), Focus(), RefreshPosition(), and GameScreenElona.RefreshPosition().
SharpenAmount
float BaseGameScreen.SharpenAmount
Definition at line 51 of file BaseGameScreen.cs.
snapSize
Vector2 BaseGameScreen.snapSize
Definition at line 59 of file BaseGameScreen.cs.
Referenced by SnapScreen().
targetZoom
float BaseGameScreen.targetZoom = 0.5f
Definition at line 170 of file BaseGameScreen.cs.
Referenced by Draw(), RefreshPosition(), GameScreenElona.RefreshPosition(), SetTargetZoomIndex(), and SetZoom().
targetZoomIndex
int BaseGameScreen.targetZoomIndex
Definition at line 168 of file BaseGameScreen.cs.
Referenced by ModTargetZoomIndex(), RefreshPosition(), and SetTargetZoomIndex().
tileAlign
Vector2 BaseGameScreen.tileAlign
Definition at line 63 of file BaseGameScreen.cs.
Referenced by BaseTileMap.Draw(), BaseTileMap.DrawRoof(), BaseTileMap.DrawTile(), TileMapElona.DrawTile(), EloMapActor.Initialize(), Point.Position(), Point.PositionTopdown(), Point.PositionTopdownTreasure(), GameScreenElona.RefreshPosition(), Point.Set(), GameScreen.SetUnitSize(), and GameScreenElona.SetUnitSize().
tileMap
BaseTileMap BaseGameScreen.tileMap
Definition at line 114 of file BaseGameScreen.cs.
Referenced by Effect._Play(), Activate(), RefractionProfile.Apply(), PostEffectProfile.Apply(), LiquidProfile.Apply(), Scene.ApplyZoneConfig(), Core.Awake(), Draw(), RenderDataHalfBlock.Draw(), CardRenderer.Draw(), UIInspector.DrawHighlight(), TaskDesignation.DrawMarker(), RenderData.DrawRepeatTo(), TileTypeWallHang.GetMountHeight(), RenderRow.GetRenderParam(), TextureManager.Init(), AM_Adv.OnActivate(), CardActor.OnRender(), Recipe.OnRenderMarker(), GrowSystem.OnRenderTileMap(), EffectIRenderer.OnUpdate(), Point.Position(), Point.PositionTopdown(), LayerEditHouse.RefreshBlockList(), Card.RenderMarker(), LayerEditHouse.SetBoard(), Card.SetFreePos(), Core.Update(), GameUpdater.Update(), CoreDebug.UpdateAlways(), and WidgetDebug.UpdateText().
tileOffsetHeight
Vector3 BaseGameScreen.tileOffsetHeight
Definition at line 73 of file BaseGameScreen.cs.
tileSelector
BaseTileSelector BaseGameScreen.tileSelector
Definition at line 116 of file BaseGameScreen.cs.
Referenced by AM_Sim._OnUpdateInput(), HitSummary.CanExecute(), ActionMode.GetHintText(), DropdownRecipe.GetLabel(), AM_Build.InputWheel(), BaseTileMap.OnActivate(), ActionMode.OnRenderTile(), AM_Build.OnRenderTile(), AM_Region.OnRenderTile(), Scene.OnUpdate(), ButtonGrid.SetIngredient(), ActionMode.ShowLayer(), BaseTileSelector.TryProcessTiles(), and LayerInteraction.Update().
tileSize
Vector2 BaseGameScreen.tileSize
Definition at line 61 of file BaseGameScreen.cs.
Referenced by GameScreen.SetUnitSize(), and GameScreenElona.SetUnitSize().
tileViewSize
Vector2 BaseGameScreen.tileViewSize
Definition at line 67 of file BaseGameScreen.cs.
Referenced by GameScreen.SetUnitSize(), and GameScreenElona.SetUnitSize().
tileWeight
Vector3 BaseGameScreen.tileWeight
Definition at line 69 of file BaseGameScreen.cs.
Referenced by BaseTileMap.Draw(), BaseTileMap.DrawRoof(), BaseTileMap.DrawTile(), TileMapElona.DrawTile(), Point.Position(), and BaseTileMap.SetRoofHeight().
tileWeightHeight
Vector3 BaseGameScreen.tileWeightHeight
Definition at line 75 of file BaseGameScreen.cs.
tileWorldSize
Vector2 BaseGameScreen.tileWorldSize
Definition at line 65 of file BaseGameScreen.cs.
Referenced by Draw(), RefreshPosition(), GameScreenElona.RefreshPosition(), GameScreen.SetUnitSize(), and GameScreenElona.SetUnitSize().
width
int BaseGameScreen.width
Definition at line 104 of file BaseGameScreen.cs.
Referenced by Draw(), BaseTileMap.Draw(), TileMapElona.Draw(), GetRandomPoint(), WidgetMinimap.OnUpdate(), RefreshPosition(), GameScreenElona.RefreshPosition(), and RefreshScreenSize().
Zoom
float BaseGameScreen.Zoom
Definition at line 90 of file BaseGameScreen.cs.
Referenced by Draw(), TCUI.DrawImmediate(), AM_Adv.OnAfterUpdate(), TCUI.OnDraw(), AM_Adv.OnUpdateCursor(), AM_Paint.OnUpdateInput(), Point.PlaySound(), TCOrbitTask.Refresh(), RefreshPosition(), GameScreenElona.RefreshPosition(), RefreshScreenSize(), ScrollAxis(), ScrollMouse(), UISong.SetSong(), SetZoom(), and UpdateShaders().
zoomPos
Vector3 BaseGameScreen.zoomPos
Definition at line 174 of file BaseGameScreen.cs.
Referenced by Draw(), and ModTargetZoomIndex().
zoomTimer
float BaseGameScreen.zoomTimer
Definition at line 172 of file BaseGameScreen.cs.
Referenced by Draw(), SetTargetZoomIndex(), and SetZoom().
Property Documentation
camSupport
CameraSupport BaseGameScreen.camSupport get protected
Definition at line 180 of file BaseGameScreen.cs.
Referenced by RefreshAll(), RefreshGrading(), RefreshScreenSize(), RefreshWeather(), and UpdateShaders().
fixFocus
bool BaseGameScreen.fixFocus get
Definition at line 176 of file BaseGameScreen.cs.
Referenced by Draw(), and RefreshPosition().
IsGameScreen
virtual bool BaseGameScreen.IsGameScreen get
Definition at line 188 of file BaseGameScreen.cs.
Referenced by Activate(), and Draw().
IsLocalMap
virtual bool BaseGameScreen.IsLocalMap get
Definition at line 190 of file BaseGameScreen.cs.
Referenced by Activate(), and RefreshSky().
SkyRate
virtual float BaseGameScreen.SkyRate get
Definition at line 184 of file BaseGameScreen.cs.
Referenced by UpdateShaders().
TargetZoom
virtual float BaseGameScreen.TargetZoom get
Definition at line 178 of file BaseGameScreen.cs.
Referenced by Draw(), Scene.Init(), LayerTravel.OnInit(), LayerTravel.OnKill(), and RefreshPosition().
transFocus
Transform BaseGameScreen.transFocus get protected
Definition at line 182 of file BaseGameScreen.cs.
Referenced by Draw(), and RefreshPosition().
ViewHeight
virtual float BaseGameScreen.ViewHeight get
Definition at line 186 of file BaseGameScreen.cs.
Referenced by UpdateShaders().
The documentation for this class was generated from the following file:
Elin/BaseGameScreen.cs