Elin Decompiled Documentation: SpriteSheet Class Reference
SpriteSheet Class Reference
Static Public Member Functions
static void Add (Sprite sprite)
static void Add (string path)
static Sprite Get (string id)
static Sprite Get (string path, string id)
Static Public Attributes
static Dictionary< string, Sprite > dict = new Dictionary<string, Sprite>()
static HashSet< string > loadedPath = new HashSet<string>()
Detailed Description
Definition at line 4 of file SpriteSheet.cs.
Member Function Documentation
Add() [1/2]
static void SpriteSheet.Add (Sprite sprite) inline static
Definition at line 10 of file SpriteSheet.cs.
    {
        dict[sprite.name] = sprite;
    }
References dict.
Referenced by Get(), Hoard.GetSprite(), and Core.Init().
Add() [2/2]
static void SpriteSheet.Add (string path) inline static
Definition at line 15 of file SpriteSheet.cs.
    {
        if (!loadedPath.Contains(path))
        {
            Sprite[] array = Resources.LoadAll<Sprite>(path);
            foreach (Sprite sprite in array)
            {
                dict[sprite.name] = sprite;
            }
            loadedPath.Add(path);
        }
    }
References dict, and loadedPath.
Get() [1/2]
static Sprite SpriteSheet.Get (string id) inline static
Definition at line 28 of file SpriteSheet.cs.
    {
        return dict.TryGetValue(id);
    }
References dict.
Referenced by WidgetMenuPanel.AddButton(), WidgetInspector.AddButton(), Element.GetIcon(), Feat.GetIcon(), LandFeat.GetIcon(), RaceBonus.GetIcon(), Resistance.GetIcon(), BaseStats.GetSprite(), UIButton.Item.GetSprite(), SourceElement.Row.GetSprite(), HotItemToggleVisible.GetSprite(), RenderRow.GetSprite(), Hoard.GetSprite(), Scene.InitPass(), LayerQuickMenu.OnInit(), InvOwner.OnWriteNote(), UIInspector.Refresh(), LayerDragGrid.RefreshCost(), WindowCharaMini.RefreshEquipment(), WindowChara.RefreshEquipment(), UIInventory.RefreshList(), ButtonGrid.SetArea(), ButtonGrid.SetBodySlot(), Person.SetImage(), TCText.ShowEmo(), and LayerInteraction.ShowPage().
Get() [2/2]
static Sprite SpriteSheet.Get (string path, string id) inline static
Definition at line 33 of file SpriteSheet.cs.
    {
        if (!loadedPath.Contains(path))
        {
            Add(path);
        }
        dict.TryGetValue(id, out var value);
        return value;
    }
References Add(), dict, and loadedPath.
Member Data Documentation
dict
Dictionary<string, Sprite> SpriteSheet.dict = new Dictionary<string, Sprite>() static
Definition at line 6 of file SpriteSheet.cs.
Referenced by Add(), Core.Awake(), Get(), and Scene.InitPass().
loadedPath
HashSet<string> SpriteSheet.loadedPath = new HashSet<string>() static
Definition at line 8 of file SpriteSheet.cs.
Referenced by Add(), Core.Awake(), and Get().
The documentation for this class was generated from the following file:
Elin/Plugins.basecore/SpriteSheet.cs