Elin Decompiled Documentation: QuestDeliver Class Reference
QuestDeliver Class Reference
Public Member Functions
override int GetExtraMoney ()
override void OnInit ()
virtual int GetDestNum ()
virtual void SetIdThing ()
override void OnStart ()
virtual bool IsDestThing (Thing t)
List< Thing > ListDestThing (bool onlyFirst=false)
override Thing GetDestThing ()
override bool IsDeliverTarget (Chara c)
override bool CanDeliverToClient (Chara c)
override bool CanDeliverToBox (Thing t)
override bool Deliver (Chara c, Thing t=null)
virtual int GetBonus (Thing t)
override string GetTextProgress ()
override void OnEnterZone ()
Public Member Functions inherited from QuestDestZone
void SetDest (Zone z, int target)
Public Member Functions inherited from QuestRandom
override void OnDropReward ()
Public Member Functions inherited from Quest
virtual Thing GetDestThing ()
virtual int GetExtraMoney ()
virtual int GetRewardPlat (int money)
override bool Equals (object obj)
virtual bool IsVisibleOnQuestBoard ()
virtual bool CanStartQuest ()
virtual bool CanUpdateOnTalk (Chara c)
virtual Zone CreateInstanceZone (Chara c)
virtual bool UpdateOnTalk ()
void Init ()
virtual void OnInit ()
Quest SetClient (Chara c, bool assignQuest=true)
void SetTask (QuestTask _task)
void Start ()
virtual void OnStart ()
virtual void OnEnterZone ()
virtual void OnClickQuest ()
void Fail ()
virtual void OnFail ()
virtual void ShowCompleteText ()
void Complete ()
virtual void OnBeforeComplete ()
virtual void OnDropReward ()
Thing DropReward (string id)
Thing DropReward (Thing t)
virtual void OnComplete ()
void CompleteTask ()
virtual void OnCompleteTask ()
virtual void OnGiveItem (Chara c, Thing t)
virtual void OnKillChara (Chara c)
virtual void OnModKarma (int a)
void NextPhase ()
void ChangePhase (int a)
virtual void OnChangePhase (int a)
string Parse (string s)
virtual string GetTitle ()
virtual string GetTrackerText ()
virtual string GetDetail (bool onJournal=false)
virtual string GetDetailText (bool onJournal=false)
virtual string GetTextProgress ()
string GetRewardText ()
virtual string GetTalkProgress ()
virtual string GetTalkComplete ()
void UpdateJournal ()
virtual bool IsDeliverTarget (Chara c)
virtual bool CanDeliverToClient (Chara c)
virtual bool CanDeliverToBox (Thing t)
virtual bool Deliver (Chara c, Thing t=null)
Public Attributes
string idThing
int num
Public Attributes inherited from QuestDestZone
int uidDest
int uidTarget
Public Attributes inherited from Quest
string id
int uid
int uidClientZone
int phase
int lv
int deadline
int difficulty
int rewardMoney
int bonusMoney
int startDate
int dangerLv
bool isNew
bool isComplete
bool track
Person person
QuestTask task
RefChara refChara = new RefChara()
Properties
virtual bool ConsumeGoods [get]
SourceThing.Row sourceThing [get]
override string NameDeliver [get]
override string RefDrama2 [get]
override int KarmaOnFail [get]
override DifficultyType difficultyType [get]
override bool ForbidTeleport [get]
Properties inherited from QuestDestZone
virtual bool IsDeliver [get]
Zone DestZone [get]
override Chara DestChara [get]
override string??? RefDrama3 [get]
override string??? RefDrama4 [get]
Properties inherited from QuestRandom
override bool CanAutoAdvance [get]
override bool IsRandomQuest [get]
override int RangeDeadLine [get]
override int KarmaOnFail [get]
override int FameOnComplete [get]
override string RefDrama1 [get]
Properties inherited from Quest
Zone ClientZone [get]
Chara chara [get]
virtual SourceQuest.Row source [get]
bool Confetti [get]
bool IsExpired [get]
int Hours [get]
string TextDeadline [get]
virtual bool HasDLC [get]
virtual string idSource [get]
virtual string RewardSuffix [get]
virtual bool FameContent [get]
virtual string TextExtra [get]
virtual string TextExtra2 [get]
virtual int DangerLv [get]
virtual int AffinityGain [get]
virtual int BaseMoney [get]
virtual int KarmaOnFail [get]
virtual bool CanAbandon [get]
virtual int FameOnComplete [get]
virtual int RangeDeadLine [get]
virtual bool UseInstanceZone [get]
virtual bool ForbidTeleport [get]
virtual bool TrackOnStart [get]
virtual bool RequireClientInSameZone [get]
virtual DifficultyType difficultyType [get]
virtual Chara DestChara [get]
virtual string RefDrama1 [get]
virtual string RefDrama2 [get]
virtual string RefDrama3 [get]
virtual string RefDrama4 [get]
virtual string TitlePrefix [get]
virtual bool CanAutoAdvance [get]
virtual bool IsRandomQuest [get]
virtual string NameDeliver [get]
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Private Member Functions
SourceCategory.Row GetDeliverCat ()
Static Private Attributes
static List< SourceCategory.Row > _listDeliver = new List<SourceCategory.Row>()
Additional Inherited Members
Public Types inherited from Quest
enum DifficultyType {
Default , Deliver , Supply , Escort ,
Bulk , Meal , Farm , Music
}
enum SubReward { plat , gacha_coin , money2 , ticket_furniture }
Static Public Member Functions inherited from Quest
static Quest Create (string _id, string _idPerson=null, Chara c=null)
static List< Zone > ListDeliver ()
Static Public Member Functions inherited from EClass
static int rndSeed (int a, int seed)
static int rnd (int a)
static int curve (int a, int start, int step, int rate=75)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Static Public Attributes inherited from Quest
const int PhaseComplete = 999
Static Public Attributes inherited from EClass
static Core core
Detailed Description
Definition at line 5 of file QuestDeliver.cs.
Member Function Documentation
CanDeliverToBox()
override bool QuestDeliver.CanDeliverToBox (Thing t) inline virtual
Reimplemented from Quest.
Definition at line 197 of file QuestDeliver.cs.
    {
        return false;
    }
CanDeliverToClient()
override bool QuestDeliver.CanDeliverToClient (Chara c) inline virtual
Reimplemented from Quest.
Definition at line 172 of file QuestDeliver.cs.
    {
        if (GetDestThing() == null && !EClass.debug.autoAdvanceQuest)
        {
            return false;
        }
        if (IsDeliver)
        {
            if (EClass._zone == base.DestZone)
            {
                return c.uid == uidTarget;
            }
            return false;
        }
        if (person.chara?.uid == c.uid)
        {
            return true;
        }
        if (c.quest != null)
        {
            return c.quest.uid == uid;
        }
        return false;
    }
References EClass._zone, CoreDebug.autoAdvanceQuest, Person.chara, EClass.debug, GetDestThing(), QuestDestZone.IsDeliver, Quest.person, Chara.quest, Card.uid, Quest.uid, and QuestDestZone.uidTarget.
Deliver()
override bool QuestDeliver.Deliver (Chara c, Thing t = null) inline virtual
Reimplemented from Quest.
Definition at line 202 of file QuestDeliver.cs.
    {
        if (t == null)
        {
            t = GetDestThing();
            if (t == null && EClass.debug.autoAdvanceQuest)
            {
                Debug.Log("[error] creating " + idThing);
                t = ThingGen.Create(idThing);
            }
        }
        if (t != null)
        {
            Thing thing = t.Split(num);
            bonusMoney += GetBonus(thing);
            Msg.Say("deliverItem", thing);
            if (ConsumeGoods)
            {
                thing.Destroy();
            }
            else
            {
                c.Pick(thing);
            }
            EClass.game.quests.Complete(this);
            c.quest = null;
            return true;
        }
        return false;
    }
References CoreDebug.autoAdvanceQuest, Quest.bonusMoney, QuestManager.Complete(), ConsumeGoods, ThingGen.Create(), EClass.debug, Debug, Card.Destroy(), EClass.game, GetBonus(), GetDestThing(), idThing, num, Chara.Pick(), Game.quests, Msg.Say(), and Card.Split().
GetBonus()
virtual int QuestDeliver.GetBonus (Thing t) inline virtual
Reimplemented in QuestSupply, and QuestSupplySpecific.
Definition at line 233 of file QuestDeliver.cs.
    {
        return 0;
    }
Referenced by Deliver().
GetDeliverCat()
SourceCategory.Row QuestDeliver.GetDeliverCat () inline private
Definition at line 71 of file QuestDeliver.cs.
    {
        if (_listDeliver.Count == 0)
        {
            foreach (SourceCategory.Row row in EClass.sources.categories.rows)
            {
                if (row.deliver > 0)
                {
                    _listDeliver.Add(row);
                }
            }
        }
        return _listDeliver.RandomItem();
    }
References _listDeliver, SourceManager.categories, and EClass.sources.
Referenced by SetIdThing().
GetDestNum()
virtual int QuestDeliver.GetDestNum () inline virtual
Reimplemented in QuestSupplyBulk, and QuestSupplyBulkJunk.
Definition at line 54 of file QuestDeliver.cs.
    {
        return 1;
    }
Referenced by OnInit().
GetDestThing()
override Thing QuestDeliver.GetDestThing () inline virtual
Reimplemented from Quest.
Definition at line 145 of file QuestDeliver.cs.
    {
        List<Thing> list = ListDestThing(onlyFirst: true);
        if (list.Count <= 0)
        {
            return null;
        }
        return list[0];
    }
References ListDestThing().
Referenced by CanDeliverToClient(), Deliver(), GetTextProgress(), QuestSupplyCat.GetTextProgress(), and ItemQuest.SetQuest().
GetExtraMoney()
override int QuestDeliver.GetExtraMoney () inline virtual
Reimplemented from Quest.
Reimplemented in QuestSupplySpecific.
Definition at line 39 of file QuestDeliver.cs.
    {
        if (base.DestZone == null)
        {
            return 0;
        }
        return base.DestZone.Dist(base.ClientZone) * 6;
    }
GetTextProgress()
override string QuestDeliver.GetTextProgress () inline virtual
Reimplemented from Quest.
Reimplemented in QuestSupplyCat.
Definition at line 238 of file QuestDeliver.cs.
    {
        string text = ((GetDestThing() != null) ? "supplyInInv".lang().TagColor(FontColor.Good) : "supplyNotInInv".lang());
        if (IsDeliver)
        {
            string @ref = (base.DestZone.dictCitizen.TryGetValue(uidTarget) ?? "???") + " (" + base.DestZone.Name + ")";
            return "progressDeliver".lang(sourceThing.GetName(num), @ref, text);
        }
        return "progressSupply".lang(sourceThing.GetName(num) + Lang.space + TextExtra2.IsEmpty(""), text);
    }
References GetDestThing(), QuestDestZone.IsDeliver, num, sourceThing, Quest.TextExtra2, and QuestDestZone.uidTarget.
IsDeliverTarget()
override bool QuestDeliver.IsDeliverTarget (Chara c) inline virtual
Reimplemented from Quest.
Definition at line 155 of file QuestDeliver.cs.
    {
        if (IsDeliver)
        {
            if (EClass._zone == base.DestZone)
            {
                return c.uid == uidTarget;
            }
            return false;
        }
        if (c.quest != null)
        {
            return c.quest.uid == uid;
        }
        return false;
    }
References EClass._zone, QuestDestZone.IsDeliver, Chara.quest, Quest.uid, and QuestDestZone.uidTarget.
IsDestThing()
virtual bool QuestDeliver.IsDestThing (Thing t) inline virtual
Reimplemented in QuestSupplyCat.
Definition at line 97 of file QuestDeliver.cs.
    {
        if (t.parentCard != null && !t.parentCard.trait.CanUseContent)
        {
            return false;
        }
        if (!t.c_isImportant && t.Num >= num && t.IsIdentified && (!t.IsContainer || t.things.Count == 0) && !t.isEquipped)
        {
            if (t.id == idThing)
            {
                return true;
            }
            if (t.c_altName.IsEmpty())
            {
                string name = sourceThing.GetName();
                if (t.source.GetName() == name || t.GetName(NameStyle.Simple, 1) == name)
                {
                    return true;
                }
            }
        }
        return false;
    }
References Card.c_altName, Card.c_isImportant, Trait.CanUseContent, Thing.GetName(), Card.id, idThing, Card.IsContainer, Thing.isEquipped, Card.IsIdentified, Card.Num, num, Card.parentCard, Thing.source, sourceThing, Card.things, and Card.trait.
Referenced by ListDestThing().
ListDestThing()
List< Thing > QuestDeliver.ListDestThing (bool onlyFirst = false) inline
Definition at line 121 of file QuestDeliver.cs.
    {
        List<Thing> list = EClass.pc.things.List((Thing t) => IsDestThing(t), onlyAccessible: true);
        if (onlyFirst && list.Count > 0)
        {
            return list;
        }
        if (!IsDeliver && EClass._zone.IsPCFaction)
        {
            foreach (Thing thing in EClass._map.props.stocked.things)
            {
                if (IsDestThing(thing))
                {
                    list.Add(thing);
                    if (onlyFirst)
                    {
                        return list;
                    }
                }
            }
        }
        return list;
    }
References EClass._map, EClass._zone, ActPlan.List.Add(), QuestDestZone.IsDeliver, IsDestThing(), Zone.IsPCFaction, ThingContainer.List(), EClass.pc, Map.props, PropsManager.stocked, Card.things, and Props.things.
Referenced by GetDestThing().
OnEnterZone()
override void QuestDeliver.OnEnterZone () inline virtual
Reimplemented from Quest.
Definition at line 249 of file QuestDeliver.cs.
    {
        if (!IsDeliver || EClass._zone != base.DestZone)
        {
            return;
        }
        Chara chara = EClass._map.charas.Find((Chara c) => c.uid == uidTarget);
        if (chara == null)
        {
            chara = EClass._map.deadCharas.Find((Chara c) => c.uid == uidTarget);
        }
        if (chara == null)
        {
            Msg.Say("deliver_funny");
            Complete();
        }
    }
References EClass._map, EClass._zone, Quest.chara, Map.charas, Quest.Complete(), Map.deadCharas, QuestDestZone.IsDeliver, Msg.Say(), Card.uid, and QuestDestZone.uidTarget.
OnInit()
override void QuestDeliver.OnInit () inline virtual
Reimplemented from Quest.
Definition at line 48 of file QuestDeliver.cs.
    {
        num = GetDestNum();
        SetIdThing();
    }
References GetDestNum(), num, and SetIdThing().
OnStart()
override void QuestDeliver.OnStart () inline virtual
Reimplemented from Quest.
Definition at line 86 of file QuestDeliver.cs.
    {
        if (IsDeliver)
        {
            Thing thing = ThingGen.Create(idThing);
            thing.Identify(show: false, IDTSource.SuperiorIdentify);
            Msg.Say("get_quest_item");
            EClass.pc.Pick(thing);
        }
    }
References ThingGen.Create(), Thing.Identify(), idThing, QuestDestZone.IsDeliver, EClass.pc, Chara.Pick(), and Msg.Say().
SetIdThing()
virtual void QuestDeliver.SetIdThing () inline virtual
Reimplemented in QuestSupplyCat, and QuestSupplySpecific.
Definition at line 59 of file QuestDeliver.cs.
    {
        CardRow cardRow;
        do
        {
            SourceCategory.Row r = GetDeliverCat();
            cardRow = SpawnListThing.Get("cat_" + r.id, (SourceThing.Row s) => EClass.sources.categories.map[s.category].IsChildOf(r.id)).Select();
        }
        while (cardRow == null);
        idThing = cardRow.id;
    }
References SourceManager.categories, SpawnListThing.Get(), GetDeliverCat(), CardRow.id, SourceCategory.Row.id, idThing, SpawnList.Select(), and EClass.sources.
Referenced by OnInit().
Member Data Documentation
_listDeliver
List<SourceCategory.Row> QuestDeliver._listDeliver = new List<SourceCategory.Row>() static private
Definition at line 13 of file QuestDeliver.cs.
Referenced by GetDeliverCat().
idThing
string QuestDeliver.idThing
Definition at line 8 of file QuestDeliver.cs.
Referenced by Deliver(), IsDestThing(), OnStart(), SetIdThing(), and QuestSupplySpecific.SetIdThing().
num
int QuestDeliver.num
Definition at line 11 of file QuestDeliver.cs.
Referenced by Deliver(), QuestSupplySpecific.GetBonus(), QuestSupplySpecific.GetExtraMoney(), GetTextProgress(), IsDestThing(), OnInit(), and QuestSupplySpecific.SetIdThing().
Property Documentation
ConsumeGoods
virtual bool QuestDeliver.ConsumeGoods get
Definition at line 15 of file QuestDeliver.cs.
Referenced by Deliver().
difficultyType
override DifficultyType QuestDeliver.difficultyType get
Definition at line 35 of file QuestDeliver.cs.
ForbidTeleport
override bool QuestDeliver.ForbidTeleport get
Definition at line 37 of file QuestDeliver.cs.
KarmaOnFail
override int QuestDeliver.KarmaOnFail get
Definition at line 23 of file QuestDeliver.cs.
    {
        get
        {
            if (!IsDeliver)
            {
                return base.KarmaOnFail;
            }
            return -15;
        }
    }
NameDeliver
override string QuestDeliver.NameDeliver get
Definition at line 19 of file QuestDeliver.cs.
RefDrama2
override string QuestDeliver.RefDrama2 get
Definition at line 21 of file QuestDeliver.cs.
sourceThing
SourceThing.Row QuestDeliver.sourceThing get
Definition at line 17 of file QuestDeliver.cs.
Referenced by GetTextProgress(), and IsDestThing().
The documentation for this class was generated from the following file:
Elin/QuestDeliver.cs