Elin Decompiled Documentation: LayerDragGrid Class Reference
LayerDragGrid Class Reference
Classes
class PutbackInfo
Public Member Functions
void OnOpen ()
LayerDragGrid SetInv (InvOwnerDraglet owner, bool refuelFromLayerDragGrid=false)
int GetPrice ()
void RefreshCost ()
bool IsAllGridSet ()
override void ClearButtons ()
override void RefreshCurrentGrid ()
override List< Thing > GetTargets ()
void Validate ()
void Redraw ()
void AddPutBack (Thing t, Thing container)
void TryPutBack ()
override void OnEndCraft ()
override void OnKill ()
override void OnUpdateInput ()
override void OnRightClick ()
Public Member Functions inherited from LayerBaseCraft
virtual List< Thing > GetTargets ()
virtual int GetReqIngredient (int index)
virtual void RefreshCurrentGrid ()
virtual void ClearButtons ()
virtual void OnEndCraft ()
Public Member Functions inherited from ELayer
override void OnBeforeAddLayer ()
void InitInspector ()
sealed override void Init ()
override void OnAfterAddLayer ()
void TryShowHelp ()
void AddLayerToUI (string id)
void TryShowHint (string _langHint=null)
void TalkHomeMemeber (string id)
void TalkMaid (string id)
override void OnRightClick ()
Public Member Functions inherited from Layer
virtual string GetTextHeader (Window window)
virtual bool HeaderIsListOf (int id)
virtual void Init ()
virtual void OnInit ()
virtual void OnAfterInit ()
virtual void ApplySkin ()
void ShowScreenLock (string id)
void UpdateInput ()
virtual void OnUpdateInput ()
virtual void OnRightClick ()
virtual bool OnBack ()
virtual void OnChangeLayer ()
virtual void OnCreate ()
void _AddLayer (string id)
Layer AddLayer (string id)
T AddLayer< T > ()
T AddLayer< T > (string id)
T AddLayerDontCloseOthers< T > ()
Layer AddLayerDontCloseOthers (Layer l)
T GetOrAddLayer< T > ()
virtual void OnBeforeAddLayer ()
virtual void OnAfterAddLayer ()
Layer AddLayer (Layer l)
void ToggleLayer (string id)
T ToggleLayer< T > (string id=null)
void WaitAndClose ()
void OnClickClose ()
virtual void Close ()
void CloseLayers ()
void RemoveLayers (bool removeImportant=false)
bool RemoveLayer< T > ()
void RemoveLayer (Layer l)
virtual void OnKill ()
Layer SetOnKill (Action action)
void DisableClose ()
void Delay (float duration=0.05f)
Layer SetDelay (float d)
Layer GetLayer (string id)
T GetLayer< T > (bool fromTop=false)
Layer GetTopLayer ()
void SwitchContent (int idWindow, int i)
virtual void OnSwitchContent (Window window)
Layer SetTitles (string langList, string idHeaderRow=null)
bool IsBlockWidgetClick ()
bool IsHideHud ()
bool IsAllowGeneralInput ()
bool IsUseBlur ()
bool IsPointerOnLayer ()
void ApplySkin ()
Static Public Member Functions
static LayerDragGrid Create (InvOwnerDraglet owner, bool refuelFromLayerDragGrid=false)
static LayerDragGrid CreateChaosOffering (TraitAltarChaos altar)
static LayerDragGrid CreateOffering (TraitAltar altar)
static LayerDragGrid CreateDeliver (InvOwnerDeliver.Mode mode=InvOwnerDeliver.Mode.Default, Card owner=null)
static LayerDragGrid CreateGive (Chara c)
static LayerDragGrid CreateCraft (TraitCrafter crafter)
static LayerDragGrid CreateRecycle (TraitRecycle recycle)
static LayerDragGrid CreateGacha (TraitGacha gacha)
static LayerDragGrid TryProc (Chara cc, InvOwnerEffect owner)
static LayerDragGrid CreateIdentify (Chara cc, bool superior=false, BlessedState state=BlessedState.Normal, int price=0, int count=1)
static LayerDragGrid CreateEnchant (Chara cc, bool armor, bool superior=false, BlessedState state=BlessedState.Normal, int count=1)
static LayerDragGrid CreateChangeMaterial (Chara cc, Thing consume, SourceMaterial.Row mat, EffectId idEffect, BlessedState state=BlessedState.Normal, int price=0, int count=1)
static LayerDragGrid CreateUncurse (Chara cc, BlessedState state=BlessedState.Normal, int price=0, int count=1)
static LayerDragGrid CreateLighten (Chara cc, BlessedState state=BlessedState.Normal, int price=0, int count=1)
static LayerDragGrid CreateReconstruction (Chara cc, BlessedState state=BlessedState.Normal, int price=0, int count=1)
Static Public Member Functions inherited from ELayer
static int rnd (int a)
Static Public Member Functions inherited from Layer
static T Create< T > ()
static T Create< T > (string path)
static Layer Create (string path)
Public Attributes
List< PutbackInfo > putBacks = new List<PutbackInfo>()
UIItem itemCost
Image imageOwner
UIText textTitle
UIText textFuel
Transform transIndex
List< ButtonGrid > buttons
ButtonGrid buttonOwner
UIButton buttonRefuel
UIButton buttonAutoRefuel
UIButton buttonAlly
UIButton buttonStock
InvOwnerDraglet owner
UICurrency uiCurrency
int currentIndex
UIDragGridInfo info
UIList listAlly
UIDragGridIngredients uiIngredients
Public Attributes inherited from Layer
Option option
UnityEvent onKill
Anime animeIn
Anime animeOut
bool closeOthers
bool defaultActionMode = true
Button screenLock
Layer parent
string idLayer
List< Layer > layers = new List<Layer>()
Vector2 lastParentPos
List< Window > windows = new List<Window>()
string langHint
Static Public Attributes
static LayerDragGrid Instance
Static Public Attributes inherited from Layer
static int skipInput
static bool closeOnRightClick
static bool rightClicked
static bool cancelKeyDown
static bool ignoreSounds
static Transform blurStopInstance
static string[] searchPath = new string[3] { "Layer", "Layer/Dialog", "Layer/LayerHome" }
Properties
ButtonGrid CurrentButton [get]
override bool CanCancelAI [get]
override bool RepeatAI [get]
Properties inherited from LayerBaseCraft
virtual bool CanCancelAI [get]
virtual bool RepeatAI [get]
Properties inherited from ELayer
static Core core [get]
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static FactionBranch Branch [get]
static Faction Home [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static CoreConfig config [get]
static GameSetting setting [get]
static ColorProfile Colors [get]
static SourceManager sources [get]
static World world [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
bool IsFloat [get]
virtual string IdHelp [get]
Properties inherited from Layer
Layer TopLayer [get]
string uid [get]
virtual RectTransform rectLayers [get]
virtual bool blockWidgetClick [get]
Private Member Functions
void Update ()
Private Attributes
bool wasInventoryOpen
int lastNum
Additional Inherited Members
Protected Member Functions inherited from ELayer
sealed override void _Close ()
sealed override void Kill ()
Protected Member Functions inherited from Layer
virtual void Awake ()
virtual void _Close ()
virtual void Kill ()
Protected Attributes inherited from Layer
RectTransform _rect
bool isDestroyed
Detailed Description
Definition at line 5 of file LayerDragGrid.cs.
Member Function Documentation
AddPutBack()
void LayerDragGrid.AddPutBack (Thing t, Thing container) inline
Definition at line 314 of file LayerDragGrid.cs.
    {
        if (container != null)
        {
            putBacks.Add(new PutbackInfo
            {
                thing = t,
                container = container
            });
        }
    }
Referenced by UIDragGridIngredients.Refresh(), and UIDragGridIngredients.Update().
ClearButtons()
override void LayerDragGrid.ClearButtons () inline virtual
Reimplemented from LayerBaseCraft.
Definition at line 239 of file LayerDragGrid.cs.
    {
        for (int i = 0; i < owner.numDragGrid; i++)
        {
            buttons[i].SetCardGrid(null);
        }
        RefreshCurrentGrid();
        uiIngredients.Refresh();
    }
References InvOwner.numDragGrid, and UIDragGridIngredients.Refresh().
Referenced by InvOwnerDraglet.OnClick().
Create()
static LayerDragGrid LayerDragGrid.Create (InvOwnerDraglet owner, bool refuelFromLayerDragGrid = false) inline static
Definition at line 381 of file LayerDragGrid.cs.
    {
        return ELayer.ui.AddLayer<LayerDragGrid>("LayerInventory/LayerDragGrid").SetInv(owner, refuelFromLayerDragGrid);
    }
References ELayer.ui.
Referenced by ActPlan._Update(), TraitMod.OnUse(), LayerCraft.SetFactory(), and Trait.TrySetToggleAct().
CreateChangeMaterial()
static LayerDragGrid LayerDragGrid.CreateChangeMaterial (Chara cc, Thing consume, SourceMaterial::Row mat, EffectId idEffect, BlessedState state = BlessedState::Normal, int price = 0, int count = 1) inline static
Definition at line 499 of file LayerDragGrid.cs.
    {
        return TryProc(cc, new InvOwnerChangeMaterial
        {
            consume = consume,
            mat = mat,
            state = state,
            price = price,
            count = count,
            idEffect = idEffect
        });
    }
Referenced by ActEffect.Proc().
CreateChaosOffering()
static LayerDragGrid LayerDragGrid.CreateChaosOffering (TraitAltarChaos altar) inline static
Definition at line 386 of file LayerDragGrid.cs.
    {
        Msg.Say("offer_what");
        return Create(new InvOwnerChaosOffering(altar.owner)
        {
            altar = altar
        });
    }
References Trait.owner, and Msg.Say().
Referenced by TraitAltarChaos.TrySetAct().
CreateCraft()
static LayerDragGrid LayerDragGrid.CreateCraft (TraitCrafter crafter) inline static
Definition at line 425 of file LayerDragGrid.cs.
    {
        return Create(new InvOwnerCraft(crafter.owner)
        {
            crafter = crafter
        });
    }
References Trait.owner.
Referenced by TraitCrafter.OnUse(), and TraitCrafter.TrySetAct().
CreateDeliver()
static LayerDragGrid LayerDragGrid.CreateDeliver (InvOwnerDeliver::Mode mode = InvOwnerDeliver::Mode::Default, Card owner = null) inline static
Definition at line 404 of file LayerDragGrid.cs.
    {
        if (mode == InvOwnerDeliver.Mode.Tax)
        {
            Msg.Say("bills", ELayer.player.taxBills.ToString() ?? "");
        }
        Msg.Say("deliver_what");
        return Create(new InvOwnerDeliver(owner)
        {
            mode = mode
        });
    }
References ELayer.player, Msg.Say(), and Player.taxBills.
Referenced by TraitBank.OnUse(), TraitFarmChest.OnUse(), and TraitTaxChest.OnUse().
CreateEnchant()
static LayerDragGrid LayerDragGrid.CreateEnchant (Chara cc, bool armor, bool superior = false, BlessedState state = BlessedState::Normal, int count = 1) inline static
Definition at line 488 of file LayerDragGrid.cs.
    {
        return TryProc(cc, new InvOwnerEnchant
        {
            armor = armor,
            state = state,
            superior = superior,
            count = count
        });
    }
References armor.
Referenced by ActEffect.Proc().
CreateGacha()
static LayerDragGrid LayerDragGrid.CreateGacha (TraitGacha gacha) inline static
Definition at line 442 of file LayerDragGrid.cs.
    {
        Msg.Say("target_what");
        return Create(new InvOwnerGacha(gacha.owner)
        {
            gacha = gacha
        });
    }
References Trait.owner, and Msg.Say().
Referenced by TraitGacha.TrySetAct().
CreateGive()
static LayerDragGrid LayerDragGrid.CreateGive (Chara c) inline static
Definition at line 417 of file LayerDragGrid.cs.
    {
        return Create(new InvOwnerGive(c)
        {
            chara = c
        });
    }
CreateIdentify()
static LayerDragGrid LayerDragGrid.CreateIdentify (Chara cc, bool superior = false, BlessedState state = BlessedState::Normal, int price = 0, int count = 1) inline static
Definition at line 477 of file LayerDragGrid.cs.
    {
        return TryProc(cc, new InvOwnerIdentify
        {
            state = state,
            price = price,
            count = count,
            superior = superior
        });
    }
Referenced by ActEffect.Proc().
CreateLighten()
static LayerDragGrid LayerDragGrid.CreateLighten (Chara cc, BlessedState state = BlessedState::Normal, int price = 0, int count = 1) inline static
Definition at line 522 of file LayerDragGrid.cs.
    {
        return TryProc(cc, new InvOwnerLighten
        {
            state = state,
            price = price,
            count = count
        });
    }
Referenced by ActEffect.Proc().
CreateOffering()
static LayerDragGrid LayerDragGrid.CreateOffering (TraitAltar altar) inline static
Definition at line 395 of file LayerDragGrid.cs.
    {
        Msg.Say("offer_what");
        return Create(new InvOwnerOffering(altar.owner)
        {
            altar = altar
        });
    }
References Trait.owner, and Msg.Say().
Referenced by TraitAltar.TrySetAct().
CreateReconstruction()
static LayerDragGrid LayerDragGrid.CreateReconstruction (Chara cc, BlessedState state = BlessedState::Normal, int price = 0, int count = 1) inline static
Definition at line 532 of file LayerDragGrid.cs.
    {
        return TryProc(cc, new InvOwnerReconstruction
        {
            state = state,
            price = price,
            count = count
        });
    }
Referenced by ActEffect.Proc().
CreateRecycle()
static LayerDragGrid LayerDragGrid.CreateRecycle (TraitRecycle recycle) inline static
Definition at line 433 of file LayerDragGrid.cs.
    {
        Msg.Say("recycle_what");
        return Create(new InvOwnerRecycle(recycle.owner)
        {
            recycle = recycle
        });
    }
References Trait.owner, and Msg.Say().
Referenced by TraitRecycle.OnUse().
CreateUncurse()
static LayerDragGrid LayerDragGrid.CreateUncurse (Chara cc, BlessedState state = BlessedState::Normal, int price = 0, int count = 1) inline static
Definition at line 512 of file LayerDragGrid.cs.
    {
        return TryProc(cc, new InvOwnerUncurse
        {
            state = state,
            price = price,
            count = count
        });
    }
Referenced by ActEffect.Proc().
GetPrice()
int LayerDragGrid.GetPrice () inline
Definition at line 206 of file LayerDragGrid.cs.
    {
        return owner.price;
    }
References InvOwnerDraglet.price.
GetTargets()
override List< Thing > LayerDragGrid.GetTargets () inline virtual
Reimplemented from LayerBaseCraft.
Definition at line 272 of file LayerDragGrid.cs.
    {
        List<Thing> list = new List<Thing>();
        TraitCrafter traitCrafter = owner.owner.trait as TraitCrafter;
        for (int i = 0; i < traitCrafter.numIng; i++)
        {
            list.Add(buttons[i].card?.Thing ?? null);
        }
        return list;
    }
References card, and TraitCrafter.numIng.
IsAllGridSet()
bool LayerDragGrid.IsAllGridSet () inline
Definition at line 227 of file LayerDragGrid.cs.
    {
        for (int i = 0; i < owner.numDragGrid; i++)
        {
            if (buttons[i].card == null)
            {
                return false;
            }
        }
        return true;
    }
References card, and InvOwner.numDragGrid.
Referenced by InvOwnerDraglet.OnProcess().
OnEndCraft()
override void LayerDragGrid.OnEndCraft () inline virtual
Reimplemented from LayerBaseCraft.
Definition at line 339 of file LayerDragGrid.cs.
    {
        TryPutBack();
    }
OnKill()
override void LayerDragGrid.OnKill () inline virtual
Reimplemented from Layer.
Definition at line 344 of file LayerDragGrid.cs.
    {
        EInput.haltInput = false;
        LayerInventory.CloseAllyInv();
        InvOwner.Trader = null;
        if (!wasInventoryOpen && ELayer.ui.IsInventoryOpen)
        {
            ELayer.ui.ToggleInventory();
        }
        LayerInventory.SetDirtyAll();
        if (ELayer.pc.ai is AI_UseCrafter && ELayer.pc.ai.IsRunning)
        {
            ELayer.pc.ai.Cancel();
        }
    }
References Chara.ai, AIAct.Cancel(), LayerInventory.CloseAllyInv(), AIAct.IsRunning, ELayer.pc, LayerInventory.SetDirtyAll(), and ELayer.ui.
OnOpen()
void LayerDragGrid.OnOpen () inline
Definition at line 62 of file LayerDragGrid.cs.
    {
        Instance = this;
        InvOwner.Trader = owner;
        wasInventoryOpen = ELayer.ui.IsInventoryOpen;
        if (!wasInventoryOpen)
        {
            ELayer.ui.OpenFloatInv(ignoreSound: true);
        }
    }
References Instance, owner, ELayer.ui, and wasInventoryOpen.
Referenced by SetInv().
OnRightClick()
override void LayerDragGrid.OnRightClick () inline virtual
Reimplemented from ELayer.
Definition at line 373 of file LayerDragGrid.cs.
    {
        if (InputModuleEX.GetComponentOf<ButtonGrid>() == null)
        {
            Close();
        }
    }
OnUpdateInput()
override void LayerDragGrid.OnUpdateInput () inline virtual
Reimplemented from Layer.
Definition at line 360 of file LayerDragGrid.cs.
    {
        if (EInput.action == EAction.MenuInventory || Input.GetKeyDown(KeyCode.Tab))
        {
            Close();
            EInput.WaitReleaseKey();
        }
        else
        {
            base.OnUpdateInput();
        }
    }
References EInput.action, and EInput.WaitReleaseKey().
Redraw()
void LayerDragGrid.Redraw () inline
Definition at line 302 of file LayerDragGrid.cs.
    {
        foreach (ButtonGrid button in buttons)
        {
            if (button.gameObject.activeSelf)
            {
                button.Redraw();
            }
        }
        LayerInventory.SetDirtyAll(immediate: true);
    }
References ButtonGrid.Redraw(), and LayerInventory.SetDirtyAll().
Referenced by AI_UseCrafter.Run().
RefreshCost()
void LayerDragGrid.RefreshCost () inline
Definition at line 211 of file LayerDragGrid.cs.
    {
        buttonAutoRefuel.mainText.text = (owner.owner.autoRefuel ? "On" : "Off");
        buttonAutoRefuel.icon.SetAlpha(owner.owner.autoRefuel ? 1f : 0.4f);
        buttonStock.mainText.text = ((!owner.owner.c_isDisableStockUse) ? "On" : "Off");
        buttonStock.icon.SetAlpha((!owner.owner.c_isDisableStockUse) ? 1f : 0.4f);
        textFuel.text = (int)((float)owner.owner.c_charges / (float)owner.owner.trait.MaxFuel * 100f) + "%";
        int price = GetPrice();
        itemCost.transform.parent.SetActive(price != 0);
        if (price != 0)
        {
            itemCost.text1.SetText(Lang._currency(GetPrice()), (ELayer.pc.GetCurrency(owner.IDCurrency) >= price) ? FontColor.Good : FontColor.Bad);
            itemCost.image1.sprite = SpriteSheet.Get("icon_" + owner.IDCurrency);
        }
    }
References Lang._currency(), Card.autoRefuel, Card.c_isDisableStockUse, SpriteSheet.Get(), Card.GetCurrency(), UIButton.icon, InvOwner.IDCurrency, Trait.MaxFuel, InvOwner.owner, ELayer.pc, UIText.SetText(), UIItem.text1, and Card.trait.
Referenced by InvOwnerDraglet.RedrawButton(), and SetInv().
RefreshCurrentGrid()
override void LayerDragGrid.RefreshCurrentGrid () inline virtual
Reimplemented from LayerBaseCraft.
Definition at line 249 of file LayerDragGrid.cs.
    {
        int num = -1;
        for (int i = 0; i < buttons.Count; i++)
        {
            bool flag = buttons[i].Card != null;
            if (num == -1 && (!flag || i == owner.numDragGrid - 1))
            {
                num = i;
            }
            buttons[i].interactable = flag || num == i;
            buttons[i].GetComponent<CanvasGroup>().alpha = (buttons[i].interactable ? 1f : 0.5f);
        }
        currentIndex = num;
        bool flag2 = num >= 0 && num < owner.numDragGrid;
        if (flag2)
        {
            transIndex.position = buttons[num].transform.position;
        }
        transIndex.SetActive(flag2);
        Redraw();
    }
References InvOwner.numDragGrid.
Referenced by InvOwnerDraglet.OnClick(), InvOwnerDraglet.OnProcess(), InvOwnerDraglet.RedrawButton(), and SetInv().
SetInv()
LayerDragGrid LayerDragGrid.SetInv (InvOwnerDraglet owner, bool refuelFromLayerDragGrid = false) inline
Definition at line 73 of file LayerDragGrid.cs.
    {
        owner.Init();
        owner.owner.SetImage(imageOwner);
        this.owner = owner;
        textTitle.text = owner.langTransfer.lang();
        OnOpen();
        buttonOwner.SetCardGrid(owner.owner);
        owner.Container.things.RefreshGrid();
        for (int j = 0; j < buttons.Count; j++)
        {
            buttons[j].gameObject.AddComponent<CanvasGroup>();
            if (owner.numDragGrid > j)
            {
                buttons[j].SetCardGrid(null, owner);
                buttons[j].index = j;
                owner.buttons.Add(buttons[j]);
            }
            else
            {
                buttons[j].SetActive(enable: false);
            }
        }
        uiIngredients.Refresh();
        textFuel.SetActive(owner.owner.trait.IsRequireFuel);
        owner.BuildUICurrency(uiCurrency);
        InvokeRepeating("RefreshCost", 0f, 0.2f);
        this.RebuildLayout(recursive: true);
        RefreshCurrentGrid();
        RefreshCost();
        this.RebuildLayout(recursive: true);
        buttonRefuel.SetActive(owner.ShowFuel);
        buttonAutoRefuel.SetActive(owner.ShowFuel);
        buttonStock.SetActive(owner.AllowStockIngredients);
        if (owner.CanTargetAlly && ELayer.pc.party.members.Count > 1)
        {
            listAlly.callbacks = new UIList.Callback<Chara, UIButton>
            {
                onInstantiate = delegate(Chara a, UIButton b)
                {
                    a.SetImage(b.icon);
                    b.SetTooltipLang(a.Name);
                },
                onClick = delegate(Chara c, UIButton i)
                {
                    if (!LayerInventory.CloseAllyInv(c))
                    {
                        SE.PopInventory();
                        LayerInventory.CreateContainerAlly(c, c);
                    }
                },
                onSort = delegate(Chara a, UIList.SortMode m)
                {
                    a.SetSortVal(m);
                    return -a.sortVal;
                },
                onList = delegate
                {
                    foreach (Chara member in ELayer.pc.party.members)
                    {
                        if (!member.IsPC)
{
                            listAlly.Add(member);
                        }
                    }
                }
            };
            listAlly.List();
        }
        else
        {
            listAlly.SetActive(enable: false);
        }
        buttonRefuel.SetOnClick(delegate
        {
            if (!ELayer.pc.HasNoGoal)
            {
                SE.BeepSmall();
            }
            else
            {
                windows[0].SetInteractable(enable: false, 0f);
                info.InitFuel(owner.owner);
                Create(new InvOwnerRefuel(owner.owner), refuelFromLayerDragGrid: true).SetOnKill(delegate
                {
                    if (!isDestroyed)
                    {
                        windows[0].SetInteractable(enable: true);
                        info.Init(owner.owner);
                        OnOpen();
                        RefreshCurrentGrid();
                        Redraw();
                        owner.OnAfterRefuel();
                    }
                });
            }
        });
        buttonAutoRefuel.SetOnClick(delegate
        {
            SE.Click();
            owner.owner.autoRefuel = !owner.owner.autoRefuel;
            RefreshCost();
            if (owner.owner.trait.IsFuelEnough())
            {
                owner.OnAfterRefuel();
            }
        });
        buttonStock.SetOnClick(delegate
        {
            SE.Click();
            owner.owner.c_isDisableStockUse = !owner.owner.c_isDisableStockUse;
            uiIngredients.Refresh();
            RefreshCost();
        });
        if (owner is InvOwnerRefuel)
        {
            if (refuelFromLayerDragGrid)
            {
                info.SetActive(enable: false);
            }
            else
            {
                Debug.Log(owner.owner);
                info.InitFuel(owner.owner);
            }
        }
        else
        {
            info.Init(owner.owner);
        }
        return this;
    }
References UIList.Add(), InvOwnerDraglet.AllowStockIngredients, InvOwnerDraglet.BuildUICurrency(), buttonAutoRefuel, buttonOwner, buttonRefuel, InvOwner.buttons, buttons, buttonStock, InvOwnerDraglet.CanTargetAlly, LayerInventory.CloseAllyInv(), InvOwner.Container, LayerInventory.CreateContainerAlly(), Chara.HasNoGoal, UIButton.icon, imageOwner, InvOwner.Init(), Chara.IsPC, Trait.IsRequireFuel, InvOwner.langTransfer, UIList.List(), listAlly, Party.members, Card.Name, InvOwner.numDragGrid, OnOpen(), InvOwner.owner, owner, Chara.party, ELayer.pc, UIDragGridIngredients.Refresh(), RefreshCost(), RefreshCurrentGrid(), ThingContainer.RefreshGrid(), ButtonGrid.SetCardGrid(), Card.SetImage(), Chara.SetSortVal(), UIButton.SetTooltipLang(), InvOwnerDraglet.ShowFuel, Card.sortVal, textFuel, Card.things, Card.trait, uiCurrency, and uiIngredients.
TryProc()
static LayerDragGrid LayerDragGrid.TryProc (Chara cc, InvOwnerEffect owner) inline static
Definition at line 451 of file LayerDragGrid.cs.
    {
        owner.cc = cc;
        if (cc.IsPC)
        {
            return Create(owner);
        }
        int num = ((owner.count == -1) ? 1 : owner.count);
        for (int i = 0; i < num; i++)
        {
            List<Thing> list = cc.things.List((Thing t) => owner.ShouldShowGuide(t));
            if (list.Count > 0)
            {
                Thing t2 = list.RandomItem();
                owner._OnProcess(t2);
                continue;
            }
            if (i == 0)
            {
                cc.SayNothingHappans();
            }
            break;
        }
        return null;
    }
References InvOwnerDraglet._OnProcess(), InvOwnerDraglet.count, Chara.IsPC, ThingContainer.List(), Card.SayNothingHappans(), InvOwner.ShouldShowGuide(), and Card.things.
TryPutBack()
void LayerDragGrid.TryPutBack () inline
Definition at line 326 of file LayerDragGrid.cs.
    {
        foreach (PutbackInfo putBack in putBacks)
        {
            if (!putBack.thing.isDestroyed && putBack.thing.Num != 0 && putBack.thing.parent != putBack.container && !putBack.container.isDestroyed)
            {
                putBack.container.AddCard(putBack.thing);
            }
        }
        putBacks.Clear();
        RefreshCurrentGrid();
    }
References Card.AddCard(), LayerDragGrid.PutbackInfo.container, Card.isDestroyed, Card.Num, Card.parent, and LayerDragGrid.PutbackInfo.thing.
Referenced by InvOwnerDraglet.OnClick().
Update()
void LayerDragGrid.Update () inline private
Definition at line 283 of file LayerDragGrid.cs.
    {
        Validate();
    }
Validate()
void LayerDragGrid.Validate () inline
Definition at line 288 of file LayerDragGrid.cs.
    {
        Card card = buttonOwner.card;
        if (card.Num != lastNum)
        {
            lastNum = card.Num;
            buttonOwner.SetCardGrid(owner.owner);
        }
        if (card == null || card.isDestroyed)
        {
            Close();
        }
    }
References ButtonGrid.card, card, InvOwner.owner, and ButtonGrid.SetCardGrid().
Member Data Documentation
buttonAlly
UIButton LayerDragGrid.buttonAlly
Definition at line 36 of file LayerDragGrid.cs.
buttonAutoRefuel
UIButton LayerDragGrid.buttonAutoRefuel
Definition at line 34 of file LayerDragGrid.cs.
Referenced by SetInv().
buttonOwner
ButtonGrid LayerDragGrid.buttonOwner
Definition at line 30 of file LayerDragGrid.cs.
Referenced by SetInv().
buttonRefuel
UIButton LayerDragGrid.buttonRefuel
Definition at line 32 of file LayerDragGrid.cs.
Referenced by SetInv().
buttons
List<ButtonGrid> LayerDragGrid.buttons
Definition at line 28 of file LayerDragGrid.cs.
Referenced by InvOwnerAlly.GetAutoUseLang(), TraitCrafter.IsCraftIngredient(), InvOwnerDraglet.OnProcess(), UIDragGridIngredients.Refresh(), SetInv(), and UIDragGridIngredients.Update().
buttonStock
UIButton LayerDragGrid.buttonStock
Definition at line 38 of file LayerDragGrid.cs.
Referenced by SetInv().
currentIndex
int LayerDragGrid.currentIndex
Definition at line 44 of file LayerDragGrid.cs.
Referenced by InvOwner.Transaction.IsValid(), InvOwner.Transaction.Process(), UIDragGridIngredients.Refresh(), and UIDragGridIngredients.Update().
imageOwner
Image LayerDragGrid.imageOwner
Definition at line 20 of file LayerDragGrid.cs.
Referenced by SetInv().
info
UIDragGridInfo LayerDragGrid.info
Definition at line 46 of file LayerDragGrid.cs.
Referenced by TraitCrafter.Craft().
Instance
LayerDragGrid LayerDragGrid.Instance static
Definition at line 14 of file LayerDragGrid.cs.
Referenced by TraitCrafter.Craft(), GameUpdater.ThingUpdater.FixedUpdate(), InvOwnerAlly.GetAutoUseLang(), TraitCrafter.IsCraftIngredient(), InvOwner.Transaction.IsValid(), DragItemCard.OnEndDrag(), OnOpen(), DragItemCard.OnStartDrag(), InvOwner.Transaction.Process(), InvOwnerAlly.Process(), and AI_UseCrafter.Run().
itemCost
UIItem LayerDragGrid.itemCost
Definition at line 18 of file LayerDragGrid.cs.
lastNum
int LayerDragGrid.lastNum private
Definition at line 54 of file LayerDragGrid.cs.
listAlly
UIList LayerDragGrid.listAlly
Definition at line 48 of file LayerDragGrid.cs.
Referenced by SetInv().
owner
InvOwnerDraglet LayerDragGrid.owner
Definition at line 40 of file LayerDragGrid.cs.
Referenced by InvOwnerAlly.GetAutoUseLang(), OnOpen(), DragItemCard.OnStartDrag(), UIDragGridIngredients.Refresh(), AI_UseCrafter.Run(), SetInv(), and UIDragGridIngredients.Update().
putBacks
List<PutbackInfo> LayerDragGrid.putBacks = new List<PutbackInfo>()
Definition at line 16 of file LayerDragGrid.cs.
textFuel
UIText LayerDragGrid.textFuel
Definition at line 24 of file LayerDragGrid.cs.
Referenced by SetInv().
textTitle
UIText LayerDragGrid.textTitle
Definition at line 22 of file LayerDragGrid.cs.
transIndex
Transform LayerDragGrid.transIndex
Definition at line 26 of file LayerDragGrid.cs.
uiCurrency
UICurrency LayerDragGrid.uiCurrency
Definition at line 42 of file LayerDragGrid.cs.
Referenced by SetInv().
uiIngredients
UIDragGridIngredients LayerDragGrid.uiIngredients
Definition at line 50 of file LayerDragGrid.cs.
Referenced by InvOwnerDraglet.OnClick(), InvOwnerDraglet.OnProcess(), and SetInv().
wasInventoryOpen
bool LayerDragGrid.wasInventoryOpen private
Definition at line 52 of file LayerDragGrid.cs.
Referenced by OnOpen().
Property Documentation
CanCancelAI
override bool LayerDragGrid.CanCancelAI get
Definition at line 58 of file LayerDragGrid.cs.
CurrentButton
ButtonGrid LayerDragGrid.CurrentButton get
Definition at line 56 of file LayerDragGrid.cs.
Referenced by DragItemCard.OnEndDrag(), DragItemCard.OnStartDrag(), and InvOwnerAlly.Process().
RepeatAI
override bool LayerDragGrid.RepeatAI get
Definition at line 60 of file LayerDragGrid.cs.
The documentation for this class was generated from the following file:
Elin/LayerDragGrid.cs