Elin Decompiled Documentation: PointTarget Class Reference
PointTarget Class Reference
Public Member Functions
void Update (Point _pos)
bool ShouldIgnore (Card c)
void CycleTarget (int a)
bool CanCycle ()
void Clear ()
void CheckLastTarget ()
Public Attributes
Card card
Area area
ObjInfo obj
BlockInfo block
TaskPoint task
IInspect target
IInspect lastTarget
bool hasTargetChanged
bool hasValidTarget
bool drawHighlight
bool mouse = true
bool hasInteraction
bool isValid
Point pos = new Point()
Point lastPos = new Point()
int index
List< Card > cards = new List<Card>()
Properties
Chara TargetChara [get]
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Additional Inherited Members
Static Public Member Functions inherited from EClass
static int rnd (int a)
static int curve (int a, int start, int step, int rate=75)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Static Public Attributes inherited from EClass
static Core core
Detailed Description
Definition at line 5 of file PointTarget.cs.
Member Function Documentation
CanCycle()
bool PointTarget.CanCycle () inline
Definition at line 185 of file PointTarget.cs.
    {
        return this.cards.Count >= 2;
    }
Referenced by AM_Adv._OnUpdateInput(), AM_MoveInstalled.HitTest(), AM_MoveInstalled.InputWheel(), and AM_MoveInstalled.OnRenderTile().
CheckLastTarget()
void PointTarget.CheckLastTarget () inline
Definition at line 199 of file PointTarget.cs.
    {
        this.hasTargetChanged = (this.target != this.lastTarget || !this.pos.Equals(this.lastPos));
        this.hasValidTarget = (this.target != null);
        this.lastTarget = this.target;
        this.lastPos.Set(this.pos);
    }
References Point.Equals(), lastPos, pos, Point.Set(), and target.
Referenced by Clear(), and Update().
Clear()
void PointTarget.Clear () inline
Definition at line 190 of file PointTarget.cs.
    {
        this.card = null;
        this.area = null;
        this.target = null;
        this.hasInteraction = false;
        this.CheckLastTarget();
    }
References CheckLastTarget().
Referenced by Scene.OnKillGame(), and Update().
CycleTarget()
void PointTarget.CycleTarget (int a) inline
Definition at line 174 of file PointTarget.cs.
    {
        SE.Rotate();
        this.index += a;
        this.Update(Scene.HitPoint);
        if (WidgetMouseover.Instance)
        {
            WidgetMouseover.Instance.Refresh();
        }
    }
References Scene.HitPoint, WidgetMouseover.Instance, WidgetMouseover.Refresh(), and Update().
Referenced by AM_Adv._OnUpdateInput(), and AM_MoveInstalled.InputWheel().
ShouldIgnore()
bool PointTarget.ShouldIgnore (Card c) inline
Definition at line 114 of file PointTarget.cs.
    {
        if (c.isChara)
        {
            if (c.Chara.host != null)
            {
                return true;
            }
            if (EClass.scene.actionMode.IsBuildMode)
            {
                if (!EClass.debug.ignoreBuildRule && (c.IsPC || !c.IsPCFaction))
                {
                    return true;
                }
            }
            else
            {
                if ((!EClass.pc.hasTelepathy || !c.Chara.race.visibleWithTelepathy) && c.isHidden && !EClass.pc.canSeeInvisible)
                {
                    return true;
                }
                if (c.IsPC)
                {
                    return true;
                }
                if (!c.isSynced || !EClass.player.CanSee(c.Chara))
                {
                    return true;
                }
            }
            return false;
        }
        else
        {
            if (c.trait.IsGround && !this.pos.cell.IsFloorWater && c.Cell.IsFloorWater)
            {
                return true;
            }
            if (EClass.scene.actionMode.IsBuildMode)
            {
                if (EClass.scene.actionMode.IsRoofEditMode(null))
                {
                    if (!c.isRoofItem)
                    {
                        return true;
                    }
                }
                else if (c.isRoofItem)
                {
                    return true;
                }
            }
            else if (c.isHidden || c.isRoofItem || c.isMasked)
            {
                return true;
            }
            return false;
        }
    }
References Scene.actionMode, Player.CanSee(), Chara.canSeeInvisible, Card.Cell, Card.Chara, EClass.debug, Chara.hasTelepathy, Chara.host, CoreDebug.ignoreBuildRule, ActionMode.IsBuildMode, Card.isChara, Cell.IsFloorWater, Trait.IsGround, Card.isHidden, Card.isMasked, Card.IsPC, Card.IsPCFaction, ActionMode.IsRoofEditMode(), Card.isRoofItem, Card.isSynced, EClass.pc, EClass.player, Chara.race, EClass.scene, and Card.trait.
Referenced by Update().
Update()
void PointTarget.Update (Point _pos) inline
Definition at line 19 of file PointTarget.cs.
    {
        this.pos.Set(_pos);
        this.isValid = this.pos.IsValid;
        this.cards.Clear();
        if (!this.isValid || this.pos.IsHidden || EClass.ui.BlockMouseOverUpdate || (this.mouse && (EClass.ui.isPointerOverUI || !EClass.scene.actionMode.ShowMouseoverTarget)))
        {
            this.Clear();
            return;
        }
        this.card = null;
        this.area = null;
        this.task = null;
        this.block = (BlockInfo._CanInspect(this.pos) ? BlockInfo.GetTemp(this.pos) : null);
        if (this.pos.sourceBlock.tileType.Invisible && !EClass.scene.actionMode.IsBuildMode)
        {
            this.block = null;
        }
        this.obj = (ObjInfo._CanInspect(this.pos) ? ObjInfo.GetTemp(this.pos) : null);
        if (this.obj != null)
        {
            this.target = this.obj;
        }
        else if (this.block != null)
        {
            this.target = this.block;
        }
        else
        {
            this.target = null;
        }
        this.drawHighlight = (this.target != null);
        CellDetail detail = this.pos.detail;
        if (detail != null)
        {
            this.area = detail.area;
            this.task = detail.designation;
            Thing thing = null;
            Chara chara = null;
            foreach (Chara chara2 in detail.charas)
            {
                if (!this.ShouldIgnore(chara2))
                {
                    this.cards.Add(chara2);
                    if (chara == null || chara2.hostility < chara.hostility)
                    {
                        chara = chara2;
                    }
                }
            }
            foreach (Thing thing2 in detail.things)
            {
                if (!this.ShouldIgnore(thing2))
                {
                    this.cards.Add(thing2);
                    thing = thing2;
                }
            }
            if (chara != null)
            {
                this.target = (this.card = chara);
                this.drawHighlight = true;
            }
            else if (thing != null)
            {
                this.target = (this.card = thing);
                this.drawHighlight = true;
            }
            else if (this.task != null)
            {
                this.target = this.task;
                this.drawHighlight = true;
            }
            else if (this.area != null && EClass.scene.actionMode.AreaHihlight != AreaHighlightMode.None)
            {
                this.target = this.area;
            }
            if (this.cards.Count > 0 && EClass.scene.actionMode.IsBuildMode)
            {
                this.target = (this.card = this.cards[Mathf.Abs(this.index) % this.cards.Count]);
                this.drawHighlight = true;
            }
        }
        if ((this.target == null || this.target is Chara) && EClass._zone.IsRegion)
        {
            Zone zone = EClass.scene.elomap.GetZone(this.pos);
            if (zone != null)
            {
                this.target = zone;
            }
        }
        this.hasInteraction = (this.target != null);
        this.CheckLastTarget();
    }
References BlockInfo._CanInspect(), ObjInfo._CanInspect(), EClass._zone, Scene.actionMode, CellDetail.area, area, ActionMode.AreaHihlight, block, cards, CellDetail.charas, CheckLastTarget(), Clear(), CellDetail.designation, Point.detail, Scene.elomap, BlockInfo.GetTemp(), ObjInfo.GetTemp(), EloMap.GetZone(), Chara.hostility, index, ActionMode.IsBuildMode, Point.IsHidden, Spatial.IsRegion, Point.IsValid, isValid, obj, pos, EClass.scene, Point.Set(), ShouldIgnore(), ActionMode.ShowMouseoverTarget, Point.sourceBlock, target, task, CellDetail.things, and EClass.ui.
Referenced by AM_Adv.AxisMove(), CycleTarget(), and ActionMode.UpdateInput().
Member Data Documentation
area
Area PointTarget.area
Definition at line 209 of file PointTarget.cs.
Referenced by Update().
block
BlockInfo PointTarget.block
Definition at line 213 of file PointTarget.cs.
Referenced by Update().
card
Card PointTarget.card
Definition at line 207 of file PointTarget.cs.
Referenced by AM_MoveInstalled.GetTarget(), AM_Inspect.OnUpdateInput(), WidgetMouseover.Refresh(), Cell.RotateAll(), and ActionMode.UpdateInput().
cards
List<Card> PointTarget.cards = new List<Card>()
Definition at line 239 of file PointTarget.cs.
Referenced by WidgetMouseover.Refresh(), and Update().
drawHighlight
bool PointTarget.drawHighlight
Definition at line 225 of file PointTarget.cs.
Referenced by AM_ViewZone.OnRenderTile().
hasInteraction
bool PointTarget.hasInteraction
Definition at line 229 of file PointTarget.cs.
hasTargetChanged
bool PointTarget.hasTargetChanged
Definition at line 221 of file PointTarget.cs.
Referenced by AM_Adv.OnUpdateCursor(), and WidgetMouseover.Refresh().
hasValidTarget
bool PointTarget.hasValidTarget
Definition at line 223 of file PointTarget.cs.
Referenced by WidgetInspector.OnUpdateInput().
index
int PointTarget.index
Definition at line 237 of file PointTarget.cs.
Referenced by Update().
isValid
bool PointTarget.isValid
Definition at line 231 of file PointTarget.cs.
Referenced by AM_Adv._OnUpdateInput(), ActPlan.Item.Perform(), and Update().
lastPos
Point PointTarget.lastPos = new Point()
Definition at line 235 of file PointTarget.cs.
Referenced by CheckLastTarget().
lastTarget
IInspect PointTarget.lastTarget
Definition at line 219 of file PointTarget.cs.
mouse
bool PointTarget.mouse = true
Definition at line 227 of file PointTarget.cs.
obj
ObjInfo PointTarget.obj
Definition at line 211 of file PointTarget.cs.
Referenced by Update().
pos
Point PointTarget.pos = new Point()
Definition at line 233 of file PointTarget.cs.
Referenced by AM_Adv._OnUpdateInput(), ActPlan._Update(), ActRush.CanPerform(), CheckLastTarget(), ActionMode.DoFunc(), UIInspector.InspectUnderMouse(), AM_Adv.OnAfterUpdate(), ActRush.OnMarkMapHighlights(), AM_ViewZone.OnRenderTile(), ActRush.Perform(), ActPlan.Item.Perform(), WidgetMouseover.Refresh(), AM_Adv.RefreshArrow(), TaskPoint.Run(), Player.TargetRanged(), LayerInteraction.TryShow(), Update(), and AM_Adv.UpdateLangWheel().
target
IInspect PointTarget.target
Definition at line 217 of file PointTarget.cs.
Referenced by CheckLastTarget(), WidgetMouseover.Refresh(), HotItemHeld.TrySetAct(), and Update().
task
TaskPoint PointTarget.task
Definition at line 215 of file PointTarget.cs.
Referenced by Update().
Property Documentation
TargetChara
Chara PointTarget.TargetChara get
Definition at line 7 of file PointTarget.cs.
    {
        get
        {
            if (this.card != null)
            {
                return this.card.Chara;
            }
            return null;
        }
    }
Referenced by ActPlan._Update(), ActRush.CanPerform(), ActionMode.DoFunc(), ActRush.OnMarkMapHighlights(), ActRush.Perform(), and CoreDebug.UpdateInput().
The documentation for this class was generated from the following file:
Elin/PointTarget.cs