Elin Decompiled Documentation: WindowMenu Class Reference
WindowMenu Class Reference
Public Member Functions
WindowMenu (LayoutGroup _layout)
WindowMenu (string _id, Window _window)
void Init ()
void Clear ()
UIButton AddButton (string idLang, Action< UIButton > onClick, Sprite sprite=null, string idButton="Default")
UIButton AddButtonSimple (Func< string > funcText, Action< UIButton > onClick=null, Sprite sprite=null, string idButton="Simple")
UIButton AddButton2Line (string idLang, Func< string > funcText, Action< UIButton > onClick=null, Sprite sprite=null, string idButton="2line")
UIButton _AddButton (string idButton, Sprite sprite, Action< UIButton > onClick)
Public Attributes
string id
Window window
LayoutGroup layout
Transform header
Private Attributes
bool initialized
Detailed Description
Definition at line 5 of file WindowMenu.cs.
Constructor & Destructor Documentation
WindowMenu() [1/2]
WindowMenu.WindowMenu (LayoutGroup _layout) inline
Definition at line 17 of file WindowMenu.cs.
    {
        layout = _layout;
        initialized = true;
    }
References initialized, and layout.
WindowMenu() [2/2]
WindowMenu.WindowMenu (string _id, Window _window) inline
Definition at line 23 of file WindowMenu.cs.
    {
        id = _id;
        window = _window;
    }
References window.
Member Function Documentation
_AddButton()
UIButton WindowMenu._AddButton (string idButton, Sprite sprite, Action< UIButton > onClick) inline
Definition at line 113 of file WindowMenu.cs.
    {
        Init();
        UIButton uIButton = Util.Instantiate<UIButton>("UI/Window/Base/Element/ButtonWindowMenu_" + idButton, layout);
        if ((bool)sprite)
        {
            uIButton.icon.sprite = sprite;
            uIButton.icon.SetActive(enable: true);
        }
        if ((bool)header)
        {
            header.SetActive(enable: true);
        }
        return uIButton;
    }
References header, UIButton.icon, Init(), layout, and Util.
Referenced by AddButton(), AddButton2Line(), and AddButtonSimple().
AddButton()
UIButton WindowMenu.AddButton (string idLang, Action< UIButton > onClick, Sprite sprite = null, string idButton = "Default") inline
Definition at line 54 of file WindowMenu.cs.
    {
        Init();
        UIButton b = _AddButton(idButton, sprite, onClick);
        b.onClick.AddListener(delegate
        {
            onClick(b);
        });
        b.mainText.text = idLang.lang();
        if ((bool)header)
        {
            header.SetActive(enable: true);
        }
        return b;
    }
References _AddButton(), header, and Init().
Referenced by LayerQuestBoard.OnSwitchContent().
AddButton2Line()
UIButton WindowMenu.AddButton2Line (string idLang, Func< string > funcText, Action< UIButton > onClick = null, Sprite sprite = null, string idButton = "2line") inline
Definition at line 91 of file WindowMenu.cs.
    {
        Init();
        UIButton b = _AddButton(idButton, sprite, onClick);
        b.onClick.AddListener(delegate
        {
            onClick?.Invoke(b);
            SE.Click();
            if ((bool)b)
            {
                b.subText.text = funcText().lang();
            }
        });
        b.mainText.text = idLang.lang();
        b.subText.text = funcText().lang();
        if ((bool)header)
        {
            header.SetActive(enable: true);
        }
        return b;
    }
References _AddButton(), header, and Init().
Referenced by LayerResource.OnInit(), BaseListPeople.OnRefreshMenu(), and LayerTech.RefreshTech().
AddButtonSimple()
UIButton WindowMenu.AddButtonSimple (Func< string > funcText, Action< UIButton > onClick = null, Sprite sprite = null, string idButton = "Simple") inline
Definition at line 70 of file WindowMenu.cs.
    {
        Init();
        UIButton b = _AddButton(idButton, sprite, onClick);
        b.onClick.AddListener(delegate
        {
            onClick?.Invoke(b);
            SE.Click();
            if ((bool)b)
            {
                b.subText.text = funcText().lang();
            }
        });
        b.subText.text = funcText().lang();
        if ((bool)header)
        {
            header.SetActive(enable: true);
        }
        return b;
    }
References _AddButton(), header, and Init().
Referenced by LayerHome.OnSwitchContent().
Clear()
void WindowMenu.Clear () inline
Definition at line 44 of file WindowMenu.cs.
    {
        Init();
        layout.DestroyChildren();
        if ((bool)header)
        {
            header.SetActive(enable: false);
        }
    }
References header, Init(), and layout.
Referenced by BaseListPeople.OnRefreshMenu(), ListOwner< T1, T2 >.OnRefreshMenu(), LayerHome.OnSwitchContent(), LayerQuestBoard.OnSwitchContent(), and LayerTech.RefreshTech().
Init()
void WindowMenu.Init () inline
Definition at line 29 of file WindowMenu.cs.
    {
        if (!initialized)
        {
            layout = Util.Instantiate<LayoutGroup>("UI/Window/Base/Element/WindowMenu" + id, window);
            header = layout.transform.Find("header");
            initialized = true;
            SkinRootStatic currentSkin = SkinManager.CurrentSkin;
            if (id == "Left")
            {
                layout.Rect().anchoredPosition = currentSkin.positions.leftMenu;
            }
        }
    }
References SkinManager.CurrentSkin, header, id, initialized, layout, SkinRootStatic.Positions.leftMenu, SkinRootStatic.positions, Util, and window.
Referenced by _AddButton(), AddButton(), AddButton2Line(), AddButtonSimple(), and Clear().
Member Data Documentation
header
Transform WindowMenu.header
Definition at line 13 of file WindowMenu.cs.
Referenced by _AddButton(), AddButton(), AddButton2Line(), AddButtonSimple(), Clear(), and Init().
id
string WindowMenu.id
Definition at line 7 of file WindowMenu.cs.
Referenced by Init().
initialized
bool WindowMenu.initialized private
Definition at line 15 of file WindowMenu.cs.
Referenced by Init(), and WindowMenu().
layout
LayoutGroup WindowMenu.layout
Definition at line 11 of file WindowMenu.cs.
Referenced by _AddButton(), Window.ApplySkin(), Clear(), Init(), and WindowMenu().
window
Window WindowMenu.window
Definition at line 9 of file WindowMenu.cs.
Referenced by Init(), and WindowMenu().
The documentation for this class was generated from the following file:
Elin/Plugins.UI/WindowMenu.cs