Elin Decompiled Documentation: ContentHallOfFame Class Reference
ContentHallOfFame Class Reference
Public Member Functions
override void OnSwitchContent (int idTab)
void Refresh ()
Public Member Functions inherited from UIContent
virtual void OnSwitchContent (int idTab)
virtual void OnInstantiate ()
Public Member Functions inherited from UINote
void Clear ()
void Build ()
void Space (int sizeY=0, int sizeX=1)
UINote AddNote (string id)
UIItem AddHeader (string text, Sprite sprite=null)
UIItem AddHeaderCard (string text, Sprite sprite=null)
UIItem AddHeaderTopic (string text, Sprite sprite=null)
UIItem AddHeader (string id, string text, Sprite sprite=null)
UIItem AddText (string text, FontColor color=FontColor.DontChange)
UIItem AddText (string id, string text, FontColor color=FontColor.DontChange)
UIItem AddText (string id, string text, Color color)
UIItem AddItem (string id)
UIItem AddTopic (string id, string text, string value=null)
UIItem AddTopic (string text, string value=null)
void AddImage (Sprite sprite)
void AddImage (string idFile)
UIButton AddButton (string text, Action onClick)
UIButton AddButtonLink (string text, string url)
UIDropdown AddDropdown (string id="DropdownDefault")
UIButton AddToggle (string idLang="", bool isOn=false, Action< bool > action=null)
Transform AddPrefab (string path)
T AddExtra< T > (string path)
Public Attributes
UIText textElapsedTime
UIText textGamneTime
UIText textKilled
UIText textMined
UIText textTax
Public Attributes inherited from UINote
RectTransform target
UINoteProfile prof
SkinType skinType
string idDefaultText
LayoutGroup layout
RectTransform cur
bool extraRebuild
Private Member Functions
void OnEnable ()
void OnDisable ()
Detailed Description
Definition at line 1 of file ContentHallOfFame.cs.
Member Function Documentation
OnDisable()
void ContentHallOfFame.OnDisable () inline private
Definition at line 18 of file ContentHallOfFame.cs.
    {
        CancelInvoke("Refresh");
    }
OnEnable()
void ContentHallOfFame.OnEnable () inline private
Definition at line 13 of file ContentHallOfFame.cs.
    {
        InvokeRepeating("Refresh", 1f, 1f);
    }
OnSwitchContent()
override void ContentHallOfFame.OnSwitchContent (int idTab) inline virtual
Reimplemented from UIContent.
Definition at line 23 of file ContentHallOfFame.cs.
    {
        textKilled.text = EClass.player.stats.kills.ToString() ?? "";
        textMined.text = EClass.player.stats.digs.ToString() ?? "";
        textTax.text = "u2_money".lang(EClass.player.stats.taxBillsPaid.ToString() ?? "");
        Refresh();
    }
References Player.Stats.digs, Player.Stats.kills, EClass.player, Refresh(), Player.stats, and Player.Stats.taxBillsPaid.
Refresh()
void ContentHallOfFame.Refresh () inline
Definition at line 31 of file ContentHallOfFame.cs.
    {
        double num = EClass.player.stats.timeElapsed % 60.0;
        double num2 = EClass.player.stats.timeElapsed / 60.0 % 60.0;
        double num3 = EClass.player.stats.timeElapsed / 3600.0;
        textElapsedTime.text = Lang.Parse("elapsedTime", ((int)num3).ToString() ?? "", ((int)num2).ToString() ?? "", ((int)num).ToString() ?? "");
        textGamneTime.text = "tGameTime".lang(EClass.player.stats.days.ToString() ?? "", EClass.player.stats.turns.ToString() ?? "");
    }
References Player.Stats.days, Lang.Parse(), EClass.player, Player.stats, and Player.Stats.turns.
Referenced by OnSwitchContent().
Member Data Documentation
textElapsedTime
UIText ContentHallOfFame.textElapsedTime
Definition at line 3 of file ContentHallOfFame.cs.
textGamneTime
UIText ContentHallOfFame.textGamneTime
Definition at line 5 of file ContentHallOfFame.cs.
textKilled
UIText ContentHallOfFame.textKilled
Definition at line 7 of file ContentHallOfFame.cs.
textMined
UIText ContentHallOfFame.textMined
Definition at line 9 of file ContentHallOfFame.cs.
textTax
UIText ContentHallOfFame.textTax
Definition at line 11 of file ContentHallOfFame.cs.
The documentation for this class was generated from the following file:
Elin/ContentHallOfFame.cs