Elin Decompiled Documentation: ZoneUtil Class Reference
ZoneUtil Class Reference
Public Member Functions
bool AddBandits ()
bool AddMerchant (string id)
Public Attributes
Zone zone
Properties
Map map [get]
Detailed Description
Definition at line 1 of file ZoneUtil.cs.
Member Function Documentation
AddBandits()
bool ZoneUtil.AddBandits () inline
Definition at line 7 of file ZoneUtil.cs.
    {
        Point centerPos = map.bounds.GetCenterPos();
        for (int i = 0; i < 5; i++)
        {
            Chara t = CharaGen.CreateFromFilter("c_wilds");
            zone.AddCardSplinkle(t, centerPos, 5);
        }
        return true;
    }
References Zone.AddCardSplinkle(), Map.bounds, CharaGen.CreateFromFilter(), MapBounds.GetCenterPos(), map, and zone.
AddMerchant()
bool ZoneUtil.AddMerchant (string id) inline
Definition at line 18 of file ZoneUtil.cs.
    {
        Point centerPos = map.bounds.GetCenterPos();
        Chara t = CharaGen.Create(id);
        zone.AddCard(t, centerPos);
        return true;
    }
References Zone.AddCard(), Map.bounds, CharaGen.Create(), MapBounds.GetCenterPos(), map, and zone.
Member Data Documentation
zone
Zone ZoneUtil.zone
Definition at line 3 of file ZoneUtil.cs.
Referenced by AddBandits(), and AddMerchant().
Property Documentation
map
Map ZoneUtil.map get
Definition at line 5 of file ZoneUtil.cs.
Referenced by AddBandits(), and AddMerchant().
The documentation for this class was generated from the following file:
Elin/ZoneUtil.cs