Elin Decompiled Documentation: BiomeProfile.ClusterThing Class Reference
BiomeProfile.ClusterThing Class Reference
Public Member Functions
override bool TryCreate (Point p)
virtual bool TryCreate (Point p)
Public Attributes
List< ItemThing > items
Public Attributes inherited from BiomeProfile.Cluster
Type type
float density
Additional Inherited Members
Public Types inherited from BiomeProfile.Cluster
enum Type {
Scatter = 0 , ScatterExterior = 1 , ScatterInterior = 2 , ScatterNonObstacle = 3 ,
ByWall = 10 , ByWallFace = 11 , Space = 20 , SpaceByWall = 21
}
Detailed Description
Definition at line 600 of file BiomeProfile.cs.
Member Function Documentation
TryCreate()
override bool BiomeProfile.ClusterThing.TryCreate (Point p) inline virtual
Reimplemented from BiomeProfile.Cluster.
Definition at line 604 of file BiomeProfile.cs.
        {
            ItemThing itemThing = items.RandomItem();
            if (Rand.Range(0f, 1f) > itemThing.chance)
            {
                return false;
            }
            Cell cell = p.cell;
            if (cell.HasBlock)
            {
                if (!itemThing.IsSpawnOnBlock)
                {
                    return false;
                }
            }
            else if (itemThing.IsSpawnOnBlock)
            {
                return false;
            }
            if (cell.IsTopWater)
            {
                if (!itemThing.IsSpawnOnWater)
                {
                    return false;
                }
            }
            else if (itemThing.IsSpawnOnWater)
            {
                return false;
            }
            Thing thing = ThingGen.Create(itemThing.id, itemThing.GetIdMaterial());
            int num = thing.TileType.GetDesiredDir(p, 0);
            if (itemThing.alignDir)
            {
                if (cell.Back.HasBlock)
                {
                    num = 0;
                }
                else if (cell.Left.HasBlock)
                {
                    num = 1;
                }
                else if (cell.Front.HasBlock)
                {
                    num = 2;
                }
                else if (cell.Right.HasBlock)
                {
                    num = 3;
                }
                if (itemThing.id == "coffin_stone")
                {
                    num++;
                }
            }
            if (num != -1)
            {
                thing.dir = num;
            }
            EClass._zone.AddCard(thing, p).Install();
            return true;
        }
References EClass._zone, Zone.AddCard(), BiomeProfile.Cluster.ItemThing.alignDir, Cell.Back, Point.cell, BiomeProfile.Cluster.BaseItem.chance, ThingGen.Create(), Cell.Front, TileType.GetDesiredDir(), BiomeProfile.Cluster.BaseItem.GetIdMaterial(), Cell.HasBlock, BiomeProfile.Cluster.ItemThing.id, Card.Install(), BiomeProfile.Cluster.BaseItem.IsSpawnOnBlock, BiomeProfile.Cluster.BaseItem.IsSpawnOnWater, Cell.IsTopWater, BiomeProfile.ClusterThing.items, Cell.Left, Rand.Range(), Cell.Right, and Card.TileType.
Member Data Documentation
items
List<ItemThing> BiomeProfile.ClusterThing.items
Definition at line 602 of file BiomeProfile.cs.
Referenced by BiomeProfile.ClusterThing.TryCreate().
The documentation for this class was generated from the following file:
Elin/BiomeProfile.cs