Elin Decompiled Documentation: QuestCraft Class Reference
QuestCraft Class Reference
Classes
class Req
Public Member Functions
override bool CanDeliverToClient (Chara c)
override bool Deliver (Chara c, Thing t=null)
void OnProgressComplete ()
override void OnDropReward ()
override void OnComplete ()
override string GetTextProgress ()
override string GetDetailText (bool onJournal=false)
override string GetTalkProgress ()
override string GetTalkComplete ()
Public Member Functions inherited from Quest
virtual Thing GetDestThing ()
virtual int GetExtraMoney ()
virtual int GetRewardPlat (int money)
override bool Equals (object obj)
virtual bool IsVisibleOnQuestBoard ()
virtual bool CanStartQuest ()
virtual bool CanUpdateOnTalk (Chara c)
virtual Zone CreateInstanceZone (Chara c)
virtual bool UpdateOnTalk ()
void Init ()
virtual void OnInit ()
Quest SetClient (Chara c, bool assignQuest=true)
void SetTask (QuestTask _task)
void Start ()
virtual void OnStart ()
virtual void OnEnterZone ()
virtual void OnClickQuest ()
void Fail ()
virtual void OnFail ()
virtual void ShowCompleteText ()
void Complete ()
virtual void OnBeforeComplete ()
virtual void OnDropReward ()
Thing DropReward (string id)
Thing DropReward (Thing t)
virtual void OnComplete ()
void CompleteTask ()
virtual void OnCompleteTask ()
virtual void OnGiveItem (Chara c, Thing t)
virtual void OnKillChara (Chara c)
virtual void OnModKarma (int a)
void NextPhase ()
void ChangePhase (int a)
virtual void OnChangePhase (int a)
string Parse (string s)
virtual string GetTitle ()
virtual string GetTrackerText ()
virtual string GetDetail (bool onJournal=false)
virtual string GetDetailText (bool onJournal=false)
virtual string GetTextProgress ()
string GetRewardText ()
virtual string GetTalkProgress ()
virtual string GetTalkComplete ()
void UpdateJournal ()
virtual bool IsDeliverTarget (Chara c)
virtual bool CanDeliverToClient (Chara c)
virtual bool CanDeliverToBox (Thing t)
virtual bool Deliver (Chara c, Thing t=null)
Public Attributes
List< Req > req1 = new List<Req>()
List< Req > req2 = new List<Req>()
int progress
Public Attributes inherited from Quest
string id
int uid
int uidClientZone
int phase
int lv
int deadline
int difficulty
int rewardMoney
int bonusMoney
int startDate
int dangerLv
bool isNew
bool isComplete
bool track
Person person
QuestTask task
RefChara refChara = new RefChara()
Properties
bool ConsumeGoods [get]
List< Req > CurrentReq [get]
bool hasSecondReq [get]
Properties inherited from Quest
Zone ClientZone [get]
Chara chara [get]
virtual SourceQuest.Row source [get]
bool Confetti [get]
bool IsExpired [get]
int Hours [get]
string TextDeadline [get]
virtual bool HasDLC [get]
virtual string idSource [get]
virtual string RewardSuffix [get]
virtual bool FameContent [get]
virtual string TextExtra [get]
virtual string TextExtra2 [get]
virtual int DangerLv [get]
virtual int AffinityGain [get]
virtual int BaseMoney [get]
virtual int KarmaOnFail [get]
virtual bool CanAbandon [get]
virtual int FameOnComplete [get]
virtual int RangeDeadLine [get]
virtual bool UseInstanceZone [get]
virtual bool ForbidTeleport [get]
virtual bool TrackOnStart [get]
virtual bool RequireClientInSameZone [get]
virtual DifficultyType difficultyType [get]
virtual Chara DestChara [get]
virtual string RefDrama1 [get]
virtual string RefDrama2 [get]
virtual string RefDrama3 [get]
virtual string RefDrama4 [get]
virtual string TitlePrefix [get]
virtual bool CanAutoAdvance [get]
virtual bool IsRandomQuest [get]
virtual string NameDeliver [get]
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Additional Inherited Members
Public Types inherited from Quest
enum DifficultyType {
Default , Deliver , Supply , Escort ,
Bulk , Meal , Farm , Music
}
enum SubReward { plat , gacha_coin , money2 , ticket_furniture }
Static Public Member Functions inherited from Quest
static Quest Create (string _id, string _idPerson=null, Chara c=null)
static List< Zone > ListDeliver ()
Static Public Member Functions inherited from EClass
static int rndSeed (int a, int seed)
static int rnd (int a)
static int curve (int a, int start, int step, int rate=75)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Static Public Attributes inherited from Quest
const int PhaseComplete = 999
Static Public Attributes inherited from EClass
static Core core
Detailed Description
Definition at line 5 of file QuestCraft.cs.
Member Function Documentation
CanDeliverToClient()
override bool QuestCraft.CanDeliverToClient (Chara c) inline virtual
Reimplemented from Quest.
Definition at line 51 of file QuestCraft.cs.
    {
        if (c.quest != this)
        {
            return false;
        }
        bool result = true;
        foreach (Req item in CurrentReq)
        {
            Thing thing = EClass.pc.things.Find(item.idThing);
            if (thing == null || thing.Num < item.num)
            {
                result = false;
                break;
            }
        }
        return result;
    }
References CurrentReq, ThingContainer.Find(), item, Card.Num, EClass.pc, Chara.quest, and Card.things.
Referenced by Deliver().
Deliver()
override bool QuestCraft.Deliver (Chara c, Thing t = null) inline virtual
Reimplemented from Quest.
Definition at line 70 of file QuestCraft.cs.
    {
        if (!CanDeliverToClient(c))
        {
            return false;
        }
        _ = ConsumeGoods;
        if (progress == 0 && hasSecondReq)
        {
            UpdateJournal();
        }
        else
        {
            EClass.game.quests.Complete(this);
        }
        OnProgressComplete();
        return true;
    }
References CanDeliverToClient(), QuestManager.Complete(), ConsumeGoods, EClass.game, hasSecondReq, OnProgressComplete(), progress, Game.quests, and Quest.UpdateJournal().
GetDetailText()
override string QuestCraft.GetDetailText (bool onJournal = false) inline virtual
Reimplemented from Quest.
Definition at line 155 of file QuestCraft.cs.
    {
        return source.GetDetail().Split('|')[progress];
    }
References progress, and Quest.source.
Referenced by GetTalkComplete(), and GetTalkProgress().
GetTalkComplete()
override string QuestCraft.GetTalkComplete () inline virtual
Reimplemented from Quest.
Definition at line 165 of file QuestCraft.cs.
    {
        if (progress != 1 || !hasSecondReq)
        {
            return Parse(source.GetText("talkComplete"));
        }
        return GetDetailText();
    }
References GetDetailText(), hasSecondReq, Quest.Parse(), progress, and Quest.source.
GetTalkProgress()
override string QuestCraft.GetTalkProgress () inline virtual
Reimplemented from Quest.
Definition at line 160 of file QuestCraft.cs.
    {
        return GetDetailText();
    }
References GetDetailText().
GetTextProgress()
override string QuestCraft.GetTextProgress () inline virtual
Reimplemented from Quest.
Definition at line 145 of file QuestCraft.cs.
    {
        string text = "";
        foreach (Req item in CurrentReq)
        {
            text = text + (text.IsEmpty() ? "" : Environment.NewLine) + "progressShowSupply".lang(EClass.sources.things.map[item.idThing].GetName(item.num));
        }
        return text;
    }
References CurrentReq, item, EClass.sources, and SourceManager.things.
OnComplete()
override void QuestCraft.OnComplete () inline virtual
Reimplemented from Quest.
Definition at line 125 of file QuestCraft.cs.
    {
        string text = id;
        if (!(text == "ash1"))
        {
            if (text == "fiama1")
            {
                QuestCraft obj = Quest.Create("fiama2") as QuestCraft;
                obj.SetClient(base.chara);
                obj.req1.Add(new Req("torch_held", 1));
            }
        }
        else
        {
            QuestCraft obj2 = Quest.Create("ash2") as QuestCraft;
            obj2.SetClient(base.chara);
            obj2.req1.Add(new Req("torch_held", 1));
        }
    }
References Quest.Create(), Quest.id, req1, and Quest.SetClient().
OnDropReward()
override void QuestCraft.OnDropReward () inline virtual
Reimplemented from Quest.
Definition at line 109 of file QuestCraft.cs.
    {
        string text = id;
        if (!(text == "fiama1"))
        {
            if (text == "ash1")
            {
                DropReward(ThingGen.Create("crimAle"));
            }
        }
        else
        {
            DropReward(ThingGen.Create("crimAle"));
        }
    }
References ThingGen.Create(), Quest.DropReward(), and Quest.id.
OnProgressComplete()
void QuestCraft.OnProgressComplete () inline
Definition at line 89 of file QuestCraft.cs.
    {
        if (progress == 0)
        {
            string text = id;
            if (!(text == "fiama1"))
            {
                if (text == "ash1")
                {
                    EClass._zone.AddCard(ThingGen.Create("string"), EClass.pc.pos);
                }
            }
            else
            {
                EClass._zone.AddCard(ThingGen.Create("water"), EClass.pc.pos);
            }
        }
        progress++;
    }
References EClass._zone, Zone.AddCard(), ThingGen.Create(), Quest.id, EClass.pc, Card.pos, and progress.
Referenced by Deliver().
Member Data Documentation
progress
int QuestCraft.progress
Definition at line 33 of file QuestCraft.cs.
Referenced by Deliver(), GetDetailText(), GetTalkComplete(), and OnProgressComplete().
req1
List<Req> QuestCraft.req1 = new List<Req>()
Definition at line 27 of file QuestCraft.cs.
Referenced by QuestManager.AddQuestAsh(), QuestManager.AddQuestFiama(), and OnComplete().
req2
List<Req> QuestCraft.req2 = new List<Req>()
Definition at line 30 of file QuestCraft.cs.
Referenced by QuestManager.AddQuestAsh(), and QuestManager.AddQuestFiama().
Property Documentation
ConsumeGoods
bool QuestCraft.ConsumeGoods get
Definition at line 35 of file QuestCraft.cs.
Referenced by Deliver().
CurrentReq
List<Req> QuestCraft.CurrentReq get
Definition at line 37 of file QuestCraft.cs.
    {
        get
        {
            if (progress != 0)
            {
                return req2;
            }
            return req1;
        }
    }
Referenced by CanDeliverToClient(), and GetTextProgress().
hasSecondReq
bool QuestCraft.hasSecondReq get
Definition at line 49 of file QuestCraft.cs.
Referenced by Deliver(), and GetTalkComplete().
The documentation for this class was generated from the following file:
Elin/QuestCraft.cs