Elin Decompiled Documentation: SpawnList Class Reference
SpawnList Class Reference
Public Member Functions
SpawnList (string id=null)
void Add (CardRow row)
void CreateMaster (CardFilter _filter, string parent=null)
SpawnList Filter (int lv, int levelRange=-1)
CardRow Select (int lv=-1, int levelRange=-1)
CardRow GetRandom ()
CardRow GetFirst ()
Static Public Member Functions
static SpawnList Get (string id, string parent=null, CardFilter filter=null)
Static Public Member Functions inherited from EClass
static int rnd (int a)
static int curve (int a, int start, int step, int rate=75)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Public Attributes
string id
List< CardRow > rows = new List<CardRow>()
CardFilter filter
int totalChance
Static Public Attributes
static Dictionary< string, SpawnList > allList = new Dictionary<string, SpawnList>()
static SpawnList tempList = new SpawnList()
Static Public Attributes inherited from EClass
static Core core
Additional Inherited Members
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Detailed Description
Definition at line 4 of file SpawnList.cs.
Constructor & Destructor Documentation
SpawnList()
SpawnList.SpawnList (string id = null) inline
Definition at line 38 of file SpawnList.cs.
    {
        if (!id.IsEmpty())
        {
            SourceSpawnList.Row row = EClass.sources.spawnLists.map.TryGetValue(id);
            if (row != null)
            {
                bool flag = row.type == "chara";
                CardFilter cardFilter = (flag ? ((CardFilter)new CharaFilter()) : ((CardFilter)new ThingFilter()));
                cardFilter.isChara = flag;
                cardFilter.strTag = row.tag;
                cardFilter.strFilter = row.filter;
                cardFilter.filterCategory = row.category;
                cardFilter.idCard = row.idCard;
                CreateMaster(cardFilter, row.parent);
            }
            this.id = id;
        }
    }
References SourceSpawnList.Row.category, CreateMaster(), SourceSpawnList.Row.filter, id, SourceSpawnList.Row.idCard, SourceSpawnList.Row.parent, EClass.sources, SourceManager.spawnLists, and SourceSpawnList.Row.tag.
Member Function Documentation
Add()
void SpawnList.Add (CardRow row) inline
Definition at line 58 of file SpawnList.cs.
    {
        rows.Add(row);
        totalChance += row.chance;
    }
References RenderRow.chance, rows, and totalChance.
Referenced by CreateMaster().
CreateMaster()
void SpawnList.CreateMaster (CardFilter _filter, string parent = null) inline
Definition at line 64 of file SpawnList.cs.
    {
        rows.Clear();
        totalChance = 0;
        filter = _filter;
        List<CardRow> list = (parent.IsEmpty() ? EClass.sources.cards.rows : Get(parent).rows);
        for (int i = 0; i < list.Count; i++)
        {
            CardRow cardRow = list[i];
            if (cardRow.chance > 0 && filter.Pass(cardRow))
            {
                Add(cardRow);
            }
        }
        if (!filter.idCard.IsEmpty())
        {
            string[] idCard = filter.idCard;
            foreach (string key in idCard)
            {
                CardRow row = EClass.sources.cards.map[key];
                Add(row);
            }
        }
    }
References Add(), SourceManager.cards, RenderRow.chance, filter, Get(), CardFilter.idCard, SourceCard.map, CardFilter.Pass(), rows, EClass.sources, and totalChance.
Referenced by Get(), and SpawnList().
Filter()
SpawnList SpawnList.Filter (int lv, int levelRange = -1) inline
Definition at line 89 of file SpawnList.cs.
    {
        tempList.rows.Clear();
        tempList.totalChance = 0;
        tempList.filter = filter;
        for (int i = 0; i < rows.Count; i++)
        {
            CardRow cardRow = rows[i];
            if (levelRange != -1)
            {
                if (cardRow.isChara && (cardRow as SourceChara.Row).mainElement.Length >= 2)
                {
                    SourceChara.Row obj = cardRow as SourceChara.Row;
                    bool flag = false;
                    string[] mainElement = obj.mainElement;
                    for (int j = 0; j < mainElement.Length; j++)
                    {
                        string[] array = mainElement[j].Split('/');
                        SourceElement.Row row = EClass.sources.elements.alias["ele" + array[0]];
                        if (Mathf.Abs(cardRow.LV * row.eleP / 100 - lv) < levelRange)
{
                            flag = true;
                            break;
                        }
                    }
                    if (!flag)
                    {
                        continue;
                    }
                }
                else if (Mathf.Abs(cardRow.LV - lv) >= levelRange)
                {
                    continue;
                }
            }
            else if (cardRow.LV > lv)
            {
                continue;
            }
            tempList.rows.Add(cardRow);
            tempList.totalChance += cardRow.chance;
        }
        if (tempList.rows.Count == 0)
        {
            Debug.Log("list contains no item: " + id + "/" + lv);
            return this;
        }
        return tempList;
    }
References RenderRow.chance, Debug, SourceManager.elements, SourceElement.Row.eleP, filter, CardRow.isChara, RenderRow.LV, SourceChara.Row.mainElement, rows, EClass.sources, and tempList.
Referenced by Select().
Get()
static SpawnList SpawnList.Get (string id, string parent = null, CardFilter filter = null) inline static
Definition at line 18 of file SpawnList.cs.
    {
        SpawnList spawnList = allList.TryGetValue(id);
        if (spawnList != null)
        {
            if (spawnList.filter != filter && filter != null)
            {
                spawnList.CreateMaster(filter, parent);
            }
            return spawnList;
        }
        spawnList = new SpawnList(id);
        if (filter != null)
        {
            spawnList.CreateMaster(filter, parent);
        }
        allList.Add(id, spawnList);
        return spawnList;
    }
References allList, CreateMaster(), and filter.
Referenced by ThingGen.CreateFromFilter(), CharaGen.CreateFromFilter(), CreateMaster(), Trait.CreateStock(), DNA.GenerateManiGene(), DNA.GenerateRandomGene(), SpawnListChara.Get(), SpawnListThing.Get(), Region.OnAdvanceHour(), GameDate.ShipRandomPackages(), Zone.SpawnMob(), ThingGen.TestCreate(), and Card.TryMakeRandomItem().
GetFirst()
CardRow SpawnList.GetFirst () inline
Definition at line 200 of file SpawnList.cs.
    {
        return rows[0];
    }
References rows.
GetRandom()
CardRow SpawnList.GetRandom () inline
Definition at line 195 of file SpawnList.cs.
    {
        return rows[EClass.rnd(rows.Count)];
    }
References EClass.rnd(), and rows.
Select()
CardRow SpawnList.Select (int lv = -1, int levelRange = -1) inline
Definition at line 139 of file SpawnList.cs.
    {
        if (lv != -1)
        {
            if (levelRange != -1)
            {
                for (int i = 0; i < 50; i++)
                {
                    SpawnList spawnList = Filter(lv + i - i * i, levelRange + i * i);
                    if (spawnList.rows.Count > 5)
                    {
                        return spawnList.Select();
                    }
                }
            }
            lv = lv + 2 + EClass.rnd(EClass.rnd(EClass.rnd(EClass.rnd(Mathf.Min(lv * 2, 20)) + 1) + 1) + 1);
            return Filter(lv).Select();
        }
        if (filter != null && filter.categoriesInclude.Count > 0)
        {
            SourceCategory.Row r = filter.categoriesInclude.RandomItem();
            for (int j = 0; j < 100; j++)
            {
                CardRow cardRow = _Select();
                if (cardRow != null && cardRow.Category.IsChildOf(r))
                {
                    return cardRow;
                }
            }
        }
        return _Select();
        CardRow _Select()
        {
            int num = EClass.rnd(totalChance);
            int num2 = 0;
            foreach (CardRow row in rows)
            {
                num2 += row.chance;
                if (num < num2)
                {
                    return row;
                }
            }
            if (rows.Count == 0)
            {
                Debug.Log("no item:" + id);
                foreach (CardFilter.FilterItem tag in filter.tags)
                {
                    Debug.Log(tag.name + "/" + tag.exclude);
                }
                return null;
            }
            return rows[EClass.rnd(rows.Count)];
        }
    }
References CardFilter.categoriesInclude, RenderRow.Category, RenderRow.chance, Debug, filter, Filter(), EClass.rnd(), rows, Select(), CardFilter.tags, and totalChance.
Referenced by ThingGen._Create(), ThingGen.CreateFromCategory(), CharaGen.CreateFromFilter(), ThingGen.CreateFromFilter(), ThingGen.CreateFromTag(), Trait.CreateStock(), DNA.GenerateManiGene(), DNA.GenerateRandomGene(), Select(), QuestDeliver.SetIdThing(), GameDate.ShipRandomPackages(), ThingGen.TestCreate(), Card.TryMakeRandomItem(), and SlaverData.TryRefresh().
Member Data Documentation
allList
Dictionary<string, SpawnList> SpawnList.allList = new Dictionary<string, SpawnList>() static
Definition at line 6 of file SpawnList.cs.
Referenced by Get(), and Core.ResetRuntime().
filter
CardFilter SpawnList.filter
Definition at line 14 of file SpawnList.cs.
Referenced by CreateMaster(), Filter(), Get(), and Select().
id
string SpawnList.id
Definition at line 10 of file SpawnList.cs.
Referenced by TraitCrafter.Craft(), SerializedCards.Restore(), and SpawnList().
rows
List<CardRow> SpawnList.rows = new List<CardRow>()
Definition at line 12 of file SpawnList.cs.
Referenced by Add(), CreateMaster(), Filter(), GetFirst(), GetRandom(), and Select().
tempList
SpawnList SpawnList.tempList = new SpawnList() static
Definition at line 8 of file SpawnList.cs.
Referenced by Filter().
totalChance
int SpawnList.totalChance
Definition at line 16 of file SpawnList.cs.
Referenced by Add(), CreateMaster(), and Select().
The documentation for this class was generated from the following file:
Elin/SpawnList.cs