Elin Decompiled Documentation: TaskBuild Class Reference
TaskBuild Class Reference
Public Member Functions
override bool CanManualCancel ()
bool CanRotateBlock ()
override string GetText (string str="")
override bool _CanPerformTask (Chara chara, int radius)
override void OnAdd ()
override HitResult GetHitResult ()
HitResult _GetHitResult (Point p)
override void OnProgressComplete ()
override void OnDestroy ()
override void DrawMarker (int x, int z, RenderParam p)
Public Member Functions inherited from TaskBaseBuild
bool CanPlaceCard (Point pos, Card c)
Public Member Functions inherited from TaskDesignation
virtual string GetTextOrbit ()
bool PointHasOtherDesignation ()
virtual void DrawMarker (int x, int z, RenderParam p)
virtual void Draw (int x, int z, RenderParam p)
virtual void OnEnterScreen ()
virtual void OnLeaveScreen ()
virtual void TrySpawnOrbit ()
void DespawnOrbit ()
Public Member Functions inherited from TaskPoint
override bool CanManualCancel ()
override bool CanPerform ()
override bool _CanPerformTask (Chara chara, int radius)
override IEnumerable< Status > Run ()
void OnInspect ()
void WriteNote (UINote n, Action< UINote > onWriteNote=null, IInspect.NoteMode mode=IInspect.NoteMode.Default, Recipe recipe=null)
Public Member Functions inherited from Task
virtual HitResult GetHitResult ()
override void OnSuccess ()
void TryLater (int min=30)
Status Destroy ()
virtual void OnDestroy ()
override Status Cancel ()
override void OnReset ()
override bool CanProgress ()
bool CanPerformTask (Chara chara, int radius)
virtual bool _CanPerformTask (Chara chara, int radius)
virtual void OnAdd ()
void ToggleSuspend ()
Public Member Functions inherited from AIAct
override string ToString ()
override MultiSprite GetStateIcon ()
virtual bool ShouldAllyAttack (Chara tg)
virtual Point GetDestination ()
AIProgress GetProgress ()
string GetCurrentActionText ()
override bool IsToolValid ()
virtual void OnStart ()
void SetOwner (Chara c)
virtual void OnSetOwner ()
void SetChild (AIAct seq, Func< Status > _onChildFail=null)
void Start ()
override bool Perform ()
Status Restart ()
Status Success (Action action=null)
virtual void OnSuccess ()
bool TryCancel (Card c)
virtual Status Cancel ()
virtual void OnCancel ()
virtual void OnCancelOrSuccess ()
virtual bool CanManualCancel ()
Status KeepRunning ()
void Reset ()
virtual void OnReset ()
Status Tick ()
virtual IEnumerable< Status > Run ()
Status TickChild ()
Status Do (AIAct _seq, Func< Status > _onChildFail=null)
Status DoGotoInteraction (Point pos, Func< Status > _onChildFail=null)
Status DoGoto (Point pos, int dist=0, bool ignoreConnection=false, Func< Status > _onChildFail=null)
Status DoGoto (Card card, Func< Status > _onChildFail=null)
Status DoGoto (Card card, int dist, Func< Status > _onChildFail=null)
Status DoGotoSpot (Card card, Func< Status > _onChildFail=null)
Status DoGoto< T > (Func< Status > _onChildFail=null)
Status DoGotoSpot< T > (Func< Status > _onChildFail=null, bool ignoreAccessType=false)
Status DoGrab (Card card, int num=-1, bool pickHeld=false, Func< Status > _onChildFail=null)
Status DoGrab< T > ()
Status DoProgress ()
Status DoIdle (int repeat=3)
Status DoWait (int count=1)
virtual AIProgress CreateProgress ()
virtual void OnCreateProgress (Progress_Custom p)
virtual bool CanProgress ()
virtual void OnBeforeProgress ()
virtual void OnProgress ()
virtual void OnProgressComplete ()
void SimulateZone (int days)
virtual void OnSimulateZone (int days)
virtual void OnSimulatePosition ()
Public Member Functions inherited from Act
virtual CursorInfo GetCursorIcon (Card c)
virtual MultiSprite GetStateIcon ()
override Sprite GetSprite ()
virtual bool ShowMouseHint (Card c)
virtual bool IsValidTC (Card c)
virtual string GetHintText (string str="")
virtual string GetText (string str="")
virtual string GetTextSmall (Card c)
bool IsTargetHostileParty ()
virtual Color GetActPlanColor ()
virtual bool Perform ()
virtual bool CanPerform ()
bool Perform (Chara _cc, Card _tc=null, Point _tp=null)
bool CanPerform (Chara _cc, Card _tc=null, Point _tp=null)
virtual bool IsToolValid ()
new void SetImage (Image image)
virtual void OnMarkMapHighlights ()
virtual bool ShouldMapHighlight (Point p)
Public Member Functions inherited from Element
virtual SourceElement.Row GetSource ()
virtual int GetSourcePotential (int v)
virtual Sprite GetSprite ()
int GetMaterialSourceValue (Thing t, int v)
virtual int GetSourceValue (int v, int lv, SourceValueType type)
virtual Sprite GetIcon (string suffix="")
bool IsActive (Card c)
int SortVal (bool charaSheet=false)
virtual bool CanLink (ElementContainer owner)
bool HasTag (string tag)
void SetImage (Image i)
virtual string GetDetail ()
bool IsFactionElement (Chara c)
Element GetParent (Card c)
void WriteNote (UINote n, ElementContainer owner=null, Action< UINote > onWriteNote=null)
void WriteNoteWithRef (UINote n, ElementContainer owner, Action< UINote > onWriteNote, Element refEle)
void _WriteNote (UINote n, Chara c, Act act)
void AddHeaderAbility (UINote n)
void _WriteNote (UINote n, ElementContainer owner, Action< UINote > onWriteNote, bool isRef, bool addHeader=true)
void AddEncNote (UINote n, Card Card, ElementContainer.NoteMode mode=ElementContainer.NoteMode.Default, Func< Element, string, string > funcText=null, Action< UINote, Element > onAddNote=null)
virtual void OnWriteNote (UINote n, ElementContainer owner)
virtual void OnChangeValue ()
void CheckLevelBonus (ElementContainer owner, UINote n=null)
int GetSortVal (UIList.SortMode m)
virtual Act.Cost GetCost (Chara c)
virtual int GetPower (Card c)
virtual void SetTextValue (UIText text)
virtual bool IsPurchaseFeatReqMet (ElementContainer owner, int lv=-1)
virtual void WritePurchaseReq (UINote n, int lv=1)
void WriteNote (UINote n, Action< UINote > onWriteNote=null, NoteMode mode=NoteMode.Default, Recipe recipe=null)
void OnInspect ()
void OnEnterScreen ()
void OnLeaveScreen ()
Public Attributes
Recipe recipe
int dir
int bridgeHeight
int altitude
List< Thing > resources = new List<Thing>()
int[] reqs
Card held
float fx
float fy
bool freePos
bool disableRotateBlock
Card target
Point lastPos
Public Attributes inherited from TaskDesignation
long sync
bool isSynced
TCOrbitTask orbit
Public Attributes inherited from TaskPoint
Point pos = new Point()
bool isRepeated
Public Attributes inherited from Task
TaskList taskList
bool isDestroyed
int nextTry
bool suspended
Public Attributes inherited from AIAct
new Chara owner
Status status
IEnumerator< Status > Enumerator
AIAct child
AIAct parent
byte restartCount
Func< Status > onChildFail
Func< bool > isFail
Public Attributes inherited from Element
SourceElement.Row _source
int id
int vBase
int vExp
int vPotential
int vTempPotential
int vLink
int vSource
int vSourcePotential
ElementContainer owner
Properties
override int destDist [get]
override bool CanPressRepeat [get]
override bool HasProgress [get]
override bool destIgnoreConnection [get]
bool useHeld [get]
override int W [get]
override int H [get]
override bool isBlock [get]
Properties inherited from TaskDesignation
override bool HasProgress [get]
virtual int idMarker [get]
virtual int W [get]
virtual int H [get]
virtual bool ShowOrbit [get]
virtual bool Working [get]
override bool ShowAuto [get]
override CursorInfo CursorIcon [get]
TaskManager.Designations Designations [get]
long Sync [get]
Properties inherited from TaskPoint
override bool HasProgress [get]
virtual int destDist [get]
virtual bool destIgnoreConnection [get]
virtual bool isBlock [get]
virtual bool Loop [get]
bool CanInspect [get]
string InspectName [get]
Point InspectPoint [get]
Vector3 InspectPosition [get]
Properties inherited from Task
override TargetType TargetType [get]
Properties inherited from AIAct
virtual bool IsRunning [get]
bool IsChildRunning [get]
bool IsMoveAI [get]
virtual int MaxRestart [get]
virtual new string Name [get]
virtual MultiSprite stateIcon [get]
virtual Sprite actionIcon [get]
virtual bool IsNoGoal [get]
virtual bool IsAutoTurn [get]
virtual bool IsIdle [get]
virtual bool CancelOnAggro [get]
virtual bool PushChara [get]
virtual int MaxProgress [get]
virtual bool ShowProgress [get]
virtual bool UseTurbo [get]
virtual int CurrentProgress [get]
virtual bool ShowCursor [get]
virtual bool CancelWhenDamaged [get]
virtual bool CancelWhenMoved [get]
virtual bool InformCancel [get]
virtual Thing RenderThing [get]
AIAct Current [get]
override bool IsAct [get]
override bool ShowPotential [get]
override bool UsePotential [get]
override bool ShowRelativeAttribute [get]
virtual bool HasProgress [get]
Properties inherited from Act
override bool ShowPotential [get]
override bool UsePotential [get]
override bool ShowRelativeAttribute [get]
virtual CursorInfo CursorIcon [get]
virtual string ID [get]
virtual bool IsAct [get]
virtual bool WillEndTurn [get]
virtual bool CloseLayers [get]
virtual int LeftHand [get]
virtual int RightHand [get]
virtual int ElementPowerMod [get]
virtual bool ShowMapHighlight [get]
virtual bool ShowMapHighlightBlock [get]
virtual bool PickHeldOnStart [get]
virtual bool DropHeldOnStart [get]
virtual bool CanPressRepeat [get]
virtual bool CanAutofire [get]
virtual bool ResetAxis [get]
virtual bool RequireTool [get]
virtual bool IsHostileAct [get]
virtual bool HideRightInfo [get]
virtual bool HaveLongPressAction [get]
virtual float Radius [get]
virtual int PerformDistance [get]
virtual int MaxRadius [get]
virtual TargetType TargetType [get]
virtual bool LocalAct [get]
virtual bool CanRapidFire [get]
virtual float RapidDelay [get]
virtual bool ShowAuto [get]
virtual bool IsCrime [get]
Properties inherited from Element
SourceElement.Row source [get]
virtual int DisplayValue [get]
virtual int MinValue [get]
int Value [get]
int ValueWithoutLink [get]
virtual int MinPotential [get]
int Potential [get]
virtual bool CanGainExp [get]
bool IsFlag [get]
virtual string Name [get]
virtual string FullName [get]
virtual int ExpToNext [get]
virtual bool UseExpMod [get]
virtual int CostTrain [get]
virtual int CostLearn [get]
virtual bool ShowXP [get]
virtual bool ShowMsgOnValueChanged [get]
virtual bool ShowValue [get]
virtual bool ShowPotential [get]
virtual bool UsePotential [get]
virtual bool PotentialAsStock [get]
virtual bool ShowRelativeAttribute [get]
virtual bool ShowBonuses [get]
virtual string ShortName [get]
bool IsGlobalElement [get]
bool IsFactionWideElement [get]
bool IsPartyWideElement [get]
virtual bool ShowEncNumber [get]
bool IsTrait [get]
bool IsFoodTrait [get]
bool IsFoodTraitMain [get]
bool IsMainAttribute [get]
Act act [get]
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Properties inherited from IInspect
bool CanInspect [get]
string InspectName [get]
Point InspectPoint [get]
Vector3 InspectPosition [get]
Properties inherited from ISyncScreen
long Sync [get]
Additional Inherited Members
Public Types inherited from AIAct
enum Status { Running , Fail , Success }
Public Types inherited from Act
enum CostType { None , MP , SP }
Public Types inherited from IInspect
enum NoteMode { Default , Recipe , Product , Info }
Static Public Member Functions inherited from Act
static void SetReference (Chara _cc, Card _tc=null, Point _tp=null)
static void SetTool (Thing t)
Static Public Member Functions inherited from Element
static string GetName (string alias)
static SourceElement.Row Get (int id)
static Dictionary< int, int > GetElementMap (int[] list)
static Dictionary< int, int > GetElementMap (int[] list, Dictionary< int, int > map)
static SourceElement.Row GetRandomElement (int lv=1, bool useWeight=true)
static Element Create (int id, int v=0)
static Element Create (string id, int v=1)
static int GetId (string alias)
static int GetResistLv (int v)
static int GetResistDamage (int dmg, int v, int power=0)
Static Public Member Functions inherited from EClass
static int rndSeed (int a, int seed)
static int rnd (long a)
static int rnd (int a)
static int curve (int a, int start, int step, int rate=75)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Static Public Attributes inherited from Act
static Chara CC
static Card TC
static Point TP = new Point()
static Thing TOOL
static int powerMod = 100
static bool forcePt
static Act CurrentAct
Static Public Attributes inherited from Element
const int Div = 5
static Element Void = new Element()
static int[] List_MainAttributes = new int[9] { 70, 72, 71, 77, 74, 75, 76, 73, 79 }
static int[] List_MainAttributesMajor = new int[8] { 70, 72, 71, 77, 74, 75, 76, 73 }
static int[] List_Body = new int[4] { 70, 72, 71, 77 }
static int[] List_Mind = new int[4] { 74, 75, 76, 73 }
static List< SourceElement.Row > ListElements = new List<SourceElement.Row>()
static List< SourceElement.Row > ListAttackElements = new List<SourceElement.Row>()
Static Public Attributes inherited from EClass
static Core core
Detailed Description
Definition at line 5 of file TaskBuild.cs.
Member Function Documentation
_CanPerformTask()
override bool TaskBuild._CanPerformTask (Chara chara, int radius) inline virtual
Reimplemented from Task.
Definition at line 122 of file TaskBuild.cs.
    {
        Recipe.Ingredient ingredient = recipe.ingredients[0];
        if (!ingredient.IsThingSpecified && ingredient.thing == null)
        {
            ingredient.thing = EClass._map.Stocked.Find(ingredient.id, ingredient.mat, ingredient.refVal);
            if (ingredient.thing == null)
            {
                TryLater();
                return false;
            }
        }
        return true;
    }
References EClass._map, Props.Find(), Recipe.Ingredient.id, Recipe.ingredients, Recipe.Ingredient.IsThingSpecified, Recipe.Ingredient.mat, recipe, Recipe.Ingredient.refVal, Map.Stocked, Recipe.Ingredient.thing, and Task.TryLater().
_GetHitResult()
HitResult TaskBuild._GetHitResult (Point p) inline
Definition at line 248 of file TaskBuild.cs.
    {
        if (useHeld)
        {
            if (EClass.pc.held == null || EClass.pc.held.isDestroyed)
            {
                return HitResult.Invalid;
            }
            if (p.Installed != null)
            {
                if (p.Installed.trait is TraitSeed && !(EClass.pc.held.trait is TraitFertilizer))
                {
                    return HitResult.Invalid;
                }
                if (EClass.pc.held.trait is TraitFertilizer && p.Things.LastItem().trait is TraitFertilizer)
                {
                    return HitResult.Invalid;
                }
                if (EClass.pc.held.trait is TraitSeed)
                {
                    foreach (Thing thing in p.Things)
                    {
                        if (thing.trait is TraitSeed)
{
                            return HitResult.Invalid;
                        }
                    }
                }
            }
        }
        return recipe.tileType._HitTest(p, recipe.Mold);
    }
References TileType._HitTest(), Chara.held, Point.Installed, Card.isDestroyed, Recipe.Mold, EClass.pc, recipe, Point.Things, Recipe.tileType, Card.trait, and useHeld.
Referenced by GetHitResult().
CanManualCancel()
override bool TaskBuild.CanManualCancel () inline virtual
Reimplemented from AIAct.
Definition at line 69 of file TaskBuild.cs.
    {
        return true;
    }
CanRotateBlock()
bool TaskBuild.CanRotateBlock () inline
Definition at line 74 of file TaskBuild.cs.
    {
        if (!EInput.rightMouse.pressing)
        {
            disableRotateBlock = false;
        }
        if (useHeld && EClass.pc.held != null)
        {
            if (EClass._zone.IsRegion)
            {
                return false;
            }
            if (!(EClass._zone is Zone_Tent) && !EClass._zone.IsPCFactionOrTent && EClass.pc.held.trait.CanBeOnlyBuiltInHome)
            {
                return false;
            }
            if (EClass._zone.RestrictBuild && !EClass.pc.held.trait.CanBuildInTown)
            {
                return false;
            }
            if (EClass.pc.held.trait is TraitBlock && pos.HasBlock && !EClass.pc.held.trait.IsDoor && !disableRotateBlock)
            {
                return true;
            }
        }
        return false;
    }
References EClass._zone, Trait.CanBeOnlyBuiltInHome, Trait.CanBuildInTown, disableRotateBlock, Point.HasBlock, Chara.held, Trait.IsDoor, Zone.IsPCFactionOrTent, Spatial.IsRegion, EClass.pc, TaskPoint.pos, ButtonState.pressing, Zone.RestrictBuild, EInput.rightMouse, Card.trait, and useHeld.
Referenced by GetHitResult(), GetText(), and OnProgressComplete().
DrawMarker()
override void TaskBuild.DrawMarker (int x, int z, RenderParam p) inline virtual
Reimplemented from TaskDesignation.
Definition at line 398 of file TaskBuild.cs.
    {
        recipe.OnRenderMarker(Point.shared.Set(x, z), owner != null, HitResult.Default, x == pos.x && z == pos.z, dir, bridgeHeight + altitude);
    }
References altitude, bridgeHeight, dir, Recipe.OnRenderMarker(), AIAct.owner, TaskPoint.pos, recipe, Point.Set(), Point.shared, Point.x, and Point.z.
GetHitResult()
override HitResult TaskBuild.GetHitResult () inline virtual
Reimplemented from Task.
Definition at line 149 of file TaskBuild.cs.
    {
        if (!pos.IsValid || ((useHeld ? (!pos.IsInBounds) : (!pos.IsInBoundsPlus)) && !EClass.debug.ignoreBuildRule))
        {
            return HitResult.Invalid;
        }
        if (recipe == null)
        {
            Debug.Log("recipe is null");
            return HitResult.Invalid;
        }
        if (useHeld)
        {
            if (EClass.pc.held == null || EClass.pc.held.GetRootCard() != EClass.pc || EClass.pc.held != held)
            {
                return HitResult.Invalid;
            }
            if (EClass.pc.held.TileType.IsBlockPass && pos.HasChara && pos.FirstChara.IsHostile(EClass.pc))
            {
                return HitResult.Invalid;
            }
            if (CanRotateBlock())
            {
                return HitResult.Valid;
            }
            if (pos.HasBlock && EClass.pc.held.TileType.IsDoor && pos.HasWallOrFence && pos.cell.blockDir != 2)
            {
                recipe.SetDir((pos.cell.blockDir != 0) ? 1 : 0);
            }
            if (!EClass.debug.ignoreBuildRule && !EClass._zone.IsPCFaction)
            {
                if (!(EClass._zone is Zone_Tent) && !EClass._zone.IsPCFactionOrTent && EClass.pc.held.trait.CanBeOnlyBuiltInHome)
                {
                    return HitResult.Invalid;
                }
                if (EClass._zone.RestrictBuild && !EClass.pc.held.trait.CanBuildInTown)
                {
                    return HitResult.Invalid;
                }
            }
        }
        if (lastPos != null)
        {
            if (recipe.IsBlock && lastPos.x != pos.x && lastPos.z != pos.z)
            {
                return HitResult.Invalid;
            }
            if (recipe.IsWallOrFence && ((recipe._dir == 0 && pos.z != lastPos.z) || (recipe._dir == 1 && pos.x != lastPos.x)))
            {
                return HitResult.Invalid;
            }
        }
        if (0 == 0 && recipe.HasSameTile(pos, recipe._dir, altitude, bridgeHeight))
        {
            return HitResult.Default;
        }
        if (recipe.IsThing)
        {
            if (recipe.renderRow is CardRow cardRow && !CanPlaceCard(pos, cardRow.model))
            {
                return HitResult.Invalid;
            }
            if (recipe.MultiSize && useHeld)
            {
                Point point = new Point();
                for (int i = 0; i < H; i++)
                {
                    for (int j = 0; j < W; j++)
                    {
                        point.Set(pos.x - j, pos.z + i);
                        if (!point.IsValid)
{
                            return HitResult.Invalid;
                        }
                        HitResult hitResult = _GetHitResult(point);
                        if (hitResult != HitResult.Valid && hitResult != HitResult.Warning)
{
                            return HitResult.Invalid;
                        }
                    }
                }
                return HitResult.Valid;
            }
        }
        if (recipe.IsWallOrFence && pos.HasWallOrFence && AM_Adv.actCount == 0 && recipe._dir != pos.cell.blockDir)
        {
            return HitResult.Valid;
        }
        if (!useHeld && EClass.debug.ignoreBuildRule)
        {
            return HitResult.Valid;
        }
        if (EClass.scene.actionMode.IsRoofEditMode())
        {
            return HitResult.Valid;
        }
        return _GetHitResult(pos);
    }
References Recipe._dir, _GetHitResult(), EClass._zone, AM_Adv.actCount, Scene.actionMode, altitude, Cell.blockDir, bridgeHeight, Trait.CanBeOnlyBuiltInHome, Trait.CanBuildInTown, TaskBaseBuild.CanPlaceCard(), CanRotateBlock(), Point.cell, EClass.debug, Debug, Point.FirstChara, Card.GetRootCard(), H, Point.HasBlock, Point.HasChara, Recipe.HasSameTile(), Point.HasWallOrFence, Chara.held, held, CoreDebug.ignoreBuildRule, Point.Invalid, Recipe.IsBlock, TileType.IsBlockPass, TileType.IsDoor, Chara.IsHostile(), Point.IsInBounds, Point.IsInBoundsPlus, Zone.IsPCFaction, Zone.IsPCFactionOrTent, ActionMode.IsRoofEditMode(), Recipe.IsThing, Point.IsValid, Recipe.IsWallOrFence, lastPos, Recipe.MultiSize, EClass.pc, TaskPoint.pos, recipe, Recipe.renderRow, Zone.RestrictBuild, EClass.scene, Point.Set(), Recipe.SetDir(), Card.TileType, Card.trait, useHeld, W, Point.x, and Point.z.
GetText()
override string TaskBuild.GetText (string str = "") inline virtual
Reimplemented from Act.
Definition at line 102 of file TaskBuild.cs.
    {
        if (CanRotateBlock())
        {
            return "actRotateWall".lang();
        }
        if (useHeld && EClass.pc.held != null)
        {
            if (EClass.pc.held.category.id == "seed")
            {
                return "actInstallSeed".lang();
            }
            if (EClass.pc.held.id == "fertilizer")
            {
                return "actInstallFertilizer".lang();
            }
        }
        return base.GetText(str);
    }
References CanRotateBlock(), Card.category, Chara.held, Card.id, EClass.pc, and useHeld.
OnAdd()
override void TaskBuild.OnAdd () inline virtual
Reimplemented from Task.
Definition at line 137 of file TaskBuild.cs.
    {
        if (reqs == null)
        {
            reqs = new int[recipe.ingredients.Count];
            for (int i = 0; i < recipe.ingredients.Count; i++)
            {
                reqs[i] = recipe.ingredients[i].req;
            }
        }
    }
References Recipe.ingredients, recipe, and reqs.
OnDestroy()
override void TaskBuild.OnDestroy () inline virtual
Reimplemented from Task.
Definition at line 390 of file TaskBuild.cs.
    {
        foreach (Thing resource in resources)
        {
            EClass._zone.AddCard(resource, pos);
        }
    }
References EClass._zone, Zone.AddCard(), TaskPoint.pos, resource, and resources.
OnProgressComplete()
override void TaskBuild.OnProgressComplete () inline virtual
Reimplemented from AIAct.
Definition at line 281 of file TaskBuild.cs.
    {
        if (useHeld)
        {
            if (EClass.pc.held == null || EClass.pc.held.GetRootCard() != EClass.pc || pos.Distance(EClass.pc.pos) > 1 || !pos.IsInBounds)
            {
                return;
            }
            if (CanRotateBlock())
            {
                SE.Rotate();
                pos.cell.RotateBlock(1);
                disableRotateBlock = true;
                return;
            }
            disableRotateBlock = true;
            ActionMode.Build.FixBridge(pos, recipe);
            bridgeHeight = ActionMode.Build.bridgeHeight;
            target = (EClass.pc.held.category.installOne ? EClass.pc.held.Split(1) : EClass.pc.held);
            if (target.trait is TraitTile)
            {
                target.ModNum(-1);
            }
            dir = recipe._dir;
            EClass.pc.LookAt(pos);
            EClass.pc.renderer.PlayAnime(AnimeID.Attack_Place, pos);
            if (target.id == "statue_weird")
            {
                EClass.pc.Say("statue_install");
            }
        }
        lastPos = pos.Copy();
        if (ActionMode.Build.IsActive && ActionMode.Build.IsFillMode())
        {
            if (recipe.IsBridge)
            {
                dir = pos.cell.floorDir;
                bridgeHeight = pos.cell.bridgeHeight;
                altitude = 0;
            }
            else if (recipe.IsFloor)
            {
                dir = pos.cell.floorDir;
            }
            else if (recipe.IsBlock)
            {
                dir = pos.cell.blockDir;
            }
        }
        else
        {
            Effect.Get("smoke").Play(pos);
            Effect.Get("mine").Play(pos).SetParticleColor(recipe.GetColorMaterial().GetColor())
                .Emit(10 + EClass.rnd(10));
            if (recipe.IsWallOrFence)
            {
                if (pos.HasWallOrFence && pos.cell.blockDir != 2 && pos.cell.blockDir != recipe._dir)
                {
                    pos.cell.blockDir = 2;
                    EClass.pc.PlaySound(pos.matBlock.GetSoundImpact());
                    pos.RefreshTile();
                    return;
                }
                if (pos.sourceRoofBlock.tileType.IsWallOrFence && pos.cell._roofBlockDir % 4 != 2 && pos.cell._roofBlockDir % 4 != recipe._dir)
                {
                    pos.cell._roofBlockDir = (byte)(pos.cell._roofBlockDir / 4 * 4 + 2);
                    EClass.pc.PlaySound(pos.matBlock.GetSoundImpact());
                    pos.RefreshTile();
                    return;
                }
            }
        }
        if (bridgeHeight > 150)
        {
            bridgeHeight = 150;
        }
        recipe.Build(this);
        resources.Clear();
        EClass.player.flags.OnBuild(recipe);
        EClass._map.RefreshShadow(pos.x, pos.z);
        EClass._map.RefreshShadow(pos.x, pos.z - 1);
        EClass._map.RefreshFOV(pos.x, pos.z);
        EClass.pc.renderer.SetFirst(first: true);
        if (recipe.IsFloor)
        {
            foreach (Card item in pos.ListThings<TraitNewZone>())
            {
                _ = (item.trait as TraitNewZone).IsDownstairs;
            }
        }
        if (!ActionMode.Build.IsActive || !ActionMode.Build.IsRoofEditMode())
        {
            pos.ForeachMultiSize(recipe.W, recipe.H, delegate(Point p, bool center)
            {
                if (p.IsBlocked && p.HasChara)
                {
                    foreach (Chara item2 in p.ListCharas())
                    {
                        EClass.pc.Kick(item2, ignoreSelf: true, karmaLoss: false, show: false);
                    }
                }
            });
        }
        if (EClass.game.IsSurvival && EClass._zone is Zone_StartSiteSky)
        {
            EClass.game.survival.OnExpandFloor(pos);
        }
    }
References Recipe._dir, EClass._map, Cell._roofBlockDir, EClass._zone, altitude, Cell.blockDir, AM_Build.bridgeHeight, Cell.bridgeHeight, bridgeHeight, ActionMode.Build, Recipe.Build(), CanRotateBlock(), Point.cell, Point.Copy(), dir, disableRotateBlock, Point.Distance(), AM_Build.FixBridge(), Player.flags, Cell.floorDir, Point.ForeachMultiSize(), EClass.game, Effect.Get(), Recipe.GetColorMaterial(), Card.GetRootCard(), Recipe.H, Point.HasChara, Point.HasWallOrFence, Chara.held, Card.id, Recipe.IsBlock, Point.IsBlocked, Recipe.IsBridge, AM_Build.IsFillMode(), Recipe.IsFloor, Point.IsInBounds, AM_Build.IsRoofEditMode(), Game.IsSurvival, Recipe.IsWallOrFence, item, Chara.Kick(), lastPos, Point.ListCharas(), Chara.LookAt(), Point.matBlock, Card.ModNum(), Player.Flags.OnBuild(), SurvivalManager.OnExpandFloor(), EClass.pc, Effect.Play(), CardRenderer.PlayAnime(), EClass.player, Card.PlaySound(), Card.pos, TaskPoint.pos, recipe, Map.RefreshFOV(), Map.RefreshShadow(), Point.RefreshTile(), Card.renderer, resources, EClass.rnd(), Cell.RotateBlock(), Card.Say(), CardRenderer.SetFirst(), Point.sourceRoofBlock, Card.Split(), Game.survival, target, Card.trait, useHeld, Recipe.W, Point.x, and Point.z.
Member Data Documentation
altitude
int TaskBuild.altitude
Definition at line 17 of file TaskBuild.cs.
Referenced by Recipe.Build(), RecipeCard.Build(), DrawMarker(), GetHitResult(), and OnProgressComplete().
bridgeHeight
int TaskBuild.bridgeHeight
Definition at line 14 of file TaskBuild.cs.
Referenced by Recipe.Build(), RecipeCard.Build(), DrawMarker(), GetHitResult(), and OnProgressComplete().
dir
int TaskBuild.dir
Definition at line 11 of file TaskBuild.cs.
Referenced by Recipe.Build(), RecipeCard.Build(), DrawMarker(), and OnProgressComplete().
disableRotateBlock
bool TaskBuild.disableRotateBlock
Definition at line 33 of file TaskBuild.cs.
Referenced by CanRotateBlock(), and OnProgressComplete().
freePos
bool TaskBuild.freePos
Definition at line 31 of file TaskBuild.cs.
fx
float TaskBuild.fx
Definition at line 27 of file TaskBuild.cs.
fy
float TaskBuild.fy
Definition at line 29 of file TaskBuild.cs.
held
Card TaskBuild.held
Definition at line 25 of file TaskBuild.cs.
Referenced by GetHitResult().
lastPos
Point TaskBuild.lastPos
Definition at line 37 of file TaskBuild.cs.
Referenced by GetHitResult(), and OnProgressComplete().
recipe
Recipe TaskBuild.recipe
Definition at line 8 of file TaskBuild.cs.
Referenced by _CanPerformTask(), _GetHitResult(), AM_Adv._OnUpdateInput(), Recipe.Build(), DrawMarker(), GetHitResult(), OnAdd(), OnProgressComplete(), HotItemHeld.OnRenderTile(), and HotItemHeld.TrySetAct().
reqs
int [] TaskBuild.reqs
Definition at line 23 of file TaskBuild.cs.
Referenced by OnAdd().
resources
List<Thing> TaskBuild.resources = new List<Thing>()
Definition at line 20 of file TaskBuild.cs.
Referenced by RecipeCard.Build(), OnDestroy(), and OnProgressComplete().
target
Card TaskBuild.target
Definition at line 35 of file TaskBuild.cs.
Referenced by RecipeCard.Build(), and OnProgressComplete().
Property Documentation
CanPressRepeat
override bool TaskBuild.CanPressRepeat get
Definition at line 41 of file TaskBuild.cs.
    {
        get
        {
            if (useHeld)
            {
                if (EClass.pc.held != null)
                {
                    return EClass.pc.held.trait.CanExtendBuild;
                }
                return false;
            }
            return false;
        }
    }
destDist
override int TaskBuild.destDist get
Definition at line 39 of file TaskBuild.cs.
destIgnoreConnection
override bool TaskBuild.destIgnoreConnection get
Definition at line 59 of file TaskBuild.cs.
H
override int TaskBuild.H get
Definition at line 65 of file TaskBuild.cs.
Referenced by GetHitResult().
HasProgress
override bool TaskBuild.HasProgress get
Definition at line 57 of file TaskBuild.cs.
isBlock
override bool TaskBuild.isBlock get
Definition at line 67 of file TaskBuild.cs.
useHeld
bool TaskBuild.useHeld get
Definition at line 61 of file TaskBuild.cs.
Referenced by _GetHitResult(), CanRotateBlock(), GetHitResult(), GetText(), and OnProgressComplete().
W
override int TaskBuild.W get
Definition at line 63 of file TaskBuild.cs.
Referenced by GetHitResult().
The documentation for this class was generated from the following file:
Elin/TaskBuild.cs