Elin Decompiled Documentation: SourceThing Class Reference
SourceThing Class Reference
Classes
class Row
Public Member Functions
override Row CreateRow ()
override void SetRow (Row r)
override void BackupPref ()
override void RestorePref ()
Public Member Functions inherited from SourceDataString< SourceThing.Row >
override T GetRow (string id)
Public Attributes
Dictionary< string, Row > _rows = new Dictionary<string, Row>()
Properties
override string[] ImportFields [get]
Detailed Description
Definition at line 4 of file SourceThing.cs.
Member Function Documentation
BackupPref()
override void SourceThing.BackupPref () inline
Definition at line 214 of file SourceThing.cs.
    {
        SourceAsset._SavePrefs("prefs_auto");
        _rows.Clear();
        foreach (Row row in rows)
        {
            _rows[row.id] = row;
        }
    }
References _rows, SourceAsset._SavePrefs(), and CardRow.id.
CreateRow()
override Row SourceThing.CreateRow () inline
Definition at line 151 of file SourceThing.cs.
    {
        return new Row
        {
            id = SourceData.GetString(0),
            name_JP = SourceData.GetString(1),
            unknown_JP = SourceData.GetString(2),
            unit_JP = SourceData.GetString(3),
            naming = SourceData.GetString(4),
            name = SourceData.GetString(5),
            unit = SourceData.GetString(6),
            unknown = SourceData.GetString(7),
            category = SourceData.GetString(8),
            sort = SourceData.GetInt(10),
            _tileType = SourceData.GetString(11),
            _idRenderData = SourceData.GetString(12),
            tiles = SourceData.GetIntArray(13),
            altTiles = SourceData.GetIntArray(14),
            anime = SourceData.GetIntArray(15),
            skins = SourceData.GetIntArray(16),
            size = SourceData.GetIntArray(17),
            colorMod = SourceData.GetInt(18),
            colorType = SourceData.GetString(19),
            recipeKey = SourceData.GetStringArray(20),
            factory = SourceData.GetStringArray(21),
            components = SourceData.GetStringArray(22),
            disassemble = SourceData.GetStringArray(23),
            defMat = SourceData.GetString(24),
            tierGroup = SourceData.GetString(25),
            value = SourceData.GetInt(26),
            LV = SourceData.GetInt(27),
            chance = SourceData.GetInt(28),
            quality = SourceData.GetInt(29),
            HP = SourceData.GetInt(30),
            weight = SourceData.GetInt(31),
            electricity = SourceData.GetInt(32),
            trait = SourceData.GetStringArray(33),
            elements = Core.ParseElements(SourceData.GetStr(34)),
            range = SourceData.GetInt(35),
            attackType = SourceData.GetString(36),
            offense = SourceData.GetIntArray(37),
            substats = SourceData.GetIntArray(38),
            defense = SourceData.GetIntArray(39),
            lightData = SourceData.GetString(40),
            idExtra = SourceData.GetString(41),
            idToggleExtra = SourceData.GetString(42),
            idActorEx = SourceData.GetString(43),
            idSound = SourceData.GetString(44),
            tag = SourceData.GetStringArray(45),
            workTag = SourceData.GetString(46),
            filter = SourceData.GetStringArray(47),
            roomName_JP = SourceData.GetStringArray(48),
            roomName = SourceData.GetStringArray(49),
            detail_JP = SourceData.GetString(50),
            detail = SourceData.GetString(51)
        };
    }
References SourceData< T, T2 >.GetInt(), SourceData< T, T2 >.GetIntArray(), SourceData< T, T2 >.GetStr(), SourceData< T, T2 >.GetString(), SourceData< T, T2 >.GetStringArray(), and Core.ParseElements().
RestorePref()
override void SourceThing.RestorePref () inline
Definition at line 224 of file SourceThing.cs.
    {
    }
SetRow()
override void SourceThing.SetRow (Row r) inline
Definition at line 209 of file SourceThing.cs.
    {
        map[r.id] = r;
    }
References CardRow.id.
Member Data Documentation
_rows
Dictionary<string, Row> SourceThing._rows = new Dictionary<string, Row>()
Definition at line 147 of file SourceThing.cs.
Referenced by BackupPref(), and SourceThingV.RestorePref().
Property Documentation
ImportFields
override string [] SourceThing.ImportFields get
Definition at line 149 of file SourceThing.cs.
The documentation for this class was generated from the following file:
Elin/SourceThing.cs