Elin Decompiled Documentation: LayerUploader Class Reference
LayerUploader Class Reference
Public Member Functions
override void OnInit ()
override void OnKill ()
void SaveID ()
void ExportMap ()
void Upload ()
Public Member Functions inherited from ELayer
override void OnBeforeAddLayer ()
void InitInspector ()
sealed override void Init ()
override void OnAfterAddLayer ()
void TryShowHelp ()
void AddLayerToUI (string id)
void TryShowHint (string _langHint=null)
void TalkHomeMemeber (string id)
void TalkMaid (string id)
override void OnRightClick ()
Public Member Functions inherited from Layer
virtual string GetTextHeader (Window window)
virtual bool HeaderIsListOf (int id)
virtual void Init ()
virtual void OnInit ()
virtual void OnAfterInit ()
virtual void ApplySkin ()
void ShowScreenLock (string id)
void UpdateInput ()
virtual void OnUpdateInput ()
virtual void OnRightClick ()
virtual bool OnBack ()
virtual void OnChangeLayer ()
virtual void OnCreate ()
void _AddLayer (string id)
Layer AddLayer (string id)
T AddLayer< T > ()
T AddLayer< T > (string id)
T AddLayerDontCloseOthers< T > ()
Layer AddLayerDontCloseOthers (Layer l)
T GetOrAddLayer< T > ()
virtual void OnBeforeAddLayer ()
virtual void OnAfterAddLayer ()
Layer AddLayer (Layer l)
void ToggleLayer (string id)
T ToggleLayer< T > (string id=null)
void WaitAndClose ()
void OnClickClose ()
virtual void Close ()
void CloseLayers ()
void RemoveLayers (bool removeImportant=false)
bool RemoveLayer< T > ()
void RemoveLayer (Layer l)
virtual void OnKill ()
Layer SetOnKill (Action action)
void DisableClose ()
void Delay (float duration=0.05f)
Layer SetDelay (float d)
Layer GetLayer (string id)
T GetLayer< T > (bool fromTop=false)
Layer GetTopLayer ()
void SwitchContent (int idWindow, int i)
virtual void OnSwitchContent (Window window)
Layer SetTitles (string langList, string idHeaderRow=null)
bool IsBlockWidgetClick ()
bool IsHideHud ()
bool IsAllowGeneralInput ()
bool IsUseBlur ()
bool IsPointerOnLayer ()
void ApplySkin ()
Public Attributes
InputField inputId
InputField inputPassword
InputField inputWelcome
IniData ini
UIText textInvalidId
UIText textInvalidPass
UIText textNextUpload
UIButton buttonUpload
UIButton buttonSave
UIButton toggleClearLocalCharas
UIButton toggleAdult
int limitSec
HashSet< string > invalidIds = new HashSet<string>()
bool validId
bool validPass
Public Attributes inherited from Layer
Option option
UnityEvent onKill
Anime animeIn
Anime animeOut
bool closeOthers
bool defaultActionMode = true
Button screenLock
Layer parent
string idLayer
List< Layer > layers = new List<Layer>()
Vector2 lastParentPos
List< Window > windows = new List<Window>()
string langHint
Static Public Attributes
static int nextUpload
static char[] InvalidChars
Static Public Attributes inherited from Layer
static int skipInput
static bool closeOnRightClick
static bool rightClicked
static bool cancelKeyDown
static bool ignoreSounds
static Transform blurStopInstance
static string[] searchPath = new string[3] { "Layer", "Layer/Dialog", "Layer/LayerHome" }
Properties
string savePath [get]
Properties inherited from ELayer
static Core core [get]
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static FactionBranch Branch [get]
static Faction Home [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static CoreConfig config [get]
static GameSetting setting [get]
static ColorProfile Colors [get]
static SourceManager sources [get]
static World world [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
bool IsFloat [get]
virtual string IdHelp [get]
Properties inherited from Layer
Layer TopLayer [get]
string uid [get]
virtual RectTransform rectLayers [get]
virtual bool blockWidgetClick [get]
Private Member Functions
void Update ()
Additional Inherited Members
Static Public Member Functions inherited from ELayer
static int rnd (int a)
Static Public Member Functions inherited from Layer
static T Create< T > ()
static T Create< T > (string path)
static Layer Create (string path)
Protected Member Functions inherited from ELayer
sealed override void _Close ()
sealed override void Kill ()
Protected Member Functions inherited from Layer
virtual void Awake ()
virtual void _Close ()
virtual void Kill ()
Protected Attributes inherited from Layer
RectTransform _rect
bool isDestroyed
Detailed Description
Definition at line 7 of file LayerUploader.cs.
Member Function Documentation
ExportMap()
void LayerUploader.ExportMap () inline
Definition at line 120 of file LayerUploader.cs.
    {
        ELayer._zone.Export(savePath, null, usermap: true);
        Msg.Say("net_mapSaved".lang(savePath));
        SE.WriteJournal();
    }
References ELayer._zone, Zone.Export(), savePath, and Msg.Say().
Referenced by Upload().
OnInit()
override void LayerUploader.OnInit () inline virtual
Reimplemented from Layer.
Definition at line 52 of file LayerUploader.cs.
    {
        ini = Core.GetElinIni();
        string text = ini.GetKey("pass") ?? "password";
        inputId.text = ELayer._map.custom?.id ?? "new_zone";
        inputPassword.text = text;
        if (ELayer._map.exportSetting == null)
        {
            ELayer._map.exportSetting = new MapExportSetting();
        }
        MapExportSetting ex = ELayer._map.exportSetting;
        inputWelcome.text = ex.textWelcome.IsEmpty("");
        inputWelcome.onValueChanged.AddListener(delegate(string s)
        {
            ex.textWelcome = s;
        });
        toggleClearLocalCharas.SetToggle(ex.clearLocalCharas, delegate(bool on)
        {
            ex.clearLocalCharas = on;
        });
        toggleAdult.SetToggle(ELayer._map.exportSetting.tag.HasTag("adult"), delegate(bool on)
        {
            ELayer._map.exportSetting.tag = ELayer._map.exportSetting.tag.SetTag("adult", on);
            Debug.Log(ELayer._map.exportSetting.tag + " / " + ELayer._map.exportSetting.tag.HasTag("adult"));
        });
    }
References ELayer._map, MapExportSetting.clearLocalCharas, Map.custom, Debug, Map.exportSetting, Core.GetElinIni(), CustomData.id, ini, inputWelcome, UIButton.SetToggle(), MapExportSetting.tag, MapExportSetting.textWelcome, toggleAdult, and toggleClearLocalCharas.
OnKill()
override void LayerUploader.OnKill () inline virtual
Reimplemented from Layer.
Definition at line 102 of file LayerUploader.cs.
    {
        if (validId && validPass)
        {
            SaveID();
        }
    }
References SaveID(), validId, and validPass.
SaveID()
void LayerUploader.SaveID () inline
Definition at line 110 of file LayerUploader.cs.
    {
        if (ELayer._map.custom != null)
        {
            ELayer._map.custom.id = inputId.text;
        }
        ini.Global["pass"] = inputPassword.text;
        Core.SaveElinIni(ini);
    }
References ELayer._map, Map.custom, ini, inputId, inputPassword, and Core.SaveElinIni().
Referenced by OnKill(), and Upload().
Update()
void LayerUploader.Update () inline private
Definition at line 79 of file LayerUploader.cs.
    {
        string text = inputId.text;
        validId = text.Length >= 3 && text.IndexOfAny(InvalidChars) == -1 && !invalidIds.Contains(text);
        text = inputPassword.text;
        validPass = text.Length >= 3 && text.IndexOfAny(InvalidChars) == -1;
        textInvalidId.SetActive(!validId);
        textInvalidPass.SetActive(!validPass);
        bool interactableWithAlpha = validId && validPass;
        buttonSave.SetInteractableWithAlpha(interactableWithAlpha);
        int num = nextUpload - (int)Time.realtimeSinceStartup;
        textNextUpload.SetActive(num > 0);
        if (num > 0)
        {
            textNextUpload.text = "net_nextUpload".lang(num.ToString() ?? "");
            if (!ELayer.debug.enable)
            {
                interactableWithAlpha = false;
            }
        }
        buttonUpload.SetInteractableWithAlpha(interactableWithAlpha);
    }
References buttonSave, buttonUpload, ELayer.debug, CoreDebug.enable, inputId, inputPassword, InvalidChars, invalidIds, UIText.lang, nextUpload, UIButton.SetInteractableWithAlpha(), textInvalidId, textInvalidPass, textNextUpload, validId, and validPass.
Upload()
void LayerUploader.Upload () inline
Definition at line 127 of file LayerUploader.cs.
    {
        if (ini.Global["agreed_usercontents_upload_terms"] != "yes")
        {
            string[] items = new string[3] { "readTerms", "agree", "disagree" };
            Dialog.List("dialogTermsOfUse".lang(), items, (string j) => j, delegate(int c, string d)
            {
                switch (c)
                {
                case 0:
                    LayerHelp.Toggle("custom", "terms");
                    return false;
                case 1:
                    ini.Global["agreed_usercontents_upload_terms"] = "yes";
                    Upload();
                    break;
                }
                return true;
            }, canCancel: true);
        }
        else
        {
            Debug.Log("Uploading map");
            string text = inputId.text;
            string text2 = inputPassword.text;
            SaveID();
            ExportMap();
            Net.UploadFile(text, text2, ELayer.pc.NameBraced, ELayer._zone.Name, savePath, Lang.langCode, (ELayer._zone is Zone_Tent) ? "Tent" : "Home", ELayer._map.exportSetting.tag);
            nextUpload = (int)Time.realtimeSinceStartup + limitSec;
        }
    }
References ELayer._map, ELayer._zone, Debug, ExportMap(), Map.exportSetting, ini, inputId, inputPassword, Lang.langCode, limitSec, Spatial.Name, Chara.NameBraced, nextUpload, ELayer.pc, SaveID(), savePath, MapExportSetting.tag, LayerHelp.Toggle(), Upload(), and Net.UploadFile().
Referenced by Upload().
Member Data Documentation
buttonSave
UIButton LayerUploader.buttonSave
Definition at line 34 of file LayerUploader.cs.
Referenced by Update().
buttonUpload
UIButton LayerUploader.buttonUpload
Definition at line 32 of file LayerUploader.cs.
Referenced by Update().
ini
IniData LayerUploader.ini
Definition at line 24 of file LayerUploader.cs.
Referenced by OnInit(), SaveID(), and Upload().
inputId
InputField LayerUploader.inputId
Definition at line 18 of file LayerUploader.cs.
Referenced by SaveID(), Update(), and Upload().
inputPassword
InputField LayerUploader.inputPassword
Definition at line 20 of file LayerUploader.cs.
Referenced by SaveID(), Update(), and Upload().
inputWelcome
InputField LayerUploader.inputWelcome
Definition at line 22 of file LayerUploader.cs.
Referenced by OnInit().
InvalidChars
char [] LayerUploader.InvalidChars static
Initial value:
= new char[21]
    {
        '*', '&', '|', '#', '\\', '/', '?', '!', '"', '>',
        '<', ':', ';', '.', ',', '~', '@', '^', '$', '%',
        ' '
    }
Definition at line 11 of file LayerUploader.cs.
Referenced by Update().
invalidIds
HashSet<string> LayerUploader.invalidIds = new HashSet<string>()
Definition at line 42 of file LayerUploader.cs.
Referenced by Update().
limitSec
int LayerUploader.limitSec
Definition at line 40 of file LayerUploader.cs.
Referenced by Upload().
nextUpload
int LayerUploader.nextUpload static
Definition at line 9 of file LayerUploader.cs.
Referenced by Update(), and Upload().
textInvalidId
UIText LayerUploader.textInvalidId
Definition at line 26 of file LayerUploader.cs.
Referenced by Update().
textInvalidPass
UIText LayerUploader.textInvalidPass
Definition at line 28 of file LayerUploader.cs.
Referenced by Update().
textNextUpload
UIText LayerUploader.textNextUpload
Definition at line 30 of file LayerUploader.cs.
Referenced by Update().
toggleAdult
UIButton LayerUploader.toggleAdult
Definition at line 38 of file LayerUploader.cs.
Referenced by OnInit().
toggleClearLocalCharas
UIButton LayerUploader.toggleClearLocalCharas
Definition at line 36 of file LayerUploader.cs.
Referenced by OnInit().
validId
bool LayerUploader.validId
Definition at line 45 of file LayerUploader.cs.
Referenced by OnKill(), and Update().
validPass
bool LayerUploader.validPass
Definition at line 48 of file LayerUploader.cs.
Referenced by OnKill(), and Update().
Property Documentation
savePath
string LayerUploader.savePath get private
Definition at line 50 of file LayerUploader.cs.
Referenced by ExportMap(), and Upload().
The documentation for this class was generated from the following file:
Elin/LayerUploader.cs