Elin Decompiled Documentation: SourceData< T, T2 >.BaseRow Class Reference
SourceData< T, T2 >.BaseRow Class Reference
Public Member Functions
Dictionary< string, FieldInfo > GetRowFields ()
virtual string GetName ()
string GetDetail ()
virtual string GetEditorListName ()
string GetText (string id="name", bool returnNull=false)
string[] GetTextArray (string id)
virtual void SetID (ref int count)
virtual void OnImportData (SourceData data)
virtual IDictionary< string, string > ExportTexts (string idField="id")
virtual void ImportTexts (IReadOnlyDictionary< string, string > texts, string idField="id")
Public Attributes
int _index
Properties
virtual bool UseAlias [get]
virtual string GetAlias [get]
Static Private Attributes
static readonly Dictionary< Type, Dictionary< string, FieldInfo > > _fieldCache = new Dictionary<Type, Dictionary<string, FieldInfo>>()
Detailed Description
Definition at line 624 of file SourceData.cs.
Member Function Documentation
ExportTexts()
virtual IDictionary< string, string > SourceData< T, T2 >.BaseRow.ExportTexts (string idField = "id") inline virtual
Definition at line 715 of file SourceData.cs.
        {
            Dictionary<string, FieldInfo> rowFields = GetRowFields();
            object obj = rowFields.GetValueOrDefault(idField)?.GetValue(this);
            SortedDictionary<string, string> sortedDictionary = new SortedDictionary<string, string>();
            if (obj == null)
            {
                return sortedDictionary;
            }
            string name = GetType().DeclaringType.Name;
            foreach (var (text2, jp2) in rowFields)
            {
                if (!text2.EndsWith("_JP"))
                {
                    continue;
                }
                string text3 = text2[..^3];
                if (rowFields.TryGetValue(text3, out var value) && rowFields.TryGetValue(text3 + "_L", out var value2))
                {
                    string text4 = GetFieldText(jp2, value, value2);
                    if (!text4.IsEmpty())
                    {
                        sortedDictionary[$"{name}.{obj}.{text3}"] = text4;
                    }
                }
            }
            return sortedDictionary;
            string GetFieldText(FieldInfo jp, FieldInfo en, FieldInfo l)
            {
                object value3 = jp.GetValue(this);
                object value4 = en.GetValue(this);
                object value5 = l.GetValue(this);
                string langCode = Lang.langCode;
                object obj2 = ((langCode == "JP") ? value3 : ((!(langCode == "EN")) ? (value5 ?? value4) : value4));
                object obj3 = obj2;
                if (obj3 is string str)
                {
                    return str.IsEmpty(value4 as string);
                }
                if (obj3 is string[] array)
                {
                    return string.Join(',', (array.Length != 0) ? array : (value4 as string[]));
                }
                return null;
            }
        }
References $, SourceData< T, T2 >.BaseRow.GetRowFields(), SourceData< T, T2 >.FieldInfo.GetValue(), and Lang.langCode.
GetDetail()
string SourceData< T, T2 >.BaseRow.GetDetail () inline
Definition at line 655 of file SourceData.cs.
        {
            return GetText("detail");
        }
References SourceData< T, T2 >.BaseRow.GetText().
Referenced by RecipeCard.GetDetail(), and RecipeSource.GetDetail().
GetEditorListName()
virtual string SourceData< T, T2 >.BaseRow.GetEditorListName () inline virtual
Reimplemented in CardRow.
Definition at line 660 of file SourceData.cs.
        {
            return this.GetField<int>("id") + "-" + this.GetField<string>("alias") + "(" + this.GetField<string>("name_JP") + ")";
        }
GetName()
virtual string SourceData< T, T2 >.BaseRow.GetName () inline virtual
Reimplemented in CardRow, SourceChara.Row, and SourceThing.Row.
Definition at line 650 of file SourceData.cs.
        {
            return GetText();
        }
References SourceData< T, T2 >.BaseRow.GetText().
Referenced by TraitTile.SetName().
GetRowFields()
Dictionary< string, FieldInfo > SourceData< T, T2 >.BaseRow.GetRowFields () inline
Definition at line 634 of file SourceData.cs.
        {
            Type type = GetType();
            if (_fieldCache.TryGetValue(type, out var value))
            {
                return value;
            }
            value = new Dictionary<string, FieldInfo>();
            FieldInfo[] fields = type.GetFields(BindingFlags.Instance | BindingFlags.Public);
            foreach (FieldInfo fieldInfo in fields)
            {
                value[fieldInfo.Name] = fieldInfo;
            }
            return _fieldCache[type] = value;
        }
References SourceData< T, T2 >.BaseRow._fieldCache.
Referenced by SourceData< T, T2 >.BaseRow.ExportTexts(), SourceData< T, T2 >.BaseRow.GetText(), SourceData< T, T2 >.BaseRow.GetTextArray(), SourceData< T, T2 >.BaseRow.ImportTexts(), and SourceThingV.OnAfterImportData().
GetText()
string SourceData< T, T2 >.BaseRow.GetText (string id = "name", bool returnNull = false) inline
Definition at line 665 of file SourceData.cs.
        {
            Dictionary<string, FieldInfo> rowFields = GetRowFields();
            if (rowFields.TryGetValue(id + LangSuffix, out var value))
            {
                string text = value.GetValue(this) as string;
                if (!text.IsEmpty())
                {
                    return text;
                }
            }
            if (!Lang.isBuiltin && rowFields.TryGetValue(id, out var value2))
            {
                string text2 = value2.GetValue(this) as string;
                if (!text2.IsEmpty())
                {
                    return text2;
                }
            }
            if (!returnNull)
            {
                return "";
            }
            return null;
        }
References SourceData< T, T2 >.BaseRow.GetRowFields(), Lang.isBuiltin, and SourceData< T, T2 >.LangSuffix.
Referenced by Card.GetDetail(), SourceData< T, T2 >.BaseRow.GetDetail(), Recipe.GetDetail(), Msg.GetGameText(), SourceData< T, T2 >.BaseRow.GetName(), Recipe.GetName(), SourceChara.Row.GetName(), SourceThing.Row.GetName(), Trait.GetName(), TraitGene.GetName(), CardRow.GetName(), RenderRow.GetSearchName(), SourceChara.Row.GetSearchName(), and SourceThing.Row.GetSearchName().
GetTextArray()
string[] SourceData< T, T2 >.BaseRow.GetTextArray (string id) inline
Definition at line 691 of file SourceData.cs.
        {
            Dictionary<string, FieldInfo> rowFields = GetRowFields();
            if (rowFields.TryGetValue(id + LangSuffix, out var value) && value.GetValue(this) is string[] { Length: >0 } array)
            {
                return array;
            }
            if (!Lang.isBuiltin && rowFields.TryGetValue(id, out var value2) && value2.GetValue(this) is string[] { Length: >0 } array2)
            {
                return array2;
            }
            return Array.Empty<string>();
        }
References SourceData< T, T2 >.BaseRow.GetRowFields(), Lang.isBuiltin, and SourceData< T, T2 >.LangSuffix.
ImportTexts()
virtual void SourceData< T, T2 >.BaseRow.ImportTexts (IReadOnlyDictionary< string, string > texts, string idField = "id") inline virtual
Definition at line 762 of file SourceData.cs.
        {
            Dictionary<string, FieldInfo> rowFields = GetRowFields();
            object obj = rowFields.GetValueOrDefault(idField)?.GetValue(this);
            if (obj == null)
            {
                return;
            }
            string name = GetType().DeclaringType.Name;
            string langCode = Lang.langCode;
            foreach (var (text2, fieldInfo2) in rowFields)
            {
                if (!text2.EndsWith("_L"))
                {
                    continue;
                }
                string text3 = text2[..^2];
                if (!texts.TryGetValue($"{name}.{obj}.{text3}", out var value2) || value2.IsEmpty() || !rowFields.TryGetValue(text3, out var value3) || !rowFields.TryGetValue(text3 + "_JP", out var value4))
                {
                    continue;
                }
                fieldInfo2.SetValue(this, null);
                SetFieldText(fieldInfo2, value2);
                if (!(langCode == "EN"))
                {
                    if (langCode == "JP")
                    {
                        SetFieldText(value4, value2);
                    }
                }
                else
                {
                    SetFieldText(value3, value2);
                }
            }
            void SetFieldText(FieldInfo l, string value)
            {
                if (l.FieldType == typeof(string))
                {
                    l.SetValue(this, value);
                }
                else if (l.FieldType == typeof(string[]))
                {
                    l.SetValue(this, value.IsEmpty() ? Array.Empty<string>() : value.Split(','));
                }
            }
        }
References $, SourceData< T, T2 >.BaseRow.GetRowFields(), and Lang.langCode.
OnImportData()
virtual void SourceData< T, T2 >.BaseRow.OnImportData (SourceData data) inline virtual
Reimplemented in CardRow, RenderRow, and SourceThing.Row.
Definition at line 711 of file SourceData.cs.
        {
        }
SetID()
virtual void SourceData< T, T2 >.BaseRow.SetID (ref int count) inline virtual
Definition at line 705 of file SourceData.cs.
        {
            this.SetField("id", count);
            count++;
        }
Member Data Documentation
_fieldCache
readonly Dictionary<Type, Dictionary<string, FieldInfo> > SourceData< T, T2 >.BaseRow._fieldCache = new Dictionary<Type, Dictionary<string, FieldInfo>>() static private
Definition at line 626 of file SourceData.cs.
Referenced by SourceData< T, T2 >.BaseRow.GetRowFields().
_index
int SourceData< T, T2 >.BaseRow._index
Definition at line 628 of file SourceData.cs.
Referenced by Thing.GetName(), Trait.GetSortVal(), Chara.SetSortVal(), and Thing.TryLickEnchant().
Property Documentation
GetAlias
virtual string SourceData< T, T2 >.BaseRow.GetAlias get
Definition at line 632 of file SourceData.cs.
UseAlias
virtual bool SourceData< T, T2 >.BaseRow.UseAlias get
Definition at line 630 of file SourceData.cs.
The documentation for this class was generated from the following file:
Elin/Plugins.basecore/SourceData.cs