Elin Decompiled Documentation: Widget.Config Class Reference
Widget.Config Class Reference
Public Member Functions
bool IsInRightMode ()
Public Attributes
State state
RectPosition anchor
RectPosition userAnchor
RectPosition pivot = RectPosition.Center
string id
string titleLang
float x
float y
bool locked
bool RC
object extra
SkinConfig skin = new SkinConfig()
bool valid
bool annoyPlayer
Meta meta
Properties
GameMode mode [get]
bool IsSealed [get]
bool IsSystem [get]
Detailed Description
Definition at line 37 of file Widget.cs.
Member Function Documentation
IsInRightMode()
bool Widget.Config.IsInRightMode () inline
Definition at line 101 of file Widget.cs.
        {
            ActionMode actionMode = EMono.scene.actionMode;
            if (actionMode.ShowBuildWidgets)
            {
                return mode.HasFlag(GameMode.Build);
            }
            if (actionMode == ActionMode.NoMap || actionMode == ActionMode.NewZone || actionMode == ActionMode.ViewMap)
            {
                return mode.HasFlag(GameMode.NoMap);
            }
            if (actionMode == ActionMode.Bird)
            {
                return mode.HasFlag(GameMode.Bird);
            }
            if (ActionMode.DefaultMode == ActionMode.Sim)
            {
                return mode.HasFlag(GameMode.Sim);
            }
            if (ActionMode.DefaultMode == ActionMode.EloMap)
            {
                return mode.HasFlag(GameMode.EloMap);
            }
            if (ActionMode.IsAdv || ActionMode.DefaultMode == ActionMode.View)
            {
                if (actionMode == ActionMode.Region && !mode.HasFlag(GameMode.EloMap))
                {
                    return false;
                }
                if (!ActionMode.Adv.zoomOut && meta.type == WidgetType.ZoomMenu)
                {
                    return false;
                }
                return mode.HasFlag(GameMode.Adv);
            }
            return false;
        }
References Scene.actionMode, ActionMode.Adv, ActionMode.Bird, ActionMode.DefaultMode, ActionMode.EloMap, ActionMode.IsAdv, Widget.Config.meta, Widget.Config.mode, ActionMode.NewZone, ActionMode.NoMap, ActionMode.Region, EMono.scene, ActionMode.ShowBuildWidgets, ActionMode.Sim, Widget.Meta.type, ActionMode.View, ActionMode.ViewMap, and AM_Adv.zoomOut.
Referenced by Widget.IsInRightMode().
Member Data Documentation
anchor
RectPosition Widget.Config.anchor
Definition at line 41 of file Widget.cs.
Referenced by Widget.Activate().
annoyPlayer
bool Widget.Config.annoyPlayer
Definition at line 67 of file Widget.cs.
extra
object Widget.Config.extra
Definition at line 59 of file Widget.cs.
Referenced by Widget.Activate().
id
string Widget.Config.id
Definition at line 47 of file Widget.cs.
Referenced by WidgetManager.OnGameInstantiated().
locked
bool Widget.Config.locked
Definition at line 55 of file Widget.cs.
Referenced by WidgetManager.RefreshWidget().
meta
Meta Widget.Config.meta
Definition at line 70 of file Widget.cs.
Referenced by Widget.Config.IsInRightMode().
pivot
RectPosition Widget.Config.pivot = RectPosition.Center
Definition at line 45 of file Widget.cs.
Referenced by Widget.Activate(), and Widget.SetBaseContextMenu().
RC
bool Widget.Config.RC
Definition at line 57 of file Widget.cs.
Referenced by Widget.SetBaseContextMenu().
skin
SkinConfig Widget.Config.skin = new SkinConfig()
Definition at line 61 of file Widget.cs.
Referenced by Widget.Activate(), Widget.AddDeco(), Widget.GetSkin(), Widget.GetSkinConfig(), WidgetManager.OnGameInstantiated(), Widget.RemoveDeco(), Widget.SetBaseContextMenu(), Widget.SetGridContextMenu(), Widget.SetSkin(), and Widget.TestSkin().
state
State Widget.Config.state
Definition at line 39 of file Widget.cs.
titleLang
string Widget.Config.titleLang
Definition at line 49 of file Widget.cs.
userAnchor
RectPosition Widget.Config.userAnchor
Definition at line 43 of file Widget.cs.
Referenced by Widget.Activate(), Widget.ClampToScreen(), and Widget.SetBaseContextMenu().
valid
bool Widget.Config.valid
Definition at line 64 of file Widget.cs.
x
float Widget.Config.x
Definition at line 51 of file Widget.cs.
Referenced by Widget.Activate().
y
float Widget.Config.y
Definition at line 53 of file Widget.cs.
Referenced by Widget.Activate().
Property Documentation
IsSealed
bool Widget.Config.IsSealed get
Definition at line 76 of file Widget.cs.
        {
            get
            {
                if (IsSystem)
                {
                    return !EMono.core.config.test.unsealWidgets;
                }
                return false;
            }
        }
IsSystem
bool Widget.Config.IsSystem get
Definition at line 89 of file Widget.cs.
        {
            get
            {
                if (!meta.system)
                {
                    return annoyPlayer;
                }
                return true;
            }
        }
mode
GameMode Widget.Config.mode get
Definition at line 73 of file Widget.cs.
Referenced by Widget.Config.IsInRightMode().
The documentation for this class was generated from the following file:
Elin/Widget.cs