Elin Decompiled Documentation: BaseListPeople Class Reference
BaseListPeople Class Reference
Public Member Functions
virtual bool IsDisabled (Chara c)
override void List ()
override void OnInstantiate (Chara a, ItemGeneral b)
void AddSubButtonWork (ItemGeneral b, Chara a)
void WriteHobbies (UITooltip t, Chara a, BaseArea roomWork)
virtual void SetSubText (Chara a, ItemGeneral b)
override void OnClick (Chara c, ItemGeneral i)
override void OnList ()
override void OnRefreshMenu ()
Public Member Functions inherited from ListOwner< Chara, ItemGeneral >
virtual void OnClick (T1 a, T2 b)
virtual void OnInstantiate (T1 a, T2 b)
virtual void OnList ()
virtual void List ()
virtual void OnCreate ()
virtual void OnSwitchContent ()
virtual void OnRefreshMenu ()
void RefreshTab ()
void MoveToOther (object c)
Public Attributes
Chara owner
FactionMemberType memberType
Public Attributes inherited from ListOwner< Chara, ItemGeneral >
Layer layer
Window window
UIMultiList multi
ListOwner other
UIList list
WindowMenu menu
Window.Setting.Tab tab
string textTab
string textHeader
bool main
int index
Properties
new LayerPeople layer [get]
override string IdHeaderRow [get]
virtual bool ShowCharaSheet [get]
virtual bool ShowShowMode [get]
virtual LayerPeople.ShowMode ShowMode [get]
virtual bool ShowGoto [get]
virtual bool ShowHome [get]
Properties inherited from ListOwner< Chara, ItemGeneral >
ListOwner Main [get]
virtual string IdTitle [get]
virtual string IdHeaderRow [get]
virtual string TextTab [get]
virtual string TextHeader [get]
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Additional Inherited Members
Static Public Member Functions inherited from EClass
static int rndSeed (int a, int seed)
static int rnd (int a)
static int curve (int a, int start, int step, int rate=75)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Static Public Attributes inherited from EClass
static Core core
Detailed Description
Definition at line 6 of file BaseListPeople.cs.
Member Function Documentation
AddSubButtonWork()
void BaseListPeople.AddSubButtonWork (ItemGeneral b, Chara a) inline
Definition at line 123 of file BaseListPeople.cs.
    {
        BaseArea roomWork = a.GetRoomWork();
        bool flag = true;
        foreach (Hobby item in a.ListWorks().Concat(a.ListHobbies()))
        {
            if (item.GetEfficiency(a) <= 0)
            {
                flag = false;
                break;
            }
        }
        b.AddSubButton(EClass.core.refs.icons.work, delegate
        {
            if (roomWork == null)
            {
                SE.BeepSmall();
            }
            else
            {
                EClass.pc.SetAI(new AI_Goto(roomWork.GetRandomFreePos(), 1));
                layer.Close();
            }
        }, null, delegate(UITooltip t)
        {
            WriteHobbies(t, a, roomWork);
        }).icon.SetAlpha(flag ? 1f : 0.4f);
    }
References EClass.core, Chara.GetRoomWork(), CoreRef.icons, item, Core.refs, and CoreRef.Icons.work.
Referenced by OnInstantiate().
IsDisabled()
virtual bool BaseListPeople.IsDisabled (Chara c) inline virtual
Reimplemented in ListPeopleBuySlave, and ListPeopleRevive.
Definition at line 26 of file BaseListPeople.cs.
    {
        if (!c.isDead && c.memberType != FactionMemberType.Guest)
        {
            return !c.IsInHomeZone();
        }
        return false;
    }
References Chara.isDead, Chara.IsInHomeZone(), and Chara.memberType.
List()
override void BaseListPeople.List () inline virtual
Reimplemented from ListOwner< Chara, ItemGeneral >.
Definition at line 35 of file BaseListPeople.cs.
    {
        list.callbacks = new UIList.Callback<Chara, ItemGeneral>
        {
            onInstantiate = delegate(Chara a, ItemGeneral b)
            {
                b.SetChara(a, (this is ListPeopleBuySlave) ? ItemGeneral.Mode.Slave : ItemGeneral.Mode.Default);
                OnInstantiate(a, b);
                b.Build();
            },
            onClick = delegate(Chara c, ItemGeneral i)
            {
                OnClick(c, i);
            },
            onSort = delegate(Chara a, UIList.SortMode m)
            {
                a.SetSortVal(m);
                return -a.sortVal;
            },
            onList = delegate
            {
                OnList();
            },
            onRefresh = null
        };
        list.List();
    }
References ItemGeneral.Build(), ListOwner< Chara, ItemGeneral >.list, UIList.List(), OnClick(), OnInstantiate(), OnList(), ItemGeneral.SetChara(), Chara.SetSortVal(), and Card.sortVal.
OnClick()
override void BaseListPeople.OnClick (Chara c, ItemGeneral i) inline
Definition at line 258 of file BaseListPeople.cs.
    {
        if (!c.IsAliveInCurrentZone)
        {
            if (c.currentZone != EClass._zone)
            {
                Msg.Say("isIn", c, (c.currentZone == null) ? "???" : c.currentZone.Name);
            }
            SE.BeepSmall();
            return;
        }
        UIContextMenu uIContextMenu = EClass.ui.CreateContextMenuInteraction().SetHighlightTarget(i);
        if (c.IsGuest())
        {
            uIContextMenu.AddButton("findMember", delegate
            {
                EClass.pc.SetAI(new AI_Goto(c, 1));
                layer.Close();
            });
        }
        else if (c.IsHomeMember())
        {
            if (!c.IsPC)
            {
                uIContextMenu.AddButton("findMember", delegate
                {
                    EClass.pc.SetAI(new AI_Goto(c, 1));
                    layer.Close();
                });
            }
            uIContextMenu.AddButton("changeName", delegate
            {
                Dialog.InputName("dialogChangeName", c.c_altName.IsEmpty(c.NameSimple), delegate(bool cancel, string text)
                {
                    if (!cancel)
                    {
                        if (text == "*r")
{
                            text = NameGen.getRandomName();
                        }
                        c.c_altName = text;
                        layer.OnSwitchContent(layer.windows[0]);
                    }
                });
            });
            if (c != EClass.pc)
            {
                if (c.sourceCard.idActor.IsEmpty() && c.host == null)
                {
                    if (c.pccData == null)
                    {
                        uIContextMenu.AddButton("editPCC", delegate
{
                            EClass.ui.AddLayer<LayerEditPortrait>().Activate(c);
                        });
                        if (!c.IsPC)
{
                            uIContextMenu.AddButton("editSkin", delegate
{
                                LayerEditSkin layerEditSkin = EClass.ui.AddLayer<LayerEditSkin>();
                                layerEditSkin.SetOnKill(delegate
{
                                    list.Refresh();
                                });
                                layerEditSkin.Activate(c);
                            });
                        }
                        uIContextMenu.AddButton("togglePCC", delegate
{
                            bool isSynced2 = c.isSynced;
                            c.pccData = PCCData.Create(c.IDPCCBodySet);
                            c.pccData.Randomize(c.IDPCCBodySet);
                            if (isSynced2)
{
                                c.renderer.OnLeaveScreen();
                            }
                            EClass.scene.syncList.Remove(c.renderer);
                            c._CreateRenderer();
                            if (isSynced2)
{
                                EClass.scene.syncList.Add(c.renderer);
                                c.renderer.OnEnterScreen();
                            }
                            list.Refresh();
                            SE.Click();
                        });
                    }
                    else
                    {
                        uIContextMenu.AddButton("editPCC", delegate
{
                            EClass.ui.AddLayer<LayerEditPCC>().Activate(c, UIPCC.Mode.Full);
                        });
                        uIContextMenu.AddButton("togglePCC", delegate
{
                            bool isSynced = c.isSynced;
                            if (isSynced)
{
                                c.renderer.OnLeaveScreen();
                            }
                            EClass.scene.syncList.Remove(c.renderer);
                            c.pccData = null;
                            c._CreateRenderer();
                            if (isSynced)
{
                                EClass.scene.syncList.Add(c.renderer);
                                c.renderer.OnEnterScreen();
                            }
                            list.Refresh();
                        });
                    }
                }
                if (c.homeBranch == EClass.Branch)
                {
                    uIContextMenu.AddButton("makeMaid", delegate
                    {
                        if (EClass.Branch.uidMaid == c.uid)
{
                            EClass.Branch.uidMaid = 0;
                        }
                        else
{
                            EClass.Branch.uidMaid = c.uid;
                        }
                        list.Refresh();
                        SE.Click();
                    });
                }
                int @int = c.GetInt(36);
                bool isLivestockTimerOn = memberType == FactionMemberType.Default && !EClass.world.date.IsExpired(@int);
                int remainingHours = EClass.world.date.GetRemainingHours(@int);
                if (!c.IsPCParty)
                {
                    uIContextMenu.AddButton((c.memberType == FactionMemberType.Livestock) ? "daMakeResident" : (isLivestockTimerOn ? "daMakeLivestock2".lang(Date.GetText(remainingHours)) : "daMakeLivestock"), delegate
                    {
                        if (isLivestockTimerOn)
{
                            SE.Beep();
                        }
                        else
{
                            if (c.memberType == FactionMemberType.Livestock)
{
                                c.SetInt(36, EClass.world.date.GetRaw() + 14400);
                            }
                            EClass.Branch.ChangeMemberType(c, (c.memberType != FactionMemberType.Livestock) ? FactionMemberType.Livestock : FactionMemberType.Default);
                            foreach (ListOwner owner in layer.multi.owners)
{
                                owner.RefreshTab();
                            }
                            List();
                            SE.Click();
                        }
                    });
                }
                uIContextMenu.AddButton("addToReserve".lang() + " (" + EClass.Home.listReserve.Count + "/" + EClass.Home.GetMaxReserve() + ")", delegate
                {
                    if (EClass.Home.listReserve.Count >= EClass.Home.GetMaxReserve())
                    {
                        SE.Beep();
                        Msg.Say("reserveLimit");
                        return;
                    }
                    SE.MoveZone();
                    EClass.Home.AddReserve(c);
                    list.List();
                    foreach (ListOwner owner2 in layer.multi.owners)
                    {
                        owner2.RefreshTab();
                    }
                });
            }
        }
        uIContextMenu.Show();
    }
References Chara._CreateRenderer(), EClass._zone, LayerEditSkin.Activate(), UIContextMenu.AddButton(), Faction.AddReserve(), EClass.Branch, Card.c_altName, FactionBranch.ChangeMemberType(), Layer.Close(), Chara.currentZone, World.date, BaseCard.GetInt(), Faction.GetMaxReserve(), Date.GetRaw(), Date.GetRemainingHours(), Date.GetText(), EClass.Home, Chara.homeBranch, Chara.host, CardRow.idActor, Chara.IDPCCBodySet, Dialog.InputName(), Chara.IsAliveInCurrentZone, Date.IsExpired(), Chara.IsGuest(), Chara.IsHomeMember(), Chara.IsPC, Chara.IsPCParty, Chara.isSynced, Faction.listReserve, Chara.memberType, LayerPeople.multi, Spatial.Name, Card.NameSimple, CardRenderer.OnEnterScreen(), CardRenderer.OnLeaveScreen(), LayerPeople.OnSwitchContent(), UIMultiList.owners, EClass.pc, Chara.pccData, ListOwner< T1, T2 >.RefreshTab(), Card.renderer, Msg.Say(), EClass.scene, Chara.SetAI(), BaseCard.SetInt(), Layer.SetOnKill(), UIContextMenu.Show(), Chara.sourceCard, Scene.syncList, EClass.ui, Card.uid, FactionBranch.uidMaid, Layer.windows, and EClass.world.
Referenced by List().
OnInstantiate()
override void BaseListPeople.OnInstantiate (Chara a, ItemGeneral b) inline
Definition at line 63 of file BaseListPeople.cs.
    {
        SetSubText(a, b);
        if (ShowHome)
        {
            if (a.IsPCFaction)
            {
                Sprite icon = a.affinity.GetIcon();
                if ((bool)icon)
                {
                    Util.Instantiate<UIItem>("UI/Element/Grid/Attach/affinity", b).image1.sprite = icon;
                }
            }
            AddSubButtonWork(b, a);
            Room room = a.FindRoom();
            TraitBed bed = a.FindBed();
            if (a.memberType == FactionMemberType.Default)
            {
                b.AddSubButton(EClass.core.refs.icons.home, delegate
                {
                    if (room == null)
                    {
                        SE.BeepSmall();
                    }
                    else
                    {
                        EClass.pc.SetAI(new AI_Goto(room.GetRandomFreePos(), 1));
                        layer.Close();
                    }
                }, null, delegate(UITooltip t)
                {
                    t.note.Clear();
                    t.note.AddHeader("infoHome".lang((room != null) ? room.Name : "none".lang()));
                    t.note.AddTopic("TopicLeft", "infoBed".lang(), (bed != null) ? bed.Name.ToTitleCase() : "none".lang());
                    t.note.Build();
                    if (room != null)
                    {
                        EClass.core.actionsNextFrame.Add(delegate
{
                        });
                    }
                }).icon.SetAlpha((bed != null) ? 1f : 0.4f);
            }
        }
        if (ShowCharaSheet && EClass.debug.showExtra)
        {
            b.AddSubButton(EClass.core.refs.icons.inspect, delegate
            {
                SE.Play("pop_paper");
                LayerChara layerChara = EClass.ui.AddLayerDontCloseOthers<LayerChara>();
                layerChara.windows[0].SetRect(EClass.core.refs.rects.center);
                layerChara.SetChara(a);
            }, "charaInfo");
        }
        if (IsDisabled(a))
        {
            b.gameObject.AddComponent<CanvasGroup>().alpha = 0.6f;
        }
    }
References BaseCore.actionsNextFrame, UINote.AddHeader(), ItemGeneral.AddSubButton(), AddSubButtonWork(), UINote.AddTopic(), Chara.affinity, bed, UINote.Build(), UINote.Clear(), EClass.core, Chara.FindBed(), Chara.FindRoom(), Affinity.GetIcon(), CoreRef.Icons.home, CoreRef.icons, Chara.IsPCFaction, Chara.memberType, BaseArea.Name, UITooltip.note, Core.refs, SetSubText(), ShowHome, and Util.
Referenced by List().
OnList()
override void BaseListPeople.OnList () inline virtual
Reimplemented from ListOwner< Chara, ItemGeneral >.
Reimplemented in ListPeopleBed, ListPeopleBuySlave, ListPeopleCallReserve, ListPeopleEmbark, ListPeopleExpedition, ListPeopleRevive, and ListPeopleSelect.
Definition at line 434 of file BaseListPeople.cs.
    {
        if (memberType == FactionMemberType.Guest)
        {
            foreach (Chara chara in EClass._map.charas)
            {
                if (chara.IsGuest())
                {
                    list.Add(chara);
                }
            }
            return;
        }
        foreach (Chara member in EClass.Branch.members)
        {
            if (member.memberType == memberType && !member.isSummon)
            {
                list.Add(member);
            }
        }
        foreach (Chara member2 in EClass.pc.party.members)
        {
            if (member2.memberType == memberType && !list.items.Contains(member2))
            {
                list.Add(member2);
            }
        }
    }
References EClass._map, EClass.Branch, Map.charas, Chara.IsGuest(), Card.isSummon, FactionBranch.members, Party.members, Chara.memberType, Chara.party, and EClass.pc.
Referenced by List().
OnRefreshMenu()
override void BaseListPeople.OnRefreshMenu () inline virtual
Reimplemented from ListOwner< Chara, ItemGeneral >.
Reimplemented in ListPeopleBed, and ListPeopleEmbark.
Definition at line 463 of file BaseListPeople.cs.
    {
        WindowMenu menuLeft = window.menuLeft;
        menuLeft.Clear();
        if (!main)
        {
            return;
        }
        menuLeft.AddButton2Line("sort", () => list.sortMode.ToString(), delegate
        {
            list.NextSort();
        });
        if (ShowShowMode)
        {
            Lang.GetList("info_people");
            menuLeft.AddButton2Line("info", () => "show" + layer.showMode, delegate
            {
                layer.showMode = layer.showMode.NextEnum();
                List();
            });
        }
    }
References WindowMenu.AddButton2Line(), WindowMenu.Clear(), Lang.GetList(), and LayerPeople.showMode.
SetSubText()
virtual void BaseListPeople.SetSubText (Chara a, ItemGeneral b) inline virtual
Reimplemented in ListPeopleExpedition.
Definition at line 239 of file BaseListPeople.cs.
    {
        switch (ShowMode)
        {
        case LayerPeople.ShowMode.Race:
            b.SetSubText(a.race.GetName().ToTitleCase(wholeText: true), 300);
            break;
        case LayerPeople.ShowMode.Job:
            b.SetSubText(a.job.GetName().ToTitleCase(wholeText: true), 300);
            break;
        case LayerPeople.ShowMode.Work:
        {
            string text = a.GetTextWork(simple: true) + "," + a.GetTextHobby(simple: true);
            b.SetSubText(text.TrimEnd(','), 300);
            break;
        }
        }
    }
References Chara.GetTextHobby(), Chara.GetTextWork(), Chara.job, Chara.race, and ItemGeneral.SetSubText().
Referenced by OnInstantiate().
WriteHobbies()
void BaseListPeople.WriteHobbies (UITooltip t, Chara a, BaseArea roomWork) inline
Definition at line 152 of file BaseListPeople.cs.
    {
        t.note.Clear();
        t.note.AddHeader("infoWork".lang((roomWork != null) ? roomWork.Name : "none".lang()));
        foreach (Hobby item in a.ListWorks())
        {
            AddText(item, "work", a.source.works.Contains(item.source.alias));
        }
        foreach (Hobby item2 in a.ListHobbies())
        {
            AddText(item2, "hobby", a.source.hobbies.Contains(item2.source.alias));
        }
        if (a.IsPCParty)
        {
            t.note.Space(8);
            t.note.AddText("workNotActive_party".lang(), FontColor.Warning);
        }
        if (a.IsPCFactionOrMinion && !a.trait.IsCountAsResident)
        {
            t.note.AddText("notCountResident".lang(), FontColor.Good);
        }
        t.note.Build();
        void AddText(Hobby h, string lang, bool fix)
        {
            int efficiency = h.GetEfficiency(a);
            string text = h.Name;
            if (fix)
            {
                text += "*";
            }
            text = text.TagColor((efficiency == 0) ? FontColor.Warning : FontColor.Good);
            string[] array = Lang.GetList("work_lv");
            string text2 = array[Mathf.Clamp(efficiency / 50, (efficiency != 0) ? 1 : 0, array.Length - 1)];
            t.note.AddTopic("TopicLeft", lang.lang(), text + " (" + text2 + ")");
            if (!h.source.destTrait.IsEmpty())
            {
                bool flag = EClass._map.FindThing(Type.GetType("Trait" + h.source.destTrait + ", Elin"), a) != null;
                List<CardRow> obj = EClass.sources.cards.rows.Where((CardRow t) => t.trait.Length != 0 && Type.GetType("Trait" + h.source.destTrait).IsAssignableFrom(Type.GetType("Trait" + t.trait[0]))).ToList();
                obj.Sort((CardRow a, CardRow b) => a.LV - b.LV);
                CardRow cardRow = obj[0];
                t.note.AddText("NoteText_small", " " + "workDestTrait".lang(cardRow.GetName().ToTitleCase().TagColor(flag ? FontColor.Good : FontColor.Warning)));
            }
            if (efficiency == 0)
            {
                t.note.AddText("NoteText_small", " " + "workNotActive".lang());
            }
            else
            {
                for (int i = 0; i < h.source.things.Length; i += 2)
                {
                    int num = Mathf.Max(1, h.source.things[i + 1].ToInt() * efficiency * a.homeBranch.GetProductBonus(a) / 100 / 1000);
                    string text3 = h.source.things[i];
                    string s = (text3.StartsWith("#") ? EClass.sources.categories.map[text3.Replace("#", "")].GetName() : EClass.sources.cards.map[h.source.things[i]].GetName());
                    if (h.source.alias == "Breeding")
                    {
                        num = a.race.breeder * 100 / 2500;
                        num = num * ((!(text3 == "_egg")) ? 1 : 2) / 3;
                        if (a.race.breeder > 0 && num <= 0)
{
                            num = 1;
                        }
                    }
                    t.note.AddText("NoteText_small", " " + "work_produce".lang(s.ToTitleCase(), num.ToString() ?? ""));
                }
                if (!h.source.elements.IsEmpty())
                {
                    for (int j = 0; j < h.source.elements.Length; j += 2)
                    {
                        SourceElement.Row row = EClass.sources.elements.map[h.source.elements[j]];
                        int num2 = h.source.elements[j + 1];
                        int num3 = ((num2 < 0 || row.id == 2115 || row.id == 2207) ? (num2 / 10) : Mathf.Max(0, num2 * h.GetEfficiency(a) * a.homeBranch.efficiency / 100 / 1000));
                        t.note.AddText("NoteText_small", " " + "workBonus_skill".lang(row.GetName().ToTitleCase(), ((num2 > 0) ? "+" : "") + num3) + ((row.id == 2115 || row.id == 2207) ? (" " + "fixedFactionSkill".lang()) : ""), (num2 >= 0) ? FontColor.Default : FontColor.Bad);
                    }
                }
                string[] array2 = h.source.GetDetail().SplitNewline();
                foreach (string text4 in array2)
                {
                    if (!text4.IsEmpty())
                    {
                        t.note.AddText("NoteText_small", " " + text4);
                    }
                }
            }
            t.note.Space(1);
        }
    }
References EClass._map, UINote.AddHeader(), SourceManager.cards, SourceManager.categories, UINote.Clear(), SourceManager.elements, Map.FindThing(), Hobby.GetEfficiency(), Lang.GetList(), SourceElement.Row.GetName(), CardRow.GetName(), SourceElement.Row.id, item, RenderRow.LV, SourceCard.map, BaseArea.Name, Hobby.Name, UITooltip.note, SourceCard.rows, Hobby.source, EClass.sources, and CardRow.trait.
Referenced by ListPeopleBed.OnInstantiate().
Member Data Documentation
memberType
FactionMemberType BaseListPeople.memberType
Definition at line 10 of file BaseListPeople.cs.
owner
Chara BaseListPeople.owner
Definition at line 8 of file BaseListPeople.cs.
Referenced by ListPeopleBuySlave.OnCreate().
Property Documentation
IdHeaderRow
override string BaseListPeople.IdHeaderRow get
Definition at line 14 of file BaseListPeople.cs.
layer
new LayerPeople BaseListPeople.layer get
Definition at line 12 of file BaseListPeople.cs.
ShowCharaSheet
virtual bool BaseListPeople.ShowCharaSheet get
Definition at line 16 of file BaseListPeople.cs.
ShowGoto
virtual bool BaseListPeople.ShowGoto get
Definition at line 22 of file BaseListPeople.cs.
ShowHome
virtual bool BaseListPeople.ShowHome get
Definition at line 24 of file BaseListPeople.cs.
Referenced by OnInstantiate().
ShowMode
virtual LayerPeople.ShowMode BaseListPeople.ShowMode get
Definition at line 20 of file BaseListPeople.cs.
ShowShowMode
virtual bool BaseListPeople.ShowShowMode get
Definition at line 18 of file BaseListPeople.cs.
The documentation for this class was generated from the following file:
Elin/BaseListPeople.cs