Elin Decompiled Documentation: ProceduralMesh Class Reference
ProceduralMesh Class Reference
Public Member Functions
Mesh GetMesh ()
void Create ()
void AddTriangles ()
Public Attributes
Vector2 tiling = Vector2.one
float UVPadding = 0.02f
Vector3 pos = new Vector3(0f, 0f, -1f)
Vector3 offset
Vector3 size = Vector3.one
bool top
bool calculateNormal = true
Private Member Functions
Vector2[] GetUVs (int id)
Private Attributes
Mesh mesh
List< int > triangles = new List<int>()
List< Vector3 > vertices = new List<Vector3>()
List< Vector2 > uv = new List<Vector2>()
int triOffset
Detailed Description
Definition at line 4 of file ProceduralMesh.cs.
Member Function Documentation
AddTriangles()
void ProceduralMesh.AddTriangles () inline
Definition at line 79 of file ProceduralMesh.cs.
    {
        triangles.AddRange(new int[6]
        {
            triOffset,
            1 + triOffset,
            2 + triOffset,
            2 + triOffset,
            3 + triOffset,
            triOffset
        });
        triOffset += 4;
    }
References triangles, and triOffset.
Referenced by Create().
Create()
void ProceduralMesh.Create () inline
Definition at line 39 of file ProceduralMesh.cs.
    {
        mesh = new Mesh();
        triOffset = 0;
        triangles.Clear();
        vertices.Clear();
        uv.Clear();
        if (top)
        {
            vertices.AddRange(new Vector3[4]
            {
                new Vector3(0f, size.y, size.z) + pos,
                new Vector3(size.x, size.y, size.z) + pos,
                new Vector3(size.x, size.y, 0f) + pos,
                new Vector3(0f, size.y, 0f) + pos
            });
            uv.AddRange(GetUVs(0));
            AddTriangles();
        }
        else
        {
            vertices.AddRange(new Vector3[4]
            {
                new Vector3(0f, size.y, 0f) + pos,
                new Vector3(size.x, size.y, 0f) + pos,
                new Vector3(size.x, offset.y, 0f) + pos,
                new Vector3(0f, offset.y, 0f) + pos
            });
            uv.AddRange(GetUVs(0));
            AddTriangles();
        }
        mesh.SetVertices(vertices);
        mesh.SetUVs(0, uv);
        mesh.SetTriangles(triangles, 0);
        if (calculateNormal)
        {
            mesh.RecalculateNormals();
        }
    }
References AddTriangles(), calculateNormal, GetUVs(), mesh, offset, pos, size, top, triangles, triOffset, uv, and vertices.
Referenced by GetMesh().
GetMesh()
Mesh ProceduralMesh.GetMesh () inline
Definition at line 30 of file ProceduralMesh.cs.
    {
        if (!mesh)
        {
            Create();
        }
        return mesh;
    }
References Create(), and mesh.
Referenced by MeshPass._Refresh().
GetUVs()
Vector2[] ProceduralMesh.GetUVs (int id) inline private
Definition at line 93 of file ProceduralMesh.cs.
    {
        Vector2[] array = new Vector2[4];
        Vector2 vector = new Vector2(1f / tiling.x, 1f / tiling.y);
        int num = id % (int)tiling.x;
        int num2 = id / (int)tiling.x;
        float num3 = UVPadding / tiling.x;
        array[0] = new Vector2((float)num / tiling.x + num3, 1f - (float)num2 / tiling.y - num3);
        array[1] = new Vector2((float)num / tiling.x + vector.x - num3, 1f - (float)num2 / tiling.y - num3);
        array[2] = new Vector2((float)num / tiling.x + vector.x - num3, 1f - ((float)num2 / tiling.y + vector.y) + num3);
        array[3] = new Vector2((float)num / tiling.x + num3, 1f - ((float)num2 / tiling.y + vector.y) + num3);
        return array;
    }
References tiling, and UVPadding.
Referenced by Create().
Member Data Documentation
calculateNormal
bool ProceduralMesh.calculateNormal = true
Definition at line 18 of file ProceduralMesh.cs.
Referenced by Create().
mesh
Mesh ProceduralMesh.mesh private
Definition at line 20 of file ProceduralMesh.cs.
Referenced by Create(), and GetMesh().
offset
Vector3 ProceduralMesh.offset
Definition at line 12 of file ProceduralMesh.cs.
Referenced by Create().
pos
Vector3 ProceduralMesh.pos = new Vector3(0f, 0f, -1f)
Definition at line 10 of file ProceduralMesh.cs.
Referenced by Create(), and RenderRow.SetRenderData().
size
Vector3 ProceduralMesh.size = Vector3.one
Definition at line 14 of file ProceduralMesh.cs.
Referenced by Create(), RenderDataObjV.Draw(), and RenderDataTile.Draw().
tiling
Vector2 ProceduralMesh.tiling = Vector2.one
Definition at line 6 of file ProceduralMesh.cs.
Referenced by TextureManager.AddBase(), RenderData.ConvertTile(), RenderDataObjAdd.Draw(), RenderDataObjV.Draw(), RenderRow.GetSprite(), GetUVs(), RenderRow.SetTiles(), SourceChara.Row.SetTiles(), and SourceThing.Row.SetTiles().
top
bool ProceduralMesh.top
Definition at line 16 of file ProceduralMesh.cs.
Referenced by Create().
triangles
List<int> ProceduralMesh.triangles = new List<int>() private
Definition at line 22 of file ProceduralMesh.cs.
Referenced by AddTriangles(), and Create().
triOffset
int ProceduralMesh.triOffset private
Definition at line 28 of file ProceduralMesh.cs.
Referenced by AddTriangles(), and Create().
uv
List<Vector2> ProceduralMesh.uv = new List<Vector2>() private
Definition at line 26 of file ProceduralMesh.cs.
Referenced by Create().
UVPadding
float ProceduralMesh.UVPadding = 0.02f
Definition at line 8 of file ProceduralMesh.cs.
Referenced by GetUVs().
vertices
List<Vector3> ProceduralMesh.vertices = new List<Vector3>() private
Definition at line 24 of file ProceduralMesh.cs.
Referenced by Create().
The documentation for this class was generated from the following file:
Elin/ProceduralMesh.cs