Elin Decompiled Documentation: ExcelParser Class Reference
ExcelParser Class Reference
Static Public Member Functions
static bool IsNull (ICell cell)
static int GetInt (int id)
static int GetInt (int col, IRow _row)
static bool GetBool (int id)
static bool GetBool (int col, IRow _row)
static double GetDouble (int id)
static float GetFloat (int id)
static float[] GetFloatArray (int id)
static int[] GetIntArray (int id)
static string[] GetStringArray (int id)
static string GetString (int id)
static string GetString (int col, IRow _row)
static string GetStr (int id, bool useDefault=false)
static string ToLetterId (int id)
static void ReportIllFormat< T > (int id)
Static Public Attributes
static string path
static IRow row
static IRow rowDefault
Detailed Description
Definition at line 6 of file ExcelParser.cs.
Member Function Documentation
GetBool() [1/2]
static bool ExcelParser.GetBool (int col, IRow _row) inline static
Definition at line 56 of file ExcelParser.cs.
    {
        row = _row;
        return GetBool(col);
    }
References GetBool(), and row.
GetBool() [2/2]
static bool ExcelParser.GetBool (int id) inline static
Definition at line 43 of file ExcelParser.cs.
    {
        string str = GetStr(id);
        bool result;
        return str switch
        {
            null => false,
            "1" => true,
            "0" => false,
            _ => bool.TryParse(str, out result) && result,
        };
    }
References GetStr().
Referenced by GetBool(), SourceData< T, T2 >.GetBool(), and TextConv.Item.Item().
GetDouble()
static double ExcelParser.GetDouble (int id) inline static
Definition at line 62 of file ExcelParser.cs.
    {
        string str = GetStr(id);
        if (str.IsEmpty())
        {
            return 0.0;
        }
        if (!double.TryParse(str, out var result))
        {
            ReportIllFormat<double>(id);
        }
        return result;
    }
References GetStr().
Referenced by SourceData< T, T2 >.GetDouble().
GetFloat()
static float ExcelParser.GetFloat (int id) inline static
Definition at line 76 of file ExcelParser.cs.
    {
        string str = GetStr(id);
        if (str.IsEmpty())
        {
            return 0f;
        }
        if (!float.TryParse(str, out var result))
        {
            ReportIllFormat<float>(id);
        }
        return result;
    }
References GetStr().
Referenced by SourceData< T, T2 >.GetFloat().
GetFloatArray()
static float[] ExcelParser.GetFloatArray (int id) inline static
Definition at line 90 of file ExcelParser.cs.
    {
        string str = GetStr(id);
        if (str.IsEmpty())
        {
            return Array.Empty<float>();
        }
        string[] array = str.Split(',');
        float[] array2 = new float[array.Length];
        for (int i = 0; i < array.Length; i++)
        {
            if (!float.TryParse(array[i], out array2[i]))
            {
                ReportIllFormat<float>(id);
                array2[i] = 0f;
            }
        }
        return array2;
    }
References GetStr().
Referenced by SourceData< T, T2 >.GetFloatArray().
GetInt() [1/2]
static int ExcelParser.GetInt (int col, IRow _row) inline static
Definition at line 37 of file ExcelParser.cs.
    {
        row = _row;
        return GetInt(col);
    }
References GetInt(), and row.
GetInt() [2/2]
static int ExcelParser.GetInt (int id) inline static
Definition at line 23 of file ExcelParser.cs.
    {
        string str = GetStr(id);
        if (str.IsEmpty())
        {
            return 0;
        }
        if (!int.TryParse(str, out var result))
        {
            ReportIllFormat<int>(id);
        }
        return result;
    }
References GetStr().
Referenced by TextConv.BuildMap(), GetInt(), and SourceData< T, T2 >.GetInt().
GetIntArray()
static int[] ExcelParser.GetIntArray (int id) inline static
Definition at line 110 of file ExcelParser.cs.
    {
        string str = GetStr(id);
        if (str.IsEmpty())
        {
            return Array.Empty<int>();
        }
        string[] array = str.Split(',');
        int[] array2 = new int[array.Length];
        for (int i = 0; i < array.Length; i++)
        {
            if (!int.TryParse(array[i], out array2[i]))
            {
                ReportIllFormat<int>(id);
                array2[i] = 0;
            }
        }
        return array2;
    }
References GetStr().
Referenced by SourceData< T, T2 >.GetIntArray().
GetStr()
static string ExcelParser.GetStr (int id, bool useDefault = false) inline static
Definition at line 151 of file ExcelParser.cs.
    {
        IRow row = (useDefault ? rowDefault : ExcelParser.row);
        if (row == null)
        {
            if (!useDefault)
            {
                return GetStr(id, useDefault: true);
            }
            return null;
        }
        ICell cell = row.GetCell(id);
        if (IsNull(cell))
        {
            if (!useDefault)
            {
                return GetStr(id, useDefault: true);
            }
            return null;
        }
        cell.SetCellType(CellType.String);
        if (cell.StringCellValue == "")
        {
            if (!useDefault)
            {
                return GetStr(id, useDefault: true);
            }
            return null;
        }
        return cell.StringCellValue;
    }
References GetStr(), IsNull(), row, and rowDefault.
Referenced by GetBool(), GetDouble(), GetFloat(), GetFloatArray(), GetInt(), GetIntArray(), GetStr(), SourceData< T, T2 >.GetStr(), GetString(), and GetStringArray().
GetString() [1/2]
static string ExcelParser.GetString (int col, IRow _row) inline static
Definition at line 145 of file ExcelParser.cs.
    {
        row = _row;
        return GetStr(col);
    }
References GetStr(), and row.
GetString() [2/2]
static string ExcelParser.GetString (int id) inline static
Definition at line 140 of file ExcelParser.cs.
    {
        return GetStr(id) ?? "";
    }
References GetStr().
Referenced by SourceData< T, T2 >.GetString(), and ExcelData.Override().
GetStringArray()
static string[] ExcelParser.GetStringArray (int id) inline static
Definition at line 130 of file ExcelParser.cs.
    {
        string str = GetStr(id);
        if (str != null)
        {
            return str.Split(',');
        }
        return Array.Empty<string>();
    }
References GetStr().
Referenced by SourceData< T, T2 >.GetStringArray().
IsNull()
static bool ExcelParser.IsNull (ICell cell) inline static
Definition at line 14 of file ExcelParser.cs.
    {
        if (cell != null && cell.CellType != CellType.Blank)
        {
            return cell.CellType == CellType.Unknown;
        }
        return true;
    }
Referenced by GetStr().
ReportIllFormat< T >()
static void ExcelParser.ReportIllFormat< T > (int id) inline static
Definition at line 195 of file ExcelParser.cs.
    {
        StringBuilder stringBuilder = new StringBuilder();
        string name = typeof(T).Name;
        ICell cell = row?.Cells.TryGet(id, returnNull: true);
        IRow obj = row;
        string value = ((obj != null && obj.RowNum >= 3) ? $", default:'{rowDefault?.Cells.TryGet(id, returnNull: true)}'" : ", SourceData begins at the 4th row. 3rd row is the default value row.");
        stringBuilder.AppendLine("$source ill-format file: " + path);
        object[] array = new object[5];
        IRow obj2 = row;
        array[0] = ((obj2 != null) ? new int?(obj2.RowNum + 1) : null);
        array[1] = id + 1;
        array[2] = ToLetterId(id);
        array[3] = name;
        array[4] = cell;
        stringBuilder.Append(string.Format("row#{0}, cell'{1}'/'{2}', expected:'{3}', read:'{4}'", array));
        stringBuilder.AppendLine(value);
        Debug.LogError(stringBuilder);
    }
References $, Debug, path, row, and ToLetterId().
ToLetterId()
static string ExcelParser.ToLetterId (int id) inline static
Definition at line 183 of file ExcelParser.cs.
    {
        string text = "";
        while (id >= 0)
        {
            text = (char)(id % 26 + 65) + text;
            id /= 26;
            id--;
        }
        return text;
    }
Referenced by ReportIllFormat< T >().
Member Data Documentation
path
string ExcelParser.path static
Definition at line 8 of file ExcelParser.cs.
Referenced by ReportIllFormat< T >().
row
IRow ExcelParser.row static
Definition at line 10 of file ExcelParser.cs.
Referenced by GetBool(), GetInt(), GetStr(), GetString(), and ReportIllFormat< T >().
rowDefault
IRow ExcelParser.rowDefault static
Definition at line 12 of file ExcelParser.cs.
Referenced by GetStr().
The documentation for this class was generated from the following file:
Elin/Plugins.basecore/ExcelParser.cs