Elin Decompiled Documentation: WidgetSticky Class Reference
WidgetSticky Class Reference
Classes
class Extra
Public Member Functions
override object CreateExtra ()
override void OnActivate ()
void Init ()
void _Add (BaseSticky sticky, bool animate=true)
void _Remove (BaseSticky sticky)
void Refresh ()
override void OnSetContextMenu (UIContextMenu m)
Public Member Functions inherited from Widget
void Test ()
bool IsInRightMode ()
void Activate ()
void RefreshOrder ()
virtual void OnActivate ()
virtual object CreateExtra ()
void Deactivate ()
virtual void OnDeactivate ()
void Close ()
void Reactivate ()
virtual void OnManagerActivate ()
virtual void OnManagerDeactivate ()
void SetAnchor (RectPosition p)
void SetPivot (RectPosition p)
virtual void OnChangePivot ()
void UpdateConfig ()
virtual void OnUpdateConfig ()
void ClampToScreen ()
virtual void OnChangeResolution ()
void OnChangePosition ()
virtual void OnChangeActionMode ()
virtual void OnFlip ()
bool IsAlignTop ()
Layer AddLayer (Layer l, Transform trans)
void RefreshTipPivotPosition ()
SkinSet GetSkin ()
SkinConfig GetSkinConfig ()
void SetSkin (int id, int v=0)
void TestSkin ()
virtual void ApplySkin ()
virtual void OnApplySkin ()
void InstantiateDeco (SkinDeco deco)
void AddDeco (SkinDeco deco)
void RemoveDeco (SkinDeco deco)
virtual bool CanShowContextMenu ()
void ShowContextMenu ()
void SetBaseContextMenu (UIContextMenu m)
virtual void OnSetContextMenu (UIContextMenu m)
void SetGridContextMenu (UIContextMenu m)
void SoundActivate ()
void OnChangeResolution ()
SkinSet GetSkin ()
SkinConfig GetSkinConfig ()
Static Public Member Functions
static void Add (BaseSticky sticky, bool animate=true)
Static Public Member Functions inherited from EMono
static int rnd (int a)
Public Attributes
LayoutGroup layout
List< BaseSticky > list = new List<BaseSticky>()
List< Sprite > icons
UIItem mold
Anime anime
Public Attributes inherited from Widget
Image imageBG
SoundData soundActivate
UIDragPanel dragPanel
RectTransform tipPivotLeft
RectTransform tipPivotRight
Static Public Attributes
static WidgetSticky Instance
Static Public Attributes inherited from EMono
static Core core
Properties
Extra extra [get]
Properties inherited from Widget
string ID [get]
Config config [get]
SkinRoot skinRoot [get]
bool IsSealed [get]
virtual bool ShowStyleMenu [get]
virtual bool AlwaysTop [get]
virtual bool IsStaticPosition [get]
virtual bool AlwaysBottom [get]
virtual Type SetSiblingAfter [get]
virtual bool ShowInBuildMode [get]
virtual bool RightClickToClose [get]
virtual bool AllowRightClickToClose [get]
Properties inherited from EMono
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SoundManager Sound [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static CoreDebug debug [get]
Additional Inherited Members
Public Types inherited from Widget
enum WidgetType { Default , ZoomMenu }
enum State { Active , Inactive }
Protected Member Functions inherited from Widget
void ClampToScreenEnsured (Component c, Vector2 anchoredPos)
void ClampToScreen (RectTransform rect, float margin=10f)
Protected Attributes inherited from Widget
bool flip
Detailed Description
Definition at line 5 of file WidgetSticky.cs.
Member Function Documentation
_Add()
void WidgetSticky._Add (BaseSticky sticky, bool animate = true) inline
Definition at line 60 of file WidgetSticky.cs.
    {
        if (!sticky.AllowMultiple)
        {
            list.ForeachReverse(delegate(BaseSticky i)
            {
                if (i.GetType().Equals(sticky.GetType()))
                {
                    _Remove(i);
                }
            });
        }
        list.Add(sticky);
        UIItem uIItem = (sticky.item = Util.Instantiate(mold, layout));
        uIItem.image1.transform.parent.SetActive(sticky.animate);
        uIItem.SetActive(enable: true);
        sticky.RefreshButton();
        uIItem.transform.SetAsFirstSibling();
        layout.RebuildLayout();
        if (animate)
        {
            anime.Play(uIItem.button1.transform);
            SE.Play(sticky.idSound);
        }
    }
References BaseSticky.AllowMultiple, BaseSticky.animate, anime, UIItem.button1, BaseSticky.idSound, UIItem.image1, layout, list, mold, Anime.Play(), BaseSticky.RefreshButton(), and Util.
Referenced by Add(), and Init().
_Remove()
void WidgetSticky._Remove (BaseSticky sticky) inline
Definition at line 86 of file WidgetSticky.cs.
    {
        list.Remove(sticky);
        Object.Destroy(sticky.item.gameObject);
    }
References BaseSticky.item, and list.
Referenced by BaseSticky.RefreshButton().
Add()
static void WidgetSticky.Add (BaseSticky sticky, bool animate = true) inline static
Definition at line 52 of file WidgetSticky.cs.
    {
        if ((bool)Instance)
        {
            Instance._Add(sticky);
        }
    }
References _Add(), and Instance.
Referenced by GameDate.AdvanceDay().
CreateExtra()
override object WidgetSticky.CreateExtra () inline virtual
Reimplemented from Widget.
Definition at line 30 of file WidgetSticky.cs.
    {
        return new Extra();
    }
Init()
void WidgetSticky.Init () inline
Definition at line 41 of file WidgetSticky.cs.
    {
        Instance = this;
        mold = layout.CreateMold<UIItem>();
        _Add(new StickyMenu(), animate: false);
        _Add(new StickyDate(), animate: false);
        _Add(new StickyWelcome(), animate: false);
        _Add(new StickyGacha(), animate: false);
        InvokeRepeating("Refresh", 0f, 1f);
    }
References _Add(), Instance, layout, and mold.
Referenced by OnActivate().
OnActivate()
override void WidgetSticky.OnActivate () inline virtual
Reimplemented from Widget.
Definition at line 35 of file WidgetSticky.cs.
    {
        Instance = this;
        Init();
    }
References Init(), and Instance.
OnSetContextMenu()
override void WidgetSticky.OnSetContextMenu (UIContextMenu m) inline virtual
Reimplemented from Widget.
Definition at line 105 of file WidgetSticky.cs.
    {
        UIContextMenu uIContextMenu = m.AddChild("setting");
        uIContextMenu.AddToggle("showDate", extra.showDate, delegate(bool a)
        {
            extra.showDate = a;
            Refresh();
        });
        uIContextMenu.AddToggle("showText", extra.showText, delegate(bool a)
        {
            extra.showText = a;
            Refresh();
        });
        uIContextMenu.AddToggle("showNerun", extra.showNerun, delegate(bool a)
        {
            extra.showNerun = a;
            Refresh();
        });
        m.AddChild("style").AddSlider("toggleButtonBG", (float a) => a.ToString() ?? "", base.config.skin.button, delegate(float a)
        {
            base.config.skin.button = (int)a;
            ApplySkin();
        }, 0f, base.config.skin.Skin.buttons.Count - 1, isInt: true);
        SetBaseContextMenu(m);
    }
References UIContextMenu.AddChild(), UIContextMenu.AddSlider(), UIContextMenu.AddToggle(), Widget.ApplySkin(), extra, Refresh(), Widget.SetBaseContextMenu(), WidgetSticky.Extra.showDate, WidgetSticky.Extra.showNerun, and WidgetSticky.Extra.showText.
Refresh()
void WidgetSticky.Refresh () inline
Definition at line 92 of file WidgetSticky.cs.
    {
        foreach (BaseSticky item in list)
        {
            bool shouldShow = item.ShouldShow;
            item.item.SetActive(shouldShow);
            if (shouldShow)
            {
                item.Refresh();
            }
        }
    }
References item, and list.
Referenced by StickyGacha.OnClick(), and OnSetContextMenu().
Member Data Documentation
anime
Anime WidgetSticky.anime
Definition at line 26 of file WidgetSticky.cs.
Referenced by _Add().
icons
List<Sprite> WidgetSticky.icons
Definition at line 22 of file WidgetSticky.cs.
Referenced by BaseSticky.RefreshButton().
Instance
WidgetSticky WidgetSticky.Instance static
Definition at line 16 of file WidgetSticky.cs.
Referenced by Add(), Init(), OnActivate(), and BaseSticky.RefreshButton().
layout
LayoutGroup WidgetSticky.layout
Definition at line 18 of file WidgetSticky.cs.
Referenced by _Add(), and Init().
list
List<BaseSticky> WidgetSticky.list = new List<BaseSticky>()
Definition at line 20 of file WidgetSticky.cs.
Referenced by _Add(), _Remove(), and Refresh().
mold
UIItem WidgetSticky.mold
Definition at line 24 of file WidgetSticky.cs.
Referenced by _Add(), and Init().
Property Documentation
extra
Extra WidgetSticky.extra get
Definition at line 28 of file WidgetSticky.cs.
Referenced by OnSetContextMenu(), and BaseSticky.RefreshButton().
The documentation for this class was generated from the following file:
Elin/WidgetSticky.cs