Elin Decompiled Documentation: ContentQuest Class Reference
ContentQuest Class Reference
Public Member Functions
override void OnSwitchContent (int idTab)
void RefreshTrackButtons ()
void SelectQuest (Quest q)
Public Member Functions inherited from UIContent
virtual void OnSwitchContent (int idTab)
virtual void OnInstantiate ()
Public Member Functions inherited from UINote
void Clear ()
void Build ()
void Space (int sizeY=0, int sizeX=1)
UINote AddNote (string id)
UIItem AddHeader (string text, Sprite sprite=null)
UIItem AddHeaderCard (string text, Sprite sprite=null)
UIItem AddHeaderTopic (string text, Sprite sprite=null)
UIItem AddHeader (string id, string text, Sprite sprite=null)
UIItem AddText (string text, FontColor color=FontColor.DontChange)
UIItem AddText (string id, string text, FontColor color=FontColor.DontChange)
UIItem AddText (string id, string text, Color color)
UIItem AddItem (string id)
UIItem AddTopic (string id, string text, string value=null)
UIItem AddTopic (string text, string value=null)
void AddImage (Sprite sprite)
void AddImage (string idFile)
UIButton AddButton (string text, Action onClick)
UIButton AddButtonLink (string text, string url)
UIDropdown AddDropdown (string id="DropdownDefault")
UIButton AddToggle (string idLang="", bool isOn=false, Action< bool > action=null)
Transform AddPrefab (string path)
T AddExtra< T > (string path)
Public Attributes
UIList list
UIText textClient
UIText textTitle
UIText textDetail
UIText textHours
UIText textNote
UIText textReward
UIText textZone
Portrait portrait
UIButton buttonAbandon
Public Attributes inherited from UINote
RectTransform target
UINoteProfile prof
SkinType skinType
string idDefaultText
LayoutGroup layout
RectTransform cur
bool extraRebuild
Detailed Description
Definition at line 4 of file ContentQuest.cs.
Member Function Documentation
OnSwitchContent()
override void ContentQuest.OnSwitchContent (int idTab) inline virtual
Reimplemented from UIContent.
Definition at line 26 of file ContentQuest.cs.
    {
        list.sortMode = UIList.SortMode.ByValue;
        list.callbacks = new UIList.Callback<Quest, ItemGeneral>
        {
            onInstantiate = delegate(Quest a, ItemGeneral b)
            {
                b.SetSound();
                string text = a.GetTitle();
                if (EClass.debug.showExtra)
                {
                    text = text + "(" + a.phase + ")";
                }
                b.button1.mainText.SetText(a.TitlePrefix + text);
                b.SetSubText(a.TextDeadline, 260, FontColor.Default, TextAnchor.MiddleRight);
                b.button2.SetActive(EClass.debug.enable && a.CanAutoAdvance);
                if (EClass.debug.enable && a.CanAutoAdvance)
                {
                    b.button2.SetOnClick(delegate
                    {
                        if (a.task != null)
{
                            a.CompleteTask();
                        }
                        else if (a is QuestSequence)
{
                            a.NextPhase();
                        }
                        else
{
                            a.Complete();
                        }
                        list.List();
                    });
                }
                b.button3.SetOnClick(delegate
                {
                    a.track = !a.track;
                    if (!WidgetQuestTracker.Instance)
                    {
                        EClass.player.questTracker = true;
                        EClass.ui.widgets.ActivateWidget("QuestTracker");
                        WidgetHotbar.RefreshButtons();
                    }
                    WidgetQuestTracker.Instance.Refresh();
                    list.Select(a);
                    SelectQuest(a);
                    RefreshTrackButtons();
                });
            },
            onClick = delegate(Quest a, ItemGeneral b)
            {
                SelectQuest(a);
            },
            onList = delegate
            {
                foreach (Quest item in EClass.game.quests.list)
                {
                    list.Add(item);
                }
            },
            onSort = (Quest a, UIList.SortMode m) => -EClass.sources.quests.rows.IndexOf(a.source)
        };
        list.List();
        SelectQuest(list.items[0] as Quest);
        RefreshTrackButtons();
    }
References UIList.Add(), UIItem.button1, UIItem.button2, UIItem.button3, Quest.CanAutoAdvance, Quest.Complete(), EClass.debug, CoreDebug.enable, EClass.game, Quest.GetTitle(), if(), WidgetQuestTracker.Instance, item, UIList.items, list, UIList.List(), QuestManager.list, UIButton.mainText, Quest.NextPhase(), Game.quests, SourceManager.quests, WidgetQuestTracker.Refresh(), RefreshTrackButtons(), UIList.Select(), SelectQuest(), ItemGeneral.SetSound(), ItemGeneral.SetSubText(), UIText.SetText(), CoreDebug.showExtra, Quest.source, EClass.sources, Quest.task, Quest.TextDeadline, Quest.TitlePrefix, and Quest.track.
Referenced by SelectQuest().
RefreshTrackButtons()
void ContentQuest.RefreshTrackButtons () inline
Definition at line 94 of file ContentQuest.cs.
    {
        foreach (UIList.ButtonPair button in list.buttons)
        {
            ClassExtension.SetActive(enable: (button.obj as Quest).track, c: (button.component as ItemGeneral).button3.icon);
        }
    }
References UIList.buttons, list, and ClassExtension.SetActive().
Referenced by OnSwitchContent().
SelectQuest()
void ContentQuest.SelectQuest (Quest q) inline
Definition at line 102 of file ContentQuest.cs.
    {
        buttonAbandon.SetActive(q.CanAbandon);
        buttonAbandon.SetOnClick(delegate
        {
            Dialog.YesNo("dialog_abandonQuest", delegate
            {
                Msg.Say("questAbandon", q.GetTitle());
                q.Fail();
                OnSwitchContent(0);
            });
        });
        textClient.text = q.person.NameBraced;
        textReward.SetText(q.GetRewardText());
        string text = q.GetDetail(onJournal: true);
        if (EClass.debug.showExtra && q.person != null)
        {
            text += Environment.NewLine;
            text = text + q.person.id + "/" + q.person.name + "/" + q.person.chara?.ToString() + Environment.NewLine;
            if (q is QuestDeliver questDeliver)
            {
                text = text + questDeliver.uidDest + "/" + questDeliver.DestChara;
            }
        }
        textDetail.SetText(text);
        textHours.text = q.TextDeadline;
        textZone.text = q.ClientZone?.Name ?? "-";
        portrait.SetPerson(q.person);
        this.RebuildLayout(recursive: true);
    }
References buttonAbandon, Quest.CanAbandon, Person.chara, Quest.ClientZone, EClass.debug, Quest.Fail(), Quest.GetDetail(), Quest.GetRewardText(), Quest.GetTitle(), Spatial.Name, Person.NameBraced, OnSwitchContent(), Quest.person, portrait, Msg.Say(), Portrait.SetPerson(), UIText.SetText(), CoreDebug.showExtra, Quest.TextDeadline, textDetail, textReward, Chara.ToString(), and Dialog.YesNo().
Referenced by OnSwitchContent().
Member Data Documentation
buttonAbandon
UIButton ContentQuest.buttonAbandon
Definition at line 24 of file ContentQuest.cs.
Referenced by SelectQuest().
list
UIList ContentQuest.list
Definition at line 6 of file ContentQuest.cs.
Referenced by OnSwitchContent(), and RefreshTrackButtons().
portrait
Portrait ContentQuest.portrait
Definition at line 22 of file ContentQuest.cs.
Referenced by SelectQuest().
textClient
UIText ContentQuest.textClient
Definition at line 8 of file ContentQuest.cs.
textDetail
UIText ContentQuest.textDetail
Definition at line 12 of file ContentQuest.cs.
Referenced by SelectQuest().
textHours
UIText ContentQuest.textHours
Definition at line 14 of file ContentQuest.cs.
textNote
UIText ContentQuest.textNote
Definition at line 16 of file ContentQuest.cs.
textReward
UIText ContentQuest.textReward
Definition at line 18 of file ContentQuest.cs.
Referenced by SelectQuest().
textTitle
UIText ContentQuest.textTitle
Definition at line 10 of file ContentQuest.cs.
textZone
UIText ContentQuest.textZone
Definition at line 20 of file ContentQuest.cs.
The documentation for this class was generated from the following file:
Elin/ContentQuest.cs