Elin Decompiled Documentation: QuestTrackCraft Class Reference
QuestTrackCraft Class Reference
Public Member Functions
override string GetTitle ()
void SetRecipe (Recipe r)
override string GetDetail (bool onJournal=false)
Public Member Functions inherited from Quest
virtual Thing GetDestThing ()
virtual int GetExtraMoney ()
virtual int GetRewardPlat (int money)
override bool Equals (object obj)
virtual bool IsVisibleOnQuestBoard ()
virtual bool CanStartQuest ()
virtual bool CanUpdateOnTalk (Chara c)
virtual Zone CreateInstanceZone (Chara c)
virtual bool UpdateOnTalk ()
void Init ()
virtual void OnInit ()
Quest SetClient (Chara c, bool assignQuest=true)
void SetTask (QuestTask _task)
void Start ()
virtual void OnStart ()
virtual void OnEnterZone ()
virtual void OnClickQuest ()
void Fail ()
virtual void OnFail ()
virtual void ShowCompleteText ()
void Complete ()
virtual void OnBeforeComplete ()
virtual void OnDropReward ()
Thing DropReward (string id)
Thing DropReward (Thing t)
virtual void OnComplete ()
void CompleteTask ()
virtual void OnCompleteTask ()
virtual void OnGiveItem (Chara c, Thing t)
virtual void OnKillChara (Chara c)
virtual void OnModKarma (int a)
void NextPhase ()
void ChangePhase (int a)
virtual void OnChangePhase (int a)
string Parse (string s)
virtual string GetTitle ()
virtual string GetTrackerText ()
virtual string GetDetail (bool onJournal=false)
virtual string GetDetailText (bool onJournal=false)
virtual string GetTextProgress ()
string GetRewardText ()
virtual string GetTalkProgress ()
virtual string GetTalkComplete ()
void UpdateJournal ()
virtual bool IsDeliverTarget (Chara c)
virtual bool CanDeliverToClient (Chara c)
virtual bool CanDeliverToBox (Thing t)
virtual bool Deliver (Chara c, Thing t=null)
Public Attributes
string idRecipe
RecipeSource _recipe
List< Recipe.Ingredient > ingredients
Public Attributes inherited from Quest
string id
int uid
int uidClientZone
int phase
int lv
int deadline
int difficulty
int rewardMoney
int bonusMoney
int startDate
int dangerLv
bool isNew
bool isComplete
bool track
Person person
QuestTask task
RefChara refChara = new RefChara()
Properties
RecipeSource recipe [get]
override bool CanAbandon [get]
Properties inherited from Quest
Zone ClientZone [get]
Chara chara [get]
virtual SourceQuest.Row source [get]
bool Confetti [get]
bool IsExpired [get]
int Hours [get]
string TextDeadline [get]
virtual bool HasDLC [get]
virtual string idSource [get]
virtual string RewardSuffix [get]
virtual bool FameContent [get]
virtual string TextExtra [get]
virtual string TextExtra2 [get]
virtual int DangerLv [get]
virtual int AffinityGain [get]
virtual int BaseMoney [get]
virtual int KarmaOnFail [get]
virtual bool CanAbandon [get]
virtual int FameOnComplete [get]
virtual int RangeDeadLine [get]
virtual bool UseInstanceZone [get]
virtual bool ForbidTeleport [get]
virtual bool TrackOnStart [get]
virtual bool RequireClientInSameZone [get]
virtual DifficultyType difficultyType [get]
virtual Chara DestChara [get]
virtual string RefDrama1 [get]
virtual string RefDrama2 [get]
virtual string RefDrama3 [get]
virtual string RefDrama4 [get]
virtual string TitlePrefix [get]
virtual bool CanAutoAdvance [get]
virtual bool IsRandomQuest [get]
virtual string NameDeliver [get]
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Additional Inherited Members
Public Types inherited from Quest
enum DifficultyType {
Default , Deliver , Supply , Escort ,
Bulk , Meal , Farm , Music
}
enum SubReward { plat , gacha_coin , money2 , ticket_furniture }
Static Public Member Functions inherited from Quest
static Quest Create (string _id, string _idPerson=null, Chara c=null)
static List< Zone > ListDeliver ()
Static Public Member Functions inherited from EClass
static int rndSeed (int a, int seed)
static int rnd (long a)
static int rnd (int a)
static int curve (int _a, int start, int step, int rate=75)
static int sqrt (int a)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Static Public Attributes inherited from Quest
const int PhaseComplete = 999
Static Public Attributes inherited from EClass
static Core core
Detailed Description
Definition at line 5 of file QuestTrackCraft.cs.
Member Function Documentation
GetDetail()
override string QuestTrackCraft.GetDetail (bool onJournal = false) inline virtual
Reimplemented from Quest.
Definition at line 28 of file QuestTrackCraft.cs.
    {
        if (ingredients == null)
        {
            ingredients = recipe.GetIngredients();
        }
        string text = "";
        for (int i = 0; i < ingredients.Count; i++)
        {
            Recipe.Ingredient ingredient = ingredients[i];
            if (!text.IsEmpty())
            {
                text += Environment.NewLine;
            }
            ThingStack thingStack = EClass._map.Stocked.ListThingStack(ingredient, StockSearchMode.All);
            _ = thingStack.list;
            Thing thing = null;
            foreach (Thing item in thingStack.list)
            {
                if (thing == null || item.Num > thing.Num)
                {
                    thing = item;
                }
            }
            int num = thing?.Num ?? 0;
            if (num >= ingredient.req)
            {
                text += "trackCraft_met".lang().TagColor(FontColor.Good);
            }
            text = text + (ingredient.optional ? "+" : "") + ingredient.GetName() + " " + num + " / " + ingredient.req;
        }
        return text;
    }
References EClass._map, RecipeSource.GetIngredients(), ingredients, item, ThingStack.list, Props.ListThingStack(), recipe, and Map.Stocked.
GetTitle()
override string QuestTrackCraft.GetTitle () inline virtual
Reimplemented from Quest.
Definition at line 18 of file QuestTrackCraft.cs.
    {
        return "trackCraft_title".lang(recipe.Name, recipe.NameFactory);
    }
References RecipeSource.Name, RecipeSource.NameFactory, and recipe.
SetRecipe()
void QuestTrackCraft.SetRecipe (Recipe r) inline
Definition at line 23 of file QuestTrackCraft.cs.
    {
        idRecipe = r.id;
    }
References Recipe.id, and idRecipe.
Referenced by Recipe.ToggleTrack().
Member Data Documentation
_recipe
RecipeSource QuestTrackCraft._recipe
Definition at line 10 of file QuestTrackCraft.cs.
idRecipe
string QuestTrackCraft.idRecipe
Definition at line 8 of file QuestTrackCraft.cs.
Referenced by LayerCraft.RefreshTrackButton(), SetRecipe(), and Recipe.ToggleTrack().
ingredients
List<Recipe.Ingredient> QuestTrackCraft.ingredients
Definition at line 12 of file QuestTrackCraft.cs.
Referenced by GetDetail().
Property Documentation
CanAbandon
override bool QuestTrackCraft.CanAbandon get
Definition at line 16 of file QuestTrackCraft.cs.
recipe
RecipeSource QuestTrackCraft.recipe get
Definition at line 14 of file QuestTrackCraft.cs.
Referenced by GetDetail(), and GetTitle().
The documentation for this class was generated from the following file:
Elin/QuestTrackCraft.cs