Elin Decompiled Documentation: WidgetDate Class Reference
WidgetDate Class Reference
Classes
class Extra
Public Member Functions
override object CreateExtra ()
override void OnActivate ()
void _Refresh ()
override void OnChangePivot ()
override void OnSetContextMenu (UIContextMenu m)
Public Member Functions inherited from Widget
void Test ()
bool IsInRightMode ()
void Activate ()
void RefreshOrder ()
virtual void OnActivate ()
virtual object CreateExtra ()
void Deactivate ()
virtual void OnDeactivate ()
void Close ()
void Reactivate ()
virtual void OnManagerActivate ()
virtual void OnManagerDeactivate ()
void SetAnchor (RectPosition p)
void SetPivot (RectPosition p)
virtual void OnChangePivot ()
void UpdateConfig ()
virtual void OnUpdateConfig ()
void ClampToScreen ()
virtual void OnChangeResolution ()
void OnChangePosition ()
virtual void OnChangeActionMode ()
virtual void OnFlip ()
bool IsAlignTop ()
Layer AddLayer (Layer l, Transform trans)
void RefreshTipPivotPosition ()
SkinSet GetSkin ()
SkinConfig GetSkinConfig ()
void SetSkin (int id, int v=0)
void TestSkin ()
virtual void ApplySkin ()
virtual void OnApplySkin ()
void InstantiateDeco (SkinDeco deco)
void AddDeco (SkinDeco deco)
void RemoveDeco (SkinDeco deco)
virtual bool CanShowContextMenu ()
void ShowContextMenu ()
void SetBaseContextMenu (UIContextMenu m)
virtual void OnSetContextMenu (UIContextMenu m)
void SetGridContextMenu (UIContextMenu m)
void SoundActivate ()
void OnChangeResolution ()
SkinSet GetSkin ()
SkinConfig GetSkinConfig ()
Static Public Member Functions
static void Refresh ()
Static Public Member Functions inherited from EMono
static int rnd (int a)
Public Attributes
Text textTime
Text textLevel
RectTransform rectClock
Image imageHour
Color colorFestival
Public Attributes inherited from Widget
Image imageBG
SoundData soundActivate
UIDragPanel dragPanel
RectTransform tipPivotLeft
RectTransform tipPivotRight
Static Public Attributes
static WidgetDate Instance
Static Public Attributes inherited from EMono
static Core core
Properties
Extra extra [get]
Properties inherited from Widget
string ID [get]
Config config [get]
SkinRoot skinRoot [get]
bool IsSealed [get]
virtual bool ShowStyleMenu [get]
virtual bool AlwaysTop [get]
virtual bool IsStaticPosition [get]
virtual bool AlwaysBottom [get]
virtual Type SetSiblingAfter [get]
virtual bool ShowInBuildMode [get]
virtual bool RightClickToClose [get]
virtual bool AllowRightClickToClose [get]
Properties inherited from EMono
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SoundManager Sound [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static CoreDebug debug [get]
Additional Inherited Members
Public Types inherited from Widget
enum WidgetType { Default , ZoomMenu }
enum State { Active , Inactive }
Protected Member Functions inherited from Widget
void ClampToScreenEnsured (Component c, Vector2 anchoredPos)
void ClampToScreen (RectTransform rect, float margin=10f)
Protected Attributes inherited from Widget
bool flip
Detailed Description
Definition at line 6 of file WidgetDate.cs.
Member Function Documentation
_Refresh()
void WidgetDate._Refresh () inline
Definition at line 51 of file WidgetDate.cs.
    {
        if (EMono.game.activeZone == null)
        {
            return;
        }
        string text = "";
        GameDate date = EMono.world.date;
        text += (extra.date ? EMono.world.date.GetText(Date.TextFormat.Widget) : "");
        if (extra.period)
        {
            text = text + " (" + EMono.world.date.periodOfDay.ToString().lang() + ") ";
        }
        text += (extra.realDate ? (" (" + DateTime.Now.ToString("H:mm") + ") ") : "");
        if (extra.loc)
        {
            text = text + " " + EMono._zone.NameWithLevel;
            if (EMono._zone is Zone_Dungeon)
            {
                text += EMono._zone.TextDangerLv;
            }
            if (EMono._zone.isClaimable && !EMono._zone.IsPCFaction)
            {
                text += "(";
                List<Element> list = EMono._zone.ListLandFeats();
                foreach (Element item in list)
                {
                    if (item != list[0])
                    {
                        text += ", ";
                    }
                    text += item.Name;
                }
                text += ")";
            }
        }
        if (EMono._zone.idCurrentSubset != null)
        {
            text += ("(" + (EMono._zone.idExport + "_" + EMono._zone.idCurrentSubset).lang() + ")").TagColor(colorFestival);
        }
        if (EMono._zone.isPeace)
        {
            text += "zone_peace".lang().TagColor(colorFestival);
        }
        if (EMono.debug.showExtra)
        {
            text = text + " <size=12>(" + EMono._zone.biome.name + "/Lv:" + EMono._zone.lv + "/Danger:" + EMono._zone.DangerLv + "/_danger:" + EMono._zone._dangerLv + "/elec:" + EMono._zone.electricity + ")</size>";
            if (EMono._zone.IsInstance)
            {
                text += "Instance";
            }
        }
        if (extra.weather)
        {
            text = text + " - " + EMono.world.weather.GetName();
        }
        if (extra.room && EMono.pc.IsInActiveZone && EMono._zone.IsPCFaction)
        {
            Room room = EMono.pc.Cell.room;
            if (room != null)
            {
                text = text + " (" + room.Name + ")";
            }
            if (EMono.pc.pos.area != null)
            {
                text = text + " (" + EMono.pc.pos.area.Name + ")";
            }
        }
        text += EMono._zone.TextWidgetDate;
        foreach (ZoneEvent item2 in EMono._zone.events.list)
        {
            text += item2.TextWidgetDate;
        }
        if (EMono.game.IsSurvival)
        {
            text += "raid_till".lang(EMono.game.survival.flags.raidLv.ToString() ?? "");
        }
        if (EMono.Branch != null && EMono.Branch.luckyMonth)
        {
            text = text + " " + "lucky_month".lang().TagColor(Msg.colors.colors["save"]);
        }
        if (EMono.debug.enable)
        {
            text += " *DEBUG MODE*";
        }
        textTime.text = text;
        rectClock.SetActive(extra.clock);
        if (extra.clock)
        {
            imageHour.transform.localEulerAngles = new Vector3(0f, 0f, -date.hour * 30 + 90);
        }
        _ = base.transform.position.x / (float)Screen.width;
        bool flag = base.config.pivot == RectPosition.BottomRIGHT || base.config.pivot == RectPosition.TopRIGHT || base.config.pivot == RectPosition.Right;
        this.Rect().SetPivot(flag ? 1 : 0, 0f);
        rectClock.SetAnchor(flag ? 1 : 0, 1f, flag ? 1 : 0, 1f);
        rectClock.anchoredPosition = new Vector2(flag ? (-60) : 60, -75f);
        textTime.RebuildLayout();
    }
References EMono._zone, Game.activeZone, Point.area, EMono.Branch, Card.Cell, WidgetDate.Extra.clock, colorFestival, Msg.colors, MsgColors.colors, World.date, EMono.debug, CoreDebug.enable, Zone.events, extra, SurvivalManager.flags, EMono.game, Weather.GetName(), Date.GetText(), Spatial.idCurrentSubset, Spatial.isClaimable, Chara.IsInActiveZone, Zone.IsInstance, Zone.IsPCFaction, Spatial.isPeace, Game.IsSurvival, item, ZoneEventManager.list, Zone.ListLandFeats(), WidgetDate.Extra.loc, FactionBranch.luckyMonth, Zone.NameWithLevel, EMono.pc, WidgetDate.Extra.period, Date.periodOfDay, Card.pos, SurvivalManager.Flags.raidLv, rectClock, Cell.room, WidgetDate.Extra.room, CoreDebug.showExtra, Game.survival, Zone.TextDangerLv, textTime, Zone.TextWidgetDate, ZoneEvent.TextWidgetDate, WidgetDate.Extra.weather, World.weather, and EMono.world.
Referenced by OnActivate(), OnChangePivot(), OnSetContextMenu(), and Refresh().
CreateExtra()
override object WidgetDate.CreateExtra () inline virtual
Reimplemented from Widget.
Definition at line 39 of file WidgetDate.cs.
    {
        return new Extra();
    }
OnActivate()
override void WidgetDate.OnActivate () inline virtual
Reimplemented from Widget.
Definition at line 44 of file WidgetDate.cs.
    {
        Instance = this;
        _Refresh();
        InvokeRepeating("_Refresh", 0.1f, 0.1f);
    }
References _Refresh(), and Instance.
OnChangePivot()
override void WidgetDate.OnChangePivot () inline virtual
Reimplemented from Widget.
Definition at line 150 of file WidgetDate.cs.
    {
        _Refresh();
    }
References _Refresh().
OnSetContextMenu()
override void WidgetDate.OnSetContextMenu (UIContextMenu m) inline virtual
Reimplemented from Widget.
Definition at line 163 of file WidgetDate.cs.
    {
        UIContextMenu uIContextMenu = m.AddChild("setting");
        uIContextMenu.AddToggle("showPeriodOfDay", extra.period, delegate(bool a)
        {
            extra.period = a;
            _Refresh();
        });
        uIContextMenu.AddToggle("showRealDate", extra.realDate, delegate(bool a)
        {
            extra.realDate = a;
            _Refresh();
        });
        uIContextMenu.AddToggle("showRoom", extra.room, delegate(bool a)
        {
            extra.room = a;
            _Refresh();
        });
        uIContextMenu.AddToggle("showClock", extra.clock, delegate(bool a)
        {
            extra.clock = a;
            _Refresh();
        });
        uIContextMenu.AddToggle("showLoc", extra.loc, delegate(bool a)
        {
            extra.loc = a;
            _Refresh();
        });
        uIContextMenu.AddToggle("showWeather", extra.weather, delegate(bool a)
        {
            extra.weather = a;
            _Refresh();
        });
        SetBaseContextMenu(m);
    }
References _Refresh(), UIContextMenu.AddChild(), UIContextMenu.AddToggle(), WidgetDate.Extra.clock, extra, WidgetDate.Extra.loc, WidgetDate.Extra.period, WidgetDate.Extra.realDate, WidgetDate.Extra.room, Widget.SetBaseContextMenu(), and WidgetDate.Extra.weather.
Refresh()
static void WidgetDate.Refresh () inline static
Definition at line 155 of file WidgetDate.cs.
    {
        if ((bool)Instance)
        {
            Instance._Refresh();
        }
    }
References _Refresh(), and Instance.
Referenced by Scene.Init(), TraitCoreZone.TrySetAct(), and TraitWaystone.TrySetAct().
Member Data Documentation
colorFestival
Color WidgetDate.colorFestival
Definition at line 35 of file WidgetDate.cs.
Referenced by _Refresh().
imageHour
Image WidgetDate.imageHour
Definition at line 33 of file WidgetDate.cs.
Instance
WidgetDate WidgetDate.Instance static
Definition at line 25 of file WidgetDate.cs.
Referenced by OnActivate(), and Refresh().
rectClock
RectTransform WidgetDate.rectClock
Definition at line 31 of file WidgetDate.cs.
Referenced by _Refresh().
textLevel
Text WidgetDate.textLevel
Definition at line 29 of file WidgetDate.cs.
textTime
Text WidgetDate.textTime
Definition at line 27 of file WidgetDate.cs.
Referenced by _Refresh().
Property Documentation
extra
Extra WidgetDate.extra get
Definition at line 37 of file WidgetDate.cs.
Referenced by _Refresh(), and OnSetContextMenu().
The documentation for this class was generated from the following file:
Elin/WidgetDate.cs