Elin Decompiled Documentation: MeshPass Class Reference
MeshPass Class Reference
Public Member Functions
void Init ()
void Add (Point point, float tile=0f, float color=0f)
void Add (ref Vector3 v, float tile=0f, float color=0f)
void Add (float x, float y, float z, float tile=0f, float color=0f)
void AddWithScale (float x, float y, float z, int tile, float scale)
void AddShadow (MeshPassParam p, ref Vector3 fix)
void AddShadow (float x, float y, float z, ShadowData.Item s, SourcePref pref, int dir=0, bool snow=false)
void AddWithRotation (float x, float y, float z, float sx, float sy, int tile, float angle, bool flip)
void Add (MeshPassParam p)
void Add (float x, float y, float z, float tile, float color, float matColor=0f)
void Add (MeshPassParam p, float tile, float color, float matColor=0f)
void Draw ()
void DrawEmpty ()
void NextBatch ()
override string ToString ()
void Refresh ()
void OnValidate ()
void _Refresh ()
Public Attributes
MeshPass subPass
MeshPass snowPass
MeshPass shadowPass
Material mat
Mesh mesh
ProceduralMesh pmesh
Sprite sprite
bool setTile
bool setColor
bool setMatColor
bool setExtra
int renderQueue
MeshPassParam _p = new MeshPassParam()
FilterMode filter
int lastCount
int lastBatchCount
bool haveSubPass
bool haveShadowPass
bool haveSnowPass
int idx
int batchIdx
int batchSize = 1023
List< MeshBatch > batches = new List<MeshBatch>()
Texture preserveTex
Static Public Attributes
const int TokenLiquid = 10000
const int TokenLowWall = 1000000
const int TokenLowWallDefault = 3000000
Properties
float meshX [get, set]
Private Member Functions
Mesh SpriteToMesh (Sprite sprite)
Private Attributes
bool initialized
bool resize
MeshBatch _batch
Vector3 tempV = Vector3.zero
Vector2 tempE = Vector2.zero
bool first = true
Detailed Description
Definition at line 7 of file MeshPass.cs.
Member Function Documentation
_Refresh()
void MeshPass._Refresh () inline
Definition at line 466 of file MeshPass.cs.
    {
        haveSubPass = subPass;
        haveShadowPass = shadowPass;
        haveSnowPass = snowPass;
        if (!mesh)
        {
            if ((bool)pmesh)
            {
                mesh = pmesh.GetMesh();
            }
            else if ((bool)sprite)
            {
                mesh = SpriteToMesh(sprite);
            }
        }
        if (haveSnowPass)
        {
            snowPass.mesh = mesh;
        }
        if (haveSubPass)
        {
            subPass.mesh = mesh;
        }
        if (haveShadowPass)
        {
            shadowPass.mesh = mesh;
        }
    }
References ProceduralMesh.GetMesh(), haveShadowPass, haveSnowPass, haveSubPass, mesh, pmesh, shadowPass, snowPass, sprite, SpriteToMesh(), and subPass.
Referenced by Init().
Add() [1/6]
void MeshPass.Add (float x, float y, float z, float tile, float color, float matColor = 0f) inline
Definition at line 306 of file MeshPass.cs.
    {
        _batch = batches[batchIdx];
        _batch.matrices[idx].m03 = x;
        _batch.matrices[idx].m13 = y;
        _batch.matrices[idx].m23 = z;
        _batch.tiles[idx] = tile;
        if (setColor)
        {
            _batch.colors[idx] = color;
        }
        if (setMatColor)
        {
            _batch.matColors[idx] = matColor;
        }
        idx++;
        if (idx == batchSize)
        {
            NextBatch();
        }
    }
References _batch, batches, batchIdx, batchSize, MeshBatch.colors, idx, MeshBatch.matColors, MeshBatch.matrices, NextBatch(), setColor, setMatColor, and MeshBatch.tiles.
Add() [2/6]
void MeshPass.Add (float x, float y, float z, float tile = 0f, float color = 0f) inline
Definition at line 159 of file MeshPass.cs.
    {
        _batch = batches[batchIdx];
        _batch.matrices[idx].m03 = x;
        _batch.matrices[idx].m13 = y;
        _batch.matrices[idx].m23 = z;
        _batch.tiles[idx] = tile;
        if (setColor)
        {
            _batch.colors[idx] = color;
        }
        idx++;
        if (idx == batchSize)
        {
            NextBatch();
        }
    }
References _batch, batches, batchIdx, batchSize, MeshBatch.colors, idx, MeshBatch.matrices, NextBatch(), setColor, and MeshBatch.tiles.
Add() [3/6]
void MeshPass.Add (MeshPassParam p) inline
Definition at line 281 of file MeshPass.cs.
    {
        _batch = batches[batchIdx];
        _batch.matrices[idx].m03 = p.x;
        _batch.matrices[idx].m13 = p.y;
        _batch.matrices[idx].m23 = p.z;
        if (setTile)
        {
            _batch.tiles[idx] = p.tile;
        }
        if (setColor)
        {
            _batch.colors[idx] = p.color;
        }
        if (setMatColor)
        {
            _batch.matColors[idx] = p.matColor;
        }
        idx++;
        if (idx == batchSize)
        {
            NextBatch();
        }
    }
References _batch, batches, batchIdx, batchSize, MeshPassParam.color, MeshBatch.colors, idx, MeshPassParam.matColor, MeshBatch.matColors, MeshBatch.matrices, NextBatch(), setColor, setMatColor, setTile, MeshPassParam.tile, MeshBatch.tiles, MeshPassParam.x, MeshPassParam.y, and MeshPassParam.z.
Add() [4/6]
void MeshPass.Add (MeshPassParam p, float tile, float color, float matColor = 0f) inline
Definition at line 328 of file MeshPass.cs.
    {
        _batch = batches[batchIdx];
        _batch.matrices[idx].m03 = p.x;
        _batch.matrices[idx].m13 = p.y;
        _batch.matrices[idx].m23 = p.z;
        _batch.tiles[idx] = tile;
        if (setColor)
        {
            _batch.colors[idx] = color;
        }
        if (setMatColor)
        {
            _batch.matColors[idx] = matColor;
        }
        idx++;
        if (idx == batchSize)
        {
            NextBatch();
        }
    }
References _batch, batches, batchIdx, batchSize, MeshBatch.colors, idx, MeshBatch.matColors, MeshBatch.matrices, NextBatch(), setColor, setMatColor, MeshBatch.tiles, MeshPassParam.x, MeshPassParam.y, and MeshPassParam.z.
Add() [5/6]
void MeshPass.Add (Point point, float tile = 0f, float color = 0f) inline
Definition at line 122 of file MeshPass.cs.
    {
        Vector3 vector = point.Position();
        _batch = batches[batchIdx];
        _batch.matrices[idx].m03 = vector.x;
        _batch.matrices[idx].m13 = vector.y;
        _batch.matrices[idx].m23 = vector.z;
        _batch.tiles[idx] = tile;
        if (setColor)
        {
            _batch.colors[idx] = color;
        }
        idx++;
        if (idx == batchSize)
        {
            NextBatch();
        }
    }
References _batch, batches, batchIdx, batchSize, MeshBatch.colors, idx, MeshBatch.matrices, NextBatch(), Point.Position(), setColor, and MeshBatch.tiles.
Referenced by PartialMap.Apply(), UIInspector.DrawHighlight(), TaskDesignation.DrawMarker(), BaseTileMap.DrawTile(), TileMapElona.DrawTile(), ScreenGuide.DrawWall(), Recipe.OnRenderMarker(), ActionMode.OnRenderTile(), AM_Adv.OnRenderTile(), AM_Build.OnRenderTile(), HotItemHeld.OnRenderTile(), Trait.OnRenderTile(), TraitRoadSign.OnRenderTile(), ActionMode.OnRenderTileFloor(), Card.RenderMarker(), GameUpdater.Update(), HoardActor.Update(), and LayerInteraction.Update().
Add() [6/6]
void MeshPass.Add (ref Vector3 v, float tile = 0f, float color = 0f) inline
Definition at line 141 of file MeshPass.cs.
    {
        _batch = batches[batchIdx];
        _batch.matrices[idx].m03 = v.x;
        _batch.matrices[idx].m13 = v.y;
        _batch.matrices[idx].m23 = v.z;
        _batch.tiles[idx] = tile;
        if (setColor)
        {
            _batch.colors[idx] = color;
        }
        idx++;
        if (idx == batchSize)
        {
            NextBatch();
        }
    }
References _batch, batches, batchIdx, batchSize, MeshBatch.colors, idx, MeshBatch.matrices, NextBatch(), setColor, and MeshBatch.tiles.
AddShadow() [1/2]
void MeshPass.AddShadow (float x, float y, float z, ShadowData::Item s, SourcePref pref, int dir = 0, bool snow = false) inline
Definition at line 213 of file MeshPass.cs.
    {
        int angle = s.angle;
        float num = (float)s.scaleX * 0.01f;
        float num2 = (float)s.scaleY * 0.01f;
        bool flag = dir % 2 == 1;
        int num3 = (flag ? 1 : (-1));
        _batch = batches[batchIdx];
        Matrix4x4[] matrices = _batch.matrices;
        matrices[idx].m03 = x - 0.01f * (float)((dir < 2) ? (flag ? pref.shadowRX : pref.shadowX) : (flag ? pref.shadowBRX : pref.shadowBX)) + ((0.7f * (0f - num) + 0.7f) * (float)num3 + (float)s.x * 0.01f) * (float)num3;
        matrices[idx].m13 = y - 0.01f * (float)((dir < 2) ? (flag ? pref.shadowRY : pref.shadowY) : (flag ? pref.shadowBRY : pref.shadowBY)) + 0.6f * (0f - num2) + 0.6f + (float)s.y * 0.01f;
        matrices[idx].m23 = z;
        matrices[idx].m00 = num;
        matrices[idx].m11 = num2;
        if (angle == 0)
        {
            matrices[idx].m00 = num;
            matrices[idx].m01 = 0f;
            matrices[idx].m10 = 0f;
            matrices[idx].m11 = num2;
        }
        else
        {
            tempV.z = -angle;
            Quaternion quaternion = Quaternion.Euler(0f, 0f, -angle);
            tempE.x = 1f - quaternion.z * quaternion.z * 2f;
            tempE.y = (0f - quaternion.w) * quaternion.z * 2f;
            matrices[idx].m00 = tempE.x * num;
            matrices[idx].m01 = tempE.y * num2;
            matrices[idx].m10 = (0f - tempE.y) * num;
            matrices[idx].m11 = tempE.x * num2;
        }
        _batch.tiles[idx] = (s.tile + (snow ? 1000 : 0)) * num3;
        idx++;
        if (idx == batchSize)
        {
            NextBatch();
        }
    }
References _batch, batches, batchIdx, batchSize, idx, MeshBatch.matrices, NextBatch(), SourcePref.shadowBRX, SourcePref.shadowBRY, SourcePref.shadowBX, SourcePref.shadowBY, SourcePref.shadowX, SourcePref.shadowY, tempE, and MeshBatch.tiles.
AddShadow() [2/2]
void MeshPass.AddShadow (MeshPassParam p, ref Vector3 fix) inline
Definition at line 195 of file MeshPass.cs.
    {
        _batch = batches[batchIdx];
        _batch.matrices[idx].SetTRS(Vector3.zero, Quaternion.Euler(0f, 0f, 0f), Vector3.one);
        _batch.matrices[idx].m03 = p.x + fix.x;
        _batch.matrices[idx].m13 = p.y + fix.y;
        _batch.matrices[idx].m23 = p.z + fix.z;
        if (setTile)
        {
            _batch.tiles[idx] = p.tile;
        }
        idx++;
        if (idx == batchSize)
        {
            NextBatch();
        }
    }
References _batch, batches, batchIdx, batchSize, idx, MeshBatch.matrices, NextBatch(), setTile, MeshPassParam.tile, and MeshBatch.tiles.
Referenced by CardRenderer.Draw(), BaseTileMap.DrawTile(), TileMapElona.DrawTile(), and GrowSystem.OnRenderTileMap().
AddWithRotation()
void MeshPass.AddWithRotation (float x, float y, float z, float sx, float sy, int tile, float angle, bool flip) inline
Definition at line 253 of file MeshPass.cs.
    {
        float num = 1f;
        float num2 = 1f;
        int num3 = ((!flip) ? 1 : (-1));
        _batch = batches[batchIdx];
        Matrix4x4[] matrices = _batch.matrices;
        matrices[idx].m03 = x + ((0.7f * (0f - num) + 0.7f) * (float)num3 + sx * 0.01f) * (float)num3;
        matrices[idx].m13 = y + 0.6f * (0f - num2) + 0.6f + sy * 0.01f;
        matrices[idx].m23 = z;
        matrices[idx].m00 = num;
        matrices[idx].m11 = num2;
        tempV.z = 0f - angle;
        Quaternion quaternion = Quaternion.Euler(0f, 0f, 0f - angle);
        tempE.x = 1f - quaternion.z * quaternion.z * 2f;
        tempE.y = (0f - quaternion.w) * quaternion.z * 2f;
        matrices[idx].m00 = tempE.x * num;
        matrices[idx].m01 = tempE.y * num2;
        matrices[idx].m10 = (0f - tempE.y) * num;
        matrices[idx].m11 = tempE.x * num2;
        _batch.tiles[idx] = tile * num3;
        idx++;
        if (idx == batchSize)
        {
            NextBatch();
        }
    }
References _batch, batches, batchIdx, batchSize, idx, MeshBatch.matrices, NextBatch(), tempE, and MeshBatch.tiles.
AddWithScale()
void MeshPass.AddWithScale (float x, float y, float z, int tile, float scale) inline
Definition at line 177 of file MeshPass.cs.
    {
        _batch = batches[batchIdx];
        Matrix4x4[] matrices = _batch.matrices;
        float num = (0f - scale) / 2f + 0.5f;
        matrices[idx].m03 = x + num;
        matrices[idx].m13 = y + num;
        matrices[idx].m23 = z;
        matrices[idx].m00 = scale;
        matrices[idx].m11 = scale;
        _batch.tiles[idx] = tile;
        idx++;
        if (idx == batchSize)
        {
            NextBatch();
        }
    }
References _batch, batches, batchIdx, batchSize, idx, MeshBatch.matrices, NextBatch(), and MeshBatch.tiles.
Draw()
void MeshPass.Draw () inline
Definition at line 350 of file MeshPass.cs.
    {
        if (haveSnowPass)
        {
            snowPass.Draw();
        }
        if (haveSubPass)
        {
            subPass.Draw();
        }
        if (haveShadowPass)
        {
            shadowPass.Draw();
        }
        if (idx == 0 && batchIdx == 0)
        {
            return;
        }
        for (int i = 0; i < batchIdx + 1; i++)
        {
            int num = ((i == batchIdx) ? idx : batches[i].size);
            if (num == 0)
            {
                break;
            }
            if (setTile)
            {
                batches[i].mpb.SetFloatArray("_Tiles", batches[i].tiles);
            }
            if (setColor)
            {
                batches[i].mpb.SetFloatArray("_Color", batches[i].colors);
            }
            if (setMatColor)
            {
                batches[i].mpb.SetFloatArray("_MatColor", batches[i].matColors);
            }
            if (renderQueue != 0)
            {
                if (batches[i].mat == null)
                {
                    batches[i].mat = new Material(mat);
                }
                batches[i].mat.renderQueue = renderQueue + i;
                Graphics.DrawMeshInstanced(mesh, 0, batches[i].mat, batches[i].matrices, num, batches[i].mpb, ShadowCastingMode.Off, receiveShadows: false, 0, Camera.main);
            }
            else
            {
                Graphics.DrawMeshInstanced(mesh, 0, mat, batches[i].matrices, num, batches[i].mpb, ShadowCastingMode.Off, receiveShadows: false, 0, Camera.main);
            }
        }
        lastBatchCount = batchIdx;
        lastCount = batchIdx * batchSize + idx;
        idx = (batchIdx = 0);
        if (resize)
        {
            Debug.Log("#pass Resize Pass:" + base.name);
            resize = false;
            batches[0] = new MeshBatch(this);
        }
    }
References batches, batchIdx, batchSize, Debug, Draw(), haveShadowPass, haveSnowPass, haveSubPass, idx, lastBatchCount, lastCount, mat, Material, mesh, renderQueue, resize, setColor, setMatColor, setTile, shadowPass, snowPass, and subPass.
Referenced by Draw(), Scene.DrawPass(), and HoardActor.Update().
DrawEmpty()
void MeshPass.DrawEmpty () inline
Definition at line 412 of file MeshPass.cs.
    {
        idx = (batchIdx = 0);
    }
References batchIdx, and idx.
Referenced by Scene.DrawPass().
Init()
void MeshPass.Init () inline
Definition at line 98 of file MeshPass.cs.
    {
        batchSize = ((batches.Count > 0) ? batches[0].size : 1023);
        if (!initialized || mesh == null)
        {
            if ((bool)subPass)
            {
                subPass.Init();
            }
            if ((bool)snowPass)
            {
                snowPass.Init();
            }
            if ((bool)shadowPass)
            {
                shadowPass.Init();
            }
            batches.Add(new MeshBatch(this));
            _Refresh();
            initialized = true;
        }
        idx = (batchIdx = 0);
    }
References _Refresh(), batches, batchIdx, batchSize, idx, Init(), initialized, mesh, shadowPass, snowPass, and subPass.
Referenced by HoardActor.Activate(), Init(), Scene.InitPass(), and Refresh().
NextBatch()
void MeshPass.NextBatch () inline
Definition at line 417 of file MeshPass.cs.
    {
        idx = 0;
        batchIdx++;
        if (batchIdx >= batches.Count)
        {
            if (batchSize != 1023)
            {
                batchSize = 1023;
                resize = true;
            }
            batches.Add(new MeshBatch(this));
        }
    }
References batches, batchIdx, batchSize, idx, and resize.
Referenced by Add(), AddShadow(), AddWithRotation(), AddWithScale(), BaseTileMap.Draw(), Assets.Resources.Scene.Render.RenderDataRoof.Draw(), RenderData.Draw(), RenderDataHalfBlock.Draw(), RenderDataLiquid.Draw(), RenderDataObj.Draw(), RenderDataObjAdd.Draw(), RenderDataObjV.Draw(), RenderDataTile.Draw(), RenderDataEffect.Draw(), RenderData.DrawShadow(), and BaseTileMap.DrawTile().
OnValidate()
void MeshPass.OnValidate () inline
Definition at line 461 of file MeshPass.cs.
    {
        Refresh();
    }
References Refresh().
Refresh()
void MeshPass.Refresh () inline
Definition at line 446 of file MeshPass.cs.
    {
        if (Application.isPlaying)
        {
            UnityEngine.Object.DestroyImmediate(mesh);
            MeshPass[] passes = Core.Instance.scene.passes;
            foreach (MeshPass obj in passes)
            {
                obj.initialized = false;
                obj.batches.Clear();
                obj.Init();
            }
        }
    }
References batches, Init(), Core.Instance, mesh, Scene.passes, and Core.scene.
Referenced by OnValidate().
SpriteToMesh()
Mesh MeshPass.SpriteToMesh (Sprite sprite) inline private
Definition at line 432 of file MeshPass.cs.
    {
        Mesh obj = new Mesh();
        obj.SetVertices(Array.ConvertAll(sprite.vertices, (Converter<Vector2, Vector3>)((Vector2 c) => c)).ToList());
        obj.uv = sprite.uv;
        obj.SetTriangles(Array.ConvertAll(sprite.triangles, (Converter<ushort, int>)((ushort c) => c)), 0);
        return obj;
    }
References sprite.
Referenced by _Refresh().
ToString()
override string MeshPass.ToString () inline
Definition at line 441 of file MeshPass.cs.
    {
        return base.name;
    }
Member Data Documentation
_batch
MeshBatch MeshPass._batch private
Definition at line 77 of file MeshPass.cs.
Referenced by Add(), AddShadow(), AddWithRotation(), and AddWithScale().
_p
MeshPassParam MeshPass._p = new MeshPassParam()
Definition at line 39 of file MeshPass.cs.
batches
List<MeshBatch> MeshPass.batches = new List<MeshBatch>()
Definition at line 66 of file MeshPass.cs.
Referenced by Add(), AddShadow(), AddWithRotation(), AddWithScale(), BaseTileMap.Draw(), Draw(), Assets.Resources.Scene.Render.RenderDataRoof.Draw(), RenderData.Draw(), RenderDataHalfBlock.Draw(), RenderDataLiquid.Draw(), RenderDataObj.Draw(), RenderDataObjAdd.Draw(), RenderDataObjV.Draw(), RenderDataTile.Draw(), RenderDataEffect.Draw(), RenderData.DrawShadow(), BaseTileMap.DrawTile(), Init(), MeshBatch.MeshBatch(), NextBatch(), and Refresh().
batchIdx
int MeshPass.batchIdx
Definition at line 60 of file MeshPass.cs.
Referenced by Add(), AddShadow(), AddWithRotation(), AddWithScale(), BaseTileMap.Draw(), Draw(), Assets.Resources.Scene.Render.RenderDataRoof.Draw(), RenderData.Draw(), RenderDataHalfBlock.Draw(), RenderDataLiquid.Draw(), RenderDataObj.Draw(), RenderDataObjAdd.Draw(), RenderDataObjV.Draw(), RenderDataTile.Draw(), RenderDataEffect.Draw(), DrawEmpty(), RenderData.DrawShadow(), BaseTileMap.DrawTile(), Init(), and NextBatch().
batchSize
int MeshPass.batchSize = 1023
Definition at line 63 of file MeshPass.cs.
Referenced by Add(), AddShadow(), AddWithRotation(), AddWithScale(), BaseTileMap.Draw(), Draw(), Assets.Resources.Scene.Render.RenderDataRoof.Draw(), RenderData.Draw(), RenderDataHalfBlock.Draw(), RenderDataLiquid.Draw(), RenderDataObj.Draw(), RenderDataObjAdd.Draw(), RenderDataObjV.Draw(), RenderDataTile.Draw(), RenderDataEffect.Draw(), RenderData.DrawShadow(), BaseTileMap.DrawTile(), Init(), MeshBatch.MeshBatch(), and NextBatch().
filter
FilterMode MeshPass.filter
Definition at line 41 of file MeshPass.cs.
first
bool MeshPass.first = true private
Definition at line 84 of file MeshPass.cs.
haveShadowPass
bool MeshPass.haveShadowPass
Definition at line 51 of file MeshPass.cs.
Referenced by _Refresh(), and Draw().
haveSnowPass
bool MeshPass.haveSnowPass
Definition at line 54 of file MeshPass.cs.
Referenced by _Refresh(), and Draw().
haveSubPass
bool MeshPass.haveSubPass
Definition at line 48 of file MeshPass.cs.
Referenced by _Refresh(), and Draw().
idx
int MeshPass.idx
Definition at line 57 of file MeshPass.cs.
Referenced by Add(), AddShadow(), AddWithRotation(), AddWithScale(), BaseTileMap.Draw(), Draw(), Assets.Resources.Scene.Render.RenderDataRoof.Draw(), RenderData.Draw(), RenderDataHalfBlock.Draw(), RenderDataLiquid.Draw(), RenderDataObj.Draw(), RenderDataObjAdd.Draw(), RenderDataObjV.Draw(), RenderDataTile.Draw(), RenderDataEffect.Draw(), DrawEmpty(), RenderData.DrawShadow(), BaseTileMap.DrawTile(), Init(), and NextBatch().
initialized
bool MeshPass.initialized private
Definition at line 69 of file MeshPass.cs.
Referenced by Init().
lastBatchCount
int MeshPass.lastBatchCount
Definition at line 45 of file MeshPass.cs.
Referenced by Draw().
lastCount
int MeshPass.lastCount
Definition at line 43 of file MeshPass.cs.
Referenced by Draw().
mat
Material MeshPass.mat
Definition at line 21 of file MeshPass.cs.
Referenced by RefractionProfile.Apply(), PostEffectProfile.Apply(), LiquidProfile.Apply(), Scene.ApplyZoneConfig(), Draw(), RenderRow.GetSprite(), CoreDebug.Test_Filter(), and Core.Update().
mesh
Mesh MeshPass.mesh
Definition at line 23 of file MeshPass.cs.
Referenced by _Refresh(), Draw(), Init(), and Refresh().
pmesh
ProceduralMesh MeshPass.pmesh
Definition at line 25 of file MeshPass.cs.
Referenced by _Refresh(), TextureManager.AddBase(), RenderData.ConvertTile(), RenderDataObjAdd.Draw(), RenderDataObjV.Draw(), RenderDataTile.Draw(), CardRenderer.Draw(), RenderRow.GetSprite(), RenderRow.SetRenderData(), RenderRow.SetTiles(), SourceChara.Row.SetTiles(), and SourceThing.Row.SetTiles().
preserveTex
Texture MeshPass.preserveTex
Definition at line 75 of file MeshPass.cs.
renderQueue
int MeshPass.renderQueue
Definition at line 37 of file MeshPass.cs.
Referenced by Draw().
resize
bool MeshPass.resize private
Definition at line 72 of file MeshPass.cs.
Referenced by Draw(), and NextBatch().
setColor
bool MeshPass.setColor
Definition at line 31 of file MeshPass.cs.
Referenced by Add(), Draw(), and MeshBatch.MeshBatch().
setExtra
bool MeshPass.setExtra
Definition at line 35 of file MeshPass.cs.
Referenced by MeshBatch.MeshBatch().
setMatColor
bool MeshPass.setMatColor
Definition at line 33 of file MeshPass.cs.
Referenced by Add(), Draw(), and MeshBatch.MeshBatch().
setTile
bool MeshPass.setTile
Definition at line 29 of file MeshPass.cs.
Referenced by Add(), AddShadow(), and Draw().
shadowPass
MeshPass MeshPass.shadowPass
Definition at line 19 of file MeshPass.cs.
Referenced by _Refresh(), Draw(), RenderData.DrawShadow(), and Init().
snowPass
MeshPass MeshPass.snowPass
Definition at line 17 of file MeshPass.cs.
Referenced by _Refresh(), Draw(), Assets.Resources.Scene.Render.RenderDataRoof.Draw(), RenderDataObj.Draw(), RenderDataObjAdd.Draw(), RenderDataObjV.Draw(), RenderDataTile.Draw(), Init(), RenderData.Init(), and TextureManager.Init().
sprite
Sprite MeshPass.sprite
Definition at line 27 of file MeshPass.cs.
Referenced by _Refresh(), and SpriteToMesh().
subPass
MeshPass MeshPass.subPass
Definition at line 15 of file MeshPass.cs.
Referenced by _Refresh(), Draw(), Assets.Resources.Scene.Render.RenderDataRoof.Draw(), RenderData.Draw(), RenderDataObj.Draw(), RenderDataObjAdd.Draw(), RenderDataObjV.Draw(), RenderDataTile.DrawWithRotation(), Init(), and RenderData.Init().
tempE
Vector2 MeshPass.tempE = Vector2.zero private
Definition at line 81 of file MeshPass.cs.
Referenced by AddShadow(), and AddWithRotation().
tempV
Vector3 MeshPass.tempV = Vector3.zero private
Definition at line 79 of file MeshPass.cs.
TokenLiquid
const int MeshPass.TokenLiquid = 10000 static
Definition at line 9 of file MeshPass.cs.
TokenLowWall
const int MeshPass.TokenLowWall = 1000000 static
Definition at line 11 of file MeshPass.cs.
TokenLowWallDefault
const int MeshPass.TokenLowWallDefault = 3000000 static
Definition at line 13 of file MeshPass.cs.
Property Documentation
meshX
float MeshPass.meshX get set
Definition at line 86 of file MeshPass.cs.
    {
        get
        {
            return pmesh.size.x;
        }
        set
        {
            pmesh.size.x = value;
        }
    }
The documentation for this class was generated from the following file:
Elin/MeshPass.cs