Elin Decompiled Documentation: GrowSystemTree Class Reference
GrowSystemTree Class Reference
Public Member Functions
override bool BlockPass (Cell cell)
override bool BlockSight (Cell cell)
override int GetShadow (int index)
override void SetGenericFirstStageTile (GrowSystem.Stage s)
override void SetStageTile (GrowSystem.Stage s)
override void OnHitFail (Chara c)
override int GetHp ()
int GetPlantBonus (PlantData plant)
override void OnMineObj (Chara c=null)
Public Member Functions inherited from GrowSystem
bool IsLastStage ()
virtual bool BlockSight (Cell cell)
virtual bool BlockPass (Cell cell)
virtual string GetSoundProgress ()
virtual GrowSystem.Stage CreateStage ()
void Init (SourceObj.Row _row)
virtual void SetGenericFirstStageTile (GrowSystem.Stage s)
virtual void SetStageTile (GrowSystem.Stage s)
virtual int GetStageTile ()
virtual int GetShadow (int index)
virtual void OnRenderTileMap (RenderParam p)
void SetRandomStage ()
void SetDefaultStage ()
bool CanGrow (VirtualDate date)
void TryGrow (VirtualDate date)
void EqualizePlants (Point pos)
void Grow (int mtp=1)
virtual void OnReachNextStage ()
virtual void OnExceedLastStage ()
void SetStage (int idx, bool renewHarvest=false)
bool HaltGrowth ()
void Perish ()
bool IsWithered ()
bool CanHarvest ()
virtual bool CanReapSeed ()
virtual void OnHit (Chara c)
virtual void OnHitFail (Chara c)
void OnProgressComplete (Chara c)
void PopMineObj (Chara c=null)
virtual void OnMineObj (Chara c=null)
void TryPick (Cell cell, Thing t, Chara c, bool applySeed=false)
void TryPick (Cell cell, string idThing, int idMat=-1, int num=1, bool applySeed=false)
Thing TryPopSeed (Chara c)
void Harvest (Chara c)
void PopHarvest (Chara c, string idThing, int num=-1)
void PopHarvest (Chara c, Thing t=null, int num=-1)
void ApplySeed (Thing t)
virtual int GetHp ()
Static Public Attributes
static int[] shadows
Static Public Attributes inherited from GrowSystem
static SourceObj.Row[] sourceSnowTree
const int DivStage = 30
static Cell cell
static GrowSystem.Stage currentStage
Static Public Attributes inherited from EClass
static Core core
Properties
override RenderData RenderHarvest [get]
override int Step [get]
override int StageLength [get]
override float MtpProgress [get]
override int HarvestStage [get]
override bool DrawHarvestOnTop [get]
override bool IsMature [get]
override bool IsTree [get]
override int ShadowStage [get]
bool Bud [get]
bool Baby [get]
bool Young [get]
bool Grown [get]
bool Mature [get]
bool Withered [get]
bool IsPalulu [get]
bool IsBamboo [get]
override bool UseGenericFirstStageTile [get]
Properties inherited from GrowSystem
virtual RenderData RenderHarvest [get]
virtual int Step [get]
virtual int StageLength [get]
virtual int DefaultStage [get]
virtual int HarvestStage [get]
virtual int AutoMineStage [get]
virtual int HaltStage [get]
virtual bool DrawHarvestOnTop [get]
virtual bool UseGenericFirstStageTile [get]
virtual bool WitherOnLastStage [get]
virtual bool CanRegrow [get]
virtual int ShadowStage [get]
virtual bool IsTree [get]
virtual bool IsCrimeToHarvest [get]
virtual float MtpProgress [get]
virtual bool NeedSunlight [get]
virtual AnimeID AnimeProgress [get]
GrowSystem.Stage stage [get]
virtual bool IsMature [get]
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Private Member Functions
int< OnMineObj > g__PlantBonus (ref GrowSystemTree.<>c__DisplayClass45_0 A_1)
Additional Inherited Members
Static Public Member Functions inherited from EClass
static int rnd (int a)
static int curve (int a, int start, int step, int rate=75)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Public Attributes inherited from GrowSystem
SourceObj.Row source
GrowSystem.Stage[] stages
int[] baseTiles
int harvestTile
int afterHarvestTile
string idHarvestThing
Protected Member Functions inherited from GrowSystem
virtual bool IsHarvestStage (int idx)
Detailed Description
Definition at line 5 of file GrowSystemTree.cs.
Member Function Documentation
BlockPass()
override bool GrowSystemTree.BlockPass (Cell cell) inline virtual
Reimplemented from GrowSystem.
Definition at line 31 of file GrowSystemTree.cs.
    {
        return cell.objVal / 30 > 1;
    }
BlockSight()
override bool GrowSystemTree.BlockSight (Cell cell) inline virtual
Reimplemented from GrowSystem.
Definition at line 36 of file GrowSystemTree.cs.
    {
        return cell.objVal / 30 > 2;
    }
g__PlantBonus()
int< OnMineObj > GrowSystemTree.g__PlantBonus (ref GrowSystemTree::<>c__DisplayClass45_0 A_1) inline private
Definition at line 303 of file GrowSystemTree.cs.
    {
        return this.GetPlantBonus(A_1.plant);
    }
References GetPlantBonus().
Referenced by OnMineObj().
GetHp()
override int GrowSystemTree.GetHp () inline virtual
Reimplemented from GrowSystem.
Definition at line 212 of file GrowSystemTree.cs.
    {
        if (base.stage.idx > this.HarvestStage)
        {
            return (int)((float)base.GetHp() * 1.5f);
        }
        return (int)((float)base.GetHp() * 0.5f);
    }
GetPlantBonus()
int GrowSystemTree.GetPlantBonus (PlantData plant) inline
Definition at line 221 of file GrowSystemTree.cs.
    {
        if (plant == null || plant.seed == null)
        {
            return 0;
        }
        int num = plant.seed.encLV / 10;
        if (EClass.rnd(10) > plant.seed.encLV % 10)
        {
            num++;
        }
        return Mathf.Min(EClass.rnd(num + 1), 4);
    }
References Card.encLV, EClass.rnd(), and PlantData.seed.
Referenced by g__PlantBonus().
GetShadow()
override int GrowSystemTree.GetShadow (int index) inline virtual
Reimplemented from GrowSystem.
Reimplemented in GrowSystemTreeSingle.
Definition at line 173 of file GrowSystemTree.cs.
    {
        if (this.source.id == 103)
        {
            return this.source.pref.shadow;
        }
        return GrowSystemTree.shadows[index];
    }
References shadows, and GrowSystem.source.
OnHitFail()
override void GrowSystemTree.OnHitFail (Chara c) inline virtual
Reimplemented from GrowSystem.
Definition at line 197 of file GrowSystemTree.cs.
    {
        if (c == null)
        {
            return;
        }
        if (this.Young || this.Grown || this.Mature || this.Withered)
        {
            Chara chara = CharaGen.Create("putty", -1);
            EClass._zone.AddCard(chara, GrowSystem.cell.GetPoint().GetNearestPoint(false, false, true, false));
            chara.renderer.PlayAnime(AnimeID.Fall, true);
            c.Say("mobFromTree", chara, null, null);
        }
    }
References EClass._zone, Zone.AddCard(), GrowSystem.cell, CharaGen.Create(), Point.GetNearestPoint(), Cell.GetPoint(), Grown, Mature, CardRenderer.PlayAnime(), Card.renderer, Card.Say(), Withered, and Young.
OnMineObj()
override void GrowSystemTree.OnMineObj (Chara c = null) inline virtual
Reimplemented from GrowSystem.
Definition at line 235 of file GrowSystemTree.cs.
    {
        GrowSystemTree.<>c__DisplayClass45_0 CS$<>8__locals1;
        CS$<>8__locals1.<>4__this = this;
        Point point = GrowSystem.cell.GetPoint();
        int id = GrowSystem.cell.matObj_fixed.id;
        CS$<>8__locals1.plant = EClass._map.TryGetPlant(GrowSystem.cell);
        if (this.Bud || this.Baby)
        {
            if (EClass.rnd(2) == 0 || this.IsPalulu)
            {
                base.TryPick(GrowSystem.cell, this.IsPalulu ? "leaf_palulu" : "leaf", -1, 1, false);
            }
            if (this.IsBamboo)
            {
                base.PopHarvest(c, "bamboo_shoot", -1);
            }
            base.TryPick(GrowSystem.cell, "branch", id, 1 + this.<OnMineObj>g__PlantBonus|45_0(ref CS$<>8__locals1), false);
            return;
        }
        if (this.Young)
        {
            if (this.IsBamboo)
            {
                base.PopHarvest(c, "bamboo_shoot", -1);
            }
            base.TryPick(GrowSystem.cell, "branch", id, 2 + this.<OnMineObj>g__PlantBonus|45_0(ref CS$<>8__locals1), false);
            if (this.IsPalulu)
            {
                base.TryPick(GrowSystem.cell, "leaf_palulu", -1, 1, false);
            }
            base.TryPick(GrowSystem.cell, "log", id, EClass.rnd(2) + this.<OnMineObj>g__PlantBonus|45_0(ref CS$<>8__locals1) / 2, true);
            return;
        }
        if (this.Grown || this.Mature)
        {
            base.TryPick(GrowSystem.cell, this.IsPalulu ? "leaf_palulu" : "bark", -1, 1 + this.<OnMineObj>g__PlantBonus|45_0(ref CS$<>8__locals1) / 2, false);
            base.TryPick(GrowSystem.cell, "log", id, 1 + EClass.rnd(3) + this.<OnMineObj>g__PlantBonus|45_0(ref CS$<>8__locals1), true);
            base.TryPick(GrowSystem.cell, "resin", -1, 1 + this.<OnMineObj>g__PlantBonus|45_0(ref CS$<>8__locals1) / 2, false);
            if (!EClass.player.isAutoFarming)
            {
                if (EClass.rnd(500) == 0)
                {
                    base.TryPick(GrowSystem.cell, "throw_putit", -1, 1, false);
                }
                if (point.IsFarmField)
                {
                    base.TryPick(GrowSystem.cell, TraitSeed.MakeSeed(point.sourceObj, CS$<>8__locals1.plant), c, false);
                    return;
                }
            }
        }
        else
        {
            base.TryPick(GrowSystem.cell, "bark", -1, EClass.rnd(3) + this.<OnMineObj>g__PlantBonus|45_0(ref CS$<>8__locals1), false);
            base.TryPick(GrowSystem.cell, "resin", -1, 1 + this.<OnMineObj>g__PlantBonus|45_0(ref CS$<>8__locals1) / 2, false);
            if (!EClass.player.isAutoFarming)
            {
                base.TryPick(GrowSystem.cell, TraitSeed.MakeSeed(GrowSystem.cell.sourceObj, CS$<>8__locals1.plant).SetNum(1 + EClass.rnd(3)), c, false);
                if (EClass.rnd(100) == 0)
                {
                    base.TryPick(GrowSystem.cell, "throw_putit", -1, 1, false);
                }
            }
        }
    }
References EClass._map, Baby, Bud, GrowSystem.cell, g__PlantBonus(), Cell.GetPoint(), Grown, Player.isAutoFarming, IsBamboo, Point.IsFarmField, IsPalulu, TraitSeed.MakeSeed(), Cell.matObj_fixed, Mature, OnMineObj(), EClass.player, EClass.rnd(), Card.SetNum(), Cell.sourceObj, Point.sourceObj, Map.TryGetPlant(), and Young.
Referenced by OnMineObj().
SetGenericFirstStageTile()
override void GrowSystemTree.SetGenericFirstStageTile (GrowSystem::Stage s) inline virtual
Reimplemented from GrowSystem.
Definition at line 182 of file GrowSystemTree.cs.
    {
        s.renderData = EClass.core.refs.renderers.objS_flat;
        s.SetTile(0, new int[]
        {
            103
        });
    }
References EClass.core.
SetStageTile()
override void GrowSystemTree.SetStageTile (GrowSystem::Stage s) inline virtual
Reimplemented from GrowSystem.
Reimplemented in GrowSystemTreeSingle.
Definition at line 191 of file GrowSystemTree.cs.
    {
        s.renderData = this.source.renderData;
        s.SetTile(s.idx + ((s.idx != 0) ? -1 : 0), this.baseTiles);
    }
References GrowSystem.source.
Member Data Documentation
shadows
int [] GrowSystemTree.shadows static
Initial value:
= new int[]
    {
        31,
        31,
        32,
        33,
        34,
        1,
        1,
        1
    }
Definition at line 308 of file GrowSystemTree.cs.
Referenced by GetShadow().
Property Documentation
Baby
bool GrowSystemTree.Baby get
Definition at line 109 of file GrowSystemTree.cs.
    {
        get
        {
            return base.stage.idx == 1;
        }
    }
Referenced by OnMineObj().
Bud
bool GrowSystemTree.Bud get
Definition at line 101 of file GrowSystemTree.cs.
    {
        get
        {
            return base.stage.idx == 0;
        }
    }
Referenced by OnMineObj().
DrawHarvestOnTop
override bool GrowSystemTree.DrawHarvestOnTop get protected
Definition at line 69 of file GrowSystemTree.cs.
    {
        get
        {
            return true;
        }
    }
Grown
bool GrowSystemTree.Grown get
Definition at line 125 of file GrowSystemTree.cs.
    {
        get
        {
            return base.stage.idx == 3;
        }
    }
Referenced by OnHitFail(), and OnMineObj().
HarvestStage
override int GrowSystemTree.HarvestStage get
Definition at line 61 of file GrowSystemTree.cs.
    {
        get
        {
            return 4;
        }
    }
IsBamboo
bool GrowSystemTree.IsBamboo get
Definition at line 157 of file GrowSystemTree.cs.
    {
        get
        {
            return this.source.id == 103;
        }
    }
Referenced by OnMineObj().
IsMature
override bool GrowSystemTree.IsMature get
Definition at line 77 of file GrowSystemTree.cs.
    {
        get
        {
            return this.Grown || this.Mature;
        }
    }
IsPalulu
bool GrowSystemTree.IsPalulu get
Definition at line 149 of file GrowSystemTree.cs.
    {
        get
        {
            return this.source.id == 17;
        }
    }
Referenced by OnMineObj().
IsTree
override bool GrowSystemTree.IsTree get
Definition at line 85 of file GrowSystemTree.cs.
    {
        get
        {
            return true;
        }
    }
Mature
bool GrowSystemTree.Mature get
Definition at line 133 of file GrowSystemTree.cs.
    {
        get
        {
            return base.stage.idx == 4;
        }
    }
Referenced by OnHitFail(), and OnMineObj().
MtpProgress
override float GrowSystemTree.MtpProgress get
Definition at line 41 of file GrowSystemTree.cs.
    {
        get
        {
            if (this.Bud || this.Baby)
            {
                return 0.5f;
            }
            if (this.Grown)
            {
                return 2f;
            }
            if (!this.Mature)
            {
                return 1f;
            }
            return 3f;
        }
    }
RenderHarvest
override RenderData GrowSystemTree.RenderHarvest get
Definition at line 7 of file GrowSystemTree.cs.
    {
        get
        {
            return EClass.core.refs.renderers.objL_harvest;
        }
    }
ShadowStage
override int GrowSystemTree.ShadowStage get
Definition at line 93 of file GrowSystemTree.cs.
    {
        get
        {
            return 0;
        }
    }
StageLength
override int GrowSystemTree.StageLength get
Definition at line 23 of file GrowSystemTree.cs.
    {
        get
        {
            return 6;
        }
    }
Step
override int GrowSystemTree.Step get
Definition at line 15 of file GrowSystemTree.cs.
    {
        get
        {
            return 3;
        }
    }
UseGenericFirstStageTile
override bool GrowSystemTree.UseGenericFirstStageTile get protected
Definition at line 165 of file GrowSystemTree.cs.
    {
        get
        {
            return false;
        }
    }
Withered
bool GrowSystemTree.Withered get
Definition at line 141 of file GrowSystemTree.cs.
    {
        get
        {
            return base.stage.idx == 5;
        }
    }
Referenced by OnHitFail().
Young
bool GrowSystemTree.Young get
Definition at line 117 of file GrowSystemTree.cs.
    {
        get
        {
            return base.stage.idx == 2;
        }
    }
Referenced by OnHitFail(), and OnMineObj().
The documentation for this class was generated from the following file:
Elin/GrowSystemTree.cs