Elin Decompiled Documentation: ContentTop Class Reference
ContentTop Class Reference
Public Member Functions
override void OnSwitchContent (int idTab)
Public Member Functions inherited from UIContent
virtual void OnSwitchContent (int idTab)
virtual void OnInstantiate ()
Public Member Functions inherited from UINote
void Clear ()
void Build ()
void Space (int sizeY=0, int sizeX=1)
UINote AddNote (string id)
UIItem AddHeader (string text, Sprite sprite=null)
UIItem AddHeaderCard (string text, Sprite sprite=null)
UIItem AddHeaderTopic (string text, Sprite sprite=null)
UIItem AddHeader (string id, string text, Sprite sprite=null)
UIItem AddText (string text, FontColor color=FontColor.DontChange)
UIItem AddText (string id, string text, FontColor color=FontColor.DontChange)
UIItem AddText (string id, string text, Color color)
UIItem AddItem (string id)
UIItem AddTopic (string id, string text, string value=null)
UIItem AddTopic (string text, string value=null)
void AddImage (Sprite sprite)
void AddImage (string idFile)
UIButton AddButton (string text, Action onClick)
UIButton AddButtonLink (string text, string url)
UIDropdown AddDropdown (string id="DropdownDefault")
UIButton AddToggle (string idLang="", bool isOn=false, Action< bool > action=null)
Transform AddPrefab (string path)
T AddExtra< T > (string path)
Public Attributes
UIText textHomeName
UIList list1
UIList list2
Public Attributes inherited from UINote
RectTransform target
UINoteProfile prof
SkinType skinType
string idDefaultText
LayoutGroup layout
RectTransform cur
bool extraRebuild
Detailed Description
Definition at line 1 of file ContentTop.cs.
Member Function Documentation
OnSwitchContent()
override void ContentTop.OnSwitchContent (int idTab) inline virtual
Reimplemented from UIContent.
Definition at line 9 of file ContentTop.cs.
    {
        textHomeName.text = Lang.Parse("journalTitle", EClass.Home.name);
        EClass.player.notices.Refresh();
        list2.callbacks = new UIList.Callback<Schedule.Item, UIItem>
        {
            onInstantiate = delegate(Schedule.Item a, UIItem b)
            {
                b.text1.text = a.Name;
                b.text2.text = ((a.date == null) ? "????" : a.date.GetText(Date.TextFormat.Schedule));
            }
        };
        list2.Clear();
        foreach (Schedule.Item item in EClass.world.schedule.list)
        {
            list2.Add(item);
        }
        list2.Refresh();
    }
References UIList.Add(), UIList.Clear(), EClass.Home, item, Schedule.list, list2, Faction.name, Player.notices, Lang.Parse(), EClass.player, NoticeManager.Refresh(), UIList.Refresh(), World.schedule, and EClass.world.
Member Data Documentation
list1
UIList ContentTop.list1
Definition at line 5 of file ContentTop.cs.
list2
UIList ContentTop.list2
Definition at line 7 of file ContentTop.cs.
Referenced by OnSwitchContent().
textHomeName
UIText ContentTop.textHomeName
Definition at line 3 of file ContentTop.cs.
The documentation for this class was generated from the following file:
Elin/ContentTop.cs