Elin Decompiled Documentation: CodexManager Class Reference
CodexManager Class Reference
Public Member Functions
CodexCreature GetOrCreate (string id)
void OnLoad ()
void AddCard (string id, int num=1)
bool Has (string id)
void MarkCardDrop (string id)
bool DroppedCard (string id)
void AddKill (string id)
void AddWeakspot (string id)
void AddSpawn (string id)
List< CardRow > ListKills ()
Public Attributes
Dictionary< string, CodexCreature > creatures = new Dictionary<string, CodexCreature>()
Additional Inherited Members
Static Public Member Functions inherited from EClass
static int rnd (int a)
static int curve (int a, int start, int step, int rate=75)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Static Public Attributes inherited from EClass
static Core core
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Detailed Description
Definition at line 4 of file CodexManager.cs.
Member Function Documentation
AddCard()
void CodexManager.AddCard (string id, int num = 1) inline
Definition at line 31 of file CodexManager.cs.
    {
        GetOrCreate(id).numCard += num;
    }
References GetOrCreate(), and CodexCreature.numCard.
Referenced by ContentCodex.Collect(), and ContentCodex.OnClickAddCards().
AddKill()
void CodexManager.AddKill (string id) inline
Definition at line 55 of file CodexManager.cs.
    {
        GetOrCreate(id).kills++;
    }
References GetOrCreate(), and CodexCreature.kills.
Referenced by Card.DamageHP().
AddSpawn()
void CodexManager.AddSpawn (string id) inline
Definition at line 65 of file CodexManager.cs.
    {
        GetOrCreate(id).spawns++;
    }
References GetOrCreate(), and CodexCreature.spawns.
Referenced by CharaGen._Create().
AddWeakspot()
void CodexManager.AddWeakspot (string id) inline
Definition at line 60 of file CodexManager.cs.
    {
        GetOrCreate(id).weakspot++;
    }
References GetOrCreate(), and CodexCreature.weakspot.
Referenced by TraitBaseSpellbook.OnRead().
DroppedCard()
bool CodexManager.DroppedCard (string id) inline
Definition at line 46 of file CodexManager.cs.
    {
        if (creatures.ContainsKey(id))
        {
            return creatures[id].droppedCard;
        }
        return false;
    }
References creatures.
Referenced by Card.SpawnLoot().
GetOrCreate()
CodexCreature CodexManager.GetOrCreate (string id) inline
Definition at line 9 of file CodexManager.cs.
    {
        CodexCreature codexCreature = creatures.TryGetValue(id);
        if (codexCreature == null)
        {
            codexCreature = new CodexCreature
            {
                id = id
            };
            creatures[id] = codexCreature;
        }
        return codexCreature;
    }
References creatures.
Referenced by AddCard(), AddKill(), AddSpawn(), AddWeakspot(), Card.DamageHP(), MarkCardDrop(), and Card.SpawnLoot().
Has()
bool CodexManager.Has (string id) inline
Definition at line 36 of file CodexManager.cs.
    {
        return creatures.ContainsKey(id);
    }
References creatures.
Referenced by InvOwnerChaosOffering._OnProcess(), and Card.DamageHP().
ListKills()
List< CardRow > CodexManager.ListKills () inline
Definition at line 70 of file CodexManager.cs.
    {
        List<CardRow> list = new List<CardRow>();
        foreach (KeyValuePair<string, CodexCreature> creature in creatures)
        {
            if (creature.Value.kills > 0)
            {
                CardRow cardRow = EClass.sources.cards.map.TryGetValue(creature.Key);
                if (cardRow != null && !cardRow.HasTag(CTAG.noRandomProduct))
                {
                    list.Add(cardRow);
                }
            }
        }
        return list;
    }
References SourceManager.cards, creatures, RenderRow.HasTag(), SourceCard.map, and EClass.sources.
Referenced by TraitCrafter.Craft().
MarkCardDrop()
void CodexManager.MarkCardDrop (string id) inline
Definition at line 41 of file CodexManager.cs.
    {
        GetOrCreate(id).droppedCard = true;
    }
References CodexCreature.droppedCard, and GetOrCreate().
Referenced by Card.SpawnLoot().
OnLoad()
void CodexManager.OnLoad () inline
Definition at line 23 of file CodexManager.cs.
    {
        foreach (KeyValuePair<string, CodexCreature> creature in creatures)
        {
            creature.Value.id = creature.Key;
        }
    }
References creatures.
Referenced by Player.OnLoad().
Member Data Documentation
creatures
Dictionary<string, CodexCreature> CodexManager.creatures = new Dictionary<string, CodexCreature>()
Definition at line 7 of file CodexManager.cs.
Referenced by DroppedCard(), GetOrCreate(), Has(), ListKills(), OnLoad(), and ContentCodex.RefreshList().
The documentation for this class was generated from the following file:
Elin/CodexManager.cs