Elin Decompiled Documentation: CustomElementContent Class Reference
CustomElementContent Class Reference
Public Member Functions
override void OnGameLoad (GameIOContext context)
override string ToString ()
Public Member Functions inherited from CustomContent
virtual void OnGameLoad (GameIOContext context)
virtual void OnGameSave (GameIOContext context)
override string ToString ()
Static Public Member Functions
static CustomElementContent CreateFromRow (SourceElement.Row r, ModPackage owner=null)
Static Public Member Functions inherited from CustomSourceContent
static string string string[] kv GetParams (string tag)
Static Public Member Functions inherited from EClass
static int rndSeed (int a, int seed)
static int rnd (long a)
static int rnd (int a)
static int curve (long _a, int start, int step, int rate=75)
static int sqrt (int a)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Public Attributes
bool addOnLoad
Properties
override string SourceType [get]
Properties inherited from CustomSourceContent
virtual string SourceType [get]
string SourceId [get, set]
Properties inherited from CustomContent
string ContentId [get, protected set]
EMod Owner [get, protected set]
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Additional Inherited Members
Static Public Attributes inherited from CustomSourceContent
static string action
static string string spec
Static Public Attributes inherited from EClass
static Core core
Detailed Description
Definition at line 4 of file CustomElementContent.cs.
Member Function Documentation
CreateFromRow()
static CustomElementContent CustomElementContent.CreateFromRow (SourceElement::Row r, ModPackage owner = null) inline static
Definition at line 10 of file CustomElementContent.cs.
    {
        if (owner == null)
        {
            owner = ModUtil.FindSourceRowPackage(r);
        }
        CustomElementContent customElementContent = new CustomElementContent
        {
            ContentId = "Element/" + r.alias,
            SourceId = r.alias,
            Owner = owner
        };
        string[] tag = r.tag;
        int i;
        for (i = 0; i < tag.Length; i++)
        {
            string item = CustomSourceContent.GetParams(tag[i]).action;
            if (item == "addEleOnLoad" || item == "addOnLoad")
            {
                customElementContent.addOnLoad = true;
            }
        }
        i = r.id;
        if (i > 10000 || i < 0)
        {
            switch (r.group)
            {
            case "FEAT":
            case "ABILITY":
            case "SPELL":
            {
                i = ((!(r.group == "FEAT")) ? 48 : 32);
                int num = i;
                ModUtil.AppendSpriteSheet(r.alias, num, num);
                break;
            }
            }
        }
        return customElementContent;
    }
References CustomContent.ContentId, CustomSourceContent.GetParams(), item, CustomContent.Owner, and CustomSourceContent.SourceId.
Referenced by ModPackage.GenerateCustomContentProfiles().
OnGameLoad()
override void CustomElementContent.OnGameLoad (GameIOContext context) inline virtual
Reimplemented from CustomContent.
Definition at line 51 of file CustomElementContent.cs.
    {
        SourceElement.Row row = EClass.sources.elements.alias[base.SourceId];
        if (addOnLoad && !EClass.pc.HasElement(base.SourceId))
        {
            switch (row.group)
            {
            case "FEAT":
                EClass.pc.SetFeat(row.id, 1, msg: true);
                break;
            case "ABILITY":
            case "SPELL":
                EClass.pc.GainAbility(row.id);
                break;
            }
        }
    }
References addOnLoad, SourceManager.elements, Chara.GainAbility(), SourceElement.Row.group, Card.HasElement(), SourceElement.Row.id, EClass.pc, Chara.SetFeat(), and EClass.sources.
ToString()
override string CustomElementContent.ToString () inline
Definition at line 69 of file CustomElementContent.cs.
    {
        return $"{base.ContentId}/addOnLoad={addOnLoad}";
    }
References $.
Member Data Documentation
addOnLoad
bool CustomElementContent.addOnLoad
Definition at line 6 of file CustomElementContent.cs.
Referenced by OnGameLoad().
Property Documentation
SourceType
override string CustomElementContent.SourceType get
Definition at line 8 of file CustomElementContent.cs.
The documentation for this class was generated from the following file:
Elin/CustomElementContent.cs