Elin Decompiled Documentation: SpawnSetting Class Reference
SpawnSetting Class Reference
Static Public Member Functions
static SpawnSetting Evolved (int fixedLv=-1)
static SpawnSetting Boss (int filterLv, int fixedLv=-1)
static SpawnSetting Boss (string id, string idEle=null, int fixedLv=-1)
static SpawnSetting Encounter (int lv)
static SpawnSetting Mob (string id, string idEle=null, int fixedLv=-1)
static SpawnSetting HomeWild (int lv)
static SpawnSetting HomeGuest (int lv)
static SpawnSetting HomeEnemy (int lv)
static SpawnSetting DefenseEnemy (int lv)
static SpawnSetting Fish ()
Public Attributes
int filterLv = -1
int dangerLv = -1
int fixedLv = -1
int tries = 100
int levelRange = -1
bool isBoss
bool isEvolved
string idSpawnList
string id
string idEle
Rarity rarity = Rarity.Random
SpawnHostility hostility = SpawnHostility.Enemy
Hostility? forcedHostility
SpawnPosition position
Static Public Attributes
static SpawnSetting Default = new SpawnSetting()
static SpawnSetting Debug = new SpawnSetting()
Detailed Description
Definition at line 1 of file SpawnSetting.cs.
Member Function Documentation
Boss() [1/2]
static SpawnSetting SpawnSetting.Boss (int filterLv, int fixedLv = -1) inline static
Definition at line 47 of file SpawnSetting.cs.
    {
        return new SpawnSetting
        {
            filterLv = filterLv - 2,
            fixedLv = fixedLv,
            rarity = Rarity.Legendary,
            isBoss = true,
            tries = 10000,
            levelRange = 5,
            forcedHostility = Hostility.Enemy
        };
    }
References filterLv, fixedLv, forcedHostility, isBoss, levelRange, rarity, and tries.
Referenced by TraitShrine._OnUse(), ZoneEventSiege.CreateChara(), Zone_RandomDungeon.OnGenerateMap(), Zone_Void.OnGenerateMap(), ZoneEventQuest.SpawnBoss(), and CoreDebug.SpawnBoss().
Boss() [2/2]
static SpawnSetting SpawnSetting.Boss (string id, string idEle = null, int fixedLv = -1) inline static
Definition at line 61 of file SpawnSetting.cs.
    {
        return new SpawnSetting
        {
            id = id,
            idEle = idEle,
            fixedLv = fixedLv,
            rarity = Rarity.Legendary,
            isBoss = true,
            tries = 10000
        };
    }
References fixedLv, id, idEle, isBoss, rarity, and tries.
DefenseEnemy()
static SpawnSetting SpawnSetting.DefenseEnemy (int lv) inline static
Definition at line 128 of file SpawnSetting.cs.
    {
        return new SpawnSetting
        {
            filterLv = lv,
            position = SpawnPosition.Outside,
            rarity = Rarity.Normal
        };
    }
References filterLv, position, and rarity.
Referenced by TraitShrine._OnUse(), ZoneEventSiege.CreateChara(), and ZoneEventQuest.Spawn().
Encounter()
static SpawnSetting SpawnSetting.Encounter (int lv) inline static
Definition at line 74 of file SpawnSetting.cs.
    {
        return new SpawnSetting
        {
            filterLv = lv,
            hostility = SpawnHostility.Random
        };
    }
References filterLv, and hostility.
Referenced by ZonePreEnterEncounter.Execute().
Evolved()
static SpawnSetting SpawnSetting.Evolved (int fixedLv = -1) inline static
Definition at line 35 of file SpawnSetting.cs.
    {
        return new SpawnSetting
        {
            fixedLv = fixedLv,
            rarity = Rarity.Legendary,
            forcedHostility = Hostility.Neutral,
            isEvolved = true,
            tries = 10000
        };
    }
References fixedLv, forcedHostility, isEvolved, rarity, and tries.
Referenced by ZoneEventSiege.CreateChara(), and Zone.TryGenerateEvolved().
Fish()
static SpawnSetting SpawnSetting.Fish () inline static
Definition at line 138 of file SpawnSetting.cs.
    {
        return new SpawnSetting
        {
            hostility = SpawnHostility.Random,
            idSpawnList = "c_randomFish"
        };
    }
References hostility, and idSpawnList.
Referenced by Zone.Generate().
HomeEnemy()
static SpawnSetting SpawnSetting.HomeEnemy (int lv) inline static
Definition at line 117 of file SpawnSetting.cs.
    {
        return new SpawnSetting
        {
            filterLv = lv,
            position = SpawnPosition.Outside,
            rarity = Rarity.Normal,
            hostility = SpawnHostility.Enemy
        };
    }
References filterLv, hostility, position, and rarity.
Referenced by SurvivalManager.OnMineWreck().
HomeGuest()
static SpawnSetting SpawnSetting.HomeGuest (int lv) inline static
Definition at line 105 of file SpawnSetting.cs.
    {
        return new SpawnSetting
        {
            filterLv = lv,
            hostility = SpawnHostility.Neutral,
            idSpawnList = "c_guest",
            position = SpawnPosition.Guest,
            rarity = Rarity.Normal
        };
    }
References filterLv, hostility, idSpawnList, position, and rarity.
HomeWild()
static SpawnSetting SpawnSetting.HomeWild (int lv) inline static
Definition at line 93 of file SpawnSetting.cs.
    {
        return new SpawnSetting
        {
            filterLv = lv,
            hostility = SpawnHostility.Random,
            idSpawnList = "c_animal",
            position = SpawnPosition.Outside,
            rarity = Rarity.Normal
        };
    }
References filterLv, hostility, idSpawnList, position, and rarity.
Referenced by SurvivalManager.OnMineWreck(), ZoneEventHarvest.OnVisit(), and TraitSpotBiome.Update().
Mob()
static SpawnSetting SpawnSetting.Mob (string id, string idEle = null, int fixedLv = -1) inline static
Definition at line 83 of file SpawnSetting.cs.
    {
        return new SpawnSetting
        {
            id = id,
            idEle = idEle,
            fixedLv = fixedLv
        };
    }
References fixedLv, id, and idEle.
Referenced by ZonePreEnterEncounter.Execute().
Member Data Documentation
dangerLv
int SpawnSetting.dangerLv = -1
Definition at line 5 of file SpawnSetting.cs.
Debug
SpawnSetting SpawnSetting.Debug = new SpawnSetting() static
Definition at line 33 of file SpawnSetting.cs.
Default
SpawnSetting SpawnSetting.Default = new SpawnSetting() static
Definition at line 31 of file SpawnSetting.cs.
Referenced by Zone.SpawnMob().
filterLv
int SpawnSetting.filterLv = -1
Definition at line 3 of file SpawnSetting.cs.
Referenced by Boss(), DefenseEnemy(), Encounter(), HomeEnemy(), HomeGuest(), and HomeWild().
fixedLv
int SpawnSetting.fixedLv = -1
Definition at line 7 of file SpawnSetting.cs.
Referenced by Boss(), Evolved(), and Mob().
forcedHostility
Hostility? SpawnSetting.forcedHostility
Definition at line 27 of file SpawnSetting.cs.
Referenced by Boss(), and Evolved().
hostility
SpawnHostility SpawnSetting.hostility = SpawnHostility.Enemy
Definition at line 25 of file SpawnSetting.cs.
Referenced by Encounter(), Fish(), HomeEnemy(), HomeGuest(), and HomeWild().
id
string SpawnSetting.id
Definition at line 19 of file SpawnSetting.cs.
Referenced by Boss(), and Mob().
idEle
string SpawnSetting.idEle
Definition at line 21 of file SpawnSetting.cs.
Referenced by Boss(), and Mob().
idSpawnList
string SpawnSetting.idSpawnList
Definition at line 17 of file SpawnSetting.cs.
Referenced by Fish(), HomeGuest(), and HomeWild().
isBoss
bool SpawnSetting.isBoss
Definition at line 13 of file SpawnSetting.cs.
Referenced by Boss().
isEvolved
bool SpawnSetting.isEvolved
Definition at line 15 of file SpawnSetting.cs.
Referenced by Evolved().
levelRange
int SpawnSetting.levelRange = -1
Definition at line 11 of file SpawnSetting.cs.
Referenced by Boss().
position
SpawnPosition SpawnSetting.position
Definition at line 29 of file SpawnSetting.cs.
Referenced by DefenseEnemy(), HomeEnemy(), HomeGuest(), and HomeWild().
rarity
Rarity SpawnSetting.rarity = Rarity.Random
Definition at line 23 of file SpawnSetting.cs.
Referenced by Boss(), DefenseEnemy(), Evolved(), HomeEnemy(), HomeGuest(), and HomeWild().
tries
int SpawnSetting.tries = 100
Definition at line 9 of file SpawnSetting.cs.
Referenced by Boss(), and Evolved().
The documentation for this class was generated from the following file:
Elin/SpawnSetting.cs