Elin Decompiled Documentation: TraitMap Class Reference
TraitMap Class Reference
Public Member Functions
void Add (Card c)
void Remove (Card c)
Card GetRandom ()
Card GetRandom (Func< Trait, bool > func)
Card GetRandomInstalled ()
bool Contains (Card c)
Detailed Description
Definition at line 5 of file TraitMap.cs.
Member Function Documentation
Add()
void TraitMap.Add (Card c) inline
Definition at line 7 of file TraitMap.cs.
    {
        Add(c.uid, c.trait);
    }
References Add(), Card.trait, and Card.uid.
Referenced by Add(), and TraitManager.OnAddCard().
Contains()
bool TraitMap.Contains (Card c) inline
Definition at line 40 of file TraitMap.cs.
    {
        return ContainsKey(c.uid);
    }
References Card.uid.
GetRandom() [1/2]
Card TraitMap.GetRandom () inline
Definition at line 17 of file TraitMap.cs.
    {
        return this.RandomItem()?.owner;
    }
Referenced by GetRandom().
GetRandom() [2/2]
Card TraitMap.GetRandom (Func< Trait, bool > func) inline
Definition at line 22 of file TraitMap.cs.
    {
        if (func == null)
        {
            return GetRandom();
        }
        return base.Values.Where(func).RandomItem()?.owner;
    }
References GetRandom().
GetRandomInstalled()
Card TraitMap.GetRandomInstalled () inline
Definition at line 31 of file TraitMap.cs.
    {
        if (base.Count == 0)
        {
            return null;
        }
        return base.Values.Where((Trait a) => a.owner.placeState == PlaceState.installed).RandomItem()?.owner;
    }
References Trait.owner, and Card.placeState.
Referenced by AI_Offer.Run().
Remove()
void TraitMap.Remove (Card c) inline
Definition at line 12 of file TraitMap.cs.
    {
        Remove(c.uid);
    }
References Remove(), and Card.uid.
Referenced by TraitManager.OnRemoveCard(), and Remove().
The documentation for this class was generated from the following file:
Elin/TraitMap.cs