Elin Decompiled Documentation: WidgetRoster Class Reference
WidgetRoster Class Reference
Classes
class Extra
Public Member Functions
override object CreateExtra ()
override void OnActivate ()
void OnMoveZone ()
void Build ()
void Refresh ()
void Add (Chara c)
void Remove (Chara c)
void OnAddMember (Chara c)
void OnRemoveMember (Chara c)
override void OnSetContextMenu (UIContextMenu m)
Public Member Functions inherited from Widget
void Test ()
bool IsInRightMode ()
void Activate ()
virtual void OnActivate ()
virtual object CreateExtra ()
void Deactivate ()
virtual void OnDeactivate ()
void Close ()
void Reactivate ()
virtual void OnManagerActivate ()
virtual void OnManagerDeactivate ()
void SetAnchor (RectPosition p)
void SetPivot (RectPosition p)
virtual void OnChangePivot ()
void UpdateConfig ()
virtual void OnUpdateConfig ()
void ClampToScreen ()
virtual void OnChangeResolution ()
void OnChangePosition ()
virtual void OnChangeActionMode ()
virtual void OnFlip ()
bool IsAlignTop ()
Layer AddLayer (Layer l, Transform trans)
void RefreshTipPivotPosition ()
SkinSet GetSkin ()
SkinConfig GetSkinConfig ()
void SetSkin (int id, int v=0)
void TestSkin ()
virtual void ApplySkin ()
virtual void OnApplySkin ()
void InstantiateDeco (SkinDeco deco)
void AddDeco (SkinDeco deco)
void RemoveDeco (SkinDeco deco)
virtual bool CanShowContextMenu ()
void ShowContextMenu ()
void SetBaseContextMenu (UIContextMenu m)
virtual void OnSetContextMenu (UIContextMenu m)
void SetGridContextMenu (UIContextMenu m)
void SoundActivate ()
Static Public Member Functions
static void SetDirty ()
Static Public Member Functions inherited from EMono
static int rnd (int a)
Public Attributes
GridLayoutGroup layout
ButtonRoster mold
RawImage imageGrid
Dictionary< Chara, ButtonRoster > buttons = new Dictionary<Chara, ButtonRoster>()
UIButton moldDropperLeft
UIButton moldDropperRight
bool showName
bool dirty
int maxWidth
Public Attributes inherited from Widget
Image imageBG
SoundData soundActivate
UIDragPanel dragPanel
RectTransform tipPivotLeft
RectTransform tipPivotRight
Static Public Attributes
static WidgetRoster Instance
Static Public Attributes inherited from EMono
static Core core
Properties
WidgetRoster.Extra extra [get]
override bool AlwaysBottom [get]
override Type SetSiblingAfter [get]
Properties inherited from Widget
string ID [get]
Widget.Config config [get]
SkinRoot skinRoot [get]
bool IsSealed [get]
virtual bool ShowStyleMenu [get]
virtual bool AlwaysTop [get]
virtual bool IsStaticPosition [get]
virtual bool AlwaysBottom [get]
virtual Type SetSiblingAfter [get]
virtual bool ShowInBuildMode [get]
virtual bool RightClickToClose [get]
virtual bool AllowRightClickToClose [get]
Properties inherited from EMono
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SoundManager Sound [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static CoreDebug debug [get]
Private Member Functions
void OnEnable ()
void OnDisable ()
Additional Inherited Members
Public Types inherited from Widget
enum WidgetType { Default , ZoomMenu }
enum State { Active , Inactive }
Protected Member Functions inherited from Widget
void ClampToScreenEnsured (Component c, Vector2 anchoredPos)
void ClampToScreen (RectTransform rect, float margin=10f)
Protected Attributes inherited from Widget
bool flip
Detailed Description
Definition at line 7 of file WidgetRoster.cs.
Member Function Documentation
Add()
void WidgetRoster.Add (Chara c) inline
Definition at line 113 of file WidgetRoster.cs.
    {
        ButtonRoster buttonRoster = Util.Instantiate<ButtonRoster>(this.mold, this.layout);
        buttonRoster.SetChara(c);
        this.buttons.Add(c, buttonRoster);
    }
References buttons, layout, mold, and ButtonRoster.SetChara().
Referenced by Build(), and OnAddMember().
Build()
void WidgetRoster.Build () inline
Definition at line 67 of file WidgetRoster.cs.
    {
        this.buttons.Clear();
        this.layout.DestroyChildren(false, true);
        this.layout.constraint = (this.extra.vertical ? GridLayoutGroup.Constraint.FixedColumnCount : GridLayoutGroup.Constraint.FixedRowCount);
        this.layout.startCorner = (this.extra.reverse ? GridLayoutGroup.Corner.LowerRight : GridLayoutGroup.Corner.UpperLeft);
        this.layout.cellSize = new Vector2((float)(this.extra.width * 4 / 5), (float)(this.extra.onlyName ? 32 : this.extra.width));
        this.layout.spacing = new Vector2((float)this.extra.margin, (float)this.extra.margin);
        foreach (Chara chara in EMono.pc.party.members)
        {
            if (chara != EMono.pc || this.extra.pc)
            {
                this.Add(chara);
            }
        }
        if (this.buttons.Count == 0)
        {
            this.Add(EMono.pc);
        }
        this.layout.RebuildLayout(false);
        this.RebuildLayout(false);
        this.OnChangeResolution();
        base.ClampToScreen();
    }
References Add(), buttons, extra, layout, Party.members, Widget.OnChangeResolution(), Chara.party, EClass.pc, and EMono.pc.
Referenced by OnActivate(), OnMoveZone(), OnSetContextMenu(), and Refresh().
CreateExtra()
override object WidgetRoster.CreateExtra () inline virtual
Reimplemented from Widget.
Definition at line 9 of file WidgetRoster.cs.
    {
        return new WidgetRoster.Extra();
    }
OnActivate()
override void WidgetRoster.OnActivate () inline virtual
Reimplemented from Widget.
Definition at line 38 of file WidgetRoster.cs.
    {
        if (Mathf.Abs(this.extra.margin) > 100)
        {
            this.extra.margin = 0;
            this.extra.width = 40;
            this.extra.portrait = false;
            this.extra.onlyName = true;
        }
        WidgetRoster.Instance = this;
        this.mold = this.layout.CreateMold(null);
        this.Build();
    }
References Build(), and layout.
OnAddMember()
void WidgetRoster.OnAddMember (Chara c) inline
Definition at line 126 of file WidgetRoster.cs.
    {
        if (this.buttons.ContainsKey(c))
        {
            return;
        }
        this.Add(c);
    }
References Add(), and buttons.
OnDisable()
void WidgetRoster.OnDisable () inline private
Definition at line 57 of file WidgetRoster.cs.
    {
        base.CancelInvoke();
    }
OnEnable()
void WidgetRoster.OnEnable () inline private
Definition at line 52 of file WidgetRoster.cs.
    {
        base.InvokeRepeating("Refresh", 0.2f, 0.2f);
    }
OnMoveZone()
void WidgetRoster.OnMoveZone () inline
Definition at line 62 of file WidgetRoster.cs.
    {
        this.Build();
    }
References Build().
Referenced by Player.MoveZone().
OnRemoveMember()
void WidgetRoster.OnRemoveMember (Chara c) inline
Definition at line 135 of file WidgetRoster.cs.
    {
        if (!this.buttons.ContainsKey(c))
        {
            return;
        }
        this.Remove(c);
    }
References buttons, and Remove().
OnSetContextMenu()
override void WidgetRoster.OnSetContextMenu (UIContextMenu m) inline virtual
Reimplemented from Widget.
Definition at line 144 of file WidgetRoster.cs.
    {
        ButtonRoster b = InputModuleEX.GetComponentOf<ButtonRoster>();
        if (b)
        {
            int index = EMono.pc.party.members.IndexOf(b.chara);
            int count = EMono.pc.party.members.Count;
            if (index >= 1 && index < count - 1)
            {
                m.AddButton("next", delegate()
                {
                    base.<OnSetContextMenu>g__Move|11(1);
                }, true);
            }
            if (index >= 2)
            {
                m.AddButton("prev", delegate()
                {
                    base.<OnSetContextMenu>g__Move|11(-1);
                }, true);
            }
        }
        UIContextMenu uicontextMenu = m.AddChild("setting");
        uicontextMenu.AddSlider("width", (float a) => a.ToString() ?? "", (float)this.extra.width, delegate(float a)
        {
            this.extra.width = (int)a;
            this.Build();
        }, 30f, 160f, true, true, false);
        uicontextMenu.AddSlider("margine", (float a) => a.ToString() ?? "", (float)this.extra.margin, delegate(float a)
        {
            this.extra.margin = (int)a;
            this.Build();
        }, -50f, 50f, true, true, false);
        uicontextMenu.AddToggle("roster_pc", this.extra.pc, delegate(bool a)
        {
            this.extra.pc = a;
            this.Build();
        });
        uicontextMenu.AddToggle("vertical", this.extra.vertical, delegate(bool a)
        {
            this.extra.vertical = a;
            this.Build();
        });
        uicontextMenu.AddToggle("roster_portrait", this.extra.portrait, delegate(bool a)
        {
            this.extra.portrait = a;
            this.Build();
        });
        uicontextMenu.AddToggle("roster_onlyname", this.extra.onlyName, delegate(bool a)
        {
            this.extra.onlyName = a;
            this.Build();
        });
        uicontextMenu.AddToggle("reverseOrder", this.extra.reverse, delegate(bool a)
        {
            this.extra.reverse = a;
            this.Build();
        });
        m.AddChild("style").AddSlider("toggleButtonBG", (float a) => a.ToString() ?? "", (float)base.config.skin.button, delegate(float a)
        {
            this.config.skin.button = (int)a;
            this.ApplySkin();
        }, 0f, (float)(base.config.skin.Skin.buttons.Count - 1), true, true, false);
        base.SetBaseContextMenu(m);
    }
References Widget.ApplySkin(), Build(), ButtonRoster.chara, extra, Party.members, OnSetContextMenu(), Chara.party, and EMono.pc.
Referenced by OnSetContextMenu().
Refresh()
void WidgetRoster.Refresh () inline
Definition at line 100 of file WidgetRoster.cs.
    {
        if (this.dirty)
        {
            this.Build();
        }
        foreach (ButtonRoster buttonRoster in this.buttons.Values)
        {
            buttonRoster.Refresh();
        }
        this.dirty = false;
    }
References Build(), buttons, dirty, and ButtonRoster.Refresh().
Remove()
void WidgetRoster.Remove (Chara c) inline
Definition at line 120 of file WidgetRoster.cs.
    {
        UnityEngine.Object.DestroyImmediate(this.buttons[c].gameObject);
        this.buttons.Remove(c);
    }
References buttons.
Referenced by OnRemoveMember().
SetDirty()
static void WidgetRoster.SetDirty () inline static
Definition at line 92 of file WidgetRoster.cs.
    {
        if (WidgetRoster.Instance)
        {
            WidgetRoster.Instance.dirty = true;
        }
    }
References Instance.
Referenced by Party.AddMemeber(), and Party.RemoveMember().
Member Data Documentation
buttons
Dictionary<Chara, ButtonRoster> WidgetRoster.buttons = new Dictionary<Chara, ButtonRoster>()
Definition at line 218 of file WidgetRoster.cs.
Referenced by Add(), Build(), OnAddMember(), OnRemoveMember(), Refresh(), and Remove().
dirty
bool WidgetRoster.dirty
Definition at line 226 of file WidgetRoster.cs.
Referenced by Refresh().
imageGrid
RawImage WidgetRoster.imageGrid
Definition at line 216 of file WidgetRoster.cs.
Instance
WidgetRoster WidgetRoster.Instance static
Definition at line 210 of file WidgetRoster.cs.
Referenced by Player.MoveZone(), and SetDirty().
layout
GridLayoutGroup WidgetRoster.layout
Definition at line 212 of file WidgetRoster.cs.
Referenced by Add(), Build(), and OnActivate().
maxWidth
int WidgetRoster.maxWidth
Definition at line 228 of file WidgetRoster.cs.
mold
ButtonRoster WidgetRoster.mold
Definition at line 214 of file WidgetRoster.cs.
Referenced by Add().
moldDropperLeft
UIButton WidgetRoster.moldDropperLeft
Definition at line 220 of file WidgetRoster.cs.
moldDropperRight
UIButton WidgetRoster.moldDropperRight
Definition at line 222 of file WidgetRoster.cs.
showName
bool WidgetRoster.showName
Definition at line 224 of file WidgetRoster.cs.
Property Documentation
AlwaysBottom
override bool WidgetRoster.AlwaysBottom get
Definition at line 22 of file WidgetRoster.cs.
    {
        get
        {
            return true;
        }
    }
extra
WidgetRoster.Extra WidgetRoster.extra get
Definition at line 14 of file WidgetRoster.cs.
    {
        get
        {
            return base.config.extra as WidgetRoster.Extra;
        }
    }
Referenced by Build(), OnSetContextMenu(), ButtonRoster.Refresh(), and ButtonRoster.SetChara().
SetSiblingAfter
override Type WidgetRoster.SetSiblingAfter get
Definition at line 30 of file WidgetRoster.cs.
    {
        get
        {
            return typeof(WidgetBottomBar);
        }
    }
The documentation for this class was generated from the following file:
Elin/WidgetRoster.cs