Elin Decompiled Documentation: ObjInfo Class Reference
ObjInfo Class Reference
Public Member Functions
override void WriteNote (UINote n, Action< UINote > onWriteNote=null, IInspect.NoteMode mode=IInspect.NoteMode.Default, Recipe recipe=null)
Public Member Functions inherited from BaseInspectPos
void OnInspect ()
virtual void WriteNote (UINote n, Action< UINote > onWriteNote=null, IInspect.NoteMode mode=IInspect.NoteMode.Default, Recipe recipe=null)
void WriteNote (UINote n, Action< UINote > onWriteNote=null, IInspect.NoteMode mode=IInspect.NoteMode.Default, Recipe recipe=null)
void OnInspect ()
Static Public Member Functions
static ObjInfo GetTemp (Point _pos)
static ObjInfo GetTempList (Point _pos)
static bool _CanInspect (Point pos)
Static Public Attributes
static ObjInfo Temp = new ObjInfo()
static ObjInfo TempList = new ObjInfo()
static VirtualDate TempDate = new VirtualDate(0)
Properties
SourceObj.Row source [get]
override bool CanInspect [get]
override string InspectName [get]
Properties inherited from BaseInspectPos
Point InspectPoint [get]
unsafe Vector3 InspectPosition [get]
virtual bool CanInspect [get]
virtual string InspectName [get]
Properties inherited from IInspect
bool CanInspect [get]
string InspectName [get]
Point InspectPoint [get]
Vector3 InspectPosition [get]
Additional Inherited Members
Public Types inherited from IInspect
enum NoteMode { Default , Recipe , Product , Info }
Public Attributes inherited from BaseInspectPos
Point pos = new Point()
Detailed Description
Definition at line 3 of file ObjInfo.cs.
Member Function Documentation
_CanInspect()
static bool ObjInfo._CanInspect (Point pos) inline static
Definition at line 33 of file ObjInfo.cs.
    {
        return pos.HasObj && (!pos.cell.HasFullBlock || pos.sourceObj.tileType.IsBlockMount);
    }
References BaseInspectPos.pos, and Point.sourceObj.
Referenced by Point.ListInspectorTargets(), and PointTarget.Update().
GetTemp()
static ObjInfo ObjInfo.GetTemp (Point _pos) inline static
Definition at line 5 of file ObjInfo.cs.
    {
        if (!ObjInfo.Temp.pos.Equals(_pos))
        {
            ObjInfo.TempDate = new VirtualDate(0);
        }
        ObjInfo.Temp.pos.Set(_pos);
        return ObjInfo.Temp;
    }
References Point.Equals(), BaseInspectPos.pos, Point.Set(), and Temp.
Referenced by PointTarget.Update().
GetTempList()
static ObjInfo ObjInfo.GetTempList (Point _pos) inline static
Definition at line 15 of file ObjInfo.cs.
    {
        if (!ObjInfo.TempList.pos.Equals(_pos))
        {
            ObjInfo.TempList = new ObjInfo();
        }
        ObjInfo.TempList.pos.Set(_pos);
        return ObjInfo.TempList;
    }
References Point.Equals(), BaseInspectPos.pos, Point.Set(), and TempList.
Referenced by Point.ListInspectorTargets().
WriteNote()
override void ObjInfo.WriteNote (UINote n, Action< UINote > onWriteNote = null, IInspect::NoteMode mode = IInspect::NoteMode::Default, Recipe recipe = null) inline virtual
Reimplemented from BaseInspectPos.
Definition at line 78 of file ObjInfo.cs.
    {
        n.Clear();
        UIItem uiitem = n.AddHeaderCard(this.source.GetName(), null);
        this.source.SetImage(uiitem.image2, null, this.source.GetColorInt(this.pos.cell.matObj), true, 0, 0);
        n.AddText("isMadeOf".lang(this.source.GetText("name", false), null, null, null, null), FontColor.DontChange);
        n.Build();
    }
References SourceObj.GetName(), and source.
Member Data Documentation
Temp
ObjInfo ObjInfo.Temp = new ObjInfo() static
Definition at line 87 of file ObjInfo.cs.
Referenced by GetTemp().
TempDate
VirtualDate ObjInfo.TempDate = new VirtualDate(0) static
Definition at line 91 of file ObjInfo.cs.
TempList
ObjInfo ObjInfo.TempList = new ObjInfo() static
Definition at line 89 of file ObjInfo.cs.
Referenced by GetTempList().
Property Documentation
CanInspect
override bool ObjInfo.CanInspect get
Implements IInspect.
Definition at line 38 of file ObjInfo.cs.
    {
        get
        {
            return ObjInfo._CanInspect(this.pos);
        }
    }
InspectName
override string ObjInfo.InspectName get
Implements IInspect.
Definition at line 46 of file ObjInfo.cs.
    {
        get
        {
            string text = this.pos.cell.GetObjName() + (EClass.debug.showExtra ? (" " + this.pos.cell.matObj.alias) : "");
            if (this.pos.growth != null)
            {
                if (this.pos.growth.CanHarvest())
                {
                    text = "growth_harvest".lang(text, null, null, null, null);
                }
                else if (this.pos.growth.IsWithered())
                {
                    text = "growth_withered".lang(text, null, null, null, null);
                }
                else if (this.pos.growth.IsMature)
                {
                    text = "growth_mature".lang(text, null, null, null, null);
                }
                if ((EClass._zone.IsPCFaction || EClass._zone is Zone_Tent) && this.pos.growth.NeedSunlight && !this.pos.growth.CanGrow(ObjInfo.TempDate))
                {
                    text = "growth_nosun".lang(text, null, null, null, null);
                    if (this.pos.cell.HasRoof)
                    {
                        text = "growth_roof".lang(text, null, null, null, null);
                    }
                }
            }
            return text;
        }
    }
source
SourceObj.Row ObjInfo.source get
Definition at line 25 of file ObjInfo.cs.
    {
        get
        {
            return this.pos.sourceObj;
        }
    }
Referenced by WriteNote().
The documentation for this class was generated from the following file:
Elin/ObjInfo.cs