Elin Decompiled Documentation: UndoManager Class Reference
UndoManager Class Reference
Classes
class Item
Public Member Functions
void Validate ()
void NewItem ()
void Add (Task t)
string GetText ()
void WriteNote (UINote n)
void Perform ()
Public Attributes
List< UndoManager.Item > items = new List<UndoManager.Item>()
Properties
UndoManager.Item lastItem [get]
Detailed Description
Definition at line 4 of file UndoManager.cs.
Member Function Documentation
Add()
void UndoManager.Add (Task t) inline
Definition at line 34 of file UndoManager.cs.
    {
        this.lastItem.list.Add(t);
    }
References Add(), and lastItem.
Referenced by Add(), and AM_Designation< T >.OnProcessTiles().
GetText()
string UndoManager.GetText () inline
Definition at line 39 of file UndoManager.cs.
    {
        string text = "tUndo".lang() + Environment.NewLine;
        if (this.items.Count == 0)
        {
            text += "tUndoNone".lang();
        }
        else
        {
            text += "tUndoNote".lang(this.lastItem.Count().ToString() ?? "", this.lastItem.name ?? "", null, null, null);
        }
        return text;
    }
References items, lastItem, and text.
NewItem()
void UndoManager.NewItem () inline
Definition at line 25 of file UndoManager.cs.
    {
        this.items.Add(new UndoManager.Item());
        if (this.items.Count > 10)
        {
            this.items.RemoveAt(0);
        }
    }
References items.
Referenced by AM_Designation< T >.OnBeforeProcessTiles().
Perform()
void UndoManager.Perform () inline
Definition at line 70 of file UndoManager.cs.
    {
        this.Validate();
        if (this.items.Count == 0)
        {
            SE.Beep();
            return;
        }
        foreach (Task task in this.lastItem.list)
        {
            task.Destroy();
        }
        this.items.Remove(this.lastItem);
        SE.Play("trash");
    }
References Task.Destroy(), items, lastItem, and Validate().
Referenced by BuildMenu.OnActivate().
Validate()
void UndoManager.Validate () inline
Definition at line 14 of file UndoManager.cs.
    {
        for (int i = this.items.Count - 1; i >= 0; i--)
        {
            if (this.items[i].Count() == 0)
            {
                this.items.RemoveAt(i);
            }
        }
    }
References items.
Referenced by Perform(), and WriteNote().
WriteNote()
void UndoManager.WriteNote (UINote n) inline
Definition at line 53 of file UndoManager.cs.
    {
        this.Validate();
        n.Clear();
        n.Space(10, 1);
        n.AddText("NoteText_topic", "tUndo".lang(), FontColor.DontChange);
        if (this.items.Count == 0)
        {
            n.AddText("tUndoNone".lang(), FontColor.DontChange);
        }
        else
        {
            n.AddText("tUndoNote".lang(this.lastItem.Count().ToString() ?? "", this.lastItem.name ?? "", null, null, null), FontColor.DontChange);
        }
        n.Build();
    }
References items, lastItem, and Validate().
Referenced by BuildMenu.OnActivate().
Member Data Documentation
items
List<UndoManager.Item> UndoManager.items = new List<UndoManager.Item>()
Definition at line 86 of file UndoManager.cs.
Referenced by GetText(), NewItem(), Perform(), Validate(), and WriteNote().
Property Documentation
lastItem
UndoManager.Item UndoManager.lastItem get
Definition at line 6 of file UndoManager.cs.
    {
        get
        {
            return this.items.LastItem<UndoManager.Item>();
        }
    }
Referenced by Add(), GetText(), Perform(), and WriteNote().
The documentation for this class was generated from the following file:
Elin/UndoManager.cs