Elin Decompiled Documentation: ContentPolicy Class Reference
ContentPolicy Class Reference
Public Member Functions
override void OnSwitchContent (int idTab)
void RefreshPolicy ()
void RefreshPolicyList (UIList list, string cat, string plan)
void RefreshPolicyIcons ()
Public Member Functions inherited from UIContent
virtual void OnSwitchContent (int idTab)
virtual void OnInstantiate ()
Public Member Functions inherited from UINote
void Clear ()
void Build ()
void Space (int sizeY=0, int sizeX=1)
UINote AddNote (string id)
UIItem AddHeader (string text, Sprite sprite=null)
UIItem AddHeaderCard (string text, Sprite sprite=null)
UIItem AddHeaderTopic (string text, Sprite sprite=null)
UIItem AddHeader (string id, string text, Sprite sprite=null)
UIItem AddText (string text, FontColor color=FontColor.DontChange)
UIItem AddText (string id, string text, FontColor color=FontColor.DontChange)
UIItem AddText (string id, string text, Color color)
UIItem AddItem (string id)
UIItem AddTopic (string id, string text, string value=null)
UIItem AddTopic (string text, string value=null)
void AddImage (Sprite sprite)
void AddImage (string idFile)
UIButton AddButton (string text, Action onClick)
UIButton AddButtonLink (string text, string url)
UIDropdown AddDropdown (string id="DropdownDefault")
UIButton AddToggle (string idLang="", bool isOn=false, Action< bool > action=null)
Transform AddPrefab (string path)
T AddExtra< T > (string path)
Public Attributes
UIList listPolicyLaw
UIList listPolicyEconomy
UIList listPolicyLife
UIList listUtility
Material matGrayscale
Public Attributes inherited from UINote
RectTransform target
UINoteProfile prof
SkinType skinType
string idDefaultText
LayoutGroup layout
RectTransform cur
bool extraRebuild
Detailed Description
Definition at line 4 of file ContentPolicy.cs.
Member Function Documentation
OnSwitchContent()
override void ContentPolicy.OnSwitchContent (int idTab) inline virtual
Reimplemented from UIContent.
Definition at line 16 of file ContentPolicy.cs.
    {
        EClass.Branch.policies.Validate();
        RefreshPolicy();
    }
References EClass.Branch, FactionBranch.policies, RefreshPolicy(), and PolicyManager.Validate().
RefreshPolicy()
void ContentPolicy.RefreshPolicy () inline
Definition at line 22 of file ContentPolicy.cs.
    {
        RefreshPolicyList(listPolicyLaw, "law", "department_law");
        RefreshPolicyList(listPolicyEconomy, "economy", "department_economy");
        RefreshPolicyList(listPolicyLife, "life", "department_life");
        RefreshPolicyList(listUtility, "utility", "department_utility");
        listUtility.SetActive(EClass.Branch.lv >= 2 || EClass.debug.enable);
        RefreshPolicyIcons();
        GetComponentInParent<Layer>().RebuildLayout(recursive: true);
        this.RebuildLayout(recursive: true);
    }
References EClass.Branch, EClass.debug, CoreDebug.enable, listPolicyEconomy, listPolicyLaw, listPolicyLife, listUtility, FactionBranch.lv, RefreshPolicyIcons(), and RefreshPolicyList().
Referenced by OnSwitchContent().
RefreshPolicyIcons()
void ContentPolicy.RefreshPolicyIcons () inline
Definition at line 124 of file ContentPolicy.cs.
    {
        int num = EClass.Branch.policies.CurrentAP();
        UIList[] array = new UIList[4] { listPolicyLaw, listPolicyLife, listPolicyEconomy, listUtility };
        for (int i = 0; i < array.Length; i++)
        {
            UIButton[] componentsInChildren = array[i].GetComponentsInChildren<UIButton>();
            foreach (UIButton obj in componentsInChildren)
            {
                Policy policy = obj.refObj as Policy;
                obj.icon.material = (policy.active ? null : matGrayscale);
                obj.imageCheck.SetActive(policy.active);
                obj.subText.SetText(policy.Cost.ToString() ?? "", (num + policy.Cost <= EClass.Branch.MaxAP || policy.active) ? FontColor.Good : FontColor.Bad);
            }
        }
    }
References Policy.active, EClass.Branch, Policy.Cost, PolicyManager.CurrentAP(), UIButton.imageCheck, FactionBranch.policies, UIText.SetText(), and UIButton.subText.
Referenced by RefreshPolicy(), and RefreshPolicyList().
RefreshPolicyList()
void ContentPolicy.RefreshPolicyList (UIList list, string cat, string plan) inline
Definition at line 34 of file ContentPolicy.cs.
    {
        list.callbacks = new UIList.Callback<Policy, UIButton>
        {
            onClick = delegate
            {
            },
            onInstantiate = delegate(Policy a, UIButton b)
            {
                b.mainText.SetText(a.Name);
                b.onClick.AddListener(delegate
                {
                    if (!a.active)
                    {
                        if ((a.Cost > 0 && EClass.Branch.policies.CurrentAP() + a.Cost > EClass.Branch.MaxAP) || !CanActivate(a))
{
                            SE.Beep();
                            return;
                        }
                        if (a.id == 2514 && EClass.pc.faction.CountTaxFreeLand() >= 3)
{
                            SE.Beep();
                            return;
                        }
                    }
                    SE.ClickOk();
                    a.active = !a.active;
                    if (a.id == 2705)
                    {
                        EClass.pc.faction.SetGlobalPolicyActive(2705, a.active);
                    }
                    if (a.id == 2708)
                    {
                        EClass.pc.faction.SetGlobalPolicyActive(2708, a.active);
                    }
                    if (a.id == 2710)
                    {
                        EClass.pc.faction.SetGlobalPolicyActive(2710, a.active);
                    }
                    if (a.id == 2711)
                    {
                        EClass.pc.faction.SetGlobalPolicyActive(2711, a.active);
                    }
                    if (a.id == 2712)
                    {
                        EClass.pc.faction.SetGlobalPolicyActive(2712, a.active);
                    }
                    EClass.Branch.policies.RefreshEffects();
                    RefreshPolicyIcons();
                });
                b.refObj = a;
                b.tooltip.onShowTooltip = delegate(UITooltip tp)
                {
                    a.WriteNote(tp.note);
                };
            },
            onList = delegate
            {
                foreach (Policy item in EClass.Branch.policies.list.Where((Policy p) => p.source.categorySub == cat))
                {
                    list.Add(item);
                }
            },
            onSort = (Policy a, UIList.SortMode m) => a.GetSortVal(m),
            onRefresh = null
        };
        list.List();
        list.GetComponentInChildren<CanvasGroup>().alpha = ((list.items.Count > 0) ? 0.9f : 0.4f);
        static bool CanActivate(Policy p)
        {
            if (p.id == 2515 && EClass.Branch.policies.IsActive(2516))
            {
                return false;
            }
            if (p.id == 2516 && EClass.Branch.policies.IsActive(2515))
            {
                return false;
            }
            if (p.id == 2814 && EClass.Branch.policies.IsActive(2823))
            {
                return false;
            }
            if (p.id == 2823 && EClass.Branch.policies.IsActive(2814))
            {
                return false;
            }
            return true;
        }
    }
References Policy.active, UIList.Add(), EClass.Branch, Faction.CountTaxFreeLand(), Chara.faction, Policy.GetSortVal(), Policy.id, if(), item, PolicyManager.list, UIButton.mainText, Policy.Name, UITooltip.note, EClass.pc, FactionBranch.policies, PolicyManager.RefreshEffects(), RefreshPolicyIcons(), UIText.SetText(), Policy.source, and Policy.WriteNote().
Referenced by RefreshPolicy().
Member Data Documentation
listPolicyEconomy
UIList ContentPolicy.listPolicyEconomy
Definition at line 8 of file ContentPolicy.cs.
Referenced by RefreshPolicy().
listPolicyLaw
UIList ContentPolicy.listPolicyLaw
Definition at line 6 of file ContentPolicy.cs.
Referenced by RefreshPolicy().
listPolicyLife
UIList ContentPolicy.listPolicyLife
Definition at line 10 of file ContentPolicy.cs.
Referenced by RefreshPolicy().
listUtility
UIList ContentPolicy.listUtility
Definition at line 12 of file ContentPolicy.cs.
Referenced by RefreshPolicy().
matGrayscale
Material ContentPolicy.matGrayscale
Definition at line 14 of file ContentPolicy.cs.
The documentation for this class was generated from the following file:
Elin/ContentPolicy.cs