Elin Decompiled Documentation: ActPlan.List Class Reference
ActPlan.List Class Reference
Public Member Functions
void Add (Act a, string s="")
Detailed Description
Definition at line 9 of file ActPlan.cs.
Member Function Documentation
Add()
void ActPlan.List.Add (Act a, string s = "") inline
Definition at line 11 of file ActPlan.cs.
        {
            Add(new Item
            {
                act = a
            });
        }
References ActPlan.List.Add().
Referenced by ThingContainer._List(), ThingContainer._ListCurrency(), ActPlan._Update(), Zone.Activate(), ActPlan.List.Add(), Props.Add(), ThingStack.Add(), Cell.AddCard(), WorkSummary.AddThing(), Card.AddThing(), RecipeCard.Build(), Map.FindThing(), AI_Haul.GetThingToClean(), TaskCraft.IsIngredientsValid(), QuestDeliver.ListDestThing(), Props.ListThingStacksInCategory(), Map.OnCardAddedToZone(), FactionBranch.ReceivePackages(), ThingContainer.RefreshGrid(), AI_HaulResource.Run(), AI_UseCrafter.Run(), RecipeUpdater.RunDisassemble(), World.SendPackage(), LayerResource.ShowThings(), ActPlan.TrySetAct(), and TraitSeed.TrySprout().
The documentation for this class was generated from the following file:
Elin/ActPlan.cs