Elin Decompiled Documentation: InteractionMenu Class Reference
InteractionMenu Class Reference
Public Member Functions
void Show ()
UIButton Add ()
void Clear ()
Public Attributes
LayoutGroup layout
UIButton mold
Vector3 offset
Vector3 modPos
SoundData soundPop
Private Member Functions
void Awake ()
Additional Inherited Members
Static Public Member Functions inherited from EMono
static int rnd (int a)
Static Public Attributes inherited from EMono
static Core core
Properties inherited from EMono
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SoundManager Sound [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static CoreDebug debug [get]
Detailed Description
Definition at line 4 of file InteractionMenu.cs.
Member Function Documentation
Add()
UIButton InteractionMenu.Add () inline
Definition at line 27 of file InteractionMenu.cs.
    {
        return Util.Instantiate(mold, layout);
    }
References layout, mold, and Util.
Referenced by LayerInteraction.Show(), and LayerInteraction.ShowPage().
Awake()
void InteractionMenu.Awake () inline private
Definition at line 16 of file InteractionMenu.cs.
    {
        mold = layout.CreateMold<UIButton>();
    }
References layout, and mold.
Clear()
void InteractionMenu.Clear () inline
Definition at line 32 of file InteractionMenu.cs.
    {
        layout.DestroyChildren();
    }
References layout.
Referenced by LayerInteraction.ShowPage().
Show()
void InteractionMenu.Show () inline
Definition at line 21 of file InteractionMenu.cs.
    {
        layout.RebuildLayout(recursive: true);
        soundPop.Play();
    }
References layout, and soundPop.
Referenced by LayerInteraction.Show(), and LayerInteraction.ShowPage().
Member Data Documentation
layout
LayoutGroup InteractionMenu.layout
Definition at line 6 of file InteractionMenu.cs.
Referenced by Add(), Awake(), Clear(), and Show().
modPos
Vector3 InteractionMenu.modPos
Definition at line 12 of file InteractionMenu.cs.
mold
UIButton InteractionMenu.mold
Definition at line 8 of file InteractionMenu.cs.
Referenced by Add(), and Awake().
offset
Vector3 InteractionMenu.offset
Definition at line 10 of file InteractionMenu.cs.
soundPop
SoundData InteractionMenu.soundPop
Definition at line 14 of file InteractionMenu.cs.
Referenced by Show().
The documentation for this class was generated from the following file:
Elin/InteractionMenu.cs