Elin Decompiled Documentation: Msg Class Reference
Msg Class Reference
Static Public Member Functions
static void SetColor ()
static void SetColor (Color color)
static void SetColor (string id)
static string GetRawText (string idLang, string ref1, string ref2=null, string ref3=null, string ref4=null)
static string GetRawText (string idLang, Card c1, Card c2, string ref1=null, string ref2=null)
static string GetRawText (string idLang, Card c1, string ref1=null, string ref2=null, string ref3=null)
static string Say (string idLang, string ref1, string ref2=null, string ref3=null, string ref4=null)
static string Say (string idLang, Card c1, Card c2, string ref1=null, string ref2=null)
static string Say (string idLang, Card c1, string ref1=null, string ref2=null, string ref3=null)
static string Say (string idLang, Card c1, int i, string ref1=null)
static string Say (string idLang, int i, string ref1=null, string ref2=null)
static string Say (string idLang)
static string SayNothingHappen ()
static string SayCannotUseHere ()
static void SayGod (string s, Card owner=null)
static string SayRaw (string text)
static void Append (Sprite sprite)
static void AquireItem (string itemName)
static void Nerun (string lang, string idPortrait="UN_nerun")
static void SayHomeMember (string lang)
static void SayPic (Card c, string lang)
static void SayPic (string idPortrait, string lang, string _idPop=null)
static PopItem Talk (Card c, string id)
static PopItem TalkHomeMemeber (string id)
static PopItem TalkMaid (string id)
static string GetGameText (string idLang)
static string GetName (Card c)
static bool IsThirdPerson (Card c)
static bool IsThirdPerson (string n)
static bool IsThirdPerson (int i)
static void NewLine ()
static unsafe void ToUpperFirst (string str)
Static Public Member Functions inherited from EClass
static int rndSeed (int a, int seed)
static int rnd (int a)
static int curve (int a, int start, int step, int rate=75)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Static Public Attributes
static ThirstPersonInfo thirdPerson1 = new ThirstPersonInfo()
static ThirstPersonInfo thirdPerson2 = new ThirstPersonInfo()
static Color currentColor = colors.Default
static bool alwaysVisible
static bool ignoreAll
Static Public Attributes inherited from EClass
static Core core
Properties
static WidgetMainText mainText [get]
static WidgetFeed feed [get]
static MsgColors colors [get]
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Detailed Description
Definition at line 4 of file Msg.cs.
Member Function Documentation
Append()
static void Msg.Append (Sprite sprite) inline static
Definition at line 135 of file Msg.cs.
    {
        mainText.Append(sprite);
    }
References WidgetMainText.Append(), and mainText.
AquireItem()
static void Msg.AquireItem (string itemName) inline static
Definition at line 140 of file Msg.cs.
    {
        Say("getItem", itemName ?? "");
    }
References Say().
Referenced by Hoard.Add().
GetGameText()
static string Msg.GetGameText (string idLang) inline static
Definition at line 252 of file Msg.cs.
    {
        LangGame.Row row = EClass.core.sources.langGame.map.TryGetValue(idLang);
        if (row == null)
        {
            return idLang.lang();
        }
        if (!row.effect.IsEmpty() && row.effect == "destroy")
        {
            mainText.Append(mainText.spriteDestroy);
        }
        if (!row.color.IsEmpty())
        {
            SetColor(colors.colors[row.color]);
        }
        if (!row.sound.IsEmpty())
        {
            EClass.Sound.Play(row.sound);
        }
        return row.GetText("text").Split(Environment.NewLine.ToCharArray()).RandomItem();
    }
References WidgetMainText.Append(), LangGame.Row.color, colors, MsgColors.colors, EClass.core, LangGame.Row.effect, SourceData< T, T2 >.BaseRow.GetText(), SourceManager.langGame, mainText, SetColor(), EClass.Sound, LangGame.Row.sound, Core.sources, and WidgetMainText.spriteDestroy.
Referenced by GetRawText(), and Say().
GetName()
static string Msg.GetName (Card c) inline static
Definition at line 274 of file Msg.cs.
    {
        if (c == null)
        {
            return "null";
        }
        if (c.IsPC)
        {
            return "you".lang();
        }
        if (!alwaysVisible && (EClass.pc.isBlind || !EClass.pc.CanSee(c)) && c.parent == EClass._zone)
        {
            return (c.isChara ? "someone" : "something").lang();
        }
        return c.Name;
    }
References EClass._zone, alwaysVisible, Chara.CanSee(), Chara.isBlind, Card.isChara, Card.IsPC, Card.Name, Card.parent, and EClass.pc.
Referenced by GetRawText(), Say(), and ActEffect.Wish().
GetRawText() [1/3]
static string Msg.GetRawText (string idLang, Card c1, Card c2, string ref1 = null, string ref2 = null) inline static
Definition at line 44 of file Msg.cs.
    {
        thirdPerson1.Set(c1);
        thirdPerson2.Set(c2);
        return GameLang.Parse(GetGameText(idLang), IsThirdPerson(c1), GetName(c1), GetName(c2), ref1, ref2);
    }
References GetGameText(), GetName(), IsThirdPerson(), GameLang.Parse(), ThirstPersonInfo.Set(), thirdPerson1, and thirdPerson2.
GetRawText() [2/3]
static string Msg.GetRawText (string idLang, Card c1, string ref1 = null, string ref2 = null, string ref3 = null) inline static
Definition at line 51 of file Msg.cs.
    {
        thirdPerson1.Set(c1);
        thirdPerson2.Set(ref1);
        return GameLang.Parse(GetGameText(idLang), IsThirdPerson(c1), GetName(c1), ref1, ref2, ref3);
    }
References GetGameText(), GetName(), IsThirdPerson(), GameLang.Parse(), ThirstPersonInfo.Set(), thirdPerson1, and thirdPerson2.
GetRawText() [3/3]
static string Msg.GetRawText (string idLang, string ref1, string ref2 = null, string ref3 = null, string ref4 = null) inline static
Definition at line 37 of file Msg.cs.
    {
        thirdPerson1.Set(ref1);
        thirdPerson2.Set(ref2);
        return GameLang.Parse(GetGameText(idLang), IsThirdPerson(ref1), ref1, ref2, ref3, ref4);
    }
References GetGameText(), IsThirdPerson(), GameLang.Parse(), ThirstPersonInfo.Set(), thirdPerson1, and thirdPerson2.
Referenced by FactionBranch.Log().
IsThirdPerson() [1/3]
static bool Msg.IsThirdPerson (Card c) inline static
Definition at line 291 of file Msg.cs.
    {
        if (c == null)
        {
            return false;
        }
        if (c.IsPC || c.Num > 1)
        {
            return false;
        }
        return true;
    }
References Card.IsPC, and Card.Num.
Referenced by GetRawText(), IsThirdPerson(), Say(), and ActEffect.Wish().
IsThirdPerson() [2/3]
static bool Msg.IsThirdPerson (int i) inline static
Definition at line 313 of file Msg.cs.
    {
        return i <= 1;
    }
IsThirdPerson() [3/3]
static bool Msg.IsThirdPerson (string n) inline static
Definition at line 304 of file Msg.cs.
    {
        if (!int.TryParse(n, out var result))
        {
            return false;
        }
        return IsThirdPerson(result);
    }
References IsThirdPerson().
Nerun()
static void Msg.Nerun (string lang, string idPortrait = "UN_nerun") inline static
Definition at line 145 of file Msg.cs.
    {
        string text = GameLang.Convert(lang.lang());
        if ((bool)feed)
        {
            feed.Nerun(text, idPortrait);
        }
        else if ((bool)mainText)
        {
            mainText.Append(text.Bracket(1), colors.Talk);
        }
    }
References WidgetMainText.Append(), colors, GameLang.Convert(), feed, mainText, WidgetFeed.Nerun(), and MsgColors.Talk.
Referenced by LayerEditPlaylist.Activate(), LayerHoard.OnClickNextMode(), WidgetFeed.OnSetContextMenu(), and LayerHoard.Update().
NewLine()
static void Msg.NewLine () inline static
Definition at line 318 of file Msg.cs.
    {
        if ((bool)mainText)
        {
            mainText.NewLine();
        }
    }
References mainText, and WidgetMainText.NewLine().
Referenced by GameDate.AdvanceMin().
Say() [1/6]
static string Msg.Say (string idLang) inline static
Definition at line 91 of file Msg.cs.
    {
        return SayRaw(GetGameText(idLang));
    }
References GetGameText(), and SayRaw().
Say() [2/6]
static string Msg.Say (string idLang, Card c1, Card c2, string ref1 = null, string ref2 = null) inline static
Definition at line 65 of file Msg.cs.
    {
        thirdPerson1.Set(c1);
        thirdPerson2.Set(c2);
        return SayRaw(GameLang.Parse(GetGameText(idLang), IsThirdPerson(c1), GetName(c1), GetName(c2), ref1, ref2));
    }
References GetGameText(), GetName(), IsThirdPerson(), GameLang.Parse(), SayRaw(), ThirstPersonInfo.Set(), thirdPerson1, and thirdPerson2.
Say() [3/6]
static string Msg.Say (string idLang, Card c1, int i, string ref1 = null) inline static
Definition at line 79 of file Msg.cs.
    {
        thirdPerson1.Set(c1);
        thirdPerson2.Set(ref1);
        return SayRaw(GameLang.Parse(GetGameText(idLang), IsThirdPerson(i), GetName(c1), i.ToString() ?? "", ref1));
    }
References GetGameText(), GetName(), IsThirdPerson(), GameLang.Parse(), SayRaw(), ThirstPersonInfo.Set(), thirdPerson1, and thirdPerson2.
Say() [4/6]
static string Msg.Say (string idLang, Card c1, string ref1 = null, string ref2 = null, string ref3 = null) inline static
Definition at line 72 of file Msg.cs.
    {
        thirdPerson1.Set(c1);
        thirdPerson2.Set(ref1);
        return SayRaw(GameLang.Parse(GetGameText(idLang), IsThirdPerson(c1), GetName(c1), ref1, ref2, ref3));
    }
References GetGameText(), GetName(), IsThirdPerson(), GameLang.Parse(), SayRaw(), ThirstPersonInfo.Set(), thirdPerson1, and thirdPerson2.
Say() [5/6]
static string Msg.Say (string idLang, int i, string ref1 = null, string ref2 = null) inline static
Definition at line 86 of file Msg.cs.
    {
        return SayRaw(GameLang.Parse(GetGameText(idLang), IsThirdPerson(i), ref1, ref2));
    }
References GetGameText(), IsThirdPerson(), GameLang.Parse(), and SayRaw().
Say() [6/6]
static string Msg.Say (string idLang, string ref1, string ref2 = null, string ref3 = null, string ref4 = null) inline static
Definition at line 58 of file Msg.cs.
    {
        thirdPerson1.Set(ref1);
        thirdPerson2.Set(ref2);
        return SayRaw(GameLang.Parse(GetGameText(idLang), IsThirdPerson(ref1), ref1, ref2, ref3, ref4));
    }
References GetGameText(), IsThirdPerson(), GameLang.Parse(), SayRaw(), ThirstPersonInfo.Set(), thirdPerson1, and thirdPerson2.
Referenced by Chara._Move(), TraitAltar._OnOffer(), InvOwnerChaosOffering._OnProcess(), InvOwnerDeliver._OnProcess(), InvOwnerGene._OnProcess(), InvOwnerMod._OnProcess(), InvOwnerRecycle._OnProcess(), InvOwnerRefuel._OnProcess(), AM_Adv._OnUpdateInput(), TraitGodStatue._OnUse(), Zone.Activate(), MiniGame.Activate(), MeetingManager.Add(), Faction.AddContribution(), Player.AddExpInfluence(), Player.AddExpKnowledge(), Party.AddMemeber(), Zone.AddRandomVisitor(), Player.Flags.AddStory(), Card.AddThing(), LayerSleep.Advance(), GameDate.AdvanceDay(), GameDate.AdvanceHour(), Chara.ApplyDeathPenalty(), AquireItem(), FactionBranch.BanishMember(), TraitDrink.BlendLove(), TraitDrink.BlendPoison(), AI_Shopping.Buy(), DramaOutcome.check_sketch(), ZoneEventSubdue.CheckClear(), Zone.ClaimZone(), Chara.ClearInventory(), ContentCodex.Collect(), RecipeManager.ComeUpWithRandomRecipe(), RecipeManager.ComeUpWithRecipe(), ItemGachaResult.Confirm(), TraitCrafter.Craft(), Recipe.Craft(), RecipeCard.Craft(), LayerDragGrid.CreateChaosOffering(), LayerDragGrid.CreateDeliver(), LayerDragGrid.CreateGacha(), LayerDragGrid.CreateOffering(), LayerDragGrid.CreateRecycle(), Card.DamageHP(), Zone.Deactivate(), QuestDeliver.Deliver(), Card.Die(), Chara.Die(), ActionMode.DoFunc(), Player.DreamSpell(), Recipe.DropIngredients(), Player.DropReward(), Chara.DropThing(), TraitDye.Dye(), Expedition.End(), Player.EnterLocalZone(), CharaBody.Equip(), Player.EquipTool(), Zone.Export(), LayerUploader.ExportMap(), Chara.FallFromZone(), AI_Fuck.Finish(), FactionBranch.GetDailyIncome(), Faction.GetFactionSalary(), AI_Shear.GetFur(), Faction.GetRankIncome(), Faction.GetResidentTax(), Chara.GetRevived(), MiniGame.GetSlotReward(), DramaOutcome.give_sketch_special(), Chara.GiveGift(), QuestDebt.GiveReward(), DramaOutcome.guild_join(), ZoneEventDefenseGame.Horn_Next(), ZoneEventDefenseGame.Horn_Retreat(), Thing.Identify(), TraitFoodEggFertilized.Incubate(), Scene.Init(), CharaBody.IsEquippable(), InvOwnerEquip.IsFailByCurse(), ActWater.IsWaterCanValid(), TaskWater.IsWaterCanValid(), Religion.JoinFaith(), Religion.LeaveFaith(), Card.LevelUp(), TraitMoongate.LoadMap(), TraitSeed.MakeSeed(), Map.MineObj(), Zone.ModDevelopment(), FactionBranch.ModExp(), Player.ModFame(), Zone.ModInfluence(), Player.ModKarma(), Player.ModKeyItem(), Player.MoveZone(), Chara.MoveZone(), ZoneEventDefenseGame.NextWave(), AM_Paint.OnActivate(), TraitHitchingPost.OnActivateTrap(), TraitTrap.OnActivateTrap(), Faction.OnAdvanceMonth(), Player.OnAdvanceRealHour(), TraitDrink.OnBlend(), TraitWell.OnBlend(), TaskDump.OnCancelOrSuccess(), BaseListPeople.OnClick(), ContentCodex.OnClickAddCards(), LayerCraft.OnClickCraft(), TaskHarvest.OnCreateProgress(), InvOwner.OnDrag(), TextureManager.OnDropFile(), QuestRandom.OnDropReward(), TraitFortuneCookie.OnEat(), QuestDeliver.OnEnterZone(), ZoneEventSiege.OnFirstTick(), InvOwnerDraglet.OnInit(), ZoneEventSiege.OnKill(), ElementContainerCard.OnLearn(), ElementContainerZone.OnLearn(), ZoneEventHarvest.OnLeaveZone(), ElementContainerCard.OnLevelDown(), ElementContainerZone.OnLevelUp(), TraitAltar.OnOffer(), InvOwnerDraglet.OnProcess(), AI_Fish.ProgressFish.OnProgressComplete(), AI_Sleep.OnProgressComplete(), TaskCraft.OnProgressComplete(), TaskDig.OnProgressComplete(), ZoneEventHarvest.OnReachTimeLimit(), ZoneEventMusic.OnReachTimeLimit(), TraitBlueprint.OnRead(), TraitDeed.OnRead(), TraitDeedRelocate.OnRead(), TraitDiary.OnRead(), TraitIndulgence.OnRead(), TraitScrollMap.OnRead(), FactionBranch.OnSimulateDay(), RecipeManager.OnSleep(), QuestDeliver.OnStart(), TraitCurrencyMedal.OnStepped(), LayerQuestBoard.OnSwitchContent(), ElementContainerCard.OnTrain(), Scene.OnUpdate(), TraitAmmo.OnUse(), TraitCrafter.OnUse(), TraitDaggerGrave.OnUse(), TraitEditPlaylist.OnUse(), TraitEquipItem.OnUse(), TraitGiftNewYear.OnUse(), TraitPlamoBox.OnUse(), TraitPowerStatue.OnUse(), TraitScrollMapTreasure.OnUse(), TraitStairsLocked.OnUse(), TraitTape.OnUse(), ZoneEventDefenseGame.OnVisit(), TraitContainer.Open(), DramaManager.ParseLine(), InvOwnerDeliver.PayBill(), ActRanged.Perform(), ActRestrain.Perform(), ActRide.Perform(), HotItemActionSleep.Perform(), LayerGachaResult.PlayGacha(), DramaOutcome.poppy_found(), ActEffect.Proc(), InvOwner.Transaction.Process(), FoodEffect.ProcTrait(), FactionRelation.Promote(), Card.PurgeDuplicateArtifact(), FactionBranch.ReceivePackages(), FactionBranch.Recruit(), LayerTravel.Refresh(), Trait.Refuel(), Region.RenewRandomSites(), Chara.Revive(), ActRide.Ride(), AI_Craft_Snowman.Run(), AI_Fish.Run(), AI_Goto.Run(), AI_Idle.Run(), AI_Slaughter.Run(), AI_UseCrafter.Run(), GoalCombat.Run(), TaskCullLife.Run(), TaskDump.Run(), Game.Save(), MiniGame.Say(), Card.Say(), SayCannotUseHere(), SayGod(), SayNothingHappen(), TraitDetector.Search(), ActWait.SearchMedal(), ContentQuest.SelectQuest(), AI_Shopping.SellChara(), Weather.SetCondition(), GameDate.ShipGoods(), Quest.ShowCompleteText(), QuestDialog.ShowCompleteText(), Zone.Simulate(), ZoneEventQuest.SpawnBoss(), ButtonAbility.SpecialHoldAction(), Expedition.Start(), Religion.Talk(), Card.TalkRaw(), Chara.TalkTopic(), Player.TargetRanged(), ActThrow.Throw(), Chara.Tick(), ConSleep.Tick(), Chara.TickConditions(), UI.ToggleFeedback(), Player.TooHeavyToMove(), GoalAutoCombat.TryAbortCombat(), Chara.TryAssignBed(), Chara.TryDropBossLoot(), Zone.TryGenerateBigDaddy(), Recipe.TryGetFirstTimeBonus(), Chara.TryNullifyCurse(), Card.TryPay(), TaskDump.TryPerform(), ActRanged.TryReload(), TraitBed.TrySetAct(), TraitCoreZone.TrySetAct(), TraitNewZone.TrySetAct(), TraitSpecialLantern.TrySetAct(), TraitWaystone.TrySetAct(), TraitToolTorch.TrySetHeldAct(), Map.TryShatter(), InvOwnerCraft.TryStartCraft(), TraitTeleporter.TryTeleport(), ActionMode.UpdateInput(), CoreDebug.UpdateInput(), Quest.UpdateJournal(), QuestManager.UpdateJournal(), HomeResourceWorth.UpdateRank(), FactionBranch.Upgrade(), Chara.UseAbility(), and ActEffect.Wish().
SayCannotUseHere()
static string Msg.SayCannotUseHere () inline static
Definition at line 101 of file Msg.cs.
    {
        return Say("cannot_use_here");
    }
References Say().
Referenced by TraitCrafter.OnUse(), TraitGiftJure.OnUse(), TraitGiftNewYear.OnUse(), TraitGiftPack.OnUse(), TraitParcel.OnUse(), and TraitPlamoBox.OnUse().
SayGod()
static void Msg.SayGod (string s, Card owner = null) inline static
Definition at line 106 of file Msg.cs.
    {
        SetColor(colors.TalkGod);
        Say(s.Bracket());
        owner?.SayRaw("@1" + s);
    }
References colors, Say(), SetColor(), and MsgColors.TalkGod.
SayHomeMember()
static void Msg.SayHomeMember (string lang) inline static
Definition at line 158 of file Msg.cs.
    {
        string text = GameLang.Convert(lang.lang());
        if ((bool)feed)
        {
            feed.Nerun(text);
        }
        else if ((bool)mainText)
        {
            mainText.Append(text.Bracket(1), colors.Talk);
        }
    }
References WidgetMainText.Append(), colors, GameLang.Convert(), feed, mainText, WidgetFeed.Nerun(), and MsgColors.Talk.
SayNothingHappen()
static string Msg.SayNothingHappen () inline static
Definition at line 96 of file Msg.cs.
    {
        return Say("nothingHappens");
    }
References Say().
Referenced by InvOwnerChaosOffering._OnProcess(), TraitCrafter.Craft(), TraitNewZone.MoveZone(), TraitDrink.OnBlend(), TraitAltar.OnOffer(), TraitBlueprint.OnRead(), TraitRecipeCat.OnRead(), TraitBookResident.OnUse(), TraitGeneMachine.OnUse(), TraitMoongate.OnUse(), TraitMoongateEx.OnUse(), TraitPhone.OnUse(), TraitPolicyBoard.OnUse(), TraitPowerStatue.OnUse(), ActDreamBug.Perform(), ActEffect.Proc(), and Chara.UseAbility().
SayPic() [1/2]
static void Msg.SayPic (Card c, string lang) inline static
Definition at line 171 of file Msg.cs.
    {
        if (c != null)
        {
            string text = GameLang.Convert(lang.lang());
            if ((bool)feed)
            {
                feed.SayRaw(c, text);
            }
            else if ((bool)mainText)
            {
                mainText.Append(text.Bracket(1), colors.Talk);
            }
        }
    }
References WidgetMainText.Append(), colors, GameLang.Convert(), feed, mainText, WidgetFeed.SayRaw(), and MsgColors.Talk.
Referenced by LayerHoard.Update().
SayPic() [2/2]
static void Msg.SayPic (string idPortrait, string lang, string _idPop = null) inline static
Definition at line 187 of file Msg.cs.
    {
        string text = GameLang.Convert(lang.lang());
        if ((bool)feed)
        {
            feed.SayRaw(idPortrait, text, _idPop);
        }
        else if ((bool)mainText)
        {
            mainText.Append(text.Bracket(1), colors.Talk);
        }
    }
References WidgetMainText.Append(), colors, GameLang.Convert(), feed, mainText, WidgetFeed.SayRaw(), and MsgColors.Talk.
SayRaw()
static string Msg.SayRaw (string text) inline static
Definition at line 113 of file Msg.cs.
    {
        if (ignoreAll)
        {
            currentColor = colors.Default;
            return "";
        }
        ToUpperFirst(text);
        if ((bool)feed)
        {
            feed.System(text);
        }
        if ((bool)mainText)
        {
            mainText.Append(text, currentColor);
        }
        currentColor = colors.Default;
        alwaysVisible = false;
        EClass.game.log.Add(text);
        return text;
    }
References MsgLog.Add(), alwaysVisible, WidgetMainText.Append(), colors, currentColor, MsgColors.Default, feed, EClass.game, ignoreAll, Game.log, mainText, WidgetFeed.System(), and ToUpperFirst().
Referenced by PartialMap.ExportDialog(), Zone.ExportDialog(), Zone_User.OnActivate(), TraitFortuneCookie.OnEat(), Say(), and CoreDebug.UpdateAlways().
SetColor() [1/3]
static void Msg.SetColor () inline static
Definition at line 22 of file Msg.cs.
    {
        currentColor = colors.Default;
    }
References colors, currentColor, and MsgColors.Default.
Referenced by Chara._Move(), Hoard.Add(), TraitCrafter.Craft(), Card.DamageHP(), Chara.Die(), GetGameText(), FactionBranch.LogRaw(), Chara.MutateRandom(), Zone_User.OnActivate(), Stats.OnChangePhase(), TraitFortuneCookie.OnEat(), ElementContainerCard.OnLevelDown(), ElementContainerCard.OnLevelUp(), ElementContainerCard.OnModTempPotential(), Scene.OnUpdate(), AttackProcess.Perform(), BaseCondition.PhaseMsg(), FoodEffect.Proc(), AI_Craft_Snowman.Run(), AI_PlayMusic.Run(), Card.Say(), SayGod(), Chara.SetFeat(), Religion.Talk(), Card.Talk(), Card.TalkRaw(), and Chara.TalkTopic().
SetColor() [2/3]
static void Msg.SetColor (Color color) inline static
Definition at line 27 of file Msg.cs.
    {
        currentColor = color;
    }
References currentColor.
SetColor() [3/3]
static void Msg.SetColor (string id) inline static
Definition at line 32 of file Msg.cs.
    {
        currentColor = colors.colors[id];
    }
References colors, MsgColors.colors, and currentColor.
Talk()
static PopItem Msg.Talk (Card c, string id) inline static
Definition at line 200 of file Msg.cs.
    {
        PopItem result = null;
        if (c == null)
        {
            return null;
        }
        string text = GameLang.Convert(c.GetTalkText(id, stripPun: true));
        if ((bool)feed && c != null)
        {
            result = feed.SayRaw(c, text);
        }
        else if ((bool)mainText)
        {
            mainText.Append(text.Bracket(1), colors.Talk);
        }
        return result;
    }
References WidgetMainText.Append(), colors, GameLang.Convert(), feed, Card.GetTalkText(), mainText, WidgetFeed.SayRaw(), and MsgColors.Talk.
Referenced by TalkHomeMemeber(), and TalkMaid().
TalkHomeMemeber()
static PopItem Msg.TalkHomeMemeber (string id) inline static
Definition at line 219 of file Msg.cs.
    {
        Chara chara = null;
        if (EClass.Branch != null)
        {
            for (int i = 0; i < 99; i++)
            {
                chara = EClass.Branch.members.RandomItem();
                if (chara != EClass.pc)
                {
                    break;
                }
            }
        }
        if (chara == null)
        {
            chara = EClass.pc;
        }
        return Talk(chara, id);
    }
References EClass.Branch, FactionBranch.members, EClass.pc, and Talk().
Referenced by LayerGacha.OnAfterInit(), LayerHoard.OnAfterInit(), LayerGacha.PlayGacha(), ELayer.TalkHomeMemeber(), and TalkMaid().
TalkMaid()
static PopItem Msg.TalkMaid (string id) inline static
Definition at line 240 of file Msg.cs.
    {
        foreach (Chara chara in EClass._map.charas)
        {
            if (chara.uid == EClass.Branch?.uidMaid)
            {
                return Talk(chara, id);
            }
        }
        return TalkHomeMemeber(id);
    }
References EClass._map, EClass.Branch, Map.charas, Talk(), TalkHomeMemeber(), Card.uid, and FactionBranch.uidMaid.
Referenced by ELayer.TalkMaid().
ToUpperFirst()
static unsafe void Msg.ToUpperFirst (string str) inline static
Definition at line 326 of file Msg.cs.
    {
        if (str != null)
        {
            fixed (char* ptr = str)
            {
                *ptr = char.ToUpper(*ptr);
            }
        }
    }
Referenced by SayRaw().
Member Data Documentation
alwaysVisible
bool Msg.alwaysVisible static
Definition at line 12 of file Msg.cs.
Referenced by GetName(), SayRaw(), and ThirstPersonInfo.Set().
currentColor
Color Msg.currentColor = colors.Default static
Definition at line 10 of file Msg.cs.
Referenced by SayRaw(), SetColor(), and WidgetFeed.System().
ignoreAll
bool Msg.ignoreAll static
Definition at line 14 of file Msg.cs.
Referenced by SayRaw().
thirdPerson1
ThirstPersonInfo Msg.thirdPerson1 = new ThirstPersonInfo() static
Definition at line 6 of file Msg.cs.
Referenced by Chara.Die(), GetRawText(), GameLang.Parse(), Say(), and ActEffect.Wish().
thirdPerson2
ThirstPersonInfo Msg.thirdPerson2 = new ThirstPersonInfo() static
Definition at line 8 of file Msg.cs.
Referenced by GetRawText(), GameLang.Parse(), and Say().
Property Documentation
colors
MsgColors Msg.colors static get
Definition at line 20 of file Msg.cs.
Referenced by Chara._Move(), WidgetDate._Refresh(), WidgetMainText.Append(), GetGameText(), Chara.MutateRandom(), Nerun(), TraitFortuneCookie.OnEat(), ElementContainerCard.OnLevelDown(), ElementContainerCard.OnLevelUp(), Scene.OnUpdate(), AI_Craft_Snowman.Run(), AI_PlayMusic.Run(), SayGod(), SayHomeMember(), SayPic(), SayRaw(), SetColor(), Chara.SetFeat(), Talk(), Religion.Talk(), Card.TalkRaw(), and Chara.TalkTopic().
feed
WidgetFeed Msg.feed static get
Definition at line 18 of file Msg.cs.
Referenced by Nerun(), SayHomeMember(), SayPic(), SayRaw(), and Talk().
mainText
WidgetMainText Msg.mainText static get
Definition at line 16 of file Msg.cs.
Referenced by Append(), GetGameText(), Nerun(), NewLine(), SayHomeMember(), SayPic(), SayRaw(), and Talk().
The documentation for this class was generated from the following file:
Elin/Msg.cs