Elin Decompiled Documentation: ExpeditionManager Class Reference
ExpeditionManager Class Reference
Public Member Functions
void SetOwner (FactionBranch _branch)
void Add (Expedition ex)
void OnSimulateHour ()
Public Attributes
Dictionary< int, Expedition > dict = new Dictionary<int, Expedition>()
FactionBranch branch
Additional Inherited Members
Static Public Member Functions inherited from EClass
static int rndSeed (int a, int seed)
static int rnd (long a)
static int rnd (int a)
static int curve (int a, int start, int step, int rate=75)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Static Public Attributes inherited from EClass
static Core core
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Detailed Description
Definition at line 5 of file ExpeditionManager.cs.
Member Function Documentation
Add()
void ExpeditionManager.Add (Expedition ex) inline
Definition at line 21 of file ExpeditionManager.cs.
    {
        dict[ex.uidChara] = ex;
        ex.Start();
    }
References dict, Expedition.Start(), and Expedition.uidChara.
Referenced by ListPeopleExpedition.OnClick(), and Chara.TryWorkOutside().
OnSimulateHour()
void ExpeditionManager.OnSimulateHour () inline
Definition at line 27 of file ExpeditionManager.cs.
    {
        dict.Values.ToList().ForeachReverse(delegate(Expedition e)
        {
            e.OnAdvanceHour();
        });
    }
References dict, and Expedition.OnAdvanceHour().
SetOwner()
void ExpeditionManager.SetOwner (FactionBranch _branch) inline
Definition at line 12 of file ExpeditionManager.cs.
    {
        branch = _branch;
        foreach (Expedition value in dict.Values)
        {
            value.SetOwner(branch);
        }
    }
References branch, dict, and Expedition.SetOwner().
Referenced by FactionBranch.SetOwner().
Member Data Documentation
branch
FactionBranch ExpeditionManager.branch
Definition at line 10 of file ExpeditionManager.cs.
Referenced by SetOwner().
dict
Dictionary<int, Expedition> ExpeditionManager.dict = new Dictionary<int, Expedition>()
Definition at line 8 of file ExpeditionManager.cs.
Referenced by Add(), Expedition.End(), OnSimulateHour(), and SetOwner().
The documentation for this class was generated from the following file:
Elin/ExpeditionManager.cs