Elin Decompiled Documentation: UIInputText Class Reference
UIInputText Class Reference
Public Types
enum Type { Number , Name }
Public Member Functions
void OnValueChange (string s)
void SetMinMax (int _min, int _max)
void SetMin ()
void SetMax ()
void ModNum (int a)
void Validate ()
void Focus ()
Public Attributes
Type type
InputField field
bool number
bool showMax
int min
int max
Action< int > onValueChanged
Text textMax
UIButton[] buttons
Properties
int Num [get, set]
string Text [get, set]
Private Member Functions
void Awake ()
void Update ()
Private Attributes
float timer
Detailed Description
Definition at line 5 of file UIInputText.cs.
Member Enumeration Documentation
Type
enum UIInputText.Type
Enumerator
Number
Name
Definition at line 7 of file UIInputText.cs.
    {
        Number,
        Name
    }
Member Function Documentation
Awake()
void UIInputText.Awake () inline private
Definition at line 58 of file UIInputText.cs.
    {
        field.onValueChanged.AddListener(OnValueChange);
        buttons = GetComponentsInChildren<UIButton>();
        field.textComponent.font = SkinManager.Instance.fontSet.ui.source.font;
    }
References buttons, field, FontSource.font, SkinManager.fontSet, SkinManager.Instance, OnValueChange(), SkinManager.FontData.source, and SkinManager.FontSet.ui.
Focus()
void UIInputText.Focus () inline
Definition at line 128 of file UIInputText.cs.
    {
        field.ActivateInputField();
        field.Select();
    }
References field.
Referenced by Dialog.OnAfterInit().
ModNum()
void UIInputText.ModNum (int a) inline
Definition at line 98 of file UIInputText.cs.
    {
        int num = Num;
        Num += a;
        OnValueChange("");
        if (num != Num)
        {
            SE.Click();
        }
        else
        {
            SE.BeepSmall();
        }
    }
References Num, and OnValueChange().
OnValueChange()
void UIInputText.OnValueChange (string s) inline
Definition at line 65 of file UIInputText.cs.
    {
        Validate();
        if (onValueChanged != null)
        {
            onValueChanged(Num);
        }
    }
References Num, onValueChanged, and Validate().
Referenced by Awake(), ModNum(), SetMax(), and SetMin().
SetMax()
void UIInputText.SetMax () inline
Definition at line 91 of file UIInputText.cs.
    {
        Num = max;
        OnValueChange("");
        SE.Click();
    }
References max, Num, and OnValueChange().
SetMin()
void UIInputText.SetMin () inline
Definition at line 84 of file UIInputText.cs.
    {
        Num = min;
        OnValueChange("");
        SE.Click();
    }
References min, Num, and OnValueChange().
SetMinMax()
void UIInputText.SetMinMax (int _min, int _max) inline
Definition at line 74 of file UIInputText.cs.
    {
        min = _min;
        max = _max;
        if ((bool)textMax)
        {
            textMax.text = "/" + max;
        }
    }
References max, min, and textMax.
Referenced by LayerCraft.RefreshInputNum().
Update()
void UIInputText.Update () inline private
Definition at line 134 of file UIInputText.cs.
    {
        timer -= Time.deltaTime;
        if (!EInput.leftMouse.pressedLong || !(timer < 0f))
        {
            return;
        }
        timer = 0.1f;
        UIButton componentOf = InputModuleEX.GetComponentOf<UIButton>();
        UIButton[] array = buttons;
        foreach (UIButton uIButton in array)
        {
            if (uIButton == componentOf)
            {
                uIButton.onClick.Invoke();
            }
        }
    }
References buttons, EInput.leftMouse, ButtonState.pressedLong, and timer.
Validate()
void UIInputText.Validate () inline
Definition at line 113 of file UIInputText.cs.
    {
        if (type == Type.Number)
        {
            if (Num < min)
            {
                Num = min;
            }
            if (Num > max)
            {
                Num = max;
            }
        }
    }
References max, min, Num, and type.
Referenced by OnValueChange(), and LayerCraft.RefreshInputNum().
Member Data Documentation
buttons
UIButton [] UIInputText.buttons
Definition at line 29 of file UIInputText.cs.
Referenced by Awake(), and Update().
field
InputField UIInputText.field
Definition at line 15 of file UIInputText.cs.
Referenced by Awake(), Focus(), and Dialog.OnKill().
max
int UIInputText.max
Definition at line 23 of file UIInputText.cs.
Referenced by SetMax(), SetMinMax(), and Validate().
min
int UIInputText.min
Definition at line 21 of file UIInputText.cs.
Referenced by SetMin(), SetMinMax(), and Validate().
number
bool UIInputText.number
Definition at line 17 of file UIInputText.cs.
onValueChanged
Action<int> UIInputText.onValueChanged
Definition at line 25 of file UIInputText.cs.
Referenced by OnValueChange().
showMax
bool UIInputText.showMax
Definition at line 19 of file UIInputText.cs.
textMax
Text UIInputText.textMax
Definition at line 27 of file UIInputText.cs.
Referenced by SetMinMax().
timer
float UIInputText.timer private
Definition at line 31 of file UIInputText.cs.
Referenced by Update().
type
Type UIInputText.type
Definition at line 13 of file UIInputText.cs.
Referenced by Validate().
Property Documentation
Num
int UIInputText.Num get set
Definition at line 33 of file UIInputText.cs.
    {
        get
        {
            int.TryParse(field.text, out var result);
            return result;
        }
        set
        {
            field.SetTextWithoutNotify(value.ToString() ?? "");
        }
    }
Referenced by LayerCraft.GetReqIngredient(), ModNum(), LayerCraft.OnClickCraft(), OnValueChange(), LayerCraft.RefreshProduct(), SetMax(), SetMin(), and Validate().
Text
string UIInputText.Text get set
Definition at line 46 of file UIInputText.cs.
    {
        get
        {
            return field.text;
        }
        set
        {
            field.SetTextWithoutNotify(value);
        }
    }
Referenced by Dialog.InputName(), and Dialog.OnKill().
The documentation for this class was generated from the following file:
Elin/Plugins.UI/UIInputText.cs