Elin Decompiled Documentation: LayerEditPlaylist Class Reference
LayerEditPlaylist Class Reference
Classes
class ListBGM
Public Types
enum Mode { Playlist , LotBGM }
Public Member Functions
override void OnInit ()
void Activate (TraitJukeBox _box)
void Activate (TraitHouseBoard _board)
void Activate (Mode _mode=Mode.Playlist)
void Refresh ()
void TogglePL ()
override void OnKill ()
override void OnSwitchContent (Window window)
Public Member Functions inherited from ELayer
override void OnBeforeAddLayer ()
void InitInspector ()
sealed override void Init ()
override void OnAfterAddLayer ()
void TryShowHelp ()
void AddLayerToUI (string id)
void TryShowHint (string _langHint=null)
void TalkHomeMemeber (string id)
void TalkMaid (string id)
override void OnRightClick ()
Public Member Functions inherited from Layer
virtual string GetTextHeader (Window window)
virtual bool HeaderIsListOf (int id)
virtual void Init ()
virtual void OnInit ()
virtual void OnAfterInit ()
virtual void ApplySkin ()
void ShowScreenLock (string id)
void UpdateInput ()
virtual void OnUpdateInput ()
virtual void OnRightClick ()
virtual bool OnBack ()
virtual void OnChangeLayer ()
virtual void OnCreate ()
void _AddLayer (string id)
Layer AddLayer (string id)
T AddLayer< T > ()
T AddLayer< T > (string id)
T AddLayerDontCloseOthers< T > ()
Layer AddLayerDontCloseOthers (Layer l)
T GetOrAddLayer< T > ()
virtual void OnBeforeAddLayer ()
virtual void OnAfterAddLayer ()
Layer AddLayer (Layer l)
void ToggleLayer (string id)
T ToggleLayer< T > (string id=null)
void WaitAndClose ()
void OnClickClose ()
virtual void Close ()
void CloseLayers ()
void RemoveLayers (bool removeImportant=false)
bool RemoveLayer< T > ()
void RemoveLayer (Layer l)
virtual void OnKill ()
Layer SetOnKill (Action action)
void DisableClose ()
void Delay (float duration=0.05f)
Layer SetDelay (float d)
Layer GetLayer (string id)
T GetLayer< T > (bool fromTop=false)
Layer GetTopLayer ()
void SwitchContent (int idWindow, int i)
virtual void OnSwitchContent (Window window)
Layer SetTitles (string langList, string idHeaderRow=null)
bool IsBlockWidgetClick ()
bool IsHideHud ()
bool IsAllowGeneralInput ()
bool IsUseBlur ()
bool IsPointerOnLayer ()
void ApplySkin ()
Public Attributes
List< BGMData > itemsDay = new List<BGMData>()
List< BGMData > itemsNight = new List<BGMData>()
UIMultiList multi
bool day
bool keepPlaying
bool single
bool dayNight
Mode mode
TraitHouseBoard board
TraitJukeBox jukebox
Public Attributes inherited from Layer
Option option
UnityEvent onKill
Anime animeIn
Anime animeOut
bool closeOthers
bool defaultActionMode = true
Button screenLock
Layer parent
string idLayer
List< Layer > layers = new List<Layer>()
Vector2 lastParentPos
List< Window > windows = new List<Window>()
string langHint
Properties
Dictionary< int, BGMData > bgms [get]
Properties inherited from ELayer
static Core core [get]
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static FactionBranch Branch [get]
static Faction Home [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static CoreConfig config [get]
static GameSetting setting [get]
static ColorProfile Colors [get]
static SourceManager sources [get]
static World world [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
bool IsFloat [get]
virtual string IdHelp [get]
Properties inherited from Layer
Layer TopLayer [get]
string uid [get]
virtual RectTransform rectLayers [get]
virtual bool blockWidgetClick [get]
Additional Inherited Members
Static Public Member Functions inherited from ELayer
static int rnd (int a)
Static Public Member Functions inherited from Layer
static T Create< T > ()
static T Create< T > (string path)
static Layer Create (string path)
Static Public Attributes inherited from Layer
static int skipInput
static bool closeOnRightClick
static bool rightClicked
static bool cancelKeyDown
static bool ignoreSounds
static Transform blurStopInstance
static string[] searchPath = new string[3] { "Layer", "Layer/Dialog", "Layer/LayerHome" }
Protected Member Functions inherited from ELayer
sealed override void _Close ()
sealed override void Kill ()
Protected Member Functions inherited from Layer
virtual void Awake ()
virtual void _Close ()
virtual void Kill ()
Protected Attributes inherited from Layer
RectTransform _rect
bool isDestroyed
Detailed Description
Definition at line 4 of file LayerEditPlaylist.cs.
Member Enumeration Documentation
Mode
enum LayerEditPlaylist.Mode
Enumerator
Playlist
LotBGM
Definition at line 6 of file LayerEditPlaylist.cs.
    {
        Playlist,
        LotBGM
    }
Member Function Documentation
Activate() [1/3]
void LayerEditPlaylist.Activate (Mode _mode = Mode::Playlist) inline
Definition at line 130 of file LayerEditPlaylist.cs.
    {
        mode = _mode;
        Msg.Nerun("nPlaylist", "UN_nerun_smile3");
        if (mode == Mode.Playlist)
        {
            if (dayNight)
            {
                windows[0].AddBottomButton("togglePlaylist", TogglePL);
            }
            foreach (int item in ELayer._map._plDay)
            {
                if (bgms.ContainsKey(item))
                {
                    itemsDay.Add(bgms[item]);
                }
            }
            foreach (int item2 in ELayer._map._plNight)
            {
                if (bgms.ContainsKey(item2))
                {
                    itemsNight.Add(bgms[item2]);
                }
            }
        }
        else
        {
            windows[1].SetActive(enable: false);
            windows[0].SetPosition();
            multi.Double = false;
        }
        Refresh();
        foreach (ListOwner owner in multi.owners)
        {
            owner.OnSwitchContent();
        }
    }
References ELayer._map, Map._plDay, Map._plNight, bgms, dayNight, item, itemsDay, itemsNight, mode, multi, Msg.Nerun(), ListOwner< T1, T2 >.OnSwitchContent(), UIMultiList.owners, Refresh(), TogglePL(), and Layer.windows.
Activate() [2/3]
void LayerEditPlaylist.Activate (TraitHouseBoard _board) inline
Definition at line 123 of file LayerEditPlaylist.cs.
    {
        board = _board;
        single = true;
        Activate(Mode.LotBGM);
    }
References Activate(), board, and single.
Activate() [3/3]
void LayerEditPlaylist.Activate (TraitJukeBox _box) inline
Definition at line 116 of file LayerEditPlaylist.cs.
    {
        jukebox = _box;
        single = true;
        Activate(Mode.LotBGM);
    }
References Activate(), jukebox, and single.
Referenced by Activate().
OnInit()
override void LayerEditPlaylist.OnInit () inline virtual
Reimplemented from Layer.
Definition at line 112 of file LayerEditPlaylist.cs.
    {
    }
OnKill()
override void LayerEditPlaylist.OnKill () inline virtual
Reimplemented from Layer.
Definition at line 231 of file LayerEditPlaylist.cs.
    {
        if (mode == Mode.LotBGM)
        {
            ELayer.Sound.StopBGM();
            ELayer._zone.RefreshBGM();
            return;
        }
        ELayer._map._plDay.Clear();
        ELayer._map._plNight.Clear();
        foreach (BGMData item in itemsDay)
        {
            ELayer._map._plDay.Add(item.id);
        }
        foreach (BGMData item2 in itemsNight)
        {
            ELayer._map._plNight.Add(item2.id);
        }
        Object.DestroyImmediate(ELayer._map.plDay);
        ELayer._map.plDay = null;
        ELayer._zone.RefreshPlaylist();
        if (!keepPlaying)
        {
            ELayer.Sound.StopBGM();
            ELayer._zone.RefreshBGM();
        }
    }
References ELayer._map, Map._plDay, Map._plNight, ELayer._zone, item, itemsDay, itemsNight, keepPlaying, mode, Map.plDay, Zone.RefreshBGM(), Zone.RefreshPlaylist(), and ELayer.Sound.
OnSwitchContent()
override void LayerEditPlaylist.OnSwitchContent (Window window) inline virtual
Reimplemented from Layer.
Definition at line 259 of file LayerEditPlaylist.cs.
    {
        if (multi.owners.Count > 0)
        {
            multi.owners[window.windowIndex].OnSwitchContent();
        }
    }
References multi, UIMultiList.owners, and Window.windowIndex.
Refresh()
void LayerEditPlaylist.Refresh () inline
Definition at line 168 of file LayerEditPlaylist.cs.
    {
        List<BGMData> list = ((mode == Mode.LotBGM) ? new List<BGMData>() : (day ? itemsDay : itemsNight));
        List<BGMData> list2 = new List<BGMData>();
        foreach (BGMData value in bgms.Values)
        {
            if (!ELayer.debug.allBGM && !ELayer.player.knownBGMs.Contains(value.id))
            {
                continue;
            }
            if (mode == Mode.LotBGM)
            {
                list.Add(value);
                continue;
            }
            bool flag = value.id != 0;
            foreach (BGMData item in list)
            {
                if (item.id == value.id)
                {
                    flag = false;
                    break;
                }
            }
            if (flag)
            {
                list2.Add(value);
            }
        }
        multi.Clear();
        if (mode == Mode.LotBGM)
        {
            multi.AddOwner(0, new ListBGM
            {
                items = list,
                idTitle = "wBGMLot",
                single = true
            });
        }
        else
        {
            multi.AddOwner(0, new ListBGM
            {
                items = list,
                idTitle = "wPlaylist"
            });
            multi.AddOwner(1, new ListBGM
            {
                items = list2,
                idTitle = "wPlaylist2"
            });
        }
        multi.Build();
    }
References UIMultiList.AddOwner(), CoreDebug.allBGM, bgms, UIMultiList.Build(), UIMultiList.Clear(), day, ELayer.debug, item, itemsDay, itemsNight, Player.knownBGMs, mode, multi, ELayer.player, and single.
Referenced by Activate(), and TogglePL().
TogglePL()
void LayerEditPlaylist.TogglePL () inline
Definition at line 223 of file LayerEditPlaylist.cs.
    {
        day = !day;
        Refresh();
        multi.Refresh();
        SE.Click();
    }
References day, multi, Refresh(), and UIMultiList.Refresh().
Referenced by Activate().
Member Data Documentation
board
TraitHouseBoard LayerEditPlaylist.board
Definition at line 106 of file LayerEditPlaylist.cs.
Referenced by Activate(), and LayerEditPlaylist.ListBGM.List().
day
bool LayerEditPlaylist.day
Definition at line 96 of file LayerEditPlaylist.cs.
Referenced by Refresh(), and TogglePL().
dayNight
bool LayerEditPlaylist.dayNight
Definition at line 102 of file LayerEditPlaylist.cs.
Referenced by Activate().
itemsDay
List<BGMData> LayerEditPlaylist.itemsDay = new List<BGMData>()
Definition at line 90 of file LayerEditPlaylist.cs.
Referenced by Activate(), OnKill(), and Refresh().
itemsNight
List<BGMData> LayerEditPlaylist.itemsNight = new List<BGMData>()
Definition at line 92 of file LayerEditPlaylist.cs.
Referenced by Activate(), OnKill(), and Refresh().
jukebox
TraitJukeBox LayerEditPlaylist.jukebox
Definition at line 108 of file LayerEditPlaylist.cs.
Referenced by Activate(), and LayerEditPlaylist.ListBGM.List().
keepPlaying
bool LayerEditPlaylist.keepPlaying
Definition at line 98 of file LayerEditPlaylist.cs.
Referenced by OnKill().
mode
Mode LayerEditPlaylist.mode
Definition at line 104 of file LayerEditPlaylist.cs.
Referenced by Activate(), LayerEditPlaylist.ListBGM.List(), OnKill(), and Refresh().
multi
UIMultiList LayerEditPlaylist.multi
Definition at line 94 of file LayerEditPlaylist.cs.
Referenced by Activate(), OnSwitchContent(), Refresh(), and TogglePL().
single
bool LayerEditPlaylist.single
Definition at line 100 of file LayerEditPlaylist.cs.
Referenced by Activate(), and Refresh().
Property Documentation
bgms
Dictionary<int, BGMData> LayerEditPlaylist.bgms get
Definition at line 110 of file LayerEditPlaylist.cs.
Referenced by Activate(), and Refresh().
The documentation for this class was generated from the following file:
Elin/LayerEditPlaylist.cs