Elin Decompiled Documentation: Empyrean.ColorPicker.Dropper Class Reference
Empyrean.ColorPicker.Dropper Class Reference
Public Member Functions
void PickColors (Action< Color > onColorPicked, Action onDropCanceled)
void Stop ()
Public Attributes
Coroutine coroutine
Action onDropCanceled
Static Public Attributes
const int BlockWidth = 16
const int BlockHeight = 16
Private Member Functions
void Awake ()
void Start ()
void Update ()
void UpdateRenderTextureIfNecessary ()
IEnumerator EnlargeAreaAroundPointer ()
void UpdateTexture ()
void UpdateColorByMousePosition ()
void OnBlockerClicked ()
Private Attributes
ColorPalette palette
Button blockerPrefab
Button blocker
RenderTexture renderTexture
Texture2D texture2D
Texture2D pixelBlock
Color color
Color[] black16x16 = new Color[256]
Action< Color > onColorPicked
Detailed Description
Definition at line 8 of file Dropper.cs.
Member Function Documentation
Awake()
void Empyrean.ColorPicker.Dropper.Awake () inline private
Definition at line 38 of file Dropper.cs.
    {
        Camera.main.targetTexture = renderTexture;
        renderTexture = new RenderTexture(Screen.width, Screen.height, 24);
        texture2D = new Texture2D(Screen.width, Screen.height, TextureFormat.ARGB32, mipChain: false);
        pixelBlock = new Texture2D(16, 16, TextureFormat.ARGB32, mipChain: false);
        for (int i = 0; i < black16x16.Length; i++)
        {
            black16x16[i] = Color.black;
        }
    }
References Empyrean.ColorPicker.Dropper.black16x16, Color, Empyrean.ColorPicker.Dropper.pixelBlock, Empyrean.ColorPicker.Dropper.renderTexture, and Empyrean.ColorPicker.Dropper.texture2D.
EnlargeAreaAroundPointer()
IEnumerator Empyrean.ColorPicker.Dropper.EnlargeAreaAroundPointer () inline private
Definition at line 67 of file Dropper.cs.
    {
        while (true)
        {
            yield return new WaitForEndOfFrame();
            UpdateTexture();
            UpdateColorByMousePosition();
            int num = (int)Mathf.Clamp(Input.mousePosition.x, 0f, texture2D.width);
            int num2 = (int)Mathf.Clamp(Input.mousePosition.y, 0f, texture2D.height);
            Vector2 vector = new Vector2(num - 8, num2 - 8);
            Vector2 vector2 = new Vector2(num + 8, num2 + 8);
            Vector2 vector3 = new Vector2(Mathf.Clamp(vector.x, 0f, texture2D.width - 8), Mathf.Clamp(vector.y, 0f, texture2D.height - 8));
            Vector2 vector4 = new Vector2(Mathf.Clamp(vector2.x, 8f, texture2D.width), Mathf.Clamp(vector2.y, 8f, texture2D.height));
            int blockWidth = (int)vector4.x - (int)vector3.x;
            int blockHeight = (int)vector4.y - (int)vector3.y;
            Color[] pixels = texture2D.GetPixels((int)vector3.x, (int)vector3.y, blockWidth, blockHeight);
            float num3 = vector3.x - vector.x;
            float num4 = vector3.y - vector.y;
            pixelBlock.SetPixels(0, 0, 16, 16, black16x16);
            pixelBlock.SetPixels((int)num3, (int)num4, blockWidth, blockHeight, pixels);
            palette.ShowEnlargedPixels(pixelBlock.GetPixels());
        }
    }
References Empyrean.ColorPicker.Dropper.black16x16, Color, Empyrean.ColorPicker.Dropper.palette, Empyrean.ColorPicker.Dropper.pixelBlock, Empyrean.ColorPicker.ColorPalette.ShowEnlargedPixels(), Empyrean.ColorPicker.Dropper.texture2D, Empyrean.ColorPicker.Dropper.UpdateColorByMousePosition(), and Empyrean.ColorPicker.Dropper.UpdateTexture().
Referenced by Empyrean.ColorPicker.Dropper.PickColors().
OnBlockerClicked()
void Empyrean.ColorPicker.Dropper.OnBlockerClicked () inline private
Definition at line 112 of file Dropper.cs.
    {
        Stop();
        onColorPicked(color);
    }
References Empyrean.ColorPicker.Dropper.color, Empyrean.ColorPicker.Dropper.onColorPicked, and Empyrean.ColorPicker.Dropper.Stop().
Referenced by Empyrean.ColorPicker.Dropper.PickColors().
PickColors()
void Empyrean.ColorPicker.Dropper.PickColors (Action< Color > onColorPicked, Action onDropCanceled) inline
Definition at line 102 of file Dropper.cs.
    {
        this.onDropCanceled = onDropCanceled;
        this.onColorPicked = onColorPicked;
        palette.ShowDropperMarker(value: true);
        blocker = UnityEngine.Object.Instantiate(blockerPrefab);
        blocker.onClick.AddListener(OnBlockerClicked);
        coroutine = blocker.StartCoroutine(EnlargeAreaAroundPointer());
    }
References Empyrean.ColorPicker.Dropper.blocker, Empyrean.ColorPicker.Dropper.blockerPrefab, Empyrean.ColorPicker.Dropper.coroutine, Empyrean.ColorPicker.Dropper.EnlargeAreaAroundPointer(), Empyrean.ColorPicker.Dropper.OnBlockerClicked(), Empyrean.ColorPicker.Dropper.onColorPicked, Empyrean.ColorPicker.Dropper.onDropCanceled, Empyrean.ColorPicker.Dropper.palette, and Empyrean.ColorPicker.ColorPalette.ShowDropperMarker().
Referenced by Empyrean.ColorPicker.ColorPicker.StartDropper().
Start()
void Empyrean.ColorPicker.Dropper.Start () inline private
Definition at line 50 of file Dropper.cs.
    {
    }
Stop()
void Empyrean.ColorPicker.Dropper.Stop () inline
Definition at line 118 of file Dropper.cs.
    {
        palette.ShowDropperMarker(value: false);
        StopCoroutine(coroutine);
        coroutine = null;
        UnityEngine.Object.Destroy(blocker.gameObject);
        blocker = null;
    }
References Empyrean.ColorPicker.Dropper.blocker, Empyrean.ColorPicker.Dropper.coroutine, Empyrean.ColorPicker.Dropper.palette, and Empyrean.ColorPicker.ColorPalette.ShowDropperMarker().
Referenced by LayerColorPicker.OnBack(), Empyrean.ColorPicker.Dropper.OnBlockerClicked(), and LayerColorPicker.OnKill().
Update()
void Empyrean.ColorPicker.Dropper.Update () inline private
Definition at line 54 of file Dropper.cs.
    {
        UpdateRenderTextureIfNecessary();
    }
References Empyrean.ColorPicker.Dropper.UpdateRenderTextureIfNecessary().
UpdateColorByMousePosition()
void Empyrean.ColorPicker.Dropper.UpdateColorByMousePosition () inline private
Definition at line 97 of file Dropper.cs.
    {
        color = texture2D.GetPixel((int)EInput.uiMousePosition.x, (int)EInput.uiMousePosition.y);
    }
References Empyrean.ColorPicker.Dropper.color, Empyrean.ColorPicker.Dropper.texture2D, and EInput.uiMousePosition.
Referenced by Empyrean.ColorPicker.Dropper.EnlargeAreaAroundPointer().
UpdateRenderTextureIfNecessary()
void Empyrean.ColorPicker.Dropper.UpdateRenderTextureIfNecessary () inline private
Definition at line 59 of file Dropper.cs.
    {
        if (renderTexture.width != Screen.width || renderTexture.height != Screen.height)
        {
            renderTexture = new RenderTexture(Screen.width, Screen.height, 24);
        }
    }
References Empyrean.ColorPicker.Dropper.renderTexture.
Referenced by Empyrean.ColorPicker.Dropper.Update().
UpdateTexture()
void Empyrean.ColorPicker.Dropper.UpdateTexture () inline private
Definition at line 91 of file Dropper.cs.
    {
        texture2D.ReadPixels(new Rect(0f, 0f, renderTexture.width, renderTexture.height), 0, 0);
        texture2D.Apply();
    }
References Empyrean.ColorPicker.Dropper.renderTexture, and Empyrean.ColorPicker.Dropper.texture2D.
Referenced by Empyrean.ColorPicker.Dropper.EnlargeAreaAroundPointer().
Member Data Documentation
black16x16
Color [] Empyrean.ColorPicker.Dropper.black16x16 = new Color[256] private
Definition at line 32 of file Dropper.cs.
Referenced by Empyrean.ColorPicker.Dropper.Awake(), and Empyrean.ColorPicker.Dropper.EnlargeAreaAroundPointer().
blocker
Button Empyrean.ColorPicker.Dropper.blocker private
Definition at line 20 of file Dropper.cs.
Referenced by Empyrean.ColorPicker.Dropper.PickColors(), and Empyrean.ColorPicker.Dropper.Stop().
blockerPrefab
Button Empyrean.ColorPicker.Dropper.blockerPrefab private
Definition at line 14 of file Dropper.cs.
Referenced by Empyrean.ColorPicker.Dropper.PickColors().
BlockHeight
const int Empyrean.ColorPicker.Dropper.BlockHeight = 16 static
Definition at line 18 of file Dropper.cs.
BlockWidth
const int Empyrean.ColorPicker.Dropper.BlockWidth = 16 static
Definition at line 16 of file Dropper.cs.
color
Color Empyrean.ColorPicker.Dropper.color private
Definition at line 30 of file Dropper.cs.
Referenced by Empyrean.ColorPicker.Dropper.OnBlockerClicked(), and Empyrean.ColorPicker.Dropper.UpdateColorByMousePosition().
coroutine
Coroutine Empyrean.ColorPicker.Dropper.coroutine
Definition at line 28 of file Dropper.cs.
Referenced by LayerColorPicker.OnBack(), LayerColorPicker.OnKill(), Empyrean.ColorPicker.Dropper.PickColors(), and Empyrean.ColorPicker.Dropper.Stop().
onColorPicked
Action<Color> Empyrean.ColorPicker.Dropper.onColorPicked private
Definition at line 36 of file Dropper.cs.
Referenced by Empyrean.ColorPicker.Dropper.OnBlockerClicked(), and Empyrean.ColorPicker.Dropper.PickColors().
onDropCanceled
Action Empyrean.ColorPicker.Dropper.onDropCanceled
Definition at line 34 of file Dropper.cs.
Referenced by LayerColorPicker.OnBack(), LayerColorPicker.OnKill(), and Empyrean.ColorPicker.Dropper.PickColors().
palette
ColorPalette Empyrean.ColorPicker.Dropper.palette private
Definition at line 11 of file Dropper.cs.
Referenced by Empyrean.ColorPicker.Dropper.EnlargeAreaAroundPointer(), Empyrean.ColorPicker.Dropper.PickColors(), and Empyrean.ColorPicker.Dropper.Stop().
pixelBlock
Texture2D Empyrean.ColorPicker.Dropper.pixelBlock private
Definition at line 26 of file Dropper.cs.
Referenced by Empyrean.ColorPicker.Dropper.Awake(), and Empyrean.ColorPicker.Dropper.EnlargeAreaAroundPointer().
renderTexture
RenderTexture Empyrean.ColorPicker.Dropper.renderTexture private
Definition at line 22 of file Dropper.cs.
Referenced by Empyrean.ColorPicker.Dropper.Awake(), Empyrean.ColorPicker.Dropper.UpdateRenderTextureIfNecessary(), and Empyrean.ColorPicker.Dropper.UpdateTexture().
texture2D
Texture2D Empyrean.ColorPicker.Dropper.texture2D private
Definition at line 24 of file Dropper.cs.
Referenced by Empyrean.ColorPicker.Dropper.Awake(), Empyrean.ColorPicker.Dropper.EnlargeAreaAroundPointer(), Empyrean.ColorPicker.Dropper.UpdateColorByMousePosition(), and Empyrean.ColorPicker.Dropper.UpdateTexture().
The documentation for this class was generated from the following file:
Elin/Plugins.UI/Empyrean/ColorPicker/Dropper.cs