Elin Decompiled Documentation: SourceTactics Class Reference
SourceTactics Class Reference
Classes
class Row
Public Member Functions
override Row CreateRow ()
override Row CreateRowByMapping (IReadOnlyDictionary< string, int > mapping)
override void SetRow (Row r)
override IReadOnlyDictionary< string, int > GetRowMapping ()
override IReadOnlyDictionary< string, string > GetTypeMapping ()
Public Member Functions inherited from SourceDataString< SourceTactics.Row >
override T GetRow (string id)
Static Public Attributes
static readonly IReadOnlyDictionary< string, int > RowMapping
static readonly IReadOnlyDictionary< string, string > TypeMapping
Detailed Description
Definition at line 4 of file SourceTactics.cs.
Member Function Documentation
CreateRow()
override Row SourceTactics.CreateRow () inline
Definition at line 100 of file SourceTactics.cs.
    {
        return new Row
        {
            id = SourceData.GetString(0),
            name_JP = SourceData.GetString(1),
            name = SourceData.GetString(2),
            dist = SourceData.GetInt(4),
            move = SourceData.GetInt(5),
            movePC = SourceData.GetInt(6),
            party = SourceData.GetInt(7),
            taunt = SourceData.GetInt(8),
            melee = SourceData.GetInt(9),
            range = SourceData.GetInt(10),
            spell = SourceData.GetInt(11),
            heal = SourceData.GetInt(12),
            summon = SourceData.GetInt(13),
            buff = SourceData.GetInt(14),
            debuff = SourceData.GetInt(15),
            tag = SourceData.GetStringArray(16),
            detail_JP = SourceData.GetString(17),
            detail = SourceData.GetString(18)
        };
    }
References SourceData< T, T2 >.GetInt(), SourceData< T, T2 >.GetString(), and SourceData< T, T2 >.GetStringArray().
CreateRowByMapping()
override Row SourceTactics.CreateRowByMapping (IReadOnlyDictionary< string, int > mapping) inline
Definition at line 125 of file SourceTactics.cs.
    {
        return new Row
        {
            id = SourceData.GetString(mapping["id"]),
            name_JP = SourceData.GetString(mapping["name_JP"]),
            name = SourceData.GetString(mapping["name"]),
            dist = SourceData.GetInt(mapping["dist"]),
            move = SourceData.GetInt(mapping["move"]),
            movePC = SourceData.GetInt(mapping["movePC"]),
            party = SourceData.GetInt(mapping["party"]),
            taunt = SourceData.GetInt(mapping["taunt"]),
            melee = SourceData.GetInt(mapping["melee"]),
            range = SourceData.GetInt(mapping["range"]),
            spell = SourceData.GetInt(mapping["spell"]),
            heal = SourceData.GetInt(mapping["heal"]),
            summon = SourceData.GetInt(mapping["summon"]),
            buff = SourceData.GetInt(mapping["buff"]),
            debuff = SourceData.GetInt(mapping["debuff"]),
            tag = SourceData.GetStringArray(mapping["tag"]),
            detail_JP = SourceData.GetString(mapping["detail_JP"]),
            detail = SourceData.GetString(mapping["detail"])
        };
    }
References SourceData< T, T2 >.GetInt(), SourceData< T, T2 >.GetString(), and SourceData< T, T2 >.GetStringArray().
GetRowMapping()
override IReadOnlyDictionary< string, int > SourceTactics.GetRowMapping () inline
Definition at line 155 of file SourceTactics.cs.
    {
        return RowMapping;
    }
References RowMapping.
GetTypeMapping()
override IReadOnlyDictionary< string, string > SourceTactics.GetTypeMapping () inline
Definition at line 160 of file SourceTactics.cs.
    {
        return TypeMapping;
    }
References TypeMapping.
SetRow()
override void SourceTactics.SetRow (Row r) inline
Definition at line 150 of file SourceTactics.cs.
    {
        map[r.id] = r;
    }
References SourceTactics.Row.id.
Member Data Documentation
RowMapping
readonly IReadOnlyDictionary<string, int> SourceTactics.RowMapping static
Initial value:
= new Dictionary<string, int>
    {
        ["id"] = 0,
        ["name_JP"] = 1,
        ["name"] = 2,
        ["dist"] = 4,
        ["move"] = 5,
        ["movePC"] = 6,
        ["party"] = 7,
        ["taunt"] = 8,
        ["melee"] = 9,
        ["range"] = 10,
        ["spell"] = 11,
        ["heal"] = 12,
        ["summon"] = 13,
        ["buff"] = 14,
        ["debuff"] = 15,
        ["tag"] = 16,
        ["detail_JP"] = 17,
        ["detail"] = 18
    }
Definition at line 56 of file SourceTactics.cs.
Referenced by GetRowMapping().
TypeMapping
readonly IReadOnlyDictionary<string, string> SourceTactics.TypeMapping static
Initial value:
= new Dictionary<string, string>
    {
        ["id"] = "string",
        ["name_JP"] = "string",
        ["name"] = "string",
        ["dist"] = "int",
        ["move"] = "int",
        ["movePC"] = "int",
        ["party"] = "int",
        ["taunt"] = "int",
        ["melee"] = "int",
        ["range"] = "int",
        ["spell"] = "int",
        ["heal"] = "int",
        ["summon"] = "int",
        ["buff"] = "int",
        ["debuff"] = "int",
        ["tag"] = "string[]",
        ["detail_JP"] = "string",
        ["detail"] = "string"
    }
Definition at line 78 of file SourceTactics.cs.
Referenced by GetTypeMapping().
The documentation for this class was generated from the following file:
Elin/SourceTactics.cs