Elin Decompiled Documentation: CardFilter Class Reference
CardFilter Class Reference
Classes
class FilterCategory
class FilterItem
Public Types
enum FilterMode { None , Exclude , Match , Equipped }
Public Member Functions
override string ToString ()
virtual bool ContainsTag (CardRow source, string str)
void Init ()
bool Pass (CardRow source)
void BuildList (List< FilterItem > list, string[] strs)
Static Public Member Functions
static FilterItem GetFilterItem (string text)
Static Public Member Functions inherited from EClass
static int rnd (int a)
static int curve (int a, int start, int step, int rate=75)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Public Attributes
string id
string[] strTag
string[] strFilter
string[] filterCategory
string[] idCard
List< FilterItem > tags = new List<FilterItem>()
List< FilterItem > filters = new List<FilterItem>()
List< FilterCategory > categories = new List<FilterCategory>()
List< SourceCategory.Row > categoriesInclude = new List<SourceCategory.Row>()
bool isChara
Protected Member Functions
virtual bool _ShouldPass (CardRow source)
Private Attributes
bool isInitialied
Additional Inherited Members
Static Public Attributes inherited from EClass
static Core core
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Detailed Description
Definition at line 5 of file CardFilter.cs.
Member Enumeration Documentation
FilterMode
enum CardFilter.FilterMode
Enumerator
None
Exclude
Match
Equipped
Definition at line 21 of file CardFilter.cs.
    {
        None,
        Exclude,
        Match,
        Equipped
    }
Member Function Documentation
_ShouldPass()
virtual bool CardFilter._ShouldPass (CardRow source) inline protected virtual
Reimplemented in CharaFilter, and ThingFilter.
Definition at line 56 of file CardFilter.cs.
    {
        return true;
    }
Referenced by Pass().
BuildList()
void CardFilter.BuildList (List< FilterItem > list, string[] strs) inline
Definition at line 161 of file CardFilter.cs.
    {
        if (strs != null)
        {
            foreach (string text in strs)
            {
                list.Add(GetFilterItem(text));
            }
        }
    }
References GetFilterItem().
Referenced by Init().
ContainsTag()
virtual bool CardFilter.ContainsTag (CardRow source, string str) inline virtual
Reimplemented in CharaFilter.
Definition at line 61 of file CardFilter.cs.
    {
        return source.tag.Contains(str);
    }
References RenderRow.tag.
Referenced by Pass().
GetFilterItem()
static FilterItem CardFilter.GetFilterItem (string text) inline static
Definition at line 172 of file CardFilter.cs.
    {
        bool flag = text.StartsWith("-");
        return new FilterItem
        {
            exclude = flag,
            name = (flag ? text.Substring(1) : text)
        };
    }
Referenced by BuildList().
Init()
void CardFilter.Init () inline
Definition at line 66 of file CardFilter.cs.
    {
        BuildList(tags, strTag);
        BuildList(filters, strFilter);
        if (!filterCategory.IsEmpty())
        {
            string[] array = filterCategory;
            foreach (string text in array)
            {
                bool flag = text.StartsWith('-');
                SourceCategory.Row row = EClass.sources.categories.map[flag ? text.Remove(0, 1) : text];
                categories.Add(new FilterCategory
                {
                    exclude = flag,
                    row = row
                });
                if (!flag)
                {
                    categoriesInclude.Add(row);
                }
            }
        }
        isInitialied = true;
    }
References BuildList(), categories, SourceManager.categories, categoriesInclude, filterCategory, filters, isInitialied, EClass.sources, strFilter, strTag, and tags.
Referenced by Pass().
Pass()
bool CardFilter.Pass (CardRow source) inline
Definition at line 91 of file CardFilter.cs.
    {
        if (!isInitialied)
        {
            Init();
        }
        if (source.chance == 0 || source.isOrigin)
        {
            return false;
        }
        for (int i = 0; i < tags.Count; i++)
        {
            FilterItem filterItem = tags[i];
            if (filterItem.exclude)
            {
                if (ContainsTag(source, filterItem.name))
                {
                    return false;
                }
            }
            else if (!ContainsTag(source, filterItem.name))
            {
                return false;
            }
        }
        for (int j = 0; j < filters.Count; j++)
        {
            FilterItem filterItem2 = filters[j];
            if (filterItem2.exclude)
            {
                if (source.filter.Contains(filterItem2.name))
                {
                    return false;
                }
            }
            else if (!source.filter.Contains(filterItem2.name))
            {
                return false;
            }
        }
        if ((isChara && !source.isChara) || (!isChara && source.isChara))
        {
            return false;
        }
        if (categories.Count > 0)
        {
            bool flag = false;
            foreach (FilterCategory category in categories)
            {
                if ((!flag || category.exclude) && EClass.sources.categories.map[source.category].IsChildOf(category.row))
                {
                    if (category.exclude)
                    {
                        return false;
                    }
                    flag = true;
                }
            }
            if (!flag)
            {
                return false;
            }
        }
        if (!_ShouldPass(source))
        {
            return false;
        }
        return true;
    }
References _ShouldPass(), categories, SourceManager.categories, RenderRow.category, RenderRow.chance, ContainsTag(), CardFilter.FilterItem.exclude, CardFilter.FilterCategory.exclude, CardRow.filter, filters, Init(), isChara, CardRow.isChara, isInitialied, CardRow.isOrigin, CardFilter.FilterItem.name, CardFilter.FilterCategory.row, EClass.sources, and tags.
Referenced by SpawnList.CreateMaster().
ToString()
override string CardFilter.ToString () inline
Definition at line 51 of file CardFilter.cs.
    {
        return id;
    }
References id.
Member Data Documentation
categories
List<FilterCategory> CardFilter.categories = new List<FilterCategory>()
Definition at line 43 of file CardFilter.cs.
Referenced by Init(), and Pass().
categoriesInclude
List<SourceCategory.Row> CardFilter.categoriesInclude = new List<SourceCategory.Row>()
Definition at line 45 of file CardFilter.cs.
Referenced by Init(), and SpawnList.Select().
filterCategory
string [] CardFilter.filterCategory
Definition at line 35 of file CardFilter.cs.
Referenced by Init().
filters
List<FilterItem> CardFilter.filters = new List<FilterItem>()
Definition at line 41 of file CardFilter.cs.
Referenced by Init(), and Pass().
id
string CardFilter.id
Definition at line 29 of file CardFilter.cs.
Referenced by ToString().
idCard
string [] CardFilter.idCard
Definition at line 37 of file CardFilter.cs.
Referenced by SpawnList.CreateMaster().
isChara
bool CardFilter.isChara
Definition at line 49 of file CardFilter.cs.
Referenced by CharaFilter.CharaFilter(), and Pass().
isInitialied
bool CardFilter.isInitialied private
Definition at line 47 of file CardFilter.cs.
Referenced by Init(), and Pass().
strFilter
string [] CardFilter.strFilter
Definition at line 33 of file CardFilter.cs.
Referenced by Init().
strTag
string [] CardFilter.strTag
Definition at line 31 of file CardFilter.cs.
Referenced by Init().
tags
List<FilterItem> CardFilter.tags = new List<FilterItem>()
Definition at line 39 of file CardFilter.cs.
Referenced by Init(), Pass(), and SpawnList.Select().
The documentation for this class was generated from the following file:
Elin/CardFilter.cs