Elin Decompiled Documentation: Steam Class Reference
Steam Class Reference
Public Member Functions
void Init ()
void CheckUpdate ()
void CheckDLC ()
void TestHasDLC ()
void CreateUserContent (BaseModPackage p)
void UpdateUserContent (PublishedFileId_t fileId)
WorkshopItemData CreateItemData (BaseModPackage p)
Static Public Member Functions
static bool HasDLC (ID_DLC id)
static void GetAchievement (ID_Achievement id)
static void ResetAllAchievement ()
static void ResetAchievement (ID_Achievement id)
Public Attributes
SteamworksBehaviour steamworks
UserGeneratedContentQueryManager ugc
WorkshopItem testData
BaseModPackage currentPackage
Static Public Attributes
static Steam Instance
Private Member Functions
void Awake ()
void CreateUserContent2 (UgcQuery query)
Detailed Description
Definition at line 9 of file Steam.cs.
Member Function Documentation
Awake()
void Steam.Awake () inline private
Definition at line 21 of file Steam.cs.
    {
        Instance = this;
    }
References Instance.
CheckDLC()
void Steam.CheckDLC () inline
Definition at line 36 of file Steam.cs.
    {
        Debug.Log(HasDLC(ID_DLC.Test));
    }
References Debug, and HasDLC().
CheckUpdate()
void Steam.CheckUpdate () inline
Definition at line 32 of file Steam.cs.
    {
    }
Referenced by CoreDebug.UpdateInput().
CreateItemData()
WorkshopItemData Steam.CreateItemData (BaseModPackage p) inline
Definition at line 197 of file Steam.cs.
    {
        FileInfo fileInfo = new FileInfo(p.dirInfo.FullName + "/preview.jpg");
        DirectoryInfo directoryInfo = new DirectoryInfo(p.dirInfo.FullName);
        WorkshopItemData workshopItemData = default(WorkshopItemData);
        workshopItemData.appId = steamworks.settings.applicationId;
        workshopItemData.title = p.title;
        workshopItemData.description = p.description;
        workshopItemData.content = directoryInfo;
        workshopItemData.preview = fileInfo;
        workshopItemData.metadata = p.id ?? "";
        workshopItemData.tags = p.tags;
        workshopItemData.visibility = ERemoteStoragePublishedFileVisibility.k_ERemoteStoragePublishedFileVisibilityPublic;
        WorkshopItemData result = workshopItemData;
        switch (p.visibility)
        {
        case "Unlisted":
            result.visibility = ERemoteStoragePublishedFileVisibility.k_ERemoteStoragePublishedFileVisibilityUnlisted;
            break;
        case "Private":
            result.visibility = ERemoteStoragePublishedFileVisibility.k_ERemoteStoragePublishedFileVisibilityPrivate;
            break;
        case "FriendsOnly":
            result.visibility = ERemoteStoragePublishedFileVisibility.k_ERemoteStoragePublishedFileVisibilityFriendsOnly;
            break;
        }
        Debug.Log(App.Client.Owner.id);
        Debug.Log(result.appId);
        Debug.Log(p.id);
        Debug.Log(directoryInfo.Exists + "/" + directoryInfo.FullName);
        Debug.Log(fileInfo.Exists + "/" + fileInfo.FullName);
        return result;
    }
References Debug, BaseModPackage.description, BaseModPackage.dirInfo, BaseModPackage.id, steamworks, BaseModPackage.tags, BaseModPackage.title, and BaseModPackage.visibility.
Referenced by CreateUserContent2(), and UpdateUserContent().
CreateUserContent()
void Steam.CreateUserContent (BaseModPackage p) inline
Definition at line 111 of file Steam.cs.
    {
        LayerProgress.Start("Uploading").onCancel = delegate
        {
        };
        p.UpdateMeta(updateOnly: true);
        currentPackage = p;
        UgcQuery myPublished = UgcQuery.GetMyPublished();
        myPublished.SetReturnKeyValueTags(tags: true);
        myPublished.Execute(CreateUserContent2);
    }
References CreateUserContent2(), currentPackage, LayerProgress.onCancel, LayerProgress.Start(), and BaseModPackage.UpdateMeta().
CreateUserContent2()
void Steam.CreateUserContent2 (UgcQuery query) inline private
Definition at line 123 of file Steam.cs.
    {
        Debug.Log("Creating Content2");
        BaseModPackage baseModPackage = currentPackage;
        if (query.ResultsList != null)
        {
            Debug.Log(query.ResultsList.Count);
        }
        foreach (WorkshopItem results in query.ResultsList)
        {
            if (results.keyValueTags == null)
            {
                continue;
            }
            StringKeyValuePair[] keyValueTags = results.keyValueTags;
            for (int i = 0; i < keyValueTags.Length; i++)
            {
                StringKeyValuePair stringKeyValuePair = keyValueTags[i];
                if (stringKeyValuePair.key == "id" && stringKeyValuePair.value == baseModPackage.id && results.Owner.id == App.Client.Owner.id)
                {
                    Debug.Log("Updating Content");
                    UpdateUserContent(results.FileId);
                    return;
                }
            }
        }
        Debug.Log("Creating Content");
        CreateItemData(baseModPackage).Create(null, null, new WorkshopItemKeyValueTag[1]
        {
            new WorkshopItemKeyValueTag
            {
                key = "id",
                value = baseModPackage.id
            }
        }, delegate(WorkshopItemDataCreateStatus result)
        {
            LayerProgress.completed = true;
            if (result.hasError)
            {
                Dialog.Ok("mod_publish_error");
                EClass.ui.Say(result.errorMessage);
                Debug.Log("error:" + result.errorMessage);
            }
            else
            {
                Dialog.Ok("mod_created");
                Debug.Log("created");
            }
        });
    }
References CreateItemData(), currentPackage, Debug, Dialog.Ok(), EClass.ui, and UpdateUserContent().
Referenced by CreateUserContent().
GetAchievement()
static void Steam.GetAchievement (ID_Achievement id) inline static
Definition at line 51 of file Steam.cs.
    {
        try
        {
            foreach (AchievementObject achievement in Instance.steamworks.settings.achievements)
            {
                if (achievement.Id == id.ToString())
                {
                    if (achievement.IsAchieved)
                    {
                        return;
                    }
                    try
                    {
                        achievement.Unlock();
                        EClass.ui.Say("sys_acv".lang(achievement.Name), Resources.Load<Sprite>("Media/Graphics/Icon/Achievement/acv_" + id));
                        SE.Play("achievement");
                        achievement.Store();
                        return;
                    }
                    catch (Exception ex)
                    {
                        Debug.LogError("Error Achievement 1:" + ex);
                        return;
                    }
                }
            }
        }
        catch (Exception ex2)
        {
            Debug.LogError("Error Achievement 2:" + ex2);
        }
        Debug.Log("Achievement not found:" + id);
    }
References Debug, Instance, steamworks, and EClass.ui.
Referenced by Chara._ShowDialog(), FactionBranch.AddMemeber(), Chara.Die(), Player.ModKarma(), UIHangIcon.OnClickCorner(), TraitDrink.OnDrink(), AI_Fish.ProgressFish.OnProgressComplete(), FoodEffect.Proc(), Trait.TryOpenLock(), and CoreDebug.UpdateAlways().
HasDLC()
static bool Steam.HasDLC (ID_DLC id) inline static
Definition at line 41 of file Steam.cs.
    {
        return id switch
        {
            ID_DLC.CursedManor => true,
            ID_DLC.BackerReward => EClass.core.config.HasBackerRewardCode(),
            _ => EClass.core.config.HasBackerRewardCode(),
        };
    }
References Core.config, EClass.core, and CoreConfig.HasBackerRewardCode().
Referenced by CheckDLC(), FactionBranch.ReceivePackages(), and TestHasDLC().
Init()
void Steam.Init () inline
Definition at line 26 of file Steam.cs.
    {
        SteamAPI.Init();
        BaseCore.IsOffline = !App.Client.LoggedOn || SteamSettings.behaviour == null;
    }
Referenced by Core.Start().
ResetAchievement()
static void Steam.ResetAchievement (ID_Achievement id) inline static
Definition at line 95 of file Steam.cs.
    {
        AchievementObject achievementObject = Instance.steamworks.settings.achievements.First((AchievementObject a) => a.Id == id.ToString());
        if (achievementObject != null)
        {
            achievementObject.ClearAchievement();
            achievementObject.Store();
        }
    }
References Instance, and steamworks.
Referenced by CoreDebug.ResetAchievement().
ResetAllAchievement()
static void Steam.ResetAllAchievement () inline static
Definition at line 86 of file Steam.cs.
    {
        foreach (AchievementObject achievement in Instance.steamworks.settings.achievements)
        {
            achievement.ClearAchievement();
            achievement.Store();
        }
    }
References Instance, and steamworks.
Referenced by CoreDebug.ResetAllAchievement().
TestHasDLC()
void Steam.TestHasDLC () inline
Definition at line 105 of file Steam.cs.
    {
        Debug.Log(HasDLC(ID_DLC.Test));
        Debug.Log(HasDLC(ID_DLC.CursedManor));
    }
References Debug, and HasDLC().
UpdateUserContent()
void Steam.UpdateUserContent (PublishedFileId_t fileId) inline
Definition at line 174 of file Steam.cs.
    {
        Debug.Log("Updating Content");
        BaseModPackage p = currentPackage;
        WorkshopItemData workshopItemData = CreateItemData(p);
        workshopItemData.publishedFileId = fileId;
        workshopItemData.Update(delegate(WorkshopItemDataUpdateStatus result)
        {
            LayerProgress.completed = true;
            if (result.hasError)
            {
                Dialog.Ok("mod_publish_error");
                EClass.ui.Say(result.errorMessage);
                Debug.Log("error:" + result.errorMessage);
            }
            else
            {
                Dialog.Ok("mod_updated");
                Debug.Log("updated");
            }
        });
    }
References CreateItemData(), currentPackage, and Debug.
Referenced by CreateUserContent2().
Member Data Documentation
currentPackage
BaseModPackage Steam.currentPackage
Definition at line 19 of file Steam.cs.
Referenced by CreateUserContent(), CreateUserContent2(), and UpdateUserContent().
Instance
Steam Steam.Instance static
Definition at line 11 of file Steam.cs.
Referenced by Awake(), GetAchievement(), ResetAchievement(), and ResetAllAchievement().
steamworks
SteamworksBehaviour Steam.steamworks
Definition at line 13 of file Steam.cs.
Referenced by Core.Awake(), CreateItemData(), CoreDebug.FirstAdventurer(), GetAchievement(), ResetAchievement(), and ResetAllAchievement().
testData
WorkshopItem Steam.testData
Definition at line 17 of file Steam.cs.
ugc
UserGeneratedContentQueryManager Steam.ugc
Definition at line 15 of file Steam.cs.
The documentation for this class was generated from the following file:
Elin/Steam.cs