Elin Decompiled Documentation: ToJShadow Class Reference
ToJShadow Class Reference
Public Member Functions
override void ModifyMesh (VertexHelper vh)
Protected Member Functions
ToJShadow ()
void ApplyShadowZeroAlloc (List< UIVertex > verts, Color32 color, int start, int end, float x, float y)
void ApplyShadow (List< UIVertex > verts, Color32 color, int start, int end, float x, float y)
Properties
Color effectColor [get, set]
Vector2 effectDistance [get, set]
bool useGraphicAlpha [get, set]
Private Attributes
Color m_EffectColor = new Color(0f, 0f, 0f, 0.5f)
Vector2 m_EffectDistance = new Vector2(1f, -1f)
bool m_UseGraphicAlpha = true
List< UIVertex > m_Verts = new List<UIVertex>()
Detailed Description
Definition at line 6 of file ToJShadow.cs.
Constructor & Destructor Documentation
ToJShadow()
ToJShadow.ToJShadow () inline protected
Definition at line 86 of file ToJShadow.cs.
    {
    }
Member Function Documentation
ApplyShadow()
void ToJShadow.ApplyShadow (List< UIVertex > verts, Color32 color, int start, int end, float x, float y) inline protected
Definition at line 115 of file ToJShadow.cs.
    {
        int num = verts.Count * 2;
        if (verts.Capacity < num)
        {
            verts.Capacity = num;
        }
        ApplyShadowZeroAlloc(verts, color, start, end, x, y);
    }
References ApplyShadowZeroAlloc().
Referenced by ModifyMesh().
ApplyShadowZeroAlloc()
void ToJShadow.ApplyShadowZeroAlloc (List< UIVertex > verts, Color32 color, int start, int end, float x, float y) inline protected
Definition at line 90 of file ToJShadow.cs.
    {
        int num = verts.Count * 2;
        if (verts.Capacity < num)
        {
            verts.Capacity = num;
        }
        for (int i = start; i < end; i++)
        {
            UIVertex uIVertex = verts[i];
            verts.Add(uIVertex);
            Vector3 position = uIVertex.position;
            position.x += x;
            position.y += y;
            uIVertex.position = position;
            Color32 color2 = color;
            if (m_UseGraphicAlpha)
            {
                color2.a = (byte)(color2.a * verts[i].color.a / 255);
            }
            uIVertex.color = color2;
            verts[i] = uIVertex;
        }
    }
References m_UseGraphicAlpha.
Referenced by ApplyShadow().
ModifyMesh()
override void ToJShadow.ModifyMesh (VertexHelper vh) inline
Definition at line 125 of file ToJShadow.cs.
    {
        if (!IsActive())
        {
            return;
        }
        vh.GetUIVertexStream(m_Verts);
        int count = m_Verts.Count;
        ApplyShadow(m_Verts, effectColor, 0, m_Verts.Count, effectDistance.x, effectDistance.y);
        Text component = GetComponent<Text>();
        if (component != null && component.material.shader == Shader.Find("Text Effects/Fancy Text"))
        {
            for (int i = 0; i < m_Verts.Count - count; i++)
            {
                UIVertex value = m_Verts[i];
                value.uv1 = new Vector2(0f, 0f);
                m_Verts[i] = value;
            }
        }
        vh.Clear();
        vh.AddUIVertexTriangleStream(m_Verts);
    }
References ApplyShadow(), effectColor, effectDistance, and m_Verts.
Member Data Documentation
m_EffectColor
Color ToJShadow.m_EffectColor = new Color(0f, 0f, 0f, 0.5f) private
Definition at line 9 of file ToJShadow.cs.
m_EffectDistance
Vector2 ToJShadow.m_EffectDistance = new Vector2(1f, -1f) private
Definition at line 12 of file ToJShadow.cs.
m_UseGraphicAlpha
bool ToJShadow.m_UseGraphicAlpha = true private
Definition at line 15 of file ToJShadow.cs.
Referenced by ApplyShadowZeroAlloc().
m_Verts
List<UIVertex> ToJShadow.m_Verts = new List<UIVertex>() private
Definition at line 17 of file ToJShadow.cs.
Referenced by ModifyMesh().
Property Documentation
effectColor
Color ToJShadow.effectColor get set
Definition at line 19 of file ToJShadow.cs.
    {
        get
        {
            return m_EffectColor;
        }
        set
        {
            m_EffectColor = value;
            if (base.graphic != null)
            {
                base.graphic.SetVerticesDirty();
            }
        }
    }
Referenced by ModifyMesh().
effectDistance
Vector2 ToJShadow.effectDistance get set
Definition at line 35 of file ToJShadow.cs.
    {
        get
        {
            return m_EffectDistance;
        }
        set
        {
            if (value.x > 600f)
            {
                value.x = 600f;
            }
            if (value.x < -600f)
            {
                value.x = -600f;
            }
            if (value.y > 600f)
            {
                value.y = 600f;
            }
            if (value.y < -600f)
            {
                value.y = -600f;
            }
            if (!(m_EffectDistance == value))
            {
                m_EffectDistance = value;
                if (base.graphic != null)
                {
                    base.graphic.SetVerticesDirty();
                }
            }
        }
    }
Referenced by ModifyMesh().
useGraphicAlpha
bool ToJShadow.useGraphicAlpha get set
Definition at line 70 of file ToJShadow.cs.
    {
        get
        {
            return m_UseGraphicAlpha;
        }
        set
        {
            m_UseGraphicAlpha = value;
            if (base.graphic != null)
            {
                base.graphic.SetVerticesDirty();
            }
        }
    }
The documentation for this class was generated from the following file:
Elin/Plugins.UI/ToJShadow.cs