Elin Decompiled Documentation: SFB.StandaloneFileBrowser Class Reference
SFB.StandaloneFileBrowser Class Reference
Static Public Member Functions
static string[] OpenFilePanel (string title, string directory, string extension, bool multiselect)
static string[] OpenFilePanel (string title, string directory, ExtensionFilter[] extensions, bool multiselect)
static void OpenFilePanelAsync (string title, string directory, string extension, bool multiselect, Action< string[]> cb)
static void OpenFilePanelAsync (string title, string directory, ExtensionFilter[] extensions, bool multiselect, Action< string[]> cb)
static string[] OpenFolderPanel (string title, string directory, bool multiselect)
static void OpenFolderPanelAsync (string title, string directory, bool multiselect, Action< string[]> cb)
static string SaveFilePanel (string title, string directory, string defaultName, string extension)
static string SaveFilePanel (string title, string directory, string defaultName, ExtensionFilter[] extensions)
static void SaveFilePanelAsync (string title, string directory, string defaultName, string extension, Action< string > cb)
static void SaveFilePanelAsync (string title, string directory, string defaultName, ExtensionFilter[] extensions, Action< string > cb)
Static Private Member Functions
static StandaloneFileBrowser ()
Static Private Attributes
static IStandaloneFileBrowser _platformWrapper
Detailed Description
Definition at line 5 of file StandaloneFileBrowser.cs.
Constructor & Destructor Documentation
StandaloneFileBrowser()
static SFB.StandaloneFileBrowser.StandaloneFileBrowser () inline static private
Definition at line 9 of file StandaloneFileBrowser.cs.
    {
        _platformWrapper = new StandaloneFileBrowserWindows();
    }
References SFB.StandaloneFileBrowser._platformWrapper.
Member Function Documentation
OpenFilePanel() [1/2]
static string[] SFB.StandaloneFileBrowser.OpenFilePanel (string title, string directory, ExtensionFilter[] extensions, bool multiselect) inline static
Definition at line 23 of file StandaloneFileBrowser.cs.
    {
        return _platformWrapper.OpenFilePanel(title, directory, extensions, multiselect);
    }
References SFB.StandaloneFileBrowser._platformWrapper, SFB.IStandaloneFileBrowser.OpenFilePanel(), and title.
OpenFilePanel() [2/2]
static string[] SFB.StandaloneFileBrowser.OpenFilePanel (string title, string directory, string extension, bool multiselect) inline static
Definition at line 14 of file StandaloneFileBrowser.cs.
    {
        ExtensionFilter[] extensions = (string.IsNullOrEmpty(extension) ? null : new ExtensionFilter[1]
        {
            new ExtensionFilter("", extension)
        });
        return OpenFilePanel(title, directory, extensions, multiselect);
    }
References SFB.StandaloneFileBrowser.OpenFilePanel(), and title.
Referenced by WidgetManager.DialogLoad(), AM_Copy.ImportDialog(), Zone.ImportDialog(), WidgetSceneCustomizer.OnClickLoad(), and SFB.StandaloneFileBrowser.OpenFilePanel().
OpenFilePanelAsync() [1/2]
static void SFB.StandaloneFileBrowser.OpenFilePanelAsync (string title, string directory, ExtensionFilter[] extensions, bool multiselect, Action< string[]> cb) inline static
Definition at line 37 of file StandaloneFileBrowser.cs.
    {
        _platformWrapper.OpenFilePanelAsync(title, directory, extensions, multiselect, cb);
    }
References SFB.StandaloneFileBrowser._platformWrapper, SFB.IStandaloneFileBrowser.OpenFilePanelAsync(), and title.
OpenFilePanelAsync() [2/2]
static void SFB.StandaloneFileBrowser.OpenFilePanelAsync (string title, string directory, string extension, bool multiselect, Action< string[]> cb) inline static
Definition at line 28 of file StandaloneFileBrowser.cs.
    {
        ExtensionFilter[] extensions = (string.IsNullOrEmpty(extension) ? null : new ExtensionFilter[1]
        {
            new ExtensionFilter("", extension)
        });
        OpenFilePanelAsync(title, directory, extensions, multiselect, cb);
    }
References SFB.StandaloneFileBrowser.OpenFilePanelAsync(), and title.
Referenced by SFB.StandaloneFileBrowser.OpenFilePanelAsync().
OpenFolderPanel()
static string[] SFB.StandaloneFileBrowser.OpenFolderPanel (string title, string directory, bool multiselect) inline static
Definition at line 42 of file StandaloneFileBrowser.cs.
    {
        return _platformWrapper.OpenFolderPanel(title, directory, multiselect);
    }
References SFB.StandaloneFileBrowser._platformWrapper, SFB.IStandaloneFileBrowser.OpenFolderPanel(), and title.
OpenFolderPanelAsync()
static void SFB.StandaloneFileBrowser.OpenFolderPanelAsync (string title, string directory, bool multiselect, Action< string[]> cb) inline static
Definition at line 47 of file StandaloneFileBrowser.cs.
    {
        _platformWrapper.OpenFolderPanelAsync(title, directory, multiselect, cb);
    }
References SFB.StandaloneFileBrowser._platformWrapper, SFB.IStandaloneFileBrowser.OpenFolderPanelAsync(), and title.
SaveFilePanel() [1/2]
static string SFB.StandaloneFileBrowser.SaveFilePanel (string title, string directory, string defaultName, ExtensionFilter[] extensions) inline static
Definition at line 61 of file StandaloneFileBrowser.cs.
    {
        return _platformWrapper.SaveFilePanel(title, directory, defaultName, extensions);
    }
References SFB.StandaloneFileBrowser._platformWrapper, SFB.IStandaloneFileBrowser.SaveFilePanel(), and title.
SaveFilePanel() [2/2]
static string SFB.StandaloneFileBrowser.SaveFilePanel (string title, string directory, string defaultName, string extension) inline static
Definition at line 52 of file StandaloneFileBrowser.cs.
    {
        ExtensionFilter[] extensions = (string.IsNullOrEmpty(extension) ? null : new ExtensionFilter[1]
        {
            new ExtensionFilter("", extension)
        });
        return SaveFilePanel(title, directory, defaultName, extensions);
    }
References SFB.StandaloneFileBrowser.SaveFilePanel(), and title.
Referenced by WidgetManager.DialogSave(), PartialMap.ExportDialog(), Zone.ExportDialog(), ContentConfigOther.OnClickDownloadWallpaper(), WidgetSceneCustomizer.OnClickSave(), LayerEditHouse.OnInit(), and SFB.StandaloneFileBrowser.SaveFilePanel().
SaveFilePanelAsync() [1/2]
static void SFB.StandaloneFileBrowser.SaveFilePanelAsync (string title, string directory, string defaultName, ExtensionFilter[] extensions, Action< string > cb) inline static
Definition at line 75 of file StandaloneFileBrowser.cs.
    {
        _platformWrapper.SaveFilePanelAsync(title, directory, defaultName, extensions, cb);
    }
References SFB.StandaloneFileBrowser._platformWrapper, SFB.IStandaloneFileBrowser.SaveFilePanelAsync(), and title.
SaveFilePanelAsync() [2/2]
static void SFB.StandaloneFileBrowser.SaveFilePanelAsync (string title, string directory, string defaultName, string extension, Action< string > cb) inline static
Definition at line 66 of file StandaloneFileBrowser.cs.
    {
        ExtensionFilter[] extensions = (string.IsNullOrEmpty(extension) ? null : new ExtensionFilter[1]
        {
            new ExtensionFilter("", extension)
        });
        SaveFilePanelAsync(title, directory, defaultName, extensions, cb);
    }
References SFB.StandaloneFileBrowser.SaveFilePanelAsync(), and title.
Referenced by SFB.StandaloneFileBrowser.SaveFilePanelAsync().
Member Data Documentation
_platformWrapper
IStandaloneFileBrowser SFB.StandaloneFileBrowser._platformWrapper static private
Definition at line 7 of file StandaloneFileBrowser.cs.
Referenced by SFB.StandaloneFileBrowser.OpenFilePanel(), SFB.StandaloneFileBrowser.OpenFilePanelAsync(), SFB.StandaloneFileBrowser.OpenFolderPanel(), SFB.StandaloneFileBrowser.OpenFolderPanelAsync(), SFB.StandaloneFileBrowser.SaveFilePanel(), SFB.StandaloneFileBrowser.SaveFilePanelAsync(), and SFB.StandaloneFileBrowser.StandaloneFileBrowser().
The documentation for this class was generated from the following file:
Elin/Plugins.basecore/SFB/StandaloneFileBrowser.cs