Elin Decompiled Documentation: TraitNewZone Class Reference
TraitNewZone Class Reference
Public Member Functions
override void OnImportMap ()
virtual Point GetExitPos ()
override void TrySetAct (ActPlan p)
bool CanAutoEnter ()
bool MoveZone (bool confirmed=false)
Zone CreateZone (Zone dest, int destLv)
override void OnStepped (Chara c)
virtual bool TryTeleport ()
virtual bool IsFor (Zone z)
Public Member Functions inherited from Trait
string GetParam (int i, string def=null)
int GetParamInt (int i, int def)
virtual bool Contains (RecipeSource r)
virtual int GetValue ()
virtual bool CanStackTo (Thing to)
virtual string GetHoverText ()
virtual Action GetHealAction (Chara c)
virtual bool CanBlend (Thing t)
virtual void OnBlend (Thing t, Chara c)
virtual int GetActDuration (Chara c)
virtual SourceElement.Row GetRefElement ()
virtual Sprite GetRefSprite ()
virtual void OnRenderExtra (RenderParam p)
virtual Emo2 GetHeldEmo (Chara c)
virtual void SetOwner (Card _owner)
virtual bool IdleUse (Chara c, int dist)
virtual void OnSetOwner ()
virtual void OnImportMap ()
virtual void SetParams (params string[] s)
virtual void OnCrafted (Recipe recipe)
virtual void OnCreate (int lv)
virtual void OnEquip (Chara c, bool onSetOwner)
virtual void OnUnequip (Chara c)
virtual void OnChangePlaceState (PlaceState state)
virtual void OnAddedToZone ()
virtual void OnRemovedFromZone ()
virtual void OnSimulateHour (VirtualDate date)
virtual string GetName ()
virtual void SetName (ref string s)
virtual void OnRenderTile (Point point, HitResult result, int dir)
virtual int CompareTo (Card b)
virtual bool CanBuiltAt (Point p)
virtual void Update ()
Point GetPoint ()
Point GetRandomPoint (Func< Point, bool > func=null, Chara accessChara=null)
virtual List< Point > ListPoints (Point center=null, bool onlyPassable=true)
virtual Recipe GetRecipe ()
virtual Recipe GetBuildModeRecipe ()
virtual bool CanCook (Card c)
void CookProgress ()
virtual bool CanOffer (Card tg)
void OfferProcess (Chara cc)
void Offer (Chara cc)
virtual bool TryProgress (AIProgress p)
virtual LockOpenState TryOpenLock (Chara cc, bool msgFail=true)
virtual void WriteNote (UINote n, bool identified)
int GetSortVal (UIList.SortMode m)
virtual HotItem GetHotItem ()
virtual bool CanRead (Chara c)
virtual void OnRead (Chara c)
virtual bool CanEat (Chara c)
virtual void OnEat (Chara c)
virtual bool CanDrink (Chara c)
virtual void OnDrink (Chara c)
virtual void OnThrowGround (Chara c, Point p)
virtual bool CanUse (Chara c)
virtual bool CanUse (Chara c, Card tg)
virtual bool CanUse (Chara c, Point p)
virtual bool OnUse (Chara c)
virtual bool OnUse (Chara c, Card tg)
virtual bool OnUse (Chara c, Point p)
virtual void TrySetAct (ActPlan p)
virtual void TrySetHeldAct (ActPlan p)
virtual void OnHeld ()
virtual void OnTickHeld ()
virtual void OnSetCurrentItem ()
virtual void OnUnsetCurrentItem ()
virtual bool OnChildDecay (Card c, bool firstDecay)
virtual bool CanChildDecay (Card c)
virtual void OnSetCardGrid (ButtonGrid b)
virtual void OnStepped (Chara c)
virtual void OnSteppedOut (Chara c)
virtual void OnOpenDoor (Chara c)
void Install (bool byPlayer)
void Uninstall ()
virtual void OnInstall (bool byPlayer)
virtual void OnUninstall ()
virtual void TryToggle ()
virtual void Toggle (bool on, bool silent=false)
virtual void PlayToggleEffect (bool silent)
virtual void OnToggle ()
virtual void TrySetToggleAct (ActPlan p)
bool IsFuelEnough (int num=1, List< Thing > excludes=null, bool tryRefuel=true)
bool IsFuel (string s)
bool IsFuel (Thing t)
int GetFuelValue (Thing t)
int GetFuelValue (string id)
void Refuel (Thing t)
void TryRefuel (int dest, List< Thing > excludes)
virtual void OnEnterScreen ()
virtual void RefreshRenderer ()
virtual void SetMainText (UIText t, bool hotitem)
virtual bool CanCopy (Thing t)
string GetTextRestock (string lang, bool pet)
Emo2 GetRestockedIcon ()
void OnBarter ()
Thing CreateStock ()
Properties
Zone zone [get, set]
virtual bool CanUseInTempDungeon [get]
virtual string langOnUse [get]
virtual bool IsUpstairs [get]
virtual bool IsDownstairs [get]
virtual bool IsTeleport [get]
virtual bool OnlyInTheSameTopZone [get]
virtual bool AutoEnter [get]
virtual bool ForceEnter [get]
virtual bool CanToggleAutoEnter [get]
virtual bool CreateExternalZone [get]
virtual ZoneTransition.EnterState enterState [get]
virtual bool IsEntrace [get]
override bool CanBeHeld [get]
override bool CanBeDestroyed [get]
override bool CanBeStolen [get]
virtual int UseDist [get]
Properties inherited from Trait
string[] Params [get]
virtual byte WeightMod [get]
virtual int IdSkin [get]
virtual string Name [get]
virtual TileType tileType [get]
virtual RefCardName RefCardName [get]
virtual bool IsBlockPath [get]
virtual bool IsBlockSight [get]
virtual bool IsDoor [get]
virtual bool IsOpenSight [get]
virtual bool IsOpenPath [get]
virtual bool IsFloating [get]
virtual bool IsGround [get]
virtual bool InvertHeldSprite [get]
virtual bool IsChangeFloorHeight [get]
virtual bool ShouldRefreshTile [get]
virtual bool ShouldTryRefreshRoom [get]
virtual int InstallBottomPriority [get]
virtual bool CanHarvest [get]
virtual int radius [get]
virtual TraitRadiusType radiusType [get]
virtual bool CanUseRoomRadius [get]
virtual int GuidePriotiy [get]
virtual int Electricity [get]
virtual bool IgnoreLastStackHeight [get]
virtual int Decay [get]
virtual int DecaySpeed [get]
virtual int DecaySpeedChild [get]
virtual bool IsFridge [get]
virtual int DefaultStock [get]
virtual bool HoldAsDefaultInteraction [get]
virtual int CraftNum [get]
virtual bool ShowOrbit [get]
virtual bool HaveUpdate [get]
virtual bool IsSpot [get]
virtual bool IsFactory [get]
virtual bool CanAutofire [get]
virtual bool CanName [get]
virtual bool CanPutAway [get]
virtual bool CanChangeHeight [get]
virtual bool CanStack [get]
virtual bool CanCopyInBlueprint [get]
virtual bool CanBeAttacked [get]
virtual bool CanExtendBuild [get]
virtual string langNote [get]
virtual string IDInvStyle [get]
virtual string IDActorEx [get]
virtual bool MaskOnBuild [get]
virtual bool ShowContextOnPick [get]
virtual bool IsThrowMainAction [get]
virtual bool LevelAsQuality [get]
virtual bool UseDummyTile [get]
virtual bool RequireFullStackCheck [get]
virtual bool DisableAutoCombat [get]
virtual InvGridSize InvGridSize [get]
virtual bool IsContainer [get]
virtual bool CanUseContent [get]
virtual bool CanSearchContent [get]
virtual bool CanOpenContainer [get]
virtual bool IsSpecialContainer [get]
virtual ContainerType ContainerType [get]
virtual ThrowType ThrowType [get]
virtual EffectDead EffectDead [get]
virtual bool IsHomeItem [get]
virtual bool IsAltar [get]
virtual bool IsRestSpot [get]
virtual bool CanBeMasked [get]
virtual bool IsBlendBase [get]
virtual bool CanBeOnlyBuiltInHome [get]
virtual bool CanBuildInTown [get]
virtual bool CanBeHeld [get]
virtual bool CanBeStolen [get]
virtual bool CanOnlyCarry [get]
virtual bool CanBeDestroyed [get]
virtual bool CanBeHallucinated [get]
virtual bool CanBeDropped [get]
virtual string ReqHarvest [get]
virtual bool CanBeDisassembled [get]
virtual bool CanBeShipped [get]
virtual bool HasCharges [get]
virtual bool ShowCharges [get]
virtual bool ShowChildrenNumber [get]
virtual bool ShowAsTool [get]
virtual bool CanBeHeldAsFurniture [get]
virtual bool HideInAdv [get]
virtual bool NoHeldDir [get]
virtual bool AlwaysHideOnLowWall [get]
bool ExistsOnMap [get]
virtual bool RenderExtra [get]
virtual float DropChance [get]
virtual string IdNoRestock [get]
virtual int IdleUseChance [get]
virtual string RecipeCat [get]
virtual bool IsTool [get]
virtual string LangUse [get]
virtual bool IsOn [get]
virtual bool IsAnimeOn [get]
bool IsToggle [get]
virtual bool AutoToggle [get]
bool IsLighting [get]
virtual bool IsLightOn [get]
virtual bool IsNightOnlyLight [get]
virtual TileMode tileMode [get]
virtual bool UseAltTiles [get]
virtual bool UseLowblock [get]
virtual bool UseExtra [get]
virtual bool UseLightColor [get]
virtual ? Color ColorExtra [get]
virtual int MaxFuel [get]
virtual int FuelCost [get]
virtual bool ShowFuelWindow [get]
bool IsRequireFuel [get]
string IdToggleExtra [get]
virtual ToggleType ToggleType [get]
virtual int ShopLv [get]
virtual CopyShopType CopyShop [get]
virtual int NumCopyItem [get]
virtual ShopType ShopType [get]
virtual CurrencyType CurrencyType [get]
virtual PriceType PriceType [get]
virtual bool AllowSell [get]
virtual int CostRerollShop [get]
virtual bool AllowCriminal [get]
virtual int RestockDay [get]
virtual SlaverType SlaverType [get]
virtual string LangBarter [get]
string TextNextRestock [get]
string TextNextRestockPet [get]
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Additional Inherited Members
Public Types inherited from Trait
enum TileMode {
Default , Door , Illumination , DefaultNoAnime ,
SignalAnime
}
enum CopyShopType { None , Item , Spellbook }
Static Public Member Functions inherited from EClass
static int rnd (int a)
static int curve (int a, int start, int step, int rate=75)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Public Attributes inherited from Trait
Card owner
Static Public Attributes inherited from Trait
static TraitSelfFactory SelfFactory = new TraitSelfFactory()
Static Public Attributes inherited from EClass
static Core core
Static Protected Attributes inherited from Trait
static List< Point > listRadiusPoints = new List<Point>()
Detailed Description
Definition at line 3 of file TraitNewZone.cs.
Member Function Documentation
CanAutoEnter()
bool TraitNewZone.CanAutoEnter () inline
Definition at line 125 of file TraitNewZone.cs.
    {
        if (!EClass._zone.AllowNewZone)
        {
            return false;
        }
        if (owner.sourceRenderCard.multisize)
        {
            return false;
        }
        if (EClass.pc.held != null && EClass.pc.held.trait.CanOnlyCarry)
        {
            return false;
        }
        return true;
    }
References EClass._zone, Zone.AllowNewZone, Trait.CanOnlyCarry, Chara.held, RenderRow.multisize, Trait.owner, EClass.pc, Card.sourceRenderCard, and Card.trait.
Referenced by AM_Adv._OnUpdateInput().
CreateZone()
Zone TraitNewZone.CreateZone (Zone dest, int destLv) inline
Definition at line 238 of file TraitNewZone.cs.
    {
        string text = dest.GetNewZoneID(destLv);
        if (CreateExternalZone)
        {
            text = owner.GetStr(30) ?? GetParam(1);
        }
        Debug.Log("Creating:" + text + "/" + destLv + "/" + EClass.sources.zones.map.ContainsKey(text) + "/" + dest);
        Zone zone = SpatialGen.Create(text, dest, register: true, owner.pos.x, owner.pos.z) as Zone;
        zone.lv = destLv;
        zone.x = dest.x;
        zone.y = dest.y;
        owner.c_uidZone = zone.uid;
        if (CreateExternalZone)
        {
            zone.isExternalZone = true;
        }
        Debug.Log("Created:" + zone.Name + "/" + zone.id);
        return zone;
    }
References SpatialGen.Create(), CreateExternalZone, Debug, Zone.GetNewZoneID(), Trait.GetParam(), BaseCard.GetStr(), Spatial.id, Spatial.Name, Trait.owner, Card.pos, EClass.sources, Spatial.uid, Point.x, Spatial.x, Spatial.y, Point.z, zone, and SourceManager.zones.
Referenced by MoveZone().
GetExitPos()
virtual Point TraitNewZone.GetExitPos () inline virtual
Reimplemented in TraitStairs.
Definition at line 78 of file TraitNewZone.cs.
    {
        Point point = new Point(owner.pos);
        if (owner.dir % 2 == 0)
        {
            point.x -= owner.sourceCard.W / 2;
            point.z--;
        }
        else
        {
            point.x++;
            point.z += owner.sourceCard.H / 2;
        }
        return point;
    }
References Card.dir, Trait.owner, Card.pos, Point.x, and Point.z.
IsFor()
virtual bool TraitNewZone.IsFor (Zone z) inline virtual
Definition at line 277 of file TraitNewZone.cs.
    {
        if (z == zone)
        {
            return true;
        }
        string param = GetParam(1);
        if (!param.IsEmpty())
        {
            int num = ((GetParam(2) != null) ? GetParam(2).ToInt() : 0);
            if (z.id == param && z.lv == num)
            {
                return true;
            }
        }
        return false;
    }
References Trait.GetParam(), Spatial.id, Spatial.lv, and zone.
Referenced by Zone.GetSpawnPos().
MoveZone()
bool TraitNewZone.MoveZone (bool confirmed = false) inline
Definition at line 142 of file TraitNewZone.cs.
    {
        if (Electricity != 0 && !owner.isOn)
        {
            owner.PlaySound("electricity_insufficient");
            return false;
        }
        if (TryTeleport())
        {
            return true;
        }
        if (!confirmed && EClass._zone.IsNefia && EClass._zone.Boss != null)
        {
            EClass.pc.ai.Cancel();
            EInput.Consume(consumeAxis: true);
            Dialog.YesNo("ExitZoneBoss".lang(EClass._zone.Name), delegate
            {
                MoveZone(confirmed: true);
            });
            return false;
        }
        ZoneTransition transition = new ZoneTransition
        {
            state = enterState,
            idTele = GetParam(3)
        };
        Zone zone = null;
        int num = GetParam(2)?.ToInt() ?? 0;
        if (OnlyInTheSameTopZone && this.zone != null && this.zone.GetTopZone() != EClass._zone.GetTopZone())
        {
            this.zone = null;
        }
        if (this.zone == null)
        {
            if (CreateExternalZone)
            {
                zone = EClass._zone;
            }
            else if (IsTeleport)
            {
                zone = EClass.world.region.FindZone(GetParam(1));
                if (zone != null)
                {
                    zone = zone.GetTopZone();
                    this.zone = zone.FindZone(num);
                }
            }
            else if (IsDownstairs || IsUpstairs)
            {
                zone = EClass._zone.GetTopZone();
                num = EClass._zone.lv + (IsUpstairs ? 1 : (IsDownstairs ? (-1) : 0));
                this.zone = EClass._zone.GetTopZone().FindZone(num);
                if (this.zone == null && EClass._zone.parent.IsRegion && ((IsUpstairs && EClass._zone.lv == -1) || (IsDownstairs && EClass._zone.lv == 1)))
                {
                    EClass.pc.MoveZone(EClass._zone.parent as Zone);
                    return false;
                }
            }
            if (OnlyInTheSameTopZone && this.zone != null && this.zone.GetTopZone() != EClass._zone.GetTopZone())
            {
                this.zone = null;
            }
            if (this.zone == null)
            {
                if (OnlyInTheSameTopZone && zone != null && zone.GetTopZone() != EClass._zone.GetTopZone())
                {
                    zone = null;
                }
                if (zone == null || EClass._zone.isExternalZone)
                {
                    Msg.SayNothingHappen();
                    return false;
                }
                CreateZone(zone, num);
            }
        }
        if ((IsDownstairs || IsUpstairs) && this.zone.IDGenerator == null && EClass._zone.IDGenerator == null)
        {
            this.zone.events.AddPreEnter(new ZonePreEnterDigStairs
            {
                pos = owner.pos.Copy(),
                fromAbove = IsDownstairs,
                uidZone = EClass._zone.uid
            });
            transition = new ZoneTransition
            {
                state = ZoneTransition.EnterState.UndergroundOrSky,
                x = owner.pos.x,
                z = owner.pos.z
            };
        }
        Debug.Log(this.zone);
        EClass.pc.MoveZone(this.zone, transition);
        return true;
    }
References EClass._zone, ZoneEventManager.AddPreEnter(), Chara.ai, Zone.Boss, AIAct.Cancel(), EInput.Consume(), Point.Copy(), CreateExternalZone, CreateZone(), Debug, Trait.Electricity, enterState, Zone.events, Spatial.FindZone(), Trait.GetParam(), Zone.GetTopZone(), Zone.IDGenerator, IsDownstairs, Spatial.isExternalZone, Zone.IsNefia, Card.isOn, Spatial.IsRegion, IsTeleport, IsUpstairs, Spatial.lv, Chara.MoveZone(), Spatial.Name, OnlyInTheSameTopZone, Trait.owner, Spatial.parent, EClass.pc, Card.PlaySound(), Card.pos, World.region, Msg.SayNothingHappen(), TryTeleport(), Spatial.uid, EClass.world, Point.x, Dialog.YesNo(), and zone.
Referenced by AM_Adv._OnUpdateInput(), OnStepped(), TrySetAct(), and CoreDebug.UpdateInput().
OnImportMap()
override void TraitNewZone.OnImportMap () inline virtual
Reimplemented from Trait.
Definition at line 73 of file TraitNewZone.cs.
    {
        owner.c_uidZone = 0;
    }
OnStepped()
override void TraitNewZone.OnStepped (Chara c) inline virtual
Reimplemented from Trait.
Definition at line 259 of file TraitNewZone.cs.
    {
        if (AutoEnter && c.IsPC && owner.IsInstalled && c.IsAliveInCurrentZone && (ForceEnter || !EClass.core.config.game.disableAutoStairs))
        {
            Debug.Log("OnStepped:" + EClass.pc.ai);
            AI_Goto aI_Goto = EClass.pc.ai.Current as AI_Goto;
            if ((aI_Goto != null || EClass.pc.ai is GoalManualMove) && (aI_Goto == null || aI_Goto.dest.Equals(owner.pos)))
            {
                MoveZone();
            }
        }
    }
References Chara.ai, AutoEnter, Core.config, EClass.core, Debug, AI_Goto.dest, CoreConfig.GameConfig.disableAutoStairs, Point.Equals(), ForceEnter, CoreConfig.game, Chara.IsAliveInCurrentZone, Card.IsInstalled, Chara.IsPC, MoveZone(), Trait.owner, EClass.pc, and Card.pos.
TrySetAct()
override void TraitNewZone.TrySetAct (ActPlan p) inline virtual
Reimplemented from Trait.
Reimplemented in TraitTeleporter.
Definition at line 94 of file TraitNewZone.cs.
    {
        if (!EClass._zone.AllowNewZone)
        {
            return;
        }
        bool flag = IsEntrace || p.IsSelf;
        if (owner.sourceRenderCard.multisize)
        {
            int x = p.pos.x;
            int z = p.pos.z;
            int w = owner.W;
            int h = owner.H;
            flag = ((owner.dir % 2 != 0) ? (p.pos.x == owner.pos.x && p.pos.z >= owner.pos.z + 1 && p.pos.z < owner.pos.z + h - 1) : (z == owner.pos.z && x > owner.pos.x - w + 1 && x <= owner.pos.x - 1));
        }
        if (!flag || (EClass.pc.held != null && EClass.pc.held.trait.CanOnlyCarry) || p.dist > UseDist)
        {
            return;
        }
        p.TrySetAct("actNewZone", delegate
        {
            if ((EClass._zone.RegenerateOnEnter || EClass._zone.IsInstance) && !CanUseInTempDungeon)
            {
                Msg.Say("badidea");
                return false;
            }
            MoveZone();
            return false;
        }, owner, CursorSystem.MoveZone);
    }
References EClass._zone, Zone.AllowNewZone, Trait.CanOnlyCarry, CanUseInTempDungeon, Card.H, Chara.held, IsEntrace, Zone.IsInstance, ActPlan.IsSelf, CursorSystem.MoveZone, MoveZone(), RenderRow.multisize, Trait.owner, EClass.pc, ActPlan.pos, Card.pos, Zone.RegenerateOnEnter, Msg.Say(), Card.sourceRenderCard, Card.trait, ActPlan.TrySetAct(), UseDist, Card.W, Point.x, and Point.z.
TryTeleport()
virtual bool TraitNewZone.TryTeleport () inline virtual
Reimplemented in TraitTeleporter.
Definition at line 272 of file TraitNewZone.cs.
    {
        return false;
    }
Referenced by MoveZone().
Property Documentation
AutoEnter
virtual bool TraitNewZone.AutoEnter get
Definition at line 29 of file TraitNewZone.cs.
Referenced by OnStepped().
CanBeDestroyed
override bool TraitNewZone.CanBeDestroyed get
Definition at line 67 of file TraitNewZone.cs.
CanBeHeld
override bool TraitNewZone.CanBeHeld get
Definition at line 65 of file TraitNewZone.cs.
CanBeStolen
override bool TraitNewZone.CanBeStolen get
Definition at line 69 of file TraitNewZone.cs.
CanToggleAutoEnter
virtual bool TraitNewZone.CanToggleAutoEnter get
Definition at line 33 of file TraitNewZone.cs.
CanUseInTempDungeon
virtual bool TraitNewZone.CanUseInTempDungeon get
Definition at line 17 of file TraitNewZone.cs.
Referenced by TrySetAct().
CreateExternalZone
virtual bool TraitNewZone.CreateExternalZone get
Definition at line 35 of file TraitNewZone.cs.
    {
        get
        {
            if (!IsTeleport)
            {
                if (owner.GetStr(30) == null)
                {
                    return GetParam(1) != null;
                }
                return true;
            }
            return false;
        }
    }
Referenced by CreateZone(), and MoveZone().
enterState
virtual ZoneTransition.EnterState TraitNewZone.enterState get
Definition at line 51 of file TraitNewZone.cs.
Referenced by MoveZone().
ForceEnter
virtual bool TraitNewZone.ForceEnter get
Definition at line 31 of file TraitNewZone.cs.
Referenced by OnStepped().
IsDownstairs
virtual bool TraitNewZone.IsDownstairs get
Definition at line 23 of file TraitNewZone.cs.
Referenced by MoveZone().
IsEntrace
virtual bool TraitNewZone.IsEntrace get
Definition at line 53 of file TraitNewZone.cs.
    {
        get
        {
            if (!IsUpstairs)
            {
                return !IsDownstairs;
            }
            return false;
        }
    }
Referenced by TrySetAct().
IsTeleport
virtual bool TraitNewZone.IsTeleport get
Definition at line 25 of file TraitNewZone.cs.
Referenced by MoveZone().
IsUpstairs
virtual bool TraitNewZone.IsUpstairs get
Definition at line 21 of file TraitNewZone.cs.
Referenced by MoveZone().
langOnUse
virtual string TraitNewZone.langOnUse get
Definition at line 19 of file TraitNewZone.cs.
OnlyInTheSameTopZone
virtual bool TraitNewZone.OnlyInTheSameTopZone get
Definition at line 27 of file TraitNewZone.cs.
Referenced by MoveZone().
UseDist
virtual int TraitNewZone.UseDist get
Definition at line 71 of file TraitNewZone.cs.
Referenced by TrySetAct().
zone
Zone TraitNewZone.zone get set
Definition at line 5 of file TraitNewZone.cs.
    {
        get
        {
            return RefZone.Get(owner.c_uidZone);
        }
        set
        {
            owner.c_uidZone = value?.uid ?? 0;
        }
    }
Referenced by CreateZone(), Zone.GetSpawnPos(), IsFor(), MoveZone(), and TraitTeleporter.TryTeleport().
The documentation for this class was generated from the following file:
Elin/TraitNewZone.cs