Elin Decompiled Documentation: SourceCategory.Row Class Reference
SourceCategory.Row Class Reference
Public Member Functions
bool IsChildOf (string id)
bool IsChildOf (Row r)
bool IsChildOf (int _uid)
bool Contatin (int _uid)
Row GetRoot ()
Row GetSecondRoot ()
string GetIdThing ()
Public Attributes
string id
int uid
string name_JP
string name
string _parent
string recipeCat
int slot
int skill
int maxStack
int tileDummy
bool installOne
int ignoreBless
string[] tag
string idThing
string[] recycle
int costSP
int gift
int deliver
int offer
int ticket
int sortVal
int flag
Row parent
List< Row > children
string name_L
Properties
override bool UseAlias [get]
override string GetAlias [get]
Detailed Description
Definition at line 7 of file SourceCategory.cs.
Member Function Documentation
Contatin()
bool SourceCategory.Row.Contatin (int _uid) inline
Definition at line 97 of file SourceCategory.cs.
        {
            if (uid == _uid)
            {
                return true;
            }
            foreach (Row child in children)
            {
                if (child.Contatin(_uid))
                {
                    return true;
                }
            }
            return false;
        }
References SourceCategory.Row.children, SourceCategory.Row.Contatin(), and SourceCategory.Row.uid.
Referenced by SourceCategory.Row.Contatin(), and UIDistribution.Refresh().
GetIdThing()
string SourceCategory.Row.GetIdThing () inline
Definition at line 131 of file SourceCategory.cs.
        {
            if (!idThing.IsEmpty())
            {
                return idThing;
            }
            return parent.GetIdThing();
        }
References SourceCategory.Row.GetIdThing(), SourceCategory.Row.idThing, and SourceCategory.Row.parent.
Referenced by SourceCategory.Row.GetIdThing().
GetRoot()
Row SourceCategory.Row.GetRoot () inline
Definition at line 113 of file SourceCategory.cs.
        {
            if (parent == null)
            {
                return this;
            }
            return parent.GetRoot();
        }
References SourceCategory.Row.GetRoot(), and SourceCategory.Row.parent.
Referenced by SourceCategory.Row.GetRoot().
GetSecondRoot()
Row SourceCategory.Row.GetSecondRoot () inline
Definition at line 122 of file SourceCategory.cs.
        {
            if (parent == null || parent.parent == null)
            {
                return this;
            }
            return parent.GetSecondRoot();
        }
References SourceCategory.Row.GetSecondRoot(), and SourceCategory.Row.parent.
Referenced by SourceCategory.Row.GetSecondRoot().
IsChildOf() [1/3]
bool SourceCategory.Row.IsChildOf (int _uid) inline
Definition at line 84 of file SourceCategory.cs.
        {
            if (uid == _uid)
            {
                return true;
            }
            if (parent != null)
            {
                return parent.IsChildOf(_uid);
            }
            return false;
        }
References SourceCategory.Row.IsChildOf(), SourceCategory.Row.parent, and SourceCategory.Row.uid.
IsChildOf() [2/3]
bool SourceCategory.Row.IsChildOf (Row r) inline
Definition at line 71 of file SourceCategory.cs.
        {
            if (r == this)
            {
                return true;
            }
            if (parent != null)
            {
                return parent.IsChildOf(r);
            }
            return false;
        }
References SourceCategory.Row.IsChildOf(), and SourceCategory.Row.parent.
IsChildOf() [3/3]
bool SourceCategory.Row.IsChildOf (string id) inline
Definition at line 66 of file SourceCategory.cs.
        {
            return IsChildOf(EClass.sources.categories.map[id]);
        }
References SourceManager.categories, SourceCategory.Row.IsChildOf(), and EClass.sources.
Referenced by Card.Decay(), Card.GetPrice(), SourceCategory.Row.IsChildOf(), Card.MakeFoodFrom(), UIDistribution.Refresh(), and LayerCraft.RefreshCategory().
Member Data Documentation
_parent
string SourceCategory.Row._parent
Definition at line 17 of file SourceCategory.cs.
Referenced by SourceCategory.OnInit().
children
List<Row> SourceCategory.Row.children
Definition at line 57 of file SourceCategory.cs.
Referenced by SourceCategory.Row.Contatin(), UIDistribution.Refresh(), and LayerDistribution.SetContainer().
costSP
int SourceCategory.Row.costSP
Definition at line 39 of file SourceCategory.cs.
deliver
int SourceCategory.Row.deliver
Definition at line 43 of file SourceCategory.cs.
flag
int SourceCategory.Row.flag
Definition at line 51 of file SourceCategory.cs.
Referenced by UIInventory.ShowDistribution().
gift
int SourceCategory.Row.gift
Definition at line 41 of file SourceCategory.cs.
id
string SourceCategory.Row.id
Definition at line 9 of file SourceCategory.cs.
Referenced by Card.GetPrice(), Props.ListThingStack(), LayerCraft.RefreshCategory(), QuestDeliver.SetIdThing(), and SourceCategory.SetRow().
idThing
string SourceCategory.Row.idThing
Definition at line 35 of file SourceCategory.cs.
Referenced by SourceCategory.Row.GetIdThing().
ignoreBless
int SourceCategory.Row.ignoreBless
Definition at line 31 of file SourceCategory.cs.
installOne
bool SourceCategory.Row.installOne
Definition at line 29 of file SourceCategory.cs.
maxStack
int SourceCategory.Row.maxStack
Definition at line 25 of file SourceCategory.cs.
name
string SourceCategory.Row.name
Definition at line 15 of file SourceCategory.cs.
name_JP
string SourceCategory.Row.name_JP
Definition at line 13 of file SourceCategory.cs.
name_L
string SourceCategory.Row.name_L
Definition at line 60 of file SourceCategory.cs.
offer
int SourceCategory.Row.offer
Definition at line 45 of file SourceCategory.cs.
parent
Row SourceCategory.Row.parent
Definition at line 54 of file SourceCategory.cs.
Referenced by SourceCategory.Row.GetIdThing(), SourceCategory.Row.GetRoot(), SourceCategory.Row.GetSecondRoot(), and SourceCategory.Row.IsChildOf().
recipeCat
string SourceCategory.Row.recipeCat
Definition at line 19 of file SourceCategory.cs.
recycle
string [] SourceCategory.Row.recycle
Definition at line 37 of file SourceCategory.cs.
skill
int SourceCategory.Row.skill
Definition at line 23 of file SourceCategory.cs.
slot
int SourceCategory.Row.slot
Definition at line 21 of file SourceCategory.cs.
sortVal
int SourceCategory.Row.sortVal
Definition at line 49 of file SourceCategory.cs.
Referenced by Card.SetSortVal().
tag
string [] SourceCategory.Row.tag
Definition at line 33 of file SourceCategory.cs.
Referenced by Card.GetValue().
ticket
int SourceCategory.Row.ticket
Definition at line 47 of file SourceCategory.cs.
tileDummy
int SourceCategory.Row.tileDummy
Definition at line 27 of file SourceCategory.cs.
uid
int SourceCategory.Row.uid
Definition at line 11 of file SourceCategory.cs.
Referenced by SourceCategory.Row.Contatin(), and SourceCategory.Row.IsChildOf().
Property Documentation
GetAlias
override string SourceCategory.Row.GetAlias get
Definition at line 64 of file SourceCategory.cs.
UseAlias
override bool SourceCategory.Row.UseAlias get
Definition at line 62 of file SourceCategory.cs.
The documentation for this class was generated from the following file:
Elin/SourceCategory.cs