Elin Decompiled Documentation: BaseCondition Class Reference
BaseCondition Class Reference
Public Member Functions
virtual bool CanStack (Condition c)
virtual bool TryMove (Point p)
void SetElement (int id)
void SetRefVal (int a, int b)
virtual Color GetSpriteColor ()
override string ToString ()
override string GetText ()
override int GetValue ()
override Color GetColor (Gradient g)
virtual void SetOwner (Chara _owner, bool onDeserialize=false)
SourceElement.Row GetElementSource (int i)
void Start ()
bool TryNullify (Condition c)
virtual void OnBeforeStart ()
virtual void OnStart ()
virtual void OnStartOrStack ()
virtual void PlayEffect ()
virtual void PlayEndEffect ()
virtual void OnRefresh ()
void SetPhase ()
bool IsNullPhase ()
override int GetPhase ()
void PhaseMsg (bool inc)
override string GetPhaseStr ()
virtual void Tick ()
void Mod (int a, bool force=false)
virtual void OnValueChanged ()
virtual void OnChangePhase (int lastPhase, int newPhase)
virtual void OnRemoved ()
virtual int EvaluatePower (int p)
virtual int EvaluateTurn (int p)
virtual BaseNotification CreateNotification ()
Element GetDefenseAttribute (Chara c=null)
override void _WriteNote (UINote n, bool asChild=false)
virtual void OnWriteNote (List< string > list)
virtual RendererReplacer GetRendererReplacer ()
Public Member Functions inherited from BaseStats
virtual Color GetColor (Gradient gradient)
virtual Color GetColor (SkinColorProfile c)
Color GetColor ()
virtual string GetText ()
virtual string GetPhaseStr ()
virtual int GetValue ()
virtual Sprite GetSprite ()
virtual void SetText (UIText t, SkinColorProfile cols=null)
virtual int GetPhase ()
void PopText ()
virtual void WriteNote (UINote n, Action< UINote > onWriteNote=null)
virtual void _WriteNote (UINote n, bool asChild=false)
Public Attributes
int[] _ints = new int[5]
int phase = -1
ElementContainer elements
Chara owner
Public Attributes inherited from BaseStats
int id
SourceStat.Row _source
Properties
int value [get, set]
int power [get, set]
int refVal [get, set]
int refVal2 [get, set]
bool givenByPcParty [get, set]
bool isPerfume [get, set]
override Chara Owner [get]
virtual string Name [get]
virtual bool IsToggle [get]
virtual bool WillOverride [get]
virtual bool AllowMultipleInstance [get]
virtual bool ConsumeTurn [get]
virtual bool PreventRegen [get]
virtual bool ShouldRefresh [get]
virtual bool CancelAI [get]
virtual bool TimeBased [get]
virtual bool SyncRide [get]
virtual bool UseElements [get]
virtual int GainResistFactor [get]
virtual int P2 [get]
SourceElement.Row sourceElement [get]
virtual bool IsElemental [get]
virtual string RefString1 [get]
virtual bool CanManualRemove [get]
Properties inherited from BaseStats
SourceStat.Row source [get]
virtual Emo2 EmoIcon [get]
virtual ConditionType Type [get]
virtual string idSprite [get]
virtual bool ShowInWidget [get]
virtual Chara Owner [get]
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Additional Inherited Members
Static Public Member Functions inherited from EClass
static int rnd (int a)
static int curve (int a, int start, int step, int rate=75)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Static Public Attributes inherited from BaseStats
static Chara CC
Static Public Attributes inherited from EClass
static Core core
Detailed Description
Definition at line 6 of file BaseCondition.cs.
Member Function Documentation
_WriteNote()
override void BaseCondition._WriteNote (UINote n, bool asChild = false) inline virtual
Reimplemented from BaseStats.
Definition at line 421 of file BaseCondition.cs.
    {
        List<string> list = new List<string>();
        Element defenseAttribute = GetDefenseAttribute();
        if (defenseAttribute != null)
        {
            list.Add("hintDefenseAttb".lang(defenseAttribute.Name.ToTitleCase()));
        }
        OnWriteNote(list);
        string[] nullify = base.source.nullify;
        foreach (string key in nullify)
        {
            list.Add("hintNullify".lang(EClass.sources.stats.alias[key].GetName()));
        }
        for (int j = 0; j < base.source.elements.Length; j += 2)
        {
            Element element = Element.Create(GetElementSource(j).id, base.source.elements[j + 1].Calc(power, 0, P2));
            list.Add("modValue".lang(element.Name, ((element.Value < 0) ? "" : "+") + element.Value));
        }
        if (list.Count <= 0)
        {
            return;
        }
        if (!asChild)
        {
            n.Space(8);
        }
        foreach (string item in list)
        {
            n.AddText("_bullet".lang() + item);
        }
    }
References Element.Create(), GetDefenseAttribute(), GetElementSource(), item, Element.Name, OnWriteNote(), P2, power, EClass.sources, SourceManager.stats, and Element.Value.
Referenced by Element._WriteNote().
CanStack()
virtual bool BaseCondition.CanStack (Condition c) inline virtual
Reimplemented in ConBuffStats, ConWrath, and TimeDebuff.
Definition at line 135 of file BaseCondition.cs.
    {
        return true;
    }
CreateNotification()
virtual BaseNotification BaseCondition.CreateNotification () inline virtual
Reimplemented in BaseDebuff, BaseStance, and Condition.
Definition at line 403 of file BaseCondition.cs.
    {
        return new BaseNotification();
    }
EvaluatePower()
virtual int BaseCondition.EvaluatePower (int p) inline virtual
Definition at line 393 of file BaseCondition.cs.
    {
        return p;
    }
Referenced by Chara.AddCondition().
EvaluateTurn()
virtual int BaseCondition.EvaluateTurn (int p) inline virtual
Reimplemented in ConBuffStats.
Definition at line 398 of file BaseCondition.cs.
    {
        return Mathf.Max(1, base.source.duration.Calc(p, 0, P2));
    }
References P2.
Referenced by Element._WriteNote(), and Condition.OnStacked().
GetColor()
override Color BaseCondition.GetColor (Gradient g) inline virtual
Reimplemented from BaseStats.
Definition at line 184 of file BaseCondition.cs.
    {
        return g.Evaluate((base.source.phase.LastItem() == 0) ? 0f : ((float)phase / (float)base.source.phase.LastItem()));
    }
References phase.
Referenced by NotificationCondition.OnRefresh().
GetDefenseAttribute()
Element BaseCondition.GetDefenseAttribute (Chara c = null) inline
Definition at line 408 of file BaseCondition.cs.
    {
        if (base.source.defenseAttb.IsEmpty())
        {
            return null;
        }
        if (c == null)
        {
            return Element.Create(base.source.defenseAttb[0]);
        }
        return c.elements.GetOrCreateElement(base.source.defenseAttb[0]);
    }
References Element.Create().
Referenced by _WriteNote(), and Chara.AddCondition().
GetElementSource()
SourceElement.Row BaseCondition.GetElementSource (int i) inline
Definition at line 215 of file BaseCondition.cs.
    {
        string text = base.source.elements[i];
        if (text == "res")
        {
            text = sourceElement.aliasRef;
        }
        else if (text == "ele")
        {
            text = sourceElement.alias;
        }
        return EClass.sources.elements.alias[text];
    }
References SourceManager.elements, sourceElement, and EClass.sources.
Referenced by _WriteNote(), and SetOwner().
GetPhase()
override int BaseCondition.GetPhase () inline virtual
Reimplemented from BaseStats.
Reimplemented in BaseDebuff, BaseStance, ConAnorexia, ConBlind, ConBuffStats, ConBurning, ConConfuse, ConDrug, ConDrunk, ConEntangle, ConFaint, ConFear, ConGravity, ConParalyze, ConReload, ConSleep, ConSuffocation, ConSuspend, ConWait, ConWet, and ConWrath.
Definition at line 329 of file BaseCondition.cs.
    {
        return base.source.phase[Mathf.Clamp(value, 0, 99) / 10];
    }
References value.
Referenced by IsNullPhase(), SetOwner(), and SetPhase().
GetPhaseStr()
override string BaseCondition.GetPhaseStr () inline virtual
Reimplemented from BaseStats.
Reimplemented in ConBuffStats.
Definition at line 357 of file BaseCondition.cs.
    {
        string[] textArray = base.source.GetTextArray("strPhase");
        if (textArray.Length == 0)
        {
            return Name;
        }
        return textArray[phase].IsEmpty("");
    }
References Name, and phase.
Referenced by GetText().
GetRendererReplacer()
virtual RendererReplacer BaseCondition.GetRendererReplacer () inline virtual
Reimplemented in ConBoost, ConTransmuteBroom, and ConTransmutePutit.
Definition at line 458 of file BaseCondition.cs.
    {
        return null;
    }
Referenced by Chara._CreateRenderer().
GetSpriteColor()
virtual Color BaseCondition.GetSpriteColor () inline virtual
Definition at line 156 of file BaseCondition.cs.
    {
        if (!IsElemental)
        {
            return Color.white;
        }
        return EClass.setting.elements[EClass.sources.elements.map[refVal].alias].colorSprite;
    }
References Color, GameSetting.elements, SourceManager.elements, IsElemental, refVal, EClass.setting, and EClass.sources.
Referenced by NotificationBuff.OnInstantiate().
GetText()
override string BaseCondition.GetText () inline virtual
Reimplemented from BaseStats.
Reimplemented in ConBuffStats.
Definition at line 170 of file BaseCondition.cs.
    {
        if (!IsNullPhase())
        {
            return GetPhaseStr();
        }
        return "";
    }
References GetPhaseStr(), and IsNullPhase().
Referenced by NotificationBuff.OnRefresh(), and NotificationCondition.OnRefresh().
GetValue()
override int BaseCondition.GetValue () inline virtual
Reimplemented from BaseStats.
Definition at line 179 of file BaseCondition.cs.
    {
        return value;
    }
References value.
IsNullPhase()
bool BaseCondition.IsNullPhase () inline
Definition at line 320 of file BaseCondition.cs.
    {
        if (base.source.strPhase.Length == 0)
        {
            return false;
        }
        return base.source.strPhase[GetPhase()] == "#";
    }
References GetPhase().
Referenced by GetText().
Mod()
void BaseCondition.Mod (int a, bool force = false) inline
Definition at line 371 of file BaseCondition.cs.
    {
        if ((!isPerfume || force) && value != 0)
        {
            value += a;
            SetPhase();
            OnValueChanged();
        }
    }
References isPerfume, OnValueChanged(), SetPhase(), and value.
Referenced by Chara.Cure(), Card.DamageHP(), AttackProcess.Perform(), ConBleed.Tick(), ConBurning.Tick(), ConChampagne.Tick(), ConDeathSentense.Tick(), ConDisease.Tick(), Condition.Tick(), ConDrunk.Tick(), ConFear.Tick(), ConHOT.Tick(), ConInsane.Tick(), ConMiasma.Tick(), ConPoison.Tick(), ConSleep.Tick(), ConSuffocation.Tick(), and ConWet.Tick().
OnBeforeStart()
virtual void BaseCondition.OnBeforeStart () inline virtual
Reimplemented in ConSleep.
Definition at line 268 of file BaseCondition.cs.
    {
    }
Referenced by Start().
OnChangePhase()
virtual void BaseCondition.OnChangePhase (int lastPhase, int newPhase) inline virtual
Reimplemented in ConFreeze, and ConPoison.
Definition at line 385 of file BaseCondition.cs.
    {
    }
Referenced by SetOwner(), and SetPhase().
OnRefresh()
virtual void BaseCondition.OnRefresh () inline virtual
Reimplemented in ConExcommunication, ConGravity, ConInvisibility, ConLevitate, ConSeeInvisible, ConTelepathy, and ConWet.
Definition at line 304 of file BaseCondition.cs.
    {
    }
Referenced by Chara.Refresh().
OnRemoved()
virtual void BaseCondition.OnRemoved () inline virtual
Reimplemented in ConBlind, ConBoost, ConConfuse, ConDisease, ConDrunk, ConExcommunication, ConFaint, ConHallucination, ConIncognito, ConNightVision, ConParalyze, ConReload, ConSleep, ConSuspend, ConTorch, ConTransmute, and ConWrath.
Definition at line 389 of file BaseCondition.cs.
    {
    }
Referenced by Condition.Kill().
OnStart()
virtual void BaseCondition.OnStart () inline virtual
Reimplemented in ConBandage, ConBlind, ConBoost, ConDrunk, ConIncognito, ConSuffocation, ConTorch, and ConTransmute.
Definition at line 272 of file BaseCondition.cs.
    {
    }
Referenced by Start().
OnStartOrStack()
virtual void BaseCondition.OnStartOrStack () inline virtual
Reimplemented in ConNightVision.
Definition at line 276 of file BaseCondition.cs.
    {
    }
Referenced by Start().
OnValueChanged()
virtual void BaseCondition.OnValueChanged () inline virtual
Reimplemented in Condition.
Definition at line 381 of file BaseCondition.cs.
    {
    }
Referenced by Mod().
OnWriteNote()
virtual void BaseCondition.OnWriteNote (List< string > list) inline virtual
Reimplemented in ConBuffStats, ConHOT, ConMiasma, and ConStrife.
Definition at line 454 of file BaseCondition.cs.
    {
    }
Referenced by _WriteNote().
PhaseMsg()
void BaseCondition.PhaseMsg (bool inc) inline
Definition at line 334 of file BaseCondition.cs.
    {
        bool flag = (base.source.invert ? (!inc) : inc);
        string[] array = (inc ? base.source.GetText("textPhase") : base.source.GetText("textPhase2")).Split(Environment.NewLine.ToCharArray());
        if (array.Length > phase && !array[phase].IsEmpty())
        {
            if (Type == ConditionType.Stance)
            {
                Msg.SetColor("ono");
            }
            else if (!base.source.invert && flag)
            {
                Msg.SetColor("negative");
            }
            else if (base.source.invert && !flag)
            {
                Msg.SetColor("positive");
            }
            PopText();
            owner.Say(array[phase].Split('|').RandomItem(), owner, RefString1);
        }
    }
References owner, phase, BaseStats.PopText(), RefString1, Card.Say(), Msg.SetColor(), and BaseStats.Type.
Referenced by SetPhase().
PlayEffect()
virtual void BaseCondition.PlayEffect () inline virtual
Reimplemented in ConBuffStats.
Definition at line 280 of file BaseCondition.cs.
    {
        if (!Condition.ignoreEffect && base.source.effect.Length != 0)
        {
            if (!base.source.effect[0].IsEmpty())
            {
                owner.PlayEffect(base.source.effect[0]);
            }
            owner.PlaySound((base.source.effect.Length >= 2) ? base.source.effect[1] : base.source.effect[0]);
        }
    }
References Condition.ignoreEffect, owner, Card.PlayEffect(), and Card.PlaySound().
Referenced by Start().
PlayEndEffect()
virtual void BaseCondition.PlayEndEffect () inline virtual
Definition at line 292 of file BaseCondition.cs.
    {
        if (base.source.effect.Length >= 3)
        {
            if (!base.source.effect[2].IsEmpty())
            {
                owner.PlayEffect(base.source.effect[2]);
            }
            owner.PlaySound((base.source.effect.Length >= 4) ? base.source.effect[3] : base.source.effect[2]);
        }
    }
References owner, Card.PlayEffect(), and Card.PlaySound().
Referenced by Condition.Kill().
SetElement()
void BaseCondition.SetElement (int id) inline
Definition at line 145 of file BaseCondition.cs.
    {
        refVal = id;
    }
References BaseStats.id, and refVal.
Referenced by Element._WriteNote(), and ConMiasma.Tick().
SetOwner()
virtual void BaseCondition.SetOwner (Chara _owner, bool onDeserialize = false) inline virtual
Reimplemented in ConBlind, ConBuffStats, ConConfuse, ConDisease, ConDrunk, ConFaint, ConHallucination, ConParalyze, ConSleep, and ConSuspend.
Definition at line 189 of file BaseCondition.cs.
    {
        owner = _owner;
        phase = GetPhase();
        if (EmoIcon > owner.emoIcon)
        {
            owner.emoIcon = EmoIcon;
        }
        if (UseElements)
        {
            elements = new ElementContainer();
            if (base.source.elements.Length != 0)
            {
                for (int i = 0; i < base.source.elements.Length; i += 2)
                {
                    elements.SetBase(GetElementSource(i).id, base.source.elements[i + 1].Calc(power, 0, P2));
                }
            }
            elements.SetParent(owner);
        }
        if (onDeserialize)
        {
            OnChangePhase(phase, phase);
        }
    }
References elements, BaseStats.EmoIcon, Chara.emoIcon, GetElementSource(), GetPhase(), OnChangePhase(), owner, P2, phase, power, ElementContainer.SetBase(), ElementContainer.SetParent(), and UseElements.
Referenced by Chara.InitStats().
SetPhase()
void BaseCondition.SetPhase () inline
Definition at line 308 of file BaseCondition.cs.
    {
        int num = GetPhase();
        if (phase != num)
        {
            int num2 = phase;
            phase = num;
            PhaseMsg(num > num2);
            OnChangePhase(num2, num);
        }
    }
References GetPhase(), OnChangePhase(), phase, and PhaseMsg().
Referenced by Mod(), Condition.OnStacked(), and Start().
SetRefVal()
void BaseCondition.SetRefVal (int a, int b) inline
Definition at line 150 of file BaseCondition.cs.
    {
        refVal = a;
        refVal2 = b;
    }
References refVal, and refVal2.
Referenced by Element._WriteNote().
Start()
void BaseCondition.Start () inline
Definition at line 229 of file BaseCondition.cs.
    {
        OnBeforeStart();
        phase = -1;
        SetPhase();
        OnStart();
        OnStartOrStack();
        PlayEffect();
        if (base.source.nullify.Length == 0)
        {
            return;
        }
        for (int num = owner.conditions.Count - 1; num >= 0; num--)
        {
            if (TryNullify(owner.conditions[num]))
            {
                owner.conditions[num].Kill();
            }
        }
    }
References Chara.conditions, OnBeforeStart(), OnStart(), OnStartOrStack(), owner, phase, PlayEffect(), SetPhase(), and TryNullify().
Tick()
virtual void BaseCondition.Tick () inline virtual
Reimplemented in BaseStance, ConAnorexia, ConBleed, ConBurning, ConChampagne, ConDeathSentense, ConDisease, Condition, ConDrunk, ConEntangle, ConFear, ConHOT, ConInsane, ConMiasma, ConPoison, ConSleep, ConStrife, ConSuffocation, ConSuspend, ConTransmute, ConWeapon, and ConWet.
Definition at line 367 of file BaseCondition.cs.
    {
    }
ToString()
override string BaseCondition.ToString () inline
Definition at line 165 of file BaseCondition.cs.
    {
        return Name + " " + value + " " + phase;
    }
References Name, phase, and value.
Referenced by ConBuffStats.OnWriteNote(), and ConStrife.OnWriteNote().
TryMove()
virtual bool BaseCondition.TryMove (Point p) inline virtual
Reimplemented in ConEntangle.
Definition at line 140 of file BaseCondition.cs.
    {
        return true;
    }
Referenced by Chara.TryMove().
TryNullify()
bool BaseCondition.TryNullify (Condition c) inline
Definition at line 250 of file BaseCondition.cs.
    {
        if (base.source.nullify.Length == 0)
        {
            return false;
        }
        string[] nullify = base.source.nullify;
        foreach (string text in nullify)
        {
            if (c.source.alias == text)
            {
                owner.Say("nullify", owner, Name.ToLower(), c.Name.ToLower());
                return true;
            }
        }
        return false;
    }
References Name, owner, and Card.Say().
Referenced by Chara.AddCondition(), and Start().
Member Data Documentation
_ints
int [] BaseCondition._ints = new int[5]
Definition at line 9 of file BaseCondition.cs.
elements
ElementContainer BaseCondition.elements
Definition at line 13 of file BaseCondition.cs.
Referenced by Condition.Kill(), ConFreeze.OnChangePhase(), ConPoison.OnChangePhase(), SetOwner(), ConBuffStats.SetOwner(), and Element.BonusInfo.WriteNote().
owner
Chara BaseCondition.owner
Definition at line 15 of file BaseCondition.cs.
Referenced by Condition.Kill(), ConSleep.OnBeforeStart(), ConExcommunication.OnRefresh(), ConGravity.OnRefresh(), ConBlind.OnRemoved(), ConBoost.OnRemoved(), ConExcommunication.OnRemoved(), ConFaint.OnRemoved(), ConHallucination.OnRemoved(), ConNightVision.OnRemoved(), ConReload.OnRemoved(), ConSuspend.OnRemoved(), ConTorch.OnRemoved(), ConTransmute.OnRemoved(), ConWrath.OnRemoved(), ConBandage.OnStart(), ConBlind.OnStart(), ConBoost.OnStart(), ConDrunk.OnStart(), ConSuffocation.OnStart(), ConTorch.OnStart(), ConTransmute.OnStart(), ConNightVision.OnStartOrStack(), PhaseMsg(), PlayEffect(), ConBuffStats.PlayEffect(), PlayEndEffect(), SetOwner(), ConBuffStats.SetOwner(), ConDisease.SetOwner(), ConFaint.SetOwner(), ConHallucination.SetOwner(), ConSleep.SetOwner(), Start(), ConBleed.Tick(), ConBurning.Tick(), ConChampagne.Tick(), ConDeathSentense.Tick(), ConDrunk.Tick(), ConEntangle.Tick(), ConFear.Tick(), ConHOT.Tick(), ConInsane.Tick(), ConMiasma.Tick(), ConPoison.Tick(), ConSleep.Tick(), ConSuffocation.Tick(), ConSuspend.Tick(), ConTransmute.Tick(), ConWet.Tick(), and TryNullify().
phase
int BaseCondition.phase = -1
Definition at line 11 of file BaseCondition.cs.
Referenced by GetColor(), GetPhaseStr(), PhaseMsg(), SetOwner(), SetPhase(), Start(), ConSuffocation.Tick(), and ToString().
Property Documentation
AllowMultipleInstance
virtual bool BaseCondition.AllowMultipleInstance get
Definition at line 97 of file BaseCondition.cs.
CancelAI
virtual bool BaseCondition.CancelAI get
Definition at line 105 of file BaseCondition.cs.
CanManualRemove
virtual bool BaseCondition.CanManualRemove get
Definition at line 133 of file BaseCondition.cs.
Referenced by NotificationCondition.OnClick().
ConsumeTurn
virtual bool BaseCondition.ConsumeTurn get
Definition at line 99 of file BaseCondition.cs.
Referenced by ConFear.Tick(), and Chara.TickConditions().
GainResistFactor
virtual int BaseCondition.GainResistFactor get
Definition at line 113 of file BaseCondition.cs.
Referenced by Chara.AddCondition(), and Chara.AddResistCon().
givenByPcParty
bool BaseCondition.givenByPcParty get set
Definition at line 65 of file BaseCondition.cs.
    {
        get
        {
            return (_ints[4] & 2) != 0;
        }
        set
        {
            _ints[4] = (value ? (_ints[4] | 2) : (_ints[4] & -3));
        }
    }
Referenced by TimeDebuff.CanStack().
IsElemental
virtual bool BaseCondition.IsElemental get
Definition at line 119 of file BaseCondition.cs.
Referenced by GetSpriteColor().
isPerfume
bool BaseCondition.isPerfume get set
Definition at line 77 of file BaseCondition.cs.
    {
        get
        {
            return (_ints[4] & 4) != 0;
        }
        set
        {
            _ints[4] = (value ? (_ints[4] | 4) : (_ints[4] & -5));
        }
    }
Referenced by Chara.Cure(), and Mod().
IsToggle
virtual bool BaseCondition.IsToggle get
Definition at line 93 of file BaseCondition.cs.
Referenced by Chara.AddCondition().
Name
virtual string BaseCondition.Name get
Definition at line 91 of file BaseCondition.cs.
Referenced by Element._WriteNote(), Condition.Create< T >(), GetPhaseStr(), ToString(), TryNullify(), and Element.BonusInfo.WriteNote().
Owner
override Chara BaseCondition.Owner get
Definition at line 89 of file BaseCondition.cs.
P2
virtual int BaseCondition.P2 get
Definition at line 115 of file BaseCondition.cs.
Referenced by _WriteNote(), EvaluateTurn(), and SetOwner().
power
int BaseCondition.power get set
Definition at line 29 of file BaseCondition.cs.
    {
        get
        {
            return _ints[1];
        }
        set
        {
            _ints[1] = value;
        }
    }
Referenced by _WriteNote(), Chara.AddCondition(), Chara.AddResistCon(), Condition.Create(), Condition.Create< T >(), ConNightVision.OnCalculateFov(), ConTorch.OnCalculateFov(), AttackProcess.Perform(), Chara.ResistCon(), and SetOwner().
PreventRegen
virtual bool BaseCondition.PreventRegen get
Definition at line 101 of file BaseCondition.cs.
Referenced by AI_PassTime.Run(), and Chara.TickConditions().
RefString1
virtual string BaseCondition.RefString1 get
Definition at line 121 of file BaseCondition.cs.
    {
        get
        {
            if (!IsElemental)
            {
                return "";
            }
            return sourceElement.GetName().ToLower();
        }
    }
Referenced by Condition.Kill(), and PhaseMsg().
refVal
int BaseCondition.refVal get set
Definition at line 41 of file BaseCondition.cs.
    {
        get
        {
            return _ints[2];
        }
        set
        {
            _ints[2] = value;
        }
    }
Referenced by Chara.GetBuffStats(), GetSpriteColor(), SetElement(), and SetRefVal().
refVal2
int BaseCondition.refVal2 get set
Definition at line 53 of file BaseCondition.cs.
    {
        get
        {
            return _ints[3];
        }
        set
        {
            _ints[3] = value;
        }
    }
Referenced by SetRefVal().
ShouldRefresh
virtual bool BaseCondition.ShouldRefresh get
Definition at line 103 of file BaseCondition.cs.
Referenced by Condition.Kill().
sourceElement
SourceElement.Row BaseCondition.sourceElement get
Definition at line 117 of file BaseCondition.cs.
Referenced by Card.DamageHP(), GetElementSource(), and AttackProcess.Perform().
SyncRide
virtual bool BaseCondition.SyncRide get
Definition at line 109 of file BaseCondition.cs.
TimeBased
virtual bool BaseCondition.TimeBased get
Definition at line 107 of file BaseCondition.cs.
Referenced by Chara.TickConditions().
UseElements
virtual bool BaseCondition.UseElements get
Definition at line 111 of file BaseCondition.cs.
Referenced by SetOwner().
value
int BaseCondition.value get set
Definition at line 17 of file BaseCondition.cs.
    {
        get
        {
            return _ints[0];
        }
        set
        {
            _ints[0] = value;
        }
    }
Referenced by GetPhase(), GetValue(), Mod(), NotificationBuff.OnRefresh(), NotificationCondition.OnRefresh(), and ToString().
WillOverride
virtual bool BaseCondition.WillOverride get
Definition at line 95 of file BaseCondition.cs.
The documentation for this class was generated from the following file:
Elin/BaseCondition.cs