Elin Decompiled Documentation: TaskManager.Designations Class Reference
TaskManager.Designations Class Reference
Public Member Functions
void OnLoad ()
bool CanRemoveDesignation (Point point)
void TryRemoveDesignation (Point point)
Public Attributes
DesignationList< TaskMine > mine = new DesignationList<TaskMine>()
DesignationList< TaskDig > dig = new DesignationList<TaskDig>()
DesignationList< TaskCut > cut = new DesignationList<TaskCut>()
DesignationList< TaskHarvest > harvest = new DesignationList<TaskHarvest>()
DesignationList< TaskBuild > build = new DesignationList<TaskBuild>()
DesignationList< TaskMoveInstalled > moveInstalled = new DesignationList<TaskMoveInstalled>()
Dictionary< int, TaskDesignation > mapAll = new Dictionary<int, TaskDesignation>()
Additional Inherited Members
Static Public Member Functions inherited from EClass
static int rndSeed (int a, int seed)
static int rnd (long a)
static int rnd (int a)
static int curve (int _a, int start, int step, int rate=75)
static int sqrt (int a)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Static Public Attributes inherited from EClass
static Core core
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Detailed Description
Definition at line 6 of file TaskManager.cs.
Member Function Documentation
CanRemoveDesignation()
bool TaskManager.Designations.CanRemoveDesignation (Point point) inline
Definition at line 38 of file TaskManager.cs.
        {
            if (mapAll.TryGetValue(point.index) == null)
            {
                return false;
            }
            return true;
        }
References Point.index, and TaskManager.Designations.mapAll.
Referenced by TaskManager.Designations.TryRemoveDesignation().
OnLoad()
void TaskManager.Designations.OnLoad () inline
Definition at line 28 of file TaskManager.cs.
        {
            mine.OnLoad();
            dig.OnLoad();
            cut.OnLoad();
            harvest.OnLoad();
            build.OnLoad();
            moveInstalled.OnLoad();
        }
References TaskManager.Designations.build, TaskManager.Designations.cut, TaskManager.Designations.dig, TaskManager.Designations.harvest, TaskManager.Designations.mine, and TaskManager.Designations.moveInstalled.
Referenced by TaskManager.OnLoad().
TryRemoveDesignation()
void TaskManager.Designations.TryRemoveDesignation (Point point) inline
Definition at line 47 of file TaskManager.cs.
        {
            if (CanRemoveDesignation(point))
            {
                TaskDesignation taskDesignation = mapAll.TryGetValue(point.index);
                if (taskDesignation.owner != null)
                {
                    taskDesignation.owner.SetAI(new NoGoal());
                }
                taskDesignation.Destroy();
            }
        }
References TaskManager.Designations.CanRemoveDesignation(), Task.Destroy(), Point.index, TaskManager.Designations.mapAll, AIAct.owner, and Chara.SetAI().
Member Data Documentation
build
DesignationList<TaskBuild> TaskManager.Designations.build = new DesignationList<TaskBuild>()
Definition at line 21 of file TaskManager.cs.
Referenced by TaskManager.Designations.OnLoad(), and GoalTask.TryAssignDesignations().
cut
DesignationList<TaskCut> TaskManager.Designations.cut = new DesignationList<TaskCut>()
Definition at line 15 of file TaskManager.cs.
Referenced by TaskManager.Designations.OnLoad(), InspectGroupObj.OnSetActions(), and GoalTask.TryAssignDesignations().
dig
DesignationList<TaskDig> TaskManager.Designations.dig = new DesignationList<TaskDig>()
Definition at line 12 of file TaskManager.cs.
Referenced by TaskManager.Designations.OnLoad(), and GoalTask.TryAssignDesignations().
harvest
DesignationList<TaskHarvest> TaskManager.Designations.harvest = new DesignationList<TaskHarvest>()
Definition at line 18 of file TaskManager.cs.
Referenced by TaskManager.Designations.OnLoad(), and GoalTask.TryAssignDesignations().
mapAll
Dictionary<int, TaskDesignation> TaskManager.Designations.mapAll = new Dictionary<int, TaskDesignation>()
Definition at line 26 of file TaskManager.cs.
Referenced by TaskManager.Designations.CanRemoveDesignation(), and TaskManager.Designations.TryRemoveDesignation().
mine
DesignationList<TaskMine> TaskManager.Designations.mine = new DesignationList<TaskMine>()
Definition at line 9 of file TaskManager.cs.
Referenced by TaskManager.Designations.OnLoad(), InspectGroupBlock.OnSetActions(), and GoalTask.TryAssignDesignations().
moveInstalled
DesignationList<TaskMoveInstalled> TaskManager.Designations.moveInstalled = new DesignationList<TaskMoveInstalled>()
Definition at line 24 of file TaskManager.cs.
Referenced by TaskManager.Designations.OnLoad(), AM_MoveInstalled.SetTarget(), and GoalTask.TryAssignDesignations().
The documentation for this class was generated from the following file:
Elin/TaskManager.cs