Elin Decompiled Documentation: ExtraHint Class Reference
ExtraHint Class Reference
Public Member Functions
void OnChangeActionMode ()
void Refresh ()
Public Attributes
UINote note
Properties
ActionMode mode [get]
Properties inherited from EMono
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SoundManager Sound [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static CoreDebug debug [get]
Additional Inherited Members
Static Public Member Functions inherited from EMono
static int rnd (int a)
Static Public Attributes inherited from EMono
static Core core
Detailed Description
Definition at line 1 of file ExtraHint.cs.
Member Function Documentation
OnChangeActionMode()
void ExtraHint.OnChangeActionMode () inline
Definition at line 7 of file ExtraHint.cs.
    {
        this.SetActive(mode.ShowExtraHint);
        if (mode.ShowExtraHint)
        {
            Refresh();
        }
    }
References mode, Refresh(), and ActionMode.ShowExtraHint.
Refresh()
void ExtraHint.Refresh () inline
Definition at line 16 of file ExtraHint.cs.
    {
        note.Clear();
        mode.OnShowExtraHint(note);
        note.Build();
    }
References UINote.Build(), UINote.Clear(), mode, note, and ActionMode.OnShowExtraHint().
Referenced by OnChangeActionMode().
Member Data Documentation
note
UINote ExtraHint.note
Definition at line 3 of file ExtraHint.cs.
Referenced by Refresh().
Property Documentation
mode
ActionMode ExtraHint.mode get
Definition at line 5 of file ExtraHint.cs.
Referenced by OnChangeActionMode(), and Refresh().
The documentation for this class was generated from the following file:
Elin/ExtraHint.cs