Elin Decompiled Documentation: ButtonHotItem Class Reference
ButtonHotItem Class Reference
Public Member Functions
override void RefreshItem ()
void Refresh ()
void RegisterHotbar ()
override void OnHover ()
Public Member Functions inherited from ButtonGridDrag
override void SetDragParent (IDragParent p)
void OnDrag (PointerEventData data)
override void OnPointerUp (PointerEventData eventData)
Public Member Functions inherited from ButtonGrid
override string ToString ()
T Attach< T > (string id, bool rightAttach=true)
Transform Attach (string id, bool rightAttach=true)
void Dettach (string id)
void Reset ()
void SetBodySlot (BodySlot b, InvOwner owner, bool showIndex=false)
void Redraw ()
void SetCardGrid (Card c, InvOwner owner=null)
void SetCard (Card c, Mode mode=Mode.Default, Action< UINote > onWriteNote=null)
void SetArea (Area a)
void SetItem (GridItem i)
void SetObject (object o)
void SetDummy ()
virtual void SetDragParent (IDragParent p)
void SetIngredient (Recipe r, Recipe.Ingredient _ing)
void SetIngredient (Recipe r, Thing t)
void SetRecipeVariation (UIRecipeInfo.RecipeVariation a)
void SetRecipe ()
void SetRecipe (Area a)
void SetRecipe (Recipe r)
void RefreshCraftable ()
void SetCraftRecipe (Recipe r, Mode mode, bool tooltip=false)
void WriteReqMat (UINote n, Recipe r)
bool ShowMouseHintLeft ()
string GetTextMouseHintLeft ()
bool ShowMouseHintRight ()
string GetTextMouseHintRight ()
RenderRow GetRenderRow ()
void OnRefreshPref ()
override bool CanMiddleClick ()
override void OnMiddleClick (bool forceClick)
Public Member Functions inherited from UIButton
virtual bool CanMiddleClick ()
virtual void OnMiddleClick (bool forceClick)
void SetItem (Item i)
virtual void RefreshItem ()
virtual void OnHover ()
void Toggle ()
void ToggleCheck ()
void SetCheck (bool check)
void SetToggle (bool isOn, Action< bool > onToggle=null)
void SetToggleWithScore (bool isOn, Action< bool > onToggle, int? score)
void SetTooltip (Action< UITooltip > onShowTooltip=null, bool enable=true)
void SetTooltip (string id, Action< UITooltip > onShowTooltip=null, bool enable=true)
void SetTooltipLang (string lang=null)
virtual void ShowTooltip ()
void ShowTooltipForced (bool ignoreWhenRightClick=true)
override void OnPointerDown (PointerEventData eventData)
override void OnPointerClick (PointerEventData eventData)
override void OnPointerUp (PointerEventData eventData)
void OnPointerUpOnDrag (PointerEventData eventData)
void _OnPress ()
void OnPress ()
void AddHighlight (Func< bool > killCondition)
void DoHighlightTransition (bool instant=false)
void DoNormalTransition (bool instant=true)
override Selectable FindSelectableOnDown ()
override Selectable FindSelectableOnUp ()
override Selectable FindSelectableOnLeft ()
override Selectable FindSelectableOnRight ()
void SetNavigation (UIButton up, UIButton down=null, UIButton left=null, UIButton right=null)
override bool IsActive ()
void SetInteractableWithAlpha (bool enable)
virtual void ApplySkin ()
void ApplySkin ()
bool ShowMouseHintLeft ()
string GetTextMouseHintLeft ()
bool ShowMouseHintRight ()
string GetTextMouseHintRight ()
RenderRow GetRenderRow ()
void OnRefreshPref ()
Public Attributes
new int index
WidgetHotbar widget
Public Attributes inherited from ButtonGridDrag
IDragParent dragParent
bool dragged
Public Attributes inherited from ButtonGrid
Area area
Recipe recipe
Recipe.Ingredient ing
Card card
int index
InvOwner invOwner
bool keepBg
List< Transform > listAttach = new List<Transform>()
Public Attributes inherited from UIButton
UIText mainText
UIText subText
UIText subText2
UIText keyText
Image icon
Image imageCheck
Graphic[] targetGraphics
float scaleIcon = 1f
float slideX
float navigationFix
bool isChecked
bool instantClick = true
UISelectableGroup group
TooltipData tooltip
SoundData soundClick
SoundData soundHighlight
Transform animeTarget
Anime animeClick
Anime animeHold
ButtonType buttonType
BaseSkinRoot skinRoot
Action onDoubleClick
Action onRightClick
Action< int > onInputWheel
object refObj
int refInt
string refStr
bool animating
bool selected
Vector3 originalIconScale = Vector3.one
UIButton highlightTarget
Item item
Properties
override float extFixY [get]
Properties inherited from ButtonGrid
ColorProfile Colors [get]
Card Card [get]
virtual float extFixY [get]
Properties inherited from UIButton
List< Graphic > Graphics [get]
virtual bool CanDragLeftButton [get]
Additional Inherited Members
Public Types inherited from ButtonGrid
enum Mode {
Default , Grid , Ingredient , Recipe ,
RecipeGrid , Search
}
Static Public Member Functions inherited from UIButton
static void UpdateButtons ()
static void TryHihlight ()
static void TryShowTip (Transform root=null, bool highlight=true, bool ignoreWhenRightClick=true)
static void TryShowTip< T > (Transform root=null, bool highlight=true, bool ignoreWhenRightClick=false)
Static Public Attributes inherited from UIButton
static bool DoSlide
static bool locked
static UIButton lastButton
static UIButton lastHovered
static UIButton currentHighlight
static UIButton currentPressedButton
static float lastClicked
static float doubleClickTime = 0.4f
static Vector2 buttonPos
static Action onPressed
static List< UIButton > buttons = new List<UIButton>()
static Action actionTooltip
Protected Member Functions inherited from ButtonGrid
override void OnDestroy ()
Protected Member Functions inherited from UIButton
override void Awake ()
override void OnEnable ()
override void DoStateTransition (SelectionState state, bool instant)
Detailed Description
Definition at line 5 of file ButtonHotItem.cs.
Member Function Documentation
OnHover()
override void ButtonHotItem.OnHover () inline virtual
Reimplemented from UIButton.
Definition at line 115 of file ButtonHotItem.cs.
    {
        if (!WidgetHotbar.registering)
        {
            base.OnHover();
        }
    }
References WidgetHotbar.registering.
Refresh()
void ButtonHotItem.Refresh () inline
Definition at line 92 of file ButtonHotItem.cs.
    {
        if (item != null)
        {
            HotItem hotItem = item as HotItem;
            if ((bool)subText)
            {
                hotItem.SetSubText(subText);
            }
            if (hotItem.Thing != null)
            {
                card = hotItem.Thing;
            }
        }
    }
References ButtonGrid.card, UIButton.item, UIButton.Item.SetSubText(), UIButton.subText, and HotItem.Thing.
Referenced by WidgetHotbar._OnDirtyInventory(), WidgetCurrentTool._RefreshCurrentHotItem(), Player.RefreshCurrentHotItem(), and RefreshItem().
RefreshItem()
override void ButtonHotItem.RefreshItem () inline virtual
Reimplemented from UIButton.
Definition at line 14 of file ButtonHotItem.cs.
    {
        HotItem item = base.item as HotItem;
        bool flag = item != null;
        instantClick = !widget.hotbar.IsUserHotbar;
        base.onClick.RemoveAllListeners();
        dragParent = ((flag && widget.CanRegisterItem) ? widget : null);
        icon.enabled = flag;
        base.interactable = flag || widget.CanRegisterItem || !widget.IsSealed;
        if (flag && item.Hidden)
        {
            icon.enabled = false;
            base.interactable = false;
        }
        mainText.SetActive(widget.extra.showShortcut);
        base.image.sprite = Core.Instance.refs.spritesHighlight[0];
        base.transition = item?.Transition ?? Transition.SpriteSwap;
        if (flag)
        {
            item.button = this;
            item.hotbar = widget.hotbar;
            base.onClick.AddListener(delegate
            {
                if (EClass.ui.BlockInput)
                {
                    SE.BeepSmall();
                }
                else if (WidgetHotbar.registering)
                {
                    RegisterHotbar();
                }
                else
                {
                    if (!widget.Visible)
                    {
                        widget.ToggleVisible();
                    }
                    UIButton.buttonPos = base.transform.position;
                    item.OnClick(this, widget.hotbar);
                    EInput.Consume(0);
                }
            });
            onRightClick = delegate
            {
                item.OnRightClick(this);
            };
            tooltip.enable = !item.TextTip.IsEmpty();
            tooltip.offset = new Vector3(0f, (widget.transform.position.y < 200f) ? 70 : (-20), 0f);
            tooltip.onShowTooltip = delegate(UITooltip t)
            {
                string textTip = item.TextTip;
                t.textMain.text = textTip;
            };
            icon.material = (item.UseUIObjMaterial ? EClass.core.refs.matUIObj : null);
            item.SetImage(icon);
            Refresh();
            return;
        }
        subText.SetActive(enable: false);
        tooltip.enable = false;
        base.onClick.AddListener(delegate
        {
            if (EClass.ui.BlockInput)
            {
                SE.BeepSmall();
            }
            else if (WidgetHotbar.registering)
            {
                RegisterHotbar();
            }
            else
            {
                widget.OnClickEmptyItem(this);
            }
        });
        onRightClick = null;
    }
References WidgetHotbar.CanRegisterItem, EInput.Consume(), ButtonGridDrag.dragParent, WidgetHotbar.extra, UIButton.Item.Hidden, WidgetHotbar.hotbar, UIButton.icon, if(), Core.Instance, UIButton.instantClick, Widget.IsSealed, Hotbar.IsUserHotbar, UIButton.item, UIButton.mainText, UIButton.Item.OnClick(), UIButton.onRightClick, Refresh(), Core.refs, RegisterHotbar(), WidgetHotbar.registering, WidgetHotbar.Extra.showShortcut, CoreRef.spritesHighlight, UIButton.subText, UIButton.Item.TextTip, WidgetHotbar.ToggleVisible(), UIButton.Item.Transition, EClass.ui, WidgetHotbar.Visible, and widget.
Referenced by HotItemWidget.OnClick(), and WidgetHotbar.RefreshButtons().
RegisterHotbar()
void ButtonHotItem.RegisterHotbar () inline
Definition at line 108 of file ButtonHotItem.cs.
    {
        SE.SelectHotitem();
        widget.SetItem(this, WidgetHotbar.registeringItem);
        Core.Instance.ui.RemoveLayer<LayerRegisterHotbar>();
    }
References Core.Instance, WidgetHotbar.registeringItem, WidgetHotbar.SetItem(), Core.ui, and widget.
Referenced by RefreshItem().
Member Data Documentation
index
new int ButtonHotItem.index
Definition at line 8 of file ButtonHotItem.cs.
Referenced by WidgetHotbar.OnSetContextMenu(), WidgetHotbar.RebuildPage(), and WidgetHotbar.SetItem().
widget
WidgetHotbar ButtonHotItem.widget
Definition at line 10 of file ButtonHotItem.cs.
Referenced by HotItemToggle.OnClick(), HotItemTogglePage.OnClick(), HotItemToggleVisible.OnClick(), WidgetHotbar.OnEndDrag(), HotItemToggleVisible.OnHover(), HotItem.OnRightClick(), WidgetHotbar.OnSetContextMenu(), RefreshItem(), and RegisterHotbar().
Property Documentation
extFixY
override float ButtonHotItem.extFixY get
Definition at line 12 of file ButtonHotItem.cs.
The documentation for this class was generated from the following file:
Elin/ButtonHotItem.cs