Elin Decompiled Documentation: UIMagicChest Class Reference
UIMagicChest Class Reference
Public Member Functions
void Init ()
void OnAfterRedraw ()
void RefreshCats ()
void RefreshBottom ()
void Search (string s)
void ClearSearch ()
void Redraw ()
Public Attributes
LayoutGroup layoutPage
LayoutGroup layoutCat
LayoutGroup layoutBottom
UIButton itemNum
UIButton itemElec
UIButton buttonClearSearch
UIButton moldCat
UISelectableGroup groupPage
List< UIButton > buttonsPage
UIInventory uiInventory
InputField inputSearch
float intervalSearch
int page
int pageMax
List< Thing > filteredList = new List<Thing>()
Color colorCat
Color colorCatSelected
HashSet< string > cats = new HashSet<string>()
Dictionary< string, UIButton > catButton = new Dictionary<string, UIButton>()
Dictionary< string, int > catCount = new Dictionary<string, int>()
string idCat = ""
string lastSearch = ""
HashSet< Recipe > searchRecipes = new HashSet<Recipe>()
Properties
Card container [get]
int GridSize [get]
Properties inherited from EMono
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SoundManager Sound [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static CoreDebug debug [get]
Private Member Functions
void LateUpdate ()
Private Attributes
bool firstSearch = true
float timerSearch
Additional Inherited Members
Static Public Member Functions inherited from EMono
static int rnd (int a)
Static Public Attributes inherited from EMono
static Core core
Detailed Description
Definition at line 5 of file UIMagicChest.cs.
Member Function Documentation
ClearSearch()
void UIMagicChest.ClearSearch () inline
Definition at line 200 of file UIMagicChest.cs.
    {
        inputSearch.text = "";
        timerSearch = 0f;
        lastSearch = "";
        Redraw();
    }
Init()
void UIMagicChest.Init () inline
Definition at line 61 of file UIMagicChest.cs.
    {
        UIButton t = layoutPage.CreateMold<UIButton>();
        moldCat = layoutCat.CreateMold<UIButton>();
        for (int i = 0; i < 9; i++)
        {
            UIButton b = Util.Instantiate(t, layoutPage);
            b.mainText.text = (i + 1).ToString() ?? "";
            buttonsPage.Add(b);
            int _i = i;
            b.SetOnClick(delegate
            {
                if (!UIContextMenu.Current)
                {
                    page = _i;
                    groupPage.Select(b);
                    SE.Tab();
                    Redraw();
                }
            });
        }
        groupPage.Init();
        inputSearch.onValueChanged.AddListener(Search);
        inputSearch.onSubmit.AddListener(Search);
        RefreshBottom();
        itemNum.RebuildLayout();
        itemElec.RebuildLayout();
        layoutBottom.RebuildLayout();
    }
References buttonsPage, UIContextMenu.Current, groupPage, UISelectableGroup.Init(), inputSearch, itemElec, itemNum, layoutBottom, layoutCat, layoutPage, moldCat, page, Redraw(), RefreshBottom(), Search, UISelectableGroup.Select(), and Util.
LateUpdate()
void UIMagicChest.LateUpdate () inline private
Definition at line 149 of file UIMagicChest.cs.
    {
        if (timerSearch > 0f)
        {
            timerSearch -= Core.delta;
            if (timerSearch <= 0f)
            {
                Search(inputSearch.text);
            }
        }
        if (EInput.wheel != 0 && !UIContextMenu.Current)
        {
            SE.Tab();
            page -= EInput.wheel;
            if (page < 0)
            {
                page = pageMax;
            }
            if (page > pageMax)
            {
                page = 0;
            }
            Redraw();
        }
    }
References UIContextMenu.Current, Core.delta, Search, and EInput.wheel.
OnAfterRedraw()
void UIMagicChest.OnAfterRedraw () inline
Definition at line 91 of file UIMagicChest.cs.
    {
        RefreshBottom();
        for (int i = 0; i < buttonsPage.Count; i++)
        {
            buttonsPage[i].interactable = i <= pageMax;
        }
        groupPage.selected = null;
        groupPage.Select(page);
    }
References buttonsPage, groupPage, page, pageMax, RefreshBottom(), and UISelectableGroup.Select().
Redraw()
void UIMagicChest.Redraw () inline
Definition at line 208 of file UIMagicChest.cs.
    {
        uiInventory.list.Redraw();
    }
References UIInventory.list, and UIList.Redraw().
Referenced by Init(), and RefreshCats().
RefreshBottom()
void UIMagicChest.RefreshBottom () inline
Definition at line 143 of file UIMagicChest.cs.
    {
        itemNum.mainText.text = container.things.Count + " / " + container.things.MaxCapacity;
        itemElec.mainText.SetText(Mathf.Abs(container.trait.Electricity) + " " + "mw".lang(), (container.trait.Electricity == 0 || container.isOn) ? FontColor.Good : FontColor.Bad);
    }
References Trait.Electricity, Card.isOn, UIButton.mainText, ThingContainer.MaxCapacity, UIText.SetText(), Card.things, and Card.trait.
Referenced by Init(), and OnAfterRedraw().
RefreshCats()
void UIMagicChest.RefreshCats () inline
Definition at line 102 of file UIMagicChest.cs.
    {
        foreach (string cat in cats)
        {
            if (catButton.ContainsKey(cat))
            {
                continue;
            }
            UIButton uIButton = Util.Instantiate(moldCat, layoutCat);
            catButton[cat] = uIButton;
            string _c = cat;
            uIButton.SetOnClick(delegate
            {
                if (!UIContextMenu.Current)
                {
                    SE.Tab();
                    if (idCat == _c)
                    {
                        idCat = "";
                    }
                    else
                    {
                        idCat = _c;
                    }
                    Redraw();
                }
            });
        }
        foreach (KeyValuePair<string, UIButton> item in catButton)
        {
            bool flag = cats.Contains(item.Key);
            UIButton value = item.Value;
            value.SetActive(flag);
            if (flag)
            {
                value.mainText.text = EMono.sources.categories.map[item.Key].GetName() + " (" + catCount[item.Key] + ")";
                value.image.color = ((item.Key == idCat) ? colorCatSelected : colorCat);
            }
        }
    }
References catButton, cats, UIContextMenu.Current, layoutCat, moldCat, Redraw(), and Util.
Referenced by ThingContainer.RefreshGrid().
Search()
void UIMagicChest.Search (string s) inline
Definition at line 175 of file UIMagicChest.cs.
    {
        s = s.ToLower();
        if (s.IsEmpty())
        {
            s = "";
        }
        buttonClearSearch.SetActive(inputSearch.text != "");
        if (s == lastSearch)
        {
            return;
        }
        if (firstSearch)
        {
            firstSearch = false;
            foreach (Thing thing in container.things)
            {
                thing.tempName = thing.GetName(NameStyle.Full, 1).ToLower();
            }
        }
        timerSearch = intervalSearch;
        lastSearch = s;
        Redraw();
    }
References Thing.GetName(), and Card.things.
Member Data Documentation
buttonClearSearch
UIButton UIMagicChest.buttonClearSearch
Definition at line 17 of file UIMagicChest.cs.
buttonsPage
List<UIButton> UIMagicChest.buttonsPage
Definition at line 23 of file UIMagicChest.cs.
Referenced by Init(), and OnAfterRedraw().
catButton
Dictionary<string, UIButton> UIMagicChest.catButton = new Dictionary<string, UIButton>()
Definition at line 43 of file UIMagicChest.cs.
Referenced by RefreshCats().
catCount
Dictionary<string, int> UIMagicChest.catCount = new Dictionary<string, int>()
Definition at line 45 of file UIMagicChest.cs.
Referenced by ThingContainer.RefreshGrid().
cats
HashSet<string> UIMagicChest.cats = new HashSet<string>()
Definition at line 41 of file UIMagicChest.cs.
Referenced by RefreshCats(), and ThingContainer.RefreshGrid().
colorCat
Color UIMagicChest.colorCat
Definition at line 37 of file UIMagicChest.cs.
colorCatSelected
Color UIMagicChest.colorCatSelected
Definition at line 39 of file UIMagicChest.cs.
filteredList
List<Thing> UIMagicChest.filteredList = new List<Thing>()
Definition at line 35 of file UIMagicChest.cs.
Referenced by ThingContainer.RefreshGrid().
firstSearch
bool UIMagicChest.firstSearch = true private
Definition at line 49 of file UIMagicChest.cs.
groupPage
UISelectableGroup UIMagicChest.groupPage
Definition at line 21 of file UIMagicChest.cs.
Referenced by Init(), and OnAfterRedraw().
idCat
string UIMagicChest.idCat = ""
Definition at line 47 of file UIMagicChest.cs.
Referenced by ThingContainer.RefreshGrid().
inputSearch
InputField UIMagicChest.inputSearch
Definition at line 27 of file UIMagicChest.cs.
Referenced by Init().
intervalSearch
float UIMagicChest.intervalSearch
Definition at line 29 of file UIMagicChest.cs.
itemElec
UIButton UIMagicChest.itemElec
Definition at line 15 of file UIMagicChest.cs.
Referenced by Init().
itemNum
UIButton UIMagicChest.itemNum
Definition at line 13 of file UIMagicChest.cs.
Referenced by Init().
lastSearch
string UIMagicChest.lastSearch = ""
Definition at line 53 of file UIMagicChest.cs.
Referenced by ThingContainer.RefreshGrid().
layoutBottom
LayoutGroup UIMagicChest.layoutBottom
Definition at line 11 of file UIMagicChest.cs.
Referenced by Init().
layoutCat
LayoutGroup UIMagicChest.layoutCat
Definition at line 9 of file UIMagicChest.cs.
Referenced by Init(), and RefreshCats().
layoutPage
LayoutGroup UIMagicChest.layoutPage
Definition at line 7 of file UIMagicChest.cs.
Referenced by Init().
moldCat
UIButton UIMagicChest.moldCat
Definition at line 19 of file UIMagicChest.cs.
Referenced by Init(), and RefreshCats().
page
int UIMagicChest.page
Definition at line 31 of file UIMagicChest.cs.
Referenced by Init(), OnAfterRedraw(), and ThingContainer.RefreshGrid().
pageMax
int UIMagicChest.pageMax
Definition at line 33 of file UIMagicChest.cs.
Referenced by OnAfterRedraw(), and ThingContainer.RefreshGrid().
searchRecipes
HashSet<Recipe> UIMagicChest.searchRecipes = new HashSet<Recipe>()
Definition at line 55 of file UIMagicChest.cs.
timerSearch
float UIMagicChest.timerSearch private
Definition at line 51 of file UIMagicChest.cs.
uiInventory
UIInventory UIMagicChest.uiInventory
Definition at line 25 of file UIMagicChest.cs.
Property Documentation
container
Card UIMagicChest.container get
Definition at line 57 of file UIMagicChest.cs.
GridSize
int UIMagicChest.GridSize get
Definition at line 59 of file UIMagicChest.cs.
The documentation for this class was generated from the following file:
Elin/UIMagicChest.cs