Elin Decompiled Documentation: LayerTravel Class Reference
LayerTravel Class Reference
Public Member Functions
override void OnInit ()
override void OnKill ()
override void OnSwitchContent (Window window)
int GetTravelFood (Zone z)
int GetTravelHours (Zone z)
int GetSortVal (Zone z)
void Refresh ()
Public Member Functions inherited from ELayer
override void OnBeforeAddLayer ()
void InitInspector ()
sealed override void Init ()
override void OnAfterAddLayer ()
void TryShowHelp ()
void AddLayerToUI (string id)
void TryShowHint (string _langHint=null)
void TalkHomeMemeber (string id)
void TalkMaid (string id)
override void OnRightClick ()
Public Member Functions inherited from Layer
virtual string GetTextHeader (Window window)
virtual bool HeaderIsListOf (int id)
virtual void Init ()
virtual void OnInit ()
virtual void OnAfterInit ()
virtual void ApplySkin ()
void ShowScreenLock (string id)
void UpdateInput ()
virtual void OnUpdateInput ()
virtual void OnRightClick ()
virtual bool OnBack ()
virtual void OnChangeLayer ()
virtual void OnCreate ()
void _AddLayer (string id)
Layer AddLayer (string id)
T AddLayer< T > ()
T AddLayer< T > (string id)
T AddLayerDontCloseOthers< T > ()
Layer AddLayerDontCloseOthers (Layer l)
T GetOrAddLayer< T > ()
virtual void OnBeforeAddLayer ()
virtual void OnAfterAddLayer ()
Layer AddLayer (Layer l)
void ToggleLayer (string id)
T ToggleLayer< T > (string id=null)
void WaitAndClose ()
void OnClickClose ()
virtual void Close ()
void CloseLayers ()
void RemoveLayers (bool removeImportant=false)
bool RemoveLayer< T > ()
void RemoveLayer (Layer l)
virtual void OnKill ()
Layer SetOnKill (Action action)
void DisableClose ()
void Delay (float duration=0.05f)
Layer SetDelay (float d)
Layer GetLayer (string id)
T GetLayer< T > (bool fromTop=false)
Layer GetTopLayer ()
void SwitchContent (int idWindow, int i)
virtual void OnSwitchContent (Window window)
Layer SetTitles (string langList, string idHeaderRow=null)
bool IsBlockWidgetClick ()
bool IsHideHud ()
bool IsAllowGeneralInput ()
bool IsUseBlur ()
bool IsPointerOnLayer ()
void ApplySkin ()
Public Attributes
UIList list
Zone currentZone
Image bg
float fadeAlpha
float fadeTime
Ease easeFade
Ease easeZoom
float startZoom
float endZoom
float timeZoom
bool highlightZone
bool useBG
bool useZoom
Public Attributes inherited from Layer
Option option
UnityEvent onKill
Anime animeIn
Anime animeOut
bool closeOthers
bool defaultActionMode = true
Button screenLock
Layer parent
string idLayer
List< Layer > layers = new List<Layer>()
Vector2 lastParentPos
List< Window > windows = new List<Window>()
string langHint
Properties
override bool blockWidgetClick [get]
Properties inherited from ELayer
static Core core [get]
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static FactionBranch Branch [get]
static Faction Home [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static CoreConfig config [get]
static GameSetting setting [get]
static ColorProfile Colors [get]
static SourceManager sources [get]
static World world [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
bool IsFloat [get]
virtual string IdHelp [get]
Properties inherited from Layer
Layer TopLayer [get]
string uid [get]
virtual RectTransform rectLayers [get]
virtual bool blockWidgetClick [get]
Private Attributes
Point posHighlight = new Point()
Additional Inherited Members
Static Public Member Functions inherited from ELayer
static int rnd (int a)
Static Public Member Functions inherited from Layer
static T Create< T > ()
static T Create< T > (string path)
static Layer Create (string path)
Static Public Attributes inherited from Layer
static int skipInput
static bool closeOnRightClick
static bool rightClicked
static bool cancelKeyDown
static bool ignoreSounds
static Transform blurStopInstance
static string[] searchPath = new string[3] { "Layer", "Layer/Dialog", "Layer/LayerHome" }
Protected Member Functions inherited from ELayer
sealed override void _Close ()
sealed override void Kill ()
Protected Member Functions inherited from Layer
virtual void Awake ()
virtual void _Close ()
virtual void Kill ()
Protected Attributes inherited from Layer
RectTransform _rect
bool isDestroyed
Detailed Description
Definition at line 7 of file LayerTravel.cs.
Member Function Documentation
GetSortVal()
int LayerTravel.GetSortVal (Zone z) inline
Definition at line 87 of file LayerTravel.cs.
    {
        if (ELayer.pc.homeZone == z)
        {
            return -1;
        }
        return GetTravelHours(z);
    }
References GetTravelHours(), Chara.homeZone, and ELayer.pc.
Referenced by Refresh().
GetTravelFood()
int LayerTravel.GetTravelFood (Zone z) inline
Definition at line 73 of file LayerTravel.cs.
    {
        if (z.tempDist == 0)
        {
            return 0;
        }
        return 1 + GetTravelHours(z) / 24;
    }
References GetTravelHours(), and Zone.tempDist.
Referenced by Refresh().
GetTravelHours()
int LayerTravel.GetTravelHours (Zone z) inline
Definition at line 82 of file LayerTravel.cs.
    {
        return z.tempDist * 3 * 100 / (100 + ELayer.pc.Evalue(407) * 2);
    }
References Card.Evalue(), and ELayer.pc.
Referenced by GetSortVal(), GetTravelFood(), and Refresh().
OnInit()
override void LayerTravel.OnInit () inline virtual
Reimplemented from Layer.
Definition at line 39 of file LayerTravel.cs.
    {
        if (useZoom)
        {
            ELayer.screen.SetZoom(ELayer.screen.TargetZoom);
            DOTween.To(() => ELayer.scene.screenElona.zoom, delegate(float x)
            {
                ELayer.scene.screenElona.zoom = x;
            }, endZoom, timeZoom).SetEase(easeZoom);
        }
        if (useBG)
        {
            bg.DOFade(fadeAlpha, fadeTime).SetEase(easeFade);
            ELayer.ui.layerFloat.SetActive(enable: false);
        }
    }
References bg, easeFade, easeZoom, endZoom, fadeAlpha, fadeTime, ELayer.scene, ELayer.screen, Scene.screenElona, BaseGameScreen.SetZoom(), BaseGameScreen.TargetZoom, timeZoom, ELayer.ui, useBG, useZoom, and GameScreenElona.zoom.
OnKill()
override void LayerTravel.OnKill () inline virtual
Reimplemented from Layer.
Definition at line 56 of file LayerTravel.cs.
    {
        if (useBG)
        {
            ELayer.ui.layerFloat.SetActive(enable: true);
        }
        if (useZoom)
        {
            ELayer.screen.SetZoom(ELayer.screen.TargetZoom);
        }
    }
References ELayer.screen, BaseGameScreen.SetZoom(), BaseGameScreen.TargetZoom, ELayer.ui, useBG, and useZoom.
OnSwitchContent()
override void LayerTravel.OnSwitchContent (Window window) inline virtual
Reimplemented from Layer.
Definition at line 68 of file LayerTravel.cs.
    {
        Refresh();
    }
References Refresh().
Refresh()
void LayerTravel.Refresh () inline
Definition at line 96 of file LayerTravel.cs.
    {
        currentZone = ELayer.scene.elomap.GetZone(ELayer.pc.pos);
        if (currentZone != null && !currentZone.isKnown)
        {
            currentZone = null;
        }
        list.callbacks = new UIList.Callback<Zone, UIButton>
        {
            onInstantiate = delegate(Zone a, UIButton b)
            {
                string text = "travelZone".lang(a.Name, a.tempDist.ToString() ?? "");
                if (a == ELayer.pc.homeZone)
                {
                    text = "travelHome".lang() + text;
                }
                if (a.isRandomSite)
                {
                    text += (" (" + "days1".lang() + (ELayer.world.date.GetRemainingHours(a.dateExpire) / 24 + 1) + "days2".lang() + ")").TagSize(13);
                }
                b.mainText.SetText(text);
                b.icon.sprite = TilemapUtils.GetOrCreateTileSprite(ELayer.scene.elomap.actor.tileset, a.icon) ?? b.icon.sprite;
                b.icon.SetNativeSize();
                b.refObj = a;
                int travelFood = GetTravelFood(a);
                int currency = ELayer.pc.GetCurrency("ration");
                b.subText.SetText(travelFood.ToString() ?? "", (currency >= travelFood) ? FontColor.Good : FontColor.Bad);
                b.subText2.SetText(Date.GetText2(GetTravelHours(a)));
            },
            onClick = delegate(Zone a, UIButton b)
            {
                if (a == currentZone)
                {
                    Close();
                    ELayer.player.EnterLocalZone();
                }
                else if (ELayer.pc.TryPay(GetTravelFood(a), "ration"))
                {
                    if (ELayer.pc.burden.GetPhase() >= 3)
                    {
                        Msg.Say("errorOverweightTravel");
                        Close();
                    }
                    else
                    {
                        ELayer.player.distanceTravel = a.tempDist;
                        ELayer.player.dateTravel = ELayer.world.date.GetRaw();
                        foreach (UIList.ButtonPair button in list.buttons)
{
                            UIButton uIButton = button.component as UIButton;
                            if ((bool)uIButton && uIButton != b)
{
                                uIButton.GetComponent<CanvasGroup>().alpha = 0.5f;
                            }
                        }
                        float time = 0f;
                        int h = 0;
                        int maxHours = GetTravelHours(a);
                        ELayer.ui.AddLayer<LayerCover>().SetCondition(delegate(float delta)
{
                            time += delta;
                            if (time >= 0.035f)
{
                                time = 0f;
                                h++;
                                ELayer.world.date.AdvanceHour();
                                if (h >= maxHours)
{
                                    Close();
                                    ELayer.pc.MoveImmediate(a.RegionPos);
                                    ELayer.player.lastZonePos = null;
                                    ZoneTransition.EnterState state = ((a.RegionEnterState == ZoneTransition.EnterState.Dir) ? ZoneTransition.DirToState(ELayer.pc.GetCurrentDir()) : a.RegionEnterState);
                                    if (a is Zone_Lumiest)
{
                                        state = ZoneTransition.EnterState.Right;
                                    }
                                    ELayer.pc.MoveZone(a, state);
                                    return true;
                                }
                            }
                            return false;
                        });
                    }
                }
            },
            onList = delegate
            {
                List<Zone> obj = ELayer.game.activeZone.Region.ListTravelZones();
                obj.Sort((Zone a, Zone b) => GetSortVal(a) - GetSortVal(b));
                foreach (Zone item in obj)
                {
                    if (windows[0].idTab != 1)
                    {
                        list.Add(item);
                    }
                }
            }
        };
        list.List();
    }
References Game.activeZone, EloMap.actor, UIList.Add(), GameDate.AdvanceHour(), Chara.burden, UIList.buttons, Layer.Close(), currency, currentZone, World.date, Spatial.dateExpire, ZoneTransition.DirToState(), Scene.elomap, Player.EnterLocalZone(), ELayer.game, Card.GetCurrency(), Chara.GetCurrentDir(), Stats.GetPhase(), Date.GetRaw(), Date.GetRemainingHours(), GetSortVal(), Date.GetText2(), GetTravelFood(), GetTravelHours(), EloMap.GetZone(), Chara.homeZone, UIButton.icon, Spatial.icon, Spatial.isKnown, Spatial.isRandomSite, item, list, UIList.List(), Region.ListTravelZones(), UIButton.mainText, Card.MoveImmediate(), Chara.MoveZone(), Spatial.Name, ELayer.pc, ELayer.player, Card.pos, Zone.Region, Zone.RegionEnterState, Spatial.RegionPos, Msg.Say(), ELayer.scene, UIText.SetText(), UIButton.subText, UIButton.subText2, Zone.tempDist, EloMapActor.tileset, Card.TryPay(), ELayer.ui, Layer.windows, and ELayer.world.
Referenced by OnSwitchContent().
Member Data Documentation
bg
Image LayerTravel.bg
Definition at line 13 of file LayerTravel.cs.
Referenced by OnInit().
currentZone
Zone LayerTravel.currentZone
Definition at line 11 of file LayerTravel.cs.
Referenced by Refresh().
easeFade
Ease LayerTravel.easeFade
Definition at line 19 of file LayerTravel.cs.
Referenced by OnInit().
easeZoom
Ease LayerTravel.easeZoom
Definition at line 21 of file LayerTravel.cs.
Referenced by OnInit().
endZoom
float LayerTravel.endZoom
Definition at line 25 of file LayerTravel.cs.
Referenced by OnInit().
fadeAlpha
float LayerTravel.fadeAlpha
Definition at line 15 of file LayerTravel.cs.
Referenced by OnInit().
fadeTime
float LayerTravel.fadeTime
Definition at line 17 of file LayerTravel.cs.
Referenced by OnInit().
highlightZone
bool LayerTravel.highlightZone
Definition at line 29 of file LayerTravel.cs.
list
UIList LayerTravel.list
Definition at line 9 of file LayerTravel.cs.
Referenced by Refresh().
posHighlight
Point LayerTravel.posHighlight = new Point() private
Definition at line 35 of file LayerTravel.cs.
startZoom
float LayerTravel.startZoom
Definition at line 23 of file LayerTravel.cs.
timeZoom
float LayerTravel.timeZoom
Definition at line 27 of file LayerTravel.cs.
Referenced by OnInit().
useBG
bool LayerTravel.useBG
Definition at line 31 of file LayerTravel.cs.
Referenced by OnInit(), and OnKill().
useZoom
bool LayerTravel.useZoom
Definition at line 33 of file LayerTravel.cs.
Referenced by OnInit(), and OnKill().
Property Documentation
blockWidgetClick
override bool LayerTravel.blockWidgetClick get
Definition at line 37 of file LayerTravel.cs.
The documentation for this class was generated from the following file:
Elin/LayerTravel.cs