Elin Decompiled Documentation: UIInspector Class Reference
UIInspector Class Reference
Public Member Functions
void SetVisible (bool enable)
void Hide ()
bool InspectUnderMouse ()
void Inspect (IInspect newTarget)
void Inspect (InspectGroup g)
void OnUpdate ()
void Refresh ()
void DrawHighlight (IInspect i, bool selected=false)
Public Member Functions inherited from ELayer
override void OnBeforeAddLayer ()
void InitInspector ()
sealed override void Init ()
override void OnAfterAddLayer ()
void TryShowHelp ()
void AddLayerToUI (string id)
void TryShowHint (string _langHint=null)
void TalkHomeMemeber (string id)
void TalkMaid (string id)
override void OnRightClick ()
Public Member Functions inherited from Layer
virtual string GetTextHeader (Window window)
virtual bool HeaderIsListOf (int id)
virtual void Init ()
virtual void OnInit ()
virtual void OnAfterInit ()
virtual void ApplySkin ()
void ShowScreenLock (string id)
void UpdateInput ()
virtual void OnUpdateInput ()
virtual void OnRightClick ()
virtual bool OnBack ()
virtual void OnChangeLayer ()
virtual void OnCreate ()
void _AddLayer (string id)
Layer AddLayer (string id)
T AddLayer< T > ()
T AddLayer< T > (string id)
T AddLayerDontCloseOthers< T > ()
Layer AddLayerDontCloseOthers (Layer l)
T GetOrAddLayer< T > ()
virtual void OnBeforeAddLayer ()
virtual void OnAfterAddLayer ()
Layer AddLayer (Layer l)
void ToggleLayer (string id)
T ToggleLayer< T > (string id=null)
void WaitAndClose ()
void OnClickClose ()
virtual void Close ()
void CloseLayers ()
void RemoveLayers (bool removeImportant=false)
bool RemoveLayer< T > ()
void RemoveLayer (Layer l)
virtual void OnKill ()
Layer SetOnKill (Action action)
void DisableClose ()
void Delay (float duration=0.05f)
Layer SetDelay (float d)
Layer GetLayer (string id)
T GetLayer< T > (bool fromTop=false)
Layer GetTopLayer ()
void SwitchContent (int idWindow, int i)
virtual void OnSwitchContent (Window window)
Layer SetTitles (string langList, string idHeaderRow=null)
bool IsBlockWidgetClick ()
bool IsHideHud ()
bool IsAllowGeneralInput ()
bool IsUseBlur ()
bool IsPointerOnLayer ()
void ApplySkin ()
Public Attributes
InspectGroup group
LayoutGroup layoutBody
LayoutGroup layoutButtons
UIButton mold
Vector3 offset
Vector3 modPos
SoundData soundPop
WindowChara windowChara
RectTransform rectInfo
RectTransform rectRoom
UINote note
UINote noteRoom
UIText textName
UIImage bg
Point point
Public Attributes inherited from Layer
Option option
UnityEvent onKill
Anime animeIn
Anime animeOut
bool closeOthers
bool defaultActionMode = true
Button screenLock
Layer parent
string idLayer
List< Layer > layers = new List<Layer>()
Vector2 lastParentPos
List< Window > windows = new List<Window>()
string langHint
Properties
bool IsActive [get]
Properties inherited from ELayer
static Core core [get]
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static FactionBranch Branch [get]
static Faction Home [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static CoreConfig config [get]
static GameSetting setting [get]
static ColorProfile Colors [get]
static SourceManager sources [get]
static World world [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
bool IsFloat [get]
virtual string IdHelp [get]
Properties inherited from Layer
Layer TopLayer [get]
string uid [get]
virtual RectTransform rectLayers [get]
virtual bool blockWidgetClick [get]
Private Attributes
bool initialized
Additional Inherited Members
Static Public Member Functions inherited from ELayer
static int rnd (int a)
Static Public Member Functions inherited from Layer
static T Create< T > ()
static T Create< T > (string path)
static Layer Create (string path)
Static Public Attributes inherited from Layer
static int skipInput
static bool closeOnRightClick
static bool rightClicked
static bool cancelKeyDown
static bool ignoreSounds
static Transform blurStopInstance
static string[] searchPath = new string[3] { "Layer", "Layer/Dialog", "Layer/LayerHome" }
Protected Member Functions inherited from ELayer
sealed override void _Close ()
sealed override void Kill ()
Protected Member Functions inherited from Layer
virtual void Awake ()
virtual void _Close ()
virtual void Kill ()
Protected Attributes inherited from Layer
RectTransform _rect
bool isDestroyed
Detailed Description
Definition at line 5 of file UIInspector.cs.
Member Function Documentation
DrawHighlight()
void UIInspector.DrawHighlight (IInspect i, bool selected = false) inline
Definition at line 194 of file UIInspector.cs.
    {
        if (i is Area || i is EloPos)
        {
            return;
        }
        Vector3 v = i.InspectPosition;
        Point inspectPoint = i.InspectPoint;
        if (inspectPoint == null)
        {
            return;
        }
        MeshPass meshPass = ((inspectPoint.HasNonWallBlock || inspectPoint.HasBlockRecipe) ? ELayer.screen.guide.passGuideBlock : ELayer.screen.guide.passGuideFloor);
        if (i is Chara)
        {
            v += ELayer.screen.pcOrbit.crystal.transform.position;
            ELayer.screen.tileMap.passIcon.Add(ref v, 1f);
            return;
        }
        if (i is Thing)
        {
            Thing thing = i as Thing;
            if (thing.IsInstalled && thing.sourceCard.multisize)
            {
                if (selected)
                {
                    thing.ForeachPoint(delegate(Point pos, bool main)
                    {
                        v = pos.Position();
                        v.z -= 0.01f;
                        ELayer.screen.guide.passGuideFloor.Add(ref v, 7f);
                    });
                }
                return;
            }
            if (thing.TileType.IsBlockMount)
            {
                meshPass = ELayer.screen.guide.passGuideBlock;
            }
        }
        else if (i is TaskBuild)
        {
            Recipe recipe = (i as TaskBuild).recipe;
            if (recipe.MultiSize)
            {
                if (selected)
                {
                    i.InspectPoint.ForeachMultiSize(recipe.W, recipe.H, delegate(Point pos, bool main)
                    {
                        v = pos.Position();
                        v.z -= 0.01f;
                        ELayer.screen.guide.passGuideBlock.Add(ref v, 7f);
                    });
                }
                return;
            }
        }
        v.z -= 0.01f;
        meshPass.Add(ref v, 7f);
    }
References MeshPass.Add(), PCOrbit.crystal, Point.ForeachMultiSize(), Card.ForeachPoint(), BaseGameScreen.guide, Recipe.H, Point.HasBlockRecipe, IInspect.InspectPoint, IInspect.InspectPosition, TileType.IsBlockMount, Card.IsInstalled, Recipe.MultiSize, RenderRow.multisize, ScreenGuide.passGuideBlock, ScreenGuide.passGuideFloor, BaseTileMap.passIcon, BaseGameScreen.pcOrbit, Point.Position(), ELayer.screen, Thing.sourceCard, BaseGameScreen.tileMap, Card.TileType, and Recipe.W.
Referenced by OnUpdate().
Hide()
void UIInspector.Hide () inline
Definition at line 50 of file UIInspector.cs.
    {
        group = null;
        point = null;
        base.gameObject.SetActive(value: false);
    }
References group, and point.
Referenced by OnUpdate(), and Refresh().
Inspect() [1/2]
void UIInspector.Inspect (IInspect newTarget) inline
Definition at line 69 of file UIInspector.cs.
    {
        if (group?.FirstTarget != newTarget)
        {
            Inspect(InspectGroup.Create(newTarget));
        }
    }
References InspectGroup< T >.Create(), group, and Inspect().
Referenced by Inspect(), and InspectUnderMouse().
Inspect() [2/2]
void UIInspector.Inspect (InspectGroup g) inline
Definition at line 77 of file UIInspector.cs.
    {
        base.gameObject.SetActive(value: true);
        if (!initialized)
        {
            windows.Add(windowChara.window);
            initialized = true;
            mold = layoutButtons.CreateMold<UIButton>();
            IUISkin[] componentsInChildren = base.transform.GetComponentsInChildren<IUISkin>(includeInactive: true);
            for (int i = 0; i < componentsInChildren.Length; i++)
            {
                componentsInChildren[i].ApplySkin();
            }
            InitInspector();
        }
        group = g;
        soundPop.Play();
        Refresh();
    }
References IUISkin.ApplySkin(), group, initialized, ELayer.InitInspector(), layoutButtons, mold, Refresh(), soundPop, WindowController.window, windowChara, and Layer.windows.
InspectUnderMouse()
bool UIInspector.InspectUnderMouse () inline
Definition at line 57 of file UIInspector.cs.
    {
        if (!Scene.HitPoint.IsValid)
        {
            return false;
        }
        List<IInspect> source = ELayer.scene.mouseTarget.pos.ListInspectorTargets();
        point = Scene.HitPoint;
        Inspect(source.NextItem(group?.FirstTarget));
        return true;
    }
References InspectGroup< T >.FirstTarget, group, Scene.HitPoint, Inspect(), Point.IsValid, Point.ListInspectorTargets(), Scene.mouseTarget, point, PointTarget.pos, and ELayer.scene.
OnUpdate()
void UIInspector.OnUpdate () inline
Definition at line 97 of file UIInspector.cs.
    {
        if (group == null || !IsActive)
        {
            return;
        }
        if (!group.CanInspect())
        {
            Hide();
            return;
        }
        foreach (IInspect target in group.targets)
        {
            DrawHighlight(target, selected: true);
        }
    }
References InspectGroup< T >.CanInspect(), DrawHighlight(), group, Hide(), IsActive, and InspectGroup< T >.targets.
Refresh()
void UIInspector.Refresh () inline
Definition at line 114 of file UIInspector.cs.
    {
        if (!group.CanInspect())
        {
            Hide();
            return;
        }
        group.SetActions();
        layoutButtons.DestroyChildren();
        foreach (InspectGroup.Item item in group.actions)
        {
            if (!group.Solo && !item.multi)
            {
                continue;
            }
            UIButton uIButton = Util.Instantiate(mold, layoutButtons);
            uIButton.icon.sprite = SpriteSheet.Get(item.idSprite.IsEmpty("icon_" + item.text)) ?? uIButton.icon.sprite;
            uIButton.mainText.SetText((item.textFunc != null) ? item.textFunc() : item.text.lang());
            uIButton.onClick.AddListener(delegate
            {
                if (group.CanInspect())
                {
                    if (item.sound)
                    {
                        soundPop.Play();
                    }
                    foreach (IInspect target in group.targets)
                    {
                        item.action(target);
                    }
                }
                if (group == null || !group.CanInspect())
                {
                    Hide();
                }
                else
                {
                    Refresh();
                }
            });
            uIButton.RebuildLayout(recursive: true);
        }
        Chara chara = group.FirstTarget as Chara;
        bool flag = group.Solo && chara != null && chara.IsHomeMember();
        Room room = null;
        if (!flag && ELayer.core.IsGameStarted && point != null)
        {
            room = point.cell.room;
        }
        bool flag2 = room != null;
        windowChara.SetActive(flag);
        rectInfo.SetActive(!flag);
        rectRoom.SetActive(flag2);
        note.Clear();
        if (flag)
        {
            windowChara.SetChara(chara);
        }
        else if (group.Solo)
        {
            group.FirstTarget.WriteNote(note);
        }
        else
        {
            note.AddHeader(group.GetName());
            note.Build();
        }
        if (flag2)
        {
            UINote uINote = noteRoom;
            uINote.Clear();
            uINote.AddHeader("Room");
            uINote.AddText(room.points.Count.ToString() ?? "");
            uINote.Build();
        }
        layoutButtons.RebuildLayout(recursive: true);
        layoutBody.RebuildLayout();
        group.FirstTarget.OnInspect();
    }
References InspectGroup< T >.actions, InspectGroup< T >.CanInspect(), SpriteSheet.Get(), group, Hide(), UIButton.icon, item, layoutButtons, UIButton.mainText, mold, InspectGroup< T >.SetActions(), UIText.SetText(), InspectGroup< T >.Solo, InspectGroup< T >.targets, and Util.
Referenced by Inspect(), and SetVisible().
SetVisible()
void UIInspector.SetVisible (bool enable) inline
Definition at line 41 of file UIInspector.cs.
    {
        base.gameObject.SetActive(enable && group != null);
        if (enable && group != null)
        {
            Refresh();
        }
    }
References group, and Refresh().
Member Data Documentation
bg
UIImage UIInspector.bg
Definition at line 33 of file UIInspector.cs.
group
InspectGroup UIInspector.group
Definition at line 7 of file UIInspector.cs.
Referenced by Hide(), Inspect(), InspectUnderMouse(), OnUpdate(), Refresh(), and SetVisible().
initialized
bool UIInspector.initialized private
Definition at line 37 of file UIInspector.cs.
Referenced by Inspect().
layoutBody
LayoutGroup UIInspector.layoutBody
Definition at line 9 of file UIInspector.cs.
layoutButtons
LayoutGroup UIInspector.layoutButtons
Definition at line 11 of file UIInspector.cs.
Referenced by Inspect(), and Refresh().
modPos
Vector3 UIInspector.modPos
Definition at line 17 of file UIInspector.cs.
mold
UIButton UIInspector.mold
Definition at line 13 of file UIInspector.cs.
Referenced by Inspect(), and Refresh().
note
UINote UIInspector.note
Definition at line 27 of file UIInspector.cs.
noteRoom
UINote UIInspector.noteRoom
Definition at line 29 of file UIInspector.cs.
offset
Vector3 UIInspector.offset
Definition at line 15 of file UIInspector.cs.
point
Point UIInspector.point
Definition at line 35 of file UIInspector.cs.
Referenced by Hide(), and InspectUnderMouse().
rectInfo
RectTransform UIInspector.rectInfo
Definition at line 23 of file UIInspector.cs.
rectRoom
RectTransform UIInspector.rectRoom
Definition at line 25 of file UIInspector.cs.
soundPop
SoundData UIInspector.soundPop
Definition at line 19 of file UIInspector.cs.
Referenced by Inspect().
textName
UIText UIInspector.textName
Definition at line 31 of file UIInspector.cs.
windowChara
WindowChara UIInspector.windowChara
Definition at line 21 of file UIInspector.cs.
Referenced by Inspect().
Property Documentation
IsActive
bool UIInspector.IsActive get
Definition at line 39 of file UIInspector.cs.
Referenced by OnUpdate().
The documentation for this class was generated from the following file:
Elin/UIInspector.cs