Elin Decompiled Documentation: Hoard Class Reference
Hoard Class Reference
Classes
class Item
Public Types
enum Mode { all , lux , junk }
Public Member Functions
Hoard.Item AddRandom (int r, bool msg=true)
Hoard.Item AddRandom (bool msg=true)
Hoard.Item Add (string id)
Hoard.Item Add (string id, int num, bool msg=false)
Sprite GetSprite (string id)
GameObject GetActor (string id)
void Clear ()
Public Attributes
Dictionary< string, Hoard.Item > items = new Dictionary<string, Hoard.Item>()
List< Hoard.Item > list = new List<Hoard.Item>()
Hoard.Mode mode
int bg
int reflection = 100
int maxSounds = 28
int volume = 40
int hiScore
int score
bool shadow = true
bool voice = true
bool pixelPerfect
bool hentai
Private Member Functions
void OnDeserialized (StreamingContext context)
Additional Inherited Members
Static Public Member Functions inherited from EClass
static int rnd (int a)
static int curve (int a, int start, int step, int rate=75)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Static Public Attributes inherited from EClass
static Core core
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Detailed Description
Definition at line 8 of file Hoard.cs.
Member Enumeration Documentation
Mode
enum Hoard.Mode
Enumerator
all
lux
junk
Definition at line 138 of file Hoard.cs.
    {
        all,
        lux,
        junk
    }
Member Function Documentation
Add() [1/2]
Hoard.Item Hoard.Add (string id) inline
Definition at line 33 of file Hoard.cs.
    {
        SourceCollectible.Row row = EClass.sources.collectibles.map[id];
        int num = (row.num == 0) ? 10 : row.num;
        if (num != 1)
        {
            num *= 2;
        }
        Hoard.Item item = this.Add(row.id, num, false);
        item.random = true;
        return item;
    }
References Add(), SourceManager.collectibles, SourceCollectible.Row.id, SourceCollectible.Row.num, and EClass.sources.
Referenced by Add(), AddRandom(), LayerHoard.Generate(), LayerCollectible.OnAfterInit(), LayerHoard.OnClickClear(), and LayerHoard.Update().
Add() [2/2]
Hoard.Item Hoard.Add (string id, int num, bool msg = false) inline
Definition at line 46 of file Hoard.cs.
    {
        if (num == 0)
        {
            return this.items.TryGetValue(id, null);
        }
        Hoard.Item item = null;
        if (!this.items.TryGetValue(id, out item))
        {
            item = new Hoard.Item
            {
                id = id
            };
            this.list.Add(item);
            this.items[id] = item;
        }
        if (item.num == item.show)
        {
            item.show += num;
        }
        item.num += num;
        if (item.IsUnique && item.show > 1)
        {
            item.show = 1;
        }
        if (msg)
        {
            Msg.SetColor(EClass.Colors.GetRarityColor(item.Source.rarity, true));
            Msg.AquireItem(item.Name(num));
        }
        if (this.hentai)
        {
            item.show = item.num;
        }
        return item;
    }
References Msg.AquireItem(), EClass.Colors, ColorProfile.GetRarityColor(), hentai, Hoard.Item.IsUnique, items, list, Hoard.Item.Name(), Hoard.Item.num, Msg.SetColor(), Hoard.Item.show, and Hoard.Item.Source.
AddRandom() [1/2]
Hoard.Item Hoard.AddRandom (bool msg = true) inline
Definition at line 27 of file Hoard.cs.
    {
        string id = EClass.sources.collectibles.rows.RandomItem<SourceCollectible.Row>().id;
        return this.Add(id, 1, msg);
    }
References Add(), SourceManager.collectibles, and EClass.sources.
AddRandom() [2/2]
Hoard.Item Hoard.AddRandom (int r, bool msg = true) inline
Definition at line 19 of file Hoard.cs.
    {
        IEnumerable<SourceCollectible.Row> ie = from a in EClass.sources.collectibles.rows
        where a.rarity == r
        select a;
        return this.Add(ie.RandomItem<SourceCollectible.Row>().id, 1, msg);
    }
References Add(), and SourceCollectible.Row.id.
Referenced by LayerGacha.PlayGacha().
Clear()
void Hoard.Clear () inline
Definition at line 98 of file Hoard.cs.
    {
        this.items.Clear();
        this.list.Clear();
    }
References items, and list.
Referenced by LayerHoard.Generate(), and LayerHoard.OnClickClear().
GetActor()
GameObject Hoard.GetActor (string id) inline
Definition at line 89 of file Hoard.cs.
    {
        EClass.sources.collectibles.Init();
        SourceCollectible.Row row = EClass.sources.collectibles.map[id];
        SpriteRenderer spriteRenderer = UnityEngine.Object.Instantiate<SpriteRenderer>(ResourceCache.Load<SpriteRenderer>("UI/Layer/Hoard/Molds/" + row.prefab.IsEmpty("default")));
        spriteRenderer.sprite = this.GetSprite(id);
        return spriteRenderer.gameObject;
    }
References SourceManager.collectibles, GetSprite(), SourceCollectible.Row.prefab, and EClass.sources.
Referenced by HoardActor.Activate().
GetSprite()
Sprite Hoard.GetSprite (string id) inline
Definition at line 83 of file Hoard.cs.
    {
        SpriteSheet.Add("UI/Layer/Hoard/Molds/_sprites_hoard");
        return SpriteSheet.Get("_sprites_hoard_" + id);
    }
Referenced by GetActor(), UIHangIcon.Refresh(), LayerCollectible.RefreshInfo(), and LayerCollectible.SetButton().
OnDeserialized()
void Hoard.OnDeserialized (StreamingContext context) inline private
Definition at line 11 of file Hoard.cs.
    {
        foreach (Hoard.Item item in this.list)
        {
            this.items.Add(item.id, item);
        }
    }
References items.
Member Data Documentation
bg
int Hoard.bg
Definition at line 113 of file Hoard.cs.
hentai
bool Hoard.hentai
Definition at line 136 of file Hoard.cs.
Referenced by Add().
hiScore
int Hoard.hiScore
Definition at line 125 of file Hoard.cs.
Referenced by CollectibleActor.OnCollisionEnter2D(), and LayerHoard.Update().
items
Dictionary<string, Hoard.Item> Hoard.items = new Dictionary<string, Hoard.Item>()
Definition at line 104 of file Hoard.cs.
Referenced by HoardActor.Activate(), Add(), Clear(), LayerCollectible.OnAfterInit(), LayerHoard.OnAfterInit(), OnDeserialized(), LayerCollectible.Refresh(), and UIHangIcon.Refresh().
list
List<Hoard.Item> Hoard.list = new List<Hoard.Item>()
Definition at line 107 of file Hoard.cs.
Referenced by Add(), and Clear().
maxSounds
int Hoard.maxSounds = 28
Definition at line 119 of file Hoard.cs.
Referenced by LayerHoard.OnClickConfig(), CollectibleActor.OnCollisionEnter2D(), and LayerHoard.Update().
mode
Hoard.Mode Hoard.mode
Definition at line 110 of file Hoard.cs.
Referenced by HoardActor.Activate(), LayerHoard.OnClickNextMode(), and LayerHoard.Reset().
pixelPerfect
bool Hoard.pixelPerfect
Definition at line 134 of file Hoard.cs.
Referenced by LayerHoard.OnClickConfig(), and HoardActor.RefreshZoom().
reflection
int Hoard.reflection = 100
Definition at line 116 of file Hoard.cs.
Referenced by LayerHoard.OnClickConfig(), and HoardActor.RefreshBG().
score
int Hoard.score
Definition at line 128 of file Hoard.cs.
Referenced by CollectibleActor.OnCollisionEnter2D(), and LayerHoard.Update().
shadow
bool Hoard.shadow = true
Definition at line 130 of file Hoard.cs.
Referenced by LayerHoard.OnClickConfig(), and HoardActor.Update().
voice
bool Hoard.voice = true
Definition at line 132 of file Hoard.cs.
Referenced by HoardActor.Activate(), and LayerHoard.OnClickConfig().
volume
int Hoard.volume = 40
Definition at line 122 of file Hoard.cs.
Referenced by LayerHoard.OnClickConfig(), CollectibleActor.OnCollisionEnter2D(), and CollectibleActor.PlaySound().
The documentation for this class was generated from the following file:
Elin/Hoard.cs