Elin Decompiled Documentation: DramaInvokeDetail Class Reference
DramaInvokeDetail Class Reference
Public Member Functions
DramaInvokeDetail (MethodInfo method, string contract=null)
bool SafeInvoke (DramaManager dm, Dictionary< string, string > line, params string[] parameters)
Properties
MethodInfo Method [get]
string Contract [get]
bool NoDiscard [get]
bool ParamPassthrough [get]
Private Member Functions
void ValidateSignature ()
Func< DramaManager, Dictionary< string, string >, string[], bool > BuildDelegate ()
Static Private Member Functions
static Expression CreateConvertExpression (Expression expr, ParameterInfo parameter)
static MethodInfo GetTryParseMethod (Type type)
Private Attributes
Func< DramaManager, Dictionary< string, string >, string[], bool > _compiled
Static Private Attributes
static readonly MethodInfo _stringIsNullOrEmpty = typeof(string).GetMethod("IsNullOrEmpty", new Type[1] { typeof(string) })
static readonly ConstructorInfo _argumentException = typeof(ArgumentException).GetConstructor(new Type[1] { typeof(string) })
Detailed Description
Definition at line 8 of file DramaInvokeDetail.cs.
Constructor & Destructor Documentation
DramaInvokeDetail()
DramaInvokeDetail.DramaInvokeDetail (MethodInfo method, string contract = null) inline
Definition at line 24 of file DramaInvokeDetail.cs.
    {
        Method = method;
        Contract = contract;
        ValidateSignature();
    }
References Contract, Method, and ValidateSignature().
Member Function Documentation
BuildDelegate()
Func< DramaManager, Dictionary< string, string >, string[], bool > DramaInvokeDetail.BuildDelegate () inline private
Definition at line 51 of file DramaInvokeDetail.cs.
    {
        ParameterInfo[] parameters = Method.GetParameters();
        ParameterExpression parameterExpression = Expression.Parameter(typeof(DramaManager), "dm");
        ParameterExpression parameterExpression2 = Expression.Parameter(typeof(Dictionary<string, string>), "line");
        ParameterExpression parameterExpression3 = Expression.Parameter(typeof(string[]), "parameters");
        List<Expression> list = new List<Expression> { parameterExpression, parameterExpression2 };
        if (parameters.Length == 3 && parameters[2].ParameterType == typeof(string[]))
        {
            list.Add(parameterExpression3);
        }
        else if (parameters.Length > 2)
        {
            for (int i = 2; i < parameters.Length; i++)
            {
                ParameterInfo parameter = parameters[i];
                int num = i - 2;
                Expression expr = Expression.Condition(Expression.LessThan(Expression.Constant(num), Expression.ArrayLength(parameterExpression3)), Expression.ArrayIndex(parameterExpression3, Expression.Constant(num)), Expression.Constant(null, typeof(string)));
                list.Add(CreateConvertExpression(expr, parameter));
            }
        }
        return Expression.Lambda<Func<DramaManager, Dictionary<string, string>, string[], bool>>(Expression.Call(null, Method, list), new ParameterExpression[3] { parameterExpression, parameterExpression2, parameterExpression3 }).Compile();
    }
References CreateConvertExpression(), and Method.
Referenced by SafeInvoke().
CreateConvertExpression()
static Expression DramaInvokeDetail.CreateConvertExpression (Expression expr, ParameterInfo parameter) inline static private
Definition at line 75 of file DramaInvokeDetail.cs.
    {
        Type parameterType = parameter.ParameterType;
        bool isOptional = parameter.IsOptional;
        object defaultValue = parameter.DefaultValue;
        string text = $"required action parameter #{parameter.Position - 2} '{parameter.Name}'";
        if (parameterType == typeof(string))
        {
            MethodCallExpression test = Expression.Call(_stringIsNullOrEmpty, expr);
            if (isOptional)
            {
                ConstantExpression ifTrue = Expression.Constant(defaultValue, typeof(string));
                return Expression.Condition(test, ifTrue, expr);
            }
            string value = "#drama " + text + " cannot be empty";
            UnaryExpression ifTrue2 = Expression.Throw(Expression.New(_argumentException, Expression.Constant(value)), typeof(string));
            return Expression.Condition(test, ifTrue2, expr);
        }
        MethodInfo tryParseMethod = GetTryParseMethod(parameterType);
        if (tryParseMethod == null)
        {
            throw new NotSupportedException("#drama type '" + parameterType.Name + "' does not have a public static TryParse method");
        }
        ParameterExpression parameterExpression = Expression.Variable(parameterType, "parsed");
        Expression test2 = Expression.Call(tryParseMethod, expr, parameterExpression);
        Expression expression;
        if (isOptional)
        {
            expression = Expression.Constant(defaultValue, parameterType);
        }
        else
        {
            string value2 = "#drama can't parse " + text + " to type '" + parameterType.Name + "'";
            expression = Expression.Throw(Expression.New(_argumentException, Expression.Constant(value2)), parameterType);
        }
        ConditionalExpression conditionalExpression = Expression.Condition(Expression.Call(_stringIsNullOrEmpty, expr), expression, Expression.Condition(test2, parameterExpression, expression));
        return Expression.Block(new ParameterExpression[1] { parameterExpression }, conditionalExpression);
    }
References $, _argumentException, _stringIsNullOrEmpty, and GetTryParseMethod().
Referenced by BuildDelegate().
GetTryParseMethod()
static MethodInfo DramaInvokeDetail.GetTryParseMethod (Type type) inline static private
Definition at line 114 of file DramaInvokeDetail.cs.
    {
        if (type.IsEnum)
        {
            MethodInfo method = typeof(Enum).GetMethod("TryParse", BindingFlags.Static | BindingFlags.Public, null, new Type[2]
            {
                typeof(string),
                type.MakeByRefType()
            }, null);
            if (method != null)
            {
                return method.MakeGenericMethod(type);
            }
        }
        return type.GetMethod("TryParse", new Type[2]
        {
            typeof(string),
            type.MakeByRefType()
        });
    }
Referenced by CreateConvertExpression().
SafeInvoke()
bool DramaInvokeDetail.SafeInvoke (DramaManager dm, Dictionary< string, string > line, params string[] parameters) inline
Definition at line 135 of file DramaInvokeDetail.cs.
    {
        if (Method == null)
        {
            return true;
        }
        try
        {
            if (_compiled == null)
            {
                _compiled = BuildDelegate();
            }
            return _compiled(dm, line, parameters);
        }
        catch (Exception ex)
        {
            ModUtil.LogModError("exception while invoking drama action '" + Method.TryToString() + "'\n" + ex.Message, new FileInfo(dm.path));
            Debug.LogException(ex);
            return false;
        }
    }
References _compiled, BuildDelegate(), Debug, Method, and DramaManager.path.
ValidateSignature()
void DramaInvokeDetail.ValidateSignature () inline private
Definition at line 31 of file DramaInvokeDetail.cs.
    {
        if (!(Method == null))
        {
            if (Method.ContainsGenericParameters)
            {
                throw new NotSupportedException("#drama action cannot contain generic parameters");
            }
            if (!Method.IsStatic)
            {
                throw new NotSupportedException("#drama action must be static");
            }
            ParameterInfo[] parameters = Method.GetParameters();
            if (parameters.Length < 2 || parameters[0].ParameterType != typeof(DramaManager) || parameters[1].ParameterType != typeof(Dictionary<string, string>) || Method.ReturnType != typeof(bool))
            {
                throw new ArgumentException("#drama action parameters must start with 'DramaManager dm, Dictionary<string, string>' and returns 'bool'");
            }
        }
    }
References Method.
Referenced by DramaInvokeDetail().
Member Data Documentation
_argumentException
readonly ConstructorInfo DramaInvokeDetail._argumentException = typeof(ArgumentException).GetConstructor(new Type[1] { typeof(string) }) static private
Definition at line 14 of file DramaInvokeDetail.cs.
Referenced by CreateConvertExpression().
_compiled
Func<DramaManager, Dictionary<string, string>, string[], bool> DramaInvokeDetail._compiled private
Definition at line 10 of file DramaInvokeDetail.cs.
Referenced by SafeInvoke().
_stringIsNullOrEmpty
readonly MethodInfo DramaInvokeDetail._stringIsNullOrEmpty = typeof(string).GetMethod("IsNullOrEmpty", new Type[1] { typeof(string) }) static private
Definition at line 12 of file DramaInvokeDetail.cs.
Referenced by CreateConvertExpression().
Property Documentation
Contract
string DramaInvokeDetail.Contract get
Definition at line 18 of file DramaInvokeDetail.cs.
{ get; }
Referenced by DramaInvokeDetail().
Method
MethodInfo DramaInvokeDetail.Method get
Definition at line 16 of file DramaInvokeDetail.cs.
{ get; }
Referenced by BuildDelegate(), DramaInvokeDetail(), SafeInvoke(), and ValidateSignature().
NoDiscard
bool DramaInvokeDetail.NoDiscard get
Definition at line 20 of file DramaInvokeDetail.cs.
ParamPassthrough
bool DramaInvokeDetail.ParamPassthrough get
Definition at line 22 of file DramaInvokeDetail.cs.
The documentation for this class was generated from the following file:
Elin/DramaInvokeDetail.cs