Elin Decompiled Documentation: UISelectableGroup Class Reference
UISelectableGroup Class Reference
Public Types
enum ColorType { General = 0 , Tab = 5 , DontChange = 99 }
Public Member Functions
void ApplySkin ()
UIButton AddButton (UIButton mold, string text)
void RemoveButton (UIButton button)
void SetButton (UIButton button)
void SetGroup (int id)
virtual void Init (int index=0, UnityAction< int > action=null, bool directChildren=false)
void SetLoop ()
void Select (UIButton button, bool check=true)
void Select (int id)
void Select (string id)
void Select (Func< UIButton, bool > func)
void RefreshButtons ()
void ForceDefaultColor (bool useNoSelection=false)
void ToggleInteractable (bool enable)
void SetColors ()
void ApplySkin ()
Public Attributes
ColorType colorType
LayoutGroup layoutButtons
int selectOnInitialize
bool colorWhenSelected
bool checkbox
bool loopNavigation
bool autoInitialize = true
bool selectOnClick = true
bool useIcon
bool useTransition = true
bool fixRefreshButtons
bool colorWhenDisabled
Color colorDefault
Color colorSelected
Color colorNoSelection
Color colorDisabled
SkinRootStatic rootSkin
UIButton selected
List< UIButton > list = new List<UIButton>()
UnityAction< int > onClick
Properties
SkinRootStatic Skin [get]
Private Member Functions
void Awake ()
void OnDisable ()
void LateUpdate ()
Private Attributes
SkinColorProfileEx.GroupColors colors
bool refreshButtons
Detailed Description
Definition at line 7 of file UISelectableGroup.cs.
Member Enumeration Documentation
ColorType
enum UISelectableGroup.ColorType
Enumerator
General
Tab
DontChange
Definition at line 9 of file UISelectableGroup.cs.
    {
        General = 0,
        Tab = 5,
        DontChange = 99
    }
Member Function Documentation
AddButton()
UIButton UISelectableGroup.AddButton (UIButton mold, string text) inline
Definition at line 105 of file UISelectableGroup.cs.
    {
        UIButton uIButton = Util.Instantiate(mold, layoutButtons);
        uIButton.mainText.text = text;
        return uIButton;
    }
References layoutButtons, and Util.
ApplySkin()
void UISelectableGroup.ApplySkin () inline
Implements IUISkin.
Definition at line 91 of file UISelectableGroup.cs.
    {
        SetColors();
        RefreshButtons();
    }
References RefreshButtons(), and SetColors().
Awake()
void UISelectableGroup.Awake () inline private
Definition at line 74 of file UISelectableGroup.cs.
    {
        SetColors();
        if (!layoutButtons)
        {
            layoutButtons = GetComponent<LayoutGroup>();
        }
        if (autoInitialize)
        {
            Init(selectOnInitialize);
        }
        if (fixRefreshButtons)
        {
            refreshButtons = true;
        }
    }
References autoInitialize, fixRefreshButtons, Init(), layoutButtons, refreshButtons, selectOnInitialize, and SetColors().
ForceDefaultColor()
void UISelectableGroup.ForceDefaultColor (bool useNoSelection = false) inline
Definition at line 309 of file UISelectableGroup.cs.
    {
        selected = null;
        foreach (UIButton item in list)
        {
            item.SetCheck(check: false);
            if (useNoSelection)
            {
                if (useIcon)
                {
                    item.icon.color = colorNoSelection;
                }
                else
                {
                    item.image.color = colorNoSelection;
                }
            }
            else if (useIcon)
            {
                item.icon.color = colorDefault;
            }
            else
            {
                item.image.color = colorDefault;
            }
        }
    }
References colorDefault, colorNoSelection, item, list, selected, and useIcon.
Init()
virtual void UISelectableGroup.Init (int index = 0, UnityAction< int > action = null, bool directChildren = false) inline virtual
Definition at line 147 of file UISelectableGroup.cs.
    {
        list.Clear();
        if (action != null)
        {
            onClick = action;
        }
        UIButton[] array = (directChildren ? base.transform.GetComponentsInDirectChildren<UIButton>().ToArray() : base.transform.GetComponentsInChildren<UIButton>(includeInactive: true));
        foreach (UIButton uIButton in array)
        {
            if (!uIButton.tag.Contains("IgnoreSelectable") && uIButton.gameObject.activeSelf)
            {
                SetButton(uIButton);
            }
        }
        if (checkbox)
        {
            selected = null;
            RefreshButtons();
        }
        else
        {
            Select(index);
        }
    }
References checkbox, list, onClick, RefreshButtons(), Select(), selected, and SetButton().
Referenced by Awake(), Window.BuildTabs(), BuildMenu.Init(), UIMagicChest.Init(), ContentPopulation.OnSwitchContent(), ActionHint.Refresh(), UIRecipeInfo.Refresh(), UIList.Refresh(), ContentConfigGame.SetGroup(), LayerConfig.SetGroup(), and TerrainMenu.Show().
LateUpdate()
void UISelectableGroup.LateUpdate () inline private
Definition at line 364 of file UISelectableGroup.cs.
    {
        if (refreshButtons)
        {
            refreshButtons = false;
            RefreshButtons();
        }
    }
References refreshButtons, and RefreshButtons().
OnDisable()
void UISelectableGroup.OnDisable () inline private
Definition at line 97 of file UISelectableGroup.cs.
    {
        if (fixRefreshButtons)
        {
            refreshButtons = true;
        }
    }
References fixRefreshButtons, and refreshButtons.
RefreshButtons()
void UISelectableGroup.RefreshButtons () inline
Definition at line 230 of file UISelectableGroup.cs.
    {
        foreach (UIButton item in list)
        {
            if (!item || item.gameObject == null)
            {
                continue;
            }
            if (colorWhenDisabled && !item.interactable)
            {
                item.image.color = colorDisabled;
                continue;
            }
            if (checkbox)
            {
                if (useIcon)
                {
                    item.icon.color = colorDefault;
                }
                else
                {
                    item.image.color = colorDefault;
                }
                if (useTransition)
                {
                    item.selected = false;
                    item.DoNormalTransition();
                }
                break;
            }
            if (!selected && colorWhenSelected)
            {
                item.SetCheck(check: false);
                if (useIcon)
                {
                    item.icon.color = colorNoSelection;
                }
                else
                {
                    item.image.color = colorNoSelection;
                }
            }
            else if ((bool)selected && item == selected)
            {
                item.SetCheck(check: true);
                if (useIcon)
                {
                    item.icon.color = colorSelected;
                }
                else
                {
                    item.image.color = colorSelected;
                }
                if (useTransition)
                {
                    item.selected = true;
                    item.DoNormalTransition();
                }
            }
            else
            {
                item.SetCheck(check: false);
                if (useIcon)
                {
                    item.icon.color = colorDefault;
                }
                else
                {
                    item.image.color = colorDefault;
                }
                if (useTransition)
                {
                    item.selected = false;
                    item.DoNormalTransition();
                }
            }
        }
    }
References checkbox, colorDefault, colorDisabled, colorNoSelection, colorSelected, colorWhenDisabled, colorWhenSelected, item, list, selected, useIcon, and useTransition.
Referenced by ApplySkin(), Init(), LateUpdate(), LayerCraft.OnCompleteCraft(), BuildMenu.Refresh(), and Select().
RemoveButton()
void UISelectableGroup.RemoveButton (UIButton button) inline
Definition at line 112 of file UISelectableGroup.cs.
    {
        list.Remove(button);
    }
References list.
Select() [1/4]
void UISelectableGroup.Select (Func< UIButton, bool > func) inline
Definition at line 218 of file UISelectableGroup.cs.
    {
        foreach (UIButton item in list)
        {
            if (func(item))
            {
                Select(item);
                break;
            }
        }
    }
References item, list, and Select().
Select() [2/4]
void UISelectableGroup.Select (int id) inline
Definition at line 202 of file UISelectableGroup.cs.
    {
        Select((id == -1 || id >= list.Count) ? null : list[id]);
    }
References list, and Select().
Select() [3/4]
void UISelectableGroup.Select (string id) inline
Definition at line 207 of file UISelectableGroup.cs.
    {
        foreach (UIButton item in list)
        {
            if (item.name == id)
            {
                Select(item);
            }
        }
    }
References item, list, and Select().
Select() [4/4]
void UISelectableGroup.Select (UIButton button, bool check = true) inline
Definition at line 188 of file UISelectableGroup.cs.
    {
        if (checkbox)
        {
            selected = null;
            button.SetCheck(check);
        }
        else if (!(selected == button))
        {
            selected = button;
            RefreshButtons();
        }
    }
References checkbox, RefreshButtons(), selected, and UIButton.SetCheck().
Referenced by UIMagicChest.Init(), Init(), UIMagicChest.OnAfterRedraw(), UIRecipeInfo.OnRotate(), UIList.OnSelect(), BuildMenu.RefreshCategory(), LayerWorldSetting.RefreshTemplate(), Select(), UIList.Select(), BuildMenu.SelectCategory(), Window.SwitchContent(), and UIButton.Toggle().
SetButton()
void UISelectableGroup.SetButton (UIButton button) inline
Definition at line 117 of file UISelectableGroup.cs.
    {
        list.Add(button);
        SetGroup(list.Count - 1);
        if (checkbox)
        {
            button.selected = false;
            button.DoNormalTransition();
        }
    }
References checkbox, UIButton.DoNormalTransition(), list, and SetGroup().
Referenced by Init().
SetColors()
void UISelectableGroup.SetColors () inline
Definition at line 345 of file UISelectableGroup.cs.
    {
        if (colorType != ColorType.DontChange)
        {
            SkinColorProfileEx colorsEx = Skin.ColorsEx;
            if (colorType == ColorType.Tab)
            {
                colors = colorsEx.tab;
            }
            else
            {
                colors = colorsEx.general;
            }
            colorDefault = colors.colorDefault;
            colorSelected = colors.colorSelected;
            colorNoSelection = colors.colorNoSelection;
        }
    }
References colorDefault, colorNoSelection, colors, colorSelected, SkinRootStatic.ColorsEx, colorType, SkinColorProfileEx.general, Skin, and SkinColorProfileEx.tab.
Referenced by ApplySkin(), and Awake().
SetGroup()
void UISelectableGroup.SetGroup (int id) inline
Definition at line 128 of file UISelectableGroup.cs.
    {
        UIButton uIButton = list[id];
        uIButton.group = this;
        if (onClick != null)
        {
            uIButton.onClick.RemoveAllListeners();
            uIButton.onClick.AddListener(delegate
            {
                onClick(id);
            });
        }
        if (selectOnClick)
        {
            uIButton.onClick.RemoveListener(uIButton.Toggle);
            uIButton.onClick.AddListener(uIButton.Toggle);
        }
    }
References list, onClick, selectOnClick, and UIButton.Toggle().
Referenced by SetButton().
SetLoop()
void UISelectableGroup.SetLoop () inline
Definition at line 173 of file UISelectableGroup.cs.
    {
        if (loopNavigation)
        {
            for (int i = 0; i < list.Count; i++)
            {
                Navigation navigation = list[i].navigation;
                navigation.mode = Navigation.Mode.Explicit;
                navigation.selectOnLeft = ((i == 0) ? list[list.Count - 1] : list[i - 1]);
                navigation.selectOnRight = ((i + 1 == list.Count) ? list[0] : list[i + 1]);
                list[i].navigation = navigation;
            }
        }
    }
References list, and loopNavigation.
ToggleInteractable()
void UISelectableGroup.ToggleInteractable (bool enable) inline
Definition at line 337 of file UISelectableGroup.cs.
    {
        foreach (UIButton item in list)
        {
            item.interactable = enable;
        }
    }
References item, and list.
Referenced by AM_Dig.OnSelectEnd(), AM_Dig.OnSelectStart(), and ActionHint.Refresh().
Member Data Documentation
autoInitialize
bool UISelectableGroup.autoInitialize = true
Definition at line 28 of file UISelectableGroup.cs.
Referenced by Awake().
checkbox
bool UISelectableGroup.checkbox
Definition at line 24 of file UISelectableGroup.cs.
Referenced by Init(), RefreshButtons(), Select(), and SetButton().
colorDefault
Color UISelectableGroup.colorDefault
Definition at line 40 of file UISelectableGroup.cs.
Referenced by ForceDefaultColor(), RefreshButtons(), and SetColors().
colorDisabled
Color UISelectableGroup.colorDisabled
Definition at line 46 of file UISelectableGroup.cs.
Referenced by RefreshButtons().
colorNoSelection
Color UISelectableGroup.colorNoSelection
Definition at line 44 of file UISelectableGroup.cs.
Referenced by ForceDefaultColor(), RefreshButtons(), and SetColors().
colors
SkinColorProfileEx.GroupColors UISelectableGroup.colors private
Definition at line 50 of file UISelectableGroup.cs.
Referenced by SetColors().
colorSelected
Color UISelectableGroup.colorSelected
Definition at line 42 of file UISelectableGroup.cs.
Referenced by RefreshButtons(), and SetColors().
colorType
ColorType UISelectableGroup.colorType
Definition at line 16 of file UISelectableGroup.cs.
Referenced by SetColors().
colorWhenDisabled
bool UISelectableGroup.colorWhenDisabled
Definition at line 38 of file UISelectableGroup.cs.
Referenced by RefreshButtons().
colorWhenSelected
bool UISelectableGroup.colorWhenSelected
Definition at line 22 of file UISelectableGroup.cs.
Referenced by RefreshButtons().
fixRefreshButtons
bool UISelectableGroup.fixRefreshButtons
Definition at line 36 of file UISelectableGroup.cs.
Referenced by Awake(), and OnDisable().
layoutButtons
LayoutGroup UISelectableGroup.layoutButtons
Definition at line 18 of file UISelectableGroup.cs.
Referenced by AddButton(), and Awake().
list
List<UIButton> UISelectableGroup.list = new List<UIButton>()
Definition at line 56 of file UISelectableGroup.cs.
Referenced by ForceDefaultColor(), Init(), RefreshButtons(), RemoveButton(), Select(), SetButton(), SetGroup(), SetLoop(), TerrainMenu.Show(), and ToggleInteractable().
loopNavigation
bool UISelectableGroup.loopNavigation
Definition at line 26 of file UISelectableGroup.cs.
Referenced by SetLoop().
onClick
UnityAction<int> UISelectableGroup.onClick
Definition at line 58 of file UISelectableGroup.cs.
Referenced by Init(), and SetGroup().
refreshButtons
bool UISelectableGroup.refreshButtons private
Definition at line 60 of file UISelectableGroup.cs.
Referenced by Awake(), LateUpdate(), and OnDisable().
rootSkin
SkinRootStatic UISelectableGroup.rootSkin
Definition at line 48 of file UISelectableGroup.cs.
selected
UIButton UISelectableGroup.selected
Definition at line 53 of file UISelectableGroup.cs.
Referenced by ForceDefaultColor(), Init(), RefreshButtons(), and Select().
selectOnClick
bool UISelectableGroup.selectOnClick = true
Definition at line 30 of file UISelectableGroup.cs.
Referenced by SetGroup().
selectOnInitialize
int UISelectableGroup.selectOnInitialize
Definition at line 20 of file UISelectableGroup.cs.
Referenced by Awake().
useIcon
bool UISelectableGroup.useIcon
Definition at line 32 of file UISelectableGroup.cs.
Referenced by ForceDefaultColor(), and RefreshButtons().
useTransition
bool UISelectableGroup.useTransition = true
Definition at line 34 of file UISelectableGroup.cs.
Referenced by RefreshButtons().
Property Documentation
Skin
SkinRootStatic UISelectableGroup.Skin get
Definition at line 62 of file UISelectableGroup.cs.
    {
        get
        {
            if (!(rootSkin != null))
            {
                return SkinManager.Instance.currentSkin;
            }
            return rootSkin;
        }
    }
Referenced by SetColors().
The documentation for this class was generated from the following file:
Elin/Plugins.UI/UISelectableGroup.cs