Elin Decompiled Documentation: WindowChara Class Reference
WindowChara Class Reference
Public Member Functions
void SetChara (Chara c)
override void OnSwitchContent (Window window)
void SetPortraitBG (int a)
void SetPortraitFrame (int a)
void ToggleFeatMode ()
void RefreshFeatMode ()
void Refresh ()
void RefreshStatic ()
void RefreshStatus ()
void AddNeeds (Stats st)
void AddStatus (BaseStats st)
void RefreshProfile ()
void RefreshEquipment (UIList list, bool sort=true)
void RefreshInfo ()
void OnClickPortrait ()
void RefreshSkill (int idTab)
virtual void OnSwitchContent (Window window)
Static Public Member Functions
static void RefreshNote (Chara chara, UINote n, bool shortMode=false)
Public Attributes
Chara chara
Portrait portrait
UIText textMood
UIText textHealth
UIText textName
UIText textAlias
UIText textTitle
UIText textBio
UIText textBio2
UIText textBio3
UIText textBirthday
UIText textFaction
UIText textFaith
UIText textHome
UIText textMom
UIText textDad
UIText textBirthplace
UIText textLike
UIText textHobby
UIText textKarma
UIText textSAN
UIText textFame
UIText textMoney
UIText textTax
UIText textTerritory
UIText textIncome
UIText textAssets
UIText textDeposit
UIText textDeepest
UIText textCurrentZone
UIText textHomeZone
UIList listAttaribute
UIList listEquipment
UIList listEquipment2
UINote note
PUIExampleRPGStats graph
UIText textStability
UIText textLaw
UIText textAffection
UIText textDominance
UIText textExtroversion
UIText textFavArmor
UIText textDV
UIText textStyle
LayoutGroup layoutNeeds
LayoutGroup layoutStatus
GridLayoutGroup gridEquip
UIScrollView scrollSkill
ButtonElement buttonMana
ButtonElement buttonLife
ButtonElement buttonVigor
ButtonElement buttonSpeed
UIItem moldStats
UIItem moldNeeds
UIHeader moldHeader
UIHeader moldHeader2
UIHeader headerEquip
UIList moldListSkill
UIList moldListResist
UIList moldListFeat
UIList moldListFeatPurchase
Transform contentList
RectTransform rectEquip
UIButton buttonFeatMode
UIButton buttonFeatOption
Image imageView
Sprite mask
Sprite maskResist
Material matItem
Color colorUnequipped
Vector2 equipPos
bool featMode
float barColor1
float barColor2
Public Attributes inherited from WindowController
Window window
Static Public Attributes
static WindowChara Instance
Properties
Biography bio [get]
Private Member Functions
void Update ()
void OnApplicationFocus (bool focus)
Private Attributes
UIHeader _header
Detailed Description
Definition at line 8 of file WindowChara.cs.
Member Function Documentation
AddNeeds()
void WindowChara.AddNeeds (Stats st) inline
Definition at line 315 of file WindowChara.cs.
    {
        UIItem uIItem = Util.Instantiate(moldNeeds, layoutNeeds);
        uIItem.text1.SetText(st.source.GetName());
        if (st.GetText().IsEmpty())
        {
            uIItem.text2.SetActive(enable: false);
        }
        else
        {
            st.SetText(uIItem.text2);
        }
        UIBar componentInChildren = uIItem.GetComponentInChildren<UIBar>();
        componentInChildren.Refresh(st.value, st.max);
        componentInChildren.image.color = st.GetColor().Multiply(barColor1, barColor2);
    }
References barColor1, barColor2, Stats.GetColor(), Stats.GetText(), layoutNeeds, Stats.max, moldNeeds, UIBar.Refresh(), UIText.SetText(), BaseStats.SetText(), BaseStats.source, UIItem.text1, UIItem.text2, Util, and Stats.value.
AddStatus()
void WindowChara.AddStatus (BaseStats st) inline
Definition at line 332 of file WindowChara.cs.
    {
        string text = st?.GetText() ?? "noItem".lang();
        if (text.IsEmpty())
        {
            return;
        }
        UIItem uIItem = Util.Instantiate(moldStats, layoutStatus);
        if (st == null)
        {
            uIItem.text1.SetText(text, FontColor.Passive);
            uIItem.button1.interactable = false;
        }
        else if (text.IsEmpty())
        {
            uIItem.text1.SetText(st.source.GetName());
        }
        else
        {
            st.SetText(uIItem.text1);
            uIItem.image1.sprite = st.GetSprite();
            uIItem.image1.SetNativeSize();
        }
        if (st != null)
        {
            uIItem.button1.SetTooltip(delegate(UITooltip t)
            {
                st.WriteNote(t.note);
            });
        }
    }
References UIItem.button1, BaseStats.GetSprite(), BaseStats.GetText(), UIItem.image1, layoutStatus, moldStats, UITooltip.note, UIText.SetText(), BaseStats.SetText(), UIButton.SetTooltip(), BaseStats.source, UIItem.text1, Util, and BaseStats.WriteNote().
Referenced by RefreshStatus().
OnApplicationFocus()
void WindowChara.OnApplicationFocus (bool focus) inline private
Definition at line 851 of file WindowChara.cs.
    {
        if (focus && window.idTab == 5)
        {
            RefreshNote(chara, note);
        }
    }
OnClickPortrait()
void WindowChara.OnClickPortrait () inline
Definition at line 490 of file WindowChara.cs.
    {
        if (chara.IsPC)
        {
            EClass.ui.AddLayer<LayerEditPCC>().Activate(chara, UIPCC.Mode.Body, null, delegate
            {
                portrait.SetChara(chara);
            });
        }
        else
        {
            SE.Beep();
        }
    }
References chara, Chara.IsPC, portrait, Portrait.SetChara(), and EClass.ui.
OnSwitchContent()
override void WindowChara.OnSwitchContent (Window window) inline virtual
Reimplemented from WindowController.
Definition at line 185 of file WindowChara.cs.
    {
        if (chara != null)
        {
            RefreshStatic();
            int idTab = window.idTab;
            if (idTab == 0)
            {
                RefreshInfo();
                RefreshProfile();
            }
            else
            {
                RefreshSkill(idTab);
            }
            bool flag = idTab == 3 || idTab == 4;
            scrollSkill.horizontal = flag;
            scrollSkill.content.anchoredPosition = new Vector2(0f, 0f);
            imageView.sprite = (flag ? maskResist : mask);
            if (flag)
            {
                RefreshEquipment(listEquipment2);
            }
            listEquipment2.transform.parent.SetActive(flag);
            buttonFeatMode.SetActive(idTab == 2 && chara.IsPC);
            buttonFeatOption.SetActive(idTab == 2 && chara.IsPC && featMode);
        }
    }
References buttonFeatMode, buttonFeatOption, chara, featMode, Window.idTab, Chara.IsPC, listEquipment2, mask, maskResist, UIList.parent, RefreshEquipment(), RefreshInfo(), RefreshProfile(), RefreshSkill(), RefreshStatic(), and WindowController.window.
Referenced by Refresh(), and SetChara().
Refresh()
void WindowChara.Refresh () inline
Definition at line 258 of file WindowChara.cs.
    {
        OnSwitchContent(window);
    }
References OnSwitchContent(), and WindowController.window.
Referenced by LayerChara.Refresh().
RefreshEquipment()
void WindowChara.RefreshEquipment (UIList list, bool sort = true) inline
Definition at line 397 of file WindowChara.cs.
    {
        string text = chara.GetFavWeaponSkill()?.Name ?? Element.Get(100).GetText();
        text = text + "/" + (chara.GetFavArmorSkill()?.Name ?? Element.Get(120).GetText());
        textFavArmor.SetText(text);
        list.Clear();
        list.callbacks = new UIList.Callback<BodySlot, UIItem>
        {
            onClick = delegate
            {
            },
            onInstantiate = delegate(BodySlot a, UIItem b)
            {
                if (a.elementId == 0)
                {
                    b.button1.interactable = false;
                }
                else
                {
                    Thing thing = (Thing)(b.refObj = a.thing);
                    if (thing != null)
                    {
                        b.button1.icon.material = matItem;
                        thing.SetImage(b.button1.icon);
                    }
                    else
                    {
                        b.button1.icon.material = null;
                        b.button1.icon.sprite = SpriteSheet.Get("Media/Graphics/Icon/Element/", "eq_" + a.element.alias);
                        b.button1.icon.color = colorUnequipped;
                        b.button1.icon.SetNativeSize();
                    }
                    b.button1.SetTooltip(delegate(UITooltip tt)
                    {
                        if (a.thing != null)
{
                            a.thing.WriteNote(tt.note);
                        }
                        else
{
                            tt.note.Clear();
                            tt.note.AddHeader(a.name);
                            tt.note.AddText("noEQ".lang());
                            if (a.elementId == 35)
{
                                Thing.AddAttackEvaluation(tt.note, chara);
                            }
                        }
                        tt.note.Build();
                    });
                }
            },
            onSort = (BodySlot a, UIList.SortMode m) => (a.element.id != 0) ? chara.body.GetSortVal(a) : (-99999)
        };
        foreach (BodySlot slot in chara.body.slots)
        {
            if (slot.elementId != 44)
            {
                list.Add(slot);
            }
        }
        if (list.items.Count < 12)
        {
            int num = 12 - list.items.Count;
            for (int i = 0; i < num; i++)
            {
                list.Add(new BodySlot());
            }
        }
        if (list.items.Count > 18)
        {
            gridEquip.cellSize = new Vector2(52f, 44f);
            gridEquip.spacing = new Vector2(-6f, -12f);
        }
        if (sort)
        {
            list.Sort();
        }
        list.Refresh();
    }
References Thing.AddAttackEvaluation(), UINote.AddHeader(), UINote.AddText(), Chara.body, UINote.Build(), UIItem.button1, chara, UIList.Clear(), UINote.Clear(), colorUnequipped, BodySlot.element, BodySlot.elementId, Element.Get(), SpriteSheet.Get(), Chara.GetFavArmorSkill(), Chara.GetFavWeaponSkill(), CharaBody.GetSortVal(), UIButton.icon, matItem, BodySlot.name, Element.Name, UITooltip.note, UIItem.refObj, Card.SetImage(), UIText.SetText(), UIButton.SetTooltip(), CharaBody.slots, textFavArmor, BodySlot.thing, and Thing.WriteNote().
Referenced by OnSwitchContent(), and RefreshProfile().
RefreshFeatMode()
void WindowChara.RefreshFeatMode () inline
Definition at line 250 of file WindowChara.cs.
    {
        buttonFeatMode.mainText.text = "featMode".lang(EClass.pc.feat.ToString() ?? "");
        ColorBlock colors = buttonFeatMode.colors;
        colors.normalColor = colors.normalColor.SetAlpha(featMode ? 1 : 0);
        buttonFeatMode.colors = colors;
    }
References buttonFeatMode, Card.feat, featMode, and EClass.pc.
RefreshInfo()
void WindowChara.RefreshInfo () inline
Definition at line 478 of file WindowChara.cs.
    {
        textBirthday.text = bio.TextBirthDate(chara);
        textMom.text = chara.bio.nameMom.ToTitleCase();
        textDad.text = chara.bio.nameDad.ToTitleCase();
        textBirthplace.text = chara.bio.nameBirthplace.ToTitleCase();
        textLike.text = EClass.sources.cards.map.TryGetValue(bio.idLike, EClass.sources.cards.map["ash"]).GetName();
        textHobby.text = EClass.sources.elements.map[bio.idHobby].GetText();
        textFaction.text = ((chara.faction == null) ? "???" : chara.faction.name.ToTitleCase());
        textFaith.text = chara.faith.Name.ToTitleCase();
    }
References Card.bio, bio, SourceManager.cards, chara, SourceManager.elements, Chara.faction, Chara.faith, Biography.idHobby, Biography.idLike, SourceCard.map, Faction.name, Religion.Name, Biography.nameBirthplace, Biography.nameDad, Biography.nameMom, EClass.sources, and Biography.TextBirthDate().
Referenced by OnSwitchContent().
RefreshNote()
static void WindowChara.RefreshNote (Chara chara, UINote n, bool shortMode = false) inline static
Definition at line 859 of file WindowChara.cs.
    {
        n.Clear();
        Biography biography = chara.bio;
        if (shortMode)
        {
            n.AddText(biography.TextBio(chara) + " " + biography.TextBio2(chara));
            n.Space();
        }
        else
        {
            UIItem uIItem = n.AddItem("ItemBackground");
            if (chara.IsPC)
            {
                uIItem.text1.SetText(EClass.player.GetBackgroundText());
                uIItem.button1.SetOnClick(delegate
                {
                    EClass.player.EditBackgroundText();
                });
            }
            else
            {
                uIItem.text1.SetText("???");
                uIItem.button1.SetActive(enable: false);
            }
            n.Space(16);
            n.AddTopic("TopicDomain", "profile".lang(), biography.TextBio(chara) + " " + biography.TextBio2(chara));
        }
        string text = "";
        ElementContainer elementContainer = (chara.IsPC ? EClass.player.GetDomains() : new ElementContainer().ImportElementMap(chara.job.domain));
        foreach (Element value in elementContainer.dict.Values)
        {
            text = text + ((value == elementContainer.dict.Values.First()) ? "" : ", ") + value.Name;
        }
        n.AddTopic("TopicDomain", "domain".lang(), text).button1.SetActive(enable: false);
        string text2 = chara.GetFavCat().GetName();
        string @ref = chara.GetFavFood().GetName();
        Add("favgift".lang(text2.ToLower().ToTitleCase(), @ref));
        Add(chara.GetTextHobby());
        Add(chara.GetTextWork());
        if (chara.IsPC)
        {
            n.AddTopic("TopicDomain", "totalFeat".lang(), EClass.player.totalFeat.ToString() ?? "");
        }
        text = chara.GetFavWeaponSkill()?.Name ?? Element.Get(100).GetText();
        text = text + " / " + ("style" + chara.GetFavAttackStyle()).lang();
        n.AddTopic("TopicDomain", "attackStyle".lang(), text);
        n.AddTopic("TopicDomain", "armorStyle".lang(), chara.GetFavArmorSkill()?.Name ?? Element.Get(120).GetText());
        if (chara.IsPC && EClass.pc.c_daysWithGod > 0)
        {
            AddText("info_daysWithGod".lang(EClass.pc.c_daysWithGod.ToString() ?? "", EClass.pc.faith.Name));
        }
        if (chara.ride != null)
        {
            AddText("info_ride".lang(chara.ride.NameBraced));
        }
        if (chara.parasite != null)
        {
            AddText("info_parasite".lang(chara.parasite.NameBraced));
        }
        if (EClass.player.IsCriminal)
        {
            AddText("info_criminal".lang());
        }
        if (!chara.IsPC)
        {
            int num = chara.GetAffinityExpBonus() - 100;
            if (num != 0)
            {
                AddText("affinity_exp_bonus".lang(chara.affinity.Name, ((num > 0) ? "+" : "") + num));
            }
            if (chara.c_daysWithPC > 0)
            {
                num = chara.GetDaysTogetherBonus() - 100;
                AddText("info_daysWithPC".lang(chara.c_daysWithPC.ToString() ?? "") + Environment.NewLine + "daystogether_bonus".lang(((num > 0) ? "+" : "") + num));
            }
        }
        if (EClass.debug.showExtra)
        {
            n.AddText("LV:" + chara.LV + "  exp:" + chara.exp + " next:" + chara.ExpToNext);
            n.AddText("Luck:" + chara.Evalue(78));
        }
        n.Build();
        void Add(string s)
        {
            string[] array = s.Split(':');
            n.AddTopic("TopicDomain", array[0], (array.Length >= 2) ? array[1].TrimStart(' ') : "").button1.SetActive(enable: false);
        }
        void AddText(string s)
        {
            n.AddText("  " + s);
        }
    }
References Add(), UINote.AddItem(), UINote.AddText(), UINote.AddTopic(), Chara.affinity, Card.bio, UIItem.button1, Card.c_daysWithGod, Card.c_daysWithPC, UINote.Clear(), EClass.debug, Player.EditBackgroundText(), Card.Evalue(), Card.exp, Card.ExpToNext, Chara.faith, Element.Get(), Card.GetAffinityExpBonus(), Player.GetBackgroundText(), Card.GetDaysTogetherBonus(), Player.GetDomains(), Chara.GetFavArmorSkill(), Chara.GetFavAttackStyle(), Chara.GetFavCat(), Chara.GetFavFood(), Chara.GetFavWeaponSkill(), Chara.GetTextHobby(), Chara.GetTextWork(), ElementContainer.ImportElementMap(), Player.IsCriminal, Chara.IsPC, Chara.job, Card.LV, Affinity.Name, Element.Name, Religion.Name, Chara.NameBraced, Chara.parasite, EClass.pc, EClass.player, Chara.ride, UIText.SetText(), CoreDebug.showExtra, UINote.Space(), UIItem.text1, Biography.TextBio(), Biography.TextBio2(), and Player.totalFeat.
RefreshProfile()
void WindowChara.RefreshProfile () inline
Definition at line 364 of file WindowChara.cs.
    {
        RefreshStatus();
        textName.text = chara.NameSimple;
        textAlias.text = chara.Aka;
        textTitle.text = (chara.IsPC ? EClass.player.title : "-");
        textCurrentZone.text = ((chara.currentZone == null) ? "???" : chara.currentZone.Name);
        textHomeZone.text = ((chara.homeZone == null) ? "???" : chara.homeZone.Name);
        textBio.text = chara.job.GetText().ToTitleCase();
        textBio2.text = bio.TextBio(chara);
        textBio3.text = bio.TextBio2(chara);
        textDV.text = "_DV".lang(chara.DV.ToString() ?? "", chara.PV.ToString() ?? "");
        textStyle.text = "_style".lang(Lang._weight(chara.body.GetWeight(armorOnly: true)) ?? "", chara.elements.GetOrCreateElement(chara.GetArmorSkill()).Name, ("style" + chara.body.GetAttackStyle()).lang());
        textKarma.text = (chara.IsPC ? (EClass.player.karma.ToString() ?? "") : "???");
        textSAN.text = chara.SAN.value.ToString() ?? "";
        textFame.text = (chara.IsPC ? (EClass.player.fame.ToFormat() ?? "") : "???");
        textMoney.text = Lang._currency(chara.GetCurrency(), showUnit: true);
        textDeposit.text = Lang._currency(chara.IsPC ? EClass.game.cards.container_deposit.GetCurrency() : chara.c_allowance, showUnit: true);
        string text = "deepestLv2".lang((chara.IsPCFaction ? EClass.player.stats.deepest : chara.LV).ToString() ?? "");
        if (chara.IsPCFaction && EClass.player.CountKeyItem("license_void") > 0)
        {
            text = text + " " + "deepestLv3".lang(EClass.player.stats.deepestVoid.ToString() ?? "");
        }
        textDeepest.text = text;
        textAssets.text = (chara.IsPC ? "tGameTime".lang(EClass.player.stats.days.ToFormat(), EClass.player.stats.turns.ToFormat()) : "???");
        textTerritory.text = (chara.IsPC ? (EClass.pc.faction.CountTerritories().ToString() ?? "") : "???");
        buttonLife.SetElement(chara.elements.GetOrCreateElement(60), chara.elements, ButtonElement.Mode.OnlyValue);
        buttonMana.SetElement(chara.elements.GetOrCreateElement(61), chara.elements, ButtonElement.Mode.OnlyValue);
        buttonVigor.SetElement(chara.elements.GetOrCreateElement(62), chara.elements, ButtonElement.Mode.OnlyValue);
        buttonSpeed.SetElement(chara.elements.GetOrCreateElement(79), chara.elements, ButtonElement.Mode.OnlyValue);
        RefreshEquipment(listEquipment);
    }
References Lang._currency(), Lang._weight(), Chara.Aka, bio, Chara.body, buttonLife, buttonMana, buttonSpeed, buttonVigor, Card.c_allowance, Game.cards, chara, CardManager.container_deposit, Player.CountKeyItem(), Faction.CountTerritories(), Chara.currentZone, Player.Stats.days, Player.Stats.deepest, Player.Stats.deepestVoid, Chara.DV, Card.elements, Chara.faction, Player.fame, EClass.game, Chara.GetArmorSkill(), CharaBody.GetAttackStyle(), Card.GetCurrency(), ElementContainer.GetOrCreateElement(), CharaBody.GetWeight(), Chara.homeZone, Chara.IsPC, Chara.IsPCFaction, Chara.job, Player.karma, listEquipment, Card.LV, Spatial.Name, Card.NameSimple, EClass.pc, EClass.player, Chara.PV, RefreshEquipment(), RefreshStatus(), Chara.SAN, ButtonElement.SetElement(), Player.stats, Biography.TextBio(), Biography.TextBio2(), Player.Stats.turns, and Stats.value.
Referenced by OnSwitchContent().
RefreshSkill()
void WindowChara.RefreshSkill (int idTab) inline
Definition at line 505 of file WindowChara.cs.
    {
        contentList.DestroyChildren();
        note.Clear();
        note.RebuildLayout();
        UIList list = default(UIList);
        if (idTab == 1)
        {
            List("skillsGeneral", "general");
            List("skillsCraft", "craft");
            List("skillsCombat", "combat");
            List("skillsWeapon", "weapon");
        }
        else if (idTab == 2)
        {
            RefreshFeatMode();
            if (featMode)
            {
                List("availableFeats", "general");
                List("availableFeats_special", "special");
                List("availableFeats_skill", "skill");
                List("availableFeats_attribute", "attribute");
                return;
            }
            Header("mutation", null);
            ListFeat();
            list.callbacks = new UIList.Callback<Feat, ButtonElement>
            {
                onClick = delegate(Feat a, ButtonElement b)
                {
                    WidgetTracker.Toggle(a);
                    b.SetElement(a, chara.elements, ButtonElement.Mode.Feat);
                },
                onInstantiate = delegate(Feat a, ButtonElement b)
                {
                    b.SetElement(a, chara.elements, ButtonElement.Mode.Feat);
                },
                onList = delegate
                {
                    foreach (Element item in chara.elements.ListElements((Element a) => a.source.category == "mutation" && a.Value != 0))
                    {
                        list.Add(item);
                    }
                }
            };
            list.List();
            if (list.items.Count == 0)
            {
                _header.SetActive(enable: false);
                list.SetActive(enable: false);
            }
            Header("etherDisease", null);
            ListFeat();
            list.callbacks = new UIList.Callback<Feat, ButtonElement>
            {
                onClick = delegate(Feat a, ButtonElement b)
                {
                    WidgetTracker.Toggle(a);
                    b.SetElement(a, chara.elements, ButtonElement.Mode.Feat);
                },
                onInstantiate = delegate(Feat a, ButtonElement b)
                {
                    b.SetElement(a, chara.elements, ButtonElement.Mode.Feat);
                },
                onList = delegate
                {
                    foreach (Element item2 in chara.elements.ListElements((Element a) => a.source.category == "ether" && a.Value != 0))
                    {
                        list.Add(item2);
                    }
                }
            };
            list.List();
            if (list.items.Count == 0)
            {
                _header.SetActive(enable: false);
                list.SetActive(enable: false);
            }
            Header("innateFeats", null);
            ListFeat();
            list.callbacks = new UIList.Callback<Feat, ButtonElement>
            {
                onClick = delegate(Feat a, ButtonElement b)
                {
                    WidgetTracker.Toggle(a);
                    b.SetElement(a, chara.elements, ButtonElement.Mode.Feat);
                },
                onInstantiate = delegate(Feat a, ButtonElement b)
                {
                    b.SetElement(a, chara.elements, ButtonElement.Mode.Feat);
                },
                onList = delegate
                {
                    foreach (Element item3 in chara.elements.ListElements((Element a) => a.source.category == "feat" && a.HasTag("innate") && a.Value != 0))
                    {
                        list.Add(item3);
                    }
                }
            };
            list.List();
            Header("feats", null);
            ListFeat();
            list.callbacks = new UIList.Callback<Feat, ButtonElement>
            {
                onClick = delegate(Feat a, ButtonElement b)
                {
                    WidgetTracker.Toggle(a);
                    b.SetElement(a, chara.elements, ButtonElement.Mode.Feat);
                },
                onInstantiate = delegate(Feat a, ButtonElement b)
                {
                    b.SetElement(a, chara.elements, ButtonElement.Mode.Feat);
                },
                onList = delegate
                {
                    foreach (Element item4 in chara.elements.ListElements((Element a) => a.source.category == "feat" && !a.HasTag("innate") && a.Value != 0))
                    {
                        list.Add(item4);
                    }
                },
                onSort = (Feat a, UIList.SortMode m) => a.GetSortVal(m)
            };
            list.ChangeSort(UIList.SortMode.ByID);
            list.List();
        }
        else if (idTab == 3)
        {
            Header("resistance", null);
            headerEquip.SetText("resistance".lang());
            ListResist();
            list.callbacks = new UIList.Callback<Element, ButtonElement>
            {
                onInstantiate = delegate(Element a, ButtonElement b)
                {
                    b.SetGrid(a, chara);
                },
                onList = delegate
                {
                    foreach (SourceElement.Row item5 in EClass.sources.elements.rows.Where((SourceElement.Row a) => a.category == "resist" && ((!a.tag.Contains("hidden") && !a.tag.Contains("high")) || chara.Evalue(a.id) != 0)))
                    {
                        list.Add(chara.elements.GetOrCreateElement(item5.id));
                    }
                }
            };
            list.List();
        }
        else if (idTab == 4)
        {
            chara.elements.GetOrCreateElement(78);
            List<Element> eles = chara.elements.ListElements(delegate(Element a)
            {
                if (a.source.tag.Contains("godAbility") || a.source.categorySub == "god")
                {
                    return false;
                }
                if (a.IsFlag)
                {
                    if (a.Value == 0)
                    {
                        return false;
                    }
                }
                else
                {
                    if (a.vSource != 0)
                    {
                        if (a.source.IsWeaponEnc)
{
                            return true;
                        }
                        int id = a.id;
                        if ((uint)(id - 55) <= 2u || id == 68 || id == 93)
{
                            return true;
                        }
                        if (a.source.category == "enchant")
{
                            return true;
                        }
                    }
                    if ((a.owner == chara.elements && a.vLink == 0 && !a.IsFactionElement(chara)) || a.source.category == "resist")
                    {
                        return false;
                    }
                }
                return true;
            });
            eles.Sort((Element a, Element b) => a.SortVal(charaSheet: true) - b.SortVal(charaSheet: true));
            string[] skillCats = new string[7] { "general", "labor", "mind", "stealth", "combat", "craft", "weapon" };
            Header("enchant", null);
            headerEquip.SetText("enchant".lang());
            ListResist();
            list.callbacks = new UIList.Callback<Element, ButtonElement>
            {
                onInstantiate = delegate(Element a, ButtonElement b)
                {
                    b.SetGrid(a, chara);
                },
                onList = delegate
                {
                    foreach (Element item6 in eles)
                    {
                        if (!skillCats.Contains(item6.source.categorySub))
{
                            list.Add(item6);
                        }
                    }
                }
            };
            list.List();
            Header("skill", null);
            ListResist();
            list.callbacks = new UIList.Callback<Element, ButtonElement>
            {
                onInstantiate = delegate(Element a, ButtonElement b)
                {
                    b.SetGrid(a, chara);
                },
                onList = delegate
                {
                    foreach (Element item7 in eles)
                    {
                        if (skillCats.Contains(item7.source.categorySub))
{
                            list.Add(item7);
                        }
                    }
                }
            };
            list.List();
        }
        else if (idTab == 5)
        {
            Header("note", null);
            note.transform.SetAsLastSibling();
            RefreshNote(chara, note);
        }
        void Header(string lang, string lang2)
        {
            _header = Util.Instantiate(moldHeader, contentList);
            _header.SetText(lang);
            if (lang2 != null)
            {
                Util.Instantiate(moldHeader2, contentList).SetText(lang2);
            }
        }
        void List(string lang, string idSubCat)
        {
            List<string> cats = new List<string>();
            cats.Add(idSubCat);
            if (idSubCat == "general")
            {
                cats.Add("labor");
                cats.Add("mind");
                cats.Add("stealth");
            }
            Header(lang, null);
            ListSkill();
            list.callbacks = new UIList.Callback<Element, ButtonElement>
            {
                onClick = delegate(Element a, ButtonElement b)
                {
                    WidgetTracker.Toggle(a);
                    b.SetElement(a, chara.elements);
                },
                onInstantiate = delegate(Element a, ButtonElement b)
                {
                    b.SetElement(a, chara.elements);
                },
                onList = delegate
                {
                    foreach (Element item8 in chara.elements.ListElements((Element a) => (a.Value != 0 || a.ValueWithoutLink != 0 || a.vSource > 0) && a.source.category == "skill" && cats.Contains(a.source.categorySub)))
                    {
                        list.Add(item8);
                    }
                },
                onSort = (Element c, UIList.SortMode m) => EClass.sources.elements.alias[c.source.aliasParent].id * -10000 - c.id
            };
            list.List(UIList.SortMode.ByElementParent);
        }
        void List(string lang, string idSubCat)
        {
            Header(lang, "cost");
            ListFeatPurchase();
            UIList _list = list;
            _list.callbacks = new UIList.Callback<Element, ButtonElement>
            {
                onClick = delegate(Element a, ButtonElement b)
                {
                    if (!a.IsPurchaseFeatReqMet(chara.elements) && !EClass.debug.enable)
                    {
                        SE.BeepSmall();
                    }
                    else if (EClass.pc.feat < a.CostLearn)
                    {
                        SE.BeepSmall();
                        Msg.Say("notEnoughFeatPoint");
                    }
                    else
                    {
                        Dialog.YesNo("dialogBuyFeat".lang(a.CostLearn.ToString() ?? "", a.FullName), delegate
{
                            EClass.pc.feat -= a.CostLearn;
                            EClass.pc.SetFeat(a.id, a.Value, msg: true);
                            RefreshSkill(idTab);
                            RefreshFeatMode();
                            RefreshStatic();
                            this.RebuildLayout(recursive: true);
                        });
                    }
                },
                onInstantiate = delegate(Element a, ButtonElement b)
                {
                    b.SetElement(a, chara.elements, ButtonElement.Mode.FeatPurchase);
                },
                onList = delegate
                {
                    foreach (Element item9 in chara.ListAvailabeFeats(pet: false, EClass.game.config.showAllFeat))
                    {
                        if (item9.source.categorySub == idSubCat)
{
                            _list.Add(item9);
                        }
                    }
                }
            };
            _list.List();
        }
        void ListFeat()
        {
            list = Util.Instantiate(moldListFeat, contentList);
        }
        void ListFeatPurchase()
        {
            list = Util.Instantiate(moldListFeatPurchase, contentList);
        }
        void ListResist()
        {
            list = Util.Instantiate(moldListResist, contentList);
        }
        void ListSkill()
        {
            list = Util.Instantiate(moldListSkill, contentList);
        }
    }
References UIList.Add(), UIList.ChangeSort(), UINote.Clear(), Card.elements, SourceManager.elements, Card.Evalue(), ElementContainer.GetOrCreateElement(), Element.GetSortVal(), Element.HasTag(), Header, Element.id, if(), Element.IsFactionElement(), Element.IsFlag, item, UIList.items, UIList.List(), ElementContainer.ListElements(), Element.owner, ButtonElement.SetElement(), ButtonElement.SetGrid(), UIHeader.SetText(), Element.source, EClass.sources, WidgetTracker.Toggle(), Element.Value, Element.vLink, and Element.vSource.
Referenced by OnSwitchContent(), and ToggleFeatMode().
RefreshStatic()
void WindowChara.RefreshStatic () inline
Definition at line 263 of file WindowChara.cs.
    {
        textHealth.text = chara.hp + "/" + chara.MaxHP;
        textMood.text = chara.mana.value + "/" + chara.mana.max;
        portrait.SetChara(chara);
        Sprite @object = Portrait.modPortraitBGs.GetItem(chara.GetStr(23) ?? "BG_1").GetObject();
        @object.texture.filterMode = FilterMode.Bilinear;
        portrait.image.sprite = @object;
        @object = Portrait.modPortraitBGFs.GetItem(chara.GetStr(24) ?? "BGF_1").GetObject();
        @object.texture.filterMode = FilterMode.Bilinear;
        portrait.imageFrame.sprite = @object;
        window.SetCaption(chara.NameBraced);
        listAttaribute.Clear();
        listAttaribute.callbacks = new UIList.Callback<Element, ButtonElement>
        {
            onClick = delegate(Element a, ButtonElement b)
            {
                WidgetTracker.Toggle(a);
                RefreshStatic();
            },
            onInstantiate = delegate(Element a, ButtonElement b)
            {
                b.SetElement(a, chara.elements, ButtonElement.Mode.Attribute);
            }
        };
        List<Element> list = chara.elements.ListElements((Element a) => a.HasTag("primary"));
        list.Sort((Element a, Element b) => a.source.sort - b.source.sort);
        foreach (Element item in list)
        {
            listAttaribute.Add(item);
        }
        listAttaribute.Refresh();
    }
References UIList.Add(), chara, UIList.Clear(), Card.elements, ModItemList< T >.GetItem(), BaseCard.GetStr(), Element.HasTag(), item, listAttaribute, ElementContainer.ListElements(), Chara.mana, Stats.max, Chara.MaxHP, Portrait.modPortraitBGFs, Portrait.modPortraitBGs, Chara.NameBraced, portrait, UIList.Refresh(), RefreshStatic(), Window.SetCaption(), Portrait.SetChara(), ButtonElement.SetElement(), Element.source, WidgetTracker.Toggle(), and WindowController.window.
Referenced by OnSwitchContent(), RefreshStatic(), SetPortraitBG(), and SetPortraitFrame().
RefreshStatus()
void WindowChara.RefreshStatus () inline
Definition at line 297 of file WindowChara.cs.
    {
        layoutStatus.DestroyChildren();
        foreach (Stats item in new List<Stats> { chara.hunger, chara.burden, chara.stamina, chara.depression, chara.bladder, chara.hygiene })
        {
            AddStatus(item);
        }
        foreach (Condition condition in chara.conditions)
        {
            AddStatus(condition);
        }
        if (layoutStatus.transform.childCount == 1)
        {
            AddStatus(null);
        }
        layoutStatus.RebuildLayout();
    }
References AddStatus(), Chara.bladder, Chara.burden, chara, Chara.conditions, Chara.depression, Chara.hunger, item, layoutStatus, and Chara.stamina.
Referenced by RefreshProfile().
SetChara()
void WindowChara.SetChara (Chara c) inline
Definition at line 164 of file WindowChara.cs.
    {
        Instance = this;
        chara = c;
        portrait.interactable = chara.IsPC;
        OnSwitchContent(window);
        if (window.setting.tabs.Count > 6)
        {
            window.setting.tabs[6].button.SetActive(chara.IsPC);
        }
        if (window.idTab == 6 && !chara.IsPC)
        {
            window.SwitchContent(0);
        }
    }
References chara, Window.idTab, Instance, Chara.IsPC, OnSwitchContent(), Window.setting, Window.SwitchContent(), Window.Setting.tabs, and WindowController.window.
Referenced by LayerChara.SetChara(), and LayerInteraction.ShowPage().
SetPortraitBG()
void WindowChara.SetPortraitBG (int a) inline
Definition at line 214 of file WindowChara.cs.
    {
        string currentId = chara.GetStr(23) ?? "BG_1";
        currentId = Portrait.modPortraitBGs.GetNextID(currentId, a);
        if (currentId == "BG_1")
        {
            currentId = null;
        }
        chara.SetStr(23, currentId);
        RefreshStatic();
    }
References chara, ModItemList< T >.GetNextID(), BaseCard.GetStr(), Portrait.modPortraitBGs, RefreshStatic(), and BaseCard.SetStr().
SetPortraitFrame()
void WindowChara.SetPortraitFrame (int a) inline
Definition at line 226 of file WindowChara.cs.
    {
        string currentId = chara.GetStr(24) ?? "BGF_1";
        currentId = Portrait.modPortraitBGFs.GetNextID(currentId, a);
        if (currentId == "BGF_1")
        {
            currentId = null;
        }
        chara.SetStr(24, currentId);
        RefreshStatic();
    }
References chara, ModItemList< T >.GetNextID(), BaseCard.GetStr(), Portrait.modPortraitBGFs, RefreshStatic(), and BaseCard.SetStr().
ToggleFeatMode()
void WindowChara.ToggleFeatMode () inline
Definition at line 238 of file WindowChara.cs.
    {
        featMode = !featMode;
        RefreshSkill(window.idTab);
        buttonFeatOption.SetActive(featMode);
        buttonFeatOption.SetToggle(EClass.game.config.showAllFeat, delegate(bool a)
        {
            EClass.game.config.showAllFeat = a;
            RefreshSkill(window.idTab);
        });
    }
References buttonFeatOption, Game.config, featMode, EClass.game, Window.idTab, RefreshSkill(), UIButton.SetToggle(), Game.Config.showAllFeat, and WindowController.window.
Referenced by WidgetExp.OnClick(), and WidgetExpHome.OnClick().
Update()
void WindowChara.Update () inline private
Definition at line 180 of file WindowChara.cs.
    {
        rectEquip.anchoredPosition = new Vector2(scrollSkill.content.anchoredPosition.x + equipPos.x, equipPos.y);
    }
References equipPos, and scrollSkill.
Member Data Documentation
_header
UIHeader WindowChara._header private
Definition at line 160 of file WindowChara.cs.
barColor1
float WindowChara.barColor1
Definition at line 156 of file WindowChara.cs.
Referenced by AddNeeds().
barColor2
float WindowChara.barColor2
Definition at line 158 of file WindowChara.cs.
Referenced by AddNeeds().
buttonFeatMode
UIButton WindowChara.buttonFeatMode
Definition at line 138 of file WindowChara.cs.
Referenced by OnSwitchContent(), and RefreshFeatMode().
buttonFeatOption
UIButton WindowChara.buttonFeatOption
Definition at line 140 of file WindowChara.cs.
Referenced by OnSwitchContent(), and ToggleFeatMode().
buttonLife
ButtonElement WindowChara.buttonLife
Definition at line 110 of file WindowChara.cs.
Referenced by RefreshProfile().
buttonMana
ButtonElement WindowChara.buttonMana
Definition at line 108 of file WindowChara.cs.
Referenced by RefreshProfile().
buttonSpeed
ButtonElement WindowChara.buttonSpeed
Definition at line 114 of file WindowChara.cs.
Referenced by RefreshProfile().
buttonVigor
ButtonElement WindowChara.buttonVigor
Definition at line 112 of file WindowChara.cs.
Referenced by RefreshProfile().
chara
Chara WindowChara.chara
Definition at line 12 of file WindowChara.cs.
Referenced by OnClickPortrait(), OnSwitchContent(), ButtonElement.Refresh(), RefreshEquipment(), RefreshInfo(), RefreshProfile(), RefreshStatic(), RefreshStatus(), SetChara(), SetPortraitBG(), and SetPortraitFrame().
colorUnequipped
Color WindowChara.colorUnequipped
Definition at line 150 of file WindowChara.cs.
Referenced by RefreshEquipment().
contentList
Transform WindowChara.contentList
Definition at line 134 of file WindowChara.cs.
equipPos
Vector2 WindowChara.equipPos
Definition at line 152 of file WindowChara.cs.
Referenced by Update().
featMode
bool WindowChara.featMode
Definition at line 154 of file WindowChara.cs.
Referenced by OnSwitchContent(), RefreshFeatMode(), and ToggleFeatMode().
graph
PUIExampleRPGStats WindowChara.graph
Definition at line 82 of file WindowChara.cs.
gridEquip
GridLayoutGroup WindowChara.gridEquip
Definition at line 104 of file WindowChara.cs.
headerEquip
UIHeader WindowChara.headerEquip
Definition at line 124 of file WindowChara.cs.
imageView
Image WindowChara.imageView
Definition at line 142 of file WindowChara.cs.
Instance
WindowChara WindowChara.Instance static
Definition at line 10 of file WindowChara.cs.
Referenced by ButtonElement.Refresh(), and SetChara().
layoutNeeds
LayoutGroup WindowChara.layoutNeeds
Definition at line 100 of file WindowChara.cs.
Referenced by AddNeeds().
layoutStatus
LayoutGroup WindowChara.layoutStatus
Definition at line 102 of file WindowChara.cs.
Referenced by AddStatus(), and RefreshStatus().
listAttaribute
UIList WindowChara.listAttaribute
Definition at line 74 of file WindowChara.cs.
Referenced by RefreshStatic().
listEquipment
UIList WindowChara.listEquipment
Definition at line 76 of file WindowChara.cs.
Referenced by RefreshProfile().
listEquipment2
UIList WindowChara.listEquipment2
Definition at line 78 of file WindowChara.cs.
Referenced by OnSwitchContent().
mask
Sprite WindowChara.mask
Definition at line 144 of file WindowChara.cs.
Referenced by OnSwitchContent().
maskResist
Sprite WindowChara.maskResist
Definition at line 146 of file WindowChara.cs.
Referenced by OnSwitchContent().
matItem
Material WindowChara.matItem
Definition at line 148 of file WindowChara.cs.
Referenced by RefreshEquipment().
moldHeader
UIHeader WindowChara.moldHeader
Definition at line 120 of file WindowChara.cs.
moldHeader2
UIHeader WindowChara.moldHeader2
Definition at line 122 of file WindowChara.cs.
moldListFeat
UIList WindowChara.moldListFeat
Definition at line 130 of file WindowChara.cs.
moldListFeatPurchase
UIList WindowChara.moldListFeatPurchase
Definition at line 132 of file WindowChara.cs.
moldListResist
UIList WindowChara.moldListResist
Definition at line 128 of file WindowChara.cs.
moldListSkill
UIList WindowChara.moldListSkill
Definition at line 126 of file WindowChara.cs.
moldNeeds
UIItem WindowChara.moldNeeds
Definition at line 118 of file WindowChara.cs.
Referenced by AddNeeds().
moldStats
UIItem WindowChara.moldStats
Definition at line 116 of file WindowChara.cs.
Referenced by AddStatus().
note
UINote WindowChara.note
Definition at line 80 of file WindowChara.cs.
portrait
Portrait WindowChara.portrait
Definition at line 14 of file WindowChara.cs.
Referenced by OnClickPortrait(), and RefreshStatic().
rectEquip
RectTransform WindowChara.rectEquip
Definition at line 136 of file WindowChara.cs.
scrollSkill
UIScrollView WindowChara.scrollSkill
Definition at line 106 of file WindowChara.cs.
Referenced by Update().
textAffection
UIText WindowChara.textAffection
Definition at line 88 of file WindowChara.cs.
textAlias
UIText WindowChara.textAlias
Definition at line 22 of file WindowChara.cs.
textAssets
UIText WindowChara.textAssets
Definition at line 64 of file WindowChara.cs.
textBio
UIText WindowChara.textBio
Definition at line 26 of file WindowChara.cs.
textBio2
UIText WindowChara.textBio2
Definition at line 28 of file WindowChara.cs.
textBio3
UIText WindowChara.textBio3
Definition at line 30 of file WindowChara.cs.
textBirthday
UIText WindowChara.textBirthday
Definition at line 32 of file WindowChara.cs.
textBirthplace
UIText WindowChara.textBirthplace
Definition at line 44 of file WindowChara.cs.
textCurrentZone
UIText WindowChara.textCurrentZone
Definition at line 70 of file WindowChara.cs.
textDad
UIText WindowChara.textDad
Definition at line 42 of file WindowChara.cs.
textDeepest
UIText WindowChara.textDeepest
Definition at line 68 of file WindowChara.cs.
textDeposit
UIText WindowChara.textDeposit
Definition at line 66 of file WindowChara.cs.
textDominance
UIText WindowChara.textDominance
Definition at line 90 of file WindowChara.cs.
textDV
UIText WindowChara.textDV
Definition at line 96 of file WindowChara.cs.
textExtroversion
UIText WindowChara.textExtroversion
Definition at line 92 of file WindowChara.cs.
textFaction
UIText WindowChara.textFaction
Definition at line 34 of file WindowChara.cs.
textFaith
UIText WindowChara.textFaith
Definition at line 36 of file WindowChara.cs.
textFame
UIText WindowChara.textFame
Definition at line 54 of file WindowChara.cs.
textFavArmor
UIText WindowChara.textFavArmor
Definition at line 94 of file WindowChara.cs.
Referenced by RefreshEquipment().
textHealth
UIText WindowChara.textHealth
Definition at line 18 of file WindowChara.cs.
textHobby
UIText WindowChara.textHobby
Definition at line 48 of file WindowChara.cs.
textHome
UIText WindowChara.textHome
Definition at line 38 of file WindowChara.cs.
textHomeZone
UIText WindowChara.textHomeZone
Definition at line 72 of file WindowChara.cs.
textIncome
UIText WindowChara.textIncome
Definition at line 62 of file WindowChara.cs.
textKarma
UIText WindowChara.textKarma
Definition at line 50 of file WindowChara.cs.
textLaw
UIText WindowChara.textLaw
Definition at line 86 of file WindowChara.cs.
textLike
UIText WindowChara.textLike
Definition at line 46 of file WindowChara.cs.
textMom
UIText WindowChara.textMom
Definition at line 40 of file WindowChara.cs.
textMoney
UIText WindowChara.textMoney
Definition at line 56 of file WindowChara.cs.
textMood
UIText WindowChara.textMood
Definition at line 16 of file WindowChara.cs.
textName
UIText WindowChara.textName
Definition at line 20 of file WindowChara.cs.
textSAN
UIText WindowChara.textSAN
Definition at line 52 of file WindowChara.cs.
textStability
UIText WindowChara.textStability
Definition at line 84 of file WindowChara.cs.
textStyle
UIText WindowChara.textStyle
Definition at line 98 of file WindowChara.cs.
textTax
UIText WindowChara.textTax
Definition at line 58 of file WindowChara.cs.
textTerritory
UIText WindowChara.textTerritory
Definition at line 60 of file WindowChara.cs.
textTitle
UIText WindowChara.textTitle
Definition at line 24 of file WindowChara.cs.
Property Documentation
bio
Biography WindowChara.bio get
Definition at line 162 of file WindowChara.cs.
Referenced by RefreshInfo(), and RefreshProfile().
The documentation for this class was generated from the following file:
Elin/WindowChara.cs