Elin Decompiled Documentation: UIButton Class Reference
UIButton Class Reference
Classes
class Item
Public Member Functions
virtual bool CanMiddleClick ()
virtual void OnMiddleClick (bool forceClick)
void SetItem (Item i)
virtual void RefreshItem ()
virtual void OnHover ()
void Toggle ()
void ToggleCheck ()
void SetCheck (bool check)
void SetToggle (bool isOn, Action< bool > onToggle=null)
void SetToggleWithScore (bool isOn, Action< bool > onToggle, int? score)
void SetTooltip (Action< UITooltip > onShowTooltip=null, bool enable=true)
void SetTooltip (string id, Action< UITooltip > onShowTooltip=null, bool enable=true)
void SetTooltipLang (string lang=null)
virtual void ShowTooltip ()
void ShowTooltipForced (bool ignoreWhenRightClick=true)
override void OnPointerDown (PointerEventData eventData)
override void OnPointerClick (PointerEventData eventData)
override void OnPointerUp (PointerEventData eventData)
void OnPointerUpOnDrag (PointerEventData eventData)
void _OnPress ()
void OnPress ()
void AddHighlight (Func< bool > killCondition)
void DoHighlightTransition (bool instant=false)
void DoNormalTransition (bool instant=true)
override Selectable FindSelectableOnDown ()
override Selectable FindSelectableOnUp ()
override Selectable FindSelectableOnLeft ()
override Selectable FindSelectableOnRight ()
void SetNavigation (UIButton up, UIButton down=null, UIButton left=null, UIButton right=null)
override bool IsActive ()
void SetInteractableWithAlpha (bool enable)
virtual void ApplySkin ()
void ApplySkin ()
Static Public Member Functions
static void UpdateButtons ()
static void TryHihlight ()
static void TryShowTip (Transform root=null, bool highlight=true, bool ignoreWhenRightClick=true)
static void TryShowTip< T > (Transform root=null, bool highlight=true, bool ignoreWhenRightClick=true)
Public Attributes
UIText mainText
UIText subText
UIText subText2
UIText keyText
Image icon
Image imageCheck
Graphic[] targetGraphics
float scaleIcon = 1f
float slideX
float navigationFix
bool isChecked
bool instantClick = true
UISelectableGroup group
TooltipData tooltip
SoundData soundClick
SoundData soundHighlight
Transform animeTarget
Anime animeClick
Anime animeHold
ButtonType buttonType
BaseSkinRoot skinRoot
Action onDoubleClick
Action onRightClick
Action< int > onInputWheel
object refObj
int refInt
string refStr
bool animating
bool selected
Vector3 originalIconScale = Vector3.one
UIButton highlightTarget
Item item
Static Public Attributes
static bool DoSlide
static bool locked
static UIButton lastButton
static UIButton lastHovered
static UIButton currentHighlight
static UIButton currentPressedButton
static float lastClicked
static float doubleClickTime = 0.4f
static Vector2 buttonPos
static Action onPressed
static List< UIButton > buttons = new List<UIButton>()
static Action actionTooltip
Protected Member Functions
override void Awake ()
override void OnEnable ()
override void DoStateTransition (SelectionState state, bool instant)
Properties
List< Graphic > Graphics [get]
virtual bool CanDragLeftButton [get]
Private Member Functions
void ColorTween (Color targetColor, bool instant)
Private Attributes
List< Graphic > m_graphics
Tween tween
SelectionState lastState
Static Private Attributes
static bool waiting
Detailed Description
Definition at line 9 of file UIButton.cs.
Member Function Documentation
_OnPress()
void UIButton._OnPress () inline
Definition at line 493 of file UIButton.cs.
    {
        if (!locked && IsActive() && IsInteractable())
        {
            if ((bool)soundClick)
            {
                SoundManager.current.Play(soundClick);
            }
            float realtimeSinceStartup = Time.realtimeSinceStartup;
            if (lastButton == this && onDoubleClick != null && realtimeSinceStartup - lastClicked < doubleClickTime)
            {
                onDoubleClick();
                lastButton = null;
            }
            else
            {
                lastClicked = realtimeSinceStartup;
                lastButton = this;
                base.onClick.Invoke();
            }
        }
    }
Referenced by OnPointerDown().
AddHighlight()
void UIButton.AddHighlight (Func< bool > killCondition) inline
Definition at line 521 of file UIButton.cs.
    {
        base.gameObject.AddComponent<UIButtonHighlighter>().Set(killCondition);
    }
ApplySkin()
virtual void UIButton.ApplySkin () inline virtual
Implements IUISkin.
Definition at line 743 of file UIButton.cs.
    {
        if ((bool)skinRoot)
        {
            SkinAsset_Button button = skinRoot.GetButton();
            base.transition = button.transition;
            SpriteState spriteState = base.spriteState;
            spriteState.highlightedSprite = button.spriteHighlight;
            if (base.transition == Transition.ColorTint)
            {
                base.image.color = Color.white;
                ColorBlock colorBlock = base.colors;
                colorBlock.normalColor = button.color;
                colorBlock.highlightedColor = button.colorHighlight;
                base.colors = colorBlock;
            }
            else
            {
                base.image.color = button.color;
            }
            base.spriteState = spriteState;
            base.image.sprite = button.spriteNormal;
        }
    }
References Color, SkinAsset_Button.color, SkinAsset_Button.colorHighlight, SkinAsset_Button.spriteHighlight, SkinAsset_Button.spriteNormal, and SkinAsset_Button.transition.
Referenced by Awake().
Awake()
override void UIButton.Awake () inline protected
Definition at line 221 of file UIButton.cs.
    {
        if ((bool)icon)
        {
            originalIconScale = icon.transform.localScale;
        }
        if (Application.isPlaying)
        {
            ApplySkin();
        }
        base.Awake();
    }
References ApplySkin(), icon, and originalIconScale.
CanMiddleClick()
virtual bool UIButton.CanMiddleClick () inline virtual
Reimplemented in ButtonAbility, and ButtonGrid.
Definition at line 212 of file UIButton.cs.
    {
        return false;
    }
Referenced by ActionMode.UpdateInput().
ColorTween()
void UIButton.ColorTween (Color targetColor, bool instant) inline private
Definition at line 637 of file UIButton.cs.
    {
        if (!(base.targetGraphic == null))
        {
            for (int i = 0; i < Graphics.Count; i++)
            {
                Graphics[i].CrossFadeColor(targetColor, (!instant) ? base.colors.fadeDuration : 0f, ignoreTimeScale: true, useAlpha: true);
            }
        }
    }
DoHighlightTransition()
void UIButton.DoHighlightTransition (bool instant = false) inline
Definition at line 526 of file UIButton.cs.
    {
        DoStateTransition(SelectionState.Highlighted, instant);
    }
Referenced by LayerList.LateUpdate(), UIContextMenu.LateUpdate(), OnEnable(), LayerList.OnInit(), UIList.Refresh(), UIDynamicList.RefreshHighlight(), UIList.Select(), LayerList.SetHighlightTarget(), TryHihlight(), LayerList.Update(), UIContextMenu.Update(), and UIDynamicList.UpdateRow().
DoNormalTransition()
void UIButton.DoNormalTransition (bool instant = true) inline
Definition at line 531 of file UIButton.cs.
    {
        DoStateTransition(SelectionState.Normal, instant);
    }
Referenced by UIContextMenu.Hide(), UIDynamicList.RefreshHighlight(), UISelectableGroup.SetButton(), WidgetHotbar.SetVisible(), and UIDynamicList.UpdateRow().
DoStateTransition()
override void UIButton.DoStateTransition (SelectionState state, bool instant) inline protected
Definition at line 536 of file UIButton.cs.
    {
        if ((waiting && state == SelectionState.Highlighted) || !Application.isPlaying)
        {
            return;
        }
        if (!base.interactable)
        {
            state = SelectionState.Disabled;
        }
        if ((bool)highlightTarget)
        {
            highlightTarget.DoStateTransition(state, instant: false);
        }
        if (selected && !imageCheck)
        {
            if (state == SelectionState.Highlighted)
            {
                ShowTooltip();
            }
            state = SelectionState.Selected;
        }
        switch (state)
        {
        case SelectionState.Normal:
            if (scaleIcon != 1f)
            {
                icon.transform.localScale = originalIconScale;
            }
            break;
        case SelectionState.Highlighted:
            currentHighlight = this;
            if (lastState != SelectionState.Pressed)
            {
                ShowTooltip();
            }
            if (scaleIcon != 1f && base.interactable)
            {
                icon.transform.localScale = new Vector3(scaleIcon, scaleIcon, 1f);
            }
            if (lastState != SelectionState.Pressed && (bool)soundHighlight)
            {
                SoundManager.current.Play(soundHighlight);
            }
            break;
        case SelectionState.Pressed:
            if (base.transition == Transition.SpriteSwap && base.spriteState.pressedSprite == null)
            {
                SpriteState spriteState = base.spriteState;
                spriteState.pressedSprite = spriteState.highlightedSprite;
                base.spriteState = spriteState;
            }
            if (scaleIcon != 1f)
            {
                icon.transform.localScale = new Vector3(scaleIcon, scaleIcon, 1f) * 0.9f;
                buttons.Add(this);
            }
            if ((bool)animeHold)
            {
                if (tween == null)
                {
                    tween = animeHold.Play(animeTarget ? animeTarget : base.transform).SetAutoKill(autoKillOnCompletion: false);
                }
                else
                {
                    tween.Restart();
                }
                animating = true;
                buttons.Add(this);
            }
            break;
        default:
            if (scaleIcon != 1f)
            {
                icon.transform.localScale = originalIconScale;
            }
            if ((bool)animeHold && tween != null && !Input.GetMouseButton(0))
            {
                tween.PlayBackwards();
                animating = false;
            }
            break;
        case SelectionState.Disabled:
            break;
        }
        lastState = state;
        if (base.transition != Transition.ColorTint)
        {
            base.DoStateTransition(state, instant);
            return;
        }
        ColorTween(state switch
        {
            SelectionState.Normal => base.colors.normalColor,
            SelectionState.Highlighted => base.colors.highlightedColor,
            SelectionState.Pressed => base.colors.pressedColor,
            SelectionState.Disabled => base.colors.disabledColor,
            _ => Color.white,
        } * base.colors.colorMultiplier, instant);
    }
References Color.
FindSelectableOnDown()
override Selectable UIButton.FindSelectableOnDown () inline
Definition at line 648 of file UIButton.cs.
    {
        if (base.navigation.selectOnDown != null)
        {
            return base.FindSelectableOnDown();
        }
        return FindSelectable(Quaternion.Euler(0f, 0f, navigationFix) * Vector3.down);
    }
FindSelectableOnLeft()
override Selectable UIButton.FindSelectableOnLeft () inline
Definition at line 666 of file UIButton.cs.
    {
        if (base.navigation.selectOnLeft != null)
        {
            return base.FindSelectableOnLeft();
        }
        return FindSelectable(Quaternion.Euler(0f, 0f, navigationFix) * Vector3.left);
    }
FindSelectableOnRight()
override Selectable UIButton.FindSelectableOnRight () inline
Definition at line 675 of file UIButton.cs.
    {
        if (base.navigation.selectOnRight != null)
        {
            return base.FindSelectableOnRight();
        }
        return FindSelectable(Quaternion.Euler(0f, 0f, navigationFix) * Vector3.right);
    }
FindSelectableOnUp()
override Selectable UIButton.FindSelectableOnUp () inline
Definition at line 657 of file UIButton.cs.
    {
        if (base.navigation.selectOnUp != null)
        {
            return base.FindSelectableOnUp();
        }
        return FindSelectable(Quaternion.Euler(0f, 0f, navigationFix) * Vector3.up);
    }
IsActive()
override bool UIButton.IsActive () inline
Definition at line 695 of file UIButton.cs.
    {
        if (IsDestroyed())
        {
            return false;
        }
        return base.IsActive();
    }
OnEnable()
override void UIButton.OnEnable () inline protected
Definition at line 234 of file UIButton.cs.
    {
        selected = false;
        base.OnEnable();
        if (!EventSystem.current)
        {
            return;
        }
        if ((bool)imageCheck)
        {
            imageCheck.gameObject.SetActive(isChecked);
        }
        if (EventSystem.current.currentSelectedGameObject == base.gameObject)
        {
            if (base.transition == Transition.SpriteSwap && base.spriteState.highlightedSprite != base.image.sprite)
            {
                DoHighlightTransition();
            }
            if ((bool)icon)
            {
                icon.transform.localScale = new Vector3(scaleIcon, scaleIcon, 1f);
            }
        }
    }
References DoHighlightTransition(), icon, imageCheck, isChecked, scaleIcon, and selected.
OnHover()
virtual void UIButton.OnHover () inline virtual
Reimplemented in ButtonHotItem.
Definition at line 312 of file UIButton.cs.
    {
        if ((!(UIContextMenu.timeSinceClosed < 0.1f) || !(lastHovered == this)) && item != null && !Input.GetMouseButton(0) && !Input.GetMouseButton(1))
        {
            buttonPos = base.transform.position;
            item.OnHover(this);
            lastHovered = this;
        }
    }
References buttonPos, item, lastHovered, UIButton.Item.OnHover(), and UIContextMenu.timeSinceClosed.
OnMiddleClick()
virtual void UIButton.OnMiddleClick (bool forceClick) inline virtual
Reimplemented in ButtonAbility, and ButtonGrid.
Definition at line 217 of file UIButton.cs.
    {
    }
Referenced by ActionMode.UpdateInput().
OnPointerClick()
override void UIButton.OnPointerClick (PointerEventData eventData) inline
Definition at line 446 of file UIButton.cs.
    {
        currentPressedButton = null;
        onPressed = null;
        if (eventData.dragging || instantClick)
        {
            return;
        }
        waiting = true;
        BaseCore.Instance.WaitForEndOfFrame(delegate
        {
            BaseCore.Instance.WaitForEndOfFrame(delegate
            {
                waiting = false;
            });
            if (EInput.skipFrame <= 0)
            {
                if (eventData.button != 0)
                {
                    if (eventData.button == PointerEventData.InputButton.Right && onRightClick != null && !EInput.rightMouse.wasConsumed)
                    {
                        onRightClick();
                    }
                }
                else
                {
                    _OnPress();
                }
            }
        });
    }
References currentPressedButton, BaseCore.Instance, instantClick, onPressed, EInput.skipFrame, BaseCore.WaitForEndOfFrame(), and waiting.
OnPointerDown()
override void UIButton.OnPointerDown (PointerEventData eventData) inline
Definition at line 395 of file UIButton.cs.
    {
        currentPressedButton = this;
        if (!instantClick)
        {
            base.OnPointerDown(eventData);
        }
        else
        {
            if (EInput.IsConsumed)
            {
                return;
            }
            if (eventData.button != 0)
            {
                if (eventData.button == PointerEventData.InputButton.Right && onRightClick != null && !EInput.rightMouse.wasConsumed)
                {
                    BaseCore.Instance.WaitForEndOfFrame(delegate
                    {
                        onRightClick();
                    });
                }
                return;
            }
            waiting = true;
            BaseCore.Instance.WaitForEndOfFrame(delegate
            {
                BaseCore.Instance.WaitForEndOfFrame(delegate
                {
                    waiting = false;
                });
                if (EInput.skipFrame <= 0)
                {
                    if ((bool)animeClick)
                    {
                        EventSystem.current.enabled = false;
                        animeClick.Play(animeTarget ? animeTarget : base.transform).OnComplete(delegate
{
                            OnPress();
                            EventSystem.current.enabled = true;
                        });
                    }
                    else
                    {
                        _OnPress();
                    }
                }
            });
        }
    }
References _OnPress(), animeClick, animeTarget, currentPressedButton, BaseCore.Instance, instantClick, EInput.IsConsumed, OnPointerDown(), OnPress(), onRightClick, Anime.Play(), EInput.rightMouse, EInput.skipFrame, BaseCore.WaitForEndOfFrame(), waiting, and ButtonState.wasConsumed.
Referenced by OnPointerDown().
OnPointerUp()
override void UIButton.OnPointerUp (PointerEventData eventData) inline
Definition at line 478 of file UIButton.cs.
    {
        currentPressedButton = null;
        onPressed = null;
        if (!instantClick)
        {
            base.OnPointerUp(eventData);
        }
    }
OnPointerUpOnDrag()
void UIButton.OnPointerUpOnDrag (PointerEventData eventData) inline
Definition at line 488 of file UIButton.cs.
    {
        base.OnPointerUp(eventData);
    }
Referenced by ButtonAbility.OnDrag(), and ButtonGridDrag.OnDrag().
OnPress()
void UIButton.OnPress () inline
Definition at line 516 of file UIButton.cs.
    {
        Invoke("_OnPress", 0.01f);
    }
Referenced by OnPointerDown().
RefreshItem()
virtual void UIButton.RefreshItem () inline virtual
Reimplemented in ButtonHotItem.
Definition at line 269 of file UIButton.cs.
    {
        bool flag = item != null;
        base.onClick.RemoveAllListeners();
        icon.enabled = flag;
        base.interactable = flag;
        if (flag && item.Hidden)
        {
            icon.enabled = false;
            base.interactable = false;
        }
        base.transition = item?.Transition ?? Transition.SpriteSwap;
        if (flag)
        {
            icon.sprite = item.GetSprite();
            base.onClick.AddListener(delegate
            {
                buttonPos = base.transform.position;
                item.OnClick(this);
                EInput.Consume(0);
            });
            icon.transform.localScale = item.SpriteScale;
            if (item.AdjustImageSize)
            {
                icon.SetNativeSize();
            }
            else
            {
                icon.Rect().sizeDelta = new Vector2(48f, 48f);
            }
            tooltip.enable = !item.TextTip.IsEmpty();
            tooltip.onShowTooltip = delegate(UITooltip t)
            {
                string textTip = item.TextTip;
                t.textMain.text = textTip;
            };
            if ((bool)subText)
            {
                item.SetSubText(subText);
            }
        }
    }
References UIButton.Item.AdjustImageSize, buttonPos, EInput.Consume(), UIButton.Item.GetSprite(), UIButton.Item.Hidden, icon, item, UIButton.Item.OnClick(), UIButton.Item.SetSubText(), UIButton.Item.SpriteScale, subText, UIButton.Item.TextTip, and UIButton.Item.Transition.
Referenced by SetItem().
SetCheck()
void UIButton.SetCheck (bool check) inline
Definition at line 332 of file UIButton.cs.
    {
        isChecked = check;
        if ((bool)imageCheck)
        {
            imageCheck.gameObject.SetActive(isChecked);
        }
    }
References imageCheck, and isChecked.
Referenced by AM_Copy.OnSetSubMenuButton(), AM_Deconstruct.OnSetSubMenuButton(), UISelectableGroup.Select(), SetToggle(), LayerResource.ShowThings(), and ToggleCheck().
SetInteractableWithAlpha()
void UIButton.SetInteractableWithAlpha (bool enable) inline
Definition at line 732 of file UIButton.cs.
    {
        CanvasGroup canvasGroup = base.gameObject.GetComponent<CanvasGroup>();
        if (!canvasGroup)
        {
            canvasGroup = base.gameObject.AddComponent<CanvasGroup>();
        }
        canvasGroup.alpha = (enable ? 1f : 0.5f);
        base.interactable = enable;
    }
Referenced by LayerUploader.Update().
SetItem()
void UIButton.SetItem (Item i) inline
Definition at line 259 of file UIButton.cs.
    {
        item = i;
        RefreshItem();
        if (item != null)
        {
            item.OnSetItem(this);
        }
    }
References item, UIButton.Item.OnSetItem(), and RefreshItem().
Referenced by WidgetMinimap.OnActivate().
SetNavigation()
void UIButton.SetNavigation (UIButton up, UIButton down = null, UIButton left = null, UIButton right = null) inline
Definition at line 684 of file UIButton.cs.
    {
        Navigation navigation = base.navigation;
        navigation.mode = Navigation.Mode.Explicit;
        navigation.selectOnUp = up;
        navigation.selectOnDown = down;
        navigation.selectOnLeft = left;
        navigation.selectOnRight = right;
        base.navigation = navigation;
    }
References down, left, right, and up.
SetToggle()
void UIButton.SetToggle (bool isOn, Action< bool > onToggle = null) inline
Definition at line 341 of file UIButton.cs.
    {
        SetCheck(isOn);
        base.onClick.RemoveAllListeners();
        base.onClick.AddListener(delegate
        {
            SetCheck(!isChecked);
            if (onToggle != null)
            {
                onToggle(isChecked);
            }
        });
    }
References isChecked, and SetCheck().
Referenced by UINote.AddToggle(), ActionHint.AddToggle(), LayerMod.OnInit(), LayerUploader.OnInit(), LayerWorldSetting.OnInit(), ContentConfigGame.OnInstantiate(), ContentConfigInput.OnInstantiate(), ContentConfigOther.OnInstantiate(), ContentConfigTest.OnInstantiate(), ContentCodex.OnSwitchContent(), ContentTactics.Refresh(), LayerWorldSetting.Refresh(), PartialMapMenu.RefreshOptions(), LayerCraft.RefreshRecipe(), LayerEditHouse.SetBoard(), UICharaMaker.SetChara(), SetToggleWithScore(), and WindowChara.ToggleFeatMode().
SetToggleWithScore()
void UIButton.SetToggleWithScore (bool isOn, Action< bool > onToggle, int? score) inline
Definition at line 355 of file UIButton.cs.
    {
        SetToggle(isOn, onToggle);
        subText.SetActive(enable: false);
    }
References SetToggle(), and subText.
SetTooltip() [1/2]
void UIButton.SetTooltip (Action< UITooltip > onShowTooltip = null, bool enable = true) inline
Definition at line 361 of file UIButton.cs.
    {
        SetTooltip("note", onShowTooltip, enable);
    }
References SetTooltip().
Referenced by WindowChara.AddStatus(), UICharaMaker.ListJob(), UICharaMaker.ListRace(), BuildMenu.OnActivate(), ListPeopleBed.OnInstantiate(), ButtonElement.Refresh(), ItemCulture.Refresh(), WindowCharaMini.Refresh(), WindowCharaMini.RefreshEquipment(), WindowChara.RefreshEquipment(), ContentHomeReport.RefreshInfo(), UIHomeInfo.RefreshInfo(), UIHomeInfo.RefreshReport(), ButtonAbility.SetAct(), GridItemCard.SetButton(), GridItemCardSource.SetButton(), GridItemRecipe.SetButton(), ButtonElement.SetGrid(), and SetTooltip().
SetTooltip() [2/2]
void UIButton.SetTooltip (string id, Action< UITooltip > onShowTooltip = null, bool enable = true) inline
Definition at line 366 of file UIButton.cs.
    {
        tooltip.id = id;
        tooltip.enable = enable;
        tooltip.onShowTooltip = onShowTooltip;
    }
SetTooltipLang()
void UIButton.SetTooltipLang (string lang = null) inline
Definition at line 373 of file UIButton.cs.
    {
        tooltip.enable = true;
        tooltip.lang = lang;
    }
Referenced by LayerWorldSetting.Refresh(), UIInventory.RefreshMenu(), and LayerDragGrid.SetInv().
ShowTooltip()
virtual void UIButton.ShowTooltip () inline virtual
Definition at line 379 of file UIButton.cs.
    {
        if (tooltip.enable && !Input.GetMouseButton(0) && !waiting && !Input.GetMouseButton(1) && (!EInput.isShiftDown || !Input.GetMouseButton(0)))
        {
            TooltipManager.Instance.ShowTooltip(tooltip, base.transform);
        }
    }
References TooltipData.enable, TooltipManager.Instance, EInput.isShiftDown, TooltipManager.ShowTooltip(), tooltip, and waiting.
Referenced by DropdownGrid.TrySelect().
ShowTooltipForced()
void UIButton.ShowTooltipForced (bool ignoreWhenRightClick = true) inline
Definition at line 387 of file UIButton.cs.
    {
        if (tooltip.enable && (!ignoreWhenRightClick || !Input.GetMouseButton(1)) && (!EInput.isShiftDown || !Input.GetMouseButton(0)))
        {
            TooltipManager.Instance.ShowTooltip(tooltip, base.transform);
        }
    }
References TooltipData.enable, TooltipManager.Instance, EInput.isShiftDown, TooltipManager.ShowTooltip(), and tooltip.
Referenced by UICharaMaker.ListJob(), and UICharaMaker.ListRace().
Toggle()
void UIButton.Toggle () inline
Definition at line 322 of file UIButton.cs.
    {
        group.Select(this, !isChecked);
    }
References group, isChecked, and UISelectableGroup.Select().
Referenced by UISelectableGroup.SetGroup().
ToggleCheck()
void UIButton.ToggleCheck () inline
Definition at line 327 of file UIButton.cs.
    {
        SetCheck(!isChecked);
    }
References isChecked, and SetCheck().
TryHihlight()
static void UIButton.TryHihlight () inline static
Definition at line 768 of file UIButton.cs.
    {
        InputModuleEX.UpdateEventData();
        UIButton componentOf = InputModuleEX.GetComponentOf<UIButton>();
        if ((bool)componentOf)
        {
            componentOf.DoHighlightTransition();
        }
    }
References DoHighlightTransition(), and InputModuleEX.UpdateEventData().
Referenced by UI.FreezeScreen(), UIDynamicList.List(), and DramaActor.Talk().
TryShowTip()
static void UIButton.TryShowTip (Transform root = null, bool highlight = true, bool ignoreWhenRightClick = true) inline static
Definition at line 778 of file UIButton.cs.
    {
        TryShowTip<UIButton>(root, highlight, ignoreWhenRightClick);
    }
Referenced by InvOwnerIdentify._OnProcess(), UIInventory.CheckDirty(), Layer.Delay(), UI.EndDrag(), UIContextMenu.Hide(), UIDynamicList.List(), UICharaMaker.ListJob(), UICharaMaker.ListRace(), LayerInfo.OnKill(), InvOwnerDraglet.OnProcess(), UIInventory.RefreshGrid(), ButtonGrid.SetCardGrid(), LayerList.SetList2< TValue >(), LayerList.SetListCheck< TValue >(), UIInventory.Update(), and CoreDebug.UpdateAlways().
TryShowTip< T >()
static void UIButton.TryShowTip< T > (Transform root = null, bool highlight = true, bool ignoreWhenRightClick = true) inline static
Type Constraints
T : UIButton
Definition at line 783 of file UIButton.cs.
                                                                                                                             : UIButton
    {
        actionTooltip = delegate
        {
            InputModuleEX.UpdateEventData();
            T componentOf = InputModuleEX.GetComponentOf<T>();
            if ((bool)componentOf && componentOf.tooltip.enable)
            {
                TooltipManager.Instance.HideTooltips();
                if ((bool)componentOf && (root == null || componentOf.transform.IsChildOf(root)))
                {
                    if (highlight)
                    {
                        componentOf.DoHighlightTransition();
                    }
                    try
                    {
                        componentOf.ShowTooltipForced(ignoreWhenRightClick);
                    }
                    catch
                    {
                    }
                }
            }
        };
    }
References TooltipManager.HideTooltips(), TooltipManager.Instance, and InputModuleEX.UpdateEventData().
UpdateButtons()
static void UIButton.UpdateButtons () inline static
Definition at line 704 of file UIButton.cs.
    {
        if ((bool)currentPressedButton && onPressed != null)
        {
            onPressed();
        }
        if (Input.GetMouseButton(0) || buttons.Count == 0)
        {
            return;
        }
        foreach (UIButton button in buttons)
        {
            if ((bool)button && (bool)button.gameObject)
            {
                if (button.animating)
                {
                    button.tween.PlayBackwards();
                    button.animating = false;
                }
                if ((bool)button.icon && button.scaleIcon != 1f)
                {
                    button.icon.transform.localScale = button.originalIconScale;
                }
            }
        }
        buttons.Clear();
    }
References animating, icon, originalIconScale, scaleIcon, and tween.
Referenced by Scene.OnUpdate().
Member Data Documentation
actionTooltip
Action UIButton.actionTooltip static
Definition at line 184 of file UIButton.cs.
Referenced by Core.LateUpdate().
animating
bool UIButton.animating
Definition at line 160 of file UIButton.cs.
Referenced by UpdateButtons().
animeClick
Anime UIButton.animeClick
Definition at line 136 of file UIButton.cs.
Referenced by OnPointerDown().
animeHold
Anime UIButton.animeHold
Definition at line 138 of file UIButton.cs.
animeTarget
Transform UIButton.animeTarget
Definition at line 134 of file UIButton.cs.
Referenced by OnPointerDown().
buttonPos
Vector2 UIButton.buttonPos static
Definition at line 98 of file UIButton.cs.
Referenced by HotItemContext.OnClick(), OnHover(), and RefreshItem().
buttons
List<UIButton> UIButton.buttons = new List<UIButton>() static
Definition at line 182 of file UIButton.cs.
Referenced by WidgetHotbar.GetSwapButton(), and WidgetHotbar.RefreshButtons().
buttonType
ButtonType UIButton.buttonType
Definition at line 140 of file UIButton.cs.
currentHighlight
UIButton UIButton.currentHighlight static
Definition at line 90 of file UIButton.cs.
Referenced by UI.ShowMouseHint().
currentPressedButton
UIButton UIButton.currentPressedButton static
Definition at line 92 of file UIButton.cs.
Referenced by OnPointerClick(), and OnPointerDown().
DoSlide
bool UIButton.DoSlide static
Definition at line 82 of file UIButton.cs.
doubleClickTime
float UIButton.doubleClickTime = 0.4f static
Definition at line 96 of file UIButton.cs.
group
UISelectableGroup UIButton.group
Definition at line 126 of file UIButton.cs.
Referenced by UIList.Select(), and Toggle().
highlightTarget
UIButton UIButton.highlightTarget
Definition at line 169 of file UIButton.cs.
icon
Image UIButton.icon
Definition at line 110 of file UIButton.cs.
Referenced by WindowMenu._AddButton(), WidgetCurrentTool._RefreshCurrentHotItem(), UICurrency.Add(), WidgetInspector.AddButton(), Awake(), ItemGeneral.DisableIcon(), DragItemCard.DragItemCard(), DragItem.GetDragImage(), WidgetMemo.OnActivate(), OnEnable(), LayerQuickMenu.OnInit(), NotificationBuff.OnInstantiate(), ListPeopleBed.OnInstantiate(), InvOwnerDraglet.OnProcess(), NotificationBuff.OnRefresh(), LayerAbility.OnStartDrag(), WidgetHotbar.OnStartDrag(), ButtonElement.Refresh(), LayerInspect.Refresh(), LayerTravel.Refresh(), LayerWorldSetting.Refresh(), UIDistribution.Refresh(), UIInspector.Refresh(), UIPlaceHelper.Refresh(), BaseSticky.RefreshButton(), LayerDragGrid.RefreshCost(), WindowCharaMini.RefreshEquipment(), WindowChara.RefreshEquipment(), UIInventory.RefreshGrid(), ButtonHotItem.RefreshItem(), RefreshItem(), ContentCodex.RefreshList(), LayerCraft.RefreshProduct(), LayerCraft.RefreshTrackButton(), LayerAbility.SelectGroup(), ButtonAbility.SetAct(), GridItemCard.SetButton(), GridItemCardSource.SetButton(), GridItemRecipe.SetButton(), LayerCollectible.SetButton(), ButtonGeneral.SetCard(), ButtonRoster.SetChara(), ItemGeneral.SetChara(), ButtonElement.SetGrid(), LayerDragGrid.SetInv(), ItemGeneral.SetMainText(), ButtonResourceTrack.SetProp(), ItemPopulation.SetTopic(), WidgetHotbar.SetVisible(), LayerCraftFloat.ShowContextMenu(), LayerInteraction.ShowPage(), WidgetMemo.ToggleAutoHide(), TraitMapBoard.TrySetAct(), and UpdateButtons().
imageCheck
Image UIButton.imageCheck
Definition at line 112 of file UIButton.cs.
Referenced by OnEnable(), ContentPolicy.RefreshPolicyIcons(), LayerPolicy.RefreshPolicyIcons(), and SetCheck().
instantClick
bool UIButton.instantClick = true
Definition at line 124 of file UIButton.cs.
Referenced by OnPointerClick(), OnPointerDown(), and ButtonHotItem.RefreshItem().
isChecked
bool UIButton.isChecked
Definition at line 122 of file UIButton.cs.
Referenced by OnEnable(), SetCheck(), SetToggle(), Toggle(), and ToggleCheck().
item
Item UIButton.item
Definition at line 172 of file UIButton.cs.
Referenced by WidgetHotbar._OnDirtyInventory(), WidgetHotbar.CheckAutoHide(), Portrait.ListPortraits(), WidgetHotbar.OnEndDrag(), OnHover(), WidgetHotbar.OnSetContextMenu(), ButtonHotItem.Refresh(), WidgetHotbar.RefreshHighlight(), ButtonHotItem.RefreshItem(), RefreshItem(), ButtonElement.SetGrid(), SetItem(), UIButtonLR.SetOptions< T >(), WidgetHotbar.SetVisible(), ButtonAbility.SpecialHoldAction(), and WidgetHotbar.ToggleVisible().
keyText
UIText UIButton.keyText
Definition at line 108 of file UIButton.cs.
Referenced by ItemGeneral.DisableIcon(), Dialog.OnUpdateInput(), LayerList.OnUpdateInput(), and UIList.Refresh().
lastButton
UIButton UIButton.lastButton static
Definition at line 86 of file UIButton.cs.
lastClicked
float UIButton.lastClicked static
Definition at line 94 of file UIButton.cs.
lastHovered
UIButton UIButton.lastHovered static
Definition at line 88 of file UIButton.cs.
Referenced by OnHover().
lastState
SelectionState UIButton.lastState private
Definition at line 178 of file UIButton.cs.
locked
bool UIButton.locked static
Definition at line 84 of file UIButton.cs.
m_graphics
List<Graphic> UIButton.m_graphics private
Definition at line 174 of file UIButton.cs.
mainText
UIText UIButton.mainText
Definition at line 102 of file UIButton.cs.
Referenced by UICurrency.Add(), Window.AddBottomButton(), WidgetInspector.AddButton(), LayerFaith.AddReligion(), ActionHint.AddToggle(), Window.BuildTabs(), TraitCrafter.Craft(), DragItemCard.DragItemCard(), BuildMenu.Init(), LayerNewspaper.OnClickPage(), LayerMod.OnInit(), LayerWorldSetting.OnInit(), NotificationHome.OnRefresh(), ContentKeyItem.OnSwitchContent(), ContentQuest.OnSwitchContent(), LayerConfig.OnSwitchContent(), LayerQuestBoard.OnSwitchContent(), ButtonElement.Refresh(), ButtonRoster.Refresh(), LayerTravel.Refresh(), LayerWorldSetting.Refresh(), PartialMapMenu.Refresh(), UIInspector.Refresh(), WindowCharaMini.Refresh(), UIMagicChest.RefreshBottom(), BaseSticky.RefreshButton(), LayerEditPortrait.RefreshButtons(), LayerCraftFloat.RefreshDisassemble(), UIHomeInfo.RefreshInfo(), LayerLoadGame.RefreshInfo(), ButtonHotItem.RefreshItem(), ContentCodex.RefreshList(), LayerEditPortrait.RefreshList(), LayerEditSkin.RefreshList(), LayerLoadGame.RefreshList(), ContentPolicy.RefreshPolicyList(), LayerPolicy.RefreshPolicyList(), UIHomeInfo.RefreshReport(), ContentConfigOther.RefreshRewardCode(), WidgetSearch.RefreshWords(), UIButtonLR.SelectOption(), ButtonAbility.SetAct(), GridItemCardSource.SetButton(), GridItemRecipe.SetButton(), ButtonGeneral.SetCard(), ItemGeneral.SetChara(), ButtonElement.SetGrid(), ItemGeneral.SetMainText(), BaseSticky.SetText(), TerrainMenu.Show(), LayerInteraction.ShowPage(), and Thing.ShowSplitMenu2().
navigationFix
float UIButton.navigationFix
Definition at line 120 of file UIButton.cs.
onDoubleClick
Action UIButton.onDoubleClick
Definition at line 144 of file UIButton.cs.
onInputWheel
Action<int> UIButton.onInputWheel
Definition at line 148 of file UIButton.cs.
Referenced by Scene.OnUpdate().
onPressed
Action UIButton.onPressed static
Definition at line 100 of file UIButton.cs.
Referenced by OnPointerClick().
onRightClick
Action UIButton.onRightClick
Definition at line 146 of file UIButton.cs.
Referenced by OnPointerDown(), ButtonHotItem.RefreshItem(), ButtonAbility.SetAct(), ButtonResourceTrack.SetCat(), and ButtonResourceTrack.SetProp().
originalIconScale
Vector3 UIButton.originalIconScale = Vector3.one
Definition at line 166 of file UIButton.cs.
Referenced by Awake(), and UpdateButtons().
refInt
int UIButton.refInt
Definition at line 154 of file UIButton.cs.
refObj
object UIButton.refObj
Definition at line 151 of file UIButton.cs.
refStr
string UIButton.refStr
Definition at line 157 of file UIButton.cs.
scaleIcon
float UIButton.scaleIcon = 1f
Definition at line 116 of file UIButton.cs.
Referenced by OnEnable(), and UpdateButtons().
selected
bool UIButton.selected
Definition at line 163 of file UIButton.cs.
Referenced by OnEnable(), UIDynamicList.RefreshHighlight(), and UIDynamicList.UpdateRow().
skinRoot
BaseSkinRoot UIButton.skinRoot
Definition at line 142 of file UIButton.cs.
Referenced by UIText.ApplySkin(), NotificationCondition.OnRefresh(), and NotificationStats.OnRefresh().
slideX
float UIButton.slideX
Definition at line 118 of file UIButton.cs.
soundClick
SoundData UIButton.soundClick
Definition at line 130 of file UIButton.cs.
Referenced by DramaEventTalk.Play().
soundHighlight
SoundData UIButton.soundHighlight
Definition at line 132 of file UIButton.cs.
subText
UIText UIButton.subText
Definition at line 104 of file UIButton.cs.
Referenced by WidgetMenuPanel.AddButton(), LayerWidget.OnInit(), ButtonElement.Refresh(), ButtonHotItem.Refresh(), ButtonResourceTrack.Refresh(), LayerTravel.Refresh(), LayerFactions.RefreshFactions(), ContentFaction.RefreshFactions(), ButtonHotItem.RefreshItem(), RefreshItem(), UIInventory.RefreshList(), LayerLoadGame.RefreshList(), ContentPolicy.RefreshPolicyIcons(), LayerPolicy.RefreshPolicyIcons(), ButtonElement.SetGrid(), ItemResearch.SetPlan(), ItemHomeResource.SetResource(), ItemGeneral.SetSubText(), and SetToggleWithScore().
subText2
UIText UIButton.subText2
Definition at line 106 of file UIButton.cs.
Referenced by WidgetCurrentTool.RebuildSlots(), LayerTravel.Refresh(), ContentCodex.RefreshList(), LayerLoadGame.RefreshList(), and ItemGeneral.SetSubText2().
targetGraphics
Graphic [] UIButton.targetGraphics
Definition at line 114 of file UIButton.cs.
tooltip
TooltipData UIButton.tooltip
Definition at line 128 of file UIButton.cs.
Referenced by ShowTooltip(), and ShowTooltipForced().
tween
Tween UIButton.tween private
Definition at line 176 of file UIButton.cs.
Referenced by UpdateButtons().
waiting
bool UIButton.waiting static private
Definition at line 180 of file UIButton.cs.
Referenced by OnPointerClick(), OnPointerDown(), and ShowTooltip().
Property Documentation
CanDragLeftButton
virtual bool UIButton.CanDragLeftButton get
Definition at line 210 of file UIButton.cs.
Referenced by ButtonGridDrag.OnDrag().
Graphics
List<Graphic> UIButton.Graphics get protected
Definition at line 186 of file UIButton.cs.
    {
        get
        {
            if (m_graphics == null)
            {
                m_graphics = new List<Graphic>();
                if (base.targetGraphic != null)
                {
                    m_graphics.Add(base.targetGraphic);
                }
                if (targetGraphics != null)
                {
                    Graphic[] array = targetGraphics;
                    foreach (Graphic graphic in array)
                    {
                        m_graphics.Add(graphic);
                    }
                }
            }
            return m_graphics;
        }
    }
The documentation for this class was generated from the following file:
Elin/Plugins.UI/UIButton.cs