Elin Decompiled Documentation: HotItemToggle Class Reference
HotItemToggle Class Reference
Public Types
enum Type {
ToggleRoof , showBalloon , muteBGM , instaComplete ,
ToggleSlope , ToggleWall , ToggleFreepos , SnapFreepos ,
ToggleBuildLight , ToggleRoofEdit , ToggleNoRoof
}
Public Member Functions
override bool ShouldHighlight ()
override void OnClick (ButtonHotItem b, Hotbar h)
Public Member Functions inherited from HotItem
string TextHotkey ()
virtual void OnClick (ButtonHotItem b, Hotbar h)
virtual void OnRightClick (ButtonHotItem b)
virtual bool CanAutoFire (Chara tg)
virtual void OnSetCurrentItem ()
virtual void OnUnsetCurrentItem ()
virtual void OnUnselect ()
virtual void SetImage (Image icon)
virtual bool TrySetAct (ActPlan p)
virtual void OnMarkMapHighlights ()
virtual void OnRenderTile (Point point, HitResult result, int dir)
Public Member Functions inherited from UIButton.Item
virtual Sprite GetSprite ()
virtual Sprite GetSprite (bool highlight)
virtual bool ShouldHighlight ()
virtual void OnAddedToBar ()
virtual void OnShowContextMenu (UIContextMenu m)
virtual void OnHover (UIButton b)
virtual void OnClick (UIButton b)
virtual void OnSetItem (UIButton b)
virtual void SetSubText (UIText t)
Public Attributes
Type type
Public Attributes inherited from HotItem
ButtonHotItem button
Hotbar hotbar
bool disabled
Public Attributes inherited from UIButton.Item
bool always
Properties
override string Name [get]
override Sprite SpriteHighlight [get]
override string pathSprite [get]
override bool Hidden [get]
Properties inherited from HotItem
override Sprite SpriteHighlight [get]
override bool IsSelectable [get]
override string TextTip [get]
virtual Thing RenderThing [get]
virtual Thing Thing [get]
virtual Thing Tool [get]
virtual bool IsTool [get]
virtual bool LookAtMouse [get]
virtual bool IsGameAction [get]
virtual bool UseUIObjMaterial [get]
Properties inherited from UIButton.Item
virtual string TextTip [get]
virtual string Name [get]
virtual Sprite SpriteHighlight [get]
virtual string pathSprite [get]
virtual bool IsSelectable [get]
virtual bool AdjustImageSize [get]
virtual bool UseIconForHighlight [get]
virtual bool KeepVisibleWhenHighlighted [get]
virtual Color SpriteColor [get]
virtual Vector3 SpriteScale [get]
virtual bool Hidden [get]
virtual Transition Transition [get]
Detailed Description
Definition at line 4 of file HotItemToggle.cs.
Member Enumeration Documentation
Type
enum HotItemToggle.Type
Enumerator
ToggleRoof
showBalloon
muteBGM
instaComplete
ToggleSlope
ToggleWall
ToggleFreepos
SnapFreepos
ToggleBuildLight
ToggleRoofEdit
ToggleNoRoof
Definition at line 6 of file HotItemToggle.cs.
    {
        ToggleRoof,
        showBalloon,
        muteBGM,
        instaComplete,
        ToggleSlope,
        ToggleWall,
        ToggleFreepos,
        SnapFreepos,
        ToggleBuildLight,
        ToggleRoofEdit,
        ToggleNoRoof
    }
Member Function Documentation
OnClick()
override void HotItemToggle.OnClick (ButtonHotItem b, Hotbar h) inline virtual
Reimplemented from HotItem.
Definition at line 60 of file HotItemToggle.cs.
    {
        switch (type)
        {
        case Type.ToggleBuildLight:
            EClass.scene.ToggleLight();
            break;
        case Type.SnapFreepos:
            EClass.scene.ToggleSnapFreePos();
            break;
        case Type.ToggleFreepos:
            EClass.scene.ToggleFreePos();
            break;
        case Type.ToggleWall:
            EClass.scene.ToggleShowWall();
            break;
        case Type.ToggleRoof:
            EClass.scene.ToggleShowRoof();
            break;
        case Type.ToggleNoRoof:
            EClass.scene.ToggleRoof();
            break;
        case Type.showBalloon:
            EClass.scene.ToggleBalloon();
            break;
        case Type.muteBGM:
            EClass.scene.ToggleMuteBGM();
            break;
        case Type.instaComplete:
            EClass.player.instaComplete = !EClass.player.instaComplete;
            SE.ClickGeneral();
            if ((bool)b)
            {
                b.widget.RefreshHighlight();
            }
            break;
        case Type.ToggleSlope:
            EClass.scene.ToggleSlope();
            break;
        }
        if ((bool)b)
        {
            b.widget.RefreshHighlight();
        }
    }
References Player.instaComplete, EClass.player, WidgetHotbar.RefreshHighlight(), EClass.scene, Scene.ToggleBalloon(), Scene.ToggleFreePos(), Scene.ToggleLight(), Scene.ToggleMuteBGM(), Scene.ToggleRoof(), Scene.ToggleShowRoof(), Scene.ToggleShowWall(), Scene.ToggleSlope(), Scene.ToggleSnapFreePos(), type, and ButtonHotItem.widget.
ShouldHighlight()
override bool HotItemToggle.ShouldHighlight () inline virtual
Reimplemented from UIButton.Item.
Definition at line 42 of file HotItemToggle.cs.
    {
        return type switch
        {
            Type.ToggleBuildLight => EClass.game.config.buildLight,
            Type.SnapFreepos => EClass.game.config.snapFreePos,
            Type.ToggleFreepos => EClass.game.config.freePos,
            Type.ToggleWall => EClass.game.config.showWall,
            Type.ToggleRoof => EClass.game.config.showRoof,
            Type.ToggleNoRoof => EClass.game.config.noRoof,
            Type.showBalloon => !EClass.scene.hideBalloon,
            Type.muteBGM => EClass.Sound.muteBGM,
            Type.instaComplete => EClass.player.instaComplete,
            Type.ToggleSlope => EClass.game.config.slope,
            _ => false,
        };
    }
References Game.Config.buildLight, Game.config, Game.Config.freePos, EClass.game, Scene.hideBalloon, Player.instaComplete, Game.Config.noRoof, EClass.player, EClass.scene, Game.Config.showRoof, Game.Config.showWall, Game.Config.slope, Game.Config.snapFreePos, EClass.Sound, and type.
Member Data Documentation
type
Type HotItemToggle.type
Definition at line 22 of file HotItemToggle.cs.
Referenced by OnClick(), and ShouldHighlight().
Property Documentation
Hidden
override bool HotItemToggle.Hidden get
Definition at line 30 of file HotItemToggle.cs.
    {
        get
        {
            if (type == Type.instaComplete)
            {
                return !EClass.debug.enable;
            }
            return false;
        }
    }
Name
override string HotItemToggle.Name get
Definition at line 24 of file HotItemToggle.cs.
pathSprite
override string HotItemToggle.pathSprite get
Definition at line 28 of file HotItemToggle.cs.
SpriteHighlight
override Sprite HotItemToggle.SpriteHighlight get
Definition at line 26 of file HotItemToggle.cs.
The documentation for this class was generated from the following file:
Elin/HotItemToggle.cs