Elin Decompiled Documentation: UIHomeInfo Class Reference
UIHomeInfo Class Reference
Classes
class ReportData
Public Member Functions
void Refresh ()
void RefreshInfo ()
string GetTextHappiness (List< Chara > list)
void RefreshResources ()
void AddReport (string text, UIHomeInfo.ReportData.ReportType type=UIHomeInfo.ReportData.ReportType.Default, Action onClick=null, Action< UITooltip > onShowTooltip=null)
void RefreshReport ()
Public Attributes
Transform transLayout
UIText textFaction
UIText textDateFound
UIText textGod
UIText textMember
UIText textLand
UIText textHeaderReport
UIText textDev
UIText textElec
UIText textCivility
UIText textName
UIText textRank
UIText textPopu
UIText textFaith
UIText textTemper
UIText textSoil
UIText textContentLv
UIText textPasture
UIButton buttonHappinessResident
UIButton buttonHappinessLivestock
UIButton buttonWorth
UIButton buttonRank
UIButton buttonLv
UIButton buttonRanking
UIList listCurrencies
UIList listResources
UIList listSkill
UIList listReport
Faction faction
FactionBranch branch
Zone zone
Image imageFaith
Image barTemper
List< UIHomeInfo.ReportData > reports = new List<UIHomeInfo.ReportData>()
Sprite[] iconReports
Properties
int tabResearch [get]
Properties inherited from EMono
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SoundManager Sound [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static CoreDebug debug [get]
Private Member Functions
void< RefreshInfo > g__Write (int lv, ref UIHomeInfo.<>c__DisplayClass38_0 A_2)
Additional Inherited Members
Static Public Member Functions inherited from EMono
static int rnd (int a)
Static Public Attributes inherited from EMono
static Core core
Detailed Description
Definition at line 7 of file UIHomeInfo.cs.
Member Function Documentation
AddReport()
void UIHomeInfo.AddReport (string text, UIHomeInfo::ReportData::ReportType type = UIHomeInfo::ReportData::ReportType::Default, Action onClick = null, Action< UITooltip > onShowTooltip = null) inline
Definition at line 232 of file UIHomeInfo.cs.
    {
        UIHomeInfo.ReportData item = new UIHomeInfo.ReportData
        {
            text = text.lang(),
            type = type,
            onClick = onClick,
            onShowTooltip = onShowTooltip
        };
        this.reports.Add(item);
    }
References reports, and text.
Referenced by RefreshInfo(), and RefreshReport().
g__Write()
void< RefreshInfo > UIHomeInfo.g__Write (int lv, ref UIHomeInfo::<>c__DisplayClass38_0 A_2) inline private
Definition at line 366 of file UIHomeInfo.cs.
    {
        string[] array = this.branch.GetHearthHint(lv).SplitNewline();
        for (int i = 0; i < array.Length; i++)
        {
            string text = array[i].Replace(Environment.NewLine, "");
            if (!text.IsEmpty())
            {
                A_2.n.AddText(text, FontColor.DontChange);
            }
        }
    }
References branch, FactionBranch.GetHearthHint(), and text.
Referenced by RefreshInfo().
GetTextHappiness()
string UIHomeInfo.GetTextHappiness (List< Chara > list) inline
Definition at line 134 of file UIHomeInfo.cs.
    {
        int num = 0;
        int num2 = 0;
        int num3 = 0;
        int num4 = 0;
        foreach (Chara chara in list)
        {
            int happiness = chara.GetHappiness();
            if (happiness >= 80)
            {
                num2++;
            }
            else if (happiness >= 30)
            {
                num3++;
            }
            else
            {
                num4++;
            }
            num += happiness;
        }
        int avg = (list.Count == 0) ? 0 : (num / list.Count);
        string s = string.Concat(new string[]
        {
            "(",
            num2.ToString().TagColor(FontColor.Good, null),
            "/",
            num3.ToString().TagColor(FontColor.Default, null),
            "/",
            num4.ToString().TagColor(FontColor.Bad, null),
            ")"
        });
        return (((list.Count == 0) ? " - " : avg.ToString()) + "%").TagColorGoodBad(() => list.Count == 0 || avg >= 50, false) + " " + s.TagSize(13);
    }
References Chara.GetHappiness().
Refresh()
void UIHomeInfo.Refresh () inline
Definition at line 17 of file UIHomeInfo.cs.
    {
        EMono._zone.RefreshElectricity();
        this.reports.Clear();
        this.faction = EMono.pc.faction;
        this.branch = (EMono.Branch ?? EMono.pc.homeZone.branch);
        FactionBranch factionBranch = EMono.Branch;
        this.zone = (((factionBranch != null) ? factionBranch.owner : null) ?? EMono.pc.homeZone);
        this.branch.resources.Refresh();
        this.RefreshInfo();
        this.RefreshResources();
        this.RefreshReport();
        this.transLayout.RebuildLayoutTo(this);
    }
References EMono._zone, EMono.Branch, branch, Zone.branch, Chara.faction, Chara.homeZone, FactionBranch.owner, EMono.pc, HomeResourceManager.Refresh(), Zone.RefreshElectricity(), RefreshInfo(), RefreshReport(), RefreshResources(), reports, FactionBranch.resources, and transLayout.
Referenced by LayerHome.OnSwitchContent().
RefreshInfo()
void UIHomeInfo.RefreshInfo () inline
Definition at line 32 of file UIHomeInfo.cs.
    {
        this.textHeaderReport.text = "headerHomeReport".lang(EMono.world.date.year.ToString() ?? "", EMono.world.date.month.ToString() + "/" + EMono.world.date.day.ToString(), null, null, null);
        this.textFaction.text = EMono.pc.faction.Name;
        this.textGod.text = this.branch.faith.Name;
        this.textContentLv.text = this.branch.DangerLV.ToString() + " " + ("(" + this.branch.ContentLV.ToString() + ")").TagSize(12);
        this.textDateFound.text = Date.GetText(this.branch.dateFound, Date.TextFormat.YearMonthDay);
        this.textPasture.text = this.branch.CountPasture().ToString() + " " + ("(-" + this.branch.GetPastureCost().ToString() + "dailyIncome".lang() + ")").TagSize(12);
        bool flag = this.branch.CountMembers(FactionMemberType.Default, false) > this.branch.MaxPopulation;
        this.textMember.SetText(this.branch.CountMembers(FactionMemberType.Default, false).ToString() + " / " + this.branch.MaxPopulation.ToString(), flag ? FontColor.Bad : FontColor.Default);
        if (flag)
        {
            this.AddReport("rPopOver", UIHomeInfo.ReportData.ReportType.Warning, null, null);
        }
        this.textDev.text = ((EMono._zone.development / 10).ToString() ?? "");
        this.textLand.text = (EMono._map.bounds.Width * EMono._map.bounds.Height / 100).ToString() + " ";
        int civility = this.branch.GetCivility();
        this.textCivility.text = civility.ToString() + " " + ("(" + Lang.GetList("civility")[Mathf.Clamp(civility / 20, 0, 4)] + ")").TagSize(12);
        int electricity = EMono._zone.GetElectricity(true);
        int electricity2 = EMono._zone.GetElectricity(false);
        this.textElec.SetText("elecLv".lang(electricity2.ToString() ?? "", (electricity.ToString() ?? "").TagColor((electricity <= electricity2) ? FontColor.Good : FontColor.Bad, null), null, null, null));
        if (electricity > electricity2)
        {
            this.AddReport("rElecOver", UIHomeInfo.ReportData.ReportType.Warning, null, null);
        }
        int soilCost = this.zone.GetSoilCost();
        int maxSoil = this.branch.MaxSoil;
        this.textSoil.SetText("soilLv".lang(maxSoil.ToString() ?? "", ((maxSoil - soilCost).ToString() ?? "").TagColor((soilCost <= maxSoil) ? FontColor.Good : FontColor.Bad, null), null, null, null));
        if (soilCost > maxSoil)
        {
            this.AddReport("rSoilOver", UIHomeInfo.ReportData.ReportType.Warning, null, null);
        }
        this.textName.SetText(this.zone.Name);
        this.textRank.SetText(this.branch.RankText);
        this.textPopu.SetText(this.faction.name);
        this.textFaith.SetText(this.branch.faith.Name + Environment.NewLine + (" " + this.branch.RankText).TagSize(13));
        this.imageFaith.sprite = this.branch.faith.GetSprite();
        this.textTemper.SetText(this.branch.faith.GetTextTemper(this.branch.temper));
        this.barTemper.fillAmount = 0.5f + (float)this.branch.temper * 0.01f * 0.5f;
        this.barTemper.color = ((this.branch.temper > -25) ? SkinManager.CurrentColors.textGood : SkinManager.CurrentColors.textBad);
        if (this.buttonWorth)
        {
            this.buttonWorth.mainText.SetText(this.branch.Worth.ToFormat());
            this.buttonWorth.SetTooltip(delegate(UITooltip t)
            {
                this.branch.resources.worth.WriteNote(t.note);
            }, true);
        }
        this.buttonLv.mainText.SetText(this.branch.lv.ToString() ?? "");
        this.buttonLv.SetTooltip(delegate(UITooltip t)
        {
            UIHomeInfo.<>c__DisplayClass38_0 CS$<>8__locals1;
            CS$<>8__locals1.n = t.note;
            CS$<>8__locals1.n.Clear();
            CS$<>8__locals1.n.AddHeader("branchLv".lang(), null);
            CS$<>8__locals1.n.AddTopic("TopicLeft", "vCurrent".lang(), EMono.Branch.TextLv);
            CS$<>8__locals1.n.Space(0, 1);
            this.<RefreshInfo>g__Write|38_6(this.branch.lv, ref CS$<>8__locals1);
            if (this.branch.lv < this.branch.MaxLv)
            {
                CS$<>8__locals1.n.Space(0, 1);
                CS$<>8__locals1.n.AddHeaderTopic("nextLevel", null);
                this.<RefreshInfo>g__Write|38_6(this.branch.lv + 1, ref CS$<>8__locals1);
            }
            t.note.Build();
        }, true);
        this.buttonRanking.mainText.SetText(EMono.game.spatials.ranks.GetRankText(EMono._zone));
        this.buttonRanking.SetTooltip(delegate(UITooltip t)
        {
            UINote note = t.note;
            note.Clear();
            note.AddHeader("homeRanking".lang(), null);
            note.AddTopic("TopicLeft", "vCurrent".lang(), EMono.game.spatials.ranks.GetRankText(EMono._zone));
            note.Space(0, 1);
            note.AddHeader("HeaderTopic", "rank_income".lang(), null);
            note.Space(1, 1);
            note.AddText("rank_income2".lang(EMono.game.spatials.ranks.GetIncome(EMono._zone).ToFormat(), null, null, null, null), FontColor.DontChange);
            t.note.Build();
        }, true);
        this.buttonRank.mainText.SetText(this.branch.rank.ToString() ?? "");
        this.buttonRank.SetTooltip(delegate(UITooltip t)
        {
            UINote note = t.note;
            note.Clear();
            note.AddHeader("factionRank2".lang(), null);
            note.AddTopic("TopicLeft", "vCurrent".lang(), this.branch.rank.ToString() ?? "");
            t.note.Build();
        }, true);
        this.buttonHappinessResident.mainText.text = this.branch.happiness.residents.GetText();
        this.buttonHappinessLivestock.mainText.text = this.branch.happiness.livestocks.GetText();
        this.buttonHappinessResident.subText.text = (this.branch.CountMembers(FactionMemberType.Default, false).ToString() ?? "");
        this.buttonHappinessLivestock.subText.text = (this.branch.CountMembers(FactionMemberType.Livestock, false).ToString() ?? "");
        this.buttonHappinessResident.SetTooltip(delegate(UITooltip t)
        {
            this.branch.happiness.residents.WriteNote(t.note);
        }, true);
        this.buttonHappinessLivestock.SetTooltip(delegate(UITooltip t)
        {
            this.branch.happiness.livestocks.WriteNote(t.note);
        }, true);
    }
References EMono._zone, AddReport(), EMono.Branch, branch, buttonHappinessLivestock, buttonHappinessResident, buttonLv, buttonRank, buttonRanking, buttonWorth, FactionBranch.ContentLV, FactionBranch.CountMembers(), FactionBranch.CountPasture(), FactionBranch.DangerLV, World.date, FactionBranch.dateFound, Date.day, Chara.faction, faction, FactionBranch.faith, g__Write(), EMono.game, FactionBranch.GetCivility(), Zone.GetElectricity(), RankedZoneManager.GetIncome(), FactionBranch.GetPastureCost(), RankedZoneManager.GetRankText(), Zone.GetSoilCost(), Religion.GetSprite(), Happiness.GetText(), Date.GetText(), Religion.GetTextTemper(), FactionBranch.happiness, HappinessManager.livestocks, FactionBranch.lv, FactionBranch.MaxPopulation, FactionBranch.MaxSoil, Date.month, Faction.Name, Faction.name, Religion.Name, Spatial.Name, EMono.pc, FactionBranch.rank, SpatialManager.ranks, FactionBranch.RankText, RefreshInfo(), HappinessManager.residents, FactionBranch.resources, Game.spatials, FactionBranch.temper, textElec, textFaith, FactionBranch.TextLv, textMember, textName, textPopu, textRank, textSoil, textTemper, EMono.world, FactionBranch.Worth, HomeResourceManager.worth, Happiness.WriteNote(), HomeResourceWorth.WriteNote(), Date.year, and zone.
Referenced by Refresh(), and RefreshInfo().
RefreshReport()
void UIHomeInfo.RefreshReport () inline
Definition at line 244 of file UIHomeInfo.cs.
    {
        if (EMono.Branch.meetings.list.Count > 0)
        {
            this.AddReport("rMeeting".lang(EMono.Branch.meetings.list.Count.ToString() ?? "", null, null, null, null), UIHomeInfo.ReportData.ReportType.Default, null, null);
        }
        foreach (ZoneEvent zoneEvent in this.branch.owner.events.list)
        {
            if (zoneEvent.HasReport)
            {
                this.AddReport(zoneEvent.GetText(), UIHomeInfo.ReportData.ReportType.Trial, null, null);
            }
        }
        foreach (ResearchPlan researchPlan in this.branch.researches.newPlans)
        {
            this.AddReport("rNewPlan".lang(researchPlan.Name ?? "", null, null, null, null), UIHomeInfo.ReportData.ReportType.Good, delegate
            {
            }, null);
        }
        foreach (ResearchPlan researchPlan2 in this.branch.researches.plans)
        {
            if (researchPlan2.exp == researchPlan2.MaxExp)
            {
                this.AddReport("vResearched".lang(researchPlan2.Name, null, null, null, null), UIHomeInfo.ReportData.ReportType.Great, delegate
                {
                }, null);
            }
        }
        foreach (Chara chara in this.branch.members)
        {
            if (!chara.isDead && !chara.IsPCParty && chara.memberType == FactionMemberType.Default && !chara.noMove)
            {
                bool flag = false;
                if (EMono.game.activeZone == this.branch.owner)
                {
                    using (List<Hobby>.Enumerator enumerator4 = chara.ListWorks(true).GetEnumerator())
                    {
                        while (enumerator4.MoveNext())
{
                            if (enumerator4.Current.GetEfficiency(chara) > 0)
{
                                flag = true;
                                break;
                            }
                        }
                        goto IL_26A;
                    }
                    goto IL_259;
                }
                goto IL_259;
                IL_26A:
                if (!flag)
                {
                    this.AddReport("rNoWork".lang(chara.Name, null, null, null, null).ToTitleCase(false), UIHomeInfo.ReportData.ReportType.Warning, null, null);
                    continue;
                }
                continue;
                IL_259:
                if (chara.GetWorkSummary().work != null)
                {
                    flag = true;
                    goto IL_26A;
                }
                goto IL_26A;
            }
        }
        if (EMono.player.taxBills > 0)
        {
            this.AddReport("rBill".lang(EMono.player.taxBills.ToString() ?? "", null, null, null, null), UIHomeInfo.ReportData.ReportType.Warning, null, null);
        }
        if (this.reports.Count == 0)
        {
            this.AddReport("rNoReport", UIHomeInfo.ReportData.ReportType.Good, null, null);
        }
        this.AddReport("rTax".lang((30 - EMono.world.date.day + 1).ToString() ?? "", this.faction.GetTotalTax(false).ToFormat(), null, null, null), UIHomeInfo.ReportData.ReportType.Default, null, delegate(UITooltip t)
        {
            t.note.Clear();
            this.faction.SetTaxTooltip(t.note);
            t.note.Build();
        });
        if (EMono.debug.showExtra)
        {
            this.AddReport("efficiency:" + this.branch.efficiency.ToString(), UIHomeInfo.ReportData.ReportType.Default, null, null);
        }
        this.reports.Sort((UIHomeInfo.ReportData a, UIHomeInfo.ReportData b) => b.type - a.type);
        this.listReport.Clear();
        BaseList baseList = this.listReport;
        UIList.Callback<UIHomeInfo.ReportData, ItemGeneral> callback = new UIList.Callback<UIHomeInfo.ReportData, ItemGeneral>();
        callback.onClick = delegate(UIHomeInfo.ReportData a, ItemGeneral b)
        {
            if (a.onClick != null)
            {
                a.onClick();
            }
        };
        callback.onInstantiate = delegate(UIHomeInfo.ReportData a, ItemGeneral b)
        {
            b.SetMainText(a.text, this.iconReports[(int)a.type], true);
            b.button1.mainText.SetColor(a.GetFontColor());
            if (a.onClick != null)
            {
                b.AddSubButton(EMono.core.refs.icons.go, a.onClick, null, null);
            }
            b.Build();
            if (a.onShowTooltip != null)
            {
                b.button1.SetTooltip(a.onShowTooltip, true);
            }
        };
        callback.onList = delegate(UIList.SortMode m)
        {
            foreach (UIHomeInfo.ReportData o in this.reports)
            {
                this.listReport.Add(o);
            }
        };
        callback.onRefresh = null;
        baseList.callbacks = callback;
        this.listReport.List(false);
    }
References Game.activeZone, AddReport(), ItemGeneral.AddSubButton(), EMono.Branch, branch, Zone.branch, ItemGeneral.Build(), EMono.core, World.date, Date.day, EMono.debug, FactionBranch.efficiency, Zone.events, ResearchPlan.exp, faction, EMono.game, ZoneEvent.GetText(), Chara.GetWorkSummary(), ZoneEvent.HasReport, Chara.isDead, Chara.IsPCParty, MeetingManager.list, ZoneEventManager.list, listReport, Chara.ListWorks(), ResearchPlan.MaxExp, FactionBranch.meetings, FactionBranch.members, Chara.memberType, Card.Name, ResearchPlan.Name, ResearchManager.newPlans, Card.noMove, FactionBranch.owner, ResearchManager.plans, EMono.player, reports, FactionBranch.researches, ItemGeneral.SetMainText(), Faction.SetTaxTooltip(), CoreDebug.showExtra, Player.taxBills, WorkSummary.work, and EMono.world.
Referenced by Refresh().
RefreshResources()
void UIHomeInfo.RefreshResources () inline
Definition at line 171 of file UIHomeInfo.cs.
    {
        this.listCurrencies.Clear();
        BaseList baseList = this.listCurrencies;
        UIList.Callback<BaseHomeResource, ItemHomeResource> callback = new UIList.Callback<BaseHomeResource, ItemHomeResource>();
        callback.onInstantiate = delegate(BaseHomeResource a, ItemHomeResource b)
        {
            b.SetResource(a);
        };
        callback.onList = delegate(UIList.SortMode m)
        {
            foreach (BaseHomeResource baseHomeResource in this.branch.resources.list)
            {
                if (baseHomeResource.IsCurrency && baseHomeResource.IsAvailable)
                {
                    this.listCurrencies.Add(baseHomeResource);
                }
            }
        };
        baseList.callbacks = callback;
        this.listCurrencies.List(false);
        this.listResources.Clear();
        BaseList baseList2 = this.listResources;
        UIList.Callback<BaseHomeResource, ItemHomeResource> callback2 = new UIList.Callback<BaseHomeResource, ItemHomeResource>();
        callback2.onInstantiate = delegate(BaseHomeResource a, ItemHomeResource b)
        {
            b.SetResource(a);
        };
        callback2.onList = delegate(UIList.SortMode m)
        {
            foreach (BaseHomeResource baseHomeResource in this.branch.resources.list)
            {
                if (baseHomeResource.IsRate && baseHomeResource.IsAvailable)
                {
                    this.listResources.Add(baseHomeResource);
                }
            }
        };
        baseList2.callbacks = callback2;
        this.listResources.List(false);
        this.listSkill.Clear();
        BaseList baseList3 = this.listSkill;
        UIList.Callback<BaseHomeResource, ItemHomeResource> callback3 = new UIList.Callback<BaseHomeResource, ItemHomeResource>();
        callback3.onInstantiate = delegate(BaseHomeResource a, ItemHomeResource b)
        {
            b.SetResource(a);
        };
        callback3.onList = delegate(UIList.SortMode m)
        {
            foreach (BaseHomeResource baseHomeResource in this.branch.resources.list)
            {
                if (baseHomeResource.IsSkill)
                {
                    this.listSkill.Add(baseHomeResource);
                }
            }
        };
        baseList3.callbacks = callback3;
        this.listSkill.List(false);
    }
References branch, BaseHomeResource.IsAvailable, BaseHomeResource.IsCurrency, BaseHomeResource.IsRate, BaseHomeResource.IsSkill, HomeResourceManager.list, listCurrencies, listResources, listSkill, FactionBranch.resources, and ItemHomeResource.SetResource().
Referenced by Refresh().
Member Data Documentation
barTemper
Image UIHomeInfo.barTemper
Definition at line 443 of file UIHomeInfo.cs.
branch
FactionBranch UIHomeInfo.branch
Definition at line 437 of file UIHomeInfo.cs.
Referenced by g__Write(), Refresh(), RefreshInfo(), RefreshReport(), and RefreshResources().
buttonHappinessLivestock
UIButton UIHomeInfo.buttonHappinessLivestock
Definition at line 417 of file UIHomeInfo.cs.
Referenced by RefreshInfo().
buttonHappinessResident
UIButton UIHomeInfo.buttonHappinessResident
Definition at line 415 of file UIHomeInfo.cs.
Referenced by RefreshInfo().
buttonLv
UIButton UIHomeInfo.buttonLv
Definition at line 423 of file UIHomeInfo.cs.
Referenced by RefreshInfo().
buttonRank
UIButton UIHomeInfo.buttonRank
Definition at line 421 of file UIHomeInfo.cs.
Referenced by RefreshInfo().
buttonRanking
UIButton UIHomeInfo.buttonRanking
Definition at line 425 of file UIHomeInfo.cs.
Referenced by RefreshInfo().
buttonWorth
UIButton UIHomeInfo.buttonWorth
Definition at line 419 of file UIHomeInfo.cs.
Referenced by RefreshInfo().
faction
Faction UIHomeInfo.faction
Definition at line 435 of file UIHomeInfo.cs.
Referenced by RefreshInfo(), and RefreshReport().
iconReports
Sprite [] UIHomeInfo.iconReports
Definition at line 447 of file UIHomeInfo.cs.
imageFaith
Image UIHomeInfo.imageFaith
Definition at line 441 of file UIHomeInfo.cs.
listCurrencies
UIList UIHomeInfo.listCurrencies
Definition at line 427 of file UIHomeInfo.cs.
Referenced by RefreshResources().
listReport
UIList UIHomeInfo.listReport
Definition at line 433 of file UIHomeInfo.cs.
Referenced by RefreshReport().
listResources
UIList UIHomeInfo.listResources
Definition at line 429 of file UIHomeInfo.cs.
Referenced by RefreshResources().
listSkill
UIList UIHomeInfo.listSkill
Definition at line 431 of file UIHomeInfo.cs.
Referenced by RefreshResources().
reports
List<UIHomeInfo.ReportData> UIHomeInfo.reports = new List<UIHomeInfo.ReportData>()
Definition at line 445 of file UIHomeInfo.cs.
Referenced by AddReport(), Refresh(), and RefreshReport().
textCivility
UIText UIHomeInfo.textCivility
Definition at line 397 of file UIHomeInfo.cs.
textContentLv
UIText UIHomeInfo.textContentLv
Definition at line 411 of file UIHomeInfo.cs.
textDateFound
UIText UIHomeInfo.textDateFound
Definition at line 383 of file UIHomeInfo.cs.
textDev
UIText UIHomeInfo.textDev
Definition at line 393 of file UIHomeInfo.cs.
textElec
UIText UIHomeInfo.textElec
Definition at line 395 of file UIHomeInfo.cs.
Referenced by RefreshInfo().
textFaction
UIText UIHomeInfo.textFaction
Definition at line 381 of file UIHomeInfo.cs.
textFaith
UIText UIHomeInfo.textFaith
Definition at line 405 of file UIHomeInfo.cs.
Referenced by RefreshInfo().
textGod
UIText UIHomeInfo.textGod
Definition at line 385 of file UIHomeInfo.cs.
textHeaderReport
UIText UIHomeInfo.textHeaderReport
Definition at line 391 of file UIHomeInfo.cs.
textLand
UIText UIHomeInfo.textLand
Definition at line 389 of file UIHomeInfo.cs.
textMember
UIText UIHomeInfo.textMember
Definition at line 387 of file UIHomeInfo.cs.
Referenced by RefreshInfo().
textName
UIText UIHomeInfo.textName
Definition at line 399 of file UIHomeInfo.cs.
Referenced by RefreshInfo().
textPasture
UIText UIHomeInfo.textPasture
Definition at line 413 of file UIHomeInfo.cs.
textPopu
UIText UIHomeInfo.textPopu
Definition at line 403 of file UIHomeInfo.cs.
Referenced by RefreshInfo().
textRank
UIText UIHomeInfo.textRank
Definition at line 401 of file UIHomeInfo.cs.
Referenced by RefreshInfo().
textSoil
UIText UIHomeInfo.textSoil
Definition at line 409 of file UIHomeInfo.cs.
Referenced by RefreshInfo().
textTemper
UIText UIHomeInfo.textTemper
Definition at line 407 of file UIHomeInfo.cs.
Referenced by RefreshInfo().
transLayout
Transform UIHomeInfo.transLayout
Definition at line 379 of file UIHomeInfo.cs.
Referenced by Refresh().
zone
Zone UIHomeInfo.zone
Definition at line 439 of file UIHomeInfo.cs.
Referenced by RefreshInfo().
Property Documentation
tabResearch
int UIHomeInfo.tabResearch get
Definition at line 9 of file UIHomeInfo.cs.
    {
        get
        {
            return 1;
        }
    }
The documentation for this class was generated from the following file:
Elin/UIHomeInfo.cs