Elin Decompiled Documentation: UIHeader Class Reference
UIHeader Class Reference
Public Member Functions
void SetText (string s)
Public Attributes
string lang1
UIText text1
bool rebuildLayout
Private Member Functions
void Start ()
Detailed Description
Definition at line 3 of file UIHeader.cs.
Member Function Documentation
SetText()
void UIHeader.SetText (string s) inline
Definition at line 24 of file UIHeader.cs.
    {
        lang1 = null;
        text1.SetText(s.lang().ToTitleCase());
        text1.RebuildLayout();
        this.RebuildLayout();
    }
References lang1, UIText.SetText(), and text1.
Referenced by Window.AddHeader(), WindowChara.RefreshSkill(), Window.SetTitles(), and UIInventory.SwitchTab().
Start()
void UIHeader.Start () inline private
Definition at line 11 of file UIHeader.cs.
    {
        if (!lang1.IsEmpty())
        {
            text1.SetLang(lang1);
        }
        if (rebuildLayout)
        {
            text1.RebuildLayout();
            this.RebuildLayout();
        }
    }
References lang1, rebuildLayout, UIText.SetLang(), and text1.
Member Data Documentation
lang1
string UIHeader.lang1
Definition at line 5 of file UIHeader.cs.
Referenced by SetText(), and Start().
rebuildLayout
bool UIHeader.rebuildLayout
Definition at line 9 of file UIHeader.cs.
Referenced by Start().
text1
UIText UIHeader.text1
Definition at line 7 of file UIHeader.cs.
Referenced by SetText(), and Start().
The documentation for this class was generated from the following file:
Elin/Plugins.UI/UIHeader.cs