Elin Decompiled Documentation: UIDistribution Class Reference
UIDistribution Class Reference
Public Member Functions
void SetContainer (Card t, Window.SaveData d)
void Refresh ()
Public Attributes
Card container
UIList list
Window.SaveData data
bool needRefresh
Private Member Functions
void OnEnable ()
Additional Inherited Members
Static Public Member Functions inherited from EMono
static int rnd (int a)
Static Public Attributes inherited from EMono
static Core core
Properties inherited from EMono
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SoundManager Sound [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static CoreDebug debug [get]
Detailed Description
Definition at line 3 of file UIDistribution.cs.
Member Function Documentation
OnEnable()
void UIDistribution.OnEnable () inline private
Definition at line 13 of file UIDistribution.cs.
    {
        if (needRefresh)
        {
            needRefresh = false;
            Refresh();
        }
    }
References needRefresh, and Refresh().
Refresh()
void UIDistribution.Refresh () inline
Definition at line 30 of file UIDistribution.cs.
    {
        HashSet<int> cats = data.cats;
        list.callbacks = new UIList.Callback<SourceCategory.Row, ButtonCategory>
        {
            onClick = delegate(SourceCategory.Row a, ButtonCategory b)
            {
                if (a.children.Count > 0)
                {
                    b.buttonFold.onClick.Invoke();
                }
            },
            onInstantiate = delegate(SourceCategory.Row a, ButtonCategory b)
            {
                b.uid = a.uid;
                b.mainText.text = a.GetName().ToTitleCase();
                bool flag3 = false;
                foreach (int item in cats)
                {
                    if (a.Contatin(item))
                    {
                        flag3 = true;
                        break;
                    }
                }
                b.SetFold(a.children.Count > 0, !flag3, delegate(UIList l)
                {
                    foreach (SourceCategory.Row child in a.children)
                    {
                        l.Add(child);
                    }
                });
                b.buttonToggle.icon.SetActive(cats.Contains(a.uid));
                b.buttonToggle.SetOnClick(delegate
                {
                    bool flag4 = !cats.Contains(a.uid);
                    b.buttonToggle.icon.SetActive(flag4);
                    if (flag4)
                    {
                        cats.Add(a.uid);
                    }
                    else
                    {
                        cats.Remove(a.uid);
                    }
                    SetAll(a.uid, flag4);
                    SE.Click();
                });
            },
            onRefresh = null
        };
        foreach (SourceCategory.Row row2 in EMono.sources.categories.rows)
        {
            if (row2.parent == null && row2.id != "new" && row2.id != "none")
            {
                list.Add(row2);
            }
        }
        list.Refresh();
        void SetAll(int uid, bool enable)
        {
            SourceCategory.Row row = EMono.sources.categories.rows.Find((SourceCategory.Row a) => a.uid == uid);
            if (row != null)
            {
                foreach (SourceCategory.Row row3 in EMono.sources.categories.rows)
                {
                    if (row.Contatin(row3.uid))
                    {
                        if (enable)
{
                            cats.Add(row3.uid);
                        }
                        else
{
                            cats.Remove(row3.uid);
                        }
                    }
                    else if (row.IsChildOf(row3.uid) && enable)
                    {
                        cats.Add(row3.uid);
                    }
                }
                bool flag;
                do
                {
                    flag = true;
                    foreach (SourceCategory.Row row4 in EMono.sources.categories.rows)
                    {
                        if (row4.children.Count != 0 && cats.Contains(row4.uid))
{
                            bool flag2 = false;
                            foreach (int item2 in cats)
{
                                if (item2 != row4.uid && row4.Contatin(item2))
{
                                    flag2 = true;
                                    break;
                                }
                            }
                            if (!flag2)
{
                                cats.Remove(row4.uid);
                                flag = false;
                            }
                        }
                    }
                }
                while (!flag);
                ButtonCategory[] componentsInChildren = list.GetComponentsInChildren<ButtonCategory>();
                foreach (ButtonCategory buttonCategory in componentsInChildren)
                {
                    buttonCategory.buttonToggle.icon.SetActive(cats.Contains(buttonCategory.uid));
                }
            }
        }
    }
References UIList.Add(), ButtonCategory.buttonFold, ButtonCategory.buttonToggle, SourceManager.categories, SourceCategory.Row.children, SourceCategory.Row.Contatin(), data, UIButton.icon, if(), SourceCategory.Row.IsChildOf(), item, list, UIList.Refresh(), ButtonCategory.SetFold(), EMono.sources, and ButtonCategory.uid.
Referenced by OnEnable().
SetContainer()
void UIDistribution.SetContainer (Card t, Window::SaveData d) inline
Definition at line 22 of file UIDistribution.cs.
    {
        container = t;
        data = d;
        needRefresh = true;
        this.SetActive(enable: false);
    }
References container, data, and needRefresh.
Referenced by UIInventory.ShowAdvDistribution().
Member Data Documentation
container
Card UIDistribution.container
Definition at line 5 of file UIDistribution.cs.
Referenced by SetContainer().
data
Window.SaveData UIDistribution.data
Definition at line 9 of file UIDistribution.cs.
Referenced by Refresh(), and SetContainer().
list
UIList UIDistribution.list
Definition at line 7 of file UIDistribution.cs.
Referenced by Refresh().
needRefresh
bool UIDistribution.needRefresh
Definition at line 11 of file UIDistribution.cs.
Referenced by OnEnable(), and SetContainer().
The documentation for this class was generated from the following file:
Elin/UIDistribution.cs