Elin Decompiled Documentation: Religion Class Reference
Religion Class Reference
Public Types
enum ConvertType { Default , Campaign }
Public Member Functions
virtual SourceElement.Row GetFeat (int i)
void Init ()
void OnLoad ()
void OnAdvanceDay ()
Sprite GetSprite ()
void SetTextRelation (UIText text)
string GetTextBenefit ()
string GetTextTemper (int _temper=-99999)
void Revelation (string idTalk, int chance=100)
void Talk (string idTalk, Card c=null, Card agent=null)
string GetGodTalk (string suffix)
virtual int GetOfferingMtp (Thing t)
int GetOfferingValue (Thing t, int num=-1)
bool TryGetGift ()
bool IsValidArtifact (string id)
virtual void OnBecomeBranchFaith ()
void JoinFaith (Chara c, ConvertType type=ConvertType.Default)
void LeaveFaith (Chara c, Religion newFaith, ConvertType type)
void Punish (Chara c)
void PunishTakeOver (Chara c)
virtual void OnJoinFaith ()
virtual void OnLeaveFaith ()
void OnChangeHour ()
Static Public Member Functions
static Thing Reforge (string id, Point pos=null, bool first=true)
Static Public Member Functions inherited from EClass
static int rnd (int a)
static int curve (int a, int start, int step, int rate=75)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Public Attributes
int relation
int giftRank
int mood
SourceReligion.Row _source
Static Public Attributes
static Religion recentWrath
Static Public Attributes inherited from EClass
static Core core
Properties
virtual string id [get]
virtual bool IsAvailable [get]
string Name [get]
SourceReligion.Row source [get]
string NameShort [get]
string NameDomain [get]
string TextType [get]
string TextGodGender [get]
string TextMood [get]
bool IsEyth [get]
bool IsEhekatl [get]
bool IsOpatos [get]
virtual bool IsMinorGod [get]
virtual bool CanJoin [get]
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Detailed Description
Definition at line 5 of file Religion.cs.
Member Enumeration Documentation
ConvertType
enum Religion.ConvertType
Enumerator
Default
Campaign
Definition at line 7 of file Religion.cs.
    {
        Default,
        Campaign
    }
Member Function Documentation
GetFeat()
virtual SourceElement.Row Religion.GetFeat (int i) inline virtual
Definition at line 54 of file Religion.cs.
    {
        return EClass.sources.elements.alias["featGod_" + id + i];
    }
References SourceManager.elements, and EClass.sources.
GetGodTalk()
string Religion.GetGodTalk (string suffix) inline
Definition at line 162 of file Religion.cs.
    {
        return EClass.sources.dataGodTalk.GetText(id, suffix).Split(Environment.NewLine.ToCharArray()).RandomItem();
    }
References SourceManager.dataGodTalk, ExcelData.GetText(), and EClass.sources.
Referenced by DramaActor.ConvertAdv(), and Talk().
GetOfferingMtp()
virtual int Religion.GetOfferingMtp (Thing t) inline virtual
Reimplemented in ReligionMoonShadow, and ReligionTrickery.
Definition at line 167 of file Religion.cs.
    {
        return 0;
    }
Referenced by GetOfferingValue().
GetOfferingValue()
int Religion.GetOfferingValue (Thing t, int num = -1) inline
Definition at line 172 of file Religion.cs.
    {
        t.CheckJustCooked();
        if (num == -1)
        {
            num = t.Num;
        }
        int v = 0;
        if (t.source._origin == "meat")
        {
            v = Mathf.Clamp(t.SelfWeight / 10, 1, 1000);
            if (t.refCard == null)
            {
                v /= 10;
            }
        }
        else if (GetOfferingMtp(t) > 0)
        {
            SetValue(t.category, GetOfferingMtp(t));
        }
        else
        {
            string[] cat_offer = source.cat_offer;
            foreach (string key in cat_offer)
            {
                if (t.category.IsChildOf(key))
                {
                    SetValue(EClass.sources.categories.map[key], 1);
                    break;
                }
            }
        }
        if (v == 0)
        {
            return 0;
        }
        if (t.IsDecayed)
        {
            v /= 10;
        }
        v = v * (100 + Mathf.Min(t.LV * 2, 100) + (t.HasElement(757) ? 50 : 0)) / 100;
        v = Mathf.Max(v, 1) * num;
        return v;
        void SetValue(SourceCategory.Row cat, int mtp)
        {
            v = Mathf.Clamp(t.SelfWeight / 10, 50, 1000);
            v *= cat.offer * mtp / 100;
        }
    }
References SourceManager.categories, Card.category, Card.CheckJustCooked(), GetOfferingMtp(), Card.HasElement(), Card.IsDecayed, Card.LV, Card.Num, Card.refCard, Thing.SelfWeight, source, Thing.source, and EClass.sources.
Referenced by TraitAltar._OnOffer(), TraitAltar.CanOffer(), and TraitAltar.OnOffer().
GetSprite()
Sprite Religion.GetSprite () inline
Definition at line 72 of file Religion.cs.
    {
        return ResourceCache.Load<Sprite>("Media/Graphics/Image/Faction/" + source.id) ?? ResourceCache.Load<Sprite>("Media/Graphics/Image/Faction/eyth");
    }
References source.
Referenced by UIHomeInfo.RefreshInfo(), Portrait.SetChara(), and UIFactionInfo.SetReligion().
GetTextBenefit()
string Religion.GetTextBenefit () inline
Definition at line 93 of file Religion.cs.
    {
        string text = "";
        for (int i = 0; i < source.elements.Length; i += 2)
        {
            if (i != 0)
            {
                text = text + Lang.words.comma + Lang.space;
            }
            text += EClass.sources.elements.map[source.elements[i]].GetName();
        }
        return source.GetText("textBenefit") + (IsEyth ? "" : "textBenefit".lang(text));
    }
References SourceManager.elements, IsEyth, source, EClass.sources, and Lang.space.
Referenced by DramaActor.ConvertAdv().
GetTextTemper()
string Religion.GetTextTemper (int _temper = -99999) inline
Definition at line 107 of file Religion.cs.
    {
        if (IsEyth)
        {
            return "-";
        }
        if (_temper == -99999)
        {
            _temper = mood;
        }
        string[] list = Lang.GetList("temper");
        if (_temper <= -85)
        {
            return list[0].ToTitleCase().TagColor(FontColor.Bad);
        }
        if (_temper <= -45)
        {
            return list[1].ToTitleCase().TagColor(FontColor.Bad);
        }
        if (_temper <= -15)
        {
            return list[2].ToTitleCase();
        }
        if (_temper < 15)
        {
            return list[3].ToTitleCase();
        }
        if (_temper < 45)
        {
            return list[4].ToTitleCase();
        }
        if (_temper < 85)
        {
            return list[5].ToTitleCase().TagColor(FontColor.Great);
        }
        return list[6].ToTitleCase().TagColor(FontColor.Good);
    }
References Lang.GetList(), IsEyth, and mood.
Referenced by UIHomeInfo.RefreshInfo().
Init()
void Religion.Init () inline
Definition at line 59 of file Religion.cs.
    {
        relation = source.relation;
    }
References relation, and source.
IsValidArtifact()
bool Religion.IsValidArtifact (string id) inline
Definition at line 255 of file Religion.cs.
    {
        if (giftRank < 2)
        {
            return false;
        }
        return id switch
        {
            "gun_mani" => this == EClass.game.religions.Machine,
            "cloak_mani" => this == EClass.game.religions.Machine,
            "scythe_kumi" => this == EClass.game.religions.Harvest,
            "blunt_earth" => this == EClass.game.religions.Earth,
            "luckydagger" => this == EClass.game.religions.Luck,
            "staff_element" => this == EClass.game.religions.Element,
            "windbow" => this == EClass.game.religions.Wind,
            "shirt_wind" => this == EClass.game.religions.Wind,
            "pole_holy" => this == EClass.game.religions.Healing,
            "sword_muramasa2" => this == EClass.game.religions.MoonShadow,
            "kogitsunemaru" => this == EClass.game.religions.Trickery,
            "warmonger" => this == EClass.game.religions.Strife,
            _ => false,
        };
    }
References ReligionManager.Earth, ReligionManager.Element, EClass.game, giftRank, ReligionManager.Harvest, ReligionManager.Healing, ReligionManager.Luck, ReligionManager.Machine, ReligionManager.MoonShadow, Game.religions, ReligionManager.Strife, ReligionManager.Trickery, and ReligionManager.Wind.
JoinFaith()
void Religion.JoinFaith (Chara c, ConvertType type = ConvertType::Default) inline
Definition at line 386 of file Religion.cs.
    {
        if (!c.IsPC)
        {
            c.faith = this;
            c.RefreshFaithElement();
            EClass.Sound.Play("worship");
            Msg.Say("changeFaith", c, Name);
            return;
        }
        if (c.faith != this)
        {
            c.faith.LeaveFaith(c, this, type);
        }
        if (type != ConvertType.Campaign)
        {
            EClass.pc.c_daysWithGod = 0;
        }
        Msg.Say("worship", Name);
        Talk("worship", c);
        EClass.Sound.Play("worship");
        c.PlayEffect("aura_heaven");
        c.faith = this;
        OnJoinFaith();
        if (IsEyth)
        {
            mood = 0;
        }
        else
        {
            mood = 50;
        }
        c.RefreshFaithElement();
        if (!c.HasElement(306))
        {
            c.elements.Learn(306);
        }
        if (c.IsPC)
        {
            EClass.pc.faction.charaElements.OnJoinFaith();
        }
    }
References Faction.charaElements, Card.elements, Chara.faction, Chara.faith, Card.HasElement(), IsEyth, Chara.IsPC, ElementContainer.Learn(), LeaveFaith(), mood, Name, ElementContainerFaction.OnJoinFaith(), OnJoinFaith(), EClass.pc, Card.PlayEffect(), Chara.RefreshFaithElement(), Msg.Say(), EClass.Sound, and Talk().
Referenced by DramaOutcome.convert_Jure(), and DramaManager.ParseLine().
LeaveFaith()
void Religion.LeaveFaith (Chara c, Religion newFaith, ConvertType type) inline
Definition at line 429 of file Religion.cs.
    {
        if (IsEyth)
        {
            return;
        }
        bool flag = (newFaith == EClass.game.religions.Trickery && this == EClass.game.religions.MoonShadow) || (newFaith == EClass.game.religions.MoonShadow && this == EClass.game.religions.Trickery);
        if (c.IsPC)
        {
            Msg.Say("worship2");
            if (!flag && type != ConvertType.Campaign)
            {
                Punish(c);
            }
        }
        if (flag)
        {
            Talk("regards");
            c.elements.SetBase(85, c.Evalue(85) / 2);
        }
        else
        {
            c.elements.SetBase(85, 0);
        }
        if (c.IsPC)
        {
            EClass.pc.faction.charaElements.OnLeaveFaith();
        }
        OnLeaveFaith();
        c.RefreshFaithElement();
    }
References Faction.charaElements, Card.elements, Card.Evalue(), Chara.faction, EClass.game, IsEyth, Chara.IsPC, ReligionManager.MoonShadow, ElementContainerFaction.OnLeaveFaith(), OnLeaveFaith(), EClass.pc, Punish, Chara.RefreshFaithElement(), Game.religions, Msg.Say(), ElementContainer.SetBase(), Talk(), and ReligionManager.Trickery.
Referenced by JoinFaith().
OnAdvanceDay()
void Religion.OnAdvanceDay () inline
Definition at line 68 of file Religion.cs.
    {
    }
OnBecomeBranchFaith()
virtual void Religion.OnBecomeBranchFaith () inline virtual
Reimplemented in ReligionEarth, ReligionHealing, and ReligionLuck.
Definition at line 382 of file Religion.cs.
    {
    }
OnChangeHour()
void Religion.OnChangeHour () inline
Definition at line 537 of file Religion.cs.
    {
        if (IsEyth)
        {
            mood = 0;
        }
        else
        {
            mood = EClass.rnd(200) - 100;
        }
    }
References IsEyth, mood, and EClass.rnd().
Referenced by Player.OnAdvanceHour().
OnJoinFaith()
virtual void Religion.OnJoinFaith () inline virtual
Definition at line 529 of file Religion.cs.
    {
    }
Referenced by JoinFaith().
OnLeaveFaith()
virtual void Religion.OnLeaveFaith () inline virtual
Definition at line 533 of file Religion.cs.
    {
    }
Referenced by LeaveFaith().
OnLoad()
void Religion.OnLoad () inline
Definition at line 64 of file Religion.cs.
    {
    }
Referenced by ReligionManager.OnLoad().
Punish()
void Religion.Punish (Chara c) inline
Definition at line 461 of file Religion.cs.
    {
        Talk("wrath");
        if (c.Evalue(1228) > 0)
        {
            c.SayNothingHappans();
            return;
        }
        c.hp = 1;
        c.mana.value = 1;
        c.stamina.value = 1;
        if (c.HasCondition<ConWrath>())
        {
            recentWrath = this;
            c.DamageHP(999999, AttackSource.Wrath);
            recentWrath = null;
            return;
        }
        Thing thing = ThingGen.Create("punish_ball");
        int num = 0;
        foreach (Religion item in EClass.game.religions.list)
        {
            if (item.giftRank > 0)
            {
                num++;
            }
        }
        if (num >= 4)
        {
            thing.idSkin = 1;
        }
        thing.ChangeWeight(EClass.pc.WeightLimit / 4 + 1000);
        c.AddThing(thing);
        c.AddCondition<ConWrath>(2000 + (c.IsPC ? (EClass.pc.c_daysWithGod * 20) : 0));
    }
References Card.ChangeWeight(), ThingGen.Create(), Card.DamageHP(), Card.Evalue(), EClass.game, Chara.HasCondition(), item, ReligionManager.list, EClass.pc, recentWrath, Game.religions, Card.SayNothingHappans(), Talk(), and Chara.WeightLimit.
PunishTakeOver()
void Religion.PunishTakeOver (Chara c) inline
Definition at line 497 of file Religion.cs.
    {
        Talk("takeoverFail");
        if (c.Evalue(1228) > 0)
        {
            c.SayNothingHappans();
            return;
        }
        c.hp /= 2;
        if (c.mana.value > 0)
        {
            c.mana.value = c.mana.value / 2;
        }
        if (c.stamina.value > 0)
        {
            c.stamina.value = c.stamina.value / 2;
        }
        if (c.HasCondition<ConWrath>())
        {
            recentWrath = this;
            c.DamageHP(999999, AttackSource.Wrath);
            recentWrath = null;
            return;
        }
        Thing thing = ThingGen.Create("punish_ball");
        thing.c_weight = EClass.pc.WeightLimit / 4 + 1000;
        thing.isWeightChanged = true;
        thing.SetDirtyWeight();
        c.AddThing(thing);
        c.AddCondition<ConWrath>(200);
    }
References Chara.AddCondition(), Card.AddThing(), ThingGen.Create(), Card.DamageHP(), Card.Evalue(), Chara.HasCondition(), Chara.mana, recentWrath, Card.SayNothingHappans(), Card.SetDirtyWeight(), Chara.stamina, Talk(), and Stats.value.
Referenced by TraitAltar.OnOffer().
Reforge()
static Thing Religion.Reforge (string id, Point pos = null, bool first = true) inline static
Definition at line 279 of file Religion.cs.
    {
        if (pos == null)
        {
            pos = EClass.pc.pos.Copy();
        }
        pos.Set(pos.GetNearestPoint(allowBlock: false, allowChara: false, allowInstalled: false, ignoreCenter: true) ?? pos);
        Thing thing = ThingGen.Create(id);
        foreach (Element value in thing.elements.dict.Values)
        {
            if (value.id == 66 || value.id == 67 || value.id == 64 || value.id == 65 || value.id == 92)
            {
                continue;
            }
            switch (id)
            {
            case "gun_mani":
                thing.c_idDeity = EClass.game.religions.Machine.id;
                break;
            case "cloak_mani":
                if (value.id == 427 || value.id == 957 || value.id == 105 || value.id == 466 || value.id == 664)
                {
                    value.vExp = -1;
                }
                thing.c_idDeity = EClass.game.religions.Machine.id;
                break;
            case "scythe_kumi":
                if (value.id == 6650 || value.id == 480 || value.id == 959 || value.id == 428 || value.id == 640 || value.id == 665)
                {
                    value.vExp = -1;
                }
                thing.c_idDeity = EClass.game.religions.Harvest.id;
                break;
            case "blunt_earth":
                if (value.id == 70 || value.id == 55 || value.id == 56 || value.id == 954 || value.id == 423 || value.id == 421)
                {
                    value.vExp = -1;
                }
                thing.c_idDeity = EClass.game.religions.Earth.id;
                break;
            case "luckydagger":
                if (value.id != 426)
                {
                    value.vExp = -1;
                }
                thing.c_idDeity = EClass.game.religions.Luck.id;
                break;
            case "staff_element":
                if (value.id == 411 || (value is Resistance && value.id != 959))
                {
                    value.vExp = -1;
                }
                thing.c_idDeity = EClass.game.religions.Element.id;
                break;
            case "windbow":
                thing.c_idDeity = EClass.game.religions.Wind.id;
                break;
            case "shirt_wind":
                if (!(value is Resistance) && value.id != 226 && value.id != 152 && value.id != 77)
                {
                    value.vExp = -1;
                }
                thing.c_idDeity = EClass.game.religions.Wind.id;
                break;
            case "pole_holy":
                if (value.id == 60 || value.id == 461 || value.id == 423)
                {
                    value.vExp = -1;
                }
                thing.c_idDeity = EClass.game.religions.Healing.id;
                break;
            case "sword_muramasa2":
                if (value.id == 401 || value.id == 916 || value.id == 661)
                {
                    value.vExp = -1;
                }
                thing.c_idDeity = EClass.game.religions.MoonShadow.id;
                break;
            case "kogitsunemaru":
                if (value.id != 656)
                {
                    value.vExp = -1;
                }
                thing.c_idDeity = EClass.game.religions.Trickery.id;
                break;
            case "warmonger":
                if (value.id == 468 || value.id == 423 || value.id == 463 || value.id == 460 || value.id == 464 || value.id == 465)
                {
                    value.vExp = -1;
                }
                thing.c_idDeity = EClass.game.religions.Strife.id;
                break;
            }
        }
        EClass._zone.AddCard(thing, pos);
        pos.PlayEffect("aura_heaven");
        if (first)
        {
            pos.PlaySound("godbless");
        }
        return thing;
    }
References EClass._zone, Zone.AddCard(), Point.Copy(), ThingGen.Create(), ReligionManager.Earth, ReligionManager.Element, EClass.game, ReligionManager.Harvest, ReligionManager.Healing, Element.id, ReligionEarth.id, ReligionElement.id, ReligionHarvest.id, ReligionHealing.id, ReligionLuck.id, ReligionMachine.id, ReligionMoonShadow.id, ReligionStrife.id, ReligionTrickery.id, ReligionWind.id, ReligionManager.Luck, ReligionManager.Machine, ReligionManager.MoonShadow, EClass.pc, Card.PlayEffect(), Card.pos, Game.religions, Point.Set(), ReligionManager.Strife, ReligionManager.Trickery, and ReligionManager.Wind.
Referenced by TraitAltar.OnOffer(), and TryGetGift().
Revelation()
void Religion.Revelation (string idTalk, int chance = 100) inline
Definition at line 145 of file Religion.cs.
    {
        if (!IsEyth && EClass.rnd(100) <= chance)
        {
            Talk(idTalk, EClass.pc);
        }
    }
References IsEyth, EClass.pc, EClass.rnd(), and Talk().
Referenced by Chara.Die(), Scene.Init(), ActPray.Pray(), and LayerSleep.Sleep().
SetTextRelation()
void Religion.SetTextRelation (UIText text) inline
Definition at line 77 of file Religion.cs.
    {
        if (relation > 100)
        {
            text.SetText("reFriend".lang(), FontColor.Good);
        }
        else if (relation < -100)
        {
            text.SetText("reEnemy".lang(), FontColor.Bad);
        }
        else
        {
            text.SetText("reNone".lang(), FontColor.Passive);
        }
    }
References relation, and UIText.SetText().
Referenced by ContentFaction.RefreshFactions().
Talk()
void Religion.Talk (string idTalk, Card c = null, Card agent = null) inline
Definition at line 153 of file Religion.cs.
    {
        if (!IsEyth)
        {
            Msg.SetColor(Msg.colors.TalkGod);
            Msg.Say("<i>" + GetGodTalk(idTalk) + " </i>", c ?? EClass.pc);
        }
    }
References Msg.colors, GetGodTalk(), IsEyth, EClass.pc, Msg.Say(), Msg.SetColor(), and MsgColors.TalkGod.
Referenced by TraitAltar._OnOffer(), TraitGodStatue._OnUse(), JoinFaith(), LeaveFaith(), ActEffect.Proc(), Punish(), PunishTakeOver(), Revelation(), TraitAltar.TakeOver(), CoreDebug.Test_GodTalk(), and TryGetGift().
TryGetGift()
bool Religion.TryGetGift () inline
Definition at line 222 of file Religion.cs.
    {
        if (IsEyth || source.rewards.Length == 0)
        {
            return false;
        }
        Point point = EClass.pc.pos.GetNearestPoint(allowBlock: false, allowChara: false, allowInstalled: false) ?? EClass.pc.pos;
        int num = EClass.pc.Evalue(85);
        if (giftRank == 0 && (num >= 15 || EClass.debug.enable))
        {
            Talk("pet");
            Chara chara = CharaGen.Create(source.rewards[0]);
            EClass._zone.AddCard(chara, point);
            chara.MakeAlly();
            chara.PlayEffect("aura_heaven");
            giftRank = 1;
            return true;
        }
        if (source.rewards.Length >= 2 && giftRank == 1 && (num >= 30 || EClass.debug.enable))
        {
            Talk("gift");
            string[] array = source.rewards[1].Split('|');
            string[] array2 = array;
            foreach (string text in array2)
            {
                Reforge(text, point, text == array[0]);
            }
            giftRank = 2;
            return true;
        }
        return false;
    }
References EClass._zone, Zone.AddCard(), CharaGen.Create(), EClass.debug, CoreDebug.enable, Card.Evalue(), Point.GetNearestPoint(), giftRank, IsEyth, Chara.MakeAlly(), EClass.pc, Card.PlayEffect(), Card.pos, Reforge(), source, and Talk().
Member Data Documentation
_source
SourceReligion.Row Religion._source
Definition at line 24 of file Religion.cs.
giftRank
int Religion.giftRank
Definition at line 17 of file Religion.cs.
Referenced by IsValidArtifact(), and TryGetGift().
mood
int Religion.mood
Definition at line 20 of file Religion.cs.
Referenced by GetTextTemper(), JoinFaith(), and OnChangeHour().
recentWrath
Religion Religion.recentWrath static
Definition at line 22 of file Religion.cs.
Referenced by Card.DamageHP(), Chara.Die(), Punish(), and PunishTakeOver().
relation
int Religion.relation
Definition at line 14 of file Religion.cs.
Referenced by Init(), UIFactionInfo.SetReligion(), and SetTextRelation().
Property Documentation
CanJoin
virtual bool Religion.CanJoin get
Definition at line 52 of file Religion.cs.
Referenced by ReligionManager.GetRandomReligion(), and TraitAltar.TrySetAct().
id
virtual string Religion.id get
Definition at line 26 of file Religion.cs.
Referenced by TraitGodStatue._OnUse(), TraitAltar.CanOffer(), ReligionManager.Find(), AI_Pray.GetAltar(), TraitGodStatue.OnChangeMaterial(), TraitAltar.OnCreate(), TraitAltar.OnImportMap(), TraitAltar.OnOffer(), FactionBranch.OnSimulateDay(), Person.Person(), ContentFaction.RefreshFactions(), UIFactionInfo.SetReligion(), TraitAltar.TakeOver(), and Element.BonusInfo.WriteNote().
IsAvailable
virtual bool Religion.IsAvailable get
Definition at line 28 of file Religion.cs.
Referenced by LayerFaith.AddReligion().
IsEhekatl
bool Religion.IsEhekatl get
Definition at line 46 of file Religion.cs.
IsEyth
bool Religion.IsEyth get
Definition at line 44 of file Religion.cs.
Referenced by AI_Pray.GetAltar(), GetTextBenefit(), GetTextTemper(), JoinFaith(), LeaveFaith(), OnChangeHour(), FactionBranch.OnSimulateDay(), Revelation(), Talk(), TryGetGift(), and ActPray.TryPray().
IsMinorGod
virtual bool Religion.IsMinorGod get
Definition at line 50 of file Religion.cs.
Referenced by ReligionManager.GetRandomReligion(), and ContentFaction.RefreshFactions().
IsOpatos
bool Religion.IsOpatos get
Definition at line 48 of file Religion.cs.
Name
string Religion.Name get
Definition at line 30 of file Religion.cs.
Referenced by LayerFaith.AddReligion(), DramaActor.ConvertAdv(), GameLang.ConvertDrama(), Chara.GetName(), JoinFaith(), TraitAltar.OnOffer(), Person.Person(), ActPray.Pray(), AI_Pray.Pray(), ContentPopulation.Refresh(), ContentFaction.RefreshFactions(), ContentHomeReport.RefreshInfo(), UIHomeInfo.RefreshInfo(), WindowChara.RefreshInfo(), WindowChara.RefreshNote(), UIFactionInfo.SetReligion(), and ActPray.TryPray().
NameDomain
string Religion.NameDomain get
Definition at line 36 of file Religion.cs.
NameShort
string Religion.NameShort get
Definition at line 34 of file Religion.cs.
Referenced by Chara.Die().
source
SourceReligion.Row Religion.source get
Definition at line 32 of file Religion.cs.
Referenced by LayerFaith.AddReligion(), DramaActor.ConvertAdv(), GetOfferingValue(), FactionBranch.GetResidentTax(), GetSprite(), GetTextBenefit(), Init(), TraitAltar.SetDeity(), UIFactionInfo.SetReligion(), and TryGetGift().
TextGodGender
string Religion.TextGodGender get
Definition at line 40 of file Religion.cs.
Referenced by TraitAltar._OnOffer(), and TraitAltar.OnOffer().
TextMood
string Religion.TextMood get
Definition at line 42 of file Religion.cs.
Referenced by WidgetStatsBar.Build().
TextType
string Religion.TextType get
Definition at line 38 of file Religion.cs.
Referenced by ContentFaction.RefreshFactions().
The documentation for this class was generated from the following file:
Elin/Religion.cs