Elin Decompiled Documentation: PopupManager Class Reference
PopupManager Class Reference
Classes
class Item
Public Member Functions
void Add (string id)
void Add (Item item)
void Remove (int index)
Public Attributes
List< Item > items = new List<Item>()
Properties
WidgetPopup Instance [get]
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Additional Inherited Members
Static Public Member Functions inherited from EClass
static int rndSeed (int a, int seed)
static int rnd (long a)
static int rnd (int a)
static int curve (int a, int start, int step, int rate=75)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Static Public Attributes inherited from EClass
static Core core
Detailed Description
Definition at line 5 of file PopupManager.cs.
Member Function Documentation
Add() [1/2]
void PopupManager.Add (Item item) inline
Definition at line 27 of file PopupManager.cs.
    {
        items.Add(item);
        if (!EClass.debug.ignorePopup)
        {
            if (!Instance)
            {
                EClass.ui.widgets.ActivateWidget("Popup");
            }
            else
            {
                Instance.OnAddItem(item);
            }
            EClass.Sound.Play("popup_add");
        }
    }
References EClass.debug, CoreDebug.ignorePopup, Instance, item, items, WidgetPopup.OnAddItem(), EClass.Sound, and EClass.ui.
Add() [2/2]
void PopupManager.Add (string id) inline
Definition at line 18 of file PopupManager.cs.
    {
        string text = GameLang.Convert(Resources.Load<TextAsset>(CorePath.Text_Popup + id).text);
        Add(new Item
        {
            text = text
        });
    }
References Add(), GameLang.Convert(), and CorePath.Text_Popup.
Referenced by Add(), and WidgetPopup.OnActivate().
Remove()
void PopupManager.Remove (int index) inline
Definition at line 44 of file PopupManager.cs.
    {
    }
Member Data Documentation
items
List<Item> PopupManager.items = new List<Item>()
Definition at line 14 of file PopupManager.cs.
Referenced by Add().
Property Documentation
Instance
WidgetPopup PopupManager.Instance get
Definition at line 16 of file PopupManager.cs.
Referenced by Add().
The documentation for this class was generated from the following file:
Elin/PopupManager.cs