Elin Decompiled Documentation: ZoneEventSubdue Class Reference
ZoneEventSubdue Class Reference
Public Member Functions
override void OnVisit ()
override void OnCharaDie (Chara c)
override void _OnTickRound ()
void CheckClear ()
Public Member Functions inherited from ZoneEventQuest
void Spawn (int num=1)
void SpawnBoss (bool evolve=false)
void AggroEnemy (int chance=100)
sealed override void OnTickRound ()
virtual void _OnTickRound ()
virtual ZoneInstance.Status OnReachTimeLimit ()
Public Member Functions inherited from ZoneEvent
virtual string GetText ()
void Tick (float delta)
void Init ()
void OnSimulateHour ()
virtual void OnVisit ()
virtual void OnInit ()
virtual void OnFirstTick ()
virtual void OnTick ()
virtual void OnTickRound ()
virtual void OnKill ()
virtual void OnCharaDie (Chara c)
virtual void OnLeaveZone ()
void OnLoad (Zone _zone)
void Kill ()
Public Attributes
int max
Public Attributes inherited from ZoneEventQuest
int uidQuest
List< int > enemies = new List<int>()
Public Attributes inherited from ZoneEvent
float time
int rounds
int hoursElapsed
int minElapsed
Zone zone
bool firstTick = true
Properties
override bool CountEnemy [get]
override bool WarnBoss [get]
Properties inherited from ZoneEventQuest
Quest quest [get]
virtual bool WarnBoss [get]
virtual bool CountEnemy [get]
virtual int TimeLimit [get]
Properties inherited from ZoneEvent
SourceQuest.Row source [get]
virtual string id [get]
virtual string TextWidgetDate [get]
virtual float roundInterval [get]
virtual Playlist playlist [get]
virtual bool debugSkip [get]
virtual string RefStr2 [get]
virtual string RefStr3 [get]
virtual int hoursToKill [get]
virtual bool HasReport [get]
string Name [get]
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Additional Inherited Members
Static Public Member Functions inherited from EClass
static int rndSeed (int a, int seed)
static int rnd (int a)
static int curve (int a, int start, int step, int rate=75)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Static Public Attributes inherited from EClass
static Core core
Detailed Description
Definition at line 4 of file ZoneEventSubdue.cs.
Member Function Documentation
_OnTickRound()
override void ZoneEventSubdue._OnTickRound () inline virtual
Reimplemented from ZoneEventQuest.
Definition at line 30 of file ZoneEventSubdue.cs.
    {
        AggroEnemy();
        CheckClear();
    }
References ZoneEventQuest.AggroEnemy(), and CheckClear().
CheckClear()
void ZoneEventSubdue.CheckClear () inline
Definition at line 36 of file ZoneEventSubdue.cs.
    {
        if (EClass._zone.instance.status == ZoneInstance.Status.Success || EClass._zone.instance.status == ZoneInstance.Status.Fail)
        {
            return;
        }
        enemies.ForeachReverse(delegate(int id)
        {
            Chara chara = EClass._map.FindChara(id);
            if (chara == null || !chara.IsAliveInCurrentZone || !EClass.pc.IsHostile(chara))
            {
                enemies.Remove(id);
            }
        });
        if (enemies.Count == 0)
        {
            EClass._zone.instance.status = ZoneInstance.Status.Success;
            Msg.Say("subdue_complete");
            EClass._zone.SetBGM();
            SE.Play("Jingle/fanfare");
        }
    }
References EClass._map, EClass._zone, ZoneEventQuest.enemies, Map.FindChara(), Zone.instance, Chara.IsAliveInCurrentZone, Chara.IsHostile(), EClass.pc, Msg.Say(), Zone.SetBGM(), and ZoneInstance.status.
Referenced by _OnTickRound(), and OnCharaDie().
OnCharaDie()
override void ZoneEventSubdue.OnCharaDie (Chara c) inline virtual
Reimplemented from ZoneEvent.
Definition at line 25 of file ZoneEventSubdue.cs.
    {
        CheckClear();
    }
References CheckClear().
OnVisit()
override void ZoneEventSubdue.OnVisit () inline virtual
Reimplemented from ZoneEvent.
Definition at line 13 of file ZoneEventSubdue.cs.
    {
        if (!EClass.game.isLoading)
        {
            EClass._zone._dangerLv = Mathf.Max(base.quest.DangerLv - 2, 1);
            Spawn(4 + base.quest.difficulty * 2 + EClass.rnd(5));
            AggroEnemy(15);
            EClass._zone.SetBGM(102);
            max = enemies.Count;
        }
    }
References EClass._zone, ZoneEventQuest.AggroEnemy(), ZoneEventQuest.enemies, EClass.game, Game.isLoading, max, EClass.rnd(), Zone.SetBGM(), and ZoneEventQuest.Spawn().
Member Data Documentation
max
int ZoneEventSubdue.max
Definition at line 7 of file ZoneEventSubdue.cs.
Referenced by OnVisit().
Property Documentation
CountEnemy
override bool ZoneEventSubdue.CountEnemy get
Definition at line 9 of file ZoneEventSubdue.cs.
WarnBoss
override bool ZoneEventSubdue.WarnBoss get
Definition at line 11 of file ZoneEventSubdue.cs.
The documentation for this class was generated from the following file:
Elin/ZoneEventSubdue.cs