Elin Decompiled Documentation: LayerLoadGame Class Reference
LayerLoadGame Class Reference
Public Member Functions
void Init (bool _backup, string _pathBackup="", string _idDest="")
void RefreshList ()
void RefreshInfo (GameIndex i)
Public Member Functions inherited from ELayer
override void OnBeforeAddLayer ()
void InitInspector ()
sealed override void Init ()
override void OnAfterAddLayer ()
void TryShowHelp ()
void AddLayerToUI (string id)
void TryShowHint (string _langHint=null)
void TalkHomeMemeber (string id)
void TalkMaid (string id)
override void OnRightClick ()
Public Member Functions inherited from Layer
virtual string GetTextHeader (Window window)
virtual bool HeaderIsListOf (int id)
virtual void Init ()
virtual void OnInit ()
virtual void OnAfterInit ()
virtual void ApplySkin ()
void ShowScreenLock (string id)
void UpdateInput ()
virtual void OnUpdateInput ()
virtual void OnRightClick ()
virtual bool OnBack ()
virtual void OnChangeLayer ()
virtual void OnCreate ()
void _AddLayer (string id)
Layer AddLayer (string id)
T AddLayer< T > ()
T AddLayer< T > (string id)
T AddLayerDontCloseOthers< T > ()
Layer AddLayerDontCloseOthers (Layer l)
T GetOrAddLayer< T > ()
virtual void OnBeforeAddLayer ()
virtual void OnAfterAddLayer ()
Layer AddLayer (Layer l)
void ToggleLayer (string id)
T ToggleLayer< T > (string id=null)
void WaitAndClose ()
void OnClickClose ()
virtual void Close ()
void CloseLayers ()
void RemoveLayers (bool removeImportant=false)
bool RemoveLayer< T > ()
void RemoveLayer (Layer l)
virtual void OnKill ()
Layer SetOnKill (Action action)
void DisableClose ()
void Delay (float duration=0.05f)
Layer SetDelay (float d)
Layer GetLayer (string id)
T GetLayer< T > (bool fromTop=false)
Layer GetTopLayer ()
void SwitchContent (int idWindow, int i)
virtual void OnSwitchContent (Window window)
Layer SetTitles (string langList, string idHeaderRow=null)
bool IsBlockWidgetClick ()
bool IsHideHud ()
bool IsAllowGeneralInput ()
bool IsUseBlur ()
bool IsPointerOnLayer ()
void ApplySkin ()
Public Attributes
UIList list
GameObject goInfo
GameObject goNoInfo
GameObject goCloudWarn
UINote note
UIButton buttonLoad
UIButton buttonDelete
UIButton buttonBackup
UIButton buttonOpen
UIButton buttonListBackup
UIButton buttonMove
List< GameIndex > worlds
Portrait portrait
UIText textAka
UIText textName
UIText textInfo
UIText textRace
UIText textJob
UIText textDeepest
UIText textDays
Public Attributes inherited from Layer
Option option
UnityEvent onKill
Anime animeIn
Anime animeOut
bool closeOthers
bool defaultActionMode = true
Button screenLock
Layer parent
string idLayer
List< Layer > layers = new List<Layer>()
Vector2 lastParentPos
List< Window > windows = new List<Window>()
string langHint
Properties
bool cloud [get]
Properties inherited from ELayer
static Core core [get]
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static FactionBranch Branch [get]
static Faction Home [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static CoreConfig config [get]
static GameSetting setting [get]
static ColorProfile Colors [get]
static SourceManager sources [get]
static World world [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
bool IsFloat [get]
virtual string IdHelp [get]
Properties inherited from Layer
Layer TopLayer [get]
string uid [get]
virtual RectTransform rectLayers [get]
virtual bool blockWidgetClick [get]
Private Attributes
string pathRoot
string idDest
string pathBackup
bool backup
Additional Inherited Members
Static Public Member Functions inherited from ELayer
static int rnd (int a)
Static Public Member Functions inherited from Layer
static T Create< T > ()
static T Create< T > (string path)
static Layer Create (string path)
Static Public Attributes inherited from Layer
static int skipInput
static bool closeOnRightClick
static bool rightClicked
static bool cancelKeyDown
static bool ignoreSounds
static Transform blurStopInstance
static string[] searchPath = new string[3] { "Layer", "Layer/Dialog", "Layer/LayerHome" }
Protected Member Functions inherited from ELayer
sealed override void _Close ()
sealed override void Kill ()
Protected Member Functions inherited from Layer
virtual void Awake ()
virtual void _Close ()
virtual void Kill ()
Protected Attributes inherited from Layer
RectTransform _rect
bool isDestroyed
Detailed Description
Definition at line 7 of file LayerLoadGame.cs.
Member Function Documentation
Init()
void LayerLoadGame.Init (bool _backup, string _pathBackup = "", string _idDest = "") inline
Definition at line 59 of file LayerLoadGame.cs.
    {
        backup = _backup;
        pathBackup = _pathBackup;
        idDest = _idDest;
        if (backup)
        {
            for (int i = 0; i < 2; i++)
            {
                Vector2 anchoredPosition = windows[i].Rect().anchoredPosition;
                windows[i].Rect().anchoredPosition = new Vector2(anchoredPosition.x + 40f, anchoredPosition.y - 30f);
            }
        }
        if (!backup && Application.isEditor)
        {
            FileInfo[] files = new DirectoryInfo("D:\\Download").GetFiles();
            foreach (FileInfo fileInfo in files)
            {
                if (fileInfo.Name.StartsWith("world") && fileInfo.Name.EndsWith(".zip"))
                {
                    string fileNameWithoutExtension = Path.GetFileNameWithoutExtension(fileInfo.Name);
                    string path = CorePath.RootSave + fileNameWithoutExtension;
                    if (!Directory.Exists(path))
                    {
                        Directory.CreateDirectory(path);
                        new StreamWriter(new MemoryStream());
                        ReadOptions options = new ReadOptions();
                        ZipFile.Read(fileInfo.FullName, options).ExtractAll(path);
                    }
                }
            }
        }
        RefreshList();
        if (!backup)
        {
            windows[0].ClearBottomButtons();
            windows[0].AddBottomButton("toggleCloud", delegate
            {
                ELayer.core.config.cloud = !ELayer.core.config.cloud;
                SE.Tab();
                RefreshList();
            });
        }
    }
References backup, CoreConfig.cloud, Core.config, ELayer.core, idDest, pathBackup, RefreshList(), and Layer.windows.
RefreshInfo()
void LayerLoadGame.RefreshInfo (GameIndex i) inline
Definition at line 145 of file LayerLoadGame.cs.
    {
        goInfo.SetActive(value: true);
        goNoInfo.SetActive(value: false);
        note.Clear();
        note.AddTopic("version".lang(), i.version.GetText());
        note.AddTopic("date_real".lang(), i.RealDate);
        note.AddTopic("date_game".lang(), i.GameData);
        note.AddTopic("ID", i.id);
        bool flag = ELayer.core.version.IsSaveCompatible(i.version);
        if (!flag)
        {
            note.Space();
            note.AddText("incompatible".lang(), FontColor.Bad);
        }
        else
        {
            note.AddTopic("currentZone".lang(), i.zoneName);
        }
        textAka.SetText(i.aka);
        textName.SetText(i.pcName);
        textDays.SetText("infoHire".lang(i.days.ToString() ?? ""));
        textDeepest.SetText("deepestLv2".lang(i.deepest.ToString() ?? ""));
        textRace.SetText(ELayer.sources.races.map.TryGetValue(i.idRace)?.GetName().ToTitleCase() ?? "");
        textJob.SetText(ELayer.sources.jobs.map.TryGetValue(i.idJob)?.GetName().ToTitleCase() ?? "");
        if (!i.idPortrait.IsEmpty())
        {
            portrait.SetActive(enable: true);
            Color color = Color.white;
            ColorUtility.TryParseHtmlString("#" + i.color, out color);
            portrait.SetPortrait(i.idPortrait, color);
        }
        else
        {
            portrait.SetActive(enable: false);
        }
        note.Build();
        buttonListBackup.SetActive(!backup);
        buttonDelete.SetActive(!backup && !ELayer.core.IsGameStarted);
        buttonBackup.SetActive(!backup && (!ELayer.core.IsGameStarted || i.id == Game.id));
        buttonOpen.SetActive(backup);
        buttonMove.SetActive(!backup && !ELayer.core.IsGameStarted);
        buttonMove.mainText.SetText((cloud ? "fromCloud" : "toCloud").lang());
        buttonMove.SetOnClick(delegate
        {
            Dialog.YesNo("dialog_switchCloud", delegate
            {
                string sourceDirName = (cloud ? CorePath.RootSaveCloud : CorePath.RootSave) + i.id;
                string text = (cloud ? CorePath.RootSave : CorePath.RootSaveCloud) + i.id;
                string text2 = (cloud ? CorePath.PathBackupCloud : CorePath.PathBackup) + i.id;
                string text3 = (cloud ? CorePath.PathBackup : CorePath.PathBackupCloud) + i.id;
                bool flag2 = Directory.Exists(text2);
                if (Directory.Exists(text) || Directory.Exists(text3))
                {
                    SE.Beep();
                    ELayer.ui.Say("cloud_conflict");
                }
                else
                {
                    SE.Play("mutation");
                    try
                    {
                        if (flag2)
{
                            Debug.Log("Converting Backup files:");
                            Directory.Move(text2, text3);
                            foreach (GameIndex game in GameIO.GetGameList(((!cloud) ? CorePath.PathBackupCloud : CorePath.PathBackup) + i.id + "/"))
{
                                Debug.Log("Processing:" + game.id + ": " + game.path);
                                if (!cloud)
{
                                    GameIO.PrepareSteamCloud(game.id, game.path);
                                }
                            }
                        }
                        Debug.Log("Converting Current World:");
                        Directory.Move(sourceDirName, text);
                        i.path = text;
                        i.cloud = !cloud;
                        GameIO.UpdateGameIndex(i);
                        if (i.cloud)
{
                            GameIO.PrepareSteamCloud(i.id);
                        }
                    }
                    catch (Exception ex)
                    {
                        ELayer.ui.Say(ex.Message);
                    }
                    RefreshList();
                }
            });
        });
        buttonLoad.onClick.RemoveAllListeners();
        buttonDelete.onClick.RemoveAllListeners();
        buttonLoad.SetOnClick(delegate
        {
            LayerTitle.KillActor();
            if (backup)
            {
                Dialog.YesNo("dialog_restoreWarning", delegate
                {
                    GameIO.DeleteGame(idDest, cloud, deleteBackup: false);
                    IO.CopyDir(pathRoot + "/" + i.id, (cloud ? CorePath.RootSaveCloud : CorePath.RootSave) + "/" + idDest);
                    SE.WriteJournal();
                    Close();
                    Game.TryLoad(idDest, cloud, delegate
                    {
                        Game.Load(idDest, cloud);
                    });
                });
            }
            else
            {
                if (!i.madeBackup && i.version.IsBelow(ELayer.core.version))
                {
                    GameIO.MakeBackup(i);
                    ELayer.ui.Say("backupDone");
                    i.madeBackup = true;
                    GameIO.UpdateGameIndex(i);
                }
                Game.TryLoad(i.id, cloud, delegate
                {
                    Game.Load(i.id, cloud);
                });
            }
        });
        buttonDelete.SetOnClick(delegate
        {
            Dialog.YesNo("dialogDeleteGame", delegate
            {
                GameIO.DeleteGame(i.id, cloud);
                worlds = null;
                RefreshList();
                SE.Trash();
            });
        });
        buttonListBackup.SetOnClick(delegate
        {
            ELayer.ui.AddLayer<LayerLoadGame>().Init(_backup: true, (cloud ? CorePath.PathBackupCloud : CorePath.PathBackup) + i.id + "/", i.id);
        });
        buttonBackup.SetOnClick(delegate
        {
            if (ELayer.core.IsGameStarted)
            {
                ELayer.game.backupTime = 0.0;
                ELayer.game.Save();
            }
            i.cloud = cloud;
            GameIO.MakeBackup(i);
            ELayer.ui.Say("backupDone");
            SE.WriteJournal();
        });
        buttonOpen.SetOnClick(delegate
        {
            Util.ShowExplorer(i.path);
        });
        buttonLoad.SetActive(flag);
    }
References UINote.AddText(), UINote.AddTopic(), GameIndex.aka, backup, UINote.Build(), buttonBackup, buttonDelete, buttonListBackup, buttonMove, buttonOpen, UINote.Clear(), cloud, Color, GameIndex.color, ELayer.core, GameIndex.days, GameIndex.deepest, GameIndex.GameData, Version.GetText(), goInfo, goNoInfo, Game.id, GameIndex.id, GameIndex.idJob, GameIndex.idPortrait, GameIndex.idRace, if(), Core.IsGameStarted, Version.IsSaveCompatible(), SourceManager.jobs, UIButton.mainText, note, CorePath.PathBackup, CorePath.PathBackupCloud, GameIndex.pcName, portrait, SourceManager.races, GameIndex.RealDate, RefreshList(), CorePath.RootSave, CorePath.RootSaveCloud, Portrait.SetPortrait(), UIText.SetText(), ELayer.sources, UINote.Space(), textAka, textDays, textDeepest, textJob, textName, textRace, ELayer.ui, GameIndex.version, BaseCore.version, Dialog.YesNo(), and GameIndex.zoneName.
Referenced by RefreshList().
RefreshList()
void LayerLoadGame.RefreshList () inline
Definition at line 104 of file LayerLoadGame.cs.
    {
        if (!backup)
        {
            windows[0].SetCaption("saveList".lang() + (cloud ? (" " + "isCloud".lang()) : ""));
        }
        pathRoot = (backup ? pathBackup : (cloud ? CorePath.RootSaveCloud : CorePath.RootSave));
        worlds = GameIO.GetGameList(pathRoot, backup);
        goCloudWarn.SetActive(cloud && !backup);
        goInfo.SetActive(value: false);
        goNoInfo.SetActive(value: true);
        list.Clear();
        list.callbacks = new UIList.Callback<GameIndex, UIButton>
        {
            onInstantiate = delegate(GameIndex a, UIButton b)
            {
                FontColor c = (ELayer.core.version.IsSaveCompatible(a.version) ? FontColor.Good : FontColor.Bad);
                string s = a.Title + ((ELayer.core.IsGameStarted && a.id == Game.id) ? "currentSave".lang() : "") + Environment.NewLine;
                b.mainText.SetText(s, c);
                b.subText.SetText(a.RealDate ?? "");
                b.subText2.SetText(((a.difficulty == 2) ? "" : ((a.difficulty == 1) ? "" : "")) + a.pcName + " (" + a.zoneName + ")", c);
                b.GetComponent<UIItem>().text1.SetText(a.version.GetText() + (cloud ? (" " + "isCloud".lang()) : ""));
            },
            onClick = delegate(GameIndex a, UIButton b)
            {
                RefreshInfo(a);
            }
        };
        foreach (GameIndex world in worlds)
        {
            list.Add(world);
        }
        list.Refresh();
        if (list.items.Count == 0)
        {
            buttonLoad.SetActive(enable: false);
            buttonDelete.SetActive(enable: false);
            goNoInfo.SetActive(value: true);
        }
    }
References UIList.Add(), backup, buttonDelete, buttonLoad, UIList.Clear(), cloud, ELayer.core, GameIndex.difficulty, GameIO.GetGameList(), Version.GetText(), goCloudWarn, goInfo, goNoInfo, Game.id, Version.IsSaveCompatible(), UIList.items, list, UIButton.mainText, pathBackup, pathRoot, GameIndex.RealDate, UIList.Refresh(), RefreshInfo(), CorePath.RootSave, UIText.SetText(), UIButton.subText, UIButton.subText2, GameIndex.version, BaseCore.version, Layer.windows, ELayer.world, and worlds.
Referenced by Init(), and RefreshInfo().
Member Data Documentation
backup
bool LayerLoadGame.backup private
Definition at line 55 of file LayerLoadGame.cs.
Referenced by Init(), RefreshInfo(), and RefreshList().
buttonBackup
UIButton LayerLoadGame.buttonBackup
Definition at line 23 of file LayerLoadGame.cs.
Referenced by RefreshInfo().
buttonDelete
UIButton LayerLoadGame.buttonDelete
Definition at line 21 of file LayerLoadGame.cs.
Referenced by RefreshInfo(), and RefreshList().
buttonListBackup
UIButton LayerLoadGame.buttonListBackup
Definition at line 27 of file LayerLoadGame.cs.
Referenced by RefreshInfo().
buttonLoad
UIButton LayerLoadGame.buttonLoad
Definition at line 19 of file LayerLoadGame.cs.
Referenced by RefreshList().
buttonMove
UIButton LayerLoadGame.buttonMove
Definition at line 29 of file LayerLoadGame.cs.
Referenced by RefreshInfo().
buttonOpen
UIButton LayerLoadGame.buttonOpen
Definition at line 25 of file LayerLoadGame.cs.
Referenced by RefreshInfo().
goCloudWarn
GameObject LayerLoadGame.goCloudWarn
Definition at line 15 of file LayerLoadGame.cs.
Referenced by RefreshList().
goInfo
GameObject LayerLoadGame.goInfo
Definition at line 11 of file LayerLoadGame.cs.
Referenced by RefreshInfo(), and RefreshList().
goNoInfo
GameObject LayerLoadGame.goNoInfo
Definition at line 13 of file LayerLoadGame.cs.
Referenced by RefreshInfo(), and RefreshList().
idDest
string LayerLoadGame.idDest private
Definition at line 51 of file LayerLoadGame.cs.
Referenced by Init().
list
UIList LayerLoadGame.list
Definition at line 9 of file LayerLoadGame.cs.
Referenced by RefreshList().
note
UINote LayerLoadGame.note
Definition at line 17 of file LayerLoadGame.cs.
Referenced by RefreshInfo().
pathBackup
string LayerLoadGame.pathBackup private
Definition at line 53 of file LayerLoadGame.cs.
Referenced by Init(), and RefreshList().
pathRoot
string LayerLoadGame.pathRoot private
Definition at line 49 of file LayerLoadGame.cs.
Referenced by RefreshList().
portrait
Portrait LayerLoadGame.portrait
Definition at line 33 of file LayerLoadGame.cs.
Referenced by RefreshInfo().
textAka
UIText LayerLoadGame.textAka
Definition at line 35 of file LayerLoadGame.cs.
Referenced by RefreshInfo().
textDays
UIText LayerLoadGame.textDays
Definition at line 47 of file LayerLoadGame.cs.
Referenced by RefreshInfo().
textDeepest
UIText LayerLoadGame.textDeepest
Definition at line 45 of file LayerLoadGame.cs.
Referenced by RefreshInfo().
textInfo
UIText LayerLoadGame.textInfo
Definition at line 39 of file LayerLoadGame.cs.
textJob
UIText LayerLoadGame.textJob
Definition at line 43 of file LayerLoadGame.cs.
Referenced by RefreshInfo().
textName
UIText LayerLoadGame.textName
Definition at line 37 of file LayerLoadGame.cs.
Referenced by RefreshInfo().
textRace
UIText LayerLoadGame.textRace
Definition at line 41 of file LayerLoadGame.cs.
Referenced by RefreshInfo().
worlds
List<GameIndex> LayerLoadGame.worlds
Definition at line 31 of file LayerLoadGame.cs.
Referenced by RefreshList().
Property Documentation
cloud
bool LayerLoadGame.cloud get private
Definition at line 57 of file LayerLoadGame.cs.
Referenced by RefreshInfo(), and RefreshList().
The documentation for this class was generated from the following file:
Elin/LayerLoadGame.cs