Elin Decompiled Documentation: AI_Idle Class Reference
AI_Idle Class Reference
Public Types
enum Behaviour { Default , NoMove }
Public Types inherited from AIAct
enum Status { Running , Fail , Success }
Public Types inherited from Act
enum CostType { None , MP , SP }
Public Member Functions
override void OnStart ()
override IEnumerable< Status > Run ()
void IdleActText (string id)
void TryCast< T > (EffectId id, int power=100)
void TryCast (EffectId id, int power=100)
BaseArea GetRandomAssignedRoom ()
Chara DoSomethingToNearChara (Func< Chara, bool > funcPickChara, Action< Chara > action=null)
Chara DoSomethingToCharaInRadius (int radius, Func< Chara, bool > funcPickChara, Action< Chara > action=null)
bool TryPerformIdleUse ()
Public Member Functions inherited from AIAct
override string ToString ()
override MultiSprite GetStateIcon ()
virtual bool ShouldAllyAttack (Chara tg)
virtual Point GetDestination ()
AIProgress GetProgress ()
string GetCurrentActionText ()
override bool IsToolValid ()
virtual void OnStart ()
void SetOwner (Chara c)
virtual void OnSetOwner ()
void SetChild (AIAct seq, Func< Status > _onChildFail=null)
void Start ()
override bool Perform ()
Status Restart ()
Status Success (Action action=null)
virtual void OnSuccess ()
bool TryCancel (Card c)
virtual Status Cancel ()
virtual void OnCancel ()
virtual void OnCancelOrSuccess ()
virtual bool CanManualCancel ()
Status KeepRunning ()
void Reset ()
virtual void OnReset ()
Status Tick ()
virtual IEnumerable< Status > Run ()
Status TickChild ()
Status Do (AIAct _seq, Func< Status > _onChildFail=null)
Status DoGotoInteraction (Point pos, Func< Status > _onChildFail=null)
Status DoGoto (Point pos, int dist=0, bool ignoreConnection=false, Func< Status > _onChildFail=null)
Status DoGoto (Card card, Func< Status > _onChildFail=null)
Status DoGoto (Card card, int dist, Func< Status > _onChildFail=null)
Status DoGotoSpot (Card card, Func< Status > _onChildFail=null)
Status DoGoto< T > (Func< Status > _onChildFail=null)
Status DoGotoSpot< T > (Func< Status > _onChildFail=null, bool ignoreAccessType=false)
Status DoGrab (Card card, int num=-1, bool pickHeld=false, Func< Status > _onChildFail=null)
Status DoGrab< T > ()
Status DoProgress ()
Status DoIdle (int repeat=3)
Status DoWait (int count=1)
virtual AIProgress CreateProgress ()
virtual void OnCreateProgress (Progress_Custom p)
virtual bool CanProgress ()
virtual void OnBeforeProgress ()
virtual void OnProgress ()
virtual void OnProgressComplete ()
void SimulateZone (int days)
virtual void OnSimulateZone (int days)
virtual void OnSimulatePosition ()
Public Member Functions inherited from Act
virtual CursorInfo GetCursorIcon (Card c)
virtual MultiSprite GetStateIcon ()
override Sprite GetSprite ()
virtual bool ShowMouseHint (Card c)
virtual bool IsValidTC (Card c)
virtual string GetHintText (string str="")
virtual string GetText (string str="")
virtual string GetTextSmall (Card c)
bool IsTargetHostileParty ()
virtual Color GetActPlanColor ()
virtual bool Perform ()
virtual bool CanPerform ()
bool Perform (Chara _cc, Card _tc=null, Point _tp=null)
bool CanPerform (Chara _cc, Card _tc=null, Point _tp=null)
virtual bool IsToolValid ()
new void SetImage (Image image)
virtual void OnMarkMapHighlights ()
virtual bool ShouldMapHighlight (Point p)
Public Member Functions inherited from Element
virtual SourceElement.Row GetSource ()
virtual int GetSourcePotential (int v)
virtual Sprite GetSprite ()
int GetMaterialSourceValue (Thing t, int v)
virtual long GetSourceValue (long v, int lv, SourceValueType type)
virtual Sprite GetIcon (string suffix="")
bool IsActive (Card c)
int SortVal (bool charaSheet=false)
virtual bool CanLink (ElementContainer owner)
bool HasTag (string tag)
void SetImage (Image i)
virtual string GetDetail ()
bool IsFactionElement (Chara c)
Element GetParent (Card c)
void WriteNote (UINote n, ElementContainer owner=null, Action< UINote > onWriteNote=null)
void WriteNoteWithRef (UINote n, ElementContainer owner, Action< UINote > onWriteNote, Element refEle)
void _WriteNote (UINote n, Chara c, Act act)
void AddHeaderAbility (UINote n)
void _WriteNote (UINote n, ElementContainer owner, Action< UINote > onWriteNote, bool isRef, bool addHeader=true)
void AddEncNote (UINote n, Card Card, ElementContainer.NoteMode mode=ElementContainer.NoteMode.Default, Func< Element, string, string > funcText=null, Action< UINote, Element > onAddNote=null)
virtual void OnWriteNote (UINote n, ElementContainer owner)
virtual void OnChangeValue ()
void CheckLevelBonus (ElementContainer owner, UINote n=null)
int GetSortVal (UIList.SortMode m)
virtual Act.Cost GetCost (Chara c)
virtual int GetPower (Card c)
virtual void SetTextValue (UIText text)
virtual bool IsPurchaseFeatReqMet (ElementContainer owner, int lv=-1)
virtual void WritePurchaseReq (UINote n, int lv=1)
Public Attributes
int maxRepeat = 10
int moveFailCount
Public Attributes inherited from AIAct
new Chara owner
Status status
IEnumerator< Status > Enumerator
AIAct child
AIAct parent
byte restartCount
Func< Status > onChildFail
Func< bool > isFail
Public Attributes inherited from Element
SourceElement.Row _source
int id
int vBase
int vExp
int vPotential
int vTempPotential
int vLink
int vSource
int vSourcePotential
ElementContainer owner
Properties
override bool IsIdle [get]
override bool InformCancel [get]
override int MaxRestart [get]
Properties inherited from AIAct
virtual bool IsRunning [get]
bool IsChildRunning [get]
bool IsMoveAI [get]
virtual int MaxRestart [get]
virtual new string Name [get]
virtual MultiSprite stateIcon [get]
virtual Sprite actionIcon [get]
virtual bool IsNoGoal [get]
virtual bool IsAutoTurn [get]
virtual bool IsIdle [get]
virtual bool CancelOnAggro [get]
virtual bool PushChara [get]
virtual int MaxProgress [get]
virtual bool ShowProgress [get]
virtual bool UseTurbo [get]
virtual int CurrentProgress [get]
virtual bool ShowCursor [get]
virtual bool CancelWhenDamaged [get]
virtual bool CancelWhenMoved [get]
virtual bool InformCancel [get]
virtual Thing RenderThing [get]
AIAct Current [get]
override bool IsAct [get]
override bool ShowPotential [get]
override bool UsePotential [get]
override bool ShowRelativeAttribute [get]
virtual bool HasProgress [get]
Properties inherited from Act
override bool ShowPotential [get]
override bool UsePotential [get]
override bool ShowRelativeAttribute [get]
virtual CursorInfo CursorIcon [get]
virtual string ID [get]
virtual bool IsAct [get]
virtual bool WillEndTurn [get]
virtual bool CloseLayers [get]
virtual int LeftHand [get]
virtual int RightHand [get]
virtual int ElementPowerMod [get]
virtual bool ShowMapHighlight [get]
virtual bool ShowMapHighlightBlock [get]
virtual bool PickHeldOnStart [get]
virtual bool DropHeldOnStart [get]
virtual bool CanPressRepeat [get]
virtual bool CanAutofire [get]
virtual bool ResetAxis [get]
virtual bool RequireTool [get]
virtual bool IsHostileAct [get]
virtual bool HideRightInfo [get]
virtual bool HaveLongPressAction [get]
virtual float Radius [get]
virtual int PerformDistance [get]
virtual int MaxRadius [get]
virtual TargetType TargetType [get]
virtual bool LocalAct [get]
virtual bool CanRapidFire [get]
virtual float RapidDelay [get]
virtual bool ShowAuto [get]
virtual bool IsCrime [get]
Properties inherited from Element
SourceElement.Row source [get]
virtual int DisplayValue [get]
virtual int MinValue [get]
int Value [get]
int ValueWithoutLink [get]
virtual int MinPotential [get]
int Potential [get]
virtual bool CanGainExp [get]
bool IsFlag [get]
virtual string Name [get]
virtual string FullName [get]
virtual int ExpToNext [get]
virtual bool UseExpMod [get]
virtual int CostTrain [get]
virtual int CostLearn [get]
virtual bool ShowXP [get]
virtual bool ShowMsgOnValueChanged [get]
virtual bool ShowValue [get]
virtual bool ShowPotential [get]
virtual bool UsePotential [get]
virtual bool PotentialAsStock [get]
virtual bool ShowRelativeAttribute [get]
virtual bool ShowBonuses [get]
virtual string ShortName [get]
bool IsGlobalElement [get]
bool IsFactionWideElement [get]
bool IsPartyWideElement [get]
virtual bool ShowEncNumber [get]
bool IsTrait [get]
bool IsFoodTrait [get]
bool IsFoodTraitMain [get]
bool IsMainAttribute [get]
Act act [get]
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Static Private Attributes
static List< BaseArea > _listRoom = new List<BaseArea>()
Additional Inherited Members
Static Public Member Functions inherited from Act
static void SetReference (Chara _cc, Card _tc=null, Point _tp=null)
static void SetTool (Thing t)
Static Public Member Functions inherited from Element
static string GetName (string alias)
static SourceElement.Row Get (int id)
static Dictionary< int, int > GetElementMap (int[] list)
static Dictionary< int, int > GetElementMap (int[] list, Dictionary< int, int > map)
static SourceElement.Row GetRandomElement (int lv=1, bool useWeight=true)
static Element Create (int id, int v=0)
static Element Create (string id, int v=1)
static int GetId (string alias)
static int GetResistLv (int v)
static int GetResistDamage (int dmg, int v, int power=0)
Static Public Member Functions inherited from EClass
static int rndSeed (int a, int seed)
static int rnd (long a)
static int rnd (int a)
static int curve (int a, int start, int step, int rate=75)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Static Public Attributes inherited from Act
static Chara CC
static Card TC
static Point TP = new Point()
static Thing TOOL
static int powerMod = 100
static bool forcePt
static Act CurrentAct
Static Public Attributes inherited from Element
const int Div = 5
static Element Void = new Element()
static int[] List_MainAttributes = new int[9] { 70, 72, 71, 77, 74, 75, 76, 73, 79 }
static int[] List_MainAttributesMajor = new int[8] { 70, 72, 71, 77, 74, 75, 76, 73 }
static int[] List_Body = new int[4] { 70, 72, 71, 77 }
static int[] List_Mind = new int[4] { 74, 75, 76, 73 }
static List< SourceElement.Row > ListElements = new List<SourceElement.Row>()
static List< SourceElement.Row > ListAttackElements = new List<SourceElement.Row>()
Static Public Attributes inherited from EClass
static Core core
Detailed Description
Definition at line 6 of file AI_Idle.cs.
Member Enumeration Documentation
Behaviour
enum AI_Idle.Behaviour
Enumerator
Default
NoMove
Definition at line 8 of file AI_Idle.cs.
    {
        Default,
        NoMove
    }
Member Function Documentation
DoSomethingToCharaInRadius()
Chara AI_Idle.DoSomethingToCharaInRadius (int radius, Func< Chara, bool > funcPickChara, Action< Chara > action = null) inline
Definition at line 1011 of file AI_Idle.cs.
    {
        List<Chara> list = owner.pos.ListCharasInRadius(owner, radius, delegate(Chara c)
        {
            if (c == owner || !owner.CanSee(c))
            {
                return false;
            }
            return funcPickChara == null || funcPickChara(c);
        });
        if (list.Count > 0)
        {
            Chara chara = list.RandomItem();
            action?.Invoke(chara);
            return chara;
        }
        return null;
    }
References Chara.CanSee(), Point.ListCharasInRadius(), and Card.pos.
Referenced by Run().
DoSomethingToNearChara()
Chara AI_Idle.DoSomethingToNearChara (Func< Chara, bool > funcPickChara, Action< Chara > action = null) inline
Definition at line 992 of file AI_Idle.cs.
    {
        List<Chara> list = owner.pos.ListCharasInNeighbor(delegate(Chara c)
        {
            if (c == owner || !owner.CanSee(c))
            {
                return false;
            }
            return funcPickChara == null || funcPickChara(c);
        });
        if (list.Count > 0)
        {
            Chara chara = list.RandomItem();
            action?.Invoke(chara);
            return chara;
        }
        return null;
    }
References Chara.CanSee(), Point.ListCharasInNeighbor(), and Card.pos.
Referenced by Run().
GetRandomAssignedRoom()
BaseArea AI_Idle.GetRandomAssignedRoom () inline
Definition at line 979 of file AI_Idle.cs.
    {
        _listRoom.Clear();
        foreach (BaseArea item in ((IEnumerable<BaseArea>)EClass._map.rooms.listRoom).Concat((IEnumerable<BaseArea>)EClass._map.rooms.listArea))
        {
            if (item.type != null && item.type.uidCharas.Contains(owner.uid))
            {
                _listRoom.Add(item);
            }
        }
        return _listRoom.RandomItem();
    }
References EClass._map, item, RoomManager.listArea, RoomManager.listRoom, and Map.rooms.
IdleActText()
void AI_Idle.IdleActText (string id) inline
Definition at line 955 of file AI_Idle.cs.
    {
        string text = "idle_" + id;
        owner.PlaySound(text);
        if (Lang.Game.map.ContainsKey(text))
        {
            owner.Say(text, owner);
        }
    }
References Lang.Game.
Referenced by Run().
OnStart()
override void AI_Idle.OnStart () inline virtual
Reimplemented from AIAct.
Definition at line 26 of file AI_Idle.cs.
    {
        owner.SetTempHand(-1, -1);
        owner.ShowEmo();
    }
References AIAct.owner, Chara.SetTempHand(), and Card.ShowEmo().
Run()
override IEnumerable< Status > AI_Idle.Run () inline virtual
Reimplemented from AIAct.
Definition at line 32 of file AI_Idle.cs.
    {
        while (true)
        {
            if (owner.held != null)
            {
                owner.PickHeld();
            }
            if (owner.nextUse != null)
            {
                Thing nextUse = owner.nextUse;
                owner.nextUse = null;
                if (nextUse.parent == owner && !nextUse.isDestroyed)
                {
                    owner.TryUse(nextUse);
                }
                yield return KeepRunning();
            }
            if (owner.pos.cell.HasFire)
            {
                if (EClass.rnd(5) == 0)
                {
                    owner.Talk("onFire");
                }
                if (owner.MoveNeighborDefinitely())
                {
                    yield return Restart();
                }
            }
            if (EClass.rnd(owner.IsPCParty ? 10 : 100) == 0 && owner.hunger.GetPhase() >= 3)
            {
                Thing thing = (owner.IsPCFaction ? owner.FindBestFoodToEat() : owner.things.Find((Thing a) => owner.CanEat(a, owner.IsPCFaction) && !a.c_isImportant, recursive: false));
                if (thing == null && owner.IsPCFaction && EClass._zone.IsPCFaction)
                {
                    thing = EClass._zone.branch.GetMeal(owner);
                    if (thing != null)
                    {
                        owner.Pick(thing);
                    }
                }
                if (thing == null && !owner.IsPCParty)
                {
                    if (!owner.IsPCFaction && EClass.rnd(8) != 0)
                    {
                        owner.hunger.Mod(-30);
                    }
                    else if (!owner.things.IsFull())
                    {
                        thing = ThingGen.CreateFromCategory("food", EClass.rnd(EClass.rnd(60) + 1) + 10);
                        if (thing.trait.CanEat(owner))
{
                            thing.isNPCProperty = true;
                            thing = owner.AddThing(thing);
                        }
                        else
{
                            thing = null;
                        }
                    }
                }
                if (thing != null)
                {
                    if (EClass._zone.IsRegion)
                    {
                        owner.InstantEat(thing, sound: false);
                        yield return Restart();
                    }
                    else if (thing.Num == 1 || !owner.things.IsFull())
                    {
                        yield return Do(new AI_Eat
{
                            target = thing
                        });
                    }
                }
            }
            if (!EClass._zone.IsRegion)
            {
                if (EClass.rnd(10) == 0 && owner.ability.Has(6627) && ((float)owner.hp < (float)owner.MaxHP * 0.8f || EClass.rnd(10) == 0) && owner.GetNearbyCatToSniff() != null && !owner.HasCondition<ConHOT>())
                {
                    owner.Sniff(owner.GetNearbyCatToSniff());
                    yield return KeepRunning();
                }
                if (EClass.rnd(3) == 0 && owner.mana.value > 0)
                {
                    Act act = null;
                    Act actRevive = null;
                    foreach (ActList.Item item in owner.ability.list.items)
                    {
                        Act act2 = item.act;
                        if (act2.id == 8430)
{
                            actRevive = act2;
                        }
                        string[] abilityType = act2.source.abilityType;
                        if (!abilityType.IsEmpty() && (abilityType[0] == "heal" || abilityType[0] == "hot"))
{
                            act = item.act;
                        }
                    }
                    if (act != null)
                    {
                        List<Chara> list = (owner.IsPCParty ? EClass.pc.party.members : new List<Chara> { owner });
                        foreach (Chara item2 in list)
{
                            if (!((float)item2.hp > (float)item2.MaxHP * 0.75f) && owner.CanSeeLos(item2) && (!(act.source.abilityType[0] == "hot") || !item2.HasCondition<ConHOT>()))
{
                                owner.UseAbility(act, item2);
                                yield return KeepRunning();
                                break;
                            }
                        }
                    }
                    if (actRevive != null && owner.IsPCFaction && EClass.game.cards.globalCharas.Where((KeyValuePair<int, Chara> a) => a.Value.isDead && a.Value.faction == EClass.pc.faction && !a.Value.isSummon && a.Value.c_wasInPcParty).ToList().Count > 0 && owner.UseAbility(actRevive.source.alias, owner))
                    {
                        yield return KeepRunning();
                    }
                }
            }
            if (owner.IsPCFaction && EClass._zone.IsPCFaction)
            {
                owner.sharedCheckTurn--;
                if (owner.sharedCheckTurn < 0 && EClass.rnd(EClass.debug.enable ? 2 : 20) == 0)
                {
                    owner.TryTakeSharedItems();
                    owner.TryPutSharedItems();
                    owner.sharedCheckTurn += (EClass.debug.enable ? 20 : 200);
                }
            }
            if ((EClass._zone is Zone_Civilized || EClass._zone.IsPCFaction) && (owner.IsPCParty ? 10 : (owner.IsPCFaction ? 2 : 0)) > EClass.rnd(100))
            {
                Thing thing2 = owner.things.Find("polish_powder");
                if (thing2 != null && EClass._map.props.installed.Find<TraitGrindstone>() != null)
                {
                    foreach (Thing thing9 in owner.things)
                    {
                        if (!thing9.IsEquipment || thing9.encLV >= 0)
{
                            continue;
                        }
                        for (int j = 0; j < 5; j++)
{
                            if (thing9.encLV >= 0)
{
                                break;
                            }
                            owner.Say("polish", owner, thing9);
                            thing9.ModEncLv(1);
                            thing2.ModNum(-1);
                            if (thing2.isDestroyed)
{
                                break;
                            }
                        }
                        if (thing2.isDestroyed)
{
                            break;
                        }
                    }
                }
            }
            if (owner.IsPCParty)
            {
                if (owner.IsRestrainedResident && owner.stamina.value > owner.stamina.max / 2)
                {
                    TraitShackle traitShackle = owner.pos.FindThing<TraitShackle>();
                    if (traitShackle != null && traitShackle.AllowTraining)
                    {
                        owner.SetAI(new AI_Torture
{
                            shackle = traitShackle
                        });
                    }
                    yield return Restart();
                }
                if (EClass.rnd(20) == 0)
                {
                    Thing thing3 = owner.things.Find((Thing a) => a.parent == owner && a.isGifted && (a.category.id == "skillbook" || a.category.id == "ancientbook"));
                    if (thing3 != null && thing3.trait.CanRead(owner) && (thing3.Num == 1 || !owner.things.IsFull()))
                    {
                        yield return Do(new AI_Read
{
                            target = thing3
                        });
                    }
                }
                if (EClass.rnd(100) == 0 && !EClass._zone.IsRegion && owner.HasElement(1227))
                {
                    List<Chara> list2 = new List<Chara>();
                    foreach (Chara member in EClass.pc.party.members)
                    {
                        if (member.Evalue(1227) > 0)
{
                            list2.Add(member);
                        }
                    }
                    if (list2.Count > 2 + EClass.pc.party.EvalueTotal(1272, (Chara c) => c.IsPC || c.faith == EClass.game.religions.Harmony))
                    {
                        list2.Remove(owner);
                        owner.SetEnemy(list2.RandomItem());
                        yield return Success();
                    }
                }
                if (EClass.rnd(150) == 0 && owner.host != null && owner.host.parasite == owner && owner.GetInt(108) == 1)
                {
                    owner.host.PlaySound("whip");
                    owner.host.Say("use_whip3", owner, owner.host);
                    owner.Talk("insult");
                    owner.host.PlayAnime(AnimeID.Shiver);
                    owner.host.DamageHP(5 + EClass.rndHalf(owner.host.MaxHP / 5), 919, 100, AttackSource.Condition);
                    owner.host.OnInsulted();
                    yield return KeepRunning();
                }
                if (EClass.rnd(EClass.debug.enable ? 2 : 20) == 0 && owner.CanSee(EClass.pc) && !(EClass.pc.ai is AI_Eat))
                {
                    owner.TryTakeSharedItems(EClass.pc.things.List((Thing t) => t.IsSharedContainer));
                }
                if (owner.isSynced && EClass.rnd((owner.host == null) ? 200 : 150) == 0 && owner.GetInt(106) == 0)
                {
                    if (EClass.rnd(2) == 0 && owner.GetInt(108) == 1)
                    {
                        owner.Talk("insult");
                    }
                    else
                    {
                        owner.TalkTopic();
                    }
                }
                if (EClass.rnd(100) == 0 && EClass._zone.IsTown)
                {
                    owner.ClearInventory(ClearInventoryType.SellAtTown);
                }
                if ((EClass.rnd(20) == 0 || EClass.debug.enable) && owner.GetCurrency() >= 500)
                {
                    bool flag = EClass._zone.IsTown;
                    if (EClass._zone.IsPCFaction)
                    {
                        foreach (Chara member2 in EClass._zone.branch.members)
{
                            if (member2.ExistsOnMap && member2.trait is TraitTrainer)
{
                                flag = true;
                            }
                        }
                    }
                    if (flag)
                    {
                        bool flag2 = false;
                        foreach (Element value in owner.elements.dict.Values)
{
                            if (!(value.source.category != "skill") && value.vTempPotential < 900)
{
                                flag2 = true;
                                break;
                            }
                        }
                        if (flag2)
{
                            int num = owner.GetCurrency();
                            if (num >= 20000)
{
                                num = 20000;
                            }
                            owner.PlaySound("pay");
                            int num2 = num / 200;
                            foreach (Element value2 in owner.elements.dict.Values)
{
                                if (!(value2.source.category != "skill"))
{
                                    int num3 = num2 * 100 / (100 + (100 + value2.vTempPotential / 2 + value2.ValueWithoutLink) * (100 + value2.vTempPotential / 2 + value2.ValueWithoutLink) / 100);
                                    num3 += 1 + EClass.rnd(3);
                                    owner.elements.ModTempPotential(value2.id, Mathf.Max(1, num3), 9999);
                                }
                            }
                            Msg.Say("party_train", owner, Lang._currency(num));
                            owner.PlaySound("ding_potential");
                            owner.ModCurrency(-num);
                        }
                    }
                }
                if (EClass.rnd(100) == 0 && EClass.pc.ai is AI_Fish && owner.stamina.value > 0 && owner.things.Find<TraitToolFishing>() != null)
                {
                    Point randomPointInRadius = EClass.pc.pos.GetRandomPointInRadius(0, 3);
                    if (randomPointInRadius != null)
                    {
                        randomPointInRadius = AI_Fish.GetFishingPoint(randomPointInRadius);
                        if (randomPointInRadius.IsValid)
{
                            yield return Do(new AI_Fish
{
                                pos = randomPointInRadius
                            });
                        }
                    }
                }
            }
            if (owner.c_uidMaster != 0)
            {
                Chara chara = owner.master;
                if (chara == null || !chara.IsAliveInCurrentZone)
                {
                    chara = owner.FindMaster();
                }
                if (chara != null && chara.IsAliveInCurrentZone)
                {
                    if (owner.enemy == null)
                    {
                        owner.SetEnemy(chara.enemy);
                    }
                    int num4 = owner.Dist(chara.pos);
                    if (owner.source.aiIdle != "root" && num4 > EClass.game.config.tactics.AllyDistance(owner) && EClass._zone.PetFollow && owner.c_minionType == MinionType.Default)
                    {
                        if (owner.HasAccess(chara.pos))
{
                            owner.TryMoveTowards(chara.pos);
                        }
                        yield return KeepRunning();
                        continue;
                    }
                }
            }
            Party party = owner.party;
            if (party == null || party.leader == owner || !party.leader.IsAliveInCurrentZone || owner.host != null || !EClass._zone.PetFollow)
            {
                break;
            }
            if (owner.source.aiIdle == "root")
            {
                yield return KeepRunning();
                continue;
            }
            if (owner.Dist(party.leader.pos) <= EClass.game.config.tactics.AllyDistance(owner))
            {
                yield return KeepRunning();
                continue;
            }
            if (owner.HasAccess(party.leader.pos) && owner.TryMoveTowards(party.leader.pos) == Card.MoveResult.Fail && owner.Dist(party.leader) > 4)
            {
                moveFailCount++;
                bool flag3 = (EClass._zone is Zone_Civilized || EClass._zone.IsPCFaction) && (EClass.pc.enemy == null || !EClass.pc.enemy.IsAliveInCurrentZone);
                if (moveFailCount >= (flag3 ? 100 : 10))
                {
                    owner.Teleport(party.leader.pos.GetNearestPoint(allowBlock: false, allowChara: false, allowInstalled: true, ignoreCenter: true), silent: false, force: true);
                    moveFailCount = 0;
                }
            }
            else
            {
                moveFailCount = 0;
            }
            yield return KeepRunning();
        }
        if (EClass._zone.IsNefia && EClass._zone.Boss == owner && EClass.rnd(20) == 0)
        {
            owner.SetEnemy(EClass.pc);
        }
        if (EClass._zone.IsRegion && EClass.rnd(10) != 0)
        {
            yield return Restart();
        }
        if (((owner.homeBranch != null && owner.homeBranch == EClass.Branch && EClass.rnd(100) == 0) || (owner.IsGuest() && EClass.rnd(50) == 0)) && owner.FindBed() == null)
        {
            owner.TryAssignBed();
        }
        string text;
        if (!EClass._zone.IsRegion)
        {
            text = owner.id;
            if (!(text == "geist"))
            {
                if (text == "mech_scarab" && EClass.rnd(20) == 0 && owner.CanDuplicate() && !EClass._zone.IsUserZone)
                {
                    int i = 0;
                    owner.pos.ForeachNeighbor(delegate(Point p)
                    {
                        if (p.HasChara && p.FirstChara.id == "mech_scarab")
{
                            i++;
                        }
                    });
                    if (i < 2)
                    {
                        Point randomPoint = owner.pos.GetRandomPoint(1, requireLos: false, allowChara: false, allowBlocked: false, 20);
                        if (randomPoint != null)
{
                            Card c2 = EClass._zone.AddCard(owner.Duplicate(), randomPoint);
                            if (randomPoint.Distance(EClass.pc.pos) < EClass.pc.GetHearingRadius())
{
                                Msg.Say("self_dupe", owner, c2);
                            }
                        }
                    }
                }
            }
            else if (EClass.rnd(20) == 0)
            {
                Point nearestPoint = EClass.pc.pos.GetNearestPoint(allowBlock: false, allowChara: false);
                if (nearestPoint != null)
                {
                    foreach (Chara item3 in nearestPoint.ListCharasInRadius(owner, 6, (Chara _c) => _c != owner && !_c.IsPCFactionOrMinion))
                    {
                        item3.Teleport(nearestPoint.GetNearestPoint(allowBlock: false, allowChara: false) ?? nearestPoint);
                    }
                    if (owner != null)
                    {
                        if (!owner.IsPCFactionOrMinion)
{
                            EClass.pc.ai.Cancel();
                        }
                        owner.Teleport(nearestPoint);
                    }
                    yield return Success();
                }
            }
        }
        if (owner.IsMinion && owner.master != null && owner.master.id == "keeper_garden" && !(owner.master.ai is GoalCombat))
        {
            owner.Banish(owner.master);
            yield return Success();
        }
        if (EClass._zone.IsPCFaction)
        {
            Room room = owner.pos.cell.room;
            if (room != null)
            {
                Point point = null;
                if (owner.memberType == FactionMemberType.Guest && room.data.accessType != 0)
                {
                    point = FindMovePoint(BaseArea.AccessType.Public);
                }
                else if (owner.memberType == FactionMemberType.Default && room.data.accessType == BaseArea.AccessType.Private)
                {
                    point = FindMovePoint(BaseArea.AccessType.Resident) ?? FindMovePoint(BaseArea.AccessType.Public);
                }
                if (point != null)
                {
                    yield return DoGoto(point);
                }
            }
        }
        if (owner.isSynced && !owner.IsPCParty)
        {
            if (owner.IsPCFaction && owner.GetInt(32) + 4320 < EClass.world.date.GetRaw())
            {
                if (owner.GetInt(32) != 0 && Zone.okaerinko < 10)
                {
                    owner.Talk("welcomeBack");
                    Zone.okaerinko++;
                }
                owner.SetInt(32, EClass.world.date.GetRaw());
            }
            else if (EClass.player.stats.turns > owner.turnLastSeen + 50 && Los.IsVisible(EClass.pc, owner) && owner.CanSee(EClass.pc))
            {
                if (EClass.rnd(5) == 0 && owner.hostility >= Hostility.Neutral && EClass.pc.IsPCC && EClass.pc.pccData.state == PCCState.Undie && !EClass.pc.pos.cell.IsTopWaterAndNoSnow)
                {
                    owner.Talk("pervert3");
                }
                else if (EClass.rnd(15) == 0 && EClass._zone.IsTown && owner.hostility >= Hostility.Neutral && !owner.IsPCFaction && !EClass.pc.HasCondition<ConIncognito>())
                {
                    bool flag4 = EClass._zone is Zone_Derphy;
                    string text2 = ((EClass.player.karma > 10) ? ((EClass.player.karma < 90) ? "" : (flag4 ? "rumor_bad" : "rumor_good")) : (flag4 ? "rumor_good" : "rumor_bad"));
                    if (!text2.IsEmpty())
                    {
                        owner.Talk(text2);
                    }
                    if ((flag4 ? (EClass.player.karma >= 90) : (EClass.player.karma <= 10)) && EClass.rnd(10) == 0)
                    {
                        Thing t2 = ThingGen.Create("stone");
                        AI_PlayMusic.ignoreDamage = true;
                        ActThrow.Throw(owner, EClass.pc.pos, t2, ThrowMethod.Punish);
                        AI_PlayMusic.ignoreDamage = false;
                    }
                }
                else
                {
                    owner.TalkTopic("fov");
                }
                owner.turnLastSeen = EClass.player.stats.turns;
            }
        }
        if (EClass.rnd(25) == 0 && owner.IsInMutterDistance())
        {
            if (owner.isRestrained)
            {
                owner.PlayAnime(AnimeID.Shiver);
            }
            TCText tC = owner.HostRenderer.GetTC<TCText>();
            if (tC == null || tC.pop.items.Count == 0)
            {
                if (owner.noMove)
                {
                    foreach (Thing thing10 in owner.pos.Things)
                    {
                        if (thing10.IsInstalled && thing10.trait is TraitGeneratorWheel)
{
                            owner.Talk("labor");
                            owner.PlayAnime(AnimeID.Shiver);
                            yield return Restart();
                        }
                    }
                }
                if (owner.isDrunk && (owner.race.id == "cat" || owner.id == "sailor"))
                {
                    owner.Talk("drunk_cat");
                }
                else if (owner.isRestrained)
                {
                    owner.Talk("restrained");
                }
                else if (owner.GetInt(106) == 0 && !owner.IsPCParty)
                {
                    if (owner.HasElement(1232) && EClass.rnd(4) == 0)
                    {
                        owner.Talk("baby");
                    }
                    else if (EClass.rnd((owner.host == null) ? 2 : 10) == 0 && owner.isSynced && owner.TalkTopic().IsEmpty())
                    {
                        owner.Talk(owner.pos.IsHotSpring ? "hotspring" : "idle");
                    }
                }
            }
        }
        if (EClass.rnd(8) == 0 && owner.race.id == "chicken")
        {
            owner.PlaySound("Animal/Chicken/chicken");
        }
        if (EClass.rnd(80) == 0 && owner.race.id == "cat")
        {
            owner.PlaySound("Animal/Cat/cat");
        }
        if (owner.trait.IdAmbience != null && owner.IsInMutterDistance(15))
        {
            float mtp = 1f;
            Room room2 = owner.Cell.room;
            Room room3 = EClass.pc.Cell.room;
            if (room2 != room3 && room3 != null)
            {
                mtp = ((room2?.lot != room3?.lot) ? 0.4f : 0.7f);
            }
            EClass.Sound.PlayAmbience(owner.trait.IdAmbience, owner.pos.Position(), mtp);
        }
        if (EClass.rnd(2000) == 0 && owner.IsHuman && (owner.host == null || owner.host.ride != owner))
        {
            Thing thing4 = owner.things.Find((Thing a) => !a.IsNegativeGift && a.trait.CanDrink(owner), recursive: false);
            if (thing4 != null && thing4.trait is TraitPotion && owner.IsPCParty)
            {
                thing4 = null;
            }
            bool flag5 = EClass.Branch != null && EClass.Branch.policies.IsActive(2503);
            if (owner.homeBranch != null && owner.homeBranch.policies.IsActive(2503))
            {
                flag5 = true;
            }
            if (thing4 == null && !flag5)
            {
                thing4 = ThingGen.Create("crimAle");
                owner.Drink(thing4);
            }
            if (thing4 != null && !thing4.isDestroyed)
            {
                owner.TryUse(thing4);
                yield return Restart();
            }
        }
        if (EClass.rnd(owner.IsPCParty ? 1000 : 200) == 0 && owner.isDrunk && (owner.isSynced || EClass.rnd(5) == 0))
        {
            DoSomethingToCharaInRadius(3, null, delegate(Chara c)
            {
                owner.Say("drunk_mess", owner, c);
                owner.Talk("drunk_mess");
                bool flag6 = EClass.rnd(5) == 0 && !c.IsPC;
                if (c.IsPCParty && owner.hostility >= Hostility.Friend)
                {
                    flag6 = false;
                }
                if (flag6)
                {
                    owner.Say("drunk_counter", c, owner);
                    c.Talk("drunk_counter");
                    c.DoHostileAction(owner);
                }
            });
        }
        if (EClass.rnd(100) == 0 && owner.trait.CanFish && owner.stamina.value > 0)
        {
            Point fishingPoint = AI_Fish.GetFishingPoint(owner.pos);
            if (fishingPoint.IsValid)
            {
                yield return Do(new AI_Fish
                {
                    pos = fishingPoint
                });
            }
        }
        string idAct = owner.source.actIdle.RandomItem();
        if (EClass.rnd(EClass.world.date.IsNight ? 1500 : 15000) == 0 && !owner.IsPCFaction && !owner.noMove)
        {
            owner.AddCondition<ConSleep>(1000 + EClass.rnd(1000), force: true);
        }
        if (!owner.noMove)
        {
            if (EClass.rnd(3) == 0 && owner.IsCat)
            {
                Chara chara2 = ((EClass.rnd(5) == 0) ? EClass.pc.party.members.RandomItem() : EClass._map.charas.RandomItem());
                Thing thing5 = chara2.things.Find<TraitFoodChuryu>();
                if (chara2 != owner && thing5 != null)
                {
                    yield return Do(new AI_Churyu
                    {
                        churyu = thing5,
                        slave = chara2
                    });
                }
            }
            if (EClass.rnd(100) == 0 && (owner.HasHobbyOrWork("Pet") || owner.HasHobbyOrWork("Fluffy")))
            {
                yield return Do(new AI_Mofu());
            }
        }
        if (EClass.rnd((owner.host != null && owner.GetInt(106) != 0) ? 1000 : 40) == 0 && owner.IsHuman)
        {
            DoSomethingToNearChara((Chara c) => (!c.IsPCParty || EClass.rnd(5) == 0) && c.IsMofuable && !owner.IsHostile(c) && !c.IsInCombat && owner.CanSee(c), delegate(Chara c)
            {
                owner.Cuddle(c);
            });
            yield return KeepRunning();
        }
        if (EClass.rnd(100) == 0 && owner.trait is TraitBitch)
        {
            Chara chara3 = DoSomethingToNearChara((Chara c) => c.IsIdle && !c.IsPCParty && !(c.trait is TraitBitch) && c.Evalue(418) <= 0);
            if (chara3 != null)
            {
                yield return Do(new AI_Fuck
                {
                    target = chara3,
                    variation = AI_Fuck.Variation.Bitch
                });
            }
        }
        if (EClass.rnd(50) == 0 && owner.trait is TraitBard)
        {
            yield return Do(new AI_PlayMusic());
        }
        if (EClass.rnd(4) == 0 && TryPerformIdleUse())
        {
            yield return Restart();
        }
        if (EClass.rnd(20) == 0 && owner.trait.IdleAct())
        {
            yield return Restart();
        }
        if (idAct == "janitor" && EClass.rnd(5) == 0)
        {
            DoSomethingToCharaInRadius(4, null, delegate(Chara c)
            {
                if (c.HasElement(1211) && !(EClass._zone is Zone_Casino))
                {
                    owner.Talk("snail");
                    Thing t4 = ThingGen.Create("1142");
                    ActThrow.Throw(owner, c.pos, t4);
                }
            });
            yield return Restart();
        }
        if (owner.IsRestrainedResident && owner.stamina.value > owner.stamina.max / 2)
        {
            TraitShackle traitShackle2 = owner.pos.FindThing<TraitShackle>();
            if (traitShackle2 != null && traitShackle2.AllowTraining)
            {
                owner.SetAI(new AI_Torture
                {
                    shackle = traitShackle2
                });
                yield return Restart();
            }
        }
        if (!owner.IsPCFactionOrMinion && EClass.rnd(owner.isSynced ? 50 : 2000) == 0 && owner.hostility == Hostility.Neutral && EClass.pc.party.HasElement(1563) && !owner.race.tag.Contains("animal") && EClass._zone.IsTown && !EClass._zone.IsPCFaction && !owner.HasCondition<ConIncognito>())
        {
            EClass.pc.DoHostileAction(owner);
        }
        if (EClass.rnd(200) == 0 && !owner.noMove)
        {
            Point cleanPoint = AI_Clean.GetCleanPoint(owner, 4);
            if (cleanPoint != null)
            {
                yield return Do(new AI_Clean
                {
                    pos = cleanPoint
                });
            }
        }
        if (EClass.rnd(35) == 0 && owner.id == "child" && owner.pos.cell.IsSnowTile)
        {
            foreach (Chara chara4 in EClass._map.charas)
            {
                if (EClass.rnd(3) != 0 && chara4 != owner && chara4.pos.cell.IsSnowTile && chara4.Dist(owner) <= 6 && Los.IsVisible(chara4, owner))
                {
                    Thing t3 = ThingGen.Create("snow");
                    ActThrow.Throw(owner, chara4.pos, t3);
                    break;
                }
            }
        }
        if (EClass.rnd(EClass.debug.enable ? 3 : 30) == 0)
        {
            Thing thing6 = owner.things.Find<TraitBall>();
            if (thing6 == null)
            {
                if (!LayerCraft.Instance && !LayerDragGrid.Instance)
                {
                    owner.pos.ForeachNeighbor(delegate(Point p)
                    {
                        Card card2 = p.FindThing<TraitBall>()?.owner;
                        if (card2 != null)
{
                            owner.Pick(card2.Thing);
                        }
                    });
                }
            }
            else
            {
                foreach (Chara chara5 in EClass._map.charas)
                {
                    if (EClass.rnd(3) != 0 && chara5 != owner && chara5.Dist(owner) <= 6 && chara5.Dist(owner) >= 3 && Los.IsVisible(chara5, owner))
                    {
                        ActThrow.Throw(owner, chara5.pos, thing6);
                        break;
                    }
                }
            }
        }
        if (EClass.rnd(20) == 0 && AI_Shopping.TryShop(owner, realtime: true))
        {
            yield return Restart();
        }
        if (EClass.rnd(20) == 0 && owner.IsPCFaction && AI_Shopping.TryRestock(owner, realtime: true))
        {
            yield return Restart();
        }
        owner.idleActTimer--;
        if (owner.idleActTimer <= 0 && !owner.source.actIdle.IsEmpty())
        {
            owner.idleActTimer = 10 + EClass.rnd(50);
            switch (idAct)
            {
            case "torture_snail":
                DoSomethingToNearChara((Chara c) => c.race.id == "snail", delegate(Chara c)
                {
                    owner.Say("use_whip3", owner, c);
                    owner.PlaySound("whip");
                    owner.Talk("insult");
                    c.PlayAnime(AnimeID.Shiver);
                    c.OnInsulted();
                });
                break;
            case "buffMage":
                if (EClass.rnd(2) == 0)
                {
                    TryCast<ConHolyVeil>(EffectId.HolyVeil, 300 + EClass.rnd(300));
                }
                else
                {
                    TryCast<ConLevitate>(EffectId.Levitate, 300 + EClass.rnd(300));
                }
                break;
            case "buffThief":
                TryCast<ConNightVision>(EffectId.CatsEye, 100 + EClass.rnd(100));
                break;
            case "buffGuildWatch":
                TryCast<ConGravity>(EffectId.Gravity, 300 + EClass.rnd(300));
                break;
            case "buffHealer":
                TryCast(EffectId.Heal);
                break;
            case "readBook":
            {
                if (EClass.rnd(2) == 0 || (owner.IsPCParty && EClass.rnd(20) != 0))
                {
                    break;
                }
                List<Thing> list3 = owner.things.List((Thing a) => a.parent == owner && (a.category.id == "spellbook" || a.category.id == "ancientbook" || a.category.id == "skillbook"), onlyAccessible: true);
                Thing thing7 = null;
                if (list3.Count > 0)
                {
                    thing7 = list3.RandomItem();
                    if (!thing7.trait.CanRead(owner))
                    {
                        thing7 = null;
                    }
                }
                if (thing7 == null)
                {
                    if (owner.things.IsFull())
                    {
                        break;
                    }
                    thing7 = ThingGen.CreateFromCategory((EClass.rnd(5) != 0) ? "spellbook" : "ancientbook");
                    thing7.isNPCProperty = true;
                }
                if (!(thing7.id == "1084") || !owner.IsPCFaction)
                {
                    if (!owner.HasElement(285))
                    {
                        owner.elements.ModBase(285, 1);
                    }
                    yield return Do(new AI_Read
                    {
                        target = thing7
                    });
                }
                break;
            }
            default:
                if (LangGame.Has("idle_" + idAct))
                {
                    IdleActText(idAct);
                }
                break;
            }
            yield return Restart();
        }
        if (owner.host != null)
        {
            yield return Restart();
        }
        if (owner.HasEditorTag(EditorTag.AINoMove) || owner.trait.IdleBehaviour == Behaviour.NoMove || owner.noMove)
        {
            if (owner.orgPos != null && !owner.pos.Equals(owner.orgPos) && !owner.orgPos.IsBlocked && !owner.orgPos.HasChara)
            {
                yield return DoGoto(owner.orgPos);
            }
            yield return Restart();
        }
        if (owner.HasEditorTag(EditorTag.AIFollow) && owner.pos.Distance(EClass.pc.GetDestination()) > 1)
        {
            yield return DoGoto(EClass.pc);
        }
        if (EClass.rnd(100) == 0 && !owner.IsPCFaction)
        {
            if (owner.id == "ashland" || owner.id == "fiama")
            {
                Card card = EClass._map.Installed.traits.restSpots.RandomItem();
                if (card != null)
                {
                    yield return DoGotoSpot(card);
                }
                else
                {
                    Room room4 = owner.FindRoom();
                    if (room4 != null)
                    {
                        yield return DoGoto(room4.GetRandomPoint().GetNearestPoint());
                    }
                }
            }
            else if (owner.orgPos != null && !owner.pos.Equals(owner.orgPos) && !owner.orgPos.IsBlocked && !owner.orgPos.HasChara && owner.orgPos.IsInBounds)
            {
                yield return DoGoto(owner.orgPos, 0, ignoreConnection: false, delegate
                {
                    if (!EClass._zone.IsPCFaction)
                    {
                        owner.Teleport(owner.orgPos, silent: false, force: true);
                    }
                    return Status.Success;
                });
            }
        }
        if (EClass.rnd(100) == 0 && owner.id == "bee")
        {
            Thing thing8 = EClass._map.ListThing<TraitBeekeep>()?.RandomItem();
            if (thing8 != null)
            {
                yield return DoGoto(thing8.pos);
            }
        }
        if (EClass.rnd(10) == 0 && !EClass._zone.IsUnderwater && (owner.race.tag.Contains("water") || owner.source.tag.Contains("water")) && !owner.pos.IsDeepWater)
        {
            for (int k = 0; k < 100; k++)
            {
                Point randomPoint2 = EClass._map.GetRandomPoint();
                if (randomPoint2.IsDeepWater && !randomPoint2.IsBlocked)
                {
                    yield return DoGoto(randomPoint2);
                    break;
                }
            }
        }
        text = owner.source.aiIdle;
        if (!(text == "stand") && !(text == "root"))
        {
            if (EClass.rnd(15) == 0)
            {
                owner.MoveRandom();
            }
            if (owner == null)
            {
                yield return Cancel();
            }
        }
        if (EClass._zone.IsPCFaction && owner.IsPCFaction && !owner.IsPCParty && (owner.GetWork("Clean") != null || owner.GetWork("Chore") != null) && !(EClass.pc.ai is AI_UseCrafter))
        {
            AI_Haul aI_Haul = AI_Haul.TryGetAI(owner);
            if (aI_Haul != null)
            {
                yield return Do(aI_Haul);
            }
        }
        yield return Restart();
        Point FindMovePoint(BaseArea.AccessType type)
        {
            for (int l = 0; l < 20; l++)
            {
                Point randomPoint3 = owner.pos.GetRandomPoint(5 + l, requireLos: false);
                if (randomPoint3 != null && randomPoint3.IsInBounds && (randomPoint3.cell.room == null || randomPoint3.cell.room.data.accessType == type))
                {
                    return randomPoint3;
                }
            }
            return null;
        }
    }
References Lang._currency(), EClass._map, EClass._zone, Chara.ability, AreaData.accessType, Element.act, Zone.AddCard(), Chara.AddCondition(), Card.AddThing(), Chara.ai, TraitShackle.AllowTraining, ConfigTactics.AllyDistance(), Chara.Banish(), Zone.Boss, EClass.Branch, Zone.branch, Card.c_isImportant, Card.c_minionType, Card.c_uidMaster, AIAct.Cancel(), Trait.CanDrink(), Chara.CanDuplicate(), Trait.CanEat(), Chara.CanEat(), TraitChara.CanFish, Trait.CanRead(), Chara.CanSee(), Chara.CanSeeLos(), card, Game.cards, Card.category, Card.Cell, Point.cell, Map.charas, Chara.ClearInventory(), Game.config, ThingGen.Create(), ThingGen.CreateFromCategory(), Chara.Cuddle(), Card.DamageHP(), BaseArea.data, World.date, EClass.debug, ElementContainer.dict, Card.Dist(), Point.Distance(), AIAct.Do(), AIAct.DoGoto(), AIAct.DoGotoSpot(), Chara.DoHostileAction(), DoSomethingToCharaInRadius(), DoSomethingToNearChara(), Chara.Drink(), Chara.Duplicate(), Card.elements, CoreDebug.enable, Card.encLV, Chara.enemy, Point.Equals(), Card.Evalue(), Party.EvalueTotal(), Card.ExistsOnMap, Chara.faction, Chara.faith, Props.Find(), ThingContainer.Find(), Chara.FindBed(), Chara.FindBestFoodToEat(), Chara.FindMaster(), Chara.FindRoom(), Point.FindThing(), Point.FirstChara, Point.ForeachNeighbor(), EClass.game, AI_Clean.GetCleanPoint(), Card.GetCurrency(), Chara.GetDestination(), AI_Fish.GetFishingPoint(), Card.GetHearingRadius(), BaseCard.GetInt(), FactionBranch.GetMeal(), Chara.GetNearbyCatToSniff(), Point.GetNearestPoint(), Stats.GetPhase(), BaseArea.GetRandomPoint(), Point.GetRandomPoint(), Point.GetRandomPointInRadius(), Date.GetRaw(), CardRenderer.GetTC(), CardManager.globalCharas, ReligionManager.Harmony, CharaAbility.Has(), LangGame.Has(), Chara.HasAccess(), Point.HasChara, Chara.HasCondition(), Card.HasEditorTag(), Party.HasElement(), Card.HasElement(), Cell.HasFire, Chara.HasHobbyOrWork(), Chara.held, Chara.homeBranch, Chara.host, Chara.hostility, Card.HostRenderer, Card.hp, Chara.hunger, Card.id, Element.id, TraitChara.IdAmbience, TraitChara.IdleAct(), IdleActText(), Chara.idleActTimer, TraitChara.IdleBehaviour, if(), Map.Installed, PropsManager.installed, LayerCraft.Instance, LayerDragGrid.Instance, Chara.InstantEat(), PolicyManager.IsActive(), Chara.IsAliveInCurrentZone, Point.IsBlocked, Chara.IsCat, Card.isDestroyed, Chara.isDrunk, Card.IsEquipment, ThingContainer.IsFull(), Card.isGifted, Chara.IsGuest(), Chara.IsHostile(), Point.IsHotSpring, Chara.IsHuman, Chara.IsIdle, Point.IsInBounds, Chara.IsInCombat, Card.IsInMutterDistance(), Card.IsInstalled, Chara.IsMinion, Chara.IsMofuable, Zone.IsNefia, Date.IsNight, Chara.IsPC, Chara.IsPCC, Chara.IsPCFaction, Zone.IsPCFaction, Card.IsPCFactionOrMinion, Chara.IsPCParty, Spatial.IsRegion, Card.isRestrained, Card.IsRestrainedResident, Thing.IsSharedContainer, Cell.IsSnowTile, Chara.isSynced, Cell.IsTopWaterAndNoSnow, Zone.IsTown, Zone.IsUserZone, Point.IsValid, Los.IsVisible(), item, ActList.items, PopManager.items, Player.karma, AIAct.KeepRunning(), Party.leader, CharaAbility.list, ThingContainer.List(), Point.ListCharasInRadius(), Room.lot, Chara.mana, Chara.master, Stats.max, Chara.MaxHP, FactionBranch.members, Party.members, Chara.memberType, Stats.Mod(), ElementContainer.ModBase(), Card.ModCurrency(), Card.ModEncLv(), Card.ModNum(), ElementContainer.ModTempPotential(), moveFailCount, Chara.MoveNeighborDefinitely(), Chara.nextUse, Card.noMove, Card.Num, Zone.okaerinko, Chara.OnInsulted(), Chara.orgPos, AIAct.owner, Chara.parasite, Card.parent, Chara.party, EClass.pc, Chara.pccData, Zone.PetFollow, Chara.Pick(), Chara.PickHeld(), Card.PlayAnime(), EClass.player, Card.PlaySound(), FactionBranch.policies, TCText.pop, Card.pos, Point.Position(), Map.props, Chara.race, Game.religions, AIAct.Restart(), TraitManager.restSpots, EClass.rnd(), EClass.rndHalf(), Cell.room, Msg.Say(), Card.Say(), Chara.SetAI(), Chara.SetEnemy(), BaseCard.SetInt(), Chara.sharedCheckTurn, Chara.Sniff(), EClass.Sound, Chara.source, Element.source, Chara.stamina, Player.stats, AIAct.Success, Game.Config.tactics, Card.Talk(), Chara.TalkTopic(), Card.Teleport(), Card.Thing, Card.things, Point.Things, ActThrow.Throw(), Card.trait, Chara.trait, Props.traits, Chara.TryAssignBed(), TryCast(), Chara.TryMoveTowards(), TryPerformIdleUse(), Chara.TryPutSharedItems(), AI_Shopping.TryRestock(), AI_Shopping.TryShop(), Chara.TryTakeSharedItems(), Chara.TryUse(), Chara.turnLastSeen, Player.Stats.turns, Chara.UseAbility(), Stats.value, Element.ValueWithoutLink, Element.vTempPotential, and EClass.world.
TryCast()
void AI_Idle.TryCast (EffectId id, int power = 100) inline
Definition at line 973 of file AI_Idle.cs.
    {
        owner.Say("idle_cast", owner);
        ActEffect.Proc(id, power, BlessedState.Normal, owner);
    }
References ActEffect.Proc().
Referenced by Run().
TryCast< T >()
void AI_Idle.TryCast< T > (EffectId id, int power = 100) inline
Type Constraints
T : Condition
Definition at line 965 of file AI_Idle.cs.
                                                                 : Condition
    {
        if (!owner.HasCondition<T>())
        {
            TryCast(id, power);
        }
    }
TryPerformIdleUse()
bool AI_Idle.TryPerformIdleUse () inline
Definition at line 1030 of file AI_Idle.cs.
    {
        for (int i = 0; i < 10; i++)
        {
            Point randomPoint = owner.pos.GetRandomPoint(7, requireLos: true, allowChara: true, allowBlocked: true);
            if (randomPoint == null || randomPoint.detail == null)
            {
                continue;
            }
            foreach (Thing thing in randomPoint.detail.things)
            {
                if (thing.IsInstalled)
                {
                    int num = owner.Dist(thing);
                    if (EClass.rnd((owner.memberType == FactionMemberType.Guest) ? 5 : 50) == 0 && thing.HasTag(CTAG.tourism) && num <= 2)
                    {
                        owner.LookAt(thing);
                        owner.Talk("nice_statue");
                        return true;
                    }
                    if (EClass.rnd(thing.trait.IdleUseChance) == 0 && thing.trait.IdleUse(owner, num))
                    {
                        owner.LookAt(thing);
                        return true;
                    }
                }
            }
        }
        return false;
    }
References Point.detail, Point.GetRandomPoint(), Card.HasTag(), Trait.IdleUse(), Trait.IdleUseChance, Card.IsInstalled, EClass.rnd(), Card.things, and Card.trait.
Referenced by Run().
Member Data Documentation
_listRoom
List<BaseArea> AI_Idle._listRoom = new List<BaseArea>() static private
Definition at line 18 of file AI_Idle.cs.
maxRepeat
int AI_Idle.maxRepeat = 10
Definition at line 14 of file AI_Idle.cs.
moveFailCount
int AI_Idle.moveFailCount
Definition at line 16 of file AI_Idle.cs.
Referenced by Run().
Property Documentation
InformCancel
override bool AI_Idle.InformCancel get
Definition at line 22 of file AI_Idle.cs.
IsIdle
override bool AI_Idle.IsIdle get
Definition at line 20 of file AI_Idle.cs.
MaxRestart
override int AI_Idle.MaxRestart get
Definition at line 24 of file AI_Idle.cs.
The documentation for this class was generated from the following file:
Elin/AI_Idle.cs