Elin Decompiled Documentation: AnimeTween Class Reference
AnimeTween Class Reference
Public Member Functions
void Refresh ()
void PlayDebug ()
void Kill ()
void Rewind ()
void Play ()
override Tween Play (Transform trans, UnityAction onComplete=null, float duration=-1f, float delay=0f)
virtual Tween Play (Transform trans, UnityAction onComplete=null, float duration=-1f, float delay=0f)
Public Attributes
bool autoPlay
bool targetParent = true
Properties
Transform target [get]
Private Member Functions
void Awake ()
Private Attributes
List< DOTweenAnimation > animes = new List<DOTweenAnimation>()
Detailed Description
Definition at line 7 of file AnimeTween.cs.
Member Function Documentation
Awake()
void AnimeTween.Awake () inline private
Definition at line 27 of file AnimeTween.cs.
    {
        Refresh();
        if (autoPlay)
        {
            Play(target);
        }
    }
References autoPlay, Play(), Refresh(), and target.
Kill()
void AnimeTween.Kill () inline
Definition at line 51 of file AnimeTween.cs.
    {
        foreach (DOTweenAnimation anime in animes)
        {
            if (anime.tween != null)
            {
                anime.tween.Kill();
            }
        }
    }
References animes.
Referenced by Rewind().
Play() [1/2]
void AnimeTween.Play () inline
Definition at line 70 of file AnimeTween.cs.
    {
        Play(target);
    }
References Play(), and target.
Referenced by Awake(), DramaProp.Enter(), DramaProp.Leave(), Play(), PlayDebug(), and Rewind().
Play() [2/2]
override Tween AnimeTween.Play (Transform trans, UnityAction onComplete = null, float duration = -1f, float delay = 0f) inline virtual
Reimplemented from Anime.
Definition at line 75 of file AnimeTween.cs.
    {
        if (animes.Count == 0)
        {
            Refresh();
        }
        bool flag = true;
        Sequence sequence = DOTween.Sequence();
        foreach (DOTweenAnimation anime in animes)
        {
            anime.target = trans;
            if (flag && onComplete != null)
            {
                anime.CreateTween(onComplete, duration);
                flag = false;
            }
            else
            {
                anime.CreateTween(null, duration);
            }
            if (delay != 0f)
            {
                anime.tween.SetDelay(anime.tween.Delay() + delay);
            }
            sequence.Join(anime.tween);
        }
        sequence.Play();
        return sequence;
    }
References animes, and Refresh().
PlayDebug()
void AnimeTween.PlayDebug () inline
Definition at line 45 of file AnimeTween.cs.
    {
        Refresh();
        Play(target);
    }
References Play(), Refresh(), and target.
Refresh()
void AnimeTween.Refresh () inline
Definition at line 36 of file AnimeTween.cs.
    {
        animes = GetComponents<DOTweenAnimation>().ToList();
        foreach (DOTweenAnimation anime in animes)
        {
            anime.target = target;
        }
    }
References animes, and target.
Referenced by Awake(), Play(), and PlayDebug().
Rewind()
void AnimeTween.Rewind () inline
Definition at line 62 of file AnimeTween.cs.
    {
        Kill();
        target.SetLocalScale(1f, 1f, 1f);
        target.SetEulerAngles(0f, 0f, 0f);
        Play(target);
    }
References Kill(), Play(), and target.
Member Data Documentation
animes
List<DOTweenAnimation> AnimeTween.animes = new List<DOTweenAnimation>() private
Definition at line 13 of file AnimeTween.cs.
Referenced by Kill(), Play(), and Refresh().
autoPlay
bool AnimeTween.autoPlay
Definition at line 9 of file AnimeTween.cs.
Referenced by Awake().
targetParent
bool AnimeTween.targetParent = true
Definition at line 11 of file AnimeTween.cs.
Property Documentation
target
Transform AnimeTween.target get
Definition at line 15 of file AnimeTween.cs.
    {
        get
        {
            if (!targetParent)
            {
                return base.transform;
            }
            return base.transform.parent;
        }
    }
Referenced by Awake(), Play(), PlayDebug(), Refresh(), and Rewind().
The documentation for this class was generated from the following file:
Elin/Plugins.UI/AnimeTween.cs