Elin Decompiled Documentation: DramaProp Class Reference
DramaProp Class Reference
Public Member Functions
void Enter ()
virtual void OnEnter ()
void Leave ()
virtual void OnLeave ()
void Kill ()
Public Attributes
SpriteRenderer sr
AnimeTween aniEnter
AnimeTween aniLeave
Additional Inherited Members
Static Public Member Functions inherited from EMono
static int rnd (int a)
Static Public Attributes inherited from EMono
static Core core
Properties inherited from EMono
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SoundManager Sound [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static CoreDebug debug [get]
Detailed Description
Definition at line 3 of file DramaProp.cs.
Member Function Documentation
Enter()
void DramaProp.Enter () inline
Definition at line 11 of file DramaProp.cs.
    {
        aniEnter.Play(base.transform);
        OnEnter();
    }
References aniEnter, OnEnter(), and AnimeTween.Play().
Referenced by DramaManager.ParseLine().
Kill()
void DramaProp.Kill () inline
Definition at line 34 of file DramaProp.cs.
    {
        Object.Destroy(base.gameObject);
    }
Leave()
void DramaProp.Leave () inline
Definition at line 21 of file DramaProp.cs.
    {
        aniLeave.Play(base.transform, delegate
        {
            Kill();
        });
        OnLeave();
    }
References aniLeave, OnLeave(), and AnimeTween.Play().
OnEnter()
virtual void DramaProp.OnEnter () inline virtual
Reimplemented in DramaPropOnev.
Definition at line 17 of file DramaProp.cs.
    {
    }
Referenced by Enter().
OnLeave()
virtual void DramaProp.OnLeave () inline virtual
Reimplemented in DramaPropOnev.
Definition at line 30 of file DramaProp.cs.
    {
    }
Referenced by Leave().
Member Data Documentation
aniEnter
AnimeTween DramaProp.aniEnter
Definition at line 7 of file DramaProp.cs.
Referenced by Enter().
aniLeave
AnimeTween DramaProp.aniLeave
Definition at line 9 of file DramaProp.cs.
Referenced by Leave().
sr
SpriteRenderer DramaProp.sr
Definition at line 5 of file DramaProp.cs.
Referenced by DramaPropOnev.OnEnter(), and DramaPropOnev.OnLeave().
The documentation for this class was generated from the following file:
Elin/DramaProp.cs