Elin Decompiled Documentation: GridItemCardSource Class Reference
GridItemCardSource Class Reference
Public Member Functions
override void SetButton (ButtonGrid b)
Public Member Functions inherited from GridItem
virtual void SetButton (ButtonGrid b)
virtual void OnClick (ButtonGrid b)
virtual void AutoAdd ()
Public Attributes
CardRow source
Thing thing
Additional Inherited Members
Static Public Member Functions inherited from EClass
static int rndSeed (int a, int seed)
static int rnd (long a)
static int rnd (int a)
static int curve (int a, int start, int step, int rate=75)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Static Public Attributes inherited from EClass
static Core core
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Detailed Description
Definition at line 1 of file GridItemCardSource.cs.
Member Function Documentation
SetButton()
override void GridItemCardSource.SetButton (ButtonGrid b) inline virtual
Reimplemented from GridItem.
Definition at line 7 of file GridItemCardSource.cs.
    {
        b.mainText.SetActive(enable: false);
        if (thing != null)
        {
            thing.SetImage(b.icon);
            b.SetTooltip("note", delegate(UITooltip t)
            {
                thing.WriteNote(t.note);
            });
        }
        else
        {
            source.SetImage(b.icon);
        }
    }
References UIButton.icon, UIButton.mainText, UITooltip.note, Card.SetImage(), RenderRow.SetImage(), UIButton.SetTooltip(), source, thing, and Thing.WriteNote().
Member Data Documentation
source
CardRow GridItemCardSource.source
Definition at line 3 of file GridItemCardSource.cs.
Referenced by SetButton().
thing
Thing GridItemCardSource.thing
Definition at line 5 of file GridItemCardSource.cs.
Referenced by SetButton().
The documentation for this class was generated from the following file:
Elin/GridItemCardSource.cs