Elin Decompiled Documentation: TileType Class Reference
TileType Class Reference
Public Types
enum RampType { None , Full , Half }
Public Member Functions
virtual bool CanRotate (bool buildMode)
HitResult _HitTest (Point pos, Card target, bool canIgnore=true)
virtual int GetDesiredDir (Point p, int d)
virtual void GetMountHeight (ref Vector3 v, Point p, int d, Card target=null)
Vector3 GetRampFix (int dir)
Static Public Member Functions
static void Init ()
Static Public Member Functions inherited from EClass
static int rnd (int a)
static int curve (int a, int start, int step, int rate=75)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Static Public Attributes
static TileTypeNone None = new TileTypeNone()
static TileTypeInvisibleBlock InvisiBlock = new TileTypeInvisibleBlock()
static TileTypeBlock Block = new TileTypeBlock()
static TileTypeBlockShip BlockShip = new TileTypeBlockShip()
static TileTypeSlope Slope = new TileTypeSlope()
static TileTypeHalfBlock HalfBlock = new TileTypeHalfBlock()
static TileTypeStairs Stairs = new TileTypeStairs()
static TileTypeStairs StairsHalf = new TileTypeStairsHalf()
static TileTypeRooftop Rooftop = new TileTypeRooftop()
static TileTypeScaffold Scaffold = new TileTypeScaffold()
static TileTypeLadder Ladder = new TileTypeLadder()
static TileTypePillar Pillar = new TileTypePillar()
static TileTypeWaterfall Waterfall = new TileTypeWaterfall()
static TileTypeWall Wall = new TileTypeWall()
static TileTypeWallOpen WallOpen = new TileTypeWallOpen()
static TileTypeFence Fence = new TileTypeFence()
static TileTypeFenceClosed FenceClosed = new TileTypeFenceClosed()
static TileTypeFloor Floor = new TileTypeFloor()
static TileTypeFloorScaffold FloorScaffold = new TileTypeFloorScaffold()
static TileTypeWater FloorWater = new TileTypeWater()
static TileTypeWaterShallow FloorWaterShallow = new TileTypeWaterShallow()
static TileTypeWaterDeep FloorWaterDeep = new TileTypeWaterDeep()
static TileTypeBridge Bridge = new TileTypeBridge()
static TileTypeBridgeDeco BridgeDeco = new TileTypeBridgeDeco()
static TileTypeBridgePillar BridgePillar = new TileTypeBridgePillar()
static TileTypeSky Sky = new TileTypeSky()
static TileTypeObj Obj = new TileTypeObj()
static TileTypeObjBig ObjBig = new TileTypeObjBig()
static TileTypeObjHuge ObjHuge = new TileTypeObjHuge()
static TileTypeObjCeil ObjCeil = new TileTypeObjCeil()
static TileTypeObjFloat ObjFloat = new TileTypeObjFloat()
static TileTypeObjWater ObjWater = new TileTypeObjWater()
static TileTypeObjWaterTop ObjWaterTop = new TileTypeObjWaterTop()
static TileTypeIllumination Illumination = new TileTypeIllumination()
static TileTypeSeed Seed = new TileTypeSeed()
static TileTypeTree Tree = new TileTypeTree()
static TileTypeDoor Door = new TileTypeDoor()
static TileTypeWallHang WallHang = new TileTypeWallHang()
static TileTypeWallHangSign WallHangSign = new TileTypeWallHangSign()
static TileTypeVine Vine = new TileTypeVine()
static TileTypeWallMount WallMount = new TileTypeWallMount()
static TileTypePaint Paint = new TileTypePaint()
static TileTypeWindow Window = new TileTypeWindow()
static TileTypeRoof Roof = new TileTypeRoof()
static TileTypeRoad Road = new TileTypeRoad()
static TileTypeChasm Chasm = new TileTypeChasm()
static TileTypeBoat Boat = new TileTypeBoat()
static TileTypeLiquid Liquid = new TileTypeLiquid()
static TileTypeMarker Marker = new TileTypeMarker()
static Dictionary< string, TileType > dict = new Dictionary<string, TileType>()
Static Public Attributes inherited from EClass
static Core core
Protected Member Functions
virtual HitResult HitTest (Point pos)
Properties
virtual string LangPlaceType [get]
virtual bool CanStack [get]
virtual bool ChangeBlockDir [get]
virtual bool IsSkipLowBlock [get]
virtual bool IsSkipFloor [get]
virtual bool IsUseBlockDir [get]
virtual bool IsFloorOrBridge [get]
virtual bool IsWall [get]
virtual bool IsFloor [get]
virtual bool IsBridge [get]
virtual bool IsWallOrFence [get]
virtual bool IsWallOrFullBlock [get]
bool IsRamp [get]
virtual RampType Ramp [get]
virtual bool IsLadder [get]
virtual bool IsBlockPass [get]
virtual bool IsOccupyCell [get]
virtual bool IsBlockSight [get]
virtual bool IsOpenSight [get]
virtual bool IsBlockLiquid [get]
virtual bool IsWater [get]
virtual bool IsDeepWater [get]
virtual bool IsBlockMount [get]
virtual bool IsFullBlock [get]
virtual bool IsFence [get]
virtual bool IsFloodBlock [get]
virtual bool IsPlayFootSound [get]
virtual bool CanSpawnOnWater [get]
virtual bool IsWaterTop [get]
virtual bool CastShadowSelf [get]
virtual bool CastShadowBack [get]
virtual bool CastAmbientShadow [get]
virtual bool CastAmbientShadowBack [get]
virtual bool CanBuiltOnArea [get]
virtual bool CanBuiltOnWater [get]
virtual bool CanBuiltOnThing [get]
virtual bool CanBuiltOnBlock [get]
virtual bool IsDoor [get]
virtual bool CanBuiltOnFloor [get]
virtual bool CanBuiltOnBridge [get]
virtual bool CanInstaComplete [get]
virtual int MinAltitude [get]
virtual int MaxAltitude [get]
virtual bool AltitudeAsDir [get]
virtual bool UseLowWallTiles [get]
virtual bool UseMountHeight [get]
virtual bool UseHangZFix [get]
virtual bool UseLowBlock [get]
virtual bool RemoveOnFloorChange [get]
virtual bool AllowObj [get]
virtual bool AllowMultiInstall [get]
virtual bool FreeStyle [get]
virtual byte slopeHeight [get]
virtual float MountHeight [get]
virtual float FloorHeight [get]
virtual float RepeatSize [get]
virtual int FloorAltitude [get]
virtual int LiquidLV [get]
virtual bool AllowLitter [get]
virtual bool AllowBlood [get]
virtual bool ShowPillar [get]
virtual bool AlwaysShowShadow [get]
virtual bool RepeatBlock [get]
virtual bool ForceRpeatBlock [get]
virtual bool CanBeHeld [get]
virtual bool EditorTile [get]
virtual bool IsFloodDoor [get]
virtual bool Invisible [get]
virtual bool IgnoreBuildRule [get]
virtual bool RenderWaterBlock [get]
virtual BaseTileSelector.SelectType SelectType [get]
virtual BaseTileSelector.BoxType BoxType [get]
virtual BaseTileSelector.HitType HitType [get]
virtual BlockRenderMode blockRenderMode [get]
bool IsMountBlock [get]
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Detailed Description
Definition at line 5 of file TileType.cs.
Member Enumeration Documentation
RampType
enum TileType.RampType
Enumerator
None
Full
Half
Definition at line 7 of file TileType.cs.
    {
        None,
        Full,
        Half
    }
Member Function Documentation
_HitTest()
HitResult TileType._HitTest (Point pos, Card target, bool canIgnore = true) inline
Definition at line 282 of file TileType.cs.
    {
        if ((EClass.debug.ignoreBuildRule || IgnoreBuildRule) && canIgnore)
        {
            return HitResult.Valid;
        }
        if (!CanBuiltOnArea && pos.HasArea)
        {
            return HitResult.Invalid;
        }
        if (pos.cell.IsTopWater)
        {
            if (!CanBuiltOnWater)
            {
                return HitResult.Invalid;
            }
        }
        else if (!CanBuiltOnFloor)
        {
            return HitResult.Invalid;
        }
        if (!CanBuiltOnBridge && pos.cell._bridge != 0)
        {
            return HitResult.Invalid;
        }
        if (target != null)
        {
            if (target.sourceCard.multisize && (pos.Installed != null || pos.cell.blocked || (pos.HasChara && pos.FirstChara.IsHostile(EClass.pc))))
            {
                return HitResult.Invalid;
            }
            if (pos.Installed != null && pos.Installed != target)
            {
                TileType tileType = pos.Installed.TileType;
                TileType tileType2 = target.TileType;
                if (!tileType.AllowMultiInstall || !tileType2.AllowMultiInstall)
                {
                    return HitResult.Invalid;
                }
            }
            if (!target.trait.CanBuiltAt(pos))
            {
                return HitResult.Invalid;
            }
        }
        else if (pos.Installed != null && !CanBuiltOnThing && !pos.cell.hasDoor)
        {
            return HitResult.Invalid;
        }
        if (pos.HasBlock)
        {
            if (!CanBuiltOnBlock && pos.sourceBlock.tileType.IsOccupyCell)
            {
                return HitResult.Invalid;
            }
            if (IsDoor && pos.HasWallOrFence && pos.cell.blockDir == 2)
            {
                return HitResult.Invalid;
            }
        }
        else if (IsDoor)
        {
            return HitResult.Invalid;
        }
        return HitTest(pos);
    }
References Cell._bridge, AllowMultiInstall, Cell.blockDir, Algorithms.WeightCell.blocked, Trait.CanBuiltAt(), CanBuiltOnArea, CanBuiltOnBlock, CanBuiltOnBridge, CanBuiltOnFloor, CanBuiltOnThing, CanBuiltOnWater, Point.cell, EClass.debug, Point.FirstChara, Point.HasArea, Point.HasBlock, Point.HasChara, Cell.hasDoor, Point.HasWallOrFence, HitTest(), CoreDebug.ignoreBuildRule, IgnoreBuildRule, Point.Installed, IsDoor, Chara.IsHostile(), Cell.IsTopWater, RenderRow.multisize, EClass.pc, Point.sourceBlock, Card.sourceCard, Card.TileType, and Card.trait.
Referenced by TaskBuild._GetHitResult(), Map._ValidateInstalled(), and TaskMoveInstalled.GetHitResult().
CanRotate()
virtual bool TileType.CanRotate (bool buildMode) inline virtual
Reimplemented in TileTypeRoof, and TileTypeSlope.
Definition at line 277 of file TileType.cs.
    {
        return true;
    }
GetDesiredDir()
virtual int TileType.GetDesiredDir (Point p, int d) inline virtual
Reimplemented in TileTypeVine, TileTypeWallHang, and TileTypeWallHangSign.
Definition at line 358 of file TileType.cs.
    {
        return -1;
    }
Referenced by AM_Build.OnRenderTile(), AM_MoveInstalled.OnRenderTile(), GenRoom.Populate(), and BiomeProfile.ClusterThing.TryCreate().
GetMountHeight()
virtual void TileType.GetMountHeight (ref Vector3 v, Point p, int d, Card target = null) inline virtual
Reimplemented in TileTypeWallHang, and TileTypeWallMount.
Definition at line 363 of file TileType.cs.
    {
        v += EClass.screen.tileMap.altitudeFix * target.altitude;
    }
Referenced by BaseTileMap.DrawTile(), TileMapElona.DrawTile(), and Card.RenderMarker().
GetRampFix()
Vector3 TileType.GetRampFix (int dir) inline
Definition at line 368 of file TileType.cs.
    {
        int num = (int)Ramp * 2 - 2 + ((dir > 1) ? 1 : 0);
        Vector3 vector = EClass.setting.render.rampFix[num];
        return new Vector3(vector.x * (float)((dir % 2 == 0) ? 1 : (-1)), vector.y, vector.z);
    }
References Ramp, GameSetting.RenderSetting.rampFix, GameSetting.render, and EClass.setting.
Referenced by BaseTileMap.DrawTile(), and BaseTileMap.GetThingPosition().
HitTest()
virtual HitResult TileType.HitTest (Point pos) inline protected virtual
Reimplemented in TileTypeBridgePillar, TileTypeRoof, TileTypeWallHang, and TileTypeWallMount.
Definition at line 349 of file TileType.cs.
    {
        if (pos.HasObj)
        {
            return HitResult.Warning;
        }
        return HitResult.Valid;
    }
References Point.HasObj.
Referenced by _HitTest().
Init()
static void TileType.Init () inline static
Definition at line 264 of file TileType.cs.
    {
        dict.Clear();
        FieldInfo[] fields = typeof(TileType).GetFields(BindingFlags.Static | BindingFlags.Public);
        foreach (FieldInfo fieldInfo in fields)
        {
            if (typeof(TileType).IsAssignableFrom(fieldInfo.FieldType))
            {
                dict[fieldInfo.Name] = (TileType)fieldInfo.GetValue(null);
            }
        }
    }
References dict.
Referenced by Core.Awake().
Member Data Documentation
Block
TileTypeBlock TileType.Block = new TileTypeBlock() static
Definition at line 18 of file TileType.cs.
Referenced by LayerEditHouse.RefreshBlockList().
BlockShip
TileTypeBlockShip TileType.BlockShip = new TileTypeBlockShip() static
Definition at line 20 of file TileType.cs.
Boat
TileTypeBoat TileType.Boat = new TileTypeBoat() static
Definition at line 106 of file TileType.cs.
Bridge
TileTypeBridge TileType.Bridge = new TileTypeBridge() static
Definition at line 58 of file TileType.cs.
BridgeDeco
TileTypeBridgeDeco TileType.BridgeDeco = new TileTypeBridgeDeco() static
Definition at line 60 of file TileType.cs.
BridgePillar
TileTypeBridgePillar TileType.BridgePillar = new TileTypeBridgePillar() static
Definition at line 62 of file TileType.cs.
Chasm
TileTypeChasm TileType.Chasm = new TileTypeChasm() static
Definition at line 104 of file TileType.cs.
dict
Dictionary<string, TileType> TileType.dict = new Dictionary<string, TileType>() static
Definition at line 112 of file TileType.cs.
Referenced by SourceCard.AddRow(), TileRow.Init(), and Init().
Door
TileTypeDoor TileType.Door = new TileTypeDoor() static
Definition at line 86 of file TileType.cs.
Referenced by Card.RenderMarker(), Recipe.Rotate(), and Card.Rotate().
Fence
TileTypeFence TileType.Fence = new TileTypeFence() static
Definition at line 44 of file TileType.cs.
FenceClosed
TileTypeFenceClosed TileType.FenceClosed = new TileTypeFenceClosed() static
Definition at line 46 of file TileType.cs.
Floor
TileTypeFloor TileType.Floor = new TileTypeFloor() static
Definition at line 48 of file TileType.cs.
FloorScaffold
TileTypeFloorScaffold TileType.FloorScaffold = new TileTypeFloorScaffold() static
Definition at line 50 of file TileType.cs.
FloorWater
TileTypeWater TileType.FloorWater = new TileTypeWater() static
Definition at line 52 of file TileType.cs.
FloorWaterDeep
TileTypeWaterDeep TileType.FloorWaterDeep = new TileTypeWaterDeep() static
Definition at line 56 of file TileType.cs.
FloorWaterShallow
TileTypeWaterShallow TileType.FloorWaterShallow = new TileTypeWaterShallow() static
Definition at line 54 of file TileType.cs.
Referenced by BaseTileMap.DrawTile().
HalfBlock
TileTypeHalfBlock TileType.HalfBlock = new TileTypeHalfBlock() static
Definition at line 24 of file TileType.cs.
Referenced by SourceBlock.Row.GetRenderParam().
Illumination
TileTypeIllumination TileType.Illumination = new TileTypeIllumination() static
Definition at line 80 of file TileType.cs.
Referenced by TraitDoor.CanClose(), and BaseTileMap.DrawTile().
InvisiBlock
TileTypeInvisibleBlock TileType.InvisiBlock = new TileTypeInvisibleBlock() static
Definition at line 16 of file TileType.cs.
Ladder
TileTypeLadder TileType.Ladder = new TileTypeLadder() static
Definition at line 34 of file TileType.cs.
Liquid
TileTypeLiquid TileType.Liquid = new TileTypeLiquid() static
Definition at line 108 of file TileType.cs.
Marker
TileTypeMarker TileType.Marker = new TileTypeMarker() static
Definition at line 110 of file TileType.cs.
None
TileTypeNone TileType.None = new TileTypeNone() static
Definition at line 14 of file TileType.cs.
Obj
TileTypeObj TileType.Obj = new TileTypeObj() static
Definition at line 66 of file TileType.cs.
Referenced by SourceCard.AddRow().
ObjBig
TileTypeObjBig TileType.ObjBig = new TileTypeObjBig() static
Definition at line 68 of file TileType.cs.
ObjCeil
TileTypeObjCeil TileType.ObjCeil = new TileTypeObjCeil() static
Definition at line 72 of file TileType.cs.
ObjFloat
TileTypeObjFloat TileType.ObjFloat = new TileTypeObjFloat() static
Definition at line 74 of file TileType.cs.
ObjHuge
TileTypeObjHuge TileType.ObjHuge = new TileTypeObjHuge() static
Definition at line 70 of file TileType.cs.
ObjWater
TileTypeObjWater TileType.ObjWater = new TileTypeObjWater() static
Definition at line 76 of file TileType.cs.
ObjWaterTop
TileTypeObjWaterTop TileType.ObjWaterTop = new TileTypeObjWaterTop() static
Definition at line 78 of file TileType.cs.
Paint
TileTypePaint TileType.Paint = new TileTypePaint() static
Definition at line 96 of file TileType.cs.
Pillar
TileTypePillar TileType.Pillar = new TileTypePillar() static
Definition at line 36 of file TileType.cs.
Referenced by RecipeManager.BuildList().
Road
TileTypeRoad TileType.Road = new TileTypeRoad() static
Definition at line 102 of file TileType.cs.
Roof
TileTypeRoof TileType.Roof = new TileTypeRoof() static
Definition at line 100 of file TileType.cs.
Referenced by LayerEditHouse.SetBoard().
Rooftop
TileTypeRooftop TileType.Rooftop = new TileTypeRooftop() static
Definition at line 30 of file TileType.cs.
Scaffold
TileTypeScaffold TileType.Scaffold = new TileTypeScaffold() static
Definition at line 32 of file TileType.cs.
Seed
TileTypeSeed TileType.Seed = new TileTypeSeed() static
Definition at line 82 of file TileType.cs.
Sky
TileTypeSky TileType.Sky = new TileTypeSky() static
Definition at line 64 of file TileType.cs.
Referenced by BaseTileMap.DrawTile(), ZonePreEnterDigStairs.Execute(), and Cell.Refresh().
Slope
TileTypeSlope TileType.Slope = new TileTypeSlope() static
Definition at line 22 of file TileType.cs.
Referenced by LayerEditHouse.SetBoard().
Stairs
TileTypeStairs TileType.Stairs = new TileTypeStairs() static
Definition at line 26 of file TileType.cs.
Referenced by LayerEditHouse.SetBoard().
StairsHalf
TileTypeStairs TileType.StairsHalf = new TileTypeStairsHalf() static
Definition at line 28 of file TileType.cs.
Tree
TileTypeTree TileType.Tree = new TileTypeTree() static
Definition at line 84 of file TileType.cs.
Vine
TileTypeVine TileType.Vine = new TileTypeVine() static
Definition at line 92 of file TileType.cs.
Wall
TileTypeWall TileType.Wall = new TileTypeWall() static
Definition at line 40 of file TileType.cs.
WallHang
TileTypeWallHang TileType.WallHang = new TileTypeWallHang() static
Definition at line 88 of file TileType.cs.
WallHangSign
TileTypeWallHangSign TileType.WallHangSign = new TileTypeWallHangSign() static
Definition at line 90 of file TileType.cs.
WallMount
TileTypeWallMount TileType.WallMount = new TileTypeWallMount() static
Definition at line 94 of file TileType.cs.
WallOpen
TileTypeWallOpen TileType.WallOpen = new TileTypeWallOpen() static
Definition at line 42 of file TileType.cs.
Waterfall
TileTypeWaterfall TileType.Waterfall = new TileTypeWaterfall() static
Definition at line 38 of file TileType.cs.
Window
TileTypeWindow TileType.Window = new TileTypeWindow() static
Definition at line 98 of file TileType.cs.
Property Documentation
AllowBlood
virtual bool TileType.AllowBlood get
Definition at line 232 of file TileType.cs.
AllowLitter
virtual bool TileType.AllowLitter get
Definition at line 230 of file TileType.cs.
AllowMultiInstall
virtual bool TileType.AllowMultiInstall get
Definition at line 214 of file TileType.cs.
Referenced by _HitTest().
AllowObj
virtual bool TileType.AllowObj get
Definition at line 212 of file TileType.cs.
Referenced by AI_HaulResource.Run().
AltitudeAsDir
virtual bool TileType.AltitudeAsDir get
Definition at line 200 of file TileType.cs.
Referenced by Recipe.Build(), AM_Build.OnRenderTile(), Recipe.Rotate(), AM_Build.SetAltitude(), AM_Build.TopHeight(), and HotItemHeld.TrySetAct().
AlwaysShowShadow
virtual bool TileType.AlwaysShowShadow get
Definition at line 236 of file TileType.cs.
Referenced by BaseTileMap.DrawTile().
blockRenderMode
virtual BlockRenderMode TileType.blockRenderMode get
Definition at line 260 of file TileType.cs.
Referenced by BaseTileMap.DrawTile().
BoxType
virtual BaseTileSelector.BoxType TileType.BoxType get
Definition at line 256 of file TileType.cs.
Referenced by Recipe.GetBoxType().
CanBeHeld
virtual bool TileType.CanBeHeld get
Definition at line 242 of file TileType.cs.
Referenced by HotItemNoItem._TrySetAct().
CanBuiltOnArea
virtual bool TileType.CanBuiltOnArea get
Definition at line 180 of file TileType.cs.
Referenced by _HitTest().
CanBuiltOnBlock
virtual bool TileType.CanBuiltOnBlock get
Definition at line 186 of file TileType.cs.
Referenced by _HitTest(), and AI_HaulResource.Run().
CanBuiltOnBridge
virtual bool TileType.CanBuiltOnBridge get
Definition at line 192 of file TileType.cs.
Referenced by _HitTest().
CanBuiltOnFloor
virtual bool TileType.CanBuiltOnFloor get
Definition at line 190 of file TileType.cs.
Referenced by _HitTest().
CanBuiltOnThing
virtual bool TileType.CanBuiltOnThing get
Definition at line 184 of file TileType.cs.
Referenced by _HitTest().
CanBuiltOnWater
virtual bool TileType.CanBuiltOnWater get
Definition at line 182 of file TileType.cs.
Referenced by _HitTest().
CanInstaComplete
virtual bool TileType.CanInstaComplete get
Definition at line 194 of file TileType.cs.
Referenced by HitSummary.Execute(), and AM_Build.ForcedInstaComplete().
CanSpawnOnWater
virtual bool TileType.CanSpawnOnWater get
Definition at line 168 of file TileType.cs.
CanStack
virtual bool TileType.CanStack get
Definition at line 116 of file TileType.cs.
Referenced by BaseTileMap.DrawTile(), TileMapElona.DrawTile(), and BaseTileMap.GetThingPosition().
CastAmbientShadow
virtual bool TileType.CastAmbientShadow get
Definition at line 176 of file TileType.cs.
CastAmbientShadowBack
virtual bool TileType.CastAmbientShadowBack get
Definition at line 178 of file TileType.cs.
CastShadowBack
virtual bool TileType.CastShadowBack get
Definition at line 174 of file TileType.cs.
CastShadowSelf
virtual bool TileType.CastShadowSelf get
Definition at line 172 of file TileType.cs.
ChangeBlockDir
virtual bool TileType.ChangeBlockDir get
Definition at line 118 of file TileType.cs.
Referenced by Recipe.Build().
EditorTile
virtual bool TileType.EditorTile get
Definition at line 244 of file TileType.cs.
Referenced by BuildMenu.RefreshCategory().
FloorAltitude
virtual int TileType.FloorAltitude get
Definition at line 226 of file TileType.cs.
FloorHeight
virtual float TileType.FloorHeight get
Definition at line 222 of file TileType.cs.
ForceRpeatBlock
virtual bool TileType.ForceRpeatBlock get
Definition at line 240 of file TileType.cs.
Referenced by BaseTileMap.DrawTile().
FreeStyle
virtual bool TileType.FreeStyle get
Definition at line 216 of file TileType.cs.
HitType
virtual BaseTileSelector.HitType TileType.HitType get
Definition at line 258 of file TileType.cs.
IgnoreBuildRule
virtual bool TileType.IgnoreBuildRule get
Definition at line 250 of file TileType.cs.
Referenced by _HitTest().
Invisible
virtual bool TileType.Invisible get
Definition at line 248 of file TileType.cs.
IsBlockLiquid
virtual bool TileType.IsBlockLiquid get
Definition at line 152 of file TileType.cs.
IsBlockMount
virtual bool TileType.IsBlockMount get
Definition at line 158 of file TileType.cs.
Referenced by UIInspector.DrawHighlight().
IsBlockPass
virtual bool TileType.IsBlockPass get
Definition at line 144 of file TileType.cs.
Referenced by Recipe.Build(), Map.DestroyObj(), and TaskBuild.GetHitResult().
IsBlockSight
virtual bool TileType.IsBlockSight get
Definition at line 148 of file TileType.cs.
IsBridge
virtual bool TileType.IsBridge get
Definition at line 132 of file TileType.cs.
IsDeepWater
virtual bool TileType.IsDeepWater get
Definition at line 156 of file TileType.cs.
IsDoor
virtual bool TileType.IsDoor get
Definition at line 188 of file TileType.cs.
Referenced by _HitTest(), and TaskBuild.GetHitResult().
IsFence
virtual bool TileType.IsFence get
Definition at line 162 of file TileType.cs.
Referenced by BaseTileMap.DrawTile(), and Room.Refresh().
IsFloodBlock
virtual bool TileType.IsFloodBlock get
Definition at line 164 of file TileType.cs.
IsFloodDoor
virtual bool TileType.IsFloodDoor get
Definition at line 246 of file TileType.cs.
IsFloor
virtual bool TileType.IsFloor get
Definition at line 130 of file TileType.cs.
IsFloorOrBridge
virtual bool TileType.IsFloorOrBridge get
Definition at line 126 of file TileType.cs.
IsFullBlock
virtual bool TileType.IsFullBlock get
Definition at line 160 of file TileType.cs.
Referenced by BaseTileMap.DrawTile().
IsLadder
virtual bool TileType.IsLadder get
Definition at line 142 of file TileType.cs.
IsMountBlock
bool TileType.IsMountBlock get
Definition at line 262 of file TileType.cs.
IsOccupyCell
virtual bool TileType.IsOccupyCell get
Definition at line 146 of file TileType.cs.
IsOpenSight
virtual bool TileType.IsOpenSight get
Definition at line 150 of file TileType.cs.
IsPlayFootSound
virtual bool TileType.IsPlayFootSound get
Definition at line 166 of file TileType.cs.
IsRamp
bool TileType.IsRamp get
Definition at line 138 of file TileType.cs.
Referenced by BaseTileMap.DrawTile(), BaseTileMap.GetThingPosition(), and SourceBlock.Row.OnInit().
IsSkipFloor
virtual bool TileType.IsSkipFloor get
Definition at line 122 of file TileType.cs.
IsSkipLowBlock
virtual bool TileType.IsSkipLowBlock get
Definition at line 120 of file TileType.cs.
Referenced by BaseTileMap.DrawTile(), and TileMapElona.DrawTile().
IsUseBlockDir
virtual bool TileType.IsUseBlockDir get
Definition at line 124 of file TileType.cs.
Referenced by BaseTileMap.DrawTile(), and TileMapElona.DrawTile().
IsWall
virtual bool TileType.IsWall get
Definition at line 128 of file TileType.cs.
Referenced by BaseTileMap.DrawTile(), and Room.Refresh().
IsWallOrFence
virtual bool TileType.IsWallOrFence get
Definition at line 134 of file TileType.cs.
Referenced by Recipe.OnRenderMarker().
IsWallOrFullBlock
virtual bool TileType.IsWallOrFullBlock get
Definition at line 136 of file TileType.cs.
IsWater
virtual bool TileType.IsWater get
Definition at line 154 of file TileType.cs.
Referenced by Chara._Move(), and Recipe.OnRenderMarker().
IsWaterTop
virtual bool TileType.IsWaterTop get
Definition at line 170 of file TileType.cs.
Referenced by BaseTileMap.DrawTile().
LangPlaceType
virtual string TileType.LangPlaceType get
Definition at line 114 of file TileType.cs.
Referenced by UIRecipeInfo.Refresh(), and UICardInfo.SetRecipe().
LiquidLV
virtual int TileType.LiquidLV get
Definition at line 228 of file TileType.cs.
MaxAltitude
virtual int TileType.MaxAltitude get
Definition at line 198 of file TileType.cs.
Referenced by Card.ChangeAltitude(), AM_MoveInstalled.InputWheel(), and Recipe.Rotate().
MinAltitude
virtual int TileType.MinAltitude get
Definition at line 196 of file TileType.cs.
Referenced by AM_Build.FixBridge().
MountHeight
virtual float TileType.MountHeight get
Definition at line 220 of file TileType.cs.
Ramp
virtual RampType TileType.Ramp get
Definition at line 140 of file TileType.cs.
Referenced by GetRampFix().
RemoveOnFloorChange
virtual bool TileType.RemoveOnFloorChange get
Definition at line 210 of file TileType.cs.
RenderWaterBlock
virtual bool TileType.RenderWaterBlock get
Definition at line 252 of file TileType.cs.
RepeatBlock
virtual bool TileType.RepeatBlock get
Definition at line 238 of file TileType.cs.
Referenced by BaseTileMap.DrawTile().
RepeatSize
virtual float TileType.RepeatSize get
Definition at line 224 of file TileType.cs.
Referenced by Recipe.OnRenderMarker().
SelectType
virtual BaseTileSelector.SelectType TileType.SelectType get
Definition at line 254 of file TileType.cs.
Referenced by AM_Build.HitTest().
ShowPillar
virtual bool TileType.ShowPillar get
Definition at line 234 of file TileType.cs.
slopeHeight
virtual byte TileType.slopeHeight get
Definition at line 218 of file TileType.cs.
Referenced by Cell.Refresh().
UseHangZFix
virtual bool TileType.UseHangZFix get
Definition at line 206 of file TileType.cs.
Referenced by BaseTileMap.DrawTile().
UseLowBlock
virtual bool TileType.UseLowBlock get
Definition at line 208 of file TileType.cs.
UseLowWallTiles
virtual bool TileType.UseLowWallTiles get
Definition at line 202 of file TileType.cs.
Referenced by BaseTileMap.DrawTile().
UseMountHeight
virtual bool TileType.UseMountHeight get
Definition at line 204 of file TileType.cs.
Referenced by CardRenderer.Draw(), BaseTileMap.DrawTile(), TileMapElona.DrawTile(), BaseTileMap.GetThingPosition(), GenRoom.Populate(), and Card.RenderMarker().
The documentation for this class was generated from the following file:
Elin/TileType.cs