Elin Decompiled Documentation: Biography Class Reference
Biography Class Reference
Public Member Functions
string TextAge (Chara c)
int GetOriginalAge (Chara c)
void Generate (Chara c)
void RerollBio (Chara c, int ageIndex=0, bool keepParent=false)
void GenerateBirthday (Chara c, int ageIndex=0)
void GenerateAppearance (Chara c)
void GenerateDad ()
void GenerateMom ()
void SetGender (int g)
void SetPortrait (Chara c)
string TextBio (Chara c)
string TextBio2 (Chara c)
string TextBirthDate (Chara c, bool _age=false)
string TextAppearance ()
Public Attributes
int[] ints = new int[20]
string[] strs = new string[3]
int[] personalities = new int[5]
Static Public Attributes
static string[] idFemale = new string[5] { "shojo", "sister", "sister_cat", "younglady", "sister_undead" }
Static Public Attributes inherited from EClass
static Core core
Properties
string idLike [get, set]
int gender [get, set]
int weight [get, set]
int height [get, set]
int birthDay [get, set]
int birthMonth [get, set]
int birthYear [get, set]
int idHome [get, set]
int idDad [get, set]
int idMom [get, set]
int idLoc [get, set]
int idAdvDad [get, set]
int idAdvMom [get, set]
int idHobby [get, set]
int stability [get, set]
int law [get, set]
int affection [get, set]
int dominance [get, set]
int extroversion [get, set]
int idInterest [get, set]
string nameHome [get]
string nameLoc [get]
string nameDad [get]
string nameMom [get]
string nameBirthplace [get]
int age [get, set]
bool IsUnderAge [get]
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Private Member Functions
int RndBio (string group)
string StrBio (int id)
Additional Inherited Members
Static Public Member Functions inherited from EClass
static int rnd (int a)
static int curve (int a, int start, int step, int rate=75)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Detailed Description
Definition at line 4 of file Biography.cs.
Member Function Documentation
Generate()
void Biography.Generate (Chara c) inline
Definition at line 308 of file Biography.cs.
    {
        string bio = c.source.bio;
        _ = c.Chara.race;
        stability = Rand.rndNormal(100);
        law = Rand.rndNormal(100);
        affection = Rand.rndNormal(100);
        dominance = Rand.rndNormal(100);
        extroversion = Rand.rndNormal(100);
        idInterest = EClass.rnd(Enum.GetNames(typeof(Interest)).Length);
        if (idFemale.Contains(c.id) || c.race.id == "roran")
        {
            SetGender(1);
        }
        else
        {
            SetGender(Gender.GetRandom());
        }
        RerollBio(c);
        c.SetRandomTone();
        c.SetRandomTalk();
        bool flag = c.IsHuman;
        if (!bio.IsEmpty())
        {
            string[] array = bio.Split('/');
            SetGender((array[0] == "f") ? 1 : 2);
            if (array.Length > 1)
            {
                if (!c.source.HasTag(CTAG.randomPortrait))
                {
                    flag = false;
                }
                age = int.Parse(array[1]);
                c.pccData = IO.LoadFile<PCCData>(CorePath.packageCore + "Data/PCC/" + c.id + ".txt");
            }
            if (array.Length > 2)
            {
                height = int.Parse(array[2]);
            }
            if (array.Length > 3)
            {
                weight = int.Parse(array[3]);
            }
            if (array.Length > 4)
            {
                c.c_idTone = array[4];
            }
            if (array.Length > 5 && !array[5].IsEmpty())
            {
                c.c_idTalk = array[5];
            }
        }
        if (c.trait is TraitGuildClerk)
        {
            flag = true;
        }
        if (flag && !c.HasTag(CTAG.noPortrait))
        {
            SetPortrait(c);
        }
        if (c.id == "prostitute" && age < 15)
        {
            age = 15;
        }
        SourceThing.Row row = EClass.sources.things.rows.RandomItem();
        idLike = row.id;
        idHobby = EClass.sources.elements.hobbies.RandomItem().id;
    }
References affection, age, Card.Chara, dominance, SourceManager.elements, extroversion, Gender.GetRandom(), Card.HasTag(), height, SourceElement.hobbies, Card.id, CardRow.id, idFemale, idHobby, idInterest, idLike, Chara.IsHuman, law, Chara.race, RerollBio(), EClass.rnd(), Rand.rndNormal(), SetGender(), SetPortrait(), Card.SetRandomTalk(), Card.SetRandomTone(), Chara.source, EClass.sources, stability, SourceManager.things, Chara.trait, and weight.
Referenced by Chara.OnCreate().
GenerateAppearance()
void Biography.GenerateAppearance (Chara c) inline
Definition at line 408 of file Biography.cs.
    {
        SourceRace.Row race = c.race;
        height = race.height + EClass.rnd(race.height / 5 + 1) - EClass.rnd(race.height / 5 + 1);
        weight = height * height * (EClass.rnd(6) + 18) / 10000;
    }
References height, SourceRace.Row.height, Chara.race, EClass.rnd(), and weight.
Referenced by RerollBio().
GenerateBirthday()
void Biography.GenerateBirthday (Chara c, int ageIndex = 0) inline
Definition at line 390 of file Biography.cs.
    {
        SourceRace.Row race = c.race;
        int num = race.age[0];
        int num2 = race.age[1];
        if (ageIndex != 0)
        {
            int num3 = (num2 - num) / 4;
            age = Rand.Range(num + num3 * (ageIndex - 1), num + num3 * ageIndex);
        }
        else
        {
            age = Rand.Range(num, num2);
        }
        birthDay = EClass.rnd(30) + 1;
        birthMonth = EClass.rnd(12) + 1;
    }
References age, SourceRace.Row.age, birthDay, birthMonth, Chara.race, Rand.Range(), and EClass.rnd().
Referenced by RerollBio().
GenerateDad()
void Biography.GenerateDad () inline
Definition at line 415 of file Biography.cs.
    {
        idDad = RndBio("parent");
        idAdvDad = RndBio("adv");
    }
References idAdvDad, idDad, and RndBio().
Referenced by RerollBio().
GenerateMom()
void Biography.GenerateMom () inline
Definition at line 421 of file Biography.cs.
    {
        idMom = RndBio("parent");
        idAdvMom = RndBio("adv");
    }
References idAdvMom, idMom, and RndBio().
Referenced by RerollBio().
GetOriginalAge()
int Biography.GetOriginalAge (Chara c) inline
Definition at line 298 of file Biography.cs.
    {
        string[] array = c.source.bio.Split('/');
        if (array.Length > 1)
        {
            return int.Parse(array[1]);
        }
        return age;
    }
References age, and Chara.source.
Referenced by TextAge().
RerollBio()
void Biography.RerollBio (Chara c, int ageIndex = 0, bool keepParent = false) inline
Definition at line 377 of file Biography.cs.
    {
        GenerateBirthday(c, ageIndex);
        GenerateAppearance(c);
        if (!keepParent)
        {
            GenerateDad();
            GenerateMom();
            idHome = RndBio("home");
            idLoc = RndBio("loc");
        }
    }
References GenerateAppearance(), GenerateBirthday(), GenerateDad(), GenerateMom(), idHome, idLoc, and RndBio().
Referenced by Generate(), and UICharaMaker.RerollBio().
RndBio()
int Biography.RndBio (string group) inline private
Definition at line 427 of file Biography.cs.
    {
        return WordGen.GetID(group);
    }
Referenced by GenerateDad(), GenerateMom(), and RerollBio().
SetGender()
void Biography.SetGender (int g) inline
Definition at line 450 of file Biography.cs.
    {
        gender = g;
        if (gender > 2)
        {
            gender = 0;
        }
    }
References gender.
Referenced by Card.ApplyBacker(), Chara.ApplyEditorTags(), Generate(), UICharaMaker.ListGender(), and AM_MoveInstalled.SetTarget().
SetPortrait()
void Biography.SetPortrait (Chara c) inline
Definition at line 459 of file Biography.cs.
    {
        string id = c.id;
        if (!(id == "shojo"))
        {
            if (id == "sister")
            {
                c.c_idPortrait = Portrait.GetRandomPortrait("special_f-littlesister");
            }
            else
            {
                c.c_idPortrait = Portrait.GetRandomPortrait(gender, c.GetIdPortraitCat());
            }
        }
        else
        {
            c.c_idPortrait = Portrait.GetRandomPortrait("special_f-littlegirl");
        }
    }
References gender, Chara.GetIdPortraitCat(), Portrait.GetRandomPortrait(), and Card.id.
Referenced by Card.ApplyBacker(), and Generate().
StrBio()
string Biography.StrBio (int id) inline private
Definition at line 432 of file Biography.cs.
    {
        object obj;
        if (!EClass.sources.langWord.map.ContainsKey(id))
        {
            obj = id.ToString();
            if (obj == null)
            {
                return "";
            }
        }
        else
        {
            obj = EClass.sources.langWord.map[id].GetText().Split(',')[0];
        }
        return (string)obj;
    }
References SourceManager.langWord, and EClass.sources.
TextAge()
string Biography.TextAge (Chara c) inline
Definition at line 280 of file Biography.cs.
    {
        object obj;
        if (age < 1000)
        {
            obj = (c.IsUnique ? GetOriginalAge(c) : age).ToString();
            if (obj == null)
            {
                return "";
            }
        }
        else
        {
            obj = "???";
        }
        return (string)obj;
    }
References age, and GetOriginalAge().
Referenced by Person.GetDramaTitle(), ButtonChara.SetChara(), TextBio(), and TextBirthDate().
TextAppearance()
string Biography.TextAppearance () inline
Definition at line 494 of file Biography.cs.
    {
        return Lang.Parse("heightWeight", height.ToString() ?? "", weight.ToString() ?? "");
    }
References height, Lang.Parse(), and weight.
Referenced by UICharaMaker.Refresh().
TextBio()
string Biography.TextBio (Chara c) inline
Definition at line 479 of file Biography.cs.
    {
        return c.race.GetText().ToTitleCase(wholeText: true) + " " + Lang.Parse("age", TextAge(c)) + " " + Lang._gender(gender);
    }
References Lang._gender(), gender, Lang.Parse(), Chara.race, and TextAge().
Referenced by WindowChara.RefreshNote(), WindowChara.RefreshProfile(), and ItemGachaResult.SetChara().
TextBio2()
string Biography.TextBio2 (Chara c) inline
Definition at line 484 of file Biography.cs.
    {
        return Lang.Parse("heightWeight", height.ToString() ?? "", weight.ToString() ?? "") + " " + ((c.material.alias == "meat") ? "" : c.material.GetName().ToTitleCase(wholeText: true));
    }
References height, Card.material, Lang.Parse(), and weight.
Referenced by WindowChara.RefreshNote(), and WindowChara.RefreshProfile().
TextBirthDate()
string Biography.TextBirthDate (Chara c, bool _age = false) inline
Definition at line 489 of file Biography.cs.
    {
        return Lang.Parse("birthText", (birthYear >= 0) ? (birthYear.ToString() ?? "") : "???", birthMonth.ToString() ?? "", birthDay.ToString() ?? "") + (_age ? (" (" + Lang.Parse("age", TextAge(c)) + ")") : "");
    }
References birthDay, birthMonth, birthYear, Lang.Parse(), and TextAge().
Referenced by UICharaMaker.Refresh(), and WindowChara.RefreshInfo().
Member Data Documentation
idFemale
string [] Biography.idFemale = new string[5] { "shojo", "sister", "sister_cat", "younglady", "sister_undead" } static
Definition at line 6 of file Biography.cs.
Referenced by Generate().
ints
int [] Biography.ints = new int[20]
Definition at line 9 of file Biography.cs.
personalities
int [] Biography.personalities = new int[5]
Definition at line 14 of file Biography.cs.
strs
string [] Biography.strs = new string[3]
Definition at line 12 of file Biography.cs.
Property Documentation
affection
int Biography.affection get set
Definition at line 208 of file Biography.cs.
    {
        get
        {
            return ints[16];
        }
        set
        {
            ints[16] = value;
        }
    }
Referenced by Generate().
age
int Biography.age get set
Definition at line 266 of file Biography.cs.
    {
        get
        {
            return EClass.world.date.year - birthYear;
        }
        set
        {
            birthYear = EClass.world.date.year - value;
        }
    }
Referenced by Generate(), GenerateBirthday(), GetOriginalAge(), and TextAge().
birthDay
int Biography.birthDay get set
Definition at line 64 of file Biography.cs.
    {
        get
        {
            return ints[4];
        }
        set
        {
            ints[4] = value;
        }
    }
Referenced by GenerateBirthday(), Player.GetBackgroundText(), and TextBirthDate().
birthMonth
int Biography.birthMonth get set
Definition at line 76 of file Biography.cs.
    {
        get
        {
            return ints[5];
        }
        set
        {
            ints[5] = value;
        }
    }
Referenced by GenerateBirthday(), Player.GetBackgroundText(), and TextBirthDate().
birthYear
int Biography.birthYear get set
Definition at line 88 of file Biography.cs.
    {
        get
        {
            return ints[6];
        }
        set
        {
            ints[6] = value;
        }
    }
Referenced by Player.GetBackgroundText(), and TextBirthDate().
dominance
int Biography.dominance get set
Definition at line 220 of file Biography.cs.
    {
        get
        {
            return ints[17];
        }
        set
        {
            ints[17] = value;
        }
    }
Referenced by Generate().
extroversion
int Biography.extroversion get set
Definition at line 232 of file Biography.cs.
    {
        get
        {
            return ints[18];
        }
        set
        {
            ints[18] = value;
        }
    }
Referenced by Generate().
gender
int Biography.gender get set
Definition at line 28 of file Biography.cs.
    {
        get
        {
            return ints[0];
        }
        set
        {
            ints[0] = value;
        }
    }
Referenced by GameLang.ConvertDrama(), Person.GetDramaTitle(), Faction.IsWearingPanty(), UICharaMaker.ListGender(), UICharaMaker.Refresh(), Person.SetChara(), ButtonChara.SetChara(), SetGender(), SetPortrait(), and TextBio().
height
int Biography.height get set
Definition at line 52 of file Biography.cs.
    {
        get
        {
            return ints[3];
        }
        set
        {
            ints[3] = value;
        }
    }
Referenced by Generate(), GenerateAppearance(), TextAppearance(), and TextBio2().
idAdvDad
int Biography.idAdvDad get set
Definition at line 148 of file Biography.cs.
    {
        get
        {
            return ints[11];
        }
        set
        {
            ints[11] = value;
        }
    }
Referenced by GenerateDad().
idAdvMom
int Biography.idAdvMom get set
Definition at line 160 of file Biography.cs.
    {
        get
        {
            return ints[12];
        }
        set
        {
            ints[12] = value;
        }
    }
Referenced by GenerateMom().
idDad
int Biography.idDad get set
Definition at line 112 of file Biography.cs.
    {
        get
        {
            return ints[8];
        }
        set
        {
            ints[8] = value;
        }
    }
Referenced by GenerateDad().
idHobby
int Biography.idHobby get set
Definition at line 172 of file Biography.cs.
    {
        get
        {
            return ints[13];
        }
        set
        {
            ints[13] = value;
        }
    }
Referenced by Generate(), and WindowChara.RefreshInfo().
idHome
int Biography.idHome get set
Definition at line 100 of file Biography.cs.
    {
        get
        {
            return ints[7];
        }
        set
        {
            ints[7] = value;
        }
    }
Referenced by RerollBio().
idInterest
int Biography.idInterest get set
Definition at line 244 of file Biography.cs.
    {
        get
        {
            return ints[19];
        }
        set
        {
            ints[19] = value;
        }
    }
Referenced by Generate(), and DramaCustomSequence.GetRumor().
idLike
string Biography.idLike get set
Definition at line 16 of file Biography.cs.
    {
        get
        {
            return strs[0];
        }
        set
        {
            strs[0] = value;
        }
    }
Referenced by Generate(), and WindowChara.RefreshInfo().
idLoc
int Biography.idLoc get set
Definition at line 136 of file Biography.cs.
    {
        get
        {
            return ints[10];
        }
        set
        {
            ints[10] = value;
        }
    }
Referenced by RerollBio().
idMom
int Biography.idMom get set
Definition at line 124 of file Biography.cs.
    {
        get
        {
            return ints[9];
        }
        set
        {
            ints[9] = value;
        }
    }
Referenced by GenerateMom().
IsUnderAge
bool Biography.IsUnderAge get
Definition at line 278 of file Biography.cs.
Referenced by DramaCustomSequence.Build().
law
int Biography.law get set
Definition at line 196 of file Biography.cs.
    {
        get
        {
            return ints[15];
        }
        set
        {
            ints[15] = value;
        }
    }
Referenced by Generate().
nameBirthplace
string Biography.nameBirthplace get
Definition at line 264 of file Biography.cs.
Referenced by UICharaMaker.Refresh(), and WindowChara.RefreshInfo().
nameDad
string Biography.nameDad get
Definition at line 260 of file Biography.cs.
Referenced by Player.GetBackgroundText(), UICharaMaker.Refresh(), and WindowChara.RefreshInfo().
nameHome
string Biography.nameHome get
Definition at line 256 of file Biography.cs.
Referenced by Player.GetBackgroundText().
nameLoc
string Biography.nameLoc get
Definition at line 258 of file Biography.cs.
Referenced by Player.GetBackgroundText().
nameMom
string Biography.nameMom get
Definition at line 262 of file Biography.cs.
Referenced by Player.GetBackgroundText(), UICharaMaker.Refresh(), and WindowChara.RefreshInfo().
stability
int Biography.stability get set
Definition at line 184 of file Biography.cs.
    {
        get
        {
            return ints[14];
        }
        set
        {
            ints[14] = value;
        }
    }
Referenced by Generate().
weight
int Biography.weight get set
Definition at line 40 of file Biography.cs.
    {
        get
        {
            return ints[2];
        }
        set
        {
            ints[2] = value;
        }
    }
Referenced by Generate(), GenerateAppearance(), TextAppearance(), and TextBio2().
The documentation for this class was generated from the following file:
Elin/Biography.cs