Elin Decompiled Documentation: HotItemActionSleep Class Reference
HotItemActionSleep Class Reference
Public Member Functions
override void Perform ()
Public Member Functions inherited from HotAction
override void OnClick (ButtonHotItem b, Hotbar h)
virtual void Perform ()
override void OnShowContextMenu (UIContextMenu m)
Public Member Functions inherited from HotItem
string TextHotkey ()
virtual void OnClick (ButtonHotItem b, Hotbar h)
virtual void OnRightClick (ButtonHotItem b)
virtual bool CanAutoFire (Chara tg)
virtual void OnSetCurrentItem ()
virtual void OnUnsetCurrentItem ()
virtual void OnUnselect ()
virtual void SetImage (Image icon)
virtual bool TrySetAct (ActPlan p)
virtual void OnMarkMapHighlights ()
virtual void OnRenderTile (Point point, HitResult result, int dir)
Public Member Functions inherited from UIButton.Item
virtual Sprite GetSprite ()
virtual Sprite GetSprite (bool highlight)
virtual bool ShouldHighlight ()
virtual void OnAddedToBar ()
virtual void OnShowContextMenu (UIContextMenu m)
virtual void OnHover (UIButton b)
virtual void OnClick (UIButton b)
virtual void OnSetItem (UIButton b)
virtual void SetSubText (UIText t)
Properties
override string Id [get]
override bool CanName [get]
Properties inherited from HotAction
Color bgColor [get, set]
override Color SpriteColor [get]
virtual string Id [get]
virtual bool CanChangeIconColor [get]
virtual bool CanName [get]
override string Name [get]
override string pathSprite [get]
Properties inherited from HotItem
override Sprite SpriteHighlight [get]
override bool IsSelectable [get]
override string TextTip [get]
virtual Thing RenderThing [get]
virtual Thing Thing [get]
virtual Thing Tool [get]
virtual bool IsTool [get]
virtual bool LookAtMouse [get]
virtual bool IsGameAction [get]
virtual bool UseUIObjMaterial [get]
Properties inherited from UIButton.Item
virtual string TextTip [get]
virtual string Name [get]
virtual Sprite SpriteHighlight [get]
virtual string pathSprite [get]
virtual bool IsSelectable [get]
virtual bool AdjustImageSize [get]
virtual bool UseIconForHighlight [get]
virtual bool KeepVisibleWhenHighlighted [get]
virtual Color SpriteColor [get]
virtual Vector3 SpriteScale [get]
virtual bool Hidden [get]
virtual Transition Transition [get]
Additional Inherited Members
Public Attributes inherited from HotAction
int _bgColor
string text
Public Attributes inherited from HotItem
ButtonHotItem button
Hotbar hotbar
bool disabled
Public Attributes inherited from UIButton.Item
bool always
Detailed Description
Definition at line 1 of file HotItemActionSleep.cs.
Member Function Documentation
Perform()
override void HotItemActionSleep.Perform () inline virtual
Reimplemented from HotAction.
Definition at line 7 of file HotItemActionSleep.cs.
    {
        if (!EClass.pc.CanSleep())
        {
            Msg.Say((EClass._zone.events.GetEvent<ZoneEventQuest>() != null) ? "badidea" : "notSleepy");
            return;
        }
        if (EClass.player.returnInfo != null || EClass.pc.isRestrained)
        {
            Msg.Say("badidea");
            return;
        }
        Thing thing = EClass.pc.things.Find<TraitBed>();
        if (thing == null)
        {
            Msg.Say("noBedFound".langGame());
            SE.Beep();
            return;
        }
        Thing thing2 = EClass.pc.things.Find<TraitPillow>();
        ItemPosition posBed = ItemPosition.Get(thing);
        ItemPosition posPillow = ItemPosition.Get(thing2);
        EClass._zone.AddCard(thing, EClass.pc.pos).Install();
        if (thing2 != null)
        {
            EClass._zone.AddCard(thing2, EClass.pc.pos).Install();
        }
        EClass.pc.Sleep(thing, thing2, pickup: true, posBed, posPillow);
    }
References EClass._zone, Zone.AddCard(), Chara.CanSleep(), Zone.events, ThingContainer.Find(), ItemPosition.Get(), Card.Install(), Card.isRestrained, EClass.pc, EClass.player, Card.pos, Player.returnInfo, Msg.Say(), Chara.Sleep(), and Card.things.
Property Documentation
CanName
override bool HotItemActionSleep.CanName get
Definition at line 5 of file HotItemActionSleep.cs.
Id
override string HotItemActionSleep.Id get
Definition at line 3 of file HotItemActionSleep.cs.
The documentation for this class was generated from the following file:
Elin/HotItemActionSleep.cs