Elin Decompiled Documentation: SourceHomeResource Class Reference
SourceHomeResource Class Reference
Classes
class Row
Public Member Functions
override Row CreateRow ()
override Row CreateRowByMapping (IReadOnlyDictionary< string, int > mapping)
override void SetRow (Row r)
override IReadOnlyDictionary< string, int > GetRowMapping ()
override IReadOnlyDictionary< string, string > GetTypeMapping ()
Public Member Functions inherited from SourceDataString< SourceHomeResource.Row >
override T GetRow (string id)
Static Public Attributes
static readonly IReadOnlyDictionary< string, int > RowMapping
static readonly IReadOnlyDictionary< string, string > TypeMapping
Detailed Description
Definition at line 4 of file SourceHomeResource.cs.
Member Function Documentation
CreateRow()
override Row SourceHomeResource.CreateRow () inline
Definition at line 60 of file SourceHomeResource.cs.
    {
        return new Row
        {
            id = SourceData.GetString(0),
            name_JP = SourceData.GetString(1),
            name = SourceData.GetString(2),
            expMod = SourceData.GetInt(3),
            maxLv = SourceData.GetInt(4),
            reward = SourceData.GetStringArray(5),
            detail_JP = SourceData.GetString(6),
            detail = SourceData.GetString(7)
        };
    }
References SourceData< T, T2 >.GetInt(), SourceData< T, T2 >.GetString(), and SourceData< T, T2 >.GetStringArray().
CreateRowByMapping()
override Row SourceHomeResource.CreateRowByMapping (IReadOnlyDictionary< string, int > mapping) inline
Definition at line 75 of file SourceHomeResource.cs.
    {
        return new Row
        {
            id = SourceData.GetString(mapping["id"]),
            name_JP = SourceData.GetString(mapping["name_JP"]),
            name = SourceData.GetString(mapping["name"]),
            expMod = SourceData.GetInt(mapping["expMod"]),
            maxLv = SourceData.GetInt(mapping["maxLv"]),
            reward = SourceData.GetStringArray(mapping["reward"]),
            detail_JP = SourceData.GetString(mapping["detail_JP"]),
            detail = SourceData.GetString(mapping["detail"])
        };
    }
References SourceData< T, T2 >.GetInt(), SourceData< T, T2 >.GetString(), and SourceData< T, T2 >.GetStringArray().
GetRowMapping()
override IReadOnlyDictionary< string, int > SourceHomeResource.GetRowMapping () inline
Definition at line 95 of file SourceHomeResource.cs.
    {
        return RowMapping;
    }
References RowMapping.
GetTypeMapping()
override IReadOnlyDictionary< string, string > SourceHomeResource.GetTypeMapping () inline
Definition at line 100 of file SourceHomeResource.cs.
    {
        return TypeMapping;
    }
References TypeMapping.
SetRow()
override void SourceHomeResource.SetRow (Row r) inline
Definition at line 90 of file SourceHomeResource.cs.
    {
        map[r.id] = r;
    }
References SourceHomeResource.Row.id.
Member Data Documentation
RowMapping
readonly IReadOnlyDictionary<string, int> SourceHomeResource.RowMapping static
Initial value:
= new Dictionary<string, int>
    {
        ["id"] = 0,
        ["name_JP"] = 1,
        ["name"] = 2,
        ["expMod"] = 3,
        ["maxLv"] = 4,
        ["reward"] = 5,
        ["detail_JP"] = 6,
        ["detail"] = 7
    }
Definition at line 36 of file SourceHomeResource.cs.
Referenced by GetRowMapping().
TypeMapping
readonly IReadOnlyDictionary<string, string> SourceHomeResource.TypeMapping static
Initial value:
= new Dictionary<string, string>
    {
        ["id"] = "string",
        ["name_JP"] = "string",
        ["name"] = "string",
        ["expMod"] = "int",
        ["maxLv"] = "int",
        ["reward"] = "string[]",
        ["detail_JP"] = "string",
        ["detail"] = "string"
    }
Definition at line 48 of file SourceHomeResource.cs.
Referenced by GetTypeMapping().
The documentation for this class was generated from the following file:
Elin/SourceHomeResource.cs