Elin Decompiled Documentation: SourceHobby Class Reference
SourceHobby Class Reference
Classes
class Row
Public Member Functions
override Row CreateRow ()
override Row CreateRowByMapping (IReadOnlyDictionary< string, int > mapping)
override void SetRow (Row r)
override IReadOnlyDictionary< string, int > GetRowMapping ()
override IReadOnlyDictionary< string, string > GetTypeMapping ()
override void OnInit ()
Public Member Functions inherited from SourceDataInt< SourceHobby.Row >
override T GetRow (string id)
Public Attributes
List< Row > listHobbies = new List<Row>()
List< Row > listWorks = new List<Row>()
Static Public Attributes
static readonly IReadOnlyDictionary< string, int > RowMapping
static readonly IReadOnlyDictionary< string, string > TypeMapping
Detailed Description
Definition at line 4 of file SourceHobby.cs.
Member Function Documentation
CreateRow()
override Row SourceHobby.CreateRow () inline
Definition at line 114 of file SourceHobby.cs.
    {
        return new Row
        {
            id = SourceData.GetInt(0),
            alias = SourceData.GetString(1),
            type = SourceData.GetString(2),
            name_JP = SourceData.GetString(3),
            name = SourceData.GetString(4),
            ai = SourceData.GetString(5),
            talk = SourceData.GetString(6),
            area = SourceData.GetString(7),
            destTrait = SourceData.GetString(8),
            workTag = SourceData.GetString(9),
            expedition = SourceData.GetString(10),
            resources = SourceData.GetIntArray(11),
            randomRange = SourceData.GetInt(12),
            modifiers = SourceData.GetStringArray(13),
            tax = SourceData.GetInt(14),
            things = SourceData.GetStringArray(15),
            elements = Core.ParseElements(SourceData.GetStr(16)),
            skill = SourceData.GetString(17),
            detail_JP = SourceData.GetString(18),
            detail = SourceData.GetString(19)
        };
    }
References SourceData< T, T2 >.GetInt(), SourceData< T, T2 >.GetIntArray(), SourceData< T, T2 >.GetStr(), SourceData< T, T2 >.GetString(), SourceData< T, T2 >.GetStringArray(), and Core.ParseElements().
CreateRowByMapping()
override Row SourceHobby.CreateRowByMapping (IReadOnlyDictionary< string, int > mapping) inline
Definition at line 141 of file SourceHobby.cs.
    {
        return new Row
        {
            id = SourceData.GetInt(mapping["id"]),
            alias = SourceData.GetString(mapping["alias"]),
            type = SourceData.GetString(mapping["type"]),
            name_JP = SourceData.GetString(mapping["name_JP"]),
            name = SourceData.GetString(mapping["name"]),
            ai = SourceData.GetString(mapping["ai"]),
            talk = SourceData.GetString(mapping["talk"]),
            area = SourceData.GetString(mapping["area"]),
            destTrait = SourceData.GetString(mapping["destTrait"]),
            workTag = SourceData.GetString(mapping["workTag"]),
            expedition = SourceData.GetString(mapping["expedition"]),
            resources = SourceData.GetIntArray(mapping["resources"]),
            randomRange = SourceData.GetInt(mapping["randomRange"]),
            modifiers = SourceData.GetStringArray(mapping["modifiers"]),
            tax = SourceData.GetInt(mapping["tax"]),
            things = SourceData.GetStringArray(mapping["things"]),
            elements = Core.ParseElements(SourceData.GetStr(mapping["elements"])),
            skill = SourceData.GetString(mapping["skill"]),
            detail_JP = SourceData.GetString(mapping["detail_JP"]),
            detail = SourceData.GetString(mapping["detail"])
        };
    }
References SourceData< T, T2 >.GetInt(), SourceData< T, T2 >.GetIntArray(), SourceData< T, T2 >.GetStr(), SourceData< T, T2 >.GetString(), SourceData< T, T2 >.GetStringArray(), and Core.ParseElements().
GetRowMapping()
override IReadOnlyDictionary< string, int > SourceHobby.GetRowMapping () inline
Definition at line 173 of file SourceHobby.cs.
    {
        return RowMapping;
    }
References RowMapping.
GetTypeMapping()
override IReadOnlyDictionary< string, string > SourceHobby.GetTypeMapping () inline
Definition at line 178 of file SourceHobby.cs.
    {
        return TypeMapping;
    }
References TypeMapping.
OnInit()
override void SourceHobby.OnInit () inline
Definition at line 183 of file SourceHobby.cs.
    {
        foreach (Row row in rows)
        {
            switch (row.type)
            {
            case "Hobby":
                listHobbies.Add(row);
                break;
            case "Work":
                listWorks.Add(row);
                break;
            case "Both":
                listHobbies.Add(row);
                listWorks.Add(row);
                break;
            }
        }
    }
References listHobbies, listWorks, and SourceHobby.Row.type.
SetRow()
override void SourceHobby.SetRow (Row r) inline
Definition at line 168 of file SourceHobby.cs.
    {
        map[r.id] = r;
    }
References SourceHobby.Row.id.
Member Data Documentation
listHobbies
List<Row> SourceHobby.listHobbies = new List<Row>()
Definition at line 109 of file SourceHobby.cs.
Referenced by OnInit(), and Chara.RerollHobby().
listWorks
List<Row> SourceHobby.listWorks = new List<Row>()
Definition at line 112 of file SourceHobby.cs.
Referenced by OnInit(), and Chara.RerollHobby().
RowMapping
readonly IReadOnlyDictionary<string, int> SourceHobby.RowMapping static
Initial value:
= new Dictionary<string, int>
    {
        ["id"] = 0,
        ["alias"] = 1,
        ["type"] = 2,
        ["name_JP"] = 3,
        ["name"] = 4,
        ["ai"] = 5,
        ["talk"] = 6,
        ["area"] = 7,
        ["destTrait"] = 8,
        ["workTag"] = 9,
        ["expedition"] = 10,
        ["resources"] = 11,
        ["randomRange"] = 12,
        ["modifiers"] = 13,
        ["tax"] = 14,
        ["things"] = 15,
        ["elements"] = 16,
        ["skill"] = 17,
        ["detail_JP"] = 18,
        ["detail"] = 19
    }
Definition at line 60 of file SourceHobby.cs.
Referenced by GetRowMapping().
TypeMapping
readonly IReadOnlyDictionary<string, string> SourceHobby.TypeMapping static
Initial value:
= new Dictionary<string, string>
    {
        ["id"] = "int",
        ["alias"] = "string",
        ["type"] = "string",
        ["name_JP"] = "string",
        ["name"] = "string",
        ["ai"] = "string",
        ["talk"] = "string",
        ["area"] = "string",
        ["destTrait"] = "string",
        ["workTag"] = "string",
        ["expedition"] = "string",
        ["resources"] = "int[]",
        ["randomRange"] = "int",
        ["modifiers"] = "string[]",
        ["tax"] = "int",
        ["things"] = "string[]",
        ["elements"] = "elements",
        ["skill"] = "string",
        ["detail_JP"] = "string",
        ["detail"] = "string"
    }
Definition at line 84 of file SourceHobby.cs.
Referenced by GetTypeMapping().
The documentation for this class was generated from the following file:
Elin/SourceHobby.cs