Elin Decompiled Documentation: Shaker Class Reference
Shaker Class Reference
Static Public Member Functions
static void Shake (Transform t, string id, float magnitude)
static void Shake (Component t, string id, float magnitude=1f)
static void ShakeCam (string id="default", float magnitude=1f)
Detailed Description
Definition at line 4 of file Shaker.cs.
Member Function Documentation
Shake() [1/2]
static void Shaker.Shake (Component t, string id, float magnitude = 1f) inline static
Definition at line 20 of file Shaker.cs.
    {
        Shake(t.transform, id, magnitude);
    }
References Shake().
Shake() [2/2]
static void Shaker.Shake (Transform t, string id, float magnitude) inline static
Definition at line 6 of file Shaker.cs.
    {
        DOTween.Kill(t);
        ShakerProfile shakerProfile = ResourceCache.Load<ShakerProfile>("Media/Effect/ScreenEffect/Shaker/" + id);
        int num = ((Random.Range(0, 2) == 0) ? 1 : (-1));
        int num2 = ((Random.Range(0, 2) == 0) ? 1 : (-1));
        _ = t.transform.localPosition;
        t.transform.localPosition = Vector3.zero;
        ((shakerProfile.type == ShakerProfile.Type.Shake) ? t.DOShakePosition(shakerProfile.duration, new Vector2((float)num * shakerProfile.power, (float)num2 * shakerProfile.power) * magnitude, shakerProfile.vibrato) : t.DOPunchPosition(new Vector2((float)num * shakerProfile.power, (float)num2 * shakerProfile.power) * magnitude, shakerProfile.duration, shakerProfile.vibrato, shakerProfile.elasticity)).OnComplete(delegate
        {
            t.localPosition = Vector3.zero;
        });
    }
References ShakerProfile.duration, ShakerProfile.elasticity, ShakerProfile.power, Random, and ShakerProfile.vibrato.
Referenced by Shake(), and ShakeCam().
ShakeCam()
static void Shaker.ShakeCam (string id = "default", float magnitude = 1f) inline static
Definition at line 25 of file Shaker.cs.
    {
        if ((bool)Camera.main)
        {
            Shake(Camera.main.transform.parent, id, magnitude);
        }
    }
References Shake().
Referenced by GameDate.AdvanceHour(), TraitTrap.OnActivateTrap(), EffectMeteor.OnPlay(), DramaManager.ParseLine(), ActEffect.ProcAt(), and ShakerProfile.ShakeCam().
The documentation for this class was generated from the following file:
Elin/Plugins.UI/Shaker.cs