Elin Decompiled Documentation: UIListDragItem Class Reference
UIListDragItem Class Reference
Public Member Functions
void OnBeginDrag (PointerEventData eventData)
void OnDrag (PointerEventData eventData)
void OnEndDrag (PointerEventData eventData)
void OnPointerEnter (PointerEventData eventData)
Public Attributes
UIList list
object item
Detailed Description
Definition at line 4 of file UIListDragItem.cs.
Member Function Documentation
OnBeginDrag()
void UIListDragItem.OnBeginDrag (PointerEventData eventData) inline
Definition at line 10 of file UIListDragItem.cs.
    {
        list.BeginItemDrag(this);
    }
References UIList.BeginItemDrag(), and list.
OnDrag()
void UIListDragItem.OnDrag (PointerEventData eventData) inline
Definition at line 15 of file UIListDragItem.cs.
    {
    }
OnEndDrag()
void UIListDragItem.OnEndDrag (PointerEventData eventData) inline
Definition at line 19 of file UIListDragItem.cs.
    {
        list.EndItemDrag(this);
    }
References UIList.EndItemDrag(), and list.
OnPointerEnter()
void UIListDragItem.OnPointerEnter (PointerEventData eventData) inline
Definition at line 24 of file UIListDragItem.cs.
    {
        list.UpdateItemDragHover(this);
    }
References list, and UIList.UpdateItemDragHover().
Member Data Documentation
item
object UIListDragItem.item
Definition at line 8 of file UIListDragItem.cs.
Referenced by UIList.BeginItemDrag(), UIList.EndItemDrag(), and UIList.UpdateItemDragHover().
list
UIList UIListDragItem.list
Definition at line 6 of file UIListDragItem.cs.
Referenced by OnBeginDrag(), OnEndDrag(), and OnPointerEnter().
The documentation for this class was generated from the following file:
Elin/Plugins.UI/UIListDragItem.cs