Elin Decompiled Documentation: InvOwnerRefuel Class Reference
InvOwnerRefuel Class Reference
Public Member Functions
InvOwnerRefuel (Card owner=null, Card container=null, CurrencyType _currency=CurrencyType.None)
override bool ShouldShowGuide (Thing t)
override void _OnProcess (Thing t)
Public Member Functions inherited from InvOwnerDraglet
override bool AllowHold (Thing t)
InvOwnerDraglet (Card owner=null, Card container=null, CurrencyType _currency=CurrencyType.Money)
override void OnInit ()
override void OnClick (ButtonGrid button)
override void OnRightClick (ButtonGrid button)
override int GetPrice (Thing t, CurrencyType currency, int num, bool sell)
override string GetTextDetail (Thing t, CurrencyType currency, int num, bool sell)
virtual void OnWriteNote (Thing t, UINote n)
sealed override void OnProcess (Thing t)
virtual void _OnProcess (Thing t)
virtual void OnAfterRefuel ()
void RedrawButton ()
override void BuildUICurrency (UICurrency uiCurrency, bool canReroll=false)
Public Member Functions inherited from InvOwner
virtual bool AllowHold (Thing t)
virtual bool AllowMoved (Thing t)
virtual bool ShouldShowGuide (Thing t)
virtual bool AllowDrop (Thing t)
virtual Thing CreateDefaultContainer ()
virtual void BuildUICurrency (UICurrency uiCurrency, bool canReroll=false)
bool IsWeightOver (Thing t)
InvOwner (Card owner, Card container=null, CurrencyType _currency=CurrencyType.None, PriceType _price=PriceType.Default)
void Init ()
virtual void OnInit ()
virtual void OnClick (ButtonGrid button)
virtual void OnRightClick (ButtonGrid button)
virtual void OnRightPressed (ButtonGrid button)
InvOwner GetShitDestOwner (ButtonGrid b, bool rightMouse=false)
virtual void OnShiftClick (ButtonGrid b, bool rightMouse=false)
virtual bool CanShiftClick (ButtonGrid b, bool rightMouse=false)
virtual string GetTextShiftClick (ButtonGrid b)
virtual void OnCtrlClick (ButtonGrid button)
virtual bool CanCtrlClick (ButtonGrid b)
virtual string GetTextCtrlClick (ButtonGrid b)
virtual void OnAltClick (ButtonGrid button)
virtual bool CanAltClick (ButtonGrid b)
virtual string GetTextAltClick (ButtonGrid b)
void Grab (DragItemCard.DragInfo from)
Thing PutBack (DragItemCard.DragInfo from)
void OnStartDrag (DragItemCard.DragInfo from)
virtual bool OnCancelDrag (DragItemCard.DragInfo from)
virtual bool OnDrag (DragItemCard.DragInfo from, DragItemCard.DragInfo to, bool execute, bool cancel=false)
virtual void OnProcess (Thing t)
bool CanOpenContainer (Thing t)
ListInteraction ListInteractions (ButtonGrid b, bool context)
bool TryHold (Thing t)
virtual void ListInteractions (ListInteraction list, Thing t, Trait trait, ButtonGrid b, bool context)
virtual string GetAutoUseLang (ButtonGrid button)
void AutoUse (ButtonGrid button, bool repeat=false)
void ShowContextMenu (ButtonGrid button)
virtual int GetPrice (Thing t, CurrencyType currency, int num, bool sell)
virtual string GetTextDetail (Thing t, CurrencyType currency, int num, bool sell)
virtual void OnWriteNote (ButtonGrid button, UINote n)
virtual string IDCostIcon (Thing t)
virtual bool IsFailByCurse (Thing t)
Properties
override ProcessType processType [get]
override string langTransfer [get]
override bool DenyImportant [get]
override bool AllowStockIngredients [get]
Properties inherited from InvOwnerDraglet
virtual ProcessType processType [get]
virtual bool ShowFuel [get]
virtual bool CanTargetAlly [get]
virtual string langWhat [get]
virtual bool AllowStockIngredients [get]
override bool AllowTransfer [get]
override bool AllowAutouse [get]
override bool AllowContext [get]
override bool UseGuide [get]
override bool CopyOnTransfer [get]
override bool InvertSell [get]
override bool DenyImportant [get]
LayerDragGrid dragGrid [get]
Properties inherited from InvOwner
static bool HasTrader [get]
static bool FreeTransfer [get]
virtual bool AllowAutouse [get]
virtual bool AllowContext [get]
virtual bool AllowSell [get]
virtual bool AlwaysShowTooltip [get]
virtual bool UseGuide [get]
virtual bool AllowTransfer [get]
virtual bool AllowDropOnDrag [get]
virtual string langTransfer [get]
virtual int destInvY [get]
virtual bool HasTransaction [get]
virtual bool CopyOnTransfer [get]
virtual bool SingleTarget [get]
bool UseHomeResource [get]
bool IsMagicChest [get]
List< Thing > Things [get]
Chara Chara [get]
ContainerType ContainerType [get]
virtual bool InvertSell [get]
virtual int numDragGrid [get]
virtual bool ShowNew [get]
virtual bool DenyImportant [get]
InvOwner destInvOwner [get]
string IDCurrency [get]
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Additional Inherited Members
Public Types inherited from InvOwnerDraglet
enum ProcessType { None , Consume }
Static Public Member Functions inherited from EClass
static int rndSeed (int a, int seed)
static int rnd (int a)
static int curve (int a, int start, int step, int rate=75)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Public Attributes inherited from InvOwnerDraglet
int count = -1
BlessedState state
int price
Public Attributes inherited from InvOwner
bool includeChildren
CurrencyType currency
PriceType priceType
HomeResource homeResource
Card owner
Card Container
List< ButtonGrid > buttons = new List<ButtonGrid>()
Static Public Attributes inherited from InvOwner
static ForceGiveData forceGive = new ForceGiveData()
static InvOwner Trader
static InvOwner Main
static float clickTimer
Static Public Attributes inherited from EClass
static Core core
Detailed Description
Definition at line 1 of file InvOwnerRefuel.cs.
Constructor & Destructor Documentation
InvOwnerRefuel()
InvOwnerRefuel.InvOwnerRefuel (Card owner = null, Card container = null, CurrencyType _currency = CurrencyType::None) inline
Definition at line 21 of file InvOwnerRefuel.cs.
        : base(owner, container, _currency)
    {
    }
Member Function Documentation
_OnProcess()
override void InvOwnerRefuel._OnProcess (Thing t) inline virtual
Reimplemented from InvOwnerDraglet.
Definition at line 31 of file InvOwnerRefuel.cs.
    {
        int fuelValue = owner.trait.GetFuelValue(t);
        int num = (owner.trait.MaxFuel - owner.c_charges) / fuelValue;
        if (num == 0)
        {
            SE.BeepSmall();
            Msg.Say("fuelFull");
            return;
        }
        if (t.Num < num)
        {
            num = t.Num;
        }
        Thing t2 = t.Split(num);
        owner.trait.Refuel(t2);
    }
References Card.c_charges, Trait.GetFuelValue(), Card.Num, InvOwner.owner, Trait.Refuel(), Msg.Say(), Card.Split(), and Card.trait.
ShouldShowGuide()
override bool InvOwnerRefuel.ShouldShowGuide (Thing t) inline virtual
Reimplemented from InvOwner.
Definition at line 26 of file InvOwnerRefuel.cs.
    {
        return owner.trait.IsFuel(t);
    }
References Trait.IsFuel(), InvOwner.owner, and Card.trait.
Property Documentation
AllowStockIngredients
override bool InvOwnerRefuel.AllowStockIngredients get
Definition at line 9 of file InvOwnerRefuel.cs.
    {
        get
        {
            if (!EClass._zone.IsPCFaction)
            {
                return EClass._zone is Zone_Tent;
            }
            return true;
        }
    }
DenyImportant
override bool InvOwnerRefuel.DenyImportant get
Definition at line 7 of file InvOwnerRefuel.cs.
langTransfer
override string InvOwnerRefuel.langTransfer get
Definition at line 5 of file InvOwnerRefuel.cs.
processType
override ProcessType InvOwnerRefuel.processType get
Definition at line 3 of file InvOwnerRefuel.cs.
The documentation for this class was generated from the following file:
Elin/InvOwnerRefuel.cs