Elin Decompiled Documentation: LangExporter Class Reference
LangExporter Class Reference
Static Public Member Functions
static void Export ()
static ICell GetCell (int x, int y)
static void WriteCell (int x, int y, string value)
static void WriteCell (int x, int y, double value)
Static Public Member Functions inherited from EClass
static int rndSeed (int a, int seed)
static int rnd (long a)
static int rnd (int a)
static int curve (int a, int start, int step, int rate=75)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Static Private Attributes
static ISheet currentSheet
Additional Inherited Members
Static Public Attributes inherited from EClass
static Core core
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Detailed Description
Definition at line 5 of file LangExporter.cs.
Member Function Documentation
Export()
static void LangExporter.Export () inline static
Definition at line 9 of file LangExporter.cs.
    {
        string text = CorePath.packageCore + "Lang/Template/";
        string text2 = "sample.xlsx";
        XSSFWorkbook xSSFWorkbook = new XSSFWorkbook();
        currentSheet = xSSFWorkbook.CreateSheet("newSheet");
        using FileStream stream = new FileStream(text + text2, FileMode.Create);
        xSSFWorkbook.Write(stream);
    }
References currentSheet.
GetCell()
static ICell LangExporter.GetCell (int x, int y) inline static
Definition at line 19 of file LangExporter.cs.
    {
        IRow row = currentSheet.GetRow(y) ?? currentSheet.CreateRow(y);
        return row.GetCell(x) ?? row.CreateCell(x);
    }
References currentSheet.
Referenced by WriteCell().
WriteCell() [1/2]
static void LangExporter.WriteCell (int x, int y, double value) inline static
Definition at line 30 of file LangExporter.cs.
    {
        GetCell(x, y).SetCellValue(value);
    }
References GetCell().
WriteCell() [2/2]
static void LangExporter.WriteCell (int x, int y, string value) inline static
Definition at line 25 of file LangExporter.cs.
    {
        GetCell(x, y).SetCellValue(value);
    }
References GetCell().
Member Data Documentation
currentSheet
ISheet LangExporter.currentSheet static private
Definition at line 7 of file LangExporter.cs.
Referenced by Export(), and GetCell().
The documentation for this class was generated from the following file:
Elin/LangExporter.cs