Elin Decompiled Documentation: ConChampagne Class Reference
ConChampagne Class Reference
Public Member Functions
override void Tick ()
Public Member Functions inherited from BaseBuff
override int GetPhase ()
Public Member Functions inherited from BaseDebuff
override int GetPhase ()
override BaseNotification CreateNotification ()
Public Member Functions inherited from Condition
override BaseNotification CreateNotification ()
virtual void OnStacked (int p)
Condition SetPerfume (int duration=3)
override void Tick ()
virtual void OnCalculateFov (Fov fov, ref int radius, ref float power)
virtual void OnCreateFov (Fov fov)
override void OnValueChanged ()
void Kill (bool silent=false)
Public Member Functions inherited from BaseCondition
virtual bool CanStack (Condition c)
virtual bool TryMove (Point p)
void SetElement (int id)
void SetRefVal (int a, int b)
virtual Color GetSpriteColor ()
override string ToString ()
override string GetText ()
override int GetValue ()
override Color GetColor (Gradient g)
virtual void SetOwner (Chara _owner, bool onDeserialize=false)
SourceElement.Row GetElementSource (int i)
void Start ()
bool TryNullify (Condition c)
virtual void OnBeforeStart ()
virtual void OnStart ()
virtual void OnStartOrStack ()
virtual void PlayEffect ()
virtual void PlayEndEffect ()
virtual void OnRefresh ()
void SetPhase ()
bool IsNullPhase ()
override int GetPhase ()
void PhaseMsg (bool inc)
override string GetPhaseStr ()
virtual void Tick ()
void Mod (int a, bool force=false)
virtual void OnValueChanged ()
virtual void OnChangePhase (int lastPhase, int newPhase)
virtual void OnRemoved ()
virtual int EvaluatePower (int p)
virtual int EvaluateTurn (int p)
virtual BaseNotification CreateNotification ()
Element GetDefenseAttribute (Chara c=null)
override void _WriteNote (UINote n, bool asChild=false)
virtual void OnWriteNote (List< string > list)
virtual RendererReplacer GetRendererReplacer ()
Public Member Functions inherited from BaseStats
virtual Color GetColor (Gradient gradient)
virtual Color GetColor (SkinColorProfile c)
Color GetColor ()
virtual string GetText ()
virtual string GetPhaseStr ()
virtual int GetValue ()
virtual Sprite GetSprite ()
virtual void SetText (UIText t, SkinColorProfile cols=null)
virtual int GetPhase ()
void PopText ()
virtual void WriteNote (UINote n, Action< UINote > onWriteNote=null)
virtual void _WriteNote (UINote n, bool asChild=false)
Public Attributes
int count
Public Attributes inherited from BaseCondition
int[] _ints = new int[5]
int phase = -1
ElementContainer elements
Chara owner
Public Attributes inherited from BaseStats
int id
SourceStat.Row _source
Additional Inherited Members
Static Public Member Functions inherited from Condition
static T Create< T > (int power=100, Action< T > onCreate=null)
static Condition Create (string alias, int power=100, Action< Condition > onCreate=null)
Static Public Member Functions inherited from EClass
static int rnd (int a)
static int curve (int a, int start, int step, int rate=75)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Static Public Attributes inherited from Condition
static bool ignoreEffect
Static Public Attributes inherited from BaseStats
static Chara CC
Static Public Attributes inherited from EClass
static Core core
Properties inherited from BaseBuff
override bool CanManualRemove [get]
Properties inherited from BaseDebuff
override bool WillOverride [get]
Properties inherited from Condition
virtual bool IsKilled [get]
virtual string TextDuration [get]
Properties inherited from BaseCondition
int value [get, set]
int power [get, set]
int refVal [get, set]
int refVal2 [get, set]
bool givenByPcParty [get, set]
bool isPerfume [get, set]
override Chara Owner [get]
virtual string Name [get]
virtual bool IsToggle [get]
virtual bool WillOverride [get]
virtual bool AllowMultipleInstance [get]
virtual bool ConsumeTurn [get]
virtual bool PreventRegen [get]
virtual bool ShouldRefresh [get]
virtual bool CancelAI [get]
virtual bool TimeBased [get]
virtual bool SyncRide [get]
virtual bool UseElements [get]
virtual int GainResistFactor [get]
virtual int P2 [get]
SourceElement.Row sourceElement [get]
virtual bool IsElemental [get]
virtual string RefString1 [get]
virtual bool CanManualRemove [get]
Properties inherited from BaseStats
SourceStat.Row source [get]
virtual Emo2 EmoIcon [get]
virtual ConditionType Type [get]
virtual string idSprite [get]
virtual bool ShowInWidget [get]
virtual Chara Owner [get]
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Detailed Description
Definition at line 4 of file ConChampagne.cs.
Member Function Documentation
Tick()
override void ConChampagne.Tick () inline virtual
Reimplemented from BaseCondition.
Definition at line 9 of file ConChampagne.cs.
    {
        count--;
        if (count <= 0)
        {
            count += 15;
            owner.Talk("champagne");
            int num = Mathf.Max(EClass.curve(owner.CHA * 10, 400, 100), 100);
            if (EClass._zone.IsUserZone && !owner.IsPCFactionOrMinion && num > 500)
            {
                num = 500;
            }
            foreach (Chara chara in EClass._map.charas)
            {
                if (chara != owner && chara.IsNeutralOrAbove() && owner.Dist(chara) <= 10)
                {
                    chara.AddCondition<ConHero>(num);
                    chara.AddCondition<ConEuphoric>(num);
                    chara.AddCondition<ConSeeInvisible>(num);
                }
            }
        }
        Mod(-1);
    }
References EClass._map, EClass._zone, Chara.AddCondition(), Card.CHA, Map.charas, count, EClass.curve(), Card.Dist(), Chara.IsNeutralOrAbove(), Card.IsPCFactionOrMinion, Zone.IsUserZone, BaseCondition.Mod(), BaseCondition.owner, and Card.Talk().
Member Data Documentation
count
int ConChampagne.count
Definition at line 7 of file ConChampagne.cs.
Referenced by Tick().
The documentation for this class was generated from the following file:
Elin/ConChampagne.cs