Elin Decompiled Documentation: TCOrbitThing Class Reference
TCOrbitThing Class Reference
Public Member Functions
override void OnSetOwner ()
override void Refresh ()
void RefreshAll ()
virtual void Refresh ()
Public Member Functions inherited from TC
void SetOwner (CardRenderer r)
virtual void OnSetOwner ()
virtual void OnDraw (ref Vector3 pos)
void Kill ()
virtual void OnKill ()
Public Attributes
GameObject goIcon
SpriteRenderer iconStatus
new Thing owner
Public Attributes inherited from TC
CardRenderer render
Private Attributes
float timer
Additional Inherited Members
Static Public Member Functions inherited from EMono
static int rnd (int a)
Static Public Attributes inherited from TC
static GameSetting.RenderSetting.TCSetting _setting
Static Public Attributes inherited from EMono
static Core core
Properties inherited from TC
Card owner [get]
virtual bool isUI [get]
virtual Vector3 FixPos [get]
Properties inherited from EMono
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SoundManager Sound [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static CoreDebug debug [get]
Detailed Description
Definition at line 3 of file TCOrbitThing.cs.
Member Function Documentation
OnSetOwner()
override void TCOrbitThing.OnSetOwner () inline virtual
Reimplemented from TC.
Definition at line 13 of file TCOrbitThing.cs.
    {
        owner = base.owner as Thing;
        RenderData data = owner.renderer.data;
        goIcon.transform.SetLocalPositionY(data.offset.y + data.size.y + 0.32f);
        RefreshAll();
    }
References RenderObject.data, goIcon, RenderData.offset, owner, RefreshAll(), Card.renderer, and RenderData.size.
Refresh()
override void TCOrbitThing.Refresh () inline virtual
Reimplemented from TCOrbit.
Definition at line 21 of file TCOrbitThing.cs.
    {
        timer += Time.deltaTime;
        if (timer > 0.2f)
        {
            timer = 0f;
            RefreshAll();
        }
        if (!owner.isHidden || EMono.pc.CanSee(owner))
        {
            if (!base.gameObject.activeSelf)
            {
                base.gameObject.SetActive(value: true);
            }
            base.transform.position = owner.renderer.position;
        }
        else if (base.gameObject.activeSelf)
        {
            base.gameObject.SetActive(value: false);
        }
    }
References Chara.CanSee(), Card.isHidden, owner, EMono.pc, CardRenderer.position, RefreshAll(), Card.renderer, and timer.
RefreshAll()
void TCOrbitThing.RefreshAll () inline
Definition at line 43 of file TCOrbitThing.cs.
    {
        _ = EMono.core.refs.orbitIcons;
        Emo2 emo = Emo2.none;
        if (owner.IsInstalled)
        {
            if (owner.isRestocking && !owner.IsPCParty && owner.trait.GetRestockedIcon() != 0 && !(EMono._zone is Zone_Dungeon))
            {
                emo = owner.trait.GetRestockedIcon();
            }
            else if (EMono.player.currentHotItem.Thing?.trait is TraitToolShears && owner.CanBeSheared())
            {
                emo = Emo2.fur;
            }
        }
        bool flag = emo != Emo2.none;
        if (flag)
        {
            iconStatus.sprite = EMono.core.refs.spritesEmo[(int)emo];
        }
        iconStatus.SetActive(flag);
    }
References EMono._zone, Card.CanBeSheared(), EMono.core, Player.currentHotItem, Trait.GetRestockedIcon(), iconStatus, Card.IsInstalled, Card.IsPCParty, Card.isRestocking, CoreRef.orbitIcons, owner, EMono.player, Core.refs, CoreRef.spritesEmo, HotItem.Thing, and Card.trait.
Referenced by OnSetOwner(), and Refresh().
Member Data Documentation
goIcon
GameObject TCOrbitThing.goIcon
Definition at line 5 of file TCOrbitThing.cs.
Referenced by OnSetOwner().
iconStatus
SpriteRenderer TCOrbitThing.iconStatus
Definition at line 7 of file TCOrbitThing.cs.
Referenced by RefreshAll().
owner
new Thing TCOrbitThing.owner
Definition at line 9 of file TCOrbitThing.cs.
Referenced by OnSetOwner(), Refresh(), and RefreshAll().
timer
float TCOrbitThing.timer private
Definition at line 11 of file TCOrbitThing.cs.
Referenced by Refresh().
The documentation for this class was generated from the following file:
Elin/TCOrbitThing.cs