Elin Decompiled Documentation: SFB.StandaloneFileBrowserWindows Class Reference
SFB.StandaloneFileBrowserWindows Class Reference
Public Member Functions
string[] OpenFilePanel (string title, string directory, ExtensionFilter[] extensions, bool multiselect)
void OpenFilePanelAsync (string title, string directory, ExtensionFilter[] extensions, bool multiselect, Action< string[]> cb)
string[] OpenFolderPanel (string title, string directory, bool multiselect)
void OpenFolderPanelAsync (string title, string directory, bool multiselect, Action< string[]> cb)
string SaveFilePanel (string title, string directory, string defaultName, ExtensionFilter[] extensions)
void SaveFilePanelAsync (string title, string directory, string defaultName, ExtensionFilter[] extensions, Action< string > cb)
string[] OpenFilePanel (string title, string directory, ExtensionFilter[] extensions, bool multiselect)
string[] OpenFolderPanel (string title, string directory, bool multiselect)
string SaveFilePanel (string title, string directory, string defaultName, ExtensionFilter[] extensions)
void OpenFilePanelAsync (string title, string directory, ExtensionFilter[] extensions, bool multiselect, Action< string[]> cb)
void OpenFolderPanelAsync (string title, string directory, bool multiselect, Action< string[]> cb)
void SaveFilePanelAsync (string title, string directory, string defaultName, ExtensionFilter[] extensions, Action< string > cb)
Private Member Functions
static IntPtr GetActiveWindow ()
Static Private Member Functions
static string GetFilterFromFileExtensionList (ExtensionFilter[] extensions)
static string GetDirectoryPath (string directory)
Detailed Description
Definition at line 9 of file StandaloneFileBrowserWindows.cs.
Member Function Documentation
GetActiveWindow()
static IntPtr SFB.StandaloneFileBrowserWindows.GetActiveWindow () private
Referenced by SFB.StandaloneFileBrowserWindows.OpenFilePanel(), SFB.StandaloneFileBrowserWindows.OpenFolderPanel(), and SFB.StandaloneFileBrowserWindows.SaveFilePanel().
GetDirectoryPath()
static string SFB.StandaloneFileBrowserWindows.GetDirectoryPath (string directory) inline static private
Definition at line 121 of file StandaloneFileBrowserWindows.cs.
    {
        string text = Path.GetFullPath(directory);
        if (!text.EndsWith("\\"))
        {
            text += "\\";
        }
        if (Path.GetPathRoot(text) == text)
        {
            return directory;
        }
        string directoryName = Path.GetDirectoryName(text);
        char directorySeparatorChar = Path.DirectorySeparatorChar;
        return directoryName + directorySeparatorChar;
    }
Referenced by SFB.StandaloneFileBrowserWindows.OpenFilePanel(), SFB.StandaloneFileBrowserWindows.OpenFolderPanel(), and SFB.StandaloneFileBrowserWindows.SaveFilePanel().
GetFilterFromFileExtensionList()
static string SFB.StandaloneFileBrowserWindows.GetFilterFromFileExtensionList (ExtensionFilter[] extensions) inline static private
Definition at line 97 of file StandaloneFileBrowserWindows.cs.
    {
        string text = "";
        for (int i = 0; i < extensions.Length; i++)
        {
            ExtensionFilter extensionFilter = extensions[i];
            text = text + extensionFilter.Name + "(";
            string[] extensions2 = extensionFilter.Extensions;
            foreach (string text2 in extensions2)
            {
                text = text + "*." + text2 + ",";
            }
            text = text.Remove(text.Length - 1);
            text += ") |";
            extensions2 = extensionFilter.Extensions;
            foreach (string text3 in extensions2)
            {
                text = text + "*." + text3 + "; ";
            }
            text += "|";
        }
        return text.Remove(text.Length - 1);
    }
References SFB.ExtensionFilter.Extensions.
Referenced by SFB.StandaloneFileBrowserWindows.OpenFilePanel(), and SFB.StandaloneFileBrowserWindows.SaveFilePanel().
OpenFilePanel()
string[] SFB.StandaloneFileBrowserWindows.OpenFilePanel (string title, string directory, ExtensionFilter[] extensions, bool multiselect) inline
Implements SFB.IStandaloneFileBrowser.
Definition at line 14 of file StandaloneFileBrowserWindows.cs.
    {
        VistaOpenFileDialog vistaOpenFileDialog = new VistaOpenFileDialog();
        vistaOpenFileDialog.Title = title;
        if (extensions != null)
        {
            vistaOpenFileDialog.Filter = GetFilterFromFileExtensionList(extensions);
            vistaOpenFileDialog.FilterIndex = 1;
        }
        else
        {
            vistaOpenFileDialog.Filter = string.Empty;
        }
        vistaOpenFileDialog.Multiselect = multiselect;
        if (!string.IsNullOrEmpty(directory))
        {
            vistaOpenFileDialog.FileName = GetDirectoryPath(directory);
        }
        string[] result = ((vistaOpenFileDialog.ShowDialog(new WindowWrapper(GetActiveWindow())) == DialogResult.OK) ? vistaOpenFileDialog.FileNames : new string[0]);
        vistaOpenFileDialog.Dispose();
        return result;
    }
References SFB.StandaloneFileBrowserWindows.GetActiveWindow(), SFB.StandaloneFileBrowserWindows.GetDirectoryPath(), SFB.StandaloneFileBrowserWindows.GetFilterFromFileExtensionList(), and title.
Referenced by SFB.StandaloneFileBrowserWindows.OpenFilePanelAsync().
OpenFilePanelAsync()
void SFB.StandaloneFileBrowserWindows.OpenFilePanelAsync (string title, string directory, ExtensionFilter[] extensions, bool multiselect, Action< string[]> cb) inline
Implements SFB.IStandaloneFileBrowser.
Definition at line 37 of file StandaloneFileBrowserWindows.cs.
    {
        cb(OpenFilePanel(title, directory, extensions, multiselect));
    }
References SFB.StandaloneFileBrowserWindows.OpenFilePanel(), and title.
OpenFolderPanel()
string[] SFB.StandaloneFileBrowserWindows.OpenFolderPanel (string title, string directory, bool multiselect) inline
Implements SFB.IStandaloneFileBrowser.
Definition at line 42 of file StandaloneFileBrowserWindows.cs.
    {
        VistaFolderBrowserDialog vistaFolderBrowserDialog = new VistaFolderBrowserDialog();
        vistaFolderBrowserDialog.Description = title;
        if (!string.IsNullOrEmpty(directory))
        {
            vistaFolderBrowserDialog.SelectedPath = GetDirectoryPath(directory);
        }
        string[] result = ((vistaFolderBrowserDialog.ShowDialog(new WindowWrapper(GetActiveWindow())) != DialogResult.OK) ? new string[0] : new string[1] { vistaFolderBrowserDialog.SelectedPath });
        vistaFolderBrowserDialog.Dispose();
        return result;
    }
References SFB.StandaloneFileBrowserWindows.GetActiveWindow(), SFB.StandaloneFileBrowserWindows.GetDirectoryPath(), and title.
Referenced by SFB.StandaloneFileBrowserWindows.OpenFolderPanelAsync().
OpenFolderPanelAsync()
void SFB.StandaloneFileBrowserWindows.OpenFolderPanelAsync (string title, string directory, bool multiselect, Action< string[]> cb) inline
Implements SFB.IStandaloneFileBrowser.
Definition at line 55 of file StandaloneFileBrowserWindows.cs.
    {
        cb(OpenFolderPanel(title, directory, multiselect));
    }
References SFB.StandaloneFileBrowserWindows.OpenFolderPanel(), and title.
SaveFilePanel()
string SFB.StandaloneFileBrowserWindows.SaveFilePanel (string title, string directory, string defaultName, ExtensionFilter[] extensions) inline
Implements SFB.IStandaloneFileBrowser.
Definition at line 60 of file StandaloneFileBrowserWindows.cs.
    {
        VistaSaveFileDialog vistaSaveFileDialog = new VistaSaveFileDialog();
        vistaSaveFileDialog.Title = title;
        string text = "";
        if (!string.IsNullOrEmpty(directory))
        {
            text = GetDirectoryPath(directory);
        }
        if (!string.IsNullOrEmpty(defaultName))
        {
            text += defaultName;
        }
        vistaSaveFileDialog.FileName = text;
        if (extensions != null)
        {
            vistaSaveFileDialog.Filter = GetFilterFromFileExtensionList(extensions);
            vistaSaveFileDialog.FilterIndex = 1;
            vistaSaveFileDialog.DefaultExt = extensions[0].Extensions[0];
            vistaSaveFileDialog.AddExtension = true;
        }
        else
        {
            vistaSaveFileDialog.DefaultExt = string.Empty;
            vistaSaveFileDialog.Filter = string.Empty;
            vistaSaveFileDialog.AddExtension = false;
        }
        string result = ((vistaSaveFileDialog.ShowDialog(new WindowWrapper(GetActiveWindow())) == DialogResult.OK) ? vistaSaveFileDialog.FileName : "");
        vistaSaveFileDialog.Dispose();
        return result;
    }
References SFB.ExtensionFilter.Extensions, SFB.StandaloneFileBrowserWindows.GetActiveWindow(), SFB.StandaloneFileBrowserWindows.GetDirectoryPath(), SFB.StandaloneFileBrowserWindows.GetFilterFromFileExtensionList(), and title.
Referenced by SFB.StandaloneFileBrowserWindows.SaveFilePanelAsync().
SaveFilePanelAsync()
void SFB.StandaloneFileBrowserWindows.SaveFilePanelAsync (string title, string directory, string defaultName, ExtensionFilter[] extensions, Action< string > cb) inline
Implements SFB.IStandaloneFileBrowser.
Definition at line 92 of file StandaloneFileBrowserWindows.cs.
    {
        cb(SaveFilePanel(title, directory, defaultName, extensions));
    }
References SFB.StandaloneFileBrowserWindows.SaveFilePanel(), and title.
The documentation for this class was generated from the following file:
Elin/Plugins.basecore/SFB/StandaloneFileBrowserWindows.cs