Elin Decompiled Documentation: LittlePopper Class Reference
LittlePopper Class Reference
Public Member Functions
void _OnAddStockpile (Thing t, int num)
Static Public Member Functions
static void OnAddStockpile (Thing t, int num)
Static Public Member Functions inherited from EMono
static int rnd (int a)
Public Attributes
PopManager pop
Static Public Attributes
static LittlePopper Instance
static bool skipPop
static bool showStock
Static Public Attributes inherited from EMono
static Core core
Private Member Functions
void Awake ()
Additional Inherited Members
Properties inherited from EMono
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SoundManager Sound [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static CoreDebug debug [get]
Detailed Description
Definition at line 1 of file LittlePopper.cs.
Member Function Documentation
_OnAddStockpile()
void LittlePopper._OnAddStockpile (Thing t, int num) inline
Definition at line 24 of file LittlePopper.cs.
    {
        pop.PopText(t.NameSimple + " (" + Lang._ChangeNum(t.Num - num, t.Num) + ")", null, "PopStock");
    }
References Lang._ChangeNum(), Card.NameSimple, Card.Num, pop, and PopManager.PopText().
Referenced by OnAddStockpile().
Awake()
void LittlePopper.Awake () inline private
Definition at line 11 of file LittlePopper.cs.
    {
        Instance = this;
    }
References Instance.
OnAddStockpile()
static void LittlePopper.OnAddStockpile (Thing t, int num) inline static
Definition at line 16 of file LittlePopper.cs.
    {
        if ((bool)Instance && showStock && !skipPop)
        {
            Instance._OnAddStockpile(t, num);
        }
    }
References _OnAddStockpile(), Instance, showStock, and skipPop.
Member Data Documentation
Instance
LittlePopper LittlePopper.Instance static
Definition at line 3 of file LittlePopper.cs.
Referenced by Awake(), and OnAddStockpile().
pop
PopManager LittlePopper.pop
Definition at line 9 of file LittlePopper.cs.
Referenced by _OnAddStockpile().
showStock
bool LittlePopper.showStock static
Definition at line 7 of file LittlePopper.cs.
Referenced by OnAddStockpile().
skipPop
bool LittlePopper.skipPop static
Definition at line 5 of file LittlePopper.cs.
Referenced by OnAddStockpile().
The documentation for this class was generated from the following file:
Elin/LittlePopper.cs