Elin Decompiled Documentation: PropsManager Class Reference
PropsManager Class Reference
Public Member Functions
void Init ()
void OnCardAddedToZone (Card c)
void OnSetPlaceState (Card c, PlaceState? newType, PlaceState? oldType=null)
Public Attributes
PropsStocked stocked = new PropsStocked()
PropsInstalled installed = new PropsInstalled()
PropsRoaming roaming = new PropsRoaming()
List< Card > deconstructing = new List<Card>()
List< Card > sales = new List<Card>()
Properties
bool dbg [get]
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Additional Inherited Members
Static Public Member Functions inherited from EClass
static int rnd (int a)
static int curve (int a, int start, int step, int rate=75)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Static Public Attributes inherited from EClass
static Core core
Detailed Description
Definition at line 4 of file PropsManager.cs.
Member Function Documentation
Init()
void PropsManager.Init () inline
Definition at line 18 of file PropsManager.cs.
    {
        stocked.Init();
        installed.Init();
        roaming.Init();
    }
References Props.Init(), installed, roaming, and stocked.
Referenced by Map.SetZone().
OnCardAddedToZone()
void PropsManager.OnCardAddedToZone (Card c) inline
Definition at line 25 of file PropsManager.cs.
    {
        if (!c.isThing)
        {
            if (c.isSale)
            {
                sales.Add(c);
            }
            return;
        }
        switch (c.placeState)
        {
        case PlaceState.installed:
            installed.Add(c);
            if (c.isSale)
            {
                sales.Add(c);
            }
            break;
        case PlaceState.roaming:
            roaming.Add(c);
            break;
        case PlaceState.stocked:
            stocked.Add(c);
            break;
        }
    }
References Props.Add(), installed, Card.isSale, Card.isThing, Card.placeState, roaming, sales, and stocked.
Referenced by Map.AddCardOnActivate(), Map.OnCardAddedToZone(), and Card.SetPlaceState().
OnSetPlaceState()
void PropsManager.OnSetPlaceState (Card c, PlaceState? newType, PlaceState? oldType = null) inline
Definition at line 53 of file PropsManager.cs.
    {
        if (!c.isThing || c.parent != EClass._zone)
        {
            return;
        }
        if (oldType.HasValue)
        {
            switch (oldType)
            {
            case PlaceState.roaming:
                if (dbg && !roaming.all.Contains(c))
                {
                    Debug.LogError("remove roaming" + c);
                }
                roaming.Remove(c);
                break;
            case PlaceState.stocked:
                if (dbg && !stocked.all.Contains(c))
                {
                    Debug.LogError("remove stocked" + c);
                }
                stocked.Remove(c);
                break;
            case PlaceState.installed:
                if (dbg && !installed.all.Contains(c))
                {
                    Debug.LogError("remove installed" + c);
                }
                installed.Remove(c);
                break;
            }
            if (c.isSale)
            {
                sales.Remove(c);
            }
        }
        if (!newType.HasValue || !newType.HasValue)
        {
            return;
        }
        switch (newType.GetValueOrDefault())
        {
        case PlaceState.roaming:
            if (dbg && roaming.all.Contains(c))
            {
                Debug.LogError("add roaming" + c);
            }
            roaming.Add(c);
            break;
        case PlaceState.stocked:
            if (dbg && stocked.all.Contains(c))
            {
                Debug.LogError("add stocked" + c);
            }
            stocked.Add(c);
            break;
        case PlaceState.installed:
            if (dbg && installed.all.Contains(c))
            {
                Debug.LogError("add installed" + c);
            }
            installed.Add(c);
            if (c.isSale)
            {
                sales.Add(c);
            }
            break;
        }
    }
References EClass._zone, Props.Add(), Props.all, PropSet.Contains(), dbg, Debug, installed, Card.isSale, Card.isThing, Card.parent, Props.Remove(), roaming, sales, and stocked.
Member Data Documentation
deconstructing
List<Card> PropsManager.deconstructing = new List<Card>()
Definition at line 12 of file PropsManager.cs.
Referenced by Props.Add(), Props.Remove(), AI_Deconstruct.Run(), GoalTask.Run(), and Card.SetDeconstruct().
installed
PropsInstalled PropsManager.installed = new PropsInstalled()
Definition at line 8 of file PropsManager.cs.
Referenced by VirtualDate.BuildSunMap(), Chara.FindBed(), Map.FindThing(), AI_Pray.GetAltar(), FactionBranch.GetMailBox(), FactionBranch.GetMailBoxPos(), Zone.GetRandomSpot< T >(), Zone.GetSpawnPos(), Init(), Chara.IsInSpot< T >(), Zone_Nymelle.OnBeforeSimulate(), OnCardAddedToZone(), OnSetPlaceState(), Map.PutAway(), DramaOutcome.PutOutFire(), Map.RefreshSunMap(), AI_Idle.Run(), MeetingManager.SetRoom(), Zone.TryAddThingInSharedContainer(), Zone.TryAddThingInSpot< T >(), Chara.TryAssignBed(), Zone.TryGetThingFromSharedContainer(), Chara.TryPutSharedItems(), Chara.TryTakeSharedItems(), and FactionBranch.TryTrash().
roaming
PropsRoaming PropsManager.roaming = new PropsRoaming()
Definition at line 10 of file PropsManager.cs.
Referenced by Zone.Deactivate(), Init(), OnCardAddedToZone(), and OnSetPlaceState().
sales
List<Card> PropsManager.sales = new List<Card>()
Definition at line 14 of file PropsManager.cs.
Referenced by Party.AddMemeber(), AI_Shopping.Buy(), Chara.Die(), OnCardAddedToZone(), OnSetPlaceState(), FactionBranch.RemoveMemeber(), Card.RemoveThing(), Card.SetSale(), and AI_Shopping.TryShop().
stocked
PropsStocked PropsManager.stocked = new PropsStocked()
Definition at line 6 of file PropsManager.cs.
Referenced by Zone.Deactivate(), Init(), QuestDeliver.ListDestThing(), OnCardAddedToZone(), OnSetPlaceState(), and WidgetSearch.Search().
Property Documentation
dbg
bool PropsManager.dbg get private
Definition at line 16 of file PropsManager.cs.
Referenced by OnSetPlaceState().
The documentation for this class was generated from the following file:
Elin/PropsManager.cs