Elin Decompiled Documentation: Critter Class Reference
Critter Class Reference
Public Member Functions
void Update ()
Static Public Member Functions
static Critter Create (Cell cell)
static void RebuildCritter (Cell cell)
Static Public Member Functions inherited from EClass
static int rnd (int a)
static int curve (int a, int start, int step, int rate=75)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Public Attributes
int tile
int index
Vector2 dir
float x
float y
float dirTimer
float animeTimer
float speed = 0.1f
bool reverse
Static Public Attributes
const float R = 0.12f
Static Public Attributes inherited from EClass
static Core core
Properties
virtual int[] animeTiles [get]
virtual int[] idleTiles [get]
virtual int AnimeTile [get]
virtual int IdleTile [get]
virtual int SnowTile [get]
virtual int Interval [get]
virtual float BaseSpeed [get]
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Detailed Description
Definition at line 4 of file Critter.cs.
Member Function Documentation
Create()
static Critter Critter.Create (Cell cell) inline static
Definition at line 62 of file Critter.cs.
    {
        BiomeProfile biomeProfile = cell.sourceFloor.biome ?? EClass.core.refs.biomes.Plain;
        if (biomeProfile == null)
        {
            return null;
        }
        if (cell.IsTopWater)
        {
            if (EClass.rnd(12) == 0)
            {
                return new CritterFish();
            }
            return null;
        }
        else
        {
            if (biomeProfile.id == BiomeID.Snow)
            {
                return null;
            }
            if (EClass.rnd(12) == 0)
            {
                return new CritterFrog();
            }
            if (EClass.rnd(6) == 0)
            {
                return new CritterFrogSmall();
            }
            if (EClass.rnd(12) == 0)
            {
                return new CritterCancer();
            }
            if (EClass.rnd(6) == 0)
            {
                return new CritterCancerSmall();
            }
            if (EClass.rnd(12) == 0)
            {
                return new CritterRat();
            }
            if (EClass.rnd(6) == 0)
            {
                return new CritterRatSmall();
            }
            if (EClass.rnd(12) == 0)
            {
                return new CritterRoach();
            }
            if (EClass.rnd(6) == 0)
            {
                return new CritterRoachSmall();
            }
            return new CritterRandom();
        }
    }
References EClass.core, BiomeProfile.id, Cell.IsTopWater, and EClass.rnd().
RebuildCritter()
static void Critter.RebuildCritter (Cell cell) inline static
Definition at line 119 of file Critter.cs.
    {
        cell.critter = null;
        if (cell.sourceObj.id == 68)
        {
            cell.critter = new CritterFish();
        }
    }
References Cell.sourceObj.
Referenced by PartialMap.Apply(), Map.Load(), Map.SetFloor(), and Map.SetObj().
Update()
void Critter.Update () inline
Definition at line 128 of file Critter.cs.
    {
        float gameDelta = Core.gameDelta;
        this.animeTimer -= gameDelta * this.speed * 100f;
        if (this.animeTimer < 0f)
        {
            this.index++;
            this.animeTimer = 2f;
        }
        if (this.dir.x != 0f || this.dir.y != 0f)
        {
            this.tile = this.AnimeTile;
        }
        else
        {
            this.tile = this.IdleTile;
        }
        this.dirTimer -= gameDelta;
        if (this.dirTimer < 0f)
        {
            this.dirTimer = (float)(this.Interval + EClass.rnd(this.Interval) / 2);
            this.dir.x = (float)(EClass.rnd(3) - 1);
            this.dir.y = (float)(EClass.rnd(3) - 1);
            this.speed = 0.01f * (float)(EClass.rnd(20) + 1) * this.BaseSpeed;
            this.reverse = (this.dir.x > 0f);
        }
        this.x += this.dir.x * gameDelta * this.speed;
        if (this.x > 0.12f)
        {
            this.x = 0.12f;
            this.dir.x = 0f;
        }
        else if (this.x < -0.12f)
        {
            this.x = -0.12f;
            this.dir.x = 0f;
        }
        this.y += this.dir.y * gameDelta * this.speed;
        if (this.y > 0.12f)
        {
            this.y = 0.12f;
            this.dir.y = 0f;
            return;
        }
        if (this.y < -0.12f)
        {
            this.y = -0.12f;
            this.dir.y = 0f;
        }
    }
References AnimeTile, animeTimer, BaseSpeed, dir, dirTimer, IdleTile, index, Interval, EClass.rnd(), speed, x, and y.
Referenced by BaseTileMap.DrawTile().
Member Data Documentation
animeTimer
float Critter.animeTimer
Definition at line 193 of file Critter.cs.
Referenced by Update().
dir
Vector2 Critter.dir
Definition at line 185 of file Critter.cs.
Referenced by Update().
dirTimer
float Critter.dirTimer
Definition at line 191 of file Critter.cs.
Referenced by Update().
index
int Critter.index
Definition at line 183 of file Critter.cs.
Referenced by Update().
R
const float Critter.R = 0.12f static
Definition at line 179 of file Critter.cs.
reverse
bool Critter.reverse
Definition at line 197 of file Critter.cs.
Referenced by BaseTileMap.DrawTile().
speed
float Critter.speed = 0.1f
Definition at line 195 of file Critter.cs.
Referenced by Update().
tile
int Critter.tile
Definition at line 181 of file Critter.cs.
Referenced by BaseTileMap.DrawTile().
x
float Critter.x
Definition at line 187 of file Critter.cs.
Referenced by Update().
y
float Critter.y
Definition at line 189 of file Critter.cs.
Referenced by Update().
Property Documentation
AnimeTile
virtual int Critter.AnimeTile get
Definition at line 22 of file Critter.cs.
    {
        get
        {
            return this.animeTiles[this.index % this.animeTiles.Length];
        }
    }
Referenced by Update().
animeTiles
virtual int [] Critter.animeTiles get
Definition at line 6 of file Critter.cs.
    {
        get
        {
            return null;
        }
    }
BaseSpeed
virtual float Critter.BaseSpeed get
Definition at line 54 of file Critter.cs.
    {
        get
        {
            return 1f;
        }
    }
Referenced by Update().
IdleTile
virtual int Critter.IdleTile get
Definition at line 30 of file Critter.cs.
    {
        get
        {
            return this.idleTiles[this.index % this.idleTiles.Length];
        }
    }
Referenced by Update().
idleTiles
virtual int [] Critter.idleTiles get
Definition at line 14 of file Critter.cs.
    {
        get
        {
            return null;
        }
    }
Interval
virtual int Critter.Interval get
Definition at line 46 of file Critter.cs.
    {
        get
        {
            return 5;
        }
    }
Referenced by Update().
SnowTile
virtual int Critter.SnowTile get
Definition at line 38 of file Critter.cs.
    {
        get
        {
            return 0;
        }
    }
Referenced by BaseTileMap.DrawTile().
The documentation for this class was generated from the following file:
Elin/Critter.cs