Elin Decompiled Documentation: SourceAsset Class Reference
SourceAsset Class Reference
Classes
class PrefData
class Prefs
Public Member Functions
void DoFix ()
void SavePrefs (string id="prefs")
void LoadPrefs ()
void LoadPrefs_bk ()
Static Public Member Functions
static void _SavePrefs (string id="prefs")
static void _LoadPrefs (string id="prefs")
Static Public Member Functions inherited from EScriptable
static int rnd (int a)
Public Attributes
string idLoad = "prefs"
UD_String_String renames
Properties
static string PrefPath [get]
Detailed Description
Definition at line 4 of file SourceAsset.cs.
Member Function Documentation
_LoadPrefs()
static void SourceAsset._LoadPrefs (string id = "prefs") inline static
Definition at line 64 of file SourceAsset.cs.
    {
        IO.CopyAs(PrefPath + id, PrefPath + id + "_loadbk");
        Prefs prefs = IO.LoadFile<Prefs>(PrefPath + id);
        foreach (SourceThing.Row row in EClass.sources.things.rows)
        {
            if (prefs.things.dict.ContainsKey(row.id))
            {
                row.pref = prefs.things.dict[row.id];
            }
            if (prefs.version == 0)
            {
                row.pref.y = 0f;
            }
        }
        Debug.Log("Imported Prefs:" + id);
    }
References Debug, SourceAsset.PrefData.dict, PrefPath, EClass.sources, SourceAsset.Prefs.things, SourceManager.things, and SourceAsset.Prefs.version.
Referenced by LoadPrefs(), and LoadPrefs_bk().
_SavePrefs()
static void SourceAsset._SavePrefs (string id = "prefs") inline static
Definition at line 33 of file SourceAsset.cs.
    {
        IO.CopyAs(PrefPath + id, PrefPath + id + "_bk");
        Prefs prefs = new Prefs();
        prefs.version = 2;
        Debug.Log(EClass.sources.things.rows.Count);
        foreach (SourceThing.Row row in EClass.sources.things.rows)
        {
            if (prefs.things.dict.ContainsKey(row.id))
            {
                Debug.LogError("exception: duplicate id:" + row.id + "/" + row.name);
            }
            else
            {
                prefs.things.dict.Add(row.id, row.pref);
            }
        }
        IO.SaveFile(PrefPath + id, prefs);
        Debug.Log("Exported Prefs:" + id);
    }
References Debug, SourceAsset.PrefData.dict, PrefPath, EClass.sources, SourceAsset.Prefs.things, and SourceManager.things.
Referenced by SavePrefs().
DoFix()
void SourceAsset.DoFix () inline
Definition at line 24 of file SourceAsset.cs.
    {
    }
LoadPrefs()
void SourceAsset.LoadPrefs () inline
Definition at line 54 of file SourceAsset.cs.
    {
        _LoadPrefs(idLoad);
    }
References _LoadPrefs(), and idLoad.
LoadPrefs_bk()
void SourceAsset.LoadPrefs_bk () inline
Definition at line 59 of file SourceAsset.cs.
    {
        _LoadPrefs(idLoad);
    }
References _LoadPrefs(), and idLoad.
SavePrefs()
void SourceAsset.SavePrefs (string id = "prefs") inline
Definition at line 28 of file SourceAsset.cs.
    {
        _SavePrefs(id);
    }
References _SavePrefs().
Member Data Documentation
idLoad
string SourceAsset.idLoad = "prefs"
Definition at line 18 of file SourceAsset.cs.
Referenced by LoadPrefs(), and LoadPrefs_bk().
renames
UD_String_String SourceAsset.renames
Definition at line 20 of file SourceAsset.cs.
Referenced by SourceThingV.RestorePref().
Property Documentation
PrefPath
string SourceAsset.PrefPath static get
Definition at line 22 of file SourceAsset.cs.
Referenced by _LoadPrefs(), and _SavePrefs().
The documentation for this class was generated from the following file:
Elin/SourceAsset.cs