Elin Decompiled Documentation: LayerNewspaper Class Reference
LayerNewspaper Class Reference
Public Member Functions
override void OnInit ()
void OnClickPage ()
void RefreshPage ()
void OnClickComic ()
async void RefreshNews ()
void RefreshAD ()
async void RefreshChat ()
async void RefreshVote ()
void RefreshWeather ()
Public Member Functions inherited from ELayer
override void OnBeforeAddLayer ()
void InitInspector ()
sealed override void Init ()
override void OnAfterAddLayer ()
void TryShowHelp ()
void AddLayerToUI (string id)
void TryShowHint (string _langHint=null)
void TalkHomeMemeber (string id)
void TalkMaid (string id)
override void OnRightClick ()
Public Attributes
UIText textDate
UIText textFortune
UIText textVote
UIText textVoteRemaining
UIList listChat
UIList listWeather
UIList listVote
UIList listNews
Image imageHeadline
Image imageAdRight
Image moldAdBottom
List< Sprite > spritesAd
List< Sprite > spritesSmallAd
List< Sprite > spritesHeadline
LayoutGroup layoutAdBottom
LayoutGroup layoutPortrait
Portrait moldPortrait
List< string > desiredNews
UIButton buttonPage
GameObject goTop
GameObject goBack
Sprite spriteComicBig
bool topPage
Properties
DayData data [get]
Properties inherited from ELayer
static Core core [get]
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static FactionBranch Branch [get]
static Faction Home [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static CoreConfig config [get]
static GameSetting setting [get]
static ColorProfile Colors [get]
static SourceManager sources [get]
static World world [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
bool IsFloat [get]
virtual string IdHelp [get]
Private Attributes
int seed
Additional Inherited Members
Static Public Member Functions inherited from ELayer
static int rnd (int a)
Protected Member Functions inherited from ELayer
sealed override void _Close ()
sealed override void Kill ()
Detailed Description
Definition at line 7 of file LayerNewspaper.cs.
Member Function Documentation
OnClickComic()
void LayerNewspaper.OnClickComic () inline
Definition at line 97 of file LayerNewspaper.cs.
    {
        SE.Play("click_recipe");
        ELayer.ui.AddLayer<LayerImage>().SetImage(spriteComicBig);
    }
References spriteComicBig, and ELayer.ui.
OnClickPage()
void LayerNewspaper.OnClickPage () inline
Definition at line 83 of file LayerNewspaper.cs.
    {
        topPage = !topPage;
        buttonPage.mainText.SetText((topPage ? "news_firstPage" : "news_secondPage").lang());
        SE.Play("click_scroll");
        RefreshPage();
    }
References buttonPage, RefreshPage(), and topPage.
OnInit()
override void LayerNewspaper.OnInit () inline
Definition at line 59 of file LayerNewspaper.cs.
    {
        if (ELayer.debug.enable)
        {
            NewsList.dict = null;
            ELayer.world.CreateDayData();
        }
        seed = (ELayer.debug.enable ? (-1) : ELayer.world.dayData.seed);
        Rand.UseSeed(seed, delegate
        {
            imageAdRight.sprite = spritesAd.RandomItem();
            imageAdRight.SetNativeSize();
        });
        textDate.text = "news_date".lang(Lang.GetList("monthEng")[ELayer.world.date.month - 1], ELayer.world.date.day.ToString() ?? "", ELayer.world.date.year.ToString() ?? "");
        int luck = (int)ELayer.world.dayData.luck;
        textFortune.text = "news_tellLuck".lang(Lang.GetList("dayLuck")[luck], Lang.GetList("dayLuck2")[luck]);
        RefreshAD();
        RefreshChat();
        RefreshVote();
        RefreshWeather();
        RefreshNews();
        RefreshPage();
    }
References World.CreateDayData(), World.date, Date.day, World.dayData, ELayer.debug, CoreDebug.enable, Lang.GetList(), imageAdRight, DayData.luck, RefreshAD(), RefreshChat(), RefreshNews(), RefreshPage(), RefreshVote(), RefreshWeather(), DayData.seed, seed, spritesAd, textFortune, Rand.UseSeed(), ELayer.world, and Date.year.
RefreshAD()
void LayerNewspaper.RefreshAD () inline
Definition at line 171 of file LayerNewspaper.cs.
    {
        Rand.SetSeed(seed);
        moldAdBottom = layoutAdBottom.CreateMold<Image>();
        float num = layoutAdBottom.Rect().sizeDelta.x - 20f;
        IList<Sprite> list = spritesSmallAd.Copy().Shuffle();
        for (int i = 0; i < list.Count; i++)
        {
            Sprite sprite = list[i];
            if (num > sprite.textureRect.width)
            {
                Image image = Util.Instantiate(moldAdBottom, layoutAdBottom);
                num = num - sprite.textureRect.width - 5f;
                image.sprite = sprite;
                image.SetNativeSize();
            }
        }
        layoutAdBottom.RebuildLayout();
        Rand.SetSeed();
    }
References layoutAdBottom, moldAdBottom, seed, Rand.SetSeed(), and spritesSmallAd.
Referenced by OnInit().
RefreshChat()
async void LayerNewspaper.RefreshChat () inline
Definition at line 192 of file LayerNewspaper.cs.
    {
        List<Net.ChatLog> logs = await Net.GetChat(ChatCategory.Test, Lang.langCode);
        if (isDestroyed || logs.Count == 0)
        {
            return;
        }
        listChat.callbacks = new UIList.Callback<Net.ChatLog, UIItem>
        {
            onInstantiate = delegate(Net.ChatLog a, UIItem b)
            {
                b.text1.SetText(a.msg);
            },
            onList = delegate
            {
                foreach (Net.ChatLog item in logs)
                {
                    listChat.Add(item);
                }
            }
        };
        listChat.List();
    }
References Net.GetChat(), item, Lang.langCode, and listChat.
Referenced by OnInit().
RefreshNews()
async void LayerNewspaper.RefreshNews () inline
Definition at line 103 of file LayerNewspaper.cs.
    {
        moldPortrait = layoutPortrait.CreateMold<Portrait>();
        List<NewsList.Item> list = NewsList.GetNews(seed);
        if (desiredNews.Count > 0)
        {
            for (int i = 0; i < desiredNews.Count; i++)
            {
                foreach (NewsList.Item item2 in NewsList.listAll)
                {
                    if (item2.title.Contains(desiredNews[i]))
                    {
                        list[i] = item2;
                        break;
                    }
                }
            }
        }
        listNews.callbacks = new UIList.Callback<NewsList.Item, UIItem>
        {
            onInstantiate = delegate(NewsList.Item a, UIItem b)
            {
                b.text1.text = a.title;
                b.text2.SetText(a.content);
            },
            onList = delegate
            {
                foreach (NewsList.Item item3 in list)
                {
                    listNews.Add(item3);
                }
            }
        };
        listNews.List();
        Rand.UseSeed(seed, delegate
        {
            imageHeadline.sprite = spritesHeadline.RandomItem();
        });
        foreach (NewsList.Item item4 in list)
        {
            List<string> listImageId = item4.listImageId;
            if (listImageId.Count == 0)
            {
                continue;
            }
            Sprite sprite = Resources.Load<Sprite>("UI/Layer/LayerNewspaper/Headline/headline_" + listImageId[0]);
            if (!sprite)
            {
                continue;
            }
            imageHeadline.sprite = sprite;
            if (listImageId.Count <= 1)
            {
                break;
            }
            for (int j = 1; j < listImageId.Count; j++)
            {
                ModItem<Sprite> item = Portrait.modPortraits.GetItem(listImageId[j], returnNull: true);
                if (item != null)
                {
                    Util.Instantiate(moldPortrait, layoutPortrait).SetPortrait(item.id);
                }
            }
            layoutPortrait.RebuildLayout();
            break;
        }
    }
References desiredNews, ModItemList< T >.GetItem(), NewsList.GetNews(), item, layoutPortrait, NewsList.listAll, listNews, Portrait.modPortraits, moldPortrait, seed, spritesHeadline, NewsList.Item.title, and Rand.UseSeed().
Referenced by OnInit().
RefreshPage()
void LayerNewspaper.RefreshPage () inline
Definition at line 91 of file LayerNewspaper.cs.
    {
        goTop.SetActive(topPage);
        goBack.SetActive(!topPage);
    }
References goBack, goTop, and topPage.
Referenced by OnClickPage(), and OnInit().
RefreshVote()
async void LayerNewspaper.RefreshVote () inline
Definition at line 216 of file LayerNewspaper.cs.
    {
        List<Net.VoteLog> logs = await Net.GetVote(Lang.langCode);
        if (isDestroyed || logs.Count == 0)
        {
            return;
        }
        textVote.SetText(logs[0].name.StripBrackets());
        int num = (int)DateTime.UtcNow.Subtract(new DateTime(1970, 1, 1)).TotalSeconds;
        int num2 = (logs[0].time - num) / 60 / 60 / 24;
        textVoteRemaining.SetText("news_voteLeft".lang(num2.ToString() ?? ""));
        logs.RemoveAt(0);
        logs.Sort((Net.VoteLog a, Net.VoteLog b) => b.count - a.count);
        listVote.callbacks = new UIList.Callback<Net.VoteLog, UIItem>
        {
            onInstantiate = delegate(Net.VoteLog a, UIItem b)
            {
                b.text1.SetText(a.name);
                b.text2.SetText(a.count.ToString() ?? "");
                b.button1.SetOnClick(delegate
                {
                    SE.Click();
                    Net.SendVote(a.index, Lang.langCode);
                    a.count++;
                    b.text2.SetText(a.count.ToString() ?? "");
                    foreach (UIList.ButtonPair button in listVote.buttons)
                    {
                        (button.component as UIItem).button1.SetActive(enable: false);
                    }
                });
            },
            onList = delegate
            {
                foreach (Net.VoteLog item in logs)
                {
                    listVote.Add(item);
                }
            }
        };
        listVote.List();
    }
References Net.GetVote(), item, Lang.langCode, listVote, Net.SendVote(), textVote, and textVoteRemaining.
Referenced by OnInit().
RefreshWeather()
void LayerNewspaper.RefreshWeather () inline
Definition at line 258 of file LayerNewspaper.cs.
    {
        List<Weather.WeatherForecast> list = ELayer.world.weather.GetWeatherForecast();
        listWeather.callbacks = new UIList.Callback<Weather.WeatherForecast, UIItem>
        {
            onInstantiate = delegate(Weather.WeatherForecast a, UIItem b)
            {
                string text = a.date.month + "/" + a.date.day;
                foreach (KeyValuePair<Weather.Condition, int> item in a.cons.OrderByDescending((KeyValuePair<Weather.Condition, int> a) => a.Value))
                {
                    if (b.image1.sprite == null)
                    {
                        b.image1.sprite = ELayer.core.refs.icons.weather[item.Key];
                    }
                    else if (b.image2.sprite == null)
                    {
                        b.image2.sprite = ELayer.core.refs.icons.weather[item.Key];
                        b.image2.SetActive(enable: true);
                    }
                }
                b.text1.text = text;
            },
            onList = delegate
            {
                for (int i = 0; i < 7; i++)
                {
                    if (list.Count > i && list[i].cons.Count > 0)
                    {
                        listWeather.Add(list[i]);
                    }
                }
            }
        };
        listWeather.List();
    }
References ELayer.core, Weather.WeatherForecast.date, Date.day, Weather.GetWeatherForecast(), CoreRef.icons, item, listWeather, Core.refs, CoreRef.Icons.weather, World.weather, and ELayer.world.
Referenced by OnInit().
Member Data Documentation
buttonPage
UIButton LayerNewspaper.buttonPage
Definition at line 45 of file LayerNewspaper.cs.
Referenced by OnClickPage().
desiredNews
List<string> LayerNewspaper.desiredNews
Definition at line 43 of file LayerNewspaper.cs.
Referenced by RefreshNews().
goBack
GameObject LayerNewspaper.goBack
Definition at line 49 of file LayerNewspaper.cs.
Referenced by RefreshPage().
goTop
GameObject LayerNewspaper.goTop
Definition at line 47 of file LayerNewspaper.cs.
Referenced by RefreshPage().
imageAdRight
Image LayerNewspaper.imageAdRight
Definition at line 27 of file LayerNewspaper.cs.
Referenced by OnInit().
imageHeadline
Image LayerNewspaper.imageHeadline
Definition at line 25 of file LayerNewspaper.cs.
layoutAdBottom
LayoutGroup LayerNewspaper.layoutAdBottom
Definition at line 37 of file LayerNewspaper.cs.
Referenced by RefreshAD().
layoutPortrait
LayoutGroup LayerNewspaper.layoutPortrait
Definition at line 39 of file LayerNewspaper.cs.
Referenced by RefreshNews().
listChat
UIList LayerNewspaper.listChat
Definition at line 17 of file LayerNewspaper.cs.
Referenced by RefreshChat().
listNews
UIList LayerNewspaper.listNews
Definition at line 23 of file LayerNewspaper.cs.
Referenced by RefreshNews().
listVote
UIList LayerNewspaper.listVote
Definition at line 21 of file LayerNewspaper.cs.
Referenced by RefreshVote().
listWeather
UIList LayerNewspaper.listWeather
Definition at line 19 of file LayerNewspaper.cs.
Referenced by RefreshWeather().
moldAdBottom
Image LayerNewspaper.moldAdBottom
Definition at line 29 of file LayerNewspaper.cs.
Referenced by RefreshAD().
moldPortrait
Portrait LayerNewspaper.moldPortrait
Definition at line 41 of file LayerNewspaper.cs.
Referenced by RefreshNews().
seed
int LayerNewspaper.seed private
Definition at line 55 of file LayerNewspaper.cs.
Referenced by OnInit(), RefreshAD(), and RefreshNews().
spriteComicBig
Sprite LayerNewspaper.spriteComicBig
Definition at line 51 of file LayerNewspaper.cs.
Referenced by OnClickComic().
spritesAd
List<Sprite> LayerNewspaper.spritesAd
Definition at line 31 of file LayerNewspaper.cs.
Referenced by OnInit().
spritesHeadline
List<Sprite> LayerNewspaper.spritesHeadline
Definition at line 35 of file LayerNewspaper.cs.
Referenced by RefreshNews().
spritesSmallAd
List<Sprite> LayerNewspaper.spritesSmallAd
Definition at line 33 of file LayerNewspaper.cs.
Referenced by RefreshAD().
textDate
UIText LayerNewspaper.textDate
Definition at line 9 of file LayerNewspaper.cs.
textFortune
UIText LayerNewspaper.textFortune
Definition at line 11 of file LayerNewspaper.cs.
Referenced by OnInit().
textVote
UIText LayerNewspaper.textVote
Definition at line 13 of file LayerNewspaper.cs.
Referenced by RefreshVote().
textVoteRemaining
UIText LayerNewspaper.textVoteRemaining
Definition at line 15 of file LayerNewspaper.cs.
Referenced by RefreshVote().
topPage
bool LayerNewspaper.topPage
Definition at line 53 of file LayerNewspaper.cs.
Referenced by OnClickPage(), and RefreshPage().
Property Documentation
data
DayData LayerNewspaper.data get
Definition at line 57 of file LayerNewspaper.cs.
The documentation for this class was generated from the following file:
Elin/LayerNewspaper.cs