Elin Decompiled Documentation: TCExtraProgress Class Reference
TCExtraProgress Class Reference
Public Types
enum ProgressType { Gene }
Public Member Functions
override void OnSetOwner ()
void Refresh ()
Public Member Functions inherited from TCUI
override void OnDraw (ref Vector3 pos)
void DrawImmediate (ref Vector3 pos)
Public Member Functions inherited from TC
void SetOwner (CardRenderer r)
virtual void OnSetOwner ()
virtual void OnDraw (ref Vector3 pos)
void Kill ()
virtual void OnKill ()
Public Attributes
ProgressType progressType
GameObject goBar
Image bar
Image bgBar
UIText textProgress
float refreshInterval
Public Attributes inherited from TC
CardRenderer render
Private Member Functions
void Update ()
Private Attributes
float timer
Additional Inherited Members
Static Public Member Functions inherited from EMono
static int rnd (int a)
Static Public Attributes inherited from TC
static GameSetting.RenderSetting.TCSetting _setting
Static Public Attributes inherited from EMono
static Core core
Protected Member Functions inherited from TCUI
virtual void Awake ()
Protected Attributes inherited from TCUI
Vector3 lastPos
Properties inherited from TCUI
override bool isUI [get]
override Vector3 FixPos [get]
Properties inherited from TC
Card owner [get]
virtual bool isUI [get]
virtual Vector3 FixPos [get]
Properties inherited from EMono
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SoundManager Sound [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static CoreDebug debug [get]
Detailed Description
Definition at line 4 of file TCExtraProgress.cs.
Member Enumeration Documentation
ProgressType
enum TCExtraProgress.ProgressType
Enumerator
Gene
Definition at line 6 of file TCExtraProgress.cs.
    {
        Gene
    }
Member Function Documentation
OnSetOwner()
override void TCExtraProgress.OnSetOwner () inline virtual
Reimplemented from TC.
Definition at line 25 of file TCExtraProgress.cs.
    {
        Refresh();
    }
References Refresh().
Refresh()
void TCExtraProgress.Refresh () inline
Definition at line 40 of file TCExtraProgress.cs.
    {
        if (base.owner == null)
        {
            return;
        }
        TraitGeneMachine traitGeneMachine = base.owner.trait as TraitGeneMachine;
        bool flag = base.owner.isOn && base.owner.IsInstalled && traitGeneMachine.IsTargetUsingGene();
        goBar.SetActive(flag);
        if (flag)
        {
            float progress = traitGeneMachine.GetProgress();
            bar.rectTransform.sizeDelta = new Vector2(progress * bgBar.rectTransform.sizeDelta.x, bgBar.rectTransform.sizeDelta.y);
            if ((bool)textProgress)
            {
                textProgress.text = traitGeneMachine.GetProgressText();
            }
        }
    }
References bgBar, TraitGeneMachine.GetProgress(), TraitGeneMachine.GetProgressText(), goBar, TraitGeneMachine.IsTargetUsingGene(), and textProgress.
Referenced by OnSetOwner(), and Update().
Update()
void TCExtraProgress.Update () inline private
Definition at line 30 of file TCExtraProgress.cs.
    {
        timer -= Core.delta;
        if (timer < 0f)
        {
            timer += refreshInterval;
            Refresh();
        }
    }
References Core.delta, Refresh(), refreshInterval, and timer.
Member Data Documentation
bar
Image TCExtraProgress.bar
Definition at line 15 of file TCExtraProgress.cs.
bgBar
Image TCExtraProgress.bgBar
Definition at line 17 of file TCExtraProgress.cs.
Referenced by Refresh().
goBar
GameObject TCExtraProgress.goBar
Definition at line 13 of file TCExtraProgress.cs.
Referenced by Refresh().
progressType
ProgressType TCExtraProgress.progressType
Definition at line 11 of file TCExtraProgress.cs.
refreshInterval
float TCExtraProgress.refreshInterval
Definition at line 21 of file TCExtraProgress.cs.
Referenced by Update().
textProgress
UIText TCExtraProgress.textProgress
Definition at line 19 of file TCExtraProgress.cs.
Referenced by Refresh().
timer
float TCExtraProgress.timer private
Definition at line 23 of file TCExtraProgress.cs.
Referenced by Update().
The documentation for this class was generated from the following file:
Elin/TCExtraProgress.cs