Elin Decompiled Documentation: ButtonRoster Class Reference
ButtonRoster Class Reference
Public Member Functions
void SetChara (Chara c)
void Refresh ()
override void OnPointerEnter (PointerEventData eventData)
override void OnPointerExit (PointerEventData eventData)
Public Member Functions inherited from UIButton
virtual bool CanMiddleClick ()
virtual void OnMiddleClick (bool forceClick)
void SetItem (Item i)
virtual void RefreshItem ()
virtual void OnHover ()
void Toggle ()
void ToggleCheck ()
void SetCheck (bool check)
void SetToggle (bool isOn, Action< bool > onToggle=null)
void SetToggleWithScore (bool isOn, Action< bool > onToggle, int? score)
void SetTooltip (Action< UITooltip > onShowTooltip=null, bool enable=true)
void SetTooltip (string id, Action< UITooltip > onShowTooltip=null, bool enable=true)
void SetTooltipLang (string lang=null)
virtual void ShowTooltip ()
void ShowTooltipForced (bool ignoreWhenRightClick=true)
override void OnPointerDown (PointerEventData eventData)
override void OnPointerClick (PointerEventData eventData)
override void OnPointerUp (PointerEventData eventData)
void OnPointerUpOnDrag (PointerEventData eventData)
void _OnPress ()
void OnPress ()
void AddHighlight (Func< bool > killCondition)
void DoHighlightTransition (bool instant=false)
void DoNormalTransition (bool instant=true)
override Selectable FindSelectableOnDown ()
override Selectable FindSelectableOnUp ()
override Selectable FindSelectableOnLeft ()
override Selectable FindSelectableOnRight ()
void SetNavigation (UIButton up, UIButton down=null, UIButton left=null, UIButton right=null)
override bool IsActive ()
void SetInteractableWithAlpha (bool enable)
virtual void ApplySkin ()
void ApplySkin ()
Public Attributes
Chara chara
float iconPivot
Image barMood
UIText textName
RectTransform rect
Portrait portrait
Public Attributes inherited from UIButton
UIText mainText
UIText subText
UIText subText2
UIText keyText
Image icon
Image imageCheck
Graphic[] targetGraphics
float scaleIcon = 1f
float slideX
float navigationFix
bool isChecked
bool instantClick = true
UISelectableGroup group
TooltipData tooltip
SoundData soundClick
SoundData soundHighlight
Transform animeTarget
Anime animeClick
Anime animeHold
ButtonType buttonType
BaseSkinRoot skinRoot
Action onDoubleClick
Action onRightClick
Action< int > onInputWheel
object refObj
int refInt
string refStr
bool animating
bool selected
Vector3 originalIconScale = Vector3.one
UIButton highlightTarget
Item item
Properties
WidgetRoster roster [get]
Properties inherited from UIButton
List< Graphic > Graphics [get]
virtual bool CanDragLeftButton [get]
Static Private Attributes
static Gradient gradient
Additional Inherited Members
Static Public Member Functions inherited from UIButton
static void UpdateButtons ()
static void TryHihlight ()
static void TryShowTip (Transform root=null, bool highlight=true, bool ignoreWhenRightClick=true)
static void TryShowTip< T > (Transform root=null, bool highlight=true, bool ignoreWhenRightClick=false)
Static Public Attributes inherited from UIButton
static bool DoSlide
static bool locked
static UIButton lastButton
static UIButton lastHovered
static UIButton currentHighlight
static UIButton currentPressedButton
static float lastClicked
static float doubleClickTime = 0.4f
static Vector2 buttonPos
static Action onPressed
static List< UIButton > buttons = new List<UIButton>()
static Action actionTooltip
Protected Member Functions inherited from UIButton
override void Awake ()
override void OnEnable ()
override void DoStateTransition (SelectionState state, bool instant)
Detailed Description
Definition at line 5 of file ButtonRoster.cs.
Member Function Documentation
OnPointerEnter()
override void ButtonRoster.OnPointerEnter (PointerEventData eventData) inline
Definition at line 79 of file ButtonRoster.cs.
    {
        if ((bool)WidgetMouseover.Instance)
        {
            WidgetMouseover.Instance.roster = chara;
        }
    }
References chara, and WidgetMouseover.Instance.
OnPointerExit()
override void ButtonRoster.OnPointerExit (PointerEventData eventData) inline
Definition at line 87 of file ButtonRoster.cs.
    {
        if ((bool)WidgetMouseover.Instance)
        {
            WidgetMouseover.Instance.roster = null;
        }
    }
References WidgetMouseover.Instance.
Refresh()
void ButtonRoster.Refresh () inline
Definition at line 35 of file ButtonRoster.cs.
    {
        if (gradient == null)
        {
            gradient = EClass.Colors.Dark.gradients["mood"];
        }
        float num = Mathf.Clamp((float)chara.hp / (float)chara.MaxHP, 0f, 1f);
        barMood.Rect().localScale = new Vector3(num, 1f, 1f);
        barMood.color = gradient.Evaluate(num);
        Color c = EClass.Colors.Dark.gradientHP.Evaluate((float)chara.hp / (float)chara.MaxHP);
        mainText.text = "".TagColor(c, chara.hp.ToString() ?? "");
        mainText.SetActive(roster.extra.showHP);
        if (roster.extra.showHP)
        {
            textName.SetText(chara.NameSimple);
        }
        else
        {
            textName.text = "".TagColor(c, chara.NameSimple);
        }
        textName.SetActive(roster.extra.onlyName);
        this.SetOnClick(delegate
        {
            bool flag = EClass.ui.IsActive;
            if (flag)
            {
                LayerInventory layer = EClass.ui.GetLayer<LayerInventory>();
                if ((bool)layer && layer.Inv.owner.IsPCFaction && layer.Inv.currency == CurrencyType.None)
                {
                    flag = false;
                }
            }
            if (chara.IsPC || chara.IsDisabled || !EClass.pc.HasNoGoal || flag)
            {
                SE.Beep();
            }
            else
            {
                EClass.ui.CloseLayers();
                LayerInventory.CreateContainer(chara);
            }
        });
    }
References barMood, chara, Color, EClass.Colors, LayerInventory.CreateContainer(), InvOwner.currency, ColorProfile.Dark, WidgetRoster.extra, gradient, SkinColorProfile.gradientHP, SkinColorProfile.gradients, Chara.HasNoGoal, Card.hp, LayerInventory.Inv, Chara.IsDisabled, Chara.IsPC, Card.IsPCFaction, UIButton.mainText, Chara.MaxHP, Card.NameSimple, WidgetRoster.Extra.onlyName, InvOwner.owner, EClass.pc, roster, UIText.SetText(), WidgetRoster.Extra.showHP, textName, and EClass.ui.
Referenced by WidgetRoster.Refresh(), and SetChara().
SetChara()
void ButtonRoster.SetChara (Chara c) inline
Definition at line 23 of file ButtonRoster.cs.
    {
        chara = c;
        chara.SetImage(icon);
        bool flag = roster.extra.portrait && !chara.GetIdPortrait().IsEmpty();
        portrait.SetChara(c);
        portrait.SetActive(flag && !roster.extra.onlyName);
        icon.enabled = !flag && !roster.extra.onlyName;
        icon.rectTransform.anchoredPosition = new Vector2(0f, roster.extra.width / 2);
        Refresh();
    }
References chara, WidgetRoster.extra, Chara.GetIdPortrait(), UIButton.icon, WidgetRoster.Extra.onlyName, portrait, Refresh(), roster, Portrait.SetChara(), Card.SetImage(), and WidgetRoster.Extra.width.
Referenced by WidgetRoster.Add().
Member Data Documentation
barMood
Image ButtonRoster.barMood
Definition at line 11 of file ButtonRoster.cs.
Referenced by Refresh().
chara
Chara ButtonRoster.chara
Definition at line 7 of file ButtonRoster.cs.
Referenced by OnPointerEnter(), WidgetRoster.OnSetContextMenu(), Refresh(), and SetChara().
gradient
Gradient ButtonRoster.gradient static private
Definition at line 19 of file ButtonRoster.cs.
Referenced by Refresh().
iconPivot
float ButtonRoster.iconPivot
Definition at line 9 of file ButtonRoster.cs.
portrait
Portrait ButtonRoster.portrait
Definition at line 17 of file ButtonRoster.cs.
Referenced by SetChara().
rect
RectTransform ButtonRoster.rect
Definition at line 15 of file ButtonRoster.cs.
textName
UIText ButtonRoster.textName
Definition at line 13 of file ButtonRoster.cs.
Referenced by Refresh().
Property Documentation
roster
WidgetRoster ButtonRoster.roster get
Definition at line 21 of file ButtonRoster.cs.
Referenced by Refresh(), and SetChara().
The documentation for this class was generated from the following file:
Elin/ButtonRoster.cs