Elin Decompiled Documentation: Applibot.UICustomBlend Class Reference
Applibot.UICustomBlend Class Reference
Public Types
enum MyCustomBlendMode : byte {
Normal , LinearDodge , Darken , Multiply ,
Subtract , Lighten
}
Protected Member Functions
override void UpdateMaterial (Material baseMaterial)
Protected Member Functions inherited from Applibot.CustomImageBase
virtual void UpdateMaterial (Material baseMaterial)
void OnEnable ()
void OnDisable ()
void OnDestroy ()
Private Attributes
MyCustomBlendMode _blendMode
readonly int _SrcFactor = Shader.PropertyToID("_SrcFactor")
readonly int _DstFactor = Shader.PropertyToID("_DstFactor")
readonly int _BlendOp = Shader.PropertyToID("_BlendOp")
Additional Inherited Members
Public Member Functions inherited from Applibot.CustomImageBase
Material GetModifiedMaterial (Material baseMaterial)
void DestroyMaterial ()
Protected Attributes inherited from Applibot.CustomImageBase
Material material
Properties inherited from Applibot.CustomImageBase
CanvasScaler canvasScaler [get]
Graphic graphic [get]
Detailed Description
Definition at line 6 of file UICustomBlend.cs.
Member Enumeration Documentation
MyCustomBlendMode
enum Applibot.UICustomBlend.MyCustomBlendMode : byte
Enumerator
Normal
LinearDodge
Darken
Multiply
Subtract
Lighten
Definition at line 8 of file UICustomBlend.cs.
    {
        Normal,
        LinearDodge,
        Darken,
        Multiply,
        Subtract,
        Lighten
    }
Member Function Documentation
UpdateMaterial()
override void Applibot.UICustomBlend.UpdateMaterial (Material baseMaterial) inline protected virtual
Reimplemented from Applibot.CustomImageBase.
Definition at line 27 of file UICustomBlend.cs.
    {
        if (material == null)
        {
            material = new Material(Shader.Find("Applibot/UI/CustomBlend"));
            material.hideFlags = HideFlags.HideAndDontSave;
        }
        material.enabledKeywords = new LocalKeyword[0];
        switch (_blendMode)
        {
        case MyCustomBlendMode.Normal:
            material.SetInt(_SrcFactor, 1);
            material.SetInt(_DstFactor, 10);
            material.SetInt(_BlendOp, 0);
            break;
        case MyCustomBlendMode.LinearDodge:
            material.SetInt(_SrcFactor, 5);
            material.SetInt(_DstFactor, 1);
            material.SetInt(_BlendOp, 0);
            break;
        case MyCustomBlendMode.Multiply:
            material.SetInt(_SrcFactor, 0);
            material.SetInt(_DstFactor, 3);
            material.SetInt(_BlendOp, 0);
            break;
        case MyCustomBlendMode.Darken:
            material.SetInt(_SrcFactor, 1);
            material.SetInt(_DstFactor, 1);
            material.SetInt(_BlendOp, 3);
            break;
        case MyCustomBlendMode.Subtract:
            material.SetInt(_SrcFactor, 1);
            material.SetInt(_DstFactor, 1);
            material.SetInt(_BlendOp, 2);
            break;
        case MyCustomBlendMode.Lighten:
            material.SetInt(_SrcFactor, 1);
            material.SetInt(_DstFactor, 1);
            material.SetInt(_BlendOp, 4);
            break;
        }
        material.EnableKeyword(_blendMode.ToString());
    }
References Applibot.UICustomBlend._blendMode, Applibot.UICustomBlend._BlendOp, Applibot.UICustomBlend._DstFactor, Applibot.UICustomBlend._SrcFactor, Material, and Applibot.CustomImageBase.material.
Member Data Documentation
_blendMode
MyCustomBlendMode Applibot.UICustomBlend._blendMode private
Definition at line 19 of file UICustomBlend.cs.
Referenced by Applibot.UICustomBlend.UpdateMaterial().
_BlendOp
readonly int Applibot.UICustomBlend._BlendOp = Shader.PropertyToID("_BlendOp") private
Definition at line 25 of file UICustomBlend.cs.
Referenced by Applibot.UICustomBlend.UpdateMaterial().
_DstFactor
readonly int Applibot.UICustomBlend._DstFactor = Shader.PropertyToID("_DstFactor") private
Definition at line 23 of file UICustomBlend.cs.
Referenced by Applibot.UICustomBlend.UpdateMaterial().
_SrcFactor
readonly int Applibot.UICustomBlend._SrcFactor = Shader.PropertyToID("_SrcFactor") private
Definition at line 21 of file UICustomBlend.cs.
Referenced by Applibot.UICustomBlend.UpdateMaterial().
The documentation for this class was generated from the following file:
Elin/Plugins.UI/Applibot/UICustomBlend.cs