Elin Decompiled Documentation: FactionManager Class Reference
FactionManager Class Reference
Public Member Functions
void AssignUID (Faction s)
void OnCreateGame ()
void OnLoad ()
T Find< T > (string id)
Faction Find (string id)
Public Attributes
Dictionary< string, Faction > dictAll = new Dictionary<string, Faction>()
new Faction Home
new Faction Wilds
GuildFighter Fighter
GuildMage Mage
GuildThief Thief
GuildMerchant Merchant
Additional Inherited Members
Static Public Member Functions inherited from EClass
static int rndSeed (int a, int seed)
static int rnd (long a)
static int rnd (int a)
static int curve (int _a, int start, int step, int rate=75)
static int sqrt (int a)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Static Public Attributes inherited from EClass
static Core core
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Detailed Description
Definition at line 5 of file FactionManager.cs.
Member Function Documentation
AssignUID()
void FactionManager.AssignUID (Faction s) inline
Definition at line 28 of file FactionManager.cs.
    {
        Faction faction = dictAll.TryGetValue(s.id);
        if (faction != null)
        {
            Debug.LogError("exception: Faction id already exists:" + faction.id);
        }
        s.uid = s.id;
        dictAll.Add(s.uid, s);
    }
References Debug, dictAll, Faction.id, and Faction.uid.
Referenced by Faction.Init().
Find()
Faction FactionManager.Find (string id) inline
Definition at line 67 of file FactionManager.cs.
    {
        foreach (Faction value in dictAll.Values)
        {
            if (value.id == id)
            {
                return value;
            }
        }
        return null;
    }
References dictAll, and Faction.id.
Referenced by Game._Create(), Find< T >(), and OnCreateGame().
Find< T >()
T FactionManager.Find< T > (string id) inline
Type Constraints
T : Faction
Definition at line 62 of file FactionManager.cs.
                                        : Faction
    {
        return Find(id) as T;
    }
References Find().
OnCreateGame()
void FactionManager.OnCreateGame () inline
Definition at line 39 of file FactionManager.cs.
    {
        foreach (SourceFaction.Row row in EClass.sources.factions.rows)
        {
            Faction.Create(row);
        }
        Home = Find("home");
        Home.relation.type = FactionRelation.RelationType.Owner;
        Wilds = Find("wilds");
        Fighter = Find<GuildFighter>("guild_fighter");
        Mage = Find<GuildMage>("guild_mage");
        Thief = Find<GuildThief>("guild_thief");
        Merchant = Find<GuildMerchant>("guild_merchant");
    }
References Faction.Create(), SourceManager.factions, Fighter, Find(), Home, Mage, Merchant, EClass.sources, Thief, and Wilds.
Referenced by Game._Create().
OnLoad()
void FactionManager.OnLoad () inline
Definition at line 54 of file FactionManager.cs.
    {
        foreach (Faction value in dictAll.Values)
        {
            value.OnLoad();
        }
    }
References dictAll, and Faction.OnLoad().
Referenced by Game.OnLoad().
Member Data Documentation
dictAll
Dictionary<string, Faction> FactionManager.dictAll = new Dictionary<string, Faction>()
Definition at line 8 of file FactionManager.cs.
Referenced by AssignUID(), Find(), Faction.GetFactionSalary(), OnLoad(), LayerFactions.RefreshFactions(), and ContentFaction.RefreshFactions().
Fighter
GuildFighter FactionManager.Fighter
Definition at line 17 of file FactionManager.cs.
Referenced by OnCreateGame().
Home
new Faction FactionManager.Home
Definition at line 11 of file FactionManager.cs.
Referenced by OnCreateGame().
Mage
GuildMage FactionManager.Mage
Definition at line 20 of file FactionManager.cs.
Referenced by OnCreateGame().
Merchant
GuildMerchant FactionManager.Merchant
Definition at line 26 of file FactionManager.cs.
Referenced by DramaOutcome.guild_join(), DramaOutcome.guild_trial(), and OnCreateGame().
Thief
GuildThief FactionManager.Thief
Definition at line 23 of file FactionManager.cs.
Referenced by OnCreateGame().
Wilds
new Faction FactionManager.Wilds
Definition at line 14 of file FactionManager.cs.
Referenced by OnCreateGame(), ContentPopulation.Refresh(), and FactionBranch.RemoveMemeber().
The documentation for this class was generated from the following file:
Elin/FactionManager.cs