Elin Decompiled Documentation: MOD Class Reference
MOD Class Reference
Static Public Member Functions
static void ResetResources ()
Static Public Attributes
static Dictionary< string, LangSetting > langs = new Dictionary<string, LangSetting>()
static ExcelDataList listAlias = new ExcelDataList()
static ExcelDataList listName = new ExcelDataList()
static TalkDataList listTalk = new TalkDataList()
static GodTalkDataList listGodTalk = new GodTalkDataList()
static ToneDataList tones = new ToneDataList()
static ExcelDataList actorSources = new ExcelDataList()
static ModItemList< Sprite > sprites = new ModItemList<Sprite>()
static Action< DirectoryInfo > OnAddPcc
static List< FileInfo > listMaps = new List<FileInfo>()
static List< FileInfo > listPartialMaps = new List<FileInfo>()
static Dictionary< string, FileInfo > sounds = new Dictionary<string, FileInfo>()
Detailed Description
Definition at line 6 of file MOD.cs.
Member Function Documentation
ResetResources()
static void MOD.ResetResources () inline static
Definition at line 32 of file MOD.cs.
    {
        langs.Clear();
        listAlias.Clear();
        listName.Clear();
        listTalk.Clear();
        listGodTalk.Clear();
        tones.Clear();
        actorSources.Clear();
        sprites = new ModItemList<Sprite>();
        listMaps.Clear();
        listPartialMaps.Clear();
        sounds.Clear();
    }
References actorSources, ExcelDataList.Clear(), langs, listAlias, listGodTalk, listMaps, listName, listPartialMaps, listTalk, sounds, sprites, and tones.
Referenced by Core.Awake().
Member Data Documentation
actorSources
ExcelDataList MOD.actorSources = new ExcelDataList() static
Definition at line 20 of file MOD.cs.
Referenced by BaseModPackage.Parse(), and ResetResources().
langs
Dictionary<string, LangSetting> MOD.langs = new Dictionary<string, LangSetting>() static
Definition at line 8 of file MOD.cs.
Referenced by ModPackage.AddOrUpdateLang(), Lang.Init(), BaseModManager.InitLang(), LayerConfig.Refresh(), ResetResources(), and UI.ShowLang().
listAlias
ExcelDataList MOD.listAlias = new ExcelDataList() static
Definition at line 10 of file MOD.cs.
Referenced by BaseModManager.InitLang(), and ResetResources().
listGodTalk
GodTalkDataList MOD.listGodTalk = new GodTalkDataList() static
Definition at line 16 of file MOD.cs.
Referenced by Religion.GetGodTalk(), BaseModManager.InitLang(), and ResetResources().
listMaps
List<FileInfo> MOD.listMaps = new List<FileInfo>() static
Definition at line 26 of file MOD.cs.
Referenced by TraitMoongate.ListSavedUserMap(), ModPackage.ParseMap(), and ResetResources().
listName
ExcelDataList MOD.listName = new ExcelDataList() static
Definition at line 12 of file MOD.cs.
Referenced by BaseModManager.InitLang(), and ResetResources().
listPartialMaps
List<FileInfo> MOD.listPartialMaps = new List<FileInfo>() static
Definition at line 28 of file MOD.cs.
Referenced by ModPackage.ParseMapPiece(), PartialMapMenu.Refresh(), and ResetResources().
listTalk
TalkDataList MOD.listTalk = new TalkDataList() static
Definition at line 14 of file MOD.cs.
Referenced by Person.GetDramaTitle(), Card.GetTalkText(), Card.HasTalk(), BaseModManager.InitLang(), ResetResources(), and Card.SetRandomTalk().
OnAddPcc
Action<DirectoryInfo> MOD.OnAddPcc static
Definition at line 24 of file MOD.cs.
Referenced by Core.Awake(), and BaseModPackage.Parse().
sounds
Dictionary<string, FileInfo> MOD.sounds = new Dictionary<string, FileInfo>() static
Definition at line 30 of file MOD.cs.
Referenced by ModPackage.ParseSound(), CoreRef.RefreshBGM(), and ResetResources().
sprites
ModItemList<Sprite> MOD.sprites = new ModItemList<Sprite>() static
Definition at line 22 of file MOD.cs.
Referenced by Scene.InitPass(), BaseModPackage.Parse(), and ResetResources().
tones
ToneDataList MOD.tones = new ToneDataList() static
Definition at line 18 of file MOD.cs.
Referenced by Card.ApplyTone(), BaseModManager.InitLang(), ResetResources(), and Card.SetRandomTone().
The documentation for this class was generated from the following file:
Elin/Plugins.basecore/MOD.cs