Elin Decompiled Documentation: Mosframe.ScrollbarHandleSize Class Reference
Mosframe.ScrollbarHandleSize Class Reference
Public Member Functions
void onValueChanged (Vector2 value)
Public Attributes
float maxSize = 1f
float minSize = 0.1f
Protected Member Functions
override void Awake ()
override void OnEnable ()
override void OnDisable ()
Private Attributes
ScrollRect scrollRect
Detailed Description
Definition at line 9 of file ScrollbarHandleSize.cs.
Member Function Documentation
Awake()
override void Mosframe.ScrollbarHandleSize.Awake () inline protected
Definition at line 17 of file ScrollbarHandleSize.cs.
    {
        base.Awake();
        scrollRect = GetComponent<ScrollRect>();
    }
References Mosframe.ScrollbarHandleSize.scrollRect.
OnDisable()
override void Mosframe.ScrollbarHandleSize.OnDisable () inline protected
Definition at line 28 of file ScrollbarHandleSize.cs.
    {
        scrollRect.onValueChanged.RemoveListener(onValueChanged);
    }
References Mosframe.ScrollbarHandleSize.onValueChanged(), and Mosframe.ScrollbarHandleSize.scrollRect.
OnEnable()
override void Mosframe.ScrollbarHandleSize.OnEnable () inline protected
Definition at line 23 of file ScrollbarHandleSize.cs.
    {
        scrollRect.onValueChanged.AddListener(onValueChanged);
    }
References Mosframe.ScrollbarHandleSize.onValueChanged(), and Mosframe.ScrollbarHandleSize.scrollRect.
onValueChanged()
void Mosframe.ScrollbarHandleSize.onValueChanged (Vector2 value) inline
Definition at line 33 of file ScrollbarHandleSize.cs.
    {
        Scrollbar horizontalScrollbar = scrollRect.horizontalScrollbar;
        if (horizontalScrollbar != null)
        {
            if (horizontalScrollbar.size > maxSize)
            {
                horizontalScrollbar.size = maxSize;
            }
            else if (horizontalScrollbar.size < minSize)
            {
                horizontalScrollbar.size = minSize;
            }
        }
        Scrollbar verticalScrollbar = scrollRect.verticalScrollbar;
        if (verticalScrollbar != null)
        {
            if (verticalScrollbar.size > maxSize)
            {
                verticalScrollbar.size = maxSize;
            }
            else if (verticalScrollbar.size < minSize)
            {
                verticalScrollbar.size = minSize;
            }
        }
    }
References Mosframe.ScrollbarHandleSize.maxSize, Mosframe.ScrollbarHandleSize.minSize, and Mosframe.ScrollbarHandleSize.scrollRect.
Referenced by Mosframe.ScrollbarHandleSize.OnDisable(), and Mosframe.ScrollbarHandleSize.OnEnable().
Member Data Documentation
maxSize
float Mosframe.ScrollbarHandleSize.maxSize = 1f
Definition at line 11 of file ScrollbarHandleSize.cs.
Referenced by Mosframe.ScrollbarHandleSize.onValueChanged().
minSize
float Mosframe.ScrollbarHandleSize.minSize = 0.1f
Definition at line 13 of file ScrollbarHandleSize.cs.
Referenced by Mosframe.ScrollbarHandleSize.onValueChanged().
scrollRect
ScrollRect Mosframe.ScrollbarHandleSize.scrollRect private
Definition at line 15 of file ScrollbarHandleSize.cs.
Referenced by Mosframe.ScrollbarHandleSize.Awake(), Mosframe.ScrollbarHandleSize.OnDisable(), Mosframe.ScrollbarHandleSize.OnEnable(), and Mosframe.ScrollbarHandleSize.onValueChanged().
The documentation for this class was generated from the following file:
Elin/Plugins.UI/Mosframe/ScrollbarHandleSize.cs