Elin Decompiled Documentation: CustomZoneContent Class Reference
CustomZoneContent Class Reference
Public Member Functions
override void OnGameLoad (GameIOContext context)
override string ToString ()
Public Member Functions inherited from CustomContent
virtual void OnGameLoad (GameIOContext context)
virtual void OnGameSave (GameIOContext context)
override string ToString ()
Static Public Member Functions
static CustomZoneContent CreateFromRow (SourceZone.Row r, ModPackage owner=null)
Static Public Member Functions inherited from CustomSourceContent
static string string string[] kv GetParams (string tag)
Static Public Member Functions inherited from EClass
static int rndSeed (int a, int seed)
static int rnd (long a)
static int rnd (int a)
static int curve (long _a, int start, int step, int rate=75)
static int sqrt (int a)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Public Attributes
string parent
bool autoSpawn
Properties
override string SourceType [get]
Properties inherited from CustomSourceContent
virtual string SourceType [get]
string SourceId [get, set]
Properties inherited from CustomContent
string ContentId [get, protected set]
EMod Owner [get, protected set]
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Additional Inherited Members
Static Public Attributes inherited from CustomSourceContent
static string action
static string string spec
Static Public Attributes inherited from EClass
static Core core
Detailed Description
Definition at line 5 of file CustomZoneContent.cs.
Member Function Documentation
CreateFromRow()
static CustomZoneContent CustomZoneContent.CreateFromRow (SourceZone::Row r, ModPackage owner = null) inline static
Definition at line 13 of file CustomZoneContent.cs.
    {
        if (owner == null)
        {
            owner = ModUtil.FindSourceRowPackage(r);
        }
        CustomZoneContent customZoneContent = new CustomZoneContent
        {
            ContentId = "Zone/" + r.id,
            SourceId = r.id,
            Owner = owner
        };
        string[] tag = r.tag;
        for (int i = 0; i < tag.Length; i++)
        {
            var (text, str, _) = CustomSourceContent.GetParams(tag[i]);
            if (text == "addMap")
            {
                customZoneContent.parent = str.IsEmpty(r.parent.IsEmpty("ntyris"));
                customZoneContent.autoSpawn = true;
            }
        }
        return customZoneContent;
    }
References CustomContent.ContentId, CustomSourceContent.GetParams(), CustomContent.Owner, and CustomSourceContent.SourceId.
Referenced by ModPackage.GenerateCustomContentProfiles().
OnGameLoad()
override void CustomZoneContent.OnGameLoad (GameIOContext context) inline virtual
Reimplemented from CustomContent.
Definition at line 38 of file CustomZoneContent.cs.
    {
        if (!autoSpawn || parent == null)
        {
            return;
        }
        Debug.Log($"#mod-content loading {this}");
        if (EClass.game.spatials.Find(base.SourceId) != null)
        {
            Debug.Log("#mod-content skipping existing custom zone " + base.SourceId);
            return;
        }
        Zone zone = ModUtil.FindZoneByFullName(parent);
        if (zone != null)
        {
            Spatial arg = SpatialGen.Create(base.SourceId, zone, register: true);
            Debug.Log($"#mod-content spawned custom zone {arg}");
            return;
        }
        ModUtil.LogModError("source zone row '" + base.SourceId + "' has invalid addMap parent '" + parent + "'", base.Owner);
    }
References $, autoSpawn, SpatialGen.Create(), Debug, SpatialManager.Find(), EClass.game, parent, and Game.spatials.
ToString()
override string CustomZoneContent.ToString () inline
Definition at line 60 of file CustomZoneContent.cs.
    {
        return base.ContentId + "/" + parent;
    }
References parent.
Member Data Documentation
autoSpawn
bool CustomZoneContent.autoSpawn
Definition at line 9 of file CustomZoneContent.cs.
Referenced by OnGameLoad().
parent
string CustomZoneContent.parent
Definition at line 7 of file CustomZoneContent.cs.
Referenced by OnGameLoad(), and ToString().
Property Documentation
SourceType
override string CustomZoneContent.SourceType get
Definition at line 11 of file CustomZoneContent.cs.
The documentation for this class was generated from the following file:
Elin/CustomZoneContent.cs