Elin Decompiled Documentation: ScreenFlash Class Reference
ScreenFlash Class Reference
Public Member Functions
void Play (float mtp=1f)
Static Public Member Functions
static void Reset ()
static void Play (string id, float mtp=1f)
Public Attributes
Color color
AnimationCurve ease
float duration
Static Public Attributes
static Color currentColor
static Color clearColor = new Color(0f, 0f, 0f, 0f)
Static Private Attributes
static Tween tween
Detailed Description
Definition at line 4 of file ScreenFlash.cs.
Member Function Documentation
Play() [1/2]
void ScreenFlash.Play (float mtp = 1f) inline
Definition at line 29 of file ScreenFlash.cs.
    {
        TweenUtil.KillTween(ref tween);
        tween = DOTween.To(() => currentColor, delegate(Color x)
        {
            currentColor = x;
        }, color * mtp, duration).SetEase(ease).OnComplete(delegate
        {
            Reset();
        });
    }
References Color, color, currentColor, duration, ease, Reset(), and tween.
Play() [2/2]
static void ScreenFlash.Play (string id, float mtp = 1f) inline static
Definition at line 24 of file ScreenFlash.cs.
    {
        ResourceCache.Load<ScreenFlash>("Media/Effect/ScreenEffect/Flash/" + id).Play(mtp);
    }
References Play().
Referenced by Play(), and GameUpdater.Update100ms().
Reset()
static void ScreenFlash.Reset () inline static
Definition at line 18 of file ScreenFlash.cs.
    {
        TweenUtil.KillTween(ref tween);
        currentColor = clearColor;
    }
References clearColor, currentColor, and tween.
Referenced by Scene.Init(), and Play().
Member Data Documentation
clearColor
Color ScreenFlash.clearColor = new Color(0f, 0f, 0f, 0f) static
Definition at line 10 of file ScreenFlash.cs.
Referenced by Reset().
color
Color ScreenFlash.color
Definition at line 12 of file ScreenFlash.cs.
Referenced by Play().
currentColor
Color ScreenFlash.currentColor static
Definition at line 8 of file ScreenFlash.cs.
Referenced by Play(), Reset(), and BaseGameScreen.UpdateShaders().
duration
float ScreenFlash.duration
Definition at line 16 of file ScreenFlash.cs.
Referenced by Play().
ease
AnimationCurve ScreenFlash.ease
Definition at line 14 of file ScreenFlash.cs.
Referenced by Play().
tween
Tween ScreenFlash.tween static private
Definition at line 6 of file ScreenFlash.cs.
Referenced by Play(), and Reset().
The documentation for this class was generated from the following file:
Elin/ScreenFlash.cs