Elin Decompiled Documentation: Popfab Class Reference
Popfab Class Reference
Public Member Functions
T Pop< T > (string id)
PopfabItem Pop (string id, string text=null)
PopfabItem Pop (PopfabItem item)
void Remove (PopfabItem item)
void Clear ()
void ForceOutro ()
void PushItems (Vector3 pos)
Public Attributes
float fixX
float fixY
float spacing = 10f
bool invert
int maxItems
Ease pushEase = Ease.Linear
float pushDuration = 0.5f
List< PopfabItem > list = new List<PopfabItem>()
Protected Member Functions
virtual void Awake ()
Private Member Functions
void OnDestroy ()
Private Attributes
Transform _trans
Detailed Description
Definition at line 5 of file Popfab.cs.
Member Function Documentation
Awake()
virtual void Popfab.Awake () inline protected virtual
Definition at line 26 of file Popfab.cs.
    {
        _trans = base.transform;
    }
References _trans.
Clear()
void Popfab.Clear () inline
Definition at line 75 of file Popfab.cs.
    {
        for (int num = list.Count - 1; num >= 0; num--)
        {
            list[num].Kill();
        }
    }
References list.
ForceOutro()
void Popfab.ForceOutro () inline
Definition at line 83 of file Popfab.cs.
    {
        foreach (PopfabItem item in list)
        {
            item.ForceOutro();
        }
    }
References item, and list.
OnDestroy()
void Popfab.OnDestroy () inline private
Definition at line 104 of file Popfab.cs.
    {
        for (int num = base.transform.childCount - 1; num >= 0; num--)
        {
            _trans.GetChild(num).GetComponent<PopfabItem>().Kill();
        }
    }
References _trans.
Pop() [1/2]
PopfabItem Popfab.Pop (PopfabItem item) inline
Definition at line 43 of file Popfab.cs.
    {
        item.Init(_trans);
        if (maxItems > 0)
        {
            item.isUseDuration = false;
        }
        if (pushEase != 0 && list.Count > 0)
        {
            PushItems(new Vector3(0f, item.rect.sizeDelta.y + spacing, 0f));
        }
        list.Add(item);
        item.reciever = this;
        if (maxItems != 0 && list.Count >= maxItems)
        {
            for (int i = 0; i < list.Count - maxItems; i++)
            {
                if (!list[i].isOutro)
                {
                    list[i].Outro();
                }
            }
        }
        item.Intro();
        return item;
    }
References _trans, item, list, maxItems, pushEase, PushItems(), and spacing.
Pop() [2/2]
PopfabItem Popfab.Pop (string id, string text = null) inline
Definition at line 36 of file Popfab.cs.
    {
        PopfabItem popfabItem = ResourceCache.Load<PopfabItem>("UI/Pop/" + id);
        popfabItem.Set(text);
        return Pop(popfabItem);
    }
References Pop(), and PopfabItem.Set().
Referenced by Pop().
Pop< T >()
T Popfab.Pop< T > (string id) inline
Type Constraints
T : PopfabItem
Definition at line 31 of file Popfab.cs.
                                       : PopfabItem
    {
        return Util.Instantiate(ResourceCache.Load<T>("UI/Pop/" + id), this);
    }
References Util.
PushItems()
void Popfab.PushItems (Vector3 pos) inline
Definition at line 91 of file Popfab.cs.
    {
        if (invert)
        {
            pos *= -1f;
        }
        foreach (PopfabItem item in list)
        {
            item.destY += pos.y;
            item.rect.DOLocalMoveY(item.destY, pushDuration).SetEase(pushEase);
        }
    }
References invert, item, list, pushDuration, and pushEase.
Referenced by Pop().
Remove()
void Popfab.Remove (PopfabItem item) inline
Definition at line 70 of file Popfab.cs.
    {
        list.Remove(item);
    }
References item, and list.
Referenced by PopfabItem.Kill().
Member Data Documentation
_trans
Transform Popfab._trans private
Definition at line 21 of file Popfab.cs.
Referenced by Awake(), OnDestroy(), and Pop().
fixX
float Popfab.fixX
Definition at line 7 of file Popfab.cs.
fixY
float Popfab.fixY
Definition at line 9 of file Popfab.cs.
invert
bool Popfab.invert
Definition at line 13 of file Popfab.cs.
Referenced by PushItems().
list
List<PopfabItem> Popfab.list = new List<PopfabItem>()
Definition at line 24 of file Popfab.cs.
Referenced by Clear(), ForceOutro(), Pop(), PushItems(), and Remove().
maxItems
int Popfab.maxItems
Definition at line 15 of file Popfab.cs.
Referenced by Pop().
pushDuration
float Popfab.pushDuration = 0.5f
Definition at line 19 of file Popfab.cs.
Referenced by PushItems().
pushEase
Ease Popfab.pushEase = Ease.Linear
Definition at line 17 of file Popfab.cs.
Referenced by Pop(), and PushItems().
spacing
float Popfab.spacing = 10f
Definition at line 11 of file Popfab.cs.
Referenced by Pop().
The documentation for this class was generated from the following file:
Elin/Plugins.UI/Popfab.cs