Elin Decompiled Documentation: TraitCrafter Class Reference
TraitCrafter Class Reference
Public Types
enum MixType {
None , Food , Resource , Dye ,
Butcher , Grind , Sculpture , Talisman ,
Scratch , Incubator , Fortune , RuneMold ,
FixedResource
}
enum AnimeType { Default , Microwave , Pot }
Public Types inherited from Trait
enum TileMode {
Default , Door , Illumination , DefaultNoAnime ,
SignalAnime
}
enum CopyShopType { None , Item , Spellbook }
Public Member Functions
virtual int WitchDoubleCraftChance (Thing t)
virtual string IDReqEle (RecipeSource r)
virtual bool IsCraftIngredient (Card c, int idx)
bool IsIngredient (int idx, SourceRecipe.Row r, Card c)
virtual bool IsIngredient (string cat, Card c)
int GetSortVal (SourceRecipe.Row r)
virtual int GetDuration (AI_UseCrafter ai, int costSp)
virtual int GetCostSp (AI_UseCrafter ai)
SourceRecipe.Row GetSource (AI_UseCrafter ai)
virtual bool ShouldConsumeIng (SourceRecipe.Row item, int index)
virtual Thing Craft (AI_UseCrafter ai)
override void TrySetAct (ActPlan p)
override bool CanUse (Chara c)
override bool OnUse (Chara c)
virtual void OnEndAI (AI_UseCrafter ai)
Public Member Functions inherited from Trait
string GetParam (int i, string def=null)
int GetParamInt (int i, int def)
virtual bool Contains (RecipeSource r)
virtual int GetValue ()
virtual bool CanStackTo (Thing to)
virtual string GetHoverText ()
virtual Action GetHealAction (Chara c)
virtual bool CanBlend (Thing t)
virtual void OnBlend (Thing t, Chara c)
virtual int GetActDuration (Chara c)
virtual SourceElement.Row GetRefElement ()
virtual Sprite GetRefSprite ()
virtual void OnRenderExtra (RenderParam p)
virtual Emo2 GetHeldEmo (Chara c)
virtual void SetOwner (Card _owner)
virtual bool IdleUse (Chara c, int dist)
virtual void OnSetOwner ()
virtual void OnImportMap ()
virtual void SetParams (params string[] s)
virtual void OnCrafted (Recipe recipe)
virtual void OnCreate (int lv)
virtual void OnEquip (Chara c, bool onSetOwner)
virtual void OnUnequip (Chara c)
virtual void OnChangePlaceState (PlaceState state)
virtual void OnAddedToZone ()
virtual void OnRemovedFromZone ()
virtual void OnSimulateHour (VirtualDate date)
virtual string GetName ()
virtual void SetName (ref string s)
virtual void OnRenderTile (Point point, HitResult result, int dir)
virtual int CompareTo (Card b)
virtual bool CanBuiltAt (Point p)
virtual void Update ()
Point GetPoint ()
Point GetRandomPoint (Func< Point, bool > func=null, Chara accessChara=null)
virtual List< Point > ListPoints (Point center=null, bool onlyPassable=true)
virtual Recipe GetRecipe ()
virtual Recipe GetBuildModeRecipe ()
virtual bool CanCook (Card c)
void CookProgress ()
virtual bool CanOffer (Card tg)
void OfferProcess (Chara cc)
void Offer (Chara cc)
virtual bool TryProgress (AIProgress p)
virtual LockOpenState TryOpenLock (Chara cc, bool msgFail=true)
virtual void WriteNote (UINote n, bool identified)
int GetSortVal (UIList.SortMode m)
virtual HotItem GetHotItem ()
virtual bool CanRead (Chara c)
virtual void OnRead (Chara c)
virtual bool CanEat (Chara c)
virtual void OnEat (Chara c)
virtual bool CanDrink (Chara c)
virtual void OnDrink (Chara c)
virtual void OnThrowGround (Chara c, Point p)
virtual bool CanUse (Chara c)
virtual bool CanUse (Chara c, Card tg)
virtual bool CanUse (Chara c, Point p)
virtual bool OnUse (Chara c)
virtual bool OnUse (Chara c, Card tg)
virtual bool OnUse (Chara c, Point p)
virtual void TrySetAct (ActPlan p)
virtual void TrySetHeldAct (ActPlan p)
virtual void OnHeld ()
virtual void OnTickHeld ()
virtual void OnSetCurrentItem ()
virtual void OnUnsetCurrentItem ()
virtual bool OnChildDecay (Card c, bool firstDecay)
virtual bool CanChildDecay (Card c)
virtual void OnSetCardGrid (ButtonGrid b)
virtual void OnStepped (Chara c)
virtual void OnSteppedOut (Chara c)
virtual void OnOpenDoor (Chara c)
void Install (bool byPlayer)
void Uninstall ()
virtual void OnInstall (bool byPlayer)
virtual void OnUninstall ()
virtual void TryToggle ()
virtual void Toggle (bool on, bool silent=false)
virtual void PlayToggleEffect (bool silent)
virtual void OnToggle ()
virtual void TrySetToggleAct (ActPlan p)
bool IsFuelEnough (int num=1, List< Thing > excludes=null, bool tryRefuel=true)
bool IsFuel (string s)
bool IsFuel (Thing t)
int GetFuelValue (Thing t)
int GetFuelValue (string id)
void Refuel (Thing t)
void TryRefuel (int dest, List< Thing > excludes)
virtual void OnEnterScreen ()
virtual void RefreshRenderer ()
virtual void SetMainText (UIText t, bool hotitem)
virtual bool CanCopy (Thing t)
string GetTextRestock (string lang, bool pet)
Emo2 GetRestockedIcon ()
void OnBarter ()
Thing CreateStock ()
Properties
override bool ShowFuelWindow [get]
virtual Emo Icon [get]
virtual int numIng [get]
virtual string IdSource [get]
virtual AnimeType animeType [get]
virtual AnimeID IdAnimeProgress [get]
virtual string idSoundProgress [get]
virtual string idSoundComplete [get]
virtual bool StopSoundProgress [get]
override bool IsNightOnlyLight [get]
virtual bool CanUseFromInventory [get]
override bool HoldAsDefaultInteraction [get]
virtual string idSoundBG [get]
virtual string CrafterTitle [get]
virtual bool CanTriggerFire [get]
virtual bool AutoTurnOff [get]
virtual bool IsConsumeIng [get]
virtual bool CloseOnComplete [get]
virtual int CostSP [get]
Properties inherited from Trait
string[] Params [get]
virtual byte WeightMod [get]
virtual int IdSkin [get]
virtual string Name [get]
virtual TileType tileType [get]
virtual RefCardName RefCardName [get]
virtual bool IsBlockPath [get]
virtual bool IsBlockSight [get]
virtual bool IsDoor [get]
virtual bool IsOpenSight [get]
virtual bool IsOpenPath [get]
virtual bool IsFloating [get]
virtual bool IsNoShop [get]
virtual bool IsGround [get]
virtual bool IsOnlyUsableByPc [get]
virtual bool InvertHeldSprite [get]
virtual bool IsChangeFloorHeight [get]
virtual bool ShouldRefreshTile [get]
virtual bool ShouldTryRefreshRoom [get]
virtual int InstallBottomPriority [get]
virtual bool CanHarvest [get]
virtual int radius [get]
virtual TraitRadiusType radiusType [get]
virtual bool CanUseRoomRadius [get]
virtual int GuidePriotiy [get]
virtual int Electricity [get]
virtual bool IgnoreLastStackHeight [get]
virtual int Decay [get]
virtual int DecaySpeed [get]
virtual int DecaySpeedChild [get]
virtual bool IsFridge [get]
virtual int DefaultStock [get]
virtual bool HoldAsDefaultInteraction [get]
virtual int CraftNum [get]
virtual bool ShowOrbit [get]
virtual bool HaveUpdate [get]
virtual bool IsSpot [get]
virtual bool IsFactory [get]
virtual bool CanAutofire [get]
virtual bool CanName [get]
virtual bool CanPutAway [get]
virtual bool CanChangeHeight [get]
virtual bool CanStack [get]
virtual bool CanCopyInBlueprint [get]
virtual bool CanBeAttacked [get]
virtual bool CanExtendBuild [get]
virtual string langNote [get]
virtual string IDInvStyle [get]
virtual string IDActorEx [get]
virtual bool MaskOnBuild [get]
virtual bool ShowContextOnPick [get]
virtual bool IsThrowMainAction [get]
virtual bool LevelAsQuality [get]
virtual bool UseDummyTile [get]
virtual bool RequireFullStackCheck [get]
virtual bool DisableAutoCombat [get]
virtual InvGridSize InvGridSize [get]
virtual bool IsContainer [get]
virtual bool CanUseContent [get]
virtual bool CanSearchContent [get]
virtual bool CanOpenContainer [get]
virtual bool IsSpecialContainer [get]
virtual ContainerType ContainerType [get]
virtual ThrowType ThrowType [get]
virtual EffectDead EffectDead [get]
virtual bool IsHomeItem [get]
virtual bool IsAltar [get]
virtual bool IsRestSpot [get]
virtual bool CanBeMasked [get]
virtual bool IsBlendBase [get]
virtual bool CanBeOnlyBuiltInHome [get]
virtual bool CanBuildInTown [get]
virtual bool CanBeHeld [get]
virtual bool CanBeStolen [get]
virtual bool CanOnlyCarry [get]
virtual bool CanBeDestroyed [get]
virtual bool CanBeSmashedToDeath [get]
virtual bool CanBeHallucinated [get]
virtual bool CanBeDropped [get]
virtual string ReqHarvest [get]
virtual bool CanBeDisassembled [get]
virtual bool CanBeShipped [get]
virtual bool HasCharges [get]
virtual bool ShowCharges [get]
virtual bool ShowChildrenNumber [get]
virtual bool ShowAsTool [get]
virtual bool CanBeHeldAsFurniture [get]
virtual bool HideInAdv [get]
virtual bool NoHeldDir [get]
virtual bool AlwaysHideOnLowWall [get]
bool ExistsOnMap [get]
virtual bool RenderExtra [get]
virtual float DropChance [get]
virtual string IdNoRestock [get]
virtual int IdleUseChance [get]
virtual string RecipeCat [get]
virtual bool IsTool [get]
virtual string LangUse [get]
virtual bool IsOn [get]
virtual bool IsAnimeOn [get]
bool IsToggle [get]
virtual bool AutoToggle [get]
bool IsLighting [get]
virtual bool IsLightOn [get]
virtual bool IsNightOnlyLight [get]
virtual TileMode tileMode [get]
virtual bool UseAltTiles [get]
virtual bool UseLowblock [get]
virtual bool UseExtra [get]
virtual bool UseLightColor [get]
virtual ? Color ColorExtra [get]
virtual int MaxFuel [get]
virtual int FuelCost [get]
virtual bool ShowFuelWindow [get]
bool IsRequireFuel [get]
string IdToggleExtra [get]
virtual ToggleType ToggleType [get]
virtual string IdSoundToggleOn [get]
virtual string IdSoundToggleOff [get]
virtual int ShopLv [get]
virtual CopyShopType CopyShop [get]
virtual int NumCopyItem [get]
virtual ShopType ShopType [get]
virtual CurrencyType CurrencyType [get]
virtual PriceType PriceType [get]
virtual bool AllowSell [get]
virtual int CostRerollShop [get]
virtual bool AllowCriminal [get]
virtual int RestockDay [get]
virtual SlaverType SlaverType [get]
virtual string LangBarter [get]
string TextNextRestock [get]
string TextNextRestockPet [get]
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Additional Inherited Members
Static Public Member Functions inherited from EClass
static int rndSeed (int a, int seed)
static int rnd (int a)
static int curve (int a, int start, int step, int rate=75)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Public Attributes inherited from Trait
Card owner
Static Public Attributes inherited from Trait
static TraitSelfFactory SelfFactory = new TraitSelfFactory()
Static Public Attributes inherited from EClass
static Core core
Static Protected Attributes inherited from Trait
static List< Point > listRadiusPoints = new List<Point>()
Detailed Description
Definition at line 4 of file TraitCrafter.cs.
Member Enumeration Documentation
AnimeType
enum TraitCrafter.AnimeType
Enumerator
Default
Microwave
Pot
Definition at line 23 of file TraitCrafter.cs.
    {
        Default,
        Microwave,
        Pot
    }
MixType
enum TraitCrafter.MixType
Enumerator
None
Food
Resource
Dye
Butcher
Grind
Sculpture
Talisman
Scratch
Incubator
Fortune
RuneMold
FixedResource
Definition at line 6 of file TraitCrafter.cs.
    {
        None,
        Food,
        Resource,
        Dye,
        Butcher,
        Grind,
        Sculpture,
        Talisman,
        Scratch,
        Incubator,
        Fortune,
        RuneMold,
        FixedResource
    }
Member Function Documentation
CanUse()
override bool TraitCrafter.CanUse (Chara c) inline virtual
Reimplemented from Trait.
Definition at line 525 of file TraitCrafter.cs.
    {
        return CanUseFromInventory;
    }
References CanUseFromInventory.
Craft()
virtual Thing TraitCrafter.Craft (AI_UseCrafter ai) inline virtual
Definition at line 266 of file TraitCrafter.cs.
    {
        Thing thing = ai.ings[0];
        Thing thing2 = ((numIng > 1) ? ai.ings[1] : null);
        SourceRecipe.Row source = GetSource(ai);
        if (source == null)
        {
            return null;
        }
        if (!EClass.player.knownCraft.Contains(source.id))
        {
            SE.Play("idea");
            Msg.Say("newKnownCraft");
            EClass.player.knownCraft.Add(source.id);
            if ((bool)LayerDragGrid.Instance)
            {
                LayerDragGrid.Instance.info.Refresh();
            }
        }
        string thing3 = source.thing;
        MixType mixType = source.type.ToEnum<MixType>();
        int num = source.num.Calc();
        Thing t = null;
        string[] array = thing3.Split('%');
        bool claimed;
        switch (mixType)
        {
        case MixType.Food:
            t = CraftUtil.MixIngredients(thing3, ai.ings, CraftUtil.MixType.General, 0, EClass.pc);
            break;
        case MixType.Resource:
        case MixType.FixedResource:
            t = CraftUtil.MixIngredients(ThingGen.Create(array[0], (array.Length > 1) ? EClass.sources.materials.alias[array[1]].id : thing.material.id), ai.ings, (mixType == MixType.FixedResource) ? CraftUtil.MixType.NoMix : CraftUtil.MixType.General, 999, EClass.pc).Thing;
            break;
        case MixType.Dye:
            t = ThingGen.Create(thing3, thing2.material.id);
            break;
        case MixType.Butcher:
            thing3 = SpawnListThing.Get("butcher", (SourceThing.Row a) => a.Category.id == "bodyparts").Select().id;
            t = ThingGen.Create(thing3);
            break;
        case MixType.Grind:
            if (source.tag.Contains("rust"))
            {
                EClass.pc.Say("polish", EClass.pc, ai.ings[1]);
                ai.ings[1].ModEncLv(1);
                ai.ings[0].ModNum(-1);
            }
            if (source.tag.Contains("mod_eject"))
            {
                ai.ings[1].EjectSockets();
                ai.ings[0].ModNum(-1);
            }
            break;
        case MixType.Sculpture:
        {
            t = ThingGen.Create(thing3);
            List<CardRow> list2 = EClass.player.codex.ListKills();
            list2.Add(EClass.sources.cards.map["putty"]);
            list2.Add(EClass.sources.cards.map["snail"]);
            CardRow cardRow = list2.RandomItemWeighted((CardRow a) => Mathf.Max(50 - a.LV, Mathf.Clamp(EClass.pc.Evalue(258) / 2, 1, a.LV * 2)));
            t.c_idRefCard = cardRow.id;
            t.ChangeMaterial(thing.material);
            t.SetEncLv(Mathf.Min(EClass.rnd(EClass.rnd(Mathf.Max(5 + EClass.pc.Evalue(258) - cardRow.LV, 1))), 12));
            t = CraftUtil.MixIngredients(t, ai.ings, CraftUtil.MixType.General, 999, EClass.pc).Thing;
            break;
        }
        case MixType.RuneMold:
        {
            Thing eq = ai.ings[0];
            Thing thing7 = eq.Duplicate(1);
            thing7.SetEncLv(0);
            List<Element> list = thing7.elements.ListRune();
            if (list.Count == 0)
            {
                Msg.SayNothingHappen();
                break;
            }
            foreach (Element item in list)
            {
                SocketData runeEnc = eq.GetRuneEnc(item.id);
                item.vLink = 0;
                if (runeEnc != null)
                {
                    if (item.vBase + item.vSource != runeEnc.value)
                    {
                        item.vLink = item.vBase + item.vSource;
                    }
                    item.vBase = runeEnc.value;
                    item.vSource = 0;
                }
            }
            if (eq.material.hardness > owner.material.hardness && !EClass.debug.enable)
            {
                Msg.Say("rune_tooHard", owner);
                break;
            }
            EClass.ui.AddLayer<LayerList>().SetList2(list, (Element a) => a.Name, delegate(Element a, ItemGeneral b)
            {
                owner.ModNum(-1);
                eq.Destroy();
                Thing thing8 = ThingGen.Create("rune");
                thing8.ChangeMaterial(owner.material);
                thing8.refVal = a.id;
                thing8.encLV = a.vBase + a.vSource;
                EClass.pc.Pick(thing8);
                EClass.pc.PlaySound("intonation");
                EClass.pc.PlayEffect("intonation");
            }, delegate(Element a, ItemGeneral b)
            {
                b.SetSubText(a.vBase + a.vSource + ((a.vLink != 0) ? (" (" + a.vLink + ")") : ""), 200, FontColor.Default, TextAnchor.MiddleRight);
                b.Build();
                if (a.HasTag("noRune"))
                {
                    b.button1.interactable = false;
                    b.button1.mainText.gameObject.AddComponent<CanvasGroup>().alpha = 0.5f;
                }
            }).SetSize(500f)
                .SetOnKill(delegate
                {
                })
                .SetTitles("wRuneMold");
            break;
        }
        case MixType.Talisman:
        {
            int num4 = EClass.pc.Evalue(1418);
            Thing thing5 = ai.ings[1];
            SourceElement.Row source2 = (thing5.trait as TraitSpellbook).source;
            int num5 = thing5.c_charges * source2.charge * (100 + num4 * 50) / 500 + 1;
            int num6 = 100;
            Thing thing6 = ThingGen.Create("talisman").SetNum(num5);
            thing6.refVal = source2.id;
            thing6.encLV = num6 * (100 + num4 * 10) / 100;
            thing.ammoData = thing6;
            thing.c_ammo = num5;
            EClass.pc.Say("talisman", thing, thing6);
            thing5.Destroy();
            break;
        }
        case MixType.Scratch:
            claimed = false;
            Prize(20, "medal", "save", cat: false);
            Prize(10, "plat", "save", cat: false);
            Prize(10, "furniture", "nice", cat: true);
            Prize(4, "plamo_box", "nice", cat: false);
            Prize(4, "food", "", cat: false);
            Prize(1, "casino_coin", "", cat: false);
            break;
        case MixType.Fortune:
        {
            EClass.player.seedFortune++;
            int num2 = 0;
            FortuneRollData orCreateFortuneRollData = EClass._zone.GetOrCreateFortuneRollData(refresh: false);
            int seed = orCreateFortuneRollData.seed + orCreateFortuneRollData.count + EClass.player.seedFortune;
            Rand.SetSeed(seed);
            for (int num3 = 3; num3 > 0; num3--)
            {
                if (EClass.rnd(FortuneRollData.chances[num3]) == 0)
                {
                    num2 = num3;
                    break;
                }
            }
            Rand.SetSeed();
            if (num2 != 0)
            {
                owner.PlaySound((num2 == 3) ? "fortuneroll_winBig" : "fortuneroll_win");
            }
            Thing thing4 = ThingGen.Create("fortune_ball");
            thing4.ChangeMaterial(FortuneRollData.mats[num2]);
            EClass._zone.AddCard(thing4, owner.pos);
            owner.PlaySound("fortuneroll_ball");
            orCreateFortuneRollData.GetPrize(num2, seed);
            if ((bool)LayerDragGrid.Instance)
            {
                LayerDragGrid.Instance.info.Refresh();
            }
            break;
        }
        case MixType.Incubator:
            TraitFoodEggFertilized.Incubate(ai.ings[0], owner.pos, owner);
            break;
        default:
            t = ThingGen.Create(thing3);
            if (thing3 == "gene")
            {
                if (ai.ings[0].c_DNA != null)
                {
                    t.MakeRefFrom(ai.ings[0].c_idRefCard);
                    t.c_DNA = ai.ings[0].c_DNA;
                    t.c_DNA.GenerateWithGene(DNA.Type.Inferior, t);
                }
            }
            else
            {
                t = CraftUtil.MixIngredients(t, ai.ings, CraftUtil.MixType.General, 999, EClass.pc).Thing;
            }
            break;
        }
        if (t != null)
        {
            if (t.HasElement(1229))
            {
                num = 1;
            }
            if (t.HasElement(704))
            {
                num = 1;
            }
            if (t.HasElement(703))
            {
                num = 1;
            }
            t.SetNum(num);
        }
        return t;
        void Prize(int chance, string s, string col, bool cat)
        {
            if (!claimed && EClass.rnd(chance) == 0)
            {
                t = (cat ? ThingGen.CreateFromCategory(s, EClass.pc.LV) : ThingGen.Create(s, -1, EClass.pc.LV));
                claimed = true;
                if (col != "")
                {
                    Msg.SetColor(col);
                }
            }
        }
    }
References EClass._zone, Zone.AddCard(), ItemGeneral.Build(), UIItem.button1, Card.c_DNA, SourceManager.cards, FortuneRollData.chances, Card.ChangeMaterial(), Player.codex, ThingGen.Create(), ThingGen.CreateFromCategory(), EClass.debug, Card.Destroy(), Card.Duplicate(), Card.Dye(), Card.elements, CoreDebug.enable, Card.Evalue(), DNA.GenerateWithGene(), SpawnListThing.Get(), Zone.GetOrCreateFortuneRollData(), FortuneRollData.GetPrize(), GetSource(), Card.HasElement(), Element.HasTag(), CardRow.id, Element.id, SourceElement.Row.id, SourceRecipe.Row.id, SpawnList.id, TraitFoodEggFertilized.Incubate(), LayerDragGrid.info, AI_UseCrafter.ings, LayerDragGrid.Instance, item, Player.knownCraft, CodexManager.ListKills(), ElementContainer.ListRune(), Card.LV, RenderRow.LV, UIButton.mainText, Card.MakeRefFrom(), SourceCard.map, Card.material, SourceManager.materials, FortuneRollData.mats, CraftUtil.MixIngredients(), Card.ModNum(), Element.Name, SourceRecipe.Row.num, numIng, Trait.owner, EClass.pc, Chara.Pick(), Card.PlayEffect(), EClass.player, Card.PlaySound(), Card.pos, UIDragGridInfo.Refresh(), EClass.rnd(), Msg.Say(), Card.Say(), Msg.SayNothingHappen(), seed, Player.seedFortune, Msg.SetColor(), Card.SetEncLv(), Card.SetNum(), Layer.SetOnKill(), Rand.SetSeed(), ItemGeneral.SetSubText(), EClass.sources, Card.Split(), SourceRecipe.Row.tag, Card.Thing, SourceRecipe.Row.thing, SourceRecipe.Row.type, EClass.ui, SocketData.value, Element.vBase, Element.vLink, and Element.vSource.
Referenced by AI_UseCrafter.Run().
GetCostSp()
virtual int TraitCrafter.GetCostSp (AI_UseCrafter ai) inline virtual
Reimplemented in TraitFactory.
Definition at line 215 of file TraitCrafter.cs.
    {
        return GetSource(ai).sp;
    }
References GetSource().
Referenced by AI_UseCrafter.Run().
GetDuration()
virtual int TraitCrafter.GetDuration (AI_UseCrafter ai, int costSp) inline virtual
Reimplemented in TraitFactory, TraitRollingFortune, and TraitScratchMachine.
Definition at line 210 of file TraitCrafter.cs.
    {
        return Mathf.Max(1, GetSource(ai).time * 100 / (80 + EClass.pc.Evalue(IDReqEle(ai.recipe?.source)) * 5));
    }
References Card.Evalue(), GetSource(), IDReqEle(), EClass.pc, AI_UseCrafter.recipe, and Recipe.source.
Referenced by AI_UseCrafter.Run().
GetSortVal()
int TraitCrafter.GetSortVal (SourceRecipe::Row r) inline
Definition at line 196 of file TraitCrafter.cs.
    {
        int num = r.id;
        string[] ing = r.ing1;
        for (int i = 0; i < ing.Length; i++)
        {
            if (ing[i].Contains('@'))
            {
                num -= 10000;
            }
        }
        return num;
    }
References Trait.Contains().
Referenced by GetSource().
GetSource()
SourceRecipe.Row TraitCrafter.GetSource (AI_UseCrafter ai) inline
Definition at line 220 of file TraitCrafter.cs.
    {
        List<SourceRecipe.Row> list = new List<SourceRecipe.Row>();
        foreach (SourceRecipe.Row row in EClass.sources.recipes.rows)
        {
            if (row.factory == IdSource)
            {
                list.Add(row);
            }
        }
        for (int i = 0; i < numIng; i++)
        {
            foreach (SourceRecipe.Row row2 in EClass.sources.recipes.rows)
            {
                if (i >= ai.ings.Count || !IsIngredient(i, row2, ai.ings[i]))
                {
                    list.Remove(row2);
                }
            }
        }
        if (list.Count == 0)
        {
            return null;
        }
        list.Sort((SourceRecipe.Row a, SourceRecipe.Row b) => GetSortVal(a) - GetSortVal(b));
        return list[0];
    }
References GetSortVal(), IdSource, AI_UseCrafter.ings, IsIngredient(), numIng, SourceManager.recipes, and EClass.sources.
Referenced by Craft(), GetCostSp(), GetDuration(), TraitRollingFortune.GetDuration(), TraitScratchMachine.GetDuration(), and AI_UseCrafter.Run().
IDReqEle()
virtual string TraitCrafter.IDReqEle (RecipeSource r) inline virtual
Reimplemented in TraitCauldron, TraitDyeMaker, and TraitSelfFactory.
Definition at line 73 of file TraitCrafter.cs.
    {
        return GetParam(1) ?? "handicraft";
    }
References Trait.GetParam().
Referenced by GetDuration(), and AI_UseCrafter.Run().
IsCraftIngredient()
virtual bool TraitCrafter.IsCraftIngredient (Card c, int idx) inline virtual
Definition at line 78 of file TraitCrafter.cs.
    {
        foreach (SourceRecipe.Row row in EClass.sources.recipes.rows)
        {
            if (idx == 1)
            {
                Card card = LayerDragGrid.Instance.buttons[0].Card;
                if (!IsIngredient(0, row, card) || (card == c && card.Num < 2))
                {
                    continue;
                }
            }
            if (IsIngredient(idx, row, c))
            {
                return true;
            }
        }
        return false;
    }
References LayerDragGrid.buttons, card, LayerDragGrid.Instance, IsIngredient(), SourceManager.recipes, and EClass.sources.
Referenced by InvOwnerCraft.ShouldShowGuide().
IsIngredient() [1/2]
bool TraitCrafter.IsIngredient (int idx, SourceRecipe::Row r, Card c) inline
Definition at line 98 of file TraitCrafter.cs.
    {
        if (r.factory != IdSource || c == null)
        {
            return false;
        }
        if (c.c_isImportant && ShouldConsumeIng(r, idx))
        {
            return false;
        }
        if (c.trait is TraitFoodFishSlice)
        {
            return false;
        }
        string[] array = ((idx == 0) ? r.ing1 : r.ing2);
        if (r.type.ToEnum<MixType>() == MixType.Grind && idx == 1)
        {
            if (r.tag.Contains("rust") && c.encLV >= 0)
            {
                return false;
            }
            if (r.tag.Contains("mod_eject"))
            {
                if (c.sockets == null)
                {
                    return false;
                }
                bool flag = false;
                foreach (int socket in c.sockets)
                {
                    if (socket != 0)
                    {
                        flag = true;
                    }
                }
                if (!flag)
                {
                    return false;
                }
            }
        }
        string[] array2 = array;
        foreach (string text in array2)
        {
            if (r.tag.Contains("noCarbone") && c.material.alias == "carbone")
            {
                return false;
            }
            if (text.StartsWith('#'))
            {
                string text2 = text.Replace("#", "");
                if (c.category.IsChildOf(text2) && IsIngredient(text2, c))
                {
                    return true;
                }
                continue;
            }
            string[] array3 = text.Split('@');
            if (array3.Length > 1)
            {
                if (c.id != array3[0] && c.sourceCard._origin != array3[0])
                {
                    return false;
                }
                if (c.refCard is SourceChara.Row row && row.race_row.tag.Contains(array3[1]))
                {
                    return true;
                }
                if (c.material.tag.Contains(array3[1]))
                {
                    return true;
                }
                continue;
            }
            if (text == "any")
            {
                if (this is TraitDyeMaker && !c.category.GetRoot().tag.Contains("dye") && !c.category.tag.Contains("dye"))
                {
                    return false;
                }
                if (!c.IsUnique && !c.IsImportant && !c.trait.CanOnlyCarry)
                {
                    return true;
                }
            }
            if (c.id == text || c.sourceCard._origin == text)
            {
                return true;
            }
        }
        return false;
    }
References Card.c_isImportant, Trait.Contains(), IdSource, IsIngredient(), SourceChara.Row.race_row, ShouldConsumeIng(), Card.sockets, and Card.trait.
Referenced by GetSource(), IsCraftIngredient(), and IsIngredient().
IsIngredient() [2/2]
virtual bool TraitCrafter.IsIngredient (string cat, Card c) inline virtual
Reimplemented in TraitRuneMold, and TraitToolTalisman.
Definition at line 191 of file TraitCrafter.cs.
    {
        return true;
    }
OnEndAI()
virtual void TraitCrafter.OnEndAI (AI_UseCrafter ai) inline virtual
Reimplemented in TraitRollingFortune.
Definition at line 554 of file TraitCrafter.cs.
    {
    }
Referenced by AI_UseCrafter.OnEnd().
OnUse()
override bool TraitCrafter.OnUse (Chara c) inline virtual
Reimplemented from Trait.
Definition at line 530 of file TraitCrafter.cs.
    {
        if (EClass._zone.IsRegion)
        {
            Msg.SayCannotUseHere();
            return false;
        }
        if (IsFactory)
        {
            Thing thing = owner.Thing;
            if (EClass.player.recipes.ListSources(thing).Count > 0)
            {
                EClass.ui.AddLayer<LayerCraft>().SetFactory(thing);
            }
            else
            {
                Msg.Say("noRecipes");
            }
            return false;
        }
        LayerDragGrid.CreateCraft(this);
        return false;
    }
References EClass._zone, LayerDragGrid.CreateCraft(), Trait.IsFactory, Spatial.IsRegion, RecipeManager.ListSources(), Trait.owner, EClass.player, Player.recipes, Msg.Say(), Msg.SayCannotUseHere(), Card.Thing, and EClass.ui.
ShouldConsumeIng()
virtual bool TraitCrafter.ShouldConsumeIng (SourceRecipe::Row item, int index) inline virtual
Reimplemented in TraitBarrelMaker, TraitRuneMold, and TraitToolTalisman.
Definition at line 248 of file TraitCrafter.cs.
    {
        if (IsFactory)
        {
            return true;
        }
        if (item == null)
        {
            return false;
        }
        int id = item.id;
        if ((uint)(id - 47) <= 1u)
        {
            return index == 0;
        }
        return true;
    }
References Trait.IsFactory, and item.
Referenced by IsIngredient(), and AI_UseCrafter.Run().
TrySetAct()
override void TraitCrafter.TrySetAct (ActPlan p) inline virtual
Reimplemented from Trait.
Definition at line 497 of file TraitCrafter.cs.
    {
        if (IsFactory)
        {
            Thing _t = owner.Thing;
            p.TrySetAct("craft", delegate
            {
                if (EClass.player.recipes.ListSources(_t).Count > 0)
                {
                    EClass.ui.AddLayer<LayerCraft>().SetFactory(_t);
                }
                else
                {
                    Msg.Say("noRecipes");
                }
                return false;
            }, _t, CursorSystem.Craft);
        }
        else if (!(this is TraitIncubator) || EClass._zone.IsPCFaction)
        {
            p.TrySetAct(CrafterTitle, delegate
            {
                LayerDragGrid.CreateCraft(this);
                return false;
            }, owner);
        }
    }
References EClass._zone, CursorSystem.Craft, CrafterTitle, LayerDragGrid.CreateCraft(), Trait.IsFactory, Zone.IsPCFaction, RecipeManager.ListSources(), Trait.owner, EClass.player, Player.recipes, Card.Thing, and ActPlan.TrySetAct().
WitchDoubleCraftChance()
virtual int TraitCrafter.WitchDoubleCraftChance (Thing t) inline virtual
Reimplemented in TraitAlchemyBench, and TraitToolAlchemy.
Definition at line 68 of file TraitCrafter.cs.
    {
        return 0;
    }
Property Documentation
animeType
virtual AnimeType TraitCrafter.animeType get
Definition at line 38 of file TraitCrafter.cs.
Referenced by AI_UseCrafter.Run().
AutoTurnOff
virtual bool TraitCrafter.AutoTurnOff get
Definition at line 60 of file TraitCrafter.cs.
Referenced by AI_UseCrafter.OnEnd().
CanTriggerFire
virtual bool TraitCrafter.CanTriggerFire get
Definition at line 58 of file TraitCrafter.cs.
CanUseFromInventory
virtual bool TraitCrafter.CanUseFromInventory get
Definition at line 50 of file TraitCrafter.cs.
Referenced by CanUse().
CloseOnComplete
virtual bool TraitCrafter.CloseOnComplete get
Definition at line 64 of file TraitCrafter.cs.
Referenced by AI_UseCrafter.Run().
CostSP
virtual int TraitCrafter.CostSP get
Definition at line 66 of file TraitCrafter.cs.
CrafterTitle
virtual string TraitCrafter.CrafterTitle get
Definition at line 56 of file TraitCrafter.cs.
Referenced by TrySetAct().
HoldAsDefaultInteraction
override bool TraitCrafter.HoldAsDefaultInteraction get
Definition at line 52 of file TraitCrafter.cs.
Icon
virtual Emo TraitCrafter.Icon get
Definition at line 32 of file TraitCrafter.cs.
Referenced by AI_UseCrafter.OnStart().
IdAnimeProgress
virtual AnimeID TraitCrafter.IdAnimeProgress get
Definition at line 40 of file TraitCrafter.cs.
Referenced by AI_UseCrafter.Run().
idSoundBG
virtual string TraitCrafter.idSoundBG get
Definition at line 54 of file TraitCrafter.cs.
Referenced by AI_UseCrafter.OnEnd(), and AI_UseCrafter.Run().
idSoundComplete
virtual string TraitCrafter.idSoundComplete get
Definition at line 44 of file TraitCrafter.cs.
Referenced by AI_UseCrafter.Run().
idSoundProgress
virtual string TraitCrafter.idSoundProgress get
Definition at line 42 of file TraitCrafter.cs.
Referenced by AI_UseCrafter.Run().
IdSource
virtual string TraitCrafter.IdSource get
Definition at line 36 of file TraitCrafter.cs.
Referenced by GetSource(), UIDragGridInfo.Init(), and IsIngredient().
IsConsumeIng
virtual bool TraitCrafter.IsConsumeIng get
Definition at line 62 of file TraitCrafter.cs.
Referenced by AI_UseCrafter.Run().
IsNightOnlyLight
override bool TraitCrafter.IsNightOnlyLight get
Definition at line 48 of file TraitCrafter.cs.
numIng
virtual int TraitCrafter.numIng get
Definition at line 34 of file TraitCrafter.cs.
Referenced by Craft(), GetSource(), LayerDragGrid.GetTargets(), and UIDragGridInfo.Init().
ShowFuelWindow
override bool TraitCrafter.ShowFuelWindow get
Definition at line 30 of file TraitCrafter.cs.
StopSoundProgress
virtual bool TraitCrafter.StopSoundProgress get
Definition at line 46 of file TraitCrafter.cs.
Referenced by AI_UseCrafter.Run().
The documentation for this class was generated from the following file:
Elin/TraitCrafter.cs