Elin Decompiled Documentation: ItemGachaResult Class Reference
ItemGachaResult Class Reference
Public Member Functions
void SetChara (Chara c, LayerGachaResult _layer)
int GetMedal ()
void Confirm (bool add)
Public Attributes
UIButton buttonGet
UIButton buttonDump
Portrait portrait
Chara chara
UIText textName
UIText textBio
UIText textJob
UIText textDetail
UIText textResult
UIText textHobby
UIText textWork
UIText textLifeStyle
LayerGachaResult layer
LayoutGroup layoutTag
Additional Inherited Members
Static Public Member Functions inherited from EMono
static int rnd (int a)
Static Public Attributes inherited from EMono
static Core core
Properties inherited from EMono
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SoundManager Sound [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static CoreDebug debug [get]
Detailed Description
Definition at line 6 of file ItemGachaResult.cs.
Member Function Documentation
Confirm()
void ItemGachaResult.Confirm (bool add) inline
Definition at line 58 of file ItemGachaResult.cs.
    {
        this.textResult.SetActive(true);
        this.textResult.SetText(add ? "Get!" : "Discarded", add ? FontColor.Good : FontColor.Bad);
        this.buttonDump.SetActive(false);
        this.buttonGet.SetActive(false);
        this.layer.items.Remove(this);
        if (add)
        {
            EMono.Home.AddReserve(this.chara);
            Msg.Say("gachaAdd", this.chara, null, null, null);
        }
        else
        {
            EMono.pc.ModCurrency(this.GetMedal(), "medal");
        }
        if (this.layer.items.Count == 0)
        {
            this.layer.Close();
        }
    }
References Faction.AddReserve(), buttonDump, buttonGet, chara, GetMedal(), EMono.Home, LayerGachaResult.items, layer, Card.ModCurrency(), EMono.pc, Msg.Say(), and textResult.
Referenced by LayerGachaResult.PlayGacha().
GetMedal()
int ItemGachaResult.GetMedal () inline
Definition at line 53 of file ItemGachaResult.cs.
    {
        return 1;
    }
Referenced by Confirm(), LayerGachaResult.Refresh(), and SetChara().
SetChara()
void ItemGachaResult.SetChara (Chara c, LayerGachaResult _layer) inline
Definition at line 8 of file ItemGachaResult.cs.
    {
        this.layer = _layer;
        this.chara = c;
        this.portrait.SetChara(c, null);
        if (c.IsPCC)
        {
            this.portrait.imageChara.transform.localScale = new Vector3(1.4f, 1.4f, 1f);
            this.portrait.imageChara.rectTransform.anchoredPosition = new Vector2(45f, -120f);
        }
        this.textName.text = c.NameBraced;
        this.textJob.text = c.job.GetName();
        this.textBio.text = c.bio.TextBio(c);
        using (List<Element>.Enumerator enumerator = c.elements.ListBestSkills().GetEnumerator())
        {
            while (enumerator.MoveNext())
            {
                Element e = enumerator.Current;
                HintIcon hintIcon = Util.Instantiate<HintIcon>("UI/Element/Item/Tag Skill", this.layoutTag);
                hintIcon.text.SetText(e.Name);
                hintIcon.text2.SetText(e.Value.ToString() ?? "");
                hintIcon.tooltip.onShowTooltip = delegate(UITooltip t)
                {
                    e.WriteNote(t.note, this.chara.elements, null);
                };
                hintIcon.RebuildLayout(false);
            }
        }
        this.textResult.SetActive(false);
        this.buttonGet.onClick.AddListener(delegate()
        {
            EMono.Sound.Play("good");
            this.Confirm(true);
        });
        this.buttonDump.tooltip.text = "gachaDump".lang(this.GetMedal().ToString() ?? "", null, null, null, null);
        this.buttonDump.onClick.AddListener(delegate()
        {
            EMono.Sound.Play("pay");
            this.Confirm(false);
        });
        this.textHobby.text = c.GetTextHobby(false);
        this.textWork.text = c.GetTextWork(false);
        this.textLifeStyle.text = "lifestyle".lang() + ": " + ("lifestyle_" + c.idTimeTable).lang();
    }
References Card.bio, buttonDump, buttonGet, Confirm, Card.elements, GetMedal(), Chara.GetTextHobby(), Chara.GetTextWork(), Chara.idTimeTable, Chara.IsPCC, Chara.job, layoutTag, ElementContainer.ListBestSkills(), Element.Name, Chara.NameBraced, portrait, Portrait.SetChara(), EMono.Sound, Biography.TextBio(), textResult, Element.Value, and Element.WriteNote().
Referenced by LayerGachaResult.PlayGacha().
Member Data Documentation
buttonDump
UIButton ItemGachaResult.buttonDump
Definition at line 82 of file ItemGachaResult.cs.
Referenced by Confirm(), and SetChara().
buttonGet
UIButton ItemGachaResult.buttonGet
Definition at line 80 of file ItemGachaResult.cs.
Referenced by Confirm(), and SetChara().
chara
Chara ItemGachaResult.chara
Definition at line 86 of file ItemGachaResult.cs.
Referenced by Confirm().
layer
LayerGachaResult ItemGachaResult.layer
Definition at line 104 of file ItemGachaResult.cs.
Referenced by Confirm().
layoutTag
LayoutGroup ItemGachaResult.layoutTag
Definition at line 106 of file ItemGachaResult.cs.
Referenced by SetChara().
portrait
Portrait ItemGachaResult.portrait
Definition at line 84 of file ItemGachaResult.cs.
Referenced by SetChara().
textBio
UIText ItemGachaResult.textBio
Definition at line 90 of file ItemGachaResult.cs.
textDetail
UIText ItemGachaResult.textDetail
Definition at line 94 of file ItemGachaResult.cs.
textHobby
UIText ItemGachaResult.textHobby
Definition at line 98 of file ItemGachaResult.cs.
textJob
UIText ItemGachaResult.textJob
Definition at line 92 of file ItemGachaResult.cs.
textLifeStyle
UIText ItemGachaResult.textLifeStyle
Definition at line 102 of file ItemGachaResult.cs.
textName
UIText ItemGachaResult.textName
Definition at line 88 of file ItemGachaResult.cs.
textResult
UIText ItemGachaResult.textResult
Definition at line 96 of file ItemGachaResult.cs.
Referenced by Confirm(), and SetChara().
textWork
UIText ItemGachaResult.textWork
Definition at line 100 of file ItemGachaResult.cs.
The documentation for this class was generated from the following file:
Elin/ItemGachaResult.cs