Elin Decompiled Documentation: ListOwner< T1, T2 > Class Template Reference
ListOwner< T1, T2 > Class Template Reference
Public Member Functions
virtual void List ()
virtual void OnCreate ()
virtual void OnSwitchContent ()
virtual void OnRefreshMenu ()
void MoveToOther (object c)
virtual void OnClick (T1 a, T2 b)
virtual void OnInstantiate (T1 a, T2 b)
virtual void OnList ()
virtual void List ()
virtual void OnCreate ()
virtual void OnSwitchContent ()
virtual void OnRefreshMenu ()
void MoveToOther (object c)
Public Attributes
Layer layer
Window window
UIMultiList multi
ListOwner other
UIList list
WindowMenu menu
string textTab
string textHeader
bool main
int index
Properties
ListOwner Main [get]
virtual string IdTitle [get]
virtual string IdHeaderRow [get]
virtual string TextTab [get]
virtual string TextHeader [get]
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Additional Inherited Members
Static Public Member Functions inherited from EClass
static int rnd (int a)
static int curve (int a, int start, int step, int rate=75)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Static Public Attributes inherited from EClass
static Core core
Detailed Description
Definition at line 1 of file ListOwner.cs.
Member Function Documentation
List() [1/2]
virtual void ListOwner< T1, T2 >.List () inline virtual
Reimplemented in BaseListPeople, and LayerEditPlaylist.ListBGM.
Definition at line 53 of file ListOwner.2.cs.
    {
    }
Referenced by ListOwner< T1, T2 >.MoveToOther(), and ListOwner< T1, T2 >.OnSwitchContent().
List() [2/2]
virtual void ListOwner< T1, T2 >.List () inline virtual
Reimplemented in BaseListPeople, and LayerEditPlaylist.ListBGM.
Definition at line 67 of file ListOwner.cs.
    {
    }
MoveToOther() [1/2]
void ListOwner< T1, T2 >.MoveToOther (object c) inline
Definition at line 81 of file ListOwner.2.cs.
    {
        this.list.RemoveDynamic(c);
        this.other.List();
        this.list.RebuildLayoutTo(this.layer);
        SE.Resource();
    }
References ListOwner< T1, T2 >.layer, ListOwner< T1, T2 >.List(), ListOwner< T1, T2 >.list, and ListOwner< T1, T2 >.other.
MoveToOther() [2/2]
void ListOwner< T1, T2 >.MoveToOther (object c) inline
Definition at line 95 of file ListOwner.cs.
    {
        list.RemoveDynamic(c);
        other.List();
        list.RebuildLayoutTo(layer);
        SE.Resource();
    }
References ListOwner< T1, T2 >.layer, ListOwner< T1, T2 >.List(), ListOwner< T1, T2 >.list, and ListOwner< T1, T2 >.other.
OnClick()
virtual void ListOwner< T1, T2 >.OnClick (T1 a, T2 b) inline virtual
Definition at line 3 of file ListOwner.cs.
    {
    }
OnCreate() [1/2]
virtual void ListOwner< T1, T2 >.OnCreate () inline virtual
Reimplemented in ListPeopleBuySlave.
Definition at line 57 of file ListOwner.2.cs.
    {
    }
Referenced by UIMultiList.AddOwner().
OnCreate() [2/2]
virtual void ListOwner< T1, T2 >.OnCreate () inline virtual
Reimplemented in ListPeopleBuySlave.
Definition at line 71 of file ListOwner.cs.
    {
    }
OnInstantiate()
virtual void ListOwner< T1, T2 >.OnInstantiate (T1 a, T2 b) inline virtual
Definition at line 7 of file ListOwner.cs.
    {
    }
OnList()
virtual void ListOwner< T1, T2 >.OnList () inline virtual
Reimplemented in BaseListPeople, ListPeopleBed, ListPeopleBuySlave, ListPeopleCallReserve, ListPeopleEmbark, ListPeopleExpedition, ListPeopleRevive, and ListPeopleSelect.
Definition at line 11 of file ListOwner.cs.
    {
    }
OnRefreshMenu() [1/2]
virtual void ListOwner< T1, T2 >.OnRefreshMenu () inline virtual
Reimplemented in BaseListPeople, ListPeopleBed, and ListPeopleEmbark.
Definition at line 75 of file ListOwner.2.cs.
    {
        this.window.menuLeft.Clear();
        this.window.menuRight.Clear();
    }
References ListOwner< T1, T2 >.window.
Referenced by ListOwner< T1, T2 >.OnSwitchContent().
OnRefreshMenu() [2/2]
virtual void ListOwner< T1, T2 >.OnRefreshMenu () inline virtual
Reimplemented in BaseListPeople, ListPeopleBed, and ListPeopleEmbark.
Definition at line 89 of file ListOwner.cs.
    {
        window.menuLeft.Clear();
        window.menuRight.Clear();
    }
References ListOwner< T1, T2 >.window.
OnSwitchContent() [1/2]
virtual void ListOwner< T1, T2 >.OnSwitchContent () inline virtual
Definition at line 61 of file ListOwner.2.cs.
    {
        this.List();
        this.OnRefreshMenu();
        if (Lang.GetList(this.IdTitle) != null)
        {
            this.window.SetTitles(this.IdTitle, this.IdHeaderRow);
        }
        if (!this.textHeader.IsEmpty())
        {
            this.window.SetCaption(this.TextHeader);
        }
    }
References ListOwner< T1, T2 >.IdHeaderRow, ListOwner< T1, T2 >.IdTitle, ListOwner< T1, T2 >.List(), ListOwner< T1, T2 >.OnRefreshMenu(), ListOwner< T1, T2 >.TextHeader, ListOwner< T1, T2 >.textHeader, and ListOwner< T1, T2 >.window.
Referenced by LayerEditPlaylist.Activate(), and UIMultiList.Refresh().
OnSwitchContent() [2/2]
virtual void ListOwner< T1, T2 >.OnSwitchContent () inline virtual
Definition at line 75 of file ListOwner.cs.
    {
        List();
        OnRefreshMenu();
        if (Lang.GetList(IdTitle) != null)
        {
            window.SetTitles(IdTitle, IdHeaderRow);
        }
        if (!textHeader.IsEmpty())
        {
            window.SetCaption(TextHeader);
        }
    }
References ListOwner< T1, T2 >.IdHeaderRow, ListOwner< T1, T2 >.IdTitle, ListOwner< T1, T2 >.List(), ListOwner< T1, T2 >.OnRefreshMenu(), ListOwner< T1, T2 >.TextHeader, ListOwner< T1, T2 >.textHeader, and ListOwner< T1, T2 >.window.
Member Data Documentation
index
int ListOwner< T1, T2 >.index
Definition at line 107 of file ListOwner.2.cs.
layer
Layer ListOwner< T1, T2 >.layer
Definition at line 89 of file ListOwner.2.cs.
Referenced by ListOwner< T1, T2 >.MoveToOther().
list
UIList ListOwner< T1, T2 >.list
Definition at line 97 of file ListOwner.2.cs.
Referenced by ListOwner< T1, T2 >.MoveToOther().
main
bool ListOwner< T1, T2 >.main
Definition at line 105 of file ListOwner.2.cs.
menu
WindowMenu ListOwner< T1, T2 >.menu
Definition at line 99 of file ListOwner.2.cs.
multi
UIMultiList ListOwner< T1, T2 >.multi
Definition at line 93 of file ListOwner.2.cs.
other
ListOwner ListOwner< T1, T2 >.other
Definition at line 95 of file ListOwner.2.cs.
Referenced by ListOwner< T1, T2 >.MoveToOther().
textHeader
string ListOwner< T1, T2 >.textHeader
Definition at line 103 of file ListOwner.2.cs.
Referenced by ListOwner< T1, T2 >.OnSwitchContent().
textTab
string ListOwner< T1, T2 >.textTab
Definition at line 101 of file ListOwner.2.cs.
window
Window ListOwner< T1, T2 >.window
Definition at line 91 of file ListOwner.2.cs.
Referenced by UIMultiList.AddOwner(), ListOwner< T1, T2 >.OnRefreshMenu(), and ListOwner< T1, T2 >.OnSwitchContent().
Property Documentation
IdHeaderRow
string ListOwner< T1, T2 >.IdHeaderRow get
Definition at line 25 of file ListOwner.2.cs.
    {
        get
        {
            return null;
        }
    }
Referenced by ListOwner< T1, T2 >.OnSwitchContent().
IdTitle
string ListOwner< T1, T2 >.IdTitle get
Definition at line 17 of file ListOwner.2.cs.
    {
        get
        {
            return base.GetType().Name;
        }
    }
Referenced by ListOwner< T1, T2 >.OnSwitchContent().
Main
ListOwner ListOwner< T1, T2 >.Main get
Definition at line 5 of file ListOwner.2.cs.
    {
        get
        {
            if (!this.main)
            {
                return this.other;
            }
            return this;
        }
    }
TextHeader
string ListOwner< T1, T2 >.TextHeader get
Definition at line 41 of file ListOwner.2.cs.
    {
        get
        {
            if (!this.textHeader.IsEmpty())
            {
                return this.textHeader.lang();
            }
            return "";
        }
    }
Referenced by ListOwner< T1, T2 >.OnSwitchContent().
TextTab
string ListOwner< T1, T2 >.TextTab get
Definition at line 33 of file ListOwner.2.cs.
    {
        get
        {
            return this.textTab.lang();
        }
    }
Referenced by UIMultiList.AddOwner().
The documentation for this class was generated from the following files:
Elin/ListOwner.2.cs
Elin/ListOwner.cs