Elin Decompiled Documentation: Player.Stats Class Reference
Player.Stats Class Reference
Public Member Functions
int GetShippingBonus (int _a)
Public Attributes
double timeElapsed
int kumi
int mins
int days
int months
int sieges
int turns
int kills
int taxBills
int taxBillsPaid
int digs
int shipNum
int shipMoney
int slept
int death
int allyDeath
int deepest
int gambleChest
int gambleChestOpen
int lastShippingExp
int lastShippingExpMax
Private Member Functions
void< GetShippingBonus > g__SetBonus (int threshold, int div, ref Player.Stats.<>c__DisplayClass21_0 A_3)
Detailed Description
Definition at line 1715 of file Player.cs.
Member Function Documentation
g__SetBonus()
void< GetShippingBonus > Player.Stats.g__SetBonus (int threshold, int div, ref Player::Stats::<>c__DisplayClass21_0 A_3) inline private
Definition at line 1735 of file Player.cs.
        {
            if (A_3.a >= threshold)
            {
                A_3.p += (A_3.a - threshold) / div;
                if (A_3.first)
                {
                    this.lastShippingExp = (A_3.a - threshold) % div;
                    this.lastShippingExpMax = div;
                    A_3.first = false;
                }
                A_3.a = threshold;
            }
        }
Referenced by Player.Stats.GetShippingBonus().
GetShippingBonus()
int Player.Stats.GetShippingBonus (int _a) inline
Definition at line 1717 of file Player.cs.
        {
            Player.Stats.<>c__DisplayClass21_0 CS$<>8__locals1;
            CS$<>8__locals1.<>4__this = this;
            CS$<>8__locals1.p = 0;
            CS$<>8__locals1.a = _a;
            CS$<>8__locals1.first = true;
            this.<GetShippingBonus>g__SetBonus|21_0(500000, 5000, ref CS$<>8__locals1);
            this.<GetShippingBonus>g__SetBonus|21_0(250000, 3000, ref CS$<>8__locals1);
            this.<GetShippingBonus>g__SetBonus|21_0(100000, 2000, ref CS$<>8__locals1);
            this.<GetShippingBonus>g__SetBonus|21_0(20000, 1000, ref CS$<>8__locals1);
            this.<GetShippingBonus>g__SetBonus|21_0(6000, 500, ref CS$<>8__locals1);
            this.<GetShippingBonus>g__SetBonus|21_0(2000, 200, ref CS$<>8__locals1);
            this.<GetShippingBonus>g__SetBonus|21_0(0, 100, ref CS$<>8__locals1);
            return CS$<>8__locals1.p;
        }
References Player.Stats.g__SetBonus(), and Player.Stats.GetShippingBonus().
Referenced by Player.Stats.GetShippingBonus().
Member Data Documentation
allyDeath
int Player.Stats.allyDeath
Definition at line 1780 of file Player.cs.
days
int Player.Stats.days
Definition at line 1756 of file Player.cs.
death
int Player.Stats.death
Definition at line 1778 of file Player.cs.
deepest
int Player.Stats.deepest
Definition at line 1782 of file Player.cs.
digs
int Player.Stats.digs
Definition at line 1770 of file Player.cs.
gambleChest
int Player.Stats.gambleChest
Definition at line 1784 of file Player.cs.
gambleChestOpen
int Player.Stats.gambleChestOpen
Definition at line 1786 of file Player.cs.
kills
int Player.Stats.kills
Definition at line 1764 of file Player.cs.
kumi
int Player.Stats.kumi
Definition at line 1752 of file Player.cs.
lastShippingExp
int Player.Stats.lastShippingExp
Definition at line 1789 of file Player.cs.
lastShippingExpMax
int Player.Stats.lastShippingExpMax
Definition at line 1792 of file Player.cs.
mins
int Player.Stats.mins
Definition at line 1754 of file Player.cs.
months
int Player.Stats.months
Definition at line 1758 of file Player.cs.
shipMoney
int Player.Stats.shipMoney
Definition at line 1774 of file Player.cs.
shipNum
int Player.Stats.shipNum
Definition at line 1772 of file Player.cs.
sieges
int Player.Stats.sieges
Definition at line 1760 of file Player.cs.
slept
int Player.Stats.slept
Definition at line 1776 of file Player.cs.
taxBills
int Player.Stats.taxBills
Definition at line 1766 of file Player.cs.
taxBillsPaid
int Player.Stats.taxBillsPaid
Definition at line 1768 of file Player.cs.
timeElapsed
double Player.Stats.timeElapsed
Definition at line 1750 of file Player.cs.
turns
int Player.Stats.turns
Definition at line 1762 of file Player.cs.
The documentation for this class was generated from the following file:
Elin/Player.cs