Elin Decompiled Documentation: LayerBaseCraft Class Reference
LayerBaseCraft Class Reference
Public Member Functions
virtual List< Thing > GetTargets ()
virtual int GetReqIngredient (int index)
virtual void RefreshCurrentGrid ()
virtual void ClearButtons ()
virtual void OnEndCraft ()
Public Member Functions inherited from ELayer
override void OnBeforeAddLayer ()
void InitInspector ()
sealed override void Init ()
override void OnAfterAddLayer ()
void TryShowHelp ()
void AddLayerToUI (string id)
void TryShowHint (string _langHint=null)
void TalkHomeMemeber (string id)
void TalkMaid (string id)
override void OnRightClick ()
Properties
virtual bool CanCancelAI [get]
virtual bool RepeatAI [get]
Properties inherited from ELayer
static Core core [get]
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static FactionBranch Branch [get]
static Faction Home [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static CoreConfig config [get]
static GameSetting setting [get]
static ColorProfile Colors [get]
static SourceManager sources [get]
static World world [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
bool IsFloat [get]
virtual string IdHelp [get]
Additional Inherited Members
Static Public Member Functions inherited from ELayer
static int rnd (int a)
Protected Member Functions inherited from ELayer
sealed override void _Close ()
sealed override void Kill ()
Detailed Description
Definition at line 3 of file LayerBaseCraft.cs.
Member Function Documentation
ClearButtons()
virtual void LayerBaseCraft.ClearButtons () inline virtual
Reimplemented in LayerCraft, and LayerDragGrid.
Definition at line 23 of file LayerBaseCraft.cs.
    {
    }
Referenced by AI_UseCrafter.Run().
GetReqIngredient()
virtual int LayerBaseCraft.GetReqIngredient (int index) inline virtual
Reimplemented in LayerCraft.
Definition at line 14 of file LayerBaseCraft.cs.
    {
        return 1;
    }
Referenced by AI_UseCrafter.Run().
GetTargets()
virtual List< Thing > LayerBaseCraft.GetTargets () inline virtual
Reimplemented in LayerCraft, and LayerDragGrid.
Definition at line 9 of file LayerBaseCraft.cs.
    {
        return null;
    }
Referenced by AI_UseCrafter.Run().
OnEndCraft()
virtual void LayerBaseCraft.OnEndCraft () inline virtual
Reimplemented in LayerCraft.
Definition at line 27 of file LayerBaseCraft.cs.
    {
    }
Referenced by AI_UseCrafter.OnEnd().
RefreshCurrentGrid()
virtual void LayerBaseCraft.RefreshCurrentGrid () inline virtual
Reimplemented in LayerCraft, and LayerDragGrid.
Definition at line 19 of file LayerBaseCraft.cs.
    {
    }
Referenced by AI_UseCrafter.Run().
Property Documentation
CanCancelAI
virtual bool LayerBaseCraft.CanCancelAI get
Definition at line 5 of file LayerBaseCraft.cs.
Referenced by AI_UseCrafter.CanManualCancel().
RepeatAI
virtual bool LayerBaseCraft.RepeatAI get
Definition at line 7 of file LayerBaseCraft.cs.
The documentation for this class was generated from the following file:
Elin/LayerBaseCraft.cs