Elin Decompiled Documentation: BlockInfo Class Reference
BlockInfo Class Reference
Public Member Functions
override void WriteNote (UINote n, Action< UINote > onWriteNote=null, IInspect.NoteMode mode=IInspect.NoteMode.Default, Recipe recipe=null)
Public Member Functions inherited from BaseInspectPos
void OnInspect ()
virtual void WriteNote (UINote n, Action< UINote > onWriteNote=null, IInspect.NoteMode mode=IInspect.NoteMode.Default, Recipe recipe=null)
void WriteNote (UINote n, Action< UINote > onWriteNote=null, NoteMode mode=NoteMode.Default, Recipe recipe=null)
void OnInspect ()
Static Public Member Functions
static BlockInfo GetTemp (Point _pos)
static BlockInfo GetTempList (Point _pos)
static bool _CanInspect (Point pos)
Static Public Attributes
static BlockInfo Temp = new BlockInfo()
static BlockInfo TempList = new BlockInfo()
Properties
SourceBlock.Row source [get]
override bool CanInspect [get]
override string InspectName [get]
Properties inherited from BaseInspectPos
Point InspectPoint [get]
Vector3 InspectPosition [get]
virtual bool CanInspect [get]
virtual string InspectName [get]
Properties inherited from IInspect
bool CanInspect [get]
string InspectName [get]
Point InspectPoint [get]
Vector3 InspectPosition [get]
Additional Inherited Members
Public Types inherited from IInspect
enum NoteMode { Default , Recipe , Product , Info }
Public Attributes inherited from BaseInspectPos
Point pos = new Point()
Detailed Description
Definition at line 3 of file BlockInfo.cs.
Member Function Documentation
_CanInspect()
static bool BlockInfo._CanInspect (Point pos) inline static
Definition at line 31 of file BlockInfo.cs.
    {
        return pos.HasNonWallBlock;
    }
References Point.HasNonWallBlock, and BaseInspectPos.pos.
Referenced by Point.ListInspectorTargets(), and PointTarget.Update().
GetTemp()
static BlockInfo BlockInfo.GetTemp (Point _pos) inline static
Definition at line 15 of file BlockInfo.cs.
    {
        Temp.pos.Set(_pos);
        return Temp;
    }
References BaseInspectPos.pos, Point.Set(), and Temp.
Referenced by PointTarget.Update().
GetTempList()
static BlockInfo BlockInfo.GetTempList (Point _pos) inline static
Definition at line 21 of file BlockInfo.cs.
    {
        if (!TempList.pos.Equals(_pos))
        {
            TempList = new BlockInfo();
        }
        TempList.pos.Set(_pos);
        return TempList;
    }
References Point.Equals(), BaseInspectPos.pos, Point.Set(), and TempList.
Referenced by Point.ListInspectorTargets().
WriteNote()
override void BlockInfo.WriteNote (UINote n, Action< UINote > onWriteNote = null, IInspect::NoteMode mode = IInspect::NoteMode::Default, Recipe recipe = null) inline virtual
Reimplemented from BaseInspectPos.
Definition at line 36 of file BlockInfo.cs.
    {
        n.Clear();
        UIItem uIItem = n.AddHeaderCard(pos.cell.GetBlockName());
        source.SetImage(uIItem.image2, null, source.GetColorInt(pos.matBlock));
        n.AddText("isMadeOf".lang(pos.cell.matBlock.GetText()));
        n.Build();
    }
References UINote.AddHeaderCard(), UINote.AddText(), UINote.Build(), Point.cell, UINote.Clear(), Cell.GetBlockName(), UIItem.image2, Cell.matBlock, Point.matBlock, BaseInspectPos.pos, and source.
Member Data Documentation
Temp
BlockInfo BlockInfo.Temp = new BlockInfo() static
Definition at line 5 of file BlockInfo.cs.
Referenced by GetTemp().
TempList
BlockInfo BlockInfo.TempList = new BlockInfo() static
Definition at line 7 of file BlockInfo.cs.
Referenced by GetTempList().
Property Documentation
CanInspect
override bool BlockInfo.CanInspect get
Implements IInspect.
Definition at line 11 of file BlockInfo.cs.
InspectName
override string BlockInfo.InspectName get
Implements IInspect.
Definition at line 13 of file BlockInfo.cs.
source
SourceBlock.Row BlockInfo.source get
Definition at line 9 of file BlockInfo.cs.
Referenced by WriteNote().
The documentation for this class was generated from the following file:
Elin/BlockInfo.cs