Elin Decompiled Documentation: CustomDramaExpansionHelper Class Reference
CustomDramaExpansionHelper Class Reference
Static Public Member Functions
static void AddTempTalk (this DramaManager dm, string text, string actor="tg", string? jump=null)
static void Goto (this DramaManager dm, string step)
static void InjectUniqueRumor (this DramaManager dm, Chara chara=null)
Detailed Description
Definition at line 4 of file CustomDramaExpansionHelper.cs.
Member Function Documentation
AddTempTalk()
static void CustomDramaExpansionHelper.AddTempTalk (this DramaManager dm, string text, string actor = "tg", string? jump = null) inline static
Definition at line 6 of file CustomDramaExpansionHelper.cs.
    {
        if (jump == null || dm.sequence.steps.ContainsKey(jump))
        {
            DramaEventTalk item = new DramaEventTalk
            {
                idActor = actor,
                idJump = jump,
                text = text,
                temp = true,
                sequence = dm.sequence
            };
            dm.sequence.tempEvents.Add(item);
        }
    }
References item, DramaManager.sequence, DramaSequence.steps, and DramaSequence.tempEvents.
Goto()
static void CustomDramaExpansionHelper.Goto (this DramaManager dm, string step) inline static
Definition at line 22 of file CustomDramaExpansionHelper.cs.
    {
        if (dm.sequence.steps.ContainsKey(step))
        {
            dm.sequence.Play(step);
        }
    }
References DramaSequence.Play(), DramaManager.sequence, and DramaSequence.steps.
InjectUniqueRumor()
static void CustomDramaExpansionHelper.InjectUniqueRumor (this DramaManager dm, Chara chara = null) inline static
Definition at line 30 of file CustomDramaExpansionHelper.cs.
    {
        if (chara == null)
        {
            chara = dm.tg.chara;
        }
        if (chara == null)
        {
            return;
        }
        DramaCustomSequence cs = new DramaCustomSequence();
        bool flag = chara.IsHumanSpeak || EClass.pc.HasElement(1640);
        if ((!chara.IsUnique && !cs.HasTopic("unique", chara.id)) || !flag)
        {
            return;
        }
        dm.CustomEvent(dm.sequence.Exit);
        DramaChoice choice = new DramaChoice("letsTalk".lang(), dm.sequence.steps.Last().Key.IsEmpty(dm.setup.step));
        dm.lastTalk.choices.Add(choice);
        dm._choices.Add(choice);
        string rumor = (chara.IsPCParty ? chara.GetTalkText("sup") : cs.GetRumor(chara));
        choice.SetOnClick(delegate
        {
            dm.sequence.firstTalk.funcText = () => rumor;
            List<Hobby> list = chara.ListHobbies();
            Hobby hobby = ((list.Count > 0) ? list[0] : null);
            if (EClass.rnd(20) == 0 || EClass.debug.showFav)
            {
                if (EClass.rnd(2) == 0 || hobby == null)
                {
                    GameLang.refDrama1 = chara.GetFavCat().GetName().ToLower();
                    GameLang.refDrama2 = chara.GetFavFood().GetName();
                    rumor = cs.GetText(chara, "general", "talk_fav");
                    chara.knowFav = true;
                }
                else
                {
                    GameLang.refDrama1 = hobby.Name.ToLower();
                    rumor = cs.GetText(chara, "general", "talk_hobby");
                }
            }
            else
            {
                rumor = cs.GetRumor(chara);
            }
            chara.affinity.OnTalkRumor();
            choice.forceHighlight = true;
        }).SetCondition(() => chara.interest > 0);
    }
References DramaManager._choices, Person.chara, DramaEventTalk.choices, DramaManager.CustomEvent(), EClass.debug, DramaSequence.Exit(), DramaCustomSequence.GetRumor(), DramaCustomSequence.GetText(), Card.HasElement(), DramaCustomSequence.HasTopic(), DramaManager.lastTalk, Hobby.Name, EClass.pc, EClass.rnd(), DramaManager.sequence, DramaChoice.SetOnClick(), DramaManager.setup, CoreDebug.showFav, DramaSetup.step, DramaSequence.steps, and DramaManager.tg.
The documentation for this class was generated from the following file:
Elin/CustomDramaExpansionHelper.cs