Elin Decompiled Documentation: CoreExtension Class Reference
CoreExtension Class Reference
Static Public Member Functions
static Color GetFixedColor (Color c, bool dark)
static string TagColorGoodBad (this string s, Func< bool > funcGood, bool dark=false)
static string TagColorGoodBad (this string s, Func< bool > funcGood, Func< bool > funcBad, bool dark=false)
static UICurrency AttachCurrency (this Window window)
static string TagColor (this string s, FontColor c, SkinColorProfile colors=null)
static string TagColor (this string text, Func< bool > funcGood, SkinColorProfile colors=null)
static string TagColor (this string text, Func< bool > funcGood, Func< bool > funcBad, SkinColorProfile colors=null)
static void Sort (this List< Thing > things, UIList.SortMode m, bool ascending=false)
Detailed Description
Definition at line 5 of file CoreExtension.cs.
Member Function Documentation
AttachCurrency()
static UICurrency CoreExtension.AttachCurrency (this Window window) inline static
Definition at line 37 of file CoreExtension.cs.
    {
        return Util.Instantiate<UICurrency>("UI/Util/UICurrency", window.transform);
    }
References Util.
GetFixedColor()
static Color CoreExtension.GetFixedColor (Color c, bool dark) inline static
Definition at line 7 of file CoreExtension.cs.
    {
        float num = 0.5f;
        SkinColorProfile @default = (dark ? SkinManager.Instance.skinDark.colors : SkinManager.CurrentSkin.colors)._default;
        float num2 = 1f + @default.contrast;
        num = ((!(c.r + c.g + c.b > 1.5f)) ? (0.5f - @default.strength) : (0.5f + @default.strength));
        c.r = Mathf.Clamp((c.r - 0.5f) * num2 + num, 0f, 1f);
        c.g = Mathf.Clamp((c.g - 0.5f) * num2 + num, 0f, 1f);
        c.b = Mathf.Clamp((c.b - 0.5f) * num2 + num, 0f, 1f);
        return c;
    }
References SkinRootStatic.colors, SkinColorProfile.contrast, and SkinManager.CurrentSkin.
Referenced by TagColorGoodBad().
Sort()
static void CoreExtension.Sort (this List< Thing > things, UIList::SortMode m, bool ascending = false) inline static
Definition at line 59 of file CoreExtension.cs.
    {
        foreach (Thing thing in things)
        {
            thing.SetSortVal(m);
        }
        things.Sort(delegate(Thing a, Thing b)
        {
            if (m == UIList.SortMode.ByName)
            {
                if (ascending)
                {
                    return string.Compare(a.GetName(NameStyle.FullNoArticle, 1), b.GetName(NameStyle.FullNoArticle, 1));
                }
                return string.Compare(b.GetName(NameStyle.FullNoArticle, 1), a.GetName(NameStyle.FullNoArticle, 1));
            }
            if (a.sortVal == b.sortVal)
            {
                return b.SecondaryCompare(m, a);
            }
            return (!ascending) ? (a.sortVal - b.sortVal) : (b.sortVal - a.sortVal);
        });
    }
References Thing.GetName(), Card.SetSortVal(), and Card.sortVal.
TagColor() [1/3]
static string CoreExtension.TagColor (this string s, FontColor c, SkinColorProfile colors = null) inline static
Definition at line 42 of file CoreExtension.cs.
    {
        return s.TagColor((colors ?? SkinManager.CurrentColors).GetTextColor(c));
    }
References SkinManager.CurrentColors.
TagColor() [2/3]
static string CoreExtension.TagColor (this string text, Func< bool > funcGood, Func< bool > funcBad, SkinColorProfile colors = null) inline static
Definition at line 53 of file CoreExtension.cs.
    {
        SkinColorProfile skinColorProfile = colors ?? SkinManager.CurrentColors;
        return text.TagColor(funcGood() ? skinColorProfile.textGood : ((funcBad != null && funcBad()) ? skinColorProfile.textBad : skinColorProfile.textDefault));
    }
References SkinManager.CurrentColors, SkinColorProfile.textBad, SkinColorProfile.textDefault, and SkinColorProfile.textGood.
TagColor() [3/3]
static string CoreExtension.TagColor (this string text, Func< bool > funcGood, SkinColorProfile colors = null) inline static
Definition at line 47 of file CoreExtension.cs.
    {
        SkinColorProfile skinColorProfile = colors ?? SkinManager.CurrentColors;
        return text.TagColor(funcGood() ? skinColorProfile.textGood : skinColorProfile.textBad);
    }
References SkinManager.CurrentColors, SkinColorProfile.textBad, and SkinColorProfile.textGood.
TagColorGoodBad() [1/2]
static string CoreExtension.TagColorGoodBad (this string s, Func< bool > funcGood, bool dark = false) inline static
Definition at line 19 of file CoreExtension.cs.
    {
        SkinColorProfile @default = (dark ? SkinManager.Instance.skinDark.colors : SkinManager.CurrentSkin.colors)._default;
        return "<color=" + GetFixedColor(funcGood() ? @default.textGood : @default.textBad, dark).ToHex() + ">" + s + "</color>";
    }
References SkinRootStatic.colors, SkinManager.CurrentSkin, and GetFixedColor().
TagColorGoodBad() [2/2]
static string CoreExtension.TagColorGoodBad (this string s, Func< bool > funcGood, Func< bool > funcBad, bool dark = false) inline static
Definition at line 25 of file CoreExtension.cs.
    {
        SkinColorProfile @default = (dark ? SkinManager.Instance.skinDark.colors : SkinManager.CurrentSkin.colors)._default;
        bool flag = funcGood();
        bool flag2 = funcBad();
        if (!flag && !flag2)
        {
            return s;
        }
        return "<color=" + GetFixedColor(flag ? @default.textGood : @default.textBad, dark).ToHex() + ">" + s + "</color>";
    }
References SkinRootStatic.colors, SkinManager.CurrentSkin, and GetFixedColor().
The documentation for this class was generated from the following file:
Elin/CoreExtension.cs