Elin Decompiled Documentation: InvOwner.ListInteraction Class Reference
InvOwner.ListInteraction Class Reference
Public Member Functions
Interaction Add (string s, int priority, Action action, string idPriority=null)
bool Contains (string s)
Public Attributes
Thing thing
Detailed Description
Definition at line 468 of file InvOwner.cs.
Member Function Documentation
Add()
Interaction InvOwner.ListInteraction.Add (string s, int priority, Action action, string idPriority = null) inline
Definition at line 472 of file InvOwner.cs.
        {
            Interaction interaction = new Interaction
            {
                name = s,
                priority = priority,
                idPriority = idPriority,
                action = delegate
                {
                    if (!idPriority.IsEmpty())
                    {
                        if (idPriority == "remove")
{
                            EClass.player.SetPriorityAction(null, thing);
                        }
                        else
{
                            EClass.player.SetPriorityAction(idPriority, thing);
                        }
                    }
                    action();
                }
            };
            Add(interaction);
            return interaction;
        }
References InvOwner.ListInteraction.Add(), EClass.player, Player.SetPriorityAction(), and InvOwner.ListInteraction.thing.
Referenced by InvOwner.ListInteraction.Add(), InvOwner.ListInteractions(), and InvOwnerEquip.ListInteractions().
Contains()
bool InvOwner.ListInteraction.Contains (string s) inline
Definition at line 499 of file InvOwner.cs.
        {
            using (Enumerator enumerator = GetEnumerator())
            {
                while (enumerator.MoveNext())
                {
                    if (enumerator.Current.name == s)
                    {
                        return true;
                    }
                }
            }
            return false;
        }
Referenced by InvOwner.ListInteractions().
Member Data Documentation
thing
Thing InvOwner.ListInteraction.thing
Definition at line 470 of file InvOwner.cs.
Referenced by InvOwner.ListInteraction.Add().
The documentation for this class was generated from the following file:
Elin/InvOwner.cs