Elin Decompiled Documentation: HotItemWidgetSet Class Reference
HotItemWidgetSet Class Reference
Public Member Functions
HotItemWidgetSet Register ()
override void Perform ()
void Load ()
override void OnShowContextMenu (UIContextMenu m)
Public Member Functions inherited from HotAction
override void OnClick (ButtonHotItem b, Hotbar h)
virtual void Perform ()
override void OnShowContextMenu (UIContextMenu m)
Public Member Functions inherited from HotItem
string TextHotkey ()
virtual void OnClick (ButtonHotItem b, Hotbar h)
virtual void OnRightClick (ButtonHotItem b)
virtual bool CanAutoFire (Chara tg)
virtual void OnSetCurrentItem ()
virtual void OnUnsetCurrentItem ()
virtual void OnUnselect ()
virtual void SetImage (Image icon)
virtual bool TrySetAct (ActPlan p)
virtual void OnMarkMapHighlights ()
virtual void OnRenderTile (Point point, HitResult result, int dir)
Public Member Functions inherited from UIButton.Item
virtual Sprite GetSprite ()
virtual Sprite GetSprite (bool highlight)
virtual bool ShouldHighlight ()
virtual void OnAddedToBar ()
virtual void OnShowContextMenu (UIContextMenu m)
virtual void OnHover (UIButton b)
virtual void OnClick (UIButton b)
virtual void OnSetItem (UIButton b)
virtual void SetSubText (UIText t)
Public Attributes
WidgetManager.SaveData data
Public Attributes inherited from HotAction
int _bgColor
string text
Public Attributes inherited from HotItem
ButtonHotItem button
Hotbar hotbar
bool disabled
Public Attributes inherited from UIButton.Item
bool always
Properties
override string Id [get]
override string TextTip [get]
override bool CanChangeIconColor [get]
Properties inherited from HotAction
Color bgColor [get, set]
override Color SpriteColor [get]
virtual string Id [get]
virtual bool CanChangeIconColor [get]
virtual bool CanName [get]
override string Name [get]
override string pathSprite [get]
Properties inherited from HotItem
override Sprite SpriteHighlight [get]
override bool IsSelectable [get]
override string TextTip [get]
virtual Thing RenderThing [get]
virtual Thing Thing [get]
virtual Thing Tool [get]
virtual bool IsTool [get]
virtual bool LookAtMouse [get]
virtual bool IsGameAction [get]
virtual bool UseUIObjMaterial [get]
Properties inherited from UIButton.Item
virtual string TextTip [get]
virtual string Name [get]
virtual Sprite SpriteHighlight [get]
virtual string pathSprite [get]
virtual bool IsSelectable [get]
virtual bool AdjustImageSize [get]
virtual bool UseIconForHighlight [get]
virtual bool KeepVisibleWhenHighlighted [get]
virtual Color SpriteColor [get]
virtual Vector3 SpriteScale [get]
virtual bool Hidden [get]
virtual Transition Transition [get]
Detailed Description
Definition at line 3 of file HotItemWidgetSet.cs.
Member Function Documentation
Load()
void HotItemWidgetSet.Load () inline
Definition at line 27 of file HotItemWidgetSet.cs.
    {
        if (EClass.player.useSubWidgetTheme)
        {
            EClass.player.subWidgets = data;
        }
        else
        {
            EClass.player.mainWidgets = data;
        }
        EClass.ui.widgets.Reset(toggleTheme: false);
        SE.Click();
    }
References data, EClass.player, EClass.ui, and Player.useSubWidgetTheme.
Referenced by Perform().
OnShowContextMenu()
override void HotItemWidgetSet.OnShowContextMenu (UIContextMenu m) inline virtual
Reimplemented from HotAction.
Definition at line 41 of file HotItemWidgetSet.cs.
    {
        base.OnShowContextMenu(m);
        m.AddButton("hotActionWidgetSet", delegate
        {
            Register();
        });
    }
References UIContextMenu.AddButton(), and Register().
Perform()
override void HotItemWidgetSet.Perform () inline virtual
Reimplemented from HotAction.
Definition at line 22 of file HotItemWidgetSet.cs.
    {
        Load();
    }
References Load().
Register()
HotItemWidgetSet HotItemWidgetSet.Register () inline
Definition at line 14 of file HotItemWidgetSet.cs.
    {
        EClass.ui.widgets.UpdateConfigs();
        data = IO.DeepCopy(EClass.player.widgets);
        SE.WriteJournal();
        return this;
    }
References data, EClass.player, EClass.ui, and Player.widgets.
Referenced by OnShowContextMenu().
Member Data Documentation
data
WidgetManager.SaveData HotItemWidgetSet.data
Definition at line 6 of file HotItemWidgetSet.cs.
Referenced by Load(), and Register().
Property Documentation
CanChangeIconColor
override bool HotItemWidgetSet.CanChangeIconColor get
Definition at line 12 of file HotItemWidgetSet.cs.
Id
override string HotItemWidgetSet.Id get
Definition at line 8 of file HotItemWidgetSet.cs.
TextTip
override string HotItemWidgetSet.TextTip get
Definition at line 10 of file HotItemWidgetSet.cs.
The documentation for this class was generated from the following file:
Elin/HotItemWidgetSet.cs