Elin Decompiled Documentation: ItemGeneral Class Reference
ItemGeneral Class Reference
Public Member Functions
void SetChara (Chara c, BaseListPeople list=null)
RenderRow GetRenderRow ()
void OnRefreshPref ()
void Clear ()
UIButton AddSubButton (Sprite sprite, Action action, string lang=null, Action< UITooltip > onTooltip=null, string id=null)
UIButton GetSubButton (string id)
void SetMainText (string lang, Sprite sprite=null, bool disableMask=true)
UIButton SetSubText (string lang, int x, FontColor c=FontColor.Default, TextAnchor align=TextAnchor.MiddleLeft)
UIButton SetSubText2 (string lang, FontColor c=FontColor.Default, TextAnchor align=TextAnchor.MiddleRight)
T AddPrefab< T > (string id)
void SetSound (SoundData data=null)
void DisableIcon ()
void DisableMask ()
void Build ()
Public Member Functions inherited from UIItem
void SetTopic (string lang1, string lang2)
void SetWidth (int w)
void Hyphenate ()
RenderRow GetRenderRow ()
void OnRefreshPref ()
Public Attributes
LayoutGroup layout
int paddingSubText = 50
Card card
Public Attributes inherited from UIItem
UIText text1
UIText text2
UIText text3
UIText text4
Image image1
Image image2
UIButton button1
UIButton button2
UIButton button3
UIItem item
Toggle toggle
UIDropdown dd
object refObj
Private Attributes
int count
bool built
Dictionary< string, UIButton > subButtons = new Dictionary<string, UIButton>()
Dictionary< string, Component > prefabs = new Dictionary<string, Component>()
Static Private Attributes
const int IconSize = 40
const int IconPadding = 10
const int ButtonPaddingWhenIcon = 3
Detailed Description
Definition at line 6 of file ItemGeneral.cs.
Member Function Documentation
AddPrefab< T >()
T ItemGeneral.AddPrefab< T > (string id) inline
Type Constraints
T : Component
Definition at line 179 of file ItemGeneral.cs.
                                             : Component
    {
        T val = prefabs.TryGetValue(id) as T;
        if (val != null)
        {
            return val;
        }
        val = Util.Instantiate<T>("UI/Element/Item/Extra/" + id, base.transform);
        prefabs[id] = val;
        return val;
    }
References prefabs, and Util.
AddSubButton()
UIButton ItemGeneral.AddSubButton (Sprite sprite, Action action, string lang = null, Action< UITooltip > onTooltip = null, string id = null) inline
Definition at line 97 of file ItemGeneral.cs.
    {
        UIButton uIButton;
        if (built)
        {
            uIButton = subButtons[id];
        }
        else
        {
            uIButton = Util.Instantiate<UIButton>("UI/Element/Button/SubButton", base.transform);
            uIButton.Rect().anchoredPosition = new Vector2(count * -40 - 20 - 10, 0f);
        }
        uIButton.icon.sprite = sprite;
        uIButton.onClick.RemoveAllListeners();
        uIButton.onClick.AddListener(delegate
        {
            action();
        });
        if (!lang.IsEmpty())
        {
            uIButton.tooltip.enable = true;
            uIButton.tooltip.lang = lang;
        }
        if (onTooltip != null)
        {
            uIButton.tooltip.id = "note";
            uIButton.tooltip.onShowTooltip = onTooltip;
            uIButton.tooltip.enable = true;
        }
        uIButton.highlightTarget = button1;
        if (!built)
        {
            count++;
            if (id != null)
            {
                subButtons[id] = uIButton;
            }
        }
        return uIButton;
    }
References built, UIItem.button1, count, subButtons, and Util.
Referenced by TraitMoongateEx._OnUse(), LayerEditPlaylist.ListBGM.List(), BaseListPeople.OnInstantiate(), ListPeopleCallReserve.OnInstantiate(), ListPeopleBed.OnInstantiate(), ListPeopleParty.OnInstantiate(), LayerHome.RefreshAreas(), UIHomeInfo.RefreshReport(), and LayerHome.RefreshSpots().
Build()
void ItemGeneral.Build () inline
Definition at line 210 of file ItemGeneral.cs.
    {
        RectTransform rectTransform = button1.Rect();
        if (count > 0)
        {
            rectTransform.sizeDelta = new Vector2(count * -40 - 10 - 3, 0f);
        }
        built = true;
    }
References built, UIItem.button1, and count.
Referenced by AM_Adv._OnUpdateInput(), TraitCrafter.Craft(), BaseListPeople.List(), LayerEditPlaylist.ListBGM.List(), LayerHome.RefreshAreas(), LayerFactions.RefreshFactions(), ContentFaction.RefreshFactions(), LayerMapList.RefreshList(), UIHomeInfo.RefreshReport(), LayerHome.RefreshSpots(), ContentFaction.RefreshZones(), LayerFactions.RefreshZones(), and LayerLocation.RefreshZones().
Clear()
void ItemGeneral.Clear () inline
Definition at line 81 of file ItemGeneral.cs.
    {
        if (count <= 0)
        {
            return;
        }
        foreach (UIButton componentsInDirectChild in base.transform.GetComponentsInDirectChildren<UIButton>())
        {
            if (componentsInDirectChild != button1)
            {
                UnityEngine.Object.DestroyImmediate(componentsInDirectChild.gameObject);
            }
        }
        count = 0;
    }
References UIItem.button1, and count.
DisableIcon()
void ItemGeneral.DisableIcon () inline
Definition at line 196 of file ItemGeneral.cs.
    {
        button1.icon.transform.parent.SetActive(enable: false);
        if (!button1.keyText)
        {
            button1.mainText.rectTransform.anchoredPosition = new Vector2(20f, 0f);
        }
    }
References UIItem.button1, UIButton.icon, and UIButton.keyText.
Referenced by SetMainText().
DisableMask()
void ItemGeneral.DisableMask () inline
Definition at line 205 of file ItemGeneral.cs.
    {
        image2.enabled = false;
    }
Referenced by SetMainText().
GetRenderRow()
RenderRow ItemGeneral.GetRenderRow () inline
Implements IPrefImage.
Definition at line 68 of file ItemGeneral.cs.
    {
        return card?.sourceRenderCard;
    }
References card, and Card.sourceRenderCard.
GetSubButton()
UIButton ItemGeneral.GetSubButton (string id) inline
Definition at line 138 of file ItemGeneral.cs.
    {
        return subButtons.TryGetValue(id);
    }
References subButtons.
OnRefreshPref()
void ItemGeneral.OnRefreshPref () inline
Implements IPrefImage.
Definition at line 73 of file ItemGeneral.cs.
    {
        if (card != null && card.isChara)
        {
            SetChara(card.Chara);
        }
    }
References card, Card.Chara, Card.isChara, and SetChara().
SetChara()
void ItemGeneral.SetChara (Chara c, BaseListPeople list = null) inline
Definition at line 28 of file ItemGeneral.cs.
    {
        card = c;
        c.SetImage(button1.icon);
        string text = c.Name;
        if (EClass.Branch?.uidMaid == c.uid)
        {
            text += ("(" + "maid".lang() + ")").TagSize(12);
        }
        FontColor c2 = FontColor.ButtonGeneral;
        if (list is ListPeopleParty)
        {
            if (c.isDead)
            {
                c2 = FontColor.Bad;
            }
            else if (!(list as ListPeopleParty).CanJoinParty(c))
            {
                c2 = FontColor.Warning;
            }
        }
        else if (c.isDead)
        {
            c2 = FontColor.Bad;
        }
        else if (c.IsPCParty)
        {
            c2 = FontColor.Good;
        }
        else if (c.hp < c.MaxHP / 2 && c.currentZone == EClass._zone)
        {
            c2 = FontColor.Warning;
        }
        if (list is ListPeopleBuySlave)
        {
            text = text + " " + c.bio.TextBioSlave(c);
        }
        button1.mainText.SetText(text, c2);
    }
References EClass._zone, Card.bio, EClass.Branch, UIItem.button1, card, Chara.currentZone, Card.hp, UIButton.icon, Chara.isDead, Chara.IsPCParty, UIButton.mainText, Chara.MaxHP, Card.Name, Card.SetImage(), UIText.SetText(), Biography.TextBioSlave(), Card.uid, and FactionBranch.uidMaid.
Referenced by BaseListPeople.List(), and OnRefreshPref().
SetMainText()
void ItemGeneral.SetMainText (string lang, Sprite sprite = null, bool disableMask = true) inline
Definition at line 143 of file ItemGeneral.cs.
    {
        button1.mainText.SetText(lang.lang());
        if ((bool)sprite)
        {
            button1.icon.sprite = sprite;
            button1.icon.SetNativeSize();
            if (disableMask)
            {
                DisableMask();
            }
        }
        else
        {
            DisableIcon();
        }
    }
References UIItem.button1, DisableIcon(), DisableMask(), UIButton.icon, UIButton.mainText, and UIText.SetText().
Referenced by LayerEditPlaylist.ListBGM.List(), LayerHome.RefreshAreas(), LayerFactions.RefreshFactions(), ContentFaction.RefreshFactions(), LayerMapList.RefreshList(), UIHomeInfo.RefreshReport(), LayerHome.RefreshSpots(), ContentFaction.RefreshZones(), LayerFactions.RefreshZones(), and LayerLocation.RefreshZones().
SetSound()
void ItemGeneral.SetSound (SoundData data = null) inline
Definition at line 191 of file ItemGeneral.cs.
    {
        button1.soundClick = data ?? SE.DataClick;
    }
Referenced by ContentKeyItem.OnSwitchContent(), ContentQuest.OnSwitchContent(), LayerFactions.RefreshFactions(), ContentFaction.RefreshFactions(), ContentFaction.RefreshZones(), LayerFactions.RefreshZones(), and LayerLocation.RefreshZones().
SetSubText()
UIButton ItemGeneral.SetSubText (string lang, int x, FontColor c = FontColor::Default, TextAnchor align = TextAnchor::MiddleLeft) inline
Definition at line 161 of file ItemGeneral.cs.
    {
        button1.subText.SetActive(enable: true);
        button1.subText.SetText(lang.lang(), c);
        button1.subText.alignment = align;
        button1.mainText.rectTransform.sizeDelta = new Vector2(x - paddingSubText, 20f);
        button1.subText.rectTransform.anchoredPosition = new Vector2(x, 0f);
        return button1;
    }
References UIItem.button1, paddingSubText, UIText.SetText(), and UIButton.subText.
Referenced by AM_Adv._OnUpdateInput(), TraitCrafter.Craft(), ListPeopleCallReserve.OnInstantiate(), ListPeopleEmbark.OnInstantiate(), ListPeopleParty.OnInstantiate(), ContentKeyItem.OnSwitchContent(), ContentQuest.OnSwitchContent(), LayerFactions.RefreshFactions(), ContentFaction.RefreshFactions(), BaseListPeople.SetSubText(), and ListPeopleExpedition.SetSubText().
SetSubText2()
UIButton ItemGeneral.SetSubText2 (string lang, FontColor c = FontColor::Default, TextAnchor align = TextAnchor::MiddleRight) inline
Definition at line 171 of file ItemGeneral.cs.
    {
        button1.subText2.SetActive(enable: true);
        button1.subText2.SetText(lang.lang(), c);
        button1.subText2.alignment = align;
        return button1;
    }
References UIItem.button1, UIText.SetText(), and UIButton.subText2.
Referenced by ListPeopleSelect.OnInstantiate().
Member Data Documentation
built
bool ItemGeneral.built private
Definition at line 22 of file ItemGeneral.cs.
Referenced by AddSubButton(), and Build().
ButtonPaddingWhenIcon
const int ItemGeneral.ButtonPaddingWhenIcon = 3 static private
Definition at line 12 of file ItemGeneral.cs.
card
Card ItemGeneral.card
Definition at line 18 of file ItemGeneral.cs.
Referenced by GetRenderRow(), OnRefreshPref(), and SetChara().
count
int ItemGeneral.count private
Definition at line 20 of file ItemGeneral.cs.
Referenced by AddSubButton(), Build(), and Clear().
IconPadding
const int ItemGeneral.IconPadding = 10 static private
Definition at line 10 of file ItemGeneral.cs.
IconSize
const int ItemGeneral.IconSize = 40 static private
Definition at line 8 of file ItemGeneral.cs.
layout
LayoutGroup ItemGeneral.layout
Definition at line 14 of file ItemGeneral.cs.
paddingSubText
int ItemGeneral.paddingSubText = 50
Definition at line 16 of file ItemGeneral.cs.
Referenced by SetSubText().
prefabs
Dictionary<string, Component> ItemGeneral.prefabs = new Dictionary<string, Component>() private
Definition at line 26 of file ItemGeneral.cs.
Referenced by AddPrefab< T >().
subButtons
Dictionary<string, UIButton> ItemGeneral.subButtons = new Dictionary<string, UIButton>() private
Definition at line 24 of file ItemGeneral.cs.
Referenced by AddSubButton(), and GetSubButton().
The documentation for this class was generated from the following file:
Elin/ItemGeneral.cs