Elin Decompiled Documentation: ItemQuestTracker Class Reference
ItemQuestTracker Class Reference
Public Member Functions
void Refresh ()
void OnClickClose ()
void Kill ()
Public Attributes
Color colorTitle
Quest quest
UIText text
UIText textTitle
UIButton buttonGoto
Private Attributes
FastString sb = new FastString(32)
FastString lastSb = new FastString(32)
Additional Inherited Members
Static Public Member Functions inherited from EMono
static int rnd (int a)
Static Public Attributes inherited from EMono
static Core core
Properties inherited from EMono
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SoundManager Sound [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static CoreDebug debug [get]
Detailed Description
Definition at line 4 of file ItemQuestTracker.cs.
Member Function Documentation
Kill()
void ItemQuestTracker.Kill () inline
Definition at line 87 of file ItemQuestTracker.cs.
    {
        if (!WidgetQuestTracker.Instance)
        {
            return;
        }
        WidgetQuestTracker.Instance.items.Remove(this);
        UnityEngine.Object.DestroyImmediate(base.gameObject);
    }
References WidgetQuestTracker.Instance, and WidgetQuestTracker.items.
Referenced by OnClickClose(), and Refresh().
OnClickClose()
void ItemQuestTracker.OnClickClose () inline
Definition at line 68 of file ItemQuestTracker.cs.
    {
        if (EMono.ui.GetLayer<LayerJournal>(false))
        {
            return;
        }
        this.quest.track = false;
        this.Kill();
        SE.Trash();
        if (this.quest is QuestTrackCraft)
        {
            EMono.game.quests.Remove(this.quest);
            if (LayerCraft.Instance)
            {
                LayerCraft.Instance.RefreshTrackButton();
            }
        }
    }
References EMono.game, LayerCraft.Instance, Kill(), quest, Game.quests, LayerCraft.RefreshTrackButton(), QuestManager.Remove(), and EMono.ui.
Refresh()
void ItemQuestTracker.Refresh () inline
Definition at line 6 of file ItemQuestTracker.cs.
    {
        if (!this.quest.track || !EMono.game.quests.list.Contains(this.quest))
        {
            this.Kill();
            return;
        }
        this.sb.Clear();
        if (this.quest.deadline > 0 && !this.quest.UseInstanceZone)
        {
            this.sb.Append("- " + "days1".lang() + this.quest.TextDeadline);
            this.sb.Append(Environment.NewLine);
        }
        string value = this.quest.GetTrackerText().TrimEnd(Environment.NewLine.ToCharArray());
        this.sb.Append(value);
        bool enable = false;
        if (this.quest is QuestDeliver)
        {
            QuestDeliver questDeliver = this.quest as QuestDeliver;
            if (!questDeliver.IsDeliver || EMono._zone == questDeliver.DestZone)
            {
                ItemQuestTracker.<>c__DisplayClass7_0 CS$<>8__locals1 = new ItemQuestTracker.<>c__DisplayClass7_0();
                ItemQuestTracker.<>c__DisplayClass7_0 CS$<>8__locals2 = CS$<>8__locals1;
                Map map = EMono._map;
                int uid;
                if (!questDeliver.IsDeliver)
                {
                    Chara chara = questDeliver.person.chara;
                    uid = ((chara != null) ? chara.uid : 0);
                }
                else
                {
                    uid = questDeliver.uidTarget;
                }
                CS$<>8__locals2.tg = map.FindChara(uid);
                if (CS$<>8__locals1.tg != null)
                {
                    enable = true;
                    this.buttonGoto.SetOnClick(delegate
                    {
                        if (!EMono.pc.HasNoGoal)
{
                            SE.BeepSmall();
                            return;
                        }
                        EMono.pc.SetAIImmediate(new AI_Goto(CS$<>8__locals1.tg, 1, false, false));
                    });
                }
            }
        }
        this.buttonGoto.SetActive(enable);
        if (this.sb.Equals(this.lastSb))
        {
            return;
        }
        this.SetActive(true);
        this.textTitle.SetText(this.quest.GetTitle().TagColor(this.colorTitle));
        this.text.SetText(this.sb.ToString());
        this.lastSb.Set(this.sb);
        this.RebuildLayout(false);
    }
References EMono._map, EMono._zone, buttonGoto, Person.chara, Quest.deadline, QuestDestZone.DestZone, Map.FindChara(), EMono.game, Quest.GetTitle(), Quest.GetTrackerText(), Chara.HasNoGoal, QuestDestZone.IsDeliver, Kill(), lastSb, QuestManager.list, EMono.pc, Quest.person, quest, Game.quests, sb, Chara.SetAIImmediate(), text, Quest.TextDeadline, textTitle, Quest.track, Card.uid, and QuestDestZone.uidTarget.
Referenced by WidgetQuestTracker.Refresh().
Member Data Documentation
buttonGoto
UIButton ItemQuestTracker.buttonGoto
Definition at line 109 of file ItemQuestTracker.cs.
Referenced by Refresh().
colorTitle
Color ItemQuestTracker.colorTitle
Definition at line 101 of file ItemQuestTracker.cs.
lastSb
FastString ItemQuestTracker.lastSb = new FastString(32) private
Definition at line 99 of file ItemQuestTracker.cs.
Referenced by Refresh().
quest
Quest ItemQuestTracker.quest
Definition at line 103 of file ItemQuestTracker.cs.
Referenced by OnClickClose(), Refresh(), and WidgetQuestTracker.Refresh().
sb
FastString ItemQuestTracker.sb = new FastString(32) private
Definition at line 97 of file ItemQuestTracker.cs.
Referenced by Refresh().
text
UIText ItemQuestTracker.text
Definition at line 105 of file ItemQuestTracker.cs.
Referenced by Refresh().
textTitle
UIText ItemQuestTracker.textTitle
Definition at line 107 of file ItemQuestTracker.cs.
Referenced by Refresh().
The documentation for this class was generated from the following file:
Elin/ItemQuestTracker.cs