Elin Decompiled Documentation: CoreConfig Class Reference
CoreConfig Class Reference
Classes
class BackerContentConfig
class CameraConfig
class CustomFont
class Fix
class FontSetting
class GameConfig
class GraphicSetting
class InputSetting
class NetSetting
class OtherSetting
class SoundSetting
class Test
class UISetting
Public Types
enum GameFunc {
None , ToggleZoom , ShowInv , ShowChara ,
ShowAbility , ToggleBuild , ShowJournal , EmuShift ,
EmuAlt , AllAction , ToggleNoRoof , OpenAllyInv ,
Talk , EmptyHand , Fire , SwitchHotbar ,
PropertySearch , ToggleLog
}
enum GameFuncBuild {
None , ExitBuildMode , Rotate , ToggleFreepos ,
SnapFreepos , ToggleRoof , ToggleSlope , ToggleWall ,
TogglePicker , ToggleBuildLight
}
enum ScreenSnapType {
None , Default , Floor , Ceil ,
Hack3 , Hack4 , Hack5 , Hack6 ,
Hack7 , Hack8 , Hack9 , Grid
}
Public Member Functions
void OnInit ()
bool HasBackerRewardCode ()
void OnReset ()
void SetLang (string id)
void TryUpdatePlayedHour ()
void Save ()
void OnChangeResolution ()
void ApplyFPS (bool force=false)
void Apply ()
void ApplyResolution (bool force=false)
void ApplyScale ()
void ApplyHUD ()
void ApplyZoom (float a)
PostEffectProfile GetPostEffectProfile (bool replaceWorld=false)
void ApplyGrading ()
void RefreshUIBrightness ()
void ApplyVolume ()
void SetBGMInterval ()
void SetVolume (string id, float v)
void OnSetLang ()
void ApplyFont ()
void ApplySkin ()
Static Public Member Functions
static bool Exist ()
static CoreConfig TryLoadConfig ()
static bool IsCompatible (Version v)
static void Init ()
static void Reset ()
static void ResetGeneral ()
static void ResetGraphics ()
static void ResetGame ()
static void ResetInput ()
static void ResetOther ()
static void ResetTest ()
Static Public Member Functions inherited from EClass
static int rndSeed (int a, int seed)
static int rnd (long a)
static int rnd (int a)
static int curve (int _a, int start, int step, int rate=75)
static int sqrt (int a)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Public Attributes
Version version
string lang = "JP"
string nameReport
string emailReport
string rewardCode
int maxPlayedHours
bool ignoreParallelsWarning
bool ignoreLinuxModWarning
bool cloud
new UISetting ui
SoundSetting sound
FontSetting font
GraphicSetting graphic
new GameConfig game
NetSetting net
BackerContentConfig backer
InputSetting input
CameraConfig camera
OtherSetting other
Fix fix
Test test
List< FontSource > customFonts
HashSet< string > helpFlags = new HashSet<string>()
int[] colors = new int[10]
bool ignoreApply
Properties
static string path [get]
static int ZoomStep [get]
CameraSupport camSupport [get]
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Private Attributes
int[] _framerates = new int[4] { 120, 60, 30, 15 }
Additional Inherited Members
Static Public Attributes inherited from EClass
static Core core
Detailed Description
Definition at line 11 of file CoreConfig.cs.
Member Enumeration Documentation
GameFunc
enum CoreConfig.GameFunc
Enumerator
None
ToggleZoom
ShowInv
ShowChara
ShowAbility
ToggleBuild
ShowJournal
EmuShift
EmuAlt
AllAction
ToggleNoRoof
OpenAllyInv
Talk
EmptyHand
Fire
SwitchHotbar
PropertySearch
ToggleLog
Definition at line 13 of file CoreConfig.cs.
    {
        None,
        ToggleZoom,
        ShowInv,
        ShowChara,
        ShowAbility,
        ToggleBuild,
        ShowJournal,
        EmuShift,
        EmuAlt,
        AllAction,
        ToggleNoRoof,
        OpenAllyInv,
        Talk,
        EmptyHand,
        Fire,
        SwitchHotbar,
        PropertySearch,
        ToggleLog
    }
GameFuncBuild
enum CoreConfig.GameFuncBuild
Enumerator
None
ExitBuildMode
Rotate
ToggleFreepos
SnapFreepos
ToggleRoof
ToggleSlope
ToggleWall
TogglePicker
ToggleBuildLight
Definition at line 35 of file CoreConfig.cs.
    {
        None,
        ExitBuildMode,
        Rotate,
        ToggleFreepos,
        SnapFreepos,
        ToggleRoof,
        ToggleSlope,
        ToggleWall,
        TogglePicker,
        ToggleBuildLight
    }
ScreenSnapType
enum CoreConfig.ScreenSnapType
Enumerator
None
Default
Floor
Ceil
Hack3
Hack4
Hack5
Hack6
Hack7
Hack8
Hack9
Grid
Definition at line 49 of file CoreConfig.cs.
    {
        None,
        Default,
        Floor,
        Ceil,
        Hack3,
        Hack4,
        Hack5,
        Hack6,
        Hack7,
        Hack8,
        Hack9,
        Grid
    }
Member Function Documentation
Apply()
void CoreConfig.Apply () inline
Definition at line 863 of file CoreConfig.cs.
    {
        if (!ignoreApply)
        {
            EInput.SetKeyMap(input.keys);
            ApplyFPS();
            Application.runInBackground = Application.isEditor || other.runBackground;
            ApplyVolume();
            ApplyGrading();
            ApplyHUD();
            ApplyResolution();
            Window.openLastTab = ui.openLastTab;
            Layer.closeOnRightClick = ui.rightClickClose;
            RenderObject.animeSetting = EClass.core.gameSetting.render.anime;
            RenderObject.renderSetting = (RenderData.renderSetting = EClass.core.gameSetting.render);
            TC._setting = EClass.core.gameSetting.render.tc;
            UIScrollView.sensitivity = ui.ScrollSensitivity;
            UIContextMenu.closeOnMouseLeave = ui.closePopupOnMouseLeave;
            EClass.core.canvas.pixelPerfect = graphic.pixelperfectUI;
            EClass.screen.RefreshScreenSize();
            CharaRenderer._animeFrame = EClass.setting.render.anime.animeStep[test.animeFrame];
            CharaRenderer._animeFramePCC = EClass.setting.render.anime.animeStep[test.animeFramePCC];
            CharaRenderer.smoothmove = camera.smoothMove;
            CharaRenderer._animeFramePC = (camera.smoothMove ? 6000 : camera.moveframe);
            Scene.skipAnime = true;
            QualitySettings.maxQueuedFrames = 0;
            PopManager.outlineAlpha = ui.outlineAlpha;
            Window.animateWindow = ui.animeWindow;
            EInput.rightScroll = game.rightScroll;
            EInput.buttonScroll = (game.rightScroll ? EInput.rightMouse : EInput.middleMouse);
            EInput.antiMissClick = 0.1f * (float)other.antiMissClick;
            camSupport.bloom.enabled = graphic.bloom;
            camSupport.beautify.bloom = test.bloom2;
            camSupport.cam.allowHDR = graphic.hdr;
            ApplyScale();
        }
    }
References GameSetting.RenderSetting.anime, CoreConfig.Test.animeFrame, CoreConfig.Test.animeFramePCC, GameSetting.RenderSetting.AnimeSetting.animeStep, CoreConfig.UISetting.animeWindow, CoreConfig.OtherSetting.antiMissClick, ApplyFPS(), ApplyGrading(), ApplyHUD(), ApplyResolution(), ApplyScale(), ApplyVolume(), CameraSupport.beautify, CameraSupport.bloom, CoreConfig.GraphicSetting.bloom, CoreConfig.Test.bloom2, CameraSupport.cam, camera, camSupport, CoreConfig.UISetting.closePopupOnMouseLeave, EClass.core, game, Core.gameSetting, graphic, CoreConfig.GraphicSetting.hdr, ignoreApply, input, CoreConfig.InputSetting.keys, EInput.middleMouse, CoreConfig.CameraConfig.moveframe, CoreConfig.UISetting.openLastTab, other, CoreConfig.UISetting.outlineAlpha, CoreConfig.GraphicSetting.pixelperfectUI, BaseGameScreen.RefreshScreenSize(), GameSetting.render, CoreConfig.UISetting.rightClickClose, CoreConfig.GameConfig.rightScroll, CoreConfig.OtherSetting.runBackground, EClass.screen, CoreConfig.UISetting.ScrollSensitivity, EInput.SetKeyMap(), EClass.setting, CoreConfig.CameraConfig.smoothMove, GameSetting.RenderSetting.tc, test, and ui.
Referenced by OnInit(), LayerConfig.OnKill(), OnReset(), LayerConfig.Refresh(), ResetGame(), ResetGeneral(), ResetGraphics(), ResetInput(), ResetOther(), and ResetTest().
ApplyFont()
void CoreConfig.ApplyFont () inline
Definition at line 1025 of file CoreConfig.cs.
    {
        EClass.core.ui.skins.SetFonts(font.fontUI, font.fontChatbox, font.fontBalloon, font.fontDialog, font.fontWidget, font.fontNews);
    }
References EClass.core, font, CoreConfig.FontSetting.fontBalloon, CoreConfig.FontSetting.fontChatbox, CoreConfig.FontSetting.fontDialog, CoreConfig.FontSetting.fontNews, CoreConfig.FontSetting.fontUI, CoreConfig.FontSetting.fontWidget, and Core.ui.
Referenced by LayerConfig.ApplyFont(), OnReset(), OnSetLang(), and ResetGeneral().
ApplyFPS()
void CoreConfig.ApplyFPS (bool force = false) inline
Definition at line 841 of file CoreConfig.cs.
    {
        if (EClass.core.IsGameStarted || force)
        {
            if (graphic.vsync)
            {
                QualitySettings.vSyncCount = 1;
                Application.targetFrameRate = 60;
            }
            else
            {
                QualitySettings.vSyncCount = 0;
                Application.targetFrameRate = _framerates[graphic.fps];
            }
        }
        else
        {
            QualitySettings.vSyncCount = 0;
            Application.targetFrameRate = 60;
        }
    }
References _framerates, EClass.core, CoreConfig.GraphicSetting.fps, graphic, Core.IsGameStarted, and CoreConfig.GraphicSetting.vsync.
Referenced by Apply(), and Game.OnGameInstantiated().
ApplyGrading()
void CoreConfig.ApplyGrading () inline
Definition at line 956 of file CoreConfig.cs.
    {
        PostEffectProfile postEffectProfile = GetPostEffectProfile();
        ScreenGrading grading = camSupport.grading;
        grading.userSaturation = graphic.saturation + postEffectProfile.Saturation;
        grading.userBrightness = graphic.brightness + postEffectProfile.Brightness;
        grading.userContrast = graphic.contrast + postEffectProfile.Contrast;
        camSupport.beautify.saturate = graphic.vibrance + grading.profile.Vibrance;
        camSupport.kuwahara.enabled = graphic.kuwahara;
        camSupport.blur.enabled = graphic.blur > 0;
        camSupport.blur.Amount = 0.01f * (float)graphic.blur;
        if (EClass.core.IsGameStarted)
        {
            EClass.screen.RefreshGrading();
        }
        camSupport.OnChangeResolution();
        RefreshUIBrightness();
        postEffectProfile.Apply(EClass.scene.cam);
    }
References PostEffectProfile.Apply(), CoreConfig.GraphicSetting.blur, PostEffectProfile.Brightness, Scene.cam, camSupport, PostEffectProfile.Contrast, EClass.core, GetPostEffectProfile(), CameraSupport.grading, graphic, if(), Core.IsGameStarted, CoreConfig.GraphicSetting.kuwahara, CameraSupport.OnChangeResolution(), BaseGameScreen.RefreshGrading(), RefreshUIBrightness(), PostEffectProfile.Saturation, EClass.scene, and EClass.screen.
Referenced by Apply(), Scene.Init(), AM_Cinema.OnDeactivate(), and LayerConfig.Refresh().
ApplyHUD()
void CoreConfig.ApplyHUD () inline
Definition at line 935 of file CoreConfig.cs.
    {
    }
Referenced by Apply().
ApplyResolution()
void CoreConfig.ApplyResolution (bool force = false) inline
Definition at line 901 of file CoreConfig.cs.
    {
        if (graphic.fixedResolution)
        {
            force = true;
        }
        if (force)
        {
            Screen.SetResolution(graphic.w, graphic.h, graphic.fullScreen);
        }
        Screen.fullScreen = graphic.fullScreen;
    }
References CoreConfig.GraphicSetting.fixedResolution, CoreConfig.GraphicSetting.fullScreen, graphic, CoreConfig.GraphicSetting.h, and CoreConfig.GraphicSetting.w.
Referenced by Apply().
ApplyScale()
void CoreConfig.ApplyScale () inline
Definition at line 914 of file CoreConfig.cs.
    {
        float num = (float)ui.scale * 0.05f;
        if (ui.autoscale)
        {
            float a = 0.55f;
            float b = num + 0.05f;
            num = 0.01f * (float)Mathf.RoundToInt(Mathf.Lerp(a, b, (float)Screen.height / 1080f) * 100f);
        }
        if (ui.secureMinWidth && Screen.width < EClass.core.ui.minWidth)
        {
            float num2 = (float)Screen.width / (float)EClass.core.ui.minWidth;
            if (num2 < num)
            {
                num = num2;
            }
        }
        Debug.Log("#UI ApplyScale:" + num);
        EClass.core.canvas.GetComponent<CanvasScaler>().scaleFactor = num;
    }
References CoreConfig.UISetting.autoscale, BaseCore.canvas, EClass.core, Debug, if(), CoreConfig.UISetting.scale, CoreConfig.UISetting.secureMinWidth, Core.ui, and ui.
Referenced by Apply(), OnChangeResolution(), and LayerConfig.Refresh().
ApplySkin()
void CoreConfig.ApplySkin () inline
Definition at line 1030 of file CoreConfig.cs.
    {
        Core.Instance.ui.skins.SetMainSkin(test.idSkin);
        EClass.core.ApplySkins();
    }
References Core.ApplySkins(), EClass.core, CoreConfig.Test.idSkin, Core.Instance, test, and Core.ui.
Referenced by OnReset().
ApplyVolume()
void CoreConfig.ApplyVolume () inline
Definition at line 996 of file CoreConfig.cs.
    {
        SetVolume("VolumeMaster", sound.volumeMaster);
        SetVolume("VolumeBGM", EClass.Sound.muteBGM ? 0f : sound.volumeBGM);
        SetVolume("VolumeSpatialBGM", sound.volumeBGM);
        SetVolume("VolumeSFX", sound.volumeSFX);
        SetVolume("VolumeAmbience", sound.volumeAMB);
        SetBGMInterval();
    }
References SetBGMInterval(), SetVolume(), sound, EClass.Sound, CoreConfig.SoundSetting.volumeAMB, CoreConfig.SoundSetting.volumeBGM, CoreConfig.SoundSetting.volumeMaster, and CoreConfig.SoundSetting.volumeSFX.
Referenced by Apply(), LayerConfig.Refresh(), and Scene.ToggleMuteBGM().
ApplyZoom()
void CoreConfig.ApplyZoom (float a) inline
Definition at line 939 of file CoreConfig.cs.
    {
        camSupport.Zoom = a;
        EClass.screen.RefreshScreenSize();
        camSupport.OnChangeResolution();
    }
References camSupport, CameraSupport.OnChangeResolution(), BaseGameScreen.RefreshScreenSize(), and EClass.screen.
Referenced by BaseGameScreen.Draw(), and BaseGameScreen.SetZoom().
Exist()
static bool CoreConfig.Exist () inline static
Definition at line 653 of file CoreConfig.cs.
    {
        if (!File.Exists(path) || (EClass.debug.useNewConfig && Application.isEditor))
        {
            return false;
        }
        return true;
    }
References EClass.debug, path, and CoreDebug.useNewConfig.
GetPostEffectProfile()
PostEffectProfile CoreConfig.GetPostEffectProfile (bool replaceWorld = false) inline
Definition at line 946 of file CoreConfig.cs.
    {
        string text = graphic.idPostProfile.IsEmpty("None");
        if (replaceWorld && EClass.core.IsGameStarted && EClass.core.game.activeZone.IsRegion && text != "None")
        {
            text = "NFAA";
        }
        return ResourceCache.Load<PostEffectProfile>("Scene/Profile/PostEffect/" + text);
    }
References Game.activeZone, EClass.core, Core.game, graphic, CoreConfig.GraphicSetting.idPostProfile, Core.IsGameStarted, and Spatial.IsRegion.
Referenced by ApplyGrading(), Init(), OnReset(), and ResetGraphics().
HasBackerRewardCode()
bool CoreConfig.HasBackerRewardCode () inline
Definition at line 737 of file CoreConfig.cs.
    {
        return ElinEncoder.IsValid(rewardCode);
    }
References ElinEncoder.IsValid(), and rewardCode.
Referenced by Steam.HasDLC().
Init()
static void CoreConfig.Init () inline static
Definition at line 708 of file CoreConfig.cs.
    {
        if (EClass.core.config == null)
        {
            Debug.Log("Creating new config.");
            CoreConfig coreConfig = (EClass.core.config = IO.DeepCopy(EClass.setting.config));
            coreConfig.SetLang(EClass.core.langCode);
            if (!Application.isEditor || !EClass.debug.useNewConfig)
            {
                coreConfig.Save();
            }
            coreConfig.GetPostEffectProfile().OnChangeProfile();
            if (EClass.debug.enable)
            {
                coreConfig.other.showTestOptions = true;
                coreConfig.test.showNumbers = true;
                coreConfig.game.waiter = 0;
                coreConfig.game.advancedMenu = true;
            }
        }
        EClass.core.config.OnInit();
    }
References Core.config, GameSetting.config, EClass.core, EClass.debug, Debug, CoreDebug.enable, GetPostEffectProfile(), BaseCore.langCode, PostEffectProfile.OnChangeProfile(), OnInit(), Save(), SetLang(), EClass.setting, and CoreDebug.useNewConfig.
Referenced by Core.Init().
IsCompatible()
static bool CoreConfig.IsCompatible (Version v) inline static
Definition at line 703 of file CoreConfig.cs.
    {
        return v.minor >= 22;
    }
Referenced by TryLoadConfig().
OnChangeResolution()
void CoreConfig.OnChangeResolution () inline
Definition at line 836 of file CoreConfig.cs.
    {
        ApplyScale();
    }
References ApplyScale().
Referenced by Core.OnChangeResolution().
OnInit()
void CoreConfig.OnInit () inline
Definition at line 731 of file CoreConfig.cs.
    {
        EClass.core.ui.skins.SetMainSkin(test.idSkin);
        Apply();
    }
References Apply(), EClass.core, CoreConfig.Test.idSkin, test, and Core.ui.
Referenced by Init().
OnReset()
void CoreConfig.OnReset () inline
Definition at line 802 of file CoreConfig.cs.
    {
        EClass.core.config.GetPostEffectProfile().OnChangeProfile();
        Apply();
        ApplyFont();
        ApplySkin();
    }
References Apply(), ApplyFont(), ApplySkin(), Core.config, EClass.core, GetPostEffectProfile(), and PostEffectProfile.OnChangeProfile().
Referenced by Reset().
OnSetLang()
void CoreConfig.OnSetLang () inline
Definition at line 1019 of file CoreConfig.cs.
    {
        SkinManager.Instance.InitFont();
        ApplyFont();
    }
References ApplyFont(), SkinManager.InitFont(), and SkinManager.Instance.
Referenced by Core.SetLang().
RefreshUIBrightness()
void CoreConfig.RefreshUIBrightness () inline
Definition at line 976 of file CoreConfig.cs.
    {
        ScreenGrading grading = camSupport.grading;
        float num = 0f;
        float num2 = 0f;
        if (EClass.core.IsGameStarted)
        {
            if (ui.dynamicBrightness && (EClass.world.date.IsNight || EClass._map.config.indoor))
            {
                num -= 0.05f * ui.dynamicBrightnessMod;
            }
        }
        else
        {
            num = -0.05f;
        }
        Shader.SetGlobalFloat("_UIBrightness", 0.01f * (float)ui.brightness + grading.profile.uiBrightness + num);
        Shader.SetGlobalFloat("_UIContrast", 0.01f * (float)ui.contrast + grading.profile.uiContrast + EClass.core.ui.lightContrast + num2);
    }
References EClass._map, CoreConfig.UISetting.brightness, camSupport, Map.config, CoreConfig.UISetting.contrast, EClass.core, World.date, CoreConfig.UISetting.dynamicBrightness, CoreConfig.UISetting.dynamicBrightnessMod, CameraSupport.grading, MapConfig.indoor, Core.IsGameStarted, Date.IsNight, Core.ui, ui, and EClass.world.
Referenced by BaseGameScreen.Activate(), ApplyGrading(), and BaseGameScreen.RefreshGrading().
Reset()
static void CoreConfig.Reset () inline static
Definition at line 742 of file CoreConfig.cs.
    {
        string text = EClass.core.config.lang;
        string text2 = EClass.core.config.rewardCode;
        EClass.core.config = IO.DeepCopy(EClass.setting.config);
        EClass.core.config.SetLang(text);
        EClass.core.config.OnReset();
        EClass.core.config.rewardCode = text2;
    }
References Core.config, GameSetting.config, EClass.core, lang, OnReset(), rewardCode, SetLang(), and EClass.setting.
Referenced by GameSetting.ApplyConfig().
ResetGame()
static void CoreConfig.ResetGame () inline static
Definition at line 770 of file CoreConfig.cs.
    {
        CoreConfig coreConfig = IO.DeepCopy(EClass.setting.config);
        EClass.core.config.game = coreConfig.game;
        EClass.core.config.net = coreConfig.net;
        EClass.core.config.backer = coreConfig.backer;
        EClass.core.config.Apply();
    }
References Apply(), backer, Core.config, GameSetting.config, EClass.core, game, net, and EClass.setting.
Referenced by LayerConfig.OnInit().
ResetGeneral()
static void CoreConfig.ResetGeneral () inline static
Definition at line 752 of file CoreConfig.cs.
    {
        CoreConfig coreConfig = IO.DeepCopy(EClass.setting.config);
        EClass.core.config.ui = coreConfig.ui;
        EClass.core.config.font = coreConfig.font;
        EClass.core.config.sound = coreConfig.sound;
        EClass.core.config.Apply();
        EClass.core.config.ApplyFont();
    }
References Apply(), ApplyFont(), Core.config, GameSetting.config, EClass.core, font, EClass.setting, sound, and ui.
ResetGraphics()
static void CoreConfig.ResetGraphics () inline static
Definition at line 762 of file CoreConfig.cs.
    {
        CoreConfig coreConfig = IO.DeepCopy(EClass.setting.config);
        EClass.core.config.graphic = coreConfig.graphic;
        EClass.core.config.GetPostEffectProfile().OnChangeProfile();
        EClass.core.config.Apply();
    }
References Apply(), Core.config, GameSetting.config, EClass.core, GetPostEffectProfile(), graphic, PostEffectProfile.OnChangeProfile(), and EClass.setting.
Referenced by LayerConfig.OnInit().
ResetInput()
static void CoreConfig.ResetInput () inline static
Definition at line 779 of file CoreConfig.cs.
    {
        CoreConfig coreConfig = IO.DeepCopy(EClass.setting.config);
        EClass.core.config.input = coreConfig.input;
        EClass.core.config.camera = coreConfig.camera;
        EClass.core.config.Apply();
    }
References Apply(), camera, Core.config, GameSetting.config, EClass.core, input, and EClass.setting.
Referenced by LayerConfig.OnInit().
ResetOther()
static void CoreConfig.ResetOther () inline static
Definition at line 787 of file CoreConfig.cs.
    {
        CoreConfig coreConfig = IO.DeepCopy(EClass.setting.config);
        EClass.core.config.fix = coreConfig.fix;
        EClass.core.config.other = coreConfig.other;
        EClass.core.config.Apply();
    }
References Apply(), Core.config, GameSetting.config, EClass.core, fix, other, and EClass.setting.
Referenced by LayerConfig.OnInit().
ResetTest()
static void CoreConfig.ResetTest () inline static
Definition at line 795 of file CoreConfig.cs.
    {
        CoreConfig coreConfig = IO.DeepCopy(EClass.setting.config);
        EClass.core.config.test = coreConfig.test;
        EClass.core.config.Apply();
    }
References Apply(), Core.config, GameSetting.config, EClass.core, EClass.setting, and test.
Referenced by LayerConfig.OnInit().
Save()
void CoreConfig.Save () inline
Definition at line 828 of file CoreConfig.cs.
    {
        version = EClass.core.version;
        IO.SaveFile(path, this, compress: false, IO.jsWriteConfig);
        IO.SaveFile(CorePath.VersionFile, version);
        Debug.Log("Config saved to " + path);
    }
References EClass.core, Debug, path, version, BaseCore.version, and CorePath.VersionFile.
Referenced by Init(), LayerMod.OnInit(), LayerConfig.OnKill(), LayerConfig.Refresh(), and TryUpdatePlayedHour().
SetBGMInterval()
void CoreConfig.SetBGMInterval () inline
Definition at line 1006 of file CoreConfig.cs.
    {
        if (EClass.core.IsGameStarted)
        {
            EClass._map.plDay.interval = other.bgmInterval * 5f;
        }
    }
References EClass.core, and Core.IsGameStarted.
Referenced by ApplyVolume(), and Zone.RefreshBGM().
SetLang()
void CoreConfig.SetLang (string id) inline
Definition at line 810 of file CoreConfig.cs.
    {
        lang = id;
    }
References lang.
Referenced by Init(), and Reset().
SetVolume()
void CoreConfig.SetVolume (string id, float v) inline
Definition at line 1014 of file CoreConfig.cs.
    {
        SoundManager.current.mixer.SetFloat(id, Mathf.Log((v < 0.01f) ? 0.01f : v) * 20f);
    }
Referenced by ApplyVolume().
TryLoadConfig()
static CoreConfig CoreConfig.TryLoadConfig () inline static
Definition at line 662 of file CoreConfig.cs.
    {
        if (!File.Exists(path) || (EClass.debug.useNewConfig && Application.isEditor))
        {
            return null;
        }
        if (!File.Exists(CorePath.VersionFile))
        {
            return null;
        }
        CoreConfig coreConfig = IO.LoadFile<CoreConfig>(path);
        if (!IsCompatible(coreConfig.version))
        {
            Debug.Log("Config version is different. deleting:" + coreConfig.version.ToString() + "/" + EClass.core.version.GetText());
            return null;
        }
        if (coreConfig.game.backupInterval == 0)
        {
            coreConfig.game.numBackup = 5;
            coreConfig.game.backupInterval = 8;
            coreConfig.game.autoBackup = true;
        }
        if (coreConfig.version.IsBelow(0, 23, 138))
        {
            coreConfig.test.extraToneMTP = 1;
        }
        if (coreConfig.version.IsBelow(0, 23, 63))
        {
            coreConfig.graphic.floorEx = true;
        }
        if (coreConfig.version.IsBelow(0, 22, 17))
        {
            coreConfig.game.tutorial = true;
        }
        if (coreConfig.version.IsBelow(0, 22, 24))
        {
            coreConfig.ui.balloonBG = true;
        }
        return coreConfig;
    }
References CoreConfig.GameConfig.backupInterval, EClass.core, EClass.debug, Debug, game, Version.GetText(), Version.IsBelow(), IsCompatible(), path, CoreDebug.useNewConfig, version, BaseCore.version, and CorePath.VersionFile.
Referenced by Core.Start().
TryUpdatePlayedHour()
void CoreConfig.TryUpdatePlayedHour () inline
Definition at line 815 of file CoreConfig.cs.
    {
        if (EClass.core.IsGameStarted)
        {
            int num = (int)(EClass.player.stats.timeElapsed / 3600.0);
            if (num > maxPlayedHours)
            {
                maxPlayedHours = num;
                Save();
            }
        }
    }
References EClass.core, Core.IsGameStarted, maxPlayedHours, EClass.player, Save(), Player.stats, and Player.Stats.timeElapsed.
Referenced by Game.Save().
Member Data Documentation
_framerates
int [] CoreConfig._framerates = new int[4] { 120, 60, 30, 15 } private
Definition at line 634 of file CoreConfig.cs.
Referenced by ApplyFPS().
backer
BackerContentConfig CoreConfig.backer
Definition at line 613 of file CoreConfig.cs.
Referenced by Thing.GetName(), Chara.GetName(), Cell.GetObjName(), TaskHarvest.OnCreateProgress(), TraitDaggerGrave.OnUse(), ResetGame(), and TraitMoongate.UseMoongate().
camera
CameraConfig CoreConfig.camera
Definition at line 617 of file CoreConfig.cs.
Referenced by Apply(), BaseGameScreen.Draw(), ActionMode.InputMovement(), BaseGameScreen.ModTargetZoomIndex(), ActEffect.Proc(), BaseGameScreen.RefreshPosition(), ResetInput(), BaseGameScreen.SetTargetZoomIndex(), and BaseGameScreen.UpdateShaders().
cloud
bool CoreConfig.cloud
Definition at line 599 of file CoreConfig.cs.
Referenced by LayerLoadGame.Init(), and LayerFeedback.OnInit().
colors
int [] CoreConfig.colors = new int[10]
Definition at line 629 of file CoreConfig.cs.
Referenced by GameSetting.CopyColors(), LayerPixelPaint.OnInit(), and UIColorPicker.SetColor().
customFonts
List<FontSource> CoreConfig.customFonts
Definition at line 625 of file CoreConfig.cs.
emailReport
string CoreConfig.emailReport
Definition at line 589 of file CoreConfig.cs.
Referenced by LayerFeedback.OnInit().
fix
Fix CoreConfig.fix
Definition at line 621 of file CoreConfig.cs.
Referenced by BaseGameScreen.RefreshScreenSize(), ResetOther(), and BaseGameScreen.SnapScreen().
font
FontSetting CoreConfig.font
Definition at line 605 of file CoreConfig.cs.
Referenced by ApplyFont(), and ResetGeneral().
game
new GameConfig CoreConfig.game
Definition at line 609 of file CoreConfig.cs.
Referenced by Chara._CreateRenderer(), Chara._Move(), ActPlan._Update(), GameDate.AdvanceMin(), Apply(), ActMelee.Attack(), Act.CanPerform(), ActThrow.CanThrow(), LayerInventory.CreateContainerAlly(), LayerInventory.CreateContainerPC(), BaseTileMap.Draw(), CardRenderer.Draw(), Player.ExitBorder(), Scene.Init(), AM_Adv.OnBecomeNoGoal(), DragItemCard.OnDrag(), InvOwner.OnDrag(), CharaRenderer.OnEnterScreen(), ButtonGrid.OnMiddleClick(), CharaActorPCC.OnRender(), AM_Adv.OnRenderTile(), TraitNewZone.OnStepped(), ActRanged.Perform(), Tutorial.Play(), AM_Adv.PressedActionMove(), ActEffect.Proc(), InvOwner.Transaction.Process(), AM_Adv.RefreshArrow(), AM_Region.RefreshArrow(), UIInventory.RefreshMenu(), ResetGame(), Game.Save(), WidgetCurrentTool.Select(), GameDate.ShipGoods(), Chara.Tick(), Scene.ToggleFreePos(), ActionMode.TogglePause(), Scene.ToggleSnapFreePos(), TryLoadConfig(), HotItemHeld.TrySetAct(), Map.TrySmoothPick(), Card.TryStackTo(), Dialog.TryWarnCrime(), Dialog.TryWarnDisassemble(), Dialog.TryWarnMana(), Dialog.TryWarnSlaughter(), ActionMode.UpdateInput(), and Game.Wait().
graphic
GraphicSetting CoreConfig.graphic
Definition at line 607 of file CoreConfig.cs.
Referenced by GameDate.AdvanceHour(), Apply(), ApplyFPS(), ApplyGrading(), ApplyResolution(), Scene.ApplyZoneConfig(), Card.GetLightRadius(), GetPostEffectProfile(), PostEffectProfile.OnChangeProfile(), LayerConfig.OnInit(), ActEffect.ProcAt(), LayerConfig.Refresh(), BaseGameScreen.RefreshAll(), BaseGameScreen.RefreshGrading(), BaseGameScreen.RefreshSky(), BaseGameScreen.RefreshWeather(), GameScreenElona.RefreshWeather(), ResetGraphics(), Core.Update(), GameUpdater.Update100ms(), and CharaRenderer.UpdatePosition().
helpFlags
HashSet<string> CoreConfig.helpFlags = new HashSet<string>()
Definition at line 627 of file CoreConfig.cs.
Referenced by ELayer.TryShowHelp().
ignoreApply
bool CoreConfig.ignoreApply
Definition at line 632 of file CoreConfig.cs.
Referenced by Apply().
ignoreLinuxModWarning
bool CoreConfig.ignoreLinuxModWarning
Definition at line 597 of file CoreConfig.cs.
Referenced by Scene.TryWarnLinuxMod().
ignoreParallelsWarning
bool CoreConfig.ignoreParallelsWarning
Definition at line 595 of file CoreConfig.cs.
Referenced by Scene.TryWarnMacScreen().
input
InputSetting CoreConfig.input
Definition at line 615 of file CoreConfig.cs.
Referenced by AM_Adv._OnUpdateInput(), Apply(), HotItemHeld.CanChangeHeightByWheel(), ActionMode.IsFuncPressed(), ActionMode.OnCancel(), Scene.OnUpdate(), Dialog.OnUpdateInput(), LayerInfo.OnUpdateInput(), AM_Adv.PressedActionMove(), ResetInput(), and ActionMode.UpdateInput().
lang
string CoreConfig.lang = "JP"
Definition at line 585 of file CoreConfig.cs.
Referenced by Core.Init(), LayerFeedback.OnInit(), LayerConfig.Refresh(), Reset(), and SetLang().
maxPlayedHours
int CoreConfig.maxPlayedHours
Definition at line 593 of file CoreConfig.cs.
Referenced by UI.ToggleFeedback(), and TryUpdatePlayedHour().
nameReport
string CoreConfig.nameReport
Definition at line 587 of file CoreConfig.cs.
Referenced by LayerFeedback.OnInit().
net
NetSetting CoreConfig.net
Definition at line 611 of file CoreConfig.cs.
Referenced by TraitMoongateEx._OnUse(), Scene.OnUpdate(), ResetGame(), TraitMoongate.UseMoongate(), and ActEffect.Wish().
other
OtherSetting CoreConfig.other
Definition at line 619 of file CoreConfig.cs.
Referenced by Apply(), WidgetManager.Load(), Core.OnApplicationFocus(), LayerConfig.OnBeforeAddLayer(), LayerMod.OnInit(), ResetOther(), WidgetManager.Save(), Card.SetCensored(), Core.Start(), and Core.StartCase().
rewardCode
string CoreConfig.rewardCode
Definition at line 591 of file CoreConfig.cs.
Referenced by HasBackerRewardCode(), Reset(), and UI.ToggleFeedback().
sound
SoundSetting CoreConfig.sound
Definition at line 603 of file CoreConfig.cs.
Referenced by ApplyVolume(), LayerConfig.Refresh(), ResetGeneral(), and Scene.ToggleMuteBGM().
test
Test CoreConfig.test
Definition at line 623 of file CoreConfig.cs.
Referenced by TileType._HitTest(), Chara._Move(), ActPlan._Update(), Zone.Activate(), DamageTextRenderer.Add(), Map.AddBackerTree(), Apply(), Map.ApplyBackerObj(), Zone.ApplyBackerPet(), ApplySkin(), AM_Adv.AxisMove(), UICharaMaker.BuildRaces(), Card.DamageHP(), BaseTileMap.Draw(), Chara.OnCreate(), OnInit(), BaseGameScreen.RefreshScreenSize(), ResetTest(), Zone.Revive(), GoalManualMove.Run(), Map.Save(), ButtonGrid.SetCard(), Portrait.SetPortrait(), WidgetHotbar.SetShortcutMenu(), and GoalManualMove.TryAltMove().
ui
new UISetting CoreConfig.ui
Definition at line 601 of file CoreConfig.cs.
Referenced by Apply(), ApplyScale(), UIScaleFix.Awake(), UI.OnUpdate(), LayerConfig.Refresh(), UIHangIcon.Refresh(), RefreshUIBrightness(), UIInventory.RefreshWindow(), ResetGeneral(), TCText.Say(), and ActionMode.UpdateInput().
version
Version CoreConfig.version
Definition at line 583 of file CoreConfig.cs.
Referenced by Save(), and TryLoadConfig().
Property Documentation
camSupport
CameraSupport CoreConfig.camSupport get
Definition at line 651 of file CoreConfig.cs.
Referenced by Apply(), ApplyGrading(), ApplyZoom(), and RefreshUIBrightness().
path
string CoreConfig.path static get
Definition at line 636 of file CoreConfig.cs.
Referenced by Exist(), Save(), Core.Start(), and TryLoadConfig().
ZoomStep
int CoreConfig.ZoomStep static get
Definition at line 638 of file CoreConfig.cs.
    {
        get
        {
            if (!EClass.debug.enable)
            {
                return 5;
            }
            return 5;
        }
    }
Referenced by HotItemContext.Show().
The documentation for this class was generated from the following file:
Elin/CoreConfig.cs