Elin Decompiled Documentation: AIAct Class Reference
AIAct Class Reference
Public Types
enum Status { Running , Fail , Success }
Public Types inherited from Act
enum CostType {
None , MP , SP , None ,
MP , SP
}
enum CostType {
None , MP , SP , None ,
MP , SP
}
Public Member Functions
override string ToString ()
override MultiSprite GetStateIcon ()
virtual Point GetDestination ()
AIProgress GetProgress ()
string GetCurrentActionText ()
override bool IsToolValid ()
virtual void OnStart ()
void SetOwner (Chara c)
virtual void OnSetOwner ()
void SetChild (AIAct seq, Func< Status > _onChildFail=null)
void Start ()
override bool Perform ()
Status Restart ()
Status Success (Action action=null)
virtual void OnSuccess ()
bool TryCancel (Card c)
virtual Status Cancel ()
virtual void OnCancel ()
virtual void OnCancelOrSuccess ()
virtual bool CanManualCancel ()
Status KeepRunning ()
void Reset ()
virtual void OnReset ()
Status Tick ()
virtual IEnumerable< Status > Run ()
Status TickChild ()
Status Do (AIAct _seq, Func< Status > _onChildFail=null)
Status DoGotoInteraction (Point pos, Func< Status > _onChildFail=null)
Status DoGoto (Point pos, int dist=0, bool ignoreConnection=false, Func< Status > _onChildFail=null)
Status DoGoto (Card card, Func< Status > _onChildFail=null)
Status DoGoto (Card card, int dist, Func< Status > _onChildFail=null)
Status DoGotoSpot (Card card, Func< Status > _onChildFail=null)
Status DoGoto< T > (Func< Status > _onChildFail=null)
Status DoGotoSpot< T > (Func< Status > _onChildFail=null, bool ignoreAccessType=false)
Status DoGrab (Card card, int num=-1, bool pickHeld=false, Func< Status > _onChildFail=null)
Status DoGrab< T > ()
Status DoProgress ()
Status DoIdle (int repeat=3)
Status DoWait (int count=1)
virtual AIProgress CreateProgress ()
virtual void OnCreateProgress (Progress_Custom p)
virtual bool CanProgress ()
virtual void OnBeforeProgress ()
virtual void OnProgress ()
virtual void OnProgressComplete ()
void SimulateZone (int days)
virtual void OnSimulateZone (int days)
virtual void OnSimulatePosition ()
Public Member Functions inherited from Act
virtual CursorInfo GetCursorIcon (Card c)
virtual MultiSprite GetStateIcon ()
override Sprite GetSprite ()
virtual bool ShowMouseHint (Card c)
virtual bool IsValidTC (Card c)
virtual string GetHintText (string str="")
virtual string GetText (string str="")
virtual string GetTextSmall (Card c)
virtual Color GetActPlanColor ()
virtual bool Perform ()
virtual bool CanPerform ()
bool Perform (Chara _cc, Card _tc=null, Point _tp=null)
bool CanPerform (Chara _cc, Card _tc=null, Point _tp=null)
virtual bool IsToolValid ()
new void SetImage (Image image)
virtual void OnMarkMapHighlights ()
virtual bool ShouldMapHighlight (Point p)
virtual CursorInfo GetCursorIcon (Card c)
virtual MultiSprite GetStateIcon ()
override Sprite GetSprite ()
virtual bool ShowMouseHint (Card c)
virtual bool IsValidTC (Card c)
virtual string GetHintText (string str="")
virtual string GetText (string str="")
virtual string GetTextSmall (Card c)
virtual Color GetActPlanColor ()
virtual bool Perform ()
virtual bool CanPerform ()
bool Perform (Chara _cc, Card _tc=null, Point _tp=null)
bool CanPerform (Chara _cc, Card _tc=null, Point _tp=null)
virtual bool IsToolValid ()
new void SetImage (Image image)
virtual void OnMarkMapHighlights ()
virtual bool ShouldMapHighlight (Point p)
Public Member Functions inherited from Element
virtual SourceElement.Row GetSource ()
virtual int GetSourcePotential (int v)
virtual Sprite GetSprite ()
int GetMaterialSourceValue (Thing t, int v)
virtual int GetSourceValue (int v, int lv, SourceValueType type)
virtual Sprite GetIcon (string suffix="")
int SortVal (bool charaSheet=false)
virtual bool CanLink (ElementContainer owner)
bool HasTag (string tag)
void SetImage (Image i)
virtual string GetDetail ()
bool IsFactionElement (Chara c)
Element GetParent (Card c)
void WriteNote (UINote n, ElementContainer owner=null, Action< UINote > onWriteNote=null)
void WriteNoteWithRef (UINote n, ElementContainer owner, Action< UINote > onWriteNote, Element refEle)
void _WriteNote (UINote n, Chara c, Act act)
void _WriteNote (UINote n, ElementContainer owner, Action< UINote > onWriteNote, bool isRef, bool addHeader=true)
virtual void OnWriteNote (UINote n, ElementContainer owner)
virtual void OnChangeValue ()
void CheckLevelBonus (ElementContainer owner, UINote n=null)
int GetSortVal (UIList.SortMode m)
virtual Act.Cost GetCost (Chara c)
virtual int GetPower (Card c)
virtual void SetTextValue (UIText text)
virtual SourceElement.Row GetSource ()
virtual int GetSourcePotential (int v)
virtual Sprite GetSprite ()
int GetMaterialSourceValue (Thing t, int v)
virtual int GetSourceValue (int v, int lv, SourceValueType type)
virtual Sprite GetIcon (string suffix="")
int SortVal (bool charaSheet=false)
virtual bool CanLink (ElementContainer owner)
bool HasTag (string tag)
void SetImage (Image i)
virtual string GetDetail ()
bool IsFactionElement (Chara c)
Element GetParent (Card c)
void WriteNote (UINote n, ElementContainer owner=null, Action< UINote > onWriteNote=null)
void WriteNoteWithRef (UINote n, ElementContainer owner, Action< UINote > onWriteNote, Element refEle)
void _WriteNote (UINote n, Chara c, Act act)
void _WriteNote (UINote n, ElementContainer owner, Action< UINote > onWriteNote, bool isRef, bool addHeader=true)
virtual void OnWriteNote (UINote n, ElementContainer owner)
virtual void OnChangeValue ()
void CheckLevelBonus (ElementContainer owner, UINote n=null)
int GetSortVal (UIList.SortMode m)
virtual Act.Cost GetCost (Chara c)
virtual int GetPower (Card c)
virtual void SetTextValue (UIText text)
Public Attributes
new Chara owner
Status status
IEnumerator< Status > Enumerator
AIAct child
AIAct parent
byte restartCount
Func< Status > onChildFail
Func< bool > isFail
Public Attributes inherited from Element
SourceElement.Row _source
int id
int vBase
int vExp
int vPotential
int vTempPotential
int vLink
int vSource
int vSourcePotential
ElementContainer owner
Properties
virtual bool IsRunning [get]
bool IsChildRunning [get]
bool IsMoveAI [get]
virtual int MaxRestart [get]
virtual new string Name [get]
virtual MultiSprite stateIcon [get]
virtual Sprite actionIcon [get]
virtual bool IsNoGoal [get]
virtual bool IsAutoTurn [get]
virtual bool IsIdle [get]
virtual bool PushChara [get]
virtual int MaxProgress [get]
virtual bool ShowProgress [get]
virtual bool UseTurbo [get]
virtual int CurrentProgress [get]
virtual bool ShowCursor [get]
virtual bool CancelWhenDamaged [get]
virtual bool CancelWhenMoved [get]
virtual bool InformCancel [get]
virtual Thing RenderThing [get]
AIAct Current [get]
override bool IsAct [get]
override bool ShowPotential [get]
override bool UsePotential [get]
override bool ShowRelativeAttribute [get]
virtual bool HasProgress [get]
Properties inherited from Act
override bool ShowPotential [get]
override bool UsePotential [get]
override bool ShowRelativeAttribute [get]
virtual CursorInfo CursorIcon [get]
virtual string ID [get]
virtual bool IsAct [get]
virtual bool WillEndTurn [get]
virtual bool CloseLayers [get]
virtual int LeftHand [get]
virtual int RightHand [get]
virtual int ElementPowerMod [get]
virtual bool ShowMapHighlight [get]
virtual bool ShowMapHighlightBlock [get]
virtual bool PickHeldOnStart [get]
virtual bool DropHeldOnStart [get]
virtual bool CanPressRepeat [get]
virtual bool CanAutofire [get]
virtual bool ResetAxis [get]
virtual bool RequireTool [get]
virtual bool IsHostileAct [get]
virtual bool HideRightInfo [get]
virtual bool HaveLongPressAction [get]
virtual float Radius [get]
virtual int PerformDistance [get]
virtual int MaxRadius [get]
virtual TargetType TargetType [get]
virtual bool LocalAct [get]
virtual bool CanRapidFire [get]
virtual float RapidDelay [get]
virtual bool ShowAuto [get]
virtual bool IsCrime [get]
Properties inherited from Element
SourceElement.Row source [get]
virtual int DisplayValue [get]
virtual int MinValue [get]
int Value [get]
int ValueWithoutLink [get]
virtual int MinPotential [get]
int Potential [get]
virtual bool CanGainExp [get]
bool IsFlag [get]
virtual string Name [get]
virtual string FullName [get]
virtual int ExpToNext [get]
virtual bool UseExpMod [get]
virtual int CostTrain [get]
virtual int CostLearn [get]
virtual bool ShowXP [get]
virtual bool ShowMsgOnValueChanged [get]
virtual bool ShowValue [get]
virtual bool ShowPotential [get]
virtual bool UsePotential [get]
virtual bool PotentialAsStock [get]
virtual bool ShowRelativeAttribute [get]
virtual bool ShowBonuses [get]
virtual string ShortName [get]
bool IsGlobalElement [get]
bool IsFactionWideElement [get]
bool IsPartyWideElement [get]
virtual bool ShowEncNumber [get]
bool IsTrait [get]
bool IsFoodTrait [get]
bool IsFoodTraitMain [get]
bool IsMainAttribute [get]
Act act [get]
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Additional Inherited Members
Static Public Member Functions inherited from Act
static void SetReference (Chara _cc, Card _tc=null, Point _tp=null)
static void SetTool (Thing t)
static void SetReference (Chara _cc, Card _tc=null, Point _tp=null)
static void SetTool (Thing t)
Static Public Member Functions inherited from Element
static string GetName (string alias)
static SourceElement.Row Get (int id)
static Dictionary< int, int > GetElementMap (int[] list)
static Dictionary< int, int > GetElementMap (int[] list, Dictionary< int, int > map)
static SourceElement.Row GetRandomElement (int lv=1)
static Element Create (int id, int v=0)
static Element Create (string id, int v=1)
static int GetId (string alias)
static int GetResistLv (int v)
static int GetResistDamage (int dmg, int v)
static string GetName (string alias)
static SourceElement.Row Get (int id)
static Dictionary< int, int > GetElementMap (int[] list)
static Dictionary< int, int > GetElementMap (int[] list, Dictionary< int, int > map)
static SourceElement.Row GetRandomElement (int lv=1)
static Element Create (int id, int v=0)
static Element Create (string id, int v=1)
static int GetId (string alias)
static int GetResistLv (int v)
static int GetResistDamage (int dmg, int v)
Static Public Member Functions inherited from EClass
static int rnd (int a)
static int curve (int a, int start, int step, int rate=75)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Static Public Attributes inherited from Act
static Chara CC
static Card TC
static Point TP = new Point()
static Thing TOOL
static int powerMod = 100
static bool forcePt
Static Public Attributes inherited from Element
const int Div = 5
static Element Void = new Element()
static int[] List_MainAttributes
static int[] List_MainAttributesMajor
static int[] List_Body
static int[] List_Mind
static List< SourceElement.Row > ListElements = new List<SourceElement.Row>()
static List< SourceElement.Row > ListAttackElements = new List<SourceElement.Row>()
Static Public Attributes inherited from EClass
static Core core
Static Package Functions inherited from Element
static string< _WriteNote > g__Calc (ref Element.<>c__DisplayClass103_0 A_0)
Detailed Description
Definition at line 5 of file AIAct.cs.
Member Enumeration Documentation
Status
enum AIAct.Status
Enumerator
Running
Fail
Success
Definition at line 7 of file AIAct.cs.
    {
        Running,
        Fail,
        Success
    }
Member Function Documentation
Cancel()
virtual Status AIAct.Cancel () inline virtual
Reimplemented in AI_Massage, and Task.
Definition at line 284 of file AIAct.cs.
    {
        status = Status.Fail;
        if (owner != null && owner.held != null && !owner.IsPC)
        {
            owner.PickHeld();
        }
        OnCancel();
        OnCancelOrSuccess();
        Reset();
        return status;
    }
References Chara.held, Chara.IsPC, OnCancel(), OnCancelOrSuccess(), owner, Chara.PickHeld(), Reset(), and status.
Referenced by AM_Adv._OnUpdateInput(), AM_Adv.AxisMove(), QueueManager.Cancel(), AI_OpenLock.CreateProgress(), AI_PracticeDummy.CreateProgress(), DoGoto(), DoGotoInteraction(), DoGotoSpot(), DoGrab(), Chara.IsEnemyOnPath(), Card.MoveImmediate(), TraitNewZone.MoveZone(), AM_Adv.OnActivate(), AI_Torture.OnCancelOrSuccess(), TaskDig.OnCreateProgress(), TaskHarvest.OnCreateProgress(), TaskMine.OnCreateProgress(), TaskPlow.OnCreateProgress(), LayerDragGrid.OnKill(), AI_Fish.ProgressFish.OnProgress(), AM_Adv.PressedActionMove(), Chara.ReleaseMinion(), AI_Bladder.Run(), AI_Cook.Run(), AI_Deconstruct.Run(), AI_Drink.Run(), AI_Eat.Run(), AI_Equip.Run(), AI_Fish.Run(), AI_Fuck.Run(), AI_Goto.Run(), AI_Grab< T >.Run(), AI_Offer.Run(), AI_PlayMusic.Run(), AI_Read.Run(), AI_Shear.Run(), AI_Steal.Run(), AI_TargetCard.Run(), AI_UseCrafter.Run(), AIProgress.Run(), GoalCombat.Run(), GoalManualMove.Run(), GoalSpot.Run(), GoalTask.Run(), Chara.SetAI(), SetChild(), Card.Teleport(), Tick(), Player.TryAbortAutoCombat(), TryCancel(), AM_Adv.TryCancelInteraction(), and AI_Goto.TryGoTo().
CanManualCancel()
virtual bool AIAct.CanManualCancel () inline virtual
Reimplemented in AI_Eat, AI_Fish, AI_Goto, AI_PassTime, AI_PracticeDummy, AI_Torture, AI_Trolley, AI_UseCrafter, GoalCombat, TaskBuild, TaskCraft, TaskCullLife, TaskDrawWater, TaskDump, TaskHarvest, TaskPoint, TaskPourWater, and TaskWater.
Definition at line 305 of file AIAct.cs.
    {
        if (IsChildRunning)
        {
            return child is AI_Goto;
        }
        return false;
    }
References child, and IsChildRunning.
Referenced by AM_Adv._OnUpdateInput(), and AM_Adv.TryCancelInteraction().
CanProgress()
virtual bool AIAct.CanProgress () inline virtual
Reimplemented in AI_TargetCard, BaseTaskHarvest, Progress_Custom, Task, TaskCraft, TaskDrawWater, TaskHarvest, TaskPlow, and TaskPourWater.
Definition at line 554 of file AIAct.cs.
    {
        return true;
    }
Referenced by CreateProgress(), and AIProgress.Run().
CreateProgress()
virtual AIProgress AIAct.CreateProgress () inline virtual
Reimplemented in AI_Fish, AI_OpenLock, AI_PracticeDummy, and AI_Torture.
Definition at line 534 of file AIAct.cs.
    {
        Progress_Custom progress_Custom = new Progress_Custom
        {
            onProgress = delegate
            {
                OnProgress();
            },
            onProgressComplete = OnProgressComplete,
            canProgress = CanProgress,
            onBeforeProgress = OnBeforeProgress
        };
        OnCreateProgress(progress_Custom);
        return progress_Custom;
    }
References CanProgress(), OnBeforeProgress(), OnCreateProgress(), OnProgress(), and OnProgressComplete().
Referenced by DoProgress(), AIWork_Lumberjack.GetWork(), and AIWork_Research.GetWork().
Do()
Status AIAct.Do (AIAct _seq, Func< Status > _onChildFail = null) inline
Definition at line 409 of file AIAct.cs.
    {
        SetChild(_seq, _onChildFail);
        return TickChild();
    }
References SetChild(), and TickChild().
Referenced by AI_Bladder.Run(), AI_Deconstruct.Run(), AI_Eat.Run(), AI_HaulResource.Run(), AI_Idle.Run(), AI_Paint.Run(), AI_Pray.Run(), AI_Shear.Run(), AI_Steal.Run(), AI_UseCrafter.Run(), AIWork.Run(), GoalIdle.Run(), GoalNeeds.Run(), GoalTask.Run(), GoalVisitorEnemy.Run(), and TaskMoveInstalled.Run().
DoGoto() [1/3]
Status AIAct.DoGoto (Card card, Func< Status > _onChildFail = null) inline
Definition at line 435 of file AIAct.cs.
    {
        return DoGoto(card, (card.isChara || card.pos.cell.blocked) ? 1 : 0, _onChildFail);
    }
References Algorithms.WeightCell.blocked, Point.cell, DoGoto(), Card.isChara, and Card.pos.
DoGoto() [2/3]
Status AIAct.DoGoto (Card card, int dist, Func< Status > _onChildFail = null) inline
Definition at line 440 of file AIAct.cs.
    {
        if (card != null && card == owner.held)
        {
            return Status.Running;
        }
        if (card == null || !card.ExistsOnMap)
        {
            return _onChildFail?.Invoke() ?? Cancel();
        }
        SetChild(new AI_Goto(card, dist), _onChildFail);
        return TickChild();
    }
References Cancel(), Card.ExistsOnMap, Chara.held, owner, SetChild(), and TickChild().
DoGoto() [3/3]
Status AIAct.DoGoto (Point pos, int dist = 0, bool ignoreConnection = false, Func< Status > _onChildFail = null) inline
Definition at line 425 of file AIAct.cs.
    {
        if (pos == null || !pos.IsValid)
        {
            return _onChildFail?.Invoke() ?? Cancel();
        }
        SetChild(new AI_Goto(pos, dist, ignoreConnection), _onChildFail);
        return TickChild();
    }
References Cancel(), Point.IsValid, SetChild(), and TickChild().
Referenced by DoGoto(), DoGoto< T >(), DoGotoSpot< T >(), AI_ArmPillow.Run(), AI_AttackHome.Run(), AI_Bladder.Run(), AI_Clean.Run(), AI_Cook.Run(), AI_Deconstruct.Run(), AI_Equip.Run(), AI_Fish.Run(), AI_Fuck.Run(), AI_GotoHearth.Run(), AI_Grab< T >.Run(), AI_Haul.Run(), AI_HaulResource.Run(), AI_Idle.Run(), AI_LeaveMap.Run(), AI_Massage.Run(), AI_Offer.Run(), AI_PassTime.Run(), AI_PlayMusic.Run(), AI_Pray.Run(), AI_ReleaseHeld.Run(), AI_Shear.Run(), AI_Shopping.Run(), AI_TargetCard.Run(), AIWork.Run(), GoalCombat.Run(), GoalGraze.Run(), GoalSiege.Run(), GoalSleep.Run(), GoalSpot.Run(), TaskCullLife.Run(), TaskDump.Run(), TaskMoveInstalled.Run(), TaskPoint.Run(), and TaskWater.Run().
DoGoto< T >()
Status AIAct.DoGoto< T > (Func< Status > _onChildFail = null) inline
Type Constraints
T : Trait
Definition at line 470 of file AIAct.cs.
                                                                      : Trait
    {
        return DoGoto(EClass._map.Installed.traits.GetTraitSet<T>().GetRandom()?.owner, _onChildFail);
    }
References EClass._map, DoGoto(), TraitSet.GetRandom(), TraitManager.GetTraitSet(), Map.Installed, Trait.owner, and Props.traits.
DoGotoInteraction()
Status AIAct.DoGotoInteraction (Point pos, Func< Status > _onChildFail = null) inline
Definition at line 415 of file AIAct.cs.
    {
        if (pos == null || !pos.IsValid)
        {
            return _onChildFail?.Invoke() ?? Cancel();
        }
        SetChild(new AI_Goto(pos, 0, _ignoreConnection: false, _interaction: true), _onChildFail);
        return TickChild();
    }
References Cancel(), Point.IsValid, SetChild(), and TickChild().
Referenced by AI_TargetCard.Run(), and DynamicAIAct.Run().
DoGotoSpot()
Status AIAct.DoGotoSpot (Card card, Func< Status > _onChildFail = null) inline
Definition at line 454 of file AIAct.cs.
    {
        if (card != null && card == owner.held)
        {
            return Status.Running;
        }
        if (card == null || !card.ExistsOnMap)
        {
            return _onChildFail?.Invoke() ?? Cancel();
        }
        Point randomPoint = card.trait.GetRandomPoint();
        int dist = (randomPoint.cell.blocked ? 1 : 0);
        SetChild(new AI_Goto(randomPoint, dist), _onChildFail);
        return TickChild();
    }
References Cancel(), Card.ExistsOnMap, Trait.GetRandomPoint(), Chara.held, owner, SetChild(), TickChild(), and Card.trait.
Referenced by AI_Idle.Run().
DoGotoSpot< T >()
Status AIAct.DoGotoSpot< T > (Func< Status > _onChildFail = null, bool ignoreAccessType = false) inline
Type Constraints
T : Trait
Definition at line 475 of file AIAct.cs.
                                                                                                         : Trait
    {
        Trait random = EClass._map.Installed.traits.GetTraitSet<T>().GetRandom(ignoreAccessType ? null : owner);
        if (random != null)
        {
            DoGoto(random.GetRandomPoint(null, ignoreAccessType ? null : owner), 0, ignoreConnection: false, _onChildFail);
        }
        return _onChildFail?.Invoke() ?? Status.Fail;
    }
References EClass._map, DoGoto(), Trait.GetRandomPoint(), TraitManager.GetTraitSet(), Map.Installed, owner, and Props.traits.
DoGrab()
Status AIAct.DoGrab (Card card, int num = -1, bool pickHeld = false, Func< Status > _onChildFail = null) inline
Definition at line 485 of file AIAct.cs.
    {
        if (card != null && card == owner.held)
        {
            return Status.Running;
        }
        if (card == null || !card.GetRootCard().ExistsOnMap)
        {
            return Cancel();
        }
        SetChild(new AI_Grab
        {
            target = card,
            num = num,
            pickHeld = pickHeld
        }, _onChildFail);
        return TickChild();
    }
References Cancel(), Card.ExistsOnMap, Card.GetRootCard(), Chara.held, owner, SetChild(), and TickChild().
Referenced by AI_Drink.Run(), AI_Eat.Run(), AI_HaulResource.Run(), AI_Offer.Run(), AI_Read.Run(), and TaskMoveInstalled.Run().
DoGrab< T >()
Status AIAct.DoGrab< T > () inline
Type Constraints
T : Trait
Definition at line 504 of file AIAct.cs.
                                      : Trait
    {
        SetChild(new AI_Grab<T>());
        return TickChild();
    }
References SetChild(), and TickChild().
DoIdle()
Status AIAct.DoIdle (int repeat = 3) inline
Definition at line 516 of file AIAct.cs.
    {
        SetChild(new AI_Idle
        {
            maxRepeat = repeat
        }, KeepRunning);
        return TickChild();
    }
References KeepRunning(), SetChild(), and TickChild().
Referenced by AI_Clean.Run(), AIWork.Run(), AIWork_Explore.Run(), GoalGraze.Run(), GoalIdle.Run(), GoalVisitorGuest.Run(), and GoalWork.Run().
DoProgress()
Status AIAct.DoProgress () inline
Definition at line 510 of file AIAct.cs.
    {
        SetChild(CreateProgress());
        return TickChild();
    }
References CreateProgress(), SetChild(), and TickChild().
Referenced by AI_Fish.Run(), AI_PracticeDummy.Run(), AI_TargetCard.Run(), AI_Torture.Run(), TaskCraft.Run(), and TaskPoint.Run().
DoWait()
Status AIAct.DoWait (int count = 1) inline
Definition at line 525 of file AIAct.cs.
    {
        SetChild(new AI_Wait
        {
            count = count
        }, KeepRunning);
        return TickChild();
    }
References KeepRunning(), SetChild(), and TickChild().
Referenced by AI_Dance.Run(), AI_Fish.Run(), and DynamicAIAct.Run().
GetCurrentActionText()
string AIAct.GetCurrentActionText () inline
Definition at line 150 of file AIAct.cs.
    {
        if (IsChildRunning && child.source.id != 0 && !child.source.name_JP.IsEmpty())
        {
            return child.GetCurrentActionText();
        }
        return base.source.GetName().IsEmpty("idle".lang());
    }
References child, GetCurrentActionText(), IsChildRunning, and Element.source.
Referenced by Chara.GetActionText(), and GetCurrentActionText().
GetDestination()
virtual Point AIAct.GetDestination () inline virtual
Reimplemented in AI_Goto.
Definition at line 132 of file AIAct.cs.
    {
        if (!IsChildRunning)
        {
            return owner.pos;
        }
        return child.GetDestination();
    }
References child, GetDestination(), IsChildRunning, owner, and Card.pos.
Referenced by GetDestination(), and Chara.GetDestination().
GetProgress()
AIProgress AIAct.GetProgress () inline
Definition at line 141 of file AIAct.cs.
    {
        if (IsChildRunning)
        {
            return child.GetProgress();
        }
        return this as AIProgress;
    }
References child, GetProgress(), and IsChildRunning.
Referenced by UIAutoTurn._Update(), and GetProgress().
GetStateIcon()
override MultiSprite AIAct.GetStateIcon () inline virtual
Reimplemented from Act.
Definition at line 127 of file AIAct.cs.
    {
        return (child ?? this).stateIcon;
    }
References child.
Referenced by CharaRenderer.RefreshStateIcon().
IsToolValid()
override bool AIAct.IsToolValid () inline virtual
Reimplemented from Act.
Definition at line 159 of file AIAct.cs.
    {
        if (owner == EClass.pc && Act.TOOL != null)
        {
            return Act.TOOL.parent == EClass.pc;
        }
        return false;
    }
References owner, EClass.pc, and Act.TOOL.
Referenced by TaskCut.OnProgress().
KeepRunning()
Status AIAct.KeepRunning () inline
Definition at line 314 of file AIAct.cs.
    {
        return Status.Running;
    }
Referenced by DoIdle(), DoWait(), AI_Clean.Run(), AI_Eat.Run(), AI_Idle.Run(), AI_OpenGambleChest.Run(), AI_PassTime.Run(), AI_Torture.Run(), AI_Trolley.Run(), AIWork.Run(), TaskCullLife.Run(), TaskPoint.Run(), and TaskWater.Run().
OnBeforeProgress()
virtual void AIAct.OnBeforeProgress () inline virtual
Reimplemented in Progress_Custom, and TaskCraft.
Definition at line 559 of file AIAct.cs.
    {
    }
Referenced by CreateProgress(), and AIProgress.Run().
OnCancel()
virtual void AIAct.OnCancel () inline virtual
Reimplemented in AI_PassTime, AI_PlayMusic, AI_Trolley, and AI_UseCrafter.
Definition at line 297 of file AIAct.cs.
    {
    }
Referenced by Cancel().
OnCancelOrSuccess()
virtual void AIAct.OnCancelOrSuccess () inline virtual
Reimplemented in AI_Torture, and TaskDump.
Definition at line 301 of file AIAct.cs.
    {
    }
Referenced by Cancel(), and Success().
OnCreateProgress()
virtual void AIAct.OnCreateProgress (Progress_Custom p) inline virtual
Reimplemented in AIWork_Lumberjack, AIWork_Research, TaskCraft, TaskCut, TaskDig, TaskDrawWater, TaskHarvest, TaskMine, TaskPlow, and TaskPourWater.
Definition at line 550 of file AIAct.cs.
    {
    }
Referenced by CreateProgress().
OnProgress()
virtual void AIAct.OnProgress () inline virtual
Reimplemented in AI_Farm, AI_Fish.ProgressFish, AI_Water, Progress_Custom, TaskCraft, and TaskCut.
Definition at line 563 of file AIAct.cs.
    {
    }
Referenced by CreateProgress(), and AIProgress.Run().
OnProgressComplete()
virtual void AIAct.OnProgressComplete () inline virtual
Reimplemented in AI_Farm, AI_Fish.ProgressFish, AI_Sleep, AI_Water, Progress_Custom, TaskBuild, TaskCraft, TaskCut, TaskDig, TaskMine, and TaskMoveInstalled.
Definition at line 567 of file AIAct.cs.
    {
    }
Referenced by CreateProgress(), AI_TargetCard.Run(), AIProgress.Run(), and TaskPoint.Run().
OnReset()
virtual void AIAct.OnReset () inline virtual
Reimplemented in AI_Bladder, AI_Goto, and Task.
Definition at line 341 of file AIAct.cs.
    {
    }
Referenced by Reset().
OnSetOwner()
virtual void AIAct.OnSetOwner () inline virtual
Reimplemented in AI_Drink, and AI_Read.
Definition at line 179 of file AIAct.cs.
    {
    }
Referenced by SetOwner().
OnSimulatePosition()
virtual void AIAct.OnSimulatePosition () inline virtual
Reimplemented in GoalGraze, GoalSleep, and GoalWork.
Definition at line 583 of file AIAct.cs.
    {
    }
Referenced by Zone.Simulate().
OnSimulateZone()
virtual void AIAct.OnSimulateZone (int days) inline virtual
Definition at line 579 of file AIAct.cs.
    {
    }
Referenced by SimulateZone().
OnStart()
virtual void AIAct.OnStart () inline virtual
Reimplemented in AI_Eat, AI_Fish.ProgressFish, AI_Idle, AI_PassTime, AI_UseCrafter, and TaskCut.
Definition at line 168 of file AIAct.cs.
    {
    }
Referenced by Start().
OnSuccess()
virtual void AIAct.OnSuccess () inline virtual
Reimplemented in AI_UseCrafter, and Task.
Definition at line 255 of file AIAct.cs.
    {
    }
Referenced by Success().
Perform()
override bool AIAct.Perform () inline virtual
Reimplemented from Act.
Reimplemented in DynamicAIAct.
Definition at line 224 of file AIAct.cs.
    {
        Act.CC.SetAIImmediate(this);
        return false;
    }
References Act.CC, and Chara.SetAIImmediate().
Reset()
void AIAct.Reset () inline
Definition at line 319 of file AIAct.cs.
    {
        if (owner != null)
        {
            if (child != null)
            {
                child.Reset();
            }
            OnReset();
            if (Enumerator != null)
            {
                Enumerator.Dispose();
                Enumerator = null;
            }
            owner = null;
            child = null;
            restartCount = 0;
            onChildFail = null;
            isFail = null;
        }
    }
References child, Enumerator, isFail, onChildFail, OnReset(), owner, Reset(), and restartCount.
Referenced by Cancel(), ActPlan.Item.Perform(), Reset(), Restart(), SetChild(), and Success().
Restart()
Status AIAct.Restart () inline
Definition at line 230 of file AIAct.cs.
    {
        restartCount++;
        if (restartCount >= MaxRestart)
        {
            return Success();
        }
        byte b = restartCount;
        Chara chara = owner;
        Reset();
        SetOwner(chara);
        restartCount = b;
        return status = Status.Running;
    }
References MaxRestart, owner, Reset(), restartCount, SetOwner(), status, and Success.
Referenced by AI_Fish.Run(), AI_Idle.Run(), AIWork.Run(), GoalVisitorEnemy.Run(), GoalVisitorGuest.Run(), NoGoal.Run(), TaskCraft.Run(), and AI_Goto.TryGoTo().
Run()
virtual IEnumerable< Status > AIAct.Run () inline virtual
Reimplemented in AI_ArmPillow, AI_AttackHome, AI_Bladder, AI_Clean, AI_Cook, AI_Dance, AI_Deconstruct, AI_Drink, AI_Eat, AI_Equip, AI_Fish, AI_Fuck, AI_Goto, AI_GotoHearth, AI_Grab< T >, AI_Haul, AI_HaulResource, AI_Idle, AI_LeaveMap, AI_Massage, AI_Offer, AI_OpenGambleChest, AI_Paint, AI_PassTime, AI_PlayMusic, AI_PracticeDummy, AI_Pray, AI_Read, AI_ReleaseHeld, AI_Shear, AI_Shopping, AI_Steal, AI_TargetCard, AI_Torture, AI_Trolley, AI_UseCrafter, AI_Wait, AIProgress, AIWork, AIWork_Explore, DynamicAIAct, GoalCombat, GoalGraze, GoalIdle, GoalManualMove, GoalNeeds, GoalSearch, GoalSiege, GoalSleep, GoalSpot, GoalTask, GoalVisitorEnemy, GoalVisitorGuest, GoalWait, GoalWork, NoGoal, TaskCraft, TaskCullLife, TaskDump, TaskMoveInstalled, TaskPoint, and TaskWater.
Definition at line 386 of file AIAct.cs.
    {
        yield return Success();
    }
References Success.
Referenced by Start().
SetChild()
void AIAct.SetChild (AIAct seq, Func< Status > _onChildFail = null) inline
Definition at line 183 of file AIAct.cs.
    {
        if (child != null)
        {
            child.Reset();
        }
        child = seq;
        child.parent = this;
        child.SetOwner(owner);
        onChildFail = _onChildFail ?? new Func<Status>(Cancel);
    }
References Cancel(), child, onChildFail, owner, Reset(), and SetOwner().
Referenced by Do(), DoGoto(), DoGotoInteraction(), DoGotoSpot(), DoGrab(), DoGrab< T >(), DoIdle(), DoProgress(), and DoWait().
SetOwner()
void AIAct.SetOwner (Chara c) inline
Definition at line 172 of file AIAct.cs.
    {
        owner = c;
        status = Status.Running;
        OnSetOwner();
    }
References OnSetOwner(), owner, and status.
Referenced by BaseTaskHarvest.GetBestTool(), Restart(), Chara.SetAI(), and SetChild().
SimulateZone()
void AIAct.SimulateZone (int days) inline
Definition at line 571 of file AIAct.cs.
    {
        if (owner.conSuspend == null)
        {
            OnSimulateZone(days);
        }
    }
References Chara.conSuspend, OnSimulateZone(), and owner.
Referenced by Zone.Simulate().
Start()
void AIAct.Start () inline
Definition at line 195 of file AIAct.cs.
    {
        Enumerator = Run().GetEnumerator();
        OnStart();
        if (owner == null)
        {
            return;
        }
        if (owner.held != null)
        {
            if (DropHeldOnStart)
            {
                owner.DropHeld();
            }
            else if (PickHeldOnStart)
            {
                owner.PickHeld();
            }
        }
        if (RightHand != 0)
        {
            owner.SetTempHand(RightHand, LeftHand);
        }
        if (owner.IsPC && UseTurbo)
        {
            ActionMode.Adv.SetTurbo();
        }
    }
References ActionMode.Adv, Chara.DropHeld(), Act.DropHeldOnStart, Enumerator, Chara.held, Chara.IsPC, Act.LeftHand, OnStart(), owner, Chara.PickHeld(), Act.PickHeldOnStart, Act.RightHand, Run(), Chara.SetTempHand(), AM_Adv.SetTurbo(), and UseTurbo.
Referenced by Tick().
Success()
Status AIAct.Success (Action action = null) inline
Definition at line 245 of file AIAct.cs.
    {
        status = Status.Success;
        OnSuccess();
        action?.Invoke();
        OnCancelOrSuccess();
        Reset();
        return status;
    }
References OnCancelOrSuccess(), OnSuccess(), Reset(), and status.
Referenced by InvOwnerDraglet.OnClick().
Tick()
Status AIAct.Tick () inline
Definition at line 345 of file AIAct.cs.
    {
        if (owner == null || (isFail != null && isFail()))
        {
            return Cancel();
        }
        if (IsChildRunning)
        {
            switch (child.Tick())
            {
            case Status.Fail:
                if (onChildFail != null)
                {
                    return onChildFail();
                }
                return Status.Fail;
            case Status.Running:
                return Status.Running;
            case Status.Success:
                if (owner == null || (isFail != null && isFail()))
                {
                    return Cancel();
                }
                break;
            }
        }
        if (Enumerator == null)
        {
            Start();
            if (status != 0)
            {
                return status;
            }
        }
        if (!Enumerator.MoveNext())
        {
            return Success();
        }
        return status;
    }
References Cancel(), child, Enumerator, IsChildRunning, isFail, onChildFail, owner, Start(), status, Success, and Tick().
Referenced by Chara.ChooseNewGoal(), Tick(), Chara.Tick(), and TickChild().
TickChild()
Status AIAct.TickChild () inline
Definition at line 391 of file AIAct.cs.
    {
        if (child == null || onChildFail == null)
        {
            Debug.Log(child?.ToString() + "/" + onChildFail);
            return Status.Fail;
        }
        if (child.Tick() == Status.Fail)
        {
            if (onChildFail != null)
            {
                return onChildFail();
            }
            return Status.Fail;
        }
        return Status.Running;
    }
References child, onChildFail, Tick(), and ToString().
Referenced by Do(), DoGoto(), DoGotoInteraction(), DoGotoSpot(), DoGrab(), DoGrab< T >(), DoIdle(), DoProgress(), and DoWait().
ToString()
override string AIAct.ToString () inline
Definition at line 122 of file AIAct.cs.
    {
        return GetType().Name;
    }
Referenced by Chara.GetHoverText2(), UIQueue.OnAdd(), TickChild(), Chara.ToString(), and WidgetDebug.UpdateText().
TryCancel()
bool AIAct.TryCancel (Card c) inline
Definition at line 259 of file AIAct.cs.
    {
        if (!IsRunning || Enumerator == null)
        {
            return false;
        }
        if (InformCancel)
        {
            if (owner.IsPC)
            {
                owner.Say("cancel_act_pc", owner);
            }
            else if (c != null)
            {
                owner.Say("cancel_act", owner, c);
            }
            else
            {
                owner.Say("cancel_act2", owner);
            }
        }
        Cancel();
        return true;
    }
References Cancel(), Enumerator, InformCancel, Chara.IsPC, IsRunning, owner, and Card.Say().
Referenced by Card.DamageHP(), and Chara.MoveByForce().
Member Data Documentation
child
AIAct AIAct.child
Definition at line 20 of file AIAct.cs.
Referenced by CanManualCancel(), TaskPoint.CanManualCancel(), GetCurrentActionText(), GetDestination(), GetProgress(), GetStateIcon(), Reset(), SetChild(), Tick(), and TickChild().
Enumerator
IEnumerator<Status> AIAct.Enumerator
Definition at line 18 of file AIAct.cs.
Referenced by Reset(), Start(), Tick(), and TryCancel().
isFail
Func<bool> AIAct.isFail
Definition at line 28 of file AIAct.cs.
Referenced by AI_PracticeDummy.CreateProgress(), AI_Torture.CreateProgress(), Reset(), AI_ArmPillow.Run(), AI_Fuck.Run(), AI_Massage.Run(), AI_PracticeDummy.Run(), AI_TargetCard.Run(), AI_Torture.Run(), and Tick().
onChildFail
Func<Status> AIAct.onChildFail
Definition at line 26 of file AIAct.cs.
Referenced by Reset(), SetChild(), Tick(), and TickChild().
owner
new Chara AIAct.owner
Definition at line 14 of file AIAct.cs.
Referenced by AIWork.AddDeliverable(), Recipe.Build(), RecipeCard.Build(), GoalCombat.BuildAbilityList(), Cancel(), TaskPoint.CanPerform(), AI_TargetCard.CanProgress(), TaskHarvest.CanProgress(), AI_OpenLock.CreateProgress(), AI_PracticeDummy.CreateProgress(), AI_Torture.CreateProgress(), DoGoto(), DoGotoSpot(), DoGotoSpot< T >(), DoGrab(), TaskBuild.DrawMarker(), AI_Fish.ProgressFish.Fail(), GoalWork.FindWork(), AI_Fuck.Finish(), GetDestination(), TaskMine.GetHitResult(), GoalGraze.GetPos(), BaseTaskHarvest.GetText(), GoalHobby.GetWorks(), GoalWork.GetWorks(), TaskHarvest.HarvestThing(), AI_HaulResource.HoldingResource(), AI_Goto.IsDestinationReached(), IsToolValid(), AI_OpenGambleChest.IsValid(), AI_Eat.IsValidTarget(), AI_PassTime.OnCancel(), AIWork_Lumberjack.OnCreateProgress(), AIWork_Research.OnCreateProgress(), TaskDig.OnCreateProgress(), TaskDrawWater.OnCreateProgress(), TaskHarvest.OnCreateProgress(), TaskMine.OnCreateProgress(), TaskPlow.OnCreateProgress(), TaskPourWater.OnCreateProgress(), AI_Farm.OnProgress(), AI_Fish.ProgressFish.OnProgress(), AI_Water.OnProgress(), TaskCraft.OnProgress(), TaskCut.OnProgress(), AI_Fish.ProgressFish.OnProgressComplete(), AI_Sleep.OnProgressComplete(), AI_Water.OnProgressComplete(), TaskCraft.OnProgressComplete(), TaskDig.OnProgressComplete(), TaskMine.OnProgressComplete(), TaskMoveInstalled.OnProgressComplete(), AI_Bladder.OnReset(), AI_Drink.OnSetOwner(), AI_Read.OnSetOwner(), GoalGraze.OnSimulatePosition(), GoalSleep.OnSimulatePosition(), GoalWork.OnSimulatePosition(), AI_Fish.ProgressFish.OnStart(), AI_Idle.OnStart(), AI_UseCrafter.OnStart(), TaskCut.OnStart(), Reset(), Restart(), AI_ArmPillow.Run(), AI_AttackHome.Run(), AI_Bladder.Run(), AI_Clean.Run(), AI_Cook.Run(), AI_Dance.Run(), AI_Deconstruct.Run(), AI_Drink.Run(), AI_Eat.Run(), AI_Equip.Run(), AI_Fish.Run(), AI_Fuck.Run(), AI_Goto.Run(), AI_GotoHearth.Run(), AI_Grab< T >.Run(), AI_Haul.Run(), AI_HaulResource.Run(), AI_Idle.Run(), AI_Massage.Run(), AI_Offer.Run(), AI_OpenGambleChest.Run(), AI_Paint.Run(), AI_PassTime.Run(), AI_PlayMusic.Run(), AI_Pray.Run(), AI_Read.Run(), AI_ReleaseHeld.Run(), AI_Shear.Run(), AI_Shopping.Run(), AI_Steal.Run(), AI_TargetCard.Run(), AI_Torture.Run(), AI_Trolley.Run(), AI_UseCrafter.Run(), AIProgress.Run(), AIWork.Run(), DynamicAIAct.Run(), GoalCombat.Run(), GoalIdle.Run(), GoalNeeds.Run(), GoalSiege.Run(), GoalSleep.Run(), GoalSpot.Run(), GoalVisitorGuest.Run(), GoalWait.Run(), GoalWork.Run(), NoGoal.Run(), TaskCullLife.Run(), TaskMoveInstalled.Run(), TaskPoint.Run(), TaskWater.Run(), SetChild(), AIWork.SetDestination(), SetOwner(), SimulateZone(), Start(), AI_Trolley.Stop(), Tick(), GoalTask.TryAssignAreaTask(), GoalTask.TryAssignTask(), TryCancel(), AI_Goto.TryGoTo(), GoalCombat.TryMove(), TraitBaseSpellbook.TryProgress(), TaskManager.Designations.TryRemoveDesignation(), GoalCombat.TryThrow(), GoalCombat.TryUseAbility(), GoalAutoCombat.TryUseRanged(), GoalCombat.TryUseRanged(), GoalWork.TryWork(), and GoalWork.ValidateHobby().
parent
AIAct AIAct.parent
Definition at line 22 of file AIAct.cs.
restartCount
byte AIAct.restartCount
Definition at line 24 of file AIAct.cs.
Referenced by Reset(), and Restart().
status
Status AIAct.status
Definition at line 16 of file AIAct.cs.
Referenced by Cancel(), Task.Destroy(), UIQueue.OnAdd(), Restart(), AI_Fish.Run(), AIProgress.Run(), SetOwner(), Success(), Tick(), and WidgetDebug.UpdateText().
Property Documentation
actionIcon
virtual Sprite AIAct.actionIcon get
Definition at line 72 of file AIAct.cs.
CancelWhenDamaged
virtual bool AIAct.CancelWhenDamaged get
Definition at line 92 of file AIAct.cs.
Referenced by Card.DamageHP().
CancelWhenMoved
virtual bool AIAct.CancelWhenMoved get
Definition at line 94 of file AIAct.cs.
Referenced by Chara.MoveByForce().
Current
AIAct AIAct.Current get
Definition at line 100 of file AIAct.cs.
    {
        get
        {
            if (!IsChildRunning)
            {
                return this;
            }
            return child.Current;
        }
    }
Referenced by Chara._Move(), Card.DamageHP(), and Chara.MoveByForce().
CurrentProgress
virtual int AIAct.CurrentProgress get
Definition at line 88 of file AIAct.cs.
HasProgress
virtual bool AIAct.HasProgress get
Definition at line 120 of file AIAct.cs.
InformCancel
virtual bool AIAct.InformCancel get
Definition at line 96 of file AIAct.cs.
Referenced by TryCancel().
IsAct
override bool AIAct.IsAct get
Definition at line 112 of file AIAct.cs.
IsAutoTurn
virtual bool AIAct.IsAutoTurn get
Definition at line 76 of file AIAct.cs.
Referenced by UIAutoTurn._Update().
IsChildRunning
bool AIAct.IsChildRunning get
Definition at line 42 of file AIAct.cs.
    {
        get
        {
            if (child != null && child.status == Status.Running)
            {
                return child.owner != null;
            }
            return false;
        }
    }
Referenced by CanManualCancel(), GetCurrentActionText(), GetDestination(), GetProgress(), and Tick().
IsIdle
virtual bool AIAct.IsIdle get
Definition at line 78 of file AIAct.cs.
IsMoveAI
bool AIAct.IsMoveAI get
Definition at line 54 of file AIAct.cs.
    {
        get
        {
            if (!IsChildRunning)
            {
                return this is AI_Goto;
            }
            return child.IsMoveAI;
        }
    }
Referenced by Chara.TryPush().
IsNoGoal
virtual bool AIAct.IsNoGoal get
Definition at line 74 of file AIAct.cs.
Referenced by ActRanged.Perform(), WidgetSearch.RefreshList(), Chara.SetAI(), UIDragGridIngredients.Update(), and ButtonAbility.Use().
IsRunning
virtual bool AIAct.IsRunning get
Definition at line 30 of file AIAct.cs.
    {
        get
        {
            if (status == Status.Running)
            {
                return owner != null;
            }
            return false;
        }
    }
Referenced by AM_Adv._OnUpdateInput(), Card.CanReserve(), Card.DamageHP(), Chara.GetDestination(), InvOwnerDraglet.OnClick(), LayerDragGrid.OnKill(), HotItemHeld.OnRenderTile(), ActPlan.Item.Perform(), Chara.SetAI(), Chara.Tick(), Task.ToggleSuspend(), TryCancel(), AM_Adv.TryCancelInteraction(), and UIQueue.Update().
MaxProgress
virtual int AIAct.MaxProgress get
Definition at line 82 of file AIAct.cs.
Referenced by UIAutoTurn._Update().
MaxRestart
virtual int AIAct.MaxRestart get
Definition at line 66 of file AIAct.cs.
Referenced by Restart().
Name
virtual new string AIAct.Name get
Definition at line 68 of file AIAct.cs.
Referenced by TaskDesignation.GetTextOrbit(), TaskDrawWater.OnCreateProgress(), TaskPlow.OnCreateProgress(), TaskPourWater.OnCreateProgress(), InspectGroupBlock.OnSetActions(), InspectGroupObj.OnSetActions(), InspectGroupTask.OnSetActions(), AI_PassTime.Run(), and TaskPoint.WriteNote().
PushChara
virtual bool AIAct.PushChara get
Definition at line 80 of file AIAct.cs.
Referenced by Chara._Move().
RenderThing
virtual Thing AIAct.RenderThing get
Definition at line 98 of file AIAct.cs.
ShowCursor
virtual bool AIAct.ShowCursor get
Definition at line 90 of file AIAct.cs.
Referenced by BaseTileSelector.OnUpdate().
ShowPotential
override bool AIAct.ShowPotential get
Definition at line 114 of file AIAct.cs.
ShowProgress
virtual bool AIAct.ShowProgress get
Definition at line 84 of file AIAct.cs.
ShowRelativeAttribute
override bool AIAct.ShowRelativeAttribute get
Definition at line 118 of file AIAct.cs.
stateIcon
virtual MultiSprite AIAct.stateIcon get protected
Definition at line 70 of file AIAct.cs.
UsePotential
override bool AIAct.UsePotential get
Definition at line 116 of file AIAct.cs.
UseTurbo
virtual bool AIAct.UseTurbo get
Definition at line 86 of file AIAct.cs.
Referenced by ActPlan.Item.Perform(), and Start().
The documentation for this class was generated from the following file:
Elin/AIAct.cs