Elin Decompiled Documentation: Zone_Dungeon Class Reference
Zone_Dungeon Class Reference
Public Types
enum RailType { Mine , Factoy }
Public Types inherited from IInspect
enum NoteMode { Default , Recipe , Product , Info }
Public Member Functions
override string GetDungenID ()
override void OnGenerateMap ()
void PlaceRail (RailType railType=RailType.Mine)
Public Member Functions inherited from Zone
int Evalue (int ele)
int Evalue (string alias)
virtual string GetDungenID ()
virtual bool ShouldScaleImportedChara (Chara c)
virtual string GetNewZoneID (int level)
override string ToString ()
string TextLevel (int _lv)
override void OnCreate ()
override void OnAfterCreate ()
void Activate ()
void RefreshHat ()
void OnVisit ()
void Revive ()
virtual void OnRegenerate ()
virtual void OnActivate ()
virtual void OnBeforeDeactivate ()
virtual void OnDeactivate ()
virtual void OnBeforeSimulate ()
virtual void OnVisitNewMapOrRegenerate ()
virtual void OnAfterSimulate ()
virtual void OnAdvanceHour ()
void Simulate ()
Point GetSpawnPos (Chara c, ZoneTransition.EnterState destState=ZoneTransition.EnterState.Auto)
Point GetRandomVisitPos (Chara c)
void AddGlobalCharasOnActivate ()
void Deactivate ()
void OnKillGame ()
void UnloadMap ()
void ClaimZone (bool debug=false, Point pos=null)
void AbandonZone ()
bool CanDestroy ()
override void _OnBeforeSave ()
override void OnLoad ()
override void Destroy ()
void ClearZones (Zone current=null)
void OnChildNumChange (Card c)
ICardParent GetRoot ()
Zone GetTopZone ()
Card AddCardSplinkle (Card t, Point center, int radius=4)
Chara AddChara (string id, int x, int z)
Card AddThing (string id, int x, int z)
Card AddThing (string id, Point p)
Card AddCard (Card t, Point point)
Card AddCard (Card t)
Card AddCard (Card t, int x, int z)
void RemoveCard (Card t)
T GetRandomSpot< T > ()
bool TryAddThingInSpot< T > (Thing t, bool useContainer=true)
List< Thing > TryListThingsInSpot< T > (Func< Thing, bool > func=null)
bool TryAddThingInSharedContainer (Thing t, List< Thing > containers=null, bool add=true, bool msg=false, Chara chara=null, bool sharedOnly=true)
bool TryAddThing (Thing target, Point p, bool destroyIfFail=false)
Thing TryGetThingFromSharedContainer (Func< Thing, bool > func)
Thing TryGetRestock< T > (string idCat)
ZoneProfile GetProfile ()
void CreateBP ()
virtual void OnCreateBP ()
void Generate ()
void TrySpawnFollower ()
void SpawnAltar ()
virtual void OnGenerateMap ()
void TryGenerateOre ()
Chara TryGenerateEvolved (bool force=false, Point p=null)
void TryGenerateBigDaddy ()
void TryGenerateShrine ()
void ResetHostility ()
virtual void OnGenerateRooms (BaseMapGen gen)
Point GetSpawnPos (SpawnPosition type, int tries=100)
Chara SpawnMob (Point pos=null, SpawnSetting setting=null)
void RefreshElectricity ()
int GetElectricity (bool cost=false)
void SetBGM (List< int > ids, bool refresh=true, float fadeDuration=0f)
void SetBGM (int id=-1, bool refresh=true, float fadeDuration=0f)
void RefreshPlaylist ()
void ResetPlaylist ()
void RefreshBGM ()
Playlist CreatePlaylist (ref List< int > list, Playlist mold=null)
Chara FindChara (string id)
Chara FindChara (int uid)
int GetDeepestLv ()
int GetDeepestLv (ref int max)
List< Element > ListLandFeats ()
ZoneExportData Import (string path)
void Export (string path, PartialMap partial=null, bool usermap=false)
void ExportDialog (string dir=null)
void ImportDialog (string dir=null)
void Export ()
void WriteNote (UINote n, Action< UINote > onWriteNote=null, IInspect.NoteMode mode=IInspect.NoteMode.Default, Recipe recipe=null)
void OnInspect ()
int GetSortVal ()
Chara AddRandomVisitor (bool guest=false)
void OnSimulateHour (VirtualDate date)
void OnSimulateDay (VirtualDate date)
void OnSimulateMonth (VirtualDate date)
void RainWater ()
void GrowPlants (VirtualDate date)
Zone GetZoneAt (int _x, int _y)
bool IsCrime (Chara c, Act act)
void RefreshCriminal ()
void RefreshListCitizen ()
virtual void SetAlarm (bool enable)
void ModInfluence (int a)
void ModDevelopment (int a)
void UpdateQuests (bool force=false)
List< Chara > ListMinions (Chara c)
int CountMinions (Chara c)
int GetSoilCost ()
void SpawnLostItems ()
void ApplyBackerPet (bool draw)
FortuneRollData GetOrCreateFortuneRollData (bool refresh=true)
Public Member Functions inherited from Spatial
int GetInt (int id, int? defaultInt=null)
void AddInt (int id, int value)
void SetInt (int id, int value=0)
override string ToString ()
void Create (string _id, int _x, int _y, int _icon)
void Register ()
virtual void OnCreate ()
virtual void OnAfterCreate ()
virtual void SetMainFaction (Faction f)
Zone GetFirstZone ()
void OnBeforeSave ()
virtual void _OnBeforeSave ()
void _OnLoad ()
virtual void OnLoad ()
virtual void Destroy ()
void DeleteMapRecursive ()
virtual void AddChild (Spatial child)
void RemoveChild (Spatial child)
Zone FindDeepestZone ()
Zone FindZone (int lv)
Zone FindZone (string _id)
virtual bool CanKill ()
int Dist (Point p)
int Dist (Spatial s)
void MakeGameObject (GameObject parentGo)
ICardParent GetRoot ()
void RemoveCard (Card c)
void OnChildNumChange (Card c)
void WriteNote (UINote n, Action< UINote > onWriteNote=null, NoteMode mode=NoteMode.Default, Recipe recipe=null)
void OnInspect ()
Properties
override string IDGenerator [get]
override bool DisableRooms [get]
override bool UseFog [get]
override bool ShowDangerLv [get]
override float PrespawnRate [get]
override bool IsReturnLocation [get]
override int StartLV [get]
override bool BlockBorderExit [get]
override float EvolvedChance [get]
override float BigDaddyChance [get]
override float ShrineChance [get]
override bool IsSnowCovered [get]
override bool CountDeepestLevel [get]
override int BaseElectricity [get]
override ZoneTransition.EnterState RegionEnterState [get]
Properties inherited from Zone
Chara Boss [get, set]
override int ContentLv [get]
override int DangerLv [get]
virtual bool DisableRooms [get]
int HourSinceLastActive [get]
int MinsSinceLastActive [get]
virtual string pathExport [get]
BiomeProfile biome [get]
virtual string IdBiome [get]
virtual string IDGenerator [get]
virtual string TextWidgetDate [get]
MapGenerator Generator [get]
virtual string IdProfile [get]
virtual string IDPlayList [get]
virtual string IDPlaylistOverwrite [get]
virtual string IDHat [get]
virtual string IDBaseLandFeat [get]
virtual string idExport [get]
string pathTemp [get]
Region Region [get]
Zone ParentZone [get]
virtual ActionMode DefaultActionMode [get]
virtual bool BlockBorderExit [get]
virtual int ExpireDays [get]
virtual ZoneTransition.EnterState RegionEnterState [get]
virtual ZoneFeatureType FeatureType [get]
virtual string IDAmbience [get]
virtual string IDSceneTemplate [get]
virtual bool IsFestival [get]
virtual string IDSubset [get]
virtual bool IsTown [get]
virtual bool CanBeDeliverDestination [get]
virtual bool CountDeepestLevel [get]
virtual bool HasLaw [get]
virtual bool SetAlarmOnBreakLaw [get]
virtual bool MakeEnemiesNeutral [get]
virtual bool MakeTownProperties [get]
virtual bool AllowCriminal [get]
virtual bool AllowInvest [get]
virtual bool AllowNewZone [get]
virtual bool WillAutoSave [get]
virtual bool RegenerateOnEnter [get]
virtual bool IsSkyLevel [get]
virtual bool IsUnderwater [get]
virtual bool IsUserZone [get]
virtual bool CanDigUnderground [get]
virtual bool LockExit [get]
virtual bool CanUnlockExit [get]
virtual int MaxLv [get]
virtual int MinLv [get]
virtual bool AddPrefix [get]
virtual bool IsNefia [get]
virtual bool PetFollow [get]
virtual bool RestrictBuild [get]
virtual bool KeepAllyDistance [get]
virtual int MaxSpawn [get]
int MaxRespawn [get]
virtual float RuinChance [get]
virtual float OreChance [get]
virtual float BigDaddyChance [get]
virtual float EvolvedChance [get]
virtual float ShrineChance [get]
virtual float PrespawnRate [get]
virtual float RespawnRate [get]
bool ShowEnemyOnMinimap [get]
virtual int RespawnPerHour [get]
virtual float ChanceSpawnNeutral [get]
virtual bool GrowPlant [get]
virtual bool GrowWeed [get]
virtual bool IsExplorable [get]
virtual bool IsReturnLocation [get]
virtual bool ShouldMakeExit [get]
virtual bool ShouldRegenerate [get]
virtual bool ShouldAutoRevive [get]
virtual bool UseFog [get]
virtual bool RevealRoom [get]
virtual bool AlwaysLowblock [get]
virtual bool UseLight [get]
virtual int StartLV [get]
virtual ZoneScaleType ScaleType [get]
virtual bool HiddenInRegionMap [get]
virtual FlockController.SpawnType FlockType [get]
override string NameSuffix [get]
string NameWithLevel [get]
string TextDangerLv [get]
string TextDeepestLv [get]
bool CanEnterBuildMode [get]
bool CanEnterBuildModeAnywhere [get]
bool IsPCFaction [get]
bool IsPCFactionOrTent [get]
bool IsStartZone [get]
bool IsInstance [get]
bool IsLoaded [get]
virtual int BaseElectricity [get]
bool IsActiveZone [get]
bool CanInspect [get]
string InspectName [get]
Point InspectPoint [get]
Vector3 InspectPosition [get]
virtual int MaxSoil [get]
Properties inherited from Spatial
int _bits [get, set]
int uid [get, set]
int icon [get, set]
int x [get, set]
int y [get, set]
int lastActive [get, set]
int idPrefix [get, set]
int lv [get, set]
int visitCount [get, set]
int dateExpire [get, set]
int dateRevive [get, set]
int _dangerLv [get, set]
int dateRegenerate [get, set]
int influence [get, set]
int investment [get, set]
int development [get, set]
int electricity [get, set]
int dateHat [get, set]
int uidBoss [get, set]
int dateQuest [get, set]
int version [get, set]
bool isGenerated [get, set]
bool isShore [get, set]
bool isRandomSite [get, set]
bool isKnown [get, set]
bool isMapSaved [get, set]
bool isExternalZone [get, set]
bool isConquered [get, set]
bool isBeach [get, set]
bool isPeace [get, set]
bool isDeathLocation [get, set]
bool isAlarmSet [get, set]
Faction mainFaction [get, set]
SourceZone.Row source [get]
bool IsPlayerFaction [get]
bool IsClosed [get]
int mapX [get]
int mapY [get]
virtual int ContentLv [get]
virtual int DangerLv [get]
virtual int DangerLvFix [get]
virtual int DangerLvBoost [get]
virtual float VolumeSea [get]
virtual bool ShowDangerLv [get]
virtual bool CanSpawnAdv [get]
string pathSave [get]
virtual string Name [get]
string NameWithDangerLevel [get]
virtual string NameSuffix [get]
virtual bool IsRegion [get]
virtual bool CanFastTravel [get]
EloMap.TileInfo Tile [get]
virtual bool IsSnowZone [get]
virtual bool IsSnowCovered [get]
virtual Point RegionPos [get]
virtual bool isClaimable [get]
int Seed [get]
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Properties inherited from IInspect
bool CanInspect [get]
string InspectName [get]
Point InspectPoint [get]
Vector3 InspectPosition [get]
Additional Inherited Members
Static Public Member Functions inherited from Zone
static bool IsImportValid (string path)
Static Public Member Functions inherited from EClass
static int rndSeed (int a, int seed)
static int rnd (long a)
static int rnd (int a)
static int curve (int _a, int start, int step, int rate=75)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Public Attributes inherited from Zone
FactionBranch branch
HashSet< int > completedQuests = new HashSet<int>()
ZoneEventManager events = new ZoneEventManager()
ElementContainerZone elements = new ElementContainerZone()
MapBounds bounds
Dictionary< int, string > dictCitizen = new Dictionary<int, string>()
ZoneInstance instance
List< int > landFeats
Map map
MapSubset subset
ZoneBlueprint bp
int fileVariation
bool dirtyElectricity
bool isStarted
bool isSimulating
int tempDist
BiomeProfile _biome
Public Attributes inherited from Spatial
Spatial parent
string id
string idUser
string name
string idMainFaction
string idProfile
string idCurrentSubset
string idHat
int[] _ints = new int[30]
List< Spatial > children = new List<Spatial>()
List< Spatial > connections = new List<Spatial>()
Dictionary< int, int > mapInt = new Dictionary<int, int>()
bool destryoed
bool isImported
BitArray32 bits
Static Public Attributes inherited from Zone
static bool forceRegenerate
static string forceSubset
static CardRow sourceHat
static int okaerinko = 0
static bool ignoreSpawnAnime
static List< Thing > Suckers = new List<Thing>()
Static Public Attributes inherited from EClass
static Core core
Protected Member Functions inherited from Spatial
Zone _FindZone (string _id)
Protected Attributes inherited from Spatial
Point _regionPos = new Point()
Detailed Description
Definition at line 5 of file Zone_Dungeon.cs.
Member Enumeration Documentation
RailType
enum Zone_Dungeon.RailType
Enumerator
Mine
Factoy
Definition at line 7 of file Zone_Dungeon.cs.
    {
        Mine,
        Factoy
    }
Member Function Documentation
GetDungenID()
override string Zone_Dungeon.GetDungenID () inline virtual
Reimplemented from Zone.
Reimplemented in Zone_DungeonFairy, Zone_DungeonMino, Zone_Gathering, Zone_RandomDungeonNature, Zone_UnderseaTemple, and Zone_VernisMine.
Definition at line 83 of file Zone_Dungeon.cs.
    {
        if (EClass.rnd(2) == 0)
        {
            return "DungeonRuins";
        }
        if (EClass.rnd(4) == 0)
        {
            return "Cavern";
        }
        if (EClass.rnd(8) == 0)
        {
            return "RoundRooms";
        }
        return "Dungeon";
    }
References EClass.rnd().
OnGenerateMap()
override void Zone_Dungeon.OnGenerateMap () inline virtual
Reimplemented from Zone.
Reimplemented in Zone_DungeonFairy, Zone_DungeonMino, Zone_DungeonPuppy, Zone_RandomDungeon, Zone_RandomDungeonFactory, Zone_UnderseaTemple, Zone_VernisMine, and Zone_Void.
Definition at line 100 of file Zone_Dungeon.cs.
    {
        if (idExport.IsEmpty())
        {
            TryGenerateOre();
            TryGenerateBigDaddy();
            TryGenerateEvolved();
            TryGenerateShrine();
        }
    }
References Zone.idExport, Zone.TryGenerateBigDaddy(), Zone.TryGenerateEvolved(), Zone.TryGenerateOre(), and Zone.TryGenerateShrine().
PlaceRail()
void Zone_Dungeon.PlaceRail (RailType railType = RailType::Mine) inline
Definition at line 111 of file Zone_Dungeon.cs.
    {
        int idRail = 31;
        string idTrolley = "390";
        bool placeStopper = true;
        int num = 8;
        if (railType == RailType.Factoy)
        {
            idRail = 110;
            placeStopper = false;
            num = EClass.rnd(4) + 1;
        }
        PathManager.Instance._pathfinder.PunishChangeDirection = true;
        PathManager.Instance._pathfinder.Diagonals = false;
        TraitStairsDown traitStairsDown = EClass._map.FindThing<TraitStairsDown>();
        TraitStairsUp traitStairsUp = EClass._map.FindThing<TraitStairsUp>();
        if (traitStairsDown != null && traitStairsUp != null)
        {
            TryPlaceRail(traitStairsDown.owner.pos, traitStairsUp.owner.pos);
        }
        int num2 = 0;
        for (int i = 0; i < 200; i++)
        {
            if (TryPlaceRail(EClass._map.bounds.GetRandomSurface(), EClass._map.bounds.GetRandomSurface()))
            {
                num2++;
                if (num2 > num)
                {
                    break;
                }
            }
        }
        PathManager.Instance._pathfinder.Diagonals = true;
        bool TryPlaceRail(Point p1, Point p2)
        {
            if (p1.Distance(p2) < 20)
            {
                return false;
            }
            PathProgress pathProgress = PathManager.Instance.RequestPathImmediate(p1, p2, EClass.pc);
            if (!pathProgress.HasPath)
            {
                return false;
            }
            Point point = new Point();
            Point point2 = new Point();
            bool flag = false;
            int num3 = 0;
            foreach (PathFinderNode node in pathProgress.nodes)
            {
                Point shared = Point.GetShared(node.X, node.Z);
                for (int j = -1; j < 2; j++)
                {
                    for (int k = -1; k < 2; k++)
                    {
                        point2.Set(shared.x + k, shared.z + j);
                        if ((Mathf.Abs(k) != 1 || Mathf.Abs(j) != 1) && point2.IsValid && point2.sourceObj.id == 31 && !point2.Equals(point))
{
                            flag = true;
                            if (num3 != 0)
{
                                break;
                            }
                            return false;
                        }
                    }
                }
                if (shared.sourceObj.id == idRail)
                {
                    break;
                }
                shared.SetBlock();
                shared.SetObj(idRail);
                shared.Things.ForeachReverse(delegate(Thing t)
                {
                    if (t.trait.CanBeDestroyed)
                    {
                        t.Destroy();
                    }
                });
                if (flag)
                {
                    break;
                }
                num3++;
                point.Set(shared);
            }
            if (!flag && placeStopper)
            {
                Point shared2 = Point.GetShared(pathProgress.nodes.LastItem().X, pathProgress.nodes.LastItem().Z);
                Cell cell = shared2.cell;
                int dir = ((cell.Front.obj != 31) ? ((cell.Right.obj == 31) ? 1 : ((cell.Back.obj == 31) ? 2 : 3)) : 0);
                if (!shared2.HasThing)
                {
                    EClass._zone.AddCard(ThingGen.Create("1208"), shared2).Install().dir = dir;
                }
            }
            if (num3 > 2)
            {
                Point shared3 = Point.GetShared(pathProgress.nodes.First().X, pathProgress.nodes.First().Z);
                if (!shared3.HasThing)
                {
                    EClass._zone.AddCard(ThingGen.Create(idTrolley), shared3).Install();
                }
            }
            return true;
        }
    }
References EClass._map, EClass._zone, Zone.AddCard(), Map.bounds, Trait.CanBeDestroyed, Point.cell, ThingGen.Create(), Card.dir, Point.Distance(), Map.FindThing(), MapBounds.GetRandomSurface(), Point.GetShared(), PathProgress.HasPath, Point.HasThing, PathManager.Instance, Cell.obj, Trait.owner, EClass.pc, Card.pos, PathManager.RequestPathImmediate(), Cell.Right, EClass.rnd(), Point.Set(), Point.SetBlock(), Point.SetObj(), Point.sourceObj, Point.Things, Card.trait, Algorithms.PathFinderNode.X, Point.x, Algorithms.PathFinderNode.Z, and Point.z.
Referenced by Zone_CurryRuinDungeon.OnGenerateMap(), Zone_RandomDungeonFactory.OnGenerateMap(), and Zone_VernisMine.OnGenerateMap().
Property Documentation
BaseElectricity
override int Zone_Dungeon.BaseElectricity get
Definition at line 79 of file Zone_Dungeon.cs.
BigDaddyChance
override float Zone_Dungeon.BigDaddyChance get
Definition at line 51 of file Zone_Dungeon.cs.
    {
        get
        {
            if (!EClass.debug.test)
            {
                return 0.08f;
            }
            return 1f;
        }
    }
BlockBorderExit
override bool Zone_Dungeon.BlockBorderExit get
Definition at line 37 of file Zone_Dungeon.cs.
CountDeepestLevel
override bool Zone_Dungeon.CountDeepestLevel get
Definition at line 77 of file Zone_Dungeon.cs.
DisableRooms
override bool Zone_Dungeon.DisableRooms get
Definition at line 15 of file Zone_Dungeon.cs.
EvolvedChance
override float Zone_Dungeon.EvolvedChance get
Definition at line 39 of file Zone_Dungeon.cs.
    {
        get
        {
            if (!EClass.debug.test)
            {
                return 0.08f;
            }
            return 1f;
        }
    }
IDGenerator
override string Zone_Dungeon.IDGenerator get
Definition at line 13 of file Zone_Dungeon.cs.
IsReturnLocation
override bool Zone_Dungeon.IsReturnLocation get
Definition at line 33 of file Zone_Dungeon.cs.
IsSnowCovered
override bool Zone_Dungeon.IsSnowCovered get
Definition at line 75 of file Zone_Dungeon.cs.
PrespawnRate
override float Zone_Dungeon.PrespawnRate get
Definition at line 21 of file Zone_Dungeon.cs.
    {
        get
        {
            if (!idExport.IsEmpty())
            {
                return 0f;
            }
            return 1f;
        }
    }
RegionEnterState
override ZoneTransition.EnterState Zone_Dungeon.RegionEnterState get
Definition at line 81 of file Zone_Dungeon.cs.
ShowDangerLv
override bool Zone_Dungeon.ShowDangerLv get
Definition at line 19 of file Zone_Dungeon.cs.
ShrineChance
override float Zone_Dungeon.ShrineChance get
Definition at line 63 of file Zone_Dungeon.cs.
    {
        get
        {
            if (!EClass.debug.test)
            {
                return 0.35f;
            }
            return 1f;
        }
    }
StartLV
override int Zone_Dungeon.StartLV get
Definition at line 35 of file Zone_Dungeon.cs.
UseFog
override bool Zone_Dungeon.UseFog get
Definition at line 17 of file Zone_Dungeon.cs.
The documentation for this class was generated from the following file:
Elin/Zone_Dungeon.cs