Elin Decompiled Documentation: RenderCamUpscaler Class Reference
RenderCamUpscaler Class Reference
Public Member Functions
void SetEnable (bool enable)
void OnChangeResolution ()
void CreateTex (int w, int h)
void OnChangeResolution ()
Public Attributes
RenderTexture renderTex
RawImage image
bool active
Static Public Attributes
static RenderCamUpscaler Instance
Private Member Functions
void Awake ()
Detailed Description
Definition at line 4 of file RenderCamUpscaler.cs.
Member Function Documentation
Awake()
void RenderCamUpscaler.Awake () inline private
Definition at line 14 of file RenderCamUpscaler.cs.
    {
        Instance = this;
    }
References Instance.
CreateTex()
void RenderCamUpscaler.CreateTex (int w, int h) inline
Definition at line 49 of file RenderCamUpscaler.cs.
    {
        if ((bool)renderTex)
        {
            renderTex.Release();
        }
        renderTex = new RenderTexture(w, h, 32);
        image.texture = renderTex;
        renderTex.filterMode = FilterMode.Point;
        Camera.main.targetTexture = renderTex;
    }
References renderTex.
Referenced by OnChangeResolution().
OnChangeResolution()
void RenderCamUpscaler.OnChangeResolution () inline
Implements IChangeResolution.
Definition at line 35 of file RenderCamUpscaler.cs.
    {
        if (active)
        {
            int num = Screen.width / 2;
            int num2 = Screen.height / 2;
            if (!renderTex || num != renderTex.width || num2 != renderTex.height)
            {
                CreateTex(num, num2);
            }
            image.Rect().sizeDelta = new Vector2(num * 2, num2 * 2);
        }
    }
References active, CreateTex(), image, and renderTex.
Referenced by SetEnable().
SetEnable()
void RenderCamUpscaler.SetEnable (bool enable) inline
Definition at line 19 of file RenderCamUpscaler.cs.
    {
        bool flag2 = (image.enabled = enable);
        active = flag2;
        if (active)
        {
            OnChangeResolution();
            return;
        }
        if ((bool)renderTex)
        {
            renderTex.Release();
        }
        Camera.main.targetTexture = null;
    }
References active, OnChangeResolution(), and renderTex.
Member Data Documentation
active
bool RenderCamUpscaler.active
Definition at line 12 of file RenderCamUpscaler.cs.
Referenced by OnChangeResolution(), and SetEnable().
image
RawImage RenderCamUpscaler.image
Definition at line 10 of file RenderCamUpscaler.cs.
Referenced by OnChangeResolution().
Instance
RenderCamUpscaler RenderCamUpscaler.Instance static
Definition at line 6 of file RenderCamUpscaler.cs.
Referenced by Awake().
renderTex
RenderTexture RenderCamUpscaler.renderTex
Definition at line 8 of file RenderCamUpscaler.cs.
Referenced by CreateTex(), OnChangeResolution(), and SetEnable().
The documentation for this class was generated from the following file:
Elin/Plugins.UI/RenderCamUpscaler.cs