Elin Decompiled Documentation: UIScreenshot Class Reference
UIScreenshot Class Reference
Public Member Functions
void Activate (PartialMap partial, DirectoryInfo dir, Action< PartialMap > onSave=null, bool isUpdate=false)
void Deactivate ()
Static Public Member Functions
static UIScreenshot Create ()
static void SavePreview (string path, string name, Action onSave)
Static Public Member Functions inherited from EMono
static int rnd (int a)
Public Attributes
Image imageFrame
InputField inputName
UIButton buttonSave
UIButton buttonCancel
bool isDeactivating
Static Public Attributes
static UIScreenshot Instance
Static Public Attributes inherited from EMono
static Core core
Private Member Functions
void Awake ()
void Update ()
Additional Inherited Members
Properties inherited from EMono
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SoundManager Sound [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static CoreDebug debug [get]
Detailed Description
Definition at line 7 of file UIScreenshot.cs.
Member Function Documentation
Activate()
void UIScreenshot.Activate (PartialMap partial, DirectoryInfo dir, Action< PartialMap > onSave = null, bool isUpdate = false) inline
Definition at line 20 of file UIScreenshot.cs.
    {
        UIScreenshot.<>c__DisplayClass8_0 CS$<>8__locals1 = new UIScreenshot.<>c__DisplayClass8_0();
        CS$<>8__locals1.dir = dir;
        CS$<>8__locals1.<>4__this = this;
        CS$<>8__locals1.isUpdate = isUpdate;
        CS$<>8__locals1.partial = partial;
        CS$<>8__locals1.onSave = onSave;
        this.inputName.text = (MapPiece.IsEditor ? CS$<>8__locals1.<Activate>g__GetUniqueName|0("") : EMono._zone.Name);
        if (CS$<>8__locals1.isUpdate)
        {
            this.inputName.text = (MapPiece.IsEditor ? CS$<>8__locals1.partial.ID : CS$<>8__locals1.partial.name);
        }
        this.buttonSave.SetOnClick(delegate
        {
            CS$<>8__locals1.<>4__this.isDeactivating = true;
            SE.Play("camera");
            CS$<>8__locals1.<>4__this.GetComponent<CanvasGroup>().alpha = 0f;
            string text = CS$<>8__locals1.dir.FullName + "/" + (MapPiece.IsEditor ? CS$<>8__locals1.<>4__this.inputName.text.IsEmpty("new") : base.<Activate>g__GetUniqueName|0("user")) + ".mp";
            if (CS$<>8__locals1.isUpdate)
            {
                if (MapPiece.IsEditor)
                {
                    PartialMap.Delete(CS$<>8__locals1.partial.path);
                }
                else
                {
                    text = CS$<>8__locals1.partial.path;
                }
            }
            CS$<>8__locals1.partial.name = CS$<>8__locals1.<>4__this.inputName.text.IsEmpty(EMono._zone.Name);
            CS$<>8__locals1.partial.path = text;
            File.Copy(PartialMap.PathTemp, text, true);
            string path = text;
            string name = CS$<>8__locals1.partial.name;
            Action onSave2;
            if ((onSave2 = CS$<>8__locals1.<>9__2) == null)
            {
                onSave2 = (CS$<>8__locals1.<>9__2 = delegate()
                {
                    if (PartialMapMenu.Instance)
                    {
                        PartialMapMenu.Instance.Refresh();
                    }
                    CS$<>8__locals1.<>4__this.Deactivate();
                    if (CS$<>8__locals1.onSave != null)
                    {
                        CS$<>8__locals1.onSave(CS$<>8__locals1.partial);
                    }
                });
            }
            UIScreenshot.SavePreview(path, name, onSave2);
        });
    }
References EMono._zone, Activate(), buttonSave, PartialMap.Delete(), PartialMapMenu.Instance, MapPiece.IsEditor, Spatial.Name, PartialMap.PathTemp, PartialMapMenu.Refresh(), SavePreview(), and text.
Referenced by Activate(), AM_Copy.OnAfterProcessTiles(), and AM_Copy.RefreshMenu().
Awake()
void UIScreenshot.Awake () inline private
Definition at line 14 of file UIScreenshot.cs.
    {
        UIScreenshot.Instance = this;
        EMono.ui.Hide(0f);
    }
References EMono.ui.
Create()
static UIScreenshot UIScreenshot.Create () inline static
Definition at line 9 of file UIScreenshot.cs.
    {
        return Util.Instantiate<UIScreenshot>("UI/Util/UIScreenshot", EMono.ui);
    }
References EMono.ui.
Referenced by AM_Copy.OnAfterProcessTiles(), and AM_Copy.RefreshMenu().
Deactivate()
void UIScreenshot.Deactivate () inline
Definition at line 136 of file UIScreenshot.cs.
    {
        UnityEngine.Object.Destroy(base.gameObject);
        EMono.ui.Show(0f);
        EInput.Consume(false, 1);
    }
References EMono.ui.
Referenced by Update().
SavePreview()
static void UIScreenshot.SavePreview (string path, string name, Action onSave) inline static
Definition at line 88 of file UIScreenshot.cs.
    {
        Action <>9__1;
        EMono.core.actionsNextFrame.Add(delegate
        {
            List<Action> actionsNextFrame = EMono.core.actionsNextFrame;
            Action item;
            if ((item = <>9__1) == null)
            {
                item = (<>9__1 = delegate()
                {
                    Texture2D texture2D = ScreenCapture.CaptureScreenshotAsTexture();
                    texture2D.filterMode = FilterMode.Point;
                    int num = 300;
                    int num2 = 200;
                    float num3 = (float)num / (float)Screen.width;
                    float num4 = (float)num2 / (float)Screen.height;
                    Vector2 scale = new Vector2(num3, num4);
                    Vector2 offset = new Vector2((1f - num3) * 0.5f, (1f - num4) * 0.5f);
                    RenderTexture renderTexture = new RenderTexture(num, num2, 0);
                    renderTexture.filterMode = FilterMode.Point;
                    renderTexture.Create();
                    RenderTexture active = RenderTexture.active;
                    RenderTexture.active = renderTexture;
                    Graphics.Blit(texture2D, renderTexture, scale, offset);
                    Texture2D texture2D2 = new Texture2D(num, num2, texture2D.format, false);
                    texture2D2.filterMode = FilterMode.Point;
                    texture2D2.ReadPixels(new Rect(0f, 0f, (float)num, (float)num2), 0, 0);
                    texture2D2.Apply();
                    RenderTexture.active = active;
                    renderTexture.Release();
                    File.WriteAllBytes(path.GetFullFileNameWithoutExtension() + ".jpg", texture2D2.EncodeToJPG());
                    File.WriteAllText(path.GetFullFileNameWithoutExtension() + ".txt", name);
                    UnityEngine.Object.Destroy(texture2D2);
                    UnityEngine.Object.Destroy(texture2D);
                    UnityEngine.Object.Destroy(renderTexture);
                    Action onSave2 = onSave;
                    if (onSave2 == null)
                    {
                        return;
                    }
                    onSave2();
                });
            }
            actionsNextFrame.Add(item);
        });
    }
References EMono.core.
Referenced by Activate().
Update()
void UIScreenshot.Update () inline private
Definition at line 75 of file UIScreenshot.cs.
    {
        if (this.isDeactivating)
        {
            EInput.Consume(false, 1);
            return;
        }
        if (EInput.rightMouse.clicked || Input.GetKeyDown(KeyCode.Escape))
        {
            this.Deactivate();
        }
    }
References Deactivate(), and isDeactivating.
Member Data Documentation
buttonCancel
UIButton UIScreenshot.buttonCancel
Definition at line 151 of file UIScreenshot.cs.
buttonSave
UIButton UIScreenshot.buttonSave
Definition at line 149 of file UIScreenshot.cs.
Referenced by Activate().
imageFrame
Image UIScreenshot.imageFrame
Definition at line 145 of file UIScreenshot.cs.
inputName
InputField UIScreenshot.inputName
Definition at line 147 of file UIScreenshot.cs.
Instance
UIScreenshot UIScreenshot.Instance static
Definition at line 143 of file UIScreenshot.cs.
Referenced by AM_Copy.OnCancel(), and AM_Copy.OnRenderTile().
isDeactivating
bool UIScreenshot.isDeactivating
Definition at line 153 of file UIScreenshot.cs.
Referenced by Update().
The documentation for this class was generated from the following file:
Elin/UIScreenshot.cs