Elin Decompiled Documentation: ZoneInspector.FillUtil Class Reference
ZoneInspector.FillUtil Class Reference
Public Member Functions
void FlattenHeight ()
void FillFloor ()
void FillBlock ()
void ClearBlock ()
void ClearObj ()
void ClearBridge ()
Public Attributes
int flatHeight
int fillFloor = 5
int fillBlock = 1
bool randomFillDir
Detailed Description
Definition at line 5 of file ZoneInspector.cs.
Member Function Documentation
ClearBlock()
void ZoneInspector.FillUtil.ClearBlock () inline
Definition at line 42 of file ZoneInspector.cs.
        {
            EMono._map.ForeachCell(delegate(Cell c)
            {
                EMono._map.SetBlock(c.x, c.z);
            });
        }
References EMono._map, Map.ForeachCell(), Map.SetBlock(), Cell.x, and Cell.z.
ClearBridge()
void ZoneInspector.FillUtil.ClearBridge () inline
Definition at line 58 of file ZoneInspector.cs.
        {
            EMono._map.ForeachCell(delegate(Cell c)
            {
                EMono._map.SetObj(c.x, c.z);
            });
        }
References EMono._map, Map.ForeachCell(), Map.SetObj(), Cell.x, and Cell.z.
ClearObj()
void ZoneInspector.FillUtil.ClearObj () inline
Definition at line 50 of file ZoneInspector.cs.
        {
            EMono._map.ForeachCell(delegate(Cell c)
            {
                EMono._map.SetObj(c.x, c.z);
            });
        }
References EMono._map, Map.ForeachCell(), Map.SetObj(), Cell.x, and Cell.z.
FillBlock()
void ZoneInspector.FillUtil.FillBlock () inline
Definition at line 33 of file ZoneInspector.cs.
        {
            EMono._map.ForeachCell(delegate(Cell c)
            {
                int dir = (randomFillDir ? EMono.rnd(4) : 0);
                EMono._map.SetBlock(c.x, c.z, EMono.sources.blocks.rows[fillBlock].DefaultMaterial.id, fillBlock, dir);
            });
        }
References EMono._map, SourceManager.blocks, ZoneInspector.FillUtil.fillBlock, Map.ForeachCell(), ZoneInspector.FillUtil.randomFillDir, EMono.rnd(), Map.SetBlock(), EMono.sources, Cell.x, and Cell.z.
FillFloor()
void ZoneInspector.FillUtil.FillFloor () inline
Definition at line 24 of file ZoneInspector.cs.
        {
            EMono._map.ForeachCell(delegate(Cell c)
            {
                int dir = (randomFillDir ? EMono.rnd(4) : 0);
                EMono._map.SetFloor(c.x, c.z, EMono.sources.floors.rows[fillFloor].DefaultMaterial.id, fillFloor, dir);
            });
        }
References EMono._map, ZoneInspector.FillUtil.fillFloor, SourceManager.floors, Map.ForeachCell(), ZoneInspector.FillUtil.randomFillDir, EMono.rnd(), Map.SetFloor(), EMono.sources, Cell.x, and Cell.z.
FlattenHeight()
void ZoneInspector.FillUtil.FlattenHeight () inline
Definition at line 15 of file ZoneInspector.cs.
        {
            EMono._map.ForeachCell(delegate(Cell c)
            {
                c.height = (byte)flatHeight;
            });
            EMono._map.RefreshAllTiles();
        }
References EMono._map, ZoneInspector.FillUtil.flatHeight, Map.ForeachCell(), and Map.RefreshAllTiles().
Member Data Documentation
fillBlock
int ZoneInspector.FillUtil.fillBlock = 1
Definition at line 11 of file ZoneInspector.cs.
Referenced by ZoneInspector.FillUtil.FillBlock().
fillFloor
int ZoneInspector.FillUtil.fillFloor = 5
Definition at line 9 of file ZoneInspector.cs.
Referenced by ZoneInspector.FillUtil.FillFloor().
flatHeight
int ZoneInspector.FillUtil.flatHeight
Definition at line 7 of file ZoneInspector.cs.
Referenced by ZoneInspector.FillUtil.FlattenHeight().
randomFillDir
bool ZoneInspector.FillUtil.randomFillDir
Definition at line 13 of file ZoneInspector.cs.
Referenced by ZoneInspector.FillUtil.FillBlock(), and ZoneInspector.FillUtil.FillFloor().
The documentation for this class was generated from the following file:
Elin/ZoneInspector.cs