Elin Decompiled Documentation: POIMap Class Reference
POIMap Class Reference
Classes
class Cell
Public Member Functions
void Init (int _mapSize, int _cellSize)
void Reset ()
Point GetCenterOfEmptyCell (int tries=100)
POIMap.Cell GetCenterCell (int radius=1)
POIMap.Cell GetEmptyCell ()
void ForeachCenterOfEmptyCell (Action< Point > action)
void OccyupyPOI (Point p, int radius=0)
void OccyupyPOI (int _x, int _z, int radius)
Public Attributes
POIMap.Cell[,] cells
Static Public Attributes
static int cellSize
static int mapSize
Properties
int length [get]
Detailed Description
Definition at line 3 of file POIMap.cs.
Member Function Documentation
ForeachCenterOfEmptyCell()
void POIMap.ForeachCenterOfEmptyCell (Action< Point > action) inline
Definition at line 71 of file POIMap.cs.
    {
        for (int i = 1; i < this.length - 2; i++)
        {
            for (int j = 1; j < this.length - 2; j++)
            {
                if (!this.cells[i, j].occupied)
                {
                    action(this.cells[i, j].GetCenter());
                }
            }
        }
    }
References cells.
GetCenterCell()
POIMap.Cell POIMap.GetCenterCell (int radius = 1) inline
Definition at line 51 of file POIMap.cs.
    {
        return this.cells[this.length / 2 - radius + EClass.rnd(radius * 2), this.length / 2 - radius + EClass.rnd(radius * 2)];
    }
References cells, and EClass.rnd().
Referenced by Zone.SpawnAltar().
GetCenterOfEmptyCell()
Point POIMap.GetCenterOfEmptyCell (int tries = 100) inline
Definition at line 36 of file POIMap.cs.
    {
        new Point();
        for (int i = 0; i < tries; i++)
        {
            int num = EClass.rnd(this.length - 2) + 1;
            int num2 = EClass.rnd(this.length - 2) + 1;
            if (!this.cells[num, num2].occupied)
            {
                return this.cells[num, num2].GetCenter();
            }
        }
        return Point.Invalid;
    }
References cells, Point.Invalid, length, and EClass.rnd().
GetEmptyCell()
POIMap.Cell POIMap.GetEmptyCell () inline
Definition at line 56 of file POIMap.cs.
    {
        new Point();
        for (int i = 0; i < 100; i++)
        {
            int num = EClass.rnd(this.length - 2) + 1;
            int num2 = EClass.rnd(this.length - 2) + 1;
            if (this.cells[num, num2] == null)
            {
                return this.cells[num, num2];
            }
        }
        return null;
    }
References cells, length, and EClass.rnd().
Init()
void POIMap.Init (int _mapSize, int _cellSize) inline
Definition at line 13 of file POIMap.cs.
    {
        POIMap.cellSize = _cellSize;
        POIMap.mapSize = _mapSize;
        this.cells = new POIMap.Cell[this.length, this.length];
        this.Reset();
    }
References length, and Reset().
Referenced by BaseMapGen.SetSize().
OccyupyPOI() [1/2]
void POIMap.OccyupyPOI (int _x, int _z, int radius) inline
Definition at line 90 of file POIMap.cs.
    {
        int num = _x / POIMap.cellSize;
        int num2 = _z / POIMap.cellSize;
        this.cells[num, num2].occupied = true;
        if (radius > 0)
        {
            for (int i = num - radius; i < num + radius + 1; i++)
            {
                if (i >= 0 && i < this.length)
                {
                    for (int j = num2 - radius; j < num2 + radius + 1; j++)
                    {
                        if (j >= 0 && j < this.length)
{
                            this.cells[i, j].occupied = true;
                        }
                    }
                }
            }
        }
    }
References cells, cellSize, and length.
OccyupyPOI() [2/2]
void POIMap.OccyupyPOI (Point p, int radius = 0) inline
Definition at line 85 of file POIMap.cs.
    {
        this.OccyupyPOI(p.x, p.z, radius);
    }
References OccyupyPOI(), Point.x, and Point.z.
Referenced by OccyupyPOI(), and Zone.SpawnAltar().
Reset()
void POIMap.Reset () inline
Definition at line 21 of file POIMap.cs.
    {
        for (int i = 0; i < this.length; i++)
        {
            for (int j = 0; j < this.length; j++)
            {
                this.cells[i, j] = new POIMap.Cell
                {
                    x = i,
                    z = j
                };
            }
        }
    }
References cells, and length.
Referenced by Init(), MapGen.OnGenerateTerrain(), MapGenDungen.OnGenerateTerrain(), and MapGenRegion.OnGenerateTerrain().
Member Data Documentation
cells
POIMap.Cell [,] POIMap.cells
Definition at line 117 of file POIMap.cs.
Referenced by ForeachCenterOfEmptyCell(), GetCenterCell(), GetCenterOfEmptyCell(), GetEmptyCell(), OccyupyPOI(), and Reset().
cellSize
int POIMap.cellSize static
Definition at line 113 of file POIMap.cs.
Referenced by POIMap.Cell.GetCenter(), and OccyupyPOI().
mapSize
int POIMap.mapSize static
Definition at line 115 of file POIMap.cs.
Referenced by BaseMapGen.SetSize().
Property Documentation
length
int POIMap.length get
Definition at line 5 of file POIMap.cs.
    {
        get
        {
            return POIMap.mapSize / POIMap.cellSize + 1;
        }
    }
Referenced by GetCenterOfEmptyCell(), GetEmptyCell(), Init(), OccyupyPOI(), and Reset().
The documentation for this class was generated from the following file:
Elin/POIMap.cs