Elin Decompiled Documentation: FortuneRollData Class Reference
FortuneRollData Class Reference
Classes
class Prize
Public Member Functions
void Refresh ()
void RefreshPrize ()
List< List< string > > GetPrizeList ()
void GetPrize (int grade, int seed)
void WriteNote (UINote n)
Public Attributes
List< Prize > prizes = new List<Prize>()
int count
int seed
int dateNextRefresh
Static Public Attributes
static string[] mats = new string[4] { "plastic", "water", "hide_dragon", "gold" }
static int[] chances = new int[4] { 1, 8, 25, 60 }
Static Public Attributes inherited from EClass
static Core core
Additional Inherited Members
Static Public Member Functions inherited from EClass
static int rndSeed (int a, int seed)
static int rnd (long a)
static int rnd (int a)
static int curve (int _a, int start, int step, int rate=75)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Detailed Description
Definition at line 6 of file FortuneRollData.cs.
Member Function Documentation
GetPrize()
void FortuneRollData.GetPrize (int grade, int seed) inline
Definition at line 208 of file FortuneRollData.cs.
    {
        Rand.SetSeed(seed);
        Prize prize = null;
        List<Prize> list = prizes.Where((Prize p) => p.grade == grade && !p.claimed).ToList();
        if (list.Count > 0)
        {
            prize = list.RandomItem();
        }
        Card card = null;
        if (prize != null)
        {
            if (prize.id == "sister")
            {
                card = CharaGen.Create("sister");
            }
            else
            {
                card = ThingGen.Create(prize.id).SetNum(prize.GetNum());
                switch (card.id)
                {
                case "rp_food":
                case "rp_block":
                    card.SetLv(10);
                    break;
                case "goods_coin":
                    EClass.player.luckycoin++;
                    if (EClass.player.luckycoin >= 10)
                    {
                        prize.claimed = true;
                    }
                    break;
                case "mathammer":
                    card.ChangeMaterial(prize.idRef);
                    card.noSell = true;
                    break;
                case "panty":
                    card.c_idRefCard = prize.idRef;
                    card.rarity = Rarity.Legendary;
                    break;
                }
            }
            if (grade != 3)
            {
                prize.claimed = true;
            }
        }
        else
        {
            card = ThingGen.Create(GetPrizeList()[0].RandomItem());
        }
        if (card.isChara)
        {
            EClass._zone.AddCard(card, EClass.pc.pos.GetNearestPoint(allowBlock: false, allowChara: false) ?? EClass.pc.pos);
            card.Chara.MakeMinion(EClass.pc);
        }
        else
        {
            EClass.pc.Pick(card.Thing);
        }
        Rand.SetSeed();
    }
References EClass._zone, Zone.AddCard(), card, FortuneRollData.Prize.claimed, ThingGen.Create(), CharaGen.Create(), Point.GetNearestPoint(), FortuneRollData.Prize.GetNum(), GetPrizeList(), FortuneRollData.Prize.grade, FortuneRollData.Prize.id, FortuneRollData.Prize.idRef, Player.luckycoin, EClass.pc, Chara.Pick(), EClass.player, Card.pos, prizes, seed, Card.SetNum(), and Rand.SetSeed().
Referenced by TraitCrafter.Craft().
GetPrizeList()
List< List< string > > FortuneRollData.GetPrizeList () inline
Definition at line 173 of file FortuneRollData.cs.
    {
        List<List<string>> list = new List<List<string>>
        {
            new List<string> { "scrubber", "tissue", "plat" },
            new List<string>
            {
                "microchip", "1089", "150", "855", "medal", "water", "goods_charm", "electronicsS", "electronics", "plat",
                "plat", "ration", "backpack2", "sister", "rp_food", "rp_block", "157", "sleepingbag"
            },
            new List<string>
            {
                "computer", "834", "1090", "goods_figure", "goods_canvas", "mb_1", "mb_2", "mb_3", "mb_4", "mb_5",
                "1174", "1085", "toilet", "714", "nobility", "plat", "1165", "mathammer", "medal", "bbq",
                "panty", "beehive", "ticket_resident", "lovepotion", "crystal_sun", "goods_crim"
            },
            new List<string>
            {
                (EClass.player.luckycoin < 10) ? "goods_coin" : "plat",
                "plat",
                "1165",
                "boat3",
                "medal"
            }
        };
        if (EClass.pc.faction.IsGlobalPolicyActive(2712))
        {
            for (int i = 0; i < (EClass.debug.enable ? 50 : 5); i++)
            {
                list[2].Add("panty");
            }
        }
        return list;
    }
References Chara.faction, Faction.IsGlobalPolicyActive(), and EClass.pc.
Referenced by GetPrize(), and RefreshPrize().
Refresh()
void FortuneRollData.Refresh () inline
Definition at line 115 of file FortuneRollData.cs.
    {
        if (EClass.world.date.GetRaw() >= dateNextRefresh)
        {
            Date date = EClass.world.date.Copy();
            date.day = 1;
            date.hour = 0;
            date.min = 0;
            date.AddMonth(1);
            dateNextRefresh = date.GetRaw();
            count++;
            RefreshPrize();
        }
    }
References Date.AddMonth(), Date.Copy(), count, World.date, dateNextRefresh, Date.GetRaw(), RefreshPrize(), and EClass.world.
Referenced by Zone.GetOrCreateFortuneRollData().
RefreshPrize()
void FortuneRollData.RefreshPrize () inline
Definition at line 130 of file FortuneRollData.cs.
    {
        prizes.Clear();
        Rand.SetSeed(EClass.game.seed + seed + count);
        List<List<string>> list = GetPrizeList();
        if ((EClass._zone.IsTown && EClass._zone.lv == 0) || (EClass.game.IsSurvival && EClass._zone is Zone_StartSiteSky))
        {
            Add(3);
            Add(2);
            Add(2);
            Add(1);
            Add(1);
            Add(1);
        }
        Rand.SetSeed();
        void Add(int grade)
        {
            List<string> list2 = list[grade];
            int index = EClass.rnd(list2.Count);
            Prize prize = new Prize
            {
                id = list2[index],
                grade = grade
            };
            string id = prize.id;
            if (!(id == "panty"))
            {
                if (id == "mathammer")
                {
                    SourceMaterial.Row randomMaterial = MATERIAL.GetRandomMaterial(20);
                    prize.idRef = randomMaterial.alias;
                }
            }
            else
            {
                IEnumerable<SourceChara.Row> ie = EClass.sources.charas.map.Values.Where((SourceChara.Row r) => (r.model.trait as TraitChara).IsWearingPanty && !r.HasTag(CTAG.noRandomProduct));
                prize.idRef = ie.RandomItem().id;
            }
            prizes.Add(prize);
            list2.RemoveAt(index);
        }
    }
References EClass._zone, Add(), SourceMaterial.Row.alias, SourceManager.charas, count, EClass.game, GetPrizeList(), MATERIAL.GetRandomMaterial(), FortuneRollData.Prize.id, Game.IsSurvival, Zone.IsTown, Spatial.lv, prizes, EClass.rnd(), seed, Game.seed, Rand.SetSeed(), and EClass.sources.
Referenced by Refresh().
WriteNote()
void FortuneRollData.WriteNote (UINote n) inline
Definition at line 271 of file FortuneRollData.cs.
    {
        n.Clear();
        n.AddHeader("fortuneroll_prize");
        n.Space(4);
        foreach (Prize prize in prizes)
        {
            prize.AddNote(n);
        }
        string text = "_circle".lang().TagColor(Color.white) + "  " + Lang.GetList("fortuneroll")[0];
        n.AddTopic("TopicDomain", text, "fortuneroll_lose".lang());
        n.Build();
    }
References UINote.AddHeader(), FortuneRollData.Prize.AddNote(), UINote.Clear(), Color, Lang.GetList(), prizes, and UINote.Space().
Referenced by UIDragGridInfo.Init().
Member Data Documentation
chances
int [] FortuneRollData.chances = new int[4] { 1, 8, 25, 60 } static
Definition at line 101 of file FortuneRollData.cs.
Referenced by TraitCrafter.Craft().
count
int FortuneRollData.count
Definition at line 107 of file FortuneRollData.cs.
Referenced by Zone.GetOrCreateFortuneRollData(), Refresh(), and RefreshPrize().
dateNextRefresh
int FortuneRollData.dateNextRefresh
Definition at line 113 of file FortuneRollData.cs.
Referenced by Refresh().
mats
string [] FortuneRollData.mats = new string[4] { "plastic", "water", "hide_dragon", "gold" } static
Definition at line 99 of file FortuneRollData.cs.
Referenced by FortuneRollData.Prize.AddNote(), and TraitCrafter.Craft().
prizes
List<Prize> FortuneRollData.prizes = new List<Prize>()
Definition at line 104 of file FortuneRollData.cs.
Referenced by GetPrize(), RefreshPrize(), and WriteNote().
seed
int FortuneRollData.seed
Definition at line 110 of file FortuneRollData.cs.
Referenced by GetPrize(), and RefreshPrize().
The documentation for this class was generated from the following file:
Elin/FortuneRollData.cs