Elin Decompiled Documentation: ElinEncoder Class Reference
ElinEncoder Class Reference
Static Public Member Functions
static string AesEncrypt (string srcStr)
static string AesDecrypt (string encStr)
static string GetCode (int idBacker, int index)
static string GetID (string code)
static bool IsValid (string code)
Static Private Attributes
const string key = "123456789012345678901234"
const string iv = "12345678"
Detailed Description
Definition at line 6 of file ElinEncoder.cs.
Member Function Documentation
AesDecrypt()
static string ElinEncoder.AesDecrypt (string encStr) inline static
Definition at line 25 of file ElinEncoder.cs.
    {
        TripleDESCryptoServiceProvider tripleDESCryptoServiceProvider = new TripleDESCryptoServiceProvider();
        byte[] array = Convert.FromBase64String(encStr);
        MemoryStream memoryStream = new MemoryStream();
        CryptoStream cryptoStream = new CryptoStream(memoryStream, tripleDESCryptoServiceProvider.CreateDecryptor(Encoding.UTF8.GetBytes("123456789012345678901234"), Encoding.UTF8.GetBytes("12345678")), CryptoStreamMode.Write);
        cryptoStream.Write(array, 0, array.Length);
        cryptoStream.Close();
        byte[] bytes = memoryStream.ToArray();
        memoryStream.Close();
        return Encoding.UTF8.GetString(bytes);
    }
Referenced by GetID(), and IsValid().
AesEncrypt()
static string ElinEncoder.AesEncrypt (string srcStr) inline static
Definition at line 12 of file ElinEncoder.cs.
    {
        TripleDESCryptoServiceProvider tripleDESCryptoServiceProvider = new TripleDESCryptoServiceProvider();
        byte[] bytes = Encoding.UTF8.GetBytes(srcStr);
        MemoryStream memoryStream = new MemoryStream();
        CryptoStream cryptoStream = new CryptoStream(memoryStream, tripleDESCryptoServiceProvider.CreateEncryptor(Encoding.UTF8.GetBytes("123456789012345678901234"), Encoding.UTF8.GetBytes("12345678")), CryptoStreamMode.Write);
        cryptoStream.Write(bytes, 0, bytes.Length);
        cryptoStream.Close();
        byte[] inArray = memoryStream.ToArray();
        memoryStream.Close();
        return Convert.ToBase64String(inArray);
    }
Referenced by GetCode().
GetCode()
static string ElinEncoder.GetCode (int idBacker, int index) inline static
Definition at line 38 of file ElinEncoder.cs.
    {
        return AesEncrypt(idBacker.ToString("0000") + index).TrimEnd('=');
    }
References AesEncrypt().
GetID()
static string ElinEncoder.GetID (string code) inline static
Definition at line 43 of file ElinEncoder.cs.
    {
        return AesDecrypt(code + "=");
    }
References AesDecrypt().
Referenced by UI.ToggleFeedback().
IsValid()
static bool ElinEncoder.IsValid (string code) inline static
Definition at line 48 of file ElinEncoder.cs.
    {
        try
        {
            int result;
            return int.TryParse(AesDecrypt(code + "="), out result);
        }
        catch
        {
        }
        return false;
    }
References AesDecrypt().
Referenced by CoreConfig.HasBackerRewardCode(), and ContentConfigOther.OpenBackerCodeInput().
Member Data Documentation
iv
const string ElinEncoder.iv = "12345678" static private
Definition at line 10 of file ElinEncoder.cs.
key
const string ElinEncoder.key = "123456789012345678901234" static private
Definition at line 8 of file ElinEncoder.cs.
The documentation for this class was generated from the following file:
Elin/Plugins.basecore/ElinEncoder.cs