Elin Decompiled Documentation: WidgetMascot Class Reference
WidgetMascot Class Reference
Public Member Functions
override void OnActivate ()
void _Update ()
override void OnFlip ()
void Say (string[] lines)
void Say (string str)
override void OnSetContextMenu (UIContextMenu m)
Public Member Functions inherited from Widget
void Test ()
bool IsInRightMode ()
void Activate ()
void RefreshOrder ()
virtual void OnActivate ()
virtual object CreateExtra ()
void Deactivate ()
virtual void OnDeactivate ()
void Close ()
void Reactivate ()
virtual void OnManagerActivate ()
virtual void OnManagerDeactivate ()
void SetAnchor (RectPosition p)
void SetPivot (RectPosition p)
virtual void OnChangePivot ()
void UpdateConfig ()
virtual void OnUpdateConfig ()
void ClampToScreen ()
virtual void OnChangeResolution ()
void OnChangePosition ()
virtual void OnChangeActionMode ()
virtual void OnFlip ()
bool IsAlignTop ()
Layer AddLayer (Layer l, Transform trans)
void RefreshTipPivotPosition ()
SkinSet GetSkin ()
SkinConfig GetSkinConfig ()
void SetSkin (int id, int v=0)
void TestSkin ()
virtual void ApplySkin ()
virtual void OnApplySkin ()
void InstantiateDeco (SkinDeco deco)
void AddDeco (SkinDeco deco)
void RemoveDeco (SkinDeco deco)
virtual bool CanShowContextMenu ()
void ShowContextMenu ()
void SetBaseContextMenu (UIContextMenu m)
virtual void OnSetContextMenu (UIContextMenu m)
void SetGridContextMenu (UIContextMenu m)
void SoundActivate ()
void OnChangeResolution ()
SkinSet GetSkin ()
SkinConfig GetSkinConfig ()
Public Attributes
RawImage image
UIText text
int intervalSay
string[] linesDefault
string[] linesSiege
string[] linesShutup
Vector2 textPos
Public Attributes inherited from Widget
Image imageBG
SoundData soundActivate
UIDragPanel dragPanel
RectTransform tipPivotLeft
RectTransform tipPivotRight
Properties
override bool ShowStyleMenu [get]
Properties inherited from Widget
string ID [get]
Config config [get]
SkinRoot skinRoot [get]
bool IsSealed [get]
virtual bool ShowStyleMenu [get]
virtual bool AlwaysTop [get]
virtual bool IsStaticPosition [get]
virtual bool AlwaysBottom [get]
virtual Type SetSiblingAfter [get]
virtual bool ShowInBuildMode [get]
virtual bool RightClickToClose [get]
virtual bool AllowRightClickToClose [get]
Properties inherited from EMono
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SoundManager Sound [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static CoreDebug debug [get]
Private Member Functions
void Update ()
Private Attributes
int nextSay = 2
bool first = true
bool isSiege
bool isShut
Additional Inherited Members
Public Types inherited from Widget
enum WidgetType { Default , ZoomMenu }
enum State { Active , Inactive }
Static Public Member Functions inherited from EMono
static int rnd (int a)
Static Public Attributes inherited from EMono
static Core core
Protected Member Functions inherited from Widget
void ClampToScreenEnsured (Component c, Vector2 anchoredPos)
void ClampToScreen (RectTransform rect, float margin=10f)
Protected Attributes inherited from Widget
bool flip
Detailed Description
Definition at line 5 of file WidgetMascot.cs.
Member Function Documentation
_Update()
void WidgetMascot._Update () inline
Definition at line 69 of file WidgetMascot.cs.
    {
        if (nextSay > 0)
        {
            nextSay--;
        }
        else
        {
            if (isShut)
            {
                return;
            }
            isSiege = EMono._zone.events.GetEvent<ZoneEventSiege>() != null;
            string[] array = (isSiege ? linesSiege : linesDefault);
            if (array != null)
            {
                string str = ((EMono.rnd(2) == 0) ? "" : array.RandomItem());
                if (first)
                {
                    str = array[0];
                    first = false;
                }
                Say(str);
            }
        }
    }
References EMono._zone, Zone.events, first, isShut, isSiege, linesDefault, linesSiege, nextSay, EMono.rnd(), and Say().
OnActivate()
override void WidgetMascot.OnActivate () inline virtual
Reimplemented from Widget.
Definition at line 31 of file WidgetMascot.cs.
    {
        string path = string.Concat(CorePath.coreWidget + base.config.id + "/", "default.png");
        string obj = Lang.setting.dir + "Widget/" + base.config.id + "/";
        string path2 = obj + "default.txt";
        string path3 = obj + "siege.txt";
        string path4 = obj + "shutup.txt";
        if (File.Exists(path2))
        {
            linesDefault = IO.LoadTextArray(path2);
        }
        if (File.Exists(path3))
        {
            linesSiege = IO.LoadTextArray(path3);
        }
        if (File.Exists(path4))
        {
            linesShutup = IO.LoadTextArray(path4);
        }
        if (File.Exists(path))
        {
            image.texture = IO.LoadPNG(path);
        }
        Say("");
        InvokeRepeating("_Update", 1f, 1f);
    }
References CorePath.coreWidget, linesDefault, linesShutup, linesSiege, and Say().
OnFlip()
override void WidgetMascot.OnFlip () inline virtual
Reimplemented from Widget.
Definition at line 96 of file WidgetMascot.cs.
    {
        image.transform.localScale = new Vector3(flip ? 1 : (-1), 1f, 1f);
    }
References Widget.flip.
OnSetContextMenu()
override void WidgetMascot.OnSetContextMenu (UIContextMenu m) inline virtual
Reimplemented from Widget.
Definition at line 126 of file WidgetMascot.cs.
    {
        m.AddToggle("shutup", isShut, delegate(bool a)
        {
            isShut = a;
            base.config.annoyPlayer = isShut;
            if (isShut)
            {
                Say(linesShutup);
            }
        });
        SetBaseContextMenu(m);
    }
References UIContextMenu.AddToggle(), isShut, linesShutup, Say(), and Widget.SetBaseContextMenu().
Say() [1/2]
void WidgetMascot.Say (string str) inline
Definition at line 106 of file WidgetMascot.cs.
    {
        Transform parent = text.transform.parent;
        if (str.IsEmpty())
        {
            parent.SetActive(enable: false);
        }
        else
        {
            parent.SetActive(enable: true);
            text.text = str;
            ClampToScreenEnsured(parent, textPos);
        }
        nextSay = intervalSay + EMono.rnd(intervalSay);
        if (isSiege)
        {
            nextSay /= 2;
        }
    }
References Widget.ClampToScreenEnsured(), intervalSay, isSiege, nextSay, EMono.rnd(), text, and textPos.
Say() [2/2]
void WidgetMascot.Say (string[] lines) inline
Definition at line 101 of file WidgetMascot.cs.
    {
        Say(lines.RandomItem());
    }
References Say().
Referenced by _Update(), OnActivate(), OnSetContextMenu(), and Say().
Update()
void WidgetMascot.Update () inline private
Definition at line 58 of file WidgetMascot.cs.
    {
        if (isShut && InputModuleEX.IsPointerOver(base.transform))
        {
            SE.Play("teleport");
            base.transform.position = new Vector3(EMono.rnd(Screen.width), EMono.rnd(Screen.height), 0f);
            OnChangePosition();
            ClampToScreen();
        }
    }
References Widget.ClampToScreen(), InputModuleEX.IsPointerOver(), isShut, Widget.OnChangePosition(), and EMono.rnd().
Member Data Documentation
first
bool WidgetMascot.first = true private
Definition at line 23 of file WidgetMascot.cs.
Referenced by _Update().
image
RawImage WidgetMascot.image
Definition at line 7 of file WidgetMascot.cs.
intervalSay
int WidgetMascot.intervalSay
Definition at line 11 of file WidgetMascot.cs.
Referenced by Say().
isShut
bool WidgetMascot.isShut private
Definition at line 27 of file WidgetMascot.cs.
Referenced by _Update(), OnSetContextMenu(), and Update().
isSiege
bool WidgetMascot.isSiege private
Definition at line 25 of file WidgetMascot.cs.
Referenced by _Update(), and Say().
linesDefault
string [] WidgetMascot.linesDefault
Definition at line 13 of file WidgetMascot.cs.
Referenced by _Update(), and OnActivate().
linesShutup
string [] WidgetMascot.linesShutup
Definition at line 17 of file WidgetMascot.cs.
Referenced by OnActivate(), and OnSetContextMenu().
linesSiege
string [] WidgetMascot.linesSiege
Definition at line 15 of file WidgetMascot.cs.
Referenced by _Update(), and OnActivate().
nextSay
int WidgetMascot.nextSay = 2 private
Definition at line 21 of file WidgetMascot.cs.
Referenced by _Update(), and Say().
text
UIText WidgetMascot.text
Definition at line 9 of file WidgetMascot.cs.
Referenced by Say().
textPos
Vector2 WidgetMascot.textPos
Definition at line 19 of file WidgetMascot.cs.
Referenced by Say().
Property Documentation
ShowStyleMenu
override bool WidgetMascot.ShowStyleMenu get
Definition at line 29 of file WidgetMascot.cs.
The documentation for this class was generated from the following file:
Elin/WidgetMascot.cs