Elin Decompiled Documentation: SpatialManager.GlobalSpatialList Class Reference
SpatialManager.GlobalSpatialList Class Reference
Public Member Functions
void Add (Spatial s)
Detailed Description
Definition at line 8 of file SpatialManager.cs.
Member Function Documentation
Add()
void SpatialManager.GlobalSpatialList.Add (Spatial s) inline
Definition at line 10 of file SpatialManager.cs.
        {
            Add(s.uid, s);
        }
References SpatialManager.GlobalSpatialList.Add(), and Spatial.uid.
Referenced by SpatialManager.GlobalSpatialList.Add(), and SpatialManager.AssignUID().
The documentation for this class was generated from the following file:
Elin/SpatialManager.cs