Elin Decompiled Documentation: ToneDataList Class Reference
ToneDataList Class Reference
Public Member Functions
override void OnInitialize ()
StringBuilder ApplyTone (string id, ref string text, int gender)
string GetToneID (string id, int gender)
Public Member Functions inherited from ExcelDataList
void Reload ()
virtual void Initialize ()
virtual void OnInitialize ()
Dictionary< string, string > GetRow (string id)
Additional Inherited Members
Public Attributes inherited from ExcelDataList
List< ExcelData > items = new List<ExcelData>(0)
Dictionary< string, Dictionary< string, string > > all = new Dictionary<string, Dictionary<string, string>>()
List< Dictionary< string, string > > list = new List<Dictionary<string, string>>()
Protected Attributes inherited from ExcelDataList
bool initialized
Properties inherited from ExcelDataList
virtual int StartIndex [get]
Detailed Description
Definition at line 5 of file ToneDataList.cs.
Member Function Documentation
ApplyTone()
StringBuilder ToneDataList.ApplyTone (string id, ref string text, int gender) inline
Definition at line 11 of file ToneDataList.cs.
    {
        if (!initialized)
        {
            Initialize();
        }
        Dictionary<string, string> dictionary = all[id];
        StringBuilder stringBuilder = new StringBuilder();
        bool flag = false;
        string text2 = "";
        for (int i = 0; i < text.Length; i++)
        {
            if (flag)
            {
                if (text[i] == '}')
                {
                    flag = false;
                    if (dictionary.ContainsKey(text2))
                    {
                        string text3 = dictionary[text2].Split(new string[3] { "\r\n", "\r", "\n" }, StringSplitOptions.None).TryGet((gender != 2) ? 1 : 0, 0);
                        stringBuilder.Append(text3.Split(',').RandomItem());
                    }
                    else
                    {
                        stringBuilder.Append(text2);
                    }
                }
                else
                {
                    text2 += text[i];
                }
            }
            else if (text[i] == '{')
            {
                text2 = "";
                flag = true;
            }
            else
            {
                stringBuilder.Append(text[i]);
            }
        }
        stringBuilder.Replace("…～", "～…");
        stringBuilder.Replace("…ー", "ー…");
        return stringBuilder;
    }
References ExcelDataList.all, ExcelDataList.Initialize(), and ExcelDataList.initialized.
Referenced by Card.ApplyTone().
GetToneID()
string ToneDataList.GetToneID (string id, int gender) inline
Definition at line 58 of file ToneDataList.cs.
    {
        if (!initialized)
        {
            Initialize();
        }
        if (!Lang.isJP)
        {
            return id + "|I|YOU";
        }
        Dictionary<string, string> dictionary = all[id];
        string text = dictionary["I"].Split(new string[3] { "\r\n", "\r", "\n" }, StringSplitOptions.None).TryGet((gender != 2) ? 1 : 0, 0);
        string text2 = dictionary["YOU"].Split(new string[3] { "\r\n", "\r", "\n" }, StringSplitOptions.None).TryGet((gender != 2) ? 1 : 0, 0);
        string[] array = text.Split(',');
        string[] array2 = text2.Split(',');
        return id + "|" + array[rnd(rnd(array.Length) + 1)] + "|" + array2[rnd(rnd(array2.Length) + 1)];
        static int rnd(int a)
        {
            return Rand.rnd(a);
        }
    }
References ExcelDataList.all, ExcelDataList.Initialize(), ExcelDataList.initialized, Lang.isJP, and Rand.rnd().
Referenced by Card.SetRandomTone().
OnInitialize()
override void ToneDataList.OnInitialize () inline virtual
Reimplemented from ExcelDataList.
Definition at line 7 of file ToneDataList.cs.
    {
    }
The documentation for this class was generated from the following file:
Elin/Plugins.basecore/ToneDataList.cs