Elin Decompiled Documentation: EffectManager Class Reference
EffectManager Class Reference
Classes
class EffectList
Public Member Functions
void Add (Effect e)
void Remove (Effect e)
void KillAll ()
void UpdateEffects ()
Public Attributes
List< Effect > list = new List<Effect>()
EffectList effects
Static Public Attributes
static EffectManager Instance
Static Public Attributes inherited from EMono
static Core core
Additional Inherited Members
Static Public Member Functions inherited from EMono
static int rnd (int a)
Properties inherited from EMono
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SoundManager Sound [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static CoreDebug debug [get]
Detailed Description
Definition at line 4 of file EffectManager.cs.
Member Function Documentation
Add()
void EffectManager.Add (Effect e) inline
Definition at line 22 of file EffectManager.cs.
    {
        list.Add(e);
    }
References list.
Referenced by Effect.Activate().
KillAll()
void EffectManager.KillAll () inline
Definition at line 32 of file EffectManager.cs.
    {
        for (int num = list.Count - 1; num >= 0; num--)
        {
            list[num].Kill();
        }
    }
References list.
Referenced by Scene.Clear(), and BaseGameScreen.Draw().
Remove()
void EffectManager.Remove (Effect e) inline
Definition at line 27 of file EffectManager.cs.
    {
        list.Remove(e);
    }
References list.
Referenced by Effect.Kill().
UpdateEffects()
void EffectManager.UpdateEffects () inline
Definition at line 40 of file EffectManager.cs.
    {
        for (int num = list.Count - 1; num >= 0; num--)
        {
            list[num].OnUpdate();
        }
    }
References list.
Referenced by BaseGameScreen.Draw().
Member Data Documentation
effects
EffectList EffectManager.effects
Definition at line 20 of file EffectManager.cs.
Referenced by Effect.Get(), Effect.Get< T >(), and Effect.Kill().
Instance
EffectManager EffectManager.Instance static
Definition at line 18 of file EffectManager.cs.
Referenced by Scene.Clear(), and BaseGameScreen.Draw().
list
List<Effect> EffectManager.list = new List<Effect>()
Definition at line 16 of file EffectManager.cs.
Referenced by Add(), KillAll(), Remove(), and UpdateEffects().
The documentation for this class was generated from the following file:
Elin/EffectManager.cs