Elin Decompiled Documentation: LayoutMaxSize Class Reference
LayoutMaxSize Class Reference
Public Member Functions
override void CalculateLayoutInputHorizontal ()
override void CalculateLayoutInputVertical ()
Public Attributes
float maxHeight = -1f
float maxWidth = -1f
Protected Member Functions
override void OnRectTransformDimensionsChange ()
Private Member Functions
void UpdateMaxSizes ()
Detailed Description
Definition at line 7 of file LayoutMaxSize.cs.
Member Function Documentation
CalculateLayoutInputHorizontal()
override void LayoutMaxSize.CalculateLayoutInputHorizontal () inline
Definition at line 13 of file LayoutMaxSize.cs.
    {
        base.CalculateLayoutInputHorizontal();
        UpdateMaxSizes();
    }
References UpdateMaxSizes().
CalculateLayoutInputVertical()
override void LayoutMaxSize.CalculateLayoutInputVertical () inline
Definition at line 19 of file LayoutMaxSize.cs.
    {
        base.CalculateLayoutInputVertical();
        UpdateMaxSizes();
    }
References UpdateMaxSizes().
OnRectTransformDimensionsChange()
override void LayoutMaxSize.OnRectTransformDimensionsChange () inline protected
Definition at line 25 of file LayoutMaxSize.cs.
    {
        base.OnRectTransformDimensionsChange();
        UpdateMaxSizes();
    }
References UpdateMaxSizes().
UpdateMaxSizes()
void LayoutMaxSize.UpdateMaxSizes () inline private
Definition at line 31 of file LayoutMaxSize.cs.
    {
        if (maxWidth != -1f)
        {
            RectTransform rectTransform = this.Rect();
            if (rectTransform.sizeDelta.x > maxWidth)
            {
                rectTransform.sizeDelta = new Vector2(maxWidth, rectTransform.sizeDelta.y);
                preferredWidth = maxWidth;
            }
        }
    }
References maxWidth.
Referenced by CalculateLayoutInputHorizontal(), CalculateLayoutInputVertical(), and OnRectTransformDimensionsChange().
Member Data Documentation
maxHeight
float LayoutMaxSize.maxHeight = -1f
Definition at line 9 of file LayoutMaxSize.cs.
maxWidth
float LayoutMaxSize.maxWidth = -1f
Definition at line 11 of file LayoutMaxSize.cs.
Referenced by UpdateMaxSizes().
The documentation for this class was generated from the following file:
Elin/Plugins.UI/LayoutMaxSize.cs