Elin Decompiled Documentation: InvOwnerDeliver Class Reference
InvOwnerDeliver Class Reference
Public Types
enum Mode { Default , Tax , Bank , Crop }
Public Types inherited from InvOwnerDraglet
enum ProcessType { None , Consume }
Public Member Functions
InvOwnerDeliver (Card owner=null, Card container=null, CurrencyType _currency=CurrencyType.Money)
override bool ShouldShowGuide (Thing t)
override void _OnProcess (Thing t)
Public Member Functions inherited from InvOwnerDraglet
override bool AllowHold (Thing t)
InvOwnerDraglet (Card owner=null, Card container=null, CurrencyType _currency=CurrencyType.Money)
override void OnInit ()
override void OnClick (ButtonGrid button)
override void OnRightClick (ButtonGrid button)
override int GetPrice (Thing t, CurrencyType currency, int num, bool sell)
override string GetTextDetail (Thing t, CurrencyType currency, int num, bool sell)
virtual void OnWriteNote (Thing t, UINote n)
sealed override void OnProcess (Thing t)
virtual void _OnProcess (Thing t)
virtual void OnAfterRefuel ()
void RedrawButton ()
override void BuildUICurrency (UICurrency uiCurrency, bool canReroll=false)
Public Member Functions inherited from InvOwner
virtual bool AllowHold (Thing t)
virtual bool AllowMoved (Thing t)
virtual bool ShouldShowGuide (Thing t)
virtual bool AllowDrop (Thing t)
virtual Thing CreateDefaultContainer ()
virtual void BuildUICurrency (UICurrency uiCurrency, bool canReroll=false)
bool IsWeightOver (Thing t)
InvOwner (Card owner, Card container=null, CurrencyType _currency=CurrencyType.None, PriceType _price=PriceType.Default)
void Init ()
virtual void OnInit ()
virtual void OnClick (ButtonGrid button)
virtual void OnRightClick (ButtonGrid button)
virtual void OnRightPressed (ButtonGrid button)
InvOwner GetShitDestOwner (ButtonGrid b, bool rightMouse=false)
virtual void OnShiftClick (ButtonGrid b, bool rightMouse=false)
virtual bool CanShiftClick (ButtonGrid b, bool rightMouse=false)
virtual string GetTextShiftClick (ButtonGrid b)
virtual void OnCtrlClick (ButtonGrid button)
virtual bool CanCtrlClick (ButtonGrid b)
virtual string GetTextCtrlClick (ButtonGrid b)
virtual void OnAltClick (ButtonGrid button)
virtual bool CanAltClick (ButtonGrid b)
virtual string GetTextAltClick (ButtonGrid b)
void Grab (DragItemCard.DragInfo from)
Thing PutBack (DragItemCard.DragInfo from)
void OnStartDrag (DragItemCard.DragInfo from)
virtual bool OnCancelDrag (DragItemCard.DragInfo from)
virtual bool OnDrag (DragItemCard.DragInfo from, DragItemCard.DragInfo to, bool execute, bool cancel=false)
virtual void OnProcess (Thing t)
bool CanOpenContainer (Thing t)
ListInteraction ListInteractions (ButtonGrid b, bool context)
bool TryHold (Thing t)
virtual void ListInteractions (ListInteraction list, Thing t, Trait trait, ButtonGrid b, bool context)
virtual string GetAutoUseLang (ButtonGrid button)
void AutoUse (ButtonGrid button, bool repeat=false)
void ShowContextMenu (ButtonGrid button)
virtual int GetPrice (Thing t, CurrencyType currency, int num, bool sell)
virtual string GetTextDetail (Thing t, CurrencyType currency, int num, bool sell)
virtual void OnWriteNote (ButtonGrid button, UINote n)
virtual string IDCostIcon (Thing t)
virtual bool IsFailByCurse (Thing t)
Static Public Member Functions
static void PayBill (Thing t, bool fromBank=false)
Static Public Member Functions inherited from EClass
static int rnd (int a)
static int curve (int a, int start, int step, int rate=75)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Public Attributes
Mode mode
Public Attributes inherited from InvOwnerDraglet
int count = -1
BlessedState state
int price
Public Attributes inherited from InvOwner
bool includeChildren
CurrencyType currency
PriceType priceType
HomeResource homeResource
Card owner
Card Container
List< ButtonGrid > buttons = new List<ButtonGrid>()
Properties
override bool SingleTarget [get]
override string langTransfer [get]
override ProcessType processType [get]
Properties inherited from InvOwnerDraglet
virtual ProcessType processType [get]
virtual bool ShowFuel [get]
virtual bool CanTargetAlly [get]
virtual string langWhat [get]
virtual bool AllowStockIngredients [get]
override bool AllowTransfer [get]
override bool AllowAutouse [get]
override bool AllowContext [get]
override bool UseGuide [get]
override bool CopyOnTransfer [get]
override bool InvertSell [get]
override bool DenyImportant [get]
LayerDragGrid dragGrid [get]
Properties inherited from InvOwner
static bool HasTrader [get]
static bool FreeTransfer [get]
virtual bool AllowAutouse [get]
virtual bool AllowContext [get]
virtual bool AllowSell [get]
virtual bool AlwaysShowTooltip [get]
virtual bool UseGuide [get]
virtual bool AllowTransfer [get]
virtual bool AllowDropOnDrag [get]
virtual string langTransfer [get]
virtual int destInvY [get]
virtual bool HasTransaction [get]
virtual bool CopyOnTransfer [get]
virtual bool SingleTarget [get]
bool UseHomeResource [get]
bool IsMagicChest [get]
List< Thing > Things [get]
Chara Chara [get]
ContainerType ContainerType [get]
virtual bool InvertSell [get]
virtual int numDragGrid [get]
virtual bool ShowNew [get]
virtual bool DenyImportant [get]
InvOwner destInvOwner [get]
string IDCurrency [get]
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Additional Inherited Members
Static Public Attributes inherited from InvOwner
static ForceGiveData forceGive = new ForceGiveData()
static InvOwner Trader
static InvOwner Main
static float clickTimer
Static Public Attributes inherited from EClass
static Core core
Detailed Description
Definition at line 1 of file InvOwnerDeliver.cs.
Member Enumeration Documentation
Mode
enum InvOwnerDeliver.Mode
Enumerator
Default
Tax
Bank
Crop
Definition at line 3 of file InvOwnerDeliver.cs.
    {
        Default,
        Tax,
        Bank,
        Crop
    }
Constructor & Destructor Documentation
InvOwnerDeliver()
InvOwnerDeliver.InvOwnerDeliver (Card owner = null, Card container = null, CurrencyType _currency = CurrencyType::Money) inline
Definition at line 29 of file InvOwnerDeliver.cs.
        : base(owner, container, _currency)
    {
    }
Member Function Documentation
_OnProcess()
override void InvOwnerDeliver._OnProcess (Thing t) inline virtual
Reimplemented from InvOwnerDraglet.
Definition at line 109 of file InvOwnerDeliver.cs.
    {
        switch (mode)
        {
        case Mode.Tax:
            PayBill(t);
            break;
        case Mode.Bank:
            SE.Pay();
            Msg.Say("depositMoney", t, owner);
            owner.AddThing(t);
            break;
        case Mode.Crop:
        {
            Msg.Say("farm_chest", t, Lang._weight(t.SelfWeight * t.Num));
            QuestHarvest questHarvest = EClass.game.quests.Get<QuestHarvest>();
            if (questHarvest != null)
            {
                questHarvest.weightDelivered += t.SelfWeight * t.Num;
            }
            SE.Pick();
            t.Destroy();
            break;
        }
        }
    }
References Card.AddThing(), Card.Destroy(), EClass.game, QuestManager.Get(), mode, Card.Num, InvOwner.owner, PayBill(), Game.quests, Msg.Say(), and Thing.SelfWeight.
PayBill()
static void InvOwnerDeliver.PayBill (Thing t, bool fromBank = false) inline static
Definition at line 53 of file InvOwnerDeliver.cs.
    {
        bool flag = t.id == "bill_tax";
        bool flag2 = t.id == "bill_debt";
        QuestDebt questDebt = EClass.game.quests.Get<QuestDebt>();
        bool flag3 = flag2 && questDebt != null && !questDebt.paid && questDebt.IsValidBill(t);
        if ((flag && EClass.player.taxBills <= 0) || (flag2 && !flag3))
        {
            SE.Beep();
            Msg.Say("badidea");
            EClass.pc.Pick(t, msg: false);
            return;
        }
        if (fromBank)
        {
            EClass.game.cards.container_deposit.ModCurrency(-t.c_bill);
        }
        else if (!EClass.pc.TryPay(t.c_bill))
        {
            return;
        }
        if (flag2)
        {
            EClass.player.debt -= t.c_bill;
            if (EClass.player.debt < 0)
            {
                EClass.player.debt = 0;
            }
            questDebt.paid = true;
            questDebt.UpdateJournal();
        }
        else if (flag)
        {
            EClass.player.stats.taxBillsPaid += t.c_bill;
            EClass.player.taxBills--;
            if (EClass.player.taxBills < 0)
            {
                EClass.player.taxBills = 0;
            }
            int num = t.GetInt(35) / 1000;
            if (num > 0)
            {
                Thing thing = ThingGen.Create("money2", "copper").SetNum(num);
                Thing p = ThingGen.CreateParcel("parcel_mysiliaGift", thing);
                Msg.Say("getSalary", thing);
                EClass.world.SendPackage(p);
            }
        }
        else
        {
            EClass.player.unpaidBill -= t.c_bill;
        }
        Msg.Say("payBill", t);
        t.Destroy();
    }
References Card.c_bill, Game.cards, CardManager.container_deposit, ThingGen.Create(), ThingGen.CreateParcel(), Player.debt, Card.Destroy(), EClass.game, QuestManager.Get(), BaseCard.GetInt(), QuestDebt.IsValidBill(), Card.ModCurrency(), EClass.pc, Chara.Pick(), EClass.player, Game.quests, Msg.Say(), World.SendPackage(), Card.SetNum(), Player.taxBills, Card.TryPay(), Quest.UpdateJournal(), and EClass.world.
Referenced by _OnProcess(), and Faction.TryPayBill().
ShouldShowGuide()
override bool InvOwnerDeliver.ShouldShowGuide (Thing t) inline virtual
Reimplemented from InvOwner.
Definition at line 34 of file InvOwnerDeliver.cs.
    {
        switch (mode)
        {
        case Mode.Tax:
            return t.c_bill != 0;
        case Mode.Bank:
            return t.id == "money";
        case Mode.Crop:
            if (!(t.category.id == "vegi") && !(t.category.id == "fruit"))
            {
                return t.category.id == "mushroom";
            }
            return true;
        default:
            return false;
        }
    }
References Card.category, and mode.
Member Data Documentation
mode
Mode InvOwnerDeliver.mode
Definition at line 11 of file InvOwnerDeliver.cs.
Referenced by _OnProcess(), and ShouldShowGuide().
Property Documentation
langTransfer
override string InvOwnerDeliver.langTransfer get
Definition at line 15 of file InvOwnerDeliver.cs.
    {
        get
        {
            if (mode != Mode.Bank)
            {
                return "invDeliver";
            }
            return "invBank";
        }
    }
processType
override ProcessType InvOwnerDeliver.processType get
Definition at line 27 of file InvOwnerDeliver.cs.
SingleTarget
override bool InvOwnerDeliver.SingleTarget get
Definition at line 13 of file InvOwnerDeliver.cs.
The documentation for this class was generated from the following file:
Elin/InvOwnerDeliver.cs