Elin Decompiled Documentation: PrimitiveUI.Examples.PUIExampleCharts Class Reference
PrimitiveUI.Examples.PUIExampleCharts Class Reference
Public Attributes
PrimitiveCanvas primitiveCanvas
Slider sliderAka
Slider sliderBlauw
Slider sliderGelb
Slider sliderVerde
float barChartBarWidth = 0.2f
Private Member Functions
void Start ()
void Draw ()
Private Attributes
Rect barChartBounds = new Rect(0.45f, 0.05f, 0.5f, 0.5f)
Vector2 pieChartCenter = new Vector2(0.7f, 0.8f)
float pieChartRadius = 0.1f
Color red = new Color(1f, 0.196f, 0f)
Color blue = new Color(0f, 0.47f, 1f)
Color yellow = new Color(1f, 0.92f, 0f)
Color green = new Color(0f, 1f, 0.176f)
StrokeStyle barChartAxisStroke
StrokeStyle barChartBgStroke
Detailed Description
Definition at line 6 of file PUIExampleCharts.cs.
Member Function Documentation
Draw()
void PrimitiveUI.Examples.PUIExampleCharts.Draw () inline private
Definition at line 62 of file PUIExampleCharts.cs.
    {
        primitiveCanvas.Clear();
        float num = barChartBounds.height / 9f;
        for (int i = 0; i < 8; i++)
        {
            float y = barChartBounds.yMin + (float)(i + 1) * num;
            primitiveCanvas.DrawLine(new Vector2(barChartBounds.xMin, y), new Vector2(barChartBounds.xMax, y), barChartBgStroke);
        }
        float num2 = barChartBounds.width * barChartBarWidth;
        float num3 = (barChartBounds.width - num2 * 4f) / 5f;
        Rect rect = new Rect(barChartBounds.xMin + num3 * 1f, barChartBounds.yMin, num2, sliderAka.value * barChartBounds.height * 0.01f);
        primitiveCanvas.DrawRectangle(rect, red);
        rect = new Rect(barChartBounds.xMin + num3 * 2f + num2 * 1f, barChartBounds.yMin, num2, sliderBlauw.value * barChartBounds.height * 0.01f);
        primitiveCanvas.DrawRectangle(rect, blue);
        rect = new Rect(barChartBounds.xMin + num3 * 3f + num2 * 2f, barChartBounds.yMin, num2, sliderGelb.value * barChartBounds.height * 0.01f);
        primitiveCanvas.DrawRectangle(rect, yellow);
        rect = new Rect(barChartBounds.xMin + num3 * 4f + num2 * 3f, barChartBounds.yMin, num2, sliderVerde.value * barChartBounds.height * 0.01f);
        primitiveCanvas.DrawRectangle(rect, green);
        Vector2[] points = new Vector2[3]
        {
            new Vector2(barChartBounds.xMin, barChartBounds.yMax),
            barChartBounds.min,
            new Vector2(barChartBounds.xMax, barChartBounds.yMin)
        };
        primitiveCanvas.DrawPath(points, barChartAxisStroke, closePath: false);
        float num4 = sliderAka.value + sliderBlauw.value + sliderGelb.value + sliderVerde.value;
        float num5 = 0f;
        float num6 = sliderAka.value / num4 * 360f;
        primitiveCanvas.DrawCircle(pieChartCenter, pieChartRadius, 1f, num5, num5 + num6, red);
        num5 += num6;
        num6 = sliderBlauw.value / num4 * 360f;
        primitiveCanvas.DrawCircle(pieChartCenter, pieChartRadius, 1f, num5, num5 + num6, blue);
        num5 += num6;
        num6 = sliderGelb.value / num4 * 360f;
        primitiveCanvas.DrawCircle(pieChartCenter, pieChartRadius, 1f, num5, num5 + num6, yellow);
        num5 += num6;
        num6 = sliderVerde.value / num4 * 360f;
        primitiveCanvas.DrawCircle(pieChartCenter, pieChartRadius, 1f, num5, num5 + num6, green);
        primitiveCanvas.DrawCircle(pieChartCenter, pieChartRadius, 1f, 0f, 1f, red);
    }
References PrimitiveUI.Examples.PUIExampleCharts.barChartAxisStroke, PrimitiveUI.Examples.PUIExampleCharts.barChartBarWidth, PrimitiveUI.Examples.PUIExampleCharts.barChartBgStroke, PrimitiveUI.Examples.PUIExampleCharts.barChartBounds, PrimitiveUI.Examples.PUIExampleCharts.blue, PrimitiveUI.PrimitiveCanvas.Clear(), PrimitiveUI.PrimitiveCanvas.DrawCircle(), PrimitiveUI.PrimitiveCanvas.DrawLine(), PrimitiveUI.PrimitiveCanvas.DrawPath(), PrimitiveUI.PrimitiveCanvas.DrawRectangle(), PrimitiveUI.Examples.PUIExampleCharts.green, PrimitiveUI.Examples.PUIExampleCharts.pieChartCenter, PrimitiveUI.Examples.PUIExampleCharts.pieChartRadius, PrimitiveUI.Examples.PUIExampleCharts.primitiveCanvas, PrimitiveUI.Examples.PUIExampleCharts.red, PrimitiveUI.Examples.PUIExampleCharts.sliderAka, PrimitiveUI.Examples.PUIExampleCharts.sliderBlauw, PrimitiveUI.Examples.PUIExampleCharts.sliderGelb, PrimitiveUI.Examples.PUIExampleCharts.sliderVerde, and PrimitiveUI.Examples.PUIExampleCharts.yellow.
Referenced by PrimitiveUI.Examples.PUIExampleCharts.Start().
Start()
void PrimitiveUI.Examples.PUIExampleCharts.Start () inline private
Definition at line 39 of file PUIExampleCharts.cs.
    {
        sliderAka.onValueChanged.AddListener(delegate
        {
            Draw();
        });
        sliderBlauw.onValueChanged.AddListener(delegate
        {
            Draw();
        });
        sliderGelb.onValueChanged.AddListener(delegate
        {
            Draw();
        });
        sliderVerde.onValueChanged.AddListener(delegate
        {
            Draw();
        });
        barChartAxisStroke = new StrokeStyle(Color.black, 0.006f, StrokeScaleMode.Relative);
        barChartBgStroke = new StrokeStyle(new Color(0f, 0f, 0f, 0.2f), 0.0025f, StrokeScaleMode.Relative);
        Draw();
    }
References PrimitiveUI.Examples.PUIExampleCharts.barChartAxisStroke, PrimitiveUI.Examples.PUIExampleCharts.barChartBgStroke, Color, PrimitiveUI.Examples.PUIExampleCharts.Draw(), PrimitiveUI.Examples.PUIExampleCharts.sliderAka, PrimitiveUI.Examples.PUIExampleCharts.sliderBlauw, PrimitiveUI.Examples.PUIExampleCharts.sliderGelb, and PrimitiveUI.Examples.PUIExampleCharts.sliderVerde.
Member Data Documentation
barChartAxisStroke
StrokeStyle PrimitiveUI.Examples.PUIExampleCharts.barChartAxisStroke private
Definition at line 35 of file PUIExampleCharts.cs.
Referenced by PrimitiveUI.Examples.PUIExampleCharts.Draw(), and PrimitiveUI.Examples.PUIExampleCharts.Start().
barChartBarWidth
float PrimitiveUI.Examples.PUIExampleCharts.barChartBarWidth = 0.2f
Definition at line 19 of file PUIExampleCharts.cs.
Referenced by PrimitiveUI.Examples.PUIExampleCharts.Draw().
barChartBgStroke
StrokeStyle PrimitiveUI.Examples.PUIExampleCharts.barChartBgStroke private
Definition at line 37 of file PUIExampleCharts.cs.
Referenced by PrimitiveUI.Examples.PUIExampleCharts.Draw(), and PrimitiveUI.Examples.PUIExampleCharts.Start().
barChartBounds
Rect PrimitiveUI.Examples.PUIExampleCharts.barChartBounds = new Rect(0.45f, 0.05f, 0.5f, 0.5f) private
Definition at line 21 of file PUIExampleCharts.cs.
Referenced by PrimitiveUI.Examples.PUIExampleCharts.Draw().
blue
Color PrimitiveUI.Examples.PUIExampleCharts.blue = new Color(0f, 0.47f, 1f) private
Definition at line 29 of file PUIExampleCharts.cs.
Referenced by PrimitiveUI.Examples.PUIExampleCharts.Draw().
green
Color PrimitiveUI.Examples.PUIExampleCharts.green = new Color(0f, 1f, 0.176f) private
Definition at line 33 of file PUIExampleCharts.cs.
Referenced by PrimitiveUI.Examples.PUIExampleCharts.Draw().
pieChartCenter
Vector2 PrimitiveUI.Examples.PUIExampleCharts.pieChartCenter = new Vector2(0.7f, 0.8f) private
Definition at line 23 of file PUIExampleCharts.cs.
Referenced by PrimitiveUI.Examples.PUIExampleCharts.Draw().
pieChartRadius
float PrimitiveUI.Examples.PUIExampleCharts.pieChartRadius = 0.1f private
Definition at line 25 of file PUIExampleCharts.cs.
Referenced by PrimitiveUI.Examples.PUIExampleCharts.Draw().
primitiveCanvas
PrimitiveCanvas PrimitiveUI.Examples.PUIExampleCharts.primitiveCanvas
Definition at line 8 of file PUIExampleCharts.cs.
Referenced by PrimitiveUI.Examples.PUIExampleCharts.Draw().
red
Color PrimitiveUI.Examples.PUIExampleCharts.red = new Color(1f, 0.196f, 0f) private
Definition at line 27 of file PUIExampleCharts.cs.
Referenced by PrimitiveUI.Examples.PUIExampleCharts.Draw().
sliderAka
Slider PrimitiveUI.Examples.PUIExampleCharts.sliderAka
Definition at line 10 of file PUIExampleCharts.cs.
Referenced by PrimitiveUI.Examples.PUIExampleCharts.Draw(), and PrimitiveUI.Examples.PUIExampleCharts.Start().
sliderBlauw
Slider PrimitiveUI.Examples.PUIExampleCharts.sliderBlauw
Definition at line 12 of file PUIExampleCharts.cs.
Referenced by PrimitiveUI.Examples.PUIExampleCharts.Draw(), and PrimitiveUI.Examples.PUIExampleCharts.Start().
sliderGelb
Slider PrimitiveUI.Examples.PUIExampleCharts.sliderGelb
Definition at line 14 of file PUIExampleCharts.cs.
Referenced by PrimitiveUI.Examples.PUIExampleCharts.Draw(), and PrimitiveUI.Examples.PUIExampleCharts.Start().
sliderVerde
Slider PrimitiveUI.Examples.PUIExampleCharts.sliderVerde
Definition at line 16 of file PUIExampleCharts.cs.
Referenced by PrimitiveUI.Examples.PUIExampleCharts.Draw(), and PrimitiveUI.Examples.PUIExampleCharts.Start().
yellow
Color PrimitiveUI.Examples.PUIExampleCharts.yellow = new Color(1f, 0.92f, 0f) private
Definition at line 31 of file PUIExampleCharts.cs.
Referenced by PrimitiveUI.Examples.PUIExampleCharts.Draw().
The documentation for this class was generated from the following file:
Elin/Plugins.UI/PrimitiveUI/Examples/PUIExampleCharts.cs