Elin Decompiled Documentation: Card Class Reference
Card Class Reference
Public Types
enum MoveResult { Fail , Success , Door }
enum MoveType { Walk , Force }
Public Types inherited from IInspect
enum NoteMode { Default , Recipe , Product , Info }
Public Member Functions
override string ToString ()
bool CanReserve (AIAct act)
bool TryReserve (AIAct act)
void Mod ()
Window.SaveData GetWindowSaveData ()
bool IsExcludeFromCraft ()
void SetDirtyWeight ()
void ChangeWeight (int a)
int Evalue (int ele)
int Evalue (int ele, bool ignoreGlobalElement)
int EvalueMax (int ele, int min=0)
int Evalue (string alias)
bool HasTag (CTAG tag)
bool HasEditorTag (EditorTag tag)
void AddEditorTag (EditorTag tag)
void RemoveEditorTag (EditorTag tag)
virtual string GetName (NameStyle style, int num=-1)
virtual string GetExtraName ()
virtual string GetDetail ()
int GetBestAttribute ()
void ModExp (string alias, int a)
void ModExp (int ele, int a)
bool IsChildOf (Card c)
T FindTool< T > ()
string ReferenceId ()
void Create (string _id, int _idMat=-1, int genLv=-1)
virtual void OnBeforeCreate ()
virtual void OnCreate (int genLv)
virtual void SetSource ()
virtual void ApplyEditorTags (EditorTag tag)
void ApplyTrait ()
Card SetLv (int a)
void AddExp (int a)
void LevelUp ()
virtual void ApplyMaterialElements (bool remove)
virtual void ApplyMaterial (bool remove=false)
Card ChangeMaterial (int idNew, bool ignoreFixedMaterial=false)
Card ChangeMaterial (string idNew, bool ignoreFixedMaterial=false)
Card ChangeMaterial (SourceMaterial.Row row, bool ignoreFixedMaterial=false)
void SetReplica (bool on)
Thing Add (string id, int num=1, int lv=1)
Card AddCard (Card c)
void RemoveCard (Card c)
void NotifyAddThing (Thing t, int num)
Thing AddThing (string id, int lv=-1)
Thing AddThing (Thing t, bool tryStack=true, int destInvX=-1, int destInvY=-1)
void PurgeDuplicateArtifact (Thing af)
void RemoveThings ()
void RemoveThing (Thing thing)
bool ShouldTrySetDirtyInventory ()
virtual bool CanStackTo (Thing to)
bool TryStackTo (Thing to)
ICardParent GetRoot ()
Card GetRootCard ()
bool IsStackable (Thing tg)
Thing Duplicate (int num)
Thing Split (int a)
Thing SetNum (int a)
Thing SetNoSell ()
void ModNum (int a, bool notify=true)
void AddSocket ()
void ApplySocket (Thing t)
void ApplySocket (int id, int lv, Card mod=null)
void EjectSockets ()
SocketData AddRune (Card rune)
SocketData AddRune (int idEle, int v)
SocketData GetRuneEnc (int idEle)
int CountRune ()
int MaxRune ()
bool CanAddRune (SourceElement.Row row)
bool HasRune ()
void OnChildNumChange (Card c)
Card Install ()
void SetPlaceState (PlaceState newState, bool byPlayer=false)
int GetTotalQuality (bool applyBonus=true)
void ModEncLv (int a)
void SetEncLv (int a)
void SetTier (int a, bool setTraits=true)
virtual void SetBlessedState (BlessedState s)
virtual void ChangeRarity (Rarity q)
bool TryPay (int a, string id="money")
void SetCharge (int a)
void ModCharge (int a, bool destroy=false)
void ModCurrency (int a, string id="money")
int GetCurrency (string id="money")
virtual void HealHPHost (int a, HealSource origin=HealSource.None)
virtual void HealHP (int a, HealSource origin=HealSource.None)
virtual int GetArmorSkill ()
virtual int ApplyProtection (int dmg, int mod=100)
void DamageHP (int dmg, AttackSource attackSource=AttackSource.None, Card origin=null)
void DamageHP (int dmg, int ele, int eleP=100, AttackSource attackSource=AttackSource.None, Card origin=null, bool showEffect=true, Thing weapon=null)
virtual void Die (Element e=null, Card origin=null, AttackSource attackSource=AttackSource.None)
void Explode (Point p, Card origin)
void Deconstruct ()
void Destroy ()
void SpawnLoot (Card origin)
Thing TryMakeRandomItem (int lv=-1)
Card MakeFoodFrom (string _id)
Card MakeFoodFrom (Card c)
void MakeFoodRef (Card c1, Card c2=null)
string TryGetFoodName (Card c)
string GetFoodName (string s)
void MakeFigureFrom (string id)
void MakeRefFrom (string id)
void MakeRefFrom (Card c1, Card c2=null)
Card SetHidden (bool hide=true)
virtual MoveResult _Move (Point p, MoveType type=MoveType.Walk)
void MoveImmediate (Point p, bool focus=true, bool cancelAI=true)
void Teleport (Point point, bool silent=false, bool force=false)
virtual void OnLand ()
int ResistLvFrom (int ele)
int ResistLv (int res)
bool HasElement (int ele, int req=1)
bool HasElement (string id, int req=1)
bool HasGlobalElement (int ele)
virtual CardRenderer _CreateRenderer ()
void AddBlood (int a=1, int id=-1)
RenderParam GetRenderParam ()
virtual void SetRenderParam (RenderParam p)
void DyeRandom ()
void Dye (string idMat)
void Dye (SourceMaterial.Row mat)
void RefreshColor ()
ref Color GetRandomColor ()
virtual Sprite GetSprite (int dir=0)
virtual Sprite GetImageSprite ()
void SetImage (Image image, int dir, int idSkin=0)
virtual void SetImage (Image image)
void ShowEmo (Emo _emo=Emo.none, float duration=0f, bool skipSame=true)
void PlaySoundHold (bool spatial=true)
void PlaySoundDrop (bool spatial=true)
void PlaySoundImpact (bool spatial=true)
void PlaySoundDead (bool spatial=true)
SoundSource PlaySound (string id, float v=1f, bool spatial=true)
void KillAnime ()
void PlayAnime (AnimeID id, bool force=false)
void PlayAnime (AnimeID id, Point dest, bool force=false)
void PlayAnimeLoot ()
Effect PlayEffect (string id, bool useRenderPos=true, float range=0f, Vector3 fix=default(Vector3))
void PlayEffect (int ele, bool useRenderPos=true, float range=0f)
virtual void SetDir (int d)
void SetRandomDir ()
virtual void LookAt (Card c)
virtual void LookAt (Point p)
virtual void Rotate (bool reverse=false)
void ChangeAltitude (int a)
virtual SubPassData GetSubPassData ()
void SetFreePos (Point point)
void RenderMarker (Point point, bool active, HitResult result, bool main, int dir, bool useCurrentPosition=false)
void RecalculateFOV ()
bool HasLight ()
float GetLightPower ()
int GetSightRadius ()
int GetLightRadius ()
void CalculateFOV ()
void SetRandomLightColors ()
Fov CreateFov ()
void ClearFOV ()
virtual void OnSimulateHour (VirtualDate date)
void DecayNatural (int hour=1)
void CheckJustCooked ()
void Decay (int a=10)
bool HasTalk (string idTopic)
void Talk (string idTopic, string ref1=null, string ref2=null, bool forceSync=false)
void TalkRaw (string text, string ref1=null, string ref2=null, bool forceSync=false)
string ApplyNewLine (string text)
void SayRaw (string text, string ref1=null, string ref2=null)
void SayNothingHappans ()
void Say (string lang, string ref1=null, string ref2=null)
void Say (string lang, Card c1, Card c2, string ref1=null, string ref2=null)
void Say (string lang, Card c1, string ref1=null, string ref2=null)
string GetTalkText (string idTopic, bool stripPun=false, bool useDefault=true)
string ApplyTone (string text, bool stripPun=false)
void SetRandomTalk ()
void SetRandomTone ()
bool HasCraftBonusTrait ()
List< Element > ListCraftBonusTraits ()
void TryStack (Thing t)
void ApplyBacker (int bid)
void RemoveBacker ()
void SetPaintData ()
byte[] GetPaintData ()
void ClearPaintSprite ()
Sprite GetPaintSprite ()
void TryUnrestrain (bool force=false, Chara c=null)
TraitShackle GetRestrainer ()
virtual void Tick ()
Thing SetPriceFix (int a)
int GetEquipValue ()
void SetSale (bool sale)
int GetValue (PriceType priceType=PriceType.Default, bool sell=false)
virtual int GetPrice (CurrencyType currency=CurrencyType.Money, bool sell=false, PriceType priceType=PriceType.Default, Chara c=null)
virtual string GetHoverText ()
virtual string GetHoverText2 ()
int Dist (Card c)
int Dist (Point p)
bool IsInMutterDistance (int d=10)
void SetCensored (bool enable)
void SetDeconstruct (bool deconstruct)
virtual bool MatchEncSearch (string s)
virtual void SetSortVal (UIList.SortMode m, CurrencyType currency=CurrencyType.Money)
virtual int SecondaryCompare (UIList.SortMode m, Card c)
void ForeachFOV (Func< Point, bool > func)
void ForeachPoint (Action< Point, bool > action)
void OnInspect ()
virtual void WriteNote (UINote n, Action< UINote > onWriteNote=null, IInspect.NoteMode mode=IInspect.NoteMode.Default, Recipe recipe=null)
void Inspect ()
virtual bool HasCondition< T > ()
bool HaveFur ()
bool CanBeSheared ()
Public Member Functions inherited from BaseCard
bool GetBool (int id)
void SetBool (int id, bool enable)
int GetInt (int id, int? defaultInt=null)
void AddInt (int id, int value)
void SetInt (int id, int value=0)
string GetStr (int id, string defaultStr=null)
void SetStr (int id, string value=null)
T GetObj< T > (int id)
void SetObj (int id, object o)
T SetObj< T > (int id, object o)
ICardParent GetRoot ()
void RemoveCard (Card c)
void OnChildNumChange (Card c)
string ReferenceId ()
void WriteNote (UINote n, Action< UINote > onWriteNote=null, NoteMode mode=NoteMode.Default, Recipe recipe=null)
void OnInspect ()
Static Public Member Functions
static string ApplyTone (Chara c, ref string text, string _tones, int gender, bool stripPun=false)
static int GetTilePrice (TileRow row, SourceMaterial.Row mat)
Static Public Member Functions inherited from EClass
static int rndSeed (int a, int seed)
static int rnd (int a)
static int curve (int a, int start, int step, int rate=75)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Public Attributes
int[] _ints = new int[30]
string id = ""
ThingContainer things = new ThingContainer()
ElementContainerCard elements = new ElementContainerCard()
Biography bio
List< int > sockets
AIAct reservedAct
Props props
Trait trait
ICardParent parent
Fov fov
Point pos = new Point()
CardRenderer renderer
CardRow hat
int turn
int _colorInt
float roundTimer
float angle = 180f
float animeCounter
bool isDestroyed
CardBlueprint bp
BitArray32 _bits1
BitArray32 _bits2
PlaceState placeState
bool dirtyWeight = true
SourceMaterial.Row _material
Emo lastEmo
int sortVal
Public Attributes inherited from BaseCard
Dictionary< int, object > mapObj = new Dictionary<int, object>()
Dictionary< int, int > mapInt = new Dictionary<int, int>()
Dictionary< int, string > mapStr = new Dictionary<int, string>()
Static Public Attributes
const int MaxWeight = 10000000
Static Public Attributes inherited from EClass
static Core core
Protected Member Functions
virtual void OnSerializing ()
virtual void OnDeserialized ()
Properties
Card parentCard [get]
Thing parentThing [get]
int colorInt [get]
bool IsHotItem [get]
int uid [get, set]
int idMaterial [get, set]
int dir [get, set]
int Num [get, set]
int _x [get, set]
int _z [get, set]
int refVal [get, set]
int decay [get, set]
int altitude [get, set]
int hp [get, set]
float fx [get, set]
float fy [get, set]
BlessedState blessedState [get, set]
PlaceState _placeState [get, set]
int rarityLv [get, set]
Rarity rarity [get, set]
int encLV [get, set]
int posInvX [get, set]
int posInvY [get, set]
int idSkin [get, set]
int feat [get, set]
int LV [get, set]
int exp [get, set]
int tier [get, set]
bool isCensored [get, set]
bool isDeconstructing [get, set]
bool isDyed [get, set]
bool isModified [get, set]
bool isNew [get, set]
bool isPlayerCreation [get, set]
bool ignoreAutoPick [get, set]
bool freePos [get, set]
bool isHidden [get, set]
bool isOn [get, set]
bool isNPCProperty [get, set]
bool isRestrained [get, set]
bool isRoofItem [get, set]
bool isMasked [get, set]
bool disableAutoToggle [get, set]
bool isImported [get, set]
bool autoRefuel [get, set]
bool ignoreStackHeight [get, set]
bool isFloating [get, set]
bool isWeightChanged [get, set]
bool isFireproof [get, set]
bool isAcidproof [get, set]
bool isReplica [get, set]
bool isSummon [get, set]
bool isElemental [get, set]
bool isBroken [get, set]
bool isSubsetCard [get, set]
bool noSnow [get, set]
bool noMove [get, set]
bool isGifted [get, set]
bool isCrafted [get, set]
bool isLostProperty [get, set]
bool noShadow [get, set]
bool noSell [get, set]
bool isLeashed [get, set]
bool isStolen [get, set]
bool isSale [get, set]
bool isCopy [get, set]
bool isRestocking [get, set]
bool hasSpawned [get, set]
bool isBackerContent [get]
SourceBacker.Row sourceBacker [get]
BedType c_bedType [get, set]
int c_equippedSlot [get, set]
int c_lockLv [get, set]
Hostility c_originalHostility [get, set]
MinionType c_minionType [get, set]
int c_vomit [get, set]
bool c_wasInPcParty [get, set]
bool c_isImportant [get, set]
bool c_lockedHard [get, set]
bool c_revealLock [get, set]
bool c_isTrained [get, set]
bool c_isPrayed [get, set]
bool c_isDisableStockUse [get, set]
int c_lightColor [get, set]
Color LightColor [get]
int c_uidZone [get, set]
int c_uidRefCard [get, set]
int c_priceFix [get, set]
int c_priceAdd [get, set]
int c_priceCopy [get, set]
int c_fixedValue [get, set]
int c_dyeMat [get, set]
VisitorState visitorState [get, set]
RescueState c_rescueState [get, set]
BossType c_bossType [get, set]
int c_dateStockExpire [get, set]
int c_dateDeathLock [get, set]
int c_IDTState [get, set]
int c_charges [get, set]
int c_bill [get, set]
int c_invest [get, set]
int c_seed [get, set]
int c_allowance [get, set]
int c_fur [get, set]
int c_dateCooked [get, set]
int c_containerSize [get, set]
int c_weight [get, set]
int c_diceDim [get, set]
int c_indexContainerIcon [get, set]
int c_idMainElement [get, set]
int c_summonDuration [get, set]
int c_idBacker [get, set]
int c_uidMaster [get, set]
int c_ammo [get, set]
int c_daysWithGod [get, set]
string c_idPortrait [get, set]
string c_idRace [get, set]
string c_idJob [get, set]
string c_idTone [get, set]
string c_color [get, set]
string c_idTalk [get, set]
string c_idDeity [get, set]
string c_altName [get, set]
string c_altName2 [get, set]
string c_extraNameRef [get, set]
string c_refText [get, set]
string c_idRefName [get, set]
string c_idRidePCC [get, set]
string c_idAbility [get, set]
string c_context [get, set]
string c_idEditor [get, set]
string c_editorTags [get, set]
string c_editorTraitVal [get, set]
string c_idTrait [get, set]
string c_idRefCard [get, set]
string c_idRefCard2 [get, set]
string c_note [get, set]
UniqueData c_uniqueData [get, set]
Thing ammoData [get, set]
List< SocketData > socketList [get, set]
Thing c_copyContainer [get, set]
Window.SaveData c_windowSaveData [get, set]
CharaUpgrade c_upgrades [get, set]
CharaGenes c_genes [get, set]
List< int > c_corruptionHistory [get, set]
ContainerUpgrade c_containerUpgrade [get, set]
DNA c_DNA [get, set]
CharaList c_charaList [get, set]
byte[] c_textureData [get, set]
SourceMaterial.Row DyeMat [get]
int invX [get, set]
int invY [get, set]
CardRow refCard [get]
CardRow refCard2 [get]
int ExpToNext [get]
int DefaultLV [get]
int ChildrenWeight [get]
int ChildrenAndSelfWeight [get]
int ChildrenAndSelfWeightSingle [get]
virtual int SelfWeight [get]
virtual int WeightLimit [get]
SourceCategory.Row category [get]
SourceMaterial.Row material [get]
virtual string AliasMaterialOnCreate [get]
Cell Cell [get]
virtual Thing Thing [get]
virtual Chara Chara [get]
virtual bool isThing [get]
virtual bool isChara [get]
bool ExistsOnMap [get]
virtual bool isSynced [get]
bool IsContainer [get]
bool IsUnique [get]
bool IsPowerful [get]
bool IsImportant [get]
virtual SourcePref Pref [get]
virtual bool IsDeadOrSleeping [get]
virtual bool IsDisabled [get]
virtual bool IsMoving [get]
virtual bool flipX [get]
virtual bool IsAliveInCurrentZone [get]
virtual string actorPrefab [get]
virtual CardRow sourceCard [get]
virtual CardRow sourceRenderCard [get]
TileType TileType [get]
string Name [get]
string NameSimple [get]
string NameOne [get]
virtual bool IsPC [get]
bool _IsPC [get]
virtual bool IsPCC [get]
virtual bool IsPCParty [get]
virtual bool IsMinion [get]
virtual bool IsPCPartyMinion [get]
virtual bool IsPCFactionMinion [get]
virtual bool IsMultisize [get]
bool IsToolbelt [get]
bool IsLightsource [get]
bool IsEquipment [get]
bool IsFood [get]
bool IsInheritFoodTraits [get]
bool ShowFoodEnc [get]
bool IsWeapon [get]
bool IsEquipmentOrRanged [get]
bool IsEquipmentOrRangedOrAmmo [get]
bool IsMeleeWeapon [get]
bool IsRangedWeapon [get]
bool IsThrownWeapon [get]
bool IsAmmo [get]
bool IsAgent [get]
bool IsFurniture [get]
bool IsBlessed [get]
bool IsCursed [get]
bool IsRestrainedResident [get]
virtual bool IsPCFaction [get]
bool IsPCFactionOrMinion [get]
virtual bool IsGlobal [get]
virtual int MaxDecay [get]
bool IsDecayed [get]
bool IsRotting [get]
bool IsFresn [get]
virtual int MaxHP [get]
virtual int Power [get]
int FameLv [get]
virtual int[] Tiles [get]
virtual int PrefIndex [get]
bool IsVariation [get]
virtual int DV [get]
virtual int PV [get]
int HIT [get]
int DMG [get]
int STR [get]
int DEX [get]
int END [get]
int PER [get]
int LER [get]
int WIL [get]
int MAG [get]
int CHA [get]
int INT [get]
int LUC [get]
int W [get]
int H [get]
bool IsIdentified [get]
string TextRarity [get]
bool IsInstalled [get]
bool IsMale [get]
bool IsNegativeGift [get]
bool HasContainerSize [get]
Thing Tool [get]
virtual SourceMaterial.Row DefaultMaterial [get]
virtual bool HasHost [get]
int Quality [get]
int QualityLv [get]
LightData LightData [get]
CardRenderer HostRenderer [get]
bool ShouldShowMsg [get]
bool CanInspect [get]
string InspectName [get]
Point InspectPoint [get]
Vector3 InspectPosition [get]
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Properties inherited from IInspect
bool CanInspect [get]
string InspectName [get]
Point InspectPoint [get]
Vector3 InspectPosition [get]
Private Member Functions
void _OnSerializing (StreamingContext context)
void _OnDeserialized (StreamingContext context)
Private Attributes
int _childrenWeight
SourceCategory.Row _category
LightData _LightData
Sprite _paintSprite
Static Private Attributes
static Color _randColor
Detailed Description
Definition at line 10 of file Card.cs.
Member Enumeration Documentation
MoveResult
enum Card.MoveResult
Enumerator
Fail
Success
Door
Definition at line 12 of file Card.cs.
    {
        Fail,
        Success,
        Door
    }
MoveType
enum Card.MoveType
Enumerator
Walk
Force
Definition at line 19 of file Card.cs.
    {
        Walk,
        Force
    }
Member Function Documentation
_CreateRenderer()
virtual CardRenderer Card._CreateRenderer () inline virtual
Reimplemented in Chara.
Definition at line 5410 of file Card.cs.
    {
        renderer = new CardRenderer();
        renderer.SetOwner(this);
        return renderer;
    }
References CardRenderer.SetOwner().
Referenced by _OnDeserialized(), and Create().
_Move()
virtual MoveResult Card._Move (Point p, MoveType type = MoveType::Walk) inline virtual
Reimplemented in Chara.
Definition at line 5298 of file Card.cs.
    {
        EClass._map.MoveCard(p, this);
        if (isChara)
        {
            Chara.SyncRide();
        }
        return MoveResult.Success;
    }
References EClass._map, Map.MoveCard(), and Chara.SyncRide().
Referenced by Recipe.Build(), and ActThrow.Throw().
_OnDeserialized()
void Card._OnDeserialized (StreamingContext context) inline private
Definition at line 2591 of file Card.cs.
    {
        _bits1.SetInt(_ints[0]);
        _bits2.SetInt(_ints[2]);
        placeState = _placeState;
        pos.Set(_x, _z);
        SetSource();
        things.SetOwner(this);
        elements.SetOwner(this, applyFeat: false);
        OnDeserialized();
        ApplyTrait();
        ApplyMaterialElements(remove: false);
        _CreateRenderer();
        foreach (Thing thing in things)
        {
            thing.parent = this;
        }
        if (isThing && Num <= 0)
        {
            isDestroyed = true;
        }
    }
References _bits1, _bits2, _CreateRenderer(), _ints, _placeState, _x, _z, ApplyMaterialElements(), ApplyTrait(), elements, isDestroyed, isThing, Num, OnDeserialized(), placeState, pos, Point.Set(), BitArray32.SetInt(), ElementContainerCard.SetOwner(), ThingContainer.SetOwner(), SetSource(), and things.
_OnSerializing()
void Card._OnSerializing (StreamingContext context) inline private
Definition at line 2576 of file Card.cs.
    {
        _x = pos.x;
        _z = pos.z;
        _ints[0] = _bits1.ToInt();
        _ints[2] = _bits2.ToInt();
        _placeState = placeState;
        OnSerializing();
    }
References _bits1, _bits2, _ints, _placeState, _x, _z, OnSerializing(), placeState, pos, BitArray32.ToInt(), Point.x, and Point.z.
Add()
Thing Card.Add (string id, int num = 1, int lv = 1) inline
Definition at line 2927 of file Card.cs.
    {
        if (num == 0)
        {
            num = 1;
        }
        return AddCard(ThingGen.Create(id, -1, lv).SetNum(num)) as Thing;
    }
References AddCard(), ThingGen.Create(), SetNum(), and Thing.
Referenced by DropdownGrid.BuildIngredients(), ThingGen.CreateTreasureContent(), ZonePreEnterBout.Execute(), ThingContainer.FindStealable(), DramaOutcome.ListFelmeraBarter(), Props.ListThingStack(), CraftUtil.MakeDish(), Zone_TestRoom.OnGenerateMap(), TraitBaseContainer.Prespawn(), UIRecipeInfo.RefreshList(), SerializedCards.Restore(), SpawnLoot(), Zone.SpawnLostItems(), Player.TargetRanged(), and Map.TryShatter().
AddBlood()
void Card.AddBlood (int a = 1, int id = -1) inline
Definition at line 5417 of file Card.cs.
    {
        if (!EClass._zone.IsRegion)
        {
            for (int i = 0; i < a; i++)
            {
                EClass._map.AddDecal(pos.x + ((EClass.rnd(2) != 0) ? (EClass.rnd(3) - 1) : 0), pos.z + ((EClass.rnd(2) != 0) ? (EClass.rnd(3) - 1) : 0), (id == -1) ? (isChara ? Chara.race.blood : material.decal) : id);
            }
            PlaySound("blood");
        }
    }
References EClass._map, EClass._zone, Map.AddDecal(), Spatial.IsRegion, material, Chara.race, EClass.rnd(), Point.x, and Point.z.
Referenced by ConBleed.Tick().
AddCard()
Card Card.AddCard (Card c) inline
Definition at line 2936 of file Card.cs.
    {
        return AddThing(c as Thing);
    }
References AddThing().
Referenced by InvOwnerGene._OnProcess(), Add(), Player.AddInventory(), AI_Shopping.Buy(), Recipe.Craft(), Player.CreateEquip(), ThingGen.CreateTreasureContent(), Zone.Deactivate(), CharaBody.Equip(), ZonePreEnterEncounter.Execute(), TraitGodStatue.OnChangeMaterial(), InvOwner.OnDrag(), QuestFiamaLock.OnStart(), TraitMannequin.OnUse(), TraitBaseContainer.Prespawn(), TraitContainerCurrency.Prespawn(), TraitToolBelt.Prespawn(), TraitBaseContainer.PutChara(), FactionBranch.PutInMailBox(), CoreDebug.QuickStart(), GameDate.ShipPackages(), GameDate.ShipRandomPackages(), GrowSystem.TryPick(), LayerDragGrid.TryPutBack(), and FactionBranch.TryTrash().
AddEditorTag()
void Card.AddEditorTag (EditorTag tag) inline
Definition at line 2505 of file Card.cs.
    {
        c_editorTags = (c_editorTags.IsEmpty() ? tag.ToString() : (c_editorTags + "," + tag));
    }
References c_editorTags.
Referenced by Zone.Activate(), Player.CreateEquip(), ThingGen.CreateTreasureContent(), Zone_Nymelle.OnBeforeSimulate(), QuestDialog.OnDropReward(), Zone_DungeonPuppy.OnGenerateMap(), and CoreDebug.TestSpawn().
AddExp()
void Card.AddExp (int a) inline
Definition at line 2816 of file Card.cs.
    {
        if (!IsPC)
        {
            a *= 2;
            if (IsPCFaction)
            {
                a = a * Mathf.Clamp(100 + Chara.affinity.value / 10, 50, 200) / 100;
                if (EClass.game.principal.petFeatExp)
                {
                    a = a * (50 + EClass.game.principal.petFeatExpMtp * 50) / 100;
                }
            }
        }
        a = a * (100 + Evalue(1237) * 30) / 100;
        exp += a;
        while (exp >= ExpToNext)
        {
            exp -= ExpToNext;
            LevelUp();
        }
    }
References Chara.affinity, Evalue(), exp, ExpToNext, EClass.game, IsPC, IsPCFaction, LevelUp(), GamePrincipal.petFeatExp, Game.principal, and Affinity.value.
Referenced by Chara.GiveGift(), Player.MoveZone(), Player.OnAdvanceHour(), ElementContainerCard.OnLevelUp(), and CoreDebug.UpdateInput().
AddRune() [1/2]
SocketData Card.AddRune (Card rune) inline
Definition at line 3389 of file Card.cs.
    {
        return AddRune(rune.refVal, rune.encLV);
    }
References AddRune(), encLV, and refVal.
Referenced by InvOwnerMod._OnProcess(), AddRune(), and RecipeCard.Craft().
AddRune() [2/2]
SocketData Card.AddRune (int idEle, int v) inline
Definition at line 3394 of file Card.cs.
    {
        if (socketList == null)
        {
            socketList = new List<SocketData>();
        }
        SourceElement.Row row = EClass.sources.elements.map[idEle];
        SocketData socketData = new SocketData
        {
            idEle = idEle,
            value = v,
            type = SocketData.Type.Rune
        };
        socketList.Add(socketData);
        if (IsWeapon || !row.IsWeaponEnc)
        {
            elements.SetTo(idEle, v);
        }
        return socketData;
    }
References elements, SourceManager.elements, IsWeapon, SourceElement.Row.IsWeaponEnc, ElementContainer.SetTo(), socketList, and EClass.sources.
AddSocket()
void Card.AddSocket () inline
Definition at line 3332 of file Card.cs.
    {
        if (sockets == null)
        {
            sockets = new List<int>();
        }
        sockets.Add(0);
    }
References sockets.
Referenced by Thing.OnCreate().
AddThing() [1/2]
Thing Card.AddThing (string id, int lv = -1) inline
Definition at line 2950 of file Card.cs.
    {
        return AddThing(ThingGen.Create(id, -1, (lv == -1) ? LV : lv));
    }
References AddThing(), ThingGen.Create(), and LV.
Referenced by InvOwnerDeliver._OnProcess(), AddCard(), ThingContainer.AddCurrency(), AddThing(), SourceMaterial.Row.CreateByProduct(), FactionBranch.DailyOutcome(), Player.EquipTool(), InvOwner.ListInteractions(), Trait.OnBarter(), TraitBrewery.OnChildDecay(), DragItemCard.OnDragSpecial(), Affinity.OnGift(), InvOwner.OnShiftClick(), HotItemEQSet.Perform(), Chara.Pick(), InvOwner.Transaction.Process(), Religion.PunishTakeOver(), Map.PutAway(), InvOwner.PutBack(), CoreDebug.QuickStart(), AI_Idle.Run(), AI_PlayMusic.Run(), AI_Steal.Run(), CoreDebug.SetStartStockpile(), Thing.ShowSplitMenu(), Zone.TryAddThingInSharedContainer(), Zone.TryGenerateEvolved(), Map.TryShatter(), and ActionMode.UpdateInput().
AddThing() [2/2]
Thing Card.AddThing (Thing t, bool tryStack = true, int destInvX = -1, int destInvY = -1) inline
Definition at line 2955 of file Card.cs.
    {
        if (t.Num == 0 || t.isDestroyed)
        {
            Debug.LogWarning("tried to add destroyed thing:" + t.Num + "/" + t.isDestroyed + "/" + t?.ToString() + "/" + this);
            return t;
        }
        if (t.parent == this)
        {
            Debug.LogWarning("already child:" + t);
            return t;
        }
        if (things.Contains(t))
        {
            Debug.Log("already in the list" + t);
            return t;
        }
        _ = t.parent;
        _ = EClass._zone;
        bool flag = IsPC && t.GetRootCard() == EClass.pc;
        if (t.parent != null)
        {
            t.parent.RemoveCard(t);
        }
        if (t.trait.ToggleType == ToggleType.Fire && destInvY == 0)
        {
            t.trait.Toggle(on: false);
        }
        t.isMasked = false;
        t.ignoreAutoPick = false;
        t.parent = this;
        t.noShadow = false;
        t.isSale = false;
        if (t.IsContainer)
        {
            t.RemoveEditorTag(EditorTag.PreciousContainer);
        }
        t.invX = -1;
        if (destInvY == -1)
        {
            t.invY = 0;
        }
        if (t.IsUnique && t.HasTag(CTAG.godArtifact) && t.GetRootCard() is Chara { IsPCFactionOrMinion: not false })
        {
            PurgeDuplicateArtifact(t);
        }
        Thing thing = (tryStack ? things.TryStack(t, destInvX, destInvY) : t);
        if (t == thing)
        {
            things.Add(t);
            things.OnAdd(t);
        }
        if (thing == t && IsPC && EClass.core.IsGameStarted && EClass._map != null && parent == EClass.game.activeZone && pos.IsValid && !flag)
        {
            NotifyAddThing(t, t.Num);
        }
        if (t == thing && isThing && parent == EClass._zone && placeState != 0)
        {
            EClass._map.Stocked.Add(t);
        }
        SetDirtyWeight();
        if (ShouldTrySetDirtyInventory())
        {
            EClass.pc.SetDirtyWeight();
            LayerInventory.SetDirty(thing);
        }
        if (IsPC)
        {
            goto IL_029f;
        }
        if (IsContainer)
        {
            Card rootCard = GetRootCard();
            if (rootCard != null && rootCard.IsPC)
            {
                goto IL_029f;
            }
        }
        goto IL_0345;
        IL_0345:
        return thing;
        IL_029f:
        t.isNPCProperty = false;
        t.isGifted = false;
        int count = 0;
        HashSet<string> ings = EClass.player.recipes.knownIngredients;
        TryAdd(t);
        if (t.CanSearchContents)
        {
            t.things.Foreach(delegate(Thing _t)
            {
                TryAdd(_t);
            });
        }
        if (count > 0 && EClass.core.IsGameStarted)
        {
            Msg.Say((count == 1) ? "newIng" : "newIngs", count.ToString() ?? "");
        }
        goto IL_0345;
        void TryAdd(Thing a)
        {
            if (!ings.Contains(a.id))
            {
                ings.Add(a.id);
                count++;
                if (a.sourceCard.origin != null && !ings.Contains(a.sourceCard.origin.id))
                {
                    ings.Add(a.sourceCard.origin.id);
                }
            }
        }
    }
References EClass._map, EClass._zone, Game.activeZone, ActPlan.List.Add(), Props.Add(), Thing.CanSearchContents, EClass.core, Debug, ThingContainer.Foreach(), EClass.game, GetRootCard(), HasTag(), id, CardRow.id, IsContainer, isDestroyed, Core.IsGameStarted, IsPC, isThing, IsUnique, Point.IsValid, RecipeManager.knownIngredients, NotifyAddThing(), Num, ThingContainer.OnAdd(), CardRow.origin, parent, EClass.pc, placeState, EClass.player, pos, PurgeDuplicateArtifact(), Player.recipes, ICardParent.RemoveCard(), RemoveEditorTag(), Msg.Say(), LayerInventory.SetDirty(), SetDirtyWeight(), ShouldTrySetDirtyInventory(), Thing.sourceCard, Map.Stocked, things, Trait.Toggle(), Trait.ToggleType, ToString(), trait, and ThingContainer.TryStack().
ApplyBacker()
void Card.ApplyBacker (int bid) inline
Definition at line 6400 of file Card.cs.
    {
        ChangeRarity(Rarity.Normal);
        SourceBacker.Row row = EClass.sources.backers.map.TryGetValue(bid);
        if (row == null)
        {
            return;
        }
        c_idBacker = row.id;
        if (row.type == 4)
        {
            Chara.bio.SetGender(row.gender);
            Chara chara = Chara;
            Hostility hostility2 = (Chara.c_originalHostility = Hostility.Neutral);
            chara.hostility = hostility2;
        }
        if (row.type == 6)
        {
            Chara.bio.SetGender(row.gender);
            Chara.bio.SetPortrait(Chara);
            Chara.idFaith = row.deity.ToLower();
        }
        if (row.type == 4 || row.type == 5 || row.type == 7)
        {
            idSkin = ((row.skin == 0) ? EClass.rnd(sourceCard._tiles.Length) : row.skin);
            if (id == "putty_snow")
            {
                idSkin = 0;
            }
        }
        if (bid == 164)
        {
            Chara.EQ_ID("amulet_moonnight");
        }
    }
References RenderRow._tiles, SourceManager.backers, bio, SourceBacker.Row.deity, Chara.EQ_ID(), SourceBacker.Row.gender, SourceBacker.Row.id, EClass.rnd(), Biography.SetGender(), Biography.SetPortrait(), SourceBacker.Row.skin, EClass.sources, and SourceBacker.Row.type.
Referenced by BackerContentInspector.ContentCard.Apply(), Zone_Casino.OnActivate(), Chara.OnCreate(), TraitSpecialLantern.OnCreate(), SerializedCards.Restore(), and Zone.TrySpawnFollower().
ApplyEditorTags()
virtual void Card.ApplyEditorTags (EditorTag tag) inline virtual
Reimplemented in Chara.
Definition at line 2738 of file Card.cs.
    {
        switch (tag)
        {
        case EditorTag.Hidden:
            SetHidden();
            break;
        case EditorTag.Empty:
            RemoveThings();
            break;
        case EditorTag.IsOn:
            isOn = true;
            break;
        case EditorTag.IsOff:
            isOn = false;
            break;
        case EditorTag.NoSnow:
            noSnow = true;
            break;
        case EditorTag.Boss:
            EClass._zone.Boss = Chara;
            break;
        }
    }
References Chara, isOn, noSnow, RemoveThings(), and SetHidden().
Referenced by SerializedCards.Restore().
ApplyMaterial()
virtual void Card.ApplyMaterial (bool remove = false) inline virtual
Reimplemented in Thing.
Definition at line 2882 of file Card.cs.
    {
        _colorInt = 0;
    }
References _colorInt.
Referenced by ChangeMaterial(), and Create().
ApplyMaterialElements()
virtual void Card.ApplyMaterialElements (bool remove) inline virtual
Reimplemented in Thing.
Definition at line 2878 of file Card.cs.
    {
    }
Referenced by _OnDeserialized(), and ModEncLv().
ApplyNewLine()
string Card.ApplyNewLine (string text) inline
Definition at line 6199 of file Card.cs.
    {
        if (text.Contains("&"))
        {
            string text2 = "_comma".lang();
            text = text.Replace(text2 + " &", Environment.NewLine ?? "");
            text = text.Replace(text2 + "&", Environment.NewLine ?? "");
            text = text.Replace("&", Environment.NewLine ?? "");
        }
        return text;
    }
ApplyProtection()
virtual int Card.ApplyProtection (int dmg, int mod = 100) inline virtual
Definition at line 3785 of file Card.cs.
    {
        int armorSkill = GetArmorSkill();
        Element orCreateElement = elements.GetOrCreateElement(armorSkill);
        int num = PV + orCreateElement.Value + DEX / 10;
        int num2 = 1;
        int sides = 1;
        int bonus = 0;
        if (num > 0)
        {
            int num3 = num / 4;
            num2 = num3 / 10 + 1;
            sides = num3 / num2 + 1;
            bonus = 0;
            dmg = dmg * 100 / (100 + num);
        }
        int num4 = Dice.Roll(num2, sides, bonus, this);
        dmg -= num4 * mod / 100;
        if (dmg < 0)
        {
            dmg = 0;
        }
        return dmg;
    }
References DEX, elements, GetArmorSkill(), ElementContainer.GetOrCreateElement(), PV, and Dice.Roll().
Referenced by ActMelee.Attack().
ApplySocket() [1/2]
void Card.ApplySocket (int id, int lv, Card mod = null) inline
Definition at line 3349 of file Card.cs.
    {
        for (int i = 0; i < sockets.Count; i++)
        {
            if (sockets[i] == 0)
            {
                if (lv >= 100)
                {
                    lv = 99;
                }
                sockets[i] = id * 100 + lv;
                elements.ModBase(id, lv);
                mod?.Destroy();
                break;
            }
        }
    }
References elements, ElementContainer.ModBase(), and sockets.
ApplySocket() [2/2]
void Card.ApplySocket (Thing t) inline
Definition at line 3341 of file Card.cs.
    {
        if (t.trait is TraitMod traitMod && sockets != null)
        {
            ApplySocket(traitMod.source.id, traitMod.owner.encLV, traitMod.owner);
        }
    }
References ApplySocket(), sockets, and trait.
Referenced by InvOwnerMod._OnProcess(), ApplySocket(), and Thing.OnCreate().
ApplyTone() [1/2]
static string Card.ApplyTone (Chara c, ref string text, string _tones, int gender, bool stripPun = false) inline static
Definition at line 6284 of file Card.cs.
    {
        if (text.IsEmpty())
        {
            return text;
        }
        string[] array = _tones.IsEmpty("").Split('|');
        string key = array[0];
        string text2 = "";
        MOD.tones.Initialize();
        if (!Lang.setting.useTone || MOD.tones.list.Count == 0)
        {
            text2 = text.Replace("{", "").Replace("}", "");
        }
        else
        {
            if (array[0].IsEmpty())
            {
                key = "default";
            }
            if (MOD.tones.all.ContainsKey(key))
            {
                StringBuilder stringBuilder = MOD.tones.ApplyTone(key, ref text, gender);
                if (Lang.isJP && c != null && c.trait.EnableTone)
                {
                    if (array.Length >= 2)
                    {
                        stringBuilder.Replace("_toneI".lang(), array[1]);
                    }
                    if (array.Length >= 3)
                    {
                        stringBuilder.Replace("_toneYou".lang(), array[2]);
                    }
                }
                text2 = stringBuilder.ToString();
            }
            else
            {
                text2 = text.Replace("{", "").Replace("}", "");
            }
        }
        if (!stripPun || !Lang.setting.stripPuns)
        {
            return text2;
        }
        return text2.StripLastPun();
    }
References ExcelDataList.all, ToneDataList.ApplyTone(), TraitChara.EnableTone, ExcelDataList.Initialize(), Lang.isJP, ExcelDataList.list, Lang.setting, LangSetting.stripPuns, MOD.tones, Chara.trait, and LangSetting.useTone.
ApplyTone() [2/2]
string Card.ApplyTone (string text, bool stripPun = false) inline
Definition at line 6278 of file Card.cs.
    {
        text = GameLang.ConvertDrama(text, Chara);
        return ApplyTone(Chara, ref text, c_idTone, bio?.gender ?? 0, stripPun);
    }
References GameLang.ConvertDrama().
Referenced by Person.ApplyTone(), DramaCustomSequence.GetText(), and Quest.Parse().
ApplyTrait()
void Card.ApplyTrait () inline
Definition at line 2763 of file Card.cs.
    {
        string str = c_idTrait;
        if (str.IsEmpty())
        {
            if (sourceCard.trait.IsEmpty())
            {
                trait = (isChara ? new TraitChara() : new Trait());
            }
            else
            {
                trait = ClassCache.Create<Trait>("Trait" + sourceCard.trait[0], "Elin");
            }
        }
        else
        {
            trait = ClassCache.Create<Trait>(str, "Elin");
        }
        trait.SetOwner(this);
    }
References c_idTrait, isChara, Trait.SetOwner(), sourceCard, trait, and CardRow.trait.
Referenced by _OnDeserialized(), Create(), and SerializedCards.Restore().
CalculateFOV()
void Card.CalculateFOV () inline
Definition at line 5909 of file Card.cs.
    {
        int radius = GetLightRadius();
        if (radius == 0 || !IsAliveInCurrentZone || !EClass._zone.isStarted)
        {
            return;
        }
        float power = GetLightPower();
        if (IsPC)
        {
            if (Chara.held != null && Chara.held.GetLightRadius() > 0)
            {
                power += Chara.held.GetLightPower();
            }
            if (radius <= 2)
            {
                power = 0f;
            }
            foreach (Condition condition in Chara.conditions)
            {
                condition.OnCalculateFov(fov, ref radius, ref power);
            }
            if (power > EClass.scene.profile.global.playerLightPowerLimit)
            {
                power = EClass.scene.profile.global.playerLightPowerLimit;
            }
            power *= EClass.scene.profile.light.playerLightMod + (float)EClass.player.customLightMod * EClass.scene.profile.light.playerLightCustomMod;
            EClass.player.lightRadius = radius;
            EClass.player.lightPower = power;
        }
        if (fov == null)
        {
            fov = CreateFov();
        }
        fov.Perform(pos.x, pos.z, radius, power * 2f);
    }
References EClass._zone, Chara.conditions, Player.customLightMod, GetLightPower(), GetLightRadius(), SceneProfile.global, Chara.held, Zone.isStarted, SceneProfile.light, Player.lightPower, Player.lightRadius, Condition.OnCalculateFov(), Fov.Perform(), EClass.player, SceneLightProfile.playerLightCustomMod, Scene.profile, EClass.scene, Point.x, and Point.z.
Referenced by Map._AddCard(), TaskHarvest.OnCreateProgress(), and Map.RefreshFOV().
CanAddRune()
bool Card.CanAddRune (SourceElement::Row row) inline
Definition at line 3451 of file Card.cs.
    {
        if (category.slot == 0)
        {
            return false;
        }
        if (material.HasEnc(row.id))
        {
            return false;
        }
        if (!IsWeapon && row.IsWeaponEnc)
        {
            return false;
        }
        if (row.category == "resist")
        {
            foreach (Element item in elements.ListElements())
            {
                if (item.source.category == "resist" && (item.vBase != 0 || item.vSource != 0))
                {
                    return false;
                }
            }
        }
        return CountRune() < MaxRune();
    }
References category, CountRune(), elements, IsWeapon, item, ElementContainer.ListElements(), material, and MaxRune().
Referenced by InvOwnerMod.ShouldShowGuide().
CanBeSheared()
bool Card.CanBeSheared () inline
Definition at line 7244 of file Card.cs.
    {
        if (EClass._zone.IsUserZone)
        {
            return false;
        }
        if (!HaveFur() || c_fur < 0)
        {
            return false;
        }
        return true;
    }
References EClass._zone, and Zone.IsUserZone.
Referenced by TraitToolShears.GetHeldEmo(), AI_Shear.IsValidTC(), TCOrbitThing.RefreshAll(), and TraitToolShears.TrySetHeldAct().
CanReserve()
bool Card.CanReserve (AIAct act) inline
Definition at line 2392 of file Card.cs.
    {
        if (reservedAct != null && reservedAct != act)
        {
            return !reservedAct.IsRunning;
        }
        return true;
    }
References AIAct.IsRunning, and reservedAct.
Referenced by TryReserve().
CanStackTo()
virtual bool Card.CanStackTo (Thing to) inline virtual
Reimplemented in Thing.
Definition at line 3183 of file Card.cs.
    {
        return false;
    }
Referenced by TryStackTo().
ChangeAltitude()
void Card.ChangeAltitude (int a) inline
Definition at line 5691 of file Card.cs.
    {
        altitude += a;
        if (altitude < 0)
        {
            altitude = 0;
        }
        if (altitude > TileType.MaxAltitude)
        {
            altitude = TileType.MaxAltitude;
        }
    }
References TileType.MaxAltitude.
ChangeMaterial() [1/3]
Card Card.ChangeMaterial (int idNew, bool ignoreFixedMaterial = false) inline
Definition at line 2887 of file Card.cs.
    {
        return ChangeMaterial(EClass.sources.materials.map[idNew], ignoreFixedMaterial);
    }
References ChangeMaterial, SourceManager.materials, and EClass.sources.
Referenced by TraitGodStatue._OnUse(), ThingContainer.AddCurrency(), DNA.CopyDNA(), TraitCrafter.Craft(), RecipeCard.Craft(), SourceMaterial.Row.CreateByProduct(), ThingGen.CreateRawMaterial(), Trait.CreateStock(), FactionBranch.DailyOutcome(), Map.DropBlockComponent(), Recipe.DropIngredients(), Duplicate(), Zone.Generate(), FactionBranch.GenerateGarbage(), DNA.GenerateWithGene(), CoreDebug.GetOrCreateDebugContainer(), TaskHarvest.HarvestThing(), Map.MineFloor(), CraftUtil.MixIngredients(), RecipeCard.OnChangeIngredient(), TraitPowerStatue.OnCreate(), TaskHarvest.OnCreateProgress(), QuestFiamaLock.OnStart(), TraitGiftJure.OnUse(), TraitPowerStatue.OnUse(), ActEffect.Proc(), CoreDebug.QuickStart(), SerializedCards.Restore(), TraitAltar.SetDeity(), CoreDebug.Spawn(), SpawnLoot(), ActThrow.Throw(), and ActionMode.UpdateInput().
ChangeMaterial() [2/3]
Card Card.ChangeMaterial (SourceMaterial::Row row, bool ignoreFixedMaterial = false) inline
Definition at line 2897 of file Card.cs.
    {
        if (sourceCard.fixedMaterial && !ignoreFixedMaterial)
        {
            return this;
        }
        ApplyMaterial(remove: true);
        _material = row;
        idMaterial = row.id;
        decay = 0;
        dirtyWeight = true;
        Card rootCard = GetRootCard();
        if (rootCard != null && rootCard.IsPC)
        {
            GetRootCard().SetDirtyWeight();
        }
        if (isThing)
        {
            LayerInventory.SetDirty(Thing);
        }
        ApplyMaterial();
        return this;
    }
References _material, ApplyMaterial(), decay, dirtyWeight, RenderRow.fixedMaterial, GetRootCard(), idMaterial, IsPC, isThing, LayerInventory.SetDirty(), SetDirtyWeight(), and sourceCard.
ChangeMaterial() [3/3]
Card Card.ChangeMaterial (string idNew, bool ignoreFixedMaterial = false) inline
Definition at line 2892 of file Card.cs.
    {
        return ChangeMaterial(EClass.sources.materials.alias[idNew], ignoreFixedMaterial);
    }
References ChangeMaterial, SourceManager.materials, and EClass.sources.
ChangeRarity()
virtual void Card.ChangeRarity (Rarity q) inline virtual
Reimplemented in Chara.
Definition at line 3667 of file Card.cs.
    {
        rarity = q;
    }
References rarity.
Referenced by TaskHarvest.OnCreateProgress().
ChangeWeight()
void Card.ChangeWeight (int a) inline
Definition at line 2464 of file Card.cs.
    {
        c_weight = a;
        isWeightChanged = true;
        SetDirtyWeight();
    }
References c_weight, isWeightChanged, and SetDirtyWeight().
Referenced by TraitTent.OnChangePlaceState(), and Religion.Punish().
CheckJustCooked()
void Card.CheckJustCooked () inline
Definition at line 6038 of file Card.cs.
    {
        if (HasElement(757) && c_dateCooked <= EClass.world.date.GetRaw() - 120)
        {
            c_dateCooked = 0;
            elements.Remove(757);
        }
    }
References World.date, Date.GetRaw(), ElementContainer.Remove(), and EClass.world.
Referenced by Religion.GetOfferingValue(), and Affinity.OnGift().
ClearFOV()
void Card.ClearFOV () inline
Definition at line 5998 of file Card.cs.
    {
        if (fov != null && fov.lastPoints.Count != 0)
        {
            fov.Perform(pos.x, pos.z, 0);
        }
    }
References Fov.lastPoints, Fov.Perform(), Point.x, and Point.z.
Referenced by Map._RemoveCard().
ClearPaintSprite()
void Card.ClearPaintSprite () inline
Definition at line 6477 of file Card.cs.
    {
        if ((bool)_paintSprite)
        {
            UnityEngine.Object.Destroy(_paintSprite.texture);
            UnityEngine.Object.Destroy(_paintSprite);
            _paintSprite = null;
        }
    }
Referenced by LayerPixelPaint.SetCanvas().
CountRune()
int Card.CountRune () inline
Definition at line 3430 of file Card.cs.
    {
        int num = 0;
        if (socketList != null)
        {
            foreach (SocketData socket in socketList)
            {
                if (socket.type == SocketData.Type.Rune)
                {
                    num++;
                }
            }
        }
        return num;
    }
References socketList, and SocketData.type.
Referenced by CanAddRune(), and HasRune().
Create()
void Card.Create (string _id, int _idMat = -1, int genLv = -1) inline
Definition at line 2623 of file Card.cs.
    {
        if (CardBlueprint.current != null)
        {
            bp = CardBlueprint.current;
            CardBlueprint.current = null;
        }
        else
        {
            bp = CardBlueprint._Default;
        }
        id = _id;
        Num = 1;
        autoRefuel = true;
        EClass.game.cards.AssignUID(this);
        isNew = true;
        SetSource();
        OnBeforeCreate();
        if (sourceCard.quality != 0)
        {
            rarity = sourceCard.quality.ToEnum<Rarity>();
        }
        else if (bp.rarity != Rarity.Random)
        {
            rarity = bp.rarity;
        }
        else if (category.slot != 0 && category.slot != 45 && category.slot != 44)
        {
            if (EClass.rnd(10) == 0)
            {
                rarity = Rarity.Crude;
            }
            else if (EClass.rnd(10) == 0)
            {
                rarity = Rarity.Superior;
            }
            else if (EClass.rnd(80) == 0)
            {
                rarity = Rarity.Legendary;
            }
            else if (EClass.rnd(250) == 0)
            {
                rarity = Rarity.Mythical;
            }
        }
        if (rarity != 0 && category.tag.Contains("fixedRarity"))
        {
            rarity = Rarity.Normal;
        }
        LV = DefaultLV;
        if (bp.lv != -999)
        {
            LV = bp.lv;
        }
        if (id == "microchip")
        {
            Debug.Log(id + "/" + _idMat + "/" + sourceCard.fixedMaterial);
        }
        if (sourceCard.fixedMaterial)
        {
            _material = EClass.sources.materials.alias[AliasMaterialOnCreate];
        }
        else
        {
            bool flag = (bp != null && bp.fixedMat) || sourceCard.quality == 4 || sourceCard.tierGroup.IsEmpty();
            if (_idMat != -1)
            {
                _material = EClass.sources.materials.rows[_idMat];
            }
            else if (!flag)
            {
                if (sourceCard.tierGroup == "wood")
                {
                    Debug.Log(id);
                }
                _material = MATERIAL.GetRandomMaterial(genLv, sourceCard.tierGroup, bp.tryLevelMatTier);
            }
            else
            {
                _material = EClass.sources.materials.alias[AliasMaterialOnCreate];
            }
        }
        idMaterial = _material.id;
        things.SetOwner(this);
        elements.SetOwner(this, applyFeat: true);
        ApplyTrait();
        if (!bp.fixedQuality && trait.LevelAsQuality && (!EClass._zone.IsPCFaction || EClass.Branch.lv != 1) && EClass.debug.testThingQuality && EClass.rnd(2) == 0)
        {
            tier = Mathf.Clamp(EClass.rnd(5) + 1, 1, 3);
            LV = LV + tier * 10 + (LV - 1) * (125 + tier * 25) / 100;
        }
        ApplyMaterial();
        OnCreate(genLv);
        _CreateRenderer();
        trait.OnCreate(genLv);
        hp = MaxHP;
        if (HasTag(CTAG.hidden))
        {
            SetHidden();
        }
        isFloating = Pref.Float;
    }
References _CreateRenderer(), CardBlueprint._Default, _material, EClass._zone, AliasMaterialOnCreate, ApplyMaterial(), ApplyTrait(), CardManager.AssignUID(), autoRefuel, bp, EClass.Branch, Game.cards, category, CardBlueprint.current, EClass.debug, Debug, DefaultLV, elements, CardBlueprint.fixedMat, RenderRow.fixedMaterial, CardBlueprint.fixedQuality, SourcePref.Float, EClass.game, MATERIAL.GetRandomMaterial(), HasTag(), hp, idMaterial, isFloating, isNew, Zone.IsPCFaction, Trait.LevelAsQuality, LV, CardBlueprint.lv, FactionBranch.lv, SourceManager.materials, MaxHP, Num, OnBeforeCreate(), OnCreate(), Trait.OnCreate(), Pref, CardRow.quality, rarity, CardBlueprint.rarity, EClass.rnd(), SetHidden(), ElementContainerCard.SetOwner(), ThingContainer.SetOwner(), SetSource(), sourceCard, EClass.sources, CoreDebug.testThingQuality, things, tier, CardRow.tierGroup, trait, and CardBlueprint.tryLevelMatTier.
Referenced by CharaGen._Create(), and ThingGen._Create().
CreateFov()
Fov Card.CreateFov () inline
Definition at line 5951 of file Card.cs.
    {
        Fov fov = new Fov();
        int num = (trait.UseLightColor ? c_lightColor : 0);
        if (num != 0)
        {
            fov.r = (byte)(num / 1024);
            fov.g = (byte)(num % 1024 / 32);
            fov.b = (byte)(num % 32);
        }
        else if (LightData != null)
        {
            fov.r = (byte)(LightData.color.r * 16f);
            fov.g = (byte)(LightData.color.g * 16f);
            fov.b = (byte)(LightData.color.b * 16f);
        }
        else if (isChara)
        {
            fov.r = 0;
            fov.g = 0;
            fov.b = 0;
        }
        else
        {
            fov.r = 3;
            fov.g = 2;
            fov.b = 1;
        }
        if (isChara && Chara.held != null && Chara.held.GetLightRadius() > 0)
        {
            Fov fov2 = Chara.held.CreateFov();
            fov.r += fov2.r;
            fov.g += fov2.g;
            fov.b += fov2.b;
        }
        if (IsPC)
        {
            fov.isPC = true;
            foreach (Condition condition in Chara.conditions)
            {
                condition.OnCreateFov(fov);
            }
        }
        fov.limitGradient = IsPCParty && EClass.scene.profile.global.limitGradient;
        return fov;
    }
References Fov.b, LightData.color, Chara.conditions, CreateFov(), Fov.g, GetLightRadius(), SceneProfile.global, Chara.held, Condition.OnCreateFov(), Scene.profile, Fov.r, and EClass.scene.
Referenced by CreateFov().
DamageHP() [1/2]
void Card.DamageHP (int dmg, AttackSource attackSource = AttackSource::None, Card origin = null) inline
Definition at line 3810 of file Card.cs.
    {
        DamageHP(dmg, 0, 0, attackSource, origin);
    }
References DamageHP().
Referenced by Chara._Move(), ActMelee.Attack(), ActEffect.DamageEle(), DamageHP(), StatsMana.Mod(), StatsStamina.Mod(), TraitTrap.OnActivateTrap(), TaskCut.OnProgress(), Scene.OnUpdate(), TraitRope.OnUse(), DramaManager.ParseLine(), ActEffect.Poison(), ActEffect.Proc(), Religion.Punish(), Religion.PunishTakeOver(), AI_Idle.Run(), AI_PassTime.Run(), Chara.Stumble(), ConBleed.Tick(), ConBurning.Tick(), ConMiasma.Tick(), ConPoison.Tick(), and ConSuffocation.Tick().
DamageHP() [2/2]
void Card.DamageHP (int dmg, int ele, int eleP = 100, AttackSource attackSource = AttackSource::None, Card origin = null, bool showEffect = true, Thing weapon = null) inline
Definition at line 3815 of file Card.cs.
    {
        if (hp < 0)
        {
            return;
        }
        Element e;
        if (ele == 0 || ele == 926)
        {
            e = Element.Void;
            if (origin != null)
            {
                dmg = dmg * Mathf.Max(100 + origin.Evalue(93) / 2, 10) / 100;
            }
        }
        else
        {
            e = Element.Create(ele);
            if (attackSource != AttackSource.Condition && showEffect)
            {
                ActEffect.TryDelay(delegate
                {
                    PlayEffect(e.id, useRenderPos: true, 0.25f);
                    EClass.Sound.Play("atk_" + e.source.alias);
                });
            }
            if (!e.source.aliasRef.IsEmpty() && attackSource != AttackSource.ManaBackfire)
            {
                int num = ((origin != null) ? origin.Evalue(1238) : 0);
                if (attackSource == AttackSource.MagicSword)
                {
                    num += 2;
                }
                dmg = Element.GetResistDamage(dmg, Evalue(e.source.aliasRef), num);
                dmg = dmg * 100 / (100 + Mathf.Clamp(Evalue(961) * 5, -50, 200));
                dmg = dmg * Mathf.Max(100 - Evalue(93), 10) / 100;
            }
            switch (e.id)
            {
            case 910:
            {
                Chara chara2 = Chara;
                if (chara2 != null && chara2.isWet)
                {
                    dmg /= 3;
                }
                break;
            }
            case 912:
            {
                Chara chara = Chara;
                if (chara != null && chara.isWet)
                {
                    dmg = dmg * 150 / 100;
                }
                break;
            }
            }
        }
        if (origin != null && origin.isChara && origin.Chara.HasCondition<ConSupress>())
        {
            dmg = dmg * 2 / 3;
        }
        if (attackSource != AttackSource.Finish)
        {
            if (!IsPCFaction && LV > 50)
            {
                dmg = dmg * (100 - (int)Mathf.Min(80f, Mathf.Sqrt(LV - 50) * 2.5f)) / 100;
            }
            if (EClass.game.principal.enableDamageReduction && IsPCFaction)
            {
                int num2 = ((origin != null) ? origin.LV : EClass._zone.DangerLv);
                if (num2 > 50)
                {
                    dmg = dmg * (100 - (int)Mathf.Min(95f, Mathf.Sqrt(num2 - 50))) / 100;
                }
            }
            dmg = dmg * Mathf.Max(0, 100 - Evalue((e == Element.Void || e.id == 926) ? 55 : 56)) / 100;
            if (origin != null && origin.IsPC && EClass.player.codex.Has(id))
            {
                dmg = dmg * (100 + Mathf.Min(10, EClass.player.codex.GetOrCreate(id).weakspot)) / 100;
            }
            if (isChara && Chara.body.GetAttackStyle() == AttackStyle.Shield && elements.ValueWithoutLink(123) >= 5 && (e == Element.Void || e.id == 926))
            {
                dmg = dmg * 90 / 100;
            }
            if (Evalue(971) > 0)
            {
                dmg = dmg * 100 / Mathf.Clamp(100 + Evalue(971), 25, 1000);
            }
            if (HasElement(1305))
            {
                dmg = dmg * 90 / 100;
            }
            if (EClass.pc.HasElement(1207) && isChara)
            {
                int num3 = 0;
                int num4 = 0;
                foreach (Condition condition2 in Chara.conditions)
                {
                    if (condition2.Type == ConditionType.Buff)
                    {
                        num3++;
                    }
                    else if (condition2.Type == ConditionType.Debuff)
                    {
                        num4++;
                    }
                }
                if (IsPCParty)
                {
                    dmg = dmg * 100 / Mathf.Min(100 + num3 * 5, 120);
                }
                else
                {
                    dmg = dmg * Mathf.Min(100 + num4 * 5, 120) / 100;
                }
            }
            if (IsPCParty && EClass.pc.ai is GoalAutoCombat)
            {
                dmg = dmg * 100 / Mathf.Clamp(105 + EClass.pc.Evalue(135) / 10, 10, 110);
            }
            if (HasElement(1218) && attackSource != AttackSource.ManaBackfire && (hp > 0 || Evalue(1421) <= 0))
            {
                dmg = dmg * (1000 - Evalue(1218)) / 1000;
                if (dmg <= 0 && EClass.rnd(4) == 0)
                {
                    dmg++;
                }
            }
            if (dmg >= MaxHP / 10 && Evalue(68) > 0)
            {
                int num5 = MaxHP / 10;
                int num6 = dmg - num5;
                num6 = num6 * 100 / (200 + Evalue(68) * 10);
                dmg = num5 + num6;
            }
        }
        if (origin != null && origin.IsPC && EClass.pc.Evalue(654) > 0)
        {
            dmg = 0;
        }
        if (dmg < 0)
        {
            dmg = 0;
        }
        int num7 = Mathf.Clamp(dmg * 6 / MaxHP, 0, 4) + ((dmg > 0) ? 1 : 0);
        if (Evalue(1421) > 0)
        {
            int num8 = 0;
            int num9 = dmg;
            if (hp > 0)
            {
                num9 = dmg - hp;
                hp -= dmg;
                num8 += dmg;
                if (hp < 0 && Chara.mana.value >= 0)
                {
                    num8 += hp;
                    hp = 0;
                }
            }
            if (hp <= 0)
            {
                if (Evalue(1421) >= 2)
                {
                    num9 /= 2;
                }
                dmg = num9;
                if (Chara.mana.value > 0)
                {
                    num9 -= Chara.mana.value;
                    Chara.mana.value -= dmg;
                    num8 += dmg;
                }
                if (Chara.mana.value <= 0)
                {
                    hp -= num9;
                    num8 += num9;
                }
            }
            dmg = num8;
        }
        else
        {
            hp -= dmg;
        }
        if (isSynced && dmg != 0)
        {
            float ratio = (float)dmg / (float)MaxHP;
            Card c = ((parent is Chara) ? (parent as Chara) : this);
            ActEffect.TryDelay(delegate
            {
                c.PlayEffect("blood").SetParticleColor(EClass.Colors.matColors[material.alias].main).Emit(20 + (int)(30f * ratio));
                if (EClass.core.config.test.showNumbers || isThing)
                {
                    EClass.scene.damageTextRenderer.Add(this, c, dmg, e);
                }
            });
        }
        if (EClass.pc.ai is AI_PracticeDummy { IsRunning: not false } aI_PracticeDummy && aI_PracticeDummy.target == this && (origin == null || origin.IsPC))
        {
            aI_PracticeDummy.hit++;
            aI_PracticeDummy.totalDamage += dmg;
        }
        ZoneInstanceBout zoneInstanceBout = EClass._zone.instance as ZoneInstanceBout;
        bool flag = false;
        if (hp < 0 && Religion.recentWrath == null)
        {
            if (isRestrained && IsPCFaction && EClass._zone.IsPCFaction && (!IsPC || (Chara.ai is AI_Torture && Chara.ai.IsRunning)))
            {
                EvadeDeath();
                if (Chara.stamina.value > 0 && (EClass.rnd(2) == 0 || !IsPC))
                {
                    Chara.stamina.Mod(-1);
                }
            }
            else if (IsInstalled && pos.HasBlock && trait.IsDoor)
            {
                EvadeDeath();
            }
            else if (!trait.CanBeDestroyed)
            {
                EvadeDeath();
            }
            else if (HasEditorTag(EditorTag.Invulnerable) || (HasEditorTag(EditorTag.InvulnerableToMobs) && (origin == null || !origin.IsPCParty)))
            {
                EvadeDeath();
            }
            else if (isChara)
            {
                if (Chara.HasCondition<ConInvulnerable>())
                {
                    EvadeDeath();
                }
                else if (IsPC && EClass.debug.godMode)
                {
                    EvadeDeath();
                }
                else if (Chara.host != null || (weapon != null && weapon.HasElement(485)))
                {
                    EvadeDeath();
                    flag = true;
                }
                else if (zoneInstanceBout != null && (bool)LayerDrama.Instance)
                {
                    EvadeDeath();
                }
                else if (LayerDrama.IsActive() && IsPC)
                {
                    EvadeDeath();
                }
                else
                {
                    if (attackSource != AttackSource.Finish && IsPCParty && Chara.host == null)
                    {
                        if (EClass.pc.ai is GoalAutoCombat && !EClass.player.invlunerable && (EClass.pc.ai as GoalAutoCombat).listHealthy.Contains(Chara))
{
                            EClass.core.actionsNextFrame.Add(delegate
{
                                Msg.Say(IsPC ? "abort_damage" : "abort_damgeAlly");
                            });
                            EClass.player.invlunerable = true;
                            EClass.player.TryAbortAutoCombat();
                            EClass.pc.stamina.Mod(-EClass.pc.stamina.max / 5);
                        }
                        if (EClass.player.invlunerable)
{
                            EvadeDeath();
                            goto IL_0baa;
                        }
                    }
                    if (IsPC && Evalue(1220) > 0 && Chara.stamina.value >= Chara.stamina.max / 2)
                    {
                        Chara.stamina.Mod(-Chara.stamina.max / 2);
                        Chara.AddCondition<ConInvulnerable>();
                        EvadeDeath();
                    }
                }
            }
        }
        goto IL_0baa;
        IL_0baa:
        if (trait.CanBeAttacked)
        {
            renderer.PlayAnime(AnimeID.HitObj);
            hp = MaxHP;
            if (trait.CanBeSmashedToDeath)
            {
                hp = -1;
            }
        }
        Chara target;
        if (hp < 0)
        {
            if ((attackSource == AttackSource.Melee || attackSource == AttackSource.Range) && origin != null && (origin.isSynced || IsPC))
            {
                string text = "";
                if (IsPC && Lang.setting.combatTextStyle == 0)
                {
                    if (e != Element.Void && e != null)
                    {
                        text = "dead_" + e.source.alias;
                    }
                    if (text == "" || !LangGame.Has(text))
                    {
                        text = "dead_attack";
                    }
                    EClass.pc.Say(text, this, "");
                }
                else
                {
                    if (e != Element.Void && e != null)
                    {
                        text = "kill_" + e.source.alias;
                    }
                    if (text == "" || !LangGame.Has(text))
                    {
                        text = "kill_attack";
                    }
                    (IsPC ? EClass.pc : origin).Say(text, origin, this);
                }
            }
            if (isChara && Religion.recentWrath == null)
            {
                if (HasElement(1410) && !Chara.HasCooldown(1410))
                {
                    Chara.AddCooldown(1410);
                    Say("reboot", this);
                    PlaySound("reboot");
                    Chara.Cure(CureType.Boss);
                    hp = MaxHP / 3;
                    Chara.AddCondition<ConInvulnerable>();
                    return;
                }
                if (HasCondition<ConRebirth>())
                {
                    Say("rebirth", this);
                    hp = Mathf.Min(MaxHP * (int)(5f + Mathf.Sqrt(Chara.GetCondition<ConRebirth>().power)) / 100, MaxHP);
                    Chara.AddCondition<ConInvulnerable>();
                    Chara.RemoveCondition<ConRebirth>();
                    PlayEffect("revive");
                    PlaySound("revive");
                    return;
                }
                foreach (Chara chara3 in EClass._map.charas)
                {
                    if (Chara.IsFriendOrAbove(chara3) && chara3.HasElement(1408) && chara3.faith == EClass.game.religions.Healing && EClass.world.date.GetRawDay() != chara3.GetInt(58) && (!chara3.IsPCFaction || IsPCFaction))
                    {
                        Msg.alwaysVisible = true;
                        Msg.Say("layhand", chara3, this);
                        Msg.Say("pray_heal", this);
                        hp = MaxHP;
                        Chara.AddCondition<ConInvulnerable>();
                        PlayEffect("revive");
                        PlaySound("revive");
                        chara3.SetInt(58, EClass.world.date.GetRawDay());
                        return;
                    }
                }
            }
            if (zoneInstanceBout != null)
            {
                target = EClass._map.FindChara(zoneInstanceBout.uidTarget);
                if (target != null)
                {
                    if (IsPC)
                    {
                        EClass.pc.hp = 0;
                        Heal();
                        target.ShowDialog("_chara", "bout_lose");
                        return;
                    }
                    if (target == this)
                    {
                        hp = 0;
                        Heal();
                        target.ModAffinity(EClass.pc, 10);
                        target.ShowDialog("_chara", "bout_win");
                        return;
                    }
                }
            }
            if (!isDestroyed)
            {
                Die(e, origin, attackSource);
                if (trait.CanBeSmashedToDeath && !EClass._zone.IsUserZone)
                {
                    Rand.SetSeed(uid);
                    if (EClass.rnd(3) == 0 && !isCrafted && !isCopy)
                    {
                        string text2 = new int[18]
{
                            233, 235, 236, 236, 236, 1170, 1143, 1144, 727, 728,
                            237, 869, 1178, 1179, 1180, 1243, 1244, 1245
                        }.RandomItem().ToString();
                        if (EClass.rnd(10) == 0)
{
                            text2 = "casino_coin";
                        }
                        if (EClass.rnd(10) == 0)
{
                            text2 = "scratchcard";
                        }
                        if (EClass.rnd(3) == 0)
{
                            text2 = "money";
                        }
                        if (EClass.rnd(5) == 0)
{
                            text2 = "plat";
                        }
                        if (EClass.rnd(10) == 0)
{
                            text2 = "money2";
                        }
                        if (EClass.rnd(20) == 0 || EClass.debug.enable)
{
                            text2 = "medal";
                        }
                        EClass._zone.AddCard(ThingGen.Create(text2).SetNum((!(text2 == "money")) ? 1 : EClass.rndHalf(100)).SetHidden(hide: false), pos);
                    }
                    Rand.SetSeed();
                }
                ProcAbsorb();
                if (EClass.pc.Evalue(1355) > 0 && isChara && (IsPCFactionOrMinion || (origin != null && origin.IsPCParty)))
                {
                    ((EClass.pc.AddCondition<ConStrife>() as ConStrife) ?? EClass.pc.GetCondition<ConStrife>())?.AddKill(Chara);
                }
            }
            if (origin != null && origin.isChara)
            {
                if (origin.IsPCFactionOrMinion && isChara && !isCopy)
                {
                    EClass.player.stats.kills++;
                    EClass.game.quests.list.ForeachReverse(delegate(Quest q)
                    {
                        q.OnKillChara(Chara);
                    });
                    EClass.player.codex.AddKill(id);
                    if (Guild.Fighter.CanGiveContribution(Chara))
                    {
                        Guild.Fighter.AddContribution(5 + LV / 5);
                    }
                    if (Guild.Fighter.HasBounty(Chara))
                    {
                        int a2 = EClass.rndHalf(200 + LV * 20);
                        Msg.Say("bounty", Chara, a2.ToString() ?? "");
                        EClass.pc.ModCurrency(a2);
                        SE.Pay();
                    }
                }
                if (origin.GetInt(106) == 0)
                {
                    origin.Chara.TalkTopic("kill");
                }
            }
            Msg.SetColor();
        }
        else if ((attackSource == AttackSource.Melee || attackSource == AttackSource.Range) && origin != null)
        {
            (IsPC ? EClass.pc : origin).Say("dmgMelee" + num7 + (IsPC ? "pc" : ""), origin, this);
        }
        else if (isChara)
        {
            int num10 = ((attackSource != AttackSource.Condition && attackSource != AttackSource.WeaponEnchant) ? 1 : 2);
            if (num7 >= num10)
            {
                if (e != Element.Void)
                {
                    Say("dmg_" + e.source.alias, this);
                }
                if (e == Element.Void || num7 >= 2)
                {
                    Say("dmg" + num7, this);
                }
            }
        }
        if (isChara)
        {
            if (flag)
            {
                if (!Chara.HasCondition<ConFaint>())
                {
                    Chara.AddCondition<ConFaint>(200, force: true);
                }
                return;
            }
            if (origin != null && origin.IsAliveInCurrentZone && origin.isChara)
            {
                if (e.id == 916)
                {
                    origin.HealHP(Mathf.Clamp(EClass.rnd(dmg * (50 + eleP) / 500 + 5), 1, origin.MaxHP / 5 + EClass.rnd(10)));
                }
                if ((attackSource == AttackSource.Melee || attackSource == AttackSource.Range) && origin.Dist(this) <= 1)
                {
                    if (attackSource == AttackSource.Melee && HasElement(1221))
                    {
                        int ele2 = ((Chara.MainElement == Element.Void) ? 924 : Chara.MainElement.id);
                        if (id == "hedgehog_ether")
{
                            ele2 = 922;
                        }
                        Say("reflect_thorne", this, origin);
                        origin.DamageHP(Mathf.Clamp(dmg / 20, 1, MaxHP / 20), ele2, Power, AttackSource.Condition);
                    }
                    if (HasElement(1223))
                    {
                        int ele3 = ((Chara.MainElement == Element.Void) ? 923 : Chara.MainElement.id);
                        Say("reflect_acid", this, origin);
                        origin.DamageHP(Mathf.Clamp(dmg / 20, 1, MaxHP / 20), ele3, Power * 2, AttackSource.Condition);
                    }
                }
                ProcAbsorb();
            }
        }
        if (hp < 0 || !isChara)
        {
            return;
        }
        if (dmg > 0)
        {
            int a3 = (int)(100L * (long)(dmg * 100 / MaxHP) / 100) + 1;
            a3 = Mathf.Min(a3, Chara.isRestrained ? 15 : 200);
            if (a3 > 0)
            {
                elements.ModExp(GetArmorSkill(), a3);
                if (Chara.body.GetAttackStyle() == AttackStyle.Shield)
                {
                    elements.ModExp(123, a3);
                }
            }
        }
        int num11 = ((EClass.rnd(2) == 0) ? 1 : 0);
        if (attackSource == AttackSource.Condition)
        {
            num11 = 1 + EClass.rnd(2);
        }
        if (num11 > 0)
        {
            bool flag2 = Chara.HasCondition<ConPoison>() || ((e.id == 915 || e.id == 923) && ResistLv(Evalue(955)) < 4);
            AddBlood(num11, flag2 ? 6 : (-1));
        }
        bool flag3 = true;
        switch (e.id)
        {
        case 910:
            if (Chance(30 + eleP / 5, 100))
            {
                Chara.AddCondition<ConBurning>(eleP);
            }
            break;
        case 911:
            if (Chara.isWet)
            {
                if (Chance(30 + eleP / 10, 100))
                {
                    Chara.AddCondition<ConFreeze>(eleP);
                }
            }
            else if (Chance(50 + eleP / 10, 100))
            {
                Chara.AddCondition<ConWet>(eleP);
            }
            break;
        case 912:
            if (Chance(75 + eleP / 20, 100) && EClass.rnd(3) == 0)
            {
                Chara.AddCondition<ConParalyze>(1, force: true);
            }
            break;
        case 915:
            if (Chance(30 + eleP / 5, 100))
            {
                Chara.AddCondition<ConPoison>(eleP);
            }
            break;
        case 913:
            if (Chance(30 + eleP / 5, 100))
            {
                Chara.AddCondition<ConBlind>(eleP);
            }
            break;
        case 918:
            flag3 = false;
            if (Chance(30 + eleP / 5, 100))
            {
                Chara.AddCondition<ConParalyze>(eleP);
            }
            break;
        case 914:
            flag3 = false;
            if (EClass.rnd(3) != 0)
            {
                if (Chance(30 + eleP / 5, 100))
                {
                    Chara.AddCondition<ConConfuse>(eleP);
                }
            }
            else if (Chance(30 + eleP / 5, 100))
            {
                Chara.AddCondition<ConSleep>(eleP);
            }
            break;
        case 917:
            if (Chance(50 + eleP / 10, 100))
            {
                Chara.AddCondition<ConDim>(eleP);
            }
            break;
        case 925:
            if (EClass.rnd(3) == 0)
            {
                if (Chance(30 + eleP / 5, 100))
                {
                    Chara.AddCondition<ConDim>(eleP);
                }
            }
            else if (EClass.rnd(2) == 0)
            {
                if (EClass.rnd(3) == 0)
                {
                    Chara.AddCondition<ConParalyze>(1, force: true);
                }
            }
            else if (EClass.rnd(2) == 0)
            {
                Chara.AddCondition<ConConfuse>(1 + EClass.rnd(3), force: true);
            }
            break;
        case 920:
            flag3 = false;
            if (Chance(5 + eleP / 25, 40))
            {
                Chara.AddCondition<ConBlind>(eleP / 2);
            }
            if (Chance(5 + eleP / 25, 40))
            {
                Chara.AddCondition<ConParalyze>(eleP / 2);
            }
            if (Chance(5 + eleP / 25, 40))
            {
                Chara.AddCondition<ConConfuse>(eleP / 2);
            }
            if (Chance(5 + eleP / 25, 40))
            {
                Chara.AddCondition<ConPoison>(eleP / 2);
            }
            if (Chance(5 + eleP / 25, 40))
            {
                Chara.AddCondition<ConSleep>(eleP / 2);
            }
            if (Chance(5 + eleP / 25, 40))
            {
                Chara.AddCondition<ConDim>(eleP / 2);
            }
            if (Chance(30 + eleP / 10, 100))
            {
                Chara.SAN.Mod(EClass.rnd(2));
            }
            break;
        case 924:
            if (Chance(50 + eleP / 10, 100))
            {
                Chara.AddCondition<ConBleed>(eleP);
            }
            break;
        case 923:
            if (Chance(50 + eleP / 10, 100) && EClass.rnd(4) == 0)
            {
                ActEffect.Proc(EffectId.Acid, Chara);
            }
            break;
        case 922:
            Chara.ModCorruption(EClass.rnd(eleP / 50 + 10));
            break;
        }
        if (origin != null && origin.HasElement(1411) && !Chara.HasCondition<ConGravity>())
        {
            Condition.ignoreEffect = true;
            Chara.AddCondition<ConGravity>(2000);
            Condition.ignoreEffect = false;
        }
        if (Chara.conSleep != null && flag3)
        {
            Chara.conSleep.Kill();
        }
        if (IsPC)
        {
            float num12 = (float)hp / (float)MaxHP;
            if (Evalue(1421) > 0)
            {
                num12 = (float)Chara.mana.value / (float)Chara.mana.max;
            }
            if (num12 < 0.3f)
            {
                PlaySound("heartbeat", 1f - num12 * 2f);
            }
        }
        if (!IsPC && hp < MaxHP / 5 && Evalue(423) <= 0 && dmg * 100 / MaxHP + 10 > EClass.rnd(IsPowerful ? 400 : 150) && !HasCondition<ConFear>())
        {
            Chara.AddCondition<ConFear>(100 + EClass.rnd(100));
        }
        if (Chara.ai.Current.CancelWhenDamaged && attackSource != AttackSource.Hunger && attackSource != AttackSource.Fatigue)
        {
            Chara.ai.Current.TryCancel(origin);
        }
        if (Chara.HasCondition<ConWeapon>())
        {
            ConWeapon condition = Chara.GetCondition<ConWeapon>();
            if (e.source.aliasRef == condition.sourceElement.aliasRef)
            {
                condition.Mod(-1);
            }
        }
        if (Chara.HasElement(1222) && (dmg >= MaxHP / 10 || EClass.rnd(20) == 0))
        {
            ActEffect.Proc(EffectId.Duplicate, this);
        }
        if (hp < MaxHP / 3 && HasElement(1409) && !Chara.HasCooldown(1409))
        {
            Chara.AddCooldown(1409);
            Chara.AddCondition<ConBoost>(Power);
            Chara.Cure(CureType.Boss);
            Chara.HealHP(MaxHP / 2);
        }
        if (origin != null && origin.isChara && attackSource != AttackSource.Finish)
        {
            if (!AI_PlayMusic.ignoreDamage)
            {
                Chara.TrySetEnemy(origin.Chara);
            }
            if ((weapon == null || !weapon.HasElement(486)) && origin.Evalue(428) > 0 && !IsPCFactionOrMinion && EClass.rnd(dmg) >= EClass.rnd(MaxHP / 10) + MaxHP / 100 + 1)
            {
                origin.Chara.TryNeckHunt(Chara, origin.Evalue(428) * 20, harvest: true);
            }
        }
        bool Chance(int a, int max)
        {
            if (dmg > 0 || (origin != null && origin.HasElement(1345)))
            {
                return Mathf.Min(a, max) > EClass.rnd(100);
            }
            return false;
        }
        void EvadeDeath()
        {
            hp = 0;
            if (Evalue(1421) > 0 && isChara && Chara.mana.value < 0)
            {
                Chara.mana.value = 0;
            }
        }
        void Heal()
        {
            target.Cure(CureType.Death);
            foreach (Chara member in EClass.pc.party.members)
            {
                member.Cure(CureType.Death);
            }
        }
        void ProcAbsorb()
        {
            if (origin != null && origin.isChara && isChara && (weapon == null || !weapon.HasElement(486)))
            {
                int valueOrDefault = (origin.Evalue(662) + weapon?.Evalue(662, ignoreGlobalElement: true)).GetValueOrDefault();
                int valueOrDefault2 = (origin.Evalue(661) + weapon?.Evalue(661, ignoreGlobalElement: true)).GetValueOrDefault();
                if (valueOrDefault > 0 && attackSource == AttackSource.Melee && origin.isChara && !origin.Chara.ignoreSPAbsorb && Chara.IsHostile(origin as Chara))
                {
                    int num13 = EClass.rnd(3 + Mathf.Clamp(dmg / 100, 0, valueOrDefault / 10));
                    origin.Chara.stamina.Mod(num13);
                    if (IsAliveInCurrentZone)
                    {
                        Chara.stamina.Mod(-num13);
                    }
                }
                if (origin.HasElement(1350) && attackSource == AttackSource.Melee)
                {
                    int num14 = EClass.rndHalf(2 + Mathf.Clamp(dmg / 10, 0, origin.Chara.GetPietyValue() + 10));
                    origin.Chara.mana.Mod(num14);
                    if (IsAliveInCurrentZone)
                    {
                        Chara.mana.Mod(-num14);
                    }
                }
                if (valueOrDefault2 > 0 && attackSource == AttackSource.Melee)
                {
                    int num15 = EClass.rnd(2 + Mathf.Clamp(dmg / 10, 0, valueOrDefault2 + 10));
                    origin.Chara.mana.Mod(num15);
                    if (IsAliveInCurrentZone)
                    {
                        Chara.mana.Mod(-num15);
                    }
                }
            }
        }
    }
References EClass._zone, DamageTextRenderer.Add(), Chara.ai, Chara.body, Chara, Player.codex, EClass.Colors, Chara.conditions, Core.config, EClass.core, Element.Create(), Scene.damageTextRenderer, Zone.DangerLv, elements, Effect.Emit(), GamePrincipal.enableDamageReduction, Evalue(), EClass.game, CharaBody.GetAttackStyle(), CodexManager.GetOrCreate(), Element.GetResistDamage(), CodexManager.Has(), HasElement(), hp, Element.id, isChara, IsPCFaction, IsPCParty, isSynced, isThing, Chara.isWet, LV, Chara.mana, ColorProfile.matColors, material, MaxHP, parent, EClass.pc, PlayEffect(), EClass.player, Game.principal, EClass.rnd(), EClass.scene, Effect.SetParticleColor(), CoreConfig.Test.showNumbers, EClass.Sound, Element.source, CoreConfig.test, ActEffect.TryDelay(), BaseStats.Type, Stats.value, ElementContainer.ValueWithoutLink(), Element.Void, and CodexCreature.weakspot.
Decay()
void Card.Decay (int a = 10) inline
Definition at line 6047 of file Card.cs.
    {
        Card card = parent as Card;
        int num = 200;
        int num2 = MaxDecay / 4 * 3;
        if (a > 0)
        {
            if (card != null)
            {
                num = card.trait.DecaySpeedChild;
            }
            num = num * trait.DecaySpeed / 100;
            int num3 = Evalue(405);
            if (num3 != 0)
            {
                num = num * (100 - num3 * 2) / 100;
            }
            if (num < 0)
            {
                num = 0;
            }
        }
        else
        {
            num = 100;
        }
        a = a * num / 100;
        if (decay + a > MaxDecay)
        {
            if (card != null && !card.trait.OnChildDecay(this, !IsDecayed))
            {
                return;
            }
            if (!IsDecayed)
            {
                if (EClass.pc.HasElement(1325) && GetRootCard() is Chara && category.IsChildOf("food"))
                {
                    Thing thing = TraitSeed.MakeRandomSeed(enc: true).SetNum(Mathf.Min(Num, 3));
                    card.AddCard(thing);
                    if (!IsParentLocked())
                    {
                        GetRootCard().Say("seed_rot", GetRootCard(), this, thing.Name);
                    }
                    Destroy();
                    return;
                }
                if (parent == EClass._zone)
                {
                    Say("rot", this);
                }
                else if (GetRootCard() == EClass.pc)
                {
                    if (!IsParentLocked())
                    {
                        EClass.pc.Say("rotInv", this, EClass.pc);
                    }
                    LayerInventory.SetDirty(Thing);
                }
                if (IsFood)
                {
                    elements.ModBase(73, -10);
                }
            }
        }
        else if (decay < num2 && decay + a >= num2 && GetRootCard() == EClass.pc)
        {
            if (!IsParentLocked())
            {
                EClass.pc.Say("rottingInv", this, EClass.pc);
            }
            LayerInventory.SetDirty(Thing);
        }
        decay += a;
        bool IsParentLocked()
        {
            if (parent is Thing)
            {
                return (parent as Thing).c_lockLv > 0;
            }
            return false;
        }
    }
References EClass._zone, card, HasElement(), SourceCategory.Row.IsChildOf(), TraitSeed.MakeRandomSeed(), ElementContainer.ModBase(), Name, EClass.pc, Say(), LayerInventory.SetDirty(), and SetNum().
DecayNatural()
void Card.DecayNatural (int hour = 1) inline
Definition at line 6015 of file Card.cs.
    {
        if (!isNPCProperty)
        {
            things.ForeachReverse(delegate(Thing t)
            {
                t.DecayNatural(hour);
            });
            if (sourceCard._origin == "dish")
            {
                CheckJustCooked();
            }
            if (parent is Card && (parent as Card).trait.CanChildDecay(this))
            {
                Decay(10 * hour);
            }
            else if (!isChara && trait.Decay != 0)
            {
                Decay(trait.Decay * hour);
            }
        }
    }
References CardRow._origin, Trait.CanChildDecay(), Trait.Decay, and DecayNatural().
Referenced by DecayNatural(), Zone.OnSimulateHour(), and Zone.Simulate().
Deconstruct()
void Card.Deconstruct () inline
Definition at line 4674 of file Card.cs.
    {
        PlaySound(material.GetSoundDead(sourceCard));
        Destroy();
    }
References material.
Referenced by AI_Deconstruct.Run().
Destroy()
void Card.Destroy () inline
Definition at line 4680 of file Card.cs.
    {
        if (isDestroyed)
        {
            Debug.Log(Name + " is already destroyed.");
            return;
        }
        if (isChara)
        {
            if (IsPCFaction && !Chara.isSummon)
            {
                Debug.Log(this);
                return;
            }
            Chara.DropHeld();
            Chara.isDead = true;
            if (IsPCParty)
            {
                EClass.pc.party.RemoveMember(Chara);
            }
            if (IsGlobal)
            {
                EClass.game.cards.globalCharas.Remove(Chara);
            }
        }
        if (renderer.hasActor)
        {
            renderer.KillActor();
        }
        if (parent != null)
        {
            parent.RemoveCard(this);
        }
        for (int num = things.Count - 1; num >= 0; num--)
        {
            things[num].Destroy();
        }
        isDestroyed = true;
    }
References Game.cards, Debug, Chara.DropHeld(), EClass.game, CardManager.globalCharas, CardRenderer.hasActor, isSummon, CardRenderer.KillActor(), Chara.party, EClass.pc, CardManager.GlobalCharaList.Remove(), ICardParent.RemoveCard(), and Party.RemoveMember().
Referenced by InvOwnerDeliver._OnProcess(), InvOwnerGacha._OnProcess(), InvOwnerRecycle._OnProcess(), ActPlan._Update(), MapSubset.Apply(), PartialMap.Apply(), FactionBranch.BanishMember(), DramaOutcome.check_sketch(), Chara.ClearInventory(), ContentCodex.Collect(), TraitCrafter.Craft(), RecipeCard.CreateMold(), FactionBranch.DailyOutcome(), QuestDeliver.Deliver(), ThingContainer.DestroyAll(), Chara.DropThing(), Chara.EQ_CAT(), Chara.EQ_ID(), CoreDebug.Fix_RemoveDemitas(), DramaOutcome.give_sketch_special(), Chara.GiveGift(), Chara.GiveLovePotion(), ModNum(), TraitTrap.OnActivateTrap(), TraitBrewery.OnChildDecay(), Meeting.OnEndDrama(), Chara.OnGiveErohon(), Game.OnLoad(), TraitAltar.OnOffer(), AM_FlagCell.OnProcessTiles(), AI_Fish.ProgressFish.OnProgressComplete(), TaskDig.OnProgressComplete(), TraitFertilizer.OnSimulateHour(), Zone.OnSimulateHour(), TraitFarmChest.OnUse(), TraitScrollMapTreasure.OnUse(), TraitStairsLocked.OnUse(), TraitFoodMeat.OnUse(), DramaManager.ParseLine(), InvOwnerDeliver.PayBill(), ActEffect.Proc(), PurgeDuplicateArtifact(), Map.PutAway(), Trait.Refuel(), QuestEscort.ReleaseEscort(), RemoveBacker(), GameDate.ShipGoods(), ConSleep.SuccubusVisit(), ActThrow.Throw(), AI_PlayMusic.ThrowReward(), Zone.TryAddThing(), TraitSwitch.TryDisarmTrap(), Chara.TryPoisonPotion(), ActPray.TryPray(), AI_Shopping.TryRestock(), Map.TryShatter(), TraitSeed.TrySprout(), TryStackTo(), TraitFoodEgg.Update(), and ActionMode.UpdateInput().
Die()
virtual void Card.Die (Element e = null, Card origin = null, AttackSource attackSource = AttackSource::None) inline virtual
Reimplemented in Chara.
Definition at line 4613 of file Card.cs.
    {
        Card rootCard = GetRootCard();
        Point _pos = rootCard?.pos ?? pos;
        if (_pos != null && !_pos.IsValid)
        {
            _pos = null;
        }
        if (trait.EffectDead == EffectDead.Default && _pos != null)
        {
            _pos.PlaySound(material.GetSoundDead(sourceCard));
            _pos.PlayEffect("mine").SetParticleColor(material.GetColor()).Emit(10 + EClass.rnd(10));
            material.AddBlood(_pos, trait.CanBeSmashedToDeath ? (12 + EClass.rnd(8)) : 6);
            if (_pos.IsSync)
            {
                string text = ((rootCard != this) ? "destroyed_inv_" : "destroyed_ground_");
                if (e != null && LangGame.Has(text + e.source.alias))
                {
                    text += e.source.alias;
                }
                if (attackSource != AttackSource.Throw)
                {
                    Msg.Say(text, this, rootCard);
                }
            }
            else if (attackSource != AttackSource.Throw)
            {
                Msg.Say("destroyed", this);
            }
        }
        if (_pos != null && !EClass._zone.IsUserZone)
        {
            things.ForeachReverse(delegate(Thing t)
            {
                if (!(t.trait is TraitChestMerchant))
                {
                    EClass._zone.AddCard(t, _pos);
                }
            });
        }
        Destroy();
        if (e != null && _pos != null && e.id == 21)
        {
            EClass._zone.AddCard(ThingGen.Create((EClass.rnd(2) == 0) ? "ash" : "ash2"), _pos);
        }
        if (trait.ThrowType == ThrowType.Explosive)
        {
            Explode(pos, origin);
        }
    }
References EClass._zone, Zone.AddCard(), Trait.CanBeSmashedToDeath, ThingGen.Create(), Trait.EffectDead, Effect.Emit(), LangGame.Has(), Point.IsSync, Zone.IsUserZone, Point.IsValid, material, Point.PlayEffect(), Point.PlaySound(), pos, EClass.rnd(), Msg.Say(), Effect.SetParticleColor(), Trait.ThrowType, and trait.
Referenced by TaskHarvest.HarvestThing(), TraitDye.OnThrowGround(), AI_Slaughter.Run(), ActThrow.Throw(), and Map.TryShatter().
Dist() [1/2]
int Card.Dist (Card c) inline
Definition at line 7025 of file Card.cs.
    {
        if (!IsMultisize && !c.IsMultisize)
        {
            return pos.Distance(c.pos);
        }
        if (IsMultisize)
        {
            int dist = 99;
            ForeachPoint(delegate(Point p, bool main)
            {
                int num2 = DistMulti(p, c);
                if (num2 < dist)
                {
                    dist = num2;
                }
            });
            return dist;
        }
        return DistMulti(pos, c);
        static int DistMulti(Point p1, Card c)
        {
            if (!c.IsMultisize)
            {
                return p1.Distance(c.pos);
            }
            int dist2 = 99;
            c.ForeachPoint(delegate(Point p, bool main)
            {
                int num = p1.Distance(p);
                if (num < dist2)
                {
                    dist2 = num;
                }
            });
            return dist2;
        }
    }
References Point.Distance(), ForeachPoint(), IsMultisize, and pos.
Referenced by Chara._Move(), AM_Adv._OnUpdateInput(), ActPlan._Update(), ActMelee.Attack(), ActMelee.CanPerform(), ActRush.CanPerform(), ActSwarm.CanPerform(), Player.CanSee(), TraitDye.CanUse(), AM_MoveInstalled.CheckEnemyNearBy(), AI_Torture.CreateProgress(), ActionMode.DoFunc(), TaskCullLife.GetTarget(), ActorEx.GetVolume(), QuestManager.HasFarAwayEscort(), AI_OpenGambleChest.IsValid(), Point.ListCharasInRadius(), Chara.MoveByForce(), ActRanged.Perform(), ActRush.Perform(), PlaySound(), ActorEx.Refresh(), AI_ArmPillow.Run(), AI_Fish.Run(), AI_Fuck.Run(), AI_Idle.Run(), AI_Massage.Run(), AI_Shear.Run(), AI_Slaughter.Run(), AI_Steal.Run(), AI_TargetCard.Run(), GoalCombat.Run(), TaskClean.Run(), TaskCullLife.Run(), TaskDump.Run(), TaskWater.Run(), TraitDetector.Search(), SpawnLoot(), ConSleep.SuccubusVisit(), Player.TargetRanged(), ConChampagne.Tick(), ThingGen.TryLickChest(), and GoalCombat.TryUseAbility().
Dist() [2/2]
int Card.Dist (Point p) inline
Definition at line 7064 of file Card.cs.
    {
        return pos.Distance(p);
    }
References Point.Distance().
Duplicate()
Thing Card.Duplicate (int num) inline
Definition at line 3235 of file Card.cs.
    {
        Thing thing = ThingGen.Create(id);
        thing.ChangeMaterial(idMaterial, ignoreFixedMaterial: true);
        thing._bits1 = _bits1;
        thing._bits2 = _bits2;
        thing.dir = dir;
        thing.refVal = refVal;
        thing.altitude = altitude;
        thing.idSkin = idSkin;
        thing.blessedState = blessedState;
        thing.rarityLv = rarityLv;
        thing.tier = tier;
        thing.LV = LV;
        thing.exp = exp;
        thing.encLV = encLV;
        thing.decay = decay;
        thing.mapInt.Clear();
        thing.mapStr.Clear();
        foreach (KeyValuePair<int, int> item in mapInt)
        {
            thing.mapInt[item.Key] = item.Value;
        }
        foreach (KeyValuePair<int, string> item2 in mapStr)
        {
            thing.mapStr[item2.Key] = item2.Value;
        }
        elements.CopyTo(thing.elements);
        thing.SetNum(num);
        if (thing.IsRangedWeapon)
        {
            thing.sockets = IO.DeepCopy(sockets);
        }
        if (thing.c_containerSize != 0)
        {
            thing.things.SetOwner(thing);
        }
        return thing;
    }
References _bits1, _bits2, altitude, blessedState, c_containerSize, ChangeMaterial(), ElementContainer.CopyTo(), ThingGen.Create(), decay, dir, elements, encLV, exp, idMaterial, idSkin, IsRangedWeapon, item, LV, BaseCard.mapInt, BaseCard.mapStr, rarityLv, refVal, SetNum(), ThingContainer.SetOwner(), sockets, things, and tier.
Referenced by TraitCrafter.Craft(), Chara.Drink(), Trait.OnBarter(), TraitBrewery.OnChildDecay(), TraitBookSecret.OnRead(), AI_Read.OnSetOwner(), TraitPotionEmpty.OnUse(), AI_Read.Run(), and AM_MoveInstalled.SetTarget().
Dye() [1/2]
void Card.Dye (SourceMaterial::Row mat) inline
Definition at line 5453 of file Card.cs.
    {
        isDyed = mat != null;
        c_dyeMat = mat?.id ?? 0;
        _colorInt = 0;
    }
Dye() [2/2]
void Card.Dye (string idMat) inline
Definition at line 5448 of file Card.cs.
    {
        Dye(EClass.sources.materials.alias[idMat]);
    }
References Dye, SourceManager.materials, and EClass.sources.
Referenced by TraitCrafter.Craft(), RecipeCard.Craft(), Trait.CreateStock(), TraitDye.Dye(), RecipeCard.OnChangeIngredient(), TraitToolWaterPot.OnCreate(), TaskDrawWater.OnCreateProgress(), TaskHarvest.OnCreateProgress(), TaskPourWater.OnCreateProgress(), TraitMannequin.OnUse(), CoreDebug.QuickStart(), SerializedCards.Restore(), and ActionMode.UpdateInput().
DyeRandom()
void Card.DyeRandom () inline
Definition at line 5443 of file Card.cs.
    {
        Dye(EClass.sources.materials.rows.Where((SourceMaterial.Row r) => r.matColor.r != r.matColor.g || r.matColor.g != r.matColor.b || r.matColor.b != r.matColor.r).RandomItem().alias);
    }
References Dye, SourceManager.materials, and EClass.sources.
Referenced by Trait.OnBarter(), Chara.OnCreate(), Game.OnLoad(), and TraitPlamoBox.OnUse().
EjectSockets()
void Card.EjectSockets () inline
Definition at line 3367 of file Card.cs.
    {
        for (int i = 0; i < sockets.Count; i++)
        {
            int num = sockets[i];
            if (num != 0)
            {
                Thing thing = ThingGen.Create(isCopy ? "ash3" : "mod_ranged");
                int ele = num / 100;
                int num2 = num % 100;
                elements.ModBase(ele, -num2);
                if (!isCopy)
                {
                    thing.refVal = ele;
                    thing.encLV = num2;
                }
                EClass._map.TrySmoothPick(pos.IsBlocked ? EClass.pc.pos : pos, thing, EClass.pc);
                sockets[i] = 0;
            }
        }
    }
References EClass._map, ThingGen.Create(), elements, Point.IsBlocked, isCopy, ElementContainer.ModBase(), EClass.pc, pos, sockets, and Map.TrySmoothPick().
Referenced by TaskHarvest.HarvestThing().
Evalue() [1/3]
int Card.Evalue (int ele) inline
Definition at line 2471 of file Card.cs.
    {
        return elements.Value(ele);
    }
References elements, and ElementContainer.Value().
Referenced by Chara._Move(), TraitAltar._OnOffer(), AM_Adv._OnUpdateInput(), ActPlan._Update(), Element._WriteNote(), AddExp(), GameDate.AdvanceDay(), GrowSystem.ApplySeed(), ActMelee.Attack(), RecipeCard.Build(), RecipeCard.BuildIngredientList(), Chara.CalcCastingChance(), AttackProcess.CalcHit(), RecipeManager.CanCeomUpWithRecipe(), ActNTR.CanPerform(), RecipeManager.ComeUpWithRecipe(), TraitCrafter.Craft(), RecipeCard.Craft(), Dice.Create(), ActEffect.DamageEle(), DamageHP(), Player.DreamSpell(), CharaBody.Equip(), Party.EValue(), Chara.FindNewEnemy(), TraitBaseSpellbook.GetActDuration(), Party.GetBestSkill(), HomeResourceEducation.GetDestValue(), HomeResourceSafety.GetDestValue(), TraitCrafter.GetDuration(), Hobby.GetEfficiency(), TraitDrinkMilkMother.GetHeldEmo(), DNA.GetInvalidFeat(), Hobby.GetLv(), CharaBody.GetMeleeDistance(), Ability.GetPower(), Recipe.GetQualityBonus(), AttackProcess.GetRawDamage(), RecipeSource.GetSPCost(), ElementContainer.GetSpellExp(), LayerTravel.GetTravelHours(), RecipeManager.GetUnlearnedRecipe(), AttackProcess.GetWeaponEnc(), GoalAutoCombat.GoalAutoCombat(), HealHP(), TraitFoodEggFertilized.Incubate(), Quest.Init(), CalcMoney.Invest(), Chara.IsCriticallyWounded(), Religion.LeaveFaith(), LevelUp(), RecipeCard.MakeDish(), AI_Fish.Makefish(), TraitSeed.MakeSeed(), MaxRune(), CraftUtil.MixIngredients(), StatsStamina.Mod(), CalcMoney.Negotiate(), Player.OnAdvanceDay(), Player.OnAdvanceHour(), Trait.OnBarter(), TraitDrinkMilkMother.OnDrink(), AI_Fish.ProgressFish.OnProgress(), RecipeManager.OnSleep(), TraitFloorSwitch.OnStepped(), Affinity.OnTalkRumor(), TraitItemProc.OnUse(), RaceBonus.OnWriteNote(), ActRanged.Perform(), ActZap.Perform(), AttackProcess.Perform(), AttackProcess.Prepare(), FoodEffect.Proc(), Religion.Punish(), Religion.PunishTakeOver(), WindowCharaMini.Refresh(), WindowChara.RefreshNote(), WindowChara.RefreshSkill(), Chara.RefreshSpeed(), Chara.RequestProtection(), Dice.Roll(), AI_Fuck.Run(), AI_Idle.Run(), AI_OpenGambleChest.Run(), AI_PassTime.Run(), AI_PlayMusic.Run(), AI_Steal.Run(), AI_UseCrafter.Run(), ActWait.Search(), Player.SelectDomain(), QuestSupplySpecific.SetIdThing(), Map.SetObj(), BaseTaskHarvest.SetTarget(), SpawnLoot(), Chara.Stumble(), ConSleep.SuccubusVisit(), Chara.Tick(), TraitSwitch.TryDisarmTrap(), Religion.TryGetGift(), Trait.TryOpenLock(), ActPray.TryPray(), TraitBaseSpellbook.TryProgress(), ActRanged.TryReload(), HotItemHeld.TrySetAct(), TraitSwitch.TrySetAct(), TraitEcoMark.TrySetHeldAct(), GoalCombat.TryUseAbility(), ElementContainerCard.ValueBonus(), and Element.BonusInfo.WriteNote().
Evalue() [2/3]
int Card.Evalue (int ele, bool ignoreGlobalElement) inline
Definition at line 2476 of file Card.cs.
    {
        if (!ignoreGlobalElement || !HasGlobalElement(ele))
        {
            return elements.Value(ele);
        }
        return 0;
    }
References elements, HasGlobalElement(), and ElementContainer.Value().
Evalue() [3/3]
int Card.Evalue (string alias) inline
Definition at line 2490 of file Card.cs.
    {
        return elements.Value(EClass.sources.elements.alias[alias].id);
    }
References elements, SourceManager.elements, EClass.sources, and ElementContainer.Value().
EvalueMax()
int Card.EvalueMax (int ele, int min = 0) inline
Definition at line 2485 of file Card.cs.
    {
        return Mathf.Max(elements.Value(ele), min);
    }
References elements, and ElementContainer.Value().
Referenced by Chara._Move(), StatsMana.Mod(), and AttackProcess.Prepare().
Explode()
void Card.Explode (Point p, Card origin) inline
Definition at line 4664 of file Card.cs.
    {
        ActEffect.ProcAt(EffectId.Explosive, 100, blessedState, this, null, p, isNeg: true, new ActRef
        {
            origin = origin?.Chara,
            refThing = Thing,
            aliasEle = "eleImpact"
        });
    }
References ActEffect.ProcAt().
FindTool< T >()
T Card.FindTool< T > () inline
Type Constraints
T : Trait
Definition at line 2566 of file Card.cs.
                                   : Trait
    {
        if (IsPC)
        {
            return Tool?.trait as T;
        }
        return things.Find<T>()?.trait as T;
    }
References ThingContainer.Find(), IsPC, things, Tool, and trait.
ForeachFOV()
void Card.ForeachFOV (Func< Point, bool > func) inline
Definition at line 7174 of file Card.cs.
    {
        if (fov == null)
        {
            return;
        }
        foreach (KeyValuePair<int, byte> lastPoint in fov.lastPoints)
        {
            Point arg = new Point().Set(lastPoint.Key);
            if (func(arg))
            {
                break;
            }
        }
    }
References Fov.lastPoints, and Point.Set().
ForeachPoint()
void Card.ForeachPoint (Action< Point, bool > action) inline
Definition at line 7190 of file Card.cs.
    {
        if (IsMultisize)
        {
            pos.ForeachMultiSize(W, H, action);
        }
        else
        {
            action(pos, arg2: true);
        }
    }
References Point.ForeachMultiSize().
Referenced by Map._AddCard(), Map._RemoveCard(), RecipeCard.Build(), Act.CanPerform(), Player.CanSee(), Dist(), UIInspector.DrawHighlight(), TraitBoat.GetWaterMat(), AM_MoveInstalled.OnProcessTiles(), TaskDump.Run(), and SetPlaceState().
GetArmorSkill()
virtual int Card.GetArmorSkill () inline virtual
Reimplemented in Chara.
Definition at line 3780 of file Card.cs.
    {
        return 0;
    }
Referenced by ApplyProtection().
GetBestAttribute()
int Card.GetBestAttribute () inline
Definition at line 2530 of file Card.cs.
    {
        int num = 1;
        foreach (Element item in elements.dict.Values.Where((Element a) => Element.List_MainAttributesMajor.Contains(a.id)))
        {
            int num2 = item.Value;
            if (isChara && Chara.tempElements != null)
            {
                num2 -= Chara.tempElements.Value(item.id);
            }
            if (num2 > num)
            {
                num = num2;
            }
        }
        return num;
    }
References ElementContainer.dict, elements, Element.id, isChara, item, Element.List_MainAttributesMajor, Chara.tempElements, and ElementContainer.Value().
Referenced by AI_Fuck.Finish().
GetCurrency()
int Card.GetCurrency (string id = "money") inline
Definition at line 3722 of file Card.cs.
    {
        if (id == "influence")
        {
            return EClass._zone.influence;
        }
        int sum = 0;
        SourceMaterial.Row mat = null;
        things.GetCurrency(id, ref sum, mat);
        return sum;
    }
References EClass._zone, ThingContainer.GetCurrency(), Spatial.influence, and things.
Referenced by PartialMap.Apply(), UICurrency.Build(), WidgetStatsBar.Build(), HitSummary.CanExecute(), AI_Fuck.Finish(), InvOwner.GetTextDetail(), InvOwner.Transaction.IsValid(), Faction.OnAdvanceMonth(), ListPeopleBuySlave.OnInstantiate(), ListPeopleRevive.OnInstantiate(), ButtonElement.Refresh(), LayerTravel.Refresh(), UIRecipeInfo.RefreshBalance(), LayerDragGrid.RefreshCost(), LayerHome.RefreshFeat(), LayerQuestBoard.RefreshHire(), UIInventory.RefreshList(), WindowChara.RefreshProfile(), AI_Idle.Run(), LayerMiniGame.Run(), TryPay(), and Faction.TryPayBill().
GetDetail()
virtual string Card.GetDetail () inline virtual
Definition at line 2525 of file Card.cs.
    {
        return sourceCard.GetText("detail", returnNull: true);
    }
References SourceData< T, T2 >.BaseRow.GetText(), and sourceCard.
GetEquipValue()
int Card.GetEquipValue () inline
Definition at line 6577 of file Card.cs.
    {
        return GetValue();
    }
Referenced by Chara.GetBestRangedWeapon(), and Chara.ShouldEquip().
GetExtraName()
virtual string Card.GetExtraName () inline virtual
Reimplemented in Thing.
Definition at line 2520 of file Card.cs.
    {
        return "";
    }
Referenced by Act.GetTextSmall().
GetFoodName()
string Card.GetFoodName (string s) inline
Definition at line 5264 of file Card.cs.
    {
        return s.Replace("_corpseFrom".lang(), "_corpseTo".lang());
    }
GetHoverText()
virtual string Card.GetHoverText () inline virtual
Reimplemented in Chara, and Thing.
Definition at line 7015 of file Card.cs.
    {
        return Name + GetExtraName();
    }
GetHoverText2()
virtual string Card.GetHoverText2 () inline virtual
Reimplemented in Chara.
Definition at line 7020 of file Card.cs.
    {
        return "";
    }
GetImageSprite()
virtual Sprite Card.GetImageSprite () inline virtual
Reimplemented in Chara.
Definition at line 5531 of file Card.cs.
    {
        return null;
    }
Referenced by HotItemThing.GetSprite().
GetLightPower()
float Card.GetLightPower () inline
Definition at line 5816 of file Card.cs.
    {
        float num = (isChara ? EClass.scene.profile.light.fovCurveChara.Evaluate(EClass.scene.timeRatio) : EClass.scene.profile.global.fovPower);
        if (LightData != null)
        {
            return 0.01f * LightData.color.a * 256f * 1.12f;
        }
        if (IsPCFaction && !IsPC)
        {
            num *= 4f;
        }
        return num;
    }
References SceneLightProfile.fovCurveChara, SceneProfile.global, SceneProfile.light, Scene.profile, EClass.scene, and Scene.timeRatio.
Referenced by CalculateFOV().
GetLightRadius()
int Card.GetLightRadius () inline
Definition at line 5839 of file Card.cs.
    {
        if (isThing)
        {
            if (!IsInstalled && EClass.pc.held != this)
            {
                return 0;
            }
            if (trait is TraitLightSource && Thing.isEquipped)
            {
                return (trait as TraitLightSource).LightRadius;
            }
            if (LightData == null || !trait.IsLightOn)
            {
                return 0;
            }
            return LightData.radius;
        }
        int num = ((LightData != null) ? LightData.radius : 0);
        int num2 = 0;
        if (IsPC)
        {
            if (Chara.isBlind)
            {
                return 1;
            }
            num = ((EClass._map.IsIndoor || EClass.world.date.IsNight) ? 2 : ((EClass.world.date.periodOfDay == PeriodOfDay.Day) ? 6 : 5));
            num2 = 2;
        }
        else
        {
            if (!EClass.core.config.graphic.drawAllyLight)
            {
                return 0;
            }
            if (LightData == null && !EClass._map.IsIndoor && !EClass.world.date.IsNight)
            {
                return 0;
            }
        }
        if (IsPCFaction)
        {
            Thing equippedThing = Chara.body.GetEquippedThing(45);
            if (equippedThing != null && equippedThing.trait is TraitLightSource traitLightSource)
            {
                num2 = traitLightSource.LightRadius;
            }
            if (Chara.held != null && IsPC)
            {
                int lightRadius = Chara.held.GetLightRadius();
                if (lightRadius > 0)
                {
                    if (lightRadius > num2)
                    {
                        num2 = Chara.held.GetLightRadius() - 1;
                    }
                    if (num2 < 3)
                    {
                        num2 = 3;
                    }
                }
            }
            if (num < num2)
            {
                num = num2;
            }
        }
        return num;
    }
References EClass._map, Chara.body, Core.config, EClass.core, World.date, CoreConfig.GraphicSetting.drawAllyLight, CharaBody.GetEquippedThing(), GetLightRadius(), CoreConfig.graphic, Chara.held, Chara.isBlind, Thing.isEquipped, Map.IsIndoor, Trait.IsLightOn, Date.IsNight, EClass.pc, Date.periodOfDay, LightData.radius, trait, and EClass.world.
Referenced by CalculateFOV(), CreateFov(), GetLightRadius(), and Chara.HoldCard().
GetName()
virtual string Card.GetName (NameStyle style, int num = -1) inline virtual
Reimplemented in Thing, and Chara.
Definition at line 2515 of file Card.cs.
    {
        return "Card";
    }
Referenced by InvOwnerBlend._OnProcess(), MakeRefFrom(), AI_Eat.Run(), AI_Read.Run(), and SecondaryCompare().
GetPaintData()
byte[] Card.GetPaintData () inline
Definition at line 6459 of file Card.cs.
    {
        Sprite sprite = GetSprite();
        Texture2D texture2D = ScreenCapture.CaptureScreenshotAsTexture();
        int num = sprite.texture.width * 2;
        int num2 = sprite.texture.height * 2;
        int x = (int)Mathf.Clamp(Input.mousePosition.x - (float)(num / 2), 1f, texture2D.width - num - 1);
        int y = (int)Mathf.Clamp(Input.mousePosition.y - (float)(num2 / 2), 1f, texture2D.height - num2 - 1);
        Color[] pixels = texture2D.GetPixels(x, y, num, num2);
        Texture2D texture2D2 = new Texture2D(num, num2, TextureFormat.ARGB32, mipChain: false);
        texture2D2.SetPixels(pixels);
        texture2D2.Apply();
        byte[] result = texture2D2.EncodeToJPG();
        UnityEngine.Object.Destroy(texture2D);
        UnityEngine.Object.Destroy(texture2D2);
        return result;
    }
References Color.
Referenced by AM_Paint.OnUpdateInput().
GetPaintSprite()
Sprite Card.GetPaintSprite () inline
Definition at line 6487 of file Card.cs.
    {
        if (!_paintSprite)
        {
            byte[] data = c_textureData;
            Texture2D texture2D = new Texture2D(1, 1);
            texture2D.LoadImage(data);
            _paintSprite = Sprite.Create(texture2D, new Rect(0f, 0f, texture2D.width, texture2D.height), new Vector2(0.5f, 0.5f), 200f);
            EClass.game.loadedTextures.Add(texture2D);
            if (trait is TraitCanvas traitCanvas)
            {
                texture2D.filterMode = ((!traitCanvas.PointFilter) ? FilterMode.Bilinear : FilterMode.Point);
            }
        }
        return _paintSprite;
    }
References EClass.game, and Game.loadedTextures.
Referenced by TraitCanvas.OnSetCardGrid(), CardActor.RefreshSprite(), and LayerPixelPaint.SetCanvas().
GetPrice()
virtual int Card.GetPrice (CurrencyType currency = CurrencyType::Money, bool sell = false, PriceType priceType = PriceType::Default, Chara c = null) inline virtual
Definition at line 6676 of file Card.cs.
    {
        if (!sell)
        {
            if (id == "littleball")
            {
                return 0;
            }
            switch (currency)
            {
            case CurrencyType.Ecopo:
                if (id == "plat")
                {
                    return 500;
                }
                break;
            case CurrencyType.Plat:
            {
                string text = id;
                if (!(text == "lucky_coin"))
                {
                    if (!(text == "book_skill"))
                    {
                        break;
                    }
                    return 50;
                }
                return 100;
            }
            case CurrencyType.Medal:
                switch (id)
                {
                case "bill_tax":
                    return 3;
                case "water":
                    return 3;
                case "bill":
                    return 3;
                case "1165":
                    return 10;
                case "diary_sister":
                    return 12;
                case "diary_lady":
                    return 25;
                case "diary_catsister":
                    return 85;
                case "container_magic":
                    return 20;
                case "wrench_tent_elec":
                    return 3;
                case "wrench_tent_soil":
                    return 3;
                case "wrench_bed":
                    return 3;
                case "wrench_storage":
                    return 4;
                case "wrench_fridge":
                    return 15;
                case "wrench_extend_v":
                    return 6;
                case "wrench_extend_h":
                    return 6;
                case "monsterball":
                    return LV / 8;
                }
                break;
            }
        }
        if (sell && noSell)
        {
            return 0;
        }
        if (!sell && id == "casino_coin")
        {
            return 20;
        }
        int value = GetValue(priceType, sell);
        if (value == 0)
        {
            return 0;
        }
        if (c == null)
        {
            c = EClass.pc;
        }
        double p = value;
        Trait trait = this.trait;
        if (!(trait is TraitBed))
        {
            if (trait is TraitContainer traitContainer)
            {
                p *= 1f + 4f * (float)(things.width - traitContainer.Width) + 4f * (float)(things.height - traitContainer.Height);
            }
        }
        else
        {
            p *= 1f + 0.5f * (float)c_containerSize;
        }
        p += c_priceAdd;
        if (c_priceFix != 0)
        {
            p = (int)((float)p * (float)Mathf.Clamp(100 + c_priceFix, 0, 1000000) / 100f);
            if (p == 0.0)
            {
                return 0;
            }
        }
        if (isStolen)
        {
            if (sell && priceType == PriceType.PlayerShop && EClass.Branch != null && EClass.Branch.policies.IsActive(2824))
            {
                p = p * 100.0 / (double)Mathf.Max(110f, 170f - Mathf.Sqrt(EClass.Branch.Evalue(2824) * 5));
            }
            else if (sell && Guild.Thief.IsMember)
            {
                p = Guild.Thief.SellStolenPrice((int)p);
            }
            else
            {
                p *= 0.5;
            }
        }
        if (!sell && category.id == "spellbook")
        {
            p = Guild.Mage.BuySpellbookPrice((int)p);
        }
        bool flag = priceType == PriceType.CopyShop;
        int num = ((!flag) ? 1 : 5);
        float num2 = Mathf.Min(0.01f * (float)Evalue(752), 1f);
        float num3 = Mathf.Min(0.01f * (float)Evalue(751), 1f);
        float num4 = Mathf.Min(0.02f * (float)Evalue(759), 2f);
        if (num3 > 0f)
        {
            num3 *= (float)num;
        }
        float num5 = Mathf.Clamp(1f + num2 + num3, 0.5f, 5f) + num4;
        p *= num5;
        p *= 0.20000000298023224;
        if (sell)
        {
            p *= 0.20000000298023224;
            if (isCopy)
            {
                p *= 0.20000000298023224;
            }
            if (currency == CurrencyType.Money && (category.IsChildOf("meal") || category.IsChildOf("preserved")))
            {
                p *= 0.5;
            }
            if ((uint)(priceType - 1) <= 1u)
            {
                if (category.IsChildOf("fish"))
                {
                    p *= ((EClass.pc.faith == EClass.game.religions.Luck) ? 1.5f : 1f);
                }
                if (category.IsChildOf("vegi") || category.IsChildOf("fruit"))
                {
                    p *= ((EClass.pc.faith == EClass.game.religions.Harvest) ? 3f : 2f);
                }
            }
        }
        if (id == "rod_wish")
        {
            p *= (sell ? 0.01f : 50f);
        }
        switch (currency)
        {
        case CurrencyType.Ecopo:
            if (this.trait is TraitSeed)
            {
                p *= 2.0;
            }
            else if (this.trait is TraitEcoMark)
            {
                p *= 1.0;
            }
            else
            {
                p *= 0.20000000298023224;
            }
            break;
        case CurrencyType.Casino_coin:
            p *= 0.10000000149011612;
            break;
        case CurrencyType.Influence:
            p *= 0.0020000000949949026;
            break;
        case CurrencyType.Medal:
            p *= 0.00019999999494757503;
            break;
        case CurrencyType.Money2:
            p *= 0.004999999888241291;
            break;
        default:
            if (IsIdentified || (this.trait is TraitErohon && !sell))
            {
                if (blessedState == BlessedState.Blessed)
                {
                    p *= 1.25;
                }
                else if (blessedState <= BlessedState.Cursed)
                {
                    p *= (flag ? 1.25f : 0.3f);
                }
                if (this.trait.HasCharges)
                {
                    p = p * 0.05000000074505806 + p * (double)(0.5f + Mathf.Clamp(0.1f * (float)c_charges, 0f, 1.5f));
                }
                if (IsDecayed)
                {
                    p *= (flag ? 0.9f : 0.5f);
                }
            }
            else
            {
                Rand.UseSeed(uid, delegate
                {
                    p = (sell ? (1 + EClass.rnd(15)) : (50 + EClass.rnd(500)));
                });
            }
            if (!sell)
            {
                p *= 1f + 0.2f * (float)c.Evalue(1406);
            }
            break;
        }
        float num6 = Math.Clamp(Mathf.Sqrt(c.EvalueMax(291) + ((!sell && EClass._zone.IsPCFaction) ? (EClass.Branch.Evalue(2800) * 2) : 0)), 0f, 25f);
        switch (priceType)
        {
        case PriceType.Tourism:
            num6 = 0f;
            break;
        case PriceType.Shipping:
            if (sell)
            {
                p *= 1.100000023841858;
            }
            break;
        case PriceType.PlayerShop:
        {
            if (!sell)
            {
                break;
            }
            float num7 = 1.25f;
            if (EClass.Branch != null)
            {
                if (EClass.Branch.policies.IsActive(2817))
                {
                    num7 += 0.1f + 0.01f * Mathf.Sqrt(EClass.Branch.Evalue(2817));
                }
                if (EClass.Branch.policies.IsActive(2816))
                {
                    num7 += 0.2f + 0.02f * Mathf.Sqrt(EClass.Branch.Evalue(2816));
                }
                if (isChara)
                {
                    if (EClass.Branch.policies.IsActive(2828))
                    {
                        num7 += 0.1f + 0.01f * Mathf.Sqrt(EClass.Branch.Evalue(2828));
                    }
                }
                else if (category.IsChildOf("food") || category.IsChildOf("drink"))
                {
                    if (EClass.Branch.policies.IsActive(2818))
                    {
                        num7 += 0.05f + 0.005f * Mathf.Sqrt(EClass.Branch.Evalue(2818));
                    }
                }
                else if (category.IsChildOf("furniture"))
                {
                    if (EClass.Branch.policies.IsActive(2819))
                    {
                        num7 += 0.05f + 0.005f * Mathf.Sqrt(EClass.Branch.Evalue(2819));
                    }
                }
                else if (EClass.Branch.policies.IsActive(2820))
                {
                    num7 += 0.05f + 0.005f * Mathf.Sqrt(EClass.Branch.Evalue(2820));
                }
            }
            p *= num7;
            break;
        }
        }
        if ((uint)currency > 1u)
        {
            num6 = 0f;
        }
        p *= (sell ? (1f + num6 * 0.02f) : (1f - num6 * 0.02f));
        if (sell)
        {
            p = EClass.curve((int)p, 10000, 10000, 80);
        }
        if (p < 1.0)
        {
            p = ((!sell) ? 1 : 0);
        }
        if (!sell)
        {
            if (currency == CurrencyType.Casino_coin)
            {
                if (p > 100000.0)
                {
                    p = Mathf.CeilToInt((float)p / 100000f) * 100000;
                }
                else if (p > 10000.0)
                {
                    p = Mathf.CeilToInt((float)p / 10000f) * 10000;
                }
                else if (p > 1000.0)
                {
                    p = Mathf.CeilToInt((float)p / 1000f) * 1000;
                }
                else if (p > 100.0)
                {
                    p = Mathf.CeilToInt((float)p / 100f) * 100;
                }
                else if (p > 10.0)
                {
                    p = Mathf.CeilToInt((float)p / 10f) * 10;
                }
            }
            if (this.trait is TraitDeed)
            {
                p *= Mathf.Pow(2f, EClass.player.flags.landDeedBought);
            }
        }
        if (p > (double)(sell ? 500000000 : 1000000000))
        {
            if (!sell)
            {
                return 1000000000;
            }
            return 500000000;
        }
        return (int)p;
    }
References EClass._zone, EClass.Branch, GuildMage.BuySpellbookPrice(), currency, EClass.curve(), FactionBranch.Evalue(), Player.flags, EClass.game, ReligionManager.Harvest, Trait.HasCharges, ThingContainer.height, SourceCategory.Row.id, PolicyManager.IsActive(), SourceCategory.Row.IsChildOf(), Guild.IsMember, Zone.IsPCFaction, Player.Flags.landDeedBought, ReligionManager.Luck, Guild.Mage, EClass.pc, EClass.player, FactionBranch.policies, Game.religions, EClass.rnd(), GuildThief.SellStolenPrice(), Guild.Thief, Rand.UseSeed(), and ThingContainer.width.
Referenced by InvOwnerRecycle._OnProcess(), AI_Shopping.Buy(), TraitSalesTag.CanTagSale(), Chara.ClearInventory(), ZonePreEnterBoutWin.Execute(), QuestSupply.GetBonus(), QuestSupplySpecific.GetBonus(), Thing.GetName(), Chara.GetName(), TraitTicketFurniture.GetPrice(), HomeResourceWorth.GetPrice(), ShopTransaction.GetPrice(), InvOwner.ListInteractions(), Trait.OnBarter(), Affinity.OnGift(), ShopTransaction.Process(), UIInventory.RefreshList(), PartialMap.Save(), GameDate.ShipGoods(), and TraitSalesTag.TrySetHeldAct().
GetRandomColor()
ref Color Card.GetRandomColor () inline
Definition at line 5495 of file Card.cs.
    {
        int num = EClass.game.seed + refVal;
        num += id[0] % 10000;
        if (id.Length > 1)
        {
            num += id[1] % 1000;
            if (id.Length > 2)
            {
                num += id[2] % 1000;
                if (id.Length > 3)
                {
                    num += id[3] % 1000;
                    if (id.Length > 4)
                    {
                        num += id[4] % 1000;
                    }
                }
            }
        }
        Rand.UseSeed(num, delegate
        {
            _randColor = EClass.sources.materials.rows[EClass.rnd(90)].matColor;
        });
        return ref _randColor;
    }
References SourceManager.materials, EClass.rnd(), EClass.sources, and Rand.UseSeed().
GetRenderParam()
RenderParam Card.GetRenderParam () inline
Definition at line 5429 of file Card.cs.
    {
        RenderParam shared = RenderParam.shared;
        shared.color = 11010048f;
        shared.liquidLv = 0;
        shared.cell = null;
        SetRenderParam(shared);
        return shared;
    }
References RenderParam.shared.
Referenced by EffectIRenderer.OnUpdate().
GetRestrainer()
TraitShackle Card.GetRestrainer () inline
Definition at line 6540 of file Card.cs.
    {
        foreach (Card item in pos.ListCards())
        {
            if (item.trait is TraitShackle && item.c_uidRefCard == uid)
            {
                return item.trait as TraitShackle;
            }
        }
        return null;
    }
References item, and Point.ListCards().
Referenced by BaseTileMap.DrawTile().
GetRoot()
ICardParent Card.GetRoot () inline
Implements ICardParent.
Definition at line 3208 of file Card.cs.
    {
        if (parent == null)
        {
            return this;
        }
        return parent.GetRoot();
    }
References ICardParent.GetRoot(), and parent.
Referenced by UIInventory.RefreshMenu().
GetRootCard()
Card Card.GetRootCard () inline
Definition at line 3217 of file Card.cs.
    {
        if (!(parent is Card card))
        {
            return this;
        }
        return card.GetRootCard();
    }
References card, and parent.
Referenced by InvOwnerBlend._OnProcess(), InvOwnerChangeMaterial._OnProcess(), InvOwnerEnchant._OnProcess(), InvOwnerIdentify._OnProcess(), InvOwnerLighten._OnProcess(), InvOwnerReconstruction._OnProcess(), InvOwnerUncurse._OnProcess(), AM_Adv._OnUpdateInput(), AddThing(), Thing.ApplyMaterialElements(), Thing.CanAutoFire(), Chara.CanPick(), AI_TargetCard.CanProgress(), InvOwner.CanShiftClick(), ChangeMaterial(), Recipe.Craft(), LayerInventory.CreateContainer(), DragItemCard.DragInfo.DragInfo(), Player.EquipTool(), BaseGameScreen.Focus(), TaskBuild.GetHitResult(), Thing.GetName(), Chara.HoldCard(), IsChildOf(), ModNum(), TraitBrewery.OnChildDecay(), TaskBuild.OnProgressComplete(), TraitEquipItem.OnSetCardGrid(), AI_Drink.OnSetOwner(), AI_Read.OnSetOwner(), AM_Paint.OnUpdateInput(), TraitMannequin.OnUse(), ActThrow.Perform(), Chara.PickHeld(), ActEffect.Proc(), InvOwner.Transaction.Process(), BuildMenu.RefreshCategory(), Player.RefreshCurrentHotItem(), WidgetSearch.RefreshList(), UIInventory.RefreshMenu(), RemoveThing(), AI_Drink.Run(), AI_Eat.Run(), AI_Grab< T >.Run(), AI_Read.Run(), AI_TargetCard.Run(), ButtonGrid.SetCard(), ButtonGrid.SetIngredient(), ShouldTrySetDirtyInventory(), Player.TryEquipBait(), TraitContainer.TryOpen(), ActRanged.TryReload(), TraitContainer.TrySetAct(), Map.TryShatter(), ThingContainer.TryStack(), and TryStackTo().
GetRuneEnc()
SocketData Card.GetRuneEnc (int idEle) inline
Definition at line 3415 of file Card.cs.
    {
        if (socketList != null)
        {
            foreach (SocketData socket in socketList)
            {
                if (socket.type == SocketData.Type.Rune && socket.idEle == idEle)
                {
                    return socket;
                }
            }
        }
        return null;
    }
References SocketData.idEle, socketList, and SocketData.type.
Referenced by Element.AddEncNote().
GetSightRadius()
int Card.GetSightRadius () inline
Definition at line 5830 of file Card.cs.
    {
        if (IsPC)
        {
            return EClass.player.lightRadius;
        }
        return (EClass._map.IsIndoor ? 4 : 5) + (IsPCFaction ? 1 : 0);
    }
References EClass._map, Map.IsIndoor, Player.lightRadius, and EClass.player.
Referenced by Chara.CanSeeLos(), GoalCombat.Run(), GoalCombat.TryThrow(), and GoalCombat.TryUseAbility().
GetSprite()
virtual Sprite Card.GetSprite (int dir = 0) inline virtual
Reimplemented in Chara.
Definition at line 5522 of file Card.cs.
    {
        if (trait is TraitAbility)
        {
            return (trait as TraitAbility).CreateAct()?.GetSprite() ?? EClass.core.refs.icons.defaultAbility;
        }
        return sourceCard.GetSprite(dir, trait.IdSkin, (IsInstalled && pos != null && pos.IsValid && pos.cell.IsSnowTile) ? true : false);
    }
References Point.cell, EClass.core, CoreRef.Icons.defaultAbility, RenderRow.GetSprite(), CoreRef.icons, Trait.IdSkin, Cell.IsSnowTile, Point.IsValid, and Core.refs.
Referenced by AM_Paint.OnUpdateInput(), CardActor.RefreshSprite(), and LayerPixelPaint.SetCanvas().
GetSubPassData()
virtual SubPassData Card.GetSubPassData () inline virtual
Reimplemented in Chara, and Thing.
Definition at line 5704 of file Card.cs.
    {
        return SubPassData.Default;
    }
References SubPassData.Default.
Referenced by CardRenderer.Draw().
GetTalkText()
string Card.GetTalkText (string idTopic, bool stripPun = false, bool useDefault = true) inline
Definition at line 6259 of file Card.cs.
    {
        bool flag = isChara && Chara.IsHumanSpeak;
        string text = MOD.listTalk.GetTalk(c_idTalk.IsEmpty(id), idTopic, useDefault, flag);
        if (!text.IsEmpty())
        {
            text = text.Split('|').RandomItem();
            if (!flag || (IsDeadOrSleeping && IsAliveInCurrentZone))
            {
                if (!text.StartsWith("(") && !text.StartsWith("*"))
                {
                    text = "(" + text + ")";
                }
                text = text.Replace(")", ")");
            }
        }
        return ApplyTone(text, stripPun);
    }
References TalkDataList.GetTalk(), Chara.IsHumanSpeak, and MOD.listTalk.
Referenced by DramaCustomSequence.GetRumor(), DramaManager.ParseLine(), Msg.Talk(), and WidgetFeed.Talk().
GetTilePrice()
static int Card.GetTilePrice (TileRow row, SourceMaterial::Row mat) inline static
Definition at line 6556 of file Card.cs.
    {
        int result = 0;
        if (row.id == 0)
        {
            return result;
        }
        result = row.value * mat.value / 100;
        if (result < 0)
        {
            result = 1;
        }
        return result;
    }
References TileRow.id.
Referenced by PartialMap.Save().
GetTotalQuality()
int Card.GetTotalQuality (bool applyBonus = true) inline
Definition at line 3583 of file Card.cs.
    {
        int num = 5 + LV + material.quality;
        if (applyBonus)
        {
            num = num * (100 + Quality) / 100;
        }
        return num;
    }
References LV, material, and Quality.
Referenced by Hobby.GetEfficiency().
GetValue()
int Card.GetValue (PriceType priceType = PriceType::Default, bool sell = false) inline
Definition at line 6598 of file Card.cs.
    {
        int num = ((c_fixedValue == 0) ? trait.GetValue() : c_fixedValue);
        if (id == "plat" && !sell)
        {
            num = 10000;
        }
        if (num == 0)
        {
            return 0;
        }
        float num2 = num;
        if (priceType == PriceType.CopyShop)
        {
            num2 += (float)c_priceCopy * 0.2f;
            num2 = num2 * (float)Mathf.Max(150 + rarityLv, 150) / 100f;
        }
        else
        {
            num2 = num2 * (float)Mathf.Max(100 + rarityLv + Mathf.Min(QualityLv * 10, 200), 80) / 100f;
        }
        if (IsFood && !material.tag.Contains("food"))
        {
            num2 *= 0.5f;
        }
        float num3;
        if (IsEquipmentOrRangedOrAmmo || trait is TraitMod)
        {
            if (sell)
            {
                num2 *= 0.3f;
            }
            num3 = 2f;
        }
        else
        {
            num3 = 0.5f;
        }
        if (isReplica)
        {
            num2 *= 0.15f;
        }
        if (!IsUnique)
        {
            if (IsEquipmentOrRanged && rarity >= Rarity.Legendary)
            {
                num2 = Mathf.Max(num2, 1800f + num2 / 5f);
            }
            num2 = num2 * (100f + num3 * (float)(material.value - 100)) / 100f;
            if (IsEquipmentOrRanged)
            {
                int num4 = 0;
                foreach (Element value in elements.dict.Values)
                {
                    num4 += value.source.value;
                }
                num2 = num2 * (float)(100 + (sell ? ((int)MathF.Sqrt(num4) * 10) : num4)) / 100f;
                if (rarity >= Rarity.Legendary)
                {
                    num2 = Mathf.Max(num2, 3600f + num2 / 5f);
                }
            }
        }
        if (trait is TraitRecipe && sell)
        {
            num2 *= 0.1f;
        }
        if (encLV != 0 && !category.tag.Contains("noEnc"))
        {
            num2 = (category.tag.Contains("enc") ? (num2 * (0.7f + (float)(encLV - 1) * 0.2f)) : ((!IsFood) ? (num2 * (1f + (float)encLV * 0.01f)) : ((!(id == "honey")) ? (num2 * Mathf.Min(1f + 0.1f * (float)encLV, 2f) + (float)(encLV * 100)) : (num2 + (float)(encLV * 10)))));
        }
        if (tier > 0)
        {
            num2 *= (float)(tier + 1);
        }
        return (int)num2;
    }
References ElementContainer.dict, Trait.GetValue(), material, Element.source, and SourceCategory.Row.tag.
Referenced by CraftUtil.MixIngredients(), and TraitBrewery.OnChildDecay().
GetWindowSaveData()
Window.SaveData Card.GetWindowSaveData () inline
Definition at line 2416 of file Card.cs.
    {
        if (IsPC)
        {
            return Window.dictData.TryGetValue("LayerInventoryFloatMain0");
        }
        if (trait is TraitChestMerchant)
        {
            return Window.dictData.TryGetValue("ChestMerchant");
        }
        return c_windowSaveData;
    }
References c_windowSaveData, Window.dictData, IsPC, and trait.
Referenced by LayerInventory.CreateBuy(), ThingContainer.GetDest(), TaskDump.IsValidContainer(), TaskDump.ListThingsToPut(), UIDragGridIngredients.Refresh(), and Zone.TryAddThingInSharedContainer().
HasCondition< T >()
virtual bool Card.HasCondition< T > () inline virtual
Reimplemented in Chara.
Type Constraints
T : Condition
Definition at line 7225 of file Card.cs.
                                                  : Condition
    {
        return false;
    }
HasCraftBonusTrait()
bool Card.HasCraftBonusTrait () inline
Definition at line 6362 of file Card.cs.
    {
        return ListCraftBonusTraits().Count > 0;
    }
Referenced by CraftUtil.MixIngredients().
HasEditorTag()
bool Card.HasEditorTag (EditorTag tag) inline
Definition at line 2500 of file Card.cs.
    {
        return c_editorTags?.Contains(tag.ToString()) ?? false;
    }
References c_editorTags.
Referenced by HotItemNoItem._TrySetAct(), AttackProcess.Perform(), AI_Idle.Run(), GoalCombat.Run(), CoreDebug.TestSpawn(), TraitBaseSpellbook.TryProgress(), and Map.TryShatter().
HasElement() [1/2]
bool Card.HasElement (int ele, int req = 1) inline
Definition at line 5395 of file Card.cs.
    {
        return elements.Value(ele) >= req;
    }
References ElementContainer.Value().
Referenced by Chara._Move(), TraitAltar._OnOffer(), InvOwnerGene._OnProcess(), ActPlan._Update(), UICharaMaker.AddDomain(), ActMelee.Attack(), DramaCustomSequence.Build(), RecipeCard.Build(), Chara.CanBeTempAlly(), TraitDemitas.CanCopy(), TraitKettle.CanCopy(), Trait.CanEat(), TaskMine.CanMine(), ActNTR.CanPerform(), TaskChopWood.CanProgress(), ActThrow.CanThrow(), TraitCrafter.Craft(), RecipeCard.Craft(), ActEffect.DamageEle(), DamageHP(), Decay(), CharaBody.Equip(), AI_Fuck.Finish(), HotItemHeld.GetAct(), Chara.GetHoverText(), TaskHarvest.GetIdDismantled(), Religion.GetOfferingValue(), BaseTaskHarvest.GetToolEfficiency(), Chara.GiveGift(), Party.HasElement(), CharaBody.IsEquippable(), CharaBody.IsTooHeavyToEquip(), Religion.JoinFaith(), CalcPlat.Learn(), LevelUp(), Thing.ListValidTraits(), RecipeCard.MakeDish(), TraitSeed.MakeSeed(), StatsMana.Mod(), StatsStamina.Mod(), Zone_Casino.OnActivate(), AM_Adv.OnBecomeNoGoal(), TraitTent.OnChangePlaceState(), Affinity.OnGift(), AI_Fish.ProgressFish.OnProgress(), InvOwnerGene.OnWriteNote(), ActThrow.Perform(), AttackProcess.Perform(), FoodEffect.Proc(), ActEffect.Proc(), CoreDebug.QuickStart(), Chara.Refresh(), Chara.RefreshSpeed(), Chara.RequestProtection(), ActRide.Ride(), AI_Idle.Run(), AI_Slaughter.Run(), GoalCombat.Run(), Weather.SetCondition(), SpawnLoot(), ConSleep.SuccubusVisit(), DramaActor.Talk(), ActThrow.Throw(), ConSuffocation.Tick(), Chara.TickConditions(), CalcPlat.Train(), TaskHarvest.TryGetAct(), ThingGen.TryLickChest(), Chara.TryNullifyCurse(), HotItemHeld.TrySetToolAct(), GoalCombat.TryThrow(), GoalCombat.TryUseAbility(), and CharaBody.Unequip().
HasElement() [2/2]
bool Card.HasElement (string id, int req = 1) inline
Definition at line 5400 of file Card.cs.
    {
        return HasElement(EClass.sources.elements.alias[id].id, req);
    }
References SourceManager.elements, and EClass.sources.
HasGlobalElement()
bool Card.HasGlobalElement (int ele) inline
Definition at line 5405 of file Card.cs.
    {
        return elements.GetElement(ele)?.IsGlobalElement ?? false;
    }
References ElementContainer.GetElement(), and Element.IsGlobalElement.
Referenced by Evalue().
HasLight()
bool Card.HasLight () inline
Definition at line 5811 of file Card.cs.
    {
        return GetLightRadius() > 0;
    }
HasRune()
bool Card.HasRune () inline
Definition at line 3478 of file Card.cs.
    {
        return CountRune() > 0;
    }
References CountRune().
Referenced by TraitKettle.CanCopy().
HasTag()
bool Card.HasTag (CTAG tag) inline
Definition at line 2495 of file Card.cs.
    {
        return sourceCard.tag.Contains(tag.ToString());
    }
References sourceCard, and RenderRow.tag.
Referenced by AM_Adv._OnUpdateInput(), FactionBranch.AddMemeber(), AddThing(), Thing.CanAutoFire(), Chara.CanEat(), TraitAltar.CanOffer(), Create(), FactionBranch.DailyOutcome(), ActEffect.DamageEle(), Zone.Deactivate(), ThingContainer.FindStealable(), Biography.Generate(), HomeResourceWorth.ListHeirloom(), CraftUtil.MixIngredients(), Chara.OnBanish(), Chara.OnCreate(), Thing.OnCreate(), Affinity.OnGift(), Game.OnLoad(), TraitAltar.OnOffer(), AttackProcess.Prepare(), ActEffect.ProcAt(), UIInventory.RefreshList(), Chara.ShouldEquip(), InvOwnerReconstruction.ShouldShowGuide(), SpawnLoot(), Chara.TryGetThrowable(), AI_Idle.TryPerformIdleUse(), Chara.TryPutSharedItems(), HotItemHeld.TrySetToolAct(), Chara.TryTakeSharedItems(), and GoalCombat.TryUseAbility().
HasTalk()
bool Card.HasTalk (string idTopic) inline
Definition at line 6130 of file Card.cs.
    {
        return !MOD.listTalk.GetTalk(c_idTalk.IsEmpty(id), idTopic, useDefault: true).IsEmpty();
    }
References TalkDataList.GetTalk(), and MOD.listTalk.
HaveFur()
bool Card.HaveFur () inline
Definition at line 7230 of file Card.cs.
    {
        if (!isChara)
        {
            return false;
        }
        string text = id;
        if (text == "putty_snow" || text == "putty_snow_gold")
        {
            return true;
        }
        return !Chara.race.fur.IsEmpty();
    }
References Chara.race.
Referenced by FactionBranch.DailyOutcome(), Chara.Duplicate(), ActEffect.ProcAt(), and AI_Slaughter.Run().
HealHP()
virtual void Card.HealHP (int a, HealSource origin = HealSource::None) inline virtual
Definition at line 3750 of file Card.cs.
    {
        long num = a;
        if (origin == HealSource.Magic)
        {
            num = (long)a * (long)Mathf.Max(100 - Evalue(93), 1) / 100;
        }
        if (num > 100000000)
        {
            num = 100000000L;
        }
        hp += (int)num;
        if (hp > MaxHP)
        {
            hp = MaxHP;
        }
        switch (origin)
        {
        case HealSource.Magic:
        case HealSource.Item:
            PlaySound("heal");
            PlayEffect("heal");
            break;
        case HealSource.HOT:
            PlaySound("heal_tick");
            PlayEffect("heal_tick");
            break;
        }
    }
References Evalue(), hp, MaxHP, PlayEffect(), and PlaySound().
Referenced by HealHPHost(), ActPray.Pray(), AI_PassTime.Run(), Zone.Simulate(), ConHOT.Tick(), and ConSleep.Tick().
HealHPHost()
virtual void Card.HealHPHost (int a, HealSource origin = HealSource::None) inline virtual
Definition at line 3734 of file Card.cs.
    {
        if (isChara)
        {
            if (Chara.parasite != null)
            {
                Chara.parasite.HealHP(a);
            }
            if (Chara.ride != null)
            {
                Chara.ride.HealHP(a);
            }
        }
        HealHP(a, origin);
    }
References HealHP(), isChara, Chara.parasite, and Chara.ride.
Inspect()
void Card.Inspect () inline
Definition at line 7210 of file Card.cs.
    {
        SE.Play("pop_paper");
        if (isChara)
        {
            LayerChara layerChara = EClass.ui.AddLayerDontCloseOthers<LayerChara>();
            layerChara.windows[0].SetRect(EClass.core.refs.rects.center);
            layerChara.SetChara(Chara);
        }
        else
        {
            EClass.ui.AddLayerDontCloseOthers<LayerInfo>().SetThing(Thing);
        }
    }
References CoreRef.Rects.center, EClass.core, CoreRef.rects, Core.refs, LayerChara.SetChara(), EClass.ui, and Layer.windows.
Referenced by ActPlan._Update().
Install()
Card Card.Install () inline
Definition at line 3492 of file Card.cs.
    {
        SetPlaceState(PlaceState.installed);
        return this;
    }
References SetPlaceState().
Referenced by AI_Shopping.Buy(), Chara.DropThing(), Zone.Generate(), Zone_SnowGrave.GenerateGrave(), GrowSystem.Grow(), Chara.MakeGrave(), MapGenDungen.OnGenerateTerrain(), TaskMine.OnProgressComplete(), QuestFiamaLock.OnStart(), ZoneEventDefenseGame.OnVisit(), HotItemActionSleep.Perform(), GrowSystem.Perish(), GenRoom.Populate(), ActEffect.Proc(), FactionBranch.PutInMailBox(), DramaOutcome.QuestDefense_0(), DramaOutcome.QuestDefense_1(), AI_Craft_Snowman.Run(), BiomeProfile.ClusterThing.TryCreate(), Chara.TryDropBossLoot(), Zone.TryGenerateShrine(), AI_Shopping.TryRestock(), and Zone.TrySpawnFollower().
IsChildOf()
bool Card.IsChildOf (Card c) inline
Definition at line 2561 of file Card.cs.
    {
        return GetRootCard() == c;
    }
References GetRootCard().
Referenced by AI_OpenGambleChest.IsValid().
IsExcludeFromCraft()
bool Card.IsExcludeFromCraft () inline
Definition at line 2429 of file Card.cs.
    {
        if (IsUnique || c_isImportant)
        {
            return true;
        }
        if (parent is Card card)
        {
            if (card.trait is TraitChestMerchant)
            {
                return true;
            }
            if (card.isSale || !card.trait.CanUseContent)
            {
                return true;
            }
            Window.SaveData windowSaveData = card.GetWindowSaveData();
            if (windowSaveData != null)
            {
                return windowSaveData.excludeCraft;
            }
        }
        return false;
    }
References c_isImportant, card, Window.SaveData.excludeCraft, IsUnique, and parent.
Referenced by Props.ListThingStack().
IsInMutterDistance()
bool Card.IsInMutterDistance (int d = 10) inline
Definition at line 7069 of file Card.cs.
    {
        return pos.Distance(EClass.pc.pos) < d;
    }
References Point.Distance(), EClass.pc, and pos.
Referenced by ActEffect.ProcAt(), and AI_Idle.Run().
IsStackable()
bool Card.IsStackable (Thing tg) inline
Definition at line 3226 of file Card.cs.
    {
        if (id != tg.id || material != tg.material)
        {
            return false;
        }
        return true;
    }
References id, and material.
KillAnime()
void Card.KillAnime () inline
Definition at line 5599 of file Card.cs.
    {
        renderer.KillAnime();
    }
References CardRenderer.KillAnime().
Referenced by ActThrow.Throw().
LevelUp()
void Card.LevelUp () inline
Definition at line 2839 of file Card.cs.
    {
        if (IsPC)
        {
            if (EClass.core.version.demo && EClass.player.totalFeat >= 5)
            {
                Msg.Say("demoLimit");
                return;
            }
            EClass.player.totalFeat++;
            Tutorial.Reserve("feat");
        }
        feat++;
        LV++;
        Say("dingExp", this);
        PlaySound("jingle_lvup");
        PlayEffect("aura_heaven");
        if (HasElement(1415) && Evalue(1415) < 9 && LV >= Evalue(1415) * 5 + 10)
        {
            Chara.SetFeat(1415, Evalue(1415) + 1, msg: true);
        }
        if (IsPC)
        {
            return;
        }
        if (Chara.race.id == "mutant")
        {
            int num = Mathf.Min(1 + LV / 5, 22);
            for (int i = 0; i < num; i++)
            {
                if (Evalue(1644) < i + 1)
                {
                    Chara.SetFeat(1644, i + 1);
                }
            }
        }
        Chara.TryUpgrade();
    }
References EClass.core, Version.demo, Evalue(), feat, HasElement(), IsPC, LV, PlayEffect(), EClass.player, PlaySound(), Chara.race, Tutorial.Reserve(), Msg.Say(), Say(), Chara.SetFeat(), Player.totalFeat, Chara.TryUpgrade(), and BaseCore.version.
Referenced by AddExp().
ListCraftBonusTraits()
List< Element > Card.ListCraftBonusTraits () inline
Definition at line 6367 of file Card.cs.
    {
        List<Element> list = new List<Element>();
        string[] tag = sourceCard.tag;
        for (int i = 0; i < tag.Length; i++)
        {
            string[] array = tag[i].Split('/');
            if (!(array[0] != "craft_bonus"))
            {
                Element item = Element.Create(array[1], array[2].ToInt());
                list.Add(item);
            }
        }
        return list;
    }
References Element.Create(), item, and RenderRow.tag.
Referenced by CraftUtil.MixIngredients().
LookAt() [1/2]
virtual void Card.LookAt (Card c) inline virtual
Reimplemented in Chara.
Definition at line 5652 of file Card.cs.
    {
    }
Referenced by ActThrow.Throw().
LookAt() [2/2]
virtual void Card.LookAt (Point p) inline virtual
Reimplemented in Chara.
Definition at line 5656 of file Card.cs.
    {
    }
MakeFigureFrom()
void Card.MakeFigureFrom (string id) inline
Definition at line 5269 of file Card.cs.
    {
        MakeRefFrom(id);
    }
Referenced by ContentCodex.OnClickGetCard(), CoreDebug.QuickStart(), and SpawnLoot().
MakeFoodFrom() [1/2]
Card Card.MakeFoodFrom (Card c) inline
Definition at line 5092 of file Card.cs.
    {
        MakeRefFrom(c);
        ChangeMaterial(c.material);
        SourceRace.Row race = c.Chara.race;
        int num = race.food[0].ToInt();
        bool flag = id == "meat_marble";
        int num2 = 1;
        bool flag2 = category.IsChildOf("meat");
        bool flag3 = category.IsChildOf("egg");
        if (flag)
        {
            num += 100;
        }
        if (flag2)
        {
            if (c.IsPCFaction && c.IsUnique)
            {
                num = -100;
            }
            elements.SetBase(70, race.STR * race.STR / 5 * num / 100 - 10 + num / 10);
            if (flag)
            {
                elements.SetBase(440, race.END * race.END / 5 * num / 100 - 10 + num / 10);
            }
            elements.SetBase(71, (int)Mathf.Clamp((float)(num / 10) + Mathf.Sqrt(race.height) - 10f, 1f, 60f));
        }
        else if (flag3)
        {
            elements.SetBase(444, race.LER * race.LER / 5 * num / 100 - 10 + num / 10);
            num2 = 2;
        }
        else
        {
            num2 = 3;
        }
        if (flag2)
        {
            if (race.IsHuman)
            {
                elements.SetBase(708, 1);
            }
            if (race.IsUndead)
            {
                elements.SetBase(709, 1);
            }
        }
        foreach (Element value in c.elements.dict.Values)
        {
            if ((!flag3 || value.id != 1229) && (value.source.category == "food" || value.source.tag.Contains("foodEnc") || value.IsTrait))
            {
                elements.SetBase(value.id, value.Value);
            }
        }
        List<Tuple<int, int>> list = new List<Tuple<int, int>>();
        foreach (KeyValuePair<int, int> item in race.elementMap)
        {
            if (EClass.sources.elements.map[item.Key].tag.Contains("primary"))
            {
                list.Add(new Tuple<int, int>(item.Key, item.Value));
            }
        }
        list.Sort((Tuple<int, int> a, Tuple<int, int> b) => b.Item2 - a.Item2);
        for (int i = 0; i < num2 && i < list.Count; i++)
        {
            Tuple<int, int> tuple = list[i];
            elements.SetBase(tuple.Item1, tuple.Item2 * tuple.Item2 / 4);
        }
        if (race.IsUndead)
        {
            elements.ModBase(73, -20);
        }
        isWeightChanged = true;
        c_weight = race.height * 4 + 100;
        c_idMainElement = c.c_idMainElement;
        SetBlessedState(BlessedState.Normal);
        int num3 = c.LV - c.sourceCard.LV;
        if (num3 < 0)
        {
            num3 = 0;
        }
        num3 = EClass.curve(num3, 10, 10, 80);
        if (c.rarity >= Rarity.Legendary || c.IsUnique)
        {
            num3 += 60;
        }
        if (flag2 && c.IsPCFaction && c.IsUnique)
        {
            num3 = 0;
        }
        if (num3 > 0)
        {
            elements.ModBase(2, num3);
        }
        return this;
    }
References ChangeMaterial, Chara, EClass.curve(), SourceManager.elements, SourceRace.Row.END, SourceRace.Row.food, SourceRace.Row.height, Element.id, SourceCategory.Row.IsChildOf(), SourceRace.Row.IsHuman, IsPCFaction, Element.IsTrait, SourceRace.Row.IsUndead, IsUnique, item, SourceRace.Row.LER, material, ElementContainer.ModBase(), Chara.race, ElementContainer.SetBase(), Element.source, EClass.sources, SourceRace.Row.STR, and Element.Value.
MakeFoodFrom() [2/2]
Card Card.MakeFoodFrom (string _id) inline
Definition at line 5087 of file Card.cs.
    {
        return MakeFoodFrom(EClass.sources.cards.map[_id].model);
    }
References SourceManager.cards, SourceCard.map, and EClass.sources.
Referenced by Chara.MakeEgg(), TaskHarvest.OnCreateProgress(), QuestFiamaLock.OnStart(), and SpawnLoot().
MakeFoodRef()
void Card.MakeFoodRef (Card c1, Card c2 = null) inline
Definition at line 5189 of file Card.cs.
    {
        Card card = c1;
        Card card2 = c2;
        if (IsIgnoreName(card))
        {
            card = null;
        }
        if (IsIgnoreName(card2))
        {
            card2 = null;
        }
        if (card == null && card2 != null)
        {
            card = card2;
            card2 = null;
        }
        if (card != null)
        {
            MakeRefFrom(card, card2);
            if (card.c_idRefCard != null)
            {
                c_idRefCard = card.c_idRefCard;
                c_altName = TryGetFoodName(card);
            }
            if (card2 != null && card2.c_idRefCard != null)
            {
                c_idRefCard2 = card2.c_idRefCard;
                c_altName2 = TryGetFoodName(card2);
            }
        }
        static bool IsIgnoreName(Card c)
        {
            if (c == null)
            {
                return true;
            }
            switch (c.id)
            {
            case "dough_cake":
            case "dough_bread":
            case "noodle":
            case "flour":
            case "rice":
                return true;
            default:
                return false;
            }
        }
    }
References c_idRefCard, card, and id.
Referenced by TraitBrewery.OnChildDecay().
MakeRefFrom() [1/2]
void Card.MakeRefFrom (Card c1, Card c2 = null) inline
Definition at line 5279 of file Card.cs.
    {
        c_idRefCard = c1.id;
        c_altName = (c1.IsPC ? c1.c_altName : c1.GetName(NameStyle.Ref, (!c1.isChara) ? 1 : 0));
        if (c2 != null)
        {
            c_idRefCard2 = c2.id;
            c_altName2 = (c2.IsPC ? c2.c_altName : c2.GetName(NameStyle.Ref, (!c2.isChara) ? 1 : 0));
        }
        c_extraNameRef = (c1.IsPC ? EClass.pc.c_altName : c1.c_extraNameRef);
    }
References c_extraNameRef, GetName(), id, and isChara.
MakeRefFrom() [2/2]
void Card.MakeRefFrom (string id) inline
Definition at line 5274 of file Card.cs.
    {
        c_idRefCard = id;
    }
Referenced by TraitCrafter.Craft(), Trait.CreateStock(), DNA.GenerateGene(), DNA.GenerateManiGene(), Chara.MakeGrave(), Chara.MakeMilk(), and Chara.Vomit().
MatchEncSearch()
virtual bool Card.MatchEncSearch (string s) inline virtual
Reimplemented in Thing.
Definition at line 7100 of file Card.cs.
    {
        return false;
    }
MaxRune()
int Card.MaxRune () inline
Definition at line 3446 of file Card.cs.
    {
        return ((!IsUnique) ? 1 : 0) + Evalue(484);
    }
References Evalue(), and IsUnique.
Referenced by CanAddRune().
Mod()
void Card.Mod () inline
Definition at line 2411 of file Card.cs.
    {
        isModified = true;
    }
References isModified.
ModCharge()
void Card.ModCharge (int a, bool destroy = false) inline
Definition at line 3697 of file Card.cs.
    {
        c_charges += a;
        LayerInventory.SetDirty(Thing);
        if (c_charges <= 0 && destroy)
        {
            Say("spellbookCrumble", this);
            ModNum(-1);
        }
    }
References c_charges, ModNum(), Say(), and LayerInventory.SetDirty().
Referenced by TraitBaseSpellbook.ModCharge(), TaskDrawWater.OnCreateProgress(), TaskPourWater.OnCreateProgress(), ActWater.Perform(), ActZap.Perform(), Trait.Refuel(), AI_UseCrafter.Run(), TaskWater.Run(), ConSleep.SuccubusVisit(), Trait.TryOpenLock(), and Map.TryShatter().
ModCurrency()
void Card.ModCurrency (int a, string id = "money") inline
Definition at line 3708 of file Card.cs.
    {
        if (a != 0)
        {
            if (id == "influence")
            {
                EClass._zone.ModInfluence(a);
                return;
            }
            SourceMaterial.Row mat = null;
            things.AddCurrency(this, id, a, mat);
        }
    }
References EClass._zone, ThingContainer.AddCurrency(), Zone.ModInfluence(), and things.
Referenced by DramaOutcome.chara_hired(), ItemGachaResult.Confirm(), MiniGame.Deactivate(), HitSummary.Execute(), AI_Fuck.Finish(), TraitGamble.IdleUse(), Faction.OnAdvanceMonth(), InvOwnerDeliver.PayBill(), InvOwner.Transaction.Process(), CoreDebug.QuickStart(), AI_Idle.Run(), DramaOutcome.sister_friend(), TryPay(), and Chara.TryPush().
ModEncLv()
void Card.ModEncLv (int a) inline
Definition at line 3593 of file Card.cs.
    {
        ApplyMaterialElements(remove: true);
        encLV += a;
        ApplyMaterialElements(remove: false);
        if (IsEquipmentOrRangedOrAmmo)
        {
            if (IsWeapon || IsAmmo)
            {
                elements.ModBase(67, a);
            }
            else
            {
                elements.ModBase(65, a * 2);
            }
        }
    }
References ApplyMaterialElements(), elements, encLV, IsAmmo, IsEquipmentOrRangedOrAmmo, IsWeapon, and ElementContainer.ModBase().
Referenced by TraitSeed.LevelSeed(), TraitDrink.OnBlend(), TraitFoodMeat.OnUse(), ActEffect.Proc(), AI_Idle.Run(), and SetEncLv().
ModExp() [1/2]
void Card.ModExp (int ele, int a) inline
Definition at line 2553 of file Card.cs.
    {
        if (isChara)
        {
            elements.ModExp(ele, a);
        }
    }
References elements, isChara, and ElementContainer.ModExp().
ModExp() [2/2]
void Card.ModExp (string alias, int a) inline
Definition at line 2548 of file Card.cs.
    {
        ModExp(EClass.sources.elements.alias[alias].id, a);
    }
References SourceManager.elements, ModExp(), and EClass.sources.
Referenced by Chara._Move(), ActMelee.Attack(), Chara.FindNewEnemy(), AI_Fuck.Finish(), Chara.GiveGift(), ModExp(), Player.OnAdvanceDay(), TaskHarvest.OnCreateProgress(), TraitDrinkMilkMother.OnDrink(), ShopTransaction.OnEndTransaction(), MiniGame.OnPlay(), TraitBaseSpellbook.OnRead(), Affinity.OnTalkRumor(), ActZap.Perform(), AttackProcess.Perform(), ActPray.Pray(), AI_Pray.Pray(), FoodEffect.Proc(), AI_Craft_Snowman.Run(), AI_OpenGambleChest.Run(), AI_PassTime.Run(), GoalCombat.Run(), TaskClean.Run(), TaskWater.Run(), ActThrow.Throw(), ConSuffocation.Tick(), TraitSwitch.TryDisarmTrap(), Chara.TryIdentify(), Trait.TryOpenLock(), and ActPray.TryPray().
ModNum()
void Card.ModNum (int a, bool notify = true) inline
Definition at line 3306 of file Card.cs.
    {
        if (Num + a < 0)
        {
            a = -Num;
        }
        Num += a;
        if (props != null)
        {
            props.OnNumChange(this, a);
        }
        if (parent != null)
        {
            parent.OnChildNumChange(this);
        }
        if (a > 0 && EClass.core.IsGameStarted && GetRootCard() == EClass.pc && notify)
        {
            NotifyAddThing(Thing, a);
        }
        SetDirtyWeight();
        if (Num <= 0)
        {
            Destroy();
        }
    }
References EClass.core, Destroy(), GetRootCard(), Core.IsGameStarted, NotifyAddThing(), Num, ICardParent.OnChildNumChange(), Props.OnNumChange(), parent, EClass.pc, props, and SetDirtyWeight().
Referenced by InvOwnerChangeMaterial._OnProcess(), InvOwnerChaosOffering._OnProcess(), InvOwnerMod._OnProcess(), ThingContainer.AddCurrency(), DramaOutcome.chara_hired_ticket(), TraitCrafter.Craft(), SourceMaterial.Row.CreateByProduct(), FactionBranch.DailyOutcome(), Chara.Drink(), TraitDye.Dye(), HitSummary.Execute(), Chara.GiveGift(), DramaOutcome.guild_mageTrial(), TraitBaseSpellbook.ModCharge(), ModCharge(), TraitDreamBug.OnBlend(), TraitDrink.OnBlend(), TraitWell.OnBlend(), TaskChopWood.OnCreateProgress(), DragItemCard.OnDragSpecial(), AI_Fish.ProgressFish.OnProgressComplete(), TaskBuild.OnProgressComplete(), TraitBookSecret.OnRead(), TraitDeed.OnRead(), TraitDeedRelocate.OnRead(), TraitDiary.OnRead(), TraitIndulgence.OnRead(), TraitLicense.OnRead(), TraitRecipe.OnRead(), TraitRecipeCat.OnRead(), TraitScrollMap.OnRead(), TraitScrollStatic.OnRead(), TraitFirework.OnUse(), TraitGainPrecious.OnUse(), TraitGiftJure.OnUse(), TraitGiftNewYear.OnUse(), TraitGiftPack.OnUse(), TraitGoodsCoin.OnUse(), TraitItemProc.OnUse(), TraitParcel.OnUse(), TraitPlamoBox.OnUse(), TraitTape.OnUse(), TraitWaystone.OnUse(), TraitPotionEmpty.OnUse(), LayerGacha.PlayGacha(), AI_Eat.Run(), AI_Idle.Run(), AI_OpenGambleChest.Run(), SetNum(), CoreDebug.SetStartStockpile(), Split(), TraitWaystone.TrySetAct(), TraitSyringeGene.TrySetHeldAct(), TraitSyringeHeaven.TrySetHeldAct(), TraitToolTorch.TrySetHeldAct(), TryStackTo(), and TraitFoodEgg.Update().
MoveImmediate()
void Card.MoveImmediate (Point p, bool focus = true, bool cancelAI = true) inline
Definition at line 5308 of file Card.cs.
    {
        if (p == null)
        {
            return;
        }
        EClass._map.MoveCard(p, this);
        if (!IsPC || focus)
        {
            renderer.SetFirst(first: true, p.PositionCenter());
        }
        if (isChara)
        {
            if (cancelAI)
            {
                Chara.ai.Cancel();
            }
            Chara.SyncRide();
        }
        if (IsPC && focus)
        {
            EClass.screen.FocusPC();
            EClass.screen.RefreshPosition();
        }
    }
References EClass._map, Chara.ai, AIAct.Cancel(), BaseGameScreen.FocusPC(), Map.MoveCard(), Point.PositionCenter(), BaseGameScreen.RefreshPosition(), EClass.screen, CardRenderer.SetFirst(), and Chara.SyncRide().
Referenced by Chara.Kick(), FactionBranch.OnActivateZone(), FactionBranch.OnAfterSimulate(), GoalGraze.OnSimulatePosition(), GoalSleep.OnSimulatePosition(), GoalWork.OnSimulatePosition(), TraitShackle.OnUse(), ActRush.Perform(), LayerTravel.Refresh(), AI_Trolley.Run(), Meeting.SetChara(), MeetingManager.Start(), ConSleep.Tick(), and ActRide.Unride().
NotifyAddThing()
void Card.NotifyAddThing (Thing t, int num) inline
Definition at line 2946 of file Card.cs.
    {
    }
Referenced by AddThing(), and ModNum().
OnBeforeCreate()
virtual void Card.OnBeforeCreate () inline virtual
Reimplemented in Chara.
Definition at line 2726 of file Card.cs.
    {
    }
Referenced by Create().
OnChildNumChange()
void Card.OnChildNumChange (Card c) inline
Implements ICardParent.
Definition at line 3483 of file Card.cs.
    {
        if (ShouldTrySetDirtyInventory() && c.isThing)
        {
            LayerInventory.SetDirty(c.Thing);
            WidgetCurrentTool.RefreshCurrentHotItem();
        }
    }
References isThing, WidgetCurrentTool.RefreshCurrentHotItem(), LayerInventory.SetDirty(), ShouldTrySetDirtyInventory(), and Thing.
OnCreate()
virtual void Card.OnCreate (int genLv) inline virtual
Reimplemented in Chara, and Thing.
Definition at line 2730 of file Card.cs.
    {
    }
Referenced by Create().
OnDeserialized()
virtual void Card.OnDeserialized () inline protected virtual
Reimplemented in Chara.
Definition at line 2614 of file Card.cs.
    {
    }
Referenced by _OnDeserialized().
OnInspect()
void Card.OnInspect () inline
Implements IInspect.
Definition at line 7202 of file Card.cs.
    {
    }
OnLand()
virtual void Card.OnLand () inline virtual
Definition at line 5376 of file Card.cs.
    {
        if (Cell.IsTopWaterAndNoSnow)
        {
            PlayEffect("ripple");
            PlaySound("Footstep/water");
        }
    }
References Cell.IsTopWaterAndNoSnow.
OnSerializing()
virtual void Card.OnSerializing () inline protected virtual
Reimplemented in Chara.
Definition at line 2586 of file Card.cs.
    {
    }
Referenced by _OnSerializing().
OnSimulateHour()
virtual void Card.OnSimulateHour (VirtualDate date) inline virtual
Definition at line 6006 of file Card.cs.
    {
        trait.OnSimulateHour(date);
        if (date.IsRealTime)
        {
            DecayNatural();
        }
    }
References VirtualDate.IsRealTime, and Trait.OnSimulateHour().
Referenced by Zone.OnSimulateHour().
PlayAnime() [1/2]
void Card.PlayAnime (AnimeID id, bool force = false) inline
Definition at line 5604 of file Card.cs.
    {
        renderer.PlayAnime(id, force);
    }
References CardRenderer.PlayAnime().
Referenced by AI_Torture.CreateProgress(), TaskChopWood.OnCreateProgress(), TaskHarvest.OnCreateProgress(), TaskMoveInstalled.OnProgressComplete(), ZoneEventBeggerChest.OnTickRound(), ZoneEventPhone.OnTickRound(), Scene.OnUpdate(), DramaManager.ParseLine(), AI_Craft_Snowman.Run(), AI_Eat.Run(), AI_Idle.Run(), AI_OpenGambleChest.Run(), AI_PlayMusic.Run(), AI_Pray.Run(), AI_Trolley.Run(), TraitDetector.Search(), Trait.TryOpenLock(), and TraitWell.TrySetAct().
PlayAnime() [2/2]
void Card.PlayAnime (AnimeID id, Point dest, bool force = false) inline
Definition at line 5609 of file Card.cs.
    {
        renderer.PlayAnime(id, dest);
    }
References CardRenderer.PlayAnime().
PlayAnimeLoot()
void Card.PlayAnimeLoot () inline
Definition at line 5614 of file Card.cs.
    {
        renderer.PlayAnime(AnimeID.Loot);
    }
References CardRenderer.PlayAnime().
Referenced by Zone.AddCard().
PlayEffect() [1/2]
void Card.PlayEffect (int ele, bool useRenderPos = true, float range = 0f) inline
Definition at line 5629 of file Card.cs.
    {
        Effect effect = Effect.Get("Element/" + EClass.sources.elements.map[ele].alias);
        if (effect == null)
        {
            Debug.Log(ele);
            return;
        }
        Card rootCard = GetRootCard();
        effect._Play(rootCard.pos, ((isSynced && useRenderPos) ? rootCard.renderer.position : rootCard.pos.Position()) + new Vector3(Rand.Range(0f - range, range), Rand.Range(0f - range, range), 0f));
    }
References Effect._Play(), Debug, SourceManager.elements, Effect.Get(), pos, CardRenderer.position, Point.Position(), Rand.Range(), renderer, and EClass.sources.
PlayEffect() [2/2]
Effect Card.PlayEffect (string id, bool useRenderPos = true, float range = 0f, Vector3 fix = default(Vector3)) inline
Definition at line 5619 of file Card.cs.
    {
        if (id.IsEmpty())
        {
            return null;
        }
        Card rootCard = GetRootCard();
        return Effect.Get(id)._Play(rootCard.pos, fix + ((isSynced && useRenderPos) ? rootCard.renderer.position : rootCard.pos.Position()) + new Vector3(Rand.Range(0f - range, range), Rand.Range(0f - range, range), 0f));
    }
References Effect._Play(), Effect.Get(), pos, CardRenderer.position, Point.Position(), Rand.Range(), and renderer.
Referenced by InvOwnerChaosOffering._OnProcess(), InvOwnerGene._OnProcess(), InvOwnerMod._OnProcess(), TraitShrine._OnUse(), TraitCrafter.Craft(), ActEffect.DamageEle(), DamageHP(), AI_Fuck.Finish(), AI_Massage.Finish(), Chara.GiveGift(), HealHP(), Religion.JoinFaith(), Chara.Kick(), LevelUp(), AI_Fish.Makefish(), TraitTrap.OnActivateTrap(), TraitDrinkMilkMother.OnDrink(), TraitAltar.OnOffer(), TraitBookSecret.OnRead(), TraitDiary.OnRead(), TraitIndulgence.OnRead(), TraitScrollStatic.OnRead(), TraitFertilizer.OnSimulateHour(), Scene.OnUpdate(), TraitDaggerGrave.OnUse(), TraitGiftJure.OnUse(), TraitPowerStatue.OnUse(), ActZap.Perform(), BaseCondition.PlayEffect(), ConBuffStats.PlayEffect(), BaseCondition.PlayEndEffect(), AttackProcess.PlayRangedAnime(), ActPray.Pray(), AI_Pray.Pray(), ActEffect.Proc(), ActEffect.ProcAt(), Religion.Reforge(), GoalCombat.Run(), TraitAltar.TakeOver(), ActThrow.Throw(), ConBurning.Tick(), Religion.TryGetGift(), ActPray.TryPray(), Chara.TryPush(), TraitFoodEgg.Update(), CoreDebug.UpdateInput(), and FactionBranch.Upgrade().
PlaySound()
SoundSource Card.PlaySound (string id, float v = 1f, bool spatial = true) inline
Definition at line 5585 of file Card.cs.
    {
        Card rootCard = GetRootCard();
        if (rootCard.IsPC)
        {
            spatial = false;
        }
        if (rootCard.Dist(EClass.pc) < EClass.player.lightRadius + 1 || !spatial)
        {
            return rootCard.pos.PlaySound(id, isSynced || !spatial, v, spatial);
        }
        return null;
    }
References Dist(), IsPC, Player.lightRadius, EClass.pc, EClass.player, Point.PlaySound(), and pos.
Referenced by Chara._Move(), RecipeManager.Add(), Chara.AddRandomBodyPart(), ActMelee.Attack(), Core.Awake(), Recipe.Build(), RecipeCard.Build(), AI_Shopping.Buy(), Zone.ClaimZone(), Trait.CookProgress(), TraitCrafter.Craft(), AI_OpenLock.CreateProgress(), ActEffect.DamageEle(), TraitDye.Dye(), CharaBody.Equip(), AI_Fuck.Finish(), AI_Massage.Finish(), Chara.GiveGift(), Chara.GiveLovePotion(), HealHP(), TraitChopper.IdleUse(), TraitGamble.IdleUse(), Trait.Install(), LevelUp(), TraitSeed.MakeSeed(), TraitNewZone.MoveZone(), Trait.Offer(), TraitChangingRoom.OnActivateTrap(), TraitSeesaw.OnActivateTrap(), TraitTrap.OnActivateTrap(), AIWork_Lumberjack.OnCreateProgress(), AIWork_Research.OnCreateProgress(), TaskDig.OnCreateProgress(), TaskDrawWater.OnCreateProgress(), TaskHarvest.OnCreateProgress(), TaskMine.OnCreateProgress(), TaskPlow.OnCreateProgress(), TaskPourWater.OnCreateProgress(), TraitDrinkMilkMother.OnDrink(), Affinity.OnGift(), ElementContainerCard.OnModTempPotential(), TraitAltar.OnOffer(), TraitDoorBell.OnOpenDoor(), AI_Farm.OnProgress(), AI_Fish.ProgressFish.OnProgress(), AI_Water.OnProgress(), TaskCraft.OnProgress(), AI_Fish.ProgressFish.OnProgressComplete(), AI_Water.OnProgressComplete(), TaskBuild.OnProgressComplete(), TraitBaseSpellbook.OnRead(), TraitBookSecret.OnRead(), TraitDeedRelocate.OnRead(), TraitDiary.OnRead(), TraitIndulgence.OnRead(), ConSleep.OnRemoved(), TraitJukeBox.OnSetBGM(), TraitToolTorch.OnSetCurrentItem(), TraitClock.OnSimulateHour(), TraitFertilizer.OnSimulateHour(), AI_Fish.ProgressFish.OnStart(), TraitMiniPool.OnStepped(), TraitSwing.OnSteppedOut(), TraitLeverBreaker.OnToggle(), Scene.OnUpdate(), TraitDaggerGrave.OnUse(), TraitEquipItem.OnUse(), TraitGeneMachine.OnUse(), TraitGiftJure.OnUse(), TraitStairsLocked.OnUse(), TraitWhistlePeace.OnUse(), TraitFoodMeat.OnUse(), DramaManager.ParseLine(), ActBash.Perform(), ActDrawWater.Perform(), ActDreamBug.Perform(), ActRanged.Perform(), ActRush.Perform(), ActSummonGuard.Perform(), ActWater.Perform(), ActZap.Perform(), AttackProcess.Perform(), BaseCondition.PlayEffect(), ConBuffStats.PlayEffect(), BaseCondition.PlayEndEffect(), AttackProcess.PlayRangedAnime(), Trait.PlayToggleEffect(), AI_Pray.Pray(), FoodEffect.Proc(), ActEffect.Proc(), ActEffect.ProcAt(), TraitBaseSpellbook.ReadFailEffect(), TraitGenerator.Recover(), Chara.RemoveLastBodyPart(), ActRide.Ride(), AI_Bladder.Run(), AI_Clean.Run(), AI_Craft_Snowman.Run(), AI_Deconstruct.Run(), AI_Eat.Run(), AI_Fuck.Run(), AI_HaulResource.Run(), AI_Idle.Run(), AI_OpenGambleChest.Run(), AI_Paint.Run(), AI_PlayMusic.Run(), AI_Read.Run(), AI_Shear.Run(), AI_Slaughter.Run(), AI_Steal.Run(), AI_Trolley.Run(), AI_UseCrafter.Run(), GoalCombat.Run(), TaskClean.Run(), TaskCullLife.Run(), TaskWater.Run(), TraitDetector.Search(), ActWait.SearchMedal(), LayerPixelPaint.SetCanvas(), TraitGenerator.ShortOut(), ActThrow.Throw(), ConBurning.Tick(), Trait.Toggle(), TraitDoor.ToggleDoor(), TraitDoorSwing.ToggleDoor(), TraitToolTorch.ToggleOn(), TraitSwitch.TryDisarmTrap(), Trait.TryOpenLock(), ActPray.TryPray(), Chara.TryPush(), AI_Shopping.TryRestock(), TraitWell.TrySetAct(), Trait.Uninstall(), ActRide.Unride(), TraitFoodEgg.Update(), and CoreDebug.UpdateInput().
PlaySoundDead()
void Card.PlaySoundDead (bool spatial = true) inline
Definition at line 5580 of file Card.cs.
    {
        PlaySound(material.GetSoundDead(sourceCard), 1f, spatial);
    }
References material.
Referenced by TaskChopWood.OnCreateProgress().
PlaySoundDrop()
void Card.PlaySoundDrop (bool spatial = true) inline
Definition at line 5570 of file Card.cs.
    {
        PlaySound(material.GetSoundDrop(sourceCard), 1f, spatial);
    }
References material.
Referenced by InvOwnerCraft._OnProcess(), RecipeCard.Craft(), InvOwnerDraglet.OnProcess(), InvOwner.OnShiftClick(), InvOwner.OnStartDrag(), Trait.Refuel(), AI_UseCrafter.Run(), and TaskDump.Run().
PlaySoundHold()
void Card.PlaySoundHold (bool spatial = true) inline
Definition at line 5565 of file Card.cs.
    {
        PlaySound(material.GetSoundDrop(sourceCard), 1f, spatial);
    }
References material.
PlaySoundImpact()
void Card.PlaySoundImpact (bool spatial = true) inline
Definition at line 5575 of file Card.cs.
    {
        PlaySound(material.GetSoundImpact(sourceCard), 1f, spatial);
    }
References material.
Referenced by TaskChopWood.OnCreateProgress().
PurgeDuplicateArtifact()
void Card.PurgeDuplicateArtifact (Thing af) inline
Definition at line 3068 of file Card.cs.
    {
        List<Chara> list = new List<Chara>();
        foreach (FactionBranch child in EClass.pc.faction.GetChildren())
        {
            foreach (Chara member in child.members)
            {
                list.Add(member);
            }
        }
        foreach (Chara chara in EClass._map.charas)
        {
            list.Add(chara);
        }
        foreach (Chara item in list)
        {
            if (!item.IsPCFactionOrMinion)
            {
                continue;
            }
            List<Thing> list2 = item.things.List((Thing t) => t.id == af.id && t != af);
            if (list2.Count == 0)
            {
                continue;
            }
            foreach (Thing item2 in list2)
            {
                Msg.Say("destroyed_inv_", item2, item);
                item2.Destroy();
            }
        }
    }
References EClass._map, Map.charas, Destroy(), Chara.faction, Faction.GetChildren(), id, item, FactionBranch.members, EClass.pc, and Msg.Say().
Referenced by FactionBranch.AddMemeber(), and AddThing().
RecalculateFOV()
void Card.RecalculateFOV () inline
Definition at line 5797 of file Card.cs.
    {
        if (fov != null)
        {
            ClearFOV();
            fov = null;
            if (IsPC)
            {
                EClass.player.lightRadius = 1;
            }
        }
        CalculateFOV();
    }
Referenced by ActPlan._Update(), GameDate.AdvanceHour(), CharaBody.Equip(), Scene.Init(), Trait.Install(), ConBlind.OnRemoved(), ConNightVision.OnRemoved(), ConTorch.OnRemoved(), TraitToolTorch.OnSetCurrentItem(), ConBlind.OnStart(), ConTorch.OnStart(), ConNightVision.OnStartOrStack(), TraitToolTorch.OnUnsetCurrentItem(), TraitDaggerGrave.OnUse(), DramaManager.ParseLine(), Trait.PlayToggleEffect(), CoreDebug.QuickStart(), Player.RefreshCurrentHotItem(), RemoveThing(), and CharaBody.Unequip().
ReferenceId()
string Card.ReferenceId () inline
Implements IGlobalValue.
Definition at line 2618 of file Card.cs.
    {
        return "c" + uid;
    }
References uid.
RefreshColor()
void Card.RefreshColor () inline
Definition at line 5460 of file Card.cs.
    {
        if (isChara)
        {
            if (isDyed)
            {
                _colorInt = BaseTileMap.GetColorInt(ref DyeMat.matColor, sourceRenderCard.colorMod);
            }
            else if (isElemental)
            {
                _colorInt = BaseTileMap.GetColorInt(ref EClass.setting.elements[Chara.MainElement.source.alias].colorSprite, sourceRenderCard.colorMod);
            }
            else
            {
                _colorInt = 104025;
            }
        }
        else if (isDyed)
        {
            _colorInt = BaseTileMap.GetColorInt(ref DyeMat.matColor, sourceRenderCard.colorMod);
        }
        else if (sourceRenderCard.useRandomColor)
        {
            _colorInt = BaseTileMap.GetColorInt(ref GetRandomColor(), sourceRenderCard.colorMod);
        }
        else if (sourceRenderCard.useAltColor)
        {
            _colorInt = BaseTileMap.GetColorInt(ref material.altColor, sourceRenderCard.colorMod);
        }
        else
        {
            _colorInt = BaseTileMap.GetColorInt(ref material.matColor, sourceRenderCard.colorMod);
        }
    }
References RenderRow.colorMod, GameSetting.elements, BaseTileMap.GetColorInt(), Chara.MainElement, SourceMaterial.Row.matColor, material, EClass.setting, Element.source, RenderRow.useAltColor, and RenderRow.useRandomColor.
RemoveBacker()
void Card.RemoveBacker () inline
Definition at line 6436 of file Card.cs.
    {
        if (c_idBacker == 164)
        {
            Chara.things.Find("amulet_moonnight")?.Destroy();
        }
        c_idBacker = 0;
    }
References Destroy(), ThingContainer.Find(), and things.
Referenced by Zone_Casino.OnActivate(), BackerContentInspector.ContentCard.Remove(), and Zone.Revive().
RemoveCard()
void Card.RemoveCard (Card c) inline
Implements ICardParent.
Definition at line 2941 of file Card.cs.
    {
        RemoveThing(c as Thing);
    }
References RemoveThing().
Referenced by ZonePreEnterBoutWin.Execute(), InvOwner.Grab(), and InvOwner.OnShiftClick().
RemoveEditorTag()
void Card.RemoveEditorTag (EditorTag tag) inline
Definition at line 2510 of file Card.cs.
    {
        c_editorTags = (c_editorTags.IsEmpty() ? null : c_editorTags.Replace(tag.ToString(), "").Replace(",,", ","));
    }
References c_editorTags.
Referenced by AddThing(), QuestDebt.OnStart(), DramaOutcome.poppy_found(), DramaOutcome.QuestExploration_AfterCrystal(), and DramaOutcome.QuestExploration_MeetFarris().
RemoveThing()
void Card.RemoveThing (Thing thing) inline
Definition at line 3109 of file Card.cs.
    {
        Card rootCard = GetRootCard();
        if (rootCard != null && rootCard.isChara && (rootCard.Chara.held == thing || (rootCard.IsPC && thing.things.Find((Thing t) => EClass.pc.held == t) != null)))
        {
            rootCard.Chara.held = null;
            if (rootCard.IsPC)
            {
                WidgetCurrentTool instance = WidgetCurrentTool.Instance;
                if ((bool)instance && instance.selected != -1 && instance.selectedButton.card != null && instance.selectedButton.card == thing)
                {
                    instance.selectedButton.card = null;
                }
                EClass.player.RefreshCurrentHotItem();
                ActionMode.AdvOrRegion.updatePlans = true;
                LayerInventory.SetDirty(thing);
            }
            RecalculateFOV();
        }
        dirtyWeight = true;
        if (thing.c_equippedSlot != 0 && isChara)
        {
            Chara.body.Unequip(thing);
        }
        things.Remove(thing);
        things.OnRemove(thing);
        if (isSale && things.Count == 0 && IsContainer)
        {
            isSale = false;
            EClass._map.props.sales.Remove(this);
        }
        if (thing.invY == 1)
        {
            WidgetCurrentTool.dirty = true;
        }
        thing.invX = -1;
        thing.invY = 0;
        if (thing.props != null)
        {
            thing.props.Remove(thing);
        }
        SetDirtyWeight();
        if (ShouldTrySetDirtyInventory())
        {
            LayerInventory.SetDirty(thing);
            WidgetHotbar.dirtyCurrentItem = true;
            thing.parent = null;
            if (thing.trait.IsContainer)
            {
                foreach (LayerInventory item in LayerInventory.listInv.Copy())
                {
                    if (item.invs[0].owner.Container.GetRootCard() != EClass.pc && item.floatInv)
                    {
                        EClass.ui.layerFloat.RemoveLayer(item);
                    }
                }
            }
        }
        thing.parent = null;
    }
References EClass._map, Chara.body, c_equippedSlot, ButtonGrid.card, Chara, dirtyWeight, ThingContainer.Find(), GetRootCard(), Chara.held, WidgetCurrentTool.Instance, invY, isChara, IsContainer, Trait.IsContainer, IsPC, isSale, item, LayerInventory.listInv, ThingContainer.OnRemove(), EClass.pc, EClass.player, props, Map.props, RecalculateFOV(), Player.RefreshCurrentHotItem(), Props.Remove(), PropsManager.sales, WidgetCurrentTool.selected, WidgetCurrentTool.selectedButton, LayerInventory.SetDirty(), SetDirtyWeight(), ShouldTrySetDirtyInventory(), things, trait, EClass.ui, and CharaBody.Unequip().
Referenced by RemoveCard(), and RemoveThings().
RemoveThings()
void Card.RemoveThings () inline
Definition at line 3101 of file Card.cs.
    {
        for (int num = things.Count - 1; num >= 0; num--)
        {
            RemoveThing(things[num]);
        }
    }
References RemoveThing(), and things.
Referenced by ApplyEditorTags(), RecipeCard.Craft(), Trait.OnBarter(), and FactionBranch.OnCreate().
RenderMarker()
void Card.RenderMarker (Point point, bool active, HitResult result, bool main, int dir, bool useCurrentPosition = false) inline
Definition at line 5733 of file Card.cs.
    {
        if (dir != -1)
        {
            this.dir = dir;
        }
        Vector3 v = point.Position();
        bool skipRender = point.cell.skipRender;
        if (result != 0 && EClass.screen.guide.isActive && !skipRender)
        {
            EClass.screen.guide.passGuideBlock.Add(ref v, (point.HasObj || point.HasChara) ? 5 : 0);
        }
        if (!main)
        {
            return;
        }
        RenderParam renderParam = GetRenderParam();
        if (EClass.scene.actionMode.IsRoofEditMode(this))
        {
            renderParam.x = v.x;
            renderParam.y = v.y;
            renderParam.z = v.z;
            EClass.screen.tileMap.SetRoofHeight(renderParam, point.cell, point.x, point.z);
            v.x = renderParam.x;
            v.y = renderParam.y;
            v.z = renderParam.z;
        }
        if (TileType.UseMountHeight && !EClass.scene.actionMode.IsRoofEditMode(this))
        {
            TileType.GetMountHeight(ref v, point, this.dir, this);
        }
        v.z += EClass.setting.render.thingZ;
        if (!skipRender)
        {
            Vector3 thingPosition = EClass.screen.tileMap.GetThingPosition(this, point);
            if (freePos)
            {
                v.x += fx;
                v.y += fy;
                v.z += thingPosition.z;
            }
            else
            {
                v += thingPosition;
            }
        }
        if (useCurrentPosition)
        {
            v = renderer.position;
            v.z += -0.01f;
        }
        if (TileType == TileType.Door)
        {
            v.z -= 0.5f;
        }
        renderParam.matColor = (active ? EClass.Colors.blockColors.Active : EClass.Colors.blockColors.Inactive);
        point.ApplyAnime(ref v);
        if (renderer.hasActor)
        {
            renderer.actor.RefreshSprite();
        }
        renderer.Draw(renderParam, ref v, drawShadow: false);
    }
References Scene.actionMode, CardRenderer.actor, MeshPass.Add(), Point.ApplyAnime(), ColorProfile.blockColors, Point.cell, EClass.Colors, TileType.Door, CardRenderer.Draw(), TileType.GetMountHeight(), BaseTileMap.GetThingPosition(), BaseGameScreen.guide, CardRenderer.hasActor, Point.HasChara, Point.HasObj, ColorProfile.BlockColors.Inactive, ScreenGuide.isActive, ActionMode.IsRoofEditMode(), ScreenGuide.passGuideBlock, CardRenderer.position, Point.Position(), CardActor.RefreshSprite(), GameSetting.render, EClass.scene, EClass.screen, BaseTileMap.SetRoofHeight(), EClass.setting, Cell.skipRender, GameSetting.RenderSetting.thingZ, BaseGameScreen.tileMap, TileType.UseMountHeight, MeshPassParam.x, Point.x, MeshPassParam.y, MeshPassParam.z, and Point.z.
Referenced by RecipeCard.OnRenderMarker().
ResistLv()
int Card.ResistLv (int res) inline
Definition at line 5390 of file Card.cs.
    {
        return Element.GetResistLv(Evalue(res));
    }
References Element.GetResistLv().
Referenced by ActEffect.ProcAt().
ResistLvFrom()
int Card.ResistLvFrom (int ele) inline
Definition at line 5385 of file Card.cs.
    {
        return ResistLv(EClass.sources.elements.alias.TryGetValue(EClass.sources.elements.map[ele].aliasRef)?.id ?? 0);
    }
References SourceManager.elements, and EClass.sources.
Referenced by GoalCombat.TryUseAbility().
Rotate()
virtual void Card.Rotate (bool reverse = false) inline virtual
Reimplemented in Chara.
Definition at line 5660 of file Card.cs.
    {
        int num = 4;
        if (sourceCard.tiles.Length > 4)
        {
            num = sourceCard.tiles.Length;
        }
        if (TileType == TileType.Door)
        {
            num = 2;
        }
        if (reverse)
        {
            dir--;
        }
        else
        {
            dir++;
        }
        if (dir < 0)
        {
            dir = num - 1;
        }
        if (dir == num)
        {
            dir = 0;
        }
        SetDir(dir);
        renderer.RefreshSprite();
    }
References TileType.Door, CardRenderer.RefreshSprite(), and RenderRow.tiles.
Referenced by RecipeCard.Rotate(), Cell.RotateAll(), and AM_Adv.ShowAllAction().
Say() [1/3]
void Card.Say (string lang, Card c1, Card c2, string ref1 = null, string ref2 = null) inline
Definition at line 6241 of file Card.cs.
    {
        if (ShouldShowMsg)
        {
            Msg.Say(IsPC ? Lang.Game.TryGetId(lang + "_pc", lang) : lang, c1, c2, ref1, ref2);
        }
        Msg.SetColor();
    }
References Lang.Game, Msg.Say(), Msg.SetColor(), and SourceLang< T >.TryGetId().
Say() [2/3]
void Card.Say (string lang, Card c1, string ref1 = null, string ref2 = null) inline
Definition at line 6250 of file Card.cs.
    {
        if (ShouldShowMsg)
        {
            Msg.Say(IsPC ? Lang.Game.TryGetId(lang + "_pc", lang) : lang, c1, ref1, ref2);
        }
        Msg.SetColor();
    }
References Lang.Game, Msg.Say(), Msg.SetColor(), and SourceLang< T >.TryGetId().
Say() [3/3]
void Card.Say (string lang, string ref1 = null, string ref2 = null) inline
Definition at line 6232 of file Card.cs.
    {
        if (ShouldShowMsg)
        {
            Msg.Say(IsPC ? Lang.Game.TryGetId(lang + "_pc", lang) : lang, ref1, ref2);
        }
        Msg.SetColor();
    }
References Lang.Game, Msg.Say(), Msg.SetColor(), and SourceLang< T >.TryGetId().
Referenced by Chara._Move(), InvOwnerBlend._OnProcess(), TraitShrine._OnUse(), ActPlan._Update(), TraitSwitch.ActivateTrap(), RecipeManager.Add(), Chara.AddRandomBodyPart(), ActMelee.Attack(), Point.CallGuard(), ElementContainerCard.CheckSkillActions(), TraitCrafter.Craft(), AI_OpenLock.CreateProgress(), Decay(), Chara.Die(), Chara.DoHostileAction(), CharaBody.Equip(), AI_Fish.ProgressFish.Fail(), AI_Fuck.Finish(), AI_Massage.Finish(), Chara.GiveGift(), Chara.GiveLovePotion(), TraitGamble.IdleUse(), Condition.Kill(), LevelUp(), ActEffect.LoveMiracle(), Chara.MakeAlly(), AI_Fish.Makefish(), StatsMana.Mod(), TraitBaseSpellbook.ModCharge(), ModCharge(), TraitWell.ModCharges(), TraitChangingRoom.OnActivateTrap(), TraitTrap.OnActivateTrap(), ConSleep.OnBeforeStart(), TraitDrink.OnBlend(), AI_PassTime.OnCancel(), Stats.OnChangePhase(), TraitBrewery.OnChildDecay(), InvOwner.OnClick(), TaskChopWood.OnCreateProgress(), TaskDig.OnCreateProgress(), TaskDrawWater.OnCreateProgress(), TaskHarvest.OnCreateProgress(), TaskMine.OnCreateProgress(), TaskPlow.OnCreateProgress(), TaskPourWater.OnCreateProgress(), TraitDrinkMilkMother.OnDrink(), Affinity.OnGift(), GrowSystemTree.OnHitFail(), ElementContainerCard.OnLevelUp(), ElementContainerCard.OnModTempPotential(), TraitAltar.OnOffer(), AI_Fish.ProgressFish.OnProgressComplete(), TaskBuild.OnProgressComplete(), TraitBaseSpellbook.OnRead(), TraitBookSecret.OnRead(), TraitBookSkill.OnRead(), TraitScrollStatic.OnRead(), ConSleep.OnRemoved(), AI_Read.OnSetOwner(), AI_Fish.ProgressFish.OnStart(), TraitFloorSwitch.OnStepped(), TraitMiniPool.OnStepped(), TraitFoodPreparedPackage.OnUse(), TraitGiftJure.OnUse(), TraitGiftNewYear.OnUse(), TraitGiftPack.OnUse(), TraitItemProc.OnUse(), TraitParcel.OnUse(), TraitPlamoBox.OnUse(), TraitWhistlePeace.OnUse(), TraitFoodMeat.OnUse(), TraitPotionEmpty.OnUse(), DramaManager.ParseLine(), ActBash.Perform(), ActDrawWater.Perform(), ActDreamBug.Perform(), ActRanged.Perform(), ActRush.Perform(), ActSummonGuard.Perform(), ActWater.Perform(), ActZap.Perform(), AttackProcess.Perform(), BaseCondition.PhaseMsg(), ConBuffStats.PlayEffect(), Trait.PlayToggleEffect(), ActEffect.Poison(), GrowSystem.PopHarvest(), ActPray.Pray(), AI_Pray.Pray(), FoodEffect.Proc(), ActEffect.Proc(), ActEffect.ProcAt(), InvOwner.Transaction.Process(), TraitBaseSpellbook.ReadFailEffect(), TraitGenerator.Recover(), Chara.RemoveLastBodyPart(), TraitShackle.Restrain(), ActRide.Ride(), AI_ArmPillow.Run(), AI_Clean.Run(), AI_Craft_Snowman.Run(), AI_Eat.Run(), AI_Fuck.Run(), AI_Haul.Run(), AI_Idle.Run(), AI_Massage.Run(), AI_OpenGambleChest.Run(), AI_PassTime.Run(), AI_PlayMusic.Run(), AI_Read.Run(), AI_Shear.Run(), AI_Slaughter.Run(), AI_Steal.Run(), AI_Trolley.Run(), GoalCombat.Run(), TaskClean.Run(), TaskWater.Run(), TraitGenerator.ShortOut(), DramaOutcome.sister_friend(), AI_Trolley.Stop(), Chara.Stumble(), ActThrow.Throw(), ConInsane.Tick(), ConSleep.Tick(), Trait.Toggle(), TraitDoorAutoShoji.ToggleDoor(), TraitToolTorch.ToggleOn(), Zone.TryAddThingInSharedContainer(), AIAct.TryCancel(), TraitSwitch.TryDisarmTrap(), ThingGen.TryLickChest(), Thing.TryLickEnchant(), BaseCondition.TryNullify(), TraitDoor.TryOpen(), Trait.TryOpenLock(), ActPray.TryPray(), TraitBaseSpellbook.TryProgress(), ActRanged.TryReload(), TraitDoor.TrySetAct(), TraitWell.TrySetAct(), CharaBody.Unequip(), CharaBody.UnqeuipIfTooHeavy(), and ActRide.Unride().
SayNothingHappans()
void Card.SayNothingHappans () inline
Definition at line 6227 of file Card.cs.
    {
        Say("nothingHappens");
    }
Referenced by TraitMoongateEx._OnUse(), ActEffect.DamageEle(), Chara.GiveGift(), TraitDiary.OnRead(), ActEffect.Proc(), Religion.Punish(), Religion.PunishTakeOver(), TraitBaseSpellbook.ReadFailEffect(), LayerDragGrid.TryProc(), and TraitMoongate.UseMoongate().
SayRaw()
void Card.SayRaw (string text, string ref1 = null, string ref2 = null) inline
Definition at line 6211 of file Card.cs.
    {
        if (isSynced && !text.IsEmpty())
        {
            if (ref1 != null)
            {
                text = text.Replace("#1", ref1);
            }
            if (ref2 != null)
            {
                text = text.Replace("#2", ref2);
            }
            HostRenderer.Say(text);
        }
    }
Referenced by CoreDebug.BroadcastNext().
SecondaryCompare()
virtual int Card.SecondaryCompare (UIList::SortMode m, Card c) inline virtual
Definition at line 7136 of file Card.cs.
    {
        int num = 0;
        if (num == 0)
        {
            num = id.CompareTo(c.id);
        }
        if (num == 0)
        {
            num = trait.CompareTo(c);
        }
        if (num == 0)
        {
            num = Lang.comparer.Compare(GetName(NameStyle.Full, 1), c.GetName(NameStyle.Full, 1));
        }
        if (num == 0)
        {
            num = refVal - c.refVal;
        }
        if (num == 0)
        {
            num = c_charges - c.c_charges;
        }
        if (num == 0)
        {
            num = encLV - c.encLV;
        }
        if (num == 0)
        {
            num = Num - c.Num;
        }
        if (num == 0)
        {
            num = uid - c.uid;
        }
        return num;
    }
References c_charges, Lang.comparer, Trait.CompareTo(), encLV, GetName(), id, Num, refVal, and uid.
SetBlessedState()
virtual void Card.SetBlessedState (BlessedState s) inline virtual
Definition at line 3642 of file Card.cs.
    {
        int num = 0;
        if (s == BlessedState.Blessed && blessedState < BlessedState.Blessed)
        {
            num = 1;
        }
        if (s < BlessedState.Blessed && blessedState == BlessedState.Blessed)
        {
            num = -1;
        }
        if (num != 0 && IsEquipmentOrRangedOrAmmo)
        {
            if (IsWeapon || IsAmmo)
            {
                elements.ModBase(67, num);
            }
            else
            {
                elements.ModBase(65, num * 2);
            }
        }
        blessedState = s;
    }
References blessedState, elements, IsAmmo, IsEquipmentOrRangedOrAmmo, IsWeapon, and ElementContainer.ModBase().
Referenced by Recipe.Craft(), RecipeCard.Craft(), Player.CreateEquip(), FactionBranch.DailyOutcome(), AI_Fish.Makefish(), TraitSeed.MakeSeed(), Chara.MutateRandom(), TraitDrink.OnBlend(), Thing.OnCreate(), TaskHarvest.OnCreateProgress(), TraitAltar.OnOffer(), TraitPotionEmpty.OnUse(), ActEffect.Proc(), CoreDebug.QuickStart(), and AI_UseCrafter.Run().
SetCensored()
void Card.SetCensored (bool enable) inline
Definition at line 7074 of file Card.cs.
    {
        isCensored = enable;
        if (EClass.core.config.other.noCensor)
        {
            isCensored = false;
        }
        renderer.SetCensored(isCensored);
    }
References Core.config, EClass.core, CoreConfig.OtherSetting.noCensor, CoreConfig.other, and CardRenderer.SetCensored().
Referenced by AI_Slaughter.OnCancelOrSuccess(), AI_Bladder.OnReset(), AI_Bladder.Run(), and AI_Slaughter.Run().
SetCharge()
void Card.SetCharge (int a) inline
Definition at line 3691 of file Card.cs.
    {
        c_charges = a;
        LayerInventory.SetDirty(Thing);
    }
References c_charges, and LayerInventory.SetDirty().
Referenced by Zone_CursedManorDungeon.OnGenerateMap(), and ActDrawWater.Perform().
SetDeconstruct()
void Card.SetDeconstruct (bool deconstruct) inline
Definition at line 7084 of file Card.cs.
    {
        if (isDeconstructing != deconstruct)
        {
            if (deconstruct)
            {
                EClass._map.props.deconstructing.Add(this);
            }
            else
            {
                EClass._map.props.deconstructing.Remove(this);
            }
            isDeconstructing = deconstruct;
        }
    }
References EClass._map, PropsManager.deconstructing, and Map.props.
Referenced by InspectGroupThing.OnSetActions(), and AI_Deconstruct.Run().
SetDir()
virtual void Card.SetDir (int d) inline virtual
Reimplemented in Chara.
Definition at line 5641 of file Card.cs.
    {
        dir = d;
        renderer.RefreshSprite();
    }
References CardRenderer.RefreshSprite().
Referenced by RecipeCard.Build(), CharaRenderer.DrawHeld(), and TraitPillowStrange.TrySetAct().
SetDirtyWeight()
void Card.SetDirtyWeight () inline
Definition at line 2454 of file Card.cs.
    {
        if (EClass.core.IsGameStarted && IsPC)
        {
            EClass.player.wasDirtyWeight = true;
        }
        dirtyWeight = true;
        (parent as Card)?.SetDirtyWeight();
    }
References EClass.core, dirtyWeight, Core.IsGameStarted, IsPC, parent, and SetDirtyWeight().
Referenced by AddThing(), ChangeMaterial(), ChangeWeight(), ModNum(), AttbMain.OnChangeValue(), Skill.OnChangeValue(), ActEffect.Proc(), Religion.PunishTakeOver(), RemoveThing(), SetDirtyWeight(), and SetLv().
SetEncLv()
void Card.SetEncLv (int a) inline
Definition at line 3611 of file Card.cs.
    {
        ModEncLv(a - encLV);
    }
References encLV, and ModEncLv().
Referenced by TraitCrafter.Craft(), RecipeCard.Craft(), AI_Shear.GetFur(), CraftUtil.MakeDish(), Chara.MakeMilk(), TraitSeed.MakeSeed(), Thing.OnCreate(), TaskHarvest.OnCreateProgress(), TraitAltar.OnOffer(), and CoreDebug.UpdateInput().
SetFreePos()
void Card.SetFreePos (Point point) inline
Definition at line 5709 of file Card.cs.
    {
        freePos = EClass.game.config.FreePos && isThing && TileType.FreeStyle && !sourceCard.multisize && !EClass.scene.actionMode.IsRoofEditMode(this);
        if (freePos)
        {
            Vector3 vector = point.Position();
            Vector3 thingPosition = EClass.screen.tileMap.GetThingPosition(this, point);
            fx = EInput.mposWorld.x + EClass.setting.render.freePosFix.x;
            fy = EInput.mposWorld.y + EClass.setting.render.freePosFix.y;
            if (EClass.game.config.snapFreePos)
            {
                fx -= fx % 0.2f;
                fy -= fy % 0.1f;
            }
            fx = fx - vector.x + thingPosition.x;
            fy = fy - vector.y + thingPosition.y;
        }
        else
        {
            float num2 = (fy = 0f);
            fx = num2;
        }
    }
References Scene.actionMode, Game.config, GameSetting.RenderSetting.freePosFix, EClass.game, BaseTileMap.GetThingPosition(), ActionMode.IsRoofEditMode(), Point.Position(), GameSetting.render, EClass.scene, EClass.screen, EClass.setting, Game.Config.snapFreePos, and BaseGameScreen.tileMap.
Referenced by RecipeCard.OnRenderMarker().
SetHidden()
Card Card.SetHidden (bool hide = true) inline
Definition at line 5291 of file Card.cs.
    {
        isHidden = hide;
        pos.cell.Refresh();
        return this;
    }
References Point.cell, and Cell.Refresh().
Referenced by ApplyEditorTags(), Create(), TraitSwitch.OnInstall(), TraitFloorSwitch.OnStepped(), and ActWait.SearchMedal().
SetImage() [1/2]
virtual void Card.SetImage (Image image) inline virtual
Definition at line 5541 of file Card.cs.
    {
        if (trait is TraitAbility)
        {
            (trait as TraitAbility).act.SetImage(image);
        }
        else
        {
            sourceRenderCard.SetImage(image, GetSprite(), colorInt);
        }
    }
References RenderRow.SetImage().
SetImage() [2/2]
void Card.SetImage (Image image, int dir, int idSkin = 0) inline
Definition at line 5536 of file Card.cs.
    {
        sourceRenderCard.SetImage(image, GetSprite(dir), colorInt, setNativeSize: true, dir, idSkin);
    }
References RenderRow.SetImage().
Referenced by WidgetPopText._SayPick(), WindowCharaMini.RefreshEquipment(), WindowChara.RefreshEquipment(), GridItemCard.SetButton(), GridItemCardSource.SetButton(), ButtonGeneral.SetCard(), ButtonGrid.SetCard(), ButtonRoster.SetChara(), ItemGeneral.SetChara(), Portrait.SetChara(), HotItemThing.SetImage(), LayerDragGrid.SetInv(), ButtonGrid.SetRecipe(), LayerCraftFloat.ShowContextMenu(), and WidgetInspector.SwitchPage().
SetLv()
Card Card.SetLv (int a) inline
Definition at line 2784 of file Card.cs.
    {
        LV = a;
        if (!isChara)
        {
            return this;
        }
        Rand.SetSeed(uid);
        ElementContainer elementContainer = new ElementContainer();
        elementContainer.ApplyElementMap(uid, SourceValueType.Chara, Chara.job.elementMap, LV);
        elementContainer.ApplyElementMap(uid, SourceValueType.Chara, Chara.race.elementMap, LV);
        elementContainer.ApplyElementMap(uid, SourceValueType.Chara, Chara.source.elementMap, 1, invert: false, applyFeat: true);
        foreach (Element value in elements.dict.Values)
        {
            int num = elementContainer.Value(value.id);
            if (num != 0)
            {
                int num2 = num - value.ValueWithoutLink;
                if (num2 != 0)
                {
                    elements.ModBase(value.id, num2);
                }
            }
        }
        Rand.SetSeed();
        hp = MaxHP;
        Chara.mana.value = Chara.mana.max;
        Chara.CalculateMaxStamina();
        SetDirtyWeight();
        return this;
    }
References ElementContainer.ApplyElementMap(), Chara.CalculateMaxStamina(), ElementContainer.dict, elements, hp, Element.id, isChara, Chara.job, LV, Chara.mana, Stats.max, MaxHP, ElementContainer.ModBase(), Chara.race, SetDirtyWeight(), Rand.SetSeed(), Chara.source, uid, and Element.ValueWithoutLink.
Referenced by Chara.Die(), ZonePreEnterBout.Execute(), DNA.Generate(), TraitFoodEggFertilized.Incubate(), Trait.OnBarter(), Chara.OnCreate(), TraitMonsterBall.OnCreate(), TraitPowerStatue.OnCreate(), TraitDrinkMilkMother.OnDrink(), ActEffect.ProcAt(), CoreDebug.QuickStart(), SerializedCards.Restore(), and CoreDebug.Spawn().
SetNoSell()
Thing Card.SetNoSell () inline
Definition at line 3300 of file Card.cs.
    {
        noSell = true;
        return this as Thing;
    }
References noSell, and Thing.
Referenced by DramaOutcome.fiama_starter_gift(), and TraitGiftJure.OnUse().
SetNum()
Thing Card.SetNum (int a) inline
Definition at line 3286 of file Card.cs.
    {
        if (!isThing)
        {
            return null;
        }
        if (a == Num)
        {
            return this as Thing;
        }
        ModNum(a - Num);
        return this as Thing;
    }
References isThing, ModNum(), Num, and Thing.
Referenced by ThingGen._Create(), InvOwnerRecycle._OnProcess(), Add(), ThingContainer.AddCurrency(), DropdownGrid.BuildIngredients(), TraitCrafter.Craft(), RecipeCard.Craft(), ThingGen.CreateCurrency(), Player.CreateEquip(), ThingGen.CreatePerfume(), ThingGen.CreatePotion(), ThingGen.CreateScroll(), ThingGen.CreateSkillbook(), ThingGen.CreateSpellbook(), Trait.CreateStock(), FactionBranch.DailyOutcome(), Decay(), Recipe.DropIngredients(), Duplicate(), Chara.EQ_Item(), ZonePreEnterBoutWin.Execute(), DramaOutcome.fiama_gold(), DramaOutcome.fiama_starter_gift(), AI_Fuck.Finish(), FactionBranch.GetDailyIncome(), AI_Shear.GetFur(), FortuneRollData.GetPrize(), MiniGame.GetSlotReward(), TaskHarvest.HarvestThing(), Chara.MakeEgg(), AI_Fish.Makefish(), Chara.MakeMilk(), AI_OpenGambleChest.MakeReward(), Map.MineObj(), Faction.OnAdvanceMonth(), Trait.OnBarter(), QuestVernis.OnChangePhase(), TraitBrewery.OnChildDecay(), QuestLoytelFarm.OnComplete(), TaskChopWood.OnCreateProgress(), TaskHarvest.OnCreateProgress(), QuestDefense.OnDropReward(), QuestRandom.OnDropReward(), Zone_CursedManorDungeon.OnGenerateMap(), GrowSystemTree.OnMineObj(), TraitGiftJure.OnUse(), InvOwnerDeliver.PayBill(), Chara.PickOrDrop(), TraitGacha.PlayGacha(), TraitBaseContainer.Prespawn(), TraitContainerCurrency.Prespawn(), FoodEffect.Proc(), ActEffect.Proc(), DramaOutcome.QuestDefense_1(), CoreDebug.QuickStart(), LayerCraft.RefreshProduct(), Chara.RestockInventory(), AI_OpenGambleChest.Run(), AI_Steal.Run(), TaskCullLife.Run(), GameDate.ShipGoods(), GameDate.ShipRandomPackages(), CoreDebug.Spawn(), SpawnLoot(), AI_PlayMusic.ThrowReward(), Recipe.TryGetFirstTimeBonus(), GrowSystem.TryPick(), Chara.TryPoisonPotion(), and TraitFoodEgg.Update().
SetPaintData()
void Card.SetPaintData () inline
Definition at line 6445 of file Card.cs.
    {
        EClass.ui.Hide(0f);
        EClass.core.WaitForEndOfFrame(delegate
        {
            ClearPaintSprite();
            c_textureData = GetPaintData();
            EClass.core.WaitForEndOfFrame(delegate
            {
                EClass.ui.Show(0f);
            });
        });
    }
References EClass.core, EClass.ui, and BaseCore.WaitForEndOfFrame().
SetPlaceState()
void Card.SetPlaceState (PlaceState newState, bool byPlayer = false) inline
Definition at line 3498 of file Card.cs.
    {
        if (this.placeState == newState)
        {
            return;
        }
        if (parent != EClass._zone)
        {
            Debug.Log("tried to change placestate of non-root card:" + this);
            return;
        }
        PlaceState placeState = this.placeState;
        Area area = pos.area;
        if (placeState == PlaceState.installed)
        {
            area?.OnUninstallCard(this);
            if (!isRoofItem)
            {
                altitude = 0;
                freePos = false;
                float num2 = (fy = 0f);
                fx = num2;
            }
            trait.Uninstall();
        }
        if (placeState == PlaceState.installed || newState == PlaceState.installed)
        {
            ForeachPoint(delegate(Point p, bool main)
            {
                p.cell.RemoveCard(this);
            });
            this.placeState = newState;
            ForeachPoint(delegate(Point p, bool main)
            {
                p.cell.AddCard(this);
            });
        }
        else
        {
            this.placeState = newState;
        }
        if (newState == PlaceState.none)
        {
            this.placeState = PlaceState.roaming;
            if (props != null)
            {
                props.Remove(this);
            }
        }
        else
        {
            EClass._map.props.OnCardAddedToZone(this);
            if (this.placeState == PlaceState.installed)
            {
                if (isThing)
                {
                    if (trait.InstallBottomPriority != -1)
                    {
                        pos.detail.MoveThingToBottom(Thing);
                    }
                    else
                    {
                        pos.detail.MoveThingToTop(Thing);
                    }
                }
                area?.OnInstallCard(this);
                isRoofItem = false;
                trait.Install(byPlayer);
            }
        }
        if (trait.ShouldRefreshTile)
        {
            pos.RefreshNeighborTiles();
        }
        if (trait.ShouldTryRefreshRoom && (placeState == PlaceState.installed || this.placeState == PlaceState.installed))
        {
            EClass._map.OnSetBlockOrDoor(pos.x, pos.z);
        }
        trait.OnChangePlaceState(newState);
        if (EClass._zone.IsPCFaction)
        {
            EClass.Branch.resources.SetDirty();
        }
    }
References EClass._map, EClass._zone, Cell.AddCard(), altitude, Point.area, EClass.Branch, Point.cell, Debug, Point.detail, ForeachPoint(), freePos, fx, fy, Trait.Install(), Trait.InstallBottomPriority, Zone.IsPCFaction, isRoofItem, isThing, CellDetail.MoveThingToBottom(), CellDetail.MoveThingToTop(), PropsManager.OnCardAddedToZone(), Trait.OnChangePlaceState(), Area.OnInstallCard(), Map.OnSetBlockOrDoor(), Area.OnUninstallCard(), parent, placeState, pos, props, Map.props, Point.RefreshNeighborTiles(), Props.Remove(), Cell.RemoveCard(), FactionBranch.resources, HomeResourceManager.SetDirty(), Trait.ShouldRefreshTile, Trait.ShouldTryRefreshRoom, trait, Trait.Uninstall(), Point.x, and Point.z.
Referenced by RecipeCard.Build(), Zone.ClaimZone(), ZonePreEnterDigStairs.Execute(), CoreDebug.GetOrCreateDebugContainer(), Install(), Map.OnCardRemovedFromZone(), AM_MoveInstalled.OnProcessTiles(), TaskMoveInstalled.OnProgressComplete(), InspectGroupThing.OnSetActions(), TraitCurrencyMedal.OnStepped(), TraitStairsLocked.OnUse(), ActRestrain.Perform(), AI_Steal.Run(), DramaOutcome.Tutorial1(), and CoreDebug.UpdateInput().
SetPriceFix()
Thing Card.SetPriceFix (int a) inline
Definition at line 6571 of file Card.cs.
    {
        c_priceFix = a;
        return Thing;
    }
Referenced by Trait.CreateStock(), and Trait.OnBarter().
SetRandomDir()
void Card.SetRandomDir () inline
Definition at line 5647 of file Card.cs.
    {
        SetDir(EClass.rnd(4));
    }
References EClass.rnd().
Referenced by Zone.TryGenerateShrine().
SetRandomLightColors()
void Card.SetRandomLightColors () inline
Definition at line 5946 of file Card.cs.
    {
        c_lightColor = (byte)(EClass.rnd(8) + 1) * 1024 + (byte)(EClass.rnd(8) + 1) * 32 + (byte)(EClass.rnd(8) + 1);
    }
References EClass.rnd().
SetRandomTalk()
void Card.SetRandomTalk () inline
Definition at line 6332 of file Card.cs.
    {
        MOD.listTalk.Initialize();
        if (!MOD.listTalk.list[0].ContainsKey(id))
        {
            c_idTalk = MOD.listTalk.GetRandomID("human");
        }
    }
References TalkDataList.GetRandomID(), ExcelDataList.Initialize(), ExcelDataList.list, and MOD.listTalk.
Referenced by Biography.Generate().
SetRandomTone()
void Card.SetRandomTone () inline
Definition at line 6341 of file Card.cs.
    {
        MOD.tones.Initialize();
        List<Dictionary<string, string>> list = MOD.tones.list;
        if (list.Count == 0)
        {
            return;
        }
        string text = list.RandomItem()["id"];
        for (int i = 0; i < 10; i++)
        {
            Dictionary<string, string> dictionary = list.RandomItem();
            if (EClass.rnd(100) <= dictionary["chance"].ToInt())
            {
                text = dictionary["id"];
                break;
            }
        }
        c_idTone = MOD.tones.GetToneID(text, bio?.gender ?? 0);
    }
References ToneDataList.GetToneID(), ExcelDataList.Initialize(), ExcelDataList.list, EClass.rnd(), and MOD.tones.
Referenced by Biography.Generate().
SetRenderParam()
virtual void Card.SetRenderParam (RenderParam p) inline virtual
Reimplemented in Chara, and Thing.
Definition at line 5439 of file Card.cs.
    {
    }
Referenced by CardRenderer.Draw(), and CharaRenderer.DrawHeld().
SetReplica()
void Card.SetReplica (bool on) inline
Definition at line 2921 of file Card.cs.
    {
        isReplica = true;
        ChangeMaterial("granite");
    }
References ChangeMaterial, and isReplica.
SetSale()
void Card.SetSale (bool sale) inline
Definition at line 6582 of file Card.cs.
    {
        if (isSale != sale)
        {
            isSale = sale;
            if (isSale)
            {
                EClass._map.props.sales.Add(this);
            }
            else
            {
                EClass._map.props.sales.Remove(this);
            }
        }
    }
References EClass._map, Map.props, and PropsManager.sales.
Referenced by AI_Slaughter.Run().
SetSortVal()
virtual void Card.SetSortVal (UIList::SortMode m, CurrencyType currency = CurrencyType::Money) inline virtual
Reimplemented in Chara.
Definition at line 7105 of file Card.cs.
    {
        switch (m)
        {
        case UIList.SortMode.ByEquip:
            sortVal = ((c_equippedSlot == 0) ? (category.sortVal * 1000) : 0);
            break;
        case UIList.SortMode.ByValue:
            sortVal = -GetPrice(currency) * 1000;
            break;
        case UIList.SortMode.ByNumber:
            sortVal = -Num * 1000;
            break;
        case UIList.SortMode.ByCategory:
            sortVal = category.sortVal * 1000;
            break;
        case UIList.SortMode.ByWeight:
            sortVal = -ChildrenAndSelfWeight * 1000;
            break;
        case UIList.SortMode.ByWeightSingle:
            sortVal = -ChildrenAndSelfWeightSingle * 1000;
            break;
        case UIList.SortMode.ByPrice:
            sortVal = -GetPrice(currency) * 1000;
            break;
        default:
            sortVal = sourceCard._index * 1000;
            break;
        }
    }
References currency, and SourceCategory.Row.sortVal.
Referenced by CoreExtension.Sort().
SetSource()
virtual void Card.SetSource () inline virtual
Reimplemented in Chara, and Thing.
Definition at line 2734 of file Card.cs.
    {
    }
Referenced by _OnDeserialized(), and Create().
SetTier()
void Card.SetTier (int a, bool setTraits = true) inline
Definition at line 3616 of file Card.cs.
    {
        if (a < 0)
        {
            a = 0;
        }
        tier = a;
        if (setTraits)
        {
            int num = ((a == 1) ? 180 : ((a == 2) ? 400 : ((a >= 3) ? 600 : 0)));
            if (a > 0)
            {
                foreach (Element value in elements.dict.Values)
                {
                    if (value.IsFoodTrait || value.IsTrait)
                    {
                        elements.SetTo(value.id, value.Value * num / 100);
                    }
                }
            }
            elements.SetBase(2, a * 30);
            elements.SetBase(759, (a > 1) ? a : 0);
        }
        LayerInventory.SetDirty(Thing);
    }
References ElementContainer.dict, elements, Element.id, Element.IsFoodTrait, Element.IsTrait, ElementContainer.SetBase(), LayerInventory.SetDirty(), ElementContainer.SetTo(), tier, and Element.Value.
Referenced by FactionBranch.DailyOutcome(), AI_Fish.Makefish(), and CoreDebug.UpdateInput().
ShouldTrySetDirtyInventory()
bool Card.ShouldTrySetDirtyInventory () inline
Definition at line 3170 of file Card.cs.
    {
        if (EClass.player.chara != null)
        {
            if (!IsPC && GetRootCard() != EClass.pc)
            {
                return EClass.ui.layers.Count > 0;
            }
            return true;
        }
        return false;
    }
References Player.chara, GetRootCard(), IsPC, EClass.pc, and EClass.player.
Referenced by AddThing(), OnChildNumChange(), and RemoveThing().
ShowEmo()
void Card.ShowEmo (Emo _emo = Emo::none, float duration = 0f, bool skipSame = true) inline
Definition at line 5553 of file Card.cs.
    {
        if ((!isChara || Chara.host == null) && !(_emo == lastEmo && skipSame))
        {
            if (_emo != 0)
            {
                renderer.ShowEmo(_emo, duration);
            }
            lastEmo = _emo;
        }
    }
References Chara.host, and CardRenderer.ShowEmo().
Referenced by RecipeManager.Add(), Chara.Cuddle(), Chara.DoHostileAction(), ZonePreEnterEncounter.Execute(), AI_Fuck.Finish(), AI_Massage.Finish(), Chara.GiveLovePotion(), Chara.HoldCard(), TraitGamble.IdleUse(), Chara.ModAffinity(), InvOwner.OnClick(), AI_Idle.OnStart(), AI_UseCrafter.OnStart(), ConDrunk.OnStart(), TaskCut.OnStart(), AI_Bladder.Run(), AI_Eat.Run(), AI_PlayMusic.Run(), AI_Slaughter.Run(), and GoalCombat.Run().
SpawnLoot()
void Card.SpawnLoot (Card origin) inline
Definition at line 4720 of file Card.cs.
    {
        if (!isChara || IsPCFactionMinion || (isCopy && EClass.rnd(10) != 0))
        {
            return;
        }
        bool isUserZone = EClass._zone.IsUserZone;
        bool flag = EClass._zone is Zone_Music;
        List<Card> list = new List<Card>();
        SourceRace.Row race = Chara.race;
        if (!IsPCFaction && !isUserZone && sourceCard.idActor.IsEmpty())
        {
            int i2 = 500;
            if (this.rarity >= Rarity.Legendary)
            {
                i2 = ((!EClass.player.codex.DroppedCard(id)) ? 1 : 10);
                EClass.player.codex.MarkCardDrop(id);
            }
            if (trait is TraitAdventurerBacker)
            {
                i2 = 10;
            }
            if (chance(i2))
            {
                Thing thing = ThingGen.Create("figure");
                thing.MakeFigureFrom(id);
                list.Add(thing);
            }
            if (chance(i2))
            {
                Thing thing2 = ThingGen.Create("figure3");
                thing2.MakeFigureFrom(id);
                list.Add(thing2);
            }
        }
        bool flag2 = Chara.race.corpse[1].ToInt() > EClass.rnd(1500) || (Chara.IsPowerful && !IsPCFaction) || EClass.debug.godFood;
        int num = 1;
        if (!IsMinion && Chara.race.IsAnimal && EClass.rnd(EClass._zone.IsPCFaction ? 3 : 5) == 0)
        {
            flag2 = true;
        }
        if (AI_Slaughter.slaughtering)
        {
            flag2 = true;
            num = EClass.rndHalf(4 + 10 * (50 + Mathf.Max(0, (int)MathF.Sqrt(EClass.pc.Evalue(290) * 10))) / 100);
        }
        else if (origin != null && origin.HasElement(290) && !IsMinion)
        {
            if (!flag2 && Chara.race.corpse[1].ToInt() > EClass.rnd(150000 / (100 + (int)Mathf.Sqrt(origin.Evalue(290)) * 5)))
            {
                flag2 = true;
                origin.elements.ModExp(290, 100);
            }
            else
            {
                origin.elements.ModExp(290, 5);
            }
        }
        if (id == "littleOne" && IsPCFactionOrMinion)
        {
            flag2 = false;
        }
        if (flag2 && !isUserZone)
        {
            string text = Chara.race.corpse[0];
            bool num2 = text == "_meat";
            int num3 = 10;
            if (AI_Slaughter.slaughtering)
            {
                num3 += (int)Mathf.Min(Mathf.Sqrt(EClass.pc.Evalue(290)), 20f);
            }
            if (num2 && num3 > EClass.rnd(100))
            {
                text = "meat_marble";
            }
            Thing thing3 = ThingGen.Create(text).SetNum(num);
            if (thing3.source._origin == "meat")
            {
                thing3.MakeFoodFrom(this);
            }
            else
            {
                thing3.ChangeMaterial(Chara.material);
            }
            list.Add(thing3);
        }
        if (!IsPCFaction && (!isUserZone || !EClass.game.principal.disableUsermapBenefit) && chance(200))
        {
            list.Add(Chara.MakeGene());
        }
        if (!IsPCFaction && !isUserZone)
        {
            foreach (string item2 in sourceCard.loot.Concat(Chara.race.loot).ToList())
            {
                string[] array = item2.Split('/');
                int num4 = array[1].ToInt();
                if (num4 >= 1000 || num4 > EClass.rnd(1000) || EClass.debug.godMode)
                {
                    list.Add(ThingGen.Create(array[0]).SetNum((num4 < 1000) ? 1 : (num4 / 1000 + ((EClass.rnd(1000) > num4 % 1000) ? 1 : 0))));
                }
            }
            if (race.IsMachine)
            {
                if (chance(20))
                {
                    list.Add(ThingGen.Create("microchip"));
                }
                if (chance(15))
                {
                    list.Add(ThingGen.Create("battery"));
                }
            }
            else
            {
                if (race.IsAnimal)
                {
                    if (chance(15))
                    {
                        list.Add(ThingGen.Create("fang"));
                    }
                    if (chance(10))
                    {
                        list.Add(ThingGen.Create("skin"));
                    }
                }
                if (chance(20))
                {
                    list.Add(ThingGen.Create("offal"));
                }
                if (chance(20))
                {
                    list.Add(ThingGen.Create("heart"));
                }
            }
            if (!isBackerContent && !flag)
            {
                switch (id)
                {
                case "isca":
                    list.Add(ThingGen.Create("blood_angel"));
                    break;
                case "golem_wood":
                    if (chance(30))
                    {
                        list.Add(ThingGen.Create("crystal_earth"));
                    }
                    break;
                case "golem_stone":
                    if (chance(30))
                    {
                        list.Add(ThingGen.Create("crystal_sun"));
                    }
                    break;
                case "golem_steel":
                    if (chance(30))
                    {
                        list.Add(ThingGen.Create("crystal_mana"));
                    }
                    break;
                case "golem_gold":
                    list.Add(ThingGen.Create("money2"));
                    break;
                }
                int num5 = ((EClass._zone.Boss == this) ? 2 : ((this.rarity >= Rarity.Legendary) ? 1 : 0));
                if (EClass._zone is Zone_Void)
                {
                    num5++;
                }
                if (EClass.rnd(5) == 0)
                {
                    num5++;
                }
                string text2 = id;
                if (text2 == "big_daddy" || text2 == "santa")
                {
                    num5 += 2;
                }
                if (num5 > 0 && EClass.game.principal.dropRate)
                {
                    num5 = Mathf.Max(1, num5 * (50 + EClass.game.principal.dropRateMtp * 50) / 100);
                }
                List<Thing> list2 = new List<Thing>();
                foreach (Thing thing4 in things)
                {
                    if (thing4.HasTag(CTAG.gift) || thing4.trait is TraitChestMerchant)
                    {
                        continue;
                    }
                    if (thing4.isGifted || thing4.rarity >= Rarity.Artifact || thing4.trait.DropChance > EClass.rndf(1f))
                    {
                        list.Add(thing4);
                    }
                    else if (thing4.IsEquipmentOrRanged)
                    {
                        if (thing4.rarity >= Rarity.Legendary)
{
                            list2.Add(thing4);
                        }
                        else if (EClass.rnd(100) == 0)
{
                            list.Add(thing4);
                        }
                    }
                    else if (EClass.rnd(5) == 0)
                    {
                        list.Add(thing4);
                    }
                }
                if (num5 > 0 && list2.Count > 0)
                {
                    list2.Shuffle();
                    for (int j = 0; j < list2.Count && j < num5; j++)
                    {
                        list.Add(list2[j]);
                        num5--;
                    }
                }
                if (this.rarity >= Rarity.Legendary && !IsUnique && c_bossType != BossType.Evolved)
                {
                    int num6 = 0;
                    foreach (Card item3 in list)
                    {
                        if (item3.rarity >= Rarity.Legendary || item3.IsContainer)
{
                            num6++;
                        }
                    }
                    if (num6 == 0)
                    {
                        int num7 = ((!(EClass._zone is Zone_Void)) ? 1 : 2);
                        if (num5 < num7)
{
                            num5 = num7;
                        }
                        for (int k = 0; k < num5; k++)
{
                            Rand.SetSeed(uid + k);
                            if (EClass.rnd((EClass._zone.events.GetEvent<ZoneEventDefenseGame>() != null) ? 3 : 2) == 0)
{
                                Rarity rarity = ((EClass.rnd(20) == 0) ? Rarity.Mythical : Rarity.Legendary);
                                CardBlueprint.Set(new CardBlueprint
{
                                    rarity = rarity
                                });
                                Thing item = ThingGen.CreateFromFilter("eq", LV);
                                list.Add(item);
                            }
                            else if (EClass.rnd(3) == 0)
{
                                list.Add(ThingGen.Create("medal"));
                            }
                            Rand.SetSeed();
                        }
                    }
                }
            }
        }
        foreach (Thing thing5 in things)
        {
            if (thing5.GetInt(116) != 0)
            {
                list.Add(thing5);
            }
        }
        Point nearestPoint = GetRootCard().pos;
        if (nearestPoint.IsBlocked)
        {
            nearestPoint = nearestPoint.GetNearestPoint();
        }
        foreach (Card item4 in list)
        {
            if (item4.parent == EClass._zone)
            {
                continue;
            }
            item4.isHidden = false;
            item4.SetInt(116);
            EClass._zone.AddCard(item4, nearestPoint);
            if (!item4.IsEquipment || item4.rarity < Rarity.Superior || item4.IsCursed)
            {
                continue;
            }
            foreach (Chara chara in EClass._map.charas)
            {
                if (chara.HasElement(1412) && chara.Dist(nearestPoint) < 3)
                {
                    item4.Thing.TryLickEnchant(chara);
                    break;
                }
            }
        }
        bool chance(int i)
        {
            i = i * 100 / (100 + EClass.player.codex.GetOrCreate(id).BonusDropLv * 10);
            if (i < 1)
            {
                i = 1;
            }
            if (IsMinion)
            {
                i *= 5;
            }
            if (EClass.rnd(i) == 0)
            {
                return true;
            }
            return false;
        }
    }
References EClass._map, EClass._zone, Add(), Zone.AddCard(), CodexCreature.BonusDropLv, ChangeMaterial(), Map.charas, Player.codex, ThingGen.Create(), ThingGen.CreateFromFilter(), EClass.debug, GamePrincipal.disableUsermapBenefit, Dist(), Trait.DropChance, CodexManager.DroppedCard(), GamePrincipal.dropRate, GamePrincipal.dropRateMtp, elements, Evalue(), Zone.events, EClass.game, BaseCard.GetInt(), Point.GetNearestPoint(), CodexManager.GetOrCreate(), CoreDebug.godFood, CoreDebug.godMode, HasElement(), HasTag(), CardRow.idActor, if(), SourceRace.Row.IsAnimal, Point.IsBlocked, IsContainer, IsCursed, IsEquipment, IsEquipmentOrRanged, isGifted, SourceRace.Row.IsMachine, Zone.IsPCFaction, Zone.IsUserZone, item, CardRow.loot, MakeFigureFrom(), MakeFoodFrom(), Chara.MakeGene(), CodexManager.MarkCardDrop(), material, ElementContainer.ModExp(), parent, EClass.pc, EClass.player, Game.principal, Chara.race, rarity, EClass.rnd(), EClass.rndf(), EClass.rndHalf(), CardBlueprint.Set(), BaseCard.SetInt(), SetNum(), Rand.SetSeed(), AI_Slaughter.slaughtering, Thing.source, Split(), Thing, trait, and Thing.TryLickEnchant().
Split()
Thing Card.Split (int a) inline
Definition at line 3275 of file Card.cs.
    {
        if (a == Num)
        {
            return Thing;
        }
        Thing result = Duplicate(a);
        ModNum(-a, notify: false);
        return result;
    }
References Duplicate, ModNum(), Num, and Thing.
Referenced by InvOwnerRefuel._OnProcess(), TraitDrink.BlendLove(), TraitDrink.BlendPoison(), RecipeCard.Build(), AI_Shopping.Buy(), TraitCrafter.Craft(), QuestDeliver.Deliver(), FactionBranch.GetMeal(), Chara.HoldCard(), TaskCraft.IsIngredientsValid(), TraitDrink.OnBlend(), DragItemCard.OnDragSpecial(), TaskBuild.OnProgressComplete(), AM_Blueprint.OnSave(), ActThrow.Perform(), ActEffect.Proc(), InvOwner.Transaction.Process(), AI_Paint.Run(), AI_UseCrafter.Run(), LayerPixelPaint.SetCanvas(), Thing.ShowSplitMenu(), SpawnLoot(), Chara.SplitHeld(), AI_PlayMusic.ThrowReward(), Map.TryShatter(), GoalCombat.TryThrow(), and UIDragGridIngredients.Update().
Talk()
void Card.Talk (string idTopic, string ref1 = null, string ref2 = null, bool forceSync = false) inline
Definition at line 6135 of file Card.cs.
    {
        if (IsPC && !EClass.player.forceTalk && idTopic != "goodBoy" && idTopic != "insane")
        {
            EClass.player.forceTalk = false;
            Msg.SetColor();
            return;
        }
        EClass.player.forceTalk = false;
        if (!isSynced && !forceSync)
        {
            Msg.SetColor();
            return;
        }
        GameLang.refDrama1 = ref1;
        GameLang.refDrama2 = ref2;
        string text = GetTalkText(idTopic, stripPun: true);
        if (HasElement(1232) && idTopic != "baby")
        {
            BackerContent.GakiConvert(ref text, "babu");
        }
        else
        {
            string text2 = id;
            if (!(text2 == "adv_gaki"))
            {
                if (text2 == "corgon")
                {
                    BackerContent.GakiConvert(ref text, "mokyu");
                }
            }
            else
            {
                BackerContent.GakiConvert(ref text);
            }
        }
        TalkRaw(text, ref1, ref2, forceSync);
    }
References Player.forceTalk, BackerContent.GakiConvert(), EClass.player, and Msg.SetColor().
Referenced by Chara._Move(), AI_Shopping.Buy(), Point.CallGuard(), AI_Torture.CreateProgress(), ZonePreEnterEncounter.Execute(), AI_Fuck.Finish(), AI_Massage.Finish(), Chara.GiveGift(), Chara.GiveLovePotion(), TraitGamble.IdleUse(), Trait.OfferProcess(), InvOwner.OnClick(), QuestEscort.OnEnterZone(), Affinity.OnGift(), TraitBaseSpellbook.OnRead(), QuestEscort.OnStart(), ActWater.Perform(), ActEffect.Poison(), FoodEffect.Proc(), InvOwner.Transaction.Process(), Chara.RequestProtection(), ActRide.Ride(), AI_ArmPillow.Run(), AI_Clean.Run(), AI_Eat.Run(), AI_Fuck.Run(), AI_GotoHearth.Run(), AI_Haul.Run(), AI_Idle.Run(), AI_Massage.Run(), AI_PlayMusic.Run(), AI_Shear.Run(), AI_Trolley.Run(), AIWork.Run(), GoalCombat.Run(), ActThrow.Throw(), ConChampagne.Tick(), ConEntangle.Tick(), ConInsane.Tick(), ConSleep.Tick(), Chara.TryPush(), and ActRide.Unride().
TalkRaw()
void Card.TalkRaw (string text, string ref1 = null, string ref2 = null, bool forceSync = false) inline
Definition at line 6174 of file Card.cs.
    {
        if ((!isSynced && !forceSync) || text.IsEmpty())
        {
            Msg.SetColor();
            return;
        }
        if (ref1 != null)
        {
            text = text.Replace("#1", ref1);
        }
        if (ref2 != null)
        {
            text = text.Replace("#2", ref2);
        }
        HostRenderer.Say(ApplyNewLine(text));
        bool flag = text.StartsWith("*");
        Msg.SetColor(text.StartsWith("(") ? Msg.colors.Thinking : (flag ? Msg.colors.Ono : Msg.colors.Talk));
        if (!flag)
        {
            text = text.Bracket();
        }
        Msg.Say(text.Replace("&", ""));
    }
References Msg.colors, MsgColors.Ono, Msg.Say(), Msg.SetColor(), MsgColors.Talk, and MsgColors.Thinking.
Referenced by ZoneEventPhone.OnTickRound(), and TraitDaggerGrave.OnUse().
Teleport()
void Card.Teleport (Point point, bool silent = false, bool force = false) inline
Definition at line 5334 of file Card.cs.
    {
        if (EClass._zone.IsRegion)
        {
            SayNothingHappans();
            return;
        }
        PlayEffect("teleport");
        if (!force && (trait is TraitNewZone || elements.Has(400) || (isChara && Chara.HasCondition<ConGravity>())))
        {
            Say("antiTeleport", this);
            PlaySound("gravity");
            return;
        }
        if (!silent)
        {
            PlaySound("teleport");
            Say("teleported", this);
        }
        _Move(point);
        renderer.SetFirst(first: true, pos.PositionCenter());
        if (isChara)
        {
            Chara.ai.Cancel();
            foreach (Chara chara in EClass._map.charas)
            {
                if (chara.enemy == this)
                {
                    chara.SetEnemy();
                }
            }
            Chara.RemoveCondition<ConEntangle>();
        }
        if (IsPC)
        {
            EClass.screen.FocusPC();
            EClass.screen.RefreshPosition();
            EClass.player.haltMove = true;
        }
        PlayEffect("teleport", useRenderPos: false);
    }
References EClass._map, EClass._zone, Chara.ai, AIAct.Cancel(), Map.charas, Chara.enemy, BaseGameScreen.FocusPC(), ElementContainer.Has(), Chara.HasCondition(), Spatial.IsRegion, Point.PositionCenter(), BaseGameScreen.RefreshPosition(), EClass.screen, Chara.SetEnemy(), and CardRenderer.SetFirst().
Referenced by CoreDebug.COM_Teleport(), TraitGeneMachine.OnUse(), ActSummonGuard.Perform(), ActEffect.Proc(), Chara.RequestProtection(), AI_Idle.Run(), AI_PassTime.Run(), ConSleep.SuccubusVisit(), and TraitTeleporter.TryTeleport().
Tick()
virtual void Card.Tick () inline virtual
Reimplemented in Chara.
Definition at line 6552 of file Card.cs.
    {
    }
ToString()
override string Card.ToString () inline
Definition at line 2387 of file Card.cs.
    {
        return Name + "/" + pos?.ToString() + "/" + parent;
    }
References Name, parent, pos, and Point.ToString().
Referenced by AddThing(), ButtonGrid.ToString(), and HotItemAct.TrySetAct().
TryGetFoodName()
string Card.TryGetFoodName (Card c) inline
Definition at line 5240 of file Card.cs.
    {
        if (c.c_idRefCard.IsEmpty())
        {
            return c.c_altName;
        }
        if (!(c.refCard is SourceChara.Row { isChara: not false } row))
        {
            return c.c_altName;
        }
        if (!row.aka.IsEmpty())
        {
            if (row.name == "*r" && row.aka == "*r")
            {
                return "corpseGeneral".lang();
            }
            if (row.name == "*r")
            {
                return row.GetText("aka");
            }
        }
        return row.GetName();
    }
References c_altName, c_idRefCard, and refCard.
TryMakeRandomItem()
Thing Card.TryMakeRandomItem (int lv = -1) inline
Definition at line 5030 of file Card.cs.
    {
        if (lv == -1)
        {
            lv = EClass._zone.DangerLv;
        }
        switch (id)
        {
        case "gene":
            DNA.CopyDNA(DNA.GenerateRandomGene(lv), Thing);
            break;
        case "log":
            ChangeMaterial(EClass.sources.materials.rows.Where((SourceMaterial.Row m) => m.category == "wood").RandomItem());
            break;
        case "ore_gem":
            ChangeMaterial(MATERIAL.GetRandomMaterialFromCategory(lv, "gem", material));
            break;
        case "ore":
            ChangeMaterial(MATERIAL.GetRandomMaterialFromCategory(lv, "ore", material));
            break;
        case "milk":
        case "_egg":
        case "egg_fertilized":
        case "_meat":
        case "meat_marble":
        {
            string text = "c_wilds";
            if (id == "_meat" || id == "meat_marble")
            {
                text = "c_animal";
            }
            for (int i = 0; i < 20; i++)
            {
                CardRow cardRow = SpawnList.Get(text).Select(lv);
                if (cardRow.model.Chara.race.corpse[0] != "_meat" && id != "milk" && id != "_egg" && id != "egg_fertilized")
                {
                    continue;
                }
                if (id == "milk")
                {
                    if (c_idRefCard.IsEmpty())
                    {
                        MakeRefFrom(cardRow.model);
                    }
                }
                else
                {
                    MakeFoodFrom(cardRow.model);
                }
                break;
            }
            break;
        }
        }
        return this as Thing;
    }
References EClass._zone, ChangeMaterial, Chara, DNA.CopyDNA(), Zone.DangerLv, DNA.GenerateRandomGene(), SpawnList.Get(), MATERIAL.GetRandomMaterialFromCategory(), material, SourceManager.materials, CardRow.model, Chara.race, SpawnList.Select(), and EClass.sources.
Referenced by FactionBranch.DailyOutcome(), Map.MineObj(), Trait.OnBarter(), and CoreDebug.UpdateInput().
TryPay()
bool Card.TryPay (int a, string id = "money") inline
Definition at line 3672 of file Card.cs.
    {
        if (GetCurrency(id) < a)
        {
            if (IsPC)
            {
                SE.Beep();
                Msg.Say((id == "ration") ? "notEnoughFood" : "notEnoughMoney");
            }
            return false;
        }
        if (IsPC && !(id == "ration"))
        {
            SE.Pay();
        }
        ModCurrency(-a, id);
        return true;
    }
References GetCurrency(), IsPC, ModCurrency(), and Msg.Say().
Referenced by ListPeopleRevive.OnClick(), InvOwnerDeliver.PayBill(), and LayerTravel.Refresh().
TryReserve()
bool Card.TryReserve (AIAct act) inline
Definition at line 2401 of file Card.cs.
    {
        if (CanReserve(act))
        {
            reservedAct = act;
            return true;
        }
        return false;
    }
References CanReserve(), and reservedAct.
Referenced by AI_Cook.Run(), and TaskMoveInstalled.Run().
TryStack()
void Card.TryStack (Thing t) inline
Definition at line 6383 of file Card.cs.
    {
        if (t == this)
        {
            return;
        }
        ThingContainer.DestData dest = things.GetDest(t);
        if (dest.stack != null)
        {
            if (IsPC)
            {
                Say("stack_thing", t, dest.stack);
            }
            t.TryStackTo(dest.stack);
        }
    }
References ThingContainer.GetDest(), ThingContainer.DestData.stack, and TryStackTo().
Referenced by Chara.PickHeld(), and ActEffect.Proc().
TryStackTo()
bool Card.TryStackTo (Thing to) inline
Definition at line 3188 of file Card.cs.
    {
        if (isDestroyed || to.isDestroyed || !CanStackTo(to))
        {
            return false;
        }
        to.decay = (to.decay * to.Num + decay * Num) / (to.Num + Num);
        to.ModNum(Num);
        if (c_isImportant)
        {
            to.c_isImportant = true;
        }
        if (EClass.core.config.game.markStack && to.GetRootCard() == EClass.pc)
        {
            to.isNew = true;
        }
        Destroy();
        return true;
    }
References c_isImportant, CanStackTo(), Core.config, EClass.core, decay, Destroy(), CoreConfig.game, GetRootCard(), isDestroyed, CoreConfig.GameConfig.markStack, ModNum(), Num, and EClass.pc.
Referenced by RecipeCard.Craft(), Chara.Pick(), UIInventory.Sort(), Zone.TryAddThing(), TryStack(), and ThingContainer.TryStack().
TryUnrestrain()
void Card.TryUnrestrain (bool force = false, Chara c = null) inline
Definition at line 6504 of file Card.cs.
    {
        if (!(GetRestrainer() == null || force))
        {
            return;
        }
        isRestrained = false;
        Say("unrestrained", this);
        if (this != c)
        {
            Talk("thanks");
        }
        MoveImmediate(pos.GetNearestPoint());
        renderer.SetFirst(first: true);
        if (c == null)
        {
            return;
        }
        if (c_rescueState == RescueState.WaitingForRescue)
        {
            c_rescueState = RescueState.Rescued;
            if (c.IsPC)
            {
                EClass.player.ModKarma(2);
            }
        }
        if (EClass._zone.IsPCFaction || EClass._zone is Zone_Tent)
        {
            return;
        }
        foreach (Chara item in c.pos.ListCharasInRadius(c, 5, (Chara _c) => _c.id == "fanatic" && _c.faith != Chara.faith))
        {
            c.DoHostileAction(item, immediate: true);
        }
    }
References EClass._zone, Chara.faith, Point.GetNearestPoint(), id, Zone.IsPCFaction, item, Player.ModKarma(), EClass.player, and CardRenderer.SetFirst().
Referenced by ActPlan._Update().
WriteNote()
virtual void Card.WriteNote (UINote n, Action< UINote > onWriteNote = null, IInspect::NoteMode mode = IInspect::NoteMode::Default, Recipe recipe = null) inline virtual
Implements IInspect.
Reimplemented in Chara, and Thing.
Definition at line 7206 of file Card.cs.
    {
    }
Referenced by GridItemCard.SetButton(), ButtonGrid.SetCard(), and ButtonGrid.SetCraftRecipe().
Member Data Documentation
_bits1
BitArray32 Card._bits1
Definition at line 75 of file Card.cs.
Referenced by _OnDeserialized(), _OnSerializing(), SerializedCards.Add(), Duplicate(), and SerializedCards.Restore().
_bits2
BitArray32 Card._bits2
Definition at line 77 of file Card.cs.
Referenced by _OnDeserialized(), _OnSerializing(), SerializedCards.Add(), Duplicate(), and SerializedCards.Restore().
_category
SourceCategory.Row Card._category private
Definition at line 85 of file Card.cs.
_childrenWeight
int Card._childrenWeight private
Definition at line 83 of file Card.cs.
_colorInt
int Card._colorInt
Definition at line 63 of file Card.cs.
Referenced by ApplyMaterial(), Thing.ApplyMaterial(), and Chara.SetMainElement().
_ints
int [] Card._ints = new int[30]
Definition at line 28 of file Card.cs.
Referenced by _OnDeserialized(), and _OnSerializing().
_LightData
LightData Card._LightData private
Definition at line 93 of file Card.cs.
_material
SourceMaterial.Row Card._material
Definition at line 87 of file Card.cs.
Referenced by ChangeMaterial(), and Create().
_paintSprite
Sprite Card._paintSprite private
Definition at line 95 of file Card.cs.
_randColor
Color Card._randColor static private
Definition at line 89 of file Card.cs.
angle
float Card.angle = 180f
Definition at line 67 of file Card.cs.
Referenced by CardRenderer.Draw(), CharaActorPCC.OnSetOwner(), CharaActorPCC.RefreshSprite(), and Game.Save().
animeCounter
float Card.animeCounter
Definition at line 69 of file Card.cs.
bio
Biography Card.bio
Definition at line 40 of file Card.cs.
Referenced by ApplyBacker(), Chara.ApplyEditorTags(), DramaCustomSequence.Build(), GameLang.ConvertDrama(), Chara.Duplicate(), Player.GetBackgroundText(), Person.GetDramaTitle(), DramaCustomSequence.GetRumor(), Faction.IsWearingPanty(), UICharaMaker.ListGender(), Chara.OnCreate(), UICharaMaker.Refresh(), WindowChara.RefreshInfo(), WindowChara.RefreshNote(), Person.SetChara(), ItemGachaResult.SetChara(), ButtonChara.SetChara(), and AM_MoveInstalled.SetTarget().
bp
CardBlueprint Card.bp
Definition at line 73 of file Card.cs.
Referenced by Create(), Chara.OnBeforeCreate(), Chara.OnCreate(), and Thing.OnCreate().
dirtyWeight
bool Card.dirtyWeight = true
Definition at line 81 of file Card.cs.
Referenced by ChangeMaterial(), RemoveThing(), and SetDirtyWeight().
elements
ElementContainerCard Card.elements = new ElementContainerCard()
Definition at line 37 of file Card.cs.
Referenced by _OnDeserialized(), TraitAltar._OnOffer(), Element._WriteNote(), Element.AddEncNote(), AddRune(), DNA.Apply(), Chara.ApplyDeathPenalty(), Chara.ApplyJob(), Thing.ApplyMaterial(), Thing.ApplyMaterialElements(), ApplyProtection(), Chara.ApplyRace(), ApplySocket(), ActMelee.Attack(), TraitDrink.BlendLove(), TraitDrink.BlendPoison(), WidgetStatsBar.Build(), TraitTrainingDummyArmor.CalcPV(), Chara.CalculateMaxStamina(), CanAddRune(), Thing.CanAutoFire(), Thing.CanStackTo(), TraitAmmo.CanStackTo(), TraitCrafter.Craft(), RecipeCard.Craft(), TraitPotion.Create(), TraitRod.Create(), TraitSpellbook.Create(), Create(), DamageHP(), Player.DreamSpell(), Chara.Duplicate(), Duplicate(), EjectSockets(), CharaBody.Equip(), Evalue(), EvalueMax(), DramaOutcome.fiama_starter_gift(), AI_Fuck.Finish(), CoreDebug.Fix_EtherDisease(), DNA.GenerateWithGene(), GetBestAttribute(), Party.GetBestSkill(), Check.GetFinalDC(), AI_Shear.GetFur(), Element.GetParent(), Chara.GiveGift(), TaskHarvest.HarvestThing(), TraitFoodEggFertilized.Incubate(), Religion.JoinFaith(), Religion.LeaveFaith(), ElementContainer.ListElements(), CraftUtil.MakeDish(), TraitSeed.MakeSeed(), CraftUtil.MixIngredients(), StatsMana.Mod(), ModEncLv(), ModExp(), Player.MoveZone(), Trait.OnBarter(), TraitPotionAlchemy.OnCrafted(), TraitRod.OnCreate(), TraitToolRangeCane.OnCreate(), TaskChopWood.OnCreateProgress(), TaskDig.OnCreateProgress(), TaskDrawWater.OnCreateProgress(), TaskHarvest.OnCreateProgress(), TaskMine.OnCreateProgress(), TaskPlow.OnCreateProgress(), TaskPourWater.OnCreateProgress(), Chara.OnDeserialized(), TraitDrinkMilkMother.OnDrink(), Game.OnLoad(), TraitAgingShelf.OnProduce(), TraitDryBrick.OnProduce(), TaskCraft.OnProgress(), AI_Fish.ProgressFish.OnProgressComplete(), TaskCraft.OnProgressComplete(), TaskDig.OnProgressComplete(), TaskMine.OnProgressComplete(), TraitBookSkill.OnRead(), TraitScrollStatic.OnRead(), Player.OnStartNewGame(), Act.Perform(), AttackProcess.Perform(), AttackProcess.PlayRangedAnime(), AttackProcess.Prepare(), FoodEffect.Proc(), ActEffect.Proc(), CoreDebug.QuickStart(), ButtonElement.Refresh(), UICharaMaker.Refresh(), WidgetTracker.Refresh(), WindowCharaMini.Refresh(), UIRecipeInfo.RefreshList(), LayerEmbark.RefreshMembers(), LayerCraft.RefreshProduct(), WindowChara.RefreshProfile(), WindowChara.RefreshSkill(), Chara.RefreshSpeed(), WindowChara.RefreshStatic(), AI_Eat.Run(), AI_Fuck.Run(), AI_Idle.Run(), AI_PlayMusic.Run(), AI_Shear.Run(), AI_Slaughter.Run(), AI_Steal.Run(), AI_UseCrafter.Run(), LayerAbility.SelectGroup(), ButtonAbility.SetAct(), SetBlessedState(), ItemGachaResult.SetChara(), CoreDebug.SetElement(), ButtonElement.SetGrid(), SetLv(), Chara.SetMainElement(), TraitAbility.SetMainText(), CharaBody.SetOwner(), Recipe.SetTextDifficulty(), SetTier(), SpawnLoot(), ButtonAbility.SpecialHoldAction(), WidgetTracker.Toggle(), CalcPlat.Train(), Map.TryShatter(), CharaBody.Unequip(), TraitFoodEgg.Update(), CoreDebug.UpdateInput(), TraitWrench.Upgrade(), Element.BonusInfo.WriteNote(), RecipeCard.WriteNote(), Thing.WriteNote(), TraitBookSkill.WriteNote(), and Recipe.WriteReqSkill().
fov
Fov Card.fov
Definition at line 53 of file Card.cs.
Referenced by Chara.CanSee(), Player.CanSee(), Chara.CanSeeLos(), Chara.CanSeeSimple(), TileMapElona.DrawTile(), and AI_Fish.Run().
hat
CardRow Card.hat
Definition at line 59 of file Card.cs.
Referenced by CharaRenderer.Draw(), and CharaRenderer.DrawHat().
id
string Card.id = ""
Definition at line 31 of file Card.cs.
Referenced by ThingContainer._ListCurrency(), InvOwnerRecycle._OnProcess(), BuildMenu._Search(), SerializedCards.Add(), Props.Add(), Zone.AddCard(), ThingContainer.AddCurrency(), ThingContainer.AddFactory(), FactionBranch.AddMemeber(), AddThing(), InvOwner.AllowHold(), Recipe.BuildIngredientList(), Chara.CanAcceptGift(), TraitDrink.CanBlend(), TraitBrewery.CanChildDecay(), TraitAltar.CanOffer(), Recipe.Ingredient.CanSetThing(), Thing.CanStackTo(), QuestCrafter.CanUpdateOnTalk(), QuestDefense.CanUpdateOnTalk(), QuestExploration.CanUpdateOnTalk(), QuestShippingChest.CanUpdateOnTalk(), Trait.Contains(), RecipeCard.Craft(), Recipe.Create(), LayerInventory.CreateContainer(), FactionBranch.DailyOutcome(), BaseTileMap.DrawTile(), TileMapElona.DrawTile(), GrowSystem.EqualizePlants(), ZonePreEnterEncounter.Execute(), CardManager.GlobalCharaList.Find(), ThingContainer.Find(), Map.FindChara(), Zone.FindChara(), CoreDebug.Fix_RemoveDemitas(), CoreDebug.Fix_RemoveDuplicateUnique(), Biography.Generate(), FactionBranch.GenerateGarbage(), DNA.GenerateGene(), TraitChara.GetAdvRank(), TraitItemProc.GetCraftNum(), ThingContainer.GetCurrency(), Trait.GetFuelValue(), AI_Shear.GetFur(), TaskChopWood.GetLog(), Thing.GetName(), ReligionMoonShadow.GetOfferingMtp(), ReligionTrickery.GetOfferingMtp(), TraitBrewery.GetProductID(), DramaCustomSequence.GetRumor(), TaskBuild.GetText(), ThingContainer.GetThingStack(), AI_Haul.GetThingToClean(), Chara.GiveGift(), TaskHarvest.HarvestThing(), Faction.HasMember(), ActDrawWater.HasWaterSource(), AI_HaulResource.HoldingResource(), UIDragGridInfo.InitFuel(), QuestDeliver.IsDestThing(), Player.IsPriorityAction(), IsStackable(), Recipe.Ingredient.IsValidIngredient(), Faction.IsWearingPanty(), Props.ListThingStack(), Props.ListThingStacksInCategory(), TraitFoodEggFertilized.MakeBaby(), CraftUtil.MakeDish(), MakeFoodRef(), MakeRefFrom(), TraitSeed.MakeSeed(), DramaOutcome.melilith_friend(), CraftUtil.MixIngredients(), Zone_Casino.OnActivate(), TraitTrap.OnActivateTrap(), Zone_WindRest.OnAfterSimulate(), Trait.OnBarter(), TraitWell.OnBlend(), TraitBrewery.OnChildDecay(), FactionBranch.OnClaimZone(), ContentCodex.OnClickAddCards(), Thing.OnCreate(), TraitRod.OnCreate(), TraitDrink.OnDrink(), TraitDrinkMilkMother.OnDrink(), QuestRandom.OnDropReward(), Zone_CursedManor.OnGenerateMap(), Zone_CursedManorDungeon.OnGenerateMap(), Zone_WindRest.OnGenerateMap(), QuestTaskFlyer.OnGiveItem(), LayerCraft.OnKill(), Game.OnLoad(), Props.OnNumChange(), TraitAltar.OnOffer(), AI_Fish.ProgressFish.OnProgressComplete(), TaskBuild.OnProgressComplete(), TraitLicense.OnRead(), TraitScrollStatic.OnRead(), ConSleep.OnRemoved(), TraitPaintBoard.OnRenderExtra(), TraitTrapMine.OnStepped(), TraitGainPrecious.OnUse(), TraitHat.OnUse(), TraitPotionEmpty.OnUse(), RecipeManager.OnVersionUpdate(), ZoneEventMusic.OnVisit(), AttackProcess.Perform(), AttackProcess.PlayRangedAnime(), DramaOutcome.poppy_found(), ActEffect.Proc(), ActEffect.ProcAt(), InvOwner.Transaction.Process(), PurgeDuplicateArtifact(), TCOrbitChara.RefreshAll(), LayerCraft.RefreshCategory(), LayerCraftFloat.RefreshDisassemble(), UIRecipeInfo.RefreshList(), TraitDaggerGrave.RemainingSword(), SerializedCards.Restore(), AI_Haul.Run(), AI_Idle.Run(), AI_PlayMusic.Run(), GoalCombat.Run(), RecipeUpdater.RunRecipe(), TraitDetector.Search(), ActWait.SearchMedal(), SecondaryCompare(), Portrait.SetChara(), TraitAltar.SetDeity(), Chara.SetMainElement(), CardActor.SetOwner(), Biography.SetPortrait(), Player.SetPriorityAction(), HitSummary.SetRecipe(), Chara.SetSource(), Thing.SetSource(), TaskHarvest.ShouldGenerateDismantled(), InvOwnerRecycle.ShouldShowGuide(), Chara.ShouldThrowAway(), Zone.Simulate(), DramaOutcome.sister_friend(), Tactics.Tactics(), DramaActor.Talk(), ActThrow.Throw(), AI_PlayMusic.ThrowReward(), Chara.TryPoisonPotion(), Chara.TryReservePickupTutorial(), Chara.TryTakeSharedItems(), TryUnrestrain(), Chara.TryUse(), GoalCombat.TryUseAbility(), CoreDebug.UpdateInput(), ElementContainerCard.ValueBonus(), and Element.BonusInfo.WriteNote().
isDestroyed
bool Card.isDestroyed
Definition at line 71 of file Card.cs.
Referenced by TaskBuild._GetHitResult(), _OnDeserialized(), AddThing(), RecipeCard.Build(), AI_Shopping.Buy(), Chara.CanPick(), FactionBranch.DailyOutcome(), Recipe.GetMaxCount(), Chara.GiveGift(), Chara.HoldCard(), TaskCraft.IsIngredientsValid(), AI_OpenGambleChest.IsValid(), Map.Load(), AM_Build.OnFinishProcessTiles(), Game.OnLoad(), AI_Fish.ProgressFish.OnProgressComplete(), InvOwner.OnShiftClick(), ActThrow.Perform(), UIRecipeInfo.Refresh(), BuildMenu.RefreshCategory(), Player.RefreshCurrentHotItem(), UIInventory.RefreshHighlight(), WidgetSearch.RefreshList(), AI_HaulResource.Run(), AI_Idle.Run(), AI_PlayMusic.Run(), AI_UseCrafter.Run(), TaskDump.Run(), ButtonGrid.SetCard(), ButtonGrid.SetCardGrid(), Thing.ShowSplitMenu(), Thing.ShowSplitMenu2(), ActThrow.Throw(), Chara.TryHoldCard(), LayerDragGrid.TryPutBack(), TryStackTo(), and FactionBranch.UpdateReqruits().
lastEmo
Emo Card.lastEmo
Definition at line 91 of file Card.cs.
MaxWeight
const int Card.MaxWeight = 10000000 static
Definition at line 25 of file Card.cs.
parent
ICardParent Card.parent
Definition at line 51 of file Card.cs.
Referenced by Props.Add(), Zone.AddCard(), Zone.AddGlobalCharasOnActivate(), AddThing(), DropdownGrid.BuildIngredients(), InvOwner.CanOpenContainer(), Thing.CanStackTo(), DamageHP(), CardRenderer.Draw(), CharaBody.Equip(), Player.EquipTool(), ThingContainer.GetDest(), Msg.GetName(), GetRoot(), GetRootCard(), IsExcludeFromCraft(), ThingContainer.IsFull(), InvOwner.ListInteractions(), Props.ListThingStack(), ModNum(), Chara.MoveZone(), AI_Drink.OnSetOwner(), AI_Read.OnSetOwner(), PropsManager.OnSetPlaceState(), InvOwner.OnShiftClick(), InvOwner.OnStartDrag(), Chara.Pick(), CardRenderer.PlayAnime(), ActEffect.Proc(), InvOwner.Transaction.Process(), Map.PutAway(), ActorEx.Refresh(), UIDragGridIngredients.Refresh(), UIInventory.RefreshHighlight(), AI_Drink.Run(), AI_Eat.Run(), AI_Equip.Run(), AI_Idle.Run(), AI_PlayMusic.Run(), AI_Read.Run(), AI_Steal.Run(), WidgetSearch.Search(), SetDirtyWeight(), SetPlaceState(), Props.ShouldListAsResource(), LayerCraftFloat.ShowContextMenu(), SpawnLoot(), ActThrow.Throw(), ToString(), Chara.TryEquipRanged(), Chara.TryHoldCard(), LayerDragGrid.TryPutBack(), ActRanged.TryReload(), and LayerInventory.TryShowGuide().
placeState
PlaceState Card.placeState
Definition at line 79 of file Card.cs.
Referenced by _OnDeserialized(), _OnSerializing(), ActPlan._Update(), SerializedCards.Add(), Zone.AddCard(), AddThing(), Recipe.Build(), BaseTileMap.DrawTile(), TileMapElona.DrawTile(), TraitMap.GetRandomInstalled(), AI_Haul.GetThingToClean(), PropsManager.OnCardAddedToZone(), TraitGodStatue.OnChangeMaterial(), TraitHouseBoard.OnChangePlaceState(), TraitBoat.OnRemovedFromZone(), SetPlaceState(), and Zone.TryAddThing().
pos
Point Card.pos = new Point()
Definition at line 55 of file Card.cs.
Referenced by Map._AddCard(), TaskPoint._CanPerformTask(), AIWork._FuncWorkPoint(), Chara._Move(), _OnDeserialized(), InvOwnerChaosOffering._OnProcess(), _OnSerializing(), AM_Adv._OnUpdateInput(), TraitShrine._OnUse(), WidgetDate._Refresh(), ActPlan._Update(), Zone.Activate(), SerializedCards.Add(), Map.AddCardOnActivate(), Zone.AddGlobalCharasOnActivate(), AddThing(), PartialMap.Apply(), TraitHouseBoard.ApplyData(), Chara.ApplyDeathPenalty(), ActMelee.Attack(), AM_Adv.AxisMove(), Recipe.Build(), AI_Shopping.Buy(), MeetingManager.CallNext(), TraitTrolley.CanActivate(), TraitDoor.CanClose(), Chara.CanInteractTo(), GoalManualMove.CanMove(), Chara.CanMoveTo(), ActBash.CanPerform(), ActKick.CanPerform(), ActRanged.CanPerform(), ActRush.CanPerform(), ActThrow.CanPerform(), Act.CanPerform(), Chara.CanPick(), Chara.CanReplace(), Chara.CanSee(), Player.CanSee(), Chara.CanSeeLos(), ActThrow.CanThrow(), QuestDefense.CanUpdateOnTalk(), TraitGeneratorWheel.CanUse(), TraitShackle.CanUse(), Zone.ClaimZone(), CoreDebug.COM_Teleport(), Trait.CookProgress(), TraitCrafter.Craft(), RecipeCard.Craft(), SpatialGen.CreateInstance(), AI_PracticeDummy.CreateProgress(), AI_Torture.CreateProgress(), Region.CreateRandomSite(), TraitNewZone.CreateZone(), FactionBranch.DailyOutcome(), ActEffect.DamageEle(), Chara.DestroyPath(), Die(), Dist(), ActionMode.DoFunc(), AI_Idle.DoSomethingToCharaInRadius(), AI_Idle.DoSomethingToNearChara(), BaseGameScreen.Draw(), BaseTileMap.Draw(), TileMapElona.Draw(), CardRenderer.Draw(), BaseTileMap.DrawTile(), TileMapElona.DrawTile(), Player.DropReward(), EjectSockets(), WidgetMinimap.EmitParticle(), Player.EnterLocalZone(), ZonePreEnterBout.Execute(), ZonePreEnterBoutWin.Execute(), ZonePreEnterEncounter.Execute(), DramaOutcome.fiama_pet(), Chara.FindNearestNewEnemy(), Map.FindThing(), BaseGameScreen.Focus(), BaseGameScreen.FocusPC(), TraitBoat.ForeachDeck(), FactionBranch.GenerateGarbage(), DramaOutcome.get_scratch(), ActPlan.GetAction(), AI_Pray.GetAltar(), AI_Clean.GetCleanPoint(), AI_Goto.GetDestination(), AIAct.GetDestination(), Hobby.GetEfficiency(), BaseArea.GetEmptySeat(), TraitNewZone.GetExitPos(), TraitStairs.GetExitPos(), Chara.GetFirstStep(), TaskMine.GetHitResult(), FactionBranch.GetMailBoxPos(), CoreDebug.GetOrCreateDebugContainer(), Trait.GetPoint(), AI_Trolley.GetPoint(), FortuneRollData.GetPrize(), Trait.GetRandomPoint(), Zone.GetRandomVisitPos(), Chara.GetRevived(), Chara.GetRoomWork(), Zone.GetSpawnPos(), Chara.GetSubPassData(), TraitGeneMachine.GetTarget(), AI_Haul.GetThingToClean(), TaskHarvest.HarvestThing(), Chara.HasAccess(), Chara.HasHigherGround(), ZoneEventDefenseGame.Horn_Ally(), TraitFoodEggFertilized.Incubate(), Scene.Init(), AI_Goto.IsDestinationReached(), IsInMutterDistance(), TraitDoor.IsOpen(), TraitShackle.IsRestraining(), TraitDoor.IsValid(), Los.IsVisible(), Chara.Kick(), HomeResourceWorth.ListHeirloom(), Trait.ListPoints(), TraitLightSun.ListPoints(), Props.ListThingStack(), Region.ListTravelZones(), Chara.LookAt(), Map.MineFloor(), Player.ModKarma(), Chara.MoveNeighborDefinitely(), Chara.MoveRandom(), TraitNewZone.MoveZone(), TraitMoongate.MoveZone(), Trait.Offer(), Trait.OfferProcess(), AM_Adv.OnActivate(), WidgetArtTool.OnActivate(), TraitHitchingPost.OnActivateTrap(), FactionBranch.OnActivateZone(), Region.OnAdvanceHour(), FactionBranch.OnAfterSimulate(), AM_Adv.OnAfterUpdate(), Chara.OnBanish(), AM_Adv.OnBecomeNoGoal(), Zone_Nymelle.OnBeforeSimulate(), ConSleep.OnBeforeStart(), TraitHouseBoard.OnChangePlaceState(), QuestIntroInspector.OnComplete(), QuestVernis.OnComplete(), TaskDig.OnCreateProgress(), TaskHarvest.OnCreateProgress(), TaskMine.OnCreateProgress(), QuestDialog.OnDropReward(), TraitRollingFortune.OnEndAI(), ElementContainerCard.OnLevelUp(), ElementContainerZone.OnLevelUp(), Act.OnMarkMapHighlights(), ActBolt.OnMarkMapHighlights(), ActRush.OnMarkMapHighlights(), TraitAltar.OnOffer(), AM_Designation< T >.OnProcessTiles(), AM_MoveInstalled.OnProcessTiles(), AI_Fish.ProgressFish.OnProgressComplete(), AI_Sleep.OnProgressComplete(), QuestCraft.OnProgressComplete(), TaskBuild.OnProgressComplete(), TaskDig.OnProgressComplete(), TraitDeedRelocate.OnRead(), TraitDiary.OnRead(), TraitScrollStatic.OnRead(), ConSleep.OnRemoved(), ConSuspend.OnRemoved(), AM_Adv.OnRenderTile(), TraitFertilizer.OnSimulateHour(), GoalSleep.OnSimulatePosition(), QuestEscort.OnStart(), TraitNewZone.OnStepped(), TraitSwing.OnSteppedOut(), LayerCraftFloat.OnSwitchContent(), Scene.OnUpdate(), TraitDaggerGrave.OnUse(), TraitFarmChest.OnUse(), TraitGeneMachine.OnUse(), TraitGiftNewYear.OnUse(), TraitMannequin.OnUse(), TraitShackle.OnUse(), TraitStairsLocked.OnUse(), TraitContainer.Open(), DramaManager.ParseLine(), Act.Perform(), ActMultihit.Perform(), ActRanged.Perform(), ActRush.Perform(), ActSummonGuard.Perform(), ActThrow.Perform(), HotItemActionSleep.Perform(), ActPlan.Item.Perform(), AttackProcess.Perform(), Zone_Dungeon.PlaceRail(), EffectIRenderer.Play(), CardRenderer.PlayAnime(), PlayEffect(), AttackProcess.PlayRangedAnime(), PlaySound(), Trait.PlayToggleEffect(), AttackProcess.Prepare(), AM_Adv.PressedActionMove(), FoodEffect.Proc(), ActEffect.Proc(), ActEffect.ProcAt(), InvOwner.Transaction.Process(), DramaOutcome.QuestExploration_AfterCrystal(), CoreDebug.QuickStart(), TraitBaseSpellbook.ReadFailEffect(), FactionBranch.Recruit(), Religion.Reforge(), ActorEx.Refresh(), LayerTravel.Refresh(), WidgetMouseover.Refresh(), AM_Adv.RefreshArrow(), AM_Region.RefreshArrow(), Zone.RefreshBGM(), LayerCraftFloat.RefreshCraft(), WidgetSearch.RefreshList(), BaseGameScreen.RefreshPosition(), GameScreenElona.RefreshPosition(), BaseGameScreen.RefreshWeather(), GameScreenElona.RefreshWeather(), Weather.RefreshWeather(), Map.Resize(), SerializedCards.Restore(), Zone.Revive(), Chara.Revive(), AI_ArmPillow.Run(), AI_Bladder.Run(), AI_Clean.Run(), AI_Cook.Run(), AI_Fuck.Run(), AI_Haul.Run(), AI_Idle.Run(), AI_Massage.Run(), AI_Offer.Run(), AI_PassTime.Run(), AI_PlayMusic.Run(), AI_Shear.Run(), AI_Shopping.Run(), AI_Slaughter.Run(), AI_Steal.Run(), AI_TargetCard.Run(), AI_Torture.Run(), AI_UseCrafter.Run(), AIWork.Run(), GoalCombat.Run(), GoalManualMove.Run(), GoalSleep.Run(), TaskDump.Run(), TaskPoint.Run(), RecipeUpdater.RunDisassemble(), PartialMap.Save(), Map.Save(), ActWait.Search(), CharaRenderer.SetFirst(), SetPlaceState(), AM_Adv.SetPressedAction(), RegionPoint.SetRegionPoint(), WidgetHotbar.SetShortcutMenu(), UISong.SetSong(), TraitGeneratorWheel.ShouldWork(), AM_Adv.ShowAllAction(), LayerCraftFloat.ShowContextMenu(), Zone.Simulate(), Player.SimulateFaction(), CoreDebug.Spawn(), CoreDebug.SpawnBoss(), ButtonAbility.SpecialHoldAction(), Chara.Stumble(), ConSleep.SuccubusVisit(), Chara.SyncRide(), Player.TargetRanged(), CoreDebug.TestSpawn(), ActThrow.Throw(), AI_PlayMusic.ThrowReward(), Chara.Tick(), ConFear.Tick(), ConMiasma.Tick(), ConSleep.Tick(), ConSuspend.Tick(), TraitDoor.ToggleDoor(), TraitDoorSwing.ToggleDoor(), ToString(), Chara.ToString(), TraitSwitch.TryDisarmTrap(), Religion.TryGetGift(), AI_Goto.TryGoTo(), GoalCombat.TryMove(), GoalManualMove.TryMove(), Chara.TryMoveFrom(), Chara.TryMoveTowards(), AI_Shopping.TryRestock(), HotItemAct.TrySetAct(), HotItemHeld.TrySetAct(), TraitCanvas.TrySetAct(), TraitCoreZone.TrySetAct(), TraitHouseBoard.TrySetAct(), TraitNewZone.TrySetAct(), TraitRoomPlate.TrySetAct(), TraitWaystone.TrySetAct(), TraitCatalyst.TrySetHeldAct(), TraitToolBrush.TrySetHeldAct(), TraitToolButcher.TrySetHeldAct(), TraitToolShears.TrySetHeldAct(), Map.TryShatter(), Map.TrySmoothPick(), TraitSeed.TrySprout(), TraitTeleporter.TryTeleport(), GoalCombat.TryThrow(), ButtonAbility.TryUse(), ActRide.Unride(), GameUpdater.Update(), TraitFoodEgg.Update(), TraitSpotSpawn.Update(), GameUpdater.Update100ms(), CoreDebug.UpdateInput(), AM_Adv.UpdateLangWheel(), CharaRenderer.UpdatePosition(), WidgetDebug.UpdateText(), Chara.UseAbility(), and VirtualRoom.VirtualRoom().
props
Props Card.props
Definition at line 47 of file Card.cs.
Referenced by Props.Add(), ModNum(), Props.Remove(), RemoveThing(), and SetPlaceState().
renderer
CardRenderer Card.renderer
Definition at line 57 of file Card.cs.
Referenced by Chara._Move(), ActPlan._Update(), GameDate.AdvanceMonth(), ActMelee.Attack(), RecipeCard.Build(), Chara.ChangeRarity(), BaseGameScreen.Draw(), CardRenderer.Draw(), CharaRenderer.DrawHeld(), BaseTileMap.DrawTile(), TileMapElona.DrawTile(), RecipeCard.GetRenderer(), BaseTileMap.GetThingPosition(), AM_Adv.OnActivate(), AM_Adv.OnBeforeUpdate(), TraitGodStatue.OnChangeMaterial(), BaseListPeople.OnClick(), TaskChopWood.OnCreateProgress(), TaskDig.OnCreateProgress(), TaskHarvest.OnCreateProgress(), TaskMine.OnCreateProgress(), TaskPlow.OnCreateProgress(), Map.OnDeactivate(), GrowSystemTree.OnHitFail(), EffectIRenderer.OnKill(), Zone.OnKillGame(), AM_MoveInstalled.OnProcessTiles(), AI_Fish.ProgressFish.OnProgress(), AI_Fish.ProgressFish.OnProgressComplete(), TaskBuild.OnProgressComplete(), ConFaint.OnRemoved(), CardActor.OnRender(), CharaActorPCC.OnRender(), CharaActorPCC.OnSetOwner(), TCOrbitChara.OnSetOwner(), TCOrbitThing.OnSetOwner(), EffectIRenderer.OnUpdate(), Scene.OnUpdate(), TraitPowerStatue.OnUse(), ActBash.Perform(), ActRanged.Perform(), EffectIRenderer.Play(), CardRenderer.PlayAnime(), PlayEffect(), AttackProcess.PlayRangedAnime(), BaseStats.PopText(), TraitEffect.Proc(), TCOrbitChara.Refresh(), TCOrbitThing.Refresh(), BaseGameScreen.RefreshPosition(), GameScreenElona.RefreshPosition(), Trait.RefreshRenderer(), TraitToolTorch.RefreshRenderer(), Trait.Refuel(), Zone.RemoveCard(), TraitDoor.RotateDoor(), AI_Bladder.Run(), AI_Deconstruct.Run(), AI_Fuck.Run(), AI_Massage.Run(), AI_OpenGambleChest.Run(), AI_Paint.Run(), AI_PlayMusic.Run(), AI_Shear.Run(), AI_Slaughter.Run(), AI_Steal.Run(), AI_UseCrafter.Run(), GoalWait.Run(), NoGoal.Run(), TaskClean.Run(), LayerPixelPaint.SetCanvas(), ConFaint.SetOwner(), ConSleep.SetOwner(), ActThrow.Throw(), Player.TooHeavyToMove(), CoreDebug.UpdateInput(), and WidgetDebug.UpdateText().
reservedAct
AIAct Card.reservedAct
Definition at line 45 of file Card.cs.
Referenced by CanReserve(), and TryReserve().
roundTimer
float Card.roundTimer
Definition at line 65 of file Card.cs.
Referenced by WidgetDebug.UpdateText().
sockets
List<int> Card.sockets
Definition at line 43 of file Card.cs.
Referenced by AddSocket(), Thing.ApplyMaterial(), ApplySocket(), TraitKettle.CanCopy(), Duplicate(), EjectSockets(), TaskHarvest.HarvestThing(), TraitCrafter.IsIngredient(), LayerCraft.RefreshProduct(), and InvOwnerMod.ShouldShowGuide().
sortVal
int Card.sortVal
Definition at line 97 of file Card.cs.
Referenced by BaseListPeople.List(), HomeResourceWorth.ListHeirloom(), LayerDragGrid.SetInv(), LayerResource.ShowThings(), and CoreExtension.Sort().
things
ThingContainer Card.things = new ThingContainer()
Definition at line 34 of file Card.cs.
Referenced by ThingContainer._List(), ThingContainer._ListCurrency(), _OnDeserialized(), AM_Adv._OnUpdateInput(), TraitGodStatue._OnUse(), BuildMenu._Search(), Zone.Activate(), Props.Add(), ThingContainer.AddFactory(), FactionBranch.AddMemeber(), AddThing(), CardManager.AssignUIDRecursive(), DramaCustomSequence.Build(), ActItem.BuildAct(), DropdownGrid.BuildIngredients(), AI_Shopping.Buy(), QuestCraft.CanDeliverToClient(), InvOwner.CanShiftClick(), QuestLoytelFarm.CanUpdateOnTalk(), DramaOutcome.chara_hired_ticket(), DramaOutcome.check_sketch(), Create(), LayerInventory.CreateBuy(), ThingGen.CreateCardboardBox(), LayerInventory.CreateContainer(), AI_OpenLock.CreateProgress(), ThingGen.CreateTreasureContent(), FactionBranch.DailyOutcome(), Chara.Die(), Player.DropReward(), Duplicate(), ZonePreEnterBoutWin.Execute(), ZonePreEnterEncounter.Execute(), ThingContainer.Find(), ThingContainer.Find< T >(), Chara.FindAmmo(), Props.FindEmptyContainer< T >(), FindTool< T >(), CoreDebug.Fix_LostCore(), ThingContainer.Foreach(), DNA.GenerateManiGene(), GoalAutoCombat.GetAbilities(), BaseTaskHarvest.GetBestTool(), TraitPainter.GetCanvas(), ThingContainer.GetCurrency(), GetCurrency(), ThingContainer.GetDest(), FactionBranch.GetMeal(), InvOwner.GetShitDestOwner(), ThingContainer.GetThingStack(), TaskDig.GetTreasureMap(), DramaOutcome.give_sketch_special(), Chara.GiveGift(), DramaOutcome.guild_mageTrial(), TraitFoodEggFertilized.Incubate(), QuestDeliver.IsDestThing(), InvOwner.Transaction.IsValid(), QuestDeliver.ListDestThing(), InvOwner.ListInteractions(), InvOwnerEquip.ListInteractions(), Props.ListThingStack(), TaskDump.ListThingsToPut(), Chara.MakeGrave(), ModCurrency(), WidgetEquip.OnActivate(), Player.OnAdvanceHour(), Faction.OnAdvanceMonth(), Chara.OnBanish(), Trait.OnBarter(), AM_Adv.OnBecomeNoGoal(), ContentCodex.OnClickAddCards(), TraitBaseContainer.OnCreate(), Player.OnCreateGame(), ShopTransaction.OnEndTransaction(), ZoneEventHarvest.OnLeaveZone(), Game.OnLoad(), Player.OnLoad(), AI_Fish.ProgressFish.OnProgressComplete(), TraitScrollStatic.OnRead(), ConSleep.OnRemoved(), ConWrath.OnRemoved(), InvOwner.OnShiftClick(), QuestFiamaLock.OnStart(), Player.OnStartNewGame(), TraitMannequin.OnUse(), TraitParcel.OnUse(), RecipeManager.OnVersionUpdate(), TraitContainer.Open(), UI.OpenFloatInv(), DramaManager.ParseLine(), ActDreamBug.Perform(), HotItemActionSleep.Perform(), HotItemEQSet.Perform(), LayerGacha.PlayGacha(), LayerGachaResult.PlayGacha(), InvOwner.PutBack(), CoreDebug.QuickStart(), WidgetCurrentTool.RebuildSlots(), UIRecipeInfo.Refresh(), UIMagicChest.RefreshBottom(), BuildMenu.RefreshCategory(), ButtonGrid.RefreshCraftable(), ThingContainer.RefreshGridRecursive(), LayerQuestBoard.RefreshHire(), Recipe.Ingredient.RefreshThing(), Props.Remove(), RemoveBacker(), RemoveThing(), RemoveThings(), SerializedCards.Restore(), Chara.Revive(), AI_Idle.Run(), AI_PlayMusic.Run(), AI_Steal.Run(), RecipeUpdater.RunDisassemble(), RecipeUpdater.RunRecipe(), UIMagicChest.Search(), WidgetSearch.Search(), ActWait.SearchMedal(), LayerDragGrid.SetInv(), CharaBody.SetOwner(), HitSummary.SetRecipe(), GameDate.ShipGoods(), GameDate.ShipPackages(), InvOwnerRecycle.ShouldShowGuide(), LayerCraftFloat.ShowContextMenu(), UIInventory.Sort(), Zone.SpawnLostItems(), ButtonAbility.SpecialHoldAction(), ConSleep.SuccubusVisit(), Map.TryAddRoom(), Zone.TryAddThingInSharedContainer(), Zone.TryAddThingInSpot< T >(), Player.TryEquipBait(), Zone.TryGetRestock< T >(), Zone.TryGetThingFromSharedContainer(), ThingGen.TryLickChest(), Zone.TryListThingsInSpot< T >(), Trait.TryOpenLock(), ActPray.TryPray(), LayerDragGrid.TryProc(), Trait.TryRefuel(), TraitDeliveryChest.TrySetAct(), TraitToolTorch.TrySetHeldAct(), LayerInventory.TryShowGuide(), ThingContainer.TryStack(), Chara.TryTakeSharedItems(), GoalAutoCombat.TryUseRanged(), and TraitWrench.Upgrade().
trait
Trait Card.trait
Definition at line 49 of file Card.cs.
Referenced by Map._AddCard(), ThingGen._Create(), TaskBuild._GetHitResult(), TileType._HitTest(), AM_Build._IsRoofEditMode(), ThingContainer._List(), Chara._Move(), InvOwnerBlend._OnProcess(), InvOwnerChangeMaterial._OnProcess(), InvOwnerMod._OnProcess(), InvOwnerRefuel._OnProcess(), AM_Adv._OnUpdateInput(), BuildMenu._Search(), HotItemNoItem._TrySetAct(), ActPlan._Update(), Zone.Activate(), Scene.AddActorEx(), Cell.AddCard(), ThingContainer.AddFactory(), AddThing(), LayerSleep.Advance(), InvOwner.AllowHold(), InvOwnerCopyShop.AllowMoved(), PartialMap.Apply(), ApplySocket(), ApplyTrait(), ActMelee.Attack(), RecipeCard.Build(), ActItem.BuildAct(), VirtualDate.BuildSunMap(), FactionBranch.CalcInnIncome(), Chara.CanAcceptGift(), TraitNewZone.CanAutoEnter(), Thing.CanAutoFire(), HotItemHeld.CanChangeHeightByWheel(), TraitBrewery.CanChildDecay(), Trait.CanCook(), TraitKettle.CanCopy(), Chara.CanEat(), Player.CanExitBorder(), Trait.CanOffer(), InvOwner.CanOpenContainer(), ActRush.CanPerform(), TaskBaseBuild.CanPlaceCard(), TaskChopWood.CanProgress(), TaskHarvest.CanProgress(), AM_MoveInstalled.CanPutAway(), HotItemHeld.CanRotate(), TaskBuild.CanRotateBlock(), InvOwner.CanShiftClick(), TraitSalesTag.CanTagSale(), ActThrow.CanThrow(), CoreDebug.ChangeRace(), Recipe.Craft(), RecipeCard.Craft(), Create(), LayerInventory.CreateBuy(), LayerInventory.CreateContainer(), Trait.CreateStock(), FactionBranch.DailyOutcome(), ActEffect.DamageEle(), Zone.Deactivate(), Chara.DestroyPath(), Die(), CardRenderer.Draw(), CharaRenderer.Draw(), CharaRenderer.DrawHeld(), BaseTileMap.DrawTile(), TileMapElona.DrawTile(), Chara.Drink(), Chara.DropThing(), CharaBody.Equip(), Player.EquipTool(), ZonePreEnterDigStairs.Execute(), Props.Find< T >(), ThingContainer.Find< T >(), ThingContainer.FindBest< T >(), Props.FindEmptyContainer< T >(), ThingContainer.FindStealable(), Map.FindThing(), Map.FindThing< T >(), Point.FindThing< T >(), FindTool< T >(), CoreDebug.Fix_LostCore(), GoalAutoCombat.GetAbilities(), HotItemHeld.GetAct(), InvOwner.GetAutoUseLang(), BaseTaskHarvest.GetBestTool(), TraitPainter.GetCanvas(), ThingContainer.GetDest(), Zone.GetElectricity(), BaseArea.GetEmptySeat(), TaskBuild.GetHitResult(), Chara.GetHoverText2(), Point.GetInstalled< T >(), GetLightRadius(), DramaCustomSequence.GetListGuide(), Thing.GetName(), LayerInteraction.GetPage(), GoalGraze.GetPos(), HotItemHeld.GetSelfAct(), ActionMode.GetSimpleText(), Zone.GetSpawnPos(), MapBounds.GetSpawnPos(), AM_Visibility.GetTarget(), ActThrow.GetText(), BaseTileMap.GetThingPosition(), BaseTaskHarvest.GetToolEfficiency(), TaskDig.GetTreasureMap(), GetWindowSaveData(), Chara.GiveGift(), Zone.GrowPlants(), TaskHarvest.HarvestThing(), ActDrawWater.HasWaterSource(), Cell.HasZoneStairs(), AM_Copy.HitTest(), Scene.Init(), UIDragGridInfo.InitFuel(), QuestDeliver.IsDestThing(), ThingContainer.IsFull(), TraitCrafter.IsIngredient(), TraitToolTalisman.IsIngredient(), Point.IsInSpot< T >(), InvOwner.Transaction.IsValid(), TaskDump.IsValidContainer(), InvOwnerMod.IsValidRangedMod(), AI_Cook.IsValidTarget(), AI_Eat.IsValidTarget(), AI_Offer.IsValidTarget(), TraitWrench.IsValidTarget(), Act.IsValidTC(), AI_Steal.IsValidTC(), TraitManager.List< T >(), GenBounds.ListEmptyPoint(), HomeResourceWorth.ListHeirloom(), InvOwner.ListInteractions(), Map.ListThing< T >(), Point.ListThings< T >(), TaskDump.ListThingsToPut(), WidgetEquip.OnActivate(), TraitManager.OnAddCard(), Trait.OnBarter(), AM_Adv.OnBecomeNoGoal(), Map.OnCardAddedToZone(), Map.OnCardRemovedFromZone(), TraitBrewery.OnChildDecay(), LayerCraft.OnClickCraft(), InvOwner.OnDrag(), ShopTransaction.OnEndTransaction(), CardRenderer.OnEnterScreen(), Affinity.OnGift(), Game.OnLoad(), ButtonGrid.OnMiddleClick(), AM_MoveInstalled.OnProcessTiles(), TaskBuild.OnProgressComplete(), TraitManager.OnRemoveCard(), ConSleep.OnRemoved(), ConTorch.OnRemoved(), CharaActorPCC.OnRender(), RecipeCard.OnRenderMarker(), ActionMode.OnRenderTile(), AM_Adv.OnRenderTile(), InspectGroupThing.OnSetActions(), HotItemHeld.OnSetCurrentItem(), AI_Read.OnSetOwner(), Zone.OnSimulateHour(), TraitAmmo.OnUse(), UI.OpenFloatInv(), ActRanged.Perform(), AttackProcess.Perform(), Chara.Pick(), Chara.PickHeld(), Zone_Dungeon.PlaceRail(), AttackProcess.Prepare(), ActEffect.Proc(), InvOwner.Transaction.Process(), Map.PutAway(), DramaOutcome.QuestDefense_0(), DramaOutcome.QuestDefense_1(), CoreDebug.QuickStart(), Scene.RebuildActorEx(), BranchMap.Refresh(), Cell.Refresh(), UIPlaceHelper.Refresh(), TCOrbitChara.RefreshAll(), TCOrbitThing.RefreshAll(), UIMagicChest.RefreshBottom(), BuildMenu.RefreshCategory(), LayerDragGrid.RefreshCost(), Player.RefreshCurrentHotItem(), Zone.RefreshElectricity(), UIInventory.RefreshMenu(), LayerCraft.RefreshProduct(), CardActor.RefreshSprite(), Map.RefreshSunMap(), Trait.Refuel(), Map.ReloadRoom(), Cell.RemoveCard(), Zone.RemoveCard(), RemoveThing(), Map.ResetEditorPos(), SerializedCards.Restore(), Chara.Revive(), ActionMode.RotateUnderMouse(), AI_Cook.Run(), AI_Idle.Run(), AI_Offer.Run(), AI_Read.Run(), RecipeUpdater.RunRecipe(), PartialMap.Save(), Map.Save(), WidgetCurrentTool.Select(), ButtonGrid.SetCard(), AIWork.SetDestPos(), LayerAbility.SetDirty(), LayerCraft.SetFactory(), LayerDragGrid.SetInv(), LayerRegisterHotbar.SetItem(), CharaBody.SetOwner(), SetPlaceState(), ButtonGrid.SetRecipe(), CoreDebug.SetStartStockpile(), HotItemThing.SetSubText(), BaseTaskHarvest.SetTarget(), GameDate.ShipGoods(), TaskHarvest.ShouldGenerateDismantled(), PointTarget.ShouldIgnore(), InvOwnerBlend.ShouldShowGuide(), InvOwnerChangeMaterial.ShouldShowGuide(), InvOwnerCopyShop.ShouldShowGuide(), InvOwnerGive.ShouldShowGuide(), InvOwnerLighten.ShouldShowGuide(), InvOwnerReconstruction.ShouldShowGuide(), InvOwnerRecycle.ShouldShowGuide(), InvOwnerRefuel.ShouldShowGuide(), ThingContainer.ShouldShowOnGrid(), Chara.ShouldThrowAway(), TaskWater.ShouldWater(), TraitGeneratorWheel.ShouldWork(), Zone.Simulate(), Zone.SpawnAltar(), SpawnLoot(), Chara.Stumble(), UIInventory.SwitchTab(), Player.TargetRanged(), AM_Picker.TestThing(), ActThrow.Throw(), Chara.Tick(), Chara.TryAbsorbRod(), Map.TryAddRoom(), Zone.TryAddThingInSharedContainer(), Zone.TryAddThingInSpot< T >(), Chara.TryDropCarryOnly(), TaskHarvest.TryGetAct(), Zone.TryGetRestock< T >(), InvOwner.TryHold(), Zone.TryListThingsInSpot< T >(), TraitDoor.TryOpen(), AI_Idle.TryPerformIdleUse(), Chara.TryPoisonPotion(), HotItemHeld.TrySetAct(), TraitContainer.TrySetAct(), TraitNewZone.TrySetAct(), TraitSalesTag.TrySetHeldAct(), TraitTicketFurniture.TrySetHeldAct(), HotItemHeld.TrySetToolAct(), Map.TryShatter(), Zone.TrySpawnFollower(), CardRenderer.TrySpawnOrbit(), InvOwnerCraft.TryStartCraft(), Chara.TryTakeSharedItems(), TraitTeleporter.TryTeleport(), Chara.TryUse(), GoalCombat.TryUseAbility(), GoalAutoCombat.TryUseRanged(), CharaBody.Unequip(), CoreDebug.UpdateInput(), VirtualRoom.VirtualRoom(), and ActEffect.Wish().
turn
int Card.turn
Definition at line 61 of file Card.cs.
Referenced by AM_Adv._OnUpdateInput(), RecipeCard.MakeDish(), RecipeCard.MixIngredients(), TraitChestPractice.OnSimulateHour(), LayerMiniGame.OnUpdateInput(), GoalCombat.TryMove(), and TraitTeleporter.TryTeleport().
Property Documentation
_IsPC
bool Card._IsPC get
Definition at line 2045 of file Card.cs.
Referenced by ConHallucination.OnRemoved(), and ConHallucination.SetOwner().
_placeState
PlaceState Card._placeState get set
Definition at line 273 of file Card.cs.
    {
        get
        {
            return _ints[18].ToEnum<PlaceState>();
        }
        set
        {
            _ints[18] = (int)value;
        }
    }
Referenced by _OnDeserialized(), and _OnSerializing().
_x
int Card._x get set
Definition at line 165 of file Card.cs.
    {
        get
        {
            return _ints[7];
        }
        set
        {
            _ints[7] = value;
        }
    }
Referenced by _OnDeserialized(), _OnSerializing(), and AI_Clean.GetCleanPoint().
_z
int Card._z get set
Definition at line 177 of file Card.cs.
    {
        get
        {
            return _ints[9];
        }
        set
        {
            _ints[9] = value;
        }
    }
Referenced by _OnDeserialized(), and _OnSerializing().
actorPrefab
virtual string Card.actorPrefab get
Definition at line 2029 of file Card.cs.
AliasMaterialOnCreate
virtual string Card.AliasMaterialOnCreate get
Definition at line 1953 of file Card.cs.
Referenced by Create().
altitude
int Card.altitude get set
Definition at line 213 of file Card.cs.
    {
        get
        {
            return _ints[13];
        }
        set
        {
            _ints[13] = value;
        }
    }
Referenced by SerializedCards.Add(), CardRenderer.Draw(), BaseTileMap.DrawTile(), TileMapElona.DrawTile(), Duplicate(), Cell.GetSurfaceHeight(), BaseTileMap.GetThingPosition(), AM_MoveInstalled.OnProcessTiles(), and SetPlaceState().
ammoData
Thing Card.ammoData get set
Definition at line 1708 of file Card.cs.
    {
        get
        {
            return GetObj<Thing>(9);
        }
        set
        {
            SetObj(9, value);
        }
    }
Referenced by AttackProcess.Prepare(), and Trait.SetMainText().
autoRefuel
bool Card.autoRefuel get set
Definition at line 597 of file Card.cs.
    {
        get
        {
            return _bits1[17];
        }
        set
        {
            _bits1[17] = value;
        }
    }
Referenced by Create(), Trait.IsFuelEnough(), LayerDragGrid.RefreshCost(), LayerCraft.RefreshProduct(), and LayerCraft.SetFactory().
blessedState
BlessedState Card.blessedState get set
Definition at line 261 of file Card.cs.
    {
        get
        {
            return _ints[17].ToEnum<BlessedState>();
        }
        set
        {
            _ints[17] = (int)value;
        }
    }
Referenced by Thing.CanStackTo(), CoreDebug.ChangeRace(), Duplicate(), CharaBody.Equip(), CharaBody.IsEquippable(), InvOwnerEquip.IsFailByCurse(), InvOwner.ListInteractions(), TraitDrink.OnBlend(), TraitWell.OnBlend(), InvOwner.OnDrag(), TraitDrink.OnDrink(), TraitAltar.OnOffer(), TraitScrollStatic.OnRead(), TraitItemProc.OnUse(), TraitMannequin.OnUse(), TraitScrollMapTreasure.OnUse(), ActZap.Perform(), HotItemEQSet.Perform(), ActEffect.Proc(), AI_UseCrafter.Run(), SetBlessedState(), ButtonGrid.SetCard(), Chara.ShouldEquip(), and TraitBaseSpellbook.TryProgress().
c_allowance
int Card.c_allowance get set
Definition at line 1276 of file Card.cs.
    {
        get
        {
            return GetInt(114);
        }
        set
        {
            SetInt(114, value);
        }
    }
Referenced by WindowChara.RefreshProfile(), and AI_Shopping.TryShop().
c_altName
string Card.c_altName get set
Definition at line 1516 of file Card.cs.
    {
        get
        {
            return GetStr(1);
        }
        set
        {
            SetStr(1, value);
        }
    }
Referenced by Thing.CanStackTo(), TraitFood.CanStackTo(), GameIndex.Create(), UICharaMaker.EditName(), CoreDebug.GetDebugContainer(), CoreDebug.GetOrCreateDebugContainer(), QuestDeliver.IsDestThing(), BaseListPeople.OnClick(), UICharaMaker.Refresh(), UIInventory.RefreshMenu(), Map.Save(), TraitBaseContainer.SetName(), TraitParcel.SetName(), and TryGetFoodName().
c_altName2
string Card.c_altName2 get set
Definition at line 1528 of file Card.cs.
    {
        get
        {
            return GetStr(2);
        }
        set
        {
            SetStr(2, value);
        }
    }
c_ammo
int Card.c_ammo get set
Definition at line 1408 of file Card.cs.
    {
        get
        {
            return GetInt(27);
        }
        set
        {
            SetInt(27, value);
        }
    }
Referenced by ActMelee.Attack(), Trait.SetMainText(), and GoalAutoCombat.TryUseRanged().
c_bedType
BedType Card.c_bedType get set
Definition at line 899 of file Card.cs.
    {
        get
        {
            return GetInt(9).ToEnum<BedType>();
        }
        set
        {
            SetInt(9, (int)value);
        }
    }
Referenced by FactionBranch.CalcInnIncome(), TraitBed.CanAssign(), TraitBed.SetBedType(), TraitBed.SetName(), and TraitBed.TrySetAct().
c_bill
int Card.c_bill get set
Definition at line 1240 of file Card.cs.
    {
        get
        {
            return GetInt(23);
        }
        set
        {
            SetInt(23, value);
        }
    }
Referenced by ThingGen.CreateBill(), and InvOwnerDeliver.PayBill().
c_bossType
BossType Card.c_bossType get set
Definition at line 1180 of file Card.cs.
    {
        get
        {
            return GetInt(65).ToEnum<BossType>();
        }
        set
        {
            SetInt(65, (int)value);
        }
    }
Referenced by GuildFighter.CanGiveContribution(), TraitToolBrush.IsTamePossible(), CardRenderer.RefreshExtra(), and GoalCombat.Run().
c_charaList
CharaList Card.c_charaList get set
Definition at line 1816 of file Card.cs.
    {
        get
        {
            return GetObj<CharaList>(13);
        }
        set
        {
            SetObj(13, value);
        }
    }
Referenced by TraitBed.AddHolder(), TraitBed.CanAssign(), TraitBed.ClearHolders(), TraitBed.GetHoverText(), TraitBed.HasHolder(), TraitBed.IsFull(), TraitBed.IsHolder(), TraitBed.RemoveHolder(), TraitBed.SetName(), and TraitBed.ValidateOwners().
c_charges
int Card.c_charges get set
Definition at line 1228 of file Card.cs.
    {
        get
        {
            return GetInt(7);
        }
        set
        {
            SetInt(7, value);
        }
    }
Referenced by InvOwnerRefuel._OnProcess(), TaskDrawWater.CanProgress(), TaskPourWater.CanProgress(), Thing.CanStackTo(), ActDrawWater.HasWaterSource(), Trait.IsFuelEnough(), TraitBaseSpellbook.ModCharge(), ModCharge(), Trait.OnBarter(), TaskPourWater.OnCreateProgress(), TraitBaseSpellbook.OnRead(), QuestFiamaLock.OnStart(), ActZap.Perform(), LayerCraft.RefreshProduct(), AI_UseCrafter.Run(), SecondaryCompare(), SetCharge(), Trait.SetMainText(), ConSleep.SuccubusVisit(), Chara.TryAbsorbRod(), Trait.TrySetToggleAct(), HotItemHeld.TrySetToolAct(), and Map.TryShatter().
c_color
string Card.c_color get set
Definition at line 1480 of file Card.cs.
    {
        get
        {
            return GetStr(8);
        }
        set
        {
            SetStr(8, value);
        }
    }
c_containerSize
int Card.c_containerSize get set
Definition at line 1312 of file Card.cs.
    {
        get
        {
            return GetInt(8);
        }
        set
        {
            SetInt(8, value);
        }
    }
Referenced by Duplicate(), and TraitWrench.Upgrade().
c_containerUpgrade
ContainerUpgrade Card.c_containerUpgrade get set
Definition at line 1792 of file Card.cs.
    {
        get
        {
            return GetObj<ContainerUpgrade>(12) ?? (c_containerUpgrade = new ContainerUpgrade());
        }
        set
        {
            SetObj(12, value);
        }
    }
Referenced by TraitWrench.Upgrade().
c_context
string Card.c_context get set
Definition at line 1600 of file Card.cs.
    {
        get
        {
            return GetStr(20);
        }
        set
        {
            SetStr(20, value);
        }
    }
Referenced by TraitDaggerGrave.OnUse().
c_copyContainer
Thing Card.c_copyContainer get set
Definition at line 1732 of file Card.cs.
    {
        get
        {
            return GetObj<Thing>(10);
        }
        set
        {
            SetObj(10, value);
        }
    }
Referenced by Trait.OnBarter().
c_corruptionHistory
List<int> Card.c_corruptionHistory get set
Definition at line 1780 of file Card.cs.
    {
        get
        {
            return GetObj<List<int>>(16);
        }
        set
        {
            SetObj(16, value);
        }
    }
c_dateCooked
int Card.c_dateCooked get set
Definition at line 1300 of file Card.cs.
    {
        get
        {
            return GetInt(66);
        }
        set
        {
            SetInt(66, value);
        }
    }
c_dateDeathLock
int Card.c_dateDeathLock get set
Definition at line 1204 of file Card.cs.
    {
        get
        {
            return GetInt(130);
        }
        set
        {
            SetInt(130, value);
        }
    }
c_dateStockExpire
int Card.c_dateStockExpire get set
Definition at line 1192 of file Card.cs.
    {
        get
        {
            return GetInt(22);
        }
        set
        {
            SetInt(22, value);
        }
    }
Referenced by Trait.GetRestockedIcon(), Trait.GetTextRestock(), and Trait.OnBarter().
c_daysWithGod
int Card.c_daysWithGod get set
Definition at line 1420 of file Card.cs.
    {
        get
        {
            return GetInt(57);
        }
        set
        {
            SetInt(57, value);
        }
    }
Referenced by Player.OnAdvanceDay(), and WindowChara.RefreshNote().
c_diceDim
int Card.c_diceDim get set
Definition at line 1336 of file Card.cs.
    {
        get
        {
            return GetInt(14);
        }
        set
        {
            SetInt(14, value);
        }
    }
Referenced by AttackProcess.Prepare().
c_DNA
DNA Card.c_DNA get set
Definition at line 1804 of file Card.cs.
    {
        get
        {
            return GetObj<DNA>(14);
        }
        set
        {
            SetObj(14, value);
        }
    }
Referenced by InvOwnerGene._OnProcess(), DNA.CopyDNA(), TraitCrafter.Craft(), TraitGene.GetName(), TraitGene.GetValue(), InvOwnerGene.OnWriteNote(), ActEffect.Proc(), InvOwnerGene.ShouldShowGuide(), and TraitGene.WriteNote().
c_dyeMat
int Card.c_dyeMat get set
Definition at line 1144 of file Card.cs.
    {
        get
        {
            return GetInt(3);
        }
        set
        {
            SetInt(3, value);
        }
    }
Referenced by Thing.CanStackTo(), and TraitToolWaterPot.SetName().
c_editorTags
string Card.c_editorTags get set
Definition at line 1624 of file Card.cs.
    {
        get
        {
            return GetStr(28);
        }
        set
        {
            SetStr(28, value);
        }
    }
Referenced by HotItemNoItem._TrySetAct(), SerializedCards.Add(), AddEditorTag(), AM_EditMarker.GetSimpleText(), HasEditorTag(), RemoveEditorTag(), and CardInspector.SetCard().
c_editorTraitVal
string Card.c_editorTraitVal get set
Definition at line 1636 of file Card.cs.
    {
        get
        {
            return GetStr(25);
        }
        set
        {
            SetStr(25, value);
        }
    }
Referenced by SerializedCards.Add(), AM_EditMarker.GetSimpleText(), and CardInspector.SetCard().
c_equippedSlot
int Card.c_equippedSlot get set
Definition at line 911 of file Card.cs.
    {
        get
        {
            return GetInt(6);
        }
        set
        {
            SetInt(6, value);
        }
    }
Referenced by HotItemEQSet.Perform(), UIInventory.RefreshList(), RemoveThing(), ButtonGrid.SetCard(), and CharaBody.Unequip().
c_extraNameRef
string Card.c_extraNameRef get set
Definition at line 1540 of file Card.cs.
    {
        get
        {
            return GetStr(12);
        }
        set
        {
            SetStr(12, value);
        }
    }
Referenced by MakeRefFrom().
c_fixedValue
int Card.c_fixedValue get set
Definition at line 1132 of file Card.cs.
    {
        get
        {
            return GetInt(131);
        }
        set
        {
            SetInt(131, value);
        }
    }
c_fur
int Card.c_fur get set
Definition at line 1288 of file Card.cs.
    {
        get
        {
            return GetInt(62);
        }
        set
        {
            SetInt(62, value);
        }
    }
Referenced by FactionBranch.DailyOutcome(), AI_Shear.GetFurLv(), TraitToolShears.GetHeldEmo(), AI_Shear.GetText(), and AI_Slaughter.GetText().
c_genes
CharaGenes Card.c_genes get set
Definition at line 1768 of file Card.cs.
    {
        get
        {
            return GetObj<CharaGenes>(15);
        }
        set
        {
            SetObj(15, value);
        }
    }
Referenced by InvOwnerGene._OnProcess(), DNA.Apply(), TraitGeneMachine.OnUse(), InvOwnerGene.OnWriteNote(), WindowCharaMini.Refresh(), and Tactics.Tactics().
c_idAbility
string Card.c_idAbility get set
Definition at line 1588 of file Card.cs.
    {
        get
        {
            return GetStr(50);
        }
        set
        {
            SetStr(50, value);
        }
    }
Referenced by TraitAbility.CreateAct(), TraitAbility.SetMainText(), and TraitAbility.SetName().
c_idBacker
int Card.c_idBacker get set
Definition at line 1384 of file Card.cs.
    {
        get
        {
            return GetInt(52);
        }
        set
        {
            SetInt(52, value);
        }
    }
Referenced by SerializedCards.Add(), Zone_Casino.OnActivate(), SerializedCards.Restore(), Zone.Revive(), and TraitSpecialLantern.TrySetAct().
c_idDeity
string Card.c_idDeity get set
Definition at line 1504 of file Card.cs.
    {
        get
        {
            return GetStr(26);
        }
        set
        {
            SetStr(26, value);
        }
    }
Referenced by SerializedCards.Add(), TraitAltar.CanOffer(), Element.IsActive(), ElementContainerFaction.IsEffective(), Trait.OfferProcess(), TraitAltar.OnImportMap(), TraitAltar.OnOffer(), ButtonElement.SetGrid(), and TraitAltar.SetName().
c_idEditor
string Card.c_idEditor get set
Definition at line 1612 of file Card.cs.
    {
        get
        {
            return GetStr(27);
        }
        set
        {
            SetStr(27, value);
        }
    }
Referenced by SerializedCards.Add(), and AM_EditMarker.GetSimpleText().
c_idJob
string Card.c_idJob get set
Definition at line 1456 of file Card.cs.
    {
        get
        {
            return GetStr(4);
        }
        set
        {
            SetStr(4, value);
        }
    }
c_idMainElement
int Card.c_idMainElement get set
Definition at line 1360 of file Card.cs.
    {
        get
        {
            return GetInt(16);
        }
        set
        {
            SetInt(16, value);
        }
    }
Referenced by SerializedCards.Add(), TraitFoodEggFertilized.CanStackTo(), and Chara.MakeEgg().
c_idPortrait
string Card.c_idPortrait get set
Definition at line 1432 of file Card.cs.
    {
        get
        {
            return GetStr(9);
        }
        set
        {
            SetStr(9, value);
        }
    }
Referenced by LayerEditPCC.Activate(), GameIndex.Create(), and LayerEditPortrait.RefreshList().
c_idRace
string Card.c_idRace get set
Definition at line 1444 of file Card.cs.
    {
        get
        {
            return GetStr(3);
        }
        set
        {
            SetStr(3, value);
        }
    }
c_idRefCard
string Card.c_idRefCard get set
Definition at line 1660 of file Card.cs.
    {
        get
        {
            return GetStr(5);
        }
        set
        {
            SetStr(5, value);
        }
    }
Referenced by SerializedCards.Add(), Thing.CanStackTo(), TraitFood.CanStackTo(), ContentCodex.Collect(), DNA.CopyDNA(), RecipeCard.Craft(), FactionBranch.DailyOutcome(), CardRenderer.Draw(), HomeResourceWorth.ListHeirloom(), CraftUtil.MakeDish(), MakeFoodRef(), TraitDrinkMilkMother.OnDrink(), TraitFigure.OnSetCardGrid(), TraitContainer.Open(), Chara.Pick(), and TryGetFoodName().
c_idRefCard2
string Card.c_idRefCard2 get set
Definition at line 1672 of file Card.cs.
    {
        get
        {
            return GetStr(6);
        }
        set
        {
            SetStr(6, value);
        }
    }
Referenced by Thing.CanStackTo().
c_idRefName
string Card.c_idRefName get set
Definition at line 1564 of file Card.cs.
    {
        get
        {
            return GetStr(7);
        }
        set
        {
            SetStr(7, value);
        }
    }
Referenced by Chara.GiveGift(), TraitBaseSpellbook.OnRead(), AM_Blueprint.OnSave(), TraitBaseContainer.SetName(), TraitBaseSpellbook.SetName(), TraitBlueprint.SetName(), TraitParcel.SetName(), and ActThrow.Throw().
c_idRidePCC
string Card.c_idRidePCC get set
Definition at line 1576 of file Card.cs.
    {
        get
        {
            return GetStr(55);
        }
        set
        {
            SetStr(55, value);
        }
    }
Referenced by ActPlan._Update().
c_idTalk
string Card.c_idTalk get set
Definition at line 1492 of file Card.cs.
    {
        get
        {
            return GetStr(21);
        }
        set
        {
            SetStr(21, value);
        }
    }
Referenced by Person.GetDramaTitle().
c_idTone
string Card.c_idTone get set
Definition at line 1468 of file Card.cs.
    {
        get
        {
            return GetStr(22);
        }
        set
        {
            SetStr(22, value);
        }
    }
Referenced by Person.GetDramaTitle(), and Person.SetChara().
c_idTrait
string Card.c_idTrait get set
Definition at line 1648 of file Card.cs.
    {
        get
        {
            return GetStr(29);
        }
        set
        {
            SetStr(29, value);
        }
    }
Referenced by SerializedCards.Add(), ApplyTrait(), and AM_EditMarker.GetSimpleText().
c_IDTState
int Card.c_IDTState get set
Definition at line 1216 of file Card.cs.
    {
        get
        {
            return GetInt(2);
        }
        set
        {
            SetInt(2, value);
        }
    }
Referenced by Thing.CanStackTo(), Player.CreateEquip(), Player.OnAdvanceHour(), and DramaOutcome.QuestExploration_Drop1().
c_indexContainerIcon
int Card.c_indexContainerIcon get set
Definition at line 1348 of file Card.cs.
    {
        get
        {
            return GetInt(15);
        }
        set
        {
            SetInt(15, value);
        }
    }
Referenced by ButtonGrid.SetCard().
c_invest
int Card.c_invest get set
Definition at line 1252 of file Card.cs.
    {
        get
        {
            return GetInt(28);
        }
        set
        {
            SetInt(28, value);
        }
    }
Referenced by TraitChara.GetDramaText(), and CalcMoney.InvestShop().
c_isDisableStockUse
bool Card.c_isDisableStockUse get set
Definition at line 1043 of file Card.cs.
    {
        get
        {
            return GetInt(122) != 0;
        }
        set
        {
            SetInt(122, value ? 1 : 0);
        }
    }
Referenced by UIDragGridIngredients.Refresh(), and LayerDragGrid.RefreshCost().
c_isImportant
bool Card.c_isImportant get set
Definition at line 983 of file Card.cs.
    {
        get
        {
            return GetInt(109) != 0;
        }
        set
        {
            SetInt(109, value ? 1 : 0);
        }
    }
Referenced by Chara.CanAcceptGift(), Chara.CanAcceptItem(), Chara.CanEat(), ActThrow.CanThrow(), Chara.DropThing(), Chara.FindBestFoodToEat(), Trait.GetFuelValue(), FactionBranch.GetMeal(), Chara.InstantEat(), QuestDeliver.IsDestThing(), QuestSupplyCat.IsDestThing(), IsExcludeFromCraft(), TraitCrafter.IsIngredient(), TraitRuneMold.IsIngredient(), InvOwner.Transaction.IsValid(), InvOwner.ListInteractions(), InvOwner.OnDrag(), InvOwner.Transaction.Process(), BuildMenu.RefreshCategory(), AI_Idle.Run(), ButtonGrid.SetCard(), Props.ShouldListAsResource(), InvOwnerRecycle.ShouldShowGuide(), HotItemHeld.TrySetAct(), TryStackTo(), and Chara.TryTakeSharedItems().
c_isPrayed
bool Card.c_isPrayed get set
Definition at line 1031 of file Card.cs.
    {
        get
        {
            return GetInt(121) != 0;
        }
        set
        {
            SetInt(121, value ? 1 : 0);
        }
    }
Referenced by FactionBranch.OnSimulateDay(), and GoalIdle.Run().
c_isTrained
bool Card.c_isTrained get set
Definition at line 1019 of file Card.cs.
    {
        get
        {
            return GetInt(120) != 0;
        }
        set
        {
            SetInt(120, value ? 1 : 0);
        }
    }
c_lightColor
int Card.c_lightColor get set
Definition at line 1055 of file Card.cs.
    {
        get
        {
            return GetInt(5);
        }
        set
        {
            Mod();
            SetInt(5, value);
        }
    }
Referenced by ActPlan._Update(), and SerializedCards.Add().
c_lockedHard
bool Card.c_lockedHard get set
Definition at line 995 of file Card.cs.
    {
        get
        {
            return GetInt(63) != 0;
        }
        set
        {
            SetInt(63, value ? 1 : 0);
        }
    }
Referenced by Trait.TryOpenLock().
c_lockLv
int Card.c_lockLv get set
Definition at line 923 of file Card.cs.
    {
        get
        {
            return GetInt(50);
        }
        set
        {
            SetInt(50, value);
        }
    }
Referenced by Chara._Move(), DramaCustomSequence.Build(), AI_Shopping.Buy(), TraitGambleChest.CanStackTo(), ThingGen.CreateTreasureContent(), InvOwner.Transaction.IsValid(), AI_Steal.IsValidTC(), Props.ListThingStack(), ConSleep.OnRemoved(), TraitChestPractice.OnSimulateHour(), ZoneEventBeggerChest.OnTickRound(), CalcMoney.Picklock(), TraitBaseContainer.Prespawn(), BuildMenu.RefreshCategory(), Chara.Revive(), AI_OpenGambleChest.Run(), Zone.TryAddThingInSharedContainer(), TraitContainer.TryOpen(), Trait.TryOpenLock(), TraitContainer.TrySetAct(), and TraitDoor.TrySetAct().
c_minionType
MinionType Card.c_minionType get set
Definition at line 947 of file Card.cs.
    {
        get
        {
            return GetInt(61).ToEnum<MinionType>();
        }
        set
        {
            SetInt(61, (int)value);
        }
    }
Referenced by TaskCullLife.CanCull(), Zone.CountMinions(), Zone.ListMinions(), and Chara.MoveZone().
c_note
string Card.c_note get set
Definition at line 1684 of file Card.cs.
    {
        get
        {
            return GetStr(51);
        }
        set
        {
            SetStr(51, value);
        }
    }
Referenced by TraitNote.CanStackTo(), and TraitNote.TrySetAct().
c_originalHostility
Hostility Card.c_originalHostility get set
Definition at line 935 of file Card.cs.
    {
        get
        {
            return GetInt(12).ToEnum<Hostility>();
        }
        set
        {
            SetInt(12, (int)value);
        }
    }
Referenced by Chara.CreateReplacement().
c_priceAdd
int Card.c_priceAdd get set
Definition at line 1108 of file Card.cs.
    {
        get
        {
            return GetInt(29);
        }
        set
        {
            SetInt(29, value);
        }
    }
Referenced by Thing.CanStackTo().
c_priceCopy
int Card.c_priceCopy get set
Definition at line 1120 of file Card.cs.
    {
        get
        {
            return GetInt(124);
        }
        set
        {
            SetInt(124, value);
        }
    }
Referenced by CraftUtil.MixIngredients().
c_priceFix
int Card.c_priceFix get set
Definition at line 1096 of file Card.cs.
    {
        get
        {
            return GetInt(21);
        }
        set
        {
            SetInt(21, value);
        }
    }
Referenced by Thing.CanStackTo().
c_refText
string Card.c_refText get set
Definition at line 1552 of file Card.cs.
    {
        get
        {
            return GetStr(10);
        }
        set
        {
            SetStr(10, value);
        }
    }
Referenced by ActPlan._Update(), Cell.GetObjName(), and TraitSeed.MakeSeed().
c_rescueState
RescueState Card.c_rescueState get set
Definition at line 1168 of file Card.cs.
    {
        get
        {
            return GetInt(53).ToEnum<RescueState>();
        }
        set
        {
            SetInt(53, (int)value);
        }
    }
c_revealLock
bool Card.c_revealLock get set
Definition at line 1007 of file Card.cs.
    {
        get
        {
            return GetInt(64) != 0;
        }
        set
        {
            SetInt(64, value ? 1 : 0);
        }
    }
Referenced by Trait.OnBarter().
c_seed
int Card.c_seed get set
Definition at line 1264 of file Card.cs.
    {
        get
        {
            return GetInt(33);
        }
        set
        {
            SetInt(33, value);
        }
    }
Referenced by TraitGodStatue._OnUse(), DNA.GenerateManiGene(), TraitSeed.LevelSeed(), and TraitSeed.MakeSeed().
c_summonDuration
int Card.c_summonDuration get set
Definition at line 1372 of file Card.cs.
    {
        get
        {
            return GetInt(17);
        }
        set
        {
            SetInt(17, value);
        }
    }
c_textureData
byte [] Card.c_textureData get set
Definition at line 1828 of file Card.cs.
    {
        get
        {
            return GetObj<byte[]>(4);
        }
        set
        {
            SetObj(4, value);
        }
    }
Referenced by TraitPainter.GetCanvas(), TraitCanvas.OnSetCardGrid(), CardActor.RefreshSprite(), LayerPixelPaint.SetCanvas(), and TraitCanvas.TrySetAct().
c_uidMaster
int Card.c_uidMaster get set
Definition at line 1396 of file Card.cs.
    {
        get
        {
            return GetInt(54);
        }
        set
        {
            SetInt(54, value);
        }
    }
Referenced by Chara.CanReplace(), Zone.CountMinions(), Zone.ListMinions(), Chara.MoveZone(), ActEffect.ProcAt(), and AI_Idle.Run().
c_uidRefCard
int Card.c_uidRefCard get set
Definition at line 1083 of file Card.cs.
    {
        get
        {
            return GetInt(11);
        }
        set
        {
            Mod();
            SetInt(11, value);
        }
    }
Referenced by TraitShackle.IsRestraining().
c_uidZone
int Card.c_uidZone get set
Definition at line 1070 of file Card.cs.
    {
        get
        {
            return GetInt(10);
        }
        set
        {
            Mod();
            SetInt(10, value);
        }
    }
c_uniqueData
UniqueData Card.c_uniqueData get set
Definition at line 1696 of file Card.cs.
    {
        get
        {
            return GetObj<UniqueData>(6);
        }
        set
        {
            SetObj(6, value);
        }
    }
c_upgrades
CharaUpgrade Card.c_upgrades get set
Definition at line 1756 of file Card.cs.
    {
        get
        {
            return GetObj<CharaUpgrade>(11);
        }
        set
        {
            SetObj(11, value);
        }
    }
Referenced by WindowCharaMini.Refresh().
c_vomit
int Card.c_vomit get set
Definition at line 959 of file Card.cs.
    {
        get
        {
            return GetInt(13);
        }
        set
        {
            SetInt(13, value);
        }
    }
c_wasInPcParty
bool Card.c_wasInPcParty get set
Definition at line 971 of file Card.cs.
    {
        get
        {
            return GetInt(103) != 0;
        }
        set
        {
            SetInt(103, value ? 1 : 0);
        }
    }
Referenced by FactionBranch.DailyOutcome(), and FactionBranch.OnAfterSimulate().
c_weight
int Card.c_weight get set
Definition at line 1324 of file Card.cs.
    {
        get
        {
            return GetInt(1);
        }
        set
        {
            SetInt(1, value);
        }
    }
Referenced by ChangeWeight().
c_windowSaveData
Window.SaveData Card.c_windowSaveData get set
Definition at line 1744 of file Card.cs.
    {
        get
        {
            return GetObj<Window.SaveData>(2);
        }
        set
        {
            SetObj(2, value);
        }
    }
Referenced by LayerInventory.CreateContainer(), LayerInventory.CreateContainer< T >(), and GetWindowSaveData().
CanInspect
bool Card.CanInspect get
Implements IInspect.
Definition at line 2369 of file Card.cs.
    {
        get
        {
            if (!isDestroyed)
            {
                return ExistsOnMap;
            }
            return false;
        }
    }
category
SourceCategory.Row Card.category get
Definition at line 1949 of file Card.cs.
Referenced by AI_Shopping.Buy(), Chara.CanAcceptItem(), CanAddRune(), TraitDrink.CanBlend(), TraitWell.CanBlend(), RecipeCard.Craft(), Create(), FactionBranch.DailyOutcome(), CardRenderer.Draw(), BaseTileMap.DrawTile(), CharaBody.Equip(), ThingContainer.GetDest(), Religion.GetOfferingValue(), TraitTicketFurniture.GetPrice(), TraitBrewery.GetProductID(), CharaBody.GetSlot(), TaskBuild.GetText(), QuestSupplyCat.IsDestThing(), Recipe.Ingredient.IsValidIngredient(), Props.ListThingsInCategory(), Props.ListThingStack(), TaskDump.ListThingsToPut(), Trait.OnBarter(), TraitBrewery.OnChildDecay(), InvOwner.OnDrag(), Affinity.OnGift(), Props.OnNumChange(), AttackProcess.Prepare(), ThingContainer.RefreshGrid(), UIInventory.RefreshList(), AI_Idle.Run(), AI_Steal.Run(), AI_UseCrafter.Run(), Chara.ShouldEquip(), InvOwnerChangeMaterial.ShouldShowGuide(), InvOwnerDeliver.ShouldShowGuide(), InvOwnerDeliverBox.ShouldShowGuide(), InvOwnerEnchant.ShouldShowGuide(), InvOwnerLighten.ShouldShowGuide(), InvOwnerReconstruction.ShouldShowGuide(), InvOwnerRecycle.ShouldShowGuide(), Chara.ShouldThrowAway(), ActThrow.Throw(), Zone.TryAddThingInSharedContainer(), Chara.TryEquip(), Zone.TryGetRestock< T >(), Chara.TryPutSharedItems(), Chara.TryReservePickupTutorial(), Map.TryShatter(), and LayerInventory.TryShowGuide().
Cell
Cell Card.Cell get
Definition at line 1955 of file Card.cs.
Referenced by Map._AddCard(), WidgetDate._Refresh(), Map._RemoveCard(), CardRenderer.Draw(), CharaRenderer.DrawHeld(), ActionMode.GetSimpleText(), ActorEx.GetVolume(), CharaActorPCC.OnRender(), TraitClock.OnSimulateHour(), TraitFertilizer.OnSimulateHour(), TraitGenerator.OnSimulateHour(), Fov.Perform(), CardActor.RefreshSprite(), AI_Idle.Run(), PointTarget.ShouldIgnore(), ConSuffocation.Tick(), ConWet.Tick(), AI_Goto.TryGoTo(), TraitDoor.TryOpen(), Trait.TryToggle(), and CharaRenderer.UpdatePosition().
CHA
int Card.CHA get
Definition at line 2247 of file Card.cs.
Referenced by AI_Fuck.Finish(), Chara.GiveGift(), CalcMoney.Invest(), CalcMoney.Negotiate(), Affinity.OnTalkRumor(), AI_Fuck.Run(), ConChampagne.Tick(), and CalcMoney.Whore().
Chara
virtual Chara Card.Chara get
Definition at line 1969 of file Card.cs.
    {
        get
        {
            if (!isChara)
            {
                return null;
            }
            return (Chara)this;
        }
    }
Referenced by InvOwnerBlend._OnProcess(), ActPlan._Update(), SerializedCards.Add(), Props.Add(), Cell.AddCard(), Zone.AddCard(), Map.AddCardOnActivate(), InvOwner.AllowHold(), Feat.Apply(), ApplyEditorTags(), Thing.ApplyMaterialElements(), ActMelee.Attack(), GuildFighter.CanGiveContribution(), ActNTR.CanPerform(), ActRestrain.CanPerform(), Chara.CanSee(), Chara.CanSeeLos(), InvOwner.CanShiftClick(), TraitSalesTag.CanTagSale(), Faction.CountMembers(), ActEffect.DamageEle(), DamageHP(), Chara.Die(), Chara.DoHostileAction(), DragItemCard.DragInfo.DragInfo(), CardRenderer.Draw(), AI_Fuck.Finish(), Biography.Generate(), AI_Shear.GetFur(), LayerInspect.GetItem(), CardRow.GetName(), CardRenderer.GetPref(), Chara.GoHostile(), InvOwner.Grab(), Chara.HasHigherGround(), ElementContainer.ListElements(), InvOwner.ListInteractions(), MakeFoodFrom(), ElementContainer.ModExp(), Trait.OnBarter(), AI_Slaughter.OnCancelOrSuccess(), Map.OnCardAddedToZone(), Map.OnCardRemovedFromZone(), InvOwner.OnClick(), InvOwner.OnDrag(), ElementContainerCard.OnLevelDown(), ElementContainerCard.OnLevelUp(), AM_MoveInstalled.OnProcessTiles(), ItemGeneral.OnRefreshPref(), ActChat.Perform(), ActDreamBug.Perform(), ActKick.Perform(), ActNTR.Perform(), ActRanged.Perform(), ActRestrain.Perform(), ActEffect.Proc(), ActEffect.ProcAt(), InvOwner.Transaction.Process(), InvOwner.PutBack(), CardRenderer.RefreshExtra(), Props.Remove(), Cell.RemoveCard(), RemoveThing(), SerializedCards.Restore(), AI_AttackHome.Run(), AI_Shear.Run(), AI_Slaughter.Run(), AI_Steal.Run(), GoalSiege.Run(), ButtonGrid.SetBodySlot(), ButtonGeneral.SetCard(), Portrait.SetChara(), Meeting.SetChara(), PointTarget.ShouldIgnore(), ActThrow.Throw(), TryMakeRandomItem(), Trait.TrySetAct(), TraitLeash.TrySetHeldAct(), TraitStethoscope.TrySetHeldAct(), TraitWhipLove.TrySetHeldAct(), Map.TryShatter(), and ElementContainerCard.ValueBonus().
ChildrenAndSelfWeight
int Card.ChildrenAndSelfWeight get
Definition at line 1941 of file Card.cs.
Referenced by Thing.CanStackTo(), CharaBody.GetWeight(), CharaBody.IsTooHeavyToEquip(), Zone_Tent.OnBeforeDeactivate(), AI_Fish.ProgressFish.OnProgressComplete(), AI_Idle.Run(), AI_Steal.Run(), and ButtonGrid.SetCard().
ChildrenAndSelfWeightSingle
int Card.ChildrenAndSelfWeightSingle get
Definition at line 1943 of file Card.cs.
ChildrenWeight
int Card.ChildrenWeight get
Definition at line 1912 of file Card.cs.
    {
        get
        {
            if (dirtyWeight)
            {
                _childrenWeight = 0;
                if (!(trait is TraitMagicChest))
                {
                    foreach (Thing thing in things)
                    {
                        _childrenWeight += thing.ChildrenAndSelfWeight;
                    }
                    dirtyWeight = false;
                    (parent as Card)?.SetDirtyWeight();
                    if (isChara && IsPCFaction)
                    {
                        Chara.CalcBurden();
                    }
                    if (_childrenWeight < 0 || _childrenWeight > 10000000)
                    {
                        _childrenWeight = 10000000;
                    }
                }
            }
            return _childrenWeight * Mathf.Max(100 - Evalue(404), 0) / 100;
        }
    }
Referenced by UICurrency.Build(), AI_Fish.ProgressFish.OnProgressComplete(), and AttackProcess.Prepare().
colorInt
int Card.colorInt get
Definition at line 103 of file Card.cs.
    {
        get
        {
            if (_colorInt == 0)
            {
                RefreshColor();
            }
            return _colorInt;
        }
    }
decay
int Card.decay get set
Definition at line 201 of file Card.cs.
    {
        get
        {
            return _ints[12];
        }
        set
        {
            _ints[12] = value;
        }
    }
Referenced by ChangeMaterial(), Duplicate(), TaskHarvest.HarvestThing(), and TryStackTo().
DefaultLV
int Card.DefaultLV get
Definition at line 1910 of file Card.cs.
Referenced by Create().
DefaultMaterial
virtual SourceMaterial.Row Card.DefaultMaterial get
Definition at line 2321 of file Card.cs.
Referenced by SerializedCards.Add().
DEX
int Card.DEX get
Definition at line 2235 of file Card.cs.
Referenced by ApplyProtection(), AttackProcess.Prepare(), GoalCombat.Run(), and TraitSwitch.TryDisarmTrap().
dir
int Card.dir get set
Definition at line 141 of file Card.cs.
    {
        get
        {
            return _ints[5];
        }
        set
        {
            _ints[5] = value;
        }
    }
Referenced by SerializedCards.Add(), CardRenderer.Draw(), CharaRenderer.DrawHeld(), BaseTileMap.DrawTile(), TileMapElona.DrawTile(), Duplicate(), TraitNewZone.GetExitPos(), MapBounds.GetSpawnPos(), BaseTileMap.GetThingPosition(), TraitDoor.IsOpen(), TraitDoor.IsValid(), TCExtra.OnDraw(), AM_MoveInstalled.OnProcessTiles(), TraitRoadSign.OnRenderTile(), Zone_Dungeon.PlaceRail(), CardActor.RefreshSprite(), RecipeCard.Rotate(), TraitDoor.RotateDoor(), ConSleep.Tick(), TraitPillowStrange.TrySetAct(), TraitSeed.TrySprout(), and WidgetDebug.UpdateText().
disableAutoToggle
bool Card.disableAutoToggle get set
Definition at line 573 of file Card.cs.
    {
        get
        {
            return _bits1[15];
        }
        set
        {
            _bits1[15] = value;
        }
    }
Referenced by Trait.TrySetToggleAct().
DMG
int Card.DMG get
Definition at line 2231 of file Card.cs.
Referenced by AttackProcess.Prepare().
DV
virtual int Card.DV get
Definition at line 2225 of file Card.cs.
Referenced by Thing.GetName().
DyeMat
SourceMaterial.Row Card.DyeMat get
Definition at line 1840 of file Card.cs.
Referenced by Recipe.GetColorMaterial(), Recipe.GetDefaultColor(), TaskPourWater.OnCreateProgress(), TraitToolWaterPot.SetName(), and ActionMode.UpdateInput().
encLV
int Card.encLV get set
Definition at line 309 of file Card.cs.
    {
        get
        {
            return _ints[20];
        }
        set
        {
            _ints[20] = value;
        }
    }
Referenced by AddRune(), ActMelee.Attack(), TraitTrainingDummyArmor.CalcPV(), Thing.CanStackTo(), Duplicate(), GrowSystem.EqualizePlants(), Element.GetMaterialSourceValue(), Cell.GetObjName(), GrowSystemTree.GetPlantBonus(), TraitMod.GetValue(), TraitSeed.LevelSeed(), CraftUtil.MakeDish(), TraitSeed.MakeSeed(), ModEncLv(), TraitDrinkMilkMother.OnDrink(), GrowSystemPasture.OnMineObj(), TraitAltar.OnOffer(), AttackProcess.Prepare(), ActEffect.Proc(), AI_Idle.Run(), SecondaryCompare(), and SetEncLv().
END
int Card.END get
Definition at line 2237 of file Card.cs.
Referenced by AI_Fuck.Finish(), and ConPoison.Tick().
ExistsOnMap
bool Card.ExistsOnMap get
Definition at line 1985 of file Card.cs.
Referenced by AM_Adv._OnUpdateInput(), HotItemNoItem._TrySetAct(), FactionBranch.AutoClean(), AI_Shopping.Buy(), ActThrow.CanPerform(), Chara.CanPick(), AI_TargetCard.CanProgress(), TaskHarvest.CanProgress(), ActThrow.CanThrow(), QuestDefense.CanUpdateOnTalk(), FactionBranch.DailyOutcome(), ActEffect.DamageEle(), CardRenderer.Draw(), AI_Fuck.Finish(), FactionBranch.GenerateGarbage(), TaskHarvest.GetHitResult(), Scene.Init(), TaskDump.IsValidContainer(), AI_Deconstruct.IsValidTarget(), AI_Slaughter.IsValidTC(), AI_Slaughter.OnCancelOrSuccess(), AI_UseCrafter.OnEnd(), TraitRollingFortune.OnEndAI(), CharaRenderer.OnEnterScreen(), AM_Build.OnFinishProcessTiles(), CardRenderer.OnLeaveScreen(), TaskMoveInstalled.OnProgressComplete(), ConSleep.OnRemoved(), TraitGiftNewYear.OnUse(), TraitItemProc.OnUse(), SourcePrefInspector.OnValidate(), TraitContainer.Open(), ActThrow.Perform(), EffectIRenderer.Play(), UIRecipeInfo.Refresh(), WidgetMouseover.Refresh(), BuildMenu.RefreshCategory(), AI_Cook.Run(), AI_Equip.Run(), AI_Grab< T >.Run(), AI_Haul.Run(), AI_Idle.Run(), AI_Offer.Run(), AI_PlayMusic.Run(), AI_Shopping.Run(), AI_Steal.Run(), AI_TargetCard.Run(), AI_Torture.Run(), AI_Trolley.Run(), AI_UseCrafter.Run(), GoalCombat.Run(), TaskMoveInstalled.Run(), AIWork.SetDestPos(), AI_PlayMusic.ThrowReward(), HotItemAct.TrySetAct(), TraitCatalyst.TrySetHeldAct(), and Thing.WriteNote().
exp
int Card.exp get set
Definition at line 381 of file Card.cs.
    {
        get
        {
            return _ints[26];
        }
        set
        {
            _ints[26] = value;
        }
    }
Referenced by AddExp(), Duplicate(), WidgetExp.Refresh(), WidgetExpHome.Refresh(), and WindowChara.RefreshNote().
ExpToNext
int Card.ExpToNext get
Definition at line 1908 of file Card.cs.
Referenced by AddExp(), Chara.GiveGift(), WidgetExp.Refresh(), WidgetExpHome.Refresh(), WindowChara.RefreshNote(), and CoreDebug.UpdateInput().
FameLv
int Card.FameLv get
Definition at line 2197 of file Card.cs.
    {
        get
        {
            if (!IsPC)
            {
                return LV;
            }
            return EClass.player.fame / 100 + 1;
        }
    }
Referenced by Region.CreateRandomSite(), ZonePreEnterEncounter.Execute(), Quest.Init(), CraftUtil.MixIngredients(), and Thing.WriteNote().
feat
int Card.feat get set
Definition at line 357 of file Card.cs.
    {
        get
        {
            return _ints[24];
        }
        set
        {
            _ints[24] = value;
        }
    }
Referenced by LevelUp(), InvOwnerGene.OnWriteNote(), ButtonElement.Refresh(), WidgetExp.Refresh(), WidgetExpHome.Refresh(), WindowCharaMini.Refresh(), and WindowChara.RefreshFeatMode().
flipX
virtual bool Card.flipX get
Definition at line 2015 of file Card.cs.
    {
        get
        {
            if (Tiles.Length == 1)
            {
                return dir % 2 == 1;
            }
            return false;
        }
    }
Referenced by CardRenderer.Draw(), BaseTileMap.DrawTile(), BaseTileMap.GetThingPosition(), and TraitPaintBoard.OnRenderExtra().
freePos
bool Card.freePos get set
Definition at line 489 of file Card.cs.
    {
        get
        {
            return _bits1[8];
        }
        set
        {
            _bits1[8] = value;
        }
    }
Referenced by BaseTileMap.DrawTile(), AM_MoveInstalled.OnProcessTiles(), RecipeCard.OnRenderMarker(), SerializedCards.Restore(), and SetPlaceState().
fx
float Card.fx get set
Definition at line 237 of file Card.cs.
    {
        get
        {
            return 0.001f * (float)_ints[15];
        }
        set
        {
            _ints[15] = (int)(value * 1000f);
        }
    }
Referenced by BaseTileMap.DrawTile(), RecipeCard.OnRenderMarker(), and SetPlaceState().
fy
float Card.fy get set
Definition at line 249 of file Card.cs.
    {
        get
        {
            return 0.001f * (float)_ints[16];
        }
        set
        {
            _ints[16] = (int)(value * 1000f);
        }
    }
Referenced by BaseTileMap.DrawTile(), RecipeCard.OnRenderMarker(), SerializedCards.Restore(), and SetPlaceState().
H
int Card.H get
Definition at line 2265 of file Card.cs.
    {
        get
        {
            if (dir % 2 != 0)
            {
                return sourceCard.W;
            }
            return sourceCard.H;
        }
    }
Referenced by HitSummary.CanExecute(), TraitBoat.ForeachDeck(), TaskMoveInstalled.Run(), AM_Adv.ShowAllAction(), and TraitNewZone.TrySetAct().
HasContainerSize
bool Card.HasContainerSize get
Definition at line 2307 of file Card.cs.
HasHost
virtual bool Card.HasHost get
Definition at line 2323 of file Card.cs.
Referenced by CardRenderer.GetPref(), ActEffect.Proc(), HotItemAct.TrySetAct(), and TraitCatalyst.TrySetHeldAct().
hasSpawned
bool Card.hasSpawned get set
Definition at line 873 of file Card.cs.
    {
        get
        {
            return _bits2[8];
        }
        set
        {
            _bits2[8] = value;
        }
    }
Referenced by Zone.AddCard().
HIT
int Card.HIT get
Definition at line 2229 of file Card.cs.
Referenced by AttackProcess.Prepare().
HostRenderer
CardRenderer Card.HostRenderer get
Definition at line 2341 of file Card.cs.
    {
        get
        {
            if (!isChara || Chara.host == null)
            {
                return renderer;
            }
            return Chara.host.renderer;
        }
    }
Referenced by AI_Idle.Run().
hp
int Card.hp get set
Definition at line 225 of file Card.cs.
    {
        get
        {
            return _ints[14];
        }
        set
        {
            _ints[14] = value;
        }
    }
Referenced by AM_Adv._OnUpdateInput(), FactionBranch.AddMemeber(), ActItem.BuildAct(), AttackProcess.CalcHit(), Create(), DamageHP(), GoalAutoCombat.GoalAutoCombat(), HealHP(), TraitGenerator.ModHP(), ButtonRoster.Refresh(), WidgetHP.Refresh(), ButtonGridExt.Refresh(), TCOrbitChara.RefreshAll(), AI_Idle.Run(), GoalCombat.Run(), ItemGeneral.SetChara(), SetLv(), Zone.Simulate(), ActThrow.Throw(), ConBleed.Tick(), and GoalCombat.TryUseAbility().
idMaterial
int Card.idMaterial get set
Definition at line 129 of file Card.cs.
    {
        get
        {
            return _ints[4];
        }
        set
        {
            _ints[4] = value;
        }
    }
Referenced by Thing.CanStackTo(), ChangeMaterial(), Create(), and Duplicate().
idSkin
int Card.idSkin get set
Definition at line 345 of file Card.cs.
    {
        get
        {
            return _ints[23];
        }
        set
        {
            _ints[23] = value;
        }
    }
Referenced by SerializedCards.Add(), Thing.CanStackTo(), Duplicate(), Chara.GetHoverText2(), TraitTrolley.GetIdSound(), CardRenderer.GetPref(), HomeResourceWorth.ListHeirloom(), TraitFoodEggFertilized.MakeBaby(), TraitDrinkMilkMother.OnDrink(), and AM_MoveInstalled.SetTarget().
ignoreAutoPick
bool Card.ignoreAutoPick get set
Definition at line 477 of file Card.cs.
    {
        get
        {
            return _bits1[7];
        }
        set
        {
            _bits1[7] = value;
        }
    }
Referenced by ActPlan._Update().
ignoreStackHeight
bool Card.ignoreStackHeight get set
Definition at line 609 of file Card.cs.
    {
        get
        {
            return _bits1[18];
        }
        set
        {
            _bits1[18] = value;
        }
    }
Referenced by BaseTileMap.DrawTile(), BaseTileMap.GetThingPosition(), and AM_MoveInstalled.OnProcessTiles().
InspectName
string Card.InspectName get
Implements IInspect.
Definition at line 2381 of file Card.cs.
InspectPoint
Point Card.InspectPoint get
Implements IInspect.
Definition at line 2383 of file Card.cs.
InspectPosition
Vector3 Card.InspectPosition get
Implements IInspect.
Definition at line 2385 of file Card.cs.
INT
int Card.INT get
Definition at line 2249 of file Card.cs.
invX
int Card.invX get set
Definition at line 1842 of file Card.cs.
    {
        get
        {
            return pos.x;
        }
        set
        {
            pos.x = value;
        }
    }
Referenced by DragItemCard.DragInfo.DragInfo(), ItemPosition.Get(), ThingContainer.IsOccupied(), InvOwner.ListInteractions(), Game.OnLoad(), HotItemEQSet.Perform(), WidgetCurrentTool.RebuildSlots(), ThingContainer.RefreshGrid(), and ThingContainer.TryStack().
invY
int Card.invY get set
Definition at line 1854 of file Card.cs.
    {
        get
        {
            return pos.z;
        }
        set
        {
            pos.z = value;
        }
    }
Referenced by DragItemCard.DragInfo.DragInfo(), ThingContainer.IsOccupied(), ThingContainer.IsOverflowing(), InvOwner.ListInteractions(), Game.OnLoad(), ThingContainer.OnRemove(), HotItemEQSet.Perform(), Chara.PickHeld(), WidgetCurrentTool.RebuildSlots(), BuildMenu.RefreshCategory(), RemoveThing(), ButtonGrid.SetCard(), UIInventory.Sort(), and ThingContainer.TryStack().
isAcidproof
bool Card.isAcidproof get set
Definition at line 657 of file Card.cs.
    {
        get
        {
            return _bits1[22];
        }
        set
        {
            _bits1[22] = value;
        }
    }
Referenced by TraitDrink.CanBlend(), and Chara.TryUse().
IsAgent
bool Card.IsAgent get
Definition at line 2149 of file Card.cs.
Referenced by TaskMine.GetHitResult(), Stats.Mod(), TaskDig.OnProgressComplete(), TaskMine.OnProgressComplete(), and Map.TrySmoothPick().
IsAliveInCurrentZone
virtual bool Card.IsAliveInCurrentZone get
Definition at line 2027 of file Card.cs.
Referenced by ActMelee.Attack(), ActMelee.CanPerform(), ActRanged.CanPerform(), ActRestrain.CanPerform(), ActEffect.DamageEle(), Chara.HoldCard(), AI_Shear.IsValidTC(), ActMultihit.Perform(), ActRanged.Perform(), AI_PracticeDummy.Run(), AI_Shear.Run(), GoalSiege.Run(), and ActThrow.Throw().
IsAmmo
bool Card.IsAmmo get
Definition at line 2147 of file Card.cs.
Referenced by RecipeCard.Craft(), FactionBranch.DailyOutcome(), Chara.GiveGift(), ModEncLv(), ActEffect.Proc(), SetBlessedState(), Chara.ShouldThrowAway(), and Chara.TryPutSharedItems().
isBackerContent
bool Card.isBackerContent get
Definition at line 885 of file Card.cs.
Referenced by TraitSpecialLantern.OnCreate(), SerializedCards.Restore(), and Zone.Revive().
IsBlessed
bool Card.IsBlessed get
Definition at line 2153 of file Card.cs.
Referenced by TraitDrink.BlendLove(), TraitDrink.BlendPoison(), and TraitWell.OnBlend().
isBroken
bool Card.isBroken get set
Definition at line 705 of file Card.cs.
    {
        get
        {
            return _bits1[26];
        }
        set
        {
            _bits1[26] = value;
        }
    }
Referenced by TraitGenerator.ModHP(), TraitGenerator.OnSimulateHour(), and TraitGenerator.SetName().
isCensored
bool Card.isCensored get set
Definition at line 405 of file Card.cs.
    {
        get
        {
            return _bits1[1];
        }
        set
        {
            _bits1[1] = value;
        }
    }
Referenced by CardRenderer.OnEnterScreen().
isChara
virtual bool Card.isChara get
Definition at line 1983 of file Card.cs.
Referenced by SerializedCards.Add(), Props.Add(), Cell.AddCard(), Map.AddCardOnActivate(), InvOwner.AllowHold(), ApplyTrait(), ActMelee.Attack(), Trait.CanOffer(), ActKick.CanPerform(), ActNTR.CanPerform(), AM_MoveInstalled.CanPutAway(), Chara.CanSee(), InvOwner.CanShiftClick(), TraitSalesTag.CanTagSale(), AM_MoveInstalled.CheckEnemyNearBy(), LayerInventory.CreateContainer(), ActEffect.DamageEle(), DamageHP(), Chara.DoHostileAction(), CardRenderer.Draw(), CharaRenderer.DrawHeld(), GetBestAttribute(), ThingContainer.GetDest(), LayerInspect.GetItem(), Msg.GetName(), CardRow.GetName(), BaseTileMap.GetThingPosition(), HealHPHost(), ActMelee.HideHint(), AM_MoveInstalled.HitTest(), Chara.HoldCard(), Act.IsValidTC(), MakeRefFrom(), ModExp(), ElementContainer.ModExp(), Map.OnCardAddedToZone(), Map.OnCardRemovedFromZone(), InvOwner.OnClick(), CardRenderer.OnEnterScreen(), ElementContainerCard.OnLevelDown(), ElementContainerCard.OnLevelUp(), Props.OnNumChange(), AM_MoveInstalled.OnProcessTiles(), ItemGeneral.OnRefreshPref(), ActDreamBug.Perform(), Chara.PickHeld(), InvOwner.Transaction.Process(), Map.PutAway(), UIInventory.RefreshMenu(), Props.Remove(), Cell.RemoveCard(), Zone.RemoveCard(), RemoveThing(), SerializedCards.Restore(), SetLv(), CardRenderer.SetOwner(), PointTarget.ShouldIgnore(), ActThrow.Throw(), CardInspector.Traits(), Map.TryShatter(), CardRenderer.TrySpawnOrbit(), and RecipeCard.WriteNote().
IsContainer
bool Card.IsContainer get
Definition at line 1989 of file Card.cs.
Referenced by AddThing(), Chara.CanAcceptGift(), RecipeCard.Craft(), ThingGen.CreateTreasureContent(), ThingContainer.FindStealable(), ThingContainer.GetDest(), QuestDeliver.IsDestThing(), TraitWrench.IsValidTarget(), Trait.OnBarter(), ThingContainer.RefreshGridRecursive(), RemoveThing(), SerializedCards.Restore(), Chara.Revive(), ButtonGrid.SetCard(), SpawnLoot(), and Zone.TryAddThingInSpot< T >().
isCopy
bool Card.isCopy get set
Definition at line 849 of file Card.cs.
    {
        get
        {
            return _bits2[6];
        }
        set
        {
            _bits2[6] = value;
        }
    }
Referenced by TraitAltar.CanOffer(), Thing.CanStackTo(), EjectSockets(), Chara.GiveGift(), TaskHarvest.HarvestThing(), TraitBrewery.OnChildDecay(), AttackProcess.Perform(), and ActEffect.Proc().
isCrafted
bool Card.isCrafted get set
Definition at line 765 of file Card.cs.
    {
        get
        {
            return _bits1[31];
        }
        set
        {
            _bits1[31] = value;
        }
    }
Referenced by TraitKettle.CanCopy(), and Thing.CanStackTo().
IsCursed
bool Card.IsCursed get
Definition at line 2155 of file Card.cs.
Referenced by InvOwner.AllowHold(), TraitDrink.BlendLove(), TraitDrink.BlendPoison(), Chara.GiveGift(), and SpawnLoot().
IsDeadOrSleeping
virtual bool Card.IsDeadOrSleeping get
Definition at line 2009 of file Card.cs.
Referenced by CardRenderer.Draw().
IsDecayed
bool Card.IsDecayed get
Definition at line 2187 of file Card.cs.
Referenced by Chara.CanEat(), Thing.CanStackTo(), RecipeCard.Craft(), Religion.GetOfferingValue(), TaskHarvest.HarvestThing(), ButtonGrid.SetCard(), Chara.ShouldThrowAway(), and Zone.TryAddThingInSharedContainer().
isDeconstructing
bool Card.isDeconstructing get set
Definition at line 417 of file Card.cs.
    {
        get
        {
            return _bits1[2];
        }
        set
        {
            _bits1[2] = value;
        }
    }
Referenced by BaseTileMap.DrawTile(), TileMapElona.DrawTile(), AI_Deconstruct.IsValidTarget(), and InspectGroupThing.OnSetActions().
IsDisabled
virtual bool Card.IsDisabled get
Definition at line 2011 of file Card.cs.
isDyed
bool Card.isDyed get set
Definition at line 429 of file Card.cs.
    {
        get
        {
            return _bits1[3];
        }
        set
        {
            _bits1[3] = value;
        }
    }
Referenced by Thing.CanStackTo(), Recipe.GetColorMaterial(), Recipe.GetDefaultColor(), Game.OnLoad(), and ActionMode.UpdateInput().
isElemental
bool Card.isElemental get set
Definition at line 693 of file Card.cs.
    {
        get
        {
            return _bits1[25];
        }
        set
        {
            _bits1[25] = value;
        }
    }
IsEquipment
bool Card.IsEquipment get
Definition at line 2073 of file Card.cs.
Referenced by RecipeCard.Craft(), SourceElement.Row.IsMaterialEncAppliable(), TraitDrink.OnBlend(), InvOwner.OnStartDrag(), AI_Idle.Run(), InvOwnerReconstruction.ShouldShowGuide(), and SpawnLoot().
IsEquipmentOrRanged
bool Card.IsEquipmentOrRanged get
Definition at line 2117 of file Card.cs.
    {
        get
        {
            if (category.slot == 0)
            {
                return IsRangedWeapon;
            }
            return true;
        }
    }
Referenced by Chara.GiveGift(), SpawnLoot(), Chara.TryTakeSharedItems(), and Chara.TryUse().
IsEquipmentOrRangedOrAmmo
bool Card.IsEquipmentOrRangedOrAmmo get
Definition at line 2129 of file Card.cs.
    {
        get
        {
            if (category.slot == 0 && !IsRangedWeapon)
            {
                return IsAmmo;
            }
            return true;
        }
    }
Referenced by TraitDrink.CanBlend(), TaskHarvest.GetIdDismantled(), SourceElement.Row.IsMaterialEncAppliable(), ModEncLv(), LayerCraft.RefreshProduct(), SetBlessedState(), and ButtonGrid.SetCard().
isFireproof
bool Card.isFireproof get set
Definition at line 645 of file Card.cs.
    {
        get
        {
            return _bits1[21];
        }
        set
        {
            _bits1[21] = value;
        }
    }
isFloating
bool Card.isFloating get set
Definition at line 621 of file Card.cs.
    {
        get
        {
            return _bits1[19];
        }
        set
        {
            _bits1[19] = value;
        }
    }
Referenced by ActPlan._Update(), Cell.CanSuffocate(), Create(), BaseTileMap.DrawTile(), and Cell.GetSurfaceHeight().
IsFood
bool Card.IsFood get
Definition at line 2075 of file Card.cs.
Referenced by TraitDreamBug.CanBlend(), TraitDrink.CanBlend(), TaskHarvest.HarvestThing(), Trait.OnBarter(), TraitBrewery.OnChildDecay(), Chara.ShouldThrowAway(), and Map.TryShatter().
IsFresn
bool Card.IsFresn get
Definition at line 2191 of file Card.cs.
IsFurniture
bool Card.IsFurniture get
Definition at line 2151 of file Card.cs.
Referenced by Element.GetMaterialSourceValue(), HomeResourceWorth.ListHeirloom(), ActThrow.Throw(), and TraitEcoMark.TrySetHeldAct().
isGifted
bool Card.isGifted get set
Definition at line 753 of file Card.cs.
    {
        get
        {
            return _bits1[30];
        }
        set
        {
            _bits1[30] = value;
        }
    }
Referenced by InvOwner.AllowHold(), Thing.CanStackTo(), ZonePreEnterBoutWin.Execute(), AI_Idle.Run(), ButtonGrid.SetCard(), Chara.ShouldThrowAway(), and SpawnLoot().
IsGlobal
virtual bool Card.IsGlobal get
Definition at line 2183 of file Card.cs.
isHidden
bool Card.isHidden get set
Definition at line 501 of file Card.cs.
    {
        get
        {
            return _bits1[9];
        }
        set
        {
            _bits1[9] = value;
        }
    }
Referenced by TraitDoor.CanClose(), Chara.CanSee(), Chara.CanSeeLos(), Chara.FindNewEnemy(), Point.ListCards(), Point.ListThings< T >(), Point.ListVisibleCards(), Cell.Refresh(), TCOrbitChara.Refresh(), TCOrbitThing.Refresh(), SerializedCards.Restore(), GoalCombat.Run(), ActWait.SearchMedal(), PointTarget.ShouldIgnore(), Chara.ShowDialog(), and TaskHarvest.TryGetAct().
IsHotItem
bool Card.IsHotItem get
Definition at line 115 of file Card.cs.
Referenced by ActPlan._Update(), GoalAutoCombat.GetAbilities(), InvOwner.OnShiftClick(), Chara.PickHeld(), ThingContainer.ShouldShowOnGrid(), Chara.TryGetThrowable(), and GoalAutoCombat.TryUseRanged().
IsIdentified
bool Card.IsIdentified get
Definition at line 2277 of file Card.cs.
Referenced by ActItem.BuildAct(), ThingContainer.GetThingStack(), QuestDeliver.IsDestThing(), TraitAltar.OnOffer(), InvOwner.Transaction.Process(), ButtonGrid.SetCard(), ButtonElement.SetGrid(), Trait.SetMainText(), TraitBaseSpellbook.SetName(), InvOwnerIdentify.ShouldShowGuide(), and Chara.TryTakeSharedItems().
IsImportant
bool Card.IsImportant get
Definition at line 2005 of file Card.cs.
isImported
bool Card.isImported get set
Definition at line 585 of file Card.cs.
    {
        get
        {
            return _bits1[16];
        }
        set
        {
            _bits1[16] = value;
        }
    }
IsInheritFoodTraits
bool Card.IsInheritFoodTraits get
Definition at line 2077 of file Card.cs.
    {
        get
        {
            if (!IsFood && !category.IsChildOf("seed") && !category.IsChildOf("drink") && !(id == "pasture"))
            {
                return id == "grass";
            }
            return true;
        }
    }
IsInstalled
bool Card.IsInstalled get
Definition at line 2281 of file Card.cs.
Referenced by Chara._Move(), ActPlan._Update(), TraitHouseBoard.ApplyData(), FactionBranch.CalcInnIncome(), TraitTrolley.CanActivate(), Cell.CanSuffocate(), TraitSalesTag.CanTagSale(), QuestSharedContainer.CanUpdateOnTalk(), QuestShippingChest.CanUpdateOnTalk(), TraitGamble.CanUse(), TraitGeneMachine.CanUse(), TraitGeneratorWheel.CanUse(), TraitItem.CanUse(), TraitLoytelMart.CanUse(), TraitMoongate.CanUse(), TraitShackle.CanUse(), Chara.DestroyPath(), CardRenderer.Draw(), UIInspector.DrawHighlight(), BaseTileMap.DrawTile(), TileMapElona.DrawTile(), Zone.GetElectricity(), BaseArea.GetEmptySeat(), Point.GetInstalled< T >(), DramaCustomSequence.GetListGuide(), LayerInteraction.GetPage(), Zone.GetSpawnPos(), Cell.GetSurfaceHeight(), TraitGeneMachine.GetTarget(), BaseTileMap.GetThingPosition(), ActorEx.GetVolume(), Zone.GrowPlants(), Cell.HasZoneStairs(), Scene.Init(), TraitShackle.IsRestraining(), TaskDump.IsValidContainer(), TraitWrench.IsValidTarget(), HomeResourceWorth.ListHeirloom(), BaseArea.ListRoomNames(), Map.ListThing< T >(), Point.ListThings< T >(), InspectGroupThing.OnSetActions(), TraitClock.OnSimulateHour(), TraitFertilizer.OnSimulateHour(), TraitGenerator.OnSimulateHour(), TraitPhone.OnSimulateHour(), Zone.OnSimulateHour(), TraitNewZone.OnStepped(), ActRestrain.Perform(), BranchMap.Refresh(), Cell.Refresh(), TCOrbitThing.RefreshAll(), Zone.RefreshElectricity(), UIInventory.RefreshMenu(), SerializedCards.Restore(), AI_Idle.Run(), AI_Steal.Run(), RecipeUpdater.RunRecipe(), PartialMap.Save(), TraitGeneratorWheel.ShouldWork(), Zone.Simulate(), Chara.Stumble(), Zone.TryGetRestock< T >(), Zone.TryListThingsInSpot< T >(), AI_Idle.TryPerformIdleUse(), TraitCanvas.TrySetAct(), TraitCoreZone.TrySetAct(), TraitDoor.TrySetAct(), TraitFactionBoard.TrySetAct(), TraitPillowStrange.TrySetAct(), TraitRoomPlate.TrySetAct(), TraitTrainingDummy.TrySetAct(), TraitEcoMark.TrySetHeldAct(), TraitTicketFurniture.TrySetHeldAct(), TraitTeleporter.TryTeleport(), Trait.TryToggle(), and ActionMode.UpdateInput().
isLeashed
bool Card.isLeashed get set
Definition at line 813 of file Card.cs.
    {
        get
        {
            return _bits2[3];
        }
        set
        {
            _bits2[3] = value;
        }
    }
Referenced by Chara._Move().
IsLightsource
bool Card.IsLightsource get
Definition at line 2071 of file Card.cs.
isLostProperty
bool Card.isLostProperty get set
Definition at line 777 of file Card.cs.
    {
        get
        {
            return _bits2[0];
        }
        set
        {
            _bits2[0] = value;
        }
    }
Referenced by DramaCustomSequence.Build(), and Trait.TryOpenLock().
IsMale
bool Card.IsMale get
Definition at line 2283 of file Card.cs.
    {
        get
        {
            if (bio != null)
            {
                return bio.gender == 2;
            }
            return false;
        }
    }
Referenced by GameLang.Convert(), GameLang.ConvertDrama(), and Player.GetBackgroundText().
isMasked
bool Card.isMasked get set
Definition at line 561 of file Card.cs.
    {
        get
        {
            return _bits1[14];
        }
        set
        {
            _bits1[14] = value;
        }
    }
Referenced by TraitSalesTag.CanTagSale(), BaseTileMap.DrawTile(), AI_Haul.GetThingToClean(), Point.ListCards(), Point.ListThings< T >(), Point.ListVisibleCards(), AM_Visibility.OnProcessTiles(), SerializedCards.Restore(), PointTarget.ShouldIgnore(), TaskHarvest.TryGetAct(), and TraitTicketFurniture.TrySetHeldAct().
IsMeleeWeapon
bool Card.IsMeleeWeapon get
Definition at line 2141 of file Card.cs.
Referenced by CharaBody.GetAttackStyle(), Element.GetCost(), Chara.ShouldEquip(), and Chara.TryEquip().
IsMinion
virtual bool Card.IsMinion get
Definition at line 2051 of file Card.cs.
isModified
bool Card.isModified get set
Definition at line 441 of file Card.cs.
    {
        get
        {
            return _bits1[4];
        }
        set
        {
            _bits1[4] = value;
        }
    }
Referenced by Thing.CanStackTo(), and Mod().
IsMoving
virtual bool Card.IsMoving get
Definition at line 2013 of file Card.cs.
IsMultisize
virtual bool Card.IsMultisize get
Definition at line 2057 of file Card.cs.
    {
        get
        {
            if (sourceCard.multisize)
            {
                return IsInstalled;
            }
            return false;
        }
    }
Referenced by Map._AddCard(), Map._RemoveCard(), ActRestrain.CanPerform(), ActEffect.DamageEle(), Dist(), AI_Trolley.GetPoint(), ActRestrain.Perform(), and TaskDump.Run().
IsNegativeGift
bool Card.IsNegativeGift get
Definition at line 2295 of file Card.cs.
    {
        get
        {
            if (!HasTag(CTAG.neg))
            {
                return blessedState <= BlessedState.Cursed;
            }
            return true;
        }
    }
Referenced by Chara.CanEat(), ActThrow.Throw(), and Chara.TryUse().
isNew
bool Card.isNew get set
Definition at line 453 of file Card.cs.
    {
        get
        {
            return _bits1[5];
        }
        set
        {
            _bits1[5] = value;
        }
    }
Referenced by Create(), Chara.Pick(), and ButtonGrid.SetCard().
isNPCProperty
bool Card.isNPCProperty get set
Definition at line 525 of file Card.cs.
    {
        get
        {
            return _bits1[11];
        }
        set
        {
            _bits1[11] = value;
        }
    }
Referenced by HotItemNoItem._TrySetAct(), ActPlan._Update(), Zone.Activate(), InvOwner.AllowHold(), InvOwner.CanAltClick(), InvOwner.CanCtrlClick(), TraitScroll.CanRead(), InvOwner.CanShiftClick(), TraitFoodPreparedPackage.CanUse(), TraitItem.CanUse(), BaseTileMap.DrawTile(), TileMapElona.DrawTile(), Point.HasNonHomeProperty(), Chara.HoldCard(), AI_Steal.IsValidTC(), InvOwner.ListInteractions(), InvOwner.OnCancelDrag(), TaskHarvest.OnCreateProgress(), ConSleep.OnRemoved(), TraitPlamoBox.OnUse(), ZoneEventDefenseGame.OnVisit(), InvOwner.Transaction.Process(), UIInventory.RefreshMenu(), RecipeUpdater.RunRecipe(), ButtonGrid.SetCard(), Chara.ShouldThrowAway(), TraitElevator.TrySetAct(), TraitTeleporter.TrySetAct(), and TraitTicketFurniture.TrySetHeldAct().
isOn
bool Card.isOn get set
Definition at line 513 of file Card.cs.
    {
        get
        {
            return _bits1[10];
        }
        set
        {
            _bits1[10] = value;
        }
    }
Referenced by ThingContainer.AddFactory(), ApplyEditorTags(), TraitAncientbook.CanStackTo(), TraitGamble.CanUse(), TraitGeneMachine.CanUse(), TraitItem.CanUse(), TraitPowerStatue.CanUse(), TraitSlotMachine.CanUse(), ActorEx.GetVolume(), Trait.Install(), ThingContainer.IsFull(), TraitNewZone.MoveZone(), TraitSeesaw.OnActivateTrap(), AI_UseCrafter.OnEnd(), TraitJukeBox.OnSetBGM(), TraitSwing.OnSteppedOut(), TraitJukeBox.OnToggle(), TraitDaggerGrave.OnUse(), TraitFireworkLauncher.OnUse(), TraitMusicBox.OnUse(), TraitTerraGlobe.OnUse(), Trait.PlayToggleEffect(), Cell.Refresh(), UIMagicChest.RefreshBottom(), Zone.RefreshElectricity(), Trait.RefreshRenderer(), Trait.Refuel(), TraitDaggerGrave.RemainingSword(), AI_UseCrafter.Run(), RecipeUpdater.RunRecipe(), TraitBaseSpellbook.SetName(), ConSuspend.Tick(), Trait.Toggle(), TraitBaseSpellbook.TryProgress(), TraitGacha.TrySetAct(), TraitSalesTag.TrySetHeldAct(), Trait.TrySetToggleAct(), Trait.TryToggle(), and Trait.Uninstall().
IsPC
virtual bool Card.IsPC get
Definition at line 2043 of file Card.cs.
Referenced by InvOwnerIdentify._OnProcess(), AddExp(), AddThing(), InvOwner.AllowHold(), InvOwner.BuildUICurrency(), InvOwner.CanShiftClick(), ChangeMaterial(), ElementContainerCard.CheckSkillActions(), CardRenderer.Draw(), FindTool< T >(), ThingContainer.GetDest(), Msg.GetName(), Ability.GetPower(), InvOwner.GetShitDestOwner(), GetWindowSaveData(), Msg.IsThirdPerson(), InvOwner.Transaction.IsValid(), LevelUp(), InvOwner.ListInteractions(), InvOwner.OnClick(), DragItemCard.OnDragSpecial(), ElementContainerCard.OnLevelDown(), ElementContainerCard.OnLevelUp(), InvOwner.OnShiftClick(), TraitMannequin.OnUse(), ActDreamBug.Perform(), PlaySound(), ActEffect.Proc(), InvOwner.Transaction.Process(), Map.PutAway(), UIInventory.RefreshMenu(), RemoveThing(), AI_Slaughter.Run(), SetDirtyWeight(), PointTarget.ShouldIgnore(), ThingContainer.ShouldShowOnGrid(), ShouldTrySetDirtyInventory(), TryPay(), TraitContainer.TrySetAct(), ThingContainer.TryStack(), and Game.Wait().
IsPCC
virtual bool Card.IsPCC get
Definition at line 2047 of file Card.cs.
Referenced by CardRenderer.GetPref().
IsPCFaction
virtual bool Card.IsPCFaction get
Definition at line 2169 of file Card.cs.
Referenced by AddExp(), TaskCullLife.CanCull(), ActRestrain.CanPerform(), DamageHP(), Chara.GoHostile(), AI_Steal.IsValidTC(), MakeFoodFrom(), InvOwner.OnClick(), ElementContainerCard.OnLearn(), ElementContainerCard.OnModTempPotential(), ActRestrain.Perform(), ButtonRoster.Refresh(), PointTarget.ShouldIgnore(), and Map.TryShatter().
IsPCFactionMinion
virtual bool Card.IsPCFactionMinion get
Definition at line 2055 of file Card.cs.
Referenced by Chara.GoHostile().
IsPCFactionOrMinion
bool Card.IsPCFactionOrMinion get
Definition at line 2171 of file Card.cs.
    {
        get
        {
            if (!IsPCFaction)
            {
                return IsPCFactionMinion;
            }
            return true;
        }
    }
Referenced by ActPlan._Update(), ConStrife.AddKill(), ZoneEventQuest.AggroEnemy(), ActMelee.Attack(), Act.CanPerform(), Chara.CanReplace(), Ability.GetPower(), AttackProcess.GetWeaponEnc(), Chara.IsFriendOrAbove(), Chara.IsHostile(), Chara.Kick(), Region.ListMobs(), AI_Fish.Makefish(), Affinity.OnTalkRumor(), AttackProcess.Perform(), ActEffect.Proc(), Chara.RequestProtection(), Zone.ResetHostility(), AI_Fuck.Run(), AI_Idle.Run(), GoalCombat.Run(), Map.Save(), WidgetSearch.Search(), AI_PlayMusic.ThrowReward(), Chara.Tick(), ConChampagne.Tick(), Chara.TryPush(), GoalCombat.TryUseAbility(), ElementContainer.Value(), ElementContainerCard.ValueBonus(), and Element.BonusInfo.WriteNote().
IsPCParty
virtual bool Card.IsPCParty get
Definition at line 2049 of file Card.cs.
Referenced by ActEffect.DamageEle(), DamageHP(), ElementContainerCard.OnLevelUp(), ActEffect.Proc(), TCOrbitThing.RefreshAll(), AI_Slaughter.Run(), Map.TryShatter(), and ElementContainerCard.ValueBonus().
IsPCPartyMinion
virtual bool Card.IsPCPartyMinion get
Definition at line 2053 of file Card.cs.
isPlayerCreation
bool Card.isPlayerCreation get set
Definition at line 465 of file Card.cs.
    {
        get
        {
            return _bits1[6];
        }
        set
        {
            _bits1[6] = value;
        }
    }
Referenced by AM_EditMarker.HitTest(), Map.ResetEditorPos(), and Map.Save().
IsPowerful
bool Card.IsPowerful get
Definition at line 1993 of file Card.cs.
    {
        get
        {
            if (rarity >= Rarity.Legendary || trait is TraitAdventurer)
            {
                return !IsPCFaction;
            }
            return false;
        }
    }
Referenced by GoalCombat.Run(), and ConBurning.Tick().
IsRangedWeapon
bool Card.IsRangedWeapon get
Definition at line 2143 of file Card.cs.
Referenced by InvOwner.CanShiftClick(), Duplicate(), Chara.GetBestRangedWeapon(), ActEffect.Proc(), InvOwner.Transaction.Process(), AI_Steal.Run(), Chara.ShouldEquip(), Chara.ShouldThrowAway(), Chara.TryPutSharedItems(), and GoalAutoCombat.TryUseRanged().
isReplica
bool Card.isReplica get set
Definition at line 669 of file Card.cs.
    {
        get
        {
            return _bits1[23];
        }
        set
        {
            _bits1[23] = value;
        }
    }
Referenced by SetReplica(), and InvOwnerReconstruction.ShouldShowGuide().
isRestocking
bool Card.isRestocking get set
Definition at line 861 of file Card.cs.
    {
        get
        {
            return _bits2[7];
        }
        set
        {
            _bits2[7] = value;
        }
    }
Referenced by TCOrbitChara.RefreshAll(), and TCOrbitThing.RefreshAll().
isRestrained
bool Card.isRestrained get set
Definition at line 537 of file Card.cs.
    {
        get
        {
            return _bits1[12];
        }
        set
        {
            _bits1[12] = value;
        }
    }
Referenced by ActPlan._Update(), Chara.AddCondition(), Zone.AddGlobalCharasOnActivate(), ActRanged.CanPerform(), ActRestrain.CanPerform(), ActRush.CanPerform(), Chara.CanReplace(), QuestDefense.CanUpdateOnTalk(), TraitShackle.CanUse(), AI_Torture.CreateProgress(), BaseTileMap.DrawTile(), TraitShackle.IsRestraining(), Chara.Kick(), FactionBranch.OnAfterSimulate(), HotItemActionSleep.Perform(), AttackProcess.Perform(), Chara.RequestProtection(), SerializedCards.Restore(), AI_Idle.Run(), AI_Torture.Run(), GoalCombat.Run(), ConSleep.Tick(), and GoalCombat.TryUseAbility().
IsRestrainedResident
bool Card.IsRestrainedResident get
Definition at line 2157 of file Card.cs.
    {
        get
        {
            if (isRestrained)
            {
                return IsPCFaction;
            }
            return false;
        }
    }
Referenced by ActPlan._Update(), ActRanged.Perform(), AI_Idle.Run(), ActThrow.Throw(), and GoalCombat.TryUseAbility().
isRoofItem
bool Card.isRoofItem get set
Definition at line 549 of file Card.cs.
    {
        get
        {
            return _bits1[13];
        }
        set
        {
            _bits1[13] = value;
        }
    }
Referenced by TraitDoor.CanClose(), CardRenderer.Draw(), BaseTileMap.DrawTile(), Point.ListCards(), Point.ListThings< T >(), Point.ListVisibleCards(), AM_MoveInstalled.OnProcessTiles(), SetPlaceState(), and PointTarget.ShouldIgnore().
IsRotting
bool Card.IsRotting get
Definition at line 2189 of file Card.cs.
Referenced by ButtonGrid.SetCard().
isSale
bool Card.isSale get set
Definition at line 837 of file Card.cs.
    {
        get
        {
            return _bits2[5];
        }
        set
        {
            _bits2[5] = value;
        }
    }
Referenced by AI_Shopping.Buy(), TraitSalesTag.CanTagSale(), PropsManager.OnCardAddedToZone(), PropsManager.OnSetPlaceState(), RemoveThing(), AI_Shopping.Run(), Zone.TryGetRestock< T >(), and TraitSalesTag.TrySetHeldAct().
isStolen
bool Card.isStolen get set
Definition at line 825 of file Card.cs.
    {
        get
        {
            return _bits2[4];
        }
        set
        {
            _bits2[4] = value;
        }
    }
Referenced by TraitKettle.CanCopy(), Thing.CanStackTo(), and ShopTransaction.OnEndTransaction().
isSubsetCard
bool Card.isSubsetCard get set
Definition at line 717 of file Card.cs.
    {
        get
        {
            return _bits1[27];
        }
        set
        {
            _bits1[27] = value;
        }
    }
Referenced by Zone.UpdateQuests().
isSummon
bool Card.isSummon get set
Definition at line 681 of file Card.cs.
    {
        get
        {
            return _bits1[24];
        }
        set
        {
            _bits1[24] = value;
        }
    }
Referenced by Chara.CanReplace(), Destroy(), and BaseListPeople.OnList().
isSynced
virtual bool Card.isSynced get
Definition at line 1987 of file Card.cs.
Referenced by DamageHP(), PointTarget.ShouldIgnore(), ActThrow.Throw(), CoreDebug.UpdateInput(), and Game.Wait().
isThing
virtual bool Card.isThing get
Definition at line 1981 of file Card.cs.
Referenced by Map._AddCard(), _OnDeserialized(), HotItemNoItem._TrySetAct(), ActPlan._Update(), Zone.AddCard(), AddThing(), Recipe.Build(), RecipeCard.Build(), AI_Shopping.Buy(), ActRush.CanPerform(), TraitDye.CanUse(), ChangeMaterial(), DamageHP(), CardRenderer.Draw(), AI_Steal.IsValidTC(), PropsManager.OnCardAddedToZone(), OnChildNumChange(), AM_MoveInstalled.OnProcessTiles(), PropsManager.OnSetPlaceState(), ActEffect.Proc(), UIInventory.RefreshMenu(), Zone.RemoveCard(), AI_Steal.Run(), AI_TargetCard.Run(), RecipeUpdater.RunDisassemble(), Trait.SetMainText(), SetNum(), SetPlaceState(), AM_MoveInstalled.SetTarget(), and ActionMode.UpdateInput().
IsThrownWeapon
bool Card.IsThrownWeapon get
Definition at line 2145 of file Card.cs.
Referenced by SourceElement.Row.IsMaterialEncAppliable(), ActEffect.Proc(), AI_Steal.Run(), and Chara.ShouldThrowAway().
IsToolbelt
bool Card.IsToolbelt get
Definition at line 2069 of file Card.cs.
Referenced by ActEffect.Proc().
IsUnique
bool Card.IsUnique get
Definition at line 1991 of file Card.cs.
Referenced by FortuneRollData.Prize.AddNote(), AddThing(), GuildFighter.CanGiveContribution(), TraitSalesTag.CanTagSale(), Chara.DestroyPath(), Chara.Die(), FactionBranch.GenerateGarbage(), IsExcludeFromCraft(), Faction.IsWearingPanty(), MakeFoodFrom(), MaxRune(), TCOrbitChara.RefreshAll(), AI_Steal.Run(), InvOwnerChangeMaterial.ShouldShowGuide(), AI_PlayMusic.ThrowReward(), Chara.TryPush(), and TraitEcoMark.TrySetHeldAct().
IsVariation
bool Card.IsVariation get
Definition at line 2223 of file Card.cs.
IsWeapon
bool Card.IsWeapon get
Definition at line 2105 of file Card.cs.
    {
        get
        {
            if (!IsMeleeWeapon)
            {
                return IsRangedWeapon;
            }
            return true;
        }
    }
Referenced by AddRune(), CanAddRune(), ModEncLv(), ActEffect.Proc(), and SetBlessedState().
isWeightChanged
bool Card.isWeightChanged get set
Definition at line 633 of file Card.cs.
    {
        get
        {
            return _bits1[20];
        }
        set
        {
            _bits1[20] = value;
        }
    }
Referenced by Thing.CanStackTo(), and ChangeWeight().
LER
int Card.LER get
Definition at line 2241 of file Card.cs.
LightColor
Color Card.LightColor get
Definition at line 1068 of file Card.cs.
Referenced by ActPlan._Update().
LightData
LightData Card.LightData get
Definition at line 2329 of file Card.cs.
    {
        get
        {
            if (_LightData == null)
            {
                return _LightData = ((!sourceCard.lightData.IsEmpty()) ? EClass.Colors.lightColors[sourceCard.lightData] : null);
            }
            return _LightData;
        }
    }
Referenced by ActPlan._Update().
LUC
int Card.LUC get
Definition at line 2251 of file Card.cs.
LV
int Card.LV get set
Definition at line 369 of file Card.cs.
    {
        get
        {
            return _ints[25];
        }
        set
        {
            _ints[25] = value;
        }
    }
Referenced by TraitGodStatue._OnUse(), TraitShrine._OnUse(), SerializedCards.Add(), AddThing(), Feat.Apply(), RecipeCard.Build(), CalcMoney.BuySlave(), TraitMonsterBall.CanStackTo(), TraitRecipeCat.CanStackTo(), TraitCrafter.Craft(), Create(), Region.CreateRandomSite(), FactionBranch.DailyOutcome(), DamageHP(), Chara.Die(), Duplicate(), ZonePreEnterBout.Execute(), ZonePreEnterBoutWin.Execute(), DNA.GenerateGene(), DNA.GenerateManiGene(), TraitChara.GetAdvRank(), AI_Shear.GetFur(), Chara.GetHoverText(), Hobby.GetLv(), Religion.GetOfferingValue(), Ability.GetPower(), FactionBranch.GetResidentTax(), ActThrow.GetText(), GetTotalQuality(), TaskHarvest.HarvestThing(), LevelUp(), TraitSeed.MakeSeed(), TraitBlanket.OnCrafted(), TraitChestPractice.OnCreate(), TraitDrinkMilkMother.OnDrink(), QuestTaskHunt.OnKillChara(), TaskDig.OnProgressComplete(), TraitRecipeCat.OnRead(), TraitChestPractice.OnSimulateHour(), AttackProcess.Perform(), AttackProcess.Prepare(), ActEffect.Proc(), ActEffect.ProcAt(), CoreDebug.QuickStart(), WindowChara.RefreshNote(), WindowChara.RefreshProfile(), LayerQuestBoard.RefreshRanking(), Chara.RefreshSpeed(), CalcMoney.Revive(), AI_PlayMusic.Run(), AI_Steal.Run(), GoalCombat.Run(), TaskCullLife.Run(), CalcMoney.SellSlave(), SetLv(), TraitMonsterBall.SetName(), TraitRecipeCat.SetName(), ElementContainerCard.SetOwner(), GameDate.ShipRandomPackages(), ActThrow.Throw(), AI_PlayMusic.ThrowReward(), Chara.TickConditions(), and Chara.TryIdentify().
MAG
int Card.MAG get
Definition at line 2245 of file Card.cs.
material
SourceMaterial.Row Card.material get
Definition at line 1951 of file Card.cs.
Referenced by Chara._Move(), SerializedCards.Add(), ThingContainer.AddCurrency(), Element.AddEncNote(), ElementContainer.ApplyMaterialElementMap(), DropdownGrid.BuildIngredients(), TraitTrainingDummyArmor.CalcPV(), CanAddRune(), QuestShippingChest.CanUpdateOnTalk(), DNA.CopyDNA(), TraitCrafter.Craft(), DamageHP(), TraitDye.Dye(), ThingContainer.Find(), Recipe.GetColorMaterial(), ThingContainer.GetCurrency(), Recipe.GetDefaultColor(), TaskHarvest.GetIdDismantled(), DropdownRecipe.GetLabel(), TraitTile.GetRecipe(), GetTotalQuality(), Chara.GiveLovePotion(), TaskHarvest.HarvestThing(), AI_HaulResource.HoldingResource(), IsStackable(), Props.ListThingStack(), MakeFoodFrom(), TaskChopWood.OnCreateProgress(), TaskHarvest.OnCreateProgress(), TaskPlow.OnCreateProgress(), DragItemCard.OnDragSpecial(), TraitDye.OnThrowGround(), AttackProcess.Prepare(), ActEffect.Proc(), AI_Deconstruct.Run(), AI_Paint.Run(), AI_Shear.Run(), AI_Slaughter.Run(), LayerPixelPaint.SetCanvas(), CardActor.SetOwner(), BaseTaskHarvest.SetTarget(), SpawnLoot(), AM_Picker.TestThing(), Biography.TextBio2(), ActionMode.UpdateInput(), and CoreDebug.UpdateInput().
MaxDecay
virtual int Card.MaxDecay get
Definition at line 2185 of file Card.cs.
MaxHP
virtual int Card.MaxHP get
Definition at line 2193 of file Card.cs.
Referenced by Create(), DamageHP(), HealHP(), and SetLv().
Name
string Card.Name get
Definition at line 2037 of file Card.cs.
Referenced by InvOwnerRecycle._OnProcess(), BuildMenu._Search(), Party.AddMemeber(), DramaCustomSequence.Build(), MeetingManager.CallNext(), GameLang.ConvertDrama(), LayerInventory.CreateContainerAlly(), FactionBranch.DailyOutcome(), ActEffect.DamageEle(), Decay(), Chara.DropThing(), Expedition.End(), ZonePreEnterEncounter.Execute(), AI_Fuck.Finish(), Person.GetDramaTitle(), LayerInspect.GetItem(), Msg.GetName(), FactionBranch.GetResidentTax(), ActPlan.Item.GetTextContext(), TaskHarvest.GetTextSmall(), ShopTransaction.Log(), GlobalGoalVisitAndStay.OnAdvanceHour(), TraitWell.OnBlend(), TaskHarvest.OnCreateProgress(), UIInventory.OnInit(), ElementContainerCard.OnLevelUp(), Game.OnLoad(), TraitBaseSpellbook.OnRead(), ActZap.Perform(), ActEffect.Proc(), ShopTransaction.Process(), WidgetCurrentTool.RebuildSlots(), FactionBranch.Recruit(), LayerQuestBoard.RefreshHire(), UIInventory.RefreshList(), UIInventory.RefreshMenu(), UIHomeInfo.RefreshReport(), Chara.RefreshSpeed(), SerializedCards.Restore(), AI_Slaughter.Run(), GoalCombat.Run(), TraitDetector.Search(), WidgetSearch.Search(), ButtonGeneral.SetCard(), ButtonGrid.SetCard(), ItemGeneral.SetChara(), Person.SetChara(), ButtonChara.SetChara(), LayerDragGrid.SetInv(), TraitMonsterBall.SetName(), CardActor.SetOwner(), ItemPopulation.SetTopic(), UIFactionInfo.SetZone(), UIZoneInfo.SetZone(), GameDate.ShipGoods(), CoreDebug.Spawn(), ZoneEventQuest.SpawnBoss(), CoreDebug.SpawnBoss(), Expedition.Start(), WidgetInspector.SwitchPage(), ToString(), GoalCombat.TryMove(), TraitSalesTag.TrySetHeldAct(), TraitSyringeGene.TrySetHeldAct(), TraitSyringeHeaven.TrySetHeldAct(), TraitWrench.TrySetHeldAct(), Map.TryShatter(), GoalCombat.TryUseAbility(), HomeResourceWorth.WriteNote(), EloPos.WriteNote(), and TraitBookSkill.WriteNote().
NameOne
string Card.NameOne get
Definition at line 2041 of file Card.cs.
Referenced by BuildMenu._Search().
NameSimple
string Card.NameSimple get
Definition at line 2039 of file Card.cs.
Referenced by LittlePopper._OnAddStockpile(), GameLang.Convert(), GameLang.ConvertDrama(), CardRenderer.Draw(), UICharaMaker.EditName(), ZonePreEnterEncounter.Execute(), Player.GetBackgroundText(), DropdownRecipe.GetLabel(), BaseTaskHarvest.GetText(), QuestEscort.GetTextProgress(), Scene.Init(), BaseListPeople.OnClick(), LayerFeedback.OnInit(), LayerGacha.PlayGacha(), ButtonRoster.Refresh(), UICharaMaker.Refresh(), WindowCharaMini.Refresh(), WindowChara.RefreshProfile(), and LayerInfo.SetThing().
noMove
bool Card.noMove get set
Definition at line 741 of file Card.cs.
    {
        get
        {
            return _bits1[29];
        }
        set
        {
            _bits1[29] = value;
        }
    }
Referenced by Chara.CanReplace(), AI_Torture.CreateProgress(), Hobby.GetEfficiency(), Chara.Kick(), FactionBranch.OnAfterSimulate(), FactionBranch.OnSimulateHour(), UIHomeInfo.RefreshReport(), AI_Eat.Run(), AI_Idle.Run(), GoalIdle.Run(), ConSleep.Tick(), and Chara.TryPush().
noSell
bool Card.noSell get set
Definition at line 801 of file Card.cs.
    {
        get
        {
            return _bits2[2];
        }
        set
        {
            _bits2[2] = value;
        }
    }
Referenced by TraitKettle.CanCopy(), Thing.CanStackTo(), HomeResourceWorth.GetPrice(), and SetNoSell().
noShadow
bool Card.noShadow get set
Definition at line 789 of file Card.cs.
    {
        get
        {
            return _bits2[1];
        }
        set
        {
            _bits2[1] = value;
        }
    }
Referenced by BaseTileMap.DrawTile(), and AM_FlagCell.OnProcessTiles().
noSnow
bool Card.noSnow get set
Definition at line 729 of file Card.cs.
    {
        get
        {
            return _bits1[28];
        }
        set
        {
            _bits1[28] = value;
        }
    }
Referenced by ApplyEditorTags(), and CardRenderer.Draw().
Num
int Card.Num get set
Definition at line 153 of file Card.cs.
    {
        get
        {
            return _ints[6];
        }
        set
        {
            _ints[6] = value;
        }
    }
Referenced by LittlePopper._OnAddStockpile(), _OnDeserialized(), TraitAltar._OnOffer(), InvOwnerDeliver._OnProcess(), InvOwnerRefuel._OnProcess(), WidgetPopText._SayPick(), PropSet.Add(), ThingStack.Add(), ThingContainer.AddCurrency(), AddThing(), DropdownGrid.BuildIngredients(), InvOwner.CanCtrlClick(), QuestCraft.CanDeliverToClient(), ShopTransaction.CanSellBack(), Recipe.Ingredient.CanSetThing(), Thing.CanStackTo(), DramaOutcome.check_sketch(), Chara.ClearInventory(), ContentCodex.Collect(), RecipeCard.Craft(), Create(), FactionBranch.DailyOutcome(), HitSummary.Execute(), ZonePreEnterEncounter.Execute(), ThingContainer.GetCurrency(), DropdownRecipe.GetLabel(), Religion.GetOfferingValue(), TaskHarvest.HarvestThing(), Chara.HoldCard(), QuestDeliver.IsDestThing(), TaskCraft.IsIngredientsValid(), Msg.IsThirdPerson(), InvOwner.ListInteractions(), Props.ListThingStacksInCategory(), Map.Load(), ModNum(), Trait.OnBarter(), TraitBrewery.OnChildDecay(), TaskHarvest.OnCreateProgress(), InvOwner.OnDrag(), DragItemCard.OnDragSpecial(), AM_Build.OnFinishProcessTiles(), Game.OnLoad(), TraitAltar.OnOffer(), AI_Fish.ProgressFish.OnProgressComplete(), LayerGacha.PlayGacha(), ActEffect.Proc(), InvOwner.Transaction.Process(), UIInventory.RefreshList(), Trait.Refuel(), PropSet.Remove(), AI_Grab< T >.Run(), AI_HaulResource.Run(), AI_Idle.Run(), AI_OpenGambleChest.Run(), PartialMap.Save(), SecondaryCompare(), GridItemCard.SetButton(), ButtonGrid.SetIngredient(), Trait.SetMainText(), SetNum(), ButtonGrid.SetRecipe(), GameDate.ShipGoods(), Thing.ShowSplitMenu(), Thing.ShowSplitMenu2(), Split(), Chara.TryHoldCard(), GrowSystem.TryPick(), Chara.TryPoisonPotion(), LayerDragGrid.TryPutBack(), TraitCanvas.TrySetAct(), TraitToolTorch.TrySetHeldAct(), TryStackTo(), Chara.TryTakeSharedItems(), TraitFoodEgg.Update(), and Props.Validate().
parentCard
Card Card.parentCard get
Definition at line 99 of file Card.cs.
Referenced by ItemPosition.Get(), QuestDeliver.IsDestThing(), InvOwner.ListInteractions(), HotItemEQSet.Perform(), ActEffect.Proc(), UIDragGridIngredients.Refresh(), BuildMenu.RefreshCategory(), Chara.Revive(), TraitContainer.TrySetAct(), and Map.TryShatter().
parentThing
Thing Card.parentThing get
Definition at line 101 of file Card.cs.
PER
int Card.PER get
Definition at line 2239 of file Card.cs.
posInvX
int Card.posInvX get set
Definition at line 321 of file Card.cs.
    {
        get
        {
            return _ints[21];
        }
        set
        {
            _ints[21] = value;
        }
    }
Referenced by UIInventory.RefreshGrid(), and Thing.ShowSplitMenu().
posInvY
int Card.posInvY get set
Definition at line 333 of file Card.cs.
    {
        get
        {
            return _ints[22];
        }
        set
        {
            _ints[22] = value;
        }
    }
Referenced by UIInventory.RefreshGrid(), and Thing.ShowSplitMenu().
Power
virtual int Card.Power get
Definition at line 2195 of file Card.cs.
Referenced by TraitItemProc.OnUse(), and AttackProcess.Perform().
Pref
virtual SourcePref Card.Pref get
Definition at line 2007 of file Card.cs.
Referenced by Create(), CharaRenderer.Draw(), CharaRenderer.DrawHeld(), BaseTileMap.DrawTile(), CardRenderer.GetPref(), BaseTileMap.GetThingPosition(), and SourcePrefInspector.OnValidate().
PrefIndex
virtual int Card.PrefIndex get
Definition at line 2211 of file Card.cs.
    {
        get
        {
            if (Tiles.Length < 3)
            {
                return dir % 2;
            }
            return dir;
        }
    }
Referenced by CardRenderer.Draw().
PV
virtual int Card.PV get
Definition at line 2227 of file Card.cs.
Referenced by ApplyProtection(), and Thing.GetName().
Quality
int Card.Quality get
Definition at line 2325 of file Card.cs.
Referenced by GetTotalQuality().
QualityLv
int Card.QualityLv get
Definition at line 2327 of file Card.cs.
Referenced by TraitBlanket.OnCreate().
rarity
Rarity Card.rarity get set
Definition at line 297 of file Card.cs.
    {
        get
        {
            return (_ints[19] / 100).ToEnum<Rarity>();
        }
        set
        {
            _ints[19] = (int)value * 100;
        }
    }
Referenced by Chara.CanAcceptGift(), GuildFighter.CanGiveContribution(), Trait.CanOffer(), ChangeRarity(), Create(), Zone.Deactivate(), ZonePreEnterBoutWin.Execute(), Chara.GiveGift(), TraitRuneMold.IsIngredient(), CardRenderer.RefreshExtra(), AI_Steal.Run(), AI_Trolley.Run(), ButtonGrid.SetCard(), InvOwnerRecycle.ShouldShowGuide(), Chara.ShouldThrowAway(), Zone.Simulate(), and SpawnLoot().
rarityLv
int Card.rarityLv get set
Definition at line 285 of file Card.cs.
    {
        get
        {
            return _ints[19];
        }
        set
        {
            _ints[19] = value;
        }
    }
Referenced by Thing.CanStackTo(), and Duplicate().
refCard
CardRow Card.refCard get
Definition at line 1866 of file Card.cs.
    {
        get
        {
            object obj;
            if (!c_idRefCard.IsEmpty())
            {
                obj = EClass.sources.cards.map.TryGetValue(c_idRefCard);
                if (obj == null)
                {
                    return EClass.sources.cards.map["ash3"];
                }
            }
            else
            {
                obj = null;
            }
            return (CardRow)obj;
        }
    }
Referenced by Religion.GetOfferingValue(), AI_Eat.Run(), and TryGetFoodName().
refCard2
CardRow Card.refCard2 get
Definition at line 1887 of file Card.cs.
    {
        get
        {
            object obj;
            if (!c_idRefCard2.IsEmpty())
            {
                obj = EClass.sources.cards.map.TryGetValue(c_idRefCard2);
                if (obj == null)
                {
                    return EClass.sources.cards.map["ash3"];
                }
            }
            else
            {
                obj = null;
            }
            return (CardRow)obj;
        }
    }
refVal
int Card.refVal get set
Definition at line 189 of file Card.cs.
    {
        get
        {
            return _ints[11];
        }
        set
        {
            _ints[11] = value;
        }
    }
Referenced by SerializedCards.Add(), AddRune(), Thing.CanStackTo(), TraitEffect.CompareTo(), Duplicate(), GrowSystem.EqualizePlants(), TraitScrollMapTreasure.GetDest(), TraitPotionRandom.GetName(), ThingContainer.GetThingStack(), TaskDig.OnProgressComplete(), TraitBaseSpellbook.OnRead(), TraitJukeBox.OnToggle(), TraitGachaBall.OnUse(), TraitScrollMapTreasure.OnUse(), TraitTape.OnUse(), SecondaryCompare(), TraitAmmoTalisman.SetName(), TraitBaseSpellbook.SetName(), TraitTape.SetName(), ActorEx.SetOwner(), TraitFigure.TrySetAct(), and TraitPaintBoard.TrySetAct().
SelfWeight
virtual int Card.SelfWeight get
Definition at line 1945 of file Card.cs.
Referenced by AI_Eat.Run().
ShouldShowMsg
bool Card.ShouldShowMsg get
Definition at line 2353 of file Card.cs.
    {
        get
        {
            if (IsPC || parent == EClass.pc || isSynced)
            {
                if (isChara)
                {
                    return !Chara.isDead;
                }
                return true;
            }
            return false;
        }
    }
Referenced by StatsMana.Mod(), StatsStamina.Mod(), Stats.OnChangePhase(), and BaseStats.PopText().
ShowFoodEnc
bool Card.ShowFoodEnc get
Definition at line 2089 of file Card.cs.
    {
        get
        {
            if (!IsInheritFoodTraits)
            {
                if (Evalue(10) > 0)
                {
                    return !IsEquipmentOrRangedOrAmmo;
                }
                return false;
            }
            return true;
        }
    }
Referenced by Element.AddEncNote(), and Element.SortVal().
socketList
List<SocketData> Card.socketList get set
Definition at line 1720 of file Card.cs.
    {
        get
        {
            return GetObj<List<SocketData>>(17);
        }
        set
        {
            SetObj(17, value);
        }
    }
Referenced by AddRune(), CountRune(), and GetRuneEnc().
sourceBacker
SourceBacker.Row Card.sourceBacker get
Definition at line 887 of file Card.cs.
    {
        get
        {
            if (!isBackerContent)
            {
                return null;
            }
            return EClass.sources.backers.map.TryGetValue(c_idBacker);
        }
    }
sourceCard
virtual CardRow Card.sourceCard get
Definition at line 2031 of file Card.cs.
Referenced by TileType._HitTest(), SerializedCards.Add(), Cell.AddCard(), ApplyTrait(), ChangeMaterial(), Trait.Contains(), Create(), CardRenderer.Draw(), CharaRenderer.DrawHeld(), GetDetail(), Trait.GetName(), TraitGene.GetName(), CardRenderer.GetPref(), Trait.GetSortVal(), BaseTileMap.GetThingPosition(), Trait.GetValue(), HasTag(), TraitTrap.IgnoreWhenLevitating(), CraftUtil.MakeDish(), TraitTrap.OnActivateTrap(), CardRenderer.OnEnterScreen(), TraitEQFlower.OnEquip(), CardActor.OnRender(), CardRenderer.RefreshExtra(), Cell.RemoveCard(), SerializedCards.Restore(), CardRenderer.SetOwner(), and ElementContainerCard.SetOwner().
sourceRenderCard
virtual CardRow Card.sourceRenderCard get
Definition at line 2033 of file Card.cs.
Referenced by TraitNewZone.CanAutoEnter(), ItemGeneral.GetRenderRow(), and TraitNewZone.TrySetAct().
STR
int Card.STR get
Definition at line 2233 of file Card.cs.
Referenced by AttackProcess.Prepare(), and AI_Steal.Run().
TextRarity
string Card.TextRarity get
Definition at line 2279 of file Card.cs.
Thing
virtual Thing Card.Thing get
Definition at line 1957 of file Card.cs.
    {
        get
        {
            if (!isThing)
            {
                return null;
            }
            return (Thing)this;
        }
    }
Referenced by InvOwnerMod._OnProcess(), ActPlan._Update(), Add(), Cell.AddCard(), Element.AddEncNote(), AI_Shopping.Buy(), InvOwner.CanAltClick(), Chara.CanPick(), InvOwner.CanShiftClick(), TraitDye.CanUse(), TraitCrafter.Craft(), RecipeCard.Craft(), TraitCatalyst.CreateAct(), LayerInventory.CreateContainer(), LayerInventory.CreateContainerAlly(), LayerInventory.CreateContainerPC(), DragItemCard.DragInfo.DragInfo(), Chara.DropHeld(), Trait.GetBuildModeRecipe(), TraitTile.GetBuildModeRecipe(), CoreDebug.GetOrCreateDebugContainer(), Trait.GetRecipe(), InvOwner.GetShitDestOwner(), Chara.HoldCard(), InvOwner.ListInteractions(), Props.ListThingStack(), CraftUtil.MixIngredients(), InvOwner.OnAltClick(), Trait.OnBarter(), Map.OnCardAddedToZone(), Map.OnCardRemovedFromZone(), TraitBrewery.OnChildDecay(), OnChildNumChange(), InvOwner.OnClick(), TraitSeed.OnCreate(), InvOwner.OnCtrlClick(), TraitDrink.OnDrink(), Affinity.OnGift(), Props.OnNumChange(), TraitBaseSpellbook.OnRead(), TraitContainer.OnSetCardGrid(), AI_Read.OnSetOwner(), InvOwner.OnShiftClick(), GoalSleep.OnSimulatePosition(), TraitAmmo.OnUse(), TraitCrafter.OnUse(), TraitEquipItem.OnUse(), TraitFoodPreparedPackage.OnUse(), TraitContainer.Open(), ActZap.Perform(), Chara.Pick(), Chara.PickHeld(), TraitChest.Prespawn(), TraitChestOyster.Prespawn(), ActEffect.Proc(), Map.PutAway(), Cell.RemoveCard(), SerializedCards.Restore(), AI_Eat.Run(), AI_GotoHearth.Run(), AI_Idle.Run(), AI_Steal.Run(), GoalSleep.Run(), RecipeUpdater.RunDisassemble(), Trait.SetMainText(), TraitBaseContainer.SetName(), SetNoSell(), SetNum(), Thing.ShowSplitMenu(), SpawnLoot(), Split(), Zone.TryAddThingInSpot< T >(), TraitCanvas.TrySetAct(), TraitCrafter.TrySetAct(), TraitSeed.TrySprout(), TraitFoodEgg.Update(), and UIDragGridIngredients.Update().
tier
int Card.tier get set
Definition at line 393 of file Card.cs.
    {
        get
        {
            return _ints[27];
        }
        set
        {
            _ints[27] = value;
        }
    }
Referenced by Thing.CanStackTo(), Create(), Duplicate(), AI_Fish.ProgressFish.OnProgressComplete(), ButtonGrid.SetCard(), and SetTier().
Tiles
virtual int [] Card.Tiles get
Definition at line 2209 of file Card.cs.
TileType
TileType Card.TileType get
Definition at line 2035 of file Card.cs.
Referenced by TileType._HitTest(), HotItemNoItem._TrySetAct(), TraitDoor.CanClose(), CardRenderer.Draw(), UIInspector.DrawHighlight(), BaseTileMap.DrawTile(), TileMapElona.DrawTile(), TaskBuild.GetHitResult(), TaskMoveInstalled.GetHitResult(), BaseTileMap.GetThingPosition(), GenRoom.Populate(), and BiomeProfile.ClusterThing.TryCreate().
Tool
Thing Card.Tool get
Definition at line 2309 of file Card.cs.
    {
        get
        {
            if (!IsPC)
            {
                return null;
            }
            return EClass.player.currentHotItem.Thing;
        }
    }
Referenced by TaskChopWood.CanProgress(), FindTool< T >(), BaseTaskHarvest.GetText(), TaskChopWood.OnCreateProgress(), TaskDig.OnCreateProgress(), TaskDrawWater.OnCreateProgress(), TaskHarvest.OnCreateProgress(), TaskMine.OnCreateProgress(), TaskPlow.OnCreateProgress(), TaskPourWater.OnCreateProgress(), AI_Fish.ProgressFish.OnProgress(), AI_Fish.ProgressFish.OnStart(), AI_Shear.Run(), AI_Slaughter.Run(), BaseTaskHarvest.SetTarget(), and TaskHarvest.TryGetAct().
uid
int Card.uid get set
Definition at line 117 of file Card.cs.
    {
        get
        {
            return _ints[1];
        }
        set
        {
            _ints[1] = value;
        }
    }
Referenced by CardManager.GlobalCharaList.Add(), CharaList.Add(), FactionBranch.AddMemeber(), Party.AddMemeber(), Faction.AddReserve(), ElementContainer.ApplyMaterialElementMap(), Recipe.BuildIngredientList(), DropdownGrid.BuildIngredients(), CalcMoney.BuySlave(), QuestDeliver.CanDeliverToClient(), Expedition.Create(), Recipe.Create(), QuestInstance.CreateInstanceZone(), CardRenderer.Draw(), ZonePreEnterOnCompleteQuestInstance.Execute(), CardManager.GlobalCharaList.Find(), CardManager.Find(), Props.Find(), ThingContainer.Find(), Map.FindChara(), Zone.FindChara(), Map.FindThing(), ItemPosition.Get(), RefChara.GetAndCache(), GoalGraze.GetPos(), Portrait.GetRandomHairColor(), RelationManager.GetRelation(), TraitGeneMachine.GetTarget(), TeleportManager.GetTeleportZone(), GuildFighter.HasBounty(), TraitBed.IsHolder(), TraitShackle.IsRestraining(), UICharaMaker.ListJob(), UICharaMaker.ListRace(), Chara.MakeMinion(), TraitTeleporter.OnChangePlaceState(), BaseListPeople.OnClick(), ListPeopleExpedition.OnClick(), Player.OnCreateGame(), QuestDeliver.OnEnterZone(), ZoneEventSiege.OnFirstTick(), Game.OnGameInstantiated(), ListPeopleExpedition.OnList(), ConSleep.OnRemoved(), Chara.OnSerializing(), QuestEscort.OnStart(), TraitGeneMachine.OnUse(), HotItemEQSet.Perform(), ReferenceId(), ItemQuestTracker.Refresh(), HotItemEQSet.Register(), CardManager.GlobalCharaList.Remove(), CharaList.Remove(), Party.RemoveMember(), Faction.RemoveReserve(), Party.Replace(), SerializedCards.Restore(), TraitShackle.Restrain(), Recipe.SaveLastIngredients(), SecondaryCompare(), RefChara.Set(), ItemGeneral.SetChara(), Person.SetChara(), TeleportManager.SetID(), SetLv(), ElementContainerCard.SetOwner(), ListPeopleExpedition.SetSubText(), ZoneEventQuest.Spawn(), ZoneEventQuest.SpawnBoss(), Msg.TalkMaid(), ActThrow.Throw(), ConSleep.Tick(), and Thing.TryLickEnchant().
visitorState
VisitorState Card.visitorState get set
Definition at line 1156 of file Card.cs.
    {
        get
        {
            return GetInt(4).ToEnum<VisitorState>();
        }
        set
        {
            SetInt(4, (int)value);
        }
    }
W
int Card.W get
Definition at line 2253 of file Card.cs.
    {
        get
        {
            if (dir % 2 != 0)
            {
                return sourceCard.H;
            }
            return sourceCard.W;
        }
    }
Referenced by HitSummary.CanExecute(), TraitBoat.ForeachDeck(), TaskMoveInstalled.Run(), and TraitNewZone.TrySetAct().
WeightLimit
virtual int Card.WeightLimit get
Definition at line 1947 of file Card.cs.
Referenced by UICurrency.Build().
WIL
int Card.WIL get
Definition at line 2243 of file Card.cs.
Referenced by AttackProcess.Prepare().
The documentation for this class was generated from the following file:
Elin/Card.cs