Elin Decompiled Documentation: Weather Class Reference
Weather Class Reference
Classes
class Forecast
class WeatherForecast
Public Types
enum Condition {
Fine , Cloudy , Rain , RainHeavy ,
Snow , SnowHeavy , Ether , Blossom ,
None
}
Public Member Functions
string GetName ()
string GetName (Condition condition)
void RefreshWeather ()
void OnChangeHour ()
Forecast GetForecast (Date date, Condition current)
List< WeatherForecast > GetWeatherForecast ()
void RefreshForecasts ()
long GetTimeSinceLastRain ()
void SetRandomCondition ()
void SetConditionFromForecast (bool silent=false)
void SetCondition (Condition condition, int _duration=20, bool silent=false)
Public Attributes
Condition _currentCondition
int duration = 8
int lastRain
List< Forecast > forecasts = new List<Forecast>()
Properties
Condition CurrentCondition [get]
Season season [get]
bool IsHazard [get]
bool IsFineOrCloudy [get]
bool IsRaining [get]
bool IsSnowing [get]
bool IsBlossom [get]
bool IsEther [get]
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Static Private Attributes
const int maxForecasts = 10
Additional Inherited Members
Static Public Member Functions inherited from EClass
static int rndSeed (int a, int seed)
static int rnd (long a)
static int rnd (int a)
static int curve (int a, int start, int step, int rate=75)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Static Public Attributes inherited from EClass
static Core core
Detailed Description
Definition at line 5 of file Weather.cs.
Member Enumeration Documentation
Condition
enum Weather.Condition
Enumerator
Fine
Cloudy
Rain
RainHeavy
Snow
SnowHeavy
Ether
Blossom
None
Definition at line 15 of file Weather.cs.
    {
        Fine,
        Cloudy,
        Rain,
        RainHeavy,
        Snow,
        SnowHeavy,
        Ether,
        Blossom,
        None
    }
Member Function Documentation
GetForecast()
Forecast Weather.GetForecast (Date date, Condition current) inline
Definition at line 206 of file Weather.cs.
    {
        Forecast forecast = new Forecast();
        forecast.condition = ((EClass.rnd(4) == 0) ? season.GetRandomWeather(date, current) : Condition.Fine);
        forecast.duration = EClass.rnd(24) + 10;
        date.AddHour(forecast.duration);
        return forecast;
    }
References Date.AddHour(), Weather.Forecast.duration, Season.GetRandomWeather(), EClass.rnd(), and season.
Referenced by RefreshForecasts().
GetName() [1/2]
string Weather.GetName () inline
Definition at line 158 of file Weather.cs.
    {
        return GetName(CurrentCondition);
    }
References CurrentCondition, and GetName().
Referenced by WidgetDate._Refresh(), and GetName().
GetName() [2/2]
string Weather.GetName (Condition condition) inline
Definition at line 163 of file Weather.cs.
    {
        return ("weather" + condition).lang();
    }
GetTimeSinceLastRain()
long Weather.GetTimeSinceLastRain () inline
Definition at line 286 of file Weather.cs.
    {
        if (CurrentCondition == Condition.Rain || CurrentCondition == Condition.RainHeavy)
        {
            return 0L;
        }
        return EClass.world.date.GetElapsedMins(lastRain);
    }
References CurrentCondition, World.date, Date.GetElapsedMins(), lastRain, and EClass.world.
GetWeatherForecast()
List< WeatherForecast > Weather.GetWeatherForecast () inline
Definition at line 215 of file Weather.cs.
    {
        RefreshForecasts();
        List<WeatherForecast> list = new List<WeatherForecast>();
        Date date = EClass.world.date.Copy();
        WeatherForecast weatherForecast = new WeatherForecast
        {
            date = date.Copy()
        };
        list.Add(weatherForecast);
        Forecast forecast = new Forecast
        {
            condition = _currentCondition,
            duration = duration
        };
        int num = forecast.duration;
        int num2 = -1;
        for (int i = 0; i < 10000; i++)
        {
            num--;
            weatherForecast.Add(forecast.condition, 1);
            if (num < 0)
            {
                num2++;
                if (forecasts.Count <= num2)
                {
                    list.Remove(weatherForecast);
                    break;
                }
                forecast = forecasts[num2];
                num = forecast.duration;
            }
            date.AddHour(1);
            if (date.day != weatherForecast.date.day)
            {
                weatherForecast.Finish();
                weatherForecast = new WeatherForecast
                {
                    date = date.Copy()
                };
                list.Add(weatherForecast);
            }
        }
        return list;
    }
References _currentCondition, Weather.WeatherForecast.Add(), Date.AddHour(), Weather.Forecast.condition, Date.Copy(), Weather.WeatherForecast.date, World.date, Date.day, Weather.Forecast.duration, duration, Weather.WeatherForecast.Finish(), forecasts, RefreshForecasts(), and EClass.world.
Referenced by LayerNewspaper.RefreshWeather().
OnChangeHour()
void Weather.OnChangeHour () inline
Definition at line 197 of file Weather.cs.
    {
        duration--;
        if (duration < 0)
        {
            SetConditionFromForecast();
        }
    }
References duration, and SetConditionFromForecast().
Referenced by GameDate.AdvanceHour().
RefreshForecasts()
void Weather.RefreshForecasts () inline
Definition at line 261 of file Weather.cs.
    {
        if (forecasts.Count >= 10)
        {
            return;
        }
        Date date = EClass.world.date.Copy();
        Condition current = Condition.Fine;
        for (int i = 0; i < 10; i++)
        {
            if (forecasts.Count > i)
            {
                Forecast forecast = forecasts[i];
                date.AddHour(forecast.duration);
                current = forecast.condition;
            }
            else
            {
                Forecast forecast2 = GetForecast(date, current);
                forecasts.Add(forecast2);
                current = forecast2.condition;
            }
        }
    }
References Date.AddHour(), Weather.Forecast.condition, Date.Copy(), World.date, Weather.Forecast.duration, forecasts, GetForecast(), and EClass.world.
Referenced by GetWeatherForecast(), and SetConditionFromForecast().
RefreshWeather()
void Weather.RefreshWeather () inline
Definition at line 168 of file Weather.cs.
    {
        if (EClass._map.IsIndoor)
        {
            return;
        }
        bool flag = EClass._zone.IsSnowCovered;
        if (EClass._zone is Region)
        {
            EloMap elomap = EClass.scene.elomapActor.elomap;
            flag = elomap.GetTileInfo(EClass.pc.pos.x + elomap.minX, EClass.pc.pos.z + elomap.minY)?.IsSnow ?? false;
            if (EClass.world.season.isWinter)
            {
                flag = true;
            }
        }
        if (IsSnowing)
        {
            if (!flag)
            {
                _currentCondition = ((_currentCondition == Condition.Snow) ? Condition.Rain : Condition.RainHeavy);
            }
        }
        else if (IsRaining && flag)
        {
            _currentCondition = ((_currentCondition == Condition.Rain) ? Condition.Snow : Condition.SnowHeavy);
        }
    }
References _currentCondition, EClass._map, EClass._zone, EloMapActor.elomap, Scene.elomapActor, EloMap.GetTileInfo(), Map.IsIndoor, IsRaining, EloMap.TileInfo.IsSnow, Spatial.IsSnowCovered, IsSnowing, Season.isWinter, EloMap.minX, EloMap.minY, EClass.pc, Card.pos, EClass.scene, World.season, EClass.world, Point.x, and Point.z.
Referenced by Scene.Init(), GameScreenElona.RefreshWeather(), and SetCondition().
SetCondition()
void Weather.SetCondition (Condition condition, int _duration = 20, bool silent = false) inline
Definition at line 308 of file Weather.cs.
    {
        if (condition == Condition.Fine)
        {
            foreach (Chara member in EClass.pc.party.members)
            {
                if (member.HasElement(1558) && EClass.rnd(4) == 0)
                {
                    condition = Condition.Rain;
                    Msg.Say("drawRain", member);
                    break;
                }
            }
        }
        if (EClass.world.season.isWinter)
        {
            switch (condition)
            {
            case Condition.Rain:
                condition = Condition.Snow;
                break;
            case Condition.RainHeavy:
                condition = Condition.SnowHeavy;
                break;
            }
        }
        else if (!EClass._zone.IsSnowZone && !EClass._map.IsIndoor)
        {
            switch (condition)
            {
            case Condition.Snow:
                condition = Condition.Rain;
                break;
            case Condition.SnowHeavy:
                condition = Condition.RainHeavy;
                break;
            }
        }
        if (_currentCondition == Condition.Rain || _currentCondition == Condition.RainHeavy)
        {
            lastRain = EClass.world.date.GetRaw();
        }
        duration = _duration;
        if (condition != _currentCondition)
        {
            _currentCondition = condition;
            RefreshWeather();
            Msg.Say("weather_" + condition);
            if (IsRaining)
            {
                EClass._zone.RainWater();
            }
            EClass.core.screen.RefreshSky();
        }
    }
References _currentCondition, EClass._map, EClass._zone, EClass.core, World.date, duration, Date.GetRaw(), Card.HasElement(), Map.IsIndoor, IsRaining, Spatial.IsSnowZone, Season.isWinter, lastRain, Party.members, Chara.party, EClass.pc, Zone.RainWater(), BaseGameScreen.RefreshSky(), RefreshWeather(), EClass.rnd(), Msg.Say(), Core.screen, World.season, and EClass.world.
Referenced by World.ModEther(), WidgetArtTool.OnActivate(), SetConditionFromForecast(), SetRandomCondition(), and CoreDebug.UpdateInput().
SetConditionFromForecast()
void Weather.SetConditionFromForecast (bool silent = false) inline
Definition at line 300 of file Weather.cs.
    {
        RefreshForecasts();
        Forecast forecast = forecasts[0];
        SetCondition(forecast.condition, forecast.duration, silent);
        forecasts.RemoveAt(0);
    }
References Weather.Forecast.condition, Weather.Forecast.duration, forecasts, RefreshForecasts(), and SetCondition().
Referenced by OnChangeHour().
SetRandomCondition()
void Weather.SetRandomCondition () inline
Definition at line 295 of file Weather.cs.
    {
        SetCondition(Util.RandomEnum<Condition>());
    }
References SetCondition(), and Util.
Member Data Documentation
_currentCondition
Condition Weather._currentCondition
Definition at line 67 of file Weather.cs.
Referenced by GetWeatherForecast(), RefreshWeather(), and SetCondition().
duration
int Weather.duration = 8
Definition at line 70 of file Weather.cs.
Referenced by GetWeatherForecast(), OnChangeHour(), and SetCondition().
forecasts
List<Forecast> Weather.forecasts = new List<Forecast>()
Definition at line 76 of file Weather.cs.
Referenced by GetWeatherForecast(), RefreshForecasts(), and SetConditionFromForecast().
lastRain
int Weather.lastRain
Definition at line 73 of file Weather.cs.
Referenced by GetTimeSinceLastRain(), and SetCondition().
maxForecasts
const int Weather.maxForecasts = 10 static private
Definition at line 64 of file Weather.cs.
Property Documentation
CurrentCondition
Condition Weather.CurrentCondition get
Definition at line 78 of file Weather.cs.
    {
        get
        {
            if (EClass._map.config.fixedCondition == Condition.None)
            {
                return _currentCondition;
            }
            return EClass._map.config.fixedCondition;
        }
    }
Referenced by Chara._Move(), GetName(), GetTimeSinceLastRain(), WidgetArtTool.OnActivate(), BaseGameScreen.RefreshScreenSize(), BaseGameScreen.RefreshWeather(), GameScreenElona.RefreshWeather(), and Chara.TickConditions().
IsBlossom
bool Weather.IsBlossom get
Definition at line 140 of file Weather.cs.
    {
        get
        {
            if (CurrentCondition != Condition.Blossom)
            {
                if (IsFineOrCloudy)
                {
                    return EClass._map.config.blossom;
                }
                return false;
            }
            return true;
        }
    }
Referenced by BaseGameScreen.RefreshWeather().
IsEther
bool Weather.IsEther get
Definition at line 156 of file Weather.cs.
Referenced by BaseGameScreen.RefreshWeather(), and GameScreenElona.RefreshWeather().
IsFineOrCloudy
bool Weather.IsFineOrCloudy get
Definition at line 104 of file Weather.cs.
    {
        get
        {
            if (CurrentCondition != 0)
            {
                return CurrentCondition == Condition.Cloudy;
            }
            return true;
        }
    }
IsHazard
bool Weather.IsHazard get
Definition at line 92 of file Weather.cs.
    {
        get
        {
            if (CurrentCondition != Condition.Rain && CurrentCondition != Condition.RainHeavy && CurrentCondition != Condition.Snow && CurrentCondition != Condition.SnowHeavy)
            {
                return CurrentCondition == Condition.Ether;
            }
            return true;
        }
    }
Referenced by TraitGenerator.OnSimulateHour().
IsRaining
bool Weather.IsRaining get
Definition at line 116 of file Weather.cs.
    {
        get
        {
            if (CurrentCondition != Condition.Rain)
            {
                return CurrentCondition == Condition.RainHeavy;
            }
            return true;
        }
    }
Referenced by GameUpdater.SurfaceUpdater.FixedUpdate(), BaseGameScreen.RefreshWeather(), GameScreenElona.RefreshWeather(), RefreshWeather(), SetCondition(), Chara.TickConditions(), Trait.TryToggle(), and GameUpdater.Update100ms().
IsSnowing
bool Weather.IsSnowing get
Definition at line 128 of file Weather.cs.
    {
        get
        {
            if (CurrentCondition != Condition.Snow)
            {
                return CurrentCondition == Condition.SnowHeavy;
            }
            return true;
        }
    }
Referenced by RefreshWeather().
season
Season Weather.season get
Definition at line 90 of file Weather.cs.
Referenced by GetForecast().
The documentation for this class was generated from the following file:
Elin/Weather.cs