Elin Decompiled Documentation: Act Class Reference
Act Class Reference
Classes
struct Cost
Public Types
enum CostType {
None , MP , SP , None ,
MP , SP
}
enum CostType {
None , MP , SP , None ,
MP , SP
}
Public Member Functions
virtual CursorInfo GetCursorIcon (Card c)
virtual MultiSprite GetStateIcon ()
override Sprite GetSprite ()
virtual bool ShowMouseHint (Card c)
virtual bool IsValidTC (Card c)
virtual string GetHintText (string str="")
virtual string GetText (string str="")
virtual string GetTextSmall (Card c)
virtual Color GetActPlanColor ()
virtual bool Perform ()
virtual bool CanPerform ()
bool Perform (Chara _cc, Card _tc=null, Point _tp=null)
bool CanPerform (Chara _cc, Card _tc=null, Point _tp=null)
virtual bool IsToolValid ()
new void SetImage (Image image)
virtual void OnMarkMapHighlights ()
virtual bool ShouldMapHighlight (Point p)
virtual CursorInfo GetCursorIcon (Card c)
virtual MultiSprite GetStateIcon ()
override Sprite GetSprite ()
virtual bool ShowMouseHint (Card c)
virtual bool IsValidTC (Card c)
virtual string GetHintText (string str="")
virtual string GetText (string str="")
virtual string GetTextSmall (Card c)
virtual Color GetActPlanColor ()
virtual bool Perform ()
virtual bool CanPerform ()
bool Perform (Chara _cc, Card _tc=null, Point _tp=null)
bool CanPerform (Chara _cc, Card _tc=null, Point _tp=null)
virtual bool IsToolValid ()
new void SetImage (Image image)
virtual void OnMarkMapHighlights ()
virtual bool ShouldMapHighlight (Point p)
Public Member Functions inherited from Element
virtual SourceElement.Row GetSource ()
virtual int GetSourcePotential (int v)
virtual Sprite GetSprite ()
int GetMaterialSourceValue (Thing t, int v)
virtual int GetSourceValue (int v, int lv, SourceValueType type)
virtual Sprite GetIcon (string suffix="")
int SortVal (bool charaSheet=false)
virtual bool CanLink (ElementContainer owner)
bool HasTag (string tag)
void SetImage (Image i)
virtual string GetDetail ()
bool IsFactionElement (Chara c)
Element GetParent (Card c)
void WriteNote (UINote n, ElementContainer owner=null, Action< UINote > onWriteNote=null)
void WriteNoteWithRef (UINote n, ElementContainer owner, Action< UINote > onWriteNote, Element refEle)
void _WriteNote (UINote n, Chara c, Act act)
void _WriteNote (UINote n, ElementContainer owner, Action< UINote > onWriteNote, bool isRef, bool addHeader=true)
virtual void OnWriteNote (UINote n, ElementContainer owner)
virtual void OnChangeValue ()
void CheckLevelBonus (ElementContainer owner, UINote n=null)
int GetSortVal (UIList.SortMode m)
virtual Act.Cost GetCost (Chara c)
virtual int GetPower (Card c)
virtual void SetTextValue (UIText text)
virtual SourceElement.Row GetSource ()
virtual int GetSourcePotential (int v)
virtual Sprite GetSprite ()
int GetMaterialSourceValue (Thing t, int v)
virtual int GetSourceValue (int v, int lv, SourceValueType type)
virtual Sprite GetIcon (string suffix="")
int SortVal (bool charaSheet=false)
virtual bool CanLink (ElementContainer owner)
bool HasTag (string tag)
void SetImage (Image i)
virtual string GetDetail ()
bool IsFactionElement (Chara c)
Element GetParent (Card c)
void WriteNote (UINote n, ElementContainer owner=null, Action< UINote > onWriteNote=null)
void WriteNoteWithRef (UINote n, ElementContainer owner, Action< UINote > onWriteNote, Element refEle)
void _WriteNote (UINote n, Chara c, Act act)
void _WriteNote (UINote n, ElementContainer owner, Action< UINote > onWriteNote, bool isRef, bool addHeader=true)
virtual void OnWriteNote (UINote n, ElementContainer owner)
virtual void OnChangeValue ()
void CheckLevelBonus (ElementContainer owner, UINote n=null)
int GetSortVal (UIList.SortMode m)
virtual Act.Cost GetCost (Chara c)
virtual int GetPower (Card c)
virtual void SetTextValue (UIText text)
Static Public Member Functions
static void SetReference (Chara _cc, Card _tc=null, Point _tp=null)
static void SetTool (Thing t)
static void SetReference (Chara _cc, Card _tc=null, Point _tp=null)
static void SetTool (Thing t)
Static Public Member Functions inherited from Element
static string GetName (string alias)
static SourceElement.Row Get (int id)
static Dictionary< int, int > GetElementMap (int[] list)
static Dictionary< int, int > GetElementMap (int[] list, Dictionary< int, int > map)
static SourceElement.Row GetRandomElement (int lv=1)
static Element Create (int id, int v=0)
static Element Create (string id, int v=1)
static int GetId (string alias)
static int GetResistLv (int v)
static int GetResistDamage (int dmg, int v)
static string GetName (string alias)
static SourceElement.Row Get (int id)
static Dictionary< int, int > GetElementMap (int[] list)
static Dictionary< int, int > GetElementMap (int[] list, Dictionary< int, int > map)
static SourceElement.Row GetRandomElement (int lv=1)
static Element Create (int id, int v=0)
static Element Create (string id, int v=1)
static int GetId (string alias)
static int GetResistLv (int v)
static int GetResistDamage (int dmg, int v)
Static Public Member Functions inherited from EClass
static int rnd (int a)
static int curve (int a, int start, int step, int rate=75)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Static Public Attributes
static Chara CC
static Card TC
static Point TP = new Point()
static Thing TOOL
static int powerMod = 100
static bool forcePt
Static Public Attributes inherited from Element
const int Div = 5
static Element Void = new Element()
static int[] List_MainAttributes
static int[] List_MainAttributesMajor
static int[] List_Body
static int[] List_Mind
static List< SourceElement.Row > ListElements = new List<SourceElement.Row>()
static List< SourceElement.Row > ListAttackElements = new List<SourceElement.Row>()
Static Public Attributes inherited from EClass
static Core core
Properties
override bool ShowPotential [get]
override bool UsePotential [get]
override bool ShowRelativeAttribute [get]
virtual CursorInfo CursorIcon [get]
virtual string ID [get]
virtual bool IsAct [get]
virtual bool WillEndTurn [get]
virtual bool CloseLayers [get]
virtual int LeftHand [get]
virtual int RightHand [get]
virtual int ElementPowerMod [get]
virtual bool ShowMapHighlight [get]
virtual bool ShowMapHighlightBlock [get]
virtual bool PickHeldOnStart [get]
virtual bool DropHeldOnStart [get]
virtual bool CanPressRepeat [get]
virtual bool CanAutofire [get]
virtual bool ResetAxis [get]
virtual bool RequireTool [get]
virtual bool IsHostileAct [get]
virtual bool HideRightInfo [get]
virtual bool HaveLongPressAction [get]
virtual float Radius [get]
virtual int PerformDistance [get]
virtual int MaxRadius [get]
virtual TargetType TargetType [get]
virtual bool LocalAct [get]
virtual bool CanRapidFire [get]
virtual float RapidDelay [get]
virtual bool ShowAuto [get]
virtual bool IsCrime [get]
Properties inherited from Element
SourceElement.Row source [get]
virtual int DisplayValue [get]
virtual int MinValue [get]
int Value [get]
int ValueWithoutLink [get]
virtual int MinPotential [get]
int Potential [get]
virtual bool CanGainExp [get]
bool IsFlag [get]
virtual string Name [get]
virtual string FullName [get]
virtual int ExpToNext [get]
virtual bool UseExpMod [get]
virtual int CostTrain [get]
virtual int CostLearn [get]
virtual bool ShowXP [get]
virtual bool ShowMsgOnValueChanged [get]
virtual bool ShowValue [get]
virtual bool ShowPotential [get]
virtual bool UsePotential [get]
virtual bool PotentialAsStock [get]
virtual bool ShowRelativeAttribute [get]
virtual bool ShowBonuses [get]
virtual string ShortName [get]
bool IsGlobalElement [get]
bool IsFactionWideElement [get]
bool IsPartyWideElement [get]
virtual bool ShowEncNumber [get]
bool IsTrait [get]
bool IsFoodTrait [get]
bool IsFoodTraitMain [get]
bool IsMainAttribute [get]
Act act [get]
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Additional Inherited Members
Public Attributes inherited from Element
SourceElement.Row _source
int id
int vBase
int vExp
int vPotential
int vTempPotential
int vLink
int vSource
int vSourcePotential
ElementContainer owner
Static Package Functions inherited from Element
static string< _WriteNote > g__Calc (ref Element.<>c__DisplayClass103_0 A_0)
Detailed Description
Definition at line 5 of file Act.2.cs.
Member Enumeration Documentation
CostType [1/2]
enum Act.CostType
Enumerator
None
MP
SP
None
MP
SP
Definition at line 568 of file Act.2.cs.
    {
        None,
        MP,
        SP
    }
CostType [2/2]
enum Act.CostType
Enumerator
None
MP
SP
None
MP
SP
Definition at line 59 of file ACT.cs.
    {
        None,
        MP,
        SP
    }
Member Function Documentation
CanPerform() [1/4]
virtual bool Act.CanPerform () inline virtual
Reimplemented in ActBash, ActDrawWater, ActItem, ActKick, ActMelee, ActPick, ActRanged, ActRestrain, ActRush, ActThrow, ActWater, AI_Fish, AI_Steal, TaskCullLife, TaskPoint, and TaskWater.
Definition at line 435 of file Act.2.cs.
    {
        return true;
    }
Referenced by CanPerform(), ActPlan.Item.Perform(), Perform(), ActPlan.TrySetAct(), HotItemAct.TrySetAct(), TraitCatalyst.TrySetHeldAct(), and GoalCombat.TryUseAbility().
CanPerform() [2/4]
virtual bool Act.CanPerform () inline virtual
Reimplemented in ActBash, ActDrawWater, ActItem, ActKick, ActMelee, ActPick, ActRanged, ActRestrain, ActRush, ActThrow, ActWater, AI_Fish, AI_Steal, TaskCullLife, TaskPoint, and TaskWater.
Definition at line 281 of file ACT.cs.
    {
        return true;
    }
CanPerform() [3/4]
bool Act.CanPerform (Chara _cc, Card _tc = null, Point _tp = null) inline
Definition at line 445 of file Act.2.cs.
    {
        Act.<>c__DisplayClass82_0 CS$<>8__locals1 = new Act.<>c__DisplayClass82_0();
        CS$<>8__locals1.<>4__this = this;
        Act.CC = _cc;
        Act.TC = _tc;
        Point tp = Act.TP;
        Point point = _tp;
        if (_tp == null)
        {
            Card tc = Act.TC;
            point = (((tc != null) ? tc.pos : null) ?? Act.CC.pos);
        }
        tp.Set(point);
        CS$<>8__locals1.tt = this.TargetType;
        if (Act.forcePt && CS$<>8__locals1.tt.Range == TargetRange.Self && !Act.CC.IsPC)
        {
            CS$<>8__locals1.tt = TargetType.Chara;
        }
        if (this.LocalAct && EClass._zone.IsRegion)
        {
            return false;
        }
        if (CS$<>8__locals1.tt.Range == TargetRange.Self)
        {
            Act.TP.Set(Act.CC.pos);
            return this.CanPerform();
        }
        if (Act.CC.IsPC && EClass.core.config.game.shiftToUseNegativeAbilityOnSelf)
        {
            Chara firstChara = Act.TP.FirstChara;
            if (firstChara != null && firstChara.IsPCFactionOrMinion)
            {
                bool flag = base.source.tag.Contains("neg");
                if (base.source.id != 6011 && flag && !EInput.isShiftDown)
                {
                    return false;
                }
            }
        }
        if (!(this is ActMelee) && CS$<>8__locals1.tt.Range == TargetRange.Chara && (Act.TC == null || !Act.CC.CanSee(Act.TC)))
        {
            return false;
        }
        CS$<>8__locals1.distCheck = CS$<>8__locals1.<CanPerform>g__DistCheck|0(Act.CC.pos, Act.TP);
        if (!CS$<>8__locals1.distCheck && (Act.CC.IsMultisize || (Act.TC != null && Act.TC.IsMultisize)))
        {
            if (Act.CC.IsMultisize)
            {
                Act.CC.ForeachPoint(delegate(Point p, bool main)
                {
                    base.<CanPerform>g__DistCheckMulti|1(p, Act.TC);
                });
            }
            else
            {
                CS$<>8__locals1.<CanPerform>g__DistCheckMulti|1(Act.CC.pos, Act.TC);
            }
        }
        return CS$<>8__locals1.distCheck && this.CanPerform();
    }
References EClass._zone, CanPerform(), Chara.CanSee(), CC, TargetType.Chara, Core.config, EClass.core, Point.FirstChara, forcePt, Card.ForeachPoint(), CoreConfig.game, Card.IsMultisize, Chara.IsMultisize, Chara.IsPC, Card.IsPCFactionOrMinion, Spatial.IsRegion, LocalAct, Card.pos, Point.Set(), CoreConfig.GameConfig.shiftToUseNegativeAbilityOnSelf, Chara.source, TargetType, TC, and TP.
CanPerform() [4/4]
bool Act.CanPerform (Chara _cc, Card _tc = null, Point _tp = null) inline
Definition at line 295 of file ACT.cs.
    {
        CC = _cc;
        TC = _tc;
        TP.Set(_tp ?? TC?.pos ?? CC.pos);
        TargetType tt = TargetType;
        if (forcePt && tt.Range == TargetRange.Self && !CC.IsPC)
        {
            tt = TargetType.Chara;
        }
        if (LocalAct && EClass._zone.IsRegion)
        {
            return false;
        }
        if (tt.Range == TargetRange.Self)
        {
            TP.Set(CC.pos);
            return CanPerform();
        }
        if (CC.IsPC && EClass.core.config.game.shiftToUseNegativeAbilityOnSelf)
        {
            Chara firstChara = TP.FirstChara;
            if (firstChara != null && firstChara.IsPCFactionOrMinion)
            {
                bool flag = base.source.tag.Contains("neg");
                if (base.source.id != 6011 && flag && !EInput.isShiftDown)
                {
                    return false;
                }
            }
        }
        if (!(this is ActMelee) && tt.Range == TargetRange.Chara && (TC == null || !CC.CanSee(TC)))
        {
            return false;
        }
        bool distCheck = DistCheck(CC.pos, TP);
        if (!distCheck && (CC.IsMultisize || (TC != null && TC.IsMultisize)))
        {
            if (CC.IsMultisize)
            {
                CC.ForeachPoint(delegate(Point p, bool main)
                {
                    DistCheckMulti(p, TC);
                });
            }
            else
            {
                DistCheckMulti(CC.pos, TC);
            }
        }
        if (!distCheck)
        {
            return false;
        }
        return CanPerform();
        bool DistCheck(Point p1, Point p2)
        {
            int num = p1.Distance(p2);
            if (tt.RequireLos)
            {
                if (CC.IsPC)
                {
                    if (!p2.IsSync)
                    {
                        return false;
                    }
                }
                else if (!Los.IsVisible(p1, p2))
                {
                    return false;
                }
            }
            if (num >= tt.LimitDist)
            {
                return false;
            }
            if (num >= MaxRadius)
            {
                return false;
            }
            if (tt.RequireChara && !p2.HasChara)
            {
                return false;
            }
            if (tt.CanOnlyTargetEnemy)
            {
                foreach (Chara chara in p2.Charas)
                {
                    if (CC.IsHostile(chara))
                    {
                        return true;
                    }
                }
                return false;
            }
            return true;
        }
        void DistCheckMulti(Point p1, Card c)
        {
            if (c == null && !distCheck)
            {
                distCheck = DistCheck(p1, TP);
            }
            else
            {
                c.ForeachPoint(delegate(Point p, bool main)
                {
                    if (!distCheck)
                    {
                        distCheck = DistCheck(p1, p);
                    }
                });
            }
        }
    }
References EClass._zone, TargetType.CanOnlyTargetEnemy, CanPerform(), Chara.CanSee(), CC, TargetType.Chara, Point.Charas, Core.config, EClass.core, Point.Distance(), Point.FirstChara, forcePt, Card.ForeachPoint(), CoreConfig.game, Point.HasChara, Chara.IsHostile(), Chara.IsMultisize, Chara.IsPC, Card.IsPCFactionOrMinion, Spatial.IsRegion, Point.IsSync, Los.IsVisible(), TargetType.LimitDist, LocalAct, MaxRadius, Card.pos, TargetType.Range, TargetType.RequireChara, TargetType.RequireLos, Point.Set(), CoreConfig.GameConfig.shiftToUseNegativeAbilityOnSelf, Chara.source, TargetType, and TP.
GetActPlanColor() [1/2]
virtual Color Act.GetActPlanColor () inline virtual
Reimplemented in GoalAutoCombat.
Definition at line 381 of file Act.2.cs.
    {
        if (!this.IsCrime)
        {
            return EClass.Colors.colorAct;
        }
        return EClass.Colors.colorHostileAct;
    }
References ColorProfile.colorAct, ColorProfile.colorHostileAct, EClass.Colors, and IsCrime.
GetActPlanColor() [2/2]
virtual Color Act.GetActPlanColor () inline virtual
Reimplemented in GoalAutoCombat.
Definition at line 235 of file ACT.cs.
    {
        if (!IsCrime)
        {
            return EClass.Colors.colorAct;
        }
        return EClass.Colors.colorHostileAct;
    }
References ColorProfile.colorAct, ColorProfile.colorHostileAct, EClass.Colors, and IsCrime.
GetCursorIcon() [1/2]
virtual CursorInfo Act.GetCursorIcon (Card c) inline virtual
Reimplemented in ActMelee.
Definition at line 31 of file Act.2.cs.
    {
        return this.CursorIcon;
    }
References CursorIcon.
GetCursorIcon() [2/2]
virtual CursorInfo Act.GetCursorIcon (Card c) inline virtual
Reimplemented in ActMelee.
Definition at line 175 of file ACT.cs.
    {
        return CursorIcon;
    }
References CursorIcon.
GetHintText() [1/2]
virtual string Act.GetHintText (string str = "") inline virtual
Reimplemented in ActMelee.
Definition at line 216 of file Act.2.cs.
    {
        return this.GetText(str);
    }
References GetText().
GetHintText() [2/2]
virtual string Act.GetHintText (string str = "") inline virtual
Reimplemented in ActMelee.
Definition at line 204 of file ACT.cs.
    {
        return GetText(str);
    }
References GetText().
GetSprite() [1/2]
override Sprite Act.GetSprite () inline virtual
Reimplemented from Element.
Definition at line 49 of file Act.2.cs.
    {
        return base.source.GetSprite();
    }
Referenced by HotItemAct.GetSprite(), and SetImage().
GetSprite() [2/2]
override Sprite Act.GetSprite () inline virtual
Reimplemented from Element.
Definition at line 185 of file ACT.cs.
    {
        return base.source.GetSprite();
    }
GetStateIcon() [1/2]
virtual MultiSprite Act.GetStateIcon () inline virtual
Reimplemented in AI_PassTime, and AIAct.
Definition at line 44 of file Act.2.cs.
    {
        return null;
    }
GetStateIcon() [2/2]
virtual MultiSprite Act.GetStateIcon () inline virtual
Reimplemented in AI_PassTime, and AIAct.
Definition at line 180 of file ACT.cs.
    {
        return null;
    }
GetText() [1/2]
virtual string Act.GetText (string str = "") inline virtual
Reimplemented in ActRanged, ActThrow, AI_Shear, BaseTaskHarvest, DynamicAct, DynamicAIAct, TaskBuild, and TaskWater.
Definition at line 221 of file Act.2.cs.
    {
        if (base.source != null)
        {
            this.id = base.source.id;
        }
        if (this.id != 0)
        {
            return Lang.ParseRaw(base.source.GetName(), str, null, null, null, null);
        }
        if (!Lang.Has(this.ToString()))
        {
            string[] array = new string[5];
            array[0] = this.ToString();
            array[1] = "/";
            int num = 2;
            SourceElement.Row source = base.source;
            array[num] = ((source != null) ? source.ToString() : null);
            array[3] = "/";
            array[4] = this.id.ToString();
            return string.Concat(array);
        }
        return Lang.Get(this.ToString());
    }
References Element.source.
Referenced by GetHintText(), ActPlan.Item.GetText(), ActPlan.Item.GetTextContext(), and ActPlan.Item.Perform().
GetText() [2/2]
virtual string Act.GetText (string str = "") inline virtual
Reimplemented in ActRanged, ActThrow, AI_Shear, BaseTaskHarvest, DynamicAct, DynamicAIAct, TaskBuild, and TaskWater.
Definition at line 209 of file ACT.cs.
    {
        if (base.source != null)
        {
            id = base.source.id;
        }
        if (id == 0)
        {
            if (!Lang.Has(ToString()))
            {
                return ToString() + "/" + base.source?.ToString() + "/" + id;
            }
            return Lang.Get(ToString());
        }
        return Lang.ParseRaw(base.source.GetName(), str);
    }
References Element.id.
GetTextSmall() [1/2]
virtual string Act.GetTextSmall (Card c) inline virtual
Reimplemented in ActMelee, BaseTaskHarvest, TaskDig, TaskHarvest, and TaskMine.
Definition at line 246 of file Act.2.cs.
    {
        if (c == null)
        {
            return null;
        }
        return c.Name + c.GetExtraName();
    }
References Card.GetExtraName().
Referenced by ActPlan.Item.GetText().
GetTextSmall() [2/2]
virtual string Act.GetTextSmall (Card c) inline virtual
Reimplemented in ActMelee, BaseTaskHarvest, TaskDig, TaskHarvest, and TaskMine.
Definition at line 226 of file ACT.cs.
    {
        if (c == null)
        {
            return null;
        }
        return c.Name + c.GetExtraName();
    }
References Card.GetExtraName().
IsToolValid() [1/2]
virtual bool Act.IsToolValid () inline virtual
Reimplemented in AIAct.
Definition at line 514 of file Act.2.cs.
    {
        return Act.CC == EClass.pc && Act.TOOL != null && Act.TOOL.parent == EClass.pc;
    }
References EClass.pc.
IsToolValid() [2/2]
virtual bool Act.IsToolValid () inline virtual
Reimplemented in AIAct.
Definition at line 418 of file ACT.cs.
    {
        if (CC == EClass.pc && TOOL != null)
        {
            return TOOL.parent == EClass.pc;
        }
        return false;
    }
References CC, EClass.pc, and TOOL.
IsValidTC() [1/2]
virtual bool Act.IsValidTC (Card c) inline virtual
Reimplemented in AI_Shear, and AI_Steal.
Definition at line 211 of file Act.2.cs.
    {
        return c.isChara || c.trait.CanBeAttacked;
    }
References Trait.CanBeAttacked, and Card.trait.
Referenced by HotItemAct.TrySetAct(), and TraitCatalyst.TrySetHeldAct().
IsValidTC() [2/2]
virtual bool Act.IsValidTC (Card c) inline virtual
Reimplemented in AI_Shear, and AI_Steal.
Definition at line 195 of file ACT.cs.
    {
        if (!c.isChara)
        {
            return c.trait.CanBeAttacked;
        }
        return true;
    }
References Trait.CanBeAttacked, Card.isChara, and Card.trait.
OnMarkMapHighlights() [1/2]
virtual void Act.OnMarkMapHighlights () inline virtual
Reimplemented in ActRush.
Definition at line 539 of file Act.2.cs.
    {
        EClass._map.ForeachSphere(EClass.pc.pos.x, EClass.pc.pos.z, (float)base.act.MaxRadius, delegate(Point p)
        {
            if (!p.HasBlock && this.ShouldMapHighlight(p))
            {
                p.cell.highlight = 8;
                EClass.player.lastMarkedHighlights.Add(p.Copy());
            }
        });
    }
References EClass._map, Map.ForeachSphere(), Point.HasBlock, EClass.pc, Card.pos, Point.x, and Point.z.
Referenced by HotItemGameAction.OnMarkMapHighlights().
OnMarkMapHighlights() [2/2]
virtual void Act.OnMarkMapHighlights () inline virtual
Reimplemented in ActRush.
Definition at line 447 of file ACT.cs.
    {
        EClass._map.ForeachSphere(EClass.pc.pos.x, EClass.pc.pos.z, base.act.MaxRadius, delegate(Point p)
        {
            if (!p.HasBlock && ShouldMapHighlight(p))
            {
                p.cell.highlight = 8;
                EClass.player.lastMarkedHighlights.Add(p.Copy());
            }
        });
    }
References EClass._map, Point.Copy(), Map.ForeachSphere(), Point.HasBlock, Player.lastMarkedHighlights, EClass.pc, EClass.player, Card.pos, ShouldMapHighlight(), Point.x, and Point.z.
Perform() [1/4]
virtual bool Act.Perform () inline virtual
Reimplemented in ActBash, ActChat, ActDrawWater, ActDreamBug, ActItem, ActKick, ActMelee, ActPick, ActPray, ActQuickCraft, ActRanged, ActRestrain, ActRide, ActRush, ActSummonGuard, ActThrow, ActWait, ActWater, ActZap, AI_Shear, AI_Steal, AIAct, DynamicAct, and DynamicAIAct.
Definition at line 398 of file Act.2.cs.
    {
        int id = this.id;
        if ((id == 8230 || id == 8232) && Act.TC.isThing)
        {
            int power = Act.CC.elements.GetOrCreateElement(base.source.id).GetPower(Act.CC) * Act.powerMod / 100;
            ActEffect.Proc(base.source.proc[0].ToEnum(true), power, BlessedState.Normal, Act.CC, Act.TC, default(ActRef));
            return true;
        }
        if (base.source.proc.Length != 0)
        {
            string text = base.source.aliasRef.IsEmpty(Act.CC.MainElement.source.alias);
            string a = base.source.proc[0];
            if (a == "LulwyTrick" || a == "BuffStats")
            {
                text = base.source.proc[1];
            }
            else if (text == "mold")
            {
                text = Act.CC.MainElement.source.alias;
            }
            if (this.TargetType.Range == TargetRange.Self && !Act.forcePt)
            {
                Act.TC = Act.CC;
                Act.TP.Set(Act.CC.pos);
            }
            int power2 = Act.CC.elements.GetOrCreateElement(base.source.id).GetPower(Act.CC) * Act.powerMod / 100;
            ActEffect.ProcAt(base.source.proc[0].ToEnum(true), power2, BlessedState.Normal, Act.CC, Act.TC, Act.TP, base.source.tag.Contains("neg"), new ActRef
            {
                n1 = base.source.proc.TryGet(1, true),
                aliasEle = text,
                act = this
            });
        }
        return true;
    }
References CC, Card.elements, forcePt, ElementContainer.GetOrCreateElement(), Element.GetPower(), Element.id, Card.isThing, Chara.MainElement, Card.pos, ActEffect.Proc(), ActEffect.ProcAt(), TargetType.Range, Point.Set(), Element.source, TC, and TP.
Referenced by ActMelee.Attack(), Thing.DoAct(), UIInventory.DoAct(), ActItem.Perform(), ActPlan.Item.Perform(), Perform(), and Chara.UseAbility().
Perform() [2/4]
virtual bool Act.Perform () inline virtual
Reimplemented in ActBash, ActChat, ActDrawWater, ActDreamBug, ActItem, ActKick, ActMelee, ActPick, ActPray, ActQuickCraft, ActRanged, ActRestrain, ActRide, ActRush, ActSummonGuard, ActThrow, ActWait, ActWater, ActZap, AI_Shear, AI_Steal, AIAct, DynamicAct, and DynamicAIAct.
Definition at line 244 of file ACT.cs.
    {
        int num = id;
        if ((num == 8230 || num == 8232) && TC.isThing)
        {
            int power = CC.elements.GetOrCreateElement(base.source.id).GetPower(CC) * powerMod / 100;
            ActEffect.Proc(base.source.proc[0].ToEnum<EffectId>(), power, BlessedState.Normal, CC, TC);
            return true;
        }
        if (base.source.proc.Length != 0)
        {
            string text = base.source.aliasRef.IsEmpty(CC.MainElement.source.alias);
            string text2 = base.source.proc[0];
            if (text2 == "LulwyTrick" || text2 == "BuffStats")
            {
                text = base.source.proc[1];
            }
            else if (text == "mold")
            {
                text = CC.MainElement.source.alias;
            }
            if (TargetType.Range == TargetRange.Self && !forcePt)
            {
                TC = CC;
                TP.Set(CC.pos);
            }
            int power2 = CC.elements.GetOrCreateElement(base.source.id).GetPower(CC) * powerMod / 100;
            ActEffect.ProcAt(base.source.proc[0].ToEnum<EffectId>(), power2, BlessedState.Normal, CC, TC, TP, base.source.tag.Contains("neg"), new ActRef
            {
                n1 = base.source.proc.TryGet(1, returnNull: true),
                aliasEle = text,
                act = this
            });
        }
        return true;
    }
References CC, Card.elements, forcePt, ElementContainer.GetOrCreateElement(), Element.GetPower(), Element.id, Chara.MainElement, Card.pos, powerMod, ActEffect.Proc(), ActEffect.ProcAt(), TargetType.Range, Point.Set(), Element.source, and TP.
Perform() [3/4]
bool Act.Perform (Chara _cc, Card _tc = null, Point _tp = null) inline
Definition at line 440 of file Act.2.cs.
    {
        return this.CanPerform(_cc, _tc, _tp) && this.Perform();
    }
References CanPerform(), and Perform().
Perform() [4/4]
bool Act.Perform (Chara _cc, Card _tc = null, Point _tp = null) inline
Definition at line 286 of file ACT.cs.
    {
        if (CanPerform(_cc, _tc, _tp))
        {
            return Perform();
        }
        return false;
    }
References CanPerform(), and Perform().
SetImage() [1/2]
new void Act.SetImage (Image image) inline
Definition at line 524 of file Act.2.cs.
    {
        image.sprite = (this.GetSprite() ?? EClass.core.refs.icons.defaultAbility);
        if (!base.source.aliasRef.IsEmpty())
        {
            image.color = EClass.setting.elements[base.source.aliasRef].colorSprite;
        }
        else
        {
            image.color = Color.white;
        }
        image.rectTransform.pivot = new Vector2(0.5f, 0.5f);
        image.SetNativeSize();
    }
References Color, EClass.core, CoreRef.Icons.defaultAbility, GameSetting.elements, GetSprite(), CoreRef.icons, Core.refs, and EClass.setting.
Referenced by ButtonAbility.SetAct(), and HotItemAct.SetImage().
SetImage() [2/2]
new void Act.SetImage (Image image) inline
Definition at line 432 of file ACT.cs.
    {
        image.sprite = GetSprite() ?? EClass.core.refs.icons.defaultAbility;
        if (!base.source.aliasRef.IsEmpty())
        {
            image.color = EClass.setting.elements[base.source.aliasRef].colorSprite;
        }
        else
        {
            image.color = Color.white;
        }
        image.rectTransform.pivot = new Vector2(0.5f, 0.5f);
        image.SetNativeSize();
    }
References Color, EClass.core, CoreRef.Icons.defaultAbility, GameSetting.elements, GetSprite(), CoreRef.icons, Core.refs, and EClass.setting.
SetReference() [1/2]
static void Act.SetReference (Chara _cc, Card _tc = null, Point _tp = null) inline static
Definition at line 507 of file Act.2.cs.
    {
        Act.CC = _cc;
        Act.TC = _tc;
        Act.TP.Set(_tp ?? Act.TC.pos);
    }
References Card.pos, Point.Set(), TC, and TP.
SetReference() [2/2]
static void Act.SetReference (Chara _cc, Card _tc = null, Point _tp = null) inline static
Definition at line 411 of file ACT.cs.
    {
        CC = _cc;
        TC = _tc;
        TP.Set(_tp ?? TC.pos);
    }
References CC, Point.Set(), and TP.
SetTool() [1/2]
static void Act.SetTool (Thing t) inline static
Definition at line 519 of file Act.2.cs.
    {
        Act.TOOL = t;
    }
SetTool() [2/2]
static void Act.SetTool (Thing t) inline static
Definition at line 427 of file ACT.cs.
    {
        TOOL = t;
    }
References TOOL.
ShouldMapHighlight() [1/2]
virtual bool Act.ShouldMapHighlight (Point p) inline virtual
Definition at line 551 of file Act.2.cs.
    {
        return base.act.TargetType.ShowMapHighlight && base.act.ShowMapHighlight && base.act.CanPerform(EClass.pc, null, p);
    }
References EClass.pc.
Referenced by OnMarkMapHighlights().
ShouldMapHighlight() [2/2]
virtual bool Act.ShouldMapHighlight (Point p) inline virtual
Definition at line 459 of file ACT.cs.
    {
        if (base.act.TargetType.ShowMapHighlight && base.act.ShowMapHighlight)
        {
            return base.act.CanPerform(EClass.pc, null, p);
        }
        return false;
    }
References EClass.pc.
ShowMouseHint() [1/2]
virtual bool Act.ShowMouseHint (Card c) inline virtual
Reimplemented in ActMelee.
Definition at line 126 of file Act.2.cs.
    {
        return true;
    }
ShowMouseHint() [2/2]
virtual bool Act.ShowMouseHint (Card c) inline virtual
Reimplemented in ActMelee.
Definition at line 190 of file ACT.cs.
    {
        return true;
    }
Member Data Documentation
CC
static Chara Act.CC static
Definition at line 556 of file Act.2.cs.
Referenced by ActMelee.Attack(), ActBash.CanPerform(), ActKick.CanPerform(), ActMelee.CanPerform(), ActRanged.CanPerform(), ActRush.CanPerform(), ActThrow.CanPerform(), TaskPoint.CanPerform(), CanPerform(), IsToolValid(), Perform(), ActBash.Perform(), ActDrawWater.Perform(), ActDreamBug.Perform(), ActItem.Perform(), ActKick.Perform(), ActPick.Perform(), ActPray.Perform(), ActRanged.Perform(), ActRestrain.Perform(), ActRide.Perform(), ActRush.Perform(), ActSummonGuard.Perform(), ActThrow.Perform(), ActWait.Perform(), ActWater.Perform(), ActZap.Perform(), AIAct.Perform(), ActPlan.Item.Perform(), ActPray.Pray(), SetReference(), ActThrow.Throw(), and ActRanged.TryReload().
forcePt
static bool Act.forcePt static
Definition at line 566 of file Act.2.cs.
Referenced by CanPerform(), and Perform().
powerMod
static int Act.powerMod = 100 static
Definition at line 564 of file Act.2.cs.
Referenced by Perform().
TC
static Card Act.TC static
Definition at line 558 of file Act.2.cs.
Referenced by ActMelee.Attack(), ActKick.CanPerform(), ActMelee.CanPerform(), ActRanged.CanPerform(), ActRestrain.CanPerform(), ActRush.CanPerform(), CanPerform(), Perform(), ActChat.Perform(), ActDreamBug.Perform(), ActKick.Perform(), ActRanged.Perform(), ActRestrain.Perform(), ActRush.Perform(), ActSummonGuard.Perform(), AI_Shear.Perform(), AI_Steal.Perform(), ActPlan.Item.Perform(), SetReference(), and ActThrow.Throw().
TOOL
static Thing Act.TOOL static
Definition at line 562 of file Act.2.cs.
Referenced by IsToolValid(), AIAct.IsToolValid(), TaskCut.OnProgress(), and SetTool().
TP
static Point Act.TP = new Point() static
Definition at line 560 of file Act.2.cs.
Referenced by ActMelee.Attack(), ActBash.CanPerform(), ActDrawWater.CanPerform(), ActKick.CanPerform(), ActPick.CanPerform(), ActRanged.CanPerform(), ActRestrain.CanPerform(), ActRush.CanPerform(), ActThrow.CanPerform(), AI_Fish.CanPerform(), TaskCullLife.CanPerform(), TaskPoint.CanPerform(), TaskWater.CanPerform(), CanPerform(), Perform(), ActBash.Perform(), ActPick.Perform(), ActRanged.Perform(), ActRestrain.Perform(), ActRide.Perform(), ActRush.Perform(), ActThrow.Perform(), ActWater.Perform(), ActZap.Perform(), ActPlan.Item.Perform(), TaskPoint.Run(), SetReference(), and ActThrow.Throw().
Property Documentation
CanAutofire
bool Act.CanAutofire get
Definition at line 155 of file Act.2.cs.
    {
        get
        {
            return false;
        }
    }
CanPressRepeat
bool Act.CanPressRepeat get
Definition at line 147 of file Act.2.cs.
    {
        get
        {
            return false;
        }
    }
Referenced by ActPlan.GetAction(), HotItemAct.TrySetAct(), and TraitCatalyst.TrySetHeldAct().
CanRapidFire
bool Act.CanRapidFire get
Definition at line 357 of file Act.2.cs.
    {
        get
        {
            return false;
        }
    }
Referenced by Chara.UseAbility().
CloseLayers
bool Act.CloseLayers get
Definition at line 78 of file Act.2.cs.
    {
        get
        {
            return true;
        }
    }
CursorIcon
CursorInfo Act.CursorIcon get
Definition at line 36 of file Act.2.cs.
    {
        get
        {
            return CursorSystem.Action;
        }
    }
Referenced by GetCursorIcon().
DropHeldOnStart
bool Act.DropHeldOnStart get
Definition at line 139 of file Act.2.cs.
    {
        get
        {
            return false;
        }
    }
Referenced by AIAct.Start().
ElementPowerMod
int Act.ElementPowerMod get
Definition at line 102 of file Act.2.cs.
    {
        get
        {
            return base.source.eleP;
        }
    }
Referenced by ActEffect.DamageEle().
HaveLongPressAction
bool Act.HaveLongPressAction get
Definition at line 195 of file Act.2.cs.
    {
        get
        {
            return this.TargetType.CanSelectParty;
        }
    }
Referenced by Element._WriteNote(), ButtonAbility.TryUse(), and GoalCombat.TryUseAbility().
HideRightInfo
bool Act.HideRightInfo get
Definition at line 187 of file Act.2.cs.
    {
        get
        {
            return false;
        }
    }
ID
string Act.ID get
Definition at line 54 of file Act.2.cs.
    {
        get
        {
            return base.source.alias;
        }
    }
Referenced by ActPlan.Item.Perform().
IsAct
bool Act.IsAct get
Definition at line 62 of file Act.2.cs.
    {
        get
        {
            return true;
        }
    }
Referenced by Thing.DoAct(), UIInventory.DoAct(), and ActPlan.Item.Perform().
IsCrime
bool Act.IsCrime get
Definition at line 390 of file Act.2.cs.
    {
        get
        {
            return EClass._zone.IsCrime(EClass.pc, this);
        }
    }
Referenced by GetActPlanColor().
IsHostileAct
bool Act.IsHostileAct get
Definition at line 179 of file Act.2.cs.
    {
        get
        {
            return false;
        }
    }
Referenced by Zone.IsCrime().
LeftHand
int Act.LeftHand get
Definition at line 86 of file Act.2.cs.
    {
        get
        {
            return 0;
        }
    }
Referenced by AIAct.Start().
LocalAct
bool Act.LocalAct get
Definition at line 349 of file Act.2.cs.
    {
        get
        {
            return true;
        }
    }
Referenced by Element._WriteNote(), ButtonAbility.CanAutoUse(), CanPerform(), TraitCatalyst.CanUse(), Thing.DoAct(), and UIInventory.DoAct().
MaxRadius
int Act.MaxRadius get
Definition at line 263 of file Act.2.cs.
    {
        get
        {
            return 99;
        }
    }
Referenced by CanPerform().
PerformDistance
int Act.PerformDistance get
Definition at line 255 of file Act.2.cs.
    {
        get
        {
            return 1;
        }
    }
Referenced by ActPlan.Item.Perform().
PickHeldOnStart
bool Act.PickHeldOnStart get
Definition at line 131 of file Act.2.cs.
    {
        get
        {
            return false;
        }
    }
Referenced by AIAct.Start().
Radius
float Act.Radius get
Definition at line 203 of file Act.2.cs.
    {
        get
        {
            return base.source.radius;
        }
    }
RapidDelay
float Act.RapidDelay get
Definition at line 365 of file Act.2.cs.
    {
        get
        {
            return 0.2f;
        }
    }
Referenced by Chara.UseAbility().
RequireTool
bool Act.RequireTool get
Definition at line 171 of file Act.2.cs.
    {
        get
        {
            return false;
        }
    }
ResetAxis
bool Act.ResetAxis get
Definition at line 163 of file Act.2.cs.
    {
        get
        {
            return false;
        }
    }
RightHand
int Act.RightHand get
Definition at line 94 of file Act.2.cs.
    {
        get
        {
            return 0;
        }
    }
Referenced by AIAct.Start().
ShowAuto
bool Act.ShowAuto get
Definition at line 373 of file Act.2.cs.
    {
        get
        {
            return false;
        }
    }
ShowMapHighlight
bool Act.ShowMapHighlight get
Definition at line 110 of file Act.2.cs.
    {
        get
        {
            return false;
        }
    }
ShowMapHighlightBlock
bool Act.ShowMapHighlightBlock get
Definition at line 118 of file Act.2.cs.
    {
        get
        {
            return false;
        }
    }
ShowPotential
override bool Act.ShowPotential get
Definition at line 7 of file Act.2.cs.
    {
        get
        {
            return false;
        }
    }
ShowRelativeAttribute
override bool Act.ShowRelativeAttribute get
Definition at line 23 of file Act.2.cs.
    {
        get
        {
            return true;
        }
    }
TargetType
TargetType Act.TargetType get
Definition at line 271 of file Act.2.cs.
    {
        get
        {
            if (!base.source.target.IsEmpty())
            {
                string target = base.source.target;
                uint num = <PrivateImplementationDetails>.ComputeStringHash(target);
                if (num <= 1049176909U)
                {
                    if (num <= 850565431U)
                    {
                        if (num != 333403860U)
{
                            if (num == 850565431U)
{
                                if (target == "Party")
{
                                    return TargetType.Party;
                                }
                            }
                        }
                        else if (target == "Chara")
{
                            return TargetType.Chara;
                        }
                    }
                    else if (num != 1004962635U)
                    {
                        if (num == 1049176909U)
{
                            if (target == "Select")
{
                                return TargetType.Select;
                            }
                        }
                    }
                    else if (target == "Enemy")
                    {
                        return TargetType.Enemy;
                    }
                }
                else if (num <= 2648502281U)
                {
                    if (num != 1480824651U)
                    {
                        if (num == 2648502281U)
{
                            if (target == "SelfParty")
{
                                return TargetType.SelfParty;
                            }
                        }
                    }
                    else if (target == "Neighbor")
                    {
                        return TargetType.SelfAndNeighbor;
                    }
                }
                else if (num != 3803529630U)
                {
                    if (num == 3834216855U)
                    {
                        if (target == "Self")
{
                            return TargetType.Self;
                        }
                    }
                }
                else if (target == "Ground")
                {
                    return TargetType.Ground;
                }
            }
            return TargetType.Any;
        }
    }
Referenced by Element._WriteNote(), ButtonAbility.CanAutoUse(), CanPerform(), TraitCatalyst.CanUse(), ButtonAbility.SetAct(), GoalCombat.TryUseAbility(), and Chara.UseAbility().
UsePotential
override bool Act.UsePotential get
Definition at line 15 of file Act.2.cs.
    {
        get
        {
            return false;
        }
    }
WillEndTurn
bool Act.WillEndTurn get
Definition at line 70 of file Act.2.cs.
    {
        get
        {
            return true;
        }
    }
The documentation for this class was generated from the following files:
Elin/Act.2.cs
Elin/ACT.cs