Elin Decompiled Documentation: CustomThingContent Class Reference
CustomThingContent Class Reference
Public Types
enum SpawnType {
Item , Block , Cassette , Currency ,
Category , Filter , Tag , Letter ,
Map , Perfume , Plan , Potion ,
Recipe , RedBook , Rod , Rune ,
RuneFree , Scroll , Skill , Spell ,
Usuihon
}
Public Member Functions
void OnThingCreated (Thing thing)
Thing Create (int createLv=-1)
override string ToString ()
Public Member Functions inherited from CustomContent
virtual void OnGameLoad (GameIOContext context)
virtual void OnGameSave (GameIOContext context)
override string ToString ()
Static Public Member Functions
static CustomThingContent CreateFromRow (SourceThing.Row r, ModPackage mod=null)
Static Public Member Functions inherited from CustomSourceContent
static string string string[] kv GetParams (string tag)
Static Public Member Functions inherited from EClass
static int rndSeed (int a, int seed)
static int rnd (long a)
static int rnd (int a)
static int curve (long _a, int start, int step, int rate=75)
static int sqrt (int a)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Public Attributes
BlessedState blessedState
string id = ""
IDTLevel identifyLevel
int lv = -1
Dictionary< string, int > mapInt = new Dictionary<string, int>()
Dictionary< string, string > mapStr = new Dictionary<string, string>()
string material = ""
bool noCopy
bool noRandomSocket
int num = 1
Rarity rarity
bool restock = true
List< string > sockets = new List<string>()
SpawnType type
string priceCalc = ""
Properties
override string SourceType [get]
Properties inherited from CustomSourceContent
virtual string SourceType [get]
string SourceId [get, set]
Properties inherited from CustomContent
string ContentId [get, protected set]
EMod Owner [get, protected set]
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Additional Inherited Members
Static Public Attributes inherited from CustomSourceContent
static string action
static string string spec
Static Public Attributes inherited from EClass
static Core core
Detailed Description
Definition at line 9 of file CustomThingContent.cs.
Member Enumeration Documentation
SpawnType
enum CustomThingContent.SpawnType
Enumerator
Item
Block
Cassette
Currency
Category
Filter
Tag
Letter
Map
Perfume
Plan
Potion
Recipe
RedBook
Rod
Rune
RuneFree
Scroll
Skill
Spell
Usuihon
Definition at line 11 of file CustomThingContent.cs.
    {
        Item,
        Block,
        Cassette,
        Currency,
        Category,
        Filter,
        Tag,
        Letter,
        Map,
        Perfume,
        Plan,
        Potion,
        Recipe,
        RedBook,
        Rod,
        Rune,
        RuneFree,
        Scroll,
        Skill,
        Spell,
        Usuihon
    }
Member Function Documentation
Create()
Thing CustomThingContent.Create (int createLv = -1) inline
Definition at line 201 of file CustomThingContent.cs.
    {
        if (lv != -1)
        {
            createLv = lv;
        }
        CardBlueprint.SetRarity(rarity);
        int.TryParse(id, out var result);
        if (EClass.sources.elements.fuzzyAlias.TryGetValue(id, out var value))
        {
            result = EClass.sources.elements.alias[value].id;
        }
        Thing thing = null;
        int idMat = EClass.sources.materials.alias.TryGetValue(material)?.id ?? (-1);
        switch (type)
        {
        case SpawnType.Item:
            thing = ThingGen.Create(id, idMat, createLv).SetNum(num);
            break;
        case SpawnType.Block:
        {
            SourceBlock.Row row = EClass.sources.blocks.alias.TryGetValue(id);
            if (row != null)
            {
                thing = ThingGen.CreateBlock(row.id, idMat).SetNum(num);
            }
            break;
        }
        case SpawnType.Cassette:
            if (!EClass.core.refs.dictBGM.ContainsKey(result))
            {
                result = EClass.core.refs.dictBGM.RandomItem().id;
            }
            thing = ThingGen.CreateCassette(result);
            break;
        case SpawnType.Currency:
            thing = ThingGen.CreateCurrency(num, id);
            break;
        case SpawnType.Category:
            thing = ThingGen.CreateFromCategory(id, createLv).SetNum(num);
            break;
        case SpawnType.Filter:
            thing = ThingGen.CreateFromFilter(id, createLv).SetNum(num);
            break;
        case SpawnType.Tag:
            thing = ThingGen.CreateFromTag(id, createLv).SetNum(num);
            break;
        case SpawnType.Letter:
            thing = ThingGen.CreateLetter(id);
            break;
        case SpawnType.Map:
            thing = ThingGen.CreateMap(id, createLv);
            break;
        case SpawnType.Perfume:
            thing = ThingGen.CreatePerfume(result, createLv).SetNum(num);
            break;
        case SpawnType.Plan:
            thing = ThingGen.CreatePlan(result);
            break;
        case SpawnType.Potion:
            thing = ThingGen.CreatePotion(result, num);
            break;
        case SpawnType.Recipe:
            thing = ThingGen.CreateRecipe(id);
            break;
        case SpawnType.RedBook:
            thing = ThingGen.CreateRedBook(id);
            break;
        case SpawnType.Rod:
            thing = ThingGen.CreateRod(result, num);
            break;
        case SpawnType.Rune:
            thing = ThingGen.CreateRune(result, num);
            break;
        case SpawnType.RuneFree:
            thing = ThingGen.CreateRune(result, num, free: true);
            break;
        case SpawnType.Scroll:
            thing = ThingGen.CreateScroll(result, num);
            break;
        case SpawnType.Skill:
            thing = ThingGen.CreateSkillbook(result, num);
            break;
        case SpawnType.Spell:
            thing = ThingGen.CreateSpellbook(result, 1, num);
            break;
        case SpawnType.Usuihon:
            thing = ThingGen.Create("1084");
            thing.c_idRefName = EClass.game.religions.dictAll.TryGetValue(id)?.id;
            break;
        default:
            thing = ThingGen.Create(id);
            break;
        }
        if (thing == null)
        {
            return null;
        }
        thing.c_IDTState = (int)identifyLevel;
        thing.SetBlessedState(blessedState);
        if (!restock)
        {
            thing.SetBool(101, enable: true);
        }
        if (!priceCalc.IsEmpty())
        {
            thing.SetStr("price_calc_override", priceCalc);
        }
        return thing;
    }
References blessedState, SourceManager.blocks, EClass.core, ThingGen.Create(), ThingGen.CreateBlock(), ThingGen.CreateCassette(), ThingGen.CreateCurrency(), ThingGen.CreateFromCategory(), ThingGen.CreateFromFilter(), ThingGen.CreateFromTag(), ThingGen.CreateLetter(), ThingGen.CreateMap(), ThingGen.CreatePerfume(), ThingGen.CreatePlan(), ThingGen.CreatePotion(), ThingGen.CreateRecipe(), ThingGen.CreateRedBook(), ThingGen.CreateRod(), ThingGen.CreateRune(), ThingGen.CreateScroll(), ThingGen.CreateSkillbook(), ThingGen.CreateSpellbook(), ReligionManager.dictAll, CoreRef.dictBGM, SourceManager.elements, SourceElement.fuzzyAlias, EClass.game, TileRow.id, identifyLevel, lv, material, SourceManager.materials, num, priceCalc, rarity, Core.refs, Game.religions, restock, Card.SetBlessedState(), Card.SetBool(), Card.SetNum(), CardBlueprint.SetRarity(), Card.SetStr(), EClass.sources, and type.
Referenced by CustomMerchantStock.Generate().
CreateFromRow()
static CustomThingContent CustomThingContent.CreateFromRow (SourceThing::Row r, ModPackage mod = null) inline static
Definition at line 73 of file CustomThingContent.cs.
    {
        CustomThingContent customThingContent = new CustomThingContent
        {
            ContentId = "Thing/" + r.id,
            SourceId = r.id,
            Owner = mod,
            id = r.id
        };
        string[] tag = r.tag;
        for (int i = 0; i < tag.Length; i++)
        {
            var (text, item, array) = CustomSourceContent.GetParams(tag[i]);
            switch (text)
            {
            case "forceRarity":
                customThingContent.rarity = r.quality.ToEnum<Rarity>();
                break;
            case "noCopy":
                if (r.elements.Contains(759))
                {
                    customThingContent.noCopy = true;
                }
                break;
            case "noRandomSocket":
                customThingContent.noRandomSocket = true;
                break;
            case "noRestock":
                customThingContent.restock = false;
                break;
            case "addSocket":
                customThingContent.sockets.Add(item);
                break;
            case "addFlag":
            case "addInt":
                customThingContent.mapInt[array[0]] = array.TryGet(1, returnNull: true)?.ToInt() ?? 1;
                break;
            case "addFlagValue":
            case "addStr":
                if (!array.TryGet(1, returnNull: true).IsEmpty())
                {
                    customThingContent.mapStr[array[0]] = array[1];
                }
                break;
            }
        }
        return customThingContent;
    }
References CustomContent.ContentId, CustomSourceContent.GetParams(), item, mapInt, mapStr, CustomContent.Owner, sockets, and CustomSourceContent.SourceId.
Referenced by ModPackage.GenerateCustomContentProfiles().
OnThingCreated()
void CustomThingContent.OnThingCreated (Thing thing) inline
Definition at line 122 of file CustomThingContent.cs.
    {
        if (thing.GetBool("custom_content") || thing.id != base.SourceId)
        {
            return;
        }
        thing.SetBool("custom_content", enable: true);
        thing.SetStr("custom_content_id", base.ContentId);
        thing.SetStr("custom_content_package", base.Owner.id);
        string key2;
        foreach (KeyValuePair<string, string> item in mapStr)
        {
            item.Deconstruct(out var key, out key2);
            string text = key;
            string value = key2;
            thing.SetStr(text, value);
        }
        foreach (KeyValuePair<string, int> item2 in mapInt)
        {
            item2.Deconstruct(out key2, out var value2);
            string text2 = key2;
            int value3 = value2;
            thing.SetInt(text2, value3);
        }
        thing.ChangeRarity(rarity);
        if (noCopy)
        {
            EClass.core.actionsNextFrame.Add(delegate
            {
                thing.elements?.SetBase(759, 10);
            });
        }
        if (sockets.Count <= 0)
        {
            return;
        }
        if (noRandomSocket)
        {
            thing.sockets.Clear();
        }
        int num = 0;
        foreach (string socket in sockets)
        {
            thing.AddSocket();
            if (socket.IsEmpty())
            {
                num++;
            }
            else
            {
                ApplyRangedSocket(socket);
            }
        }
        thing.sockets.RemoveAll((int s) => s == 0);
        for (int i = 0; i < num; i++)
        {
            thing.sockets.Add(0);
        }
        void ApplyRangedSocket(string socket)
        {
            int num2 = 3 + Mathf.Min(thing.genLv / 10, 15);
            if (!EClass.sources.elements.alias.TryGetValue(socket, out var value4))
            {
                ModUtil.LogModError("source thing row '" + base.ContentId + "' has invalid addSocket spec '" + socket + "'", base.Owner);
            }
            else
            {
                float num3 = Mathf.Sqrt((float)(thing.genLv * value4.encFactor) / 100f);
                float num4 = (float)num2 + num3;
                int num5 = (value4.mtp + EClass.rnd(value4.mtp + (int)num4)) / value4.mtp;
                if (value4.encFactor == 0 && num5 > 25)
                {
                    num5 = 25;
                }
                thing.ApplySocket(value4.id, num5);
            }
        }
    }
References BaseCore.actionsNextFrame, EClass.core, SourceManager.elements, Card.GetBool(), Card.id, item, mapInt, mapStr, noCopy, noRandomSocket, num, rarity, EClass.rnd(), Card.SetBool(), Card.SetStr(), sockets, and EClass.sources.
ToString()
override string CustomThingContent.ToString () inline
Definition at line 312 of file CustomThingContent.cs.
    {
        StringBuilder stringBuilder = new StringBuilder();
        stringBuilder.AppendLine($"{base.ContentId}/{type}/{base.Owner.id}");
        stringBuilder.AppendLine($" - num({num})/lv({lv})/restock({restock})/noCopy({noCopy})/{material}/{rarity}/{blessedState}/{identifyLevel}");
        if (sockets.Count > 0)
        {
            stringBuilder.AppendLine($" - sockets({sockets.Count})/noRandomSocket({noRandomSocket})/{string.Join(';', sockets)}");
        }
        if (mapStr.Count > 0)
        {
            stringBuilder.AppendLine(" - str/" + string.Join(';', mapStr.Select((KeyValuePair<string, string> kv) => kv.Key + "=" + kv.Value)));
        }
        if (mapInt.Count > 0)
        {
            stringBuilder.AppendLine(" - int/" + string.Join(';', mapInt.Select((KeyValuePair<string, int> kv) => $"{kv.Key}={kv.Value}")));
        }
        return stringBuilder.ToString();
    }
References $, mapInt, mapStr, and sockets.
Member Data Documentation
blessedState
BlessedState CustomThingContent.blessedState
Definition at line 37 of file CustomThingContent.cs.
Referenced by Create().
id
string CustomThingContent.id = ""
Definition at line 39 of file CustomThingContent.cs.
identifyLevel
IDTLevel CustomThingContent.identifyLevel
Definition at line 42 of file CustomThingContent.cs.
Referenced by Create().
lv
int CustomThingContent.lv = -1
Definition at line 44 of file CustomThingContent.cs.
Referenced by Create().
mapInt
Dictionary<string, int> CustomThingContent.mapInt = new Dictionary<string, int>()
Definition at line 46 of file CustomThingContent.cs.
Referenced by CreateFromRow(), OnThingCreated(), and ToString().
mapStr
Dictionary<string, string> CustomThingContent.mapStr = new Dictionary<string, string>()
Definition at line 48 of file CustomThingContent.cs.
Referenced by CreateFromRow(), OnThingCreated(), and ToString().
material
string CustomThingContent.material = ""
Definition at line 50 of file CustomThingContent.cs.
Referenced by Create().
noCopy
bool CustomThingContent.noCopy
Definition at line 52 of file CustomThingContent.cs.
Referenced by OnThingCreated().
noRandomSocket
bool CustomThingContent.noRandomSocket
Definition at line 54 of file CustomThingContent.cs.
Referenced by OnThingCreated().
num
int CustomThingContent.num = 1
Definition at line 56 of file CustomThingContent.cs.
Referenced by Create(), and OnThingCreated().
priceCalc
string CustomThingContent.priceCalc = ""
Definition at line 69 of file CustomThingContent.cs.
Referenced by Create().
rarity
Rarity CustomThingContent.rarity
Definition at line 59 of file CustomThingContent.cs.
Referenced by Create(), and OnThingCreated().
restock
bool CustomThingContent.restock = true
Definition at line 62 of file CustomThingContent.cs.
Referenced by Create().
sockets
List<string> CustomThingContent.sockets = new List<string>()
Definition at line 64 of file CustomThingContent.cs.
Referenced by CreateFromRow(), OnThingCreated(), and ToString().
type
SpawnType CustomThingContent.type
Definition at line 67 of file CustomThingContent.cs.
Referenced by Create().
Property Documentation
SourceType
override string CustomThingContent.SourceType get
Definition at line 71 of file CustomThingContent.cs.
The documentation for this class was generated from the following file:
Elin/CustomThingContent.cs