Elin Decompiled Documentation: ListPeopleParty Class Reference
ListPeopleParty Class Reference
Public Member Functions
bool CanJoinParty (Chara c)
override void OnRefreshMenu ()
override void OnInstantiate (Chara c, ItemGeneral i)
override void OnClick (Chara c, ItemGeneral i)
void JoinParty (Chara c)
override void OnList ()
HireInfo GetInfo (Chara c)
Public Member Functions inherited from BaseListPeople
virtual bool IsDisabled (Chara c)
override void List ()
override void OnInstantiate (Chara a, ItemGeneral b)
void AddSubButtonWork (ItemGeneral b, Chara a)
void WriteHobbies (UITooltip t, Chara a, BaseArea roomWork)
virtual void SetSubText (Chara a, ItemGeneral b)
override void OnClick (Chara c, ItemGeneral i)
override void OnList ()
override void OnRefreshMenu ()
Public Member Functions inherited from ListOwner< Chara, ItemGeneral >
virtual void OnClick (T1 a, T2 b)
virtual void OnInstantiate (T1 a, T2 b)
virtual void OnList ()
virtual void List ()
virtual void OnCreate ()
virtual void OnSwitchContent ()
void RefreshCaption ()
virtual void OnRefreshMenu ()
void RefreshTab ()
void MoveToOther (object c)
void RefreshAll (bool freeze=true)
Additional Inherited Members
Static Public Member Functions inherited from EClass
static int rndSeed (int a, int seed)
static int rnd (long a)
static int rnd (int a)
static int curve (long _a, int start, int step, int rate=75)
static int sqrt (int a)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Public Attributes inherited from BaseListPeople
Chara owner
FactionMemberType memberType
Public Attributes inherited from ListOwner< Chara, ItemGeneral >
Layer layer
Window window
UIMultiList multi
ListOwner other
UIDynamicList list
WindowMenu menu
Window.Setting.Tab tab
string textTab
string textHeader
bool main
int index
Func< string > funcHeader
Static Public Attributes inherited from EClass
static Core core
Properties inherited from BaseListPeople
new LayerPeople layer [get]
override string IdHeaderRow [get]
virtual bool ShowCharaSheet [get]
virtual bool ShowShowMode [get]
virtual LayerPeople.ShowMode ShowMode [get]
virtual bool ShowGoto [get]
virtual bool ShowHome [get]
Properties inherited from ListOwner< Chara, ItemGeneral >
ListOwner Main [get]
virtual string IdTitle [get]
virtual string IdHeaderRow [get]
virtual string TextTab [get]
virtual string TextHeader [get]
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Detailed Description
Definition at line 3 of file ListPeopleParty.cs.
Member Function Documentation
CanJoinParty()
bool ListPeopleParty.CanJoinParty (Chara c) inline
Definition at line 5 of file ListPeopleParty.cs.
    {
        if (!c.IsPC)
        {
            if (!c.isDead && !c.HasCondition<ConSuspend>() && c.currentZone != null && c.trait.CanJoinParty)
            {
                return c.trait.CanJoinPartyResident;
            }
            return false;
        }
        return true;
    }
References TraitChara.CanJoinParty, TraitChara.CanJoinPartyResident, Chara.currentZone, Chara.HasCondition(), Chara.isDead, Chara.IsPC, and Chara.trait.
Referenced by OnRefreshMenu().
GetInfo()
HireInfo ListPeopleParty.GetInfo (Chara c) inline
Definition at line 203 of file ListPeopleParty.cs.
    {
        return EClass.Home.listReserve.First((HireInfo a) => a.chara == c);
    }
References HireInfo.chara, EClass.Home, and Faction.listReserve.
JoinParty()
void ListPeopleParty.JoinParty (Chara c) inline
Definition at line 173 of file ListPeopleParty.cs.
    {
        if (c.currentZone != EClass._zone)
        {
            c.MoveZone(EClass._zone);
            c.MoveImmediate(EClass.pc.pos.GetNearestPoint(allowBlock: false, allowChara: false) ?? EClass.pc.pos);
        }
        EClass.pc.party.AddMemeber(c);
    }
References EClass._zone, Party.AddMemeber(), Chara.currentZone, Point.GetNearestPoint(), Card.MoveImmediate(), Chara.MoveZone(), Chara.party, EClass.pc, and Card.pos.
Referenced by OnRefreshMenu().
OnClick()
override void ListPeopleParty.OnClick (Chara c, ItemGeneral i) inline
Definition at line 141 of file ListPeopleParty.cs.
    {
        if (main)
        {
            if (!CanJoinParty(c))
            {
                SE.Beep();
                if (!c.trait.CanJoinPartyResident)
                {
                    Msg.Say("ride_req");
                }
                return;
            }
            JoinParty(c);
        }
        else
        {
            if (c.IsPC)
            {
                SE.Beep();
                return;
            }
            EClass.pc.party.RemoveMember(c);
            if (c.homeZone != EClass._zone)
            {
                c.MoveZone(c.homeZone);
            }
        }
        MoveToOther(c);
        base.Main.OnRefreshMenu();
    }
References EClass._zone, TraitChara.CanJoinPartyResident, Chara.homeZone, Chara.IsPC, Chara.MoveZone(), Chara.party, EClass.pc, Party.RemoveMember(), Msg.Say(), and Chara.trait.
OnInstantiate()
override void ListPeopleParty.OnInstantiate (Chara c, ItemGeneral i) inline
Definition at line 124 of file ListPeopleParty.cs.
    {
        Zone zone = (main ? c.currentZone : c.homeZone);
        if (main)
        {
            i.SetSubText((zone == null) ? "???" : zone.Name, 240);
        }
        UIButton uIButton = i.AddSubButton(EClass.core.refs.icons.fav, delegate
        {
            SE.ClickGeneral();
            c.isFav = !c.isFav;
            RefreshAll();
        }, null, null, "fav");
        uIButton.icon.SetAlpha(c.isFav ? 1f : 0.3f);
        uIButton.icon.SetNativeSize();
    }
References ItemGeneral.AddSubButton(), EClass.core, CoreRef.Icons.fav, Chara.homeZone, CoreRef.icons, Card.isFav, ListOwner< Chara, ItemGeneral >.main, Spatial.Name, ListOwner< Chara, ItemGeneral >.RefreshAll(), Core.refs, and ItemGeneral.SetSubText().
OnList()
override void ListPeopleParty.OnList () inline virtual
Reimplemented from BaseListPeople.
Definition at line 183 of file ListPeopleParty.cs.
    {
        if (main)
        {
            foreach (Chara value in EClass.game.cards.globalCharas.Values)
            {
                if (value.IsPCFaction && !value.IsPCParty && value.memberType == FactionMemberType.Default)
                {
                    list.Add(value);
                }
            }
            return;
        }
        foreach (Chara member in EClass.pc.party.members)
        {
            list.Add(member);
        }
        list.sortMode = UIList.SortMode.ByPartyOrder;
    }
References Game.cards, EClass.game, CardManager.globalCharas, Chara.IsPCFaction, Chara.IsPCParty, Party.members, Chara.memberType, Chara.party, and EClass.pc.
OnRefreshMenu()
override void ListPeopleParty.OnRefreshMenu () inline virtual
Reimplemented from BaseListPeople.
Definition at line 18 of file ListPeopleParty.cs.
    {
        base.OnRefreshMenu();
        if (!main)
        {
            return;
        }
        WindowMenu menuLeft = window.menuLeft;
        menuLeft.AddSpace();
        menuLeft.AddHeader("party");
        menuLeft.AddSpace(13f);
        if (EClass.pc.party.members.Count > 1)
        {
            menuLeft.AddButton("disband", delegate
            {
                EClass.pc.party.Disband();
                SE.Trash();
                RefreshAll();
            });
        }
        for (int j = 0; j < 5; j++)
        {
            int i = j;
            Player.PartySetup setup = EClass.player.partySetups[i];
            if (setup == null)
            {
                menuLeft.AddButton("party_empty".lang((i + 1).ToString() ?? ""), delegate
                {
                    if (EClass.pc.party.members.Count == 1)
                    {
                        SE.Beep();
                    }
                    else
                    {
                        SE.Equip();
                        EClass.pc.party.RegisterSetup(i);
                        RefreshAll();
                    }
                });
                continue;
            }
            UIButton uIButton = menuLeft._AddButton("Party", null);
            uIButton.SetOnClick(delegate
            {
                EClass.pc.party.Disband();
                foreach (int uid in setup.uids)
                {
                    Chara chara3 = EClass.game.cards.globalCharas.Find(uid);
                    if (chara3 != null && !chara3.IsPC && CanJoinParty(chara3))
                    {
                        JoinParty(chara3);
                        if (chara3.uid == setup.ride)
{
                            ActRide.Ride(EClass.pc, chara3, parasite: false, talk: false);
                        }
                        else if (chara3.uid == setup.parasite)
{
                            ActRide.Ride(EClass.pc, chara3, parasite: true, talk: false);
                        }
                    }
                }
                SE.Equip();
                RefreshAll();
            });
            bool flag = true;
            foreach (int uid2 in setup.uids)
            {
                Chara chara = EClass.game.cards.globalCharas.Find(uid2);
                if (chara == null || !CanJoinParty(chara))
                {
                    flag = false;
                }
            }
            uIButton.mainText.SetText("party_load".lang((i + 1).ToString() ?? ""), flag ? FontColor.Good : FontColor.Warning);
            uIButton.SetTooltip(delegate(UITooltip n)
            {
                n.note.Clear();
                n.note.AddHeader("faction_Member");
                foreach (int uid3 in setup.uids)
                {
                    Chara chara2 = EClass.game.cards.globalCharas.Find(uid3);
                    string text = ((chara2 == null) ? "???" : chara2.NameBraced);
                    if (chara2 != null)
                    {
                        if (chara2.uid == setup.ride)
{
                            text = text + " " + "party_ride".lang();
                        }
                        else if (chara2.uid == setup.parasite)
{
                            text = text + " " + "party_parasite".lang();
                        }
                    }
                    n.note.AddText(text, (chara2 == null || chara2.isDead) ? FontColor.Bad : ((!CanJoinParty(chara2)) ? FontColor.Warning : FontColor.Good));
                }
                n.note.Build();
            });
            uIButton.GetComponentInDirectChildren<UIButton>().SetOnClick(delegate
            {
                SE.Trash();
                EClass.player.partySetups[i] = null;
                RefreshAll();
            });
        }
    }
References WindowMenu._AddButton(), WindowMenu.AddButton(), WindowMenu.AddHeader(), UINote.AddHeader(), WindowMenu.AddSpace(), UINote.AddText(), UINote.Build(), CanJoinParty(), Game.cards, UINote.Clear(), Party.Disband(), CardManager.GlobalCharaList.Find(), EClass.game, CardManager.globalCharas, Chara.isDead, Chara.IsPC, JoinParty(), ListOwner< Chara, ItemGeneral >.main, Party.members, Window.menuLeft, Chara.NameBraced, UITooltip.note, Player.PartySetup.parasite, Chara.party, Player.partySetups, EClass.pc, EClass.player, ListOwner< Chara, ItemGeneral >.RefreshAll(), Party.RegisterSetup(), ActRide.Ride(), Player.PartySetup.ride, Card.uid, Player.PartySetup.uids, and ListOwner< Chara, ItemGeneral >.window.
The documentation for this class was generated from the following file:
Elin/ListPeopleParty.cs