Elin Decompiled Documentation: Int3 Class Reference
Int3 Class Reference
Public Member Functions
Int3 ()
Int3 (int _x, int _y, int _z)
Int3 (float _x, float _y, float _z)
void Set (int _x, int _y, int _z)
void Set (float _x, float _y, float _z)
Public Attributes
int[] i = new int[3]
Properties
int x [get, set]
int y [get, set]
int z [get, set]
Detailed Description
Definition at line 1 of file Int3.cs.
Constructor & Destructor Documentation
Int3() [1/3]
Int3.Int3 () inline
Definition at line 41 of file Int3.cs.
    {
    }
Int3() [2/3]
Int3.Int3 (int _x, int _y, int _z) inline
Definition at line 45 of file Int3.cs.
    {
        Set(_x, _y, _z);
    }
References Set().
Int3() [3/3]
Int3.Int3 (float _x, float _y, float _z) inline
Definition at line 50 of file Int3.cs.
    {
        Set(_x, _y, _z);
    }
References Set().
Member Function Documentation
Set() [1/2]
void Int3.Set (float _x, float _y, float _z) inline
Definition at line 62 of file Int3.cs.
    {
        i[0] = (int)_x;
        i[1] = (int)_y;
        i[2] = (int)_z;
    }
References i.
Set() [2/2]
void Int3.Set (int _x, int _y, int _z) inline
Definition at line 55 of file Int3.cs.
    {
        i[0] = _x;
        i[1] = _y;
        i[2] = _z;
    }
References i.
Referenced by Int3().
Member Data Documentation
i
int [] Int3.i = new int[3]
Definition at line 3 of file Int3.cs.
Referenced by Set().
Property Documentation
x
int Int3.x get set
Definition at line 5 of file Int3.cs.
    {
        get
        {
            return i[0];
        }
        set
        {
            i[0] = value;
        }
    }
Referenced by BaseGameScreen.Focus().
y
int Int3.y get set
Definition at line 17 of file Int3.cs.
    {
        get
        {
            return i[1];
        }
        set
        {
            i[1] = value;
        }
    }
Referenced by BaseGameScreen.Focus().
z
int Int3.z get set
Definition at line 29 of file Int3.cs.
    {
        get
        {
            return i[2];
        }
        set
        {
            i[2] = value;
        }
    }
Referenced by BaseGameScreen.Focus().
The documentation for this class was generated from the following file:
Elin/Int3.cs