Elin Decompiled Documentation: RenderDataEffect Class Reference
RenderDataEffect Class Reference
Public Member Functions
new void Draw (RenderParam p, int tile=0)
Public Member Functions inherited from RenderData
virtual CardActor CreateActor ()
void Init ()
virtual void OnInit ()
int ConvertTile (int tile)
void RenderToRenderCam (RenderParam p)
void Draw (RenderParam p, int tile)
virtual void Draw (RenderParam p)
void DrawRepeatTo (RenderParam p, float maxY, float height, ref Vector3 peakFix, bool skipFirst=false, int fire=0, bool isBlock=false)
void DrawRepeat (RenderParam p, int count, float size, bool skipFirst=false)
virtual void DrawWithRotation (RenderParam p, float angle)
virtual void DrawShadow (RenderParam p)
void RenderToRenderCam (RenderParam p)
void Draw (RenderParam p)
Public Attributes
float speed
Public Attributes inherited from RenderData
int idShadow
MeshPass pass
Vector3 offset
Vector3 offsetBack
Vector3 offsetShadow
Vector3 heldPos
Vector2 imagePivot = new Vector2(0.5f, 0.25f)
Vector2 imageScale = new Vector2(1f, 1f)
Vector2 size
bool multiSize
bool animate
bool useOffsetBack
bool persistActor
bool symmetry = true
float hangedFixZ
float stackZ
SubPassData subCrate
SourcePref shadowPref
RenderData subData
bool initialized
bool hasSubPass
bool hasSnowPass
Additional Inherited Members
Static Public Member Functions inherited from EScriptable
static int rnd (int a)
Static Public Attributes inherited from RenderData
const int HeldLightMod = 1572864
static Quaternion deadRotation = Quaternion.Euler(0f, 0f, 90f)
static GameSetting.RenderSetting renderSetting
Protected Attributes inherited from RenderData
Vector3 _offset
Properties inherited from RenderData
static Quaternion shadowRotation [get]
static Vector3 shadowScale [get]
static Vector3 shadowOffset [get]
virtual bool SkipOnMap [get]
virtual string pathSprite [get]
virtual string prefabName [get]
virtual bool ForceAltHeldPosition [get]
Detailed Description
Definition at line 3 of file RenderDataEffect.cs.
Member Function Documentation
Draw()
new void RenderDataEffect.Draw (RenderParam p, int tile = 0) inline
Definition at line 7 of file RenderDataEffect.cs.
    {
        float num = (Time.realtimeSinceStartup * speed + p.x + p.y) % 5f;
        MeshBatch meshBatch = pass.batches[pass.batchIdx];
        meshBatch.matrices[pass.idx].m03 = p.x + offset.x;
        meshBatch.matrices[pass.idx].m13 = p.y + offset.y;
        meshBatch.matrices[pass.idx].m23 = p.z + offset.z;
        meshBatch.tiles[pass.idx] = num;
        meshBatch.colors[pass.idx] = p.color;
        pass.idx++;
        if (pass.idx == pass.batchSize)
        {
            pass.NextBatch();
        }
    }
References MeshPass.batches, MeshPass.batchIdx, MeshPass.batchSize, MeshPassParam.color, MeshBatch.colors, MeshPass.idx, MeshBatch.matrices, MeshPass.NextBatch(), RenderData.offset, RenderData.pass, speed, MeshBatch.tiles, and MeshPassParam.y.
Referenced by RenderData.DrawRepeatTo(), BaseTileMap.DrawRoof(), BaseTileMap.DrawTile(), and TileMapElona.DrawTile().
Member Data Documentation
speed
float RenderDataEffect.speed
Definition at line 5 of file RenderDataEffect.cs.
Referenced by Draw().
The documentation for this class was generated from the following file:
Elin/RenderDataEffect.cs