Elin Decompiled Documentation: CardInspector Class Reference
CardInspector Class Reference
Public Member Functions
void SetCard (Card c, bool select=true)
Public Attributes
Card card
List< EditorTag > tags = new List<EditorTag>()
string traitVals
Static Public Attributes
static CardInspector Instance
Static Public Attributes inherited from EMono
static Core core
Protected Member Functions
IEnumerable< string > _SpawnList ()
Properties
string Info [get]
string idEditor [get, set]
string trait [get, set]
string BGM [get, set]
bool IsTape [get]
string spawnList [get, set]
Properties inherited from EMono
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SoundManager Sound [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static CoreDebug debug [get]
Private Member Functions
IEnumerable< string > _TapeList ()
IEnumerable< string > Traits ()
IEnumerable< Type > GetInheritedClasses (Type MyType, Type exclude=null)
void Awake ()
void OnValidate ()
Additional Inherited Members
Static Public Member Functions inherited from EMono
static int rnd (int a)
Detailed Description
Definition at line 7 of file CardInspector.cs.
Member Function Documentation
_SpawnList()
IEnumerable< string > CardInspector._SpawnList () inline protected
Definition at line 137 of file CardInspector.cs.
    {
        return EMono.editorSources.spawnLists.GetListString();
    }
References EMono.editorSources, and SourceManager.spawnLists.
_TapeList()
IEnumerable< string > CardInspector._TapeList () inline private
Definition at line 109 of file CardInspector.cs.
    {
        List<string> list = new List<string>();
        foreach (BGMData bgm in EMono.core.refs.bgms)
        {
            list.Add(bgm.name);
        }
        return list;
    }
References CoreRef.bgms, EMono.core, and Core.refs.
Awake()
void CardInspector.Awake () inline private
Definition at line 142 of file CardInspector.cs.
    {
        Instance = this;
    }
References Instance.
GetInheritedClasses()
IEnumerable< Type > CardInspector.GetInheritedClasses (Type MyType, Type exclude = null) inline private
Definition at line 130 of file CardInspector.cs.
    {
        return from TheType in Assembly.GetAssembly(MyType).GetTypes()
            where TheType.IsClass && TheType.IsSubclassOf(MyType) && (exclude == null || !TheType.IsSubclassOf(exclude))
            select TheType;
    }
Referenced by Traits().
OnValidate()
void CardInspector.OnValidate () inline private
Definition at line 169 of file CardInspector.cs.
    {
        if (!Application.isPlaying || !EMono.core.IsGameStarted || card == null)
        {
            return;
        }
        string text = null;
        bool flag = true;
        if (tags != null)
        {
            foreach (EditorTag tag in tags)
            {
                text = text + (flag ? "" : ",") + tag;
                flag = false;
            }
        }
        card.c_editorTags = text;
        card.c_editorTraitVal = (traitVals.IsEmpty() ? null : traitVals);
    }
References card, EMono.core, Core.IsGameStarted, tags, and traitVals.
SetCard()
void CardInspector.SetCard (Card c, bool select = true) inline
Definition at line 147 of file CardInspector.cs.
    {
        card = c;
        tags.Clear();
        if (c != null && !c.c_editorTags.IsEmpty())
        {
            string[] array = c.c_editorTags.Split(',');
            foreach (string text in array)
            {
                try
                {
                    tags.Add(text.ToEnum<EditorTag>());
                }
                catch
                {
                    Debug.Log("No Editor Tag Found:" + text);
                }
            }
        }
        traitVals = c.c_editorTraitVal;
    }
References Card.c_editorTags, Card.c_editorTraitVal, card, Debug, tags, and traitVals.
Referenced by AM_EditMarker.OnProcessTiles().
Traits()
IEnumerable< string > CardInspector.Traits () inline private
Definition at line 119 of file CardInspector.cs.
    {
        IEnumerable<Type> obj = ((card == null || !card.isChara) ? GetInheritedClasses(typeof(Trait), typeof(TraitChara)) : GetInheritedClasses(typeof(TraitChara)));
        List<string> list = new List<string> { "" };
        foreach (Type item in obj)
        {
            list.Add(item.Name);
        }
        return list;
    }
References card, GetInheritedClasses(), Card.isChara, and item.
Member Data Documentation
card
Card CardInspector.card
Definition at line 11 of file CardInspector.cs.
Referenced by OnValidate(), SetCard(), and Traits().
Instance
CardInspector CardInspector.Instance static
Definition at line 9 of file CardInspector.cs.
Referenced by Awake(), and AM_EditMarker.OnProcessTiles().
tags
List<EditorTag> CardInspector.tags = new List<EditorTag>()
Definition at line 13 of file CardInspector.cs.
Referenced by OnValidate(), and SetCard().
traitVals
string CardInspector.traitVals
Definition at line 15 of file CardInspector.cs.
Referenced by OnValidate(), and SetCard().
Property Documentation
BGM
string CardInspector.BGM get set
Definition at line 59 of file CardInspector.cs.
    {
        get
        {
            if (card == null || card.refVal == 0)
            {
                return "0";
            }
            BGMData bGMData = EMono.core.refs.bgms.FirstOrDefault((BGMData a) => a.id == card.refVal);
            if (!(bGMData == null))
            {
                return bGMData.name;
            }
            return "0";
        }
        set
        {
            if (card != null)
            {
                card.refVal = value.Split(' ')[0].ToInt();
            }
        }
    }
idEditor
string CardInspector.idEditor get set
Definition at line 29 of file CardInspector.cs.
    {
        get
        {
            return card?.c_idEditor;
        }
        set
        {
            if (card != null)
            {
                card.c_idEditor = value;
            }
        }
    }
Info
string CardInspector.Info get
Definition at line 17 of file CardInspector.cs.
    {
        get
        {
            if (card != null)
            {
                return card.id + "(" + card.NameSimple + ")";
            }
            return "";
        }
    }
IsTape
bool CardInspector.IsTape get
Definition at line 83 of file CardInspector.cs.
spawnList
string CardInspector.spawnList get set
Definition at line 85 of file CardInspector.cs.
    {
        get
        {
            if (card == null || card.c_idRefCard.IsEmpty() || !EMono.editorSources.spawnLists.map.ContainsKey(card.c_idRefCard))
            {
                return "-";
            }
            SourceSpawnList.Row row = EMono.editorSources.spawnLists.rows.First((SourceSpawnList.Row a) => a.id == card.c_idRefCard);
            if (row != null)
            {
                return row.id;
            }
            return "-";
        }
        set
        {
            if (card != null)
            {
                card.c_idRefCard = value;
            }
        }
    }
trait
string CardInspector.trait get set
Definition at line 44 of file CardInspector.cs.
    {
        get
        {
            return card?.c_idTrait;
        }
        set
        {
            if (card != null)
            {
                card.c_idTrait = value;
            }
        }
    }
The documentation for this class was generated from the following file:
Elin/CardInspector.cs