Elin Decompiled Documentation: TraitDrink Class Reference
TraitDrink Class Reference
Public Member Functions
override bool CanDrink (Chara c)
bool IsBlend ()
override bool CanBlend (Thing t)
override void OnBlend (Thing t, Chara c)
override void OnDrink (Chara c)
override void OnThrowGround (Chara c, Point p)
override Action GetHealAction (Chara c)
Public Member Functions inherited from Trait
string GetParam (int i, string def=null)
int GetParamInt (int i, int def)
virtual bool Contains (RecipeSource r)
virtual int GetValue ()
virtual bool CanStackTo (Thing to)
virtual string GetHoverText ()
virtual Action GetHealAction (Chara c)
virtual bool CanBlend (Thing t)
virtual void OnBlend (Thing t, Chara c)
virtual int GetActDuration (Chara c)
virtual SourceElement.Row GetRefElement ()
virtual Sprite GetRefSprite ()
virtual void OnRenderExtra (RenderParam p)
virtual Emo2 GetHeldEmo (Chara c)
virtual void SetOwner (Card _owner)
virtual bool IdleUse (Chara c, int dist)
virtual void OnSetOwner ()
virtual void OnImportMap ()
virtual void SetParams (params string[] s)
virtual void OnCrafted (Recipe recipe)
virtual void OnCreate (int lv)
virtual void OnEquip (Chara c, bool onSetOwner)
virtual void OnUnequip (Chara c)
virtual void OnChangePlaceState (PlaceState state)
virtual void OnAddedToZone ()
virtual void OnRemovedFromZone ()
virtual void OnSimulateHour (VirtualDate date)
virtual string GetName ()
virtual void SetName (ref string s)
virtual void OnRenderTile (Point point, HitResult result, int dir)
virtual int CompareTo (Card b)
virtual bool CanBuiltAt (Point p)
virtual void Update ()
Point GetPoint ()
Point GetRandomPoint (Func< Point, bool > func=null, Chara accessChara=null)
virtual List< Point > ListPoints (Point center=null, bool onlyPassable=true)
virtual Recipe GetRecipe ()
virtual Recipe GetBuildModeRecipe ()
virtual bool CanCook (Card c)
void CookProgress ()
virtual bool CanOffer (Card tg)
void OfferProcess (Chara cc)
void Offer (Chara cc)
virtual bool TryProgress (AIProgress p)
virtual LockOpenState TryOpenLock (Chara cc, bool msgFail=true)
virtual void WriteNote (UINote n, bool identified)
int GetSortVal (UIList.SortMode m)
virtual HotItem GetHotItem ()
virtual bool CanRead (Chara c)
virtual void OnRead (Chara c)
virtual bool CanEat (Chara c)
virtual void OnEat (Chara c)
virtual bool CanDrink (Chara c)
virtual void OnDrink (Chara c)
virtual void OnThrowGround (Chara c, Point p)
virtual bool CanUse (Chara c)
virtual bool CanUse (Chara c, Card tg)
virtual bool CanUse (Chara c, Point p)
virtual bool OnUse (Chara c)
virtual bool OnUse (Chara c, Card tg)
virtual bool OnUse (Chara c, Point p)
virtual void TrySetAct (ActPlan p)
virtual void TrySetHeldAct (ActPlan p)
virtual void OnHeld ()
virtual void OnTickHeld ()
virtual void OnSetCurrentItem ()
virtual void OnUnsetCurrentItem ()
virtual bool OnChildDecay (Card c, bool firstDecay)
virtual bool CanChildDecay (Card c)
virtual void OnSetCardGrid (ButtonGrid b)
virtual void OnStepped (Chara c)
virtual void OnSteppedOut (Chara c)
virtual void OnOpenDoor (Chara c)
void Install (bool byPlayer)
void Uninstall ()
virtual void OnInstall (bool byPlayer)
virtual void OnUninstall ()
virtual void TryToggle ()
virtual void Toggle (bool on, bool silent=false)
virtual void PlayToggleEffect (bool silent)
virtual void OnToggle ()
virtual void TrySetToggleAct (ActPlan p)
bool IsFuelEnough (int num=1, List< Thing > excludes=null, bool tryRefuel=true)
bool IsFuel (string s)
bool IsFuel (Thing t)
int GetFuelValue (Thing t)
int GetFuelValue (string id)
void Refuel (Thing t)
void TryRefuel (int dest, List< Thing > excludes)
virtual void OnEnterScreen ()
virtual void RefreshRenderer ()
virtual void SetMainText (UIText t, bool hotitem)
virtual bool CanCopy (Thing t)
string GetTextRestock (string lang, bool pet)
Emo2 GetRestockedIcon ()
void OnBarter ()
Thing CreateStock ()
Static Public Member Functions
static void BlendLove (Chara c, Thing t, bool dream=false)
static void BlendPoison (Chara c, Thing t)
Static Public Member Functions inherited from EClass
static int rndSeed (int a, int seed)
static int rnd (int a)
static int curve (int a, int start, int step, int rate=75)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Properties
virtual EffectId IdEffect [get]
virtual int Power [get]
virtual int IdEle [get]
virtual SourceElement.Row source [get]
virtual string AliasEle [get]
virtual string N1 [get]
virtual bool IsNeg [get]
override bool IsThrowMainAction [get]
override ThrowType ThrowType [get]
override bool IsBlendBase [get]
Properties inherited from Trait
string[] Params [get]
virtual byte WeightMod [get]
virtual int IdSkin [get]
virtual string Name [get]
virtual TileType tileType [get]
virtual RefCardName RefCardName [get]
virtual bool IsBlockPath [get]
virtual bool IsBlockSight [get]
virtual bool IsDoor [get]
virtual bool IsOpenSight [get]
virtual bool IsOpenPath [get]
virtual bool IsFloating [get]
virtual bool IsGround [get]
virtual bool IsOnlyUsableByPc [get]
virtual bool InvertHeldSprite [get]
virtual bool IsChangeFloorHeight [get]
virtual bool ShouldRefreshTile [get]
virtual bool ShouldTryRefreshRoom [get]
virtual int InstallBottomPriority [get]
virtual bool CanHarvest [get]
virtual int radius [get]
virtual TraitRadiusType radiusType [get]
virtual bool CanUseRoomRadius [get]
virtual int GuidePriotiy [get]
virtual int Electricity [get]
virtual bool IgnoreLastStackHeight [get]
virtual int Decay [get]
virtual int DecaySpeed [get]
virtual int DecaySpeedChild [get]
virtual bool IsFridge [get]
virtual int DefaultStock [get]
virtual bool HoldAsDefaultInteraction [get]
virtual int CraftNum [get]
virtual bool ShowOrbit [get]
virtual bool HaveUpdate [get]
virtual bool IsSpot [get]
virtual bool IsFactory [get]
virtual bool CanAutofire [get]
virtual bool CanName [get]
virtual bool CanPutAway [get]
virtual bool CanChangeHeight [get]
virtual bool CanStack [get]
virtual bool CanCopyInBlueprint [get]
virtual bool CanBeAttacked [get]
virtual bool CanExtendBuild [get]
virtual string langNote [get]
virtual string IDInvStyle [get]
virtual string IDActorEx [get]
virtual bool MaskOnBuild [get]
virtual bool ShowContextOnPick [get]
virtual bool IsThrowMainAction [get]
virtual bool LevelAsQuality [get]
virtual bool UseDummyTile [get]
virtual bool RequireFullStackCheck [get]
virtual bool DisableAutoCombat [get]
virtual InvGridSize InvGridSize [get]
virtual bool IsContainer [get]
virtual bool CanUseContent [get]
virtual bool CanSearchContent [get]
virtual bool CanOpenContainer [get]
virtual bool IsSpecialContainer [get]
virtual ContainerType ContainerType [get]
virtual ThrowType ThrowType [get]
virtual EffectDead EffectDead [get]
virtual bool IsHomeItem [get]
virtual bool IsAltar [get]
virtual bool IsRestSpot [get]
virtual bool CanBeMasked [get]
virtual bool IsBlendBase [get]
virtual bool CanBeOnlyBuiltInHome [get]
virtual bool CanBuildInTown [get]
virtual bool CanBeHeld [get]
virtual bool CanBeStolen [get]
virtual bool CanOnlyCarry [get]
virtual bool CanBeDestroyed [get]
virtual bool CanBeSmashedToDeath [get]
virtual bool CanBeHallucinated [get]
virtual bool CanBeDropped [get]
virtual string ReqHarvest [get]
virtual bool CanBeDisassembled [get]
virtual bool CanBeShipped [get]
virtual bool HasCharges [get]
virtual bool ShowCharges [get]
virtual bool ShowChildrenNumber [get]
virtual bool ShowAsTool [get]
virtual bool CanBeHeldAsFurniture [get]
virtual bool HideInAdv [get]
virtual bool NoHeldDir [get]
virtual bool AlwaysHideOnLowWall [get]
bool ExistsOnMap [get]
virtual bool RenderExtra [get]
virtual float DropChance [get]
virtual string IdNoRestock [get]
virtual int IdleUseChance [get]
virtual string RecipeCat [get]
virtual bool IsTool [get]
virtual string LangUse [get]
virtual bool IsOn [get]
virtual bool IsAnimeOn [get]
bool IsToggle [get]
virtual bool AutoToggle [get]
bool IsLighting [get]
virtual bool IsLightOn [get]
virtual bool IsNightOnlyLight [get]
virtual TileMode tileMode [get]
virtual bool UseAltTiles [get]
virtual bool UseLowblock [get]
virtual bool UseExtra [get]
virtual bool UseLightColor [get]
virtual ? Color ColorExtra [get]
virtual int MaxFuel [get]
virtual int FuelCost [get]
virtual bool ShowFuelWindow [get]
bool IsRequireFuel [get]
string IdToggleExtra [get]
virtual ToggleType ToggleType [get]
virtual string IdSoundToggleOn [get]
virtual string IdSoundToggleOff [get]
virtual int ShopLv [get]
virtual CopyShopType CopyShop [get]
virtual int NumCopyItem [get]
virtual ShopType ShopType [get]
virtual CurrencyType CurrencyType [get]
virtual PriceType PriceType [get]
virtual bool AllowSell [get]
virtual int CostRerollShop [get]
virtual bool AllowCriminal [get]
virtual int RestockDay [get]
virtual SlaverType SlaverType [get]
virtual string LangBarter [get]
string TextNextRestock [get]
string TextNextRestockPet [get]
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Additional Inherited Members
Public Types inherited from Trait
enum TileMode {
Default , Door , Illumination , DefaultNoAnime ,
SignalAnime
}
enum CopyShopType { None , Item , Spellbook }
Public Attributes inherited from Trait
Card owner
Static Public Attributes inherited from Trait
static TraitSelfFactory SelfFactory = new TraitSelfFactory()
Static Public Attributes inherited from EClass
static Core core
Static Protected Attributes inherited from Trait
static List< Point > listRadiusPoints = new List<Point>()
Detailed Description
Definition at line 3 of file TraitDrink.cs.
Member Function Documentation
BlendLove()
static void TraitDrink.BlendLove (Chara c, Thing t, bool dream = false) inline static
Definition at line 136 of file TraitDrink.cs.
    {
        Msg.Say("blend_love", t);
        Thing thing = t.Split(1);
        thing.elements.ModBase(dream ? 704 : 703, t.IsBlessed ? 15 : (t.IsCursed ? 5 : 10));
        c.Pick(thing);
    }
References Card.elements, Card.IsBlessed, Card.IsCursed, ElementContainer.ModBase(), Chara.Pick(), Msg.Say(), and Card.Split().
Referenced by TraitDreamBug.OnBlend(), and OnBlend().
BlendPoison()
static void TraitDrink.BlendPoison (Chara c, Thing t) inline static
Definition at line 144 of file TraitDrink.cs.
    {
        Msg.Say("blend_poison", t);
        Thing thing = t.Split(1);
        thing.elements.ModBase(702, t.IsBlessed ? 5 : (t.IsCursed ? 15 : 10));
        c.Pick(thing);
    }
References Card.elements, Card.IsBlessed, Card.IsCursed, ElementContainer.ModBase(), Chara.Pick(), Msg.Say(), and Card.Split().
Referenced by OnBlend().
CanBlend()
override bool TraitDrink.CanBlend (Thing t) inline virtual
Reimplemented from Trait.
Definition at line 64 of file TraitDrink.cs.
    {
        switch (IdEffect)
        {
        case EffectId.Poison:
        case EffectId.Love:
            return t.IsFood;
        case EffectId.Acidproof:
            if (!t.isAcidproof)
            {
                return t.IsEquipmentOrRangedOrAmmo;
            }
            return false;
        case EffectId.DrinkWater:
            if (t.category.ignoreBless != 1 && t.id != "water")
            {
                return t.id != "bucket";
            }
            return false;
        default:
            return false;
        }
    }
References Card.category, Card.id, IdEffect, Card.isAcidproof, Card.IsEquipmentOrRangedOrAmmo, and Card.IsFood.
CanDrink()
override bool TraitDrink.CanDrink (Chara c) inline virtual
Reimplemented from Trait.
Reimplemented in TraitPotionEmpty.
Definition at line 45 of file TraitDrink.cs.
    {
        return true;
    }
GetHealAction()
override Action TraitDrink.GetHealAction (Chara c) inline virtual
Reimplemented from Trait.
Definition at line 194 of file TraitDrink.cs.
    {
        if (IdEffect == EffectId.Heal)
        {
            return delegate
            {
                c.Drink(owner);
            };
        }
        return null;
    }
References Chara.Drink().
IsBlend()
bool TraitDrink.IsBlend () inline
Definition at line 50 of file TraitDrink.cs.
    {
        switch (IdEffect)
        {
        case EffectId.DrinkWater:
        case EffectId.Poison:
        case EffectId.Love:
        case EffectId.Acidproof:
            return true;
        default:
            return false;
        }
    }
References IdEffect.
OnBlend()
override void TraitDrink.OnBlend (Thing t, Chara c) inline virtual
Reimplemented from Trait.
Definition at line 88 of file TraitDrink.cs.
    {
        switch (IdEffect)
        {
        case EffectId.Love:
            BlendLove(c, t);
            break;
        case EffectId.Poison:
            BlendPoison(c, t);
            break;
        case EffectId.Acidproof:
            c.Say("coated", t, c);
            if (t.IsEquipment && owner.blessedState <= BlessedState.Cursed)
            {
                c.Say("blend_curse", t);
                t.ModEncLv(-1);
            }
            else
            {
                t.isAcidproof = true;
            }
            break;
        case EffectId.DrinkWater:
        {
            BlessedState blessedState = owner.blessedState;
            t = t.Split(1);
            if (blessedState >= BlessedState.Blessed)
            {
                Msg.Say("waterBless", t);
                t.SetBlessedState(BlessedState.Blessed);
                c.Pick(t);
            }
            else if (blessedState <= BlessedState.Cursed)
            {
                Msg.Say("waterCurse", t);
                t.SetBlessedState(BlessedState.Cursed);
                c.Pick(t);
            }
            else
            {
                Msg.SayNothingHappen();
            }
            break;
        }
        }
        owner.ModNum(-1);
    }
References BlendLove(), BlendPoison(), Card.blessedState, IdEffect, Card.IsEquipment, Card.ModEncLv(), Card.ModNum(), Trait.owner, Chara.Pick(), Msg.Say(), Card.Say(), Msg.SayNothingHappen(), Card.SetBlessedState(), and Card.Split().
OnDrink()
override void TraitDrink.OnDrink (Chara c) inline virtual
Reimplemented from Trait.
Reimplemented in TraitDrinkMilkMother, and TraitPotionEmpty.
Definition at line 152 of file TraitDrink.cs.
    {
        if (owner.id == "334" && c.HasCondition<ConAwakening>())
        {
            c.RemoveCondition<ConAwakening>();
            return;
        }
        ActEffect.Proc(IdEffect, Power, owner.blessedState, c, null, new ActRef
        {
            n1 = N1,
            isPerfume = (this is TraitPerfume),
            refThing = owner.Thing,
            act = ((source != null) ? ACT.Create(source) : null)
        });
        FoodEffect.ProcTrait(c, owner);
    }
References Card.blessedState, ACT.Create(), Chara.HasCondition(), Card.id, IdEffect, N1, Trait.owner, Power, ActEffect.Proc(), source, and Card.Thing.
OnThrowGround()
override void TraitDrink.OnThrowGround (Chara c, Point p) inline virtual
Reimplemented from Trait.
Definition at line 169 of file TraitDrink.cs.
    {
        if (IdEffect != EffectId.Drink)
        {
            bool isHostileAct = c.IsPCParty && IsNeg;
            EClass._map.SetLiquid(p.x, p.z, new CellEffect
            {
                id = 4,
                idEffect = IdEffect,
                power = Power,
                amount = 5,
                isHostileAct = isHostileAct,
                color = BaseTileMap.GetColorInt(ref owner.GetRandomColor(), owner.sourceRenderCard.colorMod),
                idEle = IdEle,
                n1 = N1,
                isBlessed = (owner.blessedState >= BlessedState.Blessed),
                isCursed = (owner.blessedState <= BlessedState.Cursed)
            });
        }
        else
        {
            EClass._map.SetLiquid(p.x, p.z, 1, 3);
        }
    }
References EClass._map, Map.SetLiquid(), Point.x, and Point.z.
Property Documentation
AliasEle
virtual string TraitDrink.AliasEle get
Definition at line 33 of file TraitDrink.cs.
IdEffect
virtual EffectId TraitDrink.IdEffect get
Definition at line 5 of file TraitDrink.cs.
Referenced by CanBlend(), IsBlend(), OnBlend(), and OnDrink().
IdEle
virtual int TraitDrink.IdEle get
Definition at line 19 of file TraitDrink.cs.
    {
        get
        {
            if (!AliasEle.IsEmpty())
            {
                return EClass.sources.elements.alias[AliasEle].id;
            }
            return 0;
        }
    }
IsBlendBase
override bool TraitDrink.IsBlendBase get
Definition at line 43 of file TraitDrink.cs.
IsNeg
virtual bool TraitDrink.IsNeg get
Definition at line 37 of file TraitDrink.cs.
IsThrowMainAction
override bool TraitDrink.IsThrowMainAction get
Definition at line 39 of file TraitDrink.cs.
N1
virtual string TraitDrink.N1 get
Definition at line 35 of file TraitDrink.cs.
Referenced by OnDrink().
Power
virtual int TraitDrink.Power get
Definition at line 7 of file TraitDrink.cs.
    {
        get
        {
            if (GetParam(2) == null)
            {
                return 100;
            }
            return GetParam(2).ToInt();
        }
    }
Referenced by OnDrink().
source
virtual SourceElement.Row TraitDrink.source get
Definition at line 31 of file TraitDrink.cs.
Referenced by OnDrink().
ThrowType
override ThrowType TraitDrink.ThrowType get
Definition at line 41 of file TraitDrink.cs.
The documentation for this class was generated from the following file:
Elin/TraitDrink.cs