Elin Decompiled Documentation: AM_MoveInstalled Class Reference
AM_MoveInstalled Class Reference
Public Member Functions
override bool IsRoofEditMode (Card c=null)
override HitResult HitResultOnDesignation (Point p)
override bool CanInstaComplete (TaskMoveInstalled t)
override MeshPass GetGuidePass (Point point)
void Activate (Thing t)
override void OnActivate ()
override void OnDeactivate ()
override void OnCreateMold (bool processing)
override HitResult HitTest (Point point, Point start)
void SetTarget (Card _target)
Card GetTarget (Point point)
bool CanPutAway ()
bool TryPutAway ()
bool CheckEnemyNearBy (Card t, Point p, bool msg=true)
override void OnProcessTiles (Point point, int dir)
override void OnRenderTile (Point point, HitResult result, int dir)
override void RotateUnderMouse ()
override void InputWheel (int wheel)
override void OnCancel ()
override void OnFinishProcessTiles ()
Public Member Functions inherited from AM_Designation< TaskMoveInstalled >
virtual bool CanInstaComplete (T t)
virtual bool ForcedInstaComplete (T t)
virtual HitResult HitResultOnDesignation (Point p)
override void OnActivate ()
void CreateNewMold (bool processing=false)
virtual void OnCreateMold (bool processing=false)
override HitResult HitTest (Point point, Point start)
override bool CanProcessTiles ()
override void OnBeforeProcessTiles ()
override void OnProcessTiles (Point point, int dir)
override void OnAfterProcessTiles (Point start, Point end)
override void OnRefreshSummary (Point point, HitResult result, HitSummary summary)
Public Attributes
Card target
Card moldCard
bool onetime
Public Attributes inherited from AM_Designation< TaskMoveInstalled >
TaskList< T > list
T mold
Properties
override int hitW [get]
override int hitH [get]
override int CostMoney [get]
override BaseTileMap.CardIconMode cardIconMode [get]
override bool AllowMiddleClickFunc [get]
bool FreePos [get]
override BaseTileSelector.SelectType selectType [get]
override bool ShouldHideBuildMenu [get]
Properties inherited from AM_Designation< TaskMoveInstalled >
override string idSound [get]
override bool IsBuildMode [get]
Detailed Description
Definition at line 3 of file AM_MoveInstalled.cs.
Member Function Documentation
Activate()
void AM_MoveInstalled.Activate (Thing t) inline
Definition at line 77 of file AM_MoveInstalled.cs.
    {
        Activate();
        SetTarget(t);
        onetime = true;
        EClass.ui.hud.hint.UpdateText();
    }
References Activate(), onetime, SetTarget(), and EClass.ui.
Referenced by Activate(), HotItemActionMode.Execute(), LayerInteraction.GetPage(), AM_Build.OnCancel(), AM_Build.OnFinishProcessTiles(), InspectGroupThing.OnSetActions(), BuildMenu.Toggle(), TraitToolBuild.TrySetHeldAct(), and CoreDebug.UpdateInput().
CanInstaComplete()
override bool AM_MoveInstalled.CanInstaComplete (TaskMoveInstalled t) inline
Definition at line 67 of file AM_MoveInstalled.cs.
    {
        return EClass.player.instaComplete;
    }
References Player.instaComplete, and EClass.player.
CanPutAway()
bool AM_MoveInstalled.CanPutAway () inline
Definition at line 178 of file AM_MoveInstalled.cs.
    {
        if (EClass.debug.ignoreBuildRule)
        {
            return true;
        }
        if (target == null || target.isChara || target.trait.CanOnlyCarry)
        {
            return false;
        }
        return true;
    }
References Trait.CanOnlyCarry, EClass.debug, CoreDebug.ignoreBuildRule, Card.isChara, target, and Card.trait.
Referenced by TryPutAway(), and ActionHint.UpdateText().
CheckEnemyNearBy()
bool AM_MoveInstalled.CheckEnemyNearBy (Card t, Point p, bool msg = true) inline
Definition at line 208 of file AM_MoveInstalled.cs.
    {
        if (t.isChara && !EClass.debug.ignoreBuildRule)
        {
            bool flag = true;
            foreach (Chara chara in EClass._map.charas)
            {
                if (chara.hostility <= Hostility.Enemy && chara.Dist(p) <= 6)
                {
                    flag = false;
                }
            }
            if (!flag)
            {
                if (msg)
                {
                    SE.BeepSmall();
                    EClass.ui.Say("enemyInMap".langGame());
                }
                return true;
            }
        }
        return false;
    }
References EClass._map, Map.charas, EClass.debug, Card.Dist(), Chara.hostility, CoreDebug.ignoreBuildRule, Card.isChara, and EClass.ui.
Referenced by HitTest(), and OnProcessTiles().
GetGuidePass()
override MeshPass AM_MoveInstalled.GetGuidePass (Point point) inline
Definition at line 72 of file AM_MoveInstalled.cs.
    {
        return EClass.screen.guide.passGuideBlock;
    }
References BaseGameScreen.guide, ScreenGuide.passGuideBlock, and EClass.screen.
GetTarget()
Card AM_MoveInstalled.GetTarget (Point point) inline
Definition at line 173 of file AM_MoveInstalled.cs.
    {
        return EClass.scene.mouseTarget.card;
    }
References PointTarget.card, Scene.mouseTarget, and EClass.scene.
Referenced by HitTest(), and OnProcessTiles().
HitResultOnDesignation()
override HitResult AM_MoveInstalled.HitResultOnDesignation (Point p) inline virtual
Reimplemented from AM_Designation< TaskMoveInstalled >.
Definition at line 62 of file AM_MoveInstalled.cs.
    {
        return HitResult.Invalid;
    }
HitTest()
override HitResult AM_MoveInstalled.HitTest (Point point, Point start) inline
Definition at line 103 of file AM_MoveInstalled.cs.
    {
        if (EClass.debug.enable)
        {
            switch (EInput.hotkey)
            {
            case 0:
                EClass._map.SetDecal(point.x, point.z);
                break;
            case 1:
                EClass._map.AddDecal(point.x, point.z, 2);
                break;
            }
        }
        if (target == null)
        {
            if (EClass.scene.mouseTarget.CanCycle())
            {
                return HitResult.Warning;
            }
            if (GetTarget(point) != null)
            {
                return HitResult.Valid;
            }
            return HitResult.Default;
        }
        if (target.isChara && CheckEnemyNearBy(target, point, msg: false))
        {
            return HitResult.Invalid;
        }
        moldCard.ignoreStackHeight = Input.GetKey(KeyCode.LeftControl);
        if (!EClass.debug.ignoreBuildRule)
        {
            if (target.isChara && (point.IsBlocked || point.HasChara))
            {
                return HitResult.Invalid;
            }
            if (!EClass._map.bounds.Contains(point))
            {
                return HitResult.Invalid;
            }
        }
        return base.HitTest(point, start);
    }
References EClass._map, Map.AddDecal(), Map.bounds, PointTarget.CanCycle(), CheckEnemyNearBy(), MapBounds.Contains(), EClass.debug, CoreDebug.enable, GetTarget(), Point.HasChara, EInput.hotkey, CoreDebug.ignoreBuildRule, Point.IsBlocked, Card.isChara, Scene.mouseTarget, EClass.scene, Map.SetDecal(), target, Point.x, and Point.z.
InputWheel()
override void AM_MoveInstalled.InputWheel (int wheel) inline
Definition at line 389 of file AM_MoveInstalled.cs.
    {
        if (!EClass.debug.enable || !EInput.isCtrlDown)
        {
            if (target != null && target.TileType.MaxAltitude > 0)
            {
                moldCard.ChangeAltitude(wheel);
            }
            else if (EClass.scene.mouseTarget.CanCycle())
            {
                EClass.scene.mouseTarget.CycleTarget(wheel);
            }
            else
            {
                base.InputWheel(wheel);
            }
        }
    }
References PointTarget.CanCycle(), PointTarget.CycleTarget(), EClass.debug, CoreDebug.enable, EInput.isCtrlDown, Scene.mouseTarget, and EClass.scene.
IsRoofEditMode()
override bool AM_MoveInstalled.IsRoofEditMode (Card c = null) inline
Definition at line 57 of file AM_MoveInstalled.cs.
    {
        return ActionMode.Build._IsRoofEditMode(target);
    }
References AM_Build._IsRoofEditMode(), ActionMode.Build, and target.
Referenced by OnProcessTiles().
OnActivate()
override void AM_MoveInstalled.OnActivate () inline
Definition at line 85 of file AM_MoveInstalled.cs.
    {
        onetime = false;
        list = base.Designations.moveInstalled;
        target = (moldCard = null);
        base.OnActivate();
    }
References AM_Designation< TaskMoveInstalled >.list, moldCard, onetime, and target.
OnCancel()
override void AM_MoveInstalled.OnCancel () inline
Definition at line 408 of file AM_MoveInstalled.cs.
    {
        if (target != null)
        {
            target = null;
            if (onetime)
            {
                base.OnCancel();
            }
        }
        else
        {
            base.OnCancel();
        }
    }
OnCreateMold()
override void AM_MoveInstalled.OnCreateMold (bool processing) inline virtual
Reimplemented from AM_Designation< TaskMoveInstalled >.
Definition at line 98 of file AM_MoveInstalled.cs.
    {
        mold.target = target;
    }
References target.
OnDeactivate()
override void AM_MoveInstalled.OnDeactivate () inline
Definition at line 93 of file AM_MoveInstalled.cs.
    {
        target = (moldCard = (mold.target = null));
    }
References moldCard, and target.
OnFinishProcessTiles()
override void AM_MoveInstalled.OnFinishProcessTiles () inline
Definition at line 424 of file AM_MoveInstalled.cs.
    {
        if (onetime)
        {
            Deactivate();
        }
    }
OnProcessTiles()
override void AM_MoveInstalled.OnProcessTiles (Point point, int dir) inline
Definition at line 233 of file AM_MoveInstalled.cs.
    {
        if (target == null)
        {
            Card t = GetTarget(point);
            if (CheckEnemyNearBy(t, t.pos))
            {
                return;
            }
            if (t.trait.ShowContextOnPick)
            {
                ActPlan actPlan = new ActPlan
                {
                    pos = point.Copy(),
                    ignoreAddCondition = true,
                    input = ActInput.AllAction,
                    altAction = true
                };
                t.trait.TrySetAct(actPlan);
                if (actPlan.list.Count > 0)
                {
                    UIContextMenu uIContextMenu = EClass.ui.CreateContextMenuInteraction();
                    uIContextMenu.AddButton("move", delegate
                    {
                        SetTarget(t);
                        SE.Click();
                    });
                    foreach (ActPlan.Item i in actPlan.list)
                    {
                        uIContextMenu.AddButton(i.GetTextContext(showName: false), delegate
{
                            i.act.Perform();
                        });
                    }
                    uIContextMenu.Show();
                    return;
                }
            }
            SetTarget(t);
            SE.Click();
        }
        else
        {
            if (CheckEnemyNearBy(target, point))
            {
                return;
            }
            mold.dir = moldCard.dir;
            mold.altitude = moldCard.altitude;
            if (target.isChara)
            {
                target.Chara.orgPos?.Set(point);
            }
            base.OnProcessTiles(point, dir);
            target.ignoreStackHeight = moldCard.ignoreStackHeight;
            target.freePos = moldCard.freePos;
            target.fx = (FreePos ? moldCard.fx : 0f);
            target.fy = (FreePos ? moldCard.fy : 0f);
            if (target.isChara && (bool)EClass.debug)
            {
                foreach (Thing thing in point.Things)
                {
                    if (thing.trait is TraitShackle traitShackle)
                    {
                        traitShackle.Restrain(target.Chara);
                    }
                }
            }
            if (target.isThing)
            {
                bool isRoofItem = target.isRoofItem;
                target.isRoofItem = IsRoofEditMode();
                if (target.isRoofItem)
                {
                    target.SetPlaceState(PlaceState.roaming);
                }
                else if (isRoofItem)
                {
                    target.SetPlaceState(PlaceState.installed);
                }
                if (!target.isRoofItem)
                {
                    target.ForeachPoint(delegate(Point p, bool center)
                    {
                        if (p.IsBlocked && p.HasChara)
{
                            foreach (Chara item in p.ListCharas())
{
                                EClass.pc.Kick(item, ignoreSelf: true, karmaLoss: false, show: false);
                            }
                        }
                    });
                }
            }
            SE.Click();
            if (target.renderer.hasActor)
            {
                target.renderer.RefreshSprite();
            }
            target = null;
        }
    }
References UIContextMenu.AddButton(), Card.altitude, Card.Chara, CheckEnemyNearBy(), Point.Copy(), EClass.debug, Card.dir, Card.ForeachPoint(), FreePos, Card.freePos, GetTarget(), CardRenderer.hasActor, Point.HasChara, Card.ignoreStackHeight, Point.IsBlocked, Card.isChara, IsRoofEditMode(), Card.isRoofItem, Card.isThing, ActPlan.list, moldCard, Chara.orgPos, Card.pos, CardRenderer.RefreshSprite(), Card.renderer, Point.Set(), Card.SetPlaceState(), SetTarget(), UIContextMenu.Show(), Trait.ShowContextOnPick, target, Point.Things, Card.trait, Trait.TrySetAct(), and EClass.ui.
OnRenderTile()
override void AM_MoveInstalled.OnRenderTile (Point point, HitResult result, int dir) inline
Definition at line 336 of file AM_MoveInstalled.cs.
    {
        if (target == null)
        {
            Card card = GetTarget(point);
            if (card != null && card.isThing)
            {
                card.Thing.RenderMarker(point, active: true, result, main: true, -1, useCurrentPosition: true);
            }
            base.OnRenderTile(point, (result != HitResult.Valid) ? result : (EClass.scene.mouseTarget.CanCycle() ? HitResult.Warning : HitResult.Default), dir);
            return;
        }
        if (moldCard == null)
        {
            base.OnRenderTile(point, result, dir);
            return;
        }
        moldCard.SetFreePos(point);
        if (result != HitResult.Valid && result != HitResult.Warning)
        {
            base.OnRenderTile(point, result, dir);
        }
        else
        {
            int desiredDir = target.TileType.GetDesiredDir(point, moldCard.dir);
            if (desiredDir != -1)
            {
                int num2 = (moldCard.dir = desiredDir);
                dir = num2;
            }
            bool flag = !base.tileSelector.multisize || (base.tileSelector.firstInMulti && base.Summary.count == base.Summary.countValid);
            moldCard.RenderMarker(point, active: false, result, flag, -1);
            if (flag)
            {
                target.trait.OnRenderTile(point, result, dir);
            }
        }
        EClass.screen.guide.DrawLine(target.pos.PositionCenter(), point.PositionCenter());
    }
References PointTarget.CanCycle(), card, ScreenGuide.DrawLine(), BaseGameScreen.guide, Scene.mouseTarget, Point.PositionCenter(), EClass.scene, and EClass.screen.
RotateUnderMouse()
override void AM_MoveInstalled.RotateUnderMouse () inline
Definition at line 376 of file AM_MoveInstalled.cs.
    {
        if (target != null)
        {
            SE.Rotate();
            moldCard.Rotate();
        }
        else
        {
            base.RotateUnderMouse();
        }
    }
SetTarget()
void AM_MoveInstalled.SetTarget (Card _target) inline
Definition at line 148 of file AM_MoveInstalled.cs.
    {
        TaskMoveInstalled[] array = EClass._map.tasks.designations.moveInstalled.items.ToArray();
        foreach (TaskMoveInstalled taskMoveInstalled in array)
        {
            if (taskMoveInstalled.target == _target)
            {
                taskMoveInstalled.Destroy();
            }
        }
        target = (mold.target = _target);
        if (target.isThing)
        {
            moldCard = target.Duplicate(1);
            moldCard.placeState = PlaceState.installed;
        }
        else
        {
            moldCard = CharaGen.Create(_target.id);
            moldCard.bio.SetGender(_target.bio.gender);
            moldCard.idSkin = target.idSkin;
        }
        EClass.ui.hud.hint.UpdateText();
    }
References EClass._map, Card.bio, CharaGen.Create(), TaskManager.designations, Task.Destroy(), Card.Duplicate(), Card.idSkin, Card.isThing, moldCard, TaskManager.Designations.moveInstalled, Biography.SetGender(), target, TaskMoveInstalled.target, Map.tasks, and EClass.ui.
Referenced by Activate(), and OnProcessTiles().
TryPutAway()
bool AM_MoveInstalled.TryPutAway () inline
Definition at line 191 of file AM_MoveInstalled.cs.
    {
        if (!CanPutAway())
        {
            return false;
        }
        if (!EClass._map.PutAway(target))
        {
            SE.Beep();
            return false;
        }
        SE.Click();
        target = null;
        EClass.ui.hud.hint.UpdateText();
        return true;
    }
References EClass._map, CanPutAway(), Map.PutAway(), target, and EClass.ui.
Referenced by ActionHint.UpdateText().
Member Data Documentation
moldCard
Card AM_MoveInstalled.moldCard
Definition at line 7 of file AM_MoveInstalled.cs.
Referenced by OnActivate(), OnDeactivate(), OnProcessTiles(), and SetTarget().
onetime
bool AM_MoveInstalled.onetime
Definition at line 9 of file AM_MoveInstalled.cs.
Referenced by Activate(), and OnActivate().
target
Card AM_MoveInstalled.target
Definition at line 5 of file AM_MoveInstalled.cs.
Referenced by CanPutAway(), AM_Inspect.GetHintText(), BaseTileMap.GetThingPosition(), HitTest(), IsRoofEditMode(), OnActivate(), OnCreateMold(), OnDeactivate(), OnProcessTiles(), SetTarget(), and TryPutAway().
Property Documentation
AllowMiddleClickFunc
override bool AM_MoveInstalled.AllowMiddleClickFunc get
Definition at line 49 of file AM_MoveInstalled.cs.
cardIconMode
override BaseTileMap.CardIconMode AM_MoveInstalled.cardIconMode get
Definition at line 47 of file AM_MoveInstalled.cs.
CostMoney
override int AM_MoveInstalled.CostMoney get
Definition at line 35 of file AM_MoveInstalled.cs.
    {
        get
        {
            if (target != null)
            {
                return 0;
            }
            return 0;
        }
    }
FreePos
bool AM_MoveInstalled.FreePos get
Definition at line 51 of file AM_MoveInstalled.cs.
Referenced by OnProcessTiles().
hitH
override int AM_MoveInstalled.hitH get
Definition at line 23 of file AM_MoveInstalled.cs.
    {
        get
        {
            if (target != null)
            {
                return moldCard.H;
            }
            return 1;
        }
    }
hitW
override int AM_MoveInstalled.hitW get
Definition at line 11 of file AM_MoveInstalled.cs.
    {
        get
        {
            if (target != null)
            {
                return moldCard.W;
            }
            return 1;
        }
    }
selectType
override BaseTileSelector.SelectType AM_MoveInstalled.selectType get
Definition at line 53 of file AM_MoveInstalled.cs.
ShouldHideBuildMenu
override bool AM_MoveInstalled.ShouldHideBuildMenu get
Definition at line 55 of file AM_MoveInstalled.cs.
The documentation for this class was generated from the following file:
Elin/AM_MoveInstalled.cs