Elin Decompiled Documentation: CharaAbility Class Reference
CharaAbility Class Reference
Public Member Functions
List< SourceElement.Row > GetRandomAbilityList ()
CharaAbility (Chara _owner)
void Refresh ()
void Add (int id, int chance, bool pt)
void AddRandom ()
void Remove (int id)
Static Public Member Functions
static List< SourceElement.Row > BuildRandomAbilityList (bool adv)
Static Public Member Functions inherited from EClass
static int rndSeed (int a, int seed)
static int rnd (int a)
static int curve (int a, int start, int step, int rate=75)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Public Attributes
Chara owner
ActList list = new ActList()
Static Public Attributes
static List< SourceElement.Row > randomAbilities = new List<SourceElement.Row>()
static List< SourceElement.Row > randomAbilitiesAdv = new List<SourceElement.Row>()
Static Public Attributes inherited from EClass
static Core core
Additional Inherited Members
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Detailed Description
Definition at line 4 of file CharaAbility.cs.
Constructor & Destructor Documentation
CharaAbility()
CharaAbility.CharaAbility (Chara _owner) inline
Definition at line 71 of file CharaAbility.cs.
    {
        owner = _owner;
        Refresh();
    }
References owner, and Refresh().
Member Function Documentation
Add()
void CharaAbility.Add (int id, int chance, bool pt) inline
Definition at line 131 of file CharaAbility.cs.
    {
        if (owner._listAbility == null)
        {
            owner._listAbility = new List<int>();
        }
        owner._listAbility.Add(id * ((!pt) ? 1 : (-1)));
        Refresh();
    }
References Chara._listAbility, owner, and Refresh().
Referenced by DNA.Apply().
AddRandom()
void CharaAbility.AddRandom () inline
Definition at line 141 of file CharaAbility.cs.
    {
        if (owner._listAbility == null)
        {
            owner._listAbility = new List<int>();
        }
        owner._listAbility.Add(GetRandomAbilityList().RandomItemWeighted((SourceElement.Row e) => e.chance).id);
        Refresh();
    }
References Chara._listAbility, GetRandomAbilityList(), owner, and Refresh().
Referenced by Zone.TryGenerateEvolved().
BuildRandomAbilityList()
static List< SourceElement.Row > CharaAbility.BuildRandomAbilityList (bool adv) inline static
Definition at line 14 of file CharaAbility.cs.
    {
        List<SourceElement.Row> list = new List<SourceElement.Row>();
        foreach (SourceElement.Row row in EClass.sources.elements.rows)
        {
            if (row.abilityType.Length == 0 || row.aliasRef == "mold")
            {
                continue;
            }
            switch (row.id)
            {
            case 5000:
            case 5001:
            case 5005:
            case 5040:
            case 5048:
            case 6400:
            case 6410:
            case 8200:
                continue;
            }
            if (row.idMold != 0 && !adv)
            {
                switch (row.aliasRef)
                {
                case "eleEther":
                case "eleAcid":
                case "eleCut":
                case "eleImpact":
                    continue;
                }
            }
            if (!row.tag.Contains("noRandomAbility"))
            {
                list.Add(row);
            }
        }
        return list;
    }
References SourceManager.elements, list, and EClass.sources.
Referenced by GetRandomAbilityList().
GetRandomAbilityList()
List< SourceElement.Row > CharaAbility.GetRandomAbilityList () inline
Definition at line 54 of file CharaAbility.cs.
    {
        if (randomAbilities.Count == 0)
        {
            randomAbilities = BuildRandomAbilityList(adv: false);
        }
        if (randomAbilitiesAdv.Count == 0)
        {
            randomAbilitiesAdv = BuildRandomAbilityList(adv: true);
        }
        if (!(owner.trait is TraitAdventurer))
        {
            return randomAbilities;
        }
        return randomAbilitiesAdv;
    }
References BuildRandomAbilityList(), owner, randomAbilities, randomAbilitiesAdv, and Chara.trait.
Referenced by AddRandom(), and Refresh().
Refresh()
void CharaAbility.Refresh () inline
Definition at line 77 of file CharaAbility.cs.
    {
        list.items.Clear();
        string[] actCombat = owner.source.actCombat;
        for (int i = 0; i < actCombat.Length; i++)
        {
            string[] array = actCombat[i].Split('/');
            list.items.Add(new ActList.Item
            {
                act = ACT.dict[ConvertID(array[0])],
                chance = ((array.Length > 1) ? array[1].ToInt() : 100),
                pt = (array.Length > 2)
            });
        }
        if (owner.trait.MaxRandomAbility > 0 && owner._listAbility == null)
        {
            int num = owner.trait.MaxRandomAbility + EClass.rnd(2) - list.items.Count;
            if (num > 1)
            {
                owner._listAbility = new List<int>();
                for (int j = 0; j < num; j++)
                {
                    owner._listAbility.Add(GetRandomAbilityList().RandomItemWeighted((SourceElement.Row e) => e.chance).id);
                }
            }
        }
        if (owner._listAbility == null)
        {
            return;
        }
        foreach (int item in owner._listAbility)
        {
            string alias = EClass.sources.elements.map[Mathf.Abs(item)].alias;
            list.items.Add(new ActList.Item
            {
                act = ACT.dict[alias],
                chance = 50,
                pt = (item < 0)
            });
        }
        string ConvertID(string s)
        {
            if (owner.MainElement == Element.Void)
            {
                return s;
            }
            if (EClass.sources.elements.alias[s].aliasRef == "mold")
            {
                return s + owner.MainElement.source.alias.Replace("ele", "");
            }
            return s;
        }
    }
References Chara._listAbility, SourceManager.elements, GetRandomAbilityList(), item, ActList.items, list, Chara.MainElement, TraitChara.MaxRandomAbility, owner, EClass.rnd(), Chara.source, Element.source, EClass.sources, Chara.trait, and Element.Void.
Referenced by Add(), AddRandom(), CharaAbility(), and Remove().
Remove()
void CharaAbility.Remove (int id) inline
Definition at line 151 of file CharaAbility.cs.
    {
        owner._listAbility.Remove(id);
        if (owner._listAbility.Count == 0)
        {
            owner._listAbility = null;
        }
        Refresh();
    }
References Chara._listAbility, owner, and Refresh().
Referenced by DNA.Apply().
Member Data Documentation
list
ActList CharaAbility.list = new ActList()
Definition at line 12 of file CharaAbility.cs.
Referenced by GoalCombat.BuildAbilityList(), BuildRandomAbilityList(), Chara.CanInsult(), Chara.GetHoverText2(), DNA.GetInvalidAction(), Refresh(), and AI_Idle.Run().
owner
Chara CharaAbility.owner
Definition at line 10 of file CharaAbility.cs.
Referenced by Add(), AddRandom(), CharaAbility(), GetRandomAbilityList(), Refresh(), and Remove().
randomAbilities
List<SourceElement.Row> CharaAbility.randomAbilities = new List<SourceElement.Row>() static
Definition at line 6 of file CharaAbility.cs.
Referenced by GetRandomAbilityList().
randomAbilitiesAdv
List<SourceElement.Row> CharaAbility.randomAbilitiesAdv = new List<SourceElement.Row>() static
Definition at line 8 of file CharaAbility.cs.
Referenced by GetRandomAbilityList().
The documentation for this class was generated from the following file:
Elin/CharaAbility.cs