Elin Decompiled Documentation: UIMultiList Class Reference
UIMultiList Class Reference
Public Member Functions
void Clear ()
void AddOwner (int i, ListOwner o)
void Build (UIList.SortMode m=UIList.SortMode.ByNone)
void Refresh ()
Public Attributes
List< ListOwner > owners = new List<ListOwner>()
Layer layer
Window[] windows
UIList[] lists
UIHeader[] headers
bool Double
bool addTab
Detailed Description
Definition at line 4 of file UIMultiList.cs.
Member Function Documentation
AddOwner()
void UIMultiList.AddOwner (int i, ListOwner o) inline
Definition at line 25 of file UIMultiList.cs.
    {
        o.index = owners.Count;
        owners.Add(o);
        o.layer = layer;
        o.window = windows[i];
        o.list = lists[i];
        o.multi = this;
        o.main = i == 0;
        if (!Double && addTab)
        {
            o.tab = o.window.AddTab(o.TextTab);
        }
        o.OnCreate();
    }
References Window.AddTab(), addTab, Double, layer, lists, ListOwner< T1, T2 >.OnCreate(), owners, ListOwner< T1, T2 >.TextTab, ListOwner< T1, T2 >.window, and windows.
Referenced by LayerPeople.Create(), LayerPeople.Create< T >(), LayerPeople.CreateBed(), LayerPeople.CreateReserve(), LayerPeople.CreateSelect(), LayerPeople.OnInit(), and LayerEditPlaylist.Refresh().
Build()
void UIMultiList.Build (UIList::SortMode m = UIList::SortMode::ByNone) inline
Definition at line 41 of file UIMultiList.cs.
    {
        foreach (ListOwner owner in owners)
        {
            owner.list.sortMode = m;
        }
        if (Double)
        {
            owners[0].other = owners[1];
            owners[1].other = owners[0];
        }
    }
References Double, and owners.
Referenced by LayerPeople.OnInit(), and LayerEditPlaylist.Refresh().
Clear()
void UIMultiList.Clear () inline
Definition at line 20 of file UIMultiList.cs.
    {
        owners.Clear();
    }
References owners.
Referenced by LayerEditPlaylist.Refresh().
Refresh()
void UIMultiList.Refresh () inline
Definition at line 54 of file UIMultiList.cs.
    {
        foreach (ListOwner owner in owners)
        {
            owner.OnSwitchContent();
        }
    }
References ListOwner< T1, T2 >.OnSwitchContent(), and owners.
Referenced by LayerEditPlaylist.TogglePL().
Member Data Documentation
addTab
bool UIMultiList.addTab
Definition at line 18 of file UIMultiList.cs.
Referenced by AddOwner().
Double
bool UIMultiList.Double
Definition at line 16 of file UIMultiList.cs.
Referenced by AddOwner(), Build(), and LayerPeople.OnSwitchContent().
headers
UIHeader [] UIMultiList.headers
Definition at line 14 of file UIMultiList.cs.
layer
Layer UIMultiList.layer
Definition at line 8 of file UIMultiList.cs.
Referenced by AddOwner().
lists
UIList [] UIMultiList.lists
Definition at line 12 of file UIMultiList.cs.
Referenced by AddOwner().
owners
List<ListOwner> UIMultiList.owners = new List<ListOwner>()
Definition at line 6 of file UIMultiList.cs.
Referenced by LayerEditPlaylist.Activate(), AddOwner(), Build(), Clear(), BaseListPeople.OnClick(), LayerPeople.OnInit(), LayerPeople.OnKill(), LayerEditPlaylist.OnSwitchContent(), LayerPeople.OnSwitchContent(), and Refresh().
windows
Window [] UIMultiList.windows
Definition at line 10 of file UIMultiList.cs.
Referenced by AddOwner().
The documentation for this class was generated from the following file:
Elin/UIMultiList.cs