Elin Decompiled Documentation: CoreDebug Class Reference
CoreDebug Class Reference
Classes
class DebugCommand
class MatColorTest
class StartSetting
Public Types
enum DebugHotkey {
None , Block , Item , Decal ,
Act , Test , Anime
}
enum StartLoadout { New , AllItem , FewItem }
enum StartParty { None , Farris , Full }
enum StartScene {
Title , Zone , Home , Home_Cave ,
Story_Test , MeetFarris , NymelleBoss , AfterNymelle ,
Melilith , Tefra
}
Public Member Functions
void Init ()
void QuickStart ()
void OnLoad ()
void AddAllRecipes ()
void SetStartStockpile (Thing container, int num=100)
Thing GetOrCreateDebugContainer ()
Thing GetDebugContainer ()
void EnableDebugResource ()
void SpawnCheatContainer ()
void UpdateAlways ()
void ValidateData ()
void UpdateInput ()
void InitDebugCommands ()
void Test_Grow ()
void Test_GodTalk ()
void COM_Teleport ()
void COM_PlayStartDrama ()
void Test_Filter ()
void LOG_Spatials ()
void Test_SiegeGuard ()
void Test_Siege ()
void COM_MaxConstruction ()
void Log (object o)
void NextBGM ()
void ToggleRevealMap ()
void LoadBroadcast ()
void BroadcastNext ()
Static Public Member Functions
static bool CheatEnabled ()
static string Cheat ()
static string Fix_RemoveDuplicateUnique ()
static string Fix_EtherDisease ()
static string ListChara ()
static string ListThing ()
static string SetElement (string alias, int value, int potential=100)
static string Spawn (string id, int num=1, string aliasMat="", int objLv=-1)
static string TestSpawn (int lv, int num, int lvRange=-1)
static string ResetPetUpgrades ()
static string GodMode ()
static string ModFame (int amount)
static string ModKarma (int amount)
static string ModContribution (int amount)
static string FlyMode ()
static string RemoveDemitas ()
static string ChangeRace (string id="?")
static string ChangeJob (string id="?")
static string FirstAdventurer ()
static string RegenerateNames ()
static string AllRecipe (bool forget=false)
static string LastWish (string name)
static string ClearLastWishFlag ()
static string Resource ()
Static Public Member Functions inherited from EScriptable
static int rnd (int a)
Public Attributes
StartScene startScene
StartLoadout startLoadout
StartParty startParty
int startHour
StartSetting startSetting
string startZone
bool showSceneSelector
bool skipModSync
Lang.LangCode langCode
bool ignorePool
bool resetPlayerConfig
bool dontUseThread
bool useNewConfig
bool ignoreAutoSave
bool alwaysResetWindow
bool validateData
bool dontCompressSave
bool skipMod
string command
bool debugInput
bool keypadDebug
DebugHotkey debugHotkeys
int advanceMin
bool testLOS
bool testLOS2
bool debugProps
bool revealMap
bool debugHoard
bool revealInner
bool ignorePopup
bool skipEvent
bool skipNerun
bool showTone
bool showExtra
bool test
bool godMode
bool randomResource
bool debugScatter
bool _godBuild
bool godCraft
bool godFood
bool ignoreBuildRule
bool ignoreWeight
bool autoIdentify
bool allAbility
bool allSkill
bool allHomeSkill
bool allArt
bool allBGM
bool ignoreEncounter
bool returnAnywhere
bool instaReturn
bool travelAnywhere
bool hidePCItemsInBuild
bool autoAdvanceQuest
bool enableMapPieceEditor
bool testThingQuality
int numResource
bool unlimitedInterest
bool inviteAnytime
bool marryAnytime
bool showFav
bool alwaysFavFood
bool maxQuests
bool allRecipe
bool allMenu
bool allPolicy
bool allStory
bool skipInitialQuest
bool logAdv
bool logCombat
bool logDice
bool validatePref
int param1
int param2
MatColorTest matColorTest
bool boradcast
bool testFixedColor
Color32 fixedColor
List< DebugCommand > commands = new List<DebugCommand>()
bool enable
Fov fov = new Fov()
Properties
bool godBuild [get]
static string EnableCheat [get]
Private Member Functions
IEnumerable< string > ZoneIDs ()
Private Attributes
readonly List< int[]> resolutions
Card animeDest
int bidx
bool bilinear
string[] blines
int indexResolution
AnimeID lastAnime
Emo lastEmo
bool naked
bool runtimeGodBuild
int ttt
Detailed Description
Definition at line 9 of file CoreDebug.cs.
Member Enumeration Documentation
DebugHotkey
enum CoreDebug.DebugHotkey
Enumerator
None
Block
Item
Decal
Act
Test
Anime
Definition at line 21 of file CoreDebug.cs.
    {
        None,
        Block,
        Item,
        Decal,
        Act,
        Test,
        Anime
    }
StartLoadout
enum CoreDebug.StartLoadout
Enumerator
New
AllItem
FewItem
Definition at line 32 of file CoreDebug.cs.
    {
        New,
        AllItem,
        FewItem
    }
StartParty
enum CoreDebug.StartParty
Enumerator
None
Farris
Full
Definition at line 39 of file CoreDebug.cs.
    {
        None,
        Farris,
        Full
    }
StartScene
enum CoreDebug.StartScene
Enumerator
Title
Zone
Home
Home_Cave
Story_Test
MeetFarris
NymelleBoss
AfterNymelle
Melilith
Tefra
Definition at line 46 of file CoreDebug.cs.
    {
        Title,
        Zone,
        Home,
        Home_Cave,
        Story_Test,
        MeetFarris,
        NymelleBoss,
        AfterNymelle,
        Melilith,
        Tefra
    }
Member Function Documentation
AddAllRecipes()
void CoreDebug.AddAllRecipes () inline
Definition at line 677 of file CoreDebug.cs.
    {
        foreach (RecipeSource item in RecipeManager.list)
        {
            if (!EClass.player.recipes.knownRecipes.ContainsKey(item.id))
            {
                EClass.player.recipes.knownRecipes.Add(item.id, 1);
            }
        }
    }
References RecipeSource.id, RecipeManager.knownRecipes, RecipeManager.list, EClass.player, and Player.recipes.
Referenced by AllRecipe(), EnableDebugResource(), OnLoad(), and QuickStart().
AllRecipe()
static string CoreDebug.AllRecipe (bool forget = false) inline static
Definition at line 2106 of file CoreDebug.cs.
    {
        if (!CheatEnabled())
        {
            return EnableCheat;
        }
        if (forget)
        {
            EClass.player.recipes.knownRecipes.Clear();
        }
        else
        {
            EClass.debug.AddAllRecipes();
        }
        return "Done!";
    }
References AddAllRecipes(), EClass.debug, RecipeManager.knownRecipes, EClass.player, and Player.recipes.
BroadcastNext()
void CoreDebug.BroadcastNext () inline
Definition at line 2192 of file CoreDebug.cs.
    {
        LoadBroadcast();
        if (Input.GetKey(KeyCode.LeftControl))
        {
            bidx--;
        }
        bidx = Mathf.Clamp(bidx, 0, blines.Length - 1);
        string text = blines[bidx];
        bidx += ((!Input.GetKey(KeyCode.LeftShift)) ? 1 : (-1));
        EClass.pc.SayRaw(text.TrimNewLines());
    }
References EClass.pc, and Card.SayRaw().
Referenced by AM_Adv._OnUpdateInput().
ChangeJob()
static string CoreDebug.ChangeJob (string id = "?") inline static
Definition at line 2052 of file CoreDebug.cs.
    {
        if (EClass.sources.jobs.map.ContainsKey(id))
        {
            EClass.pc.ChangeJob(id);
            EClass.player.RefreshDomain();
            return "Done.";
        }
        string text = "";
        foreach (SourceJob.Row row in EClass.sources.jobs.rows)
        {
            text = text + row.id + " " + row.GetName() + Environment.NewLine;
        }
        return text;
    }
References Chara.ChangeJob(), SourceManager.jobs, EClass.pc, EClass.player, Player.RefreshDomain(), and EClass.sources.
ChangeRace()
static string CoreDebug.ChangeRace (string id = "?") inline static
Definition at line 2011 of file CoreDebug.cs.
    {
        if (EClass.sources.races.map.ContainsKey(id))
        {
            Thing thing = null;
            foreach (BodySlot slot in EClass.pc.body.slots)
            {
                if (slot.thing != null)
                {
                    if (slot.thing.blessedState <= BlessedState.Cursed)
                    {
                        slot.thing.blessedState = BlessedState.Normal;
                    }
                    if (slot.thing.trait is TraitToolBelt)
                    {
                        thing = slot.thing;
                    }
                    EClass.pc.body.Unequip(slot);
                }
            }
            EClass.pc.body.RemoveBodyPart(45);
            EClass.pc.body.RemoveBodyPart(44);
            EClass.pc.ChangeRace(id);
            if (EClass.ui.IsInventoryOpen)
            {
                EClass.ui.ToggleInventory();
            }
            EClass.pc.body.AddBodyPart(45);
            EClass.pc.body.AddBodyPart(44);
            EClass.pc.body.Equip(thing);
            return "Done.";
        }
        string text = "";
        foreach (SourceRace.Row row in EClass.sources.races.rows)
        {
            text = text + row.id + " " + row.GetName() + Environment.NewLine;
        }
        return text;
    }
References CharaBody.AddBodyPart(), Card.blessedState, Chara.body, Chara.ChangeRace(), CharaBody.Equip(), EClass.pc, SourceManager.races, CharaBody.RemoveBodyPart(), CharaBody.slots, EClass.sources, BodySlot.thing, Card.trait, EClass.ui, and CharaBody.Unequip().
Cheat()
static string CoreDebug.Cheat () inline static
Definition at line 1780 of file CoreDebug.cs.
    {
        EClass.game.config.cheat = true;
        return "Cheat Enabled";
    }
CheatEnabled()
static bool CoreDebug.CheatEnabled () inline static
Definition at line 1770 of file CoreDebug.cs.
    {
        if (!EClass.debug.enable)
        {
            return EClass.game.config.cheat;
        }
        return true;
    }
References Game.Config.cheat, Game.config, EClass.debug, enable, and EClass.game.
ClearLastWishFlag()
static string CoreDebug.ClearLastWishFlag () inline static
Definition at line 2142 of file CoreDebug.cs.
    {
        if (!CheatEnabled())
        {
            return EnableCheat;
        }
        EClass.player.doneBackers.Clear();
        return Resources.Load<TextAsset>("logo2").text + Environment.NewLine + "Done!";
    }
References Player.doneBackers, and EClass.player.
COM_MaxConstruction()
void CoreDebug.COM_MaxConstruction () inline
Definition at line 1762 of file CoreDebug.cs.
    {
        if (EClass.pc.homeBranch != null)
        {
            EClass.pc.homeBranch.owner.elements.ModBase(2003, 50);
        }
    }
References Zone.elements, Chara.homeBranch, ElementContainer.ModBase(), FactionBranch.owner, and EClass.pc.
COM_PlayStartDrama()
void CoreDebug.COM_PlayStartDrama () inline
Definition at line 1712 of file CoreDebug.cs.
    {
        EClass.ui.CloseLayers();
        EClass.game.world.date.hour = 2;
        EClass.scene.screenElin.RefreshAll();
        LayerDrama.ActivateMain("mono", "1-2");
    }
References LayerDrama.ActivateMain(), BaseGameScreen.RefreshAll(), EClass.scene, Scene.screenElin, and EClass.ui.
COM_Teleport()
void CoreDebug.COM_Teleport () inline
Definition at line 1697 of file CoreDebug.cs.
    {
        for (int i = 0; i < 10000; i++)
        {
            Point point = EClass.pc.pos.Copy();
            point.x += EScriptable.rnd(60) - EScriptable.rnd(60);
            point.z += EScriptable.rnd(60) - EScriptable.rnd(60);
            if (point.IsValid && !point.cell.blocked && point.HasFloor)
            {
                EClass.pc.Teleport(point);
                break;
            }
        }
    }
References Algorithms.WeightCell.blocked, Point.cell, Point.Copy(), Point.HasFloor, Point.IsValid, EClass.pc, Card.pos, EScriptable.rnd(), and Card.Teleport().
EnableDebugResource()
void CoreDebug.EnableDebugResource () inline
Definition at line 746 of file CoreDebug.cs.
    {
        AddAllRecipes();
        EClass.player.flags.OnEnableDebug();
        enable = true;
        if ((bool)WidgetHotbar.HotbarBuild)
        {
            WidgetHotbar.HotbarBuild.RebuildPage();
        }
        WidgetSystemIndicator.Refresh();
        Thing orCreateDebugContainer = GetOrCreateDebugContainer();
        SetStartStockpile(orCreateDebugContainer, numResource);
    }
References AddAllRecipes(), enable, Player.flags, GetOrCreateDebugContainer(), WidgetHotbar.HotbarBuild, numResource, Player.Flags.OnEnableDebug(), EClass.player, WidgetHotbar.RebuildPage(), WidgetSystemIndicator.Refresh(), and SetStartStockpile().
Referenced by BuildMenu.OnActivate(), and UpdateInput().
FirstAdventurer()
static string CoreDebug.FirstAdventurer () inline static
Definition at line 2069 of file CoreDebug.cs.
    {
        string text = "Steam is not running.";
        DateTime dateTime = new DateTime(2024, 11, 3, 6, 0, 0);
        DateTimeOffset dateTimeOffset = (Application.isEditor ? new DateTimeOffset(2024, 11, 6, 1, 9, 0, default(TimeSpan)) : ((!SteamAPI.IsSteamRunning()) ? new DateTimeOffset(9999, 1, 1, 1, 9, 0, default(TimeSpan)) : DateTimeOffset.FromUnixTimeSeconds(SteamApps.GetEarliestPurchaseUnixTime(EClass.core.steam.steamworks.settings.applicationId))));
        dateTimeOffset = dateTimeOffset.ToOffset(new TimeSpan(9, 0, 0));
        text = ((dateTimeOffset < dateTime) ? "Valid: " : "Invalid: ");
        text = text + "Arrived North Tyris on " + dateTimeOffset.Year + " " + dateTimeOffset.Month + "/" + dateTimeOffset.Day + " " + dateTimeOffset.Hour + ":" + dateTimeOffset.Minute;
        return text + "  Eligible by " + dateTime.Year + " " + dateTime.Month + "/" + dateTime.Day + " " + dateTime.Hour + ":" + dateTime.Minute;
    }
References EClass.core, Core.steam, and Steam.steamworks.
Fix_EtherDisease()
static string CoreDebug.Fix_EtherDisease () inline static
Definition at line 1805 of file CoreDebug.cs.
    {
        EClass.pc.ModCorruption(-100000);
        Chara chara = CharaGen.Create("chara");
        chara.ChangeRace(EClass.pc.race.id);
        chara.ChangeJob(EClass.pc.job.id);
        string text = "";
        foreach (Element value in chara.elements.dict.Values)
        {
            if (!(value.source.category != "attribute"))
            {
                Element orCreateElement = EClass.pc.elements.GetOrCreateElement(value.id);
                if (value.vBase > orCreateElement.vBase)
                {
                    text = text + "Fixing Base Value:" + orCreateElement.Name + " Before:" + orCreateElement.vBase + " Now:" + (value.vBase + 1) + Environment.NewLine;
                    EClass.pc.elements.ModBase(orCreateElement.id, value.vBase - orCreateElement.vBase + 1);
                }
            }
        }
        return text + "Fixed!";
    }
References Chara.ChangeJob(), Chara.ChangeRace(), CharaGen.Create(), ElementContainer.dict, Card.elements, ElementContainer.GetOrCreateElement(), Element.id, Chara.job, ElementContainer.ModBase(), Chara.ModCorruption(), EClass.pc, Chara.race, Element.source, and Element.vBase.
Fix_RemoveDuplicateUnique()
static string CoreDebug.Fix_RemoveDuplicateUnique () inline static
Definition at line 1787 of file CoreDebug.cs.
    {
        if (EClass.Branch == null)
        {
            return "No Branch";
        }
        EClass.Branch.members.ForeachReverse(delegate(Chara c)
        {
            if ((c.id == "kettle" || c.id == "quru") && EClass.Branch.members.Where((Chara c2) => c2.id == c.id).Count() >= 2)
            {
                EClass.Branch.RemoveMemeber(c);
                c.Destroy();
            }
        });
        return "Fixed!";
    }
References EClass.Branch, Card.id, and FactionBranch.members.
FlyMode()
static string CoreDebug.FlyMode () inline static
Definition at line 1983 of file CoreDebug.cs.
    {
        EClass.pc.AddCondition<ConLevitate>();
        return "I can fly!";
    }
References Chara.AddCondition(), and EClass.pc.
GetDebugContainer()
Thing CoreDebug.GetDebugContainer () inline
Definition at line 734 of file CoreDebug.cs.
    {
        foreach (Thing thing in EClass._map.things)
        {
            if (thing.c_altName == "DebugContainer")
            {
                return thing;
            }
        }
        return null;
    }
References EClass._map, Card.c_altName, and Map.things.
Referenced by BuildMenu.OnActivate().
GetOrCreateDebugContainer()
Thing CoreDebug.GetOrCreateDebugContainer () inline
Definition at line 717 of file CoreDebug.cs.
    {
        foreach (Thing thing2 in EClass._map.things)
        {
            if (thing2.c_altName == "DebugContainer")
            {
                return thing2;
            }
        }
        Thing thing = EClass._zone.AddThing("barrel", EClass.pc.pos).Thing;
        thing.ChangeMaterial("obsidian");
        thing.c_altName = "DebugContainer";
        thing.isNPCProperty = false;
        thing.SetPlaceState(PlaceState.installed);
        return thing;
    }
References EClass._map, EClass._zone, Zone.AddThing(), Card.c_altName, Card.ChangeMaterial(), EClass.pc, Card.pos, Card.SetPlaceState(), Card.Thing, and Map.things.
Referenced by EnableDebugResource(), and Map.PutAway().
GodMode()
static string CoreDebug.GodMode () inline static
Definition at line 1938 of file CoreDebug.cs.
    {
        if (!CheatEnabled())
        {
            return EnableCheat;
        }
        EClass.pc.Revive();
        EClass.pc.hp = EClass.pc.MaxHP;
        return "I'm God!";
    }
References Chara.MaxHP, EClass.pc, and Chara.Revive().
Init()
void CoreDebug.Init () inline
Definition at line 329 of file CoreDebug.cs.
    {
        InitDebugCommands();
        EInput.disableKeyAxis = Application.isEditor;
    }
References InitDebugCommands().
Referenced by Core.Init().
InitDebugCommands()
void CoreDebug.InitDebugCommands () inline
Definition at line 1398 of file CoreDebug.cs.
    {
        commands.Clear();
        int cat2 = 0;
        Add(cat2, "Save Widgets", delegate
        {
            EClass.ui.widgets.Save();
        });
        Add(cat2, "Save Widgets(Dialog)", delegate
        {
            EClass.ui.widgets.DialogSave();
        });
        Add(cat2, "Export Zone", delegate
        {
            EClass._zone.Export();
        });
        Add(cat2, "Export Zone(Dialog)", delegate
        {
            EClass._zone.ExportDialog();
        });
        Add(0, "Import Zone(Dialog)", delegate
        {
            EClass._zone.ImportDialog();
        });
        Add(cat2, "Validate Backer Contents", delegate
        {
            foreach (SourceBacker.Row row2 in EClass.sources.backers.rows)
            {
                if (row2.valid)
                {
                    switch (row2.type)
                    {
                    case 1:
                        if (!EClass.sources.things.map.ContainsKey(row2.loot))
{
                            Debug.Log(row2.id + "/remain/" + row2.Name + "/" + row2.loot);
                        }
                        break;
                    case 4:
                        if (!EClass.sources.charas.map.ContainsKey(row2.chara))
{
                            Debug.Log(row2.id + "/pet/" + row2.Name + "/" + row2.chara);
                        }
                        break;
                    case 6:
                        if (!EClass.sources.religions.map.ContainsKey(row2.deity.ToLower()))
{
                            Debug.Log(row2.id + "/" + row2.Name + "/follower/" + row2.deity);
                        }
                        break;
                    }
                }
            }
        });
        Add(cat2, "Edit PCC", delegate
        {
            EClass.ui.AddLayer<LayerEditPCC>().Activate(EClass.pc, UIPCC.Mode.Full);
        });
        Add(cat2, "COM_Teleport", COM_Teleport);
        Add(cat2, "LOG_Spatials", LOG_Spatials);
        Add(cat2, "Play Start Drama", COM_PlayStartDrama);
        Add(cat2, "Fix Floating Items", delegate
        {
            foreach (Thing thing in EClass._map.things)
            {
                if (thing.Pref.Float)
                {
                    thing.isFloating = true;
                }
            }
        });
        cat2 = 1;
        Add(cat2, "Add Conditions", delegate
        {
            if (EScriptable.rnd(2) == 0)
            {
                EClass.pc.AddCondition<ConWet>();
            }
            else
            {
                EClass.pc.AddCondition<ConSuffocation>();
            }
            if (EScriptable.rnd(2) == 0)
            {
                EClass.pc.AddCondition<ConPoison>();
            }
            else
            {
                EClass.pc.AddCondition<ConDisease>();
            }
        });
        cat2 = 2;
        Add(cat2, "Max Construction", COM_MaxConstruction);
        Add(cat2, "Add Reserves", delegate
        {
            EClass.Home.AddReserve(CharaGen.Create("merc_archer"));
            EClass.Home.AddReserve(CharaGen.Create("healer"));
            EClass.Home.AddReserve(CharaGen.Create("bartender"));
            EClass.Home.AddReserve(CharaGen.Create("merchant"));
            EClass.Home.AddReserve(CharaGen.CreateFromFilter("c_wilds"));
            EClass.Home.AddReserve(CharaGen.CreateFromFilter("c_wilds"));
            EClass.Home.AddReserve(CharaGen.CreateFromFilter("c_wilds"));
        });
        Add(cat2, "Add Recruits", delegate
        {
            if (EClass.Branch != null)
            {
                EClass.Branch.AddRecruit(CharaGen.Create("merc_archer"));
                EClass.Branch.AddRecruit(CharaGen.Create("healer"));
                EClass.Branch.AddRecruit(CharaGen.Create("bartender"));
                EClass.Branch.AddRecruit(CharaGen.Create("merchant"));
                EClass.Branch.AddRecruit(CharaGen.CreateFromFilter("c_wilds"));
                EClass.Branch.AddRecruit(CharaGen.CreateFromFilter("c_wilds"));
                EClass.Branch.AddRecruit(CharaGen.CreateFromFilter("c_wilds"));
            }
        });
        Add(cat2, "Add Resources", delegate
        {
            if (EClass.Branch != null)
            {
                EClass.Branch.resources.food.Mod(100);
                EClass.Branch.resources.knowledge.Mod(100);
            }
        });
        Add(cat2, "Add Influence", delegate
        {
            EClass._zone.influence += 100;
        });
        Add(cat2, "Reroll Hobbies", delegate
        {
            foreach (Chara chara in EClass._map.charas)
            {
                chara.RerollHobby();
            }
        });
        Add(cat2, "Test_Siege", Test_Siege);
        Add(cat2, "Test_SiegeGuard", Test_SiegeGuard);
        Add(cat2, "Log_BranchMembers", delegate
        {
            if (EClass._zone.IsPCFaction)
            {
                Debug.Log(EClass.Branch.members.Count);
                foreach (Chara member in EClass.Branch.members)
                {
                    EClass.debug.Log(member);
                }
            }
        });
        cat2 = 3;
        Add(cat2, "Weather.Fine", delegate
        {
            EClass.world.weather.SetCondition(Weather.Condition.Fine);
        });
        Add(cat2, "Weather.Blossom", delegate
        {
            EClass.world.weather.SetCondition(Weather.Condition.Blossom);
        });
        Add(cat2, "Weather.Random", delegate
        {
            EClass.world.weather.SetRandomCondition();
        });
        Add(cat2, "Weather.Ether+50", delegate
        {
            EClass.world.ModEther(50);
            Debug.Log(EClass.world.ether + "/" + EClass.world.weather.CurrentCondition);
        });
        Add(cat2, "Season.Next", delegate
        {
            EClass.world.season.Next();
        });
        Add(cat2, "Unreveal Map", delegate
        {
            EClass._map.ForeachCell(delegate(Cell c)
            {
                c.isSeen = false;
            });
            WidgetMinimap.Instance.Reload();
        });
        Add(cat2, "Test_GodTalk", Test_GodTalk);
        Add(cat2, "Test_Filter", Test_Filter);
        Add(cat2, "Test_Grow", Test_Grow);
        Add(cat2, "Turn On All Lights", delegate
        {
            foreach (Thing thing2 in EClass._map.things)
            {
                if (thing2.trait.IsLighting)
                {
                    thing2.trait.Toggle(on: true);
                }
            }
        });
        Add(cat2, "Reset All Custom Lights", delegate
        {
            foreach (Thing thing3 in EClass._map.things)
            {
                thing3.c_lightColor = 0;
                thing3.RecalculateFOV();
            }
        });
        Add(cat2, "Reset All obj materials", delegate
        {
            EClass._map.ForeachCell(delegate(Cell c)
            {
                if (c.HasObj)
                {
                    c.objMat = (byte)c.sourceObj.DefaultMaterial.id;
                }
            });
        });
        Add(cat2, "Fix Floors under Blocks", delegate
        {
            EClass._map.ForeachCell(delegate(Cell c)
            {
                if (c.HasFullBlock)
                {
                    SourceBlock.Row sourceBlock = c.sourceBlock;
                    SourceFloor.Row row = EClass.sources.floors.alias[sourceBlock.autoFloor];
                    EClass._map.SetFloor(c.x, c.z, row.DefaultMaterial.id, row.id);
                }
            });
        });
        Add(cat2, "Bless Inventory", delegate
        {
            EClass.pc.things.Foreach(delegate(Thing t)
            {
                t.SetBlessedState(BlessedState.Blessed);
            });
        });
        Add(cat2, "Curse Inventory", delegate
        {
            EClass.pc.things.Foreach(delegate(Thing t)
            {
                t.SetBlessedState(BlessedState.Cursed);
            });
        });
        Add(cat2, "List Global Charas", delegate
        {
            foreach (KeyValuePair<int, Chara> globalChara in EClass.game.cards.globalCharas)
            {
                Debug.Log(globalChara.Key + "/" + globalChara.Value.Name + "/" + ((globalChara.Value.currentZone == null) ? "NULL" : globalChara.Value.currentZone.Name) + "/" + globalChara.Value.faction?.ToString() + "/" + globalChara.Value.homeBranch);
            }
        });
        Add(cat2, "List Global Charas In Zone", delegate
        {
            foreach (KeyValuePair<int, Chara> globalChara2 in EClass.game.cards.globalCharas)
            {
                if (globalChara2.Value.currentZone == EClass._zone)
                {
                    Debug.Log(globalChara2.Key + "/" + globalChara2.Value);
                }
            }
        });
        Add(cat2, "List Citizen", delegate
        {
            foreach (KeyValuePair<int, string> p in EClass._zone.dictCitizen)
            {
                Debug.Log(p.Value);
                Debug.Log(EClass._map.charas.Find((Chara c) => c.uid == p.Key));
                Debug.Log(EClass._map.deadCharas.Find((Chara c) => c.uid == p.Key));
            }
        });
        void Add(int cat, string id, Action action)
        {
            DebugCommand item = new DebugCommand
            {
                name = id,
                action = action,
                cat = cat
            };
            commands.Add(item);
        }
    }
References EClass._zone, SourceManager.backers, commands, Zone.Export(), Zone.ExportDialog(), Zone.ImportDialog(), EClass.sources, and EClass.ui.
Referenced by Init().
LastWish()
static string CoreDebug.LastWish (string name) inline static
Definition at line 2124 of file CoreDebug.cs.
    {
        string text = "";
        foreach (SourceBacker.Row row in EClass.sources.backers.rows)
        {
            if (row.name.Contains(name) || row.id.ToString() == name)
            {
                text = text + row.id + " valid?:" + row.valid + " lang:" + row.lang + " type:" + row.type + " destroyed:" + EClass.player.doneBackers.Contains(row.id) + " loc:" + (row.loc.IsEmpty() ? "random" : row.loc) + Environment.NewLine;
            }
        }
        if (text == "")
        {
            return "Not Found";
        }
        return text + Resources.Load<TextAsset>("logo2").text;
    }
References SourceManager.backers, Player.doneBackers, EClass.player, and EClass.sources.
ListChara()
static string CoreDebug.ListChara () inline static
Definition at line 1828 of file CoreDebug.cs.
    {
        string text = "";
        foreach (SourceChara.Row row in EClass.sources.charas.rows)
        {
            text = text + row.id + "\n";
        }
        return text;
    }
References SourceManager.charas, and EClass.sources.
ListThing()
static string CoreDebug.ListThing () inline static
Definition at line 1839 of file CoreDebug.cs.
    {
        string text = "";
        foreach (SourceThing.Row row in EClass.sources.things.rows)
        {
            text = text + row.id + "\n";
        }
        return text;
    }
References EClass.sources, and SourceManager.things.
LoadBroadcast()
void CoreDebug.LoadBroadcast () inline
Definition at line 2186 of file CoreDebug.cs.
    {
        TextAsset textAsset = Resources.Load<TextAsset>("Data/Text/broadcast");
        blines = textAsset.text.Split('-');
    }
Log()
void CoreDebug.Log (object o) inline
Definition at line 2163 of file CoreDebug.cs.
    {
        Debug.Log(o);
    }
Referenced by Tutorial.Play().
LOG_Spatials()
void CoreDebug.LOG_Spatials () inline
Definition at line 1730 of file CoreDebug.cs.
    {
        foreach (Spatial child in EClass.world.region.children)
        {
            Debug.Log(child.uid + "/" + child.Name + "/" + child.mainFaction.name + "/" + (child == EClass.player.zone));
        }
    }
References Spatial.children, Spatial.mainFaction, Faction.name, Spatial.Name, EClass.player, World.region, Spatial.uid, EClass.world, and Player.zone.
ModContribution()
static string CoreDebug.ModContribution (int amount) inline static
Definition at line 1972 of file CoreDebug.cs.
    {
        if (!CheatEnabled())
        {
            return EnableCheat;
        }
        Guild.GetCurrentGuild()?.AddContribution(amount);
        return "Done.";
    }
References Faction.AddContribution(), and Guild.GetCurrentGuild().
ModFame()
static string CoreDebug.ModFame (int amount) inline static
Definition at line 1950 of file CoreDebug.cs.
    {
        if (!CheatEnabled())
        {
            return EnableCheat;
        }
        EClass.player.ModFame(amount);
        return "Done.";
    }
References Player.ModFame(), and EClass.player.
ModKarma()
static string CoreDebug.ModKarma (int amount) inline static
Definition at line 1961 of file CoreDebug.cs.
    {
        if (!CheatEnabled())
        {
            return EnableCheat;
        }
        EClass.player.ModKarma(amount);
        return "Done.";
    }
References Player.ModKarma(), and EClass.player.
NextBGM()
void CoreDebug.NextBGM () inline
Definition at line 2168 of file CoreDebug.cs.
    {
        if ((bool)SoundManager.current)
        {
            SoundManager.current.NextBGM();
        }
    }
OnLoad()
void CoreDebug.OnLoad () inline
Definition at line 669 of file CoreDebug.cs.
    {
        if (allRecipe)
        {
            AddAllRecipes();
        }
    }
References AddAllRecipes(), and allRecipe.
Referenced by Game.OnLoad().
QuickStart()
void CoreDebug.QuickStart () inline
Definition at line 335 of file CoreDebug.cs.
    {
        Game.Create("quick");
        Tutorial.debugSkip = EClass.debug.skipNerun;
        if (!startSetting.race.IsEmpty())
        {
            EClass.pc.ChangeRace(startSetting.race);
        }
        if (!startSetting.job.IsEmpty())
        {
            EClass.pc.ChangeJob(startSetting.job);
        }
        switch (startScene)
        {
        case StartScene.Zone:
        case StartScene.Home:
            EClass.game.world.date.hour = EClass.debug.startHour;
            break;
        case StartScene.Home_Cave:
            EClass.game.idPrologue = 2;
            break;
        }
        EClass.game.StartNewGame();
        EClass.player.flags.OnEnableDebug();
        EClass.player.pref.lastIdTabAbility = 3;
        Zone homeZone = EClass.game.spatials.Find(EClass.game.Prologue.idStartZone);
        switch (startParty)
        {
        case StartParty.Farris:
            AddParty("farris");
            break;
        case StartParty.Full:
            AddParty("farris");
            AddParty("wescott");
            break;
        }
        int lv = startSetting.lv;
        if (allAbility)
        {
            foreach (SourceElement.Row row in EClass.sources.elements.rows)
            {
                if (row.category == "ability" && row.aliasRef != "mold" && !EClass.pc.HasElement(row.id) && (row.aliasRef.IsEmpty() || row.id <= 10000 || EClass.sources.elements.alias[row.aliasRef].tag.Contains(row.alias.Split('_')[0])))
                {
                    EClass.pc.elements.ModBase(row.id, lv).vPotential = 30;
                }
            }
        }
        if (allSkill)
        {
            foreach (SourceElement.Row row2 in EClass.sources.elements.rows)
            {
                if (row2.isSkill && !row2.tag.Contains("unused"))
                {
                    EClass.pc.elements.ModBase(row2.id, 1);
                }
            }
        }
        EClass.pc.elements.ModBase(60, lv / 2);
        EClass.pc.elements.ModBase(61, lv / 2);
        EClass.pc.elements.ModBase(79, lv / 5);
        EClass.player.totalFeat = lv;
        EClass.pc.SetLv(lv - 1);
        EClass.player.fame = EClass.pc.LV * 100;
        int idx = 0;
        switch (startLoadout)
        {
        case StartLoadout.AllItem:
            EClass.pc.ModCurrency(50, "plat");
            EClass.pc.ModCurrency(50, "money2");
            EClass.pc.EQ_CAT("weapon");
            EClass.pc.EQ_CAT((EScriptable.rnd(2) == 0) ? "weapon" : "shield");
            EClass.pc.EQ_CAT("torso");
            EClass.pc.EQ_CAT("arm");
            EClass.pc.EQ_CAT("ring");
            EClass.pc.AddCard(ThingGen.Create("chest2"));
            EClass.pc.AddCard(ThingGen.Create("torch_held"));
            AddHotbar("axe");
            AddHotbar("pickaxe");
            AddHotbar("wateringCan");
            AddHotbar("bow");
            AddHotbar("deed");
            AddAbility("SpellTeleport");
            AddAbility("SpellCatsEye");
            AddHotbar("map_big");
            break;
        case StartLoadout.FewItem:
        {
            Thing thing = ThingGen.Create("backpack");
            thing.AddCard(ThingGen.Create("rp_food", -1, 10).SetNum(30));
            thing.AddCard(ThingGen.Create("rp_block", -1, 10).SetNum(30));
            for (int i = 0; i < 30; i++)
            {
                thing.AddCard(ThingGen.Create("rp_block", -1, 50));
            }
            EClass.pc.AddCard(thing);
            thing = ThingGen.Create("pouch");
            for (int j = 0; j < 30; j++)
            {
                CardBlueprint.Set(CardBlueprint.DebugEQ);
                Thing thing2 = ThingGen.CreateFromCategory("weapon", EClass.pc.LV);
                thing2.elements.SetBase(653, 1);
                if (!(thing2.trait is TraitAmmo))
                {
                    thing.AddCard(thing2);
                }
                thing2 = ThingGen.CreateFromCategory("armor", EClass.pc.LV);
                thing2.elements.SetBase(653, 1);
                thing.AddCard(thing2);
            }
            EClass.pc.AddCard(thing);
            thing = ThingGen.Create("pouch");
            for (int k = 0; k < 30; k++)
            {
                thing.AddCard(ThingGen.Create("mathammer", MATERIAL.GetRandomMaterial(100).alias));
            }
            EClass.pc.AddCard(thing);
            thing = ThingGen.Create("pouch");
            for (int l = 0; l < 30; l++)
            {
                thing.AddCard(ThingGen.CreateFromCategory("ammo", EClass.pc.LV));
            }
            EClass.pc.AddCard(thing);
            thing = ThingGen.Create("coolerbox");
            for (int m = 0; m < 20; m++)
            {
                thing.AddCard(ThingGen.CreateFromCategory("foodstuff").SetNum(EScriptable.rnd(10) + 1));
            }
            EClass.pc.AddCard(thing);
            List<SourceChara.Row> list = EClass.sources.charas.map.Values.Where((SourceChara.Row a) => a._idRenderData == "chara").ToList();
            thing = ThingGen.Create("pouch");
            list = EClass.sources.charas.map.Values.Where((SourceChara.Row a) => a._idRenderData == "chara_L").ToList();
            for (int n = 0; n < 20; n++)
            {
                string id2 = list.RandomItem().id;
                Thing thing3 = ThingGen.Create("figure");
                thing3.MakeFigureFrom(id2);
                thing.AddCard(thing3);
            }
            EClass.pc.AddCard(thing);
            thing = ThingGen.Create("pouch");
            list = EClass.sources.charas.map.Values.Where((SourceChara.Row a) => a._idRenderData == "chara").ToList();
            for (int num = 0; num < 20; num++)
            {
                string id3 = list.RandomItem().id;
                Thing thing4 = ThingGen.Create("figure3");
                thing4.MakeFigureFrom(id3);
                thing.AddCard(thing4);
            }
            EClass.pc.AddCard(thing);
            thing.Dye("oak");
            thing = ThingGen.Create("pouch");
            list = EClass.sources.charas.map.Values.Where((SourceChara.Row a) => a._idRenderData == "chara_L").ToList();
            for (int num2 = 0; num2 < 20; num2++)
            {
                string id4 = list.RandomItem().id;
                Thing thing5 = ThingGen.Create("figure3");
                thing5.MakeFigureFrom(id4);
                thing.AddCard(thing5);
            }
            EClass.pc.AddCard(thing);
            thing.Dye("pine");
            thing = ThingGen.Create("pouch");
            thing.AddCard(ThingGen.Create("flour").SetNum(10));
            thing.AddCard(ThingGen.Create("wheat").SetNum(200));
            thing.AddCard(ThingGen.Create("rice_plant").SetNum(200));
            thing.AddCard(ThingGen.Create("noodle").SetNum(10));
            thing.AddCard(ThingGen.Create("rice").SetNum(10));
            thing.AddCard(ThingGen.Create("dough_cake").SetNum(10));
            thing.AddCard(ThingGen.Create("dough_bread").SetNum(10));
            thing.AddCard(ThingGen.Create("salt").SetNum(10));
            thing.AddCard(ThingGen.Create("sugar").SetNum(10));
            thing.AddCard(ThingGen.Create("honey").SetNum(10));
            thing.AddCard(ThingGen.Create("yeast").SetNum(10));
            thing.AddCard(ThingGen.Create("ketchup").SetNum(10));
            thing.AddCard(ThingGen.Create("butter").SetNum(10));
            thing.AddCard(ThingGen.Create("potion_empty").SetNum(10));
            thing.AddCard(ThingGen.Create("bucket_empty").SetNum(10));
            thing.AddCard(ThingGen.Create("battery"));
            EClass.pc.AddCard(thing);
            thing.Dye("saphire");
            thing = ThingGen.Create("pouch");
            thing.AddCard(ThingGen.Create("log").SetNum(99));
            thing.AddCard(ThingGen.Create("log").SetNum(99).ChangeMaterial("pine"));
            thing.AddCard(ThingGen.Create("ore").SetNum(99).ChangeMaterial("steel"));
            thing.AddCard(ThingGen.Create("ore").SetNum(99).ChangeMaterial("copper"));
            thing.AddCard(ThingGen.Create("ore_gem").SetNum(99).ChangeMaterial("gold"));
            thing.AddCard(ThingGen.Create("gem").SetNum(99).ChangeMaterial("rubinus"));
            thing.AddCard(ThingGen.Create("flower_white").SetNum(99));
            thing.AddCard(ThingGen.Create("bait").SetNum(10));
            thing.AddCard(ThingGen.Create("seed").SetNum(99));
            EClass.pc.AddCard(thing);
            thing.Dye("rubinus");
            Thing thing6 = ThingGen.Create("quiver");
            thing6.AddCard(ThingGen.Create("bullet").SetNum(250));
            thing6.AddCard(ThingGen.Create("arrow").SetNum(250));
            thing6.AddCard(ThingGen.Create("bolt").SetNum(250));
            thing6.AddCard(ThingGen.Create("bullet_energy").SetNum(250));
            EClass.pc.body.GetEquippedThing(44).AddCard(thing6);
            thing = ThingGen.Create("backpack");
            for (int num3 = 0; num3 < 10; num3++)
            {
                thing.AddThing("book", lv);
                thing.AddThing("parchment");
                thing.AddThing("book_ancient");
            }
            EClass.pc.AddCard(thing);
            thing.Dye("rubinus");
            thing = ThingGen.Create("pouch");
            for (int num4 = 0; num4 < 30; num4++)
            {
                thing.AddThing((EScriptable.rnd(10) != 0) ? "potion" : "drink", lv).SetNum(99);
            }
            EClass.pc.AddCard(thing);
            thing.Dye("steel");
            thing = ThingGen.Create("pouch");
            for (int num5 = 0; num5 < 30; num5++)
            {
                thing.AddThing(ThingGen.CreateFromCategory("rod", lv));
            }
            EClass.pc.AddCard(thing);
            thing.Dye("steel");
            thing = ThingGen.Create("pouch");
            for (int num6 = 0; num6 < 30; num6++)
            {
                thing.AddThing("scroll", lv).SetNum(99);
            }
            EClass.pc.AddCard(thing);
            thing.Dye("steel");
            thing = ThingGen.Create("pouch");
            for (int num7 = 0; num7 < 40; num7++)
            {
                thing.AddThing("372", 100);
            }
            EClass.pc.AddCard(thing);
            thing.Dye("steel");
            Thing thing7 = EClass.pc.things.Find("purse");
            thing7.AddThing("casino_coin").SetNum(30000000);
            thing7.AddThing("medal").SetNum(1000);
            thing7.ModCurrency(500, "plat");
            EClass.pc.AddThing("record");
            EClass.pc.AddThing("deed").SetNum(5);
            EClass.pc.AddThing("book_story");
            EClass.pc.AddThing("book_tutorial");
            EClass.pc.AddThing("water").SetNum(20).SetBlessedState(BlessedState.Blessed);
            EClass.pc.AddThing("water").SetNum(20).SetBlessedState(BlessedState.Cursed);
            EClass.pc.AddThing("potion_empty").SetNum(20);
            EClass.pc.ModCurrency(10000000);
            EClass.pc.AddCard(ThingGen.CreateBlock(67, 1).SetNum(99));
            EClass.pc.AddCard(ThingGen.CreateFloor(41, 1).SetNum(99));
            Thing thing8 = ThingGen.Create("scroll_random").SetNum(10);
            thing8.refVal = 8220;
            EClass.pc.AddCard(thing8);
            EClass.pc.ModCurrency(50, "money2");
            AddHotbar("hoe");
            AddHotbar("shovel");
            AddHotbar("axe");
            AddHotbar("pickaxe");
            AddHotbar("wateringCan");
            AddHotbar("gun_assault");
            AddHotbar("hammer");
            AddHotbar("bow");
            break;
        }
        }
        EClass.pc.RestockEquip(onCreate: true);
        EClass.pc.stamina.value = EClass.pc.stamina.max;
        EClass.pc.mana.value = EClass.pc.mana.max;
        EClass.pc.hp = EClass.pc.MaxHP;
        if (EClass.debug.startScene == StartScene.Zone)
        {
            EClass._zone.ClaimZone(debug: true);
        }
        SoundManager.ignoreSounds = true;
        EClass.ui.ToggleInventory();
        SoundManager.ignoreSounds = true;
        EClass.ui.ToggleAbility();
        SoundManager.ignoreSounds = false;
        EClass.ui.layerFloat.GetLayer<LayerAbility>().windows[0].SetRect(EClass.core.refs.rects.abilityDebug);
        if (allRecipe)
        {
            AddAllRecipes();
        }
        foreach (Thing thing11 in EClass.pc.things)
        {
            thing11.isNew = false;
        }
        LayerInventory.SetDirtyAll();
        EClass.core.actionsNextFrame.Add(EClass.pc.RecalculateFOV);
        if (startScene == StartScene.Story_Test)
        {
            EClass._zone.ClaimZone(debug: true);
            EClass.Branch.AddMemeber(EClass._zone.AddCard(CharaGen.Create("loytel"), EClass.pc.pos.GetNearestPoint(allowBlock: false, allowChara: false)) as Chara);
            EClass.Branch.AddMemeber(EClass._zone.AddCard(CharaGen.Create("farris"), EClass.pc.pos.GetNearestPoint(allowBlock: false, allowChara: false)) as Chara);
            EClass.Branch.AddMemeber(EClass._zone.AddCard(CharaGen.Create("kettle"), EClass.pc.pos.GetNearestPoint(allowBlock: false, allowChara: false)) as Chara);
            EClass.Branch.AddMemeber(EClass._zone.AddCard(CharaGen.Create("quru"), EClass.pc.pos.GetNearestPoint(allowBlock: false, allowChara: false)) as Chara);
            EClass.Branch.AddMemeber(EClass._zone.AddCard(CharaGen.Create("corgon"), EClass.pc.pos.GetNearestPoint(allowBlock: false, allowChara: false)) as Chara);
            EClass.Branch.AddMemeber(EClass._zone.AddCard(CharaGen.Create("demitas"), EClass.pc.pos.GetNearestPoint(allowBlock: false, allowChara: false)) as Chara);
            EClass.game.quests.Add("greatDebt");
            EClass.game.quests.Add("farris_tulip");
            EClass.game.quests.Add("kettle_join");
            EClass.game.quests.Add("quru_morning");
            EClass.game.quests.Add("vernis_gold");
            EClass.game.quests.Add("quru_sing");
            EClass.game.quests.Add("quru_past1");
            EClass.game.quests.Add("quru_past2");
            EClass.game.quests.Add("pre_debt");
        }
        static Thing AddAbility(string id)
        {
            Thing thing9 = EClass.pc.AddThing(ThingGen.Create("catalyst"));
            thing9.c_idAbility = id;
            return thing9;
        }
        Thing AddHotbar(string id)
        {
            Thing thing10 = EClass.pc.AddThing(ThingGen.Create(id));
            thing10.invX = idx;
            thing10.invY = 1;
            idx++;
            return thing10;
        }
        void AddParty(string id)
        {
            Chara chara = CharaGen.Create(id);
            chara.SetFaction(EClass.Home);
            chara.SetHomeZone(homeZone);
            if (chara.currentZone != EClass._zone)
            {
                EClass._zone.AddCard(chara, EClass.pc.pos.GetNearestPoint(allowBlock: false, allowChara: false));
            }
            EClass.pc.party.AddMemeber(chara);
        }
    }
References EClass._zone, CoreRef.Rects.abilityDebug, QuestManager.Add(), AddAllRecipes(), Card.AddCard(), Zone.AddCard(), FactionBranch.AddMemeber(), Party.AddMemeber(), Card.AddThing(), allAbility, allRecipe, allSkill, Chara.body, EClass.Branch, Chara.ChangeJob(), Card.ChangeMaterial(), Chara.ChangeRace(), SourceManager.charas, Zone.ClaimZone(), EClass.core, Game.Create(), ThingGen.Create(), CharaGen.Create(), ThingGen.CreateBlock(), ThingGen.CreateFloor(), ThingGen.CreateFromCategory(), Chara.currentZone, EClass.debug, CardBlueprint.DebugEQ, Card.Dye(), Card.elements, SourceManager.elements, Chara.EQ_CAT(), ThingContainer.Find(), SpatialManager.Find(), Player.flags, EClass.game, CharaBody.GetEquippedThing(), Point.GetNearestPoint(), MATERIAL.GetRandomMaterial(), Card.HasElement(), EClass.Home, Prologue.idStartZone, CoreDebug.StartSetting.job, Card.LV, CoreDebug.StartSetting.lv, Card.MakeFigureFrom(), Chara.mana, Stats.max, Chara.MaxHP, ElementContainer.ModBase(), Card.ModCurrency(), Player.Flags.OnEnableDebug(), Chara.party, EClass.pc, EClass.player, Card.pos, Game.Prologue, Game.quests, CoreDebug.StartSetting.race, Card.RecalculateFOV(), CoreRef.rects, Core.refs, Chara.RestockEquip(), EScriptable.rnd(), CardBlueprint.Set(), ElementContainer.SetBase(), Card.SetBlessedState(), LayerInventory.SetDirtyAll(), Chara.SetFaction(), Chara.SetHomeZone(), Card.SetLv(), Card.SetNum(), skipNerun, EClass.sources, Game.spatials, Chara.stamina, startHour, startLoadout, Game.StartNewGame(), startParty, startScene, startSetting, Card.things, Card.trait, EClass.ui, and Element.vPotential.
Referenced by Core.Init().
RegenerateNames()
static string CoreDebug.RegenerateNames () inline static
Definition at line 2081 of file CoreDebug.cs.
    {
        EClass.core.mods.InitLang();
        NameGen.list = null;
        AliasGen.list = null;
        NameGen.Init();
        AliasGen.Init();
        foreach (Chara chara in EClass._map.charas)
        {
            if (!chara.IsPC)
            {
                if (chara.source.name == "*r")
                {
                    chara.c_altName = NameGen.getRandomName();
                }
                if (!chara._alias.IsEmpty())
                {
                    chara._alias = AliasGen.GetRandomAlias();
                }
            }
        }
        return "Done!";
    }
References Chara._alias, EClass._map, Map.charas, EClass.core, ModManager.Init(), Chara.IsPC, Core.mods, and Chara.source.
RemoveDemitas()
static string CoreDebug.RemoveDemitas () inline static
Definition at line 1990 of file CoreDebug.cs.
    {
        List<Chara> list = new List<Chara>();
        foreach (Chara value in EClass.game.cards.globalCharas.Values)
        {
            if (value.id == "demitas" && value.currentZone == EClass._zone)
            {
                list.Add(value);
            }
        }
        if (list.Count > 1)
        {
            Chara chara = list[1];
            chara.homeBranch.BanishMember(chara);
            chara.Destroy();
            return "Demitas Removed!";
        }
        return "Not enough Demitas!";
    }
References EClass._zone, FactionBranch.BanishMember(), Game.cards, Chara.currentZone, Card.Destroy(), EClass.game, CardManager.globalCharas, Chara.homeBranch, and Card.id.
ResetPetUpgrades()
static string CoreDebug.ResetPetUpgrades () inline static
Definition at line 1925 of file CoreDebug.cs.
    {
        foreach (Chara value in EClass.game.cards.globalCharas.Values)
        {
            if (value.IsPCFaction)
            {
                value.ResetUpgrade();
            }
        }
        return "Not Implemented.";
    }
References Game.cards, EClass.game, CardManager.globalCharas, Chara.IsPCFaction, and Chara.ResetUpgrade().
Resource()
static string CoreDebug.Resource () inline static
Definition at line 2153 of file CoreDebug.cs.
    {
        if (!CheatEnabled())
        {
            return EnableCheat;
        }
        EClass.debug.SpawnCheatContainer();
        return "Resources spawned.";
    }
References EClass.debug, and SpawnCheatContainer().
SetElement()
static string CoreDebug.SetElement (string alias, int value, int potential = 100) inline static
Definition at line 1850 of file CoreDebug.cs.
    {
        if (!CheatEnabled())
        {
            return EnableCheat;
        }
        SourceElement.Row row = EClass.sources.elements.alias.TryGetValue(alias);
        if (row == null)
        {
            return "Element not found.";
        }
        if (row.type == "Feat")
        {
            EClass.pc.SetFeat(row.id, value, msg: true);
        }
        else
        {
            EClass.pc.elements.SetBase(row.id, value, potential);
        }
        return "Done.";
    }
References Card.elements, SourceManager.elements, SourceElement.Row.id, EClass.pc, ElementContainer.SetBase(), Chara.SetFeat(), EClass.sources, and SourceElement.Row.type.
SetStartStockpile()
void CoreDebug.SetStartStockpile (Thing container, int num = 100) inline
Definition at line 688 of file CoreDebug.cs.
    {
        LittlePopper.skipPop = true;
        foreach (SourceMaterial.Row row in EClass.sources.materials.rows)
        {
            if (!(row.alias == "void") && (!randomResource || EScriptable.rnd(4) == 0))
            {
                row.CreateByProduct(container, num);
            }
        }
        foreach (SourceThing.Row row2 in EClass.sources.things.rows)
        {
            if ((row2.factory.IsEmpty() || !(row2.factory[0] == "x")) && !row2.isOrigin && row2.Category.tag.Contains("debug"))
            {
                Thing thing = ThingGen.Create(row2.id);
                if (thing.trait.CanStack)
                {
                    thing.ModNum(num);
                }
                container.AddThing(thing);
            }
        }
        for (int i = 0; i < 10; i++)
        {
            container.AddThing(TraitSeed.MakeRandomSeed());
        }
        LittlePopper.skipPop = false;
    }
References Card.AddThing(), Trait.CanStack, ThingGen.Create(), TraitSeed.MakeRandomSeed(), SourceManager.materials, Card.ModNum(), randomResource, EScriptable.rnd(), EClass.sources, SourceManager.things, and Card.trait.
Referenced by EnableDebugResource().
Spawn()
static string CoreDebug.Spawn (string id, int num = 1, string aliasMat = "", int objLv = -1) inline static
Definition at line 1873 of file CoreDebug.cs.
    {
        if (!CheatEnabled())
        {
            return EnableCheat;
        }
        if (EClass.sources.things.map.ContainsKey(id))
        {
            Thing thing = ThingGen.Create(id, -1, objLv).SetNum(num);
            if (!aliasMat.IsEmpty())
            {
                thing.ChangeMaterial(aliasMat);
            }
            EClass._zone.AddCard(thing, EClass.pc.pos);
            return "Spawned " + thing.Name;
        }
        if (EClass.sources.charas.map.ContainsKey(id))
        {
            Chara chara = CharaGen.Create(id);
            if (objLv != -1)
            {
                chara.SetLv(objLv);
            }
            EClass._zone.AddCard(chara, EClass.pc.pos);
            return "Spawned " + chara.Name;
        }
        return "'" + id + "' does not exist in the database.";
    }
References EClass._zone, Zone.AddCard(), Card.ChangeMaterial(), SourceManager.charas, ThingGen.Create(), CharaGen.Create(), Card.Name, EClass.pc, Card.pos, Card.SetLv(), Card.SetNum(), EClass.sources, and SourceManager.things.
SpawnCheatContainer()
void CoreDebug.SpawnCheatContainer () inline
Definition at line 760 of file CoreDebug.cs.
    {
    }
Referenced by Resource().
Test_Filter()
void CoreDebug.Test_Filter () inline
Definition at line 1720 of file CoreDebug.cs.
    {
        bilinear = !bilinear;
        MeshPass[] passes = EClass.scene.passes;
        for (int i = 0; i < passes.Length; i++)
        {
            passes[i].mat.GetTexture("_MainTex").filterMode = (bilinear ? FilterMode.Bilinear : FilterMode.Point);
        }
    }
References MeshPass.mat, Scene.passes, and EClass.scene.
Test_GodTalk()
void CoreDebug.Test_GodTalk () inline
Definition at line 1689 of file CoreDebug.cs.
    {
        foreach (Religion value in EClass.game.religions.dictAll.Values)
        {
            value.Talk("test");
        }
    }
References ReligionManager.dictAll, EClass.game, Game.religions, and Religion.Talk().
Test_Grow()
void CoreDebug.Test_Grow () inline
Definition at line 1671 of file CoreDebug.cs.
    {
        EClass._map.ForeachCell(delegate(Cell c)
        {
            if (c.sourceObj.HasGrowth)
            {
                c.TryGrow();
            }
        });
        foreach (Thing item in EClass._map.things.Copy())
        {
            if (item.trait is TraitSeed traitSeed)
            {
                traitSeed.TrySprout(force: true);
            }
        }
    }
References EClass._map, Map.ForeachCell(), Cell.sourceObj, Map.things, and Card.trait.
Test_Siege()
void CoreDebug.Test_Siege () inline
Definition at line 1750 of file CoreDebug.cs.
    {
        if (EClass._zone.events.GetEvent<ZoneEventSiege>() == null)
        {
            EClass._zone.events.Add(new ZoneEventSiege());
        }
        else
        {
            EClass._zone.events.Remove<ZoneEventSiege>();
        }
    }
References EClass._zone, ZoneEventManager.Add(), Zone.events, and ZoneEventManager.Remove().
Test_SiegeGuard()
void CoreDebug.Test_SiegeGuard () inline
Definition at line 1738 of file CoreDebug.cs.
    {
        if (EClass._zone.events.GetEvent<ZoneEventSiegeGuard>() == null)
        {
            EClass._zone.events.Add(new ZoneEventSiegeGuard());
        }
        else
        {
            EClass._zone.events.Remove<ZoneEventSiegeGuard>();
        }
    }
References EClass._zone, ZoneEventManager.Add(), Zone.events, and ZoneEventManager.Remove().
TestSpawn()
static string CoreDebug.TestSpawn (int lv, int num, int lvRange = -1) inline static
Definition at line 1903 of file CoreDebug.cs.
    {
        if (!CheatEnabled())
        {
            return EnableCheat;
        }
        foreach (Chara item in EClass._map.charas.Where((Chara c) => c.HasEditorTag(EditorTag.SpawnTest)).ToList())
        {
            item.Destroy();
        }
        for (int i = 0; i < num; i++)
        {
            EClass._zone.SpawnMob(EClass.pc.pos.GetNearestPoint(allowBlock: false, allowChara: false, allowInstalled: false, ignoreCenter: true), new SpawnSetting
            {
                filterLv = lv,
                levelRange = lvRange
            }).AddEditorTag(EditorTag.SpawnTest);
        }
        return "Spawned.";
    }
References EClass._map, EClass._zone, Card.AddEditorTag(), Map.charas, Card.Destroy(), Point.GetNearestPoint(), Card.HasEditorTag(), EClass.pc, Card.pos, and Zone.SpawnMob().
Referenced by UpdateInput().
ToggleRevealMap()
void CoreDebug.ToggleRevealMap () inline
Definition at line 2176 of file CoreDebug.cs.
    {
        revealMap = !revealMap;
        if (revealMap)
        {
            EClass._map.RevealAll();
        }
        SE.ClickGeneral();
    }
References EClass._map, and Map.RevealAll().
Referenced by HotItemContext.Show().
UpdateAlways()
void CoreDebug.UpdateAlways () inline
Definition at line 764 of file CoreDebug.cs.
    {
        if (!EClass.debug.enable || (bool)EClass.ui.GetLayer<LayerConsole>())
        {
            return;
        }
        if (Input.GetKeyDown(KeyCode.B))
        {
            UIButton.TryShowTip();
        }
        if (Input.GetKeyDown(KeyCode.O))
        {
            Steam.GetAchievement(ID_Achievement.test);
        }
        if (Input.GetKeyDown(KeyCode.P))
        {
            Steam.GetAchievement(ID_Achievement.mew);
        }
        if (Input.GetKeyDown(KeyCode.F11))
        {
            if (Application.isEditor)
            {
                EClass.core.SetLang((Lang.langCode == "EN") ? "JP" : "EN");
            }
            else
            {
                EClass.sources.ImportSourceTexts();
            }
            NewsList.dict = null;
            BookList.dict = null;
            BookList.Init();
        }
        if (EClass.core.IsGameStarted)
        {
            if (Input.GetKeyDown(KeyCode.U))
            {
                Vector3 offset = EClass.screen.tileMap.rendererInnerBlock.offset;
                Msg.SayRaw(offset.ToString() ?? "");
                EClass.screen.tileMap.rendererInnerBlock.offset = Vector3.zero;
            }
            if (Input.GetKeyDown(KeyCode.I))
            {
                Vector3 offset = EClass.screen.tileMap.rendererInnerBlock.offset;
                Msg.SayRaw(offset.ToString() ?? "");
                EClass.screen.tileMap.rendererInnerBlock.offset = new Vector3(0f, 0.54f, -0.5f);
            }
        }
    }
References EClass.core, EClass.debug, enable, Steam.GetAchievement(), SourceManager.ImportSourceTexts(), Core.IsGameStarted, RenderData.offset, BaseTileMap.rendererInnerBlock, Msg.SayRaw(), EClass.screen, Core.SetLang(), EClass.sources, BaseGameScreen.tileMap, and EClass.ui.
Referenced by Core.Update().
UpdateInput()
void CoreDebug.UpdateInput () inline
Definition at line 823 of file CoreDebug.cs.
    {
        if (!debugInput || EInput.isInputFieldActive || (bool)EClass.ui.GetLayer<LayerConsole>())
        {
            return;
        }
        bool key = Input.GetKey(KeyCode.LeftShift);
        bool key2 = Input.GetKey(KeyCode.LeftAlt);
        bool key3 = Input.GetKey(KeyCode.LeftControl);
        TraitStairs traitStairs = null;
        if (Input.GetKeyDown(KeyCode.KeypadPlus))
        {
            traitStairs = EClass._map.FindThing<TraitStairsDown>();
        }
        if (Input.GetKeyDown(KeyCode.KeypadMinus))
        {
            traitStairs = EClass._map.FindThing<TraitStairsUp>();
        }
        traitStairs?.MoveZone();
        if (EInput.action == EAction.ShowGrid)
        {
            EClass.ui.Find("_Guide").ToggleActive();
        }
        if (Input.GetKey(KeyCode.N))
        {
            if (key)
            {
                SoundManager.current.sourceBGM.pitch = 10f;
            }
            if (key3)
            {
                SoundManager.current.sourceBGM.time = SoundManager.current.currentBGM.length - 10f;
            }
        }
        else if (Input.GetKeyUp(KeyCode.N))
        {
            SoundManager.current.sourceBGM.pitch = 1f;
        }
        if (EClass.scene.actionMode.IsBuildMode)
        {
            string text = "festival";
            if (Input.GetKeyDown(KeyCode.F1))
            {
                EClass.ui.AddLayer<LayerDebug>();
            }
            if (Input.GetKeyDown(KeyCode.F2))
            {
                Zone.forceRegenerate = true;
                EClass.scene.actionMode.Deactivate();
                EClass.scene.Init(Scene.Mode.Zone);
                ActionMode.Inspect.Activate();
                SE.MoveZone();
            }
            if (Input.GetKeyDown(KeyCode.F4))
            {
                if (!MapSubset.Exist(text))
                {
                    SE.Beep();
                    return;
                }
                Zone.forceRegenerate = true;
                Zone.forceSubset = text;
                EClass.scene.actionMode.Deactivate();
                EClass.scene.Init(Scene.Mode.Zone);
                ActionMode.Inspect.Activate();
                SE.MoveZone();
                EClass.ui.Say("Loaded Subset");
            }
            if (Input.GetKeyDown(KeyCode.F5))
            {
                MapSubset.Save(text);
                SE.WriteJournal();
                EClass.ui.Say("Exported Subset");
            }
            return;
        }
        if (Input.GetKeyDown(KeyCode.F1))
        {
            EClass.ui.AddLayer<LayerDebug>();
            Debug.Log(EClass._zone);
            Debug.Log(EClass._zone.id + "/" + EClass._zone.parent);
            Debug.Log(EClass._zone.RegionPos);
        }
        if (Input.GetKeyDown(KeyCode.F2))
        {
            EClass._zone.TryGenerateEvolved(force: true);
            EClass._zone.SpawnMob(null, SpawnSetting.Boss(100));
            Chara targetChara = EClass.scene.mouseTarget.TargetChara;
            if (targetChara != null)
            {
                EClass.pc.Pick(targetChara.MakeMilk());
                EClass.pc.Pick(targetChara.MakeGene());
                EClass.pc.Pick(targetChara.MakeBraineCell());
                EClass.pc.Pick(targetChara.MakeEgg(effect: true, 10));
            }
            if (EClass.game.quests.Get<QuestDebt>() == null)
            {
                Chara chara = CharaGen.Create("loytel");
                EClass._zone.AddCard(chara, EClass.pc.pos);
                chara.SetGlobal();
                Quest q = EClass.game.quests.Add("debt", "loytel");
                EClass.game.quests.Start(q);
                EClass.pc.party.RemoveMember(chara);
                Hostility hostility2 = (chara.c_originalHostility = Hostility.Ally);
                chara.hostility = hostility2;
            }
            return;
        }
        if (Input.GetKeyDown(KeyCode.F3))
        {
            EClass.pc.AddCondition<ConDisease>();
            (EClass.pc.AddCondition<ConStrife>() as ConStrife).lv = 6;
            for (int i = 0; i < 10; i++)
            {
                Thing thing = ThingGen.Create("egg_fertilized");
                thing.TryMakeRandomItem(40);
                thing.SetEncLv(200);
                EClass.pc.Pick(thing);
            }
            foreach (Chara deadChara in EClass._map.deadCharas)
            {
                Debug.Log(deadChara);
            }
            EClass.core.steam.CheckUpdate();
            EClass.player.flags.loytelMartLv++;
            Msg.Say("loytelmart:" + EClass.player.flags.loytelMartLv);
            Guild.Fighter.relation.rank = 20;
            Guild.Mage.relation.rank = 20;
            Guild.Thief.relation.rank = 20;
            Guild.Merchant.relation.rank = 20;
            if (EClass.Branch != null)
            {
                EClass.Branch.ModExp(EClass.Branch.GetNextExp());
            }
            foreach (Chara member in EClass.pc.party.members)
            {
                member.AddExp(member.ExpToNext);
            }
            EClass.pc.PlayEffect("boost");
            EClass.pc.PlaySound("boost");
            EClass.pc.elements.SetBase(306, 100);
            EClass.pc.elements.SetBase(85, 100);
            EClass.pc.feat += 10;
            EClass.player.totalFeat += 10;
            return;
        }
        if (Input.GetKeyDown(KeyCode.F4))
        {
            TestSpawn(param1, param2, 5);
            return;
        }
        if (Input.GetKeyDown(KeyCode.F5))
        {
            string text2 = (Input.GetKey(KeyCode.LeftControl) ? "quick3" : (Input.GetKey(KeyCode.LeftShift) ? "quick2" : "quick"));
            if (text2 != Game.id)
            {
                IO.DeleteDirectory(CorePath.RootSave + text2);
                IO.CopyAll(CorePath.RootSave + Game.id, CorePath.RootSave + text2);
                Game.id = text2;
            }
            EClass.game.isCloud = false;
            EClass.game.Save();
        }
        if (Input.GetKeyDown(KeyCode.F6))
        {
            EClass.core.WaitForEndOfFrame(delegate
            {
                string id = (Input.GetKey(KeyCode.LeftControl) ? "quick3" : (Input.GetKey(KeyCode.LeftShift) ? "quick2" : "quick"));
                EClass.scene.Init(Scene.Mode.None);
                Game.Load(id, cloud: false);
            });
        }
        if (Input.GetKeyDown(KeyCode.F7))
        {
            MiniGame.Activate(MiniGame.Type.Scratch);
            return;
        }
        if (Input.GetKeyDown(KeyCode.F8))
        {
            SE.Click();
            EnableDebugResource();
            runtimeGodBuild = true;
            WidgetMenuPanel.OnChangeMode();
            EClass.player.hotbars.ResetHotbar(2);
        }
        if (key3)
        {
            if (Input.GetKeyDown(KeyCode.F9))
            {
                indexResolution++;
                if (indexResolution >= resolutions.Count)
                {
                    indexResolution = 0;
                }
                int[] array = resolutions[indexResolution];
                int width = array[0];
                int height = array[1];
                Screen.SetResolution(width, height, key);
                WidgetFeed.Instance?.Nerun(width + "/" + height);
            }
            if (Input.GetKeyDown(KeyCode.F10))
            {
                int width2 = Screen.width;
                int height2 = width2 / 16 * 9;
                Screen.SetResolution(width2, height2, key);
                WidgetFeed.Instance?.Nerun(width2 + "/" + height2);
            }
        }
        else
        {
            Input.GetKeyDown(KeyCode.F9);
            if (Input.GetKey(KeyCode.F9))
            {
                EClass.scene.paused = false;
                for (int j = 0; j < advanceMin; j++)
                {
                    EClass.game.updater.FixedUpdate();
                }
                EClass.game.world.date.AdvanceMin(advanceMin);
            }
            if (Input.GetKeyDown(KeyCode.F10))
            {
                switch (EScriptable.rnd(5))
                {
                case 0:
                    EClass.world.weather.SetCondition(Weather.Condition.Rain);
                    break;
                case 1:
                    EClass.world.weather.SetCondition(Weather.Condition.Snow);
                    break;
                case 2:
                    EClass.world.weather.SetCondition(Weather.Condition.Ether);
                    break;
                default:
                    EClass.world.weather.SetCondition(Weather.Condition.Fine);
                    break;
                }
            }
        }
        if (Input.GetKeyDown(KeyCode.N) && !EInput.isShiftDown && !EInput.isCtrlDown)
        {
            EClass.Sound.NextBGM();
        }
        if (Input.GetKeyDown(KeyCode.Tab))
        {
            if (key)
            {
                EClass.ui.AddLayer<LayerConsole>();
            }
            else
            {
                EClass.ui.widgets.Toggle("Debug");
            }
        }
        Point hitPoint = Scene.HitPoint;
        if (!hitPoint.IsValid || EClass.ui.IsActive)
        {
            return;
        }
        if (hitPoint.detail != null)
        {
            _ = hitPoint.area;
        }
        if (hitPoint.detail?.things == null)
        {
            new List<Thing>();
        }
        if (hitPoint.detail?.charas == null)
        {
            new List<Chara>();
        }
        List<Card> list = hitPoint.ListCards();
        if (Input.GetMouseButtonDown(2))
        {
            if (EClass.core.releaseMode != 0)
            {
                if (key)
                {
                    EClass._zone.SpawnMob(hitPoint);
                }
                else if (key3)
                {
                    EClass._zone.SpawnMob(hitPoint);
                }
                else if (key2)
                {
                    EClass._zone.SpawnMob(hitPoint);
                }
            }
            return;
        }
        if (key2)
        {
            if (Input.GetMouseButtonDown(0))
            {
                foreach (Card item in list)
                {
                    Debug.Log(item.Name + "/" + item.dir + "/" + item.flipX + "/" + item.angle);
                }
            }
            if (Input.GetMouseButtonDown(1))
            {
                if (key)
                {
                    EClass._map.charas.ForeachReverse(delegate(Chara c)
                    {
                        if (c.IsHostile(EClass.pc))
{
                            c.DamageHP(9999999, AttackSource.Finish, EClass.pc);
                        }
                    });
                }
                else if (hitPoint.detail != null)
                {
                    for (int num = hitPoint.detail.charas.Count - 1; num >= 0; num--)
                    {
                        hitPoint.detail.charas[num].DamageHP(9999999, AttackSource.Finish, EClass.pc);
                    }
                }
                EInput.Consume();
            }
        }
        if (Input.GetKeyDown(KeyCode.Delete))
        {
            if (Input.GetKey(KeyCode.RightControl))
            {
                return;
            }
            if (key)
            {
                foreach (Card item2 in EClass._map.Roaming.all.GetList<Card>())
                {
                    EClass._zone.RemoveCard(item2);
                }
            }
            else if (hitPoint.detail != null)
            {
                for (int num2 = hitPoint.detail.things.Count - 1; num2 >= 0; num2--)
                {
                    hitPoint.detail.things[num2].Destroy();
                }
                if (hitPoint.detail != null)
                {
                    for (int num3 = hitPoint.detail.charas.Count - 1; num3 >= 0; num3--)
                    {
                        hitPoint.detail.charas[num3].Destroy();
                    }
                }
            }
        }
        if (Input.GetKeyDown(KeyCode.End) && hitPoint.detail != null)
        {
            for (int num4 = hitPoint.detail.things.Count - 1; num4 >= 0; num4--)
            {
                Thing thing2 = hitPoint.detail.things[num4];
                Debug.Log(thing2.id + "/" + thing2.Pref.height + "/" + thing2.trait?.ToString() + "/" + thing2.source.tileType.CanStack + "/" + thing2.source.tileType?.ToString() + "/" + thing2.isSynced + "/" + RenderObject.syncList.Contains(thing2.renderer));
            }
        }
        if (!Application.isEditor)
        {
            return;
        }
        switch (debugHotkeys)
        {
        case DebugHotkey.Anime:
        {
            int num5 = -1;
            if (Input.GetKeyDown(KeyCode.Alpha0))
            {
                num5 = 0;
            }
            if (Input.GetKeyDown(KeyCode.Alpha1))
            {
                num5 = 1;
            }
            if (Input.GetKeyDown(KeyCode.Alpha2))
            {
                num5 = 2;
            }
            if (Input.GetKeyDown(KeyCode.Alpha3))
            {
                num5 = 3;
            }
            if (Input.GetKeyDown(KeyCode.Alpha4))
            {
                num5 = 4;
            }
            if (Input.GetKeyDown(KeyCode.Alpha5))
            {
                num5 = 5;
            }
            if (Input.GetKeyDown(KeyCode.Alpha6))
            {
                num5 = 6;
            }
            if (Input.GetKeyDown(KeyCode.Alpha7))
            {
                num5 = 7;
            }
            if (Input.GetKeyDown(KeyCode.Alpha8))
            {
                num5 = 8;
            }
            if (Input.GetKeyDown(KeyCode.Alpha9))
            {
                num5 = 9;
            }
            if (num5 == -1)
            {
                break;
            }
            foreach (Card item3 in hitPoint.ListCards())
            {
                item3.renderer.PlayAnime(num5.ToEnum<AnimeID>());
            }
            Debug.Log(num5.ToEnum<AnimeID>());
            break;
        }
        case DebugHotkey.Block:
            if (Input.GetKeyDown(KeyCode.Alpha1))
            {
                EClass._map.SetLiquid(hitPoint.x, hitPoint.z, 1, 9);
            }
            if (Input.GetKeyDown(KeyCode.Alpha2))
            {
                EClass._map.SetLiquid(hitPoint.x, hitPoint.z, 2, 9);
            }
            break;
        case DebugHotkey.Item:
            if (Input.GetKeyDown(KeyCode.Alpha1))
            {
                Thing thing3 = ThingGen.Create("stairsDown_cave");
                EClass._zone.AddCard(thing3, EClass.pc.pos);
                thing3.SetPlaceState(PlaceState.installed);
            }
            if (Input.GetKeyDown(KeyCode.Alpha2))
            {
                Thing thing4 = ThingGen.Create("stairs");
                EClass._zone.AddCard(thing4, EClass.pc.pos);
                thing4.SetPlaceState(PlaceState.installed);
            }
            if (Input.GetKeyDown(KeyCode.Alpha3))
            {
                Thing thing5 = ThingGen.Create("sign");
                EClass._zone.AddCard(thing5, hitPoint);
                thing5.SetPlaceState(PlaceState.installed);
            }
            if (Input.GetKeyDown(KeyCode.Alpha4))
            {
                Thing thing6 = ThingGen.Create("sign2");
                EClass._zone.AddCard(thing6, hitPoint);
                thing6.SetPlaceState(PlaceState.installed);
            }
            if (Input.GetKeyDown(KeyCode.Alpha5))
            {
                Thing thing7 = ThingGen.Create("well");
                EClass._zone.AddCard(thing7, hitPoint);
                thing7.SetPlaceState(PlaceState.installed);
            }
            if (Input.GetKeyDown(KeyCode.Alpha6))
            {
                Thing thing8 = ThingGen.Create("altar");
                EClass._zone.AddCard(thing8, hitPoint);
                thing8.SetPlaceState(PlaceState.installed);
            }
            if (Input.GetKeyDown(KeyCode.Alpha7))
            {
                Thing t = ThingGen.Create("torch");
                EClass._zone.AddCard(t, hitPoint);
            }
            if (Input.GetKeyDown(KeyCode.Alpha8))
            {
                Thing t2 = ThingGen.Create("street_lamp");
                EClass._zone.AddCard(t2, hitPoint);
            }
            if (Input.GetKeyDown(KeyCode.Alpha9))
            {
                Thing t3 = ThingGen.Create("statue_elin");
                EClass._zone.AddCard(t3, hitPoint);
            }
            if (Input.GetKeyDown(KeyCode.Alpha0))
            {
                Thing t4 = ThingGen.TestCreate();
                EClass._zone.AddCard(t4, hitPoint);
            }
            if (key && Input.GetKeyDown(KeyCode.Alpha1))
            {
                Chara t5 = CharaGen.Create("korgon");
                EClass._zone.AddCard(t5, hitPoint);
            }
            break;
        case DebugHotkey.Decal:
            if (Input.GetKeyDown(KeyCode.Alpha1))
            {
                EClass._map.AddDecal(hitPoint.x, hitPoint.z, EClass.pc.material.decal);
            }
            if (!Input.GetKeyDown(KeyCode.Alpha2))
            {
            }
            break;
        case DebugHotkey.Test:
            if (Input.GetKeyDown(KeyCode.Alpha1))
            {
                QualitySettings.vSyncCount = 0;
                Application.targetFrameRate = 60;
            }
            if (Input.GetKeyDown(KeyCode.Alpha2))
            {
                QualitySettings.vSyncCount = 0;
                Application.targetFrameRate = 20;
            }
            if (Input.GetKeyDown(KeyCode.Alpha3))
            {
                QualitySettings.vSyncCount = 0;
                Application.targetFrameRate = 30;
            }
            if (Input.GetKeyDown(KeyCode.Alpha4))
            {
                QualitySettings.vSyncCount = 0;
                Application.targetFrameRate = 40;
            }
            break;
        }
        Card card = (Card)(((object)hitPoint.FirstChara) ?? ((object)hitPoint.FirstThing));
        if (card == null)
        {
            return;
        }
        CharaActorPCC charaActorPCC = (card.renderer.actor as CharaActor) as CharaActorPCC;
        if ((bool)charaActorPCC)
        {
            if (Input.GetKeyDown(KeyCode.Keypad0))
            {
                charaActorPCC.NextFrame();
                charaActorPCC.RefreshSprite();
            }
            if (Input.GetKeyDown(KeyCode.Keypad1))
            {
                charaActorPCC.NextDir();
                card.angle = charaActorPCC.provider.angle;
                charaActorPCC.RefreshSprite();
            }
            if (Input.GetKeyDown(KeyCode.Keypad2))
            {
                charaActorPCC.pcc.data.Randomize();
                charaActorPCC.provider.Rebuild();
            }
        }
        if (Input.GetKeyDown(KeyCode.Keypad4))
        {
            lastEmo = lastEmo.NextEnum();
            card.ShowEmo();
            card.ShowEmo(lastEmo);
        }
        if (Input.GetKeyDown(KeyCode.Keypad5))
        {
            card.ShowEmo();
            card.ShowEmo(lastEmo);
        }
        if (Input.GetKeyDown(KeyCode.Keypad7))
        {
            lastAnime = lastAnime.NextEnum();
            card.renderer.PlayAnime(lastAnime);
        }
        if (Input.GetKeyDown(KeyCode.Keypad8))
        {
            card.renderer.PlayAnime(lastAnime);
            animeDest = card;
        }
        if (Input.GetKeyDown(KeyCode.Keypad9))
        {
            card.renderer.PlayAnime(AnimeID.Attack, animeDest);
        }
    }
References EClass._map, EClass._zone, Scene.actionMode, AM_MoveInstalled.Activate(), MiniGame.Activate(), QuestManager.Add(), Zone.AddCard(), Chara.AddCondition(), Map.AddDecal(), Card.AddExp(), advanceMin, GameDate.AdvanceMin(), Props.all, Card.angle, animeDest, Point.area, SpawnSetting.Boss(), EClass.Branch, CellDetail.charas, Map.charas, Steam.CheckUpdate(), EClass.core, ThingGen.Create(), CharaGen.Create(), World.date, ActionMode.Deactivate(), Map.deadCharas, debugHotkeys, debugInput, Point.detail, Card.dir, Card.elements, EnableDebugResource(), MapSubset.Exist(), Card.ExpToNext, Map.FindThing(), Point.FirstChara, Point.FirstThing, GameUpdater.FixedUpdate(), Player.flags, Card.flipX, EClass.game, QuestManager.Get(), FactionBranch.GetNextExp(), SourcePref.height, Scene.HitPoint, Player.hotbars, Card.id, Game.id, Spatial.id, indexResolution, Scene.Init(), ActionMode.Inspect, WidgetFeed.Instance, ActionMode.IsBuildMode, Chara.IsHostile(), Card.isSynced, Point.IsValid, lastAnime, lastEmo, Point.ListCards(), Game.Load(), Player.Flags.loytelMartLv, Chara.MakeBraineCell(), Chara.MakeEgg(), Chara.MakeGene(), Chara.MakeMilk(), Card.material, Party.members, FactionBranch.ModExp(), Scene.mouseTarget, TraitNewZone.MoveZone(), Card.Name, WidgetFeed.Nerun(), CharaActorPCC.NextDir(), CharaActorPCC.NextFrame(), WidgetMenuPanel.OnChangeMode(), param1, param2, Spatial.parent, Chara.party, EClass.pc, CharaActorPCC.pcc, Chara.Pick(), CardRenderer.PlayAnime(), Card.PlayEffect(), EClass.player, Card.PlaySound(), Card.pos, Thing.Pref, CharaActorPCC.provider, Game.quests, CharaActorPCC.RefreshSprite(), Spatial.RegionPos, Zone.RemoveCard(), Party.RemoveMember(), Card.renderer, HotbarManager.ResetHotbar(), resolutions, EScriptable.rnd(), Map.Roaming, runtimeGodBuild, Game.Save(), MapSubset.Save(), Msg.Say(), EClass.scene, ElementContainer.SetBase(), Weather.SetCondition(), Card.SetEncLv(), Chara.SetGlobal(), Map.SetLiquid(), Card.SetPlaceState(), Card.ShowEmo(), EClass.Sound, Thing.source, Zone.SpawnMob(), QuestManager.Start(), Core.steam, RenderObject.syncList, PointTarget.TargetChara, ThingGen.TestCreate(), TestSpawn(), CellDetail.things, Card.trait, Zone.TryGenerateEvolved(), Card.TryMakeRandomItem(), EClass.ui, Game.updater, World.weather, EClass.world, Game.world, Point.x, and Point.z.
Referenced by ActionMode.UpdateInput().
ValidateData()
void CoreDebug.ValidateData () inline
Definition at line 813 of file CoreDebug.cs.
    {
        if (EClass.core.IsGameStarted)
        {
            EClass._map.Stocked.Validate();
            EClass._map.Roaming.Validate();
            EClass._map.Installed.Validate();
        }
    }
References EClass._map, EClass.core, Map.Installed, Core.IsGameStarted, Map.Roaming, Map.Stocked, and Props.Validate().
ZoneIDs()
IEnumerable< string > CoreDebug.ZoneIDs () inline private
Definition at line 318 of file CoreDebug.cs.
    {
        List<SourceZone.Row> rows = EClass.sources.zones.rows;
        List<string> list = new List<string>();
        foreach (SourceZone.Row item in rows)
        {
            list.Add(item.id);
        }
        return list;
    }
References EClass.sources, and SourceManager.zones.
Member Data Documentation
_godBuild
bool CoreDebug._godBuild
Definition at line 178 of file CoreDebug.cs.
advanceMin
int CoreDebug.advanceMin
Definition at line 145 of file CoreDebug.cs.
Referenced by UpdateInput().
allAbility
bool CoreDebug.allAbility
Definition at line 190 of file CoreDebug.cs.
Referenced by QuickStart().
allArt
bool CoreDebug.allArt
Definition at line 196 of file CoreDebug.cs.
Referenced by ContentGallery.OnSwitchContent().
allBGM
bool CoreDebug.allBGM
Definition at line 198 of file CoreDebug.cs.
Referenced by LayerEditPlaylist.Refresh().
allHomeSkill
bool CoreDebug.allHomeSkill
Definition at line 194 of file CoreDebug.cs.
Referenced by FactionBranch.OnClaimZone().
allMenu
bool CoreDebug.allMenu
Definition at line 234 of file CoreDebug.cs.
allPolicy
bool CoreDebug.allPolicy
Definition at line 236 of file CoreDebug.cs.
Referenced by FactionBranch.OnClaimZone().
allRecipe
bool CoreDebug.allRecipe
Definition at line 232 of file CoreDebug.cs.
Referenced by RecipeManager.IsKnown(), OnLoad(), and QuickStart().
allSkill
bool CoreDebug.allSkill
Definition at line 192 of file CoreDebug.cs.
Referenced by QuickStart().
allStory
bool CoreDebug.allStory
Definition at line 238 of file CoreDebug.cs.
Referenced by TraitStoryBook.OnRead().
alwaysFavFood
bool CoreDebug.alwaysFavFood
Definition at line 227 of file CoreDebug.cs.
Referenced by Affinity.OnGift().
alwaysResetWindow
bool CoreDebug.alwaysResetWindow
Definition at line 127 of file CoreDebug.cs.
Referenced by ELayer.Kill().
animeDest
Card CoreDebug.animeDest private
Definition at line 274 of file CoreDebug.cs.
Referenced by UpdateInput().
autoAdvanceQuest
bool CoreDebug.autoAdvanceQuest
Definition at line 210 of file CoreDebug.cs.
Referenced by QuestDeliver.CanDeliverToClient(), QuestDeliver.Deliver(), and QuestManager.OnShowDialog().
autoIdentify
bool CoreDebug.autoIdentify
Definition at line 188 of file CoreDebug.cs.
Referenced by Thing.OnCreate().
bidx
int CoreDebug.bidx private
Definition at line 277 of file CoreDebug.cs.
bilinear
bool CoreDebug.bilinear private
Definition at line 279 of file CoreDebug.cs.
blines
string [] CoreDebug.blines private
Definition at line 282 of file CoreDebug.cs.
boradcast
bool CoreDebug.boradcast
Definition at line 261 of file CoreDebug.cs.
Referenced by AM_Adv._OnUpdateInput().
command
string CoreDebug.command
Definition at line 135 of file CoreDebug.cs.
Referenced by Core.Awake().
commands
List<DebugCommand> CoreDebug.commands = new List<DebugCommand>()
Definition at line 284 of file CoreDebug.cs.
Referenced by InitDebugCommands(), and LayerDebug.OnSwitchContent().
debugHoard
bool CoreDebug.debugHoard
Definition at line 155 of file CoreDebug.cs.
Referenced by LayerHoard.OnAfterInit().
debugHotkeys
DebugHotkey CoreDebug.debugHotkeys
Definition at line 142 of file CoreDebug.cs.
Referenced by ActionMode.UpdateInput(), and UpdateInput().
debugInput
bool CoreDebug.debugInput
Definition at line 138 of file CoreDebug.cs.
Referenced by UpdateInput().
debugProps
bool CoreDebug.debugProps
Definition at line 151 of file CoreDebug.cs.
debugScatter
bool CoreDebug.debugScatter
Definition at line 176 of file CoreDebug.cs.
dontCompressSave
bool CoreDebug.dontCompressSave
Definition at line 131 of file CoreDebug.cs.
dontUseThread
bool CoreDebug.dontUseThread
Definition at line 121 of file CoreDebug.cs.
Referenced by LayerProgress.Start().
enable
bool CoreDebug.enable
Definition at line 287 of file CoreDebug.cs.
Referenced by AM_Adv._OnUpdateInput(), WidgetDate._Refresh(), WidgetSystemIndicator._Refresh(), ActPlan._Update(), DramaCustomSequence.Build(), RecipeCard.Build(), Chara.CanAcceptItem(), FactionBranch.CanUpgrade(), CheatEnabled(), LayerFeedback.CollectFiles(), RecipeManager.ComeUpWithRecipe(), RecipeCard.Craft(), Player.CreateEquip(), Region.CreateRandomSite(), SpatialGen.CreateRecursive(), Trait.CreateStock(), WidgetManager.DialogSave(), EnableDebugResource(), HitSummary.Execute(), ZonePreEnterEncounter.Execute(), DNA.Generate(), FactionBranch.GenerateGarbage(), Net.GetChat(), Thing.GetExtraName(), TraitGeneMachine.GetProgress(), Region.GetRandomSiteSource(), AM_MoveInstalled.HitTest(), CoreConfig.Init(), Scene.Init(), Props.ListThingStack(), Chara.MakeEgg(), AI_Fish.Makefish(), BuildMenu.OnActivate(), WidgetArtTool.OnActivate(), GlobalGoalAdv.OnAdvanceHour(), Region.OnAdvanceHour(), Trait.OnBarter(), Chara.OnCreate(), Game.OnGameInstantiated(), LayerMod.OnInit(), LayerNewspaper.OnInit(), AI_Fish.ProgressFish.OnProgressComplete(), TaskDig.OnProgressComplete(), TraitDeed.OnRead(), TileSelectorElona.OnRenderTile(), HotItemLayer.OnSetItem(), AM_FlagCell.OnSetSubMenuButton(), ContentQuest.OnSwitchContent(), AM_Inspect.OnUpdateInput(), TileSelectorElona.OnUpdateInput(), TraitDaggerGrave.OnUse(), TraitGeneMachine.OnUse(), TraitGiftJure.OnUse(), ZoneEventMusic.OnVisit(), ActRide.Perform(), FoodEffect.Proc(), ActEffect.ProcAt(), Map.PutAway(), WindowCharaMini.Refresh(), UIInventory.RefreshMenu(), ContentConfigOther.RefreshRewardCode(), Chara.Revive(), ActionMode.RotateUnderMouse(), AI_Idle.Run(), AI_OpenGambleChest.Run(), AI_PassTime.Run(), AI_PlayMusic.Run(), Net.SendChat(), GameDate.ShipRandomPackages(), HotItemContext.Show(), UI.ShowLang(), Core.StartCase(), ActThrow.Throw(), ConDisease.Tick(), UI.ToggleFeedback(), Chara.TryDropBossLoot(), Religion.TryGetGift(), TraitEffect.TrySetAct(), TraitElevator.TrySetAct(), TraitHouseBoard.TrySetAct(), TraitMapBoard.TrySetAct(), TraitPaintBoard.TrySetAct(), TraitRoomPlate.TrySetAct(), TraitTeleporter.TrySetAct(), TraitWell.TrySetAct(), AI_Shopping.TryShop(), Zone.TrySpawnFollower(), Chara.TryUpgrade(), LayerHoard.Update(), LayerUploader.Update(), UpdateAlways(), ActionMode.UpdateInput(), Zone.UpdateQuests(), TraitWrench.Upgrade(), and LayerUploader.Upload().
enableMapPieceEditor
bool CoreDebug.enableMapPieceEditor
Definition at line 212 of file CoreDebug.cs.
fixedColor
Color32 CoreDebug.fixedColor
Definition at line 265 of file CoreDebug.cs.
fov
Fov CoreDebug.fov = new Fov()
Definition at line 289 of file CoreDebug.cs.
godCraft
bool CoreDebug.godCraft
Definition at line 180 of file CoreDebug.cs.
Referenced by RecipeCard.Craft(), UIDragGridInfo.Init(), RecipeManager.ListSources(), and AI_UseCrafter.Run().
godFood
bool CoreDebug.godFood
Definition at line 182 of file CoreDebug.cs.
Referenced by AI_Eat.Run(), and Card.SpawnLoot().
godMode
bool CoreDebug.godMode
Definition at line 172 of file CoreDebug.cs.
Referenced by Chara.CanSleep(), Card.DamageHP(), StatsMana.Mod(), StatsStamina.Mod(), Faction.OnAdvanceMonth(), TraitStairsLocked.OnUse(), ActRanged.Perform(), AI_Steal.Run(), Card.SpawnLoot(), Chara.TickConditions(), TraitBaseSpellbook.TryProgress(), and Chara.UseAbility().
hidePCItemsInBuild
bool CoreDebug.hidePCItemsInBuild
Definition at line 208 of file CoreDebug.cs.
Referenced by BuildMenu.RefreshCategory().
ignoreAutoSave
bool CoreDebug.ignoreAutoSave
Definition at line 125 of file CoreDebug.cs.
Referenced by LayerSleep.Advance(), Scene.Init(), Chara.MoveZone(), and Game.Save().
ignoreBuildRule
bool CoreDebug.ignoreBuildRule
Definition at line 184 of file CoreDebug.cs.
Referenced by ActionMode._HitTest(), TileType._HitTest(), Recipe.Build(), HitSummary.CanExecute(), AM_MoveInstalled.CanPutAway(), AM_MoveInstalled.CheckEnemyNearBy(), HitSummary.Execute(), TaskBuild.GetHitResult(), AM_MoveInstalled.HitTest(), AM_Deconstruct.Perform(), Map.PutAway(), HotbarManager.ResetHotbar(), and PointTarget.ShouldIgnore().
ignoreEncounter
bool CoreDebug.ignoreEncounter
Definition at line 200 of file CoreDebug.cs.
Referenced by Chara.Tick().
ignorePool
bool CoreDebug.ignorePool
Definition at line 116 of file CoreDebug.cs.
Referenced by Core.Update().
ignorePopup
bool CoreDebug.ignorePopup
Definition at line 159 of file CoreDebug.cs.
Referenced by PopupManager.Add().
ignoreWeight
bool CoreDebug.ignoreWeight
Definition at line 186 of file CoreDebug.cs.
Referenced by Chara.CalcBurden(), Chara.GetBurden(), Chara.Tick(), and Player.TooHeavyToMove().
indexResolution
int CoreDebug.indexResolution private
Definition at line 291 of file CoreDebug.cs.
Referenced by UpdateInput().
instaReturn
bool CoreDebug.instaReturn
Definition at line 204 of file CoreDebug.cs.
Referenced by AM_Adv._OnUpdateInput().
inviteAnytime
bool CoreDebug.inviteAnytime
Definition at line 221 of file CoreDebug.cs.
Referenced by Affinity.CanInvite().
keypadDebug
bool CoreDebug.keypadDebug
Definition at line 140 of file CoreDebug.cs.
langCode
Lang.LangCode CoreDebug.langCode
Definition at line 113 of file CoreDebug.cs.
Referenced by Core.Awake().
lastAnime
AnimeID CoreDebug.lastAnime private
Definition at line 293 of file CoreDebug.cs.
Referenced by UpdateInput().
lastEmo
Emo CoreDebug.lastEmo private
Definition at line 295 of file CoreDebug.cs.
Referenced by UpdateInput().
logAdv
bool CoreDebug.logAdv
Definition at line 243 of file CoreDebug.cs.
Referenced by GlobalGoalVisitAndStay.OnAdvanceHour().
logCombat
bool CoreDebug.logCombat
Definition at line 246 of file CoreDebug.cs.
Referenced by GoalCombat.Run(), GoalCombat.TryMove(), and GoalCombat.TryUseAbility().
logDice
bool CoreDebug.logDice
Definition at line 248 of file CoreDebug.cs.
Referenced by Check.Perform(), and DramaActor.SetChoice().
marryAnytime
bool CoreDebug.marryAnytime
Definition at line 223 of file CoreDebug.cs.
Referenced by Affinity.CanMarry(), and Affinity.CanSleepBeside().
matColorTest
MatColorTest CoreDebug.matColorTest
Definition at line 259 of file CoreDebug.cs.
maxQuests
bool CoreDebug.maxQuests
Definition at line 229 of file CoreDebug.cs.
naked
bool CoreDebug.naked private
Definition at line 297 of file CoreDebug.cs.
numResource
int CoreDebug.numResource
Definition at line 216 of file CoreDebug.cs.
Referenced by EnableDebugResource().
param1
int CoreDebug.param1
Definition at line 254 of file CoreDebug.cs.
Referenced by UpdateInput().
param2
int CoreDebug.param2
Definition at line 257 of file CoreDebug.cs.
Referenced by UpdateInput().
randomResource
bool CoreDebug.randomResource
Definition at line 174 of file CoreDebug.cs.
Referenced by SetStartStockpile().
resetPlayerConfig
bool CoreDebug.resetPlayerConfig
Definition at line 119 of file CoreDebug.cs.
Referenced by WidgetManager.OnGameInstantiated(), and Player.OnLoad().
resolutions
readonly List<int[]> CoreDebug.resolutions private
Initial value:
= new List<int[]>
    {
        new int[2] { 1920, 1080 },
        new int[2] { 1366, 768 },
        new int[2] { 1280, 720 }
    }
Definition at line 267 of file CoreDebug.cs.
Referenced by UpdateInput().
returnAnywhere
bool CoreDebug.returnAnywhere
Definition at line 202 of file CoreDebug.cs.
Referenced by SpatialManager.ListReturnLocations(), and Region.ListTravelZones().
revealInner
bool CoreDebug.revealInner
Definition at line 157 of file CoreDebug.cs.
revealMap
bool CoreDebug.revealMap
Definition at line 153 of file CoreDebug.cs.
Referenced by HotItemContext.Show().
runtimeGodBuild
bool CoreDebug.runtimeGodBuild private
Definition at line 300 of file CoreDebug.cs.
Referenced by UpdateInput().
showExtra
bool CoreDebug.showExtra
Definition at line 167 of file CoreDebug.cs.
Referenced by WidgetDate._Refresh(), ActPlan._Update(), Element._WriteNote(), ElementContainer.AddNote(), Thing.GetHoverText(), Chara.GetHoverText2(), ContentQuest.OnSwitchContent(), UIRecipeInfo.Refresh(), WindowChara.RefreshNote(), UIHomeInfo.RefreshReport(), ContentQuest.SelectQuest(), DNA.WriteNote(), HomeResourceWorth.WriteNote(), Thing.WriteNote(), and TraitGene.WriteNote().
showFav
bool CoreDebug.showFav
Definition at line 225 of file CoreDebug.cs.
Referenced by DramaCustomSequence.Build().
showSceneSelector
bool CoreDebug.showSceneSelector
Definition at line 108 of file CoreDebug.cs.
Referenced by UI.ShowLang(), and Core.StartCase().
showTone
bool CoreDebug.showTone
Definition at line 165 of file CoreDebug.cs.
skipEvent
bool CoreDebug.skipEvent
Definition at line 161 of file CoreDebug.cs.
Referenced by ZoneEventManager.Add().
skipInitialQuest
bool CoreDebug.skipInitialQuest
Definition at line 240 of file CoreDebug.cs.
Referenced by LayerEditBio.OnClickStart().
skipMod
bool CoreDebug.skipMod
Definition at line 133 of file CoreDebug.cs.
Referenced by ModManager.Init(), and ModManager.RefreshMods().
skipModSync
bool CoreDebug.skipModSync
Definition at line 111 of file CoreDebug.cs.
Referenced by Core.StartCase().
skipNerun
bool CoreDebug.skipNerun
Definition at line 163 of file CoreDebug.cs.
Referenced by LayerDrama.ActivateNerun(), and QuickStart().
startHour
int CoreDebug.startHour
Definition at line 101 of file CoreDebug.cs.
Referenced by QuickStart().
startLoadout
StartLoadout CoreDebug.startLoadout
Definition at line 97 of file CoreDebug.cs.
Referenced by QuickStart().
startParty
StartParty CoreDebug.startParty
Definition at line 99 of file CoreDebug.cs.
Referenced by QuickStart().
startScene
StartScene CoreDebug.startScene
Definition at line 95 of file CoreDebug.cs.
Referenced by Core.Init(), QuickStart(), and Game.StartNewGame().
startSetting
StartSetting CoreDebug.startSetting
Definition at line 103 of file CoreDebug.cs.
Referenced by QuickStart().
startZone
string CoreDebug.startZone
Definition at line 105 of file CoreDebug.cs.
Referenced by Game.StartNewGame().
test
bool CoreDebug.test
Definition at line 169 of file CoreDebug.cs.
Referenced by Zone.TryGenerateShrine().
testFixedColor
bool CoreDebug.testFixedColor
Definition at line 263 of file CoreDebug.cs.
testLOS
bool CoreDebug.testLOS
Definition at line 147 of file CoreDebug.cs.
Referenced by HotItemContext.Show(), and GameUpdater.Update().
testLOS2
bool CoreDebug.testLOS2
Definition at line 149 of file CoreDebug.cs.
Referenced by HotItemContext.Show(), and GameUpdater.Update().
testThingQuality
bool CoreDebug.testThingQuality
Definition at line 214 of file CoreDebug.cs.
Referenced by Card.Create().
travelAnywhere
bool CoreDebug.travelAnywhere
Definition at line 206 of file CoreDebug.cs.
Referenced by Spatial.Create().
ttt
int CoreDebug.ttt private
Definition at line 302 of file CoreDebug.cs.
unlimitedInterest
bool CoreDebug.unlimitedInterest
Definition at line 219 of file CoreDebug.cs.
Referenced by Affinity.OnTalkRumor().
useNewConfig
bool CoreDebug.useNewConfig
Definition at line 123 of file CoreDebug.cs.
Referenced by CoreConfig.Exist(), CoreConfig.Init(), and CoreConfig.TryLoadConfig().
validateData
bool CoreDebug.validateData
Definition at line 129 of file CoreDebug.cs.
validatePref
bool CoreDebug.validatePref
Definition at line 251 of file CoreDebug.cs.
Referenced by Core.Init().
Property Documentation
EnableCheat
string CoreDebug.EnableCheat static get
Definition at line 316 of file CoreDebug.cs.
godBuild
bool CoreDebug.godBuild get
Definition at line 304 of file CoreDebug.cs.
    {
        get
        {
            if (!_godBuild)
            {
                return runtimeGodBuild;
            }
            return true;
        }
    }
Referenced by BuildMenu._Search(), BuildMenu.Activate(), DropdownGrid.BuildIngredients(), BaseTileMap.DrawTile(), Map.DropBlockComponent(), HitSummary.Execute(), TaskCut.GetHitResult(), TaskHarvest.GetHitResult(), AM_Build.IsFillMode(), Map.MineObj(), BuildMenu.OnActivate(), TraitBlueprint.OnRead(), BuildMenu.RefreshCategory(), HotbarManager.ResetHotbar(), AM_Adv.ShowAllAction(), BuildMenu.Toggle(), TraitBuildBoard.TrySetAct(), and ActionMode.UpdateInput().
The documentation for this class was generated from the following file:
Elin/CoreDebug.cs