Elin Decompiled Documentation: GoalAutoCombat Class Reference
GoalAutoCombat Class Reference
Public Member Functions
override Color GetActPlanColor ()
GoalAutoCombat (Chara e)
override bool TryUseRanged (int dist)
void GetAbilities (Func< Element, bool > func)
override void BuildAbilityList ()
override bool TryAbortCombat ()
Public Member Functions inherited from GoalCombat
override bool CanManualCancel ()
override IEnumerable< Status > Run ()
bool TryMove (int dist)
void AddAbility (Act a, int mod=0, int chance=100, bool aiPt=false)
virtual bool TryUseRanged (int dist)
virtual bool TryThrow (int dist)
virtual bool TryUseAbility (int dist, bool beforeMove=false)
virtual void BuildAbilityList ()
virtual bool TryAbortCombat ()
Public Member Functions inherited from Goal
Goal Duplicate ()
Public Member Functions inherited from AIAct
override string ToString ()
override MultiSprite GetStateIcon ()
virtual Point GetDestination ()
AIProgress GetProgress ()
string GetCurrentActionText ()
override bool IsToolValid ()
virtual void OnStart ()
void SetOwner (Chara c)
virtual void OnSetOwner ()
void SetChild (AIAct seq, Func< Status > _onChildFail=null)
void Start ()
override bool Perform ()
Status Restart ()
Status Success (Action action=null)
virtual void OnSuccess ()
bool TryCancel (Card c)
virtual Status Cancel ()
virtual void OnCancel ()
virtual void OnCancelOrSuccess ()
virtual bool CanManualCancel ()
Status KeepRunning ()
void Reset ()
virtual void OnReset ()
Status Tick ()
virtual IEnumerable< Status > Run ()
Status TickChild ()
Status Do (AIAct _seq, Func< Status > _onChildFail=null)
Status DoGotoInteraction (Point pos, Func< Status > _onChildFail=null)
Status DoGoto (Point pos, int dist=0, bool ignoreConnection=false, Func< Status > _onChildFail=null)
Status DoGoto (Card card, Func< Status > _onChildFail=null)
Status DoGoto (Card card, int dist, Func< Status > _onChildFail=null)
Status DoGotoSpot (Card card, Func< Status > _onChildFail=null)
Status DoGoto< T > (Func< Status > _onChildFail=null)
Status DoGotoSpot< T > (Func< Status > _onChildFail=null, bool ignoreAccessType=false)
Status DoGrab (Card card, int num=-1, bool pickHeld=false, Func< Status > _onChildFail=null)
Status DoGrab< T > ()
Status DoProgress ()
Status DoIdle (int repeat=3)
Status DoWait (int count=1)
virtual AIProgress CreateProgress ()
virtual void OnCreateProgress (Progress_Custom p)
virtual bool CanProgress ()
virtual void OnBeforeProgress ()
virtual void OnProgress ()
virtual void OnProgressComplete ()
void SimulateZone (int days)
virtual void OnSimulateZone (int days)
virtual void OnSimulatePosition ()
Public Member Functions inherited from Act
virtual CursorInfo GetCursorIcon (Card c)
virtual MultiSprite GetStateIcon ()
override Sprite GetSprite ()
virtual bool ShowMouseHint (Card c)
virtual bool IsValidTC (Card c)
virtual string GetHintText (string str="")
virtual string GetText (string str="")
virtual string GetTextSmall (Card c)
virtual Color GetActPlanColor ()
virtual bool Perform ()
virtual bool CanPerform ()
bool Perform (Chara _cc, Card _tc=null, Point _tp=null)
bool CanPerform (Chara _cc, Card _tc=null, Point _tp=null)
virtual bool IsToolValid ()
new void SetImage (Image image)
virtual void OnMarkMapHighlights ()
virtual bool ShouldMapHighlight (Point p)
virtual CursorInfo GetCursorIcon (Card c)
virtual MultiSprite GetStateIcon ()
override Sprite GetSprite ()
virtual bool ShowMouseHint (Card c)
virtual bool IsValidTC (Card c)
virtual string GetHintText (string str="")
virtual string GetText (string str="")
virtual string GetTextSmall (Card c)
virtual Color GetActPlanColor ()
virtual bool Perform ()
virtual bool CanPerform ()
bool Perform (Chara _cc, Card _tc=null, Point _tp=null)
bool CanPerform (Chara _cc, Card _tc=null, Point _tp=null)
virtual bool IsToolValid ()
new void SetImage (Image image)
virtual void OnMarkMapHighlights ()
virtual bool ShouldMapHighlight (Point p)
Public Member Functions inherited from Element
virtual SourceElement.Row GetSource ()
virtual int GetSourcePotential (int v)
virtual Sprite GetSprite ()
int GetMaterialSourceValue (Thing t, int v)
virtual int GetSourceValue (int v, int lv, SourceValueType type)
virtual Sprite GetIcon (string suffix="")
int SortVal (bool charaSheet=false)
virtual bool CanLink (ElementContainer owner)
bool HasTag (string tag)
void SetImage (Image i)
virtual string GetDetail ()
bool IsFactionElement (Chara c)
Element GetParent (Card c)
void WriteNote (UINote n, ElementContainer owner=null, Action< UINote > onWriteNote=null)
void WriteNoteWithRef (UINote n, ElementContainer owner, Action< UINote > onWriteNote, Element refEle)
void _WriteNote (UINote n, Chara c, Act act)
void _WriteNote (UINote n, ElementContainer owner, Action< UINote > onWriteNote, bool isRef, bool addHeader=true)
virtual void OnWriteNote (UINote n, ElementContainer owner)
virtual void OnChangeValue ()
void CheckLevelBonus (ElementContainer owner, UINote n=null)
int GetSortVal (UIList.SortMode m)
virtual Act.Cost GetCost (Chara c)
virtual int GetPower (Card c)
virtual void SetTextValue (UIText text)
virtual SourceElement.Row GetSource ()
virtual int GetSourcePotential (int v)
virtual Sprite GetSprite ()
int GetMaterialSourceValue (Thing t, int v)
virtual int GetSourceValue (int v, int lv, SourceValueType type)
virtual Sprite GetIcon (string suffix="")
int SortVal (bool charaSheet=false)
virtual bool CanLink (ElementContainer owner)
bool HasTag (string tag)
void SetImage (Image i)
virtual string GetDetail ()
bool IsFactionElement (Chara c)
Element GetParent (Card c)
void WriteNote (UINote n, ElementContainer owner=null, Action< UINote > onWriteNote=null)
void WriteNoteWithRef (UINote n, ElementContainer owner, Action< UINote > onWriteNote, Element refEle)
void _WriteNote (UINote n, Chara c, Act act)
void _WriteNote (UINote n, ElementContainer owner, Action< UINote > onWriteNote, bool isRef, bool addHeader=true)
virtual void OnWriteNote (UINote n, ElementContainer owner)
virtual void OnChangeValue ()
void CheckLevelBonus (ElementContainer owner, UINote n=null)
int GetSortVal (UIList.SortMode m)
virtual Act.Cost GetCost (Chara c)
virtual int GetPower (Card c)
virtual void SetTextValue (UIText text)
Public Attributes
Thing renderThing
List< Chara > listHealthy = new List<Chara>()
Public Attributes inherited from GoalCombat
Chara destEnemy
Chara tc
int idleCount
int moveFail
List< ItemAbility > abilities
List< Chara > charas = new List<Chara>()
Public Attributes inherited from AIAct
new Chara owner
Status status
IEnumerator< Status > Enumerator
AIAct child
AIAct parent
byte restartCount
Func< Status > onChildFail
Func< bool > isFail
Public Attributes inherited from Element
SourceElement.Row _source
int id
int vBase
int vExp
int vPotential
int vTempPotential
int vLink
int vSource
int vSourcePotential
ElementContainer owner
Properties
override bool UseTurbo [get]
override Thing RenderThing [get]
ConfigAutoCombat config [get]
Properties inherited from GoalCombat
override CursorInfo CursorIcon [get]
override bool CancelWhenDamaged [get]
Tactics tactics [get]
Properties inherited from Goal
override bool InformCancel [get]
Properties inherited from AIAct
virtual bool IsRunning [get]
bool IsChildRunning [get]
bool IsMoveAI [get]
virtual int MaxRestart [get]
virtual new string Name [get]
virtual MultiSprite stateIcon [get]
virtual Sprite actionIcon [get]
virtual bool IsNoGoal [get]
virtual bool IsAutoTurn [get]
virtual bool IsIdle [get]
virtual bool PushChara [get]
virtual int MaxProgress [get]
virtual bool ShowProgress [get]
virtual bool UseTurbo [get]
virtual int CurrentProgress [get]
virtual bool ShowCursor [get]
virtual bool CancelWhenDamaged [get]
virtual bool CancelWhenMoved [get]
virtual bool InformCancel [get]
virtual Thing RenderThing [get]
AIAct Current [get]
override bool IsAct [get]
override bool ShowPotential [get]
override bool UsePotential [get]
override bool ShowRelativeAttribute [get]
virtual bool HasProgress [get]
Properties inherited from Act
override bool ShowPotential [get]
override bool UsePotential [get]
override bool ShowRelativeAttribute [get]
virtual CursorInfo CursorIcon [get]
virtual string ID [get]
virtual bool IsAct [get]
virtual bool WillEndTurn [get]
virtual bool CloseLayers [get]
virtual int LeftHand [get]
virtual int RightHand [get]
virtual int ElementPowerMod [get]
virtual bool ShowMapHighlight [get]
virtual bool ShowMapHighlightBlock [get]
virtual bool PickHeldOnStart [get]
virtual bool DropHeldOnStart [get]
virtual bool CanPressRepeat [get]
virtual bool CanAutofire [get]
virtual bool ResetAxis [get]
virtual bool RequireTool [get]
virtual bool IsHostileAct [get]
virtual bool HideRightInfo [get]
virtual bool HaveLongPressAction [get]
virtual float Radius [get]
virtual int PerformDistance [get]
virtual int MaxRadius [get]
virtual TargetType TargetType [get]
virtual bool LocalAct [get]
virtual bool CanRapidFire [get]
virtual float RapidDelay [get]
virtual bool ShowAuto [get]
virtual bool IsCrime [get]
Properties inherited from Element
SourceElement.Row source [get]
virtual int DisplayValue [get]
virtual int MinValue [get]
int Value [get]
int ValueWithoutLink [get]
virtual int MinPotential [get]
int Potential [get]
virtual bool CanGainExp [get]
bool IsFlag [get]
virtual string Name [get]
virtual string FullName [get]
virtual int ExpToNext [get]
virtual bool UseExpMod [get]
virtual int CostTrain [get]
virtual int CostLearn [get]
virtual bool ShowXP [get]
virtual bool ShowMsgOnValueChanged [get]
virtual bool ShowValue [get]
virtual bool ShowPotential [get]
virtual bool UsePotential [get]
virtual bool PotentialAsStock [get]
virtual bool ShowRelativeAttribute [get]
virtual bool ShowBonuses [get]
virtual string ShortName [get]
bool IsGlobalElement [get]
bool IsFactionWideElement [get]
bool IsPartyWideElement [get]
virtual bool ShowEncNumber [get]
bool IsTrait [get]
bool IsFoodTrait [get]
bool IsFoodTraitMain [get]
bool IsMainAttribute [get]
Act act [get]
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Additional Inherited Members
Public Types inherited from AIAct
enum Status { Running , Fail , Success }
Public Types inherited from Act
enum CostType {
None , MP , SP , None ,
MP , SP
}
enum CostType {
None , MP , SP , None ,
MP , SP
}
Static Public Member Functions inherited from Act
static void SetReference (Chara _cc, Card _tc=null, Point _tp=null)
static void SetTool (Thing t)
static void SetReference (Chara _cc, Card _tc=null, Point _tp=null)
static void SetTool (Thing t)
Static Public Member Functions inherited from Element
static string GetName (string alias)
static SourceElement.Row Get (int id)
static Dictionary< int, int > GetElementMap (int[] list)
static Dictionary< int, int > GetElementMap (int[] list, Dictionary< int, int > map)
static SourceElement.Row GetRandomElement (int lv=1)
static Element Create (int id, int v=0)
static Element Create (string id, int v=1)
static int GetId (string alias)
static int GetResistLv (int v)
static int GetResistDamage (int dmg, int v)
static string GetName (string alias)
static SourceElement.Row Get (int id)
static Dictionary< int, int > GetElementMap (int[] list)
static Dictionary< int, int > GetElementMap (int[] list, Dictionary< int, int > map)
static SourceElement.Row GetRandomElement (int lv=1)
static Element Create (int id, int v=0)
static Element Create (string id, int v=1)
static int GetId (string alias)
static int GetResistLv (int v)
static int GetResistDamage (int dmg, int v)
Static Public Member Functions inherited from EClass
static int rnd (int a)
static int curve (int a, int start, int step, int rate=75)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Static Public Attributes inherited from Act
static Chara CC
static Card TC
static Point TP = new Point()
static Thing TOOL
static int powerMod = 100
static bool forcePt
Static Public Attributes inherited from Element
const int Div = 5
static Element Void = new Element()
static int[] List_MainAttributes
static int[] List_MainAttributesMajor
static int[] List_Body
static int[] List_Mind
static List< SourceElement.Row > ListElements = new List<SourceElement.Row>()
static List< SourceElement.Row > ListAttackElements = new List<SourceElement.Row>()
Static Public Attributes inherited from EClass
static Core core
Static Package Functions inherited from Element
static string< _WriteNote > g__Calc (ref Element.<>c__DisplayClass103_0 A_0)
Detailed Description
Definition at line 6 of file GoalAutoCombat.cs.
Constructor & Destructor Documentation
GoalAutoCombat()
GoalAutoCombat.GoalAutoCombat (Chara e) inline
Definition at line 31 of file GoalAutoCombat.cs.
    {
        destEnemy = e;
        EClass.player.autoCombatStartHP = ((EClass.pc.Evalue(1421) > 0) ? (EClass.pc.hp + EClass.pc.mana.value) : EClass.pc.hp);
        foreach (Chara member in EClass.pc.party.members)
        {
            if (!member.IsCriticallyWounded())
            {
                listHealthy.Add(member);
            }
        }
    }
References GoalCombat.destEnemy, Card.Evalue(), Card.hp, Chara.IsCriticallyWounded(), listHealthy, Chara.mana, Party.members, Chara.party, EClass.pc, and Stats.value.
Member Function Documentation
BuildAbilityList()
override void GoalAutoCombat.BuildAbilityList () inline virtual
Reimplemented from GoalCombat.
Definition at line 117 of file GoalAutoCombat.cs.
    {
        GetAbilities((Element e) => e.source.abilityType.Length != 0);
        AddAbility(ACT.Ranged);
        AddAbility(ACT.Melee);
        AddAbility(ACT.Item);
    }
References ACT.Item, ACT.Melee, ACT.Ranged, and Element.source.
GetAbilities()
void GoalAutoCombat.GetAbilities (Func< Element, bool > func) inline
Definition at line 91 of file GoalAutoCombat.cs.
    {
        if (config.bUseHotBar)
        {
            foreach (Thing item in EClass.pc.things.Where((Thing t) => t.IsHotItem && t.trait is TraitAbility))
            {
                Element element = owner.elements.GetElement(item.c_idAbility);
                if (element != null && func(element) && (element.id != 9150 || EClass.player.favAbility.Contains(element.id)))
                {
                    AddAbility(element.act, 15);
                }
            }
        }
        if (!config.bUseInventory)
        {
            return;
        }
        foreach (Element value in owner.elements.dict.Values)
        {
            if ((!config.bUseFav || EClass.player.favAbility.Contains(value.id)) && func(value) && (value.id != 9150 || EClass.player.favAbility.Contains(value.id)))
            {
                AddAbility(value.act);
            }
        }
    }
References Element.act, Card.c_idAbility, Player.favAbility, Element.id, Card.IsHotItem, EClass.pc, EClass.player, Card.things, and Card.trait.
GetActPlanColor()
override Color GoalAutoCombat.GetActPlanColor () inline virtual
Reimplemented from Act.
Definition at line 18 of file GoalAutoCombat.cs.
    {
        if (!EClass.pc.IsCriticallyWounded())
        {
            if (!EClass.pc.party.IsCriticallyWounded())
            {
                return EClass.Colors.colorAct;
            }
            return EClass.Colors.colorActWarnning;
        }
        return EClass.Colors.colorActCriticalWarning;
    }
References ColorProfile.colorAct, ColorProfile.colorActCriticalWarning, ColorProfile.colorActWarnning, EClass.Colors, Party.IsCriticallyWounded(), Chara.IsCriticallyWounded(), Chara.party, and EClass.pc.
TryAbortCombat()
override bool GoalAutoCombat.TryAbortCombat () inline virtual
Reimplemented from GoalCombat.
Definition at line 125 of file GoalAutoCombat.cs.
    {
        if (idleCount >= 2)
        {
            Msg.Say("abort_idle");
            return true;
        }
        return false;
    }
References Msg.Say().
TryUseRanged()
override bool GoalAutoCombat.TryUseRanged (int dist) inline virtual
Reimplemented from GoalCombat.
Definition at line 44 of file GoalAutoCombat.cs.
    {
        Thing ranged = owner.ranged;
        owner.ranged = null;
        if (config.bUseHotBar)
        {
            FindRanged(hotbar: true);
        }
        if (owner.ranged != null && ACT.Ranged.Perform(owner, tc))
        {
            if (owner == null)
            {
                return true;
            }
            renderThing = owner.ranged;
            if (owner.ranged != ranged)
            {
                owner.ranged = ranged;
            }
            return true;
        }
        return false;
        void FindRanged(bool hotbar)
        {
            owner.things.Foreach(delegate(Thing t)
            {
                if (t.IsHotItem)
                {
                    if (!hotbar)
                    {
                        return false;
                    }
                }
                else if (hotbar)
                {
                    return false;
                }
                if (t.IsRangedWeapon && (t.trait is TraitToolRangeCane || t.c_ammo > 0 || EClass.pc.FindAmmo(t) != null) && owner.CanEquipRanged(t))
                {
                    owner.ranged = t;
                    return true;
                }
                return false;
            });
        }
    }
References ConfigAutoCombat.bUseHotBar, Card.c_ammo, Chara.CanEquipRanged(), config, Chara.FindAmmo(), ThingContainer.Foreach(), Card.IsHotItem, Card.IsRangedWeapon, AIAct.owner, EClass.pc, ActRanged.Perform(), ACT.Ranged, Chara.ranged, renderThing, GoalCombat.tc, Card.things, and Card.trait.
Member Data Documentation
listHealthy
List<Chara> GoalAutoCombat.listHealthy = new List<Chara>()
Definition at line 10 of file GoalAutoCombat.cs.
Referenced by GoalAutoCombat().
renderThing
Thing GoalAutoCombat.renderThing
Definition at line 8 of file GoalAutoCombat.cs.
Referenced by TryUseRanged().
Property Documentation
config
ConfigAutoCombat GoalAutoCombat.config get
Definition at line 16 of file GoalAutoCombat.cs.
Referenced by TryUseRanged().
RenderThing
override Thing GoalAutoCombat.RenderThing get
Definition at line 14 of file GoalAutoCombat.cs.
UseTurbo
override bool GoalAutoCombat.UseTurbo get
Definition at line 12 of file GoalAutoCombat.cs.
The documentation for this class was generated from the following file:
Elin/GoalAutoCombat.cs