Elin Decompiled Documentation: ActionMode Class Reference
ActionMode Class Reference
Public Member Functions
virtual int TopHeight (Point p)
virtual void SEExecuteSummary ()
virtual bool HighlightWall (Point p)
virtual void OnClickSubMenu (int a)
virtual string OnSetSubMenuButton (int a, UIButton b)
virtual bool IsRoofEditMode (Card c=null)
virtual bool IsFillMode ()
virtual int GetDefaultTile (Point p)
virtual void OnShowExtraHint (UINote n)
void Activate (bool toggle=true, bool forceActivate=false)
virtual void OnActivate ()
void RefreshTexts ()
virtual string GetSimpleText (Card c)
void ClearSimpleTexts ()
void Deactivate ()
virtual void OnDeactivate ()
virtual void OnCancel ()
virtual void OnBeforeUpdate ()
virtual void OnAfterUpdate ()
virtual void OnUpdateCursor ()
void OnRotate ()
void SetCursorOnMap (CursorInfo cursor)
void UpdateInput ()
void InputMovement ()
virtual void InputWheel (int wheel)
virtual void OnUpdateInput ()
void DoFunc (CoreConfig.GameFuncBuild func)
bool IsFuncPressed (CoreConfig.GameFunc func)
void DoFunc (CoreConfig.GameFunc func)
virtual void OnScroll ()
void TryRightClickCloseWidget ()
bool TryShowWidgetMenu ()
HitResult _HitTest (Point point, Point start)
virtual HitResult HitTest (Point point, Point start)
virtual void OnSelectStart (Point point)
virtual void OnSelectEnd (bool cancel)
virtual MeshPass GetGuidePass (Point point)
virtual void OnRenderTile (Point point, HitResult result, int dir)
void OnRenderTileFloor (Point point, HitResult result)
virtual bool CanProcessTiles ()
virtual void OnBeforeProcessTiles ()
virtual void OnProcessTiles (Point point, int dir)
virtual void OnAfterProcessTiles (Point start, Point end)
virtual void OnFinishProcessTiles ()
virtual void OnRefreshSummary (Point point, HitResult result, HitSummary summary)
void ShowLayer ()
virtual Layer OnShowLayer ()
void HideLayer ()
virtual void OnHideLayer ()
virtual string GetHintText ()
virtual void RotateUnderMouse ()
virtual ref string SetMouseInfo (ref string s)
void TogglePause ()
void Pause (bool sound=false)
void UnPause (bool sound=false)
void ChangeGameSpeed (int a, bool sound=false)
Static Public Member Functions
static void OnGameInstantiated ()
Static Public Member Functions inherited from EClass
static int rndSeed (int a, int seed)
static int rnd (long a)
static int rnd (int a)
static int curve (int _a, int start, int step, int rate=75)
static int sqrt (int a)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Public Attributes
Layer layer
int brushRadius = 4
Static Public Attributes
static ActionMode DefaultMode
static AM_Title Title = new AM_Title()
static AM_Sim Sim
static AM_ViewZone View
static AM_Adv Adv
static AM_Region Region
static AM_ADV_Target AdvTarget
static AM_EloMap EloMap
static AM_Inspect Inspect
static AM_NoMap NoMap
static AM_MiniGame MiniGame
static AM_NewZone NewZone
static AM_Bird Bird
static AM_Mine Mine
static AM_Dig Dig
static AM_Harvest Harvest
static AM_Cut Cut
static AM_StateEditor StateEditor
static AM_Picker Picker
static AM_Copy Copy
static AM_Blueprint Blueprint
static AM_Build Build
static AM_CreateArea CreateArea
static AM_EditArea EditArea
static AM_ExpandArea ExpandArea
static AM_Deconstruct Deconstruct
static AM_Select Select
static AM_RemoveDesignation RemoveDesignation
static AM_ViewMap ViewMap
static AM_Terrain Terrain
static AM_Populate Populate
static AM_EditMarker EditMarker
static AM_Visibility Visibility
static AM_Cinema Cinema
static AM_Paint Paint
static AM_FlagCell FlagCell
static ActionMode LastBuildMode
static SourceMaterial.Row lastEditorMat
static bool ignoreSound
static float[] GameSpeeds = new float[4] { 0f, 1f, 2f, 5f }
static List< TCSimpleText > simpleTexts = new List<TCSimpleText>()
static float hotElementTimer
Static Public Attributes inherited from EClass
static Core core
Static Protected Attributes
static Vector3 mpos
Properties
static AM_Adv AdvOrRegion [get]
static bool IsAdv [get]
virtual float gameSpeed [get]
bool IsActive [get]
virtual BaseTileSelector.HitType hitType [get]
virtual BaseTileSelector.SelectType selectType [get]
virtual BaseTileSelector.BoxType boxType [get]
virtual bool ContinuousClick [get]
virtual int hitW [get]
virtual int hitH [get]
HitSummary Summary [get]
bool Multisize [get]
virtual string id [get]
virtual CursorInfo DefaultCursor [get]
virtual string idHelpTopic [get]
virtual string idSound [get]
virtual bool enableMouseInfo [get]
virtual bool hideBalloon [get]
virtual string textHintTitle [get]
virtual bool AllowAutoClick [get]
virtual bool ShowActionHint [get]
virtual bool ShowMouseoverTarget [get]
virtual AreaHighlightMode AreaHihlight [get]
virtual bool CanSelectTile [get]
virtual bool CanTargetOutsideBounds [get]
virtual bool ShouldPauseGame [get]
virtual bool FixFocus [get]
virtual bool HideSubWidgets [get]
virtual bool IsBuildMode [get]
virtual bool ShowBuildWidgets [get]
virtual BuildMenu.Mode buildMenuMode [get]
virtual bool ShouldHideBuildMenu [get]
virtual bool CanTargetFog [get]
virtual int CostMoney [get]
virtual bool AllowBuildModeShortcuts [get]
virtual bool AllowMiddleClickFunc [get]
virtual bool AllowHotbar [get]
virtual bool AllowGeneralInput [get]
virtual bool ShowMaskedThings [get]
virtual int SelectorHeight [get]
virtual bool AllowWheelZoom [get]
virtual float TargetZoom [get]
virtual BaseTileMap.CardIconMode cardIconMode [get]
virtual BaseGameScreen TargetGameScreen [get]
virtual bool IsNoMap [get]
virtual bool UseSubMenu [get]
virtual bool UseSubMenuSlider [get]
virtual bool SubMenuAsGroup [get]
virtual int SubMenuModeIndex [get]
virtual bool ShowExtraHint [get]
BaseTileSelector tileSelector [get]
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Static Private Attributes
static float smoothX = 0f
static float smoothY = 0f
static float textTimer = 0f
static float focusTimer
Detailed Description
Definition at line 5 of file ActionMode.cs.
Member Function Documentation
_HitTest()
HitResult ActionMode._HitTest (Point point, Point start) inline
Definition at line 1266 of file ActionMode.cs.
    {
        if (!EClass.debug.ignoreBuildRule && !CanTargetOutsideBounds && (!point.IsValid || !point.IsInBoundsPlus))
        {
            return HitResult.NoTarget;
        }
        if (!point.IsValid)
        {
            return HitResult.NoTarget;
        }
        if (!CanTargetFog && !point.cell.isSeen)
        {
            return HitResult.Default;
        }
        return HitTest(point, start);
    }
References CanTargetFog, CanTargetOutsideBounds, Point.cell, EClass.debug, HitTest(), CoreDebug.ignoreBuildRule, Point.IsInBoundsPlus, Cell.isSeen, and Point.IsValid.
Referenced by BaseTileSelector._ProcessTile(), and BaseTileSelector.OnUpdate().
Activate()
void ActionMode.Activate (bool toggle = true, bool forceActivate = false) inline
Definition at line 339 of file ActionMode.cs.
    {
        if (TargetGameScreen != null)
        {
            TargetGameScreen.Activate();
        }
        if (EClass.scene.actionMode == this && !forceActivate)
        {
            if (toggle && EClass.scene.actionMode != DefaultMode)
            {
                DefaultMode.Activate();
            }
            return;
        }
        if (ignoreSound)
        {
            ignoreSound = false;
        }
        else
        {
            EClass.Sound.Play(idSound);
        }
        EInput.Consume(0);
        ActionMode actionMode = EClass.scene.actionMode;
        EClass.scene.actionMode = this;
        if (actionMode != null)
        {
            if (actionMode.IsBuildMode && !(actionMode is AM_ViewMap))
            {
                LastBuildMode = actionMode;
            }
            actionMode.ClearSimpleTexts();
            actionMode.OnDeactivate();
            if (EClass.core.IsGameStarted)
            {
                foreach (Card item in ((IEnumerable<Card>)EClass._map.things).Concat((IEnumerable<Card>)EClass._map.charas))
                {
                    item.renderer.DespawnSimpleText();
                }
            }
            _ = NoMap;
            EClass.ui.RemoveLayers();
        }
        if (IsBuildMode)
        {
            BuildMenu.Activate();
            BuildMenu.Instance.terrainMenu.Show(this);
        }
        else
        {
            BuildMenu.Deactivate();
        }
        if (!(this is AM_Adv))
        {
            EClass.ui.hud.transRight.SetActive(enable: false);
        }
        EClass.ui.hud.frame.SetActive(IsBuildMode && EClass.game.altUI);
        if (hideBalloon)
        {
            EClass.ui.ShowBalloon(enable: false);
        }
        else
        {
            EClass.ui.ShowBalloon(!EClass.scene.hideBalloon);
        }
        OnActivate();
        RefreshTexts();
        ShowLayer();
        EClass.ui.widgets.OnChangeActionMode();
        EClass.ui.extraHint.OnChangeActionMode();
        CursorSystem.leftIcon = null;
        EClass.scene.UpdateCursor();
    }
References EClass._map, Scene.actionMode, BaseGameScreen.Activate(), BuildMenu.Activate(), Activate(), Game.altUI, Map.charas, ClearSimpleTexts(), EInput.Consume(), EClass.core, BuildMenu.Deactivate(), DefaultMode, EClass.game, hideBalloon, Scene.hideBalloon, idSound, ignoreSound, BuildMenu.Instance, IsBuildMode, Core.IsGameStarted, item, LastBuildMode, NoMap, OnActivate(), OnDeactivate(), RefreshTexts(), EClass.scene, TerrainMenu.Show(), ShowLayer(), EClass.Sound, TargetGameScreen, BuildMenu.terrainMenu, Map.things, EClass.ui, and Scene.UpdateCursor().
Referenced by AM_Sim._OnUpdateInput(), Activate(), Deactivate(), DoFunc(), LayerNewZone.Embark(), HotItemActionMode.Execute(), Scene.Init(), LayerGacha.OnAfterInit(), LayerHoard.OnAfterInit(), ELayer.OnBeforeAddLayer(), AM_CreateArea.OnCancel(), AM_ExpandArea.OnCancel(), UIHangIcon.OnClick(), LayerNewZone.OnClickExit(), BuildMenu.OnClickPicker(), LayerGacha.OnKill(), LayerHoard.OnKill(), TraitBlueprint.OnRead(), AM_Paint.OnUpdateInput(), TraitViewMap.OnUse(), BuildMenu.RefreshCategoryArea(), AM_Copy.RefreshMenu(), ZoneInspector.RefreshScreen(), AM_Paint.SetPainter(), BuildMenu.Toggle(), Scene.ToggleBirdView(), and UpdateInput().
CanProcessTiles()
virtual bool ActionMode.CanProcessTiles () inline virtual
Reimplemented in AM_Designation< T >.
Definition at line 1351 of file ActionMode.cs.
    {
        if (Multisize && Summary.countValid != hitW * hitH)
        {
            return false;
        }
        return true;
    }
References HitSummary.countValid, hitH, hitW, Multisize, and Summary.
Referenced by BaseTileSelector.OnUpdate(), and BaseTileSelector.TryProcessTiles().
ChangeGameSpeed()
void ActionMode.ChangeGameSpeed (int a, bool sound = false) inline
Definition at line 1512 of file ActionMode.cs.
    {
        if (EClass.game.gameSpeedIndex != a)
        {
            if (sound)
            {
                SE.Play("tick" + a);
            }
            EClass.game.gameSpeedIndex = a;
            if (a != 0)
            {
                EClass.game.lastGameSpeedIndex = a;
            }
            WidgetHotbar.RefreshHighlights();
        }
    }
References EClass.game, Game.gameSpeedIndex, and WidgetHotbar.RefreshHighlights().
Referenced by HotItemSpeed.OnClick(), Pause(), and UnPause().
ClearSimpleTexts()
void ActionMode.ClearSimpleTexts () inline
Definition at line 517 of file ActionMode.cs.
    {
        foreach (TCSimpleText simpleText in simpleTexts)
        {
            if (simpleText != null)
            {
                PoolManager.Despawn(simpleText);
            }
        }
        simpleTexts.Clear();
    }
References PoolManager.Despawn(), and simpleTexts.
Referenced by Activate(), and RefreshTexts().
Deactivate()
void ActionMode.Deactivate () inline
Definition at line 529 of file ActionMode.cs.
    {
        DefaultMode.Activate();
    }
References Activate(), and DefaultMode.
Referenced by AM_ADV_Target._OnUpdateInput(), OnCancel(), AM_Copy.OnCancel(), AM_ViewMap.OnCancel(), Scene.OnKillGame(), AM_Blueprint.OnSave(), AM_Bird.OnUpdateInput(), AM_Paint.OnUpdateInput(), AM_Select.OnUpdateInput(), Scene.ToggleBirdView(), and CoreDebug.UpdateInput().
DoFunc() [1/2]
void ActionMode.DoFunc (CoreConfig::GameFunc func) inline
Definition at line 1131 of file ActionMode.cs.
    {
        Chara targetChara = EClass.scene.mouseTarget.TargetChara;
        switch (func)
        {
        default:
            return;
        case CoreConfig.GameFunc.OpenAllyInv:
            if (!EClass.pc.HasNoGoal || (targetChara != null && !targetChara.IsPCFaction))
            {
                return;
            }
            if (EClass.scene.mouseTarget.pos.Equals(EClass.pc.pos))
            {
                if (!EClass.ui.IsInventoryOpen)
                {
                    SE.PopInventory();
                }
                EClass.ui.ToggleInventory();
            }
            else if (targetChara != null && EClass.pc.Dist(targetChara) <= 1)
            {
                LayerInventory.CreateContainer(targetChara);
            }
            break;
        case CoreConfig.GameFunc.EmptyHand:
            EInput.action = EAction.EmptyHand;
            return;
        case CoreConfig.GameFunc.Fire:
            if (EInput.keyFire.Update(forcePress: true))
            {
                EInput.action = EAction.Fire;
                return;
            }
            break;
        case CoreConfig.GameFunc.SwitchHotbar:
            WidgetCurrentTool.Instance.SwitchPage();
            break;
        case CoreConfig.GameFunc.PropertySearch:
            EClass.ui.widgets.Toggle("Search")?.SoundActivate();
            break;
        case CoreConfig.GameFunc.Talk:
            if (!EClass.pc.HasNoGoal || targetChara == null || targetChara.hostility <= Hostility.Enemy || targetChara.IsPC || EClass.pc.Dist(targetChara) > 2)
            {
                return;
            }
            ACT.Chat.Perform(EClass.pc, targetChara);
            break;
        case CoreConfig.GameFunc.AllAction:
            if (!EClass.ui.isPointerOverUI)
            {
                Adv.ShowAllAction();
            }
            return;
        case CoreConfig.GameFunc.ToggleBuild:
            if (!EClass._zone.CanEnterBuildModeAnywhere)
            {
                SE.Beep();
                Msg.Say("invalidAction");
                return;
            }
            BuildMenu.Toggle();
            break;
        case CoreConfig.GameFunc.ShowJournal:
        {
            LayerJournal layerJournal = EClass.ui.ToggleLayer<LayerJournal>();
            if ((bool)layerJournal)
            {
                layerJournal.windows[0].SetRect(EClass.core.refs.rects.center);
                layerJournal.Delay();
            }
            break;
        }
        case CoreConfig.GameFunc.ToggleLog:
            WidgetMainText.ToggleLog();
            break;
        case CoreConfig.GameFunc.ShowInv:
            EClass.ui.ToggleInventory(delay: true);
            break;
        case CoreConfig.GameFunc.ShowChara:
        {
            LayerChara layerChara = EClass.ui.ToggleLayer<LayerChara>();
            if ((bool)layerChara)
            {
                layerChara.SetChara(EClass.pc);
                layerChara.windows[0].SetRect(EClass.core.refs.rects.center);
                layerChara.Delay();
            }
            break;
        }
        case CoreConfig.GameFunc.ShowAbility:
            EClass.ui.ToggleAbility(delay: true);
            break;
        case CoreConfig.GameFunc.ToggleNoRoof:
            EClass.game.config.noRoof = !EClass.game.config.noRoof;
            break;
        case CoreConfig.GameFunc.ToggleZoom:
            Adv.ToggleZoom();
            break;
        case CoreConfig.GameFunc.EmuShift:
        case CoreConfig.GameFunc.EmuAlt:
            return;
        }
        EInput.Consume();
    }
References EClass._zone, Adv, Zone.CanEnterBuildModeAnywhere, CoreRef.Rects.center, ACT.Chat, Game.config, EInput.Consume(), EClass.core, LayerInventory.CreateContainer(), Layer.Delay(), Card.Dist(), Point.Equals(), EClass.game, Chara.HasNoGoal, Chara.hostility, WidgetCurrentTool.Instance, Chara.IsPC, Chara.IsPCFaction, EInput.keyFire, Scene.mouseTarget, Game.Config.noRoof, EClass.pc, ActChat.Perform(), Card.pos, PointTarget.pos, CoreRef.rects, Core.refs, Msg.Say(), EClass.scene, LayerChara.SetChara(), AM_Adv.ShowAllAction(), WidgetCurrentTool.SwitchPage(), PointTarget.TargetChara, BuildMenu.Toggle(), WidgetMainText.ToggleLog(), AM_Adv.ToggleZoom(), EClass.ui, EInput.KeyboardPress.Update(), and Layer.windows.
DoFunc() [2/2]
void ActionMode.DoFunc (CoreConfig::GameFuncBuild func) inline
Definition at line 1063 of file ActionMode.cs.
    {
        switch (func)
        {
        case CoreConfig.GameFuncBuild.ExitBuildMode:
            DefaultMode.Activate();
            break;
        case CoreConfig.GameFuncBuild.ToggleFreepos:
            EClass.scene.ToggleFreePos();
            break;
        case CoreConfig.GameFuncBuild.ToggleRoof:
            EClass.scene.ToggleShowRoof();
            break;
        case CoreConfig.GameFuncBuild.ToggleSlope:
            EClass.scene.ToggleSlope();
            break;
        case CoreConfig.GameFuncBuild.Rotate:
            OnRotate();
            break;
        case CoreConfig.GameFuncBuild.ToggleWall:
            EClass.scene.ToggleShowWall();
            break;
        case CoreConfig.GameFuncBuild.TogglePicker:
            if (Picker.CanActivate)
            {
                Picker.Activate();
            }
            break;
        case CoreConfig.GameFuncBuild.SnapFreepos:
            EClass.scene.ToggleSnapFreePos();
            break;
        case CoreConfig.GameFuncBuild.ToggleBuildLight:
            EClass.scene.ToggleLight();
            break;
        }
        WidgetHotbar.RefreshHighlights();
    }
References Activate(), AM_Picker.CanActivate, DefaultMode, OnRotate(), Picker, WidgetHotbar.RefreshHighlights(), EClass.scene, Scene.ToggleFreePos(), Scene.ToggleLight(), Scene.ToggleShowRoof(), Scene.ToggleShowWall(), Scene.ToggleSlope(), and Scene.ToggleSnapFreePos().
Referenced by AM_Adv._OnUpdateInput(), and UpdateInput().
GetDefaultTile()
virtual int ActionMode.GetDefaultTile (Point p) inline virtual
Reimplemented in AM_Adv.
Definition at line 321 of file ActionMode.cs.
    {
        return 0;
    }
Referenced by OnRenderTile(), and OnRenderTileFloor().
GetGuidePass()
virtual MeshPass ActionMode.GetGuidePass (Point point) inline virtual
Reimplemented in AM_BaseTerrain, AM_Deconstruct, and AM_RemoveDesignation.
Definition at line 1296 of file ActionMode.cs.
    {
        if ((!point.HasNonWallBlock && !point.HasBlockRecipe && point.IsSeen) || (point.sourceBlock.tileType.Invisible && !IsBuildMode))
        {
            return EClass.screen.guide.passGuideFloor;
        }
        return EClass.screen.guide.passGuideBlock;
    }
References BaseGameScreen.guide, Point.HasBlockRecipe, Point.HasNonWallBlock, IsBuildMode, Point.IsSeen, ScreenGuide.passGuideBlock, ScreenGuide.passGuideFloor, EClass.screen, and Point.sourceBlock.
Referenced by PartialMap.Apply(), OnRenderTile(), and OnRenderTileFloor().
GetHintText()
virtual string ActionMode.GetHintText () inline virtual
Reimplemented in AM_BaseGameMode.
Definition at line 1420 of file ActionMode.cs.
    {
        string text = textHintTitle.IsEmpty(Lang.Get(id)) + "   - ";
        BaseTileSelector baseTileSelector = EClass.screen.tileSelector;
        ActionMode actionMode = EClass.scene.actionMode;
        if (!layer)
        {
            text = ((actionMode == Inspect && Inspect.target != null) ? "hintMoveTarget".lang() : ((selectType == BaseTileSelector.SelectType.Single) ? (text + "hintSelectSingle".lang()) : ((baseTileSelector.start != null) ? (text + "hintSelectEnd".lang()) : (text + "hintSelectStart".lang()))));
        }
        else
        {
            if (actionMode == Build)
            {
                text += "hintBuild".lang();
            }
            if (actionMode == CreateArea)
            {
                text += "hintCreateArea".lang();
            }
        }
        if (actionMode == Build && Build.recipe != null && baseTileSelector.start == null)
        {
            if (Build.recipe.CanRotate)
            {
                text = text + "  " + "hintRotate".lang();
            }
            if (Build.MaxAltitude > 0)
            {
                text = text + "  " + "hintAltitude2".lang();
            }
        }
        return text;
    }
References Scene.actionMode, Build, Recipe.CanRotate, CreateArea, Lang.Get(), Inspect, layer, AM_Build.MaxAltitude, AM_Build.recipe, EClass.scene, EClass.screen, selectType, BaseTileSelector.start, textHintTitle, and BaseGameScreen.tileSelector.
Referenced by ActionHint.UpdateText().
GetSimpleText()
virtual string ActionMode.GetSimpleText (Card c) inline virtual
Reimplemented in AM_EditMarker.
Definition at line 508 of file ActionMode.cs.
    {
        if (c.trait is TraitRoomPlate && c.Cell.room != null)
        {
            return "#" + c.Cell.room.data.group;
        }
        return null;
    }
References Card.Cell, BaseArea.data, AreaData.group, Cell.room, and Card.trait.
Referenced by RefreshTexts().
HideLayer()
void ActionMode.HideLayer () inline
Definition at line 1408 of file ActionMode.cs.
    {
        EClass.ui.RemoveLayer(layer);
        CursorSystem.SetCursor(CursorSystem.Select);
        EClass.ui.hud.hint.UpdateText();
        OnHideLayer();
    }
References layer, OnHideLayer(), CursorSystem.Select, CursorSystem.SetCursor(), and EClass.ui.
HighlightWall()
virtual bool ActionMode.HighlightWall (Point p) inline virtual
Reimplemented in AM_Adv.
Definition at line 297 of file ActionMode.cs.
    {
        return false;
    }
Referenced by OnRenderTile().
HitTest()
virtual HitResult ActionMode.HitTest (Point point, Point start) inline virtual
Reimplemented in AM_BaseGameMode, AM_BaseTerrain, AM_Copy, AM_CreateArea, AM_Deconstruct, AM_Designation< T >, AM_EditArea, AM_EditMarker, AM_ExpandArea, AM_FlagCell, AM_Picker, AM_RemoveDesignation, AM_StateEditor, and AM_Visibility.
Definition at line 1283 of file ActionMode.cs.
    {
        return HitResult.Default;
    }
Referenced by _HitTest().
InputMovement()
void ActionMode.InputMovement () inline
Definition at line 964 of file ActionMode.cs.
    {
        float num = 0f;
        float num2 = 0f;
        Vector2 axis = EInput.axis;
        bool flag = !EClass.core.IsGameStarted;
        if ((!FixFocus && !EInput.rightMouse.pressing) || EClass.scene.actionMode.IsBuildMode)
        {
            if (Input.GetKey(KeyCode.LeftShift))
            {
                axis *= 3f;
            }
            if (EClass.core.config.camera.edgeScroll)
            {
                Vector2 zero = Vector2.zero;
                if (mpos.x < 16f)
                {
                    zero.x -= 1f;
                }
                if (mpos.x > (float)(Screen.width - 16))
                {
                    zero.x += 1f;
                }
                if (mpos.y < 8f)
                {
                    zero.y -= 1f;
                }
                if (mpos.y > (float)(Screen.height - 8))
                {
                    zero.y += 1f;
                }
                if (zero != Vector2.zero)
                {
                    axis += zero * (EClass.core.config.camera.sensEdge * 2f);
                }
            }
            EInput.hasAxisMoved = axis != Vector2.zero;
            _ = EInput.buttonScroll;
            if (Adv.IsActive)
            {
                _ = Adv.zoomOut;
            }
            if (EInput.buttonScroll != null && EInput.buttonScroll.pressing && (flag || !EClass.ui.BlockActions))
            {
                num = EInput.dragAmount.x * (0.1f + EClass.core.config.camera.sensDrag);
                num2 = EInput.dragAmount.y * (0.1f + EClass.core.config.camera.sensDrag);
                if (!EClass.core.config.camera.invertX)
                {
                    num *= -1f;
                }
                if (!EClass.core.config.camera.invertY)
                {
                    num2 *= -1f;
                }
                if (EInput.hasMouseMoved)
                {
                    EInput.hasAxisMoved = true;
                }
            }
            if (EInput.hasAxisMoved)
            {
                EClass.screen.zoomPos = Vector3.zero;
            }
            if (EInput.wheel != 0 && !InputModuleEX.GetComponentOf<UIScrollView>())
            {
                InputWheel(EInput.wheel);
            }
        }
        float momentum = EClass.core.config.camera.momentum;
        if (momentum > 0f && EInput.axis == Vector2.zero)
        {
            smoothX = Mathf.Lerp(smoothX, num, Time.smoothDeltaTime * momentum);
            smoothY = Mathf.Lerp(smoothY, num2, Time.smoothDeltaTime * momentum);
        }
        else
        {
            smoothX = num;
            smoothY = num2;
        }
        EClass.screen.ScrollMouse(smoothX * 0.1f, smoothY * 0.1f);
        if (EInput.hasAxisMoved)
        {
            OnScroll();
            EClass.screen.ScrollAxis(axis);
        }
    }
References Scene.actionMode, Adv, EInput.axis, EInput.buttonScroll, CoreConfig.camera, Core.config, EClass.core, CoreConfig.CameraConfig.edgeScroll, FixFocus, EInput.hasAxisMoved, EInput.hasMouseMoved, InputWheel(), CoreConfig.CameraConfig.invertX, CoreConfig.CameraConfig.invertY, IsActive, IsBuildMode, Core.IsGameStarted, CoreConfig.CameraConfig.momentum, mpos, OnScroll(), ButtonState.pressing, EInput.rightMouse, EClass.scene, EClass.screen, BaseGameScreen.ScrollAxis(), BaseGameScreen.ScrollMouse(), CoreConfig.CameraConfig.sensDrag, smoothX, smoothY, EClass.ui, EInput.wheel, and AM_Adv.zoomOut.
Referenced by LayerEmbark.Update(), and UpdateInput().
InputWheel()
virtual void ActionMode.InputWheel (int wheel) inline virtual
Definition at line 1051 of file ActionMode.cs.
    {
        if (AllowWheelZoom)
        {
            EClass.screen.ModTargetZoomIndex(-wheel);
        }
    }
References AllowWheelZoom, BaseGameScreen.ModTargetZoomIndex(), and EClass.screen.
Referenced by InputMovement().
IsFillMode()
virtual bool ActionMode.IsFillMode () inline virtual
Definition at line 316 of file ActionMode.cs.
    {
        return false;
    }
Referenced by BaseTileSelector.OnUpdate(), BaseTileSelector.RefreshMouseInfo(), and BaseTileSelector.TryProcessTiles().
IsFuncPressed()
bool ActionMode.IsFuncPressed (CoreConfig::GameFunc func) inline
Definition at line 1101 of file ActionMode.cs.
    {
        CoreConfig.InputSetting input = EClass.core.config.input;
        if (EInput.middleMouse.clicked)
        {
            return input.middleClick == func;
        }
        if (EInput.middleMouse.pressedLong)
        {
            return input.middlePressLong == func;
        }
        if (EInput.mouse3.clicked)
        {
            return input.mouse3Click == func;
        }
        if (EInput.mouse3.pressedLong)
        {
            return input.mouse3PressLong == func;
        }
        if (EInput.mouse4.clicked)
        {
            return input.mouse4Click == func;
        }
        if (EInput.mouse4.pressedLong)
        {
            return input.mouse4PressLong == func;
        }
        return false;
    }
References ButtonState.clicked, Core.config, EClass.core, CoreConfig.input, EInput.middleMouse, EInput.mouse3, EInput.mouse4, and ButtonState.pressedLong.
Referenced by WidgetSearch.Update().
IsRoofEditMode()
virtual bool ActionMode.IsRoofEditMode (Card c = null) inline virtual
Reimplemented in AM_Deconstruct.
Definition at line 311 of file ActionMode.cs.
    {
        return false;
    }
Referenced by Recipe.Build(), RecipeCard.Build(), TileTypeWallHang.GetDesiredDir(), TaskBuild.GetHitResult(), TaskMoveInstalled.GetHitResult(), BaseTileMap.GetThingPosition(), Point.ListCards(), Recipe.OnRenderMarker(), OnRenderTile(), BaseTileSelector.RefreshMouseInfo(), Card.RenderMarker(), Card.SetFreePos(), and PointTarget.ShouldIgnore().
OnActivate()
virtual void ActionMode.OnActivate () inline virtual
Reimplemented in AM_Adv, AM_ADV_Target, AM_Bird, AM_Cinema, AM_Copy, AM_Designation< T >, AM_EloMap, AM_NewZone, AM_NoMap, AM_Paint, AM_ViewMap, and AM_ViewZone.
Definition at line 413 of file ActionMode.cs.
    {
    }
Referenced by Activate().
OnAfterProcessTiles()
virtual void ActionMode.OnAfterProcessTiles (Point start, Point end) inline virtual
Reimplemented in AM_BaseTerrain, AM_Copy, AM_CreateArea, and AM_Designation< T >.
Definition at line 1368 of file ActionMode.cs.
    {
    }
Referenced by BaseTileSelector.TryProcessTiles().
OnAfterUpdate()
virtual void ActionMode.OnAfterUpdate () inline virtual
Reimplemented in AM_Adv.
Definition at line 550 of file ActionMode.cs.
    {
    }
Referenced by Scene.OnUpdate().
OnBeforeProcessTiles()
virtual void ActionMode.OnBeforeProcessTiles () inline virtual
Reimplemented in AM_Designation< T >.
Definition at line 1360 of file ActionMode.cs.
    {
    }
Referenced by BaseTileSelector.TryProcessTiles().
OnBeforeUpdate()
virtual void ActionMode.OnBeforeUpdate () inline virtual
Reimplemented in AM_Adv.
Definition at line 546 of file ActionMode.cs.
    {
    }
Referenced by Scene.OnUpdate().
OnCancel()
virtual void ActionMode.OnCancel () inline virtual
Reimplemented in AM_BaseGameMode, AM_Copy, AM_CreateArea, AM_ExpandArea, and AM_ViewMap.
Definition at line 538 of file ActionMode.cs.
    {
        if (!IsBuildMode || EClass.core.config.input.rightClickExitBuildMode || Input.GetKey(KeyCode.Escape))
        {
            Deactivate();
        }
    }
References Core.config, EClass.core, Deactivate(), CoreConfig.input, IsBuildMode, and CoreConfig.InputSetting.rightClickExitBuildMode.
Referenced by BaseTileSelector.OnUpdate().
OnClickSubMenu()
virtual void ActionMode.OnClickSubMenu (int a) inline virtual
Reimplemented in AM_Copy, AM_Deconstruct, AM_FlagCell, AM_Populate, and AM_Terrain.
Definition at line 302 of file ActionMode.cs.
    {
    }
Referenced by TerrainMenu.Show().
OnDeactivate()
virtual void ActionMode.OnDeactivate () inline virtual
Reimplemented in AM_Adv, AM_Bird, AM_Cinema, AM_Copy, AM_CreateArea, AM_EditMarker, AM_ExpandArea, AM_NoMap, AM_Paint, and AM_ViewMap.
Definition at line 534 of file ActionMode.cs.
    {
    }
Referenced by Activate().
OnFinishProcessTiles()
virtual void ActionMode.OnFinishProcessTiles () inline virtual
Definition at line 1372 of file ActionMode.cs.
    {
    }
Referenced by BaseTileSelector.TryProcessTiles().
OnGameInstantiated()
static void ActionMode.OnGameInstantiated () inline static
Definition at line 247 of file ActionMode.cs.
    {
        LastBuildMode = null;
        Sim = new AM_Sim();
        View = new AM_ViewZone();
        Adv = new AM_Adv();
        AdvTarget = new AM_ADV_Target();
        Region = new AM_Region();
        NoMap = new AM_NoMap();
        MiniGame = new AM_MiniGame();
        EloMap = new AM_EloMap();
        NewZone = new AM_NewZone();
        Select = new AM_Select();
        Inspect = new AM_Inspect();
        Bird = new AM_Bird();
        DefaultMode = Adv;
        Mine = new AM_Mine();
        Dig = new AM_Dig();
        Harvest = new AM_Harvest();
        Cut = new AM_Cut();
        Copy = new AM_Copy();
        Blueprint = new AM_Blueprint();
        Build = new AM_Build();
        Picker = new AM_Picker();
        StateEditor = new AM_StateEditor();
        CreateArea = new AM_CreateArea();
        EditArea = new AM_EditArea();
        ExpandArea = new AM_ExpandArea();
        RemoveDesignation = new AM_RemoveDesignation();
        Deconstruct = new AM_Deconstruct();
        ViewMap = new AM_ViewMap();
        Terrain = new AM_Terrain();
        Populate = new AM_Populate();
        EditMarker = new AM_EditMarker();
        Visibility = new AM_Visibility();
        Cinema = new AM_Cinema();
        FlagCell = new AM_FlagCell();
        Paint = new AM_Paint();
    }
References Adv, AdvTarget, Bird, Blueprint, Build, Cinema, Copy, CreateArea, Cut, Deconstruct, DefaultMode, Dig, EditArea, EditMarker, ExpandArea, FlagCell, Harvest, Inspect, LastBuildMode, Mine, NewZone, NoMap, Paint, Picker, Populate, RemoveDesignation, Select, Sim, StateEditor, Terrain, View, ViewMap, and Visibility.
Referenced by Game.OnGameInstantiated().
OnHideLayer()
virtual void ActionMode.OnHideLayer () inline virtual
Definition at line 1416 of file ActionMode.cs.
    {
    }
Referenced by HideLayer().
OnProcessTiles()
virtual void ActionMode.OnProcessTiles (Point point, int dir) inline virtual
Reimplemented in AM_CreateArea, AM_Deconstruct, AM_Designation< T >, AM_EditArea, AM_EditMarker, AM_ExpandArea, AM_FlagCell, AM_Picker, AM_Populate, AM_RemoveDesignation, AM_StateEditor, AM_Terrain, and AM_Visibility.
Definition at line 1364 of file ActionMode.cs.
    {
    }
Referenced by BaseTileSelector._ProcessTile(), and BaseTileSelector.TryProcessTiles().
OnRefreshSummary()
virtual void ActionMode.OnRefreshSummary (Point point, HitResult result, HitSummary summary) inline virtual
Reimplemented in AM_Designation< T >, and AM_Select.
Definition at line 1376 of file ActionMode.cs.
    {
        if (result == HitResult.Valid || result == HitResult.Warning)
        {
            summary.money += CostMoney;
            summary.countValid++;
        }
    }
References CostMoney, and HitSummary.countValid.
Referenced by BaseTileSelector._ProcessTile().
OnRenderTile()
virtual void ActionMode.OnRenderTile (Point point, HitResult result, int dir) inline virtual
Reimplemented in AM_Adv, AM_BaseTerrain, AM_Copy, AM_Picker, AM_Region, and AM_ViewZone.
Definition at line 1305 of file ActionMode.cs.
    {
        if (result != HitResult.NoTarget && point.IsValid && (point.IsSeen || CanTargetFog))
        {
            MeshPass guidePass = GetGuidePass(point);
            int num = (int)result;
            if (tileSelector.start != null && result == HitResult.Default)
            {
                num = 2;
            }
            Vector3 vector = point.Position();
            if (num == 0)
            {
                num = GetDefaultTile(point);
            }
            guidePass.Add(vector.x, vector.y, vector.z - 0.01f, num, 0.3f);
            if (!IsRoofEditMode() && point.HasWallOrFence && !point.cell.hasDoor && HighlightWall(point))
            {
                EClass.screen.guide.DrawWall(point, EClass.Colors.blockColors.Passive, useMarkerPass: true);
            }
            if (IsBuildMode && EClass.screen.tileSelector.start == null && point.Installed != null && Inspect.IsActive)
            {
                point.Installed.trait.OnRenderTile(point, result, dir);
            }
        }
    }
References MeshPass.Add(), ColorProfile.blockColors, CanTargetFog, Point.cell, EClass.Colors, ScreenGuide.DrawWall(), GetDefaultTile(), GetGuidePass(), BaseGameScreen.guide, Cell.hasDoor, Point.HasWallOrFence, HighlightWall(), Inspect, Point.Installed, IsBuildMode, IsRoofEditMode(), Point.IsSeen, Point.IsValid, Trait.OnRenderTile(), ColorProfile.BlockColors.Passive, Point.Position(), EClass.screen, BaseTileSelector.start, tileSelector, BaseGameScreen.tileSelector, and Card.trait.
Referenced by BaseTileSelector._ProcessTile().
OnRenderTileFloor()
void ActionMode.OnRenderTileFloor (Point point, HitResult result) inline
Definition at line 1332 of file ActionMode.cs.
    {
        if (result != HitResult.NoTarget && point.IsValid && (point.IsSeen || CanTargetFog))
        {
            MeshPass guidePass = GetGuidePass(point);
            int num = (int)result;
            if (tileSelector.start != null && result == HitResult.Default)
            {
                num = 2;
            }
            Vector3 vector = point.Position(point.cell.height);
            if (num == 0)
            {
                num = GetDefaultTile(point);
            }
            guidePass.Add(vector.x, vector.y, vector.z - 0.01f, num, 0.3f);
        }
    }
References MeshPass.Add(), CanTargetFog, Point.cell, GetDefaultTile(), GetGuidePass(), Cell.height, Point.IsSeen, Point.IsValid, Point.Position(), BaseTileSelector.start, and tileSelector.
OnRotate()
void ActionMode.OnRotate () inline
Definition at line 560 of file ActionMode.cs.
    {
        RotateUnderMouse();
    }
References RotateUnderMouse().
Referenced by DoFunc().
OnScroll()
virtual void ActionMode.OnScroll () inline virtual
Reimplemented in AM_ViewZone.
Definition at line 1237 of file ActionMode.cs.
    {
    }
Referenced by InputMovement().
OnSelectEnd()
virtual void ActionMode.OnSelectEnd (bool cancel) inline virtual
Reimplemented in AM_Copy.
Definition at line 1292 of file ActionMode.cs.
    {
    }
Referenced by BaseTileSelector.OnUpdate(), and BaseTileSelector.TryProcessTiles().
OnSelectStart()
virtual void ActionMode.OnSelectStart (Point point) inline virtual
Reimplemented in AM_Copy, AM_CreateArea, and AM_ExpandArea.
Definition at line 1288 of file ActionMode.cs.
    {
    }
Referenced by BaseTileSelector.OnUpdate().
OnSetSubMenuButton()
virtual string ActionMode.OnSetSubMenuButton (int a, UIButton b) inline virtual
Reimplemented in AM_Copy, AM_Deconstruct, AM_FlagCell, AM_Populate, and AM_Terrain.
Definition at line 306 of file ActionMode.cs.
    {
        return null;
    }
Referenced by TerrainMenu.Show().
OnShowExtraHint()
virtual void ActionMode.OnShowExtraHint (UINote n) inline virtual
Definition at line 326 of file ActionMode.cs.
    {
        string[] list = Lang.GetList("exhint_" + GetType().Name);
        if (list != null)
        {
            string[] array = list;
            foreach (string text in array)
            {
                n.AddText("NoteText_extrahint", text, Color.white);
            }
        }
    }
References UINote.AddText(), Color, and Lang.GetList().
Referenced by ExtraHint.Refresh().
OnShowLayer()
virtual Layer ActionMode.OnShowLayer () inline virtual
Definition at line 1403 of file ActionMode.cs.
    {
        return null;
    }
Referenced by ShowLayer().
OnUpdateCursor()
virtual void ActionMode.OnUpdateCursor () inline virtual
Reimplemented in AM_Adv, AM_CreateArea, AM_Deconstruct, AM_EditArea, AM_ExpandArea, AM_Picker, AM_RemoveDesignation, and AM_StateEditor.
Definition at line 554 of file ActionMode.cs.
    {
        CursorSystem.leftIcon = null;
        CursorSystem.SetCursor();
    }
References CursorSystem.SetCursor().
Referenced by UI.OnChangeLayer(), and Scene.UpdateCursor().
OnUpdateInput()
virtual void ActionMode.OnUpdateInput () inline virtual
Reimplemented in AM_BaseGameMode, AM_BaseTerrain, AM_Bird, AM_Cinema, AM_Copy, AM_Paint, and AM_Select.
Definition at line 1059 of file ActionMode.cs.
    {
    }
Referenced by UpdateInput().
Pause()
void ActionMode.Pause (bool sound = false) inline
Definition at line 1502 of file ActionMode.cs.
    {
        ChangeGameSpeed(1, sound);
    }
References ChangeGameSpeed().
Referenced by Scene.FocusAndPause().
RefreshTexts()
void ActionMode.RefreshTexts () inline
Definition at line 417 of file ActionMode.cs.
    {
        if (!EClass.core.IsGameStarted)
        {
            return;
        }
        ClearSimpleTexts();
        if (EClass._zone.IsRegion)
        {
            foreach (Spatial child in EClass._zone.children)
            {
                if (!child.destryoed)
                {
                    Sprite sprite = null;
                    if (child.isRandomSite && !child.isConquered && child.visitCount > 0)
                    {
                        sprite = EClass.core.refs.tcs.spriteVisited;
                    }
                    else if (child.isConquered)
                    {
                        sprite = EClass.core.refs.tcs.spriteConquer;
                    }
                    else if (!child.IsPlayerFaction && child is Zone_Field && child.isDeathLocation)
                    {
                        sprite = EClass.core.refs.tcs.spriteDeath;
                    }
                    if ((bool)sprite)
                    {
                        TCSimpleText tCSimpleText = TCSimpleText.SpawnIcon(sprite);
                        simpleTexts.Add(tCSimpleText);
                        Cell cell = child.RegionPos.cell;
                        tCSimpleText.transform.position = cell.GetPoint().PositionTopdown() + EClass.setting.render.tc.simpleTextPos;
                    }
                }
            }
        }
        if (!IsBuildMode || !ShowMaskedThings)
        {
            return;
        }
        foreach (Card item in ((IEnumerable<Card>)EClass._map.things).Concat((IEnumerable<Card>)EClass._map.charas))
        {
            string simpleText = GetSimpleText(item);
            if (!simpleText.IsEmpty())
            {
                TCSimpleText tCSimpleText2 = TCSimpleText.Spawn();
                Popper.SetText(tCSimpleText2.tm, simpleText);
                simpleTexts.Add(tCSimpleText2);
                tCSimpleText2.transform.position = item.pos.Position() + EClass.setting.render.tc.simpleTextPos;
            }
        }
        if (!Application.isEditor)
        {
            return;
        }
        foreach (KeyValuePair<int, int> backerObj in EClass._map.backerObjs)
        {
            SourceBacker.Row row = EClass.sources.backers.map[backerObj.Value];
            string text = "Backer:" + row.id + "/" + row.Name;
            if (row.isStatic != 0)
            {
                text = "" + text;
            }
            TCSimpleText tCSimpleText3 = TCSimpleText.Spawn();
            Popper.SetText(tCSimpleText3.tm, text);
            simpleTexts.Add(tCSimpleText3);
            Cell cell2 = EClass._map.GetCell(backerObj.Key);
            tCSimpleText3.transform.position = cell2.GetPoint().Position() + EClass.setting.render.tc.simpleTextPos;
        }
        foreach (Card card in EClass._map.Cards)
        {
            if (!card.isBackerContent)
            {
                continue;
            }
            SourceBacker.Row row2 = EClass.sources.backers.map.TryGetValue(card.c_idBacker);
            if (row2 != null)
            {
                string text2 = "Backer:" + row2.id + "/" + row2.Name;
                if (row2.isStatic != 0)
                {
                    text2 = "" + text2;
                }
                TCSimpleText tCSimpleText4 = TCSimpleText.Spawn();
                Popper.SetText(tCSimpleText4.tm, text2);
                simpleTexts.Add(tCSimpleText4);
                tCSimpleText4.transform.position = card.renderer.position + EClass.setting.render.tc.simpleTextPos;
            }
        }
    }
References EClass._map, EClass._zone, Map.backerObjs, SourceManager.backers, card, Map.Cards, Point.cell, Map.charas, Spatial.children, ClearSimpleTexts(), EClass.core, Spatial.destryoed, Map.GetCell(), Cell.GetPoint(), GetSimpleText(), IsBuildMode, Spatial.isConquered, Spatial.isDeathLocation, Core.IsGameStarted, Spatial.IsPlayerFaction, Spatial.isRandomSite, Spatial.IsRegion, SourceBacker.Row.isStatic, item, SourceBacker.Row.Name, Point.Position(), Point.PositionTopdown(), Core.refs, Spatial.RegionPos, GameSetting.render, Popper.SetText(), EClass.setting, ShowMaskedThings, GameSetting.RenderSetting.TCSetting.simpleTextPos, simpleTexts, EClass.sources, TCSimpleText.Spawn(), TCSimpleText.SpawnIcon(), CoreRef.TCs.spriteConquer, CoreRef.TCs.spriteDeath, CoreRef.TCs.spriteVisited, GameSetting.RenderSetting.tc, CoreRef.tcs, Map.things, TCSimpleText.tm, and Spatial.visitCount.
Referenced by Activate(), and UpdateInput().
RotateUnderMouse()
virtual void ActionMode.RotateUnderMouse () inline virtual
Reimplemented in AM_Copy.
Definition at line 1454 of file ActionMode.cs.
    {
        SE.Rotate();
        Point hitPoint = Scene.HitPoint;
        if (!hitPoint.IsValid)
        {
            return;
        }
        hitPoint.cell.RotateAll();
        if (EClass.debug.enable)
        {
            hitPoint.growth?.Grow(100);
            if (hitPoint.Installed?.trait is TraitSeed)
            {
                (hitPoint.Installed.trait as TraitSeed).TrySprout(force: true);
            }
        }
    }
References Point.cell, EClass.debug, CoreDebug.enable, GrowSystem.Grow(), Point.growth, Scene.HitPoint, Point.Installed, Point.IsValid, Cell.RotateAll(), and Card.trait.
Referenced by OnRotate().
SEExecuteSummary()
virtual void ActionMode.SEExecuteSummary () inline virtual
Reimplemented in AM_BaseTerrain.
Definition at line 292 of file ActionMode.cs.
    {
        SE.Play("plan");
    }
Referenced by BaseTileSelector.ExecuteSummary().
SetCursorOnMap()
void ActionMode.SetCursorOnMap (CursorInfo cursor) inline
Definition at line 565 of file ActionMode.cs.
    {
        CursorSystem.SetCursor(EClass.ui.isPointerOverUI ? null : cursor);
    }
References CursorSystem.SetCursor(), and EClass.ui.
Referenced by AM_CreateArea.OnUpdateCursor(), AM_Deconstruct.OnUpdateCursor(), AM_EditArea.OnUpdateCursor(), AM_ExpandArea.OnUpdateCursor(), AM_Picker.OnUpdateCursor(), AM_RemoveDesignation.OnUpdateCursor(), and AM_StateEditor.OnUpdateCursor().
SetMouseInfo()
virtual ref string ActionMode.SetMouseInfo (ref string s) inline virtual
Reimplemented in AM_Select.
Definition at line 1473 of file ActionMode.cs.
    {
        return ref s;
    }
Referenced by BaseTileSelector.RefreshMouseInfo().
ShowLayer()
void ActionMode.ShowLayer () inline
Definition at line 1385 of file ActionMode.cs.
    {
        layer = OnShowLayer();
        if (layer != null)
        {
            CursorSystem.SetCursor();
        }
        else
        {
            CursorSystem.SetCursor(DefaultCursor);
        }
        if ((bool)EClass.core.screen.tileSelector)
        {
            EClass.core.screen.tileSelector.OnChangeActionMode();
        }
        EClass.ui.hud.hint.Refresh();
    }
References EClass.core, DefaultCursor, layer, BaseTileSelector.OnChangeActionMode(), OnShowLayer(), Core.screen, CursorSystem.SetCursor(), BaseGameScreen.tileSelector, and EClass.ui.
Referenced by Activate().
TogglePause()
void ActionMode.TogglePause () inline
Definition at line 1478 of file ActionMode.cs.
    {
        if (IsAdv)
        {
            EClass.core.config.game.autopause = !EClass.core.config.game.autopause;
            if (EClass.core.config.game.autopause)
            {
                SE.Play("tick0");
            }
            else
            {
                SE.Play("tick1");
            }
        }
        else if (EClass.game.gameSpeedIndex != 0)
        {
            Pause(sound: true);
        }
        else
        {
            UnPause(sound: true);
        }
    }
References CoreConfig.GameConfig.autopause, Core.config, EClass.core, CoreConfig.game, EClass.game, Game.gameSpeedIndex, IsAdv, Pause, and UnPause().
TopHeight()
virtual int ActionMode.TopHeight (Point p) inline virtual
Reimplemented in AM_Terrain.
Definition at line 287 of file ActionMode.cs.
    {
        return -1;
    }
Referenced by BaseTileSelector.RefreshMouseInfo().
TryRightClickCloseWidget()
void ActionMode.TryRightClickCloseWidget () inline
Definition at line 1241 of file ActionMode.cs.
    {
        Widget componentOf = InputModuleEX.GetComponentOf<Widget>();
        if ((bool)componentOf && componentOf.RightClickToClose)
        {
            componentOf.Close();
        }
    }
References Widget.Close(), and Widget.RightClickToClose.
TryShowWidgetMenu()
bool ActionMode.TryShowWidgetMenu () inline
Definition at line 1250 of file ActionMode.cs.
    {
        Widget componentOf = InputModuleEX.GetComponentOf<Widget>();
        if ((bool)componentOf && componentOf.CanShowContextMenu())
        {
            if (componentOf.RightClickToClose)
            {
                componentOf.Close();
                return true;
            }
            componentOf.ShowContextMenu();
            return true;
        }
        return false;
    }
References Widget.CanShowContextMenu(), Widget.Close(), Widget.RightClickToClose, and Widget.ShowContextMenu().
Referenced by UpdateInput().
UnPause()
void ActionMode.UnPause (bool sound = false) inline
Definition at line 1507 of file ActionMode.cs.
    {
        ChangeGameSpeed(EClass.game.lastGameSpeedIndex, sound);
    }
References ChangeGameSpeed(), EClass.game, and Game.lastGameSpeedIndex.
Referenced by TogglePause().
UpdateInput()
void ActionMode.UpdateInput () inline
Definition at line 570 of file ActionMode.cs.
    {
        mpos = Input.mousePosition;
        if (!IsNoMap)
        {
            EClass.scene.mouseTarget.Update(Scene.HitPoint);
            if ((bool)WidgetMouseover.Instance)
            {
                WidgetMouseover.Instance.Refresh();
            }
        }
        if (LayerAbility.hotElement != null)
        {
            hotElementTimer += Core.delta;
            ButtonAbility hotElement = LayerAbility.hotElement;
            if (EInput.leftMouse.down)
            {
                if (EClass.core.config.game.doubleClickToHold && hotElementTimer < 0.35f)
                {
                    EClass.player.SetCurrentHotItem(new HotItemAct(hotElement.source));
                    SE.SelectHotitem();
                }
                else
                {
                    ButtonGrid componentOf = InputModuleEX.GetComponentOf<ButtonGrid>();
                    if ((bool)componentOf && componentOf.invOwner != null && componentOf.invOwner.owner == EClass.pc && (componentOf.card == null || componentOf.card.trait is TraitAbility) && !(componentOf.invOwner is InvOwnerEquip))
                    {
                        if (componentOf.card != null)
{
                            componentOf.card.Destroy();
                        }
                        SE.Equip();
                        CardBlueprint.SetNormalRarity();
                        Thing thing = ThingGen.Create("ability");
                        int num = ((componentOf.invOwner is InvOwnerHotbar) ? 1 : 0);
                        componentOf.invOwner.Container.AddThing(thing, tryStack: false, componentOf.index, num);
                        thing.c_idAbility = hotElement.source.alias;
                        thing.invY = num;
                        thing.invX = componentOf.index;
                        WidgetCurrentTool.dirty = true;
                    }
                    else
                    {
                        SE.BeepSmall();
                    }
                }
                LayerAbility.ClearHotElement();
            }
            if (EInput.rightMouse.down)
            {
                LayerAbility.ClearHotElement();
            }
        }
        else
        {
            hotElementTimer = 0f;
        }
        focusTimer += Core.delta;
        if (EClass.ui.isPointerOverUI && (EInput.leftMouse.down || EInput.rightMouse.down || (EClass.core.config.ui.autoFocusWindow && !Input.GetMouseButton(0))))
        {
            LayerInventory componentOf2 = InputModuleEX.GetComponentOf<LayerInventory>();
            if (componentOf2 != null)
            {
                LayerInventory layerInventory = LayerInventory.GetLayer(InputModuleEX.GetComponentOf<ButtonGrid>()?.card);
                if ((bool)layerInventory)
                {
                    LayerInventory.highlightInv = layerInventory.invs[0].owner;
                }
                if (focusTimer > 0.1f)
                {
                    if (EClass.ui.layerFloat.layers.Contains(componentOf2) && !layerInventory)
                    {
                        componentOf2.transform.SetAsLastSibling();
                    }
                    LayerAbility componentOf3 = InputModuleEX.GetComponentOf<LayerAbility>();
                    if (componentOf3 != null && EClass.ui.layerFloat.layers.Contains(componentOf3))
                    {
                        componentOf3.transform.SetAsLastSibling();
                    }
                    focusTimer = 0f;
                }
            }
        }
        if ((EInput.isShiftDown && Input.GetMouseButton(0)) || (EInput.rightMouse.dragging2 && !Input.GetMouseButtonDown(1) && Input.GetMouseButton(1)))
        {
            bool rightMouse = !Input.GetMouseButtonDown(1) && Input.GetMouseButton(1);
            ButtonGrid componentOf4 = InputModuleEX.GetComponentOf<ButtonGrid>();
            if (componentOf4 != null && componentOf4.invOwner != null && componentOf4.card != null && componentOf4.invOwner.CanShiftClick(componentOf4, rightMouse) && EClass.ui.AllowInventoryInteractions)
            {
                componentOf4.invOwner.OnShiftClick(componentOf4, rightMouse);
            }
        }
        if (EInput.rightMouse.down)
        {
            LayerInventory componentOf5 = InputModuleEX.GetComponentOf<LayerInventory>();
            if (componentOf5 != null && EClass.ui.layerFloat.layers.Contains(componentOf5) && EInput.rightMouse.down && !componentOf5.mainInv && !InputModuleEX.GetComponentOf<UIButton>() && !componentOf5.windows[0].saveData.noRightClickClose)
            {
                componentOf5.Close();
            }
            if (EClass.ui.contextMenu.isActive)
            {
                EClass.ui.contextMenu.currentMenu.Hide();
                EInput.rightMouse.Consume();
                Layer.rightClicked = false;
            }
            if (DropdownGrid.IsActive && !EClass.ui.GetLayer<LayerInfo>())
            {
                DropdownGrid.Instance.Deactivate();
                EInput.rightMouse.Consume();
                Layer.rightClicked = false;
            }
        }
        if (EInput.middleMouse.down && TryShowWidgetMenu())
        {
            EInput.Consume();
        }
        CoreConfig.InputSetting input = EClass.core.config.input;
        bool flag = (EInput.mouse3.clicked && input.mouse3Click == CoreConfig.GameFunc.AllAction) || (EInput.mouse4.clicked && input.mouse4Click == CoreConfig.GameFunc.AllAction) || (EInput.mouse3.pressedLong && input.mouse3PressLong == CoreConfig.GameFunc.AllAction) || (EInput.mouse4.pressedLong && input.mouse4PressLong == CoreConfig.GameFunc.AllAction);
        if (flag || EInput.middleMouse.down || EInput.middleMouse.clicked || EInput.middleMouse.pressedLong)
        {
            UIButton componentOf6 = InputModuleEX.GetComponentOf<UIButton>();
            if ((bool)componentOf6 && componentOf6.CanMiddleClick() && (flag || EInput.middleMouse.clicked || EInput.middleMouse.pressedLong))
            {
                componentOf6.OnMiddleClick(flag);
            }
        }
        if ((bool)EClass.ui.contextMenu.currentMenu)
        {
            UIContextMenu.timeSinceClosed = 0f;
        }
        else
        {
            UIContextMenu.timeSinceClosed += Time.deltaTime;
        }
        if (EClass.ui.currentDrag != null)
        {
            EClass.ui.OnDrag();
            if (EInput.leftMouse.down || EInput.rightMouse.down || EInput.isCancel)
            {
                if (Input.GetMouseButton(0) && EInput.rightMouse.down)
                {
                    EClass.ui.OnDragSpecial();
                }
                else
                {
                    EClass.ui.EndDrag(EInput.rightMouse.down || EInput.isCancel);
                }
            }
        }
        ButtonState middleMouse = EInput.middleMouse;
        if (middleMouse.pressedLongAction != null)
        {
            if (middleMouse.pressedLong)
            {
                middleMouse.pressedLongAction();
                middleMouse.pressedLongAction = null;
            }
            else if (!EInput.middleMouse.pressing)
            {
                middleMouse.pressedLongAction = null;
            }
        }
        EClass.ui.UpdateInput();
        if (EInput.action == EAction.Mute)
        {
            EClass.scene.ToggleMuteBGM();
        }
        if (AllowGeneralInput && !EClass.ui.IsDragging)
        {
            if (Input.GetKeyDown(KeyCode.Tab) && !EClass.debug.debugInput && !EClass.ui.BlockInput && !IsBuildMode && !EInput.waitReleaseAnyKey)
            {
                if (!EClass.ui.IsInventoryOpen)
                {
                    SE.PopInventory();
                }
                EClass.ui.ToggleInventory();
            }
            if (!EClass.ui.BlockInput && !IsBuildMode && !EInput.waitReleaseAnyKey)
            {
                switch (EInput.action)
                {
                case EAction.MenuChara:
                    EClass.ui.ToggleLayer<LayerChara>()?.SetChara(EClass.pc);
                    break;
                case EAction.MenuJournal:
                    EClass.ui.ToggleLayer<LayerJournal>();
                    break;
                case EAction.MenuAbility:
                    if (!EClass.debug.enable)
                    {
                        EClass.ui.ToggleAbility();
                    }
                    break;
                case EAction.MenuInventory:
                    if (!EClass.ui.IsInventoryOpen)
                    {
                        SE.PopInventory();
                    }
                    EClass.ui.ToggleInventory();
                    break;
                }
            }
            if (!FixFocus)
            {
                InputMovement();
            }
            if (!EClass.ui.canvas.enabled && EInput.IsAnyKeyDown())
            {
                EClass.ui.ToggleCanvas();
                EInput.Consume();
                return;
            }
        }
        if (EInput.action == EAction.Examine && !IsBuildMode)
        {
            ButtonGrid componentOf7 = InputModuleEX.GetComponentOf<ButtonGrid>();
            Card card = null;
            if ((bool)componentOf7 && componentOf7.card != null)
            {
                card = componentOf7.card;
            }
            if (card == null)
            {
                UIItem componentOf8 = InputModuleEX.GetComponentOf<UIItem>();
                if ((bool)componentOf8 && componentOf8.refObj is Thing)
                {
                    card = (Thing)componentOf8.refObj;
                }
            }
            if (card == null)
            {
                LayerCraft layerCraft = EClass.ui.GetLayer<LayerCraft>();
                if ((bool)layerCraft)
                {
                    card = layerCraft.product;
                }
            }
            if (card != null)
            {
                if ((bool)EClass.ui.GetLayer<LayerInfo>())
                {
                    EClass.ui.RemoveLayer<LayerInfo>();
                }
                EClass.ui.AddLayer<LayerInfo>().Set(card, _examine: true);
            }
        }
        if (EInput.buttonCtrl.clicked && !LayerDrama.Instance && EClass.scene.actionMode is AM_Adv && (bool)WidgetCurrentTool.Instance)
        {
            WidgetCurrentTool.Instance.SwitchPage();
        }
        if (EClass.ui.BlockActions)
        {
            return;
        }
        if (AllowBuildModeShortcuts && Input.GetKeyDown(KeyCode.Q) && Picker.CanActivate)
        {
            Picker.Activate();
        }
        if (EClass.debug.godBuild && EInput.isCtrlDown && EInput.wheel != 0 && Scene.HitPoint.IsValid && HotItemHeld.taskBuild == null)
        {
            Point hitPoint = Scene.HitPoint;
            bool flag2 = EInput.wheel > 0;
            if (EClass.scene.mouseTarget.card != null)
            {
                Card card2 = EClass.scene.mouseTarget.card;
                if (card2.isThing && card2.IsInstalled)
                {
                    SourceMaterial.Row currentMat = (card2.isDyed ? card2.DyeMat : card2.material);
                    List<SourceMaterial.Row> source = EClass.sources.materials.rows.Where((SourceMaterial.Row m) => m.thing == currentMat.thing).ToList();
                    if (EInput.isShiftDown)
                    {
                        source = EClass.sources.materials.rows;
                    }
                    SourceMaterial.Row row = (flag2 ? source.NextItem(currentMat) : source.PrevItem(currentMat));
                    if (row == null)
                    {
                        row = card2.DyeMat;
                    }
                    if (EInput.isAltDown)
                    {
                        row = lastEditorMat;
                    }
                    if (card2.isDyed)
                    {
                        card2.Dye(row);
                    }
                    else
                    {
                        card2.ChangeMaterial(row);
                    }
                    lastEditorMat = row;
                    Msg.Say(row.GetName() + "(" + row.alias + ")");
                }
            }
            else if (hitPoint.HasObj)
            {
                SourceMaterial.Row matObj = hitPoint.cell.matObj;
                List<SourceMaterial.Row> rows = EClass.sources.materials.rows;
                SourceMaterial.Row row2 = (flag2 ? rows.NextItem(matObj) : rows.PrevItem(matObj));
                if (EInput.isAltDown)
                {
                    row2 = lastEditorMat;
                }
                hitPoint.cell.objMat = (byte)row2.id;
                lastEditorMat = row2;
                Msg.Say(row2.GetName());
            }
            else if (hitPoint.HasBlock)
            {
                SourceMaterial.Row matBlock = hitPoint.cell.matBlock;
                List<SourceMaterial.Row> rows2 = EClass.sources.materials.rows;
                SourceMaterial.Row row3 = (flag2 ? rows2.NextItem(matBlock) : rows2.PrevItem(matBlock));
                if (EInput.isAltDown)
                {
                    row3 = lastEditorMat;
                }
                hitPoint.cell._blockMat = (byte)row3.id;
                lastEditorMat = row3;
                Msg.Say(row3.GetName());
            }
            else
            {
                SourceMaterial.Row matFloor = hitPoint.cell.matFloor;
                List<SourceMaterial.Row> rows3 = EClass.sources.materials.rows;
                SourceMaterial.Row row4 = (flag2 ? rows3.NextItem(matFloor) : rows3.PrevItem(matFloor));
                if (EInput.isAltDown)
                {
                    row4 = lastEditorMat;
                }
                hitPoint.cell._floorMat = (byte)row4.id;
                lastEditorMat = row4;
                Msg.Say(row4.GetName());
            }
            EInput.Consume();
        }
        if (AllowHotbar && !IsBuildMode && EClass.debug.debugHotkeys == CoreDebug.DebugHotkey.None)
        {
            if (EInput.hotkey != -1)
            {
                WidgetCurrentTool.Instance.Select(EInput.hotkey, fromHotkey: true);
                AdvOrRegion.UpdatePlans();
            }
            else if (!EClass.debug.enable && EInput.functionkey != -1)
            {
                WidgetHotbar hotbarExtra = WidgetHotbar.HotbarExtra;
                if ((bool)hotbarExtra)
                {
                    hotbarExtra.TryUse(EInput.functionkey);
                }
            }
        }
        OnUpdateInput();
        if (EClass.debug.enable)
        {
            EClass.core.debug.UpdateInput();
        }
        textTimer += Core.delta;
        if (textTimer > 0.1f)
        {
            textTimer = 0f;
            RefreshTexts();
        }
        if (IsBuildMode && AllowBuildModeShortcuts)
        {
            if (EInput.middleMouse.clicked)
            {
                DoFunc(input.b_middleClick);
            }
            else if (EInput.middleMouse.pressedLong)
            {
                DoFunc(input.b_middlePressLong);
                EInput.middleMouse.Consume();
            }
            if (EInput.mouse3.clicked)
            {
                DoFunc(input.b_mouse3Click);
            }
            else if (EInput.mouse3.pressedLong)
            {
                DoFunc(input.b_mouse3PressLong);
                EInput.mouse3.Consume();
            }
            if (EInput.mouse4.clicked)
            {
                DoFunc(input.b_mouse4Click);
            }
            else if (EInput.mouse4.pressedLong)
            {
                DoFunc(input.b_mouse4PressLong);
                EInput.mouse4.Consume();
            }
        }
    }
References EInput.action, Scene.actionMode, Activate(), Card.AddThing(), AdvOrRegion, AllowBuildModeShortcuts, AllowGeneralInput, AllowHotbar, CoreConfig.UISetting.autoFocusWindow, CoreConfig.InputSetting.b_middleClick, CoreConfig.InputSetting.b_middlePressLong, CoreConfig.InputSetting.b_mouse3Click, CoreConfig.InputSetting.b_mouse3PressLong, CoreConfig.InputSetting.b_mouse4Click, CoreConfig.InputSetting.b_mouse4PressLong, EInput.buttonCtrl, AM_Picker.CanActivate, UIButton.CanMiddleClick(), InvOwner.CanShiftClick(), ButtonGrid.card, card, PointTarget.card, Point.cell, Card.ChangeMaterial(), LayerAbility.ClearHotElement(), ButtonState.clicked, LayerInventory.Close(), Core.config, ButtonState.Consume(), EInput.Consume(), InvOwner.Container, EClass.core, ThingGen.Create(), DropdownGrid.Deactivate(), Core.debug, EClass.debug, CoreDebug.debugHotkeys, Core.delta, Card.Destroy(), DoFunc(), CoreConfig.GameConfig.doubleClickToHold, ButtonState.down, ButtonState.dragging2, Card.Dye(), Card.DyeMat, CoreDebug.enable, FixFocus, focusTimer, EInput.functionkey, CoreConfig.game, LayerInventory.GetLayer(), CoreDebug.godBuild, Point.HasBlock, Point.HasObj, Scene.HitPoint, WidgetHotbar.HotbarExtra, LayerAbility.hotElement, hotElementTimer, EInput.hotkey, SourceMaterial.Row.id, ButtonGrid.index, CoreConfig.input, InputMovement(), DropdownGrid.Instance, LayerDrama.Instance, WidgetCurrentTool.Instance, WidgetMouseover.Instance, ButtonGrid.invOwner, LayerInventory.invs, DropdownGrid.IsActive, EInput.isAltDown, EInput.IsAnyKeyDown(), IsBuildMode, EInput.isCancel, EInput.isCtrlDown, Card.isDyed, Card.IsInstalled, IsNoMap, EInput.isShiftDown, Card.isThing, Point.IsValid, lastEditorMat, EInput.leftMouse, Cell.matBlock, Card.material, SourceManager.materials, Cell.matFloor, Cell.matObj, EInput.middleMouse, EInput.mouse3, EInput.mouse4, CoreConfig.InputSetting.mouse4Click, CoreConfig.InputSetting.mouse4PressLong, Scene.mouseTarget, mpos, UIButton.OnMiddleClick(), InvOwner.OnShiftClick(), OnUpdateInput(), EClass.pc, Picker, EClass.player, ButtonState.pressedLong, ButtonState.pressedLongAction, ButtonState.pressing, LayerCraft.product, UIItem.refObj, WidgetMouseover.Refresh(), RefreshTexts(), EInput.rightMouse, Msg.Say(), EClass.scene, WidgetCurrentTool.Select(), Player.SetCurrentHotItem(), CardBlueprint.SetNormalRarity(), ButtonAbility.source, EClass.sources, WidgetCurrentTool.SwitchPage(), HotItemHeld.taskBuild, textTimer, SourceMaterial.Row.thing, Scene.ToggleMuteBGM(), TryShowWidgetMenu(), WidgetHotbar.TryUse(), CoreConfig.ui, EClass.ui, PointTarget.Update(), CoreDebug.UpdateInput(), AM_Adv.UpdatePlans(), EInput.waitReleaseAnyKey, EInput.wheel, and Layer.windows.
Referenced by Scene.OnUpdate().
Member Data Documentation
Adv
AM_Adv ActionMode.Adv static
Definition at line 15 of file ActionMode.cs.
Referenced by InvOwner.AutoUse(), HotItemHeld.CanRotate(), Thing.DoAct(), UIInventory.DoAct(), DoFunc(), Scene.Init(), InputMovement(), Widget.Config.IsInRightMode(), Chara.Kick(), LayerCraft.OnClickCraft(), OnGameInstantiated(), BaseTileSelector.OnUpdate(), HotItemFocusPos.Perform(), ActPlan.Item.Perform(), LayerCraftFloat.RefreshCraft(), WidgetSearch.RefreshList(), BaseGameScreen.RefreshPosition(), GameScreenElona.RefreshPosition(), ZoneInspector.RefreshScreen(), AIProgress.Run(), GoalCombat.Run(), TaskPoint.Run(), WidgetCurrentTool.Select(), HotItemContext.Show(), AIAct.Start(), Chara.Tick(), AI_Goto.TryGoTo(), Map.TryShatter(), and LayerCraft.WaitUntilIdle().
AdvTarget
AM_ADV_Target ActionMode.AdvTarget static
Definition at line 19 of file ActionMode.cs.
Referenced by OnGameInstantiated().
Bird
AM_Bird ActionMode.Bird static
Definition at line 31 of file ActionMode.cs.
Referenced by BaseGameScreen.Draw(), BaseTileMap.Draw(), TileMapElona.Draw(), Widget.Config.IsInRightMode(), OnGameInstantiated(), and Scene.ToggleBirdView().
Blueprint
AM_Blueprint ActionMode.Blueprint static
Definition at line 47 of file ActionMode.cs.
Referenced by OnGameInstantiated(), and TraitBlueprint.OnRead().
brushRadius
int ActionMode.brushRadius = 4
Definition at line 99 of file ActionMode.cs.
Referenced by TerrainMenu.OnChangeRadius(), AM_Populate.OnProcessTiles(), AM_Terrain.OnProcessTiles(), AM_BaseTerrain.OnRenderTile(), and TerrainMenu.Show().
Build
AM_Build ActionMode.Build static
Definition at line 49 of file ActionMode.cs.
Referenced by AM_Adv._OnUpdateInput(), RecipeCard.Build(), RecipeCard.CreateMold(), GetHintText(), AM_MoveInstalled.IsRoofEditMode(), OnGameInstantiated(), TaskBuild.OnProgressComplete(), HotItemHeld.OnRenderTile(), UIPlaceHelper.Refresh(), BuildMenu.RefreshCategory(), HotItemActionMode.ShouldHighlight(), BuildMenu.Toggle(), and HotItemHeld.TrySetAct().
Cinema
AM_Cinema ActionMode.Cinema static
Definition at line 73 of file ActionMode.cs.
Referenced by BaseTileMap.Draw(), BaseTileMap.DrawTile(), HotItemActionMode.Execute(), OnGameInstantiated(), HotItemActionMode.ShouldHighlight(), and BaseGameScreen.UpdateShaders().
Copy
AM_Copy ActionMode.Copy static
Definition at line 45 of file ActionMode.cs.
Referenced by PartialMap.Apply(), HotItemActionMode.Execute(), OnGameInstantiated(), Map.Save(), and HotItemActionMode.ShouldHighlight().
CreateArea
AM_CreateArea ActionMode.CreateArea static
Definition at line 51 of file ActionMode.cs.
Referenced by GetHintText(), OnGameInstantiated(), BuildMenu.RefreshCategoryArea(), and HotItemActionMode.ShouldHighlight().
Cut
AM_Cut ActionMode.Cut static
Definition at line 39 of file ActionMode.cs.
Referenced by HotItemActionMode.Execute(), OnGameInstantiated(), and HotItemActionMode.ShouldHighlight().
Deconstruct
AM_Deconstruct ActionMode.Deconstruct static
Definition at line 57 of file ActionMode.cs.
Referenced by HotItemActionMode.Execute(), OnGameInstantiated(), and HotItemActionMode.ShouldHighlight().
DefaultMode
ActionMode ActionMode.DefaultMode static
Definition at line 7 of file ActionMode.cs.
Referenced by Activate(), Deactivate(), DoFunc(), HotItemActionMode.Execute(), Widget.Config.IsInRightMode(), ELayer.OnBeforeAddLayer(), UIHangIcon.OnClick(), OnGameInstantiated(), LayerGacha.OnKill(), LayerHoard.OnKill(), and AM_Paint.OnUpdateInput().
Dig
AM_Dig ActionMode.Dig static
Definition at line 35 of file ActionMode.cs.
Referenced by HotItemActionMode.Execute(), OnGameInstantiated(), ActionHint.Refresh(), and HotItemActionMode.ShouldHighlight().
EditArea
AM_EditArea ActionMode.EditArea static
Definition at line 53 of file ActionMode.cs.
Referenced by HotItemActionMode.Execute(), AM_CreateArea.OnCancel(), AM_ExpandArea.OnCancel(), OnGameInstantiated(), BuildMenu.Refresh(), and HotItemActionMode.ShouldHighlight().
EditMarker
AM_EditMarker ActionMode.EditMarker static
Definition at line 69 of file ActionMode.cs.
Referenced by HotItemActionMode.Execute(), OnGameInstantiated(), and HotItemActionMode.ShouldHighlight().
EloMap
AM_EloMap ActionMode.EloMap static
Definition at line 21 of file ActionMode.cs.
Referenced by Widget.Config.IsInRightMode(), and LayerNewZone.OnClickExit().
ExpandArea
AM_ExpandArea ActionMode.ExpandArea static
Definition at line 55 of file ActionMode.cs.
Referenced by OnGameInstantiated(), AM_EditArea.OnProcessTiles(), InspectGroupArea.OnSetActions(), and HotItemActionMode.ShouldHighlight().
FlagCell
AM_FlagCell ActionMode.FlagCell static
Definition at line 77 of file ActionMode.cs.
Referenced by BaseTileMap.Draw(), BaseTileMap.DrawTile(), HotItemActionMode.Execute(), OnGameInstantiated(), and HotItemActionMode.ShouldHighlight().
focusTimer
float ActionMode.focusTimer static private
Definition at line 101 of file ActionMode.cs.
Referenced by UpdateInput().
GameSpeeds
float [] ActionMode.GameSpeeds = new float[4] { 0f, 1f, 2f, 5f } static
Definition at line 93 of file ActionMode.cs.
Harvest
AM_Harvest ActionMode.Harvest static
Definition at line 37 of file ActionMode.cs.
Referenced by OnGameInstantiated().
hotElementTimer
float ActionMode.hotElementTimer static
Definition at line 103 of file ActionMode.cs.
Referenced by UpdateInput().
ignoreSound
bool ActionMode.ignoreSound static
Definition at line 83 of file ActionMode.cs.
Referenced by Activate().
Inspect
AM_Inspect ActionMode.Inspect static
Definition at line 23 of file ActionMode.cs.
Referenced by HotItemActionMode.Execute(), GetHintText(), LayerInteraction.GetPage(), BaseTileMap.GetThingPosition(), AM_Build.OnCancel(), AM_Build.OnFinishProcessTiles(), OnGameInstantiated(), OnRenderTile(), InspectGroupThing.OnSetActions(), HotItemActionMode.ShouldHighlight(), BuildMenu.Toggle(), TraitToolBuild.TrySetHeldAct(), CoreDebug.UpdateInput(), and ActionHint.UpdateText().
LastBuildMode
ActionMode ActionMode.LastBuildMode static
Definition at line 79 of file ActionMode.cs.
Referenced by Activate(), OnGameInstantiated(), and BuildMenu.Toggle().
lastEditorMat
SourceMaterial.Row ActionMode.lastEditorMat static
Definition at line 81 of file ActionMode.cs.
Referenced by UpdateInput().
layer
Layer ActionMode.layer
Definition at line 97 of file ActionMode.cs.
Referenced by GetHintText(), HideLayer(), AM_ViewMap.OnActivate(), AM_ViewMap.OnDeactivate(), and ShowLayer().
Mine
AM_Mine ActionMode.Mine static
Definition at line 33 of file ActionMode.cs.
Referenced by BaseTileMap.Draw(), TileMapElona.Draw(), TaskMine.DrawMarker(), HotItemActionMode.Execute(), TaskMine.GetHitResult(), Map.MineBlock(), OnGameInstantiated(), TaskMine.OnProgressComplete(), ActionHint.Refresh(), and HotItemActionMode.ShouldHighlight().
MiniGame
AM_MiniGame ActionMode.MiniGame static
Definition at line 27 of file ActionMode.cs.
mpos
Vector3 ActionMode.mpos static protected
Definition at line 91 of file ActionMode.cs.
Referenced by InputMovement(), and UpdateInput().
NewZone
AM_NewZone ActionMode.NewZone static
Definition at line 29 of file ActionMode.cs.
Referenced by Widget.Config.IsInRightMode(), and OnGameInstantiated().
NoMap
AM_NoMap ActionMode.NoMap static
Definition at line 25 of file ActionMode.cs.
Referenced by Activate(), BaseWidgetNotice.Add(), Widget.Config.IsInRightMode(), LayerGacha.OnAfterInit(), LayerHoard.OnAfterInit(), and OnGameInstantiated().
Paint
AM_Paint ActionMode.Paint static
Definition at line 75 of file ActionMode.cs.
Referenced by OnGameInstantiated(), and TraitPainter.OnUse().
Picker
AM_Picker ActionMode.Picker static
Definition at line 43 of file ActionMode.cs.
Referenced by DoFunc(), HotItemActionMode.Execute(), BuildMenu.OnClickPicker(), OnGameInstantiated(), InspectGroupBlock.OnSetActions(), InspectGroupThing.OnSetActions(), BaseTileSelector.RefreshMouseInfo(), HotItemActionMode.ShouldHighlight(), BuildMenu.Toggle(), and UpdateInput().
Populate
AM_Populate ActionMode.Populate static
Definition at line 67 of file ActionMode.cs.
Referenced by HotItemActionMode.Execute(), OnGameInstantiated(), and HotItemActionMode.ShouldHighlight().
Region
AM_Region ActionMode.Region static
Definition at line 17 of file ActionMode.cs.
Referenced by InvOwner.AutoUse(), Scene.Init(), Widget.Config.IsInRightMode(), and ZoneInspector.RefreshScreen().
RemoveDesignation
AM_RemoveDesignation ActionMode.RemoveDesignation static
Definition at line 61 of file ActionMode.cs.
Referenced by HotItemActionMode.Execute(), OnGameInstantiated(), and HotItemActionMode.ShouldHighlight().
Select
AM_Select ActionMode.Select static
Definition at line 59 of file ActionMode.cs.
Referenced by AM_Sim._OnUpdateInput(), TileMapElona.Draw(), OnGameInstantiated(), and AM_Picker.Test().
Sim
AM_Sim ActionMode.Sim static
Definition at line 11 of file ActionMode.cs.
Referenced by LayerNewZone.Embark(), Scene.FocusAndPause(), Widget.Config.IsInRightMode(), OnGameInstantiated(), NoGoal.Run(), and Chara.SetAIImmediate().
simpleTexts
List<TCSimpleText> ActionMode.simpleTexts = new List<TCSimpleText>() static
Definition at line 95 of file ActionMode.cs.
Referenced by ClearSimpleTexts(), and RefreshTexts().
smoothX
float ActionMode.smoothX = 0f static private
Definition at line 85 of file ActionMode.cs.
Referenced by InputMovement().
smoothY
float ActionMode.smoothY = 0f static private
Definition at line 87 of file ActionMode.cs.
Referenced by InputMovement().
StateEditor
AM_StateEditor ActionMode.StateEditor static
Definition at line 41 of file ActionMode.cs.
Referenced by HotItemActionMode.Execute(), OnGameInstantiated(), and HotItemActionMode.ShouldHighlight().
Terrain
AM_Terrain ActionMode.Terrain static
Definition at line 65 of file ActionMode.cs.
Referenced by HotItemActionMode.Execute(), OnGameInstantiated(), HotItemActionMode.ShouldHighlight(), and BuildMenu.Toggle().
textTimer
float ActionMode.textTimer = 0f static private
Definition at line 89 of file ActionMode.cs.
Referenced by UpdateInput().
Title
AM_Title ActionMode.Title = new AM_Title() static
Definition at line 9 of file ActionMode.cs.
Referenced by Scene.Init(), TileSelectorElona.OnUpdateInput(), and LayerEmbark.Update().
View
AM_ViewZone ActionMode.View static
Definition at line 13 of file ActionMode.cs.
Referenced by Scene.Init(), Widget.Config.IsInRightMode(), and OnGameInstantiated().
ViewMap
AM_ViewMap ActionMode.ViewMap static
Definition at line 63 of file ActionMode.cs.
Referenced by BaseTileMap.Draw(), Widget.Config.IsInRightMode(), OnGameInstantiated(), and TraitViewMap.OnUse().
Visibility
AM_Visibility ActionMode.Visibility static
Definition at line 71 of file ActionMode.cs.
Referenced by HotItemActionMode.Execute(), OnGameInstantiated(), and HotItemActionMode.ShouldHighlight().
Property Documentation
AdvOrRegion
AM_Adv ActionMode.AdvOrRegion static get
Definition at line 105 of file ActionMode.cs.
    {
        get
        {
            if (!EClass._zone.IsRegion)
            {
                return Adv;
            }
            return Region;
        }
    }
Referenced by UpdateInput().
AllowAutoClick
virtual bool ActionMode.AllowAutoClick get
Definition at line 163 of file ActionMode.cs.
Referenced by BaseTileSelector.OnUpdate().
AllowBuildModeShortcuts
virtual bool ActionMode.AllowBuildModeShortcuts get
Definition at line 213 of file ActionMode.cs.
Referenced by UpdateInput().
AllowGeneralInput
virtual bool ActionMode.AllowGeneralInput get
Definition at line 219 of file ActionMode.cs.
Referenced by UpdateInput().
AllowHotbar
virtual bool ActionMode.AllowHotbar get
Definition at line 217 of file ActionMode.cs.
Referenced by UpdateInput().
AllowMiddleClickFunc
virtual bool ActionMode.AllowMiddleClickFunc get
Definition at line 215 of file ActionMode.cs.
AllowWheelZoom
virtual bool ActionMode.AllowWheelZoom get
Definition at line 225 of file ActionMode.cs.
Referenced by InputWheel().
AreaHihlight
virtual AreaHighlightMode ActionMode.AreaHihlight get
Definition at line 169 of file ActionMode.cs.
Referenced by Area.OnHoverArea(), BaseTileSelector.OnUpdate(), and PointTarget.Update().
boxType
virtual BaseTileSelector.BoxType ActionMode.boxType get
Definition at line 127 of file ActionMode.cs.
buildMenuMode
virtual BuildMenu.Mode ActionMode.buildMenuMode get
Definition at line 185 of file ActionMode.cs.
    {
        get
        {
            if (!IsBuildMode)
            {
                return BuildMenu.Mode.None;
            }
            return BuildMenu.Mode.Hide;
        }
    }
CanSelectTile
virtual bool ActionMode.CanSelectTile get
Definition at line 171 of file ActionMode.cs.
Referenced by BaseTileSelector.OnUpdate().
CanTargetFog
virtual bool ActionMode.CanTargetFog get
Definition at line 209 of file ActionMode.cs.
Referenced by _HitTest(), OnRenderTile(), and OnRenderTileFloor().
CanTargetOutsideBounds
virtual bool ActionMode.CanTargetOutsideBounds get
Definition at line 173 of file ActionMode.cs.
Referenced by _HitTest().
cardIconMode
virtual BaseTileMap.CardIconMode ActionMode.cardIconMode get
Definition at line 229 of file ActionMode.cs.
Referenced by BaseTileMap.Draw(), and TileMapElona.Draw().
ContinuousClick
virtual bool ActionMode.ContinuousClick get
Definition at line 129 of file ActionMode.cs.
Referenced by BaseTileSelector.OnUpdate().
CostMoney
virtual int ActionMode.CostMoney get
Definition at line 211 of file ActionMode.cs.
Referenced by OnRefreshSummary(), AM_Designation< T >.OnRefreshSummary(), and BaseTileSelector.RefreshMouseInfo().
DefaultCursor
virtual CursorInfo ActionMode.DefaultCursor get
Definition at line 151 of file ActionMode.cs.
Referenced by ShowLayer().
enableMouseInfo
virtual bool ActionMode.enableMouseInfo get
Definition at line 157 of file ActionMode.cs.
Referenced by BaseTileSelector.RefreshMouseInfo().
FixFocus
virtual bool ActionMode.FixFocus get
Definition at line 177 of file ActionMode.cs.
Referenced by InputMovement(), and UpdateInput().
gameSpeed
virtual float ActionMode.gameSpeed get
Definition at line 119 of file ActionMode.cs.
Referenced by Chara._Move(), BaseGameScreen.Draw(), Scene.OnUpdate(), LayerMiniGame.OnUpdateInput(), and Core.Update().
hideBalloon
virtual bool ActionMode.hideBalloon get
Definition at line 159 of file ActionMode.cs.
Referenced by Activate().
HideSubWidgets
virtual bool ActionMode.HideSubWidgets get
Definition at line 179 of file ActionMode.cs.
hitH
virtual int ActionMode.hitH get
Definition at line 133 of file ActionMode.cs.
Referenced by CanProcessTiles().
hitType
virtual BaseTileSelector.HitType ActionMode.hitType get
Definition at line 123 of file ActionMode.cs.
Referenced by BaseTileSelector.OnUpdate().
hitW
virtual int ActionMode.hitW get
Definition at line 131 of file ActionMode.cs.
Referenced by CanProcessTiles().
id
virtual string ActionMode.id get
Definition at line 149 of file ActionMode.cs.
idHelpTopic
virtual string ActionMode.idHelpTopic get
Definition at line 153 of file ActionMode.cs.
idSound
virtual string ActionMode.idSound get
Definition at line 155 of file ActionMode.cs.
Referenced by Activate().
IsActive
bool ActionMode.IsActive get
Definition at line 121 of file ActionMode.cs.
Referenced by InvOwner.AutoUse(), BaseTileMap.Draw(), TileMapElona.Draw(), BaseTileMap.DrawTile(), Scene.Init(), InputMovement(), BaseTileSelector.OnUpdate(), TileSelectorElona.OnUpdateInput(), BaseGameScreen.RefreshPosition(), GameScreenElona.RefreshPosition(), Map.Save(), WidgetCurrentTool.Select(), BaseGameScreen.UpdateShaders(), and LayerCraft.WaitUntilIdle().
IsAdv
bool ActionMode.IsAdv static get
Definition at line 117 of file ActionMode.cs.
Referenced by BaseTileMap.Draw(), TileMapElona.Draw(), Widget.Config.IsInRightMode(), WidgetMouseover.Refresh(), TogglePause(), and AI_Goto.TryGoTo().
IsBuildMode
virtual bool ActionMode.IsBuildMode get
Definition at line 181 of file ActionMode.cs.
Referenced by Activate(), RecipeCard.BuildIngredientList(), HotItemHeld.CanChangeHeightByWheel(), RecipeCard.Craft(), BaseTileMap.Draw(), TileMapElona.Draw(), Map.DropBlockComponent(), HotItemActionMode.Execute(), GetGuidePass(), InputMovement(), Map.MineObj(), OnCancel(), OnRenderTile(), RefreshTexts(), PointTarget.ShouldIgnore(), HotItemContext.Show(), PointTarget.Update(), UpdateInput(), and CoreDebug.UpdateInput().
IsNoMap
virtual bool ActionMode.IsNoMap get
Definition at line 233 of file ActionMode.cs.
Referenced by UpdateInput().
Multisize
bool ActionMode.Multisize get
Definition at line 137 of file ActionMode.cs.
    {
        get
        {
            if (hitW == 1)
            {
                return hitW != 1;
            }
            return true;
        }
    }
Referenced by CanProcessTiles().
SelectorHeight
virtual int ActionMode.SelectorHeight get
Definition at line 223 of file ActionMode.cs.
selectType
virtual BaseTileSelector.SelectType ActionMode.selectType get
Definition at line 125 of file ActionMode.cs.
Referenced by GetHintText(), and BaseTileSelector.OnUpdate().
ShouldHideBuildMenu
virtual bool ActionMode.ShouldHideBuildMenu get
Definition at line 197 of file ActionMode.cs.
    {
        get
        {
            if (IsBuildMode)
            {
                return tileSelector.start != null;
            }
            return false;
        }
    }
ShouldPauseGame
virtual bool ActionMode.ShouldPauseGame get
Definition at line 175 of file ActionMode.cs.
Referenced by LayerMiniGame.OnUpdateInput().
ShowActionHint
virtual bool ActionMode.ShowActionHint get
Definition at line 165 of file ActionMode.cs.
Referenced by ActionHint.Refresh(), and ActionHint.UpdateText().
ShowBuildWidgets
virtual bool ActionMode.ShowBuildWidgets get
Definition at line 183 of file ActionMode.cs.
Referenced by Widget.Config.IsInRightMode(), and Widget.IsInRightMode().
ShowExtraHint
virtual bool ActionMode.ShowExtraHint get
Definition at line 243 of file ActionMode.cs.
Referenced by ExtraHint.OnChangeActionMode().
ShowMaskedThings
virtual bool ActionMode.ShowMaskedThings get
Definition at line 221 of file ActionMode.cs.
Referenced by BaseTileMap.DrawTile(), and RefreshTexts().
ShowMouseoverTarget
virtual bool ActionMode.ShowMouseoverTarget get
Definition at line 167 of file ActionMode.cs.
Referenced by PointTarget.Update().
SubMenuAsGroup
virtual bool ActionMode.SubMenuAsGroup get
Definition at line 239 of file ActionMode.cs.
Referenced by TerrainMenu.Show().
SubMenuModeIndex
virtual int ActionMode.SubMenuModeIndex get
Definition at line 241 of file ActionMode.cs.
Referenced by TerrainMenu.Show().
Summary
HitSummary ActionMode.Summary get
Definition at line 135 of file ActionMode.cs.
Referenced by CanProcessTiles().
TargetGameScreen
virtual BaseGameScreen ActionMode.TargetGameScreen get
Definition at line 231 of file ActionMode.cs.
Referenced by Activate().
TargetZoom
virtual float ActionMode.TargetZoom get
Definition at line 227 of file ActionMode.cs.
textHintTitle
virtual string ActionMode.textHintTitle get
Definition at line 161 of file ActionMode.cs.
Referenced by GetHintText().
tileSelector
BaseTileSelector ActionMode.tileSelector get
Definition at line 245 of file ActionMode.cs.
Referenced by OnRenderTile(), and OnRenderTileFloor().
UseSubMenu
virtual bool ActionMode.UseSubMenu get
Definition at line 235 of file ActionMode.cs.
Referenced by TerrainMenu.Show().
UseSubMenuSlider
virtual bool ActionMode.UseSubMenuSlider get
Definition at line 237 of file ActionMode.cs.
Referenced by TerrainMenu.Show().
The documentation for this class was generated from the following file:
Elin/ActionMode.cs