Elin Decompiled Documentation: LayerImage Class Reference
LayerImage Class Reference
Public Member Functions
void SetImage (Sprite sprite)
override void OnUpdateInput ()
void Zoom (float a)
override void OnKill ()
Public Member Functions inherited from ELayer
override void OnBeforeAddLayer ()
void InitInspector ()
sealed override void Init ()
override void OnAfterAddLayer ()
void TryShowHelp ()
void AddLayerToUI (string id)
void TryShowHint (string _langHint=null)
void TalkHomeMemeber (string id)
void TalkMaid (string id)
override void OnRightClick ()
Public Attributes
Image image
Vector2 margin
Private Attributes
float zoom = 1f
Additional Inherited Members
Static Public Member Functions inherited from ELayer
static int rnd (int a)
Protected Member Functions inherited from ELayer
sealed override void _Close ()
sealed override void Kill ()
Properties inherited from ELayer
static Core core [get]
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static FactionBranch Branch [get]
static Faction Home [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static CoreConfig config [get]
static GameSetting setting [get]
static ColorProfile Colors [get]
static SourceManager sources [get]
static World world [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
bool IsFloat [get]
virtual string IdHelp [get]
Detailed Description
Definition at line 4 of file LayerImage.cs.
Member Function Documentation
OnKill()
override void LayerImage.OnKill () inline
Definition at line 55 of file LayerImage.cs.
    {
        EInput.Consume(2);
    }
OnUpdateInput()
override void LayerImage.OnUpdateInput () inline
Definition at line 27 of file LayerImage.cs.
    {
        if (EInput.wheel != 0)
        {
            Zoom((EInput.wheel > 0) ? 0.25f : (-0.25f));
        }
        if (EInput.middleMouse.clicked)
        {
            image.SetNativeSize();
            zoom = 1f;
            Zoom(0f);
        }
    }
References image, zoom, and Zoom().
SetImage()
void LayerImage.SetImage (Sprite sprite) inline
Definition at line 12 of file LayerImage.cs.
    {
        image.sprite = sprite;
        image.SetNativeSize();
        float num = ((float)Screen.height - margin.y) / ELayer.core.uiScale;
        RectTransform rectTransform = image.rectTransform;
        float num2 = rectTransform.sizeDelta.y;
        if (num2 > num)
        {
            num2 = num;
        }
        rectTransform.sizeDelta = new Vector2(rectTransform.sizeDelta.x, num2);
        Zoom(0f);
    }
References ELayer.core, image, margin, Core.uiScale, and Zoom().
Zoom()
void LayerImage.Zoom (float a) inline
Definition at line 41 of file LayerImage.cs.
    {
        zoom += a;
        if (zoom < 0.5f)
        {
            zoom = 0.5f;
        }
        if (zoom > 2f)
        {
            zoom = 2f;
        }
        image.rectTransform.localScale = new Vector3(zoom, zoom, zoom);
    }
References zoom.
Referenced by OnUpdateInput(), and SetImage().
Member Data Documentation
image
Image LayerImage.image
Definition at line 6 of file LayerImage.cs.
Referenced by OnUpdateInput(), and SetImage().
margin
Vector2 LayerImage.margin
Definition at line 8 of file LayerImage.cs.
Referenced by SetImage().
zoom
float LayerImage.zoom = 1f private
Definition at line 10 of file LayerImage.cs.
Referenced by OnUpdateInput(), and Zoom().
The documentation for this class was generated from the following file:
Elin/LayerImage.cs