Elin Decompiled Documentation: UIButton.Item Class Reference
UIButton.Item Class Reference
Public Member Functions
virtual Sprite GetSprite ()
virtual Sprite GetSprite (bool highlight)
virtual bool ShouldHighlight ()
virtual void OnAddedToBar ()
virtual void OnShowContextMenu (UIContextMenu m)
virtual void OnHover (UIButton b)
virtual void OnClick (UIButton b)
virtual void OnSetItem (UIButton b)
virtual void SetSubText (UIText t)
Public Attributes
bool always
Properties
virtual string TextTip [get]
virtual string Name [get]
virtual Sprite SpriteHighlight [get]
virtual string pathSprite [get]
virtual bool IsSelectable [get]
virtual bool AdjustImageSize [get]
virtual bool UseIconForHighlight [get]
virtual bool KeepVisibleWhenHighlighted [get]
virtual Color SpriteColor [get]
virtual Vector3 SpriteScale [get]
virtual bool Hidden [get]
virtual Transition Transition [get]
Detailed Description
Definition at line 12 of file UIButton.cs.
Member Function Documentation
GetSprite() [1/2]
virtual Sprite UIButton.Item.GetSprite () inline virtual
Reimplemented in HotItemAct, HotItemChara, HotItemFocusChara, HotItemIcon, HotItemNoItem, and HotItemThing.
Definition at line 41 of file UIButton.cs.
        {
            return SpriteSheet.Get(pathSprite);
        }
References SpriteSheet.Get(), and UIButton.Item.pathSprite.
Referenced by HotItemSpeed.GetSprite(), WidgetHotbar.RefreshHighlight(), UIButton.RefreshItem(), and HotItem.SetImage().
GetSprite() [2/2]
virtual Sprite UIButton.Item.GetSprite (bool highlight) inline virtual
Reimplemented in HotItemSpeed, and HotItemToggleVisible.
Definition at line 46 of file UIButton.cs.
        {
            return null;
        }
OnAddedToBar()
virtual void UIButton.Item.OnAddedToBar () inline virtual
Definition at line 56 of file UIButton.cs.
        {
        }
OnClick()
virtual void UIButton.Item.OnClick (UIButton b) inline virtual
Reimplemented in HotItemContext, HotItemToggleLog, and HotItemToggleWidget.
Definition at line 68 of file UIButton.cs.
        {
        }
Referenced by ButtonHotItem.RefreshItem(), and UIButton.RefreshItem().
OnHover()
virtual void UIButton.Item.OnHover (UIButton b) inline virtual
Reimplemented in HotItemContext, and HotItemToggleVisible.
Definition at line 64 of file UIButton.cs.
        {
        }
Referenced by UIButton.OnHover().
OnSetItem()
virtual void UIButton.Item.OnSetItem (UIButton b) inline virtual
Reimplemented in HotItemLayer.
Definition at line 72 of file UIButton.cs.
        {
        }
Referenced by UIButton.SetItem().
OnShowContextMenu()
virtual void UIButton.Item.OnShowContextMenu (UIContextMenu m) inline virtual
Reimplemented in HotAction, HotItemContext, HotItemEQSet, HotItemLayout, and HotItemWidgetSet.
Definition at line 60 of file UIButton.cs.
        {
        }
Referenced by WidgetHotbar.OnSetContextMenu().
SetSubText()
virtual void UIButton.Item.SetSubText (UIText t) inline virtual
Reimplemented in HotItemThing.
Definition at line 76 of file UIButton.cs.
        {
            t.SetActive(enable: false);
        }
Referenced by ButtonHotItem.Refresh(), and UIButton.RefreshItem().
ShouldHighlight()
virtual bool UIButton.Item.ShouldHighlight () inline virtual
Reimplemented in HotItemActionMode, HotItemSpeed, HotItemToggle, and HotItemToggleVisible.
Definition at line 51 of file UIButton.cs.
        {
            return false;
        }
Referenced by WidgetHotbar.CheckAutoHide(), and WidgetHotbar.RefreshHighlight().
Member Data Documentation
always
bool UIButton.Item.always
Definition at line 15 of file UIButton.cs.
Referenced by WidgetHotbar.OnSetContextMenu(), WidgetHotbar.SetVisible(), and WidgetHotbar.ToggleVisible().
Property Documentation
AdjustImageSize
virtual bool UIButton.Item.AdjustImageSize get
Definition at line 27 of file UIButton.cs.
Referenced by UIButton.RefreshItem(), and HotItem.SetImage().
Hidden
virtual bool UIButton.Item.Hidden get
Definition at line 37 of file UIButton.cs.
Referenced by ButtonHotItem.RefreshItem(), and UIButton.RefreshItem().
IsSelectable
virtual bool UIButton.Item.IsSelectable get
Definition at line 25 of file UIButton.cs.
KeepVisibleWhenHighlighted
virtual bool UIButton.Item.KeepVisibleWhenHighlighted get
Definition at line 31 of file UIButton.cs.
Referenced by WidgetHotbar.CheckAutoHide(), and WidgetHotbar.RefreshHighlight().
Name
virtual string UIButton.Item.Name get
Definition at line 19 of file UIButton.cs.
Referenced by ActPlan._Update(), and WidgetHotbar.SetShortcutMenu().
pathSprite
virtual string UIButton.Item.pathSprite get
Definition at line 23 of file UIButton.cs.
Referenced by UIButton.Item.GetSprite().
SpriteColor
virtual Color UIButton.Item.SpriteColor get
Definition at line 33 of file UIButton.cs.
Referenced by HotItem.SetImage().
SpriteHighlight
virtual Sprite UIButton.Item.SpriteHighlight get
Definition at line 21 of file UIButton.cs.
Referenced by WidgetHotbar.RefreshHighlight().
SpriteScale
virtual Vector3 UIButton.Item.SpriteScale get
Definition at line 35 of file UIButton.cs.
Referenced by UIButton.RefreshItem(), and HotItem.SetImage().
TextTip
virtual string UIButton.Item.TextTip get
Definition at line 17 of file UIButton.cs.
Referenced by ButtonHotItem.RefreshItem(), and UIButton.RefreshItem().
Transition
virtual Transition UIButton.Item.Transition get
Definition at line 39 of file UIButton.cs.
Referenced by ButtonHotItem.RefreshItem(), and UIButton.RefreshItem().
UseIconForHighlight
virtual bool UIButton.Item.UseIconForHighlight get
Definition at line 29 of file UIButton.cs.
Referenced by WidgetHotbar.RefreshHighlight().
The documentation for this class was generated from the following file:
Elin/Plugins.UI/UIButton.cs