Elin Decompiled Documentation: PathManager Class Reference
PathManager Class Reference
Public Types
enum MoveType { Default , Combat }
Public Member Functions
void RequestPath (PathProgress progress)
void RequestPathImmediate (PathProgress progress)
bool IsPathClear (Point origin, Point dest, IPathfindWalker walker, int radius)
PathProgress RequestPathImmediate (Point origin, Point dest, IPathfindWalker walker, MoveType moveType=MoveType.Default, int searchLimit=-1, int destDist=0)
Point GetFirstStep (Point origin, Point _dest, IPathfindWalker walker, int maxDist=20, MoveType moveType=MoveType.Default)
Point _GetFirstStep (Point origin, Point dest, IPathfindWalker walker, int maxDist=20, MoveType moveType=MoveType.Default)
void OnGridModified ()
Public Attributes
PathFinder _pathfinder
int searchLimit = 1000000
Static Public Attributes
static int requestCount
static PathManager Instance
static PathProgress tempProgress = new PathProgress()
Properties
IPathfinder pathfinder [get]
Private Member Functions
void Awake ()
Detailed Description
Definition at line 6 of file PathManager.cs.
Member Enumeration Documentation
MoveType
enum PathManager.MoveType
Enumerator
Default
Combat
Definition at line 8 of file PathManager.cs.
    {
        Default,
        Combat
    }
Member Function Documentation
_GetFirstStep()
Point PathManager._GetFirstStep (Point origin, Point dest, IPathfindWalker walker, int maxDist = 20, MoveType moveType = MoveType::Default) inline
Definition at line 78 of file PathManager.cs.
    {
        if (!dest.IsValid || (dest.cell.blocked && origin.Distance(dest) <= 1))
        {
            return Point.Invalid;
        }
        tempProgress.walker = walker;
        tempProgress.moveType = moveType;
        tempProgress.RequestPathImmediate(origin, dest, (moveType == MoveType.Combat) ? 1 : 0, _ignoreConnection: false, maxDist);
        if (!tempProgress.HasPath)
        {
            return Point.Invalid;
        }
        List<PathFinderNode> nodes = tempProgress.nodes;
        if (nodes.Count > 0)
        {
            PathFinderNode pathFinderNode = nodes[nodes.Count - 1];
            if (pathFinderNode.X == origin.x && pathFinderNode.Z == origin.z && nodes.Count > 1)
            {
                pathFinderNode = nodes[nodes.Count - 2];
            }
            if (Mathf.Abs(pathFinderNode.X - origin.x) > 1 || Mathf.Abs(pathFinderNode.Z - origin.z) > 1)
            {
                return Point.Invalid;
            }
            Point point = new Point(pathFinderNode.X, pathFinderNode.Z);
            if (point.x == origin.x && point.z == origin.z)
            {
                return Point.Invalid;
            }
            return point;
        }
        return Point.Invalid;
    }
References Algorithms.WeightCell.blocked, Point.cell, Point.Distance(), PathProgress.HasPath, Point.Invalid, Point.IsValid, PathProgress.nodes, PathProgress.RequestPathImmediate(), tempProgress, Algorithms.PathFinderNode.X, Point.x, Algorithms.PathFinderNode.Z, and Point.z.
Referenced by GetFirstStep().
Awake()
void PathManager.Awake () inline private
Definition at line 26 of file PathManager.cs.
    {
        Instance = this;
    }
References Instance.
GetFirstStep()
Point PathManager.GetFirstStep (Point origin, Point _dest, IPathfindWalker walker, int maxDist = 20, MoveType moveType = MoveType::Default) inline
Definition at line 67 of file PathManager.cs.
    {
        Point dest = _dest.Copy();
        Point point = _GetFirstStep(origin, dest, walker, maxDist, moveType);
        if (point.IsValid)
        {
            return point;
        }
        return Point.Invalid;
    }
References _GetFirstStep(), Point.Copy(), Point.Invalid, and Point.IsValid.
Referenced by Chara.GetFirstStep().
IsPathClear()
bool PathManager.IsPathClear (Point origin, Point dest, IPathfindWalker walker, int radius) inline
Definition at line 47 of file PathManager.cs.
    {
        tempProgress.walker = walker;
        tempProgress.moveType = MoveType.Default;
        tempProgress.RequestPathImmediate(origin, dest, 0, _ignoreConnection: false);
        if (tempProgress.nodes.Count > 0)
        {
            return tempProgress.nodes.Count < radius;
        }
        return false;
    }
References PathProgress.nodes, PathProgress.RequestPathImmediate(), and tempProgress.
Referenced by Zone.AddGlobalCharasOnActivate().
OnGridModified()
void PathManager.OnGridModified () inline
Definition at line 113 of file PathManager.cs.
    {
    }
RequestPath()
void PathManager.RequestPath (PathProgress progress) inline
Definition at line 31 of file PathManager.cs.
    {
        requestCount++;
        progress.state = PathProgress.State.Searching;
        ThreadPool.QueueUserWorkItem(delegate
        {
            new PathThread().Start(progress);
        });
    }
References requestCount, and PathThread.Start().
Referenced by PathProgress.RequestPath().
RequestPathImmediate() [1/2]
void PathManager.RequestPathImmediate (PathProgress progress) inline
Definition at line 41 of file PathManager.cs.
    {
        requestCount++;
        pathfinder.FindPath(progress);
    }
References IPathfinder.FindPath(), pathfinder, and requestCount.
Referenced by Spatial.Dist(), Zone_Dungeon.PlaceRail(), AM_Adv.PressedActionMove(), PathProgress.RequestPathImmediate(), Chara.TryMoveTowards(), and GameUpdater.Update().
RequestPathImmediate() [2/2]
PathProgress PathManager.RequestPathImmediate (Point origin, Point dest, IPathfindWalker walker, MoveType moveType = MoveType::Default, int searchLimit = -1, int destDist = 0) inline
Definition at line 59 of file PathManager.cs.
    {
        tempProgress.walker = walker;
        tempProgress.moveType = moveType;
        tempProgress.RequestPathImmediate(origin, dest, destDist, _ignoreConnection: false, searchLimit);
        return tempProgress;
    }
References PathProgress.RequestPathImmediate(), searchLimit, and tempProgress.
Member Data Documentation
_pathfinder
PathFinder PathManager._pathfinder
Definition at line 20 of file PathManager.cs.
Referenced by WidgetDebug.UpdateText().
Instance
PathManager PathManager.Instance static
Definition at line 16 of file PathManager.cs.
Referenced by Zone.AddGlobalCharasOnActivate(), Awake(), Spatial.Dist(), Chara.GetFirstStep(), Zone_Dungeon.PlaceRail(), AM_Adv.PressedActionMove(), PathProgress.RequestPath(), PathProgress.RequestPathImmediate(), Map.SetReference(), PathThread.Start(), Chara.TryMoveTowards(), GameUpdater.Update(), and WidgetDebug.UpdateText().
requestCount
int PathManager.requestCount static
Definition at line 14 of file PathManager.cs.
Referenced by RequestPath(), RequestPathImmediate(), and WidgetDebug.UpdateText().
searchLimit
int PathManager.searchLimit = 1000000
Definition at line 22 of file PathManager.cs.
Referenced by PathProgress.RequestPath(), PathProgress.RequestPathImmediate(), and RequestPathImmediate().
tempProgress
PathProgress PathManager.tempProgress = new PathProgress() static
Definition at line 18 of file PathManager.cs.
Referenced by _GetFirstStep(), IsPathClear(), and RequestPathImmediate().
Property Documentation
pathfinder
IPathfinder PathManager.pathfinder get
Definition at line 24 of file PathManager.cs.
Referenced by RequestPathImmediate(), Map.SetReference(), PathThread.Start(), and WidgetDebug.UpdateText().
The documentation for this class was generated from the following file:
Elin/PathManager.cs