Elin Decompiled Documentation: InputFieldsTabSwitcher Class Reference
InputFieldsTabSwitcher Class Reference
Public Member Functions
void RegisterInputField (UiInputField input)
void UnregisterInputField (UiInputField input)
Public Member Functions inherited from ManlySingleton< InputFieldsTabSwitcher >
override void Elect ()
Private Member Functions
void Start ()
void Update ()
void TrySelectNextInput ()
void CheckIfAnyInputIsSelected ()
void SelectNextInput ()
void IterateSelectableIndex ()
Private Attributes
EventSystem currentEventSystem
List< UiInputField > activeInputs = new List<UiInputField>()
int currentActiveInputIndex = -1
Additional Inherited Members
Static Public Member Functions inherited from ManlySingleton< InputFieldsTabSwitcher >
static bool Exists ()
Protected Member Functions inherited from ManlySingleton< InputFieldsTabSwitcher >
void Abdicate ()
virtual void OnDestroy ()
Properties inherited from ManlySingleton< InputFieldsTabSwitcher >
static T?? Instance [get]
static T InstanceOrNull [get]
static Transform STransform [get]
static Vector3 SPosition [get, set]
static GameObject SGameObject [get]
Detailed Description
Definition at line 5 of file InputFieldsTabSwitcher.cs.
Member Function Documentation
CheckIfAnyInputIsSelected()
void InputFieldsTabSwitcher.CheckIfAnyInputIsSelected () inline private
Definition at line 32 of file InputFieldsTabSwitcher.cs.
    {
        GameObject selectedObject = currentEventSystem.currentSelectedGameObject;
        if (selectedObject != null)
        {
            currentActiveInputIndex = activeInputs.FindIndex((UiInputField x) => x.gameObject == selectedObject);
        }
    }
References activeInputs, currentActiveInputIndex, and currentEventSystem.
Referenced by TrySelectNextInput().
IterateSelectableIndex()
void InputFieldsTabSwitcher.IterateSelectableIndex () inline private
Definition at line 52 of file InputFieldsTabSwitcher.cs.
    {
        currentActiveInputIndex++;
        currentActiveInputIndex %= activeInputs.Count;
    }
References activeInputs, and currentActiveInputIndex.
Referenced by SelectNextInput().
RegisterInputField()
void InputFieldsTabSwitcher.RegisterInputField (UiInputField input) inline
Definition at line 58 of file InputFieldsTabSwitcher.cs.
    {
        if (!activeInputs.Contains(input))
        {
            activeInputs.Add(input);
        }
    }
References activeInputs.
SelectNextInput()
void InputFieldsTabSwitcher.SelectNextInput () inline private
Definition at line 41 of file InputFieldsTabSwitcher.cs.
    {
        if (currentActiveInputIndex > -1)
        {
            activeInputs[currentActiveInputIndex].DeactivateInputField();
            IterateSelectableIndex();
            currentEventSystem.SetSelectedGameObject(activeInputs[currentActiveInputIndex].gameObject);
            activeInputs[currentActiveInputIndex].ActivateInputField();
        }
    }
References activeInputs, currentActiveInputIndex, currentEventSystem, and IterateSelectableIndex().
Referenced by TrySelectNextInput().
Start()
void InputFieldsTabSwitcher.Start () inline private
Definition at line 13 of file InputFieldsTabSwitcher.cs.
    {
        currentEventSystem = EventSystem.current;
    }
References currentEventSystem.
TrySelectNextInput()
void InputFieldsTabSwitcher.TrySelectNextInput () inline private
Definition at line 26 of file InputFieldsTabSwitcher.cs.
    {
        CheckIfAnyInputIsSelected();
        SelectNextInput();
    }
References CheckIfAnyInputIsSelected(), and SelectNextInput().
Referenced by Update().
UnregisterInputField()
void InputFieldsTabSwitcher.UnregisterInputField (UiInputField input) inline
Definition at line 66 of file InputFieldsTabSwitcher.cs.
    {
        if (activeInputs.Contains(input))
        {
            activeInputs.Remove(input);
        }
    }
References activeInputs.
Update()
void InputFieldsTabSwitcher.Update () inline private
Definition at line 18 of file InputFieldsTabSwitcher.cs.
    {
        if (Input.GetKeyDown(KeyCode.Tab))
        {
            TrySelectNextInput();
        }
    }
References TrySelectNextInput().
Member Data Documentation
activeInputs
List<UiInputField> InputFieldsTabSwitcher.activeInputs = new List<UiInputField>() private
Definition at line 9 of file InputFieldsTabSwitcher.cs.
Referenced by CheckIfAnyInputIsSelected(), IterateSelectableIndex(), RegisterInputField(), SelectNextInput(), and UnregisterInputField().
currentActiveInputIndex
int InputFieldsTabSwitcher.currentActiveInputIndex = -1 private
Definition at line 11 of file InputFieldsTabSwitcher.cs.
Referenced by CheckIfAnyInputIsSelected(), IterateSelectableIndex(), and SelectNextInput().
currentEventSystem
EventSystem InputFieldsTabSwitcher.currentEventSystem private
Definition at line 7 of file InputFieldsTabSwitcher.cs.
Referenced by CheckIfAnyInputIsSelected(), SelectNextInput(), and Start().
The documentation for this class was generated from the following file:
Elin/Plugins.UI/InputFieldsTabSwitcher.cs