Elin Decompiled Documentation: SourcePrefInspector Class Reference
SourcePrefInspector Class Reference
Public Member Functions
void ToggleUsePref ()
void ValidatePrefs ()
Public Attributes
string id
SourcePref pref
ShadowData.Item shadow
ShadowData shadowData
Static Public Attributes
static SourcePrefInspector Instance
static bool dirty
Static Public Attributes inherited from EMono
static Core core
Properties
bool CanToggleUsePref [get]
Properties inherited from EMono
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SoundManager Sound [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static CoreDebug debug [get]
Private Member Functions
void Awake ()
void OnValidate ()
void OnApplicationQuit ()
Private Attributes
Point lastPoint = new Point()
int index
int lastShadowIndex = -1
RenderRow target
Card card
List< RenderRow > list = new List<RenderRow>()
Additional Inherited Members
Static Public Member Functions inherited from EMono
static int rnd (int a)
Detailed Description
Definition at line 4 of file SourcePrefInspector.cs.
Member Function Documentation
Awake()
void SourcePrefInspector.Awake () inline private
Definition at line 51 of file SourcePrefInspector.cs.
    {
        Instance = this;
        ShadowData.Instance = shadowData;
    }
References Instance, and shadowData.
OnApplicationQuit()
void SourcePrefInspector.OnApplicationQuit () inline private
Definition at line 79 of file SourcePrefInspector.cs.
    {
    }
OnValidate()
void SourcePrefInspector.OnValidate () inline private
Definition at line 57 of file SourcePrefInspector.cs.
    {
        if (card != null && card.ExistsOnMap)
        {
            card.isFloating = card.Pref.Float;
        }
    }
References card, Card.ExistsOnMap, SourcePref.Float, and Card.Pref.
ToggleUsePref()
void SourcePrefInspector.ToggleUsePref () inline
Definition at line 43 of file SourcePrefInspector.cs.
    {
        if (CanToggleUsePref)
        {
            (target as CardRow).pref.flags |= PrefFlag.UsePref;
        }
    }
References CanToggleUsePref, SourcePref.flags, pref, and target.
ValidatePrefs()
void SourcePrefInspector.ValidatePrefs () inline
Definition at line 65 of file SourcePrefInspector.cs.
    {
        EMono.debug.validatePref = false;
        EMono.sources.foods.ValidatePref();
        EMono.sources.thingV.ValidatePref();
        EMono.sources.things.ValidatePref();
        EMono.sources.charas.ValidatePref();
        EMono.sources.objs.ValidatePref();
        foreach (ShadowData.Item item in shadowData.items)
        {
            item.Validate();
        }
    }
References SourceManager.charas, SourceManager.foods, item, ShadowData.items, SourceManager.objs, shadowData, EMono.sources, SourceManager.things, SourceManager.thingV, SourceChara.ValidatePref(), SourceObj.ValidatePref(), and SourceThingV.ValidatePref().
Referenced by Core.Init().
Member Data Documentation
card
Card SourcePrefInspector.card private
Definition at line 21 of file SourcePrefInspector.cs.
Referenced by OnValidate().
dirty
bool SourcePrefInspector.dirty static
Definition at line 27 of file SourcePrefInspector.cs.
id
string SourcePrefInspector.id
Definition at line 8 of file SourcePrefInspector.cs.
index
int SourcePrefInspector.index private
Definition at line 15 of file SourcePrefInspector.cs.
Instance
SourcePrefInspector SourcePrefInspector.Instance static
Definition at line 6 of file SourcePrefInspector.cs.
Referenced by Awake(), and Core.Init().
lastPoint
Point SourcePrefInspector.lastPoint = new Point() private
Definition at line 13 of file SourcePrefInspector.cs.
lastShadowIndex
int SourcePrefInspector.lastShadowIndex = -1 private
Definition at line 17 of file SourcePrefInspector.cs.
list
List<RenderRow> SourcePrefInspector.list = new List<RenderRow>() private
Definition at line 29 of file SourcePrefInspector.cs.
pref
SourcePref SourcePrefInspector.pref
Definition at line 11 of file SourcePrefInspector.cs.
Referenced by ToggleUsePref().
shadow
ShadowData.Item SourcePrefInspector.shadow
Definition at line 23 of file SourcePrefInspector.cs.
shadowData
ShadowData SourcePrefInspector.shadowData
Definition at line 25 of file SourcePrefInspector.cs.
Referenced by Awake(), and ValidatePrefs().
target
RenderRow SourcePrefInspector.target private
Definition at line 19 of file SourcePrefInspector.cs.
Referenced by ToggleUsePref().
Property Documentation
CanToggleUsePref
bool SourcePrefInspector.CanToggleUsePref get
Definition at line 31 of file SourcePrefInspector.cs.
    {
        get
        {
            if (target is CardRow { origin: not null } cardRow)
            {
                return !cardRow.pref.UsePref;
            }
            return false;
        }
    }
Referenced by ToggleUsePref().
The documentation for this class was generated from the following file:
Elin/SourcePrefInspector.cs