Elin Decompiled Documentation: ItemResearch Class Reference
ItemResearch Class Reference
Public Member Functions
void SetPlan (ResearchPlan p, UIList list, FactionBranch branch, LayerTech layer)
Public Member Functions inherited from UIItem
void SetTopic (string lang1, string lang2)
void SetWidth (int w)
void Hyphenate ()
Public Attributes
Image imageExp
Image goFocus
ResearchPlan plan
Public Attributes inherited from UIItem
UIText text1
UIText text2
UIText text3
UIText text4
Image image1
Image image2
UIButton button1
UIButton button2
UIButton button3
UIItem item
Toggle toggle
UIDropdown dd
object refObj
Detailed Description
Definition at line 3 of file ItemResearch.cs.
Member Function Documentation
SetPlan()
void ItemResearch.SetPlan (ResearchPlan p, UIList list, FactionBranch branch, LayerTech layer) inline
Definition at line 11 of file ItemResearch.cs.
    {
        bool isFinished = !branch.researches.plans.Contains(p);
        plan = p;
        button1.mainText.text = p.Name;
        goFocus.SetActive(branch.researches.focused == p);
        string text = p.source.tech.ToString("#,0").TagColorGoodBad(() => branch.researches.CanCompletePlan(p));
        button1.subText.text = text;
        button1.subText.SetActive(!isFinished);
        imageExp.fillAmount = (float)branch.resources.knowledge.value / (float)p.source.tech;
        button1.tooltip.onShowTooltip = delegate(UITooltip tp)
        {
            p.WriteNote(tp.note);
        };
        button1.onClick.AddListener(delegate
        {
            if (!isFinished)
            {
                if (!branch.researches.CanCompletePlan(p))
                {
                    SE.Beep();
                }
                else
                {
                    UIContextMenu uIContextMenu = EClass.ui.CreateContextMenuInteraction().SetHighlightTarget(button1);
                    uIContextMenu.AddButton("buy", delegate
                    {
                        branch.resources.knowledge.Mod(-p.source.tech);
                        branch.researches.CompletePlan(p);
                        layer.RefreshTech();
                    });
                    uIContextMenu.Show();
                }
            }
        });
    }
References UIItem.button1, ResearchManager.CanCompletePlan(), ResearchManager.focused, goFocus, HomeResourceManager.knowledge, ResearchPlan.Name, UITooltip.note, plan, ResearchManager.plans, FactionBranch.researches, FactionBranch.resources, ResearchPlan.source, UIButton.subText, BaseHomeResource.value, and ResearchPlan.WriteNote().
Referenced by LayerTech.RefreshTech().
Member Data Documentation
goFocus
Image ItemResearch.goFocus
Definition at line 7 of file ItemResearch.cs.
Referenced by LayerHome.RefreshFocus(), LayerTech.RefreshFocus(), and SetPlan().
imageExp
Image ItemResearch.imageExp
Definition at line 5 of file ItemResearch.cs.
plan
ResearchPlan ItemResearch.plan
Definition at line 9 of file ItemResearch.cs.
Referenced by LayerHome.RefreshFocus(), LayerTech.RefreshFocus(), and SetPlan().
The documentation for this class was generated from the following file:
Elin/ItemResearch.cs