Elin Decompiled Documentation: HotItemNoItem Class Reference
HotItemNoItem Class Reference
Public Member Functions
override Sprite GetSprite ()
override bool TrySetAct (ActPlan p)
Public Member Functions inherited from HotItemGameAction
override void OnClick (ButtonHotItem b, Hotbar h)
override void OnRightClick (ButtonHotItem b)
override void OnMarkMapHighlights ()
Public Member Functions inherited from HotItem
string TextHotkey ()
virtual void OnClick (ButtonHotItem b, Hotbar h)
virtual void OnRightClick (ButtonHotItem b)
virtual bool CanAutoFire (Chara tg)
virtual void OnSetCurrentItem ()
virtual void OnUnsetCurrentItem ()
virtual void OnUnselect ()
virtual void SetImage (Image icon)
virtual bool TrySetAct (ActPlan p)
virtual void OnMarkMapHighlights ()
virtual void OnRenderTile (Point point, HitResult result, int dir)
Public Member Functions inherited from UIButton.Item
virtual Sprite GetSprite ()
virtual Sprite GetSprite (bool highlight)
virtual bool ShouldHighlight ()
virtual void OnAddedToBar ()
virtual void OnShowContextMenu (UIContextMenu m)
virtual void OnHover (UIButton b)
virtual void OnClick (UIButton b)
virtual void OnSetItem (UIButton b)
virtual void SetSubText (UIText t)
Static Public Member Functions
static bool _TrySetAct (ActPlan p)
Additional Inherited Members
Public Attributes inherited from HotItem
ButtonHotItem button
Hotbar hotbar
bool disabled
Public Attributes inherited from UIButton.Item
bool always
Properties inherited from HotItemGameAction
virtual Act act [get]
override bool IsGameAction [get]
Properties inherited from HotItem
override Sprite SpriteHighlight [get]
override bool IsSelectable [get]
override string TextTip [get]
virtual Thing RenderThing [get]
virtual Thing Thing [get]
virtual Thing Tool [get]
virtual bool IsTool [get]
virtual bool LookAtMouse [get]
virtual bool IsGameAction [get]
virtual bool UseUIObjMaterial [get]
Properties inherited from UIButton.Item
virtual string TextTip [get]
virtual string Name [get]
virtual Sprite SpriteHighlight [get]
virtual string pathSprite [get]
virtual bool IsSelectable [get]
virtual bool AdjustImageSize [get]
virtual bool UseIconForHighlight [get]
virtual bool KeepVisibleWhenHighlighted [get]
virtual Color SpriteColor [get]
virtual Vector3 SpriteScale [get]
virtual bool Hidden [get]
virtual Transition Transition [get]
Detailed Description
Definition at line 3 of file HotItemNoItem.cs.
Member Function Documentation
_TrySetAct()
static bool HotItemNoItem._TrySetAct (ActPlan p) inline static
Definition at line 10 of file HotItemNoItem.cs.
    {
        if (p.IsNeighborBlocked || !p.IsSelfOrNeighbor)
        {
            return false;
        }
        Card tg = null;
        p.pos.ListVisibleCards().ForeachReverse(delegate(Card a)
        {
            if (a.TileType.CanBeHeld && a.trait.CanBeHeld && a.isThing && !a.isNPCProperty && a.isThing && a.TileType.CanBeHeld)
            {
                tg = a;
                return true;
            }
            return false;
        });
        if (tg != null)
        {
            return p.TrySetAct("actHold", delegate
            {
                if (tg.ExistsOnMap)
                {
                    if (!EClass.pc.CanLift(tg))
                    {
                        EClass.pc.Say("tooHeavy", tg);
                        return false;
                    }
                    if (tg.HasEditorTag(EditorTag.TreasureMelilith))
                    {
                        if (EClass.player.flags.pickedMelilithTreasure)
{
                            EClass.pc.PlaySound("curse3");
                            EClass.pc.PlayEffect("curse");
                            EClass.pc.SetFeat(1206, 1, msg: true);
                            EClass.player.flags.gotMelilithCurse = true;
                        }
                        else
{
                            Msg.Say("pickedMelilithTreasure");
                            EClass.player.flags.pickedMelilithTreasure = true;
                            EClass.game.quests.Get<QuestCursedManor>()?.NextPhase();
                        }
                        tg.c_editorTags = null;
                    }
                    EClass.pc.HoldCard(tg);
                    if (EClass.pc.held != null)
                    {
                        tg.PlaySoundHold(spatial: false);
                        EClass.player.RefreshCurrentHotItem();
                        ActionMode.Adv.planRight.Update(ActionMode.Adv.mouseTarget);
                        EClass.pc.renderer.Refresh();
                    }
                }
                return true;
            }, tg, null, 1, isHostileAct: false, localAct: false);
        }
        TaskHarvest taskHarvest = TaskHarvest.TryGetAct(EClass.pc, p.pos);
        if (taskHarvest != null)
        {
            p.TrySetAct(taskHarvest);
        }
        return false;
    }
References Card.c_editorTags, TileType.CanBeHeld, Trait.CanBeHeld, Card.ExistsOnMap, Card.HasEditorTag(), Chara.held, Chara.HoldCard(), if(), ActPlan.IsNeighborBlocked, Card.isNPCProperty, ActPlan.IsSelfOrNeighbor, Card.isThing, Point.ListVisibleCards(), EClass.pc, ActPlan.pos, Card.TileType, Card.trait, and ActPlan.TrySetAct().
Referenced by ActPlan._Update().
GetSprite()
override Sprite HotItemNoItem.GetSprite () inline virtual
Reimplemented from UIButton.Item.
Definition at line 5 of file HotItemNoItem.cs.
    {
        return EClass.core.refs.icons.noHotItem;
    }
References EClass.core, CoreRef.icons, CoreRef.Icons.noHotItem, and Core.refs.
TrySetAct()
override bool HotItemNoItem.TrySetAct (ActPlan p) inline virtual
Reimplemented from HotItem.
Definition at line 74 of file HotItemNoItem.cs.
    {
        return _TrySetAct(p);
    }
The documentation for this class was generated from the following file:
Elin/HotItemNoItem.cs