Elin Decompiled Documentation: HotItem Class Reference
HotItem Class Reference
Public Member Functions
string TextHotkey ()
virtual void OnClick (ButtonHotItem b, Hotbar h)
virtual void OnRightClick (ButtonHotItem b)
virtual bool CanAutoFire (Chara tg)
virtual void OnSetCurrentItem ()
virtual void OnUnsetCurrentItem ()
virtual void OnUnselect ()
virtual void SetImage (Image icon)
virtual bool TrySetAct (ActPlan p)
virtual void OnMarkMapHighlights ()
virtual void OnRenderTile (Point point, HitResult result, int dir)
Public Attributes
ButtonHotItem button
Hotbar hotbar
bool disabled
Properties
override Sprite SpriteHighlight [get]
override bool IsSelectable [get]
override string TextTip [get]
virtual Thing RenderThing [get]
virtual Thing Thing [get]
virtual Thing Tool [get]
virtual bool IsTool [get]
virtual bool LookAtMouse [get]
virtual bool IsGameAction [get]
virtual bool UseUIObjMaterial [get]
Detailed Description
Definition at line 5 of file HotItem.cs.
Member Function Documentation
CanAutoFire()
virtual bool HotItem.CanAutoFire (Chara tg) inline virtual
Definition at line 129 of file HotItem.cs.
    {
        return false;
    }
OnClick()
virtual void HotItem.OnClick (ButtonHotItem b, Hotbar h) inline virtual
Reimplemented in HotAction, HotItemActionMode, HotItemFocusChara, HotItemGameAction, HotItemLayer, HotItemSpeed, HotItemToggle, HotItemTogglePage, HotItemToggleVisible, and HotItemWidget.
Definition at line 45 of file HotItem.cs.
    {
        this.OnClick(b);
    }
References OnClick().
Referenced by ActPlan._Update(), OnClick(), ButtonHotItem.RefreshItem(), and WidgetHotbar.TryUse().
OnMarkMapHighlights()
virtual void HotItem.OnMarkMapHighlights () inline virtual
Reimplemented in HotItemGameAction.
Definition at line 165 of file HotItem.cs.
    {
    }
Referenced by Player.MarkMapHighlights().
OnRenderTile()
virtual void HotItem.OnRenderTile (Point point, HitResult result, int dir) inline virtual
Reimplemented in HotItemHeld.
Definition at line 169 of file HotItem.cs.
    {
    }
Referenced by AM_Adv.OnRenderTile().
OnRightClick()
virtual void HotItem.OnRightClick (ButtonHotItem b) inline virtual
Reimplemented in HotItemGameAction.
Definition at line 50 of file HotItem.cs.
    {
        WidgetHotbar widget = b.widget;
        if (widget == null)
        {
            return;
        }
        widget.ShowContextMenu();
    }
References Widget.ShowContextMenu(), and ButtonHotItem.widget.
Referenced by ButtonHotItem.RefreshItem().
OnSetCurrentItem()
virtual void HotItem.OnSetCurrentItem () inline virtual
Reimplemented in HotItemHeld.
Definition at line 134 of file HotItem.cs.
    {
    }
Referenced by Player.RefreshCurrentHotItem().
OnUnselect()
virtual void HotItem.OnUnselect () inline virtual
Reimplemented in HotItemHeld.
Definition at line 142 of file HotItem.cs.
    {
    }
Referenced by Hotbar.ToggleDisable(), and Hotbar.Unselect().
OnUnsetCurrentItem()
virtual void HotItem.OnUnsetCurrentItem () inline virtual
Definition at line 138 of file HotItem.cs.
    {
    }
Referenced by Player.RefreshCurrentHotItem().
SetImage()
virtual void HotItem.SetImage (Image icon) inline virtual
Reimplemented in HotItemAct, and HotItemThing.
Definition at line 146 of file HotItem.cs.
    {
        icon.sprite = (this.GetSprite() ?? EClass.core.refs.icons.defaultHotItem);
        icon.color = this.SpriteColor;
        icon.transform.localScale = this.SpriteScale;
        icon.rectTransform.pivot = new Vector2(0.5f, 0.5f);
        if (this.AdjustImageSize)
        {
            icon.SetNativeSize();
            return;
        }
        icon.Rect().sizeDelta = new Vector2(48f, 48f);
    }
References EClass.core.
Referenced by WidgetCurrentTool._RefreshCurrentHotItem(), ButtonHotItem.RefreshItem(), and ActPlan.Update().
TextHotkey()
string HotItem.TextHotkey () inline
Definition at line 31 of file HotItem.cs.
    {
        if (!this.hotbar.ShowFunctionKey)
        {
            return "";
        }
        int num = this.hotbar.CurrentPage.items.IndexOf(this) + 1;
        if (num > 8)
        {
            return "";
        }
        return " (F" + num.ToString() + ")";
    }
References Hotbar.CurrentPage, hotbar, and Hotbar.ShowFunctionKey.
TrySetAct()
virtual bool HotItem.TrySetAct (ActPlan p) inline virtual
Reimplemented in HotItemAct, HotItemChara, HotItemHeld, and HotItemNoItem.
Definition at line 160 of file HotItem.cs.
    {
        return false;
    }
Referenced by ActPlan._Update().
Member Data Documentation
button
ButtonHotItem HotItem.button
Definition at line 173 of file HotItem.cs.
Referenced by ActPlan._Update(), and WidgetHotbar.TryUse().
disabled
bool HotItem.disabled
Definition at line 177 of file HotItem.cs.
Referenced by Hotbar.ToggleDisable().
hotbar
Hotbar HotItem.hotbar
Definition at line 175 of file HotItem.cs.
Referenced by ActPlan._Update(), HotItemGameAction.OnClick(), HotItemGameAction.OnRightClick(), and TextHotkey().
Property Documentation
IsGameAction
virtual bool HotItem.IsGameAction get
Definition at line 113 of file HotItem.cs.
    {
        get
        {
            return false;
        }
    }
Referenced by ActPlan._Update().
IsSelectable
override bool HotItem.IsSelectable get
Definition at line 15 of file HotItem.cs.
    {
        get
        {
            return true;
        }
    }
IsTool
virtual bool HotItem.IsTool get
Definition at line 97 of file HotItem.cs.
    {
        get
        {
            return false;
        }
    }
LookAtMouse
virtual bool HotItem.LookAtMouse get
Definition at line 105 of file HotItem.cs.
    {
        get
        {
            return false;
        }
    }
Referenced by AM_Adv._OnUpdateInput().
RenderThing
virtual Thing HotItem.RenderThing get
Definition at line 60 of file HotItem.cs.
    {
        get
        {
            if (EClass.pc.ai.RenderThing != null)
            {
                return EClass.pc.ai.RenderThing;
            }
            if (EClass.player.renderThing != null)
            {
                return EClass.player.renderThing;
            }
            Thing thing = this.Thing;
            if (!(((thing != null) ? thing.trait : null) is TraitAbility))
            {
                return this.Thing;
            }
            return null;
        }
    }
Referenced by CharaActorPCC.OnRender().
SpriteHighlight
override Sprite HotItem.SpriteHighlight get
Definition at line 7 of file HotItem.cs.
    {
        get
        {
            return EClass.core.refs.spritesHighlight[1];
        }
    }
TextTip
override string HotItem.TextTip get
Definition at line 23 of file HotItem.cs.
    {
        get
        {
            return base.TextTip + this.TextHotkey();
        }
    }
Referenced by ButtonHotItem.RefreshItem().
Thing
virtual Thing HotItem.Thing get
Definition at line 81 of file HotItem.cs.
    {
        get
        {
            return null;
        }
    }
Referenced by AM_Adv._OnUpdateInput(), ActPlan._Update(), WidgetCurrentTool.OnClickButtonHotItem(), ConTorch.OnRemoved(), TraitAmmo.OnUse(), ButtonHotItem.Refresh(), UIPlaceHelper.Refresh(), TCOrbitChara.RefreshAll(), TCOrbitThing.RefreshAll(), Player.RefreshCurrentHotItem(), UIInventory.RefreshHighlight(), WidgetCurrentTool.RefreshHighlight(), Player.TargetRanged(), Chara.Tick(), and Chara.TryEquipRanged().
Tool
virtual Thing HotItem.Tool get
Definition at line 89 of file HotItem.cs.
    {
        get
        {
            return null;
        }
    }
UseUIObjMaterial
virtual bool HotItem.UseUIObjMaterial get
Definition at line 121 of file HotItem.cs.
    {
        get
        {
            return false;
        }
    }
The documentation for this class was generated from the following file:
Elin/HotItem.cs