Elin Decompiled Documentation: ModUtil Class Reference
ModUtil Class Reference
Static Public Member Functions
static void OnModsActivated ()
static void LoadTypeFallback ()
static void RegisterSerializedTypeFallback (string nameAssembly, string nameType, string nameFallbackType)
static ModPackage GetModPackage (string modId)
static void ImportExcel (string pathToExcelFile, string sheetName, SourceData source)
static ModPackage FindSourceRowPackage (SourceData.BaseRow row)
static SerializableSoundData GetSoundMeta (string soundPath)
static AudioType GetAudioType (string extension)
static SoundData LoadSoundData (string soundId)
static SoundData LoadSoundData (FileInfo soundFile)
static void AddOrReplaceBGM (string bgmId)
static ModPackage FindSoundPackage (string soundId)
static Playlist CreatePlaylist (ref List< int > bgmIds, Playlist mold=null)
static void SetBGMKnown (int bgmId, bool known=true)
static string[] LoadBookList ()
static string[] LoadTopicFiles ()
Static Public Member Functions inherited from EClass
static int rndSeed (int a, int seed)
static int rnd (long a)
static int rnd (int a)
static int curve (long _a, int start, int step, int rate=75)
static int sqrt (int a)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Static Public Attributes
static SourceImporter sourceImporter = new SourceImporter(SourceMapping)
static Dictionary< string, string > fallbackTypes = new Dictionary<string, string>()
Static Public Attributes inherited from EClass
static Core core
Properties
static IReadOnlyDictionary< string, SourceData > SourceMapping [get]
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Static Private Member Functions
static void PostLoadCleanup (object context)
Detailed Description
Definition at line 13 of file ModUtil.cs.
Member Function Documentation
AddOrReplaceBGM()
static void ModUtil.AddOrReplaceBGM (string bgmId) inline static
Definition at line 206 of file ModUtil.cs.
    {
        List<BGMData> bgms = Core.Instance.refs.bgms;
        Dictionary<int, BGMData> dictBGM = Core.Instance.refs.dictBGM;
        BGMData bGMData = SoundManager.current.GetData(bgmId) as BGMData;
        if (!(bGMData == null))
        {
            bGMData.name = bgmId[4..];
            if (bGMData.id <= 0)
            {
                bGMData.id = bgms.Count + 1;
                UnityEngine.Debug.Log($"#sound bgm unassigned/{bGMData.id}/{bGMData.name}");
            }
            if (dictBGM.TryGetValue(bGMData.id, out var value))
            {
                value.clip = bGMData.clip;
                UnityEngine.Debug.Log($"#sound bgm replace/{bGMData.id}/{value.name}/>/{bGMData.name}");
            }
            else
            {
                bgms.Add(bGMData);
                dictBGM[bGMData.id] = bGMData;
                UnityEngine.Debug.Log($"#sound bgm addon/{bGMData.id}/{bGMData.name}");
            }
        }
    }
References $, CoreRef.bgms, CoreRef.dictBGM, Core.Instance, and Core.refs.
Referenced by CoreRef.RefreshBGM().
CreatePlaylist()
static Playlist ModUtil.CreatePlaylist (ref List< int > bgmIds, Playlist mold = null) inline static
Definition at line 238 of file ModUtil.cs.
    {
        Playlist playlist = EClass.Sound.plBlank.Instantiate();
        if (bgmIds.Count == 0 && (bool)mold)
        {
            bgmIds = mold.ToInts();
            playlist.shuffle = mold.shuffle;
            playlist.minSwitchTime = mold.minSwitchTime;
            playlist.nextBGMOnSwitch = mold.nextBGMOnSwitch;
            playlist.ignoreLoop = mold.ignoreLoop;
            playlist.keepBGMifSamePlaylist = mold.keepBGMifSamePlaylist;
            playlist.name = mold.name;
        }
        foreach (int bgmId in bgmIds)
        {
            if (EClass.core.refs.dictBGM.TryGetValue(bgmId, out var value))
            {
                playlist.list.Add(new Playlist.Item
                {
                    data = value
                });
            }
        }
        return playlist;
    }
References EClass.core, CoreRef.dictBGM, Core.refs, and EClass.Sound.
Referenced by Zone.CreatePlaylist().
FindSoundPackage()
static ModPackage ModUtil.FindSoundPackage (string soundId) inline static
Definition at line 233 of file ModUtil.cs.
    {
        return ModManagerCore.Instance.packages.OfType<ModPackage>().LastOrDefault((ModPackage p) => p.sounds.Keys.Contains(soundId));
    }
FindSourceRowPackage()
static ModPackage ModUtil.FindSourceRowPackage (SourceData::BaseRow row) inline static
Definition at line 103 of file ModUtil.cs.
    {
        return ModManagerCore.Instance.packages.OfType<ModPackage>().LastOrDefault((ModPackage p) => p.sourceRows.Contains(row));
    }
Referenced by SourceCard.AddRow().
GetAudioType()
static AudioType ModUtil.GetAudioType (string extension) inline static
Definition at line 142 of file ModUtil.cs.
    {
        return extension.ToLowerInvariant().Trim() switch
        {
            ".acc" => AudioType.ACC,
            ".mp3" => AudioType.MPEG,
            ".ogg" => AudioType.OGGVORBIS,
            ".wav" => AudioType.WAV,
            _ => AudioType.UNKNOWN,
        };
    }
Referenced by LoadSoundData(), and ModPackage.ParseSound().
GetModPackage()
static ModPackage ModUtil.GetModPackage (string modId) inline static
Definition at line 66 of file ModUtil.cs.
    {
        return ModManagerCore.Instance.MappedPackages.GetValueOrDefault(modId) as ModPackage;
    }
GetSoundMeta()
static SerializableSoundData ModUtil.GetSoundMeta (string soundPath) inline static
Definition at line 108 of file ModUtil.cs.
    {
        string path = Path.ChangeExtension(soundPath, ".json");
        SerializableSoundData serializableSoundData;
        if (File.Exists(path))
        {
            try
            {
                serializableSoundData = IO.LoadFile<SerializableSoundData>(path);
                if (serializableSoundData.dataVersion == SerializableSoundData.SoundDataMetaVersion.V1)
                {
                    return serializableSoundData;
                }
            }
            catch
            {
            }
        }
        serializableSoundData = new SerializableSoundData();
        if (soundPath.NormalizePath().Contains("/Sound/BGM/"))
        {
            serializableSoundData.type = SoundData.Type.BGM;
            serializableSoundData.bgmDataOptional = new SerializableBGMData
            {
                parts = new List<BGMData.Part>
                {
                    new BGMData.Part()
                }
            };
        }
        IO.SaveFile(path, serializableSoundData);
        return serializableSoundData;
    }
Referenced by LoadSoundData().
ImportExcel()
static void ModUtil.ImportExcel (string pathToExcelFile, string sheetName, SourceData source) inline static
Definition at line 71 of file ModUtil.cs.
    {
        UnityEngine.Debug.Log("ImportExcel source:" + source?.ToString() + " Path:" + pathToExcelFile);
        using FileStream @is = File.Open(pathToExcelFile, FileMode.Open, FileAccess.Read, FileShare.ReadWrite);
        XSSFWorkbook xSSFWorkbook = new XSSFWorkbook((Stream)@is);
        for (int i = 0; i < xSSFWorkbook.NumberOfSheets; i++)
        {
            ISheet sheetAt = xSSFWorkbook.GetSheetAt(i);
            if (sheetAt.SheetName != sheetName)
            {
                continue;
            }
            UnityEngine.Debug.Log("Importing Sheet:" + sheetName);
            try
            {
                ExcelParser.path = pathToExcelFile;
                if (!source.ImportData(sheetAt, new FileInfo(pathToExcelFile).Name, overwrite: true))
                {
                    UnityEngine.Debug.LogError(ERROR.msg);
                    break;
                }
                UnityEngine.Debug.Log("Imported " + sheetAt.SheetName);
                source.Reset();
            }
            catch (Exception ex)
            {
                UnityEngine.Debug.LogError("[Error] Skipping import " + sheetAt.SheetName + " :" + ex.Message + "/" + ex.Source + "/" + ex.StackTrace);
                break;
            }
        }
    }
References SourceData< T, T2 >.ImportData(), ERROR.msg, and SourceData< T, T2 >.Reset().
LoadBookList()
static string[] ModUtil.LoadBookList () inline static
Definition at line 277 of file ModUtil.cs.
    {
        return (from d in PackageIterator.GetDirectories("Text").SelectMany((DirectoryInfo d) => d.GetDirectories())
            select d.FullName).ToArray();
    }
Referenced by OnModsActivated().
LoadSoundData() [1/2]
static SoundData ModUtil.LoadSoundData (FileInfo soundFile) inline static
Definition at line 163 of file ModUtil.cs.
    {
        string fileNameWithoutExtension = Path.GetFileNameWithoutExtension(soundFile.FullName);
        string fullName = soundFile.FullName;
        AudioType audioType = GetAudioType(soundFile.Extension);
        bool stream = fullName.NormalizePath().Contains("/BGM/") && audioType == AudioType.OGGVORBIS;
        using UnityWebRequest unityWebRequest = AudioClipStream.GetAudioClip("file://" + fullName, audioType, compressed: false, stream);
        unityWebRequest.SendWebRequest();
        Stopwatch stopwatch = Stopwatch.StartNew();
        while (!unityWebRequest.isDone && stopwatch.ElapsedMilliseconds < 5000)
        {
            Thread.Sleep(1);
        }
        if (unityWebRequest.result != UnityWebRequest.Result.Success)
        {
            UnityEngine.Debug.LogError("#sound '" + fileNameWithoutExtension + "' failed to load: " + unityWebRequest.error.IsEmpty("timeout"));
            return null;
        }
        AudioClip content = DownloadHandlerAudioClip.GetContent(unityWebRequest);
        int? num = content?.samples;
        if (!num.HasValue || num.GetValueOrDefault() <= 0)
        {
            UnityEngine.Debug.LogError($"#sound '{fileNameWithoutExtension}' sample is null: {audioType}");
            return null;
        }
        content.name = fileNameWithoutExtension;
        SoundData soundData = GetSoundMeta(fullName).ToSoundData();
        if (soundData is BGMData bGMData)
        {
            bGMData._name = Path.GetFileNameWithoutExtension(fullName);
            if (bGMData.song == null)
            {
                bGMData.song = new BGMData.SongData();
                bGMData.song.parts.Add(new BGMData.Part());
            }
        }
        soundData.clip = content;
        soundData.name = fileNameWithoutExtension;
        UnityEngine.Debug.Log($"#sound '{fileNameWithoutExtension}' loaded: {audioType}/{content.length}s");
        SoundManager.current.dictData[fileNameWithoutExtension] = soundData;
        return soundData;
    }
References $, GetAudioType(), and GetSoundMeta().
LoadSoundData() [2/2]
static SoundData ModUtil.LoadSoundData (string soundId) inline static
Definition at line 154 of file ModUtil.cs.
    {
        if (!MOD.sounds.TryGetValue(soundId, out var value) || !value.Exists)
        {
            return null;
        }
        return LoadSoundData(value);
    }
References LoadSoundData(), and MOD.sounds.
Referenced by LoadSoundData(), and OnModsActivated().
LoadTopicFiles()
static string[] ModUtil.LoadTopicFiles () inline static
Definition at line 283 of file ModUtil.cs.
    {
        return PackageIterator.GetFiles("Text/Help/_topics.txt").SelectMany((FileInfo f) => IO.LoadTextArray(f.FullName)).ToArray();
    }
Referenced by OnModsActivated().
LoadTypeFallback()
static void ModUtil.LoadTypeFallback () inline static
Definition at line 37 of file ModUtil.cs.
    {
        string text = "type_resolver.txt";
        string[] array = new string[0];
        if (File.Exists(CorePath.RootData + text))
        {
            array = IO.LoadTextArray(CorePath.RootData + text);
        }
        else
        {
            array = new string[2] { "TrueArena,ArenaWaveEvent,ZoneEvent", "Elin-GeneRecombinator,Elin_GeneRecombinator.IncubationSacrifice,Chara" };
            IO.SaveTextArray(CorePath.RootData + text, array);
        }
        string[] array2 = array;
        for (int i = 0; i < array2.Length; i++)
        {
            string[] array3 = array2[i].Split(',');
            if (array3.Length >= 2)
            {
                RegisterSerializedTypeFallback(array3[0], array3[1], array3[2]);
            }
        }
    }
References RegisterSerializedTypeFallback(), and CorePath.RootData.
Referenced by ModManager.ActivatePackages().
OnModsActivated()
static void ModUtil.OnModsActivated () inline static
Definition at line 23 of file ModUtil.cs.
    {
        SoundManager.current.soundLoaders.Add(LoadSoundData);
        UIBook.topicLoaders.Add(LoadTopicFiles);
        BookList.booklistLoaders.Add(LoadBookList);
        BaseModManager.PublishEvent("elin.mods.activated");
        BaseModManager.SubscribeEvent("elin.game.post_load", PostLoadCleanup);
    }
References BookList.booklistLoaders, LoadBookList(), LoadSoundData(), LoadTopicFiles(), PostLoadCleanup(), BaseModManager.PublishEvent(), BaseModManager.SubscribeEvent(), and UIBook.topicLoaders.
Referenced by ModManager.ActivatePackages().
PostLoadCleanup()
static void ModUtil.PostLoadCleanup (object context) inline static private
Definition at line 32 of file ModUtil.cs.
    {
        EClass.player.knownBGMs.RemoveWhere((int id) => !EClass.core.refs.dictBGM.ContainsKey(id));
    }
References EClass.core, CoreRef.dictBGM, Player.knownBGMs, EClass.player, and Core.refs.
Referenced by OnModsActivated().
RegisterSerializedTypeFallback()
static void ModUtil.RegisterSerializedTypeFallback (string nameAssembly, string nameType, string nameFallbackType) inline static
Definition at line 61 of file ModUtil.cs.
    {
        fallbackTypes[nameType] = nameFallbackType;
    }
References fallbackTypes.
Referenced by LoadTypeFallback().
SetBGMKnown()
static void ModUtil.SetBGMKnown (int bgmId, bool known = true) inline static
Definition at line 264 of file ModUtil.cs.
    {
        known &= EClass.core.refs.dictBGM.ContainsKey(bgmId);
        if (known)
        {
            EClass.player.knownBGMs.Add(bgmId);
        }
        else
        {
            EClass.player.knownBGMs.Remove(bgmId);
        }
    }
References EClass.core, CoreRef.dictBGM, Player.knownBGMs, EClass.player, and Core.refs.
Member Data Documentation
fallbackTypes
Dictionary<string, string> ModUtil.fallbackTypes = new Dictionary<string, string>() static
Definition at line 17 of file ModUtil.cs.
Referenced by GameSerializationBinder.BindToType(), GameIndex.Create(), GameIO.LoadGame(), and RegisterSerializedTypeFallback().
sourceImporter
SourceImporter ModUtil.sourceImporter = new SourceImporter(SourceMapping) static
Definition at line 15 of file ModUtil.cs.
Referenced by ModManager.ImportAllModSourceSheets().
Property Documentation
SourceMapping
IReadOnlyDictionary<string, SourceData> ModUtil.SourceMapping static get
Definition at line 19 of file ModUtil.cs.
The documentation for this class was generated from the following file:
Elin/ModUtil.cs