Elin Decompiled Documentation: AM_Dig Class Reference
AM_Dig Class Reference
Public Member Functions
override bool ForcedInstaComplete (TaskDig t)
override void OnUpdateCursor ()
void Activate (TaskDig.Mode _mode)
override void OnActivate ()
override void OnSelectStart (Point point)
override void OnSelectEnd (bool cancel)
override void OnCreateMold (bool processing=false)
Public Member Functions inherited from AM_Designation< TaskDig >
virtual bool CanInstaComplete (T t)
virtual bool ForcedInstaComplete (T t)
virtual HitResult HitResultOnDesignation (Point p)
override void OnActivate ()
void CreateNewMold (bool processing=false)
virtual void OnCreateMold (bool processing=false)
override HitResult HitTest (Point point, Point start)
override bool CanProcessTiles ()
override void OnBeforeProcessTiles ()
override void OnProcessTiles (Point point, int dir)
override void OnAfterProcessTiles (Point start, Point end)
override void OnRefreshSummary (Point point, HitResult result, HitSummary summary)
Public Attributes
TaskDig.Mode mode
int ramp = 3
Public Attributes inherited from AM_Designation< TaskDig >
TaskList< T > list
T mold
Properties
override int CostMoney [get]
override string id [get]
override bool AllowAutoClick [get]
Properties inherited from AM_Designation< TaskDig >
override string idSound [get]
override bool IsBuildMode [get]
Detailed Description
Definition at line 1 of file AM_Dig.cs.
Member Function Documentation
Activate()
void AM_Dig.Activate (TaskDig::Mode _mode) inline
Definition at line 27 of file AM_Dig.cs.
    {
        TaskDig.Mode mode = this.mode;
        this.mode = _mode;
        ramp = 3;
        Activate(toggle: false, mode != this.mode);
    }
References Activate(), mode, and ramp.
Referenced by Activate(), and HotItemActionMode.Execute().
ForcedInstaComplete()
override bool AM_Dig.ForcedInstaComplete (TaskDig t) inline
Definition at line 13 of file AM_Dig.cs.
    {
        if (t.pos.sourceFloor.tileType.CanInstaComplete)
        {
            return mode == TaskDig.Mode.RemoveFloor;
        }
        return false;
    }
References mode, TaskPoint.pos, and Point.sourceFloor.
OnActivate()
override void AM_Dig.OnActivate () inline
Definition at line 35 of file AM_Dig.cs.
    {
        list = base.Designations.dig;
        base.OnActivate();
    }
References AM_Designation< TaskDig >.list.
OnCreateMold()
override void AM_Dig.OnCreateMold (bool processing = false) inline virtual
Reimplemented from AM_Designation< TaskDig >.
Definition at line 51 of file AM_Dig.cs.
    {
        mold.mode = mode;
        mold.ramp = ramp;
    }
References mode, and ramp.
Referenced by ActionHint.Refresh().
OnSelectEnd()
override void AM_Dig.OnSelectEnd (bool cancel) inline
Definition at line 46 of file AM_Dig.cs.
    {
        EClass.ui.hud.hint.groupRadio.ToggleInteractable(enable: true);
    }
References ActionHint.groupRadio, HUD.hint, UI.hud, UISelectableGroup.ToggleInteractable(), and EClass.ui.
OnSelectStart()
override void AM_Dig.OnSelectStart (Point point) inline
Definition at line 41 of file AM_Dig.cs.
    {
        EClass.ui.hud.hint.groupRadio.ToggleInteractable(enable: false);
    }
References ActionHint.groupRadio, HUD.hint, UI.hud, UISelectableGroup.ToggleInteractable(), and EClass.ui.
OnUpdateCursor()
override void AM_Dig.OnUpdateCursor () inline
Definition at line 22 of file AM_Dig.cs.
    {
        SetCursorOnMap(CursorSystem.Dig);
    }
References CursorSystem.Dig.
Member Data Documentation
mode
TaskDig.Mode AM_Dig.mode
Definition at line 3 of file AM_Dig.cs.
Referenced by Activate(), ForcedInstaComplete(), and OnCreateMold().
ramp
int AM_Dig.ramp = 3
Definition at line 5 of file AM_Dig.cs.
Referenced by Activate(), and OnCreateMold().
Property Documentation
AllowAutoClick
override bool AM_Dig.AllowAutoClick get
Definition at line 11 of file AM_Dig.cs.
CostMoney
override int AM_Dig.CostMoney get
Definition at line 7 of file AM_Dig.cs.
id
override string AM_Dig.id get
Definition at line 9 of file AM_Dig.cs.
The documentation for this class was generated from the following file:
Elin/AM_Dig.cs