Elin Decompiled Documentation: Hotbar.Page Class Reference
Hotbar.Page Class Reference
Public Member Functions
void SetItem (Hotbar h, HotItem item, int index)
HotItem GetItem (int index)
Public Attributes
List< HotItem > items = new List<HotItem>()
int selected = -1
Properties
HotItem SelectedItem [get]
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Additional Inherited Members
Static Public Member Functions inherited from EClass
static int rnd (int a)
static int curve (int a, int start, int step, int rate=75)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Static Public Attributes inherited from EClass
static Core core
Detailed Description
Definition at line 13 of file Hotbar.cs.
Member Function Documentation
GetItem()
HotItem Hotbar.Page.GetItem (int index) inline
Definition at line 57 of file Hotbar.cs.
        {
            if (index >= items.Count)
            {
                return null;
            }
            return items[index];
        }
References Hotbar.Page.items.
SetItem()
void Hotbar.Page.SetItem (Hotbar h, HotItem item, int index) inline
Definition at line 33 of file Hotbar.cs.
        {
            if (index == -1)
            {
                for (int i = 0; i < items.Count; i++)
                {
                    if (items[i] == null)
                    {
                        index = i;
                        break;
                    }
                }
                if (index == -1)
                {
                    return;
                }
            }
            if (items[index] != null)
            {
                items[index].button = null;
            }
            items[index] = item;
        }
References item, and Hotbar.Page.items.
Referenced by Hotbar.SetItem().
Member Data Documentation
items
List<HotItem> Hotbar.Page.items = new List<HotItem>()
Definition at line 16 of file Hotbar.cs.
Referenced by Hotbar.Page.GetItem(), WidgetHotbar.GetItem(), WidgetHotbar.Rebuild(), Hotbar.Page.SetItem(), HotItem.TextHotkey(), and Hotbar.ValidatePage().
selected
int Hotbar.Page.selected = -1
Definition at line 19 of file Hotbar.cs.
Property Documentation
SelectedItem
HotItem Hotbar.Page.SelectedItem get
Definition at line 21 of file Hotbar.cs.
        {
            get
            {
                if (selected != -1)
                {
                    return items[selected];
                }
                return null;
            }
        }
The documentation for this class was generated from the following file:
Elin/Hotbar.cs