Elin Decompiled Documentation: UIHighlight Class Reference
UIHighlight Class Reference
Classes
class Highlight
Public Member Functions
void Add (Component target)
void Clear ()
void ApplySkin ()
void ApplySkin ()
Public Attributes
Image imageHighlight
Protected Attributes
List< Highlight > list = new List<Highlight>()
Private Member Functions
void Awake ()
Detailed Description
Definition at line 5 of file UIHighlight.cs.
Member Function Documentation
Add()
void UIHighlight.Add (Component target) inline
Definition at line 34 of file UIHighlight.cs.
    {
        Image image = Object.Instantiate(imageHighlight);
        image.transform.SetParent(target.transform, worldPositionStays: false);
        list.Add(new Highlight(image));
    }
References imageHighlight, and list.
ApplySkin()
void UIHighlight.ApplySkin () inline
Implements IUISkin.
Definition at line 50 of file UIHighlight.cs.
    {
    }
Referenced by Awake().
Awake()
void UIHighlight.Awake () inline private
Definition at line 29 of file UIHighlight.cs.
    {
        ApplySkin();
    }
References ApplySkin().
Clear()
void UIHighlight.Clear () inline
Definition at line 41 of file UIHighlight.cs.
    {
        for (int num = list.Count - 1; num >= 0; num--)
        {
            list[num].Kill();
        }
        list.Clear();
    }
References list.
Member Data Documentation
imageHighlight
Image UIHighlight.imageHighlight
Definition at line 25 of file UIHighlight.cs.
Referenced by Add().
list
List<Highlight> UIHighlight.list = new List<Highlight>() protected
Definition at line 27 of file UIHighlight.cs.
Referenced by Add(), and Clear().
The documentation for this class was generated from the following file:
Elin/Plugins.UI/UIHighlight.cs