Elin Decompiled Documentation: GenBounds Class Reference
GenBounds Class Reference
Public Member Functions
void SetFloor (BiomeProfile.Tile t, int x, int z)
void SetBlock (BiomeProfile.Tile t, int x, int z)
void SetFloor (int x, int z, int idMat, int idFloor, int direction=0)
void SetBlock (int x, int z, int idMat, int idBlock, int direction=0)
bool IsEmpty ()
List< Point > ListEmptyPoint ()
GenBounds GetBounds (int w, int h, bool ignoreBlock)
GenBounds GetBounds (Map map, Zone zone, int x, int y, int width, int height, int dw, int dh, bool ignoreBlock)
PartialMap TryAddMapPiece (MapPiece.Type type=MapPiece.Type.Any, float ruin=-1f, string tags=null, Action< PartialMap, GenBounds > onCreate=null)
Static Public Member Functions
static GenBounds Create (Zone z)
Static Public Member Functions inherited from EClass
static int rnd (int a)
static int curve (int a, int start, int step, int rate=75)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Public Attributes
Map map
Zone zone
int Size
int x
int y
int width
int height
int marginPartial
Func< Cell, bool > FuncCheckEmpty
Private Member Functions
bool IsSub (BiomeProfile.Tile g, int x, int y)
Additional Inherited Members
Static Public Attributes inherited from EClass
static Core core
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Detailed Description
Definition at line 5 of file GenBounds.cs.
Member Function Documentation
Create()
static GenBounds GenBounds.Create (Zone z) inline static
Definition at line 123 of file GenBounds.cs.
    {
        MapBounds bounds = z.map.bounds;
        return new GenBounds
        {
            zone = z,
            map = z.map,
            x = bounds.x,
            y = bounds.z,
            width = bounds.Width,
            height = bounds.Height
        };
    }
References Map.bounds, height, map, Zone.map, width, MapBounds.Width, x, MapBounds.x, y, MapBounds.z, and zone.
Referenced by ZoneEventHarvest.OnVisit(), and ZoneEventMusic.OnVisit().
GetBounds() [1/2]
GenBounds GenBounds.GetBounds (int w, int h, bool ignoreBlock) inline
Definition at line 137 of file GenBounds.cs.
    {
        return GetBounds(map, zone, x, y, width, height, w, h, ignoreBlock);
    }
References GetBounds(), height, map, width, x, y, and zone.
Referenced by GetBounds(), and TryAddMapPiece().
GetBounds() [2/2]
GenBounds GenBounds.GetBounds (Map map, Zone zone, int x, int y, int width, int height, int dw, int dh, bool ignoreBlock) inline
Definition at line 142 of file GenBounds.cs.
    {
        if (dw >= width || dh >= height)
        {
            return null;
        }
        GenBounds genBounds = new GenBounds
        {
            x = x,
            y = y,
            width = dw,
            height = dh,
            map = map,
            zone = zone,
            marginPartial = marginPartial,
            FuncCheckEmpty = FuncCheckEmpty
        };
        for (int i = 0; i < 200; i++)
        {
            if (ignoreBlock)
            {
                genBounds.x = EClass.rnd(width - dw) + x - dw / 2;
                genBounds.y = EClass.rnd(height - dh) + y - dh / 2;
                if (genBounds.x > 0 && genBounds.y > 0)
                {
                    return genBounds;
                }
            }
            else
            {
                genBounds.x = EClass.rnd(width - dw) + x;
                genBounds.y = EClass.rnd(height - dh) + y;
                if (genBounds.IsEmpty())
                {
                    return genBounds;
                }
            }
        }
        return null;
    }
References FuncCheckEmpty, height, IsEmpty(), map, marginPartial, EClass.rnd(), width, x, y, and zone.
IsEmpty()
bool GenBounds.IsEmpty () inline
Definition at line 66 of file GenBounds.cs.
    {
        for (int i = y - marginPartial; i < y + height + marginPartial; i++)
        {
            if (i < 0 || i >= EClass._map.Size)
            {
                return false;
            }
            for (int j = x - marginPartial; j < x + width + marginPartial; j++)
            {
                if (j < 0 || j >= EClass._map.Size)
                {
                    return false;
                }
                Cell cell = map.cells[j, i];
                if (FuncCheckEmpty != null && !FuncCheckEmpty(cell))
                {
                    return false;
                }
                if (cell.blocked || cell.HasBlock || cell.Installed != null)
                {
                    return false;
                }
            }
        }
        return true;
    }
References EClass._map, Algorithms.WeightCell.blocked, Map.cells, FuncCheckEmpty, Cell.HasBlock, height, Cell.Installed, map, marginPartial, MapBounds.Size, width, x, and y.
Referenced by GetBounds().
IsSub()
bool GenBounds.IsSub (BiomeProfile::Tile g, int x, int y) inline private
Definition at line 25 of file GenBounds.cs.
    {
        return g.subType switch
        {
            BiomeProfile.BaseTile.SubType.Rnd5 => EClass.rnd(5) == 0,
            BiomeProfile.BaseTile.SubType.Rnd10 => EClass.rnd(10) == 0,
            BiomeProfile.BaseTile.SubType.Rnd20 => EClass.rnd(20) == 0,
            BiomeProfile.BaseTile.SubType.Pattern => (x + y % 2) % 2 == 0,
            _ => false,
        };
    }
References EClass.rnd(), x, and y.
Referenced by SetBlock(), and SetFloor().
ListEmptyPoint()
List< Point > GenBounds.ListEmptyPoint () inline
Definition at line 94 of file GenBounds.cs.
    {
        List<Point> list = new List<Point>();
        for (int i = y; i < y + height; i++)
        {
            if (i < 0 || i >= EClass._map.Size)
            {
                continue;
            }
            for (int j = x; j < x + width; j++)
            {
                if (j < 0 || j >= EClass._map.Size)
                {
                    continue;
                }
                Cell cell = map.cells[j, i];
                if (!cell.blocked && !cell.HasBlock && (cell.Installed == null || !cell.Installed.trait.IsBlockPath))
                {
                    Point point = new Point(j, i);
                    if (!point.HasChara)
                    {
                        list.Add(point);
                    }
                }
            }
        }
        return list;
    }
References EClass._map, Algorithms.WeightCell.blocked, Map.cells, Cell.HasBlock, Point.HasChara, height, Cell.Installed, Trait.IsBlockPath, map, MapBounds.Size, Card.trait, width, x, and y.
Referenced by ZoneEventHarvest.OnVisit(), and ZoneEventMusic.OnVisit().
SetBlock() [1/2]
void GenBounds.SetBlock (BiomeProfile::Tile t, int x, int z) inline
Definition at line 43 of file GenBounds.cs.
    {
        bool flag = IsSub(t, x, z);
        SetBlock(x, z, flag ? t.matSub : t.mat, flag ? t.idSub : t.id);
    }
References IsSub(), SetBlock(), and x.
Referenced by MapGen.MakeNeighbor(), MapGen.MakeNeighbor_old(), MapGen.MakeRoad(), MapGen.OnGenerateTerrain(), MapGenDungen.OnGenerateTerrain(), SetBlock(), and MapGen.TryMakeRiver().
SetBlock() [2/2]
void GenBounds.SetBlock (int x, int z, int idMat, int idBlock, int direction = 0) inline
Definition at line 57 of file GenBounds.cs.
    {
        Cell cell = map.cells[x, z];
        cell._blockMat = (byte)idMat;
        cell._block = (byte)idBlock;
        cell.blockDir = direction;
        cell.effect = null;
    }
References Map.cells, map, and x.
SetFloor() [1/2]
void GenBounds.SetFloor (BiomeProfile::Tile t, int x, int z) inline
Definition at line 37 of file GenBounds.cs.
    {
        bool flag = IsSub(t, x, z);
        SetFloor(x, z, flag ? t.matSub : t.mat, flag ? t.idSub : t.id, EClass.rnd(EClass.rnd(8) + 1));
    }
References IsSub(), EClass.rnd(), SetFloor(), and x.
Referenced by MapGen.MakeNeighbor(), MapGen.MakeNeighbor_old(), MapGen.MakeRoad(), MapGen.OnGenerateTerrain(), MapGenDungen.OnGenerateTerrain(), MapGenRegion.OnGenerateTerrain(), SetFloor(), and MapGen.TryMakeRiver().
SetFloor() [2/2]
void GenBounds.SetFloor (int x, int z, int idMat, int idFloor, int direction = 0) inline
Definition at line 49 of file GenBounds.cs.
    {
        Cell cell = map.cells[x, z];
        cell._floorMat = (byte)idMat;
        cell._floor = (byte)idFloor;
        cell.floorDir = direction;
    }
References Map.cells, map, and x.
TryAddMapPiece()
PartialMap GenBounds.TryAddMapPiece (MapPiece::Type type = MapPiece::Type::Any, float ruin = -1f, string tags = null, Action< PartialMap, GenBounds > onCreate = null) inline
Definition at line 183 of file GenBounds.cs.
    {
        if (ruin == -1f)
        {
            ruin = zone.RuinChance;
        }
        PartialMap partialMap = MapPiece.Instance.GetMap(type, tags.IsEmpty(zone.biome.tags), ruin);
        if (partialMap == null)
        {
            Debug.Log("TryAddMap Piece: no map");
            return null;
        }
        bool flag = partialMap.dir == 1 || partialMap.dir == 3;
        GenBounds bounds = GetBounds(flag ? partialMap.h : partialMap.w, flag ? partialMap.w : partialMap.h, partialMap.ignoreBlock);
        if (bounds == null)
        {
            return null;
        }
        partialMap.Apply(new Point(bounds.x, bounds.y), PartialMap.ApplyMode.Apply);
        onCreate?.Invoke(partialMap, bounds);
        Debug.Log(partialMap.path);
        return partialMap;
    }
References PartialMap.Apply(), Zone.biome, GetBounds(), MapPiece.GetMap(), PartialMap.h, PartialMap.ignoreBlock, MapPiece.Instance, PartialMap.path, Zone.RuinChance, BiomeProfile.tags, PartialMap.w, x, y, and zone.
Referenced by Zone_CaveMonster.OnGenerateRooms(), ZoneEventHarvest.OnVisit(), ZoneEventMusic.OnVisit(), and GenRoom.Populate().
Member Data Documentation
FuncCheckEmpty
Func<Cell, bool> GenBounds.FuncCheckEmpty
Definition at line 23 of file GenBounds.cs.
Referenced by GetBounds(), and IsEmpty().
height
int GenBounds.height
Definition at line 19 of file GenBounds.cs.
Referenced by Create(), GetBounds(), GenRoom.Init(), IsEmpty(), ListEmptyPoint(), MapGenDungen.OnGenerateTerrain(), and GenRoom.Populate().
map
Map GenBounds.map
Definition at line 7 of file GenBounds.cs.
Referenced by Create(), BaseMapGen.Generate(), MapGen.GenerateTerrain(), GetBounds(), IsEmpty(), ListEmptyPoint(), MapGen.ModifyHeight(), MapGen.OnGenerateTerrain(), MapGenDungen.OnGenerateTerrain(), MapGenRegion.OnGenerateTerrain(), GenRoom.OnPopulate(), MapGen.Populate(), SetBlock(), SetFloor(), and BaseMapGen.SetSize().
marginPartial
int GenBounds.marginPartial
Definition at line 21 of file GenBounds.cs.
Referenced by GetBounds(), and IsEmpty().
Size
int GenBounds.Size
Definition at line 11 of file GenBounds.cs.
Referenced by MapGen.GenerateTerrain(), GenRoom.Init(), MapGen.MakeNeighbor(), MapGen.MakeNeighbor_old(), MapGen.MakeRoad(), MapGen.ModifyHeight(), MapGen.OnGenerateTerrain(), MapGenDungen.OnGenerateTerrain(), MapGenRegion.OnGenerateTerrain(), GenRoom.OnPopulate(), GenRoomMonsterHouse.OnPopulate(), MapGen.Populate(), and BaseMapGen.SetSize().
width
int GenBounds.width
Definition at line 17 of file GenBounds.cs.
Referenced by Create(), GetBounds(), GenRoom.Init(), IsEmpty(), ListEmptyPoint(), MapGenDungen.OnGenerateTerrain(), and GenRoom.Populate().
x
int GenBounds.x
Definition at line 13 of file GenBounds.cs.
Referenced by Create(), GetBounds(), GenRoom.Init(), IsEmpty(), IsSub(), ListEmptyPoint(), GenRoom.Populate(), SetBlock(), SetFloor(), and TryAddMapPiece().
y
int GenBounds.y
Definition at line 15 of file GenBounds.cs.
Referenced by Create(), GetBounds(), GenRoom.Init(), IsEmpty(), IsSub(), ListEmptyPoint(), GenRoom.Populate(), and TryAddMapPiece().
zone
Zone GenBounds.zone
Definition at line 9 of file GenBounds.cs.
Referenced by Create(), BaseMapGen.Generate(), MapGen.GenerateTerrain(), GetBounds(), MapGen.OnGenerateTerrain(), MapGenDungen.OnGenerateTerrain(), MapGenRegion.OnGenerateTerrain(), GenRoom.Populate(), GenRoom.SpawnMob(), and TryAddMapPiece().
The documentation for this class was generated from the following file:
Elin/GenBounds.cs