Elin Decompiled Documentation: GameUpdater Class Reference
GameUpdater Class Reference
Classes
class AreaUpdater
class CharaUpdater
class ConditionUpdater
class FastSurfaceUpdater
class FireUpdater
class LogicUpdater
class SensorUpdater
class SurfaceUpdater
class ThingUpdater
class Updater
Public Member Functions
void Reset ()
unsafe void Update100ms ()
void FixedUpdate ()
void Update ()
string GetText ()
Public Attributes
GameUpdater.AreaUpdater area
GameUpdater.SurfaceUpdater surface
GameUpdater.FastSurfaceUpdater surfaceFast
GameUpdater.FireUpdater fire
GameUpdater.CharaUpdater chara
GameUpdater.ConditionUpdater condition
GameUpdater.ThingUpdater thing
GameUpdater.SensorUpdater sensor
RecipeUpdater recipe = new RecipeUpdater()
GameUpdater.Updater[] all
Static Public Attributes
static float delta
Static Public Attributes inherited from EClass
static Core core
Private Attributes
float dateTimer
float counterTimer
int counter
float timerThunder
Additional Inherited Members
Static Public Member Functions inherited from EClass
static int rnd (int a)
static int curve (int a, int start, int step, int rate=75)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Detailed Description
Definition at line 6 of file GameUpdater.cs.
Member Function Documentation
FixedUpdate()
void GameUpdater.FixedUpdate () inline
Definition at line 85 of file GameUpdater.cs.
    {
        this.recipe.FixedUpdate();
        if (EClass.scene.paused)
        {
            return;
        }
        if (this.all == null)
        {
            this.all = new GameUpdater.Updater[]
            {
                this.area,
                this.surface,
                this.surfaceFast,
                this.fire,
                this.chara,
                this.condition,
                this.sensor,
                this.thing
            };
        }
        GameUpdater.delta = Core.delta;
        this.area.FixedUpdate();
        this.surface.FixedUpdate();
        this.surfaceFast.FixedUpdate();
        this.fire.FixedUpdate();
        this.chara.FixedUpdate();
        this.condition.FixedUpdate();
        this.sensor.FixedUpdate();
        this.thing.FixedUpdate();
    }
References all, area, chara, condition, delta, fire, FixedUpdate(), RecipeUpdater.FixedUpdate(), Scene.paused, recipe, EClass.scene, sensor, surface, surfaceFast, and thing.
Referenced by FixedUpdate(), Game.OnUpdate(), and CoreDebug.UpdateInput().
GetText()
string GameUpdater.GetText () inline
Definition at line 212 of file GameUpdater.cs.
    {
        if (this.all == null)
        {
            return "";
        }
        string text = "";
        foreach (GameUpdater.Updater updater in this.all)
        {
            text = string.Concat(new string[]
            {
                text,
                updater.GetType().Name,
                ": ",
                updater.updatesPerFrame.ToString(),
                " / frame     ",
                updater.maxCount.ToString(),
                " in ",
                updater.duration.ToString(),
                "sec \n"
            });
        }
        return text;
    }
References all, and text.
Reset()
void GameUpdater.Reset () inline
Definition at line 8 of file GameUpdater.cs.
    {
        this.area = new GameUpdater.AreaUpdater();
        this.surface = new GameUpdater.SurfaceUpdater();
        this.surfaceFast = new GameUpdater.FastSurfaceUpdater();
        this.fire = new GameUpdater.FireUpdater();
        this.chara = new GameUpdater.CharaUpdater();
        this.condition = new GameUpdater.ConditionUpdater();
        this.thing = new GameUpdater.ThingUpdater();
        this.sensor = new GameUpdater.SensorUpdater();
    }
Referenced by Scene.Init().
Update()
void GameUpdater.Update () inline
Definition at line 117 of file GameUpdater.cs.
    {
        if (EClass.game.activeZone == null)
        {
            return;
        }
        EClass._map.RefreshSunMap();
        if (EClass.debug.testLOS)
        {
            if (EClass._zone.IsRegion)
            {
                Zone zone = EClass.game.spatials.Find("palmia");
                PathProgress pathProgress = PathManager.Instance.RequestPathImmediate(new Point(zone.x - EClass.scene.elomap.minX, zone.y - EClass.scene.elomap.minY), EClass.pc.pos, EClass.pc, PathManager.MoveType.Default, -1, 0);
                if (pathProgress.HasPath)
                {
                    Debug.Log(pathProgress.nodes.Count);
                    foreach (PathFinderNode pathFinderNode in pathProgress.nodes)
                    {
                        Point point2 = new Point(pathFinderNode.X, pathFinderNode.Z);
                        EClass.screen.tileMap.passGuideBlock.Add(point2.PositionTopdown(), 20f, 0f);
                    }
                }
            }
            Point hit = Scene.HitPoint;
            if (hit.IsValid)
            {
                for (int i = 0; i < EClass._map.charas.Count; i++)
                {
                    Chara tg = EClass._map.charas[i];
                    if (Los.IsVisible(hit, tg.pos, null))
                    {
                        Los.IsVisible(hit, tg.pos, delegate(Point point, bool blocked)
{
                            EClass.screen.tileMap.passGuideFloor.Add(point, 20f, 0f);
                            if (Input.GetKey(KeyCode.LeftControl))
{
                                Debug.Log(tg.Name + ": Distance:" + hit.Distance(tg.pos).ToString());
                            }
                        });
                    }
                }
            }
        }
        if (EClass.debug.testLOS2)
        {
            Point hit = Scene.HitPoint;
            if (hit.IsValid)
            {
                EClass._map.ForeachSphere(hit.x, hit.z, 6f, delegate(Point p)
                {
                    if (p.IsValid && Los.IsVisible(hit, p, null))
                    {
                        EClass.screen.tileMap.passGuideFloor.Add(p, 20f, 0f);
                    }
                });
            }
        }
        if (EClass.scene.paused)
        {
            return;
        }
        GameUpdater.delta = Core.gameDelta;
        EClass._zone.events.Tick(GameUpdater.delta);
        this.dateTimer += GameUpdater.delta;
        if (this.dateTimer > EClass.setting.secsPerHour / 60f)
        {
            this.dateTimer = 0f;
            EClass.world.date.AdvanceMin(1);
        }
        this.counterTimer += GameUpdater.delta;
        if (this.counterTimer > 0.1f)
        {
            this.counterTimer = 0f;
            this.counter++;
            if (this.counter == 10)
            {
                this.counter = 0;
            }
            int num = this.counter;
            if (num == 1)
            {
                UIResourceTrack.Refresh();
                return;
            }
            if (num != 5)
            {
                return;
            }
            if (EClass.Sound.currentAmbience)
            {
                EClass.Sound.currentAmbience.TryEmit(EClass.world.date.IsDay, Point.shared.Set(EClass.pc.pos.x + EClass.rnd(5) - EClass.rnd(5), EClass.pc.pos.z).Clamp(false).Position(), 1f);
            }
        }
    }
References EClass._map, EClass._zone, Game.activeZone, MeshPass.Add(), GameDate.AdvanceMin(), Map.charas, Point.Clamp(), counter, counterTimer, World.date, dateTimer, EClass.debug, delta, Scene.elomap, Zone.events, SpatialManager.Find(), Map.ForeachSphere(), EClass.game, PathProgress.HasPath, Scene.HitPoint, PathManager.Instance, Date.IsDay, Spatial.IsRegion, Point.IsValid, Los.IsVisible(), EloMap.minX, EloMap.minY, PathProgress.nodes, BaseTileMap.passGuideBlock, BaseTileMap.passGuideFloor, Scene.paused, EClass.pc, Card.pos, Point.Position(), Point.PositionTopdown(), UIResourceTrack.Refresh(), Map.RefreshSunMap(), PathManager.RequestPathImmediate(), EClass.rnd(), EClass.scene, EClass.screen, GameSetting.secsPerHour, Point.Set(), EClass.setting, Point.shared, EClass.Sound, Game.spatials, CoreDebug.testLOS, CoreDebug.testLOS2, ZoneEventManager.Tick(), BaseGameScreen.tileMap, EClass.world, Algorithms.PathFinderNode.X, Point.x, Spatial.x, Spatial.y, Algorithms.PathFinderNode.Z, and Point.z.
Referenced by GameUpdater.ThingUpdater.FixedUpdate(), and Scene.OnUpdate().
Update100ms()
unsafe void GameUpdater.Update100ms () inline
Definition at line 20 of file GameUpdater.cs.
    {
        if (EClass.game.activeZone.IsPCFaction && EClass.Branch.resources.isDirty)
        {
            EClass.Branch.resources.Refresh();
        }
        bool flag = EClass.world.weather.CurrentCondition == Weather.Condition.RainHeavy;
        bool flag2;
        if (!EClass._map.config.indoor)
        {
            if (EClass.pc.IsInActiveZone)
            {
                Room room = EClass.pc.pos.cell.room;
                flag2 = (room != null && room.HasRoof);
            }
            else
            {
                flag2 = false;
            }
        }
        else
        {
            flag2 = true;
        }
        bool flag3 = flag2;
        Room room2 = EClass.pc.pos.cell.room;
        bool flag4 = room2 != null && room2.data.atrium;
        float mtpVolume = (EClass._zone.lv <= -2) ? 0f : ((flag3 && !flag4) ? 0.5f : 1f);
        if (EClass.world.weather.IsRaining && !EClass._map.IsIndoor)
        {
            for (int i = 0; i < EClass.setting.weather.splashCount * (flag ? 2 : 1); i++)
            {
                Point randomPoint = EClass.screen.GetRandomPoint();
                if (randomPoint.IsValid)
                {
                    Cell cell = randomPoint.cell;
                    if (!cell.HasRoof && cell._block == 0 && !randomPoint.IsSky)
                    {
                        if (cell.IsTopWaterAndNoSnow)
{
                            EClass.scene.psRainSplash.Emit(*randomPoint.PositionCenter(), Vector3.zero, Rand.Range(0.6f, 1.1f), 0.2f, Color.white);
                        }
                        else
{
                            EClass.scene.psRainSplashWater.Emit(*randomPoint.PositionCenter(), Vector3.zero, Rand.Range(0.6f, 1.1f), 0.2f, Color.white);
                        }
                    }
                }
            }
        }
        if (flag)
        {
            this.timerThunder += 0.1f;
            if (this.timerThunder > EClass.setting.weather.thunerInterval)
            {
                if (!EClass._map.IsIndoor)
                {
                    ScreenFlash.Play("storm" + (EClass.rnd(2) + 1).ToString(), (flag3 && !flag4) ? 0.3f : 1f);
                }
                EClass.Sound.Play("Ambience/Random/storm", mtpVolume);
                this.timerThunder = 0f - Rand.Range(0f, EClass.setting.weather.thunerInterval);
            }
        }
    }
References Cell._block, EClass._map, Game.activeZone, AreaData.atrium, EClass.Branch, Point.cell, Color, Map.config, BaseArea.data, EClass.game, BaseGameScreen.GetRandomPoint(), Cell.HasRoof, Room.HasRoof, MapConfig.indoor, HomeResourceManager.isDirty, Chara.IsInActiveZone, Map.IsIndoor, Zone.IsPCFaction, Weather.IsRaining, Point.IsSky, Cell.IsTopWaterAndNoSnow, Point.IsValid, EClass.pc, ScreenFlash.Play(), Card.pos, Point.PositionCenter(), Scene.psRainSplash, Scene.psRainSplashWater, HomeResourceManager.Refresh(), FactionBranch.resources, EClass.rnd(), Cell.room, EClass.scene, EClass.screen, EClass.setting, EClass.Sound, timerThunder, GameSetting.weather, World.weather, and EClass.world.
Member Data Documentation
all
GameUpdater.Updater [] GameUpdater.all
Definition at line 257 of file GameUpdater.cs.
Referenced by FixedUpdate(), and GetText().
area
GameUpdater.AreaUpdater GameUpdater.area
Definition at line 239 of file GameUpdater.cs.
Referenced by FixedUpdate().
chara
GameUpdater.CharaUpdater GameUpdater.chara
Definition at line 247 of file GameUpdater.cs.
Referenced by FixedUpdate(), GameUpdater.SensorUpdater.FixedUpdate(), GameUpdater.CharaUpdater.FixedUpdate(), and GameUpdater.ConditionUpdater.FixedUpdate().
condition
GameUpdater.ConditionUpdater GameUpdater.condition
Definition at line 249 of file GameUpdater.cs.
Referenced by FixedUpdate(), and GameUpdater.ConditionUpdater.FixedUpdate().
counter
int GameUpdater.counter private
Definition at line 263 of file GameUpdater.cs.
Referenced by Update().
counterTimer
float GameUpdater.counterTimer private
Definition at line 261 of file GameUpdater.cs.
Referenced by Update().
dateTimer
float GameUpdater.dateTimer private
Definition at line 259 of file GameUpdater.cs.
Referenced by Update().
delta
float GameUpdater.delta static
Definition at line 237 of file GameUpdater.cs.
Referenced by FixedUpdate(), GameUpdater.Updater.SetUpdatesPerFrame(), and Update().
fire
GameUpdater.FireUpdater GameUpdater.fire
Definition at line 245 of file GameUpdater.cs.
Referenced by FixedUpdate().
recipe
RecipeUpdater GameUpdater.recipe = new RecipeUpdater()
Definition at line 255 of file GameUpdater.cs.
Referenced by AM_Adv._OnUpdateInput(), FixedUpdate(), Scene.Init(), AM_Adv.OnBecomeNoGoal(), LayerCraftFloat.OnSwitchContent(), and LayerCraftFloat.RefreshCraft().
sensor
GameUpdater.SensorUpdater GameUpdater.sensor
Definition at line 253 of file GameUpdater.cs.
Referenced by FixedUpdate().
surface
GameUpdater.SurfaceUpdater GameUpdater.surface
Definition at line 241 of file GameUpdater.cs.
Referenced by FixedUpdate().
surfaceFast
GameUpdater.FastSurfaceUpdater GameUpdater.surfaceFast
Definition at line 243 of file GameUpdater.cs.
Referenced by FixedUpdate().
thing
GameUpdater.ThingUpdater GameUpdater.thing
Definition at line 251 of file GameUpdater.cs.
Referenced by FixedUpdate(), and GameUpdater.ThingUpdater.FixedUpdate().
timerThunder
float GameUpdater.timerThunder private
Definition at line 265 of file GameUpdater.cs.
Referenced by Update100ms().
The documentation for this class was generated from the following file:
Elin/GameUpdater.cs