Elin Decompiled Documentation: ModItemList< T > Class Template Reference
ModItemList< T > Class Template Reference
Public Member Functions
ModItemList (int _catLength=0)
string GetRandomID (string category=null)
string GetNextID (string currentId, int a, bool ignoreCategory=true)
int IndexOf (string id)
ModItem< T > GetItem (string id, bool returnNull=false)
T GetObject (string id, object option=null)
void Add (FileInfo fi, string path=null, string prefix="")
void Add (string id, FileInfo fi, string path=null)
Public Attributes
ResourceCache< T > cache = new ResourceCache<T>()
List< ModItem< T > > list = new List<ModItem<T>>()
Dictionary< string, ModItem< T > > dict = new Dictionary<string, ModItem<T>>()
int catLength
Detailed Description
Type Constraints
T : Object
Definition at line 5 of file ModItemList.cs.
Constructor & Destructor Documentation
ModItemList()
ModItemList< T >.ModItemList (int _catLength = 0) inline
Definition at line 15 of file ModItemList.cs.
    {
        catLength = _catLength;
    }
References ModItemList< T >.catLength.
Member Function Documentation
Add() [1/2]
void ModItemList< T >.Add (FileInfo fi, string path = null, string prefix = "") inline
Definition at line 85 of file ModItemList.cs.
    {
        Add(Path.GetFileNameWithoutExtension(prefix + ((fi != null) ? fi.Name : path)), fi, path);
    }
References ModItemList< T >.Add().
Referenced by ModItemList< T >.Add(), BaseModPackage.Parse(), and ModManager.ParseExtra().
Add() [2/2]
void ModItemList< T >.Add (string id, FileInfo fi, string path = null) inline
Definition at line 90 of file ModItemList.cs.
    {
        if (dict.ContainsKey(id))
        {
            dict[id].Set(fi, path);
            return;
        }
        list.Add(new ModItem<T>(fi, path, this, id));
        dict.Add(id, list[list.Count - 1]);
    }
References ModItemList< T >.dict, and ModItemList< T >.list.
GetItem()
ModItem< T > ModItemList< T >.GetItem (string id, bool returnNull = false) inline
Definition at line 61 of file ModItemList.cs.
    {
        ModItem<T> value = null;
        if (dict.TryGetValue(id, out value))
        {
            return value;
        }
        if (!returnNull)
        {
            return list[0];
        }
        return null;
    }
References ModItemList< T >.dict, and ModItemList< T >.list.
Referenced by ModItemList< T >.GetObject(), LayerNewspaper.RefreshNews(), WindowChara.RefreshStatic(), Portrait.SetChara(), and Portrait.SetPortrait().
GetNextID()
string ModItemList< T >.GetNextID (string currentId, int a, bool ignoreCategory = true) inline
Definition at line 35 of file ModItemList.cs.
    {
        int num = IndexOf(currentId) + a;
        if (num >= list.Count)
        {
            num = 0;
        }
        if (num < 0)
        {
            num = list.Count - 1;
        }
        return list[num].id;
    }
References ModItemList< T >.IndexOf(), and ModItemList< T >.list.
Referenced by WindowChara.SetPortraitBG(), and WindowChara.SetPortraitFrame().
GetObject()
T ModItemList< T >.GetObject (string id, object option = null) inline
Definition at line 75 of file ModItemList.cs.
    {
        ModItem<T> item = GetItem(id, returnNull: true);
        if (item != null)
        {
            return item.GetObject();
        }
        return null;
    }
References ModItemList< T >.GetItem(), and item.
Referenced by Portrait.SetPortrait().
GetRandomID()
string ModItemList< T >.GetRandomID (string category = null) inline
Definition at line 20 of file ModItemList.cs.
    {
        if (list.Count == 0)
        {
            return null;
        }
        ModItem<T> modItem;
        do
        {
            modItem = list[Rand.rnd(list.Count)];
        }
        while (category != null && !(modItem.category == category));
        return modItem.id;
    }
References ModItem< T >.category, ModItem< T >.id, ModItemList< T >.list, and Rand.rnd().
IndexOf()
int ModItemList< T >.IndexOf (string id) inline
Definition at line 49 of file ModItemList.cs.
    {
        for (int i = 0; i < list.Count; i++)
        {
            if (list[i].id == id)
            {
                return i;
            }
        }
        return -1;
    }
References ModItemList< T >.list.
Referenced by ModItemList< T >.GetNextID().
Member Data Documentation
cache
ResourceCache<T> ModItemList< T >.cache = new ResourceCache<T>()
Definition at line 7 of file ModItemList.cs.
catLength
int ModItemList< T >.catLength
Definition at line 13 of file ModItemList.cs.
Referenced by ModItemList< T >.ModItemList().
dict
Dictionary<string, ModItem<T> > ModItemList< T >.dict = new Dictionary<string, ModItem<T>>()
Definition at line 11 of file ModItemList.cs.
Referenced by ModItemList< T >.Add(), Portrait.Exists(), ModItemList< T >.GetItem(), and Person.Person().
list
List<ModItem<T> > ModItemList< T >.list = new List<ModItem<T>>()
Definition at line 9 of file ModItemList.cs.
Referenced by ModItemList< T >.Add(), ModItemList< T >.GetItem(), ModItemList< T >.GetNextID(), ModItemList< T >.GetRandomID(), ModItemList< T >.IndexOf(), Scene.InitPass(), and Portrait.ListPortraits().
The documentation for this class was generated from the following file:
Elin/Plugins.basecore/ModItemList.cs