Elin Decompiled Documentation: AM_Build Class Reference
AM_Build Class Reference
Public Member Functions
bool _IsRoofEditMode (Card c)
override bool IsRoofEditMode (Card c=null)
override bool IsFillMode ()
override int TopHeight (Point p)
override HitResult HitResultOnDesignation (Point p)
override MeshPass GetGuidePass (Point point)
override bool ForcedInstaComplete (TaskBuild t)
override void OnUpdateCursor ()
override void OnActivate ()
override void OnDeactivate ()
override void OnCancel ()
void StartBuild (Recipe r, Func< ButtonGrid > _button)
override void OnCreateMold (bool processing=false)
override HitResult HitTest (Point point, Point start)
void FixBridge (Point point, Recipe recipe)
unsafe override void OnRenderTile (Point point, HitResult result, int dir)
override void OnBeforeProcessTiles ()
override void OnProcessTiles (Point point, int dir)
override void OnFinishProcessTiles ()
override void RotateUnderMouse ()
override void InputWheel (int wheel)
void ModAltitude (int a)
void SetAltitude (int a)
Public Member Functions inherited from AM_Designation< TaskBuild >
virtual bool CanInstaComplete (T t)
virtual bool ForcedInstaComplete (T t)
virtual HitResult HitResultOnDesignation (Point p)
override void OnActivate ()
void CreateNewMold (bool processing=false)
virtual void OnCreateMold (bool processing=false)
override HitResult HitTest (Point point, Point start)
override bool CanProcessTiles ()
override void OnBeforeProcessTiles ()
override void OnProcessTiles (Point point, int dir)
override void OnAfterProcessTiles (Point start, Point end)
override void OnRefreshSummary (Point point, HitResult result, HitSummary summary)
Public Attributes
int bridgeHeight
int altitude
Recipe recipe
Recipe _recipe
Func< ButtonGrid > button
TraitHouseBoard houseBoard
Public Attributes inherited from AM_Designation< TaskBuild >
TaskList< T > list
T mold
Properties
override BuildMenu.Mode buildMenuMode [get]
override int CostMoney [get]
override bool IsBuildMode [get]
override string idSound [get]
override bool AllowAutoClick [get]
override bool AllowMiddleClickFunc [get]
override int SelectorHeight [get]
override BaseTileSelector.HitType hitType [get]
override BaseTileSelector.SelectType selectType [get]
override BaseTileSelector.BoxType boxType [get]
override int hitW [get]
override int hitH [get]
int MaxAltitude [get]
Properties inherited from AM_Designation< TaskBuild >
override string idSound [get]
override bool IsBuildMode [get]
Detailed Description
Definition at line 4 of file AM_Build.cs.
Member Function Documentation
_IsRoofEditMode()
bool AM_Build._IsRoofEditMode (Card c) inline
Definition at line 6 of file AM_Build.cs.
    {
        return Input.GetKey(KeyCode.LeftAlt) && (c == null || !c.trait.CanOnlyCarry);
    }
References Trait.CanOnlyCarry, and Card.trait.
Referenced by IsRoofEditMode(), and AM_MoveInstalled.IsRoofEditMode().
FixBridge()
void AM_Build.FixBridge (Point point, Recipe recipe) inline
Definition at line 277 of file AM_Build.cs.
    {
        this.bridgeHeight = -1;
        if (recipe.IsBridge)
        {
            this.bridgeHeight = (int)((byte)((point.cell.bridgeHeight == 0) ? ((int)point.cell.height + recipe.tileType.MinAltitude) : ((int)point.cell.bridgeHeight)));
        }
    }
References Cell.bridgeHeight, Point.cell, Recipe.IsBridge, TileType.MinAltitude, recipe, and Recipe.tileType.
Referenced by TaskBuild.OnProgressComplete(), and OnRenderTile().
ForcedInstaComplete()
override bool AM_Build.ForcedInstaComplete (TaskBuild t) inline
Definition at line 171 of file AM_Build.cs.
    {
        return this.recipe.tileType.CanInstaComplete;
    }
References TileType.CanInstaComplete, recipe, and Recipe.tileType.
GetGuidePass()
override MeshPass AM_Build.GetGuidePass (Point point) inline
Definition at line 162 of file AM_Build.cs.
    {
        if (!this.recipe.IsBlock)
        {
            return EClass.screen.guide.passGuideFloor;
        }
        return EClass.screen.guide.passGuideBlock;
    }
References BaseGameScreen.guide, Recipe.IsBlock, ScreenGuide.passGuideBlock, ScreenGuide.passGuideFloor, recipe, and EClass.screen.
HitResultOnDesignation()
override HitResult AM_Build.HitResultOnDesignation (Point p) inline virtual
Reimplemented from AM_Designation< TaskBuild >.
Definition at line 87 of file AM_Build.cs.
    {
        CellDetail detail = p.detail;
        if (((detail != null) ? detail.designation : null) is TaskBuild)
        {
            return HitResult.Warning;
        }
        return HitResult.Invalid;
    }
References CellDetail.designation, and Point.detail.
HitTest()
override HitResult AM_Build.HitTest (Point point, Point start) inline
Definition at line 224 of file AM_Build.cs.
    {
        if (start != null)
        {
            this.mold.bridgeHeight = (int)start.cell.bridgeHeight;
        }
        else
        {
            this.mold.bridgeHeight = (int)point.cell.bridgeHeight;
        }
        if (this.recipe == null)
        {
            return HitResult.Default;
        }
        if (this.IsRoofEditMode(null))
        {
            return HitResult.Valid;
        }
        if (this.IsFillMode())
        {
            Cell cell = point.cell;
            if (this.recipe.IsBridge)
            {
                if (cell._bridge != start.cell._bridge)
                {
                    return HitResult.NoTarget;
                }
                return HitResult.Valid;
            }
            else if (this.recipe.IsFloor)
            {
                if (cell._floor != start.cell._floor)
                {
                    return HitResult.NoTarget;
                }
                return HitResult.Valid;
            }
            else if (this.recipe.IsBlock)
            {
                if (cell._block != start.cell._block)
                {
                    return HitResult.NoTarget;
                }
                return HitResult.Valid;
            }
        }
        if (this.recipe.IsBridge && this.recipe.tileType.SelectType == BaseTileSelector.SelectType.Multiple && !point.Equals(start) && (int)point.cell.height > this.bridgeHeight + this.altitude)
        {
            return HitResult.Invalid;
        }
        return base.HitTest(point, start);
    }
References Cell._block, Cell._bridge, Cell._floor, Cell.bridgeHeight, Point.cell, Point.Equals(), Cell.height, Recipe.IsBlock, Recipe.IsBridge, IsFillMode(), Recipe.IsFloor, IsRoofEditMode(), and recipe.
InputWheel()
override void AM_Build.InputWheel (int wheel) inline
Definition at line 415 of file AM_Build.cs.
    {
        if (EInput.isAltDown || EInput.isCtrlDown)
        {
            return;
        }
        if (this.recipe.MaxAltitude > 0)
        {
            this.ModAltitude(wheel);
            EClass.screen.tileSelector.RefreshMouseInfo(true);
            return;
        }
        base.InputWheel(wheel);
    }
References Recipe.MaxAltitude, ModAltitude(), recipe, BaseTileSelector.RefreshMouseInfo(), EClass.screen, and BaseGameScreen.tileSelector.
IsFillMode()
override bool AM_Build.IsFillMode () inline
Definition at line 17 of file AM_Build.cs.
    {
        return !this.recipe.IsThing && Input.GetKey(KeyCode.LeftControl) && EClass.debug.godBuild;
    }
References EClass.debug, and CoreDebug.godBuild.
Referenced by HitTest(), and TaskBuild.OnProgressComplete().
IsRoofEditMode()
override bool AM_Build.IsRoofEditMode (Card c = null) inline
Definition at line 11 of file AM_Build.cs.
    {
        Recipe recipe = this.recipe;
        return this._IsRoofEditMode((recipe != null) ? recipe.Mold : null);
    }
References _IsRoofEditMode(), Recipe.Mold, and recipe.
Referenced by HitTest().
ModAltitude()
void AM_Build.ModAltitude (int a) inline
Definition at line 430 of file AM_Build.cs.
    {
        this.altitude += a;
        if (this.altitude < (this.recipe.IsBridge ? -10 : 0))
        {
            this.altitude = this.MaxAltitude;
        }
        if (this.altitude > this.MaxAltitude)
        {
            this.altitude = (this.recipe.IsBridge ? -10 : 0);
        }
        this.SetAltitude(this.altitude);
    }
References altitude, Recipe.IsBridge, MaxAltitude, recipe, and SetAltitude().
Referenced by AM_Adv._OnUpdateInput(), InputWheel(), and UIPlaceHelper.Refresh().
OnActivate()
override void AM_Build.OnActivate () inline
Definition at line 181 of file AM_Build.cs.
    {
        this.list = base.Designations.build;
        base.OnActivate();
    }
OnBeforeProcessTiles()
override void AM_Build.OnBeforeProcessTiles () inline
Definition at line 325 of file AM_Build.cs.
    {
        this._recipe = this.recipe;
        this._recipe._dir = this.recipe._dir;
        this.mold.dir = this.recipe._dir;
        base.OnBeforeProcessTiles();
    }
References Recipe._dir, and recipe.
OnCancel()
override void AM_Build.OnCancel () inline
Definition at line 198 of file AM_Build.cs.
    {
        ActionMode.Inspect.Activate(true, false);
    }
References AM_MoveInstalled.Activate(), and ActionMode.Inspect.
OnCreateMold()
override void AM_Build.OnCreateMold (bool processing = false) inline virtual
Reimplemented from AM_Designation< TaskBuild >.
Definition at line 218 of file AM_Build.cs.
    {
        this.mold.recipe = (processing ? this._recipe : this.recipe);
        this.SetAltitude(this.altitude);
    }
References altitude, recipe, and SetAltitude().
OnDeactivate()
override void AM_Build.OnDeactivate () inline
Definition at line 187 of file AM_Build.cs.
    {
        base.Summary.SetRecipe(null);
        this.recipe = (this.mold.recipe = null);
        this.houseBoard = null;
        if (BuildMenu.Instance)
        {
            BuildMenu.Instance.Unselect();
        }
    }
References BuildMenu.Instance, and BuildMenu.Unselect().
OnFinishProcessTiles()
override void AM_Build.OnFinishProcessTiles () inline
Definition at line 361 of file AM_Build.cs.
    {
        base.OnFinishProcessTiles();
        ButtonGrid buttonGrid = this.button();
        if (this.recipe.UseStock)
        {
            Thing thing = this.recipe.ingredients[0].thing;
            if (thing == null || thing.isDestroyed || thing.ExistsOnMap || thing.Num <= 0)
            {
                ActionMode.ignoreSound = true;
                if (buttonGrid)
                {
                    buttonGrid.selected = false;
                    buttonGrid.DoNormalTransition(true);
                }
                BuildMenu.Instance.Unselect();
                BuildMenu.Instance.RefreshCategory(EClass.player.pref.lastBuildCategory);
                ActionMode.Inspect.Activate(true, false);
                BuildMenu.Instance.Unselect();
                return;
            }
        }
        if (buttonGrid)
        {
            buttonGrid.SetRecipe();
        }
        if (this.recipe.IsBridge)
        {
            this.SetAltitude(0);
        }
    }
References AM_MoveInstalled.Activate(), button, Card.ExistsOnMap, Recipe.ingredients, ActionMode.Inspect, BuildMenu.Instance, Recipe.IsBridge, Card.isDestroyed, Card.Num, EClass.player, Player.pref, recipe, BuildMenu.RefreshCategory(), SetAltitude(), ButtonGrid.SetRecipe(), BuildMenu.Unselect(), and Recipe.UseStock.
OnProcessTiles()
override void AM_Build.OnProcessTiles (Point point, int dir) inline
Definition at line 333 of file AM_Build.cs.
    {
        if (dir != -1)
        {
            this.mold.dir = dir;
        }
        else
        {
            this.mold.dir = this.recipe._dir;
        }
        if (point.HasDesignation)
        {
            TaskBuild taskBuild = point.detail.designation as TaskBuild;
            if (taskBuild != null && this.recipe.IsWallOrFence && taskBuild.recipe.IsWallOrFence && taskBuild.dir != dir)
            {
                dir = (this.mold.dir = 2);
            }
            CellDetail detail = point.detail;
            if (detail != null)
            {
                detail.designation.Destroy();
            }
        }
        this.mold.bridgeHeight = this.bridgeHeight;
        this.SetAltitude(this.altitude);
        base.OnProcessTiles(point, dir);
    }
References Recipe._dir, altitude, bridgeHeight, CellDetail.designation, Task.Destroy(), Point.detail, TaskBuild.dir, Point.HasDesignation, Recipe.IsWallOrFence, recipe, TaskBuild.recipe, and SetAltitude().
OnRenderTile()
unsafe override void AM_Build.OnRenderTile (Point point, HitResult result, int dir) inline
Definition at line 286 of file AM_Build.cs.
    {
        if (this.recipe == null)
        {
            return;
        }
        if (this.recipe is RecipeBridgePillar)
        {
            base.OnRenderTile(point, result, dir);
            return;
        }
        if (EClass.screen.tileSelector.start == null)
        {
            this.FixBridge(point, this.recipe);
        }
        if (this.recipe.IsFloorOrBridge && !this.recipe.IsBridge && point.cell.bridgeHeight != 0)
        {
            base.OnRenderTileFloor(point, result);
            return;
        }
        if (result != HitResult.Valid && result != HitResult.Warning)
        {
            base.OnRenderTile(point, result, dir);
            return;
        }
        if (this.bridgeHeight != -1)
        {
            Vector3 vector = *point.Position();
            EClass.screen.guide.passGuideFloor.Add(vector.x, vector.y, vector.z - 0.01f, (float)result, 0f);
        }
        int desiredDir = this.recipe.tileType.GetDesiredDir(point, this.recipe._dir);
        if (desiredDir != -1)
        {
            dir = (this.recipe._dir = desiredDir);
        }
        bool main = !base.tileSelector.multisize || (base.tileSelector.firstInMulti && base.Summary.count == base.Summary.countValid);
        this.recipe.OnRenderMarker(point, false, result, main, dir, this.bridgeHeight + ((this.recipe.tileType.AltitudeAsDir && !this.IsRoofEditMode(null)) ? 0 : this.altitude));
    }
References Recipe._dir, MeshPass.Add(), altitude, TileType.AltitudeAsDir, bridgeHeight, Cell.bridgeHeight, Point.cell, FixBridge(), TileType.GetDesiredDir(), BaseGameScreen.guide, Recipe.IsFloorOrBridge, Recipe.OnRenderMarker(), ScreenGuide.passGuideFloor, Point.Position(), recipe, EClass.screen, BaseTileSelector.start, BaseGameScreen.tileSelector, and Recipe.tileType.
Referenced by HotItemHeld.OnRenderTile().
OnUpdateCursor()
override void AM_Build.OnUpdateCursor () inline
Definition at line 176 of file AM_Build.cs.
    {
        base.SetCursorOnMap(CursorSystem.Build);
    }
RotateUnderMouse()
override void AM_Build.RotateUnderMouse () inline
Definition at line 393 of file AM_Build.cs.
    {
        if (this.recipe != null && this.recipe.CanRotate)
        {
            SE.Rotate();
            this.recipe.Rotate();
            return;
        }
    }
References Recipe.CanRotate, recipe, and Recipe.Rotate().
SetAltitude()
void AM_Build.SetAltitude (int a) inline
Definition at line 444 of file AM_Build.cs.
    {
        this.mold.altitude = a;
        this.altitude = a;
        this.recipe.OnChangeAltitude(a);
        if (this.recipe.tileType.AltitudeAsDir && !this.IsRoofEditMode(null))
        {
            this.mold.dir = (this.recipe._dir = this.altitude);
        }
    }
References altitude, TileType.AltitudeAsDir, Recipe.OnChangeAltitude(), recipe, and Recipe.tileType.
Referenced by ModAltitude(), OnCreateMold(), OnFinishProcessTiles(), OnProcessTiles(), and StartBuild().
StartBuild()
void AM_Build.StartBuild (Recipe r, Func< ButtonGrid > _button) inline
Definition at line 203 of file AM_Build.cs.
    {
        this.recipe = r;
        this.button = _button;
        if (!base.IsActive)
        {
            base.Activate(true, false);
        }
        base.CreateNewMold(false);
        this.bridgeHeight = -1;
        this.SetAltitude(0);
        base.Summary.SetRecipe(r);
        EClass.ui.hud.hint.Refresh();
    }
References SetAltitude(), and EClass.ui.
Referenced by BuildMenu.RefreshCategory().
TopHeight()
override int AM_Build.TopHeight (Point p) inline
Definition at line 82 of file AM_Build.cs.
    {
        return this.bridgeHeight + (this.recipe.tileType.AltitudeAsDir ? 0 : this.altitude);
    }
References altitude.
Member Data Documentation
_recipe
Recipe AM_Build._recipe
Definition at line 461 of file AM_Build.cs.
altitude
int AM_Build.altitude
Definition at line 457 of file AM_Build.cs.
Referenced by RecipeCard.CreateMold(), ModAltitude(), OnCreateMold(), OnProcessTiles(), OnRenderTile(), UIPlaceHelper.Refresh(), SetAltitude(), and TopHeight().
bridgeHeight
int AM_Build.bridgeHeight
Definition at line 455 of file AM_Build.cs.
Referenced by OnProcessTiles(), TaskBuild.OnProgressComplete(), and OnRenderTile().
button
Func<ButtonGrid> AM_Build.button
Definition at line 463 of file AM_Build.cs.
Referenced by OnFinishProcessTiles().
houseBoard
TraitHouseBoard AM_Build.houseBoard
Definition at line 465 of file AM_Build.cs.
Referenced by RecipeCard.Build().
recipe
Recipe AM_Build.recipe
Definition at line 459 of file AM_Build.cs.
Referenced by FixBridge(), ForcedInstaComplete(), GetGuidePass(), ActionMode.GetHintText(), HitTest(), InputWheel(), IsRoofEditMode(), ModAltitude(), OnBeforeProcessTiles(), OnCreateMold(), OnFinishProcessTiles(), OnProcessTiles(), OnRenderTile(), RotateUnderMouse(), and SetAltitude().
Property Documentation
AllowAutoClick
override bool AM_Build.AllowAutoClick get
Definition at line 58 of file AM_Build.cs.
    {
        get
        {
            return this.recipe != null && !(this.recipe is RecipeCard);
        }
    }
AllowMiddleClickFunc
override bool AM_Build.AllowMiddleClickFunc get
Definition at line 66 of file AM_Build.cs.
    {
        get
        {
            return false;
        }
    }
boxType
override BaseTileSelector.BoxType AM_Build.boxType get
Definition at line 123 of file AM_Build.cs.
    {
        get
        {
            Recipe recipe = this.recipe;
            if (recipe == null)
            {
                return BaseTileSelector.BoxType.Box;
            }
            return recipe.GetBoxType();
        }
    }
buildMenuMode
override BuildMenu.Mode AM_Build.buildMenuMode get
Definition at line 22 of file AM_Build.cs.
    {
        get
        {
            return BuildMenu.Mode.Build;
        }
    }
CostMoney
override int AM_Build.CostMoney get
Definition at line 30 of file AM_Build.cs.
    {
        get
        {
            if (this.recipe == null || this.recipe.UseStock)
            {
                return 0;
            }
            return 10;
        }
    }
hitH
override int AM_Build.hitH get
Definition at line 149 of file AM_Build.cs.
    {
        get
        {
            Recipe recipe = this.recipe;
            if (recipe == null)
            {
                return 1;
            }
            return recipe.H;
        }
    }
hitType
override BaseTileSelector.HitType AM_Build.hitType get
Definition at line 97 of file AM_Build.cs.
    {
        get
        {
            Recipe recipe = this.recipe;
            if (recipe == null)
            {
                return BaseTileSelector.HitType.None;
            }
            return recipe.tileType.HitType;
        }
    }
hitW
override int AM_Build.hitW get
Definition at line 136 of file AM_Build.cs.
    {
        get
        {
            Recipe recipe = this.recipe;
            if (recipe == null)
            {
                return 1;
            }
            return recipe.W;
        }
    }
idSound
override string AM_Build.idSound get
Definition at line 50 of file AM_Build.cs.
    {
        get
        {
            return null;
        }
    }
IsBuildMode
override bool AM_Build.IsBuildMode get
Definition at line 42 of file AM_Build.cs.
    {
        get
        {
            return true;
        }
    }
MaxAltitude
int AM_Build.MaxAltitude get
Definition at line 403 of file AM_Build.cs.
    {
        get
        {
            if (!this.IsRoofEditMode(null) || !(this.recipe.renderRow is SourceBlock.Row))
            {
                return this.recipe.MaxAltitude;
            }
            return 63;
        }
    }
Referenced by ActionMode.GetHintText(), and ModAltitude().
SelectorHeight
override int AM_Build.SelectorHeight get
Definition at line 74 of file AM_Build.cs.
    {
        get
        {
            return this.bridgeHeight;
        }
    }
selectType
override BaseTileSelector.SelectType AM_Build.selectType get
Definition at line 110 of file AM_Build.cs.
    {
        get
        {
            Recipe recipe = this.recipe;
            if (recipe == null)
            {
                return BaseTileSelector.SelectType.Single;
            }
            return recipe.tileType.SelectType;
        }
    }
The documentation for this class was generated from the following file:
Elin/AM_Build.cs