Elin Decompiled Documentation: AI_Shear Class Reference
AI_Shear Class Reference
Public Member Functions
override bool ShouldAllyAttack (Chara tg)
override string GetText (string str="")
override bool IsValidTC (Card c)
override bool Perform ()
override IEnumerable< Status > Run ()
Public Member Functions inherited from AI_TargetCard
override bool CanProgress ()
override IEnumerable< Status > Run ()
Public Member Functions inherited from AIAct
override string ToString ()
override MultiSprite GetStateIcon ()
virtual bool ShouldAllyAttack (Chara tg)
virtual Point GetDestination ()
AIProgress GetProgress ()
string GetCurrentActionText ()
override bool IsToolValid ()
virtual void OnStart ()
void SetOwner (Chara c)
virtual void OnSetOwner ()
void SetChild (AIAct seq, Func< Status > _onChildFail=null)
void Start ()
override bool Perform ()
Status Restart ()
Status Success (Action action=null)
virtual void OnSuccess ()
bool TryCancel (Card c)
virtual Status Cancel ()
virtual void OnCancel ()
virtual void OnCancelOrSuccess ()
virtual bool CanManualCancel ()
Status KeepRunning ()
void Reset ()
virtual void OnReset ()
Status Tick ()
virtual IEnumerable< Status > Run ()
Status TickChild ()
Status Do (AIAct _seq, Func< Status > _onChildFail=null)
Status DoGotoInteraction (Point pos, Func< Status > _onChildFail=null)
Status DoGoto (Point pos, int dist=0, bool ignoreConnection=false, Func< Status > _onChildFail=null)
Status DoGoto (Card card, Func< Status > _onChildFail=null)
Status DoGoto (Card card, int dist, Func< Status > _onChildFail=null)
Status DoGotoSpot (Card card, Func< Status > _onChildFail=null)
Status DoGoto< T > (Func< Status > _onChildFail=null)
Status DoGotoSpot< T > (Func< Status > _onChildFail=null, bool ignoreAccessType=false)
Status DoGrab (Card card, int num=-1, bool pickHeld=false, Func< Status > _onChildFail=null)
Status DoGrab< T > ()
Status DoProgress ()
Status DoIdle (int repeat=3)
Status DoWait (int count=1)
virtual AIProgress CreateProgress ()
virtual void OnCreateProgress (Progress_Custom p)
virtual bool CanProgress ()
virtual void OnBeforeProgress ()
virtual void OnProgress ()
virtual void OnProgressComplete ()
void SimulateZone (int days)
virtual void OnSimulateZone (int days)
virtual void OnSimulatePosition ()
Public Member Functions inherited from Act
virtual CursorInfo GetCursorIcon (Card c)
virtual MultiSprite GetStateIcon ()
override Sprite GetSprite ()
virtual bool ShowMouseHint (Card c)
virtual bool IsValidTC (Card c)
virtual string GetHintText (string str="")
virtual string GetText (string str="")
virtual string GetTextSmall (Card c)
bool IsTargetHostileParty ()
virtual Color GetActPlanColor ()
virtual bool Perform ()
virtual bool CanPerform ()
bool Perform (Chara _cc, Card _tc=null, Point _tp=null)
bool CanPerform (Chara _cc, Card _tc=null, Point _tp=null)
virtual bool IsToolValid ()
new void SetImage (Image image)
virtual void OnMarkMapHighlights ()
virtual bool ShouldMapHighlight (Point p)
Public Member Functions inherited from Element
virtual SourceElement.Row GetSource ()
virtual int GetSourcePotential (int v)
virtual Sprite GetSprite ()
int GetMaterialSourceValue (Thing t, int v)
virtual long GetSourceValue (long v, int lv, SourceValueType type)
virtual Sprite GetIcon (string suffix="")
bool IsActive (Card c)
int SortVal (bool charaSheet=false)
virtual bool CanLink (ElementContainer owner)
bool HasTag (string tag)
void SetImage (Image i)
virtual string GetDetail ()
bool IsFactionElement (Chara c)
Element GetParent (Card c)
void WriteNote (UINote n, ElementContainer owner=null, Action< UINote > onWriteNote=null)
void WriteNoteWithRef (UINote n, ElementContainer owner, Action< UINote > onWriteNote, Element refEle)
void _WriteNote (UINote n, Chara c, Act act)
void AddHeaderAbility (UINote n)
void _WriteNote (UINote n, ElementContainer owner, Action< UINote > onWriteNote, bool isRef, bool addHeader=true)
void AddEncNote (UINote n, Card Card, ElementContainer.NoteMode mode=ElementContainer.NoteMode.Default, Func< Element, string, string > funcText=null, Action< UINote, Element > onAddNote=null)
virtual void OnWriteNote (UINote n, ElementContainer owner)
virtual void OnChangeValue ()
void CheckLevelBonus (ElementContainer owner, UINote n=null)
int GetSortVal (UIList.SortMode m)
virtual Act.Cost GetCost (Chara c)
virtual int GetPower (Card c)
virtual void SetTextValue (UIText text)
virtual bool IsPurchaseFeatReqMet (ElementContainer owner, int lv=-1)
virtual void WritePurchaseReq (UINote n, int lv=1)
Static Public Member Functions
static int GetFurLv (Chara c)
static Thing GetFur (Chara c, int mod=100)
Static Public Member Functions inherited from Act
static void SetReference (Chara _cc, Card _tc=null, Point _tp=null)
static void SetTool (Thing t)
Static Public Member Functions inherited from Element
static string GetName (string alias)
static SourceElement.Row Get (int id)
static Dictionary< int, int > GetElementMap (int[] list)
static Dictionary< int, int > GetElementMap (int[] list, Dictionary< int, int > map)
static SourceElement.Row GetRandomElement (int lv=1, bool useWeight=true)
static Element Create (int id, int v=0)
static Element Create (string id, int v=1)
static int GetId (string alias)
static int GetResistLv (int v)
static int GetResistDamage (int dmg, int v, int power=0)
Static Public Member Functions inherited from EClass
static int rndSeed (int a, int seed)
static int rnd (long a)
static int rnd (int a)
static int curve (long _a, int start, int step, int rate=75)
static int sqrt (int a)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Additional Inherited Members
Public Types inherited from AIAct
enum Status { Running , Fail , Success }
Public Types inherited from Act
enum CostType { None , MP , SP }
Public Attributes inherited from AI_TargetCard
Card target
Public Attributes inherited from AIAct
new Chara owner
Status status
IEnumerator< Status > Enumerator
AIAct child
AIAct parent
byte restartCount
Func< Status > onChildFail
Func< bool > isFail
Public Attributes inherited from Element
SourceElement.Row _source
int id
int vBase
int vExp
int vPotential
int vTempPotential
int vLink
int vSource
int vSourcePotential
ElementContainer owner
Static Public Attributes inherited from Act
static Chara CC
static Card TC
static Point TP = new Point()
static Thing TOOL
static int powerMod = 100
static bool forcePt
static Act CurrentAct
Static Public Attributes inherited from Element
const int Div = 5
static Element Void = new Element()
static int[] List_MainAttributes = new int[9] { 70, 72, 71, 77, 74, 75, 76, 73, 79 }
static int[] List_MainAttributesMajor = new int[8] { 70, 72, 71, 77, 74, 75, 76, 73 }
static int[] List_Body = new int[4] { 70, 72, 71, 77 }
static int[] List_Mind = new int[4] { 74, 75, 76, 73 }
static List< SourceElement.Row > ListElements = new List<SourceElement.Row>()
static List< SourceElement.Row > ListAttackElements = new List<SourceElement.Row>()
Static Public Attributes inherited from EClass
static Core core
Properties inherited from AI_TargetCard
virtual bool GotoTarget [get]
override bool HasProgress [get]
virtual bool CanTargetInventory [get]
Properties inherited from AIAct
virtual bool IsRunning [get]
bool IsChildRunning [get]
bool IsMoveAI [get]
virtual int MaxRestart [get]
virtual new string Name [get]
virtual MultiSprite stateIcon [get]
virtual Sprite actionIcon [get]
virtual bool IsNoGoal [get]
virtual bool IsAutoTurn [get]
virtual bool IsIdle [get]
virtual bool CancelOnAggro [get]
virtual bool PushChara [get]
virtual int MaxProgress [get]
virtual bool ShowProgress [get]
virtual bool UseTurbo [get]
virtual int CurrentProgress [get]
virtual bool ShowCursor [get]
virtual bool CancelWhenDamaged [get]
virtual bool CancelWhenMoved [get]
virtual bool InformCancel [get]
virtual Thing RenderThing [get]
AIAct Current [get]
override bool IsAct [get]
override bool ShowPotential [get]
override bool UsePotential [get]
override bool ShowRelativeAttribute [get]
virtual bool HasProgress [get]
Properties inherited from Act
override bool ShowPotential [get]
override bool UsePotential [get]
override bool ShowRelativeAttribute [get]
virtual CursorInfo CursorIcon [get]
virtual string ID [get]
virtual bool IsAct [get]
virtual bool WillEndTurn [get]
virtual bool CloseLayers [get]
virtual int LeftHand [get]
virtual int RightHand [get]
virtual int ElementPowerMod [get]
virtual bool ShowMapHighlight [get]
virtual bool ShowMapHighlightBlock [get]
virtual bool PickHeldOnStart [get]
virtual bool DropHeldOnStart [get]
virtual bool CanPressRepeat [get]
virtual bool CanAutofire [get]
virtual bool ResetAxis [get]
virtual bool RequireTool [get]
virtual bool IsHostileAct [get]
virtual bool HideRightInfo [get]
virtual bool ShouldEndMimicry [get]
virtual bool HaveLongPressAction [get]
virtual float Radius [get]
virtual int PerformDistance [get]
virtual int MaxRadius [get]
virtual TargetType TargetType [get]
virtual bool LocalAct [get]
virtual bool CanRapidFire [get]
virtual float RapidDelay [get]
virtual bool ShowAuto [get]
virtual bool IsCrime [get]
Properties inherited from Element
SourceElement.Row source [get]
virtual int DisplayValue [get]
virtual int MinValue [get]
int Value [get]
int ValueWithoutLink [get]
virtual int MinPotential [get]
int Potential [get]
virtual bool CanGainExp [get]
bool IsFlag [get]
virtual string Name [get]
virtual string FullName [get]
virtual int ExpToNext [get]
virtual bool UseExpMod [get]
virtual int CostTrain [get]
virtual int CostLearn [get]
virtual bool ShowXP [get]
virtual bool ShowMsgOnValueChanged [get]
virtual bool ShowValue [get]
virtual bool ShowPotential [get]
virtual bool UsePotential [get]
virtual bool PotentialAsStock [get]
virtual bool ShowRelativeAttribute [get]
virtual bool ShowBonuses [get]
virtual string ShortName [get]
bool IsGlobalElement [get]
bool IsFactionWideElement [get]
bool IsPartyWideElement [get]
virtual bool ShowEncNumber [get]
bool IsTrait [get]
bool IsFoodTrait [get]
bool IsFoodTraitMain [get]
bool IsMainAttribute [get]
Act act [get]
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Detailed Description
Definition at line 4 of file AI_Shear.cs.
Member Function Documentation
GetFur()
static Thing AI_Shear.GetFur (Chara c, int mod = 100) inline static
Definition at line 89 of file AI_Shear.cs.
    {
        int furLv = GetFurLv(c);
        string text = "fiber";
        string idMat = "wool";
        string text2 = c.id;
        if (!(text2 == "putty_snow"))
        {
            if (text2 == "putty_snow_gold")
            {
                idMat = "gold";
            }
            else if (!c.Chara.race.fur.IsEmpty())
            {
                string[] array = c.Chara.race.fur.Split('/');
                text = array[0];
                idMat = array[1];
            }
        }
        else
        {
            idMat = "cashmere";
        }
        Thing thing = ThingGen.Create(text, idMat);
        int num = mod * furLv + furLv * furLv * 10;
        int num2 = c.LV;
        if (c.IsInCombat || c.IsMinion)
        {
            Msg.Say("shear_penalty");
            num /= 2;
            num2 /= 2;
        }
        int num3 = 20 + thing.material.tier * 20;
        thing.SetNum(Mathf.Max(num / num3, 1) + EClass.rnd(furLv + 1));
        thing.SetEncLv(EClass.curve(num2, 30, 10) / 10);
        thing.elements.ModBase(2, EClass.curve(num2 / 10 * 10, 30, 10));
        c.c_fur = -5;
        return thing;
    }
References Card.Chara, ThingGen.Create(), EClass.curve(), Card.elements, GetFurLv(), Card.id, Chara.IsInCombat, Chara.IsMinion, Card.LV, ElementContainer.ModBase(), Chara.race, EClass.rnd(), Msg.Say(), Card.SetEncLv(), and Card.SetNum().
Referenced by Run(), and AI_Slaughter.Run().
GetFurLv()
static int AI_Shear.GetFurLv (Chara c) inline static
Definition at line 84 of file AI_Shear.cs.
    {
        return Mathf.Clamp(c.c_fur / 10 + 1, 1, 5);
    }
References Card.c_fur.
Referenced by GetFur(), and Run().
GetText()
override string AI_Shear.GetText (string str = "") inline virtual
Reimplemented from Act.
Definition at line 11 of file AI_Shear.cs.
    {
        string[] list = Lang.GetList("fur");
        string text = list[Mathf.Clamp(target.c_fur / 10, 0, list.Length - 1)];
        return "AI_Shear".lang() + "(" + text + ")";
    }
References Card.c_fur, Lang.GetList(), and AI_TargetCard.target.
IsValidTC()
override bool AI_Shear.IsValidTC (Card c) inline virtual
Reimplemented from Act.
Definition at line 18 of file AI_Shear.cs.
    {
        if (c != null && c.IsAliveInCurrentZone)
        {
            return c.CanBeSheared();
        }
        return false;
    }
References Card.CanBeSheared(), and Card.IsAliveInCurrentZone.
Referenced by Run().
Perform()
override bool AI_Shear.Perform () inline virtual
Reimplemented from Act.
Definition at line 27 of file AI_Shear.cs.
    {
        target = Act.TC;
        return base.Perform();
    }
References AI_TargetCard.target, and Act.TC.
Run()
override IEnumerable< Status > AI_Shear.Run () inline virtual
Reimplemented from AIAct.
Definition at line 33 of file AI_Shear.cs.
    {
        yield return DoGoto(target);
        int furLv = GetFurLv(target.Chara);
        Progress_Custom seq = new Progress_Custom
        {
            canProgress = () => IsValidTC(target),
            onProgressBegin = delegate
            {
                owner.Say("shear_start", owner, target);
                if (EClass.rnd(5) == 0)
                {
                    owner.Talk("goodBoy");
                }
            },
            onProgress = delegate(Progress_Custom p)
            {
                owner.LookAt(target);
                owner.PlaySound("shear");
                target.renderer.PlayAnime(AnimeID.Shiver);
                if (owner.Dist(target) > 1)
                {
                    owner.TryMoveTowards(target.pos);
                    if (owner == null)
                    {
                        p.Cancel();
                    }
                    else if (owner.Dist(target) > 1)
                    {
                        owner.Say("targetTooFar");
                        p.Cancel();
                    }
                }
            },
            onProgressComplete = delegate
            {
                if (target.IsAliveInCurrentZone)
                {
                    Thing fur = GetFur(target.Chara);
                    owner.Say("shear_end", owner, target, fur.Name);
                    owner.Pick(fur, msg: false);
                    owner.elements.ModExp(237, 50 * furLv);
                    owner.stamina.Mod(-1);
                    target.Chara.ModAffinity(owner, 1);
                    EClass.player.stats.shear++;
                }
            }
        }.SetDuration((6 + furLv * 6) * 100 / (100 + owner.Tool.material.hardness * 2), 3);
        yield return Do(seq);
    }
References AIAct.Cancel(), Card.Chara, Card.Dist(), AIAct.Do(), AIAct.DoGoto(), Card.elements, fur, GetFur(), GetFurLv(), Card.IsAliveInCurrentZone, IsValidTC(), Chara.LookAt(), Card.material, Stats.Mod(), Chara.ModAffinity(), ElementContainer.ModExp(), AIAct.owner, Chara.Pick(), CardRenderer.PlayAnime(), EClass.player, Card.PlaySound(), Card.pos, Card.renderer, EClass.rnd(), Card.Say(), Player.Stats.shear, Chara.stamina, Player.stats, Card.Talk(), AI_TargetCard.target, Card.Tool, and Chara.TryMoveTowards().
ShouldAllyAttack()
override bool AI_Shear.ShouldAllyAttack (Chara tg) inline virtual
Reimplemented from AIAct.
Definition at line 6 of file AI_Shear.cs.
    {
        return tg != target;
    }
References AI_TargetCard.target.
The documentation for this class was generated from the following file:
Elin/AI_Shear.cs