Elin Decompiled Documentation: UIInventory Class Reference
UIInventory Class Reference
Classes
class Tab
class Transaction
Public Types
enum Mode {
Default , Equip , Buy , Sell ,
Gear , Other , Select , Food ,
Item , Resource , Read , Hold ,
Tool , Put , Take , Give ,
Trade , All , Offer , Identify ,
Drink , Deliver , HoldFurniture , HoldBlock ,
Recycle
}
enum SubMode { Default , IdentifyScroll , DeliverTax }
enum InteractMode { Auto , Hold , Drop }
Public Member Functions
void SetHeader (string s)
UIInventory.Tab AddTab (Card c, UIInventory.Mode mode, Thing container=null)
UIInventory.Tab AddTab (InvOwner owner, UIInventory.Mode mode=UIInventory.Mode.All)
void OnInit ()
void RefreshWindow ()
void Close ()
void SwitchTab (UIInventory.Tab tab)
void DoAct (Act act)
void CheckDirty ()
void RefreshDestNum ()
bool DestNumIsMax ()
void RefreshMenu ()
Transform ShowDistribution (UIContextMenu dis, Window.SaveData data)
Transform ShowAdvDistribution (UIContextMenu dis, Window.SaveData data)
void Sort (bool redraw=true)
void RefreshList ()
void RefreshHighlight ()
void RefreshGrid ()
Static Public Member Functions
static void RefreshAllList ()
Static Public Member Functions inherited from EMono
static int rnd (int a)
Public Attributes
UIList list
BodySlot bodySlot
LayerInventory layer
Transform headerRow
Transform transOverflow
string idMold
Func< Thing, bool > funcList
Action< Thing > actionClick
Window window
UIContent content
UIInventory.Tab currentTab
AIAct currentAct
UIInventory.InteractMode interactMode
bool floatMode
bool dirty
bool isList
UIInventory.Transaction lastTransaction
Image imageHighlight
Image imageHighlightGrid
UIButton moldSmallTab
ButtonGrid moldButtonGrid
ButtonGrid moldButtonGridless
UIButton buttonTakeAll
UIMagicChest uiMagic
List< UIInventory.Tab > tabs = new List<UIInventory.Tab>()
bool wasDirty
Properties
InvOwner owner [get]
Card dest [get]
bool UseBG [get]
bool UseGrid [get]
bool IsMagicChest [get]
bool IsToolbelt [get]
bool IsShop [get]
CoreRef.InventoryStyle InvStyle [get]
bool IsMainMode [get]
CurrencyType CurrencyType [get]
string IDCurrency [get]
Properties inherited from EMono
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SoundManager Sound [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static CoreDebug debug [get]
Private Member Functions
void Update ()
Private Attributes
int destNum
int lastNum
bool firstMouseRightDown
Additional Inherited Members
Static Public Attributes inherited from EMono
static Core core
Detailed Description
Definition at line 7 of file UIInventory.cs.
Member Enumeration Documentation
InteractMode
enum UIInventory.InteractMode
Enumerator
Auto
Hold
Drop
Definition at line 1579 of file UIInventory.cs.
    {
        Auto,
        Hold,
        Drop
    }
Mode
enum UIInventory.Mode
Enumerator
Default
Equip
Buy
Sell
Gear
Other
Select
Food
Item
Resource
Read
Hold
Tool
Put
Take
Give
Trade
All
Offer
Identify
Drink
Deliver
HoldFurniture
HoldBlock
Recycle
Definition at line 1543 of file UIInventory.cs.
    {
        Default,
        Equip,
        Buy,
        Sell,
        Gear,
        Other,
        Select,
        Food,
        Item,
        Resource,
        Read,
        Hold,
        Tool,
        Put,
        Take,
        Give,
        Trade,
        All,
        Offer,
        Identify,
        Drink,
        Deliver,
        HoldFurniture,
        HoldBlock,
        Recycle
    }
SubMode
enum UIInventory.SubMode
Enumerator
Default
IdentifyScroll
DeliverTax
Definition at line 1572 of file UIInventory.cs.
    {
        Default,
        IdentifyScroll,
        DeliverTax
    }
Member Function Documentation
AddTab() [1/2]
UIInventory.Tab UIInventory.AddTab (Card c, UIInventory::Mode mode, Thing container = null) inline
Definition at line 135 of file UIInventory.cs.
    {
        return this.AddTab(new InvOwner(c, container, CurrencyType.None, PriceType.Default), mode);
    }
References AddTab().
Referenced by AddTab(), LayerInventory.CreateBuy(), LayerInventory.CreateContainer(), LayerInventory.CreateContainer< T >(), LayerInventory.CreateContainerAlly(), LayerInventory.CreateContainerPC(), and LayerInventory.CreatePCBackpack().
AddTab() [2/2]
UIInventory.Tab UIInventory.AddTab (InvOwner owner, UIInventory::Mode mode = UIInventory::Mode::All) inline
Definition at line 140 of file UIInventory.cs.
    {
        owner.Init();
        UIInventory.Tab tab = new UIInventory.Tab
        {
            mode = mode,
            owner = owner
        };
        this.tabs.Add(tab);
        return tab;
    }
References InvOwner.Init(), owner, and tabs.
CheckDirty()
void UIInventory.CheckDirty () inline
Definition at line 351 of file UIInventory.cs.
    {
        if (this.dirty)
        {
            this.wasDirty = true;
            if (this.UseGrid)
            {
                this.list.Redraw();
            }
            else
            {
                this.list.List(false);
            }
            UIButton.TryShowTip(null, true, true);
        }
    }
References dirty, list, and UseGrid.
Referenced by Update().
Close()
void UIInventory.Close () inline
Definition at line 247 of file UIInventory.cs.
    {
        if (!this.floatMode)
        {
            this.layer.Close();
        }
    }
References LayerInventory.Close(), floatMode, and layer.
Referenced by DoAct(), and Update().
DestNumIsMax()
bool UIInventory.DestNumIsMax () inline
Definition at line 382 of file UIInventory.cs.
    {
        UIInventory.Mode mode = this.currentTab.mode;
        return mode - UIInventory.Mode.Buy > 1;
    }
References currentTab.
Referenced by RefreshDestNum(), and SwitchTab().
DoAct()
void UIInventory.DoAct (Act act) inline
Definition at line 300 of file UIInventory.cs.
    {
        if (!EMono.pc.HasNoGoal || (act.LocalAct && EMono._zone.IsRegion))
        {
            SE.Beep();
            return;
        }
        EMono.player.hotItemToRestore = EMono.player.currentHotItem;
        if (act.IsAct)
        {
            act.Perform(EMono.pc, null, null);
            return;
        }
        this.currentAct = (act as AIAct);
        EMono.pc.SetAI(this.currentAct);
        ActionMode.Adv.SetTurbo(-1);
        if (!this.floatMode)
        {
            this.Close();
            return;
        }
    }
References EMono._zone, ActionMode.Adv, Close(), currentAct, Player.currentHotItem, floatMode, Chara.HasNoGoal, Act.IsAct, Spatial.IsRegion, Act.LocalAct, EMono.pc, Act.Perform(), EMono.player, Chara.SetAI(), and AM_Adv.SetTurbo().
OnInit()
void UIInventory.OnInit () inline
Definition at line 152 of file UIInventory.cs.
    {
        this.interactMode = EMono.player.pref.interactMode;
        using (List<UIInventory.Tab>.Enumerator enumerator = this.tabs.GetEnumerator())
        {
            while (enumerator.MoveNext())
            {
                UIInventory.Tab t = enumerator.Current;
                string text = t.textTab.IsEmpty("inv" + t.mode.ToString());
                if (!this.floatMode)
                {
                    string str = text.lang();
                    string str2 = " - ";
                    string str3;
                    if (!t.owner.owner.IsPC)
                    {
                        Chara chara = t.owner.Chara;
                        str3 = (((chara != null) ? chara.Name : null) ?? t.owner.Container.Name);
                    }
                    else
                    {
                        str3 = "you".lang().ToTitleCase(false);
                    }
                    text = str + str2 + str3;
                }
                Window.Setting.Tab tab = this.window.AddTab(text, this.content, delegate
                {
                    this.SwitchTab(t);
                }, EMono.core.refs.icons.invTab.TryGetValue(t.mode, null), text);
                if (t.smallTab)
                {
                    tab.customTab = this.moldSmallTab;
                }
            }
        }
        if (this.layer.mini)
        {
            this.layer.mini.SetActive(this.owner.Container.isChara);
            if (this.owner.Container.isChara)
            {
                this.layer.mini.SetChara(this.owner.Container.Chara);
            }
        }
        if (this.uiMagic)
        {
            this.uiMagic.SetActive(this.IsMagicChest);
            if (this.IsMagicChest)
            {
                this.uiMagic.Init();
            }
        }
        if (this.IsMagicChest)
        {
            TooltipManager.Instance.disableTimer = 0.1f;
        }
    }
References Card.Chara, InvOwner.Chara, InvOwner.Container, content, EMono.core, floatMode, UIMagicChest.Init(), Card.isChara, IsMagicChest, Card.IsPC, layer, LayerInventory.mini, UIInventory.Tab.mode, moldSmallTab, Card.Name, InvOwner.owner, owner, UIInventory.Tab.owner, EMono.player, Player.pref, WindowCharaMini.SetChara(), UIInventory.Tab.smallTab, SwitchTab(), tabs, text, UIInventory.Tab.textTab, uiMagic, and window.
Referenced by LayerInventory.OnInit().
RefreshAllList()
static void UIInventory.RefreshAllList () inline static
Definition at line 121 of file UIInventory.cs.
    {
        UIInventory[] componentsInChildren = EMono.ui.rectLayers.GetComponentsInChildren<UIInventory>();
        for (int i = 0; i < componentsInChildren.Length; i++)
        {
            componentsInChildren[i].list.Redraw();
        }
    }
References list, and EMono.ui.
Referenced by WidgetHotbar.OnEndDrag(), and ButtonGridDrag.OnPointerUp().
RefreshDestNum()
void UIInventory.RefreshDestNum () inline
Definition at line 368 of file UIInventory.cs.
    {
        if (this.destNum > 0)
        {
            return;
        }
        this.destNum = (this.DestNumIsMax() ? (EInput.isShiftDown ? 0 : -1) : (EInput.isShiftDown ? -1 : 0));
        if (this.destNum != this.lastNum)
        {
            this.lastNum = this.destNum;
            this.list.Redraw();
        }
    }
References destNum, DestNumIsMax(), lastNum, and list.
RefreshGrid()
void UIInventory.RefreshGrid () inline
Definition at line 1248 of file UIInventory.cs.
    {
        UIInventory.Mode mode = this.currentTab.mode;
        UIInventory.SubMode subMode = this.currentTab.subMode;
        CoreRef.InventoryStyle style = this.InvStyle;
        this.RefreshMenu();
        GridLayoutGroup g = this.list.GetComponent<GridLayoutGroup>();
        ContentSizeFitter component = this.list.GetComponent<ContentSizeFitter>();
        if (this.UseGrid)
        {
            g.constraintCount = ((this.window.saveData.columns == 0) ? this.owner.Container.things.width : this.window.saveData.columns);
            Vector2 cellSize = style.gridSize * (float)(100 + this.window.saveData.size) / 100f;
            g.cellSize = cellSize;
            g.enabled = (component.enabled = true);
        }
        else
        {
            g.enabled = (component.enabled = false);
            this.list.Rect().sizeDelta = style.sizeContainer;
        }
        this.list.Clear();
        int maxCapacity = this.IsMagicChest ? this.owner.Container.things.MaxCapacity : 0;
        UIList.Callback<Thing, ButtonGrid> callback = new UIList.Callback<Thing, ButtonGrid>
        {
            onRedraw = delegate(Thing a, ButtonGrid b, int i)
            {
                this.dirty = false;
                b.index = i;
                bool flag = i >= this.owner.Things.Count;
                if (this.IsMagicChest)
                {
                    flag = (this.uiMagic.page * this.uiMagic.GridSize + i >= maxCapacity);
                }
                if (this.UseGrid)
                {
                    b.SetCardGrid(a, flag ? null : this.owner);
                }
                else
                {
                    b.SetCardGrid(a, this.owner);
                    if (a != null)
                    {
                        b.Rect().anchoredPosition = new Vector2((float)a.posInvX, (float)a.posInvY);
                    }
                    float num = 0.01f * (float)EMono.game.config.gridIconSize;
                    b.icon.Rect().localScale = new Vector3(num, num, 1f);
                    b.Rect().sizeDelta = b.icon.rectTransform.sizeDelta;
                }
                if (flag)
                {
                    b.interactable = false;
                    b.image.sprite = null;
                    b.image.color = new Color32(byte.MaxValue, byte.MaxValue, byte.MaxValue, 120);
                    b.image.raycastTarget = true;
                    return;
                }
                b.image.raycastTarget = true;
            },
            onList = delegate(UIList.SortMode m)
            {
                this.list.bgType = (this.UseGrid ? UIList.BGType.grid : UIList.BGType.none);
                if (this.list.bgGrid)
                {
                    this.list.bgGrid.SetActive(this.UseGrid);
                    this.list.bgGrid.color = style.gridColor;
                    if (this.window.saveData.color.a != 0)
                    {
                        this.list.bgGrid.color = this.window.saveData.color;
                    }
                }
                if (this.IsMagicChest)
                {
                    this.owner.Container.things.RefreshGrid(this.uiMagic, this.window.saveData);
                }
                else
                {
                    this.owner.Container.things.RefreshGrid();
                }
                if (this.UseGrid)
                {
                    if (this.IsMagicChest)
                    {
                        for (int i = 0; i < this.owner.Container.things.GridSize; i++)
{
                            this.list.Add(this.owner.Things[i]);
                        }
                    }
                    else
                    {
                        int count = this.owner.Things.Count;
                        int num = (int)Mathf.Ceil((float)(count / g.constraintCount + ((count % g.constraintCount == 0) ? 0 : 1))) * g.constraintCount;
                        for (int j = 0; j < num; j++)
{
                            this.list.Add((j < count) ? this.owner.Things[j] : null);
                        }
                    }
                }
                else
                {
                    Vector2 sizeDelta2 = this.list.Rect().sizeDelta;
                    foreach (Thing thing2 in this.owner.Things)
                    {
                        if (thing2 != null)
{
                            this.list.Add(thing2);
                            if (thing2.posInvX == 0 && thing2.posInvY == 0)
{
                                thing2.posInvX = EMono.rnd((int)sizeDelta2.x - 60) + 30;
                                thing2.posInvY = EMono.rnd((int)sizeDelta2.y - 60) + 30;
                            }
                        }
                    }
                }
                if (this.floatMode)
                {
                    this.window.setting.tabs[0].idLang = "captionInvFloat".lang(this.owner.Container.IsPC ? "" : this.owner.Container.Name, ((float)this.owner.Container.ChildrenWeight / 1000f).ToString("F1") + "/" + ((float)this.owner.Container.WeightLimit / 1000f).ToString("F1"), null, null, null);
                }
            }
        };
        bool sorted = false;
        this.list.callbacks = callback;
        this.list.onBeforeRedraw = delegate()
        {
            if (this.IsMagicChest)
            {
                if (this.firstMouseRightDown || (!Input.GetMouseButton(1) && !Input.GetKey(KeyCode.LeftShift) && !Input.GetKey(KeyCode.RightShift)))
                {
                    this.Sort(false);
                    this.firstMouseRightDown = false;
                    this.owner.Container.things.RefreshGrid(this.uiMagic, this.window.saveData);
                }
            }
            else
            {
                if (this.window.saveData.alwaysSort && !sorted && (this.firstMouseRightDown || (!Input.GetMouseButton(1) && !Input.GetKey(KeyCode.LeftShift) && !Input.GetKey(KeyCode.RightShift))))
                {
                    sorted = true;
                    this.Sort(true);
                    sorted = false;
                    this.firstMouseRightDown = false;
                }
                this.owner.Container.things.RefreshGrid();
            }
            this.dirty = false;
            if (this.UseGrid)
            {
                UIList uilist = this.list;
                for (int i = 0; i < uilist.buttons.Count; i++)
                {
                    UIList.ButtonPair value = uilist.buttons[i];
                    value.obj = ((i < this.owner.Container.things.grid.Count) ? this.owner.Container.things.grid[i] : null);
                    uilist.buttons[i] = value;
                }
            }
        };
        this.list.onAfterRedraw = delegate()
        {
            if (!this.layer.floatInv)
            {
                int num = 0;
                foreach (UIList.ButtonPair buttonPair in this.list.buttons)
                {
                    Thing thing2 = (buttonPair.component as ButtonGrid).card as Thing;
                    if (thing2 != null)
                    {
                        num += thing2.ChildrenAndSelfWeight;
                    }
                }
                string text = "statsInv2".lang(this.owner.Container.things.Count.ToString() ?? "", this.list.ItemCount.ToString() ?? "", Lang._weight(num, true, 0) + "/" + Lang._weight(this.owner.Container.WeightLimit, true, 0), null, null);
                this.layer.windows[0].textStats.SetText(text);
            }
            if (this.owner.Container.things.IsOverflowing())
            {
                if (!this.transOverflow)
                {
                    this.transOverflow = Util.Instantiate("UI/Element/Other/InvOverflow", this.window.transform);
                }
            }
            else if (this.transOverflow)
            {
                UnityEngine.Object.Destroy(this.transOverflow.gameObject);
            }
            LayerInventory.TryShowGuide(this.list);
            if (this.layer.mini)
            {
                this.layer.mini.Refresh(this.layer.mini.window.idTab);
            }
            if (this.uiMagic)
            {
                this.uiMagic.OnAfterRedraw();
            }
            UIButton.TryShowTip(null, true, true);
        };
        callback.mold = (this.UseGrid ? this.moldButtonGrid : this.moldButtonGridless);
        if (!this.UseGrid && !this.window.saveData.firstSorted)
        {
            Vector2 sizeDelta = this.list.Rect().sizeDelta;
            foreach (Thing thing in this.owner.Things)
            {
                if (thing != null)
                {
                    thing.posInvX = EMono.rnd((int)sizeDelta.x - 60) + 30;
                    thing.posInvY = EMono.rnd((int)sizeDelta.y - 60) + 30;
                }
            }
            this.window.saveData.firstSorted = true;
        }
        this.list.List(false);
        g.RebuildLayoutTo<Layer>();
        this.list.onAfterRedraw();
        if (this.list.bgGrid)
        {
            this.list.bgGrid.color = style.gridColor;
            if (this.window.saveData.color.a != 0)
            {
                this.list.bgGrid.color = this.window.saveData.color;
            }
        }
        if (this.owner == InvOwner.Trader && this.owner.UseGuide)
        {
            LayerInventory.SetDirtyAll(false);
        }
    }
References Card.ChildrenAndSelfWeight, Game.config, EMono.game, CoreRef.InventoryStyle.gridColor, InvOwner.owner, Card.posInvX, Card.posInvY, EMono.rnd(), ButtonGrid.SetCardGrid(), LayerInventory.SetDirtyAll(), CoreRef.InventoryStyle.sizeContainer, text, InvOwner.Trader, and LayerInventory.TryShowGuide().
Referenced by SwitchTab().
RefreshHighlight()
void UIInventory.RefreshHighlight () inline
Definition at line 1229 of file UIInventory.cs.
    {
        if (!this.imageHighlight)
        {
            return;
        }
        this.imageHighlight.SetActive(false);
        if (!EMono.game.altInv)
        {
            return;
        }
        Thing thing = EMono.player.currentHotItem.Thing;
        if (this.currentTab.mode == UIInventory.Mode.All && thing != null && !thing.isDestroyed)
        {
            ICardParent parent = thing.parent;
            Card container = this.owner.Container;
        }
    }
References Game.altInv, Player.currentHotItem, EMono.game, Card.isDestroyed, Card.parent, EMono.player, and HotItem.Thing.
RefreshList()
void UIInventory.RefreshList () inline
Definition at line 1145 of file UIInventory.cs.
    {
        UIInventory.Mode mode = this.currentTab.mode;
        UIInventory.SubMode subMode = this.currentTab.subMode;
        this.RefreshMenu();
        this.list.Clear();
        UIList.Callback<Thing, ButtonGrid> callbacks = new UIList.Callback<Thing, ButtonGrid>
        {
            onClick = delegate(Thing a, ButtonGrid b)
            {
                if (this.destNum != 0)
                {
                    if (this.destNum != -1)
                    {
                        int num = this.destNum;
                    }
                    else
                    {
                        int num2 = a.Num;
                    }
                }
                if (this.actionClick != null)
                {
                    this.actionClick(a);
                    this.Close();
                    return;
                }
                EMono.pc.HoldCard(a, -1);
                SE.SelectHotitem();
            },
            onInstantiate = delegate(Thing a, ButtonGrid b)
            {
                this.dirty = false;
                string name = a.Name;
                bool flag = mode == UIInventory.Mode.Buy || mode == UIInventory.Mode.Sell || mode == UIInventory.Mode.Identify;
                int num = (this.destNum == -1) ? a.Num : 1;
                int cost = flag ? (a.GetPrice(this.CurrencyType, mode == UIInventory.Mode.Sell, PriceType.Default, null) * num) : 0;
                bool canPay = cost < EMono.pc.GetCurrency(this.IDCurrency);
                if (mode == UIInventory.Mode.Identify)
                {
                    cost = 100;
                }
                b.SetCard(a, ButtonGrid.Mode.Default, delegate(UINote n)
                {
                    UIInventory.Mode mode = mode;
                    if (mode - UIInventory.Mode.Buy <= 1)
                    {
                        n.Space(8, 1);
                        UIItem uiitem = n.AddExtra<UIItem>("costPrice");
                        uiitem.text1.SetText(Lang._currency(cost, false, 14), canPay ? FontColor.Good : FontColor.Bad);
                        uiitem.image1.sprite = SpriteSheet.Get("icon_" + this.IDCurrency);
                    }
                });
                if (flag && b.subText)
                {
                    b.subText.SetText((cost.ToString() ?? "").TagColorGoodBad(() => mode == UIInventory.Mode.Sell || cost <= EMono.pc.GetCurrency(this.IDCurrency), false));
                }
            },
            onList = delegate(UIList.SortMode m)
            {
                List<Thing> list = new List<Thing>();
                foreach (Thing thing in this.owner.Things)
                {
                    if (thing != null && (this.funcList == null || this.funcList(thing)) && !thing.HasTag(CTAG.noDrop) && (thing.c_equippedSlot == 0 || mode == UIInventory.Mode.Equip || mode == UIInventory.Mode.Identify) && (!(thing.category.id == "currency") || (mode != UIInventory.Mode.Buy && mode != UIInventory.Mode.Sell)))
                    {
                        list.Add(thing);
                    }
                }
                int num = 0;
                UIList uilist = this.list;
                foreach (Thing thing2 in list)
                {
                    num += thing2.ChildrenAndSelfWeight;
                    this.list.Add(thing2);
                }
                string text = "statsInv".lang(this.owner.Container.things.Count.ToString() ?? "", this.list.ItemCount.ToString() ?? "", Lang._weight(num, true, 0), null, null);
                this.layer.windows[0].textStats.SetText(text);
            },
            onSort = null
        };
        this.list.callbacks = callbacks;
        this.list.List(false);
    }
References Card.c_equippedSlot, Card.category, Card.ChildrenAndSelfWeight, Card.GetCurrency(), Card.GetPrice(), Card.HasTag(), Chara.HoldCard(), Card.Name, Card.Num, EMono.pc, ButtonGrid.SetCard(), and text.
Referenced by SwitchTab().
RefreshMenu()
void UIInventory.RefreshMenu () inline
Definition at line 388 of file UIInventory.cs.
    {
        UIInventory.<>c__DisplayClass69_0 CS$<>8__locals1 = new UIInventory.<>c__DisplayClass69_0();
        CS$<>8__locals1.<>4__this = this;
        CS$<>8__locals1.b = this.window.buttonSort;
        CS$<>8__locals1.data = this.window.saveData;
        if (CS$<>8__locals1.b)
        {
            CS$<>8__locals1.b.onClick.RemoveAllListeners();
            CS$<>8__locals1.b.onClick.AddListener(delegate()
            {
                UIInventory.<>c__DisplayClass69_1 CS$<>8__locals4 = new UIInventory.<>c__DisplayClass69_1();
                CS$<>8__locals4.CS$<>8__locals1 = CS$<>8__locals1;
                UIContextMenu uicontextMenu = EMono.ui.CreateContextMenuInteraction();
                uicontextMenu.layoutGroup.childAlignment = TextAnchor.UpperLeft;
                uicontextMenu.alwaysPopLeft = true;
                UIContextMenu uicontextMenu2 = uicontextMenu.AddChild("sort", TextAnchor.UpperRight);
                UIList.SortMode[] sorts = CS$<>8__locals1.<>4__this.list.sorts;
                for (int i = 0; i < sorts.Length; i++)
                {
                    UIList.SortMode sort = sorts[i];
                    UIList.SortMode _sort = sort;
                    uicontextMenu2.AddButton((((CS$<>8__locals1.<>4__this.IsShop ? EMono.player.pref.sortInvShop : EMono.player.pref.sortInv) == _sort) ? "context_checker".lang() : "") + _sort.ToString().lang(), delegate()
                    {
                        if (CS$<>8__locals4.CS$<>8__locals1.<>4__this.IsShop)
{
                            EMono.player.pref.sortInvShop = _sort;
                        }
                        else
{
                            EMono.player.pref.sortInv = _sort;
                        }
                        CS$<>8__locals4.CS$<>8__locals1.<>4__this.Sort(true);
                        SE.Click();
                    }, true);
                }
                UIContextMenu uicontextMenu3 = uicontextMenu2;
                string idLang = "sort_ascending";
                bool isOn = CS$<>8__locals1.<>4__this.IsShop ? EMono.player.pref.sort_ascending_shop : EMono.player.pref.sort_ascending;
                UnityAction<bool> action;
                if ((action = CS$<>8__locals1.<>9__3) == null)
                {
                    action = (CS$<>8__locals1.<>9__3 = delegate(bool a)
                    {
                        if (CS$<>8__locals1.<>4__this.IsShop)
{
                            EMono.player.pref.sort_ascending_shop = a;
                        }
                        else
{
                            EMono.player.pref.sort_ascending = a;
                        }
                        CS$<>8__locals1.<>4__this.Sort(true);
                        SE.Click();
                    });
                }
                uicontextMenu3.AddToggle(idLang, isOn, action);
                if (!CS$<>8__locals1.<>4__this.IsMagicChest)
                {
                    UIContextMenu uicontextMenu4 = uicontextMenu2;
                    string idLang2 = "sort_always";
                    bool alwaysSort = CS$<>8__locals1.data.alwaysSort;
                    UnityAction<bool> action2;
                    if ((action2 = CS$<>8__locals1.<>9__4) == null)
                    {
                        action2 = (CS$<>8__locals1.<>9__4 = delegate(bool a)
{
                            CS$<>8__locals1.data.alwaysSort = a;
                            if (CS$<>8__locals1.data.alwaysSort)
{
                                CS$<>8__locals1.<>4__this.Sort(true);
                            }
                            SE.Click();
                        });
                    }
                    uicontextMenu4.AddToggle(idLang2, alwaysSort, action2);
                }
                if (CS$<>8__locals1.<>4__this.IsMagicChest)
                {
                    UIContextMenu uicontextMenu5 = uicontextMenu.AddChild("catFilterType", TextAnchor.UpperRight);
                    foreach (Window.SaveData.CategoryType categoryType in Util.EnumToList<Window.SaveData.CategoryType>())
                    {
                        Window.SaveData.CategoryType _c = categoryType;
                        uicontextMenu5.AddButton(((CS$<>8__locals1.data.category == categoryType) ? "context_checker".lang() : "") + ("catFilterType_" + _c.ToString()).lang(), delegate()
{
                            CS$<>8__locals4.CS$<>8__locals1.data.category = _c;
                            CS$<>8__locals4.CS$<>8__locals1.<>4__this.uiMagic.idCat = "";
                            CS$<>8__locals4.CS$<>8__locals1.<>4__this.list.Redraw();
                            SE.Click();
                        }, true);
                    }
                }
                CS$<>8__locals4.con = CS$<>8__locals1.<>4__this.owner.Container;
                bool flag2 = (!CS$<>8__locals4.con.isNPCProperty && !CS$<>8__locals4.con.isChara && (CS$<>8__locals4.con.trait is TraitShippingChest || (CS$<>8__locals4.con.GetRoot() is Zone && EMono._zone.IsPCFaction) || CS$<>8__locals4.con.GetRootCard() == EMono.pc)) || EMono._zone is Zone_Tent;
                if (CS$<>8__locals4.con.IsPC)
                {
                    flag2 = true;
                }
                if (CS$<>8__locals4.con.trait is TraitChestMerchant)
                {
                    flag2 = false;
                }
                string text;
                if (flag2)
                {
                    UIInventory.<>c__DisplayClass69_4 CS$<>8__locals7 = new UIInventory.<>c__DisplayClass69_4();
                    CS$<>8__locals7.CS$<>8__locals4 = CS$<>8__locals4;
                    CS$<>8__locals7.dis = uicontextMenu.AddChild("distribution", TextAnchor.UpperRight);
                    UIContextMenu dis = CS$<>8__locals7.dis;
                    text = "priority_hint";
                    Func<float, string> textFunc = (float a) => a.ToString() ?? "";
                    float value = (float)CS$<>8__locals1.data.priority;
                    Action<float> action3;
                    if ((action3 = CS$<>8__locals1.<>9__15) == null)
                    {
                        action3 = (CS$<>8__locals1.<>9__15 = delegate(float a)
{
                            CS$<>8__locals1.data.priority = (int)a;
                        });
                    }
                    dis.AddSlider(text, textFunc, value, action3, -5f, 20f, true, false, false);
                    CS$<>8__locals7.dist = CS$<>8__locals1.<>4__this.ShowDistribution(CS$<>8__locals7.dis, CS$<>8__locals1.data);
                    CS$<>8__locals7.distAdv = CS$<>8__locals1.<>4__this.ShowAdvDistribution(CS$<>8__locals7.dis, CS$<>8__locals1.data);
                    CS$<>8__locals7.<RefreshMenu>g__RefreshDist|16();
                    if (CS$<>8__locals7.CS$<>8__locals4.con.trait.IsFridge || EMono.core.config.game.advancedMenu)
                    {
                        UIContextMenu dis2 = CS$<>8__locals7.dis;
                        string idLang3 = "onlyRottable";
                        bool onlyRottable = CS$<>8__locals1.data.onlyRottable;
                        UnityAction<bool> action4;
                        if ((action4 = CS$<>8__locals1.<>9__17) == null)
{
                            action4 = (CS$<>8__locals1.<>9__17 = delegate(bool a)
{
                                CS$<>8__locals1.data.onlyRottable = a;
                                SE.ClickOk();
                            });
                        }
                        dis2.AddToggle(idLang3, onlyRottable, action4);
                    }
                    UIContextMenu dis3 = CS$<>8__locals7.dis;
                    string idLang4 = "noRotten";
                    bool noRotten = CS$<>8__locals1.data.noRotten;
                    UnityAction<bool> action5;
                    if ((action5 = CS$<>8__locals1.<>9__18) == null)
                    {
                        action5 = (CS$<>8__locals1.<>9__18 = delegate(bool a)
{
                            CS$<>8__locals1.data.noRotten = a;
                            SE.ClickOk();
                        });
                    }
                    dis3.AddToggle(idLang4, noRotten, action5);
                    CS$<>8__locals7.dis.AddToggle("advDistribution", CS$<>8__locals1.data.advDistribution, delegate(bool a)
                    {
                        CS$<>8__locals7.CS$<>8__locals4.CS$<>8__locals1.data.advDistribution = a;
                        base.<RefreshMenu>g__RefreshDist|16();
                        SE.ClickOk();
                    });
                    if (EMono.core.config.game.advancedMenu)
                    {
                        UIContextMenu dis4 = CS$<>8__locals7.dis;
                        string idLang5 = CS$<>8__locals1.data.filter.IsEmpty() ? "distFilter" : "distFilter2".lang(CS$<>8__locals1.data.filter, null, null, null, null);
                        Action action6;
                        if ((action6 = CS$<>8__locals1.<>9__20) == null)
{
                            action6 = (CS$<>8__locals1.<>9__20 = delegate()
{
                                string langDetail = "distFilter3";
                                string text5 = CS$<>8__locals1.data.filter.IsEmpty("");
                                Action<bool, string> onClose;
                                if ((onClose = CS$<>8__locals1.<>9__21) == null)
{
                                    onClose = (CS$<>8__locals1.<>9__21 = delegate(bool cancel, string s)
{
                                        if (!cancel)
{
                                            CS$<>8__locals1.data._filterStrs = null;
                                            CS$<>8__locals1.data.filter = s;
                                        }
                                    });
                                }
                                Dialog.InputName(langDetail, text5, onClose, Dialog.InputType.DistributionFilter);
                            });
                        }
                        dis4.AddButton(idLang5, action6, true);
                    }
                }
                if (CS$<>8__locals4.con.IsPC && EMono.core.config.game.advancedMenu)
                {
                    UIInventory.<>c__DisplayClass69_5 CS$<>8__locals8 = new UIInventory.<>c__DisplayClass69_5();
                    CS$<>8__locals8.data = EMono.player.dataPick;
                    CS$<>8__locals8.dis = uicontextMenu.AddChild("autopick", TextAnchor.UpperRight);
                    CS$<>8__locals8.dist = CS$<>8__locals1.<>4__this.ShowDistribution(CS$<>8__locals8.dis, CS$<>8__locals8.data);
                    CS$<>8__locals8.distAdv = CS$<>8__locals1.<>4__this.ShowAdvDistribution(CS$<>8__locals8.dis, CS$<>8__locals8.data);
                    CS$<>8__locals8.<RefreshMenu>g__RefreshDist|22();
                    CS$<>8__locals8.dis.AddToggle("noRotten", CS$<>8__locals8.data.noRotten, delegate(bool a)
                    {
                        CS$<>8__locals8.data.noRotten = a;
                        SE.ClickOk();
                    });
                    CS$<>8__locals8.dis.AddToggle("advDistribution", CS$<>8__locals8.data.advDistribution, delegate(bool a)
                    {
                        CS$<>8__locals8.data.advDistribution = a;
                        base.<RefreshMenu>g__RefreshDist|22();
                        SE.ClickOk();
                    });
                    if (EMono.core.config.game.advancedMenu)
                    {
                        CS$<>8__locals8.dis.AddButton(CS$<>8__locals8.data.filter.IsEmpty() ? "distFilter" : "distFilter2".lang(CS$<>8__locals8.data.filter, null, null, null, null), delegate()
{
                            string langDetail = "distFilter3";
                            string text5 = CS$<>8__locals8.data.filter.IsEmpty("");
                            Action<bool, string> onClose;
                            if ((onClose = CS$<>8__locals8.<>9__26) == null)
{
                                onClose = (CS$<>8__locals8.<>9__26 = delegate(bool cancel, string s)
{
                                    if (!cancel)
{
                                        CS$<>8__locals8.data._filterStrs = null;
                                        CS$<>8__locals8.data.filter = s;
                                    }
                                });
                            }
                            Dialog.InputName(langDetail, text5, onClose, Dialog.InputType.DistributionFilter);
                        }, true);
                    }
                }
                if (CS$<>8__locals4.con.trait is TraitShippingChest || (CS$<>8__locals4.con.IsInstalled && (EMono._zone.IsPCFaction || EMono._zone is Zone_Tent)))
                {
                    UIContextMenu uicontextMenu6 = uicontextMenu.AddChild("autodump", TextAnchor.UpperRight);
                    foreach (AutodumpFlag autodumpFlag in new List<AutodumpFlag>
                    {
                        AutodumpFlag.existing,
                        AutodumpFlag.sameCategory,
                        AutodumpFlag.distribution,
                        AutodumpFlag.none
                    })
                    {
                        string str = (CS$<>8__locals1.data.autodump == autodumpFlag) ? "context_checker".lang() : "";
                        AutodumpFlag _e = autodumpFlag;
                        UIButton uibutton = uicontextMenu6.AddButton(str + ("dump_" + autodumpFlag.ToString()).lang(), delegate()
{
                            SE.Click();
                            CS$<>8__locals4.CS$<>8__locals1.data.autodump = _e;
                        }, true);
                        if (autodumpFlag != AutodumpFlag.none)
{
                            uibutton.SetTooltipLang("dump_" + autodumpFlag.ToString() + "_tip");
                        }
                    }
                }
                if (CS$<>8__locals4.con.IsPC || (CS$<>8__locals4.con.isThing && !(CS$<>8__locals4.con.trait is TraitChestMerchant) && !CS$<>8__locals4.con.isNPCProperty))
                {
                    UIContextMenu uicontextMenu7 = uicontextMenu.AddChild("config", TextAnchor.UpperRight);
                    UIContextMenu uicontextMenu8 = uicontextMenu7;
                    string idLang6 = "toggleExcludeCraft";
                    bool excludeCraft = CS$<>8__locals1.data.excludeCraft;
                    UnityAction<bool> action7;
                    if ((action7 = CS$<>8__locals1.<>9__28) == null)
                    {
                        action7 = (CS$<>8__locals1.<>9__28 = delegate(bool a)
{
                            CS$<>8__locals1.data.excludeCraft = a;
                            SE.ClickOk();
                        });
                    }
                    uicontextMenu8.AddToggle(idLang6, excludeCraft, action7);
                    if (CS$<>8__locals4.con.GetRootCard() == EMono.pc)
                    {
                        UIContextMenu uicontextMenu9 = uicontextMenu7;
                        string idLang7 = "toggleDump";
                        bool excludeDump = CS$<>8__locals1.data.excludeDump;
                        UnityAction<bool> action8;
                        if ((action8 = CS$<>8__locals1.<>9__29) == null)
{
                            action8 = (CS$<>8__locals1.<>9__29 = delegate(bool a)
{
                                CS$<>8__locals1.data.excludeDump = a;
                                SE.ClickOk();
                            });
                        }
                        uicontextMenu9.AddToggle(idLang7, excludeDump, action8);
                    }
                    if (EMono.core.config.game.advancedMenu)
                    {
                        if (!CS$<>8__locals4.con.IsPC)
{
                            UIContextMenu uicontextMenu10 = uicontextMenu7;
                            string idLang8 = "noRightClickClose";
                            bool noRightClickClose = CS$<>8__locals1.data.noRightClickClose;
                            UnityAction<bool> action9;
                            if ((action9 = CS$<>8__locals1.<>9__30) == null)
{
                                action9 = (CS$<>8__locals1.<>9__30 = delegate(bool a)
{
                                    CS$<>8__locals1.data.noRightClickClose = a;
                                    SE.ClickOk();
                                });
                            }
                            uicontextMenu10.AddToggle(idLang8, noRightClickClose, action9);
                        }
                        UIContextMenu uicontextMenu11 = uicontextMenu7;
                        string idLang9 = "fixedPos";
                        bool fixedPos = CS$<>8__locals1.data.fixedPos;
                        UnityAction<bool> action10;
                        if ((action10 = CS$<>8__locals1.<>9__31) == null)
{
                            action10 = (CS$<>8__locals1.<>9__31 = delegate(bool a)
{
                                CS$<>8__locals1.data.fixedPos = a;
                                CS$<>8__locals1.<>4__this.RefreshWindow();
                                SE.ClickOk();
                            });
                        }
                        uicontextMenu11.AddToggle(idLang9, fixedPos, action10);
                        UIContextMenu uicontextMenu12 = uicontextMenu7;
                        string idLang10 = "toggleItemCompress";
                        bool compress = CS$<>8__locals1.data.compress;
                        UnityAction<bool> action11;
                        if ((action11 = CS$<>8__locals1.<>9__32) == null)
{
                            action11 = (CS$<>8__locals1.<>9__32 = delegate(bool a)
{
                                CS$<>8__locals1.data.compress = a;
                                SE.ClickOk();
                            });
                        }
                        uicontextMenu12.AddToggle(idLang10, compress, action11);
                    }
                    if (CS$<>8__locals4.con.IsPC)
                    {
                        uicontextMenu7.AddToggle("placeContainerCenter", EMono.player.openContainerCenter, delegate(bool a)
{
                            EMono.player.openContainerCenter = a;
                            SE.ClickOk();
                        });
                    }
                    if (!CS$<>8__locals4.con.isChara && !CS$<>8__locals4.con.trait.IsSpecialContainer)
                    {
                        uicontextMenu7.AddButton("changeName", delegate()
{
                            string langDetail = "dialogChangeName";
                            string text5 = CS$<>8__locals4.con.c_altName.IsEmpty("");
                            Action<bool, string> onClose;
                            if ((onClose = CS$<>8__locals4.<>9__37) == null)
{
                                onClose = (CS$<>8__locals4.<>9__37 = delegate(bool cancel, string text)
{
                                    if (!cancel)
{
                                        CS$<>8__locals4.con.c_altName = text;
                                    }
                                });
                            }
                            Dialog.InputName(langDetail, text5, onClose, Dialog.InputType.Item);
                        }, true);
                    }
                    if (EMono.core.config.game.advancedMenu)
                    {
                        uicontextMenu7.AddButton("copyContainer", delegate()
{
                            SE.ClickOk();
                            EMono.player.windowDataCopy = IO.DeepCopy<Window.SaveData>(CS$<>8__locals4.CS$<>8__locals1.data);
                            EMono.player.windowDataName = CS$<>8__locals4.con.Name;
                        }, true);
                        if (EMono.player.windowDataCopy != null && !CS$<>8__locals4.con.IsPC)
{
                            UIContextMenu uicontextMenu13 = uicontextMenu7;
                            string idLang11 = "pasteContainer".lang(EMono.player.windowDataName, null, null, null, null);
                            Action action12;
                            if ((action12 = CS$<>8__locals1.<>9__36) == null)
{
                                action12 = (CS$<>8__locals1.<>9__36 = delegate()
{
                                    SE.ClickOk();
                                    CS$<>8__locals1.<>4__this.window.saveData.CopyFrom(EMono.player.windowDataCopy);
                                    CS$<>8__locals1.<>4__this.RefreshWindow();
                                    CS$<>8__locals1.<>4__this.RefreshGrid();
                                });
                            }
                            uicontextMenu13.AddButton(idLang11, action12, true);
                        }
                    }
                }
                UIContextMenu uicontextMenu14 = uicontextMenu.AddChild("appearanceWindow", TextAnchor.UpperRight);
                UIContextMenu uicontextMenu15 = uicontextMenu14;
                string idLang12 = "toggleBG";
                bool useBG = CS$<>8__locals1.data.useBG;
                UnityAction<bool> action13;
                if ((action13 = CS$<>8__locals1.<>9__5) == null)
                {
                    action13 = (CS$<>8__locals1.<>9__5 = delegate(bool a)
                    {
                        CS$<>8__locals1.data.useBG = a;
                        CS$<>8__locals1.data.color = CS$<>8__locals1.<>4__this.InvStyle.gridColor;
                        CS$<>8__locals1.<>4__this.RefreshWindow();
                        CS$<>8__locals1.<>4__this.RefreshGrid();
                        SE.ClickOk();
                    });
                }
                uicontextMenu15.AddToggle(idLang12, useBG, action13);
                UIContextMenu uicontextMenu16 = uicontextMenu14;
                string text2 = "size";
                Func<float, string> textFunc2 = (float a) => a.ToString() ?? "";
                float value2 = (float)CS$<>8__locals1.data.size;
                Action<float> action14;
                if ((action14 = CS$<>8__locals1.<>9__7) == null)
                {
                    action14 = (CS$<>8__locals1.<>9__7 = delegate(float b)
                    {
                        CS$<>8__locals1.data.size = (int)b;
                        CS$<>8__locals1.<>4__this.RefreshGrid();
                    });
                }
                uicontextMenu16.AddSlider(text2, textFunc2, value2, action14, -25f, 25f, true, false, false);
                if (EMono.core.config.game.advancedMenu && !CS$<>8__locals1.<>4__this.IsMagicChest)
                {
                    UIContextMenu uicontextMenu17 = uicontextMenu14;
                    string text3 = "columns";
                    Func<float, string> textFunc3 = (float a) => a.ToString() ?? "";
                    float value3 = (float)CS$<>8__locals1.data.columns;
                    Action<float> action15;
                    if ((action15 = CS$<>8__locals1.<>9__9) == null)
                    {
                        action15 = (CS$<>8__locals1.<>9__9 = delegate(float b)
{
                            CS$<>8__locals1.data.columns = (int)b;
                            CS$<>8__locals1.<>4__this.RefreshGrid();
                        });
                    }
                    uicontextMenu17.AddSlider(text3, textFunc3, value3, action15, 0f, 20f, true, false, false);
                }
                UIContextMenu uicontextMenu18 = uicontextMenu14;
                string idLang13 = "colorGrid";
                Action action16;
                if ((action16 = CS$<>8__locals1.<>9__10) == null)
                {
                    action16 = (CS$<>8__locals1.<>9__10 = delegate()
                    {
                        LayerColorPicker layerColorPicker = EMono.ui.AddLayer<LayerColorPicker>();
                        Color startColor = CS$<>8__locals1.data.color;
                        Color gridColor = CS$<>8__locals1.<>4__this.InvStyle.gridColor;
                        Action<PickerState, Color> onChangeColor;
                        if ((onChangeColor = CS$<>8__locals1.<>9__38) == null)
{
                            onChangeColor = (CS$<>8__locals1.<>9__38 = delegate(PickerState state, Color _c)
{
                                CS$<>8__locals1.data.color = _c;
                                CS$<>8__locals1.<>4__this.list.bgGrid.color = _c;
                                if (CS$<>8__locals1.data.color.a == 0)
{
                                    CS$<>8__locals1.<>4__this.list.bgGrid.color = CS$<>8__locals1.<>4__this.InvStyle.gridColor;
                                }
                            });
                        }
                        layerColorPicker.SetColor(startColor, gridColor, onChangeColor);
                    });
                }
                uicontextMenu18.AddButton(idLang13, action16, true);
                if (!CS$<>8__locals4.con.isChara)
                {
                    UIContextMenu uicontextMenu19 = uicontextMenu14;
                    string idLang14 = "changeIcon";
                    Action action17;
                    if ((action17 = CS$<>8__locals1.<>9__11) == null)
                    {
                        action17 = (CS$<>8__locals1.<>9__11 = delegate()
{
                            EMono.ui.contextMenu.currentMenu.Hide();
                            UIContextMenu uicontextMenu21 = EMono.ui.CreateContextMenuInteraction();
                            GridLayoutGroup parent = uicontextMenu21.AddGridLayout();
                            int num = 0;
                            foreach (Sprite sprite in EMono.core.refs.spritesContainerIcon)
{
                                UIButton uibutton2 = Util.Instantiate<UIButton>("UI/Element/Button/ButtonContainerIcon", parent);
                                int _i = num;
                                uibutton2.icon.sprite = EMono.core.refs.spritesContainerIcon[_i];
                                uibutton2.SetOnClick(delegate
{
                                    SE.Click();
                                    CS$<>8__locals1.<>4__this.owner.Container.c_indexContainerIcon = _i;
                                    LayerInventory.SetDirty(CS$<>8__locals1.<>4__this.owner.Container.Thing);
                                    EMono.ui.contextMenu.currentMenu.Hide();
                                });
                                num++;
                            }
                            uicontextMenu21.Show();
                        });
                    }
                    uicontextMenu19.AddButton(idLang14, action17, true);
                }
                if (EMono.debug.enable)
                {
                    UIContextMenu uicontextMenu20 = uicontextMenu.AddChild("debug", TextAnchor.UpperRight);
                    uicontextMenu20.AddToggle("toggleGrid", EMono.core.config.game.useGrid, delegate(bool a)
                    {
                        EMono.core.config.game.useGrid = a;
                        foreach (LayerInventory layerInventory in LayerInventory.listInv)
{
                            layerInventory.invs[0].RefreshWindow();
                            layerInventory.invs[0].RefreshGrid();
                        }
                    });
                    string text4 = "iconSize";
                    Func<float, string> textFunc4 = (float a) => a.ToString() ?? "";
                    float value4 = (float)EMono.game.config.gridIconSize;
                    Action<float> action18;
                    if ((action18 = CS$<>8__locals1.<>9__42) == null)
                    {
                        action18 = (CS$<>8__locals1.<>9__42 = delegate(float b)
{
                            EMono.game.config.gridIconSize = (int)b;
                            CS$<>8__locals1.<>4__this.RefreshGrid();
                        });
                    }
                    uicontextMenu20.AddSlider(text4, textFunc4, value4, action18, 100f, 150f, true, false, false);
                }
                uicontextMenu.Show();
                uicontextMenu.hideOnMouseLeave = false;
            });
        }
        CS$<>8__locals1.b = this.window.buttonQuickSort;
        if (CS$<>8__locals1.b)
        {
            CS$<>8__locals1.b.onClick.RemoveAllListeners();
            CS$<>8__locals1.b.onClick.AddListener(delegate()
            {
                CS$<>8__locals1.<>4__this.Sort(true);
                SE.Click();
            });
        }
        CS$<>8__locals1.b = this.window.buttonExtra;
        if (CS$<>8__locals1.b)
        {
            CS$<>8__locals1.b.SetActive(this.owner.Container.IsPC);
            CS$<>8__locals1.b.onClick.RemoveAllListeners();
            CS$<>8__locals1.b.onClick.AddListener(delegate()
            {
                TaskDump.TryPerform();
            });
        }
        CS$<>8__locals1.b = this.window.buttonShared;
        if (CS$<>8__locals1.b)
        {
            Card con = this.owner.Container;
            bool flag = !con.isChara && ((con.IsInstalled && EMono._zone.IsPCFaction) || this.owner.owner.IsPC);
            CS$<>8__locals1.b.SetActive(flag);
            if (flag)
            {
                CS$<>8__locals1.<RefreshMenu>g__RefreshShareButton|43();
                CS$<>8__locals1.b.SetOnClick(delegate
                {
                    bool flag2 = CS$<>8__locals1.data.sharedType == ContainerSharedType.Shared;
                    SE.ClickOk();
                    Msg.Say("changePermission", con, (flag2 ? "stPersonal" : "stShared").lang(), null, null);
                    CS$<>8__locals1.data.sharedType = (flag2 ? ContainerSharedType.Personal : ContainerSharedType.Shared);
                    CS$<>8__locals1.<RefreshMenu>g__RefreshShareButton|43();
                });
            }
        }
        UIInventory.Mode mode = this.currentTab.mode;
        WindowMenu menuBottom = this.window.menuBottom;
        menuBottom.Clear();
        if (mode != UIInventory.Mode.Buy)
        {
            if (mode == UIInventory.Mode.Take && !this.owner.Container.isNPCProperty && !this.owner.Container.isChara && !this.IsMagicChest)
            {
                this.buttonTakeAll = menuBottom.AddButton("takeAll".lang(EInput.keys.getAll.key.ToString().ToLower(), null, null, null, null), delegate(UIButton b)
                {
                    CS$<>8__locals1.<>4__this.owner.Container.things.ForeachReverse(delegate(Thing t)
                    {
                        if (!EMono.pc.things.IsFull(t, true, true))
{
                            EMono.pc.Pick(t, false, true);
                        }
                    });
                    if (CS$<>8__locals1.<>4__this.owner.Container.things.Count > 0)
                    {
                        SE.Beep();
                        return;
                    }
                    SE.Play("pick_thing");
                    CS$<>8__locals1.<>4__this.Close();
                }, null, "Default");
                return;
            }
        }
        else
        {
            Card _owner = this.owner.owner;
            int cost = _owner.trait.CostRerollShop;
            if (cost > 0)
            {
                menuBottom.AddButton("rerollShop".lang(cost.ToString() ?? "", null, null, null, null), delegate(UIButton b)
                {
                    if (EMono._zone.influence < cost)
                    {
                        SE.Beep();
                        Msg.Say("notEnoughInfluence");
                        return;
                    }
                    SE.Dice();
                    EMono._zone.influence -= cost;
                    _owner.c_dateStockExpire = 0;
                    _owner.trait.OnBarter();
                    CS$<>8__locals1.<>4__this.RefreshGrid();
                    CS$<>8__locals1.<>4__this.Sort(true);
                    SE.Play("shop_open");
                }, null, "Default");
            }
        }
    }
References EMono._zone, Color, Game.config, InvOwner.Container, EMono.core, Trait.CostRerollShop, currentTab, Player.dataPick, EMono.debug, CoreDebug.enable, EMono.game, Spatial.influence, Dialog.InputName(), LayerInventory.invs, ThingContainer.IsFull(), Card.IsPC, Zone.IsPCFaction, LayerInventory.listInv, Trait.OnBarter(), Player.openContainerCenter, InvOwner.owner, owner, EMono.pc, Chara.Pick(), EMono.player, Player.pref, RefreshMenu(), Msg.Say(), LayerColorPicker.SetColor(), LayerInventory.SetDirty(), text, Card.things, Card.trait, TaskDump.TryPerform(), EMono.ui, window, Player.windowDataCopy, and Player.windowDataName.
Referenced by RefreshMenu().
RefreshWindow()
void UIInventory.RefreshWindow () inline
Definition at line 209 of file UIInventory.cs.
    {
        if (this.window.saveData == null)
        {
            Window window = this.window;
            Window.SaveData saveData;
            if ((saveData = Window.dictData.TryGetValue(this.window.idWindow, null)) == null)
            {
                (saveData = new Window.SaveData()).useBG = EMono.core.config.game.showInvBG;
            }
            window.saveData = saveData;
        }
        this.window.setting.allowMove = !this.window.saveData.fixedPos;
        this.window.bgCollider.raycastTarget = (!this.window.saveData.fixedPos || this.window.saveData.useBG);
        this.window.imageBG.SetActive(this.UseBG);
        CoreRef.InventoryStyle inventoryStyle = EMono.core.refs.invStyle[this.owner.Container.trait.IDInvStyle];
        if (this.UseBG)
        {
            this.window.imageBG.sprite = inventoryStyle.bg;
            this.window.imageBG.rectTransform.anchoredPosition = inventoryStyle.posFix;
            this.window.imageBG.rectTransform.sizeDelta = inventoryStyle.sizeDelta;
            this.window.imageBG.alphaHitTestMinimumThreshold = 1f;
        }
        if (this.IsToolbelt)
        {
            this.window.cgFloatMenu.SetActive(false);
            this.window.cgFloatMenu = null;
            this.window.bgCollider.rectTransform.anchoredPosition = new Vector2(-2.5f, 0f);
            this.window.bgCollider.rectTransform.sizeDelta = new Vector2(-20f, -20f);
        }
        if (EMono.core.config.ui.showFloatButtons && this.window.cgFloatMenu)
        {
            this.window.cgFloatMenu.alpha = 1f;
            this.window.cgFloatMenu.enabled = false;
            this.window.cgFloatMenu.SetActive(true);
        }
    }
References CoreRef.InventoryStyle.bg, InvOwner.Container, EMono.core, Trait.IDInvStyle, IsToolbelt, owner, CoreRef.InventoryStyle.posFix, CoreRef.InventoryStyle.sizeDelta, Card.trait, UseBG, and window.
Referenced by SwitchTab().
SetHeader()
void UIInventory.SetHeader (string s) inline
Definition at line 130 of file UIInventory.cs.
    {
        this.window.SetCaption(s.lang());
    }
References window.
Referenced by LayerInventory.CreatePCBackpack().
ShowAdvDistribution()
Transform UIInventory.ShowAdvDistribution (UIContextMenu dis, Window::SaveData data) inline
Definition at line 1045 of file UIInventory.cs.
    {
        UIDistribution uidistribution = Util.Instantiate<UIDistribution>("UI/Layer/UIDistribution", null);
        uidistribution.SetContainer(this.owner.Container, data);
        return dis.AddGameObject<UIDistribution>(uidistribution).transform;
    }
References InvOwner.Container, owner, and UIDistribution.SetContainer().
ShowDistribution()
Transform UIInventory.ShowDistribution (UIContextMenu dis, Window::SaveData data) inline
Definition at line 1003 of file UIInventory.cs.
    {
        UIInventory.<>c__DisplayClass70_0 CS$<>8__locals1 = new UIInventory.<>c__DisplayClass70_0();
        CS$<>8__locals1.data = data;
        CS$<>8__locals1.items = new List<UIContextMenuItem>();
        CS$<>8__locals1.itemAll = null;
        List<ContainerFlag> list = Util.EnumToList<ContainerFlag>();
        list.Remove(ContainerFlag.none);
        GridLayoutGroup gridLayoutGroup = dis.AddGridLayout("Context_LayoutDistribution");
        CS$<>8__locals1.itemAll = dis.AddToggle("all", false, delegate(bool a)
        {
            foreach (UIContextMenuItem uicontextMenuItem2 in CS$<>8__locals1.items)
            {
                uicontextMenuItem2.toggle.isOn = a;
            }
            base.<ShowDistribution>g__Refresh|0();
            SE.ClickOk();
        });
        using (List<ContainerFlag>.Enumerator enumerator = list.GetEnumerator())
        {
            while (enumerator.MoveNext())
            {
                ContainerFlag f = enumerator.Current;
                SourceCategory.Row row = EMono.sources.categories.map[f.ToString()];
                CS$<>8__locals1.items.Add(dis.AddToggle(row.GetName(), !CS$<>8__locals1.data.flag.HasFlag(f), delegate(bool a)
                {
                    CS$<>8__locals1.<ShowDistribution>g__SetOn|1(f, !a);
                    CS$<>8__locals1.<ShowDistribution>g__Refresh|0();
                    SE.ClickOk();
                }));
            }
        }
        CS$<>8__locals1.itemAll.transform.SetParent(gridLayoutGroup.transform);
        CS$<>8__locals1.itemAll.GetComponentInChildren<UIText>().SetText("all".lang(), FontColor.Topic);
        foreach (UIContextMenuItem uicontextMenuItem in CS$<>8__locals1.items)
        {
            uicontextMenuItem.transform.SetParent(gridLayoutGroup.transform);
        }
        CS$<>8__locals1.<ShowDistribution>g__Refresh|0();
        return gridLayoutGroup.transform;
    }
References SourceManager.categories, SourceCategory.Row.flag, list, ShowDistribution(), and EMono.sources.
Referenced by ShowDistribution().
Sort()
void UIInventory.Sort (bool redraw = true) inline
Definition at line 1052 of file UIInventory.cs.
    {
        UIList.SortMode m = this.IsShop ? EMono.player.pref.sortInvShop : EMono.player.pref.sortInv;
        bool flag = true;
        while (flag)
        {
            flag = false;
            foreach (Thing thing in this.owner.Container.things)
            {
                if (thing.invY != 1)
                {
                    foreach (Thing thing2 in this.owner.Container.things)
                    {
                        if (thing != thing2 && thing2.invY != 1 && thing.TryStackTo(thing2))
{
                            flag = true;
                            break;
                        }
                    }
                    if (flag)
                    {
                        break;
                    }
                }
            }
        }
        int num = 0;
        foreach (Thing thing3 in this.owner.Container.things)
        {
            if (thing3.invY != 1)
            {
                thing3.invY = 0;
                thing3.invX = -1;
            }
            thing3.SetSortVal(m, this.owner.currency);
            num++;
        }
        this.owner.Container.things.Sort(delegate(Thing a, Thing b)
        {
            bool flag2 = this.IsShop ? EMono.player.pref.sort_ascending_shop : EMono.player.pref.sort_ascending;
            if (m == UIList.SortMode.ByName)
            {
                if (flag2)
                {
                    return string.Compare(a.GetName(NameStyle.FullNoArticle, 1), b.GetName(NameStyle.FullNoArticle, 1));
                }
                return string.Compare(b.GetName(NameStyle.FullNoArticle, 1), a.GetName(NameStyle.FullNoArticle, 1));
            }
            else
            {
                if (a.sortVal == b.sortVal)
                {
                    return b.SecondaryCompare(m, a);
                }
                if (!flag2)
                {
                    return a.sortVal - b.sortVal;
                }
                return b.sortVal - a.sortVal;
            }
        });
        if (!this.UseGrid)
        {
            int num2 = 0;
            int num3 = 0;
            Vector2 sizeDelta = this.list.Rect().sizeDelta;
            sizeDelta.x -= 60f;
            sizeDelta.y -= 60f;
            foreach (Thing thing4 in this.owner.Container.things)
            {
                if (thing4.invY == 0)
                {
                    thing4.posInvX = num2 + 30;
                    thing4.posInvY = (int)sizeDelta.y - num3 + 30;
                    num2 += 40;
                    if ((float)num2 > sizeDelta.x)
                    {
                        num2 = 0;
                        num3 += 40;
                        if ((float)num3 > sizeDelta.y)
{
                            num3 = 20;
                        }
                    }
                }
            }
        }
        if (redraw)
        {
            this.list.Redraw();
        }
    }
References InvOwner.Container, InvOwner.currency, Thing.GetName(), Card.invY, owner, EMono.player, Player.pref, Card.SetSortVal(), Card.sortVal, Card.things, and Card.TryStackTo().
Referenced by SwitchTab().
SwitchTab()
void UIInventory.SwitchTab (UIInventory::Tab tab) inline
Definition at line 255 of file UIInventory.cs.
    {
        if (this.currentTab == tab)
        {
            return;
        }
        this.currentTab = tab;
        this.RefreshWindow();
        this.destNum = (this.lastNum = (this.DestNumIsMax() ? -1 : 0));
        if (this.isList)
        {
            this.RefreshList();
        }
        else
        {
            this.RefreshGrid();
        }
        if (this.IsShop || this.window.saveData.alwaysSort)
        {
            this.Sort(true);
        }
        if (this.layer.uiCurrency)
        {
            tab.owner.BuildUICurrency(this.layer.uiCurrency, tab.owner.owner.trait.CostRerollShop != 0);
        }
        this.layer.TryShowHint("h_inv" + tab.mode.ToString());
        if (this.headerRow)
        {
            UIHeader[] componentsInChildren = this.headerRow.GetComponentsInChildren<UIHeader>(true);
            componentsInChildren[0].SetText("headerItem");
            UIInventory.Mode mode = tab.mode;
            if (mode - UIInventory.Mode.Buy <= 1 || mode == UIInventory.Mode.Identify)
            {
                componentsInChildren[1].SetText("headerPrice".lang(this.IDCurrency.lang(), null, null, null, null));
                return;
            }
            if (mode != UIInventory.Mode.Recycle)
            {
                componentsInChildren[1].SetText("headerWeight");
                return;
            }
            componentsInChildren[1].SetText("headerRecycle");
        }
    }
References currentTab, DestNumIsMax(), headerRow, IDCurrency, isList, IsShop, layer, RefreshGrid(), RefreshList(), RefreshWindow(), Sort(), ELayer.TryShowHint(), LayerInventory.uiCurrency, and window.
Referenced by OnInit().
Update()
void UIInventory.Update () inline private
Definition at line 323 of file UIInventory.cs.
    {
        if (this.owner.Container.isDestroyed)
        {
            this.Close();
            return;
        }
        this.imageHighlightGrid.SetActive(LayerInventory.highlightInv == this.owner);
        this.CheckDirty();
        if (EInput.action == EAction.GetAll && this.buttonTakeAll && !this.IsMagicChest)
        {
            this.buttonTakeAll.onClick.Invoke();
        }
        if ((this.IsMagicChest || this.window.saveData.alwaysSort) && this.wasDirty && (Input.GetMouseButtonUp(1) || Input.GetKeyUp(KeyCode.LeftShift) || Input.GetKeyUp(KeyCode.RightShift)))
        {
            this.list.Redraw();
            if (!Input.GetMouseButton(1) && !Input.GetKey(KeyCode.LeftShift) && !Input.GetKey(KeyCode.RightShift))
            {
                this.wasDirty = false;
                UIButton.TryShowTip(null, true, true);
            }
        }
        if (Input.GetMouseButtonDown(1))
        {
            this.firstMouseRightDown = true;
        }
    }
References buttonTakeAll, CheckDirty(), Close(), InvOwner.Container, LayerInventory.highlightInv, imageHighlightGrid, Card.isDestroyed, IsMagicChest, list, InvOwner.owner, owner, and window.
Member Data Documentation
actionClick
Action<Thing> UIInventory.actionClick
Definition at line 1486 of file UIInventory.cs.
bodySlot
BodySlot UIInventory.bodySlot
Definition at line 1474 of file UIInventory.cs.
buttonTakeAll
UIButton UIInventory.buttonTakeAll
Definition at line 1516 of file UIInventory.cs.
Referenced by Update().
content
UIContent UIInventory.content
Definition at line 1490 of file UIInventory.cs.
Referenced by OnInit().
currentAct
AIAct UIInventory.currentAct
Definition at line 1494 of file UIInventory.cs.
Referenced by DoAct().
currentTab
UIInventory.Tab UIInventory.currentTab
Definition at line 1492 of file UIInventory.cs.
Referenced by DestNumIsMax(), RefreshMenu(), and SwitchTab().
destNum
int UIInventory.destNum private
Definition at line 1520 of file UIInventory.cs.
Referenced by RefreshDestNum().
dirty
bool UIInventory.dirty
Definition at line 1500 of file UIInventory.cs.
Referenced by CheckDirty().
firstMouseRightDown
bool UIInventory.firstMouseRightDown private
Definition at line 1524 of file UIInventory.cs.
floatMode
bool UIInventory.floatMode
Definition at line 1498 of file UIInventory.cs.
Referenced by Close(), DoAct(), and OnInit().
funcList
Func<Thing, bool> UIInventory.funcList
Definition at line 1484 of file UIInventory.cs.
headerRow
Transform UIInventory.headerRow
Definition at line 1478 of file UIInventory.cs.
Referenced by SwitchTab().
idMold
string UIInventory.idMold
Definition at line 1482 of file UIInventory.cs.
imageHighlight
Image UIInventory.imageHighlight
Definition at line 1506 of file UIInventory.cs.
imageHighlightGrid
Image UIInventory.imageHighlightGrid
Definition at line 1508 of file UIInventory.cs.
Referenced by Update().
interactMode
UIInventory.InteractMode UIInventory.interactMode
Definition at line 1496 of file UIInventory.cs.
isList
bool UIInventory.isList
Definition at line 1502 of file UIInventory.cs.
Referenced by SwitchTab().
lastNum
int UIInventory.lastNum private
Definition at line 1522 of file UIInventory.cs.
Referenced by RefreshDestNum().
lastTransaction
UIInventory.Transaction UIInventory.lastTransaction
Definition at line 1504 of file UIInventory.cs.
layer
LayerInventory UIInventory.layer
Definition at line 1476 of file UIInventory.cs.
Referenced by Close(), OnInit(), and SwitchTab().
list
UIList UIInventory.list
Definition at line 1472 of file UIInventory.cs.
Referenced by CheckDirty(), UIMagicChest.Redraw(), RefreshAllList(), RefreshDestNum(), ShowDistribution(), and Update().
moldButtonGrid
ButtonGrid UIInventory.moldButtonGrid
Definition at line 1512 of file UIInventory.cs.
moldButtonGridless
ButtonGrid UIInventory.moldButtonGridless
Definition at line 1514 of file UIInventory.cs.
moldSmallTab
UIButton UIInventory.moldSmallTab
Definition at line 1510 of file UIInventory.cs.
Referenced by OnInit().
tabs
List<UIInventory.Tab> UIInventory.tabs = new List<UIInventory.Tab>()
Definition at line 1526 of file UIInventory.cs.
Referenced by AddTab(), LayerInventory.CreateBuy(), LayerInventory.CreateContainerAlly(), LayerInventory.CreateContainerPC(), and OnInit().
transOverflow
Transform UIInventory.transOverflow
Definition at line 1480 of file UIInventory.cs.
uiMagic
UIMagicChest UIInventory.uiMagic
Definition at line 1518 of file UIInventory.cs.
Referenced by OnInit().
wasDirty
bool UIInventory.wasDirty
Definition at line 1528 of file UIInventory.cs.
window
Window UIInventory.window
Definition at line 1488 of file UIInventory.cs.
Referenced by OnInit(), RefreshMenu(), RefreshWindow(), SetHeader(), SwitchTab(), and Update().
Property Documentation
CurrencyType
CurrencyType UIInventory.CurrencyType get
Definition at line 96 of file UIInventory.cs.
    {
        get
        {
            return this.currentTab.owner.currency;
        }
    }
dest
Card UIInventory.dest get
Definition at line 17 of file UIInventory.cs.
    {
        get
        {
            return this.currentTab.dest;
        }
    }
Referenced by LayerInventory.CreateBuy(), LayerInventory.CreateContainer(), and LayerInventory.CreateContainer< T >().
IDCurrency
string UIInventory.IDCurrency get
Definition at line 104 of file UIInventory.cs.
    {
        get
        {
            CurrencyType currencyType = this.CurrencyType;
            if (currencyType == CurrencyType.Medal)
            {
                return "medal";
            }
            if (currencyType != CurrencyType.Ecopo)
            {
                return "money";
            }
            return "ecopo";
        }
    }
Referenced by SwitchTab().
InvStyle
CoreRef.InventoryStyle UIInventory.InvStyle get
Definition at line 65 of file UIInventory.cs.
    {
        get
        {
            return EMono.core.refs.invStyle[(this.UseBG || this.IsToolbelt) ? this.owner.Container.trait.IDInvStyle : "transparent"];
        }
    }
IsMagicChest
bool UIInventory.IsMagicChest get
Definition at line 41 of file UIInventory.cs.
    {
        get
        {
            return this.owner.Container.trait is TraitMagicChest;
        }
    }
Referenced by OnInit(), and Update().
IsMainMode
bool UIInventory.IsMainMode get
Definition at line 73 of file UIInventory.cs.
    {
        get
        {
            switch (this.currentTab.mode)
            {
            case UIInventory.Mode.Gear:
            case UIInventory.Mode.Food:
            case UIInventory.Mode.Item:
            case UIInventory.Mode.Resource:
            case UIInventory.Mode.Read:
            case UIInventory.Mode.Hold:
            case UIInventory.Mode.Tool:
            case UIInventory.Mode.All:
            case UIInventory.Mode.Drink:
            case UIInventory.Mode.HoldFurniture:
            case UIInventory.Mode.HoldBlock:
                return true;
            }
            return false;
        }
    }
IsShop
bool UIInventory.IsShop get
Definition at line 57 of file UIInventory.cs.
    {
        get
        {
            return this.owner.Container.trait is TraitChestMerchant;
        }
    }
Referenced by SwitchTab().
IsToolbelt
bool UIInventory.IsToolbelt get
Definition at line 49 of file UIInventory.cs.
    {
        get
        {
            return this.owner.Container.trait is TraitToolBelt;
        }
    }
Referenced by RefreshWindow().
owner
InvOwner UIInventory.owner get
Definition at line 9 of file UIInventory.cs.
    {
        get
        {
            return (this.currentTab ?? this.tabs[0]).owner;
        }
    }
Referenced by AddTab(), OnInit(), RefreshMenu(), RefreshWindow(), ShowAdvDistribution(), Sort(), and Update().
UseBG
bool UIInventory.UseBG get
Definition at line 25 of file UIInventory.cs.
    {
        get
        {
            return this.window.saveData.useBG || !this.UseGrid;
        }
    }
Referenced by RefreshWindow().
UseGrid
bool UIInventory.UseGrid get
Definition at line 33 of file UIInventory.cs.
    {
        get
        {
            return EMono.core.config.game.useGrid;
        }
    }
Referenced by CheckDirty().
The documentation for this class was generated from the following file:
Elin/UIInventory.cs