Elin Decompiled Documentation: Core Class Reference
Core Class Reference
Public Member Functions
void StartCase ()
void Update ()
void OnApplicationFocus (bool focus)
void OnApplicationQuit ()
void ResetRuntime ()
void Init ()
void Quit ()
override void ConsumeInput ()
void SetReferences ()
void SetReleaseMode (ReleaseMode m)
void OnChangeResolution ()
void Halt ()
override void FreezeScreen (float duration)
override void UnfreezeScreen ()
override void RebuildBGMList ()
override void StopEventSystem (Component c, Action action, float duration=0.12f)
override void StopEventSystem (float duration=0.2f)
void SetLang (string langCode, bool force=false)
void ApplySkins ()
Static Public Member Functions
static Core SetCurrent (Core _current=null)
static Core GetCurrent ()
static int[] ParseElements (string str)
static int GetElement (string id)
Public Attributes
CoreDebug debug
SourceManager sources
PathManager pathManager
EffectManager effects
ModManager mods = new ModManager()
PCCManager pccs
SkinManager skins
TextureManager textures = new TextureManager()
GameSetting gameSetting
GameData gamedata
CoreRef refs
ColorProfile Colors
Material matUI
Steam steam
bool useUImat
bool trial
UI ui
Scene scene
BaseGameScreen screen
CoreConfig config
Game game
bool initialized
Static Public Attributes
static new Core Instance
static float delta
static float avgDelta
static float gameDelta
static float gameDeltaNoPause
static bool spiked
Protected Member Functions
override void Awake ()
Properties
bool IsGameStarted [get]
override float uiScale [get]
Private Member Functions
void Start ()
void LateUpdate ()
IEnumerator OnEndOfFrame ()
void Update100ms ()
Private Attributes
bool? lastFullScreen
float nextResolutionUpdate
float skinTimer
Static Private Attributes
static SourceElement sourceElement
Detailed Description
Definition at line 12 of file Core.cs.
Member Function Documentation
ApplySkins()
void Core.ApplySkins () inline
Definition at line 682 of file Core.cs.
    {
        IUISkin[] componentsInChildren = this.ui.GetComponentsInChildren<IUISkin>(true);
        for (int i = 0; i < componentsInChildren.Length; i++)
        {
            componentsInChildren[i].ApplySkin();
        }
    }
Awake()
override void Core.Awake () inline protected
Definition at line 30 of file Core.cs.
    {
        base.Awake();
        QualitySettings.vSyncCount = 0;
        Application.targetFrameRate = 60;
        IO.CreateDirectory(CorePath.Temp);
        Core.SetCurrent(null);
        Lang.langCode = "";
        if (Application.isEditor && this.debug.langCode != Lang.LangCode.None)
        {
            this.forceLangCode = this.debug.langCode.ToString();
        }
        foreach (string text in Application.isEditor ? this.debug.command.Split(',', StringSplitOptions.None) : Environment.GetCommandLineArgs())
        {
            text = text.Replace("-", "").ToUpper();
            Debug.Log("Commandline args:" + text);
            if (text.StartsWith("LANG_"))
            {
                this.forceLangCode = text.Replace("LANG_", "");
            }
            else if (!(text == "DEV"))
            {
                if (!(text == "UPDATE_LANG"))
                {
                    if (text == "NOMOD")
                    {
                        ModManager.disableMod = true;
                    }
                }
                else
                {
                    Lang.runUpdate = true;
                }
            }
            else
            {
                this.releaseMode = ReleaseMode.Debug;
            }
        }
        NewsList.dict = null;
        InvOwner.Trader = (InvOwner.Main = null);
        SpriteSheet.dict.Clear();
        SpriteSheet.loadedPath.Clear();
        SpriteReplacerAnimation.dict.Clear();
        LayerDrama.haltPlaylist = false;
        LayerDrama.keepBGM = false;
        BaseModManager.isInitialized = false;
        Net.isUploading = false;
        MapPiece.initialized = false;
        ActPlan.warning = false;
        Game.isPaused = false;
        if (Application.isEditor && BaseCore.resetRuntime)
        {
            this.ResetRuntime();
        }
        Window.dictData.Clear();
        LayerInventory.listInv.Clear();
        this.debug = Resources.Load<CoreDebug>("_Debug " + this.releaseMode.ToString());
        this.debug.enable = (this.releaseMode > ReleaseMode.Public);
        if (this.useUImat)
        {
            Canvas.GetDefaultCanvasMaterial().CopyPropertiesFromMaterial(this.matUI);
            Canvas.GetDefaultCanvasMaterial().shader = this.matUI.shader;
        }
        if (!this.ui)
        {
            this.ui = Util.Instantiate<UI>("UI/UI", null);
        }
        if (!this.scene)
        {
            this.scene = Util.Instantiate<Scene>("Scene/Scene", null);
        }
        this.scene.screenNoMap.Activate();
        this.ui.ShowCover(0f, 1f, null, default(Color));
        this.canvas = this.ui.canvas;
        this.ui.OnCoreStart();
        BaseCore.BlockInput = (() => this.ui.IsDragging);
        CommandRegistry.assemblies.Add(typeof(Core).Assembly);
        SoundData.EditorPlaySpatial = delegate(SoundData a)
        {
            this.game.player.chara.PlaySound(a.name, 1f, true);
        };
        SoundManager.funcCanPlayBGM = (() => !LayerDrama.haltPlaylist && !LayerDrama.keepBGM);
        FileDragAndDrop.onDrop = new Action<List<string>>(this.textures.OnDropFile);
        MOD.langs.Clear();
        MOD.OnAddPcc = new Action<DirectoryInfo>(this.pccs.Add);
        MOD.listTalk = new TalkDataList();
        MOD.tones = new ToneDataList();
        MOD.listMaps.Clear();
        MOD.listPartialMaps.Clear();
        Portrait.modPortraitBGFs = new ModItemList<Sprite>(0);
        Portrait.modPortraitBGs = new ModItemList<Sprite>(0);
        Portrait.modPortraits = new ModItemList<Sprite>(0);
        Portrait.modOverlays = new ModItemList<Sprite>(0);
        Portrait.modFull = new ModItemList<Sprite>(0);
        Portrait.dictList = new Dictionary<string, List<ModItem<Sprite>>>();
        TileType.Init();
        this.screen.tileMap.rendererObjDummy.Init();
        Debug.Log("Core Awake");
        Debug.Log(this.steam.steamworks.settings.applicationId);
    }
References BaseGameScreen.Activate(), Player.chara, Color, debug, game, LayerDrama.haltPlaylist, RenderData.Init(), TileType.Init(), LayerDrama.keepBGM, CoreDebug.langCode, LayerInventory.listInv, matUI, TextureManager.OnDropFile(), pccs, Game.player, Card.PlaySound(), BaseTileMap.rendererObjDummy, ResetRuntime(), scene, screen, Scene.screenNoMap, SetCurrent(), steam, Steam.steamworks, text, textures, BaseGameScreen.tileMap, ui, and useUImat.
ConsumeInput()
override void Core.ConsumeInput () inline
Definition at line 500 of file Core.cs.
    {
        EInput.Consume(false, 1);
    }
FreezeScreen()
override void Core.FreezeScreen (float duration) inline
Definition at line 591 of file Core.cs.
    {
        this.ui.FreezeScreen(duration);
    }
GetCurrent()
static Core Core.GetCurrent () inline static
Definition at line 520 of file Core.cs.
    {
        return Core.Instance ?? Core.SetCurrent(null);
    }
References SetCurrent().
GetElement()
static int Core.GetElement (string id) inline static
Definition at line 662 of file Core.cs.
    {
        Core.SetCurrent(null);
        if (Core.sourceElement == null)
        {
            Core.sourceElement = UnityEngine.Object.FindObjectOfType<SourceManager>().GetComponent<SourceManager>().elements;
        }
        if (!Core.sourceElement.initialized)
        {
            Core.sourceElement.Init();
        }
        SourceElement.Row row;
        if (!Core.sourceElement.alias.TryGetValue(id ?? "_void", out row))
        {
            Debug.LogError("exception:" + id);
            row = Core.sourceElement.rows[0];
        }
        return row.id;
    }
References SourceManager.elements, SourceElement.Row.id, SetCurrent(), and sourceElement.
Referenced by ParseElements().
Halt()
void Core.Halt () inline
Definition at line 587 of file Core.cs.
    {
    }
Init()
void Core.Init () inline
Definition at line 453 of file Core.cs.
    {
        Debug.Log("Initializing:" + this.langCode + "/" + this.forceLangCode);
        base.StartCoroutine("OnEndOfFrame");
        base.InvokeRepeating("Update100ms", 0.1f, 0.1f);
        UnityEngine.Object.DestroyImmediate(this.ui.layoutLang.gameObject);
        CoreConfig.Init();
        this.SetLang(this.config.lang, false);
        this.refs.Init();
        this.debug.Init();
        SpriteSheet.Add("Media/Graphics/Icon/icons_48");
        Cal.Init();
        this.Colors.Init();
        this.gameSetting.Init();
        this.mods.InitLang();
        if (!Lang.isBuiltin)
        {
            this.sources.ImportSourceTexts();
        }
        PCCManager.current.Init();
        SpriteVariationManager.current.Init();
        this.scene.InitPass();
        this.textures.Init();
        this.textures.RefreshTextures();
        SoundManager.current.Reset();
        if (this.debug.validatePref)
        {
            SourcePrefInspector.Instance.ValidatePrefs();
        }
        if (this.debug.startScene == CoreDebug.StartScene.Title)
        {
            this.scene.Init(Scene.Mode.Title);
        }
        else
        {
            this.debug.QuickStart();
        }
        this.ui.HideCover(2f, null);
        this.initialized = true;
    }
References CoreConfig.Init(), SourcePrefInspector.Instance, and SourcePrefInspector.ValidatePrefs().
Referenced by StartCase().
LateUpdate()
void Core.LateUpdate () inline private
Definition at line 317 of file Core.cs.
    {
        if (!this.initialized)
        {
            return;
        }
        if (UIButton.actionTooltip != null)
        {
            UIButton.actionTooltip();
            UIButton.actionTooltip = null;
        }
        if (this.actionsLateUpdate.Count > 0)
        {
            for (int i = this.actionsLateUpdate.Count - 1; i >= 0; i--)
            {
                this.actionsLateUpdate[i]();
                this.actionsLateUpdate.RemoveAt(i);
            }
        }
        this.scene.OnLateUpdate();
    }
References initialized, Scene.OnLateUpdate(), and scene.
OnApplicationFocus()
void Core.OnApplicationFocus (bool focus) inline
Definition at line 339 of file Core.cs.
    {
        if (focus)
        {
            AudioListener.volume = 1f;
        }
        else if (this.config.other.muteBackground)
        {
            AudioListener.volume = 0f;
        }
        if (focus && Core.Instance)
        {
            if (this.actionsNextFrame.Count == 0)
            {
                this.actionsNextFrame.Add(delegate
                {
                    this.textures.RefreshTextures();
                    this.actionsNextFrame.Add(delegate
                    {
                        if (this.IsGameStarted)
{
                            if (Application.isEditor && WidgetMinimap.Instance)
{
                                WidgetMinimap.Instance.Reload();
                            }
                            foreach (CardRow cardRow in this.sources.cards.rows)
{
                                if (cardRow.replacer.hasChacked && cardRow.replacer.data != null)
{
                                    cardRow.replacer.data.GetSprite(false);
                                }
                            }
                        }
                    });
                });
            }
            if (this.IsGameStarted && this.debug.enable)
            {
                foreach (PCC.Part part in this.pccs.allParts.Values)
                {
                    foreach (ModItem<Texture2D> modItem in part.modTextures.Values)
                    {
                        modItem.ClearCache();
                    }
                }
                CharaActorPCC[] array = UnityEngine.Object.FindObjectsOfType<CharaActorPCC>();
                for (int i = 0; i < array.Length; i++)
                {
                    array[i].provider.Rebuild(PCCState.Normal);
                }
            }
            EInput.Consume(false, 1);
            EInput.dragHack = 0f;
            EInput.DisableIME();
        }
    }
References SourceManager.cards, config, debug, CoreDebug.enable, Instance, WidgetMinimap.Instance, IsGameStarted, CoreConfig.other, CharaActorPCC.provider, TextureManager.RefreshTextures(), SourceCard.rows, sources, and textures.
OnApplicationQuit()
void Core.OnApplicationQuit () inline
Definition at line 396 of file Core.cs.
    {
        try
        {
            foreach (Widget widget in this.ui.widgets.GetComponentsInChildren<Widget>(true))
            {
                if (widget.gameObject != null)
                {
                    UnityEngine.Object.Destroy(widget.gameObject);
                }
            }
            IO.PrintLog();
        }
        catch (Exception ex)
        {
            string str = "Exception:";
            Exception ex2 = ex;
            Debug.Log(str + ((ex2 != null) ? ex2.ToString() : null));
        }
        try
        {
            if (SteamAPI.IsSteamRunning())
            {
                SteamAPI.Shutdown();
            }
        }
        catch (Exception ex3)
        {
            string str2 = "Exception:";
            Exception ex4 = ex3;
            Debug.Log(str2 + ((ex4 != null) ? ex4.ToString() : null));
        }
        try
        {
            IO.DeleteDirectory(CorePath.Temp);
            GameIO.DeleteEmptyGameFolders();
        }
        catch (Exception ex5)
        {
            string str3 = "Exception:";
            Exception ex6 = ex5;
            Debug.Log(str3 + ((ex6 != null) ? ex6.ToString() : null));
        }
    }
References GameIO.DeleteEmptyGameFolders().
OnChangeResolution()
void Core.OnChangeResolution () inline
Definition at line 570 of file Core.cs.
    {
        if (this.config != null)
        {
            this.config.OnChangeResolution();
        }
        this.screen.RefreshScreenSize();
        this.lastScreenWidth = Screen.width;
        this.lastScreenHeight = Screen.height;
        IChangeResolution[] componentsInChildren = this.ui.GetComponentsInChildren<IChangeResolution>();
        for (int i = 0; i < componentsInChildren.Length; i++)
        {
            componentsInChildren[i].OnChangeResolution();
        }
        this.scene.camSupport.OnChangeResolution();
    }
Referenced by Update().
OnEndOfFrame()
IEnumerator Core.OnEndOfFrame () inline private
Definition at line 548 of file Core.cs.
    {
        for (;;)
        {
            yield return new WaitForEndOfFrame();
            if (this.screen.guide)
            {
                this.screen.guide.OnEndOfFrame();
            }
        }
        yield break;
    }
ParseElements()
static int[] Core.ParseElements (string str) inline static
Definition at line 645 of file Core.cs.
    {
        if (string.IsNullOrEmpty(str))
        {
            return new int[0];
        }
        string[] array = str.Replace("\n", "").Split(',', StringSplitOptions.None);
        int[] array2 = new int[array.Length * 2];
        for (int i = 0; i < array.Length; i++)
        {
            string[] array3 = array[i].Split('/', StringSplitOptions.None);
            array2[i * 2] = Core.GetElement(array3[0]);
            array2[i * 2 + 1] = ((array3.Length == 1) ? 1 : int.Parse(array3[1]));
        }
        return array2;
    }
References GetElement().
Quit()
void Core.Quit () inline
Definition at line 494 of file Core.cs.
    {
        Application.Quit();
        Debug.Log("Quit");
    }
RebuildBGMList()
override void Core.RebuildBGMList () inline
Definition at line 601 of file Core.cs.
    {
        this.refs.RebuildBGMList();
    }
ResetRuntime()
void Core.ResetRuntime () inline
Definition at line 441 of file Core.cs.
    {
        BaseCore.resetRuntime = false;
        BiomeProfile.forceInitialize = true;
        WidgetHotbar.registering = false;
        WidgetHotbar.registeringItem = null;
        WordGen.initialized = false;
        RecipeManager.rebuild = true;
        BookList.dict = null;
        SpawnList.allList.Clear();
    }
References SpawnList.allList.
Referenced by Awake().
SetCurrent()
static Core Core.SetCurrent (Core _current = null) inline static
Definition at line 505 of file Core.cs.
    {
        if (Core.Instance)
        {
            return Core.Instance;
        }
        Core.Instance = (_current ?? UnityEngine.Object.FindObjectOfType<Core>());
        BaseCore.Instance = Core.Instance;
        if (Core.Instance)
        {
            Core.Instance.SetReferences();
        }
        return Core.Instance;
    }
References Instance, and SetReferences().
Referenced by Awake(), GetCurrent(), and GetElement().
SetLang()
void Core.SetLang (string langCode, bool force = false) inline
Definition at line 627 of file Core.cs.
    {
        if (Lang.langCode == langCode && this.sources && this.sources.langGeneral)
        {
            return;
        }
        Lang.Init(langCode);
        AliasGen.list = null;
        NameGen.list = null;
        WordGen.initialized = false;
        this.sources.OnChangeLang();
        if (this.game != null && !this.IsGameStarted)
        {
            this.game.Kill();
        }
        this.config.OnSetLang();
    }
SetReferences()
void Core.SetReferences () inline
Definition at line 525 of file Core.cs.
    {
        CorePath.Init();
        SourceData.dataPath = CorePath.packageCore + "/Data/Source/";
        EMono.core = this;
        EClass.core = this;
        Core.Instance = this;
        SkinManager._Instance = this.skins;
        PathManager.Instance = this.pathManager;
        EffectManager.Instance = this.effects;
        this.sources.InitLang();
    }
Referenced by SetCurrent().
SetReleaseMode()
void Core.SetReleaseMode (ReleaseMode m) inline
Definition at line 538 of file Core.cs.
    {
        if (this.releaseMode == m)
        {
            return;
        }
        this.releaseMode = m;
        this.debug = Resources.Load<CoreDebug>("_Debug " + this.releaseMode.ToString());
    }
Start()
void Core.Start () inline private
Definition at line 132 of file Core.cs.
    {
        this.config = CoreConfig.TryLoadConfig();
        string str = "Loading Config:";
        string path = CoreConfig.path;
        string str2 = " - ";
        CoreConfig coreConfig = this.config;
        Debug.Log(str + path + str2 + ((coreConfig != null) ? coreConfig.ToString() : null));
        if (this.config != null && this.config.other.disableMods)
        {
            ModManager.disableMod = true;
        }
        try
        {
            this.steam.Init();
        }
        catch
        {
        }
        this.StartCase();
    }
References config, Steam.Init(), CoreConfig.other, CoreConfig.path, StartCase(), steam, and CoreConfig.TryLoadConfig().
StartCase()
void Core.StartCase () inline
Definition at line 154 of file Core.cs.
    {
        Debug.Log("StartCase:" + ModManager.IsInitialized.ToString());
        if (!ModManager.IsInitialized)
        {
            this.mods.Init(CorePath.rootMod, "_Elona");
            base.StartCoroutine(this.mods.RefreshMods(delegate
            {
                MOD.actorSources.Initialize();
                this.StartCase();
            }, !ModManager.disableMod && !BaseCore.IsOffline && !this.debug.skipModSync && (this.config == null || this.config.other.syncMods)));
            return;
        }
        Debug.Log("Plugins:" + ModManager.ListPluginObject.Count.ToString());
        foreach (object obj in ModManager.ListPluginObject)
        {
            Component component = obj as Component;
            if (component)
            {
                GameObject gameObject = component.gameObject;
                gameObject.SendMessage("OnStartCore");
                foreach (Component component2 in gameObject.GetComponentsInChildren<Component>())
                {
                    Debug.Log(component2.GetType().Assembly.GetName().Name);
                    ClassCache.assemblies.Add(component2.GetType().Assembly.GetName().Name);
                }
                break;
            }
            Debug.Log("no go");
        }
        this.sources.Init();
        if (!this.forceLangCode.IsEmpty())
        {
            this.langCode = this.forceLangCode;
        }
        else if (this.config == null)
        {
            Debug.Log("Config doesn't exist.");
            try
            {
                if (this.debug.enable || !SteamAPI.IsSteamRunning())
                {
                    BookList.dict = null;
                    this.ui.ShowLang();
                    return;
                }
                string currentGameLanguage = SteamApps.GetCurrentGameLanguage();
                if (!(currentGameLanguage == "chinese"))
                {
                    if (!(currentGameLanguage == "japanese"))
                    {
                        BookList.dict = null;
                        this.ui.ShowLang();
                        return;
                    }
                    this.langCode = "JP";
                }
                else
                {
                    this.langCode = "CN";
                }
            }
            catch (Exception message)
            {
                Debug.Log(message);
            }
        }
        if (this.debug.showSceneSelector || (Input.GetKey(KeyCode.LeftShift) && this.debug.enable))
        {
            this.ui.ShowSceneSelector();
            return;
        }
        this.Init();
    }
References config, debug, ModManager.disableMod, CoreDebug.enable, Init(), SourceManager.Init(), ModManager.Init(), ModManager.IsInitialized, ModManager.ListPluginObject, mods, ModManager.RefreshMods(), CoreDebug.showSceneSelector, sources, and ui.
Referenced by Start().
StopEventSystem() [1/2]
override void Core.StopEventSystem (Component c, Action action, float duration = 0::12f) inline
Definition at line 606 of file Core.cs.
    {
        this.eventSystem.enabled = false;
        c.transform.DOScale(new Vector3(1f, 0f, 1f), duration).OnKill(delegate
        {
            this.eventSystem.enabled = true;
        }).OnComplete(delegate
        {
            action();
        }).SetEase(Ease.Linear);
    }
StopEventSystem() [2/2]
override void Core.StopEventSystem (float duration = 0::2f) inline
Definition at line 618 of file Core.cs.
    {
        this.eventSystem.enabled = false;
        TweenUtil.Tween(duration, null, delegate()
        {
            this.eventSystem.enabled = true;
        });
    }
UnfreezeScreen()
override void Core.UnfreezeScreen () inline
Definition at line 596 of file Core.cs.
    {
        this.ui.UnfreezeScreen();
    }
Update()
void Core.Update () inline
Definition at line 229 of file Core.cs.
    {
        this.frame++;
        SoundManager.requestCount = 0;
        InputModuleEX.UpdateEventData();
        EInput.uiMousePosition = Input.mousePosition / this.ui.canvasScaler.scaleFactor;
        if (!this.initialized)
        {
            return;
        }
        this.ui.OnUpdate();
        this.debug.UpdateAlways();
        PoolManager.ignorePool = this.debug.ignorePool;
        if (this.screen.tileMap && !this.screen.tileMap.passBlock.mat.mainTexture)
        {
            this.textures.RefreshTextures();
        }
        if (this.useUImat)
        {
            Canvas.GetDefaultCanvasMaterial().CopyPropertiesFromMaterial(this.matUI);
        }
        Core.avgDelta += (Time.smoothDeltaTime - Core.delta) * 0.1f;
        Core.delta = Time.smoothDeltaTime;
        if (Core.delta > 0.1f)
        {
            Core.delta = 0.1f;
        }
        EInput.delta = (ButtonState.delta = Core.delta);
        bool? flag = this.lastFullScreen;
        bool fullScreen = Screen.fullScreen;
        if (!(flag.GetValueOrDefault() == fullScreen & flag != null))
        {
            int width = Display.main.systemWidth;
            int height = Display.main.systemHeight;
            if (this.config != null && this.config.graphic.fixedResolution)
            {
                width = this.config.graphic.w;
                height = this.config.graphic.h;
            }
            if (Screen.fullScreen)
            {
                Screen.SetResolution(width, height, true);
            }
            this.lastFullScreen = new bool?(Screen.fullScreen);
            this.nextResolutionUpdate = 0f;
        }
        if (this.nextResolutionUpdate <= 0f)
        {
            if (this.config != null && this.config.graphic.fixedResolution)
            {
                int w = this.config.graphic.w;
                int h = this.config.graphic.h;
                if (Screen.width != w || Screen.height != h)
                {
                    Screen.SetResolution(w, h, Screen.fullScreen);
                }
            }
            if (Screen.width != this.lastScreenWidth || Screen.height != this.lastScreenHeight)
            {
                this.OnChangeResolution();
            }
            this.nextResolutionUpdate = 0.1f;
        }
        else
        {
            this.nextResolutionUpdate -= Core.delta;
        }
        if (this.IsGameStarted)
        {
            this.game.OnUpdate();
            Core.gameDeltaNoPause = Core.delta * this.scene.actionMode.gameSpeed;
            Core.gameDelta = (FlockChild.delta = (this.ui.IsPauseGame ? 0f : Core.gameDeltaNoPause));
        }
        else
        {
            Core.gameDelta = 0f;
        }
        this.scene.OnUpdate();
        if (this.actionsNextFrame.Count > 0)
        {
            for (int i = this.actionsNextFrame.Count - 1; i >= 0; i--)
            {
                this.actionsNextFrame[i]();
                this.actionsNextFrame.RemoveAt(i);
            }
        }
    }
References Scene.actionMode, config, debug, delta, game, gameDeltaNoPause, ActionMode.gameSpeed, CoreConfig.graphic, CoreDebug.ignorePool, initialized, IsGameStarted, lastFullScreen, MeshPass.mat, matUI, nextResolutionUpdate, OnChangeResolution(), Game.OnUpdate(), Scene.OnUpdate(), BaseTileMap.passBlock, TextureManager.RefreshTextures(), scene, BaseTileMap.screen, screen, textures, BaseGameScreen.tileMap, ui, CoreDebug.UpdateAlways(), and useUImat.
Update100ms()
void Core.Update100ms () inline private
Definition at line 561 of file Core.cs.
    {
        if (!this.IsGameStarted)
        {
            return;
        }
        this.game.updater.Update100ms();
    }
Member Data Documentation
avgDelta
float Core.avgDelta static
Definition at line 695 of file Core.cs.
Colors
ColorProfile Core.Colors
Definition at line 727 of file Core.cs.
config
CoreConfig Core.config
Definition at line 744 of file Core.cs.
Referenced by OnApplicationFocus(), Start(), StartCase(), and Update().
debug
CoreDebug Core.debug
Definition at line 705 of file Core.cs.
Referenced by Awake(), OnApplicationFocus(), StartCase(), and Update().
delta
float Core.delta static
Definition at line 693 of file Core.cs.
Referenced by Update().
effects
EffectManager Core.effects
Definition at line 711 of file Core.cs.
game
Game Core.game
Definition at line 746 of file Core.cs.
Referenced by Awake(), and Update().
gamedata
GameData Core.gamedata
Definition at line 723 of file Core.cs.
gameDelta
float Core.gameDelta static
Definition at line 697 of file Core.cs.
gameDeltaNoPause
float Core.gameDeltaNoPause static
Definition at line 699 of file Core.cs.
Referenced by Update().
gameSetting
GameSetting Core.gameSetting
Definition at line 721 of file Core.cs.
initialized
bool Core.initialized
Definition at line 749 of file Core.cs.
Referenced by LateUpdate(), and Update().
Instance
new Core Core.Instance static
Definition at line 691 of file Core.cs.
Referenced by OnApplicationFocus(), and SetCurrent().
lastFullScreen
bool? Core.lastFullScreen private
Definition at line 751 of file Core.cs.
Referenced by Update().
matUI
Material Core.matUI
Definition at line 729 of file Core.cs.
Referenced by Awake(), and Update().
mods
ModManager Core.mods = new ModManager()
Definition at line 713 of file Core.cs.
Referenced by StartCase().
nextResolutionUpdate
float Core.nextResolutionUpdate private
Definition at line 753 of file Core.cs.
Referenced by Update().
pathManager
PathManager Core.pathManager
Definition at line 709 of file Core.cs.
pccs
PCCManager Core.pccs
Definition at line 715 of file Core.cs.
Referenced by Awake().
refs
CoreRef Core.refs
Definition at line 725 of file Core.cs.
scene
Scene Core.scene
Definition at line 739 of file Core.cs.
Referenced by Awake(), LateUpdate(), and Update().
screen
BaseGameScreen Core.screen
Definition at line 741 of file Core.cs.
Referenced by Awake(), and Update().
skins
SkinManager Core.skins
Definition at line 717 of file Core.cs.
skinTimer
float Core.skinTimer private
Definition at line 755 of file Core.cs.
sourceElement
SourceElement Core.sourceElement static private
Definition at line 703 of file Core.cs.
Referenced by GetElement().
sources
SourceManager Core.sources
Definition at line 707 of file Core.cs.
Referenced by OnApplicationFocus(), and StartCase().
spiked
bool Core.spiked static
Definition at line 701 of file Core.cs.
steam
Steam Core.steam
Definition at line 731 of file Core.cs.
Referenced by Awake(), and Start().
textures
TextureManager Core.textures = new TextureManager()
Definition at line 719 of file Core.cs.
Referenced by Awake(), OnApplicationFocus(), and Update().
trial
bool Core.trial
Definition at line 735 of file Core.cs.
ui
UI Core.ui
Definition at line 737 of file Core.cs.
Referenced by Awake(), StartCase(), and Update().
useUImat
bool Core.useUImat
Definition at line 733 of file Core.cs.
Referenced by Awake(), and Update().
Property Documentation
IsGameStarted
bool Core.IsGameStarted get
Definition at line 14 of file Core.cs.
    {
        get
        {
            return this.game != null && this.game.activeZone != null;
        }
    }
Referenced by OnApplicationFocus(), and Update().
uiScale
override float Core.uiScale get
Definition at line 22 of file Core.cs.
    {
        get
        {
            return this.ui.canvasScaler.scaleFactor;
        }
    }
The documentation for this class was generated from the following file:
Elin/Core.cs