Elin Decompiled Documentation: UIContextMenuManager Class Reference
UIContextMenuManager Class Reference
Public Member Functions
UIContextMenu Create (string menuName="ContextMenu", bool destroyOnHide=true)
Public Attributes
Canvas canvas
UIContextMenu currentMenu
bool showMenuOnRightClick = true
bool autoClose
Static Public Attributes
static UIContextMenuManager Instance
Properties
bool isActive [get]
Private Member Functions
void Awake ()
Detailed Description
Definition at line 3 of file UIContextMenuManager.cs.
Member Function Documentation
Awake()
void UIContextMenuManager.Awake () inline private
Definition at line 27 of file UIContextMenuManager.cs.
    {
        Instance = this;
    }
References Instance.
Create()
UIContextMenu UIContextMenuManager.Create (string menuName = "ContextMenu", bool destroyOnHide = true) inline
Definition at line 32 of file UIContextMenuManager.cs.
    {
        if ((bool)currentMenu)
        {
            currentMenu.Hide();
        }
        currentMenu = Util.Instantiate<UIContextMenu>(menuName, base.transform);
        currentMenu.destroyOnHide = destroyOnHide;
        if ((bool)currentMenu.logo)
        {
            currentMenu.logo.SetActive(enable: true);
        }
        return currentMenu;
    }
References currentMenu, UIContextMenu.Hide(), UIContextMenu.logo, and Util.
Referenced by UI.CreateContextMenu(), and UI.CreateContextMenuInteraction().
Member Data Documentation
autoClose
bool UIContextMenuManager.autoClose
Definition at line 13 of file UIContextMenuManager.cs.
Referenced by UIContextMenu.Hide().
canvas
Canvas UIContextMenuManager.canvas
Definition at line 5 of file UIContextMenuManager.cs.
currentMenu
UIContextMenu UIContextMenuManager.currentMenu
Definition at line 7 of file UIContextMenuManager.cs.
Referenced by Create().
Instance
UIContextMenuManager UIContextMenuManager.Instance static
Definition at line 9 of file UIContextMenuManager.cs.
Referenced by Awake(), UIContextMenu.Hide(), and Layer.UpdateInput().
showMenuOnRightClick
bool UIContextMenuManager.showMenuOnRightClick = true
Definition at line 11 of file UIContextMenuManager.cs.
Property Documentation
isActive
bool UIContextMenuManager.isActive get
Definition at line 15 of file UIContextMenuManager.cs.
    {
        get
        {
            if (currentMenu != null)
            {
                return !currentMenu.isDestroyed;
            }
            return false;
        }
    }
Referenced by Layer.UpdateInput().
The documentation for this class was generated from the following file:
Elin/Plugins.UI/UIContextMenuManager.cs