Elin Decompiled Documentation: ActThrow Class Reference
ActThrow Class Reference
Public Member Functions
override string GetText (string str="")
override bool CanPerform ()
override bool Perform ()
Public Member Functions inherited from Act
virtual CursorInfo GetCursorIcon (Card c)
virtual MultiSprite GetStateIcon ()
override Sprite GetSprite ()
virtual bool ShowMouseHint (Card c)
virtual bool IsValidTC (Card c)
virtual string GetHintText (string str="")
virtual string GetText (string str="")
virtual string GetTextSmall (Card c)
virtual Color GetActPlanColor ()
virtual bool Perform ()
virtual bool CanPerform ()
bool Perform (Chara _cc, Card _tc=null, Point _tp=null)
bool CanPerform (Chara _cc, Card _tc=null, Point _tp=null)
virtual bool IsToolValid ()
new void SetImage (Image image)
virtual void OnMarkMapHighlights ()
virtual bool ShouldMapHighlight (Point p)
virtual CursorInfo GetCursorIcon (Card c)
virtual MultiSprite GetStateIcon ()
override Sprite GetSprite ()
virtual bool ShowMouseHint (Card c)
virtual bool IsValidTC (Card c)
virtual string GetHintText (string str="")
virtual string GetText (string str="")
virtual string GetTextSmall (Card c)
virtual Color GetActPlanColor ()
virtual bool Perform ()
virtual bool CanPerform ()
bool Perform (Chara _cc, Card _tc=null, Point _tp=null)
bool CanPerform (Chara _cc, Card _tc=null, Point _tp=null)
virtual bool IsToolValid ()
new void SetImage (Image image)
virtual void OnMarkMapHighlights ()
virtual bool ShouldMapHighlight (Point p)
Public Member Functions inherited from Element
virtual SourceElement.Row GetSource ()
virtual int GetSourcePotential (int v)
virtual Sprite GetSprite ()
int GetMaterialSourceValue (Thing t, int v)
virtual int GetSourceValue (int v, int lv, SourceValueType type)
virtual Sprite GetIcon (string suffix="")
int SortVal (bool charaSheet=false)
virtual bool CanLink (ElementContainer owner)
bool HasTag (string tag)
void SetImage (Image i)
virtual string GetDetail ()
bool IsFactionElement (Chara c)
Element GetParent (Card c)
void WriteNote (UINote n, ElementContainer owner=null, Action< UINote > onWriteNote=null)
void WriteNoteWithRef (UINote n, ElementContainer owner, Action< UINote > onWriteNote, Element refEle)
void _WriteNote (UINote n, Chara c, Act act)
void _WriteNote (UINote n, ElementContainer owner, Action< UINote > onWriteNote, bool isRef, bool addHeader=true)
virtual void OnWriteNote (UINote n, ElementContainer owner)
virtual void OnChangeValue ()
void CheckLevelBonus (ElementContainer owner, UINote n=null)
int GetSortVal (UIList.SortMode m)
virtual Act.Cost GetCost (Chara c)
virtual int GetPower (Card c)
virtual void SetTextValue (UIText text)
virtual SourceElement.Row GetSource ()
virtual int GetSourcePotential (int v)
virtual Sprite GetSprite ()
int GetMaterialSourceValue (Thing t, int v)
virtual int GetSourceValue (int v, int lv, SourceValueType type)
virtual Sprite GetIcon (string suffix="")
int SortVal (bool charaSheet=false)
virtual bool CanLink (ElementContainer owner)
bool HasTag (string tag)
void SetImage (Image i)
virtual string GetDetail ()
bool IsFactionElement (Chara c)
Element GetParent (Card c)
void WriteNote (UINote n, ElementContainer owner=null, Action< UINote > onWriteNote=null)
void WriteNoteWithRef (UINote n, ElementContainer owner, Action< UINote > onWriteNote, Element refEle)
void _WriteNote (UINote n, Chara c, Act act)
void _WriteNote (UINote n, ElementContainer owner, Action< UINote > onWriteNote, bool isRef, bool addHeader=true)
virtual void OnWriteNote (UINote n, ElementContainer owner)
virtual void OnChangeValue ()
void CheckLevelBonus (ElementContainer owner, UINote n=null)
int GetSortVal (UIList.SortMode m)
virtual Act.Cost GetCost (Chara c)
virtual int GetPower (Card c)
virtual void SetTextValue (UIText text)
Static Public Member Functions
static bool CanThrow (Chara c, Thing t, Card target, Point p=null)
static EffectIRenderer Throw (Card c, Point p, Thing t, ThrowMethod method=ThrowMethod.Default, float failChance=0f)
static EffectIRenderer Throw (Card c, Point p, Card target, Thing t, ThrowMethod method=ThrowMethod.Default)
Static Public Member Functions inherited from Act
static void SetReference (Chara _cc, Card _tc=null, Point _tp=null)
static void SetTool (Thing t)
static void SetReference (Chara _cc, Card _tc=null, Point _tp=null)
static void SetTool (Thing t)
Static Public Member Functions inherited from Element
static string GetName (string alias)
static SourceElement.Row Get (int id)
static Dictionary< int, int > GetElementMap (int[] list)
static Dictionary< int, int > GetElementMap (int[] list, Dictionary< int, int > map)
static SourceElement.Row GetRandomElement (int lv=1)
static Element Create (int id, int v=0)
static Element Create (string id, int v=1)
static int GetId (string alias)
static int GetResistLv (int v)
static int GetResistDamage (int dmg, int v)
static string GetName (string alias)
static SourceElement.Row Get (int id)
static Dictionary< int, int > GetElementMap (int[] list)
static Dictionary< int, int > GetElementMap (int[] list, Dictionary< int, int > map)
static SourceElement.Row GetRandomElement (int lv=1)
static Element Create (int id, int v=0)
static Element Create (string id, int v=1)
static int GetId (string alias)
static int GetResistLv (int v)
static int GetResistDamage (int dmg, int v)
Static Public Member Functions inherited from EClass
static int rnd (int a)
static int curve (int a, int start, int step, int rate=75)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Public Attributes
Thing target
Chara pcTarget
Public Attributes inherited from Element
SourceElement.Row _source
int id
int vBase
int vExp
int vPotential
int vTempPotential
int vLink
int vSource
int vSourcePotential
ElementContainer owner
Properties
override bool CanPressRepeat [get]
override TargetType TargetType [get]
override int PerformDistance [get]
Properties inherited from Act
override bool ShowPotential [get]
override bool UsePotential [get]
override bool ShowRelativeAttribute [get]
virtual CursorInfo CursorIcon [get]
virtual string ID [get]
virtual bool IsAct [get]
virtual bool WillEndTurn [get]
virtual bool CloseLayers [get]
virtual int LeftHand [get]
virtual int RightHand [get]
virtual int ElementPowerMod [get]
virtual bool ShowMapHighlight [get]
virtual bool ShowMapHighlightBlock [get]
virtual bool PickHeldOnStart [get]
virtual bool DropHeldOnStart [get]
virtual bool CanPressRepeat [get]
virtual bool CanAutofire [get]
virtual bool ResetAxis [get]
virtual bool RequireTool [get]
virtual bool IsHostileAct [get]
virtual bool HideRightInfo [get]
virtual bool HaveLongPressAction [get]
virtual float Radius [get]
virtual int PerformDistance [get]
virtual int MaxRadius [get]
virtual TargetType TargetType [get]
virtual bool LocalAct [get]
virtual bool CanRapidFire [get]
virtual float RapidDelay [get]
virtual bool ShowAuto [get]
virtual bool IsCrime [get]
Properties inherited from Element
SourceElement.Row source [get]
virtual int DisplayValue [get]
virtual int MinValue [get]
int Value [get]
int ValueWithoutLink [get]
virtual int MinPotential [get]
int Potential [get]
virtual bool CanGainExp [get]
bool IsFlag [get]
virtual string Name [get]
virtual string FullName [get]
virtual int ExpToNext [get]
virtual bool UseExpMod [get]
virtual int CostTrain [get]
virtual int CostLearn [get]
virtual bool ShowXP [get]
virtual bool ShowMsgOnValueChanged [get]
virtual bool ShowValue [get]
virtual bool ShowPotential [get]
virtual bool UsePotential [get]
virtual bool PotentialAsStock [get]
virtual bool ShowRelativeAttribute [get]
virtual bool ShowBonuses [get]
virtual string ShortName [get]
bool IsGlobalElement [get]
bool IsFactionWideElement [get]
bool IsPartyWideElement [get]
virtual bool ShowEncNumber [get]
bool IsTrait [get]
bool IsFoodTrait [get]
bool IsFoodTraitMain [get]
bool IsMainAttribute [get]
Act act [get]
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Additional Inherited Members
Public Types inherited from Act
enum CostType {
None , MP , SP , None ,
MP , SP
}
enum CostType {
None , MP , SP , None ,
MP , SP
}
Static Public Attributes inherited from Act
static Chara CC
static Card TC
static Point TP = new Point()
static Thing TOOL
static int powerMod = 100
static bool forcePt
Static Public Attributes inherited from Element
const int Div = 5
static Element Void = new Element()
static int[] List_MainAttributes
static int[] List_MainAttributesMajor
static int[] List_Body
static int[] List_Mind
static List< SourceElement.Row > ListElements = new List<SourceElement.Row>()
static List< SourceElement.Row > ListAttackElements = new List<SourceElement.Row>()
Static Public Attributes inherited from EClass
static Core core
Static Package Functions inherited from Element
static string< _WriteNote > g__Calc (ref Element.<>c__DisplayClass103_0 A_0)
Detailed Description
Definition at line 3 of file ActThrow.cs.
Member Function Documentation
CanPerform()
override bool ActThrow.CanPerform () inline virtual
Reimplemented from Act.
Definition at line 25 of file ActThrow.cs.
    {
        if (pcTarget != null && pcTarget.ExistsOnMap)
        {
            Act.TP.Set(pcTarget.pos);
        }
        if (!Act.TP.IsHidden)
        {
            return Act.CC.CanSeeLos(Act.TP);
        }
        return false;
    }
References Chara.CanSeeLos(), Act.CC, Card.ExistsOnMap, Point.IsHidden, pcTarget, Card.pos, Point.Set(), and Act.TP.
Referenced by GoalCombat.TryThrow().
CanThrow()
static bool ActThrow.CanThrow (Chara c, Thing t, Card target, Point p = null) inline static
Definition at line 60 of file ActThrow.cs.
    {
        if (t == null)
        {
            return false;
        }
        if (t.c_isImportant && !t.HasElement(410))
        {
            return false;
        }
        if (p == null && target != null && target.ExistsOnMap)
        {
            p = target.pos;
        }
        if (p == null)
        {
            return false;
        }
        if ((p.HasBlock && !p.cell.hasDoor && p.sourceBlock.tileType.IsBlockPass) || p.Equals(EClass.pc.pos) || t.trait.CanExtendBuild || t.trait.CanOnlyCarry)
        {
            return false;
        }
        if (c.IsPC && EClass.core.config.game.shiftToUseNegativeAbilityOnSelf && !EInput.isShiftDown && !(t.trait is TraitDrink))
        {
            Card card = target ?? p.FindAttackTarget();
            if (card != null && card.IsPCFactionOrMinion)
            {
                return false;
            }
        }
        return true;
    }
References Card.c_isImportant, Trait.CanExtendBuild, Trait.CanOnlyCarry, Core.config, EClass.core, Card.ExistsOnMap, CoreConfig.game, Card.HasElement(), Chara.IsPC, Card.IsPCFactionOrMinion, EClass.pc, Card.pos, CoreConfig.GameConfig.shiftToUseNegativeAbilityOnSelf, target, and Card.trait.
Referenced by AM_Adv._OnUpdateInput(), AI_PracticeDummy.CreateProgress(), HotItemHeld.TrySetAct(), and HotItemHeld.TrySetToolAct().
GetText()
override string ActThrow.GetText (string str = "") inline virtual
Reimplemented from Act.
Definition at line 15 of file ActThrow.cs.
    {
        string text = "";
        if (target != null && pcTarget != null && target.trait is TraitMonsterBall && pcTarget.LV > target.LV)
        {
            text = " " + "mb_invalidLV".lang();
        }
        return base.GetText(str) + text;
    }
References Card.LV, pcTarget, target, and Card.trait.
Perform()
override bool ActThrow.Perform () inline virtual
Reimplemented from Act.
Definition at line 38 of file ActThrow.cs.
    {
        if (target == null)
        {
            target = Act.TC as Thing;
        }
        if (target == null || target.isDestroyed || target.GetRootCard() != Act.CC)
        {
            return false;
        }
        if (pcTarget != null)
        {
            if (!pcTarget.ExistsOnMap)
            {
                return false;
            }
            Act.TP.Set(pcTarget.pos);
        }
        Throw(Act.CC, Act.TP, target.HasElement(410) ? target : target.Split(1));
        return true;
    }
References Act.CC, Card.ExistsOnMap, Card.GetRootCard(), Card.HasElement(), Card.isDestroyed, pcTarget, Card.pos, Point.Set(), Card.Split(), target, Throw, and Act.TP.
Referenced by AM_Adv._OnUpdateInput().
Throw() [1/2]
static EffectIRenderer ActThrow.Throw (Card c, Point p, Card target, Thing t, ThrowMethod method = ThrowMethod::Default) inline static
Definition at line 106 of file ActThrow.cs.
    {
        if (t.parent != EClass._zone && !t.HasElement(410))
        {
            EClass._zone.AddCard(t, c.pos).KillAnime();
        }
        Act.TP.Set(p);
        Act.TC = target;
        if (t.trait.ThrowType == ThrowType.Snow)
        {
            t.dir = EClass.rnd(2);
            c.Talk("snow_throw");
            if (EClass.rnd(2) == 0)
            {
                Act.TC = null;
            }
        }
        c.Say("throw", c, t.GetName(NameStyle.Full, 1));
        c.LookAt(p);
        c.renderer.NextFrame();
        c.PlaySound("throw");
        EffectIRenderer result = null;
        if (c.isSynced || p.IsSync)
        {
            result = Effect.Get<EffectIRenderer>((t.trait is TraitBall) ? "throw_ball" : "throw").Play((c.isChara && c.Chara.host != null) ? c.Chara.host : c, t, c.pos, p, 0.2f);
            t.renderer.SetFirst(first: false, c.renderer.position);
        }
        if (!t.HasElement(410))
        {
            t._Move(p);
        }
        if (!t.trait.CanBeDestroyed)
        {
            c.PlaySound("miss");
            return result;
        }
        ThrowType throwType = t.trait.ThrowType;
        if ((uint)(throwType - 1) <= 1u)
        {
            Msg.Say("shatter");
        }
        bool flag = method == ThrowMethod.Reward;
        bool flag2 = method == ThrowMethod.Default;
        switch (t.trait.ThrowType)
        {
        case ThrowType.Explosive:
            flag = true;
            t.c_uidRefCard = c.uid;
            t.Die(null, c, AttackSource.Throw);
            break;
        case ThrowType.Vase:
            t.Die(null, null, AttackSource.Throw);
            break;
        case ThrowType.Potion:
            flag = true;
            if (Act.TC != null)
            {
                Act.TC.Say("throw_hit", t, Act.TC);
            }
            Act.TP.ModFire(-50);
            if (Act.TC != null && Act.TC.isChara)
            {
                if (t.trait.CanDrink(Act.TC.Chara))
                {
                    t.trait.OnDrink(Act.TC.Chara);
                }
                flag2 = t.IsNegativeGift;
                Act.TC.Chara.AddCondition<ConWet>();
            }
            else
            {
                t.trait.OnThrowGround(c.Chara, Act.TP);
            }
            t.Die(null, null, AttackSource.Throw);
            c.ModExp(108, 50);
            break;
        case ThrowType.Snow:
            flag = true;
            flag2 = false;
            if (Act.TC != null && Act.TC.isChara)
            {
                Act.TC.Say("throw_hit", t, Act.TC);
                if (EClass.rnd(2) == 0)
                {
                    c.Talk("snow_hit");
                }
                Act.TC.Chara.AddCondition<ConWet>(50);
                t.Die(null, null, AttackSource.Throw);
                c.ModExp(108, 50);
            }
            break;
        case ThrowType.Ball:
            flag = true;
            flag2 = false;
            if (Act.TC != null && Act.TC.isChara)
            {
                Act.TC.Say("throw_hit", t, Act.TC);
                if (EClass.rnd(2) == 0)
                {
                    c.Talk("snow_hit");
                }
                Act.TC.Say("ball_hit");
                Act.TC.Chara?.Pick(t);
                c.ModExp(108, 50);
            }
            break;
        case ThrowType.Flyer:
            flag = true;
            flag2 = false;
            if (Act.TC != null && Act.TC.isChara && c.isChara)
            {
                Act.TC.Say("throw_hit", t, Act.TC);
                c.Chara.GiveGift(Act.TC.Chara, t);
                c.ModExp(108, 50);
            }
            break;
        case ThrowType.MonsterBall:
        {
            flag = true;
            flag2 = false;
            TraitMonsterBall traitMonsterBall = t.trait as TraitMonsterBall;
            if (traitMonsterBall.chara != null)
            {
                if (traitMonsterBall.IsLittleBall && !(EClass._zone is Zone_LittleGarden))
                {
                    break;
                }
                Chara _c = EClass._zone.AddCard(traitMonsterBall.chara, p).Chara;
                _c.PlayEffect("identify");
                t.Die();
                if (traitMonsterBall.IsLittleBall && _c.id == "littleOne")
                {
                    _c.orgPos = c.pos.Copy();
                    Chara chara = _c;
                    Hostility c_originalHostility = (_c.hostility = Hostility.Neutral);
                    chara.c_originalHostility = c_originalHostility;
                    EClass._zone.ModInfluence(5);
                    _c.PlaySound("chime_angel");
                    EClass.core.actionsNextFrame.Add(delegate
                    {
                        _c.Talk("little_saved");
                    });
                    EClass.player.flags.little_saved = true;
                    EClass.player.little_saved++;
                }
                else
                {
                    _c.MakeAlly();
                }
            }
            else
            {
                if (Act.TC == null || !Act.TC.isChara)
                {
                    break;
                }
                Act.TC.Say("throw_hit", t, Act.TC);
                Chara chara2 = Act.TC.Chara;
                if (traitMonsterBall.IsLittleBall)
                {
                    if (chara2.id != "littleOne" || EClass._zone is Zone_LittleGarden || EClass._zone.IsUserZone)
                    {
                        Msg.Say("monsterball_invalid");
                        break;
                    }
                }
                else
                {
                    if (!chara2.trait.CanBeTamed || EClass._zone.IsUserZone)
                    {
                        Msg.Say("monsterball_invalid");
                        break;
                    }
                    if (chara2.LV > traitMonsterBall.owner.LV)
                    {
                        Msg.Say("monsterball_lv");
                        break;
                    }
                    if (!EClass.debug.enable && chara2.hp > chara2.MaxHP / 10)
                    {
                        Msg.Say("monsterball_hp");
                        break;
                    }
                }
                Msg.Say("monsterball_capture", c, chara2);
                chara2.PlaySound("identify");
                chara2.PlayEffect("identify");
                t.ChangeMaterial("copper");
                if (chara2.IsLocalChara)
                {
                    Debug.Log("Creating Replacement NPC for:" + chara2);
                    EClass._map.deadCharas.Add(chara2.CreateReplacement());
                }
                traitMonsterBall.chara = chara2;
                EClass._zone.RemoveCard(chara2);
                chara2.homeZone = null;
                c.ModExp(108, 100);
            }
            break;
        }
        }
        if (t.trait is TraitDye)
        {
            t.trait.OnThrowGround(c.Chara, Act.TP);
        }
        if (!flag && Act.TC != null)
        {
            AttackProcess.Current.Prepare(c.Chara, t, Act.TC, Act.TP, 0, _isThrow: true);
            if (AttackProcess.Current.Perform(0, hasHit: false))
            {
                if (Act.TC.IsAliveInCurrentZone && t.trait is TraitErohon && Act.TC.id == t.c_idRefName)
                {
                    Act.TC.Chara.OnGiveErohon(t);
                }
                if (!t.isDestroyed && t.trait.CanBeDestroyed && !t.IsFurniture && !t.category.IsChildOf("instrument") && !t.IsUnique && !t.HasElement(410))
                {
                    t.Destroy();
                }
            }
            else
            {
                c.PlaySound("miss");
            }
        }
        if (EClass.rnd(2) == 0)
        {
            c.Chara.RemoveCondition<ConInvisibility>();
        }
        if (Act.TC != null)
        {
            if (flag2)
            {
                c.Chara.DoHostileAction(Act.TC);
            }
            if ((Act.TC.trait.CanBeAttacked || Act.TC.IsRestrainedResident) && EClass.rnd(2) == 0)
            {
                c.Chara.stamina.Mod(-1);
            }
        }
        if (t.HasElement(410) && Act.TC != null && Act.CC == EClass.pc && !(Act.CC.ai is AI_PracticeDummy) && (Act.TC.trait is TraitTrainingDummy || Act.TC.IsRestrainedResident) && Act.CC.stamina.value > 0)
        {
            Act.CC.SetAI(new AI_PracticeDummy
            {
                target = Act.TC,
                throwItem = t
            });
        }
        return result;
    }
References EClass._map, Card._Move(), EClass._zone, Zone.AddCard(), Chara.AddCondition(), Card.c_idRefName, Trait.CanBeAttacked, Trait.CanBeDestroyed, TraitChara.CanBeTamed, Trait.CanDrink(), Card.category, Act.CC, Card.ChangeMaterial(), Card.Chara, TraitMonsterBall.chara, Point.Copy(), EClass.core, Chara.CreateReplacement(), AttackProcess.Current, Map.deadCharas, EClass.debug, Card.Destroy(), Card.Die(), Chara.DoHostileAction(), CoreDebug.enable, Effect.Get(), Thing.GetName(), Chara.GiveGift(), Card.HasElement(), Chara.host, Card.hp, Card.id, Card.IsAliveInCurrentZone, Card.isChara, Card.isDestroyed, Card.IsFurniture, TraitMonsterBall.IsLittleBall, Chara.IsLocalChara, Card.IsNegativeGift, Card.IsRestrainedResident, Point.IsSync, Card.isSynced, Zone.IsUserZone, Card.KillAnime(), Player.little_saved, Card.LookAt(), Card.LV, Chara.MakeAlly(), Chara.MaxHP, Stats.Mod(), Card.ModExp(), Point.ModFire(), Zone.ModInfluence(), CardRenderer.NextFrame(), Trait.OnDrink(), Chara.OnGiveErohon(), Trait.OnThrowGround(), Trait.owner, Card.parent, AttackProcess.Perform(), Chara.Pick(), EffectIRenderer.Play(), Card.PlayEffect(), EClass.player, Card.PlaySound(), Card.pos, CardRenderer.position, AttackProcess.Prepare(), Zone.RemoveCard(), Card.renderer, EClass.rnd(), Msg.Say(), Card.Say(), Point.Set(), Chara.SetAI(), Chara.stamina, Card.Talk(), target, Act.TC, Trait.ThrowType, Act.TP, Card.trait, Chara.trait, and Card.uid.
Throw() [2/2]
static EffectIRenderer ActThrow.Throw (Card c, Point p, Thing t, ThrowMethod method = ThrowMethod::Default, float failChance = 0f) inline static
Definition at line 93 of file ActThrow.cs.
    {
        if (failChance > EClass.rndf(1f))
        {
            Point randomPoint = p.GetRandomPoint(1);
            if (randomPoint != null && !randomPoint.Equals(c.pos))
            {
                p = randomPoint;
            }
        }
        return Throw(c, p, p.FindAttackTarget(), t, method);
    }
References Point.Equals(), Point.FindAttackTarget(), Point.GetRandomPoint(), Card.pos, EClass.rndf(), and Throw.
Referenced by AI_PracticeDummy.CreateProgress(), Chara.DoHostileAction(), ActEffect.Proc(), AI_Idle.Run(), AI_PlayMusic.ThrowReward(), and GoalCombat.TryThrow().
Member Data Documentation
pcTarget
Chara ActThrow.pcTarget
Definition at line 7 of file ActThrow.cs.
Referenced by CanPerform(), GetText(), and Perform().
target
Thing ActThrow.target
Definition at line 5 of file ActThrow.cs.
Referenced by CanThrow(), GetText(), ActRanged.Perform(), Perform(), and Throw().
Property Documentation
CanPressRepeat
override bool ActThrow.CanPressRepeat get
Definition at line 9 of file ActThrow.cs.
PerformDistance
override int ActThrow.PerformDistance get
Definition at line 13 of file ActThrow.cs.
TargetType
override TargetType ActThrow.TargetType get
Definition at line 11 of file ActThrow.cs.
The documentation for this class was generated from the following file:
Elin/ActThrow.cs