Elin Decompiled Documentation: UIText Class Reference
UIText Class Reference
Public Member Functions
void ApplySkin ()
void SetText (string s)
void SetText (string s, Color c)
void SetText (string s, FontColor c)
UIText SetSize (int a)
void SetColor (FontColor c)
void SetLang (string idLang)
void OnChangeLanguage ()
void ApplySkin ()
Public Attributes
string lang
BaseSkinRoot skinRoot
FontType fontType
FontColor fontColor
SkinType skinType
int size
HyphenationJpn hyphenation
UIButton button
Typewriter typewriter
float orgSpacing
Color orgColor = Color.white
Static Public Attributes
static int globalSizeMod
Protected Member Functions
override void Awake ()
override void OnEnable ()
Private Member Functions
void OnSetText ()
Detailed Description
Definition at line 5 of file UIText.cs.
Member Function Documentation
ApplySkin()
void UIText.ApplySkin () inline
Implements IUISkin.
Definition at line 38 of file UIText.cs.
    {
        if (!Application.isPlaying)
        {
            return;
        }
        SkinManager instance = SkinManager.Instance;
        int num = size + 19 + globalSizeMod;
        SkinManager.FontSet fontSet = instance.fontSet;
        FontSource fontSource = instance.FontList[0];
        if (fontType != FontType.DontChange)
        {
            int num2 = 0;
            switch (fontType)
            {
            case FontType.UI:
                fontSource = fontSet.ui.source;
                num2 = Mathf.Min(fontSet.ui.sizeMod, SkinManager.LimitFontSizeMod_UI);
                break;
            case FontType.Widget:
                fontSource = fontSet.widget.source;
                num2 = fontSet.widget.sizeMod;
                break;
            case FontType.Chatbox:
                fontSource = fontSet.chatbox.source;
                num2 = fontSet.chatbox.sizeMod;
                break;
            case FontType.Balloon:
                fontSource = fontSet.balloon.source;
                num2 = fontSet.balloon.sizeMod;
                break;
            case FontType.Dialog:
                fontSource = fontSet.dialog.source;
                num2 = fontSet.dialog.sizeMod;
                break;
            case FontType.News:
                fontSource = fontSet.news.source;
                num2 = fontSet.news.sizeMod;
                break;
            }
            if (fontSource == null)
            {
                fontSource = instance.FontList[0];
            }
            base.font = fontSource.font;
            num += fontSource.sizeFix + num2;
        }
        if (base.fontSize != num)
        {
            base.fontSize = num;
        }
        if (base.resizeTextForBestFit)
        {
            base.resizeTextMaxSize = base.fontSize;
        }
        if ((bool)button && (bool)button.skinRoot)
        {
            SkinAsset_Button skinAsset_Button = button.skinRoot.GetButton();
            if (fontColor != 0)
            {
                this.color = skinAsset_Button.textColor;
            }
            Shadow component = GetComponent<Shadow>();
            if (skinAsset_Button.textShadow)
            {
                if ((bool)component)
                {
                    component.enabled = true;
                    component.effectColor = skinAsset_Button.textShadowColor;
                }
            }
            else if ((bool)component)
            {
                component.enabled = false;
            }
            return;
        }
        if (orgSpacing == 0f)
        {
            orgSpacing = base.lineSpacing;
        }
        if (fontColor == FontColor.DontChange && orgColor == Color.white)
        {
            orgColor = this.color;
        }
        BaseSkinRoot obj = skinRoot ?? SkinManager.CurrentSkin;
        SkinColorProfile colors = obj.GetColors(skinType);
        float num3 = 0.5f;
        bool flag = fontColor == FontColor.DontChange;
        float num4 = 1f + (flag ? 0f : colors.contrast) + fontSource.contrast;
        obj.ApplySkin(this, fontSource);
        Color color = (flag ? orgColor : colors.GetTextColor(fontColor));
        if (base.fontStyle == FontStyle.Bold)
        {
            if (fontSource.alwaysBold)
            {
                base.fontStyle = FontStyle.Normal;
            }
            else
            {
                color.a *= fontSource.boldAlpha;
            }
        }
        num3 = ((!(color.r + color.g + color.b > 1.5f)) ? (0.5f - (flag ? 0f : colors.strength) - (Lang.isJP ? (fontSource.strength + fontSource.strengthFixJP) : fontSource.strength)) : (0.5f + (flag ? 0f : colors.strength) + (Lang.isJP ? (fontSource.strength + fontSource.strengthFixJP) : fontSource.strength)));
        color.r = (color.r - 0.5f) * num4 + num3;
        color.g = (color.g - 0.5f) * num4 + num3;
        color.b = (color.b - 0.5f) * num4 + num3;
        this.color = color;
        base.lineSpacing = orgSpacing * fontSource.lineSpacing;
        _ = (bool)hyphenation;
    }
References FontSource.alwaysBold, BaseSkinRoot.ApplySkin(), SkinManager.FontSet.balloon, FontSource.boldAlpha, button, SkinManager.FontSet.chatbox, Color, FontSource.contrast, SkinColorProfile.contrast, SkinManager.CurrentSkin, SkinManager.FontSet.dialog, FontSource.font, fontColor, SkinManager.FontList, SkinManager.fontSet, fontType, BaseSkinRoot.GetButton(), BaseSkinRoot.GetColors(), SkinColorProfile.GetTextColor(), globalSizeMod, hyphenation, SkinManager.Instance, Lang.isJP, SkinManager.LimitFontSizeMod_UI, FontSource.lineSpacing, SkinManager.FontSet.news, orgColor, orgSpacing, size, SkinManager.FontData.sizeMod, UIButton.skinRoot, skinRoot, skinType, SkinManager.FontData.source, FontSource.strength, SkinColorProfile.strength, FontSource.strengthFixJP, SkinAsset_Button.textColor, SkinAsset_Button.textShadow, SkinAsset_Button.textShadowColor, SkinManager.FontSet.ui, and SkinManager.FontSet.widget.
Referenced by Awake(), SetColor(), SkinManager.SetFonts(), SetSize(), DialogDrama.SetText(), and SetText().
Awake()
override void UIText.Awake () inline protected
Definition at line 32 of file UIText.cs.
    {
        ApplySkin();
        base.Awake();
    }
References ApplySkin().
OnChangeLanguage()
void UIText.OnChangeLanguage () inline
Definition at line 246 of file UIText.cs.
    {
        if (!string.IsNullOrEmpty(lang))
        {
            text = Lang.Get(lang);
        }
    }
References Lang.Get(), and lang.
OnEnable()
override void UIText.OnEnable () inline protected
Definition at line 150 of file UIText.cs.
    {
        base.OnEnable();
        if (!string.IsNullOrEmpty(lang))
        {
            m_Text = Lang.Get(lang);
        }
    }
References Lang.Get(), and lang.
OnSetText()
void UIText.OnSetText () inline private
Definition at line 219 of file UIText.cs.
    {
        if ((bool)typewriter)
        {
            typewriter.OnSetText();
        }
    }
References Typewriter.OnSetText(), and typewriter.
Referenced by SetText().
SetColor()
void UIText.SetColor (FontColor c) inline
Definition at line 234 of file UIText.cs.
    {
        fontColor = c;
        ApplySkin();
    }
References ApplySkin(), and fontColor.
Referenced by ContentChronicle.OnSwitchContent(), ContentHomeLog.RefreshLog(), and UIHomeInfo.RefreshReport().
SetLang()
void UIText.SetLang (string idLang) inline
Definition at line 240 of file UIText.cs.
    {
        lang = idLang;
        text = Lang.Get(lang);
    }
References Lang.Get(), and lang.
Referenced by Window.AddBottomButton(), Window.BuildTabs(), UIButtonLR.SelectOption(), UIButtonLR.SetOptions(), UIButtonLR.SetOptions< T >(), and UIHeader.Start().
SetSize()
UIText UIText.SetSize (int a) inline
Definition at line 227 of file UIText.cs.
    {
        size = a;
        ApplySkin();
        return this;
    }
References ApplySkin(), and size.
Referenced by ButtonGrid.WriteReqMat(), and Recipe.WriteReqSkill().
SetText() [1/3]
void UIText.SetText (string s) inline
Definition at line 159 of file UIText.cs.
    {
        if (s == null)
        {
            s = "";
        }
        if ((bool)hyphenation)
        {
            if (Lang.setting.hyphenation)
            {
                if (hyphenation.evaluateLate)
                {
                    BaseCore.Instance.actionsLateUpdate.Add(delegate
                    {
                        if (this != null)
{
                            hyphenation._SetText(s, Lang.setting.hyphenation);
                            hyphenation.RebuildLayoutTo<Canvas>();
                        }
                    });
                }
                else
                {
                    hyphenation._SetText(s, Lang.setting.hyphenation);
                }
            }
            else
            {
                base.horizontalOverflow = HorizontalWrapMode.Wrap;
                text = s;
            }
        }
        else
        {
            text = s;
        }
        lang = null;
        OnSetText();
    }
References HyphenationJpn._SetText(), BaseCore.actionsLateUpdate, HyphenationJpn.evaluateLate, LangSetting.hyphenation, hyphenation, BaseCore.Instance, lang, OnSetText(), and Lang.setting.
Referenced by Dialog._Confetti(), UIAutoTurn._Update(), Element._WriteNote(), UICurrency.Add(), WidgetInspector.AddButton(), WidgetInspector.AddLog(), WindowChara.AddNeeds(), LayerFaith.AddReligion(), WindowChara.AddStatus(), UINote.AddText(), ActionHint.AddToggle(), UINote.AddTopic(), MsgBlock.Append(), MsgLine.Append(), Dialog.Choice(), ItemGachaResult.Confirm(), Dialog.CreateNarration(), UIItem.Hyphenate(), BuildMenu.Init(), DramaEventEndRoll.Init(), Dialog.Keymap(), Dialog.List< TValue >(), UICharaMaker.ListDifficulties(), UICharaMaker.ListModes(), Dialog.Ok(), UIQueue.OnAdd(), LayerNewspaper.OnClickPage(), LayerMod.OnInit(), LayerWorldSetting.OnInit(), NotificationBuff.OnRefresh(), ContentFaction.OnSwitchContent(), ContentKeyItem.OnSwitchContent(), ContentQuest.OnSwitchContent(), LayerConfig.OnSwitchContent(), InvOwner.OnWriteNote(), WidgetCurrentTool.RebuildSlots(), ButtonElement.Refresh(), ButtonResourceTrack.Refresh(), ButtonRoster.Refresh(), ContentGallery.Refresh(), ItemCulture.Refresh(), ItemQuestTracker.Refresh(), LayerTravel.Refresh(), PartialMapMenu.Refresh(), UICharaMaker.Refresh(), UIInspector.Refresh(), UIRecipeInfo.Refresh(), WindowCharaMini.Refresh(), UIRecipeInfo.RefreshBalance(), UIMagicChest.RefreshBottom(), LayerEditPortrait.RefreshButtons(), LayerNewspaper.RefreshChat(), LayerDragGrid.RefreshCost(), WindowChara.RefreshEquipment(), ContentCodex.RefreshInfo(), ContentHomeReport.RefreshInfo(), UIHomeInfo.RefreshInfo(), LayerLoadGame.RefreshInfo(), DropdownRecipe.RefreshLabel(), ContentCodex.RefreshList(), LayerEditPortrait.RefreshList(), LayerLoadGame.RefreshList(), UIInventory.RefreshList(), UIRecipeInfo.RefreshList(), LayerNewspaper.RefreshNews(), WindowChara.RefreshNote(), ContentPolicy.RefreshPolicyIcons(), LayerPolicy.RefreshPolicyIcons(), ContentPolicy.RefreshPolicyList(), LayerPolicy.RefreshPolicyList(), LayerQuestBoard.RefreshQuest(), LayerQuestBoard.RefreshRanking(), ContentConfigOther.RefreshRewardCode(), LayerGlobalMap.RefreshSummary(), UIBook.RefreshTopics(), LayerNewspaper.RefreshVote(), WidgetSearch.RefreshWords(), ContentKeyItem.SelectItem(), ContentQuest.SelectQuest(), ButtonAbility.SetAct(), UIRecipeInfo.SetArea(), CharaBody.SetBodyIndexText(), Window.SetCaption(), ButtonGeneral.SetCard(), ItemGeneral.SetChara(), UICharaMaker.SetChara(), ItemGachaResult.SetChara(), ButtonChara.SetChara(), ButtonElement.SetGrid(), ItemGeneral.SetMainText(), Trait.SetMainText(), TraitAbility.SetMainText(), TraitToolRange.SetMainText(), ItemQuest.SetQuest(), ItemGeneral.SetSubText(), ItemGeneral.SetSubText2(), BaseSticky.SetText(), DialogDrama.SetText(), PopfabText.SetText(), UIHeader.SetText(), ActionHint.SetText(), SetText(), PopItemText.SetText(), BaseStats.SetText(), Recipe.SetTextDifficulty(), FactionRelation.SetTextHostility(), Religion.SetTextRelation(), UIItem.SetTopic(), TerrainMenu.Show(), WidgetPopup.Show(), LayerShippingResult.Show(), UIBook.Show(), LayerInteraction.ShowPage(), Thing.ShowSplitMenu2(), WidgetInspector.SwitchPage(), Dialog.TryWarn(), Chara.WriteNote(), Thing.WriteNote(), and Dialog.YesNo().
SetText() [2/3]
void UIText.SetText (string s, Color c) inline
Definition at line 199 of file UIText.cs.
    {
        SetText(s);
        fontColor = FontColor.DontChange;
        orgColor = c;
        color = c;
        OnSetText();
    }
References fontColor, OnSetText(), orgColor, and SetText().
SetText() [3/3]
void UIText.SetText (string s, FontColor c) inline
Definition at line 208 of file UIText.cs.
    {
        SetText(s);
        if (c != FontColor.Ignore)
        {
            fontColor = c;
            ApplySkin();
        }
        OnSetText();
    }
References ApplySkin(), fontColor, OnSetText(), and SetText().
Member Data Documentation
button
UIButton UIText.button
Definition at line 23 of file UIText.cs.
Referenced by ApplySkin().
fontColor
FontColor UIText.fontColor
Definition at line 15 of file UIText.cs.
Referenced by ApplySkin(), SetColor(), and SetText().
fontType
FontType UIText.fontType
Definition at line 13 of file UIText.cs.
Referenced by ApplySkin().
globalSizeMod
int UIText.globalSizeMod static
Definition at line 7 of file UIText.cs.
Referenced by ApplySkin().
hyphenation
HyphenationJpn UIText.hyphenation
Definition at line 21 of file UIText.cs.
Referenced by ApplySkin(), and SetText().
lang
string UIText.lang
Definition at line 9 of file UIText.cs.
Referenced by WidgetMenuPanel.AddButton(), UIDragGridInfo.Init(), UIDragGridInfo.InitFuel(), OnChangeLanguage(), OnEnable(), LayerNewspaper.OnInit(), HUD.SetDragText(), SetLang(), SetText(), and LayerUploader.Update().
orgColor
Color UIText.orgColor = Color.white
Definition at line 30 of file UIText.cs.
Referenced by ApplySkin(), and SetText().
orgSpacing
float UIText.orgSpacing
Definition at line 27 of file UIText.cs.
Referenced by ApplySkin().
size
int UIText.size
Definition at line 19 of file UIText.cs.
Referenced by ApplySkin(), HUD.SetDragImage(), and SetSize().
skinRoot
BaseSkinRoot UIText.skinRoot
Definition at line 11 of file UIText.cs.
Referenced by ApplySkin().
skinType
SkinType UIText.skinType
Definition at line 17 of file UIText.cs.
Referenced by ApplySkin().
typewriter
Typewriter UIText.typewriter
Definition at line 25 of file UIText.cs.
Referenced by OnSetText(), and DramaEventTalk.Play().
The documentation for this class was generated from the following file:
Elin/Plugins.UI/UIText.cs