Elin Decompiled Documentation: GrowSystem Class Reference
GrowSystem Class Reference
Classes
class Stage
Public Member Functions
bool IsLastStage ()
virtual bool BlockSight (Cell cell)
virtual bool BlockPass (Cell cell)
virtual string GetSoundProgress ()
virtual GrowSystem.Stage CreateStage ()
void Init (SourceObj.Row _row)
virtual void SetGenericFirstStageTile (GrowSystem.Stage s)
virtual void SetStageTile (GrowSystem.Stage s)
virtual int GetStageTile ()
virtual int GetShadow (int index)
virtual void OnRenderTileMap (RenderParam p)
void SetRandomStage ()
void SetDefaultStage ()
bool CanGrow (VirtualDate date)
void TryGrow (VirtualDate date)
void EqualizePlants (Point pos)
void Grow (int mtp=1)
virtual void OnReachNextStage ()
virtual void OnExceedLastStage ()
void SetStage (int idx, bool renewHarvest=false)
bool HaltGrowth ()
void Perish ()
bool IsWithered ()
bool CanHarvest ()
virtual bool CanReapSeed ()
virtual void OnHit (Chara c)
virtual void OnHitFail (Chara c)
void OnProgressComplete (Chara c)
void PopMineObj (Chara c=null)
virtual void OnMineObj (Chara c=null)
void TryPick (Cell cell, Thing t, Chara c, bool applySeed=false)
void TryPick (Cell cell, string idThing, int idMat=-1, int num=1, bool applySeed=false)
Thing TryPopSeed (Chara c)
void Harvest (Chara c)
void PopHarvest (Chara c, string idThing, int num=-1)
void PopHarvest (Chara c, Thing t=null, int num=-1)
void ApplySeed (Thing t)
virtual int GetHp ()
Public Attributes
SourceObj.Row source
GrowSystem.Stage[] stages
int[] baseTiles
int harvestTile
int afterHarvestTile
string idHarvestThing
Static Public Attributes
static SourceObj.Row[] sourceSnowTree
const int DivStage = 30
static Cell cell
static GrowSystem.Stage currentStage
Static Public Attributes inherited from EClass
static Core core
Protected Member Functions
virtual bool IsHarvestStage (int idx)
Properties
virtual RenderData RenderHarvest [get]
virtual int Step [get]
virtual int StageLength [get]
virtual int DefaultStage [get]
virtual int HarvestStage [get]
virtual int AutoMineStage [get]
virtual int HaltStage [get]
virtual bool DrawHarvestOnTop [get]
virtual bool UseGenericFirstStageTile [get]
virtual bool WitherOnLastStage [get]
virtual bool CanRegrow [get]
virtual int ShadowStage [get]
virtual bool IsTree [get]
virtual bool IsCrimeToHarvest [get]
virtual float MtpProgress [get]
virtual bool NeedSunlight [get]
virtual AnimeID AnimeProgress [get]
GrowSystem.Stage stage [get]
virtual bool IsMature [get]
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Additional Inherited Members
Static Public Member Functions inherited from EClass
static int rnd (int a)
static int curve (int a, int start, int step, int rate=75)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Detailed Description
Definition at line 4 of file GrowSystem.cs.
Member Function Documentation
ApplySeed()
void GrowSystem.ApplySeed (Thing t) inline
Definition at line 726 of file GrowSystem.cs.
    {
        PlantData plantData = EClass._map.TryGetPlant(GrowSystem.cell);
        Thing thing = (plantData != null) ? plantData.seed : null;
        if (EClass._zone.IsUserZone)
        {
            thing = null;
        }
        if (thing != null)
        {
            int encLv = thing.encLV / 10 + ((thing.encLV > 0) ? 1 : 0);
            foreach (Element element in thing.elements.dict.Values)
            {
                if ((!element.IsFoodTrait || t.IsFood) && (element.IsFoodTrait || element.id == 2))
                {
                    t.elements.ModBase(element.id, element.Value / 10 * 10);
                }
            }
            t.SetEncLv(encLv);
            t.c_refText = thing.c_refText;
            t.isCrafted = true;
        }
    }
References EClass._map, EClass._zone, Card.c_refText, cell, ElementContainer.dict, Card.elements, Element.id, Card.IsFood, Element.IsFoodTrait, Zone.IsUserZone, ElementContainer.ModBase(), PlantData.seed, Card.SetEncLv(), Map.TryGetPlant(), and Element.Value.
Referenced by PopHarvest(), and TryPick().
BlockPass()
virtual bool GrowSystem.BlockPass (Cell cell) inline virtual
Reimplemented in GrowSystemTree.
Definition at line 149 of file GrowSystem.cs.
    {
        return false;
    }
BlockSight()
virtual bool GrowSystem.BlockSight (Cell cell) inline virtual
Reimplemented in GrowSystemTree.
Definition at line 144 of file GrowSystem.cs.
    {
        return false;
    }
Referenced by Cell.Refresh().
CanGrow()
bool GrowSystem.CanGrow (VirtualDate date) inline
Definition at line 315 of file GrowSystem.cs.
    {
        if (this.source.id == 0)
        {
            return false;
        }
        if (GrowSystem.cell.HasBlock && !GrowSystem.cell.sourceBlock.tileType.IsFence)
        {
            return false;
        }
        if (this.NeedSunlight)
        {
            if (date.sunMap == null)
            {
                date.BuildSunMap();
            }
            if ((GrowSystem.cell.HasRoof || date.IsWinter || EClass._map.IsIndoor) && !date.sunMap.Contains(GrowSystem.cell.index))
            {
                return false;
            }
        }
        return true;
    }
References EClass._map, VirtualDate.BuildSunMap(), cell, Cell.HasBlock, Cell.HasRoof, Cell.index, Map.IsIndoor, Date.IsWinter, NeedSunlight, source, Cell.sourceBlock, and VirtualDate.sunMap.
Referenced by Cell.CanGrow(), and TryGrow().
CanHarvest()
bool GrowSystem.CanHarvest () inline
Definition at line 542 of file GrowSystem.cs.
    {
        return this.stage.harvest && !GrowSystem.cell.isHarvested;
    }
References cell, and Cell.isHarvested.
Referenced by Cell.CanHarvest(), CanReapSeed(), and Perish().
CanReapSeed()
virtual bool GrowSystem.CanReapSeed () inline virtual
Reimplemented in GrowSystemFlower, GrowSystemHerb, GrowSystemKinoko, GrowSystemPasture, and GrowSystemWeed.
Definition at line 547 of file GrowSystem.cs.
    {
        return this.CanHarvest();
    }
References CanHarvest().
Referenced by Cell.CanReapSeed().
CreateStage()
virtual GrowSystem.Stage GrowSystem.CreateStage () inline virtual
Definition at line 175 of file GrowSystem.cs.
    {
        return new GrowSystem.Stage();
    }
Referenced by Init().
EqualizePlants()
void GrowSystem.EqualizePlants (Point pos) inline
Definition at line 348 of file GrowSystem.cs.
    {
        PlantData p1 = EClass._map.TryGetPlant(pos);
        if (p1 == null || p1.seed == null)
        {
            return;
        }
        pos.ForeachNeighbor(delegate(Point pos2)
        {
            PlantData plantData = EClass._map.TryGetPlant(pos2);
            Thing thing = (plantData != null) ? plantData.seed : null;
            if (thing == null)
            {
                Thing installed = pos2.Installed;
                if (installed != null && installed.id == p1.seed.id)
                {
                    thing = installed;
                }
            }
            if (thing == null)
            {
                return;
            }
            if (p1.seed.refVal != thing.refVal)
            {
                return;
            }
            if (thing.encLV >= p1.seed.encLV)
            {
                p1.seed = thing;
            }
        }, false);
    }
References EClass._map, Card.encLV, Point.ForeachNeighbor(), Card.id, installed, Point.Installed, Card.refVal, PlantData.seed, and Map.TryGetPlant().
Referenced by Grow().
GetHp()
virtual int GrowSystem.GetHp () inline virtual
Reimplemented in GrowSystemTree.
Definition at line 750 of file GrowSystem.cs.
    {
        return this.source.hp;
    }
References source.
Referenced by BaseTaskHarvest.SetTarget().
GetShadow()
virtual int GrowSystem.GetShadow (int index) inline virtual
Reimplemented in GrowSystemTree, and GrowSystemTreeSingle.
Definition at line 238 of file GrowSystem.cs.
    {
        return -1;
    }
Referenced by OnRenderTileMap().
GetSoundProgress()
virtual string GrowSystem.GetSoundProgress () inline virtual
Reimplemented in GrowSystemWheat.
Definition at line 154 of file GrowSystem.cs.
    {
        return "Material/grass";
    }
Referenced by TaskHarvest.OnCreateProgress().
GetStageTile()
virtual int GrowSystem.GetStageTile () inline virtual
Reimplemented in GrowSystemWheat.
Definition at line 233 of file GrowSystem.cs.
    {
        return GrowSystem.currentStage.tiles[GrowSystem.cell.objDir % GrowSystem.currentStage.tiles.Length];
    }
References currentStage.
Referenced by OnRenderTileMap().
Grow()
void GrowSystem.Grow (int mtp = 1) inline
Definition at line 382 of file GrowSystem.cs.
    {
        bool flag = GrowSystem.cell.isWatered || (GrowSystem.cell.IsTopWater && this.source.tag.Contains("flood"));
        PlantData plantData = EClass._map.TryGetPlant(GrowSystem.cell);
        if (plantData != null && flag)
        {
            plantData.water++;
        }
        int num = this.Step * mtp * (flag ? 2 : 1);
        int num2 = (int)(GrowSystem.cell.objVal / 30);
        int num3 = ((int)GrowSystem.cell.objVal + num) / 30;
        if (num2 != num3)
        {
            if (EClass.player.isAutoFarming && num2 == this.HarvestStage && this.CanHarvest())
            {
                this.PopHarvest(null, null, -1);
            }
            if (EClass.player.isAutoFarming && num2 >= this.AutoMineStage)
            {
                Point point = GrowSystem.cell.GetPoint();
                this.EqualizePlants(point);
                Thing thing = this.TryPopSeed(null);
                this.PopMineObj(null);
                if (thing != null)
                {
                    point.SetObj(0, 1, 0);
                    EClass._zone.AddCard(thing, point).Install();
                }
            }
            else if (num2 == this.StageLength - 1)
            {
                if (EClass.player.isAutoFarming)
                {
                    Point point2 = GrowSystem.cell.GetPoint();
                    this.EqualizePlants(point2);
                    Thing thing2 = this.TryPopSeed(null);
                    if (thing2 != null)
                    {
                        point2.SetObj(0, 1, 0);
                        EClass._zone.AddCard(thing2, point2).Install();
                    }
                }
                else
                {
                    this.OnExceedLastStage();
                }
            }
            else
            {
                this.OnReachNextStage();
            }
        }
        else
        {
            Cell cell = GrowSystem.cell;
            cell.objVal += (byte)num;
        }
        GrowSystem.cell.Refresh();
        EClass._map.RefreshFOV((int)GrowSystem.cell.x, (int)GrowSystem.cell.z, 6, false);
    }
References EClass._map, EClass._zone, Zone.AddCard(), cell, EqualizePlants(), Cell.GetPoint(), Card.Install(), Player.isAutoFarming, Cell.objVal, OnExceedLastStage(), OnReachNextStage(), EClass.player, PopHarvest(), PopMineObj(), Cell.Refresh(), Map.RefreshFOV(), Point.SetObj(), source, StageLength, Map.TryGetPlant(), TryPopSeed(), PlantData.water, Cell.x, and Cell.z.
Referenced by ActionMode.RotateUnderMouse(), and TryGrow().
HaltGrowth()
bool GrowSystem.HaltGrowth () inline
Definition at line 492 of file GrowSystem.cs.
    {
        return this.stage.idx == this.HarvestStage;
    }
References HarvestStage.
Harvest()
void GrowSystem.Harvest (Chara c) inline
Definition at line 654 of file GrowSystem.cs.
    {
        GrowSystem.cell.isHarvested = true;
        GrowSystem.cell.gatherCount = 0;
        this.PopHarvest(c, null, -1);
    }
References PopHarvest().
Referenced by TaskHarvest.OnCreateProgress().
Init()
void GrowSystem.Init (SourceObj::Row _row) inline
Definition at line 180 of file GrowSystem.cs.
    {
        this.source = _row;
        this.stages = new GrowSystem.Stage[this.StageLength];
        string[] growth = _row._growth;
        string[] array = growth[1].Split('/', StringSplitOptions.None);
        this.baseTiles = new int[array.Length];
        for (int i = 0; i < array.Length; i++)
        {
            this.baseTiles[i] = array[i].ToInt();
        }
        if (growth.Length > 2)
        {
            this.harvestTile = this.RenderHarvest.ConvertTile(growth[2].ToInt());
            this.idHarvestThing = growth[3];
        }
        for (int j = 0; j < this.StageLength; j++)
        {
            GrowSystem.Stage stage = this.CreateStage();
            this.stages[j] = stage;
            stage.idx = j;
            if (j == 0 && this.UseGenericFirstStageTile)
            {
                this.SetGenericFirstStageTile(stage);
            }
            else
            {
                this.SetStageTile(stage);
            }
            if (this.harvestTile != 0 && this.IsHarvestStage(j))
            {
                stage.harvest = true;
            }
        }
    }
References baseTiles, RenderData.ConvertTile(), CreateStage(), harvestTile, IsHarvestStage(), RenderHarvest, SetGenericFirstStageTile(), SetStageTile(), stage, StageLength, stages, and UseGenericFirstStageTile.
Referenced by SourceObj.Row.OnInit().
IsHarvestStage()
virtual bool GrowSystem.IsHarvestStage (int idx) inline protected virtual
Definition at line 67 of file GrowSystem.cs.
    {
        return idx == this.HarvestStage;
    }
References HarvestStage.
Referenced by Init().
IsLastStage()
bool GrowSystem.IsLastStage () inline
Definition at line 6 of file GrowSystem.cs.
    {
        return this.stage.idx == this.StageLength - 1;
    }
Referenced by Cell.CanMakeStraw().
IsWithered()
bool GrowSystem.IsWithered () inline
Definition at line 537 of file GrowSystem.cs.
    {
        return this.WitherOnLastStage && this.stage.idx == this.StageLength - 1;
    }
Referenced by OnMineObj(), and TryPopSeed().
OnExceedLastStage()
virtual void GrowSystem.OnExceedLastStage () inline virtual
Reimplemented in GrowSystemKinoko.
Definition at line 448 of file GrowSystem.cs.
    {
        GrowSystem.cell.objVal = (byte)(this.stages.Length * 30 - 1);
        if (!this.CanRegrow)
        {
            return;
        }
        if (Rand.rnd(2) == 0)
        {
            Point point = GrowSystem.cell.GetPoint();
            if (point.IsFarmField)
            {
                return;
            }
            if (Rand.rnd(2) == 0)
            {
                Point randomNeighbor = point.GetRandomNeighbor();
                if (randomNeighbor.cell.CanGrowWeed)
                {
                    randomNeighbor.SetObj((int)GrowSystem.cell.obj, 1, 0);
                    point.SetObj(0, 1, 0);
                    return;
                }
            }
            GrowSystem.cell.objVal = 0;
            GrowSystem.cell.isHarvested = false;
            GrowSystem.cell.isWatered = GrowSystem.cell.HasLiquid;
        }
    }
References Cell.CanGrowWeed, CanRegrow, cell, Point.cell, Cell.GetPoint(), Point.GetRandomNeighbor(), Cell.HasLiquid, Point.IsFarmField, Cell.obj, Point.SetObj(), and stages.
Referenced by Grow().
OnHit()
virtual void GrowSystem.OnHit (Chara c) inline virtual
Definition at line 552 of file GrowSystem.cs.
    {
    }
OnHitFail()
virtual void GrowSystem.OnHitFail (Chara c) inline virtual
Reimplemented in GrowSystemTree.
Definition at line 556 of file GrowSystem.cs.
    {
    }
Referenced by TaskHarvest.OnCreateProgress().
OnMineObj()
virtual void GrowSystem.OnMineObj (Chara c = null) inline virtual
Reimplemented in GrowSystemBerry, GrowSystemCactus, GrowSystemCrop, GrowSystemFlower, GrowSystemHerb, GrowSystemKinoko, GrowSystemPasture, GrowSystemPlant, GrowSystemTree, GrowSystemWeed, and GrowSystemWheat.
Definition at line 571 of file GrowSystem.cs.
    {
        if (!this.IsWithered())
        {
            int num = GrowSystem.cell.sourceObj.components.Length - 1;
            Thing t = ThingGen.Create(GrowSystem.cell.sourceObj.components[num].Split('/', StringSplitOptions.None)[0], GrowSystem.cell.matObj_fixed.alias);
            this.TryPick(GrowSystem.cell, t, c, false);
        }
    }
References cell, ThingGen.Create(), IsWithered(), Cell.matObj_fixed, Cell.sourceObj, and TryPick().
Referenced by PopMineObj().
OnProgressComplete()
void GrowSystem.OnProgressComplete (Chara c) inline
Definition at line 560 of file GrowSystem.cs.
    {
        EClass._map.MineObj(GrowSystem.cell.GetPoint(), null, c);
    }
References EClass._map, cell, Cell.GetPoint(), and Map.MineObj().
Referenced by TaskHarvest.OnCreateProgress().
OnReachNextStage()
virtual void GrowSystem.OnReachNextStage () inline virtual
Definition at line 443 of file GrowSystem.cs.
    {
        this.SetStage((int)(GrowSystem.cell.objVal / 30 + 1), false);
    }
References cell, Cell.objVal, and SetStage().
Referenced by Grow().
OnRenderTileMap()
virtual void GrowSystem.OnRenderTileMap (RenderParam p) inline virtual
Definition at line 243 of file GrowSystem.cs.
    {
        int num = (int)(GrowSystem.cell.objVal / 30);
        GrowSystem.currentStage = this.stages[num];
        SourceObj.Row row = this.source;
        float y = p.y;
        float z = p.z;
        if (num != 0 || !this.UseGenericFirstStageTile)
        {
            p.y += row.pref.y;
            p.z += row.pref.z;
        }
        if (GrowSystem.currentStage.harvest)
        {
            if (GrowSystem.cell.isHarvested || this.harvestTile == 0)
            {
                p.tile = (float)((this.afterHarvestTile != 0) ? this.afterHarvestTile : this.GetStageTile());
                GrowSystem.currentStage.renderData.Draw(p);
            }
            else
            {
                if (this.DrawHarvestOnTop)
                {
                    p.tile = (float)this.GetStageTile();
                    GrowSystem.currentStage.renderData.Draw(p);
                    p.liquidLv = 0;
                }
                p.tile = (float)this.harvestTile;
                this.RenderHarvest.Draw(p);
            }
        }
        else
        {
            p.tile = (float)this.GetStageTile();
            GrowSystem.currentStage.renderData.Draw(p);
        }
        p.y = y;
        p.z = z;
        if (num < this.ShadowStage)
        {
            return;
        }
        int shadow = this.GetShadow(num);
        if (shadow == -1)
        {
            shadow = row.pref.shadow;
        }
        if (shadow > 1 && !GrowSystem.cell.ignoreObjShadow)
        {
            EClass.screen.tileMap.passShadow.AddShadow(p.x + row.renderData.offsetShadow.x, p.y + row.renderData.offsetShadow.y, p.z + row.renderData.offsetShadow.z, ShadowData.Instance.items[shadow], row.pref, 0, p.snow);
        }
    }
References MeshPass.AddShadow(), afterHarvestTile, cell, currentStage, RenderData.Draw(), DrawHarvestOnTop, GetShadow(), GetStageTile(), harvestTile, Cell.ignoreObjShadow, ShadowData.Instance, Cell.isHarvested, ShadowData.items, Cell.objVal, RenderData.offsetShadow, BaseTileMap.passShadow, RenderRow.pref, RenderRow.renderData, RenderHarvest, EClass.screen, SourcePref.shadow, ShadowStage, MeshPassParam.snow, source, stages, BaseGameScreen.tileMap, UseGenericFirstStageTile, MeshPassParam.x, MeshPassParam.y, SourcePref.y, MeshPassParam.z, and SourcePref.z.
Referenced by BaseTileMap.DrawTile(), and TileMapElona.DrawTile().
Perish()
void GrowSystem.Perish () inline
Definition at line 505 of file GrowSystem.cs.
    {
        if (EClass.player.isAutoFarming)
        {
            if (this.CanHarvest())
            {
                this.PopHarvest(null, null, -1);
            }
            Thing thing = this.TryPopSeed(null);
            if (thing != null)
            {
                EClass._zone.AddCard(thing, GrowSystem.cell.GetPoint()).Install();
            }
            EClass._map.SetObj((int)GrowSystem.cell.x, (int)GrowSystem.cell.z, 0, 1, 0);
            return;
        }
        if (this.WitherOnLastStage && this.stage.idx == this.StageLength - 2)
        {
            this.SetStage(this.StageLength - 1, false);
            return;
        }
        if (EClass.rnd(3) == 0)
        {
            Thing thing2 = this.TryPopSeed(null);
            if (thing2 != null)
            {
                EClass._zone.AddCard(thing2, GrowSystem.cell.GetPoint()).Install();
            }
        }
        EClass._map.SetObj((int)GrowSystem.cell.x, (int)GrowSystem.cell.z, 0, 1, 0);
    }
References EClass._map, EClass._zone, Zone.AddCard(), CanHarvest(), cell, Cell.GetPoint(), Card.Install(), Player.isAutoFarming, EClass.player, PopHarvest(), EClass.rnd(), Map.SetObj(), SetStage(), stage, StageLength, TryPopSeed(), WitherOnLastStage, Cell.x, and Cell.z.
PopHarvest() [1/2]
void GrowSystem.PopHarvest (Chara c, string idThing, int num = -1) inline
Definition at line 661 of file GrowSystem.cs.
    {
        this.PopHarvest(c, ThingGen.Create(idThing, -1, -1), num);
    }
References ThingGen.Create(), and PopHarvest().
Referenced by Grow(), Harvest(), Perish(), and PopHarvest().
PopHarvest() [2/2]
void GrowSystem.PopHarvest (Chara c, Thing t = null, int num = -1) inline
Definition at line 666 of file GrowSystem.cs.
    {
        if (t == null)
        {
            if (this.idHarvestThing.StartsWith('#'))
            {
                t = ThingGen.CreateFromCategory(this.idHarvestThing.Replace("#", ""), -1);
            }
            else
            {
                t = ThingGen.Create(this.idHarvestThing.IsEmpty("apple"), -1, -1);
            }
        }
        this.ApplySeed(t);
        PlantData plantData = EClass._map.TryGetPlant(GrowSystem.cell);
        if (plantData != null && plantData.size > 0)
        {
            t.c_weight = t.SelfWeight * (80 + plantData.size * plantData.size * 100) / 100;
            t.SetBool(115, true);
            t.isWeightChanged = true;
        }
        t.SetBlessedState(BlessedState.Normal);
        if (this.source._growth.Length > 4)
        {
            int num2 = EClass.rnd(this.source._growth[4].ToInt()) + 1;
            if (EClass._zone.IsPCFaction)
            {
                int soilCost = EClass._zone.GetSoilCost();
                int maxSoil = EClass.Branch.MaxSoil;
                if (soilCost > maxSoil && EClass.player.stats.days >= 5)
                {
                    num2 -= EClass.rnd(2 + (soilCost - maxSoil) / 20);
                }
            }
            if (num2 <= 0)
            {
                if (!EClass.player.isAutoFarming)
                {
                    c.Say("cropSpoiled", c, GrowSystem.cell.GetObjName(), null);
                }
                return;
            }
            t.SetNum(num2);
        }
        else
        {
            Debug.Log("harvest count not set:" + this.source.id.ToString() + "/" + this.source.alias);
        }
        if (num != -1)
        {
            t.SetNum(num);
        }
        if (c == null || EClass.player.isAutoFarming)
        {
            this.TryPick(GrowSystem.cell, t, c, false);
            return;
        }
        c.Pick(t, true, true);
    }
References EClass._map, EClass._zone, ApplySeed(), EClass.Branch, cell, ThingGen.Create(), ThingGen.CreateFromCategory(), Cell.GetObjName(), Zone.GetSoilCost(), idHarvestThing, Player.isAutoFarming, Zone.IsPCFaction, FactionBranch.MaxSoil, Chara.Pick(), EClass.player, EClass.rnd(), Card.Say(), PlantData.size, source, Player.stats, Map.TryGetPlant(), and TryPick().
PopMineObj()
void GrowSystem.PopMineObj (Chara c = null) inline
Definition at line 565 of file GrowSystem.cs.
    {
        this.OnMineObj(c);
        this.TryPopSeed(c);
    }
References OnMineObj(), and TryPopSeed().
Referenced by Grow(), and Map.MineObj().
SetDefaultStage()
void GrowSystem.SetDefaultStage () inline
Definition at line 310 of file GrowSystem.cs.
    {
        GrowSystem.cell.objVal = (byte)(this.DefaultStage * 30);
    }
References DefaultStage.
Referenced by Recipe.Build().
SetGenericFirstStageTile()
virtual void GrowSystem.SetGenericFirstStageTile (GrowSystem::Stage s) inline virtual
Reimplemented in GrowSystemTree.
Definition at line 216 of file GrowSystem.cs.
    {
        s.renderData = EClass.core.refs.renderers.objS_flat;
        s.SetTile(0, new int[]
        {
            100,
            101,
            102
        });
    }
References EClass.core.
Referenced by Init().
SetRandomStage()
void GrowSystem.SetRandomStage () inline
Definition at line 296 of file GrowSystem.cs.
    {
        int num = Rand.rnd(this.stages.Length);
        if (num == 0 && EClass.rnd(5) != 0 && this.stages.Length >= 2)
        {
            num++;
        }
        else if (num == this.stages.Length - 1 && EClass.rnd(5) != 0 && this.stages.Length >= 2)
        {
            num--;
        }
        GrowSystem.cell.objVal = (byte)(num * 30);
    }
References EClass.rnd(), and stages.
Referenced by BiomeProfile.ClusterObj.TryCreate().
SetStage()
void GrowSystem.SetStage (int idx, bool renewHarvest = false) inline
Definition at line 478 of file GrowSystem.cs.
    {
        GrowSystem.cell.objVal = (byte)(idx * 30);
        GrowSystem.cell.gatherCount = 0;
        if (GrowSystem.cell.HasLiquid)
        {
            GrowSystem.cell.isWatered = true;
        }
        if (renewHarvest)
        {
            GrowSystem.cell.isHarvested = true;
        }
    }
References cell, and Cell.HasLiquid.
Referenced by OnReachNextStage(), ZoneEventHarvest.OnVisit(), and Perish().
SetStageTile()
virtual void GrowSystem.SetStageTile (GrowSystem::Stage s) inline virtual
Reimplemented in GrowSystemTree, and GrowSystemTreeSingle.
Definition at line 227 of file GrowSystem.cs.
    {
        s.renderData = this.source.renderData;
        s.SetTile(s.idx + (this.UseGenericFirstStageTile ? -1 : 0), this.baseTiles);
    }
References source.
Referenced by Init().
TryGrow()
void GrowSystem.TryGrow (VirtualDate date) inline
Definition at line 339 of file GrowSystem.cs.
    {
        if (!this.CanGrow(date))
        {
            return;
        }
        this.Grow(1);
    }
References CanGrow(), and Grow().
Referenced by TraitFertilizer.OnSimulateHour(), and Cell.TryGrow().
TryPick() [1/2]
void GrowSystem.TryPick (Cell cell, string idThing, int idMat = -1, int num = 1, bool applySeed = false) inline
Definition at line 613 of file GrowSystem.cs.
    {
        if (num <= 0)
        {
            return;
        }
        this.TryPick(cell, ThingGen.Create(idThing, idMat, -1).SetNum(num), EClass.pc, applySeed);
    }
References ThingGen.Create(), EClass.pc, Card.SetNum(), and TryPick().
TryPick() [2/2]
void GrowSystem.TryPick (Cell cell, Thing t, Chara c, bool applySeed = false) inline
Definition at line 581 of file GrowSystem.cs.
    {
        if (applySeed)
        {
            this.ApplySeed(t);
        }
        if (EClass.player.isAutoFarming)
        {
            if (EClass.rnd(4) == 0)
            {
                return;
            }
            if (t.Num > 1)
            {
                t.SetNum(t.Num / 2);
            }
            else if (EClass.rnd(2) == 0)
            {
                return;
            }
            if (!EClass._zone.TryAddThingInSharedContainer(t, null, true, false, null, true))
            {
                EClass.game.cards.container_shipping.AddCard(t);
                return;
            }
        }
        else
        {
            EClass._map.TrySmoothPick(cell, t, c);
        }
    }
References EClass._map, EClass._zone, Card.AddCard(), ApplySeed(), Game.cards, cell, CardManager.container_shipping, EClass.game, Player.isAutoFarming, Card.Num, EClass.player, EClass.rnd(), Card.SetNum(), Zone.TryAddThingInSharedContainer(), and Map.TrySmoothPick().
Referenced by OnMineObj(), PopHarvest(), TryPick(), and TryPopSeed().
TryPopSeed()
Thing GrowSystem.TryPopSeed (Chara c) inline
Definition at line 622 of file GrowSystem.cs.
    {
        if (this.source.HasTag(CTAG.seed))
        {
            int num = GrowSystem.cell.IsFarmField ? 400 : 1000;
            if (EClass._zone.IsPCFaction)
            {
                int soilCost = EClass._zone.GetSoilCost();
                int maxSoil = EClass.Branch.MaxSoil;
                if (soilCost > maxSoil)
                {
                    num += (soilCost - maxSoil) * 10;
                }
            }
            if (this.IsWithered())
            {
                num /= 5;
            }
            if (EClass.player.isAutoFarming || EClass.rnd(num) < EClass.rnd(this.source.chance))
            {
                Thing thing = TraitSeed.MakeSeed(this.source, EClass._map.TryGetPlant(GrowSystem.cell));
                if (EClass.player.isAutoFarming)
                {
                    return thing;
                }
                this.TryPick(GrowSystem.cell, thing, c, false);
                return thing;
            }
        }
        return null;
    }
References EClass._map, EClass._zone, EClass.Branch, cell, Zone.GetSoilCost(), Player.isAutoFarming, Zone.IsPCFaction, IsWithered(), TraitSeed.MakeSeed(), FactionBranch.MaxSoil, EClass.player, EClass.rnd(), source, Map.TryGetPlant(), and TryPick().
Referenced by Grow(), Perish(), and PopMineObj().
Member Data Documentation
afterHarvestTile
int GrowSystem.afterHarvestTile
Definition at line 775 of file GrowSystem.cs.
Referenced by OnRenderTileMap().
baseTiles
int [] GrowSystem.baseTiles
Definition at line 771 of file GrowSystem.cs.
Referenced by Init(), and GrowSystemTreeSingle.SetStageTile().
cell
Cell GrowSystem.cell static
Definition at line 763 of file GrowSystem.cs.
Referenced by ApplySeed(), CanGrow(), CanHarvest(), GrowSystemWheat.GetStageTile(), Grow(), OnExceedLastStage(), GrowSystemTree.OnHitFail(), OnMineObj(), GrowSystemBerry.OnMineObj(), GrowSystemCactus.OnMineObj(), GrowSystemCrop.OnMineObj(), GrowSystemFlower.OnMineObj(), GrowSystemHerb.OnMineObj(), GrowSystemPasture.OnMineObj(), GrowSystemPlant.OnMineObj(), GrowSystemTree.OnMineObj(), GrowSystemWeed.OnMineObj(), GrowSystemWheat.OnMineObj(), OnProgressComplete(), OnReachNextStage(), OnRenderTileMap(), Perish(), PopHarvest(), SetStage(), TryPick(), and TryPopSeed().
currentStage
GrowSystem.Stage GrowSystem.currentStage static
Definition at line 765 of file GrowSystem.cs.
Referenced by GetStageTile(), GrowSystemWheat.GetStageTile(), and OnRenderTileMap().
DivStage
const int GrowSystem.DivStage = 30 static
Definition at line 761 of file GrowSystem.cs.
harvestTile
int GrowSystem.harvestTile
Definition at line 773 of file GrowSystem.cs.
Referenced by Init(), and OnRenderTileMap().
idHarvestThing
string GrowSystem.idHarvestThing
Definition at line 777 of file GrowSystem.cs.
Referenced by PopHarvest().
source
SourceObj.Row GrowSystem.source
Definition at line 767 of file GrowSystem.cs.
Referenced by CanGrow(), GetHp(), GrowSystemTree.GetShadow(), GrowSystemWheat.GetSoundProgress(), Grow(), GrowSystemCrop.OnMineObj(), OnRenderTileMap(), PopHarvest(), SetStageTile(), GrowSystemTree.SetStageTile(), GrowSystemTreeSingle.SetStageTile(), and TryPopSeed().
sourceSnowTree
SourceObj.Row [] GrowSystem.sourceSnowTree static
Initial value:
= new SourceObj.Row[]
    {
        EClass.sources.objs.map[54],
        EClass.sources.objs.map[55]
    }
Definition at line 755 of file GrowSystem.cs.
stages
GrowSystem.Stage [] GrowSystem.stages
Definition at line 769 of file GrowSystem.cs.
Referenced by Init(), OnExceedLastStage(), OnRenderTileMap(), and SetRandomStage().
Property Documentation
AnimeProgress
virtual AnimeID GrowSystem.AnimeProgress get
Definition at line 159 of file GrowSystem.cs.
    {
        get
        {
            return AnimeID.HitObj;
        }
    }
Referenced by TaskHarvest.OnCreateProgress().
AutoMineStage
virtual int GrowSystem.AutoMineStage get
Definition at line 51 of file GrowSystem.cs.
    {
        get
        {
            return this.HarvestStage;
        }
    }
CanRegrow
virtual bool GrowSystem.CanRegrow get protected
Definition at line 96 of file GrowSystem.cs.
    {
        get
        {
            return true;
        }
    }
Referenced by OnExceedLastStage().
DefaultStage
virtual int GrowSystem.DefaultStage get
Definition at line 35 of file GrowSystem.cs.
    {
        get
        {
            return Mathf.Clamp(this.StageLength - 2, 0, this.StageLength - 1);
        }
    }
Referenced by SetDefaultStage().
DrawHarvestOnTop
virtual bool GrowSystem.DrawHarvestOnTop get protected
Definition at line 72 of file GrowSystem.cs.
    {
        get
        {
            return false;
        }
    }
Referenced by OnRenderTileMap().
HaltStage
virtual int GrowSystem.HaltStage get protected
Definition at line 59 of file GrowSystem.cs.
    {
        get
        {
            return this.HarvestStage;
        }
    }
HarvestStage
virtual int GrowSystem.HarvestStage get
Definition at line 43 of file GrowSystem.cs.
    {
        get
        {
            return -1;
        }
    }
Referenced by HaltGrowth(), IsHarvestStage(), and ZoneEventHarvest.OnVisit().
IsCrimeToHarvest
virtual bool GrowSystem.IsCrimeToHarvest get
Definition at line 120 of file GrowSystem.cs.
    {
        get
        {
            return false;
        }
    }
IsMature
virtual bool GrowSystem.IsMature get
Definition at line 497 of file GrowSystem.cs.
    {
        get
        {
            return false;
        }
    }
Referenced by Map.AddBackerTree().
IsTree
virtual bool GrowSystem.IsTree get
Definition at line 112 of file GrowSystem.cs.
    {
        get
        {
            return false;
        }
    }
Referenced by Map.AddBackerTree(), AIWork_Lumberjack.FuncWorkPoint(), AIWork_Lumberjack.GetWork(), and Map.MineObj().
MtpProgress
virtual float GrowSystem.MtpProgress get
Definition at line 128 of file GrowSystem.cs.
    {
        get
        {
            return 1f;
        }
    }
NeedSunlight
virtual bool GrowSystem.NeedSunlight get
Definition at line 136 of file GrowSystem.cs.
    {
        get
        {
            return true;
        }
    }
Referenced by CanGrow().
RenderHarvest
virtual RenderData GrowSystem.RenderHarvest get
Definition at line 11 of file GrowSystem.cs.
    {
        get
        {
            return this.source.renderData;
        }
    }
Referenced by Init(), and OnRenderTileMap().
ShadowStage
virtual int GrowSystem.ShadowStage get
Definition at line 104 of file GrowSystem.cs.
    {
        get
        {
            return 1;
        }
    }
Referenced by OnRenderTileMap().
stage
GrowSystem.Stage GrowSystem.stage get
Definition at line 167 of file GrowSystem.cs.
    {
        get
        {
            return this.stages[(int)(GrowSystem.cell.objVal / 30)];
        }
    }
Referenced by Init(), and Perish().
StageLength
virtual int GrowSystem.StageLength get
Definition at line 27 of file GrowSystem.cs.
    {
        get
        {
            return 5;
        }
    }
Referenced by GrowSystemWheat.GetStageTile(), Grow(), Init(), and Perish().
Step
virtual int GrowSystem.Step get
Definition at line 19 of file GrowSystem.cs.
    {
        get
        {
            return 5;
        }
    }
UseGenericFirstStageTile
virtual bool GrowSystem.UseGenericFirstStageTile get protected
Definition at line 80 of file GrowSystem.cs.
    {
        get
        {
            return true;
        }
    }
Referenced by Init(), and OnRenderTileMap().
WitherOnLastStage
virtual bool GrowSystem.WitherOnLastStage get protected
Definition at line 88 of file GrowSystem.cs.
    {
        get
        {
            return true;
        }
    }
Referenced by Perish().
The documentation for this class was generated from the following file:
Elin/GrowSystem.cs