Elin Decompiled Documentation: NotificationBuff Class Reference
NotificationBuff Class Reference
Public Member Functions
override ItemNotice GetMold ()
override void OnRefresh ()
override void OnInstantiate ()
Public Member Functions inherited from NotificationCondition
override bool ShouldRemove ()
override int GetSortVal ()
override void OnClick ()
override void OnRefresh ()
Public Member Functions inherited from BaseNotification
virtual ItemNotice GetMold ()
virtual LayoutGroup GetLayoutGroup ()
virtual int GetSortVal ()
void Refresh ()
virtual void OnClick ()
virtual void OnRefresh ()
virtual bool ShouldRemove ()
virtual void OnInstantiate ()
Properties
override int idSprite [get]
override bool Interactable [get]
Properties inherited from NotificationCondition
override bool Visible [get]
override bool Interactable [get]
override Action< UITooltip > onShowTooltip [get]
override Sprite Sprite [get]
Properties inherited from BaseNotification
virtual Sprite Sprite [get]
virtual int idSprite [get]
virtual bool Visible [get]
virtual bool Interactable [get]
virtual Action< UITooltip > onShowTooltip [get]
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Additional Inherited Members
Static Public Member Functions inherited from EClass
static int rndSeed (int a, int seed)
static int rnd (long a)
static int rnd (int a)
static int curve (long _a, int start, int step, int rate=75)
static int sqrt (int a)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Public Attributes inherited from NotificationCondition
Condition condition
Public Attributes inherited from BaseNotification
ItemNotice item
string text
string lastText
Static Public Attributes inherited from EClass
static Core core
Detailed Description
Definition at line 1 of file NotificationBuff.cs.
Member Function Documentation
GetMold()
override ItemNotice NotificationBuff.GetMold () inline virtual
Reimplemented from BaseNotification.
Definition at line 7 of file NotificationBuff.cs.
    {
        return WidgetStats.Instance.moldBuff;
    }
References WidgetStats.Instance, and WidgetStats.moldBuff.
OnInstantiate()
override void NotificationBuff.OnInstantiate () inline virtual
Reimplemented from BaseNotification.
Definition at line 23 of file NotificationBuff.cs.
    {
        item.button.icon.sprite = condition.GetSprite();
        item.button.icon.color = condition.GetSpriteColor();
        item.button.icon.SetNativeSize();
    }
References ItemNotice.button, NotificationCondition.condition, BaseStats.GetSprite(), BaseCondition.GetSpriteColor(), UIButton.icon, and BaseNotification.item.
Referenced by OnRefresh().
OnRefresh()
override void NotificationBuff.OnRefresh () inline virtual
Reimplemented from BaseNotification.
Definition at line 12 of file NotificationBuff.cs.
    {
        if (item.button.icon.sprite == EClass.core.refs.spriteDefaultCondition)
        {
            OnInstantiate();
        }
        text = condition.GetText() + (EClass.debug.showExtra ? (" " + condition.value) : "");
        item.textDuration.SetText(condition.TextDuration);
        item.textDuration.SetActive(condition.HasDuration);
    }
References ItemNotice.button, NotificationCondition.condition, EClass.core, BaseCondition.GetText(), BaseCondition.HasDuration, UIButton.icon, BaseNotification.item, OnInstantiate(), Core.refs, UIText.SetText(), CoreRef.spriteDefaultCondition, BaseNotification.text, Condition.TextDuration, ItemNotice.textDuration, and BaseCondition.value.
Property Documentation
idSprite
override int NotificationBuff.idSprite get
Definition at line 3 of file NotificationBuff.cs.
Interactable
override bool NotificationBuff.Interactable get
Definition at line 5 of file NotificationBuff.cs.
The documentation for this class was generated from the following file:
Elin/NotificationBuff.cs