Elin Decompiled Documentation: LimitVisibleCharacters Class Reference
LimitVisibleCharacters Class Reference
Public Member Functions
override void ModifyMesh (VertexHelper vh)
Protected Member Functions
LimitVisibleCharacters ()
Properties
int visibleCharacterCount [get, set]
Private Member Functions
MatchCollection GetRegexMatchedTags (string text, out int lengthWithoutTags)
Private Attributes
int m_VisibleCharacterCount
List< UIVertex > m_Verts = new List<UIVertex>()
Static Private Attributes
const string REGEX_TAGS = "<b>|</b>|<i>|</i>|<size=.*?>|</size>|<color=.*?>|</color>|<material=.*?>|</material>"
Detailed Description
Definition at line 9 of file LimitVisibleCharacters.cs.
Constructor & Destructor Documentation
LimitVisibleCharacters()
LimitVisibleCharacters.LimitVisibleCharacters () inline protected
Definition at line 37 of file LimitVisibleCharacters.cs.
    {
    }
Member Function Documentation
GetRegexMatchedTags()
MatchCollection LimitVisibleCharacters.GetRegexMatchedTags (string text, out int lengthWithoutTags) inline private
Definition at line 95 of file LimitVisibleCharacters.cs.
    {
        MatchCollection matchCollection = Regex.Matches(text, "<b>|</b>|<i>|</i>|<size=.*?>|</size>|<color=.*?>|</color>|<material=.*?>|</material>");
        lengthWithoutTags = 0;
        int num = 0;
        foreach (Match item in matchCollection)
        {
            num += item.Length;
        }
        lengthWithoutTags = text.Length - num;
        return matchCollection;
    }
References item.
Referenced by ModifyMesh().
ModifyMesh()
override void LimitVisibleCharacters.ModifyMesh (VertexHelper vh) inline
Definition at line 41 of file LimitVisibleCharacters.cs.
    {
        if (!IsActive())
        {
            return;
        }
        vh.GetUIVertexStream(m_Verts);
        Text component = GetComponent<Text>();
        List<UIVertex> list = new List<UIVertex>();
        IEnumerator enumerator = null;
        Match match = null;
        string text = component.text.Substring(0, component.cachedTextGenerator.characterCountVisible);
        int lengthWithoutTags = text.Length;
        if (component.supportRichText)
        {
            enumerator = GetRegexMatchedTags(text, out lengthWithoutTags).GetEnumerator();
            match = null;
            if (enumerator.MoveNext())
            {
                match = (Match)enumerator.Current;
            }
        }
        if (visibleCharacterCount >= lengthWithoutTags)
        {
            return;
        }
        int num = 0;
        while (list.Count < visibleCharacterCount * 6)
        {
            bool flag = false;
            if (component.supportRichText && match != null && match.Index == num)
            {
                num += match.Length - 1;
                match = null;
                if (enumerator.MoveNext())
                {
                    match = (Match)enumerator.Current;
                }
                flag = true;
            }
            if (!flag)
            {
                for (int i = 0; i < 6; i++)
                {
                    UIVertex item = m_Verts[num * 6 + i];
                    list.Add(item);
                }
            }
            num++;
        }
        vh.Clear();
        vh.AddUIVertexTriangleStream(list);
    }
References GetRegexMatchedTags(), item, m_Verts, and visibleCharacterCount.
Member Data Documentation
m_Verts
List<UIVertex> LimitVisibleCharacters.m_Verts = new List<UIVertex>() private
Definition at line 16 of file LimitVisibleCharacters.cs.
Referenced by ModifyMesh().
m_VisibleCharacterCount
int LimitVisibleCharacters.m_VisibleCharacterCount private
Definition at line 14 of file LimitVisibleCharacters.cs.
REGEX_TAGS
const string LimitVisibleCharacters.REGEX_TAGS = "<b>|</b>|<i>|</i>|<size=.*?>|</size>|<color=.*?>|</color>|<material=.*?>|</material>" static private
Definition at line 11 of file LimitVisibleCharacters.cs.
Property Documentation
visibleCharacterCount
int LimitVisibleCharacters.visibleCharacterCount get set
Definition at line 18 of file LimitVisibleCharacters.cs.
    {
        get
        {
            return m_VisibleCharacterCount;
        }
        set
        {
            if (m_VisibleCharacterCount != value)
            {
                m_VisibleCharacterCount = value;
                if (base.graphic != null)
                {
                    base.graphic.SetVerticesDirty();
                }
            }
        }
    }
Referenced by ModifyMesh().
The documentation for this class was generated from the following file:
Elin/Plugins.UI/LimitVisibleCharacters.cs