Elin Decompiled Documentation: RoomManager Class Reference
RoomManager Class Reference
Public Member Functions
void OnLoad ()
void AssignCharas ()
void RefreshAll ()
void Refresh ()
void AssignUID (BaseArea a)
Area AddArea (Area a, Point p)
Area TryAddArea (Point p, Area existingArea)
void RemoveArea (Area a)
Room AddRoom (Room r)
void RemoveRoom (Room r)
HitResult GetHitResult (Point point, Point start)
void RebuildLots ()
BaseArea FindBaseArea (string id)
Public Attributes
List< Area > listArea = new List<Area>()
List< Room > listRoom = new List<Room>()
int uidRoom = 1
Dictionary< int, BaseArea > mapIDs = new Dictionary<int, BaseArea>()
List< Lot > listLot = new List<Lot>()
bool dirtyLots
bool dirtyRooms
Private Attributes
List< BaseArea > tempList = new List<BaseArea>()
Additional Inherited Members
Static Public Member Functions inherited from EClass
static int rnd (int a)
static int curve (int a, int start, int step, int rate=75)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Static Public Attributes inherited from EClass
static Core core
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Detailed Description
Definition at line 5 of file RoomManager.cs.
Member Function Documentation
AddArea()
Area RoomManager.AddArea (Area a, Point p) inline
Definition at line 76 of file RoomManager.cs.
    {
        if (!listArea.Contains(a))
        {
            listArea.Add(a);
            mapIDs.Add(a.uid, a);
        }
        a.AddPoint(p.Copy());
        return a;
    }
References Area.AddPoint(), Point.Copy(), listArea, mapIDs, and BaseArea.uid.
Referenced by AM_CreateArea.OnProcessTiles().
AddRoom()
Room RoomManager.AddRoom (Room r) inline
Definition at line 110 of file RoomManager.cs.
    {
        listRoom.Add(r);
        AssignUID(r);
        r.SetDirty();
        mapIDs.Add(r.uid, r);
        return r;
    }
References AssignUID(), listRoom, mapIDs, Room.SetDirty(), and BaseArea.uid.
Referenced by Map.TryAddRoom().
AssignCharas()
void RoomManager.AssignCharas () inline
Definition at line 39 of file RoomManager.cs.
    {
    }
Referenced by Chara.MoveZone(), and Zone.OnVisit().
AssignUID()
void RoomManager.AssignUID (BaseArea a) inline
Definition at line 70 of file RoomManager.cs.
    {
        a.uid = uidRoom;
        uidRoom++;
    }
References uidRoom.
Referenced by AddRoom(), and Area.Create().
FindBaseArea()
BaseArea RoomManager.FindBaseArea (string id) inline
Definition at line 164 of file RoomManager.cs.
    {
        tempList.Clear();
        foreach (BaseArea item in ((IEnumerable<BaseArea>)listRoom).Concat((IEnumerable<BaseArea>)listArea))
        {
            if (item.type.id == id)
            {
                tempList.Add(item);
            }
        }
        if (tempList.Count == 0)
        {
            return null;
        }
        return tempList.RandomItem();
    }
References item, listArea, listRoom, and tempList.
GetHitResult()
HitResult RoomManager.GetHitResult (Point point, Point start) inline
Definition at line 126 of file RoomManager.cs.
    {
        if (point.area != null)
        {
            return HitResult.Invalid;
        }
        if (!point.HasBlock)
        {
            return HitResult.Valid;
        }
        return HitResult.Default;
    }
References Point.area, and Point.HasBlock.
Referenced by AM_CreateArea.HitTest(), and AM_ExpandArea.HitTest().
OnLoad()
void RoomManager.OnLoad () inline
Definition at line 26 of file RoomManager.cs.
    {
        foreach (Area item in listArea)
        {
            item.OnLoad();
        }
        foreach (Room item2 in listRoom)
        {
            item2.OnLoad();
        }
        Refresh();
    }
References item, listArea, listRoom, Room.OnLoad(), and Refresh().
Referenced by Map.OnLoad().
RebuildLots()
void RoomManager.RebuildLots () inline
Definition at line 139 of file RoomManager.cs.
    {
        listLot.Clear();
        foreach (Room item in listRoom)
        {
            item.lot = null;
        }
        foreach (Room item2 in listRoom)
        {
            if (item2.lot == null)
            {
                Lot lot = new Lot
                {
                    x = item2.x,
                    z = item2.z,
                    mx = item2.mx,
                    mz = item2.mz
                };
                lot.SetBaseRoom(item2);
                listLot.Add(lot);
            }
        }
        dirtyLots = false;
    }
References dirtyLots, item, listLot, listRoom, Room.lot, Room.mx, Lot.SetBaseRoom(), Room.x, and Room.z.
Referenced by Refresh().
Refresh()
void RoomManager.Refresh () inline
Definition at line 52 of file RoomManager.cs.
    {
        if (dirtyRooms)
        {
            foreach (Room item in listRoom)
            {
                if (item.dirty)
                {
                    item.Refresh();
                }
            }
        }
        if (dirtyLots)
        {
            RebuildLots();
        }
    }
References dirtyLots, dirtyRooms, item, listRoom, and RebuildLots().
Referenced by BaseTileMap.Draw(), TileMapElona.Draw(), OnLoad(), and RefreshAll().
RefreshAll()
void RoomManager.RefreshAll () inline
Definition at line 43 of file RoomManager.cs.
    {
        foreach (Room item in listRoom)
        {
            item.SetDirty();
        }
        Refresh();
    }
References item, listRoom, and Refresh().
Referenced by BaseArea.ListInteractions(), and Map.ReloadRoom().
RemoveArea()
void RoomManager.RemoveArea (Area a) inline
Definition at line 103 of file RoomManager.cs.
    {
        listArea.Remove(a);
        mapIDs.Remove(a.uid);
        a.OnRemove();
    }
References listArea, mapIDs, Area.OnRemove(), and BaseArea.uid.
Referenced by AM_EditArea.OnProcessTiles(), and InspectGroupArea.OnSetActions().
RemoveRoom()
void RoomManager.RemoveRoom (Room r) inline
Definition at line 119 of file RoomManager.cs.
    {
        listRoom.Remove(r);
        mapIDs.Remove(r.uid);
        r.OnRemove();
    }
References listRoom, mapIDs, Room.OnRemove(), and BaseArea.uid.
Referenced by Map.TryRemoveRoom().
TryAddArea()
Area RoomManager.TryAddArea (Point p, Area existingArea) inline
Definition at line 87 of file RoomManager.cs.
    {
        if (p.area != null)
        {
            return existingArea;
        }
        if (existingArea == null)
        {
            existingArea = Area.Create("public");
            listArea.Add(existingArea);
            mapIDs.Add(existingArea.uid, existingArea);
        }
        existingArea.AddPoint(p.Copy());
        return existingArea;
    }
References Area.AddPoint(), Point.area, Point.Copy(), Area.Create(), listArea, mapIDs, and BaseArea.uid.
Member Data Documentation
dirtyLots
bool RoomManager.dirtyLots
Definition at line 22 of file RoomManager.cs.
Referenced by RebuildLots(), and Refresh().
dirtyRooms
bool RoomManager.dirtyRooms
Definition at line 24 of file RoomManager.cs.
Referenced by Refresh().
listArea
List<Area> RoomManager.listArea = new List<Area>()
Definition at line 10 of file RoomManager.cs.
Referenced by AddArea(), FindBaseArea(), Map.FindPublicArea(), GameUpdater.AreaUpdater.FixedUpdate(), AI_Idle.GetRandomAssignedRoom(), OnLoad(), LayerHome.RefreshAreas(), RemoveArea(), TryAddArea(), and GoalTask.TryAssignAreaTask().
listLot
List<Lot> RoomManager.listLot = new List<Lot>()
Definition at line 20 of file RoomManager.cs.
Referenced by BaseTileMap.Draw(), and RebuildLots().
listRoom
List<Room> RoomManager.listRoom = new List<Room>()
Definition at line 13 of file RoomManager.cs.
Referenced by Lot.AddConnectedRooms(), AddRoom(), FindBaseArea(), Map.FindPublicArea(), GoalWork.FindWork(), AI_Idle.GetRandomAssignedRoom(), Zone.GetRandomVisitPos(), OnLoad(), RebuildLots(), Refresh(), RefreshAll(), RemoveRoom(), Lot.SetBaseRoom(), AIWork_Chore.SetDestPos(), MeetingManager.SetRoom(), and GoalWork.ValidateHobby().
mapIDs
Dictionary<int, BaseArea> RoomManager.mapIDs = new Dictionary<int, BaseArea>()
Definition at line 18 of file RoomManager.cs.
Referenced by AddArea(), AddRoom(), RefArea.Get(), Area.OnLoad(), Room.OnLoad(), RemoveArea(), RemoveRoom(), and TryAddArea().
tempList
List<BaseArea> RoomManager.tempList = new List<BaseArea>() private
Definition at line 7 of file RoomManager.cs.
Referenced by FindBaseArea().
uidRoom
int RoomManager.uidRoom = 1
Definition at line 16 of file RoomManager.cs.
Referenced by AssignUID().
The documentation for this class was generated from the following file:
Elin/RoomManager.cs