Elin Decompiled Documentation: ThingStack Class Reference
ThingStack Class Reference
Public Member Functions
void Add (Thing t)
Public Attributes
List< Thing > list = new List<Thing>()
int count
int val
int max
Additional Inherited Members
Static Public Member Functions inherited from EClass
static int rndSeed (int a, int seed)
static int rnd (int a)
static int curve (int a, int start, int step, int rate=75)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Static Public Attributes inherited from EClass
static Core core
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Detailed Description
Definition at line 3 of file ThingStack.cs.
Member Function Documentation
Add()
void ThingStack.Add (Thing t) inline
Definition at line 13 of file ThingStack.cs.
    {
        list.Add(t);
        count += t.Num;
        if (t.Num > max)
        {
            max = t.Num;
        }
    }
References ActPlan.List.Add(), count, list, max, and Card.Num.
Referenced by ThingContainer.GetThingStack().
Member Data Documentation
count
int ThingStack.count
Definition at line 7 of file ThingStack.cs.
Referenced by Add(), ButtonGrid.RefreshCraftable(), UIRecipeInfo.RefreshList(), and ButtonGrid.WriteReqMat().
list
List<Thing> ThingStack.list = new List<Thing>()
Definition at line 5 of file ThingStack.cs.
Referenced by Add(), QuestTrackCraft.GetDetail(), DropdownGrid.ListIngredients(), Props.ListThingStack(), Props.ListThingStacksInCategory(), and DropdownGrid.TrySelect().
max
int ThingStack.max
Definition at line 11 of file ThingStack.cs.
Referenced by Add().
val
int ThingStack.val
Definition at line 9 of file ThingStack.cs.
The documentation for this class was generated from the following file:
Elin/ThingStack.cs