Elin Decompiled Documentation: GridItem Class Reference
GridItem Class Reference
Public Member Functions
virtual void SetButton (ButtonGrid b)
virtual void OnClick (ButtonGrid b)
virtual void AutoAdd ()
Additional Inherited Members
Static Public Member Functions inherited from EClass
static int rndSeed (int a, int seed)
static int rnd (long a)
static int rnd (int a)
static int curve (int a, int start, int step, int rate=75)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Static Public Attributes inherited from EClass
static Core core
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Detailed Description
Definition at line 1 of file GridItem.cs.
Member Function Documentation
AutoAdd()
virtual void GridItem.AutoAdd () inline virtual
Reimplemented in GridItemCard.
Definition at line 12 of file GridItem.cs.
    {
    }
OnClick()
virtual void GridItem.OnClick (ButtonGrid b) inline virtual
Reimplemented in GridItemCard, and GridItemRecipe.
Definition at line 8 of file GridItem.cs.
    {
    }
Referenced by DropdownGrid.Build(), and Dialog.OnAfterInit().
SetButton()
virtual void GridItem.SetButton (ButtonGrid b) inline virtual
Reimplemented in GridItemCard, GridItemCardSource, and GridItemRecipe.
Definition at line 3 of file GridItem.cs.
    {
        b.SetDummy();
    }
References ButtonGrid.SetDummy().
Referenced by DropdownGrid.Build(), and ButtonGrid.SetItem().
The documentation for this class was generated from the following file:
Elin/GridItem.cs