Elin Decompiled Documentation: SourcePerson Class Reference
SourcePerson Class Reference
Classes
class Row
Public Member Functions
override Row CreateRow ()
override Row CreateRowByMapping (IReadOnlyDictionary< string, int > mapping)
override void SetRow (Row r)
override IReadOnlyDictionary< string, int > GetRowMapping ()
override IReadOnlyDictionary< string, string > GetTypeMapping ()
Public Member Functions inherited from SourceDataString< SourcePerson.Row >
override T GetRow (string id)
Static Public Attributes
static readonly IReadOnlyDictionary< string, int > RowMapping
static readonly IReadOnlyDictionary< string, string > TypeMapping
Properties
override string[] ImportFields [get]
Detailed Description
Definition at line 4 of file SourcePerson.cs.
Member Function Documentation
CreateRow()
override Row SourcePerson.CreateRow () inline
Definition at line 93 of file SourcePerson.cs.
    {
        return new Row
        {
            id = SourceData.GetString(0),
            idActor = SourceData.GetString(1),
            name_JP = SourceData.GetString(2),
            name = SourceData.GetString(3),
            aka_JP = SourceData.GetString(4),
            aka = SourceData.GetString(5),
            portrait = SourceData.GetString(6),
            faction = SourceData.GetString(7),
            LV = SourceData.GetInt(8),
            job = SourceData.GetString(9),
            race = SourceData.GetString(10),
            material = SourceData.GetString(11),
            bio = SourceData.GetString(12),
            detail_JP = SourceData.GetString(13),
            detail = SourceData.GetString(14)
        };
    }
References SourceData< T, T2 >.GetInt(), SourceData< T, T2 >.GetString(), and material.
CreateRowByMapping()
override Row SourcePerson.CreateRowByMapping (IReadOnlyDictionary< string, int > mapping) inline
Definition at line 115 of file SourcePerson.cs.
    {
        return new Row
        {
            id = SourceData.GetString(mapping["id"]),
            idActor = SourceData.GetString(mapping["idActor"]),
            name_JP = SourceData.GetString(mapping["name_JP"]),
            name = SourceData.GetString(mapping["name"]),
            aka_JP = SourceData.GetString(mapping["aka_JP"]),
            aka = SourceData.GetString(mapping["aka"]),
            portrait = SourceData.GetString(mapping["portrait"]),
            faction = SourceData.GetString(mapping["faction"]),
            LV = SourceData.GetInt(mapping["LV"]),
            job = SourceData.GetString(mapping["job"]),
            race = SourceData.GetString(mapping["race"]),
            material = SourceData.GetString(mapping["material"]),
            bio = SourceData.GetString(mapping["bio"]),
            detail_JP = SourceData.GetString(mapping["detail_JP"]),
            detail = SourceData.GetString(mapping["detail"])
        };
    }
References SourceData< T, T2 >.GetInt(), SourceData< T, T2 >.GetString(), and material.
GetRowMapping()
override IReadOnlyDictionary< string, int > SourcePerson.GetRowMapping () inline
Definition at line 142 of file SourcePerson.cs.
    {
        return RowMapping;
    }
References RowMapping.
GetTypeMapping()
override IReadOnlyDictionary< string, string > SourcePerson.GetTypeMapping () inline
Definition at line 147 of file SourcePerson.cs.
    {
        return TypeMapping;
    }
References TypeMapping.
SetRow()
override void SourcePerson.SetRow (Row r) inline
Definition at line 137 of file SourcePerson.cs.
    {
        map[r.id] = r;
    }
References SourcePerson.Row.id.
Member Data Documentation
RowMapping
readonly IReadOnlyDictionary<string, int> SourcePerson.RowMapping static
Initial value:
= new Dictionary<string, int>
    {
        ["id"] = 0,
        ["idActor"] = 1,
        ["name_JP"] = 2,
        ["name"] = 3,
        ["aka_JP"] = 4,
        ["aka"] = 5,
        ["portrait"] = 6,
        ["faction"] = 7,
        ["LV"] = 8,
        ["job"] = 9,
        ["race"] = 10,
        ["material"] = 11,
        ["bio"] = 12,
        ["detail_JP"] = 13,
        ["detail"] = 14
    }
Definition at line 53 of file SourcePerson.cs.
Referenced by GetRowMapping().
TypeMapping
readonly IReadOnlyDictionary<string, string> SourcePerson.TypeMapping static
Initial value:
= new Dictionary<string, string>
    {
        ["id"] = "string",
        ["idActor"] = "string",
        ["name_JP"] = "string",
        ["name"] = "string",
        ["aka_JP"] = "string",
        ["aka"] = "string",
        ["portrait"] = "string",
        ["faction"] = "string",
        ["LV"] = "int",
        ["job"] = "string",
        ["race"] = "string",
        ["material"] = "string",
        ["bio"] = "string",
        ["detail_JP"] = "string",
        ["detail"] = "string"
    }
Definition at line 72 of file SourcePerson.cs.
Referenced by GetTypeMapping().
Property Documentation
ImportFields
override string [] SourcePerson.ImportFields get
Definition at line 91 of file SourcePerson.cs.
The documentation for this class was generated from the following file:
Elin/SourcePerson.cs