Elin Decompiled Documentation: DramaEventEndRoll Class Reference
DramaEventEndRoll Class Reference
Public Member Functions
override bool Play ()
void Init ()
Public Member Functions inherited from DramaEvent
virtual bool Play ()
virtual void Reset ()
Properties
UIDynamicList list [get]
Properties inherited from DramaEvent
DramaActor actor [get]
DramaManager manager [get]
LayerDrama layer [get]
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Private Attributes
float timer
Additional Inherited Members
Static Public Member Functions inherited from EClass
static int rndSeed (int a, int seed)
static int rnd (long a)
static int rnd (int a)
static int curve (int a, int start, int step, int rate=75)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Public Attributes inherited from DramaEvent
int progress
string idJump
string idActor
string step
float time
bool temp
DramaSequence sequence
Static Public Attributes inherited from EClass
static Core core
Detailed Description
Definition at line 5 of file DramaEventEndRoll.cs.
Member Function Documentation
Init()
void DramaEventEndRoll.Init () inline
Definition at line 54 of file DramaEventEndRoll.cs.
    {
        ExcelData excelData = new ExcelData("Data/Raw/credit", 1);
        List<Dictionary<string, string>> items = excelData.BuildList();
        int index = 0;
        list.Clear();
        list.callbacks = new UIList.Callback<string, UIItem>
        {
            onRedraw = delegate(string a, UIItem b, int i)
            {
                b.text1.SetText(BackerContent.ConvertName(a));
            },
            onList = delegate
            {
                List<string> list = IO.LoadTextArray(CorePath.CorePackage.TextCommon + "endroll").ToList();
                for (int k = 0; k < Screen.height / 32 + 1; k++)
                {
                    Space(newline: true);
                }
                foreach (string item in list)
                {
                    if (item.StartsWith("#"))
                    {
                        string[] array = item.Replace("#", "").Split(',');
                        string text = array[0];
                        int num2 = array[1].ToInt();
                        foreach (Dictionary<string, string> item2 in items)
{
                            if (index % 5 < num2)
{
                                for (int l = 0; l < num2; l++)
{
                                    this.list.Add("");
                                    index++;
                                }
                            }
                            if ((text == "Abandon" && item2["abandon"] == "Yes") || item2["Pledge"] == text)
{
                                AddBacker(item2["Name"]);
                            }
                            if (index % 5 >= 5 - num2)
{
                                for (int n = 0; n < num2; n++)
{
                                    this.list.Add("");
                                    index++;
                                }
                            }
                        }
                    }
                    else
                    {
                        Add(item);
                    }
                }
                for (int num3 = 0; num3 < Screen.height / 32 / 2 - 1; num3++)
                {
                    Space(newline: true);
                }
            }
        };
        list.List();
        void Add(string s)
        {
            Space(newline: false);
            list.Add("");
            list.Add("");
            list.Add(s);
            list.Add("");
            list.Add("");
            index += 5;
        }
        void AddBacker(string s)
        {
            list.Add(s);
            index++;
        }
        void Space(bool newline)
        {
            int num = (newline ? 5 : 0);
            if (index % 5 != 0)
            {
                num += 5 - index % 5;
            }
            for (int j = 0; j < num; j++)
            {
                list.Add("");
                index++;
            }
        }
    }
References Add(), UIDynamicList.Add(), ExcelData.BuildList(), UIDynamicList.Clear(), BackerContent.ConvertName(), item, list, UIDynamicList.List(), UIText.SetText(), UIItem.text1, and CorePath.CorePackage.TextCommon.
Referenced by Play().
Play()
override bool DramaEventEndRoll.Play () inline virtual
Reimplemented from DramaEvent.
Definition at line 11 of file DramaEventEndRoll.cs.
    {
        if (progress == 0)
        {
            sequence.manager.endroll.SetActive(enable: true);
            Init();
            progress++;
        }
        else
        {
            timer += Time.deltaTime;
            if (timer < 0.08f)
            {
                return false;
            }
            if (Input.GetKeyDown(KeyCode.Escape))
            {
                return true;
            }
            if (list.dsv.contentAnchoredPosition <= 0f - list.dsv.contentSize + list.dsv.viewportSize + 1f)
            {
                if ((!EInput.rightMouse.pressedLong || !Application.isEditor) && EInput.IsAnyKeyDown())
                {
                    return true;
                }
            }
            else
            {
                float num = 1f;
                if (EInput.leftMouse.pressing)
                {
                    num = 10f;
                }
                if (EInput.rightMouse.pressing)
                {
                    num = (Application.isEditor ? 200f : 30f);
                }
                list.dsv.contentAnchoredPosition += Time.deltaTime * sequence.manager.creditSpeed * num;
            }
        }
        return false;
    }
References UIDynamicList.dsv, DramaManager.endroll, Init(), EInput.IsAnyKeyDown(), EInput.leftMouse, list, DramaSequence.manager, ButtonState.pressedLong, ButtonState.pressing, DramaEvent.progress, EInput.rightMouse, DramaEvent.sequence, and timer.
Member Data Documentation
timer
float DramaEventEndRoll.timer private
Definition at line 7 of file DramaEventEndRoll.cs.
Referenced by Play().
Property Documentation
list
UIDynamicList DramaEventEndRoll.list get
Definition at line 9 of file DramaEventEndRoll.cs.
Referenced by Init(), and Play().
The documentation for this class was generated from the following file:
Elin/DramaEventEndRoll.cs