Elin Decompiled Documentation: ListPeopleBed Class Reference
ListPeopleBed Class Reference
Public Member Functions
override void OnInstantiate (Chara c, ItemGeneral i)
override void OnClick (Chara c, ItemGeneral i)
override void OnList ()
override void OnRefreshMenu ()
Public Member Functions inherited from BaseListPeople
virtual bool IsDisabled (Chara c)
override void List ()
override void OnInstantiate (Chara a, ItemGeneral b)
void AddSubButtonWork (ItemGeneral b, Chara a)
void WriteHobbies (UITooltip t, Chara a, BaseArea roomWork)
virtual void SetSubText (Chara a, ItemGeneral b)
override void OnClick (Chara c, ItemGeneral i)
override void OnList ()
override void OnRefreshMenu ()
Public Member Functions inherited from ListOwner< Chara, ItemGeneral >
virtual void OnClick (T1 a, T2 b)
virtual void OnInstantiate (T1 a, T2 b)
virtual void OnList ()
virtual void List ()
virtual void OnCreate ()
virtual void OnSwitchContent ()
virtual void OnRefreshMenu ()
void RefreshTab ()
void MoveToOther (object c)
Public Attributes
TraitBed bed
Public Attributes inherited from BaseListPeople
Chara owner
FactionMemberType memberType
Public Attributes inherited from ListOwner< Chara, ItemGeneral >
Layer layer
Window window
UIMultiList multi
ListOwner other
UIList list
WindowMenu menu
Window.Setting.Tab tab
string textTab
string textHeader
bool main
int index
Properties
BedType bedType [get]
Properties inherited from ListPeople
override string TextTab [get]
override bool ShowCharaSheet [get]
override bool ShowGoto [get]
override bool ShowHome [get]
override bool ShowShowMode [get]
Properties inherited from BaseListPeople
new LayerPeople layer [get]
override string IdHeaderRow [get]
virtual bool ShowCharaSheet [get]
virtual bool ShowShowMode [get]
virtual LayerPeople.ShowMode ShowMode [get]
virtual bool ShowGoto [get]
virtual bool ShowHome [get]
Properties inherited from ListOwner< Chara, ItemGeneral >
ListOwner Main [get]
virtual string IdTitle [get]
virtual string IdHeaderRow [get]
virtual string TextTab [get]
virtual string TextHeader [get]
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Additional Inherited Members
Static Public Member Functions inherited from EClass
static int rndSeed (int a, int seed)
static int rnd (int a)
static int curve (int a, int start, int step, int rate=75)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Static Public Attributes inherited from EClass
static Core core
Detailed Description
Definition at line 1 of file ListPeopleBed.cs.
Member Function Documentation
OnClick()
override void ListPeopleBed.OnClick (Chara c, ItemGeneral i) inline
Definition at line 21 of file ListPeopleBed.cs.
    {
        if (main)
        {
            if (!bed.CanAssign(c))
            {
                SE.Beep();
                return;
            }
            c.FindBed()?.RemoveHolder(c);
            bed.AddHolder(c);
        }
        else
        {
            bed.RemoveHolder(c);
        }
        MoveToOther(c);
        base.Main.OnRefreshMenu();
    }
References TraitBed.AddHolder(), bed, TraitBed.CanAssign(), Chara.FindBed(), ListOwner< Chara, ItemGeneral >.main, ListOwner< Chara, ItemGeneral >.MoveToOther(), and TraitBed.RemoveHolder().
OnInstantiate()
override void ListPeopleBed.OnInstantiate (Chara c, ItemGeneral i) inline
Definition at line 7 of file ListPeopleBed.cs.
    {
        UIButton uIButton = i.AddSubButton(EClass.core.refs.icons.bed, delegate
        {
        }, null, delegate
        {
        });
        uIButton.icon.SetAlpha((c.FindBed() != null) ? 0.9f : 0.4f);
        uIButton.SetTooltip(delegate(UITooltip t)
        {
            WriteHobbies(t, c, c.GetRoomWork());
        });
    }
References ItemGeneral.AddSubButton(), CoreRef.Icons.bed, EClass.core, Chara.FindBed(), Chara.GetRoomWork(), UIButton.icon, CoreRef.icons, Core.refs, UIButton.SetTooltip(), and BaseListPeople.WriteHobbies().
OnList()
override void ListPeopleBed.OnList () inline virtual
Reimplemented from BaseListPeople.
Definition at line 41 of file ListPeopleBed.cs.
    {
        foreach (Chara chara in EClass._map.charas)
        {
            if (!chara.IsPCFaction || (chara.memberType != 0 && chara.memberType != FactionMemberType.Livestock))
            {
                continue;
            }
            if (main)
            {
                if (bedType == BedType.livestock)
                {
                    if (chara.memberType != FactionMemberType.Livestock)
                    {
                        continue;
                    }
                }
                else if (chara.memberType == FactionMemberType.Livestock)
                {
                    continue;
                }
                if (!bed.IsHolder(chara))
                {
                    list.Add(chara);
                }
            }
            else if (bed.IsHolder(chara))
            {
                list.Add(chara);
            }
        }
    }
References EClass._map, UIList.Add(), bed, bedType, Map.charas, TraitBed.IsHolder(), Chara.IsPCFaction, ListOwner< Chara, ItemGeneral >.list, ListOwner< Chara, ItemGeneral >.main, and Chara.memberType.
OnRefreshMenu()
override void ListPeopleBed.OnRefreshMenu () inline virtual
Reimplemented from BaseListPeople.
Definition at line 74 of file ListPeopleBed.cs.
    {
    }
Member Data Documentation
bed
TraitBed ListPeopleBed.bed
Definition at line 3 of file ListPeopleBed.cs.
Referenced by OnClick(), and OnList().
Property Documentation
bedType
BedType ListPeopleBed.bedType get
Definition at line 5 of file ListPeopleBed.cs.
Referenced by OnList().
The documentation for this class was generated from the following file:
Elin/ListPeopleBed.cs