Elin Decompiled Documentation: SourceData< T, T2 > Class Template Reference
SourceData< T, T2 > Class Template Reference
Classes
class BaseRow
class FieldInfo
class FieldMap
Public Types
enum AutoID { None , Auto }
Public Member Functions
override void Init ()
virtual void OnInit ()
virtual void SetRow (T row)
override void Reset ()
override bool ImportData (ISheet sheet, string bookname, bool overwrite=false)
virtual void OnAfterImportData ()
virtual T CreateRow ()
virtual T CreateRowByMapping (IReadOnlyDictionary< string, int > mapping)
override int ImportRows (IEnumerable< BaseRow > sourceRows)
virtual void RemoveDuplicateRows ()
override void BackupSource ()
override void RollbackSource ()
List< string > GetListString ()
SourceData< T, T2 > BuildEditorList ()
List< FieldInfo > GetFields ()
virtual T GetRow (string id)
override void ExportTexts (string path, bool update=false)
override void ValidateLang ()
override void ImportTexts (string _nameSheet=null)
void BuildFlags (string rawText, Dictionary< string, bool > map)
virtual void Reset ()
virtual void InsertData (IRow row)
virtual void Init ()
virtual string[] GetList (string id)
virtual bool ImportData (ISheet sheet, string bookname, bool overwrite=false)
virtual int ImportRows (IEnumerable< BaseRow > sourceRows)
virtual void BackupSource ()
virtual void RollbackSource ()
virtual void BackupPref ()
virtual void RestorePref ()
virtual void ValidatePref ()
virtual void ExportTexts (string path, bool update=false)
virtual void ImportTexts (string _nameSheet=null)
virtual void ValidateLang ()
virtual IReadOnlyDictionary< string, int > GetRowMapping ()
Static Public Member Functions
static ICell GetCell (int x, int y)
static bool IsNull (ICell cell)
static int GetInt (int id)
static bool GetBool (int id)
static double GetDouble (int id)
static float GetFloat (int id)
static float[] GetFloatArray (int id)
static int[] GetIntArray (int id)
static string[] GetStringArray (int id)
static string GetString (int id)
static string GetStr (int id, bool useDefault=false)
Public Attributes
List< T > rows = new List<T>()
Dictionary< T2, T > map = new Dictionary<T2, T>()
Dictionary< string, T > alias = new Dictionary<string, T>()
bool initialized
List< string > editorListString = new List<string>()
AutoID autoID
bool isNew = true
string nameSheet
string nameBook
Static Public Attributes
static ISheet currentSheet
static string LangSuffix
static string dataPath
Properties
virtual bool AllowHotInitialization [get]
virtual string[] ImportFields [get]
virtual string sheetName [get]
virtual string sourcePath [get]
static IRow row [get, set]
static IRow rowDefault [get, set]
static IRow rowHeader [get, set]
Private Attributes
List< T > _backupRows = new List<T>()
Detailed Description
Type Constraints
T : SourceData.BaseRow
Definition at line 11 of file SourceData.cs.
Member Enumeration Documentation
AutoID
enum SourceData.AutoID
Enumerator
None
Auto
Definition at line 617 of file SourceData.cs.
    {
        None,
        Auto
    }
Member Function Documentation
BackupPref()
virtual void SourceData< T, T2 >.BackupPref () inline virtual
Definition at line 910 of file SourceData.cs.
    {
    }
BackupSource() [1/2]
override void SourceData< T, T2 >.BackupSource () inline
Definition at line 268 of file SourceData.cs.
    {
        _backupRows = rows;
    }
References SourceData< T, T2 >._backupRows, and SourceData< T, T2 >.rows.
BackupSource() [2/2]
virtual void SourceData< T, T2 >.BackupSource () inline virtual
Definition at line 902 of file SourceData.cs.
    {
    }
BuildEditorList()
SourceData< T, T2 > SourceData< T, T2 >.BuildEditorList () inline
Definition at line 283 of file SourceData.cs.
    {
        if (editorListString.Count == 0)
        {
            foreach (T row in rows)
            {
                editorListString.Add(row.GetEditorListName());
            }
        }
        return this;
    }
References SourceData< T, T2 >.editorListString, SourceData< T, T2 >.row, and SourceData< T, T2 >.rows.
Referenced by SourceData< T, T2 >.GetListString().
BuildFlags()
void SourceData< T, T2 >.BuildFlags (string rawText, Dictionary< string, bool > map) inline
Definition at line 863 of file SourceData.cs.
    {
        if (!string.IsNullOrEmpty(rawText))
        {
            string[] array = rawText.Split(',');
            foreach (string key in array)
            {
                map.Add(key, value: true);
            }
        }
    }
References SourceData< T, T2 >.map.
CreateRow()
virtual T SourceData< T, T2 >.CreateRow () inline virtual
Definition at line 205 of file SourceData.cs.
    {
        return null;
    }
Referenced by SourceData< T, T2 >.ImportData().
CreateRowByMapping()
virtual T SourceData< T, T2 >.CreateRowByMapping (IReadOnlyDictionary< string, int > mapping) inline virtual
Definition at line 210 of file SourceData.cs.
    {
        return null;
    }
Referenced by SourceData< T, T2 >.ImportData().
ExportTexts() [1/2]
override void SourceData< T, T2 >.ExportTexts (string path, bool update = false) inline
Definition at line 360 of file SourceData.cs.
    {
        Debug.Log("Exporting:" + nameSheet + " path:" + path);
        string text = nameSheet + ".xlsx";
        XSSFWorkbook xSSFWorkbook = new XSSFWorkbook();
        List<FieldInfo> fields = GetFields();
        currentSheet = xSSFWorkbook.CreateSheet(nameSheet);
        int num = 0;
        int y = 0;
        foreach (FieldInfo item in fields)
        {
            GetCell(num, y).SetCellValue(item.name);
            currentSheet.SetColumnWidth(num, item.width);
            ICellStyle cellStyle = xSSFWorkbook.CreateCellStyle();
            cellStyle.FillForegroundColor = 44;
            cellStyle.FillPattern = FillPattern.SolidForeground;
            if (!item.isStatic && item.id != "version")
            {
                GetCell(num, y).CellStyle = cellStyle;
            }
            num++;
        }
        string cellValue = BaseCore.Instance.version.GetText() ?? "";
        y = 2;
        foreach (T row4 in rows)
        {
            foreach (FieldInfo item2 in fields)
            {
                if (item2.isStatic)
                {
                    GetCell(item2.column, y).SetCellValue(item2.GetValue(row4));
                }
                else if (item2.id == "version")
                {
                    GetCell(item2.column, y).SetCellValue(cellValue);
                }
            }
            y++;
        }
        currentSheet.CreateFreezePane(0, 2);
        currentSheet.SetAutoFilter(new CellRangeAddress(1, 1, 0, fields.Count - 1));
        if (update)
        {
            Dictionary<string, int> dictionary = new Dictionary<string, int>();
            if (!File.Exists(path + "_temp/" + text))
            {
                return;
            }
            XSSFWorkbook xSSFWorkbook2;
            using (FileStream @is = File.Open(path + "_temp/" + text, FileMode.Open, FileAccess.Read, FileShare.ReadWrite))
            {
                xSSFWorkbook2 = new XSSFWorkbook((Stream)@is);
            }
            ISheet sheetAt = xSSFWorkbook2.GetSheetAt(0);
            IRow row = sheetAt.GetRow(0);
            int num2 = 0;
            foreach (FieldInfo item3 in fields)
            {
                if (item3.isStatic)
                {
                    continue;
                }
                int num3 = -1;
                for (int i = 0; i < row.LastCellNum; i++)
                {
                    string stringCellValue = row.GetCell(i).StringCellValue;
                    if (stringCellValue.IsEmpty())
                    {
                        break;
                    }
                    if (stringCellValue == item3.id)
                    {
                        num3 = i;
                        break;
                    }
                }
                if (num3 == -1)
                {
                    continue;
                }
                dictionary.Add(item3.id, 0);
                for (y = 2; y <= sheetAt.LastRowNum; y++)
                {
                    IRow row2 = sheetAt.GetRow(y);
                    if (row2 == null)
                    {
                        if (y > 5)
{
                            break;
                        }
                        continue;
                    }
                    ICell cell = row2.GetCell(0);
                    if (cell == null)
                    {
                        continue;
                    }
                    string text2 = ((cell.CellType == CellType.Numeric) ? cell.NumericCellValue.ToString() : cell.StringCellValue);
                    if (text2.IsEmpty())
                    {
                        continue;
                    }
                    for (int j = 0; j <= currentSheet.LastRowNum; j++)
                    {
                        IRow row3 = currentSheet.GetRow(j);
                        if (row3 == null)
{
                            if (j > 5)
{
                                break;
                            }
                            continue;
                        }
                        ICell cell2 = row3.GetCell(0);
                        if (cell2 == null || cell2.StringCellValue != text2)
{
                            continue;
                        }
                        string text3 = row2.GetCell(num3)?.StringCellValue ?? "";
                        if (text3.IsEmpty())
{
                            continue;
                        }
                        (row3.GetCell(item3.column) ?? row3.CreateCell(item3.column)).SetCellValue(text3);
                        if (item3.id != "version")
{
                            ICell cell3 = row3.GetCell(item3.column + 2);
                            ICell cell4 = row2.GetCell(num3 + 2);
                            if (cell3 == null)
{
                                continue;
                            }
                            if (cell4 == null || cell3.StringCellValue != cell4.StringCellValue)
{
                                row3.GetCell(1).SetCellValue(cellValue);
                            }
                            num2++;
                        }
                        dictionary[item3.id]++;
                    }
                }
            }
            Log.system = Log.system + ((num2 == 0) ? "(No Changes) " : "(Updated) ") + path + "/" + text + Environment.NewLine;
            if (num2 != 0)
            {
                foreach (KeyValuePair<string, int> item4 in dictionary)
                {
                    Log.system = Log.system + item4.Key + ":" + item4.Value + "  ";
                }
                Log.system += Environment.NewLine;
            }
            Log.system += Environment.NewLine;
        }
        if (!Directory.Exists(path))
        {
            Directory.CreateDirectory(path);
        }
        using FileStream stream = new FileStream(path + "/" + text, FileMode.Create, FileAccess.Write, FileShare.ReadWrite);
        xSSFWorkbook.Write(stream);
    }
References SourceData< T, T2 >.FieldInfo.column, SourceData< T, T2 >.currentSheet, Debug, SourceData< T, T2 >.GetCell(), SourceData< T, T2 >.GetFields(), Version.GetText(), SourceData< T, T2 >.FieldInfo.GetValue(), SourceData< T, T2 >.FieldInfo.id, BaseCore.Instance, SourceData< T, T2 >.FieldInfo.isStatic, item, SourceData< T, T2 >.nameSheet, SourceData< T, T2 >.row, SourceData< T, T2 >.rows, and BaseCore.version.
ExportTexts() [2/2]
virtual void SourceData< T, T2 >.ExportTexts (string path, bool update = false) inline virtual
Definition at line 922 of file SourceData.cs.
    {
    }
GetBool()
static bool SourceData< T, T2 >.GetBool (int id) inline static
Definition at line 953 of file SourceData.cs.
    {
        return ExcelParser.GetBool(id);
    }
References ExcelParser.GetBool().
Referenced by SourceBacker.CreateRow(), SourceBlock.CreateRow(), SourceCategory.CreateRow(), SourceStat.CreateRow(), SourceBacker.CreateRowByMapping(), SourceBlock.CreateRowByMapping(), SourceCategory.CreateRowByMapping(), and SourceStat.CreateRowByMapping().
GetCell()
static ICell SourceData< T, T2 >.GetCell (int x, int y) inline static
Definition at line 609 of file SourceData.cs.
    {
        IRow row = currentSheet.GetRow(y) ?? currentSheet.CreateRow(y);
        return row.GetCell(x) ?? row.CreateCell(x);
    }
References SourceData< T, T2 >.currentSheet, and SourceData< T, T2 >.row.
Referenced by SourceData< T, T2 >.ExportTexts().
GetDouble()
static double SourceData< T, T2 >.GetDouble (int id) inline static
Definition at line 958 of file SourceData.cs.
    {
        return ExcelParser.GetDouble(id);
    }
References ExcelParser.GetDouble().
GetFields()
List< FieldInfo > SourceData< T, T2 >.GetFields () inline
Definition at line 295 of file SourceData.cs.
    {
        List<FieldInfo> list = new List<FieldInfo>();
        int x = 0;
        AddField("id", 4096);
        AddField("version", 4096);
        AddField("filter", 4096);
        AddField("name", 4096);
        AddField("text", 4096);
        AddField("detail", 4096);
        AddField("description", 4096);
        string[] importFields = ImportFields;
        foreach (string text in importFields)
        {
            if (!text.IsEmpty())
            {
                AddField(text, 4096);
            }
        }
        return list;
        void AddField(string id, int width)
        {
            bool flag = id == "id" || id == "filter";
            bool flag2 = id == "version";
            if (!(typeof(T).GetField(id) == null) || flag2)
            {
                list.Add(new FieldInfo
                {
                    id = id,
                    name = id,
                    isStatic = flag,
                    width = width,
                    column = x
                });
                x++;
                if (!(flag || flag2))
                {
                    list.Add(new FieldInfo
                    {
                        id = id,
                        name = id + "_EN",
                        isStatic = true,
                        width = width,
                        column = x
                    });
                    x++;
                    list.Add(new FieldInfo
                    {
                        id = id + "_JP",
                        name = id + "_JP",
                        isStatic = true,
                        width = width,
                        column = x
                    });
                    x++;
                }
            }
        }
    }
References SourceData< T, T2 >.ImportFields.
Referenced by SourceData< T, T2 >.ExportTexts(), and SourceData< T, T2 >.ImportTexts().
GetFloat()
static float SourceData< T, T2 >.GetFloat (int id) inline static
Definition at line 963 of file SourceData.cs.
    {
        return ExcelParser.GetFloat(id);
    }
References ExcelParser.GetFloat().
Referenced by SourceCheck.CreateRow(), SourceDeco.CreateRow(), SourceElement.CreateRow(), SourceFloor.CreateRow(), SourceCheck.CreateRowByMapping(), SourceDeco.CreateRowByMapping(), SourceElement.CreateRowByMapping(), and SourceFloor.CreateRowByMapping().
GetFloatArray()
static float[] SourceData< T, T2 >.GetFloatArray (int id) inline static
Definition at line 968 of file SourceData.cs.
    {
        return ExcelParser.GetFloatArray(id);
    }
References ExcelParser.GetFloatArray().
GetInt()
static int SourceData< T, T2 >.GetInt (int id) inline static
Definition at line 948 of file SourceData.cs.
    {
        return ExcelParser.GetInt(id);
    }
References ExcelParser.GetInt().
Referenced by LangWord.CreateRow(), SourceBacker.CreateRow(), SourceBlock.CreateRow(), SourceCategory.CreateRow(), SourceCellEffect.CreateRow(), SourceChara.CreateRow(), SourceCheck.CreateRow(), SourceCollectible.CreateRow(), SourceDeco.CreateRow(), SourceElement.CreateRow(), SourceFaction.CreateRow(), SourceFloor.CreateRow(), SourceFood.CreateRow(), SourceGlobalTile.CreateRow(), SourceHobby.CreateRow(), SourceHomeResource.CreateRow(), SourceJob.CreateRow(), SourceKeyItem.CreateRow(), SourceMaterial.CreateRow(), SourceObj.CreateRow(), SourcePerson.CreateRow(), SourceQuest.CreateRow(), SourceRace.CreateRow(), SourceRecipe.CreateRow(), SourceReligion.CreateRow(), SourceResearch.CreateRow(), SourceStat.CreateRow(), SourceTactics.CreateRow(), SourceThing.CreateRow(), SourceThingV.CreateRow(), SourceZone.CreateRow(), SourceZoneAffix.CreateRow(), LangWord.CreateRowByMapping(), SourceBacker.CreateRowByMapping(), SourceBlock.CreateRowByMapping(), SourceCategory.CreateRowByMapping(), SourceCellEffect.CreateRowByMapping(), SourceChara.CreateRowByMapping(), SourceCheck.CreateRowByMapping(), SourceCollectible.CreateRowByMapping(), SourceDeco.CreateRowByMapping(), SourceElement.CreateRowByMapping(), SourceFaction.CreateRowByMapping(), SourceFloor.CreateRowByMapping(), SourceFood.CreateRowByMapping(), SourceGlobalTile.CreateRowByMapping(), SourceHobby.CreateRowByMapping(), SourceHomeResource.CreateRowByMapping(), SourceJob.CreateRowByMapping(), SourceKeyItem.CreateRowByMapping(), SourceMaterial.CreateRowByMapping(), SourceObj.CreateRowByMapping(), SourcePerson.CreateRowByMapping(), SourceQuest.CreateRowByMapping(), SourceRace.CreateRowByMapping(), SourceRecipe.CreateRowByMapping(), SourceReligion.CreateRowByMapping(), SourceResearch.CreateRowByMapping(), SourceStat.CreateRowByMapping(), SourceTactics.CreateRowByMapping(), SourceThing.CreateRowByMapping(), SourceThingV.CreateRowByMapping(), SourceZone.CreateRowByMapping(), and SourceZoneAffix.CreateRowByMapping().
GetIntArray()
static int[] SourceData< T, T2 >.GetIntArray (int id) inline static
Definition at line 973 of file SourceData.cs.
    {
        return ExcelParser.GetIntArray(id);
    }
References ExcelParser.GetIntArray().
Referenced by SourceBlock.CreateRow(), SourceCellEffect.CreateRow(), SourceChara.CreateRow(), SourceDeco.CreateRow(), SourceElement.CreateRow(), SourceFloor.CreateRow(), SourceFood.CreateRow(), SourceGlobalTile.CreateRow(), SourceHobby.CreateRow(), SourceObj.CreateRow(), SourceRace.CreateRow(), SourceStat.CreateRow(), SourceThing.CreateRow(), SourceThingV.CreateRow(), SourceZone.CreateRow(), SourceBlock.CreateRowByMapping(), SourceCellEffect.CreateRowByMapping(), SourceChara.CreateRowByMapping(), SourceDeco.CreateRowByMapping(), SourceElement.CreateRowByMapping(), SourceFloor.CreateRowByMapping(), SourceFood.CreateRowByMapping(), SourceGlobalTile.CreateRowByMapping(), SourceHobby.CreateRowByMapping(), SourceObj.CreateRowByMapping(), SourceRace.CreateRowByMapping(), SourceStat.CreateRowByMapping(), SourceThing.CreateRowByMapping(), SourceThingV.CreateRowByMapping(), and SourceZone.CreateRowByMapping().
GetList()
virtual string[] SourceData< T, T2 >.GetList (string id) inline virtual
Definition at line 887 of file SourceData.cs.
    {
        return null;
    }
Referenced by Lang.GetList().
GetListString()
List< string > SourceData< T, T2 >.GetListString () inline
Definition at line 278 of file SourceData.cs.
    {
        return BuildEditorList().editorListString;
    }
References SourceData< T, T2 >.BuildEditorList().
GetRow()
virtual T SourceData< T, T2 >.GetRow (string id) inline virtual
Reimplemented in SourceDataInt< T >, SourceDataString< T >, and SourceLang< T >.
Definition at line 355 of file SourceData.cs.
    {
        return null;
    }
Referenced by SourceData< T, T2 >.ImportTexts().
GetRowMapping()
virtual IReadOnlyDictionary< string, int > SourceData< T, T2 >.GetRowMapping () inline virtual
Definition at line 934 of file SourceData.cs.
    {
        return null;
    }
Referenced by SourceData< T, T2 >.ImportData().
GetStr()
static string SourceData< T, T2 >.GetStr (int id, bool useDefault = false) inline static
Definition at line 988 of file SourceData.cs.
    {
        return ExcelParser.GetStr(id, useDefault);
    }
References ExcelParser.GetStr().
Referenced by SourceCategory.CreateRow(), SourceChara.CreateRow(), SourceCheck.CreateRow(), SourceFood.CreateRow(), SourceHobby.CreateRow(), SourceJob.CreateRow(), SourceMaterial.CreateRow(), SourceRace.CreateRow(), SourceReligion.CreateRow(), SourceThing.CreateRow(), SourceCategory.CreateRowByMapping(), SourceChara.CreateRowByMapping(), SourceCheck.CreateRowByMapping(), SourceFood.CreateRowByMapping(), SourceHobby.CreateRowByMapping(), SourceJob.CreateRowByMapping(), SourceMaterial.CreateRowByMapping(), SourceRace.CreateRowByMapping(), SourceReligion.CreateRowByMapping(), and SourceThing.CreateRowByMapping().
GetString()
static string SourceData< T, T2 >.GetString (int id) inline static
Definition at line 983 of file SourceData.cs.
    {
        return ExcelParser.GetString(id);
    }
References ExcelParser.GetString().
Referenced by LangGame.CreateRow(), LangGeneral.CreateRow(), LangList.CreateRow(), LangNote.CreateRow(), LangTalk.CreateRow(), LangWord.CreateRow(), SourceArea.CreateRow(), SourceBacker.CreateRow(), SourceBlock.CreateRow(), SourceCalc.CreateRow(), SourceCategory.CreateRow(), SourceCellEffect.CreateRow(), SourceChara.CreateRow(), SourceCharaText.CreateRow(), SourceCheck.CreateRow(), SourceCollectible.CreateRow(), SourceDeco.CreateRow(), SourceElement.CreateRow(), SourceFaction.CreateRow(), SourceFloor.CreateRow(), SourceFood.CreateRow(), SourceGlobalTile.CreateRow(), SourceHobby.CreateRow(), SourceHomeResource.CreateRow(), SourceJob.CreateRow(), SourceKeyItem.CreateRow(), SourceMaterial.CreateRow(), SourceObj.CreateRow(), SourcePerson.CreateRow(), SourceQuest.CreateRow(), SourceRace.CreateRow(), SourceRecipe.CreateRow(), SourceReligion.CreateRow(), SourceResearch.CreateRow(), SourceSpawnList.CreateRow(), SourceStat.CreateRow(), SourceTactics.CreateRow(), SourceThing.CreateRow(), SourceThingV.CreateRow(), SourceZone.CreateRow(), SourceZoneAffix.CreateRow(), LangGame.CreateRowByMapping(), LangGeneral.CreateRowByMapping(), LangList.CreateRowByMapping(), LangNote.CreateRowByMapping(), LangWord.CreateRowByMapping(), SourceArea.CreateRowByMapping(), SourceBacker.CreateRowByMapping(), SourceBlock.CreateRowByMapping(), SourceCalc.CreateRowByMapping(), SourceCategory.CreateRowByMapping(), SourceCellEffect.CreateRowByMapping(), SourceChara.CreateRowByMapping(), SourceCharaText.CreateRowByMapping(), SourceCheck.CreateRowByMapping(), SourceCollectible.CreateRowByMapping(), SourceDeco.CreateRowByMapping(), SourceElement.CreateRowByMapping(), SourceFaction.CreateRowByMapping(), SourceFloor.CreateRowByMapping(), SourceFood.CreateRowByMapping(), SourceGlobalTile.CreateRowByMapping(), SourceHobby.CreateRowByMapping(), SourceHomeResource.CreateRowByMapping(), SourceJob.CreateRowByMapping(), SourceKeyItem.CreateRowByMapping(), SourceMaterial.CreateRowByMapping(), SourceObj.CreateRowByMapping(), SourcePerson.CreateRowByMapping(), SourceQuest.CreateRowByMapping(), SourceRace.CreateRowByMapping(), SourceRecipe.CreateRowByMapping(), SourceReligion.CreateRowByMapping(), SourceResearch.CreateRowByMapping(), SourceSpawnList.CreateRowByMapping(), SourceStat.CreateRowByMapping(), SourceTactics.CreateRowByMapping(), SourceThing.CreateRowByMapping(), SourceThingV.CreateRowByMapping(), SourceZone.CreateRowByMapping(), and SourceZoneAffix.CreateRowByMapping().
GetStringArray()
static string[] SourceData< T, T2 >.GetStringArray (int id) inline static
Definition at line 978 of file SourceData.cs.
    {
        return ExcelParser.GetStringArray(id);
    }
References ExcelParser.GetStringArray().
Referenced by LangList.CreateRow(), SourceBlock.CreateRow(), SourceCategory.CreateRow(), SourceCellEffect.CreateRow(), SourceChara.CreateRow(), SourceCollectible.CreateRow(), SourceDeco.CreateRow(), SourceElement.CreateRow(), SourceFloor.CreateRow(), SourceFood.CreateRow(), SourceGlobalTile.CreateRow(), SourceHobby.CreateRow(), SourceHomeResource.CreateRow(), SourceJob.CreateRow(), SourceMaterial.CreateRow(), SourceObj.CreateRow(), SourceQuest.CreateRow(), SourceRace.CreateRow(), SourceRecipe.CreateRow(), SourceReligion.CreateRow(), SourceResearch.CreateRow(), SourceSpawnList.CreateRow(), SourceStat.CreateRow(), SourceTactics.CreateRow(), SourceThing.CreateRow(), SourceThingV.CreateRow(), SourceZone.CreateRow(), LangList.CreateRowByMapping(), SourceBlock.CreateRowByMapping(), SourceCategory.CreateRowByMapping(), SourceCellEffect.CreateRowByMapping(), SourceChara.CreateRowByMapping(), SourceCollectible.CreateRowByMapping(), SourceDeco.CreateRowByMapping(), SourceElement.CreateRowByMapping(), SourceFloor.CreateRowByMapping(), SourceFood.CreateRowByMapping(), SourceGlobalTile.CreateRowByMapping(), SourceHobby.CreateRowByMapping(), SourceHomeResource.CreateRowByMapping(), SourceJob.CreateRowByMapping(), SourceMaterial.CreateRowByMapping(), SourceObj.CreateRowByMapping(), SourceQuest.CreateRowByMapping(), SourceRace.CreateRowByMapping(), SourceRecipe.CreateRowByMapping(), SourceReligion.CreateRowByMapping(), SourceResearch.CreateRowByMapping(), SourceSpawnList.CreateRowByMapping(), SourceStat.CreateRowByMapping(), SourceTactics.CreateRowByMapping(), SourceThing.CreateRowByMapping(), SourceThingV.CreateRowByMapping(), and SourceZone.CreateRowByMapping().
ImportData() [1/2]
override bool SourceData< T, T2 >.ImportData (ISheet sheet, string bookname, bool overwrite = false) inline
Definition at line 137 of file SourceData.cs.
    {
        if (!overwrite)
        {
            rows = new List<T>();
        }
        isNew = true;
        nameSheet = sheet.SheetName;
        nameBook = bookname;
        SourceData.rowHeader = sheet.GetRow(0);
        SourceData.rowDefault = sheet.GetRow(2);
        IReadOnlyDictionary<string, int> rowMapping = GetRowMapping();
        Dictionary<string, int> dictionary = null;
        if (rowMapping != null)
        {
            dictionary = new Dictionary<string, int>(StringComparer.OrdinalIgnoreCase);
            foreach (ICell item in SourceData.rowHeader.Cells.Where((ICell c) => c.ToString() != "0" && !c.ToString().IsEmpty()))
            {
                dictionary[item.ToString().Trim()] = item.ColumnIndex;
            }
            if (!rowMapping.Keys.All(dictionary.ContainsKey) || rowMapping.Count > dictionary.Count)
            {
                string[] array = rowMapping.Keys.Except(dictionary.Keys).ToArray();
                if (array.Length != 0)
                {
                    Debug.LogWarning("#source ill-format file with missing columns, init with empty values\n" + ExcelParser.GetRowHeaderDiff(rowMapping, dictionary));
                    string[] array2 = array;
                    foreach (string text in array2)
                    {
                        SourceData.rowHeader.CreateCell(276, CellType.String).SetCellValue(text);
                        dictionary[text] = 276;
                    }
                }
                else
                {
                    Debug.Log("#source ill-format file with reordered columns");
                }
            }
            else
            {
                dictionary = null;
            }
        }
        int num = 0;
        for (int j = 3; j <= sheet.LastRowNum; j++)
        {
            SourceData.row = sheet.GetRow(j);
            if (string.IsNullOrEmpty(SourceData.row?.GetCell(0)?.ToString()))
            {
                break;
            }
            T val = ((dictionary != null) ? CreateRowByMapping(dictionary) : CreateRow());
            val.OnImportData(this);
            rows.Add(val);
            num++;
        }
        string text2 = sheet.SheetName + "/" + sheet.LastRowNum + "/" + num;
        Debug.Log(text2);
        ERROR.msg = text2;
        OnAfterImportData();
        initialized = false;
        return true;
    }
References SourceData< T, T2 >.CreateRow(), SourceData< T, T2 >.CreateRowByMapping(), Debug, ExcelParser.GetRowHeaderDiff(), SourceData< T, T2 >.GetRowMapping(), SourceData< T, T2 >.initialized, SourceData< T, T2 >.isNew, item, SourceData< T, T2 >.nameBook, SourceData< T, T2 >.nameSheet, SourceData< T, T2 >.OnAfterImportData(), SourceData< T, T2 >.row, SourceData< T, T2 >.rowHeader, and SourceData< T, T2 >.rows.
Referenced by SourceImporter.LoadBySheetName().
ImportData() [2/2]
virtual bool SourceData< T, T2 >.ImportData (ISheet sheet, string bookname, bool overwrite = false) inline virtual
Definition at line 892 of file SourceData.cs.
    {
        return false;
    }
ImportRows() [1/2]
override int SourceData< T, T2 >.ImportRows (IEnumerable< BaseRow > sourceRows) inline
Definition at line 215 of file SourceData.cs.
    {
        int num = 0;
        foreach (BaseRow sourceRow in sourceRows)
        {
            if (sourceRow is T val)
            {
                val.OnImportData(this);
                rows.Add(val);
                num++;
            }
        }
        OnAfterImportData();
        initialized = false;
        return num;
    }
References SourceData< T, T2 >.initialized, SourceData< T, T2 >.OnAfterImportData(), and SourceData< T, T2 >.rows.
Referenced by SourceImporter.ImportFilesCached().
ImportRows() [2/2]
virtual int SourceData< T, T2 >.ImportRows (IEnumerable< BaseRow > sourceRows) inline virtual
Definition at line 897 of file SourceData.cs.
    {
        return 0;
    }
ImportTexts() [1/2]
override void SourceData< T, T2 >.ImportTexts (string _nameSheet = null) inline
Definition at line 529 of file SourceData.cs.
    {
        string langImportMod = CorePath.CorePackage.LangImportMod;
        string text = _nameSheet.IsEmpty(nameSheet) + ".xlsx";
        if (!File.Exists(langImportMod + text))
        {
            return;
        }
        XSSFWorkbook xSSFWorkbook;
        using (FileStream @is = File.Open(langImportMod + text, FileMode.Open, FileAccess.Read, FileShare.ReadWrite))
        {
            xSSFWorkbook = new XSSFWorkbook((Stream)@is);
        }
        ISheet sheetAt = xSSFWorkbook.GetSheetAt(0);
        List<FieldInfo> fields = GetFields();
        IRow row = sheetAt.GetRow(0);
        List<FieldMap> list = new List<FieldMap>();
        foreach (FieldInfo item in fields)
        {
            if (item.isStatic)
            {
                continue;
            }
            for (int i = 0; i < row.LastCellNum; i++)
            {
                string stringCellValue = row.GetCell(i).StringCellValue;
                if (stringCellValue.IsEmpty())
                {
                    break;
                }
                if (stringCellValue == item.id)
                {
                    list.Add(new FieldMap
                    {
                        field = item,
                        column = i
                    });
                    break;
                }
            }
        }
        for (int j = 2; j <= sheetAt.LastRowNum; j++)
        {
            IRow row2 = sheetAt.GetRow(j);
            T val = GetRow(row2.GetCell(0).StringCellValue);
            if (val == null)
            {
                Debug.Log(sheetAt.SheetName + ": id to import no longer exist: " + row2.GetCell(0).StringCellValue);
                break;
            }
            foreach (FieldMap item2 in list)
            {
                FieldInfo field = item2.field;
                System.Reflection.FieldInfo field2 = val.GetType().GetField(field.id + "_L");
                if (field2 == null)
                {
                    continue;
                }
                if (typeof(string[]).IsAssignableFrom(field2.FieldType))
                {
                    ICell cell = row2.GetCell(item2.column);
                    string[] array = ((cell == null) ? new string[0] : cell.StringCellValue.Split(','));
                    string[] field3 = val.GetField<string[]>(field.id);
                    if (field3 != null)
                    {
                        field2.SetValue(val, (array.Length >= field3.Length) ? array : field3);
                    }
                }
                else
                {
                    ICell cell2 = row2.GetCell(item2.column);
                    if (cell2 != null)
                    {
                        field2.SetValue(val, cell2.StringCellValue.IsEmpty(val.GetField<string>(field.id)));
                    }
                }
            }
        }
    }
References SourceData< T, T2 >.FieldMap.column, Debug, SourceData< T, T2 >.FieldMap.field, SourceData< T, T2 >.GetFields(), SourceData< T, T2 >.GetRow(), SourceData< T, T2 >.FieldInfo.id, item, CorePath.CorePackage.LangImportMod, SourceData< T, T2 >.nameSheet, and SourceData< T, T2 >.row.
ImportTexts() [2/2]
virtual void SourceData< T, T2 >.ImportTexts (string _nameSheet = null) inline virtual
Definition at line 926 of file SourceData.cs.
    {
    }
Init() [1/2]
override void SourceData< T, T2 >.Init () inline
Definition at line 83 of file SourceData.cs.
    {
        Debug.Log("Initializing:" + base.name);
        if (initialized)
        {
            Debug.Log("#init Skipping sourceData.Init:" + base.name);
            return;
        }
        initialized = true;
        editorListString.Clear();
        RemoveDuplicateRows();
        int num = 0;
        foreach (T row in rows)
        {
            SetRow(row);
            if (row.UseAlias)
            {
                alias[row.GetAlias] = row;
            }
            row._index = num;
            num++;
        }
        OnInit();
    }
References SourceData< T, T2 >.alias, Debug, SourceData< T, T2 >.editorListString, SourceData< T, T2 >.initialized, SourceData< T, T2 >.OnInit(), SourceData< T, T2 >.RemoveDuplicateRows(), SourceData< T, T2 >.row, SourceData< T, T2 >.rows, and SourceData< T, T2 >.SetRow().
Referenced by SourceImporter.HotInit(), and SourceData< T, T2 >.Reset().
Init() [2/2]
virtual void SourceData< T, T2 >.Init () inline virtual
Definition at line 883 of file SourceData.cs.
    {
    }
InsertData()
virtual void SourceData< T, T2 >.InsertData (IRow row) inline virtual
Definition at line 879 of file SourceData.cs.
    {
    }
IsNull()
static bool SourceData< T, T2 >.IsNull (ICell cell) inline static
Definition at line 939 of file SourceData.cs.
    {
        if (cell != null && cell.CellType != CellType.Blank)
        {
            return cell.CellType == CellType.Unknown;
        }
        return true;
    }
OnAfterImportData()
virtual void SourceData< T, T2 >.OnAfterImportData () inline virtual
Definition at line 201 of file SourceData.cs.
    {
    }
Referenced by SourceData< T, T2 >.ImportData(), and SourceData< T, T2 >.ImportRows().
OnInit()
virtual void SourceData< T, T2 >.OnInit () inline virtual
Definition at line 108 of file SourceData.cs.
    {
    }
Referenced by SourceData< T, T2 >.Init().
RemoveDuplicateRows()
virtual void SourceData< T, T2 >.RemoveDuplicateRows () inline virtual
Definition at line 232 of file SourceData.cs.
    {
        HashSet<T2> hashSet = new HashSet<T2>();
        List<T> list = new List<T>(rows.Count);
        string arg = GetType().Name;
        System.Reflection.FieldInfo field = typeof(T).GetField("id");
        bool flag = typeof(LangRow).IsAssignableFrom(typeof(T));
        if (field == null)
        {
            return;
        }
        if (field.FieldType != typeof(T2))
        {
            Debug.LogError($"#source override: {arg} id field mismatch {field.FieldType} != {typeof(T2)}");
        }
        for (int num = rows.Count - 1; num >= 0; num--)
        {
            T val = rows[num];
            T2 val2 = (T2)field.GetValue(val);
            if (hashSet.Add(val2))
            {
                list.Add(val);
            }
            else if (!flag)
            {
                Debug.Log($"#source override: {arg} {val2}");
            }
        }
        if (rows.Count != list.Count)
        {
            Debug.Log($"#source override: {arg} total/{rows.Count} -> unique/{list.Count}");
            list.Reverse();
            rows = list;
        }
    }
References $, Debug, and SourceData< T, T2 >.rows.
Referenced by SourceData< T, T2 >.Init().
Reset() [1/2]
override void SourceData< T, T2 >.Reset () inline
Definition at line 116 of file SourceData.cs.
    {
        initialized = false;
        if (!Application.isPlaying)
        {
            BaseCore.resetRuntime = true;
        }
        if (map != null)
        {
            map.Clear();
        }
        if (alias != null)
        {
            alias.Clear();
        }
        if (Application.isPlaying && AllowHotInitialization)
        {
            Init();
        }
    }
References SourceData< T, T2 >.alias, SourceData< T, T2 >.AllowHotInitialization, SourceData< T, T2 >.Init(), SourceData< T, T2 >.initialized, and SourceData< T, T2 >.map.
Referenced by SourceImporter.HotInit().
Reset() [2/2]
virtual void SourceData< T, T2 >.Reset () inline virtual
Definition at line 875 of file SourceData.cs.
    {
    }
RestorePref()
virtual void SourceData< T, T2 >.RestorePref () inline virtual
Definition at line 914 of file SourceData.cs.
    {
    }
RollbackSource() [1/2]
override void SourceData< T, T2 >.RollbackSource () inline
Definition at line 273 of file SourceData.cs.
    {
        rows = _backupRows;
    }
References SourceData< T, T2 >._backupRows, and SourceData< T, T2 >.rows.
RollbackSource() [2/2]
virtual void SourceData< T, T2 >.RollbackSource () inline virtual
Definition at line 906 of file SourceData.cs.
    {
    }
SetRow()
virtual void SourceData< T, T2 >.SetRow (T row) inline virtual
Definition at line 112 of file SourceData.cs.
    {
    }
Referenced by SourceData< T, T2 >.Init().
ValidateLang() [1/2]
override void SourceData< T, T2 >.ValidateLang () inline
Definition at line 521 of file SourceData.cs.
    {
        string langImportMod = CorePath.CorePackage.LangImportMod;
        string text = nameSheet + ".xlsx";
        Log.system = Log.system + langImportMod + text + Environment.NewLine;
        Log.system += Environment.NewLine;
    }
References CorePath.CorePackage.LangImportMod, and SourceData< T, T2 >.nameSheet.
ValidateLang() [2/2]
virtual void SourceData< T, T2 >.ValidateLang () inline virtual
Definition at line 930 of file SourceData.cs.
    {
    }
ValidatePref()
virtual void SourceData< T, T2 >.ValidatePref () inline virtual
Definition at line 918 of file SourceData.cs.
    {
    }
Member Data Documentation
_backupRows
List<T> SourceData< T, T2 >._backupRows = new List<T>() private
Definition at line 72 of file SourceData.cs.
Referenced by SourceData< T, T2 >.BackupSource(), and SourceData< T, T2 >.RollbackSource().
alias
Dictionary<string, T> SourceData< T, T2 >.alias = new Dictionary<string, T>()
Definition at line 66 of file SourceData.cs.
Referenced by SourceData< T, T2 >.Init(), and SourceData< T, T2 >.Reset().
autoID
AutoID SourceData< T, T2 >.autoID
Definition at line 815 of file SourceData.cs.
currentSheet
ISheet SourceData< T, T2 >.currentSheet static
Definition at line 77 of file SourceData.cs.
Referenced by SourceData< T, T2 >.ExportTexts(), and SourceData< T, T2 >.GetCell().
dataPath
string SourceData< T, T2 >.dataPath static
Definition at line 813 of file SourceData.cs.
editorListString
List<string> SourceData< T, T2 >.editorListString = new List<string>()
Definition at line 75 of file SourceData.cs.
Referenced by SourceData< T, T2 >.BuildEditorList(), and SourceData< T, T2 >.Init().
initialized
bool SourceData< T, T2 >.initialized
Definition at line 69 of file SourceData.cs.
Referenced by SourceData< T, T2 >.ImportData(), SourceData< T, T2 >.ImportRows(), SourceData< T, T2 >.Init(), and SourceData< T, T2 >.Reset().
isNew
bool SourceData< T, T2 >.isNew = true
Definition at line 817 of file SourceData.cs.
Referenced by SourceData< T, T2 >.ImportData().
LangSuffix
string SourceData< T, T2 >.LangSuffix static
Definition at line 811 of file SourceData.cs.
Referenced by SourceData< T, T2 >.BaseRow.GetText(), and SourceData< T, T2 >.BaseRow.GetTextArray().
map
Dictionary<T2, T> SourceData< T, T2 >.map = new Dictionary<T2, T>()
Definition at line 64 of file SourceData.cs.
Referenced by SourceData< T, T2 >.BuildFlags(), and SourceData< T, T2 >.Reset().
nameBook
string SourceData< T, T2 >.nameBook
Definition at line 821 of file SourceData.cs.
Referenced by SourceData< T, T2 >.ImportData().
nameSheet
string SourceData< T, T2 >.nameSheet
Definition at line 819 of file SourceData.cs.
Referenced by SourceData< T, T2 >.ExportTexts(), SourceData< T, T2 >.ImportData(), SourceData< T, T2 >.ImportTexts(), and SourceData< T, T2 >.ValidateLang().
rows
List<T> SourceData< T, T2 >.rows = new List<T>()
Definition at line 62 of file SourceData.cs.
Referenced by SourceData< T, T2 >.BackupSource(), SourceData< T, T2 >.BuildEditorList(), SourceData< T, T2 >.ExportTexts(), SourceData< T, T2 >.ImportData(), SourceData< T, T2 >.ImportRows(), SourceData< T, T2 >.Init(), SourceData< T, T2 >.RemoveDuplicateRows(), and SourceData< T, T2 >.RollbackSource().
Property Documentation
AllowHotInitialization
virtual bool SourceData< T, T2 >.AllowHotInitialization get
Definition at line 79 of file SourceData.cs.
Referenced by SourceData< T, T2 >.Reset().
ImportFields
virtual string [] SourceData< T, T2 >.ImportFields get
Definition at line 81 of file SourceData.cs.
Referenced by SourceData< T, T2 >.GetFields().
row
IRow SourceData< T, T2 >.row static get set
Definition at line 827 of file SourceData.cs.
    {
        get
        {
            return ExcelParser.row;
        }
        set
        {
            ExcelParser.row = value;
        }
    }
Referenced by SourceData< T, T2 >.BuildEditorList(), SourceData< T, T2 >.ExportTexts(), SourceData< T, T2 >.GetCell(), SourceData< T, T2 >.ImportData(), SourceData< T, T2 >.ImportTexts(), and SourceData< T, T2 >.Init().
rowDefault
IRow SourceData< T, T2 >.rowDefault static get set
Definition at line 839 of file SourceData.cs.
    {
        get
        {
            return ExcelParser.rowDefault;
        }
        set
        {
            ExcelParser.rowDefault = value;
        }
    }
rowHeader
IRow SourceData< T, T2 >.rowHeader static get set
Definition at line 851 of file SourceData.cs.
    {
        get
        {
            return ExcelParser.rowHeader;
        }
        set
        {
            ExcelParser.rowHeader = value;
        }
    }
Referenced by SourceData< T, T2 >.ImportData().
sheetName
virtual string SourceData< T, T2 >.sheetName get
Definition at line 823 of file SourceData.cs.
sourcePath
virtual string SourceData< T, T2 >.sourcePath get
Definition at line 825 of file SourceData.cs.
The documentation for this class was generated from the following file:
Elin/Plugins.basecore/SourceData.cs