Elin Decompiled Documentation: ShopTransaction Class Reference
ShopTransaction Class Reference
Classes
class Item
Public Member Functions
void Log ()
bool HasBought (Thing t)
bool CanSellBack (Thing t, int num=-1)
void Process (Thing t, int n, bool sell)
int GetPrice (Thing t, int n, bool sell)
void OnEndTransaction ()
Public Attributes
InvOwner trader
List< ShopTransaction.Item > bought = new List<ShopTransaction.Item>()
List< ShopTransaction.Item > sold = new List<ShopTransaction.Item>()
Static Public Attributes
static ShopTransaction current
Static Public Attributes inherited from EClass
static Core core
Additional Inherited Members
Static Public Member Functions inherited from EClass
static int rnd (int a)
static int curve (int a, int start, int step, int rate=75)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Detailed Description
Definition at line 5 of file ShopTransaction.cs.
Member Function Documentation
CanSellBack()
bool ShopTransaction.CanSellBack (Thing t, int num = -1) inline
Definition at line 54 of file ShopTransaction.cs.
    {
        if (num == -1)
        {
            num = t.Num;
        }
        foreach (ShopTransaction.Item item in this.bought)
        {
            if (item.thing == t && item.num >= num)
            {
                return true;
            }
        }
        return false;
    }
References Card.Num.
Referenced by InvOwner.Transaction.IsValid(), InvOwner.ListInteractions(), and InvOwner.OnWriteNote().
GetPrice()
int ShopTransaction.GetPrice (Thing t, int n, bool sell) inline
Definition at line 132 of file ShopTransaction.cs.
    {
        int price = t.GetPrice(this.trader.currency, false, this.trader.priceType, null);
        int price2 = t.GetPrice(this.trader.currency, true, this.trader.priceType, null);
        int num = n;
        int num2 = 0;
        int num3 = sell ? price : price2;
        foreach (ShopTransaction.Item item in (sell ? this.bought : this.sold))
        {
            if (item.thing.id == t.id && item.price == num3)
            {
                int num4 = (item.num >= num) ? num : item.num;
                num -= num4;
                num2 += num4 * num3;
            }
            if (num == 0)
            {
                break;
            }
        }
        return num2 + num * (sell ? price2 : price);
    }
References Card.GetPrice(), and Card.id.
Referenced by InvOwner.GetPrice().
HasBought()
bool ShopTransaction.HasBought (Thing t) inline
Definition at line 39 of file ShopTransaction.cs.
    {
        using (List<ShopTransaction.Item>.Enumerator enumerator = this.bought.GetEnumerator())
        {
            while (enumerator.MoveNext())
            {
                if (enumerator.Current.thing == t)
                {
                    return true;
                }
            }
        }
        return false;
    }
References bought.
Referenced by InvOwner.Transaction.IsValid().
Log()
void ShopTransaction.Log () inline
Definition at line 7 of file ShopTransaction.cs.
    {
        foreach (ShopTransaction.Item item in this.bought)
        {
            Debug.Log(string.Concat(new string[]
            {
                "Bought:",
                item.thing.Name,
                "/",
                item.num.ToString(),
                " x ",
                item.price.ToString(),
                " = ",
                (item.num * item.price).ToString()
            }));
        }
        foreach (ShopTransaction.Item item2 in this.sold)
        {
            Debug.Log(string.Concat(new string[]
            {
                "Sold:",
                item2.thing.Name,
                "/",
                item2.num.ToString(),
                " x ",
                item2.price.ToString(),
                " = ",
                (item2.num * item2.price).ToString()
            }));
        }
    }
OnEndTransaction()
void ShopTransaction.OnEndTransaction () inline
Definition at line 155 of file ShopTransaction.cs.
    {
        Thing thing = this.trader.owner.things.Find("chest_merchant", -1, -1);
        if (thing != null)
        {
            thing.c_lockLv = 1;
        }
        foreach (ShopTransaction.Item item in this.bought)
        {
            Debug.Log(item.thing);
            item.thing.SetInt(101, 0);
            item.thing.isStolen = false;
        }
        if (this.trader.currency != CurrencyType.Money)
        {
            ShopTransaction.current = null;
            return;
        }
        int num = 0;
        foreach (ShopTransaction.Item item2 in this.bought)
        {
            for (int i = 0; i < item2.num; i++)
            {
                num += (int)Mathf.Sqrt((float)Mathf.Abs(item2.price * 5));
            }
            if (item2.thing.trait is TraitDeed)
            {
                EClass.player.flags.landDeedBought += item2.num;
            }
        }
        if (num >= 10)
        {
            EClass.pc.ModExp(291, num);
        }
        Debug.Log("negotiation total:" + num.ToString());
        num = 0;
        foreach (ShopTransaction.Item item3 in this.sold)
        {
            if (item3.thing.isStolen)
            {
                item3.thing.isStolen = false;
                for (int j = 0; j < item3.num; j++)
                {
                    num += (int)Mathf.Sqrt((float)item3.price) / 2;
                }
            }
        }
        Debug.Log("stolen total:" + num.ToString());
        if (num > 0)
        {
            Guild.Thief.AddContribution(num);
        }
        ShopTransaction.current = null;
    }
References Faction.AddContribution(), ThingContainer.Find(), Card.ModExp(), EClass.pc, BaseCard.SetInt(), Guild.Thief, and Card.things.
Referenced by LayerInventory.CreateBuy().
Process()
void ShopTransaction.Process (Thing t, int n, bool sell) inline
Definition at line 70 of file ShopTransaction.cs.
    {
        int price = t.GetPrice(this.trader.currency, false, this.trader.priceType, null);
        int price2 = t.GetPrice(this.trader.currency, true, this.trader.priceType, null);
        int num = n;
        Debug.Log(string.Concat(new string[]
        {
            sell ? "Selling:" : "Buying:",
            t.Name,
            "/",
            n.ToString(),
            " x ",
            (sell ? price2 : price).ToString(),
            " = ",
            (n * (sell ? price2 : price)).ToString()
        }));
        int num2 = sell ? price : price2;
        List<ShopTransaction.Item> list = sell ? this.bought : this.sold;
        foreach (ShopTransaction.Item item in list)
        {
            if (item.thing.id == t.id && item.price == num2)
            {
                int num3 = (item.num >= num) ? num : item.num;
                num -= num3;
                item.num -= num3;
            }
            if (num == 0)
            {
                break;
            }
        }
        list.ForeachReverse(delegate(ShopTransaction.Item i)
        {
            if (i.num == 0)
            {
                list.Remove(i);
            }
        });
        if (num > 0)
        {
            if (sell)
            {
                this.sold.Add(new ShopTransaction.Item
                {
                    thing = t,
                    num = num,
                    price = price2
                });
            }
            else
            {
                this.bought.Add(new ShopTransaction.Item
                {
                    thing = t,
                    num = num,
                    price = price
                });
            }
        }
        this.Log();
    }
References bought, InvOwner.currency, Card.GetPrice(), Card.id, Card.Name, sold, and trader.
Referenced by InvOwner.Transaction.Process().
Member Data Documentation
bought
List<ShopTransaction.Item> ShopTransaction.bought = new List<ShopTransaction.Item>()
Definition at line 214 of file ShopTransaction.cs.
Referenced by HasBought(), and Process().
current
ShopTransaction ShopTransaction.current static
Definition at line 210 of file ShopTransaction.cs.
Referenced by LayerInventory.CreateBuy(), InvOwner.GetPrice(), InvOwner.Transaction.IsValid(), InvOwner.ListInteractions(), InvOwner.OnWriteNote(), and InvOwner.Transaction.Process().
sold
List<ShopTransaction.Item> ShopTransaction.sold = new List<ShopTransaction.Item>()
Definition at line 216 of file ShopTransaction.cs.
Referenced by Process().
trader
InvOwner ShopTransaction.trader
Definition at line 212 of file ShopTransaction.cs.
Referenced by Process().
The documentation for this class was generated from the following file:
Elin/ShopTransaction.cs