Elin Decompiled Documentation: Net Class Reference
Net Class Reference
Classes
class ChatLog
class DownloadCahce
class DownloadMeta
class VoteLog
Public Member Functions
void ShowVote (string logs)
void ShowChat (string logs)
Static Public Member Functions
static async UniTask< bool > UploadFile (string id, string password, string name, string title, string path, string idLang, string cat="Home", string tag="")
static async UniTask< FileInfo > DownloadFile (DownloadMeta item, string path, string idLang)
static async UniTask< List< DownloadMeta > > GetFileList (string idLang)
static async UniTask< bool > SendVote (int id, string idLang)
static async UniTask< List< VoteLog > > GetVote (string idLang)
static async UniTask< bool > SendChat (string name, string msg, ChatCategory cat, string idLang)
static async UniTask< List< ChatLog > > GetChat (ChatCategory cat, string idLang)
Public Attributes
List< ChatLog > chatList
Static Public Attributes
static string urlScript = "http://elin.cloudfree.jp/script/"
static string urlChat = urlScript + "chat/"
static string urlVote = urlScript + "vote/"
static string urlUpload = urlScript + "uploader/"
static bool isUploading
Properties
static bool ShowNetError [get]
Detailed Description
Definition at line 10 of file Net.cs.
Member Function Documentation
DownloadFile()
static async UniTask< FileInfo > Net.DownloadFile (DownloadMeta item, string path, string idLang) inline static
Definition at line 164 of file Net.cs.
    {
        string fn = item.id + ".z";
        DownloadCahce caches = IO.LoadFile<DownloadCahce>(CorePath.ZoneSaveUser + "cache.txt") ?? new DownloadCahce();
        if (caches.items.TryGetValue(item.id) == item.date.Replace("\"", "") && File.Exists(path + fn))
        {
            Debug.Log("Returning Cache:" + path + fn);
            return new FileInfo(path + fn);
        }
        using UnityWebRequest www = UnityWebRequest.Get(urlUpload + "files/" + idLang + "/" + fn);
        www.downloadHandler = new DownloadHandlerFile(path + fn);
        try
        {
            await www.SendWebRequest();
        }
        catch (Exception ex)
        {
            EClass.ui.Say(ex.Message);
        }
        FileInfo fileInfo = new FileInfo(path + fn);
        if (!fileInfo.Exists || www.result != UnityWebRequest.Result.Success)
        {
            if (ShowNetError)
            {
                EClass.ui.Say(www.error);
            }
            return null;
        }
        caches.items[item.id] = item.date;
        IO.SaveFile(CorePath.ZoneSaveUser + "cache.txt", caches);
        return fileInfo;
    }
References Debug, item, Net.DownloadCahce.items, ShowNetError, EClass.ui, urlUpload, and CorePath.ZoneSaveUser.
Referenced by TraitMoongate.UseMoongate().
GetChat()
static async UniTask< List< ChatLog > > Net.GetChat (ChatCategory cat, string idLang) inline static
Definition at line 362 of file Net.cs.
    {
        List<ChatLog> list = new List<ChatLog>();
        try
        {
            if (EClass.debug.enable)
            {
                idLang = "DEBUG";
            }
            string uri = string.Format(urlChat + "logs/all_{0}.json", idLang);
            using UnityWebRequest www = UnityWebRequest.Get(uri);
            await www.SendWebRequest();
            if (www.result == UnityWebRequest.Result.ConnectionError || www.result == UnityWebRequest.Result.ProtocolError)
            {
                return null;
            }
            Debug.Log("Download Chat Logs: Success");
            foreach (JToken item in (JArray)JsonConvert.DeserializeObject(www.downloadHandler.text))
            {
                list.Add(item.ToObject<ChatLog>());
            }
            foreach (ChatLog item2 in list)
            {
                item2.msg = item2.msg.Replace("\n", "").Replace("\r", "").Replace("&quot;", "\"")
                    .ToTitleCase();
            }
            list.Reverse();
            return list;
        }
        catch
        {
            return list;
        }
    }
References EClass.debug, Debug, CoreDebug.enable, item, Net.ChatLog.msg, and urlChat.
Referenced by LayerNewspaper.RefreshChat().
GetFileList()
static async UniTask< List< DownloadMeta > > Net.GetFileList (string idLang) inline static
Definition at line 197 of file Net.cs.
    {
        List<DownloadMeta> list = new List<DownloadMeta>();
        using UnityWebRequest www = UnityWebRequest.Get(urlUpload + "files/" + idLang + "/index.txt");
        try
        {
            await www.SendWebRequest();
        }
        catch (Exception ex)
        {
            EClass.ui.Say(ex.Message);
        }
        if (www.result != UnityWebRequest.Result.Success)
        {
            if (ShowNetError)
            {
                EClass.ui.Say(www.error);
            }
            return null;
        }
        StringReader stringReader = new StringReader(www.downloadHandler.text);
        for (string text = stringReader.ReadLine(); text != null; text = stringReader.ReadLine())
        {
            if (!string.IsNullOrEmpty(text))
            {
                string[] array = text.Split(',');
                list.Add(new DownloadMeta
                {
                    path = array[0],
                    id = Path.GetFileNameWithoutExtension(array[0]),
                    name = array[2],
                    title = array[3],
                    cat = array[5],
                    date = array[6].Replace("\"", ""),
                    version = ((array.Length >= 9) ? array[8].ToInt() : 0),
                    tag = ((array.Length >= 10) ? array[9] : "")
                });
            }
        }
        return list;
    }
References ShowNetError, title, EClass.ui, and urlUpload.
Referenced by TraitMoongate.UseMoongate().
GetVote()
static async UniTask< List< VoteLog > > Net.GetVote (string idLang) inline static
Definition at line 267 of file Net.cs.
    {
        List<VoteLog> list = new List<VoteLog>();
        try
        {
            string uri = string.Format(urlVote + "logs/data_{0}.txt", idLang);
            using UnityWebRequest www = UnityWebRequest.Get(uri);
            await www.SendWebRequest();
            if (www.result == UnityWebRequest.Result.ConnectionError || www.result == UnityWebRequest.Result.ProtocolError)
            {
                if (ShowNetError)
                {
                    EClass.ui.Say(www.error);
                }
            }
            else
            {
                StringReader stringReader = new StringReader(www.downloadHandler.text);
                int num = 0;
                for (string text = stringReader.ReadLine(); text != null; text = stringReader.ReadLine())
                {
                    string[] array = text.Split(',');
                    if (num == 0)
                    {
                        list.Add(new VoteLog
{
                            name = array[0].Replace("\"", ""),
                            time = array[2].ToInt(),
                            index = num
                        });
                    }
                    else
                    {
                        list.Add(new VoteLog
{
                            name = array[0].Replace("\"", ""),
                            count = array[1].ToInt(),
                            index = num
                        });
                    }
                    num++;
                }
            }
            return list;
        }
        catch
        {
            return list;
        }
    }
References ShowNetError, EClass.ui, and urlVote.
Referenced by LayerNewspaper.RefreshVote().
SendChat()
static async UniTask< bool > Net.SendChat (string name, string msg, ChatCategory cat, string idLang) inline static
Definition at line 318 of file Net.cs.
    {
        if (EClass.core.version.demo)
        {
            return false;
        }
        try
        {
            if (EClass.debug.enable)
            {
                idLang = "DEBUG";
            }
            Debug.Log("Start Sending Text:");
            WWWForm wWWForm = new WWWForm();
            wWWForm.AddField("submit", "Send");
            wWWForm.AddField("name", name);
            wWWForm.AddField("msg", msg);
            wWWForm.AddField("cat", cat.ToString());
            wWWForm.AddField("idLang", idLang);
            try
            {
                using UnityWebRequest www = UnityWebRequest.Post(urlChat + "chat.php", wWWForm);
                await www.SendWebRequest();
                if (www.result == UnityWebRequest.Result.ConnectionError || www.result == UnityWebRequest.Result.ProtocolError)
                {
                    if (ShowNetError)
                    {
                        EClass.ui.Say(www.error);
                    }
                    return false;
                }
                Debug.Log(www.downloadHandler.text);
                return true;
            }
            catch
            {
            }
        }
        catch
        {
        }
        return false;
    }
References EClass.core, EClass.debug, Debug, Version.demo, CoreDebug.enable, ShowNetError, EClass.ui, urlChat, and BaseCore.version.
Referenced by ActEffect.Wish().
SendVote()
static async UniTask< bool > Net.SendVote (int id, string idLang) inline static
Definition at line 239 of file Net.cs.
    {
        try
        {
            Debug.Log("Start Sending Vote:");
            WWWForm wWWForm = new WWWForm();
            wWWForm.AddField("vote", id.ToString() ?? "");
            wWWForm.AddField("idLang", idLang);
            wWWForm.AddField("submit", "Send");
            using UnityWebRequest www = UnityWebRequest.Post(urlVote + "vote.php", wWWForm);
            await www.SendWebRequest();
            if (www.result == UnityWebRequest.Result.ConnectionError || www.result == UnityWebRequest.Result.ProtocolError)
            {
                if (ShowNetError)
                {
                    EClass.ui.Say(www.error);
                }
                return false;
            }
            Debug.Log(www.downloadHandler.text);
            return true;
        }
        catch
        {
            return true;
        }
    }
References Debug, ShowNetError, EClass.ui, and urlVote.
Referenced by LayerNewspaper.RefreshVote().
ShowChat()
void Net.ShowChat (string logs) inline
Definition at line 96 of file Net.cs.
    {
        foreach (JToken item in (JArray)JsonConvert.DeserializeObject(logs))
        {
            ChatLog chatLog = item.ToObject<ChatLog>();
            Debug.Log(chatLog.name + "/" + chatLog.msg);
        }
    }
References Debug, item, Net.ChatLog.msg, and Net.ChatLog.name.
ShowVote()
void Net.ShowVote (string logs) inline
Definition at line 87 of file Net.cs.
    {
        StringReader stringReader = new StringReader(logs);
        for (string text = stringReader.ReadLine(); text != null; text = stringReader.ReadLine())
        {
            Debug.Log(text);
        }
    }
References Debug.
UploadFile()
static async UniTask< bool > Net.UploadFile (string id, string password, string name, string title, string path, string idLang, string cat = "Home", string tag = "") inline static
Definition at line 105 of file Net.cs.
    {
        if (isUploading)
        {
            EClass.ui.Say("sys_uploadUploading");
            return false;
        }
        EClass.ui.Say("sys_uploadStart");
        byte[] array;
        using (FileStream fileStream = File.OpenRead(path))
        {
            array = new byte[fileStream.Length];
            fileStream.Read(array, 0, (int)fileStream.Length);
        }
        WWWForm wWWForm = new WWWForm();
        wWWForm.AddField("mode", 1);
        wWWForm.AddField("id", id);
        wWWForm.AddField("name", name);
        wWWForm.AddField("title", title);
        wWWForm.AddField("cat", cat);
        wWWForm.AddField("tag", tag);
        wWWForm.AddField("idLang", idLang);
        wWWForm.AddField("password", password);
        wWWForm.AddField("submit", "Send");
        wWWForm.AddField("version", EClass.core.version.GetInt().ToString() ?? "");
        wWWForm.AddBinaryData("file", array, "file.z");
        isUploading = true;
        Debug.Log(id);
        Debug.Log(name);
        Debug.Log(title);
        Debug.Log(idLang);
        Debug.Log(password);
        Debug.Log(tag);
        Debug.Log(array.Length);
        using (UnityWebRequest www = UnityWebRequest.Post(urlUpload + "uploader.php", wWWForm))
        {
            try
            {
                await www.SendWebRequest();
                Debug.Log(www.result.ToString());
                Debug.Log(www.downloadHandler.ToString());
                Debug.Log(www.downloadHandler.text);
                Debug.Log(www.downloadHandler.text.ToString());
            }
            catch (Exception ex)
            {
                EClass.ui.Say(ex.Message);
            }
            isUploading = false;
            if (www.result != UnityWebRequest.Result.Success)
            {
                EClass.ui.Say((www.responseCode == 401) ? "sys_uploadConflict" : "sys_uploadFail");
                return false;
            }
        }
        EClass.ui.Say("sys_uploadSuccess");
        return true;
    }
References EClass.core, Debug, Version.GetInt(), isUploading, title, EClass.ui, urlUpload, and BaseCore.version.
Referenced by LayerUploader.Upload().
Member Data Documentation
chatList
List<ChatLog> Net.chatList
Definition at line 63 of file Net.cs.
isUploading
bool Net.isUploading static
Definition at line 73 of file Net.cs.
Referenced by UploadFile().
urlChat
string Net.urlChat = urlScript + "chat/" static
Definition at line 67 of file Net.cs.
Referenced by GetChat(), and SendChat().
urlScript
string Net.urlScript = "http://elin.cloudfree.jp/script/" static
Definition at line 65 of file Net.cs.
urlUpload
string Net.urlUpload = urlScript + "uploader/" static
Definition at line 71 of file Net.cs.
Referenced by DownloadFile(), GetFileList(), and UploadFile().
urlVote
string Net.urlVote = urlScript + "vote/" static
Definition at line 69 of file Net.cs.
Referenced by GetVote(), and SendVote().
Property Documentation
ShowNetError
bool Net.ShowNetError static get
Definition at line 75 of file Net.cs.
    {
        get
        {
            if (!EClass.core.config.test.showNetError)
            {
                return EClass.debug.enable;
            }
            return true;
        }
    }
Referenced by DownloadFile(), GetFileList(), GetVote(), SendChat(), and SendVote().
The documentation for this class was generated from the following file:
Elin/Net.cs