Elin Decompiled Documentation: UIListEx< T > Class Template Reference
UIListEx< T > Class Template Reference
Classes
class RefObjectEx
Public Member Functions
override void Refresh (bool highlightLast=false)
virtual void OnInstantiate (RefObjectEx o, T t)
Public Member Functions inherited from UIList
void AddCollection (ICollection collection)
override void Add (object item)
int GetIndexOf (object item)
ButtonPair GetPair (object item)
T GetPair< T > (object item)
void AddDynamic (object item)
void RemoveDynamic (object item)
override void Clear ()
bool OnClickFolder (UIButton b, Action< UIList > onFold, bool refresh=true)
void RebuildLayoutInParent ()
virtual void Refresh (bool highlightLast=false)
void NextPage ()
void PrevPage ()
void SetPage (int i)
void OnMove (object o, object select=null)
void Select (int index=0, bool invoke=false)
void Select (object obj, bool invoke=false)
void Select< T > (Func< T, bool > func, bool invoke=false)
void Sort ()
void ChangeSort (SortMode m)
override void NextSort ()
override void List ()
override void List (SortMode sort)
void List (bool refreshHighlight=false)
void List (SortMode m, bool refreshHighlight=false)
override void Redraw ()
void BuildLayout ()
T GetMold< T > ()
void OnDestroy ()
void ClearChildren ()
Public Member Functions inherited from BaseList
virtual void NextSort ()
virtual void List ()
virtual void List (UIList.SortMode sort)
virtual void Redraw ()
virtual void Clear ()
virtual void Add (object o)
void RefreshNoItem ()
void RefreshBGGrid ()
Public Attributes
T mold
Public Attributes inherited from UIList
string langNoItem
int rows
UISelectableGroup menu
UIListTopbar bar
bool fillEmpty
bool buildLayout
UIItem paginationTop
UIItem paginationBottom
UISelectableGroup group
LayoutGroup _layoutItems
Transform moldItem
bool selectFirst
bool invokeSelected
bool enableGroup = true
bool onlyDirectChildrenButtonForGroup
bool usePage
bool usePool
bool disableInstaClick = true
bool ignoreNullObj = true
ItemHeight itemHeight
int heightFix
int page
int maxPage
int itemsPerPage
List< object > items = new List<object>()
List< ButtonPair > buttons = new List<ButtonPair>()
string idMold
Action SETab
UIList moldList
UIList parent
Dictionary< UIButton, UIList > children = new Dictionary<UIButton, UIList>()
Public Attributes inherited from BaseList
UIList.BGType bgType
Vector2 bgFix
Vector2 bgUvFix = Vector2.one
UIList.ICallback callbacks
UIList.SortMode[] sorts
Action onBeforeRedraw
Action onAfterRedraw
bool useDefaultNoItem = true
bool numbering
SkinType skinType
RawImage bgGrid
UIList.SortMode sortMode
bool isBuilt
Additional Inherited Members
Public Types inherited from UIList
enum BGType {
none , stripe , line , dot ,
dot_long , grid , thin
}
enum SortMode {
ByNone , ByNumber , ByValue , ByCategory ,
ByEquip , ByJob , ByRace , ByLevel ,
ByWeight , ByPrice , ByElementParent , ByName ,
ByID , ByWeightSingle , ByWorkk , ByFeat
}
enum ItemHeight { DontChange , Default }
Static Public Attributes inherited from UIList
const int HeightDefault = 34
static string[] strNumber
Protected Member Functions inherited from UIList
virtual void OnRefresh ()
Protected Attributes inherited from BaseList
Transform transNoItem
Properties inherited from UIList
LayoutGroup layoutItems [get]
GridLayoutGroup gridLayout [get]
override int ItemCount [get]
override int RowCount [get]
UIList Root [get]
Properties inherited from BaseList
virtual int ItemCount [get]
virtual int RowCount [get]
SkinRootStatic Skin [get]
Detailed Description
Type Constraints
T : Component
Definition at line 4 of file UIListEx.cs.
Member Function Documentation
OnInstantiate()
virtual void UIListEx< T >.OnInstantiate (RefObjectEx o, T t) inline virtual
Definition at line 44 of file UIListEx.cs.
    {
    }
Referenced by UIListEx< T >.Refresh().
Refresh()
override void UIListEx< T >.Refresh (bool highlightLast = false) inline virtual
Reimplemented from UIList.
Definition at line 17 of file UIListEx.cs.
    {
        if (callbacks == null)
        {
            callbacks = new Callback<RefObjectEx, T>
            {
                onClick = delegate(RefObjectEx a, T b)
                {
                    if (a.onClick != null)
                    {
                        a.onClick();
                    }
                },
                onInstantiate = delegate(RefObjectEx a, T b)
                {
                    OnInstantiate(a, b);
                    if (a.onInstantiate != null)
                    {
                        a.onInstantiate(b);
                    }
                },
                mold = mold
            };
        }
        base.Refresh();
    }
References BaseList.callbacks, UIListEx< T >.mold, UIListEx< T >.RefObjectEx.onClick, UIListEx< T >.RefObjectEx.onInstantiate, and UIListEx< T >.OnInstantiate().
Referenced by Dialog.OnAfterInit().
Member Data Documentation
mold
T UIListEx< T >.mold
Definition at line 15 of file UIListEx.cs.
Referenced by UIListEx< T >.Refresh().
The documentation for this class was generated from the following file:
Elin/Plugins.UI/UIListEx.cs