Elin Decompiled Documentation: UISearchPeople Class Reference
UISearchPeople Class Reference
Public Member Functions
void Init (ListOwner _list)
bool FuncFilter (object _c)
void Search (string s)
void ClearSearch ()
void Redraw ()
Public Attributes
InputField inputSearch
UIButton buttonClearSearch
UIDropdown dropdown
ListOwner list
bool disable
float intervalSearch
Private Member Functions
void LateUpdate ()
Private Attributes
int uidFilterZone = -1
float timerSearch
string lastSearch = ""
Additional Inherited Members
Static Public Member Functions inherited from EMono
static int rnd (int a)
Static Public Attributes inherited from EMono
static Core core
Properties inherited from EMono
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SoundManager Sound [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static CoreDebug debug [get]
Detailed Description
Definition at line 4 of file UISearchPeople.cs.
Member Function Documentation
ClearSearch()
void UISearchPeople.ClearSearch () inline
Definition at line 106 of file UISearchPeople.cs.
    {
        inputSearch.text = "";
        timerSearch = 0f;
        lastSearch = "";
        Redraw();
    }
References lastSearch, Redraw(), and timerSearch.
FuncFilter()
bool UISearchPeople.FuncFilter (object _c) inline
Definition at line 76 of file UISearchPeople.cs.
    {
        Chara chara = _c as Chara;
        if (uidFilterZone != -1 && (chara.homeZone == null || chara.homeZone.uid != uidFilterZone))
        {
            return false;
        }
        if (!lastSearch.IsEmpty() && !chara.NameBraced.ToLower().Contains(lastSearch))
        {
            return false;
        }
        return true;
    }
References Chara.homeZone, lastSearch, Chara.NameBraced, Spatial.uid, and uidFilterZone.
Referenced by Init().
Init()
void UISearchPeople.Init (ListOwner _list) inline
Definition at line 24 of file UISearchPeople.cs.
    {
        if (disable)
        {
            base.gameObject.SetActive(value: false);
            return;
        }
        this.list = _list;
        inputSearch.onValueChanged.AddListener(Search);
        inputSearch.onSubmit.AddListener(Search);
        List<int> list = new List<int> { -1 };
        foreach (FactionBranch child in EMono.pc.faction.GetChildren())
        {
            list.Add(child.owner.uid);
        }
        dropdown.SetList(0, list, delegate(int a, int i)
        {
            object obj;
            if (a != -1)
            {
                obj = EMono.game.spatials.Find(a)?.Name;
                if (obj == null)
                {
                    return "???";
                }
            }
            else
            {
                obj = "all".lang();
            }
            return (string)obj;
        }, delegate(int i, int a)
        {
            SE.ClickOk();
            uidFilterZone = a;
            this.list.List();
        });
        this.list.list.funcFilter = FuncFilter;
    }
References disable, dropdown, Chara.faction, SpatialManager.Find(), FuncFilter(), EMono.game, Faction.GetChildren(), inputSearch, ListOwner< T1, T2 >.List(), list, FactionBranch.owner, EMono.pc, Search, Game.spatials, Spatial.uid, and uidFilterZone.
Referenced by LayerPeople.InitList().
LateUpdate()
void UISearchPeople.LateUpdate () inline private
Definition at line 64 of file UISearchPeople.cs.
    {
        if (!disable && timerSearch > 0f)
        {
            timerSearch -= Core.delta;
            if (timerSearch <= 0f)
            {
                Search(inputSearch.text);
            }
        }
    }
References Core.delta, disable, inputSearch, Search, and timerSearch.
Redraw()
void UISearchPeople.Redraw () inline
Definition at line 114 of file UISearchPeople.cs.
    {
        list.List();
    }
References ListOwner< T1, T2 >.List(), and list.
Referenced by ClearSearch(), and Search().
Search()
void UISearchPeople.Search (string s) inline
Definition at line 90 of file UISearchPeople.cs.
    {
        s = s.ToLower();
        if (s.IsEmpty())
        {
            s = "";
        }
        buttonClearSearch.SetActive(inputSearch.text != "");
        if (!(s == lastSearch))
        {
            timerSearch = intervalSearch;
            lastSearch = s;
            Redraw();
        }
    }
References buttonClearSearch, inputSearch, intervalSearch, lastSearch, Redraw(), and timerSearch.
Member Data Documentation
buttonClearSearch
UIButton UISearchPeople.buttonClearSearch
Definition at line 8 of file UISearchPeople.cs.
Referenced by Search().
disable
bool UISearchPeople.disable
Definition at line 14 of file UISearchPeople.cs.
Referenced by Init(), and LateUpdate().
dropdown
UIDropdown UISearchPeople.dropdown
Definition at line 10 of file UISearchPeople.cs.
Referenced by Init().
inputSearch
InputField UISearchPeople.inputSearch
Definition at line 6 of file UISearchPeople.cs.
Referenced by Init(), LateUpdate(), and Search().
intervalSearch
float UISearchPeople.intervalSearch
Definition at line 16 of file UISearchPeople.cs.
Referenced by Search().
lastSearch
string UISearchPeople.lastSearch = "" private
Definition at line 22 of file UISearchPeople.cs.
Referenced by ClearSearch(), FuncFilter(), and Search().
list
ListOwner UISearchPeople.list
Definition at line 12 of file UISearchPeople.cs.
Referenced by Init(), and Redraw().
timerSearch
float UISearchPeople.timerSearch private
Definition at line 20 of file UISearchPeople.cs.
Referenced by ClearSearch(), LateUpdate(), and Search().
uidFilterZone
int UISearchPeople.uidFilterZone = -1 private
Definition at line 18 of file UISearchPeople.cs.
Referenced by FuncFilter(), and Init().
The documentation for this class was generated from the following file:
Elin/UISearchPeople.cs