Elin Decompiled Documentation: LayerWorldSetting Class Reference
LayerWorldSetting Class Reference
Public Member Functions
override void OnInit ()
void SetTemplate (int idx)
void RefreshTemplate ()
void Refresh ()
void StartGame ()
override void OnKill ()
void Apply ()
Public Member Functions inherited from ELayer
override void OnBeforeAddLayer ()
void InitInspector ()
sealed override void Init ()
override void OnAfterAddLayer ()
void TryShowHelp ()
void AddLayerToUI (string id)
void TryShowHint (string _langHint=null)
void TalkHomeMemeber (string id)
void TalkMaid (string id)
override void OnRightClick ()
Public Member Functions inherited from Layer
virtual string GetTextHeader (Window window)
virtual bool HeaderIsListOf (int id)
virtual void Init ()
virtual void OnInit ()
virtual void OnAfterInit ()
virtual void ApplySkin ()
void ShowScreenLock (string id)
void UpdateInput ()
virtual void OnUpdateInput ()
virtual void OnRightClick ()
virtual bool OnBack ()
virtual void OnChangeLayer ()
virtual void OnCreate ()
void _AddLayer (string id)
Layer AddLayer (string id)
T AddLayer< T > ()
T AddLayer< T > (string id)
T AddLayerDontCloseOthers< T > ()
Layer AddLayerDontCloseOthers (Layer l)
T GetOrAddLayer< T > ()
virtual void OnBeforeAddLayer ()
virtual void OnAfterAddLayer ()
Layer AddLayer (Layer l)
void ToggleLayer (string id)
T ToggleLayer< T > (string id=null)
void WaitAndClose ()
void OnClickClose ()
virtual void Close ()
void CloseLayers ()
void RemoveLayers (bool removeImportant=false)
bool RemoveLayer< T > ()
void RemoveLayer (Layer l)
virtual void OnKill ()
Layer SetOnKill (Action action)
void DisableClose ()
void Delay (float duration=0.05f)
Layer SetDelay (float d)
Layer GetLayer (string id)
T GetLayer< T > (bool fromTop=false)
Layer GetTopLayer ()
void SwitchContent (int idWindow, int i)
virtual void OnSwitchContent (Window window)
Layer SetTitles (string langList, string idHeaderRow=null)
bool IsBlockWidgetClick ()
bool IsHideHud ()
bool IsAllowGeneralInput ()
bool IsUseBlur ()
bool IsPointerOnLayer ()
void ApplySkin ()
Public Attributes
UISelectableGroup groupTemplate
List< UIButton > buttonTemplates
GamePrincipal pp
UIButton toggleEvaluate
UIButton toggleDeathPenaltyProtection
UIButton toggleManualSave
UIButton togglePermadeath
UIButton toggleInfiniteMarketFund
UIButton toggleOPMilk
UIButton toggleUsermapBenefit
UIButton toggleDropRate
UIButton toggleTax
UIText textScore
UIText textTitle
UIText textValidScore
UIText textDetail
UISlider sliderDropRate
Image imageScoreBar
UIButton moldToggle
UIButton moldSlider
UIButton buttonEmbark
UIButton buttonWorkaround
UIItem moldHeader
Transform transCustom
Transform transMold
List< Sprite > sprites
Public Attributes inherited from Layer
Option option
UnityEvent onKill
Anime animeIn
Anime animeOut
bool closeOthers
bool defaultActionMode = true
Button screenLock
Layer parent
string idLayer
List< Layer > layers = new List<Layer>()
Vector2 lastParentPos
List< Window > windows = new List<Window>()
string langHint
Properties
int IdxCustom [get]
bool IsEmbark [get]
Properties inherited from ELayer
static Core core [get]
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static FactionBranch Branch [get]
static Faction Home [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static CoreConfig config [get]
static GameSetting setting [get]
static ColorProfile Colors [get]
static SourceManager sources [get]
static World world [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
bool IsFloat [get]
virtual string IdHelp [get]
Properties inherited from Layer
Layer TopLayer [get]
string uid [get]
virtual RectTransform rectLayers [get]
virtual bool blockWidgetClick [get]
Private Attributes
bool started
Additional Inherited Members
Static Public Member Functions inherited from ELayer
static int rnd (int a)
Static Public Member Functions inherited from Layer
static T Create< T > ()
static T Create< T > (string path)
static Layer Create (string path)
Static Public Attributes inherited from Layer
static int skipInput
static bool closeOnRightClick
static bool rightClicked
static bool cancelKeyDown
static bool ignoreSounds
static Transform blurStopInstance
static string[] searchPath = new string[3] { "Layer", "Layer/Dialog", "Layer/LayerHome" }
Protected Member Functions inherited from ELayer
sealed override void _Close ()
sealed override void Kill ()
Protected Member Functions inherited from Layer
virtual void Awake ()
virtual void _Close ()
virtual void Kill ()
Protected Attributes inherited from Layer
RectTransform _rect
bool isDestroyed
Detailed Description
Definition at line 6 of file LayerWorldSetting.cs.
Member Function Documentation
Apply()
void LayerWorldSetting.Apply () inline
Definition at line 217 of file LayerWorldSetting.cs.
    {
        if (!IsEmbark)
        {
            pp.modified = ELayer.game.principal.modified;
            foreach (GamePrincipal.Item item in pp.ListItems())
            {
                if (item.IsModified())
                {
                    pp.modified.Add(item.id);
                }
            }
        }
        ELayer.game.principal = pp;
        if (ELayer.player.resetPrincipal)
        {
            ELayer.player.resetPrincipal = false;
        }
        ELayer.pc.SetFeat(1220, pp.permadeath ? 1 : 0);
    }
References ELayer.game, IsEmbark, item, GamePrincipal.ListItems(), GamePrincipal.modified, ELayer.pc, GamePrincipal.permadeath, ELayer.player, pp, Game.principal, Player.resetPrincipal, and Chara.SetFeat().
Referenced by OnKill().
OnInit()
override void LayerWorldSetting.OnInit () inline virtual
Reimplemented from Layer.
Definition at line 76 of file LayerWorldSetting.cs.
    {
        buttonEmbark.SetActive(IsEmbark);
        buttonWorkaround.SetActive(enable: true);
        if (IsEmbark)
        {
            ELayer.game.principal.modified.Clear();
        }
        pp = IO.DeepCopy(ELayer.game.principal);
        transMold.SetActive(enable: false);
        for (int j = 0; j < buttonTemplates.Count; j++)
        {
            int i = j;
            UIButton uIButton = buttonTemplates[i];
            uIButton.mainText.SetText(Lang.GetList("pp_templates")[i]);
            if (i != IdxCustom)
            {
                uIButton.refObj = ELayer.setting.start.principals[i];
            }
            uIButton.SetOnClick(delegate
            {
                SetTemplate(i);
            });
        }
        buttonWorkaround.SetToggle(ELayer.player.showWorkaround, delegate(bool a)
        {
            ELayer.player.showWorkaround = a;
            Refresh();
        });
        Refresh();
    }
References buttonEmbark, buttonTemplates, buttonWorkaround, ELayer.game, Lang.GetList(), IdxCustom, IsEmbark, UIButton.mainText, GamePrincipal.modified, ELayer.player, pp, Game.principal, GameSetting.StartSetting.principals, Refresh(), SetTemplate(), UIText.SetText(), ELayer.setting, UIButton.SetToggle(), Player.showWorkaround, GameSetting.start, and transMold.
OnKill()
override void LayerWorldSetting.OnKill () inline virtual
Reimplemented from Layer.
Definition at line 212 of file LayerWorldSetting.cs.
    {
        Apply();
    }
References Apply().
Refresh()
void LayerWorldSetting.Refresh () inline
Definition at line 135 of file LayerWorldSetting.cs.
    {
        RefreshTemplate();
        transCustom.DestroyChildren();
        List<GamePrincipal.Item> items = pp.ListItems();
        AddCategory(GamePrincipal.Type.Oath);
        if (ELayer.player.showWorkaround)
        {
            AddCategory(GamePrincipal.Type.Workaround);
            AddCategory(GamePrincipal.Type.Legacy);
        }
        transCustom.RebuildLayout();
        void AddCategory(GamePrincipal.Type type)
        {
            Util.Instantiate(moldHeader, transCustom).text1.SetText(("pp_" + type).lang());
            foreach (GamePrincipal.Item item in items.Where((GamePrincipal.Item a) => a.type == type))
            {
                UIButton b = null;
                GamePrincipal.ItemSlider itemSlider = item as GamePrincipal.ItemSlider;
                if (itemSlider == null)
                {
                    if (item != null)
                    {
                        _ = item;
                        b = Util.Instantiate(moldToggle, transCustom);
                    }
                }
                else
                {
                    b = Util.Instantiate(moldSlider, transCustom);
                    b.GetComponentInChildren<UISlider>().SetSlider(itemSlider.GetInt(), delegate(float a)
                    {
                        itemSlider.SetInt((int)a);
                        return itemSlider.funcText((int)a);
                    }, 0, itemSlider.max, notify: false);
                }
                bool flag = item.id == "permadeath" && !IsEmbark && !item.WasSealed();
                b.mainText.SetText(("pp_" + item.id).lang());
                b.icon.SetActive(item.grade >= 0 && (item.IsSealed() || item.WasSealed()));
                b.icon.SetAlpha(item.IsSealed() ? 1f : 0.3f);
                b.icon.sprite = ((item.grade < 0) ? null : sprites[item.grade]);
                b.icon.SetNativeSize();
                b.GetOrCreate<CanvasGroup>().alpha = (flag ? 0.5f : 1f);
                string text = "pp_" + item.id + "_hint";
                b.SetTooltipLang(text);
                b.tooltip.enable = Lang.Has(text);
                b.interactable = !flag;
                b.SetToggle(item.Get(), delegate(bool a)
                {
                    item.Set(a);
                    if (!pp.IsCustom)
                    {
                        pp.id = -1;
                        RefreshTemplate();
                    }
                    b.icon.SetActive(item.grade >= 0 && (item.IsSealed() || item.WasSealed()));
                    b.icon.SetAlpha(item.IsSealed() ? 1f : 0.3f);
                });
            }
        }
    }
References GamePrincipal.ItemSlider.funcText, GamePrincipal.ItemSlider.GetInt(), Lang.Has(), UIButton.icon, GamePrincipal.IsCustom, IsEmbark, item, GamePrincipal.ListItems(), UIButton.mainText, GamePrincipal.ItemSlider.max, moldHeader, moldSlider, moldToggle, ELayer.player, pp, RefreshTemplate(), GamePrincipal.ItemSlider.SetInt(), UIText.SetText(), UIButton.SetToggle(), UIButton.SetTooltipLang(), Player.showWorkaround, sprites, transCustom, and Util.
Referenced by OnInit(), and SetTemplate().
RefreshTemplate()
void LayerWorldSetting.RefreshTemplate () inline
Definition at line 122 of file LayerWorldSetting.cs.
    {
        if (pp.IsCustom)
        {
            groupTemplate.Select(buttonTemplates.LastItem());
        }
        else
        {
            groupTemplate.Select(pp.id);
        }
        textDetail.SetText(("vow_" + pp.id).lang());
    }
References buttonTemplates, groupTemplate, GamePrincipal.id, GamePrincipal.IsCustom, pp, UISelectableGroup.Select(), UIText.SetText(), and textDetail.
Referenced by Refresh().
SetTemplate()
void LayerWorldSetting.SetTemplate (int idx) inline
Definition at line 108 of file LayerWorldSetting.cs.
    {
        pp.id = idx;
        if (idx == IdxCustom)
        {
            pp.id = -1;
        }
        else
        {
            pp = IO.DeepCopy(ELayer.setting.start.principals[idx]);
        }
        Refresh();
    }
References IdxCustom, pp, GameSetting.StartSetting.principals, Refresh(), ELayer.setting, and GameSetting.start.
Referenced by OnInit().
StartGame()
void LayerWorldSetting.StartGame () inline
Definition at line 197 of file LayerWorldSetting.cs.
    {
        if (ELayer.player.resetPrincipal)
        {
            Close();
            return;
        }
        started = true;
        Close();
        if (!LayerDrama.Instance)
        {
            LayerDrama.ActivateMain("mono", "1-1");
        }
    }
References LayerDrama.ActivateMain(), Layer.Close(), LayerDrama.Instance, ELayer.player, Player.resetPrincipal, and started.
Member Data Documentation
buttonEmbark
UIButton LayerWorldSetting.buttonEmbark
Definition at line 48 of file LayerWorldSetting.cs.
Referenced by OnInit().
buttonTemplates
List<UIButton> LayerWorldSetting.buttonTemplates
Definition at line 10 of file LayerWorldSetting.cs.
Referenced by OnInit(), and RefreshTemplate().
buttonWorkaround
UIButton LayerWorldSetting.buttonWorkaround
Definition at line 50 of file LayerWorldSetting.cs.
Referenced by OnInit().
groupTemplate
UISelectableGroup LayerWorldSetting.groupTemplate
Definition at line 8 of file LayerWorldSetting.cs.
Referenced by RefreshTemplate().
imageScoreBar
Image LayerWorldSetting.imageScoreBar
Definition at line 42 of file LayerWorldSetting.cs.
moldHeader
UIItem LayerWorldSetting.moldHeader
Definition at line 52 of file LayerWorldSetting.cs.
Referenced by Refresh().
moldSlider
UIButton LayerWorldSetting.moldSlider
Definition at line 46 of file LayerWorldSetting.cs.
Referenced by Refresh().
moldToggle
UIButton LayerWorldSetting.moldToggle
Definition at line 44 of file LayerWorldSetting.cs.
Referenced by Refresh().
pp
GamePrincipal LayerWorldSetting.pp
Definition at line 12 of file LayerWorldSetting.cs.
Referenced by Apply(), OnInit(), Refresh(), RefreshTemplate(), and SetTemplate().
sliderDropRate
UISlider LayerWorldSetting.sliderDropRate
Definition at line 40 of file LayerWorldSetting.cs.
sprites
List<Sprite> LayerWorldSetting.sprites
Definition at line 58 of file LayerWorldSetting.cs.
Referenced by Refresh().
started
bool LayerWorldSetting.started private
Definition at line 60 of file LayerWorldSetting.cs.
Referenced by StartGame().
textDetail
UIText LayerWorldSetting.textDetail
Definition at line 38 of file LayerWorldSetting.cs.
Referenced by RefreshTemplate().
textScore
UIText LayerWorldSetting.textScore
Definition at line 32 of file LayerWorldSetting.cs.
textTitle
UIText LayerWorldSetting.textTitle
Definition at line 34 of file LayerWorldSetting.cs.
textValidScore
UIText LayerWorldSetting.textValidScore
Definition at line 36 of file LayerWorldSetting.cs.
toggleDeathPenaltyProtection
UIButton LayerWorldSetting.toggleDeathPenaltyProtection
Definition at line 16 of file LayerWorldSetting.cs.
toggleDropRate
UIButton LayerWorldSetting.toggleDropRate
Definition at line 28 of file LayerWorldSetting.cs.
toggleEvaluate
UIButton LayerWorldSetting.toggleEvaluate
Definition at line 14 of file LayerWorldSetting.cs.
toggleInfiniteMarketFund
UIButton LayerWorldSetting.toggleInfiniteMarketFund
Definition at line 22 of file LayerWorldSetting.cs.
toggleManualSave
UIButton LayerWorldSetting.toggleManualSave
Definition at line 18 of file LayerWorldSetting.cs.
toggleOPMilk
UIButton LayerWorldSetting.toggleOPMilk
Definition at line 24 of file LayerWorldSetting.cs.
togglePermadeath
UIButton LayerWorldSetting.togglePermadeath
Definition at line 20 of file LayerWorldSetting.cs.
toggleTax
UIButton LayerWorldSetting.toggleTax
Definition at line 30 of file LayerWorldSetting.cs.
toggleUsermapBenefit
UIButton LayerWorldSetting.toggleUsermapBenefit
Definition at line 26 of file LayerWorldSetting.cs.
transCustom
Transform LayerWorldSetting.transCustom
Definition at line 54 of file LayerWorldSetting.cs.
Referenced by Refresh().
transMold
Transform LayerWorldSetting.transMold
Definition at line 56 of file LayerWorldSetting.cs.
Referenced by OnInit().
Property Documentation
IdxCustom
int LayerWorldSetting.IdxCustom get
Definition at line 62 of file LayerWorldSetting.cs.
Referenced by OnInit(), and SetTemplate().
IsEmbark
bool LayerWorldSetting.IsEmbark get
Definition at line 64 of file LayerWorldSetting.cs.
    {
        get
        {
            if (ELayer.core.IsGameStarted)
            {
                return ELayer.player.resetPrincipal;
            }
            return true;
        }
    }
Referenced by Apply(), OnInit(), and Refresh().
The documentation for this class was generated from the following file:
Elin/LayerWorldSetting.cs