Elin Decompiled Documentation: SourceGlobalTile Class Reference
SourceGlobalTile Class Reference
Classes
class Row
Public Member Functions
override Row CreateRow ()
override Row CreateRowByMapping (IReadOnlyDictionary< string, int > mapping)
override void SetRow (Row r)
override IReadOnlyDictionary< string, int > GetRowMapping ()
override IReadOnlyDictionary< string, string > GetTypeMapping ()
override void OnInit ()
Public Member Functions inherited from SourceDataInt< SourceGlobalTile.Row >
override T GetRow (string id)
Public Attributes
Dictionary< int, Row > tileAlias = new Dictionary<int, Row>()
Static Public Attributes
static readonly IReadOnlyDictionary< string, int > RowMapping
static readonly IReadOnlyDictionary< string, string > TypeMapping
Detailed Description
Definition at line 4 of file SourceGlobalTile.cs.
Member Function Documentation
CreateRow()
override Row SourceGlobalTile.CreateRow () inline
Definition at line 80 of file SourceGlobalTile.cs.
    {
        return new Row
        {
            id = SourceData.GetInt(0),
            alias = SourceData.GetString(1),
            name_JP = SourceData.GetString(2),
            name = SourceData.GetString(3),
            tiles = SourceData.GetIntArray(4),
            floor = SourceData.GetInt(5),
            zoneProfile = SourceData.GetString(6),
            tag = SourceData.GetStringArray(7),
            dangerLv = SourceData.GetInt(8),
            trait = SourceData.GetStringArray(9),
            idBiome = SourceData.GetString(10),
            attribs = SourceData.GetIntArray(11),
            detail_JP = SourceData.GetString(12),
            detail = SourceData.GetString(13)
        };
    }
References SourceData< T, T2 >.GetInt(), SourceData< T, T2 >.GetIntArray(), SourceData< T, T2 >.GetString(), and SourceData< T, T2 >.GetStringArray().
CreateRowByMapping()
override Row SourceGlobalTile.CreateRowByMapping (IReadOnlyDictionary< string, int > mapping) inline
Definition at line 101 of file SourceGlobalTile.cs.
    {
        return new Row
        {
            id = SourceData.GetInt(mapping["id"]),
            alias = SourceData.GetString(mapping["alias"]),
            name_JP = SourceData.GetString(mapping["name_JP"]),
            name = SourceData.GetString(mapping["name"]),
            tiles = SourceData.GetIntArray(mapping["tiles"]),
            floor = SourceData.GetInt(mapping["floor"]),
            zoneProfile = SourceData.GetString(mapping["zoneProfile"]),
            tag = SourceData.GetStringArray(mapping["tag"]),
            dangerLv = SourceData.GetInt(mapping["dangerLv"]),
            trait = SourceData.GetStringArray(mapping["trait"]),
            idBiome = SourceData.GetString(mapping["idBiome"]),
            attribs = SourceData.GetIntArray(mapping["attribs"]),
            detail_JP = SourceData.GetString(mapping["detail_JP"]),
            detail = SourceData.GetString(mapping["detail"])
        };
    }
References SourceData< T, T2 >.GetInt(), SourceData< T, T2 >.GetIntArray(), SourceData< T, T2 >.GetString(), and SourceData< T, T2 >.GetStringArray().
GetRowMapping()
override IReadOnlyDictionary< string, int > SourceGlobalTile.GetRowMapping () inline
Definition at line 127 of file SourceGlobalTile.cs.
    {
        return RowMapping;
    }
References RowMapping.
GetTypeMapping()
override IReadOnlyDictionary< string, string > SourceGlobalTile.GetTypeMapping () inline
Definition at line 132 of file SourceGlobalTile.cs.
    {
        return TypeMapping;
    }
References TypeMapping.
OnInit()
override void SourceGlobalTile.OnInit () inline
Definition at line 137 of file SourceGlobalTile.cs.
    {
        foreach (Row row in rows)
        {
            int[] tiles = row.tiles;
            foreach (int key in tiles)
            {
                tileAlias[key] = row;
            }
        }
    }
References tileAlias, and SourceGlobalTile.Row.tiles.
SetRow()
override void SourceGlobalTile.SetRow (Row r) inline
Definition at line 122 of file SourceGlobalTile.cs.
    {
        map[r.id] = r;
    }
References SourceGlobalTile.Row.id.
Member Data Documentation
RowMapping
readonly IReadOnlyDictionary<string, int> SourceGlobalTile.RowMapping static
Initial value:
= new Dictionary<string, int>
    {
        ["id"] = 0,
        ["alias"] = 1,
        ["name_JP"] = 2,
        ["name"] = 3,
        ["tiles"] = 4,
        ["floor"] = 5,
        ["zoneProfile"] = 6,
        ["tag"] = 7,
        ["dangerLv"] = 8,
        ["trait"] = 9,
        ["idBiome"] = 10,
        ["attribs"] = 11,
        ["detail_JP"] = 12,
        ["detail"] = 13
    }
Definition at line 42 of file SourceGlobalTile.cs.
Referenced by GetRowMapping().
tileAlias
Dictionary<int, Row> SourceGlobalTile.tileAlias = new Dictionary<int, Row>()
Definition at line 78 of file SourceGlobalTile.cs.
Referenced by EloMap.GetSources(), EloMap.GetTileInfo(), MapGenRegion.OnGenerateTerrain(), and OnInit().
TypeMapping
readonly IReadOnlyDictionary<string, string> SourceGlobalTile.TypeMapping static
Initial value:
= new Dictionary<string, string>
    {
        ["id"] = "int",
        ["alias"] = "string",
        ["name_JP"] = "string",
        ["name"] = "string",
        ["tiles"] = "int[]",
        ["floor"] = "int",
        ["zoneProfile"] = "string",
        ["tag"] = "string[]",
        ["dangerLv"] = "int",
        ["trait"] = "string[]",
        ["idBiome"] = "string",
        ["attribs"] = "int[]",
        ["detail_JP"] = "string",
        ["detail"] = "string"
    }
Definition at line 60 of file SourceGlobalTile.cs.
Referenced by GetTypeMapping().
The documentation for this class was generated from the following file:
Elin/SourceGlobalTile.cs