Elin Decompiled Documentation: Player Class Reference
Player Class Reference
Classes
class Flags
class Pref
class ReturnInfo
class Stats
Public Member Functions
void OnCreateGame ()
void OnStartNewGame ()
void OnLoad ()
void OnBeforeSave ()
void SetPriorityAction (string id, Thing t)
bool IsPriorityAction (string id, Thing t)
void OnAdvanceRealHour ()
void RefreshDomain ()
ElementContainer GetDomains ()
Layer SelectDomain (Action onKill=null)
void RefreshEmptyAlly ()
void GenerateBackgroundText ()
string GetBackgroundText ()
void EditBackgroundText ()
void CreateEquip ()
void DreamSpell ()
void SimulateFaction ()
void ExitBorder (ActPlan p=null)
bool CanExitBorder (Point p)
void OnExitBorder (Point p)
void EnterLocalZone (bool encounter=false, Chara mob=null)
void EnterLocalZone (Point p, ZoneTransition trans=null, bool encounter=false, Chara mob=null)
void MoveZone (Zone z)
void AddInventory (Card c)
void EndTurn (bool consume=true)
void ModFame (int a)
void ModKeyItem (string alias, int num=1, bool msg=true)
void ModKeyItem (int id, int num=1, bool msg=true)
int CountKeyItem (string alias)
int CountKeyItem (int id)
void EquipTool (Thing a, bool setHotItem=true)
void RefreshCurrentHotItem ()
void ResetCurrentHotItem ()
void SetCurrentHotItem (HotItem item)
void TryEquipBait ()
bool HasValidRangedTarget ()
bool TargetRanged ()
void OnAdvanceHour ()
void OnAdvanceDay ()
bool TryAbortAutoCombat ()
void ClearMapHighlights ()
void MarkMapHighlights ()
bool CanAcceptInput ()
bool CanSee (Chara c)
void AddExpKnowledge (int a)
void AddExpInfluence (int a)
void ModKarma (int a)
Thing DropReward (Thing t, bool silent=false)
bool TooHeavyToMove ()
Public Attributes
Player.ReturnInfo returnInfo
int uidChara
int uidSpawnZone
int tutorialStep
int karma
int fame
int expKnowledge
int expInfluence
int dateTravel
int distanceTravel
int uidLastTravelZone
int uidLastZone
int uidLastShippedZone
int totalFeat
int taxBills
int unpaidBill
int bankMoney
int holyWell
int safeTravel
int hotbarPage
int little_dead
int little_saved
int extraTax
int lastFelmeraReward
int uidLastTown
int seedShrine
int seedChest
int debt
float angle
bool hasNewQuest
bool dailyGacha
bool useSubWidgetTheme
bool wellWished
bool prayed
bool questTracker
bool showShippingResult
bool isEditor
bool openContainerCenter
string title
string memo = ""
Player.Pref pref = new Player.Pref()
Player.Stats stats = new Player.Stats()
NumLogManager nums = new NumLogManager()
KnowledgeManager knowledges = new KnowledgeManager()
PopupManager popups = new PopupManager()
WidgetManager.SaveData mainWidgets
WidgetManager.SaveData subWidgets
Window.SaveData dataPick = new Window.SaveData()
LayerAbility.Config layerAbilityConfig = new LayerAbility.Config()
Dictionary< string, int > dialogFlags = new Dictionary<string, int>()
Dictionary< string, string > hangIcons = new Dictionary<string, string>()
Dictionary< string, KnownSong > knownSongs = new Dictionary<string, KnownSong>()
Dictionary< string, string > lastRecipes = new Dictionary<string, string>()
Dictionary< string, List< string > > priorityActions = new Dictionary<string, List<string>>()
HashSet< string > trackedCategories = new HashSet<string>()
HashSet< string > trackedCards = new HashSet<string>()
HashSet< int > trackedElements = new HashSet<int>()
HashSet< int > knownBGMs = new HashSet<int>()
HashSet< int > favAbility = new HashSet<int>()
HashSet< int > sketches = new HashSet<int>()
HashSet< int > doneBackers = new HashSet<int>()
HashSet< int > knownCraft = new HashSet<int>()
List< int > domains = new List<int>()
Zone zone
HotbarManager hotbars = new HotbarManager()
Chara _agent
Hoard hoard = new Hoard()
Player.Flags flags = new Player.Flags()
RecipeManager recipes = new RecipeManager()
HotItem currentHotItem = new HotItemNoItem()
Point lastZonePos
Thing eqBait
Dictionary< string, Window.SaveData > dataWindow
CinemaConfig cinemaConfig = new CinemaConfig()
CodexManager codex = new CodexManager()
Dictionary< int, int > keyItems = new Dictionary<int, int>()
List< int > uidPickOnLoad = new List<int>()
List< ShippingResult > shippingResults = new List<ShippingResult>()
Dictionary< string, HashSet< string > > noRestocks = new Dictionary<string, HashSet<string>>()
Window.SaveData windowAllyInv
Window.SaveData windowDataCopy
string windowDataName
ZoneTransition lastTransition
List< Point > lastMarkedHighlights = new List<Point>()
HotItem lastHotItem
HotItem hotItemToRestore
bool forceTalk
bool altHeldPos
bool instaComplete = true
bool regionMoveWarned
bool waitingInput
bool willEndTurn
bool wasDirtyWeight
bool deathDialog
bool preventDeathPenalty
bool deathZoneMove
bool haltMove
bool invlunerable
bool willAutoSave
bool simulatingZone
bool isAutoFarming
bool enemySpotted
string deathMsg
int countNewline
int lightRadius
int lastTurn
int lastEmptyAlly
float lightPower
float baseActTime
float pickupDelay = 2f
Chara chara
Chara focusedchara
NoticeManager notices = new NoticeManager()
QueueManager queues = new QueueManager()
Act lastAct
Vector2 nextMove
Vector3 position
Action onStartZone
PlayingSong playingSong
List< Chara > listSummon = new List<Chara>()
int tempFame
int autoCombatStartHP
Zone nextZone
Thing renderThing
HotItemNoItem hotItemNoItem = new HotItemNoItem()
Chara target
Static Public Attributes
static int seedHallucination
static int realHour
Static Public Attributes inherited from EClass
static Core core
Static Package Functions
static Thing< CreateEquip > g__SetSpellbook (Thing t, int charge)
static void< AddExpKnowledge > g__LvUp ()
static void< AddExpInfluence > g__LvUp ()
Properties
WidgetManager.SaveData widgets [get, set]
Zone spawnZone [get, set]
bool EnableDreamStory [get]
Zone LastTravelZone [get]
Zone LastZone [get]
Chara Agent [get]
int ContainerSearchDistance [get]
int MaxAlly [get]
int MaxExpKnowledge [get]
int MaxExpInfluence [get]
bool IsMageGuildMember [get]
bool IsFighterGuildMember [get]
bool IsThiefGuildMember [get]
bool IsMerchantGuildMember [get]
bool IsCriminal [get]
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Additional Inherited Members
Static Public Member Functions inherited from EClass
static int rnd (int a)
static int curve (int a, int start, int step, int rate=75)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Detailed Description
Definition at line 11 of file Player.cs.
Member Function Documentation
AddExpInfluence()
void Player.AddExpInfluence (int a) inline
Definition at line 1242 of file Player.cs.
    {
        this.expInfluence += a;
        if (this.expInfluence >= this.MaxExpInfluence)
        {
            for (int i = 0; i < this.expInfluence / this.MaxExpInfluence; i++)
            {
                Player.<AddExpInfluence>g__LvUp|209_0();
            }
            this.expInfluence %= this.MaxExpInfluence;
        }
    }
References AddExpInfluence(), expInfluence, g__LvUp(), and MaxExpInfluence.
Referenced by AddExpInfluence().
AddExpKnowledge()
void Player.AddExpKnowledge (int a) inline
Definition at line 1229 of file Player.cs.
    {
        this.expKnowledge += a;
        if (this.expKnowledge >= this.MaxExpKnowledge)
        {
            for (int i = 0; i < this.expKnowledge / this.MaxExpKnowledge; i++)
            {
                Player.<AddExpKnowledge>g__LvUp|208_0();
            }
            this.expKnowledge %= this.MaxExpKnowledge;
        }
    }
References AddExpKnowledge(), expKnowledge, g__LvUp(), and MaxExpKnowledge.
Referenced by AddExpKnowledge().
AddInventory()
void Player.AddInventory (Card c) inline
Definition at line 849 of file Player.cs.
    {
        EClass.pc.AddCard(c);
    }
References Card.AddCard(), and EClass.pc.
Referenced by GridItemCard.AutoAdd().
CanAcceptInput()
bool Player.CanAcceptInput () inline
Definition at line 1194 of file Player.cs.
    {
        return EClass.pc.HasNoGoal && !EClass.pc.WillConsumeTurn();
    }
References EClass.pc, and Chara.WillConsumeTurn().
Referenced by AM_Adv._OnUpdateInput(), HotAction.OnClick(), and WidgetCurrentTool.Select().
CanExitBorder()
bool Player.CanExitBorder (Point p) inline
Definition at line 674 of file Player.cs.
    {
        return (EClass._zone != EClass.game.StartZone || EClass.pc.homeBranch != null) && !EClass._zone.BlockBorderExit && (EClass.pc.held == null || !EClass.pc.held.trait.CanOnlyCarry);
    }
References EClass._zone, Trait.CanOnlyCarry, EClass.game, Chara.held, Chara.homeBranch, EClass.pc, Game.StartZone, and Card.trait.
Referenced by ActPlan._Update(), AM_Adv.AxisMove(), and AM_Adv.PressedActionMove().
CanSee()
bool Player.CanSee (Chara c) inline
Definition at line 1199 of file Player.cs.
    {
        if (EClass.pc.hasTelepathy && c.race.visibleWithTelepathy)
        {
            return true;
        }
        if (!c.IsPC && (EClass.pc.fov == null || EClass.pc.isBlind))
        {
            return false;
        }
        if (c.IsPCParty || c.isDead)
        {
            return true;
        }
        if (c.IsMultisize)
        {
            bool canSee = false;
            int dist = EClass.pc.Dist(c);
            c.ForeachPoint(delegate(Point p, bool main)
            {
                if (!canSee && (p.cell.light > 0 || dist < 2) && p.cell.pcSync)
                {
                    canSee = true;
                }
            });
            return canSee;
        }
        return (c.pos.cell.light > 0 || EClass.pc.Dist(c) < 2) && c.pos.cell.pcSync;
    }
References Point.cell, Card.Dist(), Card.ForeachPoint(), Card.fov, Chara.hasTelepathy, Chara.isBlind, Chara.isDead, Chara.IsMultisize, Chara.IsPC, Chara.IsPCParty, Cell.light, EClass.pc, Cell.pcSync, Card.pos, and Chara.race.
Referenced by BaseTileMap.DrawTile(), and PointTarget.ShouldIgnore().
ClearMapHighlights()
void Player.ClearMapHighlights () inline
Definition at line 1179 of file Player.cs.
    {
        foreach (Point point in this.lastMarkedHighlights)
        {
            point.cell.highlight = 0;
        }
        this.lastMarkedHighlights.Clear();
    }
References lastMarkedHighlights.
Referenced by MarkMapHighlights(), and Map.OnDeactivate().
CountKeyItem() [1/2]
int Player.CountKeyItem (int id) inline
Definition at line 934 of file Player.cs.
    {
        if (!this.keyItems.ContainsKey(id))
        {
            return 0;
        }
        return this.keyItems[id];
    }
References keyItems.
CountKeyItem() [2/2]
int Player.CountKeyItem (string alias) inline
Definition at line 929 of file Player.cs.
    {
        return this.CountKeyItem(EClass.sources.keyItems.alias[alias].id);
    }
References CountKeyItem(), SourceManager.keyItems, and EClass.sources.
Referenced by TraitGodStatue._OnUse(), CountKeyItem(), Region.CreateRandomSite(), EnterLocalZone(), ModFame(), ContentKeyItem.OnSwitchContent(), WindowChara.RefreshProfile(), and ElementContainerCard.ValueBonus().
CreateEquip()
void Player.CreateEquip () inline
Definition at line 476 of file Player.cs.
    {
        Chara pc = EClass.pc;
        pc.body.AddBodyPart(45, null);
        if (EClass.debug.enable)
        {
            EClass.pc.EQ_ID("lantern_old", -1, Rarity.Random);
        }
        pc.body.AddBodyPart(44, null);
        pc.EQ_ID("toolbelt", -1, Rarity.Random).c_IDTState = 0;
        pc.EQ_ID("shirt", -1, Rarity.Random).c_IDTState = 0;
        pc.AddCard(ThingGen.CreateCurrency(1 + EClass.rnd(5), "money"));
        string id = EClass.pc.job.id;
        if (!(id == "paladin"))
        {
            if (!(id == "inquisitor"))
            {
                if (!(id == "witch"))
                {
                    if (id == "swordsage")
                    {
                        pc.AddCard(Player.<CreateEquip>g__SetSpellbook|178_0(ThingGen.CreateSpellbook(50300, 1), 4));
                        pc.AddCard(Player.<CreateEquip>g__SetSpellbook|178_0(ThingGen.CreateSpellbook(50301, 1), 4));
                        pc.AddCard(Player.<CreateEquip>g__SetSpellbook|178_0(ThingGen.CreateSpellbook(50802, 1), 2));
                        pc.AddCard(ThingGen.Create("tool_talisman", -1, -1));
                    }
                }
                else
                {
                    pc.AddCard(Player.<CreateEquip>g__SetSpellbook|178_0(ThingGen.CreateSpellbook(8790, 1), 4));
                }
            }
            else
            {
                pc.AddCard(Player.<CreateEquip>g__SetSpellbook|178_0(ThingGen.CreateSpellbook(8706, 1), 4));
            }
        }
        else
        {
            pc.AddCard(Player.<CreateEquip>g__SetSpellbook|178_0(ThingGen.CreateSpellbook(8400, 1), 2));
        }
        id = EClass.pc.job.id;
        if (!(id == "wizard") && !(id == "warmage") && !(id == "priest") && !(id == "witch"))
        {
            pc.AddCard(ThingGen.Create("bandage", -1, -1).SetNum(6 + EClass.rnd(3)));
            return;
        }
        int num = 0;
        foreach (int id2 in EClass.player.domains)
        {
            Element element = Element.Create(id2, 0);
            string text = "";
            foreach (string text2 in element.source.tag)
            {
                if (text != "")
                {
                    break;
                }
                if (text2 == "hand" || text2 == "arrow" || text2 == "bolt")
                {
                    text = text2 + "_";
                }
            }
            if (text != "")
            {
                pc.AddCard(Player.<CreateEquip>g__SetSpellbook|178_0(ThingGen.CreateSpellbook(text + element.source.alias.Replace("ele", ""), 1), 4));
                num++;
                if (num >= 2)
                {
                    break;
                }
            }
        }
        if (EClass.pc.job.id == "priest")
        {
            pc.AddCard(Player.<CreateEquip>g__SetSpellbook|178_0(ThingGen.CreateSpellbook(8400, 1), 2));
            return;
        }
        pc.AddCard(Player.<CreateEquip>g__SetSpellbook|178_0(ThingGen.CreateSpellbook(8200, 1), 2));
    }
References CharaBody.AddBodyPart(), Card.AddCard(), Chara.body, Card.c_IDTState, Element.Create(), ThingGen.Create(), ThingGen.CreateCurrency(), CreateEquip(), ThingGen.CreateSpellbook(), EClass.debug, domains, CoreDebug.enable, Chara.EQ_ID(), g__SetSpellbook(), Chara.job, EClass.pc, EClass.player, EClass.rnd(), Card.SetNum(), Element.source, and text.
Referenced by CreateEquip(), and OnStartNewGame().
DreamSpell()
void Player.DreamSpell () inline
Definition at line 557 of file Player.cs.
    {
        int num = EClass.pc.Evalue(1653);
        if (num == 0 && EClass.pc.Evalue(1402) == 0 && EClass.rnd(4) != 0)
        {
            return;
        }
        List<SourceElement.Row> list = new List<SourceElement.Row>();
        foreach (int id in EClass.player.domains)
        {
            Element element = Element.Create(id, 0);
            string a2 = "";
            foreach (string text in element.source.tag)
            {
                if (a2 != "")
                {
                    break;
                }
                bool flag = false;
                if (text == "hand" || text == "arrow" || text == "bolt")
                {
                    flag = true;
                }
                if (num >= 3 && (text == "ball" || text == "weapon" || text == "funnel" || text == "miasma"))
                {
                    flag = true;
                }
                if (flag)
                {
                    list.Add(EClass.sources.elements.alias[text + "_" + element.source.alias.Replace("ele", "")]);
                }
            }
        }
        if (list.Count == 0)
        {
            return;
        }
        SourceElement.Row row = list.RandomItemWeighted((SourceElement.Row a) => (float)a.chance);
        Element element2 = EClass.pc.elements.GetElement(row.id);
        int mtp = (num == 0) ? 100 : (75 + num * 25);
        if (num > 0 || element2 == null || element2.vPotential == 0)
        {
            Msg.Say("dream_spell", EClass.sources.elements.alias[row.aliasRef].GetText("altname", false).Split(',', StringSplitOptions.None)[0].ToLower(), null, null, null);
            EClass.pc.GainAbility(row.id, mtp);
        }
    }
References SourceElement.Row.aliasRef, Element.Create(), domains, Card.elements, SourceManager.elements, Card.Evalue(), Chara.GainAbility(), ElementContainer.GetElement(), SourceElement.Row.id, EClass.pc, EClass.player, EClass.rnd(), Msg.Say(), Element.source, EClass.sources, text, and Element.vPotential.
Referenced by ConSleep.OnRemoved().
DropReward()
Thing Player.DropReward (Thing t, bool silent = false) inline
Definition at line 1287 of file Player.cs.
    {
        t.things.DestroyAll(null);
        EClass._zone.AddCard(t, EClass.pc.pos);
        if (!silent)
        {
            Msg.Say("dropReward");
        }
        return t;
    }
References EClass._zone, Zone.AddCard(), ThingContainer.DestroyAll(), EClass.pc, Card.pos, Msg.Say(), and Card.things.
Referenced by Recipe.DropIngredients(), Quest.DropReward(), DramaOutcome.fiama_gold(), DramaOutcome.fiama_starter_gift(), AI_Fuck.Finish(), DramaOutcome.give_sketch_reward(), QuestDebt.GiveBill(), QuestDebt.GiveReward(), QuestFiamaLock.OnStart(), TraitGachaBall.OnUse(), TraitGacha.PlayGacha(), DramaOutcome.QuestCraft_Drop1(), DramaOutcome.QuestDefense_1(), DramaOutcome.QuestExploration_Drop1(), DramaOutcome.QuestSharedContainer_Drop1(), DramaOutcome.QuestVernis_DropRecipe(), Chara.ShowDialog(), and TraitCoreZone.TrySetAct().
EditBackgroundText()
void Player.EditBackgroundText () inline
Definition at line 471 of file Player.cs.
    {
        Util.Run(GameIO.pathCurrentSave + "background.txt");
    }
References GameIO.pathCurrentSave.
Referenced by WindowChara.RefreshNote().
EndTurn()
void Player.EndTurn (bool consume = true) inline
Definition at line 854 of file Player.cs.
    {
        if (EClass.pc.isDead)
        {
            return;
        }
        if (consume)
        {
            EInput.Consume(false, 1);
        }
        EClass.pc.SetAI(new GoalEndTurn());
        EClass.player.baseActTime = EClass.setting.defaultActPace;
    }
References GameSetting.defaultActPace, Chara.isDead, EClass.pc, Chara.SetAI(), and EClass.setting.
Referenced by AM_Adv._OnUpdateInput(), Chara.AddCondition(), InvOwner.ListInteractions(), AM_Adv.OnBecomeNoGoal(), MiniGame.OnPlay(), TraitDeed.OnRead(), LayerMiniGame.OnUpdateInput(), TraitRope.OnUse(), ActRanged.Perform(), ActPlan.Item.Perform(), LayerCraftFloat.RefreshDisassemble(), WidgetCurrentTool.Select(), ActPlan.ShowContextMenu(), TraitContainer.TryOpen(), ButtonAbility.TryUse(), ButtonAbility.Use(), and Chara.UseAbility().
EnterLocalZone() [1/2]
void Player.EnterLocalZone (bool encounter = false, Chara mob = null) inline
Definition at line 716 of file Player.cs.
    {
        this.EnterLocalZone(EClass.pc.pos.Copy(), null, encounter, mob);
    }
References Point.Copy(), EnterLocalZone(), EClass.pc, and Card.pos.
Referenced by AM_Adv._OnUpdateInput(), ActPlan._Update(), EnterLocalZone(), OnExitBorder(), LayerTravel.Refresh(), and Chara.Tick().
EnterLocalZone() [2/2]
void Player.EnterLocalZone (Point p, ZoneTransition trans = null, bool encounter = false, Chara mob = null) inline
Definition at line 721 of file Player.cs.
    {
        if (EClass._zone.IsRegion)
        {
            p.Set(p.x + EClass.scene.elomap.minX, p.z + EClass.scene.elomap.minY);
        }
        Zone zone = EClass._zone.Region.GetZoneAt(p.x, p.z);
        int enemies = 1;
        int roadDist = EClass.scene.elomap.GetRoadDist(p.x, p.z);
        int num = (EClass.pc.homeBranch == null) ? 0 : EClass.pc.pos.Distance(EClass.game.StartZone.mapX, EClass.game.StartZone.mapY);
        if (zone == null)
        {
            if (!EClass._zone.Region.CanCreateZone(p))
            {
                Msg.Say("zoneBlocked");
                return;
            }
            int num2 = Mathf.Clamp(roadDist - 4, 0, 200) + Mathf.Clamp(num / 4, 0, 10);
            if (roadDist > 20)
            {
                num2 += roadDist - 20;
            }
            if (num2 >= 100)
            {
                num2 = 100;
            }
            Debug.Log(string.Concat(new string[]
            {
                "encounter roadiDist:",
                roadDist.ToString(),
                " homeDist:",
                num.ToString(),
                " lv:",
                num2.ToString()
            }));
            zone = EClass._zone.Region.CreateZone(p);
            zone._dangerLv = num2;
            enemies = 2 + Mathf.Min(num2 / 10, 4) + EClass.rnd(3 + Mathf.Min(num2 / 10, 4));
            if (num < 5)
            {
                enemies = 2;
            }
        }
        else
        {
            if (zone is Zone_Void && EClass.player.CountKeyItem("license_void") == 0)
            {
                Msg.Say("voidClosed");
                return;
            }
            if (zone.IsClosed)
            {
                Msg.Say("zoneClosed");
                return;
            }
            if (zone is Zone_Casino)
            {
                Msg.Say("zoneNoEntrance");
                return;
            }
        }
        if (trans == null)
        {
            ZoneTransition.EnterState state = encounter ? ZoneTransition.EnterState.Encounter : ((zone.RegionEnterState == ZoneTransition.EnterState.Dir) ? ZoneTransition.DirToState(EClass.pc.GetCurrentDir()) : zone.RegionEnterState);
            trans = new ZoneTransition
            {
                state = state
            };
        }
        EClass.pc.MoveZone(zone, trans);
        if (encounter)
        {
            zone.events.AddPreEnter(new ZonePreEnterEncounter
            {
                enemies = enemies,
                roadDist = roadDist,
                mob = mob
            }, true);
        }
    }
References EClass._zone, ZoneEventManager.AddPreEnter(), Region.CanCreateZone(), CountKeyItem(), Region.CreateZone(), ZoneTransition.DirToState(), Point.Distance(), Scene.elomap, Zone.events, EClass.game, Chara.GetCurrentDir(), EloMap.GetRoadDist(), Zone.GetZoneAt(), Spatial.IsClosed, Spatial.IsRegion, Spatial.mapX, Spatial.mapY, EloMap.minX, EloMap.minY, Chara.MoveZone(), EClass.pc, EClass.player, Card.pos, Zone.Region, Zone.RegionEnterState, EClass.rnd(), Msg.Say(), EClass.scene, Point.Set(), Game.StartZone, Point.x, Point.z, and zone.
EquipTool()
void Player.EquipTool (Thing a, bool setHotItem = true) inline
Definition at line 943 of file Player.cs.
    {
        if (a.GetRootCard() != EClass.pc)
        {
            if (a.parent is Thing)
            {
                Msg.Say("movedToEquip", a, a.parent as Thing, null, null);
            }
            a = EClass.pc.AddThing(a, true, -1, -1);
        }
        if (setHotItem)
        {
            EClass.player.SetCurrentHotItem(a.trait.GetHotItem());
            SE.SelectHotitem();
        }
    }
References Card.AddThing(), Trait.GetHotItem(), Card.GetRootCard(), Card.parent, EClass.pc, EClass.player, Msg.Say(), SetCurrentHotItem(), and Card.trait.
ExitBorder()
void Player.ExitBorder (ActPlan p = null) inline
Definition at line 629 of file Player.cs.
    {
        bool flag = EClass.game.quests.HasFarAwayEscort(false);
        string textDialog = (flag ? "ExitZoneEscort" : "ExitZone").lang(EClass._zone.Name, null, null, null, null);
        bool flag2 = EClass.pc.pos.x == EClass._map.bounds.x || EClass.pc.pos.x == EClass._map.bounds.x + EClass._map.bounds.Width - 1 || EClass.pc.pos.z == EClass._map.bounds.z || EClass.pc.pos.z == EClass._map.bounds.z + EClass._map.bounds.Height - 1;
        if (flag || EClass.core.config.game.confirmMapExit || (EClass._zone.instance != null && EClass._zone.instance.WarnExit))
        {
            if (p == null)
            {
                Dialog.YesNo(textDialog, delegate
                {
                    EClass.game.quests.HasFarAwayEscort(true);
                    EClass.pc.MoveZone(EClass._zone.ParentZone, ZoneTransition.EnterState.Auto);
                }, delegate
                {
                }, "yes", "no");
                return;
            }
            p.TrySetAct("actNewZone", delegate()
            {
                Dialog.YesNo(textDialog, delegate
                {
                    EClass.game.quests.HasFarAwayEscort(true);
                    EClass.pc.MoveZone(EClass._zone.ParentZone, ZoneTransition.EnterState.Auto);
                }, null, "yes", "no");
                return false;
            }, CursorSystem.MoveZone, flag2 ? 999 : 1);
            return;
        }
        else
        {
            if (p == null)
            {
                EClass.pc.MoveZone(EClass._zone.ParentZone, ZoneTransition.EnterState.Auto);
                return;
            }
            p.TrySetAct("actNewZone", delegate()
            {
                EClass.pc.MoveZone(EClass._zone.ParentZone, ZoneTransition.EnterState.Auto);
                return false;
            }, CursorSystem.MoveZone, flag2 ? 999 : 1);
            return;
        }
    }
References EClass._zone, EClass.core, EClass.game, QuestManager.HasFarAwayEscort(), Zone.instance, Chara.MoveZone(), Spatial.Name, Zone.ParentZone, EClass.pc, Game.quests, ZoneInstance.WarnExit, and Dialog.YesNo().
Referenced by ActPlan._Update(), AM_Adv.AxisMove(), and AM_Adv.PressedActionMove().
g__LvUp() [1/2]
static void< AddExpKnowledge > Player.g__LvUp () inline static package
Definition at line 1320 of file Player.cs.
    {
        Msg.Say("DingKnowledge");
    }
References Msg.Say().
Referenced by AddExpInfluence(), and AddExpKnowledge().
g__LvUp() [2/2]
static void< AddExpInfluence > Player.g__LvUp () inline static package
Definition at line 1326 of file Player.cs.
    {
        Msg.Say("DingInfluence");
    }
References Msg.Say().
g__SetSpellbook()
static Thing< CreateEquip > Player.g__SetSpellbook (Thing t, int charge) inline static package
Definition at line 1311 of file Player.cs.
    {
        t.AddEditorTag(EditorTag.NoReadFail);
        t.c_charges = charge;
        t.SetBlessedState(BlessedState.Normal);
        return t;
    }
References Card.AddEditorTag(), and Card.SetBlessedState().
Referenced by CreateEquip().
GenerateBackgroundText()
void Player.GenerateBackgroundText () inline
Definition at line 432 of file Player.cs.
    {
        string text = IO.LoadText(new DirectoryInfo(CorePath.CorePackage.Background).GetFiles("*.txt").RandomItem<FileInfo>().FullName);
        IO.SaveText(GameIO.pathCurrentSave + "background.txt", text);
    }
References GameIO.pathCurrentSave, and text.
Referenced by OnStartNewGame().
GetBackgroundText()
string Player.GetBackgroundText () inline
Definition at line 438 of file Player.cs.
    {
        StringBuilder stringBuilder = new StringBuilder(IO.LoadText(GameIO.pathCurrentSave + "background.txt"));
        stringBuilder.Replace("#name", EClass.pc.NameSimple);
        stringBuilder.Replace("#aka", EClass.pc.Aka);
        stringBuilder.Replace("#father", EClass.pc.bio.nameDad);
        stringBuilder.Replace("#mother", EClass.pc.bio.nameMom);
        stringBuilder.Replace("#birthloc2", EClass.pc.bio.nameHome);
        stringBuilder.Replace("#birthloc", EClass.pc.bio.nameLoc);
        stringBuilder.Replace("#job", EClass.pc.job.GetName().AddArticle());
        stringBuilder.Replace("#year", EClass.pc.bio.birthYear.ToString() ?? "");
        stringBuilder.Replace("#month", EClass.pc.bio.birthMonth.ToString() ?? "");
        stringBuilder.Replace("#day", EClass.pc.bio.birthDay.ToString() ?? "");
        stringBuilder.Replace("#he", (EClass.pc.IsMale ? "he" : "she").lang());
        stringBuilder.Replace("#his", (EClass.pc.IsMale ? "his" : "her").lang());
        stringBuilder.Replace("#him", (EClass.pc.IsMale ? "him" : "her").lang());
        string text = "_period".lang();
        string[] array = stringBuilder.ToString().Split(text, StringSplitOptions.None);
        string text2 = "";
        if (array.Length != 0)
        {
            foreach (string text3 in array)
            {
                text2 += text3.ToTitleCase(false);
                if (text3 != text && text3 != Environment.NewLine && text3.Length > 2 && text3 != array[array.Length - 1])
                {
                    text2 += text;
                }
            }
        }
        return text2.TrimEnd(Environment.NewLine.ToCharArray());
    }
References Chara.Aka, Card.bio, Biography.birthDay, Biography.birthMonth, Biography.birthYear, Card.IsMale, Chara.job, Biography.nameDad, Biography.nameHome, Biography.nameLoc, Biography.nameMom, Card.NameSimple, GameIO.pathCurrentSave, EClass.pc, and text.
Referenced by WindowChara.RefreshNote().
GetDomains()
ElementContainer Player.GetDomains () inline
Definition at line 345 of file Player.cs.
    {
        ElementContainer elementContainer = new ElementContainer();
        foreach (int id in this.domains)
        {
            elementContainer.GetOrCreateElement(id).vSource = 1;
        }
        return elementContainer;
    }
References domains.
Referenced by UICharaMaker.Refresh(), and WindowChara.RefreshNote().
HasValidRangedTarget()
bool Player.HasValidRangedTarget () inline
Definition at line 1056 of file Player.cs.
    {
        return this.target != null && this.target.IsAliveInCurrentZone && this.target.isSynced && EClass.pc.CanSee(this.target);
    }
References Chara.CanSee(), EClass.pc, and target.
Referenced by AM_Adv._OnUpdateInput().
IsPriorityAction()
bool Player.IsPriorityAction (string id, Thing t) inline
Definition at line 312 of file Player.cs.
    {
        if (!id.IsEmpty() && t != null)
        {
            List<string> list = this.priorityActions.TryGetValue(id, null);
            if (list != null && list.Contains(t.id))
            {
                return true;
            }
        }
        return false;
    }
References Card.id, and priorityActions.
Referenced by InvOwner.AutoUse(), and InvOwner.GetAutoUseLang().
MarkMapHighlights()
void Player.MarkMapHighlights () inline
Definition at line 1188 of file Player.cs.
    {
        this.ClearMapHighlights();
        this.currentHotItem.OnMarkMapHighlights();
    }
References ClearMapHighlights(), currentHotItem, and HotItem.OnMarkMapHighlights().
Referenced by AM_Adv.OnAfterUpdate(), and RefreshCurrentHotItem().
ModFame()
void Player.ModFame (int a) inline
Definition at line 868 of file Player.cs.
    {
        if (a == 0)
        {
            return;
        }
        if (a >= 0 && this.fame + a >= 5000 && EClass.player.CountKeyItem("license_adv") == 0)
        {
            a = 5000 - this.fame;
            if (a <= 0)
            {
                a = 0;
                Msg.Say("gainFameLimit");
                return;
            }
        }
        this.fame += a;
        if (this.fame < 0)
        {
            this.fame = 0;
        }
        if (a > 0)
        {
            Msg.Say("gainFame", a.ToString() ?? "", null, null, null);
        }
        else
        {
            Msg.Say("looseFame", (-a).ToString() ?? "", null, null, null);
        }
        if (a > 0)
        {
            Tutorial.Reserve("fame", null);
        }
    }
References CountKeyItem(), fame, EClass.player, Tutorial.Reserve(), and Msg.Say().
Referenced by ZonePreEnterBoutWin.Execute(), Quest.Fail(), CoreDebug.ModFame(), QuestRandom.OnDropReward(), and Chara.TryDropBossLoot().
ModKarma()
void Player.ModKarma (int a) inline
Definition at line 1255 of file Player.cs.
    {
        if (a == 0)
        {
            return;
        }
        if (a < 0)
        {
            Tutorial.Reserve("karma", null);
        }
        bool flag = this.karma < 0;
        this.karma += a;
        Msg.Say((a > 0) ? "karmaUp" : "karmaDown", a.ToString() ?? "", null, null, null);
        if (this.karma < 0 && !flag)
        {
            Msg.Say("becomeCriminal");
            EClass.pc.pos.TryWitnessCrime(EClass.pc, null, 4, null);
            EClass._zone.RefreshCriminal();
            Tutorial.Reserve("criminal", null);
        }
        if (this.karma >= 0 && flag)
        {
            Msg.Say("becomeNonCriminal");
            EClass._zone.RefreshCriminal();
        }
        EClass.game.quests.list.ForeachReverse(delegate(Quest q)
        {
            q.OnModKarma(a);
        });
        this.karma = Mathf.Clamp(this.karma, -100, 100);
    }
References EClass._zone, EClass.game, karma, QuestManager.list, Quest.OnModKarma(), EClass.pc, Card.pos, Game.quests, Zone.RefreshCriminal(), Tutorial.Reserve(), Msg.Say(), and Point.TryWitnessCrime().
Referenced by TraitAltar._OnOffer(), Quest.Complete(), ActEffect.DamageEle(), Chara.Die(), ZonePreEnterEncounter.Execute(), Quest.Fail(), AI_Fuck.Finish(), Chara.HoldCard(), Chara.Kick(), CoreDebug.ModKarma(), OnAdvanceDay(), Faction.OnAdvanceMonth(), InvOwner.OnClick(), TaskHarvest.OnCreateProgress(), ZoneEventHarvest.OnLeaveZone(), TaskDig.OnProgressComplete(), TaskMine.OnProgressComplete(), TraitBaseSpellbook.OnRead(), TraitIndulgence.OnRead(), ActRestrain.Perform(), ActEffect.Poison(), FoodEffect.Proc(), InvOwner.Transaction.Process(), AI_Steal.Run(), AI_Shopping.SellChara(), Chara.TryDropBossLoot(), Trait.TryOpenLock(), and Card.TryUnrestrain().
ModKeyItem() [1/2]
void Player.ModKeyItem (int id, int num = 1, bool msg = true) inline
Definition at line 908 of file Player.cs.
    {
        if (!this.keyItems.ContainsKey(id))
        {
            this.keyItems.Add(id, 0);
        }
        Dictionary<int, int> dictionary = this.keyItems;
        dictionary[id] += num;
        if (msg)
        {
            if (num > 0)
            {
                SE.Play("keyitem");
                Msg.Say("get_keyItem", EClass.sources.keyItems.map[id].GetName(), null, null, null);
                return;
            }
            SE.Play("keyitem_lose");
            Msg.Say("lose_keyItem", EClass.sources.keyItems.map[id].GetName(), null, null, null);
        }
    }
References keyItems, SourceManager.keyItems, Msg.Say(), and EClass.sources.
ModKeyItem() [2/2]
void Player.ModKeyItem (string alias, int num = 1, bool msg = true) inline
Definition at line 903 of file Player.cs.
    {
        this.ModKeyItem(EClass.sources.keyItems.alias[alias].id, num, msg);
    }
References SourceManager.keyItems, ModKeyItem(), and EClass.sources.
Referenced by TraitGodStatue._OnUse(), ModKeyItem(), TraitLicense.OnRead(), OnStartNewGame(), TraitGainPrecious.OnUse(), and DramaManager.ParseLine().
MoveZone()
void Player.MoveZone (Zone z) inline
Definition at line 802 of file Player.cs.
    {
        CursorSystem.ignoreCount = 15;
        EClass.ui.hud.transRight.SetActive(false);
        this.zone = z;
        if (this.zone.IsRegion)
        {
            this.dateTravel = EClass.world.date.GetRaw(0);
        }
        EClass.scene.Init(Scene.Mode.Zone);
        if (WidgetRoster.Instance)
        {
            WidgetRoster.Instance.OnMoveZone();
        }
        if (UIResourceTrack.Instance)
        {
            UIResourceTrack.Instance.OnMoveZone();
        }
        if (WidgetMinimap.Instance)
        {
            WidgetMinimap.Instance.OnMoveZone();
        }
        if (EClass.pc.currentZone == this.zone && !this.zone.IsRegion && this.LastTravelZone != this.zone)
        {
            if (this.LastTravelZone != null)
            {
                int num = EClass.world.date.GetElapsedHour(this.dateTravel);
                int num2 = num / 24;
                if (this.distanceTravel > 2)
                {
                    num %= 24;
                    Msg.Say("travel", this.LastTravelZone.Name, Date.GetText(this.dateTravel, Date.TextFormat.Travel), num2.ToString() ?? "", num.ToString() ?? "");
                    Msg.Say("travel2", this.distanceTravel.ToString() ?? "", ((EClass.pc.party.members.Count == 1) ? "you" : "youAndCompanion").lang(), null, null);
                    foreach (Chara chara in EClass.pc.party.members)
                    {
                        chara.AddExp(this.distanceTravel / 3);
                        chara.elements.ModExp(240, 30 + this.distanceTravel * 5, false);
                    }
                }
            }
            this.distanceTravel = 0;
            this.dateTravel = EClass.world.date.GetRaw(0);
            this.uidLastTravelZone = this.zone.uid;
        }
        this.regionMoveWarned = false;
    }
References Card.AddExp(), chara, Chara.currentZone, World.date, dateTravel, distanceTravel, Card.elements, Date.GetElapsedHour(), Date.GetRaw(), Date.GetText(), Scene.Init(), UIResourceTrack.Instance, WidgetMinimap.Instance, WidgetRoster.Instance, Spatial.IsRegion, LastTravelZone, Party.members, ElementContainer.ModExp(), Spatial.Name, UIResourceTrack.OnMoveZone(), WidgetMinimap.OnMoveZone(), WidgetRoster.OnMoveZone(), Chara.party, EClass.pc, Msg.Say(), EClass.scene, EClass.ui, Spatial.uid, EClass.world, and zone.
Referenced by AM_ViewZone._OnUpdateInput(), LayerNewZone.OnClickExit(), and Scene.OnUpdate().
OnAdvanceDay()
void Player.OnAdvanceDay () inline
Definition at line 1150 of file Player.cs.
    {
        this.nums.OnAdvanceDay();
        Chara pc = EClass.pc;
        int c_daysWithGod = pc.c_daysWithGod;
        pc.c_daysWithGod = c_daysWithGod + 1;
        if (EClass.pc.Evalue(85) > 0)
        {
            EClass.pc.ModExp(85, 10);
        }
        EClass.pc.RefreshFaithElement();
        this.prayed = false;
        if (this.karma < 0 && EClass.rnd(4) == 0)
        {
            this.ModKarma(1);
        }
    }
References Card.c_daysWithGod, Card.Evalue(), karma, Card.ModExp(), ModKarma(), nums, NumLogManager.OnAdvanceDay(), EClass.pc, Chara.RefreshFaithElement(), and EClass.rnd().
Referenced by GameDate.AdvanceDay().
OnAdvanceHour()
void Player.OnAdvanceHour () inline
Definition at line 1131 of file Player.cs.
    {
        EClass.pc.faith.OnChangeHour();
        if (EClass.pc.Evalue(289) > 0)
        {
            foreach (Thing t2 in EClass.pc.things.List((Thing t) => t.c_IDTState == 5, true))
            {
                EClass.pc.TryIdentify(t2, 1, true);
            }
        }
        if (!EClass.pc.IsDeadOrSleeping && EClass.rnd(2) == 0 && !EClass._zone.IsRegion)
        {
            foreach (Chara chara in EClass.pc.party.members)
            {
                chara.AddExp(1);
            }
        }
    }
References EClass._zone, Card.AddExp(), Card.c_IDTState, chara, Card.Evalue(), Chara.faith, Chara.IsDeadOrSleeping, Spatial.IsRegion, ThingContainer.List(), Party.members, Religion.OnChangeHour(), Chara.party, EClass.pc, EClass.rnd(), Card.things, and Chara.TryIdentify().
Referenced by GameDate.AdvanceHour().
OnAdvanceRealHour()
void Player.OnAdvanceRealHour () inline
Definition at line 325 of file Player.cs.
    {
        Player.realHour++;
        Msg.Say("time_warn", Player.realHour.ToString() ?? "", null, null, null);
        string text = "time_warn_" + Player.realHour.ToString();
        if (LangGame.Has(text))
        {
            Msg.Say(text);
        }
    }
References realHour, Msg.Say(), and text.
Referenced by AM_Adv.OnBecomeNoGoal().
OnBeforeSave()
void Player.OnBeforeSave () inline
Definition at line 266 of file Player.cs.
    {
        foreach (Layer comp in EClass.ui.layerFloat.layers)
        {
            foreach (Window window in comp.GetComponentsInDirectChildren(true))
            {
                window.UpdateSaveData();
            }
        }
        this.dataWindow = Window.dictData;
    }
References EClass.ui.
OnCreateGame()
void Player.OnCreateGame () inline
Definition at line 154 of file Player.cs.
    {
        this.karma = 30;
        this.debt = 20000000;
        this.chara = CharaGen.Create("chara", -1);
        this.chara.SetFaction(EClass.Home);
        this.chara.things.SetSize(7, 5);
        this.chara.c_idTone = "default";
        this.chara.SetInt(56, 1);
        this.chara.things.DestroyAll(null);
        this.chara.faith = EClass.game.religions.Eyth;
        this.chara.RefreshFaithElement();
        this.uidChara = this.chara.uid;
        Fav fav = IO.LoadFile<Fav>(CorePath.user + "PCC/fav" + EClass.rnd(3).ToString(), false, null);
        this.chara.pccData = IO.Duplicate<PCCData>(fav.data);
        this.chara._CreateRenderer();
        this.RefreshDomain();
        this._agent = CharaGen.Create("chara", -1);
        this._agent.c_altName = "stash".lang();
        EClass.player.title = "master".lang();
        this.nums.OnCreateGame();
        this.hotbars.OnCreateGame();
        this.baseActTime = EClass.setting.defaultActPace;
        this.flags.OnCreateGame();
        this.sketches.Add(115);
        this.pref.sort_ascending_shop = true;
        EClass.game.config.preference.autoEat = true;
        this.flags.toggleHotbarHighlightDisabled = true;
        this.layerAbilityConfig.hideDepletedSpell = true;
        this.layerAbilityConfig.bgAlpha = 70;
        this.memo = "memo_blank".lang();
    }
References Chara._CreateRenderer(), chara, CharaGen.Create(), GameSetting.defaultActPace, ThingContainer.DestroyAll(), ReligionManager.Eyth, flags, EClass.game, EClass.Home, hotbars, nums, HotbarManager.OnCreateGame(), NumLogManager.OnCreateGame(), OnCreateGame(), RefreshDomain(), Chara.RefreshFaithElement(), Game.religions, EClass.rnd(), Chara.SetFaction(), BaseCard.SetInt(), ThingContainer.SetSize(), EClass.setting, sketches, Card.things, and Card.uid.
Referenced by OnCreateGame().
OnExitBorder()
void Player.OnExitBorder (Point p) inline
Definition at line 679 of file Player.cs.
    {
        if (EClass._zone.ParentZone.IsRegion)
        {
            int num = 0;
            int num2 = 0;
            MapBounds bounds = EClass._map.bounds;
            if (p.x < bounds.x)
            {
                num = -1;
            }
            else if (p.x > bounds.maxX)
            {
                num = 1;
            }
            else if (p.z < bounds.z)
            {
                num2 = -1;
            }
            else
            {
                num2 = 1;
            }
            ZoneTransition.EnterState state = (num == 1) ? ZoneTransition.EnterState.Left : ((num == -1) ? ZoneTransition.EnterState.Right : ((num2 == 1) ? ZoneTransition.EnterState.Bottom : ZoneTransition.EnterState.Top));
            float ratePos = (num == 1 || num == -1) ? ((float)(p.z - bounds.z) / (float)bounds.Height) : ((float)(p.x - bounds.x) / (float)bounds.Width);
            ZoneTransition trans = new ZoneTransition
            {
                state = state,
                ratePos = ratePos
            };
            Point p2 = new Point(EClass._zone.x + num, EClass._zone.y + num2);
            this.EnterLocalZone(p2, trans, false, null);
            return;
        }
        EClass.pc.MoveZone(EClass._zone.ParentZone, ZoneTransition.EnterState.Auto);
    }
References EClass._map, EClass._zone, Map.bounds, EnterLocalZone(), MapBounds.Height, Spatial.IsRegion, MapBounds.maxX, Chara.MoveZone(), Zone.ParentZone, EClass.pc, MapBounds.Width, MapBounds.x, Point.x, Spatial.x, Spatial.y, MapBounds.z, and Point.z.
OnLoad()
void Player.OnLoad () inline
Definition at line 242 of file Player.cs.
    {
        this.nums.OnLoad();
        this.codex.OnLoad();
        if (this.dataWindow != null)
        {
            Window.dictData = this.dataWindow;
        }
        EClass.pc.Refresh(false);
        if (Application.isEditor && EClass.debug.resetPlayerConfig && !this.isEditor)
        {
            EClass.game.config = new Game.Config();
            if (this.dataWindow != null)
            {
                this.dataWindow.Clear();
            }
            EClass.pc.things.Foreach(delegate(Thing t)
            {
                t.c_windowSaveData = null;
            }, false);
        }
        this.isEditor = Application.isEditor;
    }
References codex, dataWindow, EClass.debug, ThingContainer.Foreach(), nums, CodexManager.OnLoad(), NumLogManager.OnLoad(), EClass.pc, Chara.Refresh(), CoreDebug.resetPlayerConfig, and Card.things.
Referenced by Game.OnLoad().
OnStartNewGame()
void Player.OnStartNewGame () inline
Definition at line 187 of file Player.cs.
    {
        this.ModKeyItem("old_charm", 1, false);
        this.ModKeyItem("backpack", 1, false);
        EClass.player.knownBGMs.Add(1);
        EClass.player.knownBGMs.Add(3);
        EClass.player.questTracker = true;
        this.trackedCategories.Add("food");
        this.trackedCategories.Add("drink");
        this.trackedCategories.Add("resource");
        EClass.game.quests.Start("main", null, true);
        this.chara.hp = this.chara.MaxHP;
        this.chara.SetFaith(EClass.game.religions.list[0]);
        this.chara.elements.SetBase(135, 1, 0);
        this.chara.elements.SetBase(6003, 1, 0);
        this.chara.elements.SetBase(6012, 1, 0);
        this.chara.elements.SetBase(6015, 1, 0);
        this.chara.elements.SetBase(6050, 1, 0);
        List<Element> list = new List<Element>();
        foreach (Element item in EClass.pc.elements.dict.Values)
        {
            list.Add(item);
        }
        foreach (Element element in list)
        {
            if (element.Value == 0)
            {
                EClass.pc.elements.Remove(element.id);
            }
            else if (element.HasTag("primary"))
            {
                element.vTempPotential = Mathf.Max(30, (element.ValueWithoutLink - 8) * 7);
            }
        }
        foreach (BodySlot slot in this.chara.body.slots)
        {
            this.chara.body.Unequip(slot, true);
        }
        this.chara.things.DestroyAll(null);
        this.CreateEquip();
        this.dateTravel = EClass.world.date.GetRaw(0);
        this.uidLastTravelZone = EClass.pc.currentZone.uid;
        this.GenerateBackgroundText();
        if (!EClass.game.Difficulty.allowRevive)
        {
            EClass.pc.SetFeat(1220, 1, false);
        }
        EClass.pc.elements.CheckSkillActions();
        EClass.pc.hunger.value = 30;
        EClass.pc.CalculateMaxStamina();
        EClass.pc.stamina.Set(EClass.pc.stamina.max / 2);
        EClass.pc.Refresh(false);
        this.isEditor = Application.isEditor;
    }
References GameDifficulty.allowRevive, Chara.body, Chara.CalculateMaxStamina(), chara, ElementContainerCard.CheckSkillActions(), CreateEquip(), Chara.currentZone, World.date, ThingContainer.DestroyAll(), ElementContainer.dict, Game.Difficulty, Card.elements, EClass.game, GenerateBackgroundText(), Date.GetRaw(), Element.HasTag(), Element.id, knownBGMs, ReligionManager.list, Chara.MaxHP, ModKeyItem(), EClass.pc, EClass.player, Game.quests, Chara.Refresh(), Game.religions, ElementContainer.Remove(), ElementContainer.SetBase(), Chara.SetFaith(), Chara.SetFeat(), CharaBody.slots, Chara.stamina, QuestManager.Start(), Card.things, trackedCategories, Spatial.uid, CharaBody.Unequip(), Element.Value, Element.ValueWithoutLink, and EClass.world.
RefreshCurrentHotItem()
void Player.RefreshCurrentHotItem () inline
Definition at line 960 of file Player.cs.
    {
        WidgetCurrentTool instance = WidgetCurrentTool.Instance;
        if (this.currentHotItem != null)
        {
            if (instance)
            {
                instance.buttonHotItem.Refresh();
            }
            if (this.currentHotItem is HotItemHeld && this.currentHotItem.Thing != EClass.pc.held)
            {
                this.currentHotItem = null;
            }
            else if (this.currentHotItem is HotItemThing && (this.currentHotItem.Thing == null || this.currentHotItem.Thing.GetRootCard() != EClass.pc))
            {
                this.currentHotItem = null;
            }
        }
        if (EClass.pc.held != null)
        {
            this.currentHotItem = new HotItemHeld(EClass.pc.held as Thing);
        }
        if (this.currentHotItem == null)
        {
            if (instance && instance.selected != -1 && instance.selectedButton.card != null && instance.selectedButton.card.GetRootCard() == EClass.pc)
            {
                this.currentHotItem = instance.selectedButton.card.trait.GetHotItem();
            }
            else
            {
                this.currentHotItem = this.hotItemNoItem;
            }
        }
        if (this.currentHotItem != this.lastHotItem)
        {
            if (this.lastHotItem != null)
            {
                this.lastHotItem.OnUnsetCurrentItem();
            }
            this.currentHotItem.OnSetCurrentItem();
            this.lastHotItem = this.currentHotItem;
        }
        WidgetCurrentTool.RefreshCurrentHotItem();
        WidgetHotbar.dirtyCurrentItem = false;
        this.MarkMapHighlights();
        EClass.core.actionsNextFrame.Add(delegate
        {
            EClass.core.actionsNextFrame.Add(delegate
            {
                foreach (LayerInventory layerInventory in LayerInventory.listInv)
                {
                    layerInventory.invs[0].RefreshHighlight();
                }
            });
        });
        EClass.pc.RecalculateFOV();
    }
References WidgetCurrentTool.buttonHotItem, ButtonGrid.card, EClass.core, currentHotItem, Trait.GetHotItem(), Card.GetRootCard(), Chara.held, hotItemNoItem, WidgetCurrentTool.Instance, lastHotItem, LayerInventory.listInv, MarkMapHighlights(), HotItem.OnSetCurrentItem(), HotItem.OnUnsetCurrentItem(), EClass.pc, Card.RecalculateFOV(), ButtonHotItem.Refresh(), WidgetCurrentTool.RefreshCurrentHotItem(), WidgetCurrentTool.selected, WidgetCurrentTool.selectedButton, Card.Thing, HotItem.Thing, and Card.trait.
Referenced by Scene.Init(), Scene.OnUpdate(), SetCurrentHotItem(), and InvOwner.TryHold().
RefreshDomain()
void Player.RefreshDomain () inline
Definition at line 336 of file Player.cs.
    {
        this.domains.Clear();
        for (int i = 0; i < EClass.pc.job.domain.Length; i += 2)
        {
            this.domains.Add(EClass.pc.job.domain[i]);
        }
    }
References domains, Chara.job, and EClass.pc.
Referenced by CoreDebug.ChangeJob(), UICharaMaker.ListJob(), OnCreateGame(), and UICharaMaker.RerollJob().
RefreshEmptyAlly()
void Player.RefreshEmptyAlly () inline
Definition at line 419 of file Player.cs.
    {
        int num = this.MaxAlly - EClass.pc.party.members.Count + 1;
        if (num != this.lastEmptyAlly)
        {
            this.lastEmptyAlly = num;
            foreach (Chara chara in EClass.pc.party.members)
            {
                chara.RefreshSpeed();
            }
        }
    }
References chara, lastEmptyAlly, Party.members, Chara.party, EClass.pc, and Chara.RefreshSpeed().
Referenced by Scene.Init(), and Scene.OnUpdate().
ResetCurrentHotItem()
void Player.ResetCurrentHotItem () inline
Definition at line 1018 of file Player.cs.
    {
        EClass.pc.PickHeld(false);
        EClass.player.SetCurrentHotItem(null);
        SE.SelectHotitem();
    }
References EClass.pc, Chara.PickHeld(), EClass.player, and SetCurrentHotItem().
Referenced by WidgetCurrentTool.Select().
SelectDomain()
Layer Player.SelectDomain (Action onKill = null) inline
Definition at line 355 of file Player.cs.
    {
        List<SourceElement.Row> list2 = new List<SourceElement.Row>();
        foreach (SourceElement.Row row in EClass.sources.elements.rows)
        {
            if (row.categorySub == "eleAttack" && !row.tag.Contains("hidden") && (!row.tag.Contains("high") || EClass.pc.job.domain.Contains(row.id)))
            {
                list2.Add(row);
            }
        }
        return EClass.ui.AddLayer<LayerList>().SetListCheck<SourceElement.Row>(list2, (SourceElement.Row a) => a.GetName(), delegate(SourceElement.Row s, ItemGeneral b)
        {
            bool flag = false;
            foreach (int num in EClass.player.domains)
            {
                if (s.id == num)
                {
                    flag = true;
                }
            }
            if (flag)
            {
                EClass.player.domains.Remove(s.id);
                return;
            }
            EClass.player.domains.Add(s.id);
        }, delegate(List<UIList.ButtonPair> list)
        {
            bool flag = EClass.player.domains.Count >= 3 + EClass.pc.Evalue(1402);
            foreach (UIList.ButtonPair buttonPair in list)
            {
                UIButton button = (buttonPair.component as ItemGeneral).button1;
                SourceElement.Row row2 = buttonPair.obj as SourceElement.Row;
                bool flag2 = false;
                bool flag3 = false;
                foreach (int num in EClass.player.domains)
                {
                    if (row2.id == num)
                    {
                        flag3 = true;
                    }
                }
                button.SetCheck(flag3);
                for (int i = 0; i < ((EClass.pc.job.id == "swordsage") ? 5 : 3); i++)
                {
                    if (EClass.pc.job.domain[i * 2] == row2.id)
                    {
                        flag2 = true;
                    }
                }
                button.interactable = (!flag2 && (!flag || flag3));
                button.GetComponent<CanvasGroup>().enabled = !button.interactable;
            }
        }).SetOnKill(delegate
        {
            Action onKill2 = onKill;
            if (onKill2 == null)
            {
                return;
            }
            onKill2();
        });
    }
References domains, SourceManager.elements, Card.Evalue(), Chara.job, EClass.pc, EClass.player, EClass.sources, and EClass.ui.
Referenced by UICharaMaker.AddDomain().
SetCurrentHotItem()
void Player.SetCurrentHotItem (HotItem item) inline
Definition at line 1025 of file Player.cs.
    {
        EClass.pc.PickHeld(false);
        if (this.currentHotItem != item)
        {
            this.currentHotItem = item;
            HotItemHeld hotItemHeld = this.currentHotItem as HotItemHeld;
            if (hotItemHeld != null)
            {
                EClass.pc.HoldCard(hotItemHeld.Thing, -1);
            }
        }
        this.RefreshCurrentHotItem();
    }
References currentHotItem, Chara.HoldCard(), EClass.pc, Chara.PickHeld(), RefreshCurrentHotItem(), and HotItemThing.Thing.
Referenced by EquipTool(), ButtonAbility.HoldAbility(), AM_Adv.OnBecomeNoGoal(), LayerAbility.OnUpdateInput(), ResetCurrentHotItem(), Hotbar.Select(), WidgetCurrentTool.Select(), Hotbar.ToggleDisable(), Hotbar.Unselect(), and ActionMode.UpdateInput().
SetPriorityAction()
void Player.SetPriorityAction (string id, Thing t) inline
Definition at line 278 of file Player.cs.
    {
        if (t == null)
        {
            return;
        }
        if (id.IsEmpty())
        {
            using (Dictionary<string, List<string>>.ValueCollection.Enumerator enumerator = this.priorityActions.Values.GetEnumerator())
            {
                while (enumerator.MoveNext())
                {
                    List<string> p = enumerator.Current;
                    p.ForeachReverse(delegate(string i)
                    {
                        if (i == t.id)
{
                            p.Remove(i);
                        }
                    });
                }
                return;
            }
        }
        if (!this.priorityActions.ContainsKey(id))
        {
            this.priorityActions[id] = new List<string>();
        }
        if (!this.priorityActions[id].Contains(t.id))
        {
            this.priorityActions[id].Add(t.id);
        }
    }
References Card.id, and priorityActions.
Referenced by InvOwner.ListInteraction.Add().
SimulateFaction()
void Player.SimulateFaction () inline
Definition at line 604 of file Player.cs.
    {
        this.simulatingZone = true;
        Zone currentZone = EClass.pc.currentZone;
        Point point = EClass.pc.pos.Copy();
        foreach (FactionBranch factionBranch in EClass.pc.faction.GetChildren())
        {
            if (factionBranch.owner != currentZone)
            {
                EClass.pc.MoveZone(factionBranch.owner, ZoneTransition.EnterState.Auto);
                this.zone = factionBranch.owner;
                EClass.scene.Init(Scene.Mode.Zone);
            }
        }
        EClass.pc.MoveZone(currentZone, new ZoneTransition
        {
            state = ZoneTransition.EnterState.Exact,
            x = point.x,
            z = point.z
        });
        this.zone = currentZone;
        EClass.scene.Init(Scene.Mode.Zone);
        this.simulatingZone = false;
    }
References Point.Copy(), Chara.currentZone, Chara.faction, Faction.GetChildren(), Scene.Init(), Chara.MoveZone(), FactionBranch.owner, EClass.pc, Card.pos, and EClass.scene.
Referenced by LayerSleep.Advance().
TargetRanged()
bool Player.TargetRanged () inline
Definition at line 1061 of file Player.cs.
    {
        Thing thing = EClass.player.currentHotItem.Thing;
        if (thing != null)
        {
            Trait trait = thing.trait;
        }
        int num = 999999999;
        Chara chara = null;
        Point pos = EClass.scene.mouseTarget.pos;
        List<Chara> list = new List<Chara>();
        bool flag = false;
        if (EInput.isShiftDown && pos.IsValid && pos.HasChara)
        {
            foreach (Chara chara2 in EClass._map.charas)
            {
                if (chara2.isSynced && chara2.IsAliveInCurrentZone && !chara2.IsPC && chara2.pos.Equals(pos) && EClass.pc.CanSeeLos(chara2.pos, -1))
                {
                    list.Add(chara2);
                }
            }
            if (list.Count > 0)
            {
                chara = list.NextItem(EClass.player.target);
                flag = true;
            }
            list.Clear();
        }
        if (!flag)
        {
            foreach (Chara chara3 in EClass._map.charas)
            {
                int num2 = 0;
                if (chara3.isSynced && chara3.IsAliveInCurrentZone && !chara3.IsPC && EClass.pc.CanSeeLos(chara3.pos, -1) && EClass.pc.CanSee(chara3) && !chara3.IsFriendOrAbove())
                {
                    if (chara3.IsNeutralOrAbove())
                    {
                        num2 += 10000;
                    }
                    num2 += EClass.pc.Dist(chara3);
                    if (num2 < num)
                    {
                        chara = chara3;
                        num = num2;
                    }
                    list.Add(chara3);
                }
            }
            if (EInput.isShiftDown)
            {
                chara = list.NextItem(EClass.player.target);
            }
        }
        if (chara == null)
        {
            if (this.target != null)
            {
                Msg.Say("noTargetFound");
            }
            this.target = null;
            return false;
        }
        if (this.target != chara)
        {
            Msg.Say("targetSet", chara, null, null, null);
        }
        this.target = chara;
        return true;
    }
References EClass._map, Card.Add(), Chara.CanSee(), Chara.CanSeeLos(), chara, Map.charas, currentHotItem, Card.Dist(), Point.Equals(), Point.HasChara, Chara.IsAliveInCurrentZone, Chara.IsFriendOrAbove(), Chara.IsNeutralOrAbove(), Chara.IsPC, Chara.isSynced, Point.IsValid, Scene.mouseTarget, EClass.pc, EClass.player, Card.pos, PointTarget.pos, Msg.Say(), EClass.scene, target, HotItem.Thing, and Card.trait.
Referenced by AM_Adv._OnUpdateInput().
TooHeavyToMove()
bool Player.TooHeavyToMove () inline
Definition at line 1298 of file Player.cs.
    {
        if (!EClass.debug.ignoreWeight && EClass.pc.burden.GetPhase() == 4)
        {
            Msg.Say("tooHeavyToMove");
            EClass.pc.renderer.NextFrame();
            EInput.Consume(true, 1);
            return true;
        }
        return false;
    }
References Chara.burden, EClass.debug, CoreDebug.ignoreWeight, CardRenderer.NextFrame(), EClass.pc, Card.renderer, and Msg.Say().
Referenced by AM_Adv.PressedActionMove(), AI_Goto.Run(), GoalManualMove.Run(), AM_Adv.SetManualMove(), Chara.TryMoveFrom(), and Chara.TryMoveTowards().
TryAbortAutoCombat()
bool Player.TryAbortAutoCombat () inline
Definition at line 1168 of file Player.cs.
    {
        if (!(EClass.pc.ai is GoalAutoCombat))
        {
            return false;
        }
        EClass.pc.ai.Cancel();
        EClass.pc.SetNoGoal();
        return true;
    }
References Chara.ai, AIAct.Cancel(), EClass.pc, and Chara.SetNoGoal().
Referenced by Card.DamageHP(), and Chara.Die().
TryEquipBait()
void Player.TryEquipBait () inline
Definition at line 1040 of file Player.cs.
    {
        if (this.eqBait != null && this.eqBait.GetRootCard() != EClass.pc)
        {
            this.eqBait = null;
        }
        if (this.eqBait == null)
        {
            Thing thing = EClass.pc.things.Find<TraitBait>();
            if (thing != null)
            {
                thing.trait.OnUse(EClass.pc);
            }
        }
    }
References eqBait, ThingContainer.Find(), Card.GetRootCard(), Trait.OnUse(), EClass.pc, Card.things, and Card.trait.
Referenced by AI_Fish.Run().
Member Data Documentation
_agent
Chara Player._agent
Definition at line 1527 of file Player.cs.
altHeldPos
bool Player.altHeldPos
Definition at line 1589 of file Player.cs.
Referenced by CharaRenderer.DrawHeld(), and Chara.GetSubPassData().
angle
float Player.angle
Definition at line 1416 of file Player.cs.
Referenced by Game.OnLoad().
autoCombatStartHP
int Player.autoCombatStartHP
Definition at line 1657 of file Player.cs.
Referenced by AM_Adv._OnUpdateInput().
bankMoney
int Player.bankMoney
Definition at line 1380 of file Player.cs.
baseActTime
float Player.baseActTime
Definition at line 1631 of file Player.cs.
Referenced by Chara.Tick().
chara
Chara Player.chara
Definition at line 1635 of file Player.cs.
Referenced by Core.Awake(), MoveZone(), OnAdvanceHour(), OnCreateGame(), OnStartNewGame(), ItemCulture.Refresh(), RefreshEmptyAlly(), LayerEmbark.RefreshMembers(), WindowChara.RefreshProfile(), GameBlueprint.RerollChara(), LayerEmbark.RerollPC(), LayerEditBio.SetChara(), and TargetRanged().
cinemaConfig
CinemaConfig Player.cinemaConfig = new CinemaConfig()
Definition at line 1551 of file Player.cs.
Referenced by BaseTileMap.Draw().
codex
CodexManager Player.codex = new CodexManager()
Definition at line 1554 of file Player.cs.
Referenced by CharaGen._Create(), ContentCodex.Collect(), TraitCrafter.Craft(), Card.DamageHP(), Card.g__chance(), ContentCodex.OnClickAddCards(), OnLoad(), TraitBaseSpellbook.OnRead(), ContentCodex.RefreshList(), and Card.SpawnLoot().
countNewline
int Player.countNewline
Definition at line 1621 of file Player.cs.
Referenced by GameDate.AdvanceMin().
currentHotItem
HotItem Player.currentHotItem = new HotItemNoItem()
Definition at line 1539 of file Player.cs.
Referenced by AM_Adv._OnUpdateInput(), WidgetCurrentTool._RefreshCurrentHotItem(), ActPlan._Update(), Thing.DoAct(), UIInventory.DoAct(), MarkMapHighlights(), AM_Adv.OnBecomeNoGoal(), WidgetCurrentTool.OnClickButtonHotItem(), ConTorch.OnRemoved(), CharaActorPCC.OnRender(), AM_Adv.OnRenderTile(), TraitAmmo.OnUse(), UIPlaceHelper.Refresh(), TCOrbitChara.RefreshAll(), TCOrbitThing.RefreshAll(), RefreshCurrentHotItem(), UIInventory.RefreshHighlight(), WidgetCurrentTool.RefreshHighlight(), SetCurrentHotItem(), TargetRanged(), Chara.Tick(), Chara.TryEquipRanged(), and ActPlan.Update().
dailyGacha
bool Player.dailyGacha
Definition at line 1422 of file Player.cs.
Referenced by LayerGacha.PlayGacha(), and LayerGacha.RefreshCoin().
dataPick
Window.SaveData Player.dataPick = new Window.SaveData()
Definition at line 1473 of file Player.cs.
Referenced by Chara._Move(), and UIInventory.RefreshMenu().
dataWindow
Dictionary<string, Window.SaveData> Player.dataWindow
Definition at line 1548 of file Player.cs.
Referenced by OnLoad().
dateTravel
int Player.dateTravel
Definition at line 1356 of file Player.cs.
Referenced by MoveZone().
deathDialog
bool Player.deathDialog
Definition at line 1601 of file Player.cs.
Referenced by Scene.OnUpdate().
deathMsg
string Player.deathMsg
Definition at line 1619 of file Player.cs.
Referenced by Chara.Die(), and Scene.OnUpdate().
deathZoneMove
bool Player.deathZoneMove
Definition at line 1605 of file Player.cs.
Referenced by Chara.MoveZone().
debt
int Player.debt
Definition at line 1413 of file Player.cs.
Referenced by QuestDebt.GetTextProgress(), InvOwnerDeliver.PayBill(), and GameDate.ShipGoods().
dialogFlags
Dictionary<string, int> Player.dialogFlags = new Dictionary<string, int>()
Definition at line 1479 of file Player.cs.
Referenced by TCOrbitChara.RefreshAll().
distanceTravel
int Player.distanceTravel
Definition at line 1359 of file Player.cs.
Referenced by Chara._Move(), and MoveZone().
domains
List<int> Player.domains = new List<int>()
Definition at line 1518 of file Player.cs.
Referenced by CreateEquip(), DreamSpell(), GetDomains(), RefreshDomain(), ElementSelecter.Select(), and SelectDomain().
doneBackers
HashSet<int> Player.doneBackers = new HashSet<int>()
Definition at line 1512 of file Player.cs.
Referenced by Zone.Activate(), Map.AddBackerTree(), Map.ApplyBackerObj(), Zone.ApplyBackerPet(), CoreDebug.ClearLastWishFlag(), Chara.Die(), CoreDebug.LastWish(), Chara.OnCreate(), TaskHarvest.OnCreateProgress(), and Zone.Revive().
enemySpotted
bool Player.enemySpotted
Definition at line 1617 of file Player.cs.
Referenced by AI_Goto.Run().
eqBait
Thing Player.eqBait
Definition at line 1545 of file Player.cs.
Referenced by AI_Fish.ProgressFish.OnProgressComplete(), TraitEquipItem.OnSetCardGrid(), AI_Fish.Run(), and TryEquipBait().
expInfluence
int Player.expInfluence
Definition at line 1353 of file Player.cs.
Referenced by AddExpInfluence().
expKnowledge
int Player.expKnowledge
Definition at line 1350 of file Player.cs.
Referenced by AddExpKnowledge().
extraTax
int Player.extraTax
Definition at line 1398 of file Player.cs.
Referenced by Faction.GetTotalTax(), Faction.OnAdvanceMonth(), and Faction.SetTaxTooltip().
fame
int Player.fame
Definition at line 1347 of file Player.cs.
Referenced by Quest.Fail(), Faction.GetFameTax(), ModFame(), and WindowChara.RefreshProfile().
favAbility
HashSet<int> Player.favAbility = new HashSet<int>()
Definition at line 1506 of file Player.cs.
Referenced by GoalAutoCombat.GetAbilities(), ButtonAbility.RefreshFavIcon(), LayerAbility.SelectGroup(), and ButtonAbility.ToggleFav().
flags
Player.Flags Player.flags = new Player.Flags()
Definition at line 1533 of file Player.cs.
Referenced by Chara._Move(), GameDate.AdvanceDay(), RecipeCard.Craft(), Trait.CreateStock(), CoreDebug.EnableDebugResource(), Card.GetPrice(), Scene.Init(), Chara.MutateRandom(), WidgetCurrentTool.OnActivate(), HotItemLayer.OnClick(), OnCreateGame(), TaskBuild.OnProgressComplete(), TraitStoryBook.OnRead(), HotItemLayer.OnSetItem(), Scene.OnUpdate(), Tutorial.Play(), CoreDebug.QuickStart(), FactionBranch.ReceivePackages(), Tutorial.Remove(), Tutorial.Reserve(), GameDate.ShipLetter(), GameDate.ShipRandomPackages(), Chara.ShowDialog(), UI.ToggleFeedback(), Chara.TryDropBossLoot(), Tutorial.TryPlayReserve(), and CoreDebug.UpdateInput().
focusedchara
Chara Player.focusedchara
Definition at line 1637 of file Player.cs.
forceTalk
bool Player.forceTalk
Definition at line 1587 of file Player.cs.
Referenced by Card.Talk().
haltMove
bool Player.haltMove
Definition at line 1607 of file Player.cs.
Referenced by AM_Adv._OnUpdateInput(), and Chara.Tick().
hangIcons
Dictionary<string, string> Player.hangIcons = new Dictionary<string, string>()
Definition at line 1482 of file Player.cs.
Referenced by UIHangIcon.OnClick(), and UIHangIcon.Refresh().
hasNewQuest
bool Player.hasNewQuest
Definition at line 1419 of file Player.cs.
hoard
Hoard Player.hoard = new Hoard()
Definition at line 1530 of file Player.cs.
Referenced by CollectibleActor.OnCollisionEnter2D(), LayerGacha.PlayGacha(), CollectibleActor.PlaySound(), and UIHangIcon.Refresh().
holyWell
int Player.holyWell
Definition at line 1383 of file Player.cs.
Referenced by GameDate.AdvanceMonth().
hotbarPage
int Player.hotbarPage
Definition at line 1389 of file Player.cs.
hotbars
HotbarManager Player.hotbars = new HotbarManager()
Definition at line 1524 of file Player.cs.
Referenced by WidgetMenuPanel.Build(), HotItemContext.g__Toggle(), Scene.Init(), OnCreateGame(), WidgetHotbar.OnSetContextMenu(), BuildMenu.Toggle(), and CoreDebug.UpdateInput().
hotItemNoItem
HotItemNoItem Player.hotItemNoItem = new HotItemNoItem()
Definition at line 1663 of file Player.cs.
Referenced by WidgetCurrentTool._RefreshCurrentHotItem(), and RefreshCurrentHotItem().
hotItemToRestore
HotItem Player.hotItemToRestore
Definition at line 1585 of file Player.cs.
Referenced by AM_Adv.OnBecomeNoGoal().
instaComplete
bool Player.instaComplete = true
Definition at line 1591 of file Player.cs.
Referenced by AM_MoveInstalled.CanInstaComplete(), HitSummary.Execute(), HotItemToggle.OnClick(), and HotItemToggle.ShouldHighlight().
invlunerable
bool Player.invlunerable
Definition at line 1609 of file Player.cs.
Referenced by Card.DamageHP().
isAutoFarming
bool Player.isAutoFarming
Definition at line 1615 of file Player.cs.
Referenced by GrowSystem.Grow(), TraitSeed.MakeSeed(), GrowSystemTree.OnMineObj(), GrowSystem.Perish(), GrowSystem.PopHarvest(), GrowSystem.TryPick(), and GrowSystem.TryPopSeed().
isEditor
bool Player.isEditor
Definition at line 1440 of file Player.cs.
Referenced by WidgetManager.OnGameInstantiated().
karma
int Player.karma
Definition at line 1344 of file Player.cs.
Referenced by ModKarma(), OnAdvanceDay(), WindowChara.RefreshProfile(), and AI_Idle.Run().
keyItems
Dictionary<int, int> Player.keyItems = new Dictionary<int, int>()
Definition at line 1557 of file Player.cs.
Referenced by CountKeyItem(), ModKeyItem(), and ContentKeyItem.OnSwitchContent().
knowledges
KnowledgeManager Player.knowledges = new KnowledgeManager()
Definition at line 1461 of file Player.cs.
knownBGMs
HashSet<int> Player.knownBGMs = new HashSet<int>()
Definition at line 1503 of file Player.cs.
Referenced by OnStartNewGame(), TraitTape.OnUse(), and LayerEditPlaylist.Refresh().
knownCraft
HashSet<int> Player.knownCraft = new HashSet<int>()
Definition at line 1515 of file Player.cs.
Referenced by TraitCrafter.Craft(), and UIDragGridInfo.Init().
knownSongs
Dictionary<string, KnownSong> Player.knownSongs = new Dictionary<string, KnownSong>()
Definition at line 1485 of file Player.cs.
Referenced by AI_PlayMusic.Run().
lastAct
Act Player.lastAct
Definition at line 1643 of file Player.cs.
lastEmptyAlly
int Player.lastEmptyAlly
Definition at line 1627 of file Player.cs.
Referenced by RefreshEmptyAlly(), Chara.RefreshSpeed(), and GoalCombat.TryUseAbility().
lastFelmeraReward
int Player.lastFelmeraReward
Definition at line 1401 of file Player.cs.
Referenced by DramaOutcome.check_sketch2(), DramaOutcome.GetFelmeraRewardIndex(), and DramaOutcome.give_sketch_reward().
lastHotItem
HotItem Player.lastHotItem
Definition at line 1583 of file Player.cs.
Referenced by RefreshCurrentHotItem().
lastMarkedHighlights
List<Point> Player.lastMarkedHighlights = new List<Point>()
Definition at line 1581 of file Player.cs.
Referenced by ClearMapHighlights(), and ActRush.OnMarkMapHighlights().
lastRecipes
Dictionary<string, string> Player.lastRecipes = new Dictionary<string, string>()
Definition at line 1488 of file Player.cs.
Referenced by LayerCraft.OnKill(), and LayerCraft.RefreshCategory().
lastTransition
ZoneTransition Player.lastTransition
Definition at line 1579 of file Player.cs.
Referenced by Scene.OnUpdate().
lastTurn
int Player.lastTurn
Definition at line 1625 of file Player.cs.
Referenced by AM_Adv._OnUpdateInput().
lastZonePos
Point Player.lastZonePos
Definition at line 1542 of file Player.cs.
Referenced by Zone.GetSpawnPos().
layerAbilityConfig
LayerAbility.Config Player.layerAbilityConfig = new LayerAbility.Config()
Definition at line 1476 of file Player.cs.
lightPower
float Player.lightPower
Definition at line 1629 of file Player.cs.
Referenced by BaseTileMap.DrawTile().
lightRadius
int Player.lightRadius
Definition at line 1623 of file Player.cs.
Referenced by BaseTileMap.Draw(), Card.GetSightRadius(), and Card.PlaySound().
listSummon
List<Chara> Player.listSummon = new List<Chara>()
Definition at line 1653 of file Player.cs.
Referenced by Zone.AddGlobalCharasOnActivate(), and Chara.MoveZone().
little_dead
int Player.little_dead
Definition at line 1392 of file Player.cs.
Referenced by Chara.Die(), and TraitTicketFurniture.GetPrice().
little_saved
int Player.little_saved
Definition at line 1395 of file Player.cs.
Referenced by TraitTicketFurniture.GetPrice(), Chara.ShowDialog(), and ActThrow.Throw().
mainWidgets
WidgetManager.SaveData Player.mainWidgets
Definition at line 1467 of file Player.cs.
Referenced by WidgetManager.OnGameInstantiated().
memo
string Player.memo = ""
Definition at line 1449 of file Player.cs.
Referenced by WidgetMemo.OnActivate().
nextMove
Vector2 Player.nextMove
Definition at line 1645 of file Player.cs.
Referenced by GoalManualMove.CanMove(), GoalManualMove.Run(), and GoalManualMove.TryAltMove().
nextZone
Zone Player.nextZone
Definition at line 1659 of file Player.cs.
Referenced by Zone.CanDestroy().
noRestocks
Dictionary<string, HashSet<string> > Player.noRestocks = new Dictionary<string, HashSet<string>>()
Definition at line 1566 of file Player.cs.
Referenced by Trait.g__NoRestock().
notices
NoticeManager Player.notices = new NoticeManager()
Definition at line 1639 of file Player.cs.
Referenced by ContentTop.OnSwitchContent().
nums
NumLogManager Player.nums = new NumLogManager()
Definition at line 1458 of file Player.cs.
Referenced by GameDate.AdvanceMonth(), GameDate.AdvanceYear(), OnAdvanceDay(), OnCreateGame(), OnLoad(), and ContentStatistics.OnSwitchContent().
onStartZone
Action Player.onStartZone
Definition at line 1649 of file Player.cs.
Referenced by Scene.Init().
openContainerCenter
bool Player.openContainerCenter
Definition at line 1443 of file Player.cs.
Referenced by LayerInventory.CreateContainerPC(), and UIInventory.RefreshMenu().
pickupDelay
float Player.pickupDelay = 2f
Definition at line 1633 of file Player.cs.
Referenced by Scene.OnUpdate().
playingSong
PlayingSong Player.playingSong
Definition at line 1651 of file Player.cs.
Referenced by AI_PlayMusic.Run().
popups
PopupManager Player.popups = new PopupManager()
Definition at line 1464 of file Player.cs.
position
Vector3 Player.position
Definition at line 1647 of file Player.cs.
Referenced by CharaRenderer.UpdatePosition().
prayed
bool Player.prayed
Definition at line 1431 of file Player.cs.
Referenced by GameDate.AdvanceDay(), and ActPray.TryPray().
pref
Player.Pref Player.pref = new Player.Pref()
Definition at line 1452 of file Player.cs.
Referenced by Game.Load(), BuildMenu.OnActivate(), AM_Build.OnFinishProcessTiles(), LayerAbility.OnInit(), LayerPeople.OnInit(), LayerResource.OnInit(), UIInventory.OnInit(), LayerMapList.RefreshList(), UIInventory.RefreshMenu(), LayerTech.RefreshTech(), LayerHome.RefreshTech(), and UIInventory.Sort().
preventDeathPenalty
bool Player.preventDeathPenalty
Definition at line 1603 of file Player.cs.
Referenced by Chara.Revive().
priorityActions
Dictionary<string, List<string> > Player.priorityActions = new Dictionary<string, List<string>>()
Definition at line 1491 of file Player.cs.
Referenced by IsPriorityAction(), and SetPriorityAction().
questTracker
bool Player.questTracker
Definition at line 1434 of file Player.cs.
Referenced by Scene.Init(), HotItemWidget.OnClick(), and QuestManager.Start().
queues
QueueManager Player.queues = new QueueManager()
Definition at line 1641 of file Player.cs.
Referenced by UI.OnActivateZone(), and Chara.SetAI().
realHour
int Player.realHour static
Definition at line 1573 of file Player.cs.
Referenced by OnAdvanceRealHour(), and AM_Adv.OnBecomeNoGoal().
recipes
RecipeManager Player.recipes = new RecipeManager()
Definition at line 1536 of file Player.cs.
Referenced by BuildMenu._Search(), CoreDebug.AddAllRecipes(), Card.AddThing(), CoreDebug.AllRecipe(), RecipeManager.ComeUpWithRecipe(), RecipeCard.Craft(), RecipeManager.GetLearnedRecipe(), AM_Picker.Result.GetText(), RecipeManager.GetUnlearnedRecipe(), RecipeManager.IsKnown(), RecipeManager.ListSources(), TaskHarvest.OnCreateProgress(), TaskDig.OnProgressComplete(), TaskMine.OnProgressComplete(), TraitRecipe.OnRead(), TraitRecipeCat.OnRead(), ConSleep.OnRemoved(), TraitCrafter.OnUse(), ResearchPlan.ParseReward(), UIRecipeInfo.Refresh(), BuildMenu.RefreshCategory(), LayerCraft.RefreshCategory(), LayerCraftFloat.RefreshCraft(), WidgetCodex.Search(), ButtonGrid.SetCraftRecipe(), TraitRecipe.SetName(), AM_Picker.TryGetRecipe(), and TraitCrafter.TrySetAct().
regionMoveWarned
bool Player.regionMoveWarned
Definition at line 1593 of file Player.cs.
Referenced by Chara._Move().
renderThing
Thing Player.renderThing
Definition at line 1661 of file Player.cs.
returnInfo
Player.ReturnInfo Player.returnInfo
Definition at line 1332 of file Player.cs.
Referenced by AM_Adv._OnUpdateInput(), Chara.MoveZone(), HotItemActionSleep.Perform(), ActEffect.Proc(), and Chara.Tick().
safeTravel
int Player.safeTravel
Definition at line 1386 of file Player.cs.
Referenced by Chara.Tick().
seedChest
int Player.seedChest
Definition at line 1410 of file Player.cs.
Referenced by ThingGen.g__ChangeSeed().
seedHallucination
int Player.seedHallucination static
Definition at line 1571 of file Player.cs.
Referenced by CardRenderer.Draw().
seedShrine
int Player.seedShrine
Definition at line 1407 of file Player.cs.
Referenced by Zone.TryGenerateShrine().
shippingResults
List<ShippingResult> Player.shippingResults = new List<ShippingResult>()
Definition at line 1563 of file Player.cs.
Referenced by LayerHome.OnSwitchContent(), GameDate.ShipGoods(), and LayerShippingResult.Show().
showShippingResult
bool Player.showShippingResult
Definition at line 1437 of file Player.cs.
Referenced by AM_Adv._OnUpdateInput().
simulatingZone
bool Player.simulatingZone
Definition at line 1613 of file Player.cs.
Referenced by Zone.Activate(), Zone.CanDestroy(), Zone.GetSpawnPos(), Scene.Init(), TraitShackle.IsRestraining(), Chara.MoveZone(), Scene.OnUpdate(), FactionBranch.ReceivePackages(), Zone.RefreshBGM(), and BaseGameScreen.RefreshScreenSize().
sketches
HashSet<int> Player.sketches = new HashSet<int>()
Definition at line 1509 of file Player.cs.
Referenced by DramaOutcome.check_sketch(), DramaOutcome.GetFelmeraRewardIndex(), DramaOutcome.give_sketch_special(), OnCreateGame(), ContentGallery.OnSwitchContent(), and ContentGallery.Refresh().
stats
Player.Stats Player.stats = new Player.Stats()
Definition at line 1455 of file Player.cs.
Referenced by GameDate.AdvanceDay(), GameDate.AdvanceMonth(), LayerShippingResult.Awake(), GameIndex.Create(), Card.DamageHP(), Chara.Die(), ZoneEventSiege.OnFirstTick(), TaskMine.OnProgressComplete(), TraitBookSecret.OnRead(), RecipeManager.OnSleep(), ContentHallOfFame.OnSwitchContent(), Game.OnUpdate(), Scene.OnUpdate(), Zone.OnVisit(), GrowSystem.PopHarvest(), FactionBranch.ReceivePackages(), ContentHallOfFame.Refresh(), LayerShippingResult.Refresh(), WindowChara.RefreshProfile(), LayerGlobalMap.RefreshSummary(), Chara.Revive(), AI_Idle.Run(), AI_OpenGambleChest.Run(), GameDate.ShipGoods(), GameDate.ShipLetter(), LayerSleep.Sleep(), Chara.Tick(), CoreConfig.TryUpdatePlayedHour(), and Zone.UpdateQuests().
subWidgets
WidgetManager.SaveData Player.subWidgets
Definition at line 1470 of file Player.cs.
Referenced by WidgetManager.OnGameInstantiated().
target
Chara Player.target
Definition at line 1665 of file Player.cs.
Referenced by AM_Adv._OnUpdateInput(), HasValidRangedTarget(), Scene.OnUpdate(), and TargetRanged().
taxBills
int Player.taxBills
Definition at line 1374 of file Player.cs.
Referenced by ThingGen.CreateBill(), LayerDragGrid.CreateDeliver(), Faction.OnAdvanceMonth(), InvOwnerDeliver.PayBill(), and UIHomeInfo.RefreshReport().
tempFame
int Player.tempFame
Definition at line 1655 of file Player.cs.
Referenced by CalcMoney.Whore().
title
string Player.title
Definition at line 1446 of file Player.cs.
Referenced by GameLang.Convert(), GameLang.ConvertDrama(), LayerEmbark.GetAlias(), TraitFactionBoard.GetAlias(), and FactionBranch.GetRandomName().
totalFeat
int Player.totalFeat
Definition at line 1371 of file Player.cs.
Referenced by Card.LevelUp(), and WindowChara.RefreshNote().
trackedCards
HashSet<string> Player.trackedCards = new HashSet<string>()
Definition at line 1497 of file Player.cs.
Referenced by UIResourceTrack._Refresh(), WidgetStockTracker._Refresh(), ButtonResourceTrack.SetProp(), and LayerResource.ShowThings().
trackedCategories
HashSet<string> Player.trackedCategories = new HashSet<string>()
Definition at line 1494 of file Player.cs.
Referenced by UIResourceTrack._Refresh(), WidgetStockTracker._Refresh(), OnStartNewGame(), LayerResource.RefreshCategory(), and ButtonResourceTrack.SetCat().
trackedElements
HashSet<int> Player.trackedElements = new HashSet<int>()
Definition at line 1500 of file Player.cs.
Referenced by WidgetTracker.OnSetContextMenu(), ButtonElement.Refresh(), WidgetTracker.Refresh(), and WidgetTracker.Toggle().
tutorialStep
int Player.tutorialStep
Definition at line 1341 of file Player.cs.
Referenced by StickyTutorial.OnClick().
uidChara
int Player.uidChara
Definition at line 1335 of file Player.cs.
uidLastShippedZone
int Player.uidLastShippedZone
Definition at line 1368 of file Player.cs.
Referenced by GameDate.ShipGoods().
uidLastTown
int Player.uidLastTown
Definition at line 1404 of file Player.cs.
Referenced by Scene.OnUpdate().
uidLastTravelZone
int Player.uidLastTravelZone
Definition at line 1362 of file Player.cs.
uidLastZone
int Player.uidLastZone
Definition at line 1365 of file Player.cs.
uidPickOnLoad
List<int> Player.uidPickOnLoad = new List<int>()
Definition at line 1560 of file Player.cs.
uidSpawnZone
int Player.uidSpawnZone
Definition at line 1338 of file Player.cs.
unpaidBill
int Player.unpaidBill
Definition at line 1377 of file Player.cs.
useSubWidgetTheme
bool Player.useSubWidgetTheme
Definition at line 1425 of file Player.cs.
Referenced by WidgetManager.OnGameInstantiated(), and WidgetManager.Reset().
waitingInput
bool Player.waitingInput
Definition at line 1595 of file Player.cs.
Referenced by LayerCraftFloat.RefreshCraft(), and LayerCraftFloat.RefreshDisassemble().
wasDirtyWeight
bool Player.wasDirtyWeight
Definition at line 1599 of file Player.cs.
Referenced by Scene.OnUpdate().
wellWished
bool Player.wellWished
Definition at line 1428 of file Player.cs.
Referenced by TraitGodStatue._OnUse(), and TraitWell.TrySetAct().
willAutoSave
bool Player.willAutoSave
Definition at line 1611 of file Player.cs.
Referenced by AM_Adv._OnUpdateInput().
willEndTurn
bool Player.willEndTurn
Definition at line 1597 of file Player.cs.
Referenced by AM_Adv._OnUpdateInput().
windowAllyInv
Window.SaveData Player.windowAllyInv
Definition at line 1569 of file Player.cs.
Referenced by LayerInventory.CreateContainerAlly().
windowDataCopy
Window.SaveData Player.windowDataCopy
Definition at line 1575 of file Player.cs.
Referenced by UIInventory.RefreshMenu().
windowDataName
string Player.windowDataName
Definition at line 1577 of file Player.cs.
Referenced by UIInventory.RefreshMenu().
zone
Zone Player.zone
Definition at line 1521 of file Player.cs.
Referenced by GameIndex.Create(), EnterLocalZone(), Scene.Init(), CoreDebug.LOG_Spatials(), MoveZone(), TileSelectorElona.OnUpdateInput(), ZoneInspector.RefreshScreen(), and LayerEmbark.SwitchMode().
Property Documentation
Agent
Chara Player.Agent get
Definition at line 70 of file Player.cs.
    {
        get
        {
            return this._agent;
        }
    }
Referenced by AM_Designation< T >.OnProcessTiles(), and TaskMoveInstalled.OnProgressComplete().
ContainerSearchDistance
int Player.ContainerSearchDistance get
Definition at line 78 of file Player.cs.
    {
        get
        {
            return 1 + EClass.pc.elements.GetFeatRef(1643, 0);
        }
    }
EnableDreamStory
bool Player.EnableDreamStory get
Definition at line 46 of file Player.cs.
    {
        get
        {
            return false;
        }
    }
Referenced by Chara.ShowDialog().
IsCriminal
bool Player.IsCriminal get
Definition at line 146 of file Player.cs.
    {
        get
        {
            return this.karma < 0 && !EClass.pc.HasCondition<ConIncognito>();
        }
    }
Referenced by Chara.IsHostile(), WindowChara.RefreshNote(), and GoalCombat.Run().
IsFighterGuildMember
bool Player.IsFighterGuildMember get
Definition at line 119 of file Player.cs.
    {
        get
        {
            Quest quest = EClass.game.quests.Get("guild_fighter");
            return quest != null && quest.phase >= 10;
        }
    }
IsMageGuildMember
bool Player.IsMageGuildMember get
Definition at line 110 of file Player.cs.
    {
        get
        {
            Quest quest = EClass.game.quests.Get("guild_mage");
            return quest != null && quest.phase >= 10;
        }
    }
IsMerchantGuildMember
bool Player.IsMerchantGuildMember get
Definition at line 137 of file Player.cs.
    {
        get
        {
            Quest quest = EClass.game.quests.Get("guild_merchant");
            return quest != null && quest.phase >= 10;
        }
    }
IsThiefGuildMember
bool Player.IsThiefGuildMember get
Definition at line 128 of file Player.cs.
    {
        get
        {
            Quest quest = EClass.game.quests.Get("guild_thief");
            return quest != null && quest.phase >= 10;
        }
    }
LastTravelZone
Zone Player.LastTravelZone get
Definition at line 54 of file Player.cs.
    {
        get
        {
            return RefZone.Get(this.uidLastTravelZone);
        }
    }
Referenced by MoveZone().
LastZone
Zone Player.LastZone get
Definition at line 62 of file Player.cs.
    {
        get
        {
            return RefZone.Get(this.uidLastZone);
        }
    }
MaxAlly
int Player.MaxAlly get
Definition at line 86 of file Player.cs.
    {
        get
        {
            return Mathf.Min(Mathf.Max(EClass.pc.CHA / 10, 1), 5) + EClass.pc.Evalue(1645);
        }
    }
Referenced by WidgetStatsBar.Build().
MaxExpInfluence
int Player.MaxExpInfluence get
Definition at line 102 of file Player.cs.
    {
        get
        {
            return 1000;
        }
    }
Referenced by AddExpInfluence().
MaxExpKnowledge
int Player.MaxExpKnowledge get
Definition at line 94 of file Player.cs.
    {
        get
        {
            return 1000;
        }
    }
Referenced by AddExpKnowledge().
spawnZone
Zone Player.spawnZone get set
Definition at line 34 of file Player.cs.
    {
        get
        {
            return RefZone.Get(this.uidSpawnZone);
        }
        set
        {
            this.uidSpawnZone = RefZone.Set(value);
        }
    }
Referenced by TraitCoreZone.TrySetAct(), and TraitWaystone.TrySetAct().
widgets
WidgetManager.SaveData Player.widgets get set
Definition at line 13 of file Player.cs.
    {
        get
        {
            if (!this.useSubWidgetTheme)
            {
                return this.mainWidgets;
            }
            return this.subWidgets;
        }
        set
        {
            if (this.useSubWidgetTheme)
            {
                this.subWidgets = value;
                return;
            }
            this.mainWidgets = value;
        }
    }
Referenced by WidgetManager.Save().
The documentation for this class was generated from the following file:
Elin/Player.cs