Elin Decompiled Documentation: ZoneInspector Class Reference
ZoneInspector Class Reference
Classes
class FillUtil
class ResizeUtil
Public Member Functions
void RefreshAll ()
void RefreshScreen ()
void SetAllPlayerCreation ()
void Export ()
Public Attributes
ZoneInspector.ResizeUtil resize = new ZoneInspector.ResizeUtil()
ZoneInspector.FillUtil fill = new ZoneInspector.FillUtil()
Zone zone
Static Public Attributes
static ZoneInspector Instance
Static Public Attributes inherited from EMono
static Core core
Properties
string idExport [get]
MapConfig mapConfig [get, set]
MapBounds bounds [get, set]
Properties inherited from EMono
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SoundManager Sound [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static CoreDebug debug [get]
Private Member Functions
void Awake ()
void OnValidate ()
Additional Inherited Members
Static Public Member Functions inherited from EMono
static int rnd (int a)
Detailed Description
Definition at line 4 of file ZoneInspector.cs.
Member Function Documentation
Awake()
void ZoneInspector.Awake () inline private
Definition at line 53 of file ZoneInspector.cs.
    {
        ZoneInspector.Instance = this;
    }
Export()
void ZoneInspector.Export () inline
Definition at line 95 of file ZoneInspector.cs.
    {
        EMono._zone.Export();
    }
References EMono._zone, and Zone.Export().
OnValidate()
void ZoneInspector.OnValidate () inline private
Definition at line 100 of file ZoneInspector.cs.
    {
        if (Application.isPlaying)
        {
            this.RefreshScreen();
        }
    }
References RefreshScreen().
RefreshAll()
void ZoneInspector.RefreshAll () inline
Definition at line 58 of file ZoneInspector.cs.
    {
        EMono._map.RefreshAllTiles();
    }
References EMono._map, and Map.RefreshAllTiles().
RefreshScreen()
void ZoneInspector.RefreshScreen () inline
Definition at line 63 of file ZoneInspector.cs.
    {
        if (!EMono.core.IsGameStarted)
        {
            return;
        }
        EMono.scene.profile = SceneProfile.Load(EMono._map.config.idSceneProfile.IsEmpty("default"));
        EMono.screen.Deactivate();
        if (EMono.player.zone is Region)
        {
            ActionMode.Region.Activate(true, false);
        }
        else
        {
            ActionMode.Adv.Activate(true, false);
        }
        EMono.screen.SetZoom(0.5f);
        EMono.screen.RefreshScreenSize();
    }
References EMono._map, ActionMode.Activate(), ActionMode.Adv, Map.config, EMono.core, BaseGameScreen.Deactivate(), MapConfig.idSceneProfile, SceneProfile.Load(), EMono.player, BaseGameScreen.RefreshScreenSize(), ActionMode.Region, EMono.screen, BaseGameScreen.SetZoom(), and Player.zone.
Referenced by OnValidate().
SetAllPlayerCreation()
void ZoneInspector.SetAllPlayerCreation () inline
Definition at line 83 of file ZoneInspector.cs.
    {
        foreach (Thing thing in EMono._map.things)
        {
            thing.isPlayerCreation = true;
        }
        foreach (Chara chara in EMono._map.charas)
        {
            chara.isPlayerCreation = true;
        }
    }
References EMono._map, Map.charas, and Map.things.
Member Data Documentation
fill
ZoneInspector.FillUtil ZoneInspector.fill = new ZoneInspector.FillUtil()
Definition at line 112 of file ZoneInspector.cs.
Instance
ZoneInspector ZoneInspector.Instance static
Definition at line 108 of file ZoneInspector.cs.
resize
ZoneInspector.ResizeUtil ZoneInspector.resize = new ZoneInspector.ResizeUtil()
Definition at line 110 of file ZoneInspector.cs.
zone
Zone ZoneInspector.zone
Definition at line 114 of file ZoneInspector.cs.
Property Documentation
bounds
MapBounds ZoneInspector.bounds get set
Definition at line 36 of file ZoneInspector.cs.
    {
        get
        {
            Zone zone = this.zone;
            if (zone == null)
            {
                return null;
            }
            return zone.map.bounds;
        }
        set
        {
            this.zone.map.bounds = value;
        }
    }
idExport
string ZoneInspector.idExport get
Definition at line 6 of file ZoneInspector.cs.
    {
        get
        {
            Zone zone = this.zone;
            if (zone == null)
            {
                return null;
            }
            return zone.idExport;
        }
    }
mapConfig
MapConfig ZoneInspector.mapConfig get set
Definition at line 19 of file ZoneInspector.cs.
    {
        get
        {
            Zone zone = this.zone;
            if (zone == null)
            {
                return null;
            }
            return zone.map.config;
        }
        set
        {
            this.zone.map.config = value;
        }
    }
The documentation for this class was generated from the following file:
Elin/ZoneInspector.cs