Elin Decompiled Documentation: InvOwnerEquip Class Reference
InvOwnerEquip Class Reference
Public Member Functions
override bool AllowDrop (Thing t)
InvOwnerEquip (Card owner, BodySlot slot, Card container=null, CurrencyType _currency=CurrencyType.None)
override void ListInteractions (InvOwner.ListInteraction list, Thing t, Trait trait, ButtonGrid b, bool context)
override bool IsFailByCurse (Thing t)
override void OnWriteNote (ButtonGrid button, UINote n)
Public Member Functions inherited from InvOwner
virtual bool AllowHold (Thing t)
virtual bool AllowMoved (Thing t)
virtual bool ShouldShowGuide (Thing t)
virtual bool AllowDrop (Thing t)
virtual Thing CreateDefaultContainer ()
virtual void BuildUICurrency (UICurrency uiCurrency, bool canReroll=false)
bool IsWeightOver (Thing t)
InvOwner (Card owner, Card container=null, CurrencyType _currency=CurrencyType.None, PriceType _price=PriceType.Default)
void Init ()
virtual void OnInit ()
virtual void OnClick (ButtonGrid button)
virtual void OnRightClick (ButtonGrid button)
virtual void OnRightPressed (ButtonGrid button)
InvOwner GetShitDestOwner (ButtonGrid b, bool rightMouse=false)
virtual void OnShiftClick (ButtonGrid b, bool rightMouse=false)
virtual bool CanShiftClick (ButtonGrid b, bool rightMouse=false)
virtual string GetTextShiftClick (ButtonGrid b)
virtual void OnCtrlClick (ButtonGrid button)
virtual bool CanCtrlClick (ButtonGrid b)
virtual string GetTextCtrlClick (ButtonGrid b)
virtual void OnAltClick (ButtonGrid button)
virtual bool CanAltClick (ButtonGrid b)
virtual string GetTextAltClick (ButtonGrid b)
void Grab (DragItemCard.DragInfo from)
Thing PutBack (DragItemCard.DragInfo from)
void OnStartDrag (DragItemCard.DragInfo from)
virtual bool OnCancelDrag (DragItemCard.DragInfo from)
virtual bool OnDrag (DragItemCard.DragInfo from, DragItemCard.DragInfo to, bool execute, bool cancel=false)
virtual void OnProcess (Thing t)
bool CanOpenContainer (Thing t)
InvOwner.ListInteraction ListInteractions (ButtonGrid b, bool context)
bool TryHold (Thing t)
virtual void ListInteractions (InvOwner.ListInteraction list, Thing t, Trait trait, ButtonGrid b, bool context)
virtual string GetAutoUseLang (ButtonGrid button)
void AutoUse (ButtonGrid button, bool repeat=false)
void ShowContextMenu (ButtonGrid button)
virtual int GetPrice (Thing t, CurrencyType currency, int num, bool sell)
virtual string GetTextDetail (Thing t, CurrencyType currency, int num, bool sell)
virtual void OnWriteNote (ButtonGrid button, UINote n)
virtual string IDCostIcon (Thing t)
virtual bool IsFailByCurse (Thing t)
Public Attributes
BodySlot slot
Public Attributes inherited from InvOwner
bool includeChildren
CurrencyType currency
PriceType priceType
HomeResource homeResource
Card owner
Card Container
List< ButtonGrid > buttons = new List<ButtonGrid>()
Properties
override bool AlwaysShowTooltip [get]
override bool ShowNew [get]
Properties inherited from InvOwner
static bool HasTrader [get]
static bool FreeTransfer [get]
virtual bool AllowAutouse [get]
virtual bool AllowContext [get]
virtual bool AllowSell [get]
virtual bool AlwaysShowTooltip [get]
virtual bool UseGuide [get]
virtual bool AllowTransfer [get]
virtual bool AllowDropOnDrag [get]
virtual string langTransfer [get]
virtual int destInvY [get]
virtual bool HasTransaction [get]
virtual bool CopyOnTransfer [get]
virtual bool SingleTarget [get]
bool UseHomeResource [get]
bool IsMagicChest [get]
List< Thing > Things [get]
Chara Chara [get]
ContainerType ContainerType [get]
virtual bool InvertSell [get]
virtual int numDragGrid [get]
virtual bool ShowNew [get]
virtual bool DenyImportant [get]
InvOwner destInvOwner [get]
string IDCurrency [get]
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Additional Inherited Members
Static Public Member Functions inherited from EClass
static int rnd (int a)
static int curve (int a, int start, int step, int rate=75)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Static Public Attributes inherited from InvOwner
static InvOwner.ForceGiveData forceGive = new InvOwner.ForceGiveData()
static InvOwner Trader
static InvOwner Main
static float clickTimer
Static Public Attributes inherited from EClass
static Core core
Detailed Description
Definition at line 3 of file InvOwnerEquip.cs.
Constructor & Destructor Documentation
InvOwnerEquip()
InvOwnerEquip.InvOwnerEquip (Card owner, BodySlot slot, Card container = null, CurrencyType _currency = CurrencyType::None) inline
Definition at line 26 of file InvOwnerEquip.cs.
                                                                                                                       : base(owner, container, _currency, PriceType.Default)
    {
        this.slot = slot;
    }
References slot.
Member Function Documentation
AllowDrop()
override bool InvOwnerEquip.AllowDrop (Thing t) inline virtual
Reimplemented from InvOwner.
Definition at line 21 of file InvOwnerEquip.cs.
    {
        return t.blessedState >= BlessedState.Normal;
    }
IsFailByCurse()
override bool InvOwnerEquip.IsFailByCurse (Thing t) inline virtual
Reimplemented from InvOwner.
Definition at line 50 of file InvOwnerEquip.cs.
    {
        if (t != null && t.blessedState <= BlessedState.Cursed)
        {
            Msg.Say("unequipCursed", t, null, null, null);
            SE.Play("curse3");
            return true;
        }
        return false;
    }
References Card.blessedState, and Msg.Say().
Referenced by ListInteractions().
ListInteractions()
override void InvOwnerEquip.ListInteractions (InvOwner::ListInteraction list, Thing t, Trait trait, ButtonGrid b, bool context) inline virtual
Reimplemented from InvOwner.
Definition at line 31 of file InvOwnerEquip.cs.
    {
        list.Add("actUnequip", 0, delegate()
        {
            if (this.IsFailByCurse(t))
            {
                return;
            }
            if (EClass.pc.things.IsFull(0))
            {
                Msg.Say("backpack_full");
                SE.BeepSmall();
                return;
            }
            EClass.pc.body.Unequip(t, true);
            EClass.Sound.Play("equip");
        }, null);
    }
References Chara.body, IsFailByCurse(), ThingContainer.IsFull(), EClass.pc, EClass.Sound, Card.things, and CharaBody.Unequip().
OnWriteNote()
override void InvOwnerEquip.OnWriteNote (ButtonGrid button, UINote n) inline virtual
Reimplemented from InvOwner.
Definition at line 61 of file InvOwnerEquip.cs.
    {
        if (button.card == null)
        {
            n.Clear();
            n.AddHeader(this.slot.name, null);
            n.AddText("noEQ".lang(), FontColor.DontChange);
            if (this.slot.elementId == 35)
            {
                Thing.AddAttackEvaluation(n, base.Chara, null);
            }
            return;
        }
        base.OnWriteNote(button, n);
    }
References Thing.AddAttackEvaluation(), ButtonGrid.card, BodySlot.elementId, BodySlot.name, and slot.
Member Data Documentation
slot
BodySlot InvOwnerEquip.slot
Definition at line 77 of file InvOwnerEquip.cs.
Referenced by InvOwnerEquip(), InvOwner.OnDrag(), OnWriteNote(), and LayerInventory.TryShowGuide().
Property Documentation
AlwaysShowTooltip
override bool InvOwnerEquip.AlwaysShowTooltip get
Definition at line 5 of file InvOwnerEquip.cs.
    {
        get
        {
            return true;
        }
    }
ShowNew
override bool InvOwnerEquip.ShowNew get
Definition at line 13 of file InvOwnerEquip.cs.
    {
        get
        {
            return true;
        }
    }
The documentation for this class was generated from the following file:
Elin/InvOwnerEquip.cs