Elin Decompiled Documentation: LayerFaith Class Reference
LayerFaith Class Reference
Classes
class Slot
Public Member Functions
void Activate (Religion r, Action< Religion > _onWorship)
void Move (int a)
void RefreshSlots ()
void AddReligion (Religion r)
Public Member Functions inherited from ELayer
override void OnBeforeAddLayer ()
void InitInspector ()
sealed override void Init ()
override void OnAfterAddLayer ()
void TryShowHelp ()
void AddLayerToUI (string id)
void TryShowHint (string _langHint=null)
void TalkHomeMemeber (string id)
void TalkMaid (string id)
override void OnRightClick ()
Public Member Functions inherited from Layer
virtual string GetTextHeader (Window window)
virtual bool HeaderIsListOf (int id)
virtual void Init ()
virtual void OnInit ()
virtual void OnAfterInit ()
virtual void ApplySkin ()
void ShowScreenLock (string id)
void UpdateInput ()
virtual void OnUpdateInput ()
virtual void OnRightClick ()
virtual bool OnBack ()
virtual void OnChangeLayer ()
virtual void OnCreate ()
void _AddLayer (string id)
Layer AddLayer (string id)
T AddLayer< T > ()
T AddLayer< T > (string id)
T AddLayerDontCloseOthers< T > ()
Layer AddLayerDontCloseOthers (Layer l)
T GetOrAddLayer< T > ()
virtual void OnBeforeAddLayer ()
virtual void OnAfterAddLayer ()
Layer AddLayer (Layer l)
void ToggleLayer (string id)
T ToggleLayer< T > (string id=null)
void WaitAndClose ()
void OnClickClose ()
virtual void Close ()
void CloseLayers ()
void RemoveLayers (bool removeImportant=false)
bool RemoveLayer< T > ()
void RemoveLayer (Layer l)
virtual void OnKill ()
Layer SetOnKill (Action action)
void DisableClose ()
void Delay (float duration=0.05f)
Layer SetDelay (float d)
Layer GetLayer (string id)
T GetLayer< T > (bool fromTop=false)
Layer GetTopLayer ()
void SwitchContent (int idWindow, int i)
virtual void OnSwitchContent (Window window)
Layer SetTitles (string langList, string idHeaderRow=null)
bool IsBlockWidgetClick ()
bool IsHideHud ()
bool IsAllowGeneralInput ()
bool IsUseBlur ()
bool IsPointerOnLayer ()
void ApplySkin ()
Public Attributes
Vector2 startPos
float time
float bgAlpha
float startDelay
Slot slotVoid
List< Slot > slots
UIItem moldItem
LayoutGroup layout
Action< Religion > onWorship
bool isBranchFaith
int index
List< UIItem > items = new List<UIItem>()
List< UIItem > orders = new List<UIItem>()
Public Attributes inherited from Layer
Option option
UnityEvent onKill
Anime animeIn
Anime animeOut
bool closeOthers
bool defaultActionMode = true
Button screenLock
Layer parent
string idLayer
List< Layer > layers = new List<Layer>()
Vector2 lastParentPos
List< Window > windows = new List<Window>()
string langHint
Private Member Functions
void Update ()
Additional Inherited Members
Static Public Member Functions inherited from ELayer
static int rnd (int a)
Static Public Member Functions inherited from Layer
static T Create< T > ()
static T Create< T > (string path)
static Layer Create (string path)
Static Public Attributes inherited from Layer
static int skipInput
static bool closeOnRightClick
static bool rightClicked
static bool cancelKeyDown
static bool ignoreSounds
static Transform blurStopInstance
static string[] searchPath = new string[3] { "Layer", "Layer/Dialog", "Layer/LayerHome" }
Protected Member Functions inherited from ELayer
sealed override void _Close ()
sealed override void Kill ()
Protected Member Functions inherited from Layer
virtual void Awake ()
virtual void _Close ()
virtual void Kill ()
Protected Attributes inherited from Layer
RectTransform _rect
bool isDestroyed
Properties inherited from ELayer
static Core core [get]
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static FactionBranch Branch [get]
static Faction Home [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static CoreConfig config [get]
static GameSetting setting [get]
static ColorProfile Colors [get]
static SourceManager sources [get]
static World world [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
bool IsFloat [get]
virtual string IdHelp [get]
Properties inherited from Layer
Layer TopLayer [get]
string uid [get]
virtual RectTransform rectLayers [get]
virtual bool blockWidgetClick [get]
Detailed Description
Definition at line 7 of file LayerFaith.cs.
Member Function Documentation
Activate()
void LayerFaith.Activate (Religion r, Action< Religion > _onWorship) inline
Definition at line 51 of file LayerFaith.cs.
    {
        onWorship = _onWorship;
        if (r == null)
        {
            foreach (Religion item in ELayer.game.religions.list)
            {
                if (!item.IsMinorGod)
                {
                    AddReligion(item);
                }
            }
            isBranchFaith = true;
        }
        else
        {
            AddReligion(r);
        }
        TweenUtil.Tween(startDelay, RefreshSlots);
        SE.Play("zoomIn");
    }
References AddReligion(), ELayer.game, isBranchFaith, item, ReligionManager.list, onWorship, RefreshSlots(), Game.religions, and startDelay.
AddReligion()
void LayerFaith.AddReligion (Religion r) inline
Definition at line 162 of file LayerFaith.cs.
    {
        UIItem uIItem = Util.Instantiate(moldItem, layout);
        uIItem.text1.SetText(r.source.GetDetail());
        uIItem.text2.SetText(r.Name);
        uIItem.button1.icon.sprite = Resources.Load<Sprite>("Media/Graphics/Image/Faction/" + r.source.id);
        if (isBranchFaith && !r.IsAvailable)
        {
            uIItem.button2.mainText.SetText("faithUnavailable".lang());
        }
        uIItem.refObj = r;
        items.Add(uIItem);
        uIItem.Rect().anchoredPosition = startPos;
    }
References UIItem.button2, Religion.IsAvailable, isBranchFaith, items, layout, UIButton.mainText, moldItem, Religion.Name, UIText.SetText(), Religion.source, startPos, UIItem.text1, UIItem.text2, and Util.
Referenced by Activate().
Move()
void LayerFaith.Move (int a) inline
Definition at line 81 of file LayerFaith.cs.
    {
        index += a;
        if (index >= items.Count)
        {
            index = 0;
        }
        else if (index < 0)
        {
            index = items.Count - 1;
        }
        RefreshSlots();
        SE.Play("zoomOut");
    }
References index, items, and RefreshSlots().
Referenced by RefreshSlots(), and Update().
RefreshSlots()
void LayerFaith.RefreshSlots () inline
Definition at line 96 of file LayerFaith.cs.
    {
        orders.Clear();
        int num = index;
        for (int i = 0; i < items.Count; i++)
        {
            if (num >= items.Count)
            {
                num = 0;
            }
            orders.Add(items[num]);
            num++;
        }
        for (int j = 0; j < items.Count; j++)
        {
            Slot slot = ((j >= slots.Count) ? slotVoid : slots[j]);
            UIItem item = orders[j];
            bool flag = j == 2;
            if (items.Count == 1)
            {
                flag = true;
                slot = slots[2];
            }
            item.button1.icon.raycastTarget = !flag;
            if (j == 1)
            {
                item.button1.SetOnClick(delegate
                {
                    Move(-1);
                });
            }
            if (j == 3)
            {
                item.button1.SetOnClick(delegate
                {
                    Move(1);
                });
            }
            item.button2.SetOnClick(delegate
            {
                Religion religion = item.refObj as Religion;
                if (religion.IsAvailable || !isBranchFaith)
                {
                    Close();
                    onWorship(religion);
                }
                else
                {
                    SE.Beep();
                }
            });
            item.button3.SetOnClick(delegate
            {
                Close();
            });
            item.button2.GetComponent<CanvasGroup>().DOFade(flag ? 1f : 0f, time).SetEase(slot.ease);
            item.button3.GetComponent<CanvasGroup>().DOFade(flag ? 1f : 0f, time).SetEase(slot.ease);
            item.text1.DOFade(flag ? 1f : 0f, time).SetEase(slot.ease);
            item.text3.DOFade(flag ? 1f : 0f, time).SetEase(slot.ease);
            item.image2.DOFade(flag ? bgAlpha : 0f, time).SetEase(slot.ease);
            item.Rect().DOAnchorPos(slot.position, time).SetEase(slot.ease);
            item.Rect().DOScale(slot.scale, time).SetEase(slot.ease);
            item.GetComponent<CanvasGroup>().DOFade(slot.alpha, time).SetEase(slot.ease);
        }
    }
References LayerFaith.Slot.alpha, bgAlpha, Layer.Close(), LayerFaith.Slot.ease, index, isBranchFaith, item, items, Move(), onWorship, orders, LayerFaith.Slot.position, religion, LayerFaith.Slot.scale, slots, slotVoid, and time.
Referenced by Activate(), and Move().
Update()
void LayerFaith.Update () inline private
Definition at line 73 of file LayerFaith.cs.
    {
        if (EInput.wheel != 0)
        {
            Move((EInput.wheel > 0) ? 1 : (-1));
        }
    }
References Move(), and EInput.wheel.
Member Data Documentation
bgAlpha
float LayerFaith.bgAlpha
Definition at line 25 of file LayerFaith.cs.
Referenced by RefreshSlots().
index
int LayerFaith.index
Definition at line 43 of file LayerFaith.cs.
Referenced by Move(), and RefreshSlots().
isBranchFaith
bool LayerFaith.isBranchFaith
Definition at line 40 of file LayerFaith.cs.
Referenced by Activate(), AddReligion(), and RefreshSlots().
items
List<UIItem> LayerFaith.items = new List<UIItem>()
Definition at line 46 of file LayerFaith.cs.
Referenced by AddReligion(), Move(), and RefreshSlots().
layout
LayoutGroup LayerFaith.layout
Definition at line 35 of file LayerFaith.cs.
Referenced by AddReligion().
moldItem
UIItem LayerFaith.moldItem
Definition at line 33 of file LayerFaith.cs.
Referenced by AddReligion().
onWorship
Action<Religion> LayerFaith.onWorship
Definition at line 37 of file LayerFaith.cs.
Referenced by Activate(), and RefreshSlots().
orders
List<UIItem> LayerFaith.orders = new List<UIItem>()
Definition at line 49 of file LayerFaith.cs.
Referenced by RefreshSlots().
slots
List<Slot> LayerFaith.slots
Definition at line 31 of file LayerFaith.cs.
Referenced by RefreshSlots().
slotVoid
Slot LayerFaith.slotVoid
Definition at line 29 of file LayerFaith.cs.
Referenced by RefreshSlots().
startDelay
float LayerFaith.startDelay
Definition at line 27 of file LayerFaith.cs.
Referenced by Activate().
startPos
Vector2 LayerFaith.startPos
Definition at line 21 of file LayerFaith.cs.
Referenced by AddReligion().
time
float LayerFaith.time
Definition at line 23 of file LayerFaith.cs.
Referenced by RefreshSlots().
The documentation for this class was generated from the following file:
Elin/LayerFaith.cs