Elin Decompiled Documentation: WidgetDebug Class Reference
WidgetDebug Class Reference
Public Member Functions
override void OnActivate ()
void Refresh ()
void ToggleProps ()
void ToggleUpdates ()
void ToggleOther ()
Public Member Functions inherited from Widget
void Test ()
bool IsInRightMode ()
void Activate ()
virtual void OnActivate ()
virtual object CreateExtra ()
void Deactivate ()
virtual void OnDeactivate ()
void Close ()
void Reactivate ()
virtual void OnManagerActivate ()
virtual void OnManagerDeactivate ()
void SetAnchor (RectPosition p)
void SetPivot (RectPosition p)
virtual void OnChangePivot ()
void UpdateConfig ()
virtual void OnUpdateConfig ()
void ClampToScreen ()
virtual void OnChangeResolution ()
void OnChangePosition ()
virtual void OnChangeActionMode ()
virtual void OnFlip ()
bool IsAlignTop ()
Layer AddLayer (Layer l, Transform trans)
void RefreshTipPivotPosition ()
SkinSet GetSkin ()
SkinConfig GetSkinConfig ()
void SetSkin (int id, int v=0)
void TestSkin ()
virtual void ApplySkin ()
virtual void OnApplySkin ()
void InstantiateDeco (SkinDeco deco)
void AddDeco (SkinDeco deco)
void RemoveDeco (SkinDeco deco)
virtual bool CanShowContextMenu ()
void ShowContextMenu ()
void SetBaseContextMenu (UIContextMenu m)
virtual void OnSetContextMenu (UIContextMenu m)
void SetGridContextMenu (UIContextMenu m)
void SoundActivate ()
Public Attributes
Text debugText
Text textFPS
bool showUpdates
bool showProps
bool showOther
Public Attributes inherited from Widget
Image imageBG
SoundData soundActivate
UIDragPanel dragPanel
RectTransform tipPivotLeft
RectTransform tipPivotRight
Static Public Attributes
static string output
Static Public Attributes inherited from EMono
static Core core
Private Member Functions
void OnEnable ()
void OnDisable ()
void UpdateText ()
Private Attributes
Timer.TimerItem timer
float deltaTime
int lastPathCount
Additional Inherited Members
Public Types inherited from Widget
enum WidgetType { Default , ZoomMenu }
enum State { Active , Inactive }
Static Public Member Functions inherited from EMono
static int rnd (int a)
Protected Member Functions inherited from Widget
void ClampToScreenEnsured (Component c, Vector2 anchoredPos)
void ClampToScreen (RectTransform rect, float margin=10f)
Protected Attributes inherited from Widget
bool flip
Properties inherited from Widget
string ID [get]
Widget.Config config [get]
SkinRoot skinRoot [get]
bool IsSealed [get]
virtual bool ShowStyleMenu [get]
virtual bool AlwaysTop [get]
virtual bool IsStaticPosition [get]
virtual bool AlwaysBottom [get]
virtual Type SetSiblingAfter [get]
virtual bool ShowInBuildMode [get]
virtual bool RightClickToClose [get]
virtual bool AllowRightClickToClose [get]
Properties inherited from EMono
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SoundManager Sound [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static CoreDebug debug [get]
Detailed Description
Definition at line 5 of file WidgetDebug.cs.
Member Function Documentation
OnActivate()
override void WidgetDebug.OnActivate () inline virtual
Reimplemented from Widget.
Definition at line 7 of file WidgetDebug.cs.
    {
        this.UpdateText();
    }
References UpdateText().
OnDisable()
void WidgetDebug.OnDisable () inline private
Definition at line 20 of file WidgetDebug.cs.
    {
        if (this.timer != null)
        {
            this.timer.Cancel();
        }
    }
References timer.
OnEnable()
void WidgetDebug.OnEnable () inline private
Definition at line 12 of file WidgetDebug.cs.
    {
        if (Timer.current)
        {
            this.timer = Timer.Start(0.1f, new Action(this.UpdateText), true);
        }
    }
References UpdateText().
Refresh()
void WidgetDebug.Refresh () inline
Definition at line 28 of file WidgetDebug.cs.
    {
    }
ToggleOther()
void WidgetDebug.ToggleOther () inline
Definition at line 42 of file WidgetDebug.cs.
    {
        this.showOther = !this.showOther;
    }
References showOther.
ToggleProps()
void WidgetDebug.ToggleProps () inline
Definition at line 32 of file WidgetDebug.cs.
    {
        this.showProps = !this.showProps;
    }
References showProps.
ToggleUpdates()
void WidgetDebug.ToggleUpdates () inline
Definition at line 37 of file WidgetDebug.cs.
    {
        this.showUpdates = !this.showUpdates;
    }
References showUpdates.
UpdateText()
void WidgetDebug.UpdateText () inline private
Definition at line 47 of file WidgetDebug.cs.
    {
        this.deltaTime += (Time.unscaledDeltaTime - this.deltaTime) * 0.1f;
        float num = this.deltaTime * 1000f;
        float num2 = 1f / this.deltaTime;
        string text = string.Format("{0:0.0} ms ({1:0.} fps)", num, num2);
        this.textFPS.text = text + " avg delta: " + Core.avgDelta.ToString();
        if (EMono.game == null || EMono.game.activeZone == null)
        {
            this.debugText.text = "";
            return;
        }
        IPathfinder pathfinder = EMono.core.pathManager.pathfinder;
        BaseTileMap tileMap = EMono.screen.tileMap;
        PropsManager props = EMono._map.props;
        int num3 = PathManager.requestCount - this.lastPathCount;
        this.lastPathCount = PathManager.requestCount;
        Point hitPoint = Scene.HitPoint;
        text = "";
        if (this.showOther)
        {
            text += WidgetDebug.output;
            string[] array = new string[5];
            array[0] = text;
            int num4 = 1;
            AIAct ai = EMono.pc.ai;
            array[num4] = ((ai != null) ? ai.ToString() : null);
            array[2] = "/";
            array[3] = EMono.pc.ai.status.ToString();
            array[4] = "\n";
            text = string.Concat(array);
            text = string.Concat(new string[]
            {
                text,
                "time: ",
                EMono.scene.timeRatio.ToString(),
                " turn:",
                EMono.pc.turn.ToString(),
                " "
            });
            Vector3 mposWorld = EInput.mposWorld;
            if (tileMap != null)
            {
                string[] array2 = new string[8];
                array2[0] = text;
                array2[1] = "mouse: ";
                array2[2] = tileMap.mx.ToString();
                array2[3] = "/";
                array2[4] = tileMap.mz.ToString();
                array2[5] = "   hit: ";
                int num5 = 6;
                Point point = hitPoint;
                array2[num5] = ((point != null) ? point.ToString() : null);
                array2[7] = "\n";
                text = string.Concat(array2);
                if (EMono._zone.IsRegion)
                {
                    Point point2 = hitPoint.Copy();
                    point2.x += EMono.scene.elomapActor.elomap.minX;
                    point2.z += EMono.scene.elomapActor.elomap.minY;
                    string[] array3 = new string[8];
                    array3[0] = text;
                    array3[1] = "mouse: ";
                    array3[2] = (tileMap.mx + EMono.scene.elomapActor.elomap.minX).ToString();
                    array3[3] = "/";
                    array3[4] = (tileMap.mz + EMono.scene.elomapActor.elomap.minY).ToString();
                    array3[5] = "   hit: ";
                    int num6 = 6;
                    Point point3 = point2;
                    array3[num6] = ((point3 != null) ? point3.ToString() : null);
                    array3[7] = "\n";
                    text = string.Concat(array3);
                }
            }
            CharaActorPCC charaActorPCC = EMono.pc.renderer.actor as CharaActorPCC;
            float num7 = (charaActorPCC != null) ? charaActorPCC.provider.angle : 0f;
            text = string.Concat(new string[]
            {
                text,
                "path:",
                num3.ToString(),
                "/",
                PathManager.requestCount.ToString(),
                "/",
                PathManager.Instance._pathfinder.total.ToString(),
                " syncList:",
                EMono.scene.syncList.Count.ToString(),
                "\n"
            });
            text = string.Concat(new string[]
            {
                text,
                "events:",
                EMono._zone.events.list.Count.ToString(),
                "  roundTimer:",
                EMono.pc.roundTimer.ToString(),
                "  seed:",
                EMono._map.seed.ToString(),
                "\n"
            });
            text = string.Concat(new string[]
            {
                text,
                "details:",
                CellDetail.count.ToString(),
                "(",
                CellDetail.cache.Count.ToString(),
                "  pointAnimes:",
                EMono._map.pointAnimes.Count.ToString(),
                ") pccCache:",
                PCCManager.current.pccCache.Count.ToString(),
                "\n"
            });
            if (hitPoint.IsValid)
            {
                string[] array4 = new string[12];
                array4[0] = text;
                array4[1] = "GatAngle: ";
                array4[2] = Util.GetAngle((float)(hitPoint.x - EMono.pc.pos.x), (float)(hitPoint.z - EMono.pc.pos.z)).ToString();
                array4[3] = "  dir: ";
                array4[4] = EMono.pc.dir.ToString();
                array4[5] = "  actor dir: ";
                int num8 = 6;
                CardActor actor = EMono.pc.renderer.actor;
                array4[num8] = ((actor != null) ? new int?(actor.currentDir) : null).ToString();
                array4[7] = "  angle:";
                array4[8] = EMono.pc.angle.ToString();
                array4[9] = "/";
                array4[10] = num7.ToString();
                array4[11] = "\n";
                text = string.Concat(array4);
                string[] array5 = new string[7];
                array5[0] = text;
                array5[1] = "room: ";
                int num9 = 2;
                Room room = hitPoint.cell.room;
                array5[num9] = ((room != null) ? room.ToString() : null);
                array5[3] = " objVal:";
                array5[4] = hitPoint.cell.objVal.ToString();
                array5[5] = " ";
                array5[6] = hitPoint.cell.CanGrow(hitPoint.cell.sourceObj, new VirtualDate(1)).ToString();
                text = string.Concat(array5);
            }
        }
        if (this.showUpdates)
        {
            text += EMono.game.updater.GetText();
            text += "\n";
        }
        if (this.showProps)
        {
            text = text + "roaming: " + props.roaming.Count.ToString() + "\n";
            text = text + "installed: " + props.installed.Count.ToString() + "\n";
            text = text + "charas: " + EMono._map.charas.Count.ToString() + "\n";
            text = text + "global charas: " + EMono.game.cards.globalCharas.Count.ToString() + "\n";
            text += "\n";
        }
        if (hitPoint.IsValid && hitPoint.FirstChara != null)
        {
            text += "\n";
            Chara firstChara = hitPoint.FirstChara;
            text = string.Concat(new string[]
            {
                text,
                firstChara.id,
                " uid:",
                firstChara.uid.ToString(),
                " skin:",
                firstChara.idSkin.ToString(),
                " dir:",
                firstChara.dir.ToString()
            });
        }
        this.debugText.text = text;
    }
References EMono._map, PathManager._pathfinder, EMono._zone, Game.activeZone, CardRenderer.actor, Chara.ai, Card.angle, CellDetail.cache, Cell.CanGrow(), Point.cell, Point.Copy(), EMono.core, CellDetail.count, CardActor.currentDir, deltaTime, Card.dir, EloMapActor.elomap, Scene.elomapActor, Zone.events, EMono.game, Scene.HitPoint, PathManager.Instance, Spatial.IsRegion, Point.IsValid, lastPathCount, ZoneEventManager.list, EloMap.minX, EloMap.minY, BaseTileMap.mx, BaseTileMap.mz, Cell.objVal, output, EMono.pc, Map.pointAnimes, Card.pos, Map.props, CharaActorPCC.provider, Card.renderer, PathManager.requestCount, Cell.room, Card.roundTimer, EMono.scene, EMono.screen, Map.seed, showOther, Cell.sourceObj, AIAct.status, Scene.syncList, text, BaseGameScreen.tileMap, Scene.timeRatio, AIAct.ToString(), Point.ToString(), Room.ToString(), Card.turn, Point.x, and Point.z.
Referenced by OnActivate(), and OnEnable().
Member Data Documentation
debugText
Text WidgetDebug.debugText
Definition at line 225 of file WidgetDebug.cs.
deltaTime
float WidgetDebug.deltaTime private
Definition at line 237 of file WidgetDebug.cs.
Referenced by UpdateText().
lastPathCount
int WidgetDebug.lastPathCount private
Definition at line 239 of file WidgetDebug.cs.
Referenced by UpdateText().
output
string WidgetDebug.output static
Definition at line 223 of file WidgetDebug.cs.
Referenced by UpdateText().
showOther
bool WidgetDebug.showOther
Definition at line 233 of file WidgetDebug.cs.
Referenced by ToggleOther(), and UpdateText().
showProps
bool WidgetDebug.showProps
Definition at line 231 of file WidgetDebug.cs.
Referenced by ToggleProps().
showUpdates
bool WidgetDebug.showUpdates
Definition at line 229 of file WidgetDebug.cs.
Referenced by ToggleUpdates().
textFPS
Text WidgetDebug.textFPS
Definition at line 227 of file WidgetDebug.cs.
timer
Timer.TimerItem WidgetDebug.timer private
Definition at line 235 of file WidgetDebug.cs.
Referenced by OnDisable().
The documentation for this class was generated from the following file:
Elin/WidgetDebug.cs