Elin Decompiled Documentation: ZoneEventSiege Class Reference
ZoneEventSiege Class Reference
Public Member Functions
virtual Chara CreateChara (Point p)
override void OnInit ()
override void OnVisit ()
void SpawnMob ()
virtual Point GetSpawnPos ()
override void OnTickRound ()
override void OnCharaDie (Chara c)
bool ShouldEnd ()
override void OnKill ()
Public Member Functions inherited from ZoneEvent
virtual string GetText ()
void Tick (float delta)
void Init ()
void OnSimulateHour ()
virtual void OnVisit ()
virtual void OnInit ()
virtual void OnFirstTick ()
virtual void OnTick ()
virtual void OnTickRound ()
virtual void OnKill ()
virtual void OnCharaDie (Chara c)
virtual void OnLeaveZone ()
virtual void OnLoad ()
void Kill ()
Public Attributes
List< int > uids = new List<int>()
int lv = 10
int idx
int max = 10
List< Chara > members = new List<Chara>()
Public Attributes inherited from ZoneEvent
float time
int rounds
int hoursElapsed
int minElapsed
Zone zone
bool firstTick = true
Properties
override string id [get]
override float roundInterval [get]
override Playlist playlist [get]
Properties inherited from ZoneEvent
SourceQuest.Row source [get]
virtual string id [get]
virtual string TextWidgetDate [get]
virtual float roundInterval [get]
virtual Playlist playlist [get]
virtual bool debugSkip [get]
virtual string RefStr2 [get]
virtual string RefStr3 [get]
virtual int hoursToKill [get]
virtual bool HasReport [get]
string Name [get]
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Additional Inherited Members
Static Public Member Functions inherited from EClass
static int rndSeed (int a, int seed)
static int rnd (long a)
static int rnd (int a)
static int curve (int a, int start, int step, int rate=75)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Static Public Attributes inherited from EClass
static Core core
Detailed Description
Definition at line 5 of file ZoneEventSiege.cs.
Member Function Documentation
CreateChara()
virtual Chara ZoneEventSiege.CreateChara (Point p) inline virtual
Definition at line 27 of file ZoneEventSiege.cs.
    {
        bool flag = idx == max - 1;
        int num;
        object obj;
        if (lv >= 50)
        {
            num = ((idx == max - 2) ? 1 : 0);
            if (num != 0)
            {
                obj = SpawnSetting.Evolved(lv);
                goto IL_005a;
            }
        }
        else
        {
            num = 0;
        }
        obj = (flag ? SpawnSetting.Boss(lv) : SpawnSetting.DefenseEnemy(lv));
        goto IL_005a;
        IL_005a:
        SpawnSetting spawnSetting = (SpawnSetting)obj;
        spawnSetting.dangerLv = lv + 1;
        if (num == 0)
        {
            return EClass._zone.SpawnMob(p, spawnSetting);
        }
        return EClass._zone.TryGenerateEvolved(force: true, p);
    }
References EClass._zone, SpawnSetting.Boss(), SpawnSetting.DefenseEnemy(), SpawnSetting.Evolved(), idx, lv, max, Zone.SpawnMob(), and Zone.TryGenerateEvolved().
Referenced by SpawnMob().
GetSpawnPos()
virtual Point ZoneEventSiege.GetSpawnPos () inline virtual
Reimplemented in ZoneEventRaid.
Definition at line 92 of file ZoneEventSiege.cs.
    {
        return EClass._map.GetRandomEdge();
    }
References EClass._map, and Map.GetRandomEdge().
Referenced by OnKill(), and SpawnMob().
OnCharaDie()
override void ZoneEventSiege.OnCharaDie (Chara c) inline virtual
Reimplemented from ZoneEvent.
Definition at line 109 of file ZoneEventSiege.cs.
    {
        if (ShouldEnd())
        {
            Kill();
        }
    }
References ZoneEvent.Kill(), and ShouldEnd().
OnInit()
override void ZoneEventSiege.OnInit () inline virtual
Reimplemented from ZoneEvent.
Definition at line 57 of file ZoneEventSiege.cs.
    {
        EClass.player.stats.sieges++;
        Msg.Say("startSiege");
        EClass._zone.RefreshBGM();
    }
References EClass._zone, EClass.player, Zone.RefreshBGM(), Msg.Say(), Player.Stats.sieges, and Player.stats.
OnKill()
override void ZoneEventSiege.OnKill () inline virtual
Reimplemented from ZoneEvent.
Definition at line 134 of file ZoneEventSiege.cs.
    {
        Msg.Say("endSiege");
        SE.Play("kill_boss");
        EClass._zone.RefreshBGM();
        EClass._zone.AddCard(ThingGen.CreateTreasure("chest_boss", lv, TreasureType.SurvivalRaid), GetSpawnPos().GetNearestPoint(allowBlock: false, allowChara: false, allowInstalled: false, ignoreCenter: true) ?? EClass.pc.pos).Install();
    }
References EClass._zone, Zone.AddCard(), ThingGen.CreateTreasure(), GetSpawnPos(), Card.Install(), lv, EClass.pc, Card.pos, Zone.RefreshBGM(), and Msg.Say().
OnTickRound()
override void ZoneEventSiege.OnTickRound () inline virtual
Reimplemented from ZoneEvent.
Definition at line 97 of file ZoneEventSiege.cs.
    {
        if (idx < max)
        {
            SpawnMob();
        }
        if (ShouldEnd())
        {
            Kill();
        }
    }
References idx, ZoneEvent.Kill(), max, ShouldEnd(), and SpawnMob().
OnVisit()
override void ZoneEventSiege.OnVisit () inline virtual
Reimplemented from ZoneEvent.
Definition at line 64 of file ZoneEventSiege.cs.
    {
        EClass._zone.RefreshBGM();
        members.Clear();
        foreach (int uid in uids)
        {
            foreach (Chara chara in EClass._map.charas)
            {
                if (chara.uid == uid)
                {
                    members.Add(chara);
                }
            }
        }
    }
References EClass._map, EClass._zone, Map.charas, members, Zone.RefreshBGM(), Card.uid, and uids.
ShouldEnd()
bool ZoneEventSiege.ShouldEnd () inline
Definition at line 117 of file ZoneEventSiege.cs.
    {
        bool result = idx >= max;
        foreach (Chara member in members)
        {
            if (!member.IsPCFactionOrMinion && member.IsAliveInCurrentZone)
            {
                if (member.ai is GoalIdle)
                {
                    member.SetAI(new GoalSiege());
                }
                result = false;
            }
        }
        return result;
    }
References Chara.ai, idx, Chara.IsAliveInCurrentZone, Card.IsPCFactionOrMinion, max, members, and Chara.SetAI().
Referenced by OnCharaDie(), and OnTickRound().
SpawnMob()
void ZoneEventSiege.SpawnMob () inline
Definition at line 80 of file ZoneEventSiege.cs.
    {
        Point spawnPos = GetSpawnPos();
        Chara chara = CreateChara(spawnPos);
        chara.hostility = Hostility.Enemy;
        members.Add(chara);
        uids.Add(chara.uid);
        chara.PlayEffect("teleport");
        chara.PlaySound("spell_funnel");
        idx++;
    }
References CreateChara(), GetSpawnPos(), idx, members, Card.PlayEffect(), Card.PlaySound(), Card.uid, and uids.
Referenced by OnTickRound().
Member Data Documentation
idx
int ZoneEventSiege.idx
Definition at line 14 of file ZoneEventSiege.cs.
Referenced by CreateChara(), OnTickRound(), ShouldEnd(), and SpawnMob().
lv
int ZoneEventSiege.lv = 10
Definition at line 11 of file ZoneEventSiege.cs.
Referenced by CreateChara(), ZoneEventRaid.OnInit(), and OnKill().
max
int ZoneEventSiege.max = 10
Definition at line 17 of file ZoneEventSiege.cs.
Referenced by CreateChara(), ZoneEventRaid.OnInit(), OnTickRound(), and ShouldEnd().
members
List<Chara> ZoneEventSiege.members = new List<Chara>()
Definition at line 19 of file ZoneEventSiege.cs.
Referenced by OnVisit(), ShouldEnd(), and SpawnMob().
uids
List<int> ZoneEventSiege.uids = new List<int>()
Definition at line 8 of file ZoneEventSiege.cs.
Referenced by OnVisit(), and SpawnMob().
Property Documentation
id
override string ZoneEventSiege.id get
Definition at line 21 of file ZoneEventSiege.cs.
playlist
override Playlist ZoneEventSiege.playlist get
Definition at line 25 of file ZoneEventSiege.cs.
roundInterval
override float ZoneEventSiege.roundInterval get
Definition at line 23 of file ZoneEventSiege.cs.
The documentation for this class was generated from the following file:
Elin/ZoneEventSiege.cs