Elin Decompiled Documentation: ZoneInstanceBout Class Reference
ZoneInstanceBout Class Reference
Public Member Functions
override void OnLeaveZone ()
Public Member Functions inherited from ZoneInstance
virtual void OnGenerateMap ()
virtual void OnLeaveZone ()
Public Attributes
int uidTarget
int targetX
int targetZ
Public Attributes inherited from ZoneInstance
int uidZone
int x
int z
Status status
Properties
override ZoneTransition.EnterState ReturnState [get]
Properties inherited from ZoneInstance
Zone ReturnZone [get]
virtual ZoneTransition.EnterState ReturnState [get]
virtual bool WarnExit [get]
virtual bool ShowEnemyOnMinimap [get]
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Additional Inherited Members
Public Types inherited from ZoneInstance
enum Status { Running , Fail , Success }
Static Public Member Functions inherited from EClass
static int rnd (int a)
static int curve (int a, int start, int step, int rate=75)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Static Public Attributes inherited from EClass
static Core core
Detailed Description
Definition at line 3 of file ZoneInstanceBout.cs.
Member Function Documentation
OnLeaveZone()
override void ZoneInstanceBout.OnLeaveZone () inline virtual
Reimplemented from ZoneInstance.
Definition at line 16 of file ZoneInstanceBout.cs.
    {
        Chara chara = EClass.game.cards.Find(uidTarget);
        if (chara != null)
        {
            if (chara.isDead)
            {
                chara.Revive();
            }
            chara.HealAll();
            Hostility c_originalHostility = (chara.hostility = Hostility.Friend);
            chara.c_originalHostility = c_originalHostility;
            chara.SetEnemy();
            chara.SetAI(new NoGoal());
            chara.MoveZone(EClass.game.spatials.Find(uidZone), new ZoneTransition
            {
                state = ZoneTransition.EnterState.Exact,
                x = targetX,
                z = targetZ
            });
        }
    }
References Game.cards, CardManager.Find(), SpatialManager.Find(), EClass.game, Chara.HealAll(), Chara.isDead, Chara.MoveZone(), Chara.Revive(), Chara.SetAI(), Chara.SetEnemy(), Game.spatials, targetX, targetZ, uidTarget, ZoneInstance.uidZone, ZoneInstance.x, and ZoneInstance.z.
Member Data Documentation
targetX
int ZoneInstanceBout.targetX
Definition at line 9 of file ZoneInstanceBout.cs.
Referenced by OnLeaveZone().
targetZ
int ZoneInstanceBout.targetZ
Definition at line 12 of file ZoneInstanceBout.cs.
Referenced by OnLeaveZone().
uidTarget
int ZoneInstanceBout.uidTarget
Definition at line 6 of file ZoneInstanceBout.cs.
Referenced by Card.DamageHP(), and OnLeaveZone().
Property Documentation
ReturnState
override ZoneTransition.EnterState ZoneInstanceBout.ReturnState get
Definition at line 14 of file ZoneInstanceBout.cs.
The documentation for this class was generated from the following file:
Elin/ZoneInstanceBout.cs