Elin Decompiled Documentation: AM_Copy Class Reference
AM_Copy Class Reference
Public Types
enum Mode { Copy , Place , Create }
Public Member Functions
override string OnSetSubMenuButton (int a, UIButton b)
override void OnClickSubMenu (int a)
override HitResult HitTest (Point point, Point start)
override void OnSelectStart (Point point)
override void OnSelectEnd (bool cancel)
override void OnAfterProcessTiles (Point start, Point end)
virtual void OnSave (PartialMap _partial)
override void OnRenderTile (Point point, HitResult result, int dir)
override void OnUpdateInput ()
override void RotateUnderMouse ()
void Clear ()
override void OnCancel ()
void Import (string path)
void ImportDialog (string dir=null)
void RefreshMenu (bool show)
override void OnActivate ()
override void OnDeactivate ()
Public Member Functions inherited from ActionMode
virtual int TopHeight (Point p)
virtual void SEExecuteSummary ()
virtual bool HighlightWall (Point p)
virtual void OnClickSubMenu (int a)
virtual string OnSetSubMenuButton (int a, UIButton b)
virtual bool IsRoofEditMode (Card c=null)
virtual bool IsFillMode ()
virtual int GetDefaultTile (Point p)
virtual void OnShowExtraHint (UINote n)
void Activate (bool toggle=true, bool forceActivate=false)
virtual void OnActivate ()
void RefreshTexts ()
virtual string GetSimpleText (Card c)
void ClearSimpleTexts ()
void Deactivate ()
virtual void OnDeactivate ()
virtual void OnCancel ()
virtual void OnBeforeUpdate ()
virtual void OnAfterUpdate ()
virtual void OnUpdateCursor ()
void OnRotate ()
void SetCursorOnMap (CursorInfo cursor)
void UpdateInput ()
void InputMovement ()
virtual void InputWheel (int wheel)
virtual void OnUpdateInput ()
void DoFunc (CoreConfig.GameFuncBuild func)
bool IsFuncPressed (CoreConfig.GameFunc func)
void DoFunc (CoreConfig.GameFunc func)
virtual void OnScroll ()
void TryRightClickCloseWidget ()
bool TryShowWidgetMenu ()
HitResult _HitTest (Point point, Point start)
virtual HitResult HitTest (Point point, Point start)
virtual void OnSelectStart (Point point)
virtual void OnSelectEnd (bool cancel)
virtual MeshPass GetGuidePass (Point point)
virtual void OnRenderTile (Point point, HitResult result, int dir)
void OnRenderTileFloor (Point point, HitResult result)
virtual bool CanProcessTiles ()
virtual void OnBeforeProcessTiles ()
virtual void OnProcessTiles (Point point, int dir)
virtual void OnAfterProcessTiles (Point start, Point end)
virtual void OnFinishProcessTiles ()
virtual void OnRefreshSummary (Point point, HitResult result, HitSummary summary)
void ShowLayer ()
virtual Layer OnShowLayer ()
void HideLayer ()
virtual void OnHideLayer ()
virtual string GetHintText ()
virtual void RotateUnderMouse ()
virtual ref string SetMouseInfo (ref string s)
void TogglePause ()
void Pause (bool sound=false)
void UnPause (bool sound=false)
void ChangeGameSpeed (int a, bool sound=false)
Public Attributes
string overwritePath
PartialMap partialMap
DirectoryInfo dir
DirectoryInfo dirUser
Public Attributes inherited from ActionMode
Layer layer
int brushRadius = 4
Properties
override BaseTileSelector.SelectType selectType [get]
override bool IsBuildMode [get]
override BuildMenu.Mode buildMenuMode [get]
override bool UseSubMenu [get]
override bool SubMenuAsGroup [get]
virtual Mode mode [get]
PartialMapMenu menu [get]
override int CostMoney [get]
Properties inherited from AM_BaseTileSelect
override CursorInfo DefaultCursor [get]
override bool enableMouseInfo [get]
override bool ShowMouseoverTarget [get]
override bool CanSelectTile [get]
override AreaHighlightMode AreaHihlight [get]
TaskManager.Designations Designations [get]
override string idSound [get]
override bool AllowMiddleClickFunc [get]
override bool ShowMaskedThings [get]
Properties inherited from ActionMode
static AM_Adv AdvOrRegion [get]
static bool IsAdv [get]
virtual float gameSpeed [get]
bool IsActive [get]
virtual BaseTileSelector.HitType hitType [get]
virtual BaseTileSelector.SelectType selectType [get]
virtual BaseTileSelector.BoxType boxType [get]
virtual bool ContinuousClick [get]
virtual int hitW [get]
virtual int hitH [get]
HitSummary Summary [get]
bool Multisize [get]
virtual string id [get]
virtual CursorInfo DefaultCursor [get]
virtual string idHelpTopic [get]
virtual string idSound [get]
virtual bool enableMouseInfo [get]
virtual bool hideBalloon [get]
virtual string textHintTitle [get]
virtual bool AllowAutoClick [get]
virtual bool ShowActionHint [get]
virtual bool ShowMouseoverTarget [get]
virtual AreaHighlightMode AreaHihlight [get]
virtual bool CanSelectTile [get]
virtual bool CanTargetOutsideBounds [get]
virtual bool ShouldPauseGame [get]
virtual bool FixFocus [get]
virtual bool HideSubWidgets [get]
virtual bool IsBuildMode [get]
virtual bool ShowBuildWidgets [get]
virtual BuildMenu.Mode buildMenuMode [get]
virtual bool ShouldHideBuildMenu [get]
virtual bool CanTargetFog [get]
virtual int CostMoney [get]
virtual bool AllowBuildModeShortcuts [get]
virtual bool AllowMiddleClickFunc [get]
virtual bool AllowHotbar [get]
virtual bool AllowGeneralInput [get]
virtual bool ShowMaskedThings [get]
virtual int SelectorHeight [get]
virtual bool AllowWheelZoom [get]
virtual float TargetZoom [get]
virtual BaseTileMap.CardIconMode cardIconMode [get]
virtual BaseGameScreen TargetGameScreen [get]
virtual bool IsNoMap [get]
virtual bool UseSubMenu [get]
virtual bool UseSubMenuSlider [get]
virtual bool SubMenuAsGroup [get]
virtual int SubMenuModeIndex [get]
virtual bool ShowExtraHint [get]
BaseTileSelector tileSelector [get]
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Additional Inherited Members
Static Public Member Functions inherited from ActionMode
static void OnGameInstantiated ()
Static Public Member Functions inherited from EClass
static int rnd (int a)
static int curve (int a, int start, int step, int rate=75)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Static Public Attributes inherited from ActionMode
static ActionMode DefaultMode
static AM_Title Title = new AM_Title()
static AM_Sim Sim
static AM_ViewZone View
static AM_Adv Adv
static AM_Region Region
static AM_ADV_Target AdvTarget
static AM_EloMap EloMap
static AM_Inspect Inspect
static AM_NoMap NoMap
static AM_MiniGame MiniGame
static AM_NewZone NewZone
static AM_Bird Bird
static AM_Mine Mine
static AM_Dig Dig
static AM_Harvest Harvest
static AM_Cut Cut
static AM_StateEditor StateEditor
static AM_Picker Picker
static AM_Copy Copy
static AM_Blueprint Blueprint
static AM_Build Build
static AM_CreateArea CreateArea
static AM_EditArea EditArea
static AM_ExpandArea ExpandArea
static AM_Deconstruct Deconstruct
static AM_Select Select
static AM_RemoveDesignation RemoveDesignation
static AM_ViewMap ViewMap
static AM_Terrain Terrain
static AM_Populate Populate
static AM_EditMarker EditMarker
static AM_Visibility Visibility
static AM_Cinema Cinema
static AM_Paint Paint
static AM_FlagCell FlagCell
static ActionMode LastBuildMode
static SourceMaterial.Row lastEditorMat
static bool ignoreSound
static float[] GameSpeeds = new float[4] { 0f, 1f, 2f, 5f }
static List< TCSimpleText > simpleTexts = new List<TCSimpleText>()
static float hotElementTimer
Static Public Attributes inherited from EClass
static Core core
Static Protected Attributes inherited from ActionMode
static Vector3 mpos
Detailed Description
Definition at line 5 of file AM_Copy.cs.
Member Enumeration Documentation
Mode
enum AM_Copy.Mode
Enumerator
Copy
Place
Create
Definition at line 7 of file AM_Copy.cs.
    {
        Copy,
        Place,
        Create
    }
Member Function Documentation
Clear()
void AM_Copy.Clear () inline
Definition at line 209 of file AM_Copy.cs.
    {
        partialMap.ClearMarkedCells();
        partialMap = null;
        RefreshMenu(show: true);
    }
References PartialMap.ClearMarkedCells(), partialMap, and RefreshMenu().
Referenced by OnAfterProcessTiles(), OnCancel(), and RefreshMenu().
HitTest()
override HitResult AM_Copy.HitTest (Point point, Point start) inline virtual
Reimplemented from ActionMode.
Definition at line 73 of file AM_Copy.cs.
    {
        if (!base.Summary.CanExecute())
        {
            return HitResult.Invalid;
        }
        if (partialMap == null)
        {
            foreach (Thing thing in point.cell.Things)
            {
                if (!thing.trait.CanCopyInBlueprint)
                {
                    return HitResult.Warning;
                }
            }
        }
        return HitResult.Valid;
    }
References Trait.CanCopyInBlueprint, Point.cell, partialMap, Cell.Things, and Card.trait.
Import()
void AM_Copy.Import (string path) inline
Definition at line 242 of file AM_Copy.cs.
    {
        partialMap = PartialMap.Load(path);
        RefreshMenu(show: false);
    }
References PartialMap.Load(), partialMap, and RefreshMenu().
Referenced by PartialMapMenu.Refresh(), and AM_Blueprint.SetBlueprint().
ImportDialog()
void AM_Copy.ImportDialog (string dir = null) inline
Definition at line 248 of file AM_Copy.cs.
    {
        EClass.core.WaitForEndOfFrame(delegate
        {
            string[] array = StandaloneFileBrowser.OpenFilePanel("Import Map Piece", dir ?? CorePath.MapPieceSaveUser, "mp", multiselect: false);
            if (array.Length != 0)
            {
                Import(array[0]);
            }
        });
    }
References EClass.core, dir, if(), CorePath.MapPieceSaveUser, SFB.StandaloneFileBrowser.OpenFilePanel(), and BaseCore.WaitForEndOfFrame().
Referenced by OnUpdateInput().
OnActivate()
override void AM_Copy.OnActivate () inline virtual
Reimplemented from ActionMode.
Definition at line 297 of file AM_Copy.cs.
    {
        dir = (dirUser = new DirectoryInfo(CorePath.MapPieceSaveUser));
        if (mode == Mode.Copy)
        {
            PartialMapMenu.Activate();
        }
        RefreshMenu(show: true);
    }
References PartialMapMenu.Activate(), dir, dirUser, CorePath.MapPieceSaveUser, mode, and RefreshMenu().
OnAfterProcessTiles()
override void AM_Copy.OnAfterProcessTiles (Point start, Point end) inline virtual
Reimplemented from ActionMode.
Definition at line 105 of file AM_Copy.cs.
    {
        if (partialMap != null)
        {
            EClass.Sound.Play("build_area");
            partialMap.editMode = false;
            partialMap.procedural = true;
            if (MapPiece.IsEditor)
            {
                if (Input.GetKey(KeyCode.LeftShift))
                {
                    partialMap.procedural = true;
                }
                else
                {
                    partialMap.editMode = true;
                }
            }
            partialMap.Apply(end, PartialMap.ApplyMode.Apply);
            return;
        }
        partialMap = new PartialMap
        {
            allowRotate = Application.isEditor
        };
        int x = Mathf.Min(start.x, end.x);
        int z = Mathf.Min(start.z, end.z);
        int w = Mathf.Abs(start.x - end.x) + 1;
        int h = Mathf.Abs(start.z - end.z) + 1;
        partialMap.Save(x, z, w, h);
        if (!overwritePath.IsEmpty())
        {
            File.Copy(PartialMap.PathTemp, overwritePath, overwrite: true);
            SE.Play("camera");
            overwritePath = null;
            partialMap = null;
            RefreshMenu(show: true);
            return;
        }
        partialMap = PartialMap.Load();
        partialMap.localOffsetX = ((end.x > start.x) ? (start.x - end.x) : 0);
        partialMap.localOffsetZ = ((end.z > start.z) ? (start.z - end.z) : 0);
        RefreshMenu(show: false);
        if (mode == Mode.Create)
        {
            UIScreenshot.Create().Activate(partialMap, dir, OnSave);
            Clear();
        }
        else
        {
            SE.Click();
        }
    }
References UIScreenshot.Activate(), PartialMap.Apply(), Clear(), UIScreenshot.Create(), dir, MapPiece.IsEditor, PartialMap.Load(), mode, OnSave(), overwritePath, partialMap, PartialMap.PathTemp, RefreshMenu(), PartialMap.Save(), EClass.Sound, Point.x, and Point.z.
OnCancel()
override void AM_Copy.OnCancel () inline virtual
Reimplemented from ActionMode.
Definition at line 216 of file AM_Copy.cs.
    {
        if (!overwritePath.IsEmpty())
        {
            overwritePath = null;
            SE.Play("actionMode");
            RefreshMenu(show: true);
        }
        else if (mode == Mode.Place)
        {
            Deactivate();
        }
        else if (!UIScreenshot.Instance)
        {
            if (partialMap != null)
            {
                Clear();
                SE.Play("actionMode");
            }
            else
            {
                Deactivate();
            }
        }
    }
References Clear(), ActionMode.Deactivate(), UIScreenshot.Instance, mode, overwritePath, partialMap, and RefreshMenu().
OnClickSubMenu()
override void AM_Copy.OnClickSubMenu (int a) inline virtual
Reimplemented from ActionMode.
Definition at line 68 of file AM_Copy.cs.
    {
        PartialMap.relative = !PartialMap.relative;
    }
References PartialMap.relative.
OnDeactivate()
override void AM_Copy.OnDeactivate () inline virtual
Reimplemented from ActionMode.
Definition at line 307 of file AM_Copy.cs.
    {
        if (partialMap != null)
        {
            partialMap.ClearMarkedCells();
            partialMap = null;
        }
        if ((bool)menu)
        {
            menu.Deactivate();
        }
        if (Application.isEditor)
        {
            MapPiece.initialized = false;
        }
    }
References PartialMap.ClearMarkedCells(), PartialMapMenu.Deactivate(), menu, and partialMap.
OnRenderTile()
override void AM_Copy.OnRenderTile (Point point, HitResult result, int dir) inline virtual
Reimplemented from ActionMode.
Definition at line 170 of file AM_Copy.cs.
    {
        if (!UIScreenshot.Instance)
        {
            if (partialMap != null)
            {
                partialMap.Apply(point, PartialMap.ApplyMode.Render);
            }
            else
            {
                base.OnRenderTile(point, result, dir);
            }
        }
    }
References PartialMap.Apply(), dir, UIScreenshot.Instance, and partialMap.
OnSave()
virtual void AM_Copy.OnSave (PartialMap _partial) inline virtual
Reimplemented in AM_Blueprint.
Definition at line 159 of file AM_Copy.cs.
    {
        if (MapPiece.IsEditor)
        {
            MapPiece.initialized = false;
            menu.RefreshCategory();
        }
        menu.DestorySprites();
        menu.Refresh();
    }
References PartialMapMenu.DestorySprites(), MapPiece.IsEditor, menu, PartialMapMenu.Refresh(), and PartialMapMenu.RefreshCategory().
Referenced by OnAfterProcessTiles(), and RefreshMenu().
OnSelectEnd()
override void AM_Copy.OnSelectEnd (bool cancel) inline virtual
Reimplemented from ActionMode.
Definition at line 97 of file AM_Copy.cs.
    {
        if (cancel)
        {
            RefreshMenu(show: true);
        }
    }
References RefreshMenu().
OnSelectStart()
override void AM_Copy.OnSelectStart (Point point) inline virtual
Reimplemented from ActionMode.
Definition at line 92 of file AM_Copy.cs.
    {
        RefreshMenu(show: false);
    }
References RefreshMenu().
OnSetSubMenuButton()
override string AM_Copy.OnSetSubMenuButton (int a, UIButton b) inline virtual
Reimplemented from ActionMode.
Definition at line 58 of file AM_Copy.cs.
    {
        if (a != 0)
        {
            return null;
        }
        b.SetCheck(PartialMap.relative);
        return "copyRelative";
    }
References PartialMap.relative, and UIButton.SetCheck().
OnUpdateInput()
override void AM_Copy.OnUpdateInput () inline virtual
Reimplemented from ActionMode.
Definition at line 185 of file AM_Copy.cs.
    {
        if (Input.GetKeyDown(KeyCode.K))
        {
            PartialMap.ExportDialog();
        }
        if (Input.GetKeyDown(KeyCode.L))
        {
            ImportDialog();
        }
    }
References PartialMap.ExportDialog(), and ImportDialog().
RefreshMenu()
void AM_Copy.RefreshMenu (bool show) inline
Definition at line 260 of file AM_Copy.cs.
    {
        if (!menu)
        {
            return;
        }
        menu.SetVisible(show);
        BuildMenu.Instance.terrainMenu.SetActive(!show);
        menu.buttonSave.SetActive(partialMap != null && partialMap.path.IsEmpty());
        menu.buttonDelete.SetActive(partialMap != null && !partialMap.path.IsEmpty());
        menu.buttonEdit.SetActive(partialMap != null && !partialMap.path.IsEmpty());
        menu.buttonSave.SetOnClick(delegate
        {
            UIScreenshot.Create().Activate(partialMap, dir, delegate(PartialMap a)
            {
                OnSave(a);
                Clear();
            });
        });
        menu.buttonDelete.SetOnClick(delegate
        {
            Dialog.YesNo("dialog_deleteMapPiece", delegate
            {
                SE.Trash();
                PartialMap.Delete(partialMap.path);
                menu.DestorySprites();
                menu.Refresh();
                Clear();
            });
        });
        menu.buttonEdit.SetOnClick(delegate
        {
            UIScreenshot.Create().Activate(partialMap, dir, OnSave, isUpdate: true);
            Clear();
        });
    }
References ActionMode.Activate(), UIScreenshot.Activate(), PartialMapMenu.buttonDelete, PartialMapMenu.buttonEdit, PartialMapMenu.buttonSave, Clear(), UIScreenshot.Create(), PartialMap.Delete(), PartialMapMenu.DestorySprites(), dir, BuildMenu.Instance, menu, OnSave(), partialMap, PartialMap.path, PartialMapMenu.Refresh(), PartialMapMenu.SetVisible(), BuildMenu.terrainMenu, and Dialog.YesNo().
Referenced by Clear(), Import(), OnActivate(), OnAfterProcessTiles(), OnCancel(), OnSelectEnd(), OnSelectStart(), and PartialMapMenu.Refresh().
RotateUnderMouse()
override void AM_Copy.RotateUnderMouse () inline virtual
Reimplemented from ActionMode.
Definition at line 197 of file AM_Copy.cs.
    {
        if (partialMap != null && partialMap.allowRotate)
        {
            partialMap.Rotate();
        }
        else
        {
            base.RotateUnderMouse();
        }
    }
References PartialMap.allowRotate, partialMap, and PartialMap.Rotate().
Member Data Documentation
dir
DirectoryInfo AM_Copy.dir
Definition at line 18 of file AM_Copy.cs.
Referenced by ImportDialog(), OnActivate(), OnAfterProcessTiles(), OnRenderTile(), and RefreshMenu().
dirUser
DirectoryInfo AM_Copy.dirUser
Definition at line 20 of file AM_Copy.cs.
Referenced by OnActivate().
overwritePath
string AM_Copy.overwritePath
Definition at line 14 of file AM_Copy.cs.
Referenced by OnAfterProcessTiles(), and OnCancel().
partialMap
PartialMap AM_Copy.partialMap
Definition at line 16 of file AM_Copy.cs.
Referenced by Clear(), HitTest(), Import(), OnAfterProcessTiles(), OnCancel(), OnDeactivate(), OnRenderTile(), RefreshMenu(), and RotateUnderMouse().
Property Documentation
buildMenuMode
override BuildMenu.Mode AM_Copy.buildMenuMode get
Definition at line 36 of file AM_Copy.cs.
CostMoney
override int AM_Copy.CostMoney get
Definition at line 46 of file AM_Copy.cs.
    {
        get
        {
            if (partialMap == null)
            {
                return 0;
            }
            return partialMap.value;
        }
    }
IsBuildMode
override bool AM_Copy.IsBuildMode get
Definition at line 34 of file AM_Copy.cs.
menu
PartialMapMenu AM_Copy.menu get
Definition at line 44 of file AM_Copy.cs.
Referenced by OnDeactivate(), OnSave(), and RefreshMenu().
mode
virtual Mode AM_Copy.mode get
Definition at line 42 of file AM_Copy.cs.
Referenced by OnActivate(), OnAfterProcessTiles(), and OnCancel().
selectType
override BaseTileSelector.SelectType AM_Copy.selectType get
Definition at line 22 of file AM_Copy.cs.
    {
        get
        {
            if (partialMap != null)
            {
                return BaseTileSelector.SelectType.Single;
            }
            return BaseTileSelector.SelectType.Multiple;
        }
    }
SubMenuAsGroup
override bool AM_Copy.SubMenuAsGroup get
Definition at line 40 of file AM_Copy.cs.
UseSubMenu
override bool AM_Copy.UseSubMenu get
Definition at line 38 of file AM_Copy.cs.
The documentation for this class was generated from the following file:
Elin/AM_Copy.cs