Elin Decompiled Documentation: PopManager Class Reference
PopManager Class Reference
Public Member Functions
T Get< T > (string id)
PopItemText PopText (string text, Sprite sprite=null, string id="PopText", Color c=default(Color), Vector3 destPos=default(Vector3), float duration=0f)
PopItem Pop (PopItem item, Vector3 destPos=default(Vector3), float duration=0f)
void UpdateDestPos ()
void Kill (PopItem item, bool instant=false)
void CopyAll (RectTransform rect)
void KillAll (bool instant=false)
Public Attributes
int maxLines
Vector2 dir
Vector2 align
Vector2 spacing
Vector2 startPos
float durationMove
float durationActive
Ease ease
bool startAtDestPos
bool insert
bool ignoreDestPos
List< PopItem > items = new List<PopItem>()
Static Public Attributes
static int outlineAlpha
Private Member Functions
void Update ()
void _Kill (PopItem item)
Detailed Description
Definition at line 7 of file PopManager.cs.
Member Function Documentation
_Kill()
void PopManager._Kill (PopItem item) inline private
Definition at line 161 of file PopManager.cs.
    {
        if (item == null || item.gameObject == null)
        {
            return;
        }
        DOTween.Kill(item.Rect());
        UnityEngine.Object.Destroy(item.gameObject);
        items.Remove(item);
        if (!ignoreDestPos)
        {
            UpdateDestPos();
            for (int i = 0; i < items.Count; i++)
            {
                items[i].Rect().DOAnchorPos(items[i].destPos, durationMove).SetEase(ease);
            }
        }
    }
References durationMove, ease, ignoreDestPos, item, items, and UpdateDestPos().
Referenced by Kill().
CopyAll()
void PopManager.CopyAll (RectTransform rect) inline
Definition at line 180 of file PopManager.cs.
    {
        foreach (PopItem item in items)
        {
            ContentSizeFitter[] componentsInChildren = item.GetComponentsInChildren<ContentSizeFitter>();
            for (int i = 0; i < componentsInChildren.Length; i++)
            {
                componentsInChildren[i].enabled = false;
            }
            LayoutGroup[] componentsInChildren2 = item.GetComponentsInChildren<LayoutGroup>();
            for (int i = 0; i < componentsInChildren2.Length; i++)
            {
                componentsInChildren2[i].enabled = false;
            }
            GameObject go = UnityEngine.Object.Instantiate(item.gameObject);
            go.transform.SetParent(rect, worldPositionStays: false);
            go.transform.position = item.transform.position;
            Vector3 fixPos = Camera.main.ScreenToWorldPoint(go.transform.Rect().anchoredPosition * BaseCore.Instance.uiScale);
            UIFollow uIFollow = go.AddComponent<UIFollow>();
            uIFollow.followPos = true;
            uIFollow.fixPos = fixPos;
            uIFollow.LateUpdate();
            go.AddComponent<CanvasGroup>().DOFade(0f, 1.5f).SetDelay(0.5f)
                .OnComplete(delegate
                {
                    if (go != null)
                    {
                        UnityEngine.Object.Destroy(go);
                    }
                });
        }
    }
References BaseCore.Instance, item, items, UIFollow.LateUpdate(), and BaseCore.uiScale.
Get< T >()
T PopManager.Get< T > (string id) inline
Type Constraints
T : PopItem
Definition at line 36 of file PopManager.cs.
                                       : PopItem
    {
        return Util.Instantiate<T>("UI/Pop/" + id, this);
    }
References Util.
Kill()
void PopManager.Kill (PopItem item, bool instant = false) inline
Definition at line 137 of file PopManager.cs.
    {
        if (item.important)
        {
            return;
        }
        TweenUtil.KillTween(ref item.killTimer);
        if (!instant && (bool)item.animeOut)
        {
            if (!item.isDying)
            {
                item.isDying = true;
                item.animeOut.Play(item.transform).OnComplete(delegate
                {
                    _Kill(item);
                });
            }
        }
        else
        {
            _Kill(item);
        }
    }
References _Kill(), and item.
Referenced by ELayer.Kill(), KillAll(), Pop(), and Update().
KillAll()
void PopManager.KillAll (bool instant = false) inline
Definition at line 213 of file PopManager.cs.
    {
        if (instant)
        {
            foreach (PopItem item in items)
            {
                TweenUtil.KillTween(ref item.killTimer);
                DOTween.Kill(item.Rect());
                UnityEngine.Object.Destroy(item.gameObject);
            }
            items.Clear();
        }
        else
        {
            for (int num = items.Count - 1; num >= 0; num--)
            {
                Kill(items[num], instant);
            }
        }
    }
References item, items, and Kill().
Referenced by WidgetMainText._ToggleLog().
Pop()
PopItem PopManager.Pop (PopItem item, Vector3 destPos = default(Vector3), float duration = 0f) inline
Definition at line 50 of file PopManager.cs.
    {
        Text[] componentsInChildren = item.GetComponentsInChildren<Text>();
        for (int i = 0; i < componentsInChildren.Length; i++)
        {
            componentsInChildren[i].RebuildLayout();
        }
        item.RebuildLayout();
        if (insert)
        {
            items.Insert(0, item);
        }
        else
        {
            items.Add(item);
        }
        RectTransform rectTransform = item.Rect();
        if (!ignoreDestPos)
        {
            UnityEngine.Object.Destroy(item.GetComponent<UIFollow>());
            UpdateDestPos();
            Vector2 anchoredPosition = (startAtDestPos ? item.destPos : new Vector2(rectTransform.rect.width * align.x, rectTransform.rect.height * align.y));
            anchoredPosition += startPos;
            rectTransform.anchoredPosition = anchoredPosition;
            for (int j = 0; j < items.Count; j++)
            {
                items[j].Rect().DOAnchorPos(items[j].destPos, durationMove).SetEase(ease);
            }
        }
        else
        {
            UIFollow uIFollow = item.GetComponent<UIFollow>();
            if (!uIFollow)
            {
                uIFollow = item.gameObject.AddComponent<UIFollow>();
            }
            uIFollow.followPos = true;
            uIFollow.fixPos = destPos;
            rectTransform.anchoredPosition = Camera.main.WorldToScreenPoint(destPos) / BaseCore.Instance.uiScale;
        }
        if ((bool)item.animeIn)
        {
            item.animeIn.Play(item.transform);
        }
        item.killTimer = TweenUtil.Tween(((duration == 0f) ? 1f : duration) * durationActive + durationMove, null, delegate
        {
            Kill(item);
        });
        base.enabled = true;
        return item;
    }
References align, durationActive, durationMove, ease, ignoreDestPos, insert, BaseCore.Instance, item, items, Kill(), startAtDestPos, startPos, BaseCore.uiScale, and UpdateDestPos().
Referenced by PopText().
PopText()
PopItemText PopManager.PopText (string text, Sprite sprite = null, string id = "PopText", Color c = default(Color), Vector3 destPos = default(Vector3), float duration = 0f) inline
Definition at line 41 of file PopManager.cs.
    {
        PopItemText popItemText = Get<PopItemText>(id);
        popItemText.important = false;
        popItemText.SetText(text, sprite, c);
        Pop(popItemText, destPos, duration);
        return popItemText;
    }
References Pop(), and PopItemText.SetText().
Referenced by LittlePopper._OnAddStockpile(), WidgetPopText._Say(), WidgetPopText._SayPick(), TCText.Say(), UI.Say(), WidgetFeed.SayRaw(), and WidgetFeed.System().
Update()
void PopManager.Update () inline private
Definition at line 102 of file PopManager.cs.
    {
        if (items.Count == 0)
        {
            base.enabled = false;
        }
        if (maxLines != 0 && items.Count > maxLines)
        {
            if (insert)
            {
                Kill(items.LastItem());
            }
            else
            {
                Kill(items[0]);
            }
        }
    }
References insert, items, Kill(), and maxLines.
UpdateDestPos()
void PopManager.UpdateDestPos () inline
Definition at line 121 of file PopManager.cs.
    {
        Vector2 zero = Vector2.zero;
        for (int i = 0; i < items.Count; i++)
        {
            Rect rect = items[i].Rect().rect;
            zero.x += rect.width * dir.x + spacing.x;
            zero.y += rect.height * dir.y + spacing.y;
            items[i].destPos = zero + new Vector2(rect.width * align.x, rect.height * align.y);
            if ((bool)items[i].arrow)
            {
                items[i].arrow.enabled = i == 0;
            }
        }
    }
References align, items, and spacing.
Referenced by _Kill(), and Pop().
Member Data Documentation
align
Vector2 PopManager.align
Definition at line 15 of file PopManager.cs.
Referenced by Pop(), and UpdateDestPos().
dir
Vector2 PopManager.dir
Definition at line 13 of file PopManager.cs.
durationActive
float PopManager.durationActive
Definition at line 23 of file PopManager.cs.
Referenced by Pop().
durationMove
float PopManager.durationMove
Definition at line 21 of file PopManager.cs.
Referenced by _Kill(), and Pop().
ease
Ease PopManager.ease
Definition at line 25 of file PopManager.cs.
Referenced by _Kill(), and Pop().
ignoreDestPos
bool PopManager.ignoreDestPos
Definition at line 31 of file PopManager.cs.
Referenced by _Kill(), and Pop().
insert
bool PopManager.insert
Definition at line 29 of file PopManager.cs.
Referenced by Pop(), and Update().
items
List<PopItem> PopManager.items = new List<PopItem>()
Definition at line 34 of file PopManager.cs.
Referenced by _Kill(), CopyAll(), KillAll(), Pop(), AI_Idle.Run(), Update(), and UpdateDestPos().
maxLines
int PopManager.maxLines
Definition at line 11 of file PopManager.cs.
Referenced by Update().
outlineAlpha
int PopManager.outlineAlpha static
Definition at line 9 of file PopManager.cs.
Referenced by PopItemText.SetText().
spacing
Vector2 PopManager.spacing
Definition at line 17 of file PopManager.cs.
Referenced by UpdateDestPos().
startAtDestPos
bool PopManager.startAtDestPos
Definition at line 27 of file PopManager.cs.
Referenced by Pop().
startPos
Vector2 PopManager.startPos
Definition at line 19 of file PopManager.cs.
Referenced by Pop().
The documentation for this class was generated from the following file:
Elin/Plugins.UI/PopManager.cs