Elin Decompiled Documentation: Party Class Reference
Party Class Reference
Public Member Functions
List< Chara > SetMembers ()
void AddMemeber (Chara c, bool showMsg=false)
Chara Find (string id)
void RemoveMember (Chara c)
void Replace (Chara c, int index)
void SetLeader (Chara c)
Element GetPartySkill (int ele)
void ModExpPartySkill (int ele, int a)
Element GetBestSkill (int ele)
bool IsCriticallyWounded (bool includePc=false)
int EvalueBest (int ele)
int EvalueTotal (int ele, Func< Chara, bool > funcIf=null)
bool HasElement (int ele, bool excludePC=false)
int Count ()
Public Attributes
int uidLeader
List< int > uidMembers = new List<int>()
List< Chara > _members
RefChara refLeader = new RefChara()
Properties
List< Chara > members [get]
Chara leader [get, set]
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Additional Inherited Members
Static Public Member Functions inherited from EClass
static int rndSeed (int a, int seed)
static int rnd (long a)
static int rnd (int a)
static int curve (int _a, int start, int step, int rate=75)
static int sqrt (int a)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Static Public Attributes inherited from EClass
static Core core
Detailed Description
Definition at line 6 of file Party.cs.
Member Function Documentation
AddMemeber()
void Party.AddMemeber (Chara c, bool showMsg = false) inline
Definition at line 57 of file Party.cs.
    {
        if (c.party == this)
        {
            return;
        }
        if (!c.IsGlobal)
        {
            Debug.LogError("exception: " + c?.ToString() + " is not global chara");
        }
        members.Add(c);
        uidMembers.Add(c.uid);
        c.party = this;
        c.isSale = false;
        c.SetBool(18, enable: false);
        if (c.homeBranch != null)
        {
            c.RefreshWorkElements(c.homeBranch.elements);
            c.homeBranch.RefreshEfficiency();
            c.homeBranch.policies.Validate();
            if (c.homeBranch.owner.map != null)
            {
                c.homeBranch.owner.map.props.sales.Remove(c);
            }
        }
        if (showMsg)
        {
            Msg.Say("party_join", c.Name);
            SE.Play("party_join");
        }
        WidgetRoster.SetDirty();
    }
References Debug, FactionBranch.elements, Chara.homeBranch, Chara.IsGlobal, Zone.map, members, Card.Name, FactionBranch.owner, Chara.party, FactionBranch.policies, Map.props, FactionBranch.RefreshEfficiency(), Chara.RefreshWorkElements(), PropsManager.sales, Msg.Say(), BaseCard.SetBool(), WidgetRoster.SetDirty(), Card.uid, uidMembers, and PolicyManager.Validate().
Referenced by PartyManager.Create(), FactionBranch.DailyOutcome(), Chara.GetRevived(), TraitFoodEggFertilized.Incubate(), Chara.MakeAlly(), Chara.MakePartyMemeber(), FactionBranch.OnAfterSimulate(), QuestDebt.OnStart(), CoreDebug.QuickStart(), and ActRide.Ride().
Count()
int Party.Count () inline
Definition at line 206 of file Party.cs.
    {
        int num = 0;
        foreach (Chara member in members)
        {
            if (!member.isDead)
            {
                num++;
            }
        }
        return num;
    }
References Chara.isDead, and members.
EvalueBest()
int Party.EvalueBest (int ele) inline
Definition at line 168 of file Party.cs.
    {
        int num = 0;
        foreach (Chara member in members)
        {
            if (member.Evalue(ele) > num)
            {
                num = member.Evalue(ele);
            }
        }
        return num;
    }
References Card.Evalue(), and members.
EvalueTotal()
int Party.EvalueTotal (int ele, Func< Chara, bool > funcIf = null) inline
Definition at line 181 of file Party.cs.
    {
        int num = 0;
        foreach (Chara member in members)
        {
            if (funcIf == null || funcIf(member))
            {
                num += member.Evalue(ele);
            }
        }
        return num;
    }
References Card.Evalue(), and members.
Referenced by AI_Idle.Run().
Find()
Chara Party.Find (string id) inline
Definition at line 90 of file Party.cs.
    {
        foreach (Chara member in members)
        {
            if (member.id == id)
            {
                return member;
            }
        }
        return null;
    }
References Card.id, and members.
Referenced by Zone_DungeonFairy.OnGenerateMap(), and TraitStairsLocked.OnUse().
GetBestSkill()
Element Party.GetBestSkill (int ele) inline
Definition at line 143 of file Party.cs.
    {
        Element element = Element.Create(ele);
        foreach (Chara member in members)
        {
            if (member.IsAliveInCurrentZone && member.Evalue(ele) > element.Value)
            {
                element = member.elements.GetElement(ele);
            }
        }
        return element;
    }
References Element.Create(), Card.elements, Card.Evalue(), ElementContainer.GetElement(), Chara.IsAliveInCurrentZone, and members.
Referenced by GetPartySkill().
GetPartySkill()
Element Party.GetPartySkill (int ele) inline
Definition at line 134 of file Party.cs.
    {
        return GetBestSkill(ele);
    }
References GetBestSkill().
HasElement()
bool Party.HasElement (int ele, bool excludePC = false) inline
Definition at line 194 of file Party.cs.
    {
        foreach (Chara member in members)
        {
            if ((!excludePC || !member.IsPC) && member.HasElement(ele))
            {
                return true;
            }
        }
        return false;
    }
References Card.HasElement(), Chara.IsPC, and members.
Referenced by Chara.Die(), and AI_Idle.Run().
IsCriticallyWounded()
bool Party.IsCriticallyWounded (bool includePc = false) inline
Definition at line 156 of file Party.cs.
    {
        foreach (Chara member in members)
        {
            if ((!includePc || !member.IsPC) && member.IsCriticallyWounded())
            {
                return true;
            }
        }
        return false;
    }
References Chara.IsCriticallyWounded(), Chara.IsPC, and members.
Referenced by AM_Adv._OnUpdateInput(), and GoalAutoCombat.GetActPlanColor().
ModExpPartySkill()
void Party.ModExpPartySkill (int ele, int a) inline
Definition at line 139 of file Party.cs.
    {
    }
RemoveMember()
void Party.RemoveMember (Chara c) inline
Definition at line 102 of file Party.cs.
    {
        if (c.host != null)
        {
            ActRide.Unride(c.host, c.host.parasite == c);
        }
        members.Remove(c);
        uidMembers.Remove(c.uid);
        c.party = null;
        c.c_wasInPcParty = false;
        c.SetDirtySpeed();
        if (c.homeBranch != null)
        {
            c.homeBranch.RefreshEfficiency();
            c.RefreshWorkElements(c.homeBranch.elements);
        }
        WidgetRoster.SetDirty();
    }
References FactionBranch.elements, Chara.homeBranch, Chara.host, members, Chara.parasite, FactionBranch.RefreshEfficiency(), Chara.RefreshWorkElements(), WidgetRoster.SetDirty(), Chara.SetDirtySpeed(), Card.uid, uidMembers, and ActRide.Unride().
Referenced by Faction.AddReserve(), Card.Destroy(), Chara.Die(), Chara.MoveHome(), TraitHitchingPost.OnActivateTrap(), TraitGeneMachine.OnUse(), AI_Slaughter.Run(), and CoreDebug.UpdateInput().
Replace()
void Party.Replace (Chara c, int index) inline
Definition at line 121 of file Party.cs.
    {
        members.Remove(c);
        uidMembers.Remove(c.uid);
        members.Insert(index, c);
        uidMembers.Insert(index, c.uid);
    }
References members, Card.uid, and uidMembers.
SetLeader()
void Party.SetLeader (Chara c) inline
Definition at line 129 of file Party.cs.
    {
        leader = c;
    }
References leader.
Referenced by PartyManager.Create().
SetMembers()
List< Chara > Party.SetMembers () inline
Definition at line 42 of file Party.cs.
    {
        _members = new List<Chara>();
        HashSet<int> hashSet = new HashSet<int>();
        foreach (int uidMember in uidMembers)
        {
            if (!hashSet.Contains(uidMember))
            {
                hashSet.Add(uidMember);
                members.Add(RefChara.Get(uidMember));
            }
        }
        return _members;
    }
References _members, RefChara.Get(), members, and uidMembers.
Member Data Documentation
_members
List<Chara> Party._members
Definition at line 14 of file Party.cs.
Referenced by SetMembers().
refLeader
RefChara Party.refLeader = new RefChara()
Definition at line 16 of file Party.cs.
uidLeader
int Party.uidLeader
Definition at line 9 of file Party.cs.
uidMembers
List<int> Party.uidMembers = new List<int>()
Definition at line 12 of file Party.cs.
Referenced by AddMemeber(), RemoveMember(), Replace(), and SetMembers().
Property Documentation
leader
Chara Party.leader get set
Definition at line 30 of file Party.cs.
    {
        get
        {
            return refLeader.GetAndCache(uidLeader);
        }
        set
        {
            refLeader.Set(ref uidLeader, value);
        }
    }
Referenced by TileMapElona.DrawTile(), Chara.MoveZone(), AI_Idle.Run(), and SetLeader().
members
List<Chara> Party.members get
Definition at line 18 of file Party.cs.
    {
        get
        {
            if (_members != null)
            {
                return _members;
            }
            return SetMembers();
        }
    }
Referenced by Chara._Move(), TraitGodStatue._OnUse(), TraitShrine._OnUse(), AddMemeber(), LayerSleep.Advance(), ZoneEventQuest.AggroEnemy(), WidgetRoster.Build(), WidgetStatsBar.Build(), Count(), LayerInventory.CreateContainer(), Chara.Cuddle(), Chara.DoHostileAction(), EvalueBest(), EvalueTotal(), ZonePreEnterEncounter.Execute(), Find(), GetBestSkill(), GoalAutoCombat.GoalAutoCombat(), HasElement(), IsCriticallyWounded(), Player.MoveZone(), Chara.MoveZone(), Player.OnAdvanceHour(), Zone_RandomDungeon.OnGenerateMap(), Zone_Void.OnGenerateMap(), ZoneEventHarvest.OnLeaveZone(), ElementContainerCard.OnLevelUp(), BaseListPeople.OnList(), Game.OnLoad(), ConSleep.OnRemoved(), Scene.OnUpdate(), ZoneEventMusic.OnVisit(), ActPray.Pray(), Player.RefreshEmptyAlly(), RemoveMember(), Replace(), AI_Idle.Run(), AI_PassTime.Run(), Weather.SetCondition(), LayerDragGrid.SetInv(), SetMembers(), Chara.Tick(), ConSleep.Tick(), Chara.TryNullifyCurse(), ActPray.TryPray(), GoalCombat.TryUseAbility(), DramaOutcome.upgrade_miscreation(), Chara.UseAbility(), ElementContainerCard.ValueBonus(), and TraitBookSkill.WriteNote().
The documentation for this class was generated from the following file:
Elin/Party.cs