Elin Decompiled Documentation: SourceObj Class Reference
SourceObj Class Reference
Classes
class Row
class Stage
Public Member Functions
override Row CreateRow ()
override void SetRow (Row r)
override void BackupPref ()
override void RestorePref ()
override void ValidatePref ()
string GetName (int id)
override void OnAfterImportData ()
override void OnInit ()
Public Member Functions inherited from SourceDataInt< SourceObj.Row >
override T GetRow (string id)
Public Attributes
Dictionary< int, Row > _rows = new Dictionary<int, Row>()
Static Public Attributes
static RenderData FallbackRenderData
Detailed Description
Definition at line 4 of file SourceObj.cs.
Member Function Documentation
BackupPref()
override void SourceObj.BackupPref () inline
Definition at line 122 of file SourceObj.cs.
    {
        _rows.Clear();
        foreach (Row row in rows)
        {
            _rows[row.id] = row;
        }
    }
References _rows, and TileRow.id.
CreateRow()
override Row SourceObj.CreateRow () inline
Definition at line 79 of file SourceObj.cs.
    {
        return new Row
        {
            id = SourceData.GetInt(0),
            alias = SourceData.GetString(1),
            name_JP = SourceData.GetString(2),
            name = SourceData.GetString(3),
            _growth = SourceData.GetStringArray(4),
            costSoil = SourceData.GetInt(5),
            objType = SourceData.GetString(6),
            vals = SourceData.GetStringArray(7),
            tag = SourceData.GetStringArray(8),
            sort = SourceData.GetInt(9),
            reqHarvest = SourceData.GetStringArray(10),
            hp = SourceData.GetInt(11),
            _tileType = SourceData.GetString(12),
            valType = SourceData.GetString(13),
            _idRenderData = SourceData.GetString(14),
            tiles = SourceData.GetIntArray(15),
            snowTile = SourceData.GetInt(16),
            colorMod = SourceData.GetInt(17),
            colorType = SourceData.GetString(18),
            value = SourceData.GetInt(19),
            LV = SourceData.GetInt(20),
            chance = SourceData.GetInt(21),
            recipeKey = SourceData.GetStringArray(22),
            factory = SourceData.GetStringArray(23),
            components = SourceData.GetStringArray(24),
            defMat = SourceData.GetString(25),
            matCategory = SourceData.GetString(26),
            category = SourceData.GetString(27),
            idRoof = SourceData.GetInt(28),
            detail_JP = SourceData.GetString(29),
            detail = SourceData.GetString(30)
        };
    }
References SourceData< T, T2 >.GetInt(), SourceData< T, T2 >.GetIntArray(), SourceData< T, T2 >.GetString(), and SourceData< T, T2 >.GetStringArray().
GetName()
string SourceObj.GetName (int id) inline
Definition at line 147 of file SourceObj.cs.
    {
        return map[id].GetName().ToTitleCase();
    }
Referenced by Cell.GetObjName(), ActBash.Perform(), TraitSeed.SetName(), LayerInfo.SetObj(), and ObjInfo.WriteNote().
OnAfterImportData()
override void SourceObj.OnAfterImportData () inline
Definition at line 152 of file SourceObj.cs.
    {
        int num = 0;
        foreach (Row row in rows)
        {
            if (row.sort != 0)
            {
                num = row.sort;
            }
            row.sort = num;
            num++;
        }
        rows.Sort((Row a, Row b) => a.id - b.id);
    }
References TileRow.id, and RenderRow.sort.
OnInit()
override void SourceObj.OnInit () inline
Definition at line 167 of file SourceObj.cs.
    {
        FallbackRenderData = ResourceCache.Load<RenderData>("Scene/Render/Data/obj");
        Cell.objList = rows;
        foreach (Row row in rows)
        {
            row.Init();
        }
    }
References FallbackRenderData, and TileRow.Init().
RestorePref()
override void SourceObj.RestorePref () inline
Definition at line 131 of file SourceObj.cs.
    {
        foreach (Row row in rows)
        {
            row.pref = _rows.TryGetValue(row.id)?.pref ?? new SourcePref();
        }
    }
References _rows, and TileRow.id.
SetRow()
override void SourceObj.SetRow (Row r) inline
Definition at line 117 of file SourceObj.cs.
    {
        map[r.id] = r;
    }
References TileRow.id.
ValidatePref()
override void SourceObj.ValidatePref () inline
Definition at line 139 of file SourceObj.cs.
    {
        foreach (Row row in rows)
        {
            row.pref.Validate();
        }
    }
References RenderRow.pref, and SourcePref.Validate().
Referenced by SourcePrefInspector.ValidatePrefs().
Member Data Documentation
_rows
Dictionary<int, Row> SourceObj._rows = new Dictionary<int, Row>()
Definition at line 75 of file SourceObj.cs.
Referenced by BackupPref(), and RestorePref().
FallbackRenderData
RenderData SourceObj.FallbackRenderData static
Definition at line 77 of file SourceObj.cs.
Referenced by OnInit().
The documentation for this class was generated from the following file:
Elin/SourceObj.cs