Elin Decompiled Documentation: WidgetMemo Class Reference
WidgetMemo Class Reference
Classes
class Extra
Public Member Functions
override object CreateExtra ()
override void OnActivate ()
override void OnDeactivate ()
void ToggleInput (bool enable)
override void OnUpdateConfig ()
void SaveText ()
void ToggleAutoHide ()
Public Member Functions inherited from Widget
void Test ()
bool IsInRightMode ()
void Activate ()
void RefreshOrder ()
virtual void OnActivate ()
virtual object CreateExtra ()
void Deactivate ()
virtual void OnDeactivate ()
void Close ()
void Reactivate ()
virtual void OnManagerActivate ()
virtual void OnManagerDeactivate ()
void SetAnchor (RectPosition p)
void SetPivot (RectPosition p)
virtual void OnChangePivot ()
void UpdateConfig ()
virtual void OnUpdateConfig ()
void ClampToScreen ()
virtual void OnChangeResolution ()
void OnChangePosition ()
virtual void OnChangeActionMode ()
virtual void OnFlip ()
bool IsAlignTop ()
Layer AddLayer (Layer l, Transform trans)
void RefreshTipPivotPosition ()
SkinSet GetSkin ()
SkinConfig GetSkinConfig ()
void SetSkin (int id, int v=0)
void TestSkin ()
virtual void ApplySkin ()
virtual void OnApplySkin ()
void InstantiateDeco (SkinDeco deco)
void AddDeco (SkinDeco deco)
void RemoveDeco (SkinDeco deco)
virtual bool CanShowContextMenu ()
void ShowContextMenu ()
void SetBaseContextMenu (UIContextMenu m)
virtual void OnSetContextMenu (UIContextMenu m)
void SetGridContextMenu (UIContextMenu m)
void SoundActivate ()
void OnChangeResolution ()
SkinSet GetSkin ()
SkinConfig GetSkinConfig ()
Public Attributes
int id
float hideTimer
InputField input
Window window
Image bgInput
Text textInput
UIButton buttonClose
UIButton buttonEdit
UIButton buttonAutoHide
CanvasGroup cgText
RectTransform inputRect
Public Attributes inherited from Widget
Image imageBG
SoundData soundActivate
UIDragPanel dragPanel
RectTransform tipPivotLeft
RectTransform tipPivotRight
Static Public Attributes
static WidgetMemo Instance
Static Public Attributes inherited from EMono
static Core core
Properties
Extra extra [get]
override bool AlwaysBottom [get]
override Type SetSiblingAfter [get]
Properties inherited from Widget
string ID [get]
Config config [get]
SkinRoot skinRoot [get]
bool IsSealed [get]
virtual bool ShowStyleMenu [get]
virtual bool AlwaysTop [get]
virtual bool IsStaticPosition [get]
virtual bool AlwaysBottom [get]
virtual Type SetSiblingAfter [get]
virtual bool ShowInBuildMode [get]
virtual bool RightClickToClose [get]
virtual bool AllowRightClickToClose [get]
Properties inherited from EMono
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SoundManager Sound [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static CoreDebug debug [get]
Private Member Functions
void Update ()
Additional Inherited Members
Public Types inherited from Widget
enum WidgetType { Default , ZoomMenu }
enum State { Active , Inactive }
Static Public Member Functions inherited from EMono
static int rnd (int a)
Protected Member Functions inherited from Widget
void ClampToScreenEnsured (Component c, Vector2 anchoredPos)
void ClampToScreen (RectTransform rect, float margin=10f)
Protected Attributes inherited from Widget
bool flip
Detailed Description
Definition at line 5 of file WidgetMemo.cs.
Member Function Documentation
CreateExtra()
override object WidgetMemo.CreateExtra () inline virtual
Reimplemented from Widget.
Definition at line 43 of file WidgetMemo.cs.
    {
        return new Extra();
    }
OnActivate()
override void WidgetMemo.OnActivate () inline virtual
Reimplemented from Widget.
Definition at line 48 of file WidgetMemo.cs.
    {
        input.text = ((id == 0) ? EMono.player.memo : EMono.player.memo2);
        buttonEdit.SetOnClick(delegate
        {
            SE.Tab();
            ToggleInput(!input.isFocused);
        });
        Instance = this;
        buttonAutoHide.icon.SetAlpha(extra.autoHide ? 0.4f : 1f);
        if (extra.autoHide)
        {
            cgText.alpha = 0f;
        }
    }
References WidgetMemo.Extra.autoHide, buttonAutoHide, buttonEdit, extra, UIButton.icon, input, Instance, Player.memo, Player.memo2, EMono.player, and ToggleInput().
OnDeactivate()
override void WidgetMemo.OnDeactivate () inline virtual
Reimplemented from Widget.
Definition at line 64 of file WidgetMemo.cs.
    {
        SaveText();
    }
References SaveText().
OnUpdateConfig()
override void WidgetMemo.OnUpdateConfig () inline virtual
Reimplemented from Widget.
Definition at line 81 of file WidgetMemo.cs.
    {
        SaveText();
    }
References SaveText().
SaveText()
void WidgetMemo.SaveText () inline
Definition at line 86 of file WidgetMemo.cs.
    {
        if (id == 0)
        {
            EMono.player.memo = input.text;
        }
        else
        {
            EMono.player.memo2 = input.text;
        }
    }
References input.
Referenced by OnDeactivate(), and OnUpdateConfig().
ToggleAutoHide()
void WidgetMemo.ToggleAutoHide () inline
Definition at line 98 of file WidgetMemo.cs.
    {
        SE.Tab();
        extra.autoHide = !extra.autoHide;
        hideTimer = 0f;
        cgText.alpha = 1f;
        buttonAutoHide.icon.SetAlpha(extra.autoHide ? 0.4f : 1f);
    }
References WidgetMemo.Extra.autoHide, buttonAutoHide, extra, hideTimer, and UIButton.icon.
ToggleInput()
void WidgetMemo.ToggleInput (bool enable) inline
Definition at line 69 of file WidgetMemo.cs.
    {
        input.interactable = enable;
        bgInput.enabled = enable;
        textInput.raycastTarget = enable;
        buttonClose.SetActive(enable);
        if (enable)
        {
            input.Select();
        }
    }
References buttonClose, and input.
Referenced by OnActivate(), and Update().
Update()
void WidgetMemo.Update () inline private
Definition at line 107 of file WidgetMemo.cs.
    {
        if (!input.isFocused)
        {
            if (input.interactable && !InputModuleEX.IsPointerChildOf(this))
            {
                ToggleInput(enable: false);
            }
        }
        else if (!bgInput.enabled)
        {
            ToggleInput(enable: true);
        }
        if (extra.autoHide)
        {
            bool flag = InputModuleEX.IsPointerOver(this) || input.isFocused;
            if (!flag && cgText.alpha != 0f)
            {
                Vector3 point = inputRect.InverseTransformPoint(Input.mousePosition);
                if (inputRect.rect.Contains(point))
                {
                    flag = true;
                }
            }
            if (flag)
            {
                hideTimer = 0f;
                cgText.alpha = 1f;
                return;
            }
            hideTimer += Core.delta;
            if (hideTimer > 1f)
            {
                cgText.alpha = 0f;
            }
        }
        else
        {
            cgText.alpha = 1f;
            hideTimer = 0f;
        }
    }
References WidgetMemo.Extra.autoHide, bgInput, cgText, Core.delta, extra, hideTimer, input, inputRect, InputModuleEX.IsPointerChildOf(), InputModuleEX.IsPointerOver(), and ToggleInput().
Member Data Documentation
bgInput
Image WidgetMemo.bgInput
Definition at line 23 of file WidgetMemo.cs.
Referenced by Update().
buttonAutoHide
UIButton WidgetMemo.buttonAutoHide
Definition at line 31 of file WidgetMemo.cs.
Referenced by OnActivate(), and ToggleAutoHide().
buttonClose
UIButton WidgetMemo.buttonClose
Definition at line 27 of file WidgetMemo.cs.
Referenced by ToggleInput().
buttonEdit
UIButton WidgetMemo.buttonEdit
Definition at line 29 of file WidgetMemo.cs.
Referenced by OnActivate().
cgText
CanvasGroup WidgetMemo.cgText
Definition at line 33 of file WidgetMemo.cs.
Referenced by Update().
hideTimer
float WidgetMemo.hideTimer
Definition at line 17 of file WidgetMemo.cs.
Referenced by ToggleAutoHide(), and Update().
id
int WidgetMemo.id
Definition at line 14 of file WidgetMemo.cs.
input
InputField WidgetMemo.input
Definition at line 19 of file WidgetMemo.cs.
Referenced by OnActivate(), SaveText(), ToggleInput(), and Update().
inputRect
RectTransform WidgetMemo.inputRect
Definition at line 35 of file WidgetMemo.cs.
Referenced by Update().
Instance
WidgetMemo WidgetMemo.Instance static
Definition at line 12 of file WidgetMemo.cs.
Referenced by OnActivate().
textInput
Text WidgetMemo.textInput
Definition at line 25 of file WidgetMemo.cs.
window
Window WidgetMemo.window
Definition at line 21 of file WidgetMemo.cs.
Property Documentation
AlwaysBottom
override bool WidgetMemo.AlwaysBottom get
Definition at line 39 of file WidgetMemo.cs.
extra
Extra WidgetMemo.extra get
Definition at line 37 of file WidgetMemo.cs.
Referenced by OnActivate(), ToggleAutoHide(), and Update().
SetSiblingAfter
override Type WidgetMemo.SetSiblingAfter get
Definition at line 41 of file WidgetMemo.cs.
The documentation for this class was generated from the following file:
Elin/WidgetMemo.cs