Elin Decompiled Documentation: UIZoneInfo Class Reference
UIZoneInfo Class Reference
Public Member Functions
void SetZone (Zone _zone)
Public Attributes
UINote note
UIButton buttonBuy
UIButton buttonVisit
UIButton buttonExplore
int gx
int gy
Zone zone
Properties
EloMap elomap [get]
EloMapActor actor [get]
Properties inherited from EMono
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SoundManager Sound [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static CoreDebug debug [get]
Additional Inherited Members
Static Public Member Functions inherited from EMono
static int rnd (int a)
Static Public Attributes inherited from EMono
static Core core
Detailed Description
Definition at line 1 of file UIZoneInfo.cs.
Member Function Documentation
SetZone()
void UIZoneInfo.SetZone (Zone _zone) inline
Definition at line 21 of file UIZoneInfo.cs.
    {
        zone = _zone;
        gx = zone.x;
        gy = zone.y;
        elomap.GetCell(gx, gy);
        note.Clear();
        GetComponentInParent<Window>().SetCaption(zone.Name);
        note.AddHeaderTopic("mainFaction".lang());
        note.AddText(zone.mainFaction.name);
        note.Space();
        note.AddHeaderTopic("listRoamers".lang());
        int num = 0;
        foreach (Chara value in EMono.game.cards.globalCharas.Values)
        {
            if (value.currentZone == zone)
            {
                note.AddText(value.Name);
                num++;
                if (num > 5)
                {
                    break;
                }
            }
        }
        if (num == 0)
        {
            note.AddText("????????");
        }
        note.Build();
    }
References EMono._zone, UINote.AddHeaderTopic(), UINote.AddText(), UINote.Build(), Game.cards, UINote.Clear(), Chara.currentZone, elomap, EMono.game, EloMap.GetCell(), CardManager.globalCharas, gx, gy, Spatial.mainFaction, Card.Name, Faction.name, Spatial.Name, note, UINote.Space(), Spatial.x, Spatial.y, and zone.
Referenced by LayerLocation.RefreshZones().
Member Data Documentation
buttonBuy
UIButton UIZoneInfo.buttonBuy
Definition at line 5 of file UIZoneInfo.cs.
buttonExplore
UIButton UIZoneInfo.buttonExplore
Definition at line 9 of file UIZoneInfo.cs.
buttonVisit
UIButton UIZoneInfo.buttonVisit
Definition at line 7 of file UIZoneInfo.cs.
gx
int UIZoneInfo.gx
Definition at line 11 of file UIZoneInfo.cs.
Referenced by SetZone().
gy
int UIZoneInfo.gy
Definition at line 13 of file UIZoneInfo.cs.
Referenced by SetZone().
note
UINote UIZoneInfo.note
Definition at line 3 of file UIZoneInfo.cs.
Referenced by SetZone().
zone
Zone UIZoneInfo.zone
Definition at line 15 of file UIZoneInfo.cs.
Referenced by SetZone().
Property Documentation
actor
EloMapActor UIZoneInfo.actor get
Definition at line 19 of file UIZoneInfo.cs.
elomap
EloMap UIZoneInfo.elomap get
Definition at line 17 of file UIZoneInfo.cs.
Referenced by SetZone().
The documentation for this class was generated from the following file:
Elin/UIZoneInfo.cs