Elin Decompiled Documentation: GameUpdater.FastSurfaceUpdater Class Reference
GameUpdater.FastSurfaceUpdater Class Reference
Public Member Functions
override void FixedUpdate ()
override void FixedUpdate ()
Public Member Functions inherited from GameUpdater.Updater
virtual void FixedUpdate ()
void SetUpdatesPerFrame (int _maxcount, float _duration)
Additional Inherited Members
Static Public Member Functions inherited from EClass
static int rnd (int a)
static int curve (int a, int start, int step, int rate=75)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Public Attributes inherited from GameUpdater.SurfaceUpdater
int x
int z
Public Attributes inherited from GameUpdater.Updater
int index
int updatesPerFrame
int maxCount
float duration = 1f
float _updatesPerFrame
Point pos = new Point()
Static Public Attributes inherited from EClass
static Core core
Properties inherited from GameUpdater.SurfaceUpdater
int SizeXZ [get]
int Size [get]
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Detailed Description
Definition at line 138 of file GameUpdater.cs.
Member Function Documentation
FixedUpdate()
override void GameUpdater.FastSurfaceUpdater.FixedUpdate () inline virtual
Reimplemented from GameUpdater.SurfaceUpdater.
Definition at line 140 of file GameUpdater.cs.
        {
            if (!pos.Set(x, z).IsValid)
            {
                x = (z = 0);
            }
            SetUpdatesPerFrame(base.SizeXZ, 1f);
            for (int i = 0; i < updatesPerFrame; i++)
            {
                pos.Set(x, z);
                Cell cell = pos.cell;
                if (cell.effect != null && cell.effect.WillFade)
                {
                    cell.effect.amount--;
                    if (cell.effect.amount <= 0)
                    {
                        EClass._map.SetEffect(pos.x, pos.z);
                    }
                }
                x++;
                if (x >= base.Size)
                {
                    x = 0;
                    z++;
                    if (z >= base.Size)
                    {
                        z = 0;
                    }
                }
            }
        }
References EClass._map, CellEffect.amount, Point.cell, Cell.effect, Point.IsValid, GameUpdater.Updater.pos, Point.Set(), Map.SetEffect(), GameUpdater.Updater.SetUpdatesPerFrame(), GameUpdater.Updater.updatesPerFrame, CellEffect.WillFade, GameUpdater.SurfaceUpdater.x, Point.x, GameUpdater.SurfaceUpdater.z, and Point.z.
Referenced by GameUpdater.FixedUpdate().
The documentation for this class was generated from the following file:
Elin/GameUpdater.cs