Elin Decompiled Documentation: HotbarManager Class Reference
HotbarManager Class Reference
Public Member Functions
void ResetHotbar (int id)
Hotbar SetHobar (int id, int slots, WidgetHotbar actor=null)
void OnCreateGame ()
Public Attributes
Hotbar[] bars = new Hotbar[8]
Additional Inherited Members
Static Public Member Functions inherited from EClass
static int rndSeed (int a, int seed)
static int rnd (long a)
static int rnd (int a)
static int curve (int a, int start, int step, int rate=75)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Static Public Attributes inherited from EClass
static Core core
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Detailed Description
Definition at line 3 of file HotbarManager.cs.
Member Function Documentation
OnCreateGame()
void HotbarManager.OnCreateGame () inline
Definition at line 289 of file HotbarManager.cs.
    {
        ResetHotbar(0);
        ResetHotbar(1);
        ResetHotbar(2);
        ResetHotbar(3);
        ResetHotbar(4);
        ResetHotbar(5);
        ResetHotbar(6);
        ResetHotbar(7);
    }
References ResetHotbar().
Referenced by Player.OnCreateGame().
ResetHotbar()
void HotbarManager.ResetHotbar (int id) inline
Definition at line 8 of file HotbarManager.cs.
    {
        WidgetHotbar widgetHotbar = bars[id]?.actor ?? null;
        Hotbar hotbar = null;
        switch (id)
        {
        case 0:
            hotbar = SetHobar(0, 4);
            break;
        case 1:
            hotbar = SetHobar(1, 4);
            hotbar.SetItem(new HotItemContext
            {
                id = "system"
            }, 0);
            hotbar.SetItem(new HotItemToggleLog(), 1);
            hotbar.SetItem(new HotItemContext
            {
                id = "mapTool"
            }, 2);
            hotbar.SetItem(new HotItemToggleWidget(), 3);
            break;
        case 2:
            hotbar = SetHobar(2, 7);
            hotbar.SetItem(new HotItemLayer
            {
                id = "stash"
            });
            hotbar.SetItem(new HotItemLayer
            {
                id = "LayerAbility"
            });
            hotbar.SetItem(new HotItemLayer
            {
                id = "LayerChara"
            });
            hotbar.SetItem(new HotItemLayer
            {
                id = "LayerJournal"
            });
            if (EClass.core.IsGameStarted && EClass._zone.CanEnterBuildModeAnywhere)
            {
                hotbar.SetItem(new HotItemActionMode
                {
                    id = "Inspect"
                });
            }
            if (EClass.core.IsGameStarted && EClass._zone.IsRegion)
            {
                hotbar.SetItem(new HotItemLayer
                {
                    id = "LayerTravel"
                });
            }
            break;
        case 3:
        {
            hotbar = SetHobar(3, 12);
            if (!EClass.core.IsGameStarted)
            {
                return;
            }
            bool flag = EClass.debug.godBuild || EClass.debug.ignoreBuildRule;
            if (flag || EClass.Branch != null)
            {
                if (flag || EClass.Branch.elements.Has(4006))
                {
                    hotbar.SetItem(new HotItemActionMode
                    {
                        id = "Inspect"
                    }).always = true;
                }
                if (flag || EClass.Branch.elements.Has(4000))
                {
                    hotbar.SetItem(new HotItemActionMode
                    {
                        id = "Cut"
                    });
                }
                if (flag || EClass.Branch.elements.Has(4001))
                {
                    hotbar.SetItem(new HotItemActionMode
                    {
                        id = "Mine"
                    });
                }
                if (flag || EClass.Branch.elements.Has(4001))
                {
                    hotbar.SetItem(new HotItemActionMode
                    {
                        id = "Dig"
                    });
                }
                if (flag || EClass.Branch.elements.Has(4002))
                {
                    hotbar.SetItem(new HotItemActionMode
                    {
                        id = "Terrain"
                    });
                }
                if (flag)
                {
                    hotbar.SetItem(new HotItemActionMode
                    {
                        id = "Copy"
                    });
                }
                if (flag)
                {
                    hotbar.SetItem(new HotItemActionMode
                    {
                        id = "Populate"
                    });
                }
                if (flag || EClass.Branch.elements.Has(4004))
                {
                    hotbar.SetItem(new HotItemActionMode
                    {
                        id = "Deconstruct"
                    });
                }
            }
            else if (EClass._zone is Zone_Tent)
            {
                if (flag || EClass.pc.homeBranch.elements.Has(4006))
                {
                    hotbar.SetItem(new HotItemActionMode
                    {
                        id = "Inspect"
                    }).always = true;
                }
                if (flag || EClass.pc.homeBranch.elements.Has(4000))
                {
                    hotbar.SetItem(new HotItemActionMode
                    {
                        id = "Cut"
                    });
                }
                if (flag || EClass.pc.homeBranch.elements.Has(4001))
                {
                    hotbar.SetItem(new HotItemActionMode
                    {
                        id = "Mine"
                    });
                }
                if (flag || EClass.pc.homeBranch.elements.Has(4001))
                {
                    hotbar.SetItem(new HotItemActionMode
                    {
                        id = "Dig"
                    });
                }
                if (flag || EClass.pc.homeBranch.elements.Has(4004))
                {
                    hotbar.SetItem(new HotItemActionMode
                    {
                        id = "Deconstruct"
                    });
                }
                hotbar.SetItem(new HotItemActionMode
                {
                    id = "Terrain"
                });
            }
            hotbar.SetItem(new HotItemActionMode
            {
                id = "ExitBuild"
            });
            break;
        }
        case 4:
        {
            hotbar = SetHobar(4, 9);
            if (!EClass.core.IsGameStarted)
            {
                return;
            }
            FactionBranch factionBranch = ((EClass._zone is Zone_Tent) ? EClass.pc.homeBranch : EClass.Branch);
            if (EClass.debug.godBuild || factionBranch != null)
            {
                hotbar.SetItem(new HotItemActionMode
                {
                    id = "Cinema"
                });
                hotbar.SetItem(new HotItemActionMode
                {
                    id = "FlagCell"
                });
                if (EClass.debug.godBuild || factionBranch.elements.Has(4006))
                {
                    hotbar.SetItem(new HotItemActionMode
                    {
                        id = "Visibility"
                    });
                }
                if (EClass.debug.godBuild)
                {
                    hotbar.SetItem(new HotItemActionMode
                    {
                        id = "EditMarker"
                    });
                }
                if (EClass.debug.godBuild || factionBranch.elements.Has(4005))
                {
                    hotbar.SetItem(new HotItemActionMode
                    {
                        id = "Picker"
                    });
                }
                if (EClass.debug.godBuild)
                {
                    hotbar.SetItem(new HotItemContext
                    {
                        id = "mapTool",
                        autoExpand = false
                    });
                }
            }
            break;
        }
        case 5:
            hotbar = SetHobar(5, 9);
            hotbar.SetItem(new HotItemLayer
            {
                id = "LayerHelp"
            }, 0);
            hotbar.SetItem(new HotItemWidget
            {
                id = "Codex"
            }, 1);
            hotbar.SetItem(new HotItemWidget
            {
                id = "Memo"
            }, 2);
            hotbar.SetItem(new HotItemWidget
            {
                id = "QuestTracker"
            }, 3);
            hotbar.SetItem(new HotItemActionSleep(), 4);
            break;
        case 6:
            hotbar = SetHobar(6, 9);
            break;
        case 7:
            hotbar = SetHobar(7, 7);
            hotbar.SetItem(new HotItemToggle
            {
                type = HotItemToggle.Type.SnapFreepos
            });
            hotbar.SetItem(new HotItemToggle
            {
                type = HotItemToggle.Type.ToggleRoof
            });
            hotbar.SetItem(new HotItemToggle
            {
                type = HotItemToggle.Type.ToggleSlope
            });
            hotbar.SetItem(new HotItemToggle
            {
                type = HotItemToggle.Type.ToggleBuildLight
            });
            break;
        }
        hotbar.actor = widgetHotbar;
        if ((bool)widgetHotbar)
        {
            widgetHotbar.Rebuild();
        }
    }
References EClass._zone, Hotbar.actor, bars, EClass.Branch, Zone.CanEnterBuildModeAnywhere, EClass.core, EClass.debug, FactionBranch.elements, CoreDebug.godBuild, ElementContainer.Has(), Chara.homeBranch, CoreDebug.ignoreBuildRule, Core.IsGameStarted, Spatial.IsRegion, EClass.pc, WidgetHotbar.Rebuild(), SetHobar(), and Hotbar.SetItem().
Referenced by Scene.Init(), OnCreateGame(), WidgetHotbar.OnSetContextMenu(), BuildMenu.Toggle(), and CoreDebug.UpdateInput().
SetHobar()
Hotbar HotbarManager.SetHobar (int id, int slots, WidgetHotbar actor = null) inline
Definition at line 278 of file HotbarManager.cs.
    {
        Hotbar hotbar = new Hotbar();
        hotbar.itemsPerPage = slots;
        bars[id] = hotbar;
        hotbar.AddPage();
        hotbar.AddPage();
        hotbar.id = id;
        return hotbar;
    }
References Hotbar.AddPage(), and bars.
Referenced by ResetHotbar().
Member Data Documentation
bars
Hotbar [] HotbarManager.bars = new Hotbar[8]
Definition at line 6 of file HotbarManager.cs.
Referenced by ResetHotbar(), SetHobar(), and BuildMenu.Toggle().
The documentation for this class was generated from the following file:
Elin/HotbarManager.cs