Elin Decompiled Documentation: LayerRegisterHotbar Class Reference
LayerRegisterHotbar Class Reference
Public Member Functions
void SetItem (SourceElement.Row act)
LayerRegisterHotbar SetItem (Thing t)
void SetItem (Chara c)
LayerRegisterHotbar SetItem (HotItem item)
void Show ()
ButtonHotItem GetButton ()
bool OnEndDrag ()
override void OnKill ()
Public Member Functions inherited from ELayer
override void OnBeforeAddLayer ()
void InitInspector ()
sealed override void Init ()
override void OnAfterAddLayer ()
void TryShowHelp ()
void AddLayerToUI (string id)
void TryShowHint (string _langHint=null)
void TalkHomeMemeber (string id)
void TalkMaid (string id)
override void OnRightClick ()
Public Member Functions inherited from Layer
virtual string GetTextHeader (Window window)
virtual bool HeaderIsListOf (int id)
virtual void Init ()
virtual void OnInit ()
virtual void OnAfterInit ()
virtual void ApplySkin ()
void ShowScreenLock (string id)
void UpdateInput ()
virtual void OnUpdateInput ()
virtual void OnRightClick ()
virtual bool OnBack ()
virtual void OnChangeLayer ()
virtual void OnCreate ()
void _AddLayer (string id)
Layer AddLayer (string id)
T AddLayer< T > ()
T AddLayer< T > (string id)
T AddLayerDontCloseOthers< T > ()
Layer AddLayerDontCloseOthers (Layer l)
T GetOrAddLayer< T > ()
virtual void OnBeforeAddLayer ()
virtual void OnAfterAddLayer ()
Layer AddLayer (Layer l)
void ToggleLayer (string id)
T ToggleLayer< T > (string id=null)
void WaitAndClose ()
void OnClickClose ()
virtual void Close ()
void CloseLayers ()
void RemoveLayers (bool removeImportant=false)
bool RemoveLayer< T > ()
void RemoveLayer (Layer l)
virtual void OnKill ()
Layer SetOnKill (Action action)
void DisableClose ()
void Delay (float duration=0.05f)
Layer SetDelay (float d)
Layer GetLayer (string id)
T GetLayer< T > (bool fromTop=false)
Layer GetTopLayer ()
void SwitchContent (int idWindow, int i)
virtual void OnSwitchContent (Window window)
Layer SetTitles (string langList, string idHeaderRow=null)
bool IsBlockWidgetClick ()
bool IsHideHud ()
bool IsAllowGeneralInput ()
bool IsUseBlur ()
bool IsPointerOnLayer ()
void ApplySkin ()
Public Attributes
Image moldCover
Public Attributes inherited from Layer
Option option
UnityEvent onKill
Anime animeIn
Anime animeOut
bool closeOthers
bool defaultActionMode = true
Button screenLock
Layer parent
string idLayer
List< Layer > layers = new List<Layer>()
Vector2 lastParentPos
List< Window > windows = new List<Window>()
string langHint
Private Attributes
List< WidgetHotbar > hotbars = new List<WidgetHotbar>()
List< Image > covers = new List<Image>()
Additional Inherited Members
Static Public Member Functions inherited from ELayer
static int rnd (int a)
Static Public Member Functions inherited from Layer
static T Create< T > ()
static T Create< T > (string path)
static Layer Create (string path)
Static Public Attributes inherited from Layer
static int skipInput
static bool closeOnRightClick
static bool rightClicked
static bool cancelKeyDown
static bool ignoreSounds
static Transform blurStopInstance
static string[] searchPath = new string[3] { "Layer", "Layer/Dialog", "Layer/LayerHome" }
Protected Member Functions inherited from ELayer
sealed override void _Close ()
sealed override void Kill ()
Protected Member Functions inherited from Layer
virtual void Awake ()
virtual void _Close ()
virtual void Kill ()
Protected Attributes inherited from Layer
RectTransform _rect
bool isDestroyed
Properties inherited from ELayer
static Core core [get]
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static FactionBranch Branch [get]
static Faction Home [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static CoreConfig config [get]
static GameSetting setting [get]
static ColorProfile Colors [get]
static SourceManager sources [get]
static World world [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
bool IsFloat [get]
virtual string IdHelp [get]
Properties inherited from Layer
Layer TopLayer [get]
string uid [get]
virtual RectTransform rectLayers [get]
virtual bool blockWidgetClick [get]
Detailed Description
Definition at line 5 of file LayerRegisterHotbar.cs.
Member Function Documentation
GetButton()
ButtonHotItem LayerRegisterHotbar.GetButton () inline
Definition at line 59 of file LayerRegisterHotbar.cs.
    {
        foreach (WidgetHotbar hotbar in hotbars)
        {
            foreach (ButtonHotItem button in hotbar.buttons)
            {
                if (InputModuleEX.IsPointerOver(button))
                {
                    return button;
                }
            }
        }
        return null;
    }
References WidgetHotbar.buttons, hotbars, and InputModuleEX.IsPointerOver().
Referenced by LayerAbility.OnDrag(), and OnEndDrag().
OnEndDrag()
bool LayerRegisterHotbar.OnEndDrag () inline
Definition at line 74 of file LayerRegisterHotbar.cs.
    {
        ButtonHotItem button = GetButton();
        if ((bool)button)
        {
            button.onClick.Invoke();
            return true;
        }
        return false;
    }
References GetButton().
Referenced by LayerAbility.OnEndDrag().
OnKill()
override void LayerRegisterHotbar.OnKill () inline virtual
Reimplemented from Layer.
Definition at line 85 of file LayerRegisterHotbar.cs.
    {
        foreach (WidgetHotbar hotbar in hotbars)
        {
            hotbar.transform.SetParent(ELayer.ui.widgets.transform, worldPositionStays: false);
        }
        foreach (Image cover in covers)
        {
            Object.DestroyImmediate(cover.gameObject);
        }
        WidgetHotbar.registering = false;
        WidgetHotbar.registeringItem = null;
    }
References covers, hotbars, and ELayer.ui.
SetItem() [1/4]
void LayerRegisterHotbar.SetItem (Chara c) inline
Definition at line 26 of file LayerRegisterHotbar.cs.
    {
        SetItem(new HotItemChara
        {
            uid = c.uid
        });
    }
References SetItem(), and Layer.uid.
SetItem() [2/4]
LayerRegisterHotbar LayerRegisterHotbar.SetItem (HotItem item) inline
Definition at line 34 of file LayerRegisterHotbar.cs.
    {
        WidgetHotbar.registeringItem = item;
        Show();
        return this;
    }
References item, and Show().
SetItem() [3/4]
void LayerRegisterHotbar.SetItem (SourceElement::Row act) inline
Definition at line 13 of file LayerRegisterHotbar.cs.
    {
        SetItem(new HotItemAct
        {
            id = act.id
        });
    }
References SetItem().
Referenced by SetItem().
SetItem() [4/4]
LayerRegisterHotbar LayerRegisterHotbar.SetItem (Thing t) inline
Definition at line 21 of file LayerRegisterHotbar.cs.
    {
        return SetItem(t.trait.GetHotItem());
    }
References Trait.GetHotItem(), SetItem(), and Card.trait.
Show()
void LayerRegisterHotbar.Show () inline
Definition at line 41 of file LayerRegisterHotbar.cs.
    {
        WidgetHotbar.registering = true;
        foreach (Widget item in ELayer.ui.widgets.list)
        {
            WidgetHotbar widgetHotbar = item as WidgetHotbar;
            if (!(widgetHotbar == null) && widgetHotbar.CanRegisterItem && !widgetHotbar.hotbar.IsLocked)
            {
                if (!widgetHotbar.Visible)
                {
                    widgetHotbar.ToggleVisible();
                }
                widgetHotbar.transform.SetParent(base.transform, worldPositionStays: false);
                hotbars.Add(widgetHotbar);
            }
        }
    }
References WidgetHotbar.CanRegisterItem, WidgetHotbar.hotbar, hotbars, Hotbar.IsLocked, item, WidgetHotbar.ToggleVisible(), ELayer.ui, and WidgetHotbar.Visible.
Referenced by SetItem().
Member Data Documentation
covers
List<Image> LayerRegisterHotbar.covers = new List<Image>() private
Definition at line 11 of file LayerRegisterHotbar.cs.
Referenced by OnKill().
hotbars
List<WidgetHotbar> LayerRegisterHotbar.hotbars = new List<WidgetHotbar>() private
Definition at line 9 of file LayerRegisterHotbar.cs.
Referenced by GetButton(), OnKill(), and Show().
moldCover
Image LayerRegisterHotbar.moldCover
Definition at line 7 of file LayerRegisterHotbar.cs.
The documentation for this class was generated from the following file:
Elin/LayerRegisterHotbar.cs