Elin Decompiled Documentation: AI_PlayMusic Class Reference
AI_PlayMusic Class Reference
Public Member Functions
override IEnumerable< Status > Run ()
void Evaluate (bool success)
void ThrowReward (Chara c, bool punish)
override void OnCancel ()
Public Member Functions inherited from AIAct
override string ToString ()
override MultiSprite GetStateIcon ()
virtual bool ShouldAllyAttack (Chara tg)
virtual Point GetDestination ()
AIProgress GetProgress ()
string GetCurrentActionText ()
override bool IsToolValid ()
virtual void OnStart ()
void SetOwner (Chara c)
virtual void OnSetOwner ()
void SetChild (AIAct seq, Func< Status > _onChildFail=null)
void Start ()
override bool Perform ()
Status Restart ()
Status Success (Action action=null)
virtual void OnSuccess ()
bool TryCancel (Card c)
virtual Status Cancel ()
virtual void OnCancel ()
virtual void OnCancelOrSuccess ()
virtual bool CanManualCancel ()
Status KeepRunning ()
void Reset ()
virtual void OnReset ()
Status Tick ()
virtual IEnumerable< Status > Run ()
Status TickChild ()
Status Do (AIAct _seq, Func< Status > _onChildFail=null)
Status DoGotoInteraction (Point pos, Func< Status > _onChildFail=null)
Status DoGoto (Point pos, int dist=0, bool ignoreConnection=false, Func< Status > _onChildFail=null)
Status DoGoto (Card card, Func< Status > _onChildFail=null)
Status DoGoto (Card card, int dist, Func< Status > _onChildFail=null)
Status DoGotoSpot (Card card, Func< Status > _onChildFail=null)
Status DoGoto< T > (Func< Status > _onChildFail=null)
Status DoGotoSpot< T > (Func< Status > _onChildFail=null, bool ignoreAccessType=false)
Status DoGrab (Card card, int num=-1, bool pickHeld=false, Func< Status > _onChildFail=null)
Status DoGrab< T > ()
Status DoProgress ()
Status DoIdle (int repeat=3)
Status DoWait (int count=1)
virtual AIProgress CreateProgress ()
virtual void OnCreateProgress (Progress_Custom p)
virtual bool CanProgress ()
virtual void OnBeforeProgress ()
virtual void OnProgress ()
virtual void OnProgressComplete ()
void SimulateZone (int days)
virtual void OnSimulateZone (int days)
virtual void OnSimulatePosition ()
Public Member Functions inherited from Act
virtual CursorInfo GetCursorIcon (Card c)
virtual MultiSprite GetStateIcon ()
override Sprite GetSprite ()
virtual bool ShowMouseHint (Card c)
virtual bool IsValidTC (Card c)
virtual string GetHintText (string str="")
virtual string GetText (string str="")
virtual string GetTextSmall (Card c)
bool IsTargetHostileParty ()
virtual Color GetActPlanColor ()
virtual bool Perform ()
virtual bool CanPerform ()
bool Perform (Chara _cc, Card _tc=null, Point _tp=null)
bool CanPerform (Chara _cc, Card _tc=null, Point _tp=null)
virtual bool IsToolValid ()
new void SetImage (Image image)
virtual void OnMarkMapHighlights ()
virtual bool ShouldMapHighlight (Point p)
Public Member Functions inherited from Element
virtual SourceElement.Row GetSource ()
virtual int GetSourcePotential (int v)
virtual Sprite GetSprite ()
int GetMaterialSourceValue (Thing t, int v)
virtual long GetSourceValue (long v, int lv, SourceValueType type)
virtual Sprite GetIcon (string suffix="")
bool IsActive (Card c)
int SortVal (bool charaSheet=false)
virtual bool CanLink (ElementContainer owner)
bool HasTag (string tag)
void SetImage (Image i)
virtual string GetDetail ()
bool IsFactionElement (Chara c)
Element GetParent (Card c)
void WriteNote (UINote n, ElementContainer owner=null, Action< UINote > onWriteNote=null)
void WriteNoteWithRef (UINote n, ElementContainer owner, Action< UINote > onWriteNote, Element refEle)
void _WriteNote (UINote n, Chara c, Act act)
void AddHeaderAbility (UINote n)
void _WriteNote (UINote n, ElementContainer owner, Action< UINote > onWriteNote, bool isRef, bool addHeader=true)
void AddEncNote (UINote n, Card Card, ElementContainer.NoteMode mode=ElementContainer.NoteMode.Default, Func< Element, string, string > funcText=null, Action< UINote, Element > onAddNote=null)
virtual void OnWriteNote (UINote n, ElementContainer owner)
virtual void OnChangeValue ()
void CheckLevelBonus (ElementContainer owner, UINote n=null)
int GetSortVal (UIList.SortMode m)
virtual Act.Cost GetCost (Chara c)
virtual int GetPower (Card c)
virtual void SetTextValue (UIText text)
virtual bool IsPurchaseFeatReqMet (ElementContainer owner, int lv=-1)
virtual void WritePurchaseReq (UINote n, int lv=1)
Static Public Member Functions
static void CancelKeepPlaying ()
Static Public Member Functions inherited from Act
static void SetReference (Chara _cc, Card _tc=null, Point _tp=null)
static void SetTool (Thing t)
Static Public Member Functions inherited from Element
static string GetName (string alias)
static SourceElement.Row Get (int id)
static Dictionary< int, int > GetElementMap (int[] list)
static Dictionary< int, int > GetElementMap (int[] list, Dictionary< int, int > map)
static SourceElement.Row GetRandomElement (int lv=1, bool useWeight=true)
static Element Create (int id, int v=0)
static Element Create (string id, int v=1)
static int GetId (string alias)
static int GetResistLv (int v)
static int GetResistDamage (int dmg, int v, int power=0)
Static Public Member Functions inherited from EClass
static int rndSeed (int a, int seed)
static int rnd (long a)
static int rnd (int a)
static int curve (int _a, int start, int step, int rate=75)
static int sqrt (int a)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Public Attributes
Thing tool
PlayingSong playing
int score
int gold
int toolLv
Public Attributes inherited from AIAct
new Chara owner
Status status
IEnumerator< Status > Enumerator
AIAct child
AIAct parent
byte restartCount
Func< Status > onChildFail
Func< bool > isFail
Public Attributes inherited from Element
SourceElement.Row _source
int id
int vBase
int vExp
int vPotential
int vTempPotential
int vLink
int vSource
int vSourcePotential
ElementContainer owner
Static Public Attributes
static bool keepPlaying
static Thing playingTool
static bool ignoreDamage
Static Public Attributes inherited from Act
static Chara CC
static Card TC
static Point TP = new Point()
static Thing TOOL
static int powerMod = 100
static bool forcePt
static Act CurrentAct
Static Public Attributes inherited from Element
const int Div = 5
static Element Void = new Element()
static int[] List_MainAttributes = new int[9] { 70, 72, 71, 77, 74, 75, 76, 73, 79 }
static int[] List_MainAttributesMajor = new int[8] { 70, 72, 71, 77, 74, 75, 76, 73 }
static int[] List_Body = new int[4] { 70, 72, 71, 77 }
static int[] List_Mind = new int[4] { 74, 75, 76, 73 }
static List< SourceElement.Row > ListElements = new List<SourceElement.Row>()
static List< SourceElement.Row > ListAttackElements = new List<SourceElement.Row>()
Static Public Attributes inherited from EClass
static Core core
Properties
override bool ShowProgress [get]
override bool CancelWhenDamaged [get]
override TargetType TargetType [get]
Properties inherited from AIAct
virtual bool IsRunning [get]
bool IsChildRunning [get]
bool IsMoveAI [get]
virtual int MaxRestart [get]
virtual new string Name [get]
virtual MultiSprite stateIcon [get]
virtual Sprite actionIcon [get]
virtual bool IsNoGoal [get]
virtual bool IsAutoTurn [get]
virtual bool IsIdle [get]
virtual bool CancelOnAggro [get]
virtual bool PushChara [get]
virtual int MaxProgress [get]
virtual bool ShowProgress [get]
virtual bool UseTurbo [get]
virtual int CurrentProgress [get]
virtual bool ShowCursor [get]
virtual bool CancelWhenDamaged [get]
virtual bool CancelWhenMoved [get]
virtual bool InformCancel [get]
virtual Thing RenderThing [get]
AIAct Current [get]
override bool IsAct [get]
override bool ShowPotential [get]
override bool UsePotential [get]
override bool ShowRelativeAttribute [get]
virtual bool HasProgress [get]
Properties inherited from Act
override bool ShowPotential [get]
override bool UsePotential [get]
override bool ShowRelativeAttribute [get]
virtual CursorInfo CursorIcon [get]
virtual string ID [get]
virtual bool IsAct [get]
virtual bool WillEndTurn [get]
virtual bool CloseLayers [get]
virtual int LeftHand [get]
virtual int RightHand [get]
virtual int ElementPowerMod [get]
virtual bool ShowMapHighlight [get]
virtual bool ShowMapHighlightBlock [get]
virtual bool PickHeldOnStart [get]
virtual bool DropHeldOnStart [get]
virtual bool CanPressRepeat [get]
virtual bool CanAutofire [get]
virtual bool ResetAxis [get]
virtual bool RequireTool [get]
virtual bool IsHostileAct [get]
virtual bool HideRightInfo [get]
virtual bool HaveLongPressAction [get]
virtual float Radius [get]
virtual int PerformDistance [get]
virtual int MaxRadius [get]
virtual TargetType TargetType [get]
virtual bool LocalAct [get]
virtual bool CanRapidFire [get]
virtual float RapidDelay [get]
virtual bool ShowAuto [get]
virtual bool IsCrime [get]
Properties inherited from Element
SourceElement.Row source [get]
virtual int DisplayValue [get]
virtual int MinValue [get]
int Value [get]
int ValueWithoutLink [get]
virtual int MinPotential [get]
int Potential [get]
virtual bool CanGainExp [get]
bool IsFlag [get]
virtual string Name [get]
virtual string FullName [get]
virtual int ExpToNext [get]
virtual bool UseExpMod [get]
virtual int CostTrain [get]
virtual int CostLearn [get]
virtual bool ShowXP [get]
virtual bool ShowMsgOnValueChanged [get]
virtual bool ShowValue [get]
virtual bool ShowPotential [get]
virtual bool UsePotential [get]
virtual bool PotentialAsStock [get]
virtual bool ShowRelativeAttribute [get]
virtual bool ShowBonuses [get]
virtual string ShortName [get]
bool IsGlobalElement [get]
bool IsFactionWideElement [get]
bool IsPartyWideElement [get]
virtual bool ShowEncNumber [get]
bool IsTrait [get]
bool IsFoodTrait [get]
bool IsFoodTraitMain [get]
bool IsMainAttribute [get]
Act act [get]
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Additional Inherited Members
Public Types inherited from AIAct
enum Status { Running , Fail , Success }
Public Types inherited from Act
enum CostType { None , MP , SP }
Detailed Description
Definition at line 6 of file AI_PlayMusic.cs.
Member Function Documentation
CancelKeepPlaying()
static void AI_PlayMusic.CancelKeepPlaying () inline static
Definition at line 40 of file AI_PlayMusic.cs.
    {
        if (keepPlaying)
        {
            SE.CancelAction();
            keepPlaying = false;
            playingTool = null;
        }
    }
References keepPlaying, and playingTool.
Referenced by AM_Adv._OnUpdateInput(), and Scene.OnUpdate().
Evaluate()
void AI_PlayMusic.Evaluate (bool success) inline
Definition at line 426 of file AI_PlayMusic.cs.
    {
        if (owner == null || !owner.IsPC)
        {
            return;
        }
        if (success)
        {
            score = score * 110 / 100;
        }
        else
        {
            score = score / 2 - 20;
        }
        int num = Mathf.Clamp(score / 20 + 1, 0, 9);
        owner.Say(Lang.GetList("music_result")[num]);
        if (gold > 0)
        {
            owner.Say("music_reward", owner, gold.ToString() ?? "");
        }
        if (EClass.rnd(3) != 0)
        {
            owner.stamina.Mod(-1);
        }
        QuestMusic questMusic = EClass.game.quests.Get<QuestMusic>();
        if (questMusic != null)
        {
            questMusic.score += score;
            questMusic.sumMoney += gold;
            int num2 = num / 2 - 1;
            if (num > 0)
            {
                SE.Play("clap" + num2);
            }
        }
    }
References EClass.game, QuestManager.Get(), Lang.GetList(), Game.quests, and EClass.rnd().
Referenced by Run().
OnCancel()
override void AI_PlayMusic.OnCancel () inline virtual
Reimplemented from AIAct.
Definition at line 592 of file AI_PlayMusic.cs.
    {
        if (playing != null && (bool)playing.bgm)
        {
            playing.bgm.song.Fail(playing.source, playing.bgm);
            if ((bool)UISong.Instance)
            {
                UISong.Instance.Kill();
            }
            playing.source = null;
            SoundManager.jingleTimer = 1f;
        }
        Evaluate(success: false);
    }
References PlayingSong.bgm, UISong.Instance, UISong.Kill(), and PlayingSong.source.
Run()
override IEnumerable< Status > AI_PlayMusic.Run () inline virtual
Reimplemented from AIAct.
Definition at line 50 of file AI_PlayMusic.cs.
    {
        if (tool == null)
        {
            tool = (owner.IsPC ? owner.Tool : owner.things.Find<TraitToolMusic>());
        }
        if (tool == null && !owner.IsPCFaction && EClass.rnd(20) == 0)
        {
            tool = owner.AddThing(ThingGen.Create("lute"));
        }
        if (tool == null)
        {
            yield return Cancel();
        }
        if (tool.parent is Zone)
        {
            yield return DoGoto(tool.pos, tool.pos.IsBlocked ? 1 : 0);
        }
        if (owner.IsPC && EClass.game.config.preference.keepPlayingMusic)
        {
            keepPlaying = true;
            playingTool = tool;
            EInput.Consume(consumeAxis: true, 10);
        }
        toolLv = 1;
        string idSong = null;
        KnownSong song = null;
        playing = null;
        score = 40;
        gold = 0;
        if (owner.IsPC && EClass.player.playingSong != null && EClass.player.playingSong.idTool == tool.id)
        {
            playing = EClass.player.playingSong;
            idSong = EClass.player.playingSong.id;
            song = EClass.player.knownSongs[EClass.player.playingSong.id];
        }
        if (playing == null)
        {
            switch (tool.id)
            {
            case "sax":
            case "trumpet":
                idSong = "trumpet_practice";
                break;
            case "piano_gould":
                idSong = "piano_gould";
                break;
            case "piano_killkill":
            case "piano2":
                idSong = "piano_neko";
                break;
            case "piano":
                idSong = "piano_kanon";
                break;
            case "harpsichord":
                idSong = "harpsichord_goldberg";
                break;
            case "guitar_ash":
                idSong = "guitar_caccini";
                break;
            case "guitar_efrond":
                idSong = "guitar_dusk";
                break;
            case "guitar":
                idSong = "guitar_air";
                break;
            case "harp":
                idSong = "harp_komori";
                break;
            case "shield_lute":
            case "lute":
                idSong = "guitar_sad";
                break;
            case "recorder":
                idSong = "recorder";
                break;
            case "flute":
                idSong = "flute";
                break;
            case "taiko":
            case "drum":
                idSong = "taiko";
                break;
            case "mokugyo":
                idSong = "mokugyo";
                break;
            case "tambourine":
                idSong = "tambourine";
                break;
            case "mic":
                idSong = "mic_rachmaninoff";
                break;
            case "cello":
                idSong = "cello_prelude";
                break;
            case "koto":
                idSong = "koto";
                break;
            case "instrument_violin":
            case "panty":
                idSong = "violin_chaconne";
                break;
            case "stradivarius":
                idSong = "violin_furusato";
                break;
            default:
                idSong = "violin_chaconne";
                break;
            }
            if (owner.IsPC && EClass.player.knownSongs.ContainsKey(idSong))
            {
                song = EClass.player.knownSongs[idSong];
            }
            if (song == null)
            {
                song = new KnownSong();
                if (owner.IsPC)
                {
                    EClass.player.knownSongs[idSong] = song;
                }
            }
            playing = new PlayingSong
            {
                id = idSong,
                idTool = tool.id
            };
            if (owner.IsPC)
            {
                EClass.player.playingSong = playing;
            }
        }
        if (owner.IsPC)
        {
            (EClass.Sound.GetData("Instrument/" + idSong) as BGMData).song.index = playing.index;
        }
        if (Application.isEditor && owner.IsPC)
        {
            song.lv += 10;
            Debug.Log(song.lv);
        }
        List<Chara> reacted = new List<Chara>();
        Progress_Custom progress = new Progress_Custom
        {
            maxProgress = 15,
            cancelWhenMoved = false,
            showProgress = false,
            canProgress = () => tool != null && !tool.isDestroyed,
            onProgressBegin = delegate
            {
                owner.Say("music_start", owner, tool);
                owner.ShowEmo(Emo.happy, 3f, skipSame: false);
                if (tool != null && tool.ExistsOnMap)
                {
                    owner.LookAt(tool);
                }
                owner.PlayAnime(AnimeID.PlayMusic);
                if (owner.IsPC)
                {
                    bool flag = false;
                    if (playing.mistakes == 0 && (bool)playing.source && playing.source.isPlaying && playing.source.data.name == idSong)
                    {
                        SoundSource soundSource = playing.source;
                        if (Mathf.Abs(soundSource.source.time - (soundSource.data as BGMData).song.parts[playing.index].start) < 2f && playing.source.source.volume >= 0.1f)
{
                            soundSource.KeepPlay();
                            flag = true;
                            Debug.Log("keep:" + soundSource.source.time);
                        }
                        else
{
                            EClass.Sound.Stop(soundSource.data, 0.1f);
                        }
                        Debug.Log(playing.source);
                    }
                    if (!flag)
                    {
                        playing.source = owner.PlaySound("Instrument/" + idSong);
                        Debug.Log(playing.source);
                    }
                    playing.bgm = playing.source.data as BGMData;
                    BGMData.Part part = playing.bgm.song.parts[playing.index];
                    if (!UISong.Instance)
                    {
                        Util.Instantiate<UISong>("UI/Util/UISong", EClass.ui.rectDynamicEssential);
                    }
                    UISong.Instance.SetSong(playing.source, playing.bgm, part);
                    if (EClass.Sound.currentBGM != null)
                    {
                        float num3 = 0.5f - 0.1f * (float)playing.index;
                        if (num3 < 0f)
{
                            num3 = 0f;
                        }
                        if (EClass.Sound.sourceBGM.volume > EClass.Sound.currentBGM.data.volume * num3)
{
                            EClass.Sound.sourceBGM.DOFade(EClass.Sound.currentBGM.data.volume * num3, 3f);
                        }
                        SoundManager.jingleTimer = part.duration / playing.bgm.pitch + playing.bgm.song.fadeIn + 2f;
                    }
                }
            },
            onProgress = delegate(Progress_Custom p)
            {
                Msg.SetColor(Msg.colors.Ono);
                owner.Say(Lang.GetList("music").RandomItem());
                Msg.SetColor();
                if (tool.id == "tambourine")
                {
                    Msg.Say("tambourine");
                }
                if (EClass.debug.enable && EClass.pc.job.id == "pianist")
                {
                    song.lv = 10000;
                }
                if (p.progress > 2 && (EClass.rnd(100 + 50 * owner.Evalue(1405)) == 0 || EClass.rnd(4 + (int)MathF.Max(0f, song.lv - playing.index * 25 - playing.index * playing.index / 2)) == 0))
                {
                    playing.mistakes++;
                    if (EClass.rnd(2) == 0)
                    {
                        LevelSong(2 + 2 * EClass.rnd(owner.Evalue(1405) + 1));
                    }
                    if (playing.mistakes >= 10)
                    {
                        playing.index = 0;
                    }
                    Cancel();
                }
                else
                {
                    foreach (Chara item in EClass._map.ListCharasInCircle(owner.pos, 4f))
                    {
                        if (item.conSleep != null && item.ResistLv(957) <= 0)
{
                            item.conSleep.Kill();
                            item.ShowEmo(Emo.angry);
                        }
                    }
                    List<Chara> list = owner.pos.ListWitnesses(owner, 4, WitnessType.music);
                    int num = (owner.Evalue(241) + tool?.Evalue(241)).Value * (100 + toolLv) / 100;
                    int num2 = 0;
                    foreach (Chara item2 in list)
                    {
                        if (owner == null)
{
                            break;
                        }
                        if (!reacted.Contains(item2) && EClass.rnd(5) == 0)
{
                            if (tool != null)
{
                                foreach (Element value in tool.elements.dict.Values)
{
                                    if (value.id == 489 && EClass.rnd(8) == 0)
{
                                        item2.AddCondition<ConDrunk>();
                                    }
                                    if (value.source.categorySub == "eleAttack")
{
                                        item2.ApplyElementEffect(value, value.Value * 10, owner, checkHostileAct: true);
                                    }
                                }
                            }
                            if (owner.IsPCParty)
{
                                if (item2.interest <= 0 || (EClass._zone is Zone_Music && (item2.IsPCFaction || item2.IsPCFactionMinion)))
{
                                    continue;
                                }
                                if (!item2.isDrunk)
{
                                    item2.interest -= EClass.rnd(10);
                                    if (item2.interest < 0)
{
                                        item2.Talk("musicBored");
                                        continue;
                                    }
                                }
                            }
                            if (EClass.rnd(num2 * num2) <= 30 && item2.pos.FirstChara == item2)
{
                                bool isMinion = item2.IsMinion;
                                p.cancelWhenDamaged = false;
                                if (num < item2.LV && EClass.rnd(2) == 0)
{
                                    reacted.Add(item2);
                                    if (!isMinion)
{
                                        score -= item2.LV / 2 - 10;
                                    }
                                    if (EClass.rnd(2) == 0)
{
                                        item2.Talk("musicBad");
                                    }
                                    else
{
                                        item2.Say("musicBad", item2, owner);
                                    }
                                    item2.ShowEmo(Emo.sad);
                                    owner.elements.ModExp(241, 10f);
                                    if (EClass.rnd(5) == 0)
{
                                        ThrowReward(item2, punish: true);
                                    }
                                    num2++;
                                }
                                else if (EClass.rnd(num + 5) > EClass.rnd(item2.LV * 5 + 1))
{
                                    reacted.Add(item2);
                                    if (!isMinion)
{
                                        score += EClass.rnd(item2.LV / 2 + 5) + 5;
                                    }
                                    if (EClass.rnd(2) == 0)
{
                                        item2.Talk("musicGood");
                                    }
                                    else
{
                                        item2.Say("musicGood", item2, owner);
                                    }
                                    item2.ShowEmo(Emo.happy);
                                    item2.renderer.PlayAnime((EClass.rnd(2) == 0) ? AnimeID.Jump : AnimeID.Fishing);
                                    owner.elements.ModExp(241, EClass._zone.IsUserZone ? 10 : 50);
                                    if (!isMinion)
{
                                        ThrowReward(item2, punish: false);
                                    }
                                    num2++;
                                }
                                p.cancelWhenDamaged = true;
                            }
                        }
                    }
                    if (owner != null && owner.IsPC && EClass.rnd(80) < num2)
                    {
                        owner.stamina.Mod(-1);
                    }
                }
            },
            onProgressComplete = delegate
            {
                if (EClass.rnd(2) == 0)
                {
                    LevelSong(2);
                }
                if ((bool)playing.bgm)
                {
                    playing.index++;
                    playing.mistakes = 0;
                    if (playing.index >= playing.bgm.song.parts.Count)
                    {
                        playing.index = 0;
                    }
                    playing.bgm.song.index = playing.index;
                }
                Evaluate(success: true);
            }
        }.SetDuration(26);
        yield return Do(progress);
        if (progress.status == Status.Fail)
        {
            yield return Cancel();
        }
        void LevelSong(int a)
        {
            if (a > 0)
            {
                song.lv += a + EClass.rnd(2);
                if (owner == EClass.pc)
                {
                    Msg.Say("level_song");
                }
            }
        }
    }
References EClass._map, EClass._zone, Chara.AddCondition(), Card.AddThing(), Card.ApplyElementEffect(), PlayingSong.bgm, AIAct.Cancel(), Msg.colors, Game.config, EInput.Consume(), ThingGen.Create(), EClass.debug, Debug, ElementContainer.dict, AIAct.DoGoto(), Card.elements, CoreDebug.enable, Evaluate(), Card.Evalue(), Card.ExistsOnMap, ThingContainer.Find(), EClass.game, Lang.GetList(), gold, Card.id, Element.id, PlayingSong.id, PlayingSong.idTool, if(), PlayingSong.index, UISong.Instance, Chara.interest, Point.IsBlocked, Card.isDestroyed, Chara.isDrunk, Chara.IsMinion, Chara.IsPC, Chara.IsPCFaction, Chara.IsPCFactionMinion, Chara.IsPCParty, Zone.IsUserZone, item, Chara.job, keepPlaying, ConfigPreference.keepPlayingMusic, Player.knownSongs, Map.ListCharasInCircle(), Point.ListWitnesses(), Chara.LookAt(), Card.LV, KnownSong.lv, PlayingSong.mistakes, Stats.Mod(), ElementContainer.ModExp(), MsgColors.Ono, AIAct.owner, Card.parent, EClass.pc, CardRenderer.PlayAnime(), Card.PlayAnime(), EClass.player, playing, Player.playingSong, playingTool, Card.PlaySound(), Card.pos, Game.Config.preference, AIProgress.progress, Card.renderer, EClass.rnd(), Msg.Say(), Card.Say(), score, Msg.SetColor(), UISong.SetSong(), Card.ShowEmo(), EClass.Sound, Element.source, PlayingSong.source, Chara.stamina, Card.Talk(), Card.things, ThrowReward(), tool, toolLv, EClass.ui, Util, and Element.Value.
ThrowReward()
void AI_PlayMusic.ThrowReward (Chara c, bool punish) inline
Definition at line 463 of file AI_PlayMusic.cs.
    {
        Thing thing = null;
        string text = "";
        int num = 1;
        bool flag = true;
        if (punish)
        {
            text = ((EClass.rnd(5) == 0) ? "rock" : "pebble");
            if (EClass.rnd(8) == 0)
            {
                text = ((EClass.rnd(3) == 0) ? "water_dirty" : "water");
            }
            if (!c.IsPCFactionOrMinion)
            {
                thing = c.TryGetThrowable()?.Split(1);
            }
        }
        else if (EClass.rnd(100) == 0 && !EClass._zone.IsUserZone)
        {
            text = "ecopo";
            if (EClass.rnd(4) == 0)
            {
                text = "gacha_coin";
            }
            if (EClass.rnd(4) == 0)
            {
                text = "plat";
            }
            if (EClass.rnd(3) == 0)
            {
                text = "tomato";
            }
            if (EClass.rnd(3) == 0)
            {
                text = "casino_coin";
            }
            if (owner.IsPC && !EClass._zone.IsInstance)
            {
                if (c.LV >= 20 && EClass.rnd(10 * (int)Mathf.Pow(2f, EClass.player.flags.reward_killkill + 1)) == 0)
                {
                    text = "piano_killkill";
                    punish = true;
                    flag = false;
                    EClass.player.flags.reward_killkill++;
                }
                else if (c.LV >= 40 && EClass.rnd(10 * (int)Mathf.Pow(2f, EClass.player.flags.reward_gould + 1)) == 0)
                {
                    text = "piano_gould";
                    punish = true;
                    flag = false;
                    EClass.player.flags.reward_gould++;
                }
            }
        }
        else
        {
            num = (EClass.rnd(c.LV * 2 + 1) + 1) * (100 + toolLv * 2 + owner.Evalue(1405) * 10) / 100;
            if (c.IsUnique)
            {
                num *= 2;
            }
            if (!(EClass._zone is Zone_Music))
            {
                if (num > 25)
                {
                    num /= 2;
                }
                if (num > 50)
                {
                    num /= 2;
                }
                if (num > 100)
                {
                    num /= 2;
                }
                if (EClass._zone.IsUserZone)
                {
                    num /= 5;
                }
            }
            if (num < 1)
            {
                num = 1;
            }
            gold += num;
            text = "money";
        }
        if (!owner.IsPCParty && !punish && text != "money")
        {
            return;
        }
        if (thing == null)
        {
            thing = ThingGen.Create(text).SetNum(num);
        }
        ignoreDamage = true;
        ActThrow.Throw(c, owner.pos, thing, (!punish) ? ThrowMethod.Reward : ThrowMethod.Punish);
        ignoreDamage = false;
        if (owner == null || !thing.ExistsOnMap)
        {
            return;
        }
        if (!owner.IsPC && owner.things.IsFull())
        {
            thing.Destroy();
        }
        else
        {
            if (!owner.IsAliveInCurrentZone)
            {
                return;
            }
            if (flag)
            {
                owner.Pick(thing);
            }
            if (thing.id == "money" && !owner.IsPC)
            {
                int? obj = ((owner.Evalue(241) + tool?.Evalue(241)) * 10 + 100) / ((owner.IsPCFaction && owner.memberType == FactionMemberType.Default) ? 1 : 10);
                if (owner.GetCurrency() - obj > 0)
                {
                    owner.c_allowance += num;
                    owner.ModCurrency(-num);
                }
            }
        }
    }
References EClass._zone, ThingGen.Create(), Card.Destroy(), Card.ExistsOnMap, Player.flags, Card.id, Zone.IsInstance, Card.IsPCFactionOrMinion, Card.IsUnique, Zone.IsUserZone, Card.LV, EClass.player, Card.pos, Player.Flags.reward_gould, Player.Flags.reward_killkill, EClass.rnd(), Card.SetNum(), Card.Split(), ActThrow.Throw(), tool, and Chara.TryGetThrowable().
Referenced by Run().
Member Data Documentation
gold
int AI_PlayMusic.gold
Definition at line 20 of file AI_PlayMusic.cs.
Referenced by Run().
ignoreDamage
bool AI_PlayMusic.ignoreDamage static
Definition at line 14 of file AI_PlayMusic.cs.
keepPlaying
bool AI_PlayMusic.keepPlaying static
Definition at line 8 of file AI_PlayMusic.cs.
Referenced by AM_Adv._OnUpdateInput(), CancelKeepPlaying(), Scene.OnUpdate(), and Run().
playing
PlayingSong AI_PlayMusic.playing
Definition at line 16 of file AI_PlayMusic.cs.
Referenced by Run().
playingTool
Thing AI_PlayMusic.playingTool static
Definition at line 10 of file AI_PlayMusic.cs.
Referenced by AM_Adv._OnUpdateInput(), CancelKeepPlaying(), and Run().
score
int AI_PlayMusic.score
Definition at line 18 of file AI_PlayMusic.cs.
Referenced by Run().
tool
Thing AI_PlayMusic.tool
Definition at line 12 of file AI_PlayMusic.cs.
Referenced by Run().
toolLv
int AI_PlayMusic.toolLv
Definition at line 22 of file AI_PlayMusic.cs.
Referenced by Run().
Property Documentation
CancelWhenDamaged
override bool AI_PlayMusic.CancelWhenDamaged get
Definition at line 26 of file AI_PlayMusic.cs.
ShowProgress
override bool AI_PlayMusic.ShowProgress get
Definition at line 24 of file AI_PlayMusic.cs.
TargetType
override TargetType AI_PlayMusic.TargetType get
Definition at line 28 of file AI_PlayMusic.cs.
    {
        get
        {
            if (tool != null && tool != EClass.pc.Tool)
            {
                return TargetType.Any;
            }
            return TargetType.Self;
        }
    }
The documentation for this class was generated from the following file:
Elin/AI_PlayMusic.cs