Elin Decompiled Documentation: SourceZoneAffix Class Reference
SourceZoneAffix Class Reference
Classes
class Row
Public Member Functions
override Row CreateRow ()
override Row CreateRowByMapping (IReadOnlyDictionary< string, int > mapping)
override void SetRow (Row r)
override IReadOnlyDictionary< string, int > GetRowMapping ()
override IReadOnlyDictionary< string, string > GetTypeMapping ()
Public Member Functions inherited from SourceDataInt< SourceZoneAffix.Row >
override T GetRow (string id)
Static Public Attributes
static readonly IReadOnlyDictionary< string, int > RowMapping
static readonly IReadOnlyDictionary< string, string > TypeMapping
Detailed Description
Definition at line 4 of file SourceZoneAffix.cs.
Member Function Documentation
CreateRow()
override Row SourceZoneAffix.CreateRow () inline
Definition at line 60 of file SourceZoneAffix.cs.
    {
        return new Row
        {
            id = SourceData.GetInt(0),
            zone = SourceData.GetString(1),
            name_JP = SourceData.GetString(2),
            name = SourceData.GetString(3),
            textAssign_JP = SourceData.GetString(4),
            textAssign = SourceData.GetString(5),
            detail_JP = SourceData.GetString(6),
            detail = SourceData.GetString(7)
        };
    }
References SourceData< T, T2 >.GetInt(), and SourceData< T, T2 >.GetString().
CreateRowByMapping()
override Row SourceZoneAffix.CreateRowByMapping (IReadOnlyDictionary< string, int > mapping) inline
Definition at line 75 of file SourceZoneAffix.cs.
    {
        return new Row
        {
            id = SourceData.GetInt(mapping["id"]),
            zone = SourceData.GetString(mapping["zone"]),
            name_JP = SourceData.GetString(mapping["name_JP"]),
            name = SourceData.GetString(mapping["name"]),
            textAssign_JP = SourceData.GetString(mapping["textAssign_JP"]),
            textAssign = SourceData.GetString(mapping["textAssign"]),
            detail_JP = SourceData.GetString(mapping["detail_JP"]),
            detail = SourceData.GetString(mapping["detail"])
        };
    }
References SourceData< T, T2 >.GetInt(), and SourceData< T, T2 >.GetString().
GetRowMapping()
override IReadOnlyDictionary< string, int > SourceZoneAffix.GetRowMapping () inline
Definition at line 95 of file SourceZoneAffix.cs.
    {
        return RowMapping;
    }
References RowMapping.
GetTypeMapping()
override IReadOnlyDictionary< string, string > SourceZoneAffix.GetTypeMapping () inline
Definition at line 100 of file SourceZoneAffix.cs.
    {
        return TypeMapping;
    }
References TypeMapping.
SetRow()
override void SourceZoneAffix.SetRow (Row r) inline
Definition at line 90 of file SourceZoneAffix.cs.
    {
        map[r.id] = r;
    }
References SourceZoneAffix.Row.id.
Member Data Documentation
RowMapping
readonly IReadOnlyDictionary<string, int> SourceZoneAffix.RowMapping static
Initial value:
= new Dictionary<string, int>
    {
        ["id"] = 0,
        ["zone"] = 1,
        ["name_JP"] = 2,
        ["name"] = 3,
        ["textAssign_JP"] = 4,
        ["textAssign"] = 5,
        ["detail_JP"] = 6,
        ["detail"] = 7
    }
Definition at line 36 of file SourceZoneAffix.cs.
Referenced by GetRowMapping().
TypeMapping
readonly IReadOnlyDictionary<string, string> SourceZoneAffix.TypeMapping static
Initial value:
= new Dictionary<string, string>
    {
        ["id"] = "int",
        ["zone"] = "string",
        ["name_JP"] = "string",
        ["name"] = "string",
        ["textAssign_JP"] = "string",
        ["textAssign"] = "string",
        ["detail_JP"] = "string",
        ["detail"] = "string"
    }
Definition at line 48 of file SourceZoneAffix.cs.
Referenced by GetTypeMapping().
The documentation for this class was generated from the following file:
Elin/SourceZoneAffix.cs