Elin Decompiled Documentation: LayerHome Class Reference
LayerHome Class Reference
Public Member Functions
override bool HeaderIsListOf (int id)
override void OnInit ()
override void OnSwitchContent (Window window)
void RefreshChronicle ()
void RefreshTech (bool listComplete=false)
void RefreshFocus ()
void RefreshFeat ()
void RefreshAreas ()
void RefreshSpots ()
Public Member Functions inherited from ELayer
override void OnBeforeAddLayer ()
void InitInspector ()
sealed override void Init ()
override void OnAfterAddLayer ()
void TryShowHelp ()
void AddLayerToUI (string id)
void TryShowHint (string _langHint=null)
void TalkHomeMemeber (string id)
void TalkMaid (string id)
override void OnRightClick ()
Public Member Functions inherited from Layer
virtual string GetTextHeader (Window window)
virtual bool HeaderIsListOf (int id)
virtual void Init ()
virtual void OnInit ()
virtual void OnAfterInit ()
virtual void ApplySkin ()
void ShowScreenLock (string id)
void UpdateInput ()
virtual void OnUpdateInput ()
virtual void OnRightClick ()
virtual bool OnBack ()
virtual void OnChangeLayer ()
virtual void OnCreate ()
void _AddLayer (string id)
Layer AddLayer (string id)
T AddLayer< T > ()
T AddLayer< T > (string id)
T AddLayerDontCloseOthers< T > ()
Layer AddLayerDontCloseOthers (Layer l)
T GetOrAddLayer< T > ()
virtual void OnBeforeAddLayer ()
virtual void OnAfterAddLayer ()
Layer AddLayer (Layer l)
void ToggleLayer (string id)
T ToggleLayer< T > (string id=null)
void WaitAndClose ()
void OnClickClose ()
virtual void Close ()
void CloseLayers ()
void RemoveLayers (bool removeImportant=false)
bool RemoveLayer< T > ()
void RemoveLayer (Layer l)
virtual void OnKill ()
Layer SetOnKill (Action action)
void DisableClose ()
void Delay (float duration=0.05f)
Layer SetDelay (float d)
Layer GetLayer (string id)
T GetLayer< T > (bool fromTop=false)
Layer GetTopLayer ()
void SwitchContent (int idWindow, int i)
virtual void OnSwitchContent (Window window)
Layer SetTitles (string langList, string idHeaderRow=null)
bool IsBlockWidgetClick ()
bool IsHideHud ()
bool IsAllowGeneralInput ()
bool IsUseBlur ()
bool IsPointerOnLayer ()
void ApplySkin ()
Public Attributes
UIList listArea
UIList listTech
UIList listTech2
UIList listFeat
UIList listFeat2
UIList listFeat3
FactionBranch branch
UIHomeInfo info
Public Attributes inherited from Layer
Option option
UnityEvent onKill
Anime animeIn
Anime animeOut
bool closeOthers
bool defaultActionMode = true
Button screenLock
Layer parent
string idLayer
List< Layer > layers = new List<Layer>()
Vector2 lastParentPos
List< Window > windows = new List<Window>()
string langHint
Static Public Attributes
static LayerHome Instance
const int TabResearch = 1
const int TabPolicy = 2
const int TabPopulation = 3
const int TabFeat = 4
Static Public Attributes inherited from Layer
static int skipInput
static bool closeOnRightClick
static bool rightClicked
static bool cancelKeyDown
static bool ignoreSounds
static Transform blurStopInstance
static string[] searchPath = new string[3] { "Layer", "Layer/Dialog", "Layer/LayerHome" }
Additional Inherited Members
Static Public Member Functions inherited from ELayer
static int rnd (int a)
Static Public Member Functions inherited from Layer
static T Create< T > ()
static T Create< T > (string path)
static Layer Create (string path)
Protected Member Functions inherited from ELayer
sealed override void _Close ()
sealed override void Kill ()
Protected Member Functions inherited from Layer
virtual void Awake ()
virtual void _Close ()
virtual void Kill ()
Protected Attributes inherited from Layer
RectTransform _rect
bool isDestroyed
Properties inherited from ELayer
static Core core [get]
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static FactionBranch Branch [get]
static Faction Home [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static CoreConfig config [get]
static GameSetting setting [get]
static ColorProfile Colors [get]
static SourceManager sources [get]
static World world [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
bool IsFloat [get]
virtual string IdHelp [get]
Properties inherited from Layer
Layer TopLayer [get]
string uid [get]
virtual RectTransform rectLayers [get]
virtual bool blockWidgetClick [get]
Detailed Description
Definition at line 4 of file LayerHome.cs.
Member Function Documentation
HeaderIsListOf()
override bool LayerHome.HeaderIsListOf (int id) inline virtual
Reimplemented from Layer.
Definition at line 32 of file LayerHome.cs.
    {
        return id != 0;
    }
OnInit()
override void LayerHome.OnInit () inline virtual
Reimplemented from Layer.
Definition at line 37 of file LayerHome.cs.
    {
        branch = ELayer.Branch;
        Instance = this;
    }
References ELayer.Branch, branch, and Instance.
OnSwitchContent()
override void LayerHome.OnSwitchContent (Window window) inline virtual
Reimplemented from Layer.
Definition at line 43 of file LayerHome.cs.
    {
        if (window.setting.tabs.Count == 0)
        {
            return;
        }
        WindowMenu menuLeft = window.menuLeft;
        menuLeft.Clear();
        if (ELayer.player.shippingResults.Count > 0)
        {
            menuLeft.AddButtonSimple(() => "shipping_result".lang(), delegate
            {
                ELayer.ui.AddLayer<LayerShippingResult>().Show();
            });
        }
        switch (window.CurrentTab.idLang)
        {
        case "top":
            info.Refresh();
            break;
        case "skills":
            RefreshFeat();
            break;
        case "chronicle":
            RefreshChronicle();
            break;
        case "population":
            break;
        }
    }
References WindowMenu.AddButtonSimple(), WindowMenu.Clear(), Window.CurrentTab, info, Window.menuLeft, ELayer.player, UIHomeInfo.Refresh(), RefreshChronicle(), RefreshFeat(), Window.setting, Player.shippingResults, Window.Setting.tabs, and ELayer.ui.
RefreshAreas()
void LayerHome.RefreshAreas () inline
Definition at line 204 of file LayerHome.cs.
    {
        listArea.callbacks = new UIList.Callback<Area, ItemGeneral>
        {
            onClick = delegate
            {
            },
            onInstantiate = delegate(Area a, ItemGeneral b)
            {
                _ = b.button1;
                b.SetMainText(a.Name);
                b.AddSubButton(ELayer.core.refs.icons.go, delegate
                {
                    ELayer.screen.Focus(a.points[0]);
                }, "tFocus");
                b.Build();
            },
            onList = delegate
            {
                foreach (Area item in ELayer._map.rooms.listArea)
                {
                    listArea.Add(item);
                }
            },
            onSort = (Area a, UIList.SortMode m) => a.GetSortVal(m),
            onRefresh = null
        };
        listArea.List();
    }
References ELayer._map, UIList.Add(), ItemGeneral.AddSubButton(), ItemGeneral.Build(), UIItem.button1, ELayer.core, BaseArea.GetSortVal(), CoreRef.Icons.go, CoreRef.icons, item, UIList.List(), RoomManager.listArea, BaseArea.Name, Core.refs, Map.rooms, and ItemGeneral.SetMainText().
RefreshChronicle()
void LayerHome.RefreshChronicle () inline
Definition at line 74 of file LayerHome.cs.
    {
    }
Referenced by OnSwitchContent().
RefreshFeat()
void LayerHome.RefreshFeat () inline
Definition at line 109 of file LayerHome.cs.
    {
        listFeat.callbacks = new UIList.Callback<Element, ButtonElement>
        {
            onClick = delegate(Element a, ButtonElement b)
            {
                int p = ELayer.Branch.GetTechUpgradeCost(a);
                int currency = ELayer.pc.GetCurrency("money2");
                if (p == 0 || p > currency || a.ValueWithoutLink == 0 || a.source.cost[0] == 0)
                {
                    SE.Beep();
                }
                else
                {
                    Dialog.YesNo("dialogUpgradeTech".lang(a.Name), delegate
                    {
                        SE.Pay();
                        ELayer.pc.ModCurrency(-p, "money2");
                        ELayer.Branch.elements.ModBase(a.id, 1);
                        listFeat.List();
                        ELayer.Branch.resources.SetDirty();
                        ELayer.core.game.player.hotbars.ResetHotbar(2);
                        if ((bool)WidgetHotbar.HotBarMainMenu)
{
                            WidgetHotbar.HotBarMainMenu.RebuildPage();
                        }
                        if ((bool)WidgetMenuPanel.Instance)
{
                            WidgetMenuPanel.Instance.OnChangeActionMode();
                        }
                    });
                }
            },
            onInstantiate = delegate(Element a, ButtonElement b)
            {
                b.SetElement(a, ELayer._zone.elements, ButtonElement.Mode.Tech);
            },
            onList = delegate
            {
                foreach (Element item in branch.elements.dict.Values.Where((Element b) => (b.Value > 0 || b.vBase > 0) && b.source.category != "policy" && b.source.category != "landfeat" && !b.HasTag("hidden")))
                {
                    listFeat.Add(item);
                }
            },
            onSort = (Element a, UIList.SortMode m) => a.GetSortVal(m),
            onRefresh = null
        };
        listFeat.List();
        listFeat2.callbacks = new UIList.Callback<Element, ButtonElement>
        {
            onClick = delegate
            {
            },
            onInstantiate = delegate(Element a, ButtonElement b)
            {
                b.SetElement(a, ELayer._zone.elements, ButtonElement.Mode.Policy);
            },
            onList = delegate
            {
                foreach (Element item2 in branch.elements.dict.Values.Where((Element b) => b.source.category == "policy"))
                {
                    listFeat2.Add(item2);
                }
            },
            onSort = (Element a, UIList.SortMode m) => a.GetSortVal(m),
            onRefresh = null
        };
        listFeat2.List();
        listFeat3.callbacks = new UIList.Callback<Element, ButtonElement>
        {
            onClick = delegate
            {
            },
            onInstantiate = delegate(Element a, ButtonElement b)
            {
                b.SetElement(a, ELayer._zone.elements, ButtonElement.Mode.LandFeat);
            },
            onList = delegate
            {
                IEnumerable<Element> enumerable = branch.elements.dict.Values;
                if (branch.HasNetwork)
                {
                    enumerable = enumerable.Concat(ELayer.pc.faction.elements.dict.Values);
                }
                foreach (Element item3 in enumerable.Where((Element b) => (b.Value > 0 || b.vBase > 0) && b.source.category == "landfeat" && !b.HasTag("hidden")))
                {
                    listFeat3.Add(item3);
                }
            },
            onSort = (Element a, UIList.SortMode m) => a.GetSortVal(m),
            onRefresh = null
        };
        listFeat3.List();
    }
References ELayer._zone, UIList.Add(), ELayer.Branch, branch, currency, ElementContainer.dict, FactionBranch.elements, Zone.elements, Card.GetCurrency(), Element.GetSortVal(), FactionBranch.GetTechUpgradeCost(), Element.HasTag(), if(), WidgetMenuPanel.Instance, item, listFeat, Element.Name, ELayer.pc, ButtonElement.SetElement(), Element.source, Element.Value, Element.ValueWithoutLink, Element.vBase, and Dialog.YesNo().
Referenced by OnSwitchContent().
RefreshFocus()
void LayerHome.RefreshFocus () inline
Definition at line 100 of file LayerHome.cs.
    {
        ItemResearch[] componentsInChildren = listTech.GetComponentsInChildren<ItemResearch>();
        foreach (ItemResearch itemResearch in componentsInChildren)
        {
            itemResearch.goFocus.SetActive(itemResearch.plan == branch.researches.focused);
        }
    }
References branch, ResearchManager.focused, ItemResearch.goFocus, listTech, ItemResearch.plan, and FactionBranch.researches.
Referenced by RefreshTech().
RefreshSpots()
void LayerHome.RefreshSpots () inline
Definition at line 234 of file LayerHome.cs.
    {
        listArea.Clear();
        listArea.callbacks = new UIList.Callback<Trait, ItemGeneral>
        {
            onClick = delegate
            {
            },
            onInstantiate = delegate(Trait a, ItemGeneral b)
            {
                _ = b.button1;
                b.SetMainText(a.Name);
                b.AddSubButton(ELayer.core.refs.icons.go, delegate
                {
                    ELayer.screen.Focus(a.GetPoint());
                }, "tFocus");
                b.Build();
            },
            onList = delegate
            {
                foreach (Card item in ELayer._map.Installed.all)
                {
                    if (item.trait.IsSpot)
                    {
                        listArea.Add(item.trait);
                    }
                }
            },
            onSort = (Trait a, UIList.SortMode m) => a.GetSortVal(m),
            onRefresh = null
        };
        listArea.List();
    }
References ELayer._map, UIList.Add(), ItemGeneral.AddSubButton(), Props.all, ItemGeneral.Build(), UIItem.button1, UIList.Clear(), ELayer.core, Trait.GetSortVal(), CoreRef.Icons.go, CoreRef.icons, Map.Installed, item, UIList.List(), Trait.Name, Core.refs, and ItemGeneral.SetMainText().
RefreshTech()
void LayerHome.RefreshTech (bool listComplete = false) inline
Definition at line 78 of file LayerHome.cs.
    {
        UIList list = (listComplete ? listTech2 : listTech);
        list.sortMode = ELayer.player.pref.sortResearch;
        list.callbacks = new UIList.Callback<ResearchPlan, ItemResearch>
        {
            onInstantiate = delegate
            {
            },
            onList = delegate
            {
                foreach (ResearchPlan item in listComplete ? branch.researches.finished : branch.researches.plans)
                {
                    list.Add(item);
                }
            },
            onSort = (ResearchPlan a, UIList.SortMode m) => a.GetSortVal(m)
        };
        list.List();
        RefreshFocus();
    }
References UIList.Add(), branch, ResearchManager.finished, ResearchPlan.GetSortVal(), item, UIList.List(), listTech, listTech2, ResearchManager.plans, ELayer.player, Player.pref, RefreshFocus(), FactionBranch.researches, and Player.Pref.sortResearch.
Member Data Documentation
branch
FactionBranch LayerHome.branch
Definition at line 20 of file LayerHome.cs.
Referenced by OnInit(), RefreshFeat(), RefreshFocus(), and RefreshTech().
info
UIHomeInfo LayerHome.info
Definition at line 22 of file LayerHome.cs.
Referenced by OnSwitchContent().
Instance
LayerHome LayerHome.Instance static
Definition at line 6 of file LayerHome.cs.
Referenced by OnInit().
listArea
UIList LayerHome.listArea
Definition at line 8 of file LayerHome.cs.
listFeat
UIList LayerHome.listFeat
Definition at line 14 of file LayerHome.cs.
Referenced by RefreshFeat().
listFeat2
UIList LayerHome.listFeat2
Definition at line 16 of file LayerHome.cs.
listFeat3
UIList LayerHome.listFeat3
Definition at line 18 of file LayerHome.cs.
listTech
UIList LayerHome.listTech
Definition at line 10 of file LayerHome.cs.
Referenced by RefreshFocus(), and RefreshTech().
listTech2
UIList LayerHome.listTech2
Definition at line 12 of file LayerHome.cs.
Referenced by RefreshTech().
TabFeat
const int LayerHome.TabFeat = 4 static
Definition at line 30 of file LayerHome.cs.
TabPolicy
const int LayerHome.TabPolicy = 2 static
Definition at line 26 of file LayerHome.cs.
TabPopulation
const int LayerHome.TabPopulation = 3 static
Definition at line 28 of file LayerHome.cs.
TabResearch
const int LayerHome.TabResearch = 1 static
Definition at line 24 of file LayerHome.cs.
The documentation for this class was generated from the following file:
Elin/LayerHome.cs