Elin Decompiled Documentation: UIRawImage Class Reference
UIRawImage Class Reference
Public Member Functions
IEnumerator Animate ()
void ApplySkin ()
void ApplySkin ()
Public Attributes
ImageType imageType
BaseSkinRoot skinRoot
bool animate
Vector2 animeSpeed
Protected Member Functions
override void Awake ()
override void OnEnable ()
override void OnDisable ()
override void OnPopulateMesh (VertexHelper vh)
Detailed Description
Definition at line 5 of file UIRawImage.cs.
Member Function Documentation
Animate()
IEnumerator UIRawImage.Animate () inline
Definition at line 39 of file UIRawImage.cs.
    {
        while (true)
        {
            Rect rect = base.uvRect;
            rect.x += animeSpeed.x * Time.smoothDeltaTime;
            rect.y += animeSpeed.y * Time.smoothDeltaTime;
            base.uvRect = rect;
            yield return true;
        }
    }
ApplySkin()
void UIRawImage.ApplySkin () inline
Implements IUISkin.
Definition at line 51 of file UIRawImage.cs.
    {
        BaseSkinRoot baseSkinRoot = skinRoot ?? SkinManager.Instance.currentSkin;
        baseSkinRoot.ApplySkin(this);
        if (imageType == ImageType.Line)
        {
            color = baseSkinRoot.Colors.colorLine;
        }
    }
References BaseSkinRoot.ApplySkin(), SkinColorProfile.colorLine, BaseSkinRoot.Colors, SkinManager.currentSkin, imageType, SkinManager.Instance, and skinRoot.
Referenced by Awake().
Awake()
override void UIRawImage.Awake () inline protected
Definition at line 15 of file UIRawImage.cs.
    {
        ApplySkin();
        base.Awake();
    }
References ApplySkin().
OnDisable()
override void UIRawImage.OnDisable () inline protected
Definition at line 30 of file UIRawImage.cs.
    {
        if (animate)
        {
            StopCoroutine("Animate");
        }
        base.OnDisable();
    }
References animate.
OnEnable()
override void UIRawImage.OnEnable () inline protected
Definition at line 21 of file UIRawImage.cs.
    {
        if (animate)
        {
            StartCoroutine("Animate");
        }
        base.OnEnable();
    }
References animate.
OnPopulateMesh()
override void UIRawImage.OnPopulateMesh (VertexHelper vh) inline protected
Definition at line 61 of file UIRawImage.cs.
    {
        if (color.a == 0f || !base.texture)
        {
            vh.Clear();
        }
        else
        {
            base.OnPopulateMesh(vh);
        }
    }
Member Data Documentation
animate
bool UIRawImage.animate
Definition at line 11 of file UIRawImage.cs.
Referenced by OnDisable(), and OnEnable().
animeSpeed
Vector2 UIRawImage.animeSpeed
Definition at line 13 of file UIRawImage.cs.
imageType
ImageType UIRawImage.imageType
Definition at line 7 of file UIRawImage.cs.
Referenced by ApplySkin(), and SkinRoot.ApplySkin().
skinRoot
BaseSkinRoot UIRawImage.skinRoot
Definition at line 9 of file UIRawImage.cs.
Referenced by ApplySkin().
The documentation for this class was generated from the following file:
Elin/Plugins.UI/UIRawImage.cs