Elin Decompiled Documentation: ElinGameIOPropertyAttribute Class Reference
ElinGameIOPropertyAttribute Class Reference
Public Member Functions
ElinGameIOPropertyAttribute (string chunkName)
override void Register (PropertyInfo property)
Public Member Functions inherited from ElinEventBaseAttribute
virtual void Register (MethodInfo method)
virtual void Register (PropertyInfo property)
Properties
string ChunkName [get]
Static Private Member Functions
static Action< object > CreateSetterDelegate (MethodInfo method)
static void LoadGameIOProperty (GameIOContext context)
static void SaveGameIOProperty (GameIOContext context)
Static Private Attributes
static bool _registered
static readonly Dictionary< string,(PropertyInfo property, Func< object > getter, Action< object > setter)> _contextVars = new Dictionary<string, (PropertyInfo, Func<object>, Action<object>)>()
Detailed Description
Definition at line 9 of file ElinGameIOPropertyAttribute.cs.
Constructor & Destructor Documentation
ElinGameIOPropertyAttribute()
ElinGameIOPropertyAttribute.ElinGameIOPropertyAttribute (string chunkName) inline
Definition at line 17 of file ElinGameIOPropertyAttribute.cs.
    {
        ChunkName = chunkName;
    }
References ChunkName.
Member Function Documentation
CreateSetterDelegate()
static Action< object > ElinGameIOPropertyAttribute.CreateSetterDelegate (MethodInfo method) inline static private
Definition at line 41 of file ElinGameIOPropertyAttribute.cs.
    {
        Type parameterType = method.GetParameters()[0].ParameterType;
        ParameterExpression parameterExpression = Expression.Parameter(typeof(object), "obj");
        UnaryExpression arg = Expression.Convert(parameterExpression, parameterType);
        return Expression.Lambda<Action<object>>(Expression.Call(method, arg), new ParameterExpression[1] { parameterExpression }).Compile();
    }
Referenced by Register().
LoadGameIOProperty()
static void ElinGameIOPropertyAttribute.LoadGameIOProperty (GameIOContext context) inline static private
Definition at line 49 of file ElinGameIOPropertyAttribute.cs.
    {
        if (!context.Load<Dictionary<string, object>>("context_vars", out var data))
        {
            data = new Dictionary<string, object>();
        }
        KeyValuePair<string, (PropertyInfo, Func<object>, Action<object>)>[] array = _contextVars.ToArray();
        foreach (KeyValuePair<string, (PropertyInfo, Func<object>, Action<object>)> keyValuePair in array)
        {
            keyValuePair.Deconstruct(out var key, out var value);
            (PropertyInfo, Func<object>, Action<object>) tuple = value;
            string text = key;
            var (propertyInfo, _, action) = tuple;
            try
            {
                string key2 = propertyInfo.DeclaringType.FullName + ":" + text;
                object valueOrDefault = data.GetValueOrDefault(key2);
                action(valueOrDefault);
            }
            catch (Exception arg)
            {
                Debug.LogError($"#io failed to populate context var {text}\n{arg}");
                _contextVars.Remove(text);
            }
        }
    }
References $, _contextVars, and Debug.
Referenced by Register().
Register()
override void ElinGameIOPropertyAttribute.Register (PropertyInfo property) inline virtual
Reimplemented from ElinEventBaseAttribute.
Definition at line 22 of file ElinGameIOPropertyAttribute.cs.
    {
        if (!_registered)
        {
            BaseModManager.SubscribeEvent<GameIOContext>("elin.game.post_load", LoadGameIOProperty);
            BaseModManager.SubscribeEvent<GameIOContext>("elin.game.post_save", SaveGameIOProperty);
            _registered = true;
        }
        MethodInfo getMethod = property.GetMethod;
        MethodInfo setMethod = property.SetMethod;
        if (!(getMethod == null) && !(setMethod == null) && setMethod.IsStatic)
        {
            Func<object> item = getMethod.CreateDelegate<Func<object>>();
            Action<object> item2 = CreateSetterDelegate(setMethod);
            Type declaringType = property.DeclaringType;
            _contextVars[declaringType.FullName + ":" + ChunkName] = (property, item, item2);
        }
    }
References _contextVars, _registered, ChunkName, CreateSetterDelegate(), item, LoadGameIOProperty(), SaveGameIOProperty(), and BaseModManager.SubscribeEvent().
SaveGameIOProperty()
static void ElinGameIOPropertyAttribute.SaveGameIOProperty (GameIOContext context) inline static private
Definition at line 76 of file ElinGameIOPropertyAttribute.cs.
    {
        Dictionary<string, object> dictionary = new Dictionary<string, object>(StringComparer.Ordinal);
        KeyValuePair<string, (PropertyInfo, Func<object>, Action<object>)>[] array = _contextVars.ToArray();
        foreach (KeyValuePair<string, (PropertyInfo, Func<object>, Action<object>)> keyValuePair in array)
        {
            keyValuePair.Deconstruct(out var key, out var value);
            (PropertyInfo, Func<object>, Action<object>) tuple = value;
            string text = key;
            var (propertyInfo, func, _) = tuple;
            try
            {
                object value2 = func();
                string key2 = propertyInfo.DeclaringType.FullName + ":" + text;
                dictionary[key2] = value2;
            }
            catch (Exception arg)
            {
                Debug.LogError($"#io failed to save context var {text}\n{arg}");
                _contextVars.Remove(text);
            }
        }
        context.Save("context_vars", dictionary);
    }
References $, _contextVars, and Debug.
Referenced by Register().
Member Data Documentation
_contextVars
readonly Dictionary<string, (PropertyInfo property, Func<object> getter, Action<object> setter)> ElinGameIOPropertyAttribute._contextVars = new Dictionary<string, (PropertyInfo, Func<object>, Action<object>)>() static private
Definition at line 13 of file ElinGameIOPropertyAttribute.cs.
Referenced by LoadGameIOProperty(), Register(), and SaveGameIOProperty().
_registered
bool ElinGameIOPropertyAttribute._registered static private
Definition at line 11 of file ElinGameIOPropertyAttribute.cs.
Referenced by Register().
Property Documentation
ChunkName
string ElinGameIOPropertyAttribute.ChunkName get
Definition at line 15 of file ElinGameIOPropertyAttribute.cs.
{ get; }
Referenced by ElinGameIOPropertyAttribute(), and Register().
The documentation for this class was generated from the following file:
Elin/ElinGameIOPropertyAttribute.cs