Elin Decompiled Documentation: ResourceCache< T > Class Template Reference
ResourceCache< T > Class Template Reference
Public Member Functions
ResourceCache (string _path="")
void Clear ()
T Get (string id, ResourceLoadType loadType=ResourceLoadType.Resource, object option=null)
T2 Get< T2 > (string id, ResourceLoadType loadType=ResourceLoadType.Resource)
Static Public Member Functions
static T Load< T > (string path)
static T LoadBundle< T > (string path)
Public Attributes
Dictionary< string, T > dict = new Dictionary<string, T>()
string path
Static Public Attributes
static ResourceCache< Object > caches = new ResourceCache<Object>()
Detailed Description
Type Constraints
T : Object
Definition at line 19 of file ResourceCache.cs.
Constructor & Destructor Documentation
ResourceCache()
ResourceCache< T >.ResourceCache (string _path = "") inline
Definition at line 25 of file ResourceCache.cs.
    {
        path = _path;
    }
References ResourceCache< T >.path.
Member Function Documentation
Clear()
void ResourceCache< T >.Clear () inline
Definition at line 30 of file ResourceCache.cs.
    {
        foreach (T value in dict.Values)
        {
            Object.DestroyImmediate(value);
        }
        dict.Clear();
    }
References ResourceCache< T >.dict.
Get()
T ResourceCache< T >.Get (string id, ResourceLoadType loadType = ResourceLoadType::Resource, object option = null) inline
Definition at line 39 of file ResourceCache.cs.
    {
        T value = null;
        string key = typeof(T).Name + id;
        if (!dict.TryGetValue(key, out value))
        {
            value = ((loadType == ResourceLoadType.Streaming) ? IO.LoadObject<T>(path + id, option) : Resources.Load<T>(path + id));
            dict.Add(key, value);
        }
        return value;
    }
References ResourceCache< T >.dict, and ResourceCache< T >.path.
Referenced by ResourceCache< T >.Load< T >(), and ResourceCache< T >.LoadBundle< T >().
Get< T2 >()
T2 ResourceCache< T >.Get< T2 > (string id, ResourceLoadType loadType = ResourceLoadType::Resource) inline
Type Constraints
T2 : Object
Definition at line 51 of file ResourceCache.cs.
                                                                                                 : Object
    {
        T value = null;
        string key = typeof(T2).Name + id;
        if (!dict.TryGetValue(key, out value))
        {
            T2 val = null;
            val = ((loadType != 0) ? AssetBundle.LoadFromFile(Application.streamingAssetsPath + "/Bundle/" + id).LoadAsset<GameObject>(new FileInfo(id).Name).GetComponent<T2>() : Resources.Load<T2>(path + id));
            dict.Add(key, val as T);
            return val;
        }
        return value as T2;
    }
References AssetBundle, ResourceCache< T >.dict, and ResourceCache< T >.path.
Load< T >()
static T ResourceCache< T >.Load< T > (string path) inline static
Type Constraints
T : Object
Definition at line 9 of file ResourceCache.cs.
                                                 : Object
    {
        return caches.Get<T>(path);
    }
References ResourceCache< T >.caches, ResourceCache< T >.Get(), and ResourceCache< T >.path.
LoadBundle< T >()
static T ResourceCache< T >.LoadBundle< T > (string path) inline static
Type Constraints
T : Object
Definition at line 14 of file ResourceCache.cs.
                                                       : Object
    {
        return caches.Get<T>(path, ResourceLoadType.AssetBundle);
    }
References ResourceCache< T >.caches, ResourceCache< T >.Get(), and ResourceCache< T >.path.
Member Data Documentation
caches
ResourceCache<Object> ResourceCache< T >.caches = new ResourceCache<Object>() static
Definition at line 7 of file ResourceCache.cs.
Referenced by ResourceCache< T >.Load< T >(), and ResourceCache< T >.LoadBundle< T >().
dict
Dictionary<string, T> ResourceCache< T >.dict = new Dictionary<string, T>()
Definition at line 21 of file ResourceCache.cs.
Referenced by ResourceCache< T >.Clear(), ResourceCache< T >.Get(), and ResourceCache< T >.Get< T2 >().
path
string ResourceCache< T >.path
Definition at line 23 of file ResourceCache.cs.
Referenced by ResourceCache< T >.Get(), ResourceCache< T >.Get< T2 >(), ResourceCache< T >.Load< T >(), ResourceCache< T >.LoadBundle< T >(), and ResourceCache< T >.ResourceCache().
The documentation for this class was generated from the following file:
Elin/Plugins.basecore/ResourceCache.cs