Elin Decompiled Documentation: WidgetCurrentTool Class Reference
WidgetCurrentTool Class Reference
Classes
class Extra
Public Member Functions
override object CreateExtra ()
override void OnActivate ()
void RebuildSlots ()
void CheckDirty ()
void SwitchPage ()
void _RefreshCurrentHotItem ()
void OnClickButtonHotItem ()
void ModSelected (int a)
int GetNextSelectableIndex ()
int GetPrevSelectableIndex ()
void Reselect ()
void Select (int index, bool fromHotkey=false)
void RefreshHighlight ()
override bool CanShowContextMenu ()
override void OnSetContextMenu (UIContextMenu m)
Public Member Functions inherited from Widget
void Test ()
bool IsInRightMode ()
void Activate ()
void RefreshOrder ()
virtual void OnActivate ()
virtual object CreateExtra ()
void Deactivate ()
virtual void OnDeactivate ()
void Close ()
void Reactivate ()
virtual void OnManagerActivate ()
virtual void OnManagerDeactivate ()
void SetAnchor (RectPosition p)
void SetPivot (RectPosition p)
virtual void OnChangePivot ()
void UpdateConfig ()
virtual void OnUpdateConfig ()
void ClampToScreen ()
virtual void OnChangeResolution ()
void OnChangePosition ()
virtual void OnChangeActionMode ()
virtual void OnFlip ()
bool IsAlignTop ()
Layer AddLayer (Layer l, Transform trans)
void RefreshTipPivotPosition ()
SkinSet GetSkin ()
SkinConfig GetSkinConfig ()
void SetSkin (int id, int v=0)
void TestSkin ()
virtual void ApplySkin ()
virtual void OnApplySkin ()
void InstantiateDeco (SkinDeco deco)
void AddDeco (SkinDeco deco)
void RemoveDeco (SkinDeco deco)
virtual bool CanShowContextMenu ()
void ShowContextMenu ()
void SetBaseContextMenu (UIContextMenu m)
virtual void OnSetContextMenu (UIContextMenu m)
void SetGridContextMenu (UIContextMenu m)
void SoundActivate ()
void OnChangeResolution ()
SkinSet GetSkin ()
SkinConfig GetSkinConfig ()
Static Public Member Functions
static void RefreshCurrentHotItem ()
Static Public Member Functions inherited from EMono
static int rnd (int a)
Public Attributes
ButtonHotItem buttonHotItem
UIButton buttonSwitchPage
Image iconHeld
Image imageHighlight
UIList list
int maxSlots = 9
List< Thing > grid = new List<Thing>(new Thing[20])
UIPlaceHelper placer
GridLayoutGroup layout
Transform transHighlightSwitch
int selected = -1
int selectedPage
Public Attributes inherited from Widget
Image imageBG
SoundData soundActivate
UIDragPanel dragPanel
RectTransform tipPivotLeft
RectTransform tipPivotRight
Static Public Attributes
const int SlotsPerPage = 10
const int MaxPage = 2
static WidgetCurrentTool Instance
static bool dirty
Static Public Attributes inherited from EMono
static Core core
Properties
Extra extra [get]
int page [get, set]
ButtonGrid selectedButton [get]
Properties inherited from Widget
string ID [get]
Config config [get]
SkinRoot skinRoot [get]
bool IsSealed [get]
virtual bool ShowStyleMenu [get]
virtual bool AlwaysTop [get]
virtual bool IsStaticPosition [get]
virtual bool AlwaysBottom [get]
virtual Type SetSiblingAfter [get]
virtual bool ShowInBuildMode [get]
virtual bool RightClickToClose [get]
virtual bool AllowRightClickToClose [get]
Properties inherited from EMono
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SoundManager Sound [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static CoreDebug debug [get]
Private Member Functions
void Update ()
Additional Inherited Members
Public Types inherited from Widget
enum WidgetType { Default , ZoomMenu }
enum State { Active , Inactive }
Protected Member Functions inherited from Widget
void ClampToScreenEnsured (Component c, Vector2 anchoredPos)
void ClampToScreen (RectTransform rect, float margin=10f)
Protected Attributes inherited from Widget
bool flip
Detailed Description
Definition at line 5 of file WidgetCurrentTool.cs.
Member Function Documentation
_RefreshCurrentHotItem()
void WidgetCurrentTool._RefreshCurrentHotItem () inline
Definition at line 189 of file WidgetCurrentTool.cs.
    {
        HotItem hotItem = EMono.player.currentHotItem;
        if (hotItem == null)
        {
            hotItem = EMono.player.hotItemNoItem;
        }
        buttonHotItem.item = hotItem;
        buttonHotItem.icon.material = (hotItem.UseUIObjMaterial ? EMono.core.refs.matUIObj : null);
        hotItem.SetImage(buttonHotItem.icon);
        buttonHotItem.interactable = true;
        buttonHotItem.Refresh();
        iconHeld.SetActive(hotItem is HotItemHeld);
        RefreshHighlight();
    }
References buttonHotItem, Player.currentHotItem, Player.hotItemNoItem, UIButton.icon, iconHeld, EMono.player, ButtonHotItem.Refresh(), RefreshHighlight(), and HotItem.SetImage().
Referenced by CheckDirty(), OnActivate(), RefreshCurrentHotItem(), and SwitchPage().
CanShowContextMenu()
override bool WidgetCurrentTool.CanShowContextMenu () inline virtual
Reimplemented from Widget.
Definition at line 308 of file WidgetCurrentTool.cs.
    {
        ButtonGrid componentOf = InputModuleEX.GetComponentOf<ButtonGrid>();
        if ((bool)componentOf && componentOf != buttonHotItem)
        {
            return false;
        }
        return base.CanShowContextMenu();
    }
References buttonHotItem.
CheckDirty()
void WidgetCurrentTool.CheckDirty () inline
Definition at line 161 of file WidgetCurrentTool.cs.
    {
        if (dirty)
        {
            list.Redraw();
            _RefreshCurrentHotItem();
        }
        dirty = false;
    }
References _RefreshCurrentHotItem(), dirty, list, and UIList.Redraw().
Referenced by LayerInventory.SetDirtyAll(), SwitchPage(), and Update().
CreateExtra()
override object WidgetCurrentTool.CreateExtra () inline virtual
Reimplemented from Widget.
Definition at line 64 of file WidgetCurrentTool.cs.
    {
        return new Extra();
    }
GetNextSelectableIndex()
int WidgetCurrentTool.GetNextSelectableIndex () inline
Definition at line 225 of file WidgetCurrentTool.cs.
    {
        int num = selected + 1;
        if (num >= maxSlots)
        {
            num = -1;
        }
        return num;
    }
References maxSlots, and selected.
Referenced by ModSelected().
GetPrevSelectableIndex()
int WidgetCurrentTool.GetPrevSelectableIndex () inline
Definition at line 235 of file WidgetCurrentTool.cs.
    {
        int num = selected - 1;
        if (num <= -2)
        {
            num = maxSlots - 1;
        }
        return num;
    }
References maxSlots, and selected.
Referenced by ModSelected().
ModSelected()
void WidgetCurrentTool.ModSelected (int a) inline
Definition at line 218 of file WidgetCurrentTool.cs.
    {
        SE.SelectHotitem();
        int index = ((a > 0) ? GetNextSelectableIndex() : GetPrevSelectableIndex());
        Select(index);
    }
References GetNextSelectableIndex(), GetPrevSelectableIndex(), and Select().
Referenced by AM_Adv._OnUpdateInput().
OnActivate()
override void WidgetCurrentTool.OnActivate () inline virtual
Reimplemented from Widget.
Definition at line 69 of file WidgetCurrentTool.cs.
    {
        transHighlightSwitch.SetActive(!EMono.player.flags.toggleHotbarHighlightDisabled);
        Instance = this;
        _RefreshCurrentHotItem();
        buttonHotItem.onClick.AddListener(OnClickButtonHotItem);
        buttonSwitchPage.SetOnClick(delegate
        {
            if (!EMono.player.flags.toggleHotbarHighlightDisabled && page == 1)
            {
                EMono.player.flags.toggleHotbarHighlightDisabled = true;
                transHighlightSwitch.SetActive(enable: false);
            }
            SwitchPage();
        });
        RebuildSlots();
        dirty = true;
        placer.Refresh();
        ApplySkin();
    }
References _RefreshCurrentHotItem(), Widget.ApplySkin(), buttonHotItem, buttonSwitchPage, dirty, Player.flags, Instance, OnClickButtonHotItem(), page, placer, EMono.player, RebuildSlots(), UIPlaceHelper.Refresh(), SwitchPage(), Player.Flags.toggleHotbarHighlightDisabled, and transHighlightSwitch.
OnClickButtonHotItem()
void WidgetCurrentTool.OnClickButtonHotItem () inline
Definition at line 205 of file WidgetCurrentTool.cs.
    {
        SE.SelectHotitem();
        if (selected != -1 && EMono.player.currentHotItem.Thing == selectedButton.card)
        {
            Select(-1);
            return;
        }
        int index = selected;
        selected = -1;
        Select(index);
    }
References ButtonGrid.card, Player.currentHotItem, EMono.player, Select(), selected, selectedButton, and HotItem.Thing.
Referenced by OnActivate().
OnSetContextMenu()
override void WidgetCurrentTool.OnSetContextMenu (UIContextMenu m) inline virtual
Reimplemented from Widget.
Definition at line 318 of file WidgetCurrentTool.cs.
    {
        InputModuleEX.GetComponentOf<ButtonHotItem>();
        UIContextMenu uIContextMenu = m.AddChild("setting");
        UIContextMenu uIContextMenu2 = m.AddChild("style");
        uIContextMenu2.AddSlider("iconSize", (float n) => n.ToString() ?? "", extra.iconSize, delegate(float a)
        {
            extra.iconSize = (int)a;
            RebuildSlots();
        }, 0f, EMono.setting.ui.iconSizes.Count - 1, isInt: true);
        SetGridContextMenu(uIContextMenu2);
        uIContextMenu.AddToggle("showShortcut", extra.showShortcut, delegate(bool a)
        {
            extra.showShortcut = a;
            RebuildSlots();
        });
        SetBaseContextMenu(m);
    }
References UIContextMenu.AddChild(), UIContextMenu.AddSlider(), extra, WidgetCurrentTool.Extra.iconSize, RebuildSlots(), Widget.SetBaseContextMenu(), Widget.SetGridContextMenu(), and WidgetCurrentTool.Extra.showShortcut.
RebuildSlots()
void WidgetCurrentTool.RebuildSlots () inline
Definition at line 90 of file WidgetCurrentTool.cs.
    {
        imageHighlight.transform.SetParent(base.transform, worldPositionStays: false);
        layout.cellSize = EMono.setting.ui.iconSizes[extra.iconSize];
        SkinConfig skin = base.config.skin;
        list.Clear();
        list.callbacks = new UIList.Callback<Thing, ButtonGridDrag>
        {
            onRedraw = delegate(Thing a, ButtonGridDrag b, int i)
            {
                int num = i + 1;
                b.subText2.SetText((num % 10).ToString() ?? "");
                b.subText2.SetActive(extra.showShortcut);
                b.index = i % 10 + 10 * page;
                b.SetCardGrid(a, new InvOwnerHotbar(EMono.pc)
                {
                    index = i % 10 + 10 * page
                });
            }
        };
        for (int j = 0; j < maxSlots; j++)
        {
            list.Add(null);
        }
        list.onBeforeRedraw = delegate
        {
            dirty = false;
            for (int k = 0; k < grid.Count; k++)
            {
                grid[k] = null;
            }
            foreach (Thing thing in EMono.pc.things)
            {
                if (thing.invY == 1 && thing.invX >= page * 10 && thing.invX < (page + 1) * 10)
                {
                    if (thing.invX < 0 || thing.invX >= grid.Count)
                    {
                        Debug.Log(thing.Name + "/" + thing.invX);
                    }
                    else
                    {
                        grid[thing.invX] = thing;
                    }
                }
            }
            for (int l = 0; l < list.buttons.Count; l++)
            {
                UIList.ButtonPair value = list.buttons[l];
                value.obj = grid[l + page * 10];
                list.buttons[l] = value;
            }
            buttonSwitchPage.mainText.text = (page + 1).ToString() ?? "";
        };
        list.onAfterRedraw = delegate
        {
            LayerInventory.TryShowGuide(list);
        };
        list.Refresh();
        list.Redraw();
        UIRawImage obj = list.bgGrid as UIRawImage;
        obj.skinRoot = GetComponent<SkinRoot>();
        obj.color = skin.gridColor;
        ClampToScreen();
        RefreshHighlight();
    }
References UIList.Add(), UIList.buttons, Widget.ClampToScreen(), UIList.Clear(), Debug, dirty, extra, grid, SkinConfig.gridColor, WidgetCurrentTool.Extra.iconSize, GameSetting.UISetting.iconSizes, imageHighlight, Card.invX, Card.invY, list, maxSlots, Card.Name, page, EMono.pc, UIList.Redraw(), UIList.Refresh(), RefreshHighlight(), ButtonGrid.SetCardGrid(), UIText.SetText(), EMono.setting, WidgetCurrentTool.Extra.showShortcut, UIButton.subText2, Card.things, LayerInventory.TryShowGuide(), and GameSetting.ui.
Referenced by OnActivate(), and OnSetContextMenu().
RefreshCurrentHotItem()
static void WidgetCurrentTool.RefreshCurrentHotItem () inline static
Definition at line 171 of file WidgetCurrentTool.cs.
    {
        if ((bool)Instance)
        {
            Instance._RefreshCurrentHotItem();
        }
    }
References _RefreshCurrentHotItem(), and Instance.
Referenced by Card.OnChildNumChange(), ConReload.OnRemoved(), Player.RefreshCurrentHotItem(), and LayerAbility.SetDirty().
RefreshHighlight()
void WidgetCurrentTool.RefreshHighlight () inline
Definition at line 294 of file WidgetCurrentTool.cs.
    {
        bool flag = selected != -1;
        imageHighlight.SetActive(flag);
        if (flag)
        {
            imageHighlight.transform.SetParent(selectedButton.transform, worldPositionStays: false);
            imageHighlight.transform.position = selectedButton.transform.position;
            imageHighlight.Rect().sizeDelta = selectedButton.Rect().sizeDelta;
            imageHighlight.transform.SetAsFirstSibling();
            imageHighlight.SetAlpha((EMono.player.currentHotItem.Thing == selectedButton.card) ? 1f : 0.35f);
        }
    }
References ButtonGrid.card, Player.currentHotItem, imageHighlight, EMono.player, selected, selectedButton, and HotItem.Thing.
Referenced by _RefreshCurrentHotItem(), RebuildSlots(), and Select().
Reselect()
void WidgetCurrentTool.Reselect () inline
Definition at line 245 of file WidgetCurrentTool.cs.
    {
        Select(selected);
    }
References Select(), and selected.
Referenced by InvOwnerHotbar.OnProcess().
Select()
void WidgetCurrentTool.Select (int index, bool fromHotkey = false) inline
Definition at line 250 of file WidgetCurrentTool.cs.
    {
        if (index != -1 && fromHotkey && EMono.core.config.game.useAbilityOnHotkey)
        {
            ButtonGrid buttonGrid = list.buttons[index].component as ButtonGrid;
            TraitAbility traitAbility = ((buttonGrid.card != null) ? (buttonGrid.card.trait as TraitAbility) : null);
            if (traitAbility != null && traitAbility.CanUse(EMono.pc))
            {
                if (EMono.player.CanAcceptInput() && traitAbility.OnUse(EMono.pc))
                {
                    EMono.player.EndTurn();
                }
                return;
            }
        }
        if (fromHotkey)
        {
            SE.SelectHotitem();
        }
        if (selected == index && selectedPage == page)
        {
            index = -1;
        }
        selected = index;
        selectedPage = page;
        if (selected >= maxSlots)
        {
            selected = -1;
        }
        if (selected == -1 || selectedButton.card == null)
        {
            EMono.player.ResetCurrentHotItem();
        }
        else
        {
            EMono.player.SetCurrentHotItem(selectedButton.card.trait.GetHotItem());
        }
        if (ActionMode.Adv.IsActive)
        {
            ActionMode.Adv.UpdatePlans();
        }
        RefreshHighlight();
    }
References ActionMode.Adv, UIList.buttons, Player.CanAcceptInput(), TraitCatalyst.CanUse(), ButtonGrid.card, Core.config, EMono.core, Player.EndTurn(), CoreConfig.game, Trait.GetHotItem(), ActionMode.IsActive, list, maxSlots, TraitCatalyst.OnUse(), page, EMono.pc, EMono.player, RefreshHighlight(), Player.ResetCurrentHotItem(), selected, selectedButton, selectedPage, Player.SetCurrentHotItem(), Card.trait, AM_Adv.UpdatePlans(), and CoreConfig.GameConfig.useAbilityOnHotkey.
Referenced by AM_Adv._OnUpdateInput(), ModSelected(), InvOwnerHotbar.OnClick(), OnClickButtonHotItem(), InvOwnerHotbar.OnRightClick(), Reselect(), and ActionMode.UpdateInput().
SwitchPage()
void WidgetCurrentTool.SwitchPage () inline
Definition at line 179 of file WidgetCurrentTool.cs.
    {
        page = ((page == 0) ? 1 : 0);
        _RefreshCurrentHotItem();
        dirty = true;
        CheckDirty();
        placer.Refresh();
        SE.Play("switch_hotbar");
    }
References _RefreshCurrentHotItem(), CheckDirty(), dirty, page, placer, and UIPlaceHelper.Refresh().
Referenced by ActionMode.DoFunc(), OnActivate(), and ActionMode.UpdateInput().
Update()
void WidgetCurrentTool.Update () inline private
Definition at line 156 of file WidgetCurrentTool.cs.
    {
        CheckDirty();
    }
References CheckDirty().
Member Data Documentation
buttonHotItem
ButtonHotItem WidgetCurrentTool.buttonHotItem
Definition at line 22 of file WidgetCurrentTool.cs.
Referenced by _RefreshCurrentHotItem(), CanShowContextMenu(), OnActivate(), and Player.RefreshCurrentHotItem().
buttonSwitchPage
UIButton WidgetCurrentTool.buttonSwitchPage
Definition at line 24 of file WidgetCurrentTool.cs.
Referenced by OnActivate().
dirty
bool WidgetCurrentTool.dirty static
Definition at line 32 of file WidgetCurrentTool.cs.
Referenced by CheckDirty(), OnActivate(), RebuildSlots(), and SwitchPage().
grid
List<Thing> WidgetCurrentTool.grid = new List<Thing>(new Thing[20])
Definition at line 36 of file WidgetCurrentTool.cs.
Referenced by RebuildSlots().
iconHeld
Image WidgetCurrentTool.iconHeld
Definition at line 26 of file WidgetCurrentTool.cs.
Referenced by _RefreshCurrentHotItem().
imageHighlight
Image WidgetCurrentTool.imageHighlight
Definition at line 28 of file WidgetCurrentTool.cs.
Referenced by RebuildSlots(), and RefreshHighlight().
Instance
WidgetCurrentTool WidgetCurrentTool.Instance static
Definition at line 20 of file WidgetCurrentTool.cs.
Referenced by AM_Adv._OnUpdateInput(), ActPlan._Update(), ActionMode.DoFunc(), OnActivate(), LayerMiniGame.OnAfterInit(), InvOwnerHotbar.OnClick(), LayerMiniGame.OnKill(), InvOwnerHotbar.OnProcess(), InvOwnerHotbar.OnRightClick(), Player.RefreshCurrentHotItem(), RefreshCurrentHotItem(), Card.RemoveThing(), LayerAbility.SetDirty(), LayerInventory.SetDirtyAll(), and ActionMode.UpdateInput().
layout
GridLayoutGroup WidgetCurrentTool.layout
Definition at line 40 of file WidgetCurrentTool.cs.
list
UIList WidgetCurrentTool.list
Definition at line 30 of file WidgetCurrentTool.cs.
Referenced by AM_Adv._OnUpdateInput(), CheckDirty(), RebuildSlots(), Select(), and LayerAbility.SetDirty().
MaxPage
const int WidgetCurrentTool.MaxPage = 2 static
Definition at line 18 of file WidgetCurrentTool.cs.
maxSlots
int WidgetCurrentTool.maxSlots = 9
Definition at line 34 of file WidgetCurrentTool.cs.
Referenced by GetNextSelectableIndex(), GetPrevSelectableIndex(), RebuildSlots(), and Select().
placer
UIPlaceHelper WidgetCurrentTool.placer
Definition at line 38 of file WidgetCurrentTool.cs.
Referenced by AM_Adv._OnUpdateInput(), ActPlan._Update(), OnActivate(), and SwitchPage().
selected
int WidgetCurrentTool.selected = -1
Definition at line 44 of file WidgetCurrentTool.cs.
Referenced by GetNextSelectableIndex(), GetPrevSelectableIndex(), OnClickButtonHotItem(), InvOwnerHotbar.OnProcess(), Player.RefreshCurrentHotItem(), RefreshHighlight(), Card.RemoveThing(), Reselect(), and Select().
selectedPage
int WidgetCurrentTool.selectedPage
Definition at line 46 of file WidgetCurrentTool.cs.
Referenced by Select().
SlotsPerPage
const int WidgetCurrentTool.SlotsPerPage = 10 static
Definition at line 16 of file WidgetCurrentTool.cs.
transHighlightSwitch
Transform WidgetCurrentTool.transHighlightSwitch
Definition at line 42 of file WidgetCurrentTool.cs.
Referenced by OnActivate(), and InvOwnerHotbar.OnProcess().
Property Documentation
extra
Extra WidgetCurrentTool.extra get
Definition at line 48 of file WidgetCurrentTool.cs.
Referenced by OnSetContextMenu(), and RebuildSlots().
page
int WidgetCurrentTool.page get set
Definition at line 50 of file WidgetCurrentTool.cs.
    {
        get
        {
            return EMono.player.hotbarPage;
        }
        set
        {
            EMono.player.hotbarPage = value;
        }
    }
Referenced by OnActivate(), RebuildSlots(), Select(), and SwitchPage().
selectedButton
ButtonGrid WidgetCurrentTool.selectedButton get
Definition at line 62 of file WidgetCurrentTool.cs.
Referenced by OnClickButtonHotItem(), Player.RefreshCurrentHotItem(), RefreshHighlight(), Card.RemoveThing(), and Select().
The documentation for this class was generated from the following file:
Elin/WidgetCurrentTool.cs