Elin Decompiled Documentation: WidgetSideScreen Class Reference
WidgetSideScreen Class Reference
Classes
class Extra
Public Member Functions
override object CreateExtra ()
override void OnActivate ()
override void OnSetContextMenu (UIContextMenu m)
void Refresh ()
override void OnChangeResolution ()
void SlideMiniGame (float w)
Public Member Functions inherited from Widget
void Test ()
bool IsInRightMode ()
void Activate ()
void RefreshOrder ()
virtual void OnActivate ()
virtual object CreateExtra ()
void Deactivate ()
virtual void OnDeactivate ()
void Close ()
void Reactivate ()
virtual void OnManagerActivate ()
virtual void OnManagerDeactivate ()
void SetAnchor (RectPosition p)
void SetPivot (RectPosition p)
virtual void OnChangePivot ()
void UpdateConfig ()
virtual void OnUpdateConfig ()
void ClampToScreen ()
virtual void OnChangeResolution ()
void OnChangePosition ()
virtual void OnChangeActionMode ()
virtual void OnFlip ()
bool IsAlignTop ()
Layer AddLayer (Layer l, Transform trans)
void RefreshTipPivotPosition ()
SkinSet GetSkin ()
SkinConfig GetSkinConfig ()
void SetSkin (int id, int v=0)
void TestSkin ()
virtual void ApplySkin ()
virtual void OnApplySkin ()
void InstantiateDeco (SkinDeco deco)
void AddDeco (SkinDeco deco)
void RemoveDeco (SkinDeco deco)
virtual bool CanShowContextMenu ()
void ShowContextMenu ()
void SetBaseContextMenu (UIContextMenu m)
virtual void OnSetContextMenu (UIContextMenu m)
void SetGridContextMenu (UIContextMenu m)
void SoundActivate ()
void OnChangeResolution ()
SkinSet GetSkin ()
SkinConfig GetSkinConfig ()
Public Attributes
Sprite[] sprites
Image imagePic
Public Attributes inherited from Widget
Image imageBG
SoundData soundActivate
UIDragPanel dragPanel
RectTransform tipPivotLeft
RectTransform tipPivotRight
Static Public Attributes
static WidgetSideScreen Instance
Static Public Attributes inherited from EMono
static Core core
Properties
override bool AlwaysBottom [get]
Extra extra [get]
Color bgColor [get, set]
Properties inherited from Widget
string ID [get]
Config config [get]
SkinRoot skinRoot [get]
bool IsSealed [get]
virtual bool ShowStyleMenu [get]
virtual bool AlwaysTop [get]
virtual bool IsStaticPosition [get]
virtual bool AlwaysBottom [get]
virtual Type SetSiblingAfter [get]
virtual bool ShowInBuildMode [get]
virtual bool RightClickToClose [get]
virtual bool AllowRightClickToClose [get]
Properties inherited from EMono
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SoundManager Sound [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static CoreDebug debug [get]
Private Member Functions
void OnEnable ()
void OnDisable ()
Additional Inherited Members
Public Types inherited from Widget
enum WidgetType { Default , ZoomMenu }
enum State { Active , Inactive }
Static Public Member Functions inherited from EMono
static int rnd (int a)
Protected Member Functions inherited from Widget
void ClampToScreenEnsured (Component c, Vector2 anchoredPos)
void ClampToScreen (RectTransform rect, float margin=10f)
Protected Attributes inherited from Widget
bool flip
Detailed Description
Definition at line 4 of file WidgetSideScreen.cs.
Member Function Documentation
CreateExtra()
override object WidgetSideScreen.CreateExtra () inline virtual
Reimplemented from Widget.
Definition at line 43 of file WidgetSideScreen.cs.
    {
        return new Extra();
    }
OnActivate()
override void WidgetSideScreen.OnActivate () inline virtual
Reimplemented from Widget.
Definition at line 48 of file WidgetSideScreen.cs.
    {
        Layer.blurStopInstance = base.transform;
        Refresh();
        OnChangeResolution();
        Instance = this;
    }
References Instance, OnChangeResolution(), and Refresh().
OnChangeResolution()
override void WidgetSideScreen.OnChangeResolution () inline virtual
Reimplemented from Widget.
Definition at line 96 of file WidgetSideScreen.cs.
    {
        base.OnChangeResolution();
        RectTransform rectTransform = this.Rect();
        float x = 0.01f * (float)Screen.width * (float)extra.width / EMono.core.uiScale + 50f;
        float num = (float)Screen.height / EMono.core.uiScale + 50f;
        rectTransform.sizeDelta = new Vector2(x, num);
        if (extra.reverse)
        {
            rectTransform.SetAnchor(0f, 0.5f, 0f, 0.5f);
            rectTransform.anchoredPosition = new Vector2(rectTransform.sizeDelta.x * 0.5f, 0f);
        }
        else
        {
            rectTransform.SetAnchor(1f, 0.5f, 1f, 0.5f);
            rectTransform.anchoredPosition = new Vector2(rectTransform.sizeDelta.x * -0.5f, 0f);
        }
        Refresh();
        imagePic.SetActive(extra.idImage > 0);
        Sprite sprite = sprites[extra.idImage];
        if ((bool)sprite)
        {
            imagePic.sprite = sprite;
            imagePic.rectTransform.sizeDelta = new Vector2(num * (float)sprite.texture.width / (float)sprite.texture.height, num);
            imagePic.color = bgColor;
        }
        if (extra.alignUI)
        {
            if (extra.reverse)
            {
                EMono.ui.rectLayers.anchoredPosition = new Vector2(rectTransform.sizeDelta.x / 2f, 0f);
                EMono.ui.rectLayers.sizeDelta = new Vector2(0f - rectTransform.sizeDelta.x, 0f);
                SlideMiniGame(rectTransform.sizeDelta.x);
            }
            else
            {
                EMono.ui.rectLayers.anchoredPosition = new Vector2((0f - rectTransform.sizeDelta.x) / 2f, 0f);
                EMono.ui.rectLayers.sizeDelta = new Vector2(0f - rectTransform.sizeDelta.x, 0f);
                SlideMiniGame(0f - rectTransform.sizeDelta.x);
            }
        }
        else
        {
            EMono.ui.rectLayers.anchoredPosition = Vector2.zero;
            EMono.ui.rectLayers.sizeDelta = Vector2.zero;
            SlideMiniGame(0f);
        }
    }
References WidgetSideScreen.Extra.alignUI, bgColor, EMono.core, extra, WidgetSideScreen.Extra.idImage, imagePic, Refresh(), WidgetSideScreen.Extra.reverse, SlideMiniGame(), sprites, and Core.uiScale.
Referenced by Game.Load(), OnActivate(), and OnSetContextMenu().
OnDisable()
void WidgetSideScreen.OnDisable () inline private
Definition at line 158 of file WidgetSideScreen.cs.
    {
        EMono.scene.cam.rect = new Rect(0f, 0f, 1f, 1f);
        EMono.ui.rectLayers.anchoredPosition = Vector2.zero;
        EMono.ui.rectLayers.sizeDelta = Vector2.zero;
        SlideMiniGame(0f);
    }
References SlideMiniGame().
OnEnable()
void WidgetSideScreen.OnEnable () inline private
Definition at line 153 of file WidgetSideScreen.cs.
    {
        Refresh();
    }
References Refresh().
OnSetContextMenu()
override void WidgetSideScreen.OnSetContextMenu (UIContextMenu m) inline virtual
Reimplemented from Widget.
Definition at line 56 of file WidgetSideScreen.cs.
    {
        _ = base.config.skin;
        UIContextMenu uIContextMenu = m.AddChild("setting");
        uIContextMenu.AddToggle("alignUI", extra.alignUI, delegate
        {
            extra.alignUI = !extra.alignUI;
            OnChangeResolution();
        });
        uIContextMenu.AddToggle("reverse", extra.reverse, delegate
        {
            extra.reverse = !extra.reverse;
            OnChangeResolution();
        });
        uIContextMenu.AddSlider("width", (float a) => a.ToString() ?? "", extra.width, delegate(float a)
        {
            extra.width = (int)a;
            OnChangeResolution();
        }, 10f, 50f, isInt: true);
        uIContextMenu.AddSlider("image", (float a) => a.ToString() ?? "", extra.idImage, delegate(float a)
        {
            extra.idImage = (int)a;
            OnChangeResolution();
        }, 0f, sprites.Length - 1, isInt: true);
        uIContextMenu.AddButton("colorBG", delegate
        {
            EMono.ui.AddLayer<LayerColorPicker>().SetColor(bgColor, Color.white, delegate(PickerState state, Color _c)
            {
                bgColor = _c;
                OnChangeResolution();
            });
        });
        SetBaseContextMenu(m);
    }
References UIContextMenu.AddButton(), UIContextMenu.AddChild(), UIContextMenu.AddSlider(), UIContextMenu.AddToggle(), WidgetSideScreen.Extra.alignUI, bgColor, Color, extra, WidgetSideScreen.Extra.idImage, OnChangeResolution(), WidgetSideScreen.Extra.reverse, Widget.SetBaseContextMenu(), EMono.ui, and WidgetSideScreen.Extra.width.
Refresh()
void WidgetSideScreen.Refresh () inline
Definition at line 91 of file WidgetSideScreen.cs.
    {
        EMono.scene.cam.rect = (extra.reverse ? new Rect(0.01f * (float)extra.width, 0f, 1f + 0.01f * (float)extra.width, 1f) : new Rect(-0.01f * (float)extra.width, 0f, 1f, 1f));
    }
References extra, and WidgetSideScreen.Extra.width.
Referenced by OnActivate(), OnChangeResolution(), and OnEnable().
SlideMiniGame()
void WidgetSideScreen.SlideMiniGame (float w) inline
Definition at line 145 of file WidgetSideScreen.cs.
    {
        if ((bool)LayerMiniGame.Instance)
        {
            LayerMiniGame.Instance.mini.SlidePosition(w * EMono.core.uiScale);
        }
    }
References EMono.core, LayerMiniGame.Instance, LayerMiniGame.mini, MiniGame.SlidePosition(), and Core.uiScale.
Referenced by OnChangeResolution(), and OnDisable().
Member Data Documentation
imagePic
Image WidgetSideScreen.imagePic
Definition at line 25 of file WidgetSideScreen.cs.
Referenced by OnChangeResolution().
Instance
WidgetSideScreen WidgetSideScreen.Instance static
Definition at line 21 of file WidgetSideScreen.cs.
Referenced by Game.Load(), OnActivate(), LayerMiniGame.OnAfterInit(), LayerMiniGame.OnKill(), and UI.ToggleCanvas().
sprites
Sprite [] WidgetSideScreen.sprites
Definition at line 23 of file WidgetSideScreen.cs.
Referenced by OnChangeResolution().
Property Documentation
AlwaysBottom
override bool WidgetSideScreen.AlwaysBottom get
Definition at line 27 of file WidgetSideScreen.cs.
bgColor
Color WidgetSideScreen.bgColor get set
Definition at line 31 of file WidgetSideScreen.cs.
    {
        get
        {
            return IntColor.FromInt(extra.bgColor);
        }
        set
        {
            extra.bgColor = IntColor.ToInt(ref value);
        }
    }
Referenced by OnChangeResolution(), and OnSetContextMenu().
extra
Extra WidgetSideScreen.extra get
Definition at line 29 of file WidgetSideScreen.cs.
Referenced by OnChangeResolution(), OnSetContextMenu(), and Refresh().
The documentation for this class was generated from the following file:
Elin/WidgetSideScreen.cs