Elin Decompiled Documentation: NotificationCondition Class Reference
NotificationCondition Class Reference
Public Member Functions
override bool ShouldRemove ()
override int GetSortVal ()
override void OnClick ()
override void OnRefresh ()
Public Member Functions inherited from BaseNotification
virtual ItemNotice GetMold ()
virtual LayoutGroup GetLayoutGroup ()
virtual int GetSortVal ()
void Refresh ()
virtual void OnClick ()
virtual void OnRefresh ()
virtual bool ShouldRemove ()
virtual void OnInstantiate ()
Public Attributes
Condition condition
Public Attributes inherited from BaseNotification
ItemNotice item
string text
string lastText
Properties
override bool Visible [get]
override bool Interactable [get]
override Action< UITooltip > onShowTooltip [get]
override Sprite Sprite [get]
Properties inherited from BaseNotification
virtual Sprite Sprite [get]
virtual int idSprite [get]
virtual bool Visible [get]
virtual bool Interactable [get]
virtual Action< UITooltip > onShowTooltip [get]
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Additional Inherited Members
Static Public Member Functions inherited from EClass
static int rndSeed (int a, int seed)
static int rnd (long a)
static int rnd (int a)
static int curve (int a, int start, int step, int rate=75)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Static Public Attributes inherited from EClass
static Core core
Detailed Description
Definition at line 4 of file NotificationCondition.cs.
Member Function Documentation
GetSortVal()
override int NotificationCondition.GetSortVal () inline virtual
Reimplemented from BaseNotification.
Definition at line 32 of file NotificationCondition.cs.
    {
        int num = 5;
        WidgetStats instance = WidgetStats.Instance;
        bool sort = instance.extra.sort;
        bool sort_ascend = instance.extra.sort_ascend;
        switch (condition.Type)
        {
        case ConditionType.Stance:
            num = 0;
            break;
        case ConditionType.Buff:
            num = 10;
            break;
        case ConditionType.Debuff:
            num = ((!sort) ? 10 : (sort_ascend ? 9 : 11));
            break;
        }
        if (condition is ConBuffStats)
        {
            num = 1;
        }
        if (condition is ConAwakening)
        {
            num = 2;
        }
        int num2 = (sort ? condition.GetSortVal() : instance.list.IndexOf(this));
        if ((!sort && !sort_ascend) || (sort && sort_ascend))
        {
            num2 = 100000 - num2;
        }
        return 8000000 + num * 100000 + num2;
    }
References condition, WidgetStats.extra, BaseStats.GetSortVal(), WidgetStats.Instance, BaseWidgetNotice.list, WidgetStats.Extra.sort, WidgetStats.Extra.sort_ascend, and BaseStats.Type.
OnClick()
override void NotificationCondition.OnClick () inline virtual
Reimplemented from BaseNotification.
Definition at line 66 of file NotificationCondition.cs.
    {
        if (condition.CanManualRemove)
        {
            SE.Trash();
            condition.Kill();
            WidgetStats.RefreshAll();
            if ((bool)WidgetStats.Instance)
            {
                WidgetStats.Instance.layout.RebuildLayout();
            }
        }
        else
        {
            SE.Beep();
        }
    }
References BaseCondition.CanManualRemove, condition, WidgetStats.Instance, Condition.Kill(), BaseWidgetNotice.layout, and WidgetStats.RefreshAll().
OnRefresh()
override void NotificationCondition.OnRefresh () inline virtual
Reimplemented from BaseNotification.
Definition at line 84 of file NotificationCondition.cs.
    {
        text = condition.GetText() + (EClass.debug.showExtra ? (" " + condition.value) : "");
        item.button.mainText.color = condition.GetColor(item.button.skinRoot.GetButton().colorProf);
    }
References ItemNotice.button, SkinAsset_Button.colorProf, condition, BaseSkinRoot.GetButton(), BaseCondition.GetColor(), BaseCondition.GetText(), BaseNotification.item, UIButton.skinRoot, BaseNotification.text, and BaseCondition.value.
ShouldRemove()
override bool NotificationCondition.ShouldRemove () inline virtual
Reimplemented from BaseNotification.
Definition at line 19 of file NotificationCondition.cs.
    {
        if (condition.IsKilled)
        {
            return true;
        }
        if (EClass.core.IsGameStarted && !EClass.pc.conditions.Contains(condition))
        {
            return true;
        }
        return false;
    }
References condition, Chara.conditions, EClass.core, Core.IsGameStarted, Condition.IsKilled, and EClass.pc.
Referenced by WidgetStats.OnRefresh().
Member Data Documentation
condition
Condition NotificationCondition.condition
Definition at line 6 of file NotificationCondition.cs.
Referenced by GetSortVal(), OnClick(), NotificationBuff.OnInstantiate(), NotificationBuff.OnRefresh(), OnRefresh(), WidgetStats.OnRefresh(), and ShouldRemove().
Property Documentation
Interactable
override bool NotificationCondition.Interactable get
Definition at line 10 of file NotificationCondition.cs.
onShowTooltip
override Action<UITooltip> NotificationCondition.onShowTooltip get
Definition at line 12 of file NotificationCondition.cs.
Sprite
override Sprite NotificationCondition.Sprite get
Definition at line 17 of file NotificationCondition.cs.
Visible
override bool NotificationCondition.Visible get
Definition at line 8 of file NotificationCondition.cs.
The documentation for this class was generated from the following file:
Elin/NotificationCondition.cs