Elin Decompiled Documentation: LayerMod Class Reference
LayerMod Class Reference
Public Member Functions
override void OnInit ()
void Refresh ()
override void OnKill ()
Public Member Functions inherited from ELayer
override void OnBeforeAddLayer ()
void InitInspector ()
sealed override void Init ()
override void OnAfterAddLayer ()
void TryShowHelp ()
void AddLayerToUI (string id)
void TryShowHint (string _langHint=null)
void TalkHomeMemeber (string id)
void TalkMaid (string id)
override void OnRightClick ()
Public Member Functions inherited from Layer
virtual string GetTextHeader (Window window)
virtual bool HeaderIsListOf (int id)
virtual void Init ()
virtual void OnInit ()
virtual void OnAfterInit ()
virtual void ApplySkin ()
void ShowScreenLock (string id)
void UpdateInput ()
virtual void OnUpdateInput ()
virtual void OnRightClick ()
virtual bool OnBack ()
virtual void OnChangeLayer ()
virtual void OnCreate ()
void _AddLayer (string id)
Layer AddLayer (string id)
T AddLayer< T > ()
T AddLayer< T > (string id)
T AddLayerDontCloseOthers< T > ()
Layer AddLayerDontCloseOthers (Layer l)
T GetOrAddLayer< T > ()
virtual void OnBeforeAddLayer ()
virtual void OnAfterAddLayer ()
Layer AddLayer (Layer l)
void ToggleLayer (string id)
T ToggleLayer< T > (string id=null)
void WaitAndClose ()
void OnClickClose ()
virtual void Close ()
void CloseLayers ()
void RemoveLayers (bool removeImportant=false)
bool RemoveLayer< T > ()
void RemoveLayer (Layer l)
virtual void OnKill ()
Layer SetOnKill (Action action)
void DisableClose ()
void Delay (float duration=0.05f)
Layer SetDelay (float d)
Layer GetLayer (string id)
T GetLayer< T > (bool fromTop=false)
Layer GetTopLayer ()
void SwitchContent (int idWindow, int i)
virtual void OnSwitchContent (Window window)
Layer SetTitles (string langList, string idHeaderRow=null)
bool IsBlockWidgetClick ()
bool IsHideHud ()
bool IsAllowGeneralInput ()
bool IsUseBlur ()
bool IsPointerOnLayer ()
void ApplySkin ()
Public Attributes
UIList list
UIList list2
UIText textRestart
UIButton toggleDisableMods
Public Attributes inherited from Layer
Option option
UnityEvent onKill
Anime animeIn
Anime animeOut
bool closeOthers
bool defaultActionMode = true
Button screenLock
Layer parent
string idLayer
List< Layer > layers = new List<Layer>()
Vector2 lastParentPos
List< Window > windows = new List<Window>()
string langHint
Static Public Attributes
static LayerMod Instance
Static Public Attributes inherited from Layer
static int skipInput
static bool closeOnRightClick
static bool rightClicked
static bool cancelKeyDown
static bool ignoreSounds
static Transform blurStopInstance
static string[] searchPath = new string[3] { "Layer", "Layer/Dialog", "Layer/LayerHome" }
Properties
ModManager manager [get]
Properties inherited from ELayer
static Core core [get]
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static FactionBranch Branch [get]
static Faction Home [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static CoreConfig config [get]
static GameSetting setting [get]
static ColorProfile Colors [get]
static SourceManager sources [get]
static World world [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
bool IsFloat [get]
virtual string IdHelp [get]
Properties inherited from Layer
Layer TopLayer [get]
string uid [get]
virtual RectTransform rectLayers [get]
virtual bool blockWidgetClick [get]
Additional Inherited Members
Static Public Member Functions inherited from ELayer
static int rnd (int a)
Static Public Member Functions inherited from Layer
static T Create< T > ()
static T Create< T > (string path)
static Layer Create (string path)
Protected Member Functions inherited from ELayer
sealed override void _Close ()
sealed override void Kill ()
Protected Member Functions inherited from Layer
virtual void Awake ()
virtual void _Close ()
virtual void Kill ()
Protected Attributes inherited from Layer
RectTransform _rect
bool isDestroyed
Detailed Description
Definition at line 3 of file LayerMod.cs.
Member Function Documentation
OnInit()
override void LayerMod.OnInit () inline virtual
Reimplemented from Layer.
Definition at line 17 of file LayerMod.cs.
    {
        textRestart.SetActive(enable: false);
        toggleDisableMods.SetToggle(ELayer.config.other.disableMods, delegate(bool on)
        {
            ELayer.config.other.disableMods = on;
            ELayer.config.Save();
            textRestart.SetActive(enable: true);
        });
        Instance = this;
        UIList uIList = list;
        UIList uIList2 = list2;
        UIList.Callback<BaseModPackage, ItemMod> obj = new UIList.Callback<BaseModPackage, ItemMod>
        {
            onClick = delegate
            {
            },
            onInstantiate = delegate(BaseModPackage a, ItemMod b)
            {
                a.UpdateMeta(updateOnly: true);
                b.package = a;
                string s = ELayer.core.mods.packages.IndexOf(a) + 1 + ". " + (a.isInPackages ? "[Local] " : "") + a.title;
                b.buttonActivate.mainText.SetText(s, (!a.IsValidVersion()) ? FontColor.Bad : (a.activated ? FontColor.ButtonGeneral : FontColor.Passive));
                b.buttonActivate.subText.text = a.version;
                b.buttonLock.mainText.text = a.author;
                b.buttonUp.SetActive(!a.builtin);
                b.buttonDown.SetActive(!a.builtin);
                b.buttonToggle.SetToggle(a.willActivate);
                b.buttonUp.SetOnClick(delegate
                {
                    Move(a, b, -1);
                });
                b.buttonDown.SetOnClick(delegate
                {
                    Move(a, b, 1);
                });
                UIButton bt = b.buttonToggle;
                bt.SetOnClick(delegate
                {
                    a.willActivate = !a.willActivate;
                    bt.SetToggle(a.willActivate);
                    ELayer.core.mods.SaveLoadOrder();
                    textRestart.SetActive(enable: true);
                });
                bt.interactable = !a.builtin;
                b.buttonActivate.onClick.AddListener(delegate
                {
                    Refresh();
                    UIContextMenu uIContextMenu = ELayer.ui.CreateContextMenuInteraction();
                    if (ELayer.debug.enable || (!BaseCore.IsOffline && a.isInPackages && !a.builtin && !ELayer.core.version.demo))
                    {
                        uIContextMenu.AddButton("mod_publish", delegate
{
                            Core.TryWarnUpload(delegate
{
                                Dialog.YesNo("mod_publish_warn".lang(a.title, a.id, a.author), delegate
{
                                    ELayer.core.steam.CreateUserContent(a);
                                });
                            });
                        });
                    }
                    if (!a.builtin)
                    {
                        uIContextMenu.AddButton(a.willActivate ? "mod_deactivate" : "mod_activate", delegate
{
                            SE.Click();
                            a.willActivate = !a.willActivate;
                            ELayer.core.mods.SaveLoadOrder();
                            list.List();
                            textRestart.SetActive(enable: true);
                        });
                    }
                    uIContextMenu.AddButton("mod_info", delegate
                    {
                        SE.Click();
                        Util.ShowExplorer(a.dirInfo.FullName + "/package.xml");
                    });
                    uIContextMenu.Show();
                });
                b.buttonLock.onClick.AddListener(delegate
                {
                    Refresh();
                });
            },
            onList = delegate
            {
                foreach (BaseModPackage package in manager.packages)
                {
                    if (package.builtin)
                    {
                        list2.Add(package);
                    }
                    else
                    {
                        list.Add(package);
                    }
                }
            },
            onRefresh = Refresh
        };
        UIList.ICallback callbacks = obj;
        uIList2.callbacks = obj;
        uIList.callbacks = callbacks;
        list.List();
        list2.List();
        void Move(BaseModPackage p, ItemMod b, int a)
        {
            List<BaseModPackage> packages = ELayer.core.mods.packages;
            int num = packages.IndexOf(p);
            if (num + a < 0 || num + a >= packages.Count || packages[num + a].builtin)
            {
                SE.BeepSmall();
            }
            else
            {
                packages.Move(p, a);
                SE.Tab();
                textRestart.SetActive(enable: true);
                ELayer.core.mods.SaveLoadOrder();
                list.List();
            }
        }
    }
References UIList.Add(), UIContextMenu.AddButton(), BaseModPackage.author, BaseModPackage.builtin, ItemMod.buttonActivate, ItemMod.buttonDown, ItemMod.buttonLock, ItemMod.buttonToggle, ItemMod.buttonUp, ELayer.config, ELayer.core, ELayer.debug, Version.demo, BaseModPackage.dirInfo, CoreConfig.OtherSetting.disableMods, CoreDebug.enable, BaseModPackage.id, Instance, BaseModPackage.isInPackages, BaseCore.IsOffline, BaseModPackage.IsValidVersion(), list, UIList.List(), list2, UIButton.mainText, manager, Core.mods, CoreConfig.other, BaseModManager.packages, Refresh(), CoreConfig.Save(), ModManager.SaveLoadOrder(), UIText.SetText(), UIButton.SetToggle(), UIContextMenu.Show(), textRestart, BaseModPackage.title, toggleDisableMods, Core.TryWarnUpload(), ELayer.ui, BaseModPackage.UpdateMeta(), Util, BaseCore.version, BaseModPackage.version, BaseModPackage.willActivate, and Dialog.YesNo().
OnKill()
override void LayerMod.OnKill () inline virtual
Reimplemented from Layer.
Definition at line 146 of file LayerMod.cs.
    {
        ELayer.core.mods.SaveLoadOrder();
    }
References ELayer.core, Core.mods, and ModManager.SaveLoadOrder().
Refresh()
void LayerMod.Refresh () inline
Definition at line 142 of file LayerMod.cs.
    {
    }
Referenced by OnInit().
Member Data Documentation
Instance
LayerMod LayerMod.Instance static
Definition at line 5 of file LayerMod.cs.
Referenced by OnInit().
list
UIList LayerMod.list
Definition at line 7 of file LayerMod.cs.
Referenced by OnInit().
list2
UIList LayerMod.list2
Definition at line 9 of file LayerMod.cs.
Referenced by OnInit().
textRestart
UIText LayerMod.textRestart
Definition at line 11 of file LayerMod.cs.
Referenced by OnInit().
toggleDisableMods
UIButton LayerMod.toggleDisableMods
Definition at line 13 of file LayerMod.cs.
Referenced by OnInit().
Property Documentation
manager
ModManager LayerMod.manager get
Definition at line 15 of file LayerMod.cs.
Referenced by OnInit().
The documentation for this class was generated from the following file:
Elin/LayerMod.cs