Elin Decompiled Documentation: LayerEquip Class Reference
LayerEquip Class Reference
Public Member Functions
override void OnInit ()
void Rebuild ()
void Redraw ()
void RefreshToolBelt (bool rebuildLayout=false)
void RefreshEquipment (UIList list, bool etc=false)
Public Member Functions inherited from ELayer
override void OnBeforeAddLayer ()
void InitInspector ()
sealed override void Init ()
override void OnAfterAddLayer ()
void TryShowHelp ()
void AddLayerToUI (string id)
void TryShowHint (string _langHint=null)
void TalkHomeMemeber (string id)
void TalkMaid (string id)
override void OnRightClick ()
Static Public Member Functions
static void SetDirty ()
Static Public Member Functions inherited from ELayer
static int rnd (int a)
Public Attributes
UIList listMain
UIList listEtc
Chara chara
Static Public Attributes
static LayerEquip Instance
static bool dirty
Additional Inherited Members
Protected Member Functions inherited from ELayer
sealed override void _Close ()
sealed override void Kill ()
Properties inherited from ELayer
static Core core [get]
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static FactionBranch Branch [get]
static Faction Home [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static CoreConfig config [get]
static GameSetting setting [get]
static ColorProfile Colors [get]
static SourceManager sources [get]
static World world [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
bool IsFloat [get]
virtual string IdHelp [get]
Detailed Description
Definition at line 3 of file LayerEquip.cs.
Member Function Documentation
OnInit()
override void LayerEquip.OnInit () inline
Definition at line 20 of file LayerEquip.cs.
    {
        windows[0].layer = this;
        if (!Window.dictData.ContainsKey(windows[0].idWindow) && !ELayer.ui.widgets.GetWidget("BottomBar"))
        {
            RectTransform rectTransform = windows[0].Rect();
            windows[0].Rect().anchoredPosition = new Vector2(rectTransform.anchoredPosition.x, 45f);
        }
        chara = ELayer.pc;
        Instance = this;
        Rebuild();
    }
References chara, Instance, ELayer.pc, Rebuild(), and ELayer.ui.
Rebuild()
void LayerEquip.Rebuild () inline
Definition at line 33 of file LayerEquip.cs.
    {
        RefreshEquipment(listMain);
        RefreshEquipment(listEtc, etc: true);
        RefreshToolBelt();
        windows[0].RebuildLayout(recursive: true);
        dirty = true;
    }
References dirty, listEtc, listMain, RefreshEquipment(), and RefreshToolBelt().
Referenced by OnInit().
Redraw()
void LayerEquip.Redraw () inline
Definition at line 42 of file LayerEquip.cs.
    {
        dirty = false;
        listMain.Redraw();
        listEtc.Redraw();
    }
References dirty, listEtc, and listMain.
RefreshEquipment()
void LayerEquip.RefreshEquipment (UIList list, bool etc = false) inline
Definition at line 53 of file LayerEquip.cs.
    {
        list.Clear();
        list.callbacks = new UIList.Callback<BodySlot, ButtonGridDrag>
        {
            onInstantiate = delegate(BodySlot a, ButtonGridDrag b)
            {
                b.SetBodySlot(a, new InvOwnerEquip(chara, a), showIndex: true);
            },
            onRedraw = delegate(BodySlot a, ButtonGridDrag b, int i)
            {
                b.SetBodySlot(a, new InvOwnerEquip(chara, a), showIndex: true);
            },
            onSort = (BodySlot a, UIList.SortMode b) => chara.body.GetSortVal(a),
            onList = delegate
            {
                foreach (BodySlot slot in chara.body.slots)
                {
                    if (slot.elementId != 44)
                    {
                        if (slot.elementId == 36 || slot.elementId == 31 || slot.elementId == 37 || slot.elementId == 45)
{
                            if (!etc)
{
                                continue;
                            }
                        }
                        else if (etc)
{
                            continue;
                        }
                        list.Add(slot);
                    }
                }
            }
        };
        list.sortMode = UIList.SortMode.ByNumber;
        list.List();
    }
References Chara.body, chara, BodySlot.elementId, CharaBody.GetSortVal(), ButtonGrid.SetBodySlot(), and CharaBody.slots.
Referenced by Rebuild().
RefreshToolBelt()
void LayerEquip.RefreshToolBelt (bool rebuildLayout = false) inline
Definition at line 49 of file LayerEquip.cs.
    {
    }
Referenced by Rebuild().
SetDirty()
static void LayerEquip.SetDirty () inline static
Definition at line 15 of file LayerEquip.cs.
    {
        dirty = true;
    }
References dirty.
Member Data Documentation
chara
Chara LayerEquip.chara
Definition at line 13 of file LayerEquip.cs.
Referenced by OnInit(), and RefreshEquipment().
dirty
bool LayerEquip.dirty static
Definition at line 7 of file LayerEquip.cs.
Referenced by Rebuild(), Redraw(), and SetDirty().
Instance
LayerEquip LayerEquip.Instance static
Definition at line 5 of file LayerEquip.cs.
Referenced by OnInit().
listEtc
UIList LayerEquip.listEtc
Definition at line 11 of file LayerEquip.cs.
Referenced by Rebuild(), and Redraw().
listMain
UIList LayerEquip.listMain
Definition at line 9 of file LayerEquip.cs.
Referenced by Rebuild(), and Redraw().
The documentation for this class was generated from the following file:
Elin/LayerEquip.cs