Elin Decompiled Documentation: Recipe Class Reference
Recipe Class Reference
Classes
class Ingredient
Public Types
enum State { Valid , Invalid }
enum IngType { Default , CreativeFood }
Public Member Functions
bool IsStaticLV ()
int GetQualityBonus ()
virtual int GetRefVal ()
virtual string GetIdThing ()
virtual bool ShouldShowHighlight (HitResult r)
BaseTileSelector.BoxType GetBoxType ()
int GetDefaultColor ()
virtual SourceMaterial.Row GetMainMaterial ()
virtual SourceMaterial.Row GetColorMaterial ()
virtual void BuildIngredientList ()
void BuildIngredientList (Thing t)
virtual void OnChangeIngredient ()
virtual Thing Craft (BlessedState blessed, bool sound=false, List< Thing > ings=null, TraitCrafter crafter=null, bool model=false)
bool HasSameTile (Point point, int dir, int altitude, int bridgeHeight)
virtual void Build (TaskBuild task)
virtual void Build (Chara chara, Card t, Point pos, int mat, int dir, int altitude, int bridgeHeight)
virtual void OnRenderMarker (Point point, bool active, HitResult result, bool main, int dir, int bridgeHeight)
string GetName ()
virtual string GetDetail ()
virtual void WriteNote (UINote n)
void WriteReqFactory (UINote n, bool hasFactory=true)
void WriteReqSkill (UINote n)
virtual IRenderer GetRenderer ()
virtual void OnSelected ()
virtual void OnChangeAltitude (int a)
virtual void Rotate ()
virtual void SetDir (int d)
virtual Recipe Duplicate ()
virtual void SetImage (Image icon)
bool IsCraftable ()
int GetMaxCount ()
void SetTextDifficulty (UIText text)
int GetSortVal ()
bool HasFirstTimeBonus ()
void TryGetFirstTimeBonus ()
void SaveLastIngredients ()
QuestTrackCraft GetQuestTrack ()
void ToggleTrack (QuestTrackCraft quest)
Static Public Member Functions
static Recipe GetOrCreate (string id)
static Recipe Create (RecipeSource _source, int idMat=-1, Thing ing=null)
static Recipe Create (Thing t)
static void DropIngredients (string id, string idMatMain, int num=1)
Static Public Member Functions inherited from EClass
static int rndSeed (int a, int seed)
static int rnd (long a)
static int rnd (int a)
static int curve (int a, int start, int step, int rate=75)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Public Attributes
string id
List< Ingredient > ingredients = new List<Ingredient>()
bool UseStock
bool IngAsProduct
bool VirtualBlock
int _dir
int sync
int idMat = -1
int idSkin
State state
RecipeSource _source
Static Public Attributes
static Dictionary< string, Recipe > recipeCache = new Dictionary<string, Recipe>()
Static Public Attributes inherited from EClass
static Core core
Properties
RecipeSource source [get]
SourceMaterial.Row DefaultMaterial [get]
virtual TileRow tileRow [get]
virtual RenderRow renderRow [get]
string Name [get]
virtual TileType tileType [get]
virtual bool IsFloorOrBridge [get]
int MaxAltitude [get]
int RecipeLv [get]
bool IsFloor [get]
bool IsObj [get]
virtual bool IsBlock [get]
bool IsWallOrFence [get]
bool IsBridge [get]
virtual bool IsThing [get]
virtual Card Mold [get]
virtual int W [get]
virtual int H [get]
virtual bool RequireIngredients [get]
bool MultiSize [get]
BaseTileSelector tileSelector [get]
virtual int CostMoney [get]
virtual bool CanRotate [get]
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Detailed Description
Definition at line 6 of file Recipe.cs.
Member Enumeration Documentation
IngType
enum Recipe.IngType
Enumerator
Default
CreativeFood
Definition at line 14 of file Recipe.cs.
    {
        Default,
        CreativeFood
    }
State
enum Recipe.State
Enumerator
Valid
Invalid
Definition at line 8 of file Recipe.cs.
    {
        Valid,
        Invalid
    }
Member Function Documentation
Build() [1/2]
virtual void Recipe.Build (Chara chara, Card t, Point pos, int mat, int dir, int altitude, int bridgeHeight) inline virtual
Reimplemented in RecipeBridgePillar, and RecipeCard.
Definition at line 628 of file Recipe.cs.
    {
        if (mat == -1)
        {
            mat = 2;
        }
        EClass.pc.PlaySound(EClass.sources.materials.rows[mat].GetSoundImpact());
        pos.cell.isModified = true;
        switch (source.type)
        {
        case "Block":
        {
            int ramp = tileRow.id;
            if (ramp == 3)
            {
                ramp = EClass.sources.materials.rows[mat].ramp;
            }
            if (EClass.scene.actionMode.IsRoofEditMode())
            {
                EClass._map.SetRoofBlock(pos.x, pos.z, mat, ramp, dir, altitude);
                break;
            }
            if (pos.HasObj && !pos.sourceObj.tileType.CanBuiltOnBlock)
            {
                EClass._map.MineObjSound(pos);
                EClass._map.SetObj(pos.x, pos.z);
            }
            EClass._map.SetBlock(pos.x, pos.z, mat, ramp, dir);
            if (tileType.IsBlockPass && pos.HasChara)
            {
                foreach (Chara item in pos.ListCharas())
                {
                    chara.Kick(item, ignoreSelf: false, karmaLoss: false);
                }
            }
            if (tileType.AltitudeAsDir)
            {
                pos.cell.objDir = dir;
            }
            {
                foreach (Card item2 in pos.ListCards())
                {
                    if (item2.isThing && item2.placeState == PlaceState.roaming)
                    {
                        item2._Move(item2.pos.GetNearestPoint());
                    }
                }
                break;
            }
        }
        case "Floor":
            if (pos.HasObj && pos.sourceObj.tileType.RemoveOnFloorChange && (!BuildMenu.Instance || !EClass.debug.ignoreBuildRule))
            {
                EClass._map.SetObj(pos.x, pos.z);
            }
            EClass._map.SetFloor(pos.x, pos.z, mat, tileRow.id, dir);
            break;
        case "Bridge":
            if (pos.sourceObj.tileType.RemoveOnFloorChange)
            {
                EClass._map.SetObj(pos.x, pos.z);
            }
            EClass._map.SetBridge(pos.x, pos.z, Mathf.Clamp(bridgeHeight + altitude, 0, 255), mat, tileRow.id, dir);
            break;
        case "Obj":
            EClass._map.SetObj(pos.x, pos.z, mat, tileRow.id, 1, dir, ignoreRandomMat: true);
            if (tileType.ChangeBlockDir || pos.growth is GrowSystemTreeSingle)
            {
                EClass._map.SetBlockDir(pos.x, pos.z, dir);
            }
            if (pos.growth != null)
            {
                pos.growth.SetDefaultStage();
            }
            break;
        }
    }
References EClass._map, Card._Move(), Scene.actionMode, TileType.AltitudeAsDir, TileType.ChangeBlockDir, EClass.debug, Point.GetNearestPoint(), Point.growth, Point.HasChara, Point.HasObj, TileRow.id, CoreDebug.ignoreBuildRule, BuildMenu.Instance, TileType.IsBlockPass, ActionMode.IsRoofEditMode(), Card.isThing, item, Chara.Kick(), Point.ListCards(), Point.ListCharas(), SourceManager.materials, Map.MineObjSound(), EClass.pc, Card.placeState, Card.PlaySound(), Card.pos, EClass.scene, Map.SetBlock(), Map.SetBlockDir(), Map.SetBridge(), GrowSystem.SetDefaultStage(), Map.SetFloor(), Map.SetObj(), Map.SetRoofBlock(), source, Point.sourceObj, EClass.sources, tileRow, tileType, RecipeSource.type, Point.x, and Point.z.
Build() [2/2]
virtual void Recipe.Build (TaskBuild task) inline virtual
Reimplemented in RecipeCard, and RecipeCustom.
Definition at line 623 of file Recipe.cs.
    {
        Build(task.owner, null, task.pos, (ingredients.Count > 0) ? ingredients[0].mat : task.recipe.idMat, task.dir, task.altitude, task.bridgeHeight);
    }
References TaskBuild.altitude, TaskBuild.bridgeHeight, Build, TaskBuild.dir, idMat, ingredients, AIAct.owner, TaskPoint.pos, and TaskBuild.recipe.
Referenced by TaskBuild.OnProgressComplete().
BuildIngredientList() [1/2]
virtual void Recipe.BuildIngredientList () inline virtual
Reimplemented in RecipeCard.
Definition at line 527 of file Recipe.cs.
    {
        if (!UseStock && RequireIngredients)
        {
            ingredients = source.GetIngredients();
        }
    }
References RecipeSource.GetIngredients(), ingredients, RequireIngredients, source, and UseStock.
Referenced by Create(), RecipeManager.Create(), DropIngredients(), BuildMenu.RefreshCategory(), and LayerCraft.RefreshCategory().
BuildIngredientList() [2/2]
void Recipe.BuildIngredientList (Thing t) inline
Definition at line 535 of file Recipe.cs.
    {
        UseStock = true;
        Ingredient item = new Ingredient
        {
            id = t.id,
            tag = null,
            req = 1,
            uid = t.uid,
            thing = t,
            mat = t.material.id
        };
        ingredients.Add(item);
    }
References Card.id, ingredients, item, Card.uid, and UseStock.
Craft()
virtual Thing Recipe.Craft (BlessedState blessed, bool sound = false, List< Thing > ings = null, TraitCrafter crafter = null, bool model = false) inline virtual
Reimplemented in RecipeCard.
Definition at line 554 of file Recipe.cs.
    {
        Thing thing = null;
        string type = source.type;
        thing = ((type == "Block") ? ThingGen.CreateBlock(tileRow.id, GetMainMaterial().id) : ((!(type == "Obj")) ? ThingGen.CreateFloor(tileRow.id, GetMainMaterial().id, source.isBridge) : ThingGen.CreateObj(tileRow.id, GetMainMaterial().id)));
        if (thing == null)
        {
            return null;
        }
        thing.trait.OnCrafted(this, ings);
        thing.SetBlessedState(blessed);
        if (model)
        {
            return thing;
        }
        Msg.Say("crafted", thing);
        thing = EClass.pc.AddCard(thing) as Thing;
        if (thing.GetRootCard() == EClass.pc)
        {
            EClass.pc.HoldCard(thing);
        }
        return thing;
    }
References Card.AddCard(), ThingGen.CreateBlock(), ThingGen.CreateFloor(), ThingGen.CreateObj(), GetMainMaterial(), Card.GetRootCard(), Chara.HoldCard(), TileRow.id, RecipeSource.isBridge, Trait.OnCrafted(), EClass.pc, Msg.Say(), Card.SetBlessedState(), source, tileRow, Card.trait, and RecipeSource.type.
Referenced by TaskCraft.OnProgressComplete(), LayerCraft.RefreshProduct(), and AI_UseCrafter.Run().
Create() [1/2]
static Recipe Recipe.Create (RecipeSource _source, int idMat = -1, Thing ing = null) inline static
Definition at line 326 of file Recipe.cs.
    {
        string type = _source.type;
        Recipe recipe = (_source.isBridgePillar ? new RecipeBridgePillar() : (type.IsEmpty() ? new RecipeCard() : ((type == "Custom") ? new RecipeCustom() : new Recipe())));
        recipe.id = _source.id;
        recipe._source = _source;
        recipe.idMat = idMat;
        if (ing != null)
        {
            recipe.BuildIngredientList(ing);
            if (ing.trait is TraitTile)
            {
                recipe.VirtualBlock = true;
            }
        }
        return recipe;
    }
References _source, BuildIngredientList(), RecipeSource.id, idMat, and RecipeSource.type.
Referenced by BuildMenu._Search(), RecipeManager.Create(), Trait.GetBuildModeRecipe(), TraitTile.GetBuildModeRecipe(), GetOrCreate(), Trait.GetRecipe(), TraitTile.GetRecipe(), BuildMenu.RefreshCategory(), LayerCraft.RefreshCategory(), LayerCraftFloat.RefreshDisassemble(), and WidgetCodex.Search().
Create() [2/2]
static Recipe Recipe.Create (Thing t) inline static
Definition at line 344 of file Recipe.cs.
    {
        RecipeSource recipeSource = RecipeManager.dict.TryGetValue(t.id);
        if (recipeSource == null)
        {
            return null;
        }
        RecipeCard recipeCard = new RecipeCard
        {
            id = recipeSource.id,
            _source = recipeSource,
            IngAsProduct = true,
            idSkin = t.idSkin
        };
        recipeCard.BuildIngredientList(t);
        if (t.uid == 0 || recipeCard.ingredients[0].uid == 0 || recipeCard.ingredients[0].thing == null)
        {
            Debug.LogError("expection: invalid ingredient " + t);
        }
        return recipeCard;
    }
References _source, RecipeCard.BuildIngredientList(), Debug, RecipeManager.dict, Card.id, RecipeSource.id, idSkin, IngAsProduct, ingredients, and Card.uid.
DropIngredients()
static void Recipe.DropIngredients (string id, string idMatMain, int num = 1) inline static
Definition at line 366 of file Recipe.cs.
    {
        RecipeManager.BuildList();
        Recipe orCreate = GetOrCreate(EClass.sources.cards.map[id].RecipeID);
        orCreate.BuildIngredientList();
        Msg.Say("dropReward");
        foreach (Ingredient ingredient in orCreate.ingredients)
        {
            Thing thing = ThingGen.Create(ingredient.id).SetNum(ingredient.req);
            if (ingredient == orCreate.ingredients[0])
            {
                thing.ChangeMaterial(idMatMain);
                thing.SetNum(num);
            }
            EClass.player.DropReward(thing, silent: true);
        }
    }
References BuildIngredientList(), RecipeManager.BuildList(), SourceManager.cards, Card.ChangeMaterial(), ThingGen.Create(), Player.DropReward(), GetOrCreate(), Recipe.Ingredient.id, SourceCard.map, EClass.player, Recipe.Ingredient.req, Msg.Say(), Card.SetNum(), and EClass.sources.
Referenced by DramaOutcome.QuestShippingChest_Drop1().
Duplicate()
virtual Recipe Recipe.Duplicate () inline virtual
Reimplemented in RecipeBridgePillar, and RecipeCard.
Definition at line 895 of file Recipe.cs.
    {
        return IO.DeepCopy(this);
    }
GetBoxType()
BaseTileSelector.BoxType Recipe.GetBoxType () inline
Definition at line 466 of file Recipe.cs.
    {
        if (tileType.BoxType != BaseTileSelector.BoxType.Fence)
        {
            return BaseTileSelector.BoxType.Box;
        }
        return BaseTileSelector.BoxType.Fence;
    }
References TileType.BoxType, and tileType.
GetColorMaterial()
virtual SourceMaterial.Row Recipe.GetColorMaterial () inline virtual
Definition at line 499 of file Recipe.cs.
    {
        if (idMat != -1)
        {
            return EClass.sources.materials.rows[idMat];
        }
        if (UseStock)
        {
            ingredients[0].RefreshThing();
            Thing thing = ingredients[0].thing;
            if (thing != null)
            {
                if (!thing.isDyed)
                {
                    return thing.material;
                }
                return thing.DyeMat;
            }
            return EClass.sources.materials.rows[3];
        }
        int num = ((ingredients.Count > 0) ? ingredients[source.colorIng].mat : 3);
        if (num == -1)
        {
            num = 3;
        }
        return EClass.sources.materials.rows[num];
    }
References RecipeSource.colorIng, Card.DyeMat, idMat, ingredients, Card.isDyed, Card.material, SourceManager.materials, source, EClass.sources, and UseStock.
Referenced by RecipeCard.Build(), RecipeCard.Craft(), HasSameTile(), DropdownGrid.OnChangeIngredient(), RecipeCard.OnChangeIngredient(), TaskBuild.OnProgressComplete(), TaskCraft.OnProgressComplete(), UIRecipeInfo.RefreshImages(), AI_UseCrafter.Run(), ButtonGrid.SetRecipeVariation(), and UICardInfo.UpdateRecipe().
GetDefaultColor()
int Recipe.GetDefaultColor () inline
Definition at line 475 of file Recipe.cs.
    {
        if (UseStock)
        {
            Thing thing = ingredients[0].thing;
            return renderRow.GetColorInt(thing.isDyed ? thing.DyeMat : thing.material);
        }
        return renderRow.GetColorInt(DefaultMaterial);
    }
References DefaultMaterial, Card.DyeMat, RenderRow.GetColorInt(), ingredients, Card.isDyed, Card.material, renderRow, and UseStock.
Referenced by GridItemRecipe.SetButton(), and ButtonGrid.SetRecipe().
GetDetail()
virtual string Recipe.GetDetail () inline virtual
Reimplemented in RecipeCard.
Definition at line 800 of file Recipe.cs.
    {
        return renderRow.GetText("detail").IsEmpty(source.GetDetail());
    }
References RecipeSource.GetDetail(), SourceData< T, T2 >.BaseRow.GetText(), renderRow, and source.
Referenced by UIRecipeInfo.Refresh(), GridItemRecipe.SetButton(), and ButtonGrid.SetCraftRecipe().
GetIdThing()
virtual string Recipe.GetIdThing () inline virtual
Reimplemented in RecipeCard.
Definition at line 440 of file Recipe.cs.
    {
        if (source.row is SourceBlock.Row)
        {
            return (source.row as SourceBlock.Row).idThing;
        }
        if (source.row is SourceFloor.Row)
        {
            if (!IsBridge)
            {
                return "floor";
            }
            return "platform";
        }
        if (source.row is SourceObj.Row)
        {
            return "obj";
        }
        return null;
    }
References IsBridge, RecipeSource.row, and source.
Referenced by UIRecipeInfo.Refresh().
GetMainMaterial()
virtual SourceMaterial.Row Recipe.GetMainMaterial () inline virtual
Definition at line 485 of file Recipe.cs.
    {
        int num = -1;
        if (ingredients.Count > 0)
        {
            num = ((ingredients[0].thing == null) ? ingredients[0].mat : ingredients[0].thing.material.id);
        }
        if (num == -1)
        {
            num = 3;
        }
        return EClass.sources.materials.rows[num];
    }
References ingredients, SourceManager.materials, and EClass.sources.
Referenced by RecipeCard.Build(), Craft(), RecipeCard.Craft(), RecipeCard.OnChangeIngredient(), and TaskCraft.OnProgress().
GetMaxCount()
int Recipe.GetMaxCount () inline
Definition at line 931 of file Recipe.cs.
    {
        int num = 999;
        for (int i = 0; i < ingredients.Count; i++)
        {
            Ingredient ingredient = ingredients[i];
            Thing thing = ingredient.thing;
            int num2 = 0;
            if (!ingredient.optional || thing != null)
            {
                if (thing != null && !thing.isDestroyed)
                {
                    num2 = thing.Num / ingredient.req;
                }
                if (num2 < num)
                {
                    num = num2;
                }
            }
        }
        return num;
    }
References ingredients, Card.isDestroyed, Recipe.Ingredient.optional, Recipe.Ingredient.req, and Recipe.Ingredient.thing.
Referenced by LayerCraft.RefreshInputNum().
GetName()
string Recipe.GetName () inline
Definition at line 778 of file Recipe.cs.
    {
        if (UseStock && ingredients[0].thing == null)
        {
            return "";
        }
        string text = (UseStock ? ingredients[0].thing.Name : source.Name);
        if (text == "")
        {
            text = ("card_" + source.id).lang();
        }
        if (text == "*r")
        {
            text = source.row.GetText("aka");
        }
        if (text == "*r")
        {
            text = "(" + source.row.GetField<string>("id") + ")";
        }
        return text.ToTitleCase();
    }
References SourceData< T, T2 >.BaseRow.GetText(), RecipeSource.id, ingredients, RecipeSource.Name, RecipeSource.row, source, and UseStock.
Referenced by UIRecipeInfo.Refresh(), and ButtonGrid.SetCraftRecipe().
GetOrCreate()
static Recipe Recipe.GetOrCreate (string id) inline static
Definition at line 311 of file Recipe.cs.
    {
        Recipe recipe = recipeCache.TryGetValue(id);
        if (recipe == null)
        {
            RecipeSource recipeSource = RecipeManager.dict.TryGetValue(id);
            if (recipeSource != null)
            {
                recipe = Create(recipeSource);
                recipeCache.Add(id, recipe);
            }
        }
        return recipe;
    }
References Create(), RecipeManager.dict, and recipeCache.
Referenced by PartialMap.Apply(), and DropIngredients().
GetQualityBonus()
int Recipe.GetQualityBonus () inline
Definition at line 398 of file Recipe.cs.
    {
        if (IsStaticLV())
        {
            return 0;
        }
        Element reqSkill = source.GetReqSkill();
        int num = reqSkill.Value - EClass.pc.Evalue(reqSkill.id);
        int num2 = 0;
        if (num > 0)
        {
            if (num < 5)
            {
                return 0;
            }
            return -(num - 4) * 10;
        }
        num2 += EClass.curve(-num, 10, 20, 80) / 10 * 10 + 10;
        if (RecipeLv > 0)
        {
            num2 += (int)Mathf.Sqrt(RecipeLv - 1) * 10;
        }
        return num2;
    }
References EClass.curve(), Card.Evalue(), RecipeSource.GetReqSkill(), Element.id, IsStaticLV(), EClass.pc, RecipeLv, and source.
Referenced by RecipeCard.Craft(), RecipeCard.MakeDish(), and RecipeCard.MixIngredients().
GetQuestTrack()
QuestTrackCraft Recipe.GetQuestTrack () inline
Definition at line 1004 of file Recipe.cs.
    {
        QuestTrackCraft result = null;
        foreach (Quest item in EClass.game.quests.list)
        {
            if (item is QuestTrackCraft)
            {
                result = item as QuestTrackCraft;
                break;
            }
        }
        return result;
    }
References EClass.game, item, QuestManager.list, and Game.quests.
Referenced by WidgetCodex.RefreshList(), and LayerCraft.RefreshTrackButton().
GetRefVal()
virtual int Recipe.GetRefVal () inline virtual
Definition at line 423 of file Recipe.cs.
    {
        if (source.row is SourceBlock.Row)
        {
            return (source.row as SourceBlock.Row).id;
        }
        if (source.row is SourceFloor.Row)
        {
            return (source.row as SourceFloor.Row).id;
        }
        if (source.row is SourceObj.Row)
        {
            return (source.row as SourceObj.Row).id;
        }
        return -1;
    }
References RecipeSource.row, and source.
Referenced by UIRecipeInfo.Refresh().
GetRenderer()
virtual IRenderer Recipe.GetRenderer () inline virtual
Reimplemented in RecipeCard.
Definition at line 830 of file Recipe.cs.
    {
        return tileRow.renderData;
    }
References RenderRow.renderData, and tileRow.
Referenced by UICardInfo.UpdateRecipe().
GetSortVal()
int Recipe.GetSortVal () inline
Definition at line 962 of file Recipe.cs.
    {
        Element reqSkill = source.GetReqSkill();
        return reqSkill.source.id * 10000 - reqSkill.Value;
    }
References RecipeSource.GetReqSkill(), source, and Element.Value.
Referenced by LayerCraft.RefreshCategory().
HasFirstTimeBonus()
bool Recipe.HasFirstTimeBonus () inline
Definition at line 968 of file Recipe.cs.
    {
        if (IsStaticLV())
        {
            return false;
        }
        if (EClass.player.recipes.craftedRecipes.Contains(id))
        {
            return false;
        }
        return true;
    }
References RecipeManager.craftedRecipes, IsStaticLV(), EClass.player, and Player.recipes.
Referenced by LayerCraft.RefreshCategory(), and TryGetFirstTimeBonus().
HasSameTile()
bool Recipe.HasSameTile (Point point, int dir, int altitude, int bridgeHeight) inline
Definition at line 578 of file Recipe.cs.
    {
        if (IsObj)
        {
            if (point.growth != null && point.sourceObj == tileRow && point.cell.matObj == GetColorMaterial())
            {
                return true;
            }
            if (dir == point.cell.objDir && point.cell.matObj == GetColorMaterial() && point.sourceObj == tileRow)
            {
                return true;
            }
        }
        else if (IsBridge)
        {
            if (dir == point.cell.floorDir && point.matBridge == GetColorMaterial() && point.sourceBridge == tileRow && Mathf.Clamp(bridgeHeight + altitude, 0, 255) == point.cell.bridgeHeight)
            {
                return true;
            }
        }
        else if (IsFloorOrBridge)
        {
            if (dir == point.cell.floorDir && point.matFloor == GetColorMaterial() && point.sourceFloor == tileRow)
            {
                return true;
            }
        }
        else if (IsWallOrFence)
        {
            if (point.matBlock == GetColorMaterial() && point.sourceBlock == tileRow && dir == point.cell.blockDir)
            {
                return true;
            }
        }
        else if (IsBlock && point.matBlock == GetColorMaterial() && (point.sourceBlock == tileRow || (tileRow != null && tileRow.tileType == point.sourceBlock.tileType && tileRow.tileType == TileType.Slope)))
        {
            if (point.sourceBlock.tileType.AltitudeAsDir && dir != point.cell.objDir)
            {
                return false;
            }
            return true;
        }
        return false;
    }
References Cell.blockDir, Cell.bridgeHeight, Point.cell, Cell.floorDir, GetColorMaterial(), Point.growth, IsBlock, IsBridge, IsFloorOrBridge, IsObj, IsWallOrFence, Point.matBlock, Point.matBridge, Point.matFloor, Cell.matObj, Cell.objDir, TileType.Slope, Point.sourceBlock, Point.sourceBridge, Point.sourceFloor, Point.sourceObj, tileRow, and RenderRow.tileType.
Referenced by TaskBuild.GetHitResult().
IsCraftable()
bool Recipe.IsCraftable () inline
Definition at line 905 of file Recipe.cs.
    {
        foreach (Ingredient ingredient in ingredients)
        {
            if (ingredient.optional)
            {
                continue;
            }
            ThingStack thingStack = EClass._map.Stocked.ListThingStack(ingredient, StockSearchMode.AroundPC);
            bool flag = false;
            foreach (Thing item in thingStack.list)
            {
                if (item.Num >= ingredient.req)
                {
                    flag = true;
                    break;
                }
            }
            if (!flag)
            {
                return false;
            }
        }
        return true;
    }
References EClass._map, ingredients, item, Props.ListThingStack(), Recipe.Ingredient.optional, Recipe.Ingredient.req, and Map.Stocked.
IsStaticLV()
bool Recipe.IsStaticLV () inline
Definition at line 384 of file Recipe.cs.
    {
        switch (source.idFactory)
        {
        case "factory_floor":
        case "factory_block":
        case "factory_wall":
        case "factory_platform":
            return true;
        default:
            return renderRow.Category.IsChildOf("block");
        }
    }
References RenderRow.Category, RecipeSource.idFactory, renderRow, and source.
Referenced by GetQualityBonus(), HasFirstTimeBonus(), and TryGetFirstTimeBonus().
OnChangeAltitude()
virtual void Recipe.OnChangeAltitude (int a) inline virtual
Reimplemented in RecipeCard.
Definition at line 839 of file Recipe.cs.
    {
    }
Referenced by AM_Build.SetAltitude().
OnChangeIngredient()
virtual void Recipe.OnChangeIngredient () inline virtual
Reimplemented in RecipeCard.
Definition at line 550 of file Recipe.cs.
    {
    }
Referenced by DropdownGrid.OnChangeIngredient(), BuildMenu.RefreshCategory(), LayerCraftFloat.RefreshCraft(), LayerCraft.RefreshRecipe(), and ButtonGrid.SetIngredient().
OnRenderMarker()
virtual void Recipe.OnRenderMarker (Point point, bool active, HitResult result, bool main, int dir, int bridgeHeight) inline virtual
Reimplemented in RecipeCard.
Definition at line 706 of file Recipe.cs.
    {
        if (dir != -1)
        {
            _dir = dir;
        }
        RenderParam renderParam = tileRow.GetRenderParam(DefaultMaterial, _dir, point, bridgeHeight);
        renderParam.matColor = (active ? EClass.Colors.blockColors.Active : EClass.Colors.blockColors.Inactive);
        point.ApplyAnime(renderParam);
        if (tileType.IsWater)
        {
            if (EClass.screen.guide.isActive)
            {
                EClass.screen.guide.passGuideFloor.Add(point, (float)result, 0.3f);
            }
            return;
        }
        if (tileType.IsWallOrFence && point.HasNonWallBlock)
        {
            Vector3 v = point.Position();
            if (EClass.screen.guide.isActive)
            {
                EClass.screen.guide.passGuideBlock.Add(ref v, 5f);
            }
        }
        if (renderRow.renderData.pass == EClass.screen.tileMap.passBlock || renderRow.renderData.pass == EClass.screen.tileMap.passBlockEx || renderRow.renderData.pass == EClass.screen.tileMap.passLiquid)
        {
            if (bridgeHeight > 0 && !point.cell.skipRender && EClass.screen.guide.isActive)
            {
                EClass.screen.guide.passGuideFloor.Add(point, (float)result, 0.3f);
            }
            if (!tileType.IsWallOrFence && (point.HasChara || (point.HasObj && point.cell.blocked)))
            {
                Vector3 v2 = point.Position();
                if (EClass.screen.guide.isActive)
                {
                    EClass.screen.guide.passGuideBlock.Add(ref v2, 5f);
                }
                return;
            }
            if (EClass.scene.actionMode.IsRoofEditMode())
            {
                EClass.screen.tileMap.SetRoofHeight(renderParam, point.cell, point.x, point.z, 0, bridgeHeight, tileType.IsWallOrFence ? _dir : (-1), ignoreAltitudeY: true);
            }
            renderParam.y = renderParam.y - EClass.screen.tileMap.rendererBlockMarker.offset.y + renderRow.renderData.offset.y;
            renderParam.z += EClass.setting.render.tileMarkerZ;
            int num = ((tileType.blockRenderMode != BlockRenderMode.Pillar) ? 1 : (_dir + 1 + ((_dir >= 7) ? _dir : 0)));
            if (num == 1)
            {
                EClass.screen.tileMap.rendererBlockMarker.Draw(renderParam);
            }
            else
            {
                EClass.screen.tileMap.rendererBlockMarker.DrawRepeat(renderParam, num, tileType.RepeatSize);
            }
        }
        else if (renderRow.renderData.pass == EClass.screen.tileMap.passFloor || renderRow.renderData.pass == EClass.screen.tileMap.passFloorEx || renderRow.renderData.pass == EClass.screen.tileMap.passFloorWater)
        {
            if (point.HasObj)
            {
                _ = ref point.Position();
            }
            renderParam.z += ((point.cell.liquidLv > 0) ? (-0.01f) : EClass.setting.render.tileMarkerZFloor);
            EClass.screen.tileMap.rendererFloorMarker.Draw(renderParam);
        }
        else
        {
            renderParam.z += EClass.setting.render.tileMarkerZ;
            renderRow.renderData.Draw(renderParam);
        }
    }
References _dir, Scene.actionMode, MeshPass.Add(), Point.ApplyAnime(), ColorProfile.blockColors, Algorithms.WeightCell.blocked, Point.cell, EClass.Colors, DefaultMaterial, RenderData.Draw(), RenderData.DrawRepeat(), RenderRow.GetRenderParam(), BaseGameScreen.guide, Point.HasChara, Point.HasNonWallBlock, Point.HasObj, ColorProfile.BlockColors.Inactive, ScreenGuide.isActive, ActionMode.IsRoofEditMode(), TileType.IsWallOrFence, TileType.IsWater, RenderData.offset, RenderData.pass, BaseTileMap.passBlock, BaseTileMap.passBlockEx, BaseTileMap.passFloor, BaseTileMap.passFloorEx, BaseTileMap.passFloorWater, ScreenGuide.passGuideBlock, ScreenGuide.passGuideFloor, BaseTileMap.passLiquid, Point.Position(), GameSetting.render, RenderRow.renderData, BaseTileMap.rendererBlockMarker, BaseTileMap.rendererFloorMarker, renderRow, TileType.RepeatSize, EClass.scene, EClass.screen, BaseTileMap.SetRoofHeight(), EClass.setting, Cell.skipRender, BaseGameScreen.tileMap, GameSetting.RenderSetting.tileMarkerZ, GameSetting.RenderSetting.tileMarkerZFloor, tileRow, tileType, Point.x, and Point.z.
Referenced by PartialMap.Apply(), TaskBuild.DrawMarker(), and AM_Build.OnRenderTile().
OnSelected()
virtual void Recipe.OnSelected () inline virtual
Reimplemented in RecipeCard.
Definition at line 835 of file Recipe.cs.
    {
    }
Referenced by UIRecipeInfo.Refresh().
Rotate()
virtual void Recipe.Rotate () inline virtual
Reimplemented in RecipeCard.
Definition at line 843 of file Recipe.cs.
    {
        if (EInput.isShiftDown || Input.GetMouseButton(1))
        {
            _dir--;
        }
        else
        {
            _dir++;
        }
        if (tileType.AltitudeAsDir)
        {
            if (_dir >= tileType.MaxAltitude)
            {
                _dir = 0;
            }
            if (_dir < 0)
            {
                _dir = tileType.MaxAltitude - 1;
            }
        }
        else
        {
            int num = tileRow._tiles.Length;
            if (tileRow.tileType == TileType.Door)
            {
                num = 2;
            }
            if (_dir < 0)
            {
                _dir = num - 1;
            }
            if (_dir >= num)
            {
                _dir = 0;
            }
        }
        if ((bool)BuildMenu.Instance)
        {
            BuildMenu.Instance.info1.OnRotate();
        }
    }
References _dir, RenderRow._tiles, TileType.AltitudeAsDir, TileType.Door, BuildMenu.info1, BuildMenu.Instance, EInput.isShiftDown, TileType.MaxAltitude, UIRecipeInfo.OnRotate(), tileRow, tileType, and RenderRow.tileType.
Referenced by AM_Adv._OnUpdateInput(), and AM_Build.RotateUnderMouse().
SaveLastIngredients()
void Recipe.SaveLastIngredients () inline
Definition at line 993 of file Recipe.cs.
    {
        List<int> list = new List<int>();
        foreach (Ingredient ingredient in ingredients)
        {
            int item = ((ingredient.thing != null) ? ingredient.thing.uid : 0);
            list.Add(item);
        }
        EClass.player.recipes.lastIngredients[id] = list;
    }
References id, ingredients, item, RecipeManager.lastIngredients, EClass.player, Player.recipes, Recipe.Ingredient.thing, and Card.uid.
Referenced by DropdownGrid.Activate(), LayerCraft.OnClickCraft(), LayerCraft.RefreshCategory(), and ButtonGrid.SetIngredient().
SetDir()
virtual void Recipe.SetDir (int d) inline virtual
Reimplemented in RecipeCard.
Definition at line 886 of file Recipe.cs.
    {
        _dir = d;
        if ((bool)BuildMenu.Instance)
        {
            BuildMenu.Instance.info1.OnRotate();
        }
    }
References _dir, BuildMenu.info1, BuildMenu.Instance, and UIRecipeInfo.OnRotate().
Referenced by TaskBuild.GetHitResult(), and UIRecipeInfo.Refresh().
SetImage()
virtual void Recipe.SetImage (Image icon) inline virtual
Definition at line 900 of file Recipe.cs.
    {
        renderRow.SetImage(icon, null, renderRow.GetColorInt((ingredients != null && ingredients.Count > 0 && ingredients[0].thing != null) ? ingredients[0].thing.material : DefaultMaterial), setNativeSize: true, 0, idSkin);
    }
References DefaultMaterial, RenderRow.GetColorInt(), idSkin, ingredients, renderRow, and RenderRow.SetImage().
Referenced by ButtonGrid.SetCraftRecipe().
SetTextDifficulty()
void Recipe.SetTextDifficulty (UIText text) inline
Definition at line 954 of file Recipe.cs.
    {
        Element reqSkill = source.GetReqSkill();
        _ = EClass.pc.elements.GetOrCreateElement(reqSkill).Value;
        string text2 = reqSkill.Name + " " + reqSkill.Value;
        text.SetText(text2);
    }
References Card.elements, ElementContainer.GetOrCreateElement(), RecipeSource.GetReqSkill(), EClass.pc, UIText.SetText(), source, and Element.Value.
Referenced by UIRecipeInfo.RefreshQuality().
ShouldShowHighlight()
virtual bool Recipe.ShouldShowHighlight (HitResult r) inline virtual
Definition at line 461 of file Recipe.cs.
    {
        return r != HitResult.Valid;
    }
ToggleTrack()
void Recipe.ToggleTrack (QuestTrackCraft quest) inline
Definition at line 1018 of file Recipe.cs.
    {
        if (quest != null && quest.idRecipe == id)
        {
            EClass.game.quests.Remove(quest);
        }
        else
        {
            if (quest != null)
            {
                EClass.game.quests.Remove(quest);
            }
            QuestTrackCraft questTrackCraft = Quest.Create("track_craft") as QuestTrackCraft;
            questTrackCraft.SetRecipe(this);
            EClass.game.quests.Start(questTrackCraft);
        }
        if (!WidgetQuestTracker.Instance)
        {
            EClass.player.questTracker = true;
            EClass.ui.widgets.ActivateWidget("QuestTracker");
            WidgetHotbar.RefreshButtons();
        }
        WidgetQuestTracker.Instance.Refresh();
    }
References Quest.Create(), EClass.game, QuestTrackCraft.idRecipe, WidgetQuestTracker.Instance, Game.quests, WidgetQuestTracker.Refresh(), WidgetHotbar.RefreshButtons(), QuestManager.Remove(), QuestTrackCraft.SetRecipe(), QuestManager.Start(), and EClass.ui.
Referenced by WidgetCodex.RefreshList(), and LayerCraft.RefreshTrackButton().
TryGetFirstTimeBonus()
void Recipe.TryGetFirstTimeBonus () inline
Definition at line 981 of file Recipe.cs.
    {
        if (HasFirstTimeBonus())
        {
            EClass.player.recipes.craftedRecipes.Add(id);
            Element reqSkill = source.GetReqSkill();
            int num = 1 + ((!IsStaticLV()) ? (reqSkill.Value / 20) : 0);
            Msg.Say("firstTimeCraft", Name);
            EClass.pc.Pick(ThingGen.Create("ticket_fortune").SetNum(num));
        }
    }
References RecipeManager.craftedRecipes, ThingGen.Create(), RecipeSource.GetReqSkill(), HasFirstTimeBonus(), IsStaticLV(), Name, EClass.pc, Chara.Pick(), EClass.player, Player.recipes, Msg.Say(), Card.SetNum(), source, and Element.Value.
Referenced by AI_UseCrafter.Run().
WriteNote()
virtual void Recipe.WriteNote (UINote n) inline virtual
Reimplemented in RecipeCard.
Definition at line 805 of file Recipe.cs.
    {
        n.Clear();
        n.Build();
    }
References UINote.Build(), and UINote.Clear().
Referenced by UIRecipeInfo.Refresh().
WriteReqFactory()
void Recipe.WriteReqFactory (UINote n, bool hasFactory = true) inline
Definition at line 811 of file Recipe.cs.
    {
        if (source.NeedFactory)
        {
            n.AddHeaderTopic("reqFactory".lang(source.NameFactory.TagColor(hasFactory ? FontColor.Default : FontColor.Bad)));
            n.Space(8);
        }
    }
References UINote.AddHeaderTopic(), RecipeSource.NameFactory, RecipeSource.NeedFactory, source, and UINote.Space().
Referenced by ButtonGrid.WriteReqMat().
WriteReqSkill()
void Recipe.WriteReqSkill (UINote n) inline
Definition at line 820 of file Recipe.cs.
    {
        n.AddHeaderTopic("reqSkill");
        Element reqSkill = source.GetReqSkill();
        int value = EClass.pc.elements.GetOrCreateElement(reqSkill).Value;
        Color textColor = EClass.Colors.Skin.GetTextColor((value >= reqSkill.Value) ? FontColor.Good : FontColor.Warning);
        n.AddText(null, reqSkill.Name + " " + reqSkill.Value + " (" + value + ")", textColor).text1.SetSize(-1);
        n.Space(8);
    }
References UINote.AddHeaderTopic(), UINote.AddText(), Color, EClass.Colors, Card.elements, ElementContainer.GetOrCreateElement(), RecipeSource.GetReqSkill(), SkinColorProfile.GetTextColor(), Element.Name, EClass.pc, UIText.SetSize(), ColorProfile.Skin, source, UINote.Space(), UIItem.text1, and Element.Value.
Referenced by ButtonGrid.WriteReqMat().
Member Data Documentation
_dir
int Recipe._dir
Definition at line 193 of file Recipe.cs.
Referenced by RecipeCard.CreateMold(), TaskBuild.GetHitResult(), AM_Build.OnBeforeProcessTiles(), AM_Build.OnProcessTiles(), TaskBuild.OnProgressComplete(), OnRenderMarker(), AM_Build.OnRenderTile(), HotItemHeld.OnRenderTile(), UIRecipeInfo.OnRotate(), UIRecipeInfo.Refresh(), UIRecipeInfo.RefreshImages(), Rotate(), RecipeCard.Rotate(), SetDir(), and HotItemHeld.TrySetAct().
_source
RecipeSource Recipe._source
Definition at line 203 of file Recipe.cs.
Referenced by Create().
id
string Recipe.id
Definition at line 179 of file Recipe.cs.
Referenced by DropdownGrid.BuildIngredients(), HitSummary.Execute(), RecipeCard.GetIdThing(), Player.Flags.OnBuild(), LayerCraft.OnClickCraft(), LayerCraft.OnCompleteCraft(), LayerCraft.OnKill(), UIRecipeInfo.Refresh(), BuildMenu.RefreshCategory(), LayerCraft.RefreshCategory(), LayerCraftFloat.RefreshCraft(), LayerCraft.RefreshTrackButton(), AI_UseCrafter.Run(), RecipeUpdater.RunRecipe(), SaveLastIngredients(), BuildMenu.Select(), ButtonGrid.SetCraftRecipe(), and QuestTrackCraft.SetRecipe().
idMat
int Recipe.idMat = -1
Definition at line 197 of file Recipe.cs.
Referenced by Build(), Create(), and GetColorMaterial().
idSkin
int Recipe.idSkin
Definition at line 199 of file Recipe.cs.
Referenced by RecipeCard.Build(), RecipeCard.Craft(), Create(), RecipeCard.CreateMold(), DropdownGrid.OnChangeIngredient(), LayerCraft.RefreshCategory(), UIRecipeInfo.RefreshImages(), BuildMenu.Select(), SetImage(), ButtonGrid.SetRecipe(), and ButtonGrid.SetRecipeVariation().
IngAsProduct
bool Recipe.IngAsProduct
Definition at line 188 of file Recipe.cs.
Referenced by RecipeCard.Build(), Create(), UIRecipeInfo.Refresh(), and BuildMenu.RefreshCategory().
ingredients
List<Ingredient> Recipe.ingredients = new List<Ingredient>()
Definition at line 182 of file Recipe.cs.
Referenced by TaskBuild._CanPerformTask(), Build(), RecipeCard.Build(), BuildIngredientList(), RecipeCard.BuildIngredientList(), DropdownGrid.BuildIngredients(), HitSummary.CanExecute(), Create(), RecipeCard.CreateMold(), HitSummary.Execute(), GetColorMaterial(), GetDefaultColor(), GetMainMaterial(), GetMaxCount(), GetName(), LayerCraft.GetReqIngredient(), LayerCraft.GetTargets(), IsCraftable(), TaskCraft.IsIngredientsValid(), RecipeCard.MakeDish(), RecipeCard.MixIngredients(), TaskBuild.OnAdd(), LayerCraft.OnClickCraft(), AM_Build.OnFinishProcessTiles(), UIRecipeInfo.Refresh(), BuildMenu.RefreshCategory(), LayerCraft.RefreshCategory(), UIRecipeInfo.RefreshImages(), DropdownRecipe.RefreshLabel(), UIRecipeInfo.RefreshList(), LayerCraft.RefreshProduct(), LayerCraft.RefreshRecipe(), TaskCraft.ResetReq(), AI_HaulResource.Run(), RecipeUpdater.RunRecipe(), SaveLastIngredients(), ButtonGrid.SetCraftRecipe(), SetImage(), ButtonGrid.SetIngredient(), ButtonGrid.SetRecipe(), UIRecipeInfo.SetRecipe(), ButtonGrid.SetRecipeVariation(), LayerCraftFloat.ShowContextMenu(), and ButtonGrid.WriteReqMat().
recipeCache
Dictionary<string, Recipe> Recipe.recipeCache = new Dictionary<string, Recipe>() static
Definition at line 176 of file Recipe.cs.
Referenced by GetOrCreate().
state
State Recipe.state
Definition at line 201 of file Recipe.cs.
sync
int Recipe.sync
Definition at line 195 of file Recipe.cs.
UseStock
bool Recipe.UseStock
Definition at line 185 of file Recipe.cs.
Referenced by BuildIngredientList(), HitSummary.CanExecute(), RecipeCard.CreateMold(), HitSummary.Execute(), GetColorMaterial(), GetDefaultColor(), GetName(), RecipeCard.OnChangeIngredient(), AM_Build.OnFinishProcessTiles(), UIRecipeInfo.Refresh(), BuildMenu.RefreshCategory(), UIRecipeInfo.RefreshImages(), UIRecipeInfo.RefreshList(), ButtonGrid.SetRecipe(), HitSummary.SetRecipe(), UIRecipeInfo.SetRecipe(), and ButtonGrid.SetRecipeVariation().
VirtualBlock
bool Recipe.VirtualBlock
Definition at line 191 of file Recipe.cs.
Referenced by HitSummary.Execute(), UIRecipeInfo.Refresh(), UIRecipeInfo.RefreshImages(), ButtonGrid.SetRecipe(), and ButtonGrid.SetRecipeVariation().
Property Documentation
CanRotate
virtual bool Recipe.CanRotate get
Definition at line 299 of file Recipe.cs.
    {
        get
        {
            if (tileType.CanRotate(buildMode: true))
            {
                return tileRow._tiles.Length > 1;
            }
            return false;
        }
    }
Referenced by ActionMode.GetHintText(), and AM_Build.RotateUnderMouse().
CostMoney
virtual int Recipe.CostMoney get
Definition at line 297 of file Recipe.cs.
Referenced by UIRecipeInfo.Refresh(), and UIRecipeInfo.RefreshList().
DefaultMaterial
SourceMaterial.Row Recipe.DefaultMaterial get
Definition at line 207 of file Recipe.cs.
Referenced by DropdownGrid.BuildIngredients(), GetDefaultColor(), OnRenderMarker(), and SetImage().
H
virtual int Recipe.H get
Definition at line 269 of file Recipe.cs.
    {
        get
        {
            if (_dir % 2 != 0)
            {
                return renderRow.W;
            }
            return renderRow.H;
        }
    }
Referenced by UIInspector.DrawHighlight(), TaskBuild.OnProgressComplete(), HotItemHeld.OnRenderTile(), and AI_HaulResource.Run().
IsBlock
virtual bool Recipe.IsBlock get
Definition at line 247 of file Recipe.cs.
Referenced by AM_Build.GetGuidePass(), TaskBuild.GetHitResult(), HasSameTile(), AM_Build.HitTest(), and TaskBuild.OnProgressComplete().
IsBridge
bool Recipe.IsBridge get
Definition at line 251 of file Recipe.cs.
Referenced by AM_Build.FixBridge(), GetIdThing(), HasSameTile(), AM_Build.HitTest(), AM_Build.ModAltitude(), AM_Build.OnFinishProcessTiles(), TaskBuild.OnProgressComplete(), and AM_Build.OnRenderTile().
IsFloor
bool Recipe.IsFloor get
Definition at line 243 of file Recipe.cs.
Referenced by AM_Build.HitTest(), and TaskBuild.OnProgressComplete().
IsFloorOrBridge
virtual bool Recipe.IsFloorOrBridge get
Definition at line 227 of file Recipe.cs.
Referenced by HasSameTile(), and AM_Build.OnRenderTile().
IsObj
bool Recipe.IsObj get
Definition at line 245 of file Recipe.cs.
Referenced by HasSameTile().
IsThing
virtual bool Recipe.IsThing get
Definition at line 253 of file Recipe.cs.
Referenced by TaskBuild.GetHitResult(), and AM_Build.IsFillMode().
IsWallOrFence
bool Recipe.IsWallOrFence get
Definition at line 249 of file Recipe.cs.
Referenced by TaskBuild.GetHitResult(), HasSameTile(), AM_Build.OnProcessTiles(), and TaskBuild.OnProgressComplete().
MaxAltitude
int Recipe.MaxAltitude get
Definition at line 229 of file Recipe.cs.
    {
        get
        {
            if (IsThing || IsBridge || tileType.blockRenderMode == BlockRenderMode.Pillar)
            {
                return tileType.MaxAltitude;
            }
            return 0;
        }
    }
Referenced by HotItemHeld.CanChangeHeightByWheel(), AM_Build.InputWheel(), and UIPlaceHelper.Refresh().
Mold
virtual Card Recipe.Mold get
Definition at line 255 of file Recipe.cs.
Referenced by TaskBuild._GetHitResult().
MultiSize
bool Recipe.MultiSize get
Definition at line 283 of file Recipe.cs.
    {
        get
        {
            if (W == 1)
            {
                return H != 1;
            }
            return true;
        }
    }
Referenced by UIInspector.DrawHighlight(), TaskBuild.GetHitResult(), and HotItemHeld.OnRenderTile().
Name
string Recipe.Name get
Definition at line 213 of file Recipe.cs.
Referenced by GridItemRecipe.SetButton(), UICardInfo.SetRecipe(), and TryGetFirstTimeBonus().
RecipeLv
int Recipe.RecipeLv get
Definition at line 241 of file Recipe.cs.
Referenced by GetQualityBonus().
renderRow
virtual RenderRow Recipe.renderRow get
Definition at line 211 of file Recipe.cs.
Referenced by GetDefaultColor(), GetDetail(), TaskBuild.GetHitResult(), IsStaticLV(), DropdownGrid.OnChangeIngredient(), TaskCraft.OnProgress(), OnRenderMarker(), UIRecipeInfo.Refresh(), BuildMenu.RefreshCategory(), UIRecipeInfo.RefreshImages(), GridItemRecipe.SetButton(), SetImage(), ButtonGrid.SetRecipe(), ButtonGrid.SetRecipeVariation(), and UICardInfo.UpdateRecipe().
RequireIngredients
virtual bool Recipe.RequireIngredients get
Definition at line 281 of file Recipe.cs.
Referenced by BuildIngredientList(), and HitSummary.Execute().
source
RecipeSource Recipe.source get
Definition at line 205 of file Recipe.cs.
Referenced by Build(), BuildIngredientList(), Craft(), GetColorMaterial(), TraitFactory.GetCostSp(), GetDetail(), TraitCrafter.GetDuration(), GetIdThing(), GetName(), GetQualityBonus(), GetRefVal(), GetSortVal(), IsStaticLV(), TaskCraft.OnProgress(), TaskCraft.OnProgressComplete(), UIRecipeInfo.Refresh(), UIRecipeInfo.RefreshBalance(), BuildMenu.RefreshCategory(), DropdownRecipe.RefreshLabel(), UIRecipeInfo.RefreshList(), AI_UseCrafter.Run(), BuildMenu.Select(), GridItemRecipe.SetButton(), ButtonGrid.SetIngredient(), HitSummary.SetRecipe(), UICardInfo.SetRecipe(), SetTextDifficulty(), TryGetFirstTimeBonus(), WriteReqFactory(), and WriteReqSkill().
tileRow
virtual TileRow Recipe.tileRow get
Definition at line 209 of file Recipe.cs.
Referenced by Build(), RecipeBridgePillar.Build(), Craft(), GetRenderer(), HasSameTile(), OnRenderMarker(), and Rotate().
tileSelector
BaseTileSelector Recipe.tileSelector get
Definition at line 295 of file Recipe.cs.
tileType
virtual TileType Recipe.tileType get
Definition at line 215 of file Recipe.cs.
    {
        get
        {
            if (!(source.type == "Bridge") || source.row.tileType is TileTypeBridge)
            {
                return renderRow.tileType;
            }
            return TileType.Bridge;
        }
    }
Referenced by TaskBuild._GetHitResult(), Build(), HitSummary.Execute(), AM_Build.FixBridge(), AM_Build.ForcedInstaComplete(), GetBoxType(), AM_Build.HitTest(), OnRenderMarker(), AM_Build.OnRenderTile(), UIRecipeInfo.Refresh(), Rotate(), AI_HaulResource.Run(), AM_Build.SetAltitude(), UICardInfo.SetRecipe(), AM_Build.TopHeight(), and HotItemHeld.TrySetAct().
W
virtual int Recipe.W get
Definition at line 257 of file Recipe.cs.
    {
        get
        {
            if (_dir % 2 != 0)
            {
                return renderRow.H;
            }
            return renderRow.W;
        }
    }
Referenced by UIInspector.DrawHighlight(), TaskBuild.OnProgressComplete(), HotItemHeld.OnRenderTile(), and AI_HaulResource.Run().
The documentation for this class was generated from the following file:
Elin/Recipe.cs