Elin Decompiled Documentation: SpriteReplacerAnimation Class Reference
SpriteReplacerAnimation Class Reference
Public Types
enum Type { Default , Boat }
Public Member Functions
void SetData (string id)
Public Attributes
Type type
string id
SpriteData data
SpriteRenderer sr
Static Public Attributes
static Dictionary< string, SpriteData > dict = new Dictionary<string, SpriteData>()
Private Member Functions
void Awake ()
void Refresh ()
Private Attributes
int index
Detailed Description
Definition at line 5 of file SpriteReplacerAnimation.cs.
Member Enumeration Documentation
Type
enum SpriteReplacerAnimation.Type
Enumerator
Default
Boat
Definition at line 7 of file SpriteReplacerAnimation.cs.
    {
        Default,
        Boat
    }
Member Function Documentation
Awake()
void SpriteReplacerAnimation.Awake () inline private
Definition at line 26 of file SpriteReplacerAnimation.cs.
    {
        if (!id.IsEmpty())
        {
            SetData(id);
        }
    }
References SetData().
Refresh()
void SpriteReplacerAnimation.Refresh () inline private
Definition at line 58 of file SpriteReplacerAnimation.cs.
    {
        index++;
        if (index >= data.frame)
        {
            index = 0;
        }
        sr.sprite = data.GetSprites()[index];
    }
References data, SpriteData.frame, SpriteData.GetSprites(), and index.
SetData()
void SpriteReplacerAnimation.SetData (string id) inline
Definition at line 34 of file SpriteReplacerAnimation.cs.
    {
        this.id = id;
        string text = id.IsEmpty(base.name + "_anime");
        string path = CorePath.packageCore + "Texture/Item/" + text;
        data = dict.TryGetValue(text);
        if (data == null)
        {
            data = new SpriteData
            {
                path = path
            };
            data.Init();
            dict.Add(text, data);
        }
        sr = GetComponent<SpriteRenderer>();
        sr.sprite = data.GetSprite();
        if (type == Type.Default)
        {
            CancelInvoke();
            InvokeRepeating("Refresh", 0f, data.time);
        }
    }
References data, dict, SpriteData.GetSprite(), id, SpriteData.Init(), sr, SpriteData.time, and type.
Referenced by Awake(), and CardActor.SetOwner().
Member Data Documentation
data
SpriteData SpriteReplacerAnimation.data
Definition at line 19 of file SpriteReplacerAnimation.cs.
Referenced by CardActor.OnRender(), Refresh(), and SetData().
dict
Dictionary<string, SpriteData> SpriteReplacerAnimation.dict = new Dictionary<string, SpriteData>() static
Definition at line 13 of file SpriteReplacerAnimation.cs.
Referenced by Core.Awake(), and SetData().
id
string SpriteReplacerAnimation.id
Definition at line 17 of file SpriteReplacerAnimation.cs.
Referenced by SetData().
index
int SpriteReplacerAnimation.index private
Definition at line 24 of file SpriteReplacerAnimation.cs.
Referenced by Refresh().
sr
SpriteRenderer SpriteReplacerAnimation.sr
Definition at line 22 of file SpriteReplacerAnimation.cs.
Referenced by SetData().
type
Type SpriteReplacerAnimation.type
Definition at line 15 of file SpriteReplacerAnimation.cs.
Referenced by SetData().
The documentation for this class was generated from the following file:
Elin/Plugins.basecore/SpriteReplacerAnimation.cs