Elin Decompiled Documentation: ZoneEventMusic Class Reference
ZoneEventMusic Class Reference
Public Member Functions
override void OnVisit ()
void Spawn (Chara c, Point p)
override ZoneInstance.Status OnReachTimeLimit ()
Public Member Functions inherited from ZoneEventQuest
void Spawn (int num=1)
void SpawnBoss (bool evolve=false)
void AggroEnemy (int chance=100)
sealed override void OnTickRound ()
virtual void _OnTickRound ()
virtual ZoneInstance.Status OnReachTimeLimit ()
Public Member Functions inherited from ZoneEvent
virtual string GetText ()
void Tick (float delta)
void Init ()
void OnSimulateHour ()
virtual void OnVisit ()
virtual void OnInit ()
virtual void OnFirstTick ()
virtual void OnTick ()
virtual void OnTickRound ()
virtual void OnKill ()
virtual void OnCharaDie (Chara c)
virtual void OnLeaveZone ()
void OnLoad (Zone _zone)
void Kill ()
Properties
QuestMusic questMusic [get]
override string TextWidgetDate [get]
override int TimeLimit [get]
Properties inherited from ZoneEventQuest
Quest quest [get]
virtual bool WarnBoss [get]
virtual bool CountEnemy [get]
virtual int TimeLimit [get]
Properties inherited from ZoneEvent
SourceQuest.Row source [get]
virtual string id [get]
virtual string TextWidgetDate [get]
virtual float roundInterval [get]
virtual Playlist playlist [get]
virtual bool debugSkip [get]
virtual string RefStr2 [get]
virtual string RefStr3 [get]
virtual int hoursToKill [get]
virtual bool HasReport [get]
string Name [get]
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Additional Inherited Members
Static Public Member Functions inherited from EClass
static int rnd (int a)
static int curve (int a, int start, int step, int rate=75)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Public Attributes inherited from ZoneEventQuest
int uidQuest
List< int > enemies = new List<int>()
Public Attributes inherited from ZoneEvent
float time
int rounds
int hoursElapsed
int minElapsed
Zone zone
bool firstTick = true
Static Public Attributes inherited from EClass
static Core core
Detailed Description
Definition at line 5 of file ZoneEventMusic.cs.
Member Function Documentation
OnReachTimeLimit()
override ZoneInstance.Status ZoneEventMusic.OnReachTimeLimit () inline virtual
Reimplemented from ZoneEventQuest.
Definition at line 102 of file ZoneEventMusic.cs.
    {
        Msg.Say("party_end", questMusic.score.ToString() ?? "");
        Msg.Say("party_end2", questMusic.sumMoney.ToString() ?? "");
        if (questMusic.score < questMusic.destScore)
        {
            return ZoneInstance.Status.Fail;
        }
        return ZoneInstance.Status.Success;
    }
References QuestMusic.destScore, questMusic, Msg.Say(), QuestMusic.score, and QuestMusic.sumMoney.
OnVisit()
override void ZoneEventMusic.OnVisit () inline virtual
Reimplemented from ZoneEvent.
Definition at line 13 of file ZoneEventMusic.cs.
    {
        if (EClass.game.isLoading || (EClass.debug.enable && Input.GetKey(KeyCode.LeftShift)))
        {
            return;
        }
        int difficulty = questMusic.difficulty;
        int maxLv = difficulty * 5 + 2;
        if (difficulty > 2)
        {
            maxLv += (difficulty - 2) * 10;
        }
        GenBounds genBounds = GenBounds.Create(EClass._zone);
        genBounds.marginPartial = 1;
        genBounds.FuncCheckEmpty = (Cell cell) => cell.sourceFloor.id == 76;
        int i;
        for (i = 0; i < 25; i++)
        {
            genBounds.TryAddMapPiece(MapPiece.Type.Concert, 0f, "", delegate(PartialMap p, GenBounds b)
            {
                int num = 1 + i * 3;
                if (num > maxLv)
                {
                    num = EClass.rnd(maxLv);
                }
                List<Point> list = b.ListEmptyPoint();
                for (int k = 0; k < EClass.rndHalf(list.Count); k++)
                {
                    if (list.Count == 0)
                    {
                        break;
                    }
                    Point point = list.RandomItem();
                    Chara c4 = CharaGen.CreateFromFilter("c_neutral", num, 5);
                    Spawn(c4, point);
                    list.Remove(point);
                }
            });
        }
        foreach (SourceChara.Row item in EClass.sources.charas.rows.Where((SourceChara.Row c) => c.tag.Contains("party")))
        {
            if (item.LV >= maxLv * 2)
            {
                continue;
            }
            Point randomPoint = EClass._map.bounds.GetRandomPoint();
            if (randomPoint.HasChara || randomPoint.HasBlock)
            {
                continue;
            }
            bool flag = true;
            foreach (Chara member in EClass.pc.party.members)
            {
                if (member.id == item.id)
                {
                    flag = false;
                }
            }
            if (flag)
            {
                Chara c2 = CharaGen.Create(item.id);
                Spawn(c2, randomPoint);
            }
        }
        for (int j = 0; j < 50; j++)
        {
            Point randomPoint2 = EClass._map.bounds.GetRandomPoint();
            if (!randomPoint2.HasChara && !randomPoint2.HasBlock)
            {
                Chara c3 = CharaGen.CreateFromFilter("c_neutral", maxLv / 2);
                Spawn(c3, randomPoint2);
            }
        }
        foreach (Thing thing in EClass._map.things)
        {
            thing.isNPCProperty = true;
        }
    }
References EClass._map, EClass._zone, Map.bounds, SourceManager.charas, CharaGen.Create(), GenBounds.Create(), CharaGen.CreateFromFilter(), EClass.debug, Quest.difficulty, CoreDebug.enable, EClass.game, MapBounds.GetRandomPoint(), Point.HasBlock, Point.HasChara, Card.id, Game.isLoading, item, GenBounds.ListEmptyPoint(), Party.members, Chara.party, EClass.pc, questMusic, EClass.rnd(), EClass.rndHalf(), EClass.sources, Spawn(), Map.things, and GenBounds.TryAddMapPiece().
Spawn()
void ZoneEventMusic.Spawn (Chara c, Point p) inline
Definition at line 92 of file ZoneEventMusic.cs.
    {
        EClass._zone.AddCard(c, p);
        if (c.hostility < Hostility.Neutral)
        {
            Hostility c_originalHostility = (c.hostility = Hostility.Neutral);
            c.c_originalHostility = c_originalHostility;
        }
    }
References EClass._zone, Zone.AddCard(), and Chara.hostility.
Referenced by OnVisit().
Property Documentation
questMusic
QuestMusic ZoneEventMusic.questMusic get
Definition at line 7 of file ZoneEventMusic.cs.
Referenced by OnReachTimeLimit(), and OnVisit().
TextWidgetDate
override string ZoneEventMusic.TextWidgetDate get
Definition at line 9 of file ZoneEventMusic.cs.
TimeLimit
override int ZoneEventMusic.TimeLimit get
Definition at line 11 of file ZoneEventMusic.cs.
The documentation for this class was generated from the following file:
Elin/ZoneEventMusic.cs