Elin Decompiled Documentation: TextureData Class Reference
TextureData Class Reference
Classes
class Date
Public Types
enum Type { Pass , World , DestTex }
Public Member Functions
void TryRefresh ()
void ForceRefresh ()
virtual bool IsValid ()
void Load (bool dateMatched)
void CreateReplace (int index, string path, TextureReplace.Source source, int sizeX, int sizeY)
void AddReplace (TextureReplace r)
void DeleteReplace (TextureReplace r)
void RemoveDeletedReplace (int index)
Static Public Member Functions
static void RefreshAll ()
Static Public Member Functions inherited from EScriptable
static int rnd (int a)
Public Attributes
string id
Type type
Date date
Texture2D tex
bool forceRefresh
int tileW
int tileH
string path
string texName
List< MeshPass > listPass = new List<MeshPass>()
Dictionary< int, TextureReplace > dictReplace = new Dictionary<int, TextureReplace>()
List< TextureReplace > listReplaceLocal = new List<TextureReplace>()
Detailed Description
Definition at line 6 of file TextureData.cs.
Member Enumeration Documentation
Type
enum TextureData.Type
Enumerator
Pass
World
DestTex
Definition at line 26 of file TextureData.cs.
    {
        Pass,
        World,
        DestTex
    }
Member Function Documentation
AddReplace()
void TextureData.AddReplace (TextureReplace r) inline
Definition at line 193 of file TextureData.cs.
    {
        TextureReplace textureReplace = dictReplace.TryGetValue(r.index);
        if (textureReplace != null)
        {
            if (r.source == TextureReplace.Source.Local && textureReplace.source != TextureReplace.Source.Local)
            {
                r.original = textureReplace;
            }
            else
            {
                textureReplace.DestoryTex();
            }
        }
        if (r.source == TextureReplace.Source.Local)
        {
            listReplaceLocal.Add(r);
        }
        dictReplace[r.index] = r;
    }
References TextureReplace.DestoryTex(), dictReplace, TextureReplace.index, listReplaceLocal, and TextureReplace.source.
Referenced by TextureManager.TryAddReplace().
CreateReplace()
void TextureData.CreateReplace (int index, string path, TextureReplace::Source source, int sizeX, int sizeY) inline
Definition at line 174 of file TextureData.cs.
    {
        string text = id + "_" + index + ".png";
        Texture2D texture2D = new Texture2D(tileW * sizeX, tileH * sizeY);
        int srcX = index % 100 * tileW;
        int srcY = tex.height - index / 100 * tileH - texture2D.height;
        Graphics.CopyTexture(tex, 0, 0, srcX, srcY, tileW * sizeX, tileH * sizeY, texture2D, 0, 0, 0, 0);
        byte[] bytes = texture2D.EncodeToPNG();
        try
        {
            File.WriteAllBytes(path + text, bytes);
            EClass.core.textures.TryAddReplace(new FileInfo(path + text), source, add: true, refresh: true);
        }
        catch
        {
        }
        UnityEngine.Object.Destroy(texture2D);
    }
References EClass.core, path, tex, Core.textures, tileH, tileW, and TextureManager.TryAddReplace().
Referenced by LayerTextureViewer.Update().
DeleteReplace()
void TextureData.DeleteReplace (TextureReplace r) inline
Definition at line 214 of file TextureData.cs.
    {
        r.file.Delete();
        RemoveDeletedReplace(r.index);
    }
References TextureReplace.file, TextureReplace.index, and RemoveDeletedReplace().
Referenced by LayerTextureViewer.Update().
ForceRefresh()
void TextureData.ForceRefresh () inline
Definition at line 98 of file TextureData.cs.
    {
        forceRefresh = true;
        TryRefresh();
    }
References forceRefresh, and TryRefresh().
Referenced by RefreshAll(), and LayerTextureViewer.Update().
IsValid()
virtual bool TextureData.IsValid () inline virtual
Definition at line 116 of file TextureData.cs.
    {
        switch (type)
        {
        case Type.Pass:
            foreach (MeshPass item in listPass)
            {
                if (!item.mat.GetTexture(texName))
                {
                    return false;
                }
            }
            return true;
        case Type.World:
            return EClass.scene.tileset.AtlasTexture;
        default:
            return true;
        }
    }
References item, listPass, EClass.scene, texName, Scene.tileset, and type.
Referenced by TryRefresh().
Load()
void TextureData.Load (bool dateMatched) inline
Definition at line 136 of file TextureData.cs.
    {
        if (!dateMatched)
        {
            Texture2D texture2D = IO.LoadPNG(path);
            if (!texture2D)
            {
                Debug.Log(path);
            }
            if (tex.width != texture2D.width || tex.height != texture2D.height)
            {
                Debug.Log(id + "/" + texture2D.width + "/" + texture2D.height + "/" + path);
            }
            tex.SetPixels32(texture2D.GetPixels32());
            tex.Apply();
            UnityEngine.Object.Destroy(texture2D);
            Debug.Log("Reloaded Texture:" + path);
        }
        switch (type)
        {
        case Type.Pass:
        {
            foreach (MeshPass item in listPass)
            {
                item.mat.SetTexture(texName, tex);
                if (item.haveShadowPass)
                {
                    item.shadowPass.mat.SetTexture(texName, tex);
                }
            }
            break;
        }
        case Type.World:
            EClass.scene.tileset.AtlasTexture = tex;
            break;
        }
    }
References Debug, item, listPass, path, tex, texName, and type.
Referenced by TryRefresh().
RefreshAll()
static void TextureData.RefreshAll () inline static
Definition at line 104 of file TextureData.cs.
    {
        if (!EClass.core.IsGameStarted)
        {
            return;
        }
        foreach (TextureData value in EClass.core.textures.texMap.Values)
        {
            value.ForceRefresh();
        }
    }
References EClass.core, ForceRefresh(), Core.IsGameStarted, TextureManager.texMap, and Core.textures.
RemoveDeletedReplace()
void TextureData.RemoveDeletedReplace (int index) inline
Definition at line 220 of file TextureData.cs.
    {
        TextureReplace textureReplace = dictReplace.TryGetValue(index);
        if (textureReplace != null)
        {
            textureReplace.DestoryTex();
            if (textureReplace.original != null && textureReplace.original.file.Exists)
            {
                dictReplace[index] = textureReplace.original;
            }
            else
            {
                dictReplace.Remove(index);
            }
        }
    }
References TextureReplace.DestoryTex(), dictReplace, TextureReplace.file, and TextureReplace.original.
Referenced by DeleteReplace(), and TryRefresh().
TryRefresh()
void TextureData.TryRefresh () inline
Definition at line 62 of file TextureData.cs.
    {
        DateTime lastWriteTime = File.GetLastWriteTime(path);
        bool flag = date.DateTime.Year != 1 && date.DateTime.Equals(lastWriteTime);
        if (dictReplace.Count > 0)
        {
            List<int> list = new List<int>();
            foreach (TextureReplace value in dictReplace.Values)
            {
                if (!File.Exists(value.file.FullName))
                {
                    forceRefresh = true;
                    list.Add(value.index);
                }
            }
            foreach (int item in list)
            {
                RemoveDeletedReplace(item);
            }
        }
        if (forceRefresh)
        {
            forceRefresh = false;
            flag = false;
        }
        if (!flag || !IsValid())
        {
            Load(flag);
        }
        foreach (TextureReplace value2 in dictReplace.Values)
        {
            value2.TryRefresh(!flag);
        }
        date.DateTime = lastWriteTime;
    }
References date, TextureData.Date.DateTime, dictReplace, TextureReplace.file, forceRefresh, TextureReplace.index, IsValid(), item, Load(), path, RemoveDeletedReplace(), and TextureReplace.TryRefresh().
Referenced by ForceRefresh(), TextureManager.RefreshTextures(), and TextureManager.TryAddReplace().
Member Data Documentation
date
Date TextureData.date
Definition at line 37 of file TextureData.cs.
Referenced by TryRefresh().
dictReplace
Dictionary<int, TextureReplace> TextureData.dictReplace = new Dictionary<int, TextureReplace>()
Definition at line 57 of file TextureData.cs.
Referenced by TextureManager.AddBase(), AddReplace(), TextureManager.ApplyLocalReplace(), LayerTextureViewer.RefreshPage(), RemoveDeletedReplace(), TryRefresh(), and LayerTextureViewer.Update().
forceRefresh
bool TextureData.forceRefresh
Definition at line 41 of file TextureData.cs.
Referenced by ForceRefresh(), and TryRefresh().
id
string TextureData.id
Definition at line 33 of file TextureData.cs.
Referenced by TextureManager.Add(), TextureManager.AddBase(), TextureManager.AddList(), and LayerTextureViewer.RefreshPage().
listPass
List<MeshPass> TextureData.listPass = new List<MeshPass>()
Definition at line 54 of file TextureData.cs.
Referenced by IsValid(), Load(), and TextureManager.TryAddReplace().
listReplaceLocal
List<TextureReplace> TextureData.listReplaceLocal = new List<TextureReplace>()
Definition at line 60 of file TextureData.cs.
Referenced by AddReplace(), and TextureManager.ApplyLocalReplace().
path
string TextureData.path
Definition at line 48 of file TextureData.cs.
Referenced by CreateReplace(), Load(), and TryRefresh().
tex
Texture2D TextureData.tex
Definition at line 39 of file TextureData.cs.
Referenced by TextureManager.AddBase(), CreateReplace(), Load(), TextureReplace.Load(), and LayerTextureViewer.RefreshPage().
texName
string TextureData.texName
Definition at line 51 of file TextureData.cs.
Referenced by IsValid(), and Load().
tileH
int TextureData.tileH
Definition at line 45 of file TextureData.cs.
Referenced by TextureManager.AddBase(), CreateReplace(), LayerTextureViewer.RefreshPage(), LayerTextureViewer.SetPos(), and LayerTextureViewer.Update().
tileW
int TextureData.tileW
Definition at line 43 of file TextureData.cs.
Referenced by CreateReplace(), TextureReplace.Load(), LayerTextureViewer.RefreshPage(), LayerTextureViewer.SetPos(), and LayerTextureViewer.Update().
type
Type TextureData.type
Definition at line 35 of file TextureData.cs.
Referenced by IsValid(), and Load().
The documentation for this class was generated from the following file:
Elin/TextureData.cs