Elin Decompiled Documentation: DropdownGrid Class Reference
DropdownGrid Class Reference
Public Member Functions
void Build (List< GridItem > items)
List< Thing > ListIngredients (Recipe.Ingredient ingredient, StockSearchMode searchMode)
void BuildIngredients (Recipe _recipe, Image _icon, Action _onValueChange, StockSearchMode _searchMode)
void Redraw ()
void Activate (Recipe.Ingredient ingredient, List< Thing > things)
void OnChangeIngredient ()
void Deactivate ()
void OnDestroy ()
void TrySelect (int a)
void Next ()
void Prev ()
Public Attributes
UIList list
UIList listDrop
RectTransform rectDrop
RectTransform rectDropContent
RectTransform pivot
Recipe recipe
Image icon
SoundData soundPop
Action onValueChange
int slots = 4
Vector3 fixPos
StockSearchMode searchMode
UIRecipeInfo recipeInfo
Dictionary< string, int > lastMats = new Dictionary<string, int>()
Static Public Attributes
static bool IsActive
static DropdownGrid Instance
Static Public Attributes inherited from EMono
static Core core
Private Member Functions
void Awake ()
void Update ()
Additional Inherited Members
Static Public Member Functions inherited from EMono
static int rnd (int a)
Properties inherited from EMono
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SoundManager Sound [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static CoreDebug debug [get]
Detailed Description
Definition at line 6 of file DropdownGrid.cs.
Member Function Documentation
Activate()
void DropdownGrid.Activate (Recipe::Ingredient ingredient, List< Thing > things) inline
Definition at line 259 of file DropdownGrid.cs.
    {
        IsActive = true;
        Instance = this;
        rectDrop.SetActive(enable: true);
        rectDrop.SetParent(EMono.ui.transform);
        rectDrop.sizeDelta = new Vector2(0f, 0f);
        rectDrop.anchoredPosition = Vector3.zero;
        listDrop.callbacks = new UIList.Callback<Thing, ButtonGrid>
        {
            onClick = delegate(Thing a, ButtonGrid b)
            {
                SE.Resource();
                ingredient.SetThing(a);
                recipe.SaveLastIngredients();
                OnChangeIngredient();
                if (onValueChange != null)
                {
                    onValueChange();
                }
                Deactivate();
                if ((bool)LayerCraft.Instance)
                {
                    LayerCraft.Instance.OnChangeIngredient();
                }
            },
            onInstantiate = delegate(Thing a, ButtonGrid b)
            {
                b.SetIngredient(recipe, a);
                b.SetOnClick(delegate
                {
                });
                b.onRightClick = delegate
                {
                };
            }
        };
        listDrop.Clear();
        foreach (Thing thing in things)
        {
            listDrop.Add(thing);
        }
        listDrop.Refresh();
        rectDropContent.position = list.transform.position + fixPos;
        if (listDrop.items.Count == 0)
        {
            SE.Beep();
            Deactivate();
        }
        else if ((bool)soundPop)
        {
            soundPop.Play();
        }
    }
References UIList.Add(), UIList.Clear(), Deactivate(), fixPos, Instance, LayerCraft.Instance, IsActive, UIList.items, listDrop, OnChangeIngredient(), LayerCraft.OnChangeIngredient(), onValueChange, recipe, rectDrop, UIList.Refresh(), Recipe.SaveLastIngredients(), ButtonGrid.SetIngredient(), soundPop, and EMono.ui.
Referenced by BuildIngredients().
Awake()
void DropdownGrid.Awake () inline private
Definition at line 41 of file DropdownGrid.cs.
    {
        rectDrop.SetActive(enable: false);
    }
References rectDrop.
Build()
void DropdownGrid.Build (List< GridItem > items) inline
Definition at line 51 of file DropdownGrid.cs.
    {
        list.Clear();
        list.callbacks = new UIList.Callback<GridItem, ButtonGrid>
        {
            onInstantiate = delegate(GridItem a, ButtonGrid b)
            {
                a.SetButton(b);
            },
            onClick = delegate(GridItem a, ButtonGrid b)
            {
                a.OnClick(b);
            },
            onRedraw = delegate(GridItem a, ButtonGrid b, int i)
            {
                a.SetButton(b);
            }
        };
        for (int j = 0; j < slots; j++)
        {
            if (j < items.Count)
            {
                list.Add(items[j]);
            }
            else
            {
                list.Add(new GridItem());
            }
        }
        list.Refresh();
    }
References UIList.Add(), UIList.Clear(), list, GridItem.OnClick(), UIList.Refresh(), GridItem.SetButton(), and slots.
Referenced by UIRecipeInfo.RefreshList().
BuildIngredients()
void DropdownGrid.BuildIngredients (Recipe _recipe, Image _icon, Action _onValueChange, StockSearchMode _searchMode) inline
Definition at line 88 of file DropdownGrid.cs.
    {
        recipe = _recipe;
        icon = _icon;
        list.Clear();
        onValueChange = _onValueChange;
        searchMode = _searchMode;
        if (recipe == null)
        {
            return;
        }
        list.callbacks = new UIList.Callback<Recipe.Ingredient, ButtonGrid>
        {
            onInstantiate = delegate(Recipe.Ingredient ingredient, ButtonGrid b)
            {
                List<Thing> things;
                if (ingredient.id.IsEmpty())
                {
                    b.SetIngredient(recipe, ingredient);
                }
                else
                {
                    bool flag = false;
                    List<int> list = EMono.player.recipes.lastIngredients.TryGetValue(recipe.id);
                    int num = recipe.ingredients.IndexOf(ingredient);
                    if (num != -1 && list != null && list.Count > num)
                    {
                        int uid = list[num];
                        if (uid != 0)
{
                            Thing thing = EMono.pc.things.Find((Thing t) => t.uid == uid) ?? EMono._map.Stocked.Find(uid);
                            if (thing != null && ingredient.IsValidIngredient(thing) && (!(thing.parent is Card card) || card.GetWindowSaveData() == null || !card.GetWindowSaveData().excludeCraft))
{
                                ingredient.SetThing(thing);
                                flag = true;
                            }
                        }
                    }
                    if (!flag)
                    {
                        things = ListIngredients(ingredient, searchMode);
                        if (things.Count == 0)
{
                            if (EMono.debug.godBuild && ingredient.thing == null)
{
                                Thing thing2 = ThingGen.Create(ingredient.IdThing, recipe.DefaultMaterial.alias).SetNum(99);
                                things.Add(thing2);
                                ingredient.SetThing(thing2);
                            }
                            else
{
                                ingredient.SetThing();
                                things.Insert(0, null);
                            }
                        }
                        else if (!ingredient.optional)
{
                            if (ingredient.thing == null)
{
                                int num2 = lastMats.TryGetValue(recipe.id, -1);
                                if (num2 != -1)
{
                                    foreach (Thing item in things)
{
                                        if (item.material.id == num2 && item.Num >= ingredient.req)
{
                                            ingredient.SetThing(item);
                                            break;
                                        }
                                    }
                                }
                                if (ingredient.thing == null)
{
                                    SourceMaterial.Row defaultMaterial = recipe.DefaultMaterial;
                                    foreach (Thing item2 in things)
{
                                        if (item2.material.id == defaultMaterial.id && item2.Num >= ingredient.req)
{
                                            ingredient.SetThing(item2);
                                            break;
                                        }
                                    }
                                    if (EMono.debug.godBuild && ingredient.thing == null)
{
                                        Thing thing3 = (ingredient.useCat ? ThingGen.CreateFromCategory(ingredient.id) : ThingGen.Create(ingredient.id, defaultMaterial.alias)).SetNum(99);
                                        things.Add(thing3);
                                        ingredient.SetThing(thing3);
                                    }
                                }
                                if (ingredient.thing == null)
{
                                    ingredient.SetThing(FindMax());
                                }
                            }
                            else
{
                                bool flag2 = true;
                                foreach (Thing item3 in things)
{
                                    if (ingredient.thing == item3)
{
                                        flag2 = false;
                                        break;
                                    }
                                }
                                if (flag2 && ingredient.thing == null)
{
                                    ingredient.SetThing(FindMax());
                                }
                            }
                        }
                    }
                    b.SetIngredient(recipe, ingredient);
                    b.onClick.RemoveAllListeners();
                    b.onClick.AddListener(delegate
                    {
                        List<Thing> list2 = ListIngredients(ingredient, searchMode);
                        if (list2.Count == 0 || list2[0] == null)
{
                            SE.Beep();
                        }
                        else if ((bool)rectDrop)
{
                            Activate(ingredient, list2);
                        }
                    });
                }
                Thing FindMax()
                {
                    if (things.Count == 0)
                    {
                        return null;
                    }
                    int num3 = 0;
                    Thing result = null;
                    foreach (Thing item4 in things)
                    {
                        if (item4.Num > num3)
{
                            num3 = item4.Num;
                            result = item4;
                        }
                    }
                    return result;
                }
            },
            onRedraw = delegate(Recipe.Ingredient a, ButtonGrid b, int i)
            {
                b.SetIngredient(recipe, a);
            }
        };
        for (int j = 0; j < slots; j++)
        {
            if (j < recipe.ingredients.Count)
            {
                list.Add(recipe.ingredients[j]);
                continue;
            }
            list.Add(new Recipe.Ingredient
            {
                id = ""
            });
        }
        list.Refresh();
    }
References EMono._map, Activate(), UIList.Add(), Card.Add(), card, UIList.Clear(), ThingGen.Create(), ThingGen.CreateFromCategory(), EMono.debug, Recipe.DefaultMaterial, Props.Find(), ThingContainer.Find(), CoreDebug.godBuild, icon, Recipe.id, Recipe.ingredients, Thing.IsValidIngredient(), item, RecipeManager.lastIngredients, lastMats, list, ListIngredients(), Card.material, Card.Num, onValueChange, Card.parent, EMono.pc, EMono.player, recipe, Player.recipes, rectDrop, UIList.Refresh(), searchMode, ButtonGrid.SetIngredient(), Card.SetNum(), slots, Map.Stocked, Card.things, and Card.uid.
Referenced by UIRecipeInfo.RefreshList().
Deactivate()
void DropdownGrid.Deactivate () inline
Definition at line 331 of file DropdownGrid.cs.
    {
        IsActive = false;
        if (rectDrop != null)
        {
            rectDrop.SetActive(enable: false);
        }
    }
References IsActive, and rectDrop.
Referenced by Activate(), and ActionMode.UpdateInput().
ListIngredients()
List< Thing > DropdownGrid.ListIngredients (Recipe::Ingredient ingredient, StockSearchMode searchMode) inline
Definition at line 83 of file DropdownGrid.cs.
    {
        return EMono._map.Stocked.ListThingStack(ingredient, searchMode).list;
    }
References EMono._map, ThingStack.list, Props.ListThingStack(), searchMode, and Map.Stocked.
Referenced by BuildIngredients().
Next()
void DropdownGrid.Next () inline
Definition at line 383 of file DropdownGrid.cs.
    {
        TrySelect(1);
    }
References TrySelect().
Referenced by Scene.OnUpdate().
OnChangeIngredient()
void DropdownGrid.OnChangeIngredient () inline
Definition at line 314 of file DropdownGrid.cs.
    {
        if (recipe == null)
        {
            return;
        }
        recipe.OnChangeIngredient();
        if ((bool)rectDrop)
        {
            if ((bool)icon)
            {
                recipe.renderRow.SetImage(icon, null, recipe.renderRow.GetColorInt(recipe.GetColorMaterial()), setNativeSize: true, 0, recipe.idSkin);
            }
            list.Redraw();
        }
    }
References RenderRow.GetColorInt(), Recipe.GetColorMaterial(), icon, Recipe.idSkin, list, Recipe.OnChangeIngredient(), recipe, rectDrop, UIList.Redraw(), Recipe.renderRow, and RenderRow.SetImage().
Referenced by Activate(), and TrySelect().
OnDestroy()
void DropdownGrid.OnDestroy () inline
Definition at line 340 of file DropdownGrid.cs.
    {
        IsActive = false;
        UnityEngine.Object.DestroyImmediate(rectDrop.gameObject);
    }
References IsActive, and rectDrop.
Prev()
void DropdownGrid.Prev () inline
Definition at line 388 of file DropdownGrid.cs.
    {
        TrySelect(-1);
    }
References TrySelect().
Referenced by Scene.OnUpdate().
Redraw()
void DropdownGrid.Redraw () inline
Definition at line 254 of file DropdownGrid.cs.
    {
        list.Redraw();
    }
References list, and UIList.Redraw().
Referenced by UIRecipeInfo.RefreshBalance().
TrySelect()
void DropdownGrid.TrySelect (int a) inline
Definition at line 346 of file DropdownGrid.cs.
    {
        ButtonGrid componentOf = InputModuleEX.GetComponentOf<ButtonGrid>();
        if (!componentOf || componentOf.ing == null)
        {
            return;
        }
        Recipe.Ingredient ing = componentOf.ing;
        List<Thing> list = EMono._map.Stocked.ListThingStack(ing, searchMode).list;
        int num = list.IndexOf(ing.thing);
        if (num != -1)
        {
            SE.Resource();
            num += a;
            if (num < 0)
            {
                num = 0;
            }
            if (num >= list.Count)
            {
                num = list.Count - 1;
            }
            ing.SetThing(list[num]);
            OnChangeIngredient();
            TooltipManager.Instance.ResetTooltips();
            componentOf.ShowTooltip();
            if ((bool)recipeInfo)
            {
                recipeInfo.RefreshImages();
            }
            if ((bool)LayerCraft.Instance)
            {
                LayerCraft.Instance.RefreshProduct();
            }
        }
    }
References EMono._map, ButtonGrid.ing, LayerCraft.Instance, TooltipManager.Instance, list, ThingStack.list, Props.ListThingStack(), OnChangeIngredient(), recipeInfo, UIRecipeInfo.RefreshImages(), LayerCraft.RefreshProduct(), TooltipManager.ResetTooltips(), searchMode, Recipe.Ingredient.SetThing(), UIButton.ShowTooltip(), Map.Stocked, and Recipe.Ingredient.thing.
Referenced by Next(), and Prev().
Update()
void DropdownGrid.Update () inline private
Definition at line 46 of file DropdownGrid.cs.
    {
        rectDrop.SetActive(IsActive);
    }
References IsActive, and rectDrop.
Member Data Documentation
fixPos
Vector3 DropdownGrid.fixPos
Definition at line 32 of file DropdownGrid.cs.
Referenced by Activate().
icon
Image DropdownGrid.icon
Definition at line 24 of file DropdownGrid.cs.
Referenced by BuildIngredients(), and OnChangeIngredient().
Instance
DropdownGrid DropdownGrid.Instance static
Definition at line 10 of file DropdownGrid.cs.
Referenced by Activate(), and ActionMode.UpdateInput().
IsActive
bool DropdownGrid.IsActive static
Definition at line 8 of file DropdownGrid.cs.
Referenced by Activate(), Deactivate(), OnDestroy(), Scene.OnUpdate(), Update(), and ActionMode.UpdateInput().
lastMats
Dictionary<string, int> DropdownGrid.lastMats = new Dictionary<string, int>()
Definition at line 39 of file DropdownGrid.cs.
Referenced by BuildIngredients().
list
UIList DropdownGrid.list
Definition at line 12 of file DropdownGrid.cs.
Referenced by Build(), BuildIngredients(), OnChangeIngredient(), Redraw(), and TrySelect().
listDrop
UIList DropdownGrid.listDrop
Definition at line 14 of file DropdownGrid.cs.
Referenced by Activate().
onValueChange
Action DropdownGrid.onValueChange
Definition at line 28 of file DropdownGrid.cs.
Referenced by Activate(), and BuildIngredients().
pivot
RectTransform DropdownGrid.pivot
Definition at line 20 of file DropdownGrid.cs.
Referenced by LayerCraft.OnAfterInit().
recipe
Recipe DropdownGrid.recipe
Definition at line 22 of file DropdownGrid.cs.
Referenced by Activate(), BuildIngredients(), and OnChangeIngredient().
recipeInfo
UIRecipeInfo DropdownGrid.recipeInfo
Definition at line 36 of file DropdownGrid.cs.
Referenced by TrySelect().
rectDrop
RectTransform DropdownGrid.rectDrop
Definition at line 16 of file DropdownGrid.cs.
Referenced by Activate(), Awake(), BuildIngredients(), Deactivate(), OnChangeIngredient(), OnDestroy(), and Update().
rectDropContent
RectTransform DropdownGrid.rectDropContent
Definition at line 18 of file DropdownGrid.cs.
searchMode
StockSearchMode DropdownGrid.searchMode
Definition at line 34 of file DropdownGrid.cs.
Referenced by BuildIngredients(), ListIngredients(), and TrySelect().
slots
int DropdownGrid.slots = 4
Definition at line 30 of file DropdownGrid.cs.
Referenced by Build(), and BuildIngredients().
soundPop
SoundData DropdownGrid.soundPop
Definition at line 26 of file DropdownGrid.cs.
Referenced by Activate().
The documentation for this class was generated from the following file:
Elin/DropdownGrid.cs