Elin Decompiled Documentation: GamePrincipal Class Reference
GamePrincipal Class Reference
Public Member Functions
int GetGrade (int score)
string GetTitle ()
int GetScore ()
int GetScore (string s)
int GetValidScore ()
void Apply ()
Public Attributes
int idTemplate
int socre
int dropRateMtp
bool ignoreEvaluate
bool disableDeathPenaltyProtection
bool tax
bool opMilk
bool disableManualSave
bool permadeath
bool infiniteMarketFund
bool disableUsermapBenefit
bool dropRate
Properties
bool IsCustom [get]
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Additional Inherited Members
Static Public Member Functions inherited from EClass
static int rnd (int a)
static int curve (int a, int start, int step, int rate=75)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Static Public Attributes inherited from EClass
static Core core
Detailed Description
Definition at line 6 of file GamePrincipal.cs.
Member Function Documentation
Apply()
void GamePrincipal.Apply () inline
Definition at line 137 of file GamePrincipal.cs.
    {
        EClass.player.validScore = GetScore();
    }
References GetScore().
Referenced by LayerWorldSetting.OnKill().
GetGrade()
int GamePrincipal.GetGrade (int score) inline
Definition at line 46 of file GamePrincipal.cs.
    {
        return Mathf.Clamp(score / 20, 0, 5);
    }
Referenced by GetTitle().
GetScore() [1/2]
int GamePrincipal.GetScore () inline
Definition at line 57 of file GamePrincipal.cs.
    {
        if (ignoreEvaluate)
        {
            return 0;
        }
        int num = 0;
        if (tax)
        {
            num += GetScore("tax");
        }
        if (disableManualSave)
        {
            num += GetScore("disableManualSave");
        }
        if (disableDeathPenaltyProtection)
        {
            num += GetScore("disableDeathPenaltyProtection");
        }
        if (disableUsermapBenefit)
        {
            num += GetScore("disableUsermapBenefit");
        }
        if (permadeath)
        {
            num += GetScore("permadeath");
        }
        if (infiniteMarketFund)
        {
            num += GetScore("infiniteMarketFund");
        }
        if (opMilk)
        {
            num += GetScore("opMilk");
        }
        if (dropRate)
        {
            num += GetScore("dropRate");
        }
        if (num >= 0)
        {
            return num;
        }
        return 0;
    }
References disableDeathPenaltyProtection, disableManualSave, disableUsermapBenefit, dropRate, GetScore(), ignoreEvaluate, infiniteMarketFund, opMilk, permadeath, and tax.
Referenced by Apply(), GetScore(), GetTitle(), GetValidScore(), LayerWorldSetting.Refresh(), and LayerWorldSetting.RefreshScore().
GetScore() [2/2]
int GamePrincipal.GetScore (string s) inline
Definition at line 103 of file GamePrincipal.cs.
    {
        if (ignoreEvaluate)
        {
            return 0;
        }
        return s switch
        {
            "tax" => 20,
            "disableManualSave" => 20,
            "disableDeathPenaltyProtection" => 10,
            "disableUsermapBenefit" => 20,
            "permadeath" => 50,
            "infiniteMarketFund" => -40,
            "opMilk" => -40,
            "dropRate" => 20 + dropRateMtp * -10,
            _ => 0,
        };
    }
References dropRateMtp, and ignoreEvaluate.
GetTitle()
string GamePrincipal.GetTitle () inline
Definition at line 51 of file GamePrincipal.cs.
    {
        int grade = GetGrade(GetScore());
        return Lang.GetList("pp_titles")[grade];
    }
References GetGrade(), Lang.GetList(), and GetScore().
Referenced by LayerWorldSetting.RefreshScore().
GetValidScore()
int GamePrincipal.GetValidScore () inline
Definition at line 123 of file GamePrincipal.cs.
    {
        int score = GetScore();
        if (EClass.player.validScore != -1)
        {
            if (score >= EClass.player.validScore)
            {
                return EClass.player.validScore;
            }
            return score;
        }
        return score;
    }
References GetScore(), EClass.player, and Player.validScore.
Referenced by LayerWorldSetting.RefreshScore().
Member Data Documentation
disableDeathPenaltyProtection
bool GamePrincipal.disableDeathPenaltyProtection
Definition at line 21 of file GamePrincipal.cs.
Referenced by GetScore(), and LayerWorldSetting.Refresh().
disableManualSave
bool GamePrincipal.disableManualSave
Definition at line 30 of file GamePrincipal.cs.
Referenced by GetScore(), and LayerWorldSetting.Refresh().
disableUsermapBenefit
bool GamePrincipal.disableUsermapBenefit
Definition at line 39 of file GamePrincipal.cs.
Referenced by GetScore(), and LayerWorldSetting.Refresh().
dropRate
bool GamePrincipal.dropRate
Definition at line 42 of file GamePrincipal.cs.
Referenced by GetScore(), and LayerWorldSetting.Refresh().
dropRateMtp
int GamePrincipal.dropRateMtp
Definition at line 15 of file GamePrincipal.cs.
Referenced by GetScore(), and LayerWorldSetting.Refresh().
idTemplate
int GamePrincipal.idTemplate
Definition at line 9 of file GamePrincipal.cs.
Referenced by LayerWorldSetting.Refresh().
ignoreEvaluate
bool GamePrincipal.ignoreEvaluate
Definition at line 18 of file GamePrincipal.cs.
Referenced by GetScore(), LayerWorldSetting.Refresh(), and LayerWorldSetting.RefreshScore().
infiniteMarketFund
bool GamePrincipal.infiniteMarketFund
Definition at line 36 of file GamePrincipal.cs.
Referenced by GetScore(), and LayerWorldSetting.Refresh().
opMilk
bool GamePrincipal.opMilk
Definition at line 27 of file GamePrincipal.cs.
Referenced by GetScore(), and LayerWorldSetting.Refresh().
permadeath
bool GamePrincipal.permadeath
Definition at line 33 of file GamePrincipal.cs.
Referenced by GetScore(), and LayerWorldSetting.Refresh().
socre
int GamePrincipal.socre
Definition at line 12 of file GamePrincipal.cs.
tax
bool GamePrincipal.tax
Definition at line 24 of file GamePrincipal.cs.
Referenced by GetScore(), and LayerWorldSetting.Refresh().
Property Documentation
IsCustom
bool GamePrincipal.IsCustom get
Definition at line 44 of file GamePrincipal.cs.
Referenced by LayerWorldSetting.Refresh().
The documentation for this class was generated from the following file:
Elin/GamePrincipal.cs