Elin Decompiled Documentation: SourceRace Class Reference
SourceRace Class Reference
Classes
class Row
Public Member Functions
override Row CreateRow ()
override Row CreateRowByMapping (IReadOnlyDictionary< string, int > mapping)
override void SetRow (Row r)
override IReadOnlyDictionary< string, int > GetRowMapping ()
override IReadOnlyDictionary< string, string > GetTypeMapping ()
override void OnInit ()
Public Member Functions inherited from SourceDataString< SourceRace.Row >
override T GetRow (string id)
Static Public Attributes
static readonly IReadOnlyDictionary< string, int > RowMapping
static readonly IReadOnlyDictionary< string, string > TypeMapping
Detailed Description
Definition at line 4 of file SourceRace.cs.
Member Function Documentation
CreateRow()
override Row SourceRace.CreateRow () inline
Definition at line 226 of file SourceRace.cs.
    {
        return new Row
        {
            id = SourceData.GetString(0),
            name_JP = SourceData.GetString(1),
            name = SourceData.GetString(2),
            playable = SourceData.GetInt(3),
            tag = SourceData.GetStringArray(4),
            life = SourceData.GetInt(5),
            mana = SourceData.GetInt(6),
            vigor = SourceData.GetInt(7),
            DV = SourceData.GetInt(8),
            PV = SourceData.GetInt(9),
            PDR = SourceData.GetInt(10),
            EDR = SourceData.GetInt(11),
            EP = SourceData.GetInt(12),
            STR = SourceData.GetInt(13),
            END = SourceData.GetInt(14),
            DEX = SourceData.GetInt(15),
            PER = SourceData.GetInt(16),
            LER = SourceData.GetInt(17),
            WIL = SourceData.GetInt(18),
            MAG = SourceData.GetInt(19),
            CHA = SourceData.GetInt(20),
            SPD = SourceData.GetInt(21),
            INT = SourceData.GetInt(23),
            martial = SourceData.GetInt(24),
            pen = SourceData.GetInt(25),
            elements = Core.ParseElements(SourceData.GetStr(26)),
            skill = SourceData.GetString(27),
            figure = SourceData.GetString(28),
            geneCap = SourceData.GetInt(29),
            material = SourceData.GetString(30),
            corpse = SourceData.GetStringArray(31),
            loot = SourceData.GetStringArray(32),
            blood = SourceData.GetInt(33),
            meleeStyle = SourceData.GetString(34),
            castStyle = SourceData.GetString(35),
            EQ = SourceData.GetStringArray(36),
            sex = SourceData.GetInt(37),
            age = SourceData.GetIntArray(38),
            height = SourceData.GetInt(39),
            breeder = SourceData.GetInt(40),
            food = SourceData.GetStringArray(41),
            fur = SourceData.GetString(42),
            detail_JP = SourceData.GetString(43),
            detail = SourceData.GetString(44)
        };
    }
References figure, food, fur, SourceData< T, T2 >.GetInt(), SourceData< T, T2 >.GetIntArray(), SourceData< T, T2 >.GetStr(), SourceData< T, T2 >.GetString(), SourceData< T, T2 >.GetStringArray(), material, and Core.ParseElements().
CreateRowByMapping()
override Row SourceRace.CreateRowByMapping (IReadOnlyDictionary< string, int > mapping) inline
Definition at line 277 of file SourceRace.cs.
    {
        return new Row
        {
            id = SourceData.GetString(mapping["id"]),
            name_JP = SourceData.GetString(mapping["name_JP"]),
            name = SourceData.GetString(mapping["name"]),
            playable = SourceData.GetInt(mapping["playable"]),
            tag = SourceData.GetStringArray(mapping["tag"]),
            life = SourceData.GetInt(mapping["life"]),
            mana = SourceData.GetInt(mapping["mana"]),
            vigor = SourceData.GetInt(mapping["vigor"]),
            DV = SourceData.GetInt(mapping["DV"]),
            PV = SourceData.GetInt(mapping["PV"]),
            PDR = SourceData.GetInt(mapping["PDR"]),
            EDR = SourceData.GetInt(mapping["EDR"]),
            EP = SourceData.GetInt(mapping["EP"]),
            STR = SourceData.GetInt(mapping["STR"]),
            END = SourceData.GetInt(mapping["END"]),
            DEX = SourceData.GetInt(mapping["DEX"]),
            PER = SourceData.GetInt(mapping["PER"]),
            LER = SourceData.GetInt(mapping["LER"]),
            WIL = SourceData.GetInt(mapping["WIL"]),
            MAG = SourceData.GetInt(mapping["MAG"]),
            CHA = SourceData.GetInt(mapping["CHA"]),
            SPD = SourceData.GetInt(mapping["SPD"]),
            INT = SourceData.GetInt(mapping["INT"]),
            martial = SourceData.GetInt(mapping["martial"]),
            pen = SourceData.GetInt(mapping["pen"]),
            elements = Core.ParseElements(SourceData.GetStr(mapping["elements"])),
            skill = SourceData.GetString(mapping["skill"]),
            figure = SourceData.GetString(mapping["figure"]),
            geneCap = SourceData.GetInt(mapping["geneCap"]),
            material = SourceData.GetString(mapping["material"]),
            corpse = SourceData.GetStringArray(mapping["corpse"]),
            loot = SourceData.GetStringArray(mapping["loot"]),
            blood = SourceData.GetInt(mapping["blood"]),
            meleeStyle = SourceData.GetString(mapping["meleeStyle"]),
            castStyle = SourceData.GetString(mapping["castStyle"]),
            EQ = SourceData.GetStringArray(mapping["EQ"]),
            sex = SourceData.GetInt(mapping["sex"]),
            age = SourceData.GetIntArray(mapping["age"]),
            height = SourceData.GetInt(mapping["height"]),
            breeder = SourceData.GetInt(mapping["breeder"]),
            food = SourceData.GetStringArray(mapping["food"]),
            fur = SourceData.GetString(mapping["fur"]),
            detail_JP = SourceData.GetString(mapping["detail_JP"]),
            detail = SourceData.GetString(mapping["detail"])
        };
    }
References figure, food, fur, SourceData< T, T2 >.GetInt(), SourceData< T, T2 >.GetIntArray(), SourceData< T, T2 >.GetStr(), SourceData< T, T2 >.GetString(), SourceData< T, T2 >.GetStringArray(), material, and Core.ParseElements().
GetRowMapping()
override IReadOnlyDictionary< string, int > SourceRace.GetRowMapping () inline
Definition at line 333 of file SourceRace.cs.
    {
        return RowMapping;
    }
References RowMapping.
GetTypeMapping()
override IReadOnlyDictionary< string, string > SourceRace.GetTypeMapping () inline
Definition at line 338 of file SourceRace.cs.
    {
        return TypeMapping;
    }
References TypeMapping.
OnInit()
override void SourceRace.OnInit () inline
Definition at line 343 of file SourceRace.cs.
    {
        foreach (Row row in rows)
        {
            Dictionary<int, int> dictionary = new Dictionary<int, int>();
            dictionary[70] = row.STR;
            dictionary[71] = row.END;
            dictionary[72] = row.DEX;
            dictionary[73] = row.PER;
            dictionary[74] = row.LER;
            dictionary[75] = row.WIL;
            dictionary[76] = row.MAG;
            dictionary[77] = row.CHA;
            dictionary[79] = row.SPD;
            dictionary[80] = row.INT;
            dictionary[100] = row.martial;
            dictionary[60] = row.life;
            dictionary[61] = row.mana;
            dictionary[62] = row.vigor;
            dictionary[65] = row.PV;
            dictionary[64] = row.DV;
            dictionary[55] = row.PDR;
            dictionary[56] = row.EDR;
            dictionary[57] = row.EP;
            dictionary[261] = 1;
            dictionary[225] = 1;
            dictionary[255] = 1;
            dictionary[220] = 1;
            dictionary[250] = 1;
            dictionary[101] = 1;
            dictionary[102] = 1;
            dictionary[103] = 1;
            dictionary[107] = 1;
            dictionary[106] = 1;
            dictionary[110] = 1;
            dictionary[111] = 1;
            dictionary[104] = 1;
            dictionary[109] = 1;
            dictionary[108] = 1;
            dictionary[123] = 1;
            dictionary[122] = 1;
            dictionary[120] = 1;
            dictionary[150] = 1;
            dictionary[301] = 1;
            dictionary[306] = 1;
            row.elementMap = Element.GetElementMap(row.elements, dictionary);
        }
    }
References SourceRace.Row.CHA, SourceRace.Row.DEX, SourceRace.Row.DV, SourceRace.Row.EDR, SourceRace.Row.elements, SourceRace.Row.END, SourceRace.Row.EP, Element.GetElementMap(), SourceRace.Row.INT, SourceRace.Row.LER, SourceRace.Row.life, SourceRace.Row.MAG, SourceRace.Row.mana, SourceRace.Row.martial, SourceRace.Row.PDR, SourceRace.Row.PER, SourceRace.Row.PV, SourceRace.Row.SPD, SourceRace.Row.STR, SourceRace.Row.vigor, and SourceRace.Row.WIL.
SetRow()
override void SourceRace.SetRow (Row r) inline
Definition at line 328 of file SourceRace.cs.
    {
        map[r.id] = r;
    }
References SourceRace.Row.id.
Member Data Documentation
RowMapping
readonly IReadOnlyDictionary<string, int> SourceRace.RowMapping static
Definition at line 130 of file SourceRace.cs.
Referenced by GetRowMapping().
TypeMapping
readonly IReadOnlyDictionary<string, string> SourceRace.TypeMapping static
Definition at line 178 of file SourceRace.cs.
Referenced by GetTypeMapping().
The documentation for this class was generated from the following file:
Elin/SourceRace.cs