Elin Decompiled Documentation: InvOwner Class Reference
InvOwner Class Reference
Classes
class ErrorMessage
class ForceGiveData
class Interaction
class ListInteraction
class Transaction
Public Member Functions
virtual bool AllowHold (Thing t)
virtual bool AllowMoved (Thing t)
virtual bool ShouldShowGuide (Thing t)
virtual bool AllowDrop (Thing t)
virtual Thing CreateDefaultContainer ()
virtual void BuildUICurrency (UICurrency uiCurrency, bool canReroll=false)
bool IsWeightOver (Thing t)
InvOwner (Card owner, Card container=null, CurrencyType _currency=CurrencyType.None, PriceType _price=PriceType.Default)
void Init ()
virtual void OnInit ()
virtual void OnClick (ButtonGrid button)
virtual void OnRightClick (ButtonGrid button)
virtual void OnRightPressed (ButtonGrid button)
InvOwner GetShitDestOwner (ButtonGrid b, bool rightMouse=false)
virtual void OnShiftClick (ButtonGrid b, bool rightMouse=false)
virtual bool CanShiftClick (ButtonGrid b, bool rightMouse=false)
virtual string GetTextShiftClick (ButtonGrid b)
virtual void OnCtrlClick (ButtonGrid button)
virtual bool CanCtrlClick (ButtonGrid b)
virtual string GetTextCtrlClick (ButtonGrid b)
virtual void OnAltClick (ButtonGrid button)
virtual bool CanAltClick (ButtonGrid b)
virtual string GetTextAltClick (ButtonGrid b)
void Grab (DragItemCard.DragInfo from)
Thing PutBack (DragItemCard.DragInfo from)
void OnStartDrag (DragItemCard.DragInfo from)
virtual bool OnCancelDrag (DragItemCard.DragInfo from)
virtual bool OnDrag (DragItemCard.DragInfo from, DragItemCard.DragInfo to, bool execute, bool cancel=false)
virtual void OnProcess (Thing t)
bool CanOpenContainer (Thing t)
InvOwner.ListInteraction ListInteractions (ButtonGrid b, bool context)
bool TryHold (Thing t)
virtual void ListInteractions (InvOwner.ListInteraction list, Thing t, Trait trait, ButtonGrid b, bool context)
virtual string GetAutoUseLang (ButtonGrid button)
void AutoUse (ButtonGrid button, bool repeat=false)
void ShowContextMenu (ButtonGrid button)
virtual int GetPrice (Thing t, CurrencyType currency, int num, bool sell)
virtual string GetTextDetail (Thing t, CurrencyType currency, int num, bool sell)
virtual void OnWriteNote (ButtonGrid button, UINote n)
virtual string IDCostIcon (Thing t)
virtual bool IsFailByCurse (Thing t)
Public Attributes
bool includeChildren
CurrencyType currency
PriceType priceType
HomeResource homeResource
Card owner
Card Container
List< ButtonGrid > buttons = new List<ButtonGrid>()
Static Public Attributes
static InvOwner.ForceGiveData forceGive = new InvOwner.ForceGiveData()
static InvOwner Trader
static InvOwner Main
static float clickTimer
Static Public Attributes inherited from EClass
static Core core
Properties
static bool HasTrader [get]
static bool FreeTransfer [get]
virtual bool AllowAutouse [get]
virtual bool AllowContext [get]
virtual bool AllowSell [get]
virtual bool AlwaysShowTooltip [get]
virtual bool UseGuide [get]
virtual bool AllowTransfer [get]
virtual bool AllowDropOnDrag [get]
virtual string langTransfer [get]
virtual int destInvY [get]
virtual bool HasTransaction [get]
virtual bool CopyOnTransfer [get]
virtual bool SingleTarget [get]
bool UseHomeResource [get]
bool IsMagicChest [get]
List< Thing > Things [get]
Chara Chara [get]
ContainerType ContainerType [get]
virtual bool InvertSell [get]
virtual int numDragGrid [get]
virtual bool ShowNew [get]
virtual bool DenyImportant [get]
InvOwner destInvOwner [get]
string IDCurrency [get]
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Additional Inherited Members
Static Public Member Functions inherited from EClass
static int rnd (int a)
static int curve (int a, int start, int step, int rate=75)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Detailed Description
Definition at line 5 of file InvOwner.cs.
Constructor & Destructor Documentation
InvOwner()
InvOwner.InvOwner (Card owner, Card container = null, CurrencyType _currency = CurrencyType::None, PriceType _price = PriceType::Default) inline
Definition at line 270 of file InvOwner.cs.
    {
        this.currency = _currency;
        this.priceType = _price;
        this.owner = owner;
        this.Container = (container ?? owner);
        if (this.currency == CurrencyType.BranchMoney)
        {
            this.homeResource = EClass.BranchOrHomeBranch.resources.money;
        }
    }
References EClass.BranchOrHomeBranch, currency, HomeResourceManager.money, owner, and FactionBranch.resources.
Member Function Documentation
AllowDrop()
virtual bool InvOwner.AllowDrop (Thing t) inline virtual
Reimplemented in InvOwnerEquip.
Definition at line 106 of file InvOwner.cs.
    {
        return !EClass._zone.IsRegion || t.trait is TraitAbility;
    }
Referenced by CanAltClick().
AllowHold()
virtual bool InvOwner.AllowHold (Thing t) inline virtual
Reimplemented in InvOwnerAutoCombatBar, InvOwnerDraglet, and InvOwnerToolbelt.
Definition at line 47 of file InvOwner.cs.
    {
        if (!t.trait.CanBeDropped)
        {
            return false;
        }
        if (t.isEquipped && t.IsCursed)
        {
            return false;
        }
        if (this.Container.isChara && !this.Container.IsPC)
        {
            return !(t.id == "money") && !t.isGifted && !t.isNPCProperty && (!t.isEquipped || this.Container.Chara.affinity.CanForceTradeEquip());
        }
        return !t.trait.CanOnlyCarry && (!this.Container.isNPCProperty || !InvOwner.FreeTransfer);
    }
References Trait.CanBeDropped, Container, FreeTransfer, Card.isChara, Card.IsCursed, Thing.isEquipped, Card.isGifted, Card.isNPCProperty, and Card.trait.
Referenced by CanShiftClick(), ListInteractions(), OnClick(), and TryHold().
AllowMoved()
virtual bool InvOwner.AllowMoved (Thing t) inline virtual
Reimplemented in InvOwnerCopyShop.
Definition at line 64 of file InvOwner.cs.
    {
        return true;
    }
Referenced by CanShiftClick(), and ListInteractions().
AutoUse()
void InvOwner.AutoUse (ButtonGrid button, bool repeat = false) inline
Definition at line 1208 of file InvOwner.cs.
    {
        Card card = button.card;
        if (!ActionMode.Adv.IsActive && !ActionMode.Region.IsActive)
        {
            return;
        }
        if (!EClass.pc.HasNoGoal)
        {
            SE.Beep();
            return;
        }
        InvOwner.ListInteraction listInteraction = this.ListInteractions(button, false);
        if (listInteraction.Count == 0)
        {
            SE.Beep();
            return;
        }
        foreach (InvOwner.Interaction interaction in listInteraction)
        {
            if (EClass.player.IsPriorityAction(interaction.idPriority, listInteraction.thing))
            {
                listInteraction.Insert(0, interaction);
                break;
            }
        }
        if (repeat && !listInteraction[0].repeatable)
        {
            return;
        }
        listInteraction[0].action();
    }
References ActionMode.Adv, ButtonGrid.card, Chara.HasNoGoal, ActionMode.IsActive, Player.IsPriorityAction(), EClass.pc, EClass.player, ActionMode.Region, and InvOwner.ListInteraction.thing.
BuildUICurrency()
virtual void InvOwner.BuildUICurrency (UICurrency uiCurrency, bool canReroll = false) inline virtual
Reimplemented in InvOwnerDraglet, and InvOwnerRecycle.
Definition at line 156 of file InvOwner.cs.
    {
        bool flag = this.Container.isChara && !this.Container.IsPC;
        uiCurrency.SetActive(this.currency > CurrencyType.None || flag);
        uiCurrency.target = this.owner;
        if (this.currency > CurrencyType.None || flag)
        {
            uiCurrency.Build(new UICurrency.Options
            {
                weight = flag,
                money = (this.currency == CurrencyType.Money),
                plat = (this.currency == CurrencyType.Plat),
                medal = (this.currency == CurrencyType.Medal),
                money2 = (this.currency == CurrencyType.Money2),
                influence = (this.currency == CurrencyType.Influence),
                casino = (this.currency == CurrencyType.Casino_coin),
                ecopo = (this.currency == CurrencyType.Ecopo)
            });
        }
    }
References UICurrency.Build(), Container, currency, Card.IsPC, and owner.
CanAltClick()
virtual bool InvOwner.CanAltClick (ButtonGrid b) inline virtual
Definition at line 628 of file InvOwner.cs.
    {
        return EInput.isAltDown && EClass.pc.HasNoGoal && !this.Container.isNPCProperty && this.currency == CurrencyType.None && this.AllowDrop(b.card.Thing);
    }
References AllowDrop(), ButtonGrid.card, and Card.Thing.
Referenced by OnClick().
CanCtrlClick()
virtual bool InvOwner.CanCtrlClick (ButtonGrid b) inline virtual
Definition at line 613 of file InvOwner.cs.
    {
        return EInput.isCtrlDown && EClass.pc.HasNoGoal && !this.Container.isNPCProperty && b.card.Num > 1;
    }
Referenced by OnClick().
CanOpenContainer()
bool InvOwner.CanOpenContainer (Thing t) inline
Definition at line 824 of file InvOwner.cs.
    {
        if (!t.trait.CanOpenContainer)
        {
            return false;
        }
        if (t.parent != EClass.pc)
        {
            Thing thing = t.parent as Thing;
            return ((thing != null) ? thing.trait : null) is TraitToolBelt;
        }
        return true;
    }
References Trait.CanOpenContainer, Card.parent, EClass.pc, and Card.trait.
Referenced by ListInteractions().
CanShiftClick()
virtual bool InvOwner.CanShiftClick (ButtonGrid b, bool rightMouse = false) inline virtual
Definition at line 532 of file InvOwner.cs.
    {
        if (!EInput.isShiftDown && !rightMouse)
        {
            return false;
        }
        if (!EClass.pc.HasNoGoal || this.Container.isNPCProperty || this.currency != CurrencyType.None)
        {
            return false;
        }
        if (rightMouse && !InvOwner.HasTrader)
        {
            return false;
        }
        if (InvOwner.HasTrader)
        {
            if (InvOwner.Trader is InvOwnerDraglet || InvOwner.Trader.Container.isNPCProperty || InvOwner.Trader.currency != CurrencyType.None)
            {
                return false;
            }
            if (InvOwner.Trader.Container.isChara)
            {
                return false;
            }
            Card card = b.card;
            if (card != null && card.c_isImportant)
            {
                return false;
            }
        }
        InvOwner shitDestOwner = this.GetShitDestOwner(b, rightMouse);
        if (shitDestOwner == null)
        {
            return false;
        }
        Thing thing = b.card.Thing;
        if (thing.trait.IsContainer && thing.things.Count > 0)
        {
            return false;
        }
        if (!this.AllowHold(thing))
        {
            return false;
        }
        if (InvOwner.HasTrader)
        {
            if (!InvOwner.Trader.Container.GetRootCard().IsPC && thing.trait is TraitCatalyst)
            {
                return false;
            }
            if (!InvOwner.Trader.AllowMoved(thing))
            {
                return false;
            }
        }
        if (shitDestOwner.Container.isChara && !shitDestOwner.owner.IsPC && !shitDestOwner.owner.Chara.CanAcceptItem(thing, -1))
        {
            return false;
        }
        if (b.invOwner.owner.isChara && b.invOwner.owner.Chara.IsPCFaction && !b.invOwner.owner.IsPC && thing.IsRangedWeapon)
        {
            thing.ammoData = null;
            thing.c_ammo = 0;
        }
        if (EInput.isShiftDown)
        {
            LayerInventory.highlightInv = shitDestOwner;
        }
        return true;
    }
References AllowHold(), AllowMoved(), Card.c_isImportant, Chara.CanAcceptItem(), ButtonGrid.card, Card.Chara, Container, currency, Card.GetRootCard(), GetShitDestOwner(), Chara.HasNoGoal, HasTrader, ButtonGrid.invOwner, Card.isChara, Trait.IsContainer, Card.isNPCProperty, Card.IsPC, Chara.IsPCFaction, Card.IsRangedWeapon, owner, EClass.pc, Card.Thing, Card.things, Trader, and Card.trait.
Referenced by OnClick(), and ActionMode.UpdateInput().
CreateDefaultContainer()
virtual Thing InvOwner.CreateDefaultContainer () inline virtual
Reimplemented in InvOwnerChangeMaterial, InvOwnerEnchant, InvOwnerIdentify, InvOwnerLighten, InvOwnerReconstruction, and InvOwnerUncurse.
Definition at line 127 of file InvOwner.cs.
    {
        return ThingGen.Create("chest3", -1, -1);
    }
References ThingGen.Create().
Referenced by Init().
GetAutoUseLang()
virtual string InvOwner.GetAutoUseLang (ButtonGrid button) inline virtual
Reimplemented in InvOwnerAlly.
Definition at line 1167 of file InvOwner.cs.
    {
        if (button == null || button.gameObject == null)
        {
            return "";
        }
        InvOwner.ListInteraction list = this.ListInteractions(button, false);
        foreach (InvOwner.Interaction interaction in list)
        {
            if (EClass.player.IsPriorityAction(interaction.idPriority, list.thing))
            {
                list.Insert(0, interaction);
                break;
            }
        }
        if (button.card.trait.HoldAsDefaultInteraction && list.Count > 0)
        {
            InvOwner.Interaction interaction2 = list[0];
            if (interaction2.name == "actPick" || interaction2.name == "actHold" || interaction2.name == "actHoldTool")
            {
                return null;
            }
        }
        list.ForeachReverse(delegate(InvOwner.Interaction a)
        {
            if (a.name == "actPick" || a.name == "actHold" || a.name == "actHoldTool")
            {
                list.Remove(a);
            }
        });
        if (list.Count == 0)
        {
            return null;
        }
        if (list[0].name == "actTransfer")
        {
            return null;
        }
        return list[0].name.lang();
    }
References ButtonGrid.card, Trait.HoldAsDefaultInteraction, Player.IsPriorityAction(), ListInteractions(), InvOwner.Interaction.name, EClass.player, InvOwner.ListInteraction.thing, and Card.trait.
GetPrice()
virtual int InvOwner.GetPrice (Thing t, CurrencyType currency, int num, bool sell) inline virtual
Reimplemented in InvOwnerDraglet.
Definition at line 1263 of file InvOwner.cs.
    {
        return ShopTransaction.current.GetPrice(t, num, sell);
    }
References ShopTransaction.current, and ShopTransaction.GetPrice().
Referenced by InvOwner.Transaction.GetPrice().
GetShitDestOwner()
InvOwner InvOwner.GetShitDestOwner (ButtonGrid b, bool rightMouse = false) inline
Definition at line 458 of file InvOwner.cs.
    {
        Thing thing = b.card.Thing;
        if (rightMouse && !b.invOwner.owner.IsPC)
        {
            LayerInventory pclayer = LayerInventory.GetPCLayer();
            if (pclayer == null)
            {
                return null;
            }
            return pclayer.Inv;
        }
        else if (InvOwner.Trader != null)
        {
            if (b.invOwner.owner.IsPC)
            {
                if (!InvOwner.Trader.Container.things.IsFull(thing, true, true))
                {
                    return InvOwner.Trader;
                }
                return null;
            }
            else
            {
                LayerInventory topLayer = LayerInventory.GetTopLayer(thing, true, InvOwner.Trader);
                if (topLayer == null)
                {
                    return null;
                }
                return topLayer.Inv;
            }
        }
        else
        {
            LayerInventory topLayer2 = LayerInventory.GetTopLayer(thing, true, this);
            if (topLayer2 == null)
            {
                return null;
            }
            return topLayer2.Inv;
        }
    }
References ButtonGrid.card, Container, LayerInventory.GetPCLayer(), LayerInventory.GetTopLayer(), LayerInventory.Inv, ButtonGrid.invOwner, ThingContainer.IsFull(), Card.IsPC, owner, Card.Thing, Card.things, and Trader.
Referenced by CanShiftClick(), and OnShiftClick().
GetTextAltClick()
virtual string InvOwner.GetTextAltClick (ButtonGrid b) inline virtual
Definition at line 633 of file InvOwner.cs.
    {
        return "actDrop".lang();
    }
GetTextCtrlClick()
virtual string InvOwner.GetTextCtrlClick (ButtonGrid b) inline virtual
Definition at line 618 of file InvOwner.cs.
    {
        return "actSplit".lang();
    }
GetTextDetail()
virtual string InvOwner.GetTextDetail (Thing t, CurrencyType currency, int num, bool sell) inline virtual
Reimplemented in InvOwnerDraglet.
Definition at line 1268 of file InvOwner.cs.
    {
        int price = this.GetPrice(t, currency, num, sell);
        string @ref = InvOwner.Trader.UseHomeResource ? InvOwner.Trader.homeResource.Name : ((currency == CurrencyType.Influence) ? "influence".lang() : EClass.sources.things.map[this.IDCurrency].GetName());
        string ref2 = (price == 0) ? "" : "invInteraction3".lang(price.ToFormat() ?? "", @ref, null, null, null);
        string text = "invInteraction1".lang(num.ToString() ?? "", ref2, (sell ? "invSell" : "invBuy").lang(), null, null);
        if (!sell && EClass.pc.GetCurrency(Currency.ToID(currency)) < price)
        {
            text = text.TagColor(FontColor.Bad, SkinManager.DarkColors);
        }
        return text;
    }
References currency, Card.GetCurrency(), EClass.pc, EClass.sources, text, SourceManager.things, and Currency.ToID().
GetTextShiftClick()
virtual string InvOwner.GetTextShiftClick (ButtonGrid b) inline virtual
Definition at line 603 of file InvOwner.cs.
    {
        return "actTransfer".lang();
    }
Grab()
void InvOwner.Grab (DragItemCard::DragInfo from) inline
Definition at line 638 of file InvOwner.cs.
    {
        bool isEquipped = from.thing.isEquipped;
        if (isEquipped)
        {
            from.invOwner.owner.Chara.body.Unequip(from.thing, true);
        }
        from.invOwner.Container.RemoveCard(from.thing);
        if (isEquipped)
        {
            from.list.Redraw();
        }
        LayerInventory.SetDirty(from.thing);
    }
References LayerInventory.SetDirty().
Referenced by OnDrag(), and OnStartDrag().
IDCostIcon()
virtual string InvOwner.IDCostIcon (Thing t) inline virtual
Definition at line 1329 of file InvOwner.cs.
    {
        return "icon_" + this.IDCurrency;
    }
Init()
void InvOwner.Init () inline
Definition at line 282 of file InvOwner.cs.
    {
        if (this.owner == null)
        {
            CardBlueprint.SetNormalRarity(false);
            this.owner = this.CreateDefaultContainer();
            this.owner.c_lockLv = 0;
            this.owner.c_IDTState = 0;
            this.Container = (this.Container ?? this.owner);
        }
        this.OnInit();
        InvOwner.forceGive = new InvOwner.ForceGiveData();
    }
References CreateDefaultContainer(), OnInit(), owner, and CardBlueprint.SetNormalRarity().
Referenced by UIInventory.AddTab(), and LayerDragGrid.SetInv().
IsFailByCurse()
virtual bool InvOwner.IsFailByCurse (Thing t) inline virtual
Reimplemented in InvOwnerEquip.
Definition at line 1342 of file InvOwner.cs.
    {
        return false;
    }
IsWeightOver()
bool InvOwner.IsWeightOver (Thing t) inline
Definition at line 253 of file InvOwner.cs.
    {
        return false;
    }
ListInteractions() [1/2]
InvOwner.ListInteraction InvOwner.ListInteractions (ButtonGrid b, bool context) inline
Definition at line 838 of file InvOwner.cs.
    {
        InvOwner.ListInteraction listInteraction = new InvOwner.ListInteraction();
        if (b == null || b.card == null || this is InvOwnerAlly)
        {
            return listInteraction;
        }
        Thing t = b.card.Thing;
        if (t == null)
        {
            return listInteraction;
        }
        listInteraction.thing = t;
        Trait trait = t.trait;
        bool flag = trait is TraitAbility;
        if (InvOwner.HasTrader)
        {
            if (InvOwner.Trader == null || this.destInvOwner == null)
            {
                return listInteraction;
            }
            if (this.CanOpenContainer(t))
            {
                listInteraction.Add("actContainer", 10, delegate()
                {
                    (t.trait as TraitContainer).TryOpen();
                }, null);
            }
            bool flag2 = !flag && !trait.CanOnlyCarry && (!this.destInvOwner.UseGuide || this.destInvOwner.ShouldShowGuide(t));
            bool flag3 = ShopTransaction.current != null && ShopTransaction.current.CanSellBack(t, -1);
            if (this.destInvOwner == InvOwner.Trader && !InvOwner.Trader.AllowSell && !flag3)
            {
                flag2 = false;
            }
            if (!this.AllowHold(t))
            {
                flag2 = false;
            }
            if (!InvOwner.Trader.AllowMoved(t))
            {
                flag2 = false;
            }
            if (flag2 && (!t.c_isImportant || !this.destInvOwner.DenyImportant))
            {
                if (!flag3 && (InvOwner.Trader.currency == CurrencyType.None || t.GetPrice(CurrencyType.Money, false, PriceType.Default, null) == 0))
                {
                    InvOwner.Transaction trans = new InvOwner.Transaction(b, t.Num, null);
                    if (trans.IsValid())
                    {
                        Action <>9__2;
                        listInteraction.Add(this.Container.isNPCProperty ? "actSteal".lang().TagColor(FontColor.Bad, SkinManager.DarkColors) : this.destInvOwner.langTransfer, 0, delegate()
{
                            if (this.Container.isNPCProperty)
{
                                Action action;
                                if ((action = <>9__2) == null)
{
                                    action = (<>9__2 = delegate()
{
                                        trans.Process(false);
                                    });
                                }
                                Dialog.TryWarnCrime(action);
                                return;
                            }
                            trans.Process(false);
                        }, null);
                    }
                }
                else
                {
                    bool isShiftDown = EInput.isShiftDown;
                    InvOwner.Transaction trans = new InvOwner.Transaction(b, 1, null);
                    listInteraction.Add(trans.GetTextDetail(), 0, delegate()
                    {
                        trans.Process(false);
                    }, null).repeatable = true;
                    if (t.Num > 1)
                    {
                        InvOwner.Transaction trans2 = new InvOwner.Transaction(b, t.Num, null);
                        listInteraction.Add(trans2.GetTextDetail(), 10, delegate()
{
                            trans2.Process(false);
                        }, null);
                        if (isShiftDown)
{
                            listInteraction.Add(listInteraction[0]);
                            listInteraction.RemoveAt(0);
                        }
                    }
                }
            }
        }
        this.ListInteractions(listInteraction, t, trait, b, context);
        if (this.AllowHold(t) && !t.isEquipped && !InvOwner.HasTrader)
        {
            InvOwner.Interaction item = listInteraction.Add((EClass.pc.held == t) ? "actPick" : "actHold", 60, delegate()
            {
                this.TryHold(t);
            }, null);
            if (t.trait.HoldAsDefaultInteraction)
            {
                listInteraction.Remove(item);
                listInteraction.Insert(0, item);
            }
            if (t.trait.CanBeHeldAsFurniture)
            {
                listInteraction.Add("actHoldTool", 70, delegate()
                {
                    if (t != EClass.pc.held)
                    {
                        if (this.TryHold(t))
{
                            HotItemHeld.disableTool = true;
                            return;
                        }
                    }
                    else
                    {
                        HotItemHeld.disableTool = true;
                    }
                }, "remove");
            }
        }
        if (context)
        {
            bool flag4 = false;
            if (this.AllowHold(t) && !this.Container.isNPCProperty)
            {
                if (t.Num > 1)
                {
                    listInteraction.Add("actSplit", 50, delegate()
                    {
                        t.ShowSplitMenu(b, (InvOwner.HasTrader && this.currency != CurrencyType.None && !this.owner.IsPC) ? new InvOwner.Transaction(b, 1, null) : null);
                    }, null);
                }
                if (this.owner.IsPC && this.AllowDrop(t))
                {
                    flag4 = true;
                    listInteraction.Add(t.c_isImportant ? "important_off" : "important_on", 299, delegate()
                    {
                        t.c_isImportant = !t.c_isImportant;
                        LayerInventory.SetDirty(t);
                        SE.ClickOk();
                    }, null);
                    if (!EClass._zone.IsRegion)
                    {
                        listInteraction.Add(flag ? "dragForget" : "actDrop", 300, delegate()
{
                            EClass.pc.DropThing(t, -1);
                        }, null);
                    }
                }
            }
            if (!flag4 && t.c_isImportant)
            {
                listInteraction.Add(t.c_isImportant ? "important_off" : "important_on", 299, delegate()
                {
                    t.c_isImportant = !t.c_isImportant;
                    LayerInventory.SetDirty(t);
                    SE.ClickOk();
                }, null);
            }
        }
        return listInteraction;
    }
References EClass._zone, InvOwner.ListInteraction.Add(), AllowHold(), AllowMoved(), AllowSell, Card.c_isImportant, Trait.CanBeHeldAsFurniture, CanOpenContainer(), ShopTransaction.CanSellBack(), ButtonGrid.card, Container, currency, ShopTransaction.current, destInvOwner, Chara.DropThing(), Card.GetPrice(), InvOwner.Transaction.GetTextDetail(), HasTrader, Chara.held, Trait.HoldAsDefaultInteraction, Thing.isEquipped, Card.isNPCProperty, Card.IsPC, Spatial.IsRegion, InvOwner.Transaction.IsValid(), langTransfer, ListInteractions(), Card.Num, owner, EClass.pc, InvOwner.Transaction.Process(), LayerInventory.SetDirty(), ShouldShowGuide(), Thing.ShowSplitMenu(), Card.Thing, Trader, Card.trait, TryHold(), and Dialog.TryWarnCrime().
Referenced by GetAutoUseLang(), and ListInteractions().
ListInteractions() [2/2]
virtual void InvOwner.ListInteractions (InvOwner::ListInteraction list, Thing t, Trait trait, ButtonGrid b, bool context) inline virtual
Reimplemented in InvOwnerAlly, InvOwnerEquip, and InvOwnerShop.
Definition at line 1029 of file InvOwner.cs.
    {
        if (this.owner.IsPC)
        {
            if (this.CanOpenContainer(t) && !list.Contains("actContainer"))
            {
                list.Add(LayerInventory.IsOpen(t) ? "close" : "actContainer", 100, delegate()
                {
                    (t.trait as TraitContainer).TryOpen();
                }, null);
            }
            if (!InvOwner.HasTrader)
            {
                CharaBody body = this.owner.Chara.body;
                BodySlot slot = body.GetSlot(t, false, EInput.isShiftDown);
                if (slot != null)
                {
                    Card tParent = t.parentCard;
                    int tInvX = t.invX;
                    int tInvY = t.invY;
                    if (tInvY != 1)
                    {
                        list.Add("invEquip", 90, delegate()
{
                            if (slot.thing != null && slot.thing.blessedState <= BlessedState.Cursed)
{
                                Msg.Say("unequipCursed", slot.thing, null, null, null);
                                SE.Play("curse3");
                                return;
                            }
                            if (EClass.pc.held == t)
{
                                EClass.pc.PickHeld(false);
                            }
                            Thing thing = slot.thing;
                            body.Equip(t, slot, true);
                            EClass.Sound.Play("equip");
                            if (thing != null)
{
                                if (tParent != null)
{
                                    tParent.AddThing(thing, true, -1, -1);
                                    thing.invX = tInvX;
                                    thing.invY = tInvY;
                                    return;
                                }
                                if (thing.parent is Card && (thing.parent as Card).things.IsOverflowing())
{
                                    thing.parent.RemoveCard(thing);
                                    EClass.pc.Pick(thing, true, true);
                                }
                            }
                        }, null);
                    }
                }
                if (trait.CanRead(EClass.pc))
                {
                    list.Add("invRead", 110, delegate()
                    {
                        t.DoAct(new AI_Read
{
                            target = t
                        });
                    }, "remove");
                }
                if (trait.CanUse(EClass.pc))
                {
                    list.Add(trait.LangUse, 120, delegate()
                    {
                        if (trait.OnUse(EClass.pc))
{
                            EClass.player.EndTurn(true);
                        }
                    }, "use");
                }
                if (trait.CanDrink(EClass.pc))
                {
                    list.Add("invDrink", 130, delegate()
                    {
                        t.DoAct(new AI_Drink
{
                            target = t
                        });
                    }, "remove");
                }
                if (trait.CanEat(EClass.pc))
                {
                    list.Add("invFood", 140, delegate()
                    {
                        t.DoAct(new AI_Eat
{
                            cook = false,
                            target = t
                        });
                    }, "remove");
                }
                if (trait.IsBlendBase)
                {
                    list.Add("invBlend", 150, delegate()
                    {
                        LayerDragGrid.Create(new InvOwnerBlend(t, null, CurrencyType.None), false);
                    }, "blend");
                }
                if (context)
                {
                    if (trait is TraitCard)
                    {
                        list.Add("invCollect", 150, delegate()
{
                            ContentCodex.Collect(t);
                        }, null);
                    }
                    if (trait.CanName)
                    {
                        Action<bool, string> <>9__9;
                        list.Add("changeName", 200, delegate()
{
                            string langDetail = "dialogChangeName";
                            string text2 = t.c_refText.IsEmpty("");
                            Action<bool, string> onClose;
                            if ((onClose = <>9__9) == null)
{
                                onClose = (<>9__9 = delegate(bool cancel, string text)
{
                                    if (!cancel)
{
                                        t.c_refText = text;
                                    }
                                });
                            }
                            Dialog.InputName(langDetail, text2, onClose, Dialog.InputType.Default);
                        }, null);
                    }
                }
            }
        }
    }
References Card.AddThing(), Card.blessedState, Chara.body, Card.c_refText, Trait.CanDrink(), Trait.CanEat(), Trait.CanName, CanOpenContainer(), Trait.CanRead(), Trait.CanUse(), Card.Chara, ContentCodex.Collect(), cook, LayerDragGrid.Create(), Thing.DoAct(), Player.EndTurn(), CharaBody.Equip(), CharaBody.GetSlot(), HasTrader, Chara.held, Dialog.InputName(), Card.invX, Card.invY, Trait.IsBlendBase, LayerInventory.IsOpen(), ThingContainer.IsOverflowing(), Card.IsPC, Trait.LangUse, Trait.OnUse(), owner, Card.parent, Card.parentCard, EClass.pc, Chara.Pick(), Chara.PickHeld(), EClass.player, ICardParent.RemoveCard(), Msg.Say(), EClass.Sound, text, BodySlot.thing, and Card.things.
OnAltClick()
virtual void InvOwner.OnAltClick (ButtonGrid button) inline virtual
Definition at line 623 of file InvOwner.cs.
    {
        EClass.pc.DropThing(button.card.Thing, -1);
    }
References ButtonGrid.card, Chara.DropThing(), EClass.pc, and Card.Thing.
Referenced by OnClick().
OnCancelDrag()
virtual bool InvOwner.OnCancelDrag (DragItemCard::DragInfo from) inline virtual
Reimplemented in InvOwnerAlly, and InvOwnerShop.
Definition at line 696 of file InvOwner.cs.
    {
        if (this.Container.isNPCProperty)
        {
            return false;
        }
        this.PutBack(from);
        return true;
    }
References Container, Card.isNPCProperty, and PutBack().
Referenced by OnDrag().
OnClick()
virtual void InvOwner.OnClick (ButtonGrid button) inline virtual
Reimplemented in InvOwnerAlly, InvOwnerDraglet, InvOwnerHotbar, and InvOwnerToolbelt.
Definition at line 300 of file InvOwner.cs.
    {
        Card card = button.card;
        Card card2 = button.invOwner.owner;
        if (card != null && EClass.ui.currentDrag == null)
        {
            bool flag = false;
            if (card.Thing.isEquipped && card.Thing.IsEquipmentOrRanged && card.Thing.IsCursed)
            {
                SE.Play("curse3");
            }
            else if (!this.AllowHold(card.Thing) && card2.isChara && !card2.IsPC && card2.IsPCFaction)
            {
                if (InvOwner.forceGive.card != card)
                {
                    InvOwner.forceGive.card = card;
                    InvOwner.forceGive.tries = 0;
                }
                else
                {
                    if (!EInput.isShiftDown)
                    {
                        InvOwner.forceGive.tries++;
                    }
                    if (InvOwner.forceGive.tries >= 2)
                    {
                        if (card.HasTag(CTAG.gift) && card.isGifted)
{
                            EClass.ui.CloseLayers();
                            card2.Say("angry", card2, null, null);
                            card2.ShowEmo(Emo.angry, 0f, true);
                            card2.Talk("noGiveRing", null, null, false);
                            card2.Chara.ModAffinity(EClass.pc, -30, true);
                            card2.Chara.InstantEat(card.Thing, true);
                            return;
                        }
                        InvOwner.forceGive.card = null;
                        bool flag2 = card.trait is TraitCurrency;
                        card.isGifted = false;
                        card.isNPCProperty = false;
                        card2.Talk(flag2 ? "forceGiveCurrency" : "forceGive", null, null, false);
                        int num = flag2 ? 3 : 1;
                        if (card.id == "money")
{
                            num += card.Num / 1000;
                        }
                        if (num >= 5)
{
                            num = 5;
                        }
                        EClass.player.ModKarma(-num);
                        EClass.pc.Pick(card.Thing, true, true);
                        return;
                    }
                }
            }
            if (this.AllowHold(card.Thing) || flag)
            {
                if (EInput.isAltDown)
                {
                    if (this.CanAltClick(button))
                    {
                        this.OnAltClick(button);
                        return;
                    }
                    SE.BeepSmall();
                    return;
                }
                else if (EInput.isCtrlDown)
                {
                    if (this.CanCtrlClick(button))
                    {
                        this.OnCtrlClick(button);
                        return;
                    }
                    SE.BeepSmall();
                    return;
                }
                else if (EInput.isShiftDown)
                {
                    if (this.CanShiftClick(button, false))
                    {
                        this.OnShiftClick(button, false);
                        return;
                    }
                    SE.BeepSmall();
                    return;
                }
                else
                {
                    if (!this.owner.IsPC)
                    {
                        new InvOwner.Transaction(button, (InvOwner.HasTrader && !InvOwner.FreeTransfer) ? 1 : card.Num, null).Process(true);
                        return;
                    }
                    if (button.card != null && this.IsFailByCurse(button.card.Thing))
                    {
                        return;
                    }
                    EClass.ui.StartDrag(new DragItemCard(button, true));
                    return;
                }
            }
            else
            {
                SE.BeepSmall();
                if (card2.isChara && !card2.IsPC)
                {
                    card2.Talk("noGive", null, null, false);
                }
            }
        }
    }
References AllowHold(), CanAltClick(), CanCtrlClick(), CanShiftClick(), ButtonGrid.card, Card.Chara, forceGive, FreeTransfer, Card.HasTag(), HasTrader, Card.id, Chara.InstantEat(), ButtonGrid.invOwner, Card.isChara, Card.IsCursed, Card.IsEquipmentOrRanged, Thing.isEquipped, Card.isGifted, Card.IsPC, Card.IsPCFaction, Chara.ModAffinity(), Player.ModKarma(), Card.Num, OnAltClick(), OnCtrlClick(), OnShiftClick(), owner, EClass.pc, Chara.Pick(), EClass.player, InvOwner.Transaction.Process(), Card.Say(), Card.ShowEmo(), Card.Talk(), Card.Thing, and EClass.ui.
Referenced by OnRightClick(), and ButtonGrid.SetCardGrid().
OnCtrlClick()
virtual void InvOwner.OnCtrlClick (ButtonGrid button) inline virtual
Definition at line 608 of file InvOwner.cs.
    {
        button.card.Thing.ShowSplitMenu(button, this.HasTransaction ? new InvOwner.Transaction(button, 1, null) : null);
    }
References ButtonGrid.card, HasTransaction, Thing.ShowSplitMenu(), and Card.Thing.
Referenced by OnClick().
OnDrag()
virtual bool InvOwner.OnDrag (DragItemCard::DragInfo from, DragItemCard::DragInfo to, bool execute, bool cancel = false) inline virtual
Definition at line 706 of file InvOwner.cs.
    {
        if (cancel)
        {
            return this.OnCancelDrag(from);
        }
        bool flag = false;
        string text = "";
        if (EClass.ui.GetLayer<LayerRegisterHotbar>(false) == null)
        {
            EClass.ui.AddLayer<LayerRegisterHotbar>().SetItem(from.thing);
        }
        LayerInventory componentOf = InputModuleEX.GetComponentOf<LayerInventory>();
        if (!EClass.ui.isPointerOverUI && !EClass._zone.IsRegion)
        {
            flag = this.AllowDropOnDrag;
            text = ((!this.AllowDropOnDrag) ? "" : ((from.thing.trait is TraitAbility) ? "dragForget" : "dragDropThing"));
            if (execute)
            {
                if (!this.AllowDropOnDrag || from.thing.c_isImportant)
                {
                    return this.OnCancelDrag(from);
                }
                EClass.pc.DropThing(from.thing, -1);
                return true;
            }
        }
        else if (!EClass.core.config.game.useGrid && componentOf)
        {
            if (to.button && to.invOwner != null && to.thing != null && to.thing.CanStackTo(from.thing))
            {
                InvOwner.Transaction transaction = new InvOwner.Transaction(from, to, from.thing.Num);
                flag = transaction.IsValid();
                text = transaction.GetTextDetail();
                if (execute)
                {
                    return transaction.Process(false);
                }
            }
            else
            {
                InvOwner.Transaction transaction2 = new InvOwner.Transaction(from, componentOf.invs[0], from.thing.Num);
                flag = transaction2.IsValid();
                text = transaction2.GetTextDetail();
                if (execute)
                {
                    return transaction2.Process(false);
                }
            }
        }
        else if (to.button && to.invOwner != null && to.button.interactable)
        {
            if (to.invOwner is InvOwnerEquip)
            {
                InvOwnerEquip invOwnerEquip = to.invOwner as InvOwnerEquip;
                Chara chara = invOwnerEquip.owner.Chara;
                BodySlot slot = invOwnerEquip.slot;
                if (execute && to.thing != null && to.thing.blessedState <= BlessedState.Cursed)
                {
                    Msg.Say("unequipCursed", to.thing, null, null, null);
                    return false;
                }
                if (from.thing.category.slot == slot.elementId)
                {
                    flag = true;
                    text = "dragEquip";
                    if (execute)
                    {
                        if (!chara.body.IsEquippable(from.thing, slot, true))
{
                            return false;
                        }
                        chara.AddCard(from.thing);
                        if (to.thing != null)
{
                            EClass.ui.nextDrag = new DragItemCard(to.button, true);
                            this.Grab(to);
                        }
                        chara.body.Equip(from.thing, invOwnerEquip.slot, true);
                        EClass.Sound.Play("equip");
                        if (EClass.game.UseGrid)
{
                            from.list.Redraw();
                        }
                        to.list.Redraw();
                        to.invOwner.OnProcess(from.thing);
                        return true;
                    }
                }
            }
            else
            {
                if (to.invOwner is InvOwnerCopyShop && !to.invOwner.owner.trait.CanCopy(from.thing))
                {
                    return false;
                }
                if (!to.invOwner.AllowTransfer)
                {
                    return false;
                }
                InvOwner.Transaction transaction3 = new InvOwner.Transaction(from, to, from.thing.Num);
                flag = transaction3.IsValid();
                text = transaction3.GetTextDetail();
                if (execute)
                {
                    return transaction3.Process(false);
                }
            }
        }
        EClass.ui.hud.SetDragText(flag ? text : "", (from.thing.Num > 1) ? (from.thing.Num.ToString() ?? "") : null);
        CursorSystem.SetCursor(flag ? null : CursorSystem.Invalid, 100);
        return false;
    }
References EClass._zone, Card.AddCard(), AllowDropOnDrag, Chara.body, Trait.CanCopy(), Card.Chara, EClass.core, Chara.DropThing(), BodySlot.elementId, CharaBody.Equip(), EClass.game, InvOwner.Transaction.GetTextDetail(), Grab(), LayerInventory.invs, CharaBody.IsEquippable(), Spatial.IsRegion, InvOwner.Transaction.IsValid(), OnCancelDrag(), owner, EClass.pc, InvOwner.Transaction.Process(), Msg.Say(), InvOwnerEquip.slot, EClass.Sound, text, Card.trait, EClass.ui, and Game.UseGrid.
OnInit()
virtual void InvOwner.OnInit () inline virtual
Reimplemented in InvOwnerDraglet.
Definition at line 296 of file InvOwner.cs.
    {
    }
Referenced by Init().
OnProcess()
virtual void InvOwner.OnProcess (Thing t) inline virtual
Reimplemented in InvOwnerDraglet, and InvOwnerHotbar.
Definition at line 820 of file InvOwner.cs.
    {
    }
OnRightClick()
virtual void InvOwner.OnRightClick (ButtonGrid button) inline virtual
Reimplemented in InvOwnerAlly, InvOwnerDraglet, and InvOwnerHotbar.
Definition at line 414 of file InvOwner.cs.
    {
        if (!this.AllowAutouse)
        {
            this.OnClick(button);
        }
        if (button.card == null)
        {
            return;
        }
        this.AutoUse(button, false);
    }
References AllowAutouse, AutoUse, ButtonGrid.card, and OnClick().
OnRightPressed()
virtual void InvOwner.OnRightPressed (ButtonGrid button) inline virtual
Reimplemented in InvOwnerAlly, and InvOwnerHotbar.
Definition at line 427 of file InvOwner.cs.
    {
        if (!EInput.rightMouse.pressedLong)
        {
            return;
        }
        float num = 1f;
        float pressedTimer = EInput.rightMouse.pressedTimer;
        if (pressedTimer > 2f)
        {
            num = 2f;
        }
        else if (pressedTimer > 4f)
        {
            num = 5f;
        }
        else if (pressedTimer > 6f)
        {
            num = 50f;
        }
        InvOwner.clickTimer -= Core.delta * num;
        if (InvOwner.clickTimer < 0f)
        {
            InvOwner.clickTimer = 0.1f;
            if (button.card != null)
            {
                this.AutoUse(button, true);
            }
        }
    }
References AutoUse, ButtonGrid.card, and clickTimer.
OnShiftClick()
virtual void InvOwner.OnShiftClick (ButtonGrid b, bool rightMouse = false) inline virtual
Definition at line 501 of file InvOwner.cs.
    {
        InvOwner shitDestOwner = this.GetShitDestOwner(b, rightMouse);
        Thing thing = b.card.Thing;
        Card container = shitDestOwner.Container;
        if (rightMouse && !this.owner.IsPC)
        {
            EClass.pc.Pick(thing, false, true);
            return;
        }
        if ((thing.parent == container || thing == container) && !thing.IsHotItem)
        {
            if (EInput.isShiftDown)
            {
                SE.BeepSmall();
            }
            return;
        }
        thing.PlaySoundDrop(false);
        if (thing.IsHotItem && thing.parent == container)
        {
            container.RemoveCard(thing);
        }
        if (container.things.CanStack(thing, -1, -1) != thing)
        {
            container.things.TryStack(thing, -1, -1);
            return;
        }
        container.AddThing(thing, true, -1, -1);
    }
References Card.AddThing(), ThingContainer.CanStack(), ButtonGrid.card, Container, GetShitDestOwner(), Card.IsHotItem, Card.IsPC, owner, Card.parent, EClass.pc, Chara.Pick(), Card.PlaySoundDrop(), Card.RemoveCard(), Card.Thing, Card.things, and ThingContainer.TryStack().
Referenced by OnClick(), and ActionMode.UpdateInput().
OnStartDrag()
void InvOwner.OnStartDrag (DragItemCard::DragInfo from) inline
Definition at line 682 of file InvOwner.cs.
    {
        from.thing.PlaySoundDrop(false);
        if (from.thing.parent != null)
        {
            this.Grab(from);
        }
        if (from.thing.IsEquipment)
        {
            WidgetEquip.dragEquip = from.thing;
            WidgetEquip.Redraw();
        }
    }
References Grab(), and WidgetEquip.Redraw().
OnWriteNote()
virtual void InvOwner.OnWriteNote (ButtonGrid button, UINote n) inline virtual
Reimplemented in InvOwnerEquip.
Definition at line 1281 of file InvOwner.cs.
    {
        Thing thing = button.card as Thing;
        if (thing == null)
        {
            return;
        }
        bool flag;
        if (InvOwner.HasTrader && InvOwner.Trader.currency != CurrencyType.None)
        {
            if (this.destInvOwner == InvOwner.Trader)
            {
                if (!InvOwner.Trader.AllowSell)
                {
                    ShopTransaction current = ShopTransaction.current;
                    flag = (current != null && current.CanSellBack(thing, -1));
                }
                else
                {
                    flag = true;
                }
            }
            else
            {
                flag = true;
            }
        }
        else
        {
            flag = false;
        }
        bool flag2 = flag;
        if (flag2 && InvOwner.Trader.UseGuide && !InvOwner.Trader.ShouldShowGuide(thing))
        {
            flag2 = false;
        }
        if (flag2)
        {
            InvOwner.Transaction transaction = new InvOwner.Transaction(button, 1, null);
            n.Space(8, 1);
            UIItem uiitem = n.AddExtra<UIItem>("costPrice");
            string id = this.IDCostIcon(thing);
            int price = transaction.GetPrice();
            uiitem.text1.SetText(Lang._currency(price, false, 14), transaction.IsValid() ? FontColor.Good : FontColor.Bad);
            uiitem.image1.sprite = (InvOwner.Trader.UseHomeResource ? InvOwner.Trader.homeResource.Sprite : SpriteSheet.Get(id));
        }
    }
References AllowSell, ShopTransaction.CanSellBack(), currency, ShopTransaction.current, InvOwner.Transaction.GetPrice(), HasTrader, InvOwner.Transaction.IsValid(), ShouldShowGuide(), Trader, and UseGuide.
Referenced by ButtonGrid.SetCardGrid().
PutBack()
Thing InvOwner.PutBack (DragItemCard::DragInfo from) inline
Definition at line 653 of file InvOwner.cs.
    {
        Thing thing = from.thing;
        if (from.invY == 1 && from.container.things.IsOccupied(from.invX, from.invY))
        {
            return EClass.pc.Pick(thing, false, true);
        }
        if (from.container.things.IsFull(thing, false, false))
        {
            return EClass.pc.Pick(thing, false, true);
        }
        thing.invY = from.invY;
        thing = from.container.AddThing(thing, true, from.invX, from.invY);
        if (from.equippedSlot != null)
        {
            from.invOwner.owner.Chara.body.Equip(thing, from.equippedSlot, true);
            from.list.Redraw();
        }
        else
        {
            thing.invX = from.invX;
        }
        if (from.invY == 1)
        {
            WidgetCurrentTool.dirty = true;
        }
        return thing;
    }
References Card.AddThing(), Chara.body, Card.Chara, CharaBody.Equip(), Card.invX, Card.invY, EClass.pc, and Chara.Pick().
Referenced by OnCancelDrag().
ShouldShowGuide()
virtual bool InvOwner.ShouldShowGuide (Thing t) inline virtual
Reimplemented in InvOwnerBlend, InvOwnerChangeMaterial, InvOwnerCopyShop, InvOwnerCraft, InvOwnerDeliver, InvOwnerDeliverBox, InvOwnerEnchant, InvOwnerGacha, InvOwnerGene, InvOwnerGive, InvOwnerIdentify, InvOwnerLighten, InvOwnerMod, InvOwnerOffering, InvOwnerReconstruction, InvOwnerRecycle, InvOwnerRefuel, and InvOwnerUncurse.
Definition at line 85 of file InvOwner.cs.
    {
        return false;
    }
Referenced by ListInteractions(), DragItemCard.OnStartDrag(), OnWriteNote(), UIDragGridIngredients.Refresh(), LayerDragGrid.TryProc(), and LayerInventory.TryShowGuide().
ShowContextMenu()
void InvOwner.ShowContextMenu (ButtonGrid button) inline
Definition at line 1241 of file InvOwner.cs.
    {
        if (!EClass.pc.HasNoGoal)
        {
            SE.Beep();
            return;
        }
        InvOwner.ListInteraction listInteraction = this.ListInteractions(button, true);
        if (listInteraction.Count == 0)
        {
            SE.BeepSmall();
            return;
        }
        UIContextMenu uicontextMenu = EClass.ui.CreateContextMenuInteraction();
        listInteraction.Sort((InvOwner.Interaction a, InvOwner.Interaction b) => a.priority - b.priority);
        foreach (InvOwner.Interaction interaction in listInteraction)
        {
            uicontextMenu.AddButton(interaction.name, interaction.action, true);
        }
        uicontextMenu.Show();
    }
References Chara.HasNoGoal, EClass.pc, and EClass.ui.
Referenced by ButtonGrid.OnMiddleClick().
TryHold()
bool InvOwner.TryHold (Thing t) inline
Definition at line 1005 of file InvOwner.cs.
    {
        if (!this.AllowHold(t) || t.isEquipped || InvOwner.HasTrader)
        {
            return false;
        }
        if (EClass.pc.held == t)
        {
            if (t.trait.CanOnlyCarry)
            {
                SE.Beep();
                return true;
            }
            EClass.pc.PickHeld(false);
        }
        else
        {
            EClass.pc.HoldCard(t, -1);
        }
        EClass.player.RefreshCurrentHotItem();
        SE.SelectHotitem();
        return true;
    }
References AllowHold(), Trait.CanOnlyCarry, HasTrader, Chara.held, Chara.HoldCard(), Thing.isEquipped, EClass.pc, Chara.PickHeld(), EClass.player, Player.RefreshCurrentHotItem(), and Card.trait.
Referenced by ListInteractions(), DragItemCard.OnDrag(), and ButtonGrid.OnMiddleClick().
Member Data Documentation
buttons
List<ButtonGrid> InvOwner.buttons = new List<ButtonGrid>()
Definition at line 1367 of file InvOwner.cs.
Referenced by LayerDragGrid.SetInv().
clickTimer
float InvOwner.clickTimer static
Definition at line 1353 of file InvOwner.cs.
Referenced by OnRightPressed().
Container
Card InvOwner.Container
Definition at line 1365 of file InvOwner.cs.
Referenced by InvOwnerRecycle._OnProcess(), AllowHold(), BuildUICurrency(), CanShiftClick(), LayerInventory.GetPCLayer(), LayerInventory.GetPlayerContainer(), GetShitDestOwner(), LayerInventory.GetTopLayer(), ListInteractions(), OnCancelDrag(), DragItemCard.OnDragSpecial(), LayerInventory.OnInit(), UIInventory.OnInit(), LayerInventory.OnKill(), OnShiftClick(), UIInventory.RefreshMenu(), UIInventory.RefreshWindow(), LayerDragGrid.SetInv(), UIInventory.ShowAdvDistribution(), UIInventory.Sort(), UIInventory.Update(), and ActionMode.UpdateInput().
currency
CurrencyType InvOwner.currency
Definition at line 1357 of file InvOwner.cs.
Referenced by BuildUICurrency(), CanShiftClick(), InvOwnerDraglet.GetTextDetail(), InvOwner(), InvOwner.Transaction.IsValid(), ListInteractions(), OnWriteNote(), ShopTransaction.Process(), ButtonRoster.Refresh(), and UIInventory.Sort().
forceGive
InvOwner.ForceGiveData InvOwner.forceGive = new InvOwner.ForceGiveData() static
Definition at line 1347 of file InvOwner.cs.
Referenced by OnClick().
homeResource
HomeResource InvOwner.homeResource
Definition at line 1361 of file InvOwner.cs.
Referenced by InvOwner.Transaction.IsValid(), and InvOwner.Transaction.Process().
includeChildren
bool InvOwner.includeChildren
Definition at line 1355 of file InvOwner.cs.
Main
InvOwner InvOwner.Main static
Definition at line 1351 of file InvOwner.cs.
owner
Card InvOwner.owner
Definition at line 1363 of file InvOwner.cs.
Referenced by InvOwnerBlend._OnProcess(), InvOwnerDeliver._OnProcess(), InvOwnerMod._OnProcess(), InvOwnerRefuel._OnProcess(), InvOwnerCopyShop.AllowMoved(), BuildUICurrency(), CanShiftClick(), LayerInventory.CloseAllyInv(), DragItemCard.DragInfo.DragInfo(), GetShitDestOwner(), Init(), InvOwner(), ListInteractions(), OnClick(), OnDrag(), DragItemCard.OnDragSpecial(), UIInventory.OnInit(), OnShiftClick(), ButtonRoster.Refresh(), LayerDragGrid.RefreshCost(), UIInventory.RefreshGrid(), UIInventory.RefreshMenu(), AI_UseCrafter.Run(), ButtonGrid.SetBodySlot(), LayerDragGrid.SetInv(), InvOwnerBlend.ShouldShowGuide(), InvOwnerCopyShop.ShouldShowGuide(), InvOwnerRefuel.ShouldShowGuide(), LayerInventory.TryShowGuide(), InvOwnerCraft.TryStartCraft(), UIInventory.Update(), ActionMode.UpdateInput(), and LayerDragGrid.Validate().
priceType
PriceType InvOwner.priceType
Definition at line 1359 of file InvOwner.cs.
Trader
InvOwner InvOwner.Trader static
Definition at line 1349 of file InvOwner.cs.
Referenced by CanShiftClick(), InvOwner.Transaction.GetPrice(), GetShitDestOwner(), InvOwner.Transaction.IsValid(), ListInteractions(), LayerInventory.OnKill(), OnWriteNote(), InvOwner.Transaction.Process(), UIInventory.RefreshGrid(), and LayerInventory.TryShowGuide().
Property Documentation
AllowAutouse
virtual bool InvOwner.AllowAutouse get
Definition at line 23 of file InvOwner.cs.
    {
        get
        {
            return true;
        }
    }
Referenced by OnRightClick().
AllowContext
virtual bool InvOwner.AllowContext get
Definition at line 31 of file InvOwner.cs.
    {
        get
        {
            return true;
        }
    }
Referenced by ButtonGrid.OnMiddleClick().
AllowDropOnDrag
virtual bool InvOwner.AllowDropOnDrag get
Definition at line 98 of file InvOwner.cs.
    {
        get
        {
            return true;
        }
    }
Referenced by OnDrag().
AllowSell
virtual bool InvOwner.AllowSell get
Definition at line 39 of file InvOwner.cs.
    {
        get
        {
            return this.currency == CurrencyType.None || this.owner.trait.AllowSell;
        }
    }
Referenced by InvOwner.Transaction.IsValid(), ListInteractions(), and OnWriteNote().
AllowTransfer
virtual bool InvOwner.AllowTransfer get
Definition at line 90 of file InvOwner.cs.
    {
        get
        {
            return this.Container.isChara || !this.Container.isNPCProperty;
        }
    }
AlwaysShowTooltip
virtual bool InvOwner.AlwaysShowTooltip get
Definition at line 69 of file InvOwner.cs.
    {
        get
        {
            return false;
        }
    }
Referenced by ButtonGrid.SetCard().
Chara
Chara InvOwner.Chara get
Definition at line 205 of file InvOwner.cs.
    {
        get
        {
            return this.owner as Chara;
        }
    }
Referenced by UIInventory.OnInit().
ContainerType
ContainerType InvOwner.ContainerType get
Definition at line 213 of file InvOwner.cs.
    {
        get
        {
            return this.Container.trait.ContainerType;
        }
    }
CopyOnTransfer
virtual bool InvOwner.CopyOnTransfer get
Definition at line 140 of file InvOwner.cs.
    {
        get
        {
            return false;
        }
    }
DenyImportant
virtual bool InvOwner.DenyImportant get
Definition at line 245 of file InvOwner.cs.
    {
        get
        {
            return true;
        }
    }
destInvOwner
InvOwner InvOwner.destInvOwner get
Definition at line 258 of file InvOwner.cs.
    {
        get
        {
            if (!this.owner.IsPC)
            {
                return InvOwner.Main;
            }
            return InvOwner.Trader;
        }
    }
Referenced by ListInteractions().
destInvY
virtual int InvOwner.destInvY get
Definition at line 119 of file InvOwner.cs.
    {
        get
        {
            return 0;
        }
    }
Referenced by DragItemCard.DragInfo.DragInfo().
FreeTransfer
bool InvOwner.FreeTransfer static get
Definition at line 15 of file InvOwner.cs.
    {
        get
        {
            return !InvOwner.HasTrader || InvOwner.Trader.currency == CurrencyType.None;
        }
    }
Referenced by AllowHold(), and OnClick().
HasTrader
bool InvOwner.HasTrader static get
Definition at line 7 of file InvOwner.cs.
    {
        get
        {
            return InvOwner.Trader != null;
        }
    }
Referenced by CanShiftClick(), InvOwner.Transaction.IsValid(), ListInteractions(), OnClick(), OnWriteNote(), UI.ToggleInventory(), and TryHold().
HasTransaction
virtual bool InvOwner.HasTransaction get
Definition at line 132 of file InvOwner.cs.
    {
        get
        {
            return false;
        }
    }
Referenced by OnCtrlClick().
IDCurrency
string InvOwner.IDCurrency get
Definition at line 1334 of file InvOwner.cs.
    {
        get
        {
            return Currency.ToID(InvOwner.Trader.currency);
        }
    }
Referenced by LayerDragGrid.RefreshCost().
InvertSell
virtual bool InvOwner.InvertSell get
Definition at line 221 of file InvOwner.cs.
    {
        get
        {
            return false;
        }
    }
IsMagicChest
bool InvOwner.IsMagicChest get
Definition at line 185 of file InvOwner.cs.
    {
        get
        {
            return this.Container.trait is TraitMagicChest;
        }
    }
langTransfer
virtual string InvOwner.langTransfer get
Definition at line 111 of file InvOwner.cs.
    {
        get
        {
            return "actTransfer";
        }
    }
Referenced by InvOwnerAlly.GetAutoUseLang(), ListInteractions(), and LayerDragGrid.SetInv().
numDragGrid
virtual int InvOwner.numDragGrid get
Definition at line 229 of file InvOwner.cs.
    {
        get
        {
            return 1;
        }
    }
Referenced by LayerDragGrid.ClearButtons(), LayerDragGrid.IsAllGridSet(), LayerDragGrid.RefreshCurrentGrid(), and LayerDragGrid.SetInv().
ShowNew
virtual bool InvOwner.ShowNew get
Definition at line 237 of file InvOwner.cs.
    {
        get
        {
            return this.owner.IsPC;
        }
    }
Referenced by ButtonGrid.SetCard().
SingleTarget
virtual bool InvOwner.SingleTarget get
Definition at line 148 of file InvOwner.cs.
    {
        get
        {
            return false;
        }
    }
Things
List<Thing> InvOwner.Things get
Definition at line 193 of file InvOwner.cs.
    {
        get
        {
            if (!this.Container.things.HasGrid)
            {
                return this.Container.things;
            }
            return this.Container.things.grid;
        }
    }
UseGuide
virtual bool InvOwner.UseGuide get
Definition at line 77 of file InvOwner.cs.
    {
        get
        {
            return false;
        }
    }
Referenced by LayerInventory.OnKill(), OnWriteNote(), and LayerInventory.TryShowGuide().
UseHomeResource
bool InvOwner.UseHomeResource get
Definition at line 177 of file InvOwner.cs.
    {
        get
        {
            return this.homeResource != null;
        }
    }
Referenced by InvOwner.Transaction.IsValid(), and InvOwner.Transaction.Process().
The documentation for this class was generated from the following file:
Elin/InvOwner.cs