Elin Decompiled Documentation: AI_UseCrafter Class Reference
AI_UseCrafter Class Reference
Public Member Functions
override bool CanManualCancel ()
override void OnStart ()
override void OnSuccess ()
override void OnCancel ()
void OnEnd ()
override IEnumerable< Status > Run ()
Public Member Functions inherited from AIAct
override string ToString ()
override MultiSprite GetStateIcon ()
virtual Point GetDestination ()
AIProgress GetProgress ()
string GetCurrentActionText ()
override bool IsToolValid ()
virtual void OnStart ()
void SetOwner (Chara c)
virtual void OnSetOwner ()
void SetChild (AIAct seq, Func< Status > _onChildFail=null)
void Start ()
override bool Perform ()
Status Restart ()
Status Success (Action action=null)
virtual void OnSuccess ()
bool TryCancel (Card c)
virtual Status Cancel ()
virtual void OnCancel ()
virtual void OnCancelOrSuccess ()
virtual bool CanManualCancel ()
Status KeepRunning ()
void Reset ()
virtual void OnReset ()
Status Tick ()
virtual IEnumerable< Status > Run ()
Status TickChild ()
Status Do (AIAct _seq, Func< Status > _onChildFail=null)
Status DoGotoInteraction (Point pos, Func< Status > _onChildFail=null)
Status DoGoto (Point pos, int dist=0, bool ignoreConnection=false, Func< Status > _onChildFail=null)
Status DoGoto (Card card, Func< Status > _onChildFail=null)
Status DoGoto (Card card, int dist, Func< Status > _onChildFail=null)
Status DoGotoSpot (Card card, Func< Status > _onChildFail=null)
Status DoGoto< T > (Func< Status > _onChildFail=null)
Status DoGotoSpot< T > (Func< Status > _onChildFail=null, bool ignoreAccessType=false)
Status DoGrab (Card card, int num=-1, bool pickHeld=false, Func< Status > _onChildFail=null)
Status DoGrab< T > ()
Status DoProgress ()
Status DoIdle (int repeat=3)
Status DoWait (int count=1)
virtual AIProgress CreateProgress ()
virtual void OnCreateProgress (Progress_Custom p)
virtual bool CanProgress ()
virtual void OnBeforeProgress ()
virtual void OnProgress ()
virtual void OnProgressComplete ()
void SimulateZone (int days)
virtual void OnSimulateZone (int days)
virtual void OnSimulatePosition ()
Public Member Functions inherited from Act
virtual CursorInfo GetCursorIcon (Card c)
virtual MultiSprite GetStateIcon ()
override Sprite GetSprite ()
virtual bool ShowMouseHint (Card c)
virtual bool IsValidTC (Card c)
virtual string GetHintText (string str="")
virtual string GetText (string str="")
virtual string GetTextSmall (Card c)
virtual Color GetActPlanColor ()
virtual bool Perform ()
virtual bool CanPerform ()
bool Perform (Chara _cc, Card _tc=null, Point _tp=null)
bool CanPerform (Chara _cc, Card _tc=null, Point _tp=null)
virtual bool IsToolValid ()
new void SetImage (Image image)
virtual void OnMarkMapHighlights ()
virtual bool ShouldMapHighlight (Point p)
virtual CursorInfo GetCursorIcon (Card c)
virtual MultiSprite GetStateIcon ()
override Sprite GetSprite ()
virtual bool ShowMouseHint (Card c)
virtual bool IsValidTC (Card c)
virtual string GetHintText (string str="")
virtual string GetText (string str="")
virtual string GetTextSmall (Card c)
virtual Color GetActPlanColor ()
virtual bool Perform ()
virtual bool CanPerform ()
bool Perform (Chara _cc, Card _tc=null, Point _tp=null)
bool CanPerform (Chara _cc, Card _tc=null, Point _tp=null)
virtual bool IsToolValid ()
new void SetImage (Image image)
virtual void OnMarkMapHighlights ()
virtual bool ShouldMapHighlight (Point p)
Public Member Functions inherited from Element
virtual SourceElement.Row GetSource ()
virtual int GetSourcePotential (int v)
virtual Sprite GetSprite ()
int GetMaterialSourceValue (Thing t, int v)
virtual int GetSourceValue (int v, int lv, SourceValueType type)
virtual Sprite GetIcon (string suffix="")
int SortVal (bool charaSheet=false)
virtual bool CanLink (ElementContainer owner)
bool HasTag (string tag)
void SetImage (Image i)
virtual string GetDetail ()
bool IsFactionElement (Chara c)
Element GetParent (Card c)
void WriteNote (UINote n, ElementContainer owner=null, Action< UINote > onWriteNote=null)
void WriteNoteWithRef (UINote n, ElementContainer owner, Action< UINote > onWriteNote, Element refEle)
void _WriteNote (UINote n, Chara c, Act act)
void _WriteNote (UINote n, ElementContainer owner, Action< UINote > onWriteNote, bool isRef, bool addHeader=true)
virtual void OnWriteNote (UINote n, ElementContainer owner)
virtual void OnChangeValue ()
void CheckLevelBonus (ElementContainer owner, UINote n=null)
int GetSortVal (UIList.SortMode m)
virtual Act.Cost GetCost (Chara c)
virtual int GetPower (Card c)
virtual void SetTextValue (UIText text)
virtual SourceElement.Row GetSource ()
virtual int GetSourcePotential (int v)
virtual Sprite GetSprite ()
int GetMaterialSourceValue (Thing t, int v)
virtual int GetSourceValue (int v, int lv, SourceValueType type)
virtual Sprite GetIcon (string suffix="")
int SortVal (bool charaSheet=false)
virtual bool CanLink (ElementContainer owner)
bool HasTag (string tag)
void SetImage (Image i)
virtual string GetDetail ()
bool IsFactionElement (Chara c)
Element GetParent (Card c)
void WriteNote (UINote n, ElementContainer owner=null, Action< UINote > onWriteNote=null)
void WriteNoteWithRef (UINote n, ElementContainer owner, Action< UINote > onWriteNote, Element refEle)
void _WriteNote (UINote n, Chara c, Act act)
void _WriteNote (UINote n, ElementContainer owner, Action< UINote > onWriteNote, bool isRef, bool addHeader=true)
virtual void OnWriteNote (UINote n, ElementContainer owner)
virtual void OnChangeValue ()
void CheckLevelBonus (ElementContainer owner, UINote n=null)
int GetSortVal (UIList.SortMode m)
virtual Act.Cost GetCost (Chara c)
virtual int GetPower (Card c)
virtual void SetTextValue (UIText text)
Public Attributes
LayerBaseCraft layer
TraitCrafter crafter
Recipe recipe
int num = 1
List< Thing > ings = new List<Thing>()
Public Attributes inherited from AIAct
new Chara owner
Status status
IEnumerator< Status > Enumerator
AIAct child
AIAct parent
byte restartCount
Func< Status > onChildFail
Func< bool > isFail
Public Attributes inherited from Element
SourceElement.Row _source
int id
int vBase
int vExp
int vPotential
int vTempPotential
int vLink
int vSource
int vSourcePotential
ElementContainer owner
Properties
override int LeftHand [get]
override int RightHand [get]
Properties inherited from AIAct
virtual bool IsRunning [get]
bool IsChildRunning [get]
bool IsMoveAI [get]
virtual int MaxRestart [get]
virtual new string Name [get]
virtual MultiSprite stateIcon [get]
virtual Sprite actionIcon [get]
virtual bool IsNoGoal [get]
virtual bool IsAutoTurn [get]
virtual bool IsIdle [get]
virtual bool PushChara [get]
virtual int MaxProgress [get]
virtual bool ShowProgress [get]
virtual bool UseTurbo [get]
virtual int CurrentProgress [get]
virtual bool ShowCursor [get]
virtual bool CancelWhenDamaged [get]
virtual bool CancelWhenMoved [get]
virtual bool InformCancel [get]
virtual Thing RenderThing [get]
AIAct Current [get]
override bool IsAct [get]
override bool ShowPotential [get]
override bool UsePotential [get]
override bool ShowRelativeAttribute [get]
virtual bool HasProgress [get]
Properties inherited from Act
override bool ShowPotential [get]
override bool UsePotential [get]
override bool ShowRelativeAttribute [get]
virtual CursorInfo CursorIcon [get]
virtual string ID [get]
virtual bool IsAct [get]
virtual bool WillEndTurn [get]
virtual bool CloseLayers [get]
virtual int LeftHand [get]
virtual int RightHand [get]
virtual int ElementPowerMod [get]
virtual bool ShowMapHighlight [get]
virtual bool ShowMapHighlightBlock [get]
virtual bool PickHeldOnStart [get]
virtual bool DropHeldOnStart [get]
virtual bool CanPressRepeat [get]
virtual bool CanAutofire [get]
virtual bool ResetAxis [get]
virtual bool RequireTool [get]
virtual bool IsHostileAct [get]
virtual bool HideRightInfo [get]
virtual bool HaveLongPressAction [get]
virtual float Radius [get]
virtual int PerformDistance [get]
virtual int MaxRadius [get]
virtual TargetType TargetType [get]
virtual bool LocalAct [get]
virtual bool CanRapidFire [get]
virtual float RapidDelay [get]
virtual bool ShowAuto [get]
virtual bool IsCrime [get]
Properties inherited from Element
SourceElement.Row source [get]
virtual int DisplayValue [get]
virtual int MinValue [get]
int Value [get]
int ValueWithoutLink [get]
virtual int MinPotential [get]
int Potential [get]
virtual bool CanGainExp [get]
bool IsFlag [get]
virtual string Name [get]
virtual string FullName [get]
virtual int ExpToNext [get]
virtual bool UseExpMod [get]
virtual int CostTrain [get]
virtual int CostLearn [get]
virtual bool ShowXP [get]
virtual bool ShowMsgOnValueChanged [get]
virtual bool ShowValue [get]
virtual bool ShowPotential [get]
virtual bool UsePotential [get]
virtual bool PotentialAsStock [get]
virtual bool ShowRelativeAttribute [get]
virtual bool ShowBonuses [get]
virtual string ShortName [get]
bool IsGlobalElement [get]
bool IsFactionWideElement [get]
bool IsPartyWideElement [get]
virtual bool ShowEncNumber [get]
bool IsTrait [get]
bool IsFoodTrait [get]
bool IsFoodTraitMain [get]
bool IsMainAttribute [get]
Act act [get]
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Additional Inherited Members
Public Types inherited from AIAct
enum Status { Running , Fail , Success }
Public Types inherited from Act
enum CostType {
None , MP , SP , None ,
MP , SP
}
enum CostType {
None , MP , SP , None ,
MP , SP
}
Static Public Member Functions inherited from Act
static void SetReference (Chara _cc, Card _tc=null, Point _tp=null)
static void SetTool (Thing t)
static void SetReference (Chara _cc, Card _tc=null, Point _tp=null)
static void SetTool (Thing t)
Static Public Member Functions inherited from Element
static string GetName (string alias)
static SourceElement.Row Get (int id)
static Dictionary< int, int > GetElementMap (int[] list)
static Dictionary< int, int > GetElementMap (int[] list, Dictionary< int, int > map)
static SourceElement.Row GetRandomElement (int lv=1)
static Element Create (int id, int v=0)
static Element Create (string id, int v=1)
static int GetId (string alias)
static int GetResistLv (int v)
static int GetResistDamage (int dmg, int v)
static string GetName (string alias)
static SourceElement.Row Get (int id)
static Dictionary< int, int > GetElementMap (int[] list)
static Dictionary< int, int > GetElementMap (int[] list, Dictionary< int, int > map)
static SourceElement.Row GetRandomElement (int lv=1)
static Element Create (int id, int v=0)
static Element Create (string id, int v=1)
static int GetId (string alias)
static int GetResistLv (int v)
static int GetResistDamage (int dmg, int v)
Static Public Member Functions inherited from EClass
static int rnd (int a)
static int curve (int a, int start, int step, int rate=75)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Static Public Attributes inherited from Act
static Chara CC
static Card TC
static Point TP = new Point()
static Thing TOOL
static int powerMod = 100
static bool forcePt
Static Public Attributes inherited from Element
const int Div = 5
static Element Void = new Element()
static int[] List_MainAttributes
static int[] List_MainAttributesMajor
static int[] List_Body
static int[] List_Mind
static List< SourceElement.Row > ListElements = new List<SourceElement.Row>()
static List< SourceElement.Row > ListAttackElements = new List<SourceElement.Row>()
Static Public Attributes inherited from EClass
static Core core
Static Package Functions inherited from Element
static string< _WriteNote > g__Calc (ref Element.<>c__DisplayClass103_0 A_0)
Detailed Description
Definition at line 3 of file AI_UseCrafter.cs.
Member Function Documentation
CanManualCancel()
override bool AI_UseCrafter.CanManualCancel () inline virtual
Reimplemented from AIAct.
Definition at line 19 of file AI_UseCrafter.cs.
    {
        if ((bool)layer)
        {
            return layer.CanCancelAI;
        }
        return false;
    }
References LayerBaseCraft.CanCancelAI, and layer.
OnCancel()
override void AI_UseCrafter.OnCancel () inline virtual
Reimplemented from AIAct.
Definition at line 41 of file AI_UseCrafter.cs.
    {
        OnEnd();
        if ((bool)layer)
        {
            layer.Close();
        }
    }
References layer, and OnEnd().
OnEnd()
void AI_UseCrafter.OnEnd () inline
Definition at line 50 of file AI_UseCrafter.cs.
    {
        foreach (Thing ing in ings)
        {
            if (ing != null && ing.ExistsOnMap)
            {
                ing.isHidden = false;
                EClass.pc.Pick(ing);
            }
        }
        if (crafter.AutoTurnOff && crafter.owner.isOn)
        {
            crafter.Toggle(on: false);
        }
        if (!crafter.idSoundBG.IsEmpty())
        {
            EClass.Sound.Stop(crafter.idSoundBG);
        }
        if ((bool)layer)
        {
            layer.OnEndCraft();
        }
    }
References TraitCrafter.AutoTurnOff, crafter, Card.ExistsOnMap, TraitCrafter.idSoundBG, ings, Card.isOn, layer, LayerBaseCraft.OnEndCraft(), Trait.owner, EClass.pc, Chara.Pick(), EClass.Sound, and Trait.Toggle().
Referenced by OnCancel(), and OnSuccess().
OnStart()
override void AI_UseCrafter.OnStart () inline virtual
Reimplemented from AIAct.
Definition at line 28 of file AI_UseCrafter.cs.
    {
        if (crafter.Icon != 0)
        {
            owner.ShowEmo(crafter.Icon);
        }
    }
References crafter, TraitCrafter.Icon, AIAct.owner, and Card.ShowEmo().
OnSuccess()
override void AI_UseCrafter.OnSuccess () inline virtual
Reimplemented from AIAct.
Definition at line 36 of file AI_UseCrafter.cs.
    {
        OnEnd();
    }
References OnEnd().
Run()
override IEnumerable< Status > AI_UseCrafter.Run () inline virtual
Reimplemented from AIAct.
Definition at line 74 of file AI_UseCrafter.cs.
    {
        do
        {
            if (crafter.owner.isDestroyed || !layer)
            {
                yield return Success();
            }
            if (!crafter.idSoundBG.IsEmpty())
            {
                SE.Play(crafter.idSoundBG);
            }
            List<Thing> targets = layer.GetTargets();
            BlessedState blessed = BlessedState.Normal;
            for (int j = 0; j < targets.Count; j++)
            {
                Thing t2 = targets[j];
                if (!IsIngValid(t2, j))
                {
                    if (j == 0)
                    {
                        layer.ClearButtons();
                    }
                    else
                    {
                        layer.RefreshCurrentGrid();
                    }
                    yield return Success();
                }
            }
            if (!crafter.IsFuelEnough(num, targets))
            {
                Msg.Say("notEnoughFuel");
                layer.RefreshCurrentGrid();
                yield return Success();
            }
            ings = new List<Thing>();
            for (int k = 0; k < targets.Count; k++)
            {
                Thing thing = targets[k].Split(layer.GetReqIngredient(k));
                ings.Add(thing);
                if (thing.blessedState <= BlessedState.Cursed && blessed > thing.blessedState)
                {
                    blessed = thing.blessedState;
                }
                if (thing.blessedState > BlessedState.Normal && blessed == BlessedState.Normal)
                {
                    blessed = thing.blessedState;
                }
                if (crafter.IsConsumeIng)
                {
                    Card card = EClass._zone.AddCard(thing, crafter.owner.ExistsOnMap ? crafter.owner.pos : owner.pos);
                    card.altitude = ((!crafter.owner.ExistsOnMap) ? 1 : 0);
                    if (crafter.animeType == TraitCrafter.AnimeType.Microwave)
                    {
                        card.isHidden = true;
                    }
                }
            }
            if ((bool)LayerDragGrid.Instance)
            {
                LayerDragGrid.Instance.Redraw();
            }
            bool requireOn = crafter.IsRequireFuel || crafter.ToggleType != ToggleType.None;
            if (requireOn && !crafter.owner.isOn)
            {
                crafter.Toggle(on: true);
            }
            int costSP = crafter.GetCostSp(this);
            int duration = crafter.GetDuration(this, costSP);
            Progress_Custom progress = new Progress_Custom
            {
                canProgress = delegate
                {
                    if (requireOn && !crafter.owner.isOn)
                    {
                        return false;
                    }
                    foreach (Thing ing in ings)
                    {
                        if (ing.isDestroyed || (crafter.IsConsumeIng && !ing.ExistsOnMap))
{
                            return false;
                        }
                    }
                    if ((bool)LayerDragGrid.Instance)
                    {
                        InvOwnerDraglet invOwnerDraglet = LayerDragGrid.Instance.owner;
                        for (int l = 0; l < invOwnerDraglet.numDragGrid; l++)
{
                            if (invOwnerDraglet.buttons[l].Card == null)
{
                                return false;
                            }
                        }
                        if (invOwnerDraglet.numDragGrid == 2 && ings[0] == ings[1] && ings[0].Num == 1)
{
                            return false;
                        }
                    }
                    return !crafter.owner.isDestroyed;
                },
                onProgress = delegate
                {
                    if (crafter.owner.ExistsOnMap && !owner.pos.Equals(crafter.owner.pos))
                    {
                        owner.LookAt(crafter.owner);
                    }
                    owner.PlaySound(crafter.idSoundProgress);
                    if (crafter.owner.ExistsOnMap)
                    {
                        TraitCrafter.AnimeType animeType = crafter.animeType;
                        if ((uint)(animeType - 1) <= 1u)
{
                            crafter.owner.renderer.PlayAnime(crafter.IdAnimeProgress);
                        }
                    }
                    foreach (Thing ing2 in ings)
                    {
                        ing2.renderer.PlayAnime(crafter.IdAnimeProgress);
                    }
                },
                onProgressComplete = delegate
                {
                    if (crafter.StopSoundProgress)
                    {
                        EClass.Sound.Stop(crafter.idSoundProgress);
                    }
                    owner.PlaySound(crafter.idSoundComplete);
                    Element orCreateElement = owner.elements.GetOrCreateElement(crafter.IDReqEle(recipe?.source ?? null));
                    if (recipe != null)
                    {
                        for (int m = 0; m < this.num; m++)
{
                            recipe.Craft(blessed, m == 0, ings, crafter);
                        }
                        EClass.Sound.Play("craft");
                        Point from = (crafter.owner.ExistsOnMap ? crafter.owner.pos : owner.pos);
                        Effect.Get("smoke").Play(from);
                        Effect.Get("mine").Play(from).SetParticleColor(recipe.GetColorMaterial().GetColor())
                            .Emit(10 + EClass.rnd(10));
                        owner.renderer.PlayAnime(AnimeID.JumpSmall);
                    }
                    else
                    {
                        Thing thing2 = crafter.Craft(this);
                        if (thing2 != null)
{
                            if (thing2.category.ignoreBless == 0)
{
                                thing2.SetBlessedState(blessed);
                            }
                            thing2.PlaySoundDrop(spatial: false);
                            EClass._zone.AddCard(thing2, EClass.pc.pos);
                            thing2.Identify(show: false);
                            owner.Pick(thing2);
                        }
                    }
                    for (int n = 0; n < ings.Count; n++)
                    {
                        if (crafter.ShouldConsumeIng(crafter.GetSource(this), n))
{
                            ings[n].Destroy();
                        }
                    }
                    foreach (Thing ing3 in ings)
                    {
                        if (ing3.ExistsOnMap)
{
                            owner.Pick(ing3);
                        }
                    }
                    if (crafter.IsRequireFuel)
                    {
                        crafter.owner.ModCharge(-crafter.FuelCost * this.num);
                        if (crafter.owner.c_charges <= 0)
{
                            crafter.owner.c_charges = 0;
                            crafter.Toggle(on: false);
                        }
                    }
                    for (int num = 0; num < this.num; num++)
                    {
                        owner.RemoveCondition<ConInvulnerable>();
                        owner.elements.ModExp(orCreateElement.id, costSP * 12 * (100 + duration * 2) / 100);
                        owner.stamina.Mod(-costSP);
                        if (owner == null || owner.isDead)
{
                            break;
                        }
                    }
                    Rand.SetSeed();
                    if (crafter is TraitCookerMicrowave && recipe.id == "onsentamago" && EClass.rnd(3) != 0)
                    {
                        int power = EClass.curve((200 + ings[0].Quality * 5) * (100 + EClass.pc.Evalue(287) * 10) / 100, 400, 100);
                        ActEffect.ProcAt(EffectId.Explosive, power, BlessedState.Normal, crafter.owner.ExistsOnMap ? crafter.owner : EClass.pc, EClass.pc, EClass.pc.pos, isNeg: true, new ActRef
{
                            aliasEle = "eleImpact"
                        });
                    }
                }
            }.SetDuration(duration, 5);
            owner.SetTempHand(-1, -1);
            if (EClass.debug.godCraft)
            {
                progress.SetDuration(1, 1);
            }
            yield return Do(progress);
            if (progress.status == Status.Fail)
            {
                yield return Cancel();
            }
            if (crafter.CloseOnComplete)
            {
                yield return Cancel();
            }
            if (!crafter.IsConsumeIng)
            {
                layer.ClearButtons();
                break;
            }
        }
        while ((bool)layer && layer.RepeatAI);
        bool IsIngValid(Thing t, int i)
        {
            if (t == null || t.isDestroyed)
            {
                return false;
            }
            Card rootCard = t.GetRootCard();
            if (rootCard != null && rootCard.isChara && !rootCard.IsPC)
            {
                return false;
            }
            if (!crafter.IsFactory && !crafter.IsCraftIngredient(t, i))
            {
                return false;
            }
            return true;
        }
    }
References EClass._zone, ActPlan.List.Add(), Zone.AddCard(), TraitCrafter.animeType, Card.blessedState, InvOwner.buttons, Card.c_charges, AIAct.Cancel(), Card.category, LayerBaseCraft.ClearButtons(), TraitCrafter.CloseOnComplete, TraitCrafter.Craft(), Recipe.Craft(), crafter, EClass.curve(), EClass.debug, AIAct.Do(), Card.elements, Point.Equals(), Card.Evalue(), Card.ExistsOnMap, Trait.FuelCost, Effect.Get(), Recipe.GetColorMaterial(), TraitCrafter.GetCostSp(), TraitCrafter.GetDuration(), ElementContainer.GetOrCreateElement(), LayerBaseCraft.GetReqIngredient(), TraitCrafter.GetSource(), LayerBaseCraft.GetTargets(), CoreDebug.godCraft, Recipe.id, TraitCrafter.IdAnimeProgress, Thing.Identify(), TraitCrafter.IDReqEle(), TraitCrafter.idSoundBG, TraitCrafter.idSoundComplete, TraitCrafter.idSoundProgress, ings, LayerDragGrid.Instance, TraitCrafter.IsConsumeIng, Chara.isDead, Card.isDestroyed, Trait.IsFuelEnough(), Card.isOn, Trait.IsRequireFuel, layer, Chara.LookAt(), Stats.Mod(), Card.ModCharge(), ElementContainer.ModExp(), num, InvOwner.numDragGrid, AIAct.owner, LayerDragGrid.owner, Trait.owner, EClass.pc, Chara.Pick(), Effect.Play(), CardRenderer.PlayAnime(), Card.PlaySound(), Card.PlaySoundDrop(), Card.pos, ActEffect.ProcAt(), recipe, LayerDragGrid.Redraw(), LayerBaseCraft.RefreshCurrentGrid(), Card.renderer, EClass.rnd(), Msg.Say(), Card.SetBlessedState(), Chara.SetTempHand(), TraitCrafter.ShouldConsumeIng(), EClass.Sound, Recipe.source, Card.Split(), Chara.stamina, TraitCrafter.StopSoundProgress, AIAct.Success, and Trait.Toggle().
Member Data Documentation
crafter
TraitCrafter AI_UseCrafter.crafter
Definition at line 7 of file AI_UseCrafter.cs.
Referenced by OnEnd(), OnStart(), and Run().
ings
List<Thing> AI_UseCrafter.ings = new List<Thing>()
Definition at line 13 of file AI_UseCrafter.cs.
Referenced by TraitCrafter.Craft(), TraitCrafter.GetSource(), OnEnd(), and Run().
layer
LayerBaseCraft AI_UseCrafter.layer
Definition at line 5 of file AI_UseCrafter.cs.
Referenced by CanManualCancel(), OnCancel(), OnEnd(), and Run().
num
int AI_UseCrafter.num = 1
Definition at line 11 of file AI_UseCrafter.cs.
Referenced by Run().
recipe
Recipe AI_UseCrafter.recipe
Definition at line 9 of file AI_UseCrafter.cs.
Referenced by TraitCrafter.GetDuration(), and Run().
Property Documentation
LeftHand
override int AI_UseCrafter.LeftHand get
Definition at line 15 of file AI_UseCrafter.cs.
RightHand
override int AI_UseCrafter.RightHand get
Definition at line 17 of file AI_UseCrafter.cs.
The documentation for this class was generated from the following file:
Elin/AI_UseCrafter.cs