Elin Decompiled Documentation: WidgetEquip Class Reference
WidgetEquip Class Reference
Classes
class Extra
Public Member Functions
override object CreateExtra ()
override void OnActivate ()
void Rebuild ()
void CheckDirty ()
void _Redraw ()
void RefreshEquipment (UIList list, bool etc=false)
override bool CanShowContextMenu ()
override void OnSetContextMenu (UIContextMenu m)
Public Member Functions inherited from Widget
void Test ()
bool IsInRightMode ()
void Activate ()
void RefreshOrder ()
virtual void OnActivate ()
virtual object CreateExtra ()
void Deactivate ()
virtual void OnDeactivate ()
void Close ()
void Reactivate ()
virtual void OnManagerActivate ()
virtual void OnManagerDeactivate ()
void SetAnchor (RectPosition p)
void SetPivot (RectPosition p)
virtual void OnChangePivot ()
void UpdateConfig ()
virtual void OnUpdateConfig ()
void ClampToScreen ()
virtual void OnChangeResolution ()
void OnChangePosition ()
virtual void OnChangeActionMode ()
virtual void OnFlip ()
bool IsAlignTop ()
Layer AddLayer (Layer l, Transform trans)
void RefreshTipPivotPosition ()
SkinSet GetSkin ()
SkinConfig GetSkinConfig ()
void SetSkin (int id, int v=0)
void TestSkin ()
virtual void ApplySkin ()
virtual void OnApplySkin ()
void InstantiateDeco (SkinDeco deco)
void AddDeco (SkinDeco deco)
void RemoveDeco (SkinDeco deco)
virtual bool CanShowContextMenu ()
void ShowContextMenu ()
void SetBaseContextMenu (UIContextMenu m)
virtual void OnSetContextMenu (UIContextMenu m)
void SetGridContextMenu (UIContextMenu m)
void SoundActivate ()
Static Public Member Functions
static void SetDirty ()
static void Redraw ()
Static Public Member Functions inherited from EMono
static int rnd (int a)
Public Attributes
UIList listMain
UIList listEtc
Chara chara
RectTransform transLayer
GridLayoutGroup grid
Public Attributes inherited from Widget
Image imageBG
SoundData soundActivate
UIDragPanel dragPanel
RectTransform tipPivotLeft
RectTransform tipPivotRight
Static Public Attributes
static WidgetEquip Instance
static bool dirty
static Thing dragEquip
Static Public Attributes inherited from EMono
static Core core
Properties
Extra extra [get]
Properties inherited from Widget
string ID [get]
Config config [get]
SkinRoot skinRoot [get]
bool IsSealed [get]
virtual bool ShowStyleMenu [get]
virtual bool AlwaysTop [get]
virtual bool IsStaticPosition [get]
virtual bool AlwaysBottom [get]
virtual Type SetSiblingAfter [get]
virtual bool ShowInBuildMode [get]
virtual bool RightClickToClose [get]
virtual bool AllowRightClickToClose [get]
Properties inherited from EMono
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SoundManager Sound [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static CoreDebug debug [get]
Additional Inherited Members
Public Types inherited from Widget
enum WidgetType { Default , ZoomMenu }
enum State { Active , Inactive }
Protected Member Functions inherited from Widget
void ClampToScreenEnsured (Component c, Vector2 anchoredPos)
void ClampToScreen (RectTransform rect, float margin=10f)
Protected Attributes inherited from Widget
bool flip
Detailed Description
Definition at line 4 of file WidgetEquip.cs.
Member Function Documentation
_Redraw()
void WidgetEquip._Redraw () inline
Definition at line 77 of file WidgetEquip.cs.
    {
        dirty = false;
        listMain.Redraw();
        listEtc.Redraw();
    }
References dirty, listEtc, and listMain.
Referenced by CheckDirty(), and Redraw().
CanShowContextMenu()
override bool WidgetEquip.CanShowContextMenu () inline virtual
Reimplemented from Widget.
Definition at line 134 of file WidgetEquip.cs.
    {
        ButtonGrid componentOf = InputModuleEX.GetComponentOf<ButtonGrid>();
        if ((bool)componentOf && componentOf.card != null)
        {
            return false;
        }
        return base.CanShowContextMenu();
    }
CheckDirty()
void WidgetEquip.CheckDirty () inline
Definition at line 61 of file WidgetEquip.cs.
    {
        if (dirty)
        {
            _Redraw();
        }
    }
References _Redraw(), and dirty.
Referenced by LayerInventory.SetDirtyAll().
CreateExtra()
override object WidgetEquip.CreateExtra () inline virtual
Reimplemented from Widget.
Definition at line 29 of file WidgetEquip.cs.
    {
        return new Extra();
    }
OnActivate()
override void WidgetEquip.OnActivate () inline virtual
Reimplemented from Widget.
Definition at line 39 of file WidgetEquip.cs.
    {
        chara = EMono.pc;
        Instance = this;
        foreach (Thing thing in EMono.pc.things)
        {
            if (thing.trait is TraitToolBelt)
            {
                AddLayer(LayerInventory.CreateContainer(thing), transLayer);
            }
        }
        Rebuild();
    }
References Widget.AddLayer(), chara, LayerInventory.CreateContainer(), Instance, EMono.pc, Rebuild(), Card.things, Card.trait, and transLayer.
OnSetContextMenu()
override void WidgetEquip.OnSetContextMenu (UIContextMenu m) inline virtual
Reimplemented from Widget.
Definition at line 144 of file WidgetEquip.cs.
    {
        m.AddChild("setting").AddToggle("showWeaponIndex", extra.showIndex, delegate(bool a)
        {
            extra.showIndex = a;
            Rebuild();
            SE.ClickOk();
        });
        SetBaseContextMenu(m);
    }
References extra, Rebuild(), Widget.SetBaseContextMenu(), and WidgetEquip.Extra.showIndex.
Rebuild()
void WidgetEquip.Rebuild () inline
Definition at line 53 of file WidgetEquip.cs.
    {
        RefreshEquipment(listMain);
        RefreshEquipment(listEtc, etc: true);
        dirty = true;
        this.RebuildLayout(recursive: true);
    }
References dirty, listEtc, listMain, and RefreshEquipment().
Referenced by Feat.Apply(), OnActivate(), and OnSetContextMenu().
Redraw()
static void WidgetEquip.Redraw () inline static
Definition at line 69 of file WidgetEquip.cs.
    {
        if ((bool)Instance)
        {
            Instance._Redraw();
        }
    }
References _Redraw(), and Instance.
Referenced by DragItemCard.OnEndDrag(), InvOwner.OnStartDrag(), and Scene.OnUpdate().
RefreshEquipment()
void WidgetEquip.RefreshEquipment (UIList list, bool etc = false) inline
Definition at line 84 of file WidgetEquip.cs.
    {
        list.Clear();
        list.callbacks = new UIList.Callback<BodySlot, ButtonGridDrag>
        {
            onInstantiate = delegate(BodySlot a, ButtonGridDrag b)
            {
                b.SetBodySlot(a, new InvOwnerEquip(chara, a), extra.showIndex);
            },
            onRedraw = delegate(BodySlot a, ButtonGridDrag b, int i)
            {
                b.SetBodySlot(a, new InvOwnerEquip(chara, a), extra.showIndex);
            },
            onSort = (BodySlot a, UIList.SortMode b) => chara.body.GetSortVal(a),
            onList = delegate
            {
                int num = 0;
                foreach (BodySlot slot in chara.body.slots)
                {
                    if (slot.elementId != 44)
                    {
                        if (slot.elementId == 36 || slot.elementId == 31 || slot.elementId == 45)
{
                            if (!etc)
{
                                continue;
                            }
                        }
                        else if (etc)
{
                            continue;
                        }
                        list.Add(slot);
                        num++;
                    }
                }
                if (list == listMain)
                {
                    grid.constraintCount = num / 12 + 1;
                }
            }
        };
        list.onAfterRedraw = delegate
        {
            LayerInventory.TryShowGuide(list);
        };
        list.sortMode = UIList.SortMode.ByNumber;
        list.List();
    }
References Chara.body, chara, BodySlot.elementId, extra, CharaBody.GetSortVal(), listMain, ButtonGrid.SetBodySlot(), WidgetEquip.Extra.showIndex, CharaBody.slots, and LayerInventory.TryShowGuide().
Referenced by Rebuild().
SetDirty()
static void WidgetEquip.SetDirty () inline static
Definition at line 34 of file WidgetEquip.cs.
    {
        dirty = true;
    }
References dirty.
Referenced by CharaBody.Equip(), and CharaBody.Unequip().
Member Data Documentation
chara
Chara WidgetEquip.chara
Definition at line 21 of file WidgetEquip.cs.
Referenced by OnActivate(), and RefreshEquipment().
dirty
bool WidgetEquip.dirty static
Definition at line 13 of file WidgetEquip.cs.
Referenced by _Redraw(), CheckDirty(), Scene.OnUpdate(), Rebuild(), and SetDirty().
dragEquip
Thing WidgetEquip.dragEquip static
Definition at line 15 of file WidgetEquip.cs.
Referenced by LayerInventory.TryShowGuide().
grid
GridLayoutGroup WidgetEquip.grid
Definition at line 25 of file WidgetEquip.cs.
Instance
WidgetEquip WidgetEquip.Instance static
Definition at line 11 of file WidgetEquip.cs.
Referenced by Feat.Apply(), OnActivate(), LayerMiniGame.OnAfterInit(), LayerMiniGame.OnKill(), Redraw(), and LayerInventory.SetDirtyAll().
listEtc
UIList WidgetEquip.listEtc
Definition at line 19 of file WidgetEquip.cs.
Referenced by _Redraw(), and Rebuild().
listMain
UIList WidgetEquip.listMain
Definition at line 17 of file WidgetEquip.cs.
Referenced by _Redraw(), Rebuild(), and RefreshEquipment().
transLayer
RectTransform WidgetEquip.transLayer
Definition at line 23 of file WidgetEquip.cs.
Referenced by OnActivate().
Property Documentation
extra
Extra WidgetEquip.extra get
Definition at line 27 of file WidgetEquip.cs.
Referenced by OnSetContextMenu(), and RefreshEquipment().
The documentation for this class was generated from the following file:
Elin/WidgetEquip.cs