Elin Decompiled Documentation: UIContextMenu Class Reference
UIContextMenu Class Reference
Public Member Functions
void OnPointerEnter (PointerEventData data)
void OnPointerExit (PointerEventData data)
void Show (UIItem i)
void Show (UIButton b)
void Show (Vector2 pos)
void Show ()
void Hide ()
void ClearItems ()
void AddSeparator (int index=0)
void AddButton (Func< string > funcText, UnityAction action=null)
UIButton AddButton (string idLang="", Action action=null, bool hideAfter=true)
UIContextMenuItem AddToggle (string idLang="", bool isOn=false, UnityAction< bool > action=null)
UIContextMenuItem AddSlider (string text, Func< float, string > textFunc, float value, Action< float > action, float min=0f, float max=1f, bool isInt=false, bool hideOther=true, bool useInput=false)
UIContextMenuItem AddSlider (string id, string text, Func< float, string > textFunc, float value, Action< float > action, float min=0f, float max=1f, bool isInt=false, bool hideOther=true, bool useInput=false)
UIContextMenuItem AddSlider (UIContextMenuItem item, string text, Func< float, string > textFunc, float value, Action< float > action, float min=0f, float max=1f, bool isInt=false, bool hideOther=true, bool useInput=false)
GridLayoutGroup AddGridLayout ()
GridLayoutGroup AddGridLayout (string id)
T AddGameObject< T > (T c)
T AddGameObject< T > (string id)
UIContextMenu AddOrGetChild (string idLang="Child")
UIContextMenu AddChild (string idLang, TextAnchor anchor)
UIContextMenu AddChild (string idLang="Child")
UIContextMenu SetHighlightTarget (UIItem i)
UIContextMenu SetHighlightTarget (UIButton t)
Public Attributes
UIContextMenuItem defaultButton
UIContextMenuPopper defaultPopper
UIContextMenuItem defaultToggle
UIContextMenuItem defaultSlider
GridLayoutGroup defaultGridLayout
Transform logo
CanvasGroup cg
GameObject[] separators
Action onDestroy
Action onUpdate
UIContextMenuPopper popper
bool destroyOnHide
bool wasCanceled
Material matBlur
bool system
bool alwaysPopLeft
Image bg
SoundData soundPop
Vector2 margin
Vector2 fixPos
UIButton highlightTarget
bool hideOnMouseLeave
VerticalLayoutGroup layoutGroup
RectTransform _rect
bool isPointerOver
int depth
UIContextMenu parent
float timeSinceOpen
float timeSincePointerLeft
float updatesSinceOpen
bool isDestroyed
Static Public Attributes
static UIContextMenu Current
static float timeSinceClosed
static bool closeOnMouseLeave
Properties
bool isChild [get]
UIContextMenu Root [get]
Private Member Functions
void Awake ()
void Update ()
void LateUpdate ()
void PositionMenu ()
Private Attributes
Vector2 showPos
Detailed Description
Definition at line 8 of file UIContextMenu.cs.
Member Function Documentation
AddButton() [1/2]
void UIContextMenu.AddButton (Func< string > funcText, UnityAction action = null) inline
Definition at line 273 of file UIContextMenu.cs.
    {
        UIContextMenuItem item = UnityEngine.Object.Instantiate(defaultButton);
        item.transform.SetParent(layoutGroup.transform, worldPositionStays: false);
        item.textName.text = funcText();
        Button button = item.button;
        if (action != null)
        {
            button.onClick.AddListener(action);
        }
        button.onClick.AddListener(delegate
        {
            if ((bool)item)
            {
                item.textName.text = funcText();
            }
        });
    }
References Button, defaultButton, item, and layoutGroup.
Referenced by BaseListPeople.OnClick(), ListPeopleExpedition.OnClick(), LayerAbility.OnInit(), LayerMod.OnInit(), AM_EditArea.OnProcessTiles(), AM_MoveInstalled.OnProcessTiles(), WidgetHotbar.OnSetContextMenu(), WidgetMainText.OnSetContextMenu(), WidgetRoster.OnSetContextMenu(), WidgetSideScreen.OnSetContextMenu(), WidgetTracker.OnSetContextMenu(), HotAction.OnShowContextMenu(), HotItemEQSet.OnShowContextMenu(), HotItemLayout.OnShowContextMenu(), HotItemWidgetSet.OnShowContextMenu(), LayerSkinDeco.OnUpdateInput(), ItemCulture.Refresh(), UIInventory.RefreshMenu(), Widget.SetBaseContextMenu(), Widget.SetGridContextMenu(), WidgetHotbar.SetShortcutMenu(), HotItemContext.Show(), InvOwner.ShowContextMenu(), Thing.ShowSplitMenu(), Thing.ShowSplitMenu2(), TraitBed.TrySetAct(), and LayerTextureViewer.Update().
AddButton() [2/2]
UIButton UIContextMenu.AddButton (string idLang = "", Action action = null, bool hideAfter = true) inline
Definition at line 292 of file UIContextMenu.cs.
    {
        UIContextMenuItem uIContextMenuItem = UnityEngine.Object.Instantiate(defaultButton);
        uIContextMenuItem.transform.SetParent(layoutGroup.transform, worldPositionStays: false);
        uIContextMenuItem.textName.text = Lang.Get(idLang);
        UIButton uIButton = uIContextMenuItem.button as UIButton;
        if (hideAfter)
        {
            uIButton.onClick.AddListener(Hide);
        }
        if ((bool)popper && hideAfter)
        {
            uIButton.onClick.AddListener(popper.parent.Hide);
        }
        if (action != null)
        {
            uIButton.onClick.AddListener(delegate
            {
                action();
            });
        }
        return uIButton;
    }
References defaultButton, Lang.Get(), Hide(), layoutGroup, UIContextMenuPopper.parent, and popper.
AddChild() [1/2]
UIContextMenu UIContextMenu.AddChild (string idLang, TextAnchor anchor) inline
Definition at line 496 of file UIContextMenu.cs.
    {
        UIContextMenu uIContextMenu = AddChild(idLang);
        uIContextMenu.layoutGroup.childAlignment = anchor;
        return uIContextMenu;
    }
References AddChild().
Referenced by AddChild(), AddOrGetChild(), LayerAbility.OnInit(), BaseWidgetNotice.OnSetContextMenu(), WidgetBottomBar.OnSetContextMenu(), WidgetCurrentTool.OnSetContextMenu(), WidgetDate.OnSetContextMenu(), WidgetEquip.OnSetContextMenu(), WidgetFeed.OnSetContextMenu(), WidgetHotbar.OnSetContextMenu(), WidgetHP.OnSetContextMenu(), WidgetInspector.OnSetContextMenu(), WidgetMainText.OnSetContextMenu(), WidgetMenuPanel.OnSetContextMenu(), WidgetMinimap.OnSetContextMenu(), WidgetRoster.OnSetContextMenu(), WidgetSideMenu.OnSetContextMenu(), WidgetSideScreen.OnSetContextMenu(), WidgetStatsBar.OnSetContextMenu(), WidgetSticky.OnSetContextMenu(), WidgetUnityChan.OnSetContextMenu(), LayerSkinDeco.OnUpdateInput(), UIInventory.RefreshMenu(), Widget.SetBaseContextMenu(), WidgetHotbar.SetShortcutMenu(), HotItemContext.Show(), and LayerCraftFloat.ShowContextMenu().
AddChild() [2/2]
UIContextMenu UIContextMenu.AddChild (string idLang = "Child") inline
Definition at line 503 of file UIContextMenu.cs.
    {
        UIContextMenuPopper uIContextMenuPopper = UnityEngine.Object.Instantiate(defaultPopper);
        uIContextMenuPopper.transform.SetParent(layoutGroup.transform, worldPositionStays: false);
        uIContextMenuPopper.textName.text = Lang.Get(idLang);
        uIContextMenuPopper.parent = this;
        uIContextMenuPopper.id = idLang;
        UIContextMenu uIContextMenu = uIContextMenuPopper.CreateMenu();
        uIContextMenu.alwaysPopLeft = alwaysPopLeft;
        uIContextMenu.ClearItems();
        uIContextMenuPopper.button.onClick.RemoveAllListeners();
        return uIContextMenuPopper.menu;
    }
References alwaysPopLeft, UIContextMenuItem.button, ClearItems(), UIContextMenuPopper.CreateMenu(), defaultPopper, Lang.Get(), layoutGroup, and UIContextMenuPopper.menu.
AddGameObject< T >() [1/2]
T UIContextMenu.AddGameObject< T > (string id) inline
Type Constraints
T : Component
Definition at line 479 of file UIContextMenu.cs.
                                                 : Component
    {
        return Util.Instantiate<T>("Items/" + id, layoutGroup);
    }
References layoutGroup, and Util.
AddGameObject< T >() [2/2]
T UIContextMenu.AddGameObject< T > (T c) inline
Type Constraints
T : Component
Definition at line 473 of file UIContextMenu.cs.
                                           : Component
    {
        c.transform.SetParent(layoutGroup.transform, worldPositionStays: false);
        return c;
    }
References layoutGroup.
AddGridLayout() [1/2]
GridLayoutGroup UIContextMenu.AddGridLayout () inline
Definition at line 461 of file UIContextMenu.cs.
    {
        GridLayoutGroup gridLayoutGroup = UnityEngine.Object.Instantiate(defaultGridLayout);
        gridLayoutGroup.transform.SetParent(layoutGroup.transform, worldPositionStays: false);
        return gridLayoutGroup;
    }
References defaultGridLayout, and layoutGroup.
Referenced by UIInventory.RefreshMenu(), UIInventory.ShowDistribution(), and TraitMapBoard.TrySetAct().
AddGridLayout() [2/2]
GridLayoutGroup UIContextMenu.AddGridLayout (string id) inline
Definition at line 468 of file UIContextMenu.cs.
    {
        return Util.Instantiate<GridLayoutGroup>("Items/" + id, layoutGroup);
    }
References layoutGroup, and Util.
AddOrGetChild()
UIContextMenu UIContextMenu.AddOrGetChild (string idLang = "Child") inline
Definition at line 484 of file UIContextMenu.cs.
    {
        foreach (UIContextMenuPopper componentsInDirectChild in base.transform.GetComponentsInDirectChildren<UIContextMenuPopper>())
        {
            if (componentsInDirectChild.id == idLang)
            {
                return componentsInDirectChild.menu;
            }
        }
        return AddChild(idLang);
    }
References AddChild(), UIContextMenuPopper.id, and UIContextMenuPopper.menu.
Referenced by Widget.SetBaseContextMenu().
AddSeparator()
void UIContextMenu.AddSeparator (int index = 0) inline
Definition at line 268 of file UIContextMenu.cs.
    {
        UnityEngine.Object.Instantiate(separators[index]).transform.SetParent(layoutGroup.transform, worldPositionStays: false);
    }
References layoutGroup, and separators.
Referenced by HotItemContext.Show().
AddSlider() [1/3]
UIContextMenuItem UIContextMenu.AddSlider (string id, string text, Func< float, string > textFunc, float value, Action< float > action, float min = 0f, float max = 1f, bool isInt = false, bool hideOther = true, bool useInput = false) inline
Definition at line 335 of file UIContextMenu.cs.
    {
        UIContextMenuItem item = Util.Instantiate<UIContextMenuItem>("Items/" + id);
        return AddSlider(item, text, textFunc, value, action, min, max, isInt, hideOther, useInput);
    }
References AddSlider(), item, and Util.
AddSlider() [2/3]
UIContextMenuItem UIContextMenu.AddSlider (string text, Func< float, string > textFunc, float value, Action< float > action, float min = 0f, float max = 1f, bool isInt = false, bool hideOther = true, bool useInput = false) inline
Definition at line 329 of file UIContextMenu.cs.
    {
        UIContextMenuItem item = UnityEngine.Object.Instantiate(defaultSlider);
        return AddSlider(item, text, textFunc, value, action, min, max, isInt, hideOther, useInput);
    }
References AddSlider(), defaultSlider, and item.
Referenced by ActPlan._Update(), AddSlider(), LayerHoard.OnClickConfig(), LayerAbility.OnInit(), BaseWidgetNotice.OnSetContextMenu(), WidgetBottomBar.OnSetContextMenu(), WidgetCurrentTool.OnSetContextMenu(), WidgetFeed.OnSetContextMenu(), WidgetHotbar.OnSetContextMenu(), WidgetHP.OnSetContextMenu(), WidgetInspector.OnSetContextMenu(), WidgetMainText.OnSetContextMenu(), WidgetMenuPanel.OnSetContextMenu(), WidgetMinimap.OnSetContextMenu(), WidgetRoster.OnSetContextMenu(), WidgetSideMenu.OnSetContextMenu(), WidgetSideScreen.OnSetContextMenu(), WidgetSticky.OnSetContextMenu(), LayerSkinDeco.OnUpdateInput(), LayerCollectible.Refresh(), UIInventory.RefreshMenu(), Widget.SetBaseContextMenu(), Widget.SetGridContextMenu(), HotItemContext.Show(), Thing.ShowSplitMenu(), Thing.ShowSplitMenu2(), TraitEffect.TrySetAct(), TraitFigure.TrySetAct(), TraitMapBoard.TrySetAct(), and TraitPaintBoard.TrySetAct().
AddSlider() [3/3]
UIContextMenuItem UIContextMenu.AddSlider (UIContextMenuItem item, string text, Func< float, string > textFunc, float value, Action< float > action, float min = 0f, float max = 1f, bool isInt = false, bool hideOther = true, bool useInput = false) inline
Definition at line 341 of file UIContextMenu.cs.
    {
        UiInputField input = item.GetComponentInChildren<UiInputField>();
        Slider s = item.slider;
        item.transform.SetParent(layoutGroup.transform, worldPositionStays: false);
        item.textName.text = text.lang();
        s.minValue = min;
        if (max < 0f)
        {
            max = 0f;
        }
        s.maxValue = max;
        s.wholeNumbers = isInt;
        s.SetValueWithoutNotify(value);
        item.textSlider.text = textFunc(value);
        s.onValueChanged.AddListener(delegate(float a)
        {
            item.textSlider.text = textFunc(a);
            action(a);
            if ((bool)input)
            {
                input.text = s.value.ToString() ?? "";
                input.Select();
                input.HideCaret();
            }
        });
        if ((bool)input)
        {
            input.SetActive(useInput);
            input.text = s.value.ToString() ?? "";
            input.onValueChanged.AddListener(delegate(string text)
            {
                if (!text.IsEmpty())
                {
                    float num2 = Mathf.Clamp(text.ToInt(), min, max);
                    s.SetValueWithoutNotify(num2);
                    action(num2);
                }
            });
            input.onUpdate = delegate
            {
                if (Input.GetKeyDown(KeyCode.Space) || Input.GetKeyDown(KeyCode.Return) || Input.GetKeyDown(KeyCode.KeypadEnter))
                {
                    action(s.value);
                    Current?.Hide();
                }
                else if (!input.text.IsEmpty())
                {
                    int num = input.text.ToInt();
                    if ((float)num > max)
                    {
                        num = (int)max;
                        input.text = num.ToString() ?? "";
                        s.SetValueWithoutNotify(num);
                    }
                }
            };
            if (useInput)
            {
                input.onDisable = delegate
                {
                    action(s.value);
                };
            }
            if (useInput)
            {
                input.Select();
            }
        }
        if (hideOther)
        {
            RectTransform blocker = null;
            EventTrigger component = s.GetComponent<EventTrigger>();
            component.triggers.Clear();
            EventTrigger.Entry entry = new EventTrigger.Entry
            {
                eventID = EventTriggerType.PointerDown
            };
            entry.callback.AddListener(delegate
            {
                blocker = Util.Instantiate<RectTransform>("Items/sliderBlocker", this);
                blocker.SetAsFirstSibling();
                UIContextMenu[] componentsInParent2 = GetComponentsInParent<UIContextMenu>();
                for (int j = 0; j < componentsInParent2.Length; j++)
                {
                    componentsInParent2[j].cg.DOFade(0.01f, 1f);
                }
                if ((bool)s && s.gameObject != null)
                {
                    s.gameObject.AddComponent<CanvasGroup>().ignoreParentGroups = true;
                }
            });
            component.triggers.Add(entry);
            entry = new EventTrigger.Entry
            {
                eventID = EventTriggerType.PointerUp
            };
            entry.callback.AddListener(delegate
            {
                if (!isPointerOver)
                {
                    Root.Hide();
                }
                else
                {
                    UIContextMenu[] componentsInParent = GetComponentsInParent<UIContextMenu>();
                    foreach (UIContextMenu obj in componentsInParent)
                    {
                        DOTween.Kill(obj.cg);
                        obj.cg.alpha = 1f;
                    }
                    UnityEngine.Object.Destroy(s.GetComponent<CanvasGroup>());
                    UnityEngine.Object.DestroyImmediate(blocker.gameObject);
                }
            });
            component.triggers.Add(entry);
        }
        return item;
    }
References cg, UiInputField.Clear(), Current, Hide(), isPointerOver, item, layoutGroup, Root, and Util.
AddToggle()
UIContextMenuItem UIContextMenu.AddToggle (string idLang = "", bool isOn = false, UnityAction< bool > action = null) inline
Definition at line 316 of file UIContextMenu.cs.
    {
        UIContextMenuItem uIContextMenuItem = UnityEngine.Object.Instantiate(defaultToggle);
        uIContextMenuItem.transform.SetParent(layoutGroup.transform, worldPositionStays: false);
        uIContextMenuItem.textName.text = idLang.lang().ToTitleCase();
        uIContextMenuItem.toggle.isOn = isOn;
        if (action != null)
        {
            uIContextMenuItem.toggle.onValueChanged.AddListener(action);
        }
        return uIContextMenuItem;
    }
References defaultToggle, layoutGroup, and UIContextMenuItem.toggle.
Referenced by LayerHoard.OnClickConfig(), LayerAbility.OnInit(), WidgetBottomBar.OnSetContextMenu(), WidgetDate.OnSetContextMenu(), WidgetEquip.OnSetContextMenu(), WidgetHotbar.OnSetContextMenu(), WidgetHP.OnSetContextMenu(), WidgetInspector.OnSetContextMenu(), WidgetMainText.OnSetContextMenu(), WidgetMascot.OnSetContextMenu(), WidgetMinimap.OnSetContextMenu(), WidgetNotice.OnSetContextMenu(), WidgetRoster.OnSetContextMenu(), WidgetSideScreen.OnSetContextMenu(), WidgetStatsBar.OnSetContextMenu(), WidgetSticky.OnSetContextMenu(), WidgetTracker.OnSetContextMenu(), WidgetUnityChan.OnSetContextMenu(), HotItemContext.OnShowContextMenu(), LayerSkinDeco.OnUpdateInput(), LayerCollectible.Refresh(), UIInventory.RefreshMenu(), Widget.SetBaseContextMenu(), HotItemContext.Show(), and UIInventory.ShowDistribution().
Awake()
void UIContextMenu.Awake () inline private
Definition at line 103 of file UIContextMenu.cs.
    {
        layoutGroup = GetComponent<VerticalLayoutGroup>();
        _rect = base.transform as RectTransform;
        base.gameObject.SetActive(value: false);
    }
References _rect, and layoutGroup.
ClearItems()
void UIContextMenu.ClearItems () inline
Definition at line 263 of file UIContextMenu.cs.
    {
        layoutGroup.DestroyChildren();
    }
References layoutGroup.
Referenced by AddChild().
Hide()
void UIContextMenu.Hide () inline
Definition at line 226 of file UIContextMenu.cs.
    {
        if (!UIContextMenuManager.Instance.autoClose)
        {
            return;
        }
        isPointerOver = false;
        if (destroyOnHide)
        {
            if (!isDestroyed)
            {
                isDestroyed = true;
                UnityEngine.Object.DestroyImmediate(base.gameObject);
                if (onDestroy != null)
                {
                    onDestroy();
                }
                if ((bool)highlightTarget && !InputModuleEX.IsPointerOver(highlightTarget))
                {
                    highlightTarget.DoNormalTransition();
                }
            }
        }
        else
        {
            if (!base.gameObject.activeSelf)
            {
                return;
            }
            base.gameObject.SetActive(value: false);
        }
        EInput.DisableIME();
        BaseCore.Instance.eventSystem.SetSelectedGameObject(null);
        BaseCore.Instance.ConsumeInput();
        UIButton.TryShowTip();
    }
References UIContextMenuManager.autoClose, BaseCore.ConsumeInput(), destroyOnHide, EInput.DisableIME(), UIButton.DoNormalTransition(), BaseCore.eventSystem, highlightTarget, BaseCore.Instance, UIContextMenuManager.Instance, isDestroyed, InputModuleEX.IsPointerOver(), isPointerOver, onDestroy, and UIButton.TryShowTip().
Referenced by AddButton(), AddSlider(), UIContextMenuManager.Create(), UIContextMenuPopper.Depop(), Scene.OnUpdate(), LayerSkinDeco.OnUpdateInput(), Widget.SetBaseContextMenu(), LayerCraftFloat.ShowContextMenu(), and Update().
LateUpdate()
void UIContextMenu.LateUpdate () inline private
Definition at line 157 of file UIContextMenu.cs.
    {
        if ((bool)highlightTarget)
        {
            highlightTarget.DoHighlightTransition();
        }
    }
References UIButton.DoHighlightTransition(), and highlightTarget.
OnPointerEnter()
void UIContextMenu.OnPointerEnter (PointerEventData data) inline
Definition at line 165 of file UIContextMenu.cs.
    {
        isPointerOver = true;
    }
References isPointerOver.
OnPointerExit()
void UIContextMenu.OnPointerExit (PointerEventData data) inline
Definition at line 170 of file UIContextMenu.cs.
    {
        isPointerOver = false;
    }
References isPointerOver.
PositionMenu()
void UIContextMenu.PositionMenu () inline private
Definition at line 517 of file UIContextMenu.cs.
    {
        base.gameObject.SetActive(value: true);
        this.RebuildLayout(recursive: true);
        _rect.anchoredPosition = showPos;
        RectTransform obj = _rect.parent as RectTransform;
        Vector3 localPosition = _rect.localPosition;
        Vector3 vector = obj.rect.min - _rect.rect.min;
        Vector3 vector2 = obj.rect.max - _rect.rect.max;
        localPosition.x = Mathf.Clamp(_rect.localPosition.x, vector.x, vector2.x);
        localPosition.y = Mathf.Clamp(_rect.localPosition.y, vector.y, vector2.y + margin.y);
        _rect.localPosition = localPosition;
    }
References _rect, margin, and showPos.
Referenced by Show().
SetHighlightTarget() [1/2]
UIContextMenu UIContextMenu.SetHighlightTarget (UIButton t) inline
Definition at line 536 of file UIContextMenu.cs.
    {
        highlightTarget = t;
        return this;
    }
References highlightTarget.
SetHighlightTarget() [2/2]
UIContextMenu UIContextMenu.SetHighlightTarget (UIItem i) inline
Definition at line 531 of file UIContextMenu.cs.
    {
        return SetHighlightTarget(i.button1);
    }
References UIItem.button1, and SetHighlightTarget().
Referenced by SetHighlightTarget(), and Show().
Show() [1/4]
void UIContextMenu.Show () inline
Definition at line 192 of file UIContextMenu.cs.
    {
        wasCanceled = false;
        if (isChild)
        {
            hideOnMouseLeave = Current.hideOnMouseLeave;
        }
        else
        {
            hideOnMouseLeave = true;
        }
        if (showPos == Vector2.zero)
        {
            showPos = EInput.uiMousePosition;
        }
        base.gameObject.SetActive(value: true);
        this.RebuildLayout(recursive: true);
        if (!isChild)
        {
            showPos += fixPos;
            if ((bool)soundPop)
            {
                SE.Play(soundPop);
            }
            _rect.anchoredPosition = new Vector2(-10000f, -10000f);
            PositionMenu();
            Current = this;
        }
        if ((bool)TooltipManager.Instance)
        {
            TooltipManager.Instance.HideTooltips();
        }
    }
References Current, fixPos, hideOnMouseLeave, TooltipManager.HideTooltips(), TooltipManager.Instance, isChild, PositionMenu(), showPos, soundPop, EInput.uiMousePosition, and wasCanceled.
Referenced by Show().
Show() [2/4]
void UIContextMenu.Show (UIButton b) inline
Definition at line 180 of file UIContextMenu.cs.
    {
        SetHighlightTarget(b);
        Show();
    }
References SetHighlightTarget(), and Show().
Show() [3/4]
void UIContextMenu.Show (UIItem i) inline
Definition at line 175 of file UIContextMenu.cs.
    {
        Show(i.button1);
    }
References UIItem.button1, and Show().
Referenced by ActPlan._Update(), ListPeopleExpedition.OnClick(), LayerHoard.OnClickConfig(), WidgetHotbar.OnClickEmptyItem(), LayerAbility.OnInit(), LayerMod.OnInit(), AM_EditArea.OnProcessTiles(), AM_MoveInstalled.OnProcessTiles(), AM_Select.OnUpdateInput(), LayerSkinDeco.OnUpdateInput(), UIContextMenuPopper.Pop(), ItemCulture.Refresh(), LayerCollectible.Refresh(), Widget.ShowContextMenu(), InvOwner.ShowContextMenu(), LayerCraftFloat.ShowContextMenu(), Thing.ShowSplitMenu(), Thing.ShowSplitMenu2(), TraitEffect.TrySetAct(), TraitFigure.TrySetAct(), TraitMapBoard.TrySetAct(), TraitPaintBoard.TrySetAct(), and LayerTextureViewer.Update().
Show() [4/4]
void UIContextMenu.Show (Vector2 pos) inline
Definition at line 186 of file UIContextMenu.cs.
    {
        showPos = pos;
        Show();
    }
References Show(), and showPos.
Update()
void UIContextMenu.Update () inline private
Definition at line 110 of file UIContextMenu.cs.
    {
        if (onUpdate != null)
        {
            onUpdate();
        }
        if ((bool)highlightTarget)
        {
            highlightTarget.DoHighlightTransition();
        }
        timeSinceOpen += Time.unscaledDeltaTime;
        if (timeSinceOpen < 0.3f)
        {
            return;
        }
        if (Input.GetKeyDown(KeyCode.Escape) || Input.GetMouseButtonDown(1))
        {
            wasCanceled = true;
            Hide();
            return;
        }
        updatesSinceOpen += 1f;
        if (!Current.hideOnMouseLeave && updatesSinceOpen > 10f && !isPointerOver && Input.GetMouseButtonDown(0) && !isChild)
        {
            Hide();
        }
        else if (updatesSinceOpen > 10f && !isPointerOver && !Input.GetMouseButton(0))
        {
            timeSincePointerLeft += Time.unscaledDeltaTime;
            if ((!isChild || !popper.isPointerOver) && timeSincePointerLeft > 0.1f)
            {
                if (Input.GetMouseButtonUp(0))
                {
                    Hide();
                }
                if (hideOnMouseLeave && (!isChild || !popper.isPointerOver))
                {
                    Hide();
                }
            }
        }
        else
        {
            timeSincePointerLeft = 0f;
        }
    }
References Current, UIButton.DoHighlightTransition(), Hide(), hideOnMouseLeave, highlightTarget, isChild, isPointerOver, UIContextMenuPopper.isPointerOver, onUpdate, popper, timeSinceOpen, timeSincePointerLeft, updatesSinceOpen, and wasCanceled.
Member Data Documentation
_rect
RectTransform UIContextMenu._rect
Definition at line 66 of file UIContextMenu.cs.
Referenced by Awake(), PositionMenu(), and UIContextMenuPopper.PositionMenu().
alwaysPopLeft
bool UIContextMenu.alwaysPopLeft
Definition at line 46 of file UIContextMenu.cs.
Referenced by AddChild(), and UIContextMenuPopper.PositionMenu().
bg
Image UIContextMenu.bg
Definition at line 48 of file UIContextMenu.cs.
cg
CanvasGroup UIContextMenu.cg
Definition at line 28 of file UIContextMenu.cs.
Referenced by AddSlider().
closeOnMouseLeave
bool UIContextMenu.closeOnMouseLeave static
Definition at line 14 of file UIContextMenu.cs.
Current
UIContextMenu UIContextMenu.Current static
Definition at line 10 of file UIContextMenu.cs.
Referenced by AddSlider(), UIMagicChest.Init(), UIMagicChest.LateUpdate(), Scene.OnUpdate(), UIContextMenuPopper.Pop(), UIMagicChest.RefreshCats(), Show(), TooltipManager.ShowTooltip(), Update(), and UIContextMenuPopper.Update().
defaultButton
UIContextMenuItem UIContextMenu.defaultButton
Definition at line 16 of file UIContextMenu.cs.
Referenced by AddButton().
defaultGridLayout
GridLayoutGroup UIContextMenu.defaultGridLayout
Definition at line 24 of file UIContextMenu.cs.
Referenced by AddGridLayout().
defaultPopper
UIContextMenuPopper UIContextMenu.defaultPopper
Definition at line 18 of file UIContextMenu.cs.
Referenced by AddChild().
defaultSlider
UIContextMenuItem UIContextMenu.defaultSlider
Definition at line 22 of file UIContextMenu.cs.
Referenced by AddSlider().
defaultToggle
UIContextMenuItem UIContextMenu.defaultToggle
Definition at line 20 of file UIContextMenu.cs.
Referenced by AddToggle().
depth
int UIContextMenu.depth
Definition at line 72 of file UIContextMenu.cs.
destroyOnHide
bool UIContextMenu.destroyOnHide
Definition at line 38 of file UIContextMenu.cs.
Referenced by Hide().
fixPos
Vector2 UIContextMenu.fixPos
Definition at line 54 of file UIContextMenu.cs.
Referenced by Show().
hideOnMouseLeave
bool UIContextMenu.hideOnMouseLeave
Definition at line 58 of file UIContextMenu.cs.
Referenced by UIContextMenuPopper.Pop(), Show(), Update(), and UIContextMenuPopper.Update().
highlightTarget
UIButton UIContextMenu.highlightTarget
Definition at line 56 of file UIContextMenu.cs.
Referenced by Hide(), LateUpdate(), SetHighlightTarget(), and Update().
isDestroyed
bool UIContextMenu.isDestroyed
Definition at line 87 of file UIContextMenu.cs.
Referenced by Hide().
isPointerOver
bool UIContextMenu.isPointerOver
Definition at line 69 of file UIContextMenu.cs.
Referenced by AddSlider(), Hide(), OnPointerEnter(), OnPointerExit(), Update(), and UIContextMenuPopper.Update().
layoutGroup
VerticalLayoutGroup UIContextMenu.layoutGroup
Definition at line 63 of file UIContextMenu.cs.
Referenced by AddButton(), AddChild(), AddGameObject< T >(), AddGridLayout(), AddSeparator(), AddSlider(), AddToggle(), Awake(), ClearItems(), and UIInventory.RefreshMenu().
logo
Transform UIContextMenu.logo
Definition at line 26 of file UIContextMenu.cs.
Referenced by UIContextMenuManager.Create().
margin
Vector2 UIContextMenu.margin
Definition at line 52 of file UIContextMenu.cs.
Referenced by PositionMenu().
matBlur
Material UIContextMenu.matBlur
Definition at line 42 of file UIContextMenu.cs.
Referenced by UIContextMenuPopper.CreateMenu().
onDestroy
Action UIContextMenu.onDestroy
Definition at line 32 of file UIContextMenu.cs.
Referenced by Hide().
onUpdate
Action UIContextMenu.onUpdate
Definition at line 34 of file UIContextMenu.cs.
Referenced by Update().
parent
UIContextMenu UIContextMenu.parent
Definition at line 75 of file UIContextMenu.cs.
popper
UIContextMenuPopper UIContextMenu.popper
Definition at line 36 of file UIContextMenu.cs.
Referenced by AddButton(), and Update().
separators
GameObject [] UIContextMenu.separators
Definition at line 30 of file UIContextMenu.cs.
Referenced by AddSeparator().
showPos
Vector2 UIContextMenu.showPos private
Definition at line 60 of file UIContextMenu.cs.
Referenced by PositionMenu(), and Show().
soundPop
SoundData UIContextMenu.soundPop
Definition at line 50 of file UIContextMenu.cs.
Referenced by Show().
system
bool UIContextMenu.system
Definition at line 44 of file UIContextMenu.cs.
Referenced by UIContextMenuPopper.CreateMenu().
timeSinceClosed
float UIContextMenu.timeSinceClosed static
Definition at line 12 of file UIContextMenu.cs.
Referenced by UIButton.OnHover().
timeSinceOpen
float UIContextMenu.timeSinceOpen
Definition at line 78 of file UIContextMenu.cs.
Referenced by Update(), and UIContextMenuPopper.Update().
timeSincePointerLeft
float UIContextMenu.timeSincePointerLeft
Definition at line 81 of file UIContextMenu.cs.
Referenced by Update().
updatesSinceOpen
float UIContextMenu.updatesSinceOpen
Definition at line 84 of file UIContextMenu.cs.
Referenced by Update().
wasCanceled
bool UIContextMenu.wasCanceled
Definition at line 40 of file UIContextMenu.cs.
Referenced by Show(), Thing.ShowSplitMenu(), and Update().
Property Documentation
isChild
bool UIContextMenu.isChild get
Definition at line 89 of file UIContextMenu.cs.
Referenced by Show(), and Update().
Root
UIContextMenu UIContextMenu.Root get
Definition at line 91 of file UIContextMenu.cs.
    {
        get
        {
            if (!parent)
            {
                return this;
            }
            return parent.Root;
        }
    }
Referenced by AddSlider().
The documentation for this class was generated from the following file:
Elin/Plugins.UI/UIContextMenu.cs