Elin Decompiled Documentation: StatsStamina Class Reference
StatsStamina Class Reference
Public Member Functions
override void Mod (int a)
override int GetPhase ()
Public Member Functions inherited from Stats
override int GetValue ()
override string ToString ()
override string GetText ()
override Color GetColor (Gradient g)
Stats Set (int[] _raw, int _rawIndex, Chara _CC)
override int GetPhase ()
virtual void Set (int a)
virtual void Mod (int a)
virtual void OnChangePhase (int phase, int lastPhase)
Public Member Functions inherited from BaseStats
virtual Color GetColor (Gradient gradient)
virtual Color GetColor (SkinColorProfile c)
Color GetColor ()
virtual string GetText ()
virtual string GetPhaseStr ()
virtual int GetValue ()
virtual int GetSortVal ()
virtual Sprite GetSprite ()
virtual void SetText (UIText t, SkinColorProfile cols=null)
virtual int GetPhase ()
void PopText ()
virtual void WriteNote (UINote n, Action< UINote > onWriteNote=null)
virtual void _WriteNote (UINote n, bool asChild=false)
Static Public Attributes
const int Exhausted = 0
const int VeryTired = 1
const int Tired = 2
const int Fine = 3
Static Public Attributes inherited from Stats
static StatsHunger Hunger
static StatsBurden Burden
static StatsStamina Stamina
static StatsSleepiness Sleepiness
static Stats Depression
static Stats Bladder
static StatsHygiene Hygiene
static StatsMana Mana
static StatsSAN SAN
Static Public Attributes inherited from BaseStats
static Chara CC
Static Public Attributes inherited from EClass
static Core core
Properties
override bool TrackPhaseChange [get]
override int max [get]
override int min [get]
Properties inherited from Stats
virtual int value [get, set]
virtual int max [get, set]
string name [get]
virtual bool TrackPhaseChange [get]
virtual int min [get]
Properties inherited from BaseStats
SourceStat.Row source [get]
virtual Emo2 EmoIcon [get]
virtual ConditionType Type [get]
virtual string idSprite [get]
virtual bool ShowInWidget [get]
virtual Chara Owner [get]
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Additional Inherited Members
Static Public Member Functions inherited from EClass
static int rndSeed (int a, int seed)
static int rnd (long a)
static int rnd (int a)
static int curve (int a, int start, int step, int rate=75)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Public Attributes inherited from Stats
int rawIndex
int[] raw
Public Attributes inherited from BaseStats
int id
SourceStat.Row _source
Detailed Description
Definition at line 1 of file StatsStamina.cs.
Member Function Documentation
GetPhase()
override int StatsStamina.GetPhase () inline virtual
Reimplemented from Stats.
Definition at line 50 of file StatsStamina.cs.
    {
        if (value < 0)
        {
            return 0;
        }
        return base.GetPhase();
    }
References Stats.value.
Mod()
override void StatsStamina.Mod (int a) inline virtual
Reimplemented from Stats.
Definition at line 17 of file StatsStamina.cs.
    {
        if (BaseStats.CC.IsPC && EClass.debug.godMode && a < 0)
        {
            return;
        }
        if (a < 0 && BaseStats.CC.HasElement(1330))
        {
            if (a == -1 && EClass.rnd(4) == 0)
            {
                return;
            }
            a = -EClass.rnd(-a * 130 / 100 + 2);
        }
        int num = BaseStats.CC.Evalue(1403);
        if (a < 0 && num > 0 && (a != -1 || EClass.rnd(num + 1) != 0))
        {
            a = a * 100 / (100 + EClass.rnd(num + 1) * 20);
        }
        if (a != 0)
        {
            base.Mod(a);
            if (a < 0)
            {
                _ = BaseStats.CC.ShouldShowMsg;
            }
            if (a < 0 && value < 0)
            {
                BaseStats.CC.DamageHP(-value, AttackSource.Fatigue);
            }
        }
    }
References BaseStats.CC, Card.DamageHP(), EClass.debug, Card.Evalue(), CoreDebug.godMode, Card.HasElement(), Chara.IsPC, EClass.rnd(), Card.ShouldShowMsg, and Stats.value.
Member Data Documentation
Exhausted
const int StatsStamina.Exhausted = 0 static
Definition at line 3 of file StatsStamina.cs.
Fine
const int StatsStamina.Fine = 3 static
Definition at line 9 of file StatsStamina.cs.
Tired
const int StatsStamina.Tired = 2 static
Definition at line 7 of file StatsStamina.cs.
VeryTired
const int StatsStamina.VeryTired = 1 static
Definition at line 5 of file StatsStamina.cs.
Property Documentation
max
override int StatsStamina.max get
Definition at line 13 of file StatsStamina.cs.
min
override int StatsStamina.min get
Definition at line 15 of file StatsStamina.cs.
TrackPhaseChange
override bool StatsStamina.TrackPhaseChange get
Definition at line 11 of file StatsStamina.cs.
The documentation for this class was generated from the following file:
Elin/StatsStamina.cs