Elin Decompiled Documentation: UIRecipeInfo Class Reference
UIRecipeInfo Class Reference
Classes
class RecipeVariation
Public Member Functions
void Init ()
void SetArea (Area a)
void SetRecipe (Recipe r)
void Clear ()
void RefreshBalance ()
void RefreshImages ()
void Refresh ()
void OnRotate ()
void RefreshQuality ()
void RefreshList ()
Public Attributes
UIText textName
UIText textDetail
UIText textCost
UIText textInfo
UIText textQuality
UIText textReqSkill
UIText textCostSP
Thing factory
Recipe recipe
Area area
UIList listIngredients
UIList listVariations
Image imageArea
Image imageIcon
UINote note
Color colorCost
Color colorPredict
GameObject goMoney
GameObject goIngredients
GameObject goInfo
bool main
bool CraftMode
StockSearchMode searchMode
DropdownGrid ddList
DropdownGrid ddFactory
ButtonGrid buttonProduct
Dictionary< string, int > lastMats = new Dictionary<string, int>()
bool hideMode = true
List< DropdownRecipe > dds = new List<DropdownRecipe>()
Properties
HitSummary summary [get]
Properties inherited from EMono
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SoundManager Sound [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static CoreDebug debug [get]
Additional Inherited Members
Static Public Member Functions inherited from EMono
static int rnd (int a)
Static Public Attributes inherited from EMono
static Core core
Detailed Description
Definition at line 7 of file UIRecipeInfo.cs.
Member Function Documentation
Clear()
void UIRecipeInfo.Clear () inline
Definition at line 150 of file UIRecipeInfo.cs.
    {
        recipe = null;
        area = null;
        if (main)
        {
            goIngredients.SetActive(value: false);
            goInfo.SetActive(value: false);
            if ((bool)listVariations)
            {
                listVariations.SetActive(enable: false);
            }
        }
        if (textName.text != "")
        {
            UIText uIText = textName;
            string text2 = (textDetail.text = "");
            uIText.text = text2;
            RefreshList();
            RefreshBalance();
            if ((bool)imageArea)
            {
                imageArea.SetActive(enable: false);
            }
            note.Clear();
            note.Build();
            this.RebuildLayout(recursive: true);
        }
    }
References area, UINote.Build(), UINote.Clear(), goInfo, goIngredients, imageArea, listVariations, main, note, recipe, RefreshBalance(), RefreshList(), and textName.
Referenced by SetArea(), and SetRecipe().
Init()
void UIRecipeInfo.Init () inline
Definition at line 79 of file UIRecipeInfo.cs.
    {
        DropdownRecipe.colorCost = colorCost;
        DropdownRecipe.colorPredict = colorPredict;
        SetRecipe(null);
    }
References colorCost, colorPredict, and SetRecipe().
Referenced by BuildMenu.Init().
OnRotate()
void UIRecipeInfo.OnRotate () inline
Definition at line 381 of file UIRecipeInfo.cs.
    {
        if (listVariations.gameObject.activeSelf)
        {
            listVariations.group.Select(recipe._dir);
        }
        RefreshImages();
    }
References Recipe._dir, UIList.group, listVariations, recipe, RefreshImages(), and UISelectableGroup.Select().
Referenced by Recipe.Rotate(), RecipeCard.Rotate(), and Recipe.SetDir().
Refresh()
void UIRecipeInfo.Refresh () inline
Definition at line 244 of file UIRecipeInfo.cs.
    {
        if (recipe == null)
        {
            return;
        }
        if (recipe.UseStock || recipe.IngAsProduct)
        {
            Thing thing = recipe.ingredients[0].thing;
            if (thing == null || thing.isDestroyed || thing.ExistsOnMap)
            {
                return;
            }
        }
        Recipe r = recipe;
        r.OnSelected();
        RefreshList();
        RefreshBalance();
        if (r.UseStock && r.ingredients[0].thing == null)
        {
            return;
        }
        textName.text = r.GetName();
        string text = "";
        int[] tiles = recipe.renderRow.tiles;
        if (EMono.debug.showExtra)
        {
            text = text + "(" + recipe.id + "  " + recipe.renderRow.idRenderData + "/" + ((tiles.Length != 0) ? tiles[0] : (-1)) + ")" + Environment.NewLine;
        }
        textDetail.SetActive(enable: true);
        if (CraftMode)
        {
            if (main)
            {
                EMono.pc.things.GetThingStack(r.GetIdThing(), r.GetRefVal());
                int num = EMono.player.recipes.knownRecipes.TryGetValue(r.id, 0);
                textInfo.SetText("recipe_lv".lang(num.ToString() ?? ""));
                text += r.GetDetail();
            }
            else
            {
                text += r.GetDetail();
                r.WriteNote(note);
            }
        }
        else
        {
            string detail = r.GetDetail();
            if (!detail.IsEmpty())
            {
                text = text + detail + "\n\n";
            }
            text = text + "( " + r.tileType.LangPlaceType.lang() + " ) " + (r.tileType.LangPlaceType + "_hint").lang();
            if (r.UseStock && r.ingredients[0].thing != null)
            {
                r.ingredients[0].thing.WriteNote(note, null, IInspect.NoteMode.Recipe);
            }
            else
            {
                r.WriteNote(note);
            }
            if (!r.UseStock && r.source.NeedFactory)
            {
                PropSet propSet = EMono._map.Installed.cardMap.TryGetValue(r.source.idFactory);
                if ((propSet == null || propSet.Count == 0) && EMono.pc.things.Find((Thing t) => t.id == r.source.idFactory) == null)
                {
                    note.Space(8);
                    note.AddText("noFactory".lang(r.source.NameFactory), FontColor.Bad);
                    note.Build();
                }
            }
        }
        textDetail.SetText(text);
        if ((bool)goMoney)
        {
            goMoney.transform.SetAsLastSibling();
        }
        if (main)
        {
            if ((bool)listVariations)
            {
                UIList uIList = listVariations;
                bool flag = r.CanRotate && r.renderRow != null;
                int[] array = (flag ? r.renderRow._tiles : null);
                if (flag && array.Length <= 1)
                {
                    flag = false;
                }
                uIList.SetActive(flag);
                if (flag)
                {
                    uIList.Clear();
                    uIList.callbacks = new UIList.Callback<RecipeVariation, ButtonGrid>
                    {
                        onClick = delegate(RecipeVariation a, ButtonGrid b)
{
                            r.SetDir(a.dir);
                        },
                        onInstantiate = delegate(RecipeVariation a, ButtonGrid b)
{
                            b.SetRecipeVariation(a);
                        },
                        onRedraw = delegate(RecipeVariation a, ButtonGrid b, int i)
{
                            b.SetRecipeVariation(a);
                        }
                    };
                    for (int j = 0; j < array.Length; j++)
                    {
                        uIList.Add(new RecipeVariation
{
                            recipe = r,
                            dir = j
                        });
                    }
                    uIList.Refresh();
                    uIList.group.Init(r._dir);
                }
            }
            if ((bool)goMoney)
            {
                goMoney.SetActive(!CraftMode);
            }
        }
        else
        {
            listIngredients.SetActive(!recipe.UseStock || recipe.VirtualBlock);
            if ((bool)goMoney)
            {
                goMoney.SetActive(r.CostMoney != 0);
            }
        }
        RefreshImages();
        this.SetActive(enable: true);
        this.RebuildLayout(recursive: true);
    }
References Recipe._dir, EMono._map, UIList.Add(), UINote.AddText(), UINote.Build(), Props.cardMap, UIList.Clear(), Recipe.CostMoney, CraftMode, EMono.debug, UIRecipeInfo.RecipeVariation.dir, Card.ExistsOnMap, ThingContainer.Find(), Recipe.GetDetail(), Recipe.GetIdThing(), Recipe.GetName(), Recipe.GetRefVal(), ThingContainer.GetThingStack(), goMoney, UIList.group, Recipe.id, RecipeSource.idFactory, Recipe.IngAsProduct, Recipe.ingredients, UISelectableGroup.Init(), Map.Installed, Card.isDestroyed, RecipeManager.knownRecipes, TileType.LangPlaceType, listIngredients, listVariations, main, RecipeSource.NameFactory, RecipeSource.NeedFactory, note, Recipe.OnSelected(), EMono.pc, EMono.player, recipe, Player.recipes, UIList.Refresh(), RefreshBalance(), RefreshImages(), RefreshList(), Recipe.renderRow, Recipe.SetDir(), ButtonGrid.SetRecipeVariation(), UIText.SetText(), CoreDebug.showExtra, Recipe.source, UINote.Space(), textDetail, textInfo, Card.things, RenderRow.tiles, Recipe.tileType, Recipe.UseStock, Recipe.VirtualBlock, and Recipe.WriteNote().
Referenced by BaseTileSelector.ExecuteSummary(), and SetRecipe().
RefreshBalance()
void UIRecipeInfo.RefreshBalance () inline
Definition at line 180 of file UIRecipeInfo.cs.
    {
        if (!main)
        {
            return;
        }
        string text = Lang._Number(EMono.pc.GetCurrency());
        if (summary.money != 0)
        {
            text = text + "<color=" + colorCost.ToHex() + ">  -" + summary.money + "</color>";
        }
        textCost.SetText(text);
        foreach (DropdownRecipe dd in dds)
        {
            dd.RefreshLabel();
        }
        if ((bool)ddList)
        {
            ddList.Redraw();
        }
        if ((bool)textCostSP)
        {
            int countValid = summary.countValid;
            int num = ((countValid == 0) ? (-1) : (recipe.source.GetSPCost(summary.factory) * countValid));
            text = ((num == -1) ? "-" : (num.ToString() ?? ""));
            DOTweenAnimation component = textCostSP.GetComponent<DOTweenAnimation>();
            Transform transform = textCostSP.Find("nerun");
            bool flag = num >= EMono.pc.stamina.value;
            if ((bool)component && !flag)
            {
                component.DOPause();
            }
            textCostSP.SetText(text, (num == -1) ? FontColor.Bad : ((num < EMono.pc.stamina.value) ? FontColor.Good : FontColor.Warning));
            if ((bool)component && flag)
            {
                component.tween.Restart();
            }
            if ((bool)transform)
            {
                transform.SetActive(flag);
            }
        }
    }
References Lang._Number(), colorCost, HitSummary.countValid, ddList, dds, HitSummary.factory, Card.GetCurrency(), RecipeSource.GetSPCost(), main, HitSummary.money, EMono.pc, recipe, DropdownGrid.Redraw(), DropdownRecipe.RefreshLabel(), UIText.SetText(), Recipe.source, Chara.stamina, summary, textCost, textCostSP, and Stats.value.
Referenced by Clear(), Refresh(), LayerCraft.RefreshProduct(), and BaseTileSelector.RefreshSummary().
RefreshImages()
void UIRecipeInfo.RefreshImages () inline
Definition at line 224 of file UIRecipeInfo.cs.
    {
        Recipe recipe = this.recipe;
        if ((bool)listVariations)
        {
            listVariations.Redraw();
        }
        if ((bool)imageIcon)
        {
            if (recipe.UseStock && !recipe.VirtualBlock)
            {
                recipe.ingredients[0].thing.SetImage(imageIcon, recipe._dir, recipe.ingredients[0].thing.trait.IdSkin);
            }
            else
            {
                recipe.renderRow.SetImage(imageIcon, null, recipe.renderRow.GetColorInt(recipe.GetColorMaterial()), setNativeSize: true, recipe._dir, recipe.idSkin);
            }
        }
    }
References Recipe._dir, RenderRow.GetColorInt(), Recipe.GetColorMaterial(), Recipe.idSkin, imageIcon, Recipe.ingredients, listVariations, recipe, UIList.Redraw(), Recipe.renderRow, RenderRow.SetImage(), Recipe.UseStock, and Recipe.VirtualBlock.
Referenced by OnRotate(), Refresh(), and DropdownGrid.TrySelect().
RefreshList()
void UIRecipeInfo.RefreshList () inline
Definition at line 398 of file UIRecipeInfo.cs.
    {
        if ((bool)textReqSkill)
        {
            string str = "";
            FontColor c = FontColor.Good;
            if (recipe != null)
            {
                Element reqSkill = recipe.source.GetReqSkill();
                int value = EMono.pc.elements.GetOrCreateElement(reqSkill).Value;
                _ = reqSkill.Name + " " + reqSkill.Value;
                str = "reqSkill2".lang(reqSkill.Name, reqSkill.Value.ToString() ?? "", value.ToString() ?? "");
                if (value < reqSkill.Value)
                {
                    c = FontColor.Warning;
                }
            }
            textReqSkill.SetText(str.IsEmpty("noReqSkill".lang()), c);
        }
        if ((bool)ddFactory)
        {
            List<GridItem> list = new List<GridItem>();
            if (recipe.source.NeedFactory)
            {
                GridItemCardSource gridItemCardSource = new GridItemCardSource
                {
                    source = EMono.sources.cards.map[recipe.source.idFactory]
                };
                if (factory != null && recipe.source.idFactory == factory.id)
                {
                    gridItemCardSource.thing = factory;
                }
                list.Add(gridItemCardSource);
            }
            ddFactory.Build(list);
        }
        RefreshQuality();
        if ((bool)ddList)
        {
            ddList.SetActive(recipe != null && !recipe.UseStock);
            if (recipe != null && !recipe.UseStock)
            {
                ddList.recipeInfo = this;
                ddList.lastMats = lastMats;
                ddList.BuildIngredients(recipe, imageIcon, RefreshQuality, searchMode);
            }
            return;
        }
        Recipe r = recipe;
        UIList uIList = listIngredients;
        uIList.Clear();
        dds.Clear();
        if (r == null || r.UseStock)
        {
            return;
        }
        uIList.callbacks = new UIList.Callback<Recipe.Ingredient, UIItem>
        {
            onClick = delegate
            {
            },
            onInstantiate = delegate(Recipe.Ingredient ingredient, UIItem b)
            {
                DropdownRecipe dropdownRecipe = b.dd as DropdownRecipe;
                dropdownRecipe.recipe = r;
                dds.Add(dropdownRecipe);
                ThingStack thingStack = EMono._map.Stocked.ListThingStack(ingredient, searchMode);
                int num = thingStack.count;
                Color color = ((num >= ingredient.req) ? SkinManager.CurrentColors.textGood : SkinManager.CurrentColors.textBad);
                dropdownRecipe.SetList(0, new List<string> { ingredient.id }, (string n, int i) => "<color=" + color.ToHex() + ">" + ingredient.GetName() + " x " + ingredient.req + "  (" + num + ")</color>", delegate
                {
                });
                dropdownRecipe.textLabel.text = dropdownRecipe.orgLabel.text;
                if ((bool)textCost)
                {
                    textCost.text = r.CostMoney.ToString() ?? "";
                }
            }
        };
        foreach (Recipe.Ingredient ingredient in r.ingredients)
        {
            uIList.Add(ingredient);
        }
        uIList.Refresh();
    }
References EMono._map, UIList.Add(), Card.Add(), DropdownGrid.Build(), DropdownGrid.BuildIngredients(), SourceManager.cards, UIList.Clear(), Color, Recipe.CostMoney, ThingStack.count, SkinManager.CurrentColors, ddFactory, ddList, dds, Card.elements, factory, ElementContainer.GetOrCreateElement(), RecipeSource.GetReqSkill(), Card.id, RecipeSource.idFactory, imageIcon, Recipe.ingredients, lastMats, listIngredients, Props.ListThingStack(), SourceCard.map, Element.Name, RecipeSource.NeedFactory, DropdownRecipe.orgLabel, EMono.pc, recipe, UIList.Refresh(), RefreshQuality(), searchMode, UIText.SetText(), Recipe.source, EMono.sources, Map.Stocked, SkinColorProfile.textBad, textCost, SkinColorProfile.textGood, textReqSkill, Recipe.UseStock, and Element.Value.
Referenced by Clear(), Refresh(), and SetArea().
RefreshQuality()
void UIRecipeInfo.RefreshQuality () inline
Definition at line 390 of file UIRecipeInfo.cs.
    {
        if ((bool)textQuality)
        {
            recipe.SetTextDifficulty(textQuality);
        }
    }
References recipe, Recipe.SetTextDifficulty(), and textQuality.
Referenced by RefreshList().
SetArea()
void UIRecipeInfo.SetArea (Area a) inline
Definition at line 86 of file UIRecipeInfo.cs.
    {
        if (a == null)
        {
            Clear();
            return;
        }
        if (main)
        {
            goInfo.SetActive(value: true);
            goIngredients.SetActive(value: false);
        }
        if (area != a)
        {
            area = a;
            recipe = null;
            textName.text = a.Name;
            textDetail.SetActive(enable: true);
            textDetail.SetText(a.source.GetDetail());
            note.Clear();
            note.Build();
            if (!main)
            {
                listIngredients.SetActive(enable: false);
            }
            RefreshList();
            if ((bool)imageArea)
            {
                imageArea.SetActive(enable: true);
            }
            if ((bool)listVariations)
            {
                listVariations.SetActive(enable: false);
            }
            this.SetActive(enable: true);
            this.RebuildLayout(recursive: true);
        }
    }
References area, UINote.Build(), UINote.Clear(), Clear(), goInfo, goIngredients, imageArea, listIngredients, listVariations, main, BaseArea.Name, note, recipe, RefreshList(), UIText.SetText(), BaseArea.source, and textDetail.
Referenced by BuildMenu.Refresh(), and BuildMenu.RefreshCategoryArea().
SetRecipe()
void UIRecipeInfo.SetRecipe (Recipe r) inline
Definition at line 125 of file UIRecipeInfo.cs.
    {
        if ((bool)imageArea)
        {
            imageArea.SetActive(enable: false);
        }
        area = null;
        if (r == null)
        {
            textDetail.SetActive(enable: false);
            Clear();
            return;
        }
        if (main)
        {
            goInfo.SetActive(value: true);
            goIngredients.SetActive(r.ingredients.Count > 0 && !r.UseStock);
        }
        if (recipe != r)
        {
            recipe = r;
            Refresh();
        }
    }
References area, Clear(), goInfo, goIngredients, imageArea, Recipe.ingredients, main, recipe, Refresh(), textDetail, and Recipe.UseStock.
Referenced by Init(), BuildMenu.Refresh(), BuildMenu.RefreshCategory(), LayerCraft.RefreshRecipe(), and BuildMenu.Unselect().
Member Data Documentation
area
Area UIRecipeInfo.area
Definition at line 34 of file UIRecipeInfo.cs.
Referenced by Clear(), BuildMenu.RefreshCategoryArea(), SetArea(), and SetRecipe().
buttonProduct
ButtonGrid UIRecipeInfo.buttonProduct
Definition at line 66 of file UIRecipeInfo.cs.
Referenced by LayerCraft.RefreshProduct().
colorCost
Color UIRecipeInfo.colorCost
Definition at line 46 of file UIRecipeInfo.cs.
Referenced by Init(), and RefreshBalance().
colorPredict
Color UIRecipeInfo.colorPredict
Definition at line 48 of file UIRecipeInfo.cs.
Referenced by Init().
CraftMode
bool UIRecipeInfo.CraftMode
Definition at line 58 of file UIRecipeInfo.cs.
Referenced by Refresh().
ddFactory
DropdownGrid UIRecipeInfo.ddFactory
Definition at line 64 of file UIRecipeInfo.cs.
Referenced by RefreshList().
ddList
DropdownGrid UIRecipeInfo.ddList
Definition at line 62 of file UIRecipeInfo.cs.
Referenced by LayerCraft.OnAfterInit(), RefreshBalance(), and RefreshList().
dds
List<DropdownRecipe> UIRecipeInfo.dds = new List<DropdownRecipe>()
Definition at line 75 of file UIRecipeInfo.cs.
Referenced by RefreshBalance(), and RefreshList().
factory
Thing UIRecipeInfo.factory
Definition at line 30 of file UIRecipeInfo.cs.
Referenced by RefreshList().
goInfo
GameObject UIRecipeInfo.goInfo
Definition at line 54 of file UIRecipeInfo.cs.
Referenced by Clear(), SetArea(), and SetRecipe().
goIngredients
GameObject UIRecipeInfo.goIngredients
Definition at line 52 of file UIRecipeInfo.cs.
Referenced by Clear(), SetArea(), and SetRecipe().
goMoney
GameObject UIRecipeInfo.goMoney
Definition at line 50 of file UIRecipeInfo.cs.
Referenced by Refresh().
hideMode
bool UIRecipeInfo.hideMode = true
Definition at line 72 of file UIRecipeInfo.cs.
Referenced by BuildMenu.Refresh().
imageArea
Image UIRecipeInfo.imageArea
Definition at line 40 of file UIRecipeInfo.cs.
Referenced by Clear(), SetArea(), and SetRecipe().
imageIcon
Image UIRecipeInfo.imageIcon
Definition at line 42 of file UIRecipeInfo.cs.
Referenced by RefreshImages(), and RefreshList().
lastMats
Dictionary<string, int> UIRecipeInfo.lastMats = new Dictionary<string, int>()
Definition at line 69 of file UIRecipeInfo.cs.
Referenced by HitSummary.Execute(), RefreshList(), and BuildMenu.Select().
listIngredients
UIList UIRecipeInfo.listIngredients
Definition at line 36 of file UIRecipeInfo.cs.
Referenced by Refresh(), RefreshList(), and SetArea().
listVariations
UIList UIRecipeInfo.listVariations
Definition at line 38 of file UIRecipeInfo.cs.
Referenced by Clear(), OnRotate(), Refresh(), RefreshImages(), and SetArea().
main
bool UIRecipeInfo.main
Definition at line 56 of file UIRecipeInfo.cs.
Referenced by Clear(), Refresh(), RefreshBalance(), SetArea(), and SetRecipe().
note
UINote UIRecipeInfo.note
Definition at line 44 of file UIRecipeInfo.cs.
Referenced by Clear(), Refresh(), LayerCraft.RefreshProduct(), and SetArea().
recipe
Recipe UIRecipeInfo.recipe
Definition at line 32 of file UIRecipeInfo.cs.
Referenced by Clear(), OnRotate(), Refresh(), RefreshBalance(), BuildMenu.RefreshCategory(), RefreshImages(), RefreshList(), RefreshQuality(), LayerCraft.RefreshRecipe(), SetArea(), and SetRecipe().
searchMode
StockSearchMode UIRecipeInfo.searchMode
Definition at line 60 of file UIRecipeInfo.cs.
Referenced by RefreshList().
textCost
UIText UIRecipeInfo.textCost
Definition at line 20 of file UIRecipeInfo.cs.
Referenced by RefreshBalance(), and RefreshList().
textCostSP
UIText UIRecipeInfo.textCostSP
Definition at line 28 of file UIRecipeInfo.cs.
Referenced by RefreshBalance().
textDetail
UIText UIRecipeInfo.textDetail
Definition at line 18 of file UIRecipeInfo.cs.
Referenced by Refresh(), SetArea(), and SetRecipe().
textInfo
UIText UIRecipeInfo.textInfo
Definition at line 22 of file UIRecipeInfo.cs.
Referenced by Refresh().
textName
UIText UIRecipeInfo.textName
Definition at line 16 of file UIRecipeInfo.cs.
Referenced by Clear().
textQuality
UIText UIRecipeInfo.textQuality
Definition at line 24 of file UIRecipeInfo.cs.
Referenced by RefreshQuality().
textReqSkill
UIText UIRecipeInfo.textReqSkill
Definition at line 26 of file UIRecipeInfo.cs.
Referenced by RefreshList().
Property Documentation
summary
HitSummary UIRecipeInfo.summary get
Definition at line 77 of file UIRecipeInfo.cs.
Referenced by RefreshBalance().
The documentation for this class was generated from the following file:
Elin/UIRecipeInfo.cs