Elin Decompiled Documentation: LayerInteraction.Page Class Reference
LayerInteraction.Page Class Reference
Public Member Functions
Item Add (object target, string text, string idSprite, Action action, int priority=0, bool auto=false)
Item Add (object target, string text, Func< bool > valueFunc, Action< bool > action)
Public Attributes
UIButton button
Area area
List< Item > items = new List<Item>()
Detailed Description
Definition at line 16 of file LayerInteraction.cs.
Member Function Documentation
Add() [1/2]
Item LayerInteraction.Page.Add (object target, string text, Func< bool > valueFunc, Action< bool > action) inline
Definition at line 39 of file LayerInteraction.cs.
        {
            Action action2 = delegate
            {
                SE.Click();
                action(!valueFunc());
            };
            Item item = new Item
            {
                target = target,
                textFunc = () => text.lang() + " (" + (valueFunc() ? "on" : "off") + ")",
                action = action2,
                reload = true
            };
            items.Add(item);
            return item;
        }
References item, and LayerInteraction.Page.items.
Add() [2/2]
Item LayerInteraction.Page.Add (object target, string text, string idSprite, Action action, int priority = 0, bool auto = false) inline
Definition at line 24 of file LayerInteraction.cs.
        {
            Item item = new Item
            {
                target = target,
                text = text,
                idSprite = idSprite,
                action = action,
                priority = priority,
                auto = auto
            };
            items.Add(item);
            return item;
        }
References item, and LayerInteraction.Page.items.
Referenced by LayerInteraction.GetPage(), and LayerInteraction.Show().
Member Data Documentation
area
Area LayerInteraction.Page.area
Definition at line 20 of file LayerInteraction.cs.
button
UIButton LayerInteraction.Page.button
Definition at line 18 of file LayerInteraction.cs.
Referenced by LayerInteraction.Show().
items
List<Item> LayerInteraction.Page.items = new List<Item>()
Definition at line 22 of file LayerInteraction.cs.
Referenced by LayerInteraction.Page.Add(), LayerInteraction.GetPage(), and LayerInteraction.Show().
The documentation for this class was generated from the following file:
Elin/LayerInteraction.cs