Elin Decompiled Documentation: PoolManager Class Reference
PoolManager Class Reference
Classes
class PoolGroup
Public Member Functions
PoolGroup CreateGroup (string id, Transform original)
PoolGroup CreateGroup (string id, string path)
Static Public Member Functions
static T Spawn< T > (T original, Component parent=null)
static T Spawn< T > (string id, string path, Transform parent=null)
static Transform Spawn (string id, string path, Transform parent)
static PoolGroup GetGroup (string id)
static void Despawn (Component c)
static bool TryDespawn (Component c)
static void DespawnOrDestroy (Component c)
Public Attributes
Dictionary< string, PoolGroup > groups
Dictionary< int, PoolGroup > spawnedList
Static Public Attributes
static PoolManager current
static Transform _trans
static bool ignorePool
Private Member Functions
void Awake ()
Transform _Spawn (string id, string path, Transform parent)
Transform _Spawn (string id, Transform original, Transform parent)
Detailed Description
Definition at line 4 of file PoolManager.cs.
Member Function Documentation
_Spawn() [1/2]
Transform PoolManager._Spawn (string id, string path, Transform parent) inline private
Definition at line 96 of file PoolManager.cs.
    {
        PoolGroup poolGroup = groups.TryGetValue(id);
        if (poolGroup == null)
        {
            poolGroup = CreateGroup(id, path);
        }
        return poolGroup.Spawn(parent);
    }
References CreateGroup(), groups, and PoolManager.PoolGroup.Spawn().
Referenced by Spawn(), and Spawn< T >().
_Spawn() [2/2]
Transform PoolManager._Spawn (string id, Transform original, Transform parent) inline private
Definition at line 106 of file PoolManager.cs.
    {
        PoolGroup poolGroup = groups.TryGetValue(id);
        if (poolGroup == null)
        {
            poolGroup = CreateGroup(id, original);
        }
        return poolGroup.Spawn(parent);
    }
References CreateGroup(), groups, and PoolManager.PoolGroup.Spawn().
Awake()
void PoolManager.Awake () inline private
Definition at line 67 of file PoolManager.cs.
    {
        current = this;
        _trans = base.transform;
        spawnedList = new Dictionary<int, PoolGroup>();
        groups = new Dictionary<string, PoolGroup>();
        base.gameObject.SetActive(value: false);
    }
References _trans, current, groups, and spawnedList.
CreateGroup() [1/2]
PoolGroup PoolManager.CreateGroup (string id, string path) inline
Definition at line 123 of file PoolManager.cs.
    {
        return CreateGroup(id, Resources.Load<Transform>(path));
    }
References CreateGroup().
CreateGroup() [2/2]
PoolGroup PoolManager.CreateGroup (string id, Transform original) inline
Definition at line 116 of file PoolManager.cs.
    {
        PoolGroup poolGroup = new PoolGroup(original, this, id);
        groups.Add(id, poolGroup);
        return poolGroup;
    }
References groups.
Referenced by _Spawn(), and CreateGroup().
Despawn()
static void PoolManager.Despawn (Component c) inline static
Definition at line 128 of file PoolManager.cs.
    {
        if (Application.isPlaying)
        {
            if (ignorePool)
            {
                Object.Destroy(c.gameObject);
            }
            else
            {
                current.spawnedList[c.transform.GetHashCode()].Despawn(c.transform);
            }
        }
    }
References current, ignorePool, and spawnedList.
Referenced by MsgBox.AddLog(), MsgBox.Clear(), ActionMode.ClearSimpleTexts(), TaskDesignation.DespawnOrbit(), CardRenderer.DespawnSimpleText(), ButtonGrid.Dettach(), CardActor.Kill(), TC.Kill(), PopperManager.Kill(), CardRenderer.OnLeaveScreen(), and ButtonGrid.Reset().
DespawnOrDestroy()
static void PoolManager.DespawnOrDestroy (Component c) inline static
Definition at line 158 of file PoolManager.cs.
    {
        if (ignorePool || !TryDespawn(c))
        {
            Object.Destroy(c.gameObject);
        }
    }
References ignorePool, and TryDespawn().
Referenced by Effect.Kill(), MsgBlock.Reset(), and MsgLine.Reset().
GetGroup()
static PoolGroup PoolManager.GetGroup (string id) inline static
Definition at line 91 of file PoolManager.cs.
    {
        return current.groups[id];
    }
References current, and groups.
Spawn()
static Transform PoolManager.Spawn (string id, string path, Transform parent) inline static
Definition at line 86 of file PoolManager.cs.
    {
        return current._Spawn(id, path, parent);
    }
References _Spawn(), and current.
Referenced by CardRenderer.AddExtra(), MsgBlock.Append(), MsgLine.Append(), ButtonGrid.Attach(), RenderDataCard.CreateActor(), MsgBox.CreateNewBlock(), DynamicAsset< T >.GetNew(), UIList.Callback< T1, T2 >.Instantiate(), CardRenderer.OnEnterScreen(), PopperManager.Pop(), CharaRenderer.RefreshStateIcon(), CardRenderer.Say(), CardRenderer.SetCensored(), CardRenderer.ShowEmo(), TCSimpleText.Spawn(), TCSimpleText.SpawnIcon(), CardRenderer.SpawnSimpleText(), CardRenderer.TrySpawnOrbit(), and TaskDesignation.TrySpawnOrbit().
Spawn< T >() [1/2]
static T PoolManager.Spawn< T > (string id, string path, Transform parent = null) inline static
Definition at line 81 of file PoolManager.cs.
    {
        return current._Spawn(id, path, parent).GetComponent<T>();
    }
References _Spawn(), and current.
Spawn< T >() [2/2]
static T PoolManager.Spawn< T > (T original, Component parent = null) inline static
Type Constraints
T : Component
Definition at line 76 of file PoolManager.cs.
                                                                          : Component
    {
        return current._Spawn(original.name, original.transform, parent?.transform).GetComponent<T>();
    }
References _Spawn(), and current.
TryDespawn()
static bool PoolManager.TryDespawn (Component c) inline static
Definition at line 143 of file PoolManager.cs.
    {
        if (ignorePool)
        {
            return false;
        }
        PoolGroup poolGroup = current.spawnedList.TryGetValue(c.transform.GetHashCode());
        if (poolGroup == null)
        {
            return false;
        }
        poolGroup.Despawn(c.transform);
        return true;
    }
References current, PoolManager.PoolGroup.Despawn(), ignorePool, and spawnedList.
Referenced by UIList.ClearChildren(), and DespawnOrDestroy().
Member Data Documentation
_trans
Transform PoolManager._trans static
Definition at line 59 of file PoolManager.cs.
Referenced by Awake().
current
PoolManager PoolManager.current static
Definition at line 57 of file PoolManager.cs.
Referenced by Awake(), Despawn(), GetGroup(), Spawn(), PoolManager.PoolGroup.Spawn(), Spawn< T >(), and TryDespawn().
groups
Dictionary<string, PoolGroup> PoolManager.groups
Definition at line 63 of file PoolManager.cs.
Referenced by _Spawn(), Awake(), CreateGroup(), and GetGroup().
ignorePool
bool PoolManager.ignorePool static
Definition at line 61 of file PoolManager.cs.
Referenced by Despawn(), DespawnOrDestroy(), PoolManager.PoolGroup.Spawn(), and TryDespawn().
spawnedList
Dictionary<int, PoolGroup> PoolManager.spawnedList
Definition at line 65 of file PoolManager.cs.
Referenced by Awake(), Despawn(), PoolManager.PoolGroup.Spawn(), and TryDespawn().
The documentation for this class was generated from the following file:
Elin/Plugins.basecore/PoolManager.cs