Elin Decompiled Documentation: InvOwnerHotbar Class Reference
InvOwnerHotbar Class Reference
Public Member Functions
InvOwnerHotbar (Card owner, Card container=null, CurrencyType _currency=CurrencyType.None)
override void OnClick (ButtonGrid button)
override void OnRightClick (ButtonGrid button)
override void OnRightPressed (ButtonGrid button)
override void OnProcess (Thing t)
Public Member Functions inherited from InvOwner
virtual bool AllowHold (Thing t)
virtual bool AllowMoved (Thing t)
virtual bool ShouldShowGuide (Thing t)
virtual bool AllowDrop (Thing t)
virtual Thing CreateDefaultContainer ()
virtual void BuildUICurrency (UICurrency uiCurrency, bool canReroll=false)
bool IsWeightOver (Thing t)
InvOwner (Card owner, Card container=null, CurrencyType _currency=CurrencyType.None, PriceType _price=PriceType.Default)
void Init ()
virtual void OnInit ()
virtual void OnClick (ButtonGrid button)
virtual void OnRightClick (ButtonGrid button)
virtual void OnRightPressed (ButtonGrid button)
InvOwner GetShitDestOwner (ButtonGrid b, bool rightMouse=false)
virtual void OnShiftClick (ButtonGrid b, bool rightMouse=false)
virtual bool CanShiftClick (ButtonGrid b, bool rightMouse=false)
virtual string GetTextShiftClick (ButtonGrid b)
virtual void OnCtrlClick (ButtonGrid button)
virtual bool CanCtrlClick (ButtonGrid b)
virtual string GetTextCtrlClick (ButtonGrid b)
virtual void OnAltClick (ButtonGrid button)
virtual bool CanAltClick (ButtonGrid b)
virtual string GetTextAltClick (ButtonGrid b)
void Grab (DragItemCard.DragInfo from)
Thing PutBack (DragItemCard.DragInfo from)
void OnStartDrag (DragItemCard.DragInfo from)
virtual bool OnCancelDrag (DragItemCard.DragInfo from)
virtual bool OnDrag (DragItemCard.DragInfo from, DragItemCard.DragInfo to, bool execute, bool cancel=false)
virtual void OnProcess (Thing t)
bool CanOpenContainer (Thing t)
ListInteraction ListInteractions (ButtonGrid b, bool context)
bool TryHold (Thing t)
virtual void ListInteractions (ListInteraction list, Thing t, Trait trait, ButtonGrid b, bool context)
virtual string GetAutoUseLang (ButtonGrid button)
void AutoUse (ButtonGrid button, bool repeat=false)
void ShowContextMenu (ButtonGrid button)
virtual int GetPrice (Thing t, CurrencyType currency, int num, bool sell)
virtual string GetTextDetail (Thing t, CurrencyType currency, int num, bool sell)
virtual void OnWriteNote (ButtonGrid button, UINote n)
virtual string IDCostIcon (Thing t)
virtual bool IsFailByCurse (Thing t)
Public Attributes
int index
Public Attributes inherited from InvOwner
bool includeChildren
CurrencyType currency
PriceType priceType
HomeResource homeResource
Card owner
Card Container
List< ButtonGrid > buttons = new List<ButtonGrid>()
Properties
override bool AllowAutouse [get]
override int destInvY [get]
Properties inherited from InvOwner
static bool HasTrader [get]
static bool FreeTransfer [get]
virtual bool AllowAutouse [get]
virtual bool AllowContext [get]
virtual bool AllowSell [get]
virtual bool AlwaysShowTooltip [get]
virtual bool UseGuide [get]
virtual bool AllowTransfer [get]
virtual bool AllowDropOnDrag [get]
virtual string langTransfer [get]
virtual int destInvY [get]
virtual bool HasTransaction [get]
virtual bool CopyOnTransfer [get]
virtual bool SingleTarget [get]
bool UseHomeResource [get]
bool IsMagicChest [get]
List< Thing > Things [get]
Chara Chara [get]
ContainerType ContainerType [get]
virtual bool InvertSell [get]
virtual int numDragGrid [get]
virtual bool ShowNew [get]
virtual bool DenyImportant [get]
InvOwner destInvOwner [get]
string IDCurrency [get]
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Additional Inherited Members
Static Public Member Functions inherited from EClass
static int rnd (int a)
static int curve (int a, int start, int step, int rate=75)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Static Public Attributes inherited from InvOwner
static ForceGiveData forceGive = new ForceGiveData()
static InvOwner Trader
static InvOwner Main
static float clickTimer
Static Public Attributes inherited from EClass
static Core core
Detailed Description
Definition at line 1 of file InvOwnerHotbar.cs.
Constructor & Destructor Documentation
InvOwnerHotbar()
InvOwnerHotbar.InvOwnerHotbar (Card owner, Card container = null, CurrencyType _currency = CurrencyType::None) inline
Definition at line 19 of file InvOwnerHotbar.cs.
        : base(owner, container, _currency)
    {
    }
Member Function Documentation
OnClick()
override void InvOwnerHotbar.OnClick (ButtonGrid button) inline virtual
Reimplemented from InvOwner.
Definition at line 24 of file InvOwnerHotbar.cs.
    {
        if ((bool)EClass.ui.layerFloat.GetLayer<LayerInventory>())
        {
            base.OnClick(button);
            return;
        }
        SE.SelectHotitem();
        WidgetCurrentTool.Instance.Select(index % 10);
    }
References index, WidgetCurrentTool.Instance, UI.layerFloat, WidgetCurrentTool.Select(), and EClass.ui.
OnProcess()
override void InvOwnerHotbar.OnProcess (Thing t) inline virtual
Reimplemented from InvOwner.
Definition at line 50 of file InvOwnerHotbar.cs.
    {
        if (WidgetCurrentTool.Instance.selected == index)
        {
            WidgetCurrentTool.Instance.Reselect();
        }
        if (!EClass.player.flags.toggleHotbarHighlightActivated && (bool)WidgetCurrentTool.Instance)
        {
            WidgetCurrentTool.Instance.transHighlightSwitch.SetActive(enable: true);
            EClass.player.flags.toggleHotbarHighlightActivated = true;
            EClass.player.flags.toggleHotbarHighlightDisabled = false;
        }
    }
References Player.flags, index, WidgetCurrentTool.Instance, EClass.player, WidgetCurrentTool.Reselect(), WidgetCurrentTool.selected, Player.Flags.toggleHotbarHighlightActivated, and WidgetCurrentTool.transHighlightSwitch.
OnRightClick()
override void InvOwnerHotbar.OnRightClick (ButtonGrid button) inline virtual
Reimplemented from InvOwner.
Definition at line 35 of file InvOwnerHotbar.cs.
    {
        if (AllowAutouse)
        {
            base.OnRightClick(button);
            return;
        }
        SE.SelectHotitem();
        WidgetCurrentTool.Instance.Select(index % 10);
    }
References AllowAutouse, index, WidgetCurrentTool.Instance, and WidgetCurrentTool.Select().
OnRightPressed()
override void InvOwnerHotbar.OnRightPressed (ButtonGrid button) inline virtual
Reimplemented from InvOwner.
Definition at line 46 of file InvOwnerHotbar.cs.
    {
    }
Member Data Documentation
index
int InvOwnerHotbar.index
Definition at line 3 of file InvOwnerHotbar.cs.
Referenced by OnClick(), OnProcess(), and OnRightClick().
Property Documentation
AllowAutouse
override bool InvOwnerHotbar.AllowAutouse get
Definition at line 5 of file InvOwnerHotbar.cs.
    {
        get
        {
            if (InvOwner.Trader != null)
            {
                return InvOwner.Trader.UseGuide;
            }
            return false;
        }
    }
Referenced by OnRightClick().
destInvY
override int InvOwnerHotbar.destInvY get
Definition at line 17 of file InvOwnerHotbar.cs.
The documentation for this class was generated from the following file:
Elin/InvOwnerHotbar.cs