Elin Decompiled Documentation: Empyrean.ColorPicker.SliderBackgroundController Class Reference
Empyrean.ColorPicker.SliderBackgroundController Class Reference
Public Member Functions
void Init (LabeledColorSlider parent)
void ToggleSliderMode ()
Private Member Functions
void Awake ()
void UpdateBackround (Color color)
void GenerateSliderTexture ()
Color[] GenerateColorSpectrum ()
Color GetColorByTypeAndIndex (int index)
IEnumerator DelayedUpdateBg ()
Private Attributes
ColorPicker colorPicker
RawImage sliderBackground
LabeledColorSlider parent
Color[] colorArray
Detailed Description
Definition at line 8 of file SliderBackgroundController.cs.
Member Function Documentation
Awake()
void Empyrean.ColorPicker.SliderBackgroundController.Awake () inline private
Definition at line 20 of file SliderBackgroundController.cs.
    {
        colorPicker.ColorUpdated += UpdateBackround;
    }
References Empyrean.ColorPicker.SliderBackgroundController.UpdateBackround().
DelayedUpdateBg()
IEnumerator Empyrean.ColorPicker.SliderBackgroundController.DelayedUpdateBg () inline private
Definition at line 87 of file SliderBackgroundController.cs.
    {
        yield return null;
        UpdateBackround(colorPicker.SelectedColor);
    }
References Empyrean.ColorPicker.SliderBackgroundController.colorPicker, Empyrean.ColorPicker.ColorPicker.SelectedColor, and Empyrean.ColorPicker.SliderBackgroundController.UpdateBackround().
Referenced by Empyrean.ColorPicker.SliderBackgroundController.ToggleSliderMode().
GenerateColorSpectrum()
Color[] Empyrean.ColorPicker.SliderBackgroundController.GenerateColorSpectrum () inline private
Definition at line 42 of file SliderBackgroundController.cs.
    {
        Color[] array = new Color[256];
        for (int i = 0; i < 256; i++)
        {
            array[i] = GetColorByTypeAndIndex(i);
        }
        return array;
    }
References Color, and Empyrean.ColorPicker.SliderBackgroundController.GetColorByTypeAndIndex().
Referenced by Empyrean.ColorPicker.SliderBackgroundController.GenerateSliderTexture().
GenerateSliderTexture()
void Empyrean.ColorPicker.SliderBackgroundController.GenerateSliderTexture () inline private
Definition at line 30 of file SliderBackgroundController.cs.
    {
        Color[] array = ((parent.Type == SliderType.Hue) ? HueSlider.GenerateHsvSpectrum() : GenerateColorSpectrum());
        Texture2D texture2D = new Texture2D(array.Length, 1);
        for (int i = 0; i < texture2D.width; i++)
        {
            texture2D.SetPixel(i, 1, array[i]);
        }
        texture2D.Apply();
        sliderBackground.texture = texture2D;
    }
References Color, Empyrean.ColorPicker.SliderBackgroundController.GenerateColorSpectrum(), and Empyrean.ColorPicker.HueSlider.GenerateHsvSpectrum().
Referenced by Empyrean.ColorPicker.SliderBackgroundController.UpdateBackround().
GetColorByTypeAndIndex()
Color Empyrean.ColorPicker.SliderBackgroundController.GetColorByTypeAndIndex (int index) inline private
Definition at line 52 of file SliderBackgroundController.cs.
    {
        Color selectedColor = colorPicker.SelectedColor;
        switch (parent.Type)
        {
        case SliderType.Red:
            return new Color((float)index / 255f, selectedColor.g, selectedColor.b, 1f);
        case SliderType.Green:
            return new Color(selectedColor.r, (float)index / 255f, selectedColor.b, 1f);
        case SliderType.Blue:
            return new Color(selectedColor.r, selectedColor.g, (float)index / 255f, 1f);
        case SliderType.Sat:
        {
            float v = ((colorPicker.ValueHSV >= 0.3f) ? colorPicker.ValueHSV : 0.3f);
            return new HSVColor(colorPicker.Hue, (float)index / 255f, v).ToRGB();
        }
        case SliderType.Val:
            return new HSVColor(colorPicker.Hue, colorPicker.Saturation, (float)index / 255f).ToRGB();
        case SliderType.Alpha:
            return new Color(1f, 1f, 1f, (float)index / 255f);
        default:
            return Color.red;
        }
    }
References Color, Empyrean.ColorPicker.SliderBackgroundController.colorPicker, Empyrean.ColorPicker.ColorPicker.Hue, Empyrean.ColorPicker.SliderBackgroundController.parent, Empyrean.ColorPicker.ColorPicker.Saturation, Empyrean.ColorPicker.ColorPicker.SelectedColor, Empyrean.ColorPicker.LabeledColorSlider.Type, and Empyrean.ColorPicker.ColorPicker.ValueHSV.
Referenced by Empyrean.ColorPicker.SliderBackgroundController.GenerateColorSpectrum().
Init()
void Empyrean.ColorPicker.SliderBackgroundController.Init (LabeledColorSlider parent) inline
Definition at line 77 of file SliderBackgroundController.cs.
    {
        this.parent = parent;
    }
References Empyrean.ColorPicker.SliderBackgroundController.parent.
Referenced by Empyrean.ColorPicker.LabeledColorSlider.Awake().
ToggleSliderMode()
void Empyrean.ColorPicker.SliderBackgroundController.ToggleSliderMode () inline
Definition at line 82 of file SliderBackgroundController.cs.
    {
        StartCoroutine(DelayedUpdateBg());
    }
References Empyrean.ColorPicker.SliderBackgroundController.DelayedUpdateBg().
Referenced by Empyrean.ColorPicker.LabeledColorSlider.ToggleSliderMode().
UpdateBackround()
void Empyrean.ColorPicker.SliderBackgroundController.UpdateBackround (Color color) inline private
Definition at line 25 of file SliderBackgroundController.cs.
    {
        GenerateSliderTexture();
    }
References Empyrean.ColorPicker.SliderBackgroundController.GenerateSliderTexture().
Referenced by Empyrean.ColorPicker.SliderBackgroundController.Awake(), and Empyrean.ColorPicker.SliderBackgroundController.DelayedUpdateBg().
Member Data Documentation
colorArray
Color [] Empyrean.ColorPicker.SliderBackgroundController.colorArray private
Definition at line 18 of file SliderBackgroundController.cs.
colorPicker
ColorPicker Empyrean.ColorPicker.SliderBackgroundController.colorPicker private
Definition at line 11 of file SliderBackgroundController.cs.
Referenced by Empyrean.ColorPicker.SliderBackgroundController.DelayedUpdateBg(), and Empyrean.ColorPicker.SliderBackgroundController.GetColorByTypeAndIndex().
parent
LabeledColorSlider Empyrean.ColorPicker.SliderBackgroundController.parent private
Definition at line 16 of file SliderBackgroundController.cs.
Referenced by Empyrean.ColorPicker.SliderBackgroundController.GetColorByTypeAndIndex(), and Empyrean.ColorPicker.SliderBackgroundController.Init().
sliderBackground
RawImage Empyrean.ColorPicker.SliderBackgroundController.sliderBackground private
Definition at line 14 of file SliderBackgroundController.cs.
The documentation for this class was generated from the following file:
Elin/Plugins.UI/Empyrean/ColorPicker/SliderBackgroundController.cs