Elin Decompiled Documentation: AM_Terrain Class Reference
AM_Terrain Class Reference
Public Types
enum Mode { Flatten , Up , Down }
Public Member Functions
override int TopHeight (Point p)
override string OnSetSubMenuButton (int a, UIButton b)
override void OnClickSubMenu (int a)
override void OnProcessTiles (Point point, int dir)
Public Member Functions inherited from AM_BaseTerrain
override void SEExecuteSummary ()
override MeshPass GetGuidePass (Point point)
override HitResult HitTest (Point point, Point start)
override void OnRenderTile (Point point, HitResult result, int dir)
override void OnUpdateInput ()
override void OnAfterProcessTiles (Point start, Point end)
Public Member Functions inherited from ActionMode
virtual int TopHeight (Point p)
virtual void SEExecuteSummary ()
virtual bool HighlightWall (Point p)
virtual void OnClickSubMenu (int a)
virtual string OnSetSubMenuButton (int a, UIButton b)
virtual bool IsRoofEditMode (Card c=null)
virtual bool IsFillMode ()
virtual int GetDefaultTile (Point p)
virtual void OnShowExtraHint (UINote n)
void Activate (bool toggle=true, bool forceActivate=false)
virtual void OnActivate ()
void RefreshTexts ()
virtual string GetSimpleText (Card c)
void ClearSimpleTexts ()
void Deactivate ()
virtual void OnDeactivate ()
virtual void OnCancel ()
virtual void OnBeforeUpdate ()
virtual void OnAfterUpdate ()
virtual void OnUpdateCursor ()
void OnRotate ()
void SetCursorOnMap (CursorInfo cursor)
void UpdateInput ()
void InputMovement ()
virtual void InputWheel (int wheel)
virtual void OnUpdateInput ()
void DoFunc (CoreConfig.GameFuncBuild func)
bool IsFuncPressed (CoreConfig.GameFunc func)
void DoFunc (CoreConfig.GameFunc func)
virtual void OnScroll ()
void TryRightClickCloseWidget ()
bool TryShowWidgetMenu ()
HitResult _HitTest (Point point, Point start)
virtual HitResult HitTest (Point point, Point start)
virtual void OnSelectStart (Point point)
virtual void OnSelectEnd (bool cancel)
virtual MeshPass GetGuidePass (Point point)
virtual void OnRenderTile (Point point, HitResult result, int dir)
void OnRenderTileFloor (Point point, HitResult result)
virtual bool CanProcessTiles ()
virtual void OnBeforeProcessTiles ()
virtual void OnProcessTiles (Point point, int dir)
virtual void OnAfterProcessTiles (Point start, Point end)
virtual void OnFinishProcessTiles ()
virtual void OnRefreshSummary (Point point, HitResult result, HitSummary summary)
void ShowLayer ()
virtual Layer OnShowLayer ()
void HideLayer ()
virtual void OnHideLayer ()
virtual string GetHintText ()
virtual void RotateUnderMouse ()
virtual ref string SetMouseInfo (ref string s)
void TogglePause ()
void Pause (bool sound=false)
void UnPause (bool sound=false)
void ChangeGameSpeed (int a, bool sound=false)
Public Attributes
Mode mode
Public Attributes inherited from AM_BaseTerrain
int power = 1
float timer
bool firstClick
Point lastPoint
Public Attributes inherited from ActionMode
Layer layer
int brushRadius = 4
Properties
override int SubMenuModeIndex [get]
override bool FixedPointer [get]
Properties inherited from AM_BaseTerrain
override BaseTileSelector.SelectType selectType [get]
override bool UseSubMenu [get]
override bool UseSubMenuSlider [get]
override bool SubMenuAsGroup [get]
override bool ContinuousClick [get]
override bool IsBuildMode [get]
virtual bool FixedPointer [get]
Properties inherited from AM_BaseTileSelect
override CursorInfo DefaultCursor [get]
override bool enableMouseInfo [get]
override bool ShowMouseoverTarget [get]
override bool CanSelectTile [get]
override AreaHighlightMode AreaHihlight [get]
TaskManager.Designations Designations [get]
override string idSound [get]
override bool AllowMiddleClickFunc [get]
override bool ShowMaskedThings [get]
Properties inherited from ActionMode
static AM_Adv AdvOrRegion [get]
static bool IsAdv [get]
virtual float gameSpeed [get]
bool IsActive [get]
virtual BaseTileSelector.HitType hitType [get]
virtual BaseTileSelector.SelectType selectType [get]
virtual BaseTileSelector.BoxType boxType [get]
virtual bool ContinuousClick [get]
virtual int hitW [get]
virtual int hitH [get]
HitSummary Summary [get]
bool Multisize [get]
virtual string id [get]
virtual CursorInfo DefaultCursor [get]
virtual string idHelpTopic [get]
virtual string idSound [get]
virtual bool enableMouseInfo [get]
virtual bool hideBalloon [get]
virtual string textHintTitle [get]
virtual bool AllowAutoClick [get]
virtual bool ShowActionHint [get]
virtual bool ShowMouseoverTarget [get]
virtual AreaHighlightMode AreaHihlight [get]
virtual bool CanSelectTile [get]
virtual bool CanTargetOutsideBounds [get]
virtual bool ShouldPauseGame [get]
virtual bool FixFocus [get]
virtual bool HideSubWidgets [get]
virtual bool IsBuildMode [get]
virtual bool ShowBuildWidgets [get]
virtual BuildMenu.Mode buildMenuMode [get]
virtual bool ShouldHideBuildMenu [get]
virtual bool CanTargetFog [get]
virtual int CostMoney [get]
virtual bool AllowBuildModeShortcuts [get]
virtual bool AllowMiddleClickFunc [get]
virtual bool AllowHotbar [get]
virtual bool AllowGeneralInput [get]
virtual bool ShowMaskedThings [get]
virtual int SelectorHeight [get]
virtual bool AllowWheelZoom [get]
virtual float TargetZoom [get]
virtual BaseTileMap.CardIconMode cardIconMode [get]
virtual BaseGameScreen TargetGameScreen [get]
virtual bool IsNoMap [get]
virtual bool UseSubMenu [get]
virtual bool UseSubMenuSlider [get]
virtual bool SubMenuAsGroup [get]
virtual int SubMenuModeIndex [get]
virtual bool ShowExtraHint [get]
BaseTileSelector tileSelector [get]
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Additional Inherited Members
Static Public Member Functions inherited from ActionMode
static void OnGameInstantiated ()
Static Public Member Functions inherited from EClass
static int rndSeed (int a, int seed)
static int rnd (long a)
static int rnd (int a)
static int curve (int _a, int start, int step, int rate=75)
static int sqrt (int a)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Static Public Attributes inherited from ActionMode
static ActionMode DefaultMode
static AM_Title Title = new AM_Title()
static AM_Sim Sim
static AM_ViewZone View
static AM_Adv Adv
static AM_Region Region
static AM_ADV_Target AdvTarget
static AM_EloMap EloMap
static AM_Inspect Inspect
static AM_NoMap NoMap
static AM_MiniGame MiniGame
static AM_NewZone NewZone
static AM_Bird Bird
static AM_Mine Mine
static AM_Dig Dig
static AM_Harvest Harvest
static AM_Cut Cut
static AM_StateEditor StateEditor
static AM_Picker Picker
static AM_Copy Copy
static AM_Blueprint Blueprint
static AM_Build Build
static AM_CreateArea CreateArea
static AM_EditArea EditArea
static AM_ExpandArea ExpandArea
static AM_Deconstruct Deconstruct
static AM_Select Select
static AM_RemoveDesignation RemoveDesignation
static AM_ViewMap ViewMap
static AM_Terrain Terrain
static AM_Populate Populate
static AM_EditMarker EditMarker
static AM_Visibility Visibility
static AM_Cinema Cinema
static AM_Paint Paint
static AM_FlagCell FlagCell
static ActionMode LastBuildMode
static SourceMaterial.Row lastEditorMat
static bool ignoreSound
static float[] GameSpeeds = new float[4] { 0f, 1f, 2f, 5f }
static List< TCSimpleText > simpleTexts = new List<TCSimpleText>()
static float hotElementTimer
Static Public Attributes inherited from EClass
static Core core
Static Protected Attributes inherited from ActionMode
static Vector3 mpos
Detailed Description
Definition at line 3 of file AM_Terrain.cs.
Member Enumeration Documentation
Mode
enum AM_Terrain.Mode
Enumerator
Flatten
Up
Down
Definition at line 5 of file AM_Terrain.cs.
    {
        Flatten,
        Up,
        Down
    }
Member Function Documentation
OnClickSubMenu()
override void AM_Terrain.OnClickSubMenu (int a) inline virtual
Reimplemented from ActionMode.
Definition at line 32 of file AM_Terrain.cs.
    {
        mode = a.ToEnum<Mode>();
    }
References mode.
OnProcessTiles()
override void AM_Terrain.OnProcessTiles (Point point, int dir) inline virtual
Reimplemented from ActionMode.
Definition at line 37 of file AM_Terrain.cs.
    {
        if (timer < 0.1f)
        {
            return;
        }
        if (lastPoint != null)
        {
            point = lastPoint;
        }
        else
        {
            lastPoint = new Point(point);
        }
        timer = 0f;
        Cell cell = point.cell;
        EClass._map.ForeachSphere(point.x, point.z, brushRadius, delegate(Point p)
        {
            int num = p.Distance(point);
            if (mode == Mode.Flatten)
            {
                if (p.cell.IsFloorWater != cell.IsFloorWater)
                {
                    return;
                }
                int num2 = p.cell.height - cell.height;
                if (!EInput.isShiftDown)
                {
                    num2 = ((num2 >= 0) ? Mathf.Clamp(brushRadius - num, 1, num2) : Mathf.Clamp((brushRadius - num) * -1, num2, -1));
                }
                p.cell.height -= (byte)num2;
                if (p.cell._bridge != 0)
                {
                    if (p.cell.bridgeHeight - num2 < 0)
                    {
                        p.cell.bridgeHeight = 0;
                    }
                    else
                    {
                        p.cell.bridgeHeight -= (byte)num2;
                    }
                }
            }
            else
            {
                int num3 = brushRadius - num;
                if (EInput.isShiftDown)
                {
                    num3 = 1;
                }
                if (mode == Mode.Down)
                {
                    num3 *= -1;
                }
                if (p.cell.height + num3 < 0)
                {
                    num3 = -p.cell.height;
                }
                else if (p.cell.height + num3 > EClass.setting.maxGenHeight)
                {
                    num3 = EClass.setting.maxGenHeight - p.cell.height;
                }
                p.cell.height += (byte)num3;
                if (p.cell._bridge != 0)
                {
                    if (p.cell.bridgeHeight + num3 < 0)
                    {
                        p.cell.bridgeHeight = 0;
                    }
                    else
                    {
                        p.cell.bridgeHeight += (byte)num3;
                    }
                }
            }
            p.RefreshNeighborTiles();
            if (p.cell.room != null)
            {
                p.cell.room.SetDirty();
            }
        });
    }
References Cell._bridge, EClass._map, ActionMode.brushRadius, Point.cell, Point.Distance(), Map.ForeachSphere(), Cell.height, if(), EInput.isShiftDown, AM_BaseTerrain.lastPoint, mode, AM_BaseTerrain.timer, Point.x, and Point.z.
OnSetSubMenuButton()
override string AM_Terrain.OnSetSubMenuButton (int a, UIButton b) inline virtual
Reimplemented from ActionMode.
Definition at line 23 of file AM_Terrain.cs.
    {
        if (a < 3)
        {
            return "terrain" + a.ToEnum<Mode>();
        }
        return null;
    }
TopHeight()
override int AM_Terrain.TopHeight (Point p) inline virtual
Reimplemented from ActionMode.
Definition at line 18 of file AM_Terrain.cs.
    {
        return p.cell.height;
    }
References Point.cell, and Cell.height.
Member Data Documentation
mode
Mode AM_Terrain.mode
Definition at line 12 of file AM_Terrain.cs.
Referenced by OnClickSubMenu(), and OnProcessTiles().
Property Documentation
FixedPointer
override bool AM_Terrain.FixedPointer get
Definition at line 16 of file AM_Terrain.cs.
SubMenuModeIndex
override int AM_Terrain.SubMenuModeIndex get
Definition at line 14 of file AM_Terrain.cs.
The documentation for this class was generated from the following file:
Elin/AM_Terrain.cs