Elin Decompiled Documentation: SlaverData Class Reference
SlaverData Class Reference
Public Member Functions
void TryRefresh (Chara owner)
Public Attributes
List< Chara > list = new List<Chara>()
int dateRefresh
Additional Inherited Members
Static Public Member Functions inherited from EClass
static int rnd (int a)
static int curve (int a, int start, int step, int rate=75)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Static Public Attributes inherited from EClass
static Core core
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Detailed Description
Definition at line 4 of file SlaverData.cs.
Member Function Documentation
TryRefresh()
void SlaverData.TryRefresh (Chara owner) inline
Definition at line 12 of file SlaverData.cs.
    {
        if (!EClass.world.date.IsExpired(dateRefresh))
        {
            return;
        }
        list.Clear();
        int num = 4 + EClass.rnd(4);
        for (int i = 0; i < num; i++)
        {
            Chara item = ((owner.trait.SlaverType != SlaverType.Animal) ? CharaGen.Create(SpawnListChara.Get("slaver_human", (SourceChara.Row s) => EClass.sources.races.map[s.race].tag.Contains("human")).Select().id) : ((!(EClass._zone is Zone_Yowyn) || EClass.rnd(3) == 0) ? CharaGen.Create(SpawnListChara.Get("slaver_animal", (SourceChara.Row s) => EClass.sources.races.map[s.race].tag.Contains("animal")).Select().id) : CharaGen.Create(SpawnListChara.Get("slaver_horse", (SourceChara.Row s) => s.id == "horse_yowyn").Select().id)));
            list.Add(item);
        }
        dateRefresh = EClass.world.date.GetRaw(168);
        owner.isRestocking = true;
    }
References EClass._zone, CharaGen.Create(), World.date, dateRefresh, SpawnListChara.Get(), Date.GetRaw(), CardRow.id, Date.IsExpired(), list, SourceManager.races, EClass.rnd(), SpawnList.Select(), EClass.sources, and EClass.world.
Referenced by ListPeopleBuySlave.OnCreate().
Member Data Documentation
dateRefresh
int SlaverData.dateRefresh
Definition at line 10 of file SlaverData.cs.
Referenced by Trait.GetRestockedIcon(), Trait.GetTextRestock(), and TryRefresh().
list
List<Chara> SlaverData.list = new List<Chara>()
Definition at line 7 of file SlaverData.cs.
Referenced by ListPeopleBuySlave.OnList(), and TryRefresh().
The documentation for this class was generated from the following file:
Elin/SlaverData.cs