Elin Decompiled Documentation: ZoneEventWedding Class Reference
ZoneEventWedding Class Reference
Public Member Functions
override void OnVisit ()
override void OnLeaveZone ()
override ZoneInstance.Status OnReachTimeLimit ()
Public Member Functions inherited from ZoneEventQuest
void Spawn (int num=1)
void SpawnBoss (bool evolve=false)
void AggroEnemy (int chance=100)
sealed override void OnTickRound ()
virtual void _OnTickRound ()
virtual ZoneInstance.Status OnReachTimeLimit ()
Public Member Functions inherited from ZoneEvent
virtual string GetText ()
void Tick (float delta)
void Init ()
void OnSimulateHour ()
virtual void OnVisit ()
virtual void OnInit ()
virtual void OnFirstTick ()
virtual void OnTick ()
virtual void OnTickRound ()
virtual void OnKill ()
virtual void OnCharaDie (Chara c)
virtual void OnLeaveZone ()
virtual void OnLoad ()
void Kill ()
Public Attributes
int attendees
CharaMassTransfer transfer = new CharaMassTransfer()
Public Attributes inherited from ZoneEventQuest
int uidQuest
List< int > enemies = new List<int>()
Public Attributes inherited from ZoneEvent
float time
int rounds
int hoursElapsed
int minElapsed
Zone zone
bool firstTick = true
Properties
QuestWedding questWedding [get]
override string TextWidgetDate [get]
override int TimeLimit [get]
int MaxAttendee [get]
Properties inherited from ZoneEventQuest
Quest quest [get]
virtual bool WarnBoss [get]
virtual bool CountEnemy [get]
virtual int TimeLimit [get]
Properties inherited from ZoneEvent
SourceQuest.Row source [get]
virtual string id [get]
virtual string TextWidgetDate [get]
virtual float roundInterval [get]
virtual Playlist playlist [get]
virtual bool debugSkip [get]
virtual string RefStr2 [get]
virtual string RefStr3 [get]
virtual int hoursToKill [get]
virtual bool HasReport [get]
string Name [get]
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Additional Inherited Members
Static Public Member Functions inherited from EClass
static int rndSeed (int a, int seed)
static int rnd (long a)
static int rnd (int a)
static int curve (long _a, int start, int step, int rate=75)
static int sqrt (int a)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Static Public Attributes inherited from EClass
static Core core
Detailed Description
Definition at line 6 of file ZoneEventWedding.cs.
Member Function Documentation
OnLeaveZone()
override void ZoneEventWedding.OnLeaveZone () inline virtual
Reimplemented from ZoneEvent.
Definition at line 86 of file ZoneEventWedding.cs.
    {
        transfer.Restore();
    }
References CharaMassTransfer.Restore(), and transfer.
OnReachTimeLimit()
override ZoneInstance.Status ZoneEventWedding.OnReachTimeLimit () inline virtual
Reimplemented from ZoneEventQuest.
Definition at line 91 of file ZoneEventWedding.cs.
    {
        Msg.Say("party_end3");
        return ZoneInstance.Status.Success;
    }
References Msg.Say().
OnVisit()
override void ZoneEventWedding.OnVisit () inline virtual
Reimplemented from ZoneEvent.
Definition at line 22 of file ZoneEventWedding.cs.
    {
        if (EClass.game.isLoading || (EClass.debug.enable && Input.GetKey(KeyCode.LeftShift)))
        {
            return;
        }
        foreach (Thing thing2 in EClass._map.things)
        {
            if (!thing2.isHidden)
            {
                thing2.isNPCProperty = true;
            }
        }
        EClass._zone.SetFieldEffect(10001, 1);
        List<Chara> list = new List<Chara>();
        foreach (Chara value in EClass.game.cards.globalCharas.Values)
        {
            if (!value.isDead && value != EClass.pc && value != questWedding.chara && value.IsPCFaction && value.currentZone != null && value.currentZone.IsPCFaction && value.conSuspend == null && !value.isRestrained && value.pos != null)
            {
                list.Add(value);
            }
        }
        list.Sort((Chara a, Chara b) => Mathf.Abs(b.affinity.value) - Mathf.Abs(a.affinity.value));
        if (list.Count > MaxAttendee)
        {
            list.RemoveRange(MaxAttendee, list.Count - MaxAttendee);
        }
        List<Thing> list2 = new List<Thing>();
        bool flag = EClass.pc.HasElement(1250);
        foreach (Thing thing3 in EClass._map.things)
        {
            if (thing3.HasElement(10))
            {
                thing3.isNPCProperty = false;
                thing3.c_priceFix = -90;
                thing3.SetBool(128, enable: true);
                if (flag)
                {
                    thing3.elements.ModBase(710, 2);
                }
            }
            if (thing3.id == "1321")
            {
                list2.Add(thing3);
            }
        }
        list2.Sort((Thing a, Thing b) => a.pos.index - b.pos.index);
        foreach (Chara item in list)
        {
            if (list2.Count == 0)
            {
                break;
            }
            transfer.Add(item);
            attendees++;
            item.MoveZone(EClass._zone);
            Thing thing = list2.Last();
            list2.Remove(thing);
            item.noMove = false;
            item.turnLastSeen = -100;
            item.MoveImmediate(thing.pos, focus: false);
        }
    }
References EClass._map, EClass._zone, CharaMassTransfer.Add(), Chara.affinity, attendees, Game.cards, Quest.chara, Chara.conSuspend, Chara.currentZone, EClass.debug, Card.elements, CoreDebug.enable, EClass.game, CardManager.globalCharas, Card.HasElement(), Card.id, Point.index, Chara.isDead, Card.isHidden, Game.isLoading, Chara.IsPCFaction, Zone.IsPCFaction, Card.isRestrained, item, MaxAttendee, ElementContainer.ModBase(), EClass.pc, Card.pos, questWedding, BaseCard.SetBool(), Zone.SetFieldEffect(), Map.things, transfer, and Affinity.value.
Member Data Documentation
attendees
int ZoneEventWedding.attendees
Definition at line 9 of file ZoneEventWedding.cs.
Referenced by OnVisit().
transfer
CharaMassTransfer ZoneEventWedding.transfer = new CharaMassTransfer()
Definition at line 12 of file ZoneEventWedding.cs.
Referenced by OnLeaveZone(), and OnVisit().
Property Documentation
MaxAttendee
int ZoneEventWedding.MaxAttendee get
Definition at line 20 of file ZoneEventWedding.cs.
Referenced by OnVisit().
questWedding
QuestWedding ZoneEventWedding.questWedding get
Definition at line 14 of file ZoneEventWedding.cs.
Referenced by OnVisit().
TextWidgetDate
override string ZoneEventWedding.TextWidgetDate get
Definition at line 16 of file ZoneEventWedding.cs.
TimeLimit
override int ZoneEventWedding.TimeLimit get
Definition at line 18 of file ZoneEventWedding.cs.
The documentation for this class was generated from the following file:
Elin/ZoneEventWedding.cs