Elin Decompiled Documentation: MeetingManager Class Reference
MeetingManager Class Reference
Public Member Functions
void SetOwner (FactionBranch _branch)
void OnSimulateHour (VirtualDate date)
void Add (VirtualDate date)
void Add (Meeting m)
void Remove (Meeting m)
BaseArea SetRoom ()
void Start ()
void CallNext ()
Public Attributes
List< Meeting > list = new List<Meeting>()
FactionBranch branch
BaseArea room
Properties
bool CanStartMeeting [get]
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Additional Inherited Members
Static Public Member Functions inherited from EClass
static int rnd (int a)
static int curve (int a, int start, int step, int rate=75)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Static Public Attributes inherited from EClass
static Core core
Detailed Description
Definition at line 5 of file MeetingManager.cs.
Member Function Documentation
Add() [1/2]
void MeetingManager.Add (Meeting m) inline
Definition at line 42 of file MeetingManager.cs.
    {
        this.list.Add(m);
    }
References list.
Add() [2/2]
void MeetingManager.Add (VirtualDate date) inline
Definition at line 31 of file MeetingManager.cs.
    {
        MeetingMerchant meetingMerchant = new MeetingMerchant();
        meetingMerchant.dateExipire = date.GetRaw(0) + 10080;
        this.list.Add(meetingMerchant);
        if (date.IsRealTime)
        {
            Msg.Say("newMeeting");
        }
    }
References Date.GetRaw(), VirtualDate.IsRealTime, list, and Msg.Say().
CallNext()
void MeetingManager.CallNext () inline
Definition at line 87 of file MeetingManager.cs.
    {
        if (this.list.Count == 0)
        {
            return;
        }
        Thing emptySeat = this.room.GetEmptySeat();
        Point chara = ((emptySeat != null) ? emptySeat.pos : null) ?? this.room.GetRandomPoint(true, false);
        Meeting meeting = this.list[0];
        this.list.RemoveAt(0);
        meeting.SetChara(chara);
        Chara maid = EClass.Branch.GetMaid();
        if (maid != null)
        {
            GameLang.refDrama1 = meeting.chara.Name;
            LayerDrama.Activate("_chara", null, "meeting", maid, null, "").SetOnKill(new Action(meeting.Start));
            return;
        }
        meeting.Start();
    }
References LayerDrama.Activate(), EClass.Branch, Meeting.chara, BaseArea.GetEmptySeat(), FactionBranch.GetMaid(), BaseArea.GetRandomPoint(), list, Card.Name, Card.pos, room, Meeting.SetChara(), and Meeting.Start().
Referenced by Meeting.OnEndDrama(), and Start().
OnSimulateHour()
void MeetingManager.OnSimulateHour (VirtualDate date) inline
Definition at line 16 of file MeetingManager.cs.
    {
        if (this.list.Count > 0)
        {
            for (int i = this.list.Count - 1; i >= 0; i--)
            {
                if (this.list[i].dateExipire != 0 && date.IsExpired(this.list[i].dateExipire))
                {
                    this.list.RemoveAt(i);
                }
            }
        }
        int count = this.list.Count;
    }
References Date.IsExpired(), and list.
Remove()
void MeetingManager.Remove (Meeting m) inline
Definition at line 47 of file MeetingManager.cs.
    {
        this.list.Remove(m);
    }
References list.
SetOwner()
void MeetingManager.SetOwner (FactionBranch _branch) inline
Definition at line 7 of file MeetingManager.cs.
    {
        this.branch = _branch;
        foreach (Meeting meeting in this.list)
        {
            meeting.SetOwner(this.branch);
        }
    }
References branch, list, and Meeting.SetOwner().
Referenced by FactionBranch.SetOwner().
SetRoom()
BaseArea MeetingManager.SetRoom () inline
Definition at line 60 of file MeetingManager.cs.
    {
        Thing thing = EClass._map.props.installed.Find<TraitSpotMeeting>();
        TraitSpotMeeting traitSpotMeeting = ((thing != null) ? thing.trait : null) as TraitSpotMeeting;
        if (traitSpotMeeting != null)
        {
            this.room = traitSpotMeeting.owner.Cell.room;
            if (this.room == null)
            {
                this.room = new VirtualRoom(traitSpotMeeting.owner);
            }
        }
        else
        {
            this.room = EClass._map.rooms.listRoom.RandomItem<Room>();
        }
        return this.room;
    }
References EClass._map, Card.Cell, Props.Find(), PropsManager.installed, RoomManager.listRoom, Trait.owner, Map.props, Cell.room, room, Map.rooms, and Card.trait.
Referenced by Start().
Start()
void MeetingManager.Start () inline
Definition at line 79 of file MeetingManager.cs.
    {
        this.SetRoom();
        Thing emptySeat = this.room.GetEmptySeat();
        EClass.pc.MoveImmediate(((emptySeat != null) ? emptySeat.pos : null) ?? this.room.GetRandomPoint(true, false), true, true);
        this.CallNext();
    }
References CallNext(), BaseArea.GetEmptySeat(), Card.MoveImmediate(), EClass.pc, Card.pos, room, and SetRoom().
Member Data Documentation
branch
FactionBranch MeetingManager.branch
Definition at line 111 of file MeetingManager.cs.
Referenced by SetOwner().
list
List<Meeting> MeetingManager.list = new List<Meeting>()
Definition at line 109 of file MeetingManager.cs.
Referenced by Add(), CallNext(), OnSimulateHour(), UIHomeInfo.RefreshReport(), Remove(), and SetOwner().
room
BaseArea MeetingManager.room
Definition at line 113 of file MeetingManager.cs.
Referenced by CallNext(), SetRoom(), and Start().
Property Documentation
CanStartMeeting
bool MeetingManager.CanStartMeeting get
Definition at line 52 of file MeetingManager.cs.
    {
        get
        {
            return this.list.Count > 0 && this.SetRoom() != null;
        }
    }
The documentation for this class was generated from the following file:
Elin/MeetingManager.cs