Elin Decompiled Documentation: CalcPlat Class Reference
CalcPlat Class Reference
Static Public Member Functions
static int Learn (Chara c, Element e)
static int Train (Chara c, Element _e)
Static Public Member Functions inherited from EClass
static int rndSeed (int a, int seed)
static int rnd (long a)
static int rnd (int a)
static int curve (int a, int start, int step, int rate=75)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Additional Inherited Members
Static Public Attributes inherited from EClass
static Core core
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Detailed Description
Definition at line 3 of file CalcPlat.cs.
Member Function Documentation
Learn()
static int CalcPlat.Learn (Chara c, Element e) inline static
Definition at line 5 of file CalcPlat.cs.
    {
        int num = Mathf.Max(1, e.CostLearn * (c.HasElement(1202) ? 80 : 100) / 100);
        if (e.source.tag.Contains("guild") && Guild.CurrentDrama.relation.rank < 2)
        {
            return num * 2;
        }
        return num;
    }
References Element.CostLearn, Guild.CurrentDrama, Card.HasElement(), FactionRelation.rank, Faction.relation, and Element.source.
Train()
static int CalcPlat.Train (Chara c, Element _e) inline static
Definition at line 15 of file CalcPlat.cs.
    {
        Element element = c.elements.GetElement(_e.id);
        if (element.vTempPotential >= 1000)
        {
            return 0;
        }
        int num = Mathf.Max(1, element.CostTrain * (c.HasElement(1202) ? 80 : 100) / 100);
        if (element.source.tag.Contains("guild") && Guild.CurrentDrama.relation.rank < 2)
        {
            return num * 2;
        }
        return num;
    }
References Element.CostTrain, Guild.CurrentDrama, Card.elements, ElementContainer.GetElement(), Card.HasElement(), Element.id, FactionRelation.rank, Faction.relation, Element.source, and Element.vTempPotential.
The documentation for this class was generated from the following file:
Elin/CalcPlat.cs