Elin Decompiled Documentation: CharaActor Class Reference
CharaActor Class Reference
Public Member Functions
void SetOwnerAsChara ()
override void OnSetOwner ()
override void NextFrame ()
override void RefreshSprite ()
Public Member Functions inherited from CardActor
void SetOwner (Card t)
virtual void OnSetOwner ()
virtual void IdleFrame ()
virtual void NextFrame ()
virtual void NextDir ()
virtual int GetFrame ()
virtual void OnRender (RenderParam p)
virtual void RefreshSprite ()
virtual void Kill ()
Public Attributes
new Chara owner
Public Attributes inherited from CardActor
Card owner
SpriteRenderer sr
SpriteRenderer sr2
SpriteReplacerAnimation srAnime
MaterialPropertyBlock mpb
MaterialPropertyBlock mpb2
Type type
Additional Inherited Members
Public Types inherited from CardActor
enum Type { Default , Boat , Canvas , MultiSprite }
Static Public Member Functions inherited from EMono
static int rnd (int a)
Static Public Attributes inherited from EMono
static Core core
Static Protected Attributes inherited from CardActor
static Vector3 tempV
static Vector3 tempV2
Properties inherited from CardActor
virtual bool isPCC [get]
virtual int currentDir [get]
Properties inherited from EMono
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SoundManager Sound [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static CoreDebug debug [get]
Detailed Description
Definition at line 3 of file CharaActor.cs.
Member Function Documentation
NextFrame()
override void CharaActor.NextFrame () inline virtual
Reimplemented from CardActor.
Reimplemented in CharaActorPCC.
Definition at line 20 of file CharaActor.cs.
    {
        RefreshSprite();
    }
References RefreshSprite().
OnSetOwner()
override void CharaActor.OnSetOwner () inline virtual
Reimplemented from CardActor.
Reimplemented in CharaActorPCC.
Definition at line 12 of file CharaActor.cs.
    {
        SetOwnerAsChara();
        sr.sprite = owner.GetSprite();
        mpb.SetTexture("_MainTex", sr.sprite.texture);
        IdleFrame();
    }
References Chara.GetSprite(), CardActor.IdleFrame(), CardActor.mpb, owner, SetOwnerAsChara(), and CardActor.sr.
RefreshSprite()
override void CharaActor.RefreshSprite () inline virtual
Reimplemented from CardActor.
Reimplemented in CharaActorPCC.
Definition at line 25 of file CharaActor.cs.
    {
        Sprite sprite = sr.sprite;
        Texture2D texture = sprite.texture;
        Rect textureRect = sprite.textureRect;
        if (!isPCC)
        {
            sr.flipX = owner.flipX;
        }
        Vector4 value = new Vector4(textureRect.x / (float)texture.width, textureRect.min.y / (float)texture.height, textureRect.max.x / (float)texture.width, textureRect.max.y / (float)texture.height);
        mpb.SetVector("_Rect", value);
        mpb.SetFloat("_PixelHeight", sprite.rect.height);
    }
References Chara.flipX, CardActor.isPCC, CardActor.mpb, owner, and CardActor.sr.
Referenced by NextFrame().
SetOwnerAsChara()
void CharaActor.SetOwnerAsChara () inline
Definition at line 7 of file CharaActor.cs.
    {
        owner = base.owner as Chara;
    }
References owner.
Referenced by OnSetOwner(), and CharaActorPCC.OnSetOwner().
Member Data Documentation
owner
new Chara CharaActor.owner
Definition at line 5 of file CharaActor.cs.
Referenced by CharaActorPCC.IdleFrame(), CharaActorPCC.OnRender(), OnSetOwner(), CharaActorPCC.OnSetOwner(), RefreshSprite(), CharaActorPCC.RefreshSprite(), and SetOwnerAsChara().
The documentation for this class was generated from the following file:
Elin/CharaActor.cs