Elin Decompiled Documentation: Tutorial Class Reference
Tutorial Class Reference
Static Public Member Functions
static void Play (string idStep)
static void Remove (string idStep)
static void Reserve (string idStep, Action onBeforePlay=null)
static void TryPlayReserve ()
Static Public Member Functions inherited from EClass
static int rndSeed (int a, int seed)
static int rnd (int a)
static int curve (int a, int start, int step, int rate=75)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Static Public Attributes
static bool debugSkip
Static Public Attributes inherited from EClass
static Core core
Additional Inherited Members
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Detailed Description
Definition at line 3 of file Tutorial.cs.
Member Function Documentation
Play()
static void Tutorial.Play (string idStep) inline static
Definition at line 7 of file Tutorial.cs.
    {
        bool flag = debugSkip || !EClass.core.config.game.tutorial;
        int id = EClass.player.flags.GetStoryRowID("_tutorial", idStep);
        EClass.debug.Log(idStep + "/" + id + "/" + flag + "/" + debugSkip + "/" + EClass.player.flags.playedStories.Contains(id));
        if (EClass.player.flags.playedStories.Contains(id))
        {
            return;
        }
        if (!flag)
        {
            EClass.core.actionsNextFrame.Add(delegate
            {
                EClass.player.flags.PlayStory("_tutorial", id);
                if ((bool)LayerDrama.Instance)
                {
                    LayerDrama.Instance.SetOnKill(delegate
                    {
                        AfterPlay();
                    });
                }
            });
        }
        else
        {
            EClass.player.flags.playedStories.Add(id);
            AfterPlay();
        }
        void AfterPlay()
        {
            if (idStep == "first")
            {
                EClass.pc.PickOrDrop(EClass.pc.pos, ThingGen.Create("book_tutorial"));
            }
            if (id < 950)
            {
                Msg.Say("tutorial_added");
                SE.WriteJournal();
            }
        }
    }
References BaseCore.actionsNextFrame, Core.config, EClass.core, EClass.debug, debugSkip, Player.flags, CoreConfig.game, Player.Flags.GetStoryRowID(), LayerDrama.Instance, CoreDebug.Log(), Player.Flags.playedStories, EClass.player, Player.Flags.PlayStory(), and CoreConfig.GameConfig.tutorial.
Referenced by LayerInventory.CreateContainer(), GameScreenElona.OnActivate(), LayerCraft.OnKill(), ConFaint.OnRemoved(), DramaManager.ParseLine(), Chara.TickConditions(), and TraitResidentBoard.TrySetAct().
Remove()
static void Tutorial.Remove (string idStep) inline static
Definition at line 49 of file Tutorial.cs.
    {
        int storyRowID = EClass.player.flags.GetStoryRowID("_tutorial", idStep);
        EClass.player.flags.playedStories.Remove(storyRowID);
    }
References Player.flags, Player.Flags.GetStoryRowID(), Player.Flags.playedStories, and EClass.player.
Referenced by GameDate.AdvanceHour().
Reserve()
static void Tutorial.Reserve (string idStep, Action onBeforePlay = null) inline static
Definition at line 55 of file Tutorial.cs.
    {
        if (!EClass.player.flags.reservedTutorial.Contains(idStep))
        {
            int storyRowID = EClass.player.flags.GetStoryRowID("_tutorial", idStep);
            if (!EClass.player.flags.playedStories.Contains(storyRowID))
            {
                onBeforePlay?.Invoke();
                EClass.player.flags.reservedTutorial.Add(idStep);
            }
        }
    }
References Player.flags, Player.Flags.GetStoryRowID(), Player.Flags.playedStories, EClass.player, and Player.Flags.reservedTutorial.
Referenced by GameDate.AdvanceDay(), GameDate.AdvanceHour(), Chara.Die(), FactionBranch.GenerateGarbage(), Card.LevelUp(), Chara.ModCorruption(), Player.ModFame(), Zone.ModInfluence(), Player.ModKarma(), Zone_DungeonPuppy.OnBeforeSimulate(), ConSuffocation.OnStart(), DramaManager.ParseLine(), Chara.TryReservePickupTutorial(), and FactionBranch.Upgrade().
TryPlayReserve()
static void Tutorial.TryPlayReserve () inline static
Definition at line 68 of file Tutorial.cs.
    {
        if (!EClass.ui.IsActive && EClass.player.flags.reservedTutorial.Count != 0 && !LayerDrama.Instance)
        {
            Play(EClass.player.flags.reservedTutorial[0]);
            EClass.player.flags.reservedTutorial.RemoveAt(0);
        }
    }
References Player.flags, LayerDrama.Instance, EClass.player, Player.Flags.reservedTutorial, and EClass.ui.
Referenced by AM_Adv.OnBecomeNoGoal().
Member Data Documentation
debugSkip
bool Tutorial.debugSkip static
Definition at line 5 of file Tutorial.cs.
Referenced by Play().
The documentation for this class was generated from the following file:
Elin/Tutorial.cs