Elin Decompiled Documentation: ClassCache< T > Class Template Reference
ClassCache< T > Class Template Reference
Public Member Functions
Func< T > CreateDelegate (Type type)
T Create< T2 > (string id, string assembly)
Static Public Member Functions
static T Create< T > (string id, string assembly="Assembly-CSharp")
static Type LoadTypeFromGlobalNamespace (string id)
Public Attributes
Dictionary< string, Func< T > > dict = new Dictionary<string, Func<T>>()
Static Public Attributes
static ClassCache< object > caches = new ClassCache<object>()
static HashSet< string > assemblies = new HashSet<string>()
static List< Func< string, Type > > typeLoaders = new List<Func<string, Type>> { LoadTypeFromGlobalNamespace }
static HashSet< Type > modTypes = new HashSet<Type>()
Detailed Description
Definition at line 6 of file ClassCache.cs.
Member Function Documentation
Create< T >()
static T ClassCache< T >.Create< T > (string id, string assembly = "Assembly-CSharp") inline static
Definition at line 60 of file ClassCache.cs.
    {
        return (T)caches.Create<T>(id, assembly);
    }
References ClassCache< T >.caches.
Create< T2 >()
T ClassCache< T >.Create< T2 > (string id, string assembly) inline
Definition at line 25 of file ClassCache.cs.
    {
        id = id.Trim();
        Func<T> func = dict.TryGetValue(id);
        if (func != null)
        {
            return func();
        }
        Type type = Type.GetType(id + ", " + assembly);
        if (type == null)
        {
            for (int num = ClassCache.typeLoaders.Count - 1; num >= 0; num--)
            {
                type = ClassCache.typeLoaders[num](id);
                if (type != null)
                {
                    break;
                }
            }
        }
        func = CreateDelegate(type);
        dict[id] = func;
        return func();
    }
References ClassCache< T >.CreateDelegate(), ClassCache< T >.dict, and ClassCache< T >.typeLoaders.
CreateDelegate()
Func< T > ClassCache< T >.CreateDelegate (Type type) inline
Definition at line 10 of file ClassCache.cs.
    {
        Func<T> result = () => default(T);
        if (type == null)
        {
            return result;
        }
        ConstructorInfo constructor = type.GetConstructor(Type.EmptyTypes);
        if (constructor != null)
        {
            result = Expression.Lambda<Func<T>>(Expression.New(constructor), Array.Empty<ParameterExpression>()).Compile();
        }
        return result;
    }
Referenced by ClassCache< T >.Create< T2 >().
LoadTypeFromGlobalNamespace()
static Type ClassCache< T >.LoadTypeFromGlobalNamespace (string id) inline static
Definition at line 65 of file ClassCache.cs.
    {
        foreach (string assembly in assemblies)
        {
            Type type = Type.GetType(id + ", " + assembly);
            if (type != null)
            {
                return type;
            }
        }
        return null;
    }
References ClassCache< T >.assemblies.
Member Data Documentation
assemblies
HashSet<string> ClassCache< T >.assemblies = new HashSet<string>() static
Definition at line 54 of file ClassCache.cs.
Referenced by ClassCache< T >.LoadTypeFromGlobalNamespace(), and Core.StartCase().
caches
ClassCache<object> ClassCache< T >.caches = new ClassCache<object>() static
Definition at line 52 of file ClassCache.cs.
Referenced by ClassCache< T >.Create< T >().
dict
Dictionary<string, Func<T> > ClassCache< T >.dict = new Dictionary<string, Func<T>>()
Definition at line 8 of file ClassCache.cs.
Referenced by ClassCache< T >.Create< T2 >().
modTypes
HashSet<Type> ClassCache< T >.modTypes = new HashSet<Type>() static
Definition at line 58 of file ClassCache.cs.
typeLoaders
List<Func<string, Type> > ClassCache< T >.typeLoaders = new List<Func<string, Type>> { LoadTypeFromGlobalNamespace } static
Definition at line 56 of file ClassCache.cs.
Referenced by ClassCache< T >.Create< T2 >().
The documentation for this class was generated from the following file:
Elin/Plugins.basecore/ClassCache.cs