Elin Decompiled Documentation: RecipeCard Class Reference
RecipeCard Class Reference
Public Member Functions
override IRenderer GetRenderer ()
override string GetDetail ()
override string GetIdThing ()
override void OnRenderMarker (Point point, bool active, HitResult result, bool main, int dir, int bridgeHeight)
override void BuildIngredientList ()
override void OnChangeIngredient ()
override void OnSelected ()
Card CreateMold ()
override Thing Craft (BlessedState blessed, bool sound=false, List< Thing > ings=null, TraitCrafter crafter=null, bool model=false)
void MakeDish (Thing t)
void MixIngredients (Thing t)
string GetIdFailDish ()
override void Build (TaskBuild task)
override void Build (Chara chara, Card t, Point pos, int mat, int dir, int altitude, int bridgeHeight)
override void OnChangeAltitude (int a)
override void Rotate ()
override void SetDir (int d)
override void WriteNote (UINote n)
override Recipe Duplicate ()
Public Member Functions inherited from Recipe
bool IsStaticLV ()
int GetQualityBonus ()
virtual int GetRefVal ()
virtual string GetIdThing ()
virtual bool ShouldShowHighlight (HitResult r)
BaseTileSelector.BoxType GetBoxType ()
int GetDefaultColor ()
virtual SourceMaterial.Row GetMainMaterial ()
virtual SourceMaterial.Row GetColorMaterial ()
virtual void BuildIngredientList ()
void BuildIngredientList (Thing t)
virtual void OnChangeIngredient ()
virtual Thing Craft (BlessedState blessed, bool sound=false, List< Thing > ings=null, TraitCrafter crafter=null, bool model=false)
bool HasSameTile (Point point, int dir, int altitude, int bridgeHeight)
virtual void Build (TaskBuild task)
virtual void Build (Chara chara, Card t, Point pos, int mat, int dir, int altitude, int bridgeHeight)
virtual void OnRenderMarker (Point point, bool active, HitResult result, bool main, int dir, int bridgeHeight)
string GetName ()
virtual string GetDetail ()
virtual void WriteNote (UINote n)
void WriteReqFactory (UINote n, bool hasFactory=true)
void WriteReqSkill (UINote n)
virtual IRenderer GetRenderer ()
virtual void OnSelected ()
virtual void OnChangeAltitude (int a)
virtual void Rotate ()
virtual void SetDir (int d)
virtual Recipe Duplicate ()
virtual void SetImage (Image icon)
bool IsCraftable ()
int GetMaxCount ()
void SetTextDifficulty (UIText text)
int GetSortVal ()
bool HasFirstTimeBonus ()
void TryGetFirstTimeBonus ()
void SaveLastIngredients ()
QuestTrackCraft GetQuestTrack ()
void ToggleTrack (QuestTrackCraft quest)
Public Attributes
CardRow _sourceCard
bool freePos
float fx
float fy
Card _mold
Public Attributes inherited from Recipe
string id
List< Ingredient > ingredients = new List<Ingredient>()
bool UseStock
bool IngAsProduct
bool VirtualBlock
int _dir
int sync
int idMat = -1
int idSkin
State state
RecipeSource _source
Properties
CardRow sourceCard [get]
override RenderRow renderRow [get]
override TileType tileType [get]
string idCard [get]
override bool CanRotate [get]
override bool IsThing [get]
override Card Mold [get]
bool isDish [get]
Properties inherited from Recipe
RecipeSource source [get]
SourceMaterial.Row DefaultMaterial [get]
virtual TileRow tileRow [get]
virtual RenderRow renderRow [get]
string Name [get]
virtual TileType tileType [get]
virtual bool IsFloorOrBridge [get]
int MaxAltitude [get]
int RecipeLv [get]
bool IsFloor [get]
bool IsObj [get]
virtual bool IsBlock [get]
bool IsWallOrFence [get]
bool IsBridge [get]
virtual bool IsThing [get]
virtual Card Mold [get]
virtual int W [get]
virtual int H [get]
virtual bool RequireIngredients [get]
bool MultiSize [get]
BaseTileSelector tileSelector [get]
virtual int CostMoney [get]
virtual bool CanRotate [get]
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Additional Inherited Members
Public Types inherited from Recipe
enum State { Valid , Invalid }
enum IngType { Default , CreativeFood }
Static Public Member Functions inherited from Recipe
static Recipe GetOrCreate (string id)
static Recipe Create (RecipeSource _source, int idMat=-1, Thing ing=null)
static Recipe Create (Thing t)
static void DropIngredients (string id, string idMatMain, int num=1)
Static Public Member Functions inherited from EClass
static int rndSeed (int a, int seed)
static int rnd (long a)
static int rnd (int a)
static int curve (int _a, int start, int step, int rate=75)
static int sqrt (int a)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Static Public Attributes inherited from Recipe
static Dictionary< string, Recipe > recipeCache = new Dictionary<string, Recipe>()
Static Public Attributes inherited from EClass
static Core core
Detailed Description
Definition at line 5 of file RecipeCard.cs.
Member Function Documentation
Build() [1/2]
override void RecipeCard.Build (Chara chara, Card t, Point pos, int mat, int dir, int altitude, int bridgeHeight) inline virtual
Reimplemented from Recipe.
Definition at line 454 of file RecipeCard.cs.
    {
        if (mat == -1)
        {
            mat = 2;
        }
        EClass.pc.PlaySound(EClass.sources.materials.rows[mat].GetSoundImpact());
        t.SetDir(dir);
        t.idSkin = idSkin;
        EClass._zone.AddCard(t, pos);
        if (t.trait is TraitHouseBoard && ActionMode.Build.houseBoard != null)
        {
            (t.trait as TraitHouseBoard).data = IO.DeepCopy(ActionMode.Build.houseBoard.data);
        }
        t.SetPlaceState(PlaceState.installed, byPlayer: true);
        t.altitude = altitude;
        t.isPlayerCreation = true;
        if (EClass._zone.idCurrentSubset != null)
        {
            t.isSubsetCard = true;
        }
        t.ignoreStackHeight = Input.GetKey(KeyCode.LeftControl);
        if (ActionMode.Build.IsActive && t.trait.MaskOnBuild && EClass.debug.enable)
        {
            t.isMasked = true;
        }
        if (EClass.scene.actionMode.IsRoofEditMode(t) && t.isThing)
        {
            t.isRoofItem = true;
            t.SetPlaceState(PlaceState.roaming);
        }
        try
        {
            t.ForeachPoint(delegate(Point p, bool main)
            {
                CheckBlock(p);
            });
        }
        catch
        {
            Debug.LogWarning("kokodayo");
        }
        t.freePos = freePos;
        if (freePos)
        {
            t.fx = fx;
            t.fy = fy;
        }
        t.renderer.RefreshSprite();
        void CheckBlock(Point _pos)
        {
            if (_pos.cell.IsBlocked && _pos.HasChara)
            {
                foreach (Chara item in _pos.ListCharas().Copy())
                {
                    chara.Kick(item, ignoreSelf: false, karmaLoss: false);
                }
            }
        }
    }
References EClass._zone, Scene.actionMode, Zone.AddCard(), ActionMode.Build, Point.cell, TraitHouseBoard.data, EClass.debug, Debug, CoreDebug.enable, Card.ForeachPoint(), freePos, fx, fy, Point.HasChara, AM_Build.houseBoard, Spatial.idCurrentSubset, Recipe.idSkin, Cell.IsBlocked, ActionMode.IsRoofEditMode(), Card.isThing, item, Chara.Kick(), Point.ListCharas(), Trait.MaskOnBuild, SourceManager.materials, EClass.pc, Card.PlaySound(), CardRenderer.RefreshSprite(), Card.renderer, EClass.scene, Card.SetDir(), Card.SetPlaceState(), EClass.sources, and Card.trait.
Build() [2/2]
override void RecipeCard.Build (TaskBuild task) inline virtual
Reimplemented from Recipe.
Definition at line 397 of file RecipeCard.cs.
    {
        Card card = null;
        if (task.target != null)
        {
            card = task.target;
        }
        else if (IngAsProduct)
        {
            if (task.resources.Count == 0)
            {
                Thing thing = ingredients[0].RefreshThing();
                if (thing == null)
                {
                    SE.Beep();
                    return;
                }
                Thing item = thing.Split(1);
                task.resources.Add(item);
                if (ingredients[0].thing.isDestroyed || ingredients[0].thing.ExistsOnMap)
                {
                    ingredients[0].thing = null;
                }
            }
            card = task.resources[0];
        }
        else if (sourceCard.isChara)
        {
            card = CharaGen.Create(idCard, Mathf.Max(EClass._zone.DangerLv, EClass.pc.LV));
        }
        else
        {
            card = ThingGen.Create(idCard, -1, Mathf.Max(EClass._zone.DangerLv, EClass.pc.LV));
            if (!card.IsUnique)
            {
                card.ChangeMaterial(GetMainMaterial());
            }
            if (base.source.colorIng != 0)
            {
                card.Dye(GetColorMaterial());
            }
            if (card.IsContainer)
            {
                card.RemoveThings();
            }
            foreach (Ingredient ingredient in ingredients)
            {
                if (ingredient.thing != null && ingredient.thing.HasElement(759))
                {
                    card.elements.SetBase(759, ingredient.thing.Evalue(759));
                }
            }
        }
        Build(task.owner, card, task.pos, ingredients[0].mat, task.dir, task.altitude, task.bridgeHeight);
        card.renderer.PlayAnime(AnimeID.Place);
    }
References EClass._zone, ActPlan.List.Add(), TaskBuild.altitude, TaskBuild.bridgeHeight, Build, card, ThingGen.Create(), CharaGen.Create(), Zone.DangerLv, TaskBuild.dir, Card.Evalue(), Recipe.GetColorMaterial(), Recipe.GetMainMaterial(), Card.HasElement(), idCard, Recipe.IngAsProduct, Recipe.ingredients, CardRow.isChara, Card.isDestroyed, item, Card.LV, AIAct.owner, EClass.pc, TaskPoint.pos, TaskBuild.resources, sourceCard, Card.Split(), TaskBuild.target, and Recipe.Ingredient.thing.
BuildIngredientList()
override void RecipeCard.BuildIngredientList () inline virtual
Reimplemented from Recipe.
Definition at line 65 of file RecipeCard.cs.
    {
        if (ingredients.Count != 0)
        {
            return;
        }
        base.BuildIngredientList();
        if (!EClass.core.IsGameStarted || EClass.core.game.isLoading || !isDish)
        {
            return;
        }
        if (EClass.pc.HasElement(487) && !EClass.scene.actionMode.IsBuildMode)
        {
            ingredients[0].ingType = IngType.CreativeFood;
        }
        if (EClass.pc.Evalue(1650) < 2)
        {
            return;
        }
        bool flag = ingredients.Count < 3;
        foreach (Ingredient ingredient in ingredients)
        {
            if (ingredient.id == "seasoning")
            {
                flag = false;
            }
        }
        if (flag)
        {
            ingredients.Add(new Ingredient
            {
                id = "seasoning",
                useCat = true,
                optional = true,
                req = 1
            });
        }
    }
References Scene.actionMode, EClass.core, Card.Evalue(), Core.game, Card.HasElement(), Recipe.Ingredient.id, Recipe.ingredients, ActionMode.IsBuildMode, isDish, Core.IsGameStarted, Game.isLoading, EClass.pc, and EClass.scene.
Referenced by Recipe.Create().
Craft()
override Thing RecipeCard.Craft (BlessedState blessed, bool sound = false, List< Thing > ings = null, TraitCrafter crafter = null, bool model = false) inline virtual
Reimplemented from Recipe.
Definition at line 153 of file RecipeCard.cs.
    {
        string key = idCard;
        int num = GetMainMaterial().id;
        Element reqSkill = base.source.GetReqSkill();
        int num2 = reqSkill.Value - EClass.pc.Evalue(reqSkill.id);
        int num3 = GetQualityBonus();
        int num4 = renderRow.LV + num3;
        bool flag = num3 < 0;
        CardRow cardRow = EClass.sources.cards.map.TryGetValue(key);
        bool flag2 = false;
        if (ings != null)
        {
            foreach (Thing ing in ings)
            {
                if (ing != null && ing.IsDecayed)
                {
                    flag2 = true;
                }
            }
        }
        if (EClass.debug.godCraft || model)
        {
            flag = false;
        }
        else if (cardRow != null && cardRow.tag.Contains("no_fail"))
        {
            flag = false;
        }
        else if (isDish && !EClass.scene.actionMode.IsBuildMode)
        {
            if (num2 > 0 && EClass.rnd(num2 * 10) > EClass.rnd(100))
            {
                key = GetIdFailDish();
                flag = true;
            }
            else
            {
                flag = false;
            }
        }
        if (!model)
        {
            switch (id)
            {
            case "weapon_stone":
            case "weapon_wood":
                Rand.SetSeed();
                key = new string[6] { "dagger", "sword", "axe_hand", "blunt_club", "spear", "staff_long" }.RandomItem();
                break;
            case "weapon_anvil":
                Rand.SetSeed();
                key = new string[6] { "dagger", "sword", "axe_hand", "blunt_club", "spear", "staff_long" }.RandomItem();
                num = ings[1].material.id;
                break;
            }
        }
        bool flag3 = EClass.sources.cards.map[key].tag.Contains("static_craft");
        if (!isDish && num4 < 1)
        {
            num4 = 1;
        }
        if (EClass.sources.cards.map[key].tag.Contains("noQuality"))
        {
            num4 = -1;
        }
        if (EClass.sources.cards.map[key].tag.Contains("noMaterialChange"))
        {
            num = -1;
        }
        if (flag3)
        {
            num3 = 0;
            flag = false;
        }
        CardBlueprint.Set(new CardBlueprint
        {
            qualityBonus = num3,
            rarity = (flag ? Rarity.Crude : Rarity.Normal),
            isCraft = true
        });
        Thing thing = (flag3 ? ThingGen.Create(key) : ThingGen.Create(key, num, num4));
        thing.idSkin = idSkin;
        if (thing.IsEquipment && ings != null)
        {
            foreach (Thing ing2 in ings)
            {
                if (ing2.trait is TraitRune)
                {
                    if (thing.CanAddRune(ing2.trait as TraitRune))
                    {
                        thing.AddRune(ing2);
                    }
                    if (!thing.HasElement(484))
                    {
                        thing.elements.SetBase(484, 1);
                    }
                }
            }
        }
        thing.Identify(show: false);
        thing.isCrafted = true;
        if (!flag3)
        {
            if (base.source.colorIng != 0)
            {
                thing.Dye(GetColorMaterial());
            }
            if (thing.IsContainer)
            {
                thing.RemoveThings();
                thing.c_lockLv = 0;
            }
        }
        thing.SetBlessedState(blessed);
        if (!flag3)
        {
            if (isDish)
            {
                if (flag)
                {
                    thing.ChangeMaterial("meat");
                }
                else
                {
                    MakeDish(thing);
                }
            }
            else
            {
                MixIngredients(thing);
            }
            if (isDish && flag2)
            {
                thing.decay = thing.MaxDecay + 1;
            }
        }
        thing.trait.OnCrafted(this, ings);
        if (thing.IsAmmo && num2 < 0)
        {
            thing.SetEncLv(-num2 / 10);
        }
        if (model)
        {
            thing.SetNum(1);
            return thing;
        }
        int num5 = thing.trait.CraftNum;
        if (crafter != null && EClass.pc.Evalue(1417) > 0 && crafter.WitchDoubleCraftChance(thing) > EClass.rnd(100))
        {
            num5 *= 2;
        }
        if (thing.trait is TraitFoodFishSlice && thing.c_idRefCard == thing.id && (thing.SelfWeight == 0 || thing.Evalue(10) == 0))
        {
            Msg.Say("noMoreSlice");
            num5 = 1;
        }
        if (num5 > 1 && (thing.HasElement(703) || thing.HasElement(704) || thing.HasElement(1229)))
        {
            num5 = 1;
        }
        if (num5 > 1)
        {
            thing.SetNum(num5);
        }
        if (EClass.pc.held == null || !thing.TryStackTo(EClass.pc.held.Thing))
        {
            EClass.pc.HoldCard(thing);
        }
        if (sound)
        {
            thing.PlaySoundDrop(spatial: false);
        }
        Msg.Say("crafted", thing);
        if (thing.Num > EClass.rnd(1000) || EClass.debug.enable)
        {
            EClass.player.recipes.ComeUpWithRandomRecipe(thing.category.id);
        }
        if (isDish)
        {
            if (EClass.debug.enable || (EClass.player.flags.canComupWithFoodRecipe && EClass.rnd(30) == 0))
            {
                EClass.player.recipes.ComeUpWithRandomRecipe(thing.category.id);
                EClass.player.flags.canComupWithFoodRecipe = false;
            }
            if (flag && crafter != null && crafter.CanTriggerFire && EClass.rnd(4) == 0)
            {
                Point point = (crafter.ExistsOnMap ? crafter.owner.pos : EClass.pc.pos);
                if (!point.cell.HasFire)
                {
                    EClass._map.ModFire(point.x, point.z, 10);
                }
            }
        }
        return thing;
    }
References EClass._map, Scene.actionMode, Card.AddRune(), Card.c_idRefCard, Card.CanAddRune(), Player.Flags.canComupWithFoodRecipe, SourceManager.cards, Card.category, Point.cell, Card.ChangeMaterial(), RecipeManager.ComeUpWithRandomRecipe(), Trait.CraftNum, ThingGen.Create(), EClass.debug, Card.Dye(), Card.elements, CoreDebug.enable, Card.Evalue(), Player.flags, Recipe.GetColorMaterial(), GetIdFailDish(), Recipe.GetMainMaterial(), Recipe.GetQualityBonus(), CoreDebug.godCraft, Card.HasElement(), Cell.HasFire, Chara.held, Chara.HoldCard(), Card.id, Element.id, idCard, Thing.Identify(), Recipe.idSkin, Card.IsAmmo, ActionMode.IsBuildMode, Card.IsContainer, Card.IsDecayed, isDish, Card.IsEquipment, MakeDish(), SourceCard.map, MixIngredients(), Map.ModFire(), Card.Num, Trait.OnCrafted(), EClass.pc, EClass.player, Card.PlaySoundDrop(), Card.pos, Player.recipes, Card.RemoveThings(), EClass.rnd(), Msg.Say(), EClass.scene, Thing.SelfWeight, CardBlueprint.Set(), ElementContainer.SetBase(), Card.SetBlessedState(), Card.SetEncLv(), Card.SetNum(), Rand.SetSeed(), Element.source, EClass.sources, RenderRow.tag, Card.Thing, Card.trait, Card.TryStackTo(), Point.x, and Point.z.
CreateMold()
Card RecipeCard.CreateMold () inline
Definition at line 121 of file RecipeCard.cs.
    {
        if (_mold != null)
        {
            _mold.Destroy();
        }
        if (UseStock)
        {
            ingredients[0].RefreshThing();
        }
        if (UseStock && ingredients[0].thing != null)
        {
            _mold = ingredients[0].thing.Duplicate(1);
        }
        else
        {
            if (sourceCard.isChara)
            {
                _mold = CharaGen.Create(idCard);
            }
            else
            {
                _mold = ThingGen.Create(idCard);
            }
            OnChangeIngredient();
        }
        _mold.dir = _dir;
        _mold.altitude = ActionMode.Build.altitude;
        _mold.idSkin = idSkin;
        return _mold;
    }
References Recipe._dir, _mold, AM_Build.altitude, ActionMode.Build, ThingGen.Create(), CharaGen.Create(), Card.Destroy(), idCard, Recipe.idSkin, Recipe.ingredients, CardRow.isChara, OnChangeIngredient(), sourceCard, and Recipe.UseStock.
Referenced by OnSelected().
Duplicate()
override Recipe RecipeCard.Duplicate () inline virtual
Reimplemented from Recipe.
Definition at line 546 of file RecipeCard.cs.
    {
        RecipeCard recipeCard = IO.DeepCopy(this);
        recipeCard._mold = _mold;
        return recipeCard;
    }
References _mold.
GetDetail()
override string RecipeCard.GetDetail () inline virtual
Reimplemented from Recipe.
Definition at line 41 of file RecipeCard.cs.
    {
        return sourceCard.GetDetail();
    }
References SourceData< T, T2 >.BaseRow.GetDetail(), and sourceCard.
GetIdFailDish()
string RecipeCard.GetIdFailDish () inline
Definition at line 379 of file RecipeCard.cs.
    {
        return sourceCard.category switch
        {
            "meal_meat" => "fail_meat",
            "meal_fish" => "fail_fish",
            "meal_vegi" => "fail_vegi",
            "meal_fruit" => "fail_fruit",
            "meal_cake" => "fail_dough_cake",
            "meal_bread" => "fail_dough_bread",
            "meal_noodle" => "fail_noodle",
            "meal_egg" => "fail_egg",
            "meal_rice" => "fail_rice",
            "meal_soup" => "fail_drink",
            _ => "fail_dish",
        };
    }
Referenced by Craft().
GetIdThing()
override string RecipeCard.GetIdThing () inline virtual
Reimplemented from Recipe.
Definition at line 46 of file RecipeCard.cs.
    {
        return id;
    }
References Recipe.id.
GetRenderer()
override IRenderer RecipeCard.GetRenderer () inline virtual
Reimplemented from Recipe.
Definition at line 36 of file RecipeCard.cs.
    {
        return Mold.renderer;
    }
References Mold, and Card.renderer.
MakeDish()
void RecipeCard.MakeDish (Thing t) inline
Definition at line 350 of file RecipeCard.cs.
    {
        Rand.SetSeed(EClass.pc.turn);
        List<Thing> list = new List<Thing>();
        foreach (Ingredient ingredient in ingredients)
        {
            list.Add(ingredient.thing);
        }
        CraftUtil.MakeDish(t, list, GetQualityBonus(), EClass.pc);
        Rand.SetSeed();
        if (EClass.pc.HasElement(1658))
        {
            t.elements.SetBase(757, 1);
            t.c_dateCooked = EClass.world.date.GetRaw() + (EClass.pc.Evalue(1658) - 1) * 48 * 60;
        }
    }
References World.date, Card.Evalue(), Recipe.GetQualityBonus(), Date.GetRaw(), Card.HasElement(), Recipe.ingredients, CraftUtil.MakeDish(), EClass.pc, Rand.SetSeed(), Recipe.Ingredient.thing, Card.turn, and EClass.world.
Referenced by Craft().
MixIngredients()
void RecipeCard.MixIngredients (Thing t) inline
Definition at line 367 of file RecipeCard.cs.
    {
        Rand.SetSeed(EClass.pc.turn);
        List<Thing> list = new List<Thing>();
        foreach (Ingredient ingredient in ingredients)
        {
            list.Add(ingredient.thing);
        }
        CraftUtil.MixIngredients(t, list, CraftUtil.MixType.General, GetQualityBonus());
        Rand.SetSeed();
    }
References Recipe.GetQualityBonus(), Recipe.ingredients, CraftUtil.MixIngredients(), EClass.pc, Rand.SetSeed(), Recipe.Ingredient.thing, and Card.turn.
Referenced by Craft().
OnChangeAltitude()
override void RecipeCard.OnChangeAltitude (int a) inline virtual
Reimplemented from Recipe.
Definition at line 515 of file RecipeCard.cs.
    {
        Mold.altitude = a;
    }
OnChangeIngredient()
override void RecipeCard.OnChangeIngredient () inline virtual
Reimplemented from Recipe.
Definition at line 104 of file RecipeCard.cs.
    {
        if (!UseStock)
        {
            Mold.ChangeMaterial(GetMainMaterial());
            if (base.source.colorIng != 0)
            {
                Mold.Dye(GetColorMaterial());
            }
        }
    }
References Card.ChangeMaterial(), Card.Dye(), Recipe.GetColorMaterial(), Recipe.GetMainMaterial(), Mold, and Recipe.UseStock.
Referenced by CreateMold().
OnRenderMarker()
override void RecipeCard.OnRenderMarker (Point point, bool active, HitResult result, bool main, int dir, int bridgeHeight) inline virtual
Reimplemented from Recipe.
Definition at line 51 of file RecipeCard.cs.
    {
        Mold.ignoreStackHeight = Input.GetKey(KeyCode.LeftControl);
        Mold.SetFreePos(point);
        freePos = Mold.freePos;
        fx = Mold.fx;
        fy = Mold.fy;
        Mold.RenderMarker(point, active, result, main, dir);
        if (!point.cell.skipRender)
        {
            Mold.trait.OnRenderTile(point, result, dir);
        }
    }
References Point.cell, Card.freePos, freePos, Card.fx, fx, Card.fy, fy, Mold, Trait.OnRenderTile(), Card.RenderMarker(), Card.SetFreePos(), Cell.skipRender, and Card.trait.
OnSelected()
override void RecipeCard.OnSelected () inline virtual
Reimplemented from Recipe.
Definition at line 116 of file RecipeCard.cs.
    {
        CreateMold();
    }
References CreateMold().
Rotate()
override void RecipeCard.Rotate () inline virtual
Reimplemented from Recipe.
Definition at line 520 of file RecipeCard.cs.
    {
        Mold.Rotate();
        _dir = Mold.dir;
        if ((bool)BuildMenu.Instance)
        {
            BuildMenu.Instance.info1.OnRotate();
        }
    }
References Recipe._dir, Card.dir, BuildMenu.info1, BuildMenu.Instance, Mold, UIRecipeInfo.OnRotate(), and Card.Rotate().
SetDir()
override void RecipeCard.SetDir (int d) inline virtual
Reimplemented from Recipe.
Definition at line 530 of file RecipeCard.cs.
    {
        Mold.dir = d;
        base.SetDir(d);
    }
WriteNote()
override void RecipeCard.WriteNote (UINote n) inline virtual
Reimplemented from Recipe.
Definition at line 536 of file RecipeCard.cs.
    {
        n.Clear();
        if (!Mold.isChara)
        {
            Mold.elements.AddNote(n);
        }
        n.Build();
    }
References ElementContainer.AddNote(), UINote.Build(), UINote.Clear(), Card.elements, Card.isChara, and Mold.
Member Data Documentation
_mold
Card RecipeCard._mold
Definition at line 18 of file RecipeCard.cs.
Referenced by CreateMold(), Duplicate(), and ButtonGrid.SetCraftRecipe().
_sourceCard
CardRow RecipeCard._sourceCard
Definition at line 7 of file RecipeCard.cs.
freePos
bool RecipeCard.freePos
Definition at line 10 of file RecipeCard.cs.
Referenced by Build(), and OnRenderMarker().
fx
float RecipeCard.fx
Definition at line 13 of file RecipeCard.cs.
Referenced by Build(), and OnRenderMarker().
fy
float RecipeCard.fy
Definition at line 16 of file RecipeCard.cs.
Referenced by Build(), and OnRenderMarker().
Property Documentation
CanRotate
override bool RecipeCard.CanRotate get
Definition at line 28 of file RecipeCard.cs.
idCard
string RecipeCard.idCard get
Definition at line 26 of file RecipeCard.cs.
Referenced by Build(), Craft(), and CreateMold().
isDish
bool RecipeCard.isDish get
Definition at line 34 of file RecipeCard.cs.
Referenced by BuildIngredientList(), and Craft().
IsThing
override bool RecipeCard.IsThing get
Definition at line 30 of file RecipeCard.cs.
Mold
override Card RecipeCard.Mold get
Definition at line 32 of file RecipeCard.cs.
Referenced by GetRenderer(), OnChangeIngredient(), OnRenderMarker(), Rotate(), ButtonGrid.SetCraftRecipe(), and WriteNote().
renderRow
override RenderRow RecipeCard.renderRow get
Definition at line 22 of file RecipeCard.cs.
sourceCard
CardRow RecipeCard.sourceCard get
Definition at line 20 of file RecipeCard.cs.
Referenced by Build(), CreateMold(), GetDetail(), and BuildMenu.RefreshCategory().
tileType
override TileType RecipeCard.tileType get
Definition at line 24 of file RecipeCard.cs.
The documentation for this class was generated from the following file:
Elin/RecipeCard.cs