Elin Decompiled Documentation: FactionBranch Class Reference
FactionBranch Class Reference
Classes
class Statistics
Public Member Functions
int GetNextExp (int _lv=-1)
int Evalue (int ele)
int GetProductBonus (Chara c)
void RefreshEfficiency ()
void Abandon ()
void OnCreate (Zone zone)
void SetOwner (Zone zone)
void OnActivateZone ()
void OnAfterSimulate ()
void OnUnloadMap ()
void OnSimulateHour (VirtualDate date)
void AutoClean ()
void OnSimulateDay (VirtualDate date)
void OnAdvanceDay ()
void OnSimulateMonth (VirtualDate date)
void GenerateGarbage (VirtualDate date)
bool TryTrash (Thing t)
void ReceivePackages (VirtualDate date)
void DailyOutcome (VirtualDate date)
void PutInMailBox (Thing t, bool outside=false, bool install=true)
Thing GetMailBox ()
Point GetMailBoxPos ()
int GetResidentTax ()
void CalcInnIncome ()
void CalcTourismIncome ()
void GetDailyIncome ()
Thing GetMeal (Chara c)
void OnClaimZone ()
void OnUnclaimZone ()
void ValidateUpgradePolicies ()
void Upgrade ()
bool CanUpgrade ()
int GetUpgradeCost ()
void ModExp (int a)
string GetHearthHint (int a)
void AddFeat (int ele, int v)
void AddMemeber (Chara c)
void ChangeMemberType (Chara c, FactionMemberType type)
void BanishMember (Chara c, bool sell=false)
void RemoveMemeber (Chara c)
int GetHappiness (FactionMemberType type)
bool IsAllDead ()
void Recruit (Chara c)
Chara GetMaid ()
string GetRandomName ()
int CountMembers (FactionMemberType type, bool onlyAlive=false)
int CountGuests ()
int CountWealthyGuests ()
void UpdateReqruits (bool clear=false)
void AddRecruit (Chara c)
void RemoveRecruit (Chara c)
int CountNewRecruits ()
void ClearNewRecruits ()
bool IsRecruit (Chara c)
int CountPasture ()
int GetPastureCost ()
int GetCivility ()
float GetHearthIncome ()
float GetHearthIncome (string id)
int GetTechUpgradeCost (Element e)
string Log (string idLang, string ref1=null, string ref2=null, string ref3=null, string ref4=null)
string Log (string idLang, Card c1, Card c2, string ref1=null, string ref2=null)
string Log (string idLang, Card c1, string ref1=null, string ref2=null, string ref3=null)
string LogRaw (string text, string col=null)
Public Attributes
int lv = 1
int rank
int exp
int seedPlan
int temper
int uidMaid
int lastUpdateReqruit
int incomeShop
GStability stability
HomeResourceManager resources = new HomeResourceManager()
ResearchManager researches = new ResearchManager()
PolicyManager policies = new PolicyManager()
HappinessManager happiness = new HappinessManager()
MeetingManager meetings = new MeetingManager()
Thing stash
MsgLog log
Religion faith
ExpeditionManager expeditions = new ExpeditionManager()
List< HireInfo > listRecruit = new List<HireInfo>()
int dateFound
int tourism
Statistics statistics = new Statistics()
Statistics lastStatistics = new Statistics()
Zone owner
int incomeInn
int incomeTourism
int efficiency = 100
List< Chara > members = new List<Chara>()
Properties
int Money [get]
int Worth [get]
int NumHeirloom [get]
int MaxAP [get]
int MaxPopulation [get]
int MaxSoil [get]
int ContentLV [get]
int DangerLV [get]
bool HasNetwork [get]
bool IsTaxFree [get]
string RankText [get]
string TextLv [get]
bool IsStartBranch [get]
ElementContainerZone elements [get]
int MaxLv [get]
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Additional Inherited Members
Static Public Member Functions inherited from EClass
static int rnd (int a)
static int curve (int a, int start, int step, int rate=75)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Static Public Attributes inherited from EClass
static Core core
Detailed Description
Definition at line 7 of file FactionBranch.cs.
Member Function Documentation
Abandon()
void FactionBranch.Abandon () inline
Definition at line 224 of file FactionBranch.cs.
    {
    }
AddFeat()
void FactionBranch.AddFeat (int ele, int v) inline
Definition at line 1270 of file FactionBranch.cs.
    {
        elements.ModBase(ele, v);
        WidgetPopText.Say("rewardElement".lang(EClass.sources.elements.map[ele].GetName()));
    }
References SourceManager.elements, WidgetPopText.Say(), and EClass.sources.
Referenced by ResearchPlan.ParseReward().
AddMemeber()
void FactionBranch.AddMemeber (Chara c) inline
Definition at line 1276 of file FactionBranch.cs.
    {
        if (!members.Contains(c))
        {
            EClass.Home.FindBranch(c)?.RemoveMemeber(c);
            EClass.Home.RemoveReserve(c);
            c.SetGlobal();
            c.SetFaction(EClass.Home);
            c.SetHomeZone(owner);
            if (c.OriginalHostility <= Hostility.Ally)
            {
                c.c_originalHostility = Hostility.Ally;
            }
            c.hostility = Hostility.Ally;
            c.enemy = null;
            c.orgPos = null;
            c.memberType = FactionMemberType.Default;
            if (c.hp > c.MaxHP)
            {
                c.hp = c.MaxHP;
            }
            if (c.mana.value > c.mana.max)
            {
                c.mana.value = c.mana.max;
            }
            if (c.stamina.value > c.stamina.max)
            {
                c.stamina.value = c.stamina.max;
            }
            members.Add(c);
            EClass.pc.faction.charaElements.OnAddMemeber(c);
            RefreshEfficiency();
            c.RefreshWorkElements(elements);
            if (uidMaid == 0 && c.id == "maid")
            {
                uidMaid = c.uid;
            }
        }
    }
References Faction.charaElements, Chara.faction, Faction.FindBranch(), EClass.Home, Card.hp, Card.id, Chara.mana, Stats.max, Chara.MaxHP, ElementContainerFaction.OnAddMemeber(), Chara.OriginalHostility, EClass.pc, Chara.RefreshWorkElements(), RemoveMemeber(), Faction.RemoveReserve(), Chara.SetFaction(), Chara.SetGlobal(), Chara.SetHomeZone(), Chara.stamina, Card.uid, and Stats.value.
Referenced by Chara._MakeAlly(), Zone.AbandonZone(), Zone.ClaimZone(), TraitFoodEggFertilized.Incubate(), QuestVernis.OnChangePhase(), QuestIntroInspector.OnComplete(), QuestVernis.OnComplete(), QuestDialog.OnDropReward(), Game.OnLoad(), QuestDebt.OnStart(), and CoreDebug.QuickStart().
AddRecruit()
void FactionBranch.AddRecruit (Chara c) inline
Definition at line 1518 of file FactionBranch.cs.
    {
        HireInfo hireInfo = new HireInfo
        {
            chara = c,
            isNew = true
        };
        hireInfo.deadline = EClass.world.date.GetRaw() + (EClass.rnd(5) + 1) * 1440 + EClass.rnd(24) * 60;
        listRecruit.Add(hireInfo);
    }
References World.date, Date.GetRaw(), EClass.rnd(), and EClass.world.
AutoClean()
void FactionBranch.AutoClean () inline
Definition at line 459 of file FactionBranch.cs.
    {
        foreach (Chara member in members)
        {
            if (member.IsPCParty || !member.ExistsOnMap || member.memberType != 0)
            {
                continue;
            }
            Hobby hobby = member.GetWork("Clean") ?? member.GetWork("Chore");
            if (hobby == null)
            {
                continue;
            }
            int num = (5 + EClass.rnd(5)) * hobby.GetEfficiency(member) / 100;
            for (int i = 0; i < num; i++)
            {
                Thing thingToClean = AI_Haul.GetThingToClean(member);
                if (thingToClean == null)
                {
                    break;
                }
                EClass._zone.TryAddThingInSharedContainer(thingToClean);
            }
        }
    }
References EClass._zone, Card.ExistsOnMap, Hobby.GetEfficiency(), AI_Haul.GetThingToClean(), Chara.GetWork(), Chara.IsPCParty, Chara.memberType, EClass.rnd(), and Zone.TryAddThingInSharedContainer().
BanishMember()
void FactionBranch.BanishMember (Chara c, bool sell = false) inline
Definition at line 1325 of file FactionBranch.cs.
    {
        RemoveMemeber(c);
        if (!sell)
        {
            Msg.Say("banish", c, EClass._zone.Name);
        }
        if (c.IsGlobal)
        {
            c.OnBanish();
        }
        else
        {
            c.Destroy();
        }
    }
References EClass._zone, Card.Destroy(), Chara.IsGlobal, Spatial.Name, Chara.OnBanish(), and Msg.Say().
Referenced by CoreDebug.RemoveDemitas(), and AI_Shopping.SellChara().
CalcInnIncome()
void FactionBranch.CalcInnIncome () inline
Definition at line 960 of file FactionBranch.cs.
    {
        int num = CountGuests();
        if (num == 0)
        {
            return;
        }
        int num2 = 0;
        int num3 = 0;
        foreach (Thing thing in EClass._map.things)
        {
            if (thing.IsInstalled && thing.trait is TraitBed traitBed && traitBed.owner.c_bedType == BedType.guest)
            {
                num2++;
                num3 += traitBed.owner.LV;
            }
        }
        num = Mathf.Min(num, num2);
        if (num != 0)
        {
            num3 /= num2;
            num3 = num3 * (100 + 5 * (int)Mathf.Sqrt(Evalue(2812))) / 100;
            float num4 = 10f + Mathf.Sqrt(num) * 10f;
            if (policies.IsActive(2813))
            {
                num4 += Mathf.Sqrt(CountWealthyGuests()) * 50f * (80f + 5f * Mathf.Sqrt(Evalue(2813))) / 100f;
            }
            if (policies.IsActive(2812))
            {
                num4 = num4 * (float)(100 + num3) / 100f;
            }
            num4 = Mathf.Min(num4, Mathf.Sqrt(Worth) / 15f + 5f);
            incomeInn += EClass.rndHalf((int)num4) + EClass.rndHalf((int)num4);
        }
    }
References EClass._map, Card.c_bedType, PolicyManager.IsActive(), Card.IsInstalled, Trait.owner, EClass.rndHalf(), Map.things, and Card.trait.
CalcTourismIncome()
void FactionBranch.CalcTourismIncome () inline
Definition at line 996 of file FactionBranch.cs.
    {
        int num = CountGuests();
        if (num != 0)
        {
            float num2 = 10f + Mathf.Sqrt(num) * 10f;
            if (policies.IsActive(2815))
            {
                num2 += Mathf.Sqrt(CountWealthyGuests()) * 50f * (80f + 5f * Mathf.Sqrt(Evalue(2815))) / 100f;
            }
            num2 = Mathf.Min(num2, Mathf.Sqrt(tourism) / 5f);
            incomeTourism += EClass.rndHalf((int)num2) + EClass.rndHalf((int)num2);
        }
    }
References PolicyManager.IsActive(), EClass.rndHalf(), and tourism.
CanUpgrade()
bool FactionBranch.CanUpgrade () inline
Definition at line 1209 of file FactionBranch.cs.
    {
        if (lv < MaxLv)
        {
            if (exp < GetNextExp())
            {
                return EClass.debug.enable;
            }
            return true;
        }
        return false;
    }
References EClass.debug, and CoreDebug.enable.
ChangeMemberType()
void FactionBranch.ChangeMemberType (Chara c, FactionMemberType type) inline
Definition at line 1316 of file FactionBranch.cs.
    {
        c.ClearBed();
        c.memberType = type;
        RefreshEfficiency();
        c.RefreshWorkElements(elements);
        policies.Validate();
    }
References Chara.ClearBed(), Chara.RefreshWorkElements(), and PolicyManager.Validate().
Referenced by TraitFoodEggFertilized.Incubate(), and BaseListPeople.OnClick().
ClearNewRecruits()
void FactionBranch.ClearNewRecruits () inline
Definition at line 1553 of file FactionBranch.cs.
    {
        foreach (HireInfo item in listRecruit)
        {
            item.isNew = false;
        }
    }
Referenced by LayerHire.OnKill(), and LayerQuestBoard.OnKill().
CountGuests()
int FactionBranch.CountGuests () inline
Definition at line 1433 of file FactionBranch.cs.
    {
        int num = 0;
        foreach (Chara chara in EClass._map.charas)
        {
            if (chara.memberType == FactionMemberType.Guest)
            {
                num++;
            }
        }
        return num;
    }
References EClass._map, Map.charas, and Chara.memberType.
CountMembers()
int FactionBranch.CountMembers (FactionMemberType type, bool onlyAlive = false) inline
Definition at line 1420 of file FactionBranch.cs.
    {
        int num = 0;
        foreach (Chara member in members)
        {
            if (member.memberType == type && member.trait.IsCountAsResident && (!onlyAlive || !member.isDead))
            {
                num++;
            }
        }
        return num;
    }
References TraitChara.IsCountAsResident, Chara.isDead, Chara.memberType, and Chara.trait.
Referenced by OnSimulateHour(), RefreshEfficiency(), ContentHomeReport.RefreshInfo(), and UIHomeInfo.RefreshInfo().
CountNewRecruits()
int FactionBranch.CountNewRecruits () inline
Definition at line 1540 of file FactionBranch.cs.
    {
        int num = 0;
        foreach (HireInfo item in listRecruit)
        {
            if (item.isNew)
            {
                num++;
            }
        }
        return num;
    }
References HireInfo.isNew.
CountPasture()
int FactionBranch.CountPasture () inline
Definition at line 1573 of file FactionBranch.cs.
    {
        return EClass._map.Stocked.GetNum("pasture", onlyShared: true) + EClass._map.Installed.GetNum("pasture");
    }
References EClass._map, Props.GetNum(), Map.Installed, and Map.Stocked.
Referenced by UIHomeInfo.RefreshInfo().
CountWealthyGuests()
int FactionBranch.CountWealthyGuests () inline
Definition at line 1446 of file FactionBranch.cs.
    {
        int num = 0;
        foreach (Chara chara in EClass._map.charas)
        {
            if (chara.memberType == FactionMemberType.Guest && chara.IsWealthy)
            {
                num++;
            }
        }
        return num;
    }
References EClass._map, Map.charas, Chara.IsWealthy, and Chara.memberType.
DailyOutcome()
void FactionBranch.DailyOutcome (VirtualDate date) inline
Definition at line 672 of file FactionBranch.cs.
    {
        Thing thing = null;
        Chara m;
        foreach (Chara member in members)
        {
            m = member;
            if (m.IsPCParty || !m.ExistsOnMap)
            {
                continue;
            }
            m.RefreshWorkElements(elements);
            if (m.memberType == FactionMemberType.Livestock)
            {
                if (thing == null)
                {
                    thing = EClass._map.Stocked.Find("pasture", -1, -1, shared: true) ?? EClass._map.Installed.Find("pasture");
                }
                if (thing == null)
                {
                    continue;
                }
                if (m.race.breeder >= EClass.rnd(2500 - (int)Mathf.Sqrt(Evalue(2827) * 100)))
                {
                    if (EClass.rnd(3) != 0)
                    {
                        Thing t2 = m.MakeEgg(date.IsRealTime, 1, date.IsRealTime);
                        if (!date.IsRealTime)
{
                            m.TryPutShared(t2);
                        }
                    }
                    else
                    {
                        Thing t3 = m.MakeMilk(date.IsRealTime, 1, date.IsRealTime);
                        if (!date.IsRealTime)
{
                            m.TryPutShared(t3);
                        }
                    }
                }
                if (m.HaveFur())
                {
                    m.c_fur++;
                }
                thing.ModNum(-1);
                if (thing.isDestroyed || thing.Num == 0)
                {
                    thing = null;
                }
                continue;
            }
            foreach (Hobby item in m.ListHobbies())
            {
                GetOutcome(item);
            }
            foreach (Hobby item2 in m.ListWorks())
            {
                GetOutcome(item2);
            }
        }
        int soilCost = EClass._zone.GetSoilCost();
        int num = Mathf.Min(100, 70 + (MaxSoil - soilCost));
        int flower = 5;
        int lv = 1;
        EClass._map.bounds.ForeachCell(delegate(Cell cell)
        {
            if (cell.obj != 0 && cell.sourceObj.tag.Contains("flower"))
            {
                PlantData plantData = cell.TryGetPlant();
                if (plantData != null && plantData.seed != null)
                {
                    lv += plantData.seed.encLV + 1;
                }
                else
                {
                    lv++;
                }
                flower++;
            }
        });
        lv /= flower;
        int num2 = 0;
        foreach (Thing thing6 in EClass._map.things)
        {
            if (thing6.IsInstalled && thing6.trait is TraitBeekeep && !thing6.things.IsFull())
            {
                flower -= 3 + EClass.rnd(5 + num2 * 4);
                num2++;
                if (flower < 0)
                {
                    break;
                }
                if (EClass.rnd(100) <= num)
                {
                    Thing thing2 = ThingGen.Create("honey");
                    thing2.SetEncLv(lv / 10);
                    thing2.elements.SetBase(2, EClass.curve(lv, 50, 10, 80));
                    thing6.AddThing(thing2);
                }
            }
        }
        void GetOutcome(Hobby h)
        {
            int num3 = h.GetEfficiency(m) * GetProductBonus(m) / 100;
            int num4 = h.GetLv(m);
            int id = EClass.sources.elements.alias[h.source.skill].id;
            if (!m.elements.HasBase(id))
            {
                m.elements.SetBase(id, 1);
            }
            m.ModExp(id, 100);
            for (int i = 0; i < h.source.things.Length; i += 2)
            {
                string text = h.source.things[i];
                int num5 = Mathf.Max(1, h.source.things[i + 1].ToInt() * num3 / 1000);
                int num6 = num5 / 1000;
                if (num5 % 1000 > EClass.rnd(1000))
                {
                    num6++;
                }
                if (num6 != 0)
                {
                    if (!(text == "_egg"))
                    {
                        if (text == "milk")
{
                            m.MakeMilk(date.IsRealTime, num6);
                        }
                        else
{
                            Thing thing3 = ((!text.StartsWith("#")) ? ThingGen.Create(h.source.things[i], -1, num4) : ThingGen.CreateFromCategory(text.Replace("#", ""), num4));
                            if (thing3 != null)
{
                                thing3.SetNum(thing3.trait.CraftNum * num6);
                                thing3.SetBlessedState(BlessedState.Normal);
                                thing3.TryMakeRandomItem(num4);
                                if (thing3.IsAmmo)
{
                                    thing3.ChangeMaterial("iron");
                                    thing3.c_IDTState = 0;
                                }
                                m.TryPutShared(thing3);
                            }
                        }
                    }
                    else
                    {
                        m.MakeEgg(date.IsRealTime, num6);
                    }
                }
            }
            switch (h.source.alias)
            {
            case "Nurse":
            {
                foreach (Chara member2 in members)
                {
                    if (!member2.IsPCParty)
                    {
                        if (member2.isDead && EClass.rnd(num3) > EClass.rnd(100))
{
                            Log("bNurse", m, member2);
                            member2.Revive(member2.pos, msg: true);
                            break;
                        }
                        if (EClass.rnd(num3) > EClass.rnd(100))
{
                            member2.CureHost(CureType.HealComplete);
                        }
                    }
                }
                break;
            }
            case "Chore":
            case "Clean":
            {
                for (int j = 0; j < num3 / 2; j++)
                {
                    Point randomPoint = EClass._map.bounds.GetRandomPoint();
                    if (randomPoint.HasDecal)
                    {
                        EClass._map.SetDecal(randomPoint.x, randomPoint.z);
                    }
                }
                break;
            }
            case "TreasureHunt":
                if (EClass.rnd(num3) > EClass.rnd(EClass.debug.enable ? 100 : 5000))
                {
                    Thing thing4 = EClass._zone.TryGetThingFromSharedContainer((Thing t) => t.trait is TraitScrollMapTreasure);
                    if (thing4 != null)
                    {
                        Thing thing5 = ThingGen.CreateTreasure("chest_treasure", thing4.LV);
                        m.TryPutShared(thing5);
                        thing4.Destroy();
                        WidgetPopText.Say("foundTreasure".lang(thing5.Name));
                    }
                }
                break;
            }
        }
    }
References EClass._map, EClass._zone, Map.bounds, Card.c_fur, Props.Find(), MapBounds.ForeachCell(), Zone.GetSoilCost(), Map.Installed, Card.isDestroyed, Card.ModNum(), Card.Num, Cell.obj, Chara.RefreshWorkElements(), EClass.rnd(), Cell.sourceObj, and Map.Stocked.
Evalue()
int FactionBranch.Evalue (int ele) inline
Definition at line 157 of file FactionBranch.cs.
    {
        SourceElement.Row row = EClass.sources.elements.map[ele];
        if (row.category == "policy")
        {
            return policies.GetValue(ele);
        }
        if (HasNetwork && row.tag.Contains("network"))
        {
            return EClass.pc.faction.elements.Value(ele) + elements.Value(ele);
        }
        return elements.Value(ele);
    }
References SourceElement.Row.category, Faction.elements, elements, SourceManager.elements, Chara.faction, PolicyManager.GetValue(), HasNetwork, EClass.pc, policies, EClass.sources, SourceElement.Row.tag, and ElementContainer.Value().
Referenced by Faction.EvadeTax(), Hobby.GetEfficiency(), Card.GetPrice(), HomeResourceWorth.GetPrice(), GetProductBonus(), Zone.GrowPlants(), HomeResourceWorth.ListHeirloom(), AI_Fish.Makefish(), and AI_Shopping.TryShop().
GenerateGarbage()
void FactionBranch.GenerateGarbage (VirtualDate date) inline
Definition at line 538 of file FactionBranch.cs.
    {
        int sortChance = 40 + GetCivility();
        int unsortedCount = 0;
        foreach (Chara member in members)
        {
            if (!member.IsPCParty && member.ExistsOnMap)
            {
                Hobby hobby = member.GetWork("Clean") ?? member.GetWork("Chore");
                if (hobby != null)
                {
                    sortChance += 20 * hobby.GetEfficiency(member) / 100;
                }
            }
        }
        int num = Evalue(2702);
        int num2 = EClass.rnd(2);
        for (int i = 0; i < num2; i++)
        {
            if (num == 0 || EClass.rnd(num + (EClass.debug.enable ? 100000 : 10)) == 0)
            {
                Generate(null);
            }
        }
        foreach (Chara member2 in members)
        {
            if (!member2.IsPCParty && member2.ExistsOnMap && (num == 0 || EClass.rnd(num + (EClass.debug.enable ? 100000 : 10)) == 0))
            {
                Generate(member2);
            }
        }
        void Generate(Chara c)
        {
            if (c == null || EClass.rnd(5) == 0)
            {
                if (EClass.rnd(80) == 0)
                {
                    Add(ThingGen.CreateFromCategory("junk"));
                }
                else if (EClass.rnd(40) == 0)
                {
                    Thing thing;
                    Add(thing = ThingGen.CreateFromTag("garbage"));
                }
                else
                {
                    string id = "trash2";
                    if (EClass.rnd(3) == 0)
                    {
                        id = "trash1";
                    }
                    if (EClass.rnd(10) == 0)
                    {
                        id = ((EClass.rnd(3) == 0) ? "529" : "1170");
                    }
                    if (c != null && (!c.IsUnique || c.memberType == FactionMemberType.Livestock) && EClass.rnd((c.memberType == FactionMemberType.Livestock) ? 2 : 50) == 0)
                    {
                        id = "_poop";
                    }
                    if (EClass.rnd(200000) == 0)
                    {
                        id = "goodness";
                    }
                    Add(ThingGen.Create(id));
                }
            }
            void Add(Thing t)
            {
                if (sortChance < EClass.rnd(100))
                {
                    EClass._zone.TryAddThing(t, (c != null) ? (c.pos.GetRandomPoint(2) ?? c.pos).GetNearestPoint() : EClass._zone.bounds.GetRandomSurface(), destroyIfFail: true);
                }
                else
                {
                    if (t.id == "_poop" && EClass.rnd(150) == 0)
                    {
                        t.ChangeMaterial((EClass.rnd(2) == 0) ? "silver" : "gold");
                    }
                    if (!TryTrash(t))
                    {
                        EClass._zone.AddCard(t, EClass._map.bounds.GetRandomSurface());
                        unsortedCount++;
                        if (unsortedCount >= 5)
{
                            Tutorial.Reserve("garbage");
                        }
                    }
                }
            }
        }
    }
References EClass._map, EClass._zone, Zone.AddCard(), Map.bounds, Zone.bounds, Card.ChangeMaterial(), ThingGen.Create(), ThingGen.CreateFromCategory(), ThingGen.CreateFromTag(), EClass.debug, CoreDebug.enable, Card.ExistsOnMap, Hobby.GetEfficiency(), Point.GetRandomPoint(), MapBounds.GetRandomSurface(), Chara.GetWork(), Card.id, Chara.IsPCParty, Card.IsUnique, Chara.memberType, Card.pos, Tutorial.Reserve(), EClass.rnd(), and Zone.TryAddThing().
GetCivility()
int FactionBranch.GetCivility () inline
Definition at line 1583 of file FactionBranch.cs.
    {
        int num = 10 + Evalue(2203);
        if (Evalue(2701) > 0)
        {
            num += 10 + (int)Mathf.Sqrt(Evalue(2701));
        }
        if (Evalue(2702) > 0)
        {
            num -= 10 + (int)Mathf.Sqrt(Evalue(2702));
        }
        return num;
    }
Referenced by UIHomeInfo.RefreshInfo().
GetDailyIncome()
void FactionBranch.GetDailyIncome () inline
Definition at line 1011 of file FactionBranch.cs.
    {
        GetIncome(ref incomeShop, ref statistics.shop, "getIncomeShop", tax: false);
        GetIncome(ref incomeInn, ref statistics.inn, "getIncomeInn", tax: true);
        GetIncome(ref incomeTourism, ref statistics.tourism, "getIncomeTourism", tax: true);
        void GetIncome(ref int n, ref int stat, string lang, bool tax)
        {
            if (tax && !IsTaxFree)
            {
                n = n * 10 / 100;
            }
            if (n != 0)
            {
                Msg.Say(lang, Lang._currency(n, "money"), owner.Name);
                Thing t = ThingGen.Create("money").SetNum(n);
                EClass.pc.Pick(t);
                stat += n;
                n = 0;
            }
        }
    }
References ThingGen.Create(), FactionBranch.Statistics.inn, Spatial.Name, EClass.pc, Chara.Pick(), Msg.Say(), Card.SetNum(), FactionBranch.Statistics.shop, and FactionBranch.Statistics.tourism.
Referenced by OnAfterSimulate().
GetHappiness()
int FactionBranch.GetHappiness (FactionMemberType type) inline
Definition at line 1359 of file FactionBranch.cs.
    {
        float num = 0f;
        if (members.Count == 0)
        {
            return 0;
        }
        foreach (Chara member in members)
        {
            num += (float)member.happiness;
        }
        return (int)(num / (float)members.Count);
    }
References Chara.happiness.
GetHearthHint()
string FactionBranch.GetHearthHint (int a) inline
Definition at line 1252 of file FactionBranch.cs.
    {
        if (a <= 1)
        {
            return "hearth1".lang();
        }
        string text = "";
        for (int i = 1; i < a; i++)
        {
            string text2 = ("hearth" + (i + 1)).lang();
            if (!text2.IsEmpty())
            {
                text = text + text2 + Environment.NewLine;
            }
        }
        return text.TrimEnd(Environment.NewLine.ToCharArray());
    }
Referenced by UIHomeInfo.RefreshInfo().
GetHearthIncome() [1/2]
float FactionBranch.GetHearthIncome () inline
Definition at line 1597 of file FactionBranch.cs.
    {
        float num = 0f;
        foreach (Element value in elements.dict.Values)
        {
            if (value.source.category == "culture")
            {
                num += GetHearthIncome(value.source.alias);
            }
        }
        return num;
    }
References Element.source.
GetHearthIncome() [2/2]
float FactionBranch.GetHearthIncome (string id) inline
Definition at line 1610 of file FactionBranch.cs.
    {
        int num = 0;
        foreach (KeyValuePair<int, Element> item in elements.dict)
        {
            if (item.Value.source.aliasParent == id)
            {
                num++;
            }
        }
        return 0.2f * (float)num;
    }
GetMaid()
Chara FactionBranch.GetMaid () inline
Definition at line 1399 of file FactionBranch.cs.
    {
        foreach (Chara member in members)
        {
            if (member.IsAliveInCurrentZone && member.IsMaid)
            {
                return member;
            }
        }
        return null;
    }
References Chara.IsAliveInCurrentZone, and Chara.IsMaid.
Referenced by MeetingManager.CallNext().
GetMailBox()
Thing FactionBranch.GetMailBox () inline
Definition at line 895 of file FactionBranch.cs.
    {
        return EClass._map.props.installed.FindEmptyContainer<TraitMailPost>();
    }
References EClass._map, PropsManager.installed, and Map.props.
GetMailBoxPos()
Point FactionBranch.GetMailBoxPos () inline
Definition at line 900 of file FactionBranch.cs.
    {
        Thing thing = GetMailBox();
        if (thing == null)
        {
            thing = EClass._map.props.installed.Find<TraitCoreZone>();
        }
        if (thing != null)
        {
            return thing.pos.GetNearestPoint(allowBlock: false, allowChara: true, allowInstalled: false, ignoreCenter: true).Clamp(useBounds: true);
        }
        return EClass._map.GetCenterPos();
    }
References EClass._map, Point.Clamp(), Props.Find(), MapBounds.GetCenterPos(), Point.GetNearestPoint(), PropsManager.installed, Card.pos, and Map.props.
GetMeal()
Thing FactionBranch.GetMeal (Chara c) inline
Definition at line 1033 of file FactionBranch.cs.
    {
        Thing thing = EClass._zone.TryGetThingFromSharedContainer((Thing t) => c.CanEat(t, shouldEat: true));
        if (thing != null)
        {
            thing = thing.Split(1);
        }
        return thing;
    }
References EClass._zone, Chara.CanEat(), Card.Split(), and Zone.TryGetThingFromSharedContainer().
Referenced by AI_Idle.Run().
GetNextExp()
int FactionBranch.GetNextExp (int _lv = -1) inline
Definition at line 148 of file FactionBranch.cs.
    {
        if (_lv == -1)
        {
            _lv = lv;
        }
        return _lv * _lv * 100 + 100;
    }
References lv.
Referenced by WidgetStatsBar.Build(), and LayerShippingResult.Refresh().
GetPastureCost()
int FactionBranch.GetPastureCost () inline
Definition at line 1578 of file FactionBranch.cs.
    {
        return CountMembers(FactionMemberType.Livestock);
    }
Referenced by UIHomeInfo.RefreshInfo().
GetProductBonus()
int FactionBranch.GetProductBonus (Chara c) inline
Definition at line 171 of file FactionBranch.cs.
    {
        if (c.isDead || c.IsPCParty)
        {
            return 0;
        }
        return Mathf.Max(1, (90 + Evalue(2116) / 2) * efficiency / 100);
    }
References efficiency, Evalue(), Chara.isDead, and Chara.IsPCParty.
GetRandomName()
string FactionBranch.GetRandomName () inline
Definition at line 1411 of file FactionBranch.cs.
    {
        if (EClass.rnd(4) == 0 || members.Count == 0)
        {
            return EClass.player.title;
        }
        return members.RandomItem().Name;
    }
References EClass.player, EClass.rnd(), and Player.title.
Referenced by BaseArea.GetRandomName().
GetResidentTax()
int FactionBranch.GetResidentTax () inline
Definition at line 914 of file FactionBranch.cs.
    {
        if (!policies.IsActive(2512, 30))
        {
            return 0;
        }
        int num = 0;
        int num2 = (policies.IsActive(2500, 30) ? Evalue(2500) : 0);
        int num3 = (policies.IsActive(2501, 30) ? Evalue(2501) : 0);
        int num4 = 50 + (int)Mathf.Sqrt(Evalue(2512)) * 5;
        foreach (Chara member in members)
        {
            if (member.IsPC || member.memberType != 0)
            {
                continue;
            }
            bool isWealthy = member.IsWealthy;
            int num5 = 0;
            foreach (Hobby item in member.ListWorks().Concat(member.ListHobbies()))
            {
                int num6 = item.source.tax * 100 / 100;
                if (num6 > num5)
                {
                    num5 = num6;
                }
            }
            int num7 = ((isWealthy ? 50 : 10) + member.LV * 2) * num5 / 100 * num4 / 100;
            if (isWealthy && num2 > 0)
            {
                num7 = num7 * (150 + (int)Mathf.Sqrt(num2) * 5) / 100;
            }
            if (num3 > 0)
            {
                num7 += (80 + (int)Mathf.Sqrt(num3) * 5) * member.faith.source.tax / 100;
            }
            num7 = num7 * efficiency / (IsTaxFree ? 100 : 1000);
            num += num7;
            if (num7 > 0)
            {
                Log("bTax", num7.ToString() ?? "", member.Name);
            }
        }
        statistics.tax += num;
        return num;
    }
References Chara.faith, PolicyManager.IsActive(), Chara.IsPC, Chara.IsWealthy, Chara.ListHobbies(), Chara.ListWorks(), Card.LV, Chara.memberType, Card.Name, and Religion.source.
Referenced by Faction.GetResidentTax().
GetTechUpgradeCost()
int FactionBranch.GetTechUpgradeCost (Element e) inline
Definition at line 1623 of file FactionBranch.cs.
    {
        int valueWithoutLink = e.ValueWithoutLink;
        valueWithoutLink += e.CostLearn;
        if (e.source.max != 0 && e.ValueWithoutLink >= e.source.max)
        {
            return 0;
        }
        return valueWithoutLink;
    }
References Element.CostLearn, Element.source, and Element.ValueWithoutLink.
Referenced by ButtonElement.Refresh(), and LayerHome.RefreshFeat().
GetUpgradeCost()
int FactionBranch.GetUpgradeCost () inline
Definition at line 1222 of file FactionBranch.cs.
    {
        return lv * lv * lv * 1000;
    }
IsAllDead()
bool FactionBranch.IsAllDead () inline
Definition at line 1373 of file FactionBranch.cs.
    {
        foreach (Chara member in members)
        {
            if (!member.isDead)
            {
                return false;
            }
        }
        return true;
    }
References Chara.isDead.
Referenced by ZoneEventSiege.OnTickRound().
IsRecruit()
bool FactionBranch.IsRecruit (Chara c) inline
Definition at line 1561 of file FactionBranch.cs.
    {
        foreach (HireInfo item in listRecruit)
        {
            if (item.chara == c)
            {
                return true;
            }
        }
        return false;
    }
References HireInfo.chara.
Referenced by DramaOutcome.chara_hired().
Log() [1/3]
string FactionBranch.Log (string idLang, Card c1, Card c2, string ref1 = null, string ref2 = null) inline
Definition at line 1640 of file FactionBranch.cs.
    {
        Msg.alwaysVisible = true;
        return LogRaw(Msg.GetRawText(idLang, c1, c2, ref1, ref2), EClass.sources.langGame.map[idLang].logColor);
    }
References Msg.GetRawText(), SourceManager.langGame, and EClass.sources.
Log() [2/3]
string FactionBranch.Log (string idLang, Card c1, string ref1 = null, string ref2 = null, string ref3 = null) inline
Definition at line 1646 of file FactionBranch.cs.
    {
        Msg.alwaysVisible = true;
        return LogRaw(Msg.GetRawText(idLang, c1, ref1, ref2, ref3), EClass.sources.langGame.map[idLang].logColor);
    }
References Msg.GetRawText(), SourceManager.langGame, and EClass.sources.
Log() [3/3]
string FactionBranch.Log (string idLang, string ref1 = null, string ref2 = null, string ref3 = null, string ref4 = null) inline
Definition at line 1634 of file FactionBranch.cs.
    {
        Msg.alwaysVisible = true;
        return LogRaw(Msg.GetRawText(idLang, ref1, ref2, ref3, ref4), EClass.sources.langGame.map[idLang].logColor);
    }
References Msg.GetRawText(), SourceManager.langGame, and EClass.sources.
Referenced by AI_Shopping.Buy(), Zone.ClaimZone(), Chara.Die(), Expedition.End(), ElementContainerCard.OnLevelUp(), ElementContainerZone.OnLevelUp(), Chara.Revive(), and Expedition.Start().
LogRaw()
string FactionBranch.LogRaw (string text, string col = null) inline
Definition at line 1652 of file FactionBranch.cs.
    {
        log.Add(text, col.IsEmpty() ? null : col);
        Msg.alwaysVisible = false;
        Msg.SetColor();
        return text;
    }
References MsgLog.Add(), and Msg.SetColor().
ModExp()
void FactionBranch.ModExp (int a) inline
Definition at line 1227 of file FactionBranch.cs.
    {
        if (policies.IsActive(2515))
        {
            return;
        }
        if (policies.IsActive(2516))
        {
            a = a * 150 / 100 + EClass.rnd(2);
        }
        exp += a;
        if (exp >= GetNextExp() && CanUpgrade())
        {
            if (EClass.core.version.demo && lv >= 3)
            {
                exp = 0;
                Msg.Say("demoLimit2");
            }
            else
            {
                Upgrade();
            }
        }
    }
References EClass.core, PolicyManager.IsActive(), EClass.rnd(), and Msg.Say().
OnActivateZone()
void FactionBranch.OnActivateZone () inline
Definition at line 265 of file FactionBranch.cs.
    {
        incomeInn = 0;
        incomeTourism = 0;
        foreach (Chara member in members)
        {
            if (member.IsAliveInCurrentZone && !member.pos.IsInBounds)
            {
                member.MoveImmediate(EClass._map.GetCenterPos().GetNearestPoint());
            }
            member.RefreshWorkElements(elements);
        }
        ValidateUpgradePolicies();
    }
References EClass._map, elements, MapBounds.GetCenterPos(), Point.GetNearestPoint(), incomeInn, incomeTourism, Chara.IsAliveInCurrentZone, Point.IsInBounds, members, Card.MoveImmediate(), Card.pos, Chara.RefreshWorkElements(), and ValidateUpgradePolicies().
OnAdvanceDay()
void FactionBranch.OnAdvanceDay () inline
Definition at line 512 of file FactionBranch.cs.
    {
        int num = 0;
        foreach (Chara member in members)
        {
            if (!member.IsPC && !member.isDead && member.memberType == FactionMemberType.Default)
            {
                if (EClass.rnd(3) == 0)
                {
                    num++;
                }
                if (member.GetWork("Pioneer") != null)
                {
                    num += 3;
                }
            }
        }
        ModExp(num);
    }
References Chara.GetWork(), Chara.isDead, Chara.IsPC, Chara.memberType, and EClass.rnd().
Referenced by Faction.OnAdvanceDay().
OnAfterSimulate()
void FactionBranch.OnAfterSimulate () inline
Definition at line 280 of file FactionBranch.cs.
    {
        if (!EClass.game.isLoading)
        {
            GetDailyIncome();
        }
    }
References EClass.game, GetDailyIncome(), and Game.isLoading.
Referenced by Zone.OnVisit().
OnClaimZone()
void FactionBranch.OnClaimZone () inline
Definition at line 1043 of file FactionBranch.cs.
    {
        if (EClass.debug.allHomeSkill)
        {
            foreach (SourceElement.Row item in EClass.sources.elements.rows.Where((SourceElement.Row a) => a.category == "tech"))
            {
                elements.SetBase(item.id, 1);
            }
            foreach (SourceElement.Row item2 in EClass.sources.elements.rows.Where((SourceElement.Row a) => a.category == "policy" && !a.tag.Contains("hidden")))
            {
                policies.AddPolicy(item2.id);
            }
        }
        else
        {
            elements.SetBase(2003, 1);
            elements.SetBase(4002, 1);
            elements.SetBase(2115, 1);
            elements.SetBase(2204, 1);
            elements.SetBase(2120, 1);
            policies.AddPolicy(2512);
            policies.AddPolicy(2702);
            policies.AddPolicy(2703);
            policies.AddPolicy(2516);
            policies.AddPolicy(2515);
            policies.AddPolicy(2514);
        }
        if (EClass.pc.faction.CountTaxFreeLand() < 3)
        {
            policies.Activate(2514);
        }
        Element element = EClass._zone.ListLandFeats()[0];
        elements.SetBase(element.id, 1);
        switch (element.id)
        {
        case 3604:
            elements.SetBase(2206, 10);
            break;
        case 3602:
            elements.SetBase(2206, 15);
            break;
        }
        if (EClass.game.StartZone == owner || owner is Zone_Vernis)
        {
            AddMemeber(EClass.pc);
        }
        if (EClass.debug.allPolicy)
        {
            foreach (SourceElement.Row item3 in EClass.sources.elements.rows.Where((SourceElement.Row a) => a.category == "policy"))
            {
                policies.AddPolicy(item3.id);
            }
        }
        ValidateUpgradePolicies();
    }
References EClass._zone, PolicyManager.Activate(), PolicyManager.AddPolicy(), CoreDebug.allHomeSkill, CoreDebug.allPolicy, Faction.CountTaxFreeLand(), EClass.debug, SourceManager.elements, Chara.faction, EClass.game, Card.id, Element.id, Zone.ListLandFeats(), EClass.pc, EClass.sources, and Game.StartZone.
Referenced by Zone.ClaimZone().
OnCreate()
void FactionBranch.OnCreate (Zone zone) inline
Definition at line 228 of file FactionBranch.cs.
    {
        SetOwner(zone);
        stash = ThingGen.Create("container_salary");
        stash.RemoveThings();
        faith = EClass.game.religions.Eyth;
        dateFound = EClass.world.date.GetRaw();
    }
References ThingGen.Create(), World.date, dateFound, ReligionManager.Eyth, faith, EClass.game, Date.GetRaw(), Game.religions, Card.RemoveThings(), SetOwner(), stash, and EClass.world.
Referenced by Zone.ClaimZone().
OnSimulateDay()
void FactionBranch.OnSimulateDay (VirtualDate date) inline
Definition at line 485 of file FactionBranch.cs.
    {
        if (owner == null || owner.mainFaction != EClass.Home)
        {
            return;
        }
        researches.OnSimulateDay();
        resources.OnSimulateDay();
        happiness.OnSimulateDay();
        if (!date.IsRealTime)
        {
            BranchMap branchMap = date.GetBranchMap();
            foreach (Chara member in members)
            {
                if (!member.IsPCParty && member.memberType != FactionMemberType.Livestock && !member.faith.IsEyth && !member.c_isPrayed && branchMap.altarMap.Contains(member.faith.id))
                {
                    AI_Pray.Pray(member, silent: true);
                }
            }
        }
        foreach (Chara member2 in members)
        {
            member2.c_isPrayed = false;
            member2.c_isTrained = false;
        }
    }
References Card.c_isPrayed, Chara.faith, VirtualDate.GetBranchMap(), EClass.Home, Religion.id, Religion.IsEyth, Chara.IsPCParty, VirtualDate.IsRealTime, Spatial.mainFaction, Chara.memberType, HappinessManager.OnSimulateDay(), HomeResourceManager.OnSimulateDay(), ResearchManager.OnSimulateDay(), and AI_Pray.Pray().
Referenced by Zone.OnSimulateDay().
OnSimulateHour()
void FactionBranch.OnSimulateHour (VirtualDate date) inline
Definition at line 292 of file FactionBranch.cs.
    {
        int num = CountMembers(FactionMemberType.Default, onlyAlive: true);
        int starveChance = Mathf.Max(num - MaxPopulation, 0);
        members.ForeachReverse(delegate(Chara c)
        {
            if (!c.IsPCParty && c.IsAliveInCurrentZone && !c.noMove)
            {
                if (EClass.rnd(24 * members.Count) < starveChance)
                {
                    starveChance--;
                }
                else
                {
                    c.TickWork(date);
                }
                if (!date.IsRealTime && EClass.rnd(3) != 0 && c.memberType == FactionMemberType.Default)
                {
                    c.hunger.Mod(1);
                    if (c.hunger.GetPhase() >= 3)
                    {
                        Thing meal = GetMeal(c);
                        if (meal != null)
{
                            FoodEffect.Proc(c, meal);
                            meal.Destroy();
                        }
                        else
{
                            c.hunger.Mod(-50);
                        }
                    }
                }
            }
        });
        expeditions.OnSimulateHour();
        meetings.OnSimulateHour(date);
        policies.OnSimulateHour(date);
        int num2 = Evalue(3707);
        int num3 = Evalue(3705) + Evalue(3710) * 2;
        int num4 = 4 + num3 * 4;
        int num5 = Mathf.Max(1, (100 + Evalue(2205) * 5 + Evalue(3703) * 100 - num2 * 80) / 10);
        int num6 = 10;
        if (policies.IsActive(2709))
        {
            num6 = 0;
        }
        if (EClass.world.date.IsNight)
        {
            num5 /= 2;
        }
        if ((date.IsRealTime || num2 > 0) && !EClass.debug.enable && EClass.rnd(num5) == 0 && !EClass.pc.IsDeadOrSleeping && EClass._map.CountHostile() < num4)
        {
            int num7 = 1 + EClass.rnd(num2 + num3 + 1);
            for (int i = 0; i < num7; i++)
            {
                EClass._zone.SpawnMob(null, SpawnSetting.HomeEnemy(DangerLV));
            }
        }
        if ((date.IsRealTime || num2 == 0) && num6 != 0 && EClass.rnd(num6) == 0 && EClass._map.CountWildAnimal() < num4)
        {
            EClass._zone.SpawnMob(null, SpawnSetting.HomeWild(5));
        }
        if (EClass.rnd(5) == 0 && policies.IsActive(2810))
        {
            int num8 = 3 + lv + Evalue(2206) / 5 + Evalue(3702) * 2 + Evalue(2202) / 2;
            num8 = num8 * (100 + Evalue(3702) * 20 + Evalue(2206)) / 100;
            num8 = num8 * (100 + (int)Mathf.Sqrt(Evalue(2811)) * 3) / 100;
            if (EClass._map.CountGuest() < num8)
            {
                Chara chara;
                if (policies.IsActive(2822) && Mathf.Sqrt(Evalue(2822) / 2) + 5f >= (float)EClass.rnd(100))
                {
                    chara = CharaGen.CreateWealthy(ContentLV);
                    EClass._zone.AddCard(chara, EClass._zone.GetSpawnPos(SpawnPosition.Random) ?? EClass._map.GetRandomSurface());
                }
                else
                {
                    chara = EClass._zone.SpawnMob(null, SpawnSetting.HomeGuest(ContentLV));
                }
                if (chara != null && (chara.id == "nun_mother" || chara.id == "prostitute") && policies.IsActive(2710))
                {
                    chara.Destroy();
                    chara = null;
                }
                if (chara != null)
                {
                    statistics.visitor++;
                    chara.memberType = FactionMemberType.Guest;
                    chara.SetInt(34, EClass.world.date.GetRaw());
                    chara.c_allowance = chara.LV * 100;
                    if (chara.IsWealthy)
                    {
                        chara.c_allowance *= 10;
                    }
                    if (date.IsRealTime)
                    {
                        Msg.Say("guestArrive", chara.Name);
                    }
                    else
                    {
                        chara.TryAssignBed();
                    }
                }
            }
        }
        foreach (Chara chara3 in EClass._map.charas)
        {
            if (chara3.memberType == FactionMemberType.Guest && ((chara3.c_allowance <= 0 && EClass.rnd(2) == 0) || chara3.GetInt(34) + 10080 < EClass.world.date.GetRaw()))
            {
                if (!chara3.IsGlobal)
                {
                    chara3.Destroy();
                }
                chara3.ClearBed();
                break;
            }
        }
        if (date.hour == 5)
        {
            DailyOutcome(date);
            GenerateGarbage(date);
            if (!date.IsRealTime)
            {
                AutoClean();
            }
            CalcTourismIncome();
            CalcInnIncome();
            if (date.IsRealTime)
            {
                GetDailyIncome();
            }
        }
        if (!EClass.player.simulatingZone && date.hour == 6)
        {
            ReceivePackages(date);
        }
        if (!date.IsRealTime && date.hour % 8 == 0)
        {
            foreach (Chara item in EClass._map.charas.Where((Chara c) => c.memberType == FactionMemberType.Guest).ToList())
            {
                for (int j = 0; j < 3; j++)
                {
                    AI_Shopping.TryShop(item, realtime: false);
                }
            }
            AI_Shopping.TryRestock(EClass.pc, realtime: false);
        }
        if (EClass.rnd(24) == 0 || EClass.debug.enable)
        {
            foreach (Thing thing in EClass._map.things)
            {
                if (EClass.rnd(20) == 0 && thing.trait is TraitFoodEggFertilized && thing.pos.FindThing<TraitBed>() != null)
                {
                    Chara chara2 = TraitFoodEggFertilized.Incubate(thing, thing.pos);
                    thing.ModNum(-1);
                    if (date.IsRealTime)
                    {
                        chara2.PlaySound("egg");
                    }
                    break;
                }
            }
        }
        resources.SetDirty();
    }
References CountMembers(), Chara.IsAliveInCurrentZone, Chara.IsPCParty, VirtualDate.IsRealTime, MaxPopulation, members, Chara.memberType, Card.noMove, and EClass.rnd().
Referenced by Zone.OnSimulateHour().
OnSimulateMonth()
void FactionBranch.OnSimulateMonth (VirtualDate date) inline
Definition at line 532 of file FactionBranch.cs.
    {
        lastStatistics = statistics;
        statistics = new Statistics();
    }
Referenced by Zone.OnSimulateMonth().
OnUnclaimZone()
void FactionBranch.OnUnclaimZone () inline
Definition at line 1099 of file FactionBranch.cs.
    {
    }
Referenced by Zone.AbandonZone().
OnUnloadMap()
void FactionBranch.OnUnloadMap () inline
Definition at line 288 of file FactionBranch.cs.
    {
    }
Referenced by Zone.UnloadMap().
PutInMailBox()
void FactionBranch.PutInMailBox (Thing t, bool outside = false, bool install = true) inline
Definition at line 876 of file FactionBranch.cs.
    {
        if (!outside)
        {
            Thing mailBox = GetMailBox();
            if (mailBox != null)
            {
                mailBox.AddCard(t);
                return;
            }
        }
        Point mailBoxPos = GetMailBoxPos();
        EClass._zone.AddCard(t, mailBoxPos);
        if (install)
        {
            t.Install();
        }
    }
References EClass._zone, Card.AddCard(), Zone.AddCard(), and Card.Install().
ReceivePackages()
void FactionBranch.ReceivePackages (VirtualDate date) inline
Definition at line 641 of file FactionBranch.cs.
    {
        if (EClass.player.simulatingZone)
        {
            return;
        }
        List<Thing> listPackage = EClass.game.cards.listPackage;
        if (EClass.player.stats.days >= 2 && !EClass.player.flags.elinGift && Steam.HasDLC(ID_DLC.BackerReward))
        {
            listPackage.Add(ThingGen.Create("gift"));
            EClass.player.flags.elinGift = true;
        }
        if (listPackage.Count == 0)
        {
            return;
        }
        SE.Play("notice");
        int num = 0;
        foreach (Thing item in listPackage)
        {
            if (item.id != "bill")
            {
                num++;
            }
            PutInMailBox(item, item.id == "cardboard_box" || item.id == "gift");
            WidgetPopText.Say("popDeliver".lang(item.Name));
        }
        Msg.Say("deliver_arrive", num.ToString() ?? "");
        listPackage.Clear();
    }
References ActPlan.List.Add(), Game.cards, ThingGen.Create(), Player.Stats.days, Player.Flags.elinGift, Player.flags, EClass.game, Steam.HasDLC(), Card.id, CardManager.listPackage, Card.Name, EClass.player, Msg.Say(), WidgetPopText.Say(), Player.simulatingZone, and Player.stats.
Recruit()
void FactionBranch.Recruit (Chara c) inline
Definition at line 1385 of file FactionBranch.cs.
    {
        RemoveRecruit(c);
        AddMemeber(c);
        if (c.currentZone != EClass._zone && !c.isDead)
        {
            Point point = EClass._map.Installed.traits.GetTraitSet<TraitSpotExit>().GetRandom()?.GetPoint() ?? EClass.pc.pos;
            EClass._zone.AddCard(c, point);
        }
        RefreshEfficiency();
        c.RefreshWorkElements();
        Msg.Say("hire".langGame(c.Name));
    }
References EClass._map, EClass._zone, Zone.AddCard(), Chara.currentZone, Trait.GetPoint(), TraitManager.GetTraitSet(), Map.Installed, Chara.isDead, Card.Name, EClass.pc, Card.pos, Chara.RefreshWorkElements(), Msg.Say(), and Props.traits.
Referenced by DramaOutcome.chara_hired(), DramaOutcome.chara_hired_ticket(), and DramaOutcome.QuestExploration_MeetFarris2().
RefreshEfficiency()
void FactionBranch.RefreshEfficiency () inline
Definition at line 180 of file FactionBranch.cs.
    {
        int num = 100;
        int num2 = CountMembers(FactionMemberType.Default);
        int ration = 0;
        foreach (Chara member in members)
        {
            if (member.memberType != 0)
            {
                continue;
            }
            if (member.IsPCParty || member.homeBranch == null || member.homeBranch.owner == null)
            {
                return;
            }
            foreach (Hobby item in member.ListHobbies())
            {
                TryAdd(item);
            }
            foreach (Hobby item2 in member.ListWorks())
            {
                TryAdd(item2);
            }
        }
        if (num2 > MaxPopulation)
        {
            num -= (num2 - MaxPopulation) * 20 * 100 / (100 + 20 * (int)Mathf.Sqrt(ration));
        }
        efficiency = num;
        void TryAdd(Hobby h)
        {
            if (!h.source.elements.IsEmpty())
            {
                for (int i = 0; i < h.source.elements.Length; i += 2)
                {
                    if (h.source.elements[i] == 2207)
                    {
                        ration += h.source.elements[i + 1];
                    }
                }
            }
        }
    }
References CountMembers(), efficiency, Chara.homeBranch, Chara.IsPCParty, Chara.ListHobbies(), Chara.ListWorks(), MaxPopulation, members, Chara.memberType, owner, and Hobby.source.
Referenced by Party.AddMemeber(), Party.RemoveMember(), and SetOwner().
RemoveMemeber()
void FactionBranch.RemoveMemeber (Chara c) inline
Definition at line 1342 of file FactionBranch.cs.
    {
        c.isSale = false;
        if (c.currentZone != null && c.currentZone.map != null)
        {
            c.ClearBed(c.currentZone.map);
            c.currentZone.map.props.sales.Remove(c);
        }
        c.RefreshWorkElements();
        c.RemoveGlobal();
        members.Remove(c);
        EClass.pc.faction.charaElements.OnRemoveMember(c);
        c.SetFaction(EClass.game.factions.Wilds);
        policies.Validate();
        RefreshEfficiency();
    }
References Faction.charaElements, Chara.ClearBed(), Chara.currentZone, Chara.faction, Game.factions, EClass.game, Zone.map, ElementContainerFaction.OnRemoveMember(), EClass.pc, Map.props, Chara.RefreshWorkElements(), Chara.RemoveGlobal(), PropsManager.sales, Chara.SetFaction(), PolicyManager.Validate(), and FactionManager.Wilds.
Referenced by AddMemeber(), Faction.AddReserve(), and QuestDebt.OnStart().
RemoveRecruit()
void FactionBranch.RemoveRecruit (Chara c) inline
Definition at line 1529 of file FactionBranch.cs.
    {
        listRecruit.ForeachReverse(delegate(HireInfo i)
        {
            if (i.chara == c)
            {
                listRecruit.Remove(i);
            }
        });
    }
References HireInfo.chara.
SetOwner()
void FactionBranch.SetOwner (Zone zone) inline
Definition at line 237 of file FactionBranch.cs.
    {
        owner = zone;
        resources.SetOwner(this);
        researches.SetOwner(this);
        policies.SetOwner(this);
        happiness.SetOwner(this);
        expeditions.SetOwner(this);
        meetings.SetOwner(this);
        foreach (Chara value in EClass.game.cards.globalCharas.Values)
        {
            if (value == null)
            {
                Debug.LogError("exception: c==null");
            }
            else if (EClass.pc == null)
            {
                Debug.LogError("exception: pc==null");
            }
            else if (value.homeZone == zone && value.faction == EClass.pc.faction)
            {
                members.Add(value);
                EClass.pc.faction.charaElements.OnAddMemeber(value);
            }
        }
        RefreshEfficiency();
    }
References Game.cards, Faction.charaElements, expeditions, Chara.faction, EClass.game, CardManager.globalCharas, happiness, Chara.homeZone, meetings, members, ElementContainerFaction.OnAddMemeber(), owner, EClass.pc, policies, RefreshEfficiency(), researches, resources, ExpeditionManager.SetOwner(), MeetingManager.SetOwner(), ResearchManager.SetOwner(), HappinessManager.SetOwner(), HomeResourceManager.SetOwner(), and PolicyManager.SetOwner().
Referenced by OnCreate(), and Zone.OnLoad().
TryTrash()
bool FactionBranch.TryTrash (Thing t) inline
Definition at line 630 of file FactionBranch.cs.
    {
        Thing thing = ((t.id == "_poop") ? EClass._map.props.installed.FindEmptyContainer<TraitContainerCompost>(t) : (t.isFireproof ? EClass._map.props.installed.FindEmptyContainer<TraitContainerUnburnable>(t) : EClass._map.props.installed.FindEmptyContainer<TraitContainerBurnable>(t)));
        if (thing != null)
        {
            thing.AddCard(t);
            return true;
        }
        return EClass._zone.TryAddThingInSpot<TraitSpotGarbage>(t, useContainer: false, putRandomPosIfNoSpot: false);
    }
References EClass._map, EClass._zone, Card.AddCard(), PropsManager.installed, and Map.props.
UpdateReqruits()
void FactionBranch.UpdateReqruits (bool clear = false) inline
Definition at line 1459 of file FactionBranch.cs.
    {
        resources.Refresh();
        if (clear)
        {
            listRecruit.ForeachReverse(delegate(HireInfo i)
            {
                if (!i.chara.IsGlobal)
                {
                    i.chara.Destroy();
                }
                if (i.chara.isDestroyed)
                {
                    listRecruit.Remove(i);
                }
            });
            listRecruit.Clear();
            lastUpdateReqruit = -1;
        }
        else
        {
            listRecruit.ForeachReverse(delegate(HireInfo i)
            {
                if (i.Hours < 0)
                {
                    if (!i.chara.IsGlobal)
                    {
                        i.chara.Destroy();
                    }
                    listRecruit.Remove(i);
                }
            });
        }
        if (lastUpdateReqruit == EClass.world.date.day)
        {
            return;
        }
        lastUpdateReqruit = EClass.world.date.day;
        int num = 2 + (int)Mathf.Sqrt(Evalue(2513)) / 2;
        int num2 = EClass.rnd(3 + (int)Mathf.Sqrt(Evalue(2513)) / 2) + num - listRecruit.Count;
        if (num2 <= 0)
        {
            return;
        }
        new List<Chara>(EClass.game.cards.globalCharas.Values).Shuffle();
        for (int j = 0; j < num2; j++)
        {
            Chara chara = CharaGen.CreateFromFilter("c_neutral", ContentLV + Mathf.Min(EClass.player.stats.days, 10));
            if (chara.isBackerContent)
            {
                j--;
            }
            else
            {
                AddRecruit(chara);
            }
        }
    }
References HireInfo.chara, HireInfo.Hours, Card.isDestroyed, Chara.IsGlobal, and HomeResourceManager.Refresh().
Referenced by LayerQuestBoard.OnInit().
Upgrade()
void FactionBranch.Upgrade () inline
Definition at line 1136 of file FactionBranch.cs.
    {
        List<Element> list = owner.ListLandFeats();
        if (owner.IsActiveZone)
        {
            TraitCoreZone traitCoreZone = EClass._map.FindThing<TraitCoreZone>();
            if (traitCoreZone != null)
            {
                SE.Play("godbless");
                traitCoreZone.owner.PlayEffect("aura_heaven");
            }
        }
        lv++;
        exp = 0;
        int admin = 4;
        int food = 4;
        Set(4, 3);
        switch (list[0].id)
        {
        case 3500:
            Set(5, 3);
            break;
        case 3604:
            Set(4, 3);
            break;
        case 3600:
            Set(5, 3);
            break;
        case 3601:
            Set(4, 4);
            break;
        case 3603:
            Set(6, 2);
            break;
        case 3602:
            Set(5, 2);
            break;
        }
        elements.SetBase(2003, Mathf.Min((lv - 1) * 2 + 1, 10));
        elements.SetBase(2115, (lv - 1) * admin + 1);
        elements.SetBase(2204, (lv - 1) * food + 1);
        elements.GetElement(2003).CheckLevelBonus(elements);
        ValidateUpgradePolicies();
        if (lv == 4)
        {
            elements.SetBase(list[1].id, 1);
        }
        if (lv == 7)
        {
            elements.SetBase(list[2].id, 1);
        }
        if (lv >= 5)
        {
            List<Element> list2 = elements.dict.Values.Where((Element a) => a.source.category == "landfeat" && a.HasTag("network")).ToList();
            foreach (Element item in list2)
            {
                EClass.pc.faction.elements.ModBase(item.id, item.Value);
            }
            foreach (Element item2 in list2)
            {
                elements.Remove(item2.id);
            }
        }
        Msg.Say("upgrade_hearth", lv.ToString() ?? "", owner.Name);
        LogRaw("upgrade_hearth".langGame(lv.ToString() ?? "", owner.Name), "Good");
        Tutorial.Reserve("stone");
        void Set(int a, int f)
        {
            admin = a;
            food = f;
        }
    }
References EClass._map, Faction.elements, Chara.faction, Map.FindThing(), food, Element.HasTag(), Element.id, Zone.IsActiveZone, Zone.ListLandFeats(), ElementContainer.ModBase(), Spatial.Name, Trait.owner, EClass.pc, Card.PlayEffect(), Tutorial.Reserve(), Msg.Say(), Element.source, and Element.Value.
ValidateUpgradePolicies()
void FactionBranch.ValidateUpgradePolicies () inline
Definition at line 1103 of file FactionBranch.cs.
    {
        if (lv >= 2)
        {
            if (!policies.HasPolicy(2705))
            {
                policies.AddPolicy(2705);
                EClass.pc.faction.SetGlobalPolicyActive(2705, EClass.pc.faction.IsGlobalPolicyActive(2705));
            }
            if (!policies.HasPolicy(2708))
            {
                policies.AddPolicy(2708);
                EClass.pc.faction.SetGlobalPolicyActive(2708, EClass.pc.faction.IsGlobalPolicyActive(2708));
            }
            if (!policies.HasPolicy(2707))
            {
                policies.AddPolicy(2707);
            }
            if (!policies.HasPolicy(2709))
            {
                policies.AddPolicy(2709);
            }
        }
        foreach (int globalPolicy in EClass.pc.faction.globalPolicies)
        {
            if (!policies.HasPolicy(globalPolicy))
            {
                policies.AddPolicy(globalPolicy, show: false);
                EClass.pc.faction.SetGlobalPolicyActive(globalPolicy, EClass.pc.faction.IsGlobalPolicyActive(globalPolicy));
            }
        }
    }
References PolicyManager.AddPolicy(), Chara.faction, Faction.globalPolicies, PolicyManager.HasPolicy(), Faction.IsGlobalPolicyActive(), EClass.pc, and Faction.SetGlobalPolicyActive().
Referenced by OnActivateZone(), and TraitBookSkill.OnRead().
Member Data Documentation
dateFound
int FactionBranch.dateFound
Definition at line 97 of file FactionBranch.cs.
Referenced by OnCreate(), and UIHomeInfo.RefreshInfo().
efficiency
int FactionBranch.efficiency = 100
Definition at line 114 of file FactionBranch.cs.
Referenced by GetProductBonus(), RefreshEfficiency(), and UIHomeInfo.RefreshReport().
exp
int FactionBranch.exp
Definition at line 40 of file FactionBranch.cs.
Referenced by WidgetStatsBar.Build(), and GameDate.ShipGoods().
expeditions
ExpeditionManager FactionBranch.expeditions = new ExpeditionManager()
Definition at line 91 of file FactionBranch.cs.
Referenced by Expedition.End(), ListPeopleExpedition.OnClick(), SetOwner(), and Chara.TryWorkOutside().
faith
Religion FactionBranch.faith
Definition at line 88 of file FactionBranch.cs.
Referenced by OnCreate(), ContentHomeReport.RefreshInfo(), and UIHomeInfo.RefreshInfo().
happiness
HappinessManager FactionBranch.happiness = new HappinessManager()
Definition at line 73 of file FactionBranch.cs.
Referenced by Policy.ModHappiness(), PolicyManager.RefreshEffects(), ContentHomeReport.RefreshInfo(), UIHomeInfo.RefreshInfo(), and SetOwner().
incomeInn
int FactionBranch.incomeInn
Definition at line 110 of file FactionBranch.cs.
Referenced by OnActivateZone().
incomeShop
int FactionBranch.incomeShop
Definition at line 55 of file FactionBranch.cs.
incomeTourism
int FactionBranch.incomeTourism
Definition at line 112 of file FactionBranch.cs.
Referenced by OnActivateZone().
lastStatistics
Statistics FactionBranch.lastStatistics = new Statistics()
Definition at line 106 of file FactionBranch.cs.
Referenced by ItemStatistics.Refresh().
lastUpdateReqruit
int FactionBranch.lastUpdateReqruit
Definition at line 52 of file FactionBranch.cs.
listRecruit
List<HireInfo> FactionBranch.listRecruit = new List<HireInfo>()
Definition at line 94 of file FactionBranch.cs.
Referenced by LayerQuestBoard.RefreshHire().
log
MsgLog FactionBranch.log
Initial value:
= new MsgLog
    {
        id = "log"
    }
Definition at line 82 of file FactionBranch.cs.
Referenced by ContentHomeLog.RefreshLog(), and GameDate.ShipGoods().
lv
int FactionBranch.lv = 1
Definition at line 34 of file FactionBranch.cs.
Referenced by Card.Create(), ActEffect.DamageEle(), Faction.GetMaxReserve(), GetNextExp(), Quest.Init(), UIHomeInfo.RefreshInfo(), ContentPolicy.RefreshPolicy(), UIFactionInfo.SetZone(), GameDate.ShipGoods(), and Map.TryShatter().
meetings
MeetingManager FactionBranch.meetings = new MeetingManager()
Definition at line 76 of file FactionBranch.cs.
Referenced by DramaCustomSequence.Build(), Meeting.OnEndDrama(), UIHomeInfo.RefreshReport(), and SetOwner().
members
List<Chara> FactionBranch.members = new List<Chara>()
Definition at line 116 of file FactionBranch.cs.
Referenced by Zone.AbandonZone(), Happiness.CountMembers(), Zone.Deactivate(), Faction.FindBranch(), CoreDebug.Fix_RemoveDuplicateUnique(), HomeResourceEducation.GetDestValue(), HomeResourceSafety.GetDestValue(), Happiness.GetTargetValue(), QuestCompanion.GetTextProgress(), HappinessSummary.HappinessSummary(), OnActivateZone(), BaseListPeople.OnList(), ListPeopleExpedition.OnList(), Game.OnLoad(), OnSimulateHour(), TraitGeneMachine.OnUse(), TraitGeneratorWheel.OnUse(), Card.PurgeDuplicateArtifact(), TCOrbitChara.RefreshAll(), RefreshEfficiency(), UIHomeInfo.RefreshReport(), DramaOutcome.revive_pet(), AI_AttackHome.Run(), AI_Idle.Run(), SetOwner(), and Msg.TalkHomeMemeber().
owner
Zone FactionBranch.owner
Definition at line 108 of file FactionBranch.cs.
Referenced by Zone.AbandonZone(), Party.AddMemeber(), CoreDebug.COM_MaxConstruction(), Expedition.End(), Hobby.GetEfficiency(), RankedZoneManager.GetIncome(), Faction.GetRankIncome(), Game.OnLoad(), TraitDeedRelocate.OnRead(), QuestDebt.OnStart(), ContentHomeReport.OnSwitchContent(), UIHomeInfo.Refresh(), RefreshEfficiency(), UIHomeInfo.RefreshReport(), Chara.RefreshWorkElements(), SetOwner(), Player.SimulateFaction(), HomeResourceWorth.UpdateRank(), and TraitBookPlan.WriteNote().
policies
PolicyManager FactionBranch.policies = new PolicyManager()
Definition at line 70 of file FactionBranch.cs.
Referenced by Party.AddMemeber(), UICurrency.Build(), Faction.CountTaxFreeLand(), Evalue(), Card.GetPrice(), HomeResourceWorth.GetPrice(), Happiness.GetTargetValue(), Zone.GrowPlants(), Faction.IsGlobalPolicyActive(), Chara.MoveHome(), Faction.OnAdvanceMonth(), TraitBookSkill.OnRead(), ContentPolicy.OnSwitchContent(), ResearchPlan.ParseReward(), ContentPolicy.RefreshPolicyIcons(), LayerPolicy.RefreshPolicyIcons(), ContentPolicy.RefreshPolicyList(), LayerPolicy.RefreshPolicyList(), AI_Idle.Run(), Faction.SetGlobalPolicyActive(), SetOwner(), GameDate.ShipRandomPackages(), and AI_Shopping.TryShop().
rank
int FactionBranch.rank
Definition at line 37 of file FactionBranch.cs.
Referenced by ContentHomeReport.RefreshInfo(), UIHomeInfo.RefreshInfo(), and TraitAltar.TrySetAct().
researches
ResearchManager FactionBranch.researches = new ResearchManager()
Definition at line 67 of file FactionBranch.cs.
Referenced by ResearchManager.IsListBarter(), LayerHome.RefreshFocus(), LayerTech.RefreshFocus(), UIHomeInfo.RefreshReport(), LayerTech.RefreshTech(), LayerHome.RefreshTech(), SetOwner(), ItemResearch.SetPlan(), and ResearchManager.ShowNewPlans().
resources
HomeResourceManager FactionBranch.resources = new HomeResourceManager()
Definition at line 64 of file FactionBranch.cs.
Referenced by UICurrency.Build(), ResearchManager.CanCompletePlan(), Faction.CountWealth(), Happiness.GetTargetValue(), InvOwner.InvOwner(), Expedition.OnCreate(), DramaManager.ParseLine(), UIHomeInfo.Refresh(), PolicyManager.RefreshEffects(), UIHomeInfo.RefreshInfo(), ContentHomeReport.RefreshResources(), UIHomeInfo.RefreshResources(), SetOwner(), Card.SetPlaceState(), ItemResearch.SetPlan(), UIFactionInfo.SetZone(), TraitCoreZone.TrySetAct(), GameUpdater.Update100ms(), and TraitWrench.Upgrade().
seedPlan
int FactionBranch.seedPlan
Definition at line 43 of file FactionBranch.cs.
Referenced by ResearchManager.ShowNewPlans().
stability
GStability FactionBranch.stability
Initial value:
= new GStability
    {
        value = 1
    }
Definition at line 58 of file FactionBranch.cs.
stash
Thing FactionBranch.stash
Definition at line 79 of file FactionBranch.cs.
Referenced by OnCreate().
statistics
Statistics FactionBranch.statistics = new Statistics()
Definition at line 103 of file FactionBranch.cs.
Referenced by ContentHomeLog.OnSwitchContent().
temper
int FactionBranch.temper
Definition at line 46 of file FactionBranch.cs.
Referenced by UIHomeInfo.RefreshInfo().
tourism
int FactionBranch.tourism
Definition at line 100 of file FactionBranch.cs.
Referenced by WidgetStatsBar.Build(), and HomeResourceWorth.WriteNote().
uidMaid
int FactionBranch.uidMaid
Definition at line 49 of file FactionBranch.cs.
Referenced by Faction.AddReserve(), BaseListPeople.OnClick(), ItemGeneral.SetChara(), and Msg.TalkMaid().
Property Documentation
ContentLV
int FactionBranch.ContentLV get
Definition at line 130 of file FactionBranch.cs.
DangerLV
int FactionBranch.DangerLV get
Definition at line 132 of file FactionBranch.cs.
elements
ElementContainerZone FactionBranch.elements get
Definition at line 144 of file FactionBranch.cs.
Referenced by Party.AddMemeber(), PolicyManager.AddPolicy(), Evalue(), OnActivateZone(), TraitBookSkill.OnRead(), ButtonElement.Refresh(), ItemCulture.Refresh(), LayerHome.RefreshFeat(), HotbarManager.ResetHotbar(), TraitBookSkill.SetName(), BuildMenu.Toggle(), and TraitBookPlan.WriteNote().
HasNetwork
bool FactionBranch.HasNetwork get
Definition at line 134 of file FactionBranch.cs.
Referenced by Evalue(), ButtonElement.Refresh(), and TraitTeleporter.TryTeleport().
IsStartBranch
bool FactionBranch.IsStartBranch get
Definition at line 142 of file FactionBranch.cs.
IsTaxFree
bool FactionBranch.IsTaxFree get
Definition at line 136 of file FactionBranch.cs.
MaxAP
int FactionBranch.MaxAP get
Definition at line 124 of file FactionBranch.cs.
Referenced by UICurrency.Build(), and LayerPolicy.RefreshPolicyList().
MaxLv
int FactionBranch.MaxLv get
Definition at line 146 of file FactionBranch.cs.
Referenced by UIHomeInfo.RefreshInfo().
MaxPopulation
int FactionBranch.MaxPopulation get
Definition at line 126 of file FactionBranch.cs.
Referenced by OnSimulateHour(), RefreshEfficiency(), and UIHomeInfo.RefreshInfo().
MaxSoil
int FactionBranch.MaxSoil get
Definition at line 128 of file FactionBranch.cs.
Referenced by Map.MineObj(), GrowSystem.PopHarvest(), UIHomeInfo.RefreshInfo(), and GrowSystem.TryPopSeed().
Money
int FactionBranch.Money get
Definition at line 118 of file FactionBranch.cs.
NumHeirloom
int FactionBranch.NumHeirloom get
Definition at line 122 of file FactionBranch.cs.
Referenced by HomeResourceWorth.WriteNote().
RankText
string FactionBranch.RankText get
Definition at line 138 of file FactionBranch.cs.
Referenced by ContentHomeReport.RefreshInfo(), and UIHomeInfo.RefreshInfo().
TextLv
string FactionBranch.TextLv get
Definition at line 140 of file FactionBranch.cs.
Referenced by WidgetStatsBar.Build(), UIHomeInfo.RefreshInfo(), TraitCoreZone.SetName(), and UIFactionInfo.SetZone().
Worth
int FactionBranch.Worth get
Definition at line 120 of file FactionBranch.cs.
Referenced by Faction.CountWealth(), and UIHomeInfo.RefreshInfo().
The documentation for this class was generated from the following file:
Elin/FactionBranch.cs