Elin Decompiled Documentation: ThingContainer Class Reference
ThingContainer Class Reference
Classes
struct DestData
Public Member Functions
void SetOwner (Card owner)
void ChangeSize (int w, int h)
void RefreshGridRecursive ()
void RefreshGrid ()
void RefreshGrid (UIMagicChest magic, Window.SaveData data)
bool IsOccupied (int x, int y)
bool ShouldShowOnGrid (Thing t)
void OnAdd (Thing t)
bool IsFull (int y=0)
bool IsOverflowing ()
int GetFreeGridIndex ()
void OnRemove (Thing t)
void SetSize (int w, int h)
Thing TryStack (Thing target, int destInvX=-1, int destInvY=-1)
Thing CanStack (Thing target, int destInvX=-1, int destInvY=-1)
DestData GetDest (Thing t, bool tryStack=true)
bool IsFull (Thing t, bool recursive=true, bool tryStack=true)
void AddCurrency (Card owner, string id, int a, SourceMaterial.Row mat=null)
void DestroyAll (Func< Thing, bool > funcExclude=null)
Thing Find (int uid)
Thing Find< T > ()
Thing FindBest< T > (Func< Thing, int > func)
Thing Find (Func< Thing, bool > func, bool recursive=true)
Thing Find (string id, string idMat)
Thing Find (string id, int idMat=-1, int refVal=-1)
Thing FindStealable ()
ThingStack GetThingStack (string id, int refVal=-1)
ThingStack GetThingStack (string id, ThingStack s, bool isOrigin, int refVal=-1)
ThingStack GetThingStack (string id)
ThingStack GetThingStack (string id, ThingStack s, bool isOrigin)
int GetCurrency (string id, ref int sum, SourceMaterial.Row mat=null)
List< Thing > ListCurrency (string id)
List< Thing > List (Func< Thing, bool > func, bool onlyAccessible=false)
void _List (Func< Thing, bool > func, bool onlyAccessible=false)
void AddFactory (HashSet< string > hash)
void Foreach (Action< Thing > action, bool onlyAccessible=true)
void Foreach (Func< Thing, bool > action, bool onlyAccessible=true)
Public Member Functions inherited from ActPlan.List< Thing >
void Add (Act a, string s="")
Public Attributes
int width
int height
Card owner
List< Thing > grid
Static Public Attributes
static List< Thing > listUnassigned = new List<Thing>()
const int InvYHotbar = 1
Properties
int GridSize [get]
bool HasGrid [get]
bool IsMagicChest [get]
int MaxCapacity [get]
Private Member Functions
void _ListCurrency (string id)
Static Private Attributes
static List< ThingContainer > _listContainers = new List<ThingContainer>()
static List< Thing > tempList = new List<Thing>()
Detailed Description
Definition at line 6 of file ThingContainer.cs.
Member Function Documentation
_List()
void ThingContainer._List (Func< Thing, bool > func, bool onlyAccessible = false) inline
Definition at line 791 of file ThingContainer.cs.
    {
        using Enumerator enumerator = GetEnumerator();
        while (enumerator.MoveNext())
        {
            Thing current = enumerator.Current;
            if (!onlyAccessible || !(current.parent is Card) || (current.parent as Card).c_lockLv <= 0)
            {
                current.things._List(func, onlyAccessible);
                if (func(current))
                {
                    tempList.Add(current);
                }
            }
        }
    }
References _List(), ActPlan.List.Add(), Card.parent, tempList, and Card.things.
Referenced by _List(), and List().
_ListCurrency()
void ThingContainer._ListCurrency (string id) inline private
Definition at line 767 of file ThingContainer.cs.
    {
        using Enumerator enumerator = GetEnumerator();
        while (enumerator.MoveNext())
        {
            Thing current = enumerator.Current;
            if (current.CanSearchContents)
            {
                current.things._ListCurrency(id);
            }
            if (current.id == id)
            {
                tempList.Add(current);
            }
        }
    }
References _ListCurrency(), ActPlan.List.Add(), Thing.CanSearchContents, Card.id, tempList, and Card.things.
Referenced by _ListCurrency(), and ListCurrency().
AddCurrency()
void ThingContainer.AddCurrency (Card owner, string id, int a, SourceMaterial::Row mat = null) inline
Definition at line 500 of file ThingContainer.cs.
    {
        int num = a;
        ListCurrency(id);
        foreach (Thing temp in tempList)
        {
            if (!(temp.id != id) && (mat == null || temp.material == mat))
            {
                if (num > 0)
                {
                    temp.ModNum(num);
                    return;
                }
                if (temp.Num + num >= 0)
                {
                    temp.ModNum(num);
                    return;
                }
                num += temp.Num;
                temp.ModNum(-temp.Num);
            }
        }
        if (num != 0 && num > 0)
        {
            Thing thing = ThingGen.Create(id);
            if (mat != null)
            {
                thing.ChangeMaterial(mat);
            }
            owner.AddThing(thing).SetNum(num);
        }
    }
References Card.AddThing(), Card.ChangeMaterial(), ThingGen.Create(), Card.id, ListCurrency(), Card.material, Card.ModNum(), Card.Num, owner, Card.SetNum(), and tempList.
Referenced by Card.ModCurrency(), and LayerGachaResult.PlayGacha().
AddFactory()
void ThingContainer.AddFactory (HashSet< string > hash) inline
Definition at line 808 of file ThingContainer.cs.
    {
        using Enumerator enumerator = GetEnumerator();
        while (enumerator.MoveNext())
        {
            Thing current = enumerator.Current;
            if (current.CanSearchContents)
            {
                current.things.AddFactory(hash);
            }
            if (current.trait.IsFactory)
            {
                hash.Add(current.id);
            }
            if (current.trait.ToggleType == ToggleType.Fire && current.isOn)
            {
                hash.Add("fire");
            }
        }
    }
References AddFactory(), Thing.CanSearchContents, Card.id, Trait.IsFactory, Card.isOn, Card.things, Trait.ToggleType, and Card.trait.
Referenced by AddFactory(), and RecipeUpdater.RunRecipe().
CanStack()
Thing ThingContainer.CanStack (Thing target, int destInvX = -1, int destInvY = -1) inline
Definition at line 381 of file ThingContainer.cs.
    {
        using Enumerator enumerator = GetEnumerator();
        while (enumerator.MoveNext())
        {
            Thing current = enumerator.Current;
            if (current != target && target.CanStackTo(current))
            {
                return current;
            }
        }
        return target;
    }
References Thing.CanStackTo().
Referenced by GetDest(), IsFull(), InvOwner.OnShiftClick(), and Zone.TryAddThingInSharedContainer().
ChangeSize()
void ThingContainer.ChangeSize (int w, int h) inline
Definition at line 83 of file ThingContainer.cs.
    {
        width = w;
        height = h;
        owner.c_containerSize = w * 100 + h;
        RefreshGrid();
        Debug.Log(base.Count + "/" + width + "/" + height + "/" + GridSize);
    }
References GridSize, height, RefreshGrid(), and width.
DestroyAll()
void ThingContainer.DestroyAll (Func< Thing, bool > funcExclude = null) inline
Definition at line 533 of file ThingContainer.cs.
    {
        this.ForeachReverse(delegate(Thing t)
        {
            if (funcExclude == null || !funcExclude(t))
            {
                t.Destroy();
                Remove(t);
            }
        });
        if (grid != null)
        {
            for (int i = 0; i < grid.Count; i++)
            {
                grid[i] = null;
            }
        }
    }
References Card.Destroy(), and grid.
Referenced by ThingGen.CreateCardboardBox(), ThingGen.CreateTreasureContent(), Player.DropReward(), TraitGodStatue.GetManiGene(), TraitFoodEggFertilized.Incubate(), Trait.OnBarter(), Player.OnCreateGame(), QuestFiamaLock.OnStart(), Player.OnStartNewGame(), TraitContainer.Open(), DramaOutcome.QuestDefense_0(), and Zone.SpawnLostItems().
Find() [1/4]
Thing ThingContainer.Find (Func< Thing, bool > func, bool recursive = true) inline
Definition at line 611 of file ThingContainer.cs.
    {
        using (Enumerator enumerator = GetEnumerator())
        {
            while (enumerator.MoveNext())
            {
                Thing current = enumerator.Current;
                if (recursive && current.CanSearchContents)
                {
                    Thing thing = current.things.Find(func);
                    if (thing != null)
                    {
                        return thing;
                    }
                }
                if (func(current))
                {
                    return current;
                }
            }
        }
        return null;
    }
References Thing.CanSearchContents, Find(), and Card.things.
Find() [2/4]
Thing ThingContainer.Find (int uid) inline
Definition at line 552 of file ThingContainer.cs.
    {
        using (Enumerator enumerator = GetEnumerator())
        {
            while (enumerator.MoveNext())
            {
                Thing current = enumerator.Current;
                if (current.CanSearchContents)
                {
                    Thing thing = current.things.Find(uid);
                    if (thing != null)
                    {
                        return thing;
                    }
                }
                if (current.uid == uid)
                {
                    return current;
                }
            }
        }
        return null;
    }
References Thing.CanSearchContents, Find(), Card.things, and Card.uid.
Referenced by AM_Adv._OnUpdateInput(), TraitGodStatue._OnUse(), QuestCraft.CanDeliverToClient(), QuestLoytelFarm.CanUpdateOnTalk(), DramaOutcome.chara_hired_ticket(), DramaOutcome.check_sketch(), LayerInventory.CreateBuy(), Chara.Die(), Find(), Find< T >(), Chara.FindAmmo(), DramaOutcome.give_sketch_special(), Chara.GiveGift(), DramaOutcome.guild_mageTrial(), Chara.MakeGrave(), Trait.OnBarter(), ShopTransaction.OnEndTransaction(), ConSleep.OnRemoved(), ConWrath.OnRemoved(), DramaManager.ParseLine(), HotItemActionSleep.Perform(), HotItemEQSet.Perform(), LayerGacha.PlayGacha(), CoreDebug.QuickStart(), LayerQuestBoard.RefreshHire(), Recipe.Ingredient.RefreshThing(), Card.RemoveBacker(), AI_Idle.Run(), AI_PlayMusic.Run(), ConSleep.SuccubusVisit(), Player.TryEquipBait(), Zone.TryGetRestock< T >(), Zone.TryGetThingFromSharedContainer(), ActPray.TryPray(), and TraitToolTorch.TrySetHeldAct().
Find() [3/4]
Thing ThingContainer.Find (string id, int idMat = -1, int refVal = -1) inline
Definition at line 640 of file ThingContainer.cs.
    {
        using (Enumerator enumerator = GetEnumerator())
        {
            while (enumerator.MoveNext())
            {
                Thing current = enumerator.Current;
                if (current.CanSearchContents)
                {
                    Thing thing = current.things.Find(id, idMat, refVal);
                    if (thing != null)
                    {
                        return thing;
                    }
                }
                if (current.id == id && (idMat == -1 || current.material.id == idMat) && (refVal == -1 || current.refVal == refVal))
                {
                    return current;
                }
            }
        }
        return null;
    }
References Thing.CanSearchContents, Find(), Card.id, Card.material, and Card.things.
Find() [4/4]
Thing ThingContainer.Find (string id, string idMat) inline
Definition at line 635 of file ThingContainer.cs.
    {
        return Find(id, idMat.IsEmpty() ? (-1) : EClass.sources.materials.alias[idMat].id);
    }
References Find(), SourceManager.materials, and EClass.sources.
Find< T >()
Thing ThingContainer.Find< T > () inline
Type Constraints
T : Trait
Definition at line 576 of file ThingContainer.cs.
                                   : Trait
    {
        using (Enumerator enumerator = GetEnumerator())
        {
            while (enumerator.MoveNext())
            {
                Thing current = enumerator.Current;
                if (current.CanSearchContents)
                {
                    Thing thing = current.things.Find<T>();
                    if (thing != null)
                    {
                        return thing;
                    }
                }
                if (current.trait is T)
                {
                    return current;
                }
            }
        }
        return null;
    }
References Thing.CanSearchContents, Find(), Card.things, and Card.trait.
FindBest< T >()
Thing ThingContainer.FindBest< T > (Func< Thing, int > func) inline
Type Constraints
T : Trait
Definition at line 600 of file ThingContainer.cs.
                                                            : Trait
    {
        List((Thing t) => t.trait is T, onlyAccessible: true);
        if (tempList.Count == 0)
        {
            return null;
        }
        tempList.Sort((Thing a, Thing b) => func(b) - func(a));
        return tempList[0];
    }
References List(), tempList, and Card.trait.
FindStealable()
Thing ThingContainer.FindStealable () inline
Definition at line 664 of file ThingContainer.cs.
    {
        List<Thing> list = new List<Thing>();
        using (Enumerator enumerator = GetEnumerator())
        {
            while (enumerator.MoveNext())
            {
                Thing current = enumerator.Current;
                if (!current.IsContainer && current.trait.CanBeStolen && !current.HasTag(CTAG.gift))
                {
                    list.Add(current);
                }
            }
        }
        if (list.Count == 0)
        {
            return null;
        }
        list.Sort((Thing a, Thing b) => Compare(a) - Compare(b));
        return list[0];
        static int Compare(Thing a)
        {
            return a.SelfWeight + (a.isEquipped ? 10000 : 0);
        }
    }
References Card.Add(), Trait.CanBeStolen, Card.HasTag(), Card.IsContainer, and Card.trait.
Referenced by AI_Steal.Run().
Foreach() [1/2]
void ThingContainer.Foreach (Action< Thing > action, bool onlyAccessible = true) inline
Definition at line 829 of file ThingContainer.cs.
    {
        using Enumerator enumerator = GetEnumerator();
        while (enumerator.MoveNext())
        {
            Thing current = enumerator.Current;
            if (!onlyAccessible || current.CanSearchContents)
            {
                current.things.Foreach(action);
            }
            action(current);
        }
    }
References Thing.CanSearchContents, Foreach(), and Card.things.
Referenced by BuildMenu._Search(), Card.AddThing(), DramaCustomSequence.Build(), Foreach(), BaseTaskHarvest.GetBestTool(), Props.ListThingStack(), TaskDump.ListThingsToPut(), ZoneEventHarvest.OnLeaveZone(), Player.OnLoad(), RecipeManager.OnVersionUpdate(), BuildMenu.RefreshCategory(), Chara.Revive(), WidgetSearch.Search(), Trait.TryRefuel(), LayerInventory.TryShowGuide(), and GoalAutoCombat.TryUseRanged().
Foreach() [2/2]
void ThingContainer.Foreach (Func< Thing, bool > action, bool onlyAccessible = true) inline
Definition at line 843 of file ThingContainer.cs.
    {
        using Enumerator enumerator = GetEnumerator();
        while (enumerator.MoveNext())
        {
            Thing current = enumerator.Current;
            if (!onlyAccessible || current.CanSearchContents)
            {
                current.things.Foreach(action);
            }
            if (action(current))
            {
                break;
            }
        }
    }
References Thing.CanSearchContents, Foreach(), and Card.things.
GetCurrency()
int ThingContainer.GetCurrency (string id, ref int sum, SourceMaterial::Row mat = null) inline
Definition at line 740 of file ThingContainer.cs.
    {
        using (Enumerator enumerator = GetEnumerator())
        {
            while (enumerator.MoveNext())
            {
                Thing current = enumerator.Current;
                if (current.CanSearchContents)
                {
                    current.things.GetCurrency(id, ref sum, mat);
                }
                if (current.id == id && (mat == null || current.material == mat))
                {
                    sum += current.Num;
                }
            }
        }
        return sum;
    }
References Thing.CanSearchContents, GetCurrency(), Card.id, Card.material, Card.Num, and Card.things.
Referenced by GetCurrency(), and Card.GetCurrency().
GetDest()
DestData ThingContainer.GetDest (Thing t, bool tryStack = true) inline
Definition at line 395 of file ThingContainer.cs.
    {
        DestData d = default(DestData);
        if (!owner.IsPC)
        {
            SearchDest(this, searchEmpty: true, searchStack: true);
            return d;
        }
        if (t.trait.CanOnlyCarry && IsFull())
        {
            return d;
        }
        ContainerFlag flag = t.category.GetRoot().id.ToEnum<ContainerFlag>();
        if (flag == ContainerFlag.none)
        {
            flag = ContainerFlag.other;
        }
        _listContainers.Clear();
        _listContainers.Add(this);
        TrySearchContainer(owner);
        _listContainers.Sort((ThingContainer a, ThingContainer b) => (b.owner.GetWindowSaveData()?.priority ?? 0) * 10 + (b.owner.IsPC ? 1 : 0) - ((a.owner.GetWindowSaveData()?.priority ?? 0) * 10 + (a.owner.IsPC ? 1 : 0)));
        foreach (ThingContainer listContainer in _listContainers)
        {
            SearchDest(listContainer, searchEmpty: false, searchStack: true);
            if (d.IsValid)
            {
                return d;
            }
        }
        foreach (ThingContainer listContainer2 in _listContainers)
        {
            SearchDest(listContainer2, searchEmpty: true, searchStack: false);
            if (d.IsValid)
            {
                return d;
            }
        }
        return d;
        void SearchDest(ThingContainer things, bool searchEmpty, bool searchStack)
        {
            if (!t.IsContainer || t.things.Count <= 0 || !things.owner.IsContainer || things.owner.trait is TraitToolBelt)
            {
                if (searchStack && tryStack)
                {
                    Thing thing = things.CanStack(t);
                    if (thing != t)
                    {
                        d.stack = thing;
                        return;
                    }
                }
                if (searchEmpty && !things.IsFull() && !(things.owner.trait is TraitToolBelt) && (things.owner.isChara || things.owner.parent is Chara || (things.owner.parent as Thing)?.trait is TraitToolBelt))
                {
                    d.container = things.owner;
                }
            }
        }
        void TrySearchContainer(Card c)
        {
            foreach (Thing thing2 in c.things)
            {
                if (thing2.CanSearchContents)
                {
                    TrySearchContainer(thing2);
                }
            }
            if (c.things != this)
            {
                Window.SaveData windowSaveData = c.GetWindowSaveData();
                if (windowSaveData != null && (!windowSaveData.noRotten || !t.IsDecayed) && (!windowSaveData.onlyRottable || t.trait.Decay != 0) && (!windowSaveData.userFilter || windowSaveData.IsFilterPass(t.GetName(NameStyle.Full, 1))))
                {
                    if (windowSaveData.advDistribution)
                    {
                        foreach (int cat in windowSaveData.cats)
{
                            if (t.category.uid == cat)
{
                                _listContainers.Add(c.things);
                                break;
                            }
                        }
                        return;
                    }
                    if (!windowSaveData.flag.HasFlag(flag))
                    {
                        _listContainers.Add(c.things);
                    }
                }
            }
        }
    }
References _listContainers, Trait.CanOnlyCarry, Thing.CanSearchContents, CanStack(), Card.category, Card.GetWindowSaveData(), Card.isChara, Card.IsContainer, IsFull(), Card.IsPC, owner, Card.parent, Card.things, Card.trait, and Chara.trait.
Referenced by IsFull(), and Card.TryStack().
GetFreeGridIndex()
int ThingContainer.GetFreeGridIndex () inline
Definition at line 329 of file ThingContainer.cs.
    {
        for (int i = 0; i < grid.Count; i++)
        {
            if (grid[i] == null)
            {
                return i;
            }
        }
        return -1;
    }
References grid.
Referenced by IsFull(), OnAdd(), and RefreshGrid().
GetThingStack() [1/4]
ThingStack ThingContainer.GetThingStack (string id) inline
Definition at line 715 of file ThingContainer.cs.
    {
        ThingStack s = new ThingStack();
        bool isOrigin = EClass.sources.cards.map[id].isOrigin;
        return GetThingStack(id, s, isOrigin);
    }
References SourceManager.cards, GetThingStack(), SourceCard.map, and EClass.sources.
GetThingStack() [2/4]
ThingStack ThingContainer.GetThingStack (string id, int refVal = -1) inline
Definition at line 690 of file ThingContainer.cs.
    {
        ThingStack s = new ThingStack();
        bool isOrigin = EClass.sources.cards.map[id].isOrigin;
        return GetThingStack(id, s, isOrigin, refVal);
    }
References SourceManager.cards, GetThingStack(), SourceCard.map, and EClass.sources.
Referenced by GetThingStack(), UIRecipeInfo.Refresh(), and ButtonGrid.RefreshCraftable().
GetThingStack() [3/4]
ThingStack ThingContainer.GetThingStack (string id, ThingStack s, bool isOrigin) inline
Definition at line 722 of file ThingContainer.cs.
    {
        using Enumerator enumerator = GetEnumerator();
        while (enumerator.MoveNext())
        {
            Thing current = enumerator.Current;
            if (current.CanSearchContents)
            {
                current.things.GetThingStack(id, s, isOrigin);
            }
            if (current.id == id || (isOrigin && current.source._origin == id))
            {
                s.Add(current);
            }
        }
        return s;
    }
References ThingStack.Add(), Thing.CanSearchContents, GetThingStack(), Card.id, Thing.source, and Card.things.
GetThingStack() [4/4]
ThingStack ThingContainer.GetThingStack (string id, ThingStack s, bool isOrigin, int refVal = -1) inline
Definition at line 697 of file ThingContainer.cs.
    {
        using Enumerator enumerator = GetEnumerator();
        while (enumerator.MoveNext())
        {
            Thing current = enumerator.Current;
            if (current.CanSearchContents)
            {
                current.things.GetThingStack(id, s, isOrigin, refVal);
            }
            if ((refVal == -1 || current.refVal == refVal) && current.IsIdentified && (current.id == id || (isOrigin && current.source._origin == id)))
            {
                s.Add(current);
            }
        }
        return s;
    }
References ThingStack.Add(), Thing.CanSearchContents, GetThingStack(), Card.id, Card.IsIdentified, Card.refVal, Thing.source, and Card.things.
IsFull() [1/2]
bool ThingContainer.IsFull (int y = 0) inline
Definition at line 275 of file ThingContainer.cs.
    {
        if (IsMagicChest)
        {
            if (base.Count < MaxCapacity)
            {
                if (owner.trait.IsFridge)
                {
                    return !owner.isOn;
                }
                return false;
            }
            return true;
        }
        if (y != 0)
        {
            return false;
        }
        if (owner.trait.IsSpecialContainer && owner.parent != null)
        {
            return true;
        }
        if (!HasGrid)
        {
            return base.Count >= GridSize;
        }
        return GetFreeGridIndex() == -1;
    }
References GetFreeGridIndex(), GridSize, HasGrid, Trait.IsFridge, IsMagicChest, Card.isOn, Trait.IsSpecialContainer, MaxCapacity, owner, Card.parent, and Card.trait.
Referenced by Props.FindEmptyContainer< T >(), GetDest(), InvOwner.GetShitDestOwner(), LayerInventory.GetTopLayer(), IsFull(), InvOwner.Transaction.IsValid(), InvOwnerEquip.ListInteractions(), Faction.OnAdvanceMonth(), AI_Fish.ProgressFish.OnProgressComplete(), ActDreamBug.Perform(), InvOwner.PutBack(), AI_Idle.Run(), and GameDate.ShipPackages().
IsFull() [2/2]
bool ThingContainer.IsFull (Thing t, bool recursive = true, bool tryStack = true) inline
Definition at line 487 of file ThingContainer.cs.
    {
        if (!IsFull() || (tryStack && CanStack(t) != t))
        {
            return false;
        }
        if (!recursive)
        {
            return true;
        }
        return !GetDest(t, tryStack).IsValid;
    }
References CanStack(), GetDest(), IsFull(), and ThingContainer.DestData.IsValid.
IsOccupied()
bool ThingContainer.IsOccupied (int x, int y) inline
Definition at line 229 of file ThingContainer.cs.
    {
        using (Enumerator enumerator = GetEnumerator())
        {
            while (enumerator.MoveNext())
            {
                Thing current = enumerator.Current;
                if (current.invY == y && current.invX == x)
                {
                    return true;
                }
            }
        }
        return false;
    }
References Card.invX, and Card.invY.
Referenced by InvOwner.PutBack().
IsOverflowing()
bool ThingContainer.IsOverflowing () inline
Definition at line 304 of file ThingContainer.cs.
    {
        if (!HasGrid || IsMagicChest)
        {
            return false;
        }
        int num = 0;
        using (Enumerator enumerator = GetEnumerator())
        {
            while (enumerator.MoveNext())
            {
                Thing current = enumerator.Current;
                if (current.invY != 1 && !current.isEquipped)
                {
                    num++;
                }
            }
        }
        if (num > grid.Count)
        {
            return true;
        }
        return false;
    }
References grid, HasGrid, Card.invY, Thing.isEquipped, and IsMagicChest.
Referenced by InvOwner.ListInteractions().
List()
List< Thing > ThingContainer.List (Func< Thing, bool > func, bool onlyAccessible = false) inline
Definition at line 784 of file ThingContainer.cs.
    {
        tempList.Clear();
        _List(func, onlyAccessible);
        return tempList;
    }
References _List(), and tempList.
Referenced by DramaCustomSequence.Build(), ZonePreEnterEncounter.Execute(), FindBest< T >(), TraitPainter.GetCanvas(), TaskDig.GetTreasureMap(), QuestDeliver.ListDestThing(), Player.OnAdvanceHour(), AM_Adv.OnBecomeNoGoal(), ContentCodex.OnClickAddCards(), Game.OnLoad(), AI_Fish.ProgressFish.OnProgressComplete(), TraitScrollStatic.OnRead(), ConSleep.OnRemoved(), UI.OpenFloatInv(), AI_Idle.Run(), ButtonAbility.SpecialHoldAction(), Zone.TryListThingsInSpot< T >(), LayerDragGrid.TryProc(), and Map.TryShatter().
ListCurrency()
List< Thing > ThingContainer.ListCurrency (string id) inline
Definition at line 760 of file ThingContainer.cs.
    {
        tempList.Clear();
        _ListCurrency(id);
        return tempList;
    }
References _ListCurrency(), and tempList.
Referenced by AddCurrency().
OnAdd()
void ThingContainer.OnAdd (Thing t) inline
Definition at line 262 of file ThingContainer.cs.
    {
        if (HasGrid && ShouldShowOnGrid(t))
        {
            int freeGridIndex = GetFreeGridIndex();
            if (freeGridIndex != -1)
            {
                grid[freeGridIndex] = t;
            }
            t.pos.x = freeGridIndex;
        }
    }
References GetFreeGridIndex(), grid, HasGrid, and ShouldShowOnGrid().
Referenced by Card.AddThing().
OnRemove()
void ThingContainer.OnRemove (Thing t) inline
Definition at line 341 of file ThingContainer.cs.
    {
        if (HasGrid && t.invY == 0)
        {
            int num = grid.IndexOf(t);
            if (num != -1)
            {
                grid[num] = null;
            }
        }
    }
References grid, HasGrid, and Card.invY.
Referenced by Card.RemoveThing().
RefreshGrid() [1/2]
void ThingContainer.RefreshGrid () inline
Definition at line 108 of file ThingContainer.cs.
    {
        if (GridSize == 0)
        {
            return;
        }
        grid = new List<Thing>(new Thing[GridSize]);
        using (Enumerator enumerator = GetEnumerator())
        {
            while (enumerator.MoveNext())
            {
                Thing current = enumerator.Current;
                if (ShouldShowOnGrid(current))
                {
                    if (current.invX >= GridSize || current.invX < 0 || grid[current.invX] != null)
                    {
                        listUnassigned.Add(current);
                    }
                    else
                    {
                        grid[current.invX] = current;
                    }
                }
            }
        }
        foreach (Thing item in listUnassigned)
        {
            int freeGridIndex = GetFreeGridIndex();
            if (freeGridIndex == -1)
            {
                break;
            }
            grid[freeGridIndex] = item;
            item.invX = freeGridIndex;
        }
        listUnassigned.Clear();
    }
References ActPlan.List.Add(), GetFreeGridIndex(), grid, GridSize, Card.invX, listUnassigned, and ShouldShowOnGrid().
Referenced by ChangeSize(), RefreshGrid(), RefreshGridRecursive(), and LayerDragGrid.SetInv().
RefreshGrid() [2/2]
void ThingContainer.RefreshGrid (UIMagicChest magic, Window::SaveData data) inline
Definition at line 146 of file ThingContainer.cs.
    {
        magic.filteredList.Clear();
        magic.cats.Clear();
        magic.catCount.Clear();
        grid = new List<Thing>(new Thing[GridSize]);
        string lastSearch = magic.lastSearch;
        bool flag = !lastSearch.IsEmpty();
        bool flag2 = !magic.idCat.IsEmpty();
        Window.SaveData.CategoryType category = data.category;
        bool flag3 = category != Window.SaveData.CategoryType.None;
        string text = "";
        using (Enumerator enumerator = GetEnumerator())
        {
            while (enumerator.MoveNext())
            {
                Thing current = enumerator.Current;
                if (flag3)
                {
                    switch (category)
                    {
                    case Window.SaveData.CategoryType.Main:
                        text = current.category.GetRoot().id;
                        break;
                    case Window.SaveData.CategoryType.Sub:
                        text = current.category.GetSecondRoot().id;
                        break;
                    case Window.SaveData.CategoryType.Exact:
                        text = current.category.id;
                        break;
                    }
                    magic.cats.Add(text);
                    if (magic.catCount.ContainsKey(text))
                    {
                        magic.catCount[text]++;
                    }
                    else
                    {
                        magic.catCount.Add(text, 1);
                    }
                }
                if (flag)
                {
                    if (current.tempName == null)
                    {
                        current.tempName = current.GetName(NameStyle.Full, 1).ToLower();
                    }
                    if (!current.tempName.Contains(lastSearch) && !current.source.GetSearchName(jp: false).Contains(lastSearch) && !current.source.GetSearchName(jp: true).Contains(lastSearch))
                    {
                        continue;
                    }
                }
                if (!flag2 || !(text != magic.idCat))
                {
                    magic.filteredList.Add(current);
                }
            }
        }
        if (flag2 && !magic.cats.Contains(magic.idCat))
        {
            magic.idCat = "";
            RefreshGrid(magic, data);
            return;
        }
        magic.pageMax = (magic.filteredList.Count - 1) / GridSize;
        if (magic.page > magic.pageMax)
        {
            magic.page = magic.pageMax;
        }
        for (int i = 0; i < GridSize; i++)
        {
            int num = magic.page * GridSize + i;
            if (num >= magic.filteredList.Count)
            {
                break;
            }
            Thing thing = magic.filteredList[num];
            grid[i] = thing;
            thing.invX = i;
        }
        magic.RefreshCats();
    }
References ActPlan.List.Add(), UIMagicChest.catCount, Card.category, UIMagicChest.cats, UIMagicChest.filteredList, Thing.GetName(), grid, GridSize, UIMagicChest.idCat, UIMagicChest.lastSearch, UIMagicChest.page, UIMagicChest.pageMax, UIMagicChest.RefreshCats(), RefreshGrid(), Thing.source, and Thing.tempName.
RefreshGridRecursive()
void ThingContainer.RefreshGridRecursive () inline
Definition at line 92 of file ThingContainer.cs.
    {
        using (Enumerator enumerator = GetEnumerator())
        {
            while (enumerator.MoveNext())
            {
                Thing current = enumerator.Current;
                if (current.IsContainer)
                {
                    current.things.RefreshGridRecursive();
                }
            }
        }
        RefreshGrid();
    }
References Card.IsContainer, RefreshGrid(), RefreshGridRecursive(), and Card.things.
Referenced by Game.OnLoad(), and RefreshGridRecursive().
SetOwner()
void ThingContainer.SetOwner (Card owner) inline
Definition at line 71 of file ThingContainer.cs.
    {
        this.owner = owner;
        width = owner.c_containerSize / 100;
        height = owner.c_containerSize % 100;
        if (width == 0)
        {
            width = 8;
            height = 5;
        }
    }
References height, owner, and width.
Referenced by Card._OnDeserialized(), Card.Create(), Card.Duplicate(), and SetSize().
SetSize()
void ThingContainer.SetSize (int w, int h) inline
Definition at line 353 of file ThingContainer.cs.
    {
        owner.c_containerSize = w * 100 + h;
        SetOwner(owner);
    }
References owner, and SetOwner().
Referenced by TraitBaseContainer.OnCreate(), Player.OnCreateGame(), and TraitWrench.Upgrade().
ShouldShowOnGrid()
bool ThingContainer.ShouldShowOnGrid (Thing t) inline
Definition at line 245 of file ThingContainer.cs.
    {
        if (!owner.IsPC)
        {
            if (t.trait is TraitChestMerchant)
            {
                return false;
            }
            return true;
        }
        if (!t.isEquipped)
        {
            return !t.IsHotItem;
        }
        return false;
    }
References Thing.isEquipped, Card.IsHotItem, Card.IsPC, owner, and Card.trait.
Referenced by OnAdd(), and RefreshGrid().
TryStack()
Thing ThingContainer.TryStack (Thing target, int destInvX = -1, int destInvY = -1) inline
Definition at line 359 of file ThingContainer.cs.
    {
        using Enumerator enumerator = GetEnumerator();
        while (enumerator.MoveNext())
        {
            Thing current = enumerator.Current;
            if (destInvX == -1 && current.CanSearchContents && owner.GetRootCard().IsPC)
            {
                Thing thing = current.things.TryStack(target, destInvX, destInvY);
                if (thing != target)
                {
                    return thing;
                }
            }
            if ((destInvX == -1 || (current.invX == destInvX && current.invY == destInvY)) && current != target && target.TryStackTo(current))
            {
                return current;
            }
        }
        return target;
    }
References Thing.CanSearchContents, Card.GetRootCard(), Card.invX, Card.invY, Card.IsPC, owner, Card.things, TryStack(), and Card.TryStackTo().
Referenced by Card.AddThing(), InvOwner.OnShiftClick(), Zone.TryAddThingInSharedContainer(), and TryStack().
Member Data Documentation
_listContainers
List<ThingContainer> ThingContainer._listContainers = new List<ThingContainer>() static private
Definition at line 45 of file ThingContainer.cs.
Referenced by GetDest().
grid
List<Thing> ThingContainer.grid
Definition at line 43 of file ThingContainer.cs.
Referenced by DestroyAll(), GetFreeGridIndex(), IsOverflowing(), OnAdd(), OnRemove(), and RefreshGrid().
height
int ThingContainer.height
Definition at line 37 of file ThingContainer.cs.
Referenced by ChangeSize(), Card.GetPrice(), SetOwner(), and TraitWrench.Upgrade().
InvYHotbar
const int ThingContainer.InvYHotbar = 1 static
Definition at line 31 of file ThingContainer.cs.
listUnassigned
List<Thing> ThingContainer.listUnassigned = new List<Thing>() static
Definition at line 28 of file ThingContainer.cs.
Referenced by RefreshGrid().
owner
Card ThingContainer.owner
Definition at line 40 of file ThingContainer.cs.
Referenced by AddCurrency(), GetDest(), IsFull(), SetOwner(), SetSize(), ShouldShowOnGrid(), and TryStack().
tempList
List<Thing> ThingContainer.tempList = new List<Thing>() static private
Definition at line 47 of file ThingContainer.cs.
Referenced by _List(), _ListCurrency(), AddCurrency(), FindBest< T >(), List(), and ListCurrency().
width
int ThingContainer.width
Definition at line 34 of file ThingContainer.cs.
Referenced by ChangeSize(), Card.GetPrice(), SetOwner(), and TraitWrench.Upgrade().
Property Documentation
GridSize
int ThingContainer.GridSize get
Definition at line 50 of file ThingContainer.cs.
Referenced by ChangeSize(), IsFull(), RefreshGrid(), and TraitWrench.Upgrade().
HasGrid
bool ThingContainer.HasGrid get
Definition at line 53 of file ThingContainer.cs.
Referenced by IsFull(), IsOverflowing(), OnAdd(), and OnRemove().
IsMagicChest
bool ThingContainer.IsMagicChest get
Definition at line 56 of file ThingContainer.cs.
Referenced by IsFull(), and IsOverflowing().
MaxCapacity
int ThingContainer.MaxCapacity get
Definition at line 59 of file ThingContainer.cs.
    {
        get
        {
            if (!IsMagicChest)
            {
                return GridSize;
            }
            return 100 + owner.c_containerUpgrade.cap;
        }
    }
Referenced by IsFull(), UIMagicChest.RefreshBottom(), and Zone.TryAddThingInSharedContainer().
The documentation for this class was generated from the following file:
Elin/ThingContainer.cs