Elin Decompiled Documentation: UIMouseInfo Class Reference
UIMouseInfo Class Reference
Public Member Functions
void RefreshPosition ()
void SetText (string t="")
Public Attributes
UIText text
UIText textCost
Image imageRange
string willShow
Private Member Functions
void OnEnable ()
void LateUpdate ()
Detailed Description
Definition at line 4 of file UIMouseInfo.cs.
Member Function Documentation
LateUpdate()
void UIMouseInfo.LateUpdate () inline private
Definition at line 20 of file UIMouseInfo.cs.
    {
        RefreshPosition();
    }
References RefreshPosition().
OnEnable()
void UIMouseInfo.OnEnable () inline private
Definition at line 14 of file UIMouseInfo.cs.
    {
        textCost.SetActive(enable: false);
        RefreshPosition();
    }
References RefreshPosition(), and textCost.
RefreshPosition()
void UIMouseInfo.RefreshPosition () inline
Definition at line 25 of file UIMouseInfo.cs.
    {
        base.transform.position = Input.mousePosition;
        if (CursorSystem.ignoreCount <= 0)
        {
            if (willShow != null)
            {
                text.text = willShow;
                willShow = null;
            }
            if (text.text.IsEmpty())
            {
                this.SetActive(enable: false);
            }
        }
    }
References CursorSystem.ignoreCount, text, and willShow.
Referenced by LateUpdate(), and OnEnable().
SetText()
void UIMouseInfo.SetText (string t = "") inline
Definition at line 42 of file UIMouseInfo.cs.
    {
        if (CursorSystem.ignoreCount <= 0)
        {
            text.text = t;
            willShow = null;
            this.SetActive(!t.IsEmpty());
        }
        else
        {
            willShow = t;
        }
    }
References CursorSystem.ignoreCount, and willShow.
Member Data Documentation
imageRange
Image UIMouseInfo.imageRange
Definition at line 10 of file UIMouseInfo.cs.
text
UIText UIMouseInfo.text
Definition at line 6 of file UIMouseInfo.cs.
Referenced by RefreshPosition().
textCost
UIText UIMouseInfo.textCost
Definition at line 8 of file UIMouseInfo.cs.
Referenced by OnEnable().
willShow
string UIMouseInfo.willShow
Definition at line 12 of file UIMouseInfo.cs.
Referenced by RefreshPosition(), and SetText().
The documentation for this class was generated from the following file:
Elin/Plugins.UI/UIMouseInfo.cs