Elin Decompiled Documentation: UIButtonList Class Reference
UIButtonList Class Reference
Public Member Functions
override void OnInstantiate (RefObjectEx o, UIButton t)
void AddButton (object obj, string text, Action onClick, Action< UIButton > onInstantiate=null)
new void Select (object obj, bool invoke=false)
Public Member Functions inherited from UIListEx< UIButton >
override void Refresh (bool highlightLast=false)
virtual void OnInstantiate (RefObjectEx o, T t)
Additional Inherited Members
Public Attributes inherited from UIListEx< UIButton >
T mold
Detailed Description
Definition at line 4 of file UIButtonList.cs.
Member Function Documentation
AddButton()
void UIButtonList.AddButton (object obj, string text, Action onClick, Action< UIButton > onInstantiate = null) inline
Definition at line 11 of file UIButtonList.cs.
    {
        Add(new RefObjectEx
        {
            obj = obj,
            text = text,
            onClick = onClick,
            onInstantiate = onInstantiate
        });
    }
References Add().
Referenced by Dialog._Confetti(), Dialog.AddButton(), LayerNewZone.Embark(), Dialog.Gift(), Dialog.InputName(), Dialog.Ok(), LayerGacha.PlayGacha(), Dialog.Recipe(), Dialog.TryWarn(), and Dialog.YesNo().
OnInstantiate()
override void UIButtonList.OnInstantiate (RefObjectEx o, UIButton t) inline
Definition at line 6 of file UIButtonList.cs.
    {
        t.mainText.text = o.text;
    }
Select()
new void UIButtonList.Select (object obj, bool invoke = false) inline
Definition at line 22 of file UIButtonList.cs.
    {
        for (int i = 0; i < items.Count; i++)
        {
            RefObject refObject = (RefObject)items[i];
            if (obj.Equals(refObject.obj))
            {
                base.Select(i, invoke);
                return;
            }
        }
        Debug.Log(obj?.ToString() + obj.GetType());
    }
References Debug.
The documentation for this class was generated from the following file:
Elin/Plugins.UI/UIButtonList.cs