Elin Decompiled Documentation: SpriteData Class Reference
SpriteData Class Reference
Public Member Functions
void Init ()
void LoadPref ()
void LoadAnimationIni ()
void LoadSprites ()
Sprite[] GetSprites ()
Sprite GetSprite ()
void Validate ()
void Load ()
Public Attributes
string id
string path
Texture2D tex
Sprite[] sprites
DateTime dateTex
DateTime dateIni
DateTime datePref
int frame = 1
int scale = 50
float time = 0.2f
SourcePref pref
bool tryFixPrefNotLoadedAtStart
Detailed Description
Definition at line 8 of file SpriteData.cs.
Member Function Documentation
GetSprite()
Sprite SpriteData.GetSprite () inline
Definition at line 120 of file SpriteData.cs.
    {
        if (sprites == null)
        {
            Load();
        }
        return sprites.TryGet(0, returnNull: true);
    }
References Load(), and sprites.
Referenced by SpriteReplacer.GetSprite(), LayerEditSkin.RefreshList(), and SpriteReplacerAnimation.SetData().
GetSprites()
Sprite[] SpriteData.GetSprites () inline
Definition at line 111 of file SpriteData.cs.
    {
        if (sprites == null)
        {
            Load();
        }
        return sprites;
    }
References Load(), and sprites.
Referenced by CardActor.OnRender(), and SpriteReplacerAnimation.Refresh().
Init()
void SpriteData.Init () inline
Definition at line 34 of file SpriteData.cs.
    {
        try
        {
            id = Path.GetFileNameWithoutExtension(path);
            LoadAnimationIni();
            LoadPref();
        }
        catch (Exception exception)
        {
            Debug.LogException(exception);
            Debug.LogError("#sprite failed " + id + "/" + path);
        }
    }
References Debug, LoadAnimationIni(), LoadPref(), and path.
Referenced by SpriteReplacer.BuildSuffixData(), LayerEditSkin.RefreshList(), and SpriteReplacerAnimation.SetData().
Load()
void SpriteData.Load () inline
Definition at line 152 of file SpriteData.cs.
    {
        LoadAnimationIni();
        LoadPref();
        LoadSprites();
    }
References LoadAnimationIni(), LoadPref(), and LoadSprites().
Referenced by GetSprite(), GetSprites(), and Validate().
LoadAnimationIni()
void SpriteData.LoadAnimationIni () inline
Definition at line 58 of file SpriteData.cs.
    {
        if (!File.Exists(path + ".ini"))
        {
            frame = 1;
            scale = 50;
            time = 0.2f;
            return;
        }
        try
        {
            IniData iniData = new FileIniDataParser().ReadFile(path + ".ini", Encoding.UTF8);
            frame = Mathf.Max(1, (!int.TryParse(iniData.GetKey("frame"), out var result)) ? 1 : result);
            scale = (int.TryParse(iniData.GetKey("scale"), out var result2) ? result2 : 50);
            time = (float.TryParse(iniData.GetKey("time"), out var result3) ? Mathf.Max(0.016f, result3) : 0.2f);
        }
        catch (Exception exception)
        {
            Debug.LogException(exception);
        }
    }
References Debug, frame, path, scale, and time.
Referenced by Init(), and Load().
LoadPref()
void SpriteData.LoadPref () inline
Definition at line 49 of file SpriteData.cs.
    {
        pref = null;
        if (File.Exists(path + ".pref"))
        {
            pref = SourcePref.ReadFromIni(path + ".pref");
        }
    }
References path, pref, and SourcePref.ReadFromIni().
Referenced by Init(), and Load().
LoadSprites()
void SpriteData.LoadSprites () inline
Definition at line 80 of file SpriteData.cs.
    {
        Texture2D texture2D = IO.LoadPNG(path + ".png");
        Debug.Log(texture2D.width + "/" + texture2D.height + "/" + path);
        if ((bool)tex)
        {
            if (texture2D.width != tex.width || texture2D.height != tex.height)
            {
                tex.Reinitialize(texture2D.width, texture2D.height);
            }
            tex.SetPixels32(texture2D.GetPixels32());
            tex.Apply();
            UnityEngine.Object.Destroy(texture2D);
        }
        else
        {
            tex = texture2D;
        }
        int num = tex.width / frame;
        int height = tex.height;
        if (sprites == null || sprites.Length != frame)
        {
            sprites = new Sprite[frame];
        }
        Vector2 pivot = new Vector2(0.5f, 0.5f);
        for (int i = 0; i < frame; i++)
        {
            sprites[i] = Sprite.Create(tex, new Rect(i * num, 0f, num, height), pivot, 100f, 0u, SpriteMeshType.FullRect);
        }
    }
References Debug, frame, path, sprites, and tex.
Referenced by Load().
Validate()
void SpriteData.Validate () inline
Definition at line 129 of file SpriteData.cs.
    {
        if (IsDirty(".png", ref dateTex) || IsDirty(".ini", ref dateIni) || IsDirty(".pref", ref datePref))
        {
            Load();
        }
        bool IsDirty(string p, ref DateTime lastChecked)
        {
            string text = path + p;
            if (!File.Exists(text))
            {
                return false;
            }
            DateTime lastWriteTimeUtc = File.GetLastWriteTimeUtc(text);
            if (lastWriteTimeUtc == lastChecked)
            {
                return false;
            }
            lastChecked = lastWriteTimeUtc;
            return true;
        }
    }
References dateIni, datePref, dateTex, Load(), and path.
Referenced by SpriteReplacer.Validate().
Member Data Documentation
dateIni
DateTime SpriteData.dateIni
Definition at line 20 of file SpriteData.cs.
Referenced by Validate().
datePref
DateTime SpriteData.datePref
Definition at line 22 of file SpriteData.cs.
Referenced by Validate().
dateTex
DateTime SpriteData.dateTex
Definition at line 18 of file SpriteData.cs.
Referenced by Validate().
frame
int SpriteData.frame = 1
Definition at line 24 of file SpriteData.cs.
Referenced by LoadAnimationIni(), LoadSprites(), CardActor.OnRender(), and SpriteReplacerAnimation.Refresh().
id
string SpriteData.id
Definition at line 10 of file SpriteData.cs.
Referenced by SpriteReplacer.HasSprite().
path
string SpriteData.path
Definition at line 12 of file SpriteData.cs.
Referenced by Init(), LoadAnimationIni(), LoadPref(), LoadSprites(), LayerEditSkin.OnClickEdit(), LayerEditSkin.RefreshList(), SpriteReplacer.Reload(), and Validate().
pref
SourcePref SpriteData.pref
Definition at line 30 of file SpriteData.cs.
Referenced by LoadPref(), and Card.SetImage().
scale
int SpriteData.scale = 50
Definition at line 26 of file SpriteData.cs.
Referenced by LoadAnimationIni().
sprites
Sprite [] SpriteData.sprites
Definition at line 16 of file SpriteData.cs.
Referenced by GetSprite(), GetSprites(), and LoadSprites().
tex
Texture2D SpriteData.tex
Definition at line 14 of file SpriteData.cs.
Referenced by LoadSprites().
time
float SpriteData.time = 0.2f
Definition at line 28 of file SpriteData.cs.
Referenced by LoadAnimationIni(), CardActor.OnRender(), and SpriteReplacerAnimation.SetData().
tryFixPrefNotLoadedAtStart
bool SpriteData.tryFixPrefNotLoadedAtStart
Definition at line 32 of file SpriteData.cs.
The documentation for this class was generated from the following file:
Elin/SpriteData.cs