Elin Decompiled Documentation: PrimitiveUI.PrimitiveCanvas Class Reference
PrimitiveUI.PrimitiveCanvas Class Reference
Classes
class PUIElement
class PUIFillElement
class PUIStrokeElement
class PUIUtils
Public Member Functions
void Clear ()
void DrawSquare (Vector2 center, float size, Color fillColor)
void DrawSquare (Vector2 center, float size, StrokeStyle strokeStyle)
void DrawSquare (Vector2 center, float size, Color fillColor, StrokeStyle strokeStyle)
void DrawSquare (Vector2 center, float size, float rotation=0f, Color? fillColor=null, StrokeStyle strokeStyle=null)
void DrawRectangle (float x, float y, float width, float height, Color fillColor)
void DrawRectangle (float x, float y, float width, float height, StrokeStyle strokeStyle)
void DrawRectangle (float x, float y, float width, float height, Color fillColor, StrokeStyle strokeStyle)
void DrawRectangle (float x, float y, float width, float height, float rotation=0f, Color? fillColor=null, StrokeStyle strokeStyle=null)
void DrawRectangle (Rect rect, Color fillColor)
void DrawRectangle (Rect rect, StrokeStyle strokeStyle)
void DrawRectangle (Rect rect, Color fillColor, StrokeStyle strokeStyle)
void DrawRectangle (Rect rect, float rotation=0f, Color? fillColor=null, StrokeStyle strokeStyle=null)
void DrawCircle (Vector2 center, float radius, Color fillColor)
void DrawCircle (Vector2 center, float radius, StrokeStyle strokeStyle)
void DrawCircle (Vector2 center, float radius, Color fillColor, StrokeStyle strokeStyle)
void DrawCircle (Vector2 center, float radius, float stepSize=1f, float startAngle=0f, float endAngle=360f, Color? fillColor=null, StrokeStyle strokeStyle=null)
void DrawEllipse (Vector2 center, Vector2 radii, Color fillColor)
void DrawEllipse (Vector2 center, Vector2 radii, StrokeStyle strokeStyle)
void DrawEllipse (Vector2 center, Vector2 radii, Color fillColor, StrokeStyle strokeStyle)
void DrawEllipse (Vector2 center, Vector2 radii, float stepSize=1f, float rotation=0f, float startAngle=0f, float endAngle=360f, Color? fillColor=null, StrokeStyle strokeStyle=null)
void DrawRegularSolid (Vector2 center, float radius, int sides, Color fillColor)
void DrawRegularSolid (Vector2 center, float radius, int sides, StrokeStyle strokeStyle)
void DrawRegularSolid (Vector2 center, float radius, int sides, Color fillColor, StrokeStyle strokeStyle)
void DrawRegularSolid (Vector2 center, float radius, int sides, float rotation=0f, Color? fillColor=null, StrokeStyle strokeStyle=null)
void DrawIrregularSolid (Vector2 center, float[] radii, Color fillColor)
void DrawIrregularSolid (Vector2 center, float[] radii, StrokeStyle strokeStyle)
void DrawIrregularSolid (Vector2 center, float[] radii, Color fillColor, StrokeStyle strokeStyle)
void DrawIrregularSolid (Vector2 center, float[] radii, float rotation, Color? fillColor, StrokeStyle strokeStyle)
void DrawPolygon (Vector2[] points, Color fillColor)
void DrawPolygon (Vector2[] points, StrokeStyle strokeStyle)
void DrawPolygon (Vector2[] points, Color fillColor, StrokeStyle strokeStyle)
void DrawRawMesh (Vector2[] points, int[] triangles, Color fillColor)
void DrawLine (Vector2 point1, Vector2 point2)
void DrawLine (Vector2 point1, Vector2 point2, StrokeStyle strokeStyle)
void DrawPath (Vector2[] points)
void DrawPath (Vector2[] points, StrokeStyle strokeStyle)
void DrawPath (Vector2[] points, StrokeStyle strokeStyle, bool closePath)
Public Attributes
bool setDirtyOnDraw = true
Protected Member Functions
override void OnPopulateMesh (VertexHelper vh)
override void OnRectTransformDimensionsChange ()
Properties
float aspectRatio [get]
Private Attributes
List< PUIElement > elements = new List<PUIElement>()
Detailed Description
Definition at line 10 of file PrimitiveCanvas.cs.
Member Function Documentation
Clear()
void PrimitiveUI.PrimitiveCanvas.Clear () inline
Definition at line 284 of file PrimitiveCanvas.cs.
    {
        elements.Clear();
        SetAllDirty();
    }
References PrimitiveUI.PrimitiveCanvas.elements.
Referenced by PrimitiveUI.Examples.PUIExampleCharts.Draw(), PrimitiveUI.Examples.PUIExampleRPGStats.Draw(), and PrimitiveUI.Examples.PUIExampleSineWaves.Draw().
DrawCircle() [1/4]
void PrimitiveUI.PrimitiveCanvas.DrawCircle (Vector2 center, float radius, Color fillColor) inline
Definition at line 408 of file PrimitiveCanvas.cs.
    {
        DrawCircle(center, radius, 1f, 0f, 360f, fillColor);
    }
References PrimitiveUI.PrimitiveCanvas.DrawCircle().
Referenced by PrimitiveUI.Examples.PUIExampleCharts.Draw(), PrimitiveUI.PrimitiveCanvas.DrawCircle(), and PrimitiveUI.PrimitiveCanvas.DrawRegularSolid().
DrawCircle() [2/4]
void PrimitiveUI.PrimitiveCanvas.DrawCircle (Vector2 center, float radius, Color fillColor, StrokeStyle strokeStyle) inline
Definition at line 418 of file PrimitiveCanvas.cs.
    {
        DrawCircle(center, radius, 1f, 0f, 360f, fillColor, strokeStyle);
    }
References PrimitiveUI.PrimitiveCanvas.DrawCircle().
DrawCircle() [3/4]
void PrimitiveUI.PrimitiveCanvas.DrawCircle (Vector2 center, float radius, float stepSize = 1f, float startAngle = 0f, float endAngle = 360f, Color? fillColor = null, StrokeStyle strokeStyle = null) inline
Definition at line 423 of file PrimitiveCanvas.cs.
    {
        if (endAngle - startAngle < 0f)
        {
            Debug.LogWarning("DrawCircle() only works in the clockwise-direction; please ensure endAngle > startAngle.");
        }
        else
        {
            DrawEllipse(center, new Vector2(radius, radius * aspectRatio), stepSize, 0f, startAngle, endAngle, fillColor, strokeStyle);
        }
    }
References PrimitiveUI.PrimitiveCanvas.aspectRatio, Debug, and PrimitiveUI.PrimitiveCanvas.DrawEllipse().
DrawCircle() [4/4]
void PrimitiveUI.PrimitiveCanvas.DrawCircle (Vector2 center, float radius, StrokeStyle strokeStyle) inline
Definition at line 413 of file PrimitiveCanvas.cs.
    {
        DrawCircle(center, radius, 1f, 0f, 360f, Color.white, strokeStyle);
    }
References Color, and PrimitiveUI.PrimitiveCanvas.DrawCircle().
DrawEllipse() [1/4]
void PrimitiveUI.PrimitiveCanvas.DrawEllipse (Vector2 center, Vector2 radii, Color fillColor) inline
Definition at line 435 of file PrimitiveCanvas.cs.
    {
        DrawEllipse(center, radii, 1f, 0f, 0f, 360f, fillColor);
    }
References PrimitiveUI.PrimitiveCanvas.DrawEllipse().
Referenced by PrimitiveUI.PrimitiveCanvas.DrawCircle(), and PrimitiveUI.PrimitiveCanvas.DrawEllipse().
DrawEllipse() [2/4]
void PrimitiveUI.PrimitiveCanvas.DrawEllipse (Vector2 center, Vector2 radii, Color fillColor, StrokeStyle strokeStyle) inline
Definition at line 445 of file PrimitiveCanvas.cs.
    {
        DrawEllipse(center, radii, 1f, 0f, 0f, 360f, fillColor, strokeStyle);
    }
References PrimitiveUI.PrimitiveCanvas.DrawEllipse().
DrawEllipse() [3/4]
void PrimitiveUI.PrimitiveCanvas.DrawEllipse (Vector2 center, Vector2 radii, float stepSize = 1f, float rotation = 0f, float startAngle = 0f, float endAngle = 360f, Color? fillColor = null, StrokeStyle strokeStyle = null) inline
Definition at line 450 of file PrimitiveCanvas.cs.
    {
        if (endAngle - startAngle == 0f)
        {
            return;
        }
        if (endAngle - startAngle < 0f)
        {
            Debug.LogWarning("DrawEllipse() only works in the clockwise-direction; please ensure endAngle > startAngle.");
            return;
        }
        Vector2 vector = center;
        if (rotation != 0f)
        {
            radii.x *= aspectRatio;
        }
        float num = MathF.PI / 2f - startAngle * (MathF.PI / 180f);
        float num2 = MathF.PI * 2f / (360f / stepSize);
        int num3 = Mathf.CeilToInt((endAngle - startAngle) / stepSize) + 1;
        List<Vector2> list = new List<Vector2>();
        list.Add(center);
        for (int i = 0; i < num3; i++)
        {
            list.Add(new Vector2(Mathf.Cos(num - num2 * (float)i) * radii.x + center.x, Mathf.Sin(num - num2 * (float)i) * radii.y + center.y));
        }
        if (rotation != 0f)
        {
            rotation *= MathF.PI / 180f;
            float num4 = aspectRatio;
            float num5 = Mathf.Cos(rotation);
            float num6 = Mathf.Sin(rotation);
            for (int j = 0; j < list.Count; j++)
            {
                float num7 = list[j].x - center.x;
                float num8 = list[j].y - center.y;
                list[j] = new Vector2((num7 * num5 + num8 * num6) / num4 + vector.x, num8 * num5 - num7 * num6 + vector.y);
            }
        }
        if (fillColor.HasValue)
        {
            int[] array;
            if (endAngle - startAngle == 0f)
            {
                array = new int[(list.Count - 1) * 3];
                int num9 = 0;
                int num10 = 1;
                while (num9 < array.Length)
                {
                    array[num9] = 0;
                    array[num9 + 1] = num10;
                    array[num9 + 2] = num10 + 1;
                    num9 += 3;
                    num10++;
                }
                array[^1] = 1;
            }
            else
            {
                array = new int[(list.Count - 2) * 3];
                int num11 = 0;
                int num12 = 1;
                while (num11 < array.Length)
                {
                    array[num11] = 0;
                    array[num11 + 1] = num12;
                    array[num11 + 2] = num12 + 1;
                    num11 += 3;
                    num12++;
                }
            }
            elements.Add(new PUIFillElement(list.ToArray(), array, fillColor.Value));
        }
        if (strokeStyle != null)
        {
            DrawPath(list.GetRange(1, list.Count - 2).ToArray(), strokeStyle, closePath: true);
        }
        if (setDirtyOnDraw)
        {
            SetVerticesDirty();
        }
    }
References PrimitiveUI.PrimitiveCanvas.aspectRatio, Debug, PrimitiveUI.PrimitiveCanvas.DrawPath(), PrimitiveUI.PrimitiveCanvas.elements, and PrimitiveUI.PrimitiveCanvas.setDirtyOnDraw.
DrawEllipse() [4/4]
void PrimitiveUI.PrimitiveCanvas.DrawEllipse (Vector2 center, Vector2 radii, StrokeStyle strokeStyle) inline
Definition at line 440 of file PrimitiveCanvas.cs.
    {
        DrawEllipse(center, radii, 1f, 0f, 0f, 360f, null, strokeStyle);
    }
References PrimitiveUI.PrimitiveCanvas.DrawEllipse().
DrawIrregularSolid() [1/4]
void PrimitiveUI.PrimitiveCanvas.DrawIrregularSolid (Vector2 center, float[] radii, Color fillColor) inline
Definition at line 559 of file PrimitiveCanvas.cs.
    {
        DrawIrregularSolid(center, radii, 0f, fillColor, null);
    }
References PrimitiveUI.PrimitiveCanvas.DrawIrregularSolid().
Referenced by PrimitiveUI.Examples.PUIExampleRPGStats.Draw(), and PrimitiveUI.PrimitiveCanvas.DrawIrregularSolid().
DrawIrregularSolid() [2/4]
void PrimitiveUI.PrimitiveCanvas.DrawIrregularSolid (Vector2 center, float[] radii, Color fillColor, StrokeStyle strokeStyle) inline
Definition at line 569 of file PrimitiveCanvas.cs.
    {
        DrawIrregularSolid(center, radii, 0f, fillColor, strokeStyle);
    }
References PrimitiveUI.PrimitiveCanvas.DrawIrregularSolid().
DrawIrregularSolid() [3/4]
void PrimitiveUI.PrimitiveCanvas.DrawIrregularSolid (Vector2 center, float[] radii, float rotation, Color? fillColor, StrokeStyle strokeStyle) inline
Definition at line 574 of file PrimitiveCanvas.cs.
    {
        int num = radii.Length;
        if (num < 3)
        {
            Debug.LogError("DrawIrregularSolid() requires at least 3 radii.");
            return;
        }
        float num2 = MathF.PI / 2f - rotation * (MathF.PI / 180f);
        float num3 = MathF.PI * 2f / (float)num;
        float num4 = aspectRatio;
        List<Vector2> list = new List<Vector2>();
        list.Add(center);
        for (int i = 0; i < num; i++)
        {
            Vector2 vector = new Vector2(radii[i], radii[i] * num4);
            list.Add(new Vector2(Mathf.Cos(num2 - num3 * (float)i) * vector.x + center.x, Mathf.Sin(num2 - num3 * (float)i) * vector.y + center.y));
        }
        if (fillColor.HasValue)
        {
            int[] array = new int[(list.Count - 1) * 3];
            int num5 = 0;
            int num6 = 1;
            while (num5 < array.Length)
            {
                array[num5] = 0;
                array[num5 + 1] = num6;
                array[num5 + 2] = num6 + 1;
                num5 += 3;
                num6++;
            }
            array[^1] = 1;
            elements.Add(new PUIFillElement(list.ToArray(), array, fillColor.Value));
        }
        if (strokeStyle != null)
        {
            DrawPath(list.GetRange(1, list.Count - 2).ToArray(), strokeStyle, closePath: true);
        }
        if (setDirtyOnDraw)
        {
            SetVerticesDirty();
        }
    }
References PrimitiveUI.PrimitiveCanvas.aspectRatio, Debug, PrimitiveUI.PrimitiveCanvas.DrawPath(), PrimitiveUI.PrimitiveCanvas.elements, and PrimitiveUI.PrimitiveCanvas.setDirtyOnDraw.
DrawIrregularSolid() [4/4]
void PrimitiveUI.PrimitiveCanvas.DrawIrregularSolid (Vector2 center, float[] radii, StrokeStyle strokeStyle) inline
Definition at line 564 of file PrimitiveCanvas.cs.
    {
        DrawIrregularSolid(center, radii, 0f, null, strokeStyle);
    }
References PrimitiveUI.PrimitiveCanvas.DrawIrregularSolid().
DrawLine() [1/2]
void PrimitiveUI.PrimitiveCanvas.DrawLine (Vector2 point1, Vector2 point2) inline
Definition at line 782 of file PrimitiveCanvas.cs.
    {
        DrawLine(point1, point2, StrokeStyle.defaultStrokeStyle);
    }
References PrimitiveUI.StrokeStyle.defaultStrokeStyle, and PrimitiveUI.PrimitiveCanvas.DrawLine().
Referenced by PrimitiveUI.Examples.PUIExampleCharts.Draw(), PrimitiveUI.Examples.PUIExampleRPGStats.Draw(), PrimitiveUI.Examples.PUIExampleSineWaves.Draw(), PrimitiveUI.PrimitiveCanvas.DrawLine(), and PrimitiveUI.PrimitiveCanvas.DrawPath().
DrawLine() [2/2]
void PrimitiveUI.PrimitiveCanvas.DrawLine (Vector2 point1, Vector2 point2, StrokeStyle strokeStyle) inline
Definition at line 787 of file PrimitiveCanvas.cs.
    {
        float strokeThickness = ((strokeStyle.scaleMode == StrokeScaleMode.Absolute) ? (strokeStyle.thickness / base.rectTransform.rect.width) : strokeStyle.thickness);
        elements.Add(new PUIStrokeElement(new Vector2[2] { point1, point2 }, PUIUtils.GetLinePoints(point1, point2, strokeThickness, aspectRatio), strokeStyle, isClosedPath: false));
        if (setDirtyOnDraw)
        {
            SetVerticesDirty();
        }
    }
References PrimitiveUI.PrimitiveCanvas.aspectRatio, PrimitiveUI.PrimitiveCanvas.elements, PrimitiveUI.PrimitiveCanvas.PUIUtils.GetLinePoints(), PrimitiveUI.PrimitiveCanvas.setDirtyOnDraw, and PrimitiveUI.StrokeStyle.thickness.
DrawPath() [1/3]
void PrimitiveUI.PrimitiveCanvas.DrawPath (Vector2[] points) inline
Definition at line 797 of file PrimitiveCanvas.cs.
    {
        DrawPath(points, StrokeStyle.defaultStrokeStyle, closePath: false);
    }
References PrimitiveUI.StrokeStyle.defaultStrokeStyle, and PrimitiveUI.PrimitiveCanvas.DrawPath().
Referenced by PrimitiveUI.Examples.PUIExampleCharts.Draw(), PrimitiveUI.Examples.PUIExampleSineWaves.Draw(), PrimitiveUI.PrimitiveCanvas.DrawEllipse(), PrimitiveUI.PrimitiveCanvas.DrawIrregularSolid(), PrimitiveUI.PrimitiveCanvas.DrawPath(), PrimitiveUI.PrimitiveCanvas.DrawPolygon(), and PrimitiveUI.PrimitiveCanvas.DrawRectangle().
DrawPath() [2/3]
void PrimitiveUI.PrimitiveCanvas.DrawPath (Vector2[] points, StrokeStyle strokeStyle) inline
Definition at line 802 of file PrimitiveCanvas.cs.
    {
        DrawPath(points, strokeStyle, closePath: false);
    }
References PrimitiveUI.PrimitiveCanvas.DrawPath().
DrawPath() [3/3]
void PrimitiveUI.PrimitiveCanvas.DrawPath (Vector2[] points, StrokeStyle strokeStyle, bool closePath) inline
Definition at line 807 of file PrimitiveCanvas.cs.
    {
        if (points.Length < 2)
        {
            Debug.LogError("DrawPath() needs at least two points to draw");
            return;
        }
        if (points.Length == 2)
        {
            DrawLine(points[0], points[1], strokeStyle);
            if (closePath)
            {
                Debug.LogWarning("DrawPath() can't close a path with only two points. 'closePath' parameter ignored.");
            }
            return;
        }
        float strokeThickness = ((strokeStyle.scaleMode == StrokeScaleMode.Absolute) ? (strokeStyle.thickness / base.rectTransform.rect.width) : strokeStyle.thickness);
        elements.Add(new PUIStrokeElement(points, PUIUtils.GetPathPoints(points, closePath, strokeThickness, aspectRatio), strokeStyle, closePath));
        if (setDirtyOnDraw)
        {
            SetVerticesDirty();
        }
    }
References PrimitiveUI.PrimitiveCanvas.aspectRatio, Debug, PrimitiveUI.PrimitiveCanvas.DrawLine(), PrimitiveUI.PrimitiveCanvas.elements, PrimitiveUI.PrimitiveCanvas.PUIUtils.GetPathPoints(), PrimitiveUI.PrimitiveCanvas.setDirtyOnDraw, and PrimitiveUI.StrokeStyle.thickness.
DrawPolygon() [1/3]
void PrimitiveUI.PrimitiveCanvas.DrawPolygon (Vector2[] points, Color fillColor) inline
Definition at line 618 of file PrimitiveCanvas.cs.
    {
        DrawPolygon(points, fillColor, null);
    }
References PrimitiveUI.PrimitiveCanvas.DrawPolygon().
Referenced by PrimitiveUI.PrimitiveCanvas.DrawPolygon().
DrawPolygon() [2/3]
void PrimitiveUI.PrimitiveCanvas.DrawPolygon (Vector2[] points, Color fillColor, StrokeStyle strokeStyle) inline
Definition at line 628 of file PrimitiveCanvas.cs.
    {
        if (points.Length < 3)
        {
            Debug.LogError("DrawPolygon() requires at least 3 vertices");
            return;
        }
        if (points.Length == 3)
        {
            points = new Vector2[3]
            {
                points[0],
                points[1],
                points[2]
            };
            elements.Add(new PUIFillElement(points, new int[3] { 0, 1, 2 }, fillColor));
        }
        else if (points.Length == 4)
        {
            elements.Add(new PUIFillElement(points, new int[6] { 0, 1, 2, 2, 3, 0 }, fillColor));
        }
        else
        {
            int[] array = new int[(points.Length - 2) * 3];
            int num = 0;
            LinkedList<Vector2> linkedList = new LinkedList<Vector2>(points);
            List<LinkedListNode<Vector2>> list = new List<LinkedListNode<Vector2>>();
            List<LinkedListNode<Vector2>> list2 = new List<LinkedListNode<Vector2>>();
            List<LinkedListNode<Vector2>> list3 = new List<LinkedListNode<Vector2>>();
            LinkedListNode<Vector2> linkedListNode = linkedList.First;
            LinkedListNode<Vector2> linkedListNode2 = linkedList.First;
            while (linkedListNode.Next != null)
            {
                linkedListNode = linkedListNode.Next;
                if (linkedListNode.Value.x < linkedListNode2.Value.x)
                {
                    linkedListNode2 = linkedListNode;
                }
            }
            LinkedListNode<Vector2> linkedListNode3 = linkedListNode2.Previous ?? linkedListNode2.List.Last;
            LinkedListNode<Vector2> linkedListNode4 = linkedListNode2.Next ?? linkedListNode2.List.First;
            Func<Vector2, Vector2, Vector2, bool> func = ((!(linkedListNode4.Value.y > linkedListNode3.Value.y)) ? ((Func<Vector2, Vector2, Vector2, bool>)delegate(Vector2 prev, Vector2 cur, Vector2 next)
            {
                Vector2 vector2 = cur - prev;
                Vector2 rhs2 = next - cur;
                return Vector2.Dot(new Vector2(0f - vector2.y, vector2.x), rhs2) > 0f;
            }) : ((Func<Vector2, Vector2, Vector2, bool>)delegate(Vector2 prev, Vector2 cur, Vector2 next)
            {
                Vector2 vector = cur - prev;
                Vector2 rhs = next - cur;
                return Vector2.Dot(new Vector2(0f - vector.y, vector.x), rhs) < 0f;
            }));
            linkedListNode = linkedList.First;
            for (int i = 0; i < linkedList.Count; i++)
            {
                linkedListNode3 = linkedListNode.Previous ?? linkedListNode.List.Last;
                linkedListNode4 = linkedListNode.Next ?? linkedListNode.List.First;
                if (func(linkedListNode3.Value, linkedListNode.Value, linkedListNode4.Value))
                {
                    list2.Add(linkedListNode);
                    float triangleArea = PUIUtils.GetTriangleArea(linkedListNode3.Value, linkedListNode.Value, linkedListNode4.Value);
                    bool flag = true;
                    foreach (LinkedListNode<Vector2> item in list3)
                    {
                        if (PUIUtils.PointInTriangle(item.Value, linkedListNode3.Value, linkedListNode.Value, linkedListNode4.Value, triangleArea))
{
                            flag = false;
                            break;
                        }
                    }
                    if (flag)
                    {
                        list.Add(linkedListNode);
                    }
                }
                else
                {
                    list3.Add(linkedListNode);
                }
                linkedListNode = linkedListNode.Next;
            }
            while (linkedList.Count > 3)
            {
                linkedListNode = list[0];
                linkedListNode3 = linkedListNode.Previous ?? linkedListNode.List.Last;
                linkedListNode4 = linkedListNode.Next ?? linkedListNode.List.First;
                array[num] = Array.IndexOf(points, linkedListNode3.Value);
                array[num + 1] = Array.IndexOf(points, linkedListNode.Value);
                array[num + 2] = Array.IndexOf(points, linkedListNode4.Value);
                num += 3;
                list.Remove(linkedListNode);
                linkedList.Remove(linkedListNode);
                LinkedListNode<Vector2>[] array2 = new LinkedListNode<Vector2>[2] { linkedListNode3, linkedListNode4 };
                foreach (LinkedListNode<Vector2> linkedListNode5 in array2)
                {
                    LinkedListNode<Vector2> linkedListNode6 = linkedListNode5.Previous ?? linkedListNode5.List.Last;
                    LinkedListNode<Vector2> linkedListNode7 = linkedListNode5.Next ?? linkedListNode5.List.First;
                    if (func(linkedListNode6.Value, linkedListNode5.Value, linkedListNode7.Value))
                    {
                        if (list3.Contains(linkedListNode5))
{
                            list3.Remove(linkedListNode5);
                            list2.Add(linkedListNode5);
                        }
                        float triangleArea2 = PUIUtils.GetTriangleArea(linkedListNode6.Value, linkedListNode5.Value, linkedListNode7.Value);
                        bool flag2 = true;
                        foreach (LinkedListNode<Vector2> item2 in list3)
{
                            if (PUIUtils.PointInTriangle(item2.Value, linkedListNode6.Value, linkedListNode5.Value, linkedListNode7.Value, triangleArea2))
{
                                flag2 = false;
                                break;
                            }
                        }
                        if (flag2 && !list.Contains(linkedListNode5))
{
                            list.Add(linkedListNode5);
                        }
                        else if (!flag2 && list.Contains(linkedListNode5))
{
                            list.Remove(linkedListNode5);
                        }
                    }
                    else
                    {
                        list2.Remove(linkedListNode5);
                        list3.Add(linkedListNode5);
                    }
                }
            }
            array[num] = Array.IndexOf(points, linkedList.First.Value);
            array[num + 1] = Array.IndexOf(points, linkedList.First.Next.Value);
            array[num + 2] = Array.IndexOf(points, linkedList.First.Next.Next.Value);
            elements.Add(new PUIFillElement(points, array, fillColor));
        }
        if (strokeStyle != null)
        {
            DrawPath(points, strokeStyle, closePath: true);
        }
        if (setDirtyOnDraw)
        {
            SetVerticesDirty();
        }
    }
References Debug, PrimitiveUI.PrimitiveCanvas.DrawPath(), PrimitiveUI.PrimitiveCanvas.elements, PrimitiveUI.PrimitiveCanvas.PUIUtils.GetTriangleArea(), item, PrimitiveUI.PrimitiveCanvas.PUIUtils.PointInTriangle(), and PrimitiveUI.PrimitiveCanvas.setDirtyOnDraw.
DrawPolygon() [3/3]
void PrimitiveUI.PrimitiveCanvas.DrawPolygon (Vector2[] points, StrokeStyle strokeStyle) inline
Definition at line 623 of file PrimitiveCanvas.cs.
    {
        DrawPath(points, strokeStyle, closePath: true);
    }
References PrimitiveUI.PrimitiveCanvas.DrawPath().
DrawRawMesh()
void PrimitiveUI.PrimitiveCanvas.DrawRawMesh (Vector2[] points, int[] triangles, Color fillColor) inline
Definition at line 773 of file PrimitiveCanvas.cs.
    {
        elements.Add(new PUIFillElement(points, triangles, fillColor));
        if (setDirtyOnDraw)
        {
            SetVerticesDirty();
        }
    }
References PrimitiveUI.PrimitiveCanvas.elements, and PrimitiveUI.PrimitiveCanvas.setDirtyOnDraw.
DrawRectangle() [1/8]
void PrimitiveUI.PrimitiveCanvas.DrawRectangle (float x, float y, float width, float height, Color fillColor) inline
Definition at line 335 of file PrimitiveCanvas.cs.
    {
        DrawRectangle(new Rect(x, y, width, height), 0f, fillColor);
    }
References PrimitiveUI.PrimitiveCanvas.DrawRectangle().
Referenced by PrimitiveUI.Examples.PUIExampleCharts.Draw(), PrimitiveUI.PrimitiveCanvas.DrawRectangle(), and PrimitiveUI.PrimitiveCanvas.DrawSquare().
DrawRectangle() [2/8]
void PrimitiveUI.PrimitiveCanvas.DrawRectangle (float x, float y, float width, float height, Color fillColor, StrokeStyle strokeStyle) inline
Definition at line 345 of file PrimitiveCanvas.cs.
    {
        DrawRectangle(new Rect(x, y, width, height), fillColor, strokeStyle);
    }
References PrimitiveUI.PrimitiveCanvas.DrawRectangle().
DrawRectangle() [3/8]
void PrimitiveUI.PrimitiveCanvas.DrawRectangle (float x, float y, float width, float height, float rotation = 0f, Color? fillColor = null, StrokeStyle strokeStyle = null) inline
Definition at line 350 of file PrimitiveCanvas.cs.
    {
        DrawRectangle(new Rect(x, y, width, height), rotation, fillColor, strokeStyle);
    }
References PrimitiveUI.PrimitiveCanvas.DrawRectangle().
DrawRectangle() [4/8]
void PrimitiveUI.PrimitiveCanvas.DrawRectangle (float x, float y, float width, float height, StrokeStyle strokeStyle) inline
Definition at line 340 of file PrimitiveCanvas.cs.
    {
        DrawRectangle(new Rect(x, y, width, height), strokeStyle);
    }
References PrimitiveUI.PrimitiveCanvas.DrawRectangle().
DrawRectangle() [5/8]
void PrimitiveUI.PrimitiveCanvas.DrawRectangle (Rect rect, Color fillColor) inline
Definition at line 355 of file PrimitiveCanvas.cs.
    {
        DrawRectangle(rect, 0f, fillColor);
    }
References PrimitiveUI.PrimitiveCanvas.DrawRectangle().
DrawRectangle() [6/8]
void PrimitiveUI.PrimitiveCanvas.DrawRectangle (Rect rect, Color fillColor, StrokeStyle strokeStyle) inline
Definition at line 365 of file PrimitiveCanvas.cs.
    {
        DrawRectangle(rect, 0f, fillColor, strokeStyle);
    }
References PrimitiveUI.PrimitiveCanvas.DrawRectangle().
DrawRectangle() [7/8]
void PrimitiveUI.PrimitiveCanvas.DrawRectangle (Rect rect, float rotation = 0f, Color? fillColor = null, StrokeStyle strokeStyle = null) inline
Definition at line 370 of file PrimitiveCanvas.cs.
    {
        Vector2 center = rect.center;
        Vector2[] array = new Vector2[4];
        if (rotation != 0f)
        {
            rect.width *= aspectRatio;
        }
        array[0] = new Vector2(rect.min.x, rect.min.y);
        array[1] = new Vector2(rect.min.x, rect.max.y);
        array[2] = new Vector2(rect.max.x, rect.max.y);
        array[3] = new Vector2(rect.max.x, rect.min.y);
        if (rotation != 0f)
        {
            rotation *= MathF.PI / 180f;
            float num = Mathf.Cos(rotation);
            float num2 = Mathf.Sin(rotation);
            for (int i = 0; i < array.Length; i++)
            {
                float num3 = array[i].x - rect.center.x;
                float num4 = array[i].y - rect.center.y;
                array[i] = new Vector2((num3 * num + num4 * num2) / aspectRatio + center.x, num4 * num - num3 * num2 + center.y);
            }
        }
        if (fillColor.HasValue)
        {
            elements.Add(new PUIFillElement(array, new int[6] { 0, 1, 2, 2, 3, 0 }, fillColor.Value));
        }
        if (strokeStyle != null)
        {
            DrawPath(array, strokeStyle, closePath: true);
        }
        if (setDirtyOnDraw)
        {
            SetVerticesDirty();
        }
    }
References PrimitiveUI.PrimitiveCanvas.aspectRatio, PrimitiveUI.PrimitiveCanvas.DrawPath(), PrimitiveUI.PrimitiveCanvas.elements, and PrimitiveUI.PrimitiveCanvas.setDirtyOnDraw.
DrawRectangle() [8/8]
void PrimitiveUI.PrimitiveCanvas.DrawRectangle (Rect rect, StrokeStyle strokeStyle) inline
Definition at line 360 of file PrimitiveCanvas.cs.
    {
        DrawRectangle(rect, 0f, null, strokeStyle);
    }
References PrimitiveUI.PrimitiveCanvas.DrawRectangle().
DrawRegularSolid() [1/4]
void PrimitiveUI.PrimitiveCanvas.DrawRegularSolid (Vector2 center, float radius, int sides, Color fillColor) inline
Definition at line 532 of file PrimitiveCanvas.cs.
    {
        DrawRegularSolid(center, radius, sides, 0f, fillColor);
    }
References PrimitiveUI.PrimitiveCanvas.DrawRegularSolid().
Referenced by PrimitiveUI.Examples.PUIExampleRPGStats.Draw(), and PrimitiveUI.PrimitiveCanvas.DrawRegularSolid().
DrawRegularSolid() [2/4]
void PrimitiveUI.PrimitiveCanvas.DrawRegularSolid (Vector2 center, float radius, int sides, Color fillColor, StrokeStyle strokeStyle) inline
Definition at line 542 of file PrimitiveCanvas.cs.
    {
        DrawRegularSolid(center, radius, sides, 0f, fillColor, strokeStyle);
    }
References PrimitiveUI.PrimitiveCanvas.DrawRegularSolid().
DrawRegularSolid() [3/4]
void PrimitiveUI.PrimitiveCanvas.DrawRegularSolid (Vector2 center, float radius, int sides, float rotation = 0f, Color? fillColor = null, StrokeStyle strokeStyle = null) inline
Definition at line 547 of file PrimitiveCanvas.cs.
    {
        if (sides < 3)
        {
            Debug.LogError("DrawRegularSolid() requires at least 3 sides.");
        }
        else
        {
            DrawCircle(center, radius, 360f / (float)sides, rotation, 360f + rotation, fillColor, strokeStyle);
        }
    }
References Debug, and PrimitiveUI.PrimitiveCanvas.DrawCircle().
DrawRegularSolid() [4/4]
void PrimitiveUI.PrimitiveCanvas.DrawRegularSolid (Vector2 center, float radius, int sides, StrokeStyle strokeStyle) inline
Definition at line 537 of file PrimitiveCanvas.cs.
    {
        DrawRegularSolid(center, radius, sides, 0f, null, strokeStyle);
    }
References PrimitiveUI.PrimitiveCanvas.DrawRegularSolid().
DrawSquare() [1/4]
void PrimitiveUI.PrimitiveCanvas.DrawSquare (Vector2 center, float size, Color fillColor) inline
Definition at line 315 of file PrimitiveCanvas.cs.
    {
        DrawSquare(center, size, 0f, fillColor);
    }
References PrimitiveUI.PrimitiveCanvas.DrawSquare().
Referenced by PrimitiveUI.PrimitiveCanvas.DrawSquare().
DrawSquare() [2/4]
void PrimitiveUI.PrimitiveCanvas.DrawSquare (Vector2 center, float size, Color fillColor, StrokeStyle strokeStyle) inline
Definition at line 325 of file PrimitiveCanvas.cs.
    {
        DrawSquare(center, size, 0f, fillColor, strokeStyle);
    }
References PrimitiveUI.PrimitiveCanvas.DrawSquare().
DrawSquare() [3/4]
void PrimitiveUI.PrimitiveCanvas.DrawSquare (Vector2 center, float size, float rotation = 0f, Color? fillColor = null, StrokeStyle strokeStyle = null) inline
Definition at line 330 of file PrimitiveCanvas.cs.
    {
        DrawRectangle(new Rect(center.x - size * 0.5f, center.y - size * 0.5f * aspectRatio, size, size * aspectRatio), rotation, fillColor, strokeStyle);
    }
References PrimitiveUI.PrimitiveCanvas.aspectRatio, and PrimitiveUI.PrimitiveCanvas.DrawRectangle().
DrawSquare() [4/4]
void PrimitiveUI.PrimitiveCanvas.DrawSquare (Vector2 center, float size, StrokeStyle strokeStyle) inline
Definition at line 320 of file PrimitiveCanvas.cs.
    {
        DrawSquare(center, size, 0f, null, strokeStyle);
    }
References PrimitiveUI.PrimitiveCanvas.DrawSquare().
OnPopulateMesh()
override void PrimitiveUI.PrimitiveCanvas.OnPopulateMesh (VertexHelper vh) inline protected
Definition at line 271 of file PrimitiveCanvas.cs.
    {
        vh.Clear();
        Vector2 size = base.rectTransform.rect.size;
        Vector3 vector = new Vector3(0f - base.rectTransform.pivot.x, 0f - base.rectTransform.pivot.y, 0f);
        List<List<UIVertex>> list = new List<List<UIVertex>>(elements.Count);
        for (int i = 0; i < elements.Count; i++)
        {
            list.Add(elements[i].GetUIVertexTriangleStream(vector, size, color));
        }
        vh.AddUIVertexTriangleStream(list.SelectMany((List<UIVertex> l) => l).ToList());
    }
References PrimitiveUI.PrimitiveCanvas.elements.
OnRectTransformDimensionsChange()
override void PrimitiveUI.PrimitiveCanvas.OnRectTransformDimensionsChange () inline protected
Definition at line 290 of file PrimitiveCanvas.cs.
    {
        base.OnRectTransformDimensionsChange();
        foreach (PUIElement element in elements)
        {
            if (!(element.GetType() == typeof(PUIStrokeElement)))
            {
                continue;
            }
            PUIStrokeElement pUIStrokeElement = (PUIStrokeElement)element;
            if (pUIStrokeElement.strokeStyle.scaleMode == StrokeScaleMode.Absolute)
            {
                float strokeThickness = pUIStrokeElement.strokeStyle.thickness / base.rectTransform.rect.width;
                if (pUIStrokeElement.rawPoints.Length == 2)
                {
                    pUIStrokeElement.UpdatePoints(PUIUtils.GetLinePoints(pUIStrokeElement.rawPoints[0], pUIStrokeElement.rawPoints[1], strokeThickness, aspectRatio));
                }
                else
                {
                    pUIStrokeElement.UpdatePoints(PUIUtils.GetPathPoints(pUIStrokeElement.rawPoints, pUIStrokeElement.isClosedPath, strokeThickness, aspectRatio));
                }
            }
        }
    }
References PrimitiveUI.PrimitiveCanvas.aspectRatio, PrimitiveUI.PrimitiveCanvas.elements, PrimitiveUI.PrimitiveCanvas.PUIUtils.GetLinePoints(), PrimitiveUI.PrimitiveCanvas.PUIUtils.GetPathPoints(), PrimitiveUI.PrimitiveCanvas.PUIStrokeElement.isClosedPath, PrimitiveUI.PrimitiveCanvas.PUIStrokeElement.rawPoints, PrimitiveUI.StrokeStyle.scaleMode, PrimitiveUI.PrimitiveCanvas.PUIStrokeElement.strokeStyle, and PrimitiveUI.PrimitiveCanvas.PUIStrokeElement.UpdatePoints().
Member Data Documentation
elements
List<PUIElement> PrimitiveUI.PrimitiveCanvas.elements = new List<PUIElement>() private
Definition at line 267 of file PrimitiveCanvas.cs.
Referenced by PrimitiveUI.PrimitiveCanvas.Clear(), PrimitiveUI.PrimitiveCanvas.DrawEllipse(), PrimitiveUI.PrimitiveCanvas.DrawIrregularSolid(), PrimitiveUI.PrimitiveCanvas.DrawLine(), PrimitiveUI.PrimitiveCanvas.DrawPath(), PrimitiveUI.PrimitiveCanvas.DrawPolygon(), PrimitiveUI.PrimitiveCanvas.DrawRawMesh(), PrimitiveUI.PrimitiveCanvas.DrawRectangle(), PrimitiveUI.PrimitiveCanvas.OnPopulateMesh(), and PrimitiveUI.PrimitiveCanvas.OnRectTransformDimensionsChange().
setDirtyOnDraw
bool PrimitiveUI.PrimitiveCanvas.setDirtyOnDraw = true
Definition at line 265 of file PrimitiveCanvas.cs.
Referenced by PrimitiveUI.PrimitiveCanvas.DrawEllipse(), PrimitiveUI.PrimitiveCanvas.DrawIrregularSolid(), PrimitiveUI.PrimitiveCanvas.DrawLine(), PrimitiveUI.PrimitiveCanvas.DrawPath(), PrimitiveUI.PrimitiveCanvas.DrawPolygon(), PrimitiveUI.PrimitiveCanvas.DrawRawMesh(), and PrimitiveUI.PrimitiveCanvas.DrawRectangle().
Property Documentation
aspectRatio
float PrimitiveUI.PrimitiveCanvas.aspectRatio get
Definition at line 269 of file PrimitiveCanvas.cs.
Referenced by PrimitiveUI.Examples.PUIExampleRPGStats.Draw(), PrimitiveUI.Examples.PUIExampleSineWaves.Draw(), PrimitiveUI.PrimitiveCanvas.DrawCircle(), PrimitiveUI.PrimitiveCanvas.DrawEllipse(), PrimitiveUI.PrimitiveCanvas.DrawIrregularSolid(), PrimitiveUI.PrimitiveCanvas.DrawLine(), PrimitiveUI.PrimitiveCanvas.DrawPath(), PrimitiveUI.PrimitiveCanvas.DrawRectangle(), PrimitiveUI.PrimitiveCanvas.DrawSquare(), PrimitiveUI.PrimitiveCanvas.PUIUtils.GetLinePoints(), PrimitiveUI.PrimitiveCanvas.PUIUtils.GetPathPoints(), and PrimitiveUI.PrimitiveCanvas.OnRectTransformDimensionsChange().
The documentation for this class was generated from the following file:
Elin/Plugins.UI/PrimitiveUI/PrimitiveCanvas.cs