Elin Decompiled Documentation: LayerLocation Class Reference
LayerLocation Class Reference
Public Member Functions
override bool HeaderIsListOf (int id)
override void OnSwitchContent (Window window)
void RefreshZones ()
Public Member Functions inherited from ELayer
override void OnBeforeAddLayer ()
void InitInspector ()
sealed override void Init ()
override void OnAfterAddLayer ()
void TryShowHelp ()
void AddLayerToUI (string id)
void TryShowHint (string _langHint=null)
void TalkHomeMemeber (string id)
void TalkMaid (string id)
override void OnRightClick ()
Public Member Functions inherited from Layer
virtual string GetTextHeader (Window window)
virtual bool HeaderIsListOf (int id)
virtual void Init ()
virtual void OnInit ()
virtual void OnAfterInit ()
virtual void ApplySkin ()
void ShowScreenLock (string id)
void UpdateInput ()
virtual void OnUpdateInput ()
virtual void OnRightClick ()
virtual bool OnBack ()
virtual void OnChangeLayer ()
virtual void OnCreate ()
void _AddLayer (string id)
Layer AddLayer (string id)
T AddLayer< T > ()
T AddLayer< T > (string id)
T AddLayerDontCloseOthers< T > ()
Layer AddLayerDontCloseOthers (Layer l)
T GetOrAddLayer< T > ()
virtual void OnBeforeAddLayer ()
virtual void OnAfterAddLayer ()
Layer AddLayer (Layer l)
void ToggleLayer (string id)
T ToggleLayer< T > (string id=null)
void WaitAndClose ()
void OnClickClose ()
virtual void Close ()
void CloseLayers ()
void RemoveLayers (bool removeImportant=false)
bool RemoveLayer< T > ()
void RemoveLayer (Layer l)
virtual void OnKill ()
Layer SetOnKill (Action action)
void DisableClose ()
void Delay (float duration=0.05f)
Layer SetDelay (float d)
Layer GetLayer (string id)
T GetLayer< T > (bool fromTop=false)
Layer GetTopLayer ()
void SwitchContent (int idWindow, int i)
virtual void OnSwitchContent (Window window)
Layer SetTitles (string langList, string idHeaderRow=null)
bool IsBlockWidgetClick ()
bool IsHideHud ()
bool IsAllowGeneralInput ()
bool IsUseBlur ()
bool IsPointerOnLayer ()
void ApplySkin ()
Public Attributes
UIList listZone
Sprite spriteFaction
Sprite spriteFaith
UIZoneInfo info
Public Attributes inherited from Layer
Option option
UnityEvent onKill
Anime animeIn
Anime animeOut
bool closeOthers
bool defaultActionMode = true
Button screenLock
Layer parent
string idLayer
List< Layer > layers = new List<Layer>()
Vector2 lastParentPos
List< Window > windows = new List<Window>()
string langHint
Additional Inherited Members
Static Public Member Functions inherited from ELayer
static int rnd (int a)
Static Public Member Functions inherited from Layer
static T Create< T > ()
static T Create< T > (string path)
static Layer Create (string path)
Static Public Attributes inherited from Layer
static int skipInput
static bool closeOnRightClick
static bool rightClicked
static bool cancelKeyDown
static bool ignoreSounds
static Transform blurStopInstance
static string[] searchPath = new string[3] { "Layer", "Layer/Dialog", "Layer/LayerHome" }
Protected Member Functions inherited from ELayer
sealed override void _Close ()
sealed override void Kill ()
Protected Member Functions inherited from Layer
virtual void Awake ()
virtual void _Close ()
virtual void Kill ()
Protected Attributes inherited from Layer
RectTransform _rect
bool isDestroyed
Properties inherited from ELayer
static Core core [get]
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static FactionBranch Branch [get]
static Faction Home [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static CoreConfig config [get]
static GameSetting setting [get]
static ColorProfile Colors [get]
static SourceManager sources [get]
static World world [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
bool IsFloat [get]
virtual string IdHelp [get]
Properties inherited from Layer
Layer TopLayer [get]
string uid [get]
virtual RectTransform rectLayers [get]
virtual bool blockWidgetClick [get]
Detailed Description
Definition at line 3 of file LayerLocation.cs.
Member Function Documentation
HeaderIsListOf()
override bool LayerLocation.HeaderIsListOf (int id) inline virtual
Reimplemented from Layer.
Definition at line 13 of file LayerLocation.cs.
    {
        return true;
    }
OnSwitchContent()
override void LayerLocation.OnSwitchContent (Window window) inline virtual
Reimplemented from Layer.
Definition at line 18 of file LayerLocation.cs.
    {
        if (window.windowIndex == 1)
        {
            RefreshZones();
        }
    }
References RefreshZones(), and Window.windowIndex.
RefreshZones()
void LayerLocation.RefreshZones () inline
Definition at line 26 of file LayerLocation.cs.
    {
        UIList uIList = listZone;
        uIList.Clear();
        uIList.callbacks = new UIList.Callback<Spatial, ItemGeneral>
        {
            onClick = delegate(Spatial a, ItemGeneral b)
            {
                if (a is Zone)
                {
                    info.SetZone(a as Zone);
                }
            },
            onInstantiate = delegate(Spatial a, ItemGeneral b)
            {
                b.SetSound();
                b.SetMainText(a.Name);
                b.Build();
            }
        };
        foreach (Spatial value in ELayer.game.spatials.map.Values)
        {
            if (!(value is Zone) || value.parent != ELayer.pc.currentZone.Region)
            {
                continue;
            }
            if (windows[1].idTab == 0)
            {
                if (!value.IsPlayerFaction)
                {
                    continue;
                }
            }
            else if (value.IsPlayerFaction)
            {
                continue;
            }
            uIList.Add(value);
        }
        uIList.Refresh();
    }
References ItemGeneral.Build(), UIList.Clear(), Chara.currentZone, ELayer.game, info, Spatial.IsPlayerFaction, listZone, SpatialManager.map, Spatial.Name, Spatial.parent, ELayer.pc, Zone.Region, ItemGeneral.SetMainText(), ItemGeneral.SetSound(), UIZoneInfo.SetZone(), Game.spatials, and Layer.windows.
Referenced by OnSwitchContent().
Member Data Documentation
info
UIZoneInfo LayerLocation.info
Definition at line 11 of file LayerLocation.cs.
Referenced by RefreshZones().
listZone
UIList LayerLocation.listZone
Definition at line 5 of file LayerLocation.cs.
Referenced by RefreshZones().
spriteFaction
Sprite LayerLocation.spriteFaction
Definition at line 7 of file LayerLocation.cs.
spriteFaith
Sprite LayerLocation.spriteFaith
Definition at line 9 of file LayerLocation.cs.
The documentation for this class was generated from the following file:
Elin/LayerLocation.cs