Elin Decompiled Documentation: ContentConfigOther Class Reference
ContentConfigOther Class Reference
Public Member Functions
override void OnInstantiate ()
void OpenLog ()
void OoenConfigFolder ()
void OpenPackage ()
void OpenUser ()
void ResetWindows ()
void OpenBackerCodeInput ()
void OnClickDownloadWallpaper ()
void RefreshRewardCode ()
Public Member Functions inherited from ContentConfig
void SetSlider (Slider slider, float value, Func< float, string > action)
Public Member Functions inherited from UIContent
virtual void OnSwitchContent (int idTab)
virtual void OnInstantiate ()
Public Member Functions inherited from UINote
void Clear ()
void Build ()
void Space (int sizeY=0, int sizeX=1)
UINote AddNote (string id)
UIItem AddHeader (string text, Sprite sprite=null)
UIItem AddHeaderCard (string text, Sprite sprite=null)
UIItem AddHeaderTopic (string text, Sprite sprite=null)
UIItem AddHeader (string id, string text, Sprite sprite=null)
UIItem AddText (string text, FontColor color=FontColor.DontChange)
UIItem AddText (string id, string text, FontColor color=FontColor.DontChange)
UIItem AddText (string id, string text, Color color)
UIItem AddItem (string id)
UIItem AddTopic (string id, string text, string value=null)
UIItem AddTopic (string text, string value=null)
void AddImage (Sprite sprite)
void AddImage (string idFile)
UIButton AddButton (string text, Action onClick)
UIButton AddButtonLink (string text, string url)
UIDropdown AddDropdown (string id="DropdownDefault")
UIButton AddToggle (string idLang="", bool isOn=false, Action< bool > action=null)
Transform AddPrefab (string path)
T AddExtra< T > (string path)
Public Attributes
UIButton toggleSyncMod
UIButton toggleNoCensor
UIButton toggleRunBackground
UIButton toggleMuteBackground
UIButton toggleTest
UIButton toggleAltInv
UIButton toggleAltAbility
UIButton buttonBackerCode
UIButton toggleDisableMods
UIButton buttonWallPaper
UIDropdown ddSnap
UIDropdown ddDivider
Slider sliderMissClick
Slider sliderBGMInterval
UIText textBackerCode
Public Attributes inherited from UINote
RectTransform target
UINoteProfile prof
SkinType skinType
string idDefaultText
LayoutGroup layout
RectTransform cur
bool extraRebuild
Additional Inherited Members
Properties inherited from ContentConfig
CoreConfig config [get]
Detailed Description
Definition at line 7 of file ContentConfigOther.cs.
Member Function Documentation
OnClickDownloadWallpaper()
void ContentConfigOther.OnClickDownloadWallpaper () inline
Definition at line 154 of file ContentConfigOther.cs.
    {
        EClass.core.WaitForEndOfFrame(delegate
        {
            string text = StandaloneFileBrowser.SaveFilePanel("Export Wallpaper", CorePath.RootData, "wallpaper", "zip");
            Debug.Log(text);
            if (!string.IsNullOrEmpty(text))
            {
                try
                {
                    TextAsset textAsset = Resources.Load("Etc/wallpaper") as TextAsset;
                    Debug.Log(textAsset);
                    File.WriteAllBytes(text, textAsset.bytes);
                    EClass.ui.Say("umimyaaThankyou");
                    SE.Play("godbless");
                }
                catch (Exception ex)
                {
                    EClass.ui.Say(ex.Message);
                }
            }
        });
    }
References EClass.core, Debug, if(), CorePath.RootData, SFB.StandaloneFileBrowser.SaveFilePanel(), EClass.ui, and BaseCore.WaitForEndOfFrame().
OnInstantiate()
override void ContentConfigOther.OnInstantiate () inline virtual
Reimplemented from UIContent.
Definition at line 39 of file ContentConfigOther.cs.
    {
        ddSnap.SetList((int)base.config.fix.snapType, Util.EnumToList<CoreConfig.ScreenSnapType>(), (CoreConfig.ScreenSnapType a, int b) => a.ToString().lang(), delegate(int a, CoreConfig.ScreenSnapType b)
        {
            base.config.fix.snapType = b;
        });
        ddDivider.SetList((int)base.config.fix.divider, Util.EnumToList<CameraSupport.Divider>(), (CameraSupport.Divider a, int b) => a.ToString().lang(), delegate(int a, CameraSupport.Divider b)
        {
            base.config.fix.divider = b;
            EClass.core.screen.RefreshScreenSize();
        });
        SetSlider(sliderMissClick, base.config.other.antiMissClick, delegate(float a)
        {
            base.config.other.antiMissClick = (int)a;
            EInput.antiMissClick = 0.1f * a;
            return Lang.Get("antiMissClick") + "(" + 0.1f * a + "s)";
        });
        SetSlider(sliderBGMInterval, base.config.other.bgmInterval, delegate(float a)
        {
            base.config.other.bgmInterval = (int)a;
            base.config.ApplyVolume();
            return Lang.Get("bgmInterval") + "(" + a * 5f + "sec)";
        });
        toggleSyncMod.SetToggle(base.config.other.syncMods, delegate(bool on)
        {
            base.config.other.syncMods = on;
        });
        toggleDisableMods.SetToggle(base.config.other.disableMods, delegate(bool on)
        {
            base.config.other.disableMods = on;
        });
        toggleNoCensor.SetToggle(base.config.other.noCensor, delegate(bool on)
        {
            base.config.other.noCensor = on;
            base.config.Apply();
        });
        toggleRunBackground.SetToggle(base.config.other.runBackground, delegate(bool on)
        {
            base.config.other.runBackground = on;
            base.config.Apply();
        });
        toggleMuteBackground.SetToggle(base.config.other.muteBackground, delegate(bool on)
        {
            base.config.other.muteBackground = on;
            base.config.Apply();
        });
        toggleAltInv.SetToggle(base.config.game.altInv, delegate(bool on)
        {
            base.config.game.altInv = on;
            EClass.ui.layerFloat.RemoveLayers(removeImportant: true);
        });
        toggleAltAbility.SetToggle(base.config.game.altAbility, delegate(bool on)
        {
            base.config.game.altAbility = on;
            EClass.ui.layerFloat.RemoveLayers(removeImportant: true);
        });
        toggleTest.SetToggle(base.config.other.showTestOptions, delegate(bool on)
        {
            base.config.other.showTestOptions = on;
            EClass.ui.GetLayer<LayerConfig>().Close();
            EClass.ui.AddLayer<LayerConfig>();
        });
        buttonWallPaper.SetActive(base.config.HasBackerRewardCode());
        RefreshRewardCode();
    }
References buttonWallPaper, ddDivider, ddSnap, Lang.Get(), RefreshRewardCode(), ContentConfig.SetSlider(), UIButton.SetToggle(), sliderBGMInterval, sliderMissClick, toggleAltAbility, toggleAltInv, toggleDisableMods, toggleMuteBackground, toggleNoCensor, toggleRunBackground, toggleSyncMod, toggleTest, EClass.ui, and Util.
OoenConfigFolder()
void ContentConfigOther.OoenConfigFolder () inline
Definition at line 110 of file ContentConfigOther.cs.
    {
        Util.ShowExplorer(CorePath.RootSave + "config.txt");
    }
References CorePath.RootSave, and Util.
OpenBackerCodeInput()
void ContentConfigOther.OpenBackerCodeInput () inline
Definition at line 133 of file ContentConfigOther.cs.
    {
        Dialog.InputName("dialogBackerCode", "", delegate(bool cancel, string text)
        {
            if (!cancel)
            {
                if (ElinEncoder.IsValid(text))
                {
                    base.config.rewardCode = text;
                    SE.Change();
                    EClass.ui.GetLayer<LayerConfig>().Close();
                    EClass.ui.AddLayer<LayerConfig>();
                }
                else
                {
                    Dialog.Ok("invalidRewardCode".lang(text));
                }
            }
        });
    }
References Dialog.InputName(), and ElinEncoder.IsValid().
OpenLog()
void ContentConfigOther.OpenLog () inline
Definition at line 105 of file ContentConfigOther.cs.
    {
        Util.ShowExplorer(CorePath.RootSave);
    }
References CorePath.RootSave, and Util.
OpenPackage()
void ContentConfigOther.OpenPackage () inline
Definition at line 115 of file ContentConfigOther.cs.
    {
        Util.ShowExplorer(CorePath.rootMod + "_Elona");
    }
References CorePath.rootMod, and Util.
OpenUser()
void ContentConfigOther.OpenUser () inline
Definition at line 120 of file ContentConfigOther.cs.
    {
        Util.ShowExplorer(CorePath.user + "PCC");
    }
References CorePath.user, and Util.
RefreshRewardCode()
void ContentConfigOther.RefreshRewardCode () inline
Definition at line 178 of file ContentConfigOther.cs.
    {
        buttonBackerCode.interactable = !base.config.HasBackerRewardCode() || EClass.debug.enable;
        if (base.config.HasBackerRewardCode())
        {
            buttonBackerCode.mainText.SetText("rewardCodeActive".lang());
        }
    }
References buttonBackerCode, EClass.debug, CoreDebug.enable, UIButton.mainText, and UIText.SetText().
Referenced by OnInstantiate().
ResetWindows()
void ContentConfigOther.ResetWindows () inline
Definition at line 125 of file ContentConfigOther.cs.
    {
        Dialog.YesNo("dialogResetWindow", delegate
        {
            Window.dictData.Clear();
        });
    }
References Window.dictData, and Dialog.YesNo().
Member Data Documentation
buttonBackerCode
UIButton ContentConfigOther.buttonBackerCode
Definition at line 23 of file ContentConfigOther.cs.
Referenced by RefreshRewardCode().
buttonWallPaper
UIButton ContentConfigOther.buttonWallPaper
Definition at line 27 of file ContentConfigOther.cs.
Referenced by OnInstantiate().
ddDivider
UIDropdown ContentConfigOther.ddDivider
Definition at line 31 of file ContentConfigOther.cs.
Referenced by OnInstantiate().
ddSnap
UIDropdown ContentConfigOther.ddSnap
Definition at line 29 of file ContentConfigOther.cs.
Referenced by OnInstantiate().
sliderBGMInterval
Slider ContentConfigOther.sliderBGMInterval
Definition at line 35 of file ContentConfigOther.cs.
Referenced by OnInstantiate().
sliderMissClick
Slider ContentConfigOther.sliderMissClick
Definition at line 33 of file ContentConfigOther.cs.
Referenced by OnInstantiate().
textBackerCode
UIText ContentConfigOther.textBackerCode
Definition at line 37 of file ContentConfigOther.cs.
toggleAltAbility
UIButton ContentConfigOther.toggleAltAbility
Definition at line 21 of file ContentConfigOther.cs.
Referenced by OnInstantiate().
toggleAltInv
UIButton ContentConfigOther.toggleAltInv
Definition at line 19 of file ContentConfigOther.cs.
Referenced by OnInstantiate().
toggleDisableMods
UIButton ContentConfigOther.toggleDisableMods
Definition at line 25 of file ContentConfigOther.cs.
Referenced by OnInstantiate().
toggleMuteBackground
UIButton ContentConfigOther.toggleMuteBackground
Definition at line 15 of file ContentConfigOther.cs.
Referenced by OnInstantiate().
toggleNoCensor
UIButton ContentConfigOther.toggleNoCensor
Definition at line 11 of file ContentConfigOther.cs.
Referenced by OnInstantiate().
toggleRunBackground
UIButton ContentConfigOther.toggleRunBackground
Definition at line 13 of file ContentConfigOther.cs.
Referenced by OnInstantiate().
toggleSyncMod
UIButton ContentConfigOther.toggleSyncMod
Definition at line 9 of file ContentConfigOther.cs.
Referenced by OnInstantiate().
toggleTest
UIButton ContentConfigOther.toggleTest
Definition at line 17 of file ContentConfigOther.cs.
Referenced by OnInstantiate().
The documentation for this class was generated from the following file:
Elin/ContentConfigOther.cs