Elin Decompiled Documentation: Mosframe.DynamicScrollView Class Reference
Mosframe.DynamicScrollView Class Reference
Public Types
enum Direction { Vertical , Horizontal }
Public Member Functions
void scrollToLastPos ()
void scrollByItemIndex (int itemIndex)
void refresh ()
void Build ()
void Update ()
void OnResize ()
void resizeContent ()
virtual void init ()
Public Attributes
int totalItemCount
RectTransform itemPrototype
UIDynamicList dynamicList
LinkedList< DSVRow > containers = new LinkedList<DSVRow>()
int prevTotalItemCount = -1
RectTransform contentRect
Protected Member Functions
override void Awake ()
virtual void clear ()
Protected Attributes
Direction direction
float prevAnchoredPosition
int nextInsertItemNo
ScrollRect scrollRect
RectTransform viewportRect
Properties
abstract float contentAnchoredPosition [get, set]
abstract float contentSize [get]
abstract float viewportSize [get]
abstract float itemSize [get]
Private Member Functions
void updateItem (int index, DSVRow itemObj)
Detailed Description
Definition at line 10 of file DynamicScrollView.cs.
Member Enumeration Documentation
Direction
enum Mosframe.DynamicScrollView.Direction
Enumerator
Vertical
Horizontal
Definition at line 12 of file DynamicScrollView.cs.
    {
        Vertical,
        Horizontal
    }
Member Function Documentation
Awake()
override void Mosframe.DynamicScrollView.Awake () inline protected
Definition at line 84 of file DynamicScrollView.cs.
    {
        base.Awake();
        scrollRect = GetComponent<ScrollRect>();
        viewportRect = scrollRect.viewport;
        contentRect = scrollRect.content;
        contentRect.anchoredPosition = Vector2.zero;
        prevTotalItemCount = totalItemCount;
    }
References Mosframe.DynamicScrollView.contentRect, Mosframe.DynamicScrollView.prevTotalItemCount, Mosframe.DynamicScrollView.scrollRect, Mosframe.DynamicScrollView.totalItemCount, and Mosframe.DynamicScrollView.viewportRect.
Build()
void Mosframe.DynamicScrollView.Build () inline
Definition at line 94 of file DynamicScrollView.cs.
    {
        itemPrototype.gameObject.SetActive(value: false);
        int num = (int)(viewportSize / itemSize) + 3;
        for (int i = containers.Count; i < num; i++)
        {
            RectTransform rectTransform = UnityEngine.Object.Instantiate(itemPrototype);
            rectTransform.SetParent(contentRect, worldPositionStays: false);
            rectTransform.name = i.ToString();
            rectTransform.anchoredPosition = ((direction == Direction.Vertical) ? new Vector2(0f, (0f - itemSize) * (float)i) : new Vector2(itemSize * (float)i, 0f));
            DSVRow component = rectTransform.GetComponent<DSVRow>();
            containers.AddLast(component);
            rectTransform.gameObject.SetActive(value: true);
            updateItem(i, component);
        }
        resizeContent();
    }
References Mosframe.DynamicScrollView.containers, Mosframe.DynamicScrollView.contentRect, Mosframe.DynamicScrollView.direction, Mosframe.DynamicScrollView.itemPrototype, Mosframe.DynamicScrollView.itemSize, Mosframe.DynamicScrollView.resizeContent(), Mosframe.DynamicScrollView.updateItem(), and Mosframe.DynamicScrollView.viewportSize.
Referenced by Mosframe.DynamicScrollView.OnResize(), UIDynamicList.Refresh(), and Mosframe.DynamicScrollView.Update().
clear()
virtual void Mosframe.DynamicScrollView.clear () inline protected virtual
Definition at line 272 of file DynamicScrollView.cs.
    {
        while (base.transform.childCount > 0)
        {
            UnityEngine.Object.DestroyImmediate(base.transform.GetChild(0).gameObject);
        }
    }
Referenced by Mosframe.DynamicScrollView.init().
init()
virtual void Mosframe.DynamicScrollView.init () inline virtual
Reimplemented in Mosframe.DynamicHScrollView, and Mosframe.DynamicVScrollView.
Definition at line 200 of file DynamicScrollView.cs.
    {
        clear();
        GetComponent<RectTransform>().setFullSize();
        ScrollRect component = GetComponent<ScrollRect>();
        component.horizontal = direction == Direction.Horizontal;
        component.vertical = direction == Direction.Vertical;
        component.scrollSensitivity = 15f;
        RectTransform component2 = new GameObject("Viewport", typeof(RectTransform), typeof(Mask), typeof(Image)).GetComponent<RectTransform>();
        component2.SetParent(component.transform, worldPositionStays: false);
        component2.setFullSize();
        component2.offsetMin = new Vector2(10f, 10f);
        component2.offsetMax = new Vector2(-10f, -10f);
        component2.GetComponent<Image>().type = Image.Type.Sliced;
        component2.GetComponent<Mask>().showMaskGraphic = false;
        component.viewport = component2;
        RectTransform component3 = new GameObject("Content", typeof(RectTransform)).GetComponent<RectTransform>();
        component3.SetParent(component2, worldPositionStays: false);
        if (direction == Direction.Horizontal)
        {
            component3.setSizeFromLeft(1f);
        }
        else
        {
            component3.setSizeFromTop(1f);
        }
        Vector2 size = component3.getSize();
        component3.setSize(size - size * 0.06f);
        component.content = component3;
        RectTransform component4 = new GameObject((direction == Direction.Horizontal) ? "Scrollbar Horizontal" : "Scrollbar Vertical", typeof(Scrollbar), typeof(Image)).GetComponent<RectTransform>();
        component4.SetParent(component2, worldPositionStays: false);
        if (direction == Direction.Horizontal)
        {
            component4.setSizeFromBottom(0.05f);
        }
        else
        {
            component4.setSizeFromRight(0.05f);
        }
        component4.SetParent(component.transform, worldPositionStays: true);
        Scrollbar component5 = component4.GetComponent<Scrollbar>();
        component5.direction = ((direction != Direction.Horizontal) ? Scrollbar.Direction.BottomToTop : Scrollbar.Direction.LeftToRight);
        if (direction == Direction.Horizontal)
        {
            component.horizontalScrollbar = component5;
        }
        else
        {
            component.verticalScrollbar = component5;
        }
        Image component6 = component4.GetComponent<Image>();
        component6.color = new Color(0.1f, 0.1f, 0.1f, 0.5f);
        component6.type = Image.Type.Sliced;
        RectTransform component7 = new GameObject("Sliding Area", typeof(RectTransform)).GetComponent<RectTransform>();
        component7.SetParent(component4, worldPositionStays: false);
        component7.setFullSize();
        RectTransform component8 = new GameObject("Handle", typeof(Image)).GetComponent<RectTransform>();
        component8.SetParent(component7, worldPositionStays: false);
        component8.setFullSize();
        Image component9 = component8.GetComponent<Image>();
        component9.color = new Color(0.5f, 0.5f, 1f, 0.5f);
        component9.type = Image.Type.Sliced;
        component5.handleRect = component8;
        if (component.GetComponent<ScrollbarHandleSize>() == null)
        {
            ScrollbarHandleSize scrollbarHandleSize = component.gameObject.AddComponent<ScrollbarHandleSize>();
            scrollbarHandleSize.maxSize = 1f;
            scrollbarHandleSize.minSize = 0.1f;
        }
        base.gameObject.setLayer(base.transform.parent.gameObject.layer);
    }
References Mosframe.DynamicScrollView.clear(), Color, and Mosframe.DynamicScrollView.direction.
OnResize()
void Mosframe.DynamicScrollView.OnResize () inline
Definition at line 165 of file DynamicScrollView.cs.
    {
        Build();
        base.transform.parent.parent.parent.RebuildLayout();
        refresh();
        Update();
        GetComponent<UIScrollView>().Refresh();
    }
References Mosframe.DynamicScrollView.Build(), Mosframe.DynamicScrollView.refresh(), and Mosframe.DynamicScrollView.Update().
Referenced by UIDynamicList.OnResizeWindow().
refresh()
void Mosframe.DynamicScrollView.refresh () inline
Definition at line 63 of file DynamicScrollView.cs.
    {
        int num = 0;
        if (contentAnchoredPosition != 0f)
        {
            num = (int)((0f - contentAnchoredPosition) / itemSize);
        }
        foreach (DSVRow container in containers)
        {
            if (!(container == null) && !(container.Rect() == null))
            {
                float num2 = itemSize * (float)num;
                container.Rect().anchoredPosition = ((direction == Direction.Vertical) ? new Vector2(0f, 0f - num2) : new Vector2(num2, 0f));
                updateItem(num, container);
                num++;
            }
        }
        nextInsertItemNo = num - containers.Count;
        prevAnchoredPosition = (float)(int)(contentAnchoredPosition / itemSize) * itemSize;
    }
References Mosframe.DynamicScrollView.containers, Mosframe.DynamicScrollView.contentAnchoredPosition, Mosframe.DynamicScrollView.direction, Mosframe.DynamicScrollView.itemSize, Mosframe.DynamicScrollView.nextInsertItemNo, Mosframe.DynamicScrollView.prevAnchoredPosition, and Mosframe.DynamicScrollView.updateItem().
Referenced by Mosframe.DynamicScrollView.OnResize(), UIDynamicList.Scroll(), Mosframe.DynamicScrollView.scrollByItemIndex(), Mosframe.DynamicScrollView.scrollToLastPos(), and Mosframe.DynamicScrollView.Update().
resizeContent()
void Mosframe.DynamicScrollView.resizeContent () inline
Definition at line 174 of file DynamicScrollView.cs.
    {
        Vector2 size = contentRect.getSize();
        if (direction == Direction.Vertical)
        {
            size.y = itemSize * (float)totalItemCount;
        }
        else
        {
            size.x = itemSize * (float)totalItemCount;
        }
        contentRect.setSize(size);
    }
References Mosframe.DynamicScrollView.contentRect, Mosframe.DynamicScrollView.direction, Mosframe.DynamicScrollView.itemSize, and Mosframe.DynamicScrollView.totalItemCount.
Referenced by Mosframe.DynamicScrollView.Build(), and Mosframe.DynamicScrollView.Update().
scrollByItemIndex()
void Mosframe.DynamicScrollView.scrollByItemIndex (int itemIndex) inline
Definition at line 55 of file DynamicScrollView.cs.
    {
        float num = contentSize / (float)totalItemCount * (float)itemIndex;
        contentAnchoredPosition = 0f - num;
        Update();
        refresh();
    }
References Mosframe.DynamicScrollView.contentAnchoredPosition, Mosframe.DynamicScrollView.contentSize, Mosframe.DynamicScrollView.refresh(), Mosframe.DynamicScrollView.totalItemCount, and Mosframe.DynamicScrollView.Update().
Referenced by UIDynamicList.Scroll().
scrollToLastPos()
void Mosframe.DynamicScrollView.scrollToLastPos () inline
Definition at line 49 of file DynamicScrollView.cs.
    {
        contentAnchoredPosition = viewportSize - contentSize;
        refresh();
    }
References Mosframe.DynamicScrollView.contentAnchoredPosition, Mosframe.DynamicScrollView.contentSize, Mosframe.DynamicScrollView.refresh(), and Mosframe.DynamicScrollView.viewportSize.
Update()
void Mosframe.DynamicScrollView.Update () inline
Definition at line 112 of file DynamicScrollView.cs.
    {
        Build();
        if (totalItemCount != prevTotalItemCount)
        {
            prevTotalItemCount = totalItemCount;
            bool flag = false;
            if (viewportSize - contentAnchoredPosition >= contentSize - itemSize * 0.5f && contentAnchoredPosition != 0f)
            {
                flag = true;
            }
            resizeContent();
            if (flag)
            {
                contentAnchoredPosition = viewportSize - contentSize;
            }
            refresh();
        }
        while (contentAnchoredPosition - prevAnchoredPosition < (0f - itemSize) * 2f)
        {
            prevAnchoredPosition -= itemSize;
            LinkedListNode<DSVRow> first = containers.First;
            if (first == null)
            {
                break;
            }
            DSVRow value = first.Value;
            containers.RemoveFirst();
            containers.AddLast(value);
            float num = itemSize * (float)(containers.Count + nextInsertItemNo);
            value.Rect().anchoredPosition = ((direction == Direction.Vertical) ? new Vector2(0f, 0f - num) : new Vector2(num, 0f));
            updateItem(containers.Count + nextInsertItemNo, value);
            nextInsertItemNo++;
        }
        while (contentAnchoredPosition - prevAnchoredPosition > 0f)
        {
            prevAnchoredPosition += itemSize;
            LinkedListNode<DSVRow> last = containers.Last;
            if (last != null)
            {
                DSVRow value2 = last.Value;
                containers.RemoveLast();
                containers.AddFirst(value2);
                nextInsertItemNo--;
                float num2 = itemSize * (float)nextInsertItemNo;
                value2.Rect().anchoredPosition = ((direction == Direction.Vertical) ? new Vector2(0f, 0f - num2) : new Vector2(num2, 0f));
                updateItem(nextInsertItemNo, value2);
                continue;
            }
            break;
        }
    }
References Mosframe.DynamicScrollView.Build(), Mosframe.DynamicScrollView.containers, Mosframe.DynamicScrollView.contentAnchoredPosition, Mosframe.DynamicScrollView.contentSize, Mosframe.DynamicScrollView.direction, Mosframe.DynamicScrollView.itemSize, Mosframe.DynamicScrollView.nextInsertItemNo, Mosframe.DynamicScrollView.prevAnchoredPosition, Mosframe.DynamicScrollView.prevTotalItemCount, Mosframe.DynamicScrollView.refresh(), Mosframe.DynamicScrollView.resizeContent(), Mosframe.DynamicScrollView.totalItemCount, Mosframe.DynamicScrollView.updateItem(), and Mosframe.DynamicScrollView.viewportSize.
Referenced by Mosframe.DynamicScrollView.OnResize(), UIDynamicList.Refresh(), and Mosframe.DynamicScrollView.scrollByItemIndex().
updateItem()
void Mosframe.DynamicScrollView.updateItem (int index, DSVRow itemObj) inline private
Definition at line 188 of file DynamicScrollView.cs.
    {
        if (index < 0 || index >= totalItemCount)
        {
            itemObj.SetActive(enable: false);
            return;
        }
        itemObj.SetActive(enable: true);
        dynamicList.UpdateRow(itemObj, index);
    }
References Mosframe.DynamicScrollView.dynamicList, Mosframe.DynamicScrollView.totalItemCount, and UIDynamicList.UpdateRow().
Referenced by Mosframe.DynamicScrollView.Build(), Mosframe.DynamicScrollView.refresh(), and Mosframe.DynamicScrollView.Update().
Member Data Documentation
containers
LinkedList<DSVRow> Mosframe.DynamicScrollView.containers = new LinkedList<DSVRow>()
Definition at line 26 of file DynamicScrollView.cs.
Referenced by Mosframe.DynamicScrollView.Build(), UIDynamicList.GetComp< T >(), Mosframe.DynamicScrollView.refresh(), UIDynamicList.RefreshHighlight(), UIDynamicList.Select< T >(), and Mosframe.DynamicScrollView.Update().
contentRect
RectTransform Mosframe.DynamicScrollView.contentRect
Definition at line 39 of file DynamicScrollView.cs.
Referenced by Mosframe.DynamicScrollView.Awake(), Mosframe.DynamicScrollView.Build(), and Mosframe.DynamicScrollView.resizeContent().
direction
Direction Mosframe.DynamicScrollView.direction protected
Definition at line 24 of file DynamicScrollView.cs.
Referenced by Mosframe.DynamicHScrollView.Awake(), Mosframe.DynamicVScrollView.Awake(), Mosframe.DynamicScrollView.Build(), Mosframe.DynamicHScrollView.init(), Mosframe.DynamicScrollView.init(), Mosframe.DynamicVScrollView.init(), Mosframe.DynamicScrollView.refresh(), Mosframe.DynamicScrollView.resizeContent(), and Mosframe.DynamicScrollView.Update().
dynamicList
UIDynamicList Mosframe.DynamicScrollView.dynamicList
Definition at line 22 of file DynamicScrollView.cs.
Referenced by Mosframe.DynamicScrollView.updateItem().
itemPrototype
RectTransform Mosframe.DynamicScrollView.itemPrototype
Definition at line 20 of file DynamicScrollView.cs.
Referenced by UIDynamicList._Add(), Mosframe.DynamicScrollView.Build(), and UIDynamicList.OnResizeWindow().
nextInsertItemNo
int Mosframe.DynamicScrollView.nextInsertItemNo protected
Definition at line 30 of file DynamicScrollView.cs.
Referenced by Mosframe.DynamicScrollView.refresh(), and Mosframe.DynamicScrollView.Update().
prevAnchoredPosition
float Mosframe.DynamicScrollView.prevAnchoredPosition protected
Definition at line 28 of file DynamicScrollView.cs.
Referenced by Mosframe.DynamicScrollView.refresh(), and Mosframe.DynamicScrollView.Update().
prevTotalItemCount
int Mosframe.DynamicScrollView.prevTotalItemCount = -1
Definition at line 33 of file DynamicScrollView.cs.
Referenced by Mosframe.DynamicScrollView.Awake(), and Mosframe.DynamicScrollView.Update().
scrollRect
ScrollRect Mosframe.DynamicScrollView.scrollRect protected
Definition at line 35 of file DynamicScrollView.cs.
Referenced by Mosframe.DynamicScrollView.Awake().
totalItemCount
int Mosframe.DynamicScrollView.totalItemCount
Definition at line 18 of file DynamicScrollView.cs.
Referenced by Mosframe.DynamicScrollView.Awake(), Mosframe.DynamicScrollView.resizeContent(), Mosframe.DynamicScrollView.scrollByItemIndex(), Mosframe.DynamicScrollView.Update(), and Mosframe.DynamicScrollView.updateItem().
viewportRect
RectTransform Mosframe.DynamicScrollView.viewportRect protected
Definition at line 37 of file DynamicScrollView.cs.
Referenced by Mosframe.DynamicScrollView.Awake().
Property Documentation
contentAnchoredPosition
abstract float Mosframe.DynamicScrollView.contentAnchoredPosition get set
Definition at line 41 of file DynamicScrollView.cs.
{ get; set; }
Referenced by Mosframe.DynamicScrollView.refresh(), Mosframe.DynamicScrollView.scrollByItemIndex(), Mosframe.DynamicScrollView.scrollToLastPos(), and Mosframe.DynamicScrollView.Update().
contentSize
abstract float Mosframe.DynamicScrollView.contentSize get
Definition at line 43 of file DynamicScrollView.cs.
{ get; }
Referenced by Mosframe.DynamicScrollView.scrollByItemIndex(), Mosframe.DynamicScrollView.scrollToLastPos(), and Mosframe.DynamicScrollView.Update().
itemSize
abstract float Mosframe.DynamicScrollView.itemSize get protected
Definition at line 47 of file DynamicScrollView.cs.
{ get; }
Referenced by Mosframe.DynamicScrollView.Build(), Mosframe.DynamicScrollView.refresh(), Mosframe.DynamicScrollView.resizeContent(), and Mosframe.DynamicScrollView.Update().
viewportSize
abstract float Mosframe.DynamicScrollView.viewportSize get
Definition at line 45 of file DynamicScrollView.cs.
{ get; }
Referenced by Mosframe.DynamicScrollView.Build(), Mosframe.DynamicScrollView.scrollToLastPos(), and Mosframe.DynamicScrollView.Update().
The documentation for this class was generated from the following file:
Elin/Plugins.UI/Mosframe/DynamicScrollView.cs