Elin Decompiled Documentation: SelectedColorController Class Reference
SelectedColorController Class Reference
Public Member Functions
void Select (Color rgba)
void Select (HSVColor hsv)
Properties
Color RGBA [get, set]
HSVColor HSV [get, set]
Private Member Functions
void SetupComponents (Color rgba)
Private Attributes
Image colorImage
Color rgba
HSVColor hsv
Slider slider
Detailed Description
Definition at line 5 of file SelectedColorController.cs.
Member Function Documentation
Select() [1/2]
void SelectedColorController.Select (Color rgba) inline
Definition at line 43 of file SelectedColorController.cs.
    {
        this.rgba = rgba;
        hsv = Colorist.RGBtoHSV(rgba);
        SetupComponents(rgba);
    }
References hsv, rgba, Empyrean.Utils.Colorist.RGBtoHSV(), and SetupComponents().
Referenced by Empyrean.ColorPicker.ColorPicker.OnColorPickedFromPalette(), Empyrean.ColorPicker.ColorPicker.SelectColor(), and Empyrean.ColorPicker.ColorPicker.UpdateColor().
Select() [2/2]
void SelectedColorController.Select (HSVColor hsv) inline
Definition at line 50 of file SelectedColorController.cs.
    {
        rgba = Colorist.HSVtoRGB(hsv);
        this.hsv = hsv;
        SetupComponents(rgba);
    }
References hsv, Empyrean.Utils.Colorist.HSVtoRGB(), rgba, and SetupComponents().
SetupComponents()
void SelectedColorController.SetupComponents (Color rgba) inline private
Definition at line 57 of file SelectedColorController.cs.
    {
        slider.value = rgba.a;
        colorImage.color = new Color(rgba.r, rgba.g, rgba.b, 1f);
    }
References Color, and rgba.
Referenced by Select().
Member Data Documentation
colorImage
Image SelectedColorController.colorImage private
Definition at line 8 of file SelectedColorController.cs.
hsv
HSVColor SelectedColorController.hsv private
Definition at line 14 of file SelectedColorController.cs.
Referenced by Select().
rgba
Color SelectedColorController.rgba private
Definition at line 11 of file SelectedColorController.cs.
Referenced by Select(), and SetupComponents().
slider
Slider SelectedColorController.slider private
Definition at line 17 of file SelectedColorController.cs.
Property Documentation
HSV
HSVColor SelectedColorController.HSV get set
Definition at line 31 of file SelectedColorController.cs.
    {
        get
        {
            return hsv;
        }
        set
        {
            Select(value);
        }
    }
Referenced by Empyrean.ColorPicker.ColorPicker.UpdateColorPicker(), and Empyrean.ColorPicker.ColorPicker.UpdateSlidersValues().
RGBA
Color SelectedColorController.RGBA get set
Definition at line 19 of file SelectedColorController.cs.
    {
        get
        {
            return rgba;
        }
        set
        {
            Select(value);
        }
    }
Referenced by Empyrean.ColorPicker.ColorPicker.StartDropper(), Empyrean.ColorPicker.ColorPicker.UpdateColorPicker(), and Empyrean.ColorPicker.ColorPicker.UpdateSlidersValues().
The documentation for this class was generated from the following file:
Elin/Plugins.UI/SelectedColorController.cs