Elin Decompiled Documentation: Dice Class Reference
Dice Class Reference
Public Member Functions
Dice (int _num=0, int _sides=0, int _bonus=0, Card _card=null)
int Roll ()
int RollMax ()
override string ToString ()
Static Public Member Functions
static int Roll_Normal (long num, long sides, int bonus=0)
static int Roll_Precise (int num, int sides, int bonus=0)
static int Roll (int num, int sides, int bonus=0, Card card=null)
static int RollMax (int num, int sides, int bonus=0)
static int rnd (int a)
static Dice Parse (string raw)
static Dice Create (Element ele, Card c)
static Dice Create (string id, int power, Card c=null, Act act=null)
Public Attributes
int num
int sides
int bonus
Card card
Static Public Attributes
static Dice Null = new Dice()
Properties
static int MaxValue [get]
Detailed Description
Definition at line 4 of file Dice.cs.
Constructor & Destructor Documentation
Dice()
Dice.Dice (int _num = 0, int _sides = 0, int _bonus = 0, Card _card = null) inline
Definition at line 80 of file Dice.cs.
    {
        num = _num;
        sides = _sides;
        bonus = _bonus;
        card = _card;
    }
References bonus, card, num, and sides.
Member Function Documentation
Create() [1/2]
static Dice Dice.Create (Element ele, Card c) inline static
Definition at line 120 of file Dice.cs.
    {
        string key = ele.source.alias;
        if (!EClass.sources.calc.map.ContainsKey(key) && !ele.source.aliasRef.IsEmpty())
        {
            key = ele.source.alias.Split('_')[0] + "_";
        }
        if (!EClass.sources.calc.map.ContainsKey(key))
        {
            return null;
        }
        SourceCalc.Row row = EClass.sources.calc.map[key];
        int power = ele.GetPower(c);
        int ele2 = ((!ele.source.aliasParent.IsEmpty()) ? c.Evalue(ele.source.aliasParent) : 0);
        try
        {
            return new Dice(Mathf.Max(1, row.num.Calc(power, ele2)), Mathf.Max(1, row.sides.Calc(power, ele2)), row.bonus.Calc(power, ele2), c);
        }
        catch
        {
            Debug.Log(ele.id);
            return new Dice();
        }
    }
References SourceCalc.Row.bonus, SourceManager.calc, Debug, Card.Evalue(), Element.GetPower(), Element.id, SourceCalc.Row.num, SourceCalc.Row.sides, Element.source, and EClass.sources.
Referenced by Element._WriteNote(), ActEffect.DamageEle(), ConHOT.OnWriteNote(), ConMiasma.OnWriteNote(), ActEffect.Proc(), ConHOT.Tick(), and ConMiasma.Tick().
Create() [2/2]
static Dice Dice.Create (string id, int power, Card c = null, Act act = null) inline static
Definition at line 145 of file Dice.cs.
    {
        if (!EClass.sources.calc.map.ContainsKey(id))
        {
            Debug.Log(id);
            return null;
        }
        SourceCalc.Row row = EClass.sources.calc.map[id];
        int power2 = power;
        int ele = power / 10;
        if (act != null)
        {
            Element orCreateElement = c.elements.GetOrCreateElement(act.source.id);
            power2 = orCreateElement.GetPower(c);
            ele = ((!orCreateElement.source.aliasParent.IsEmpty()) ? c.Evalue(orCreateElement.source.aliasParent) : 0);
        }
        try
        {
            return new Dice(Mathf.Max(1, row.num.Calc(power2, ele)), Mathf.Max(1, row.sides.Calc(power2, ele)), row.bonus.Calc(power2, ele), c);
        }
        catch
        {
            return new Dice();
        }
    }
References SourceCalc.Row.bonus, SourceManager.calc, Debug, Element.GetPower(), SourceCalc.Row.num, SourceCalc.Row.sides, Element.source, and EClass.sources.
Parse()
static Dice Dice.Parse (string raw) inline static
Definition at line 88 of file Dice.cs.
    {
        Dice dice = new Dice();
        string[] array = raw.Split(',');
        if (array.Length != 0)
        {
            string[] array2 = array[0].Split('d');
            dice.num = int.Parse(array2[0]);
            dice.sides = int.Parse(array2[1]);
        }
        if (array.Length > 1)
        {
            dice.bonus = int.Parse(array[1]);
        }
        return dice;
    }
rnd()
static int Dice.rnd (int a) inline static
Definition at line 75 of file Dice.cs.
    {
        return Rand.Range(0, a);
    }
References Rand.Range().
Referenced by Roll(), Roll_Normal(), and Roll_Precise().
Roll() [1/2]
int Dice.Roll () inline
Definition at line 105 of file Dice.cs.
    {
        return Roll(num, sides, bonus, card);
    }
References bonus, card, num, Roll(), and sides.
Referenced by Roll().
Roll() [2/2]
static int Dice.Roll (int num, int sides, int bonus = 0, Card card = null) inline static
Definition at line 48 of file Dice.cs.
    {
        int a = 1;
        bool flag = true;
        int num2 = 0;
        if (card != null)
        {
            int num3 = card.Evalue(78);
            flag = num3 >= 0;
            a = 1 + Mathf.Abs(num3 / 100) + ((Mathf.Abs(num3 % 100) > rnd(100)) ? 1 : 0);
        }
        for (int i = 0; i < Mathf.Min(a, 20); i++)
        {
            int num4 = ((num >= 10) ? Roll_Normal(num, sides, bonus) : Roll_Precise(num, sides, bonus));
            if (i == 0 || (flag && num4 > num2) || (!flag && num4 < num2))
            {
                num2 = num4;
            }
        }
        return num2;
    }
References bonus, card, Card.Evalue(), num, rnd(), Roll_Normal(), Roll_Precise(), and sides.
Referenced by Card.ApplyProtection(), ActEffect.DamageEle(), AttackProcess.GetRawDamage(), Check.Perform(), ActEffect.Proc(), ConHOT.Tick(), and ConMiasma.Tick().
Roll_Normal()
static int Dice.Roll_Normal (long num, long sides, int bonus = 0) inline static
Definition at line 18 of file Dice.cs.
    {
        double num2 = (double)(num * (sides + 1)) / 2.0;
        double num3 = Math.Sqrt((double)(num * (sides * sides - 1)) / 12.0);
        double d = (double)(rnd(1000000) + 1) / 1000001.0;
        double num4 = (double)(rnd(1000000) + 1) / 1000001.0;
        double num5 = Math.Sqrt(-2.0 * Math.Log(d)) * Math.Cos(Math.PI * 2.0 * num4);
        long num6 = (long)Math.Floor(num2 + num3 * num5 + 0.5);
        long num7 = num * sides;
        if (num6 < num)
        {
            num6 = num;
        }
        if (num6 > num7)
        {
            num6 = num7;
        }
        return (int)Mathf.Clamp(num6 + bonus, -MaxValue, MaxValue);
    }
References bonus, MaxValue, num, rnd(), and sides.
Referenced by Roll().
Roll_Precise()
static int Dice.Roll_Precise (int num, int sides, int bonus = 0) inline static
Definition at line 38 of file Dice.cs.
    {
        long num2 = 0L;
        for (int i = 0; i < num; i++)
        {
            num2 += rnd(sides) + 1;
        }
        return (int)Mathf.Clamp(num2 + bonus, -MaxValue, MaxValue);
    }
References bonus, MaxValue, num, rnd(), and sides.
Referenced by Roll().
RollMax() [1/2]
int Dice.RollMax () inline
Definition at line 110 of file Dice.cs.
    {
        return RollMax(num, sides, bonus);
    }
References bonus, num, RollMax(), and sides.
Referenced by RollMax().
RollMax() [2/2]
static int Dice.RollMax (int num, int sides, int bonus = 0) inline static
Definition at line 70 of file Dice.cs.
    {
        return (int)Mathf.Clamp((long)num * (long)sides + bonus, -MaxValue, MaxValue);
    }
References bonus, MaxValue, num, and sides.
Referenced by ActEffect.DamageEle(), and AttackProcess.GetRawDamage().
ToString()
override string Dice.ToString () inline
Definition at line 115 of file Dice.cs.
    {
        return num + "d" + sides + ((bonus > 0) ? ("+" + bonus) : ((bonus < 0) ? (bonus.ToString() ?? "") : ""));
    }
References bonus, num, and sides.
Referenced by Element._WriteNote(), ConHOT.OnWriteNote(), and ConMiasma.OnWriteNote().
Member Data Documentation
bonus
int Dice.bonus
Definition at line 12 of file Dice.cs.
Referenced by Dice(), Roll(), Roll_Normal(), Roll_Precise(), RollMax(), and ToString().
card
Card Dice.card
Definition at line 14 of file Dice.cs.
Referenced by Dice(), and Roll().
Null
Dice Dice.Null = new Dice() static
Definition at line 6 of file Dice.cs.
num
int Dice.num
Definition at line 8 of file Dice.cs.
Referenced by Dice(), Roll(), Roll_Normal(), Roll_Precise(), RollMax(), and ToString().
sides
int Dice.sides
Definition at line 10 of file Dice.cs.
Referenced by Dice(), Roll(), Roll_Normal(), Roll_Precise(), RollMax(), and ToString().
Property Documentation
MaxValue
int Dice.MaxValue static get
Definition at line 16 of file Dice.cs.
Referenced by Roll_Normal(), Roll_Precise(), and RollMax().
The documentation for this class was generated from the following file:
Elin/Dice.cs