Elin Decompiled Documentation: ZonePreEnterDigStairs Class Reference
ZonePreEnterDigStairs Class Reference
Public Member Functions
override void Execute ()
virtual void Execute ()
Public Attributes
Point pos
bool fromAbove
int uidZone
Additional Inherited Members
Static Public Member Functions inherited from EClass
static int rnd (int a)
static int curve (int a, int start, int step, int rate=75)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Static Public Attributes inherited from EClass
static Core core
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Detailed Description
Definition at line 3 of file ZonePreEnterDigStairs.cs.
Member Function Documentation
Execute()
override void ZonePreEnterDigStairs.Execute () inline virtual
Reimplemented from ZonePreEnterEvent.
Definition at line 14 of file ZonePreEnterDigStairs.cs.
    {
        if (pos.HasBlock)
        {
            pos.SetBlock();
        }
        if (pos.HasObj)
        {
            pos.SetObj();
        }
        Trait trait = null;
        foreach (Thing thing2 in pos.Things)
        {
            if (thing2.trait is TraitStairsLocked)
            {
                trait = thing2.trait;
                break;
            }
            if (thing2.trait is TraitNewZone traitNewZone && ((fromAbove && traitNewZone.IsUpstairs) || (!fromAbove && traitNewZone.IsDownstairs)))
            {
                trait = traitNewZone;
                break;
            }
        }
        if (trait != null)
        {
            return;
        }
        if (EClass._zone.IsSkyLevel)
        {
            for (int i = pos.z - 1; i < pos.z + 2; i++)
            {
                for (int j = pos.x - 1; j < pos.x + 2; j++)
                {
                    Point point = new Point(j, i);
                    if (point.IsValid && point.sourceFloor.tileType == TileType.Sky)
                    {
                        EClass._map.SetFloor(point.x, point.z, EClass._zone.biome.interior.floor.mat, EClass._zone.biome.interior.floor.id);
                    }
                }
            }
        }
        Thing thing = ThingGen.Create(EClass._zone.biome.style.GetIdStairs(fromAbove));
        EClass._zone.AddCard(thing, pos.x, pos.z);
        thing.c_uidZone = uidZone;
        thing.SetPlaceState(PlaceState.installed);
        thing.isPlayerCreation = true;
    }
References EClass._map, EClass._zone, Zone.AddCard(), Zone.biome, ThingGen.Create(), BiomeProfile.TileGroup.floor, fromAbove, BiomeProfile.Style.GetIdStairs(), Point.HasBlock, Point.HasObj, BiomeProfile.Tile.id, BiomeProfile.interior, Zone.IsSkyLevel, Point.IsValid, BiomeProfile.Tile.mat, pos, Point.SetBlock(), Map.SetFloor(), Point.SetObj(), Card.SetPlaceState(), TileType.Sky, Point.sourceFloor, BiomeProfile.style, Point.Things, Card.trait, uidZone, Point.x, and Point.z.
Member Data Documentation
fromAbove
bool ZonePreEnterDigStairs.fromAbove
Definition at line 9 of file ZonePreEnterDigStairs.cs.
Referenced by Execute().
pos
Point ZonePreEnterDigStairs.pos
Definition at line 6 of file ZonePreEnterDigStairs.cs.
Referenced by Execute().
uidZone
int ZonePreEnterDigStairs.uidZone
Definition at line 12 of file ZonePreEnterDigStairs.cs.
Referenced by Execute().
The documentation for this class was generated from the following file:
Elin/ZonePreEnterDigStairs.cs