Elin Decompiled Documentation: ZoneEventManager Class Reference
ZoneEventManager Class Reference
Public Member Functions
void OnLoad (Zone _zone)
void Add< T > (bool allowDuplicate=false)
void Add (ZoneEvent e, bool allowDuplicate=false)
void AddPreEnter (ZonePreEnterEvent e, bool executeIfActiveZone=true)
T GetEvent< T > ()
void Remove< T > ()
void Remove (ZoneEvent e)
void Clear ()
void Tick (float delta)
void OnVisit ()
void OnLeaveZone ()
void OnCharaDie (Chara c)
void OnSimulateHour ()
Public Attributes
Zone zone
List< ZoneEvent > list = new List<ZoneEvent>()
List< ZonePreEnterEvent > listPreEnter = new List<ZonePreEnterEvent>()
Additional Inherited Members
Static Public Member Functions inherited from EClass
static int rndSeed (int a, int seed)
static int rnd (long a)
static int rnd (int a)
static int curve (int _a, int start, int step, int rate=75)
static int sqrt (int a)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Static Public Attributes inherited from EClass
static Core core
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Detailed Description
Definition at line 6 of file ZoneEventManager.cs.
Member Function Documentation
Add()
void ZoneEventManager.Add (ZoneEvent e, bool allowDuplicate = false) inline
Definition at line 31 of file ZoneEventManager.cs.
    {
        if (EClass.debug.skipEvent && e.debugSkip)
        {
            return;
        }
        if (!allowDuplicate)
        {
            foreach (ZoneEvent item in list)
            {
                if (e.GetType() == item.GetType())
                {
                    return;
                }
            }
        }
        list.Add(e);
        e.zone = zone;
        e.Init();
        Debug.Log("#game zone event " + e.GetType()?.ToString() + " added.");
    }
References EClass.debug, Debug, ZoneEvent.debugSkip, ZoneEvent.Init(), item, list, CoreDebug.skipEvent, and zone.
Referenced by Add< T >(), QuestInstance.CreateInstanceZone(), SurvivalManager.OnMineWreck(), TraitPhone.OnSimulateHour(), QuestFiamaLock.OnStart(), CoreDebug.Test_Siege(), CoreDebug.Test_SiegeGuard(), and TraitCoreDefense.TrySetAct().
Add< T >()
void ZoneEventManager.Add< T > (bool allowDuplicate = false) inline
Type Constraints
T : ZoneEvent
Definition at line 26 of file ZoneEventManager.cs.
                                                            : ZoneEvent
    {
        Add(Activator.CreateInstance<T>(), allowDuplicate);
    }
References Add().
AddPreEnter()
void ZoneEventManager.AddPreEnter (ZonePreEnterEvent e, bool executeIfActiveZone = true) inline
Definition at line 53 of file ZoneEventManager.cs.
    {
        if (zone.IsActiveZone && executeIfActiveZone)
        {
            e.Execute();
        }
        else
        {
            listPreEnter.Add(e);
        }
    }
References ZonePreEnterEvent.Execute(), Zone.IsActiveZone, listPreEnter, and zone.
Referenced by Player.EnterLocalZone(), and TraitNewZone.MoveZone().
Clear()
void ZoneEventManager.Clear () inline
Definition at line 93 of file ZoneEventManager.cs.
    {
        list.Clear();
    }
References list.
GetEvent< T >()
T ZoneEventManager.GetEvent< T > () inline
Type Constraints
T : ZoneEvent
Definition at line 65 of file ZoneEventManager.cs.
                                   : ZoneEvent
    {
        foreach (ZoneEvent item in list)
        {
            if (item is T)
            {
                return item as T;
            }
        }
        return null;
    }
References item, and list.
OnCharaDie()
void ZoneEventManager.OnCharaDie (Chara c) inline
Definition at line 122 of file ZoneEventManager.cs.
    {
        list.ForeachReverse(delegate(ZoneEvent e)
        {
            e.OnCharaDie(c);
        });
    }
References list, and ZoneEvent.OnCharaDie().
Referenced by Chara.Die().
OnLeaveZone()
void ZoneEventManager.OnLeaveZone () inline
Definition at line 114 of file ZoneEventManager.cs.
    {
        foreach (ZoneEvent item in list)
        {
            item.OnLeaveZone();
        }
    }
References item, and list.
OnLoad()
void ZoneEventManager.OnLoad (Zone _zone) inline
Definition at line 16 of file ZoneEventManager.cs.
    {
        zone = _zone;
        foreach (ZoneEvent item in list)
        {
            item.zone = zone;
            item.OnLoad();
        }
    }
References EClass._zone, item, list, and zone.
Referenced by Zone.OnLoad().
OnSimulateHour()
void ZoneEventManager.OnSimulateHour () inline
Definition at line 130 of file ZoneEventManager.cs.
    {
        if (list.Count == 0)
        {
            return;
        }
        foreach (ZoneEvent item in list.Copy())
        {
            item.OnSimulateHour();
        }
    }
References item, and list.
Referenced by Zone.OnSimulateHour().
OnVisit()
void ZoneEventManager.OnVisit () inline
Definition at line 106 of file ZoneEventManager.cs.
    {
        foreach (ZoneEvent item in list)
        {
            item.OnVisit();
        }
    }
References item, and list.
Referenced by Zone.OnVisit().
Remove()
void ZoneEventManager.Remove (ZoneEvent e) inline
Definition at line 88 of file ZoneEventManager.cs.
    {
        list.Remove(e);
    }
References list.
Referenced by CoreDebug.Test_Siege(), and CoreDebug.Test_SiegeGuard().
Remove< T >()
void ZoneEventManager.Remove< T > () inline
Type Constraints
T : ZoneEvent
Definition at line 77 of file ZoneEventManager.cs.
                                    : ZoneEvent
    {
        for (int num = list.Count - 1; num >= 0; num--)
        {
            if (list[num] is T)
            {
                list[num].Kill();
            }
        }
    }
References list.
Tick()
void ZoneEventManager.Tick (float delta) inline
Definition at line 98 of file ZoneEventManager.cs.
    {
        list.ForeachReverse(delegate(ZoneEvent e)
        {
            e.Tick(delta);
        });
    }
References list, and ZoneEvent.Tick().
Referenced by GameUpdater.Update().
Member Data Documentation
list
List<ZoneEvent> ZoneEventManager.list = new List<ZoneEvent>()
Definition at line 11 of file ZoneEventManager.cs.
Referenced by WidgetDate._Refresh(), Add(), GameDate.AdvanceMin(), Clear(), GetEvent< T >(), ZoneEvent.Kill(), OnCharaDie(), OnLeaveZone(), OnLoad(), OnSimulateHour(), OnVisit(), Zone.RefreshBGM(), UIHomeInfo.RefreshReport(), Remove(), Remove< T >(), Tick(), and WidgetDebug.UpdateText().
listPreEnter
List<ZonePreEnterEvent> ZoneEventManager.listPreEnter = new List<ZonePreEnterEvent>()
Definition at line 14 of file ZoneEventManager.cs.
Referenced by AddPreEnter().
zone
Zone ZoneEventManager.zone
Definition at line 8 of file ZoneEventManager.cs.
Referenced by Add(), AddPreEnter(), and OnLoad().
The documentation for this class was generated from the following file:
Elin/ZoneEventManager.cs