Elin Decompiled Documentation: Util Class Reference
Util Class Reference
Static Public Member Functions
static int Distance (int pX1, int pY1, int pX2, int pY2)
static T CopyComponent< T > (T original, GameObject destination)
static T Instantiate< T > (T t, Component parent=null)
static Transform Instantiate (string path, Component parent=null)
static T Instantiate< T > (string path, Component parent=null)
static void DestroyChildren (Transform trans)
static void RebuildLayoutInParents (Component c, Component root)
static void SetRectToFitScreen (RectTransform rect)
static void ClampToScreen (RectTransform rect, int margin=0)
static float GetAngle (Vector3 self, Vector3 target)
static float GetAngle (float x, float y)
static VectorDir GetVectorDir (Vector3 normal)
static Vector2 ConvertAxis (Vector2 v)
static Vector2 WorldToUIPos (Vector3 worldPoint, RectTransform container)
static T RandomEnum< T > ()
static List< T > EnumToList< T > ()
static void ShowExplorer (string itemPath, bool selectFirstFile=false)
static void Run (string itemPath)
static T[,] ResizeArray< T > (T[,] original, int x, int y, Func< int, int, T > func)
Static Public Attributes
static Color[] alphaMap
static Canvas canvas
Static Private Member Functions
static Util ()
Detailed Description
Definition at line 9 of file Util.cs.
Constructor & Destructor Documentation
Util()
static Util.Util () inline static private
Definition at line 15 of file Util.cs.
    {
        alphaMap = new Color[256];
        for (int i = 0; i < 256; i++)
        {
            alphaMap[i] = new Color(1f, 1f, 1f, 1f * (float)i / 255f);
        }
    }
References Color.
Member Function Documentation
ClampToScreen()
static void Util.ClampToScreen (RectTransform rect, int margin = 0) inline static
Definition at line 110 of file Util.cs.
    {
        RectTransform rectTransform = BaseCore.Instance.canvas.Rect();
        Vector3 localPosition = rect.localPosition;
        Vector3 vector = rectTransform.rect.min - rect.rect.min;
        Vector3 vector2 = rectTransform.rect.max - rect.rect.max;
        localPosition.x = Mathf.Clamp(localPosition.x, vector.x + (float)margin, vector2.x - (float)margin);
        localPosition.y = Mathf.Clamp(localPosition.y, vector.y + (float)margin, vector2.y - (float)margin);
        rect.localPosition = localPosition;
    }
References BaseCore.canvas, and BaseCore.Instance.
ConvertAxis()
static Vector2 Util.ConvertAxis (Vector2 v) inline static
Definition at line 157 of file Util.cs.
    {
        float x = v.x;
        float y = v.y;
        if (y == 1f)
        {
            if (x == 0f)
            {
                return new Vector2(-1f, 1f);
            }
            if (x == 1f)
            {
                return new Vector2(0f, 1f);
            }
            if (x == -1f)
            {
                return new Vector2(-1f, 0f);
            }
        }
        if (y == 0f)
        {
            if (x == 0f)
            {
                return Vector2.zero;
            }
            if (x == 1f)
            {
                return new Vector2(1f, 1f);
            }
            if (x == -1f)
            {
                return new Vector2(-1f, -1f);
            }
        }
        if (y == -1f)
        {
            if (x == 0f)
            {
                return new Vector2(1f, -1f);
            }
            if (x == 1f)
            {
                return new Vector2(1f, 0f);
            }
            if (x == -1f)
            {
                return new Vector2(0f, -1f);
            }
        }
        return Vector3.zero;
    }
CopyComponent< T >()
static T Util.CopyComponent< T > (T original, GameObject destination) inline static
Type Constraints
T : Component
Definition at line 29 of file Util.cs.
                                                                                 : Component
    {
        Type type = original.GetType();
        T val = destination.GetComponent(type) as T;
        if (!val)
        {
            val = destination.AddComponent(type) as T;
        }
        FieldInfo[] fields = type.GetFields();
        foreach (FieldInfo fieldInfo in fields)
        {
            if (!fieldInfo.IsStatic)
            {
                fieldInfo.SetValue(val, fieldInfo.GetValue(original));
            }
        }
        PropertyInfo[] properties = type.GetProperties();
        foreach (PropertyInfo propertyInfo in properties)
        {
            if (propertyInfo.CanWrite && propertyInfo.CanWrite && !(propertyInfo.Name == "name") && !(propertyInfo.Name == "usedByComposite") && !(propertyInfo.Name == "density"))
            {
                propertyInfo.SetValue(val, propertyInfo.GetValue(original, null), null);
            }
        }
        return val;
    }
DestroyChildren()
static void Util.DestroyChildren (Transform trans) inline static
Definition at line 82 of file Util.cs.
    {
        for (int num = trans.childCount - 1; num >= 0; num--)
        {
            UnityEngine.Object.Destroy(trans.GetChild(num).gameObject);
        }
    }
Distance()
static int Util.Distance (int pX1, int pY1, int pX2, int pY2) inline static
Definition at line 24 of file Util.cs.
    {
        return (int)Math.Sqrt((pX1 - pX2) * (pX1 - pX2) + (pY1 - pY2) * (pY1 - pY2));
    }
EnumToList< T >()
static List< T > Util.EnumToList< T > () inline static
Type Constraints
T : Enum
Definition at line 223 of file Util.cs.
                                                  : Enum
    {
        return Enum.GetValues(typeof(T)).Cast<T>().ToList();
    }
GetAngle() [1/2]
static float Util.GetAngle (float x, float y) inline static
Definition at line 127 of file Util.cs.
    {
        return Mathf.Atan2(0f - y, x) * 57.29578f + 90f;
    }
GetAngle() [2/2]
static float Util.GetAngle (Vector3 self, Vector3 target) inline static
Definition at line 121 of file Util.cs.
    {
        Vector3 vector = target - self;
        return Mathf.Atan2(vector.y * -1f, vector.x) * 57.29578f + 90f;
    }
GetVectorDir()
static VectorDir Util.GetVectorDir (Vector3 normal) inline static
Definition at line 132 of file Util.cs.
    {
        if (Math.Abs(normal.y - 1f) < 0.1f)
        {
            return VectorDir.down;
        }
        if (Math.Abs(normal.x - 1f) < 0.1f)
        {
            return VectorDir.left;
        }
        if (Math.Abs(normal.x - -1f) < 0.1f)
        {
            return VectorDir.right;
        }
        if (Math.Abs(normal.z - 1f) < 0.1f)
        {
            return VectorDir.back;
        }
        if (Math.Abs(normal.z - -1f) < 0.1f)
        {
            return VectorDir.forward;
        }
        return VectorDir.up;
    }
Instantiate()
static Transform Util.Instantiate (string path, Component parent = null) inline static
Definition at line 67 of file Util.cs.
    {
        return Instantiate<Transform>(path, parent);
    }
Referenced by Instantiate< T >().
Instantiate< T >() [1/2]
static T Util.Instantiate< T > (string path, Component parent = null) inline static
Type Constraints
T : Component
Definition at line 72 of file Util.cs.
                                                                                 : Component
    {
        T val = Resources.Load<T>(path);
        if (val == null)
        {
            return null;
        }
        return Instantiate(val, parent);
    }
References Instantiate().
Instantiate< T >() [2/2]
static T Util.Instantiate< T > (T t, Component parent = null) inline static
Type Constraints
T : Component
Definition at line 56 of file Util.cs.
                                                                         : Component
    {
        T val = UnityEngine.Object.Instantiate(t);
        val.transform.SetParent(parent ? parent.transform : null, worldPositionStays: false);
        if (!val.gameObject.activeSelf)
        {
            val.gameObject.SetActive(value: true);
        }
        return val;
    }
RandomEnum< T >()
static T Util.RandomEnum< T > () inline static
Definition at line 217 of file Util.cs.
    {
        Array values = Enum.GetValues(typeof(T));
        return (T)values.GetValue(new System.Random().Next(values.Length));
    }
RebuildLayoutInParents()
static void Util.RebuildLayoutInParents (Component c, Component root) inline static
Definition at line 90 of file Util.cs.
    {
        Transform transform = c.transform;
        transform.RebuildLayout();
        Transform parent = transform.parent;
        if ((bool)parent && !(parent == root.transform))
        {
            RebuildLayoutInParents(parent, root);
        }
    }
References RebuildLayoutInParents().
Referenced by RebuildLayoutInParents().
ResizeArray< T >()
static T[,] Util.ResizeArray< T > (T original[,], int x, int y, Func< int, int, T > func) inline static
Definition at line 247 of file Util.cs.
    {
        T[,] array = new T[x, y];
        int num = Math.Min(x, original.GetLength(0));
        int num2 = Math.Min(y, original.GetLength(1));
        for (int i = 0; i < x; i++)
        {
            for (int j = 0; j < y; j++)
            {
                if (i >= num || j >= num2)
                {
                    array[i, j] = func(i, j);
                }
                else
                {
                    array[i, j] = original[i, j];
                }
            }
        }
        return array;
    }
Run()
static void Util.Run (string itemPath) inline static
Definition at line 242 of file Util.cs.
    {
        Process.Start(itemPath);
    }
SetRectToFitScreen()
static void Util.SetRectToFitScreen (RectTransform rect) inline static
Definition at line 101 of file Util.cs.
    {
        rect.anchorMin = Vector2.zero;
        rect.anchorMax = Vector2.one;
        rect.localPosition = Vector3.zero;
        rect.anchoredPosition = Vector2.zero;
        rect.sizeDelta = Vector2.zero;
    }
ShowExplorer()
static void Util.ShowExplorer (string itemPath, bool selectFirstFile = false) inline static
Definition at line 228 of file Util.cs.
    {
        if (selectFirstFile)
        {
            FileInfo[] files = new DirectoryInfo(itemPath).GetFiles();
            if (files.Length != 0)
            {
                itemPath = itemPath + "/" + files[0].Name;
            }
        }
        itemPath = itemPath.Replace("/", "\\");
        Process.Start("explorer.exe", "/select," + itemPath);
    }
WorldToUIPos()
static Vector2 Util.WorldToUIPos (Vector3 worldPoint, RectTransform container) inline static
Definition at line 209 of file Util.cs.
    {
        Vector2 localPoint = Vector2.zero;
        Vector2 screenPoint = RectTransformUtility.WorldToScreenPoint(Camera.main, worldPoint);
        RectTransformUtility.ScreenPointToLocalPointInRectangle(container, screenPoint, canvas.worldCamera, out localPoint);
        return localPoint;
    }
Member Data Documentation
alphaMap
Color [] Util.alphaMap static
Definition at line 11 of file Util.cs.
canvas
Canvas Util.canvas static
Definition at line 13 of file Util.cs.
The documentation for this class was generated from the following file:
Elin/Plugins.basecore/Util.cs