Elin Decompiled Documentation: Scene Class Reference
Scene Class Reference
Public Types
enum Mode { None , Title , StartGame , Zone }
Public Member Functions
void TryWarnMacScreen ()
void TryWarnLinuxMod ()
void Init (Mode newMode)
void OnKillGame ()
void Clear ()
void OnUpdate ()
void OnLateUpdate ()
void UpdateCursor ()
void UpdateTimeRatio ()
void OnChangeHour ()
void RefreshBG ()
void FocusAndPause (Point pos, int a)
void ApplyZoneConfig ()
void OnToggle ()
void ToggleShowRoof ()
void ToggleLight ()
void ToggleSnapFreePos ()
void ToggleFreePos ()
void ToggleShowWall ()
void ToggleRoof ()
void ToggleSlope ()
void ToggleTilt ()
void ToggleHighlightArea ()
void ToggleBirdView (bool sound=true)
void ToggleBalloon ()
void ToggleMuteBGM ()
void RebuildActorEx ()
void RefreshActorEx ()
void ClearActorEx ()
void AddActorEx (Card c, Action< ActorEx > onBeforeSetOwner=null)
void RemoveActorEx (Card c)
void InitPass ()
void DrawPass ()
void RefreshSync ()
Transform LoadPrefab (string id)
void DestroyPrefabs ()
void DestroyPrefab (string id)
Public Attributes
Vector2[] test
Transform transFocus
Transform transBlizzard
Transform transAudio
Vector3 posAudioListener
AudioListener audioListener
Camera cam
Camera camTreasure
CameraSupport camSupport
VFX firefly
VFX fireflyNight
VFX star
ParticleSystem rain
ParticleSystem snow
ParticleSystem ether
ParticleSystem godray
ParticleSystem godrayDust
ParticleSystem blossom
ParticleSystem etherBlossom
ParticleSystem bubble
ParticleSystem[] blossoms
ParticleSystem[] blizzards
FlockController flock
MeshRenderer skyBG
MeshRenderer skyPlane
SceneProfile profile
CameraFilterPack_Atmosphere_Rain filterRain
ActionMode actionMode
SoundSource sfxRain
SoundSource sfxWind
SoundSource sfxUnderwater
SoundSource sfxSea
SoundSource sfxFire
SoundSource sfxEther
GameScreen screenElin
GameScreenElona screenElona
GameScreenNoMap screenNoMap
PopperManager popper
EloMapActor elomapActor
SpriteRenderer srTarget
Tileset tileset
Material matFloorEx
DamageTextRenderer damageTextRenderer = new DamageTextRenderer()
ParticleSystem psFoot
ParticleSystem psSmoke
ParticleSystem psRainSplash
ParticleSystem psRainSplashWater
ParticleSystem psFey
MeshPass[] passes
GameSetting.RenderSetting.MapBGSetting bg
Mode mode
float timeRatio
List< GameObject > loadedPrefabs = new List<GameObject>()
PointTarget mouseTarget = new PointTarget()
List< ISyncScreen > syncList = new List<ISyncScreen>()
bool paused
long syncFrame
Dictionary< Card, ActorEx > dictActorEx = new Dictionary<Card, ActorEx>()
bool hideBalloon
Static Public Attributes
static bool isAnnounced
static Point HitPoint = new Point()
static Point ClickPoint = new Point()
static bool skipAnime
Static Public Attributes inherited from EMono
static Core core
Properties
EloMap elomap [get]
Properties inherited from EMono
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SoundManager Sound [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static CoreDebug debug [get]
Private Member Functions
void Awake ()
Additional Inherited Members
Static Public Member Functions inherited from EMono
static int rnd (int a)
Detailed Description
Definition at line 7 of file Scene.cs.
Member Enumeration Documentation
Mode
enum Scene.Mode
Enumerator
None
Title
StartGame
Zone
Definition at line 9 of file Scene.cs.
    {
        None,
        Title,
        StartGame,
        Zone
    }
Member Function Documentation
AddActorEx()
void Scene.AddActorEx (Card c, Action< ActorEx > onBeforeSetOwner = null) inline
Definition at line 1015 of file Scene.cs.
    {
        ActorEx actorEx = dictActorEx.TryGetValue(c);
        if (!(actorEx != null))
        {
            actorEx = Util.Instantiate<ActorEx>("Scene/Render/Actor/Ex/" + c.trait.IDActorEx);
            onBeforeSetOwner?.Invoke(actorEx);
            actorEx.SetOwner(c);
            dictActorEx.Add(c, actorEx);
        }
    }
References Trait.IDActorEx, ActorEx.SetOwner(), Card.trait, and Util.
Referenced by Map._AddCard(), TraitJukeBox.OnToggle(), and TraitRadio.OnUse().
ApplyZoneConfig()
void Scene.ApplyZoneConfig () inline
Definition at line 823 of file Scene.cs.
    {
        MapConfig conf;
        if (EMono.core.IsGameStarted)
        {
            conf = EMono._map.config;
            LiquidProfile.Apply(conf.idLiquid);
            RefractionProfile.Apply(conf.idRefraction);
            BaseTileMap tileMap = screenElin.tileMap;
            SetOcean(tileMap.passLiquid.mat);
            SetOcean(tileMap.passFloorWater.mat);
            SetOcean(tileMap.passAutoTileWater.mat);
            ScreenGrading grading = camSupport.grading;
            ScreenGradingProfile.Lut lut = grading.lut;
            grading.profile.funcOverlay = () => EMono.scene.profile.overlay;
            if (conf.idLut == "None")
            {
                lut.tex = null;
            }
            else
            {
                lut.tex = Resources.Load<Texture2D>("Scene/Profile/Lut/" + conf.idLut);
                lut.Brightness = conf.lutBrightness;
                lut.Saturation = conf.lutSaturation;
                lut.Contrast = conf.lutContrast;
                lut.blend = conf.lutBlend;
            }
            grading.SetGrading();
        }
        void SetOcean(Material m)
        {
            m.SetFloat("_GradientWater", EMono.core.config.graphic.gradientWater ? EMono.core.config.graphic.gradientWaterLevel : 0f);
            if (conf.seaDir != 0)
            {
                m.EnableKeyword("WAVE_ON");
                Vector4[] array = new Vector4[4]
                {
                    new Vector4(-2f, -1f, -1f, 1f),
                    new Vector4(1f, 0f, 1f, 1f),
                    new Vector4(2f, 1f, -1f, 1f),
                    new Vector4(-1f, 0f, 1f, 1f)
                };
                m.SetVector("_WaveDir", array[conf.seaDir - 1]);
            }
            else
            {
                m.DisableKeyword("WAVE_ON");
            }
        }
    }
References EMono._map, LiquidProfile.Apply(), RefractionProfile.Apply(), Core.config, Map.config, EMono.core, CoreConfig.GraphicSetting.gradientWater, CoreConfig.GraphicSetting.gradientWaterLevel, CameraSupport.grading, CoreConfig.graphic, MapConfig.idLiquid, MapConfig.idLut, MapConfig.idRefraction, if(), Core.IsGameStarted, MapConfig.lutBlend, MapConfig.lutBrightness, MapConfig.lutContrast, MapConfig.lutSaturation, MeshPass.mat, Material, SceneProfile.overlay, BaseTileMap.passAutoTileWater, BaseTileMap.passFloorWater, BaseTileMap.passLiquid, profile, EMono.scene, MapConfig.seaDir, and BaseGameScreen.tileMap.
Referenced by BaseGameScreen.Activate(), WidgetSceneCustomizer.OnActivate(), TextureManager.RefreshTextures(), and WidgetSceneCustomizer.ShowPicker().
Awake()
void Scene.Awake () inline private
Definition at line 151 of file Scene.cs.
    {
        InvokeRepeating("RefreshActorEx", 0.5f, 0.5f);
    }
Clear()
void Scene.Clear () inline
Definition at line 353 of file Scene.cs.
    {
        foreach (ISyncScreen sync in syncList)
        {
            sync.OnLeaveScreen();
        }
        syncList.Clear();
        EffectManager.Instance.KillAll();
        ClearActorEx();
        DestroyPrefabs();
    }
References ClearActorEx(), DestroyPrefabs(), EffectManager.Instance, EffectManager.KillAll(), ISyncScreen.OnLeaveScreen(), and syncList.
Referenced by Zone.Deactivate(), and OnKillGame().
ClearActorEx()
void Scene.ClearActorEx () inline
Definition at line 1006 of file Scene.cs.
    {
        foreach (ActorEx value in dictActorEx.Values)
        {
            value.Kill();
        }
        dictActorEx.Clear();
    }
References ActorEx.Kill().
Referenced by Clear().
DestroyPrefab()
void Scene.DestroyPrefab (string id) inline
Definition at line 1115 of file Scene.cs.
    {
        GameObject gameObject = GameObject.Find(id);
        if ((bool)gameObject)
        {
            UnityEngine.Object.DestroyImmediate(gameObject);
        }
    }
DestroyPrefabs()
void Scene.DestroyPrefabs () inline
Definition at line 1106 of file Scene.cs.
    {
        foreach (GameObject loadedPrefab in loadedPrefabs)
        {
            UnityEngine.Object.Destroy(loadedPrefab);
        }
        loadedPrefabs.Clear();
    }
Referenced by Clear().
DrawPass()
void Scene.DrawPass () inline
Definition at line 1058 of file Scene.cs.
    {
        if (cam.enabled)
        {
            MeshPass[] array = passes;
            for (int i = 0; i < array.Length; i++)
            {
                array[i].Draw();
            }
        }
        else
        {
            MeshPass[] array = passes;
            for (int i = 0; i < array.Length; i++)
            {
                array[i].DrawEmpty();
            }
        }
        RefreshSync();
        if ((bool)EMono.screen.guide)
        {
            EMono.screen.guide.OnDrawPass();
        }
    }
References MeshPass.Draw(), MeshPass.DrawEmpty(), BaseGameScreen.guide, ScreenGuide.OnDrawPass(), and EMono.screen.
FocusAndPause()
void Scene.FocusAndPause (Point pos, int a) inline
Definition at line 811 of file Scene.cs.
    {
        if (a >= 1)
        {
            EMono.core.screen.Focus(pos);
        }
        if (a >= 2)
        {
            ActionMode.Sim.Pause();
        }
    }
References EMono.core, BaseGameScreen.Focus(), ActionMode.Pause(), Core.screen, and ActionMode.Sim.
Init()
void Scene.Init (Mode newMode) inline
Definition at line 178 of file Scene.cs.
    {
        Debug.Log("Scene.Init:" + newMode);
        EMono.ui.RemoveLayers();
        BuildMenu.Deactivate();
        ScreenFlash.Reset();
        mode = newMode;
        switch (newMode)
        {
        case Mode.None:
            if (EMono.game != null)
            {
                EMono.game.Kill();
            }
            EMono.ui.RemoveLayers();
            screenNoMap.Activate();
            break;
        case Mode.Title:
            SoundManager.bgmVolumeMod = (SoundManager.bgmDumpMod = 0f);
            if (EMono.game != null)
            {
                EMono.game.Kill();
            }
            EMono.ui.AddLayer<LayerTitle>();
            if (!isAnnounced || Application.isEditor)
            {
                isAnnounced = true;
                EMono.core.WaitForEndOfFrame(delegate
                {
                    EMono.ui.AddLayer("LayerAnnounce").SetOnKill(TryWarnMacScreen);
                });
            }
            else
            {
                TryWarnMacScreen();
            }
            ActionMode.Title.Activate();
            screenNoMap.Activate();
            break;
        case Mode.StartGame:
            EMono.ui.RemoveLayer<LayerTitle>();
            EMono.ui.ShowCover();
            Init(Mode.Zone);
            break;
        case Mode.Zone:
            EMono.player.target = null;
            UIBook.str_pc = EMono.pc.NameSimple;
            if (EMono.player.zone == null)
            {
                Player obj = EMono.player;
                Zone zone = (EMono.pc.currentZone = EMono.pc.homeZone);
                obj.zone = zone;
            }
            EMono.core.config.game.ignoreWarnCrime = (EMono.core.config.game.ignoreWarnMana = (EMono.core.config.game.ignoreWarnDisassemble = (EMono.core.config.game.ignoreWarnSlaughter = false)));
            EMono.game.updater.Reset();
            CellDetail.count = 0;
            skipAnime = true;
            EMono.player.baseActTime = EMono.setting.defaultActPace;
            EMono.player.Agent.renderer.isSynced = true;
            EMono.player.Agent.currentZone = EMono.player.zone;
            Point._screen = (EMono.player.zone.IsRegion ? ((BaseGameScreen)screenElona) : ((BaseGameScreen)screenElin));
            EMono.player.zone.Activate();
            EMono.player.RefreshEmptyAlly();
            UpdateTimeRatio();
            EMono.world.weather.RefreshWeather();
            EMono.screen.Deactivate();
            Popper.scale = (EMono._zone.IsRegion ? new Vector3(1.7f, 1.7f, 1f) : Vector3.one);
            if (!EMono.pc.IsInActiveZone)
            {
                ActionMode.View.Activate();
            }
            else if (EMono.player.zone is Region)
            {
                ActionMode.Region.Activate();
            }
            else
            {
                ActionMode.Adv.Activate();
            }
            if (EMono.game.altCraft)
            {
                if (EMono._zone.IsRegion)
                {
                    if ((bool)EMono.ui.layerFloat.GetLayer<LayerCraftFloat>())
                    {
                        EMono.ui.layerFloat.RemoveLayer<LayerCraftFloat>();
                    }
                }
                else if (!EMono.ui.layerFloat.GetLayer<LayerCraftFloat>())
                {
                    EMono.ui.layerFloat.AddLayer<LayerCraftFloat>();
                }
            }
            EMono.screen.tileMap.activeCount = 0;
            EMono.screen.SetZoom(EMono.screen.TargetZoom);
            EMono.player.RefreshCurrentHotItem();
            EMono.screen.FocusPC();
            EMono.game.updater.recipe.Build(EMono.pc.pos);
            WidgetDate.Refresh();
            WidgetMenuPanel.OnChangeMode();
            EMono.player.hotbars.ResetHotbar(2);
            if (EMono.ui.hud.imageCover.gameObject.activeSelf && !EMono.player.simulatingZone)
            {
                EMono.ui.HideCover(4f);
            }
            if (!EMono.core.debug.ignoreAutoSave && EMono.core.config.game.autoSave && EMono.game.countLoadedMaps > 3 && !EMono.player.simulatingZone)
            {
                EMono.game.Save();
            }
            foreach (Thing thing in EMono._map.things)
            {
                if (thing.IsInstalled)
                {
                    thing.trait.TryToggle();
                }
            }
            EMono.core.config.ApplyGrading();
            camSupport.water.enabled = EMono._zone.IsUnderwater;
            if (EMono.player.onStartZone != null)
            {
                EMono.player.onStartZone();
                EMono.player.onStartZone = null;
            }
            ActionMode.LastBuildMode = null;
            if (ActionMode.Adv.IsActive && (EInput.leftMouse.pressing || EInput.axis != Vector2.zero))
            {
                ActionMode.Adv.SetPressedAction(EInput.leftMouse);
                ActionMode.Adv.RefreshArrow();
                ActionMode.Adv.SetManualMove();
            }
            if (EMono.pc.IsAliveInCurrentZone)
            {
                EMono.pc.RecalculateFOV();
            }
            flock.SetSpawnType(EMono._zone.FlockType);
            if (!EMono.player.simulatingZone)
            {
                EMono.player.flags.OnEnterZone();
                if (EMono._zone == EMono.pc.homeZone)
                {
                    EMono.pc.faith.Revelation("welcome");
                }
                if (EMono._zone.Boss != null && EMono._zone.Boss.ExistsOnMap)
                {
                    Msg.Say("beware", EMono._zone.Name, EMono._zone.Boss.NameBraced);
                }
                EMono.game.quests.OnEnterZone();
            }
            EInput.keyWait.Consume();
            if (EMono.player.questTracker && !EMono.ui.widgets.GetWidget("QuestTracker"))
            {
                EMono.ui.widgets.Activate("QuestTracker");
            }
            if ((EMono._zone is Zone_Town || EMono._zone is Zone_Tent) && !EMono._zone.isMapSaved && !EMono.debug.ignoreAutoSave)
            {
                EMono.game.Save();
            }
            break;
        }
        etherBlossom.SetActive(mode == Mode.Zone && EMono._zone is Zone_WindRest);
        bubble.SetActive(mode == Mode.Zone && EMono._zone.IsUnderwater);
    }
References EMono._map, EMono._zone, BaseGameScreen.Activate(), Zone.Activate(), ActionMode.Activate(), ActionMode.Adv, Game.altCraft, CoreConfig.ApplyGrading(), CoreConfig.GameConfig.autoSave, EInput.axis, Zone.Boss, bubble, RecipeUpdater.Build(), Core.config, EInput.KeyboardPress.Consume(), EMono.core, Game.countLoadedMaps, BaseGameScreen.Deactivate(), BuildMenu.Deactivate(), Core.debug, EMono.debug, Debug, GameSetting.defaultActPace, etherBlossom, Card.ExistsOnMap, Chara.faith, Player.flags, flock, Zone.FlockType, BaseGameScreen.FocusPC(), CoreConfig.game, EMono.game, Chara.homeZone, Player.hotbars, CoreDebug.ignoreAutoSave, Init(), ActionMode.IsActive, Chara.IsAliveInCurrentZone, isAnnounced, Chara.IsInActiveZone, Card.IsInstalled, Spatial.IsRegion, Zone.IsUnderwater, EInput.keyWait, Game.Kill(), EInput.leftMouse, mode, Spatial.Name, Chara.NameBraced, Card.NameSimple, WidgetMenuPanel.OnChangeMode(), Player.Flags.OnEnterZone(), QuestManager.OnEnterZone(), Player.onStartZone, EMono.pc, EMono.player, Card.pos, ButtonState.pressing, Game.quests, Player.questTracker, Card.RecalculateFOV(), GameUpdater.recipe, WidgetDate.Refresh(), AM_Adv.RefreshArrow(), Player.RefreshCurrentHotItem(), Player.RefreshEmptyAlly(), Weather.RefreshWeather(), ActionMode.Region, GameUpdater.Reset(), ScreenFlash.Reset(), HotbarManager.ResetHotbar(), Religion.Revelation(), Game.Save(), Msg.Say(), EMono.screen, screenElin, screenElona, screenNoMap, AM_Adv.SetManualMove(), AM_Adv.SetPressedAction(), EMono.setting, BaseGameScreen.SetZoom(), Player.simulatingZone, skipAnime, BaseGameScreen.TargetZoom, Map.things, ActionMode.Title, Card.trait, Trait.TryToggle(), TryWarnMacScreen(), EMono.ui, Game.updater, UpdateTimeRatio(), ActionMode.View, BaseCore.WaitForEndOfFrame(), World.weather, EMono.world, and Player.zone.
Referenced by AM_Adv._OnUpdateInput(), Game.GotoTitle(), Core.Init(), Init(), Game.Load(), Player.MoveZone(), Map.Reload(), Player.SimulateFaction(), Game.StartNewGame(), and CoreDebug.UpdateInput().
InitPass()
void Scene.InitPass () inline
Definition at line 1037 of file Scene.cs.
    {
        MeshPass[] array = passes;
        for (int i = 0; i < array.Length; i++)
        {
            array[i].Init();
        }
        foreach (ModItem<Sprite> item in MOD.sprites.list)
        {
            Sprite sprite = SpriteSheet.Get(item.id);
            if ((bool)sprite)
            {
                Sprite @object = item.GetObject(new SpriteLoadOption
                {
                    pivot = new Vector2(sprite.pivot.x / (sprite.bounds.size.x * 100f), sprite.pivot.y / (sprite.bounds.size.y * 100f))
                });
                SpriteSheet.dict[item.id] = @object;
            }
        }
    }
References SpriteSheet.dict, SpriteSheet.Get(), MeshPass.Init(), item, ModItemList< T >.list, and MOD.sprites.
Referenced by Core.Init().
LoadPrefab()
Transform Scene.LoadPrefab (string id) inline
Definition at line 1098 of file Scene.cs.
    {
        Transform transform = Util.Instantiate<Transform>("Scene/Prefab/" + id);
        transform.name = id;
        loadedPrefabs.Add(transform.gameObject);
        return transform;
    }
References Util.
Referenced by Zone_Olvina.OnActivate(), and Zone_SisterHouse.OnActivate().
OnChangeHour()
void Scene.OnChangeHour () inline
Definition at line 776 of file Scene.cs.
    {
        UpdateTimeRatio();
        firefly.OnChangeHour();
        fireflyNight.OnChangeHour();
        star.OnChangeHour();
        if ((bool)EMono.screen.pcOrbit)
        {
            EMono.screen.pcOrbit.OnChangeMin();
        }
        EMono.screen.RefreshSky();
        EMono.screen.OnChangeHour();
        foreach (Transform componentsInDirectChild in EMono.ui.rectDynamic.GetComponentsInDirectChildren<Transform>())
        {
            if (componentsInDirectChild.gameObject.tag != "IgnoreDestroy" && !componentsInDirectChild.GetComponent<TC>())
            {
                UnityEngine.Object.Destroy(componentsInDirectChild.gameObject);
            }
        }
    }
References BaseGameScreen.OnChangeHour(), VFX.OnChangeHour(), PCOrbit.OnChangeMin(), BaseGameScreen.pcOrbit, BaseGameScreen.RefreshSky(), EMono.screen, and EMono.ui.
Referenced by BaseGameScreen.Activate(), GameDate.AdvanceHour(), and DramaManager.ParseLine().
OnKillGame()
void Scene.OnKillGame () inline
Definition at line 341 of file Scene.cs.
    {
        actionMode.Deactivate();
        mouseTarget.Clear();
        hideBalloon = false;
        actionMode = null;
        PCC.PurgeCache();
        Clear();
        flock.Reset();
        elomapActor.OnKillGame();
    }
References actionMode, PointTarget.Clear(), Clear(), ActionMode.Deactivate(), elomapActor, flock, hideBalloon, mouseTarget, and EloMapActor.OnKillGame().
Referenced by Game.Kill().
OnLateUpdate()
void Scene.OnLateUpdate () inline
Definition at line 745 of file Scene.cs.
    {
        DrawPass();
        CursorSystem.Instance.Draw();
    }
References CursorSystem.Draw(), and CursorSystem.Instance.
Referenced by Core.LateUpdate().
OnToggle()
void Scene.OnToggle () inline
Definition at line 874 of file Scene.cs.
    {
        SE.ClickGeneral();
        WidgetSystemIndicator.Refresh();
        WidgetHotbar.RefreshHighlights();
    }
References WidgetSystemIndicator.Refresh(), and WidgetHotbar.RefreshHighlights().
OnUpdate()
void Scene.OnUpdate () inline
Definition at line 365 of file Scene.cs.
    {
        SoundManager.speed = (EMono.core.IsGameStarted ? Mathf.Clamp(actionMode.gameSpeed * 0.75f, 1f, 2f) : 1f);
        UIButton.UpdateButtons();
        EMono.ui.RefreshActiveState();
        bool isShiftDown = EInput.isShiftDown;
        if ((bool)UIDropdown.activeInstance)
        {
            EInput.UpdateOnlyAxis();
        }
        else
        {
            EInput.Update();
        }
        CoreConfig.InputSetting input = EMono.core.config.input;
        if (EInput.middleMouse.pressing)
        {
            if (input.middleClick == CoreConfig.GameFunc.EmuShift || input.middlePressLong == CoreConfig.GameFunc.EmuShift)
            {
                EInput.isShiftDown = true;
            }
            if (input.middleClick == CoreConfig.GameFunc.EmuAlt || input.middlePressLong == CoreConfig.GameFunc.EmuAlt)
            {
                EInput.isAltDown = true;
            }
        }
        if (EInput.mouse3.pressing)
        {
            if (input.mouse3Click == CoreConfig.GameFunc.EmuShift || input.mouse3PressLong == CoreConfig.GameFunc.EmuShift)
            {
                EInput.isShiftDown = true;
            }
            if (input.mouse3Click == CoreConfig.GameFunc.EmuAlt || input.mouse3PressLong == CoreConfig.GameFunc.EmuAlt)
            {
                EInput.isAltDown = true;
            }
        }
        if (EInput.mouse4.pressing)
        {
            if (input.mouse4Click == CoreConfig.GameFunc.EmuShift || input.mouse4PressLong == CoreConfig.GameFunc.EmuShift)
            {
                EInput.isShiftDown = true;
            }
            if (input.mouse4Click == CoreConfig.GameFunc.EmuAlt || input.mouse4PressLong == CoreConfig.GameFunc.EmuAlt)
            {
                EInput.isAltDown = true;
            }
        }
        EInput.hasShiftChanged = EInput.isShiftDown != isShiftDown;
        Layer.cancelKeyDown = EInput.isCancel;
        Layer.rightClicked = EInput.rightMouse.down;
        int num = EInput.wheel;
        if (num != 0)
        {
            if (EMono.ui.isPointerOverUI)
            {
                if (!EMono.ui.GetLayer<LayerConfig>())
                {
                    UIDropdown componentOf = InputModuleEX.GetComponentOf<UIDropdown>();
                    if ((bool)componentOf && !UIDropdown.activeInstance)
                    {
                        if (num < 0)
{
                            componentOf.Next();
                        }
                        else if (num > 0)
{
                            componentOf.Prev();
                        }
                        num = (EInput.wheel = 0);
                    }
                    Slider componentOf2 = InputModuleEX.GetComponentOf<Slider>();
                    if ((bool)componentOf2 && (bool)EMono.ui.GetLayer<LayerEditPCC>())
                    {
                        SE.Tab();
                        componentOf2.value += (componentOf2.wholeNumbers ? ((float)num) : (0.1f * (float)num));
                        num = (EInput.wheel = 0);
                    }
                }
                if (!DropdownGrid.IsActive)
                {
                    DropdownGrid componentOf3 = InputModuleEX.GetComponentOf<DropdownGrid>();
                    if ((bool)componentOf3)
                    {
                        if (num < 0)
{
                            componentOf3.Next();
                        }
                        else if (num > 0)
{
                            componentOf3.Prev();
                        }
                        num = (EInput.wheel = 0);
                    }
                }
                if (EMono.ui.contextMenu.isActive)
                {
                    Slider componentOf4 = InputModuleEX.GetComponentOf<Slider>();
                    if ((bool)componentOf4)
                    {
                        componentOf4.value += (componentOf4.wholeNumbers ? ((float)num) : (0.1f * (float)num));
                        num = (EInput.wheel = 0);
                        SE.Tab();
                    }
                }
                UIScrollView componentOf5 = InputModuleEX.GetComponentOf<UIScrollView>();
                if ((bool)componentOf5)
                {
                    num = (EInput.wheel = 0);
                    if (componentOf5.verticalScrollbar.isActiveAndEnabled)
                    {
                        EMono.ui.HideMouseHint();
                    }
                }
                UIButton componentOf6 = InputModuleEX.GetComponentOf<UIButton>();
                if ((bool)componentOf6 && componentOf6.onInputWheel != null)
                {
                    componentOf6.onInputWheel(num);
                    num = (EInput.wheel = 0);
                }
            }
            if (num != 0)
            {
                Layer layer = (EMono.ui.IsActive ? EMono.ui.GetTopLayer() : LayerAbility.Instance);
                if (layer != null && layer.windows.Count > 0)
                {
                    Window window = layer.windows[0];
                    if (InputModuleEX.IsPointerChildOf(window.rectTab) && !DropdownGrid.IsActive && window.NextTab(num))
                    {
                        num = (EInput.wheel = 0);
                    }
                }
            }
        }
        if ((EInput.leftMouse.down || EInput.rightMouse.down) && (bool)WidgetMainText.Instance && WidgetMainText.Instance.box.isShowingLog && !InputModuleEX.IsPointerChildOf(WidgetMainText.Instance))
        {
            WidgetMainText.Instance._ToggleLog();
            EInput.Consume();
        }
        switch (mode)
        {
        case Mode.Title:
            if (EMono.scene.elomapActor.IsActive)
            {
                timeRatio = 0f;
                EMono.screen.UpdateShaders();
            }
            godray.SetActive(enable: false);
            UpdateCursor();
            EMono.ui.UpdateInput();
            break;
        case Mode.Zone:
        {
            if (!EMono.core.IsGameStarted)
            {
                break;
            }
            if (EMono._zone.dirtyElectricity)
            {
                EMono._zone.RefreshElectricity();
            }
            if (EMono.player.target != null && EMono.player.target.isSynced)
            {
                srTarget.enabled = true;
                Vector3 position = EMono.player.target.pos.PositionCenter();
                position.y += EMono.player.target.renderer.data.size.y;
                position.z -= 10f;
                srTarget.transform.parent.position = position;
            }
            else
            {
                srTarget.enabled = false;
            }
            EMono.player.pickupDelay -= Core.delta;
            if (EMono.player.pickupDelay < 0f)
            {
                EMono.player.pickupDelay = 0f;
            }
            actionMode.OnBeforeUpdate();
            paused = EMono.ui.IsPauseGame || actionMode.ShouldPauseGame || Game.IsWaiting;
            EMono.player.RefreshEmptyAlly();
            if (!EMono.pc.isDead)
            {
                if (AI_PlayMusic.keepPlaying && EInput.skipFrame <= 0 && Input.anyKeyDown && !Input.GetKey(KeyCode.Tab) && !Input.GetKey(KeyCode.LeftAlt))
                {
                    AI_PlayMusic.CancelKeepPlaying();
                }
                actionMode.UpdateInput();
            }
            else
            {
                EMono.ui.UpdateInput();
            }
            if (EMono.pc.currentZone != EMono.game.activeZone && EMono.pc.global.transition != null)
            {
                EMono.player.flags.OnLeaveZone();
                if (!LayerDrama.IsActive())
                {
                    EMono.player.MoveZone(EMono.pc.currentZone);
                }
            }
            if (EMono.pc.isDead && !EMono.player.deathDialog)
            {
                EMono.player.deathDialog = true;
                EMono.player.returnInfo = null;
                EMono.player.ignoreFallOver = 1;
                Msg.Say("diebye");
                EMono.Sound.Play("dead_pc2");
                EMono.Sound.Play("dead_pc");
                string[] list = Lang.GetList("lastWords");
                string lastWord = list.RandomItem();
                if (EMono.game.principal.permadeath)
                {
                    GameIO.DeleteGame(Game.id, EMono.game.isCloud);
                }
                EMono.ui.CloseLayers();
                if ((bool)UIContextMenu.Current)
                {
                    UIContextMenu.Current.Hide();
                }
                EInput.haltInput = false;
                Dialog.InputName("dialogLastword", lastWord, delegate(bool cancel, string text)
                {
                    if (!cancel)
                    {
                        lastWord = text;
                    }
                    Player obj = EMono.player;
                    obj.deathMsg = obj.deathMsg + Lang.space + lastWord.Bracket(1);
                    if (EMono.core.config.net.enable && EMono.core.config.net.sendEvent)
                    {
                        Net.SendChat(EMono.pc.NameTitled, EMono.player.deathMsg, ChatCategory.Dead, Lang.langCode);
                    }
                    Debug.Log(lastWord);
                    Msg.SetColor(Msg.colors.Talk);
                    Msg.Say(lastWord.Bracket(1));
                    List<string> list2 = new List<string>();
                    Zone lastTown = EMono.game.spatials.Find(EMono.player.uidLastTown);
                    bool addTownRevive = lastTown != null && !EMono._zone.IsInstance;
                    if (!EMono.game.principal.permadeath)
                    {
                        if (addTownRevive)
{
                            list2.Add("pc_revive_town".lang(lastTown.Name));
                        }
                        list2.Add("pc_revive");
                        list2.Add("pc_gameover");
                    }
                    else
                    {
                        list2.Add("pc_gameover");
                    }
                    Debug.Log(list2.Count);
                    EMono.ui.AddLayer<LayerCover>().SetDuration(1f, delegate
                    {
                        EMono.ui.CloseLayers();
                        Dialog.List("pc_deathChoice".lang(), list2, (string j) => j, delegate(int c, string d)
{
                            EMono.player.deathDialog = false;
                            if (!EMono.game.principal.permadeath && (c == 0 || (addTownRevive && c == 1)))
{
                                EMono.pc.MakeGrave(lastWord);
                                EMono.pc.Revive();
                                EMono.pc.RecalculateFOV();
                                Zone zone = EMono.player.spawnZone ?? EMono.pc.homeZone;
                                if (addTownRevive && c == 0)
{
                                    zone = lastTown;
                                }
                                if (EMono.game.activeZone == zone)
{
                                    EMono.pc.Teleport(EMono._zone.GetSpawnPos(EMono.pc, ZoneTransition.EnterState.Return).GetNearestPoint() ?? EMono._map.GetCenterPos(), silent: true, force: true);
                                }
                                else
{
                                    EMono.player.deathZoneMove = true;
                                    EMono.pc.MoveZone(zone, ZoneTransition.EnterState.Return);
                                }
                                EMono.screen.FocusPC();
                                Msg.Say("crawlup");
                                if (EMono.player.stats.death == 0)
{
                                    Tutorial.Reserve("death");
                                }
                                EMono.player.stats.death++;
                            }
                            else
{
                                EMono.game.GotoTitle(showDialog: false);
                            }
                            return true;
                        });
                    });
                });
            }
            UpdateCursor();
            UpdateTimeRatio();
            EMono.Sound.UpdateBGM();
            EMono.game.updater.Update();
            if (WidgetHotbar.dirtyCurrentItem)
            {
                EMono.player.RefreshCurrentHotItem();
            }
            if (WidgetEquip.dirty)
            {
                WidgetEquip.Redraw();
            }
            if (EMono.player.wasDirtyWeight)
            {
                foreach (Chara member in EMono.pc.party.members)
                {
                    member.CalcBurden();
                }
                EMono.player.wasDirtyWeight = false;
            }
            if (!EMono.ui.IsActive)
            {
                EMono.core.screen.tileSelector.OnUpdate();
            }
            else if (EMono.ui.mouseInfo.gameObject.activeSelf)
            {
                EMono.ui.mouseInfo.SetText();
            }
            EMono.screen.Draw();
            damageTextRenderer.Flush();
            actionMode.OnAfterUpdate();
            if (EMono.player.lastTransition == null || EMono.player.simulatingZone)
            {
                break;
            }
            if (!EMono.ui.GetLayer<LayerDrama>())
            {
                switch (EMono.player.lastTransition.state)
                {
                case ZoneTransition.EnterState.Fall:
                    EMono.pc.PlaySound("fall");
                    EMono.pc.PlayAnime(AnimeID.FallSky);
                    EMono.pc.DamageHP((20 + EMono.rnd(30) + ((EMono.player.lastTransition.lastZone is Zone_Casino) ? 1000 : 0)) / ((!EMono.pc.IsLevitating) ? 1 : 10), AttackSource.Fall);
                    break;
                case ZoneTransition.EnterState.Elevator:
                    EMono.pc.PlaySound("elevator");
                    break;
                case ZoneTransition.EnterState.PortalReturn:
                case ZoneTransition.EnterState.Return:
                case ZoneTransition.EnterState.Teleport:
                case ZoneTransition.EnterState.Moongate:
                    EMono.pc.PlayEffect("teleport");
                    EMono.pc.PlaySound("return");
                    break;
                default:
                    SE.MoveZone();
                    break;
                case ZoneTransition.EnterState.Encounter:
                    break;
                }
            }
            bool flag = (EMono.rnd(5) == 0 && EMono.pc.burden.GetPhase() >= 3) || EMono.pc.burden.GetPhase() >= 4;
            if (EMono.player.lastTransition.lastZone is Region)
            {
                flag = false;
            }
            if (EMono.player.ignoreFallOver > 0)
            {
                flag = flag;
                EMono.player.ignoreFallOver--;
            }
            if (flag)
            {
                EMono.pc.Stumble();
            }
            EMono.player.lastTransition = null;
            break;
        }
        default:
            UpdateCursor();
            EMono.ui.UpdateInput();
            break;
        }
    }
References WidgetMainText._ToggleLog(), EMono._zone, actionMode, UIDropdown.activeInstance, Game.activeZone, WidgetMainText.box, Chara.burden, Chara.CalcBurden(), AI_PlayMusic.CancelKeepPlaying(), Msg.colors, Core.config, EInput.Consume(), EMono.core, UIContextMenu.Current, Chara.currentZone, Card.DamageHP(), damageTextRenderer, RenderObject.data, Player.deathDialog, Debug, GameIO.DeleteGame(), Core.delta, WidgetEquip.dirty, WidgetHotbar.dirtyCurrentItem, Zone.dirtyElectricity, ButtonState.down, BaseGameScreen.Draw(), elomapActor, CoreConfig.NetSetting.enable, SpatialManager.Find(), Player.flags, DamageTextRenderer.Flush(), EMono.game, ActionMode.gameSpeed, Lang.GetList(), Stats.GetPhase(), Chara.global, godray, UIContextMenu.Hide(), Game.id, if(), Player.ignoreFallOver, CoreConfig.input, Dialog.InputName(), LayerAbility.Instance, WidgetMainText.Instance, DropdownGrid.IsActive, EloMapActor.IsActive, LayerDrama.IsActive(), EInput.isCancel, Game.isCloud, Chara.isDead, Core.IsGameStarted, Zone.IsInstance, Chara.IsLevitating, InputModuleEX.IsPointerChildOf(), EInput.isShiftDown, MsgBox.isShowingLog, Chara.isSynced, Game.IsWaiting, AI_PlayMusic.keepPlaying, Player.lastTransition, ZoneTransition.lastZone, EInput.leftMouse, Party.members, CoreConfig.InputSetting.middleClick, EInput.middleMouse, CoreConfig.InputSetting.middlePressLong, mode, EInput.mouse3, CoreConfig.InputSetting.mouse3Click, CoreConfig.InputSetting.mouse3PressLong, EInput.mouse4, CoreConfig.InputSetting.mouse4Click, CoreConfig.InputSetting.mouse4PressLong, Player.MoveZone(), CoreConfig.net, DropdownGrid.Next(), UIDropdown.Next(), Window.NextTab(), ActionMode.OnAfterUpdate(), ActionMode.OnBeforeUpdate(), UIButton.onInputWheel, Player.Flags.OnLeaveZone(), BaseTileSelector.OnUpdate(), Chara.party, paused, EMono.pc, GamePrincipal.permadeath, Player.pickupDelay, Card.PlayAnime(), Card.PlayEffect(), EMono.player, Card.PlaySound(), Card.pos, Point.PositionCenter(), ButtonState.pressing, DropdownGrid.Prev(), UIDropdown.Prev(), Game.principal, Window.rectTab, WidgetEquip.Redraw(), Player.RefreshCurrentHotItem(), Zone.RefreshElectricity(), Player.RefreshEmptyAlly(), Card.renderer, EInput.rightMouse, EMono.rnd(), Msg.Say(), EMono.scene, Core.screen, EMono.screen, CoreConfig.NetSetting.sendEvent, Msg.SetColor(), LayerCover.SetDuration(), Player.simulatingZone, RenderData.size, EInput.skipFrame, EMono.Sound, Game.spatials, ZoneTransition.state, Chara.Stumble(), MsgColors.Talk, Player.target, BaseGameScreen.tileSelector, timeRatio, GlobalData.transition, EMono.ui, Player.uidLastTown, GameUpdater.Update(), EInput.Update(), UIButton.UpdateButtons(), UpdateCursor(), ActionMode.UpdateInput(), EInput.UpdateOnlyAxis(), Game.updater, BaseGameScreen.UpdateShaders(), UpdateTimeRatio(), Player.wasDirtyWeight, EInput.wheel, and Layer.windows.
Referenced by Core.Update().
RebuildActorEx()
void Scene.RebuildActorEx () inline
Definition at line 986 of file Scene.cs.
    {
        foreach (Thing thing in EMono._map.things)
        {
            if (!thing.trait.IDActorEx.IsEmpty())
            {
                AddActorEx(thing);
            }
        }
    }
References EMono._map, Trait.IDActorEx, Map.things, and Card.trait.
RefreshActorEx()
void Scene.RefreshActorEx () inline
Definition at line 997 of file Scene.cs.
    {
        SoundManager.bgmDumpMod = 0f;
        foreach (ActorEx value in dictActorEx.Values)
        {
            value.Refresh();
        }
    }
References ActorEx.Refresh().
RefreshBG()
void Scene.RefreshBG () inline
Definition at line 797 of file Scene.cs.
    {
        bg = EMono.setting.render.bgs[EMono._map.config.bg];
        if (EMono._map.config.bg == MapBG.Sky && EMono._zone.IsSnowZone)
        {
            bg = EMono.setting.render.bgs[MapBG.Snow];
        }
        skyBG.SetActive(bg.skyBox);
        skyBG.sharedMaterial = bg.mat;
        skyPlane.SetActive(bg.plane);
        skyPlane.sharedMaterial = bg.mat;
        cam.clearFlags = ((!EMono.core.config.graphic.alwaysClearCamera && bg.skyBox) ? CameraClearFlags.Depth : CameraClearFlags.Color);
    }
References EMono._map, EMono._zone, MapConfig.bg, GameSetting.RenderSetting.bgs, Map.config, Spatial.IsSnowZone, GameSetting.RenderSetting.MapBGSetting.mat, GameSetting.RenderSetting.MapBGSetting.plane, GameSetting.render, EMono.setting, and GameSetting.RenderSetting.MapBGSetting.skyBox.
Referenced by GameScreen.OnActivate(), and TraitMapBoard.TrySetAct().
RefreshSync()
void Scene.RefreshSync () inline
Definition at line 1083 of file Scene.cs.
    {
        for (int num = syncList.Count - 1; num >= 0; num--)
        {
            ISyncScreen syncScreen = syncList[num];
            if (syncScreen.Sync != syncFrame)
            {
                syncScreen.OnLeaveScreen();
                syncList.RemoveAt(num);
            }
        }
        syncFrame++;
        RenderObject.syncFrame = syncFrame;
    }
References ISyncScreen.OnLeaveScreen(), and ISyncScreen.Sync.
RemoveActorEx()
void Scene.RemoveActorEx (Card c) inline
Definition at line 1027 of file Scene.cs.
    {
        ActorEx actorEx = dictActorEx.TryGetValue(c);
        if (!(actorEx == null))
        {
            actorEx.Kill();
            dictActorEx.Remove(c);
        }
    }
References ActorEx.Kill().
Referenced by TraitJukeBox.OnToggle(), TraitRadio.OnUse(), and Zone.RemoveCard().
ToggleBalloon()
void Scene.ToggleBalloon () inline
Definition at line 967 of file Scene.cs.
    {
        hideBalloon = !hideBalloon;
        EMono.ui.ShowBalloon(!hideBalloon);
        SE.ClickGeneral();
        WidgetSystemIndicator.Refresh();
    }
References WidgetSystemIndicator.Refresh(), and EMono.ui.
Referenced by HotItemToggle.OnClick().
ToggleBirdView()
void Scene.ToggleBirdView (bool sound = true) inline
Definition at line 954 of file Scene.cs.
    {
        SE.ClickGeneral();
        if (EMono.scene.actionMode == ActionMode.Bird)
        {
            EMono.scene.actionMode.Deactivate();
        }
        else
        {
            ActionMode.Bird.Activate();
        }
    }
References actionMode, ActionMode.Activate(), ActionMode.Bird, ActionMode.Deactivate(), and EMono.scene.
Referenced by HotItemContext.Show().
ToggleFreePos()
void Scene.ToggleFreePos () inline
Definition at line 904 of file Scene.cs.
    {
        if (!EMono.core.config.game.freePos)
        {
            SE.Beep();
            return;
        }
        EMono.game.config.freePos = !EMono.game.config.freePos;
        OnToggle();
    }
References Core.config, Game.config, EMono.core, CoreConfig.GameConfig.freePos, Game.Config.freePos, CoreConfig.game, and EMono.game.
Referenced by ActionMode.DoFunc(), and HotItemToggle.OnClick().
ToggleHighlightArea()
void Scene.ToggleHighlightArea () inline
Definition at line 948 of file Scene.cs.
    {
        EMono.game.config.highlightArea = !EMono.game.config.highlightArea;
        OnToggle();
    }
References Game.config, EMono.game, and Game.Config.highlightArea.
ToggleLight()
void Scene.ToggleLight () inline
Definition at line 887 of file Scene.cs.
    {
        EMono.game.config.buildLight = !EMono.game.config.buildLight;
        OnToggle();
    }
References Game.Config.buildLight, Game.config, and EMono.game.
Referenced by ActionMode.DoFunc(), and HotItemToggle.OnClick().
ToggleMuteBGM()
void Scene.ToggleMuteBGM () inline
Definition at line 975 of file Scene.cs.
    {
        EMono.Sound.ToggleMute(EMono.core.config.sound.volumeBGM);
        SE.ClickGeneral();
        WidgetSystemIndicator.Refresh();
        if (!EMono.Sound.muteBGM)
        {
            EMono.core.config.ApplyVolume();
        }
    }
References CoreConfig.ApplyVolume(), Core.config, EMono.core, WidgetSystemIndicator.Refresh(), CoreConfig.sound, EMono.Sound, and CoreConfig.SoundSetting.volumeBGM.
Referenced by HotItemToggle.OnClick(), and ActionMode.UpdateInput().
ToggleRoof()
void Scene.ToggleRoof () inline
Definition at line 921 of file Scene.cs.
    {
        EMono.game.config.noRoof = !EMono.game.config.noRoof;
        OnToggle();
    }
References Game.config, EMono.game, and Game.Config.noRoof.
Referenced by HotItemToggle.OnClick().
ToggleShowRoof()
void Scene.ToggleShowRoof () inline
Definition at line 881 of file Scene.cs.
    {
        EMono.game.config.showRoof = !EMono.game.config.showRoof;
        OnToggle();
    }
References Game.config, EMono.game, and Game.Config.showRoof.
Referenced by ActionMode.DoFunc(), and HotItemToggle.OnClick().
ToggleShowWall()
void Scene.ToggleShowWall () inline
Definition at line 915 of file Scene.cs.
    {
        EMono.game.config.showWall = !EMono.game.config.showWall;
        OnToggle();
    }
References Game.config, EMono.game, and Game.Config.showWall.
Referenced by ActionMode.DoFunc(), and HotItemToggle.OnClick().
ToggleSlope()
void Scene.ToggleSlope () inline
Definition at line 927 of file Scene.cs.
    {
        EMono.game.config.slope = !EMono.game.config.slope;
        OnToggle();
        skipAnime = true;
    }
References Game.config, EMono.game, and Game.Config.slope.
Referenced by ActionMode.DoFunc(), and HotItemToggle.OnClick().
ToggleSnapFreePos()
void Scene.ToggleSnapFreePos () inline
Definition at line 893 of file Scene.cs.
    {
        if (!EMono.core.config.game.freePos)
        {
            SE.Beep();
            return;
        }
        EMono.game.config.snapFreePos = !EMono.game.config.snapFreePos;
        OnToggle();
    }
References Core.config, Game.config, EMono.core, CoreConfig.GameConfig.freePos, CoreConfig.game, EMono.game, and Game.Config.snapFreePos.
Referenced by ActionMode.DoFunc(), and HotItemToggle.OnClick().
ToggleTilt()
void Scene.ToggleTilt () inline
Definition at line 934 of file Scene.cs.
    {
        if (EMono._zone.IsRegion)
        {
            EMono.game.config.tiltRegion = !EMono.game.config.tiltRegion;
        }
        else
        {
            EMono.game.config.tilt = !EMono.game.config.tilt;
        }
        EMono.screen.RefreshTilt();
        OnToggle();
    }
References EMono._zone, Game.config, EMono.game, Spatial.IsRegion, BaseGameScreen.RefreshTilt(), EMono.screen, Game.Config.tilt, and Game.Config.tiltRegion.
TryWarnLinuxMod()
void Scene.TryWarnLinuxMod () inline
Definition at line 167 of file Scene.cs.
    {
        if (!EMono.core.config.ignoreLinuxModWarning)
        {
            Dialog.TryWarn("warn_linuxMod", delegate
            {
                Application.OpenURL(Lang.isJP ? "https://ylvania.org/elin_dev.html" : "https://ylvania.org/elin_dev_e.html");
            }, yes: false);
        }
    }
References Core.config, EMono.core, CoreConfig.ignoreLinuxModWarning, Lang.isJP, and Dialog.TryWarn().
Referenced by MiniGame.Activate().
TryWarnMacScreen()
void Scene.TryWarnMacScreen () inline
Definition at line 156 of file Scene.cs.
    {
        if (!EMono.core.config.ignoreParallelsWarning && SystemInfo.graphicsDeviceName.Contains("Parallels Display"))
        {
            Dialog.TryWarn("warn_parallels", delegate
            {
                Application.OpenURL(Lang.isJP ? "https://ylvania.org/elin_dev.html" : "https://ylvania.org/elin_dev_e.html");
            }, yes: false);
        }
    }
References Core.config, EMono.core, CoreConfig.ignoreParallelsWarning, Lang.isJP, and Dialog.TryWarn().
Referenced by Init().
UpdateCursor()
void Scene.UpdateCursor () inline
Definition at line 751 of file Scene.cs.
    {
        CursorSystem.position = EInput.mposWorld;
        CursorSystem.position.z = -100f;
        if (EMono.core.IsGameStarted)
        {
            CursorSystem.posOrigin = EMono.screen.position.SetZ(-100f);
            actionMode.OnUpdateCursor();
        }
        else
        {
            CursorSystem.SetCursor();
        }
    }
References EMono.core, Core.IsGameStarted, EInput.mposWorld, ActionMode.OnUpdateCursor(), BaseGameScreen.position, EMono.screen, and CursorSystem.SetCursor().
Referenced by ActionMode.Activate(), and OnUpdate().
UpdateTimeRatio()
void Scene.UpdateTimeRatio () inline
Definition at line 766 of file Scene.cs.
    {
        float num = ((EMono._map.config.hour != -1) ? ((float)EMono._map.config.hour) : ((float)EMono.world.date.hour + (float)EMono.world.date.min / 60f));
        if (num > 12f)
        {
            num = 24f - num;
        }
        timeRatio = Mathf.Clamp(num * 100f / 24f * 0.01f + EMono.setting.dayRatioMod, 0f, 1f);
    }
References EMono._map, Map.config, World.date, GameSetting.dayRatioMod, MapConfig.hour, Date.min, EMono.setting, and EMono.world.
Referenced by Init(), and OnUpdate().
Member Data Documentation
actionMode
ActionMode Scene.actionMode
Definition at line 79 of file Scene.cs.
Referenced by Chara._Move(), AM_Sim._OnUpdateInput(), ActionMode.Activate(), BaseWidgetNotice.Add(), Recipe.Build(), RecipeCard.Build(), RecipeCard.BuildIngredientList(), HotItemHeld.CanChangeHeightByWheel(), RecipeCard.Craft(), BaseGameScreen.Draw(), BaseTileMap.Draw(), TileMapElona.Draw(), BaseTileMap.DrawTile(), Map.DropBlockComponent(), HotItemActionMode.Execute(), TileTypeWallHang.GetDesiredDir(), ActionMode.GetHintText(), TaskBuild.GetHitResult(), TaskMoveInstalled.GetHitResult(), BaseTileMap.GetThingPosition(), ActionMode.InputMovement(), Widget.Config.IsInRightMode(), Widget.IsInRightMode(), Point.ListCards(), Map.MineObj(), UI.OnChangeLayer(), HotItemSpeed.OnClick(), Area.OnHoverArea(), OnKillGame(), Recipe.OnRenderMarker(), OnUpdate(), LayerMiniGame.OnUpdateInput(), BuildMenu.Refresh(), BuildMenu.RefreshCategoryArea(), BaseTileSelector.RefreshMouseInfo(), Card.RenderMarker(), NoGoal.Run(), Chara.SetAIImmediate(), Card.SetFreePos(), HotItemActionMode.ShouldHighlight(), PointTarget.ShouldIgnore(), HotItemContext.Show(), ToggleBirdView(), Core.Update(), WidgetSearch.Update(), PointTarget.Update(), ActionMode.UpdateInput(), CoreDebug.UpdateInput(), and ActionHint.UpdateText().
audioListener
AudioListener Scene.audioListener
Definition at line 35 of file Scene.cs.
bg
GameSetting.RenderSetting.MapBGSetting Scene.bg
Definition at line 124 of file Scene.cs.
Referenced by BaseTileMap.Draw().
blizzards
ParticleSystem [] Scene.blizzards
Definition at line 67 of file Scene.cs.
Referenced by BaseGameScreen.RefreshWeather(), and GameScreenElona.RefreshWeather().
blossom
ParticleSystem Scene.blossom
Definition at line 59 of file Scene.cs.
Referenced by BaseGameScreen.RefreshWeather(), and GameScreenElona.RefreshWeather().
blossoms
ParticleSystem [] Scene.blossoms
Definition at line 65 of file Scene.cs.
Referenced by BaseGameScreen.Activate(), BaseGameScreen.RefreshWeather(), and GameScreenElona.RefreshWeather().
bubble
ParticleSystem Scene.bubble
Definition at line 63 of file Scene.cs.
Referenced by Init().
cam
Camera Scene.cam
Definition at line 37 of file Scene.cs.
Referenced by CoreConfig.ApplyGrading(), TileMapElona.Draw(), TileSelectorElona.OnRenderTile(), EloMapTileSelector.OnUpdateInput(), TileSelectorElona.OnUpdateInput(), PostEffectProfile.OnValidate(), and BaseGameScreen.RefreshScreenSize().
camSupport
CameraSupport Scene.camSupport
Definition at line 41 of file Scene.cs.
Referenced by BaseTileMap.Draw(), TileMapElona.Draw(), RenderRow.GetRenderParam(), WidgetArtTool.OnActivate(), Core.OnChangeResolution(), ConBlind.OnRemoved(), ConBlind.OnStart(), BaseGameScreen.RefreshScreenSize(), CardRenderer.RenderToRenderCam(), and RenderData.RenderToRenderCam().
camTreasure
Camera Scene.camTreasure
Definition at line 39 of file Scene.cs.
Referenced by LayerTreasureMap.SetMap().
ClickPoint
Point Scene.ClickPoint = new Point() static
Definition at line 23 of file Scene.cs.
Referenced by AM_Sim._OnUpdateInput().
damageTextRenderer
DamageTextRenderer Scene.damageTextRenderer = new DamageTextRenderer()
Definition at line 109 of file Scene.cs.
Referenced by Card.DamageHP(), and OnUpdate().
dictActorEx
Dictionary<Card, ActorEx> Scene.dictActorEx = new Dictionary<Card, ActorEx>()
Definition at line 144 of file Scene.cs.
elomapActor
EloMapActor Scene.elomapActor
Definition at line 101 of file Scene.cs.
Referenced by Zone.Activate(), Region.CanCreateZone(), Zone.GetProfile(), EloMap.GetRoadDist(), UI.Hide(), Region.InitElomap(), BaseGameScreen.ModTargetZoomIndex(), Region.OnActivate(), MapGenRegion.OnGenerateTerrain(), OnKillGame(), OnUpdate(), Weather.RefreshWeather(), LayerTreasureMap.SetMap(), RegionPoint.SetRegionPoint(), UI.Show(), and WidgetDebug.UpdateText().
ether
ParticleSystem Scene.ether
Definition at line 53 of file Scene.cs.
Referenced by BaseGameScreen.Activate(), BaseGameScreen.RefreshWeather(), and GameScreenElona.RefreshWeather().
etherBlossom
ParticleSystem Scene.etherBlossom
Definition at line 61 of file Scene.cs.
Referenced by Init().
filterRain
CameraFilterPack_Atmosphere_Rain Scene.filterRain
Definition at line 77 of file Scene.cs.
firefly
VFX Scene.firefly
Definition at line 43 of file Scene.cs.
Referenced by BaseGameScreen.Activate(), and BaseGameScreen.RefreshSky().
fireflyNight
VFX Scene.fireflyNight
Definition at line 45 of file Scene.cs.
Referenced by BaseGameScreen.Activate(), and BaseGameScreen.RefreshSky().
flock
FlockController Scene.flock
Definition at line 69 of file Scene.cs.
Referenced by BaseGameScreen.Activate(), BaseGameScreen.Draw(), Init(), AM_Bird.OnActivate(), OnKillGame(), AM_Bird.OnUpdateInput(), BaseGameScreen.RefreshAll(), and HotItemContext.Show().
godray
ParticleSystem Scene.godray
Definition at line 55 of file Scene.cs.
Referenced by OnUpdate(), BaseGameScreen.RefreshWeather(), GameScreenElona.RefreshWeather(), and BaseGameScreen.UpdateShaders().
godrayDust
ParticleSystem Scene.godrayDust
Definition at line 57 of file Scene.cs.
Referenced by BaseGameScreen.RefreshWeather(), and GameScreenElona.RefreshWeather().
hideBalloon
bool Scene.hideBalloon
Definition at line 147 of file Scene.cs.
Referenced by ActionMode.Activate(), OnKillGame(), and HotItemToggle.ShouldHighlight().
HitPoint
Point Scene.HitPoint = new Point() static
Definition at line 21 of file Scene.cs.
Referenced by AM_Sim._OnUpdateInput(), PointTarget.CycleTarget(), LayerInspect.GetMenuItems(), UIInspector.InspectUnderMouse(), BaseTileSelector.OnUpdate(), LayerInspect.OnUpdateInput(), BaseTileSelector.RefreshMouseInfo(), BaseTileSelector.RefreshSummary(), ActionMode.RotateUnderMouse(), LayerInteraction.Show(), LayerInteraction.TryShow(), GameUpdater.Update(), ActionMode.UpdateInput(), CoreDebug.UpdateInput(), and WidgetDebug.UpdateText().
isAnnounced
bool Scene.isAnnounced static
Definition at line 19 of file Scene.cs.
Referenced by Init().
loadedPrefabs
List<GameObject> Scene.loadedPrefabs = new List<GameObject>()
Definition at line 133 of file Scene.cs.
matFloorEx
Material Scene.matFloorEx
Definition at line 107 of file Scene.cs.
Referenced by BaseGameScreen.RefreshAll().
mode
Mode Scene.mode
Definition at line 127 of file Scene.cs.
Referenced by Init(), and OnUpdate().
mouseTarget
PointTarget Scene.mouseTarget = new PointTarget()
Definition at line 135 of file Scene.cs.
Referenced by AM_Adv._OnUpdateInput(), ActPlan._Update(), ActRush.CanPerform(), HotItemHeld.CanRotate(), ActionMode.DoFunc(), AM_MoveInstalled.GetTarget(), AM_MoveInstalled.HitTest(), AM_MoveInstalled.InputWheel(), UIInspector.InspectUnderMouse(), OnKillGame(), ActBolt.OnMarkMapHighlights(), ActRush.OnMarkMapHighlights(), AM_MoveInstalled.OnRenderTile(), AM_Inspect.OnUpdateInput(), ActRush.Perform(), ActPlan.Item.Perform(), WidgetMouseover.Refresh(), Cell.RotateAll(), Player.TargetRanged(), HotItemHeld.TrySetAct(), LayerInteraction.TryShow(), ActionMode.UpdateInput(), CoreDebug.UpdateInput(), and AM_Adv.UpdateLangWheel().
passes
MeshPass [] Scene.passes
Definition at line 121 of file Scene.cs.
Referenced by MeshPass.Refresh(), and CoreDebug.Test_Filter().
paused
bool Scene.paused
Definition at line 140 of file Scene.cs.
Referenced by GameUpdater.FixedUpdate(), OnUpdate(), Chara.SetAIImmediate(), and GameUpdater.Update().
popper
PopperManager Scene.popper
Definition at line 99 of file Scene.cs.
Referenced by DamageTextRenderer.Flush(), and BaseStats.PopText().
posAudioListener
Vector3 Scene.posAudioListener
Definition at line 33 of file Scene.cs.
Referenced by BaseGameScreen.RefreshPosition(), and GameScreenElona.RefreshPosition().
profile
SceneProfile Scene.profile
Definition at line 75 of file Scene.cs.
Referenced by BaseGameScreen.Activate(), ApplyZoneConfig(), Card.CalculateFOV(), Card.CreateFov(), BaseTileMap.Draw(), TileMapElona.Draw(), Card.GetLightPower(), BaseTileMap.OnActivate(), EloMapActor.OnChangeHour(), VFX.OnChangeHour(), PCOrbit.OnChangeMin(), UIGameBG.Refresh(), BaseGameScreen.RefreshAll(), BaseGameScreen.RefreshGrading(), BaseGameScreen.RefreshSky(), BaseGameScreen.RefreshWeather(), Fov.SetVisible(), and BaseGameScreen.UpdateShaders().
psFey
ParticleSystem Scene.psFey
Definition at line 119 of file Scene.cs.
Referenced by BaseTileMap.DrawTile().
psFoot
ParticleSystem Scene.psFoot
Definition at line 111 of file Scene.cs.
Referenced by Chara._Move().
psRainSplash
ParticleSystem Scene.psRainSplash
Definition at line 115 of file Scene.cs.
Referenced by GameUpdater.Update100ms().
psRainSplashWater
ParticleSystem Scene.psRainSplashWater
Definition at line 117 of file Scene.cs.
Referenced by GameUpdater.Update100ms().
psSmoke
ParticleSystem Scene.psSmoke
Definition at line 113 of file Scene.cs.
Referenced by Chara._Move().
rain
ParticleSystem Scene.rain
Definition at line 49 of file Scene.cs.
Referenced by BaseGameScreen.Activate(), BaseGameScreen.RefreshWeather(), and GameScreenElona.RefreshWeather().
screenElin
GameScreen Scene.screenElin
Definition at line 93 of file Scene.cs.
Referenced by RefractionProfile.Apply(), PostEffectProfile.Apply(), LiquidProfile.Apply(), CoreDebug.COM_PlayStartDrama(), CardRenderer.Draw(), TextureManager.Init(), Init(), CardActor.OnRender(), CharaActorPCC.OnRender(), EffectIRenderer.OnUpdate(), DramaManager.ParseLine(), and Chara.SetTempHand().
screenElona
GameScreenElona Scene.screenElona
Definition at line 95 of file Scene.cs.
Referenced by Init(), EloMapActor.Initialize(), LayerTravel.OnInit(), and Point.PositionTopdownTreasure().
screenNoMap
GameScreenNoMap Scene.screenNoMap
Definition at line 97 of file Scene.cs.
Referenced by Core.Awake(), and Init().
sfxEther
SoundSource Scene.sfxEther
Definition at line 91 of file Scene.cs.
sfxFire
SoundSource Scene.sfxFire
Definition at line 89 of file Scene.cs.
Referenced by BaseGameScreen.Activate(), BaseTileMap.Draw(), and TileMapElona.Draw().
sfxRain
SoundSource Scene.sfxRain
Definition at line 81 of file Scene.cs.
Referenced by BaseGameScreen.Activate(), BaseGameScreen.RefreshWeather(), and GameScreenElona.RefreshWeather().
sfxSea
SoundSource Scene.sfxSea
Definition at line 87 of file Scene.cs.
Referenced by BaseGameScreen.Activate(), BaseGameScreen.RefreshWeather(), and GameScreenElona.RefreshWeather().
sfxUnderwater
SoundSource Scene.sfxUnderwater
Definition at line 85 of file Scene.cs.
Referenced by BaseGameScreen.Activate().
sfxWind
SoundSource Scene.sfxWind
Definition at line 83 of file Scene.cs.
Referenced by BaseGameScreen.Activate(), BaseGameScreen.RefreshScreenSize(), and GameScreenElona.RefreshWeather().
skipAnime
bool Scene.skipAnime static
Definition at line 25 of file Scene.cs.
Referenced by BaseGameScreen.Draw(), Init(), and CharaRenderer.UpdatePosition().
skyBG
MeshRenderer Scene.skyBG
Definition at line 71 of file Scene.cs.
Referenced by GameScreenElona.OnActivate().
skyPlane
MeshRenderer Scene.skyPlane
Definition at line 73 of file Scene.cs.
snow
ParticleSystem Scene.snow
Definition at line 51 of file Scene.cs.
Referenced by BaseGameScreen.Activate(), BaseGameScreen.RefreshWeather(), and GameScreenElona.RefreshWeather().
srTarget
SpriteRenderer Scene.srTarget
Definition at line 103 of file Scene.cs.
star
VFX Scene.star
Definition at line 47 of file Scene.cs.
Referenced by BaseGameScreen.Activate(), and BaseGameScreen.RefreshSky().
syncFrame
long Scene.syncFrame
Definition at line 142 of file Scene.cs.
Referenced by TaskDesignation.Draw().
syncList
List<ISyncScreen> Scene.syncList = new List<ISyncScreen>()
Definition at line 137 of file Scene.cs.
Referenced by Clear(), TaskDesignation.Draw(), BaseTileMap.OnActivate(), BaseListPeople.OnClick(), and WidgetDebug.UpdateText().
test
Vector2 [] Scene.test
Definition at line 17 of file Scene.cs.
tileset
Tileset Scene.tileset
Definition at line 105 of file Scene.cs.
Referenced by TextureData.IsValid().
timeRatio
float Scene.timeRatio
Definition at line 130 of file Scene.cs.
Referenced by BaseGameScreen.Draw(), BaseTileMap.Draw(), TileMapElona.Draw(), Card.GetLightPower(), EloMapActor.OnChangeHour(), VFX.OnChangeHour(), PCOrbit.OnChangeMin(), OnUpdate(), UIGameBG.Refresh(), BaseGameScreen.RefreshGrading(), and LayerTreasureMap.SetMap().
transAudio
Transform Scene.transAudio
Definition at line 31 of file Scene.cs.
Referenced by Point.PlaySound(), and ESoundSource.Refresh().
transBlizzard
Transform Scene.transBlizzard
Definition at line 29 of file Scene.cs.
transFocus
Transform Scene.transFocus
Definition at line 27 of file Scene.cs.
Referenced by AM_Bird.OnUpdateInput().
Property Documentation
elomap
EloMap Scene.elomap get
Definition at line 149 of file Scene.cs.
Referenced by Chara._Move(), Zone.ClaimZone(), Region.CreateRandomSite(), Zone.Destroy(), Spatial.Dist(), Player.EnterLocalZone(), TraitScrollMapTreasure.GetDest(), RankedZone.GetSprite(), Region.ListTravelZones(), Region.OnActivate(), TraitDeedRelocate.OnRead(), Point.PositionTopdownTreasure(), LayerTravel.Refresh(), RegionPoint.SetRegionPoint(), Chara.Tick(), Point.ToRegionPos(), TraitMapBoard.TrySetAct(), GameUpdater.Update(), and PointTarget.Update().
The documentation for this class was generated from the following file:
Elin/Scene.cs