Elin Decompiled Documentation: InspectGroupArea Class Reference
InspectGroupArea Class Reference
Public Member Functions
override void OnSetActions ()
Public Member Functions inherited from InspectGroup< Area >
bool CanInspect ()
virtual bool Contains (IInspect t)
string GetName ()
virtual void SetActions ()
sealed override void SetActions ()
virtual void OnSetActions ()
Item Add (string text, string idSprite, Action action, bool sound=false, int priority=0, bool auto=false)
Item Add (string text, string idSprite, Action< T > action, bool sound=false, int priority=0, bool auto=false)
Properties
override string MultiName [get]
Properties inherited from InspectGroup< Area >
IInspect FirstTarget [get]
new T FirstTarget [get]
bool Solo [get]
virtual string MultiName [get]
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Additional Inherited Members
Static Public Member Functions inherited from InspectGroup< Area >
static InspectGroup Create (IInspect t)
Static Public Member Functions inherited from EClass
static int rndSeed (int a, int seed)
static int rnd (long a)
static int rnd (int a)
static int curve (int a, int start, int step, int rate=75)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Public Attributes inherited from InspectGroup< Area >
Type type
List< Item > actions
List< IInspect > targets
Static Public Attributes inherited from EClass
static Core core
Detailed Description
Definition at line 3 of file InspectGroupArea.cs.
Member Function Documentation
OnSetActions()
override void InspectGroupArea.OnSetActions () inline virtual
Reimplemented from InspectGroup< Area >.
Definition at line 7 of file InspectGroupArea.cs.
    {
        Area first = base.FirstTarget;
        Add("expandArea", "", (Action)delegate
        {
            ActionMode.ExpandArea.Activate(first);
        }, sound: false, 0, auto: false);
        Add("shrinkArea", "", (Action)delegate
        {
            ActionMode.ExpandArea.Activate(first, _shrink: true);
        }, sound: false, 0, auto: false);
        Add("delete", "", (Action)delegate
        {
            SE.Play("trash");
            EClass._map.rooms.RemoveArea(first);
        }, sound: false, 0, auto: false);
    }
References EClass._map, AM_ExpandArea.Activate(), InspectGroup< Area >.Add(), ActionMode.ExpandArea, RoomManager.RemoveArea(), and Map.rooms.
Property Documentation
MultiName
override string InspectGroupArea.MultiName get
Definition at line 5 of file InspectGroupArea.cs.
The documentation for this class was generated from the following file:
Elin/InspectGroupArea.cs