Elin Decompiled Documentation: UIContextMenuPopper Class Reference
UIContextMenuPopper Class Reference
Public Member Functions
virtual void OnPointerEnter (PointerEventData data)
virtual void OnPointerExit (PointerEventData data)
void Pop ()
void Depop ()
UIContextMenu CreateMenu ()
void PositionMenu ()
Public Attributes
RectTransform _rect
bool isPointerOver
UIContextMenu parent
string id
UIContextMenu menu
UIContextMenu defaultMenu
Vector2 margin = new Vector2(8f, 10f)
float bottomFix
Public Attributes inherited from UIContextMenuItem
Text textName
Button button
Toggle toggle
Slider slider
Text textSlider
Private Member Functions
void Awake ()
void Update ()
Detailed Description
Definition at line 5 of file UIContextMenuPopper.cs.
Member Function Documentation
Awake()
void UIContextMenuPopper.Awake () inline private
Definition at line 27 of file UIContextMenuPopper.cs.
    {
        _rect = base.transform as RectTransform;
    }
References _rect.
CreateMenu()
UIContextMenu UIContextMenuPopper.CreateMenu () inline
Definition at line 80 of file UIContextMenuPopper.cs.
    {
        menu = UnityEngine.Object.Instantiate(defaultMenu);
        menu.transform.SetParent(base.transform, worldPositionStays: false);
        menu.popper = this;
        menu.depth = parent.depth + 1;
        menu.parent = parent;
        if (parent.system)
        {
            menu.bg.material = parent.matBlur;
        }
        return menu;
    }
References defaultMenu, UIContextMenu.matBlur, menu, parent, and UIContextMenu.system.
Referenced by UIContextMenu.AddChild(), and Pop().
Depop()
void UIContextMenuPopper.Depop () inline
Definition at line 75 of file UIContextMenuPopper.cs.
    {
        menu.Hide();
    }
References UIContextMenu.Hide(), and menu.
Referenced by Pop(), and Update().
OnPointerEnter()
virtual void UIContextMenuPopper.OnPointerEnter (PointerEventData data) inline virtual
Definition at line 32 of file UIContextMenuPopper.cs.
    {
        isPointerOver = true;
    }
References isPointerOver.
OnPointerExit()
virtual void UIContextMenuPopper.OnPointerExit (PointerEventData data) inline virtual
Definition at line 37 of file UIContextMenuPopper.cs.
    {
        isPointerOver = false;
    }
References isPointerOver.
Pop()
void UIContextMenuPopper.Pop () inline
Definition at line 54 of file UIContextMenuPopper.cs.
    {
        if (!UIContextMenu.Current.hideOnMouseLeave)
        {
            UIContextMenuPopper[] componentsInChildren = UIContextMenu.Current.GetComponentsInChildren<UIContextMenuPopper>();
            for (int i = 0; i < componentsInChildren.Length; i++)
            {
                componentsInChildren[i].Depop();
            }
        }
        if (menu == null)
        {
            CreateMenu();
        }
        menu.Show();
        if (parent != null)
        {
            PositionMenu();
        }
    }
References CreateMenu(), UIContextMenu.Current, Depop(), UIContextMenu.hideOnMouseLeave, menu, parent, PositionMenu(), and UIContextMenu.Show().
Referenced by Update().
PositionMenu()
void UIContextMenuPopper.PositionMenu () inline
Definition at line 94 of file UIContextMenuPopper.cs.
    {
        RectTransform rect = menu._rect;
        rect.RebuildLayout(recursive: true);
        Vector2 zero = Vector2.zero;
        zero.x = _rect.sizeDelta.x - margin.x;
        zero.y = _rect.sizeDelta.y * -1f - margin.y;
        rect.pivot = new Vector2(0f, 1f);
        rect.anchoredPosition = zero;
        if (parent.transform.position.x + parent._rect.sizeDelta.x * (1f - parent._rect.pivot.x) > (float)Screen.width - rect.sizeDelta.x || menu.alwaysPopLeft)
        {
            zero.x = margin.x;
            rect.pivot = new Vector2(1f, menu._rect.pivot.y);
        }
        zero.x = (int)zero.x;
        zero.y = (int)zero.y;
        rect.anchoredPosition = zero;
        if (rect.position.y - rect.sizeDelta.y * BaseCore.Instance.uiScale < 0f)
        {
            Vector3 position = rect.position;
            position.y = rect.sizeDelta.y * BaseCore.Instance.uiScale;
            rect.position = position;
        }
    }
References UIContextMenu._rect, UIContextMenu.alwaysPopLeft, BaseCore.Instance, margin, menu, parent, and BaseCore.uiScale.
Referenced by Pop().
Update()
void UIContextMenuPopper.Update () inline private
Definition at line 42 of file UIContextMenuPopper.cs.
    {
        if (isPointerOver && !menu.gameObject.activeSelf && parent.timeSinceOpen > 0.1f && !Input.GetMouseButton(0))
        {
            Pop();
        }
        if (!isPointerOver && !Input.GetMouseButton(0) && UIContextMenu.Current.hideOnMouseLeave && !menu.isPointerOver)
        {
            Depop();
        }
    }
References UIContextMenu.Current, Depop(), UIContextMenu.hideOnMouseLeave, UIContextMenu.isPointerOver, isPointerOver, menu, parent, Pop(), and UIContextMenu.timeSinceOpen.
Member Data Documentation
_rect
RectTransform UIContextMenuPopper._rect
Definition at line 8 of file UIContextMenuPopper.cs.
Referenced by Awake().
bottomFix
float UIContextMenuPopper.bottomFix
Definition at line 25 of file UIContextMenuPopper.cs.
defaultMenu
UIContextMenu UIContextMenuPopper.defaultMenu
Definition at line 21 of file UIContextMenuPopper.cs.
Referenced by CreateMenu().
id
string UIContextMenuPopper.id
Definition at line 17 of file UIContextMenuPopper.cs.
Referenced by UIContextMenu.AddOrGetChild().
isPointerOver
bool UIContextMenuPopper.isPointerOver
Definition at line 11 of file UIContextMenuPopper.cs.
Referenced by OnPointerEnter(), OnPointerExit(), UIContextMenu.Update(), and Update().
margin
Vector2 UIContextMenuPopper.margin = new Vector2(8f, 10f)
Definition at line 23 of file UIContextMenuPopper.cs.
Referenced by PositionMenu().
menu
UIContextMenu UIContextMenuPopper.menu
Definition at line 19 of file UIContextMenuPopper.cs.
Referenced by UIContextMenu.AddChild(), UIContextMenu.AddOrGetChild(), CreateMenu(), Depop(), Pop(), PositionMenu(), and Update().
parent
UIContextMenu UIContextMenuPopper.parent
Definition at line 14 of file UIContextMenuPopper.cs.
Referenced by UIContextMenu.AddButton(), CreateMenu(), Pop(), PositionMenu(), and Update().
The documentation for this class was generated from the following file:
Elin/Plugins.UI/UIContextMenuPopper.cs