Elin Decompiled Documentation: CardActor Class Reference
CardActor Class Reference
Public Types
enum Type { Default , Boat , Canvas , MultiSprite }
Public Member Functions
void SetOwner (Card t)
virtual void OnSetOwner ()
virtual void IdleFrame ()
virtual void NextFrame ()
virtual void NextDir ()
virtual int GetFrame ()
virtual void OnRender (RenderParam p)
virtual void RefreshSprite ()
virtual void Kill ()
Public Attributes
Card owner
SpriteRenderer sr
SpriteRenderer sr2
SpriteReplacerAnimation srAnime
MaterialPropertyBlock mpb
MaterialPropertyBlock mpb2
CardActor.Type type
Static Protected Attributes
static Vector3 tempV
static Vector3 tempV2
Properties
virtual bool isPCC [get]
virtual int currentDir [get]
Properties inherited from EMono
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SoundManager Sound [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static CoreDebug debug [get]
Private Member Functions
void Awake ()
Private Attributes
float destLiquid
float spriteTimer
int spriteIndex
Vector3 originalScale
Additional Inherited Members
Static Public Member Functions inherited from EMono
static int rnd (int a)
Static Public Attributes inherited from EMono
static Core core
Detailed Description
Definition at line 4 of file CardActor.cs.
Member Enumeration Documentation
Type
enum CardActor.Type
Enumerator
Default
Boat
Canvas
MultiSprite
Definition at line 282 of file CardActor.cs.
    {
        Default,
        Boat,
        Canvas,
        MultiSprite
    }
Member Function Documentation
Awake()
void CardActor.Awake () inline private
Definition at line 22 of file CardActor.cs.
    {
        this.originalScale = base.transform.localScale;
    }
GetFrame()
virtual int CardActor.GetFrame () inline virtual
Reimplemented in CharaActorPCC.
Definition at line 77 of file CardActor.cs.
    {
        return 0;
    }
Referenced by CardRenderer.Draw(), CharaRenderer.DrawHat(), and CharaRenderer.DrawHeld().
IdleFrame()
virtual void CardActor.IdleFrame () inline virtual
Reimplemented in CharaActorPCC.
Definition at line 65 of file CardActor.cs.
    {
    }
Referenced by CardRenderer.IdleFrame(), CharaActor.OnSetOwner(), and CharaRenderer.UpdatePosition().
Kill()
virtual void CardActor.Kill () inline virtual
Reimplemented in CharaActorPCC.
Definition at line 251 of file CardActor.cs.
    {
        PoolManager.Despawn(base.transform);
    }
Referenced by CardRenderer.KillActor().
NextDir()
virtual void CardActor.NextDir () inline virtual
Reimplemented in CharaActorPCC.
Definition at line 73 of file CardActor.cs.
    {
    }
Referenced by CardRenderer.NextDir().
NextFrame()
virtual void CardActor.NextFrame () inline virtual
Reimplemented in CharaActor, and CharaActorPCC.
Definition at line 69 of file CardActor.cs.
    {
    }
Referenced by CardRenderer.NextFrame(), and CharaRenderer.UpdatePosition().
OnRender()
virtual void CardActor.OnRender (RenderParam p) inline virtual
Reimplemented in CharaActorPCC.
Definition at line 82 of file CardActor.cs.
    {
        this.SetActive(true);
        SubPassData current = SubPassData.Current;
        RenderData data = this.owner.renderer.data;
        if (data.useOffsetBack && this.owner != EMono.pc.held && (data.symmetry ? (p.dir % 2 == 1) : (p.dir == 1 || p.dir == 2)))
        {
            CardActor.tempV.x = p.x + data.offsetBack.x + current.offset.x;
            CardActor.tempV.y = p.y + data.offsetBack.y + current.offset.y;
            CardActor.tempV.z = p.z + data.offsetBack.z + current.offset.z;
        }
        else
        {
            CardActor.tempV.x = p.x + data.offset.x + current.offset.x;
            CardActor.tempV.y = p.y + data.offset.y + current.offset.y;
            CardActor.tempV.z = p.z + data.offset.z + current.offset.z;
        }
        if (this.isPCC)
        {
            RenderDataPcc renderDataPcc = data as RenderDataPcc;
            CharaActorPCC charaActorPCC = this as CharaActorPCC;
            CardActor.tempV.x = (float)((int)(CardActor.tempV.x * 100f)) * 0.01f;
            CardActor.tempV.y = (float)((int)(CardActor.tempV.y * 100f)) * 0.01f;
            CardActor.tempV2.x = charaActorPCC.provider.vCurrent.source.size.x * current.scale.x;
            CardActor.tempV2.y = charaActorPCC.provider.vCurrent.source.size.y * current.scale.y;
            CardActor.tempV2.z = renderDataPcc._scale.z * current.scale.z;
            base.transform.localRotation = current.rotation;
        }
        else
        {
            CardActor.tempV2.x = this.originalScale.x * current.scale.x;
            CardActor.tempV2.y = this.originalScale.y * current.scale.y;
            CardActor.tempV2.z = this.originalScale.z * current.scale.z;
        }
        if (this.type == CardActor.Type.Boat)
        {
            float floatY = EMono.scene.screenElin.tileMap.floatY;
            int floatV = EMono.scene.screenElin.tileMap.floatV;
            this.sr2.transform.localPosition = new Vector3(0f, -0.005f * floatY, this.sr2.transform.localPosition.z);
            if (floatV == 1)
            {
                if (floatY < 2f)
                {
                }
            }
            else if (floatY < 3f)
            {
            }
            int index;
            if (floatV == 1)
            {
                if (floatY < 0f)
                {
                    index = 0;
                }
                else if (floatY < 3f)
                {
                    index = 1;
                }
                else
                {
                    index = 2;
                }
            }
            else if (floatY < 2f)
            {
                index = 0;
            }
            else if (floatY < 5f)
            {
                index = 3;
            }
            else
            {
                index = 2;
            }
            this.srAnime.sr.sprite = this.srAnime.data.GetSprites().TryGet(index, -1);
        }
        base.transform.position = CardActor.tempV;
        base.transform.localScale = CardActor.tempV2;
        this.destLiquid = Mathf.Lerp(this.destLiquid, (float)p.liquidLv, Core.gameDelta * (float)((this.destLiquid > (float)p.liquidLv) ? 90 : 20));
        this.mpb.SetFloat("_MatColor", p.matColor);
        this.mpb.SetFloat("_Color", p.color);
        this.mpb.SetFloat("_Liquid", this.destLiquid);
        this.sr.SetPropertyBlock(this.mpb);
        if (this.sr2)
        {
            if (this.sr2.sprite)
            {
                this.mpb2.SetTexture("_MainTex", this.sr2.sprite.texture);
            }
            this.mpb2.SetTexture("_MaskTex", this.sr.sprite.texture);
            this.mpb2.SetFloat("_MatColor", p.matColor);
            this.mpb2.SetFloat("_Color", p.color);
            this.mpb2.SetFloat("_Liquid", this.destLiquid);
            this.sr2.SetPropertyBlock(this.mpb2);
        }
        if (this.owner.sourceCard.replacer.data != null)
        {
            SpriteData data2 = this.owner.sourceCard.replacer.data;
            if (data2.frame > 1)
            {
                this.spriteTimer += Core.delta;
                if (this.spriteTimer >= data2.time)
                {
                    this.spriteTimer -= data2.time;
                    this.spriteIndex++;
                    if (this.spriteIndex >= data2.frame)
                    {
                        this.spriteIndex = 0;
                    }
                    this.sr.sprite = ((data2.spritesSnow != null && p.snow) ? data2.spritesSnow[this.spriteIndex] : data2.sprites[this.spriteIndex]);
                }
            }
        }
    }
References MeshPassParam.color, SubPassData.Current, RenderObject.data, destLiquid, RenderParam.dir, BaseTileMap.floatV, BaseTileMap.floatY, Chara.held, isPCC, RenderParam.liquidLv, MeshPassParam.matColor, mpb, mpb2, SubPassData.offset, owner, EMono.pc, Card.renderer, RenderRow.replacer, SubPassData.rotation, SubPassData.scale, EMono.scene, Scene.screenElin, MeshPassParam.snow, Card.sourceCard, spriteIndex, spriteTimer, sr, sr2, srAnime, RenderData.symmetry, tempV, tempV2, BaseGameScreen.tileMap, type, and RenderData.useOffsetBack.
Referenced by CardRenderer.Draw(), and EffectIRenderer.OnUpdate().
OnSetOwner()
virtual void CardActor.OnSetOwner () inline virtual
Reimplemented in CharaActor, and CharaActorPCC.
Definition at line 61 of file CardActor.cs.
    {
    }
Referenced by SetOwner().
RefreshSprite()
virtual void CardActor.RefreshSprite () inline virtual
Reimplemented in CharaActor, and CharaActorPCC.
Definition at line 199 of file CardActor.cs.
    {
        switch (this.type)
        {
        case CardActor.Type.Boat:
            this.sr2.SetActive(this.owner.Cell.IsFloorWater);
            break;
        case CardActor.Type.Canvas:
            if (this.owner != null && this.owner.c_textureData != null && this.sr2)
            {
                this.sr2.sprite = this.owner.GetPaintSprite();
                TraitCanvas traitCanvas = this.owner.trait as TraitCanvas;
                if (traitCanvas != null)
                {
                    this.sr2.transform.SetLocalScale(traitCanvas.Scale, traitCanvas.Scale, 1f);
                }
            }
            break;
        case CardActor.Type.MultiSprite:
            this.sr2.sprite = this.owner.GetSprite(0);
            break;
        }
        int dir = this.owner.dir;
        Sprite sprite = this.sr.sprite = (this.sr.sprite = this.owner.GetSprite(dir));
        this.sr.flipX = ((dir == 1 || dir == 3) && (this.owner.Thing == null || !this.owner.Thing.isEquipped));
        this.mpb.SetTexture("_MainTex", sprite.texture);
        Vector4 value = new Vector4(sprite.textureRect.min.x / (float)sprite.texture.width, sprite.textureRect.min.y / (float)sprite.texture.height, sprite.textureRect.max.x / (float)sprite.texture.width, sprite.textureRect.max.y / (float)sprite.texture.height);
        this.mpb.SetVector("_Rect", value);
        this.mpb.SetFloat("_PixelHeight", sprite.rect.height);
        if (this.sr2)
        {
            if (this.sr2.sprite && this.sr2.sprite.texture)
            {
                this.sr2.flipX = (dir == 1 || dir == 3);
                sprite = this.sr2.sprite;
                if (sprite)
                {
                    Rect textureRect = sprite.textureRect;
                    value = new Vector4(sprite.textureRect.min.x / (float)sprite.texture.width, sprite.textureRect.min.y / (float)sprite.texture.height, sprite.textureRect.max.x / (float)sprite.texture.width, sprite.textureRect.max.y / (float)sprite.texture.height);
                    this.mpb2.SetTexture("_MainTex", sprite.texture);
                    this.mpb2.SetVector("_Rect", value);
                    this.mpb2.SetFloat("_PixelHeight", sprite.rect.height);
                    return;
                }
            }
            else
            {
                this.sr2.sprite = null;
            }
        }
    }
References Card.c_textureData, Card.Cell, Card.dir, Card.GetPaintSprite(), Card.GetSprite(), Thing.isEquipped, Cell.IsFloorWater, mpb, mpb2, owner, TraitCanvas.Scale, sr2, Card.Thing, and type.
Referenced by CardRenderer.RefreshSprite(), and SetOwner().
SetOwner()
void CardActor.SetOwner (Card t) inline
Definition at line 27 of file CardActor.cs.
    {
        base.gameObject.SetActive(true);
        this.owner = t;
        if (this.mpb == null)
        {
            this.mpb = new MaterialPropertyBlock();
        }
        this.mpb.SetColor("_Mat", EMono.Colors.matColors.TryGetValue(t.material.alias, null).main);
        if (this.sr)
        {
            this.sr.SetPropertyBlock(this.mpb);
        }
        if (this.sr2)
        {
            if (this.mpb2 == null)
            {
                this.mpb2 = new MaterialPropertyBlock();
            }
            this.mpb2.SetColor("_Mat", Color.white);
            this.sr2.SetPropertyBlock(this.mpb2);
        }
        this.OnSetOwner();
        if (Application.isEditor)
        {
            base.gameObject.name = this.owner.Name;
        }
        if (this.type == CardActor.Type.Boat)
        {
            this.srAnime.SetData(this.owner.id + "_anime");
        }
        this.RefreshSprite();
    }
References Color, EMono.Colors, Card.id, ColorProfile.matColors, Card.material, mpb, mpb2, Card.Name, OnSetOwner(), owner, RefreshSprite(), sr, sr2, srAnime, and type.
Referenced by CardRenderer.OnEnterScreen().
Member Data Documentation
destLiquid
float CardActor.destLiquid private
Definition at line 270 of file CardActor.cs.
Referenced by OnRender().
mpb
MaterialPropertyBlock CardActor.mpb
Definition at line 264 of file CardActor.cs.
Referenced by OnRender(), CharaActor.OnSetOwner(), CharaActorPCC.OnSetOwner(), RefreshSprite(), CharaActor.RefreshSprite(), and SetOwner().
mpb2
MaterialPropertyBlock CardActor.mpb2
Definition at line 266 of file CardActor.cs.
Referenced by OnRender(), RefreshSprite(), and SetOwner().
originalScale
Vector3 CardActor.originalScale private
Definition at line 276 of file CardActor.cs.
owner
Card CardActor.owner
Definition at line 256 of file CardActor.cs.
Referenced by OnRender(), RefreshSprite(), and SetOwner().
spriteIndex
int CardActor.spriteIndex private
Definition at line 274 of file CardActor.cs.
Referenced by OnRender().
spriteTimer
float CardActor.spriteTimer private
Definition at line 272 of file CardActor.cs.
Referenced by OnRender().
sr
SpriteRenderer CardActor.sr
Definition at line 258 of file CardActor.cs.
Referenced by OnRender(), CharaActor.OnSetOwner(), CharaActorPCC.OnSetOwner(), CharaActor.RefreshSprite(), and SetOwner().
sr2
SpriteRenderer CardActor.sr2
Definition at line 260 of file CardActor.cs.
Referenced by OnRender(), RefreshSprite(), and SetOwner().
srAnime
SpriteReplacerAnimation CardActor.srAnime
Definition at line 262 of file CardActor.cs.
Referenced by OnRender(), and SetOwner().
tempV
Vector3 CardActor.tempV static protected
Definition at line 278 of file CardActor.cs.
Referenced by OnRender().
tempV2
Vector3 CardActor.tempV2 static protected
Definition at line 280 of file CardActor.cs.
Referenced by OnRender().
type
CardActor.Type CardActor.type
Definition at line 268 of file CardActor.cs.
Referenced by OnRender(), RefreshSprite(), and SetOwner().
Property Documentation
currentDir
virtual int CardActor.currentDir get
Definition at line 14 of file CardActor.cs.
    {
        get
        {
            return 0;
        }
    }
Referenced by CardRenderer.Draw(), and WidgetDebug.UpdateText().
isPCC
virtual bool CardActor.isPCC get
Definition at line 6 of file CardActor.cs.
    {
        get
        {
            return false;
        }
    }
Referenced by OnRender().
The documentation for this class was generated from the following file:
Elin/CardActor.cs