Elin Decompiled Documentation: WidgetStats Class Reference
WidgetStats Class Reference
Public Member Functions
override void _OnActivate ()
override void OnRefresh ()
Public Member Functions inherited from BaseWidgetNotice
sealed override void OnActivate ()
virtual void _OnActivate ()
void _RefreshAll ()
virtual void OnRefresh ()
ItemNotice Add (BaseNotification n, Transform parent=null)
void Remove (BaseNotification n)
override void OnFlip ()
override void OnSetContextMenu (UIContextMenu m)
void RefreshLayout ()
override void OnApplySkin ()
Public Member Functions inherited from Widget
void Test ()
bool IsInRightMode ()
void Activate ()
void RefreshOrder ()
virtual void OnActivate ()
virtual object CreateExtra ()
void Deactivate ()
virtual void OnDeactivate ()
void Close ()
void Reactivate ()
virtual void OnManagerActivate ()
virtual void OnManagerDeactivate ()
void SetAnchor (RectPosition p)
void SetPivot (RectPosition p)
virtual void OnChangePivot ()
void UpdateConfig ()
virtual void OnUpdateConfig ()
void ClampToScreen ()
virtual void OnChangeResolution ()
void OnChangePosition ()
virtual void OnChangeActionMode ()
virtual void OnFlip ()
bool IsAlignTop ()
Layer AddLayer (Layer l, Transform trans)
void RefreshTipPivotPosition ()
SkinSet GetSkin ()
SkinConfig GetSkinConfig ()
void SetSkin (int id, int v=0)
void TestSkin ()
virtual void ApplySkin ()
virtual void OnApplySkin ()
void InstantiateDeco (SkinDeco deco)
void AddDeco (SkinDeco deco)
void RemoveDeco (SkinDeco deco)
virtual bool CanShowContextMenu ()
void ShowContextMenu ()
void SetBaseContextMenu (UIContextMenu m)
virtual void OnSetContextMenu (UIContextMenu m)
void SetGridContextMenu (UIContextMenu m)
void SoundActivate ()
void OnChangeResolution ()
Static Public Member Functions
static void RefreshAll ()
Static Public Member Functions inherited from EMono
static int rnd (int a)
Public Attributes
List< NotificationCondition > conditions = new List<NotificationCondition>()
ItemNotice moldBuff
ItemNotice moldStance
Public Attributes inherited from BaseWidgetNotice
Sprite[] sprites
List< BaseNotification > list = new List<BaseNotification>()
VerticalLayoutGroup layout
VerticalLayoutGroup layout2
ItemNotice mold
Public Attributes inherited from Widget
Image imageBG
SoundData soundActivate
UIDragPanel dragPanel
RectTransform tipPivotLeft
RectTransform tipPivotRight
Static Public Attributes
static WidgetStats Instance
Static Public Attributes inherited from EMono
static Core core
Additional Inherited Members
Public Types inherited from Widget
enum WidgetType { Default , ZoomMenu }
enum State { Active , Inactive }
Protected Member Functions inherited from Widget
void ClampToScreenEnsured (Component c, Vector2 anchoredPos)
void ClampToScreen (RectTransform rect, float margin=10f)
Protected Attributes inherited from Widget
bool flip
Properties inherited from Widget
string ID [get]
Config config [get]
SkinRoot skinRoot [get]
bool IsSealed [get]
virtual bool ShowStyleMenu [get]
virtual bool AlwaysTop [get]
virtual bool IsStaticPosition [get]
virtual bool AlwaysBottom [get]
virtual Type SetSiblingAfter [get]
virtual bool ShowInBuildMode [get]
virtual bool RightClickToClose [get]
virtual bool AllowRightClickToClose [get]
Properties inherited from EMono
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SoundManager Sound [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static CoreDebug debug [get]
Detailed Description
Definition at line 3 of file WidgetStats.cs.
Member Function Documentation
_OnActivate()
override void WidgetStats._OnActivate () inline virtual
Reimplemented from BaseWidgetNotice.
Definition at line 21 of file WidgetStats.cs.
    {
        Instance = this;
        Add(new NotificationStats
        {
            stats = () => EMono.pc.hunger
        });
        Add(new NotificationStats
        {
            stats = () => EMono.pc.burden
        });
        Add(new NotificationStats
        {
            stats = () => EMono.pc.depression
        });
        Add(new NotificationStats
        {
            stats = () => EMono.pc.bladder
        });
        Add(new NotificationStats
        {
            stats = () => EMono.pc.hygiene
        });
        Add(new NotificationStats
        {
            stats = () => EMono.pc.sleepiness
        });
        Add(new NotificationStats
        {
            stats = () => EMono.pc.stamina
        });
        Add(new NotificationExceedParty());
    }
References BaseWidgetNotice.Add(), Chara.bladder, Chara.burden, Chara.depression, Chara.hunger, Chara.hygiene, Instance, EMono.pc, Chara.sleepiness, and Chara.stamina.
OnRefresh()
override void WidgetStats.OnRefresh () inline virtual
Reimplemented from BaseWidgetNotice.
Definition at line 55 of file WidgetStats.cs.
    {
        conditions.ForeachReverse(delegate(NotificationCondition a)
        {
            if (a.ShouldRemove())
            {
                conditions.Remove(a);
                Remove(a);
            }
        });
        foreach (Condition condition in EMono.pc.conditions)
        {
            if (!condition.ShowInWidget)
            {
                continue;
            }
            bool flag = true;
            foreach (NotificationCondition condition2 in conditions)
            {
                if (condition2.condition == condition)
                {
                    flag = false;
                    break;
                }
            }
            if (flag)
            {
                NotificationCondition notificationCondition = condition.CreateNotification() as NotificationCondition;
                Add(notificationCondition);
                conditions.Add(notificationCondition);
            }
        }
    }
References BaseWidgetNotice.Add(), NotificationCondition.condition, Chara.conditions, conditions, Condition.CreateNotification(), EMono.pc, NotificationCondition.ShouldRemove(), and BaseStats.ShowInWidget.
RefreshAll()
static void WidgetStats.RefreshAll () inline static
Definition at line 13 of file WidgetStats.cs.
    {
        if ((bool)Instance)
        {
            Instance._RefreshAll();
        }
    }
References BaseWidgetNotice._RefreshAll(), and Instance.
Referenced by NotificationCondition.OnClick().
Member Data Documentation
conditions
List<NotificationCondition> WidgetStats.conditions = new List<NotificationCondition>()
Definition at line 7 of file WidgetStats.cs.
Referenced by OnRefresh().
Instance
WidgetStats WidgetStats.Instance static
Definition at line 5 of file WidgetStats.cs.
Referenced by _OnActivate(), NotificationBuff.GetLayoutGroup(), NotificationBuff.GetMold(), NotificationStance.GetMold(), NotificationCondition.OnClick(), and RefreshAll().
moldBuff
ItemNotice WidgetStats.moldBuff
Definition at line 9 of file WidgetStats.cs.
Referenced by NotificationBuff.GetMold().
moldStance
ItemNotice WidgetStats.moldStance
Definition at line 11 of file WidgetStats.cs.
Referenced by NotificationStance.GetMold().
The documentation for this class was generated from the following file:
Elin/WidgetStats.cs