Elin Decompiled Documentation: PropSetCategory Class Reference
PropSetCategory Class Reference
Public Member Functions
override void ModNum (int a)
void ModSum (int a)
Public Member Functions inherited from PropSet
new void Add (Card c)
new void Remove (Card c)
virtual void ModNum (int a)
void OnChangeNum (int a)
Public Attributes
SourceCategory.Row source
PropSetCategory parent
int sum
Public Attributes inherited from PropSet
int num
Detailed Description
Definition at line 1 of file PropSetCategory.cs.
Member Function Documentation
ModNum()
override void PropSetCategory.ModNum (int a) inline virtual
Reimplemented from PropSet.
Definition at line 9 of file PropSetCategory.cs.
    {
        num += a;
        ModSum(a);
    }
References ModSum(), and PropSet.num.
ModSum()
void PropSetCategory.ModSum (int a) inline
Definition at line 15 of file PropSetCategory.cs.
    {
        if (parent != null)
        {
            parent.ModSum(a);
        }
        sum += a;
    }
References ModSum(), parent, and sum.
Referenced by ModNum(), and ModSum().
Member Data Documentation
parent
PropSetCategory PropSetCategory.parent
Definition at line 5 of file PropSetCategory.cs.
Referenced by ModSum().
source
SourceCategory.Row PropSetCategory.source
Definition at line 3 of file PropSetCategory.cs.
Referenced by WidgetStockTracker._Refresh(), Props.Init(), and ButtonResourceTrack.SetCat().
sum
int PropSetCategory.sum
Definition at line 7 of file PropSetCategory.cs.
Referenced by WidgetStockTracker._Refresh(), ModSum(), and ButtonResourceTrack.Refresh().
The documentation for this class was generated from the following file:
Elin/PropSetCategory.cs