Elin Decompiled Documentation: ColorComparer Class Reference
ColorComparer Class Reference
Static Public Member Functions
static float Compare (Color colorA, Color colorB)
Static Private Member Functions
static float Distance (float a, float b)
Detailed Description
Definition at line 3 of file ColorComparer.cs.
Member Function Documentation
Compare()
static float ColorComparer.Compare (Color colorA, Color colorB) inline static
Definition at line 5 of file ColorComparer.cs.
    {
        Lab lab = ColorConverter.RgbToLab(colorA);
        Lab lab2 = ColorConverter.RgbToLab(colorB);
        return Mathf.Sqrt(Distance(lab.L, lab2.L) + Distance(lab.A, lab2.A) + Distance(lab.B, lab2.B));
    }
References Lab.A, Lab.B, Distance(), Lab.L, and ColorConverter.RgbToLab().
Distance()
static float ColorComparer.Distance (float a, float b) inline static private
Definition at line 12 of file ColorComparer.cs.
    {
        return (a - b) * (a - b);
    }
Referenced by Compare().
The documentation for this class was generated from the following file:
Elin/Plugins.UI/ColorComparer.cs