Elin Decompiled Documentation: WidgetHP Class Reference
WidgetHP Class Reference
Classes
class Extra
Public Member Functions
override object CreateExtra ()
override void OnActivate ()
void Rebuild ()
void Refresh ()
override void OnSetContextMenu (UIContextMenu m)
Public Member Functions inherited from Widget
void Test ()
bool IsInRightMode ()
void Activate ()
void RefreshOrder ()
virtual void OnActivate ()
virtual object CreateExtra ()
void Deactivate ()
virtual void OnDeactivate ()
void Close ()
void Reactivate ()
virtual void OnManagerActivate ()
virtual void OnManagerDeactivate ()
void SetAnchor (RectPosition p)
void SetPivot (RectPosition p)
virtual void OnChangePivot ()
void UpdateConfig ()
virtual void OnUpdateConfig ()
void ClampToScreen ()
virtual void OnChangeResolution ()
void OnChangePosition ()
virtual void OnChangeActionMode ()
virtual void OnFlip ()
bool IsAlignTop ()
Layer AddLayer (Layer l, Transform trans)
void RefreshTipPivotPosition ()
SkinSet GetSkin ()
SkinConfig GetSkinConfig ()
void SetSkin (int id, int v=0)
void TestSkin ()
virtual void ApplySkin ()
virtual void OnApplySkin ()
void InstantiateDeco (SkinDeco deco)
void AddDeco (SkinDeco deco)
void RemoveDeco (SkinDeco deco)
virtual bool CanShowContextMenu ()
void ShowContextMenu ()
void SetBaseContextMenu (UIContextMenu m)
virtual void OnSetContextMenu (UIContextMenu m)
void SetGridContextMenu (UIContextMenu m)
void SoundActivate ()
void OnChangeResolution ()
SkinSet GetSkin ()
SkinConfig GetSkinConfig ()
Public Attributes
Gauge gaugeHP
Gauge gaugeMP
Gauge gaugeStamina
UIText textHP
UIText textMP
UIText textStamina
UIText textBarrier
GridLayoutGroup grid
GameObject goBarrier
Public Attributes inherited from Widget
Image imageBG
SoundData soundActivate
UIDragPanel dragPanel
RectTransform tipPivotLeft
RectTransform tipPivotRight
Properties
Extra extra [get]
Properties inherited from Widget
string ID [get]
Config config [get]
SkinRoot skinRoot [get]
bool IsSealed [get]
virtual bool ShowStyleMenu [get]
virtual bool AlwaysTop [get]
virtual bool IsStaticPosition [get]
virtual bool AlwaysBottom [get]
virtual Type SetSiblingAfter [get]
virtual bool ShowInBuildMode [get]
virtual bool RightClickToClose [get]
virtual bool AllowRightClickToClose [get]
Properties inherited from EMono
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SoundManager Sound [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static CoreDebug debug [get]
Additional Inherited Members
Public Types inherited from Widget
enum WidgetType { Default , ZoomMenu }
enum State { Active , Inactive }
Static Public Member Functions inherited from EMono
static int rnd (int a)
Static Public Attributes inherited from EMono
static Core core
Protected Member Functions inherited from Widget
void ClampToScreenEnsured (Component c, Vector2 anchoredPos)
void ClampToScreen (RectTransform rect, float margin=10f)
Protected Attributes inherited from Widget
bool flip
Detailed Description
Definition at line 5 of file WidgetHP.cs.
Member Function Documentation
CreateExtra()
override object WidgetHP.CreateExtra () inline virtual
Reimplemented from Widget.
Definition at line 42 of file WidgetHP.cs.
    {
        return new Extra();
    }
OnActivate()
override void WidgetHP.OnActivate () inline virtual
Reimplemented from Widget.
Definition at line 47 of file WidgetHP.cs.
    {
        Rebuild();
        InvokeRepeating("Refresh", 0f, 0.2f);
    }
References Rebuild().
OnSetContextMenu()
override void WidgetHP.OnSetContextMenu (UIContextMenu m) inline virtual
Reimplemented from Widget.
Definition at line 94 of file WidgetHP.cs.
    {
        UIContextMenu uIContextMenu = m.AddChild("setting");
        uIContextMenu.AddSlider("layout", (float n) => n.ToString() ?? "", extra.layout, delegate(float a)
        {
            extra.layout = (int)a;
            Rebuild();
            ClampToScreen();
        }, 0f, 2f, isInt: true);
        uIContextMenu.AddToggle("showGauge", extra.showGauge, delegate(bool a)
        {
            extra.showGauge = a;
            Refresh();
            this.RebuildLayout(recursive: true);
        });
        uIContextMenu.AddToggle("showMax", extra.showMax, delegate(bool a)
        {
            extra.showMax = a;
            Refresh();
            this.RebuildLayout(recursive: true);
        });
        uIContextMenu.AddToggle("stamina", extra.stamina, delegate(bool a)
        {
            extra.stamina = a;
            Refresh();
            this.RebuildLayout(recursive: true);
        });
        SetBaseContextMenu(m);
    }
References UIContextMenu.AddChild(), UIContextMenu.AddSlider(), UIContextMenu.AddToggle(), Widget.ClampToScreen(), extra, WidgetHP.Extra.layout, Rebuild(), Refresh(), Widget.SetBaseContextMenu(), WidgetHP.Extra.showGauge, WidgetHP.Extra.showMax, and WidgetHP.Extra.stamina.
Rebuild()
void WidgetHP.Rebuild () inline
Definition at line 53 of file WidgetHP.cs.
    {
        grid.constraintCount = extra.layout + 1;
        Refresh();
        this.RebuildLayout();
    }
References Refresh().
Referenced by OnActivate(), and OnSetContextMenu().
Refresh()
void WidgetHP.Refresh () inline
Definition at line 60 of file WidgetHP.cs.
    {
        if (!EMono.game.isLoading)
        {
            if (EMono.pc.hp > EMono.pc.MaxHP)
            {
                EMono.pc.hp = EMono.pc.MaxHP;
            }
            if (EMono.pc.mana.value > EMono.pc.mana.max)
            {
                EMono.pc.mana.value = EMono.pc.mana.max;
            }
            if (EMono.pc.stamina.value > EMono.pc.stamina.max)
            {
                EMono.pc.stamina.value = EMono.pc.stamina.max;
            }
        }
        gaugeHP.hideBar = !extra.showGauge;
        gaugeMP.hideBar = !extra.showGauge;
        gaugeStamina.hideBar = !extra.showGauge;
        gaugeStamina.SetActive(extra.stamina);
        gaugeHP.UpdateValue(EMono.pc.hp, EMono.pc.MaxHP);
        gaugeMP.UpdateValue(EMono.pc.mana.value, EMono.pc.mana.max);
        gaugeStamina.UpdateValue(EMono.pc.stamina.value, EMono.pc.stamina.max);
        Color c = EMono.Colors.Dark.gradientHP.Evaluate((float)EMono.pc.hp / (float)EMono.pc.MaxHP);
        gaugeHP.textNow.text = "".TagColor(c, EMono.pc.hp.ToString() ?? "") + (extra.showMax ? ("/" + EMono.pc.MaxHP) : "");
        c = EMono.Colors.Dark.gradientMP.Evaluate((float)EMono.pc.mana.value / (float)EMono.pc.mana.max);
        gaugeMP.textNow.text = "".TagColor(c, EMono.pc.mana.value.ToString() ?? "") + (extra.showMax ? ("/" + EMono.pc.mana.max) : "");
        c = EMono.Colors.Dark.gradientSP.Evaluate((float)EMono.pc.stamina.value / (float)EMono.pc.stamina.max);
        gaugeStamina.textNow.text = "".TagColor(c, EMono.pc.stamina.value.ToString() ?? "") + (extra.showMax ? ("/" + EMono.pc.stamina.max) : "");
        goBarrier.SetActive(value: false);
        textBarrier.text = "10";
    }
References Color, EMono.Colors, ColorProfile.Dark, extra, EMono.game, gaugeHP, gaugeMP, gaugeStamina, goBarrier, SkinColorProfile.gradientHP, SkinColorProfile.gradientMP, SkinColorProfile.gradientSP, Card.hp, Game.isLoading, Chara.mana, Stats.max, Chara.MaxHP, EMono.pc, WidgetHP.Extra.showGauge, WidgetHP.Extra.showMax, Chara.stamina, WidgetHP.Extra.stamina, Gauge.UpdateValue(), and Stats.value.
Referenced by OnSetContextMenu(), and Rebuild().
Member Data Documentation
gaugeHP
Gauge WidgetHP.gaugeHP
Definition at line 22 of file WidgetHP.cs.
Referenced by Refresh().
gaugeMP
Gauge WidgetHP.gaugeMP
Definition at line 24 of file WidgetHP.cs.
Referenced by Refresh().
gaugeStamina
Gauge WidgetHP.gaugeStamina
Definition at line 26 of file WidgetHP.cs.
Referenced by Refresh().
goBarrier
GameObject WidgetHP.goBarrier
Definition at line 38 of file WidgetHP.cs.
Referenced by Refresh().
grid
GridLayoutGroup WidgetHP.grid
Definition at line 36 of file WidgetHP.cs.
textBarrier
UIText WidgetHP.textBarrier
Definition at line 34 of file WidgetHP.cs.
textHP
UIText WidgetHP.textHP
Definition at line 28 of file WidgetHP.cs.
textMP
UIText WidgetHP.textMP
Definition at line 30 of file WidgetHP.cs.
textStamina
UIText WidgetHP.textStamina
Definition at line 32 of file WidgetHP.cs.
Property Documentation
extra
Extra WidgetHP.extra get
Definition at line 40 of file WidgetHP.cs.
Referenced by OnSetContextMenu(), and Refresh().
The documentation for this class was generated from the following file:
Elin/WidgetHP.cs