Elin Decompiled Documentation: UICharaMaker Class Reference
UICharaMaker Class Reference
Public Member Functions
void SetChara (Chara c)
void BuildRaces ()
void RefreshPortraitZoom (bool force=false)
void Refresh ()
void ListModes ()
void ListDifficulties ()
void RerollAlias ()
void ListAlias ()
void RerollName ()
void EditName ()
void OnEndEditName ()
void RerollRace ()
void ListRace ()
void RerollJob ()
void ListJob ()
void AddDomain (UINote n, ElementContainer domains, bool button)
void ListGender ()
void ListAge ()
void SetPortraitSlider ()
void RerollPCC ()
void RerollHair ()
void RerollBio ()
void RerollBio (bool keepParent)
void EditPCC ()
void OnClickChangePortrait ()
Public Attributes
Chara chara
Portrait portrait
Portrait portraitZoom
InputField inputName
InputField inputAlias
InputField inputJob
InputField inputRace
InputField inputGender
InputField inputAge
UISlider sliderPortrait
List< SourceRace.Row > races = new List<SourceRace.Row>()
List< SourceJob.Row > jobs = new List<SourceJob.Row>()
UIButton toggleExtra
UIButton toggleParentLock
UINote note
UINote note2
UINote noteJob
UINote noteRace
bool addShadow
bool extraRace
UIText textSign
UIText textMode
UIText textDifficulty
int ageIndex
Vector2 posList
Vector2 posList2
string[] listMode
string[] listDifficulties
Properties
Biography bio [get]
string TextUnknown [get]
Properties inherited from EMono
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SoundManager Sound [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static CoreDebug debug [get]
Private Member Functions
void Update ()
Additional Inherited Members
Static Public Member Functions inherited from EMono
static int rnd (int a)
Static Public Attributes inherited from EMono
static Core core
Detailed Description
Definition at line 8 of file UICharaMaker.cs.
Member Function Documentation
AddDomain()
void UICharaMaker.AddDomain (UINote n, ElementContainer domains, bool button) inline
Definition at line 415 of file UICharaMaker.cs.
    {
        n.Space(8);
        string text = "";
        foreach (Element value in domains.dict.Values)
        {
            text = text + ((value == domains.dict.Values.First()) ? "" : ", ") + value.Name;
        }
        UIItem uIItem = n.AddTopic("TopicDomain", "domain".lang(), text);
        uIItem.button1.SetActive(button && EMono.pc.HasElement(1402));
        uIItem.button1.SetOnClick(delegate
        {
            EMono.player.SelectDomain(Refresh);
        });
    }
References Card.HasElement(), EMono.pc, EMono.player, Refresh(), and Player.SelectDomain().
Referenced by ListJob(), and Refresh().
BuildRaces()
void UICharaMaker.BuildRaces () inline
Definition at line 92 of file UICharaMaker.cs.
    {
        races.Clear();
        jobs.Clear();
        bool flag = EMono.core.config.test.extraRace;
        foreach (SourceRace.Row row in EMono.sources.races.rows)
        {
            if (row.playable == 1 || (row.playable <= 6 && extraRace) || (flag && row.playable != 9))
            {
                races.Add(row);
            }
        }
        foreach (SourceJob.Row row2 in EMono.sources.jobs.rows)
        {
            if (row2.playable == 1 || (row2.playable <= 6 && extraRace) || (flag && row2.playable != 9))
            {
                jobs.Add(row2);
            }
        }
        races.Sort((SourceRace.Row a, SourceRace.Row b) => (a.playable - b.playable) * 10000 + a._index - b._index);
        jobs.Sort((SourceJob.Row a, SourceJob.Row b) => (a.playable - b.playable) * 10000 + a._index - b._index);
    }
References Core.config, EMono.core, CoreConfig.Test.extraRace, extraRace, SourceManager.jobs, jobs, SourceManager.races, races, EMono.sources, and CoreConfig.test.
Referenced by SetChara().
EditName()
void UICharaMaker.EditName () inline
Definition at line 287 of file UICharaMaker.cs.
    {
        Dialog.InputName("dialogChangeName", chara.c_altName.IsEmpty(chara.NameSimple), delegate(bool cancel, string text)
        {
            if (!cancel)
            {
                chara.c_altName = text;
                Refresh();
            }
        }).SetOnKill(delegate
        {
            EMono.ui.hud.hint.Show("hintEmbarkTop".lang(), icon: false);
        });
    }
References Card.c_altName, chara, Dialog.InputName(), Card.NameSimple, Refresh(), and EMono.ui.
EditPCC()
void UICharaMaker.EditPCC () inline
Definition at line 489 of file UICharaMaker.cs.
    {
        EMono.ui.AddLayer<LayerEditPCC>().Activate(chara, UIPCC.Mode.Body, null, delegate
        {
            portrait.SetChara(chara);
            SetPortraitSlider();
        });
    }
References chara, portrait, Portrait.SetChara(), SetPortraitSlider(), and EMono.ui.
ListAge()
void UICharaMaker.ListAge () inline
Definition at line 447 of file UICharaMaker.cs.
    {
        EMono.ui.AddLayer<LayerList>().SetStringList(() => Lang.GetList("ages"), delegate(int a, string b)
        {
            if (ageIndex != a)
            {
                ageIndex = a;
                RerollBio(keepParent: true);
            }
            Refresh();
        }).SetTitles("wAge");
    }
References ageIndex, Lang.GetList(), Refresh(), RerollBio(), and EMono.ui.
ListAlias()
void UICharaMaker.ListAlias () inline
Definition at line 262 of file UICharaMaker.cs.
    {
        EMono.ui.AddLayer<LayerList>().SetStringList(delegate
        {
            List<string> list = new List<string>();
            for (int i = 0; i < 10; i++)
            {
                list.Add(AliasGen.GetRandomAlias());
            }
            return list;
        }, delegate(int a, string b)
        {
            chara._alias = b;
            Refresh();
        }).SetSize()
            .EnableReroll()
            .SetTitles("wAlias");
    }
References LayerList.EnableReroll(), Refresh(), and EMono.ui.
ListDifficulties()
void UICharaMaker.ListDifficulties () inline
Definition at line 212 of file UICharaMaker.cs.
    {
        TooltipManager.Instance.HideTooltips(immediate: true);
        TooltipManager.Instance.disableHide = "note";
        bool first = true;
        EMono.ui.AddLayer<LayerList>().SetPivot(0.5f, 0.2f).SetSize(260f)
            .SetList2(EMono.setting.start.difficulties, (GameDifficulty a) => a.Name, delegate(GameDifficulty a, ItemGeneral b)
            {
                EMono.game.idDifficulty = a.ID;
                textDifficulty.SetText(listDifficulties[EMono.game.idDifficulty]);
                Refresh();
            }, delegate(GameDifficulty a, ItemGeneral item)
            {
                UIButton b2 = item.button1;
                b2.SetTooltip(delegate(UITooltip t)
                {
                    t.note.Clear();
                    t.note.AddHeader(a.Name);
                    t.note.Space(8);
                    t.note.AddText("NoteText_medium", "vow_" + a.ID).Hyphenate();
                    t.note.Space(8);
                    t.note.Build();
                });
                if (first)
                {
                    TooltipManager.Instance.GetComponent<CanvasGroup>().alpha = 0f;
                    TooltipManager.Instance.GetComponent<CanvasGroup>().DOFade(1f, 0.3f);
                    EMono.core.actionsNextFrame.Add(delegate
                    {
                        b2.ShowTooltipForced();
                    });
                }
                first = false;
            })
            .SetTitles("wDifficulty");
        RectTransform rectTransform = EMono.ui.GetLayer<LayerList>().windows[0].Rect();
        rectTransform.pivot = new Vector2(0.5f, 0.5f);
        rectTransform.anchoredPosition = posList2;
        TweenUtil.Tween(0.3f, null, delegate
        {
            UIButton.TryShowTip();
        });
    }
References BaseCore.actionsNextFrame, EMono.core, GameSetting.StartSetting.difficulties, EMono.game, GameDifficulty.ID, Game.idDifficulty, item, listDifficulties, GameDifficulty.Name, posList2, Refresh(), LayerList.SetSize(), EMono.setting, GameSetting.start, textDifficulty, and EMono.ui.
ListGender()
void UICharaMaker.ListGender () inline
Definition at line 431 of file UICharaMaker.cs.
    {
        EMono.ui.AddLayer<LayerList>().SetStringList(() => Lang.GetList("genders"), delegate(int a, string b)
        {
            if (chara.bio.gender != a)
            {
                chara.bio.SetGender(a);
                chara.c_idPortrait = Portrait.GetRandomPortrait(chara.bio.gender, chara.GetIdPortraitCat());
                portrait.SetChara(chara);
                portraitZoom.SetChara(chara);
            }
            SetPortraitSlider();
            Refresh();
        }).SetTitles("wGender");
    }
References Card.bio, chara, Biography.gender, Chara.GetIdPortraitCat(), Lang.GetList(), Portrait.GetRandomPortrait(), portrait, portraitZoom, Refresh(), Portrait.SetChara(), Biography.SetGender(), SetPortraitSlider(), and EMono.ui.
ListJob()
void UICharaMaker.ListJob () inline
Definition at line 367 of file UICharaMaker.cs.
    {
        TooltipManager.Instance.HideTooltips(immediate: true);
        TooltipManager.Instance.disableHide = "note";
        bool first = true;
        EMono.ui.AddLayer<LayerList>().SetPivot(0.5f, 0.1f).SetSize(260f)
            .SetList2(jobs, (SourceJob.Row a) => a.GetText().ToTitleCase(wholeText: true), delegate(SourceJob.Row a, ItemGeneral b)
            {
                chara.ChangeJob(a.id);
                EMono.player.RefreshDomain();
                RerollBio(keepParent: true);
            }, delegate(SourceJob.Row a, ItemGeneral item)
            {
                UIButton b2 = item.button1;
                b2.SetTooltip(delegate(UITooltip t)
                {
                    ElementContainer elementContainer = new ElementContainer();
                    elementContainer.ApplyElementMap(EMono.pc.uid, SourceValueType.Chara, a.elementMap, 1);
                    elementContainer.ApplyPotential(2);
                    t.note.Clear();
                    t.note.AddHeader(a.GetText().ToTitleCase(wholeText: true));
                    elementContainer.AddNoteAll(t.note);
                    t.note.AddHeader("lore");
                    t.note.AddText("NoteText_long", a.GetDetail().IsEmpty(TextUnknown)).Hyphenate();
                    AddDomain(t.note, new ElementContainer().ImportElementMap(a.domain), button: false);
                    t.note.Build();
                });
                if (first)
                {
                    TooltipManager.Instance.GetComponent<CanvasGroup>().alpha = 0f;
                    TooltipManager.Instance.GetComponent<CanvasGroup>().DOFade(1f, 0.3f);
                    EMono.core.actionsNextFrame.Add(delegate
                    {
                        b2.ShowTooltipForced();
                    });
                }
                first = false;
            })
            .SetTitles("wClass");
        RectTransform rectTransform = EMono.ui.GetLayer<LayerList>().windows[0].Rect();
        rectTransform.pivot = new Vector2(0.5f, 0.5f);
        rectTransform.anchoredPosition = posList;
        TweenUtil.Tween(0.3f, null, delegate
        {
            UIButton.TryShowTip();
        });
    }
References BaseCore.actionsNextFrame, AddDomain(), ElementContainer.AddNoteAll(), ElementContainer.ApplyElementMap(), ElementContainer.ApplyPotential(), Chara.ChangeJob(), chara, EMono.core, item, jobs, EMono.pc, EMono.player, posList, Player.RefreshDomain(), RerollBio(), LayerList.SetSize(), TextUnknown, EMono.ui, and Card.uid.
ListModes()
void UICharaMaker.ListModes () inline
Definition at line 196 of file UICharaMaker.cs.
    {
        EMono.ui.AddLayer<LayerList>().SetStringList(() => listMode, delegate(int a, string b)
        {
            EMono.game.idPrologue = a;
            Prologue prologue = EMono.game.Prologue;
            EMono.world.date.year = prologue.year;
            EMono.world.date.month = prologue.month;
            EMono.world.date.day = prologue.day;
            EMono.world.weather._currentCondition = prologue.weather;
            textMode.SetText(listMode[EMono.game.idPrologue]);
            Refresh();
        }).SetSize()
            .SetTitles("wStartMode");
    }
References Prologue.day, EMono.game, Game.idPrologue, listMode, Prologue.month, Game.Prologue, Refresh(), textMode, EMono.ui, Prologue.weather, and Prologue.year.
ListRace()
void UICharaMaker.ListRace () inline
Definition at line 313 of file UICharaMaker.cs.
    {
        TooltipManager.Instance.HideTooltips(immediate: true);
        TooltipManager.Instance.disableHide = "note";
        bool first = true;
        EMono.ui.AddLayer<LayerList>().SetPivot(0.5f, 0.2f).SetSize(260f)
            .SetList2(races, (SourceRace.Row a) => a.GetText().ToTitleCase(wholeText: true), delegate(SourceRace.Row a, ItemGeneral b)
            {
                chara.ChangeRace(a.id);
                RerollBio(keepParent: true);
            }, delegate(SourceRace.Row a, ItemGeneral item)
            {
                UIButton b2 = item.button1;
                b2.SetTooltip(delegate(UITooltip t)
                {
                    ElementContainer elementContainer = new ElementContainer();
                    elementContainer.ApplyElementMap(EMono.pc.uid, SourceValueType.Chara, a.elementMap, 1);
                    elementContainer.ApplyPotential(1);
                    t.note.Clear();
                    t.note.AddHeader(a.GetText().ToTitleCase(wholeText: true));
                    elementContainer.AddNoteAll(t.note);
                    t.note.AddHeader("lore");
                    t.note.AddText("NoteText_long", a.GetDetail().IsEmpty(TextUnknown)).Hyphenate();
                    t.note.Space(8);
                    t.note.Build();
                });
                if (first)
                {
                    TooltipManager.Instance.GetComponent<CanvasGroup>().alpha = 0f;
                    TooltipManager.Instance.GetComponent<CanvasGroup>().DOFade(1f, 0.3f);
                    EMono.core.actionsNextFrame.Add(delegate
                    {
                        b2.ShowTooltipForced();
                    });
                }
                first = false;
            })
            .SetTitles("wRace");
        RectTransform rectTransform = EMono.ui.GetLayer<LayerList>().windows[0].Rect();
        rectTransform.pivot = new Vector2(0.5f, 0.5f);
        rectTransform.anchoredPosition = posList;
        TweenUtil.Tween(0.3f, null, delegate
        {
            UIButton.TryShowTip();
        });
    }
References BaseCore.actionsNextFrame, ElementContainer.AddNoteAll(), ElementContainer.ApplyElementMap(), ElementContainer.ApplyPotential(), Chara.ChangeRace(), chara, EMono.core, item, EMono.pc, posList, races, RerollBio(), LayerList.SetSize(), TextUnknown, EMono.ui, and Card.uid.
OnClickChangePortrait()
void UICharaMaker.OnClickChangePortrait () inline
Definition at line 498 of file UICharaMaker.cs.
    {
        EMono.ui.AddLayer<LayerEditPortrait>().Activate(chara, chara.pccData, delegate
        {
            portrait.SetChara(chara, chara.pccData);
        });
    }
References Chara.pccData, Portrait.SetChara(), and EMono.ui.
OnEndEditName()
void UICharaMaker.OnEndEditName () inline
Definition at line 302 of file UICharaMaker.cs.
    {
        chara.c_altName = inputName.text;
    }
References inputName.
Refresh()
void UICharaMaker.Refresh () inline
Definition at line 139 of file UICharaMaker.cs.
    {
        chara.elements.ApplyPotential();
        Prologue prologue = EMono.game.Prologue;
        textSign.SetText("signDisembark".lang(prologue.month.ToString() ?? "", prologue.day.ToString() ?? "", prologue.year.ToString() ?? ""));
        RefreshPortraitZoom();
        inputAlias.text = chara.Aka;
        inputName.text = chara.c_altName;
        inputRace.text = chara.race.GetText().ToTitleCase(wholeText: true);
        inputJob.text = chara.job.GetText().ToTitleCase(wholeText: true);
        inputGender.text = Lang._gender(chara.bio.gender);
        inputAge.text = Lang.GetList("ages")[ageIndex];
        note.Clear();
        note.AddTopic("name".lang(), "nameBio".lang(chara.NameSimple, chara.Aka));
        note.AddTopic("birthday".lang(), bio.TextBirthDate(chara, _age: true) + ((ageIndex == 0) ? "" : (" (" + Lang.GetList("ages")[ageIndex] + ")")));
        note.AddTopic("appearance".lang(), bio.TextAppearance());
        note.AddTopic("dad".lang(), bio.nameDad.ToTitleCase());
        note.AddTopic("mom".lang(), bio.nameMom.ToTitleCase());
        note.AddTopic("birthLoc".lang(), bio.nameBirthplace.ToTitleCase());
        note.Build();
        noteRace.Clear();
        noteRace.AddHeaderTopic("race".lang() + ": " + chara.race.GetText().ToTitleCase(wholeText: true));
        noteRace.Space(8);
        noteRace.AddText("NoteText_long", chara.race.GetDetail().IsEmpty(TextUnknown)).Hyphenate();
        noteRace.Build();
        noteJob.Clear();
        noteJob.AddHeaderTopic("job".lang() + ": " + chara.job.GetText().ToTitleCase(wholeText: true));
        noteJob.Space(8);
        noteJob.AddText("NoteText_long", chara.job.GetDetail().IsEmpty(TextUnknown)).Hyphenate();
        AddDomain(noteJob, EMono.player.GetDomains(), button: true);
        noteJob.Build();
        note2.Clear();
        note2.AddHeaderTopic("attributes".lang());
        chara.elements.AddNote(note2, (Element e) => e.HasTag("primary"), null, ElementContainer.NoteMode.CharaMake);
        note2.Space();
        note2.AddHeaderTopic("skills".lang());
        chara.elements.AddNote(note2, (Element e) => e.source.category == "skill" && e.ValueWithoutLink > 1 && e.source.categorySub != "weapon", null, ElementContainer.NoteMode.CharaMake);
        note2.Space();
        note2.AddHeaderTopic("feats".lang());
        chara.elements.AddNote(note2, (Element e) => e is Feat, null, ElementContainer.NoteMode.CharaMake, addRaceFeat: true);
        note2.Build();
        if (!addShadow)
        {
            return;
        }
        Text[] componentsInChildren = note2.gameObject.GetComponentsInChildren<Text>();
        foreach (Text text in componentsInChildren)
        {
            Shadow shadow = text.GetComponent<Shadow>();
            if (!shadow)
            {
                shadow = text.gameObject.AddComponent<Shadow>();
            }
            shadow.effectColor = Color.black;
        }
    }
References Lang._gender(), AddDomain(), ElementContainer.AddNote(), addShadow, ageIndex, Chara.Aka, ElementContainer.ApplyPotential(), Card.bio, bio, Card.c_altName, chara, Color, Prologue.day, Card.elements, EMono.game, Biography.gender, Player.GetDomains(), Lang.GetList(), Element.HasTag(), Chara.job, Prologue.month, Biography.nameBirthplace, Biography.nameDad, Biography.nameMom, Card.NameSimple, note, note2, noteJob, noteRace, EMono.player, Game.Prologue, Chara.race, RefreshPortraitZoom(), Element.source, Biography.TextAppearance(), Biography.TextBirthDate(), textSign, TextUnknown, Element.ValueWithoutLink, and Prologue.year.
Referenced by AddDomain(), EditName(), ListAge(), ListAlias(), ListDifficulties(), ListGender(), ListModes(), RerollAlias(), RerollBio(), RerollJob(), RerollName(), and SetChara().
RefreshPortraitZoom()
void UICharaMaker.RefreshPortraitZoom (bool force = false) inline
Definition at line 120 of file UICharaMaker.cs.
    {
        if (!portraitZoom)
        {
            return;
        }
        List<GameObject> hovered = InputModuleEX.GetPointerEventData().hovered;
        bool enable = false;
        foreach (GameObject item in hovered)
        {
            if (item.transform.IsChildOf(portrait.transform))
            {
                enable = true;
                break;
            }
        }
        portraitZoom.SetActive(enable);
    }
References item, portrait, and portraitZoom.
Referenced by Refresh(), and Update().
RerollAlias()
void UICharaMaker.RerollAlias () inline
Definition at line 256 of file UICharaMaker.cs.
    {
        chara._alias = AliasGen.GetRandomAlias();
        Refresh();
    }
References Refresh().
RerollBio() [1/2]
void UICharaMaker.RerollBio () inline
Definition at line 478 of file UICharaMaker.cs.
    {
        RerollBio(keepParent: false);
    }
References RerollBio().
Referenced by ListAge(), ListJob(), ListRace(), RerollBio(), and RerollRace().
RerollBio() [2/2]
void UICharaMaker.RerollBio (bool keepParent) inline
Definition at line 483 of file UICharaMaker.cs.
    {
        bio.RerollBio(chara, ageIndex, keepParent);
        Refresh();
    }
References ageIndex, bio, chara, Refresh(), and Biography.RerollBio().
RerollHair()
void UICharaMaker.RerollHair () inline
Definition at line 471 of file UICharaMaker.cs.
    {
        chara.pccData.SetRandomColor("hair");
        portrait.SetChara(chara);
        portraitZoom.SetChara(chara);
    }
References chara, Chara.pccData, portrait, portraitZoom, and Portrait.SetChara().
RerollJob()
void UICharaMaker.RerollJob () inline
Definition at line 360 of file UICharaMaker.cs.
    {
        chara.ChangeJob(jobs.RandomItem(chara.job).id);
        EMono.player.RefreshDomain();
        Refresh();
    }
References Chara.ChangeJob(), chara, Chara.job, jobs, EMono.player, Refresh(), and Player.RefreshDomain().
RerollName()
void UICharaMaker.RerollName () inline
Definition at line 281 of file UICharaMaker.cs.
    {
        chara.c_altName = NameGen.getRandomName();
        Refresh();
    }
References Refresh().
RerollPCC()
void UICharaMaker.RerollPCC () inline
Definition at line 464 of file UICharaMaker.cs.
    {
        chara.pccData.Randomize(null, null, randomizeHairColor: false);
        portrait.SetChara(chara);
        portraitZoom.SetChara(chara);
    }
References chara, Chara.pccData, portrait, portraitZoom, and Portrait.SetChara().
RerollRace()
void UICharaMaker.RerollRace () inline
Definition at line 307 of file UICharaMaker.cs.
    {
        chara.ChangeRace(races.RandomItem(chara.race).id);
        RerollBio(keepParent: true);
    }
References Chara.ChangeRace(), chara, Chara.race, races, and RerollBio().
SetChara()
void UICharaMaker.SetChara (Chara c) inline
Definition at line 72 of file UICharaMaker.cs.
    {
        listMode = Lang.GetList("startMode");
        listDifficulties = Lang.GetList("difficulties");
        textMode.SetText(listMode[EMono.game.idPrologue]);
        textDifficulty.SetText(listDifficulties[EMono.game.idDifficulty]);
        chara = c;
        BuildRaces();
        SetPortraitSlider();
        portrait.SetChara(chara, chara.pccData);
        portraitZoom.SetChara(chara);
        Refresh();
        toggleExtra.SetToggle(extraRace, delegate(bool a)
        {
            extraRace = a;
            BuildRaces();
            SE.Tab();
        });
    }
References BuildRaces(), chara, extraRace, EMono.game, Lang.GetList(), Game.idDifficulty, Game.idPrologue, listDifficulties, listMode, Chara.pccData, portrait, portraitZoom, Refresh(), Portrait.SetChara(), SetPortraitSlider(), textDifficulty, textMode, and toggleExtra.
Referenced by LayerEditBio.SetChara().
SetPortraitSlider()
void UICharaMaker.SetPortraitSlider () inline
Definition at line 460 of file UICharaMaker.cs.
    {
    }
Referenced by EditPCC(), ListGender(), and SetChara().
Update()
void UICharaMaker.Update () inline private
Definition at line 115 of file UICharaMaker.cs.
    {
        RefreshPortraitZoom();
    }
References RefreshPortraitZoom().
Member Data Documentation
addShadow
bool UICharaMaker.addShadow
Definition at line 46 of file UICharaMaker.cs.
Referenced by Refresh().
ageIndex
int UICharaMaker.ageIndex
Definition at line 56 of file UICharaMaker.cs.
Referenced by ListAge(), Refresh(), and RerollBio().
chara
Chara UICharaMaker.chara
Definition at line 10 of file UICharaMaker.cs.
Referenced by EditName(), EditPCC(), ListGender(), ListJob(), ListRace(), Refresh(), RerollBio(), RerollHair(), RerollJob(), RerollPCC(), RerollRace(), and SetChara().
extraRace
bool UICharaMaker.extraRace
Definition at line 48 of file UICharaMaker.cs.
Referenced by BuildRaces(), and SetChara().
inputAge
InputField UICharaMaker.inputAge
Definition at line 26 of file UICharaMaker.cs.
inputAlias
InputField UICharaMaker.inputAlias
Definition at line 18 of file UICharaMaker.cs.
inputGender
InputField UICharaMaker.inputGender
Definition at line 24 of file UICharaMaker.cs.
inputJob
InputField UICharaMaker.inputJob
Definition at line 20 of file UICharaMaker.cs.
inputName
InputField UICharaMaker.inputName
Definition at line 16 of file UICharaMaker.cs.
Referenced by OnEndEditName().
inputRace
InputField UICharaMaker.inputRace
Definition at line 22 of file UICharaMaker.cs.
jobs
List<SourceJob.Row> UICharaMaker.jobs = new List<SourceJob.Row>()
Definition at line 32 of file UICharaMaker.cs.
Referenced by BuildRaces(), ListJob(), and RerollJob().
listDifficulties
string [] UICharaMaker.listDifficulties
Definition at line 66 of file UICharaMaker.cs.
Referenced by ListDifficulties(), and SetChara().
listMode
string [] UICharaMaker.listMode
Definition at line 63 of file UICharaMaker.cs.
Referenced by ListModes(), and SetChara().
note
UINote UICharaMaker.note
Definition at line 38 of file UICharaMaker.cs.
Referenced by Refresh().
note2
UINote UICharaMaker.note2
Definition at line 40 of file UICharaMaker.cs.
Referenced by Refresh().
noteJob
UINote UICharaMaker.noteJob
Definition at line 42 of file UICharaMaker.cs.
Referenced by Refresh().
noteRace
UINote UICharaMaker.noteRace
Definition at line 44 of file UICharaMaker.cs.
Referenced by Refresh().
portrait
Portrait UICharaMaker.portrait
Definition at line 12 of file UICharaMaker.cs.
Referenced by EditPCC(), ListGender(), RefreshPortraitZoom(), RerollHair(), RerollPCC(), and SetChara().
portraitZoom
Portrait UICharaMaker.portraitZoom
Definition at line 14 of file UICharaMaker.cs.
Referenced by ListGender(), RefreshPortraitZoom(), RerollHair(), RerollPCC(), and SetChara().
posList
Vector2 UICharaMaker.posList
Definition at line 58 of file UICharaMaker.cs.
Referenced by ListJob(), and ListRace().
posList2
Vector2 UICharaMaker.posList2
Definition at line 60 of file UICharaMaker.cs.
Referenced by ListDifficulties().
races
List<SourceRace.Row> UICharaMaker.races = new List<SourceRace.Row>()
Definition at line 30 of file UICharaMaker.cs.
Referenced by BuildRaces(), ListRace(), and RerollRace().
sliderPortrait
UISlider UICharaMaker.sliderPortrait
Definition at line 28 of file UICharaMaker.cs.
textDifficulty
UIText UICharaMaker.textDifficulty
Definition at line 54 of file UICharaMaker.cs.
Referenced by ListDifficulties(), and SetChara().
textMode
UIText UICharaMaker.textMode
Definition at line 52 of file UICharaMaker.cs.
Referenced by ListModes(), and SetChara().
textSign
UIText UICharaMaker.textSign
Definition at line 50 of file UICharaMaker.cs.
Referenced by Refresh().
toggleExtra
UIButton UICharaMaker.toggleExtra
Definition at line 34 of file UICharaMaker.cs.
Referenced by SetChara().
toggleParentLock
UIButton UICharaMaker.toggleParentLock
Definition at line 36 of file UICharaMaker.cs.
Property Documentation
bio
Biography UICharaMaker.bio get
Definition at line 68 of file UICharaMaker.cs.
Referenced by Refresh(), and RerollBio().
TextUnknown
string UICharaMaker.TextUnknown get
Definition at line 70 of file UICharaMaker.cs.
Referenced by ListJob(), ListRace(), and Refresh().
The documentation for this class was generated from the following file:
Elin/UICharaMaker.cs