Elin Decompiled Documentation: UI Class Reference
UI Class Reference
Public Member Functions
void OnCoreStart ()
void OnActivateZone ()
void ShowFloats ()
void HideFloats ()
void OnKillGame ()
void OnClickAction (string _mode)
void RefreshActiveState ()
override void OnChangeLayer ()
void FlashCover (float durationOut=1f, float duration=1f, float durationIn=1f, Action onFadeOut=null, Action onComplete=null, Color color=default(Color))
void ShowCover (float duration=0f, float dest=1f, Action onComplete=null, Color color=default(Color))
void HideCover (float duration=0f, Action onComplete=null)
bool IsCovered ()
void ShowBalloon (bool enable)
void Show (float duration=1f)
void Hide (float duration=1f)
void OnUpdate ()
void ShowMouseHint ()
void HideMouseHint (float duration=0.2f)
void CheckWindowOrder ()
void ShowSceneSelector ()
void ShowLang ()
void SetLight (bool enable)
UIContextMenu CreateContextMenu (string cid="ContextMenu")
UIContextMenu CreateContextMenuInteraction ()
void Say (string text, Sprite sprite=null)
void FreezeScreen (float duration)
void UnfreezeScreen ()
void ToggleAbility (bool delay=false)
void ToggleInventory (bool delay=false)
void OpenFloatInv (bool ignoreSound=false)
void ToggleFeedback ()
void StartDrag (DragItem item)
void OnDrag ()
void OnDragSpecial ()
void EndDrag (bool canceled=false)
Public Member Functions inherited from ELayer
override void OnBeforeAddLayer ()
void InitInspector ()
sealed override void Init ()
override void OnAfterAddLayer ()
void TryShowHelp ()
void AddLayerToUI (string id)
void TryShowHint (string _langHint=null)
void TalkHomeMemeber (string id)
void TalkMaid (string id)
override void OnRightClick ()
Public Attributes
Canvas canvas
HUD hud
ExtraHint extraHint
InputModuleEX inputModule
UIContextMenuManager contextMenu
WidgetManager widgets
UIMouseInfo mouseInfo
RectTransform rectDynamic
RectTransform rectDynamicEssential
RectTransform _rectLayers
ReflexConsole console
GameObject blur
Material matBlur
LayoutGroup layoutLang
CanvasScaler canvasScaler
Image light
CanvasGroup cg
int minWidth
Layer layerFloat
UIAutoTurn autoTurn
PopManager popGame
PopManager popSystem
float blurSpeed
Texture2D texFreeze
RawImage imageFreeze
DragItem currentDrag
DragItem nextDrag
float lightContrast
float dragDuration
bool wasActive
bool isPointerOverUI
Protected Member Functions
override void Awake ()
Protected Member Functions inherited from ELayer
sealed override void _Close ()
sealed override void Kill ()
Properties
SkinManager skins [get]
bool IsActive [get]
bool AllowInventoryInteractions [get]
bool BlockActions [get]
bool BlockMouseOverUpdate [get]
bool BlockInput [get]
bool IsPauseGame [get]
bool IsInventoryOpen [get]
bool IsAbilityOpen [get]
override bool blockWidgetClick [get]
override RectTransform rectLayers [get]
bool IsDragging [get]
Properties inherited from ELayer
static Core core [get]
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static FactionBranch Branch [get]
static Faction Home [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static CoreConfig config [get]
static GameSetting setting [get]
static ColorProfile Colors [get]
static SourceManager sources [get]
static World world [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
bool IsFloat [get]
virtual string IdHelp [get]
Private Attributes
bool hidingCover
Tween tweenCover
float durationHideMouseHint
Static Private Attributes
static float blurSize
Additional Inherited Members
Static Public Member Functions inherited from ELayer
static int rnd (int a)
Detailed Description
Definition at line 9 of file UI.cs.
Member Function Documentation
Awake()
override void UI.Awake () inline protected
Definition at line 163 of file UI.cs.
    {
        base.Awake();
        InvokeRepeating("CheckWindowOrder", 1f, 0.5f);
    }
CheckWindowOrder()
void UI.CheckWindowOrder () inline
Definition at line 448 of file UI.cs.
    {
        if (layers.Count > 0)
        {
            return;
        }
        foreach (GameObject item in InputModuleEX.GetPointerEventData().hovered)
        {
            if ((bool)item)
            {
                Widget component = item.GetComponent<Widget>();
                if ((bool)component && !component.AlwaysBottom && widgets.transform.GetChild(widgets.transform.childCount - 1) != item.transform)
                {
                    item.transform.SetAsLastSibling();
                    break;
                }
            }
        }
        if ((bool)WidgetFeed.Instance)
        {
            WidgetFeed.Instance.transform.SetAsLastSibling();
        }
    }
References WidgetFeed.Instance.
CreateContextMenu()
UIContextMenu UI.CreateContextMenu (string cid = "ContextMenu") inline
Definition at line 528 of file UI.cs.
    {
        return contextMenu.Create(cid);
    }
CreateContextMenuInteraction()
UIContextMenu UI.CreateContextMenuInteraction () inline
Definition at line 533 of file UI.cs.
    {
        return contextMenu.Create("ContextInteraction");
    }
Referenced by AM_EditArea.OnProcessTiles().
EndDrag()
void UI.EndDrag (bool canceled = false) inline
Definition at line 778 of file UI.cs.
    {
        if (currentDrag == null)
        {
            return;
        }
        bool num = currentDrag.OnDrag(execute: true, canceled);
        EInput.Consume();
        EInput.dragHack = 0f;
        if (num)
        {
            ELayer.ui.RemoveLayer<LayerRegisterHotbar>();
            currentDrag.OnEndDrag();
            currentDrag = null;
            if (nextDrag != null)
            {
                StartDrag(nextDrag);
                nextDrag = null;
            }
            else
            {
                hud.SetDragImage(null);
            }
            UIButton.TryShowTip();
        }
        else
        {
            SE.BeepSmall();
        }
    }
References DragItem.OnDrag(), DragItem.OnEndDrag(), HUD.SetDragImage(), and ELayer.ui.
FlashCover()
void UI.FlashCover (float durationOut = 1f, float duration = 1f, float durationIn = 1f, Action onFadeOut = null, Action onComplete = null, Color color = default(Color)) inline
Definition at line 257 of file UI.cs.
    {
        ShowCover(durationOut, 1f, null, color);
        TweenUtil.Tween(durationOut + duration, null, delegate
        {
            if (onFadeOut != null)
            {
                onFadeOut();
            }
            HideCover(durationIn, onComplete);
        });
    }
References HideCover(), and ShowCover().
FreezeScreen()
void UI.FreezeScreen (float duration) inline
Definition at line 544 of file UI.cs.
    {
        if ((bool)texFreeze)
        {
            UnityEngine.Object.Destroy(texFreeze);
        }
        texFreeze = ScreenCapture.CaptureScreenshotAsTexture();
        imageFreeze.SetActive(enable: true);
        imageFreeze.texture = texFreeze;
        if (duration != 0f)
        {
            TweenUtil.Tween(duration, null, delegate
            {
                UnfreezeScreen();
            });
        }
    }
Hide()
void UI.Hide (float duration = 1f) inline
Definition at line 323 of file UI.cs.
    {
        ELayer.scene.elomapActor.selector.srHighlight.SetActive(enable: false);
        if (duration == 0f)
        {
            cg.alpha = 0f;
        }
        else
        {
            cg.DOFade(0f, duration);
        }
    }
References Scene.elomapActor, ELayer.scene, EloMapActor.selector, and EloMapTileSelector.srHighlight.
HideCover()
void UI.HideCover (float duration = 0f, Action onComplete = null) inline
Definition at line 283 of file UI.cs.
    {
        if (!hidingCover)
        {
            hidingCover = true;
            TweenUtil.KillTween(ref tweenCover);
            tweenCover = hud.imageCover.DOFade(0f, duration).OnComplete(delegate
            {
                hud.imageCover.SetActive(enable: false);
                onComplete?.Invoke();
                hidingCover = false;
            });
        }
    }
References HUD.imageCover.
Referenced by LayerSleep.Advance(), FlashCover(), and LayerSleep.Wait().
HideFloats()
void UI.HideFloats () inline
Definition at line 189 of file UI.cs.
    {
        layerFloat.SetActive(enable: false);
    }
Referenced by OnChangeLayer().
HideMouseHint()
void UI.HideMouseHint (float duration = 0::2f) inline
Definition at line 441 of file UI.cs.
    {
        durationHideMouseHint = duration;
        hud.textMouseHintLeft.SetActive(enable: false);
        hud.textMouseHintRight.SetActive(enable: false);
    }
References HUD.textMouseHintLeft, and HUD.textMouseHintRight.
IsCovered()
bool UI.IsCovered () inline
Definition at line 298 of file UI.cs.
    {
        return !hidingCover;
    }
OnActivateZone()
void UI.OnActivateZone () inline
Definition at line 174 of file UI.cs.
    {
        widgets.OnActivateZone();
        ELayer.player.queues.SetOwner(ELayer.pc);
        if ((bool)hud.hangCorner && hud.hangCorner.isActiveAndEnabled)
        {
            hud.hangCorner.Refresh();
        }
    }
References HUD.hangCorner, WidgetManager.OnActivateZone(), ELayer.pc, ELayer.player, Player.queues, UIHangIcon.Refresh(), and QueueManager.SetOwner().
OnChangeLayer()
override void UI.OnChangeLayer () inline
Definition at line 226 of file UI.cs.
    {
        RefreshActiveState();
        CursorSystem.SetCursor();
        hud.HideMouseInfo();
        if (ELayer.core.IsGameStarted)
        {
            ELayer.scene.actionMode.OnUpdateCursor();
        }
        CursorSystem.Instance.Draw();
        Layer topLayer = base.TopLayer;
        if ((object)topLayer != null && topLayer.option.dontShowHint)
        {
            return;
        }
        if (layers.Count == 0)
        {
            hud.hint.Refresh();
            return;
        }
        if (base.TopLayer.option.hideFloatUI)
        {
            HideFloats();
        }
        if (base.TopLayer.option.hideWidgets)
        {
            widgets.Hide();
        }
        (base.TopLayer as ELayer)?.TryShowHint();
    }
References Scene.actionMode, ELayer.core, WidgetManager.Hide(), HideFloats(), HUD.HideMouseInfo(), HUD.hint, Core.IsGameStarted, ActionMode.OnUpdateCursor(), ActionHint.Refresh(), RefreshActiveState(), ELayer.scene, and ELayer.TryShowHint().
OnClickAction()
void UI.OnClickAction (string _mode) inline
Definition at line 202 of file UI.cs.
    {
        RemoveLayers();
        ((ActionMode)typeof(ActionMode).GetField(_mode, BindingFlags.Static | BindingFlags.Public).GetValue(null)).Activate();
    }
OnCoreStart()
void UI.OnCoreStart () inline
Definition at line 169 of file UI.cs.
    {
        mouseInfo.SetActive(enable: false);
    }
OnDrag()
void UI.OnDrag () inline
Definition at line 764 of file UI.cs.
    {
        dragDuration += Core.delta;
        currentDrag.OnDrag(execute: false);
    }
References Core.delta, and DragItem.OnDrag().
OnDragSpecial()
void UI.OnDragSpecial () inline
Definition at line 770 of file UI.cs.
    {
        if (currentDrag != null && !currentDrag.OnDragSpecial())
        {
            EndDrag(canceled: true);
        }
    }
References DragItem.OnDragSpecial().
OnKillGame()
void UI.OnKillGame () inline
Definition at line 194 of file UI.cs.
    {
        widgets.OnKillGame();
        ShowBalloon(enable: true);
        layerFloat.RemoveLayers(removeImportant: true);
        currentDrag = null;
    }
References WidgetManager.OnKillGame(), and ShowBalloon().
OnUpdate()
void UI.OnUpdate () inline
Definition at line 336 of file UI.cs.
    {
        if (hud.imageDrag.gameObject.activeSelf)
        {
            hud.imageDrag.transform.position = EInput.mpos + (ELayer.game.UseGrid ? hud.imageDragFix2 : hud.imageDragFix2);
            Util.ClampToScreen(hud.imageDrag.Rect(), hud.marginImageDrag);
        }
        if (ELayer.config.ui.blur && layers.Count > 0 && IsUseBlur())
        {
            blurSize += Time.unscaledDeltaTime * blurSpeed;
            if (blurSize > ELayer.config.ui.blurSize)
            {
                blurSize = ELayer.config.ui.blurSize;
            }
            if (!blur.activeSelf)
            {
                blur.SetActive(value: true);
            }
            int siblingIndex = blur.transform.GetSiblingIndex();
            int num = 0;
            for (int num2 = layers.Count - 1; num2 >= 0; num2--)
            {
                if (layers[num2].IsUseBlur())
                {
                    num = layers[num2].transform.GetSiblingIndex() - 1;
                    break;
                }
            }
            if (siblingIndex != num)
            {
                blur.transform.SetSiblingIndex(num);
            }
        }
        else
        {
            blurSize -= Time.unscaledDeltaTime * blurSpeed;
            if (blurSize < 0f)
            {
                blurSize = 0f;
            }
            if (blur.activeSelf && blurSize == 0f)
            {
                blur.SetActive(value: false);
            }
        }
        matBlur.SetFloat("_Size", blurSize);
        if (!EInput.isShiftDown)
        {
            LayerInventory.highlightInv = null;
        }
        ShowMouseHint();
    }
References CoreConfig.UISetting.blur, CoreConfig.UISetting.blurSize, ELayer.config, HUD.imageDrag, HUD.imageDragFix2, HUD.marginImageDrag, ShowMouseHint(), and CoreConfig.ui.
OpenFloatInv()
void UI.OpenFloatInv (bool ignoreSound = false) inline
Definition at line 635 of file UI.cs.
    {
        TooltipManager.Instance.disableTimer = 0.1f;
        if (ignoreSound)
        {
            SoundManager.ignoreSounds = true;
        }
        ELayer.ui.layerFloat.AddLayer(LayerInventory.CreatePCBackpack());
        SoundManager.ignoreSounds = true;
        ELayer.ui.widgets.Activate("Equip");
        foreach (Thing item in ELayer.pc.things.List((Thing a) => a.trait.IsContainer))
        {
            Window.SaveData c_windowSaveData = item.c_windowSaveData;
            if (!(item.trait is TraitToolBelt) && c_windowSaveData != null && c_windowSaveData.open)
            {
                LayerInventory.CreateContainer(item);
            }
        }
        SoundManager.ignoreSounds = false;
        TooltipManager.Instance.disableTimer = 0f;
    }
References LayerInventory.CreateContainer(), LayerInventory.CreatePCBackpack(), Trait.IsContainer, ThingContainer.List(), ELayer.pc, Card.things, Card.trait, and ELayer.ui.
RefreshActiveState()
void UI.RefreshActiveState () inline
Definition at line 208 of file UI.cs.
    {
        isPointerOverUI = false;
        foreach (GameObject item in InputModuleEX.GetPointerEventData().hovered)
        {
            if ((bool)item && item.layer == 5)
            {
                isPointerOverUI = true;
                break;
            }
        }
        wasActive = IsActive;
        if (wasActive)
        {
            CursorSystem.SetCursor();
        }
    }
References IsActive.
Referenced by OnChangeLayer().
Say()
void UI.Say (string text, Sprite sprite = null) inline
Definition at line 538 of file UI.cs.
    {
        popSystem.PopText(text.lang(), sprite, "PopAchievement");
        Debug.Log(text);
    }
SetLight()
void UI.SetLight (bool enable) inline
Definition at line 524 of file UI.cs.
    {
    }
Show()
void UI.Show (float duration = 1f) inline
Definition at line 309 of file UI.cs.
    {
        ELayer.scene.elomapActor.selector.srHighlight.SetActive(enable: true);
        cg.DOKill();
        if (duration == 0f)
        {
            cg.alpha = 1f;
        }
        else
        {
            cg.DOFade(1f, duration);
        }
    }
References Scene.elomapActor, ELayer.scene, EloMapActor.selector, and EloMapTileSelector.srHighlight.
ShowBalloon()
void UI.ShowBalloon (bool enable) inline
Definition at line 303 of file UI.cs.
    {
        ELayer.ui.rectDynamic.SetActive(enable);
        WidgetSystemIndicator.Refresh();
    }
References WidgetSystemIndicator.Refresh(), and ELayer.ui.
Referenced by OnKillGame().
ShowCover()
void UI.ShowCover (float duration = 0f, float dest = 1f, Action onComplete = null, Color color = default(Color)) inline
Definition at line 270 of file UI.cs.
    {
        TweenUtil.KillTween(ref tweenCover);
        float a = hud.imageCover.color.a;
        hud.imageCover.color = ((color == default(Color)) ? Color.black : color).SetAlpha(a);
        hud.imageCover.SetActive(enable: true);
        hidingCover = false;
        tweenCover = hud.imageCover.DOFade(dest, duration).OnComplete(delegate
        {
            onComplete?.Invoke();
        });
    }
References Color, and HUD.imageCover.
Referenced by LayerSleep.Advance(), FlashCover(), and LayerSleep.OnAfterInit().
ShowFloats()
void UI.ShowFloats () inline
Definition at line 184 of file UI.cs.
    {
        layerFloat.SetActive(enable: true);
    }
ShowLang()
void UI.ShowLang () inline
Definition at line 495 of file UI.cs.
    {
        canvasScaler.scaleFactor = 1f;
        Shader.SetGlobalFloat("_UIBrightness", 1f);
        Shader.SetGlobalFloat("_UIContrast", 1f);
        layoutLang.SetActive(enable: true);
        Button t = layoutLang.CreateMold<Button>();
        foreach (LangSetting value in MOD.langs.Values)
        {
            Button button = Util.Instantiate(t, layoutLang);
            LangSetting _l = value;
            button.GetComponentInChildren<Text>().text = value.name + " (" + value.name_en + ")";
            button.onClick.AddListener(delegate
            {
                layoutLang.SetActive(enable: false);
                ELayer.core.langCode = _l.id;
                if (ELayer.debug.showSceneSelector || (Input.GetKey(KeyCode.LeftShift) && ELayer.debug.enable))
                {
                    ShowSceneSelector();
                }
                else
                {
                    ELayer.core.Init();
                }
            });
        }
        layoutLang.RebuildLayout();
    }
References ELayer.core, ELayer.debug, CoreDebug.enable, Core.Init(), CoreDebug.showSceneSelector, and ShowSceneSelector().
ShowMouseHint()
void UI.ShowMouseHint () inline
Definition at line 389 of file UI.cs.
    {
        if (durationHideMouseHint > 0f)
        {
            durationHideMouseHint -= Core.delta;
            hud.textMouseHintLeft.SetActive(enable: false);
            hud.textMouseHintRight.SetActive(enable: false);
            return;
        }
        IMouseHint mouseHint = UIButton.currentHighlight as IMouseHint;
        bool flag = mouseHint != null && !IsDragging && isPointerOverUI && (bool)UIButton.currentHighlight && InputModuleEX.IsPointerOver(UIButton.currentHighlight) && LayerAbility.hotElement == null;
        bool flag2 = flag;
        if (flag2)
        {
            if (mouseHint.ShowMouseHintLeft())
            {
                hud.textMouseHintLeft.text = mouseHint.GetTextMouseHintLeft();
                if (hud.textMouseHintLeft.text == "")
                {
                    flag2 = false;
                }
            }
            else
            {
                flag2 = false;
            }
        }
        if (flag)
        {
            if (mouseHint.ShowMouseHintRight())
            {
                hud.textMouseHintRight.text = mouseHint.GetTextMouseHintRight();
                if (hud.textMouseHintRight.text == "")
                {
                    flag = false;
                }
            }
            else
            {
                flag = false;
            }
        }
        hud.textMouseHintLeft.SetActive(flag2);
        hud.textMouseHintRight.SetActive(flag);
        if (flag || flag2)
        {
            hud.textMouseHintLeft.transform.position = UIButton.currentHighlight.transform.position + hud.textMouseHintFixLeft;
            hud.textMouseHintRight.transform.position = UIButton.currentHighlight.transform.position + hud.textMouseHintFix;
            Util.ClampToScreen(hud.textMouseHintRight.Rect(), 10);
        }
    }
References Core.delta, IMouseHint.GetTextMouseHintLeft(), IMouseHint.GetTextMouseHintRight(), IMouseHint.ShowMouseHintLeft(), IMouseHint.ShowMouseHintRight(), HUD.textMouseHintFix, HUD.textMouseHintFixLeft, HUD.textMouseHintLeft, and HUD.textMouseHintRight.
Referenced by OnUpdate().
ShowSceneSelector()
void UI.ShowSceneSelector () inline
Definition at line 472 of file UI.cs.
    {
        canvasScaler.scaleFactor = 1f;
        Shader.SetGlobalFloat("_UIBrightness", 1f);
        Shader.SetGlobalFloat("_UIContrast", 1f);
        layoutLang.SetActive(enable: true);
        List<CoreDebug.StartScene> list = Util.EnumToList<CoreDebug.StartScene>();
        Button t = layoutLang.CreateMold<Button>();
        foreach (CoreDebug.StartScene item in list)
        {
            Button button = Util.Instantiate(t, layoutLang);
            CoreDebug.StartScene _l = item;
            button.GetComponentInChildren<Text>().text = item.ToString();
            button.onClick.AddListener(delegate
            {
                layoutLang.SetActive(enable: false);
                ELayer.debug.startScene = _l;
                ELayer.core.Init();
            });
        }
        layoutLang.RebuildLayout();
    }
References ELayer.core, and Core.Init().
Referenced by ShowLang().
StartDrag()
void UI.StartDrag (DragItem item) inline
Definition at line 743 of file UI.cs.
    {
        Debug.Log(EInput.leftMouse.down);
        dragDuration = 0f;
        if (currentDrag != null)
        {
            EndDrag(canceled: true);
            if (currentDrag != null)
            {
                return;
            }
        }
        currentDrag = item;
        item.OnStartDrag();
        OnDrag();
        ELayer.core.actionsNextFrame.Add(delegate
        {
            TooltipManager.Instance.HideTooltips(immediate: true);
        });
    }
References ELayer.core, and DragItem.OnStartDrag().
ToggleAbility()
void UI.ToggleAbility (bool delay = false) inline
Definition at line 571 of file UI.cs.
    {
        if (ELayer.game.altAbility)
        {
            if ((bool)ELayer.ui.layerFloat.GetLayer<LayerAbility>())
            {
                ELayer.ui.layerFloat.RemoveLayer<LayerAbility>();
                ELayer.player.pref.layerAbility = false;
                SE.Play("pop_ability_deactivate");
            }
            else
            {
                ELayer.ui.layerFloat.AddLayer<LayerAbility>("LayerAbility/LayerAbilityFloat");
                ELayer.player.pref.layerAbility = true;
            }
        }
        else if (!ELayer.ui.RemoveLayer<LayerAbility>())
        {
            LayerAbility layerAbility = ELayer.ui.AddLayer<LayerAbility>();
            if (delay)
            {
                layerAbility.windows[0].SetRect(ELayer.core.refs.rects.center);
                layerAbility.Delay();
            }
        }
    }
References Game.altAbility, CoreRef.Rects.center, ELayer.core, ELayer.game, CoreRef.rects, Core.refs, and ELayer.ui.
ToggleFeedback()
void UI.ToggleFeedback () inline
Definition at line 657 of file UI.cs.
    {
        string text = "";
        if (Application.isEditor)
        {
            text = "Debug";
        }
        else
        {
            try
            {
                if (SteamAPI.IsSteamRunning())
                {
                    text = SteamFriends.GetPersonaName();
                    if (text.IsEmpty())
                    {
                        text = "NULL";
                    }
                }
            }
            catch
            {
            }
        }
        if (text.IsEmpty())
        {
            Dialog.Ok("dialog_needToLogOn");
            return;
        }
        string text2 = "";
        try
        {
            if (!ELayer.config.rewardCode.IsEmpty())
            {
                text2 = "backer";
                text2 = ElinEncoder.GetID(ELayer.config.rewardCode);
            }
        }
        catch (Exception message)
        {
            text2 = "";
            Debug.Log(message);
        }
        if (!Application.isEditor && text2.IsEmpty())
        {
            string pchName = "public";
            try
            {
                if (!SteamApps.GetCurrentBetaName(out pchName, 128) || !(pchName == "nightly"))
                {
                    Dialog.Ok("dialog_feedbackTooMany");
                    return;
                }
                Debug.Log(pchName);
            }
            catch
            {
                Dialog.Ok("dialog_feedbackTooMany");
                return;
            }
        }
        if (ELayer.core.IsGameStarted && !ELayer.ui.GetLayer<LayerFeedback>() && ELayer.pc.HasCondition<ConHallucination>())
        {
            SE.Play("wow");
            Msg.Say("bug_hal");
            return;
        }
        if (!Application.isEditor && (ELayer.debug.enable || ELayer.core.version.demo || (ELayer.core.IsGameStarted && ELayer.player.flags.debugEnabled)))
        {
            Dialog.Ok("dialog_debugFeedback");
            return;
        }
        string userName = "Unknown";
        string[] array = Application.persistentDataPath.Split('/');
        if (array.Length > 2)
        {
            userName = array[2];
        }
        LayerFeedback.userName = userName;
        LayerFeedback.playedHours = ELayer.config.maxPlayedHours;
        LayerFeedback.backerId = text2;
        LayerFeedback.steamName = text;
        ELayer.ui.ToggleLayer<LayerFeedback>();
        SE.Tab();
    }
References ELayer.config, ELayer.core, ELayer.debug, Player.Flags.debugEnabled, CoreDebug.enable, Player.flags, Chara.HasCondition(), Core.IsGameStarted, CoreConfig.maxPlayedHours, Dialog.Ok(), ELayer.pc, ELayer.player, CoreConfig.rewardCode, Msg.Say(), and ELayer.ui.
ToggleInventory()
void UI.ToggleInventory (bool delay = false) inline
Definition at line 598 of file UI.cs.
    {
        if (IsInventoryOpen)
        {
            if (InvOwner.HasTrader)
            {
                SE.Beep();
                return;
            }
            List<Card> list = new List<Card>();
            foreach (LayerInventory item in LayerInventory.listInv)
            {
                if (item.IsPlayerContainer())
                {
                    list.Add(item.invs[0].owner.Container);
                }
            }
            LayerInventory.listInv.ForeachReverse(delegate(LayerInventory l)
            {
                if (l.IsPlayerContainer(includePlayer: true))
                {
                    ELayer.ui.layerFloat.RemoveLayer(l);
                }
            });
            ELayer.ui.widgets.DeactivateWidget("Equip");
            foreach (Card item2 in list)
            {
                item2.c_windowSaveData.open = true;
            }
            SE.Play("pop_inventory_deactivate");
        }
        else
        {
            OpenFloatInv();
        }
    }
References InvOwner.HasTrader, LayerInventory.invs, LayerInventory.IsPlayerContainer(), LayerInventory.listInv, and ELayer.ui.
UnfreezeScreen()
void UI.UnfreezeScreen () inline
Definition at line 562 of file UI.cs.
    {
        if ((bool)texFreeze)
        {
            UnityEngine.Object.DestroyImmediate(texFreeze);
        }
        imageFreeze.SetActive(enable: false);
    }
Member Data Documentation
_rectLayers
RectTransform UI._rectLayers
Definition at line 31 of file UI.cs.
autoTurn
UIAutoTurn UI.autoTurn
Definition at line 51 of file UI.cs.
blur
GameObject UI.blur
Definition at line 35 of file UI.cs.
blurSize
float UI.blurSize static private
Definition at line 11 of file UI.cs.
blurSpeed
float UI.blurSpeed
Definition at line 57 of file UI.cs.
canvas
Canvas UI.canvas
Definition at line 13 of file UI.cs.
canvasScaler
CanvasScaler UI.canvasScaler
Definition at line 41 of file UI.cs.
cg
CanvasGroup UI.cg
Definition at line 45 of file UI.cs.
console
ReflexConsole UI.console
Definition at line 33 of file UI.cs.
contextMenu
UIContextMenuManager UI.contextMenu
Definition at line 21 of file UI.cs.
currentDrag
DragItem UI.currentDrag
Definition at line 63 of file UI.cs.
dragDuration
float UI.dragDuration
Definition at line 73 of file UI.cs.
durationHideMouseHint
float UI.durationHideMouseHint private
Definition at line 83 of file UI.cs.
extraHint
ExtraHint UI.extraHint
Definition at line 17 of file UI.cs.
hidingCover
bool UI.hidingCover private
Definition at line 67 of file UI.cs.
hud
HUD UI.hud
Definition at line 15 of file UI.cs.
Referenced by AM_Dig.OnSelectEnd(), and AM_Dig.OnSelectStart().
imageFreeze
RawImage UI.imageFreeze
Definition at line 61 of file UI.cs.
inputModule
InputModuleEX UI.inputModule
Definition at line 19 of file UI.cs.
isPointerOverUI
bool UI.isPointerOverUI
Definition at line 81 of file UI.cs.
Referenced by AM_BaseGameMode.OnUpdateInput().
layerFloat
Layer UI.layerFloat
Definition at line 49 of file UI.cs.
Referenced by AM_Bird.OnActivate(), AM_NoMap.OnActivate(), AM_ViewMap.OnActivate(), InvOwnerHotbar.OnClick(), AM_Bird.OnDeactivate(), AM_NoMap.OnDeactivate(), AM_ViewMap.OnDeactivate(), and TraitScrollMapTreasure.OnUse().
layoutLang
LayoutGroup UI.layoutLang
Definition at line 39 of file UI.cs.
light
Image UI.light
Definition at line 43 of file UI.cs.
lightContrast
float UI.lightContrast
Definition at line 70 of file UI.cs.
matBlur
Material UI.matBlur
Definition at line 37 of file UI.cs.
minWidth
int UI.minWidth
Definition at line 47 of file UI.cs.
mouseInfo
UIMouseInfo UI.mouseInfo
Definition at line 25 of file UI.cs.
nextDrag
DragItem UI.nextDrag
Definition at line 65 of file UI.cs.
popGame
PopManager UI.popGame
Definition at line 53 of file UI.cs.
popSystem
PopManager UI.popSystem
Definition at line 55 of file UI.cs.
rectDynamic
RectTransform UI.rectDynamic
Definition at line 27 of file UI.cs.
rectDynamicEssential
RectTransform UI.rectDynamicEssential
Definition at line 29 of file UI.cs.
texFreeze
Texture2D UI.texFreeze
Definition at line 59 of file UI.cs.
tweenCover
Tween UI.tweenCover private
Definition at line 75 of file UI.cs.
wasActive
bool UI.wasActive
Definition at line 78 of file UI.cs.
Referenced by AM_Sim._OnUpdateInput().
widgets
WidgetManager UI.widgets
Definition at line 23 of file UI.cs.
Referenced by HotItemToggleWidget.OnClick().
Property Documentation
AllowInventoryInteractions
bool UI.AllowInventoryInteractions get
Definition at line 99 of file UI.cs.
    {
        get
        {
            if (!contextMenu.isActive)
            {
                if (layers.Count != 0)
                {
                    return base.TopLayer.option.allowInventoryInteraction;
                }
                return true;
            }
            return false;
        }
    }
BlockActions
bool UI.BlockActions get
Definition at line 115 of file UI.cs.
    {
        get
        {
            if (!wasActive || ((bool)base.TopLayer && base.TopLayer.option.passive))
            {
                return EInput.isInputFieldActive;
            }
            return true;
        }
    }
BlockInput
bool UI.BlockInput get
Definition at line 129 of file UI.cs.
    {
        get
        {
            if (!IsDragging && !IsBlockWidgetClick() && !(LayerAbility.hotElement != null) && !EInput.isInputFieldActive)
            {
                return contextMenu.isActive;
            }
            return true;
        }
    }
BlockMouseOverUpdate
bool UI.BlockMouseOverUpdate get
Definition at line 127 of file UI.cs.
blockWidgetClick
override bool UI.blockWidgetClick get
Definition at line 157 of file UI.cs.
IsAbilityOpen
bool UI.IsAbilityOpen get
Definition at line 155 of file UI.cs.
IsActive
bool UI.IsActive get
Definition at line 87 of file UI.cs.
    {
        get
        {
            if (layers.Count <= 0)
            {
                return contextMenu.isActive;
            }
            return true;
        }
    }
Referenced by RefreshActiveState().
IsDragging
bool UI.IsDragging get
Definition at line 161 of file UI.cs.
IsInventoryOpen
bool UI.IsInventoryOpen get
Definition at line 153 of file UI.cs.
IsPauseGame
bool UI.IsPauseGame get
Definition at line 141 of file UI.cs.
    {
        get
        {
            if (layers.Count > 0)
            {
                return base.TopLayer.option.pauseGame;
            }
            return false;
        }
    }
rectLayers
override RectTransform UI.rectLayers get
Definition at line 159 of file UI.cs.
skins
SkinManager UI.skins get
Definition at line 85 of file UI.cs.
The documentation for this class was generated from the following file:
Elin/UI.cs