Elin Decompiled Documentation: SourceReligion Class Reference
SourceReligion Class Reference
Classes
class Row
Public Member Functions
override Row CreateRow ()
override Row CreateRowByMapping (IReadOnlyDictionary< string, int > mapping)
override void SetRow (Row r)
override IReadOnlyDictionary< string, int > GetRowMapping ()
override IReadOnlyDictionary< string, string > GetTypeMapping ()
Public Member Functions inherited from SourceDataString< SourceReligion.Row >
override T GetRow (string id)
Static Public Attributes
static readonly IReadOnlyDictionary< string, int > RowMapping
static readonly IReadOnlyDictionary< string, string > TypeMapping
Properties
override string[] ImportFields [get]
Detailed Description
Definition at line 4 of file SourceReligion.cs.
Member Function Documentation
CreateRow()
override Row SourceReligion.CreateRow () inline
Definition at line 131 of file SourceReligion.cs.
    {
        return new Row
        {
            id = SourceData.GetString(0),
            name_JP = SourceData.GetString(1),
            name = SourceData.GetString(2),
            name2_JP = SourceData.GetStringArray(3),
            name2 = SourceData.GetStringArray(4),
            type = SourceData.GetString(5),
            idMaterial = SourceData.GetString(6),
            faith = SourceData.GetString(7),
            domain = SourceData.GetString(8),
            tax = SourceData.GetInt(9),
            relation = SourceData.GetInt(10),
            elements = Core.ParseElements(SourceData.GetStr(11)),
            cat_offer = SourceData.GetStringArray(12),
            rewards = SourceData.GetStringArray(13),
            textType_JP = SourceData.GetString(14),
            textType = SourceData.GetString(15),
            textAvatar = SourceData.GetString(16),
            detail_JP = SourceData.GetString(17),
            detail = SourceData.GetString(18),
            textBenefit_JP = SourceData.GetString(19),
            textBenefit = SourceData.GetString(20),
            textPet_JP = SourceData.GetString(21),
            textPet = SourceData.GetString(22)
        };
    }
References faith, SourceData< T, T2 >.GetInt(), SourceData< T, T2 >.GetStr(), SourceData< T, T2 >.GetString(), SourceData< T, T2 >.GetStringArray(), and Core.ParseElements().
CreateRowByMapping()
override Row SourceReligion.CreateRowByMapping (IReadOnlyDictionary< string, int > mapping) inline
Definition at line 161 of file SourceReligion.cs.
    {
        return new Row
        {
            id = SourceData.GetString(mapping["id"]),
            name_JP = SourceData.GetString(mapping["name_JP"]),
            name = SourceData.GetString(mapping["name"]),
            name2_JP = SourceData.GetStringArray(mapping["name2_JP"]),
            name2 = SourceData.GetStringArray(mapping["name2"]),
            type = SourceData.GetString(mapping["type"]),
            idMaterial = SourceData.GetString(mapping["idMaterial"]),
            faith = SourceData.GetString(mapping["faith"]),
            domain = SourceData.GetString(mapping["domain"]),
            tax = SourceData.GetInt(mapping["tax"]),
            relation = SourceData.GetInt(mapping["relation"]),
            elements = Core.ParseElements(SourceData.GetStr(mapping["elements"])),
            cat_offer = SourceData.GetStringArray(mapping["cat_offer"]),
            rewards = SourceData.GetStringArray(mapping["rewards"]),
            textType_JP = SourceData.GetString(mapping["textType_JP"]),
            textType = SourceData.GetString(mapping["textType"]),
            textAvatar = SourceData.GetString(mapping["textAvatar"]),
            detail_JP = SourceData.GetString(mapping["detail_JP"]),
            detail = SourceData.GetString(mapping["detail"]),
            textBenefit_JP = SourceData.GetString(mapping["textBenefit_JP"]),
            textBenefit = SourceData.GetString(mapping["textBenefit"]),
            textPet_JP = SourceData.GetString(mapping["textPet_JP"]),
            textPet = SourceData.GetString(mapping["textPet"])
        };
    }
References faith, SourceData< T, T2 >.GetInt(), SourceData< T, T2 >.GetStr(), SourceData< T, T2 >.GetString(), SourceData< T, T2 >.GetStringArray(), and Core.ParseElements().
GetRowMapping()
override IReadOnlyDictionary< string, int > SourceReligion.GetRowMapping () inline
Definition at line 196 of file SourceReligion.cs.
    {
        return RowMapping;
    }
References RowMapping.
GetTypeMapping()
override IReadOnlyDictionary< string, string > SourceReligion.GetTypeMapping () inline
Definition at line 201 of file SourceReligion.cs.
    {
        return TypeMapping;
    }
References TypeMapping.
SetRow()
override void SourceReligion.SetRow (Row r) inline
Definition at line 191 of file SourceReligion.cs.
    {
        map[r.id] = r;
    }
References SourceReligion.Row.id.
Member Data Documentation
RowMapping
readonly IReadOnlyDictionary<string, int> SourceReligion.RowMapping static
Initial value:
= new Dictionary<string, int>
    {
        ["id"] = 0,
        ["name_JP"] = 1,
        ["name"] = 2,
        ["name2_JP"] = 3,
        ["name2"] = 4,
        ["type"] = 5,
        ["idMaterial"] = 6,
        ["faith"] = 7,
        ["domain"] = 8,
        ["tax"] = 9,
        ["relation"] = 10,
        ["elements"] = 11,
        ["cat_offer"] = 12,
        ["rewards"] = 13,
        ["textType_JP"] = 14,
        ["textType"] = 15,
        ["textAvatar"] = 16,
        ["detail_JP"] = 17,
        ["detail"] = 18,
        ["textBenefit_JP"] = 19,
        ["textBenefit"] = 20,
        ["textPet_JP"] = 21,
        ["textPet"] = 22
    }
Definition at line 75 of file SourceReligion.cs.
Referenced by GetRowMapping().
TypeMapping
readonly IReadOnlyDictionary<string, string> SourceReligion.TypeMapping static
Initial value:
= new Dictionary<string, string>
    {
        ["id"] = "string",
        ["name_JP"] = "string",
        ["name"] = "string",
        ["name2_JP"] = "string[]",
        ["name2"] = "string[]",
        ["type"] = "string",
        ["idMaterial"] = "string",
        ["faith"] = "string",
        ["domain"] = "string",
        ["tax"] = "int",
        ["relation"] = "int",
        ["elements"] = "elements",
        ["cat_offer"] = "string[]",
        ["rewards"] = "string[]",
        ["textType_JP"] = "string",
        ["textType"] = "string",
        ["textAvatar"] = "string",
        ["detail_JP"] = "string",
        ["detail"] = "string",
        ["textBenefit_JP"] = "string",
        ["textBenefit"] = "string",
        ["textPet_JP"] = "string",
        ["textPet"] = "string"
    }
Definition at line 102 of file SourceReligion.cs.
Referenced by GetTypeMapping().
Property Documentation
ImportFields
override string [] SourceReligion.ImportFields get
Definition at line 129 of file SourceReligion.cs.
The documentation for this class was generated from the following file:
Elin/SourceReligion.cs