Elin Decompiled Documentation: AreaTypeFarm Class Reference
AreaTypeFarm Class Reference
Public Member Functions
override AIAct GetAI ()
Point GetPlowPos ()
Public Member Functions inherited from AreaType
virtual AIAct GetAI ()
virtual int GetEfficiency ()
Public Attributes
int refSeed
Public Attributes inherited from AreaType
HashSet< int > uidCharas = new HashSet<int>()
string id = "Public"
BaseArea owner
SourceArea.Row _source
Properties
override bool IsWork [get]
Properties inherited from AreaType
virtual bool CanAssign [get]
virtual bool IsWork [get]
virtual bool IsPublicArea [get]
virtual bool IsPrison [get]
virtual string RandomNameGroup [get]
string langHeader [get]
SourceArea.Row source [get]
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Additional Inherited Members
Static Public Member Functions inherited from EClass
static int rndSeed (int a, int seed)
static int rnd (int a)
static int curve (int a, int start, int step, int rate=75)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Static Public Attributes inherited from EClass
static Core core
Detailed Description
Definition at line 4 of file AreaTypeFarm.cs.
Member Function Documentation
GetAI()
override AIAct AreaTypeFarm.GetAI () inline virtual
Reimplemented from AreaType.
Definition at line 11 of file AreaTypeFarm.cs.
    {
        Point plowPos = GetPlowPos();
        if (plowPos != null)
        {
            if (plowPos.HasObj)
            {
                return new TaskCut
                {
                    pos = plowPos.Copy()
                };
            }
            return new AI_Farm
            {
                pos = plowPos.Copy()
            };
        }
        if (EClass.rnd(3) == 0)
        {
            return new AI_Farm
            {
                pos = owner.GetRandomFreePos()
            };
        }
        if (EClass.rnd(3) == 0)
        {
            return new AI_Water
            {
                pos = owner.GetRandomFreePos()
            };
        }
        return base.GetAI();
    }
References Point.Copy(), GetPlowPos(), BaseArea.GetRandomFreePos(), Point.HasObj, AreaType.owner, and EClass.rnd().
GetPlowPos()
Point AreaTypeFarm.GetPlowPos () inline
Definition at line 45 of file AreaTypeFarm.cs.
    {
        List<Point> list = new List<Point>();
        foreach (Point point in owner.points)
        {
            if ((point.sourceFloor.ContainsTag("grass") || point.sourceFloor.tag.Contains("soil")) && (!point.IsFarmField || point.HasObj))
            {
                list.Add(point);
            }
        }
        if (list.Count > 0)
        {
            return list.RandomItem();
        }
        return null;
    }
References Point.HasObj, Point.IsFarmField, AreaType.owner, BaseArea.points, and Point.sourceFloor.
Referenced by GetAI().
Member Data Documentation
refSeed
int AreaTypeFarm.refSeed
Definition at line 7 of file AreaTypeFarm.cs.
Property Documentation
IsWork
override bool AreaTypeFarm.IsWork get
Definition at line 9 of file AreaTypeFarm.cs.
The documentation for this class was generated from the following file:
Elin/AreaTypeFarm.cs