Elin Decompiled Documentation: EffectMeteor Class Reference
EffectMeteor Class Reference
Public Member Functions
override void OnPlay ()
Public Member Functions inherited from Effect
void Play (float delay, Point from, float fixY=0f, Point to=null, Sprite sprite=null)
Effect Play (Point from, float fixY=0f, Point to=null, Sprite sprite=null)
Effect _Play (Point from, Vector3 fromV, float fixY=0f, Point to=null, Sprite sprite=null)
Effect Play (Vector3 v)
Effect Flip (bool x=false, bool y=false)
Effect SetStartDelay (float a)
virtual void OnPlay ()
virtual void OnUpdate ()
void Kill ()
virtual void OnKill ()
void OnDisable ()
void OnDestroy ()
Effect Emit (int num)
Effect SetParticleColor (Color c)
Effect SetParticleColor (Color color, bool changeMaterial=false, string idCol="_Color")
Effect SetScale (float a)
Static Public Member Functions
static void Create (Point center, int radius, int count, Action< int, Point > onComplete)
Static Public Member Functions inherited from Effect
static Effect Get (Effect original)
static Effect Get (string id)
static T Get< T > (string id)
Static Public Member Functions inherited from EMono
static int rnd (int a)
Public Attributes
Animator aniExplosion
Vector3 startPos
float time
Public Attributes inherited from Effect
Type type
float duration = 1f
float speed
float startDelay
bool lookAtTarget
bool rotate
bool pool
SpriteRenderer sr
ParticleSystem[] systems
Vector3[] dirs
Ease ease
Vector3 posFix
Vector3 randomRange
Tween moveTween
Sprite[] sprites
bool randomFlip
bool randomSpeed
bool test
bool setColor = true
Action onComplete
int spriteIndex
float timer
Vector3 fromV
Vector3 destV
bool pooled
Transform poolParent
List< Material > materialsToDestroy
Point destPos
Tween killTimer
Additional Inherited Members
Public Types inherited from Effect
enum Type { Default , Firework }
Static Public Attributes inherited from EMono
static Core core
Protected Member Functions inherited from Effect
void Activate ()
Protected Attributes inherited from Effect
bool killed
Properties inherited from Effect
static EffectManager manager [get]
Properties inherited from EMono
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SoundManager Sound [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static CoreDebug debug [get]
Detailed Description
Definition at line 6 of file EffectMeteor.cs.
Member Function Documentation
Create()
static void EffectMeteor.Create (Point center, int radius, int count, Action< int, Point > onComplete) inline static
Definition at line 33 of file EffectMeteor.cs.
    {
        List<Point> list = new List<Point>();
        for (int i = 0; i < count; i++)
        {
            Point p = center.Copy();
            Effect effect = Effect.Get("meteor");
            effect.startDelay = Rand.Range(0f, 0.5f);
            if (radius > 0)
            {
                int num = 0;
                if (num < 1000)
                {
                    Point randomSurface = EMono._map.GetRandomSurface(center.x, center.z, radius);
                    foreach (Point item in list)
                    {
                        randomSurface.Equals(item);
                    }
                    p.Set(randomSurface);
                    list.Add(randomSurface);
                }
            }
            int _i = i;
            effect.onComplete = delegate
            {
                onComplete(_i, p);
            };
            effect.Play(p);
        }
    }
References EMono._map, Point.Copy(), Point.Equals(), Effect.Get(), MapBounds.GetRandomSurface(), item, Effect.onComplete, Effect.Play(), Rand.Range(), Point.Set(), Point.x, and Point.z.
Referenced by ActEffect.ProcAt().
OnPlay()
override void EffectMeteor.OnPlay () inline virtual
Reimplemented from Effect.
Definition at line 14 of file EffectMeteor.cs.
    {
        sr.enabled = true;
        aniExplosion.SetActive(enable: false);
        destV = fromV;
        fromV += startPos + startPos.Random() * 0.2f;
        base.transform.position = fromV;
        moveTween = base.transform.DOMove(destV, time).SetEase(Ease.Linear).SetDelay(startDelay)
            .OnComplete(delegate
            {
                sr.enabled = false;
                aniExplosion.SetActive(enable: true);
                destPos.Animate(AnimeID.Dig, animeBlock: true);
                onComplete?.Invoke();
                EMono.Sound.Play("explode", destV);
                Shaker.ShakeCam("meteor");
            });
    }
References aniExplosion, Point.Animate(), Effect.destPos, Effect.destV, Effect.fromV, Effect.moveTween, Effect.onComplete, Shaker.ShakeCam(), EMono.Sound, Effect.startDelay, startPos, and time.
Member Data Documentation
aniExplosion
Animator EffectMeteor.aniExplosion
Definition at line 8 of file EffectMeteor.cs.
Referenced by OnPlay().
startPos
Vector3 EffectMeteor.startPos
Definition at line 10 of file EffectMeteor.cs.
Referenced by OnPlay().
time
float EffectMeteor.time
Definition at line 12 of file EffectMeteor.cs.
Referenced by OnPlay().
The documentation for this class was generated from the following file:
Elin/EffectMeteor.cs