Elin Decompiled Documentation: UIMapPreview.GenThread Class Reference
UIMapPreview.GenThread Class Reference
Public Member Functions
void Init ()
void Reset ()
void Start ()
Public Attributes
ZoneBlueprint bp
Map map
bool done = true
Additional Inherited Members
Static Public Member Functions inherited from EClass
static int rndSeed (int a, int seed)
static int rnd (long a)
static int rnd (int a)
static int curve (int _a, int start, int step, int rate=75)
static int sqrt (int a)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Static Public Attributes inherited from EClass
static Core core
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Detailed Description
Definition at line 9 of file UIMapPreview.cs.
Member Function Documentation
Init()
void UIMapPreview.GenThread.Init () inline
Definition at line 17 of file UIMapPreview.cs.
        {
            bp = new ZoneBlueprint();
            bp.Create();
            Reset();
        }
References UIMapPreview.GenThread.bp, ZoneBlueprint.Create(), and UIMapPreview.GenThread.Reset().
Referenced by UIMapPreview.GenerateMap().
Reset()
void UIMapPreview.GenThread.Reset () inline
Definition at line 24 of file UIMapPreview.cs.
        {
            done = false;
        }
References UIMapPreview.GenThread.done.
Referenced by UIMapPreview.GenerateMap(), and UIMapPreview.GenThread.Init().
Start()
void UIMapPreview.GenThread.Start () inline
Definition at line 29 of file UIMapPreview.cs.
        {
            done = true;
        }
References UIMapPreview.GenThread.done.
Referenced by UIMapPreview.GenerateMap().
Member Data Documentation
bp
ZoneBlueprint UIMapPreview.GenThread.bp
Definition at line 11 of file UIMapPreview.cs.
Referenced by UIMapPreview.CheckThread(), UIMapPreview.GenThread.Init(), and LayerEmbark.OnClickPreview().
done
bool UIMapPreview.GenThread.done = true
Definition at line 15 of file UIMapPreview.cs.
Referenced by UIMapPreview.CheckThread(), UIMapPreview.GenerateMap(), LayerEmbark.RerollPreviewMap(), UIMapPreview.GenThread.Reset(), and UIMapPreview.GenThread.Start().
map
Map UIMapPreview.GenThread.map
Definition at line 13 of file UIMapPreview.cs.
The documentation for this class was generated from the following file:
Elin/UIMapPreview.cs