Elin Decompiled Documentation: SourceMaterial.Tier Class Reference
SourceMaterial.Tier Class Reference
Public Member Functions
SourceMaterial.Row Select ()
Public Attributes
int sum
List< SourceMaterial.Row > list = new List<SourceMaterial.Row>()
Detailed Description
Definition at line 482 of file SourceMaterial.cs.
Member Function Documentation
Select()
SourceMaterial.Row SourceMaterial.Tier.Select () inline
Definition at line 484 of file SourceMaterial.cs.
        {
            int num = 0;
            int num2 = EClass.rnd(this.sum);
            foreach (SourceMaterial.Row row in this.list)
            {
                num += row.chance;
                if (num2 < num)
                {
                    return row;
                }
            }
            return this.list.RandomItem<SourceMaterial.Row>();
        }
References SourceMaterial.Tier.list, EClass.rnd(), and SourceMaterial.Tier.sum.
Referenced by MATERIAL.GetRandomMaterial().
Member Data Documentation
list
List<SourceMaterial.Row> SourceMaterial.Tier.list = new List<SourceMaterial.Row>()
Definition at line 501 of file SourceMaterial.cs.
Referenced by MATERIAL.GetRandomMaterial(), SourceMaterial.OnInit(), and SourceMaterial.Tier.Select().
sum
int SourceMaterial.Tier.sum
Definition at line 499 of file SourceMaterial.cs.
Referenced by SourceMaterial.Tier.Select().
The documentation for this class was generated from the following file:
Elin/SourceMaterial.cs