Elin Decompiled Documentation: ItemQuest Class Reference
ItemQuest Class Reference
Public Member Functions
void SetQuest (Quest q)
Public Attributes
Portrait portrait
UIButton button
UIText textDetail
UIText textReward
UIText textDate
UIText textDifficulty
UIText textExtra
UIText textExtra2
Image imageNew
Additional Inherited Members
Static Public Member Functions inherited from EMono
static int rnd (int a)
Static Public Attributes inherited from EMono
static Core core
Properties inherited from EMono
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SoundManager Sound [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static CoreDebug debug [get]
Detailed Description
Definition at line 4 of file ItemQuest.cs.
Member Function Documentation
SetQuest()
void ItemQuest.SetQuest (Quest q) inline
Definition at line 6 of file ItemQuest.cs.
    {
        this.portrait.SetPerson(q.person);
        this.button.mainText.text = (EMono.game.quests.list.Contains(q) ? "questInProgress".lang().TagColor(FontColor.Good, null) : "") + q.TitlePrefix + q.GetTitle();
        this.button.subText.text = q.person.NameBraced;
        this.textDate.SetText(Date.GetText(q.Hours));
        this.textDate.transform.parent.RebuildLayout(false);
        this.textReward.SetText(q.GetRewardText());
        string text = q.GetDetail(false);
        QuestSupply questSupply = q as QuestSupply;
        if (questSupply != null && questSupply.GetDestThing() != null)
        {
            text = "questSupplyOwned".lang().TagColor(FontColor.Good, null) + text;
        }
        this.textDetail.SetText(text);
        this.imageNew.SetActive(q.isNew);
        q.isNew = false;
        this.textDifficulty.SetText("★".Repeat(q.difficulty));
        this.textDifficulty.SetActive(q.IsRandomQuest);
        string text2 = q.TextExtra;
        this.textExtra.SetActive(!text2.IsEmpty());
        this.textExtra.SetText(text2);
        text2 = q.TextExtra2;
        this.textExtra2.SetActive(!text2.IsEmpty());
        this.textExtra2.SetText(text2);
    }
References Quest.difficulty, EMono.game, QuestDeliver.GetDestThing(), Quest.GetDetail(), Quest.GetRewardText(), Date.GetText(), Quest.GetTitle(), Quest.Hours, imageNew, Quest.isNew, Quest.IsRandomQuest, QuestManager.list, Person.NameBraced, Quest.person, portrait, Game.quests, Portrait.SetPerson(), text, textDate, textDetail, textDifficulty, textExtra, Quest.TextExtra, textExtra2, Quest.TextExtra2, textReward, and Quest.TitlePrefix.
Referenced by LayerQuestBoard.RefreshQuest().
Member Data Documentation
button
UIButton ItemQuest.button
Definition at line 35 of file ItemQuest.cs.
Referenced by LayerQuestBoard.RefreshQuest().
imageNew
Image ItemQuest.imageNew
Definition at line 49 of file ItemQuest.cs.
Referenced by SetQuest().
portrait
Portrait ItemQuest.portrait
Definition at line 33 of file ItemQuest.cs.
Referenced by SetQuest().
textDate
UIText ItemQuest.textDate
Definition at line 41 of file ItemQuest.cs.
Referenced by SetQuest().
textDetail
UIText ItemQuest.textDetail
Definition at line 37 of file ItemQuest.cs.
Referenced by SetQuest().
textDifficulty
UIText ItemQuest.textDifficulty
Definition at line 43 of file ItemQuest.cs.
Referenced by SetQuest().
textExtra
UIText ItemQuest.textExtra
Definition at line 45 of file ItemQuest.cs.
Referenced by SetQuest().
textExtra2
UIText ItemQuest.textExtra2
Definition at line 47 of file ItemQuest.cs.
Referenced by SetQuest().
textReward
UIText ItemQuest.textReward
Definition at line 39 of file ItemQuest.cs.
Referenced by SetQuest().
The documentation for this class was generated from the following file:
Elin/ItemQuest.cs