Elin Decompiled Documentation: EScriptable Class Reference
EScriptable Class Reference
Static Public Member Functions
static int rnd (int a)
Detailed Description
Definition at line 3 of file EScriptable.cs.
Member Function Documentation
rnd()
static int EScriptable.rnd (int a) inline static
Definition at line 5 of file EScriptable.cs.
    {
        return Rand.rnd(a);
    }
References Rand.rnd().
Referenced by CoreDebug.COM_Teleport(), Crawler.Crawl(), BiomeProfile.Tile.GetDir(), MapPiece.GetMap(), CoreDebug.QuickStart(), CoreDebug.SetStartStockpile(), BiomeProfile.ClusterObj.TryCreate(), and CoreDebug.UpdateInput().
The documentation for this class was generated from the following file:
Elin/EScriptable.cs