Elin Decompiled Documentation: Hotbar Class Reference
Hotbar Class Reference
Classes
class Page
Public Types
enum Type { Default , Main , ZoomMenu }
Public Member Functions
void SetSlotNum (int a)
void AddPage ()
void ValidatePage (Hotbar.Page page, int num=-1)
void SetPage (int pageIndex)
void Remove (HotItem item)
HotItem GetItem (int index, int pageIndex=-1)
HotItem SetItem (HotItem item, int index=-1, int pageIndex=-1, bool refreshActor=false)
void Select (HotItem item)
void ToggleDisable (HotItem item)
void Unselect (int pageIndex=-1)
HotItem GetSelectedItem ()
int GetNextSelectableIndex (int pageIndex=-1)
int GetPrevSelectableIndex (int pageIndex=-1)
Public Attributes
int currentPage
int itemsPerPage = 6
int id
List< Hotbar.Page > pages = new List<Hotbar.Page>()
bool dirty
WidgetHotbar actor
Static Public Attributes
const int IDMainMenu = 2
const int IDBuild = 3
const int IDUser2 = 5
const int IDUser3 = 6
const int IDSpeed = 7
Static Public Attributes inherited from EClass
static Core core
Properties
HotbarManager manager [get]
HotItem SelectedItem [get]
HotItem DefaultItem [get]
bool IsLocked [get]
bool IsUserHotbar [get]
bool ShowFunctionKey [get]
Hotbar.Page CurrentPage [get]
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Additional Inherited Members
Static Public Member Functions inherited from EClass
static int rnd (int a)
static int curve (int a, int start, int step, int rate=75)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Detailed Description
Definition at line 5 of file Hotbar.cs.
Member Enumeration Documentation
Type
enum Hotbar.Type
Enumerator
Default
Main
ZoomMenu
Definition at line 248 of file Hotbar.cs.
    {
        Default,
        Main,
        ZoomMenu
    }
Member Function Documentation
AddPage()
void Hotbar.AddPage () inline
Definition at line 72 of file Hotbar.cs.
    {
        Hotbar.Page page = new Hotbar.Page();
        this.pages.Add(page);
        this.ValidatePage(page, -1);
    }
References pages, and ValidatePage().
Referenced by HotbarManager.SetHobar(), and SetItem().
GetItem()
HotItem Hotbar.GetItem (int index, int pageIndex = -1) inline
Definition at line 114 of file Hotbar.cs.
    {
        return this.pages[(pageIndex == -1) ? this.currentPage : pageIndex].GetItem(index);
    }
References currentPage, GetItem(), and pages.
Referenced by GetItem(), and WidgetHotbar.RebuildPage().
GetNextSelectableIndex()
int Hotbar.GetNextSelectableIndex (int pageIndex = -1) inline
Definition at line 190 of file Hotbar.cs.
    {
        if (pageIndex == -1)
        {
            pageIndex = this.currentPage;
        }
        Hotbar.Page page = this.pages[pageIndex];
        int num = page.selected + 1;
        if (num >= this.itemsPerPage)
        {
            num = -1;
        }
        this.ValidatePage(page, -1);
        return num;
    }
References currentPage, itemsPerPage, pages, and ValidatePage().
GetPrevSelectableIndex()
int Hotbar.GetPrevSelectableIndex (int pageIndex = -1) inline
Definition at line 206 of file Hotbar.cs.
    {
        if (pageIndex == -1)
        {
            pageIndex = this.currentPage;
        }
        Hotbar.Page page = this.pages[pageIndex];
        int num = page.selected - 1;
        if (num < -1)
        {
            num = this.itemsPerPage - 1;
        }
        this.ValidatePage(page, -1);
        return num;
    }
References currentPage, pages, and ValidatePage().
GetSelectedItem()
HotItem Hotbar.GetSelectedItem () inline
Definition at line 180 of file Hotbar.cs.
    {
        int selected = this.pages[this.currentPage].selected;
        if (selected == -1)
        {
            return null;
        }
        return this.pages[this.currentPage].items[selected];
    }
References currentPage, and pages.
Remove()
void Hotbar.Remove (HotItem item) inline
Definition at line 100 of file Hotbar.cs.
    {
        for (int i = 0; i < this.pages.Count; i++)
        {
            for (int j = 0; j < this.pages[i].items.Count; j++)
            {
                if (this.pages[i].items[j] == item)
                {
                    this.SetItem(null, j, i, true);
                }
            }
        }
    }
References pages, and SetItem().
Select()
void Hotbar.Select (HotItem item) inline
Definition at line 148 of file Hotbar.cs.
    {
        SE.SelectHotitem();
        EClass.player.SetCurrentHotItem(item);
    }
References EClass.player, and Player.SetCurrentHotItem().
Referenced by HotItemGameAction.OnClick(), and HotItemGameAction.OnRightClick().
SetItem()
HotItem Hotbar.SetItem (HotItem item, int index = -1, int pageIndex = -1, bool refreshActor = false) inline
Definition at line 119 of file Hotbar.cs.
    {
        if (item == null)
        {
            item = this.DefaultItem;
        }
        if (pageIndex == -1)
        {
            pageIndex = this.currentPage;
        }
        if (pageIndex >= this.pages.Count)
        {
            this.AddPage();
            pageIndex = this.pages.Count - 1;
        }
        Hotbar.Page page = this.pages[pageIndex];
        this.ValidatePage(page, index + 1);
        page.SetItem(this, item, index);
        if (item != null)
        {
            item.OnAddedToBar();
        }
        if (refreshActor && this.actor)
        {
            this.actor.RebuildPage(-1);
        }
        return item;
    }
References actor, AddPage(), currentPage, DefaultItem, pages, WidgetHotbar.RebuildPage(), Hotbar.Page.SetItem(), and ValidatePage().
Referenced by WidgetHotbar.OnSetContextMenu(), Remove(), HotbarManager.ResetHotbar(), and WidgetHotbar.SetItem().
SetPage()
void Hotbar.SetPage (int pageIndex) inline
Definition at line 95 of file Hotbar.cs.
    {
        this.currentPage = pageIndex;
    }
Referenced by WidgetHotbar.RebuildPage().
SetSlotNum()
void Hotbar.SetSlotNum (int a) inline
Definition at line 63 of file Hotbar.cs.
    {
        this.itemsPerPage = a;
        foreach (Hotbar.Page page in this.pages)
        {
            this.ValidatePage(page, -1);
        }
    }
References ValidatePage().
Referenced by WidgetHotbar.OnSetContextMenu().
ToggleDisable()
void Hotbar.ToggleDisable (HotItem item) inline
Definition at line 154 of file Hotbar.cs.
    {
        item.disabled = !item.disabled;
        if (item.disabled)
        {
            item.OnUnselect();
        }
        SE.SelectHotitem();
        EClass.player.SetCurrentHotItem(item.disabled ? null : item);
    }
References HotItem.disabled, HotItem.OnUnselect(), EClass.player, and Player.SetCurrentHotItem().
Unselect()
void Hotbar.Unselect (int pageIndex = -1) inline
Definition at line 165 of file Hotbar.cs.
    {
        if (pageIndex == -1)
        {
            pageIndex = this.currentPage;
        }
        HotItem selectedItem = this.pages[pageIndex].SelectedItem;
        this.pages[pageIndex].selected = -1;
        if (selectedItem != null)
        {
            selectedItem.OnUnselect();
        }
        EClass.player.SetCurrentHotItem(null);
    }
References currentPage, HotItem.OnUnselect(), pages, EClass.player, and Player.SetCurrentHotItem().
ValidatePage()
void Hotbar.ValidatePage (Hotbar::Page page, int num = -1) inline
Definition at line 79 of file Hotbar.cs.
    {
        if (num != -1 && this.itemsPerPage < num)
        {
            this.itemsPerPage = num;
        }
        if (page.items.Count < this.itemsPerPage)
        {
            int num2 = this.itemsPerPage - page.items.Count;
            for (int i = 0; i < num2; i++)
            {
                page.items.Add(this.DefaultItem);
            }
        }
    }
References DefaultItem, and itemsPerPage.
Referenced by AddPage(), GetNextSelectableIndex(), GetPrevSelectableIndex(), SetItem(), and SetSlotNum().
Member Data Documentation
actor
WidgetHotbar Hotbar.actor
Definition at line 246 of file Hotbar.cs.
Referenced by WidgetHotbar.OnEndDrag(), HotbarManager.ResetHotbar(), and SetItem().
currentPage
int Hotbar.currentPage
Definition at line 233 of file Hotbar.cs.
Referenced by GetItem(), GetNextSelectableIndex(), GetPrevSelectableIndex(), GetSelectedItem(), WidgetHotbar.RebuildPage(), SetItem(), WidgetHotbar.SwitchPage(), and Unselect().
dirty
bool Hotbar.dirty
Definition at line 244 of file Hotbar.cs.
Referenced by WidgetMenuPanel.Build(), WidgetHotbar.OnChangeActionMode(), and BuildMenu.Toggle().
id
int Hotbar.id
Definition at line 239 of file Hotbar.cs.
Referenced by WidgetHotbar.OnSetContextMenu().
IDBuild
const int Hotbar.IDBuild = 3 static
Definition at line 224 of file Hotbar.cs.
IDMainMenu
const int Hotbar.IDMainMenu = 2 static
Definition at line 222 of file Hotbar.cs.
IDSpeed
const int Hotbar.IDSpeed = 7 static
Definition at line 230 of file Hotbar.cs.
IDUser2
const int Hotbar.IDUser2 = 5 static
Definition at line 226 of file Hotbar.cs.
IDUser3
const int Hotbar.IDUser3 = 6 static
Definition at line 228 of file Hotbar.cs.
itemsPerPage
int Hotbar.itemsPerPage = 6
Definition at line 236 of file Hotbar.cs.
Referenced by GetNextSelectableIndex(), WidgetHotbar.OnActivate(), and ValidatePage().
pages
List<Hotbar.Page> Hotbar.pages = new List<Hotbar.Page>()
Definition at line 242 of file Hotbar.cs.
Referenced by AddPage(), GetItem(), GetNextSelectableIndex(), GetPrevSelectableIndex(), GetSelectedItem(), Remove(), SetItem(), and Unselect().
Property Documentation
CurrentPage
Hotbar.Page Hotbar.CurrentPage get
Definition at line 55 of file Hotbar.cs.
    {
        get
        {
            return this.pages[(this.currentPage >= 0) ? this.currentPage : 0];
        }
    }
Referenced by WidgetHotbar.GetItem(), WidgetHotbar.Rebuild(), and HotItem.TextHotkey().
DefaultItem
HotItem Hotbar.DefaultItem get
Definition at line 23 of file Hotbar.cs.
    {
        get
        {
            return null;
        }
    }
Referenced by SetItem(), and ValidatePage().
IsLocked
bool Hotbar.IsLocked get
Definition at line 31 of file Hotbar.cs.
    {
        get
        {
            return this.id == 3;
        }
    }
Referenced by WidgetHotbar.OnSetContextMenu(), and LayerRegisterHotbar.Show().
IsUserHotbar
bool Hotbar.IsUserHotbar get
Definition at line 39 of file Hotbar.cs.
    {
        get
        {
            return this.id == 5 || this.id == 6;
        }
    }
Referenced by WidgetHotbar.CanShowContextMenu(), and ButtonHotItem.RefreshItem().
manager
HotbarManager Hotbar.manager get
Definition at line 7 of file Hotbar.cs.
    {
        get
        {
            return EClass.player.hotbars;
        }
    }
SelectedItem
HotItem Hotbar.SelectedItem get
Definition at line 15 of file Hotbar.cs.
    {
        get
        {
            return this.pages[this.currentPage].SelectedItem;
        }
    }
ShowFunctionKey
bool Hotbar.ShowFunctionKey get
Definition at line 47 of file Hotbar.cs.
    {
        get
        {
            return this.id == 5;
        }
    }
Referenced by HotItem.TextHotkey().
The documentation for this class was generated from the following file:
Elin/Hotbar.cs