Elin Decompiled Documentation: CellDetail Class Reference
CellDetail Class Reference
Public Member Functions
bool TryDespawn ()
void MoveThingToBottom (Thing t)
void MoveThingToTop (Thing t)
Static Public Member Functions
static CellDetail Spawn ()
Public Attributes
List< Thing > things = new List<Thing>(1)
List< Chara > charas = new List<Chara>(1)
Area area
Footmark footmark
TaskDesignation designation
TransAnime anime
Static Public Attributes
static int count
static Map map
static Stack< CellDetail > cache = new Stack<CellDetail>()
Properties
static CellDetail Empty [get]
Detailed Description
Definition at line 4 of file CellDetail.cs.
Member Function Documentation
MoveThingToBottom()
void CellDetail.MoveThingToBottom (Thing t) inline
Definition at line 34 of file CellDetail.cs.
    {
        if (this.things.Count == 1)
        {
            return;
        }
        this.things.Remove(t);
        this.things.Insert(0, t);
        int num = 0;
        while (num < this.things.Count - 1 && this.things[num].IsInstalled)
        {
            t.stackOrder = num;
            num++;
        }
    }
References things.
MoveThingToTop()
void CellDetail.MoveThingToTop (Thing t) inline
Definition at line 50 of file CellDetail.cs.
    {
        if (this.things.Count == 1)
        {
            return;
        }
        int num = 0;
        int num2 = 0;
        while (num2 < this.things.Count - 1 && this.things[num2].IsInstalled)
        {
            num = num2 + 1;
            num2++;
        }
        if (num >= this.things.Count)
        {
            num--;
        }
        this.things.Remove(t);
        this.things.Insert(num, t);
        t.stackOrder = num;
    }
References things.
Referenced by Card.SetPlaceState().
Spawn()
static CellDetail CellDetail.Spawn () inline static
Definition at line 14 of file CellDetail.cs.
    {
        if (CellDetail.cache.Count > 0)
        {
            return CellDetail.cache.Pop();
        }
        CellDetail.count++;
        return new CellDetail();
    }
References cache, and count.
Referenced by Cell.GetOrCreateDetail().
TryDespawn()
bool CellDetail.TryDespawn () inline
Definition at line 24 of file CellDetail.cs.
    {
        if (this.things.Count > 0 || this.charas.Count > 0 || this.area != null || this.footmark != null || this.designation != null || this.anime != null)
        {
            return false;
        }
        CellDetail.cache.Push(this);
        return true;
    }
References cache, and things.
Referenced by Cell.TryDespawnDetail().
Member Data Documentation
anime
TransAnime CellDetail.anime
Definition at line 88 of file CellDetail.cs.
Referenced by Point.Animate(), BaseTileMap.DrawTile(), TileMapElona.DrawTile(), and CharaRenderer.UpdatePosition().
area
Area CellDetail.area
Definition at line 82 of file CellDetail.cs.
Referenced by Area.AddPoint(), BaseTileMap.DrawTile(), TileMapElona.DrawTile(), and PointTarget.Update().
cache
Stack<CellDetail> CellDetail.cache = new Stack<CellDetail>() static
Definition at line 76 of file CellDetail.cs.
Referenced by Spawn(), TryDespawn(), and WidgetDebug.UpdateText().
charas
List<Chara> CellDetail.charas = new List<Chara>(1)
Definition at line 80 of file CellDetail.cs.
Referenced by Cell.AddCard(), BaseTileMap.DrawTile(), TileMapElona.DrawTile(), Point.FindChara(), Point.FirstVisibleChara(), Chara.IsEnemyOnPath(), Point.ListCards(), Point.ListCharas(), Map.ListCharasInCircle(), Point.ListCharasInNeighbor(), Point.ListInspectorTargets(), Point.ListVisibleCards(), Point.ListVisibleCharas(), Point.ListWitnesses(), Cell.RemoveCard(), PointTarget.Update(), and CoreDebug.UpdateInput().
count
int CellDetail.count static
Definition at line 72 of file CellDetail.cs.
Referenced by Spawn(), and WidgetDebug.UpdateText().
designation
TaskDesignation CellDetail.designation
Definition at line 86 of file CellDetail.cs.
Referenced by BaseTileMap.DrawTile(), TileMapElona.DrawTile(), AM_Build.HitResultOnDesignation(), Point.ListInspectorTargets(), DesignationList< T >.OnAdd(), AM_Build.OnProcessTiles(), InspectGroupBlock.OnSetActions(), InspectGroupObj.OnSetActions(), DesignationList< T >.Remove(), and PointTarget.Update().
footmark
Footmark CellDetail.footmark
Definition at line 84 of file CellDetail.cs.
Referenced by GameDate.AdvanceMin(), BaseTileMap.DrawTile(), TileMapElona.DrawTile(), and Map.SetFoormark().
map
Map CellDetail.map static
Definition at line 74 of file CellDetail.cs.
things
List<Thing> CellDetail.things = new List<Thing>(1)
Definition at line 78 of file CellDetail.cs.
Referenced by Cell.AddCard(), Cell.CanSuffocate(), BaseTileMap.DrawTile(), TileMapElona.DrawTile(), Point.FindThing< T >(), Cell.GetSurfaceHeight(), BaseTileMap.GetThingPosition(), Cell.HasZoneStairs(), Point.ListCards(), Point.ListInspectorTargets(), Point.ListThings< T >(), Point.ListVisibleCards(), MoveThingToBottom(), MoveThingToTop(), Cell.Refresh(), Cell.RemoveCard(), Cell.RotateAll(), RecipeUpdater.RunRecipe(), ActWait.Search(), LayerCraftFloat.ShowContextMenu(), Map.TryAddRoom(), Zone.TryAddThing(), TryDespawn(), AI_Idle.TryPerformIdleUse(), PointTarget.Update(), and CoreDebug.UpdateInput().
Property Documentation
Empty
CellDetail CellDetail.Empty static get
Definition at line 6 of file CellDetail.cs.
    {
        get
        {
            return new CellDetail();
        }
    }
The documentation for this class was generated from the following file:
Elin/CellDetail.cs