Elin Decompiled Documentation: QueueManager Class Reference
QueueManager Class Reference
Public Member Functions
void OnSetGoal (AIAct newGoal)
AIAct Pop ()
Queue ManualAdd (AIAct interaction)
Queue Add (AIAct interaction, bool insert=false)
void Remove (Queue q)
void Cancel (Queue q)
void SetOwner (Chara _owner)
Public Attributes
Chara owner
List< Queue > list = new List<Queue>()
Properties
UIQueue uiq [get]
Queue currentQueue [get]
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Additional Inherited Members
Static Public Member Functions inherited from EClass
static int rndSeed (int a, int seed)
static int rnd (long a)
static int rnd (int a)
static int curve (int _a, int start, int step, int rate=75)
static int sqrt (int a)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Static Public Attributes inherited from EClass
static Core core
Detailed Description
Definition at line 3 of file QueueManager.cs.
Member Function Documentation
Add()
Queue QueueManager.Add (AIAct interaction, bool insert = false) inline
Definition at line 37 of file QueueManager.cs.
    {
        Queue queue = new Queue
        {
            interaction = interaction
        };
        if (insert)
        {
            list.Insert(0, queue);
        }
        else
        {
            list.Add(queue);
        }
        if ((bool)uiq)
        {
            uiq.OnAdd(queue, insert);
        }
        return queue;
    }
References list, UIQueue.OnAdd(), and uiq.
Cancel()
void QueueManager.Cancel (Queue q) inline
Definition at line 68 of file QueueManager.cs.
    {
        if (list[0] == q)
        {
            q.interaction.Cancel();
        }
        else
        {
            Remove(q);
        }
    }
References AIAct.Cancel(), Queue.interaction, list, and Remove().
Referenced by UIQueue.OnAdd().
ManualAdd()
Queue QueueManager.ManualAdd (AIAct interaction) inline
Definition at line 32 of file QueueManager.cs.
    {
        return null;
    }
OnSetGoal()
void QueueManager.OnSetGoal (AIAct newGoal) inline
Definition at line 23 of file QueueManager.cs.
    {
    }
Referenced by Chara.SetAI().
Pop()
AIAct QueueManager.Pop () inline
Definition at line 27 of file QueueManager.cs.
    {
        return null;
    }
Remove()
void QueueManager.Remove (Queue q) inline
Definition at line 58 of file QueueManager.cs.
    {
        q.removed = true;
        list.Remove(q);
        if ((bool)uiq)
        {
            uiq.OnRemove(q);
        }
    }
References list, UIQueue.OnRemove(), and uiq.
Referenced by Cancel().
SetOwner()
void QueueManager.SetOwner (Chara _owner) inline
Definition at line 80 of file QueueManager.cs.
    {
        list.Clear();
        owner = _owner;
        if ((bool)uiq)
        {
            uiq.OnSetOwner();
        }
    }
References list, UIQueue.OnSetOwner(), owner, and uiq.
Referenced by UI.OnActivateZone().
Member Data Documentation
list
List<Queue> QueueManager.list = new List<Queue>()
Definition at line 7 of file QueueManager.cs.
Referenced by Add(), Cancel(), Remove(), SetOwner(), and UIQueue.Update().
owner
Chara QueueManager.owner
Definition at line 5 of file QueueManager.cs.
Referenced by SetOwner().
Property Documentation
currentQueue
Queue QueueManager.currentQueue get
Definition at line 11 of file QueueManager.cs.
    {
        get
        {
            if (list.Count <= 0)
            {
                return null;
            }
            return list[0];
        }
    }
Referenced by UIQueue.Update().
uiq
UIQueue QueueManager.uiq get
Definition at line 9 of file QueueManager.cs.
Referenced by Add(), Remove(), and SetOwner().
The documentation for this class was generated from the following file:
Elin/QueueManager.cs