Elin Decompiled Documentation: ContentChronicle Class Reference
ContentChronicle Class Reference
Public Member Functions
override void OnSwitchContent (int idTab)
Public Member Functions inherited from UIContent
virtual void OnSwitchContent (int idTab)
virtual void OnInstantiate ()
Public Member Functions inherited from UINote
void Clear ()
void Build ()
void Space (int sizeY=0, int sizeX=1)
UINote AddNote (string id)
UIItem AddHeader (string text, Sprite sprite=null)
UIItem AddHeaderCard (string text, Sprite sprite=null)
UIItem AddHeaderTopic (string text, Sprite sprite=null)
UIItem AddHeader (string id, string text, Sprite sprite=null)
UIItem AddText (string text, FontColor color=FontColor.DontChange)
UIItem AddText (string id, string text, FontColor color=FontColor.DontChange)
UIItem AddText (string id, string text, Color color)
UIItem AddItem (string id)
UIItem AddTopic (string id, string text, string value=null)
UIItem AddTopic (string text, string value=null)
void AddImage (Sprite sprite)
void AddImage (string idFile)
UIButton AddButton (string text, Action onClick)
UIButton AddButtonLink (string text, string url)
UIDropdown AddDropdown (string id="DropdownDefault")
UIButton AddToggle (string idLang="", bool isOn=false, Action< bool > action=null)
Transform AddPrefab (string path)
T AddExtra< T > (string path)
Public Attributes
UIList list
Public Attributes inherited from UINote
RectTransform target
UINoteProfile prof
SkinType skinType
string idDefaultText
LayoutGroup layout
RectTransform cur
bool extraRebuild
Detailed Description
Definition at line 1 of file ContentChronicle.cs.
Member Function Documentation
OnSwitchContent()
override void ContentChronicle.OnSwitchContent (int idTab) inline virtual
Reimplemented from UIContent.
Definition at line 5 of file ContentChronicle.cs.
    {
        list.callbacks = new UIList.Callback<MsgLog.Data, UIItem>
        {
            onInstantiate = delegate(MsgLog.Data a, UIItem b)
            {
                b.text1.text = a.text;
                if (!a.col.IsEmpty())
                {
                    b.text1.SetColor(a.col.ToEnum<FontColor>());
                }
            }
        };
        list.Clear();
        foreach (MsgLog.Data item in EClass.game.log.GetList())
        {
            list.Add(item);
        }
        list.Refresh();
        this.RebuildLayout(recursive: true);
    }
References UIList.Add(), UIList.Clear(), EClass.game, MsgLog.GetList(), item, list, Game.log, UIList.Refresh(), UIText.SetColor(), and UIItem.text1.
Member Data Documentation
list
UIList ContentChronicle.list
Definition at line 3 of file ContentChronicle.cs.
Referenced by OnSwitchContent().
The documentation for this class was generated from the following file:
Elin/ContentChronicle.cs