Elin Decompiled Documentation: Map Class Reference
Map Class Reference
Public Member Functions
void CreateNew (int size, bool setReference=true)
void SetZone (Zone _zone)
void SetReference ()
void OnDeactivate ()
void Resize (int newSize)
void Shift (Vector2Int offset)
void Reload ()
void ReloadRoom ()
void Reset ()
void ResetEditorPos ()
void Save (string path, ZoneExportData export=null, PartialMap partial=null)
byte[] TryLoadFile (string path, string s, int size)
void Load (string path, bool import=false, PartialMap partial=null)
void ValidateVersion ()
void OnLoad ()
void OnImport (ZoneExportData data)
void ExportMetaData (string _path, string id, PartialMap partial=null)
void AddCardOnActivate (Card c)
void OnCardAddedToZone (Card t, int x, int z)
void OnCardRemovedFromZone (Card t)
void MoveCard (Point p, Card t)
void _AddCard (int x, int z, Card t, bool onAddToZone)
void _RemoveCard (Card t)
Cell GetCell (int index)
void SetSeen (int x, int z, bool seen=true, bool refresh=true)
void RevealAll (bool reveal=true)
void Reveal (Point center, int power=100)
void RefreshFOV (int x, int z, int radius=6, bool recalculate=false)
void RefreshFOVAll ()
void SetFloor (int x, int z, int idMat=0, int idFloor=0)
void SetFloor (int x, int z, int idMat, int idFloor, int dir)
void SetBridge (int x, int z, int height=0, int idMat=0, int idBridge=0, int dir=0)
void SetRoofBlock (int x, int z, int idMat, int idBlock, int dir, int height)
void SetBlock (int x, int z, int idMat=0, int idBlock=0)
void SetBlock (int x, int z, int idMat, int idBlock, int dir)
void OnSetBlockOrDoor (int x, int z)
void TryRemoveRoom (int x, int z)
void TryAddRoom (int x, int z)
void SetBlockDir (int x, int z, int dir)
void ModFire (int x, int z, int amount)
void TryShatter (Point pos, int ele, int power)
void Burn (int x, int z, bool instant=false)
void SetLiquid (int x, int z, CellEffect effect=null)
void SetLiquid (int x, int z, int id, int value=1)
void SetEffect (int x, int z, CellEffect effect=null)
void ModLiquid (int x, int z, int amount)
void ClearRainAndDecal ()
void SetObj (int x, int z, int id=0, int value=1, int dir=0)
void SetObj (int x, int z, int idMat, int idObj, int value, int dir)
void AddBackerTree (bool draw)
SourceBacker.Row GetBackerObj (Point p)
void ApplyBackerObj (Point p, int id=-1)
void DropBlockComponent (Point point, TileRow r, SourceMaterial.Row mat, bool recoverBlock, bool isPlatform=false, Chara c=null)
void MineBlock (Point point, bool recoverBlock=false, Chara c=null)
void MineRamp (Point point, int ramp, bool recoverBlock=false)
void MineFloor (Point point, Chara c=null, bool recoverBlock=false, bool removePlatform=true)
void RefreshShadow (int x, int z)
void TrySmoothPick (Cell cell, Thing t, Chara c)
void TrySmoothPick (Point p, Thing t, Chara c)
void DestroyObj (Point point)
void MineObj (Point point, Task task=null, Chara c=null)
void MineObjSound (Point point)
PlantData TryGetPlant (Point p)
PlantData TryGetPlant (Cell c)
PlantData AddPlant (Point pos, Thing seed)
void RemovePlant (Point pos)
void ValidateInstalled (Point p)
void _ValidateInstalled (int x, int y)
void RemoveLonelyRamps (Cell cell)
void DestroyBlock (int x, int z)
void AddDecal (int x, int z, int id, int amount=1, bool refresh=true)
void SetDecal (int x, int z, int id=0, int amount=1, bool refresh=true)
void SetFoormark (Point pos, int id, int angle, int offset=0)
int AngleToIndex (int a)
void RefreshSingleTile (int x, int z)
void RefreshAllTiles ()
void RefreshNeighborTiles (int x, int z)
void QuickRefreshTile (int x, int z)
int GetRampDir (int x, int z, TileType blockType=null)
Cell GetDependedRamp (Cell cell)
Point GetRandomPoint (Point center, int radius, int tries=100, bool mustBeWalkable=true, bool requireLos=true)
new Point GetRandomEdge (int r=3)
Point GetNearbyResourcePoint (Point center)
List< Point > ListPointsInCircle (Point center, float radius, bool mustBeWalkable=true, bool los=true)
List< Chara > ListCharasInCircle (Point center, float radius, bool los=true)
List< Point > ListPointsInArc (Point center, Point to, int radius, float angle)
List< Point > ListPointsInLine (Point center, Point to, int radius)
void SetBounds (int size)
void SetBounds (MapBounds b)
new void ForeachCell (Action< Cell > action)
new void ForeachPoint (Action< Point > action)
new void ForeachXYZ (Action< int, int > action)
void ForeachSphere (int _x, int _z, float r, Action< Point > action)
void ForeachNeighbor (Point center, Action< Point > action)
void Quake ()
int CountChara (Faction faction)
int CountGuest ()
int CountHostile ()
int CountWildAnimal ()
int CountNonHostile ()
List< Chara > ListChara (Faction faction)
List< Thing > ListThing< T > ()
bool PutAway (Card c)
Chara FindChara (string id)
Chara FindChara (int uid)
Thing FindThing (Func< Thing, bool > func)
Thing FindThing (int uid)
T FindThing< T > ()
Thing FindThing (Type type, Chara c=null)
Thing FindThing (Type type, BaseArea area1, BaseArea area2=null)
Thing FindThing (string workTag, BaseArea area1=null, BaseArea area2=null)
Thing FindThing (string workTag, Chara c)
BaseArea FindPublicArea ()
void RefreshSunMap ()
Public Member Functions inherited from MapBounds
void SetBounds (int _x, int _z, int _maxX, int _maxZ)
bool Contains (int dx, int dz)
bool Contains (Point p)
Point GetCenterPos ()
Point GetRandomTopPos ()
Point GetRandomRightPos ()
Point GetRandomBottomPos ()
Point GetRandomLeftPos ()
Point GetTopPos (float rate=-1f)
Point GetRightPos (float rate=-1f)
Point GetBottomPos (float rate=-1f)
Point GetLeftPos (float rate=-1f)
Point GetRandomPoint ()
Point GetSpawnPos (int x, int z, int maxX, int maxZ)
bool CanExpand (int a)
void Expand (int a)
Point GetSurface (int x, int z, bool walkable=true)
Point GetRandomSurface (int x, int z, int radius, bool walkable=true, bool allowWater=false)
Point GetRandomSurface (bool centered=false, bool walkable=true, bool allowWater=false)
Point GetRandomSpawnPos ()
Point GetRandomEdge (int r=3)
Point GetRandomSpace (int width, int height, int tries=100)
void ForeachCell (Action< Cell > action)
void ForeachPoint (Action< Point > action)
void ForeachXYZ (Action< int, int > action)
Static Public Member Functions
static MapMetaData GetMetaData (string pathZip)
static void UpdateMetaData (string pathZip, PartialMap partial=null)
Static Public Member Functions inherited from EClass
static int rnd (int a)
static int curve (int a, int start, int step, int rate=75)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Public Attributes
int seed
int _bits
IO.Compression compression
global::Version version
RoomManager rooms = new RoomManager()
TaskManager tasks = new TaskManager()
MapConfig config = new MapConfig()
CustomData custom
List< Chara > serializedCharas = new List<Chara>()
List< Chara > deadCharas = new List<Chara>()
List< Thing > things = new List<Thing>()
MapBounds bounds = new MapBounds()
List< int > _plDay = new List<int>()
List< int > _plNight = new List<int>()
Dictionary< int, int > gatherCounts = new Dictionary<int, int>()
Dictionary< int, CellEffect > cellEffects = new Dictionary<int, CellEffect>()
Dictionary< int, int > backerObjs = new Dictionary<int, int>()
Dictionary< int, PlantData > plants = new Dictionary<int, PlantData>()
BitArray32 bits
Playlist plDay
Playlist plNight
List< Chara > charas = new List<Chara>()
List< TransAnime > pointAnimes = new List<TransAnime>()
Cell[,] cells
Zone zone
CellEffectManager effectManager = new CellEffectManager()
PropsManager props = new PropsManager()
FloodSpiller flood = new FloodSpiller()
BiomeProfile[,] biomes
POIMap poiMap
List< Footmark > footmarks = new List<Footmark>()
FowProfile fowProfile
bool revealed
Public Attributes inherited from MapBounds
int x
int z
int maxX
int maxZ
int Size
Static Public Attributes
static HashSet< int > sunMap = new HashSet<int>()
static bool isDirtySunMap
Static Public Attributes inherited from EClass
static Core core
Protected Member Functions
virtual void OnSerializing ()
Static Package Functions
static bool< TryShatter > g__CanCook (Card c, ref Map.<>c__DisplayClass101_0 A_1)
Properties
bool isBreakerDown [get, set]
PropsStocked Stocked [get]
PropsInstalled Installed [get]
PropsRoaming Roaming [get]
float sizeModifier [get]
bool isGenerated [get]
bool IsIndoor [get]
int SizeXZ [get]
IEnumerable< Card > Cards [get]
Properties inherited from MapBounds
int CenterX [get]
int CenterZ [get]
int Width [get]
int Height [get]
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Private Member Functions
void OnSerializing (StreamingContext context)
void OnDeserialized (StreamingContext context)
void< MineObj > g__Pop (Thing t, ref Map.<>c__DisplayClass121_0 A_2)
Thing< FindThing > g__Find (BaseArea area, ref Map.<>c__DisplayClass171_0 A_2)
Private Attributes
HashSet< int > roomHash = new HashSet<int>()
List< Thing > _things = new List<Thing>()
Detailed Description
Definition at line 13 of file Map.cs.
Member Function Documentation
_AddCard()
void Map._AddCard (int x, int z, Card t, bool onAddToZone) inline
Definition at line 807 of file Map.cs.
    {
        if (!onAddToZone)
        {
            this._RemoveCard(t);
        }
        t.pos.Set(x, z);
        if (t.IsMultisize)
        {
            t.ForeachPoint(delegate(Point p, bool main)
            {
                p.cell.AddCard(t);
            });
        }
        else
        {
            t.Cell.AddCard(t);
        }
        t.CalculateFOV();
        if (t.isThing && !t.trait.IDActorEx.IsEmpty())
        {
            EClass.scene.AddActorEx(t, null);
        }
    }
References _RemoveCard(), Scene.AddActorEx(), Cell.AddCard(), Card.CalculateFOV(), Card.Cell, Point.cell, Card.ForeachPoint(), Trait.IDActorEx, Card.IsMultisize, Card.isThing, Card.pos, EClass.scene, Point.Set(), Card.trait, MapBounds.x, and MapBounds.z.
Referenced by AddCardOnActivate(), MoveCard(), and OnCardAddedToZone().
_RemoveCard()
void Map._RemoveCard (Card t) inline
Definition at line 832 of file Map.cs.
    {
        if (t.IsMultisize)
        {
            t.ForeachPoint(delegate(Point p, bool main)
            {
                p.cell.RemoveCard(t);
            });
        }
        else
        {
            t.Cell.RemoveCard(t);
        }
        t.ClearFOV();
    }
References Card.Cell, Point.cell, Card.ClearFOV(), Card.ForeachPoint(), Card.IsMultisize, and Cell.RemoveCard().
Referenced by _AddCard(), and OnCardRemovedFromZone().
_ValidateInstalled()
void Map._ValidateInstalled (int x, int y) inline
Definition at line 1986 of file Map.cs.
    {
        Point point = Point.shared.Set(x, y);
        if (!point.IsValid)
        {
            return;
        }
        List<Card> list = point.ListCards(false);
        CellDetail detail = point.cell.detail;
        if (detail == null)
        {
            return;
        }
        foreach (Card card in list)
        {
            if (card.isThing && card.trait.CanBeDestroyed && card.IsInstalled)
            {
                HitResult hitResult = card.TileType._HitTest(point, card.Thing, false);
                if (card.Thing.stackOrder != detail.things.IndexOf(card.Thing) || (hitResult != HitResult.Valid && hitResult != HitResult.Warning))
                {
                    if (EClass._zone.IsPCFaction)
                    {
                        card.SetPlaceState(PlaceState.roaming, false);
                    }
                    else
                    {
                        card.Die(null, null, AttackSource.None);
                    }
                }
            }
        }
    }
References TileType._HitTest(), EClass._zone, Trait.CanBeDestroyed, Point.cell, Cell.detail, Card.Die(), Card.IsInstalled, Zone.IsPCFaction, Card.isThing, Point.IsValid, Point.ListCards(), Point.Set(), Card.SetPlaceState(), Point.shared, Thing.stackOrder, Card.Thing, Card.TileType, and Card.trait.
Referenced by TryShatter().
AddBackerTree()
void Map.AddBackerTree (bool draw) inline
Definition at line 1538 of file Map.cs.
    {
        SourceBacker.Row item = EClass.sources.backers.listTree.NextItem(ref BackerContent.indexTree);
        int num = draw ? 2 : 1;
        EClass._map.bounds.ForeachCell(delegate(Cell c)
        {
            int num;
            if (num <= 0 || c.growth == null || !c.growth.IsTree || !c.growth.IsMature || (EClass.player.doneBackers.Contains(item.id) && !EClass.core.config.test.ignoreBackerDestoryFlag))
            {
                return;
            }
            if (c.sourceObj.alias == item.tree || item.tree == "random")
            {
                this.backerObjs[c.index] = item.id;
                Debug.Log(string.Concat(new string[]
                {
                    c.index.ToString(),
                    "/",
                    c.x.ToString(),
                    "/",
                    c.z.ToString(),
                    "/",
                    item.id.ToString(),
                    "/",
                    item.Name,
                    "/",
                    item.tree
                }));
                num = num;
                num--;
                item = EClass.sources.backers.listTree.NextItem(ref BackerContent.indexTree);
            }
        });
    }
References EClass._map, SourceManager.backers, bounds, EClass.core, Player.doneBackers, MapBounds.ForeachCell(), Cell.growth, SourceBacker.Row.id, BackerContent.indexTree, GrowSystem.IsMature, GrowSystem.IsTree, SourceBacker.listTree, EClass.player, Cell.sourceObj, EClass.sources, and SourceBacker.Row.tree.
Referenced by Zone_Field.OnGenerateMap().
AddCardOnActivate()
void Map.AddCardOnActivate (Card c) inline
Definition at line 746 of file Map.cs.
    {
        c.parent = this.zone;
        this.props.OnCardAddedToZone(c);
        Chara chara = c.Chara;
        if (chara != null)
        {
            chara.currentZone = EClass._zone;
        }
        if (c.isChara)
        {
            if (!c.pos.IsInBounds)
            {
                c.pos.Set(EClass._map.GetCenterPos());
            }
        }
        else if (!c.pos.IsValid)
        {
            c.pos.Set(EClass._map.GetCenterPos());
        }
        this._AddCard(c.pos.x, c.pos.z, c, true);
    }
References _AddCard(), EClass._map, EClass._zone, Card.Chara, MapBounds.GetCenterPos(), Card.isChara, Point.IsInBounds, Point.IsValid, PropsManager.OnCardAddedToZone(), Card.pos, props, Point.Set(), Point.x, Point.z, and zone.
Referenced by Zone.Activate(), and Zone.AddGlobalCharasOnActivate().
AddDecal()
void Map.AddDecal (int x, int z, int id, int amount = 1, bool refresh = true) inline
Definition at line 2037 of file Map.cs.
    {
        if (x < 0 || z < 0 || x >= this.Size || z >= this.Size)
        {
            return;
        }
        Cell cell = this.cells[x, z];
        if (!cell.sourceFloor.tileType.AllowBlood)
        {
            return;
        }
        if ((int)(cell.decal / 8) != id && (int)(cell.decal % 8) > amount)
        {
            return;
        }
        if ((int)(cell.decal / 8) != id && cell.decal % 8 == 0)
        {
            amount--;
        }
        int num = Mathf.Clamp((int)(((int)(cell.decal / 8) == id) ? (cell.decal % 8) : 0) + amount, 0, 7);
        cell.decal = (byte)(id * 8 + num);
        if (refresh)
        {
            this.RefreshNeighborTiles(x, z);
        }
    }
References Cell.decal, and Cell.sourceFloor.
Referenced by Card.AddBlood(), SourceMaterial.Row.AddBlood(), AM_MoveInstalled.HitTest(), and CoreDebug.UpdateInput().
AddPlant()
PlantData Map.AddPlant (Point pos, Thing seed) inline
Definition at line 1962 of file Map.cs.
    {
        PlantData plantData = new PlantData
        {
            seed = seed
        };
        this.plants[pos.index] = plantData;
        return plantData;
    }
References Point.index, and seed.
Referenced by TraitFertilizer.OnSimulateHour(), ZoneEventHarvest.OnVisit(), and TraitSeed.TrySprout().
AngleToIndex()
int Map.AngleToIndex (int a) inline
Definition at line 2087 of file Map.cs.
    {
        if (EClass._zone.IsRegion)
        {
            if (a == 135)
            {
                return 7;
            }
            if (a == 180)
            {
                return 0;
            }
            if (a == 225)
            {
                return 1;
            }
            if (a == -90)
            {
                return 2;
            }
            if (a == -45)
            {
                return 3;
            }
            if (a == 0)
            {
                return 4;
            }
            if (a == 45)
            {
                return 5;
            }
            return 6;
        }
        else
        {
            if (a == 135)
            {
                return 0;
            }
            if (a == 180)
            {
                return 1;
            }
            if (a == 225)
            {
                return 2;
            }
            if (a == -90)
            {
                return 3;
            }
            if (a == -45)
            {
                return 4;
            }
            if (a == 0)
            {
                return 5;
            }
            if (a == 45)
            {
                return 6;
            }
            return 7;
        }
    }
References EClass._zone, and Spatial.IsRegion.
ApplyBackerObj()
void Map.ApplyBackerObj (Point p, int id = -1) inline
Definition at line 1582 of file Map.cs.
    {
        if (!p.HasObj)
        {
            return;
        }
        bool flag = p.sourceObj.id == 82;
        SourceBacker.Row row = (id != -1) ? EClass.sources.backers.map.TryGetValue(id, null) : (flag ? EClass.sources.backers.listRemain.NextItem(ref BackerContent.indexRemain) : EClass.sources.backers.listTree.NextItem(ref BackerContent.indexTree));
        if (row != null)
        {
            if (!EClass.player.doneBackers.Contains(row.id) || EClass.core.config.test.ignoreBackerDestoryFlag)
            {
                this.backerObjs[p.index] = row.id;
                if (flag)
                {
                    p.cell.objDir = row.skin;
                    return;
                }
            }
            else
            {
                this.backerObjs.Remove(p.index);
            }
        }
    }
References SourceManager.backers, EClass.core, Player.doneBackers, Point.HasObj, SourceBacker.Row.id, Point.index, BackerContent.indexRemain, BackerContent.indexTree, SourceBacker.listRemain, SourceBacker.listTree, EClass.player, SourceBacker.Row.skin, and EClass.sources.
Referenced by BackerContentInspector.ContentObj.Apply(), and GenRoom.OnPopulate().
Burn()
void Map.Burn (int x, int z, bool instant = false) inline
Definition at line 1373 of file Map.cs.
    {
        Cell cell = this.cells[x, z];
        Point sharedPoint = cell.GetSharedPoint();
        if ((instant || EClass.rnd(10) == 0) && cell.HasObj)
        {
            if (cell.sourceObj.tileType is TileTypeTree)
            {
                this.SetObj(x, z, cell.matObj_fixed.id, 59, 0, EClass.rnd(4));
            }
            else
            {
                this.SetObj(x, z, 0, 1, 0);
                if (EClass.rnd(2) == 0)
                {
                    EClass._zone.AddCard(ThingGen.Create((EClass.rnd(2) == 0) ? "ash" : "ash2", -1, -1), sharedPoint);
                }
            }
        }
        if ((instant || EClass.rnd(5) == 0) && cell._block != 0 && cell._block != 96)
        {
            if (EClass.rnd(10) == 0 || !cell.sourceBlock.tileType.IsWall)
            {
                cell._block = 0;
            }
            else
            {
                cell._block = 96;
            }
            this.SetObj(x, z, 0, 1, 0);
            if (cell.room != null)
            {
                cell.room.SetDirty();
            }
            this.RefreshNeighborTiles(x, z);
        }
        if (instant || EClass.rnd(10) == 0)
        {
            if (EClass.rnd(4) != 0)
            {
                cell._floor = 49;
            }
            if (cell._bridge != 0 && EClass.rnd(5) != 0)
            {
                cell._bridge = 49;
            }
        }
        foreach (Card card in sharedPoint.ListCards(false))
        {
            if (card.trait.CanBeDestroyed && !card.trait.IsDoor && card.isThing)
            {
                if (instant)
                {
                    card.Destroy();
                    EClass._zone.AddCard(ThingGen.Create((EClass.rnd(2) == 0) ? "ash" : "ash2", -1, -1), sharedPoint);
                }
                else
                {
                    card.DamageHP(30, 910, 100, AttackSource.None, null, true);
                }
            }
        }
        if (instant)
        {
            cell.effect = null;
        }
    }
References Cell._block, Cell._bridge, EClass._zone, Zone.AddCard(), Trait.CanBeDestroyed, cells, ThingGen.Create(), Card.DamageHP(), Card.Destroy(), Cell.GetSharedPoint(), Cell.HasObj, Trait.IsDoor, Card.isThing, Cell.matObj_fixed, RefreshNeighborTiles(), EClass.rnd(), Cell.room, Room.SetDirty(), SetObj(), Cell.sourceBlock, Cell.sourceObj, Card.trait, MapBounds.x, and MapBounds.z.
Referenced by LogicalFire.Update().
ClearRainAndDecal()
void Map.ClearRainAndDecal () inline
Definition at line 1493 of file Map.cs.
    {
        this.ForeachCell(delegate(Cell c)
        {
            c.effect = null;
            c.decal = 0;
        });
    }
References ForeachCell().
CountChara()
int Map.CountChara (Faction faction) inline
Definition at line 2487 of file Map.cs.
    {
        int num = 0;
        using (List<Chara>.Enumerator enumerator = this.charas.GetEnumerator())
        {
            while (enumerator.MoveNext())
            {
                if (enumerator.Current.faction == faction)
                {
                    num++;
                }
            }
        }
        return num;
    }
CountGuest()
int Map.CountGuest () inline
Definition at line 2503 of file Map.cs.
    {
        int num = 0;
        using (List<Chara>.Enumerator enumerator = this.charas.GetEnumerator())
        {
            while (enumerator.MoveNext())
            {
                if (enumerator.Current.IsGuest())
                {
                    num++;
                }
            }
        }
        return num;
    }
CountHostile()
int Map.CountHostile () inline
Definition at line 2519 of file Map.cs.
    {
        int num = 0;
        foreach (Chara chara in this.charas)
        {
            if (!chara.IsPCFaction && chara.IsHostile())
            {
                num++;
            }
        }
        return num;
    }
References Chara.IsHostile(), and Chara.IsPCFaction.
CountNonHostile()
int Map.CountNonHostile () inline
Definition at line 2545 of file Map.cs.
    {
        int num = 0;
        foreach (Chara chara in this.charas)
        {
            if (!chara.IsPCFaction && !chara.IsHostile())
            {
                num++;
            }
        }
        return num;
    }
References Chara.IsHostile(), and Chara.IsPCFaction.
CountWildAnimal()
int Map.CountWildAnimal () inline
Definition at line 2532 of file Map.cs.
    {
        int num = 0;
        foreach (Chara chara in this.charas)
        {
            if (!chara.IsPCFaction && chara.race.IsAnimal)
            {
                num++;
            }
        }
        return num;
    }
References Chara.IsPCFaction, and Chara.race.
CreateNew()
void Map.CreateNew (int size, bool setReference = true) inline
Definition at line 107 of file Map.cs.
    {
        Debug.Log("Map CreateNew:");
        this.Size = size;
        this.cells = new Cell[this.Size, this.Size];
        this.bounds = new MapBounds
        {
            x = 0,
            z = 0,
            maxX = this.Size - 1,
            maxZ = this.Size - 1,
            Size = this.Size
        };
        base.SetBounds(0, 0, this.Size - 1, this.Size - 1);
        this.ForeachXYZ(delegate(int x, int z)
        {
            this.cells[x, z] = new Cell
            {
                x = (byte)x,
                z = (byte)z
            };
        });
        if (setReference)
        {
            this.SetReference();
        }
    }
References cells, ForeachXYZ(), MapBounds.maxX, MapBounds.maxZ, SetReference(), MapBounds.Size, MapBounds.x, and MapBounds.z.
Referenced by MapGen.OnGenerateTerrain(), MapGenDungen.OnGenerateTerrain(), and MapGenRegion.OnGenerateTerrain().
DestroyBlock()
void Map.DestroyBlock (int x, int z) inline
Definition at line 2032 of file Map.cs.
    {
        this.SetBlock(x, z, 0, 0);
    }
Referenced by OnCardAddedToZone().
DestroyObj()
void Map.DestroyObj (Point point) inline
Definition at line 1801 of file Map.cs.
    {
        Cell cell = point.cell;
        RenderRow sourceObj = cell.sourceObj;
        SourceMaterial.Row matObj = cell.matObj;
        if (sourceObj.tileType.IsBlockPass)
        {
            Effect.Get("smoke").Play(point, 0f, null, null);
        }
        Effect.Get("mine").Play(point, 0f, null, null).SetParticleColor(cell.matObj.GetColor()).Emit(10 + EClass.rnd(10));
        point.PlaySound(matObj.GetSoundDead(null), true, 1f, true);
        matObj.AddBlood(point, 3);
    }
References SourceMaterial.Row.AddBlood(), Point.cell, Effect.Get(), SourceMaterial.Row.GetSoundDead(), TileType.IsBlockPass, Cell.matObj, Effect.Play(), Point.PlaySound(), EClass.rnd(), Cell.sourceObj, and RenderRow.tileType.
Referenced by TaskHarvest.OnCreateProgress().
DropBlockComponent()
void Map.DropBlockComponent (Point point, TileRow r, SourceMaterial::Row mat, bool recoverBlock, bool isPlatform = false, Chara c = null) inline
Definition at line 1608 of file Map.cs.
    {
        if (r.components.Length == 0)
        {
            return;
        }
        RecipeManager.BuildList();
        Thing thing;
        if (recoverBlock)
        {
            if (r is SourceFloor.Row)
            {
                thing = ThingGen.CreateFloor(r.id, mat.id, isPlatform);
            }
            else
            {
                thing = ThingGen.CreateBlock(r.id, mat.id);
            }
        }
        else
        {
            RecipeSource recipeSource = RecipeManager.Get(r.RecipeID + (isPlatform ? "-b" : ""));
            if (recipeSource == null)
            {
                return;
            }
            string idingredient = recipeSource.GetIDIngredient();
            if (idingredient == null)
            {
                return;
            }
            thing = ThingGen.Create(idingredient, -1, -1);
            thing.ChangeMaterial(mat.alias);
        }
        if (EClass.scene.actionMode.IsBuildMode && EClass.debug.godBuild)
        {
            this.PutAway(thing);
            return;
        }
        this.TrySmoothPick(point, thing, c);
    }
References Scene.actionMode, RecipeManager.BuildList(), Card.ChangeMaterial(), RenderRow.components, ThingGen.Create(), ThingGen.CreateBlock(), ThingGen.CreateFloor(), EClass.debug, RecipeManager.Get(), RecipeSource.GetIDIngredient(), CoreDebug.godBuild, TileRow.id, ActionMode.IsBuildMode, RenderRow.RecipeID, and EClass.scene.
ExportMetaData()
void Map.ExportMetaData (string _path, string id, PartialMap partial = null) inline
Definition at line 673 of file Map.cs.
    {
        if (this.custom == null)
        {
            this.custom = new CustomData();
        }
        MapMetaData mapMetaData = new MapMetaData
        {
            name = EClass._zone.Name,
            version = BaseCore.Instance.version.GetInt(),
            partial = partial
        };
        CustomData customData = this.custom;
        mapMetaData.id = id;
        customData.id = id;
        IO.SaveFile(_path + "meta", mapMetaData, false, null);
    }
References EClass._zone, custom, Spatial.Name, and version.
Referenced by UpdateMetaData().
FindChara() [1/2]
Chara Map.FindChara (int uid) inline
Definition at line 2635 of file Map.cs.
    {
        foreach (Chara chara in this.charas)
        {
            if (chara.uid == uid)
            {
                return chara;
            }
        }
        return null;
    }
References Card.uid.
FindChara() [2/2]
Chara Map.FindChara (string id) inline
Definition at line 2623 of file Map.cs.
    {
        foreach (Chara chara in this.charas)
        {
            if (chara.id == id)
            {
                return chara;
            }
        }
        return null;
    }
References Card.id.
Referenced by QuestPuppy.CanUpdateOnTalk(), ZoneEventSubdue.CheckClear(), ActEffect.DamageEle(), Card.DamageHP(), ZonePreEnterOnCompleteQuestInstance.Execute(), Chara.FindMaster(), CharaList.Get(), and ItemQuestTracker.Refresh().
FindPublicArea()
BaseArea Map.FindPublicArea () inline
Definition at line 2761 of file Map.cs.
    {
        return (from a in this.rooms.listArea.Concat(this.rooms.listRoom)
        where a.type.IsPublicArea
        select a).RandomItem<BaseArea>();
    }
Referenced by GoalSleep.OnSimulatePosition(), and GoalSleep.Run().
FindThing() [1/6]
Thing Map.FindThing (Func< Thing, bool > func) inline
Definition at line 2647 of file Map.cs.
    {
        foreach (Thing thing in this.things)
        {
            if (func(thing))
            {
                return thing;
            }
        }
        return null;
    }
Referenced by ConSleep.g__TryPick(), GoalGraze.GetPos(), Zone_Dungeon.PlaceRail(), AIWork.SetDestination(), Chara.Stumble(), CoreDebug.UpdateInput(), and FactionBranch.Upgrade().
FindThing() [2/6]
Thing Map.FindThing (int uid) inline
Definition at line 2659 of file Map.cs.
    {
        foreach (Thing thing in this.things)
        {
            if (thing.uid == uid)
            {
                return thing;
            }
        }
        return null;
    }
References Card.uid.
FindThing() [3/6]
Thing Map.FindThing (string workTag, BaseArea area1 = null, BaseArea area2 = null) inline
Definition at line 2717 of file Map.cs.
    {
        if (area1 == null && area2 == null)
        {
            return null;
        }
        Thing thing = null;
        PropSet orCreate = EClass._map.Installed.workMap.GetOrCreate(workTag, null);
        if (area1 != null)
        {
            IEnumerable<Card> enumerable = from a in orCreate.Values
            where a.pos.HasRoomOrArea(area1)
            select a;
            if (enumerable.Count<Card>() > 0)
            {
                thing = (enumerable.RandomItem<Card>() as Thing);
            }
        }
        if (thing == null && area2 != null)
        {
            IEnumerable<Card> enumerable2 = from a in orCreate.Values
            where a.pos.HasRoomOrArea(area2)
            select a;
            if (enumerable2.Count<Card>() > 0)
            {
                thing = (enumerable2.RandomItem<Card>() as Thing);
            }
        }
        return thing;
    }
References EClass._map, Point.HasRoomOrArea(), Installed, Card.pos, and Props.workMap.
FindThing() [4/6]
Thing Map.FindThing (string workTag, Chara c) inline
Definition at line 2748 of file Map.cs.
    {
        Thing result = null;
        IEnumerable<Card> enumerable = from a in EClass._map.Installed.workMap.GetOrCreate(workTag, null).Values
        where a.pos.IsPublicSpace()
        select a;
        if (enumerable.Count<Card>() > 0)
        {
            result = (enumerable.RandomItem<Card>() as Thing);
        }
        return result;
    }
References EClass._map, Installed, and Props.workMap.
FindThing() [5/6]
Thing Map.FindThing (Type type, BaseArea area1, BaseArea area2 = null) inline
Definition at line 2700 of file Map.cs.
    {
        Map.<>c__DisplayClass171_0 CS$<>8__locals1;
        CS$<>8__locals1.<>4__this = this;
        CS$<>8__locals1.type = type;
        if (area1 == null && area2 == null)
        {
            return null;
        }
        Thing thing = this.<FindThing>g__Find|171_0(area1, ref CS$<>8__locals1);
        if (thing == null && area2 != null)
        {
            thing = this.<FindThing>g__Find|171_0(area2, ref CS$<>8__locals1);
        }
        return thing;
    }
FindThing() [6/6]
Thing Map.FindThing (Type type, Chara c = null) inline
Definition at line 2683 of file Map.cs.
    {
        this._things.Clear();
        foreach (Thing thing in EClass._map.props.installed.things)
        {
            if (type.IsAssignableFrom(thing.trait.GetType()) && thing.pos.IsPublicSpace())
            {
                this._things.Add(thing);
            }
        }
        if (this._things.Count <= 0)
        {
            return null;
        }
        return this._things.RandomItem<Thing>();
    }
References EClass._map, Card.Add(), PropsManager.installed, Point.IsPublicSpace(), Card.pos, props, Props.things, and Card.trait.
FindThing< T >()
T Map.FindThing< T > () inline
Type Constraints
T : Trait
Definition at line 2671 of file Map.cs.
                                    : Trait
    {
        foreach (Thing thing in this.things)
        {
            if (thing.trait is T)
            {
                return thing.trait as T;
            }
        }
        return default(T);
    }
References Card.trait.
ForeachCell()
new void Map.ForeachCell (Action< Cell > action) inline
Definition at line 2396 of file Map.cs.
    {
        for (int i = 0; i < this.Size; i++)
        {
            for (int j = 0; j < this.Size; j++)
            {
                action(this.cells[i, j]);
            }
        }
    }
Referenced by Zone.Activate(), ZoneInspector.FillUtil.ClearBlock(), ZoneInspector.FillUtil.ClearBridge(), ZoneInspector.FillUtil.ClearObj(), ClearRainAndDecal(), ZoneInspector.FillUtil.FillBlock(), ZoneInspector.FillUtil.FillFloor(), ZoneInspector.FillUtil.FlattenHeight(), Zone_Field.OnGenerateMap(), Zone_RandomDungeonFactory.OnGenerateMap(), Zone_VernisMine.OnGenerateMap(), MapSubset.OnSave(), and CoreDebug.Test_Grow().
ForeachNeighbor()
void Map.ForeachNeighbor (Point center, Action< Point > action) inline
Definition at line 2450 of file Map.cs.
    {
        int x = center.x;
        int z = center.z;
        Point point = new Point();
        for (int i = x - 1; i < x + 2; i++)
        {
            if (i >= 0 && i < this.Size)
            {
                for (int j = z - 1; j < z + 2; j++)
                {
                    if (j >= 0 && j < this.Size)
                    {
                        point.Set(i, j);
                        action(point);
                    }
                }
            }
        }
    }
References Point.Set(), Point.x, and Point.z.
ForeachPoint()
new void Map.ForeachPoint (Action< Point > action) inline
Definition at line 2407 of file Map.cs.
    {
        Point point = new Point();
        for (int i = 0; i < this.Size; i++)
        {
            for (int j = 0; j < this.Size; j++)
            {
                action(point.Set(i, j));
            }
        }
    }
References Point.Set().
Referenced by BaseTileSelector.ProcessFillTiles().
ForeachSphere()
void Map.ForeachSphere (int _x, int _z, float r, Action< Point > action) inline
Definition at line 2430 of file Map.cs.
    {
        Point point = new Point();
        int num = (int)Mathf.Ceil(r);
        for (int i = _x - num; i < _x + num + 1; i++)
        {
            if (i >= 0 && i < this.Size)
            {
                for (int j = _z - num; j < _z + num + 1; j++)
                {
                    if (j >= 0 && j < this.Size && (float)((i - _x) * (i - _x) + (j - _z) * (j - _z)) < r * r)
                    {
                        point.Set(i, j);
                        action(point);
                    }
                }
            }
        }
    }
References Point.Set().
Referenced by Trait.ListPoints(), TraitLightSun.ListPoints(), Act.OnMarkMapHighlights(), AM_Populate.OnProcessTiles(), AM_Terrain.OnProcessTiles(), AM_BaseTerrain.OnRenderTile(), RefreshFOV(), Reveal(), ActWait.Search(), GameUpdater.Update(), and VirtualRoom.VirtualRoom().
ForeachXYZ()
new void Map.ForeachXYZ (Action< int, int > action) inline
Definition at line 2419 of file Map.cs.
    {
        for (int i = 0; i < this.Size; i++)
        {
            for (int j = 0; j < this.Size; j++)
            {
                action(i, j);
            }
        }
    }
Referenced by CreateNew().
g__CanCook()
static bool< TryShatter > Map.g__CanCook (Card c, ref Map::<>c__DisplayClass101_0 A_1) inline static package
Definition at line 2785 of file Map.cs.
    {
        return A_1.fire && c.IsFood && c.category.IsChildOf("foodstuff");
    }
References Card.category.
Referenced by TryShatter().
g__Find()
Thing< FindThing > Map.g__Find (BaseArea area, ref Map::<>c__DisplayClass171_0 A_2) inline private
Definition at line 2802 of file Map.cs.
    {
        this._things.Clear();
        foreach (Thing thing in EClass._map.props.installed.things)
        {
            if (A_2.type.IsAssignableFrom(thing.trait.GetType()) && thing.pos.HasRoomOrArea(area))
            {
                this._things.Add(thing);
            }
        }
        if (this._things.Count <= 0)
        {
            return null;
        }
        return this._things.RandomItem<Thing>();
    }
References EClass._map, Point.HasRoomOrArea(), PropsManager.installed, Card.pos, props, Props.things, and Card.trait.
g__Pop()
void< MineObj > Map.g__Pop (Thing t, ref Map::<>c__DisplayClass121_0 A_2) inline private
Definition at line 2791 of file Map.cs.
    {
        if (EClass.scene.actionMode.IsBuildMode && EClass.debug.godBuild)
        {
            EClass._map.PutAway(t);
            return;
        }
        this.TrySmoothPick(A_2.point, t, A_2.c);
    }
References EClass._map, Scene.actionMode, EClass.debug, CoreDebug.godBuild, ActionMode.IsBuildMode, PutAway(), and EClass.scene.
GetBackerObj()
SourceBacker.Row Map.GetBackerObj (Point p) inline
Definition at line 1573 of file Map.cs.
    {
        if (!this.backerObjs.ContainsKey(p.index))
        {
            return null;
        }
        return EClass.sources.backers.map.TryGetValue(this.backerObjs[p.index], null);
    }
References SourceManager.backers, Point.index, and EClass.sources.
Referenced by TaskHarvest.OnCreateProgress().
GetCell()
Cell Map.GetCell (int index) inline
Definition at line 848 of file Map.cs.
    {
        return this.cells[index % this.Size, index % this.SizeXZ / this.Size];
    }
References cells, and MapBounds.Size.
Referenced by Zone.Activate(), MapSubset.Apply(), Fov.ClearVisible(), Fov.Perform(), and ActionMode.RefreshTexts().
GetDependedRamp()
Cell Map.GetDependedRamp (Cell cell) inline
Definition at line 2241 of file Map.cs.
    {
        Cell right = cell.Right;
        if (right.HasRamp && !right.HasStairs && right.blockDir == 1)
        {
            return right;
        }
        Cell front = cell.Front;
        if (front.HasRamp && !front.HasStairs && front.blockDir == 0)
        {
            return front;
        }
        Cell left = cell.Left;
        if (left.HasRamp && !left.HasStairs && left.blockDir == 3)
        {
            return left;
        }
        Cell back = cell.Back;
        if (back.HasRamp && !back.HasStairs && back.blockDir == 2)
        {
            return back;
        }
        return null;
    }
References Cell.Back, Cell.blockDir, Cell.Front, Cell.HasRamp, Cell.HasStairs, Cell.Left, and Cell.Right.
GetMetaData()
static MapMetaData Map.GetMetaData (string pathZip) inline static
Definition at line 691 of file Map.cs.
    {
        try
        {
            using (ZipFile zipFile = ZipFile.Read(pathZip))
            {
                ZipEntry zipEntry = zipFile["meta"];
                if (zipEntry != null)
                {
                    Debug.Log(zipEntry);
                    using (MemoryStream memoryStream = new MemoryStream())
                    {
                        zipEntry.Extract(memoryStream);
                        MapMetaData mapMetaData = IO.LoadStreamJson<MapMetaData>(memoryStream, null);
                        Debug.Log(mapMetaData);
                        mapMetaData.path = pathZip;
                        return mapMetaData;
                    }
                }
            }
        }
        catch (Exception message)
        {
            Debug.Log(message);
        }
        return null;
    }
Referenced by Zone.IsImportValid(), PartialMap.Load(), TraitMoongateEx.OnUse(), and PartialMapMenu.Refresh().
GetNearbyResourcePoint()
Point Map.GetNearbyResourcePoint (Point center) inline
Definition at line 2309 of file Map.cs.
    {
        Point point = new Point();
        int num = (EClass.rnd(2) == 0) ? 1 : -1;
        int num2 = (EClass.rnd(2) == 0) ? 1 : -1;
        for (int i = 0; i < 3; i++)
        {
            point.x = center.x - num + i * num;
            for (int j = 0; j < 3; j++)
            {
                point.z = center.z - num2 + j * num2;
                if (point.IsValid && point.area == null && point.cell.CanHarvest())
                {
                    return point;
                }
            }
        }
        return Point.Invalid;
    }
References Point.area, Cell.CanHarvest(), Point.cell, Point.Invalid, Point.IsValid, and EClass.rnd().
GetRampDir()
int Map.GetRampDir (int x, int z, TileType blockType = null) inline
Definition at line 2204 of file Map.cs.
    {
        Cell cell = this.cells[x, z];
        if (cell.HasFullBlock)
        {
            if (blockType == null)
            {
                blockType = cell.sourceBlock.tileType;
            }
            Cell right = cell.Right;
            Cell front = cell.Front;
            Cell left = cell.Left;
            Cell back = cell.Back;
            if (!right.HasBlock && !right.IsVoid && left.HasFullBlock && front.CanBuildRamp(1) && back.CanBuildRamp(1))
            {
                return 1;
            }
            if (!front.HasBlock && !front.IsVoid && back.HasFullBlock && left.CanBuildRamp(0) && right.CanBuildRamp(0))
            {
                return 0;
            }
            if (!left.HasBlock && !left.IsVoid && right.HasFullBlock && front.CanBuildRamp(3) && back.CanBuildRamp(3))
            {
                return 3;
            }
            if (!back.HasBlock && !back.IsVoid && front.HasFullBlock && left.CanBuildRamp(2) && right.CanBuildRamp(2))
            {
                return 2;
            }
            if (!blockType.IsRamp)
            {
                return 0;
            }
        }
        return -1;
    }
References Cell.Back, Cell.CanBuildRamp(), Cell.Front, Cell.HasBlock, Cell.HasFullBlock, Cell.IsVoid, Cell.Left, Cell.Right, and Cell.sourceBlock.
Referenced by TaskMine.GetHitResult(), and MineRamp().
GetRandomEdge()
new Point Map.GetRandomEdge (int r = 3) inline
Definition at line 2284 of file Map.cs.
    {
        for (int i = 0; i < 10000; i++)
        {
            int x;
            int z;
            if (EClass.rnd(2) == 0)
            {
                x = ((EClass.rnd(2) == 0) ? EClass.rnd(r) : (this.Size - 1 - EClass.rnd(r)));
                z = EClass.rnd(this.Size);
            }
            else
            {
                z = ((EClass.rnd(2) == 0) ? EClass.rnd(r) : (this.Size - 1 - EClass.rnd(r)));
                x = EClass.rnd(this.Size);
            }
            Point surface = base.GetSurface(x, z, false);
            if (surface.IsValid)
            {
                return surface;
            }
        }
        return base.GetSurface(this.Size / 2, this.Size / 2, false);
    }
References Point.IsValid, and EClass.rnd().
Referenced by MapGen.MakeRiver(), and ZoneEventSiege.OnFirstTick().
GetRandomPoint()
Point Map.GetRandomPoint (Point center, int radius, int tries = 100, bool mustBeWalkable = true, bool requireLos = true) inline
Definition at line 2266 of file Map.cs.
    {
        Point point = new Point();
        for (int i = 0; i < tries; i++)
        {
            point.x = center.x + EClass.rnd(radius * 2 + 1) - radius;
            point.z = center.z + EClass.rnd(radius * 2 + 1) - radius;
            point.Clamp(false);
            if ((!mustBeWalkable || !point.cell.blocked) && (!requireLos || Los.IsVisible(center, point, null)))
            {
                return point;
            }
        }
        Debug.Log("GetRandomPoint failed center:" + ((center != null) ? center.ToString() : null) + " rad:" + radius.ToString());
        point.IsValid = false;
        return point;
    }
References Algorithms.WeightCell.blocked, Point.cell, Point.Clamp(), Los.IsVisible(), EClass.rnd(), and Point.ToString().
Referenced by MapBounds.GetRandomSpawnPos(), MapGenDungen.OnGenerateTerrain(), MapGen.Populate(), and TraitSpotSpawn.Update().
ListChara()
List< Chara > Map.ListChara (Faction faction) inline
Definition at line 2558 of file Map.cs.
    {
        List<Chara> list = new List<Chara>();
        foreach (Chara chara in this.charas)
        {
            if (chara.faction == faction)
            {
                list.Add(chara);
            }
        }
        return list;
    }
References Chara.faction.
Referenced by ContentPopulation.Refresh().
ListCharasInCircle()
List< Chara > Map.ListCharasInCircle (Point center, float radius, bool los = true) inline
Definition at line 2342 of file Map.cs.
    {
        List<Chara> list = new List<Chara>();
        foreach (Point point in this.ListPointsInCircle(center, radius, false, los))
        {
            CellDetail detail = point.detail;
            if (detail != null && detail.charas.Count > 0)
            {
                foreach (Chara item in point.detail.charas)
                {
                    list.Add(item);
                }
            }
        }
        return list;
    }
References CellDetail.charas, and Point.detail.
Referenced by AI_PlayMusic.Run().
ListPointsInArc()
List< Point > Map.ListPointsInArc (Point center, Point to, int radius, float angle) inline
Definition at line 2359 of file Map.cs.
    {
        Point to2 = new Point((to.x > center.x) ? 1 : ((to.x < center.x) ? -1 : 0), (to.z > center.z) ? 1 : ((to.z < center.z) ? -1 : 0));
        Point point = new Point(0, 0);
        List<Point> list = new List<Point>();
        float diff = point.GetAngle2(to2);
        this.ForeachSphere(center.x, center.z, (float)radius, delegate(Point p)
        {
            float angle2 = center.GetAngle2(p);
            if ((Mathf.Abs(diff - angle2) < angle || Mathf.Abs(diff - angle2 + 360f) < angle || Mathf.Abs(360f - diff + angle2) < angle) && Los.IsVisible(center, p, null) && !p.IsBlocked)
            {
                list.Add(p.Copy());
            }
        });
        return list;
    }
References Point.GetAngle2(), Point.IsBlocked, Los.IsVisible(), Point.x, and Point.z.
Referenced by ActEffect.ProcAt().
ListPointsInCircle()
List< Point > Map.ListPointsInCircle (Point center, float radius, bool mustBeWalkable = true, bool los = true) inline
Definition at line 2329 of file Map.cs.
    {
        List<Point> list = new List<Point>();
        this.ForeachSphere(center.x, center.z, radius, delegate(Point p)
        {
            if ((!mustBeWalkable || !p.cell.blocked) && (!los || Los.IsVisible(center, p, null)))
            {
                list.Add(p.Copy());
            }
        });
        return list;
    }
References Algorithms.WeightCell.blocked, Point.cell, Los.IsVisible(), Point.x, and Point.z.
Referenced by Point.ListWitnesses(), and ActEffect.ProcAt().
ListPointsInLine()
List< Point > Map.ListPointsInLine (Point center, Point to, int radius) inline
Definition at line 2376 of file Map.cs.
    {
        return Los.ListVisible(center, to, radius, null);
    }
References Los.ListVisible().
Referenced by ActMelee.Attack(), ActRanged.Perform(), and ActEffect.ProcAt().
ListThing< T >()
List< Thing > Map.ListThing< T > () inline
Type Constraints
T : Trait
Definition at line 2571 of file Map.cs.
                                              : Trait
    {
        List<Thing> list = new List<Thing>();
        foreach (Thing thing in this.things)
        {
            if (thing.IsInstalled && thing.trait is T)
            {
                list.Add(thing);
            }
        }
        return list;
    }
References Card.IsInstalled, and Card.trait.
Load()
void Map.Load (string path, bool import = false, PartialMap partial = null) inline
Definition at line 503 of file Map.cs.
    {
        Map.<>c__DisplayClass69_0 CS$<>8__locals1 = new Map.<>c__DisplayClass69_0();
        CS$<>8__locals1.<>4__this = this;
        CS$<>8__locals1.path = path;
        if (partial == null)
        {
            Debug.Log("Map Load:" + this.compression.ToString() + ": " + CS$<>8__locals1.path);
        }
        int num = this.Size;
        int num2 = this.Size;
        if (partial != null)
        {
            num = partial.w;
            num2 = partial.h;
            Debug.Log(string.Concat(new string[]
            {
                this.compression.ToString(),
                ": ",
                num.ToString(),
                "/",
                num2.ToString()
            }));
        }
        CS$<>8__locals1.size = num * num2;
        this.cells = new Cell[num, num2];
        if (this.bounds.maxX == 0)
        {
            this.bounds.SetBounds(0, 0, num - 1, num2 - 1);
        }
        base.SetBounds(0, 0, num - 1, num2 - 1);
        byte[] array = CS$<>8__locals1.<Load>g__TryLoad|0("objVals");
        byte[] array2 = CS$<>8__locals1.<Load>g__TryLoad|0("blockMats");
        byte[] array3 = CS$<>8__locals1.<Load>g__TryLoad|0("blocks");
        byte[] array4 = CS$<>8__locals1.<Load>g__TryLoad|0("floorMats");
        byte[] array5 = CS$<>8__locals1.<Load>g__TryLoad|0("floors");
        byte[] array6 = CS$<>8__locals1.<Load>g__TryLoad|0("objs");
        byte[] array7 = CS$<>8__locals1.<Load>g__TryLoad|0("objMats");
        byte[] array8 = CS$<>8__locals1.<Load>g__TryLoad|0("decal");
        byte[] array9 = CS$<>8__locals1.<Load>g__TryLoad|0("dirs");
        byte[] array10 = CS$<>8__locals1.<Load>g__TryLoad|0("flags");
        byte[] array11 = CS$<>8__locals1.<Load>g__TryLoad|0("flags2");
        byte[] array12 = CS$<>8__locals1.<Load>g__TryLoad|0("heights");
        byte[] array13 = CS$<>8__locals1.<Load>g__TryLoad|0("bridges");
        byte[] array14 = CS$<>8__locals1.<Load>g__TryLoad|0("bridgeMats");
        byte[] array15 = CS$<>8__locals1.<Load>g__TryLoad|0("bridgeHeights");
        byte[] array16 = CS$<>8__locals1.<Load>g__TryLoad|0("bridgePillars");
        byte[] array17 = CS$<>8__locals1.<Load>g__TryLoad|0("roofBlocks");
        byte[] array18 = CS$<>8__locals1.<Load>g__TryLoad|0("roofBlockMats");
        byte[] array19 = CS$<>8__locals1.<Load>g__TryLoad|0("roofBlockDirs");
        if (array16.Length < CS$<>8__locals1.size)
        {
            array16 = new byte[CS$<>8__locals1.size];
        }
        if (array.Length < CS$<>8__locals1.size)
        {
            array = new byte[CS$<>8__locals1.size];
        }
        if (array11.Length < CS$<>8__locals1.size)
        {
            array11 = new byte[CS$<>8__locals1.size];
        }
        CS$<>8__locals1.<Load>g__Validate|1(ref array, "objVals");
        CS$<>8__locals1.<Load>g__Validate|1(ref array2, "blockMats");
        CS$<>8__locals1.<Load>g__Validate|1(ref array3, "blocks");
        CS$<>8__locals1.<Load>g__Validate|1(ref array4, "floorMats");
        CS$<>8__locals1.<Load>g__Validate|1(ref array5, "floors");
        CS$<>8__locals1.<Load>g__Validate|1(ref array6, "objs");
        CS$<>8__locals1.<Load>g__Validate|1(ref array7, "objMats");
        CS$<>8__locals1.<Load>g__Validate|1(ref array8, "decal");
        CS$<>8__locals1.<Load>g__Validate|1(ref array9, "dirs");
        CS$<>8__locals1.<Load>g__Validate|1(ref array10, "flags");
        CS$<>8__locals1.<Load>g__Validate|1(ref array11, "flags2");
        CS$<>8__locals1.<Load>g__Validate|1(ref array12, "heights");
        CS$<>8__locals1.<Load>g__Validate|1(ref array13, "bridges");
        CS$<>8__locals1.<Load>g__Validate|1(ref array14, "bridgeMats");
        CS$<>8__locals1.<Load>g__Validate|1(ref array15, "bridgeHeights");
        CS$<>8__locals1.<Load>g__Validate|1(ref array16, "bridgePillars");
        CS$<>8__locals1.<Load>g__Validate|1(ref array17, "roofBlocks");
        CS$<>8__locals1.<Load>g__Validate|1(ref array18, "roofBlockMats");
        CS$<>8__locals1.<Load>g__Validate|1(ref array19, "roofBlockDirs");
        int num3 = 0;
        for (int i = 0; i < num; i++)
        {
            for (int j = 0; j < num2; j++)
            {
                this.cells[i, j] = new Cell
                {
                    x = (byte)i,
                    z = (byte)j,
                    objVal = array[num3],
                    _blockMat = array2[num3],
                    _block = array3[num3],
                    _floorMat = array4[num3],
                    _floor = array5[num3],
                    obj = array6[num3],
                    objMat = array7[num3],
                    decal = array8[num3],
                    _dirs = array9[num3],
                    height = array12[num3],
                    _bridge = array13[num3],
                    _bridgeMat = array14[num3],
                    bridgeHeight = array15[num3],
                    bridgePillar = array16[num3],
                    _roofBlock = array17[num3],
                    _roofBlockMat = array18[num3],
                    _roofBlockDir = array19[num3],
                    isSeen = array10[num3].GetBit(1),
                    isHarvested = array10[num3].GetBit(2),
                    impassable = array10[num3].GetBit(3),
                    isModified = array10[num3].GetBit(4),
                    isClearSnow = array10[num3].GetBit(5),
                    isForceFloat = array10[num3].GetBit(6),
                    isToggleWallPillar = array10[num3].GetBit(7),
                    isWatered = array11[num3].GetBit(0),
                    isObjDyed = array11[num3].GetBit(1),
                    crossWall = array11[num3].GetBit(2)
                };
                Critter.RebuildCritter(this.cells[i, j]);
                num3++;
            }
        }
        this.things.ForeachReverse(delegate(Thing t)
        {
            if (t.Num <= 0 || t.isDestroyed)
            {
                Debug.Log(string.Concat(new string[]
                {
                    "[bug] Removing bugged thing:",
                    t.Num.ToString(),
                    "/",
                    t.isDestroyed.ToString(),
                    "/",
                    (t != null) ? t.ToString() : null
                }));
                CS$<>8__locals1.<>4__this.things.Remove(t);
            }
        });
        foreach (KeyValuePair<int, CellEffect> keyValuePair in this.cellEffects)
        {
            int key = keyValuePair.Key;
            int num4 = key % this.Size;
            int num5 = key / this.Size;
            this.cells[num4, num5].effect = keyValuePair.Value;
            if (keyValuePair.Value.IsFire)
            {
                this.effectManager.GetOrCreate(new Point(num4, num5));
            }
        }
        this.cellEffects.Clear();
        this.ValidateVersion();
    }
References bounds, cellEffects, cells, compression, Cell.effect, effectManager, LogicalPointManager.GetOrCreate(), Card.isDestroyed, Load(), MapBounds.maxX, Card.Num, Critter.RebuildCritter(), MapBounds.SetBounds(), MapBounds.Size, things, Card.ToString(), ValidateVersion(), MapBounds.x, and MapBounds.z.
Referenced by PartialMap._Load(), Zone.Activate(), and Load().
MineBlock()
void Map.MineBlock (Point point, bool recoverBlock = false, Chara c = null) inline
Definition at line 1650 of file Map.cs.
    {
        bool flag = ActionMode.Mine.IsRoofEditMode(null) && point.cell._roofBlock > 0;
        if (!point.IsValid || (!flag && !point.cell.HasBlock))
        {
            return;
        }
        SourceMaterial.Row row = flag ? point.matRoofBlock : point.matBlock;
        byte b = flag ? point.cell._roofBlock : point.cell._block;
        SourceBlock.Row row2 = EClass.sources.blocks.rows[(int)b];
        Effect.Get("smoke").Play(point, 0f, null, null);
        Effect.Get("mine").Play(point, 0f, null, null).SetParticleColor(row.GetColor()).Emit(10 + EClass.rnd(10));
        point.PlaySound(row.GetSoundDead(row2), true, 1f, true);
        row.AddBlood(point, 8);
        bool flag2 = c == null || c.IsAgent || c.IsPCFactionOrMinion;
        if (flag)
        {
            point.cell._roofBlock = 0;
            this.RefreshSingleTile(point.x, point.z);
        }
        else
        {
            if (point.cell.HasFullBlock)
            {
                this.RemoveLonelyRamps(point.cell);
            }
            point.SetBlock(0, 0);
            if (flag2 && point.sourceObj.tileType.IsBlockMount)
            {
                this.MineObj(point, null, c);
            }
        }
        if (flag2)
        {
            this.DropBlockComponent(point, row2, row, recoverBlock, false, c);
        }
        this.RefreshShadow(point.x, point.z);
        this.RefreshShadow(point.x, point.z - 1);
        this.ValidateInstalled(point);
        this.RefreshFOV(point.x, point.z, 6, false);
        if (flag2 && !point.cell.isModified && !flag)
        {
            if (b == 17 || EClass.rnd(100) == 0)
            {
                this.zone.AddCard(ThingGen.Create("money2", -1, -1), point);
            }
            if (EClass._zone.DangerLv >= 10 && EClass.rnd(200) == 0)
            {
                this.zone.AddCard(ThingGen.Create("crystal_earth", -1, -1), point);
            }
            if (EClass._zone.DangerLv >= 25 && EClass.rnd(200) == 0)
            {
                this.zone.AddCard(ThingGen.Create("crystal_sun", -1, -1), point);
            }
            if (EClass._zone.DangerLv >= 40 && EClass.rnd(200) == 0)
            {
                this.zone.AddCard(ThingGen.Create("crystal_mana", -1, -1), point);
            }
            point.cell.isModified = true;
        }
    }
References Cell._block, EClass._zone, SourceMaterial.Row.AddBlood(), SourceManager.blocks, Point.cell, ThingGen.Create(), Zone.DangerLv, Effect.Get(), SourceMaterial.Row.GetColor(), SourceMaterial.Row.GetSoundDead(), Cell.HasBlock, Cell.HasFullBlock, Cell.isModified, AM_Mine.IsRoofEditMode(), Point.IsValid, Point.matBlock, ActionMode.Mine, Effect.Play(), Point.PlaySound(), EClass.rnd(), Point.SetBlock(), Point.sourceObj, EClass.sources, Point.x, and Point.z.
Referenced by ActEffect.DamageEle(), and TaskMine.OnProgressComplete().
MineFloor()
void Map.MineFloor (Point point, Chara c = null, bool recoverBlock = false, bool removePlatform = true) inline
Definition at line 1729 of file Map.cs.
    {
        if (!point.IsValid || (!point.HasFloor && !point.HasBridge))
        {
            return;
        }
        SourceMaterial.Row row = point.cell.HasBridge ? point.matBridge : point.matFloor;
        SourceFloor.Row c2 = point.cell.HasBridge ? point.sourceBridge : point.sourceFloor;
        Effect.Get("mine").Play(point, 0f, null, null).SetParticleColor(row.GetColor()).Emit(10 + EClass.rnd(10));
        point.PlaySound(row.GetSoundDead(c2), true, 1f, true);
        this.MineObj(point, null, c);
        if (point.cell.HasBridge && removePlatform)
        {
            this.DropBlockComponent(EClass.pc.pos, point.sourceBridge, point.matBridge, recoverBlock, true, c);
            EClass._map.SetBridge(point.x, point.z, 0, 0, 0, 0);
            if (point.IsSky)
            {
                EClass.pc.Kick(point, true);
            }
            return;
        }
        if (EClass._zone.IsSkyLevel)
        {
            this.DropBlockComponent(EClass.pc.pos, point.sourceFloor, row, recoverBlock, false, c);
            this.SetFloor(point.x, point.z, 0, 90);
            if (point.IsSky)
            {
                EClass.pc.Kick(point, true);
            }
            return;
        }
        if (this.zone.IsRegion || point.cell._floor == 40)
        {
            Thing thing = ThingGen.CreateRawMaterial(row);
            thing.ChangeMaterial(row.alias);
            this.TrySmoothPick(point, thing, c);
        }
        else
        {
            this.DropBlockComponent(point, point.sourceFloor, row, recoverBlock, false, c);
        }
        if (EClass._zone.IsRegion || point.sourceFloor.components[0].Contains("chunk@soil"))
        {
            return;
        }
        point.SetFloor(EClass.sources.floors.rows[1].DefaultMaterial.id, 40);
    }
References Cell._floor, EClass._map, EClass._zone, SourceMaterial.Row.alias, Point.cell, Card.ChangeMaterial(), ThingGen.CreateRawMaterial(), SourceManager.floors, Effect.Get(), SourceMaterial.Row.GetColor(), SourceMaterial.Row.GetSoundDead(), Cell.HasBridge, Point.HasBridge, Point.HasFloor, Spatial.IsRegion, Point.IsSky, Zone.IsSkyLevel, Point.IsValid, Chara.Kick(), Point.matBridge, Point.matFloor, EClass.pc, Effect.Play(), Point.PlaySound(), Card.pos, EClass.rnd(), SetBridge(), Point.SetFloor(), Point.sourceBridge, Point.sourceFloor, EClass.sources, Point.x, and Point.z.
Referenced by TaskDig.OnProgressComplete().
MineObj()
void Map.MineObj (Point point, Task task = null, Chara c = null) inline
Definition at line 1815 of file Map.cs.
    {
        Map.<>c__DisplayClass121_0 CS$<>8__locals1;
        CS$<>8__locals1.<>4__this = this;
        CS$<>8__locals1.point = point;
        CS$<>8__locals1.c = c;
        if (!CS$<>8__locals1.point.IsValid || !CS$<>8__locals1.point.HasObj)
        {
            return;
        }
        Cell cell = CS$<>8__locals1.point.cell;
        SourceObj.Row sourceObj = cell.sourceObj;
        bool flag = false;
        if (CS$<>8__locals1.c == null && task != null)
        {
            CS$<>8__locals1.c = task.owner;
        }
        bool flag2 = CS$<>8__locals1.c == null || CS$<>8__locals1.c.IsAgent || CS$<>8__locals1.c.IsPCFactionOrMinion;
        this.DestroyObj(CS$<>8__locals1.point);
        if (flag2)
        {
            SourceMaterial.Row matObj_fixed = cell.matObj_fixed;
            TaskHarvest taskHarvest = task as TaskHarvest;
            if (taskHarvest != null && taskHarvest.IsReapSeed)
            {
                int num = 1 + EClass.rnd(2) + ((EClass.rnd(3) == 0) ? 1 : 0);
                if (EClass._zone.IsPCFaction)
                {
                    int soilCost = EClass._zone.GetSoilCost();
                    int maxSoil = EClass.Branch.MaxSoil;
                    if (soilCost > maxSoil)
                    {
                        num -= EClass.rnd(2 + (soilCost - maxSoil) / 10);
                    }
                }
                if (num <= 0)
                {
                    Msg.Say("seedSpoiled", cell.GetObjName(), null, null, null);
                }
                else
                {
                    Thing t = TraitSeed.MakeSeed(sourceObj, this.TryGetPlant(cell)).SetNum(num);
                    EClass.pc.PickOrDrop(CS$<>8__locals1.point, t, true);
                }
                if (cell.growth.IsTree)
                {
                    cell.isHarvested = true;
                    return;
                }
            }
            else if (sourceObj.HasGrowth)
            {
                cell.growth.PopMineObj(CS$<>8__locals1.c);
            }
            else
            {
                if (cell.HasBlock && (sourceObj.id == 18 || sourceObj.id == 19))
                {
                    this.MineBlock(CS$<>8__locals1.point, false, CS$<>8__locals1.c);
                }
                string alias = sourceObj.alias;
                uint num2 = <PrivateImplementationDetails>.ComputeStringHash(alias);
                if (num2 <= 529228496U)
                {
                    if (num2 != 414349311U)
                    {
                        if (num2 != 489301296U)
{
                            if (num2 == 529228496U)
{
                                if (!(alias == "wreck_junk"))
{
                                }
                            }
                        }
                        else if (!(alias == "wreck_precious"))
{
                        }
                    }
                    else if (alias == "nest_bird")
                    {
                        if (EClass.rnd(5) <= 1)
{
                            this.<MineObj>g__Pop|121_0(ThingGen.Create((EClass.rnd(10) == 0) ? "egg_fertilized" : "_egg", -1, -1).TryMakeRandomItem(-1), ref CS$<>8__locals1);
                        }
                    }
                }
                else if (num2 <= 1575653919U)
                {
                    if (num2 != 1117262783U)
                    {
                        if (num2 == 1575653919U)
{
                            if (!(alias == "wreck_scrap"))
{
                            }
                        }
                    }
                    else if (!(alias == "wreck_stone"))
                    {
                    }
                }
                else if (num2 != 3603235706U)
                {
                    if (num2 == 3937420123U)
                    {
                        if (!(alias == "wreck_wood"))
{
                        }
                    }
                }
                else if (!(alias == "wreck_cloth"))
                {
                }
                int num3 = EClass.rnd(EClass.rnd(sourceObj.components.Length) + 1);
                string[] array = sourceObj.components[num3].Split('/', StringSplitOptions.None);
                Thing thing = ThingGen.Create(array[0], matObj_fixed.alias);
                if (array.Length > 1)
                {
                    thing.SetNum(EClass.rnd(array[1].ToInt()) + 1);
                }
                this.<MineObj>g__Pop|121_0(thing, ref CS$<>8__locals1);
            }
        }
        this.SetObj(CS$<>8__locals1.point.x, CS$<>8__locals1.point.z, 0, 1, 0);
        cell.gatherCount = 0;
        if (flag)
        {
            this.RefreshFOV(CS$<>8__locals1.point.x, CS$<>8__locals1.point.z, 6, false);
        }
    }
References EClass._zone, SourceMaterial.Row.alias, TileRow.alias, EClass.Branch, RenderRow.components, ThingGen.Create(), Cell.GetObjName(), Zone.GetSoilCost(), Cell.growth, Cell.HasBlock, SourceObj.Row.HasGrowth, TileRow.id, Zone.IsPCFaction, TaskHarvest.IsReapSeed, GrowSystem.IsTree, TraitSeed.MakeSeed(), Cell.matObj_fixed, FactionBranch.MaxSoil, EClass.pc, Chara.PickOrDrop(), GrowSystem.PopMineObj(), EClass.rnd(), Msg.Say(), Card.SetNum(), Cell.sourceObj, and Card.TryMakeRandomItem().
Referenced by ActEffect.DamageEle(), TaskHarvest.OnCreateProgress(), TaskCut.OnProgressComplete(), and GrowSystem.OnProgressComplete().
MineObjSound()
void Map.MineObjSound (Point point) inline
Definition at line 1947 of file Map.cs.
    {
        point.PlaySound(point.cell.matObj.GetSoundDead(point.cell.sourceObj), true, 1f, true);
    }
References Point.cell, Cell.matObj, Point.PlaySound(), and Cell.sourceObj.
Referenced by Recipe.Build().
MineRamp()
void Map.MineRamp (Point point, int ramp, bool recoverBlock = false) inline
Definition at line 1712 of file Map.cs.
    {
        if (!point.IsValid || !point.cell.HasFullBlock)
        {
            return;
        }
        SourceMaterial.Row matBlock = point.matBlock;
        byte block = point.cell._block;
        Effect.Get("smoke").Play(point, 0f, null, null);
        Effect.Get("mine").Play(point, 0f, null, null).SetParticleColor(point.matBlock.GetColor()).Emit(10 + EClass.rnd(10));
        this.MineObj(point, null, null);
        int rampDir = EClass._map.GetRampDir(point.x, point.z, EClass.sources.blocks.rows[ramp].tileType);
        this.RemoveLonelyRamps(point.cell);
        this.SetBlock(point.x, point.z, (int)point.cell._blockMat, ramp, rampDir);
        this.DropBlockComponent(point, EClass.sources.blocks.rows[(int)block], matBlock, recoverBlock, false, null);
    }
References Cell._block, Cell._blockMat, EClass._map, SourceManager.blocks, Point.cell, Effect.Get(), GetRampDir(), Cell.HasFullBlock, Point.IsValid, Point.matBlock, Effect.Play(), EClass.rnd(), EClass.sources, Point.x, and Point.z.
Referenced by TaskMine.OnProgressComplete().
ModFire()
void Map.ModFire (int x, int z, int amount) inline
Definition at line 1142 of file Map.cs.
    {
        Cell cell = this.cells[x, z];
        if (cell.IsTopWaterAndNoSnow || cell.IsSnowTile)
        {
            return;
        }
        if (cell.effect == null && amount > 0)
        {
            SE.Play("fire");
        }
        CellEffect effect = cell.effect;
        int num = amount + ((effect != null) ? effect.FireAmount : 0);
        if (num > 20)
        {
            num = 20;
        }
        if (num <= 0)
        {
            cell.effect = null;
            return;
        }
        cell.effect = new CellEffect
        {
            id = 3,
            amount = num
        };
        this.effectManager.GetOrCreate(new Point(x, z));
    }
References cells, Cell.effect, effectManager, CellEffect.FireAmount, LogicalPointManager.GetOrCreate(), Cell.IsSnowTile, Cell.IsTopWaterAndNoSnow, MapBounds.x, and MapBounds.z.
Referenced by RecipeCard.Craft(), Point.ModFire(), and TaskWater.Run().
ModLiquid()
void Map.ModLiquid (int x, int z, int amount) inline
Definition at line 1479 of file Map.cs.
    {
        Cell cell = this.cells[x, z];
        if (cell.IsTopWaterAndNoSnow || cell.effect == null)
        {
            return;
        }
        cell.effect.amount += amount;
        if (cell.effect.amount <= 0)
        {
            cell.effect = null;
        }
    }
References CellEffect.amount, cells, Cell.effect, Cell.IsTopWaterAndNoSnow, MapBounds.x, and MapBounds.z.
Referenced by GameUpdater.SurfaceUpdater.FixedUpdate().
MoveCard()
void Map.MoveCard (Point p, Card t) inline
Definition at line 802 of file Map.cs.
    {
        this._AddCard(p.x, p.z, t, false);
    }
References _AddCard(), Point.x, and Point.z.
Referenced by Chara._Move(), Card._Move(), Card.MoveImmediate(), ResetEditorPos(), Resize(), AI_Trolley.Run(), and Chara.SyncRide().
OnCardAddedToZone()
void Map.OnCardAddedToZone (Card t, int x, int z) inline
Definition at line 769 of file Map.cs.
    {
        if (t.isChara)
        {
            this.charas.Add(t.Chara);
        }
        else
        {
            this.things.Add(t.Thing);
        }
        this.props.OnCardAddedToZone(t);
        if (t.isChara && new Point(x, z).cell.HasFullBlock)
        {
            this.DestroyBlock(x, z);
        }
        this._AddCard(x, z, t, true);
        t.trait.OnAddedToZone();
    }
References _AddCard(), ActPlan.List.Add(), Card.Chara, charas, DestroyBlock(), Card.isChara, Trait.OnAddedToZone(), PropsManager.OnCardAddedToZone(), props, Card.Thing, things, Card.trait, MapBounds.x, and MapBounds.z.
Referenced by Zone.AddCard().
OnCardRemovedFromZone()
void Map.OnCardRemovedFromZone (Card t) inline
Definition at line 788 of file Map.cs.
    {
        t.trait.OnRemovedFromZone();
        t.SetPlaceState(PlaceState.none, false);
        this._RemoveCard(t);
        t.parent = null;
        if (t.isChara)
        {
            this.charas.Remove(t.Chara);
            return;
        }
        this.things.Remove(t.Thing);
    }
References _RemoveCard(), Card.Chara, charas, Card.isChara, Trait.OnRemovedFromZone(), Card.SetPlaceState(), Card.Thing, things, and Card.trait.
Referenced by Zone.RemoveCard().
OnDeactivate()
void Map.OnDeactivate () inline
Definition at line 163 of file Map.cs.
    {
        this.charas.ForeachReverse(delegate(Chara c)
        {
            c.ai = new NoGoal();
            if (c.IsGlobal)
            {
                this.zone.RemoveCard(c);
                c.currentZone = this.zone;
            }
        });
        foreach (Thing thing in this.things)
        {
            if (thing.renderer.hasActor)
            {
                thing.renderer.KillActor();
            }
        }
        EClass.player.ClearMapHighlights();
    }
References charas, Player.ClearMapHighlights(), CardRenderer.hasActor, Chara.IsGlobal, CardRenderer.KillActor(), EClass.player, Zone.RemoveCard(), Card.renderer, things, and zone.
Referenced by Zone.Deactivate().
OnDeserialized()
void Map.OnDeserialized (StreamingContext context) inline private
Definition at line 102 of file Map.cs.
    {
        this.bits.Bits = (uint)this._bits;
    }
References _bits.
OnImport()
void Map.OnImport (ZoneExportData data) inline
Definition at line 667 of file Map.cs.
    {
        this.tasks = new TaskManager();
        data.serializedCards.Restore(this, data.orgMap, false, null);
    }
References ZoneExportData.orgMap, SerializedCards.Restore(), and ZoneExportData.serializedCards.
Referenced by Zone.Activate().
OnLoad()
void Map.OnLoad () inline
Definition at line 661 of file Map.cs.
    {
        this.rooms.OnLoad();
        this.tasks.OnLoad();
    }
References RoomManager.OnLoad(), TaskManager.OnLoad(), rooms, and tasks.
Referenced by Zone.Activate().
OnSerializing() [1/2]
virtual void Map.OnSerializing () inline protected virtual
Definition at line 97 of file Map.cs.
    {
    }
OnSerializing() [2/2]
void Map.OnSerializing (StreamingContext context) inline private
Definition at line 92 of file Map.cs.
    {
        this._bits = (int)this.bits.Bits;
    }
References bits.
OnSetBlockOrDoor()
void Map.OnSetBlockOrDoor (int x, int z) inline
Definition at line 990 of file Map.cs.
    {
        new Point(x, z);
        this.TryRemoveRoom(x, z);
        if (x > 0)
        {
            this.TryRemoveRoom(x - 1, z);
        }
        if (x < this.Size - 1)
        {
            this.TryRemoveRoom(x + 1, z);
        }
        if (z > 0)
        {
            this.TryRemoveRoom(x, z - 1);
        }
        if (z < this.Size - 1)
        {
            this.TryRemoveRoom(x, z + 1);
        }
        if (x > 0 && z < this.Size - 1)
        {
            this.TryRemoveRoom(x - 1, z + 1);
        }
        this.roomHash.Clear();
        this.TryAddRoom(x, z);
        if (x > 0)
        {
            this.TryAddRoom(x - 1, z);
        }
        if (x < this.Size - 1)
        {
            this.TryAddRoom(x + 1, z);
        }
        if (z > 0)
        {
            this.TryAddRoom(x, z - 1);
        }
        if (z < this.Size - 1)
        {
            this.TryAddRoom(x, z + 1);
        }
        if (x > 0 && z < this.Size - 1)
        {
            this.TryAddRoom(x - 1, z + 1);
        }
    }
References roomHash, MapBounds.Size, TryAddRoom(), TryRemoveRoom(), MapBounds.x, and MapBounds.z.
Referenced by SerializedCards.Restore(), SetBlock(), and Card.SetPlaceState().
PutAway()
bool Map.PutAway (Card c) inline
Definition at line 2584 of file Map.cs.
    {
        if (c.IsPC || (c.trait.CanOnlyCarry && !EClass.debug.ignoreBuildRule))
        {
            return false;
        }
        if (c.isChara)
        {
            if (!EClass.debug.ignoreBuildRule)
            {
                return false;
            }
            c.Destroy();
            return true;
        }
        else
        {
            Thing thing = c.Thing;
            if (thing.parent != null)
            {
                thing.parent.RemoveCard(thing);
            }
            thing.isMasked = false;
            thing.isRoofItem = false;
            if (EClass._zone.IsPCFaction && EClass._map.props.installed.traits.GetRandomThing<TraitSpotStockpile>() != null)
            {
                EClass._zone.TryAddThingInSpot<TraitSpotStockpile>(thing, true, true);
                return true;
            }
            if (EClass.debug.enable)
            {
                EClass.debug.GetOrCreateDebugContainer().AddThing(thing, true, -1, -1);
                return true;
            }
            EClass.pc.Pick(thing, false, true);
            return true;
        }
    }
References EClass._map, EClass._zone, Card.AddThing(), Trait.CanOnlyCarry, EClass.debug, Card.Destroy(), CoreDebug.enable, CoreDebug.GetOrCreateDebugContainer(), CoreDebug.ignoreBuildRule, PropsManager.installed, Card.isChara, Card.IsPC, Zone.IsPCFaction, Card.parent, EClass.pc, Chara.Pick(), props, ICardParent.RemoveCard(), Card.Thing, Card.trait, and Props.traits.
Referenced by g__Pop(), AM_Deconstruct.Perform(), and AM_MoveInstalled.TryPutAway().
Quake()
void Map.Quake () inline
Definition at line 2471 of file Map.cs.
    {
        Point point = new Point();
        for (int i = 0; i < this.Size; i++)
        {
            for (int j = 0; j < this.Size; j++)
            {
                point.x = i;
                point.z = j;
                point.Copy().Animate(AnimeID.Quake, true);
                j += EClass.rnd(2);
            }
            i += EClass.rnd(2);
        }
    }
References Point.Animate(), Point.Copy(), and EClass.rnd().
QuickRefreshTile()
void Map.QuickRefreshTile (int x, int z) inline
Definition at line 2189 of file Map.cs.
    {
        Cell cell = this.cells[x, z];
        Cell cell2 = (x > 0) ? this.cells[x - 1, z] : Cell.Void;
        Cell cell3 = (x + 1 < this.Size) ? this.cells[x + 1, z] : Cell.Void;
        Cell cell4 = (z > 0) ? this.cells[x, z - 1] : Cell.Void;
        Cell cell5 = (z + 1 < this.Size) ? this.cells[x, z + 1] : Cell.Void;
        Cell cell6 = (x > 0 && z > 0) ? this.cells[x - 1, z - 1] : Cell.Void;
        Cell cell7 = (x + 1 < this.Size && z > 0) ? this.cells[x + 1, z - 1] : Cell.Void;
        Cell cell8 = (x > 0 && z + 1 < this.Size) ? this.cells[x - 1, z + 1] : Cell.Void;
        Cell cell9 = (x + 1 < this.Size && z + 1 < this.Size) ? this.cells[x + 1, z + 1] : Cell.Void;
        cell.isSurrounded4d = (cell2.HasFullBlock && cell3.HasFullBlock && cell4.HasFullBlock && cell5.HasFullBlock);
        cell.isSurrounded = (cell.isSurrounded4d && cell6.HasFullBlock && cell7.HasFullBlock && cell8.HasFullBlock && cell9.HasFullBlock);
    }
References Cell.Void.
Referenced by MapGen.GenerateTerrain().
RefreshAllTiles()
void Map.RefreshAllTiles () inline
Definition at line 2160 of file Map.cs.
    {
        for (int i = 0; i < this.Size; i++)
        {
            for (int j = 0; j < this.Size; j++)
            {
                this.cells[i, j].Refresh();
            }
        }
    }
Referenced by Zone.Activate(), GameDate.AdvanceMonth(), PartialMap.Apply(), ZoneInspector.FillUtil.FlattenHeight(), MapGenDungen.OnGenerateTerrain(), MapGenRegion.OnGenerateTerrain(), Zone.OnSimulateMonth(), MapGen.Populate(), ZoneInspector.RefreshAll(), and HotItemContext.Show().
RefreshFOV()
void Map.RefreshFOV (int x, int z, int radius = 6, bool recalculate = false) inline
Definition at line 891 of file Map.cs.
    {
        this.ForeachSphere(x, z, (float)radius, delegate(Point p)
        {
            List<Card> list = p.ListCards(false);
            if (recalculate)
            {
                using (List<Card>.Enumerator enumerator = list.GetEnumerator())
                {
                    while (enumerator.MoveNext())
                    {
                        Card card = enumerator.Current;
                        card.RecalculateFOV();
                    }
                    return;
                }
            }
            foreach (Card card2 in list)
            {
                card2.CalculateFOV();
            }
        });
    }
References Card.CalculateFOV(), ForeachSphere(), Point.ListCards(), Card.RecalculateFOV(), and MapBounds.z.
Referenced by GrowSystem.Grow(), WidgetArtTool.OnActivate(), TaskBuild.OnProgressComplete(), TaskMoveInstalled.OnProgressComplete(), TraitDoor.ToggleDoor(), and TraitDoorSwing.ToggleDoor().
RefreshFOVAll()
void Map.RefreshFOVAll () inline
Definition at line 915 of file Map.cs.
    {
        foreach (Card card in EClass._map.things.Concat(EClass._map.charas))
        {
            card.RecalculateFOV();
        }
    }
References EClass._map, charas, Card.RecalculateFOV(), and things.
Referenced by ColorProfile.OnValidate().
RefreshNeighborTiles()
void Map.RefreshNeighborTiles (int x, int z) inline
Definition at line 2171 of file Map.cs.
    {
        this.cells[x, z].Refresh();
        for (int i = x - 2; i < x + 3; i++)
        {
            if (i >= 0 && i < this.Size)
            {
                for (int j = z - 2; j < z + 3; j++)
                {
                    if (j >= 0 && j < this.Size && (x != i || z != j))
                    {
                        this.cells[i, j].Refresh();
                    }
                }
            }
        }
    }
Referenced by Burn(), Point.RefreshNeighborTiles(), SetBlock(), SetBridge(), SetFloor(), SetObj(), and SetSeen().
RefreshShadow()
void Map.RefreshShadow (int x, int z) inline
Definition at line 1777 of file Map.cs.
    {
    }
Referenced by TaskBuild.OnProgressComplete().
RefreshSingleTile()
void Map.RefreshSingleTile (int x, int z) inline
Definition at line 2155 of file Map.cs.
    {
        this.cells[x, z].Refresh();
    }
Referenced by GameUpdater.LogicUpdater.FixedUpdate(), Point.RefreshTile(), SetRoofBlock(), TraitDoor.ToggleDoor(), and TraitDoorSwing.ToggleDoor().
RefreshSunMap()
void Map.RefreshSunMap () inline
Definition at line 2768 of file Map.cs.
    {
        if (Map.isDirtySunMap)
        {
            Map.sunMap.Clear();
            foreach (Trait trait in EClass._map.props.installed.traits.suns.Values)
            {
                foreach (Point point in trait.ListPoints(null, false))
                {
                    Map.sunMap.Add(point.index);
                }
            }
            Map.isDirtySunMap = false;
        }
    }
References EClass._map, Point.index, PropsManager.installed, isDirtySunMap, Trait.ListPoints(), props, sunMap, TraitManager.suns, and Props.traits.
Referenced by GameUpdater.Update().
Reload()
void Map.Reload () inline
Definition at line 269 of file Map.cs.
    {
        this.rooms = new RoomManager();
        this.SetReference();
        string id = Game.id;
        EClass.game.Save(false, null, false);
        EClass.scene.Init(Scene.Mode.None);
        Game.Load(id);
        this.RevealAll(true);
        TweenUtil.Tween(0.1f, null, delegate()
        {
            this.ReloadRoom();
        });
    }
References EClass.game, Game.id, Scene.Init(), Game.Load(), ReloadRoom(), RevealAll(), Game.Save(), EClass.scene, and SetReference().
Referenced by Resize(), and Shift().
ReloadRoom()
void Map.ReloadRoom () inline
Definition at line 284 of file Map.cs.
    {
        List<Thing> list = new List<Thing>();
        foreach (Thing thing in this.things)
        {
            if (thing.trait.IsDoor)
            {
                list.Add(thing);
            }
        }
        foreach (Thing thing2 in list)
        {
            Point pos = thing2.pos;
            EClass._zone.RemoveCard(thing2);
            EClass._zone.AddCard(thing2, pos);
            thing2.Install();
        }
        this.rooms.RefreshAll();
    }
References EClass._zone, Zone.AddCard(), Card.Install(), Trait.IsDoor, Card.pos, RoomManager.RefreshAll(), Zone.RemoveCard(), rooms, things, and Card.trait.
Referenced by MapGenDungen.OnGenerateTerrain(), and Reload().
RemoveLonelyRamps()
void Map.RemoveLonelyRamps (Cell cell) inline
Definition at line 2019 of file Map.cs.
    {
        for (int i = 0; i < 4; i++)
        {
            Cell dependedRamp = this.GetDependedRamp(cell);
            if (dependedRamp == null)
            {
                break;
            }
            this.MineBlock(dependedRamp.GetPoint(), false, null);
        }
    }
References Cell.GetPoint().
RemovePlant()
void Map.RemovePlant (Point pos) inline
Definition at line 1972 of file Map.cs.
    {
        this.plants.Remove(pos.index);
    }
References Point.index.
Reset()
void Map.Reset () inline
Definition at line 304 of file Map.cs.
    {
        for (int i = 0; i < this.Size; i++)
        {
            for (int j = 0; j < this.Size; j++)
            {
                this.cells[i, j].Reset();
            }
        }
        this.SetReference();
    }
References cells, Cell.Reset(), SetReference(), and MapBounds.Size.
Referenced by MapGen.OnGenerateTerrain().
ResetEditorPos()
void Map.ResetEditorPos () inline
Definition at line 316 of file Map.cs.
    {
        EClass._zone.Revive();
        foreach (Chara chara in this.charas)
        {
            if (chara.isPlayerCreation && chara.orgPos != null)
            {
                this.MoveCard(chara.orgPos, chara);
            }
        }
        foreach (Thing thing in this.things)
        {
            if (thing.trait is TraitDoor)
            {
                (thing.trait as TraitDoor).ForceClose();
            }
        }
    }
References EClass._zone, charas, Card.isPlayerCreation, MoveCard(), Chara.orgPos, Zone.Revive(), things, and Card.trait.
Referenced by Zone.Export(), and BuildMenu.OnActivate().
Resize()
void Map.Resize (int newSize) inline
Definition at line 184 of file Map.cs.
    {
        Point p = new Point(0, 0);
        foreach (Thing thing in EClass._map.things)
        {
            if (thing.pos.x >= newSize || thing.pos.z >= newSize)
            {
                this.MoveCard(p, thing);
            }
        }
        foreach (Chara chara in EClass._map.charas)
        {
            if (chara.pos.x >= newSize || chara.pos.z >= newSize)
            {
                this.MoveCard(p, chara);
            }
        }
        this.bounds.Size = newSize;
        this.Size = newSize;
        this.maxX = (this.maxZ = this.Size);
        this.cells = Util.ResizeArray<Cell>(EClass._map.cells, newSize, newSize, (int x, int y) => new Cell
        {
            x = (byte)x,
            z = (byte)y,
            isSeen = true
        });
        this.Reload();
    }
References EClass._map, cells, charas, MoveCard(), Card.pos, Reload(), MapBounds.Size, things, MapBounds.x, Point.x, MapBounds.z, and Point.z.
Referenced by ZoneInspector.ResizeUtil.Apply(), and MapGen.OnGenerateTerrain().
Reveal()
void Map.Reveal (Point center, int power = 100) inline
Definition at line 880 of file Map.cs.
    {
        this.ForeachSphere(center.x, center.z, (float)(10 + power / 5), delegate(Point p)
        {
            if (EClass.rnd(power) >= Mathf.Min(p.Distance(center) * 10, power - 10))
            {
                EClass._map.SetSeen(p.x, p.z, true, true);
            }
        });
    }
References Point.Distance(), ForeachSphere(), EClass.rnd(), Point.x, and Point.z.
Referenced by ActEffect.Proc().
RevealAll()
void Map.RevealAll (bool reveal = true) inline
Definition at line 867 of file Map.cs.
    {
        for (int i = 0; i < this.Size; i++)
        {
            for (int j = 0; j < this.Size; j++)
            {
                EClass._map.SetSeen(i, j, reveal, false);
            }
        }
        this.revealed = !this.revealed;
        WidgetMinimap.UpdateMap();
    }
References EClass._map, revealed, SetSeen(), MapBounds.Size, and WidgetMinimap.UpdateMap().
Referenced by BuildMenu.Activate(), Zone.ClaimZone(), ZoneProfile.Generate(), DramaManager.ParseLine(), ActEffect.Proc(), Reload(), and CoreDebug.ToggleRevealMap().
Save()
void Map.Save (string path, ZoneExportData export = null, PartialMap partial = null) inline
Definition at line 335 of file Map.cs.
    {
        this.version = EClass.core.version;
        Debug.Log("#io saving map:" + path);
        IO.CreateDirectory(path);
        int num = 0;
        int num2 = 0;
        int num3 = this.Size;
        int num4 = this.Size;
        if (partial != null)
        {
            num = partial.offsetX;
            num2 = partial.offsetZ;
            num3 = partial.w;
            num4 = partial.h;
        }
        int num5 = num3 * num4;
        byte[] array = new byte[num5];
        byte[] array2 = new byte[num5];
        byte[] array3 = new byte[num5];
        byte[] array4 = new byte[num5];
        byte[] array5 = new byte[num5];
        byte[] array6 = new byte[num5];
        byte[] array7 = new byte[num5];
        byte[] array8 = new byte[num5];
        byte[] array9 = new byte[num5];
        byte[] array10 = new byte[num5];
        byte[] array11 = new byte[num5];
        byte[] array12 = new byte[num5];
        byte[] array13 = new byte[num5];
        byte[] array14 = new byte[num5];
        byte[] array15 = new byte[num5];
        byte[] array16 = new byte[num5];
        byte[] array17 = new byte[num5];
        byte[] array18 = new byte[num5];
        byte[] array19 = new byte[num5];
        this.cellEffects.Clear();
        int num6 = 0;
        for (int i = num; i < num + num3; i++)
        {
            for (int j = num2; j < num2 + num4; j++)
            {
                Cell cell = this.cells[i, j];
                array[num6] = cell.objVal;
                array3[num6] = cell._blockMat;
                array2[num6] = cell._block;
                array5[num6] = cell._floorMat;
                array4[num6] = cell._floor;
                array6[num6] = cell.obj;
                array7[num6] = cell.objMat;
                array8[num6] = cell.decal;
                array9[num6] = cell._dirs;
                array12[num6] = cell.height;
                array13[num6] = cell._bridge;
                array14[num6] = cell._bridgeMat;
                array15[num6] = cell.bridgeHeight;
                array17[num6] = cell._roofBlockDir;
                array18[num6] = cell._roofBlock;
                array19[num6] = cell._roofBlockMat;
                array16[num6] = cell.bridgePillar;
                array10[num6] = array10[num6].SetBit(1, cell.isSeen);
                array10[num6] = array10[num6].SetBit(2, cell.isHarvested);
                array10[num6] = array10[num6].SetBit(3, cell.impassable);
                array10[num6] = array10[num6].SetBit(4, cell.isModified);
                array10[num6] = array10[num6].SetBit(5, cell.isClearSnow);
                array10[num6] = array10[num6].SetBit(6, cell.isForceFloat);
                array10[num6] = array10[num6].SetBit(7, cell.isToggleWallPillar);
                array11[num6] = array11[num6].SetBit(0, cell.isWatered);
                array11[num6] = array11[num6].SetBit(1, cell.isObjDyed);
                array11[num6] = array11[num6].SetBit(2, cell.crossWall);
                if (cell.effect != null)
                {
                    this.cellEffects[j * num4 + i] = cell.effect;
                }
                num6++;
            }
        }
        this.compression = IO.Compression.None;
        IO.WriteLZ4(path + "objVals", array);
        IO.WriteLZ4(path + "blocks", array2);
        IO.WriteLZ4(path + "blockMats", array3);
        IO.WriteLZ4(path + "floors", array4);
        IO.WriteLZ4(path + "floorMats", array5);
        IO.WriteLZ4(path + "objs", array6);
        IO.WriteLZ4(path + "objMats", array7);
        IO.WriteLZ4(path + "decal", array8);
        IO.WriteLZ4(path + "flags", array10);
        IO.WriteLZ4(path + "flags2", array11);
        IO.WriteLZ4(path + "dirs", array9);
        IO.WriteLZ4(path + "heights", array12);
        IO.WriteLZ4(path + "bridges", array13);
        IO.WriteLZ4(path + "bridgeMats", array14);
        IO.WriteLZ4(path + "bridgeHeights", array15);
        IO.WriteLZ4(path + "bridgePillars", array16);
        IO.WriteLZ4(path + "roofBlocks", array18);
        IO.WriteLZ4(path + "roofBlockMats", array19);
        IO.WriteLZ4(path + "roofBlockDirs", array17);
        this.things.Sort((Thing a, Thing b) => a.stackOrder - b.stackOrder);
        if (export == null)
        {
            foreach (Chara chara in this.charas)
            {
                if (!chara.IsGlobal)
                {
                    this.serializedCharas.Add(chara);
                }
            }
            GameIO.SaveFile(path + "map", this);
        }
        else
        {
            export.serializedCards.cards.Clear();
            if (partial == null)
            {
                foreach (Chara chara2 in this.charas)
                {
                    if (export.usermap)
                    {
                        if (!chara2.trait.IsUnique && !chara2.IsPC)
{
                            export.serializedCards.Add(chara2);
                        }
                    }
                    else if (!chara2.IsGlobal && chara2.isPlayerCreation)
                    {
                        export.serializedCards.Add(chara2);
                    }
                }
                using (List<Thing>.Enumerator enumerator2 = this.things.GetEnumerator())
                {
                    while (enumerator2.MoveNext())
                    {
                        Thing thing = enumerator2.Current;
                        if (thing.isPlayerCreation && thing.c_altName != "DebugContainer")
{
                            export.serializedCards.Add(thing);
                        }
                    }
                    goto IL_68A;
                }
            }
            foreach (Thing thing2 in this.things)
            {
                if ((ActionMode.Copy.IsActive || thing2.trait.CanCopyInBlueprint) && thing2.pos.x >= num && thing2.pos.z >= num2 && thing2.pos.x < num + num3 && thing2.pos.z < num2 + num4)
                {
                    export.serializedCards.Add(thing2);
                }
            }
            IL_68A:
            List<Thing> list = this.things;
            this.things = new List<Thing>();
            GameIO.SaveFile(path + "map", this);
            this.things = list;
        }
        this.serializedCharas.Clear();
    }
References Cell._block, Cell._blockMat, Cell._bridge, Cell._bridgeMat, Cell._dirs, Cell._floor, Cell._floorMat, Cell._roofBlock, Cell._roofBlockDir, Cell._roofBlockMat, Card.Add(), Cell.bridgeHeight, Cell.bridgePillar, Card.c_altName, Trait.CanCopyInBlueprint, cellEffects, cells, charas, ActionMode.Copy, EClass.core, Cell.crossWall, Cell.decal, Cell.effect, Cell.height, Cell.impassable, ActionMode.IsActive, Cell.isClearSnow, Cell.isForceFloat, Chara.IsGlobal, Cell.isHarvested, Cell.isModified, Cell.isObjDyed, Chara.IsPC, Card.isPlayerCreation, Cell.isSeen, Cell.isToggleWallPillar, TraitChara.IsUnique, Cell.isWatered, Cell.obj, Cell.objMat, Cell.objVal, GameIO.SaveFile(), serializedCharas, MapBounds.Size, Thing.stackOrder, things, Card.trait, and Chara.trait.
Referenced by Zone._OnBeforeSave().
SetBlock() [1/2]
void Map.SetBlock (int x, int z, int idMat, int idBlock, int dir) inline
Definition at line 967 of file Map.cs.
    {
        Cell cell = this.cells[x, z];
        bool hasFloodBlock = cell.HasFloodBlock;
        cell._blockMat = (byte)idMat;
        cell._block = (byte)idBlock;
        cell.blockDir = dir;
        if (cell.effect == null || !cell.effect.IsFire)
        {
            cell.effect = null;
        }
        cell.isToggleWallPillar = false;
        if (cell.room != null)
        {
            cell.room.SetDirty();
        }
        if (hasFloodBlock || cell.HasFloodBlock)
        {
            this.OnSetBlockOrDoor(x, z);
        }
        this.RefreshNeighborTiles(x, z);
    }
References cells, Cell.effect, Cell.HasFloodBlock, CellEffect.IsFire, OnSetBlockOrDoor(), RefreshNeighborTiles(), Cell.room, Room.SetDirty(), MapBounds.x, and MapBounds.z.
SetBlock() [2/2]
void Map.SetBlock (int x, int z, int idMat = 0, int idBlock = 0) inline
Definition at line 962 of file Map.cs.
    {
        this.SetBlock(x, z, idMat, idBlock, 0);
    }
References SetBlock(), and MapBounds.z.
Referenced by Recipe.Build(), ZoneInspector.FillUtil.ClearBlock(), ZoneInspector.FillUtil.FillBlock(), Point.SetBlock(), and SetBlock().
SetBlockDir()
void Map.SetBlockDir (int x, int z, int dir) inline
Definition at line 1135 of file Map.cs.
    {
        Cell cell = this.cells[x, z];
        cell._block = (byte)cell.sourceBlock.id;
        cell.blockDir = dir;
    }
References Cell.blockDir, cells, Cell.sourceBlock, MapBounds.x, and MapBounds.z.
Referenced by Recipe.Build().
SetBounds() [1/2]
void Map.SetBounds (int size) inline
Definition at line 2381 of file Map.cs.
    {
        if (size > this.Size / 2 + 1)
        {
            size = this.Size / 2 - 1;
        }
        this.bounds.SetBounds(this.Size / 2 - size, this.Size / 2 - size, this.Size / 2 + size, this.Size / 2 + size);
    }
Referenced by MapGen.OnGenerateTerrain().
SetBounds() [2/2]
void Map.SetBounds (MapBounds b) inline
Definition at line 2390 of file Map.cs.
    {
        this.bounds.SetBounds(b.x, b.z, b.maxX, b.maxZ);
        this.bounds.Size = b.Size;
    }
References MapBounds.maxX, MapBounds.maxZ, MapBounds.Size, MapBounds.x, and MapBounds.z.
SetBridge()
void Map.SetBridge (int x, int z, int height = 0, int idMat = 0, int idBridge = 0, int dir = 0) inline
Definition at line 938 of file Map.cs.
    {
        Cell cell = this.cells[x, z];
        cell.bridgeHeight = (byte)height;
        cell._bridgeMat = (byte)idMat;
        cell._bridge = (byte)idBridge;
        cell.bridgePillar = 0;
        cell.floorDir = dir;
        if (cell.room != null)
        {
            cell.room.SetDirty();
        }
        this.RefreshNeighborTiles(x, z);
    }
References cells, RefreshNeighborTiles(), Cell.room, Room.SetDirty(), MapBounds.x, and MapBounds.z.
Referenced by Recipe.Build(), MineFloor(), and TaskDig.OnProgressComplete().
SetDecal()
void Map.SetDecal (int x, int z, int id = 0, int amount = 1, bool refresh = true) inline
Definition at line 2064 of file Map.cs.
    {
        this.cells[x, z].decal = (byte)(id * 8 + ((id == 0) ? 0 : amount));
        if (refresh)
        {
            this.RefreshNeighborTiles(x, z);
        }
    }
Referenced by AM_MoveInstalled.HitTest(), AIWork_Clean.OnPerformWork(), TaskCut.OnProgressComplete(), AI_Clean.Run(), and TraitBroom.TrySetHeldAct().
SetEffect()
void Map.SetEffect (int x, int z, CellEffect effect = null) inline
Definition at line 1474 of file Map.cs.
    {
        this.cells[x, z].effect = effect;
    }
References cells, Cell.effect, MapBounds.x, and MapBounds.z.
Referenced by Chara._Move(), GameUpdater.FastSurfaceUpdater.FixedUpdate(), and ActEffect.ProcAt().
SetFloor() [1/2]
void Map.SetFloor (int x, int z, int idMat, int idFloor, int dir) inline
Definition at line 928 of file Map.cs.
    {
        Cell cell = this.cells[x, z];
        cell._floorMat = (byte)idMat;
        cell._floor = (byte)idFloor;
        cell.floorDir = dir;
        Critter.RebuildCritter(cell);
        this.RefreshNeighborTiles(x, z);
    }
References cells, Critter.RebuildCritter(), RefreshNeighborTiles(), MapBounds.x, and MapBounds.z.
SetFloor() [2/2]
void Map.SetFloor (int x, int z, int idMat = 0, int idFloor = 0) inline
Definition at line 923 of file Map.cs.
    {
        this.SetFloor(x, z, idMat, idFloor, 0);
    }
References SetFloor(), and MapBounds.z.
Referenced by Recipe.Build(), ZonePreEnterDigStairs.Execute(), ZoneInspector.FillUtil.FillFloor(), Point.SetFloor(), and SetFloor().
SetFoormark()
void Map.SetFoormark (Point pos, int id, int angle, int offset = 0) inline
Definition at line 2073 of file Map.cs.
    {
        Cell cell = pos.cell;
        int tile = this.AngleToIndex(angle) + offset;
        Footmark footmark = new Footmark
        {
            tile = tile,
            remaining = 10
        };
        footmark.pos.Set(pos);
        this.footmarks.Add(footmark);
        cell.GetOrCreateDetail().footmark = footmark;
    }
References Point.cell, CellDetail.footmark, Cell.GetOrCreateDetail(), Footmark.pos, and Point.Set().
Referenced by Chara._Move().
SetLiquid() [1/2]
void Map.SetLiquid (int x, int z, CellEffect effect = null) inline
Definition at line 1441 of file Map.cs.
    {
        Cell cell = this.cells[x, z];
        if (cell.IsTopWaterAndNoSnow && effect != null)
        {
            return;
        }
        cell.effect = effect;
    }
References cells, Cell.IsTopWaterAndNoSnow, MapBounds.x, and MapBounds.z.
Referenced by GameUpdater.SurfaceUpdater.FixedUpdate(), TaskDrawWater.g__ChangeFloor(), TaskPourWater.g__ChangeFloor(), AI_Water.OnProgressComplete(), TraitDrink.OnThrowGround(), AI_Bladder.Run(), AI_Clean.Run(), TaskWater.Run(), TraitBroom.TrySetHeldAct(), and CoreDebug.UpdateInput().
SetLiquid() [2/2]
void Map.SetLiquid (int x, int z, int id, int value = 1) inline
Definition at line 1451 of file Map.cs.
    {
        Cell cell = this.cells[x, z];
        if (cell.IsTopWaterAndNoSnow && value != 0)
        {
            return;
        }
        if (value > 3)
        {
            value = 3;
        }
        if (value <= 0)
        {
            cell.effect = null;
            return;
        }
        cell.effect = new CellEffect
        {
            id = id,
            amount = value
        };
    }
References cells, Cell.IsTopWaterAndNoSnow, MapBounds.x, and MapBounds.z.
SetObj() [1/2]
void Map.SetObj (int x, int z, int id = 0, int value = 1, int dir = 0) inline
Definition at line 1502 of file Map.cs.
    {
        this.SetObj(x, z, (int)((byte)EClass.sources.objs.rows[id].DefaultMaterial.id), id, value, dir);
    }
References SourceManager.objs, SetObj(), EClass.sources, and MapBounds.z.
Referenced by Recipe.Build(), Burn(), ZoneInspector.FillUtil.ClearBridge(), ZoneInspector.FillUtil.ClearObj(), GenRoom.OnPopulate(), TraitFertilizer.OnSimulateHour(), GrowSystem.Perish(), Point.SetObj(), and SetObj().
SetObj() [2/2]
void Map.SetObj (int x, int z, int idMat, int idObj, int value, int dir) inline
Definition at line 1507 of file Map.cs.
    {
        Cell cell = this.cells[x, z];
        cell.obj = (byte)idObj;
        cell.objVal = (byte)value;
        cell.objMat = (byte)idMat;
        cell.objDir = dir;
        cell.isHarvested = false;
        cell.isObjDyed = false;
        SourceObj.Row sourceObj = cell.sourceObj;
        if (!sourceObj.matCategory.IsEmpty())
        {
            int num = EClass._zone.DangerLv;
            if (sourceObj.tag.Contains("spot"))
            {
                num += EClass.pc.Evalue(1656) * 5;
            }
            cell.objMat = (byte)MATERIAL.GetRandomMaterialFromCategory(num, sourceObj.matCategory.Split(',', StringSplitOptions.None), cell.matObj).id;
        }
        if (this.backerObjs.ContainsKey(cell.index))
        {
            this.backerObjs.Remove(cell.index);
        }
        if (this.plants.ContainsKey(cell.index))
        {
            this.plants.Remove(cell.index);
        }
        Critter.RebuildCritter(cell);
        this.RefreshNeighborTiles(x, z);
    }
References EClass._zone, backerObjs, cells, Zone.DangerLv, Card.Evalue(), MATERIAL.GetRandomMaterialFromCategory(), Cell.index, SourceObj.Row.matCategory, Cell.matObj, EClass.pc, plants, Critter.RebuildCritter(), RefreshNeighborTiles(), Cell.sourceObj, RenderRow.tag, MapBounds.x, and MapBounds.z.
SetReference()
void Map.SetReference () inline
Definition at line 149 of file Map.cs.
    {
        CellDetail.map = this;
        Point.map = this;
        Wall.map = this;
        Cell.map = this;
        Fov.map = this;
        Cell.Size = this.Size;
        Cell.cells = this.cells;
        IPathfinder pathfinder = PathManager.Instance.pathfinder;
        WeightCell[,] weightMap = this.cells;
        pathfinder.Init(this, weightMap, this.Size);
    }
References cells, IPathfinder.Init(), PathManager.Instance, PathManager.pathfinder, and MapBounds.Size.
Referenced by PartialMap._Load(), Zone.Activate(), PartialMap.Apply(), CreateNew(), Reload(), Reset(), and SetZone().
SetRoofBlock()
void Map.SetRoofBlock (int x, int z, int idMat, int idBlock, int dir, int height) inline
Definition at line 953 of file Map.cs.
    {
        Cell cell = this.cells[x, z];
        cell._roofBlockMat = (byte)idMat;
        cell._roofBlock = (byte)idBlock;
        cell._roofBlockDir = (byte)(dir + height * 4);
        this.RefreshSingleTile(x, z);
    }
References cells, RefreshSingleTile(), MapBounds.x, and MapBounds.z.
Referenced by Recipe.Build().
SetSeen()
void Map.SetSeen (int x, int z, bool seen = true, bool refresh = true) inline
Definition at line 853 of file Map.cs.
    {
        if (this.cells[x, z].isSeen == seen)
        {
            return;
        }
        this.cells[x, z].isSeen = seen;
        if (refresh)
        {
            WidgetMinimap.UpdateMap(x, z);
        }
        EClass._map.RefreshNeighborTiles(x, z);
    }
References EClass._map, cells, Cell.isSeen, RefreshNeighborTiles(), WidgetMinimap.UpdateMap(), MapBounds.x, and MapBounds.z.
Referenced by Fov.Perform(), and RevealAll().
SetZone()
void Map.SetZone (Zone _zone) inline
Definition at line 135 of file Map.cs.
    {
        this.zone = _zone;
        this.zone.bounds = this.bounds;
        this.bounds.Size = this.Size;
        this.SetReference();
        this.props.Init();
        EClass.scene.profile = SceneProfile.Load(this.config.idSceneProfile.IsEmpty("default"));
        if (!this.config.idFowProfile.IsEmpty())
        {
            this.fowProfile = FowProfile.Load(this.config.idFowProfile);
        }
    }
References EClass._zone, bounds, config, MapConfig.idFowProfile, MapConfig.idSceneProfile, PropsManager.Init(), FowProfile.Load(), SceneProfile.Load(), props, SetReference(), and MapBounds.Size.
Referenced by Zone.Activate(), Zone.Generate(), ZoneBlueprint.GenerateMap(), MapGen.GenerateTerrain(), MapGenDungen.OnGenerateTerrain(), and MapGenRegion.OnGenerateTerrain().
Shift()
void Map.Shift (Vector2Int offset) inline
Definition at line 213 of file Map.cs.
    {
        TweenUtil.Tween(0.1f, null, delegate()
        {
            foreach (Card card in EClass._map.things.Concat(EClass._map.charas))
            {
                card.pos.x += offset.x;
                card.pos.z += offset.y;
                card.pos.Clamp(false);
            }
            Cell[,] array = new Cell[this.Size, this.Size];
            for (int i = 0; i < this.Size; i++)
            {
                int num = i - offset.y;
                for (int j = 0; j < this.Size; j++)
                {
                    int num2 = j - offset.x;
                    if (num2 >= 0 && num2 < this.Size && num >= 0 && num < this.Size)
                    {
                        array[j, i] = this.cells[num2, num];
                    }
                    else
                    {
                        array[j, i] = new Cell
{
                            x = (byte)j,
                            z = (byte)i
                        };
                    }
                }
            }
            this.cells = array;
            this.bounds.x += offset.x;
            this.bounds.z += offset.y;
            this.bounds.maxX += offset.x;
            this.bounds.maxZ += offset.y;
            if (this.bounds.x < 0)
            {
                this.bounds.x = 0;
            }
            if (this.bounds.z < 0)
            {
                this.bounds.z = 0;
            }
            if (this.bounds.maxX > this.Size)
            {
                this.bounds.maxX = this.Size;
            }
            if (this.bounds.maxZ > this.Size)
            {
                this.bounds.maxZ = this.Size;
            }
            this.Reload();
        });
    }
References EClass._map, bounds, cells, charas, MapBounds.maxX, MapBounds.maxZ, Reload(), MapBounds.Size, things, Cell.x, MapBounds.x, and MapBounds.z.
Referenced by ZoneInspector.ResizeUtil.Apply().
TryAddRoom()
void Map.TryAddRoom (int x, int z) inline
Definition at line 1051 of file Map.cs.
    {
        if (EClass._zone.DisableRooms)
        {
            return;
        }
        if (this.roomHash.Contains(x + z * this.Size) || this.cells[x, z].HasFloodBlock)
        {
            return;
        }
        FloodSpiller floodSpiller = this.flood;
        IFloodCell[,] array = this.cells;
        FloodSpiller.Result result = floodSpiller.SpillFlood(array, x, z);
        if (!result.IsValid)
        {
            return;
        }
        bool flag = false;
        foreach (IFloodCell floodCell in result.visited)
        {
            if (floodCell.hasDoor)
            {
                flag = true;
                break;
            }
            Cell cell = floodCell as Cell;
            if (cell.sourceBlock.tileType.IsFloodDoor || cell.Front.hasDoor || cell.Right.hasDoor || cell.FrontRight.hasDoor || cell.Back.hasDoor || cell.Left.hasDoor || cell.BackLeft.hasDoor)
            {
                flag = true;
                break;
            }
        }
        if (!flag && this.IsIndoor)
        {
            foreach (IFloodCell floodCell2 in result.visited)
            {
                Cell cell2 = floodCell2 as Cell;
                if (cell2.detail != null && cell2.detail.things.Count != 0)
                {
                    foreach (Thing thing in cell2.detail.things)
                    {
                        if (thing.trait is TraitRoomPlate || thing.trait is TraitHouseBoard)
{
                            flag = true;
                            break;
                        }
                    }
                    if (flag)
                    {
                        break;
                    }
                }
            }
        }
        if (!flag)
        {
            return;
        }
        Room room = this.rooms.AddRoom(new Room());
        foreach (IFloodCell floodCell3 in result.visited)
        {
            Cell cell3 = floodCell3 as Cell;
            byte x2 = cell3.x;
            byte z2 = cell3.z;
            room.AddPoint(new Point((int)x2, (int)z2));
            this.roomHash.Add((int)x2 + (int)z2 * this.Size);
            if (z2 > 0 && cell3.Front.HasFloodBlock && cell3.Front.room == null)
            {
                room.AddPoint(new Point((int)x2, (int)(z2 - 1)));
                this.roomHash.Add((int)x2 + (int)(z2 - 1) * this.Size);
            }
            if ((int)x2 < this.Size - 1 && cell3.Right.HasFloodBlock && cell3.Right.room == null)
            {
                room.AddPoint(new Point((int)(x2 + 1), (int)z2));
                this.roomHash.Add((int)(x2 + 1) + (int)z2 * this.Size);
            }
            if (z2 > 0 && (int)x2 < this.Size - 1 && cell3.FrontRight.HasFloodBlock && cell3.FrontRight.room == null)
            {
                room.AddPoint(new Point((int)(x2 + 1), (int)(z2 - 1)));
                this.roomHash.Add((int)(x2 + 1) + (int)(z2 - 1) * this.Size);
            }
        }
    }
References EClass._zone, RoomManager.AddRoom(), Cell.Back, Cell.BackLeft, cells, Cell.detail, Zone.DisableRooms, flood, Cell.Front, Cell.FrontRight, Cell.hasDoor, Cell.HasFloodBlock, IsIndoor, Cell.Left, Cell.Right, Cell.room, roomHash, rooms, MapBounds.Size, Cell.sourceBlock, CellDetail.things, Card.trait, Cell.x, MapBounds.x, Cell.z, and MapBounds.z.
Referenced by OnSetBlockOrDoor().
TryGetPlant() [1/2]
PlantData Map.TryGetPlant (Cell c) inline
Definition at line 1957 of file Map.cs.
    {
        return this.plants.TryGetValue(c.index, null);
    }
References Cell.index.
TryGetPlant() [2/2]
PlantData Map.TryGetPlant (Point p) inline
Definition at line 1952 of file Map.cs.
    {
        return this.plants.TryGetValue(p.index, null);
    }
References Point.index.
Referenced by GrowSystem.ApplySeed(), GrowSystem.EqualizePlants(), Cell.GetObjName(), GrowSystem.Grow(), GrowSystemPasture.OnMineObj(), GrowSystemTree.OnMineObj(), TraitFertilizer.OnSimulateHour(), GrowSystem.PopHarvest(), BaseTaskHarvest.SetTarget(), Cell.TryGetPlant(), and GrowSystem.TryPopSeed().
TryLoadFile()
byte[] Map.TryLoadFile (string path, string s, int size) inline
Definition at line 492 of file Map.cs.
    {
        byte[] array = IO.ReadLZ4(path + s, size, this.compression);
        if (array == null)
        {
            Debug.Log("Couldn't load:" + s);
            return new byte[size];
        }
        return array;
    }
References compression.
Referenced by Zone.Activate().
TryRemoveRoom()
void Map.TryRemoveRoom (int x, int z) inline
Definition at line 1038 of file Map.cs.
    {
        if (this.cells[x, z].HasFloodBlock)
        {
            return;
        }
        Room room = this.cells[x, z].room;
        if (room != null)
        {
            this.rooms.RemoveRoom(room);
        }
    }
References cells, RoomManager.RemoveRoom(), Cell.room, rooms, MapBounds.x, and MapBounds.z.
Referenced by OnSetBlockOrDoor().
TryShatter()
void Map.TryShatter (Point pos, int ele, int power) inline
Definition at line 1172 of file Map.cs.
    {
        Element element = Element.Create(ele, 0);
        List<Card> list = new List<Card>();
        Map.<>c__DisplayClass101_0 CS$<>8__locals1;
        CS$<>8__locals1.fire = (ele == 910);
        bool fire = CS$<>8__locals1.fire;
        List<Card> list2 = pos.ListCards(false);
        if (CS$<>8__locals1.fire && (pos.cell.IsSnowTile || pos.cell.IsTopWater))
        {
            return;
        }
        foreach (Card card in list2)
        {
            if (card.ResistLvFrom(ele) < 3 && !(card.trait is TraitBlanket) && (EClass.rnd(3) != 0 || Map.<TryShatter>g__CanCook|101_0(card, ref CS$<>8__locals1)) && (!card.IsPCFaction || EClass.rnd(3) != 0))
            {
                if (EClass._zone.IsPCFaction && EClass.Branch.lv >= 3)
                {
                    Card rootCard = card.GetRootCard();
                    if (!rootCard.isChara || rootCard.Chara.IsPCFaction)
                    {
                        if (pos.IsSync)
{
                            Msg.Say("damage_protectCore", card, null, null, null);
                            continue;
                        }
                        continue;
                    }
                }
                if (card.isThing && card.things.Count == 0)
                {
                    list.Add(card);
                }
                else
                {
                    Thing thing;
                    if (ele != 910)
                    {
                        thing = card.things.FindBest<TraitBlanketColdproof>((Thing t) => -t.c_charges);
                    }
                    else
                    {
                        thing = card.things.FindBest<TraitBlanketFireproof>((Thing t) => -t.c_charges);
                    }
                    Thing thing2 = thing;
                    if (thing2 != null)
                    {
                        thing2.ModCharge(-1, false);
                        Card rootCard2 = card.GetRootCard();
                        if (pos.IsSync)
{
                            Msg.Say((card.isChara ? "blanketInv_" : "blanketGround_") + element.source.alias, thing2, card, null, null);
                        }
                        if (thing2.c_charges <= 0)
{
                            thing2.Die(element, null, AttackSource.None);
                            if (rootCard2.IsPCParty)
{
                                ActionMode.Adv.itemLost++;
                            }
                        }
                    }
                    else
                    {
                        foreach (Thing thing3 in card.things.List((Thing a) => a.things.Count == 0, false))
{
                            Card parentCard = thing3.parentCard;
                            if (parentCard == null || (!(parentCard.trait is TraitChestMerchant) && !parentCard.HasEditorTag(EditorTag.PreciousContainer)))
{
                                list.Add(thing3);
                            }
                        }
                    }
                }
            }
        }
        list.Shuffle<Card>();
        int num = 0;
        foreach (Card card2 in list)
        {
            if (card2.trait.CanBeDestroyed && !card2.category.IsChildOf("currency") && !(card2.trait is TraitDoor) && !(card2.trait is TraitFigure) && !(card2.trait is TraitTrainingDummy) && card2.rarity < Rarity.Legendary)
            {
                Card rootCard3 = card2.GetRootCard();
                if (!card2.IsEquipmentOrRanged || (EClass.rnd(4) == 0 && ((!card2.IsRangedWeapon && !card2.Thing.isEquipped) || !rootCard3.IsPCFaction || EClass.rnd(4) == 0)))
                {
                    if (ele != 910)
                    {
                        if (ele == 911)
{
                            if (!card2.category.IsChildOf("drink") && EClass.rnd(5) == 0)
{
                                continue;
                            }
                        }
                    }
                    else
                    {
                        if (card2.isFireproof)
{
                            continue;
                        }
                        if (!card2.category.IsChildOf("book") && EClass.rnd(2) == 0)
{
                            continue;
                        }
                    }
                    if (EClass.rnd(num * num) == 0)
                    {
                        bool flag = Map.<TryShatter>g__CanCook|101_0(card2, ref CS$<>8__locals1);
                        string text = "";
                        if (flag)
{
                            List<SourceThing.Row> list3 = new List<SourceThing.Row>();
                            foreach (RecipeSource recipeSource in RecipeManager.list)
{
                                SourceThing.Row row = recipeSource.row as SourceThing.Row;
                                if (row != null && !row.isOrigin && !row.components.IsEmpty() && (row.components.Length < 3 || row.components[2].StartsWith('+')) && row.Category.IsChildOf("meal"))
{
                                    if (!row.factory.IsEmpty())
{
                                        string a2 = row.factory[0];
                                        if (a2 == "chopper" || a2 == "mixer" || a2 == "camppot" || a2 == "cauldron")
{
                                            continue;
                                        }
                                    }
                                    if (row.components[0] == card2.id || row.components[0] == card2.sourceCard._origin)
{
                                        list3.Add(row);
                                    }
                                }
                            }
                            if (list3.Count > 0)
{
                                text = list3.RandomItem<SourceThing.Row>().id;
                            }
                        }
                        if (flag && !text.IsEmpty())
{
                            card2.GetRoot();
                            Thing thing4 = card2.Split(1);
                            List<Thing> list4 = new List<Thing>();
                            list4.Add(thing4);
                            Thing thing5 = ThingGen.Create(text, -1, -1);
                            CraftUtil.MakeDish(thing5, list4, 999, null);
                            thing5.elements.ModBase(2, EClass.curve(power / 10, 50, 10, 75));
                            if (pos.IsSync)
{
                                Msg.Say((rootCard3 == card2) ? "cook_groundItem" : "cook_invItem", thing4, rootCard3, thing5.Name, null);
                            }
                            if (rootCard3 == card2)
{
                                EClass._zone.AddCard(thing5, card2.pos);
                            }
                            else if (rootCard3.isChara)
{
                                rootCard3.Chara.Pick(thing5, false, true);
                            }
                            else
{
                                rootCard3.AddThing(thing5, true, -1, -1);
                            }
                            thing4.Destroy();
                        }
                        else
{
                            int num2 = EClass.rnd(card2.Num) / 2 + 1;
                            if (card2.Num > num2)
{
                                Thing thing6 = card2.Split(num2);
                                if (pos.IsSync)
{
                                    Msg.Say((rootCard3 == card2) ? "damage_groundItem" : "damage_invItem", thing6, rootCard3, null, null);
                                }
                                thing6.Destroy();
                                if (rootCard3.IsPCFaction)
{
                                    WidgetPopText.Say("popDestroy".lang(thing6.Name, rootCard3.Name, null, null, null), FontColor.Default, null);
                                }
                            }
                            else
{
                                card2.Die(element, null, AttackSource.None);
                                if (rootCard3.IsPCFaction)
{
                                    WidgetPopText.Say("popDestroy".lang(card2.Name, rootCard3.Name, null, null, null), FontColor.Default, null);
                                }
                            }
                        }
                        if (rootCard3.IsPCParty)
{
                            ActionMode.Adv.itemLost++;
                        }
                        num++;
                    }
                }
            }
        }
        this._ValidateInstalled(pos.x, pos.z);
    }
References CardRow._origin, _ValidateInstalled(), EClass._zone, Card.Add(), Zone.AddCard(), Card.AddThing(), ActionMode.Adv, EClass.Branch, Card.c_charges, Trait.CanBeDestroyed, Card.category, RenderRow.Category, Point.cell, Card.Chara, RenderRow.components, Element.Create(), ThingGen.Create(), EClass.curve(), Card.Destroy(), Card.Die(), Card.elements, RenderRow.factory, g__CanCook(), Card.GetRoot(), Card.GetRootCard(), Card.HasEditorTag(), Card.id, Card.isChara, Card.IsEquipmentOrRanged, Thing.isEquipped, Card.isFireproof, CardRow.isOrigin, Card.IsPCFaction, Chara.IsPCFaction, Zone.IsPCFaction, Card.IsPCParty, Cell.IsSnowTile, Card.isThing, Cell.IsTopWater, AM_Adv.itemLost, RecipeManager.list, ThingContainer.List(), Point.ListCards(), FactionBranch.lv, CraftUtil.MakeDish(), ElementContainer.ModBase(), Card.ModCharge(), Card.Name, Card.Num, Card.parentCard, Chara.Pick(), Card.pos, Card.rarity, Card.ResistLvFrom(), EClass.rnd(), Msg.Say(), WidgetPopText.Say(), Card.sourceCard, Card.Split(), text, Card.Thing, Card.things, Card.trait, and TryShatter().
Referenced by ActEffect.DamageEle(), and TryShatter().
TrySmoothPick() [1/2]
void Map.TrySmoothPick (Cell cell, Thing t, Chara c) inline
Definition at line 1781 of file Map.cs.
    {
        this.TrySmoothPick(cell.GetPoint(), t, c);
    }
References Cell.GetPoint().
Referenced by Card.EjectSockets(), ZonePreEnterBoutWin.Execute(), DramaOutcome.get_scratch(), TaskHarvest.HarvestThing(), TaskMine.OnProgressComplete(), TraitSwitch.TryDisarmTrap(), and GrowSystem.TryPick().
TrySmoothPick() [2/2]
void Map.TrySmoothPick (Point p, Thing t, Chara c) inline
Definition at line 1786 of file Map.cs.
    {
        if (c != null && c.IsAgent)
        {
            EClass.pc.PickOrDrop(p, t, true);
            return;
        }
        if (c != null && (c.pos.Equals(p) || EClass.core.config.game.smoothPick || EClass._zone.IsRegion))
        {
            c.PickOrDrop(p, t, true);
            return;
        }
        EClass._zone.AddCard(t, p);
    }
References EClass._zone, Zone.AddCard(), EClass.core, Point.Equals(), Card.IsAgent, Spatial.IsRegion, EClass.pc, Chara.PickOrDrop(), and Card.pos.
UpdateMetaData()
static void Map.UpdateMetaData (string pathZip, PartialMap partial = null) inline static
Definition at line 719 of file Map.cs.
    {
        IO.CreateTempDirectory(null);
        ZipFile zipFile = ZipFile.Read(pathZip);
        zipFile.ExtractExistingFile = ExtractExistingFileAction.OverwriteSilently;
        zipFile.ExtractAll(IO.TempPath);
        zipFile.Dispose();
        EClass._map.ExportMetaData(IO.TempPath + "/", Path.GetFileNameWithoutExtension(pathZip), partial);
        ZipFile zipFile2;
        zipFile = (zipFile2 = new ZipFile());
        try
        {
            zipFile.ExtractExistingFile = ExtractExistingFileAction.OverwriteSilently;
            zipFile.AddDirectory(IO.TempPath);
            zipFile.Save(pathZip);
            zipFile.Dispose();
        }
        finally
        {
            if (zipFile2 != null)
            {
                ((IDisposable)zipFile2).Dispose();
            }
        }
        IO.DeleteTempDirectory(null);
    }
References EClass._map, and ExportMetaData().
Referenced by PartialMap.Update().
ValidateInstalled()
void Map.ValidateInstalled (Point p) inline
Definition at line 1977 of file Map.cs.
    {
        this._ValidateInstalled(p.x, p.z);
        this._ValidateInstalled(p.x + 1, p.z);
        this._ValidateInstalled(p.x - 1, p.z);
        this._ValidateInstalled(p.x, p.z + 1);
        this._ValidateInstalled(p.x, p.z - 1);
    }
References Point.x, and Point.z.
ValidateVersion()
void Map.ValidateVersion () inline
Definition at line 656 of file Map.cs.
    {
        this.version = EClass.core.version;
    }
References EClass.core.
Referenced by Load().
Member Data Documentation
_bits
int Map._bits
Definition at line 2827 of file Map.cs.
Referenced by OnDeserialized().
_plDay
List<int> Map._plDay = new List<int>()
Definition at line 2860 of file Map.cs.
Referenced by LayerEditPlaylist.Activate(), Zone.Generate(), and LayerEditPlaylist.OnKill().
_plNight
List<int> Map._plNight = new List<int>()
Definition at line 2863 of file Map.cs.
Referenced by LayerEditPlaylist.Activate(), and LayerEditPlaylist.OnKill().
_things
List<Thing> Map._things = new List<Thing>() private
Definition at line 2909 of file Map.cs.
backerObjs
Dictionary<int, int> Map.backerObjs = new Dictionary<int, int>()
Definition at line 2872 of file Map.cs.
Referenced by Zone.Activate(), Cell.GetObjName(), ActionMode.RefreshTexts(), BackerContentInspector.ContentObj.Remove(), and SetObj().
biomes
BiomeProfile [,] Map.biomes
Definition at line 2897 of file Map.cs.
bits
BitArray32 Map.bits
Definition at line 2877 of file Map.cs.
Referenced by OnSerializing().
bounds
MapBounds Map.bounds = new MapBounds()
Definition at line 2857 of file Map.cs.
Referenced by UIMapPreview._RefreshPoint(), AddBackerTree(), ZoneUtil.AddBandits(), ZoneUtil.AddMerchant(), QuestVernis.CanUpdateOnTalk(), Zone.ClaimZone(), Point.Clamp(), GenBounds.Create(), FactionBranch.DailyOutcome(), BaseTileMap.DrawTile(), BaseGameScreen.FocusPC(), FactionBranch.g__Add(), Zone.Generate(), HomeResourceNature.GetDestValue(), Region.GetRandomPoint(), Zone.GetRandomVisitPos(), Zone.GetSoilCost(), Zone.GetSpawnPos(), QuestVernis.GetTextProgress(), AM_MoveInstalled.HitTest(), TaskWater.ListPoints(), Load(), Player.OnExitBorder(), Zone_DungeonPuppy.OnGenerateMap(), Zone_TestRoom.OnGenerateMap(), AIWork_Clean.OnPerformWork(), AM_Cinema.OnUpdateInput(), ZoneEventMusic.OnVisit(), Zone_Dungeon.PlaceRail(), ActEffect.Proc(), Zone.RainWater(), Cell.Refresh(), AIWork_Chore.SetDestPos(), UIMapPreview.SetMap(), SetZone(), Shift(), ZoneEventQuest.Spawn(), ZoneEventQuest.SpawnBoss(), Zone.TryAddThingInSpot< T >(), Zone.TryGenerateOre(), AI_Goto.TryGoTo(), and Zone.TrySpawnFollower().
cellEffects
Dictionary<int, CellEffect> Map.cellEffects = new Dictionary<int, CellEffect>()
Definition at line 2869 of file Map.cs.
Referenced by Load(), and Save().
cells
Cell [,] Map.cells
Definition at line 2887 of file Map.cs.
Referenced by PartialMap._Load(), Zone.Activate(), PartialMap.Apply(), Burn(), Chara.CanInteractTo(), Chara.CanMoveTo(), Crawler.Crawl(), CreateNew(), BaseTileMap.DrawRoof(), BaseTileMap.DrawTile(), TileMapElona.DrawTile(), MapBounds.ForeachCell(), GetCell(), Los.IsBlocked(), GenBounds.IsEmpty(), GenBounds.ListEmptyPoint(), Load(), ModFire(), MapGen.ModifyHeight(), ModLiquid(), MapGen.OnGenerateTerrain(), MapGenRegion.OnGenerateTerrain(), Room.Refresh(), Reset(), Resize(), RecipeUpdater.RunRecipe(), PartialMap.Save(), Save(), Lot.SetBaseRoom(), SetBlock(), GenBounds.SetBlock(), SetBlockDir(), SetBridge(), SetEffect(), SetFloor(), GenBounds.SetFloor(), SetLiquid(), UIMapPreview.SetMap(), SetObj(), SetReference(), SetRoofBlock(), SetSeen(), Fov.SetVisible(), Shift(), LayerCraftFloat.ShowContextMenu(), Fov.TraceLine(), TryAddRoom(), and TryRemoveRoom().
charas
List<Chara> Map.charas = new List<Chara>()
Definition at line 2883 of file Map.cs.
Referenced by Zone.Activate(), ActionMode.Activate(), SerializedCards.Add(), Zone.AddGlobalCharasOnActivate(), ZoneEventQuest.AggroEnemy(), Zone.ApplyBackerPet(), Chara.CallHelp(), TraitTrolley.CanActivate(), QuestDefense.CanUpdateOnTalk(), ElementContainerFaction.CheckDirty(), AM_MoveInstalled.CheckEnemyNearBy(), FactionBranch.CountGuests(), Zone.CountMinions(), FactionBranch.CountWealthyGuests(), AI_Torture.CreateProgress(), LayerPeople.CreateSelectEmbarkMembers(), Card.DamageHP(), Chara.Die(), Chara.FindNearestNewEnemy(), Chara.FindNewEnemy(), GameUpdater.SensorUpdater.FixedUpdate(), GameUpdater.CharaUpdater.FixedUpdate(), GameUpdater.ConditionUpdater.FixedUpdate(), Zone_WindRest.g__TryRevive(), RefChara.GetAndCache(), GoalSiege.GetDestCard(), DramaCustomSequence.GetListGuide(), TaskCullLife.GetTarget(), QuestManager.HasFarAwayEscort(), TraitShackle.IsRestraining(), Point.ListCharasInRadius(), Region.ListMobs(), Chara.MoveZone(), Zone_Casino.OnActivate(), TraitTrap.OnActivateTrap(), AI_Torture.OnCancelOrSuccess(), OnCardAddedToZone(), OnCardRemovedFromZone(), NotificationBattle.OnClick(), NotificationGuest.OnClick(), AM_EditMarker.OnDeactivate(), OnDeactivate(), QuestDeliver.OnEnterZone(), ZoneEventSiege.OnFirstTick(), Zone.OnGenerateMap(), Zone_CursedManor.OnGenerateMap(), Zone_RandomDungeon.OnGenerateMap(), Zone_Void.OnGenerateMap(), Zone_SubTown.OnGenerateRooms(), ZoneInstanceRandomQuest.OnLeaveZone(), BaseListPeople.OnList(), ListPeopleBed.OnList(), WidgetNotice.OnRefresh(), AM_Adv.OnRenderTile(), Zone.OnVisit(), Card.PurgeDuplicateArtifact(), Zone.RefreshCriminal(), RefreshFOVAll(), WidgetMinimap.RefreshMarkers(), LayerQuestBoard.RefreshQuest(), ActionMode.RefreshTexts(), CoreDebug.RegenerateNames(), Chara.ReleaseMinion(), Chara.RequestProtection(), ResetEditorPos(), Zone.ResetHostility(), Resize(), SerializedCards.Restore(), AI_Fuck.Run(), AI_Idle.Run(), AI_Offer.Run(), Save(), WidgetSearch.Search(), ZoneInspector.SetAllPlayerCreation(), Shift(), Zone.Simulate(), ConSleep.SuccubusSleep(), ConSleep.SuccubusVisit(), ContentRanking.SwitchRanking(), Msg.TalkMaid(), Player.TargetRanged(), Card.Teleport(), CoreDebug.TestSpawn(), Chara.Tick(), ConChampagne.Tick(), ThingGen.TryLickChest(), GameUpdater.Update(), CoreDebug.UpdateInput(), and ElementContainerCard.ValueBonus().
compression
IO.Compression Map.compression
Definition at line 2830 of file Map.cs.
Referenced by Load(), and TryLoadFile().
config
MapConfig Map.config = new MapConfig()
Definition at line 2842 of file Map.cs.
Referenced by LiquidProfile.ApplyColor(), Scene.ApplyZoneConfig(), BaseTileMap.Draw(), TileMapElona.Draw(), BaseTileMap.DrawTile(), LiquidProfile.g__Set(), BaseMapGen.Generate(), Zone.GetSpawnPos(), GameScreen.OnActivate(), WidgetSceneCustomizer.OnActivate(), WidgetSceneCustomizer.OnClickSave(), BaseGameScreen.RefreshAll(), Scene.RefreshBG(), WidgetSceneCustomizer.RefreshColor(), BaseGameScreen.RefreshGrading(), ZoneInspector.RefreshScreen(), BaseGameScreen.RefreshSky(), CoreConfig.RefreshUIBrightness(), BaseGameScreen.RefreshWeather(), GameScreenElona.RefreshWeather(), SetZone(), WidgetSceneCustomizer.ShowPicker(), TraitMapBoard.TrySetAct(), GameUpdater.Update100ms(), and Scene.UpdateTimeRatio().
custom
CustomData Map.custom
Definition at line 2845 of file Map.cs.
Referenced by ExportMetaData(), LayerUploader.OnInit(), and LayerUploader.SaveID().
deadCharas
List<Chara> Map.deadCharas = new List<Chara>()
Definition at line 2851 of file Map.cs.
Referenced by Zone.Activate(), SerializedCards.Add(), Chara.Die(), ZonePreEnterOnCompleteQuestInstance.Execute(), Chara.MakeAlly(), QuestDeliver.OnEnterZone(), SerializedCards.Restore(), Zone.Revive(), ActThrow.Throw(), and CoreDebug.UpdateInput().
effectManager
CellEffectManager Map.effectManager = new CellEffectManager()
Definition at line 2891 of file Map.cs.
Referenced by Load(), and ModFire().
flood
FloodSpiller Map.flood = new FloodSpiller()
Definition at line 2895 of file Map.cs.
Referenced by TryAddRoom().
footmarks
List<Footmark> Map.footmarks = new List<Footmark>()
Definition at line 2901 of file Map.cs.
Referenced by GameDate.AdvanceMin().
fowProfile
FowProfile Map.fowProfile
Definition at line 2903 of file Map.cs.
Referenced by BaseGameScreen.UpdateShaders().
gatherCounts
Dictionary<int, int> Map.gatherCounts = new Dictionary<int, int>()
Definition at line 2866 of file Map.cs.
isDirtySunMap
bool Map.isDirtySunMap static
Definition at line 2821 of file Map.cs.
Referenced by RefreshSunMap().
plants
Dictionary<int, PlantData> Map.plants = new Dictionary<int, PlantData>()
Definition at line 2875 of file Map.cs.
Referenced by SetObj().
plDay
Playlist Map.plDay
Definition at line 2879 of file Map.cs.
Referenced by TraitTape.OnCreate(), LayerEditPlaylist.OnKill(), and GoalCombat.Run().
plNight
Playlist Map.plNight
Definition at line 2881 of file Map.cs.
poiMap
POIMap Map.poiMap
Definition at line 2899 of file Map.cs.
Referenced by MapGen.OnGenerateTerrain(), MapGenDungen.OnGenerateTerrain(), MapGenRegion.OnGenerateTerrain(), BaseMapGen.SetSize(), and Zone.SpawnAltar().
pointAnimes
List<TransAnime> Map.pointAnimes = new List<TransAnime>()
Definition at line 2885 of file Map.cs.
Referenced by Point.Animate(), BaseGameScreen.Draw(), and WidgetDebug.UpdateText().
props
PropsManager Map.props = new PropsManager()
Definition at line 2893 of file Map.cs.
Referenced by Props.Add(), AddCardOnActivate(), Party.AddMemeber(), VirtualDate.BuildSunMap(), AI_Shopping.Buy(), Zone.Deactivate(), Chara.Die(), Chara.FindBed(), FindThing(), g__Find(), AI_Pray.GetAltar(), FactionBranch.GetMailBox(), FactionBranch.GetMailBoxPos(), Zone.GetRandomSpot< T >(), Zone.GetSpawnPos(), Chara.IsInSpot< T >(), QuestDeliver.ListDestThing(), Zone_Nymelle.OnBeforeSimulate(), OnCardAddedToZone(), PutAway(), DramaOutcome.PutOutFire(), RefreshSunMap(), Props.Remove(), FactionBranch.RemoveMemeber(), Card.RemoveThing(), AI_Deconstruct.Run(), AI_Idle.Run(), GoalTask.Run(), WidgetSearch.Search(), Card.SetDeconstruct(), Card.SetPlaceState(), MeetingManager.SetRoom(), Card.SetSale(), SetZone(), Zone.TryAddThingInSharedContainer(), Zone.TryAddThingInSpot< T >(), Chara.TryAssignBed(), Zone.TryGetThingFromSharedContainer(), Chara.TryPutSharedItems(), AI_Shopping.TryShop(), Chara.TryTakeSharedItems(), FactionBranch.TryTrash(), and WidgetDebug.UpdateText().
revealed
bool Map.revealed
Definition at line 2905 of file Map.cs.
Referenced by RevealAll().
roomHash
HashSet<int> Map.roomHash = new HashSet<int>() private
Definition at line 2907 of file Map.cs.
Referenced by OnSetBlockOrDoor(), and TryAddRoom().
rooms
RoomManager Map.rooms = new RoomManager()
Definition at line 2836 of file Map.cs.
Referenced by Zone.Activate(), Lot.AddConnectedRooms(), Area.Create(), BaseTileMap.Draw(), GoalWork.FindWork(), GameUpdater.AreaUpdater.FixedUpdate(), RefArea.Get(), AI_Idle.GetRandomAssignedRoom(), Zone.GetRandomVisitPos(), AM_CreateArea.HitTest(), AM_ExpandArea.HitTest(), BaseArea.ListInteractions(), Chara.MoveZone(), OnLoad(), Room.OnLoad(), AM_CreateArea.OnProcessTiles(), AM_EditArea.OnProcessTiles(), InspectGroupArea.OnSetActions(), Zone.OnVisit(), LayerHome.RefreshAreas(), ReloadRoom(), Lot.SetBaseRoom(), AIWork_Chore.SetDestPos(), MeetingManager.SetRoom(), TryAddRoom(), GoalTask.TryAssignAreaTask(), TryRemoveRoom(), TraitRoomPlate.TrySetAct(), and GoalWork.ValidateHobby().
seed
int Map.seed
Definition at line 2824 of file Map.cs.
Referenced by Zone.Activate(), MapGen.Output(), and WidgetDebug.UpdateText().
serializedCharas
List<Chara> Map.serializedCharas = new List<Chara>()
Definition at line 2848 of file Map.cs.
Referenced by Zone.Activate(), SerializedCards.Restore(), and Save().
sunMap
HashSet<int> Map.sunMap = new HashSet<int>() static
Definition at line 2819 of file Map.cs.
Referenced by BaseTileMap.DrawTile(), and RefreshSunMap().
tasks
TaskManager Map.tasks = new TaskManager()
Definition at line 2839 of file Map.cs.
Referenced by BuildMenu.OnActivate(), AM_Designation< T >.OnBeforeProcessTiles(), OnLoad(), AM_Designation< T >.OnProcessTiles(), InspectGroupBlock.OnSetActions(), InspectGroupObj.OnSetActions(), and AM_MoveInstalled.SetTarget().
things
List<Thing> Map.things = new List<Thing>()
Definition at line 2854 of file Map.cs.
Referenced by Zone.Activate(), ActionMode.Activate(), GameDate.AdvanceMonth(), PartialMap.Apply(), FactionBranch.CalcInnIncome(), QuestSharedContainer.CanUpdateOnTalk(), QuestShippingChest.CanUpdateOnTalk(), Zone.ClaimZone(), FactionBranch.DailyOutcome(), Zone.Deactivate(), GameUpdater.ThingUpdater.FixedUpdate(), CoreDebug.GetDebugContainer(), Zone.GetElectricity(), DramaCustomSequence.GetListGuide(), CoreDebug.GetOrCreateDebugContainer(), Zone.GetSpawnPos(), AI_Haul.GetThingToClean(), Zone.GrowPlants(), Scene.Init(), Point.IsInSpot< T >(), HomeResourceWorth.ListHeirloom(), Load(), Zone_Tent.OnBeforeDeactivate(), OnCardAddedToZone(), OnCardRemovedFromZone(), AM_EditMarker.OnDeactivate(), OnDeactivate(), Zone_CursedManorDungeon.OnGenerateMap(), Zone_WindRest.OnGenerateMap(), MapGenDungen.OnGenerateTerrain(), Zone.OnKillGame(), Zone.OnSimulateHour(), ZoneEventHarvest.OnVisit(), ZoneEventMusic.OnVisit(), Scene.RebuildActorEx(), BranchMap.Refresh(), Zone.RefreshElectricity(), RefreshFOVAll(), ActionMode.RefreshTexts(), ReloadRoom(), TraitDaggerGrave.RemainingSword(), ResetEditorPos(), Resize(), SerializedCards.Restore(), TaskDump.Run(), PartialMap.Save(), Save(), TraitDetector.Search(), WidgetSearch.Search(), ZoneInspector.SetAllPlayerCreation(), Shift(), Zone.Simulate(), CoreDebug.Test_Grow(), Zone.TryGetRestock< T >(), Zone.TryListThingsInSpot< T >(), AI_Shopping.TryRestock(), TraitFactionBoard.TrySetAct(), and TraitTeleporter.TryTeleport().
version
global.Version Map.version
Definition at line 2833 of file Map.cs.
Referenced by ExportMetaData().
zone
Zone Map.zone
Definition at line 2889 of file Map.cs.
Referenced by AddCardOnActivate(), OnDeactivate(), and WidgetMinimap.UpdateMap().
Property Documentation
Cards
IEnumerable<Card> Map.Cards get
Definition at line 83 of file Map.cs.
    {
        get
        {
            return this.things.Concat(this.charas);
        }
    }
Referenced by Zone.Activate(), MapSubset.OnSave(), and ActionMode.RefreshTexts().
Installed
PropsInstalled Map.Installed get
Definition at line 35 of file Map.cs.
    {
        get
        {
            return this.props.installed;
        }
    }
Referenced by QuestCrafter.CanUpdateOnTalk(), FactionBranch.CountPasture(), FactionBranch.DailyOutcome(), AIAct.DoGoto< T >(), AIAct.DoGotoSpot< T >(), FindThing(), AI_Grab< T >.GetTarget(), FactionBranch.Recruit(), UIRecipeInfo.Refresh(), LayerHome.RefreshSpots(), AI_Bladder.Run(), AI_Cook.Run(), AI_GotoHearth.Run(), AI_Idle.Run(), AI_LeaveMap.Run(), AI_Offer.Run(), GoalSpot.Run(), HitSummary.SetRecipe(), and CoreDebug.ValidateData().
isBreakerDown
bool Map.isBreakerDown get set
Definition at line 15 of file Map.cs.
    {
        get
        {
            return this.bits[0];
        }
        set
        {
            this.bits[0] = value;
        }
    }
Referenced by TraitLeverBreaker.OnToggle().
isGenerated
bool Map.isGenerated get
Definition at line 59 of file Map.cs.
    {
        get
        {
            return this.Size != 0;
        }
    }
Referenced by MapGen.OnGenerateTerrain().
IsIndoor
bool Map.IsIndoor get
Definition at line 67 of file Map.cs.
    {
        get
        {
            return this.config.indoor;
        }
    }
Referenced by GrowSystem.CanGrow(), BaseTileMap.Draw(), CardRenderer.Draw(), Card.GetLightRadius(), Card.GetSightRadius(), TraitGenerator.OnSimulateHour(), TraitScrollMapTreasure.OnUse(), Zone.RainWater(), BaseGameScreen.RefreshGrading(), BaseGameScreen.RefreshScreenSize(), Weather.RefreshWeather(), Weather.SetCondition(), Chara.TickConditions(), TryAddRoom(), Trait.TryToggle(), and GameUpdater.Update100ms().
Roaming
PropsRoaming Map.Roaming get
Definition at line 43 of file Map.cs.
    {
        get
        {
            return this.props.roaming;
        }
    }
Referenced by GameUpdater.SurfaceUpdater.FixedUpdate(), Props.GetNumStockedAndRoaming(), CoreDebug.UpdateInput(), and CoreDebug.ValidateData().
sizeModifier
float Map.sizeModifier get
Definition at line 51 of file Map.cs.
    {
        get
        {
            return 1f / (16384f / (float)this.SizeXZ);
        }
    }
Referenced by Crawler.Crawl().
SizeXZ
int Map.SizeXZ get
Definition at line 75 of file Map.cs.
    {
        get
        {
            return this.Size * this.Size;
        }
    }
Referenced by BaseTileMap.Draw(), TileMapElona.Draw(), and HomeResourceWorth.ListHeirloom().
Stocked
PropsStocked Map.Stocked get
Definition at line 27 of file Map.cs.
    {
        get
        {
            return this.props.stocked;
        }
    }
Referenced by TaskBuild._CanPerformTask(), WidgetStockTracker._Refresh(), BuildMenu._Search(), Props.Add(), Card.AddThing(), FactionBranch.CountPasture(), FactionBranch.DailyOutcome(), QuestTrackCraft.GetDetail(), Props.GetNumStockedAndRoaming(), AI_Grab< T >.GetTarget(), Recipe.IsCraftable(), DropdownGrid.ListIngredients(), LayerResource.OnInit(), NotificationStockpile.OnRefresh(), UIDragGridIngredients.Refresh(), LayerResource.RefreshCategory(), BuildMenu.RefreshCategory(), UIRecipeInfo.RefreshList(), Recipe.Ingredient.RefreshThing(), ButtonResourceTrack.SetCat(), ButtonResourceTrack.SetProp(), LayerResource.ShowThings(), DropdownGrid.TrySelect(), CoreDebug.ValidateData(), and ButtonGrid.WriteReqMat().
The documentation for this class was generated from the following file:
Elin/Map.cs