Elin Decompiled Documentation: Crawler Class Reference
Crawler Class Reference
Classes
class Member
class Result
Public Types
enum MoveType { Surface , Block }
enum StartType { Surface , Block }
Public Member Functions
bool CrawlUntil (Map map, Func< Point > onStart, int tries, Func< Crawler.Result, bool > canComplete, Action onFail=null)
void Crawl (Map map)
Crawler.Result Crawl (Map map, Point _start, Action< Point > onNewVisit=null)
Static Public Member Functions
static Crawler Create (string id)
Static Public Member Functions inherited from EScriptable
static int rnd (int a)
Public Attributes
int life
int member
int radius
int repeat
bool stickToStartBiome
bool skipBorder
Crawler.StartType startType
Crawler.MoveType moveType
int Size
List< Crawler.Member > members = new List<Crawler.Member>()
Static Public Attributes
static int[,] mapping = new int[0, 0]
static int sync
Detailed Description
Definition at line 5 of file Crawler.cs.
Member Enumeration Documentation
MoveType
enum Crawler.MoveType
Enumerator
Surface
Block
Definition at line 196 of file Crawler.cs.
    {
        Surface,
        Block
    }
StartType
enum Crawler.StartType
Enumerator
Surface
Block
Definition at line 202 of file Crawler.cs.
    {
        Surface,
        Block
    }
Member Function Documentation
Crawl() [1/2]
void Crawler.Crawl (Map map) inline
Definition at line 59 of file Crawler.cs.
    {
        int num = 0;
        while ((float)num < map.sizeModifier * (float)this.repeat + 1f)
        {
            this.Crawl(map, map.GetRandomSurface(false, true, false), delegate(Point p)
            {
                p.cell.biome.Populate(p, false);
            });
            num++;
        }
    }
References Cell.biome, Point.cell, Crawl(), MapBounds.GetRandomSurface(), BiomeProfile.Populate(), and Map.sizeModifier.
Referenced by Crawl(), and CrawlUntil().
Crawl() [2/2]
Crawler.Result Crawler.Crawl (Map map, Point _start, Action< Point > onNewVisit = null) inline
Definition at line 72 of file Crawler.cs.
    {
        if (this.members.Count == 0)
        {
            for (int i = 0; i < this.member; i++)
            {
                this.members.Add(new Crawler.Member());
            }
        }
        Point point = _start.Copy();
        point.Clamp(false);
        Crawler.Result result = new Crawler.Result();
        BiomeProfile biome = point.cell.biome;
        Crawler.sync++;
        this.Size = map.Size;
        int num = this.skipBorder ? 2 : 0;
        int num2 = this.skipBorder ? (this.Size - 2) : this.Size;
        if (Crawler.mapping.Length != this.Size)
        {
            Crawler.mapping = new int[map.Size, map.Size];
        }
        foreach (Crawler.Member member in this.members)
        {
            member.pos.Set(point);
            member.life = this.life;
        }
        for (int j = 0; j < this.life; j++)
        {
            for (int k = 0; k < this.members.Count; k++)
            {
                Crawler.Member member2 = this.members[k];
                int num3 = EScriptable.rnd(3) - 1;
                int num4 = EScriptable.rnd(3) - 1;
                int num5 = member2.pos.x + num3;
                int num6 = member2.pos.z + num4;
                if (point.Distance(num5, num6) <= this.radius && num5 >= num && num6 >= num && num5 < num2 && num6 < num2)
                {
                    Cell cell = map.cells[num5, num6];
                    if (!this.stickToStartBiome || !(cell.biome != biome))
                    {
                        Crawler.MoveType moveType = this.moveType;
                        if (moveType != Crawler.MoveType.Surface)
{
                            if (moveType == Crawler.MoveType.Block)
{
                                if (cell._block == 0 || !cell.sourceBlock.tileType.IsFullBlock || cell.Installed != null)
{
                                    goto IL_269;
                                }
                            }
                        }
                        else
{
                            if (cell._block != 0)
{
                                goto IL_269;
                            }
                            if (cell.IsTopWater)
{
                                goto IL_269;
                            }
                        }
                        member2.pos.Set(num5, num6);
                        if (Crawler.mapping[num5, num6] != Crawler.sync)
{
                            Crawler.mapping[num5, num6] = Crawler.sync;
                            Point point2 = member2.pos.Copy();
                            result.points.Add(point2);
                            if (onNewVisit != null)
{
                                onNewVisit(point2);
                            }
                        }
                    }
                }
                IL_269:;
            }
        }
        return result;
    }
References Cell._block, Cell.biome, Point.cell, Map.cells, Point.Clamp(), Point.Copy(), Point.Distance(), Cell.Installed, Cell.IsTopWater, life, mapping, member, members, moveType, Crawler.Result.points, Crawler.Member.pos, EScriptable.rnd(), Point.Set(), Size, MapBounds.Size, Cell.sourceBlock, stickToStartBiome, and sync.
CrawlUntil()
bool Crawler.CrawlUntil (Map map, Func< Point > onStart, int tries, Func< Crawler::Result, bool > canComplete, Action onFail = null) inline
Definition at line 7 of file Crawler.cs.
    {
        if (tries <= 0)
        {
            return false;
        }
        for (int i = 0; i < tries; i++)
        {
            bool flag = false;
            for (int j = 0; j < 100; j++)
            {
                Point point = onStart();
                Crawler.StartType startType = this.startType;
                if (startType != Crawler.StartType.Surface)
                {
                    if (startType == Crawler.StartType.Block)
                    {
                        if (point.sourceBlock.tileType.IsFullBlock && point.Installed == null)
{
                            flag = true;
                        }
                    }
                }
                else if (!point.HasBlock)
                {
                    flag = true;
                }
            }
            if (flag)
            {
                Crawler.Result arg = this.Crawl(map, onStart(), null);
                if (canComplete(arg))
                {
                    if (i > 0)
                    {
                        Debug.Log("CrawlUntil Complete:" + i.ToString());
                    }
                    return true;
                }
            }
        }
        if (onFail != null)
        {
            Debug.Log("CrawlUntil Fail" + tries.ToString());
            if (onFail != null)
            {
                onFail();
            }
        }
        return false;
    }
References Crawl(), Point.HasBlock, Point.Installed, Point.sourceBlock, and startType.
Referenced by MapGen.Populate(), and Zone.TryGenerateOre().
Create()
static Crawler Crawler.Create (string id) inline static
Definition at line 153 of file Crawler.cs.
    {
        return ResourceCache.Load<Crawler>("World/Map/Crawler/crawler " + id);
    }
Referenced by MapGen.Populate(), and Zone.TryGenerateOre().
Member Data Documentation
life
int Crawler.life
Definition at line 162 of file Crawler.cs.
Referenced by Crawl().
mapping
int [,] Crawler.mapping = new int[0, 0] static
Definition at line 158 of file Crawler.cs.
Referenced by Crawl().
member
int Crawler.member
Definition at line 164 of file Crawler.cs.
Referenced by Crawl().
members
List<Crawler.Member> Crawler.members = new List<Crawler.Member>()
Definition at line 182 of file Crawler.cs.
Referenced by Crawl().
moveType
Crawler.MoveType Crawler.moveType
Definition at line 176 of file Crawler.cs.
Referenced by Crawl().
radius
int Crawler.radius
Definition at line 166 of file Crawler.cs.
repeat
int Crawler.repeat
Definition at line 168 of file Crawler.cs.
Size
int Crawler.Size
Definition at line 179 of file Crawler.cs.
Referenced by Crawl().
skipBorder
bool Crawler.skipBorder
Definition at line 172 of file Crawler.cs.
startType
Crawler.StartType Crawler.startType
Definition at line 174 of file Crawler.cs.
Referenced by CrawlUntil().
stickToStartBiome
bool Crawler.stickToStartBiome
Definition at line 170 of file Crawler.cs.
Referenced by Crawl().
sync
int Crawler.sync static
Definition at line 160 of file Crawler.cs.
Referenced by Crawl().
The documentation for this class was generated from the following file:
Elin/Crawler.cs