Elin Decompiled Documentation: LayerConfig Class Reference
LayerConfig Class Reference
Public Member Functions
override string GetTextHeader (Window window)
override void OnBeforeAddLayer ()
override void OnInit ()
override void OnSwitchContent (Window window)
void ValidateResolution ()
override void OnKill ()
void Refresh ()
void SetFont (SkinManager.FontSaveData data, UIItem item, string lang)
void ApplyFont ()
void SetSlider (Slider slider, float value, Func< float, string > action, bool notify=false)
void SetGroup (UISelectableGroup group, int value, UnityAction< int > action)
Public Member Functions inherited from ELayer
override void OnBeforeAddLayer ()
void InitInspector ()
sealed override void Init ()
override void OnAfterAddLayer ()
void TryShowHelp ()
void AddLayerToUI (string id)
void TryShowHint (string _langHint=null)
void TalkHomeMemeber (string id)
void TalkMaid (string id)
override void OnRightClick ()
Public Member Functions inherited from Layer
virtual string GetTextHeader (Window window)
virtual bool HeaderIsListOf (int id)
virtual void Init ()
virtual void OnInit ()
virtual void OnAfterInit ()
virtual void ApplySkin ()
void ShowScreenLock (string id)
void UpdateInput ()
virtual void OnUpdateInput ()
virtual void OnRightClick ()
virtual bool OnBack ()
virtual void OnChangeLayer ()
virtual void OnCreate ()
void _AddLayer (string id)
Layer AddLayer (string id)
T AddLayer< T > ()
T AddLayer< T > (string id)
T AddLayerDontCloseOthers< T > ()
Layer AddLayerDontCloseOthers (Layer l)
T GetOrAddLayer< T > ()
virtual void OnBeforeAddLayer ()
virtual void OnAfterAddLayer ()
Layer AddLayer (Layer l)
void ToggleLayer (string id)
T ToggleLayer< T > (string id=null)
void WaitAndClose ()
void OnClickClose ()
virtual void Close ()
void CloseLayers ()
void RemoveLayers (bool removeImportant=false)
bool RemoveLayer< T > ()
void RemoveLayer (Layer l)
virtual void OnKill ()
Layer SetOnKill (Action action)
void DisableClose ()
void Delay (float duration=0.05f)
Layer SetDelay (float d)
Layer GetLayer (string id)
T GetLayer< T > (bool fromTop=false)
Layer GetTopLayer ()
void SwitchContent (int idWindow, int i)
virtual void OnSwitchContent (Window window)
Layer SetTitles (string langList, string idHeaderRow=null)
bool IsBlockWidgetClick ()
bool IsHideHud ()
bool IsAllowGeneralInput ()
bool IsUseBlur ()
bool IsPointerOnLayer ()
void ApplySkin ()
Public Attributes
Slider sliderMaster
Slider sliderBGM
Slider sliderSFX
Slider sliderAMB
Slider sliderBrightness
Slider sliderContrast
Slider sliderSaturation
Slider sliderVibrance
Slider sliderScrollSense
Slider sliderScale
Slider sliderSharpen
Slider sliderSharpen2
Slider sliderBlur
UISelectableGroup groupVSync
UISelectableGroup groupLang
UIButton toggleVsync
UIButton toggleFixedResolution
UIButton toggleOpenLastTab
UIButton toggleClosePopupOnMouseLeave
UIButton toggleRightClickClose
UIButton toggleFullscreen
UIButton togglePixelPerfectUI
UIButton toggleBloom
UIButton toggleHDR
UIButton toggleBlur
UIButton toggleAutoscale
UIButton toggleDynamicBrightness
UIButton toggleKuwahara
UIButton toggleBlizzard
UIButton toggleDisableShake
UIButton toggleFirefly
UIButton toggleSecureWidth
UIButton toggleGradientWater
UIButton toggleGodray
UIButton toggleShowFloatButtons
UIButton toggleAllyLight
UIButton toggleBalloon
UIButton toggleFloorEx
UIItem fontUI
UIItem fontChatbox
UIItem fontBalloon
UIItem fontDialog
UIItem fontWidget
UIItem fontNews
UIDropdown ddPostEffect
UIButton buttonReset
Slider sliderUIBrightness
Slider sliderUIContrast
Slider sliderBalloon
LayoutGroup layoutLanguage
UIButton moldLanguage
UIButton buttonApplyScreenSize
InputField inputW
InputField inputH
Public Attributes inherited from Layer
Option option
UnityEvent onKill
Anime animeIn
Anime animeOut
bool closeOthers
bool defaultActionMode = true
Button screenLock
Layer parent
string idLayer
List< Layer > layers = new List<Layer>()
Vector2 lastParentPos
List< Window > windows = new List<Window>()
string langHint
Private Member Functions
void Update ()
Additional Inherited Members
Static Public Member Functions inherited from ELayer
static int rnd (int a)
Static Public Member Functions inherited from Layer
static T Create< T > ()
static T Create< T > (string path)
static Layer Create (string path)
Static Public Attributes inherited from Layer
static int skipInput
static bool closeOnRightClick
static bool rightClicked
static bool cancelKeyDown
static bool ignoreSounds
static Transform blurStopInstance
static string[] searchPath = new string[3] { "Layer", "Layer/Dialog", "Layer/LayerHome" }
Protected Member Functions inherited from ELayer
sealed override void _Close ()
sealed override void Kill ()
Protected Member Functions inherited from Layer
virtual void Awake ()
virtual void _Close ()
virtual void Kill ()
Protected Attributes inherited from Layer
RectTransform _rect
bool isDestroyed
Properties inherited from ELayer
static Core core [get]
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static FactionBranch Branch [get]
static Faction Home [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static CoreConfig config [get]
static GameSetting setting [get]
static ColorProfile Colors [get]
static SourceManager sources [get]
static World world [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
bool IsFloat [get]
virtual string IdHelp [get]
Properties inherited from Layer
Layer TopLayer [get]
string uid [get]
virtual RectTransform rectLayers [get]
virtual bool blockWidgetClick [get]
Detailed Description
Definition at line 8 of file LayerConfig.cs.
Member Function Documentation
ApplyFont()
void LayerConfig.ApplyFont () inline
Definition at line 542 of file LayerConfig.cs.
    {
        ELayer.config.ApplyFont();
        this.RebuildLayout(recursive: true);
    }
References CoreConfig.ApplyFont(), and ELayer.config.
GetTextHeader()
override string LayerConfig.GetTextHeader (Window window) inline virtual
Reimplemented from Layer.
Definition at line 118 of file LayerConfig.cs.
    {
        return "_configOf".lang(base.GetTextHeader(window));
    }
OnBeforeAddLayer()
override void LayerConfig.OnBeforeAddLayer () inline virtual
Reimplemented from ELayer.
Definition at line 123 of file LayerConfig.cs.
    {
        windows[0].setting.tabs[5].disable = !ELayer.core.config.other.showTestOptions;
    }
References Core.config, ELayer.core, CoreConfig.other, CoreConfig.OtherSetting.showTestOptions, and Layer.windows.
OnInit()
override void LayerConfig.OnInit () inline virtual
Reimplemented from Layer.
Definition at line 128 of file LayerConfig.cs.
    {
        inputW.text = ELayer.config.graphic.w.ToString() ?? "";
        inputH.text = ELayer.config.graphic.h.ToString() ?? "";
        ELayer.config.graphic.fullScreen = Screen.fullScreen;
        windows[0].AddBottomSpace();
        buttonReset = windows[0].AddBottomButton("", delegate
        {
            Dialog.YesNo("dialogResetConfigTab".lang(windows[0].CurrentTab.idLang.lang()), delegate
            {
                Close();
                if (windows[0].idTab == 0)
                {
                    CoreConfig.ResetGeneral();
                }
                else if (windows[0].idTab == 1)
                {
                    CoreConfig.ResetGraphics();
                }
                else if (windows[0].idTab == 2)
                {
                    CoreConfig.ResetGame();
                }
                else if (windows[0].idTab == 3)
                {
                    CoreConfig.ResetInput();
                }
                else if (windows[0].idTab == 4)
                {
                    CoreConfig.ResetOther();
                }
                else
                {
                    CoreConfig.ResetTest();
                }
                ELayer.ui.AddLayer<LayerConfig>();
            });
        });
        windows[0].AddBottomButton("resetConfig", delegate
        {
            Dialog.YesNo("dialogResetConfig", delegate
            {
                Close();
                CoreConfig.Reset();
                ELayer.ui.AddLayer<LayerConfig>();
            });
        });
        List<PostEffectProfile> list = (from p in Resources.LoadAll<PostEffectProfile>("Scene/Profile/PostEffect/")
            where !p.disable
            select p).ToList();
        ddPostEffect.SetList(ELayer.config.graphic.idPostProfile, list, (PostEffectProfile a, int b) => a.name, delegate(int a, PostEffectProfile b)
        {
            ELayer.config.graphic.idPostProfile = b.name;
            b.OnChangeProfile();
            sliderSharpen.value = ELayer.config.graphic.sharpen;
            sliderSharpen2.value = ELayer.config.graphic.sharpen2;
            sliderBlur.value = ELayer.config.graphic.blur;
            toggleKuwahara.SetCheck(ELayer.config.graphic.kuwahara);
            ELayer.config.ApplyGrading();
        }, notify: false);
        Refresh();
    }
References buttonReset, ELayer.config, CoreConfig.graphic, CoreConfig.GraphicSetting.h, if(), CoreConfig.ResetGame(), CoreConfig.ResetGraphics(), CoreConfig.ResetInput(), CoreConfig.ResetOther(), CoreConfig.ResetTest(), ELayer.ui, CoreConfig.GraphicSetting.w, Layer.windows, and Dialog.YesNo().
OnKill()
override void LayerConfig.OnKill () inline virtual
Reimplemented from Layer.
Definition at line 216 of file LayerConfig.cs.
    {
        ELayer.core.config.graphic.w = inputW.text.ToInt();
        ELayer.core.config.graphic.h = inputH.text.ToInt();
        ELayer.core.config.Save();
        ELayer.core.config.Apply();
    }
References CoreConfig.Apply(), Core.config, ELayer.core, and CoreConfig.Save().
OnSwitchContent()
override void LayerConfig.OnSwitchContent (Window window) inline virtual
Reimplemented from Layer.
Definition at line 191 of file LayerConfig.cs.
    {
        buttonReset.mainText.SetText("resetConfigTab".lang(windows[0].CurrentTab.idLang.lang()));
        windows[0].rectBottom.RebuildLayout(recursive: true);
        windows[0].CurrentContent.RebuildLayout(recursive: true);
    }
References UIButton.mainText, and UIText.SetText().
Refresh()
void LayerConfig.Refresh () inline
Definition at line 224 of file LayerConfig.cs.
    {
        ELayer.config.ignoreApply = true;
        SetSlider(sliderMaster, ELayer.config.sound.volumeMaster, delegate(float a)
        {
            ELayer.config.sound.volumeMaster = a;
            ELayer.config.ApplyVolume();
            return Lang.Get("MASTER") + "(" + (int)(a * 100f) + "%)";
        });
        SetSlider(sliderBGM, ELayer.config.sound.volumeBGM, delegate(float a)
        {
            ELayer.config.sound.volumeBGM = a;
            ELayer.config.ApplyVolume();
            return Lang.Get("BGM") + "(" + (int)(a * 100f) + "%)";
        });
        SetSlider(sliderSFX, ELayer.config.sound.volumeSFX, delegate(float a)
        {
            ELayer.config.sound.volumeSFX = a;
            ELayer.config.ApplyVolume();
            return Lang.Get("SFX") + "(" + (int)(a * 100f) + "%)";
        });
        SetSlider(sliderAMB, ELayer.config.sound.volumeAMB, delegate(float a)
        {
            ELayer.config.sound.volumeAMB = a;
            ELayer.config.ApplyVolume();
            return Lang.Get("AMB") + "(" + (int)(a * 100f) + "%)";
        });
        SetSlider(sliderBrightness, ELayer.config.graphic.brightness, delegate(float a)
        {
            ELayer.config.graphic.brightness = a;
            ELayer.config.ApplyGrading();
            return Lang.Get("brightness") + "(" + (int)(a * 100f) + "%)";
        });
        SetSlider(sliderContrast, ELayer.config.graphic.contrast, delegate(float a)
        {
            ELayer.config.graphic.contrast = a;
            ELayer.config.ApplyGrading();
            return Lang.Get("contrast") + "(" + (int)(a * 100f) + "%)";
        });
        SetSlider(sliderSaturation, ELayer.config.graphic.saturation, delegate(float a)
        {
            ELayer.config.graphic.saturation = a;
            ELayer.config.ApplyGrading();
            return Lang.Get("saturation") + "(" + (int)(a * 100f) + "%)";
        });
        SetSlider(sliderVibrance, ELayer.config.graphic.vibrance, delegate(float a)
        {
            ELayer.config.graphic.vibrance = a;
            ELayer.config.ApplyGrading();
            return Lang.Get("vibrance") + "(" + (int)(a * 100f) + "%)";
        });
        SetSlider(sliderSharpen, ELayer.config.graphic.sharpen, delegate(float a)
        {
            ELayer.config.graphic.sharpen = (int)a;
            ELayer.config.ApplyGrading();
            return Lang.Get("sharpen") + "(" + (int)a + "%)";
        });
        SetSlider(sliderSharpen2, ELayer.config.graphic.sharpen2, delegate(float a)
        {
            ELayer.config.graphic.sharpen2 = (int)a;
            ELayer.config.ApplyGrading();
            return Lang.Get("sharpen2") + "(" + (int)a + "%)";
        });
        SetSlider(sliderBlur, ELayer.config.graphic.blur, delegate(float a)
        {
            ELayer.config.graphic.blur = (int)a;
            ELayer.config.ApplyGrading();
            return Lang.Get("blur") + "(" + (int)a + "%)";
        });
        SetSlider(sliderScrollSense, ELayer.config.ui.scrollSens, delegate(float a)
        {
            ELayer.config.ui.scrollSens = a;
            UIScrollView.sensitivity = ELayer.config.ui.ScrollSensitivity;
            return Lang.Get("scrollSens") + "(" + (int)(a * 100f) + ")";
        });
        SetSlider(sliderScale, ELayer.config.ui.scale, delegate(float a)
        {
            ELayer.config.ui.scale = (int)a;
            ELayer.config.ApplyScale();
            ELayer.core.OnChangeResolution();
            return Lang.Get("uiScale") + "(" + a * 5f + "%)";
        });
        SetSlider(sliderUIBrightness, ELayer.config.ui.brightness, delegate(float a)
        {
            ELayer.config.ui.brightness = (int)a;
            ELayer.config.ApplyGrading();
            return Lang.Get("uiBrightness") + "(" + a + "%)";
        });
        SetSlider(sliderUIContrast, ELayer.config.ui.contrast, delegate(float a)
        {
            ELayer.config.ui.contrast = (int)a;
            ELayer.config.ApplyGrading();
            return Lang.Get("uiContrast") + "(" + a + "%)";
        });
        SetSlider(sliderBalloon, ELayer.config.ui.outlineAlpha, delegate(float a)
        {
            ELayer.config.ui.outlineAlpha = (int)a;
            ELayer.config.Apply();
            return Lang.Get("outlineAlpha") + "(" + a + "%)";
        });
        SetGroup(groupVSync, ELayer.config.graphic.fps, delegate(int a)
        {
            ELayer.config.graphic.fps = a;
            ELayer.config.Apply();
        });
        if (!moldLanguage)
        {
            moldLanguage = layoutLanguage.CreateMold<UIButton>();
        }
        layoutLanguage.DestroyChildren();
        int value = 0;
        List<LangSetting> list = new List<LangSetting>();
        foreach (LangSetting value2 in MOD.langs.Values)
        {
            Util.Instantiate(moldLanguage, layoutLanguage).mainText.text = value2.name + "(" + value2.name_en + ")";
            if (ELayer.config.lang == value2.id)
            {
                value = list.Count;
            }
            list.Add(value2);
        }
        layoutLanguage.RebuildLayout();
        SetGroup(groupLang, value, delegate(int a)
        {
            if (ELayer.config.lang != list[a].id)
            {
                ELayer.config.lang = list[a].id;
                ELayer.core.SetLang(ELayer.config.lang);
                Close();
                IChangeLanguage[] componentsInChildren = ELayer.ui.GetComponentsInChildren<IChangeLanguage>();
                for (int i = 0; i < componentsInChildren.Length; i++)
                {
                    componentsInChildren[i].OnChangeLanguage();
                }
                ELayer.ui.AddLayer<LayerConfig>();
                Dialog.Ok("dialogChangeLang");
                ELayer.config.Save();
            }
        });
        toggleGradientWater.SetToggle(ELayer.config.graphic.gradientWater, delegate(bool on)
        {
            ELayer.config.graphic.gradientWater = on;
            ELayer.scene.ApplyZoneConfig();
        });
        toggleVsync.SetToggle(ELayer.config.graphic.vsync, delegate(bool on)
        {
            ELayer.config.graphic.vsync = on;
            ELayer.config.Apply();
        });
        toggleAutoscale.SetToggle(ELayer.config.ui.autoscale, delegate(bool on)
        {
            ELayer.config.ui.autoscale = on;
            ELayer.core.OnChangeResolution();
            ELayer.config.ApplyScale();
        });
        toggleOpenLastTab.SetToggle(ELayer.config.ui.openLastTab, delegate(bool on)
        {
            ELayer.config.ui.openLastTab = on;
            ELayer.config.Apply();
        });
        if ((bool)toggleClosePopupOnMouseLeave)
        {
            toggleClosePopupOnMouseLeave.SetToggle(ELayer.config.ui.closePopupOnMouseLeave, delegate(bool on)
            {
                ELayer.config.ui.closePopupOnMouseLeave = on;
                ELayer.config.Apply();
            });
        }
        toggleBalloon.SetToggle(ELayer.config.ui.balloonBG, delegate(bool on)
        {
            ELayer.config.ui.balloonBG = on;
            ELayer.config.Apply();
        });
        toggleRightClickClose.SetToggle(ELayer.config.ui.rightClickClose, delegate(bool on)
        {
            ELayer.config.ui.rightClickClose = on;
            ELayer.config.Apply();
        });
        toggleFullscreen.SetToggle(ELayer.config.graphic.fullScreen, delegate(bool on)
        {
            ELayer.config.graphic.fullScreen = on;
            ELayer.config.Apply();
        });
        togglePixelPerfectUI.SetToggle(ELayer.config.graphic.pixelperfectUI, delegate(bool on)
        {
            ELayer.config.graphic.pixelperfectUI = on;
            ELayer.config.Apply();
        });
        toggleFixedResolution.SetToggle(ELayer.config.graphic.fixedResolution, delegate(bool on)
        {
            ELayer.config.graphic.fixedResolution = on;
            ELayer.config.Apply();
        });
        toggleBloom.SetToggle(ELayer.config.graphic.bloom, delegate(bool on)
        {
            ELayer.config.graphic.bloom = on;
            ELayer.config.Apply();
        });
        toggleHDR.SetToggle(ELayer.config.graphic.hdr, delegate(bool on)
        {
            ELayer.config.graphic.hdr = on;
            ELayer.config.Apply();
        });
        toggleKuwahara.SetToggle(ELayer.config.graphic.kuwahara, delegate(bool on)
        {
            ELayer.config.graphic.kuwahara = on;
            ELayer.config.ApplyGrading();
        });
        toggleDisableShake.SetToggle(ELayer.config.graphic.disableShake, delegate(bool on)
        {
            ELayer.config.graphic.disableShake = on;
        });
        toggleFirefly.SetToggle(ELayer.config.graphic.firefly, delegate(bool on)
        {
            ELayer.config.graphic.firefly = on;
            if (ELayer.core.IsGameStarted)
            {
                ELayer.screen.RefreshSky();
            }
        });
        toggleFloorEx.SetToggle(ELayer.config.graphic.floorEx, delegate(bool on)
        {
            ELayer.config.graphic.floorEx = on;
            if (ELayer.core.IsGameStarted)
            {
                ELayer.screen.RefreshAll();
            }
        });
        toggleGodray.SetToggle(ELayer.config.graphic.godray, delegate(bool on)
        {
            ELayer.config.graphic.godray = on;
            if (ELayer.core.IsGameStarted)
            {
                ELayer.screen.RefreshSky();
            }
        });
        toggleBlizzard.SetToggle(ELayer.config.graphic.blizzard, delegate(bool on)
        {
            ELayer.config.graphic.blizzard = on;
            if (ELayer.core.IsGameStarted)
            {
                ELayer.screen.RefreshSky();
            }
        });
        toggleAllyLight.SetToggle(ELayer.config.graphic.drawAllyLight, delegate(bool on)
        {
            ELayer.config.graphic.drawAllyLight = on;
            if (ELayer.core.IsGameStarted)
            {
                ELayer._map.RefreshFOVAll();
            }
        });
        toggleBlur.SetToggle(ELayer.config.ui.blur, delegate(bool on)
        {
            ELayer.config.ui.blur = on;
        });
        toggleDynamicBrightness.SetToggle(ELayer.config.ui.dynamicBrightness, delegate(bool on)
        {
            ELayer.config.ui.dynamicBrightness = on;
            ELayer.config.RefreshUIBrightness();
        });
        toggleSecureWidth.SetToggle(ELayer.config.ui.secureMinWidth, delegate(bool on)
        {
            ELayer.config.ui.secureMinWidth = on;
        });
        toggleShowFloatButtons.SetToggle(ELayer.config.ui.showFloatButtons, delegate(bool on)
        {
            ELayer.config.ui.showFloatButtons = on;
        });
        buttonApplyScreenSize.SetOnClick(delegate
        {
            ValidateResolution();
            ELayer.config.ApplyResolution(force: true);
        });
        new List<string> { "none", "focus", "focusPause" };
        new List<string> { "ani0", "ani1", "ani2", "ani3", "ani4" };
        SetFont(ELayer.config.font.fontUI, fontUI, "fontUI");
        SetFont(ELayer.config.font.fontChatbox, fontChatbox, "fontChatbox");
        SetFont(ELayer.config.font.fontBalloon, fontBalloon, "fontBalloon");
        SetFont(ELayer.config.font.fontDialog, fontDialog, "fontDialog");
        SetFont(ELayer.config.font.fontWidget, fontWidget, "widget");
        SetFont(ELayer.config.font.fontNews, fontNews, "fontNews");
        ELayer.config.ignoreApply = false;
    }
References CoreConfig.Apply(), CoreConfig.ApplyGrading(), CoreConfig.ApplyScale(), CoreConfig.ApplyVolume(), CoreConfig.GraphicSetting.blur, CoreConfig.GraphicSetting.brightness, CoreConfig.UISetting.brightness, ELayer.config, CoreConfig.GraphicSetting.contrast, CoreConfig.UISetting.contrast, ELayer.core, CoreConfig.GraphicSetting.fps, Lang.Get(), CoreConfig.graphic, LangSetting.id, CoreConfig.lang, MOD.langs, Dialog.Ok(), Core.OnChangeResolution(), CoreConfig.UISetting.outlineAlpha, CoreConfig.GraphicSetting.saturation, CoreConfig.Save(), CoreConfig.UISetting.scale, CoreConfig.UISetting.scrollSens, CoreConfig.UISetting.ScrollSensitivity, CoreConfig.GraphicSetting.sharpen, CoreConfig.GraphicSetting.sharpen2, CoreConfig.sound, CoreConfig.ui, ELayer.ui, Util, CoreConfig.GraphicSetting.vibrance, CoreConfig.SoundSetting.volumeAMB, CoreConfig.SoundSetting.volumeBGM, CoreConfig.SoundSetting.volumeMaster, and CoreConfig.SoundSetting.volumeSFX.
SetFont()
void LayerConfig.SetFont (SkinManager::FontSaveData data, UIItem item, string lang) inline
Definition at line 509 of file LayerConfig.cs.
    {
        item.text1.SetLang(lang);
        UIDropdown componentInChildren = item.GetComponentInChildren<UIDropdown>();
        UIButtonLR obj = item.button1 as UIButtonLR;
        List<string> langs = new List<string> { "sizeS", "sizeDefault", "sizeL", "sizeLL", "sizeLLL", "sizeLLLL" };
        SkinManager skins = ELayer.ui.skins;
        obj.SetOptions(data.size, langs, delegate(int i)
        {
            data.size = i;
            ApplyFont();
        }, invoke: false);
        componentInChildren.options.Clear();
        for (int j = 0; j < skins.FontList.Count; j++)
        {
            FontSource fontSource = skins.FontList[j];
            componentInChildren.options.Add(new Dropdown.OptionData
            {
                text = fontSource._name
            });
            if (j == data.index)
            {
                componentInChildren.value = j;
            }
        }
        componentInChildren.onValueChanged.RemoveAllListeners();
        componentInChildren.onValueChanged.AddListener(delegate(int i)
        {
            data.index = i;
            ApplyFont();
        });
    }
References FontSource._name, Dropdown, SkinManager.FontList, item, and ELayer.ui.
SetGroup()
void LayerConfig.SetGroup (UISelectableGroup group, int value, UnityAction< int > action) inline
Definition at line 566 of file LayerConfig.cs.
    {
        group.Init(value, action);
    }
References UISelectableGroup.Init().
SetSlider()
void LayerConfig.SetSlider (Slider slider, float value, Func< float, string > action, bool notify = false) inline
Definition at line 548 of file LayerConfig.cs.
    {
        slider.onValueChanged.RemoveAllListeners();
        slider.onValueChanged.AddListener(delegate(float a)
        {
            slider.GetComponentInChildren<UIText>(includeInactive: true).text = action(a);
        });
        if (notify)
        {
            slider.value = value;
        }
        else
        {
            slider.SetValueWithoutNotify(value);
        }
        slider.GetComponentInChildren<UIText>(includeInactive: true).text = action(value);
    }
Update()
void LayerConfig.Update () inline private
Definition at line 198 of file LayerConfig.cs.
    {
        if (!inputW.isFocused && !inputH.isFocused)
        {
            ValidateResolution();
        }
    }
ValidateResolution()
void LayerConfig.ValidateResolution () inline
Definition at line 206 of file LayerConfig.cs.
    {
        int num = Mathf.Clamp(inputW.text.ToInt(), 800, Display.main.systemWidth);
        int num2 = Mathf.Clamp(inputH.text.ToInt(), 600, Display.main.systemHeight);
        inputW.text = num.ToString() ?? "";
        inputH.text = num2.ToString() ?? "";
        ELayer.core.config.graphic.w = inputW.text.ToInt();
        ELayer.core.config.graphic.h = inputH.text.ToInt();
    }
Member Data Documentation
buttonApplyScreenSize
UIButton LayerConfig.buttonApplyScreenSize
Definition at line 112 of file LayerConfig.cs.
buttonReset
UIButton LayerConfig.buttonReset
Definition at line 100 of file LayerConfig.cs.
Referenced by OnInit().
ddPostEffect
UIDropdown LayerConfig.ddPostEffect
Definition at line 98 of file LayerConfig.cs.
fontBalloon
UIItem LayerConfig.fontBalloon
Definition at line 90 of file LayerConfig.cs.
fontChatbox
UIItem LayerConfig.fontChatbox
Definition at line 88 of file LayerConfig.cs.
fontDialog
UIItem LayerConfig.fontDialog
Definition at line 92 of file LayerConfig.cs.
fontNews
UIItem LayerConfig.fontNews
Definition at line 96 of file LayerConfig.cs.
fontUI
UIItem LayerConfig.fontUI
Definition at line 86 of file LayerConfig.cs.
fontWidget
UIItem LayerConfig.fontWidget
Definition at line 94 of file LayerConfig.cs.
groupLang
UISelectableGroup LayerConfig.groupLang
Definition at line 38 of file LayerConfig.cs.
groupVSync
UISelectableGroup LayerConfig.groupVSync
Definition at line 36 of file LayerConfig.cs.
inputH
InputField LayerConfig.inputH
Definition at line 116 of file LayerConfig.cs.
inputW
InputField LayerConfig.inputW
Definition at line 114 of file LayerConfig.cs.
layoutLanguage
LayoutGroup LayerConfig.layoutLanguage
Definition at line 108 of file LayerConfig.cs.
moldLanguage
UIButton LayerConfig.moldLanguage
Definition at line 110 of file LayerConfig.cs.
sliderAMB
Slider LayerConfig.sliderAMB
Definition at line 16 of file LayerConfig.cs.
sliderBalloon
Slider LayerConfig.sliderBalloon
Definition at line 106 of file LayerConfig.cs.
sliderBGM
Slider LayerConfig.sliderBGM
Definition at line 12 of file LayerConfig.cs.
sliderBlur
Slider LayerConfig.sliderBlur
Definition at line 34 of file LayerConfig.cs.
sliderBrightness
Slider LayerConfig.sliderBrightness
Definition at line 18 of file LayerConfig.cs.
sliderContrast
Slider LayerConfig.sliderContrast
Definition at line 20 of file LayerConfig.cs.
sliderMaster
Slider LayerConfig.sliderMaster
Definition at line 10 of file LayerConfig.cs.
sliderSaturation
Slider LayerConfig.sliderSaturation
Definition at line 22 of file LayerConfig.cs.
sliderScale
Slider LayerConfig.sliderScale
Definition at line 28 of file LayerConfig.cs.
sliderScrollSense
Slider LayerConfig.sliderScrollSense
Definition at line 26 of file LayerConfig.cs.
sliderSFX
Slider LayerConfig.sliderSFX
Definition at line 14 of file LayerConfig.cs.
sliderSharpen
Slider LayerConfig.sliderSharpen
Definition at line 30 of file LayerConfig.cs.
sliderSharpen2
Slider LayerConfig.sliderSharpen2
Definition at line 32 of file LayerConfig.cs.
sliderUIBrightness
Slider LayerConfig.sliderUIBrightness
Definition at line 102 of file LayerConfig.cs.
sliderUIContrast
Slider LayerConfig.sliderUIContrast
Definition at line 104 of file LayerConfig.cs.
sliderVibrance
Slider LayerConfig.sliderVibrance
Definition at line 24 of file LayerConfig.cs.
toggleAllyLight
UIButton LayerConfig.toggleAllyLight
Definition at line 80 of file LayerConfig.cs.
toggleAutoscale
UIButton LayerConfig.toggleAutoscale
Definition at line 60 of file LayerConfig.cs.
toggleBalloon
UIButton LayerConfig.toggleBalloon
Definition at line 82 of file LayerConfig.cs.
toggleBlizzard
UIButton LayerConfig.toggleBlizzard
Definition at line 66 of file LayerConfig.cs.
toggleBloom
UIButton LayerConfig.toggleBloom
Definition at line 54 of file LayerConfig.cs.
toggleBlur
UIButton LayerConfig.toggleBlur
Definition at line 58 of file LayerConfig.cs.
toggleClosePopupOnMouseLeave
UIButton LayerConfig.toggleClosePopupOnMouseLeave
Definition at line 46 of file LayerConfig.cs.
toggleDisableShake
UIButton LayerConfig.toggleDisableShake
Definition at line 68 of file LayerConfig.cs.
toggleDynamicBrightness
UIButton LayerConfig.toggleDynamicBrightness
Definition at line 62 of file LayerConfig.cs.
toggleFirefly
UIButton LayerConfig.toggleFirefly
Definition at line 70 of file LayerConfig.cs.
toggleFixedResolution
UIButton LayerConfig.toggleFixedResolution
Definition at line 42 of file LayerConfig.cs.
toggleFloorEx
UIButton LayerConfig.toggleFloorEx
Definition at line 84 of file LayerConfig.cs.
toggleFullscreen
UIButton LayerConfig.toggleFullscreen
Definition at line 50 of file LayerConfig.cs.
toggleGodray
UIButton LayerConfig.toggleGodray
Definition at line 76 of file LayerConfig.cs.
toggleGradientWater
UIButton LayerConfig.toggleGradientWater
Definition at line 74 of file LayerConfig.cs.
toggleHDR
UIButton LayerConfig.toggleHDR
Definition at line 56 of file LayerConfig.cs.
toggleKuwahara
UIButton LayerConfig.toggleKuwahara
Definition at line 64 of file LayerConfig.cs.
toggleOpenLastTab
UIButton LayerConfig.toggleOpenLastTab
Definition at line 44 of file LayerConfig.cs.
togglePixelPerfectUI
UIButton LayerConfig.togglePixelPerfectUI
Definition at line 52 of file LayerConfig.cs.
toggleRightClickClose
UIButton LayerConfig.toggleRightClickClose
Definition at line 48 of file LayerConfig.cs.
toggleSecureWidth
UIButton LayerConfig.toggleSecureWidth
Definition at line 72 of file LayerConfig.cs.
toggleShowFloatButtons
UIButton LayerConfig.toggleShowFloatButtons
Definition at line 78 of file LayerConfig.cs.
toggleVsync
UIButton LayerConfig.toggleVsync
Definition at line 40 of file LayerConfig.cs.
The documentation for this class was generated from the following file:
Elin/LayerConfig.cs