Elin Decompiled Documentation: BiomeProfile.Spawns Class Reference
BiomeProfile.Spawns Class Reference
Public Member Functions
string GetRandomCharaId ()
string GetRandomThingId ()
Public Attributes
List< SpawnListChara > chara
List< SpawnListThing > thing
Detailed Description
Definition at line 401 of file BiomeProfile.cs.
Member Function Documentation
GetRandomCharaId()
string BiomeProfile.Spawns.GetRandomCharaId () inline
Definition at line 407 of file BiomeProfile.cs.
        {
            if (chara.Count != 0)
            {
                return chara.RandomItemWeighted((SpawnListChara a) => a.chance).id;
            }
            return "c_dungeon";
        }
References BiomeProfile.SpawnList.chance, and BiomeProfile.Spawns.chara.
Referenced by Region.OnAdvanceHour(), and SerializedCards.Restore().
GetRandomThingId()
string BiomeProfile.Spawns.GetRandomThingId () inline
Definition at line 416 of file BiomeProfile.cs.
        {
            if (thing.Count != 0)
            {
                return thing.RandomItemWeighted((SpawnListThing a) => a.chance).id;
            }
            return "dungeon";
        }
References BiomeProfile.SpawnList.chance, and BiomeProfile.Spawns.thing.
Referenced by SerializedCards.Restore().
Member Data Documentation
chara
List<SpawnListChara> BiomeProfile.Spawns.chara
Definition at line 403 of file BiomeProfile.cs.
Referenced by BiomeProfile.Spawns.GetRandomCharaId().
thing
List<SpawnListThing> BiomeProfile.Spawns.thing
Definition at line 405 of file BiomeProfile.cs.
Referenced by BiomeProfile.Spawns.GetRandomThingId().
The documentation for this class was generated from the following file:
Elin/BiomeProfile.cs