Elin Decompiled Documentation: TraitMoongate Class Reference
TraitMoongate Class Reference
Public Member Functions
override bool CanUse (Chara c)
override bool OnUse (Chara c)
async UniTask< bool > UseMoongate ()
void LoadMap (MapMetaData m)
void MoveZone (Zone zone)
List< MapMetaData > ListSavedUserMap ()
Public Member Functions inherited from Trait
string GetParam (int i, string def=null)
int GetParamInt (int i, int def)
virtual bool Contains (RecipeSource r)
virtual int GetValue ()
virtual bool CanStackTo (Thing to)
virtual string GetHoverText ()
virtual Action GetHealAction (Chara c)
virtual bool CanBlend (Thing t)
virtual void OnBlend (Thing t, Chara c)
virtual int GetActDuration (Chara c)
virtual SourceElement.Row GetRefElement ()
virtual Sprite GetRefSprite ()
virtual void OnRenderExtra (RenderParam p)
virtual Emo2 GetHeldEmo (Chara c)
virtual void SetOwner (Card _owner)
virtual bool IdleUse (Chara c, int dist)
virtual void OnSetOwner ()
virtual void OnImportMap ()
virtual void SetParams (params string[] s)
virtual void OnCrafted (Recipe recipe)
virtual void OnCreate (int lv)
virtual void OnEquip (Chara c, bool onSetOwner)
virtual void OnUnequip (Chara c)
virtual void OnChangePlaceState (PlaceState state)
virtual void OnAddedToZone ()
virtual void OnRemovedFromZone ()
virtual void OnSimulateHour (VirtualDate date)
virtual string GetName ()
virtual void SetName (ref string s)
virtual void OnRenderTile (Point point, HitResult result, int dir)
virtual int CompareTo (Card b)
virtual bool CanBuiltAt (Point p)
virtual void Update ()
Point GetPoint ()
Point GetRandomPoint (Func< Point, bool > func=null, Chara accessChara=null)
virtual List< Point > ListPoints (Point center=null, bool onlyPassable=true)
virtual Recipe GetRecipe ()
virtual Recipe GetBuildModeRecipe ()
virtual bool CanCook (Card c)
void CookProgress ()
virtual bool CanOffer (Card tg)
void OfferProcess (Chara cc)
void Offer (Chara cc)
virtual bool TryProgress (AIProgress p)
virtual LockOpenState TryOpenLock (Chara cc, bool msgFail=true)
virtual void WriteNote (UINote n, bool identified)
int GetSortVal (UIList.SortMode m)
virtual HotItem GetHotItem ()
virtual bool CanRead (Chara c)
virtual void OnRead (Chara c)
virtual bool CanEat (Chara c)
virtual void OnEat (Chara c)
virtual bool CanDrink (Chara c)
virtual void OnDrink (Chara c)
virtual void OnThrowGround (Chara c, Point p)
virtual bool CanUse (Chara c)
virtual bool CanUse (Chara c, Card tg)
virtual bool CanUse (Chara c, Point p)
virtual bool OnUse (Chara c)
virtual bool OnUse (Chara c, Card tg)
virtual bool OnUse (Chara c, Point p)
virtual void TrySetAct (ActPlan p)
virtual void TrySetHeldAct (ActPlan p)
virtual void OnHeld ()
virtual void OnTickHeld ()
virtual void OnSetCurrentItem ()
virtual void OnUnsetCurrentItem ()
virtual bool OnChildDecay (Card c, bool firstDecay)
virtual bool CanChildDecay (Card c)
virtual void OnSetCardGrid (ButtonGrid b)
virtual void OnStepped (Chara c)
virtual void OnSteppedOut (Chara c)
virtual void OnOpenDoor (Chara c)
void Install (bool byPlayer)
void Uninstall ()
virtual void OnInstall (bool byPlayer)
virtual void OnUninstall ()
virtual void TryToggle ()
virtual void Toggle (bool on, bool silent=false)
virtual void PlayToggleEffect (bool silent)
virtual void OnToggle ()
virtual void TrySetToggleAct (ActPlan p)
bool IsFuelEnough (int num=1, List< Thing > excludes=null, bool tryRefuel=true)
bool IsFuel (string s)
bool IsFuel (Thing t)
int GetFuelValue (Thing t)
int GetFuelValue (string id)
void Refuel (Thing t)
void TryRefuel (int dest, List< Thing > excludes)
virtual void OnEnterScreen ()
virtual void RefreshRenderer ()
virtual void SetMainText (UIText t, bool hotitem)
virtual bool CanCopy (Thing t)
string GetTextRestock (string lang, bool pet)
Emo2 GetRestockedIcon ()
void OnBarter ()
Thing CreateStock ()
Public Attributes
UniTask< bool > test
Public Attributes inherited from Trait
Card owner
Additional Inherited Members
Public Types inherited from Trait
enum TileMode {
Default , Door , Illumination , DefaultNoAnime ,
SignalAnime
}
enum CopyShopType { None , Item , Spellbook }
Static Public Member Functions inherited from EClass
static int rnd (int a)
static int curve (int a, int start, int step, int rate=75)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Static Public Attributes inherited from Trait
static TraitSelfFactory SelfFactory = new TraitSelfFactory()
Static Public Attributes inherited from EClass
static Core core
Static Protected Attributes inherited from Trait
static List< Point > listRadiusPoints = new List<Point>()
Properties inherited from Trait
string[] Params [get]
virtual byte WeightMod [get]
virtual int IdSkin [get]
virtual string Name [get]
virtual TileType tileType [get]
virtual RefCardName RefCardName [get]
virtual bool IsBlockPath [get]
virtual bool IsBlockSight [get]
virtual bool IsDoor [get]
virtual bool IsOpenSight [get]
virtual bool IsOpenPath [get]
virtual bool IsFloating [get]
virtual bool IsGround [get]
virtual bool InvertHeldSprite [get]
virtual bool IsChangeFloorHeight [get]
virtual bool ShouldRefreshTile [get]
virtual bool ShouldTryRefreshRoom [get]
virtual int InstallBottomPriority [get]
virtual bool CanHarvest [get]
virtual int radius [get]
virtual TraitRadiusType radiusType [get]
virtual bool CanUseRoomRadius [get]
virtual int GuidePriotiy [get]
virtual int Electricity [get]
virtual bool IgnoreLastStackHeight [get]
virtual int Decay [get]
virtual int DecaySpeed [get]
virtual int DecaySpeedChild [get]
virtual bool IsFridge [get]
virtual int DefaultStock [get]
virtual bool HoldAsDefaultInteraction [get]
virtual int CraftNum [get]
virtual bool ShowOrbit [get]
virtual bool HaveUpdate [get]
virtual bool IsSpot [get]
virtual bool IsFactory [get]
virtual bool CanAutofire [get]
virtual bool CanName [get]
virtual bool CanPutAway [get]
virtual bool CanChangeHeight [get]
virtual bool CanStack [get]
virtual bool CanCopyInBlueprint [get]
virtual bool CanBeAttacked [get]
virtual bool CanExtendBuild [get]
virtual string langNote [get]
virtual string IDInvStyle [get]
virtual string IDActorEx [get]
virtual bool MaskOnBuild [get]
virtual bool ShowContextOnPick [get]
virtual bool IsThrowMainAction [get]
virtual bool LevelAsQuality [get]
virtual bool UseDummyTile [get]
virtual bool RequireFullStackCheck [get]
virtual bool DisableAutoCombat [get]
virtual InvGridSize InvGridSize [get]
virtual bool IsContainer [get]
virtual bool CanUseContent [get]
virtual bool CanSearchContent [get]
virtual bool CanOpenContainer [get]
virtual bool IsSpecialContainer [get]
virtual ContainerType ContainerType [get]
virtual ThrowType ThrowType [get]
virtual EffectDead EffectDead [get]
virtual bool IsHomeItem [get]
virtual bool IsAltar [get]
virtual bool IsRestSpot [get]
virtual bool CanBeMasked [get]
virtual bool IsBlendBase [get]
virtual bool CanBeOnlyBuiltInHome [get]
virtual bool CanBuildInTown [get]
virtual bool CanBeHeld [get]
virtual bool CanBeStolen [get]
virtual bool CanOnlyCarry [get]
virtual bool CanBeDestroyed [get]
virtual bool CanBeHallucinated [get]
virtual bool CanBeDropped [get]
virtual string ReqHarvest [get]
virtual bool CanBeDisassembled [get]
virtual bool CanBeShipped [get]
virtual bool HasCharges [get]
virtual bool ShowCharges [get]
virtual bool ShowChildrenNumber [get]
virtual bool ShowAsTool [get]
virtual bool CanBeHeldAsFurniture [get]
virtual bool HideInAdv [get]
virtual bool NoHeldDir [get]
virtual bool AlwaysHideOnLowWall [get]
bool ExistsOnMap [get]
virtual bool RenderExtra [get]
virtual float DropChance [get]
virtual string IdNoRestock [get]
virtual int IdleUseChance [get]
virtual string RecipeCat [get]
virtual bool IsTool [get]
virtual string LangUse [get]
virtual bool IsOn [get]
virtual bool IsAnimeOn [get]
bool IsToggle [get]
virtual bool AutoToggle [get]
bool IsLighting [get]
virtual bool IsLightOn [get]
virtual bool IsNightOnlyLight [get]
virtual TileMode tileMode [get]
virtual bool UseAltTiles [get]
virtual bool UseLowblock [get]
virtual bool UseExtra [get]
virtual bool UseLightColor [get]
virtual ? Color ColorExtra [get]
virtual int MaxFuel [get]
virtual int FuelCost [get]
virtual bool ShowFuelWindow [get]
bool IsRequireFuel [get]
string IdToggleExtra [get]
virtual ToggleType ToggleType [get]
virtual int ShopLv [get]
virtual CopyShopType CopyShop [get]
virtual int NumCopyItem [get]
virtual ShopType ShopType [get]
virtual CurrencyType CurrencyType [get]
virtual PriceType PriceType [get]
virtual bool AllowSell [get]
virtual int CostRerollShop [get]
virtual bool AllowCriminal [get]
virtual int RestockDay [get]
virtual SlaverType SlaverType [get]
virtual string LangBarter [get]
string TextNextRestock [get]
string TextNextRestockPet [get]
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Detailed Description
Definition at line 8 of file TraitMoongate.cs.
Member Function Documentation
CanUse()
override bool TraitMoongate.CanUse (Chara c) inline virtual
Reimplemented from Trait.
Definition at line 12 of file TraitMoongate.cs.
    {
        if (EClass._zone.IsInstance || EClass._zone.dateExpire != 0 || EClass._zone.IsRegion || !owner.IsInstalled)
        {
            return false;
        }
        return true;
    }
References EClass._zone, Spatial.dateExpire, Card.IsInstalled, Zone.IsInstance, Spatial.IsRegion, and Trait.owner.
ListSavedUserMap()
List< MapMetaData > TraitMoongate.ListSavedUserMap () inline
Definition at line 134 of file TraitMoongate.cs.
    {
        List<MapMetaData> list = new List<MapMetaData>();
        foreach (FileInfo item in new DirectoryInfo(CorePath.ZoneSaveUser).GetFiles().Concat(MOD.listMaps))
        {
            if (!(item.Extension != ".z"))
            {
                MapMetaData metaData = Map.GetMetaData(item.FullName);
                if (metaData != null && metaData.IsValidVersion())
                {
                    metaData.path = item.FullName;
                    metaData.date = item.LastWriteTime;
                    list.Add(metaData);
                }
            }
        }
        return list;
    }
References Map.GetMetaData(), MapMetaData.IsValidVersion(), item, MOD.listMaps, and CorePath.ZoneSaveUser.
Referenced by TraitMoongateEx._OnUse(), and UseMoongate().
LoadMap()
void TraitMoongate.LoadMap (MapMetaData m) inline
Definition at line 102 of file TraitMoongate.cs.
    {
        if (EClass.pc.burden.GetPhase() == 4)
        {
            Msg.Say("returnOverweight");
            return;
        }
        Debug.Log("loading:" + m.name + "/" + m.path);
        Zone_User zone_User = EClass.game.spatials.Find((Zone_User z) => z.idUser == m.id);
        if (zone_User == null)
        {
            zone_User = SpatialGen.Create("user", EClass.world.region, register: true) as Zone_User;
            zone_User.path = m.path;
            zone_User.idUser = m.id;
            zone_User.dateExpire = EClass.world.date.GetRaw(1);
            zone_User.name = m.name;
        }
        Debug.Log(zone_User);
        MoveZone(zone_User);
    }
References Chara.burden, SpatialGen.Create(), World.date, Debug, SpatialManager.Find(), EClass.game, Stats.GetPhase(), Date.GetRaw(), MapMetaData.id, Spatial.idUser, MoveZone(), MapMetaData.name, MapMetaData.path, EClass.pc, World.region, Msg.Say(), Game.spatials, and EClass.world.
Referenced by TraitMoongateEx._OnUse(), and UseMoongate().
MoveZone()
void TraitMoongate.MoveZone (Zone zone) inline
Definition at line 123 of file TraitMoongate.cs.
    {
        zone.instance = new ZoneInsstanceMoongate
        {
            uidZone = EClass._zone.uid,
            x = EClass.pc.pos.x,
            z = EClass.pc.pos.z
        };
        EClass.pc.MoveZone(zone, ZoneTransition.EnterState.Moongate);
    }
References EClass._zone, Chara.MoveZone(), EClass.pc, Card.pos, Spatial.uid, and Point.x.
Referenced by LoadMap(), and UseMoongate().
OnUse()
override bool TraitMoongate.OnUse (Chara c) inline virtual
Reimplemented from Trait.
Reimplemented in TraitMoongateEx.
Definition at line 21 of file TraitMoongate.cs.
    {
        if (EClass.core.version.demo)
        {
            Msg.SayNothingHappen();
            return false;
        }
        Core.TryWarnMod(delegate
        {
            LayerProgress.StartAsync("Loading", UseMoongate());
        }, warn: false);
        return false;
    }
References EClass.core, Version.demo, Msg.SayNothingHappen(), LayerProgress.StartAsync(), Core.TryWarnMod(), UseMoongate(), and BaseCore.version.
UseMoongate()
async UniTask< bool > TraitMoongate.UseMoongate () inline
Definition at line 35 of file TraitMoongate.cs.
    {
        string lang = Lang.langCode;
        if (lang != "JP" && lang != "CN" && lang != "EN")
        {
            lang = "EN";
        }
        if (EClass.core.config.backer.filter == 0)
        {
            lang = ((EClass.rnd(10) != 0) ? ((EClass.rnd(2) == 0) ? "JP" : "EN") : "CN");
        }
        Debug.Log(lang);
        try
        {
            List<Net.DownloadMeta> list = (await Net.GetFileList(lang)).Where((Net.DownloadMeta m) => m.IsValidVersion()).ToList();
            if (list == null || list.Count == 0)
            {
                EClass.pc.SayNothingHappans();
                return false;
            }
            List<MapMetaData> list2 = ListSavedUserMap();
            IList<Net.DownloadMeta> list3 = list.Copy();
            foreach (MapMetaData item2 in list2)
            {
                foreach (Net.DownloadMeta item3 in list3)
                {
                    if (item3.id == item2.id && item3.version == item2.version)
                    {
                        list3.Remove(item3);
                        break;
                    }
                }
            }
            Debug.Log(list3.Count);
            if (list3.Count == 0)
            {
                list3 = list.Copy();
            }
            Net.DownloadMeta item = list3.RandomItem();
            Zone_User zone_User = EClass.game.spatials.Find((Zone_User z) => z.id == item.id);
            if (zone_User != null)
            {
                MoveZone(zone_User);
                return true;
            }
            FileInfo fileInfo = await Net.DownloadFile(item, CorePath.ZoneSaveUser, lang);
            Debug.Log(item?.ToString() + "/" + item.title + item.id + "/" + item.path + "/");
            Debug.Log(fileInfo?.ToString() + "/" + item.name + "/" + item.path);
            if (Zone.IsImportValid(fileInfo.FullName))
            {
                Debug.Log("valid");
                LoadMap(Map.GetMetaData(fileInfo.FullName));
            }
            else
            {
                Debug.Log("invalid");
                EClass.pc.SayNothingHappans();
            }
        }
        catch (Exception ex)
        {
            EClass.ui.Say(ex.Message);
            return false;
        }
        return true;
    }
References CoreConfig.backer, Core.config, EClass.core, Debug, Net.DownloadFile(), CoreConfig.BackerContentConfig.filter, SpatialManager.Find(), EClass.game, Net.GetFileList(), Map.GetMetaData(), MapMetaData.id, Spatial.id, Zone.IsImportValid(), item, Lang.langCode, ListSavedUserMap(), LoadMap(), MoveZone(), EClass.pc, EClass.rnd(), Card.SayNothingHappans(), Game.spatials, EClass.ui, MapMetaData.version, and CorePath.ZoneSaveUser.
Referenced by OnUse().
Member Data Documentation
test
UniTask<bool> TraitMoongate.test
Definition at line 10 of file TraitMoongate.cs.
The documentation for this class was generated from the following file:
Elin/TraitMoongate.cs