Elin Decompiled Documentation: PoolManager.PoolGroup Class Reference
PoolManager.PoolGroup Class Reference
Public Member Functions
PoolGroup (Transform original, PoolManager manager, string _id)
Transform Spawn (Transform parent)
void Despawn (Transform trans)
Public Attributes
string id
Transform original
Transform holder
List< Transform > pooledList = new List<Transform>()
Detailed Description
Definition at line 6 of file PoolManager.cs.
Constructor & Destructor Documentation
PoolGroup()
PoolManager.PoolGroup.PoolGroup (Transform original, PoolManager manager, string _id) inline
Definition at line 16 of file PoolManager.cs.
        {
            id = _id;
            this.original = original;
            holder = new GameObject().transform;
            holder.SetParent(manager.transform);
            holder.name = id;
        }
References PoolManager.PoolGroup.holder, PoolManager.PoolGroup.id, and PoolManager.PoolGroup.original.
Member Function Documentation
Despawn()
void PoolManager.PoolGroup.Despawn (Transform trans) inline
Definition at line 50 of file PoolManager.cs.
        {
            trans.SetParent(holder, worldPositionStays: false);
            pooledList.Add(trans);
        }
References PoolManager.PoolGroup.holder, and PoolManager.PoolGroup.pooledList.
Referenced by PoolManager.TryDespawn().
Spawn()
Transform PoolManager.PoolGroup.Spawn (Transform parent) inline
Definition at line 25 of file PoolManager.cs.
        {
            Transform transform = null;
            if (ignorePool)
            {
                transform = Object.Instantiate(original);
            }
            else if (pooledList.Count != 0)
            {
                transform = pooledList[pooledList.Count - 1];
                pooledList.RemoveAt(pooledList.Count - 1);
            }
            else
            {
                transform = Object.Instantiate(original);
                current.spawnedList[transform.GetHashCode()] = this;
            }
            if (Application.isEditor)
            {
                transform.SetAsLastSibling();
            }
            transform.SetParent(parent, worldPositionStays: false);
            return transform;
        }
References PoolManager.current, PoolManager.ignorePool, PoolManager.PoolGroup.original, PoolManager.PoolGroup.pooledList, and PoolManager.spawnedList.
Referenced by PoolManager._Spawn().
Member Data Documentation
holder
Transform PoolManager.PoolGroup.holder
Definition at line 12 of file PoolManager.cs.
Referenced by PoolManager.PoolGroup.Despawn(), and PoolManager.PoolGroup.PoolGroup().
id
string PoolManager.PoolGroup.id
Definition at line 8 of file PoolManager.cs.
Referenced by PoolManager.PoolGroup.PoolGroup().
original
Transform PoolManager.PoolGroup.original
Definition at line 10 of file PoolManager.cs.
Referenced by PoolManager.PoolGroup.PoolGroup(), and PoolManager.PoolGroup.Spawn().
pooledList
List<Transform> PoolManager.PoolGroup.pooledList = new List<Transform>()
Definition at line 14 of file PoolManager.cs.
Referenced by PoolManager.PoolGroup.Despawn(), and PoolManager.PoolGroup.Spawn().
The documentation for this class was generated from the following file:
Elin/Plugins.basecore/PoolManager.cs