Elin Decompiled Documentation: RecipeManager Class Reference
RecipeManager Class Reference
Public Member Functions
RecipeSource GetSource (string id)
void Add (string id, bool showEffect=true)
bool IsKnown (string id)
List< RecipeSource > ListSources (Thing factory, List< RecipeSource > newRecipes=null)
void OnSleep (bool ehe=false)
void ComeUpWithRandomRecipe (string idCat=null, int lvBonus=0)
bool CanCeomUpWithRecipe (string idRecipe)
void ComeUpWithRecipe (string idRecipe, int chanceForRandomRecipe=0)
void OnVersionUpdate ()
Static Public Member Functions
static void BuildList ()
static void Create (RenderRow row, string type, string suffix="")
static RecipeSource Get (string id)
static RecipeSource GetUnlearnedRecipe (int lvBonus, string cat, bool onlyUnlearned)
static RecipeSource GetLearnedRecipe (string cat=null)
static string GetRandomRecipe (int lvBonus, string cat=null, bool onlyUnlearned=false)
Static Public Member Functions inherited from EClass
static int rndSeed (int a, int seed)
static int rnd (long a)
static int rnd (int a)
static int curve (int a, int start, int step, int rate=75)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Public Attributes
HashSet< string > knownIngredients = new HashSet<string>()
HashSet< string > craftedRecipes = new HashSet<string>()
Dictionary< string, int > knownRecipes = new Dictionary<string, int>()
HashSet< string > hoveredRecipes = new HashSet<string>()
HashSet< string > newRecipes = new HashSet<string>()
Dictionary< string, List< int > > lastIngredients = new Dictionary<string, List<int>>()
Static Public Attributes
static bool rebuild
static List< RecipeSource > list = new List<RecipeSource>()
static Dictionary< string, RecipeSource > dict = new Dictionary<string, RecipeSource>()
Static Public Attributes inherited from EClass
static Core core
Additional Inherited Members
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Detailed Description
Definition at line 5 of file RecipeManager.cs.
Member Function Documentation
Add()
void RecipeManager.Add (string id, bool showEffect = true) inline
Definition at line 105 of file RecipeManager.cs.
    {
        if (id.IsEmpty())
        {
            return;
        }
        RecipeSource recipeSource = Get(id);
        if (recipeSource == null)
        {
            return;
        }
        if (!knownRecipes.ContainsKey(id))
        {
            newRecipes.Add(id);
            knownRecipes[id] = 0;
        }
        knownRecipes[id]++;
        int num = knownRecipes[id];
        if (showEffect)
        {
            EClass.pc.PlaySound("idea");
            EClass.pc.ShowEmo(Emo.idea, 0.5f, skipSame: false);
        }
        EClass.pc.Say("learnRecipe" + ((num == 1) ? "New" : ""), dict[id].Name.ToTitleCase(), num.ToString() ?? "");
        if (num == 1 && !recipeSource.isBridgePillar)
        {
            if (recipeSource.NeedFactory)
            {
                EClass.pc.Say("recipe_factory", recipeSource.NameFactory);
            }
            else
            {
                EClass.pc.Say("recipe_nofactory");
            }
        }
        recipeSource = Get(id + "-p");
        if (recipeSource != null && !knownRecipes.ContainsKey(recipeSource.id))
        {
            Add(recipeSource.id, showEffect: false);
        }
        recipeSource = Get(id.Replace("-p", ""));
        if (recipeSource != null && !knownRecipes.ContainsKey(recipeSource.id))
        {
            Add(recipeSource.id, showEffect: false);
        }
        if (recipeSource.row.category == "floor")
        {
            recipeSource = Get(id + "-b");
            if (recipeSource != null && !knownRecipes.ContainsKey(recipeSource.id))
            {
                Add(recipeSource.id, showEffect: false);
            }
            recipeSource = Get(id.Replace("-b", ""));
            if (recipeSource != null && !knownRecipes.ContainsKey(recipeSource.id))
            {
                Add(recipeSource.id, showEffect: false);
            }
        }
    }
References Add(), RenderRow.category, dict, Get(), RecipeSource.id, RecipeSource.isBridgePillar, knownRecipes, RecipeSource.NameFactory, RecipeSource.NeedFactory, newRecipes, EClass.pc, Card.PlaySound(), RecipeSource.row, Card.Say(), and Card.ShowEmo().
Referenced by Add(), ComeUpWithRandomRecipe(), ComeUpWithRecipe(), ListSources(), TraitRecipe.OnRead(), TraitRecipeCat.OnRead(), OnSleep(), and ResearchPlan.ParseReward().
BuildList()
static void RecipeManager.BuildList () inline static
Definition at line 31 of file RecipeManager.cs.
    {
        if (!rebuild && list.Count > 0)
        {
            return;
        }
        Debug.Log("Rebuilding recipe list");
        list.Clear();
        dict.Clear();
        foreach (CardRow row in EClass.sources.cards.rows)
        {
            if (!row.isOrigin && (row.factory.IsEmpty() || !(row.factory[0] == "x")))
            {
                Create(row, "", row.isChara ? "-c" : "");
            }
        }
        foreach (SourceBlock.Row row2 in EClass.sources.blocks.rows)
        {
            Create(row2, "Block");
            if (row2.tileType == TileType.Pillar)
            {
                Create(row2, "BridgePillar", "-p");
            }
        }
        foreach (SourceFloor.Row row3 in EClass.sources.floors.rows)
        {
            if (!row3.tag.Contains("noFloor"))
            {
                Create(row3, "Floor");
            }
        }
        foreach (SourceFloor.Row row4 in EClass.sources.floors.rows)
        {
            if (!row4.tag.Contains("noBridge") && !row4.factory.IsEmpty() && row4.factory[0] != "x")
            {
                Create(row4, "Bridge", "-b");
            }
        }
        foreach (SourceObj.Row row5 in EClass.sources.objs.rows)
        {
            Create(row5, "Obj");
        }
        foreach (SourceCellEffect.Row row6 in EClass.sources.cellEffects.rows)
        {
            Create(row6, "Liquid");
        }
        rebuild = false;
    }
References SourceManager.blocks, SourceManager.cards, SourceManager.cellEffects, Create(), Debug, dict, RenderRow.factory, SourceManager.floors, CardRow.isChara, CardRow.isOrigin, list, SourceManager.objs, TileType.Pillar, rebuild, SourceCard.rows, and EClass.sources.
Referenced by BuildMenu._Search(), BuildMenu.Activate(), Map.DropBlockComponent(), Recipe.DropIngredients(), GetUnlearnedRecipe(), ListSources(), CraftUtil.MakeDish(), Game.OnGameInstantiated(), HotItemHeld.OnSetCurrentItem(), LayerCraft.RefreshCategory(), and WidgetCodex.Search().
CanCeomUpWithRecipe()
bool RecipeManager.CanCeomUpWithRecipe (string idRecipe) inline
Definition at line 244 of file RecipeManager.cs.
    {
        if (idRecipe.IsEmpty())
        {
            return false;
        }
        RecipeSource recipeSource = Get(idRecipe);
        if (recipeSource == null || EClass.player.recipes.knownRecipes.ContainsKey(idRecipe) || (!recipeSource.NeedFactory && !recipeSource.IsQuickCraft))
        {
            return false;
        }
        int id = recipeSource.GetReqSkill().id;
        if (EClass.pc.Evalue(id) + 5 < recipeSource.row.LV)
        {
            return false;
        }
        return true;
    }
References Card.Evalue(), Get(), RecipeSource.GetReqSkill(), Element.id, RecipeSource.IsQuickCraft, knownRecipes, RenderRow.LV, RecipeSource.NeedFactory, EClass.pc, EClass.player, Player.recipes, and RecipeSource.row.
Referenced by BaseTaskHarvest.GetText().
ComeUpWithRandomRecipe()
void RecipeManager.ComeUpWithRandomRecipe (string idCat = null, int lvBonus = 0) inline
Definition at line 234 of file RecipeManager.cs.
    {
        string randomRecipe = GetRandomRecipe(lvBonus, idCat, onlyUnlearned: true);
        if (randomRecipe != null)
        {
            Msg.Say("learnRecipeIdea");
            Add(randomRecipe);
        }
    }
References Add(), GetRandomRecipe(), and Msg.Say().
Referenced by TraitShrine._OnUse(), ComeUpWithRecipe(), and RecipeCard.Craft().
ComeUpWithRecipe()
void RecipeManager.ComeUpWithRecipe (string idRecipe, int chanceForRandomRecipe = 0) inline
Definition at line 263 of file RecipeManager.cs.
    {
        if (idRecipe.IsEmpty())
        {
            return;
        }
        RecipeSource recipeSource = Get(idRecipe);
        int num = EClass.pc.Evalue(1661);
        if (EClass.rnd((num >= 2) ? 5 : ((num == 1) ? 8 : 10)) != 0 && !EClass.debug.enable)
        {
            return;
        }
        if (recipeSource == null || EClass.player.recipes.knownRecipes.ContainsKey(idRecipe) || (!recipeSource.NeedFactory && !recipeSource.IsQuickCraft))
        {
            if (recipeSource != null && chanceForRandomRecipe > 0 && EClass.rnd(EClass.debug.enable ? 1 : chanceForRandomRecipe) == 0)
            {
                ComeUpWithRandomRecipe(recipeSource.row.Category.id);
            }
            return;
        }
        int id = recipeSource.GetReqSkill().id;
        if (EClass.pc.Evalue(id) + 5 < recipeSource.row.LV)
        {
            Msg.Say("recipeReqLv", EClass.sources.elements.map[id].GetName());
            return;
        }
        Msg.Say("learnRecipeIdea");
        Add(idRecipe);
    }
References Add(), RenderRow.Category, ComeUpWithRandomRecipe(), EClass.debug, SourceManager.elements, CoreDebug.enable, Card.Evalue(), Get(), RecipeSource.GetReqSkill(), Element.id, RecipeSource.IsQuickCraft, knownRecipes, RenderRow.LV, RecipeSource.NeedFactory, EClass.pc, EClass.player, Player.recipes, EClass.rnd(), RecipeSource.row, Msg.Say(), and EClass.sources.
Referenced by TaskHarvest.OnCreateProgress(), TaskDig.OnProgressComplete(), and TaskMine.OnProgressComplete().
Create()
static void RecipeManager.Create (RenderRow row, string type, string suffix = "") inline static
Definition at line 80 of file RecipeManager.cs.
    {
        RecipeSource recipeSource = new RecipeSource();
        recipeSource.id = row.RecipeID + suffix;
        recipeSource.isBridge = type == "Bridge";
        recipeSource.isBridgePillar = type == "BridgePillar";
        recipeSource.type = type;
        recipeSource.row = row;
        recipeSource.isChara = row is SourceChara.Row;
        list.Add(recipeSource);
        dict[recipeSource.id] = recipeSource;
        _ = row.components;
        Recipe.Create(recipeSource).BuildIngredientList();
    }
References Recipe.BuildIngredientList(), RenderRow.components, Recipe.Create(), dict, RecipeSource.id, and list.
Referenced by BuildList().
Get()
static RecipeSource RecipeManager.Get (string id) inline static
Definition at line 95 of file RecipeManager.cs.
    {
        return dict.TryGetValue(id);
    }
References dict.
Referenced by Add(), CanCeomUpWithRecipe(), ComeUpWithRecipe(), Map.DropBlockComponent(), GetLearnedRecipe(), CraftUtil.MakeDish(), and LayerCraftFloat.RefreshDisassemble().
GetLearnedRecipe()
static RecipeSource RecipeManager.GetLearnedRecipe (string cat = null) inline static
Definition at line 307 of file RecipeManager.cs.
    {
        List<RecipeSource> list = new List<RecipeSource>();
        foreach (string key in EClass.player.recipes.knownRecipes.Keys)
        {
            RecipeSource recipeSource = Get(key);
            if (recipeSource != null && recipeSource.row is SourceThing.Row && (recipeSource.NeedFactory || recipeSource.IsQuickCraft) && (cat == null || recipeSource.row.Category.IsChildOf(cat)))
            {
                list.Add(recipeSource);
            }
        }
        return list.RandomItemWeighted((RecipeSource r) => (r.row.chance == 0) ? 100 : r.row.chance);
    }
References RenderRow.Category, RenderRow.chance, Get(), RecipeSource.IsQuickCraft, knownRecipes, list, RecipeSource.NeedFactory, EClass.player, Player.recipes, and RecipeSource.row.
Referenced by GetRandomRecipe().
GetRandomRecipe()
static string RecipeManager.GetRandomRecipe (int lvBonus, string cat = null, bool onlyUnlearned = false) inline static
Definition at line 321 of file RecipeManager.cs.
    {
        RecipeSource recipeSource = null;
        recipeSource = GetUnlearnedRecipe(lvBonus, cat, onlyUnlearned);
        if (recipeSource == null)
        {
            recipeSource = GetLearnedRecipe(cat);
        }
        return recipeSource?.id;
    }
References GetLearnedRecipe(), GetUnlearnedRecipe(), and RecipeSource.id.
Referenced by ComeUpWithRandomRecipe(), TraitRecipe.OnCreate(), TraitRecipeCat.OnRead(), and OnSleep().
GetSource()
RecipeSource RecipeManager.GetSource (string id) inline
Definition at line 100 of file RecipeManager.cs.
    {
        return dict.TryGetValue(id);
    }
References dict.
Referenced by AM_Picker.TryGetRecipe().
GetUnlearnedRecipe()
static RecipeSource RecipeManager.GetUnlearnedRecipe (int lvBonus, string cat, bool onlyUnlearned) inline static
Definition at line 293 of file RecipeManager.cs.
    {
        BuildList();
        List<RecipeSource> list = new List<RecipeSource>();
        foreach (RecipeSource item in RecipeManager.list)
        {
            if (!item.alwaysKnown && (item.NeedFactory || item.IsQuickCraft) && (cat == null || item.row.Category.IsChildOf(cat)) && (!onlyUnlearned || !EClass.player.recipes.knownRecipes.ContainsKey(item.id)) && EClass.pc.Evalue(item.GetReqSkill().id) + 5 + lvBonus >= item.row.LV && !item.row.ContainsTag("hiddenRecipe"))
            {
                list.Add(item);
            }
        }
        return list.RandomItemWeighted((RecipeSource r) => (r.row.chance == 0) ? 100 : r.row.chance);
    }
References BuildList(), RenderRow.chance, Card.Evalue(), item, knownRecipes, list, EClass.pc, EClass.player, Player.recipes, and RecipeSource.row.
Referenced by GetRandomRecipe().
IsKnown()
bool RecipeManager.IsKnown (string id) inline
Definition at line 165 of file RecipeManager.cs.
    {
        if (!EClass.debug.allRecipe)
        {
            return EClass.player.recipes.knownRecipes.ContainsKey(id);
        }
        return true;
    }
References CoreDebug.allRecipe, EClass.debug, knownRecipes, EClass.player, and Player.recipes.
Referenced by AM_Picker.Result.GetText(), and BuildMenu.RefreshCategory().
ListSources()
List< RecipeSource > RecipeManager.ListSources (Thing factory, List< RecipeSource > newRecipes = null) inline
Definition at line 174 of file RecipeManager.cs.
    {
        BuildList();
        List<RecipeSource> list = new List<RecipeSource>();
        foreach (RecipeSource item in RecipeManager.list)
        {
            if (item.isBridgePillar || (factory == null && item.idFactory != "self") || (factory != null && !factory.trait.Contains(item)) || item.isChara || item.noListing)
            {
                continue;
            }
            if (!EClass.debug.godCraft && !EClass.player.recipes.knownRecipes.ContainsKey(item.id))
            {
                bool flag = false;
                if (item.row.recipeKey != null && item.row.recipeKey.Length != 0 && item.row.recipeKey[0][0] == '*')
                {
                    flag = true;
                }
                string id = item.id;
                if (!(id == "waystone"))
                {
                    if (id == "container_shipping" && EClass.game.quests.GetPhase<QuestShippingChest>() >= 0)
                    {
                        flag = true;
                    }
                }
                else if (EClass.game.quests.GetPhase<QuestExploration>() >= 6)
                {
                    flag = true;
                }
                if (!flag)
                {
                    continue;
                }
                if (newRecipes != null)
                {
                    EClass.player.recipes.Add(item.id);
                    if (EClass.player.recipes.newRecipes.Contains(item.id))
                    {
                        newRecipes.Add(item);
                        EClass.player.recipes.newRecipes.Remove(item.id);
                    }
                }
            }
            list.Add(item);
        }
        return list;
    }
References Add(), BuildList(), EClass.debug, EClass.game, CoreDebug.godCraft, item, knownRecipes, list, newRecipes, EClass.player, Game.quests, and Player.recipes.
Referenced by TraitCrafter.OnUse(), LayerCraft.RefreshCategory(), and TraitCrafter.TrySetAct().
OnSleep()
void RecipeManager.OnSleep (bool ehe = false) inline
Definition at line 222 of file RecipeManager.cs.
    {
        int slept = EClass.player.stats.slept;
        Rand.SetSeed(EClass.game.seed + slept);
        if ((slept <= 3 || EClass.rnd(ehe ? 777 : 3) != 0) && (EClass.rnd(EClass.pc.Evalue(1642) + 1) > 0 || ((slept <= 15 || EClass.rnd(3) != 0) && (slept <= 30 || EClass.rnd(3) != 0) && (slept <= 60 || EClass.rnd(3) != 0))))
        {
            Msg.Say("learnRecipeSleep");
            Rand.SetSeed();
            Add(GetRandomRecipe((ehe ? 5 : 0) + EClass.rnd(EClass.rnd(EClass.rnd(10)))));
        }
    }
References Add(), Card.Evalue(), EClass.game, GetRandomRecipe(), EClass.pc, EClass.player, EClass.rnd(), Msg.Say(), Game.seed, Rand.SetSeed(), Player.Stats.slept, and Player.stats.
Referenced by ConSleep.OnRemoved().
OnVersionUpdate()
void RecipeManager.OnVersionUpdate () inline
Definition at line 332 of file RecipeManager.cs.
    {
        EClass.pc.things.Foreach(delegate(Thing t)
        {
            knownIngredients.Add(t.id);
        });
        knownIngredients.Add("flower");
    }
References ThingContainer.Foreach(), Card.id, knownIngredients, EClass.pc, and Card.things.
Member Data Documentation
craftedRecipes
HashSet<string> RecipeManager.craftedRecipes = new HashSet<string>()
Definition at line 17 of file RecipeManager.cs.
Referenced by Recipe.HasFirstTimeBonus(), and Recipe.TryGetFirstTimeBonus().
dict
Dictionary<string, RecipeSource> RecipeManager.dict = new Dictionary<string, RecipeSource>() static
Definition at line 11 of file RecipeManager.cs.
Referenced by Add(), BuildList(), Create(), Recipe.Create(), Get(), TraitTile.GetBuildModeRecipe(), Recipe.GetOrCreate(), TraitTile.GetRecipe(), and GetSource().
hoveredRecipes
HashSet<string> RecipeManager.hoveredRecipes = new HashSet<string>()
Definition at line 23 of file RecipeManager.cs.
Referenced by LayerCraft.RefreshCategory(), LayerCraftFloat.RefreshCraft(), and ButtonGrid.SetCraftRecipe().
knownIngredients
HashSet<string> RecipeManager.knownIngredients = new HashSet<string>()
Definition at line 14 of file RecipeManager.cs.
Referenced by Card.AddThing(), and OnVersionUpdate().
knownRecipes
Dictionary<string, int> RecipeManager.knownRecipes = new Dictionary<string, int>()
Definition at line 20 of file RecipeManager.cs.
Referenced by BuildMenu._Search(), Add(), CoreDebug.AddAllRecipes(), CoreDebug.AllRecipe(), CanCeomUpWithRecipe(), ComeUpWithRecipe(), GetLearnedRecipe(), GetUnlearnedRecipe(), IsKnown(), ListSources(), UIRecipeInfo.Refresh(), WidgetCodex.Search(), and TraitRecipe.SetName().
lastIngredients
Dictionary<string, List<int> > RecipeManager.lastIngredients = new Dictionary<string, List<int>>()
Definition at line 29 of file RecipeManager.cs.
Referenced by DropdownGrid.BuildIngredients(), and Recipe.SaveLastIngredients().
list
List<RecipeSource> RecipeManager.list = new List<RecipeSource>() static
Definition at line 9 of file RecipeManager.cs.
Referenced by BuildMenu._Search(), CoreDebug.AddAllRecipes(), BuildList(), Create(), GetLearnedRecipe(), GetUnlearnedRecipe(), ListSources(), Trait.OnBarter(), BuildMenu.RefreshCategory(), WidgetCodex.Search(), and Map.TryShatter().
newRecipes
HashSet<string> RecipeManager.newRecipes = new HashSet<string>()
Definition at line 26 of file RecipeManager.cs.
Referenced by Add(), and ListSources().
rebuild
bool RecipeManager.rebuild static
Definition at line 7 of file RecipeManager.cs.
Referenced by BuildList().
The documentation for this class was generated from the following file:
Elin/RecipeManager.cs