Elin Decompiled Documentation: DramaEventTalk Class Reference
DramaEventTalk Class Reference
Public Member Functions
DramaEventTalk ()
DramaEventTalk (string _idActor, Func< string > func)
DramaEventTalk (string _idActor, string _text, List< DramaChoice > listChoice=null)
void AddChoice (DramaChoice choice)
override bool Play ()
void InitDialog ()
void ResetDialog ()
Public Member Functions inherited from DramaEvent
virtual bool Play ()
virtual void Reset ()
Public Attributes
string text
string idCancelJump
List< DramaChoice > choices = new List<DramaChoice>()
bool center
bool canCancel
bool unknown
float timer
Func< string > funcText
Public Attributes inherited from DramaEvent
int progress
string idJump
string idActor
string step
float time
bool temp
DramaSequence sequence
Additional Inherited Members
Static Public Member Functions inherited from EClass
static int rnd (int a)
static int curve (int a, int start, int step, int rate=75)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Static Public Attributes inherited from EClass
static Core core
Properties inherited from DramaEvent
DramaActor actor [get]
DramaManager manager [get]
LayerDrama layer [get]
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Detailed Description
Definition at line 5 of file DramaEventTalk.cs.
Constructor & Destructor Documentation
DramaEventTalk() [1/3]
DramaEventTalk.DramaEventTalk () inline
Definition at line 23 of file DramaEventTalk.cs.
    {
    }
DramaEventTalk() [2/3]
DramaEventTalk.DramaEventTalk (string _idActor, Func< string > func) inline
Definition at line 27 of file DramaEventTalk.cs.
    {
        if (_idActor.Contains("?"))
        {
            unknown = true;
        }
        idActor = _idActor.Replace("?", "");
        funcText = func;
    }
References funcText, DramaEvent.idActor, and unknown.
DramaEventTalk() [3/3]
DramaEventTalk.DramaEventTalk (string _idActor, string _text, List< DramaChoice > listChoice = null) inline
Definition at line 37 of file DramaEventTalk.cs.
    {
        if (_idActor.Contains("?"))
        {
            unknown = true;
        }
        idActor = _idActor.Replace("?", "");
        text = _text;
        if (listChoice == null)
        {
            return;
        }
        foreach (DramaChoice item in listChoice)
        {
            AddChoice(item);
        }
    }
References AddChoice(), DramaEvent.idActor, item, text, and unknown.
Member Function Documentation
AddChoice()
void DramaEventTalk.AddChoice (DramaChoice choice) inline
Definition at line 55 of file DramaEventTalk.cs.
    {
        choices.Add(choice);
    }
References choices.
Referenced by DramaCustomSequence.Choice(), DramaCustomSequence.Choice2(), DramaEventTalk(), and DramaManager.ParseLine().
InitDialog()
void DramaEventTalk.InitDialog () inline
Definition at line 161 of file DramaEventTalk.cs.
    {
        if (idActor == "*")
        {
            base.manager.SetDialog("Mono");
        }
        if (idActor == "*2")
        {
            base.manager.SetDialog("Default2");
        }
        base.manager.imageBG.color = ((idActor == "*") ? new Color(0.6f, 0.6f, 0.6f) : Color.white);
    }
References Color, and DramaEvent.idActor.
Referenced by Play().
Play()
override bool DramaEventTalk.Play () inline virtual
Reimplemented from DramaEvent.
Definition at line 60 of file DramaEventTalk.cs.
    {
        if (progress == 0)
        {
            InitDialog();
            if (sequence.firstTalk == null)
            {
                sequence.firstTalk = this;
            }
            timer = 0f;
            sequence.dialog.SetActive(enable: true);
            base.actor.Talk(sequence.message + ((funcText != null) ? funcText() : text), choices, center, unknown);
            sequence.message = "";
            progress++;
        }
        else
        {
            timer += Time.deltaTime;
            if (timer < 0.08f)
            {
                return false;
            }
            if (canCancel && (EInput.rightMouse.down || Input.GetKeyDown(KeyCode.Escape) || Input.GetKeyDown(KeyCode.LeftShift)))
            {
                ResetDialog();
                if (temp)
                {
                    sequence.tempEvents.Clear();
                }
                EClass.Sound.Play("click_chat");
                if (idCancelJump == "back")
                {
                    return true;
                }
                if (idCancelJump.IsEmpty())
                {
                    sequence.Exit();
                }
                else
                {
                    sequence.Play(idCancelJump);
                }
                return false;
            }
            int num = 0;
            foreach (DramaChoice choice in choices)
            {
                if (choice.activeCondition != null && !choice.activeCondition())
                {
                    continue;
                }
                string inputString = Input.inputString;
                if ((bool)choice.button && inputString == ((num + 1).ToString() ?? ""))
                {
                    if ((bool)choice.button.soundClick)
                    {
                        SoundManager.current.Play(choice.button.soundClick);
                    }
                    choice.button.onClick.Invoke();
                    return false;
                }
                num++;
            }
            if (num == 0 && (EInput.leftMouse.down || EInput.rightMouse.down || Input.GetKeyDown(KeyCode.KeypadEnter) || Input.GetKey(KeyCode.LeftControl) || EInput.action == EAction.Confirm || EInput.action == EAction.Wait || Input.GetKeyDown(KeyCode.Return) || Input.GetKeyDown(KeyCode.Escape)))
            {
                ResetDialog();
                if (EClass.ui.GetTopLayer() == base.layer)
                {
                    Typewriter typewriter = sequence.dialog.textMain.typewriter;
                    if ((bool)typewriter && !typewriter.IsFinished)
                    {
                        typewriter.Skip();
                        return false;
                    }
                    base.actor.gameObject.SetActive(value: false);
                    EClass.Sound.Play("click_chat");
                    if (temp)
                    {
                        sequence.tempEvents.Clear();
                        if (!idJump.IsEmpty())
{
                            sequence.Play(idJump);
                            return false;
                        }
                        return true;
                    }
                    if (idJump.IsEmpty())
                    {
                        sequence.PlayNext();
                    }
                    else
                    {
                        sequence.Play(idJump);
                    }
                    return false;
                }
            }
        }
        return false;
    }
References EInput.action, DramaChoice.activeCondition, DramaChoice.button, canCancel, center, choices, DramaSequence.dialog, ButtonState.down, DramaSequence.Exit(), DramaSequence.firstTalk, funcText, idCancelJump, DramaEvent.idJump, InitDialog(), Typewriter.IsFinished, EInput.leftMouse, DramaSequence.message, DramaSequence.Play(), DramaSequence.PlayNext(), DramaEvent.progress, ResetDialog(), EInput.rightMouse, DramaEvent.sequence, Typewriter.Skip(), EClass.Sound, UIButton.soundClick, DramaEvent.temp, DramaSequence.tempEvents, text, DialogDrama.textMain, timer, UIText.typewriter, EClass.ui, and unknown.
ResetDialog()
void DramaEventTalk.ResetDialog () inline
Definition at line 174 of file DramaEventTalk.cs.
    {
        base.manager.imageBG.color = Color.white;
        if (idActor == "*" || idActor == "*2")
        {
            base.manager.SetDialog();
        }
    }
References Color, and DramaEvent.idActor.
Referenced by Play().
Member Data Documentation
canCancel
bool DramaEventTalk.canCancel
Definition at line 15 of file DramaEventTalk.cs.
Referenced by Play().
center
bool DramaEventTalk.center
Definition at line 13 of file DramaEventTalk.cs.
Referenced by Play().
choices
List<DramaChoice> DramaEventTalk.choices = new List<DramaChoice>()
Definition at line 11 of file DramaEventTalk.cs.
Referenced by AddChoice(), and Play().
funcText
Func<string> DramaEventTalk.funcText
Definition at line 21 of file DramaEventTalk.cs.
Referenced by DramaEventTalk(), and Play().
idCancelJump
string DramaEventTalk.idCancelJump
Definition at line 9 of file DramaEventTalk.cs.
Referenced by Play().
text
string DramaEventTalk.text
Definition at line 7 of file DramaEventTalk.cs.
Referenced by DramaEventTalk(), and Play().
timer
float DramaEventTalk.timer
Definition at line 19 of file DramaEventTalk.cs.
Referenced by Play().
unknown
bool DramaEventTalk.unknown
Definition at line 17 of file DramaEventTalk.cs.
Referenced by DramaEventTalk(), and Play().
The documentation for this class was generated from the following file:
Elin/DramaEventTalk.cs