Elin Decompiled Documentation: PointList Class Reference
PointList Class Reference
Public Member Functions
void Deserialize ()
Public Attributes
int[] data
Private Member Functions
void OnSerializing (StreamingContext context)
void OnDeserialized (StreamingContext context)
Detailed Description
Definition at line 6 of file PointList.cs.
Member Function Documentation
Deserialize()
void PointList.Deserialize () inline
Definition at line 32 of file PointList.cs.
    {
        base.Capacity = data.Length / 2 + 8;
        for (int i = 0; i < data.Length / 2; i++)
        {
            Add(new Point(data[i * 2], data[i * 2 + 1]));
        }
    }
References Add(), and data.
Referenced by OnDeserialized().
OnDeserialized()
void PointList.OnDeserialized (StreamingContext context) inline private
Definition at line 27 of file PointList.cs.
    {
        Deserialize();
    }
References Deserialize().
OnSerializing()
void PointList.OnSerializing (StreamingContext context) inline private
Definition at line 12 of file PointList.cs.
    {
        data = new int[base.Count * 2];
        int num = 0;
        using Enumerator enumerator = GetEnumerator();
        while (enumerator.MoveNext())
        {
            Point current = enumerator.Current;
            data[num] = current.x;
            data[num + 1] = current.z;
            num += 2;
        }
    }
References data, Point.x, and Point.z.
Member Data Documentation
data
int [] PointList.data
Definition at line 9 of file PointList.cs.
Referenced by Deserialize(), and OnSerializing().
The documentation for this class was generated from the following file:
Elin/PointList.cs