Elin Decompiled Documentation: PolicyManager Class Reference
PolicyManager Class Reference
Public Member Functions
void SetOwner (FactionBranch _owner)
void AddPolicy (string id)
Policy AddPolicy (int id, bool show=true)
void Activate (int id)
void SetActive (int id, bool active)
bool IsActive (int id, int days=-1)
bool HasPolicy (int id)
void OnSimulateHour (VirtualDate date)
int GetValue (int id)
int CurrentAP ()
void RefreshEffects ()
void Validate ()
Public Attributes
List< Policy > list = new List<Policy>()
FactionBranch owner
Additional Inherited Members
Static Public Member Functions inherited from EClass
static int rnd (int a)
static int curve (int a, int start, int step, int rate=75)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Static Public Attributes inherited from EClass
static Core core
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Detailed Description
Definition at line 4 of file PolicyManager.cs.
Member Function Documentation
Activate()
void PolicyManager.Activate (int id) inline
Definition at line 49 of file PolicyManager.cs.
    {
        foreach (Policy item in list)
        {
            if (item.id == id)
            {
                item.active = true;
            }
        }
    }
References Policy.id, and list.
Referenced by FactionBranch.OnClaimZone().
AddPolicy() [1/2]
Policy PolicyManager.AddPolicy (int id, bool show = true) inline
Definition at line 26 of file PolicyManager.cs.
    {
        if (owner.elements.GetElement(id) == null)
        {
            owner.elements.SetBase(id, 1);
        }
        Policy policy = new Policy
        {
            id = id
        };
        policy.SetOwner(owner);
        list.Add(policy);
        if (show)
        {
            WidgetPopText.Say("rewardPolicy".lang(EClass.sources.elements.map[id].GetName()));
        }
        if (policy.source.tag.Contains("globalPolicy"))
        {
            EClass.pc.faction.AddGlobalPolicy(policy.id);
        }
        return policy;
    }
References Faction.AddGlobalPolicy(), FactionBranch.elements, SourceManager.elements, Chara.faction, ElementContainer.GetElement(), Policy.id, list, owner, EClass.pc, WidgetPopText.Say(), ElementContainer.SetBase(), Policy.SetOwner(), Policy.source, and EClass.sources.
AddPolicy() [2/2]
void PolicyManager.AddPolicy (string id) inline
Definition at line 21 of file PolicyManager.cs.
    {
        AddPolicy(EClass.sources.elements.alias[id].id);
    }
References AddPolicy(), SourceManager.elements, and EClass.sources.
Referenced by AddPolicy(), FactionBranch.OnClaimZone(), TraitBookSkill.OnRead(), ResearchPlan.ParseReward(), and FactionBranch.ValidateUpgradePolicies().
CurrentAP()
int PolicyManager.CurrentAP () inline
Definition at line 126 of file PolicyManager.cs.
    {
        int num = 0;
        foreach (Policy item in list)
        {
            if (item.active)
            {
                num += item.Cost;
            }
        }
        return num;
    }
References Policy.active, Policy.Cost, and list.
Referenced by UICurrency.Build(), ContentPolicy.RefreshPolicyIcons(), LayerPolicy.RefreshPolicyIcons(), and LayerPolicy.RefreshPolicyList().
GetValue()
int PolicyManager.GetValue (int id) inline
Definition at line 114 of file PolicyManager.cs.
    {
        foreach (Policy item in list)
        {
            if (item.id == id && item.active)
            {
                return item.Ele.Value;
            }
        }
        return 0;
    }
References Policy.active, Policy.Ele, Policy.id, list, and Element.Value.
Referenced by FactionBranch.Evalue().
HasPolicy()
bool PolicyManager.HasPolicy (int id) inline
Definition at line 83 of file PolicyManager.cs.
    {
        foreach (Policy item in list)
        {
            if (item.id == id)
            {
                return true;
            }
        }
        return false;
    }
References Policy.id, and list.
Referenced by TraitBookSkill.OnRead(), and FactionBranch.ValidateUpgradePolicies().
IsActive()
bool PolicyManager.IsActive (int id, int days = -1) inline
Definition at line 71 of file PolicyManager.cs.
    {
        foreach (Policy item in list)
        {
            if (item.active && item.id == id && (days == -1 || item.days >= days))
            {
                return true;
            }
        }
        return false;
    }
References Policy.active, Policy.days, Policy.id, and list.
Referenced by FactionBranch.CalcInnIncome(), FactionBranch.CalcTourismIncome(), Faction.CountTaxFreeLand(), Card.GetPrice(), HomeResourceWorth.GetPrice(), FactionBranch.GetResidentTax(), Zone.GrowPlants(), Faction.IsGlobalPolicyActive(), FactionBranch.ModExp(), Faction.OnAdvanceMonth(), AI_Idle.Run(), GameDate.ShipRandomPackages(), and AI_Shopping.TryShop().
OnSimulateHour()
void PolicyManager.OnSimulateHour (VirtualDate date) inline
Definition at line 95 of file PolicyManager.cs.
    {
        foreach (Policy item in list)
        {
            if (item.active)
            {
                item.OnAdvanceHour(date);
                if (date.hour == 0)
                {
                    item.days++;
                }
            }
            else
            {
                item.days = 0;
            }
        }
    }
References Policy.active, Policy.days, list, and Policy.OnAdvanceHour().
RefreshEffects()
void PolicyManager.RefreshEffects () inline
Definition at line 139 of file PolicyManager.cs.
    {
        foreach (Happiness item in owner.happiness.list)
        {
            item.OnRefreshEffect();
        }
        foreach (BaseHomeResource item2 in owner.resources.list)
        {
            item2.OnRefreshEffect();
        }
        foreach (Policy item3 in list)
        {
            if (item3.active)
            {
                item3.RefreshEffect();
            }
        }
        owner.resources.SetDirty();
    }
References Policy.active, FactionBranch.happiness, HappinessManager.list, HomeResourceManager.list, list, BaseHomeResource.OnRefreshEffect(), Happiness.OnRefreshEffect(), owner, Policy.RefreshEffect(), FactionBranch.resources, and HomeResourceManager.SetDirty().
Referenced by ContentPolicy.RefreshPolicyList(), and SetOwner().
SetActive()
void PolicyManager.SetActive (int id, bool active) inline
Definition at line 60 of file PolicyManager.cs.
    {
        foreach (Policy item in list)
        {
            if (item.id == id)
            {
                item.active = active;
            }
        }
    }
References Policy.id, and list.
Referenced by Faction.SetGlobalPolicyActive().
SetOwner()
void PolicyManager.SetOwner (FactionBranch _owner) inline
Definition at line 11 of file PolicyManager.cs.
    {
        owner = _owner;
        foreach (Policy item in list)
        {
            item.SetOwner(owner);
        }
        RefreshEffects();
    }
References list, owner, RefreshEffects(), and Policy.SetOwner().
Referenced by FactionBranch.SetOwner().
Validate()
void PolicyManager.Validate () inline
Definition at line 159 of file PolicyManager.cs.
    {
    }
Referenced by Party.AddMemeber(), FactionBranch.ChangeMemberType(), Chara.MoveHome(), ContentPolicy.OnSwitchContent(), and FactionBranch.RemoveMemeber().
Member Data Documentation
list
List<Policy> PolicyManager.list = new List<Policy>()
Definition at line 7 of file PolicyManager.cs.
Referenced by Activate(), AddPolicy(), CurrentAP(), Happiness.GetTargetValue(), GetValue(), HasPolicy(), IsActive(), OnSimulateHour(), RefreshEffects(), ContentPolicy.RefreshPolicyList(), LayerPolicy.RefreshPolicyList(), SetActive(), and SetOwner().
owner
FactionBranch PolicyManager.owner
Definition at line 9 of file PolicyManager.cs.
Referenced by AddPolicy(), RefreshEffects(), and SetOwner().
The documentation for this class was generated from the following file:
Elin/PolicyManager.cs