Elin Decompiled Documentation: ZonePreEnterEncounter Class Reference
ZonePreEnterEncounter Class Reference
Public Member Functions
override void Execute ()
virtual void Execute ()
Public Attributes
int enemies
int roadDist
Chara mob
Additional Inherited Members
Static Public Member Functions inherited from EClass
static int rndSeed (int a, int seed)
static int rnd (long a)
static int rnd (int a)
static int curve (int a, int start, int step, int rate=75)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Static Public Attributes inherited from EClass
static Core core
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Detailed Description
Definition at line 5 of file ZonePreEnterEncounter.cs.
Member Function Documentation
Execute()
override void ZonePreEnterEncounter.Execute () inline virtual
Reimplemented from ZonePreEnterEvent.
Definition at line 13 of file ZonePreEnterEncounter.cs.
    {
        bool flag = EClass.pc.HasCondition<ConDrawMetal>();
        int lv = Mathf.Max(EClass._zone.DangerLv, EClass.pc.FameLv * Math.Min(roadDist * 20, 100) / 100);
        if (mob != null)
        {
            List<Chara> list = new List<Chara>();
            Chara leader = null;
            float num = Mathf.Clamp(EClass.pc.FameLv + 8, 8f, 24f + Mathf.Sqrt(EClass.pc.FameLv));
            for (int i = 0; i < EClass.rndHalf((int)num); i++)
            {
                Point randomPointInRadius = EClass.pc.pos.GetRandomPointInRadius(2, 5, requireLos: false, allowChara: false);
                if (randomPointInRadius != null)
                {
                    Chara chara = EClass._zone.SpawnMob(randomPointInRadius, SpawnSetting.Mob(mob.id, (mob.MainElement == Element.Void) ? null : mob.MainElement.source.alias.Substring(3)));
                    Hostility hostility2 = (chara.c_originalHostility = Hostility.Enemy);
                    chara.hostility = hostility2;
                    chara.enemy = EClass.pc.party.members.RandomItem();
                    leader = chara;
                    if (EClass.rnd(5) == 0)
                    {
                        TraitFoodEggFertilized.MakeBaby(chara, 1);
                    }
                    list.Add(chara);
                }
            }
            if (leader != null)
            {
                List<Thing> list2 = EClass.pc.things.List(delegate(Thing t)
                {
                    if (t.Num >= 10)
                    {
                        return false;
                    }
                    return t.trait.CanBeDestroyed && t.things.Count == 0 && t.invY != 1 && t.trait.CanBeStolen && !t.trait.CanOnlyCarry && !t.IsUnique && !t.isEquipped;
                }, onlyAccessible: true);
                Thing t2 = ((list2.Count > 0) ? list2.RandomItem() : null);
                if (t2 == null)
                {
                    GameLang.refDrama1 = (GameLang.refDrama2 = "mobPity".lang());
                }
                else
                {
                    GameLang.refDrama1 = t2.NameSimple;
                    GameLang.refDrama2 = t2.Name;
                }
                LayerDrama.refAction1 = delegate
                {
                    foreach (Chara item in list)
                    {
                        item.ShowEmo(Emo.angry);
                        if (EClass.rnd(6) == 0)
{
                            item.Talk((EClass.rnd(5) == 0) ? "rumor_bad" : ((EClass.rnd(5) == 0) ? "callGuards" : "disgust"));
                        }
                    }
                };
                LayerDrama.refAction2 = delegate
                {
                    if (t2 != null)
                    {
                        leader.AddCard(t2);
                    }
                    foreach (Chara item2 in list)
                    {
                        if (EClass.rnd(6) == 0)
{
                            item2.Talk((EClass.rnd(5) == 0) ? "rumor_good" : ((EClass.rnd(3) == 0) ? "thanks3" : "thanks"));
                        }
                        item2.ShowEmo(Emo.happy);
                        Hostility hostility5 = (item2.c_originalHostility = Hostility.Neutral);
                        item2.hostility = hostility5;
                        item2.enemy = null;
                    }
                    EClass.player.ModKarma(1);
                };
                leader.ShowDialog("_chara", "encounter_mob");
            }
        }
        else
        {
            for (int j = 0; j < enemies; j++)
            {
                Point nearestPoint = (EClass.pc.pos.GetRandomPoint(4) ?? EClass.pc.pos).GetNearestPoint(allowBlock: false, allowChara: false);
                Chara chara2 = EClass._zone.SpawnMob(nearestPoint, SpawnSetting.Encounter(lv));
                Hostility hostility2 = (chara2.c_originalHostility = Hostility.Enemy);
                chara2.hostility = hostility2;
                chara2.enemy = EClass.pc.party.members.RandomItem();
            }
        }
        if (flag && EClass.rnd(EClass.debug.enable ? 1 : 3) == 0)
        {
            Point nearestPoint2 = (EClass.pc.pos.GetRandomPoint(4) ?? EClass.pc.pos).GetNearestPoint(allowBlock: false, allowChara: false);
            SpawnList list3 = SpawnListChara.Get("c_metal", (SourceChara.Row s) => s.race == "metal");
            EClass._zone.AddCard(CharaGen.CreateFromFilter(list3, EClass._zone.DangerLv), nearestPoint2);
        }
        if ((EClass._zone.Tile.isRoad || EClass._zone.Tile.IsNeighborRoad) && EClass.rnd(2) == 0)
        {
            Point nearestPoint3 = (EClass.pc.pos.GetRandomPoint(4) ?? EClass.pc.pos).GetNearestPoint(allowBlock: false, allowChara: false);
            EClass._zone.AddCard(CharaGen.Create("guard"), nearestPoint3);
        }
    }
References EClass._zone, Card.AddCard(), Zone.AddCard(), CharaGen.Create(), CharaGen.CreateFromFilter(), Zone.DangerLv, EClass.debug, CoreDebug.enable, SpawnSetting.Encounter(), enemies, Card.FameLv, SpawnListChara.Get(), Point.GetRandomPoint(), Point.GetRandomPointInRadius(), Chara.HasCondition(), Card.id, Thing.isEquipped, item, ThingContainer.List(), Chara.MainElement, TraitFoodEggFertilized.MakeBaby(), Party.members, SpawnSetting.Mob(), mob, Player.ModKarma(), Card.Name, Card.NameSimple, Card.Num, Chara.party, EClass.pc, EClass.player, Card.pos, EClass.rnd(), EClass.rndHalf(), roadDist, Chara.ShowDialog(), Card.ShowEmo(), Element.source, Zone.SpawnMob(), Card.Talk(), Card.things, Spatial.Tile, and Element.Void.
Member Data Documentation
enemies
int ZonePreEnterEncounter.enemies
Definition at line 7 of file ZonePreEnterEncounter.cs.
Referenced by Execute().
mob
Chara ZonePreEnterEncounter.mob
Definition at line 11 of file ZonePreEnterEncounter.cs.
Referenced by Execute().
roadDist
int ZonePreEnterEncounter.roadDist
Definition at line 9 of file ZonePreEnterEncounter.cs.
Referenced by Execute().
The documentation for this class was generated from the following file:
Elin/ZonePreEnterEncounter.cs