Elin Decompiled Documentation: Anime Class Reference
Anime Class Reference
Public Member Functions
virtual Tween Play (Transform trans, UnityAction onComplete=null, float duration=-1f, float delay=0f)
Detailed Description
Definition at line 5 of file Anime.cs.
Member Function Documentation
Play()
virtual Tween Anime.Play (Transform trans, UnityAction onComplete = null, float duration = -1f, float delay = 0f) inline virtual
Reimplemented in AnimeTween.
Definition at line 7 of file Anime.cs.
    {
        return null;
    }
Referenced by WidgetSticky._Add(), Layer.Close(), PopfabItem.ForceOutro(), Layer.Init(), PopfabItem.Intro(), UIButton.OnPointerDown(), PopfabItem.Outro(), AnimeItem.Play(), UIFactionInfo.SetFaction(), UIFactionInfo.SetReligion(), ActionHint.SetText(), and LayerArea.ShowPage().
The documentation for this class was generated from the following file:
Elin/Plugins.UI/Anime.cs