Elin Decompiled Documentation: LayerPeople Class Reference
LayerPeople Class Reference
Public Types
enum Mode { Default , Select , Double , Hire }
enum ShowMode { Job , Race , Work }
Public Member Functions
override bool HeaderIsListOf (int id)
override void OnInit ()
LayerPeople SetOnConfirm (Action _onConfirm)
void Confirm ()
override void OnKill ()
override void OnSwitchContent (Window window)
Public Member Functions inherited from ELayer
override void OnBeforeAddLayer ()
void InitInspector ()
sealed override void Init ()
override void OnAfterAddLayer ()
void TryShowHelp ()
void AddLayerToUI (string id)
void TryShowHint (string _langHint=null)
void TalkHomeMemeber (string id)
void TalkMaid (string id)
override void OnRightClick ()
Public Member Functions inherited from Layer
virtual string GetTextHeader (Window window)
virtual bool HeaderIsListOf (int id)
virtual void Init ()
virtual void OnInit ()
virtual void OnAfterInit ()
virtual void ApplySkin ()
void ShowScreenLock (string id)
void UpdateInput ()
virtual void OnUpdateInput ()
virtual void OnRightClick ()
virtual bool OnBack ()
virtual void OnChangeLayer ()
virtual void OnCreate ()
void _AddLayer (string id)
Layer AddLayer (string id)
T AddLayer< T > ()
T AddLayer< T > (string id)
T AddLayerDontCloseOthers< T > ()
Layer AddLayerDontCloseOthers (Layer l)
T GetOrAddLayer< T > ()
virtual void OnBeforeAddLayer ()
virtual void OnAfterAddLayer ()
Layer AddLayer (Layer l)
void ToggleLayer (string id)
T ToggleLayer< T > (string id=null)
void WaitAndClose ()
void OnClickClose ()
virtual void Close ()
void CloseLayers ()
void RemoveLayers (bool removeImportant=false)
bool RemoveLayer< T > ()
void RemoveLayer (Layer l)
virtual void OnKill ()
Layer SetOnKill (Action action)
void DisableClose ()
void Delay (float duration=0.05f)
Layer SetDelay (float d)
Layer GetLayer (string id)
T GetLayer< T > (bool fromTop=false)
Layer GetTopLayer ()
void SwitchContent (int idWindow, int i)
virtual void OnSwitchContent (Window window)
Layer SetTitles (string langList, string idHeaderRow=null)
bool IsBlockWidgetClick ()
bool IsHideHud ()
bool IsAllowGeneralInput ()
bool IsUseBlur ()
bool IsPointerOnLayer ()
void ApplySkin ()
Static Public Member Functions
static LayerPeople Create (Mode mode)
static LayerPeople Create< T > (string langHint=null, Chara owner=null)
static LayerPeople CreateReserve ()
static LayerPeople CreateBed (TraitBed bed)
static LayerPeople CreateSelectEmbarkMembers (List< Chara > settlers)
static LayerPeople Create (BaseListPeople list)
static LayerPeople CreateSelect (string langHeader, string langHint, Action< UIList > onList, Action< Chara > onClick, Func< Chara, string > _onShowSubText=null)
Static Public Member Functions inherited from ELayer
static int rnd (int a)
Static Public Member Functions inherited from Layer
static T Create< T > ()
static T Create< T > (string path)
static Layer Create (string path)
Public Attributes
ShowMode showMode
LayoutGroup layoutMenu
Action onConfirm
UIMultiList multi
Public Attributes inherited from Layer
Option option
UnityEvent onKill
Anime animeIn
Anime animeOut
bool closeOthers
bool defaultActionMode = true
Button screenLock
Layer parent
string idLayer
List< Layer > layers = new List<Layer>()
Vector2 lastParentPos
List< Window > windows = new List<Window>()
string langHint
Static Public Attributes
static Chara slaveToBuy
Static Public Attributes inherited from Layer
static int skipInput
static bool closeOnRightClick
static bool rightClicked
static bool cancelKeyDown
static bool ignoreSounds
static Transform blurStopInstance
static string[] searchPath = new string[3] { "Layer", "Layer/Dialog", "Layer/LayerHome" }
Additional Inherited Members
Protected Member Functions inherited from ELayer
sealed override void _Close ()
sealed override void Kill ()
Protected Member Functions inherited from Layer
virtual void Awake ()
virtual void _Close ()
virtual void Kill ()
Protected Attributes inherited from Layer
RectTransform _rect
bool isDestroyed
Properties inherited from ELayer
static Core core [get]
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static FactionBranch Branch [get]
static Faction Home [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static CoreConfig config [get]
static GameSetting setting [get]
static ColorProfile Colors [get]
static SourceManager sources [get]
static World world [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
bool IsFloat [get]
virtual string IdHelp [get]
Properties inherited from Layer
Layer TopLayer [get]
string uid [get]
virtual RectTransform rectLayers [get]
virtual bool blockWidgetClick [get]
Detailed Description
Definition at line 5 of file LayerPeople.cs.
Member Enumeration Documentation
Mode
enum LayerPeople.Mode
Enumerator
Default
Select
Double
Hire
Definition at line 7 of file LayerPeople.cs.
    {
        Default,
        Select,
        Double,
        Hire
    }
ShowMode
enum LayerPeople.ShowMode
Enumerator
Job
Race
Work
Definition at line 15 of file LayerPeople.cs.
    {
        Job,
        Race,
        Work
    }
Member Function Documentation
Confirm()
void LayerPeople.Confirm () inline
Definition at line 66 of file LayerPeople.cs.
    {
        if (onConfirm != null)
        {
            onConfirm();
        }
        Close();
    }
References Layer.Close(), and onConfirm.
Create() [1/2]
static LayerPeople LayerPeople.Create (BaseListPeople list) inline static
Definition at line 169 of file LayerPeople.cs.
    {
        LayerPeople layerPeople = Create(Mode.Select);
        layerPeople.multi.AddOwner(0, list);
        return layerPeople;
    }
References UIMultiList.AddOwner(), Create(), and multi.
Create() [2/2]
static LayerPeople LayerPeople.Create (Mode mode) inline static
Definition at line 94 of file LayerPeople.cs.
    {
        string path = "LayerPeople";
        if (mode == Mode.Double)
        {
            path = "LayerPeople/LayerPeopleDouble";
        }
        return Layer.Create(path) as LayerPeople;
    }
References Layer.Create().
Referenced by Create(), Create< T >(), CreateBed(), CreateReserve(), CreateSelect(), and CreateSelectEmbarkMembers().
Create< T >()
static LayerPeople LayerPeople.Create< T > (string langHint = null, Chara owner = null) inline static
Type Constraints
T : BaseListPeople
Definition at line 104 of file LayerPeople.cs.
                                                                                            : BaseListPeople
    {
        LayerPeople layerPeople = Create(Mode.Select);
        T o = new T
        {
            owner = owner
        };
        layerPeople.multi.AddOwner(0, o);
        layerPeople.langHint = langHint;
        return layerPeople;
    }
References UIMultiList.AddOwner(), Create(), Layer.langHint, and multi.
CreateBed()
static LayerPeople LayerPeople.CreateBed (TraitBed bed) inline static
Definition at line 128 of file LayerPeople.cs.
    {
        LayerPeople layerPeople = Create(Mode.Double);
        layerPeople.multi.AddOwner(0, new ListPeopleBed
        {
            textHeader = "candidates",
            bed = bed
        });
        layerPeople.multi.AddOwner(1, new ListPeopleBed
        {
            textHeader = "listBedHolder".lang(bed.MaxHolders.ToString() ?? ""),
            bed = bed
        });
        ELayer.ui.AddLayer(layerPeople);
        return layerPeople;
    }
References UIMultiList.AddOwner(), bed, Create(), multi, and ELayer.ui.
Referenced by TraitBed.TrySetAct().
CreateReserve()
static LayerPeople LayerPeople.CreateReserve () inline static
Definition at line 116 of file LayerPeople.cs.
    {
        LayerPeople layerPeople = Create(Mode.Hire);
        layerPeople.multi.AddOwner(0, new ListPeopleCallReserve
        {
            textHeader = "actCallReserve"
        });
        layerPeople.langHint = "h_reserve";
        ELayer.ui.AddLayer(layerPeople);
        return layerPeople;
    }
References UIMultiList.AddOwner(), Create(), multi, and ELayer.ui.
Referenced by TraitCoreZone.TrySetAct().
CreateSelect()
static LayerPeople LayerPeople.CreateSelect (string langHeader, string langHint, Action< UIList > onList, Action< Chara > onClick, Func< Chara, string > _onShowSubText = null) inline static
Definition at line 176 of file LayerPeople.cs.
    {
        LayerPeople layerPeople = Create(Mode.Select);
        layerPeople.multi.AddOwner(0, new ListPeopleSelect
        {
            textHeader = langHeader,
            onList = onList,
            onClick = onClick,
            onShowSubText = _onShowSubText
        });
        layerPeople.langHint = langHint;
        ELayer.ui.AddLayer(layerPeople);
        return layerPeople;
    }
References UIMultiList.AddOwner(), Create(), Layer.langHint, multi, and ELayer.ui.
Referenced by TraitGeneMachine.OnUse(), and TraitGeneratorWheel.OnUse().
CreateSelectEmbarkMembers()
static LayerPeople LayerPeople.CreateSelectEmbarkMembers (List< Chara > settlers) inline static
Definition at line 145 of file LayerPeople.cs.
    {
        LayerPeople layerPeople = Create(Mode.Double);
        List<Chara> list = new List<Chara>();
        foreach (Chara chara in ELayer.game.lastActiveZone.map.charas)
        {
            if (chara.IsHomeMember())
            {
                list.Add(chara);
            }
        }
        layerPeople.multi.AddOwner(0, new ListPeopleEmbark
        {
            textHeader = "candidates",
            charas = list
        });
        layerPeople.multi.AddOwner(1, new ListPeopleEmbark
        {
            textHeader = "listEmbark",
            charas = settlers
        });
        return layerPeople;
    }
References Map.charas, Create(), ELayer.game, Chara.IsHomeMember(), Game.lastActiveZone, and Zone.map.
Referenced by LayerNewZone.OnClickSelectMembers().
HeaderIsListOf()
override bool LayerPeople.HeaderIsListOf (int id) inline virtual
Reimplemented from Layer.
Definition at line 32 of file LayerPeople.cs.
    {
        return true;
    }
OnInit()
override void LayerPeople.OnInit () inline virtual
Reimplemented from Layer.
Definition at line 37 of file LayerPeople.cs.
    {
        showMode = ELayer.player.pref.modePoeple;
        if (multi.owners.Count == 0)
        {
            multi.AddOwner(0, new ListPeople
            {
                memberType = FactionMemberType.Default
            });
            multi.AddOwner(0, new ListPeople
            {
                memberType = FactionMemberType.Livestock
            });
            multi.AddOwner(0, new ListPeople
            {
                memberType = FactionMemberType.Guest
            });
            langHint = "h_residents";
        }
        multi.Build(ELayer.player.pref.sortPeople);
        multi.owners[0].menu = new WindowMenu(layoutMenu);
    }
References UIMultiList.AddOwner(), UIMultiList.Build(), Layer.langHint, layoutMenu, Player.Pref.modePoeple, multi, UIMultiList.owners, ELayer.player, Player.pref, showMode, and Player.Pref.sortPeople.
OnKill()
override void LayerPeople.OnKill () inline virtual
Reimplemented from Layer.
Definition at line 75 of file LayerPeople.cs.
    {
        ELayer.player.pref.sortPeople = multi.owners[0].list.sortMode;
        ELayer.player.pref.modePoeple = showMode;
        ELayer.scene.screenElin.focusOption = null;
    }
References multi, UIMultiList.owners, and showMode.
OnSwitchContent()
override void LayerPeople.OnSwitchContent (Window window) inline virtual
Reimplemented from Layer.
Definition at line 82 of file LayerPeople.cs.
    {
        if (multi.Double)
        {
            multi.owners[window.windowIndex].OnSwitchContent();
        }
        else
        {
            multi.owners[window.idTab].OnSwitchContent();
        }
    }
References UIMultiList.Double, Window.idTab, multi, UIMultiList.owners, and Window.windowIndex.
Referenced by BaseListPeople.OnClick().
SetOnConfirm()
LayerPeople LayerPeople.SetOnConfirm (Action _onConfirm) inline
Definition at line 60 of file LayerPeople.cs.
    {
        onConfirm = _onConfirm;
        return this;
    }
References onConfirm.
Referenced by LayerNewZone.OnClickSelectMembers().
Member Data Documentation
layoutMenu
LayoutGroup LayerPeople.layoutMenu
Definition at line 26 of file LayerPeople.cs.
Referenced by OnInit().
multi
UIMultiList LayerPeople.multi
Definition at line 30 of file LayerPeople.cs.
Referenced by Create(), Create< T >(), CreateBed(), CreateReserve(), CreateSelect(), BaseListPeople.OnClick(), OnInit(), OnKill(), and OnSwitchContent().
onConfirm
Action LayerPeople.onConfirm
Definition at line 28 of file LayerPeople.cs.
Referenced by Confirm(), and SetOnConfirm().
showMode
ShowMode LayerPeople.showMode
Definition at line 24 of file LayerPeople.cs.
Referenced by OnInit(), OnKill(), and BaseListPeople.OnRefreshMenu().
slaveToBuy
Chara LayerPeople.slaveToBuy static
Definition at line 22 of file LayerPeople.cs.
The documentation for this class was generated from the following file:
Elin/LayerPeople.cs