Elin Decompiled Documentation: ListPeopleCallReserve Class Reference
ListPeopleCallReserve Class Reference
Public Member Functions
override void OnInstantiate (Chara a, ItemGeneral b)
override void OnClick (Chara c, ItemGeneral i)
override void OnList ()
HireInfo GetInfo (Chara c)
Public Member Functions inherited from BaseListPeople
virtual bool IsDisabled (Chara c)
override void List ()
override void OnInstantiate (Chara a, ItemGeneral b)
virtual void SetSubText (Chara a, ItemGeneral b)
override void OnClick (Chara c, ItemGeneral i)
override void OnList ()
override void OnRefreshMenu ()
Public Member Functions inherited from ListOwner< Chara, ItemGeneral >
virtual void OnClick (T1 a, T2 b)
virtual void OnInstantiate (T1 a, T2 b)
virtual void OnList ()
virtual void List ()
virtual void OnCreate ()
virtual void OnSwitchContent ()
virtual void OnRefreshMenu ()
void MoveToOther (object c)
Public Attributes
bool skipDialog
Public Attributes inherited from BaseListPeople
Chara owner
FactionMemberType memberType
Public Attributes inherited from ListOwner< Chara, ItemGeneral >
Layer layer
Window window
UIMultiList multi
ListOwner other
UIList list
WindowMenu menu
string textTab
string textHeader
bool main
int index
Additional Inherited Members
Static Public Member Functions inherited from EClass
static int rnd (int a)
static int curve (int a, int start, int step, int rate=75)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Static Public Attributes inherited from EClass
static Core core
Properties inherited from BaseListPeople
new LayerPeople layer [get]
override string IdHeaderRow [get]
virtual bool ShowCharaSheet [get]
virtual bool ShowShowMode [get]
virtual LayerPeople.ShowMode ShowMode [get]
virtual bool ShowGoto [get]
virtual bool ShowHome [get]
Properties inherited from ListOwner< Chara, ItemGeneral >
ListOwner Main [get]
virtual string IdTitle [get]
virtual string IdHeaderRow [get]
virtual string TextTab [get]
virtual string TextHeader [get]
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Detailed Description
Definition at line 4 of file ListPeopleCallReserve.cs.
Member Function Documentation
GetInfo()
HireInfo ListPeopleCallReserve.GetInfo (Chara c) inline
Definition at line 63 of file ListPeopleCallReserve.cs.
    {
        return EClass.Home.listReserve.First((HireInfo a) => a.chara == c);
    }
References HireInfo.chara, EClass.Home, and Faction.listReserve.
OnClick()
override void ListPeopleCallReserve.OnClick (Chara c, ItemGeneral i) inline
Definition at line 47 of file ListPeopleCallReserve.cs.
    {
        BaseCore.Instance.FreezeScreen(0.1f);
        EClass.Branch.Recruit(c);
        EClass.Sound.Play("good");
        list.List();
    }
References EClass.Branch, BaseCore.FreezeScreen(), BaseCore.Instance, FactionBranch.Recruit(), and EClass.Sound.
OnInstantiate()
override void ListPeopleCallReserve.OnInstantiate (Chara a, ItemGeneral b) inline
Definition at line 8 of file ListPeopleCallReserve.cs.
    {
        b.SetSubText(a.job.GetName().ToTitleCase(), 280);
        if (!a.trait.CanBeBanished)
        {
            return;
        }
        b.AddSubButton(EClass.core.refs.icons.trash, delegate
        {
            Action func = delegate
            {
                EClass.Home.RemoveReserve(a);
                a.OnBanish();
                list.List();
                SE.Trash();
            };
            if (skipDialog)
            {
                func();
            }
            else
            {
                Dialog.Choice("dialogDeleteRecruit", delegate(Dialog d)
                {
                    d.AddButton("yes".lang(), delegate
                    {
                        func();
                    });
                    d.AddButton("yesAndSkip".lang(), delegate
                    {
                        func();
                        skipDialog = true;
                    });
                    d.AddButton("no".lang());
                });
            }
        });
    }
References Dialog.AddButton(), ItemGeneral.AddSubButton(), TraitChara.CanBeBanished, Dialog.Choice(), EClass.core, CoreRef.icons, Chara.job, Core.refs, ItemGeneral.SetSubText(), skipDialog, Chara.trait, and CoreRef.Icons.trash.
OnList()
override void ListPeopleCallReserve.OnList () inline virtual
Reimplemented from BaseListPeople.
Definition at line 55 of file ListPeopleCallReserve.cs.
    {
        foreach (HireInfo item in EClass.Home.listReserve)
        {
            list.Add(item.chara);
        }
    }
References EClass.Home, item, and Faction.listReserve.
Member Data Documentation
skipDialog
bool ListPeopleCallReserve.skipDialog
Definition at line 6 of file ListPeopleCallReserve.cs.
Referenced by OnInstantiate().
The documentation for this class was generated from the following file:
Elin/ListPeopleCallReserve.cs