Elin Decompiled Documentation: Popper Class Reference
Popper Class Reference
Public Member Functions
Popper SetText (string s, Color c=default(Color))
Static Public Member Functions
static void SetText (TextMesh mesh, string text)
Public Attributes
bool isDestryoed
DOTweenAnimation anime
SpriteRenderer sr
Vector3 posFix
Vector3 posRandom
bool useLocalPosition
Tween tweenDelay
TextMesh text
TextMesh text2
Static Public Attributes
static Vector3 scale = Vector3.one
Detailed Description
Definition at line 5 of file Popper.cs.
Member Function Documentation
SetText() [1/2]
Popper Popper.SetText (string s, Color c = default(Color)) inline
Definition at line 28 of file Popper.cs.
    {
        SetText(text, s);
        base.transform.localScale = scale;
        if (c != default(Color))
        {
            text.color = c;
            text2.color = c;
        }
        return this;
    }
References Color, scale, SetText(), and text.
Referenced by DamageTextRenderer.Flush(), BaseStats.PopText(), ActionMode.RefreshTexts(), and SetText().
SetText() [2/2]
static void Popper.SetText (TextMesh mesh, string text) inline static
Definition at line 40 of file Popper.cs.
    {
        TextMesh[] componentsInChildren = mesh.GetComponentsInChildren<TextMesh>();
        foreach (TextMesh obj in componentsInChildren)
        {
            obj.font = SkinManager.Instance.fontSet.ui.source.font;
            obj.text = text;
            obj.font.material.renderQueue = 4999;
            obj.GetComponent<MeshRenderer>().sharedMaterial = mesh.font.material;
        }
        mesh.font.material.renderQueue = 5000;
    }
References FontSource.font, SkinManager.fontSet, SkinManager.Instance, SkinManager.FontData.source, text, and SkinManager.FontSet.ui.
Member Data Documentation
anime
DOTweenAnimation Popper.anime
Definition at line 12 of file Popper.cs.
Referenced by PopperManager.Kill(), and PopperManager.Pop().
isDestryoed
bool Popper.isDestryoed
Definition at line 10 of file Popper.cs.
posFix
Vector3 Popper.posFix
Definition at line 16 of file Popper.cs.
Referenced by PopperManager.Pop().
posRandom
Vector3 Popper.posRandom
Definition at line 18 of file Popper.cs.
Referenced by PopperManager.Pop().
scale
Vector3 Popper.scale = Vector3.one static
Definition at line 7 of file Popper.cs.
Referenced by SetText().
sr
SpriteRenderer Popper.sr
Definition at line 14 of file Popper.cs.
text
TextMesh Popper.text
Definition at line 24 of file Popper.cs.
Referenced by SetText().
text2
TextMesh Popper.text2
Definition at line 26 of file Popper.cs.
tweenDelay
Tween Popper.tweenDelay
Definition at line 22 of file Popper.cs.
Referenced by PopperManager.Kill().
useLocalPosition
bool Popper.useLocalPosition
Definition at line 20 of file Popper.cs.
Referenced by PopperManager.Pop().
The documentation for this class was generated from the following file:
Elin/Plugins.UI/Popper.cs