Elin Decompiled Documentation: ContentRanking Class Reference
ContentRanking Class Reference
Public Member Functions
override void OnSwitchContent (int idTab)
void SwitchRanking (string id)
Public Member Functions inherited from UIContent
virtual void OnSwitchContent (int idTab)
virtual void OnInstantiate ()
Public Member Functions inherited from UINote
void Clear ()
void Build ()
void Space (int sizeY=0, int sizeX=1)
UINote AddNote (string id)
UIItem AddHeader (string text, Sprite sprite=null)
UIItem AddHeaderCard (string text, Sprite sprite=null)
UIItem AddHeaderTopic (string text, Sprite sprite=null)
UIItem AddHeader (string id, string text, Sprite sprite=null)
UIItem AddText (string text, FontColor color=FontColor.DontChange)
UIItem AddText (string id, string text, FontColor color=FontColor.DontChange)
UIItem AddText (string id, string text, Color color)
UIItem AddItem (string id)
UIItem AddTopic (string id, string text, string value=null)
UIItem AddTopic (string text, string value=null)
void AddImage (Sprite sprite)
void AddImage (string idFile)
UIButton AddButton (string text, Action onClick)
UIButton AddButtonLink (string text, string url)
UIDropdown AddDropdown (string id="DropdownDefault")
UIButton AddToggle (string idLang="", bool isOn=false, Action< bool > action=null)
Transform AddPrefab (string path)
T AddExtra< T > (string path)
Public Attributes
UIList list
UIText textTitle
UIText textFactionName
Sprite[] spriteTrophies
GameObject comingSoon
GameObject wet
Public Attributes inherited from UINote
RectTransform target
UINoteProfile prof
SkinType skinType
string idDefaultText
LayoutGroup layout
RectTransform cur
bool extraRebuild
Detailed Description
Definition at line 3 of file ContentRanking.cs.
Member Function Documentation
OnSwitchContent()
override void ContentRanking.OnSwitchContent (int idTab) inline virtual
Reimplemented from UIContent.
Definition at line 17 of file ContentRanking.cs.
    {
        SwitchRanking("contribution");
    }
References SwitchRanking().
SwitchRanking()
void ContentRanking.SwitchRanking (string id) inline
Definition at line 22 of file ContentRanking.cs.
    {
        textTitle.text = Lang.Get("rank_" + id);
        textFactionName.text = EClass.Home.name;
        switch (id)
        {
        }
        list.callbacks = new UIList.Callback<Chara, ButtonChara>
        {
            onInstantiate = delegate(Chara a, ButtonChara b)
            {
                b.SetChara(a, ButtonChara.Mode.Journal);
                b.item.text1.text = "123456";
                b.item.text2.text = "contribution".lang();
            }
        };
        list.Clear();
        foreach (Chara chara in EClass._map.charas)
        {
            if (chara.faction == EClass.Home)
            {
                list.Add(chara);
            }
        }
        list.Refresh();
        for (int i = 0; i < list.buttons.Count; i++)
        {
            ButtonChara buttonChara = list.buttons[i].component as ButtonChara;
            buttonChara.item.text3.text = "rank".lang((i + 1).ToString() ?? "");
            buttonChara.item.image1.SetActive(i < 3);
            if (i < 3)
            {
                buttonChara.item.image1.sprite = spriteTrophies[i];
            }
        }
        comingSoon.SetActive(id != "contribution");
        wet.SetActive(id == "wettunic");
        list.SetActive(id == "contribution");
        this.RebuildLayout(recursive: true);
    }
References EClass._map, UIList.Add(), UIList.buttons, Map.charas, UIList.Clear(), comingSoon, Chara.faction, Lang.Get(), EClass.Home, UIItem.image1, ButtonChara.item, list, Faction.name, UIList.Refresh(), ButtonChara.SetChara(), spriteTrophies, and wet.
Referenced by OnSwitchContent().
Member Data Documentation
comingSoon
GameObject ContentRanking.comingSoon
Definition at line 13 of file ContentRanking.cs.
Referenced by SwitchRanking().
list
UIList ContentRanking.list
Definition at line 5 of file ContentRanking.cs.
Referenced by SwitchRanking().
spriteTrophies
Sprite [] ContentRanking.spriteTrophies
Definition at line 11 of file ContentRanking.cs.
Referenced by SwitchRanking().
textFactionName
UIText ContentRanking.textFactionName
Definition at line 9 of file ContentRanking.cs.
textTitle
UIText ContentRanking.textTitle
Definition at line 7 of file ContentRanking.cs.
wet
GameObject ContentRanking.wet
Definition at line 15 of file ContentRanking.cs.
Referenced by SwitchRanking().
The documentation for this class was generated from the following file:
Elin/ContentRanking.cs