Elin Decompiled Documentation: BaseArea Class Reference
BaseArea Class Reference
Classes
class Interaction
Public Types
enum AccessType { Public , Resident , Private }
Public Types inherited from IInspect
enum NoteMode { Default , Recipe , Product , Info }
Public Member Functions
Point GetRandomFreePos ()
Thing GetEmptySeat ()
virtual Point GetRandomPoint (bool walkable=true, bool allowChara=true)
void ChangeType (string _id)
void SetRandomName (int seed=-1)
string GetRandomName (int seed=-1)
HashSet< string > ListRoomNames ()
int GetSortVal (UIList.SortMode m)
List< BaseArea.Interaction > ListInteractions ()
void OnInspect ()
void WriteNote (UINote n, Action< UINote > onWriteNote=null, IInspect.NoteMode mode=IInspect.NoteMode.Default, Recipe recipe=null)
void WriteNote (UINote n, Action< UINote > onWriteNote=null, IInspect.NoteMode mode=IInspect.NoteMode.Default, Recipe recipe=null)
void OnInspect ()
Public Attributes
int uid
PointList points = new PointList()
AreaData data = new AreaData()
AreaType type = new AreaTypeRoom()
TraitRoomPlate plate
Properties
virtual string Name [get]
bool IsPrivate [get]
SourceArea.Row source [get]
bool CanInspect [get]
string InspectName [get]
Point InspectPoint [get]
Vector3 InspectPosition [get]
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Properties inherited from IInspect
bool CanInspect [get]
string InspectName [get]
Point InspectPoint [get]
Vector3 InspectPosition [get]
Additional Inherited Members
Static Public Member Functions inherited from EClass
static int rnd (int a)
static int curve (int a, int start, int step, int rate=75)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Static Public Attributes inherited from EClass
static Core core
Detailed Description
Definition at line 6 of file BaseArea.cs.
Member Enumeration Documentation
AccessType
enum BaseArea.AccessType
Enumerator
Public
Resident
Private
Definition at line 321 of file BaseArea.cs.
    {
        Public,
        Resident,
        Private
    }
Member Function Documentation
ChangeType()
void BaseArea.ChangeType (string _id) inline
Definition at line 82 of file BaseArea.cs.
    {
        this.type = ClassCache.Create<AreaType>("AreaType" + _id, "Elin");
        this.type.id = _id;
        this.type.owner = this;
        if (this.plate != null)
        {
            this.plate.areaData.type = this.type;
        }
    }
References plate, and type.
Referenced by Area.Create().
GetEmptySeat()
Thing BaseArea.GetEmptySeat () inline
Definition at line 49 of file BaseArea.cs.
    {
        foreach (Point point in this.points)
        {
            foreach (Thing thing in point.Things)
            {
                if (thing.IsInstalled && !thing.pos.HasChara && thing.trait is TraitChair)
                {
                    return thing;
                }
            }
        }
        return null;
    }
References Point.HasChara, Card.IsInstalled, points, Card.pos, Point.Things, and Card.trait.
Referenced by MeetingManager.CallNext(), and MeetingManager.Start().
GetRandomFreePos()
Point BaseArea.GetRandomFreePos () inline
Definition at line 36 of file BaseArea.cs.
    {
        for (int i = 0; i < 100; i++)
        {
            Point point = this.points.RandomItem<Point>();
            if (!point.IsBlocked)
            {
                return point;
            }
        }
        return null;
    }
References Point.IsBlocked, and points.
Referenced by AreaTypeFarm.GetAI(), BaseListPeople.OnInstantiate(), GoalSleep.OnSimulatePosition(), GoalWork.OnSimulatePosition(), and GoalSleep.Run().
GetRandomName()
string BaseArea.GetRandomName (int seed = -1) inline
Definition at line 98 of file BaseArea.cs.
    {
        if (seed != -1)
        {
            Rand.SetSeed(seed);
        }
        FactionBranch branch = EClass.Branch;
        string combinedName = WordGen.GetCombinedName((branch != null) ? branch.GetRandomName() : null, this.ListRoomNames().RandomItem<string>(), true);
        if (seed != -1)
        {
            Rand.SetSeed(-1);
        }
        return combinedName;
    }
References EClass.Branch, FactionBranch.GetRandomName(), and seed.
Referenced by SetRandomName().
GetRandomPoint()
virtual Point BaseArea.GetRandomPoint (bool walkable = true, bool allowChara = true) inline virtual
Definition at line 64 of file BaseArea.cs.
    {
        if (walkable)
        {
            for (int i = 0; i < 100; i++)
            {
                foreach (Point point in this.points)
                {
                    if (!point.IsBlocked && (allowChara || !point.HasChara))
                    {
                        return point;
                    }
                }
            }
        }
        return this.points.RandomItem<Point>();
    }
References Point.HasChara, Point.IsBlocked, and points.
Referenced by MeetingManager.CallNext(), AI_Idle.Run(), and AIWork_Chore.SetDestPos().
GetSortVal()
int BaseArea.GetSortVal (UIList::SortMode m) inline
Definition at line 136 of file BaseArea.cs.
    {
        return this.source._index;
    }
References source.
Referenced by LayerHome.RefreshAreas().
ListInteractions()
List< BaseArea.Interaction > BaseArea.ListInteractions () inline
Definition at line 141 of file BaseArea.cs.
    {
        return new List<BaseArea.Interaction>
        {
            new BaseArea.Interaction
            {
                text = "accessType".lang(("access_" + this.data.accessType.ToString()).lang(), null, null, null, null),
                action = delegate()
                {
                    UIContextMenu uicontextMenu = EClass.ui.CreateContextMenuInteraction();
                    using (List<BaseArea.AccessType>.Enumerator enumerator = Util.EnumToList<BaseArea.AccessType>().GetEnumerator())
                    {
                        while (enumerator.MoveNext())
{
                            BaseArea.AccessType t = enumerator.Current;
                            uicontextMenu.AddButton(((this.data.accessType == t) ? "context_checker".lang() : "") + ("access_" + t.ToString()).lang(), delegate()
{
                                this.data.accessType = t;
                                if (this.plate != null)
{
                                    this.plate.areaData.accessType = this.data.accessType;
                                }
                                SE.ClickOk();
                            }, true);
                        }
                    }
                    CursorSystem.ignoreCount = 5;
                    uicontextMenu.Show();
                }
            },
            new BaseArea.Interaction
            {
                text = "changeName",
                action = delegate()
                {
                    Dialog.InputName("dialogChangeName", this.data.name.IsEmpty(this.GetRandomName(-1)), delegate(bool cancel, string text)
                    {
                        if (!cancel)
{
                            this.data.name = text;
                            if (this.plate != null)
{
                                this.plate.areaData.name = text;
                            }
                        }
                    }, Dialog.InputType.Default);
                }
            },
            new BaseArea.Interaction
            {
                text = "toggleShowWallItem".lang() + "(" + (this.data.showWallItem ? "on" : "off").lang() + ")",
                action = delegate()
                {
                    this.data.showWallItem = !this.data.showWallItem;
                    SE.ClickOk();
                }
            },
            new BaseArea.Interaction
            {
                text = "toggleAtrium".lang() + "(" + (this.data.atrium ? "on" : "off").lang() + ")",
                action = delegate()
                {
                    this.data.atrium = !this.data.atrium;
                    if (this.plate != null)
                    {
                        this.plate.areaData.atrium = this.data.atrium;
                    }
                    SE.ClickOk();
                }
            },
            new BaseArea.Interaction
            {
                text = "limitRoomHeight",
                action = delegate()
                {
                    List<string> list = new List<string>();
                    EClass.ui.AddLayer<LayerList>().SetStringList(delegate
                    {
                        list.Clear();
                        for (int i = 1; i < 10; i++)
{
                            list.Add(i.ToString() ?? "");
                        }
                        return list;
                    }, delegate(int a, string b)
                    {
                        this.data.maxHeight = a + 1;
                        if (this.plate != null)
{
                            this.plate.areaData.maxHeight = a + 1;
                        }
                        EClass._map.rooms.RefreshAll();
                    }, true);
                }
            },
            new BaseArea.Interaction
            {
                text = "changeGroup",
                action = delegate()
                {
                    List<string> list = new List<string>();
                    EClass.ui.AddLayer<LayerList>().SetStringList(delegate
                    {
                        list.Clear();
                        for (int i = 0; i < 5; i++)
{
                            list.Add(i.ToString() ?? "");
                        }
                        return list;
                    }, delegate(int a, string b)
                    {
                        this.data.group = a;
                        if (this.plate != null)
{
                            this.plate.areaData.group = a;
                        }
                        EClass._map.rooms.RefreshAll();
                    }, true);
                }
            }
        };
    }
References EClass._map, AreaData.accessType, AreaData.atrium, data, Dialog.InputName(), AreaData.name, plate, RoomManager.RefreshAll(), Map.rooms, AreaData.showWallItem, text, and EClass.ui.
Referenced by TraitRoomPlate.TrySetAct().
ListRoomNames()
HashSet< string > BaseArea.ListRoomNames () inline
Definition at line 113 of file BaseArea.cs.
    {
        HashSet<string> hashSet = new HashSet<string>();
        foreach (string item in Lang.GetList("rooms"))
        {
            hashSet.Add(item);
        }
        foreach (Point point in this.points)
        {
            foreach (Thing thing in point.Things)
            {
                if (thing.IsInstalled && !thing.source.roomName.IsEmpty())
                {
                    foreach (string item2 in thing.source.GetTextArray("roomName"))
                    {
                        hashSet.Add(item2);
                    }
                }
            }
        }
        return hashSet;
    }
References Card.IsInstalled, points, Thing.source, and Point.Things.
OnInspect()
void BaseArea.OnInspect () inline
Implements IInspect.
Definition at line 264 of file BaseArea.cs.
    {
    }
SetRandomName()
void BaseArea.SetRandomName (int seed = -1) inline
Definition at line 93 of file BaseArea.cs.
    {
        this.data.name = this.GetRandomName(seed);
    }
References GetRandomName(), and seed.
Referenced by AM_CreateArea.OnProcessTiles().
WriteNote()
void BaseArea.WriteNote (UINote n, Action< UINote > onWriteNote = null, IInspect::NoteMode mode = IInspect::NoteMode::Default, Recipe recipe = null) inline
Implements IInspect.
Definition at line 292 of file BaseArea.cs.
    {
        n.Clear();
        n.AddHeaderCard(this.Name, null);
        n.Build();
    }
References Name.
Member Data Documentation
data
AreaData BaseArea.data = new AreaData()
Definition at line 314 of file BaseArea.cs.
Referenced by Lot.AddConnectedRooms(), BaseTileMap.DrawTile(), AI_Idle.g__FindMovePoint(), Thing.GetExtraName(), ActionMode.GetSimpleText(), Chara.HasAccess(), ListInteractions(), BaseGameScreen.RefreshWeather(), AI_Idle.Run(), and GameUpdater.Update100ms().
plate
TraitRoomPlate BaseArea.plate
Definition at line 319 of file BaseArea.cs.
Referenced by ChangeType(), ListInteractions(), and Room.Refresh().
points
PointList BaseArea.points = new PointList()
Definition at line 311 of file BaseArea.cs.
Referenced by Lot.AddConnectedRooms(), Room.AddPoint(), Area.AddPoint(), GetEmptySeat(), AreaTypeFarm.GetPlowPos(), GetRandomFreePos(), GetRandomPoint(), AM_ExpandArea.HitTest(), Trait.ListPoints(), ListRoomNames(), Area.OnHoverArea(), Area.OnLoad(), Room.OnLoad(), Area.OnRemove(), Room.OnRemove(), Room.Refresh(), UIInspector.Refresh(), Area.RemovePoint(), and VirtualRoom.VirtualRoom().
type
AreaType BaseArea.type = new AreaTypeRoom()
Definition at line 317 of file BaseArea.cs.
Referenced by ChangeType(), AM_CreateArea.CreateNew(), RoomManager.FindBaseArea(), AI_Idle.GetRandomAssignedRoom(), AIWork.GetSession(), and Point.IsPublicSpace().
uid
int BaseArea.uid
Definition at line 308 of file BaseArea.cs.
Referenced by RoomManager.AddArea(), RoomManager.AddRoom(), Area.OnLoad(), Room.OnLoad(), RoomManager.RemoveArea(), RoomManager.RemoveRoom(), RefArea.Set(), Room.ToString(), and RoomManager.TryAddArea().
Property Documentation
CanInspect
bool BaseArea.CanInspect get
Implements IInspect.
Definition at line 268 of file BaseArea.cs.
    {
        get
        {
            return true;
        }
    }
InspectName
string BaseArea.InspectName get
Implements IInspect.
Definition at line 276 of file BaseArea.cs.
    {
        get
        {
            return this.Name;
        }
    }
InspectPoint
Point BaseArea.InspectPoint get
Implements IInspect.
Definition at line 284 of file BaseArea.cs.
    {
        get
        {
            return Point.Invalid;
        }
    }
InspectPosition
Vector3 BaseArea.InspectPosition get
Implements IInspect.
Definition at line 299 of file BaseArea.cs.
    {
        get
        {
            return Vector3.zero;
        }
    }
IsPrivate
bool BaseArea.IsPrivate get
Definition at line 20 of file BaseArea.cs.
    {
        get
        {
            return this.data.accessType == BaseArea.AccessType.Private;
        }
    }
Referenced by GoalWork.FindWork(), and AIWork_Chore.SetDestPos().
Name
virtual string BaseArea.Name get
Definition at line 8 of file BaseArea.cs.
    {
        get
        {
            if (!this.data.name.IsEmpty())
            {
                return this.data.name;
            }
            return this.type.source.GetName();
        }
    }
Referenced by BaseListPeople.OnInstantiate(), LayerHome.RefreshAreas(), UIRecipeInfo.SetArea(), and WriteNote().
source
SourceArea.Row BaseArea.source get
Definition at line 28 of file BaseArea.cs.
    {
        get
        {
            return this.type.source;
        }
    }
Referenced by GetSortVal(), BuildMenu.RefreshCategoryArea(), and UIRecipeInfo.SetArea().
The documentation for this class was generated from the following file:
Elin/BaseArea.cs