Elin Decompiled Documentation: RankedZoneManager Class Reference
RankedZoneManager Class Reference
Public Member Functions
int GetIncome (Zone z)
string GetRankText (Zone z)
int GetRank (Zone z)
List< RankedZone > GetList ()
Additional Inherited Members
Static Public Member Functions inherited from EClass
static int rnd (int a)
static int curve (int a, int start, int step, int rate=75)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Static Public Attributes inherited from EClass
static Core core
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Detailed Description
Definition at line 4 of file RankedZoneManager.cs.
Member Function Documentation
GetIncome()
int RankedZoneManager.GetIncome (Zone z) inline
Definition at line 6 of file RankedZoneManager.cs.
    {
        List<FactionBranch> children = EClass.pc.faction.GetChildren();
        children.Sort((FactionBranch a, FactionBranch b) => GetRank(a.owner) - GetRank(b.owner));
        int num = children.IndexOf(z.branch);
        return CalcIncome(z) * 100 / (100 + num * 40);
        int CalcIncome(Zone _z)
        {
            int rank = GetRank(_z);
            if (rank > 125)
            {
                return 0;
            }
            return (126 - rank) * 100;
        }
    }
References Zone.branch, Chara.faction, Faction.GetChildren(), GetRank(), FactionBranch.owner, and EClass.pc.
Referenced by Faction.GetRankIncome(), UIHomeInfo.RefreshInfo(), and UIFactionInfo.SetZone().
GetList()
List< RankedZone > RankedZoneManager.GetList () inline
Definition at line 47 of file RankedZoneManager.cs.
    {
        List<RankedZone> list = new List<RankedZone>();
        foreach (Spatial z in EClass.game.spatials.map.Values)
        {
            if ((z.source.value <= 0 || z.lv != 0) && !z.IsPlayerFaction)
            {
                continue;
            }
            int v = 0;
            if (z.IsPlayerFaction)
            {
                v = (z as Zone).branch.Worth;
            }
            else
            {
                v = z.source.value;
                Rand.UseSeed(z.uid, delegate
                {
                    v = z.source.value + EClass.rnd(z.source.value / 10);
                });
            }
            list.Add(new RankedZone
            {
                z = (z as Zone),
                value = v
            });
        }
        list.Sort((RankedZone a, RankedZone b) => b.Value - a.Value);
        int num = 0;
        int num2 = 0;
        foreach (RankedZone item in list)
        {
            int num3 = num2 - item.value;
            int num4 = 1000;
            num4 = ((item.value < 100000000) ? ((item.value < 10000000) ? ((item.value < 5000000) ? ((item.value < 1000000) ? ((item.value < 500000) ? ((item.value < 100000) ? ((item.value < 50000) ? ((item.value < 10000) ? 1000 : 2000) : 5000) : 10000) : 50000) : 500000) : 1000000) : 5000000) : 100000000);
            num = (item.rank = num + Mathf.Max(num3 / num4, 1));
            num2 = item.Value;
        }
        return list;
    }
References EClass.game, Spatial.IsPlayerFaction, Spatial.lv, SpatialManager.map, EClass.rnd(), Spatial.source, Game.spatials, Spatial.uid, and Rand.UseSeed().
Referenced by GetRank(), and ContentHomeRanking.Refresh().
GetRank()
int RankedZoneManager.GetRank (Zone z) inline
Definition at line 35 of file RankedZoneManager.cs.
    {
        foreach (RankedZone item in GetList())
        {
            if (item.z == z)
            {
                return item.rank;
            }
        }
        return 1;
    }
References GetList(), and item.
Referenced by GetIncome(), GetRankText(), and HomeResourceWorth.UpdateRank().
GetRankText()
string RankedZoneManager.GetRankText (Zone z) inline
Definition at line 23 of file RankedZoneManager.cs.
    {
        int rank = GetRank(z);
        string[] list = Lang.GetList("num_rank");
        int num = rank % 10;
        if (num >= list.Length)
        {
            num = 0;
        }
        return rank + list[num];
    }
References Lang.GetList(), and GetRank().
Referenced by UIHomeInfo.RefreshInfo(), UIFactionInfo.SetZone(), and HomeResourceWorth.UpdateRank().
The documentation for this class was generated from the following file:
Elin/RankedZoneManager.cs