Elin Decompiled Documentation: UIButtonLR Class Reference
UIButtonLR Class Reference
Public Member Functions
void SetOptions (int _index, List< string > langs, Action< int > onSelect, bool invoke=true, string langTopic=null)
void SetOptions< T > (int _index, IList< T > list, Func< T, string > funcName, Action< T > onSelect, bool invoke=true, string langTopic=null)
void SelectOption (int _index)
Public Member Functions inherited from UIButton
virtual bool CanMiddleClick ()
virtual void OnMiddleClick (bool forceClick)
void SetItem (Item i)
virtual void RefreshItem ()
virtual void OnHover ()
void Toggle ()
void ToggleCheck ()
void SetCheck (bool check)
void SetToggle (bool isOn, Action< bool > onToggle=null)
void SetToggleWithScore (bool isOn, Action< bool > onToggle, int? score)
void SetTooltip (Action< UITooltip > onShowTooltip=null, bool enable=true)
void SetTooltip (string id, Action< UITooltip > onShowTooltip=null, bool enable=true)
void SetTooltipLang (string lang=null)
virtual void ShowTooltip ()
void ShowTooltipForced (bool ignoreWhenRightClick=true)
override void OnPointerDown (PointerEventData eventData)
override void OnPointerClick (PointerEventData eventData)
override void OnPointerUp (PointerEventData eventData)
void OnPointerUpOnDrag (PointerEventData eventData)
void _OnPress ()
void OnPress ()
void AddHighlight (Func< bool > killCondition)
void DoHighlightTransition (bool instant=false)
void DoNormalTransition (bool instant=true)
override Selectable FindSelectableOnDown ()
override Selectable FindSelectableOnUp ()
override Selectable FindSelectableOnLeft ()
override Selectable FindSelectableOnRight ()
void SetNavigation (UIButton up, UIButton down=null, UIButton left=null, UIButton right=null)
override bool IsActive ()
void SetInteractableWithAlpha (bool enable)
virtual void ApplySkin ()
void ApplySkin ()
Public Attributes
int index
UIButton left
UIButton right
UIText textTitle
bool loopOption
List< string > options = new List<string>()
Public Attributes inherited from UIButton
UIText mainText
UIText subText
UIText subText2
UIText keyText
Image icon
Image imageCheck
Graphic[] targetGraphics
float scaleIcon = 1f
float slideX
float navigationFix
bool isChecked
bool instantClick = true
UISelectableGroup group
TooltipData tooltip
SoundData soundClick
SoundData soundHighlight
Transform animeTarget
Anime animeClick
Anime animeHold
ButtonType buttonType
BaseSkinRoot skinRoot
Action onDoubleClick
Action onRightClick
Action< int > onInputWheel
object refObj
int refInt
string refStr
bool animating
bool selected
Vector3 originalIconScale = Vector3.one
UIButton highlightTarget
Item item
Additional Inherited Members
Static Public Member Functions inherited from UIButton
static void UpdateButtons ()
static void TryHihlight ()
static void TryShowTip (Transform root=null, bool highlight=true, bool ignoreWhenRightClick=true)
static void TryShowTip< T > (Transform root=null, bool highlight=true, bool ignoreWhenRightClick=false)
Static Public Attributes inherited from UIButton
static bool DoSlide
static bool locked
static UIButton lastButton
static UIButton lastHovered
static UIButton currentHighlight
static UIButton currentPressedButton
static float lastClicked
static float doubleClickTime = 0.4f
static Vector2 buttonPos
static Action onPressed
static List< UIButton > buttons = new List<UIButton>()
static Action actionTooltip
Protected Member Functions inherited from UIButton
override void Awake ()
override void OnEnable ()
override void DoStateTransition (SelectionState state, bool instant)
Properties inherited from UIButton
List< Graphic > Graphics [get]
virtual bool CanDragLeftButton [get]
Detailed Description
Definition at line 4 of file UIButtonLR.cs.
Member Function Documentation
SelectOption()
void UIButtonLR.SelectOption (int _index) inline
Definition at line 76 of file UIButtonLR.cs.
    {
        if (_index < 0)
        {
            _index = (loopOption ? (options.Count - 1) : 0);
        }
        if (_index >= options.Count)
        {
            _index = ((!loopOption) ? (options.Count - 1) : 0);
        }
        index = _index;
        mainText.SetLang(options[index]);
    }
References index, loopOption, UIButton.mainText, options, and UIText.SetLang().
Referenced by SetOptions(), and SetOptions< T >().
SetOptions()
void UIButtonLR.SetOptions (int _index, List< string > langs, Action< int > onSelect, bool invoke = true, string langTopic = null) inline
Definition at line 20 of file UIButtonLR.cs.
    {
        left.onClick.RemoveAllListeners();
        right.onClick.RemoveAllListeners();
        options = langs;
        left.onClick.AddListener(delegate
        {
            SelectOption(index - 1);
            onSelect(index);
        });
        right.onClick.AddListener(delegate
        {
            SelectOption(index + 1);
            onSelect(index);
        });
        SelectOption(_index);
        if (invoke)
        {
            onSelect(index);
        }
        if (!langTopic.IsEmpty())
        {
            textTitle.SetLang(langTopic);
        }
    }
References index, left, options, right, SelectOption(), UIText.SetLang(), and textTitle.
Referenced by ContentConfigTest.OnInstantiate().
SetOptions< T >()
void UIButtonLR.SetOptions< T > (int _index, IList< T > list, Func< T, string > funcName, Action< T > onSelect, bool invoke = true, string langTopic = null) inline
Definition at line 46 of file UIButtonLR.cs.
    {
        options.Clear();
        foreach (T item in list)
        {
            options.Add(funcName(item));
        }
        left.onClick.RemoveAllListeners();
        right.onClick.RemoveAllListeners();
        left.onClick.AddListener(delegate
        {
            SelectOption(index - 1);
            onSelect(list[index]);
        });
        right.onClick.AddListener(delegate
        {
            SelectOption(index + 1);
            onSelect(list[index]);
        });
        SelectOption(_index);
        if (invoke)
        {
            onSelect(list[index]);
        }
        if (!langTopic.IsEmpty())
        {
            textTitle.SetLang(langTopic);
        }
    }
References index, UIButton.item, left, options, right, SelectOption(), UIText.SetLang(), and textTitle.
Member Data Documentation
index
int UIButtonLR.index
Definition at line 7 of file UIButtonLR.cs.
Referenced by SelectOption(), SetOptions(), and SetOptions< T >().
left
UIButton UIButtonLR.left
Definition at line 9 of file UIButtonLR.cs.
Referenced by SetOptions(), and SetOptions< T >().
loopOption
bool UIButtonLR.loopOption
Definition at line 15 of file UIButtonLR.cs.
Referenced by SelectOption().
options
List<string> UIButtonLR.options = new List<string>()
Definition at line 18 of file UIButtonLR.cs.
Referenced by SelectOption(), SetOptions(), and SetOptions< T >().
right
UIButton UIButtonLR.right
Definition at line 11 of file UIButtonLR.cs.
Referenced by SetOptions(), and SetOptions< T >().
textTitle
UIText UIButtonLR.textTitle
Definition at line 13 of file UIButtonLR.cs.
Referenced by SetOptions(), and SetOptions< T >().
The documentation for this class was generated from the following file:
Elin/Plugins.UI/UIButtonLR.cs