Elin Decompiled Documentation: ExcelBookImportSetting Class Reference
ExcelBookImportSetting Class Reference
Public Member Functions
ExcelSheetImportSetting GetSheet (string id)
ExcelSheetImportSetting GetOrCreateSheet (string id)
override string ToString ()
Public Attributes
string name
string exportPath
string _prefix
List< ExcelSheetImportSetting > sheets = new List<ExcelSheetImportSetting>()
Properties
string prefix [get]
string path [get]
Detailed Description
Definition at line 5 of file ExcelBookImportSetting.cs.
Member Function Documentation
GetOrCreateSheet()
ExcelSheetImportSetting ExcelBookImportSetting.GetOrCreateSheet (string id) inline
Definition at line 41 of file ExcelBookImportSetting.cs.
    {
        ExcelSheetImportSetting sheet = GetSheet(id);
        if (sheet != null)
        {
            return sheet;
        }
        sheet = new ExcelSheetImportSetting
        {
            name = id
        };
        sheets.Add(sheet);
        return sheet;
    }
References GetSheet(), name, and sheets.
GetSheet()
ExcelSheetImportSetting ExcelBookImportSetting.GetSheet (string id) inline
Definition at line 29 of file ExcelBookImportSetting.cs.
    {
        foreach (ExcelSheetImportSetting sheet in sheets)
        {
            if (sheet.name == id)
            {
                return sheet;
            }
        }
        return null;
    }
References ExcelSheetImportSetting.name, and sheets.
Referenced by GetOrCreateSheet().
ToString()
override string ExcelBookImportSetting.ToString () inline
Definition at line 56 of file ExcelBookImportSetting.cs.
    {
        return name;
    }
References name.
Member Data Documentation
_prefix
string ExcelBookImportSetting._prefix
Definition at line 11 of file ExcelBookImportSetting.cs.
exportPath
string ExcelBookImportSetting.exportPath
Definition at line 9 of file ExcelBookImportSetting.cs.
name
string ExcelBookImportSetting.name
Definition at line 7 of file ExcelBookImportSetting.cs.
Referenced by GetOrCreateSheet(), and ToString().
sheets
List<ExcelSheetImportSetting> ExcelBookImportSetting.sheets = new List<ExcelSheetImportSetting>()
Definition at line 13 of file ExcelBookImportSetting.cs.
Referenced by GetOrCreateSheet(), and GetSheet().
Property Documentation
path
string ExcelBookImportSetting.path get
Definition at line 27 of file ExcelBookImportSetting.cs.
prefix
string ExcelBookImportSetting.prefix get
Definition at line 15 of file ExcelBookImportSetting.cs.
    {
        get
        {
            if (!string.IsNullOrEmpty(_prefix))
            {
                return _prefix;
            }
            return "Source";
        }
    }
The documentation for this class was generated from the following file:
Elin/Plugins.basecore/ExcelBookImportSetting.cs