Elin Decompiled Documentation: ElementContainer Class Reference
ElementContainer Class Reference
Public Types
enum NoteMode {
Default , CharaMake , CharaMakeAttributes , Domain ,
Trait
}
Public Member Functions
void ApplyElementMap (int uid, SourceValueType type, Dictionary< int, int > map, int lv, bool invert=false, bool applyFeat=false)
void ApplyMaterialElementMap (Thing t, bool invert=false)
void ImportElementMap (Dictionary< int, int > map)
ElementContainer ImportElementMap (int[] ints)
void ApplyPotential (int mode=0)
int Value (int ele)
virtual int ValueBonus (Element e)
int ValueWithoutLink (int ele)
int ValueWithoutLink (string alias)
int GetFeatRef (int ele, int idx=0)
int Exp (int ele)
bool Has (int ele)
bool Has (SourceElement.Row row)
bool Has (string alias)
bool HasBase (int ele)
int Base (int ele)
void Learn (int ele, int v=1)
void Train (int ele, int a=10)
void ModExp (int ele, int a, bool chain=false)
virtual void OnLearn (int ele)
virtual void OnTrain (int ele)
virtual void OnLevelUp (Element e, int lastValue)
virtual void OnLevelDown (Element e, int lastValue)
Element SetBase (string alias, int v, int potential=0)
Element SetBase (int id, int v, int potential=0)
void SetTo (int id, int v)
void Remove (int id)
Element ModBase (int ele, int v)
virtual void OnChangeValue ()
Element ModPotential (int ele, int v)
Element ModTempPotential (int ele, int v, int threshMsg=0)
virtual void OnModTempPotential (Element e, int v, int threshMsg)
int GetSpellExp (Chara c, Element e, int costMod=100)
Element GetElement (string alias)
Element GetElement (int id)
Element CreateElement (int id)
Element GetOrCreateElement (Element ele)
Element GetOrCreateElement (string alias)
Element GetOrCreateElement (int id)
void SetParent (Card c)
void SetParent (ElementContainer newParent=null)
List< Element > ListElements (Func< Element, bool > shoudList=null, Comparison< Element > comparison=null)
List< Element > ListBestAttributes ()
List< Element > ListBestSkills ()
List< Element > ListGeneFeats ()
List< Element > ListLearnable (Chara c)
void CopyTo (ElementContainer container)
void AddNote (UINote n, Func< Element, bool > isValid=null, Action onAdd=null, NoteMode mode=NoteMode.Default, bool addRaceFeat=false, Func< Element, string, string > funcText=null, Action< UINote, Element > onAddNote=null)
void AddNoteAll (UINote n)
Static Public Member Functions
static int GetSortVal (Element a)
Static Public Member Functions inherited from EClass
static int rnd (int a)
static int curve (int a, int start, int step, int rate=75)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Public Attributes
Dictionary< int, Element > dict = new Dictionary<int, Element>()
ElementContainer parent
List< int > list
Static Public Attributes
const int sizeElement = 5
Static Public Attributes inherited from EClass
static Core core
Properties
virtual Card Card [get]
virtual Chara Chara [get]
virtual bool IsMeleeWeapon [get]
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Private Member Functions
void OnSerializing (StreamingContext context)
void OnDeserialized (StreamingContext context)
Element ModLink (int id, int v)
Detailed Description
Definition at line 9 of file ElementContainer.cs.
Member Enumeration Documentation
NoteMode
enum ElementContainer.NoteMode
Enumerator
Default
CharaMake
CharaMakeAttributes
Domain
Trait
Definition at line 11 of file ElementContainer.cs.
    {
        Default,
        CharaMake,
        CharaMakeAttributes,
        Domain,
        Trait
    }
Member Function Documentation
AddNote()
void ElementContainer.AddNote (UINote n, Func< Element, bool > isValid = null, Action onAdd = null, NoteMode mode = NoteMode::Default, bool addRaceFeat = false, Func< Element, string, string > funcText = null, Action< UINote, Element > onAddNote = null) inline
Definition at line 669 of file ElementContainer.cs.
    {
        List<Element> list = new List<Element>();
        foreach (Element value2 in dict.Values)
        {
            if ((isValid == null || isValid(value2)) && (mode != NoteMode.CharaMake || value2.ValueWithoutLink != 0) && (value2.Value != 0 || mode == NoteMode.CharaMakeAttributes) && (!value2.HasTag("hidden") || EClass.debug.showExtra))
            {
                list.Add(value2);
            }
        }
        if (addRaceFeat)
        {
            Element element = Element.Create(29, 1);
            element.owner = this;
            list.Add(element);
        }
        if (list.Count == 0)
        {
            return;
        }
        onAdd?.Invoke();
        switch (mode)
        {
        case NoteMode.CharaMake:
        case NoteMode.CharaMakeAttributes:
            list.Sort((Element a, Element b) => a.GetSortVal(UIList.SortMode.ByElementParent) - b.GetSortVal(UIList.SortMode.ByElementParent));
            break;
        case NoteMode.Trait:
            list.Sort((Element a, Element b) => GetSortVal(b) - GetSortVal(a));
            break;
        default:
            list.Sort((Element a, Element b) => a.SortVal() - b.SortVal());
            break;
        }
        string text = "";
        foreach (Element e in list)
        {
            switch (mode)
            {
            case NoteMode.Domain:
                n.AddText(e.Name, FontColor.Default);
                continue;
            case NoteMode.Default:
            case NoteMode.Trait:
            {
                bool flag = e.source.tag.Contains("common");
                string categorySub = e.source.categorySub;
                bool flag2 = false;
                bool flag3 = (e.source.tag.Contains("neg") ? (e.Value > 0) : (e.Value < 0));
                int num = Mathf.Abs(e.Value);
                bool flag4 = Card != null && Card.ShowFoodEnc;
                bool flag5 = Card != null && Card.IsWeapon && e is Ability;
                if (e.IsTrait || (flag4 && e.IsFoodTrait))
                {
                    string[] textArray = e.source.GetTextArray("textAlt");
                    int num2 = Mathf.Clamp(e.Value / 10 + 1, (e.Value < 0 || textArray.Length <= 2) ? 1 : 2, textArray.Length - 1);
                    text = "altEnc".lang(textArray[0].IsEmpty(e.Name), textArray[num2], EClass.debug.showExtra ? (e.Value + " " + e.Name) : "");
                    flag3 = num2 <= 1 || textArray.Length <= 2;
                    flag2 = true;
                }
                else if (flag5)
                {
                    text = "isProc".lang(e.Name);
                    flag3 = false;
                }
                else if (categorySub == "resist")
                {
                    text = ("isResist" + (flag3 ? "Neg" : "")).lang(e.Name);
                }
                else if (categorySub == "eleAttack")
                {
                    text = "isEleAttack".lang(e.Name);
                }
                else if (!e.source.textPhase.IsEmpty() && e.Value > 0)
                {
                    text = e.source.GetText("textPhase");
                }
                else
                {
                    string name = e.Name;
                    bool flag6 = e.source.category == "skill" || (e.source.category == "attribute" && !e.source.textPhase.IsEmpty());
                    bool flag7 = e.source.category == "enchant";
                    if (e.source.tag.Contains("multiplier"))
                    {
                        flag6 = (flag7 = false);
                        name = EClass.sources.elements.alias[e.source.aliasRef].GetName();
                    }
                    flag2 = !(flag6 || flag7);
                    text = (flag6 ? "textEncSkill" : (flag7 ? "textEncEnc" : "textEnc")).lang(name, num + (e.source.tag.Contains("ratio") ? "%" : ""), ((e.Value > 0) ? "encIncrease" : "encDecrease").lang());
                }
                int num3 = ((!(e is Resistance)) ? 1 : 0);
                if (!flag && !flag2 && !e.source.tag.Contains("flag"))
                {
                    text = text + " [" + "*".Repeat(Mathf.Clamp(num * e.source.mtp / 5 + num3, 1, 5)) + ((num * e.source.mtp / 5 + num3 > 5) ? "+" : "") + "]";
                }
                if (e.HasTag("hidden"))
                {
                    text = "(debug)" + text;
                }
                FontColor color = (flag ? FontColor.Default : (flag3 ? FontColor.Bad : FontColor.Good));
                if (e.IsGlobalElement)
                {
                    text = text + " " + (e.IsFactionWideElement ? "_factionWide" : "_partyWide").lang();
                    if (Card != null && !Card.c_idDeity.IsEmpty() && Card.c_idDeity != EClass.pc.idFaith)
                    {
                        continue;
                    }
                    color = FontColor.Myth;
                }
                if (flag4 && e.IsFoodTrait && !e.IsFoodTraitMain)
                {
                    color = FontColor.FoodMisc;
                }
                if (e.id == 2 && e.Value >= 0)
                {
                    color = FontColor.FoodQuality;
                }
                if (funcText != null)
                {
                    text = funcText(e, text);
                }
                n.AddText("NoteText_prefwidth", text, color);
                onAddNote?.Invoke(n, e);
                continue;
            }
            }
            UIItem uIItem = n.AddTopic("TopicAttribute", e.Name, "".TagColor((e.ValueWithoutLink > 0) ? SkinManager.CurrentColors.textGood : SkinManager.CurrentColors.textBad, e.ValueWithoutLink.ToString() ?? ""));
            if ((bool)uIItem.button1)
            {
                uIItem.button1.tooltip.onShowTooltip = delegate(UITooltip t)
                {
                    e.WriteNote(t.note, EClass.pc.elements);
                };
            }
            e.SetImage(uIItem.image1);
            Image image = uIItem.image2;
            int value = (e.Potential - 80) / 20;
            image.enabled = e.Potential != 80;
            image.sprite = EClass.core.refs.spritesPotential[Mathf.Clamp(Mathf.Abs(value), 0, EClass.core.refs.spritesPotential.Count - 1)];
            image.color = ((e.Potential - 80 >= 0) ? Color.white : new Color(1f, 0.7f, 0.7f));
        }
    }
References UIItem.button1, Card.c_idDeity, Color, EClass.core, Element.Create(), SkinManager.CurrentColors, EClass.debug, dict, Card.elements, SourceManager.elements, GetSortVal(), Element.GetSortVal(), Element.HasTag(), Element.id, Chara.idFaith, UIItem.image1, UIItem.image2, Element.IsFoodTrait, Element.IsFoodTraitMain, Element.IsGlobalElement, Element.IsTrait, list, Element.Name, UITooltip.note, EClass.pc, Core.refs, Element.SetImage(), CoreDebug.showExtra, Card.ShowFoodEnc, Element.SortVal(), Element.source, EClass.sources, CoreRef.spritesPotential, SkinColorProfile.textBad, SkinColorProfile.textGood, Element.Value, Element.ValueWithoutLink, and Element.WriteNote().
Referenced by AddNoteAll(), UICharaMaker.Refresh(), RecipeCard.WriteNote(), and Thing.WriteNote().
AddNoteAll()
void ElementContainer.AddNoteAll (UINote n) inline
Definition at line 812 of file ElementContainer.cs.
    {
        Transform transform = n.AddExtra<Transform>("noteRace");
        UINote n2 = transform.Find("note1").GetComponent<UINote>();
        UINote n3 = transform.Find("note2").GetComponent<UINote>();
        AddNote(n3, (Element e) => e.HasTag("primary"), delegate
        {
            n3.AddHeader("HeaderNoteSmall", "attributes");
        }, NoteMode.CharaMakeAttributes);
        AddNote(n2, (Element e) => e.source.category == "skill" && !e.HasTag("hidden") && e.ValueWithoutLink > 1 && e.source.categorySub != "weapon", delegate
        {
            n2.AddHeader("HeaderNoteSmall", "skills");
        }, NoteMode.CharaMake);
        AddNote(n2, (Element e) => e is Feat, delegate
        {
            n2.AddHeader("HeaderNoteSmall", "feats");
        }, NoteMode.CharaMake);
    }
References AddNote(), Element.HasTag(), Element.source, and Element.ValueWithoutLink.
Referenced by UICharaMaker.ListJob(), and UICharaMaker.ListRace().
ApplyElementMap()
void ElementContainer.ApplyElementMap (int uid, SourceValueType type, Dictionary< int, int > map, int lv, bool invert = false, bool applyFeat = false) inline
Definition at line 73 of file ElementContainer.cs.
    {
        int num = ((!invert) ? 1 : (-1));
        Rand.SetSeed(uid);
        foreach (KeyValuePair<int, int> item in map)
        {
            Element orCreateElement = GetOrCreateElement(item.Key);
            int value = item.Value;
            if (value != 0)
            {
                if (orCreateElement.source.category == "skill")
                {
                    orCreateElement.vSourcePotential += orCreateElement.GetSourcePotential(value) * num;
                }
                int num2 = orCreateElement.GetSourceValue(value, lv, type) * num;
                orCreateElement.vSource += num2;
                if (applyFeat && orCreateElement is Feat)
                {
                    (orCreateElement as Feat).Apply(num2, this);
                }
            }
        }
        Rand.SetSeed();
    }
References GetOrCreateElement(), Element.GetSourcePotential(), Element.GetSourceValue(), item, Rand.SetSeed(), and Element.source.
Referenced by Chara.ApplyJob(), Chara.ApplyRace(), UICharaMaker.ListJob(), UICharaMaker.ListRace(), Chara.OnDeserialized(), Card.SetLv(), and ElementContainerCard.SetOwner().
ApplyMaterialElementMap()
void ElementContainer.ApplyMaterialElementMap (Thing t, bool invert = false) inline
Definition at line 98 of file ElementContainer.cs.
    {
        int num = ((!invert) ? 1 : (-1));
        SourceMaterial.Row material = t.material;
        Rand.SetSeed(t.uid);
        foreach (KeyValuePair<int, int> item in material.elementMap)
        {
            int value = item.Value;
            if (value == 0)
            {
                continue;
            }
            Element orCreateElement = GetOrCreateElement(item.Key);
            if (!orCreateElement.source.IsEncAppliable(t))
            {
                if (orCreateElement.vBase == 0 && orCreateElement.vSource == 0 && orCreateElement.vLink == 0 && orCreateElement.vExp == 0 && orCreateElement.vPotential == 0)
                {
                    Remove(orCreateElement.id);
                }
                continue;
            }
            int num2 = orCreateElement.GetMaterialSourceValue(t, value) * num;
            orCreateElement.vSource += num2;
            if (orCreateElement.vBase == 0 && orCreateElement.vSource == 0 && orCreateElement.vLink == 0 && orCreateElement.vExp == 0 && orCreateElement.vPotential == 0)
            {
                Remove(orCreateElement.id);
            }
        }
        Rand.SetSeed();
    }
References Element.GetMaterialSourceValue(), GetOrCreateElement(), Element.id, item, Card.material, material, Remove(), Rand.SetSeed(), Element.source, Card.uid, Element.vBase, Element.vExp, Element.vLink, Element.vPotential, and Element.vSource.
Referenced by Thing.ApplyMaterialElements().
ApplyPotential()
void ElementContainer.ApplyPotential (int mode = 0) inline
Definition at line 146 of file ElementContainer.cs.
    {
        foreach (Element value in dict.Values)
        {
            if (value.HasTag("primary"))
            {
                value.vTempPotential = (value.ValueWithoutLink - ((mode != 2) ? 7 : 0)) * 5;
            }
        }
    }
References dict, and Element.HasTag().
Referenced by UICharaMaker.ListJob(), UICharaMaker.ListRace(), and UICharaMaker.Refresh().
Base()
int ElementContainer.Base (int ele) inline
Definition at line 251 of file ElementContainer.cs.
    {
        return GetElement(ele)?.ValueWithoutLink ?? 0;
    }
References GetElement(), and Element.ValueWithoutLink.
Referenced by Chara.ModTempElement(), and FoodEffect.Proc().
CopyTo()
void ElementContainer.CopyTo (ElementContainer container) inline
Definition at line 639 of file ElementContainer.cs.
    {
        container.dict.Clear();
        foreach (KeyValuePair<int, Element> item in dict)
        {
            Element element = container.CreateElement(item.Key);
            element.vBase = item.Value.vBase;
            element.vExp = item.Value.vExp;
            element.vSource = item.Value.vSource;
        }
    }
References dict, and item.
Referenced by Card.Duplicate().
CreateElement()
Element ElementContainer.CreateElement (int id) inline
Definition at line 488 of file ElementContainer.cs.
    {
        Element element = Element.Create(id);
        if (element == null)
        {
            return null;
        }
        element.owner = this;
        dict.Add(id, element);
        return element;
    }
References Element.Create(), and dict.
Referenced by GetOrCreateElement(), and ListElements().
Exp()
int ElementContainer.Exp (int ele) inline
Definition at line 204 of file ElementContainer.cs.
    {
        return GetElement(ele)?.vExp ?? 0;
    }
References GetElement(), and Element.vExp.
GetElement() [1/2]
Element ElementContainer.GetElement (int id) inline
Definition at line 483 of file ElementContainer.cs.
    {
        return dict.TryGetValue(id);
    }
References dict.
GetElement() [2/2]
Element ElementContainer.GetElement (string alias) inline
Definition at line 478 of file ElementContainer.cs.
    {
        return GetElement(EClass.sources.elements.alias.TryGetValue(alias)?.id ?? 0);
    }
References SourceManager.elements, GetElement(), and EClass.sources.
Referenced by PolicyManager.AddPolicy(), ActMelee.Attack(), Base(), WidgetStatsBar.Build(), Thing.CanAutoFire(), Thing.CanStackTo(), ElementContainerCard.CheckSkillActions(), Chara.CureTempElements(), Player.DreamSpell(), Exp(), Party.GetBestSkill(), GetElement(), GetFeatRef(), Check.GetFinalDC(), Has(), HasBase(), Feat.IsPurchaseFeatReqMet(), ModExp(), TraitDrinkMilkMother.OnDrink(), FoodEffect.Proc(), WidgetTracker.Refresh(), Remove(), TraitAbility.SetMainText(), ButtonAbility.SpecialHoldAction(), CalcPlat.Train(), Value(), ElementContainerCard.ValueBonus(), ValueWithoutLink(), and Element.BonusInfo.WriteNote().
GetFeatRef()
int ElementContainer.GetFeatRef (int ele, int idx = 0) inline
Definition at line 194 of file ElementContainer.cs.
    {
        if (!(GetElement(ele) is Feat feat))
        {
            return 0;
        }
        feat.Apply(feat.Value, this);
        return Feat.featRef[idx].ToInt();
    }
References Feat.featRef, and GetElement().
GetOrCreateElement() [1/3]
Element ElementContainer.GetOrCreateElement (Element ele) inline
Definition at line 500 of file ElementContainer.cs.
    {
        return GetOrCreateElement(ele.id);
    }
References GetOrCreateElement(), and Element.id.
Referenced by TraitAltar._OnOffer(), Element._WriteNote(), ApplyElementMap(), ApplyMaterialElementMap(), Card.ApplyProtection(), CoreDebug.Fix_EtherDisease(), GetOrCreateElement(), Element.GetParent(), ImportElementMap(), ModBase(), ModLink(), ModPotential(), ModTempPotential(), OnDeserialized(), TaskCraft.OnProgress(), TaskCraft.OnProgressComplete(), Act.Perform(), AttackProcess.Prepare(), ActEffect.Proc(), ItemCulture.Refresh(), WindowCharaMini.Refresh(), UIRecipeInfo.RefreshList(), WindowChara.RefreshProfile(), WindowChara.RefreshSkill(), AI_UseCrafter.Run(), SetBase(), Recipe.SetTextDifficulty(), SetTo(), Value(), Element.BonusInfo.WriteNote(), Thing.WriteNote(), and Recipe.WriteReqSkill().
GetOrCreateElement() [2/3]
Element ElementContainer.GetOrCreateElement (int id) inline
Definition at line 510 of file ElementContainer.cs.
    {
        Element value = null;
        if (!dict.TryGetValue(id, out value))
        {
            value = CreateElement(id);
        }
        return value;
    }
References CreateElement(), and dict.
GetOrCreateElement() [3/3]
Element ElementContainer.GetOrCreateElement (string alias) inline
Definition at line 505 of file ElementContainer.cs.
    {
        return GetOrCreateElement(EClass.sources.elements.alias[alias].id);
    }
References SourceManager.elements, GetOrCreateElement(), and EClass.sources.
GetSortVal()
static int ElementContainer.GetSortVal (Element a) inline static
Definition at line 651 of file ElementContainer.cs.
    {
        int num = a.Value;
        if (a.source.textAlt.Length <= 2 || a.Value < 0)
        {
            num -= 100000;
        }
        if (a.id == 2)
        {
            num += 20000;
        }
        if (a.IsFoodTraitMain)
        {
            num += 10000;
        }
        return num;
    }
References Element.id, Element.IsFoodTraitMain, Element.source, and Element.Value.
Referenced by AddNote(), and Thing.ListLimitedValidTraits().
GetSpellExp()
int ElementContainer.GetSpellExp (Chara c, Element e, int costMod = 100) inline
Definition at line 461 of file ElementContainer.cs.
    {
        Act.Cost cost = e.GetCost(c);
        int num = cost.cost * ((cost.type == Act.CostType.SP) ? 20 : 5) * (100 + c.Evalue(1208) * 30) / 100 + 10;
        num = num * costMod / 100;
        if (!e.source.aliasParent.IsEmpty())
        {
            int num2 = ValueWithoutLink(e.source.aliasParent) - ValueWithoutLink(e.source.id);
            num = ((num2 < 0) ? (num * 100 / (100 - num2 * 25)) : (num * (100 + num2 * 5) / 100));
        }
        if (num < 0)
        {
            num = 0;
        }
        return num;
    }
References Card.Evalue(), Element.GetCost(), Element.source, and ValueWithoutLink().
Referenced by ActMelee.Attack().
Has() [1/3]
bool ElementContainer.Has (int ele) inline
Definition at line 209 of file ElementContainer.cs.
    {
        Element element = GetElement(ele);
        if (element == null)
        {
            return false;
        }
        return element.Value > 0;
    }
References GetElement().
Referenced by Element.CheckLevelBonus(), Has(), BuildMenu.OnActivate(), HotbarManager.ResetHotbar(), AI_PassTime.Run(), Card.Teleport(), BuildMenu.Toggle(), and TraitFoodEgg.Update().
Has() [2/3]
bool ElementContainer.Has (SourceElement::Row row) inline
Definition at line 219 of file ElementContainer.cs.
    {
        return Has(row.id);
    }
References Has().
Has() [3/3]
bool ElementContainer.Has (string alias) inline
Definition at line 224 of file ElementContainer.cs.
    {
        return Has(EClass.sources.elements.alias[alias].id);
    }
References SourceManager.elements, Has(), and EClass.sources.
HasBase()
bool ElementContainer.HasBase (int ele) inline
Definition at line 229 of file ElementContainer.cs.
    {
        Element element = GetElement(ele);
        if (element == null)
        {
            return false;
        }
        int num = element.ValueWithoutLink;
        switch (ele)
        {
        case 300:
            num += Value(1516) * -4;
            num += Value(1517) * 4;
            break;
        case 307:
            num += Value(1524) * -4;
            num += Value(1525) * 4;
            break;
        }
        return num != 0;
    }
References GetElement(), Value(), and Element.ValueWithoutLink.
Referenced by ElementContainerCard.CheckSkillActions(), TraitBookSkill.OnRead(), TraitBookSkill.SetName(), TraitBookPlan.WriteNote(), and TraitBookSkill.WriteNote().
ImportElementMap() [1/2]
void ElementContainer.ImportElementMap (Dictionary< int, int > map) inline
Definition at line 129 of file ElementContainer.cs.
    {
        foreach (KeyValuePair<int, int> item in map)
        {
            GetOrCreateElement(item.Key).vSource += item.Value;
        }
    }
References GetOrCreateElement(), item, and Element.vSource.
Referenced by WindowChara.RefreshNote().
ImportElementMap() [2/2]
ElementContainer ElementContainer.ImportElementMap (int[] ints) inline
Definition at line 137 of file ElementContainer.cs.
    {
        for (int i = 0; i < ints.Length; i += 2)
        {
            GetOrCreateElement(ints[i]).vSource += ints[i + 1];
        }
        return this;
    }
References GetOrCreateElement(), and Element.vSource.
Learn()
void ElementContainer.Learn (int ele, int v = 1) inline
Definition at line 256 of file ElementContainer.cs.
    {
        ModBase(ele, v);
        OnLearn(ele);
    }
References ModBase(), and OnLearn().
Referenced by DNA.Apply(), Element.CheckLevelBonus(), Religion.JoinFaith(), and TraitBookSkill.OnRead().
ListBestAttributes()
List< Element > ElementContainer.ListBestAttributes () inline
Definition at line 607 of file ElementContainer.cs.
    {
        List<Element> obj = ListElements((Element a) => a.HasTag("primary"));
        obj.Sort((Element a, Element b) => (b.ValueWithoutLink - a.ValueWithoutLink) * 100000 + a.id - b.id);
        return obj;
    }
References Element.HasTag(), Element.id, ListElements(), and Element.ValueWithoutLink.
Referenced by AI_Fuck.Finish(), and TraitDrinkMilkMother.OnDrink().
ListBestSkills()
List< Element > ElementContainer.ListBestSkills () inline
Definition at line 614 of file ElementContainer.cs.
    {
        List<Element> obj = ListElements((Element a) => a.source.category == "skill");
        obj.Sort((Element a, Element b) => (b.ValueWithoutLink - a.ValueWithoutLink) * 100000 + a.id - b.id);
        return obj;
    }
References Element.id, ListElements(), Element.source, and Element.ValueWithoutLink.
Referenced by TraitDrinkMilkMother.OnDrink(), and LayerEmbark.RefreshMembers().
ListElements()
List< Element > ElementContainer.ListElements (Func< Element, bool > shoudList = null, Comparison< Element > comparison = null) inline
Definition at line 550 of file ElementContainer.cs.
    {
        List<Element> list = new List<Element>();
        List<Element> eles = dict.Values.ToList();
        if (Card != null && Card.Chara != null)
        {
            if (Card.Chara.IsPCFaction)
            {
                AddElements(EClass.pc.faction.charaElements, isGlobal: true);
            }
            AddElements(Card.Chara.faithElements, isGlobal: false);
        }
        foreach (Element item2 in eles)
        {
            if (shoudList == null || shoudList(item2))
            {
                list.Add(item2);
            }
        }
        if (comparison != null)
        {
            list.Sort(comparison);
        }
        return list;
        void AddElements(ElementContainer container, bool isGlobal)
        {
            if (container == null)
            {
                return;
            }
            foreach (Element value in container.dict.Values)
            {
                bool flag = true;
                foreach (Element item3 in eles)
                {
                    if (value.id == item3.id)
                    {
                        flag = false;
                        break;
                    }
                }
                if (flag && value.Value != 0)
                {
                    if (isGlobal)
                    {
                        Element item = Card.Chara.elements.CreateElement(value.id);
                        eles.Add(item);
                    }
                    else
                    {
                        eles.Add(value);
                    }
                }
            }
        }
    }
References Card.Chara, Faction.charaElements, CreateElement(), dict, Card.elements, Chara.faction, Chara.faithElements, Element.id, Chara.IsPCFaction, item, list, EClass.pc, and Element.Value.
Referenced by WidgetStatsBar.Build(), ListBestAttributes(), ListBestSkills(), ListGeneFeats(), ActEffect.Proc(), WindowCharaMini.Refresh(), WindowChara.RefreshSkill(), and WindowChara.RefreshStatic().
ListGeneFeats()
List< Element > ElementContainer.ListGeneFeats () inline
Definition at line 621 of file ElementContainer.cs.
    {
        return ListElements((Element a) => a.Value > 0 && a.source.category == "feat" && a.source.cost.Length != 0 && a.source.cost[0] > 0);
    }
References ListElements(), Element.source, and Element.Value.
ListLearnable()
List< Element > ElementContainer.ListLearnable (Chara c) inline
Definition at line 626 of file ElementContainer.cs.
    {
        List<Element> list = new List<Element>();
        foreach (KeyValuePair<int, Element> item in c.elements.dict)
        {
            if (!dict.ContainsKey(item.Key))
            {
                list.Add(item.Value);
            }
        }
        return list;
    }
References dict, item, and list.
ModBase()
Element ElementContainer.ModBase (int ele, int v) inline
Definition at line 401 of file ElementContainer.cs.
    {
        Element orCreateElement = GetOrCreateElement(ele);
        orCreateElement.vBase += v;
        if (parent != null && orCreateElement.CanLink(this))
        {
            parent.ModLink(ele, v);
        }
        orCreateElement.CheckLevelBonus(this);
        orCreateElement.OnChangeValue();
        if (orCreateElement.vBase == 0 && orCreateElement.vSource == 0 && orCreateElement.vLink == 0 && orCreateElement.vPotential == 0 && orCreateElement.vExp == 0)
        {
            Remove(orCreateElement.id);
        }
        return orCreateElement;
    }
References Element.CanLink(), Element.CheckLevelBonus(), GetOrCreateElement(), Element.id, ModLink(), Element.OnChangeValue(), parent, Remove(), Element.vBase, Element.vExp, Element.vLink, Element.vPotential, and Element.vSource.
Referenced by DNA.Apply(), Feat.Apply(), Thing.ApplyMaterial(), Card.ApplySocket(), TraitDrink.BlendLove(), TraitDrink.BlendPoison(), CoreDebug.COM_MaxConstruction(), Card.EjectSockets(), CoreDebug.Fix_EtherDisease(), AI_Shear.GetFur(), Learn(), Card.MakeFoodFrom(), Card.ModEncLv(), ModExp(), Chara.ModTempElement(), TraitDrinkMilkMother.OnDrink(), ElementContainerFaction.OnEquip(), ElementContainerFaction.OnUnequip(), ActEffect.Proc(), CoreDebug.QuickStart(), Chara.RefreshWorkElements(), AI_Idle.Run(), Card.SetBlessedState(), Card.SetLv(), Chara.SetMainElement(), SetTo(), ConDisease.Tick(), Map.TryShatter(), TraitFoodEgg.Update(), and FactionBranch.Upgrade().
ModExp()
void ElementContainer.ModExp (int ele, int a, bool chain = false) inline
Definition at line 268 of file ElementContainer.cs.
    {
        if ((Card != null && Card.isChara && Card.Chara.isDead) || a == 0)
        {
            return;
        }
        Element element = GetElement(ele);
        if (element == null || !element.CanGainExp)
        {
            return;
        }
        int value = (element.UsePotential ? element.Potential : 100);
        if (element.UseExpMod && a >= 0)
        {
            a = a * Mathf.Clamp(value, 10, 1000) / (100 + Mathf.Max(0, element.ValueWithoutLink) * 25);
            if (a >= 0 && EClass.rnd(element.ValueWithoutLink + 1) < 10)
            {
                a++;
            }
        }
        element.vExp += a;
        if (!chain && element.source.parentFactor > 0f && Card != null && !element.source.aliasParent.IsEmpty())
        {
            Element element2 = element.GetParent(Card);
            if (element2.CanGainExp)
            {
                ModExp(element2.id, (int)Math.Max(1f, (float)a * element.source.parentFactor / 100f), chain: true);
            }
        }
        if (element.vExp >= element.ExpToNext)
        {
            int num = element.vExp - element.ExpToNext;
            int vBase = element.vBase;
            ModBase(ele, 1);
            OnLevelUp(element, vBase);
            element.vExp = Mathf.Clamp(num / 2, 0, element.ExpToNext / 2);
            if (element.vTempPotential > 0)
            {
                element.vTempPotential -= element.vTempPotential / 4 + EClass.rnd(5) + 5;
                if (element.vTempPotential < 0)
                {
                    element.vTempPotential = 0;
                }
            }
            else if (element.vTempPotential < 0)
            {
                element.vTempPotential += -element.vTempPotential / 4 + EClass.rnd(5) + 5;
                if (element.vTempPotential > 0)
                {
                    element.vTempPotential = 0;
                }
            }
        }
        else if (element.vExp < 0)
        {
            if (element.ValueWithoutLink <= 1)
            {
                element.vExp = 0;
                return;
            }
            int vBase2 = element.vBase;
            ModBase(ele, -1);
            OnLevelDown(element, vBase2);
            element.vExp = Mathf.Max(element.ExpToNext / 2, element.ExpToNext + element.vExp);
        }
    }
References Element.CanGainExp, Card.Chara, Element.ExpToNext, GetElement(), Element.GetParent(), Element.id, Card.isChara, Chara.isDead, ModBase(), ModExp(), OnLevelDown(), OnLevelUp(), EClass.rnd(), Element.source, Element.UseExpMod, Element.ValueWithoutLink, Element.vBase, Element.vExp, and Element.vTempPotential.
Referenced by TraitAltar._OnOffer(), Chara.ApplyDeathPenalty(), Card.DamageHP(), AI_Fuck.Finish(), StatsMana.Mod(), Card.ModExp(), ModExp(), Player.MoveZone(), Policy.OnAdvanceHour(), TaskChopWood.OnCreateProgress(), TaskDig.OnCreateProgress(), TaskDrawWater.OnCreateProgress(), TaskHarvest.OnCreateProgress(), TaskMine.OnCreateProgress(), TaskPlow.OnCreateProgress(), TaskPourWater.OnCreateProgress(), TaskCraft.OnProgress(), AI_Fish.ProgressFish.OnProgressComplete(), TaskCraft.OnProgressComplete(), TaskDig.OnProgressComplete(), TaskMine.OnProgressComplete(), TraitBookSkill.OnRead(), TraitScrollStatic.OnRead(), FoodEffect.Proc(), AI_Fuck.Run(), AI_PlayMusic.Run(), AI_Shear.Run(), AI_Slaughter.Run(), AI_Steal.Run(), AI_UseCrafter.Run(), and Card.SpawnLoot().
ModLink()
Element ElementContainer.ModLink (int id, int v) inline private
Definition at line 449 of file ElementContainer.cs.
    {
        Element orCreateElement = GetOrCreateElement(id);
        orCreateElement.vLink += v;
        orCreateElement.OnChangeValue();
        if (parent != null && orCreateElement.CanLink(this))
        {
            parent.ModLink(id, v);
        }
        return orCreateElement;
    }
References Element.CanLink(), GetOrCreateElement(), ModLink(), Element.OnChangeValue(), and parent.
Referenced by ModBase(), ModLink(), Remove(), SetBase(), and SetParent().
ModPotential()
Element ElementContainer.ModPotential (int ele, int v) inline
Definition at line 422 of file ElementContainer.cs.
    {
        Element orCreateElement = GetOrCreateElement(ele);
        orCreateElement.vPotential += v;
        if (orCreateElement.vPotential > 1000)
        {
            orCreateElement.vPotential = 1000;
        }
        return orCreateElement;
    }
References GetOrCreateElement(), and Element.vPotential.
Referenced by Feat.Apply(), and FoodEffect.Proc().
ModTempPotential()
Element ElementContainer.ModTempPotential (int ele, int v, int threshMsg = 0) inline
Definition at line 433 of file ElementContainer.cs.
    {
        Element orCreateElement = GetOrCreateElement(ele);
        orCreateElement.vTempPotential += v;
        if (orCreateElement.vTempPotential > 1000)
        {
            orCreateElement.vTempPotential = 1000;
        }
        OnModTempPotential(orCreateElement, v, threshMsg);
        return orCreateElement;
    }
References GetOrCreateElement(), OnModTempPotential(), and Element.vTempPotential.
Referenced by AI_Fuck.Finish(), FoodEffect.Proc(), ActEffect.Proc(), AI_Idle.Run(), and Train().
OnChangeValue()
virtual void ElementContainer.OnChangeValue () inline virtual
Definition at line 418 of file ElementContainer.cs.
    {
    }
OnDeserialized()
void ElementContainer.OnDeserialized (StreamingContext context) inline private
Definition at line 53 of file ElementContainer.cs.
    {
        if (list == null)
        {
            return;
        }
        for (int i = 0; i < list.Count; i += 5)
        {
            Element orCreateElement = GetOrCreateElement(list[i]);
            if (orCreateElement != null)
            {
                orCreateElement.vBase += list[i + 1];
                orCreateElement.vExp += list[i + 2];
                orCreateElement.vPotential += list[i + 3];
                orCreateElement.vTempPotential = list[i + 4];
                orCreateElement.owner = this;
            }
        }
    }
References GetOrCreateElement(), and list.
OnLearn()
virtual void ElementContainer.OnLearn (int ele) inline virtual
Reimplemented in ElementContainerCard, and ElementContainerZone.
Definition at line 335 of file ElementContainer.cs.
    {
    }
Referenced by Learn().
OnLevelDown()
virtual void ElementContainer.OnLevelDown (Element e, int lastValue) inline virtual
Reimplemented in ElementContainerCard.
Definition at line 347 of file ElementContainer.cs.
    {
    }
Referenced by ModExp().
OnLevelUp()
virtual void ElementContainer.OnLevelUp (Element e, int lastValue) inline virtual
Reimplemented in ElementContainerCard, and ElementContainerZone.
Definition at line 343 of file ElementContainer.cs.
    {
    }
Referenced by ModExp().
OnModTempPotential()
virtual void ElementContainer.OnModTempPotential (Element e, int v, int threshMsg) inline virtual
Reimplemented in ElementContainerCard.
Definition at line 445 of file ElementContainer.cs.
    {
    }
Referenced by ModTempPotential().
OnSerializing()
void ElementContainer.OnSerializing (StreamingContext context) inline private
Definition at line 36 of file ElementContainer.cs.
    {
        list = new List<int>();
        foreach (Element value in dict.Values)
        {
            if (value.vBase != 0 || value.vExp != 0 || value.vPotential != 0 || value.vTempPotential != 0)
            {
                list.AddRange(new int[5] { value.id, value.vBase, value.vExp, value.vPotential, value.vTempPotential });
            }
        }
        if (list.Count == 0)
        {
            list = null;
        }
    }
References dict, Element.id, list, Element.vBase, Element.vExp, Element.vPotential, and Element.vTempPotential.
OnTrain()
virtual void ElementContainer.OnTrain (int ele) inline virtual
Reimplemented in ElementContainerCard.
Definition at line 339 of file ElementContainer.cs.
    {
    }
Referenced by Train().
Remove()
void ElementContainer.Remove (int id) inline
Definition at line 388 of file ElementContainer.cs.
    {
        Element element = GetElement(id);
        if (element != null)
        {
            if (parent != null && element.CanLink(this))
            {
                parent.ModLink(id, -element.Value);
            }
            dict.Remove(id);
        }
    }
References Element.CanLink(), dict, GetElement(), ModLink(), parent, and Element.Value.
Referenced by ApplyMaterialElementMap(), Card.CheckJustCooked(), ModBase(), Chara.ModTempElement(), Trait.OnBarter(), Player.OnStartNewGame(), LayerCraft.RefreshProduct(), SetBase(), and SetTo().
SetBase() [1/2]
Element ElementContainer.SetBase (int id, int v, int potential = 0) inline
Definition at line 356 of file ElementContainer.cs.
    {
        Element orCreateElement = GetOrCreateElement(id);
        if (parent != null && orCreateElement.CanLink(this))
        {
            parent.ModLink(id, -orCreateElement.vBase + v);
        }
        orCreateElement.vBase = v;
        orCreateElement.vExp = 0;
        orCreateElement.vPotential = potential;
        orCreateElement.OnChangeValue();
        if (orCreateElement.vBase == 0 && orCreateElement.vSource == 0 && orCreateElement.vLink == 0 && orCreateElement.vPotential == 0 && orCreateElement.vExp == 0)
        {
            Remove(orCreateElement.id);
        }
        return orCreateElement;
    }
References Element.CanLink(), GetOrCreateElement(), Element.id, ModLink(), Element.OnChangeValue(), parent, Remove(), Element.vBase, Element.vExp, Element.vLink, Element.vPotential, and Element.vSource.
SetBase() [2/2]
Element ElementContainer.SetBase (string alias, int v, int potential = 0) inline
Definition at line 351 of file ElementContainer.cs.
    {
        return SetBase(EClass.sources.elements.alias[alias].id, v, potential);
    }
References SourceManager.elements, SetBase(), and EClass.sources.
Referenced by TraitAltar._OnOffer(), PolicyManager.AddPolicy(), Thing.ApplyMaterial(), TraitTrainingDummyArmor.CalcPV(), ElementContainerCard.CheckSkillActions(), Card.Decay(), DramaOutcome.fiama_starter_gift(), TaskHarvest.HarvestThing(), Religion.LeaveFaith(), CraftUtil.MakeDish(), Card.MakeFoodFrom(), TraitSeed.MakeSeed(), Trait.OnBarter(), ConFreeze.OnChangePhase(), ConPoison.OnChangePhase(), TraitToolRangeCane.OnCreate(), Player.OnStartNewGame(), CoreDebug.QuickStart(), Chara.RefreshFaithElement(), SetBase(), CoreDebug.SetElement(), Chara.SetMainElement(), BaseCondition.SetOwner(), ConBuffStats.SetOwner(), CoreDebug.UpdateInput(), and TraitWrench.Upgrade().
SetParent() [1/2]
void ElementContainer.SetParent (Card c) inline
Definition at line 520 of file ElementContainer.cs.
    {
        SetParent(c?.elements);
    }
References SetParent().
Referenced by Thing.ApplyMaterialElements(), CharaBody.Equip(), Condition.Kill(), Chara.ModTempElement(), Chara.OnDeserialized(), ConDisease.OnRemoved(), Chara.RefreshFaithElement(), Chara.RefreshWorkElements(), BaseCondition.SetOwner(), ConBuffStats.SetOwner(), ConDisease.SetOwner(), CharaBody.SetOwner(), SetParent(), and CharaBody.Unequip().
SetParent() [2/2]
void ElementContainer.SetParent (ElementContainer newParent = null) inline
Definition at line 525 of file ElementContainer.cs.
    {
        if (parent != null)
        {
            foreach (Element value in dict.Values)
            {
                if (value.CanLink(this))
                {
                    parent.ModLink(value.id, -(value.vBase + value.vSource));
                }
            }
        }
        if (newParent != null)
        {
            foreach (Element value2 in dict.Values)
            {
                if (value2.CanLink(this))
                {
                    newParent.ModLink(value2.id, value2.vBase + value2.vSource);
                }
            }
        }
        parent = newParent;
    }
References Element.CanLink(), dict, Element.id, ModLink(), parent, Element.vBase, and Element.vSource.
SetTo()
void ElementContainer.SetTo (int id, int v) inline
Definition at line 374 of file ElementContainer.cs.
    {
        Element orCreateElement = GetOrCreateElement(id);
        int num = v - (orCreateElement.vBase + orCreateElement.vSource);
        if (num != 0)
        {
            ModBase(id, num);
        }
        if (orCreateElement.vBase == 0 && orCreateElement.vSource == 0 && orCreateElement.vLink == 0 && orCreateElement.vPotential == 0 && orCreateElement.vExp == 0)
        {
            Remove(orCreateElement.id);
        }
    }
References GetOrCreateElement(), Element.id, ModBase(), Remove(), Element.vBase, Element.vExp, Element.vLink, Element.vPotential, and Element.vSource.
Referenced by DNA.GenerateWithGene(), TraitSeed.MakeSeed(), TraitAgingShelf.OnProduce(), and TraitDryBrick.OnProduce().
Train()
void ElementContainer.Train (int ele, int a = 10) inline
Definition at line 262 of file ElementContainer.cs.
    {
        OnTrain(ele);
        ModTempPotential(ele, a);
    }
References ModTempPotential(), and OnTrain().
Value()
int ElementContainer.Value (int ele) inline
Definition at line 157 of file ElementContainer.cs.
    {
        Element element = GetElement(ele);
        if (element == null)
        {
            if (EClass.core.game == null)
            {
                return 0;
            }
            if (Card == null || !Card.IsPCFactionOrMinion)
            {
                return 0;
            }
            if (ele != 78)
            {
                return EClass.pc.faction.charaElements.Value(ele);
            }
            return GetOrCreateElement(ele).Value;
        }
        return element.Value;
    }
References Faction.charaElements, EClass.core, Chara.faction, Core.game, GetElement(), GetOrCreateElement(), Card.IsPCFactionOrMinion, EClass.pc, Element.Value, and Value().
Referenced by Element._WriteNote(), Card.Evalue(), FactionBranch.Evalue(), Card.GetBestAttribute(), Zone.GetElectricity(), HasBase(), Card.HasElement(), Feat.IsPurchaseFeatReqMet(), WidgetStatsBar.Refresh(), Zone.RefreshElectricity(), Value(), Element.BonusInfo.WriteNote(), Element.WriteNoteWithRef(), and Feat.WritePurchaseReq().
ValueBonus()
virtual int ElementContainer.ValueBonus (Element e) inline virtual
Reimplemented in ElementContainerCard.
Definition at line 179 of file ElementContainer.cs.
    {
        return 0;
    }
ValueWithoutLink() [1/2]
int ElementContainer.ValueWithoutLink (int ele) inline
Definition at line 184 of file ElementContainer.cs.
    {
        return GetElement(ele)?.ValueWithoutLink ?? 0;
    }
References GetElement(), and Element.ValueWithoutLink.
Referenced by DNA.Apply(), ElementContainerCard.CheckSkillActions(), Card.DamageHP(), AI_Fuck.Finish(), GetSpellExp(), AttackProcess.Perform(), ButtonElement.Refresh(), and Chara.RefreshSpeed().
ValueWithoutLink() [2/2]
int ElementContainer.ValueWithoutLink (string alias) inline
Definition at line 189 of file ElementContainer.cs.
    {
        return GetElement(alias)?.ValueWithoutLink ?? 0;
    }
References GetElement(), and Element.ValueWithoutLink.
Member Data Documentation
dict
Dictionary<int, Element> ElementContainer.dict = new Dictionary<int, Element>()
Definition at line 20 of file ElementContainer.cs.
Referenced by AddNote(), Feat.Apply(), Chara.ApplyDeathPenalty(), ApplyPotential(), Chara.CalculateMaxStamina(), Thing.CanStackTo(), TraitAmmo.CanStackTo(), CopyTo(), CreateElement(), Chara.DiminishTempElements(), Chara.Duplicate(), CoreDebug.Fix_EtherDisease(), Card.GetBestAttribute(), GetElement(), GetOrCreateElement(), Card.GetValue(), Chara.GiveGift(), Element.IsFactionElement(), ListElements(), ListLearnable(), TraitSeed.MakeSeed(), CraftUtil.MixIngredients(), Chara.ModTempElement(), OnSerializing(), Player.OnStartNewGame(), AttackProcess.Perform(), AttackProcess.PlayRangedAnime(), FoodEffect.Proc(), ActEffect.Proc(), LayerHome.RefreshFeat(), LayerCraft.RefreshProduct(), Remove(), AI_Eat.Run(), AI_Idle.Run(), LayerAbility.SelectGroup(), Card.SetLv(), SetParent(), and Element.BonusInfo.WriteNote().
list
List<int> ElementContainer.list
Definition at line 27 of file ElementContainer.cs.
Referenced by AddNote(), ListElements(), ListLearnable(), OnDeserialized(), and OnSerializing().
parent
ElementContainer ElementContainer.parent
Definition at line 22 of file ElementContainer.cs.
Referenced by ModBase(), ModLink(), Remove(), SetBase(), and SetParent().
sizeElement
const int ElementContainer.sizeElement = 5 static
Definition at line 24 of file ElementContainer.cs.
Property Documentation
Card
virtual Card ElementContainer.Card get
Definition at line 29 of file ElementContainer.cs.
Referenced by Feat.Apply(), Ability.CanLink(), Ability.OnChangeValue(), RaceBonus.OnWriteNote(), and ButtonElement.Refresh().
Chara
virtual Chara ElementContainer.Chara get
Definition at line 31 of file ElementContainer.cs.
Referenced by Element._WriteNote(), Feat.Apply(), AttbMain.OnChangeValue(), and Skill.OnChangeValue().
IsMeleeWeapon
virtual bool ElementContainer.IsMeleeWeapon get
Definition at line 33 of file ElementContainer.cs.
Referenced by AttbWeapon.CanLink().
The documentation for this class was generated from the following file:
Elin/ElementContainer.cs