Elin Decompiled Documentation: AI_Goto Class Reference
AI_Goto Class Reference
Public Member Functions
override bool CanManualCancel ()
override Point GetDestination ()
AI_Goto (Point _dest, int dist, bool _ignoreConnection=false, bool _interaction=false)
AI_Goto (Card _card, int dist, bool _ignoreConnection=false, bool _interaction=false)
override void OnReset ()
Status TryGoTo ()
bool IsDestinationReached ()
override IEnumerable< Status > Run ()
Public Member Functions inherited from AIAct
override string ToString ()
override MultiSprite GetStateIcon ()
virtual Point GetDestination ()
AIProgress GetProgress ()
string GetCurrentActionText ()
override bool IsToolValid ()
virtual void OnStart ()
void SetOwner (Chara c)
virtual void OnSetOwner ()
void SetChild (AIAct seq, Func< Status > _onChildFail=null)
void Start ()
override bool Perform ()
Status Restart ()
Status Success (Action action=null)
virtual void OnSuccess ()
bool TryCancel (Card c)
virtual Status Cancel ()
virtual void OnCancel ()
virtual void OnCancelOrSuccess ()
virtual bool CanManualCancel ()
Status KeepRunning ()
void Reset ()
virtual void OnReset ()
Status Tick ()
virtual IEnumerable< Status > Run ()
Status TickChild ()
Status Do (AIAct _seq, Func< Status > _onChildFail=null)
Status DoGotoInteraction (Point pos, Func< Status > _onChildFail=null)
Status DoGoto (Point pos, int dist=0, bool ignoreConnection=false, Func< Status > _onChildFail=null)
Status DoGoto (Card card, Func< Status > _onChildFail=null)
Status DoGoto (Card card, int dist, Func< Status > _onChildFail=null)
Status DoGotoSpot (Card card, Func< Status > _onChildFail=null)
Status DoGoto< T > (Func< Status > _onChildFail=null)
Status DoGotoSpot< T > (Func< Status > _onChildFail=null, bool ignoreAccessType=false)
Status DoGrab (Card card, int num=-1, bool pickHeld=false, Func< Status > _onChildFail=null)
Status DoGrab< T > ()
Status DoProgress ()
Status DoIdle (int repeat=3)
Status DoWait (int count=1)
virtual AIProgress CreateProgress ()
virtual void OnCreateProgress (Progress_Custom p)
virtual bool CanProgress ()
virtual void OnBeforeProgress ()
virtual void OnProgress ()
virtual void OnProgressComplete ()
void SimulateZone (int days)
virtual void OnSimulateZone (int days)
virtual void OnSimulatePosition ()
Public Member Functions inherited from Act
virtual CursorInfo GetCursorIcon (Card c)
virtual MultiSprite GetStateIcon ()
override Sprite GetSprite ()
virtual bool ShowMouseHint (Card c)
virtual bool IsValidTC (Card c)
virtual string GetHintText (string str="")
virtual string GetText (string str="")
virtual string GetTextSmall (Card c)
virtual Color GetActPlanColor ()
virtual bool Perform ()
virtual bool CanPerform ()
bool Perform (Chara _cc, Card _tc=null, Point _tp=null)
bool CanPerform (Chara _cc, Card _tc=null, Point _tp=null)
virtual bool IsToolValid ()
new void SetImage (Image image)
virtual void OnMarkMapHighlights ()
virtual bool ShouldMapHighlight (Point p)
virtual CursorInfo GetCursorIcon (Card c)
virtual MultiSprite GetStateIcon ()
override Sprite GetSprite ()
virtual bool ShowMouseHint (Card c)
virtual bool IsValidTC (Card c)
virtual string GetHintText (string str="")
virtual string GetText (string str="")
virtual string GetTextSmall (Card c)
virtual Color GetActPlanColor ()
virtual bool Perform ()
virtual bool CanPerform ()
bool Perform (Chara _cc, Card _tc=null, Point _tp=null)
bool CanPerform (Chara _cc, Card _tc=null, Point _tp=null)
virtual bool IsToolValid ()
new void SetImage (Image image)
virtual void OnMarkMapHighlights ()
virtual bool ShouldMapHighlight (Point p)
Public Member Functions inherited from Element
virtual SourceElement.Row GetSource ()
virtual int GetSourcePotential (int v)
virtual Sprite GetSprite ()
int GetMaterialSourceValue (Thing t, int v)
virtual int GetSourceValue (int v, int lv, SourceValueType type)
virtual Sprite GetIcon (string suffix="")
int SortVal (bool charaSheet=false)
virtual bool CanLink (ElementContainer owner)
bool HasTag (string tag)
void SetImage (Image i)
virtual string GetDetail ()
bool IsFactionElement (Chara c)
Element GetParent (Card c)
void WriteNote (UINote n, ElementContainer owner=null, Action< UINote > onWriteNote=null)
void WriteNoteWithRef (UINote n, ElementContainer owner, Action< UINote > onWriteNote, Element refEle)
void _WriteNote (UINote n, Chara c, Act act)
void _WriteNote (UINote n, ElementContainer owner, Action< UINote > onWriteNote, bool isRef, bool addHeader=true)
virtual void OnWriteNote (UINote n, ElementContainer owner)
virtual void OnChangeValue ()
void CheckLevelBonus (ElementContainer owner, UINote n=null)
int GetSortVal (UIList.SortMode m)
virtual Act.Cost GetCost (Chara c)
virtual int GetPower (Card c)
virtual void SetTextValue (UIText text)
virtual SourceElement.Row GetSource ()
virtual int GetSourcePotential (int v)
virtual Sprite GetSprite ()
int GetMaterialSourceValue (Thing t, int v)
virtual int GetSourceValue (int v, int lv, SourceValueType type)
virtual Sprite GetIcon (string suffix="")
int SortVal (bool charaSheet=false)
virtual bool CanLink (ElementContainer owner)
bool HasTag (string tag)
void SetImage (Image i)
virtual string GetDetail ()
bool IsFactionElement (Chara c)
Element GetParent (Card c)
void WriteNote (UINote n, ElementContainer owner=null, Action< UINote > onWriteNote=null)
void WriteNoteWithRef (UINote n, ElementContainer owner, Action< UINote > onWriteNote, Element refEle)
void _WriteNote (UINote n, Chara c, Act act)
void _WriteNote (UINote n, ElementContainer owner, Action< UINote > onWriteNote, bool isRef, bool addHeader=true)
virtual void OnWriteNote (UINote n, ElementContainer owner)
virtual void OnChangeValue ()
void CheckLevelBonus (ElementContainer owner, UINote n=null)
int GetSortVal (UIList.SortMode m)
virtual Act.Cost GetCost (Chara c)
virtual int GetPower (Card c)
virtual void SetTextValue (UIText text)
Public Attributes
Card destCard
Point dest = new Point()
int destDist
int waitCount
bool ignoreConnection
bool interaction
bool repath
Public Attributes inherited from AIAct
new Chara owner
Status status
IEnumerator< Status > Enumerator
AIAct child
AIAct parent
byte restartCount
Func< Status > onChildFail
Func< bool > isFail
Public Attributes inherited from Element
SourceElement.Row _source
int id
int vBase
int vExp
int vPotential
int vTempPotential
int vLink
int vSource
int vSourcePotential
ElementContainer owner
Properties
override bool UseTurbo [get]
override bool CancelWhenDamaged [get]
override bool CancelWhenMoved [get]
override bool InformCancel [get]
override bool PushChara [get]
Properties inherited from AIAct
virtual bool IsRunning [get]
bool IsChildRunning [get]
bool IsMoveAI [get]
virtual int MaxRestart [get]
virtual new string Name [get]
virtual MultiSprite stateIcon [get]
virtual Sprite actionIcon [get]
virtual bool IsNoGoal [get]
virtual bool IsAutoTurn [get]
virtual bool IsIdle [get]
virtual bool CancelOnAggro [get]
virtual bool PushChara [get]
virtual int MaxProgress [get]
virtual bool ShowProgress [get]
virtual bool UseTurbo [get]
virtual int CurrentProgress [get]
virtual bool ShowCursor [get]
virtual bool CancelWhenDamaged [get]
virtual bool CancelWhenMoved [get]
virtual bool InformCancel [get]
virtual Thing RenderThing [get]
AIAct Current [get]
override bool IsAct [get]
override bool ShowPotential [get]
override bool UsePotential [get]
override bool ShowRelativeAttribute [get]
virtual bool HasProgress [get]
Properties inherited from Act
override bool ShowPotential [get]
override bool UsePotential [get]
override bool ShowRelativeAttribute [get]
virtual CursorInfo CursorIcon [get]
virtual string ID [get]
virtual bool IsAct [get]
virtual bool WillEndTurn [get]
virtual bool CloseLayers [get]
virtual int LeftHand [get]
virtual int RightHand [get]
virtual int ElementPowerMod [get]
virtual bool ShowMapHighlight [get]
virtual bool ShowMapHighlightBlock [get]
virtual bool PickHeldOnStart [get]
virtual bool DropHeldOnStart [get]
virtual bool CanPressRepeat [get]
virtual bool CanAutofire [get]
virtual bool ResetAxis [get]
virtual bool RequireTool [get]
virtual bool IsHostileAct [get]
virtual bool HideRightInfo [get]
virtual bool HaveLongPressAction [get]
virtual float Radius [get]
virtual int PerformDistance [get]
virtual int MaxRadius [get]
virtual TargetType TargetType [get]
virtual bool LocalAct [get]
virtual bool CanRapidFire [get]
virtual float RapidDelay [get]
virtual bool ShowAuto [get]
virtual bool IsCrime [get]
Properties inherited from Element
SourceElement.Row source [get]
virtual int DisplayValue [get]
virtual int MinValue [get]
int Value [get]
int ValueWithoutLink [get]
virtual int MinPotential [get]
int Potential [get]
virtual bool CanGainExp [get]
bool IsFlag [get]
virtual string Name [get]
virtual string FullName [get]
virtual int ExpToNext [get]
virtual bool UseExpMod [get]
virtual int CostTrain [get]
virtual int CostLearn [get]
virtual bool ShowXP [get]
virtual bool ShowMsgOnValueChanged [get]
virtual bool ShowValue [get]
virtual bool ShowPotential [get]
virtual bool UsePotential [get]
virtual bool PotentialAsStock [get]
virtual bool ShowRelativeAttribute [get]
virtual bool ShowBonuses [get]
virtual string ShortName [get]
bool IsGlobalElement [get]
bool IsFactionWideElement [get]
bool IsPartyWideElement [get]
virtual bool ShowEncNumber [get]
bool IsTrait [get]
bool IsFoodTrait [get]
bool IsFoodTraitMain [get]
bool IsMainAttribute [get]
Act act [get]
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Additional Inherited Members
Public Types inherited from AIAct
enum Status { Running , Fail , Success }
Public Types inherited from Act
enum CostType {
None , MP , SP , None ,
MP , SP
}
enum CostType {
None , MP , SP , None ,
MP , SP
}
Static Public Member Functions inherited from Act
static void SetReference (Chara _cc, Card _tc=null, Point _tp=null)
static void SetTool (Thing t)
static void SetReference (Chara _cc, Card _tc=null, Point _tp=null)
static void SetTool (Thing t)
Static Public Member Functions inherited from Element
static string GetName (string alias)
static SourceElement.Row Get (int id)
static Dictionary< int, int > GetElementMap (int[] list)
static Dictionary< int, int > GetElementMap (int[] list, Dictionary< int, int > map)
static SourceElement.Row GetRandomElement (int lv=1)
static Element Create (int id, int v=0)
static Element Create (string id, int v=1)
static int GetId (string alias)
static int GetResistLv (int v)
static int GetResistDamage (int dmg, int v)
static string GetName (string alias)
static SourceElement.Row Get (int id)
static Dictionary< int, int > GetElementMap (int[] list)
static Dictionary< int, int > GetElementMap (int[] list, Dictionary< int, int > map)
static SourceElement.Row GetRandomElement (int lv=1)
static Element Create (int id, int v=0)
static Element Create (string id, int v=1)
static int GetId (string alias)
static int GetResistLv (int v)
static int GetResistDamage (int dmg, int v)
Static Public Member Functions inherited from EClass
static int rnd (int a)
static int curve (int a, int start, int step, int rate=75)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Static Public Attributes inherited from Act
static Chara CC
static Card TC
static Point TP = new Point()
static Thing TOOL
static int powerMod = 100
static bool forcePt
Static Public Attributes inherited from Element
const int Div = 5
static Element Void = new Element()
static int[] List_MainAttributes
static int[] List_MainAttributesMajor
static int[] List_Body
static int[] List_Mind
static List< SourceElement.Row > ListElements = new List<SourceElement.Row>()
static List< SourceElement.Row > ListAttackElements = new List<SourceElement.Row>()
Static Public Attributes inherited from EClass
static Core core
Static Package Functions inherited from Element
static string< _WriteNote > g__Calc (ref Element.<>c__DisplayClass103_0 A_0)
Detailed Description
Definition at line 4 of file AI_Goto.cs.
Constructor & Destructor Documentation
AI_Goto() [1/2]
AI_Goto.AI_Goto (Point _dest, int dist, bool _ignoreConnection = false, bool _interaction = false) inline
Definition at line 44 of file AI_Goto.cs.
    {
        dest.Set(_dest);
        destDist = dist;
        ignoreConnection = _ignoreConnection;
        interaction = _interaction;
    }
References dest, destDist, ignoreConnection, interaction, and Point.Set().
AI_Goto() [2/2]
AI_Goto.AI_Goto (Card _card, int dist, bool _ignoreConnection = false, bool _interaction = false) inline
Definition at line 52 of file AI_Goto.cs.
    {
        destCard = _card;
        destDist = dist;
        ignoreConnection = _ignoreConnection;
        interaction = _interaction;
    }
References destCard, destDist, ignoreConnection, and interaction.
Member Function Documentation
CanManualCancel()
override bool AI_Goto.CanManualCancel () inline virtual
Reimplemented from AIAct.
Definition at line 30 of file AI_Goto.cs.
    {
        return true;
    }
GetDestination()
override Point AI_Goto.GetDestination () inline virtual
Reimplemented from AIAct.
Definition at line 35 of file AI_Goto.cs.
    {
        if (destCard != null)
        {
            return destCard.pos;
        }
        return dest;
    }
References dest, destCard, and Card.pos.
Referenced by Run().
IsDestinationReached()
bool AI_Goto.IsDestinationReached () inline
Definition at line 156 of file AI_Goto.cs.
    {
        if (destCard != null)
        {
            int num = destCard.pos.Distance(owner.pos);
            if (interaction && num == 1 && owner.CanInteractTo(owner.pos))
            {
                return true;
            }
            return num <= destDist;
        }
        int num2 = Util.Distance(owner.pos.x, owner.pos.z, dest.x, dest.z);
        if (interaction && num2 == 1 && owner.CanInteractTo(dest))
        {
            return true;
        }
        return num2 <= destDist;
    }
References Chara.CanInteractTo(), dest, destCard, destDist, Point.Distance(), interaction, AIAct.owner, Card.pos, Point.x, and Point.z.
Referenced by Run(), and TryGoTo().
OnReset()
override void AI_Goto.OnReset () inline virtual
Reimplemented from AIAct.
Definition at line 60 of file AI_Goto.cs.
    {
        owner.path.state = PathProgress.State.Idle;
    }
Run()
override IEnumerable< Status > AI_Goto.Run () inline virtual
Reimplemented from AIAct.
Definition at line 175 of file AI_Goto.cs.
    {
        if (owner.host != null)
        {
            yield return Cancel();
        }
        while (true)
        {
            if (destCard != null)
            {
                dest.Set(GetDestination());
            }
            while (owner.path.state == PathProgress.State.Searching)
            {
                yield return Status.Running;
            }
            owner.path.state = PathProgress.State.Idle;
            if (IsDestinationReached())
            {
                yield return Success();
            }
            EClass.player.enemySpotted = false;
            while (true)
            {
                if (owner.IsPC)
                {
                    if (EClass.player.TooHeavyToMove())
                    {
                        yield return Cancel();
                    }
                    if (EClass.player.enemySpotted)
                    {
                        EClass.player.enemySpotted = false;
                        Msg.Say("enemy_spotted");
                        yield return Cancel();
                    }
                }
                yield return TryGoTo();
                if (destCard != null)
                {
                    Point destination = GetDestination();
                    int num = dest.Distance(destination);
                    if (num > 3 && num < 20)
                    {
                        break;
                    }
                }
            }
            repath = true;
            owner.path.state = PathProgress.State.Idle;
        }
    }
References AIAct.Cancel(), dest, destCard, Point.Distance(), Player.enemySpotted, GetDestination(), Chara.host, IsDestinationReached(), Chara.IsPC, AIAct.owner, Chara.path, EClass.player, repath, Msg.Say(), Point.Set(), PathProgress.state, AIAct.Success, Player.TooHeavyToMove(), and TryGoTo().
TryGoTo()
Status AI_Goto.TryGoTo () inline
Definition at line 65 of file AI_Goto.cs.
    {
        PathProgress path = owner.path;
        Point pos = owner.pos;
        if (owner.IsPC)
        {
            if (dest.x > EClass._map.bounds.maxX + 1)
            {
                dest.x = EClass._map.bounds.maxX + 1;
            }
            else if (dest.x < EClass._map.bounds.x - 1)
            {
                dest.x = EClass._map.bounds.x - 1;
            }
            if (dest.z > EClass._map.bounds.maxZ + 1)
            {
                dest.z = EClass._map.bounds.maxZ + 1;
            }
            else if (dest.z < EClass._map.bounds.z - 1)
            {
                dest.z = EClass._map.bounds.z - 1;
            }
        }
        if ((repath || (owner.IsPC && ActionMode.IsAdv)) && path.state == PathProgress.State.Idle)
        {
            path.RequestPathImmediate(pos, dest, destDist, ignoreConnection);
            repath = false;
        }
        switch (path.state)
        {
        case PathProgress.State.Idle:
            path.RequestPath(pos, dest, destDist, ignoreConnection);
            break;
        case PathProgress.State.Fail:
            return Cancel();
        case PathProgress.State.PathReady:
        {
            if (path.nodeIndex < 0)
            {
                return Cancel();
            }
            PathFinderNode pathFinderNode = path.nodes[path.nodeIndex];
            if (owner.IsPC && ActionMode.IsAdv && path.nodeIndex > 2)
            {
                ActionMode.Adv.SetTurbo();
            }
            Point shared = Point.GetShared(pathFinderNode.X, pathFinderNode.Z);
            if (shared.x == owner.pos.x && shared.z == owner.pos.z && path.nodeIndex > 0 && !shared.cell.HasLadder && !owner.Cell.HasLadder)
            {
                path.nodeIndex--;
                pathFinderNode = path.nodes[path.nodeIndex];
                shared.Set(pathFinderNode.X, pathFinderNode.Z);
            }
            if (shared.HasChara && !owner.IsPC)
            {
                waitCount++;
                if (waitCount < 3 || EClass.rnd(5) != 0)
                {
                    return Status.Running;
                }
            }
            waitCount = 0;
            Card.MoveResult moveResult = owner.TryMove(shared);
            if (owner == null)
            {
                return Status.Running;
            }
            if (moveResult == Card.MoveResult.Fail || moveResult == Card.MoveResult.Door)
            {
                if (owner.IsPC && ActionMode.IsAdv)
                {
                    return Cancel();
                }
                return Restart();
            }
            if (!owner.pos.Equals(shared))
            {
                path.state = PathProgress.State.Idle;
                repath = true;
            }
            path.nodeIndex--;
            if (IsDestinationReached())
            {
                return Success();
            }
            break;
        }
        }
        return Status.Running;
    }
References EClass._map, ActionMode.Adv, Map.bounds, AIAct.Cancel(), Card.Cell, Point.cell, dest, destDist, Point.Equals(), Point.GetShared(), Point.HasChara, Cell.HasLadder, ignoreConnection, ActionMode.IsAdv, IsDestinationReached(), Chara.IsPC, MapBounds.maxX, MapBounds.maxZ, PathProgress.nodeIndex, PathProgress.nodes, AIAct.owner, Chara.path, Card.pos, repath, PathProgress.RequestPath(), PathProgress.RequestPathImmediate(), AIAct.Restart(), EClass.rnd(), Point.Set(), AM_Adv.SetTurbo(), PathProgress.state, AIAct.Success, Chara.TryMove(), waitCount, Algorithms.PathFinderNode.X, MapBounds.x, Point.x, Algorithms.PathFinderNode.Z, MapBounds.z, and Point.z.
Referenced by Run().
Member Data Documentation
dest
Point AI_Goto.dest = new Point()
Definition at line 8 of file AI_Goto.cs.
Referenced by AI_Goto(), GetDestination(), IsDestinationReached(), TraitNewZone.OnStepped(), Run(), and TryGoTo().
destCard
Card AI_Goto.destCard
Definition at line 6 of file AI_Goto.cs.
Referenced by AI_Goto(), GetDestination(), IsDestinationReached(), and Run().
destDist
int AI_Goto.destDist
Definition at line 10 of file AI_Goto.cs.
Referenced by AI_Goto(), IsDestinationReached(), and TryGoTo().
ignoreConnection
bool AI_Goto.ignoreConnection
Definition at line 14 of file AI_Goto.cs.
Referenced by AI_Goto(), and TryGoTo().
interaction
bool AI_Goto.interaction
Definition at line 16 of file AI_Goto.cs.
Referenced by AI_Goto(), and IsDestinationReached().
repath
bool AI_Goto.repath
Definition at line 18 of file AI_Goto.cs.
Referenced by Run(), and TryGoTo().
waitCount
int AI_Goto.waitCount
Definition at line 12 of file AI_Goto.cs.
Referenced by TryGoTo().
Property Documentation
CancelWhenDamaged
override bool AI_Goto.CancelWhenDamaged get
Definition at line 22 of file AI_Goto.cs.
CancelWhenMoved
override bool AI_Goto.CancelWhenMoved get
Definition at line 24 of file AI_Goto.cs.
InformCancel
override bool AI_Goto.InformCancel get
Definition at line 26 of file AI_Goto.cs.
PushChara
override bool AI_Goto.PushChara get
Definition at line 28 of file AI_Goto.cs.
UseTurbo
override bool AI_Goto.UseTurbo get
Definition at line 20 of file AI_Goto.cs.
The documentation for this class was generated from the following file:
Elin/AI_Goto.cs