Elin Decompiled Documentation: SourceResearch Class Reference
SourceResearch Class Reference
Classes
class Row
Public Member Functions
override Row CreateRow ()
override Row CreateRowByMapping (IReadOnlyDictionary< string, int > mapping)
override void SetRow (Row r)
override IReadOnlyDictionary< string, int > GetRowMapping ()
override IReadOnlyDictionary< string, string > GetTypeMapping ()
Public Member Functions inherited from SourceDataString< SourceResearch.Row >
override T GetRow (string id)
Static Public Attributes
static readonly IReadOnlyDictionary< string, int > RowMapping
static readonly IReadOnlyDictionary< string, string > TypeMapping
Detailed Description
Definition at line 4 of file SourceResearch.cs.
Member Function Documentation
CreateRow()
override Row SourceResearch.CreateRow () inline
Definition at line 80 of file SourceResearch.cs.
    {
        return new Row
        {
            id = SourceData.GetString(0),
            name_JP = SourceData.GetString(1),
            name = SourceData.GetString(2),
            resource = SourceData.GetStringArray(3),
            money = SourceData.GetInt(4),
            tech = SourceData.GetInt(5),
            req = SourceData.GetString(6),
            type = SourceData.GetString(7),
            expMod = SourceData.GetInt(8),
            maxLv = SourceData.GetInt(9),
            reward = SourceData.GetString(10),
            detail_JP = SourceData.GetString(11),
            detail = SourceData.GetString(12)
        };
    }
References SourceData< T, T2 >.GetInt(), SourceData< T, T2 >.GetString(), SourceData< T, T2 >.GetStringArray(), money, and resource.
CreateRowByMapping()
override Row SourceResearch.CreateRowByMapping (IReadOnlyDictionary< string, int > mapping) inline
Definition at line 100 of file SourceResearch.cs.
    {
        return new Row
        {
            id = SourceData.GetString(mapping["id"]),
            name_JP = SourceData.GetString(mapping["name_JP"]),
            name = SourceData.GetString(mapping["name"]),
            resource = SourceData.GetStringArray(mapping["resource"]),
            money = SourceData.GetInt(mapping["money"]),
            tech = SourceData.GetInt(mapping["tech"]),
            req = SourceData.GetString(mapping["req"]),
            type = SourceData.GetString(mapping["type"]),
            expMod = SourceData.GetInt(mapping["expMod"]),
            maxLv = SourceData.GetInt(mapping["maxLv"]),
            reward = SourceData.GetString(mapping["reward"]),
            detail_JP = SourceData.GetString(mapping["detail_JP"]),
            detail = SourceData.GetString(mapping["detail"])
        };
    }
References SourceData< T, T2 >.GetInt(), SourceData< T, T2 >.GetString(), SourceData< T, T2 >.GetStringArray(), money, and resource.
GetRowMapping()
override IReadOnlyDictionary< string, int > SourceResearch.GetRowMapping () inline
Definition at line 125 of file SourceResearch.cs.
    {
        return RowMapping;
    }
References RowMapping.
GetTypeMapping()
override IReadOnlyDictionary< string, string > SourceResearch.GetTypeMapping () inline
Definition at line 130 of file SourceResearch.cs.
    {
        return TypeMapping;
    }
References TypeMapping.
SetRow()
override void SourceResearch.SetRow (Row r) inline
Definition at line 120 of file SourceResearch.cs.
    {
        map[r.id] = r;
    }
References SourceResearch.Row.id.
Member Data Documentation
RowMapping
readonly IReadOnlyDictionary<string, int> SourceResearch.RowMapping static
Initial value:
= new Dictionary<string, int>
    {
        ["id"] = 0,
        ["name_JP"] = 1,
        ["name"] = 2,
        ["resource"] = 3,
        ["money"] = 4,
        ["tech"] = 5,
        ["req"] = 6,
        ["type"] = 7,
        ["expMod"] = 8,
        ["maxLv"] = 9,
        ["reward"] = 10,
        ["detail_JP"] = 11,
        ["detail"] = 12
    }
Definition at line 46 of file SourceResearch.cs.
Referenced by GetRowMapping().
TypeMapping
readonly IReadOnlyDictionary<string, string> SourceResearch.TypeMapping static
Initial value:
= new Dictionary<string, string>
    {
        ["id"] = "string",
        ["name_JP"] = "string",
        ["name"] = "string",
        ["resource"] = "string[]",
        ["money"] = "int",
        ["tech"] = "int",
        ["req"] = "string",
        ["type"] = "string",
        ["expMod"] = "int",
        ["maxLv"] = "int",
        ["reward"] = "string",
        ["detail_JP"] = "string",
        ["detail"] = "string"
    }
Definition at line 63 of file SourceResearch.cs.
Referenced by GetTypeMapping().
The documentation for this class was generated from the following file:
Elin/SourceResearch.cs