Elin Decompiled Documentation: RefractionProfile Class Reference
RefractionProfile Class Reference
Public Member Functions
void Apply ()
Static Public Member Functions
static RefractionProfile Get (string id)
static void Apply (string id)
Static Public Member Functions inherited from EScriptable
static int rnd (int a)
Public Attributes
Texture2D tex
float transparency
Vector4 grabAnime
Vector4 grabPos
Detailed Description
Definition at line 3 of file RefractionProfile.cs.
Member Function Documentation
Apply() [1/2]
void RefractionProfile.Apply () inline
Definition at line 23 of file RefractionProfile.cs.
    {
        BaseTileMap tileMap = EClass.scene.screenElin.tileMap;
        Set(tileMap.passFloorWater.mat);
        Set(tileMap.passLiquid.mat);
        Set(tileMap.passAutoTileWater.mat);
        void Set(Material mat)
        {
            mat.SetVector("_GrabAnime", grabAnime);
            mat.SetVector("_GrabPos", grabPos);
            mat.SetTexture("_BumpTex", tex);
        }
    }
References grabAnime, grabPos, MeshPass.mat, Material, BaseTileMap.passAutoTileWater, BaseTileMap.passFloorWater, BaseTileMap.passLiquid, EClass.scene, Scene.screenElin, tex, and BaseGameScreen.tileMap.
Apply() [2/2]
static void RefractionProfile.Apply (string id) inline static
Definition at line 18 of file RefractionProfile.cs.
    {
        Get(id).Apply();
    }
References Apply(), and Get().
Referenced by Apply(), and Scene.ApplyZoneConfig().
Get()
static RefractionProfile RefractionProfile.Get (string id) inline static
Definition at line 13 of file RefractionProfile.cs.
    {
        return Resources.Load<RefractionProfile>("Scene/Profile/Refraction/" + id);
    }
Referenced by Apply().
Member Data Documentation
grabAnime
Vector4 RefractionProfile.grabAnime
Definition at line 9 of file RefractionProfile.cs.
Referenced by Apply().
grabPos
Vector4 RefractionProfile.grabPos
Definition at line 11 of file RefractionProfile.cs.
Referenced by Apply().
tex
Texture2D RefractionProfile.tex
Definition at line 5 of file RefractionProfile.cs.
Referenced by Apply().
transparency
float RefractionProfile.transparency
Definition at line 7 of file RefractionProfile.cs.
The documentation for this class was generated from the following file:
Elin/RefractionProfile.cs