Elin Decompiled Documentation: EloMap Class Reference
EloMap Class Reference
Classes
class Cell
class TileInfo
Public Member Functions
void Init (EloMapActor _actor)
void SetZone (int gx, int gy, Zone z, bool updateMesh=false)
EloMap.Cell GetCell (Point pos)
EloMap.Cell GetCell (int gx, int gy)
EloMap.TileInfo GetTileInfo (int gx, int gy)
List< SourceGlobalTile.Row > GetSources (int gx, int gy)
bool CanBuildSite (int gx, int gy, int radius=0, ElomapSiteType type=ElomapSiteType.Nefia)
bool IsSnow (int gx, int gy)
Zone GetZone (Point p)
Zone GetZone (int gx, int gy)
int GetRoadDist (int gx, int gy)
void AddLight (int gx, int gy, string id="elolight")
void RemoveLight (int gx, int gy)
Public Attributes
int[,] _ints
EloMap.Cell[,] cells
TilemapGroup group
STETilemap fogmap
STETilemap seaMap
STETilemap objScatterMap
STETilemap objmap
STETilemap extramap
STETilemap cloudmap
int w
int h
int minX
int minY
bool initialized
EloMapActor actor
Package Functions
void OnSerializing (StreamingContext context)
void OnDeserialized (StreamingContext context)
Properties
Region region [get]
string idMap [get]
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Additional Inherited Members
Static Public Member Functions inherited from EClass
static int rnd (int a)
static int curve (int a, int start, int step, int rate=75)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Static Public Attributes inherited from EClass
static Core core
Detailed Description
Definition at line 8 of file EloMap.cs.
Member Function Documentation
AddLight()
void EloMap.AddLight (int gx, int gy, string id = "elolight") inline
Definition at line 385 of file EloMap.cs.
    {
        SpriteRenderer spriteRenderer = Util.Instantiate<SpriteRenderer>(id, this.actor.transLight);
        EloMapLight item = new EloMapLight
        {
            sr = spriteRenderer,
            gx = gx,
            gy = gy
        };
        this.actor.lights.Add(item);
        spriteRenderer.transform.position = TilemapUtils.GetGridWorldPos(this.fogmap, gx, gy);
    }
References actor, fogmap, EloMapActor.lights, and EloMapActor.transLight.
Referenced by Init(), and SetZone().
CanBuildSite()
bool EloMap.CanBuildSite (int gx, int gy, int radius = 0, ElomapSiteType type = ElomapSiteType::Nefia) inline
Definition at line 275 of file EloMap.cs.
    {
        if (radius != 0)
        {
            for (int i = gy - radius; i < gy + radius + 1; i++)
            {
                for (int j = gx - radius; j < gx + radius + 1; j++)
                {
                    if (!this.CanBuildSite(j, i, 0, ElomapSiteType.Nefia))
                    {
                        return false;
                    }
                }
            }
            return true;
        }
        EloMap.Cell cell = this.GetCell(gx, gy);
        if (cell == null || cell.zone != null || this.cloudmap.GetTileData(gx, gy) != 4294967295U)
        {
            return false;
        }
        SourceGlobalTile.Row row = this.GetSources(gx, gy).LastItem<SourceGlobalTile.Row>();
        if (type == ElomapSiteType.Mob)
        {
            if (row.id == 4 && EClass.rnd(5) == 0)
            {
                return false;
            }
            if (row.id == 7 && EClass.rnd(2) == 0)
            {
                return false;
            }
        }
        else
        {
            if (row == null || !row.tag.Contains("site"))
            {
                return false;
            }
            if (row.id == 7 && EClass.rnd(5) == 0)
            {
                return false;
            }
        }
        return true;
    }
References CanBuildSite(), GetCell(), GetSources(), SourceGlobalTile.Row.id, EClass.rnd(), SourceGlobalTile.Row.tag, and EloMap.Cell.zone.
Referenced by CanBuildSite(), TraitScrollMapTreasure.GetDest(), and Region.GetRandomPoint().
GetCell() [1/2]
EloMap.Cell EloMap.GetCell (int gx, int gy) inline
Definition at line 182 of file EloMap.cs.
    {
        if (gx < this.minX || gy < this.minY || gx >= this.minX + this.w || gy >= this.minY + this.h)
        {
            return null;
        }
        return this.cells[gx - this.minX, gy - this.minY];
    }
References cells, h, minX, minY, and w.
GetCell() [2/2]
EloMap.Cell EloMap.GetCell (Point pos) inline
Definition at line 177 of file EloMap.cs.
    {
        return this.GetCell(pos.x + this.minX, pos.z + this.minY);
    }
References GetCell(), Point.x, and Point.z.
Referenced by Chara._Move(), CanBuildSite(), GetCell(), Init(), IsSnow(), TraitDeedRelocate.OnRead(), EloMapTileSelector.OnUpdateInput(), TileSelectorElona.OnUpdateInput(), SetZone(), UIZoneInfo.SetZone(), and Chara.Tick().
GetRoadDist()
int EloMap.GetRoadDist (int gx, int gy) inline
Definition at line 354 of file EloMap.cs.
    {
        if (!this.initialized)
        {
            EClass.scene.elomapActor.Initialize(EClass.world.region.elomap);
        }
        for (int i = 0; i < 100; i++)
        {
            for (int j = gy - i; j < gy + i + 1; j++)
            {
                for (int k = gx - i; k < gx + i + 1; k++)
                {
                    if (j == gy - i || j == gy + i || k == gx - i || k == gx + i)
                    {
                        uint tileData = this.objScatterMap.GetTileData(k, j);
                        if (((tileData != 4294967295U) ? ((tileData & 268369920U) >> 16) : 0U) == 3U)
{
                            return i;
                        }
                        tileData = this.seaMap.GetTileData(k, j);
                        if (((tileData != 4294967295U) ? ((tileData & 268369920U) >> 16) : 0U) == 3U)
{
                            return i;
                        }
                    }
                }
            }
        }
        return 100;
    }
References Region.elomap, Scene.elomapActor, EloMapActor.Initialize(), initialized, objScatterMap, World.region, EClass.scene, seaMap, and EClass.world.
Referenced by Player.EnterLocalZone(), and RegionPoint.SetRegionPoint().
GetSources()
List< SourceGlobalTile.Row > EloMap.GetSources (int gx, int gy) inline
Definition at line 258 of file EloMap.cs.
    {
        List<SourceGlobalTile.Row> list = new List<SourceGlobalTile.Row>();
        foreach (STETilemap stetilemap in this.group.Tilemaps)
        {
            if (!(stetilemap == this.fogmap))
            {
                int tileIdFromTileData = Tileset.GetTileIdFromTileData(stetilemap.GetTileData(gx, gy));
                if (EClass.sources.globalTiles.tileAlias.ContainsKey(tileIdFromTileData))
                {
                    list.Add(EClass.sources.globalTiles.tileAlias.TryGetValue(tileIdFromTileData, null));
                }
            }
        }
        return list;
    }
References fogmap, SourceManager.globalTiles, group, EClass.sources, and SourceGlobalTile.tileAlias.
Referenced by CanBuildSite(), and IsSnow().
GetTileInfo()
EloMap.TileInfo EloMap.GetTileInfo (int gx, int gy) inline
Definition at line 191 of file EloMap.cs.
    {
        EloMap.TileInfo t = new EloMap.TileInfo();
        bool skip = false;
        this.group.Tilemaps.ForeachReverse(delegate(STETilemap m)
        {
            if (m == this.fogmap | skip)
            {
                return;
            }
            int tileIdFromTileData = Tileset.GetTileIdFromTileData(m.GetTileData(gx, gy));
            TileData tileData = new TileData(m.GetTileData(gx, gy));
            int tileId = tileData.tileId;
            if (tileId >= 22 && tileId <= 25)
            {
                bool flipHorizontal = tileData.flipHorizontal;
                bool flipVertical = tileData.flipVertical;
                bool rot = tileData.rot90;
                int num = (flipHorizontal ? 1 : 0) + (flipVertical ? 1 : 0) * 2 + (rot ? 1 : 0) * 4;
                t.isRoad = true;
                t.roadLeft = (tileId == 23 || (tileId == 24 && (num == 4 || num == 0)) || (tileId == 25 && num != 6));
                t.roadRight = (tileId == 23 || (tileId == 24 && (num == 6 || num == 1)) || (tileId == 25 && num != 4));
                t.roadUp = (tileId == 22 || (tileId == 24 && (num == 4 || num == 6)) || (tileId == 25 && num != 0));
                t.roadDown = (tileId == 22 || (tileId == 24 && (num == 0 || num == 1)) || (tileId == 25 && num != 2));
            }
            SourceGlobalTile.Row row = EClass.sources.globalTiles.tileAlias.TryGetValue(tileIdFromTileData, null);
            if (row == null)
            {
                return;
            }
            t.source = row;
            t.sprite = TilemapUtils.GetOrCreateTileSprite(this.actor.tileset, row.tiles[0], 0f);
            string alias = row.alias;
            if (!(alias == "bridge"))
            {
                if (!(alias == "wall") && !(alias == "rock"))
                {
                    if (!(alias == "sea"))
                    {
                        if (alias == "beach")
{
                            t.shore = true;
                        }
                    }
                    else
                    {
                        t.sea = true;
                    }
                }
                else
                {
                    t.rock = true;
                }
            }
            if (!row.zoneProfile.IsEmpty())
            {
                skip = true;
                return;
            }
            if (row.attribs[0] == 0)
            {
                t.blocked = true;
            }
        });
        return t;
    }
References actor, SourceGlobalTile.Row.alias, SourceGlobalTile.Row.attribs, fogmap, SourceManager.globalTiles, group, EClass.sources, SourceGlobalTile.tileAlias, SourceGlobalTile.Row.tiles, EloMapActor.tileset, and SourceGlobalTile.Row.zoneProfile.
Referenced by Region.CanCreateZone(), Spatial.Dist(), Zone.GetProfile(), TileSelectorElona.OnRenderTile(), TileSelectorElona.OnUpdateInput(), Weather.RefreshWeather(), RegionPoint.SetRegionPoint(), and Chara.Tick().
GetZone() [1/2]
Zone EloMap.GetZone (int gx, int gy) inline
Definition at line 337 of file EloMap.cs.
    {
        Zone zone = null;
        foreach (Spatial spatial in this.region.children)
        {
            if (spatial.x == gx && spatial.y == gy)
            {
                Zone zone2 = spatial as Zone;
                if (((zone2 != null) ? zone2.instance : null) == null && (zone == null || zone is Zone_Field))
                {
                    zone = (spatial as Zone);
                }
            }
        }
        return zone;
    }
References Spatial.children, Zone.instance, region, Spatial.x, and Spatial.y.
GetZone() [2/2]
Zone EloMap.GetZone (Point p) inline
Definition at line 332 of file EloMap.cs.
    {
        return this.GetZone(p.x + this.minX, p.z + this.minY);
    }
References GetZone(), Point.x, and Point.z.
Referenced by GetZone(), EloMapTileSelector.OnUpdateInput(), TileSelectorElona.OnUpdateInput(), LayerTravel.Refresh(), and PointTarget.Update().
Init()
void EloMap.Init (EloMapActor _actor) inline
Definition at line 60 of file EloMap.cs.
    {
        if (this.initialized)
        {
            return;
        }
        this.actor = _actor;
        this.initialized = true;
        this.group = this.actor.transMap.GetComponentInChildren<TilemapGroup>();
        this.seaMap = this.group.Tilemaps[0];
        this.cloudmap = this.group.Tilemaps[7];
        this.extramap = this.group.Tilemaps[6];
        this.fogmap = this.group.Tilemaps[5];
        this.objmap = this.group.Tilemaps[4];
        this.objScatterMap = this.group.Tilemaps[3];
        this.w = this.fogmap.GridWidth;
        this.h = this.fogmap.GridHeight;
        this.minX = this.fogmap.MinGridX;
        this.minY = this.fogmap.MinGridY;
        if (this.cells == null)
        {
            this.cells = new EloMap.Cell[this.w, this.h];
            for (int i = 0; i < this.h; i++)
            {
                for (int j = 0; j < this.w; j++)
                {
                    this.cells[j, i] = new EloMap.Cell();
                }
            }
        }
        foreach (Spatial spatial in this.region.children)
        {
            int x = spatial.x;
            int y = spatial.y;
            Zone zone = spatial as Zone;
            EloMap.Cell cell = this.GetCell(x, y);
            if (cell == null)
            {
                Debug.Log("cell is null:" + x.ToString() + "/" + y.ToString());
            }
            else
            {
                cell.zone = zone;
                if (!zone.IsInstance)
                {
                    cell.obj = zone.icon;
                }
            }
        }
        for (int k = 0; k < this.h; k++)
        {
            for (int l = 0; l < this.w; l++)
            {
                EloMap.Cell cell2 = this.cells[l, k];
                int num = this.minX + l;
                int num2 = this.minY + k;
                if (cell2.obj != 0)
                {
                    this.objmap.SetTile(num, num2, cell2.obj, 0, eTileFlags.None);
                }
                if (cell2.zone != null)
                {
                    if (cell2.zone.UseLight)
                    {
                        this.AddLight(num, num2, "elolight");
                    }
                    if (cell2.zone.IsClosed)
                    {
                        this.extramap.SetTile(num, num2, 333, 0, eTileFlags.None);
                    }
                }
            }
        }
        this.extramap.UpdateMeshImmediate();
        this.objmap.UpdateMeshImmediate();
    }
References actor, AddLight(), cells, Spatial.children, extramap, fogmap, GetCell(), group, h, Spatial.icon, initialized, Spatial.IsClosed, Zone.IsInstance, EloMap.Cell.obj, objmap, region, EloMapActor.transMap, Zone.UseLight, w, Spatial.x, Spatial.y, and EloMap.Cell.zone.
Referenced by EloMapActor.Initialize().
IsSnow()
bool EloMap.IsSnow (int gx, int gy) inline
Definition at line 322 of file EloMap.cs.
    {
        if (this.GetCell(gx, gy) == null)
        {
            return false;
        }
        SourceGlobalTile.Row row = this.GetSources(gx, gy).LastItem<SourceGlobalTile.Row>();
        return row != null && row.id == 7;
    }
References GetCell(), and GetSources().
Referenced by Region.CreateRandomSite().
OnDeserialized()
void EloMap.OnDeserialized (StreamingContext context) inline package
Definition at line 43 of file EloMap.cs.
    {
        if (this._ints != null && this._ints.GetLength(0) > 0)
        {
            this.w = this._ints.GetLength(0);
            this.h = this._ints.GetLength(1);
            this.cells = new EloMap.Cell[this.w, this.h];
            for (int i = 0; i < this.h; i++)
            {
                for (int j = 0; j < this.w; j++)
                {
                    this.cells[j, i] = new EloMap.Cell(this._ints[j, i]);
                }
            }
        }
    }
References _ints, cells, h, and w.
OnSerializing()
void EloMap.OnSerializing (StreamingContext context) inline package
Definition at line 27 of file EloMap.cs.
    {
        if (this.cells != null)
        {
            this._ints = new int[this.w, this.h];
            for (int i = 0; i < this.h; i++)
            {
                for (int j = 0; j < this.w; j++)
                {
                    this._ints[j, i] = this.cells[j, i].GetInt();
                }
            }
        }
    }
References _ints, cells, h, and w.
RemoveLight()
void EloMap.RemoveLight (int gx, int gy) inline
Definition at line 398 of file EloMap.cs.
    {
        foreach (EloMapLight eloMapLight in this.actor.lights)
        {
            if (eloMapLight.gx == gx && eloMapLight.gy == gy)
            {
                UnityEngine.Object.DestroyImmediate(eloMapLight.sr.gameObject);
                this.actor.lights.Remove(eloMapLight);
                break;
            }
        }
    }
References actor, EloMapLight.gx, EloMapLight.gy, EloMapActor.lights, and EloMapLight.sr.
Referenced by SetZone().
SetZone()
void EloMap.SetZone (int gx, int gy, Zone z, bool updateMesh = false) inline
Definition at line 137 of file EloMap.cs.
    {
        EloMap.Cell cell = this.GetCell(gx, gy);
        if (cell == null)
        {
            Debug.Log("cell is null:" + gx.ToString() + "/" + gy.ToString());
            return;
        }
        if (z != null && cell.obj == z.icon)
        {
            return;
        }
        cell.obj = ((z != null) ? z.icon : 0);
        if (z != null && z.source.tag.Contains("iconFlag"))
        {
            cell.obj = 306;
        }
        if (cell.zone != null && cell.zone.UseLight)
        {
            this.RemoveLight(gx, gy);
        }
        cell.zone = z;
        if (cell.obj == 0)
        {
            this.objmap.Erase(gx, gy);
        }
        else
        {
            this.objmap.SetTile(gx, gy, cell.obj, 0, eTileFlags.None);
        }
        if (z != null && z.UseLight)
        {
            this.AddLight(gx, gy, "elolight");
        }
        if (updateMesh)
        {
            this.objmap.UpdateMeshImmediate();
        }
    }
References AddLight(), GetCell(), Spatial.icon, EloMap.Cell.obj, objmap, RemoveLight(), Spatial.source, Zone.UseLight, and EloMap.Cell.zone.
Referenced by Zone.ClaimZone(), Region.CreateRandomSite(), Zone.Destroy(), TraitDeedRelocate.OnRead(), and TraitMapBoard.TrySetAct().
Member Data Documentation
_ints
int [,] EloMap._ints
Definition at line 412 of file EloMap.cs.
Referenced by OnDeserialized(), and OnSerializing().
actor
EloMapActor EloMap.actor
Definition at line 440 of file EloMap.cs.
Referenced by AddLight(), RankedZone.GetSprite(), GetTileInfo(), Init(), LayerTravel.Refresh(), RemoveLight(), and TraitMapBoard.TrySetAct().
cells
EloMap.Cell [,] EloMap.cells
Definition at line 414 of file EloMap.cs.
Referenced by GetCell(), Init(), OnDeserialized(), MapGenRegion.OnGenerateTerrain(), and OnSerializing().
cloudmap
STETilemap EloMap.cloudmap
Definition at line 428 of file EloMap.cs.
Referenced by MapGenRegion.OnGenerateTerrain().
extramap
STETilemap EloMap.extramap
Definition at line 426 of file EloMap.cs.
Referenced by Init().
fogmap
STETilemap EloMap.fogmap
Definition at line 418 of file EloMap.cs.
Referenced by AddLight(), TileMapElona.Draw(), GetSources(), GetTileInfo(), Init(), EloMapActor.Initialize(), EloMapActor.OnActivate(), MapGenRegion.OnGenerateTerrain(), and GameScreenElona.RefreshPosition().
group
TilemapGroup EloMap.group
Definition at line 416 of file EloMap.cs.
Referenced by GetSources(), GetTileInfo(), Init(), and MapGenRegion.OnGenerateTerrain().
h
int EloMap.h
Definition at line 432 of file EloMap.cs.
Referenced by GetCell(), Init(), OnDeserialized(), MapGenRegion.OnGenerateTerrain(), and OnSerializing().
initialized
bool EloMap.initialized
Definition at line 438 of file EloMap.cs.
Referenced by GetRoadDist(), Init(), and EloMapActor.Initialize().
minX
int EloMap.minX
Definition at line 434 of file EloMap.cs.
Referenced by Region.CreateRandomSite(), Spatial.Dist(), TileMapElona.Draw(), Player.EnterLocalZone(), GetCell(), TraitScrollMapTreasure.GetDest(), Region.GetRandomPoint(), Region.ListTravelZones(), Point.PositionTopdownTreasure(), Weather.RefreshWeather(), RegionPoint.SetRegionPoint(), Point.ToRegionPos(), GameUpdater.Update(), and WidgetDebug.UpdateText().
minY
int EloMap.minY
Definition at line 436 of file EloMap.cs.
Referenced by Region.CreateRandomSite(), Spatial.Dist(), TileMapElona.Draw(), Player.EnterLocalZone(), GetCell(), TraitScrollMapTreasure.GetDest(), Region.GetRandomPoint(), Region.ListTravelZones(), Point.PositionTopdownTreasure(), Weather.RefreshWeather(), RegionPoint.SetRegionPoint(), Point.ToRegionPos(), GameUpdater.Update(), and WidgetDebug.UpdateText().
objmap
STETilemap EloMap.objmap
Definition at line 424 of file EloMap.cs.
Referenced by Region.CheckRandomSites(), Region.CreateRandomSite(), Init(), EloMapActor.OnActivate(), and SetZone().
objScatterMap
STETilemap EloMap.objScatterMap
Definition at line 422 of file EloMap.cs.
Referenced by GetRoadDist().
seaMap
STETilemap EloMap.seaMap
Definition at line 420 of file EloMap.cs.
Referenced by GetRoadDist().
w
int EloMap.w
Definition at line 430 of file EloMap.cs.
Referenced by GetCell(), Init(), OnDeserialized(), MapGenRegion.OnGenerateTerrain(), and OnSerializing().
Property Documentation
idMap
string EloMap.idMap get
Definition at line 18 of file EloMap.cs.
    {
        get
        {
            return "map_ntyris";
        }
    }
Referenced by EloMapActor.Initialize().
region
Region EloMap.region get
Definition at line 10 of file EloMap.cs.
    {
        get
        {
            return EClass.world.region;
        }
    }
Referenced by GetZone(), and Init().
The documentation for this class was generated from the following file:
Elin/EloMap.cs