Elin Decompiled Documentation: TileTypeWallHang Class Reference
TileTypeWallHang Class Reference
Public Member Functions
override int GetDesiredDir (Point p, int d)
unsafe override void GetMountHeight (ref Vector3 v, Point p, int d, Card target=null)
Public Member Functions inherited from TileType
virtual bool CanRotate (bool buildMode)
HitResult _HitTest (Point pos, Card target, bool canIgnore=true)
virtual int GetDesiredDir (Point p, int d)
virtual void GetMountHeight (ref Vector3 v, Point p, int d, Card target=null)
Vector3 GetRampFix (int dir)
Static Public Attributes
static bool[] DIRS = new bool[4]
Static Public Attributes inherited from TileType
static TileTypeNone None = new TileTypeNone()
static TileTypeInvisibleBlock InvisiBlock = new TileTypeInvisibleBlock()
static TileTypeBlock Block = new TileTypeBlock()
static TileTypeBlockShip BlockShip = new TileTypeBlockShip()
static TileTypeSlope Slope = new TileTypeSlope()
static TileTypeHalfBlock HalfBlock = new TileTypeHalfBlock()
static TileTypeStairs Stairs = new TileTypeStairs()
static TileTypeStairs StairsHalf = new TileTypeStairsHalf()
static TileTypeRooftop Rooftop = new TileTypeRooftop()
static TileTypeScaffold Scaffold = new TileTypeScaffold()
static TileTypeLadder Ladder = new TileTypeLadder()
static TileTypePillar Pillar = new TileTypePillar()
static TileTypeWaterfall Waterfall = new TileTypeWaterfall()
static TileTypeWall Wall = new TileTypeWall()
static TileTypeWallOpen WallOpen = new TileTypeWallOpen()
static TileTypeFence Fence = new TileTypeFence()
static TileTypeFenceClosed FenceClosed = new TileTypeFenceClosed()
static TileTypeFloor Floor = new TileTypeFloor()
static TileTypeFloorScaffold FloorScaffold = new TileTypeFloorScaffold()
static TileTypeWater FloorWater = new TileTypeWater()
static TileTypeWaterShallow FloorWaterShallow = new TileTypeWaterShallow()
static TileTypeWaterDeep FloorWaterDeep = new TileTypeWaterDeep()
static TileTypeBridge Bridge = new TileTypeBridge()
static TileTypeBridgeDeco BridgeDeco = new TileTypeBridgeDeco()
static TileTypeBridgePillar BridgePillar = new TileTypeBridgePillar()
static TileTypeSky Sky = new TileTypeSky()
static TileTypeObj Obj = new TileTypeObj()
static TileTypeObjBig ObjBig = new TileTypeObjBig()
static TileTypeObjHuge ObjHuge = new TileTypeObjHuge()
static TileTypeObjCeil ObjCeil = new TileTypeObjCeil()
static TileTypeObjFloat ObjFloat = new TileTypeObjFloat()
static TileTypeObjWater ObjWater = new TileTypeObjWater()
static TileTypeObjWaterTop ObjWaterTop = new TileTypeObjWaterTop()
static TileTypeIllumination Illumination = new TileTypeIllumination()
static TileTypeSeed Seed = new TileTypeSeed()
static TileTypeTree Tree = new TileTypeTree()
static TileTypeDoor Door = new TileTypeDoor()
static TileTypeWallHang WallHang = new TileTypeWallHang()
static TileTypeWallHangSign WallHangSign = new TileTypeWallHangSign()
static TileTypeVine Vine = new TileTypeVine()
static TileTypeWallMount WallMount = new TileTypeWallMount()
static TileTypePaint Paint = new TileTypePaint()
static TileTypeWindow Window = new TileTypeWindow()
static TileTypeRoof Roof = new TileTypeRoof()
static TileTypeRoad Road = new TileTypeRoad()
static TileTypeChasm Chasm = new TileTypeChasm()
static TileTypeBoat Boat = new TileTypeBoat()
static TileTypeLiquid Liquid = new TileTypeLiquid()
static TileTypeMarker Marker = new TileTypeMarker()
static Dictionary< string, TileType > dict = new Dictionary<string, TileType>()
Static Public Attributes inherited from EClass
static Core core
Protected Member Functions
override HitResult HitTest (Point pos)
virtual HitResult HitTest (Point pos)
Properties
override string LangPlaceType [get]
override bool CanStack [get]
override bool IsBlockMount [get]
override bool UseMountHeight [get]
override bool UseHangZFix [get]
virtual bool NoBackSide [get]
Properties inherited from TileTypeObj
override bool CanBuiltOnThing [get]
override bool CanBuiltOnWater [get]
override bool FreeStyle [get]
override bool CanStack [get]
Properties inherited from TileType
virtual string LangPlaceType [get]
virtual bool CanStack [get]
virtual bool ChangeBlockDir [get]
virtual bool IsSkipLowBlock [get]
virtual bool IsSkipFloor [get]
virtual bool IsUseBlockDir [get]
virtual bool IsFloorOrBridge [get]
virtual bool IsWall [get]
virtual bool IsFloor [get]
virtual bool IsBridge [get]
virtual bool IsWallOrFence [get]
virtual bool IsWallOrFullBlock [get]
bool IsRamp [get]
virtual TileType.RampType Ramp [get]
virtual bool IsLadder [get]
virtual bool IsBlockPass [get]
virtual bool IsOccupyCell [get]
virtual bool IsBlockSight [get]
virtual bool IsOpenSight [get]
virtual bool IsBlockLiquid [get]
virtual bool IsWater [get]
virtual bool IsDeepWater [get]
virtual bool IsBlockMount [get]
virtual bool IsFullBlock [get]
virtual bool IsFence [get]
virtual bool IsFloodBlock [get]
virtual bool IsPlayFootSound [get]
virtual bool CanSpawnOnWater [get]
virtual bool IsWaterTop [get]
virtual bool CastShadowSelf [get]
virtual bool CastShadowBack [get]
virtual bool CastAmbientShadow [get]
virtual bool CastAmbientShadowBack [get]
virtual bool CanBuiltOnArea [get]
virtual bool CanBuiltOnWater [get]
virtual bool CanBuiltOnThing [get]
virtual bool CanBuiltOnBlock [get]
virtual bool IsDoor [get]
virtual bool CanBuiltOnFloor [get]
virtual bool CanBuiltOnBridge [get]
virtual bool CanInstaComplete [get]
virtual int MinAltitude [get]
virtual int MaxAltitude [get]
virtual bool AltitudeAsDir [get]
virtual bool UseLowWallTiles [get]
virtual bool UseMountHeight [get]
virtual bool UseHangZFix [get]
virtual bool UseLowBlock [get]
virtual bool RemoveOnFloorChange [get]
virtual bool AllowObj [get]
virtual bool AllowMultiInstall [get]
virtual bool FreeStyle [get]
virtual byte slopeHeight [get]
virtual float MountHeight [get]
virtual float FloorHeight [get]
virtual float RepeatSize [get]
virtual int FloorAltitude [get]
virtual int LiquidLV [get]
virtual bool AllowLitter [get]
virtual bool AllowBlood [get]
virtual bool ShowPillar [get]
virtual bool AlwaysShowShadow [get]
virtual bool RepeatBlock [get]
virtual bool ForceRpeatBlock [get]
virtual bool CanBeHeld [get]
virtual bool EditorTile [get]
virtual bool IsFloodDoor [get]
virtual bool Invisible [get]
virtual bool IgnoreBuildRule [get]
virtual bool RenderWaterBlock [get]
virtual BaseTileSelector.SelectType SelectType [get]
virtual BaseTileSelector.BoxType BoxType [get]
virtual BaseTileSelector.HitType HitType [get]
virtual BlockRenderMode blockRenderMode [get]
bool IsMountBlock [get]
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Additional Inherited Members
Public Types inherited from TileType
enum RampType { None , Full , Half }
Static Public Member Functions inherited from TileType
static void Init ()
Static Public Member Functions inherited from EClass
static int rnd (int a)
static int curve (int a, int start, int step, int rate=75)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Detailed Description
Definition at line 4 of file TileTypeWallHang.cs.
Member Function Documentation
GetDesiredDir()
override int TileTypeWallHang.GetDesiredDir (Point p, int d) inline virtual
Reimplemented from TileType.
Definition at line 54 of file TileTypeWallHang.cs.
    {
        if (EClass.scene.actionMode != null && EClass.scene.actionMode.IsRoofEditMode(null))
        {
            return -1;
        }
        Cell cell = p.cell;
        TileTypeWallHang.DIRS[0] = (cell.Back.sourceBlock.tileType.IsMountBlock && (!cell.Back.sourceBlock.tileType.IsWallOrFence || cell.Back.blockDir != 1));
        TileTypeWallHang.DIRS[1] = (cell.Left.sourceBlock.tileType.IsMountBlock && (!cell.Left.sourceBlock.tileType.IsWallOrFence || cell.Left.blockDir != 0));
        if (this.NoBackSide)
        {
            TileTypeWallHang.DIRS[2] = false;
            TileTypeWallHang.DIRS[3] = false;
        }
        else
        {
            TileTypeWallHang.DIRS[2] = (cell.Front.sourceBlock.tileType.IsMountBlock && (!cell.Front.sourceBlock.tileType.IsWallOrFence || cell.Front.blockDir != 1));
            TileTypeWallHang.DIRS[3] = (cell.Right.sourceBlock.tileType.IsMountBlock && (!cell.Right.sourceBlock.tileType.IsWallOrFence || cell.Right.blockDir != 0));
        }
        if (d == -1 || !TileTypeWallHang.DIRS[d])
        {
            if (d == -1)
            {
                d = 0;
            }
            for (int i = 0; i < 4; i++)
            {
                if (TileTypeWallHang.DIRS[(i + d) % 4])
                {
                    return (i + d) % 4;
                }
            }
        }
        if (TileTypeWallHang.DIRS[d])
        {
            return d;
        }
        return -1;
    }
References Scene.actionMode, Point.cell, DIRS, ActionMode.IsRoofEditMode(), NoBackSide, and EClass.scene.
Referenced by HitTest().
GetMountHeight()
unsafe override void TileTypeWallHang.GetMountHeight (ref Vector3 v, Point p, int d, Card target = null) inline virtual
Reimplemented from TileType.
Definition at line 94 of file TileTypeWallHang.cs.
    {
        if (d == 0 && p.z < EClass._map.Size - 1)
        {
            Point.shared2.Set(p.x, p.z + 1);
            Vector3 vector = *Point.shared2.Position();
            v.x = vector.x;
            v.y = vector.y + Point.shared2.sourceBlock.tileType.MountHeight;
            v.z = vector.z;
            if (Point.shared2.HasWallOrFence)
            {
                v += EClass.screen.tileMap.wallHangFix[0];
            }
            v += EClass.screen.tileMap.altitudeFix * (float)target.altitude;
            return;
        }
        if (d == 1 && p.x > 0)
        {
            Point.shared2.Set(p.x - 1, p.z);
            Vector3 vector2 = *Point.shared2.Position();
            v.x = vector2.x;
            v.y = vector2.y + Point.shared2.sourceBlock.tileType.MountHeight;
            v.z = vector2.z;
            if (Point.shared2.HasWallOrFence)
            {
                v += EClass.screen.tileMap.wallHangFix[1];
            }
            v += EClass.screen.tileMap.altitudeFix * (float)target.altitude;
            return;
        }
        if (d == 2 && p.z > 0)
        {
            Point.shared2.Set(p.x, p.z - 1);
            Vector3 vector3 = *p.Position();
            v.x = vector3.x;
            v.y = vector3.y + p.sourceBlock.tileType.MountHeight;
            v.z = vector3.z;
            if (Point.shared2.HasWallOrFence)
            {
                v += EClass.screen.tileMap.wallHangFix[2];
            }
            v += EClass.screen.tileMap.altitudeFix * (float)target.altitude;
            return;
        }
        if (d == 3 && p.x < EClass._map.Size - 1)
        {
            Point.shared2.Set(p.x + 1, p.z);
            Vector3 vector4 = *p.Position();
            v.x = vector4.x;
            v.y = vector4.y + p.sourceBlock.tileType.MountHeight;
            v.z = vector4.z;
            if (Point.shared2.HasWallOrFence)
            {
                v += EClass.screen.tileMap.wallHangFix[3];
            }
            v += EClass.screen.tileMap.altitudeFix * (float)target.altitude;
            return;
        }
        v.y += p.sourceBlock.tileType.MountHeight;
    }
References EClass._map, Point.HasWallOrFence, Point.Position(), EClass.screen, Point.Set(), Point.shared2, MapBounds.Size, Point.sourceBlock, BaseGameScreen.tileMap, BaseTileMap.wallHangFix, Point.x, and Point.z.
HitTest()
override HitResult TileTypeWallHang.HitTest (Point pos) inline protected virtual
Reimplemented from TileType.
Definition at line 155 of file TileTypeWallHang.cs.
    {
        if (this.GetDesiredDir(pos, -1) == -1)
        {
            return HitResult.Invalid;
        }
        return base.HitTest(pos);
    }
References GetDesiredDir().
Member Data Documentation
DIRS
bool [] TileTypeWallHang.DIRS = new bool[4] static
Definition at line 164 of file TileTypeWallHang.cs.
Referenced by GetDesiredDir().
Property Documentation
CanStack
override bool TileTypeWallHang.CanStack get
Definition at line 14 of file TileTypeWallHang.cs.
    {
        get
        {
            return true;
        }
    }
IsBlockMount
override bool TileTypeWallHang.IsBlockMount get
Definition at line 22 of file TileTypeWallHang.cs.
    {
        get
        {
            return true;
        }
    }
LangPlaceType
override string TileTypeWallHang.LangPlaceType get
Definition at line 6 of file TileTypeWallHang.cs.
    {
        get
        {
            return "place_WallMount";
        }
    }
NoBackSide
virtual bool TileTypeWallHang.NoBackSide get
Definition at line 46 of file TileTypeWallHang.cs.
    {
        get
        {
            return false;
        }
    }
Referenced by GetDesiredDir().
UseHangZFix
override bool TileTypeWallHang.UseHangZFix get
Definition at line 38 of file TileTypeWallHang.cs.
    {
        get
        {
            return true;
        }
    }
UseMountHeight
override bool TileTypeWallHang.UseMountHeight get
Definition at line 30 of file TileTypeWallHang.cs.
    {
        get
        {
            return true;
        }
    }
The documentation for this class was generated from the following file:
Elin/TileTypeWallHang.cs