Elin Decompiled Documentation: BiomeProfile.ClusterObj Class Reference
BiomeProfile.ClusterObj Class Reference
Public Member Functions
override bool TryCreate (Point p)
virtual bool TryCreate (Point p)
Public Attributes
List< BiomeProfile.Cluster.Item > items
Public Attributes inherited from BiomeProfile.Cluster
BiomeProfile.Cluster.Type type
float density
Additional Inherited Members
Public Types inherited from BiomeProfile.Cluster
enum Type {
Scatter , ScatterExterior , ScatterInterior , ScatterNonObstacle ,
ByWall = 10
}
Detailed Description
Definition at line 756 of file BiomeProfile.cs.
Member Function Documentation
TryCreate()
override bool BiomeProfile.ClusterObj.TryCreate (Point p) inline virtual
Reimplemented from BiomeProfile.Cluster.
Definition at line 758 of file BiomeProfile.cs.
        {
            BiomeProfile.Cluster.Item item = this.items.RandomItem<BiomeProfile.Cluster.Item>();
            if (Rand.Range(0f, 1f) > item.chance)
            {
                return false;
            }
            Cell cell = p.cell;
            if (cell.HasBlock)
            {
                if (!item.IsSpawnOnBlock)
                {
                    return false;
                }
            }
            else if (item.IsSpawnOnBlock)
            {
                return false;
            }
            p.SetObj(item.idObj, 1, 0);
            cell.objDir = EScriptable.rnd(8);
            if (cell.sourceObj.HasGrowth && cell.sourceObj.id != 103)
            {
                cell.growth.SetRandomStage();
            }
            return true;
        }
References Point.cell, BiomeProfile.Cluster.BaseItem.chance, Cell.growth, Cell.HasBlock, BiomeProfile.Cluster.Item.idObj, BiomeProfile.Cluster.Item.IsSpawnOnBlock, BiomeProfile.ClusterObj.items, EScriptable.rnd(), Point.SetObj(), GrowSystem.SetRandomStage(), and Cell.sourceObj.
Member Data Documentation
items
List<BiomeProfile.Cluster.Item> BiomeProfile.ClusterObj.items
Definition at line 786 of file BiomeProfile.cs.
Referenced by BiomeProfile.ClusterObj.TryCreate().
The documentation for this class was generated from the following file:
Elin/BiomeProfile.cs