Elin Decompiled Documentation: Player.Flags Class Reference
Player.Flags Class Reference
Public Member Functions
void OnCreateGame ()
void OnEnableDebug ()
void OnBuild (Recipe r)
bool IsStoryPlayed (int flag)
int GetStoryRowID (string idBook, string idStep)
Dictionary< string, string > GetStoryRow (string idBook, int id)
ExcelData GetStoryExcelData (string idBook)
bool PlayStory (string idBook, int id, bool fromBook=false)
bool PlayStory (int id, bool fromBook=false)
void AddStory (int id)
void OnEnterZone ()
void OnLeaveZone ()
Public Attributes
int[] ints = new int[50]
List< int > playedStories = new List<int>()
List< int > availableStories = new List<int>()
HashSet< int > pleaseDontTouch = new HashSet<int>()
List< string > reservedTutorial = new List<string>()
BitArray32 bits
Dictionary< string, ExcelData > storyExcel = new Dictionary<string, ExcelData>()
Static Public Attributes
const int MonoDeparture = 100
Static Public Attributes inherited from EClass
static Core core
Properties
bool gotClickReward [get, set]
bool welcome [get, set]
bool fiamaStoryBookGiven [get, set]
bool fiamaFirstDream [get, set]
bool helpHighlightDisabled [get, set]
bool pickedMelilithTreasure [get, set]
bool isShoesOff [get, set]
bool backpackHighlightDisabled [get, set]
bool abilityHighlightDisabled [get, set]
bool elinGift [get, set]
bool gotMelilithCurse [get, set]
bool canComupWithFoodRecipe [get, set]
bool KilledBossInVoid [get, set]
bool statueShipped [get, set]
bool little_saved [get, set]
bool little_killed [get, set]
bool gotEtherDisease [get, set]
bool loytelEscaped [get, set]
bool toggleHotbarHighlightDisabled [get, set]
bool debugEnabled [get, set]
bool magicChestSent [get, set]
bool toggleHotbarHighlightActivated [get, set]
bool gotJurePillow [get, set]
bool gotLoytelMart [get, set]
bool killedDuponne [get, set]
int santa [get, set]
int start [get, set]
int build [get, set]
int main [get, set]
int storyFiama [get, set]
int lutz [get, set]
int daysAfterQuestExploration [get, set]
int landDeedBought [get, set]
int loytelMartLv [get, set]
int reward_gould [get, set]
int reward_killkill [get, set]
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Private Member Functions
void _OnSerializing (StreamingContext context)
void _OnDeserialized (StreamingContext context)
Additional Inherited Members
Static Public Member Functions inherited from EClass
static int rndSeed (int a, int seed)
static int rnd (long a)
static int rnd (int a)
static int curve (int _a, int start, int step, int rate=75)
static int sqrt (int a)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Detailed Description
Definition at line 251 of file Player.cs.
Member Function Documentation
_OnDeserialized()
void Player.Flags._OnDeserialized (StreamingContext context) inline private
Definition at line 713 of file Player.cs.
        {
            bits.Bits = (uint)ints[0];
        }
References Player.Flags.ints.
_OnSerializing()
void Player.Flags._OnSerializing (StreamingContext context) inline private
Definition at line 707 of file Player.cs.
        {
            ints[0] = (int)bits.Bits;
        }
References Player.Flags.bits, BitArray32.Bits, and Player.Flags.ints.
AddStory()
void Player.Flags.AddStory (int id) inline
Definition at line 798 of file Player.cs.
        {
            if (!playedStories.Contains(id) && !availableStories.Contains(id))
            {
                availableStories.Add(id);
                Msg.Say("story_added");
                SE.WriteJournal();
            }
        }
References Player.Flags.availableStories, Player.Flags.playedStories, and Msg.Say().
Referenced by Player.Flags.OnEnterZone().
GetStoryExcelData()
ExcelData Player.Flags.GetStoryExcelData (string idBook) inline
Definition at line 763 of file Player.cs.
        {
            ExcelData excelData = storyExcel.TryGetValue(idBook);
            if (excelData == null)
            {
                excelData = new ExcelData();
                excelData.path = CorePath.DramaData + idBook + ".xlsx";
                excelData.BuildList("index");
                storyExcel.Add(idBook, excelData);
            }
            return excelData;
        }
References ExcelData.BuildList(), and Player.Flags.storyExcel.
Referenced by Player.Flags.GetStoryRow(), and Player.Flags.GetStoryRowID().
GetStoryRow()
Dictionary< string, string > Player.Flags.GetStoryRow (string idBook, int id) inline
Definition at line 751 of file Player.cs.
        {
            foreach (Dictionary<string, string> item in GetStoryExcelData(idBook).sheets["index"].list)
            {
                if (item["id"].ToInt() == id)
                {
                    return item;
                }
            }
            return null;
        }
References Player.Flags.GetStoryExcelData(), and item.
Referenced by Player.Flags.PlayStory().
GetStoryRowID()
int Player.Flags.GetStoryRowID (string idBook, string idStep) inline
Definition at line 739 of file Player.cs.
        {
            foreach (Dictionary<string, string> item in GetStoryExcelData(idBook).sheets["index"].list)
            {
                if (item["step"] == idStep)
                {
                    return item["id"].ToInt();
                }
            }
            return 0;
        }
References Player.Flags.GetStoryExcelData(), and item.
Referenced by Tutorial.Play(), Tutorial.Remove(), and Tutorial.Reserve().
IsStoryPlayed()
bool Player.Flags.IsStoryPlayed (int flag) inline
Definition at line 734 of file Player.cs.
        {
            return playedStories.Contains(flag);
        }
References Player.Flags.playedStories.
Referenced by TraitStoryBook.OnRead().
OnBuild()
void Player.Flags.OnBuild (Recipe r) inline
Definition at line 726 of file Player.cs.
        {
            if (build == 0 && r.id == "workbench")
            {
                build = 1;
            }
        }
References Player.Flags.build, and Recipe.id.
Referenced by TaskBuild.OnProgressComplete().
OnCreateGame()
void Player.Flags.OnCreateGame () inline
Definition at line 718 of file Player.cs.
        {
        }
Referenced by Player.OnCreateGame().
OnEnableDebug()
void Player.Flags.OnEnableDebug () inline
Definition at line 722 of file Player.cs.
        {
        }
Referenced by CoreDebug.EnableDebugResource(), and CoreDebug.QuickStart().
OnEnterZone()
void Player.Flags.OnEnterZone () inline
Definition at line 808 of file Player.cs.
        {
            if (EClass._zone.id == "nymelle")
            {
                if (EClass._zone.lv == -1)
                {
                    AddStory(10);
                }
                if (EClass._zone.lv == -2)
                {
                    AddStory(20);
                }
                if (EClass._zone.lv == -3)
                {
                    AddStory(30);
                }
            }
            if (QuestMain.Phase == 700 && EClass._zone.id == "lothria")
            {
                PlayStory(50);
            }
            if ((EClass._zone.IsPCFaction || EClass._zone.id == EClass.game.Prologue.idStartZone) && availableStories.Count > 0)
            {
                PlayStory(availableStories[0]);
                availableStories.RemoveAt(0);
            }
            if (!LayerDrama.Instance && !EClass.game.isLoading && EClass._zone.IsPCFaction)
            {
                if (EClass.game.quests.GetPhase<QuestIntoDarkness>() == 0 && EClass.game.quests.GetPhase<QuestNegotiationDarkness>() == 5)
                {
                    EClass.game.quests.Get<QuestNegotiationDarkness>().Complete();
                    EClass.game.quests.Get<QuestIntoDarkness>().UpdateOnTalk();
                }
                else if (EClass.game.quests.GetPhase<QuestIntoDarkness>() == 1)
                {
                    EClass.game.quests.Get<QuestIntoDarkness>().UpdateOnTalk();
                }
                else if (EClass.game.quests.GetPhase<QuestIntoDarkness>() == 2)
                {
                    EClass.game.quests.Get<QuestIntoDarkness>().UpdateOnTalk();
                }
                else if (EClass.game.quests.GetPhase<QuestIntoDarkness>() == 3)
                {
                    EClass.game.quests.Get<QuestIntoDarkness>().UpdateOnTalk();
                }
            }
        }
References EClass._zone, Player.Flags.AddStory(), Player.Flags.availableStories, EClass.game, QuestManager.Get(), Spatial.id, Prologue.idStartZone, LayerDrama.Instance, Game.isLoading, Zone.IsPCFaction, Spatial.lv, QuestMain.Phase, Player.Flags.PlayStory(), Game.Prologue, and Game.quests.
Referenced by Scene.Init().
OnLeaveZone()
void Player.Flags.OnLeaveZone () inline
Definition at line 856 of file Player.cs.
        {
            if (!EClass.player.simulatingZone && QuestMain.Phase == 700)
            {
                PlayStory(40);
            }
        }
References QuestMain.Phase, EClass.player, Player.Flags.PlayStory(), and Player.simulatingZone.
Referenced by Scene.OnUpdate().
PlayStory() [1/2]
bool Player.Flags.PlayStory (int id, bool fromBook = false) inline
Definition at line 793 of file Player.cs.
        {
            return PlayStory("_main", id, fromBook);
        }
References Player.Flags.PlayStory().
PlayStory() [2/2]
bool Player.Flags.PlayStory (string idBook, int id, bool fromBook = false) inline
Definition at line 776 of file Player.cs.
        {
            if (!fromBook && playedStories.Contains(id))
            {
                return false;
            }
            Dictionary<string, string> storyRow = GetStoryRow(idBook, id);
            SoundManager.ForceBGM();
            LayerDrama.fromBook = fromBook;
            LayerDrama.Activate(idBook, storyRow["sheet"], storyRow["step"]);
            if (!fromBook && !playedStories.Contains(id))
            {
                playedStories.Add(id);
            }
            return true;
        }
References LayerDrama.Activate(), Player.Flags.GetStoryRow(), and Player.Flags.playedStories.
Referenced by Player.Flags.OnEnterZone(), Player.Flags.OnLeaveZone(), TraitStoryBook.OnRead(), Tutorial.Play(), and Player.Flags.PlayStory().
Member Data Documentation
availableStories
List<int> Player.Flags.availableStories = new List<int>()
Definition at line 262 of file Player.cs.
Referenced by Player.Flags.AddStory(), and Player.Flags.OnEnterZone().
bits
BitArray32 Player.Flags.bits
Definition at line 270 of file Player.cs.
Referenced by Player.Flags._OnSerializing().
ints
int [] Player.Flags.ints = new int[50]
Definition at line 256 of file Player.cs.
Referenced by Player.Flags._OnDeserialized(), and Player.Flags._OnSerializing().
MonoDeparture
const int Player.Flags.MonoDeparture = 100 static
Definition at line 253 of file Player.cs.
playedStories
List<int> Player.Flags.playedStories = new List<int>()
Definition at line 259 of file Player.cs.
Referenced by Player.Flags.AddStory(), Player.Flags.IsStoryPlayed(), Tutorial.Play(), Player.Flags.PlayStory(), Tutorial.Remove(), and Tutorial.Reserve().
pleaseDontTouch
HashSet<int> Player.Flags.pleaseDontTouch = new HashSet<int>()
Definition at line 265 of file Player.cs.
reservedTutorial
List<string> Player.Flags.reservedTutorial = new List<string>()
Definition at line 268 of file Player.cs.
Referenced by Tutorial.Reserve(), and Tutorial.TryPlayReserve().
storyExcel
Dictionary<string, ExcelData> Player.Flags.storyExcel = new Dictionary<string, ExcelData>()
Definition at line 272 of file Player.cs.
Referenced by Player.Flags.GetStoryExcelData().
Property Documentation
abilityHighlightDisabled
bool Player.Flags.abilityHighlightDisabled get set
Definition at line 370 of file Player.cs.
        {
            get
            {
                return bits[9];
            }
            set
            {
                bits[9] = value;
            }
        }
Referenced by HotItemLayer.OnClick(), and HotItemLayer.OnSetItem().
backpackHighlightDisabled
bool Player.Flags.backpackHighlightDisabled get set
Definition at line 358 of file Player.cs.
        {
            get
            {
                return bits[8];
            }
            set
            {
                bits[8] = value;
            }
        }
Referenced by HotItemLayer.OnClick(), and HotItemLayer.OnSetItem().
build
int Player.Flags.build get set
Definition at line 598 of file Player.cs.
        {
            get
            {
                return ints[11];
            }
            set
            {
                ints[11] = value;
            }
        }
Referenced by Player.Flags.OnBuild().
canComupWithFoodRecipe
bool Player.Flags.canComupWithFoodRecipe get set
Definition at line 406 of file Player.cs.
        {
            get
            {
                return bits[12];
            }
            set
            {
                bits[12] = value;
            }
        }
Referenced by RecipeCard.Craft().
daysAfterQuestExploration
int Player.Flags.daysAfterQuestExploration get set
Definition at line 646 of file Player.cs.
        {
            get
            {
                return ints[16];
            }
            set
            {
                ints[16] = value;
            }
        }
Referenced by GameDate.AdvanceDay().
debugEnabled
bool Player.Flags.debugEnabled get set
Definition at line 502 of file Player.cs.
        {
            get
            {
                return bits[20];
            }
            set
            {
                bits[20] = value;
            }
        }
Referenced by UI.ToggleFeedback().
elinGift
bool Player.Flags.elinGift get set
Definition at line 382 of file Player.cs.
        {
            get
            {
                return bits[10];
            }
            set
            {
                bits[10] = value;
            }
        }
Referenced by FactionBranch.ReceivePackages().
fiamaFirstDream
bool Player.Flags.fiamaFirstDream get set
Definition at line 310 of file Player.cs.
        {
            get
            {
                return bits[4];
            }
            set
            {
                bits[4] = value;
            }
        }
Referenced by Chara.ShowDialog().
fiamaStoryBookGiven
bool Player.Flags.fiamaStoryBookGiven get set
Definition at line 298 of file Player.cs.
        {
            get
            {
                return bits[3];
            }
            set
            {
                bits[3] = value;
            }
        }
Referenced by Chara.ShowDialog().
gotClickReward
bool Player.Flags.gotClickReward get set
Definition at line 274 of file Player.cs.
        {
            get
            {
                return bits[1];
            }
            set
            {
                bits[1] = value;
            }
        }
gotEtherDisease
bool Player.Flags.gotEtherDisease get set
Definition at line 466 of file Player.cs.
        {
            get
            {
                return bits[17];
            }
            set
            {
                bits[17] = value;
            }
        }
Referenced by Chara.MutateRandom().
gotJurePillow
bool Player.Flags.gotJurePillow get set
Definition at line 538 of file Player.cs.
        {
            get
            {
                return bits[30];
            }
            set
            {
                bits[30] = value;
            }
        }
Referenced by DramaOutcome.convert_Jure().
gotLoytelMart
bool Player.Flags.gotLoytelMart get set
Definition at line 550 of file Player.cs.
        {
            get
            {
                return bits[31];
            }
            set
            {
                bits[31] = value;
            }
        }
Referenced by QuestDebt.GiveReward().
gotMelilithCurse
bool Player.Flags.gotMelilithCurse get set
Definition at line 394 of file Player.cs.
        {
            get
            {
                return bits[11];
            }
            set
            {
                bits[11] = value;
            }
        }
helpHighlightDisabled
bool Player.Flags.helpHighlightDisabled get set
Definition at line 322 of file Player.cs.
        {
            get
            {
                return bits[5];
            }
            set
            {
                bits[5] = value;
            }
        }
Referenced by HotItemLayer.OnClick(), and HotItemLayer.OnSetItem().
isShoesOff
bool Player.Flags.isShoesOff get set
Definition at line 346 of file Player.cs.
        {
            get
            {
                return bits[7];
            }
            set
            {
                bits[7] = value;
            }
        }
Referenced by Chara._Move().
KilledBossInVoid
bool Player.Flags.KilledBossInVoid get set
Definition at line 418 of file Player.cs.
        {
            get
            {
                return bits[13];
            }
            set
            {
                bits[13] = value;
            }
        }
Referenced by Chara.TryDropBossLoot().
killedDuponne
bool Player.Flags.killedDuponne get set
Definition at line 562 of file Player.cs.
        {
            get
            {
                return bits[32];
            }
            set
            {
                bits[32] = value;
            }
        }
landDeedBought
int Player.Flags.landDeedBought get set
Definition at line 658 of file Player.cs.
        {
            get
            {
                return ints[17];
            }
            set
            {
                ints[17] = value;
            }
        }
Referenced by Card.GetPrice().
little_killed
bool Player.Flags.little_killed get set
Definition at line 454 of file Player.cs.
        {
            get
            {
                return bits[16];
            }
            set
            {
                bits[16] = value;
            }
        }
Referenced by Chara.ShowDialog().
little_saved
bool Player.Flags.little_saved get set
Definition at line 442 of file Player.cs.
        {
            get
            {
                return bits[15];
            }
            set
            {
                bits[15] = value;
            }
        }
Referenced by Chara.ShowDialog().
loytelEscaped
bool Player.Flags.loytelEscaped get set
Definition at line 478 of file Player.cs.
        {
            get
            {
                return bits[18];
            }
            set
            {
                bits[18] = value;
            }
        }
Referenced by Chara.ShowDialog().
loytelMartLv
int Player.Flags.loytelMartLv get set
Definition at line 670 of file Player.cs.
        {
            get
            {
                return ints[18];
            }
            set
            {
                ints[18] = value;
            }
        }
Referenced by Trait.CreateStock(), Trait.OnBarter(), and CoreDebug.UpdateInput().
lutz
int Player.Flags.lutz get set
Definition at line 634 of file Player.cs.
        {
            get
            {
                return ints[15];
            }
            set
            {
                ints[15] = value;
            }
        }
Referenced by GameDate.ShipLetter().
magicChestSent
bool Player.Flags.magicChestSent get set
Definition at line 514 of file Player.cs.
        {
            get
            {
                return bits[21];
            }
            set
            {
                bits[21] = value;
            }
        }
Referenced by GameDate.AdvanceDay().
main
int Player.Flags.main get set
Definition at line 610 of file Player.cs.
        {
            get
            {
                return ints[13];
            }
            set
            {
                ints[13] = value;
            }
        }
pickedMelilithTreasure
bool Player.Flags.pickedMelilithTreasure get set
Definition at line 334 of file Player.cs.
        {
            get
            {
                return bits[6];
            }
            set
            {
                bits[6] = value;
            }
        }
reward_gould
int Player.Flags.reward_gould get set
Definition at line 682 of file Player.cs.
        {
            get
            {
                return ints[19];
            }
            set
            {
                ints[19] = value;
            }
        }
Referenced by AI_PlayMusic.ThrowReward().
reward_killkill
int Player.Flags.reward_killkill get set
Definition at line 694 of file Player.cs.
        {
            get
            {
                return ints[20];
            }
            set
            {
                ints[20] = value;
            }
        }
Referenced by AI_PlayMusic.ThrowReward().
santa
int Player.Flags.santa get set
Definition at line 574 of file Player.cs.
        {
            get
            {
                return ints[9];
            }
            set
            {
                ints[9] = value;
            }
        }
start
int Player.Flags.start get set
Definition at line 586 of file Player.cs.
        {
            get
            {
                return ints[10];
            }
            set
            {
                ints[10] = value;
            }
        }
statueShipped
bool Player.Flags.statueShipped get set
Definition at line 430 of file Player.cs.
        {
            get
            {
                return bits[14];
            }
            set
            {
                bits[14] = value;
            }
        }
Referenced by GameDate.ShipRandomPackages().
storyFiama
int Player.Flags.storyFiama get set
Definition at line 622 of file Player.cs.
        {
            get
            {
                return ints[14];
            }
            set
            {
                ints[14] = value;
            }
        }
Referenced by Chara.ShowDialog().
toggleHotbarHighlightActivated
bool Player.Flags.toggleHotbarHighlightActivated get set
Definition at line 526 of file Player.cs.
        {
            get
            {
                return bits[22];
            }
            set
            {
                bits[22] = value;
            }
        }
Referenced by InvOwnerHotbar.OnProcess().
toggleHotbarHighlightDisabled
bool Player.Flags.toggleHotbarHighlightDisabled get set
Definition at line 490 of file Player.cs.
        {
            get
            {
                return bits[19];
            }
            set
            {
                bits[19] = value;
            }
        }
Referenced by WidgetCurrentTool.OnActivate().
welcome
bool Player.Flags.welcome get set
Definition at line 286 of file Player.cs.
        {
            get
            {
                return bits[2];
            }
            set
            {
                bits[2] = value;
            }
        }
The documentation for this class was generated from the following file:
Elin/Player.cs