Elin Decompiled Documentation: LayerArea Class Reference
LayerArea Class Reference
Public Member Functions
override void OnInit ()
void SetArea (Area a)
override void OnKill ()
void ShowPage ()
void AddButton ()
Public Member Functions inherited from ELayer
override void OnBeforeAddLayer ()
void InitInspector ()
sealed override void Init ()
override void OnAfterAddLayer ()
void TryShowHelp ()
void AddLayerToUI (string id)
void TryShowHint (string _langHint=null)
void TalkHomeMemeber (string id)
void TalkMaid (string id)
override void OnRightClick ()
Public Attributes
Area area
Anime animeButton
LayoutGroup layout
UIButton moldButton
RectTransform transMenu
Vector3 offset
Vector3 modPos
Additional Inherited Members
Static Public Member Functions inherited from ELayer
static int rnd (int a)
Protected Member Functions inherited from ELayer
sealed override void _Close ()
sealed override void Kill ()
Properties inherited from ELayer
static Core core [get]
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static FactionBranch Branch [get]
static Faction Home [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static CoreConfig config [get]
static GameSetting setting [get]
static ColorProfile Colors [get]
static SourceManager sources [get]
static World world [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
bool IsFloat [get]
virtual string IdHelp [get]
Detailed Description
Definition at line 5 of file LayerArea.cs.
Member Function Documentation
AddButton()
void LayerArea.AddButton () inline
Definition at line 56 of file LayerArea.cs.
    {
        Util.Instantiate(moldButton, layout);
    }
References layout, and moldButton.
Referenced by ShowPage().
OnInit()
override void LayerArea.OnInit () inline
Definition at line 21 of file LayerArea.cs.
    {
        BuildMenu.Hide();
        moldButton = layout.CreateMold<UIButton>();
    }
References BuildMenu.Hide(), layout, and moldButton.
OnKill()
override void LayerArea.OnKill () inline
Definition at line 33 of file LayerArea.cs.
    {
        BuildMenu.Show();
    }
References BuildMenu.Show().
SetArea()
void LayerArea.SetArea (Area a) inline
Definition at line 27 of file LayerArea.cs.
    {
        area = a;
        ShowPage();
    }
References area, and ShowPage().
ShowPage()
void LayerArea.ShowPage () inline
Definition at line 38 of file LayerArea.cs.
    {
        transMenu.position = Input.mousePosition + offset;
        layout.DestroyChildren();
        AddButton();
        AddButton();
        AddButton();
        layout.RebuildLayout(recursive: true);
        layout.enabled = false;
        List<UIButton> componentsInDirectChildren = layout.GetComponentsInDirectChildren<UIButton>();
        for (int i = 0; i < componentsInDirectChildren.Count; i++)
        {
            UIButton uIButton = componentsInDirectChildren[i];
            uIButton.transform.position = uIButton.transform.position + modPos * i;
            animeButton.Play(uIButton.transform);
        }
    }
References AddButton(), animeButton, layout, modPos, and offset.
Referenced by SetArea().
Member Data Documentation
animeButton
Anime LayerArea.animeButton
Definition at line 9 of file LayerArea.cs.
Referenced by ShowPage().
area
Area LayerArea.area
Definition at line 7 of file LayerArea.cs.
Referenced by SetArea().
layout
LayoutGroup LayerArea.layout
Definition at line 11 of file LayerArea.cs.
Referenced by AddButton(), OnInit(), and ShowPage().
modPos
Vector3 LayerArea.modPos
Definition at line 19 of file LayerArea.cs.
Referenced by ShowPage().
moldButton
UIButton LayerArea.moldButton
Definition at line 13 of file LayerArea.cs.
Referenced by AddButton(), and OnInit().
offset
Vector3 LayerArea.offset
Definition at line 17 of file LayerArea.cs.
Referenced by ShowPage().
transMenu
RectTransform LayerArea.transMenu
Definition at line 15 of file LayerArea.cs.
The documentation for this class was generated from the following file:
Elin/LayerArea.cs