Elin Decompiled Documentation: WorkSummary Class Reference
WorkSummary Class Reference
Public Member Functions
void Reset ()
void AddThing (Thing t)
Public Attributes
int[] ints = new int[10]
WorkSession work
List< WorkSession > hobbies = new List<WorkSession>()
List< Thing > things = new List<Thing>()
Properties
int progress [get, set]
int money [get, set]
int food [get, set]
int knowledge [get, set]
int material [get, set]
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Additional Inherited Members
Static Public Member Functions inherited from EClass
static int rndSeed (int a, int seed)
static int rnd (long a)
static int rnd (int a)
static int curve (int a, int start, int step, int rate=75)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Static Public Attributes inherited from EClass
static Core core
Detailed Description
Definition at line 4 of file WorkSummary.cs.
Member Function Documentation
AddThing()
void WorkSummary.AddThing (Thing t) inline
Definition at line 87 of file WorkSummary.cs.
    {
        things.Add(t);
    }
References ActPlan.List.Add(), and things.
Referenced by AIWork.AddDeliverable().
Reset()
void WorkSummary.Reset () inline
Definition at line 78 of file WorkSummary.cs.
    {
        int num2 = (material = 0);
        int num4 = (knowledge = num2);
        int num6 = (food = num4);
        int num8 = (money = num6);
        progress = num8;
    }
References food, knowledge, material, money, and progress.
Member Data Documentation
hobbies
List<WorkSession> WorkSummary.hobbies = new List<WorkSession>()
Definition at line 13 of file WorkSummary.cs.
Referenced by GoalWork.FindWork(), Chara.TickWork(), GoalWork.TryWork(), and GoalWork.ValidateHobby().
ints
int [] WorkSummary.ints = new int[10]
Definition at line 7 of file WorkSummary.cs.
things
List<Thing> WorkSummary.things = new List<Thing>()
Definition at line 16 of file WorkSummary.cs.
Referenced by AddThing().
work
WorkSession WorkSummary.work
Definition at line 10 of file WorkSummary.cs.
Referenced by UIHomeInfo.RefreshReport(), and Chara.TickWork().
Property Documentation
food
int WorkSummary.food get set
Definition at line 42 of file WorkSummary.cs.
    {
        get
        {
            return ints[6];
        }
        set
        {
            ints[6] = value;
        }
    }
Referenced by Reset().
knowledge
int WorkSummary.knowledge get set
Definition at line 54 of file WorkSummary.cs.
    {
        get
        {
            return ints[7];
        }
        set
        {
            ints[7] = value;
        }
    }
Referenced by Reset().
material
int WorkSummary.material get set
Definition at line 66 of file WorkSummary.cs.
    {
        get
        {
            return ints[8];
        }
        set
        {
            ints[8] = value;
        }
    }
Referenced by Reset().
money
int WorkSummary.money get set
Definition at line 30 of file WorkSummary.cs.
    {
        get
        {
            return ints[5];
        }
        set
        {
            ints[5] = value;
        }
    }
Referenced by Reset().
progress
int WorkSummary.progress get set
Definition at line 18 of file WorkSummary.cs.
    {
        get
        {
            return ints[0];
        }
        set
        {
            ints[0] = value;
        }
    }
Referenced by Expedition.End(), and Reset().
The documentation for this class was generated from the following file:
Elin/WorkSummary.cs