Elin Decompiled Documentation: SourceDeco Class Reference
SourceDeco Class Reference
Classes
class Row
Public Member Functions
override Row CreateRow ()
override Row CreateRowByMapping (IReadOnlyDictionary< string, int > mapping)
override void SetRow (Row r)
override IReadOnlyDictionary< string, int > GetRowMapping ()
override IReadOnlyDictionary< string, string > GetTypeMapping ()
override void BackupPref ()
override void RestorePref ()
override void ValidatePref ()
override void OnAfterImportData ()
override void OnInit ()
Public Member Functions inherited from SourceDataInt< SourceDeco.Row >
override T GetRow (string id)
Public Attributes
Dictionary< int, Row > _rows = new Dictionary<int, Row>()
Static Public Attributes
static readonly IReadOnlyDictionary< string, int > RowMapping
static readonly IReadOnlyDictionary< string, string > TypeMapping
Detailed Description
Definition at line 4 of file SourceDeco.cs.
Member Function Documentation
BackupPref()
override void SourceDeco.BackupPref () inline
Definition at line 186 of file SourceDeco.cs.
    {
        _rows.Clear();
        foreach (Row row in rows)
        {
            _rows[row.id] = row;
        }
    }
References _rows, and TileRow.id.
CreateRow()
override Row SourceDeco.CreateRow () inline
Definition at line 101 of file SourceDeco.cs.
    {
        return new Row
        {
            id = SourceData.GetInt(0),
            alias = SourceData.GetString(1),
            name_JP = SourceData.GetString(2),
            name = SourceData.GetString(3),
            sort = SourceData.GetInt(4),
            idBiome = SourceData.GetString(5),
            reqHarvest = SourceData.GetStringArray(6),
            hp = SourceData.GetInt(7),
            _tileType = SourceData.GetString(8),
            _idRenderData = SourceData.GetString(9),
            tiles = SourceData.GetIntArray(10),
            anime = SourceData.GetIntArray(11),
            colorMod = SourceData.GetInt(12),
            value = SourceData.GetInt(13),
            LV = SourceData.GetInt(14),
            recipeKey = SourceData.GetStringArray(15),
            factory = SourceData.GetStringArray(16),
            components = SourceData.GetStringArray(17),
            defMat = SourceData.GetString(18),
            category = SourceData.GetString(19),
            edge = SourceData.GetInt(20),
            autotile = SourceData.GetInt(21),
            autotilePriority = SourceData.GetInt(22),
            autotileBrightness = SourceData.GetFloat(23),
            soundFoot = SourceData.GetString(24),
            tag = SourceData.GetStringArray(25),
            detail_JP = SourceData.GetString(26),
            detail = SourceData.GetString(27)
        };
    }
References SourceData< T, T2 >.GetFloat(), SourceData< T, T2 >.GetInt(), SourceData< T, T2 >.GetIntArray(), SourceData< T, T2 >.GetString(), and SourceData< T, T2 >.GetStringArray().
CreateRowByMapping()
override Row SourceDeco.CreateRowByMapping (IReadOnlyDictionary< string, int > mapping) inline
Definition at line 136 of file SourceDeco.cs.
    {
        return new Row
        {
            id = SourceData.GetInt(mapping["id"]),
            alias = SourceData.GetString(mapping["alias"]),
            name_JP = SourceData.GetString(mapping["name_JP"]),
            name = SourceData.GetString(mapping["name"]),
            sort = SourceData.GetInt(mapping["sort"]),
            idBiome = SourceData.GetString(mapping["idBiome"]),
            reqHarvest = SourceData.GetStringArray(mapping["reqHarvest"]),
            hp = SourceData.GetInt(mapping["hp"]),
            _tileType = SourceData.GetString(mapping["_tileType"]),
            _idRenderData = SourceData.GetString(mapping["_idRenderData"]),
            tiles = SourceData.GetIntArray(mapping["tiles"]),
            anime = SourceData.GetIntArray(mapping["anime"]),
            colorMod = SourceData.GetInt(mapping["colorMod"]),
            value = SourceData.GetInt(mapping["value"]),
            LV = SourceData.GetInt(mapping["LV"]),
            recipeKey = SourceData.GetStringArray(mapping["recipeKey"]),
            factory = SourceData.GetStringArray(mapping["factory"]),
            components = SourceData.GetStringArray(mapping["components"]),
            defMat = SourceData.GetString(mapping["defMat"]),
            category = SourceData.GetString(mapping["category"]),
            edge = SourceData.GetInt(mapping["edge"]),
            autotile = SourceData.GetInt(mapping["autotile"]),
            autotilePriority = SourceData.GetInt(mapping["autotilePriority"]),
            autotileBrightness = SourceData.GetFloat(mapping["autotileBrightness"]),
            soundFoot = SourceData.GetString(mapping["soundFoot"]),
            tag = SourceData.GetStringArray(mapping["tag"]),
            detail_JP = SourceData.GetString(mapping["detail_JP"]),
            detail = SourceData.GetString(mapping["detail"])
        };
    }
References SourceData< T, T2 >.GetFloat(), SourceData< T, T2 >.GetInt(), SourceData< T, T2 >.GetIntArray(), SourceData< T, T2 >.GetString(), and SourceData< T, T2 >.GetStringArray().
GetRowMapping()
override IReadOnlyDictionary< string, int > SourceDeco.GetRowMapping () inline
Definition at line 176 of file SourceDeco.cs.
    {
        return RowMapping;
    }
References RowMapping.
GetTypeMapping()
override IReadOnlyDictionary< string, string > SourceDeco.GetTypeMapping () inline
Definition at line 181 of file SourceDeco.cs.
    {
        return TypeMapping;
    }
References TypeMapping.
OnAfterImportData()
override void SourceDeco.OnAfterImportData () inline
Definition at line 211 of file SourceDeco.cs.
    {
        int num = 0;
        foreach (Row row in rows)
        {
            if (row.sort != 0)
            {
                num = row.sort;
            }
            row.sort = num;
            num++;
        }
        rows.Sort((Row a, Row b) => a.id - b.id);
    }
References TileRow.id, and RenderRow.sort.
OnInit()
override void SourceDeco.OnInit () inline
Definition at line 226 of file SourceDeco.cs.
    {
        Cell.decoList = rows;
        foreach (Row row in rows)
        {
            row.Init();
        }
    }
References TileRow.Init().
RestorePref()
override void SourceDeco.RestorePref () inline
Definition at line 195 of file SourceDeco.cs.
    {
        foreach (Row row in rows)
        {
            row.pref = _rows.TryGetValue(row.id)?.pref ?? new SourcePref();
        }
    }
References _rows, and TileRow.id.
SetRow()
override void SourceDeco.SetRow (Row r) inline
Definition at line 171 of file SourceDeco.cs.
    {
        map[r.id] = r;
    }
References TileRow.id.
ValidatePref()
override void SourceDeco.ValidatePref () inline
Definition at line 203 of file SourceDeco.cs.
    {
        foreach (Row row in rows)
        {
            row.pref.Validate();
        }
    }
References RenderRow.pref, and SourcePref.Validate().
Member Data Documentation
_rows
Dictionary<int, Row> SourceDeco._rows = new Dictionary<int, Row>()
Definition at line 99 of file SourceDeco.cs.
Referenced by BackupPref(), and RestorePref().
RowMapping
readonly IReadOnlyDictionary<string, int> SourceDeco.RowMapping static
Definition at line 35 of file SourceDeco.cs.
Referenced by GetRowMapping().
TypeMapping
readonly IReadOnlyDictionary<string, string> SourceDeco.TypeMapping static
Definition at line 67 of file SourceDeco.cs.
Referenced by GetTypeMapping().
The documentation for this class was generated from the following file:
Elin/SourceDeco.cs