Elin Decompiled Documentation: SpatialGen Class Reference
SpatialGen Class Reference
Static Public Member Functions
static Spatial CreateRecursive (string id, Spatial parent=null)
static Spatial Create (string id, Spatial parent, bool register, int x=-99999, int y=-99999, int icon=0)
static Zone CreateInstance (string id, ZoneInstance instance)
Static Public Member Functions inherited from EClass
static int rnd (int a)
static int curve (int a, int start, int step, int rate=75)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Additional Inherited Members
Static Public Attributes inherited from EClass
static Core core
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Detailed Description
Definition at line 1 of file SpatialGen.cs.
Member Function Documentation
Create()
static Spatial SpatialGen.Create (string id, Spatial parent, bool register, int x = -99999, int y = -99999, int icon = 0) inline static
Definition at line 16 of file SpatialGen.cs.
    {
        SourceZone.Row row = EClass.sources.zones.map[id];
        Spatial spatial = ClassCache.Create<Spatial>(row.type, "Elin");
        if (x == -99999)
        {
            x = ((row.pos.Length != 0) ? row.pos[0] : (-1000));
            y = ((row.pos.Length != 0) ? row.pos[1] : (-1000));
        }
        if (icon == 0 && row.pos.Length != 0)
        {
            icon = row.pos[2];
        }
        spatial.Create(id, x, y, icon);
        if (register)
        {
            spatial.Register();
        }
        parent?.AddChild(spatial);
        spatial.OnAfterCreate();
        return spatial;
    }
References Spatial.AddChild(), Spatial.Create(), Spatial.OnAfterCreate(), SourceZone.Row.pos, Spatial.Register(), EClass.sources, SourceZone.Row.type, and SourceManager.zones.
Referenced by Region.CheckRandomSites(), CreateInstance(), Region.CreateRandomSite(), CreateRecursive(), Region.CreateZone(), TraitNewZone.CreateZone(), TraitMoongate.LoadMap(), Game.OnLoad(), and Game.StartNewGame().
CreateInstance()
static Zone SpatialGen.CreateInstance (string id, ZoneInstance instance) inline static
Definition at line 39 of file SpatialGen.cs.
    {
        Zone topZone = EClass._zone.GetTopZone();
        Zone obj = Create(id, EClass._zone.Region, register: true, topZone.x, topZone.y) as Zone;
        obj.instance = instance;
        instance.x = EClass.pc.pos.x;
        instance.z = EClass.pc.pos.z;
        instance.uidZone = EClass._zone.uid;
        obj.dateExpire = EClass.world.date.GetRaw() + 1440;
        return obj;
    }
References EClass._zone, Create(), World.date, Date.GetRaw(), Zone.GetTopZone(), EClass.pc, Card.pos, Zone.Region, Spatial.uid, EClass.world, Point.x, Spatial.x, Spatial.y, and Point.z.
Referenced by QuestInstance.CreateInstanceZone().
CreateRecursive()
static Spatial SpatialGen.CreateRecursive (string id, Spatial parent = null) inline static
Definition at line 3 of file SpatialGen.cs.
    {
        Spatial spatial = Create(id, parent, register: true);
        foreach (SourceZone.Row row in EClass.sources.zones.rows)
        {
            if ((!row.tag.Contains("debug") || EClass.debug.enable) && row.parent == id)
            {
                CreateRecursive(row.id, spatial);
            }
        }
        return spatial;
    }
References Create(), CreateRecursive(), EClass.debug, CoreDebug.enable, EClass.sources, and SourceManager.zones.
Referenced by Game._Create(), and CreateRecursive().
The documentation for this class was generated from the following file:
Elin/SpatialGen.cs