Elin Decompiled Documentation: DragItemCard Class Reference
DragItemCard Class Reference
Classes
class DragInfo
Public Member Functions
DragItemCard (ButtonGrid _button, bool setDragImage=true)
override void OnStartDrag ()
override void OnEndDrag ()
override bool OnDragSpecial ()
override bool OnDrag (bool execute, bool cancel=false)
Public Member Functions inherited from DragItem
virtual Image GetDragImage ()
virtual void OnStartDrag ()
virtual void OnEndDrag ()
virtual bool OnDrag (bool execute, bool cancel=false)
virtual bool OnDragSpecial ()
Public Attributes
ButtonGrid button
DragInfo from
DragInfo to
Properties
override UIButton Button [get]
Properties inherited from DragItem
virtual UIButton Button [get]
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Additional Inherited Members
Static Public Member Functions inherited from EClass
static int rndSeed (int a, int seed)
static int rnd (long a)
static int rnd (int a)
static int curve (int a, int start, int step, int rate=75)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Static Public Attributes inherited from EClass
static Core core
Detailed Description
Definition at line 3 of file DragItemCard.cs.
Constructor & Destructor Documentation
DragItemCard()
DragItemCard.DragItemCard (ButtonGrid _button, bool setDragImage = true) inline
Definition at line 60 of file DragItemCard.cs.
    {
        button = _button;
        from = new DragInfo(button);
        if (setDragImage)
        {
            EClass.ui.hud.SetDragImage(button.icon, null, button.mainText);
        }
    }
References button, from, UIButton.icon, UIButton.mainText, and EClass.ui.
Member Function Documentation
OnDrag()
override bool DragItemCard.OnDrag (bool execute, bool cancel = false) inline virtual
Reimplemented from DragItem.
Definition at line 112 of file DragItemCard.cs.
    {
        DragInfo dragInfo = new DragInfo(InputModuleEX.GetComponentOf<ButtonGrid>());
        bool num = from.invOwner.OnDrag(from, dragInfo, execute, cancel);
        if (num && EClass.core.config.game.doubleClickToHold && EClass.ui.dragDuration < 0.35f && dragInfo.button == from.button && from.thing != null)
        {
            dragInfo.button.invOwner.TryHold(from.thing);
        }
        return num;
    }
References DragItemCard.DragInfo.button, Core.config, EClass.core, CoreConfig.GameConfig.doubleClickToHold, from, CoreConfig.game, ButtonGrid.invOwner, DragItemCard.DragInfo.invOwner, InvOwner.OnDrag(), DragItemCard.DragInfo.thing, InvOwner.TryHold(), and EClass.ui.
OnDragSpecial()
override bool DragItemCard.OnDragSpecial () inline virtual
Reimplemented from DragItem.
Definition at line 89 of file DragItemCard.cs.
    {
        DragInfo dragInfo = new DragInfo(InputModuleEX.GetComponentOf<ButtonGrid>());
        if (dragInfo != null && (bool)dragInfo.button && dragInfo.button.interactable && !(dragInfo.invOwner is InvOwnerHotbar) && dragInfo.invOwner.owner == from.invOwner.owner && dragInfo.invOwner.owner.IsPC && from.thing.Num > 1 && (dragInfo.thing == null || dragInfo.thing.CanStackTo(from.thing)))
        {
            bool num = dragInfo.thing != null;
            Thing thing = from.thing.Split(1);
            SE.Play(thing.material.GetSoundDrop(thing.sourceCard));
            if (num)
            {
                dragInfo.thing.ModNum(1);
            }
            else
            {
                dragInfo.invOwner.Container.AddThing(thing, tryStack: false);
                thing.invX = dragInfo.invX;
                thing.invY = dragInfo.invY;
            }
            return true;
        }
        return false;
    }
References Card.AddThing(), DragItemCard.DragInfo.button, Thing.CanStackTo(), InvOwner.Container, from, DragItemCard.DragInfo.invOwner, DragItemCard.DragInfo.invX, DragItemCard.DragInfo.invY, Card.IsPC, Card.material, Card.ModNum(), Card.Num, InvOwner.owner, Thing.sourceCard, Card.Split(), and DragItemCard.DragInfo.thing.
OnEndDrag()
override void DragItemCard.OnEndDrag () inline virtual
Reimplemented from DragItem.
Definition at line 79 of file DragItemCard.cs.
    {
        WidgetEquip.dragEquip = null;
        WidgetEquip.Redraw();
        if ((bool)LayerDragGrid.Instance)
        {
            LayerDragGrid.Instance.CurrentButton.Dettach("guide");
        }
    }
References LayerDragGrid.CurrentButton, ButtonGrid.Dettach(), LayerDragGrid.Instance, and WidgetEquip.Redraw().
OnStartDrag()
override void DragItemCard.OnStartDrag () inline virtual
Reimplemented from DragItem.
Definition at line 70 of file DragItemCard.cs.
    {
        from.invOwner.OnStartDrag(from);
        if ((bool)LayerDragGrid.Instance && LayerDragGrid.Instance.owner.ShouldShowGuide(from.thing))
        {
            LayerDragGrid.Instance.CurrentButton.Attach("guide", rightAttach: false);
        }
    }
References ButtonGrid.Attach(), LayerDragGrid.CurrentButton, from, LayerDragGrid.Instance, DragItemCard.DragInfo.invOwner, InvOwner.OnStartDrag(), LayerDragGrid.owner, InvOwner.ShouldShowGuide(), and DragItemCard.DragInfo.thing.
Member Data Documentation
button
ButtonGrid DragItemCard.button
Definition at line 52 of file DragItemCard.cs.
Referenced by DragItemCard(), InvOwner.Transaction.IsValid(), InvOwner.Transaction.Process(), and InvOwner.Transaction.Transaction().
from
DragInfo DragItemCard.from
Definition at line 54 of file DragItemCard.cs.
Referenced by DragItemCard(), OnDrag(), OnDragSpecial(), OnStartDrag(), and Thing.ShowSplitMenu().
to
DragInfo DragItemCard.to
Definition at line 56 of file DragItemCard.cs.
Property Documentation
Button
override UIButton DragItemCard.Button get
Definition at line 58 of file DragItemCard.cs.
The documentation for this class was generated from the following file:
Elin/DragItemCard.cs