Elin Decompiled Documentation: ZoneEventPhone Class Reference
ZoneEventPhone Class Reference
Public Member Functions
override void OnInit ()
override void OnTickRound ()
override void OnKill ()
Public Member Functions inherited from ZoneEvent
virtual string GetText ()
void Tick (float delta)
void Init ()
void OnSimulateHour ()
virtual void OnVisit ()
virtual void OnInit ()
virtual void OnFirstTick ()
virtual void OnTick ()
virtual void OnTickRound ()
virtual void OnKill ()
virtual void OnCharaDie (Chara c)
virtual void OnLeaveZone ()
virtual void OnLoad ()
void Kill ()
Public Attributes
int uidPhone
int ring
Public Attributes inherited from ZoneEvent
float time
int rounds
int hoursElapsed
int minElapsed
Zone zone
bool firstTick = true
Properties
override int hoursToKill [get]
TraitPhone Phone [get]
Properties inherited from ZoneEvent
SourceQuest.Row source [get]
virtual string id [get]
virtual string TextWidgetDate [get]
virtual float roundInterval [get]
virtual Playlist playlist [get]
virtual bool debugSkip [get]
virtual string RefStr2 [get]
virtual string RefStr3 [get]
virtual int hoursToKill [get]
virtual bool HasReport [get]
string Name [get]
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Additional Inherited Members
Static Public Member Functions inherited from EClass
static int rndSeed (int a, int seed)
static int rnd (long a)
static int rnd (int a)
static int curve (int a, int start, int step, int rate=75)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Static Public Attributes inherited from EClass
static Core core
Detailed Description
Definition at line 3 of file ZoneEventPhone.cs.
Member Function Documentation
OnInit()
override void ZoneEventPhone.OnInit () inline virtual
Reimplemented from ZoneEvent.
Definition at line 15 of file ZoneEventPhone.cs.
    {
        ring = EClass.rnd(4) + 3;
    }
References ring, and EClass.rnd().
OnKill()
override void ZoneEventPhone.OnKill () inline virtual
Reimplemented from ZoneEvent.
Definition at line 38 of file ZoneEventPhone.cs.
    {
        if (Phone != null)
        {
            Phone.ev = null;
        }
    }
References Phone.
OnTickRound()
override void ZoneEventPhone.OnTickRound () inline virtual
Reimplemented from ZoneEvent.
Definition at line 20 of file ZoneEventPhone.cs.
    {
        TraitPhone phone = Phone;
        if (phone == null)
        {
            Kill();
            return;
        }
        ring--;
        phone.owner.TalkRaw(Lang.Game.Get("phone_boss"));
        phone.owner.PlayAnime(AnimeID.Shiver);
        phone.ev = this;
        if (ring < 0)
        {
            Kill();
        }
    }
References Lang.Game, SourceLang< T >.Get(), ZoneEvent.Kill(), Trait.owner, Phone, Card.PlayAnime(), ring, and Card.TalkRaw().
Member Data Documentation
ring
int ZoneEventPhone.ring
Definition at line 9 of file ZoneEventPhone.cs.
Referenced by OnInit(), and OnTickRound().
uidPhone
int ZoneEventPhone.uidPhone
Definition at line 6 of file ZoneEventPhone.cs.
Property Documentation
hoursToKill
override int ZoneEventPhone.hoursToKill get
Definition at line 11 of file ZoneEventPhone.cs.
Phone
TraitPhone ZoneEventPhone.Phone get
Definition at line 13 of file ZoneEventPhone.cs.
Referenced by OnKill(), and OnTickRound().
The documentation for this class was generated from the following file:
Elin/ZoneEventPhone.cs