Elin Decompiled Documentation: TaskDump Class Reference
TaskDump Class Reference
Public Member Functions
override bool CanManualCancel ()
override IEnumerable< Status > Run ()
override void OnCancelOrSuccess ()
bool IsValidContainer (Thing c)
List< Thing > ListThingsToPut (Thing c)
Public Member Functions inherited from Task
virtual HitResult GetHitResult ()
override void OnSuccess ()
void TryLayer (int min=30)
Status Destroy ()
virtual void OnDestroy ()
override Status Cancel ()
override void OnReset ()
override bool CanProgress ()
bool CanPerformTask (Chara chara, int radius)
virtual bool _CanPerformTask (Chara chara, int radius)
virtual void OnAdd ()
void ToggleSuspend ()
Public Member Functions inherited from AIAct
override string ToString ()
override MultiSprite GetStateIcon ()
virtual Point GetDestination ()
AIProgress GetProgress ()
string GetCurrentActionText ()
override bool IsToolValid ()
virtual void OnStart ()
void SetOwner (Chara c)
virtual void OnSetOwner ()
void SetChild (AIAct seq, Func< Status > _onChildFail=null)
void Start ()
override bool Perform ()
Status Restart ()
Status Success (Action action=null)
virtual void OnSuccess ()
bool TryCancel (Card c)
virtual Status Cancel ()
virtual void OnCancel ()
virtual void OnCancelOrSuccess ()
virtual bool CanManualCancel ()
Status KeepRunning ()
void Reset ()
virtual void OnReset ()
Status Tick ()
virtual IEnumerable< Status > Run ()
Status TickChild ()
Status Do (AIAct _seq, Func< Status > _onChildFail=null)
Status DoGotoInteraction (Point pos, Func< Status > _onChildFail=null)
Status DoGoto (Point pos, int dist=0, bool ignoreConnection=false, Func< Status > _onChildFail=null)
Status DoGoto (Card card, Func< Status > _onChildFail=null)
Status DoGoto (Card card, int dist, Func< Status > _onChildFail=null)
Status DoGotoSpot (Card card, Func< Status > _onChildFail=null)
Status DoGoto< T > (Func< Status > _onChildFail=null)
Status DoGotoSpot< T > (Func< Status > _onChildFail=null, bool ignoreAccessType=false)
Status DoGrab (Card card, int num=-1, bool pickHeld=false, Func< Status > _onChildFail=null)
Status DoGrab< T > ()
Status DoProgress ()
Status DoIdle (int repeat=3)
Status DoWait (int count=1)
virtual AIProgress CreateProgress ()
virtual void OnCreateProgress (Progress_Custom p)
virtual bool CanProgress ()
virtual void OnBeforeProgress ()
virtual void OnProgress ()
virtual void OnProgressComplete ()
void SimulateZone (int days)
virtual void OnSimulateZone (int days)
virtual void OnSimulatePosition ()
Public Member Functions inherited from Act
virtual CursorInfo GetCursorIcon (Card c)
virtual MultiSprite GetStateIcon ()
override Sprite GetSprite ()
virtual bool ShowMouseHint (Card c)
virtual bool IsValidTC (Card c)
virtual string GetHintText (string str="")
virtual string GetText (string str="")
virtual string GetTextSmall (Card c)
virtual Color GetActPlanColor ()
virtual bool Perform ()
virtual bool CanPerform ()
bool Perform (Chara _cc, Card _tc=null, Point _tp=null)
bool CanPerform (Chara _cc, Card _tc=null, Point _tp=null)
virtual bool IsToolValid ()
new void SetImage (Image image)
virtual void OnMarkMapHighlights ()
virtual bool ShouldMapHighlight (Point p)
virtual CursorInfo GetCursorIcon (Card c)
virtual MultiSprite GetStateIcon ()
override Sprite GetSprite ()
virtual bool ShowMouseHint (Card c)
virtual bool IsValidTC (Card c)
virtual string GetHintText (string str="")
virtual string GetText (string str="")
virtual string GetTextSmall (Card c)
virtual Color GetActPlanColor ()
virtual bool Perform ()
virtual bool CanPerform ()
bool Perform (Chara _cc, Card _tc=null, Point _tp=null)
bool CanPerform (Chara _cc, Card _tc=null, Point _tp=null)
virtual bool IsToolValid ()
new void SetImage (Image image)
virtual void OnMarkMapHighlights ()
virtual bool ShouldMapHighlight (Point p)
Public Member Functions inherited from Element
virtual SourceElement.Row GetSource ()
virtual int GetSourcePotential (int v)
virtual Sprite GetSprite ()
int GetMaterialSourceValue (Thing t, int v)
virtual int GetSourceValue (int v, int lv, SourceValueType type)
virtual Sprite GetIcon (string suffix="")
int SortVal (bool charaSheet=false)
virtual bool CanLink (ElementContainer owner)
bool HasTag (string tag)
void SetImage (Image i)
virtual string GetDetail ()
bool IsFactionElement (Chara c)
Element GetParent (Card c)
void WriteNote (UINote n, ElementContainer owner=null, Action< UINote > onWriteNote=null)
void WriteNoteWithRef (UINote n, ElementContainer owner, Action< UINote > onWriteNote, Element refEle)
void _WriteNote (UINote n, Chara c, Act act)
void _WriteNote (UINote n, ElementContainer owner, Action< UINote > onWriteNote, bool isRef, bool addHeader=true)
virtual void OnWriteNote (UINote n, ElementContainer owner)
virtual void OnChangeValue ()
void CheckLevelBonus (ElementContainer owner, UINote n=null)
int GetSortVal (UIList.SortMode m)
virtual Act.Cost GetCost (Chara c)
virtual int GetPower (Card c)
virtual void SetTextValue (UIText text)
virtual SourceElement.Row GetSource ()
virtual int GetSourcePotential (int v)
virtual Sprite GetSprite ()
int GetMaterialSourceValue (Thing t, int v)
virtual int GetSourceValue (int v, int lv, SourceValueType type)
virtual Sprite GetIcon (string suffix="")
int SortVal (bool charaSheet=false)
virtual bool CanLink (ElementContainer owner)
bool HasTag (string tag)
void SetImage (Image i)
virtual string GetDetail ()
bool IsFactionElement (Chara c)
Element GetParent (Card c)
void WriteNote (UINote n, ElementContainer owner=null, Action< UINote > onWriteNote=null)
void WriteNoteWithRef (UINote n, ElementContainer owner, Action< UINote > onWriteNote, Element refEle)
void _WriteNote (UINote n, Chara c, Act act)
void _WriteNote (UINote n, ElementContainer owner, Action< UINote > onWriteNote, bool isRef, bool addHeader=true)
virtual void OnWriteNote (UINote n, ElementContainer owner)
virtual void OnChangeValue ()
void CheckLevelBonus (ElementContainer owner, UINote n=null)
int GetSortVal (UIList.SortMode m)
virtual Act.Cost GetCost (Chara c)
virtual int GetPower (Card c)
virtual void SetTextValue (UIText text)
Static Public Member Functions
static void TryPerform ()
Static Public Member Functions inherited from Act
static void SetReference (Chara _cc, Card _tc=null, Point _tp=null)
static void SetTool (Thing t)
static void SetReference (Chara _cc, Card _tc=null, Point _tp=null)
static void SetTool (Thing t)
Static Public Member Functions inherited from Element
static string GetName (string alias)
static SourceElement.Row Get (int id)
static Dictionary< int, int > GetElementMap (int[] list)
static Dictionary< int, int > GetElementMap (int[] list, Dictionary< int, int > map)
static SourceElement.Row GetRandomElement (int lv=1)
static Element Create (int id, int v=0)
static Element Create (string id, int v=1)
static int GetId (string alias)
static int GetResistLv (int v)
static int GetResistDamage (int dmg, int v)
static string GetName (string alias)
static SourceElement.Row Get (int id)
static Dictionary< int, int > GetElementMap (int[] list)
static Dictionary< int, int > GetElementMap (int[] list, Dictionary< int, int > map)
static SourceElement.Row GetRandomElement (int lv=1)
static Element Create (int id, int v=0)
static Element Create (string id, int v=1)
static int GetId (string alias)
static int GetResistLv (int v)
static int GetResistDamage (int dmg, int v)
Static Public Member Functions inherited from EClass
static int rnd (int a)
static int curve (int a, int start, int step, int rate=75)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Additional Inherited Members
Public Types inherited from AIAct
enum Status { Running , Fail , Success }
Public Types inherited from Act
enum CostType {
None , MP , SP , None ,
MP , SP
}
enum CostType {
None , MP , SP , None ,
MP , SP
}
Public Attributes inherited from Task
TaskList taskList
bool isDestroyed
int nextTry
bool suspended
Public Attributes inherited from AIAct
new Chara owner
Status status
IEnumerator< Status > Enumerator
AIAct child
AIAct parent
byte restartCount
Func< Status > onChildFail
Func< bool > isFail
Public Attributes inherited from Element
SourceElement.Row _source
int id
int vBase
int vExp
int vPotential
int vTempPotential
int vLink
int vSource
int vSourcePotential
ElementContainer owner
Static Public Attributes inherited from Act
static Chara CC
static Card TC
static Point TP = new Point()
static Thing TOOL
static int powerMod = 100
static bool forcePt
Static Public Attributes inherited from Element
const int Div = 5
static Element Void = new Element()
static int[] List_MainAttributes
static int[] List_MainAttributesMajor
static int[] List_Body
static int[] List_Mind
static List< SourceElement.Row > ListElements = new List<SourceElement.Row>()
static List< SourceElement.Row > ListAttackElements = new List<SourceElement.Row>()
Static Public Attributes inherited from EClass
static Core core
Static Package Functions inherited from Element
static string< _WriteNote > g__Calc (ref Element.<>c__DisplayClass103_0 A_0)
Properties inherited from Task
override TargetType TargetType [get]
Properties inherited from AIAct
virtual bool IsRunning [get]
bool IsChildRunning [get]
bool IsMoveAI [get]
virtual int MaxRestart [get]
virtual new string Name [get]
virtual MultiSprite stateIcon [get]
virtual Sprite actionIcon [get]
virtual bool IsNoGoal [get]
virtual bool IsAutoTurn [get]
virtual bool IsIdle [get]
virtual bool PushChara [get]
virtual int MaxProgress [get]
virtual bool ShowProgress [get]
virtual bool UseTurbo [get]
virtual int CurrentProgress [get]
virtual bool ShowCursor [get]
virtual bool CancelWhenDamaged [get]
virtual bool CancelWhenMoved [get]
virtual bool InformCancel [get]
virtual Thing RenderThing [get]
AIAct Current [get]
override bool IsAct [get]
override bool ShowPotential [get]
override bool UsePotential [get]
override bool ShowRelativeAttribute [get]
virtual bool HasProgress [get]
Properties inherited from Act
override bool ShowPotential [get]
override bool UsePotential [get]
override bool ShowRelativeAttribute [get]
virtual CursorInfo CursorIcon [get]
virtual string ID [get]
virtual bool IsAct [get]
virtual bool WillEndTurn [get]
virtual bool CloseLayers [get]
virtual int LeftHand [get]
virtual int RightHand [get]
virtual int ElementPowerMod [get]
virtual bool ShowMapHighlight [get]
virtual bool ShowMapHighlightBlock [get]
virtual bool PickHeldOnStart [get]
virtual bool DropHeldOnStart [get]
virtual bool CanPressRepeat [get]
virtual bool CanAutofire [get]
virtual bool ResetAxis [get]
virtual bool RequireTool [get]
virtual bool IsHostileAct [get]
virtual bool HideRightInfo [get]
virtual bool HaveLongPressAction [get]
virtual float Radius [get]
virtual int PerformDistance [get]
virtual int MaxRadius [get]
virtual TargetType TargetType [get]
virtual bool LocalAct [get]
virtual bool CanRapidFire [get]
virtual float RapidDelay [get]
virtual bool ShowAuto [get]
virtual bool IsCrime [get]
Properties inherited from Element
SourceElement.Row source [get]
virtual int DisplayValue [get]
virtual int MinValue [get]
int Value [get]
int ValueWithoutLink [get]
virtual int MinPotential [get]
int Potential [get]
virtual bool CanGainExp [get]
bool IsFlag [get]
virtual string Name [get]
virtual string FullName [get]
virtual int ExpToNext [get]
virtual bool UseExpMod [get]
virtual int CostTrain [get]
virtual int CostLearn [get]
virtual bool ShowXP [get]
virtual bool ShowMsgOnValueChanged [get]
virtual bool ShowValue [get]
virtual bool ShowPotential [get]
virtual bool UsePotential [get]
virtual bool PotentialAsStock [get]
virtual bool ShowRelativeAttribute [get]
virtual bool ShowBonuses [get]
virtual string ShortName [get]
bool IsGlobalElement [get]
bool IsFactionWideElement [get]
bool IsPartyWideElement [get]
virtual bool ShowEncNumber [get]
bool IsTrait [get]
bool IsFoodTrait [get]
bool IsFoodTraitMain [get]
bool IsMainAttribute [get]
Act act [get]
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Detailed Description
Definition at line 4 of file TaskDump.cs.
Member Function Documentation
CanManualCancel()
override bool TaskDump.CanManualCancel () inline virtual
Reimplemented from AIAct.
Definition at line 25 of file TaskDump.cs.
    {
        return true;
    }
IsValidContainer()
bool TaskDump.IsValidContainer (Thing c) inline
Definition at line 136 of file TaskDump.cs.
    {
        if ((!c.ExistsOnMap && !c.IsInstalled) || !c.CanSearchContents)
        {
            return false;
        }
        if (c.trait is TraitShippingChest)
        {
            c = EClass.game.cards.container_shipping;
        }
        if (c.GetWindowSaveData() == null || c.GetWindowSaveData().autodump == AutodumpFlag.none)
        {
            return false;
        }
        if (ListThingsToPut(c).Count == 0)
        {
            return false;
        }
        return true;
    }
References Thing.CanSearchContents, Game.cards, CardManager.container_shipping, Card.ExistsOnMap, EClass.game, Card.GetWindowSaveData(), Card.IsInstalled, and Card.trait.
Referenced by Run().
ListThingsToPut()
List< Thing > TaskDump.ListThingsToPut (Thing c) inline
Definition at line 157 of file TaskDump.cs.
    {
        List<Thing> list = new List<Thing>();
        if (c.trait is TraitShippingChest)
        {
            c = EClass.game.cards.container_shipping;
        }
        Window.SaveData data = c.GetWindowSaveData();
        if (data == null)
        {
            return list;
        }
        switch (data.autodump)
        {
        case AutodumpFlag.distribution:
            EClass.pc.things.Foreach(delegate(Thing t)
            {
                if (!ExcludeDump(t))
                {
                    if (data.advDistribution)
                    {
                        foreach (int cat in data.cats)
{
                            if (t.category.uid == cat)
{
                                list.Add(t);
                                break;
                            }
                        }
                        return;
                    }
                    ContainerFlag containerFlag = t.category.GetRoot().id.ToEnum<ContainerFlag>();
                    if (containerFlag == ContainerFlag.none)
                    {
                        containerFlag = ContainerFlag.other;
                    }
                    if (!data.flag.HasFlag(containerFlag))
                    {
                        list.Add(t);
                    }
                }
            });
            break;
        case AutodumpFlag.existing:
            foreach (Thing ct in c.things)
            {
                EClass.pc.things.Foreach(delegate(Thing t)
                {
                    if (!ExcludeDump(t) && t.CanStackTo(ct))
                    {
                        list.Add(t);
                    }
                });
            }
            break;
        case AutodumpFlag.sameCategory:
        {
            if (c.things.Count == 0)
            {
                break;
            }
            HashSet<SourceCategory.Row> cats = new HashSet<SourceCategory.Row>();
            foreach (Thing thing in c.things)
            {
                cats.Add(thing.category);
            }
            EClass.pc.things.Foreach(delegate(Thing t)
            {
                if (!ExcludeDump(t) && cats.Contains(t.category))
                {
                    list.Add(t);
                }
            });
            break;
        }
        }
        return list;
        bool ExcludeDump(Thing t)
        {
            if (t.isEquipped || t.c_isImportant || !t.trait.CanBeDropped || t.IsHotItem || t.trait is TraitToolBelt || t.trait is TraitAbility)
            {
                return true;
            }
            if (t.IsContainer && t.things.Count > 0)
            {
                return true;
            }
            if (data.noRotten && t.IsDecayed)
            {
                return true;
            }
            if (data.onlyRottable && t.trait.Decay == 0)
            {
                return true;
            }
            if (data.userFilter && !data.IsFilterPass(t.GetName(NameStyle.Full, 1)))
            {
                return true;
            }
            if (!(t.parent is Card card))
            {
                return false;
            }
            return card.GetWindowSaveData()?.excludeDump ?? false;
        }
    }
References Thing.CanStackTo(), Game.cards, Card.category, CardManager.container_shipping, ThingContainer.Foreach(), EClass.game, Card.GetWindowSaveData(), EClass.pc, Card.things, and Card.trait.
Referenced by Run().
OnCancelOrSuccess()
override void TaskDump.OnCancelOrSuccess () inline virtual
Reimplemented from AIAct.
Definition at line 130 of file TaskDump.cs.
    {
        Msg.Say("dump_end");
        SE.Play("auto_dump");
    }
References Msg.Say().
Run()
override IEnumerable< Status > TaskDump.Run () inline virtual
Reimplemented from AIAct.
Definition at line 30 of file TaskDump.cs.
    {
        List<Thing> containers = new List<Thing>();
        EClass._map.things.ForEach(delegate(Thing t)
        {
            if (IsValidContainer(t))
            {
                containers.Add(t);
            }
        });
        while (containers.Count > 0)
        {
            bool flag = true;
            int num = SortVal(containers.First());
            foreach (Thing item in containers)
            {
                if (SortVal(item) != num)
                {
                    flag = false;
                    break;
                }
            }
            if (flag)
            {
                containers.Sort((Thing a, Thing b) => EClass.pc.Dist(b) - EClass.pc.Dist(a));
            }
            else
            {
                containers.Sort((Thing a, Thing b) => SortVal(a) - SortVal(b));
            }
            Thing c = containers.LastItem();
            containers.RemoveAt(containers.Count - 1);
            if (!IsValidContainer(c))
            {
                continue;
            }
            EClass.ui.CloseLayers();
            Point pos = c.pos.Copy();
            if (c.IsMultisize)
            {
                int minDist = 999;
                c.ForeachPoint(delegate(Point p, bool isCenter)
                {
                    if (p.IsValid && p.IsInBounds)
                    {
                        PathProgress pathProgress = PathManager.Instance.RequestPathImmediate(EClass.pc.pos, p, EClass.pc, PathManager.MoveType.Default, -1, 1);
                        if (pathProgress.HasPath && pathProgress.nodes.Count < minDist)
{
                            minDist = pathProgress.nodes.Count;
                            pos = p.Copy();
                        }
                    }
                });
            }
            yield return DoGoto(pos, 1, ignoreConnection: false, () => Status.Running);
            if (!IsValidContainer(c))
            {
                continue;
            }
            if (!c.ExistsOnMap)
            {
                Msg.Say("dump_noExist", c);
                continue;
            }
            if (EClass.pc.Dist(c) > 1)
            {
                Msg.Say("dump_tooFar", c);
                continue;
            }
            List<Thing> list = ListThingsToPut(c);
            int num2 = 0;
            if (c.trait is TraitShippingChest)
            {
                c = EClass.game.cards.container_shipping;
            }
            foreach (Thing item2 in list)
            {
                if (!c.things.IsFull(item2) && !item2.isDestroyed)
                {
                    item2.PlaySoundDrop(spatial: false);
                    if (c.parent is Card)
                    {
                        (c.parent as Card).SetDirtyWeight();
                    }
                    Msg.Say("dump_item", item2, c);
                    c.AddCard(item2);
                    num2++;
                }
            }
            if (num2 > 0)
            {
                Msg.Say("dump_dumped", num2.ToString() ?? "", c.Name);
            }
        }
        static int SortVal(Thing t)
        {
            return t.GetWindowSaveData()?.priority ?? 0;
        }
    }
References EClass._map, Game.cards, CardManager.container_shipping, Point.Copy(), Card.Dist(), AIAct.DoGoto(), Card.ForeachPoint(), EClass.game, Card.isDestroyed, Point.IsInBounds, Card.IsMultisize, Point.IsValid, IsValidContainer(), ListThingsToPut(), EClass.pc, Card.PlaySoundDrop(), Card.pos, Msg.Say(), Element.SortVal(), Map.things, and EClass.ui.
TryPerform()
static void TaskDump.TryPerform () inline static
Definition at line 6 of file TaskDump.cs.
    {
        if (EClass.ui.AllowInventoryInteractions)
        {
            if (!EClass._zone.IsPCFaction && !(EClass._zone is Zone_Tent))
            {
                Msg.Say("dump_invalid");
            }
            else if (!EClass.pc.HasNoGoal)
            {
                SE.Beep();
            }
            else
            {
                EClass.pc.SetAIImmediate(new TaskDump());
            }
        }
    }
References EClass._zone, Chara.HasNoGoal, Zone.IsPCFaction, EClass.pc, Msg.Say(), Chara.SetAIImmediate(), and EClass.ui.
Referenced by AM_Adv._OnUpdateInput(), LayerInventory.OnUpdateInput(), and HotItemActionAudoDump.Perform().
The documentation for this class was generated from the following file:
Elin/TaskDump.cs