Elin Decompiled Documentation: CustomCharaContent Class Reference
CustomCharaContent Class Reference
Public Types
enum SpawnType { Common , Adventurer , Merchant , Unique }
Public Member Functions
void OnCharaCreated (Chara chara)
override void OnGameLoad (GameIOContext context)
override string ToString ()
Public Member Functions inherited from CustomContent
virtual void OnGameLoad (GameIOContext context)
virtual void OnGameSave (GameIOContext context)
override string ToString ()
Static Public Member Functions
static CustomCharaContent CreateFromRow (SourceChara.Row r, ModPackage owner=null)
static SpawnType GetSpawnTypeFromTrait (string trait)
Static Public Member Functions inherited from CustomSourceContent
static string string string[] kv GetParams (string tag)
Static Public Member Functions inherited from EClass
static int rndSeed (int a, int seed)
static int rnd (long a)
static int rnd (int a)
static int curve (long _a, int start, int step, int rate=75)
static int sqrt (int a)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Public Attributes
List< string > equipments = new List<string>()
Dictionary< string, int > mapInt = new Dictionary<string, int>()
Dictionary< string, string > mapStr = new Dictionary<string, string>()
SpawnType spawnType
List< string > spawnZones = new List<string>()
List< string > stocks = new List<string>()
List< string > things = new List<string>()
Properties
override string SourceType [get]
bool IsAdventurer [get]
Properties inherited from CustomSourceContent
virtual string SourceType [get]
string SourceId [get, set]
Properties inherited from CustomContent
string ContentId [get, protected set]
EMod Owner [get, protected set]
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Static Private Attributes
static readonly Dictionary< string, SpawnType > _cachedSpawnTypes = new Dictionary<string, SpawnType>()
Additional Inherited Members
Static Public Attributes inherited from CustomSourceContent
static string action
static string string spec
Static Public Attributes inherited from EClass
static Core core
Detailed Description
Definition at line 9 of file CustomCharaContent.cs.
Member Enumeration Documentation
SpawnType
enum CustomCharaContent.SpawnType
Enumerator
Common
Adventurer
Merchant
Unique
Definition at line 11 of file CustomCharaContent.cs.
    {
        Common,
        Adventurer,
        Merchant,
        Unique
    }
Member Function Documentation
CreateFromRow()
static CustomCharaContent CustomCharaContent.CreateFromRow (SourceChara::Row r, ModPackage owner = null) inline static
Definition at line 39 of file CustomCharaContent.cs.
    {
        string trait = r.trait.TryGet(0, returnNull: true) ?? "Chara";
        if (owner == null)
        {
            owner = ModUtil.FindSourceRowPackage(r);
        }
        CustomCharaContent customCharaContent = new CustomCharaContent
        {
            ContentId = "Chara/" + r.id,
            SourceId = r.id,
            spawnType = GetSpawnTypeFromTrait(trait),
            Owner = owner
        };
        string[] tag = r.tag;
        for (int i = 0; i < tag.Length; i++)
        {
            var (text, text2, array) = CustomSourceContent.GetParams(tag[i]);
            switch (text)
            {
            case "addZone":
            case "addAdvZone":
                if (!text2.IsEmpty())
                {
                    customCharaContent.spawnZones.Add(text2);
                }
                break;
            case "addEq":
            case "addAdvEq":
            case "addEquipment":
                if (!text2.IsEmpty())
                {
                    customCharaContent.equipments.Add(text2);
                }
                break;
            case "addThing":
                if (!text2.IsEmpty())
                {
                    customCharaContent.things.Add(text2);
                }
                break;
            case "addStock":
            {
                string text3 = text2.IsEmpty(r.id);
                if (!ModUtil.HasContent("MerchantStock/" + text3))
                {
                    CustomMerchantStock customMerchantStock = CustomMerchantStock.CreateFromId(text3, owner);
                    if (customMerchantStock == null)
                    {
                        break;
                    }
                    ModUtil.AddContent(customMerchantStock);
                }
                if (!customCharaContent.stocks.Contains(text3))
                {
                    customCharaContent.stocks.Add(text3);
                    customCharaContent.mapStr["merchant_override"] = string.Join('|', customCharaContent.stocks);
                }
                break;
            }
            case "addDrama":
                if (!text2.IsEmpty())
                {
                    customCharaContent.mapStr["drama_override"] = text2;
                }
                break;
            case "addBio":
            case "addBiography":
            {
                string text4 = text2.IsEmpty(r.id);
                customCharaContent.mapStr["biography_override"] = text4;
                if (!ModUtil.HasContent("Biography/" + text4))
                {
                    CustomBiographyContent customBiographyContent = CustomBiographyContent.CreateFromId(text4, owner);
                    if (customBiographyContent != null)
                    {
                        ModUtil.AddContent(customBiographyContent);
                    }
                }
                break;
            }
            case "addFlag":
            case "addInt":
                customCharaContent.mapInt[array[0]] = array.TryGet(1, returnNull: true)?.ToInt() ?? 1;
                break;
            case "addFlagValue":
            case "addStr":
                if (!array.TryGet(1, returnNull: true).IsEmpty())
                {
                    customCharaContent.mapStr[array[0]] = array[1];
                }
                break;
            }
        }
        return customCharaContent;
    }
References CustomContent.ContentId, CustomBiographyContent.CreateFromId(), CustomMerchantStock.CreateFromId(), equipments, CustomSourceContent.GetParams(), GetSpawnTypeFromTrait(), mapInt, mapStr, CustomContent.Owner, CustomSourceContent.SourceId, spawnType, spawnZones, stocks, and things.
Referenced by ModPackage.GenerateCustomContentProfiles().
GetSpawnTypeFromTrait()
static SpawnType CustomCharaContent.GetSpawnTypeFromTrait (string trait) inline static
Definition at line 136 of file CustomCharaContent.cs.
    {
        if (_cachedSpawnTypes.TryGetValue(trait, out var value))
        {
            return value;
        }
        Trait trait2 = ClassCache.Create<Trait>("Trait" + trait, "Elin");
        if (!(trait2 is TraitChara traitChara))
        {
            goto IL_005f;
        }
        SpawnType spawnType;
        if (traitChara.AdvType == TraitChara.Adv_Type.None)
        {
            if (!(trait2 is TraitMerchant))
            {
                if (!(trait2 is TraitUniqueChara))
                {
                    goto IL_005f;
                }
                spawnType = SpawnType.Unique;
            }
            else
            {
                spawnType = SpawnType.Merchant;
            }
        }
        else
        {
            spawnType = SpawnType.Adventurer;
        }
        goto IL_0061;
        IL_0061:
        return _cachedSpawnTypes[trait] = spawnType;
        IL_005f:
        spawnType = SpawnType.Common;
        goto IL_0061;
    }
References _cachedSpawnTypes, and spawnType.
Referenced by CreateFromRow().
OnCharaCreated()
void CustomCharaContent.OnCharaCreated (Chara chara) inline
Definition at line 175 of file CustomCharaContent.cs.
    {
        if (chara.GetBool("custom_content") || chara.id != base.SourceId)
        {
            return;
        }
        chara.SetBool("custom_content", enable: true);
        chara.SetStr("custom_content_id", base.ContentId);
        chara.SetStr("custom_content_package", base.Owner.id);
        string key2;
        foreach (KeyValuePair<string, string> item in mapStr)
        {
            item.Deconstruct(out var key, out key2);
            string id2 = key;
            string value = key2;
            chara.SetStr(id2, value);
        }
        foreach (KeyValuePair<string, int> item2 in mapInt)
        {
            item2.Deconstruct(out key2, out var value2);
            string id3 = key2;
            int value3 = value2;
            chara.SetInt(id3, value3);
        }
        if (chara.GetBool("cwl_tags_applied"))
        {
            return;
        }
        if (things.Count > 0 || equipments.Count > 0)
        {
            chara.RemoveThings();
        }
        foreach (string[] item3 in equipments.Select((string t) => t.Split('#')))
        {
            if (!Enum.TryParse<Rarity>(item3.TryGet(1, returnNull: true), out var result))
            {
                result = Rarity.Random;
            }
            if (HasValidContentId(item3[0]))
            {
                chara.EQ_ID(item3[0], -1, result);
            }
        }
        foreach (string[] item4 in things.Select((string t) => t.Split('#')))
        {
            if (!int.TryParse(item4.TryGet(1, returnNull: true), out var result2))
            {
                result2 = 1;
            }
            if (HasValidContentId(item4[0]))
            {
                chara.AddThing(item4[0]).SetNum(result2);
            }
        }
        bool HasValidContentId(string id)
        {
            if (EClass.sources.cards.map.ContainsKey(id))
            {
                return true;
            }
            ModUtil.LogModError("source chara row '" + base.ContentId + "' has invalid addEq/addThing spec '" + id + "'", base.Owner);
            return false;
        }
    }
References SourceManager.cards, equipments, Card.GetBool(), Card.id, item, SourceCard.map, mapInt, mapStr, Card.SetBool(), Card.SetStr(), EClass.sources, and things.
OnGameLoad()
override void CustomCharaContent.OnGameLoad (GameIOContext context) inline virtual
Reimplemented from CustomContent.
Definition at line 240 of file CustomCharaContent.cs.
    {
        if (spawnZones.Count == 0)
        {
            return;
        }
        Debug.Log($"#mod-content loading {this}");
        ILookup<string, Chara> lookup = EClass.game.cards.globalCharas.Values.ToLookup((Chara c) => c.id);
        List<Zone> list = new List<Zone>();
        foreach (string spawnZone in spawnZones)
        {
            Zone zone = ModUtil.FindZoneByFullName(spawnZone);
            if (zone != null)
            {
                list.Add(zone);
                continue;
            }
            ModUtil.LogModError("source chara row '" + base.SourceId + "' has invalid addZone spec '" + spawnZone + "'", base.Owner);
        }
        List<Chara> list2 = lookup[base.SourceId].ToList();
        int count = list2.Count;
        if (list.Count == 0 && count == 0)
        {
            ModUtil.LogModError("source chara row '" + base.SourceId + "' has invalid addZone spec", base.Owner);
            return;
        }
        int num = Math.Max(0, list.Count - count);
        int num2 = count;
        if (num2 <= 1)
        {
            if (num2 != 1)
            {
                goto IL_01cf;
            }
            if (IsAdventurer)
            {
                goto IL_0178;
            }
        }
        else if (IsAdventurer)
        {
            Debug.LogWarning("#mod-content adventurer '" + base.SourceId + "' has spawned more than once");
            return;
        }
        if (num == 0)
        {
            goto IL_0178;
        }
        goto IL_01cf;
        IL_0178:
        Debug.Log("#mod-content skipping existing character '" + base.SourceId + "', " + $"{count} at {string.Join(',', list2.Select((Chara c) => c.currentZone?.ZoneFullName))}");
        return;
        IL_01cf:
        for (int i = 0; i < num; i++)
        {
            Zone z2 = list[i];
            Chara chara = SpawnToZone(z2);
            if (chara == null)
            {
                ModUtil.LogModError("can't spawn character '" + base.SourceId + "'", base.Owner);
                break;
            }
            if (IsAdventurer)
            {
                EClass.game.cards.listAdv.Add(chara);
                break;
            }
        }
        Chara SpawnToZone(Zone z)
        {
            Chara chara2 = CharaGen.Create(base.SourceId);
            if (chara2.id == "chicken")
            {
                return null;
            }
            chara2.SetHomeZone(z);
            chara2.MoveZone(z, ZoneTransition.EnterState.RandomVisit);
            Debug.Log("#mod-content spawned character '" + base.SourceId + "' to " + z.ZoneFullName);
            return chara2;
        }
    }
References $, Game.cards, CharaGen.Create(), Debug, EClass.game, CardManager.globalCharas, Card.id, IsAdventurer, CardManager.listAdv, Chara.MoveZone(), Chara.SetHomeZone(), spawnZones, and Zone.ZoneFullName.
ToString()
override string CustomCharaContent.ToString () inline
Definition at line 322 of file CustomCharaContent.cs.
    {
        StringBuilder stringBuilder = new StringBuilder();
        stringBuilder.AppendLine($"{base.ContentId}/{spawnType}/{base.Owner.id}");
        stringBuilder.AppendLine($" - zones({spawnZones.Count})/{string.Join(';', spawnZones)}");
        if (things.Count > 0)
        {
            stringBuilder.AppendLine($" - things({things.Count})/{string.Join(';', things)}");
        }
        if (equipments.Count > 0)
        {
            stringBuilder.AppendLine($" - equipments({equipments.Count})/{string.Join(';', equipments)}");
        }
        if (stocks.Count > 0)
        {
            stringBuilder.AppendLine(" - stocks/" + string.Join(';', stocks));
        }
        if (mapStr.Count > 0)
        {
            stringBuilder.AppendLine(" - str/" + string.Join(';', mapStr.Select((KeyValuePair<string, string> kv) => kv.Key + "=" + kv.Value)));
        }
        if (mapInt.Count > 0)
        {
            stringBuilder.AppendLine(" - int/" + string.Join(';', mapInt.Select((KeyValuePair<string, int> kv) => $"{kv.Key}={kv.Value}")));
        }
        return stringBuilder.ToString();
    }
References $, equipments, mapInt, mapStr, stocks, and things.
Member Data Documentation
_cachedSpawnTypes
readonly Dictionary<string, SpawnType> CustomCharaContent._cachedSpawnTypes = new Dictionary<string, SpawnType>() static private
Definition at line 19 of file CustomCharaContent.cs.
Referenced by GetSpawnTypeFromTrait().
equipments
List<string> CustomCharaContent.equipments = new List<string>()
Definition at line 21 of file CustomCharaContent.cs.
Referenced by CreateFromRow(), OnCharaCreated(), and ToString().
mapInt
Dictionary<string, int> CustomCharaContent.mapInt = new Dictionary<string, int>()
Definition at line 23 of file CustomCharaContent.cs.
Referenced by CreateFromRow(), OnCharaCreated(), and ToString().
mapStr
Dictionary<string, string> CustomCharaContent.mapStr = new Dictionary<string, string>()
Definition at line 25 of file CustomCharaContent.cs.
Referenced by CreateFromRow(), OnCharaCreated(), and ToString().
spawnType
SpawnType CustomCharaContent.spawnType
Definition at line 27 of file CustomCharaContent.cs.
Referenced by CreateFromRow(), and GetSpawnTypeFromTrait().
spawnZones
List<string> CustomCharaContent.spawnZones = new List<string>()
Definition at line 29 of file CustomCharaContent.cs.
Referenced by CreateFromRow(), and OnGameLoad().
stocks
List<string> CustomCharaContent.stocks = new List<string>()
Definition at line 31 of file CustomCharaContent.cs.
Referenced by CreateFromRow(), and ToString().
things
List<string> CustomCharaContent.things = new List<string>()
Definition at line 33 of file CustomCharaContent.cs.
Referenced by CreateFromRow(), OnCharaCreated(), and ToString().
Property Documentation
IsAdventurer
bool CustomCharaContent.IsAdventurer get
Definition at line 37 of file CustomCharaContent.cs.
Referenced by OnGameLoad().
SourceType
override string CustomCharaContent.SourceType get
Definition at line 35 of file CustomCharaContent.cs.
The documentation for this class was generated from the following file:
Elin/CustomCharaContent.cs