Elin Decompiled Documentation: CoreConfig.BackerContentConfig Class Reference
CoreConfig.BackerContentConfig Class Reference
Public Member Functions
bool Show (int id)
bool Show (SourceBacker.Row row)
bool Show (string s)
Public Attributes
int filter
Properties
bool FilterAll [get]
bool FilterLang [get]
bool FilterNone [get]
Private Member Functions
bool IsJapanese (string text)
Detailed Description
Definition at line 434 of file CoreConfig.cs.
Member Function Documentation
IsJapanese()
bool CoreConfig.BackerContentConfig.IsJapanese (string text) inline private
Definition at line 491 of file CoreConfig.cs.
        {
            return Regex.IsMatch(text, "[\\p{IsHiragana}\\p{IsKatakana}\\p{IsCJKUnifiedIdeographs}]+");
        }
Referenced by CoreConfig.BackerContentConfig.Show().
Show() [1/3]
bool CoreConfig.BackerContentConfig.Show (int id) inline
Definition at line 444 of file CoreConfig.cs.
        {
            return Show(EClass.sources.backers.map.TryGetValue(id));
        }
References SourceManager.backers, CoreConfig.BackerContentConfig.Show(), and EClass.sources.
Referenced by Thing.GetName(), Chara.GetName(), Cell.GetObjName(), TaskHarvest.OnCreateProgress(), and CoreConfig.BackerContentConfig.Show().
Show() [2/3]
bool CoreConfig.BackerContentConfig.Show (SourceBacker::Row row) inline
Definition at line 449 of file CoreConfig.cs.
        {
            if (row == null)
            {
                return false;
            }
            if (FilterNone)
            {
                return true;
            }
            if (FilterAll)
            {
                return false;
            }
            bool flag = row.lang == "JP" || row.lang == "CN";
            string langCode = Lang.langCode;
            if (langCode == "JP" || langCode == "CN")
            {
                return flag;
            }
            return !flag;
        }
References CoreConfig.BackerContentConfig.FilterAll, CoreConfig.BackerContentConfig.FilterNone, and Lang.langCode.
Show() [3/3]
bool CoreConfig.BackerContentConfig.Show (string s) inline
Definition at line 472 of file CoreConfig.cs.
        {
            if (FilterNone)
            {
                return true;
            }
            if (FilterAll)
            {
                return false;
            }
            bool flag = IsJapanese(s);
            string langCode = Lang.langCode;
            if (langCode == "JP" || langCode == "CN")
            {
                return flag;
            }
            return !flag;
        }
References CoreConfig.BackerContentConfig.FilterAll, CoreConfig.BackerContentConfig.FilterNone, CoreConfig.BackerContentConfig.IsJapanese(), and Lang.langCode.
Member Data Documentation
filter
int CoreConfig.BackerContentConfig.filter
Definition at line 436 of file CoreConfig.cs.
Referenced by TraitMoongate.UseMoongate().
Property Documentation
FilterAll
bool CoreConfig.BackerContentConfig.FilterAll get
Definition at line 438 of file CoreConfig.cs.
Referenced by TraitDaggerGrave.OnUse(), and CoreConfig.BackerContentConfig.Show().
FilterLang
bool CoreConfig.BackerContentConfig.FilterLang get
Definition at line 440 of file CoreConfig.cs.
FilterNone
bool CoreConfig.BackerContentConfig.FilterNone get
Definition at line 442 of file CoreConfig.cs.
Referenced by CoreConfig.BackerContentConfig.Show().
The documentation for this class was generated from the following file:
Elin/CoreConfig.cs