Elin Decompiled Documentation: UICardInfo Class Reference
UICardInfo Class Reference
Public Member Functions
void SetRenderer (IRenderer _renderer, RenderParam p)
void UpdateImage ()
void Build ()
void SetElement (Element e)
void SetThing (Thing t)
void UpdateRecipe (Recipe r)
void SetRecipe (Recipe r)
void SetBlock (Cell cell)
void SetFloor (Cell cell)
void SetLiquid (Cell cell)
void SetObj (Cell cell)
Public Attributes
UINote note
IRenderer renderer
RenderParam param
Private Member Functions
void Update ()
Additional Inherited Members
Static Public Member Functions inherited from EMono
static int rnd (int a)
Static Public Attributes inherited from EMono
static Core core
Properties inherited from EMono
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SoundManager Sound [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static CoreDebug debug [get]
Detailed Description
Definition at line 1 of file UICardInfo.cs.
Member Function Documentation
Build()
void UICardInfo.Build () inline
Definition at line 23 of file UICardInfo.cs.
    {
        note.Build();
        UpdateImage();
    }
References UINote.Build(), note, and UpdateImage().
Referenced by SetBlock(), SetFloor(), SetLiquid(), SetObj(), SetRecipe(), and SetThing().
SetBlock()
void UICardInfo.SetBlock (Cell cell) inline
Definition at line 64 of file UICardInfo.cs.
    {
        string blockName = cell.GetBlockName();
        RenderParam renderParam = cell.sourceBlock.GetRenderParam(cell.matBlock, 0);
        SetRenderer(cell.sourceBlock.renderData, renderParam);
        note.AddHeaderCard(blockName).image2.SetActive(enable: false);
        note.AddText("isMadeOf".lang(cell.matBlock.GetText()));
        Build();
    }
References UINote.AddHeaderCard(), UINote.AddText(), Build(), Cell.GetBlockName(), UIItem.image2, Cell.matBlock, note, SetRenderer(), and Cell.sourceBlock.
Referenced by LayerInfo.SetBlock().
SetElement()
void UICardInfo.SetElement (Element e) inline
Definition at line 34 of file UICardInfo.cs.
    {
        e.WriteNote(note);
    }
References note, and Element.WriteNote().
Referenced by LayerInfo.SetElement().
SetFloor()
void UICardInfo.SetFloor (Cell cell) inline
Definition at line 74 of file UICardInfo.cs.
    {
        string floorName = cell.GetFloorName();
        RenderParam renderParam = cell.sourceFloor.GetRenderParam(cell.matFloor, 0);
        SetRenderer(cell.sourceFloor.renderData, renderParam);
        note.AddHeaderCard(floorName).image2.SetActive(enable: false);
        note.AddText("isMadeOf".lang(cell.matFloor.GetText()));
        Build();
    }
References UINote.AddHeaderCard(), UINote.AddText(), Build(), Cell.GetFloorName(), UIItem.image2, Cell.matFloor, note, SetRenderer(), and Cell.sourceFloor.
Referenced by LayerInfo.SetFloor().
SetLiquid()
void UICardInfo.SetLiquid (Cell cell) inline
Definition at line 84 of file UICardInfo.cs.
    {
        string liquidName = cell.GetLiquidName();
        RenderParam renderParam = cell.sourceEffect.GetRenderParam(cell.matFloor, 0);
        SetRenderer(cell.sourceEffect.renderData, renderParam);
        note.AddHeaderCard(liquidName).image2.SetActive(enable: false);
        note.AddText("isMadeOf".lang(cell.sourceEffect.GetText()));
        Build();
    }
References UINote.AddHeaderCard(), UINote.AddText(), Build(), Cell.GetLiquidName(), UIItem.image2, Cell.matFloor, note, SetRenderer(), and Cell.sourceEffect.
Referenced by LayerInfo.SetLiquid().
SetObj()
void UICardInfo.SetObj (Cell cell) inline
Definition at line 94 of file UICardInfo.cs.
    {
        SourceObj.Row sourceObj = cell.sourceObj;
        RenderParam renderParam = cell.sourceObj.GetRenderParam(cell.matBlock, 0);
        SetRenderer(sourceObj.renderData, renderParam);
        note.AddHeaderCard(base.name).image2.SetActive(enable: false);
        note.AddText("isMadeOf".lang(sourceObj.DefaultMaterial.GetText()));
        Build();
    }
References UINote.AddHeaderCard(), UINote.AddText(), Build(), RenderRow.DefaultMaterial, UIItem.image2, Cell.matBlock, note, RenderRow.renderData, SetRenderer(), and Cell.sourceObj.
Referenced by LayerInfo.SetObj().
SetRecipe()
void UICardInfo.SetRecipe (Recipe r) inline
Definition at line 50 of file UICardInfo.cs.
    {
        UpdateRecipe(r);
        note.Clear();
        note.AddHeaderCard(r.Name);
        note.AddText(r.source.GetDetail());
        note.Space();
        note.AddHeaderTopic("buildType".lang() + ": " + r.tileType.LangPlaceType.lang());
        note.AddText((r.tileType.LangPlaceType + "_hint").lang());
        note.Space();
        note.AddHeaderTopic("reqMat".lang());
        Build();
    }
References UINote.AddHeaderCard(), UINote.AddHeaderTopic(), UINote.AddText(), Build(), UINote.Clear(), RecipeSource.GetDetail(), TileType.LangPlaceType, Recipe.Name, note, Recipe.source, UINote.Space(), Recipe.tileType, and UpdateRecipe().
SetRenderer()
void UICardInfo.SetRenderer (IRenderer _renderer, RenderParam p) inline
Definition at line 9 of file UICardInfo.cs.
    {
        renderer = _renderer;
        param = p;
    }
References param, and renderer.
Referenced by SetBlock(), SetFloor(), SetLiquid(), SetObj(), and UpdateRecipe().
SetThing()
void UICardInfo.SetThing (Thing t) inline
Definition at line 39 of file UICardInfo.cs.
    {
        t.WriteNote(note, null, IInspect.NoteMode.Info);
        Build();
    }
References Build(), note, and Thing.WriteNote().
Referenced by LayerInfo.SetThing().
Update()
void UICardInfo.Update () inline private
Definition at line 29 of file UICardInfo.cs.
    {
        UpdateImage();
    }
References UpdateImage().
UpdateImage()
void UICardInfo.UpdateImage () inline
Definition at line 15 of file UICardInfo.cs.
    {
        if (EMono.core.IsGameStarted && renderer != null)
        {
            renderer.RenderToRenderCam(param);
        }
    }
References EMono.core, Core.IsGameStarted, param, renderer, and IRenderer.RenderToRenderCam().
Referenced by Build(), and Update().
UpdateRecipe()
void UICardInfo.UpdateRecipe (Recipe r) inline
Definition at line 45 of file UICardInfo.cs.
    {
        SetRenderer(r.GetRenderer(), r.renderRow.GetRenderParam(r.GetColorMaterial(), 0));
    }
References Recipe.GetColorMaterial(), Recipe.GetRenderer(), RenderRow.GetRenderParam(), Recipe.renderRow, and SetRenderer().
Referenced by SetRecipe().
Member Data Documentation
note
UINote UICardInfo.note
Definition at line 3 of file UICardInfo.cs.
Referenced by Build(), SetBlock(), SetElement(), SetFloor(), SetLiquid(), SetObj(), SetRecipe(), and SetThing().
param
RenderParam UICardInfo.param
Definition at line 7 of file UICardInfo.cs.
Referenced by SetRenderer(), and UpdateImage().
renderer
IRenderer UICardInfo.renderer
Definition at line 5 of file UICardInfo.cs.
Referenced by SetRenderer(), and UpdateImage().
The documentation for this class was generated from the following file:
Elin/UICardInfo.cs