Elin Decompiled Documentation: DNA Class Reference
DNA Class Reference
Public Types
enum Type { Inferior , Default = 3 , Superior = 5 , Brain = 8 }
Public Member Functions
void Apply (Chara c)
void Apply (Chara c, bool reverse)
bool CanRemove ()
void GenerateWithGene (DNA.Type _type, Card gene, Chara model=null)
void Generate (DNA.Type _type, Chara model=null)
void CalcCost ()
string GetMaterialId (DNA.Type type)
int GetDurationHour ()
DNA.Type GetRandomType ()
string GetText ()
void WriteNote (UINote n)
Element GetInvalidFeat (Chara c)
Element GetInvalidAction (Chara c)
Static Public Member Functions
static Thing GenerateGene (Chara c, DNA.Type? type=null)
static Thing GenerateGene (CardRow r, DNA.Type? type=null, int lv=-1, int seed=-1)
static DNA.Type GetType (string idMat)
Static Public Member Functions inherited from EClass
static int rnd (int a)
static int curve (int a, int start, int step, int rate=75)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Public Attributes
string id
int[] ints = new int[4]
List< int > vals = new List<int>()
Properties
DNA.Type type [get, set]
int cost [get, set]
int lv [get, set]
int seed [get, set]
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Private Member Functions
void< Generate > g__AddVal (int id, int v, bool allowStack, Func< int, int > funcCost, ref DNA.<>c__DisplayClass22_0 A_5)
void< Generate > g__AddSkill (ref DNA.<>c__DisplayClass22_0 A_1)
void< Generate > g__AddAttribute (ref DNA.<>c__DisplayClass22_0 A_1)
void< Generate > g__AddFeat (ref DNA.<>c__DisplayClass22_0 A_1)
void< Generate > g__AddBody (ref DNA.<>c__DisplayClass22_0 A_1)
void< Generate > g__AddAction (ref DNA.<>c__DisplayClass22_0 A_1)
void< Generate > g__AddRandom (int n, ref DNA.<>c__DisplayClass22_0 A_2)
void< Generate > g__AddSpecial (ref DNA.<>c__DisplayClass22_0 A_1)
Additional Inherited Members
Static Public Attributes inherited from EClass
static Core core
Detailed Description
Definition at line 7 of file DNA.cs.
Member Enumeration Documentation
Type
enum DNA.Type
Enumerator
Inferior
Default
Superior
Brain
Definition at line 623 of file DNA.cs.
    {
        Inferior,
        Default = 3,
        Superior = 5,
        Brain = 8
    }
Member Function Documentation
Apply() [1/2]
void DNA.Apply (Chara c) inline
Definition at line 87 of file DNA.cs.
    {
        if (c.c_genes == null)
        {
            c.c_genes = new CharaGenes();
        }
        CharaGenes c_genes = c.c_genes;
        if (this.type == DNA.Type.Inferior)
        {
            c.c_genes.inferior++;
            return;
        }
        c.feat -= this.cost;
        this.Apply(c, false);
        c_genes.items.Add(this);
    }
References Apply(), Card.c_genes, cost, CharaGenes.inferior, CharaGenes.items, and type.
Referenced by Apply(), and CharaGenes.Remove().
Apply() [2/2]
void DNA.Apply (Chara c, bool reverse) inline
Definition at line 104 of file DNA.cs.
    {
        if (this.type == DNA.Type.Brain)
        {
            c._tactics = null;
            return;
        }
        for (int i = 0; i < this.vals.Count; i += 2)
        {
            int num = this.vals[i];
            int num2 = this.vals[i + 1];
            SourceElement.Row row = EClass.sources.elements.map[num];
            string category = row.category;
            if (!(category == "slot"))
            {
                if (!(category == "feat"))
                {
                    if (!(category == "ability"))
                    {
                        if (!reverse && c.elements.ValueWithoutLink(row.id) == 0)
{
                            c.elements.Learn(row.id, num2);
                        }
                        else
{
                            c.elements.ModBase(num, reverse ? (-num2) : num2);
                        }
                    }
                    else if (reverse)
                    {
                        c.ability.Remove(num * ((num2 < 0) ? -1 : 1));
                    }
                    else
                    {
                        c.ability.Add(num, Mathf.Abs(num2), num2 < 0);
                    }
                }
                else
                {
                    c.SetFeat(num, c.elements.ValueWithoutLink(num) + (reverse ? -1 : 1), !reverse);
                }
            }
            else
            {
                if (reverse)
                {
                    c.body.RemoveBodyPart(row.id);
                }
                else
                {
                    c.body.AddBodyPart(row.id, null);
                }
                c.body.RefreshBodyParts();
            }
        }
    }
References Chara.ability, CharaAbility.Add(), CharaBody.AddBodyPart(), Chara.body, SourceElement.Row.category, Card.elements, SourceManager.elements, SourceElement.Row.id, ElementContainer.Learn(), ElementContainer.ModBase(), CharaBody.RefreshBodyParts(), CharaAbility.Remove(), CharaBody.RemoveBodyPart(), Chara.SetFeat(), EClass.sources, type, vals, and ElementContainer.ValueWithoutLink().
CalcCost()
void DNA.CalcCost () inline
Definition at line 259 of file DNA.cs.
    {
        for (int i = 0; i < this.vals.Count; i += 2)
        {
            Element.Create(this.vals[i], this.vals[i + 1]);
        }
    }
References Element.Create(), and vals.
Referenced by Generate().
CanRemove()
bool DNA.CanRemove () inline
Definition at line 161 of file DNA.cs.
    {
        for (int i = 0; i < this.vals.Count; i += 2)
        {
            if (this.vals[i] == 1415)
            {
                return false;
            }
        }
        return true;
    }
References vals.
Referenced by WindowCharaMini.Refresh(), and WriteNote().
g__AddAction()
void< Generate > DNA.g__AddAction (ref DNA::<>c__DisplayClass22_0 A_1) inline private
Definition at line 552 of file DNA.cs.
    {
        if (A_1.model.ability.list.items.Count == 0)
        {
            return;
        }
        ActList.Item a = A_1.model.ability.list.items.RandomItem<ActList.Item>();
        if (a.act.source.category != "ability")
        {
            return;
        }
        this.<Generate>g__AddVal|22_0(a.act.source.id, a.chance * (a.pt ? -1 : 1), false, (int v) => 8 + a.act.source.cost[0] / 10 * 2, ref A_1);
        int action = A_1.action;
        A_1.action = action + 1;
    }
References ActList.Item.act, ActList.Item.chance, g__AddVal(), Generate(), ActList.Item.pt, and Element.source.
Referenced by g__AddSpecial().
g__AddAttribute()
void< Generate > DNA.g__AddAttribute (ref DNA::<>c__DisplayClass22_0 A_1) inline private
Definition at line 506 of file DNA.cs.
    {
        Element element = A_1.listAttb[EClass.rnd(3)];
        this.<Generate>g__AddVal|22_0(element.id, EClass.rndHalf(element.ValueWithoutLink / 2), true, (int v) => v / 5 + 1, ref A_1);
    }
References g__AddVal(), Generate(), Element.id, EClass.rnd(), EClass.rndHalf(), and Element.ValueWithoutLink.
Referenced by g__AddRandom(), and g__AddSpecial().
g__AddBody()
void< Generate > DNA.g__AddBody (ref DNA::<>c__DisplayClass22_0 A_1) inline private
Definition at line 526 of file DNA.cs.
    {
        if (A_1.body != 0)
        {
            return;
        }
        BodySlot bodySlot = null;
        for (int i = 0; i < 100; i++)
        {
            BodySlot bodySlot2 = A_1.model.body.slots.RandomItem<BodySlot>();
            if (bodySlot2 != null && bodySlot2.elementId != 40)
            {
                bodySlot = bodySlot2;
                break;
            }
        }
        if (bodySlot == null)
        {
            return;
        }
        this.<Generate>g__AddVal|22_0(bodySlot.elementId, 1, false, (int v) => 20, ref A_1);
        int body = A_1.body;
        A_1.body = body + 1;
    }
References BodySlot.elementId, g__AddVal(), and Generate().
Referenced by g__AddSpecial().
g__AddFeat()
void< Generate > DNA.g__AddFeat (ref DNA::<>c__DisplayClass22_0 A_1) inline private
Definition at line 513 of file DNA.cs.
    {
        if (A_1.listFeat.Count == 0)
        {
            return;
        }
        int feat = A_1.feat;
        A_1.feat = feat + 1;
        Element e = A_1.listFeat.RandomItem<Element>();
        this.<Generate>g__AddVal|22_0(e.id, 1, false, (int v) => e.source.cost[0] * 5, ref A_1);
    }
References g__AddVal(), Generate(), Element.id, and Element.source.
Referenced by g__AddSpecial().
g__AddRandom()
void< Generate > DNA.g__AddRandom (int n, ref DNA::<>c__DisplayClass22_0 A_2) inline private
Definition at line 569 of file DNA.cs.
    {
        for (int i = 0; i < n; i++)
        {
            if (EClass.debug.enable && EClass.rnd(2) == 0)
            {
                this.<Generate>g__AddSpecial|22_7(ref A_2);
            }
            else if (EClass.rnd(2) == 0)
            {
                this.<Generate>g__AddSkill|22_1(ref A_2);
            }
            else
            {
                this.<Generate>g__AddAttribute|22_2(ref A_2);
            }
        }
    }
References EClass.debug, CoreDebug.enable, g__AddAttribute(), g__AddSkill(), g__AddSpecial(), Generate(), and EClass.rnd().
Referenced by Generate().
g__AddSkill()
void< Generate > DNA.g__AddSkill (ref DNA::<>c__DisplayClass22_0 A_1) inline private
Definition at line 499 of file DNA.cs.
    {
        Element element = A_1.listSkill[Mathf.Clamp(EClass.rnd(6), 0, A_1.listSkill.Count - 1)];
        this.<Generate>g__AddVal|22_0(element.id, EClass.rndHalf(element.ValueWithoutLink / 2), true, (int v) => v / 5 + 1, ref A_1);
    }
References g__AddVal(), Generate(), Element.id, EClass.rnd(), EClass.rndHalf(), and Element.ValueWithoutLink.
Referenced by g__AddRandom(), and g__AddSpecial().
g__AddSpecial()
void< Generate > DNA.g__AddSpecial (ref DNA::<>c__DisplayClass22_0 A_1) inline private
Definition at line 589 of file DNA.cs.
    {
        if (EClass.rnd(3) == 0)
        {
            this.<Generate>g__AddAction|22_5(ref A_1);
            return;
        }
        if (EClass.rnd(5) == 0)
        {
            this.<Generate>g__AddBody|22_4(ref A_1);
            return;
        }
        if (A_1.listFeat.Count > 0)
        {
            this.<Generate>g__AddFeat|22_3(ref A_1);
            return;
        }
        if (EClass.rnd(2) == 0)
        {
            this.<Generate>g__AddSkill|22_1(ref A_1);
            return;
        }
        this.<Generate>g__AddAttribute|22_2(ref A_1);
    }
References g__AddAction(), g__AddAttribute(), g__AddBody(), g__AddFeat(), g__AddSkill(), Generate(), and EClass.rnd().
Referenced by g__AddRandom(), and Generate().
g__AddVal()
void< Generate > DNA.g__AddVal (int id, int v, bool allowStack, Func< int, int > funcCost, ref DNA::<>c__DisplayClass22_0 A_5) inline private
Definition at line 451 of file DNA.cs.
    {
        bool flag = false;
        int num = EClass.curve(v, 20, 10, 90);
        v = EClass.curve(v, 20, 10, 80);
        int i = 0;
        while (i < this.vals.Count)
        {
            if (this.vals[i] == id)
            {
                if (!allowStack)
                {
                    return;
                }
                v /= 2;
                num /= 2;
                List<int> list = this.vals;
                int index = i + 1;
                list[index] += v;
                Debug.Log(string.Concat(new string[]
                {
                    this.vals[i + 1].ToString(),
                    ": ",
                    v.ToString(),
                    "/",
                    num.ToString()
                }));
                flag = true;
                break;
            }
            else
            {
                i += 2;
            }
        }
        if (v == 0)
        {
            return;
        }
        if (!flag)
        {
            this.vals.Add(id);
            this.vals.Add(v);
        }
        this.cost += funcCost(num);
    }
References EClass.curve(), and vals.
Referenced by g__AddAction(), g__AddAttribute(), g__AddBody(), g__AddFeat(), and g__AddSkill().
Generate()
void DNA.Generate (DNA::Type _type, Chara model = null) inline
Definition at line 180 of file DNA.cs.
    {
        DNA.<>c__DisplayClass22_0 CS$<>8__locals1;
        CS$<>8__locals1.<>4__this = this;
        CS$<>8__locals1.model = model;
        this.type = _type;
        this.cost = 0;
        this.vals.Clear();
        Debug.Log(this.seed);
        Rand.SetSeed(this.seed);
        if (CS$<>8__locals1.model == null)
        {
            CS$<>8__locals1.model = CharaGen.Create(this.id, this.lv);
        }
        if (this.type == DNA.Type.Inferior || CS$<>8__locals1.model == null)
        {
            this.type = DNA.Type.Inferior;
            return;
        }
        if (this.type == DNA.Type.Brain)
        {
            this.cost = 4;
            return;
        }
        CS$<>8__locals1.body = 0;
        CS$<>8__locals1.action = 0;
        CS$<>8__locals1.feat = 0;
        CS$<>8__locals1.listAttb = CS$<>8__locals1.model.elements.ListBestAttributes();
        CS$<>8__locals1.listSkill = CS$<>8__locals1.model.elements.ListBestSkills();
        CS$<>8__locals1.listFeat = CS$<>8__locals1.model.elements.ListGeneFeats();
        Rand.SetSeed(this.seed);
        if (CS$<>8__locals1.listFeat.Count == 0)
        {
            CS$<>8__locals1.listFeat = CS$<>8__locals1.model.ListAvailabeFeats(true);
        }
        Rand.SetSeed(this.seed);
        DNA.Type type = this.type;
        if (type != DNA.Type.Default)
        {
            if (type == DNA.Type.Superior)
            {
                this.<Generate>g__AddRandom|22_6(EClass.rnd(EClass.rnd(4)) + 3, ref CS$<>8__locals1);
                if (EClass.rnd(3) == 0)
                {
                    this.<Generate>g__AddSpecial|22_7(ref CS$<>8__locals1);
                }
                this.<Generate>g__AddSpecial|22_7(ref CS$<>8__locals1);
            }
        }
        else
        {
            this.<Generate>g__AddRandom|22_6(EClass.rnd(EClass.rnd(4)) + 1, ref CS$<>8__locals1);
            if (EClass.rnd(3) == 0 || this.vals.Count == 0)
            {
                this.<Generate>g__AddSpecial|22_7(ref CS$<>8__locals1);
            }
        }
        if (this.vals.Count == 0)
        {
            for (int i = 0; i < 10; i++)
            {
                if (EClass.rnd(4) == 0)
                {
                    this.<Generate>g__AddSpecial|22_7(ref CS$<>8__locals1);
                }
                else
                {
                    this.<Generate>g__AddRandom|22_6(1, ref CS$<>8__locals1);
                }
                if (this.vals.Count > 0)
                {
                    break;
                }
            }
        }
        Rand.SetSeed(-1);
        this.CalcCost();
    }
References CalcCost(), CharaGen.Create(), g__AddRandom(), g__AddSpecial(), Generate(), lv, EClass.rnd(), seed, type, and vals.
Referenced by g__AddAction(), g__AddAttribute(), g__AddBody(), g__AddFeat(), g__AddRandom(), g__AddSkill(), g__AddSpecial(), Generate(), GenerateWithGene(), and ActEffect.Proc().
GenerateGene() [1/2]
static Thing DNA.GenerateGene (CardRow r, DNA::Type? type = null, int lv = -1, int seed = -1) inline static
Definition at line 72 of file DNA.cs.
    {
        DNA.Type? type2 = type;
        DNA.Type type3 = DNA.Type.Brain;
        Thing thing = ThingGen.Create((type2.GetValueOrDefault() == type3 & type2 != null) ? "gene_brain" : "gene", -1, -1);
        DNA dna = new DNA();
        thing.MakeRefFrom(r.id);
        dna.id = r.id;
        dna.lv = ((lv == -1) ? r.LV : lv);
        dna.seed = ((seed == -1) ? EClass.rnd(20000) : seed);
        thing.c_DNA = dna;
        dna.GenerateWithGene(type ?? dna.GetRandomType(), thing, null);
        return thing;
    }
References ThingGen.Create(), GenerateWithGene(), GetRandomType(), CardRow.id, lv, RenderRow.LV, Card.MakeRefFrom(), EClass.rnd(), seed, and type.
GenerateGene() [2/2]
static Thing DNA.GenerateGene (Chara c, DNA::Type? type = null) inline static
Definition at line 57 of file DNA.cs.
    {
        DNA.Type? type2 = type;
        DNA.Type type3 = DNA.Type.Brain;
        Thing thing = ThingGen.Create((type2.GetValueOrDefault() == type3 & type2 != null) ? "gene_brain" : "gene", -1, -1);
        DNA dna = new DNA();
        thing.MakeRefFrom(c, null);
        dna.id = c.id;
        dna.lv = c.LV;
        dna.seed = EClass.rnd(20000);
        thing.c_DNA = dna;
        dna.GenerateWithGene(type ?? dna.GetRandomType(), thing, c);
        return thing;
    }
References ThingGen.Create(), GenerateWithGene(), GetRandomType(), Card.id, Card.LV, Card.MakeRefFrom(), EClass.rnd(), and type.
Referenced by Trait.CreateStock(), TraitGodStatue.GetManiGene(), Chara.MakeBraineCell(), and Chara.MakeGene().
GenerateWithGene()
void DNA.GenerateWithGene (DNA::Type _type, Card gene, Chara model = null) inline
Definition at line 173 of file DNA.cs.
    {
        this.Generate(_type, model);
        gene.ChangeMaterial(this.GetMaterialId(this.type));
        gene.elements.SetTo(10, 0);
    }
References Card.ChangeMaterial(), Card.elements, Generate(), GetMaterialId(), ElementContainer.SetTo(), and type.
Referenced by GenerateGene().
GetDurationHour()
int DNA.GetDurationHour () inline
Definition at line 301 of file DNA.cs.
    {
        return this.cost * this.cost / 2;
    }
Referenced by InvOwnerGene._OnProcess(), and TraitGene.WriteNote().
GetInvalidAction()
Element DNA.GetInvalidAction (Chara c) inline
Definition at line 428 of file DNA.cs.
    {
        for (int i = 0; i < this.vals.Count; i += 2)
        {
            Element element = Element.Create(this.vals[i], this.vals[i + 1]);
            if (element.source.category == "ability")
            {
                using (List<ActList.Item>.Enumerator enumerator = c.ability.list.items.GetEnumerator())
                {
                    while (enumerator.MoveNext())
                    {
                        if (enumerator.Current.act.source.id == element.id)
{
                            return element;
                        }
                    }
                }
            }
        }
        return null;
    }
References Chara.ability, Element.Create(), Element.id, ActList.items, CharaAbility.list, Element.source, and vals.
Referenced by InvOwnerGene._OnProcess().
GetInvalidFeat()
Element DNA.GetInvalidFeat (Chara c) inline
Definition at line 415 of file DNA.cs.
    {
        for (int i = 0; i < this.vals.Count; i += 2)
        {
            Element element = Element.Create(this.vals[i], this.vals[i + 1]);
            if (element.source.category == "feat" && c.Evalue(element.id) >= element.source.max)
            {
                return element;
            }
        }
        return null;
    }
References Element.Create(), Card.Evalue(), Element.id, Element.source, and vals.
Referenced by InvOwnerGene._OnProcess().
GetMaterialId()
string DNA.GetMaterialId (DNA::Type type) inline
Definition at line 284 of file DNA.cs.
    {
        if (type == DNA.Type.Default)
        {
            return "jelly";
        }
        if (type == DNA.Type.Superior)
        {
            return "gold";
        }
        if (type != DNA.Type.Brain)
        {
            return "process";
        }
        return "amethyst";
    }
References type.
Referenced by GenerateWithGene().
GetRandomType()
DNA.Type DNA.GetRandomType () inline
Definition at line 306 of file DNA.cs.
    {
        if (EClass.rnd(5) == 0)
        {
            return DNA.Type.Superior;
        }
        if (EClass.rnd(10) == 0)
        {
            return DNA.Type.Inferior;
        }
        return DNA.Type.Default;
    }
References EClass.rnd().
Referenced by GenerateGene().
GetText()
string DNA.GetText () inline
Definition at line 319 of file DNA.cs.
    {
        string s = "gene";
        CardRow cardRow = EClass.sources.cards.map.TryGetValue(this.id, null);
        return s.lang((((cardRow != null) ? cardRow.GetName() : null) ?? "???").ToTitleCase(false), this.cost.ToString() ?? "", null, null, null);
    }
References SourceManager.cards, CardRow.GetName(), SourceCard.map, and EClass.sources.
Referenced by WindowCharaMini.Refresh().
GetType()
static DNA.Type DNA.GetType (string idMat) inline static
Definition at line 267 of file DNA.cs.
    {
        if (idMat == "jelly")
        {
            return DNA.Type.Default;
        }
        if (idMat == "gold")
        {
            return DNA.Type.Superior;
        }
        if (!(idMat == "amethyst"))
        {
            return DNA.Type.Inferior;
        }
        return DNA.Type.Brain;
    }
Referenced by ActEffect.Proc().
WriteNote()
void DNA.WriteNote (UINote n) inline
Definition at line 326 of file DNA.cs.
    {
        if (!this.CanRemove())
        {
            n.AddText("isPermaGene".lang(), FontColor.Warning);
        }
        if (this.type == DNA.Type.Brain)
        {
            SourceChara.Row row = EClass.sources.charas.map.TryGetValue(this.id, null);
            if (row != null)
            {
                string tactics = row.tactics;
                SourceTactics.Row row2 = EClass.sources.tactics.map.TryGetValue(row.id, null);
                string defaultStr;
                if ((defaultStr = ((row2 != null) ? row2.id : null)) == null)
                {
                    SourceTactics.Row row3 = EClass.sources.tactics.map.TryGetValue(row.job, null);
                    defaultStr = (((row3 != null) ? row3.id : null) ?? "predator");
                }
                string key = tactics.IsEmpty(defaultStr);
                n.AddText("gene_info".lang(EClass.sources.tactics.map[key].GetName().ToTitleCase(false), "", null, null, null), FontColor.ButtonGeneral);
            }
            for (int i = 0; i < this.vals.Count; i += 2)
            {
                int num = this.vals[i];
                int num2 = this.vals[i + 1];
                FontColor color = (num2 >= 0) ? FontColor.Good : FontColor.Bad;
                string @ref = (num + 1).ToString() ?? "";
                string text = "";
                num2 = Mathf.Abs(num2 / 20) + 1;
                text = string.Concat(new string[]
                {
                    text,
                    "[",
                    "*".Repeat(Mathf.Clamp(num2, 1, 5)),
                    (num2 > 5) ? "+" : "",
                    "]"
                });
                n.AddText("gene_info_brain".lang(@ref, text, null, null, null), color);
            }
            return;
        }
        for (int j = 0; j < this.vals.Count; j += 2)
        {
            Element element = Element.Create(this.vals[j], this.vals[j + 1]);
            string text2 = "";
            int num3 = element.Value / 10;
            FontColor color2 = FontColor.Good;
            string category = element.source.category;
            if (!(category == "slot"))
            {
                if (!(category == "feat"))
                {
                    if (category == "ability")
                    {
                        color2 = FontColor.Topic2;
                        num3 = -1;
                    }
                }
                else
                {
                    color2 = FontColor.FoodMisc;
                    num3 = -1;
                }
            }
            else
            {
                color2 = FontColor.Myth;
                num3 = -1;
            }
            if (num3 >= 0)
            {
                text2 = string.Concat(new string[]
                {
                    text2,
                    "[",
                    "*".Repeat(Mathf.Clamp(num3, 1, 5)),
                    (num3 > 5) ? "+" : "",
                    "]"
                });
            }
            if (EClass.debug.showExtra)
            {
                text2 = text2 + " " + element.Value.ToString();
            }
            n.AddText("gene_info".lang(element.Name.ToTitleCase(true), text2, null, null, null), color2);
        }
    }
References CanRemove(), SourceManager.charas, Element.Create(), EClass.debug, CardRow.id, SourceTactics.Row.id, SourceChara.Row.job, Element.Name, CoreDebug.showExtra, Element.source, EClass.sources, SourceChara.Row.tactics, SourceManager.tactics, text, type, vals, and Element.Value.
Referenced by WindowCharaMini.Refresh(), and TraitGene.WriteNote().
Member Data Documentation
id
string DNA.id
Definition at line 615 of file DNA.cs.
Referenced by Tactics.Tactics().
ints
int [] DNA.ints = new int[4]
Definition at line 618 of file DNA.cs.
vals
List<int> DNA.vals = new List<int>()
Definition at line 621 of file DNA.cs.
Referenced by Apply(), CalcCost(), CanRemove(), g__AddVal(), Generate(), GetInvalidAction(), GetInvalidFeat(), and WriteNote().
Property Documentation
cost
int DNA.cost get set
Definition at line 21 of file DNA.cs.
    {
        get
        {
            return this.ints[1];
        }
        set
        {
            this.ints[1] = value;
        }
    }
Referenced by Apply(), CharaGenes.GetTotalCost(), TraitGene.GetValue(), InvOwnerGene.OnWriteNote(), CharaGenes.Remove(), InvOwnerGene.ShouldShowGuide(), and TraitGene.WriteNote().
lv
int DNA.lv get set
Definition at line 33 of file DNA.cs.
    {
        get
        {
            return this.ints[2];
        }
        set
        {
            this.ints[2] = value;
        }
    }
Referenced by Generate(), and GenerateGene().
seed
int DNA.seed get set
Definition at line 45 of file DNA.cs.
    {
        get
        {
            return this.ints[3];
        }
        set
        {
            this.ints[3] = value;
        }
    }
Referenced by Generate(), and GenerateGene().
type
DNA.Type DNA.type get set
Definition at line 9 of file DNA.cs.
    {
        get
        {
            return this.ints[0].ToEnum<DNA.Type>();
        }
        set
        {
            this.ints[0] = (int)value;
        }
    }
Referenced by InvOwnerGene._OnProcess(), Apply(), Generate(), GenerateGene(), GenerateWithGene(), GetMaterialId(), TraitGene.GetName(), Tactics.Tactics(), and WriteNote().
The documentation for this class was generated from the following file:
Elin/DNA.cs