Elin Decompiled Documentation: ElementContainerFaction Class Reference
ElementContainerFaction Class Reference
Public Member Functions
bool IsEffective (Thing t)
void OnEquip (Chara c, Thing t)
void OnUnequip (Chara c, Thing t)
void OnEquip (Thing t)
void OnUnequip (Thing t)
void CheckDirty ()
void OnLeaveFaith ()
void OnJoinFaith ()
void OnAddMemeber (Chara c)
void OnRemoveMember (Chara c)
Public Member Functions inherited from ElementContainer
void ApplyElementMap (int uid, SourceValueType type, Dictionary< int, int > map, int lv, bool invert=false, bool applyFeat=false)
void ApplyMaterialElementMap (Thing t, bool invert=false)
void ImportElementMap (Dictionary< int, int > map)
ElementContainer ImportElementMap (int[] ints)
void ApplyPotential (int mode=0)
int Value (int ele)
virtual int ValueBonus (Element e)
int ValueWithoutLink (int ele)
int ValueWithoutLink (string alias)
int GetFeatRef (int ele, int idx=0)
int Exp (int ele)
bool Has (int ele)
bool Has (SourceElement.Row row)
bool Has (string alias)
bool HasBase (int ele)
int Base (int ele)
void Learn (int ele, int v=1)
void Train (int ele, int a=10)
void ModExp (int ele, float a, bool chain=false)
virtual void OnLearn (int ele)
virtual void OnTrain (int ele)
virtual void OnLevelUp (Element e, int lastValue)
virtual void OnLevelDown (Element e, int lastValue)
Element SetBase (string alias, int v, int potential=0)
Element SetBase (int id, int v, int potential=0)
void SetTo (int id, int v)
void Remove (int id)
Element ModBase (int ele, int v)
virtual void OnChangeValue ()
Element ModPotential (int ele, int v)
Element ModTempPotential (int ele, int v, int threshMsg=0)
virtual void OnModTempPotential (Element e, int v, int threshMsg)
int GetSpellExp (Chara c, Element e, int costMod=100)
Element GetElement (string alias)
Element GetElement (int id)
Element CreateElement (int id)
Element GetOrCreateElement (Element ele)
Element GetOrCreateElement (string alias)
Element GetOrCreateElement (int id)
void SetParent (Card c)
void SetParent (ElementContainer newParent=null)
List< Element > ListElements (Func< Element, bool > shoudList=null, Comparison< Element > comparison=null)
List< Element > ListBestAttributes ()
List< Element > ListBestSkills ()
List< Element > ListGeneFeats ()
List< Element > ListLearnable (Chara c)
List< Element > ListRune ()
void CopyTo (ElementContainer container)
void AddNote (UINote n, Func< Element, bool > isValid=null, Action onAdd=null, NoteMode mode=NoteMode.Default, bool addRaceFeat=false, Func< Element, string, string > funcText=null, Action< UINote, Element > onAddNote=null)
void AddNoteAll (UINote n)
Public Attributes
bool isDirty
Public Attributes inherited from ElementContainer
Dictionary< int, Element > dict = new Dictionary<int, Element>()
ElementContainer parent
List< int > list
Additional Inherited Members
Public Types inherited from ElementContainer
enum NoteMode {
Default , CharaMake , CharaMakeAttributes , Domain ,
BonusTrait
}
Static Public Member Functions inherited from ElementContainer
static int GetSortVal (Element a)
Static Public Member Functions inherited from EClass
static int rndSeed (int a, int seed)
static int rnd (long a)
static int rnd (int a)
static int curve (int a, int start, int step, int rate=75)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Static Public Attributes inherited from ElementContainer
const int sizeElement = 5
Static Public Attributes inherited from EClass
static Core core
Properties inherited from ElementContainer
virtual Card Card [get]
virtual Chara Chara [get]
virtual bool LimitLink [get]
virtual bool IsMeleeWeapon [get]
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Detailed Description
Definition at line 1 of file ElementContainerFaction.cs.
Member Function Documentation
CheckDirty()
void ElementContainerFaction.CheckDirty () inline
Definition at line 64 of file ElementContainerFaction.cs.
    {
        if (!isDirty)
        {
            return;
        }
        foreach (Chara value in EClass.game.cards.globalCharas.Values)
        {
            if (value.IsPCFaction)
            {
                value.Refresh();
            }
        }
        if (EClass.core.IsGameStarted)
        {
            foreach (Chara chara in EClass._map.charas)
            {
                if (chara.IsPCFactionMinion)
                {
                    chara.Refresh();
                }
            }
        }
        isDirty = false;
    }
References EClass._map, Game.cards, Map.charas, EClass.core, EClass.game, CardManager.globalCharas, isDirty, Core.IsGameStarted, Chara.IsPCFaction, Chara.IsPCFactionMinion, and Chara.Refresh().
Referenced by OnEquip(), and OnUnequip().
IsEffective()
bool ElementContainerFaction.IsEffective (Thing t) inline
Definition at line 5 of file ElementContainerFaction.cs.
    {
        if (t.c_idDeity.IsEmpty())
        {
            return true;
        }
        return t.c_idDeity == EClass.pc.idFaith;
    }
References Card.c_idDeity, Chara.idFaith, and EClass.pc.
Referenced by OnEquip(), and OnUnequip().
OnAddMemeber()
void ElementContainerFaction.OnAddMemeber (Chara c) inline
Definition at line 112 of file ElementContainerFaction.cs.
    {
        foreach (BodySlot slot in c.body.slots)
        {
            if (slot.thing != null)
            {
                OnEquip(slot.thing);
            }
        }
    }
References OnEquip(), and BodySlot.thing.
Referenced by FactionBranch.AddMemeber(), OnJoinFaith(), and FactionBranch.SetOwner().
OnEquip() [1/2]
void ElementContainerFaction.OnEquip (Chara c, Thing t) inline
Definition at line 14 of file ElementContainerFaction.cs.
    {
        if (c.IsPCFaction)
        {
            OnEquip(t);
        }
    }
References Chara.IsPCFaction, and OnEquip().
Referenced by CharaBody.Equip(), OnAddMemeber(), and OnEquip().
OnEquip() [2/2]
void ElementContainerFaction.OnEquip (Thing t) inline
Definition at line 30 of file ElementContainerFaction.cs.
    {
        if (!IsEffective(t))
        {
            return;
        }
        foreach (Element value in t.elements.dict.Values)
        {
            if (value.IsGlobalElement)
            {
                ModBase(value.id, value.Value).vExp = value.vExp;
                isDirty = true;
            }
        }
        CheckDirty();
    }
References CheckDirty(), Element.id, isDirty, IsEffective(), Element.IsGlobalElement, ElementContainer.ModBase(), Element.Value, and Element.vExp.
OnJoinFaith()
void ElementContainerFaction.OnJoinFaith () inline
Definition at line 101 of file ElementContainerFaction.cs.
    {
        foreach (Chara value in EClass.game.cards.globalCharas.Values)
        {
            if (value.IsPCFaction)
            {
                OnAddMemeber(value);
            }
        }
    }
References Game.cards, EClass.game, CardManager.globalCharas, Chara.IsPCFaction, and OnAddMemeber().
Referenced by Religion.JoinFaith().
OnLeaveFaith()
void ElementContainerFaction.OnLeaveFaith () inline
Definition at line 90 of file ElementContainerFaction.cs.
    {
        foreach (Chara value in EClass.game.cards.globalCharas.Values)
        {
            if (value.IsPCFaction)
            {
                OnRemoveMember(value);
            }
        }
    }
References Game.cards, EClass.game, CardManager.globalCharas, Chara.IsPCFaction, and OnRemoveMember().
Referenced by Religion.LeaveFaith().
OnRemoveMember()
void ElementContainerFaction.OnRemoveMember (Chara c) inline
Definition at line 123 of file ElementContainerFaction.cs.
    {
        foreach (BodySlot slot in c.body.slots)
        {
            if (slot.thing != null)
            {
                OnUnequip(slot.thing);
            }
        }
    }
References OnUnequip(), and BodySlot.thing.
Referenced by OnLeaveFaith(), and FactionBranch.RemoveMemeber().
OnUnequip() [1/2]
void ElementContainerFaction.OnUnequip (Chara c, Thing t) inline
Definition at line 22 of file ElementContainerFaction.cs.
    {
        if (c.IsPCFaction)
        {
            OnUnequip(t);
        }
    }
References Chara.IsPCFaction, and OnUnequip().
Referenced by OnRemoveMember(), OnUnequip(), and CharaBody.Unequip().
OnUnequip() [2/2]
void ElementContainerFaction.OnUnequip (Thing t) inline
Definition at line 47 of file ElementContainerFaction.cs.
    {
        if (!IsEffective(t))
        {
            return;
        }
        foreach (Element value in t.elements.dict.Values)
        {
            if (value.IsGlobalElement)
            {
                ModBase(value.id, -value.Value);
                isDirty = true;
            }
        }
        CheckDirty();
    }
References CheckDirty(), Element.id, isDirty, IsEffective(), Element.IsGlobalElement, ElementContainer.ModBase(), and Element.Value.
Member Data Documentation
isDirty
bool ElementContainerFaction.isDirty
Definition at line 3 of file ElementContainerFaction.cs.
Referenced by CheckDirty(), OnEquip(), and OnUnequip().
The documentation for this class was generated from the following file:
Elin/ElementContainerFaction.cs