Elin Decompiled Documentation: BookList Class Reference
BookList Class Reference
Classes
class Item
Static Public Member Functions
static void Init ()
static Item GetRandomItem (string idCat="Book")
static Item GetItem (string id, string idCat="Book")
static string[] LoadDefaultBookList ()
Static Public Attributes
static List< Func< string[]> > booklistLoaders = new List<Func<string[]>>()
static Dictionary< string, Dictionary< string, Item > > dict
Detailed Description
Definition at line 7 of file BookList.cs.
Member Function Documentation
GetItem()
static Item BookList.GetItem (string id, string idCat = "Book") inline static
Definition at line 96 of file BookList.cs.
    {
        Init();
        return dict[idCat].TryGetValue(id) ?? dict["Book"]["_default"];
    }
References dict, and Init().
GetRandomItem()
static Item BookList.GetRandomItem (string idCat = "Book") inline static
Definition at line 89 of file BookList.cs.
    {
        Init();
        return dict[idCat].Where((KeyValuePair<string, Item> p) => p.Value.chance != 0).ToList().RandomItemWeighted((KeyValuePair<string, Item> p) => p.Value.chance)
            .Value;
    }
References dict, and Init().
Referenced by TraitBook.OnCreate().
Init()
static void BookList.Init () inline static
Definition at line 32 of file BookList.cs.
    {
        if (dict != null)
        {
            return;
        }
        dict = new Dictionary<string, Dictionary<string, Item>>();
        List<string> list = new List<string>();
        list.AddRange(LoadDefaultBookList());
        foreach (Func<string[]> booklistLoader in booklistLoaders)
        {
            try
            {
                list.AddRange(booklistLoader());
            }
            catch (Exception arg)
            {
                Debug.LogWarning($"#book external booklist loader failed\n{arg}");
            }
        }
        foreach (string item in list)
        {
            DirectoryInfo directoryInfo = new DirectoryInfo(item);
            if (!directoryInfo.Exists)
            {
                Debug.LogWarning("#book invalid booklist path/" + item);
                continue;
            }
            string name = directoryInfo.Name;
            dict.TryAdd(name, new Dictionary<string, Item>());
            FileInfo[] files = directoryInfo.GetFiles("*.txt", SearchOption.TopDirectoryOnly);
            foreach (FileInfo fileInfo in files)
            {
                using StreamReader streamReader = new StreamReader(fileInfo.FullName);
                string text = Path.ChangeExtension(fileInfo.Name, null);
                string text2 = streamReader.ReadLine();
                int? num = text2?.Length;
                if (!num.HasValue || num.GetValueOrDefault() <= 0)
                {
                    Debug.LogWarning("#book invalid first line/" + item);
                    continue;
                }
                string[] array = text2.Split(',');
                dict[name][text] = new Item
                {
                    cat = name,
                    title = array[0],
                    author = ((array.Length > 1) ? "nameAuthor".lang(array[1]) : "unknownAuthor".lang()),
                    chance = ((array.Length > 2) ? array[2].ToInt() : 100),
                    skin = ((array.Length > 3) ? array[3].ToInt() : 0),
                    id = text,
                    path = fileInfo.FullName
                };
            }
        }
    }
References $, booklistLoaders, Debug, dict, item, LoadDefaultBookList(), and title.
Referenced by GetItem(), and GetRandomItem().
LoadDefaultBookList()
static string[] BookList.LoadDefaultBookList () inline static
Definition at line 102 of file BookList.cs.
    {
        return new string[2]
        {
            CorePath.CorePackage.Book,
            CorePath.CorePackage.Scroll
        };
    }
References CorePath.CorePackage.Book.
Referenced by Init().
Member Data Documentation
booklistLoaders
List<Func<string[]> > BookList.booklistLoaders = new List<Func<string[]>>() static
Definition at line 28 of file BookList.cs.
Referenced by Init().
dict
Dictionary<string, Dictionary<string, Item> > BookList.dict static
Definition at line 30 of file BookList.cs.
Referenced by GetItem(), GetRandomItem(), and Init().
The documentation for this class was generated from the following file:
Elin/Plugins.UI/BookList.cs