Elin Decompiled Documentation: HexInput Class Reference
HexInput Class Reference
Public Member Functions
void SelectColor (Color color)
Events
Action< Color > ColorSelected
Private Member Functions
void Awake ()
char OnValidateInput (string text, int charIndex, char addedChar)
void BackupColor ()
void OnInputValueChanged (string value)
string GetAlpha (string alpha)
void OnInputEndEdit (string value)
Color GetColorByHex (string hex)
Private Attributes
ColorPicker colorPicker
UiInputField input
string hexBackup
string currentHex
Detailed Description
Definition at line 8 of file HexInput.cs.
Member Function Documentation
Awake()
void HexInput.Awake () inline private
Definition at line 24 of file HexInput.cs.
    {
        input.InputSelected += BackupColor;
        input.onEndEdit.AddListener(OnInputEndEdit);
        input.onValueChanged.AddListener(OnInputValueChanged);
        UiInputField uiInputField = input;
        uiInputField.onValidateInput = (InputField.OnValidateInput)Delegate.Combine(uiInputField.onValidateInput, new InputField.OnValidateInput(OnValidateInput));
        input.characterLimit = (colorPicker.IsAlphaBeingUsed() ? 8 : 6);
    }
References BackupColor(), colorPicker, input, Empyrean.ColorPicker.ColorPicker.IsAlphaBeingUsed(), OnInputEndEdit(), OnInputValueChanged(), and OnValidateInput().
BackupColor()
void HexInput.BackupColor () inline private
Definition at line 43 of file HexInput.cs.
    {
        hexBackup = input.text;
    }
References hexBackup, and input.
Referenced by Awake().
GetAlpha()
string HexInput.GetAlpha (string alpha) inline private
Definition at line 80 of file HexInput.cs.
    {
        if (!colorPicker.IsAlphaBeingUsed())
        {
            return "";
        }
        return alpha;
    }
References colorPicker, and Empyrean.ColorPicker.ColorPicker.IsAlphaBeingUsed().
Referenced by OnInputValueChanged().
GetColorByHex()
Color HexInput.GetColorByHex (string hex) inline private
Definition at line 99 of file HexInput.cs.
    {
        return Colorist.HexToColor(hex);
    }
References Empyrean.Utils.Colorist.HexToColor().
Referenced by OnInputEndEdit(), and OnInputValueChanged().
OnInputEndEdit()
void HexInput.OnInputEndEdit (string value) inline private
Definition at line 89 of file HexInput.cs.
    {
        if (Input.GetKeyDown(KeyCode.Escape))
        {
            currentHex = hexBackup;
        }
        input.text = currentHex;
        this.ColorSelected(GetColorByHex(currentHex));
    }
References ColorSelected, currentHex, GetColorByHex(), and hexBackup.
Referenced by Awake().
OnInputValueChanged()
void HexInput.OnInputValueChanged (string value) inline private
Definition at line 48 of file HexInput.cs.
    {
        if (input.isFocused)
        {
            switch (value.Length)
            {
            default:
                return;
            case 0:
            case 1:
            case 2:
            case 5:
            case 7:
                currentHex = hexBackup;
                return;
            case 3:
                currentHex = string.Concat(value[0], value[0], value[1], value[1], value[2], value[2], GetAlpha("FF"));
                break;
            case 4:
                currentHex = string.Concat(value[0], value[0], value[1], value[1], value[2], value[2], GetAlpha(string.Concat(value[3], value[3])));
                break;
            case 6:
                currentHex = value + GetAlpha("FF");
                break;
            case 8:
                currentHex = value;
                break;
            }
            this.ColorSelected(GetColorByHex(currentHex));
        }
    }
References ColorSelected, currentHex, GetAlpha(), GetColorByHex(), hexBackup, and input.
Referenced by Awake().
OnValidateInput()
char HexInput.OnValidateInput (string text, int charIndex, char addedChar) inline private
Definition at line 34 of file HexInput.cs.
    {
        if (!Regex.IsMatch(addedChar.ToString(), "[A-Fa-f0-9]"))
        {
            return '\0';
        }
        return addedChar;
    }
Referenced by Awake().
SelectColor()
void HexInput.SelectColor (Color color) inline
Definition at line 104 of file HexInput.cs.
    {
        if (!input.isFocused)
        {
            string text = (currentHex = Colorist.ColorToHex(color));
            input.text = text;
        }
    }
References Empyrean.Utils.Colorist.ColorToHex(), currentHex, and input.
Referenced by Empyrean.ColorPicker.ColorPicker.UpdateColorPicker().
Member Data Documentation
colorPicker
ColorPicker HexInput.colorPicker private
Definition at line 11 of file HexInput.cs.
Referenced by Awake(), and GetAlpha().
currentHex
string HexInput.currentHex private
Definition at line 18 of file HexInput.cs.
Referenced by OnInputEndEdit(), OnInputValueChanged(), and SelectColor().
hexBackup
string HexInput.hexBackup private
Definition at line 16 of file HexInput.cs.
Referenced by BackupColor(), OnInputEndEdit(), and OnInputValueChanged().
input
UiInputField HexInput.input private
Definition at line 14 of file HexInput.cs.
Referenced by Awake(), BackupColor(), OnInputValueChanged(), and SelectColor().
Event Documentation
ColorSelected
Action<Color> HexInput.ColorSelected
Initial value:
= delegate
    {
    }
Definition at line 20 of file HexInput.cs.
Referenced by OnInputEndEdit(), and OnInputValueChanged().
The documentation for this class was generated from the following file:
Elin/Plugins.UI/HexInput.cs