Elin Decompiled Documentation: RecipeUpdater Class Reference
RecipeUpdater Class Reference
Public Types
enum Mode { Passive , Immediate , Validate }
Public Member Functions
void Build (Point _p, Mode _mode=Mode.Passive)
void FixedUpdate ()
IEnumerable RunRecipe ()
IEnumerable RunDisassemble ()
Public Attributes
IEnumerator Enumerator
Point pos = new Point()
Static Public Attributes
static List< Thing > listD = new List<Thing>()
static List< Thing > lastListD = new List<Thing>()
static HashSet< Recipe > recipes = new HashSet<Recipe>()
static HashSet< Recipe > lastRecipes = new HashSet<Recipe>()
static HashSet< string > factories = new HashSet<string>()
static Mode mode
static int sync
static bool dirty
Static Public Attributes inherited from EClass
static Core core
Additional Inherited Members
Static Public Member Functions inherited from EClass
static int rnd (int a)
static int curve (int a, int start, int step, int rate=75)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Detailed Description
Definition at line 5 of file RecipeUpdater.cs.
Member Enumeration Documentation
Mode
enum RecipeUpdater.Mode
Enumerator
Passive
Immediate
Validate
Definition at line 7 of file RecipeUpdater.cs.
    {
        Passive,
        Immediate,
        Validate
    }
Member Function Documentation
Build()
void RecipeUpdater.Build (Point _p, Mode _mode = Mode::Passive) inline
Definition at line 34 of file RecipeUpdater.cs.
    {
        if (!LayerCraftFloat.Instance)
        {
            return;
        }
        pos.Set(_p);
        mode = _mode;
        sync++;
        Enumerator = RunRecipe().GetEnumerator();
        if (mode == Mode.Passive)
        {
            return;
        }
        for (int i = 0; i < 1000; i++)
        {
            FixedUpdate();
            if (Enumerator == null)
            {
                break;
            }
        }
    }
References Enumerator, FixedUpdate(), LayerCraftFloat.Instance, mode, pos, RunRecipe(), Point.Set(), and sync.
Referenced by AM_Adv._OnUpdateInput(), Scene.Init(), AM_Adv.OnBecomeNoGoal(), LayerCraftFloat.OnSwitchContent(), and LayerCraftFloat.RefreshCraft().
FixedUpdate()
void RecipeUpdater.FixedUpdate () inline
Definition at line 58 of file RecipeUpdater.cs.
    {
        if (Enumerator != null && !Enumerator.MoveNext())
        {
            Enumerator = null;
        }
    }
References Enumerator.
Referenced by Build(), and GameUpdater.FixedUpdate().
RunDisassemble()
IEnumerable RecipeUpdater.RunDisassemble () inline
Definition at line 202 of file RecipeUpdater.cs.
    {
        lastListD.Clear();
        foreach (Thing item in listD)
        {
            lastListD.Add(item);
        }
        listD.Clear();
        yield return true;
        foreach (Card item2 in EClass.pc.pos.ListCards())
        {
            if (item2.isThing)
            {
                item2.Thing.GetDisassembles(listD);
            }
        }
        yield return true;
        foreach (Thing thing in EClass.pc.things)
        {
            thing.GetDisassembles(listD);
        }
        yield return true;
        if (mode == Mode.Passive && listD.SequenceEqual(lastListD))
        {
            yield return false;
        }
        else if (mode != Mode.Validate)
        {
            LayerCraftFloat.Instance.RefreshDisassemble();
        }
        yield return null;
    }
References ActPlan.List.Add(), Thing.GetDisassembles(), LayerCraftFloat.Instance, Card.isThing, item, lastListD, Point.ListCards(), listD, mode, EClass.pc, Card.pos, LayerCraftFloat.RefreshDisassemble(), Card.Thing, and Card.things.
RunRecipe()
IEnumerable RecipeUpdater.RunRecipe () inline
Definition at line 66 of file RecipeUpdater.cs.
    {
        recipes.Clear();
        factories.Clear();
        yield return true;
        int count = 0;
        for (int i = pos.x - 1; i < pos.x + 2; i++)
        {
            if (i < 0 || i >= EClass._map.Size)
            {
                continue;
            }
            for (int j = pos.z - 1; j < pos.z + 2; j++)
            {
                if (j < 0 || j >= EClass._map.Size)
                {
                    continue;
                }
                Cell cell = EClass._map.cells[i, j];
                if (cell.detail == null || cell.detail.things.Count == 0)
                {
                    continue;
                }
                if (pos.cell.effect?.IsFire ?? false)
                {
                    factories.Add("fire");
                }
                foreach (Thing thing in cell.detail.things)
                {
                    if (thing.IsInstalled)
                    {
                        if (thing.trait.IsFactory)
{
                            factories.Add(thing.id);
                        }
                        if (thing.trait.ToggleType == ToggleType.Fire && thing.isOn)
{
                            factories.Add("fire");
                        }
                    }
                }
            }
        }
        yield return true;
        EClass.pc.things.AddFactory(factories);
        yield return true;
        foreach (Thing thing2 in EClass.pc.things)
        {
            thing2.GetRecipes(recipes);
            count++;
        }
        yield return true;
        for (int k = pos.x - 1; k < pos.x + 2; k++)
        {
            if (k < 0 || k >= EClass._map.Size)
            {
                continue;
            }
            for (int l = pos.z - 1; l < pos.z + 2; l++)
            {
                if (l < 0 || l >= EClass._map.Size)
                {
                    continue;
                }
                Cell cell = EClass._map.cells[k, l];
                if (cell.detail == null || cell.detail.things.Count == 0)
                {
                    continue;
                }
                foreach (Thing thing3 in cell.detail.things)
                {
                    if (thing3.isNPCProperty)
                    {
                        continue;
                    }
                    if (thing3.trait.IsContainer)
                    {
                        if (!thing3.IsInstalled)
{
                            continue;
                        }
                    }
                    else if (thing3.IsInstalled)
                    {
                        continue;
                    }
                    thing3.GetRecipes(recipes);
                    count++;
                }
            }
        }
        yield return true;
        List<Recipe> list = new List<Recipe>();
        foreach (Recipe recipe in recipes)
        {
            bool flag = true;
            string id = recipe.id;
            if ((id == "waystone" || id == "waystone_temp") && EClass.game.quests.GetPhase<QuestExploration>() >= 6)
            {
                list.Add(recipe);
                continue;
            }
            foreach (Recipe.Ingredient ingredient in recipe.ingredients)
            {
                if (ingredient.thing == null)
                {
                    flag = false;
                    break;
                }
            }
            if (!flag)
            {
                list.Add(recipe);
            }
        }
        foreach (Recipe item in list)
        {
            recipes.Remove(item);
        }
        yield return true;
        if (mode == Mode.Passive && lastRecipes.SetEquals(recipes))
        {
            yield return false;
        }
        else if (mode != Mode.Validate)
        {
            LayerCraftFloat.Instance.RefreshCraft();
        }
        lastRecipes.Clear();
        foreach (Recipe recipe2 in recipes)
        {
            lastRecipes.Add(recipe2);
        }
        yield return null;
    }
References EClass._map, ThingContainer.AddFactory(), Point.cell, Map.cells, Cell.detail, Cell.effect, factories, EClass.game, Thing.GetRecipes(), Card.id, Recipe.id, Recipe.ingredients, LayerCraftFloat.Instance, Trait.IsContainer, Trait.IsFactory, CellEffect.IsFire, Card.IsInstalled, Card.isNPCProperty, Card.isOn, item, lastRecipes, mode, EClass.pc, pos, Game.quests, recipes, LayerCraftFloat.RefreshCraft(), MapBounds.Size, Card.things, CellDetail.things, Trait.ToggleType, Card.trait, Point.x, and Point.z.
Referenced by Build().
Member Data Documentation
dirty
bool RecipeUpdater.dirty static
Definition at line 32 of file RecipeUpdater.cs.
Referenced by AM_Adv._OnUpdateInput().
Enumerator
IEnumerator RecipeUpdater.Enumerator
Definition at line 14 of file RecipeUpdater.cs.
Referenced by Build(), and FixedUpdate().
factories
HashSet<string> RecipeUpdater.factories = new HashSet<string>() static
Definition at line 26 of file RecipeUpdater.cs.
Referenced by RunRecipe().
lastListD
List<Thing> RecipeUpdater.lastListD = new List<Thing>() static
Definition at line 20 of file RecipeUpdater.cs.
Referenced by RunDisassemble().
lastRecipes
HashSet<Recipe> RecipeUpdater.lastRecipes = new HashSet<Recipe>() static
Definition at line 24 of file RecipeUpdater.cs.
Referenced by RunRecipe().
listD
List<Thing> RecipeUpdater.listD = new List<Thing>() static
Definition at line 18 of file RecipeUpdater.cs.
Referenced by LayerCraftFloat.RefreshDisassemble(), and RunDisassemble().
mode
Mode RecipeUpdater.mode static
Definition at line 28 of file RecipeUpdater.cs.
Referenced by Build(), RunDisassemble(), and RunRecipe().
pos
Point RecipeUpdater.pos = new Point()
Definition at line 16 of file RecipeUpdater.cs.
Referenced by Build(), and RunRecipe().
recipes
HashSet<Recipe> RecipeUpdater.recipes = new HashSet<Recipe>() static
Definition at line 22 of file RecipeUpdater.cs.
Referenced by LayerCraftFloat.RefreshCraft(), and RunRecipe().
sync
int RecipeUpdater.sync static
Definition at line 30 of file RecipeUpdater.cs.
Referenced by Build().
The documentation for this class was generated from the following file:
Elin/RecipeUpdater.cs