Elin Decompiled Documentation: SkinManager.FontSet Class Reference
SkinManager.FontSet Class Reference
Public Attributes
FontData ui = new FontData()
FontData chatbox = new FontData()
FontData balloon = new FontData()
FontData dialog = new FontData()
FontData widget = new FontData()
FontData news = new FontData()
Detailed Description
Definition at line 26 of file SkinManager.cs.
Member Data Documentation
balloon
FontData SkinManager.FontSet.balloon = new FontData()
Definition at line 32 of file SkinManager.cs.
Referenced by UIText.ApplySkin().
chatbox
FontData SkinManager.FontSet.chatbox = new FontData()
Definition at line 30 of file SkinManager.cs.
Referenced by UIText.ApplySkin().
dialog
FontData SkinManager.FontSet.dialog = new FontData()
Definition at line 34 of file SkinManager.cs.
Referenced by UIText.ApplySkin().
news
FontData SkinManager.FontSet.news = new FontData()
Definition at line 38 of file SkinManager.cs.
Referenced by UIText.ApplySkin().
ui
FontData SkinManager.FontSet.ui = new FontData()
Definition at line 28 of file SkinManager.cs.
Referenced by UIText.ApplySkin(), UiInputField.Awake(), UIInputText.Awake(), and Popper.SetText().
widget
FontData SkinManager.FontSet.widget = new FontData()
Definition at line 36 of file SkinManager.cs.
Referenced by UIText.ApplySkin().
The documentation for this class was generated from the following file:
Elin/Plugins.UI/SkinManager.cs