Elin Decompiled Documentation: SourceKeyItem Class Reference
SourceKeyItem Class Reference
Classes
class Row
Public Member Functions
override Row CreateRow ()
override Row CreateRowByMapping (IReadOnlyDictionary< string, int > mapping)
override void SetRow (Row r)
override IReadOnlyDictionary< string, int > GetRowMapping ()
override IReadOnlyDictionary< string, string > GetTypeMapping ()
Public Member Functions inherited from SourceDataInt< SourceKeyItem.Row >
override T GetRow (string id)
Static Public Attributes
static readonly IReadOnlyDictionary< string, int > RowMapping
static readonly IReadOnlyDictionary< string, string > TypeMapping
Detailed Description
Definition at line 4 of file SourceKeyItem.cs.
Member Function Documentation
CreateRow()
override Row SourceKeyItem.CreateRow () inline
Definition at line 52 of file SourceKeyItem.cs.
    {
        return new Row
        {
            id = SourceData.GetInt(0),
            alias = SourceData.GetString(1),
            name_JP = SourceData.GetString(2),
            name = SourceData.GetString(3),
            detail_JP = SourceData.GetString(4),
            detail = SourceData.GetString(5)
        };
    }
References SourceData< T, T2 >.GetInt(), and SourceData< T, T2 >.GetString().
CreateRowByMapping()
override Row SourceKeyItem.CreateRowByMapping (IReadOnlyDictionary< string, int > mapping) inline
Definition at line 65 of file SourceKeyItem.cs.
    {
        return new Row
        {
            id = SourceData.GetInt(mapping["id"]),
            alias = SourceData.GetString(mapping["alias"]),
            name_JP = SourceData.GetString(mapping["name_JP"]),
            name = SourceData.GetString(mapping["name"]),
            detail_JP = SourceData.GetString(mapping["detail_JP"]),
            detail = SourceData.GetString(mapping["detail"])
        };
    }
References SourceData< T, T2 >.GetInt(), and SourceData< T, T2 >.GetString().
GetRowMapping()
override IReadOnlyDictionary< string, int > SourceKeyItem.GetRowMapping () inline
Definition at line 83 of file SourceKeyItem.cs.
    {
        return RowMapping;
    }
References RowMapping.
GetTypeMapping()
override IReadOnlyDictionary< string, string > SourceKeyItem.GetTypeMapping () inline
Definition at line 88 of file SourceKeyItem.cs.
    {
        return TypeMapping;
    }
References TypeMapping.
SetRow()
override void SourceKeyItem.SetRow (Row r) inline
Definition at line 78 of file SourceKeyItem.cs.
    {
        map[r.id] = r;
    }
References SourceKeyItem.Row.id.
Member Data Documentation
RowMapping
readonly IReadOnlyDictionary<string, int> SourceKeyItem.RowMapping static
Initial value:
= new Dictionary<string, int>
    {
        ["id"] = 0,
        ["alias"] = 1,
        ["name_JP"] = 2,
        ["name"] = 3,
        ["detail_JP"] = 4,
        ["detail"] = 5
    }
Definition at line 32 of file SourceKeyItem.cs.
Referenced by GetRowMapping().
TypeMapping
readonly IReadOnlyDictionary<string, string> SourceKeyItem.TypeMapping static
Initial value:
= new Dictionary<string, string>
    {
        ["id"] = "int",
        ["alias"] = "string",
        ["name_JP"] = "string",
        ["name"] = "string",
        ["detail_JP"] = "string",
        ["detail"] = "string"
    }
Definition at line 42 of file SourceKeyItem.cs.
Referenced by GetTypeMapping().
The documentation for this class was generated from the following file:
Elin/SourceKeyItem.cs