Elin Decompiled Documentation: ContentCodex Class Reference
ContentCodex Class Reference
Public Member Functions
override void OnSwitchContent (int idTab)
void RefreshList ()
void RefreshInfo ()
void OnClickAddCards ()
void OnClickGetCard ()
Public Member Functions inherited from UIContent
virtual void OnSwitchContent (int idTab)
virtual void OnInstantiate ()
Public Member Functions inherited from UINote
void Clear ()
void Build ()
void Space (int sizeY=0, int sizeX=1)
UINote AddNote (string id)
UIItem AddHeader (string text, Sprite sprite=null)
UIItem AddHeaderCard (string text, Sprite sprite=null)
UIItem AddHeaderTopic (string text, Sprite sprite=null)
UIItem AddHeader (string id, string text, Sprite sprite=null)
UIItem AddText (string text, FontColor color=FontColor.DontChange)
UIItem AddText (string id, string text, FontColor color=FontColor.DontChange)
UIItem AddText (string id, string text, Color color)
UIItem AddItem (string id)
UIItem AddTopic (string id, string text, string value=null)
UIItem AddTopic (string text, string value=null)
void AddImage (Sprite sprite)
void AddImage (string idFile)
UIButton AddButton (string text, Action onClick)
UIButton AddButtonLink (string text, string url)
UIDropdown AddDropdown (string id="DropdownDefault")
UIButton AddToggle (string idLang="", bool isOn=false, Action< bool > action=null)
Transform AddPrefab (string path)
T AddExtra< T > (string path)
Static Public Member Functions
static void Collect (Thing t)
Public Attributes
UIDynamicList list
UIText textName
UIText textOwn
UIText textValue
UIText textKills
UIText textWeakspot
UIText textSpawns
UIText textBonus
UINote note
CodexCreature currentCodex
Transform transInfo
UIButton buttonTake
UIButton buttonAddCards
UIButton buttonToggleCollect
Vector2 pivot
Vector2 localPos
Public Attributes inherited from UINote
RectTransform target
UINoteProfile prof
SkinType skinType
string idDefaultText
LayoutGroup layout
RectTransform cur
bool extraRebuild
Detailed Description
Definition at line 5 of file ContentCodex.cs.
Member Function Documentation
Collect()
static void ContentCodex.Collect (Thing t) inline static
Definition at line 170 of file ContentCodex.cs.
    {
        EClass.player.codex.AddCard(t.c_idRefCard, t.Num);
        SE.Play("use_card");
        Msg.Say("addedCards", t.Num, t.Num.ToString() ?? "");
        t.Destroy();
    }
References CodexManager.AddCard(), Card.c_idRefCard, Player.codex, Card.Destroy(), Card.Num, EClass.player, and Msg.Say().
Referenced by Chara.Pick().
OnClickAddCards()
void ContentCodex.OnClickAddCards () inline
Definition at line 139 of file ContentCodex.cs.
    {
        List<Thing> list = EClass.pc.things.List((Thing c) => c.id == "figure3", onlyAccessible: true);
        int num = 0;
        if (list.Count > 0)
        {
            foreach (Thing item in list)
            {
                EClass.player.codex.AddCard(item.c_idRefCard, item.Num);
                num += item.Num;
                item.Destroy();
                RefreshList();
            }
            SE.Play("use_card");
            Msg.Say("addedCards", num, num.ToString() ?? "");
        }
        else
        {
            SE.BeepSmall();
            Msg.Say("noCard");
        }
        if (EClass.debug.enable)
        {
            foreach (SourceChara.Row row in EClass.sources.charas.rows)
            {
                EClass.player.codex.AddCard(row.id);
            }
        }
        RefreshInfo();
    }
References CodexManager.AddCard(), SourceManager.charas, Player.codex, EClass.debug, CoreDebug.enable, Card.id, item, list, ThingContainer.List(), EClass.pc, EClass.player, RefreshInfo(), RefreshList(), Msg.Say(), EClass.sources, and Card.things.
OnClickGetCard()
void ContentCodex.OnClickGetCard () inline
Definition at line 178 of file ContentCodex.cs.
    {
        currentCodex.numCard--;
        Thing thing = ThingGen.Create("figure3");
        thing.MakeFigureFrom(currentCodex.id);
        bool autoCollectCard = EClass.game.config.autoCollectCard;
        EClass.game.config.autoCollectCard = false;
        EClass.pc.Pick(thing);
        EClass.game.config.autoCollectCard = autoCollectCard;
        if (currentCodex.numCard == 0)
        {
            RefreshList();
            return;
        }
        list.Redraw();
        list.Select(currentCodex);
        RefreshInfo();
    }
References Game.Config.autoCollectCard, Game.config, ThingGen.Create(), currentCodex, EClass.game, CodexCreature.id, list, Card.MakeFigureFrom(), CodexCreature.numCard, EClass.pc, Chara.Pick(), UIDynamicList.Redraw(), RefreshInfo(), RefreshList(), and UIDynamicList.Select().
OnSwitchContent()
override void ContentCodex.OnSwitchContent (int idTab) inline virtual
Reimplemented from UIContent.
Definition at line 39 of file ContentCodex.cs.
    {
        if (list.isBuilt)
        {
            if (currentCodex != null)
            {
                list.Select(currentCodex);
                RefreshInfo();
            }
        }
        else
        {
            RefreshList();
            buttonToggleCollect.SetToggle(EClass.game.config.autoCollectCard, delegate(bool a)
            {
                EClass.game.config.autoCollectCard = a;
            });
        }
    }
References Game.Config.autoCollectCard, buttonToggleCollect, Game.config, currentCodex, EClass.game, BaseList.isBuilt, list, RefreshInfo(), RefreshList(), UIDynamicList.Select(), and UIButton.SetToggle().
RefreshInfo()
void ContentCodex.RefreshInfo () inline
Definition at line 113 of file ContentCodex.cs.
    {
        CodexCreature codexCreature = currentCodex;
        if (codexCreature != null)
        {
            UINote uINote = note;
            SourceChara.Row source = codexCreature.source;
            uINote.Clear();
            UIItem uIItem = uINote.AddHeader("HeaderCodex", codexCreature.Name.Replace("", Environment.NewLine + ""));
            int idSkin = ((EClass.core.config.game.antiSpider && codexCreature.source.skinAntiSpider != 0) ? codexCreature.source.skinAntiSpider : 0);
            codexCreature.SetImage(uIItem.image1, idSkin);
            uIItem.text2.text = "Lv." + source.LV + Environment.NewLine + EClass.sources.races.map[source.race].GetName().ToTitleCase(wholeText: true) + Environment.NewLine + EClass.sources.jobs.map[source.job].GetName().ToTitleCase(wholeText: true);
            uIItem.image1.rectTransform.pivot = pivot;
            uIItem.image1.rectTransform.localPosition = localPos;
            uIItem.image1.rectTransform.localScale = new Vector3(0f - uIItem.image1.transform.localScale.x, uIItem.image1.transform.localScale.y, 1f);
            uINote.Build();
            textOwn.text = codexCreature.numCard.ToString() ?? "";
            textValue.text = codexCreature.source.value.ToString() ?? "";
            textKills.text = codexCreature.kills.ToString() ?? "";
            textWeakspot.SetText((codexCreature.weakspot == 0) ? "undiscovered".lang() : "discovered".lang(codexCreature.weakspot.ToString() ?? ""), (codexCreature.weakspot == 0) ? FontColor.Default : FontColor.Good);
            textSpawns.text = codexCreature.spawns.ToString() ?? "";
            textBonus.text = codexCreature.GetTextBonus();
            currentCodex = codexCreature;
        }
    }
References UINote.AddHeader(), UINote.Build(), UINote.Clear(), currentCodex, CodexCreature.GetTextBonus(), UIItem.image1, SourceChara.Row.job, SourceManager.jobs, CodexCreature.kills, localPos, CodexCreature.Name, note, CodexCreature.numCard, pivot, SourceChara.Row.race, SourceManager.races, CodexCreature.SetImage(), UIText.SetText(), CodexCreature.source, EClass.sources, CodexCreature.spawns, textWeakspot, and CodexCreature.weakspot.
Referenced by OnClickAddCards(), OnClickGetCard(), OnSwitchContent(), and RefreshList().
RefreshList()
void ContentCodex.RefreshList () inline
Definition at line 59 of file ContentCodex.cs.
    {
        currentCodex = null;
        list.Clear();
        list.callbacks = new UIList.Callback<CodexCreature, ButtonGrid>
        {
            onClick = delegate(CodexCreature a, ButtonGrid b)
            {
                currentCodex = a;
                RefreshInfo();
                list.Select(a);
            },
            onRedraw = delegate(CodexCreature a, ButtonGrid b, int i)
            {
                b.refObj = a.source;
                b.mainText.SetText(a.Name);
                b.subText.text = a.numCard.ToString() ?? "";
                b.subText2.SetText(a.source._id + ".");
                if (EClass.core.uiScale < 1.2f)
                {
                    b.icon.transform.localScale = new Vector3(1f / EClass.core.uiScale, 1f / EClass.core.uiScale, 1f);
                }
                int idSkin = ((EClass.core.config.game.antiSpider && a.source.skinAntiSpider != 0) ? a.source.skinAntiSpider : 0);
                a.SetImage(b.icon, idSkin);
            },
            onList = delegate
            {
                List<CodexCreature> list = new List<CodexCreature>();
                foreach (KeyValuePair<string, CodexCreature> creature in EClass.player.codex.creatures)
                {
                    if (creature.Value.numCard > 0 && EClass.sources.charas.map.ContainsKey(creature.Value.id))
                    {
                        list.Add(creature.Value);
                    }
                }
                list.Sort((CodexCreature a, CodexCreature b) => a.source._id - b.source._id);
                foreach (CodexCreature item in list)
                {
                    this.list.Add(item);
                }
            }
        };
        list.List();
        bool flag = list.objects.Count > 0;
        if (flag)
        {
            list.dsv.scrollByItemIndex(0);
            list.Select(list.objects[0], invoke: true);
            currentCodex = list.objects[0] as CodexCreature;
        }
        transInfo.SetActive(flag);
        buttonTake.SetActive(flag);
    }
References UIDynamicList.Add(), buttonTake, SourceManager.charas, UIDynamicList.Clear(), Player.codex, EClass.core, CodexManager.creatures, currentCodex, UIDynamicList.dsv, UIButton.icon, item, list, UIDynamicList.List(), UIButton.mainText, CodexCreature.Name, CodexCreature.numCard, UIDynamicList.objects, EClass.player, RefreshInfo(), UIDynamicList.Select(), CodexCreature.SetImage(), UIText.SetText(), CodexCreature.source, EClass.sources, UIButton.subText2, transInfo, and Core.uiScale.
Referenced by OnClickAddCards(), OnClickGetCard(), and OnSwitchContent().
Member Data Documentation
buttonAddCards
UIButton ContentCodex.buttonAddCards
Definition at line 31 of file ContentCodex.cs.
buttonTake
UIButton ContentCodex.buttonTake
Definition at line 29 of file ContentCodex.cs.
Referenced by RefreshList().
buttonToggleCollect
UIButton ContentCodex.buttonToggleCollect
Definition at line 33 of file ContentCodex.cs.
Referenced by OnSwitchContent().
currentCodex
CodexCreature ContentCodex.currentCodex
Definition at line 25 of file ContentCodex.cs.
Referenced by OnClickGetCard(), OnSwitchContent(), RefreshInfo(), and RefreshList().
list
UIDynamicList ContentCodex.list
Definition at line 7 of file ContentCodex.cs.
Referenced by OnClickAddCards(), OnClickGetCard(), OnSwitchContent(), and RefreshList().
localPos
Vector2 ContentCodex.localPos
Definition at line 37 of file ContentCodex.cs.
Referenced by RefreshInfo().
note
UINote ContentCodex.note
Definition at line 23 of file ContentCodex.cs.
Referenced by RefreshInfo().
pivot
Vector2 ContentCodex.pivot
Definition at line 35 of file ContentCodex.cs.
Referenced by RefreshInfo().
textBonus
UIText ContentCodex.textBonus
Definition at line 21 of file ContentCodex.cs.
textKills
UIText ContentCodex.textKills
Definition at line 15 of file ContentCodex.cs.
textName
UIText ContentCodex.textName
Definition at line 9 of file ContentCodex.cs.
textOwn
UIText ContentCodex.textOwn
Definition at line 11 of file ContentCodex.cs.
textSpawns
UIText ContentCodex.textSpawns
Definition at line 19 of file ContentCodex.cs.
textValue
UIText ContentCodex.textValue
Definition at line 13 of file ContentCodex.cs.
textWeakspot
UIText ContentCodex.textWeakspot
Definition at line 17 of file ContentCodex.cs.
Referenced by RefreshInfo().
transInfo
Transform ContentCodex.transInfo
Definition at line 27 of file ContentCodex.cs.
Referenced by RefreshList().
The documentation for this class was generated from the following file:
Elin/ContentCodex.cs