Elin Decompiled Documentation: SpatialManager Class Reference
SpatialManager Class Reference
Classes
class GlobalSpatialList
Public Member Functions
void AssignUID (Spatial s)
void Remove (Spatial s)
T Find< T > (Func< T, bool > func)
Zone Find (string id)
Zone Find (int uid)
List< Zone > ListReturnLocations ()
Public Attributes
SpatialManager.GlobalSpatialList map = new SpatialManager.GlobalSpatialList()
int uidNext = 1
RankedZoneManager ranks = new RankedZoneManager()
List< Spatial > listDestryoed = new List<Spatial>()
Properties
Zone Somewhere [get]
List< Zone > Zones [get]
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Additional Inherited Members
Static Public Member Functions inherited from EClass
static int rnd (int a)
static int curve (int a, int start, int step, int rate=75)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Static Public Attributes inherited from EClass
static Core core
Detailed Description
Definition at line 6 of file SpatialManager.cs.
Member Function Documentation
AssignUID()
void SpatialManager.AssignUID (Spatial s) inline
Definition at line 16 of file SpatialManager.cs.
    {
        s.uid = this.uidNext;
        this.uidNext++;
        this.map.Add(s);
    }
References map, and uidNext.
Referenced by Spatial.Register().
Find() [1/2]
Zone SpatialManager.Find (int uid) inline
Definition at line 58 of file SpatialManager.cs.
    {
        return this.map.TryGetValue(uid, null) as Zone;
    }
References map.
Find() [2/2]
Zone SpatialManager.Find (string id) inline
Definition at line 46 of file SpatialManager.cs.
    {
        foreach (Spatial spatial in this.map.Values)
        {
            if (spatial is Zone && spatial.id == id)
            {
                return spatial as Zone;
            }
        }
        return null;
    }
References Spatial.id, and map.
Referenced by TeleportManager.GetTeleportZone(), TraitMoongate.LoadMap(), Chara.MoveZone(), Chara.OnBanish(), Trait.OnBarter(), Meeting.OnEndDrama(), ZoneInstanceBout.OnLeaveZone(), Game.OnLoad(), Scene.OnUpdate(), CoreDebug.QuickStart(), LayerShippingResult.Refresh(), WindowChara.RefreshProfile(), Meeting.SetChara(), TraitTicketFurniture.SetZone(), GameDate.ShipGoods(), LayerShippingResult.Show(), Game.StartNewGame(), and GameUpdater.Update().
Find< T >()
T SpatialManager.Find< T > (Func< T, bool > func) inline
Type Constraints
T : Zone
Definition at line 33 of file SpatialManager.cs.
                                                 : Zone
    {
        foreach (Spatial spatial in this.map.Values)
        {
            T t = spatial as T;
            if (t != null && func(t))
            {
                return t;
            }
        }
        return default(T);
    }
References map.
ListReturnLocations()
List< Zone > SpatialManager.ListReturnLocations () inline
Definition at line 63 of file SpatialManager.cs.
    {
        if (EClass.debug.returnAnywhere)
        {
            List<Zone> list = (from Zone a in
                from a in this.map.Values
                where a is Zone
                select a
            where a != EClass._zone && (a.IsReturnLocation || a.IsPCFaction || (!(a is Zone_Field) && !a.IsInstance && !a.isRandomSite)) && a.parent == EClass.world.region && !a.source.tag.Contains("closed")
            select a).ToList<Zone>();
            list.Sort((Zone a, Zone b) => a.GetSortVal() - b.GetSortVal());
            return list;
        }
        List<Zone> list2 = (from Zone a in
            from a in this.map.Values
            where a is Zone
            select a
        where a != EClass._zone && a.IsReturnLocation && a.GetTopZone().visitCount > 0 && (a.GetTopZone().FindDeepestZone() == a || EClass.pc.homeZone == a)
        select a).ToList<Zone>();
        list2.Sort((Zone a, Zone b) => a.GetSortVal() - b.GetSortVal());
        return list2;
    }
References EClass.debug, Zone.GetSortVal(), Zone.GetTopZone(), Spatial.parent, World.region, CoreDebug.returnAnywhere, Spatial.source, Spatial.visitCount, and EClass.world.
Referenced by AM_Adv._OnUpdateInput(), and ActEffect.Proc().
Remove()
void SpatialManager.Remove (Spatial s) inline
Definition at line 23 of file SpatialManager.cs.
    {
        if (s.parent != null)
        {
            s.parent.children.Remove(s);
        }
        this.map.Remove(s.uid);
        this.listDestryoed.Add(s);
    }
References Spatial.children, listDestryoed, map, Spatial.parent, Remove(), and Spatial.uid.
Referenced by Zone.Destroy(), and Remove().
Member Data Documentation
listDestryoed
List<Spatial> SpatialManager.listDestryoed = new List<Spatial>()
Definition at line 105 of file SpatialManager.cs.
Referenced by Remove().
map
SpatialManager.GlobalSpatialList SpatialManager.map = new SpatialManager.GlobalSpatialList()
Definition at line 97 of file SpatialManager.cs.
Referenced by AssignUID(), Faction.CountTerritories(), ThingGen.CreateCardboardBox(), Find(), Find< T >(), RefZone.Get(), Faction.GetChildren(), RankedZoneManager.GetList(), Region.ListTowns(), Chara.OnBanish(), ContentFaction.RefreshZones(), LayerFactions.RefreshZones(), LayerLocation.RefreshZones(), Remove(), GameIO.SaveGame(), Chara.Tick(), and TraitMapBoard.TrySetAct().
ranks
RankedZoneManager SpatialManager.ranks = new RankedZoneManager()
Definition at line 103 of file SpatialManager.cs.
Referenced by Faction.GetRankIncome(), ContentHomeRanking.Refresh(), UIHomeInfo.RefreshInfo(), UIFactionInfo.SetZone(), and HomeResourceWorth.UpdateRank().
uidNext
int SpatialManager.uidNext = 1
Definition at line 100 of file SpatialManager.cs.
Referenced by AssignUID().
Property Documentation
Somewhere
Zone SpatialManager.Somewhere get
Definition at line 8 of file SpatialManager.cs.
    {
        get
        {
            return this.Find("somewhere");
        }
    }
Zones
List<Zone> SpatialManager.Zones get
Definition at line 86 of file SpatialManager.cs.
    {
        get
        {
            return (from a in this.map.Values
            where a is Zone
            select a).Cast<Zone>().ToList<Zone>();
        }
    }
Referenced by Quest.ListDeliver(), Region.ListTravelZones(), Region.ListZonesInRadius(), and LayerMapList.RefreshList().
The documentation for this class was generated from the following file:
Elin/SpatialManager.cs