Elin Decompiled Documentation: CharaMassTransfer Class Reference
CharaMassTransfer Class Reference
Public Member Functions
void Add (Chara c)
void Restore ()
Public Attributes
List< CharaOriginalPositionData > list = new List<CharaOriginalPositionData>()
Additional Inherited Members
Static Public Member Functions inherited from EClass
static int rndSeed (int a, int seed)
static int rnd (long a)
static int rnd (int a)
static int curve (long _a, int start, int step, int rate=75)
static int sqrt (int a)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Static Public Attributes inherited from EClass
static Core core
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Detailed Description
Definition at line 4 of file CharaMassTransfer.cs.
Member Function Documentation
Add()
void CharaMassTransfer.Add (Chara c) inline
Definition at line 9 of file CharaMassTransfer.cs.
    {
        CharaOriginalPositionData item = new CharaOriginalPositionData
        {
            uid = c.uid,
            uidZone = c.currentZone.uid,
            x = c.pos.x,
            z = c.pos.z,
            noMove = c.noMove
        };
        list.Add(item);
    }
References Chara.currentZone, item, list, Card.pos, Card.uid, Spatial.uid, Point.x, and Point.z.
Referenced by ZoneEventWedding.OnVisit().
Restore()
void CharaMassTransfer.Restore () inline
Definition at line 22 of file CharaMassTransfer.cs.
    {
        foreach (CharaOriginalPositionData item in list)
        {
            Chara chara = EClass.game.cards.globalCharas.Find(item.uid);
            if (chara != null)
            {
                chara.MoveZone(EClass.game.spatials.Find(item.uidZone), new ZoneTransition
                {
                    state = ZoneTransition.EnterState.Exact,
                    x = item.x,
                    z = item.z
                });
                chara.pos.x = item.x;
                chara.pos.z = item.z;
                chara.noMove = item.noMove;
            }
        }
    }
References Game.cards, CardManager.GlobalCharaList.Find(), SpatialManager.Find(), EClass.game, CardManager.globalCharas, item, list, Chara.MoveZone(), and Game.spatials.
Referenced by ZoneEventWedding.OnLeaveZone().
Member Data Documentation
list
List<CharaOriginalPositionData> CharaMassTransfer.list = new List<CharaOriginalPositionData>()
Definition at line 7 of file CharaMassTransfer.cs.
Referenced by Add(), and Restore().
The documentation for this class was generated from the following file:
Elin/CharaMassTransfer.cs