Elin Decompiled Documentation: LayerSleep Class Reference
LayerSleep Class Reference
Public Member Functions
override void OnAfterInit ()
void Wait (float duration=5f)
void Sleep (int _hours, Thing _bed, Thing _pillow=null)
void Advance ()
Public Member Functions inherited from ELayer
override void OnBeforeAddLayer ()
void InitInspector ()
sealed override void Init ()
override void OnAfterAddLayer ()
void TryShowHelp ()
void AddLayerToUI (string id)
void TryShowHint (string _langHint=null)
void TalkHomeMemeber (string id)
void TalkMaid (string id)
override void OnRightClick ()
Public Attributes
float repeatRate
float coverAlpha
float coverShow
float coverHide
float hideDelay
Private Attributes
int hours
int min
int maxMin
Thing bed
Thing pillow
Additional Inherited Members
Static Public Member Functions inherited from ELayer
static int rnd (int a)
Protected Member Functions inherited from ELayer
sealed override void _Close ()
sealed override void Kill ()
Properties inherited from ELayer
static Core core [get]
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static FactionBranch Branch [get]
static Faction Home [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static CoreConfig config [get]
static GameSetting setting [get]
static ColorProfile Colors [get]
static SourceManager sources [get]
static World world [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
bool IsFloat [get]
virtual string IdHelp [get]
Detailed Description
Definition at line 1 of file LayerSleep.cs.
Member Function Documentation
Advance()
void LayerSleep.Advance () inline
Definition at line 52 of file LayerSleep.cs.
    {
        if (min > maxMin)
        {
            CancelInvoke();
            if (!ELayer._zone.IsInstance && (ELayer._zone.IsPCFaction || ELayer._zone is Zone_Field || ELayer._zone.IsRegion))
            {
                ELayer.player.SimulateFaction();
            }
            foreach (Chara member in ELayer.pc.party.members)
            {
                member.OnSleep(bed);
            }
            Msg.Say("slept", hours.ToString() ?? "");
            if (pillow != null && pillow.trait is TraitPillowOpatos)
            {
                ELayer.world.region.RenewRandomSites();
            }
            if (!ELayer.debug.ignoreAutoSave)
            {
                ELayer.game.Save();
            }
            if (ELayer._zone.IsRegion)
            {
                ELayer._zone.Region.UpdateRandomSites();
            }
            ELayer.ui.ShowCover();
            TweenUtil.Delay(hideDelay, delegate
            {
                ELayer.ui.HideCover(coverHide, delegate
                {
                    Close();
                });
            });
        }
        else
        {
            min += 10;
            ELayer.world.date.AdvanceMin(10);
        }
    }
References ELayer._zone, GameDate.AdvanceMin(), bed, coverHide, World.date, ELayer.debug, ELayer.game, UI.HideCover(), hideDelay, hours, CoreDebug.ignoreAutoSave, Zone.IsInstance, Zone.IsPCFaction, Spatial.IsRegion, maxMin, Party.members, min, Chara.OnSleep(), Chara.party, ELayer.pc, pillow, ELayer.player, World.region, Zone.Region, Region.RenewRandomSites(), Game.Save(), Msg.Say(), UI.ShowCover(), Player.SimulateFaction(), Card.trait, ELayer.ui, Region.UpdateRandomSites(), and ELayer.world.
OnAfterInit()
override void LayerSleep.OnAfterInit () inline
Definition at line 23 of file LayerSleep.cs.
    {
        ELayer.ui.ShowCover(coverShow, coverAlpha);
    }
References coverAlpha, coverShow, UI.ShowCover(), and ELayer.ui.
Sleep()
void LayerSleep.Sleep (int _hours, Thing _bed, Thing _pillow = null) inline
Definition at line 40 of file LayerSleep.cs.
    {
        ELayer.Sound.Play("jingle_sleep");
        hours = _hours;
        bed = _bed;
        pillow = _pillow;
        maxMin = hours * 60;
        InvokeRepeating("Advance", repeatRate, repeatRate);
        ELayer.pc.faith.Revelation("sleep");
        ELayer.player.stats.slept++;
    }
References bed, Chara.faith, hours, maxMin, ELayer.pc, pillow, ELayer.player, repeatRate, Religion.Revelation(), Player.Stats.slept, ELayer.Sound, and Player.stats.
Wait()
void LayerSleep.Wait (float duration = 5f) inline
Definition at line 28 of file LayerSleep.cs.
    {
        ELayer.Sound.Play("jingle_sleep");
        TweenUtil.Tween(duration, null, delegate
        {
            ELayer.ui.HideCover(coverHide, delegate
            {
                Close();
            });
        });
    }
References coverHide, UI.HideCover(), ELayer.Sound, and ELayer.ui.
Member Data Documentation
bed
Thing LayerSleep.bed private
Definition at line 19 of file LayerSleep.cs.
Referenced by Advance(), and Sleep().
coverAlpha
float LayerSleep.coverAlpha
Definition at line 5 of file LayerSleep.cs.
Referenced by OnAfterInit().
coverHide
float LayerSleep.coverHide
Definition at line 9 of file LayerSleep.cs.
Referenced by Advance(), and Wait().
coverShow
float LayerSleep.coverShow
Definition at line 7 of file LayerSleep.cs.
Referenced by OnAfterInit().
hideDelay
float LayerSleep.hideDelay
Definition at line 11 of file LayerSleep.cs.
Referenced by Advance().
hours
int LayerSleep.hours private
Definition at line 13 of file LayerSleep.cs.
Referenced by Advance(), and Sleep().
maxMin
int LayerSleep.maxMin private
Definition at line 17 of file LayerSleep.cs.
Referenced by Advance(), and Sleep().
min
int LayerSleep.min private
Definition at line 15 of file LayerSleep.cs.
Referenced by Advance().
pillow
Thing LayerSleep.pillow private
Definition at line 21 of file LayerSleep.cs.
Referenced by Advance(), and Sleep().
repeatRate
float LayerSleep.repeatRate
Definition at line 3 of file LayerSleep.cs.
Referenced by Sleep().
The documentation for this class was generated from the following file:
Elin/LayerSleep.cs