Elin Decompiled Documentation: Region Class Reference
Region Class Reference
Public Member Functions
override void OnActivate ()
void CheckRandomSites ()
void RenewRandomSites ()
void UpdateRandomSites ()
void InitElomap ()
Zone CreateRandomSite (Zone center, int radius=8, string idSource=null, bool updateMesh=true, int lv=0)
SourceZone.Row GetRandomSiteSource ()
Point GetRandomPoint ()
Point GetRandomPoint (int orgX, int orgY, int radius=8, bool increaseRadius=false)
Point GetRandomPoint (int orgX, int orgY, int minRadius, int maxRadius)
bool CanCreateZone (Point pos)
Zone CreateZone (Point pos)
List< Zone > ListTowns ()
Zone GetRandomTown ()
List< Zone > ListRandomSites ()
List< Zone > ListZonesInRadius (Zone center, int radius=10)
List< Zone > ListTravelZones (int radius=100)
override void OnAdvanceHour ()
List< Chara > ListMobs ()
Public Member Functions inherited from Zone
int Evalue (int ele)
int Evalue (string alias)
virtual string GetDungenID ()
virtual string GetNewZoneID (int level)
override string ToString ()
string TextLevel (int _lv)
override void OnCreate ()
override void OnAfterCreate ()
void Activate ()
void RefreshHat ()
void OnVisit ()
void Revive ()
virtual void OnRegenerate ()
virtual void OnActivate ()
virtual void OnBeforeDeactivate ()
virtual void OnDeactivate ()
virtual void OnBeforeSimulate ()
virtual void OnVisitNewMapOrRegenerate ()
virtual void OnAfterSimulate ()
virtual void OnAdvanceHour ()
void Simulate ()
Point GetSpawnPos (Chara c, ZoneTransition.EnterState destState=ZoneTransition.EnterState.Auto)
Point GetRandomVisitPos (Chara c)
void AddGlobalCharasOnActivate ()
void Deactivate ()
void OnKillGame ()
void UnloadMap ()
void ClaimZone (bool debug=false)
void AbandonZone ()
bool CanDestroy ()
override void _OnBeforeSave ()
override void OnLoad ()
override void Destroy ()
void ClearZones (Zone current=null)
void OnChildNumChange (Card c)
ICardParent GetRoot ()
Zone GetTopZone ()
Card AddCardSplinkle (Card t, Point center, int radius=4)
Card AddChara (string id, int x, int z)
Card AddThing (string id, int x, int z)
Card AddThing (string id, Point p)
Card AddCard (Card t, Point point)
Card AddCard (Card t)
Card AddCard (Card t, int x, int z)
void RemoveCard (Card t)
T GetRandomSpot< T > ()
bool TryAddThingInSpot< T > (Thing t, bool useContainer=true)
List< Thing > TryListThingsInSpot< T > (Func< Thing, bool > func=null)
bool TryAddThingInSharedContainer (Thing t, List< Thing > containers=null, bool add=true, bool msg=false, Chara chara=null, bool sharedOnly=true)
bool TryAddThing (Thing target, Point p, bool destroyIfFail=false)
Thing TryGetThingFromSharedContainer (Func< Thing, bool > func)
Thing TryGetRestock< T > (string idCat)
ZoneProfile GetProfile ()
void CreateBP ()
virtual void OnCreateBP ()
void Generate ()
void TrySpawnFollower ()
void SpawnAltar ()
virtual void OnGenerateMap ()
void TryGenerateOre ()
Chara TryGenerateEvolved (bool force=false, Point p=null)
void TryGenerateBigDaddy ()
void TryGenerateShrine ()
void ResetHostility ()
virtual void OnGenerateRooms (BaseMapGen gen)
Point GetSpawnPos (SpawnPosition type, int tries=100)
Chara SpawnMob (Point pos=null, SpawnSetting setting=null)
void RefreshElectricity ()
int GetElectricity (bool cost=false)
void SetBGM (List< int > ids, bool refresh=true)
void SetBGM (int id=-1, bool refresh=true)
void RefreshPlaylist ()
void RefreshBGM ()
Playlist CreatePlaylist (ref List< int > list, Playlist mold=null)
Chara FindChara (string id)
Chara FindChara (int uid)
int GetDeepestLv ()
int GetDeepestLv (ref int max)
List< Element > ListLandFeats ()
ZoneExportData Import (string path)
void Export (string path, PartialMap partial=null, bool usermap=false)
void ExportDialog (string dir=null)
void ImportDialog (string dir=null)
void Export ()
void WriteNote (UINote n, Action< UINote > onWriteNote=null, IInspect.NoteMode mode=IInspect.NoteMode.Default, Recipe recipe=null)
void OnInspect ()
int GetSortVal ()
Chara AddRandomVisitor (bool guest=false)
void OnSimulateHour (VirtualDate date)
void OnSimulateDay (VirtualDate date)
void OnSimulateMonth (VirtualDate date)
void RainWater ()
void GrowPlants (VirtualDate date)
Zone GetZoneAt (int _x, int _y)
bool IsCrime (Chara c, Act act)
void RefreshCriminal ()
void RefreshListCitizen ()
void ModInfluence (int a)
void ModDevelopment (int a)
void UpdateQuests (bool force=false)
List< Chara > ListMinions (Chara c)
int CountMinions (Chara c)
int GetSoilCost ()
void SpawnLostItems ()
void ApplyBackerPet (bool draw)
FortuneRollData GetOrCreateFortuneRollData (bool refresh=true)
Public Member Functions inherited from Spatial
int GetInt (int id, int? defaultInt=null)
void AddInt (int id, int value)
void SetInt (int id, int value=0)
override string ToString ()
void Create (string _id, int _x, int _y, int _icon)
void Register ()
virtual void OnCreate ()
virtual void OnAfterCreate ()
virtual void SetMainFaction (Faction f)
Zone GetFirstZone ()
void OnBeforeSave ()
virtual void _OnBeforeSave ()
void _OnLoad ()
virtual void OnLoad ()
virtual void Destroy ()
void DeleteMapRecursive ()
virtual void AddChild (Spatial child)
void RemoveChild (Spatial child)
Zone FindDeepestZone ()
Zone FindZone (int lv)
Zone FindZone (string _id)
virtual bool CanKill ()
int Dist (Point p)
int Dist (Spatial s)
void MakeGameObject (GameObject parentGo)
ICardParent GetRoot ()
void RemoveCard (Card c)
void OnChildNumChange (Card c)
void WriteNote (UINote n, Action< UINote > onWriteNote=null, NoteMode mode=NoteMode.Default, Recipe recipe=null)
void OnInspect ()
Public Attributes
EloMap elomap = new EloMap()
int dateCheckSites
Public Attributes inherited from Zone
FactionBranch branch
HashSet< int > completedQuests = new HashSet<int>()
ZoneEventManager events = new ZoneEventManager()
ElementContainerZone elements = new ElementContainerZone()
MapBounds bounds
Dictionary< int, string > dictCitizen = new Dictionary<int, string>()
ZoneInstance instance
List< int > landFeats
Map map
MapSubset subset
ZoneBlueprint bp
int fileVariation
bool dirtyElectricity
bool isStarted
bool isSimulating
int tempDist
BiomeProfile _biome
Public Attributes inherited from Spatial
Spatial parent
string id
string idUser
string name
string idMainFaction
string idProfile
string idCurrentSubset
string idHat
int[] _ints = new int[30]
List< Spatial > children = new List<Spatial>()
List< Spatial > connections = new List<Spatial>()
Dictionary< int, int > mapInt = new Dictionary<int, int>()
bool destryoed
bool isImported
BitArray32 bits
Properties
override bool WillAutoSave [get]
override ActionMode DefaultActionMode [get]
override bool IsRegion [get]
override int DangerLv [get]
override bool BlockBorderExit [get]
override Point RegionPos [get]
Properties inherited from Zone
Chara Boss [get, set]
override int ContentLv [get]
override int DangerLv [get]
virtual bool DisableRooms [get]
int HourSinceLastActive [get]
int MinsSinceLastActive [get]
virtual string pathExport [get]
BiomeProfile biome [get]
virtual string IdBiome [get]
virtual string IDGenerator [get]
virtual string TextWidgetDate [get]
MapGenerator Generator [get]
virtual string IdProfile [get]
virtual string IDPlayList [get]
virtual string IDPlaylistOverwrite [get]
virtual string IDHat [get]
virtual string IDBaseLandFeat [get]
virtual string idExport [get]
string pathTemp [get]
Region Region [get]
Zone ParentZone [get]
virtual ActionMode DefaultActionMode [get]
virtual bool BlockBorderExit [get]
virtual int ExpireDays [get]
virtual ZoneTransition.EnterState RegionEnterState [get]
virtual ZoneFeatureType FeatureType [get]
virtual string IDAmbience [get]
virtual string IDSceneTemplate [get]
virtual bool IsFestival [get]
virtual string IDSubset [get]
virtual bool IsTown [get]
virtual bool CanBeDeliverDestination [get]
virtual bool CountDeepestLevel [get]
virtual bool HasLaw [get]
virtual bool MakeEnemiesNeutral [get]
virtual bool MakeTownProperties [get]
virtual bool AllowCriminal [get]
virtual bool AllowInvest [get]
virtual bool AllowNewZone [get]
virtual bool WillAutoSave [get]
virtual bool RegenerateOnEnter [get]
virtual bool IsSkyLevel [get]
virtual bool IsUserZone [get]
virtual bool CanDigUnderground [get]
virtual bool LockExit [get]
virtual bool CanUnlockExit [get]
virtual int MaxLv [get]
virtual int MinLv [get]
virtual bool AddPrefix [get]
virtual bool IsNefia [get]
virtual bool PetFollow [get]
virtual bool RestrictBuild [get]
virtual bool KeepAllyDistance [get]
virtual int MaxSpawn [get]
int MaxRespawn [get]
virtual float RuinChance [get]
virtual float OreChance [get]
virtual float BigDaddyChance [get]
virtual float EvolvedChance [get]
virtual float ShrineChance [get]
virtual float PrespawnRate [get]
virtual float RespawnRate [get]
bool ShowEnemyOnMinimap [get]
virtual int RespawnPerHour [get]
virtual float ChanceSpawnNeutral [get]
virtual bool GrowPlant [get]
virtual bool GrowWeed [get]
virtual bool IsExplorable [get]
virtual bool IsReturnLocation [get]
virtual bool ShouldMakeExit [get]
virtual bool ShouldRegenerate [get]
virtual bool ShouldAutoRevive [get]
virtual bool UseFog [get]
virtual bool RevealRoom [get]
virtual bool AlwaysLowblock [get]
virtual bool UseLight [get]
virtual int StartLV [get]
virtual bool ScaleMonsterLevel [get]
virtual bool HiddenInRegionMap [get]
virtual FlockController.SpawnType FlockType [get]
override string NameSuffix [get]
string NameWithLevel [get]
string TextDeepestLv [get]
bool CanEnterBuildMode [get]
bool CanEnterBuildModeAnywhere [get]
bool IsPCFaction [get]
bool IsStartZone [get]
bool IsInstance [get]
bool IsLoaded [get]
virtual int BaseElectricity [get]
bool IsActiveZone [get]
bool CanInspect [get]
string InspectName [get]
Point InspectPoint [get]
Vector3 InspectPosition [get]
virtual int MaxSoil [get]
Properties inherited from Spatial
int _bits [get, set]
int uid [get, set]
int icon [get, set]
int x [get, set]
int y [get, set]
int lastActive [get, set]
int idPrefix [get, set]
int lv [get, set]
int visitCount [get, set]
int dateExpire [get, set]
int dateRevive [get, set]
int _dangerLv [get, set]
int dateRegenerate [get, set]
int influence [get, set]
int investment [get, set]
int development [get, set]
int electricity [get, set]
int dateHat [get, set]
int uidBoss [get, set]
int dateQuest [get, set]
int version [get, set]
bool isGenerated [get, set]
bool isShore [get, set]
bool isRandomSite [get, set]
bool isKnown [get, set]
bool isMapSaved [get, set]
bool isExternalZone [get, set]
bool isConquered [get, set]
bool isBeach [get, set]
bool isPeace [get, set]
bool isDeathLocation [get, set]
Faction mainFaction [get, set]
SourceZone.Row source [get]
bool IsPlayerFaction [get]
bool IsClosed [get]
int mapX [get]
int mapY [get]
virtual int ContentLv [get]
virtual int DangerLv [get]
virtual int DangerLvFix [get]
virtual float VolumeSea [get]
virtual bool ShowDangerLv [get]
virtual bool CanSpawnAdv [get]
string pathSave [get]
virtual string Name [get]
string NameWithDangerLevel [get]
virtual string NameSuffix [get]
virtual bool IsRegion [get]
virtual bool CanFastTravel [get]
EloMap.TileInfo Tile [get]
virtual bool IsSnowZone [get]
virtual bool IsSnowCovered [get]
virtual Point RegionPos [get]
virtual bool isClaimable [get]
int Seed [get]
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Properties inherited from IInspect
bool CanInspect [get]
string InspectName [get]
Point InspectPoint [get]
Vector3 InspectPosition [get]
Private Member Functions
Zone CreateRandomSite (Point pos, string idSource, bool updateMesh, int lv=0)
Additional Inherited Members
Public Types inherited from IInspect
enum NoteMode { Default , Recipe , Product , Info }
Static Public Member Functions inherited from Zone
static bool IsImportValid (string path)
Static Public Member Functions inherited from EClass
static int rnd (int a)
static int curve (int a, int start, int step, int rate=75)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Static Public Attributes inherited from Zone
static bool forceRegenerate
static string forceSubset
static CardRow sourceHat
static int okaerinko = 0
static bool ignoreSpawnAnime
static List< Thing > Suckers = new List<Thing>()
Static Public Attributes inherited from EClass
static Core core
Protected Member Functions inherited from Spatial
Zone _FindZone (string _id)
Protected Attributes inherited from Spatial
Point _regionPos = new Point()
Detailed Description
Definition at line 6 of file Region.cs.
Member Function Documentation
CanCreateZone()
bool Region.CanCreateZone (Point pos) inline
Definition at line 215 of file Region.cs.
    {
        EClass.scene.elomapActor.Initialize(EClass.world.region.elomap);
        EloMap.TileInfo tileInfo = EClass.scene.elomapActor.elomap.GetTileInfo(pos.x, pos.z);
        if (!tileInfo.idZoneProfile.IsEmpty())
        {
            return !tileInfo.blocked;
        }
        return false;
    }
References EloMap.TileInfo.blocked, EloMapActor.elomap, elomap, Scene.elomapActor, EloMap.GetTileInfo(), EloMap.TileInfo.idZoneProfile, EloMapActor.Initialize(), World.region, EClass.scene, EClass.world, Point.x, and Point.z.
Referenced by Player.EnterLocalZone().
CheckRandomSites()
void Region.CheckRandomSites () inline
Definition at line 53 of file Region.cs.
    {
        if (EClass.world.date.IsExpired(dateCheckSites))
        {
            dateCheckSites = EClass.world.date.GetRaw() + 1440;
            UpdateRandomSites();
        }
        if (FindZone("foxtown_nefu") == null)
        {
            SpatialGen.Create("foxtown_nefu", this, register: true);
        }
        if (FindZone("little_garden") == null)
        {
            SpatialGen.Create("little_garden", this, register: true);
        }
        if (FindZone("cave_yeek") == null)
        {
            SpatialGen.Create("cave_yeek", this, register: true);
        }
        elomap.objmap.UpdateMeshImmediate();
    }
References SpatialGen.Create(), World.date, dateCheckSites, elomap, Spatial.FindZone(), Date.GetRaw(), Date.IsExpired(), EloMap.objmap, UpdateRandomSites(), and EClass.world.
Referenced by GameDate.AdvanceHour(), and OnActivate().
CreateRandomSite() [1/2]
Zone Region.CreateRandomSite (Point pos, string idSource, bool updateMesh, int lv = 0) inline private
Definition at line 110 of file Region.cs.
    {
        if (pos == null)
        {
            return null;
        }
        if (idSource.IsEmpty())
        {
            idSource = GetRandomSiteSource().id;
        }
        Zone zone = SpatialGen.Create(idSource, this, register: true, pos.x, pos.z) as Zone;
        if (lv <= 0)
        {
            if (EClass.player.CountKeyItem("license_adv") == 0 && !EClass.debug.enable)
            {
                lv = ((EClass.rnd(3) == 0) ? EClass.pc.LV : EClass.pc.FameLv) * (75 + EClass.rnd(50)) / 100 + EClass.rnd(EClass.rnd(10) + 1) - 3;
                if (lv >= 50)
                {
                    lv = EClass.rndHalf(50);
                }
            }
            else
            {
                lv = EClass.pc.FameLv * 100 / (100 + EClass.rnd(50)) + EClass.rnd(EClass.rnd(10) + 1) - 3;
                if (EClass.rnd(10) == 0)
                {
                    lv = lv * 3 / 2;
                }
                if (EClass.rnd(10) == 0)
                {
                    lv /= 2;
                }
            }
        }
        zone._dangerLv = Mathf.Max(1, lv);
        zone.isRandomSite = true;
        zone.dateExpire = EClass.world.date.GetRaw() + 10080;
        if (elomap.IsSnow(zone.x, zone.y))
        {
            zone.icon++;
        }
        elomap.SetZone(zone.x, zone.y, zone);
        if (updateMesh)
        {
            elomap.objmap.UpdateMeshImmediate();
        }
        return zone;
    }
References Player.CountKeyItem(), SpatialGen.Create(), World.date, EClass.debug, elomap, CoreDebug.enable, Card.FameLv, GetRandomSiteSource(), Date.GetRaw(), Spatial.icon, EloMap.IsSnow(), Card.LV, Spatial.lv, EloMap.objmap, EClass.pc, EClass.player, EClass.rnd(), EClass.rndHalf(), EloMap.SetZone(), EClass.world, Point.x, Spatial.x, Spatial.y, and Point.z.
CreateRandomSite() [2/2]
Zone Region.CreateRandomSite (Zone center, int radius = 8, string idSource = null, bool updateMesh = true, int lv = 0) inline
Definition at line 104 of file Region.cs.
    {
        InitElomap();
        return CreateRandomSite(GetRandomPoint(center.IsRegion ? (EClass.pc.pos.x + EClass.scene.elomap.minX) : center.x, center.IsRegion ? (EClass.pc.pos.z + EClass.scene.elomap.minY) : center.y, radius), idSource, updateMesh, lv);
    }
References CreateRandomSite(), Scene.elomap, GetRandomPoint(), InitElomap(), Spatial.IsRegion, Spatial.lv, EloMap.minX, EloMap.minY, EClass.pc, Card.pos, EClass.scene, Point.x, Spatial.x, Spatial.y, and Point.z.
Referenced by CreateRandomSite(), Expedition.End(), TraitScrollMap.OnRead(), and UpdateRandomSites().
CreateZone()
Zone Region.CreateZone (Point pos) inline
Definition at line 226 of file Region.cs.
    {
        return SpatialGen.Create("field", this, register: true, pos.x, pos.z) as Zone;
    }
References SpatialGen.Create(), Point.x, and Point.z.
Referenced by Player.EnterLocalZone().
GetRandomPoint() [1/3]
Point Region.GetRandomPoint () inline
Definition at line 164 of file Region.cs.
    {
        Point point = new Point();
        for (int i = 0; i < 1000; i++)
        {
            point = map.bounds.GetRandomPoint();
            point.x += elomap.minX;
            point.z += elomap.minY;
            if (elomap.CanBuildSite(point.x, point.z, 1))
            {
                return point;
            }
        }
        return null;
    }
References Map.bounds, EloMap.CanBuildSite(), elomap, MapBounds.GetRandomPoint(), Zone.map, EloMap.minX, EloMap.minY, Point.x, and Point.z.
Referenced by CreateRandomSite(), OnAdvanceHour(), and UpdateRandomSites().
GetRandomPoint() [2/3]
Point Region.GetRandomPoint (int orgX, int orgY, int minRadius, int maxRadius) inline
Definition at line 199 of file Region.cs.
    {
        Point point = new Point();
        Point p = new Point(orgX, orgY);
        for (int i = 0; i < 1000; i++)
        {
            point.x = orgX + Rand.Range(-maxRadius, maxRadius);
            point.z = orgY + Rand.Range(-maxRadius, maxRadius);
            if (point.Distance(p) >= minRadius && !point.IsBlocked && elomap.CanBuildSite(point.x + elomap.minX, point.z + elomap.minY, 0, ElomapSiteType.Mob))
            {
                return point;
            }
        }
        return null;
    }
References EloMap.CanBuildSite(), Point.Distance(), elomap, Point.IsBlocked, EloMap.minX, EloMap.minY, Rand.Range(), Point.x, and Point.z.
GetRandomPoint() [3/3]
Point Region.GetRandomPoint (int orgX, int orgY, int radius = 8, bool increaseRadius = false) inline
Definition at line 180 of file Region.cs.
    {
        Point point = new Point();
        for (int i = 0; i < 1000; i++)
        {
            point.x = orgX + Rand.Range(-radius / 2, radius / 2);
            point.z = orgY + Rand.Range(-radius / 2, radius / 2);
            if (i % 100 == 0 && increaseRadius)
            {
                radius++;
            }
            if (elomap.CanBuildSite(point.x, point.z))
            {
                return point;
            }
        }
        return null;
    }
References EloMap.CanBuildSite(), elomap, Rand.Range(), Point.x, and Point.z.
GetRandomSiteSource()
SourceZone.Row Region.GetRandomSiteSource () inline
Definition at line 159 of file Region.cs.
    {
        return EClass.sources.zones.rows.Where((SourceZone.Row a) => a.tag.Contains("random") && (EClass.debug.enable || !a.tag.Contains("debug"))).ToList().RandomItemWeighted((SourceZone.Row a) => a.chance);
    }
References EClass.debug, CoreDebug.enable, EClass.sources, and SourceManager.zones.
Referenced by ThingGen.CreateMap(), and CreateRandomSite().
GetRandomTown()
Zone Region.GetRandomTown () inline
Definition at line 244 of file Region.cs.
    {
        List<Zone> list = ListTowns();
        Zone zone = null;
        for (int i = 0; i < 5; i++)
        {
            zone = list.RandomItem();
            _ = zone is Zone_SubTown;
        }
        return zone;
    }
References ListTowns().
Referenced by GlobalGoalAdv.OnAdvanceHour().
InitElomap()
void Region.InitElomap () inline
Definition at line 99 of file Region.cs.
    {
        EClass.scene.elomapActor.Initialize(elomap);
    }
References elomap, Scene.elomapActor, EloMapActor.Initialize(), and EClass.scene.
Referenced by CreateRandomSite().
ListMobs()
List< Chara > Region.ListMobs () inline
Definition at line 332 of file Region.cs.
    {
        List<Chara> list = new List<Chara>();
        foreach (Chara chara in EClass._map.charas)
        {
            if (!chara.IsPCFactionOrMinion && !chara.IsGlobal)
            {
                list.Add(chara);
            }
        }
        return list;
    }
References EClass._map, Map.charas, Chara.IsGlobal, and Card.IsPCFactionOrMinion.
Referenced by OnAdvanceHour().
ListRandomSites()
List< Zone > Region.ListRandomSites () inline
Definition at line 256 of file Region.cs.
    {
        return (from Zone a in children
            where a.isRandomSite
            select a).ToList();
    }
References Spatial.children.
Referenced by RenewRandomSites(), and UpdateRandomSites().
ListTowns()
List< Zone > Region.ListTowns () inline
Definition at line 231 of file Region.cs.
    {
        List<Zone> list = new List<Zone>();
        foreach (Spatial value in EClass.game.spatials.map.Values)
        {
            if (value.CanSpawnAdv)
            {
                list.Add(value as Zone);
            }
        }
        return list;
    }
References Spatial.CanSpawnAdv, EClass.game, SpatialManager.map, and Game.spatials.
Referenced by GameDate.AdvanceDay(), GlobalGoalVisitTown.GetDestZone(), GetRandomTown(), and Chara.OnBanish().
ListTravelZones()
List< Zone > Region.ListTravelZones (int radius = 100) inline
Definition at line 276 of file Region.cs.
    {
        bool isRegion = EClass.pc.currentZone.IsRegion;
        List<Zone> list = new List<Zone>();
        if (!isRegion)
        {
            new Point(EClass.pc.currentZone.x - EClass.scene.elomap.minX, EClass.pc.currentZone.y - EClass.scene.elomap.minY);
        }
        else
        {
            _ = EClass.pc.pos;
        }
        foreach (Zone zone in EClass.game.spatials.Zones)
        {
            if (zone.CanFastTravel && !zone.IsInstance && (zone.isKnown || EClass.debug.returnAnywhere) && zone.parent == this)
            {
                list.Add(zone);
                zone.tempDist = zone.Dist(EClass.pc.pos);
            }
        }
        return list;
    }
References Spatial.CanFastTravel, Chara.currentZone, EClass.debug, Spatial.Dist(), Scene.elomap, EClass.game, Zone.IsInstance, Spatial.isKnown, Spatial.IsRegion, EloMap.minX, EloMap.minY, Spatial.parent, EClass.pc, Card.pos, CoreDebug.returnAnywhere, EClass.scene, Game.spatials, Spatial.x, Spatial.y, and SpatialManager.Zones.
Referenced by LayerTravel.Refresh().
ListZonesInRadius()
List< Zone > Region.ListZonesInRadius (Zone center, int radius = 10) inline
Definition at line 263 of file Region.cs.
    {
        List<Zone> list = new List<Zone>();
        foreach (Zone zone in EClass.game.spatials.Zones)
        {
            if (zone.Dist(center) <= radius && zone != center && !(zone.source.parent != base.source.id))
            {
                list.Add(zone);
            }
        }
        return list;
    }
References Spatial.Dist(), EClass.game, Spatial.source, Game.spatials, and SpatialManager.Zones.
Referenced by Expedition.End().
OnActivate()
override void Region.OnActivate () inline virtual
Reimplemented from Zone.
Definition at line 25 of file Region.cs.
    {
        children.ForeachReverse(delegate(Spatial _z)
        {
            Zone zone2 = _z as Zone;
            if (zone2.CanDestroy())
            {
                zone2.Destroy();
            }
        });
        children.ForeachReverse(delegate(Spatial _z)
        {
            if (_z.destryoed)
            {
                children.Remove(_z);
            }
        });
        children.ForEach(delegate(Spatial a)
        {
            Zone zone = a as Zone;
            if (!zone.IsInstance && (zone.IsPCFaction || !(zone is Zone_Field)) && !(zone is Zone_SisterHouse))
            {
                elomap.SetZone(zone.x, zone.y, zone);
            }
        });
        CheckRandomSites();
    }
References Zone.CanDestroy(), CheckRandomSites(), Spatial.children, Spatial.destryoed, Zone.IsInstance, and Zone.IsPCFaction.
OnAdvanceHour()
override void Region.OnAdvanceHour () inline virtual
Reimplemented from Zone.
Definition at line 299 of file Region.cs.
    {
        if (EClass.world.date.hour == 0)
        {
            foreach (Chara item in ListMobs())
            {
                if (item.Dist(EClass.pc) > 20 && EClass.rnd(2) == 0)
                {
                    item.Destroy();
                }
            }
        }
        if (ListMobs().Count >= (EClass.debug.enable ? 100 : 6) || EClass.rnd(3) != 0)
        {
            return;
        }
        Point randomPoint = GetRandomPoint(EClass.pc.pos.x, EClass.pc.pos.z, 8, 14);
        if (randomPoint != null)
        {
            RegionPoint regionPoint = new RegionPoint(EClass.pc.pos);
            BiomeProfile biome = regionPoint.biome;
            SpawnList list = ((biome.spawn.chara.Count <= 0) ? SpawnList.Get(biome.name, "chara", new CharaFilter
            {
                ShouldPass = (SourceChara.Row s) => s.biome == biome.name || s.biome.IsEmpty()
            }) : SpawnList.Get(biome.spawn.GetRandomCharaId()));
            Chara chara = CharaGen.CreateFromFilter(list, regionPoint.dangerLv);
            if (chara != null)
            {
                AddCard(chara, randomPoint);
            }
        }
    }
References Zone.AddCard(), RegionPoint.biome, Zone.biome, CharaGen.CreateFromFilter(), World.date, EClass.debug, CoreDebug.enable, SpawnList.Get(), BiomeProfile.Spawns.GetRandomCharaId(), GetRandomPoint(), Date.hour, item, ListMobs(), EClass.pc, Card.pos, EClass.rnd(), BiomeProfile.spawn, EClass.world, Point.x, and Point.z.
RenewRandomSites()
void Region.RenewRandomSites () inline
Definition at line 75 of file Region.cs.
    {
        dateCheckSites = 0;
        Msg.Say("renewNefia");
        Debug.Log(ListRandomSites().Count);
        foreach (Zone item in ListRandomSites())
        {
            item.dateExpire = 1;
        }
    }
References dateCheckSites, Debug, item, ListRandomSites(), and Msg.Say().
Referenced by LayerSleep.Advance().
UpdateRandomSites()
void Region.UpdateRandomSites () inline
Definition at line 86 of file Region.cs.
    {
        List<Zone> list = ListRandomSites();
        int num = 50 - list.Count;
        if (num > 0)
        {
            for (int i = 0; i < num; i++)
            {
                CreateRandomSite(GetRandomPoint(), null, updateMesh: false);
            }
        }
    }
References CreateRandomSite(), GetRandomPoint(), and ListRandomSites().
Referenced by LayerSleep.Advance(), and CheckRandomSites().
Member Data Documentation
dateCheckSites
int Region.dateCheckSites
Definition at line 11 of file Region.cs.
Referenced by CheckRandomSites(), and RenewRandomSites().
elomap
EloMap Region.elomap = new EloMap()
Definition at line 8 of file Region.cs.
Referenced by Zone.Activate(), CanCreateZone(), CheckRandomSites(), CreateRandomSite(), EloMapActor.GetEloMap(), Zone.GetProfile(), GetRandomPoint(), EloMap.GetRoadDist(), InitElomap(), MapGenRegion.OnGenerateTerrain(), and LayerTreasureMap.SetMap().
Property Documentation
BlockBorderExit
override bool Region.BlockBorderExit get
Definition at line 21 of file Region.cs.
DangerLv
override int Region.DangerLv get
Definition at line 19 of file Region.cs.
DefaultActionMode
override ActionMode Region.DefaultActionMode get
Definition at line 15 of file Region.cs.
IsRegion
override bool Region.IsRegion get
Definition at line 17 of file Region.cs.
RegionPos
override Point Region.RegionPos get
Definition at line 23 of file Region.cs.
WillAutoSave
override bool Region.WillAutoSave get
Definition at line 13 of file Region.cs.
The documentation for this class was generated from the following file:
Elin/Region.cs