Elin Decompiled Documentation: WidgetPopText Class Reference
WidgetPopText Class Reference
Public Member Functions
override void OnActivate ()
void _SayPick (Thing t, int num)
void _SayValue (string name, int a, bool negative=false, Sprite sprite=null)
void _Say (string text, FontColor fontColor=FontColor.Default, Sprite sprite=null)
Public Member Functions inherited from Widget
void Test ()
bool IsInRightMode ()
void Activate ()
void RefreshOrder ()
virtual void OnActivate ()
virtual object CreateExtra ()
void Deactivate ()
virtual void OnDeactivate ()
void Close ()
void Reactivate ()
virtual void OnManagerActivate ()
virtual void OnManagerDeactivate ()
void SetAnchor (RectPosition p)
void SetPivot (RectPosition p)
virtual void OnChangePivot ()
void UpdateConfig ()
virtual void OnUpdateConfig ()
void ClampToScreen ()
virtual void OnChangeResolution ()
void OnChangePosition ()
virtual void OnChangeActionMode ()
virtual void OnFlip ()
bool IsAlignTop ()
Layer AddLayer (Layer l, Transform trans)
void RefreshTipPivotPosition ()
SkinSet GetSkin ()
SkinConfig GetSkinConfig ()
void SetSkin (int id, int v=0)
void TestSkin ()
virtual void ApplySkin ()
virtual void OnApplySkin ()
void InstantiateDeco (SkinDeco deco)
void AddDeco (SkinDeco deco)
void RemoveDeco (SkinDeco deco)
virtual bool CanShowContextMenu ()
void ShowContextMenu ()
void SetBaseContextMenu (UIContextMenu m)
virtual void OnSetContextMenu (UIContextMenu m)
void SetGridContextMenu (UIContextMenu m)
void SoundActivate ()
void OnChangeResolution ()
SkinSet GetSkin ()
SkinConfig GetSkinConfig ()
Static Public Member Functions
static void SayPick (Thing t, int num)
static void SayValue (string name, int a, bool negative=false, Sprite sprite=null)
static void Say (string text, FontColor fontColor=FontColor.Default, Sprite sprite=null)
Static Public Member Functions inherited from EMono
static int rnd (int a)
Public Attributes
PopManager pop
Sprite[] icons
Public Attributes inherited from Widget
Image imageBG
SoundData soundActivate
UIDragPanel dragPanel
RectTransform tipPivotLeft
RectTransform tipPivotRight
Static Public Attributes
static WidgetPopText Instance
Static Public Attributes inherited from EMono
static Core core
Additional Inherited Members
Public Types inherited from Widget
enum WidgetType { Default , ZoomMenu }
enum State { Active , Inactive }
Protected Member Functions inherited from Widget
void ClampToScreenEnsured (Component c, Vector2 anchoredPos)
void ClampToScreen (RectTransform rect, float margin=10f)
Protected Attributes inherited from Widget
bool flip
Properties inherited from Widget
string ID [get]
Config config [get]
SkinRoot skinRoot [get]
bool IsSealed [get]
virtual bool ShowStyleMenu [get]
virtual bool AlwaysTop [get]
virtual bool IsStaticPosition [get]
virtual bool AlwaysBottom [get]
virtual Type SetSiblingAfter [get]
virtual bool ShowInBuildMode [get]
virtual bool RightClickToClose [get]
virtual bool AllowRightClickToClose [get]
Properties inherited from EMono
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SoundManager Sound [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static CoreDebug debug [get]
Detailed Description
Definition at line 3 of file WidgetPopText.cs.
Member Function Documentation
_Say()
void WidgetPopText._Say (string text, FontColor fontColor = FontColor::Default, Sprite sprite = null) inline
Definition at line 52 of file WidgetPopText.cs.
    {
        PopItemText popItemText = pop.PopText(text, sprite ?? icons[0], "PopNotification");
        if (fontColor != FontColor.Default)
        {
            popItemText.text.color = SkinManager.Instance.skinDark.Colors.GetTextColor(fontColor);
        }
    }
References SkinRootStatic.Colors, SkinColorProfile.GetTextColor(), icons, SkinManager.Instance, pop, PopManager.PopText(), and SkinManager.skinDark.
Referenced by Say().
_SayPick()
void WidgetPopText._SayPick (Thing t, int num) inline
Definition at line 40 of file WidgetPopText.cs.
    {
        PopItemText popItemText = pop.PopText("notifyAddThing".lang(t.GetName(NameStyle.Full, num), t.Num.ToString() ?? ""), null, "PopNotification");
        t.SetImage(popItemText.image);
        popItemText.image.SetActive(enable: true);
    }
References Thing.GetName(), PopItemText.image, Card.Num, pop, PopManager.PopText(), and Card.SetImage().
Referenced by SayPick().
_SayValue()
void WidgetPopText._SayValue (string name, int a, bool negative = false, Sprite sprite = null) inline
Definition at line 47 of file WidgetPopText.cs.
    {
        Say(name + " " + ((a > 0) ? "+" : "") + a, (!negative) ? FontColor.Default : FontColor.Bad, sprite);
    }
References Say().
Referenced by SayValue().
OnActivate()
override void WidgetPopText.OnActivate () inline virtual
Reimplemented from Widget.
Definition at line 11 of file WidgetPopText.cs.
    {
        Instance = this;
    }
References Instance.
Say()
static void WidgetPopText.Say (string text, FontColor fontColor = FontColor::Default, Sprite sprite = null) inline static
Definition at line 32 of file WidgetPopText.cs.
    {
        if ((bool)Instance)
        {
            Instance._Say(text, fontColor, sprite);
        }
    }
References _Say(), and Instance.
Referenced by _SayValue(), FactionBranch.AddFeat(), ResearchManager.AddPlan(), PolicyManager.AddPolicy(), ResearchManager.CompletePlan(), FactionBranch.DailyOutcome(), Chara.Die(), Expedition.End(), Chara.MutateRandom(), ElementContainerCard.OnLevelUp(), ElementContainerZone.OnLevelUp(), FactionBranch.ReceivePackages(), Expedition.Start(), and Map.TryShatter().
SayPick()
static void WidgetPopText.SayPick (Thing t, int num) inline static
Definition at line 16 of file WidgetPopText.cs.
    {
        if ((bool)Instance)
        {
            Instance._SayPick(t, num);
        }
    }
References _SayPick(), and Instance.
SayValue()
static void WidgetPopText.SayValue (string name, int a, bool negative = false, Sprite sprite = null) inline static
Definition at line 24 of file WidgetPopText.cs.
    {
        if ((bool)Instance)
        {
            Instance._SayValue(name, a, negative, sprite);
        }
    }
References _SayValue(), and Instance.
Referenced by HomeResource.Mod().
Member Data Documentation
icons
Sprite [] WidgetPopText.icons
Definition at line 9 of file WidgetPopText.cs.
Referenced by _Say().
Instance
WidgetPopText WidgetPopText.Instance static
Definition at line 5 of file WidgetPopText.cs.
Referenced by OnActivate(), Say(), SayPick(), and SayValue().
pop
PopManager WidgetPopText.pop
Definition at line 7 of file WidgetPopText.cs.
Referenced by _Say(), and _SayPick().
The documentation for this class was generated from the following file:
Elin/WidgetPopText.cs