Elin Decompiled Documentation: WidgetManager Class Reference
WidgetManager Class Reference
Classes
class SaveData
Public Member Functions
void OnActivateZone ()
void OnGameInstantiated ()
void OnKillGame ()
void OnChangeActionMode ()
void UpdateConfigs ()
void Activate (string id)
Widget Toggle (string id)
Widget Toggle (Widget.Config c)
void ToggleLock (Widget.Config c)
Widget ActivateWidget (Widget.Config c)
Widget ActivateWidget (string id)
void RefreshWidget (Widget.Config c)
void RefreshWidget (Widget w)
Widget GetWidget (string id)
void DeactivateWidget (string id)
void DeactivateWidget (Widget w)
void KillWidgets ()
void Show ()
void Hide ()
void Reset (bool toggleTheme)
void DialogSave (Action onSave=null)
void DialogLoad (Action onLoad=null)
void Save (string path=null)
void Load (bool isSubTheme, string path=null)
Public Attributes
Dictionary< string, Widget.Meta > metaMap = new Dictionary<string, Widget.Meta>()
string currentPath
List< Widget > list = new List<Widget>()
Properties
List< Widget.Meta > metas [get]
Dictionary< string, Widget.Config > configs [get]
Properties inherited from EMono
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SoundManager Sound [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static CoreDebug debug [get]
Private Attributes
bool first
Additional Inherited Members
Static Public Member Functions inherited from EMono
static int rnd (int a)
Static Public Attributes inherited from EMono
static Core core
Detailed Description
Definition at line 8 of file WidgetManager.cs.
Member Function Documentation
Activate()
void WidgetManager.Activate (string id) inline
Definition at line 144 of file WidgetManager.cs.
    {
        if (!GetWidget(id))
        {
            ActivateWidget(configs[id]);
        }
    }
References ActivateWidget(), configs, and GetWidget().
Referenced by OnActivateZone().
ActivateWidget() [1/2]
Widget WidgetManager.ActivateWidget (string id) inline
Definition at line 185 of file WidgetManager.cs.
    {
        string text = "Widget" + id;
        Widget widget = Util.Instantiate<Widget>("UI/Widget/" + text, this) ?? Util.Instantiate<Widget>("UI/Widget/" + text + "/" + text, this);
        if (!widget)
        {
            Debug.LogError("Widget:" + id + " not found.");
            return null;
        }
        list.Add(widget);
        widget.gameObject.name = text;
        widget.Activate();
        RefreshWidget(widget);
        if ((bool)LayerWidget.Instance)
        {
            widget.OnManagerActivate();
        }
        return widget;
    }
References Widget.Activate(), Debug, LayerWidget.Instance, list, Widget.OnManagerActivate(), RefreshWidget(), and Util.
ActivateWidget() [2/2]
Widget WidgetManager.ActivateWidget (Widget::Config c) inline
Definition at line 180 of file WidgetManager.cs.
    {
        return ActivateWidget(c.id);
    }
References ActivateWidget().
Referenced by Activate(), ActivateWidget(), OnActivateZone(), and Toggle().
DeactivateWidget() [1/2]
void WidgetManager.DeactivateWidget (string id) inline
Definition at line 230 of file WidgetManager.cs.
    {
        DeactivateWidget(GetWidget(id));
    }
References DeactivateWidget(), and GetWidget().
Referenced by DeactivateWidget(), OnActivateZone(), and Toggle().
DeactivateWidget() [2/2]
void WidgetManager.DeactivateWidget (Widget w) inline
Definition at line 235 of file WidgetManager.cs.
    {
        if (!(w == null))
        {
            list.Remove(w);
            w.Deactivate();
            if ((bool)LayerWidget.Instance)
            {
                LayerWidget.Instance.Refresh();
            }
        }
    }
References Widget.Deactivate(), LayerWidget.Instance, list, and LayerWidget.Refresh().
DialogLoad()
void WidgetManager.DialogLoad (Action onLoad = null) inline
Definition at line 320 of file WidgetManager.cs.
    {
        EMono.core.WaitForEndOfFrame(delegate
        {
            string[] array = StandaloneFileBrowser.OpenFilePanel("Load Widget Theme", CorePath.WidgetSave, "json", multiselect: false);
            if (array.Length != 0)
            {
                Load(EMono.player.useSubWidgetTheme, array[0]);
                Reset(toggleTheme: false);
                if (onLoad != null)
                {
                    onLoad();
                }
            }
        });
    }
References EMono.core, if(), SFB.StandaloneFileBrowser.OpenFilePanel(), BaseCore.WaitForEndOfFrame(), and CorePath.WidgetSave.
DialogSave()
void WidgetManager.DialogSave (Action onSave = null) inline
Definition at line 297 of file WidgetManager.cs.
    {
        EMono.core.WaitForEndOfFrame(delegate
        {
            string text = StandaloneFileBrowser.SaveFilePanel("Save Widget Theme", CorePath.WidgetSave, "new theme", "json");
            if (!string.IsNullOrEmpty(text))
            {
                if (!EMono.debug.enable && (text.Contains("Default.json") || text.Contains("Modern.json") || text.Contains("Classic.json")))
                {
                    Dialog.Ok("dialogInvalidTheme");
                }
                else
                {
                    Save(text);
                    if (onSave != null)
                    {
                        onSave();
                    }
                }
            }
        });
    }
References EMono.core, EMono.debug, CoreDebug.enable, if(), SFB.StandaloneFileBrowser.SaveFilePanel(), BaseCore.WaitForEndOfFrame(), and CorePath.WidgetSave.
GetWidget()
Widget WidgetManager.GetWidget (string id) inline
Definition at line 218 of file WidgetManager.cs.
    {
        foreach (Widget item in list)
        {
            if (item.gameObject.name == "Widget" + id)
            {
                return item;
            }
        }
        return null;
    }
References item, and list.
Referenced by Activate(), DeactivateWidget(), OnActivateZone(), RefreshWidget(), and Toggle().
Hide()
void WidgetManager.Hide () inline
Definition at line 266 of file WidgetManager.cs.
    {
        foreach (Widget item in list)
        {
            if (item is WidgetCurrentTool || item is WidgetQuestTracker || item is WidgetTracker || item is WidgetMemo || item is WidgetEquip)
            {
                item.gameObject.SetActive(value: false);
            }
        }
    }
References item, and list.
Referenced by UI.OnChangeLayer().
KillWidgets()
void WidgetManager.KillWidgets () inline
Definition at line 248 of file WidgetManager.cs.
    {
        this.DestroyChildren(destroyInactive: true);
        list.Clear();
        first = true;
    }
References first, and list.
Referenced by OnKillGame(), and Reset().
Load()
void WidgetManager.Load (bool isSubTheme, string path = null) inline
Definition at line 347 of file WidgetManager.cs.
    {
        if (path == null)
        {
            path = CorePath.WidgetSave + (isSubTheme ? EMono.core.config.other.idSubWidgetTheme : EMono.core.config.other.idMainWidgetTheme) + ".json";
        }
        SaveData saveData = IO.LoadFile<SaveData>(path);
        if (isSubTheme)
        {
            EMono.player.subWidgets = saveData;
        }
        else
        {
            EMono.player.mainWidgets = saveData;
        }
        currentPath = path;
    }
References Core.config, EMono.core, CoreConfig.OtherSetting.idMainWidgetTheme, and CoreConfig.other.
Referenced by OnGameInstantiated().
OnActivateZone()
void WidgetManager.OnActivateZone () inline
Definition at line 28 of file WidgetManager.cs.
    {
        if (!first)
        {
            return;
        }
        first = false;
        foreach (Widget.Config value in configs.Values)
        {
            if (value.state == Widget.State.Active)
            {
                ActivateWidget(value);
            }
        }
        bool flag = EMono.ui.layerFloat.GetLayer<LayerInventory>();
        if (GetWidget("Equip") == null)
        {
            if (flag)
            {
                Activate("Equip");
            }
        }
        else if (!flag)
        {
            DeactivateWidget("Equip");
        }
    }
References Activate(), ActivateWidget(), configs, DeactivateWidget(), first, GetWidget(), and EMono.ui.
Referenced by UI.OnActivateZone(), and Reset().
OnChangeActionMode()
void WidgetManager.OnChangeActionMode () inline
Definition at line 128 of file WidgetManager.cs.
    {
        foreach (Widget item in list)
        {
            item.OnChangeActionMode();
        }
    }
References item, and list.
Referenced by Reset().
OnGameInstantiated()
void WidgetManager.OnGameInstantiated () inline
Definition at line 56 of file WidgetManager.cs.
    {
        if (Application.isEditor && EMono.debug.resetPlayerConfig && !EMono.player.isEditor)
        {
            EMono.player.useSubWidgetTheme = false;
            EMono.ui.widgets.Load(isSubTheme: false);
        }
        first = true;
        if (EMono.player.useSubWidgetTheme)
        {
            if (EMono.player.subWidgets == null)
            {
                Load(isSubTheme: true);
            }
        }
        else if (EMono.player.mainWidgets == null)
        {
            Load(isSubTheme: false);
            if (Screen.width <= 1300 && !EMono.player.useSubWidgetTheme)
            {
                foreach (KeyValuePair<string, Widget.Config> item in EMono.player.mainWidgets.dict)
                {
                    if (item.Key == "StatsBar")
                    {
                        item.Value.state = Widget.State.Inactive;
                    }
                }
            }
        }
        if (metaMap.Count == 0)
        {
            foreach (Widget.Meta meta in metas)
            {
                metaMap.Add(meta.id, meta);
            }
        }
        foreach (Widget.Meta meta2 in metas)
        {
            if (!configs.ContainsKey(meta2.id))
            {
                Widget.Config config = new Widget.Config
                {
                    meta = meta2,
                    valid = true,
                    id = meta2.id,
                    state = ((!meta2.enabled) ? Widget.State.Inactive : Widget.State.Active),
                    locked = meta2.locked
                };
                config.skin.SetID(0);
                configs.Add(meta2.id, config);
            }
            else
            {
                Widget.Config config2 = configs[meta2.id];
                config2.valid = true;
                config2.meta = meta2;
            }
        }
        foreach (Widget.Config item2 in configs.Values.ToList())
        {
            if (!item2.valid)
            {
                configs.Remove(item2.id);
            }
        }
    }
References configs, EMono.debug, first, Widget.Config.id, Player.isEditor, item, Load(), Player.mainWidgets, metaMap, metas, EMono.player, CoreDebug.resetPlayerConfig, SkinConfig.SetID(), Widget.Config.skin, Player.subWidgets, EMono.ui, and Player.useSubWidgetTheme.
Referenced by Reset().
OnKillGame()
void WidgetManager.OnKillGame () inline
Definition at line 123 of file WidgetManager.cs.
    {
        KillWidgets();
    }
References KillWidgets().
Referenced by UI.OnKillGame().
RefreshWidget() [1/2]
void WidgetManager.RefreshWidget (Widget w) inline
Definition at line 210 of file WidgetManager.cs.
    {
        if ((bool)w)
        {
            w.dragPanel.GetComponent<Graphic>().raycastTarget = !w.config.locked;
        }
    }
References Widget.config, Widget.dragPanel, and Widget.Config.locked.
RefreshWidget() [2/2]
void WidgetManager.RefreshWidget (Widget::Config c) inline
Definition at line 205 of file WidgetManager.cs.
    {
        RefreshWidget(GetWidget(c.id));
    }
References GetWidget(), and RefreshWidget().
Referenced by ActivateWidget(), RefreshWidget(), and ToggleLock().
Reset()
void WidgetManager.Reset (bool toggleTheme) inline
Definition at line 277 of file WidgetManager.cs.
    {
        if (WidgetMainText.Instance.box.isShowingLog)
        {
            WidgetMainText.Instance._ToggleLog();
        }
        if ((bool)WidgetMainText.Instance)
        {
            (WidgetMainText.boxBk = WidgetMainText.Instance.box).transform.SetParent(base.transform.parent, worldPositionStays: false);
        }
        KillWidgets();
        if (toggleTheme)
        {
            EMono.player.useSubWidgetTheme = !EMono.player.useSubWidgetTheme;
        }
        OnGameInstantiated();
        OnActivateZone();
        OnChangeActionMode();
    }
References WidgetMainText._ToggleLog(), WidgetMainText.box, WidgetMainText.Instance, MsgBox.isShowingLog, KillWidgets(), OnActivateZone(), OnChangeActionMode(), OnGameInstantiated(), EMono.player, and Player.useSubWidgetTheme.
Referenced by HotItemToggleWidget.OnClick().
Save()
void WidgetManager.Save (string path = null) inline
Definition at line 337 of file WidgetManager.cs.
    {
        if (path == null)
        {
            path = CorePath.WidgetSave + (EMono.player.useSubWidgetTheme ? EMono.core.config.other.idSubWidgetTheme : EMono.core.config.other.idMainWidgetTheme) + ".json";
        }
        UpdateConfigs();
        IO.SaveFile(path, EMono.player.widgets);
    }
References Core.config, EMono.core, CoreConfig.OtherSetting.idMainWidgetTheme, CoreConfig.other, EMono.player, and Player.widgets.
Show()
void WidgetManager.Show () inline
Definition at line 255 of file WidgetManager.cs.
    {
        foreach (Widget item in list)
        {
            if (item.IsInRightMode())
            {
                item.gameObject.SetActive(value: true);
            }
        }
    }
References item, and list.
Toggle() [1/2]
Widget WidgetManager.Toggle (string id) inline
Definition at line 152 of file WidgetManager.cs.
    {
        Widget widget = GetWidget(id);
        if ((bool)widget)
        {
            DeactivateWidget(widget);
            return null;
        }
        return ActivateWidget(configs[id]);
    }
References ActivateWidget(), configs, DeactivateWidget(), and GetWidget().
Referenced by LayerWidget.OnInit().
Toggle() [2/2]
Widget WidgetManager.Toggle (Widget::Config c) inline
Definition at line 163 of file WidgetManager.cs.
    {
        Widget widget = GetWidget(c.id);
        if ((bool)widget)
        {
            DeactivateWidget(widget);
            return null;
        }
        return ActivateWidget(c);
    }
References ActivateWidget(), DeactivateWidget(), and GetWidget().
ToggleLock()
void WidgetManager.ToggleLock (Widget::Config c) inline
Definition at line 174 of file WidgetManager.cs.
    {
        c.locked = !c.locked;
        RefreshWidget(c);
    }
References RefreshWidget().
Referenced by LayerWidget.OnInit().
UpdateConfigs()
void WidgetManager.UpdateConfigs () inline
Definition at line 136 of file WidgetManager.cs.
    {
        foreach (Widget item in list)
        {
            item.UpdateConfig();
        }
    }
References item, and list.
Referenced by HotItemToggleWidget.OnClick().
Member Data Documentation
currentPath
string WidgetManager.currentPath
Definition at line 17 of file WidgetManager.cs.
first
bool WidgetManager.first private
Definition at line 22 of file WidgetManager.cs.
Referenced by KillWidgets(), OnActivateZone(), and OnGameInstantiated().
list
List<Widget> WidgetManager.list = new List<Widget>()
Definition at line 20 of file WidgetManager.cs.
Referenced by ActivateWidget(), DeactivateWidget(), GetWidget(), Hide(), KillWidgets(), OnChangeActionMode(), Show(), and UpdateConfigs().
metaMap
Dictionary<string, Widget.Meta> WidgetManager.metaMap = new Dictionary<string, Widget.Meta>()
Definition at line 15 of file WidgetManager.cs.
Referenced by OnGameInstantiated().
Property Documentation
configs
Dictionary<string, Widget.Config> WidgetManager.configs get
Definition at line 26 of file WidgetManager.cs.
Referenced by Activate(), OnActivateZone(), OnGameInstantiated(), and Toggle().
metas
List<Widget.Meta> WidgetManager.metas get
Definition at line 24 of file WidgetManager.cs.
Referenced by OnGameInstantiated().
The documentation for this class was generated from the following file:
Elin/WidgetManager.cs