Elin Decompiled Documentation: HyphenationJpn Class Reference
HyphenationJpn Class Reference
Public Member Functions
void _SetText (string str, bool useHypenation)
float GetWidth ()
Public Attributes
int padding
bool useParentWidth = true
bool usePreferredWidth = true
bool evaluateLate
Properties
RectTransform _RectTransform [get]
Text _Text [get]
Private Member Functions
void UpdateText (string str)
float GetSpaceWidth ()
float GetTextWidth (string message)
string GetFormatedText (string msg)
List< string > GetWordList (string tmpText)
Static Private Member Functions
static bool CHECK_HYP_FRONT (char str)
static bool CHECK_HYP_BACK (char str)
static bool IsLatin (char s)
Private Attributes
string text
bool useHypenation
RectTransform _rectTransform
Text _text
float width
Static Private Attributes
static readonly string RITCH_TEXT_REPLACE = "(\<color=.*\>|</color>|\<size=.n\\>|</size>|<b>|</b>|<i>|</i>)"
static readonly char[] HYP_FRONT = ",)]｝、。）〕〉》」』】〙〗〟’”｠»ァィゥェォッャュョヮヵヶっぁぃぅぇぉっゃゅょゎ‐゠–〜ー?!！？‼⁇⁈⁉・:;。.".ToCharArray()
static readonly char[] HYP_BACK = "(（[｛〔〈《「『【〘〖〝‘“｟«".ToCharArray()
static readonly char[] HYP_LATIN = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789<>=/().,".ToCharArray()
Detailed Description
Definition at line 10 of file HyphenationJpn.cs.
Member Function Documentation
_SetText()
void HyphenationJpn._SetText (string str, bool useHypenation) inline
Definition at line 70 of file HyphenationJpn.cs.
    {
        text = str;
        this.useHypenation = useHypenation;
        if (!useHypenation)
        {
            _Text.horizontalOverflow = HorizontalWrapMode.Wrap;
            _Text.text = text;
            return;
        }
        _Text.text = text;
        width = GetWidth();
        if (width < 50f)
        {
            this.RebuildLayoutTo<Canvas>();
            this.RebuildLayout();
            width = GetWidth();
            if (width < 50f)
            {
                BaseCore.Instance.actionsNextFrame.Add(delegate
                {
                    width = GetWidth();
                    UpdateText(text);
                    this.RebuildLayout();
                });
            }
            else
            {
                UpdateText(text);
                this.RebuildLayout();
            }
        }
        else
        {
            UpdateText(text);
        }
    }
References BaseCore.actionsNextFrame, GetWidth(), BaseCore.Instance, text, UpdateText(), useHypenation, and width.
Referenced by UIText.SetText().
CHECK_HYP_BACK()
static bool HyphenationJpn.CHECK_HYP_BACK (char str) inline static private
Definition at line 224 of file HyphenationJpn.cs.
    {
        return Array.Exists(HYP_BACK, (char item) => item == str);
    }
References HYP_BACK, and item.
Referenced by GetWordList().
CHECK_HYP_FRONT()
static bool HyphenationJpn.CHECK_HYP_FRONT (char str) inline static private
Definition at line 219 of file HyphenationJpn.cs.
    {
        return Array.Exists(HYP_FRONT, (char item) => item == str);
    }
References HYP_FRONT, and item.
Referenced by GetWordList().
GetFormatedText()
string HyphenationJpn.GetFormatedText (string msg) inline private
Definition at line 148 of file HyphenationJpn.cs.
    {
        if (string.IsNullOrEmpty(msg))
        {
            return string.Empty;
        }
        msg = Regex.Replace(msg, "\\n", "〒");
        float num = width;
        float spaceWidth = GetSpaceWidth();
        _Text.horizontalOverflow = HorizontalWrapMode.Overflow;
        StringBuilder stringBuilder = new StringBuilder();
        float num2 = 0f;
        foreach (string word in GetWordList(msg))
        {
            string text = word;
            num2 += GetTextWidth(text);
            if (text.StartsWith("〒"))
            {
                num2 = 0f;
                stringBuilder.AppendLine();
                text = text.Replace("〒", "");
            }
            if (text == "〒")
            {
                num2 = 0f;
                stringBuilder.AppendLine();
                continue;
            }
            if (text == " ")
            {
                num2 += spaceWidth;
            }
            if (num2 > num - (float)padding)
            {
                stringBuilder.Append(Environment.NewLine);
                num2 = GetTextWidth(text);
            }
            stringBuilder.Append(text);
        }
        return stringBuilder.ToString();
    }
References GetSpaceWidth(), GetTextWidth(), GetWordList(), padding, text, and width.
Referenced by UpdateText().
GetSpaceWidth()
float HyphenationJpn.GetSpaceWidth () inline private
Definition at line 131 of file HyphenationJpn.cs.
    {
        float textWidth = GetTextWidth("m m");
        float textWidth2 = GetTextWidth("mm");
        return textWidth - textWidth2;
    }
References GetTextWidth().
Referenced by GetFormatedText().
GetTextWidth()
float HyphenationJpn.GetTextWidth (string message) inline private
Definition at line 138 of file HyphenationJpn.cs.
    {
        if (_text.supportRichText)
        {
            message = Regex.Replace(message, RITCH_TEXT_REPLACE, string.Empty);
        }
        _Text.text = message;
        return _Text.preferredWidth;
    }
References _text, _Text, Empty, and RITCH_TEXT_REPLACE.
Referenced by GetFormatedText(), and GetSpaceWidth().
GetWidth()
float HyphenationJpn.GetWidth () inline
Definition at line 108 of file HyphenationJpn.cs.
    {
        if (usePreferredWidth)
        {
            LayoutElement component = GetComponent<LayoutElement>();
            if ((bool)component && component.enabled && component.preferredWidth != -1f)
            {
                return component.preferredWidth;
            }
        }
        if ((bool)base.transform.parent && useParentWidth)
        {
            LayoutGroup component2 = base.transform.parent.GetComponent<LayoutGroup>();
            float num = base.transform.parent.Rect().rect.width;
            if ((bool)component2)
            {
                num = num - (float)component2.padding.left - (float)component2.padding.right;
            }
            return num;
        }
        return _RectTransform.rect.width;
    }
References _RectTransform, useParentWidth, and usePreferredWidth.
Referenced by _SetText().
GetWordList()
List< string > HyphenationJpn.GetWordList (string tmpText) inline private
Definition at line 190 of file HyphenationJpn.cs.
    {
        List<string> list = new List<string>();
        StringBuilder stringBuilder = new StringBuilder();
        char c = '\0';
        bool flag = false;
        for (int i = 0; i < tmpText.Length; i++)
        {
            char c2 = tmpText[i];
            char c3 = ((i < tmpText.Length - 1) ? tmpText[i + 1] : c);
            char c4 = ((i <= 0) ? c : (c4 = tmpText[i - 1]));
            if (c2 == '<')
            {
                flag = true;
            }
            if (c2 == '>')
            {
                flag = false;
            }
            stringBuilder.Append(c2);
            if (!flag && ((IsLatin(c2) && IsLatin(c4) && IsLatin(c2) && !IsLatin(c4)) || (!IsLatin(c2) && CHECK_HYP_BACK(c4)) || (!IsLatin(c3) && !CHECK_HYP_FRONT(c3) && !CHECK_HYP_BACK(c2)) || i == tmpText.Length - 1))
            {
                list.Add(stringBuilder.ToString());
                stringBuilder = new StringBuilder();
            }
        }
        return list;
    }
References CHECK_HYP_BACK(), CHECK_HYP_FRONT(), and IsLatin().
Referenced by GetFormatedText().
IsLatin()
static bool HyphenationJpn.IsLatin (char s) inline static private
Definition at line 229 of file HyphenationJpn.cs.
    {
        return false;
    }
Referenced by GetWordList().
UpdateText()
void HyphenationJpn.UpdateText (string str) inline private
Definition at line 62 of file HyphenationJpn.cs.
    {
        if (useHypenation)
        {
            _Text.text = GetFormatedText(str).IsEmpty(str);
        }
    }
References GetFormatedText(), and useHypenation.
Referenced by _SetText().
Member Data Documentation
_rectTransform
RectTransform HyphenationJpn._rectTransform private
Definition at line 24 of file HyphenationJpn.cs.
_text
Text HyphenationJpn._text private
Definition at line 26 of file HyphenationJpn.cs.
Referenced by GetTextWidth().
evaluateLate
bool HyphenationJpn.evaluateLate
Definition at line 18 of file HyphenationJpn.cs.
Referenced by UIText.SetText().
HYP_BACK
readonly char [] HyphenationJpn.HYP_BACK = "(（[｛〔〈《「『【〘〖〝‘“｟«".ToCharArray() static private
Definition at line 34 of file HyphenationJpn.cs.
Referenced by CHECK_HYP_BACK().
HYP_FRONT
readonly char [] HyphenationJpn.HYP_FRONT = ",)]｝、。）〕〉》」』】〙〗〟’”｠»ァィゥェォッャュョヮヵヶっぁぃぅぇぉっゃゅょゎ‐゠–〜ー?!！？‼⁇⁈⁉・:;。.".ToCharArray() static private
Definition at line 32 of file HyphenationJpn.cs.
Referenced by CHECK_HYP_FRONT().
HYP_LATIN
readonly char [] HyphenationJpn.HYP_LATIN = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789<>=/().,".ToCharArray() static private
Definition at line 36 of file HyphenationJpn.cs.
padding
int HyphenationJpn.padding
Definition at line 12 of file HyphenationJpn.cs.
Referenced by GetFormatedText().
RITCH_TEXT_REPLACE
readonly string HyphenationJpn.RITCH_TEXT_REPLACE = "(\<color=.*\>|</color>|\<size=.n\\>|</size>|<b>|</b>|<i>|</i>)" static private
Definition at line 30 of file HyphenationJpn.cs.
Referenced by GetTextWidth().
text
string HyphenationJpn.text private
Definition at line 20 of file HyphenationJpn.cs.
Referenced by _SetText(), and GetFormatedText().
useHypenation
bool HyphenationJpn.useHypenation private
Definition at line 22 of file HyphenationJpn.cs.
Referenced by _SetText(), and UpdateText().
useParentWidth
bool HyphenationJpn.useParentWidth = true
Definition at line 14 of file HyphenationJpn.cs.
Referenced by GetWidth().
usePreferredWidth
bool HyphenationJpn.usePreferredWidth = true
Definition at line 16 of file HyphenationJpn.cs.
Referenced by GetWidth().
width
float HyphenationJpn.width private
Definition at line 28 of file HyphenationJpn.cs.
Referenced by _SetText(), and GetFormatedText().
Property Documentation
_RectTransform
RectTransform HyphenationJpn._RectTransform get private
Definition at line 38 of file HyphenationJpn.cs.
    {
        get
        {
            if (_rectTransform == null)
            {
                _rectTransform = GetComponent<RectTransform>();
            }
            return _rectTransform;
        }
    }
Referenced by GetWidth().
_Text
Text HyphenationJpn._Text get
Definition at line 50 of file HyphenationJpn.cs.
    {
        get
        {
            if (_text == null)
            {
                _text = GetComponent<Text>();
            }
            return _text;
        }
    }
Referenced by GetTextWidth().
The documentation for this class was generated from the following file:
Elin/Plugins.UI/HyphenationJpn.cs