Elin Decompiled Documentation: CraftUtil Class Reference
CraftUtil Class Reference
Public Types
enum MixType { General , Food , NoMix }
enum WrapType { Love , Dark }
Static Public Member Functions
static void ModRandomFoodEnc (Thing t)
static void AddRandomFoodEnc (Thing t)
static void MakeDish (Thing food, int lv, Chara crafter=null, int seed=-1)
static string GetBloodText (Chara c)
static Thing MakeBloodMeal (Chara sucker, Chara feeder, bool msg=true)
static Thing MakeBloodSample (Chara sucker, Chara feeder)
static Thing MakeDarkSoup ()
static Thing GetRandomDarkSoupIngredient (Chara c)
static Thing MakeLoveLunch (Chara c)
static Thing GetRandomLoveLunchIngredient (Chara c)
static void WrapIngredient (Card product, Chara c, Card ing, WrapType wrapType)
static void MakeDish (Card food, List< Thing > ings, int qualityBonus, Chara crafter=null)
static Thing MixIngredients (string idProduct, List< Thing > ings, MixType type, int idMat=0, Chara crafter=null)
static Card MixIngredients (Card product, List< Thing > ings, MixType type, int maxQuality, Chara crafter=null)
Static Public Member Functions inherited from EClass
static int rndSeed (int a, int seed)
static int rnd (long a)
static int rnd (int a)
static int curve (int _a, int start, int step, int rate=75)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Static Public Attributes
static string[] ListFoodEffect = new string[2] { "exp", "pot" }
Static Public Attributes inherited from EClass
static Core core
Additional Inherited Members
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Detailed Description
Definition at line 5 of file CraftUtil.cs.
Member Enumeration Documentation
MixType
enum CraftUtil.MixType
Enumerator
General
Food
NoMix
Definition at line 7 of file CraftUtil.cs.
    {
        General,
        Food,
        NoMix
    }
WrapType
enum CraftUtil.WrapType
Enumerator
Love
Dark
Definition at line 14 of file CraftUtil.cs.
    {
        Love,
        Dark
    }
Member Function Documentation
AddRandomFoodEnc()
static void CraftUtil.AddRandomFoodEnc (Thing t) inline static
Definition at line 43 of file CraftUtil.cs.
    {
        List<SourceElement.Row> list = EClass.sources.elements.rows.Where((SourceElement.Row e) => e.foodEffect.Length > 1 && ListFoodEffect.Contains(e.foodEffect[0])).ToList();
        list.ForeachReverse(delegate(SourceElement.Row e)
        {
            if (t.elements.dict.ContainsKey(e.id))
            {
                list.Remove(e);
            }
        });
        if (list.Count != 0)
        {
            SourceElement.Row row = list.RandomItemWeighted((SourceElement.Row a) => a.chance);
            t.elements.SetBase(row.id, 1);
            t.c_seed = row.id;
        }
    }
References SourceManager.elements, ListFoodEffect, and EClass.sources.
Referenced by TraitSeed.LevelSeed().
GetBloodText()
static string CraftUtil.GetBloodText (Chara c) inline static
Definition at line 117 of file CraftUtil.cs.
    {
        string text = "";
        List<Element> list = MakeBloodMeal(EClass.pc, c, msg: false).elements.ListElements((Element e) => e.IsFoodTraitMain, (Element a, Element b) => b.Value - a.Value);
        int num = Mathf.Min(list.Count(), 3, EClass.debug.godMode ? 3 : (1 + EClass.pc.Evalue(6607) / 15));
        for (int i = 0; i < num; i++)
        {
            Element element = list[i];
            string[] textArray = element.source.GetTextArray("textAlt");
            int num2 = Mathf.Clamp(element.Value / 10 + 1, (element.Value < 0 || textArray.Length <= 2) ? 1 : 2, textArray.Length - 1);
            string text2 = textArray[num2];
            if (i != 0)
            {
                text += ", ";
            }
            text += text2;
        }
        if (!text.IsEmpty())
        {
            text = " (" + text + ")";
        }
        return text;
    }
References EClass.debug, Card.Evalue(), CoreDebug.godMode, Element.IsFoodTraitMain, EClass.pc, Element.source, and Element.Value.
Referenced by Chara.GetHoverText().
GetRandomDarkSoupIngredient()
static Thing CraftUtil.GetRandomDarkSoupIngredient (Chara c) inline static
Definition at line 202 of file CraftUtil.cs.
    {
        return ThingGen.CreateFromFilter("darksoup", c.LV);
    }
References ThingGen.CreateFromFilter(), and Card.LV.
GetRandomLoveLunchIngredient()
static Thing CraftUtil.GetRandomLoveLunchIngredient (Chara c) inline static
Definition at line 236 of file CraftUtil.cs.
    {
        Thing thing = null;
        for (int i = 0; i < 3; i++)
        {
            thing = ThingGen.Create("dish", -1, c.Evalue(287) + 5 + (EClass.debug.enable ? c.LV : 0));
            if (!thing.HasTag(CTAG.dish_fail))
            {
                break;
            }
        }
        MakeDish(thing, c.LV, c);
        return thing;
    }
References ThingGen.Create(), EClass.debug, CoreDebug.enable, Card.Evalue(), Card.HasTag(), and Card.LV.
MakeBloodMeal()
static Thing CraftUtil.MakeBloodMeal (Chara sucker, Chara feeder, bool msg = true) inline static
Definition at line 141 of file CraftUtil.cs.
    {
        Thing c_bloodData = feeder.c_bloodData;
        if (c_bloodData == null)
        {
            int num = ((feeder.GetInt(118) == 0) ? (EClass.game.seed + feeder.uid) : feeder.GetInt(118));
            Rand.SetSeed(num);
            c_bloodData = ThingGen.CreateFromCategory("meal", 100);
            if (msg)
            {
                sucker.Say("food_blood", c_bloodData);
            }
            MakeDish(c_bloodData, 100, null, num + feeder.uid);
            c_bloodData.elements.SetTo(709, 0);
            c_bloodData.elements.SetTo(708, 0);
            c_bloodData.elements.SetTo(701, 0);
            feeder.c_bloodData = c_bloodData.Duplicate(1);
        }
        else
        {
            c_bloodData = c_bloodData.Duplicate(1);
            if (msg)
            {
                sucker.Say("food_blood", c_bloodData);
            }
        }
        c_bloodData.elements.SetTo(2, Mathf.Min(EClass.curve(feeder.LV, 30, 10, 65), 200));
        c_bloodData.elements.ModBase(710, 15 + (int)Mathf.Min(Mathf.Sqrt(sucker.Evalue(6607) + Mathf.Max(sucker.LER, 0)), 55f));
        return c_bloodData;
    }
References Card.c_bloodData, ThingGen.CreateFromCategory(), EClass.curve(), Card.Duplicate(), Card.elements, Card.Evalue(), EClass.game, BaseCard.GetInt(), Card.LER, Card.LV, ElementContainer.ModBase(), Card.Say(), Game.seed, Rand.SetSeed(), ElementContainer.SetTo(), and Card.uid.
Referenced by AI_Fuck.Finish(), and CoreDebug.UpdateInput().
MakeBloodSample()
static Thing CraftUtil.MakeBloodSample (Chara sucker, Chara feeder) inline static
Definition at line 172 of file CraftUtil.cs.
    {
        Thing thing = MakeBloodMeal(sucker, feeder);
        Thing thing2 = ThingGen.Create("bloodsample");
        foreach (Element value in thing.elements.dict.Values)
        {
            thing2.elements.SetTo(value.id, value.Value);
        }
        thing2.elements.SetTo(10, 0);
        thing2.MakeRefFrom(feeder);
        thing2.c_idRefCard = thing.id;
        thing2.SetInt(118, EClass.game.seed + feeder.uid);
        return thing2;
    }
References ThingGen.Create(), Card.elements, EClass.game, Element.id, Game.seed, ElementContainer.SetTo(), and Element.Value.
MakeDarkSoup()
static Thing CraftUtil.MakeDarkSoup () inline static
Definition at line 187 of file CraftUtil.cs.
    {
        Thing thing = ThingGen.Create("soup_dark");
        for (int i = 0; i < 4 + EClass.rnd(4); i++)
        {
            Chara c = EClass._map.charas.RandomItem();
            WrapIngredient(thing, c, GetRandomDarkSoupIngredient(c), WrapType.Dark);
        }
        if (!EClass.debug.autoIdentify)
        {
            thing.c_IDTState = 1;
        }
        return thing;
    }
References EClass._map, CoreDebug.autoIdentify, Map.charas, ThingGen.Create(), EClass.debug, and EClass.rnd().
MakeDish() [1/2]
static void CraftUtil.MakeDish (Card food, List< Thing > ings, int qualityBonus, Chara crafter = null) inline static
Definition at line 297 of file CraftUtil.cs.
    {
        List<Thing> list = new List<Thing>();
        bool flag = food.sourceCard.vals.Contains("fixed");
        for (int i = 0; i < ings.Count; i++)
        {
            Thing thing = ings[i];
            if (flag)
            {
                list.Add(thing);
                break;
            }
            if (!IsIgnoreName(thing))
            {
                list.Add(thing);
            }
        }
        if (list.Count > 0)
        {
            Thing thing2 = list.RandomItem();
            if (thing2 != null)
            {
                food.MakeRefFrom(thing2);
                if (thing2.c_idRefCard != null)
                {
                    food.c_idRefCard = thing2.c_idRefCard;
                    food.c_altName = food.TryGetFoodName(thing2);
                    if (thing2.id == "_egg" || thing2.id == "egg_fertilized")
                    {
                        food.c_altName = "_egg".lang(food.c_altName);
                    }
                }
            }
        }
        MixIngredients(food, ings, MixType.Food, qualityBonus, crafter);
        static bool IsIgnoreName(Card t)
        {
            if (t == null)
            {
                return true;
            }
            switch (t.sourceCard._origin)
            {
            case "dough":
            case "dish":
            case "dish_lunch":
                return true;
            default:
                return false;
            }
        }
    }
References CardRow._origin, Card.Add(), Card.c_idRefCard, food, Card.id, and Card.sourceCard.
MakeDish() [2/2]
static void CraftUtil.MakeDish (Thing food, int lv, Chara crafter = null, int seed = -1) inline static
Definition at line 61 of file CraftUtil.cs.
    {
        RecipeManager.BuildList();
        List<Thing> list = new List<Thing>();
        RecipeSource recipeSource = RecipeManager.Get(food.id);
        if (recipeSource == null || !recipeSource.IsCraftable())
        {
            return;
        }
        SetSeed();
        int num = Mathf.Min(EClass.rnd(lv), 50);
        foreach (Recipe.Ingredient ingredient in recipeSource.GetIngredients())
        {
            SetSeed();
            Thing thing = ThingGen.Create(ingredient.id, -1, lv);
            if (thing.id == "deadbody")
            {
                thing = ThingGen.Create("_meat");
            }
            SetSeed();
            thing = thing.TryMakeRandomItem(lv, TryMakeRandomItemSource.Cooking, crafter);
            SetSeed();
            TraitSeed.LevelSeed(thing, null, EClass.rnd(lv / 4) + 1);
            thing.SetEncLv(thing.encLV / 2);
            if (num > 0 && EClass.rnd(3) == 0)
            {
                thing.elements.SetBase(2, num);
            }
            list.Add(thing);
        }
        MakeDish(food, list, num, crafter);
        if (crafter != null && crafter.id != "rodwyn")
        {
            if (food.HasElement(709))
            {
                food.elements.Remove(709);
            }
            if (food.HasElement(708) && !crafter.HasElement(1205))
            {
                food.elements.Remove(708);
            }
        }
        if (seed != -1)
        {
            Rand.SetSeed();
        }
        void SetSeed()
        {
            if (seed != -1)
            {
                Rand.SetSeed(seed);
                seed++;
            }
        }
    }
References RecipeManager.BuildList(), ThingGen.Create(), Card.elements, Card.encLV, food, RecipeManager.Get(), RecipeSource.GetIngredients(), Card.id, RecipeSource.IsCraftable(), TraitSeed.LevelSeed(), EClass.rnd(), seed, ElementContainer.SetBase(), Card.SetEncLv(), Rand.SetSeed(), and Card.TryMakeRandomItem().
Referenced by FactionBranch.DailyOutcome(), RecipeCard.MakeDish(), Trait.OnBarter(), Map.TryShatter(), and TraitFoodEgg.Update().
MakeLoveLunch()
static Thing CraftUtil.MakeLoveLunch (Chara c) inline static
Definition at line 207 of file CraftUtil.cs.
    {
        Thing thing = ThingGen.Create("lunch_love");
        thing.MakeRefFrom(c);
        int num = c.uid + EClass.world.date.year * 10000 + EClass.world.date.month * 100;
        Rand.SetSeed(num);
        float num2 = Mathf.Clamp(1f + Mathf.Sqrt(c.Evalue(287) / 5), 2f, 6f);
        if (!EClass.debug.autoIdentify)
        {
            thing.c_IDTState = 5;
        }
        for (int i = 0; (float)i < num2; i++)
        {
            Rand.SetSeed(num + i);
            WrapIngredient(thing, c, GetRandomLoveLunchIngredient(c), WrapType.Love);
        }
        thing.elements.SetBase(701, 0);
        if (thing.Evalue(753) < 0)
        {
            thing.elements.SetBase(753, 0);
        }
        if (EClass.pc.HasElement(1250) && !thing.HasElement(710))
        {
            thing.elements.SetBase(710, 1);
        }
        Rand.SetSeed();
        return thing;
    }
References CoreDebug.autoIdentify, ThingGen.Create(), EClass.debug, Card.elements, Card.Evalue(), Card.HasElement(), Card.MakeRefFrom(), EClass.pc, ElementContainer.SetBase(), and Rand.SetSeed().
Referenced by Trait.OnBarter(), Chara.ShowDialog(), and CoreDebug.UpdateInput().
MixIngredients() [1/2]
static Card CraftUtil.MixIngredients (Card product, List< Thing > ings, MixType type, int maxQuality, Chara crafter = null) inline static
Definition at line 361 of file CraftUtil.cs.
    {
        bool noMix = type == MixType.NoMix || product.HasTag(CTAG.noMix);
        bool isFood = type == MixType.Food;
        int nutFactor = 100 - (ings.Count - 1) * 5;
        Thing thing = ((ings.Count > 0) ? ings[0] : null);
        bool creative = crafter?.HasElement(487) ?? false;
        if (crafter != null && crafter.Evalue(1650) >= 3)
        {
            nutFactor -= 10;
        }
        if (!noMix)
        {
            foreach (Element value2 in product.elements.dict.Values)
            {
                int id = value2.id;
                if ((uint)(id - 914) > 1u && value2.Value >= 0 && (value2.HasTag("noInherit") || IsValidTrait(value2)))
                {
                    product.elements.SetTo(value2.id, 0);
                }
            }
        }
        if (product.HasCraftBonusTrait())
        {
            foreach (Element item in product.ListCraftBonusTraits())
            {
                product.elements.ModBase(item.id, item.Value);
            }
        }
        if (isFood)
        {
            product.elements.SetTo(10, 5);
        }
        int num = 0;
        int num2 = 0;
        int num3 = 0;
        foreach (Thing ing in ings)
        {
            if (ing != null)
            {
                MixElements(ing);
                num3 += ing.c_priceCopy;
                if (isFood)
                {
                    num += Mathf.Clamp(ing.SelfWeight * 80 / 100, 50, 400 + ing.SelfWeight / 20);
                    int value = ing.GetValue();
                    num2 += value;
                }
                if (product.id == "1300" && product.GetInt(118) == 0)
                {
                    product.SetInt(118, ing.GetInt(118));
                    product.c_idRefCard = ing.c_idRefCard;
                }
            }
        }
        if (isFood)
        {
            product.isWeightChanged = true;
            product.c_weight = num;
            product.c_priceAdd = num2;
        }
        product.c_priceCopy = num3;
        if (thing != null && product.trait is TraitFoodFishSlice)
        {
            product.elements.SetTo(10, thing.Evalue(10) / 4);
            product.isWeightChanged = true;
            product.c_weight = Mathf.Min(thing.SelfWeight / 6, 1000);
            product.c_idRefCard = thing.id;
            product.c_priceCopy = ((thing.c_priceCopy == 0) ? thing.GetValue() : thing.c_priceCopy);
            product.c_fixedValue = ((thing.c_fixedValue == 0) ? thing.sourceCard.value : thing.c_fixedValue) / 4;
            product.c_priceAdd = 0;
            product.decay = thing.decay;
            product.elements.SetBase(707, 1);
            product.SetTier(thing.tier, setTraits: false);
            product.idSkin = ((thing.trait is TraitFoodFishSlice) ? thing.idSkin : (thing.HasTag(CTAG.bigFish) ? 1 : 0));
        }
        if (product.HasElement(652))
        {
            product.ChangeWeight((isFood ? num : product.Thing.source.weight) * 100 / (100 + product.Evalue(652)));
        }
        if (product.elements.Value(2) > maxQuality)
        {
            product.elements.SetTo(2, maxQuality);
        }
        string id2 = product.id;
        if (!(id2 == "zassouni"))
        {
            if (id2 == "map")
            {
                int num4 = 1 + product.Evalue(2) + product.Evalue(751);
                if (num4 < 1)
                {
                    num4 = 1;
                }
                foreach (Thing ing2 in ings)
                {
                    if (ing2 != null && ing2.Thing != null && !(ing2.id != "gem"))
                    {
                        num4 *= ing2.Thing.material.hardness / 20 + 2;
                    }
                }
                if (num4 > EClass.pc.FameLv + 10 - 1)
                {
                    num4 = EClass.pc.FameLv + 10 - 1;
                }
                product.SetInt(25, num4);
            }
        }
        else
        {
            product.elements.ModBase(10, 6);
        }
        if (product.HasElement(762))
        {
            product.elements.ModBase(10, product.Evalue(762) / 5);
            if (product.Evalue(10) < 1)
            {
                product.elements.SetTo(10, 1);
            }
        }
        if (creative && isFood && product.category.IsChildOf("meal"))
        {
            product.elements.SetBase(764, 1);
        }
        return product;
        bool IsValidTrait(Element e)
        {
            if (e.HasTag("noInherit"))
            {
                return false;
            }
            switch (type)
            {
            case MixType.General:
                if (e.IsTrait)
                {
                    return true;
                }
                if (e.IsFoodTrait)
                {
                    return product.IsInheritFoodTraits;
                }
                break;
            case MixType.Food:
                if (e.IsFoodTrait || e.IsTrait || e.id == 2)
                {
                    return true;
                }
                break;
            }
            return false;
        }
        void MixElements(Card t)
        {
            if (t != null)
            {
                foreach (Element value3 in t.elements.dict.Values)
                {
                    if (IsValidTrait(value3) && (!noMix || value3.id == 2))
                    {
                        if (isFood && value3.IsFoodTraitMain)
{
                            int num5 = value3.Value;
                            if (product.id == "lunch_dystopia")
{
                                num5 *= -1;
                            }
                            if (creative && num5 > 500)
{
                                num5 = 500;
                            }
                            product.elements.ModBase(value3.id, num5);
                        }
                        else
{
                            int num6 = product.elements.Base(value3.id);
                            if ((num6 <= 0 && value3.Value < 0 && value3.Value < num6) || (value3.Value > 0 && value3.Value > num6))
{
                                product.elements.SetTo(value3.id, value3.Value);
                            }
                        }
                    }
                }
                if (isFood)
                {
                    product.elements.ModBase(10, t.Evalue(10) * nutFactor / 100);
                }
            }
        }
    }
References Card.c_idRefCard, Card.c_priceCopy, ElementContainer.dict, Card.elements, Card.Evalue(), Card.FameLv, BaseCard.GetInt(), Card.GetValue(), Card.HasCraftBonusTrait(), Card.HasElement(), Card.HasTag(), Element.HasTag(), Card.id, Element.id, Element.IsFoodTrait, Element.IsFoodTraitMain, Element.IsTrait, item, Card.ListCraftBonusTraits(), ElementContainer.ModBase(), noMix, EClass.pc, Thing.SelfWeight, ElementContainer.SetTo(), Card.Thing, and Element.Value.
MixIngredients() [2/2]
static Thing CraftUtil.MixIngredients (string idProduct, List< Thing > ings, MixType type, int idMat = 0, Chara crafter = null) inline static
Definition at line 350 of file CraftUtil.cs.
    {
        Thing thing = ThingGen.Create(idProduct);
        if (idMat != 0)
        {
            thing.ChangeMaterial(idMat);
        }
        MixIngredients(thing, ings, type, 999, crafter);
        return thing;
    }
References Card.ChangeMaterial(), and ThingGen.Create().
Referenced by TraitCrafter.Craft(), RecipeCard.MixIngredients(), TraitBrewery.OnChildDecay(), and TaskChopWood.OnCreateProgress().
ModRandomFoodEnc()
static void CraftUtil.ModRandomFoodEnc (Thing t) inline static
Definition at line 22 of file CraftUtil.cs.
    {
        List<Element> list = new List<Element>();
        foreach (Element value in t.elements.dict.Values)
        {
            if (value.IsFoodTrait)
            {
                list.Add(value);
            }
        }
        if (list.Count != 0)
        {
            Element element = list.RandomItem();
            t.elements.ModBase(element.id, EClass.rnd(6) + 1);
            if (element.Value > 60)
            {
                t.elements.SetTo(element.id, 60);
            }
        }
    }
References Element.id, Element.IsFoodTrait, EClass.rnd(), and Element.Value.
Referenced by TraitSeed.LevelSeed().
WrapIngredient()
static void CraftUtil.WrapIngredient (Card product, Chara c, Card ing, WrapType wrapType) inline static
Definition at line 251 of file CraftUtil.cs.
    {
        if (product.c_mixedFoodData == null)
        {
            product.c_mixedFoodData = new MixedFoodData();
        }
        product.c_mixedFoodData.texts.Add(ing.Name + ((wrapType == WrapType.Dark) ? "isMixedBy".lang(c.NameSimple) : ""));
        foreach (Element value in ing.elements.dict.Values)
        {
            if (!IsValidTrait(value))
            {
                continue;
            }
            if (value.IsFoodTraitMain)
            {
                int num = value.Value;
                if (ing.id == "lunch_dystopia" && (wrapType == WrapType.Dark || num < 0))
                {
                    num *= -1;
                }
                product.elements.ModBase(value.id, num);
            }
            else
            {
                int num2 = product.elements.Base(value.id);
                if ((num2 <= 0 && value.Value < 0 && value.Value < num2) || (value.Value > 0 && value.Value > num2))
                {
                    product.elements.SetTo(value.id, value.Value);
                }
            }
        }
        product.elements.ModBase(10, ing.Evalue(10));
        static bool IsValidTrait(Element e)
        {
            if (e.HasTag("noInherit"))
            {
                return false;
            }
            if (e.IsFoodTrait || e.IsTrait || e.id == 2)
            {
                return true;
            }
            return false;
        }
    }
References Card.c_mixedFoodData, Element.HasTag(), Element.id, Element.IsFoodTrait, Element.IsFoodTraitMain, Element.IsTrait, Card.Name, Card.NameSimple, MixedFoodData.texts, and Element.Value.
Member Data Documentation
ListFoodEffect
string [] CraftUtil.ListFoodEffect = new string[2] { "exp", "pot" } static
Definition at line 20 of file CraftUtil.cs.
Referenced by AddRandomFoodEnc().
The documentation for this class was generated from the following file:
Elin/CraftUtil.cs