Elin Decompiled Documentation: Empyrean.Utils.Colorist Class Reference
Empyrean.Utils.Colorist Class Reference
Static Public Member Functions
static Color Lighten (this Color c, float value=0.2f)
static Color Darken (this Color c, float value=0.2f)
static Color Inverse (this Color color)
static Color HSVtoRGB (HSVColor hsv)
static Color HSVtoRGB (float hue, float saturation, float value, float alpha=1f)
static HSVColor RGBtoHSV (Color color)
static HSVColor RGBtoHSV (float r, float g, float b, float a=1f)
static HSLColor RGBtoHSL (float r, float g, float b, float a=1f)
static HSLColor RGBtoHSL (Color color)
static HSLColor HSVtoHSL (HSVColor hsv)
static HSVColor HSLtoHSV (HSLColor hsl)
static string ColorToHex (Color32 color)
static Color HexToColor (string hex)
static Color SlightlyTransparent (Color color)
static Color SetAlpha (this Color color, float alpha=0.5f)
Static Public Attributes
static readonly Color steelBlue = new Color32(70, 130, 180, byte.MaxValue)
static readonly Color lightSteelBlue = new Color32(176, 196, 222, byte.MaxValue)
static readonly Color white32 = new Color32(byte.MaxValue, byte.MaxValue, byte.MaxValue, byte.MaxValue)
static readonly Color black = new Color32(0, 0, 0, byte.MaxValue)
static readonly Color nearlyBlack = new Color(0.1f, 0.1f, 0.1f)
static readonly Color red10 = new Color(1f, 0.9f, 0.9f)
static readonly Color red25 = new Color(1f, 0.75f, 0.75f)
static readonly Color red50 = new Color(1f, 0.5f, 0.5f)
static readonly Color red75 = new Color(1f, 0.25f, 0.25f)
static readonly Color green10 = new Color(0.9f, 1f, 0.9f)
static readonly Color green25 = new Color(0.75f, 1f, 0.75f)
static readonly Color green50 = new Color(0.5f, 1f, 0.5f)
static readonly Color green75 = new Color(0.25f, 1f, 0.25f)
static readonly Color blue10 = new Color(0.9f, 0.9f, 1f)
static readonly Color blue25 = new Color(0.75f, 0.75f, 1f)
static readonly Color blue50 = new Color(0.5f, 0.5f, 1f)
static readonly Color blue75 = new Color(0.25f, 0.25f, 1f)
static readonly Color cyan25 = new Color(0.75f, 1f, 1f)
static readonly Color cyan50 = new Color(0.5f, 1f, 1f)
static readonly Color cyan75 = new Color(0.25f, 1f, 1f)
static readonly Color magenta25 = new Color(1f, 0.75f, 1f)
static readonly Color magenta50 = new Color(1f, 0.5f, 1f)
static readonly Color magenta75 = new Color(1f, 0.25f, 1f)
static readonly Color yellow25 = new Color(1f, 1f, 0.75f)
static readonly Color yellow50 = new Color(1f, 1f, 0.5f)
static readonly Color yellow75 = new Color(1f, 1f, 0.25f)
static readonly Color transparentBlack = new Color(0f, 0f, 0f, 0f)
static readonly Color transparentWhite = new Color(1f, 1f, 1f, 0f)
static readonly Color white = new Color32(byte.MaxValue, byte.MaxValue, byte.MaxValue, byte.MaxValue)
static readonly Color red = new Color32(byte.MaxValue, 0, 0, byte.MaxValue)
static readonly Color brown = new Color32(165, 42, 42, byte.MaxValue)
static readonly Color gray = new Color32(190, 190, 190, byte.MaxValue)
static readonly Color pink = new Color32(byte.MaxValue, 192, 203, byte.MaxValue)
static readonly Color green = new Color32(0, byte.MaxValue, 0, byte.MaxValue)
static readonly Color tan = new Color32(210, 180, 140, byte.MaxValue)
static readonly Color yellow = new Color32(byte.MaxValue, byte.MaxValue, 0, byte.MaxValue)
static readonly Color maroon = new Color32(128, 0, 0, byte.MaxValue)
static readonly Color navyBlue = new Color32(0, 0, 128, byte.MaxValue)
static readonly Color magenta = new Color32(byte.MaxValue, 0, byte.MaxValue, byte.MaxValue)
static readonly Color blue = new Color32(0, 0, byte.MaxValue, byte.MaxValue)
static readonly Color aqua = new Color32(0, byte.MaxValue, byte.MaxValue, byte.MaxValue)
static readonly Color orange = new Color32(byte.MaxValue, 165, 0, byte.MaxValue)
Detailed Description
Definition at line 6 of file Colorist.cs.
Member Function Documentation
ColorToHex()
static string Empyrean.Utils.Colorist.ColorToHex (Color32 color) inline static
Definition at line 232 of file Colorist.cs.
    {
        return color.r.ToString("X2") + color.g.ToString("X2") + color.b.ToString("X2") + color.a.ToString("X2");
    }
Referenced by HexInput.SelectColor().
Darken()
static Color Empyrean.Utils.Colorist.Darken (this Color c, float value = 0::2f) inline static
Definition at line 97 of file Colorist.cs.
    {
        return new Color(c.r - value, c.g - value, c.b - value);
    }
References Color.
HexToColor()
static Color Empyrean.Utils.Colorist.HexToColor (string hex) inline static
Definition at line 237 of file Colorist.cs.
    {
        byte r = byte.Parse(hex.Substring(0, 2), NumberStyles.HexNumber);
        byte g = byte.Parse(hex.Substring(2, 2), NumberStyles.HexNumber);
        byte b = byte.Parse(hex.Substring(4, 2), NumberStyles.HexNumber);
        byte a = byte.MaxValue;
        if (hex.Length == 8)
        {
            a = byte.Parse(hex.Substring(6, 2), NumberStyles.HexNumber);
        }
        return new Color32(r, g, b, a);
    }
Referenced by HexInput.GetColorByHex().
HSLtoHSV()
static HSVColor Empyrean.Utils.Colorist.HSLtoHSV (HSLColor hsl) inline static
Definition at line 223 of file Colorist.cs.
    {
        HSVColor result = default(HSVColor);
        result.h = hsl.h;
        result.v = (2f * hsl.l + hsl.s * (1f - Mathf.Abs(2f * hsl.l - 1f))) / 2f;
        result.s = 2f * (result.v - hsl.l) / result.v;
        return result;
    }
References HSLColor.h, HSLColor.l, and HSVColor.v.
HSVtoHSL()
static HSLColor Empyrean.Utils.Colorist.HSVtoHSL (HSVColor hsv) inline static
Definition at line 214 of file Colorist.cs.
    {
        HSLColor result = default(HSLColor);
        result.h = hsv.h;
        result.l = hsv.v * (2f - hsv.s) / 2f;
        result.s = hsv.v * hsv.s / (1f - Mathf.Abs(result.l - 1f));
        return result;
    }
References HSVColor.h, HSLColor.l, and HSVColor.s.
HSVtoRGB() [1/2]
static Color Empyrean.Utils.Colorist.HSVtoRGB (float hue, float saturation, float value, float alpha = 1f) inline static
Definition at line 112 of file Colorist.cs.
    {
        int num = (int)(hue / 60f) % 6;
        float num2 = hue / 60f - (float)(int)(hue / 60f);
        float num3 = value * (1f - saturation);
        float num4 = value * (1f - num2 * saturation);
        float num5 = value * (1f - (1f - num2) * saturation);
        return num switch
        {
            0 => new Color(value, num5, num3, alpha),
            1 => new Color(num4, value, num3, alpha),
            2 => new Color(num3, value, num5, alpha),
            3 => new Color(num3, num4, value, alpha),
            4 => new Color(num5, num3, value, alpha),
            _ => new Color(value, num3, num4, alpha),
        };
    }
References Color.
HSVtoRGB() [2/2]
static Color Empyrean.Utils.Colorist.HSVtoRGB (HSVColor hsv) inline static
Definition at line 107 of file Colorist.cs.
    {
        return HSVtoRGB(hsv.h, hsv.s, hsv.v, hsv.a);
    }
References HSVColor.a, HSVColor.h, Empyrean.Utils.Colorist.HSVtoRGB(), HSVColor.s, and HSVColor.v.
Referenced by Empyrean.ColorPicker.HueSlider.GenerateHsvSpectrum(), Empyrean.ColorPicker.ColorPalette.GeneratePaletteTexture(), Empyrean.Utils.Colorist.HSVtoRGB(), SelectedColorController.Select(), and Empyrean.Utils.Extensions.ToRGB().
Inverse()
static Color Empyrean.Utils.Colorist.Inverse (this Color color) inline static
Definition at line 102 of file Colorist.cs.
    {
        return new Color(1f - color.r, 1f - color.g, 1f - color.b, color.a);
    }
References Color.
Lighten()
static Color Empyrean.Utils.Colorist.Lighten (this Color c, float value = 0::2f) inline static
Definition at line 92 of file Colorist.cs.
    {
        return new Color(c.r + value, c.g + value, c.b + value);
    }
References Color.
RGBtoHSL() [1/2]
static HSLColor Empyrean.Utils.Colorist.RGBtoHSL (Color color) inline static
Definition at line 209 of file Colorist.cs.
    {
        return RGBtoHSL(color.r, color.g, color.b, color.a);
    }
References Empyrean.Utils.Colorist.RGBtoHSL().
RGBtoHSL() [2/2]
static HSLColor Empyrean.Utils.Colorist.RGBtoHSL (float r, float g, float b, float a = 1f) inline static
Definition at line 174 of file Colorist.cs.
    {
        HSLColor result = default(HSLColor);
        float num = Mathf.Max(r, g, b);
        float num2 = Mathf.Min(r, g, b);
        float num3 = num - num2;
        result.a = a;
        if (num == 0f || num2 == 1f || num3 == 0f)
        {
            result.h = 0f;
            result.s = 0f;
            return result;
        }
        if (num == r)
        {
            result.h = (g - b) / num3;
        }
        else if (num == g)
        {
            result.h = (b - r) / num3 + 2f;
        }
        else
        {
            result.h = (r - g) / num3 + 4f;
        }
        result.h *= 60f;
        if (result.h < 0f)
        {
            result.h += 360f;
        }
        result.l = (num + num2) / 2f;
        result.s = num3 / (1f - Mathf.Abs(2f * result.l - 1f));
        return result;
    }
References HSLColor.h, and HSLColor.l.
Referenced by Empyrean.Utils.Colorist.RGBtoHSL().
RGBtoHSV() [1/2]
static HSVColor Empyrean.Utils.Colorist.RGBtoHSV (Color color) inline static
Definition at line 130 of file Colorist.cs.
    {
        if (color.r == color.g && color.g == color.b)
        {
            color.r += 0.01f;
        }
        return RGBtoHSV(color.r, color.g, color.b, color.a);
    }
References Empyrean.Utils.Colorist.RGBtoHSV().
Referenced by Empyrean.Utils.Colorist.RGBtoHSV(), SelectedColorController.Select(), and Empyrean.Utils.Extensions.ToHsv().
RGBtoHSV() [2/2]
static HSVColor Empyrean.Utils.Colorist.RGBtoHSV (float r, float g, float b, float a = 1f) inline static
Definition at line 139 of file Colorist.cs.
    {
        HSVColor result = default(HSVColor);
        float num = Mathf.Max(r, g, b);
        float num2 = Mathf.Min(r, g, b);
        float num3 = num - num2;
        result.a = a;
        if (num == 0f || num2 == 1f || num3 == 0f)
        {
            result.h = 0f;
            result.s = 0f;
            return result;
        }
        if (num == r)
        {
            result.h = (g - b) / num3;
        }
        else if (num == g)
        {
            result.h = (b - r) / num3 + 2f;
        }
        else
        {
            result.h = (r - g) / num3 + 4f;
        }
        result.h *= 60f;
        if (result.h < 0f)
        {
            result.h += 360f;
        }
        result.v = num;
        result.s = num3 / num;
        return result;
    }
References HSVColor.h.
SetAlpha()
static Color Empyrean.Utils.Colorist.SetAlpha (this Color color, float alpha = 0::5f) inline static
Definition at line 255 of file Colorist.cs.
    {
        color.a = alpha;
        return color;
    }
SlightlyTransparent()
static Color Empyrean.Utils.Colorist.SlightlyTransparent (Color color) inline static
Definition at line 250 of file Colorist.cs.
    {
        return color.SetAlpha(0.75f);
    }
Member Data Documentation
aqua
readonly Color Empyrean.Utils.Colorist.aqua = new Color32(0, byte.MaxValue, byte.MaxValue, byte.MaxValue) static
Definition at line 88 of file Colorist.cs.
black
readonly Color Empyrean.Utils.Colorist.black = new Color32(0, 0, 0, byte.MaxValue) static
Definition at line 14 of file Colorist.cs.
blue
readonly Color Empyrean.Utils.Colorist.blue = new Color32(0, 0, byte.MaxValue, byte.MaxValue) static
Definition at line 86 of file Colorist.cs.
blue10
readonly Color Empyrean.Utils.Colorist.blue10 = new Color(0.9f, 0.9f, 1f) static
Definition at line 34 of file Colorist.cs.
blue25
readonly Color Empyrean.Utils.Colorist.blue25 = new Color(0.75f, 0.75f, 1f) static
Definition at line 36 of file Colorist.cs.
blue50
readonly Color Empyrean.Utils.Colorist.blue50 = new Color(0.5f, 0.5f, 1f) static
Definition at line 38 of file Colorist.cs.
blue75
readonly Color Empyrean.Utils.Colorist.blue75 = new Color(0.25f, 0.25f, 1f) static
Definition at line 40 of file Colorist.cs.
brown
readonly Color Empyrean.Utils.Colorist.brown = new Color32(165, 42, 42, byte.MaxValue) static
Definition at line 68 of file Colorist.cs.
cyan25
readonly Color Empyrean.Utils.Colorist.cyan25 = new Color(0.75f, 1f, 1f) static
Definition at line 42 of file Colorist.cs.
cyan50
readonly Color Empyrean.Utils.Colorist.cyan50 = new Color(0.5f, 1f, 1f) static
Definition at line 44 of file Colorist.cs.
cyan75
readonly Color Empyrean.Utils.Colorist.cyan75 = new Color(0.25f, 1f, 1f) static
Definition at line 46 of file Colorist.cs.
gray
readonly Color Empyrean.Utils.Colorist.gray = new Color32(190, 190, 190, byte.MaxValue) static
Definition at line 70 of file Colorist.cs.
green
readonly Color Empyrean.Utils.Colorist.green = new Color32(0, byte.MaxValue, 0, byte.MaxValue) static
Definition at line 74 of file Colorist.cs.
green10
readonly Color Empyrean.Utils.Colorist.green10 = new Color(0.9f, 1f, 0.9f) static
Definition at line 26 of file Colorist.cs.
green25
readonly Color Empyrean.Utils.Colorist.green25 = new Color(0.75f, 1f, 0.75f) static
Definition at line 28 of file Colorist.cs.
green50
readonly Color Empyrean.Utils.Colorist.green50 = new Color(0.5f, 1f, 0.5f) static
Definition at line 30 of file Colorist.cs.
green75
readonly Color Empyrean.Utils.Colorist.green75 = new Color(0.25f, 1f, 0.25f) static
Definition at line 32 of file Colorist.cs.
lightSteelBlue
readonly Color Empyrean.Utils.Colorist.lightSteelBlue = new Color32(176, 196, 222, byte.MaxValue) static
Definition at line 10 of file Colorist.cs.
magenta
readonly Color Empyrean.Utils.Colorist.magenta = new Color32(byte.MaxValue, 0, byte.MaxValue, byte.MaxValue) static
Definition at line 84 of file Colorist.cs.
magenta25
readonly Color Empyrean.Utils.Colorist.magenta25 = new Color(1f, 0.75f, 1f) static
Definition at line 48 of file Colorist.cs.
magenta50
readonly Color Empyrean.Utils.Colorist.magenta50 = new Color(1f, 0.5f, 1f) static
Definition at line 50 of file Colorist.cs.
magenta75
readonly Color Empyrean.Utils.Colorist.magenta75 = new Color(1f, 0.25f, 1f) static
Definition at line 52 of file Colorist.cs.
maroon
readonly Color Empyrean.Utils.Colorist.maroon = new Color32(128, 0, 0, byte.MaxValue) static
Definition at line 80 of file Colorist.cs.
navyBlue
readonly Color Empyrean.Utils.Colorist.navyBlue = new Color32(0, 0, 128, byte.MaxValue) static
Definition at line 82 of file Colorist.cs.
nearlyBlack
readonly Color Empyrean.Utils.Colorist.nearlyBlack = new Color(0.1f, 0.1f, 0.1f) static
Definition at line 16 of file Colorist.cs.
orange
readonly Color Empyrean.Utils.Colorist.orange = new Color32(byte.MaxValue, 165, 0, byte.MaxValue) static
Definition at line 90 of file Colorist.cs.
pink
readonly Color Empyrean.Utils.Colorist.pink = new Color32(byte.MaxValue, 192, 203, byte.MaxValue) static
Definition at line 72 of file Colorist.cs.
red
readonly Color Empyrean.Utils.Colorist.red = new Color32(byte.MaxValue, 0, 0, byte.MaxValue) static
Definition at line 66 of file Colorist.cs.
red10
readonly Color Empyrean.Utils.Colorist.red10 = new Color(1f, 0.9f, 0.9f) static
Definition at line 18 of file Colorist.cs.
red25
readonly Color Empyrean.Utils.Colorist.red25 = new Color(1f, 0.75f, 0.75f) static
Definition at line 20 of file Colorist.cs.
red50
readonly Color Empyrean.Utils.Colorist.red50 = new Color(1f, 0.5f, 0.5f) static
Definition at line 22 of file Colorist.cs.
red75
readonly Color Empyrean.Utils.Colorist.red75 = new Color(1f, 0.25f, 0.25f) static
Definition at line 24 of file Colorist.cs.
steelBlue
readonly Color Empyrean.Utils.Colorist.steelBlue = new Color32(70, 130, 180, byte.MaxValue) static
Definition at line 8 of file Colorist.cs.
tan
readonly Color Empyrean.Utils.Colorist.tan = new Color32(210, 180, 140, byte.MaxValue) static
Definition at line 76 of file Colorist.cs.
transparentBlack
readonly Color Empyrean.Utils.Colorist.transparentBlack = new Color(0f, 0f, 0f, 0f) static
Definition at line 60 of file Colorist.cs.
transparentWhite
readonly Color Empyrean.Utils.Colorist.transparentWhite = new Color(1f, 1f, 1f, 0f) static
Definition at line 62 of file Colorist.cs.
white
readonly Color Empyrean.Utils.Colorist.white = new Color32(byte.MaxValue, byte.MaxValue, byte.MaxValue, byte.MaxValue) static
Definition at line 64 of file Colorist.cs.
white32
readonly Color Empyrean.Utils.Colorist.white32 = new Color32(byte.MaxValue, byte.MaxValue, byte.MaxValue, byte.MaxValue) static
Definition at line 12 of file Colorist.cs.
yellow
readonly Color Empyrean.Utils.Colorist.yellow = new Color32(byte.MaxValue, byte.MaxValue, 0, byte.MaxValue) static
Definition at line 78 of file Colorist.cs.
yellow25
readonly Color Empyrean.Utils.Colorist.yellow25 = new Color(1f, 1f, 0.75f) static
Definition at line 54 of file Colorist.cs.
yellow50
readonly Color Empyrean.Utils.Colorist.yellow50 = new Color(1f, 1f, 0.5f) static
Definition at line 56 of file Colorist.cs.
yellow75
readonly Color Empyrean.Utils.Colorist.yellow75 = new Color(1f, 1f, 0.25f) static
Definition at line 58 of file Colorist.cs.
The documentation for this class was generated from the following file:
Elin/Plugins.UI/Empyrean/Utils/Colorist.cs