Elin Decompiled Documentation: LayerMiniGame Class Reference
LayerMiniGame Class Reference
Public Member Functions
override void OnAfterInit ()
override void OnUpdateInput ()
override bool OnBack ()
void Run ()
override void OnKill ()
Public Member Functions inherited from ELayer
override void OnBeforeAddLayer ()
void InitInspector ()
sealed override void Init ()
override void OnAfterAddLayer ()
void TryShowHelp ()
void AddLayerToUI (string id)
void TryShowHint (string _langHint=null)
void TalkHomeMemeber (string id)
void TalkMaid (string id)
override void OnRightClick ()
Public Member Functions inherited from Layer
virtual string GetTextHeader (Window window)
virtual bool HeaderIsListOf (int id)
virtual void Init ()
virtual void OnInit ()
virtual void OnAfterInit ()
virtual void ApplySkin ()
void ShowScreenLock (string id)
void UpdateInput ()
virtual void OnUpdateInput ()
virtual void OnRightClick ()
virtual bool OnBack ()
virtual void OnChangeLayer ()
virtual void OnCreate ()
void _AddLayer (string id)
Layer AddLayer (string id)
T AddLayer< T > ()
T AddLayer< T > (string id)
T AddLayerDontCloseOthers< T > ()
Layer AddLayerDontCloseOthers (Layer l)
T GetOrAddLayer< T > ()
virtual void OnBeforeAddLayer ()
virtual void OnAfterAddLayer ()
Layer AddLayer (Layer l)
void ToggleLayer (string id)
T ToggleLayer< T > (string id=null)
void WaitAndClose ()
void OnClickClose ()
virtual void Close ()
void CloseLayers ()
void RemoveLayers (bool removeImportant=false)
bool RemoveLayer< T > ()
void RemoveLayer (Layer l)
virtual void OnKill ()
Layer SetOnKill (Action action)
void DisableClose ()
void Delay (float duration=0.05f)
Layer SetDelay (float d)
Layer GetLayer (string id)
T GetLayer< T > (bool fromTop=false)
Layer GetTopLayer ()
void SwitchContent (int idWindow, int i)
virtual void OnSwitchContent (Window window)
Layer SetTitles (string langList, string idHeaderRow=null)
bool IsBlockWidgetClick ()
bool IsHideHud ()
bool IsAllowGeneralInput ()
bool IsUseBlur ()
bool IsPointerOnLayer ()
void ApplySkin ()
Public Attributes
MiniGame mini
MiniGame.Type type
Public Attributes inherited from Layer
Option option
UnityEvent onKill
Anime animeIn
Anime animeOut
bool closeOthers
bool defaultActionMode = true
Button screenLock
Layer parent
string idLayer
List< Layer > layers = new List<Layer>()
Vector2 lastParentPos
List< Window > windows = new List<Window>()
string langHint
Static Public Attributes
static LayerMiniGame Instance
Static Public Attributes inherited from Layer
static int skipInput
static bool closeOnRightClick
static bool rightClicked
static bool cancelKeyDown
static bool ignoreSounds
static Transform blurStopInstance
static string[] searchPath = new string[3] { "Layer", "Layer/Dialog", "Layer/LayerHome" }
Additional Inherited Members
Static Public Member Functions inherited from ELayer
static int rnd (int a)
Static Public Member Functions inherited from Layer
static T Create< T > ()
static T Create< T > (string path)
static Layer Create (string path)
Protected Member Functions inherited from ELayer
sealed override void _Close ()
sealed override void Kill ()
Protected Member Functions inherited from Layer
virtual void Awake ()
virtual void _Close ()
virtual void Kill ()
Protected Attributes inherited from Layer
RectTransform _rect
bool isDestroyed
Properties inherited from ELayer
static Core core [get]
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static FactionBranch Branch [get]
static Faction Home [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static CoreConfig config [get]
static GameSetting setting [get]
static ColorProfile Colors [get]
static SourceManager sources [get]
static World world [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
bool IsFloat [get]
virtual string IdHelp [get]
Properties inherited from Layer
Layer TopLayer [get]
string uid [get]
virtual RectTransform rectLayers [get]
virtual bool blockWidgetClick [get]
Detailed Description
Definition at line 3 of file LayerMiniGame.cs.
Member Function Documentation
OnAfterInit()
override void LayerMiniGame.OnAfterInit () inline virtual
Reimplemented from Layer.
Definition at line 11 of file LayerMiniGame.cs.
    {
        Instance = this;
        ELayer.pc.SetNoGoal();
        EInput.Consume(consumeAxis: true);
        ELayer.ui.layerFloat.SetActive(enable: false);
        if ((bool)WidgetCurrentTool.Instance)
        {
            WidgetCurrentTool.Instance.SetActive(enable: false);
        }
        if ((bool)WidgetEquip.Instance)
        {
            WidgetEquip.Instance.SetActive(enable: false);
        }
        if ((bool)WidgetSideScreen.Instance)
        {
            Canvas canvas = WidgetSideScreen.Instance.gameObject.AddComponent<Canvas>();
            canvas.overrideSorting = true;
            canvas.sortingOrder = -1;
        }
    }
References EInput.Consume(), Instance, WidgetCurrentTool.Instance, WidgetEquip.Instance, WidgetSideScreen.Instance, ELayer.pc, Chara.SetNoGoal(), and ELayer.ui.
OnBack()
override bool LayerMiniGame.OnBack () inline virtual
Reimplemented from Layer.
Definition at line 51 of file LayerMiniGame.cs.
    {
        if (mini != null && !mini.CanExit())
        {
            SE.BeepSmall();
            return false;
        }
        return base.OnBack();
    }
References MiniGame.CanExit(), and mini.
OnKill()
override void LayerMiniGame.OnKill () inline virtual
Reimplemented from Layer.
Definition at line 71 of file LayerMiniGame.cs.
    {
        if (mini != null)
        {
            mini.Deactivate();
        }
        ELayer.ui.layerFloat.SetActive(enable: true);
        if ((bool)WidgetCurrentTool.Instance)
        {
            WidgetCurrentTool.Instance.SetActive(enable: true);
        }
        if ((bool)WidgetEquip.Instance)
        {
            WidgetEquip.Instance.SetActive(enable: true);
        }
        if ((bool)WidgetSideScreen.Instance)
        {
            Object.Destroy(WidgetSideScreen.Instance.gameObject.GetComponent<Canvas>());
        }
    }
References MiniGame.Deactivate(), WidgetCurrentTool.Instance, WidgetEquip.Instance, WidgetSideScreen.Instance, mini, and ELayer.ui.
OnUpdateInput()
override void LayerMiniGame.OnUpdateInput () inline virtual
Reimplemented from Layer.
Definition at line 33 of file LayerMiniGame.cs.
    {
        if (mini == null && EInput.leftMouse.clicked)
        {
            SE.Click();
            ELayer.pc.stamina.Mod(-10);
            ELayer.player.EndTurn();
            Debug.Log(ELayer.ui.IsPauseGame);
            Debug.Log(ELayer.scene.actionMode.ShouldPauseGame + "/" + ELayer.scene.actionMode);
            Debug.Log(ELayer.scene.actionMode.gameSpeed);
            Debug.Log(ELayer.pc.turn);
            if (ELayer.pc.isDead || ELayer.pc.IsDisabled)
            {
                Close();
            }
        }
    }
References Scene.actionMode, ButtonState.clicked, Layer.Close(), Debug, Player.EndTurn(), ActionMode.gameSpeed, Chara.isDead, Chara.IsDisabled, EInput.leftMouse, mini, Stats.Mod(), ELayer.pc, ELayer.player, ELayer.scene, ActionMode.ShouldPauseGame, Chara.stamina, Card.turn, and ELayer.ui.
Run()
void LayerMiniGame.Run () inline
Definition at line 61 of file LayerMiniGame.cs.
    {
        if (mini != null)
        {
            mini.balance.lastCoin = ELayer.pc.GetCurrency("casino_coin");
            mini.balance.changeCoin = 0;
            mini.OnActivate();
        }
    }
References Card.GetCurrency(), mini, MiniGame.OnActivate(), and ELayer.pc.
Referenced by MiniGame.Activate().
Member Data Documentation
Instance
LayerMiniGame LayerMiniGame.Instance static
Definition at line 5 of file LayerMiniGame.cs.
Referenced by OnAfterInit(), and WidgetSideScreen.SlideMiniGame().
mini
MiniGame LayerMiniGame.mini
Definition at line 7 of file LayerMiniGame.cs.
Referenced by OnBack(), OnKill(), OnUpdateInput(), Run(), and WidgetSideScreen.SlideMiniGame().
type
MiniGame.Type LayerMiniGame.type
Definition at line 9 of file LayerMiniGame.cs.
Referenced by MiniGame.OnPlay().
The documentation for this class was generated from the following file:
Elin/LayerMiniGame.cs