Elin Decompiled Documentation: BaseWidgetNotice Class Reference
BaseWidgetNotice Class Reference
Public Member Functions
sealed override void OnActivate ()
virtual void _OnActivate ()
void _RefreshAll ()
virtual void OnRefresh ()
ItemNotice Add (BaseNotification n, Transform parent=null)
void Remove (BaseNotification n)
override void OnFlip ()
override void OnSetContextMenu (UIContextMenu m)
void RefreshLayout ()
override void OnApplySkin ()
Public Member Functions inherited from Widget
void Test ()
bool IsInRightMode ()
void Activate ()
void RefreshOrder ()
virtual void OnActivate ()
virtual object CreateExtra ()
void Deactivate ()
virtual void OnDeactivate ()
void Close ()
void Reactivate ()
virtual void OnManagerActivate ()
virtual void OnManagerDeactivate ()
void SetAnchor (RectPosition p)
void SetPivot (RectPosition p)
virtual void OnChangePivot ()
void UpdateConfig ()
virtual void OnUpdateConfig ()
void ClampToScreen ()
virtual void OnChangeResolution ()
void OnChangePosition ()
virtual void OnChangeActionMode ()
virtual void OnFlip ()
bool IsAlignTop ()
Layer AddLayer (Layer l, Transform trans)
void RefreshTipPivotPosition ()
SkinSet GetSkin ()
SkinConfig GetSkinConfig ()
void SetSkin (int id, int v=0)
void TestSkin ()
virtual void ApplySkin ()
virtual void OnApplySkin ()
void InstantiateDeco (SkinDeco deco)
void AddDeco (SkinDeco deco)
void RemoveDeco (SkinDeco deco)
virtual bool CanShowContextMenu ()
void ShowContextMenu ()
void SetBaseContextMenu (UIContextMenu m)
virtual void OnSetContextMenu (UIContextMenu m)
void SetGridContextMenu (UIContextMenu m)
void SoundActivate ()
void OnChangeResolution ()
SkinSet GetSkin ()
SkinConfig GetSkinConfig ()
Public Attributes
Sprite[] sprites
List< BaseNotification > list = new List<BaseNotification>()
VerticalLayoutGroup layout
VerticalLayoutGroup layout2
ItemNotice mold
Public Attributes inherited from Widget
Image imageBG
SoundData soundActivate
UIDragPanel dragPanel
RectTransform tipPivotLeft
RectTransform tipPivotRight
Private Member Functions
void OnEnable ()
void OnDisable ()
Private Attributes
bool activating = true
Additional Inherited Members
Public Types inherited from Widget
enum WidgetType { Default , ZoomMenu }
enum State { Active , Inactive }
Static Public Member Functions inherited from EMono
static int rnd (int a)
Static Public Attributes inherited from EMono
static Core core
Protected Member Functions inherited from Widget
void ClampToScreenEnsured (Component c, Vector2 anchoredPos)
void ClampToScreen (RectTransform rect, float margin=10f)
Protected Attributes inherited from Widget
bool flip
Properties inherited from Widget
string ID [get]
Config config [get]
SkinRoot skinRoot [get]
bool IsSealed [get]
virtual bool ShowStyleMenu [get]
virtual bool AlwaysTop [get]
virtual bool IsStaticPosition [get]
virtual bool AlwaysBottom [get]
virtual Type SetSiblingAfter [get]
virtual bool ShowInBuildMode [get]
virtual bool RightClickToClose [get]
virtual bool AllowRightClickToClose [get]
Properties inherited from EMono
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SoundManager Sound [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static CoreDebug debug [get]
Detailed Description
Definition at line 5 of file BaseWidgetNotice.cs.
Member Function Documentation
_OnActivate()
virtual void BaseWidgetNotice._OnActivate () inline virtual
Reimplemented in WidgetNotice, and WidgetStats.
Definition at line 36 of file BaseWidgetNotice.cs.
    {
    }
Referenced by OnActivate().
_RefreshAll()
void BaseWidgetNotice._RefreshAll () inline
Definition at line 50 of file BaseWidgetNotice.cs.
    {
        OnRefresh();
        bool rebuild = false;
        foreach (BaseNotification i in list)
        {
            i.Refresh();
            i.item.SetActive(i.Visible, delegate(bool enabled)
            {
                if (enabled)
                {
                    i.item.button.RebuildLayout(recursive: true);
                }
                rebuild = true;
            });
        }
        if (rebuild)
        {
            layout.RebuildLayout();
            if ((bool)layout2)
            {
                layout2.RebuildLayout(recursive: true);
            }
        }
    }
References ItemNotice.button, BaseNotification.item, layout, layout2, list, OnRefresh(), BaseNotification.Refresh(), and BaseNotification.Visible.
Referenced by OnActivate(), WidgetNotice.RefreshAll(), and WidgetStats.RefreshAll().
Add()
ItemNotice BaseWidgetNotice.Add (BaseNotification n, Transform parent = null) inline
Definition at line 80 of file BaseWidgetNotice.cs.
    {
        list.Add(n);
        LayoutGroup layoutGroup = n.GetLayoutGroup() ?? layout;
        ItemNotice itemNotice = Util.Instantiate(n.GetMold() ?? mold, parent ?? layoutGroup.transform);
        itemNotice.button.onClick.AddListener(delegate
        {
            if (EMono.scene.actionMode == ActionMode.NoMap)
            {
                BaseCore.Instance.WaitForEndOfFrame(n.OnClick);
            }
            else
            {
                n.OnClick();
            }
        });
        Sprite sprite = n.Sprite;
        if (n.idSprite != -1)
        {
            sprite = sprites[n.idSprite];
        }
        if ((bool)sprite)
        {
            itemNotice.button.icon.sprite = sprite;
        }
        itemNotice.button.image.raycastTarget = n.Interactable;
        itemNotice.button.tooltip.enable = n.onShowTooltip != null;
        itemNotice.button.tooltip.onShowTooltip = n.onShowTooltip;
        n.item = itemNotice;
        n.Refresh();
        n.OnInstantiate();
        if (!activating)
        {
            layoutGroup.RebuildLayout(recursive: true);
        }
        return itemNotice;
    }
References Scene.actionMode, activating, ItemNotice.button, BaseNotification.GetLayoutGroup(), BaseNotification.GetMold(), BaseNotification.idSprite, BaseNotification.Interactable, layout, list, mold, ActionMode.NoMap, BaseNotification.OnInstantiate(), BaseNotification.onShowTooltip, BaseNotification.Refresh(), EMono.scene, BaseNotification.Sprite, sprites, and Util.
Referenced by WidgetNotice._OnActivate(), WidgetStats._OnActivate(), and WidgetStats.OnRefresh().
OnActivate()
sealed override void BaseWidgetNotice.OnActivate () inline virtual
Reimplemented from Widget.
Definition at line 19 of file BaseWidgetNotice.cs.
    {
        if (!mold)
        {
            mold = layout.CreateMold<ItemNotice>();
        }
        _OnActivate();
        RefreshLayout();
        layout.RebuildLayout(recursive: true);
        if ((bool)layout2)
        {
            layout2.RebuildLayout(recursive: true);
        }
        activating = false;
        _RefreshAll();
    }
References _OnActivate(), _RefreshAll(), activating, layout, layout2, mold, and RefreshLayout().
OnApplySkin()
override void BaseWidgetNotice.OnApplySkin () inline virtual
Reimplemented from Widget.
Definition at line 155 of file BaseWidgetNotice.cs.
    {
        RefreshLayout();
    }
References RefreshLayout().
OnDisable()
void BaseWidgetNotice.OnDisable () inline private
Definition at line 45 of file BaseWidgetNotice.cs.
    {
        CancelInvoke();
    }
OnEnable()
void BaseWidgetNotice.OnEnable () inline private
Definition at line 40 of file BaseWidgetNotice.cs.
    {
        InvokeRepeating("_RefreshAll", 0.1f, 0.2f);
    }
OnFlip()
override void BaseWidgetNotice.OnFlip () inline virtual
Reimplemented from Widget.
Definition at line 127 of file BaseWidgetNotice.cs.
    {
        layout.childAlignment = (flip ? TextAnchor.MiddleRight : TextAnchor.MiddleLeft);
        this.Rect().pivot = new Vector2(flip ? 1 : 0, this.Rect().pivot.y);
    }
References Widget.flip.
OnRefresh()
virtual void BaseWidgetNotice.OnRefresh () inline virtual
Reimplemented in WidgetNotice, and WidgetStats.
Definition at line 76 of file BaseWidgetNotice.cs.
    {
    }
Referenced by _RefreshAll().
OnSetContextMenu()
override void BaseWidgetNotice.OnSetContextMenu (UIContextMenu m) inline virtual
Reimplemented from Widget.
Reimplemented in WidgetNotice.
Definition at line 133 of file BaseWidgetNotice.cs.
    {
        m.AddChild("style").AddSlider("toggleButtonBG", (float a) => a.ToString() ?? "", base.config.skin.button, delegate(float a)
        {
            base.config.skin.button = (int)a;
            ApplySkin();
        }, 0f, base.config.skin.Skin.buttons.Count - 1, isInt: true);
        SetBaseContextMenu(m);
    }
References UIContextMenu.AddChild(), UIContextMenu.AddSlider(), Widget.ApplySkin(), and Widget.SetBaseContextMenu().
RefreshLayout()
void BaseWidgetNotice.RefreshLayout () inline
Definition at line 143 of file BaseWidgetNotice.cs.
    {
        SkinAsset_Button button = GetComponent<SkinRoot>().Config.Button;
        int y = button.size.y;
        foreach (BaseNotification item in list)
        {
            RectTransform rectTransform = item.item.Rect();
            rectTransform.sizeDelta = new Vector2(rectTransform.sizeDelta.x, y);
        }
        layout.spacing = button.spacing.y;
    }
References item, list, and SkinAsset_Button.size.
Referenced by OnActivate(), and OnApplySkin().
Remove()
void BaseWidgetNotice.Remove (BaseNotification n) inline
Definition at line 118 of file BaseWidgetNotice.cs.
    {
        list.Remove(n);
        if ((bool)n.item)
        {
            Object.DestroyImmediate(n.item.gameObject);
        }
    }
References BaseNotification.item, and list.
Member Data Documentation
activating
bool BaseWidgetNotice.activating = true private
Definition at line 17 of file BaseWidgetNotice.cs.
Referenced by Add(), and OnActivate().
layout
VerticalLayoutGroup BaseWidgetNotice.layout
Definition at line 11 of file BaseWidgetNotice.cs.
Referenced by _RefreshAll(), Add(), OnActivate(), and NotificationCondition.OnClick().
layout2
VerticalLayoutGroup BaseWidgetNotice.layout2
Definition at line 13 of file BaseWidgetNotice.cs.
Referenced by _RefreshAll(), NotificationBuff.GetLayoutGroup(), and OnActivate().
list
List<BaseNotification> BaseWidgetNotice.list = new List<BaseNotification>()
Definition at line 9 of file BaseWidgetNotice.cs.
Referenced by _RefreshAll(), Add(), RefreshLayout(), and Remove().
mold
ItemNotice BaseWidgetNotice.mold
Definition at line 15 of file BaseWidgetNotice.cs.
Referenced by Add(), and OnActivate().
sprites
Sprite [] BaseWidgetNotice.sprites
Definition at line 7 of file BaseWidgetNotice.cs.
Referenced by Add().
The documentation for this class was generated from the following file:
Elin/BaseWidgetNotice.cs