Elin Decompiled Documentation: LayerWidget Class Reference
LayerWidget Class Reference
Public Member Functions
override void OnInit ()
override void OnUpdateInput ()
void Refresh ()
override void OnKill ()
Public Member Functions inherited from ELayer
override void OnBeforeAddLayer ()
void InitInspector ()
sealed override void Init ()
override void OnAfterAddLayer ()
void TryShowHelp ()
void AddLayerToUI (string id)
void TryShowHint (string _langHint=null)
void TalkHomeMemeber (string id)
void TalkMaid (string id)
override void OnRightClick ()
Public Member Functions inherited from Layer
virtual string GetTextHeader (Window window)
virtual bool HeaderIsListOf (int id)
virtual void Init ()
virtual void OnInit ()
virtual void OnAfterInit ()
virtual void ApplySkin ()
void ShowScreenLock (string id)
void UpdateInput ()
virtual void OnUpdateInput ()
virtual void OnRightClick ()
virtual bool OnBack ()
virtual void OnChangeLayer ()
virtual void OnCreate ()
void _AddLayer (string id)
Layer AddLayer (string id)
T AddLayer< T > ()
T AddLayer< T > (string id)
T AddLayerDontCloseOthers< T > ()
Layer AddLayerDontCloseOthers (Layer l)
T GetOrAddLayer< T > ()
virtual void OnBeforeAddLayer ()
virtual void OnAfterAddLayer ()
Layer AddLayer (Layer l)
void ToggleLayer (string id)
T ToggleLayer< T > (string id=null)
void WaitAndClose ()
void OnClickClose ()
virtual void Close ()
void CloseLayers ()
void RemoveLayers (bool removeImportant=false)
bool RemoveLayer< T > ()
void RemoveLayer (Layer l)
virtual void OnKill ()
Layer SetOnKill (Action action)
void DisableClose ()
void Delay (float duration=0.05f)
Layer SetDelay (float d)
Layer GetLayer (string id)
T GetLayer< T > (bool fromTop=false)
Layer GetTopLayer ()
void SwitchContent (int idWindow, int i)
virtual void OnSwitchContent (Window window)
Layer SetTitles (string langList, string idHeaderRow=null)
bool IsBlockWidgetClick ()
bool IsHideHud ()
bool IsAllowGeneralInput ()
bool IsUseBlur ()
bool IsPointerOnLayer ()
void ApplySkin ()
Public Attributes
UIList list
UIList list2
Public Attributes inherited from Layer
Option option
UnityEvent onKill
Anime animeIn
Anime animeOut
bool closeOthers
bool defaultActionMode = true
Button screenLock
Layer parent
string idLayer
List< Layer > layers = new List<Layer>()
Vector2 lastParentPos
List< Window > windows = new List<Window>()
string langHint
Static Public Attributes
static LayerWidget Instance
Static Public Attributes inherited from Layer
static int skipInput
static bool closeOnRightClick
static bool rightClicked
static bool cancelKeyDown
static bool ignoreSounds
static Transform blurStopInstance
static string[] searchPath = new string[3] { "Layer", "Layer/Dialog", "Layer/LayerHome" }
Additional Inherited Members
Static Public Member Functions inherited from ELayer
static int rnd (int a)
Static Public Member Functions inherited from Layer
static T Create< T > ()
static T Create< T > (string path)
static Layer Create (string path)
Protected Member Functions inherited from ELayer
sealed override void _Close ()
sealed override void Kill ()
Protected Member Functions inherited from Layer
virtual void Awake ()
virtual void _Close ()
virtual void Kill ()
Protected Attributes inherited from Layer
RectTransform _rect
bool isDestroyed
Properties inherited from ELayer
static Core core [get]
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static FactionBranch Branch [get]
static Faction Home [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static CoreConfig config [get]
static GameSetting setting [get]
static ColorProfile Colors [get]
static SourceManager sources [get]
static World world [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
bool IsFloat [get]
virtual string IdHelp [get]
Properties inherited from Layer
Layer TopLayer [get]
string uid [get]
virtual RectTransform rectLayers [get]
virtual bool blockWidgetClick [get]
Detailed Description
Definition at line 3 of file LayerWidget.cs.
Member Function Documentation
OnInit()
override void LayerWidget.OnInit () inline virtual
Reimplemented from Layer.
Definition at line 11 of file LayerWidget.cs.
    {
        ELayer.ui.HideFloats();
        WidgetManager widgets = ELayer.ui.widgets;
        Instance = this;
        UIList uIList = list;
        UIList uIList2 = list2;
        UIList.Callback<Widget.Config, ItemWidget> obj = new UIList.Callback<Widget.Config, ItemWidget>
        {
            onClick = delegate
            {
            },
            onInstantiate = delegate(Widget.Config a, ItemWidget b)
            {
                b.buttonActivate.mainText.text = Lang.Get("Widget" + a.id);
                b.buttonActivate.subText.SetActive(a.IsSystem);
                b.buttonActivate.onClick.AddListener(delegate
                {
                    if (a.IsSealed)
                    {
                        SE.Beep();
                    }
                    else
                    {
                        if (a.id == "QuestTracker")
{
                            if (ELayer.ui.widgets.GetWidget("QuestTracker") != null)
{
                                ELayer.player.questTracker = false;
                            }
                            else
{
                                ELayer.player.questTracker = true;
                            }
                            WidgetHotbar.RefreshButtons();
                        }
                        widgets.Toggle(a)?.SoundActivate();
                        Refresh();
                    }
                });
                b.buttonLock.onClick.AddListener(delegate
                {
                    widgets.ToggleLock(a);
                    Refresh();
                });
                b.config = a;
            },
            onRefresh = Refresh
        };
        UIList.ICallback callbacks = obj;
        uIList2.callbacks = obj;
        uIList.callbacks = callbacks;
        foreach (Widget.Meta widgetMeta in ELayer.setting.ui.widgetMetas)
        {
            Widget.Config config = widgets.configs[widgetMeta.id];
            if (config.IsInRightMode() && !widgetMeta.debugOnly)
            {
                if (config.id.Contains("Hotbar"))
                {
                    list2.Add(config);
                }
                else
                {
                    list.Add(config);
                }
            }
        }
        list.Refresh();
        list2.Refresh();
        foreach (Widget item in widgets.list)
        {
            item.OnManagerActivate();
        }
        windows[0].AddBottomSpace();
        windows[0].AddBottomButton("resetWidget", delegate
        {
            Dialog.YesNo("dialogResetWidget", delegate
            {
                Close();
                ELayer.ui.widgets.Load(ELayer.player.useSubWidgetTheme);
                ELayer.ui.widgets.Reset(toggleTheme: false);
                ELayer.ui.AddLayer<LayerWidget>();
            });
        });
        windows[0].AddBottomButton("loadTheme", delegate
        {
            widgets.DialogLoad(delegate
            {
                Close();
                ELayer.ui.AddLayer<LayerWidget>();
            });
        });
        windows[0].AddBottomButton("saveTheme", delegate
        {
            widgets.DialogSave(delegate
            {
                Dialog.Ok("dialogSaveTheme");
            });
        });
    }
References ItemWidget.buttonActivate, ItemWidget.buttonLock, Lang.Get(), Instance, list, list2, Refresh(), Widget.SoundActivate(), UIButton.subText, WidgetManager.Toggle(), WidgetManager.ToggleLock(), and ELayer.ui.
OnKill()
override void LayerWidget.OnKill () inline virtual
Reimplemented from Layer.
Definition at line 135 of file LayerWidget.cs.
    {
        foreach (Widget item in ELayer.ui.widgets.list)
        {
            item.OnManagerDeactivate();
        }
        ELayer.ui.ShowFloats();
    }
References item, and ELayer.ui.
OnUpdateInput()
override void LayerWidget.OnUpdateInput () inline virtual
Reimplemented from Layer.
Definition at line 112 of file LayerWidget.cs.
    {
        if (EInput.leftMouse.clicked && !EInput.leftMouse.dragging)
        {
            Widget componentOf = InputModuleEX.GetComponentOf<Widget>();
            if ((bool)componentOf)
            {
                componentOf.ShowContextMenu();
            }
        }
    }
References ButtonState.clicked, ButtonState.dragging, EInput.leftMouse, and Widget.ShowContextMenu().
Refresh()
void LayerWidget.Refresh () inline
Definition at line 124 of file LayerWidget.cs.
    {
        foreach (UIList.ButtonPair item in list.buttons.Concat(list2.buttons))
        {
            ItemWidget itemWidget = item.component as ItemWidget;
            itemWidget.imageLock.SetActive(itemWidget.config.locked);
            itemWidget.imageActive.SetActive(itemWidget.config.state == Widget.State.Active);
            itemWidget.buttonLock.mainText.text = Lang.Get(itemWidget.config.locked ? "unlockWidget" : "lockWidget");
        }
    }
References UIList.buttons, ItemWidget.config, Lang.Get(), ItemWidget.imageActive, ItemWidget.imageLock, and item.
Referenced by WidgetManager.DeactivateWidget(), and OnInit().
Member Data Documentation
Instance
LayerWidget LayerWidget.Instance static
Definition at line 5 of file LayerWidget.cs.
Referenced by WidgetManager.ActivateWidget(), WidgetManager.DeactivateWidget(), and OnInit().
list
UIList LayerWidget.list
Definition at line 7 of file LayerWidget.cs.
Referenced by OnInit().
list2
UIList LayerWidget.list2
Definition at line 9 of file LayerWidget.cs.
Referenced by OnInit().
The documentation for this class was generated from the following file:
Elin/LayerWidget.cs