Elin Decompiled Documentation: ColorConverter Class Reference
ColorConverter Class Reference
Static Public Member Functions
static Lab RgbToLab (Color rgb)
static Lab XyzToLab (Xyz xyz)
static Xyz RgbToXyz (Color rgb)
Static Private Member Functions
static float PivotXyz (float n)
static float CubicRoot (float n)
static float PivotRgb (float n)
Static Private Attributes
const float Epsilon = 0.008856f
const float Kappa = 903.3f
static readonly Xyz WhiteReference
Detailed Description
Definition at line 4 of file ColorConverter.cs.
Member Function Documentation
CubicRoot()
static float ColorConverter.CubicRoot (float n) inline static private
Definition at line 45 of file ColorConverter.cs.
    {
        return Mathf.Pow(n, 1f / 3f);
    }
Referenced by PivotXyz().
PivotRgb()
static float ColorConverter.PivotRgb (float n) inline static private
Definition at line 63 of file ColorConverter.cs.
    {
        return ((n > 0.04045f) ? Mathf.Pow((n + 0.055f) / 1.055f, 2.4f) : (n / 12.92f)) * 100f;
    }
Referenced by RgbToXyz().
PivotXyz()
static float ColorConverter.PivotXyz (float n) inline static private
Definition at line 36 of file ColorConverter.cs.
    {
        if (!(n > 0.008856f))
        {
            return (903.3f * n + 16f) / 116f;
        }
        return CubicRoot(n);
    }
References CubicRoot().
Referenced by XyzToLab().
RgbToLab()
static Lab ColorConverter.RgbToLab (Color rgb) inline static
Definition at line 17 of file ColorConverter.cs.
    {
        return XyzToLab(RgbToXyz(rgb));
    }
References RgbToXyz(), and XyzToLab().
Referenced by ColorComparer.Compare().
RgbToXyz()
static Xyz ColorConverter.RgbToXyz (Color rgb) inline static
Definition at line 50 of file ColorConverter.cs.
    {
        float num = PivotRgb(rgb.r);
        float num2 = PivotRgb(rgb.g);
        float num3 = PivotRgb(rgb.b);
        return new Xyz
        {
            X = num * 0.4124f + num2 * 0.3576f + num3 * 0.1805f,
            Y = num * 0.2126f + num2 * 0.7152f + num3 * 0.0722f,
            Z = num * 0.0193f + num2 * 0.1192f + num3 * 0.9505f
        };
    }
References PivotRgb().
Referenced by RgbToLab().
XyzToLab()
static Lab ColorConverter.XyzToLab (Xyz xyz) inline static
Definition at line 22 of file ColorConverter.cs.
    {
        Xyz whiteReference = WhiteReference;
        float num = PivotXyz(xyz.X / whiteReference.X);
        float num2 = PivotXyz(xyz.Y / whiteReference.Y);
        float num3 = PivotXyz(xyz.Z / whiteReference.Z);
        return new Lab
        {
            L = Math.Max(0f, 116f * num2 - 16f),
            A = 500f * (num - num2),
            B = 200f * (num2 - num3)
        };
    }
References PivotXyz(), WhiteReference, Xyz.X, Xyz.Y, and Xyz.Z.
Referenced by RgbToLab().
Member Data Documentation
Epsilon
const float ColorConverter.Epsilon = 0.008856f static private
Definition at line 6 of file ColorConverter.cs.
Kappa
const float ColorConverter.Kappa = 903.3f static private
Definition at line 8 of file ColorConverter.cs.
WhiteReference
readonly Xyz ColorConverter.WhiteReference static private
Initial value:
= new Xyz
    {
        X = 95.047f,
        Y = 100f,
        Z = 108.883f
    }
Definition at line 10 of file ColorConverter.cs.
Referenced by XyzToLab().
The documentation for this class was generated from the following file:
Elin/Plugins.UI/ColorConverter.cs