Elin Decompiled Documentation: SourceCheck Class Reference
SourceCheck Class Reference
Classes
class Row
Public Member Functions
override Row CreateRow ()
override Row CreateRowByMapping (IReadOnlyDictionary< string, int > mapping)
override void SetRow (Row r)
override IReadOnlyDictionary< string, int > GetRowMapping ()
override IReadOnlyDictionary< string, string > GetTypeMapping ()
Public Member Functions inherited from SourceDataString< SourceCheck.Row >
override T GetRow (string id)
Static Public Attributes
static readonly IReadOnlyDictionary< string, int > RowMapping
static readonly IReadOnlyDictionary< string, string > TypeMapping
Detailed Description
Definition at line 4 of file SourceCheck.cs.
Member Function Documentation
CreateRow()
override Row SourceCheck.CreateRow () inline
Definition at line 62 of file SourceCheck.cs.
    {
        return new Row
        {
            id = SourceData.GetString(0),
            element = Core.GetElement(SourceData.GetStr(1)),
            targetElement = Core.GetElement(SourceData.GetStr(2)),
            subFactor = SourceData.GetFloat(3),
            targetSubFactor = SourceData.GetFloat(4),
            baseDC = SourceData.GetInt(5),
            critRange = SourceData.GetInt(6),
            fumbleRange = SourceData.GetInt(7),
            dice = SourceData.GetInt(8),
            lvMod = SourceData.GetFloat(9)
        };
    }
References Core.GetElement(), SourceData< T, T2 >.GetFloat(), SourceData< T, T2 >.GetInt(), SourceData< T, T2 >.GetStr(), and SourceData< T, T2 >.GetString().
CreateRowByMapping()
override Row SourceCheck.CreateRowByMapping (IReadOnlyDictionary< string, int > mapping) inline
Definition at line 79 of file SourceCheck.cs.
    {
        return new Row
        {
            id = SourceData.GetString(mapping["id"]),
            element = Core.GetElement(SourceData.GetStr(mapping["element"])),
            targetElement = Core.GetElement(SourceData.GetStr(mapping["targetElement"])),
            subFactor = SourceData.GetFloat(mapping["subFactor"]),
            targetSubFactor = SourceData.GetFloat(mapping["targetSubFactor"]),
            baseDC = SourceData.GetInt(mapping["baseDC"]),
            critRange = SourceData.GetInt(mapping["critRange"]),
            fumbleRange = SourceData.GetInt(mapping["fumbleRange"]),
            dice = SourceData.GetInt(mapping["dice"]),
            lvMod = SourceData.GetFloat(mapping["lvMod"])
        };
    }
References Core.GetElement(), SourceData< T, T2 >.GetFloat(), SourceData< T, T2 >.GetInt(), SourceData< T, T2 >.GetStr(), and SourceData< T, T2 >.GetString().
GetRowMapping()
override IReadOnlyDictionary< string, int > SourceCheck.GetRowMapping () inline
Definition at line 101 of file SourceCheck.cs.
    {
        return RowMapping;
    }
References RowMapping.
GetTypeMapping()
override IReadOnlyDictionary< string, string > SourceCheck.GetTypeMapping () inline
Definition at line 106 of file SourceCheck.cs.
    {
        return TypeMapping;
    }
References TypeMapping.
SetRow()
override void SourceCheck.SetRow (Row r) inline
Definition at line 96 of file SourceCheck.cs.
    {
        map[r.id] = r;
    }
References SourceCheck.Row.id.
Member Data Documentation
RowMapping
readonly IReadOnlyDictionary<string, int> SourceCheck.RowMapping static
Initial value:
= new Dictionary<string, int>
    {
        ["id"] = 0,
        ["element"] = 1,
        ["targetElement"] = 2,
        ["subFactor"] = 3,
        ["targetSubFactor"] = 4,
        ["baseDC"] = 5,
        ["critRange"] = 6,
        ["fumbleRange"] = 7,
        ["dice"] = 8,
        ["lvMod"] = 9
    }
Definition at line 34 of file SourceCheck.cs.
Referenced by GetRowMapping().
TypeMapping
readonly IReadOnlyDictionary<string, string> SourceCheck.TypeMapping static
Initial value:
= new Dictionary<string, string>
    {
        ["id"] = "string",
        ["element"] = "element_id",
        ["targetElement"] = "element_id",
        ["subFactor"] = "float",
        ["targetSubFactor"] = "float",
        ["baseDC"] = "int",
        ["critRange"] = "int",
        ["fumbleRange"] = "int",
        ["dice"] = "int",
        ["lvMod"] = "float"
    }
Definition at line 48 of file SourceCheck.cs.
Referenced by GetTypeMapping().
The documentation for this class was generated from the following file:
Elin/SourceCheck.cs