Elin Decompiled Documentation: Window Class Reference
Window Class Reference
Classes
class SaveData
class Setting
Public Types
enum Type { Default , AlignToMouse , Side }
Public Member Functions
void Init (Layer _layer=null)
void RefreshTipPivotPosition ()
void SetRect (RectData data, bool mousePos=false)
void UpdateSaveData ()
void OnKill ()
void ApplySkin ()
T SwitchContent< T > ()
void SwitchContent (UIContent content)
void SwitchContent (string name)
void SwitchContent (Setting.Tab tab)
UIContent SwitchContent (int index)
void SetTitles (string langList, string idHeaderRow=null)
void SetCaption (string text)
void AddHeader (string langLeft=null, string langRight=null)
void LoadHeader (string id="HeaderRow")
void SetPosition ()
T SetContent< T > (int tabIndex=-1, string id=null)
void SetContent (int tabIndex, UIContent content)
T GetContent< T > ()
bool NextTab (int a)
void BuildTabs (int index=-1)
Setting.Tab AddTab (string idLang, UIContent content=null, Action action=null, Sprite sprite=null, string langTooltip=null)
int GetTab (UIContent content)
int GetTab (string name)
void ClearBottomButtons ()
UIButton AddBottomButton (string idLang, UnityAction onClick, bool setFirst=false)
void AddBottomSpace (int size=20)
void EnableShadow ()
void SetInteractable (bool enable, float alpha=0.5f)
void Close ()
void InitPanel ()
void OnChangeResolution ()
void SetAnchor ()
void OnApplicationFocus (bool focus)
void BringToTop ()
void ClampToScreen ()
void OnChangeResolution ()
void ApplySkin ()
Public Attributes
bool leftSide = true
bool isFloat
Setting setting
UIContentView view
UIText textCaption
UIText textStats
Image iconCaption
Image deco1
Image deco2
UIImage imageBG
UIImage bgCaption
Button buttonClose
UIButton buttonHelp
UIButton buttonSort
UIButton buttonQuickSort
UIButton buttonExtra
UIButton buttonShared
UIButton moldTab
UIButton moldBottom
RectTransform rectCorner
RectTransform rectCaption
RectTransform rectTab
RectTransform rectBottom
RectTransform rectStats
RectTransform tipPiovotLeft
RectTransform tipPivotRight
RectTransform rectDeco
RectTransform rectHeader
UISelectableGroup groupTab
WindowController controller
SkinRootStatic skinRoot
Tween tweenAnime
CanvasGroup cgBG
CanvasGroup cgFloatMenu
UICollider bgCollider
List< CanvasGroup > listCgFloat
Layer layer
float FrameOffsetL = -15f
float FrameOffsetR = -15f
float FrameOffsetTop = -30f
float FrameThickness = 14f
float CaptionHeight = 50f
float frameOffsetY = 5f
int idTab
int windowIndex
WindowMenu menuLeft
WindowMenu menuLeftBottom
WindowMenu menuBottom
WindowMenu menuRight
CanvasGroup cg
Vector2 posBottom
Vector2 posTab
Vector2 posCaption
SaveData saveData
Window attachedWindow
Vector2 attachFix
Static Public Attributes
static Dictionary< string, SaveData > dictData = new Dictionary<string, SaveData>()
static Dictionary< string, int > dictTab = new Dictionary<string, int>()
static bool openLastTab
static bool animateWindow
Properties
string idWindow [get]
Setting.Tab CurrentTab [get]
UIContent CurrentContent [get]
bool AutoAnchor [get]
SkinRootStatic Skin [get]
Canvas Canvas [get]
EventTrigger EventTrigger [get]
RectTransform RectTransform [get]
Vector3 CorrectedLossyScale [get]
Vector3[] FrameOuterCorners [get]
Vector3[] FrameInnerCorners [get]
Vector3[] CaptionCorners [get]
bool isStatic [get]
Private Member Functions
void Awake ()
void RecalculatePositionCaches ()
void Update ()
void OnPointerEnter (PointerEventData data)
void OnPointerExit (PointerEventData data)
void OnPointerDown (PointerEventData data)
void OnPointerUp (PointerEventData data)
void ProcessCursorChanges ()
void ProcessMovement ()
void ProcessResize ()
bool CursorOverTopBorder (bool canExceed=false)
bool CursorOverBottomBorder (bool canExceed=false)
bool CursorOverLeftBorder (bool canExceed=false)
bool CursorOverRightBorder (bool canExceed=false)
bool CursorOverCaption ()
bool CursorOverWindow ()
Private Attributes
RectTransform _rect
LayoutGroup layoutWindow
bool? shadowEnabled
Shadow bgShadow
Canvas _canvas
EventTrigger _eventTrigger
RectTransform _rectTransform
Vector3 _correctedLossyScale
Vector3[] _frameOuterCorners
Vector3[] _frameInnerCorners
Vector3[] _captionCorners
bool IsProcessingCursorChanges
bool IsProcessingMovement
bool IsProcessingResize
bool IsResizingOverTop
bool IsResizingOverBottom
bool IsResizingOverLeft
bool IsResizingOverRight
Vector3 LastScreenCursorPosition
Vector3 dragStartPos
Vector3 dragOffset
bool scrolling
bool isTop
float floatAlpha
Detailed Description
Definition at line 12 of file Window.cs.
Member Enumeration Documentation
Type
enum Window.Type
Enumerator
Default
AlignToMouse
Side
Definition at line 14 of file Window.cs.
    {
        Default,
        AlignToMouse,
        Side
    }
Member Function Documentation
AddBottomButton()
UIButton Window.AddBottomButton (string idLang, UnityAction onClick, bool setFirst = false) inline
Definition at line 1486 of file Window.cs.
    {
        UIButton uIButton = (moldBottom ? Util.Instantiate(moldBottom, rectBottom) : Util.Instantiate<UIButton>("UI/Window/Base/Element/ButtonBottom", rectBottom));
        uIButton.mainText.SetLang(idLang);
        uIButton.onClick.AddListener(onClick);
        if (setFirst)
        {
            uIButton.transform.SetAsFirstSibling();
        }
        uIButton.RebuildLayout(recursive: true);
        return uIButton;
    }
References UIButton.mainText, moldBottom, rectBottom, UIText.SetLang(), and Util.
Referenced by Init().
AddBottomSpace()
void Window.AddBottomSpace (int size = 20) inline
Definition at line 1499 of file Window.cs.
    {
        RectTransform rectTransform = new GameObject().AddComponent<RectTransform>();
        rectTransform.sizeDelta = new Vector2(size, 20f);
        rectTransform.SetParent(rectBottom, worldPositionStays: false);
    }
References rectBottom, and RectTransform.
AddHeader()
void Window.AddHeader (string langLeft = null, string langRight = null) inline
Definition at line 1295 of file Window.cs.
    {
        if (!rectHeader)
        {
            LoadHeader();
        }
        UIHeader[] componentsInChildren = rectHeader.GetComponentsInChildren<UIHeader>(includeInactive: true);
        if (!langLeft.IsEmpty())
        {
            componentsInChildren[0].SetText(langLeft);
        }
        if (componentsInChildren.Length > 1)
        {
            if (langRight.IsEmpty())
            {
                componentsInChildren[1].SetActive(enable: false);
            }
            else
            {
                componentsInChildren[1].SetText(langRight);
            }
        }
    }
References LoadHeader(), rectHeader, and UIHeader.SetText().
AddTab()
Setting.Tab Window.AddTab (string idLang, UIContent content = null, Action action = null, Sprite sprite = null, string langTooltip = null) inline
Definition at line 1443 of file Window.cs.
    {
        Setting.Tab tab = new Setting.Tab
        {
            idLang = idLang,
            content = content,
            action = action,
            sprite = sprite,
            langTooltip = langTooltip
        };
        setting.tabs.Add(tab);
        return tab;
    }
References setting, and Window.Setting.tabs.
Referenced by UIMultiList.AddOwner(), and LayerCraft.RefreshCategory().
ApplySkin()
void Window.ApplySkin () inline
Implements IUISkin.
Definition at line 1129 of file Window.cs.
    {
        SkinRootStatic skin = Skin;
        if ((bool)cg && setting.transparent)
        {
            cg.alpha = skin.transparency;
        }
        if ((bool)deco1)
        {
            Image image = deco1;
            Color color2 = (deco2.color = skin.colorsEx.deco1);
            image.color = color2;
        }
        layoutWindow.padding = skin.positions.paddingWindow;
        rectBottom.anchoredPosition = posBottom + skin.positions.bottom;
        if (!setting.tabAfterCaption)
        {
            rectTab.anchoredPosition = posTab + skin.positions.tab;
        }
        Image image2 = imageBG?.frame;
        if (!shadowEnabled.HasValue)
        {
            shadowEnabled = bgShadow?.enabled ?? false;
        }
        if ((bool)image2 && skin.useFrame)
        {
            image2.GetComponent<Shadow>().enabled = shadowEnabled.GetValueOrDefault();
            if ((bool)bgShadow)
            {
                bgShadow.enabled = false;
            }
        }
        else if ((bool)bgShadow)
        {
            bgShadow.enabled = shadowEnabled.GetValueOrDefault();
        }
        Outline component = textCaption.GetComponent<Outline>();
        if ((bool)component)
        {
            component.enabled = skin.captionOutline;
        }
        if ((bool)rectDeco)
        {
            rectDeco.SetActive(skin.useDeco);
        }
        if ((bool)rectCorner && imageBG.imageType != ImageType.BG_Window_Board)
        {
            rectCorner.anchoredPosition = skin.positions.windowCorner;
        }
        if ((bool)menuLeft.layout)
        {
            menuLeft.layout.Rect().anchoredPosition = skin.positions.leftMenu;
        }
        if ((bool)bgCaption)
        {
            bgCaption.SetActive(skin.captionBG && textCaption.gameObject.activeInHierarchy);
        }
        if (skin.alwaysShadow || skin.noShadow)
        {
            EnableShadow();
        }
    }
References SkinRootStatic.alwaysShadow, bgCaption, bgShadow, SkinRootStatic.Positions.bottom, SkinRootStatic.captionBG, SkinRootStatic.captionOutline, cg, Color, SkinRootStatic.colorsEx, SkinColorProfileEx.deco1, deco1, EnableShadow(), UIImage.frame, imageBG, WindowMenu.layout, SkinRootStatic.Positions.leftMenu, menuLeft, SkinRootStatic.noShadow, Outline, SkinRootStatic.Positions.paddingWindow, posBottom, SkinRootStatic.positions, posTab, rectCorner, rectDeco, setting, shadowEnabled, Skin, SkinRootStatic.Positions.tab, Window.Setting.tabAfterCaption, textCaption, SkinRootStatic.transparency, Window.Setting.transparent, SkinRootStatic.useDeco, SkinRootStatic.useFrame, and SkinRootStatic.Positions.windowCorner.
Referenced by Init().
Awake()
void Window.Awake () inline private
Definition at line 934 of file Window.cs.
    {
        controller = base.gameObject.GetComponent<WindowController>();
        if ((bool)controller)
        {
            controller.window = this;
        }
        menuLeft = new WindowMenu("Left", this);
        menuRight = new WindowMenu(setting.rightMenuAlias.IsEmpty("Right"), this);
        menuBottom = new WindowMenu("Bottom", this);
        menuLeftBottom = new WindowMenu("LeftBottom", this);
        if (!base.gameObject.GetComponent<Canvas>())
        {
            base.gameObject.AddComponent<Canvas>();
            base.gameObject.AddComponent<GraphicRaycaster>();
        }
        cg = base.gameObject.GetComponent<CanvasGroup>();
        if (cg == null)
        {
            cg = base.gameObject.AddComponent<CanvasGroup>();
        }
        posTab = rectTab.anchoredPosition;
        posBottom = rectBottom.anchoredPosition;
        layoutWindow = GetComponent<LayoutGroup>();
        posCaption = new Vector2(layoutWindow.padding.left, layoutWindow.padding.top);
        if (setting.tabAfterCaption)
        {
            rectTab.SetSiblingIndex(rectCaption.GetSiblingIndex());
        }
        if ((bool)imageBG)
        {
            bgShadow = imageBG.GetComponent<Shadow>();
        }
        _rect = this.Rect();
    }
References _rect, bgShadow, Canvas, cg, controller, imageBG, layoutWindow, menuBottom, menuLeft, menuLeftBottom, menuRight, posBottom, posCaption, posTab, rectBottom, rectCaption, rectTab, Window.Setting.rightMenuAlias, setting, and Window.Setting.tabAfterCaption.
BringToTop()
void Window.BringToTop () inline
Definition at line 1747 of file Window.cs.
    {
        if (!layer)
        {
            return;
        }
        int num = 0;
        foreach (Window window in layer.windows)
        {
            int siblingIndex = window.transform.GetSiblingIndex();
            if (siblingIndex > num)
            {
                num = siblingIndex;
            }
        }
        base.transform.SetSiblingIndex(num);
    }
References layer, and Layer.windows.
Referenced by Update().
BuildTabs()
void Window.BuildTabs (int index = -1) inline
Definition at line 1396 of file Window.cs.
    {
        if (setting.tabs.Count > 0)
        {
            bool flag = false;
            foreach (Setting.Tab tab in setting.tabs)
            {
                if (!tab.button)
                {
                    if (!flag && (bool)tab.customTab)
                    {
                        GameObject obj = new GameObject();
                        obj.AddComponent<RectTransform>().sizeDelta = new Vector2(22f, 1f);
                        obj.transform.SetParent(rectTab);
                        flag = true;
                    }
                    UIButton uIButton = (tab.customTab ? Util.Instantiate(tab.customTab, rectTab) : (moldTab ? Util.Instantiate(moldTab, rectTab) : Util.Instantiate<UIButton>("UI/Window/Base/Element/ButtonTab", rectTab)));
                    uIButton.mainText.SetLang(tab.idLang);
                    tab.button = uIButton;
                    if (!tab.langTooltip.IsEmpty())
                    {
                        uIButton.tooltip.enable = true;
                        uIButton.tooltip.lang = tab.langTooltip;
                    }
                    if ((bool)tab.sprite)
                    {
                        uIButton.icon.sprite = tab.sprite;
                    }
                    if (tab.disable)
                    {
                        uIButton.SetActive(enable: false);
                    }
                }
                tab.button.onClick.AddListener(delegate
                {
                    SwitchContent(tab);
                });
            }
        }
        rectTab.SetActive(setting.tabs.Count > 1 || setting.alwaysShowTab);
        rectTab.RebuildLayout(recursive: true);
        if ((bool)groupTab)
        {
            groupTab.Init(index);
        }
    }
References Window.Setting.alwaysShowTab, groupTab, UISelectableGroup.Init(), UIButton.mainText, moldTab, rectTab, RectTransform, UIText.SetLang(), setting, SwitchContent(), Window.Setting.tabs, and Util.
Referenced by Init(), and LayerCraft.RefreshCategory().
ClampToScreen()
void Window.ClampToScreen () inline
Definition at line 1765 of file Window.cs.
    {
        RectTransform rectTransform = base.transform.parent.Rect();
        RectTransform rectTransform2 = base.transform.Rect();
        Transform transform = base.transform;
        Vector3 localPosition = base.transform.localPosition;
        Vector3 vector = rectTransform.rect.min - rectTransform2.rect.min;
        Vector3 vector2 = rectTransform.rect.max - rectTransform2.rect.max;
        float num = ((setting.clampMargin.x == -1f) ? 20f : setting.clampMargin.x);
        float num2 = ((setting.clampMargin.y == -1f) ? 40f : setting.clampMargin.y);
        localPosition.x = Mathf.Clamp(transform.localPosition.x, vector.x + num - 50f, vector2.x - num);
        localPosition.y = Mathf.Clamp(transform.localPosition.y, vector.y + num2 - 50f, vector2.y - num2 + 50f);
        transform.localPosition = localPosition;
    }
References Window.Setting.clampMargin, RectTransform, and setting.
Referenced by LayerInventory.CreateContainerAlly(), LayerInventory.CreateContainerPC(), InitPanel(), OnChangeResolution(), and ProcessMovement().
ClearBottomButtons()
void Window.ClearBottomButtons () inline
Definition at line 1481 of file Window.cs.
    {
        rectBottom.DestroyChildren();
    }
References rectBottom.
Close()
void Window.Close () inline
Definition at line 1531 of file Window.cs.
    {
        if ((bool)layer)
        {
            layer.OnClickClose();
        }
    }
References layer, and Layer.OnClickClose().
Referenced by Init().
CursorOverBottomBorder()
bool Window.CursorOverBottomBorder (bool canExceed = false) inline private
Definition at line 1995 of file Window.cs.
    {
        UIButton componentOf = InputModuleEX.GetComponentOf<UIButton>();
        if ((bool)componentOf && componentOf.GetComponentInParent<Window>() == this)
        {
            return false;
        }
        if (canExceed)
        {
            return LastScreenCursorPosition.y <= FrameInnerCorners[0].y;
        }
        if (LastScreenCursorPosition.y <= FrameInnerCorners[0].y && LastScreenCursorPosition.y >= FrameOuterCorners[0].y && LastScreenCursorPosition.x >= FrameOuterCorners[0].x)
        {
            return LastScreenCursorPosition.x <= FrameOuterCorners[2].x;
        }
        return false;
    }
References FrameInnerCorners, FrameOuterCorners, and LastScreenCursorPosition.
Referenced by OnPointerDown(), and ProcessCursorChanges().
CursorOverCaption()
bool Window.CursorOverCaption () inline private
Definition at line 2049 of file Window.cs.
    {
        foreach (GameObject item in InputModuleEX.GetList())
        {
            if (item != null && (bool)item.GetComponent<ScrollRect>())
            {
                return false;
            }
        }
        return true;
    }
References InputModuleEX.GetList(), and item.
Referenced by OnPointerDown().
CursorOverLeftBorder()
bool Window.CursorOverLeftBorder (bool canExceed = false) inline private
Definition at line 2013 of file Window.cs.
    {
        if (canExceed)
        {
            return LastScreenCursorPosition.x <= FrameInnerCorners[0].x;
        }
        if (LastScreenCursorPosition.x <= FrameInnerCorners[0].x && LastScreenCursorPosition.x >= FrameOuterCorners[0].x && LastScreenCursorPosition.y >= FrameOuterCorners[0].y)
        {
            return LastScreenCursorPosition.y <= FrameOuterCorners[1].y;
        }
        return false;
    }
References FrameInnerCorners, FrameOuterCorners, and LastScreenCursorPosition.
Referenced by OnPointerDown(), and ProcessCursorChanges().
CursorOverRightBorder()
bool Window.CursorOverRightBorder (bool canExceed = false) inline private
Definition at line 2026 of file Window.cs.
    {
        Scrollbar componentOf = InputModuleEX.GetComponentOf<Scrollbar>();
        if ((bool)componentOf && componentOf.GetComponentInParent<Window>() == this)
        {
            return false;
        }
        UIButton componentOf2 = InputModuleEX.GetComponentOf<UIButton>();
        if ((bool)componentOf2 && componentOf2.GetComponentInParent<Window>() == this)
        {
            return false;
        }
        if (canExceed)
        {
            return LastScreenCursorPosition.x >= FrameInnerCorners[3].x;
        }
        if (LastScreenCursorPosition.x >= FrameInnerCorners[3].x && LastScreenCursorPosition.x <= FrameOuterCorners[3].x && LastScreenCursorPosition.y >= FrameOuterCorners[0].y)
        {
            return LastScreenCursorPosition.y <= FrameOuterCorners[1].y;
        }
        return false;
    }
References FrameInnerCorners, FrameOuterCorners, and LastScreenCursorPosition.
Referenced by OnPointerDown(), and ProcessCursorChanges().
CursorOverTopBorder()
bool Window.CursorOverTopBorder (bool canExceed = false) inline private
Definition at line 1990 of file Window.cs.
    {
        return false;
    }
Referenced by ProcessCursorChanges().
CursorOverWindow()
bool Window.CursorOverWindow () inline private
Definition at line 2061 of file Window.cs.
    {
        if (LastScreenCursorPosition.x >= FrameOuterCorners[0].x && LastScreenCursorPosition.x <= FrameOuterCorners[3].x && LastScreenCursorPosition.y >= FrameOuterCorners[0].y)
        {
            return LastScreenCursorPosition.y <= FrameOuterCorners[1].y;
        }
        return false;
    }
References FrameOuterCorners, and LastScreenCursorPosition.
EnableShadow()
void Window.EnableShadow () inline
Definition at line 1506 of file Window.cs.
    {
        if (!imageBG)
        {
            return;
        }
        Shadow component = imageBG.GetComponent<Shadow>();
        if ((bool)component)
        {
            if (Skin.noShadow)
            {
                component.enabled = false;
                return;
            }
            component.effectColor = Skin.shadowColor;
            component.enabled = true;
        }
    }
References imageBG, SkinRootStatic.noShadow, SkinRootStatic.shadowColor, and Skin.
Referenced by ApplySkin().
GetContent< T >()
T Window.GetContent< T > () inline
Type Constraints
T : UIContent
Definition at line 1369 of file Window.cs.
                                     : UIContent
    {
        if ((bool)CurrentContent)
        {
            return CurrentContent as T;
        }
        return null;
    }
References CurrentContent.
GetTab() [1/2]
int Window.GetTab (string name) inline
Definition at line 1469 of file Window.cs.
    {
        for (int i = 0; i < setting.tabs.Count; i++)
        {
            if (setting.tabs[i].content.name == name)
            {
                return i;
            }
        }
        return 0;
    }
References setting, and Window.Setting.tabs.
GetTab() [2/2]
int Window.GetTab (UIContent content) inline
Definition at line 1457 of file Window.cs.
    {
        for (int i = 0; i < setting.tabs.Count; i++)
        {
            if (content == setting.tabs[i].content)
            {
                return i;
            }
        }
        return 0;
    }
References setting, and Window.Setting.tabs.
Referenced by SwitchContent(), and SwitchContent< T >().
Init()
void Window.Init (Layer _layer = null) inline
Definition at line 970 of file Window.cs.
    {
        _rect = this.Rect();
        layer = _layer;
        if (!setting.asWidget)
        {
            setting.allowResize = false;
            setting.saveWindow = false;
        }
        if (setting.saveWindow)
        {
            saveData = dictData.TryGetValue(idWindow);
        }
        if (saveData != null)
        {
            if (saveData.customAnchor != 0)
            {
                saveData.anchor = saveData.customAnchor;
            }
            if (AutoAnchor)
            {
                _rect.SetAnchor(saveData.anchor);
            }
            _rect.anchoredPosition = new Vector2(saveData.x, saveData.y);
            _rect.sizeDelta = new Vector2(saveData.w, saveData.h);
        }
        else if (setting.usePosFix)
        {
            _rect.anchoredPosition += setting.posFix;
        }
        if (openLastTab && setting.openLastTab && setting.tabs.Count > idTab && !setting.tabs[dictTab.TryGetValue(idWindow, 0)].disable)
        {
            idTab = dictTab.TryGetValue(idWindow, 0);
        }
        if (setting.textCaption.IsEmpty())
        {
            textCaption.SetActive(enable: false);
            iconCaption.SetActive(enable: false);
        }
        else
        {
            if (Lang.GetList(setting.textCaption) != null)
            {
                SetTitles(setting.textCaption);
            }
            else
            {
                SetCaption(setting.textCaption.lang());
            }
            if ((bool)setting.spriteCaption)
            {
                iconCaption.sprite = setting.spriteCaption;
            }
        }
        BuildTabs();
        bool flag = !(layer == null) && layer.option.canClose;
        if (flag && setting.bottomBack)
        {
            AddBottomButton("back", Close, setFirst: true);
        }
        if ((bool)buttonClose && buttonClose.gameObject.activeSelf)
        {
            buttonClose.onClick.RemoveAllListeners();
            buttonClose.onClick.AddListener(Close);
            buttonClose.SetActive(flag);
        }
        rectBottom.RebuildLayout(recursive: true);
        switch (setting.type)
        {
        case Type.AlignToMouse:
            leftSide = Input.mousePosition.x > (float)Screen.width / 1.5f;
            _rect.pivot = new Vector2(leftSide ? 1 : 0, _rect.pivot.y);
            _rect.position = Input.mousePosition + new Vector3(60f * (leftSide ? (-1f) : 1f), 0f, 0f);
            break;
        case Type.Side:
        {
            leftSide = Input.mousePosition.x > (float)Screen.width / 1.7f;
            float num = BaseCore.Instance.uiScale * (_rect.sizeDelta.x * 0.5f + 30f);
            _rect.position = new Vector3(leftSide ? num : ((float)Screen.width - num), _rect.position.y, 0f);
            setting.anime = Resources.Load<Anime>("Media/Anime/" + (leftSide ? "In Window from left" : "In Window from right"));
            break;
        }
        }
        RefreshTipPivotPosition();
        SwitchContent(idTab);
        InitPanel();
        ApplySkin();
        GameObject go = base.gameObject;
        if (!setting.anime || !animateWindow)
        {
            return;
        }
        BaseCore.Instance.actionsLateUpdate.Add(delegate
        {
            if ((bool)setting.anime && go != null)
            {
                tweenAnime = setting.anime.Play(this.Rect());
            }
        });
    }
References _rect, BaseCore.actionsLateUpdate, AddBottomButton(), Window.SaveData.anchor, animateWindow, Window.Setting.anime, ApplySkin(), Window.Setting.asWidget, AutoAnchor, Window.Setting.bottomBack, BuildTabs(), buttonClose, Layer.Option.canClose, Close(), Window.SaveData.customAnchor, dictData, dictTab, Lang.GetList(), Window.SaveData.h, iconCaption, idTab, idWindow, if(), InitPanel(), BaseCore.Instance, layer, leftSide, Window.Setting.openLastTab, openLastTab, Layer.option, Window.Setting.posFix, rectBottom, RefreshTipPivotPosition(), saveData, Window.Setting.saveWindow, SetCaption(), setting, SetTitles(), Window.Setting.spriteCaption, SwitchContent(), Window.Setting.tabs, Window.Setting.textCaption, textCaption, Window.Setting.type, BaseCore.uiScale, Window.Setting.usePosFix, Window.SaveData.w, Window.SaveData.x, and Window.SaveData.y.
InitPanel()
void Window.InitPanel () inline
Definition at line 1539 of file Window.cs.
    {
        if (!isStatic)
        {
            EventTrigger.Entry entry = new EventTrigger.Entry();
            entry.eventID = EventTriggerType.PointerEnter;
            entry.callback.AddListener(delegate(BaseEventData d)
            {
                OnPointerEnter(d as PointerEventData);
            });
            EventTrigger.triggers.Add(entry);
            entry = new EventTrigger.Entry();
            entry.eventID = EventTriggerType.PointerExit;
            entry.callback.AddListener(delegate(BaseEventData d)
            {
                OnPointerExit(d as PointerEventData);
            });
            EventTrigger.triggers.Add(entry);
            entry = new EventTrigger.Entry();
            entry.eventID = EventTriggerType.PointerDown;
            entry.callback.AddListener(delegate(BaseEventData d)
            {
                OnPointerDown(d as PointerEventData);
            });
            EventTrigger.triggers.Add(entry);
            entry = new EventTrigger.Entry();
            entry.eventID = EventTriggerType.PointerUp;
            entry.callback.AddListener(delegate(BaseEventData d)
            {
                OnPointerUp(d as PointerEventData);
            });
            EventTrigger.triggers.Add(entry);
            RecalculatePositionCaches();
            if (AutoAnchor)
            {
                SetAnchor();
            }
            ClampToScreen();
        }
    }
References AutoAnchor, ClampToScreen(), EventTrigger, isStatic, OnPointerDown(), OnPointerEnter(), OnPointerExit(), OnPointerUp(), RecalculatePositionCaches(), and SetAnchor().
Referenced by Init().
LoadHeader()
void Window.LoadHeader (string id = "HeaderRow") inline
Definition at line 1319 of file Window.cs.
    {
        ScrollRect componentInChildren = GetComponentInChildren<ScrollRect>();
        if ((bool)componentInChildren)
        {
            if ((bool)rectHeader)
            {
                UnityEngine.Object.DestroyImmediate(rectHeader.gameObject);
            }
            else
            {
                RectTransform viewport = componentInChildren.viewport;
                Vector2 sizeDelta = viewport.sizeDelta;
                sizeDelta.y -= 30f;
                viewport.anchoredPosition = sizeDelta;
                viewport.sizeDelta = sizeDelta;
            }
            Transform c = Util.Instantiate("UI/Element/Header/" + id, componentInChildren.transform);
            rectHeader = c.Rect();
        }
    }
References rectHeader, RectTransform, and Util.
Referenced by AddHeader(), and SetTitles().
NextTab()
bool Window.NextTab (int a) inline
Definition at line 1378 of file Window.cs.
    {
        List<Setting.Tab> list = new List<Setting.Tab>();
        foreach (Setting.Tab tab in setting.tabs)
        {
            if (!tab.disable && (bool)tab.button)
            {
                list.Add(tab);
            }
        }
        if (list.Count > 1)
        {
            ((a < 0) ? list.NextItem(CurrentTab) : list.PrevItem(CurrentTab)).button._OnPress();
            return true;
        }
        return false;
    }
References CurrentTab, setting, and Window.Setting.tabs.
Referenced by Scene.OnUpdate().
OnApplicationFocus()
void Window.OnApplicationFocus (bool focus) inline
Definition at line 1606 of file Window.cs.
    {
        IsProcessingCursorChanges = false;
        IsProcessingMovement = false;
        IsResizingOverBottom = false;
        IsResizingOverLeft = false;
        IsResizingOverRight = false;
    }
References IsProcessingCursorChanges, IsProcessingMovement, IsResizingOverBottom, IsResizingOverLeft, and IsResizingOverRight.
OnChangeResolution()
void Window.OnChangeResolution () inline
Implements IChangeResolution.
Definition at line 1580 of file Window.cs.
    {
        if (!isStatic)
        {
            RecalculatePositionCaches();
            if (AutoAnchor)
            {
                SetAnchor();
            }
            IsProcessingCursorChanges = true;
            ClampToScreen();
        }
    }
References AutoAnchor, ClampToScreen(), IsProcessingCursorChanges, isStatic, RecalculatePositionCaches(), and SetAnchor().
OnKill()
void Window.OnKill () inline
Definition at line 1116 of file Window.cs.
    {
        UpdateSaveData();
        if (saveData != null)
        {
            saveData.open = false;
        }
        if (setting.openLastTab)
        {
            dictTab[idWindow] = idTab;
        }
    }
References dictTab, idTab, idWindow, Window.Setting.openLastTab, saveData, setting, and UpdateSaveData().
Referenced by Layer.Kill().
OnPointerDown()
void Window.OnPointerDown (PointerEventData data) inline private
Definition at line 1794 of file Window.cs.
    {
        if (data.button == PointerEventData.InputButton.Left && !(EInput.dragHack < 0.1f))
        {
            base.transform.SetAsLastSibling();
            IsProcessingCursorChanges = false;
            IsResizingOverBottom = setting.allowResize && CursorOverBottomBorder();
            IsResizingOverLeft = setting.allowResize && CursorOverLeftBorder();
            IsResizingOverRight = setting.allowResize && CursorOverRightBorder();
            IsProcessingMovement = !IsResizingOverBottom && !IsResizingOverLeft && !IsResizingOverRight && setting.allowMove && CursorOverCaption();
            dragStartPos = Input.mousePosition;
            dragOffset = base.transform.position - dragStartPos;
            IsProcessingResize = IsResizingOverTop || IsResizingOverBottom || IsResizingOverLeft || IsResizingOverRight;
        }
    }
References CursorOverBottomBorder(), CursorOverCaption(), CursorOverLeftBorder(), CursorOverRightBorder(), EInput.dragHack, dragOffset, dragStartPos, IsProcessingCursorChanges, IsProcessingMovement, IsProcessingResize, IsResizingOverBottom, IsResizingOverLeft, IsResizingOverRight, and IsResizingOverTop.
Referenced by InitPanel().
OnPointerEnter()
void Window.OnPointerEnter (PointerEventData data) inline private
Definition at line 1780 of file Window.cs.
    {
        IsProcessingCursorChanges = !Input.GetMouseButton(0);
    }
References IsProcessingCursorChanges.
Referenced by InitPanel().
OnPointerExit()
void Window.OnPointerExit (PointerEventData data) inline private
Definition at line 1785 of file Window.cs.
    {
        IsProcessingCursorChanges = false;
        if (!IsProcessingResize && !Input.GetMouseButton(0))
        {
            CursorSystem.SetCursor();
        }
    }
References IsProcessingCursorChanges, IsProcessingResize, and CursorSystem.SetCursor().
Referenced by InitPanel().
OnPointerUp()
void Window.OnPointerUp (PointerEventData data) inline private
Definition at line 1810 of file Window.cs.
    {
    }
Referenced by InitPanel().
ProcessCursorChanges()
void Window.ProcessCursorChanges () inline private
Definition at line 1814 of file Window.cs.
    {
        if (setting.allowResize && (isTop || IsProcessingResize))
        {
            if ((CursorOverTopBorder() && CursorOverLeftBorder()) || (CursorOverBottomBorder() && CursorOverRightBorder()))
            {
                SetCursor(CursorSystem.ResizeNWSE);
            }
            else if ((CursorOverTopBorder() && CursorOverRightBorder()) || (CursorOverBottomBorder() && CursorOverLeftBorder()))
            {
                SetCursor(CursorSystem.ResizeNESW);
            }
            else if (CursorOverTopBorder() || CursorOverBottomBorder())
            {
                SetCursor(CursorSystem.ResizeNS);
            }
            else if (CursorOverLeftBorder() || CursorOverRightBorder())
            {
                SetCursor(CursorSystem.ResizeWE);
            }
        }
        void SetCursor(CursorInfo info)
        {
            Window topComponentOf = InputModuleEX.GetTopComponentOf<Window>();
            if (!topComponentOf || !(topComponentOf != this))
            {
                CursorSystem.SetCursor(info);
            }
        }
    }
References Window.Setting.allowResize, CursorOverBottomBorder(), CursorOverLeftBorder(), CursorOverRightBorder(), CursorOverTopBorder(), IsProcessingResize, isTop, CursorSystem.ResizeNESW, CursorSystem.ResizeNS, CursorSystem.ResizeNWSE, CursorSystem.ResizeWE, CursorSystem.SetCursor(), and setting.
Referenced by Update().
ProcessMovement()
void Window.ProcessMovement () inline private
Definition at line 1845 of file Window.cs.
    {
        Vector3 mousePosition = Input.mousePosition;
        mousePosition.x = Mathf.Clamp(mousePosition.x, 0f, Canvas.pixelRect.width);
        mousePosition.y = Mathf.Clamp(mousePosition.y, 0f, Canvas.pixelRect.height);
        base.transform.position = Input.mousePosition + dragOffset;
        ClampToScreen();
    }
References Canvas, ClampToScreen(), and dragOffset.
Referenced by Update().
ProcessResize()
void Window.ProcessResize () inline private
Definition at line 1854 of file Window.cs.
    {
        Vector3 vector = Input.mousePosition;
        vector.x = Mathf.Clamp(vector.x, 0f, Canvas.pixelRect.width);
        vector.y = Mathf.Clamp(vector.y, 0f, Canvas.pixelRect.height);
        Vector3 vector2 = LastScreenCursorPosition;
        Vector3 vector3 = vector - vector2;
        if (vector3.x == 0f && vector3.y == 0f)
        {
            return;
        }
        if (Canvas.renderMode == RenderMode.ScreenSpaceCamera)
        {
            vector = Canvas.worldCamera.ScreenToWorldPoint(new Vector3(vector.x, vector.y, Canvas.planeDistance));
            vector2 = Canvas.worldCamera.ScreenToWorldPoint(new Vector3(vector2.x, vector2.y, Canvas.planeDistance));
        }
        Vector3 vector4 = vector - vector2;
        Vector3 position = RectTransform.position;
        Vector2 sizeDelta = RectTransform.sizeDelta;
        Vector2 size = RectTransform.rect.size;
        Vector3 zero = Vector3.zero;
        Vector2 zero2 = Vector2.zero;
        Rect bound = setting.bound;
        float x = bound.x;
        float y = bound.y;
        float width = bound.width;
        float height = bound.height;
        if (IsResizingOverTop || IsResizingOverBottom)
        {
            if (RectTransform.anchorMin.y == RectTransform.anchorMax.y)
            {
                if (IsResizingOverTop)
                {
                    float num = sizeDelta.y + vector3.y;
                    if (num > y && num < height)
                    {
                        zero.y = vector4.y * RectTransform.pivot.y;
                        zero2.y = vector3.y;
                    }
                }
                else if (IsResizingOverBottom)
                {
                    float num2 = sizeDelta.y - vector3.y;
                    if (num2 > y && num2 < height)
                    {
                        zero.y = vector4.y * (1f - RectTransform.pivot.y);
                        zero2.y = 0f - vector3.y;
                    }
                }
                position.y += zero.y;
                sizeDelta.y += zero2.y / CorrectedLossyScale.y;
            }
            else
            {
                if (IsResizingOverTop)
                {
                    float num3 = size.y + vector3.y;
                    if (num3 > y && num3 < height)
                    {
                        zero.y = vector4.y * RectTransform.pivot.y;
                        zero2.y = vector3.y;
                    }
                }
                else if (IsResizingOverBottom)
                {
                    float num4 = size.y - vector3.y;
                    if (num4 > y && num4 < height)
                    {
                        zero.y = vector4.y * (1f - RectTransform.pivot.y);
                        zero2.y = 0f - vector3.y;
                    }
                }
                position.y += zero.y;
                sizeDelta.y += zero2.y / CorrectedLossyScale.y;
            }
        }
        if (IsResizingOverRight || IsResizingOverLeft)
        {
            if (RectTransform.anchorMin.x == RectTransform.anchorMax.x)
            {
                if (IsResizingOverRight)
                {
                    float num5 = sizeDelta.x + vector3.x;
                    if (num5 > x && num5 < width)
                    {
                        zero.x = vector4.x * RectTransform.pivot.x;
                        zero2.x = vector3.x;
                    }
                }
                else if (IsResizingOverLeft)
                {
                    float num6 = sizeDelta.x - vector3.x;
                    if (num6 > x && num6 < width)
                    {
                        zero.x = vector4.x * (1f - RectTransform.pivot.x);
                        zero2.x = 0f - vector3.x;
                    }
                }
                position.x += zero.x;
                sizeDelta.x += zero2.x / CorrectedLossyScale.x;
            }
            else
            {
                if (IsResizingOverRight)
                {
                    float num7 = size.x + vector3.x;
                    if (num7 > x && num7 < width)
                    {
                        zero.x = vector4.x * RectTransform.pivot.x;
                        zero2.x = vector3.x;
                    }
                }
                else if (IsResizingOverLeft)
                {
                    float num8 = size.x - vector3.x;
                    if (num8 > x && num8 < width)
                    {
                        zero.x = vector4.x * (1f - RectTransform.pivot.x);
                        zero2.x = 0f - vector3.x;
                    }
                }
                position.x += zero.x;
                sizeDelta.x += zero2.x / CorrectedLossyScale.x;
            }
        }
        if (setting.resizeGrid != Vector2.zero)
        {
            sizeDelta.x = setting.resizeGrid.x * (float)(int)(sizeDelta.x / setting.resizeGrid.x);
            sizeDelta.y = setting.resizeGrid.y * (float)(int)(sizeDelta.y / setting.resizeGrid.y);
        }
        RectTransform.sizeDelta = sizeDelta;
        RectTransform.position = position;
        RecalculatePositionCaches();
        this.RebuildLayout(recursive: true);
    }
References Window.Setting.bound, Canvas, CorrectedLossyScale, IsResizingOverBottom, IsResizingOverLeft, IsResizingOverRight, IsResizingOverTop, LastScreenCursorPosition, RecalculatePositionCaches(), RectTransform, Window.Setting.resizeGrid, and setting.
Referenced by Update().
RecalculatePositionCaches()
void Window.RecalculatePositionCaches () inline private
Definition at line 1599 of file Window.cs.
    {
        _frameInnerCorners = null;
        _frameOuterCorners = null;
        _captionCorners = null;
    }
References _captionCorners, _frameInnerCorners, and _frameOuterCorners.
Referenced by InitPanel(), OnChangeResolution(), ProcessResize(), and Update().
RefreshTipPivotPosition()
void Window.RefreshTipPivotPosition () inline
Definition at line 1071 of file Window.cs.
    {
        bool flag = (float)(Screen.width / 2 - 40) > base.transform.position.x;
        if ((bool)tipPiovotLeft)
        {
            tipPiovotLeft.SetActive(!flag || !tipPivotRight);
        }
        if ((bool)tipPivotRight)
        {
            tipPivotRight.SetActive(flag || !tipPiovotLeft);
        }
    }
References tipPiovotLeft, and tipPivotRight.
Referenced by Init(), and Update().
SetAnchor()
void Window.SetAnchor () inline
Definition at line 1594 of file Window.cs.
    {
        _rect.SetAnchor((saveData != null) ? saveData.customAnchor : RectPosition.Auto);
    }
References _rect, Window.SaveData.customAnchor, and saveData.
Referenced by Widget.AddLayer(), InitPanel(), OnChangeResolution(), and Update().
SetCaption()
void Window.SetCaption (string text) inline
Definition at line 1289 of file Window.cs.
    {
        textCaption.SetText(text);
        textCaption.RebuildLayout();
    }
References UIText.SetText(), and textCaption.
Referenced by Init(), ListOwner< T1, T2 >.OnSwitchContent(), WindowChara.RefreshStatic(), SetTitles(), and SwitchContent().
SetContent()
void Window.SetContent (int tabIndex, UIContent content) inline
Definition at line 1355 of file Window.cs.
    {
        if (tabIndex != -1)
        {
            Setting.Tab tab = setting.tabs[tabIndex];
            if ((bool)tab.content && !tab.content.IsPrefab())
            {
                tab.content.SetActive(enable: false);
            }
            tab.content = content;
            tab.button = rectTab.GetComponentsInChildren<UIButton>()[tabIndex];
        }
    }
References Window.Setting.Tab.content, rectTab, setting, and Window.Setting.tabs.
Referenced by SetContent< T >().
SetContent< T >()
T Window.SetContent< T > (int tabIndex = -1, string id = null) inline
Type Constraints
T : UIContent
Definition at line 1348 of file Window.cs.
                                                                        : UIContent
    {
        T val = Util.Instantiate<T>("UI/Content/" + typeof(T).Name, view);
        SetContent(tabIndex, val);
        return val;
    }
References SetContent(), Util, and view.
SetInteractable()
void Window.SetInteractable (bool enable, float alpha = 0::5f) inline
Definition at line 1525 of file Window.cs.
    {
        cg.alpha = (enable ? 1f : alpha);
        GetComponent<GraphicRaycaster>().enabled = enable;
    }
Referenced by LayerCraft.OnCompleteCraft(), and LayerCraft.SetFactory().
SetPosition()
void Window.SetPosition () inline
Definition at line 1341 of file Window.cs.
    {
        RectTransform rectTransform = this.Rect();
        rectTransform.pivot = new Vector2(0.5f, 0.5f);
        rectTransform.anchoredPosition = Vector2.zero;
    }
References RectTransform.
SetRect()
void Window.SetRect (RectData data, bool mousePos = false) inline
Definition at line 1084 of file Window.cs.
    {
        data.Apply(_rect);
        if (mousePos)
        {
            _rect.position = EInput.uiMousePosition;
        }
    }
References _rect, RectData.Apply(), and EInput.uiMousePosition.
SetTitles()
void Window.SetTitles (string langList, string idHeaderRow = null) inline
Definition at line 1262 of file Window.cs.
    {
        string[] list = Lang.GetList(langList);
        if (!list[0].IsEmpty())
        {
            SetCaption(list[0]);
        }
        if (list.Length >= 3)
        {
            if (!rectHeader || idHeaderRow != null)
            {
                LoadHeader(idHeaderRow);
            }
            UIHeader[] componentsInChildren = rectHeader.GetComponentsInChildren<UIHeader>(includeInactive: true);
            UIHeader[] array = componentsInChildren;
            for (int i = 0; i < array.Length; i++)
            {
                array[i].SetActive(enable: false);
            }
            for (int j = 0; j < list.Length - 3 && componentsInChildren.Length >= j + 1; j++)
            {
                componentsInChildren[j].SetActive(!list[j + 3].IsEmpty());
                componentsInChildren[j].SetText(list[j + 3]);
            }
        }
    }
References Lang.GetList(), LoadHeader(), rectHeader, SetCaption(), and UIHeader.SetText().
Referenced by Init(), and ListOwner< T1, T2 >.OnSwitchContent().
SwitchContent() [1/4]
UIContent Window.SwitchContent (int index) inline
Definition at line 1213 of file Window.cs.
    {
        idTab = index;
        if (setting.tabs.Count > 0)
        {
            Setting.Tab tab = setting.tabs[index];
            foreach (Setting.Tab tab2 in setting.tabs)
            {
                if ((bool)tab2.content && !tab2.content.IsPrefab())
                {
                    tab2.content.SetActive(tab2 == tab);
                }
            }
            if ((bool)groupTab)
            {
                groupTab.Select(setting.tabs[index].button);
            }
            if ((bool)tab.content)
            {
                if (tab.content.IsPrefab())
                {
                    tab.content = Util.Instantiate(tab.content, view);
                    tab.content.SetActive(enable: true);
                    tab.content.OnInstantiate();
                }
                tab.content.SetActive(enable: true);
                tab.content.OnSwitchContent(idTab);
            }
            if (tab.action != null)
            {
                tab.action();
            }
            string text = ((layer == null) ? "" : layer.GetTextHeader(this));
            if (!text.IsEmpty())
            {
                SetCaption(text);
            }
        }
        if ((bool)controller)
        {
            controller.OnSwitchContent(this);
        }
        else if ((bool)layer)
        {
            layer.OnSwitchContent(this);
        }
        return CurrentContent;
    }
References Window.Setting.Tab.action, Window.Setting.Tab.content, controller, CurrentContent, Layer.GetTextHeader(), groupTab, idTab, layer, UIContent.OnInstantiate(), UIContent.OnSwitchContent(), Layer.OnSwitchContent(), WindowController.OnSwitchContent(), UISelectableGroup.Select(), SetCaption(), setting, Window.Setting.tabs, Util, and view.
SwitchContent() [2/4]
void Window.SwitchContent (Setting::Tab tab) inline
Definition at line 1208 of file Window.cs.
    {
        SwitchContent(setting.tabs.IndexOf(tab));
    }
References setting, SwitchContent(), and Window.Setting.tabs.
SwitchContent() [3/4]
void Window.SwitchContent (string name) inline
Definition at line 1203 of file Window.cs.
    {
        SwitchContent(GetTab(name));
    }
References GetTab(), and SwitchContent().
SwitchContent() [4/4]
void Window.SwitchContent (UIContent content) inline
Definition at line 1198 of file Window.cs.
    {
        SwitchContent(GetTab(content));
    }
References GetTab(), and SwitchContent().
Referenced by BuildTabs(), Init(), WindowChara.SetChara(), SwitchContent(), and SwitchContent< T >().
SwitchContent< T >()
T Window.SwitchContent< T > () inline
Type Constraints
T : UIContent
Definition at line 1192 of file Window.cs.
                                        : UIContent
    {
        SwitchContent(GetTab(typeof(T).Name.Replace("Content", "")));
        return CurrentContent as T;
    }
References CurrentContent, GetTab(), and SwitchContent().
Update()
void Window.Update () inline private
Definition at line 1615 of file Window.cs.
    {
        RefreshTipPivotPosition();
        if (isStatic)
        {
            return;
        }
        isTop = InputModuleEX.GetComponentOf<Window>() == this;
        if (isFloat && (bool)cgFloatMenu && cgFloatMenu.enabled)
        {
            bool flag = InputModuleEX.IsPointerOver(this) && (saveData == null || !saveData.shiftToShowMenu || Input.GetKey(KeyCode.LeftShift) || Input.GetKey(KeyCode.RightShift));
            floatAlpha = Mathf.Clamp(floatAlpha + (flag ? 2f : (-2f)) * Time.deltaTime * 1.5f, 0.5f, 1f);
            if ((bool)cgBG)
            {
                cgBG.alpha = floatAlpha;
            }
            float alpha = (floatAlpha - 0.5f) * 2f;
            if ((bool)cgFloatMenu)
            {
                cgFloatMenu.alpha = alpha;
            }
            cgFloatMenu.SetActive(cgFloatMenu.alpha > 0f);
            foreach (CanvasGroup item in listCgFloat)
            {
                item.alpha = alpha;
            }
        }
        if ((bool)attachedWindow)
        {
            Vector2 anchoredPosition = attachedWindow._rect.anchoredPosition;
            Vector2 anchoredPosition2 = new Vector2(anchoredPosition.x, anchoredPosition.y - attachedWindow._rect.sizeDelta.y) + attachFix;
            if (!_rect.anchorMin.Equals(attachedWindow._rect.anchorMin) || !_rect.anchorMax.Equals(attachedWindow._rect.anchorMax))
            {
                _rect.anchorMin = attachedWindow._rect.anchorMin;
                _rect.anchorMax = attachedWindow._rect.anchorMax;
            }
            if (_rect.anchoredPosition.x != anchoredPosition2.x || _rect.anchoredPosition.y != anchoredPosition2.y)
            {
                _rect.anchoredPosition = anchoredPosition2;
            }
            if (_rect.sizeDelta.x != attachedWindow._rect.sizeDelta.x)
            {
                _rect.sizeDelta = new Vector2(attachedWindow._rect.sizeDelta.x, _rect.sizeDelta.y);
            }
            rectCaption.SetActive(enable: false);
        }
        if (setting.dontBringToTop && base.transform.GetSiblingIndex() != 0)
        {
            base.transform.SetAsFirstSibling();
        }
        if (scrolling)
        {
            IsProcessingCursorChanges = false;
            IsProcessingMovement = false;
            IsResizingOverBottom = false;
            IsResizingOverLeft = false;
            IsResizingOverRight = false;
            CursorSystem.SetCursor();
        }
        else
        {
            if (IsProcessingCursorChanges)
            {
                ProcessCursorChanges();
            }
            if (IsProcessingMovement)
            {
                ProcessMovement();
            }
            if (IsProcessingResize)
            {
                ProcessResize();
            }
            if (isTop)
            {
                if ((IsResizingOverTop || IsResizingOverBottom) && (IsResizingOverRight || IsResizingOverLeft))
                {
                    CursorSystem.SetCursor(CursorSystem.ResizeNWSE);
                }
                else if (IsResizingOverTop || IsResizingOverBottom)
                {
                    CursorSystem.SetCursor(CursorSystem.ResizeNS);
                }
                else if (IsResizingOverRight || IsResizingOverLeft)
                {
                    CursorSystem.SetCursor(CursorSystem.ResizeWE);
                }
            }
        }
        if (Input.GetMouseButtonDown(0))
        {
            if ((bool)InputModuleEX.GetComponentOf<Scrollbar>())
            {
                scrolling = true;
            }
            if (isTop && !setting.dontBringToTop)
            {
                BringToTop();
            }
        }
        if (Input.GetMouseButtonUp(0))
        {
            if (IsProcessingMovement)
            {
                IsProcessingMovement = false;
                if (AutoAnchor)
                {
                    SetAnchor();
                }
            }
            scrolling = false;
            RecalculatePositionCaches();
            if (IsProcessingResize)
            {
                UIDynamicList[] componentsInChildren = GetComponentsInChildren<UIDynamicList>();
                for (int i = 0; i < componentsInChildren.Length; i++)
                {
                    componentsInChildren[i].OnResizeWindow();
                }
                IsProcessingResize = false;
            }
            IsProcessingCursorChanges = true;
            IsResizingOverTop = false;
            IsResizingOverBottom = false;
            IsResizingOverLeft = false;
            IsResizingOverRight = false;
        }
        LastScreenCursorPosition = Input.mousePosition;
        LastScreenCursorPosition.x = Mathf.Clamp(LastScreenCursorPosition.x, 0f, Canvas.pixelRect.width);
        LastScreenCursorPosition.y = Mathf.Clamp(LastScreenCursorPosition.y, 0f, Canvas.pixelRect.height);
    }
References _rect, attachedWindow, attachFix, AutoAnchor, BringToTop(), Canvas, cgBG, cgFloatMenu, Window.Setting.dontBringToTop, floatAlpha, isFloat, InputModuleEX.IsPointerOver(), IsProcessingCursorChanges, IsProcessingMovement, IsProcessingResize, IsResizingOverBottom, IsResizingOverLeft, IsResizingOverRight, IsResizingOverTop, isStatic, isTop, item, LastScreenCursorPosition, listCgFloat, UIDynamicList.OnResizeWindow(), ProcessCursorChanges(), ProcessMovement(), ProcessResize(), RecalculatePositionCaches(), rectCaption, RefreshTipPivotPosition(), CursorSystem.ResizeNS, CursorSystem.ResizeNWSE, CursorSystem.ResizeWE, saveData, scrolling, SetAnchor(), CursorSystem.SetCursor(), and setting.
UpdateSaveData()
void Window.UpdateSaveData () inline
Definition at line 1093 of file Window.cs.
    {
        if (setting.saveWindow)
        {
            if (saveData == null)
            {
                saveData = new SaveData();
            }
            dictData[idWindow] = saveData;
        }
        if (saveData != null)
        {
            saveData.anchor = ((saveData.customAnchor == RectPosition.Auto) ? _rect.GetAnchor() : saveData.customAnchor);
            _rect.SetAnchor(saveData.anchor);
            Vector2 anchoredPosition = _rect.anchoredPosition;
            Vector2 sizeDelta = _rect.sizeDelta;
            saveData.x = anchoredPosition.x;
            saveData.y = anchoredPosition.y;
            saveData.w = sizeDelta.x;
            saveData.h = sizeDelta.y;
        }
    }
References _rect, Window.SaveData.anchor, Window.SaveData.customAnchor, dictData, idWindow, saveData, Window.Setting.saveWindow, and setting.
Referenced by LayerInventory.CreateContainerAlly(), LayerInventory.CreateContainerPC(), Player.OnBeforeSave(), and OnKill().
Member Data Documentation
_canvas
Canvas Window._canvas private
Definition at line 734 of file Window.cs.
_captionCorners
Vector3 [] Window._captionCorners private
Definition at line 746 of file Window.cs.
Referenced by RecalculatePositionCaches().
_correctedLossyScale
Vector3 Window._correctedLossyScale private
Definition at line 740 of file Window.cs.
_eventTrigger
EventTrigger Window._eventTrigger private
Definition at line 736 of file Window.cs.
_frameInnerCorners
Vector3 [] Window._frameInnerCorners private
Definition at line 744 of file Window.cs.
Referenced by RecalculatePositionCaches().
_frameOuterCorners
Vector3 [] Window._frameOuterCorners private
Definition at line 742 of file Window.cs.
Referenced by RecalculatePositionCaches().
_rect
RectTransform Window._rect private
Definition at line 674 of file Window.cs.
Referenced by Awake(), Init(), SetAnchor(), SetRect(), Update(), and UpdateSaveData().
_rectTransform
RectTransform Window._rectTransform private
Definition at line 738 of file Window.cs.
animateWindow
bool Window.animateWindow static
Definition at line 600 of file Window.cs.
Referenced by Init().
attachedWindow
Window Window.attachedWindow
Definition at line 730 of file Window.cs.
Referenced by Update().
attachFix
Vector2 Window.attachFix
Definition at line 732 of file Window.cs.
Referenced by Update().
bgCaption
UIImage Window.bgCaption
Definition at line 622 of file Window.cs.
Referenced by ApplySkin().
bgCollider
UICollider Window.bgCollider
Definition at line 670 of file Window.cs.
Referenced by Widget.AddLayer().
bgShadow
Shadow Window.bgShadow private
Definition at line 728 of file Window.cs.
Referenced by ApplySkin(), and Awake().
buttonClose
Button Window.buttonClose
Definition at line 624 of file Window.cs.
Referenced by LayerInventory.CreateContainerAlly(), LayerInventory.CreateContainerPC(), Layer.DisableClose(), and Init().
buttonExtra
UIButton Window.buttonExtra
Definition at line 632 of file Window.cs.
buttonHelp
UIButton Window.buttonHelp
Definition at line 626 of file Window.cs.
buttonQuickSort
UIButton Window.buttonQuickSort
Definition at line 630 of file Window.cs.
buttonShared
UIButton Window.buttonShared
Definition at line 634 of file Window.cs.
buttonSort
UIButton Window.buttonSort
Definition at line 628 of file Window.cs.
CaptionHeight
float Window.CaptionHeight = 50f
Definition at line 689 of file Window.cs.
cg
CanvasGroup Window.cg
Definition at line 712 of file Window.cs.
Referenced by ApplySkin(), and Awake().
cgBG
CanvasGroup Window.cgBG
Definition at line 666 of file Window.cs.
Referenced by LayerAbility.RefreshConfig(), and Update().
cgFloatMenu
CanvasGroup Window.cgFloatMenu
Definition at line 668 of file Window.cs.
Referenced by Update().
controller
WindowController Window.controller
Definition at line 660 of file Window.cs.
Referenced by Awake(), and SwitchContent().
deco1
Image Window.deco1
Definition at line 616 of file Window.cs.
Referenced by ApplySkin().
deco2
Image Window.deco2
Definition at line 618 of file Window.cs.
dictData
Dictionary<string, SaveData> Window.dictData = new Dictionary<string, SaveData>() static
Definition at line 594 of file Window.cs.
Referenced by Core.Awake(), LayerInventory.CreateBuy(), Card.GetWindowSaveData(), Init(), ELayer.Kill(), Player.OnBeforeSave(), LayerEquip.OnInit(), UIInventory.RefreshWindow(), ContentConfigOther.ResetWindows(), HotItemLayout.Save(), and UpdateSaveData().
dictTab
Dictionary<string, int> Window.dictTab = new Dictionary<string, int>() static
Definition at line 596 of file Window.cs.
Referenced by Init(), Game.Kill(), and OnKill().
dragOffset
Vector3 Window.dragOffset private
Definition at line 766 of file Window.cs.
Referenced by OnPointerDown(), and ProcessMovement().
dragStartPos
Vector3 Window.dragStartPos private
Definition at line 764 of file Window.cs.
Referenced by OnPointerDown().
floatAlpha
float Window.floatAlpha private
Definition at line 772 of file Window.cs.
Referenced by Update().
FrameOffsetL
float Window.FrameOffsetL = -15f
Definition at line 681 of file Window.cs.
FrameOffsetR
float Window.FrameOffsetR = -15f
Definition at line 683 of file Window.cs.
FrameOffsetTop
float Window.FrameOffsetTop = -30f
Definition at line 685 of file Window.cs.
frameOffsetY
float Window.frameOffsetY = 5f
Definition at line 691 of file Window.cs.
FrameThickness
float Window.FrameThickness = 14f
Definition at line 687 of file Window.cs.
groupTab
UISelectableGroup Window.groupTab
Definition at line 658 of file Window.cs.
Referenced by BuildTabs(), LayerCraft.OnCompleteCraft(), and SwitchContent().
iconCaption
Image Window.iconCaption
Definition at line 614 of file Window.cs.
Referenced by Init().
idTab
int Window.idTab
Definition at line 694 of file Window.cs.
Referenced by Layer.GetTextHeader(), Init(), OnKill(), LayerAbility.OnSwitchContent(), LayerAdmin.OnSwitchContent(), LayerDebug.OnSwitchContent(), LayerFactions.OnSwitchContent(), LayerPeople.OnSwitchContent(), LayerQuestBoard.OnSwitchContent(), WindowChara.OnSwitchContent(), WindowCharaMini.OnSwitchContent(), WindowChara.SetChara(), SwitchContent(), and WindowChara.ToggleFeatMode().
imageBG
UIImage Window.imageBG
Definition at line 620 of file Window.cs.
Referenced by ApplySkin(), Awake(), and EnableShadow().
isFloat
bool Window.isFloat
Definition at line 604 of file Window.cs.
Referenced by Update().
IsProcessingCursorChanges
bool Window.IsProcessingCursorChanges private
Definition at line 748 of file Window.cs.
Referenced by OnApplicationFocus(), OnChangeResolution(), OnPointerDown(), OnPointerEnter(), OnPointerExit(), and Update().
IsProcessingMovement
bool Window.IsProcessingMovement private
Definition at line 750 of file Window.cs.
Referenced by OnApplicationFocus(), OnPointerDown(), and Update().
IsProcessingResize
bool Window.IsProcessingResize private
Definition at line 752 of file Window.cs.
Referenced by OnPointerDown(), OnPointerExit(), ProcessCursorChanges(), and Update().
IsResizingOverBottom
bool Window.IsResizingOverBottom private
Definition at line 756 of file Window.cs.
Referenced by OnApplicationFocus(), OnPointerDown(), ProcessResize(), and Update().
IsResizingOverLeft
bool Window.IsResizingOverLeft private
Definition at line 758 of file Window.cs.
Referenced by OnApplicationFocus(), OnPointerDown(), ProcessResize(), and Update().
IsResizingOverRight
bool Window.IsResizingOverRight private
Definition at line 760 of file Window.cs.
Referenced by OnApplicationFocus(), OnPointerDown(), ProcessResize(), and Update().
IsResizingOverTop
bool Window.IsResizingOverTop private
Definition at line 754 of file Window.cs.
Referenced by OnPointerDown(), ProcessResize(), and Update().
isTop
bool Window.isTop private
Definition at line 770 of file Window.cs.
Referenced by ProcessCursorChanges(), and Update().
LastScreenCursorPosition
Vector3 Window.LastScreenCursorPosition private
Definition at line 762 of file Window.cs.
Referenced by CursorOverBottomBorder(), CursorOverLeftBorder(), CursorOverRightBorder(), CursorOverWindow(), ProcessResize(), and Update().
layer
Layer Window.layer
Definition at line 677 of file Window.cs.
Referenced by BringToTop(), Close(), Init(), SwitchContent(), and UIBook.Update().
layoutWindow
LayoutGroup Window.layoutWindow private
Definition at line 679 of file Window.cs.
Referenced by Awake().
leftSide
bool Window.leftSide = true
Definition at line 602 of file Window.cs.
Referenced by Init().
listCgFloat
List<CanvasGroup> Window.listCgFloat
Definition at line 672 of file Window.cs.
Referenced by LayerAbility.RefreshConfig(), and Update().
menuBottom
WindowMenu Window.menuBottom
Definition at line 706 of file Window.cs.
Referenced by Awake().
menuLeft
WindowMenu Window.menuLeft
Definition at line 700 of file Window.cs.
Referenced by ApplySkin(), Awake(), ListOwner< T1, T2 >.OnRefreshMenu(), and LayerHome.OnSwitchContent().
menuLeftBottom
WindowMenu Window.menuLeftBottom
Definition at line 703 of file Window.cs.
Referenced by Awake().
menuRight
WindowMenu Window.menuRight
Definition at line 709 of file Window.cs.
Referenced by Awake(), and ListOwner< T1, T2 >.OnRefreshMenu().
moldBottom
UIButton Window.moldBottom
Definition at line 638 of file Window.cs.
Referenced by AddBottomButton().
moldTab
UIButton Window.moldTab
Definition at line 636 of file Window.cs.
Referenced by BuildTabs().
openLastTab
bool Window.openLastTab static
Definition at line 598 of file Window.cs.
Referenced by Init().
posBottom
Vector2 Window.posBottom
Definition at line 715 of file Window.cs.
Referenced by ApplySkin(), and Awake().
posCaption
Vector2 Window.posCaption
Definition at line 721 of file Window.cs.
Referenced by Awake().
posTab
Vector2 Window.posTab
Definition at line 718 of file Window.cs.
Referenced by ApplySkin(), and Awake().
rectBottom
RectTransform Window.rectBottom
Definition at line 646 of file Window.cs.
Referenced by AddBottomButton(), AddBottomSpace(), Awake(), ClearBottomButtons(), and Init().
rectCaption
RectTransform Window.rectCaption
Definition at line 642 of file Window.cs.
Referenced by Awake(), and Update().
rectCorner
RectTransform Window.rectCorner
Definition at line 640 of file Window.cs.
Referenced by ApplySkin().
rectDeco
RectTransform Window.rectDeco
Definition at line 654 of file Window.cs.
Referenced by ApplySkin().
rectHeader
RectTransform Window.rectHeader
Definition at line 656 of file Window.cs.
Referenced by AddHeader(), LoadHeader(), and SetTitles().
rectStats
RectTransform Window.rectStats
Definition at line 648 of file Window.cs.
Referenced by UIScrollView.Awake().
rectTab
RectTransform Window.rectTab
Definition at line 644 of file Window.cs.
Referenced by Awake(), BuildTabs(), Scene.OnUpdate(), and SetContent().
saveData
SaveData Window.saveData
Definition at line 724 of file Window.cs.
Referenced by Init(), OnKill(), SetAnchor(), Update(), and UpdateSaveData().
scrolling
bool Window.scrolling private
Definition at line 768 of file Window.cs.
Referenced by Update().
setting
Setting Window.setting
Definition at line 606 of file Window.cs.
Referenced by AddTab(), ApplySkin(), Awake(), BuildTabs(), ClampToScreen(), GetTab(), Layer.GetTextHeader(), Init(), NextTab(), OnKill(), LayerHome.OnSwitchContent(), ProcessCursorChanges(), ProcessResize(), WindowChara.SetChara(), SetContent(), SwitchContent(), Update(), and UpdateSaveData().
shadowEnabled
bool? Window.shadowEnabled private
Definition at line 726 of file Window.cs.
Referenced by ApplySkin().
skinRoot
SkinRootStatic Window.skinRoot
Definition at line 662 of file Window.cs.
textCaption
UIText Window.textCaption
Definition at line 610 of file Window.cs.
Referenced by ApplySkin(), Init(), SetCaption(), and UIBook.Show().
textStats
UIText Window.textStats
Definition at line 612 of file Window.cs.
tipPiovotLeft
RectTransform Window.tipPiovotLeft
Definition at line 650 of file Window.cs.
Referenced by RefreshTipPivotPosition().
tipPivotRight
RectTransform Window.tipPivotRight
Definition at line 652 of file Window.cs.
Referenced by RefreshTipPivotPosition().
tweenAnime
Tween Window.tweenAnime
Definition at line 664 of file Window.cs.
view
UIContentView Window.view
Definition at line 608 of file Window.cs.
Referenced by SetContent< T >(), and SwitchContent().
windowIndex
int Window.windowIndex
Definition at line 697 of file Window.cs.
Referenced by LayerEditPlaylist.OnSwitchContent(), LayerFactions.OnSwitchContent(), LayerLocation.OnSwitchContent(), and LayerPeople.OnSwitchContent().
Property Documentation
AutoAnchor
bool Window.AutoAnchor get
Definition at line 810 of file Window.cs.
    {
        get
        {
            if (!isFloat || (bool)attachedWindow)
            {
                if (saveData != null)
                {
                    return saveData.customAnchor != RectPosition.Auto;
                }
                return false;
            }
            return true;
        }
    }
Referenced by Init(), InitPanel(), OnChangeResolution(), and Update().
Canvas
Canvas Window.Canvas get
Definition at line 838 of file Window.cs.
    {
        get
        {
            if (!_canvas)
            {
                _canvas = GetComponentInParent<Canvas>();
            }
            return _canvas;
        }
    }
Referenced by Awake(), ProcessMovement(), ProcessResize(), and Update().
CaptionCorners
Vector3 [] Window.CaptionCorners get
Definition at line 912 of file Window.cs.
    {
        get
        {
            if (_captionCorners == null || _captionCorners.Length != 4)
            {
                _captionCorners = new Vector3[4];
                for (int i = 0; i < 4; i++)
                {
                    _captionCorners[i] = FrameInnerCorners[i];
                }
                _captionCorners[1].y -= FrameOffsetTop * CorrectedLossyScale.y;
                _captionCorners[2].y -= FrameOffsetTop * CorrectedLossyScale.y;
                _captionCorners[0].y = _captionCorners[1].y - CaptionHeight * CorrectedLossyScale.y;
                _captionCorners[3].y = _captionCorners[2].y - CaptionHeight * CorrectedLossyScale.y;
            }
            return _captionCorners;
        }
    }
CorrectedLossyScale
Vector3 Window.CorrectedLossyScale get
Definition at line 874 of file Window.cs.
    {
        get
        {
            if (_correctedLossyScale == Vector3.zero)
            {
                _correctedLossyScale = Canvas.CorrectLossyScale();
            }
            return _correctedLossyScale;
        }
    }
Referenced by ProcessResize().
CurrentContent
UIContent Window.CurrentContent get
Definition at line 798 of file Window.cs.
    {
        get
        {
            if (CurrentTab == null || !CurrentTab.content)
            {
                return null;
            }
            return CurrentTab.content;
        }
    }
Referenced by GetContent< T >(), SwitchContent(), and SwitchContent< T >().
CurrentTab
Setting.Tab Window.CurrentTab get
Definition at line 786 of file Window.cs.
    {
        get
        {
            if (setting.tabs.Count <= 0)
            {
                return null;
            }
            return setting.tabs[idTab];
        }
    }
Referenced by Layer.GetTextHeader(), NextTab(), LayerHome.OnSwitchContent(), and LayerTextureViewer.OnSwitchContent().
EventTrigger
EventTrigger Window.EventTrigger get
Definition at line 850 of file Window.cs.
    {
        get
        {
            if (!_eventTrigger)
            {
                _eventTrigger = GetComponent<EventTrigger>();
            }
            return _eventTrigger;
        }
    }
Referenced by InitPanel().
FrameInnerCorners
Vector3 [] Window.FrameInnerCorners get
Definition at line 899 of file Window.cs.
    {
        get
        {
            if (_frameInnerCorners == null || _frameInnerCorners.Length != 4)
            {
                _frameInnerCorners = new Vector3[4];
                RectTransform.GetScreenCorners(_frameInnerCorners, Canvas, FrameOffsetL + FrameThickness, FrameOffsetR + FrameThickness, frameOffsetY + FrameThickness);
            }
            return _frameInnerCorners;
        }
    }
Referenced by CursorOverBottomBorder(), CursorOverLeftBorder(), and CursorOverRightBorder().
FrameOuterCorners
Vector3 [] Window.FrameOuterCorners get
Definition at line 886 of file Window.cs.
    {
        get
        {
            if (_frameOuterCorners == null || _frameOuterCorners.Length != 4)
            {
                _frameOuterCorners = new Vector3[4];
                RectTransform.GetScreenCorners(_frameOuterCorners, Canvas, FrameOffsetL, FrameOffsetR, frameOffsetY);
            }
            return _frameOuterCorners;
        }
    }
Referenced by CursorOverBottomBorder(), CursorOverLeftBorder(), CursorOverRightBorder(), and CursorOverWindow().
idWindow
string Window.idWindow get
Definition at line 774 of file Window.cs.
    {
        get
        {
            if (!(layer == null))
            {
                return layer.uid + windowIndex;
            }
            return "nolayer";
        }
    }
Referenced by Init(), OnKill(), and UpdateSaveData().
isStatic
bool Window.isStatic get
Definition at line 932 of file Window.cs.
Referenced by InitPanel(), OnChangeResolution(), and Update().
RectTransform
RectTransform Window.RectTransform get
Definition at line 862 of file Window.cs.
    {
        get
        {
            if (!_rectTransform)
            {
                _rectTransform = base.transform as RectTransform;
            }
            return _rectTransform;
        }
    }
Referenced by AddBottomSpace(), BuildTabs(), ClampToScreen(), LoadHeader(), ProcessResize(), and SetPosition().
Skin
SkinRootStatic Window.Skin get
Definition at line 826 of file Window.cs.
    {
        get
        {
            if (!(skinRoot != null))
            {
                return SkinManager.CurrentSkin;
            }
            return skinRoot;
        }
    }
Referenced by ApplySkin(), and EnableShadow().
The documentation for this class was generated from the following file:
Elin/Plugins.UI/Window.cs