Elin Decompiled Documentation: Los Class Reference
Los Class Reference
Static Public Member Functions
static int MAX (int a, int b)
static int ABS (int a)
static int ZSGN (int a)
static List< Point > ListVisible (Point p1, Point p2, int radius, Action< Point, bool > _onVisit=null)
static Point GetNearestNeighbor (Point p1, Point p2)
static Point GetRushPoint (Point p1, Point dest)
static bool IsVisible (Point p1, Point p2, Action< Point, bool > _onVisit=null)
static bool IsVisible (Card c1, Card c2)
static bool IsVisible (int x1, int x2, int z1, int z2, Action< Point, bool > _onVisit=null, bool returnOnBlock=true)
Static Public Member Functions inherited from EClass
static int rnd (int a)
static int curve (int a, int start, int step, int rate=75)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Static Public Attributes
static Point p = new Point()
static Point originalP = new Point()
static Action< Point, bool > onVisit
Static Public Attributes inherited from EClass
static Core core
Static Private Member Functions
static bool IsBlocked (int x, int z, int sx, int sz)
Additional Inherited Members
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Detailed Description
Definition at line 4 of file Los.cs.
Member Function Documentation
ABS()
static int Los.ABS (int a) inline static
Definition at line 21 of file Los.cs.
    {
        if (a >= 0)
        {
            return a;
        }
        return -a;
    }
GetNearestNeighbor()
static Point Los.GetNearestNeighbor (Point p1, Point p2) inline static
Definition at line 129 of file Los.cs.
    {
        Point dest = null;
        IsVisible(p1, p2, delegate(Point p, bool blocked)
        {
            if (!blocked && dest == null && p2.Distance(p) == 1 && !p.HasChara)
            {
                dest = new Point(p);
            }
        });
        return dest;
    }
References Point.Distance(), Point.HasChara, IsVisible(), and p.
GetRushPoint()
static Point Los.GetRushPoint (Point p1, Point dest) inline static
Definition at line 142 of file Los.cs.
    {
        Point rushPos = null;
        bool valid = true;
        IsVisible(p1, dest, delegate(Point p, bool blocked)
        {
            if (!p.Equals(dest) && !p.Equals(p1))
            {
                if (blocked || p.HasChara || p.IsBlocked)
                {
                    valid = false;
                }
                if (p.Distance(dest) == 1)
                {
                    rushPos = p.Copy();
                }
            }
        });
        if (!valid)
        {
            return null;
        }
        return rushPos;
    }
References Point.Distance(), Point.Equals(), if(), IsVisible(), and p.
Referenced by ActRush.CanPerform(), and ActRush.Perform().
IsBlocked()
static bool Los.IsBlocked (int x, int z, int sx, int sz) inline static private
Definition at line 43 of file Los.cs.
    {
        bool flag = false;
        if (x < 0 || z < 0 || x >= EClass._map.Size || z >= EClass._map.Size)
        {
            flag = true;
        }
        else
        {
            Cell cell = EClass._map.cells[x, z];
            byte[] weights = EClass._map.cells[x, z].weights;
            if ((sz == -1 && weights[0] == 0) || (sz == 1 && weights[2] == 0) || (sx == 1 && weights[1] == 0) || (sx == -1 && weights[3] == 0))
            {
                flag = true;
            }
            if (!flag && sx != 0 && sz != 0)
            {
                if (x + sx < 0 || z + sz < 0 || x + sx >= EClass._map.Size || z + sz >= EClass._map.Size)
                {
                    flag = true;
                }
                else
                {
                    byte[] weights2 = EClass._map.cells[x + sx, z + sz].weights;
                    if ((sz < 0 && weights2[2] == 0) || (sx > 0 && weights2[3] == 0))
                    {
                        flag = true;
                    }
                    if ((sz > 0 && weights2[0] == 0) || (sx < 0 && weights2[1] == 0))
                    {
                        flag = true;
                    }
                }
            }
            if (cell.blockSight)
            {
                flag = true;
            }
        }
        p.Set(x, z);
        if (onVisit != null)
        {
            onVisit(p, flag);
        }
        return flag;
    }
References EClass._map, Cell.blockSight, Map.cells, onVisit, p, Point.Set(), MapBounds.Size, and Algorithms.WeightCell.weights.
IsVisible() [1/3]
static bool Los.IsVisible (Card c1, Card c2) inline static
Definition at line 172 of file Los.cs.
    {
        return IsVisible(c1.pos.x, c2.pos.x, c1.pos.z, c2.pos.z);
    }
References Card.pos, Point.x, and Point.z.
IsVisible() [2/3]
static bool Los.IsVisible (int x1, int x2, int z1, int z2, Action< Point, bool > _onVisit = null, bool returnOnBlock = true) inline static
Definition at line 177 of file Los.cs.
    {
        onVisit = _onVisit;
        p.Set(x1, z1);
        originalP.Set(x1, z1);
        int a = x2 - x1;
        int a2 = z2 - z1;
        int num = ABS(a) << 1;
        int num2 = ABS(a2) << 1;
        int num3 = ZSGN(a);
        int num4 = ZSGN(a2);
        int num5 = x1;
        int num6 = z1;
        if (num >= num2)
        {
            int num7 = num2 - (num >> 1);
            while (true)
            {
                if (num5 == x2)
                {
                    p.Set(num5, num6);
                    if (onVisit != null)
                    {
                        onVisit(p, arg2: false);
                    }
                    return true;
                }
                if (IsBlocked(num5, num6, num3, (num7 >= 0) ? num4 : 0) && returnOnBlock)
                {
                    break;
                }
                if (num7 >= 0)
                {
                    num6 += num4;
                    num7 -= num;
                }
                num5 += num3;
                num7 += num2;
            }
            return false;
        }
        if (num2 >= num)
        {
            int num8 = num - (num2 >> 1);
            while (true)
            {
                if (num6 == z2)
                {
                    p.Set(num5, num6);
                    if (onVisit != null)
                    {
                        onVisit(p, arg2: false);
                    }
                    return true;
                }
                if (IsBlocked(num5, num6, (num8 >= 0) ? num3 : 0, num4) && returnOnBlock)
                {
                    break;
                }
                if (num8 >= 0)
                {
                    num5 += num3;
                    num8 -= num2;
                }
                num6 += num4;
                num8 += num;
            }
            return false;
        }
        return false;
    }
References Point.Set().
IsVisible() [3/3]
static bool Los.IsVisible (Point p1, Point p2, Action< Point, bool > _onVisit = null) inline static
Definition at line 167 of file Los.cs.
    {
        return IsVisible(p1.x, p2.x, p1.z, p2.z, _onVisit);
    }
References Point.x, and Point.z.
Referenced by Act.CanPerform(), Chara.CanSeeLos(), GetNearestNeighbor(), Point.GetRandomPoint(), Map.GetRandomPoint(), Point.GetRandomPointInRadius(), GetRushPoint(), Point.ListCharasInRadius(), Trait.ListPoints(), Map.ListPointsInArc(), Map.ListPointsInCircle(), ListVisible(), ActRush.OnMarkMapHighlights(), AI_Idle.Run(), and GameUpdater.Update().
ListVisible()
static List< Point > Los.ListVisible (Point p1, Point p2, int radius, Action< Point, bool > _onVisit = null) inline static
Definition at line 90 of file Los.cs.
    {
        List<Point> list = new List<Point>();
        List<Point> vecs = new List<Point>();
        Point lastPoint = p1.Copy();
        IsVisible(p1.x, p2.x, p1.z, p2.z, delegate(Point p, bool blocked)
        {
            Point point3 = new Point(p.x - lastPoint.x, p.z - lastPoint.z);
            if (point3.x != 0 || point3.z != 0)
            {
                vecs.Add(point3);
            }
            lastPoint.Set(p);
        }, returnOnBlock: false);
        if (vecs.Count == 0)
        {
            return list;
        }
        Point point = p1.Copy();
        for (int i = 0; i < radius; i++)
        {
            Point point2 = vecs[i % vecs.Count];
            point.x += point2.x;
            point.z += point2.z;
        }
        IsVisible(p1.x, point.x, p1.z, point.z, delegate(Point p, bool blocked)
        {
            if (!blocked)
            {
                list.Add(p.Copy());
            }
            if (_onVisit != null)
            {
                _onVisit(p, blocked);
            }
        });
        return list;
    }
References Point.Copy(), IsVisible(), p, Point.Set(), Point.x, and Point.z.
Referenced by Map.ListPointsInLine().
MAX()
static int Los.MAX (int a, int b) inline static
Definition at line 12 of file Los.cs.
    {
        if (a <= b)
        {
            return b;
        }
        return a;
    }
ZSGN()
static int Los.ZSGN (int a) inline static
Definition at line 30 of file Los.cs.
    {
        if (a >= 0)
        {
            if (a <= 0)
            {
                return 0;
            }
            return 1;
        }
        return -1;
    }
Member Data Documentation
onVisit
Action<Point, bool> Los.onVisit static
Definition at line 10 of file Los.cs.
Referenced by IsBlocked().
originalP
Point Los.originalP = new Point() static
Definition at line 8 of file Los.cs.
p
Point Los.p = new Point() static
Definition at line 6 of file Los.cs.
Referenced by GetNearestNeighbor(), GetRushPoint(), IsBlocked(), and ListVisible().
The documentation for this class was generated from the following file:
Elin/Los.cs