Elin Decompiled Documentation: InspectGroupThing Class Reference
InspectGroupThing Class Reference
Public Member Functions
override void OnSetActions ()
Public Member Functions inherited from InspectGroup< Thing >
sealed override void SetActions ()
virtual void SetActions ()
sealed override void SetActions ()
virtual void OnSetActions ()
virtual void OnSetActions ()
InspectGroup.Item Add (string text, string idSprite, Action action, bool sound=false, int priority=0, bool auto=false)
InspectGroup.Item Add (string text, string idSprite, Action< T > action, bool sound=false, int priority=0, bool auto=false)
Item Add (string text, string idSprite, Action action, bool sound=false, int priority=0, bool auto=false)
Item Add (string text, string idSprite, Action< T > action, bool sound=false, int priority=0, bool auto=false)
bool CanInspect ()
virtual bool Contains (IInspect t)
string GetName ()
Properties
override string MultiName [get]
Properties inherited from InspectGroup< Thing >
new T FirstTarget [get]
IInspect FirstTarget [get]
bool Solo [get]
virtual string MultiName [get]
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Additional Inherited Members
Static Public Member Functions inherited from InspectGroup< Thing >
static InspectGroup Create (IInspect t)
Static Public Member Functions inherited from EClass
static int rnd (int a)
static int curve (int a, int start, int step, int rate=75)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Public Attributes inherited from InspectGroup< Thing >
Type type
List< Item > actions
List< IInspect > targets
Static Public Attributes inherited from EClass
static Core core
Detailed Description
Definition at line 3 of file InspectGroupThing.cs.
Member Function Documentation
OnSetActions()
override void InspectGroupThing.OnSetActions () inline virtual
Reimplemented from InspectGroup< Thing >.
Definition at line 7 of file InspectGroupThing.cs.
    {
        Thing first = base.FirstTarget;
        Add("objInfo", "", (Action)delegate
        {
            EClass.ui.AddLayer<LayerInfo>().Set(first);
        }, sound: false, 0, auto: false);
        if (first.trait is TraitQuestBoard)
        {
            Add("quest", "", (Action)delegate
            {
                EClass.ui.AddLayer<LayerQuestBoard>();
            }, sound: false, 20, auto: true);
            Add("hire", "", (Action)delegate
            {
                EClass.ui.AddLayer<LayerHire>();
            }, sound: false, 20, auto: true);
        }
        if (first.trait is TraitGacha)
        {
            Add("gacha", "", (Action)delegate
            {
                EClass.ui.AddLayer<LayerGacha>();
            }, sound: false, 10, auto: true);
        }
        if (first.trait.IsFactory)
        {
            Add("craft", "icon_Inspect", (Action)delegate
            {
                EClass.ui.AddLayer<LayerCraft>().SetFactory(first);
            }, sound: false, 100, auto: true);
        }
        if (first.IsInstalled)
        {
            Add("uninstall", "", (Action)delegate
            {
                first.SetPlaceState(PlaceState.roaming);
            }, sound: false, 0, auto: false);
        }
        Add("install", "", (Action)delegate
        {
            ActionMode.Inspect.Activate(first);
        }, sound: false, 0, auto: false);
        if (first.isDeconstructing)
        {
            Add("cancel".lang() + "\n(" + "Deconstruct".lang() + ")", "", delegate(Thing t)
            {
                t.SetDeconstruct(deconstruct: false);
            }, sound: true);
        }
        else
        {
            Add("Deconstruct", "", delegate(Thing t)
            {
                t.SetDeconstruct(deconstruct: true);
            }, sound: true);
        }
        AM_Picker.Result r = ActionMode.Picker.TestThing(first);
        if (r.IsValid)
        {
            Add("Copy", "", (Action)delegate
            {
                ActionMode.Picker.Select(r);
            }, sound: false, 0, auto: false);
        }
    }
References AM_MoveInstalled.Activate(), InspectGroup< Thing >.Add(), ActionMode.Inspect, Card.isDeconstructing, Trait.IsFactory, Card.IsInstalled, AM_Picker.Result.IsValid, ActionMode.Picker, AM_Picker.Select(), Card.SetDeconstruct(), Card.SetPlaceState(), AM_Picker.TestThing(), Card.trait, and EClass.ui.
Property Documentation
MultiName
override string InspectGroupThing.MultiName get
Definition at line 5 of file InspectGroupThing.cs.
The documentation for this class was generated from the following file:
Elin/InspectGroupThing.cs