Elin Decompiled Documentation: TraitAltar Class Reference
TraitAltar Class Reference
Public Member Functions
override void OnCreate (int lv)
override void OnImportMap ()
void SetDeity (string id)
override void SetName (ref string s)
override void TrySetAct (ActPlan p)
override bool CanOffer (Card c)
void OnOffer (Chara c, Thing t)
void _OnOffer (Chara c, Thing t, int takeoverMod=0)
void TakeOver ()
Public Member Functions inherited from Trait
string GetParam (int i, string def=null)
int GetParamInt (int i, int def)
virtual bool Contains (RecipeSource r)
virtual int GetValue ()
virtual bool CanStackTo (Thing to)
virtual string GetHoverText ()
virtual Action GetHealAction (Chara c)
virtual bool CanBlend (Thing t)
virtual void OnBlend (Thing t, Chara c)
virtual int GetActDuration (Chara c)
virtual SourceElement.Row GetRefElement ()
virtual Sprite GetRefSprite ()
virtual void OnRenderExtra (RenderParam p)
virtual Emo2 GetHeldEmo (Chara c)
virtual void SetOwner (Card _owner)
virtual bool IdleUse (Chara c, int dist)
virtual void OnSetOwner ()
virtual void OnImportMap ()
virtual void SetParams (params string[] s)
virtual void OnCrafted (Recipe recipe, List< Thing > ings)
virtual void OnCreate (int lv)
virtual void OnEquip (Chara c, bool onSetOwner)
virtual void OnUnequip (Chara c)
virtual void OnChangePlaceState (PlaceState state)
virtual void OnAddedToZone ()
virtual void OnRemovedFromZone ()
virtual void OnSimulateHour (VirtualDate date)
virtual string GetName ()
virtual void SetName (ref string s)
virtual void OnRenderTile (Point point, HitResult result, int dir)
virtual int CompareTo (Card b)
virtual bool CanBuiltAt (Point p)
virtual void Update ()
Point GetPoint ()
Point GetRandomPoint (Func< Point, bool > func=null, Chara accessChara=null)
virtual List< Point > ListPoints (Point center=null, bool onlyPassable=true)
virtual Recipe GetRecipe ()
virtual Recipe GetBuildModeRecipe ()
virtual bool CanCook (Card c)
void CookProgress ()
virtual bool CanOffer (Card tg)
void OfferProcess (Chara cc)
void Offer (Chara cc)
virtual bool TryProgress (AIProgress p)
virtual LockOpenState TryOpenLock (Chara cc, bool msgFail=true)
virtual void WriteNote (UINote n, bool identified)
int GetSortVal (UIList.SortMode m)
virtual HotItem GetHotItem ()
virtual bool CanRead (Chara c)
virtual void OnRead (Chara c)
virtual bool CanEat (Chara c)
virtual void OnEat (Chara c)
virtual bool CanDrink (Chara c)
virtual void OnDrink (Chara c)
virtual void OnThrowGround (Chara c, Point p)
virtual bool CanUse (Chara c)
virtual bool CanUse (Chara c, Card tg)
virtual bool CanUse (Chara c, Point p)
virtual bool OnUse (Chara c)
virtual bool OnUse (Chara c, Card tg)
virtual bool OnUse (Chara c, Point p)
virtual void TrySetAct (ActPlan p)
virtual void TrySetHeldAct (ActPlan p)
virtual void OnHeld ()
virtual void OnTickHeld ()
virtual void OnSetCurrentItem ()
virtual void OnUnsetCurrentItem ()
virtual bool OnChildDecay (Card c, bool firstDecay)
virtual bool CanChildDecay (Card c)
virtual void OnSetCardGrid (ButtonGrid b)
virtual void OnStepped (Chara c)
virtual void OnSteppedOut (Chara c)
virtual void OnOpenDoor (Chara c)
void Install (bool byPlayer)
void Uninstall ()
virtual void OnInstall (bool byPlayer)
virtual void OnUninstall ()
virtual void TryToggle ()
virtual void Toggle (bool on, bool silent=false)
virtual void PlayToggleEffect (bool silent)
virtual void OnToggle ()
virtual void TrySetToggleAct (ActPlan p)
bool IsFuelEnough (int num=1, List< Thing > excludes=null, bool tryRefuel=true)
bool IsFuel (string s)
bool IsFuel (Thing t)
int GetFuelValue (Thing t)
int GetFuelValue (string id)
void Refuel (Thing t)
void TryRefuel (int dest, List< Thing > excludes)
virtual void OnEnterScreen ()
virtual void RefreshRenderer ()
virtual void SetMainText (UIText t, bool hotitem)
virtual bool CanCopy (Thing t)
string GetTextRestock (string lang, bool pet)
Emo2 GetRestockedIcon ()
void OnBarter (bool reroll=false)
Thing CreateStock ()
Properties
override bool CanStack [get]
override bool IsAltar [get]
bool IsBranchAltar [get]
override bool CanOnlyCarry [get]
virtual string idDeity [get]
virtual Religion Deity [get]
string StrDeity [get]
bool IsEyth [get]
Properties inherited from Trait
string[] Params [get]
virtual byte WeightMod [get]
virtual int IdSkin [get]
virtual string Name [get]
virtual TileType tileType [get]
virtual RefCardName RefCardName [get]
virtual bool IsBlockPath [get]
virtual bool IsBlockSight [get]
virtual bool IsDoor [get]
virtual bool IsOpenSight [get]
virtual bool IsOpenPath [get]
virtual bool IsFloating [get]
virtual bool IsNoShop [get]
virtual bool IsGround [get]
virtual bool IsOnlyUsableByPc [get]
virtual bool InvertHeldSprite [get]
virtual bool IsChangeFloorHeight [get]
virtual bool ShouldRefreshTile [get]
virtual bool ShouldTryRefreshRoom [get]
virtual int InstallBottomPriority [get]
virtual bool CanHarvest [get]
virtual int radius [get]
virtual TraitRadiusType radiusType [get]
virtual bool CanUseRoomRadius [get]
virtual int GuidePriotiy [get]
virtual int Electricity [get]
virtual bool IgnoreLastStackHeight [get]
virtual int Decay [get]
virtual int DecaySpeed [get]
virtual int DecaySpeedChild [get]
virtual bool IsFridge [get]
virtual int DefaultStock [get]
virtual bool HoldAsDefaultInteraction [get]
virtual int CraftNum [get]
virtual bool ShowOrbit [get]
virtual bool HaveUpdate [get]
virtual bool IsSpot [get]
virtual bool IsFactory [get]
virtual bool CanAutofire [get]
virtual bool CanName [get]
virtual bool CanPutAway [get]
virtual bool CanChangeHeight [get]
virtual bool CanStack [get]
virtual bool CanCopyInBlueprint [get]
virtual bool CanBeAttacked [get]
virtual bool CanBeTeleported [get]
virtual bool CanExtendBuild [get]
virtual string langNote [get]
virtual string IDInvStyle [get]
virtual string IDActorEx [get]
virtual bool MaskOnBuild [get]
virtual bool ShowContextOnPick [get]
virtual bool IsThrowMainAction [get]
virtual bool LevelAsQuality [get]
virtual bool UseDummyTile [get]
virtual bool RequireFullStackCheck [get]
virtual bool DisableAutoCombat [get]
virtual InvGridSize InvGridSize [get]
virtual bool IsContainer [get]
virtual bool CanUseContent [get]
virtual bool CanSearchContent [get]
virtual bool CanOpenContainer [get]
virtual bool IsSpecialContainer [get]
virtual ContainerType ContainerType [get]
virtual ThrowType ThrowType [get]
virtual EffectDead EffectDead [get]
virtual bool IsHomeItem [get]
virtual bool IsAltar [get]
virtual bool IsRestSpot [get]
virtual bool CanBeMasked [get]
virtual bool IsLocalAct [get]
virtual bool IsBlendBase [get]
virtual bool CanBeOnlyBuiltInHome [get]
virtual bool CanBuildInTown [get]
virtual bool CanBeHeld [get]
virtual bool CanBeStolen [get]
virtual bool CanOnlyCarry [get]
virtual bool CanBeDestroyed [get]
virtual bool CanBeSmashedToDeath [get]
virtual bool CanBeHallucinated [get]
virtual bool CanBeDropped [get]
virtual string ReqHarvest [get]
virtual bool CanBeDisassembled [get]
virtual bool CanBeShipped [get]
virtual bool HasCharges [get]
virtual bool ShowCharges [get]
virtual bool ShowChildrenNumber [get]
virtual bool ShowAsTool [get]
virtual bool CanBeHeldAsFurniture [get]
virtual bool HideInAdv [get]
virtual bool NoHeldDir [get]
virtual bool AlwaysHideOnLowWall [get]
bool ExistsOnMap [get]
virtual bool RenderExtra [get]
virtual float DropChance [get]
virtual string IdNoRestock [get]
virtual int IdleUseChance [get]
virtual string RecipeCat [get]
virtual bool IsTool [get]
virtual string LangUse [get]
virtual bool IgnoreOnSteppedWhenMoving [get]
virtual bool IsOn [get]
virtual bool IsAnimeOn [get]
bool IsToggle [get]
virtual bool AutoToggle [get]
bool IsLighting [get]
virtual bool IsLightOn [get]
virtual bool IsNightOnlyLight [get]
virtual TileMode tileMode [get]
virtual bool UseAltTiles [get]
virtual bool UseLowblock [get]
virtual bool UseExtra [get]
virtual bool UseLightColor [get]
virtual ? Color ColorExtra [get]
virtual int MaxFuel [get]
virtual int FuelCost [get]
virtual bool ShowFuelWindow [get]
bool IsRequireFuel [get]
string IdToggleExtra [get]
virtual ToggleType ToggleType [get]
virtual string IdSoundToggleOn [get]
virtual string IdSoundToggleOff [get]
virtual int ShopLv [get]
virtual CopyShopType CopyShop [get]
virtual int NumCopyItem [get]
virtual ShopType ShopType [get]
virtual CurrencyType CurrencyType [get]
virtual PriceType PriceType [get]
virtual bool AllowSell [get]
virtual int CostRerollShop [get]
virtual bool AllowCriminal [get]
virtual int RestockDay [get]
virtual SlaverType SlaverType [get]
virtual string LangBarter [get]
virtual bool RemoveGlobalOnBanish [get]
string TextNextRestock [get]
string TextNextRestockPet [get]
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Additional Inherited Members
Public Types inherited from Trait
enum TileMode {
Default , Door , Illumination , DefaultNoAnime ,
SignalAnime , FakeBlock
}
enum CopyShopType { None , Item , Spellbook }
Static Public Member Functions inherited from EClass
static int rndSeed (int a, int seed)
static int rnd (long a)
static int rnd (int a)
static int curve (int a, int start, int step, int rate=75)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Public Attributes inherited from Trait
Card owner
Static Public Attributes inherited from Trait
static TraitSelfFactory SelfFactory = new TraitSelfFactory()
Static Public Attributes inherited from EClass
static Core core
Static Protected Attributes inherited from Trait
static List< Point > listRadiusPoints = new List<Point>()
Detailed Description
Definition at line 3 of file TraitAltar.cs.
Member Function Documentation
_OnOffer()
void TraitAltar._OnOffer (Chara c, Thing t, int takeoverMod = 0) inline
Definition at line 202 of file TraitAltar.cs.
    {
        bool @bool = t.GetBool(115);
        int offeringValue = Deity.GetOfferingValue(t, t.Num);
        offeringValue = offeringValue * (c.HasElement(1228) ? 130 : 100) / 100;
        if (takeoverMod == 0)
        {
            if (offeringValue >= 200)
            {
                Msg.Say("god_offer1", t);
                EClass.pc.faith.Talk("offer");
            }
            else if (offeringValue >= 100)
            {
                Msg.Say("god_offer2", t);
            }
            else if (offeringValue >= 50)
            {
                Msg.Say("god_offer3", t);
            }
            else
            {
                Msg.Say("god_offer4", t);
            }
        }
        else
        {
            Msg.Say("god_offer1", t);
            offeringValue += Deity.GetOfferingValue(t, 1) * takeoverMod;
        }
        int num = Mathf.Max(c.Evalue(306), 1);
        Element orCreateElement = c.elements.GetOrCreateElement(85);
        int value = orCreateElement.Value;
        c.elements.ModExp(orCreateElement.id, offeringValue * 2 / 3);
        int num2 = 4;
        if (orCreateElement.vBase >= num)
        {
            c.elements.SetBase(orCreateElement.id, num);
        }
        else
        {
            num2 = Mathf.Clamp(orCreateElement.vBase * 100 / num / 25, 0, 3);
        }
        if (num2 == 4 || orCreateElement.Value != value)
        {
            Msg.Say("piety" + num2, c, c.faith.TextGodGender);
        }
        Debug.Log(offeringValue + "/" + orCreateElement.Value + "/" + orCreateElement.vExp);
        if (orCreateElement.Value > num * 8 / 10)
        {
            c.elements.ModExp(306, offeringValue / 5);
        }
        c.RefreshFaithElement();
        if (@bool)
        {
            EClass.player.ModKarma(-1);
        }
    }
References Debug, Deity, Card.elements, Card.Evalue(), Chara.faith, BaseCard.GetBool(), Religion.GetOfferingValue(), ElementContainer.GetOrCreateElement(), Card.HasElement(), Element.id, ElementContainer.ModExp(), Player.ModKarma(), Card.Num, EClass.pc, EClass.player, Chara.RefreshFaithElement(), Msg.Say(), ElementContainer.SetBase(), Religion.Talk(), Religion.TextGodGender, Element.Value, Element.vBase, and Element.vExp.
Referenced by OnOffer().
CanOffer()
override bool TraitAltar.CanOffer (Card c) inline virtual
Reimplemented from Trait.
Definition at line 76 of file TraitAltar.cs.
    {
        if (c != null && c.HasTag(CTAG.godArtifact) && c.c_idDeity == Deity.id)
        {
            return true;
        }
        if (base.CanOffer(c) && (EClass.pc.faith.GetOfferingValue(c as Thing) > 0 || c.id == "water") && !c.isCopy)
        {
            return !c.HasElement(764);
        }
        return false;
    }
References Card.c_idDeity, Deity, Chara.faith, Religion.GetOfferingValue(), Card.HasElement(), Card.HasTag(), Card.id, Religion.id, Card.isCopy, and EClass.pc.
Referenced by OnOffer(), and InvOwnerOffering.ShouldShowGuide().
OnCreate()
override void TraitAltar.OnCreate (int lv) inline virtual
Reimplemented from Trait.
Definition at line 21 of file TraitAltar.cs.
    {
        SetDeity(GetParam(1) ?? EClass.game.religions.GetRandomReligion().id);
    }
References EClass.game, Trait.GetParam(), ReligionManager.GetRandomReligion(), Religion.id, Game.religions, and SetDeity().
OnImportMap()
override void TraitAltar.OnImportMap () inline virtual
Reimplemented from Trait.
Definition at line 26 of file TraitAltar.cs.
    {
        if (owner.c_idDeity.IsEmpty() || GetParam(1) != null)
        {
            SetDeity(GetParam(1) ?? EClass.game.religions.GetRandomReligion().id);
        }
    }
References Card.c_idDeity, EClass.game, Trait.GetParam(), ReligionManager.GetRandomReligion(), Religion.id, Trait.owner, Game.religions, and SetDeity().
OnOffer()
void TraitAltar.OnOffer (Chara c, Thing t) inline
Definition at line 89 of file TraitAltar.cs.
    {
        if (t == null)
        {
            return;
        }
        if (t.id == "water")
        {
            if (Deity != EClass.pc.faith)
            {
                if (t.blessedState == BlessedState.Cursed)
                {
                    Msg.SayNothingHappen();
                    return;
                }
                Msg.Say("waterCurse", t);
                EClass.pc.PlayEffect("curse");
                EClass.pc.PlaySound("curse3");
                t.SetBlessedState(BlessedState.Cursed);
            }
            else if (t.blessedState == BlessedState.Blessed)
            {
                Msg.SayNothingHappen();
            }
            else
            {
                Msg.Say("waterBless", t);
                EClass.pc.PlayEffect("revive");
                EClass.pc.PlaySound("revive");
                t.SetBlessedState(BlessedState.Blessed);
            }
            return;
        }
        if (!IsBranchAltar && EClass.pc.IsEyth)
        {
            EClass.pc.Say("god_offerEyth", owner, t);
            return;
        }
        EClass.pc.Say("god_offer", owner, t, Deity.Name);
        if (!CanOffer(t))
        {
            EClass.pc.Say("nothingHappens", owner, t);
            return;
        }
        Effect.Get("debuff").Play(owner.pos);
        EClass.pc.PlaySound("offering");
        if (IsBranchAltar)
        {
            Msg.Say("nothingHappens");
        }
        else if (IsEyth)
        {
            if (EClass.pc.IsEyth)
            {
                Msg.Say("nothingHappens");
            }
            else
            {
                Msg.Say("takeover_empty", EClass.pc.faith.Name);
                TakeOver();
                _OnOffer(c, t, 2);
            }
        }
        else
        {
            if (t.HasTag(CTAG.godArtifact) && t.c_idDeity == Deity.id)
            {
                _ = t.encLV;
                t.Destroy();
                Thing thing = Religion.Reforge(t.id);
                thing.SetEncLv(t.encLV);
                thing.SetBlessedState(t.blessedState);
                if (t.IsIdentified)
                {
                    thing.Identify(show: true, IDTSource.SuperiorIdentify);
                }
                return;
            }
            if (EClass.pc.IsEyth)
            {
                Msg.Say("nothingHappens");
                return;
            }
            if (Deity != EClass.pc.faith)
            {
                bool flag = EClass.rnd(EClass.pc.faith.GetOfferingValue(t, t.Num)) > EClass.rnd(200);
                if (GetParam(1) != null)
                {
                    Msg.Say("nothingHappens");
                    return;
                }
                Msg.Say("takeover_versus", EClass.pc.faith.Name, Deity.Name);
                if (flag)
                {
                    Msg.Say("takeover_success", EClass.pc.faith.TextGodGender);
                    Msg.Say("takeover_success2", EClass.pc.faith.Name);
                    TakeOver();
                    _OnOffer(c, t, 5);
                }
                else
                {
                    Msg.Say("takeover_fail", Deity.Name);
                    Deity.PunishTakeOver(EClass.pc);
                }
            }
            else
            {
                _OnOffer(c, t);
            }
        }
        t.Destroy();
    }
References _OnOffer(), Card.blessedState, Card.c_idDeity, CanOffer(), Deity, Card.Destroy(), Card.encLV, Chara.faith, Effect.Get(), Religion.GetOfferingValue(), Trait.GetParam(), Card.HasTag(), Card.id, Religion.id, Thing.Identify(), IsBranchAltar, Chara.IsEyth, IsEyth, Card.IsIdentified, Religion.Name, Card.Num, Trait.owner, EClass.pc, Effect.Play(), Card.PlayEffect(), Card.PlaySound(), Card.pos, Religion.PunishTakeOver(), Religion.Reforge(), EClass.rnd(), Msg.Say(), Card.Say(), Msg.SayNothingHappen(), Card.SetBlessedState(), Card.SetEncLv(), TakeOver(), and Religion.TextGodGender.
Referenced by InvOwnerOffering._OnProcess().
SetDeity()
void TraitAltar.SetDeity (string id) inline
Definition at line 34 of file TraitAltar.cs.
    {
        owner.c_idDeity = id;
        if (owner.id == "altar")
        {
            owner.ChangeMaterial(Deity.source.idMaterial);
        }
    }
References Card.ChangeMaterial(), Deity, Card.id, Trait.owner, and Religion.source.
Referenced by OnCreate(), OnImportMap(), and TakeOver().
SetName()
override void TraitAltar.SetName (ref string s) inline virtual
Reimplemented from Trait.
Definition at line 43 of file TraitAltar.cs.
    {
        if (!owner.c_idDeity.IsEmpty())
        {
            s = "_of".lang(StrDeity, s);
        }
    }
References Card.c_idDeity, Trait.owner, and StrDeity.
TakeOver()
void TraitAltar.TakeOver () inline
Definition at line 261 of file TraitAltar.cs.
    {
        SetDeity(EClass.pc.faith.id);
        EClass.pc.faith.Talk("takeover");
        EClass.pc.PlayEffect("revive");
        owner.PlayEffect("aura_heaven");
    }
References Chara.faith, Religion.id, Trait.owner, EClass.pc, Card.PlayEffect(), SetDeity(), and Religion.Talk().
Referenced by OnOffer().
TrySetAct()
override void TraitAltar.TrySetAct (ActPlan p) inline virtual
Reimplemented from Trait.
Definition at line 51 of file TraitAltar.cs.
    {
        if (IsBranchAltar)
        {
            return;
        }
        if ((IsBranchAltar && EClass.Branch.rank != 0) || !IsBranchAltar)
        {
            p.TrySetAct("actOffer", delegate
            {
                LayerDragGrid.CreateOffering(this);
                return false;
            }, owner);
        }
        if (!IsBranchAltar && Deity != EClass.pc.faith && Deity.CanJoin)
        {
            p.TrySetAct("actWorship", delegate
            {
                LayerDrama.currentReligion = Deity;
                LayerDrama.Activate("_adv", "god", "worship");
                return false;
            }, owner);
        }
    }
References LayerDrama.Activate(), EClass.Branch, Religion.CanJoin, LayerDragGrid.CreateOffering(), Deity, Chara.faith, IsBranchAltar, Trait.owner, EClass.pc, FactionBranch.rank, and ActPlan.TrySetAct().
Property Documentation
CanOnlyCarry
override bool TraitAltar.CanOnlyCarry get
Definition at line 11 of file TraitAltar.cs.
CanStack
override bool TraitAltar.CanStack get
Definition at line 5 of file TraitAltar.cs.
Deity
virtual Religion TraitAltar.Deity get
Definition at line 15 of file TraitAltar.cs.
Referenced by _OnOffer(), CanOffer(), OnOffer(), SetDeity(), and TrySetAct().
idDeity
virtual string TraitAltar.idDeity get
Definition at line 13 of file TraitAltar.cs.
Referenced by AI_Pray.GetAltar(), and BranchMap.Refresh().
IsAltar
override bool TraitAltar.IsAltar get
Definition at line 7 of file TraitAltar.cs.
IsBranchAltar
bool TraitAltar.IsBranchAltar get
Definition at line 9 of file TraitAltar.cs.
Referenced by OnOffer(), and TrySetAct().
IsEyth
bool TraitAltar.IsEyth get
Definition at line 19 of file TraitAltar.cs.
Referenced by OnOffer().
StrDeity
string TraitAltar.StrDeity get
Definition at line 17 of file TraitAltar.cs.
Referenced by SetName().
The documentation for this class was generated from the following file:
Elin/TraitAltar.cs