Elin Decompiled Documentation: WidgetTracker Class Reference
WidgetTracker Class Reference
Classes
class Extra
Public Member Functions
override object CreateExtra ()
override void OnActivate ()
void Refresh ()
override void OnSetContextMenu (UIContextMenu m)
Public Member Functions inherited from Widget
void Test ()
bool IsInRightMode ()
void Activate ()
virtual void OnActivate ()
virtual object CreateExtra ()
void Deactivate ()
virtual void OnDeactivate ()
void Close ()
void Reactivate ()
virtual void OnManagerActivate ()
virtual void OnManagerDeactivate ()
void SetAnchor (RectPosition p)
void SetPivot (RectPosition p)
virtual void OnChangePivot ()
void UpdateConfig ()
virtual void OnUpdateConfig ()
void ClampToScreen ()
virtual void OnChangeResolution ()
void OnChangePosition ()
virtual void OnChangeActionMode ()
virtual void OnFlip ()
bool IsAlignTop ()
Layer AddLayer (Layer l, Transform trans)
void RefreshTipPivotPosition ()
SkinSet GetSkin ()
SkinConfig GetSkinConfig ()
void SetSkin (int id, int v=0)
void TestSkin ()
virtual void ApplySkin ()
virtual void OnApplySkin ()
void InstantiateDeco (SkinDeco deco)
void AddDeco (SkinDeco deco)
void RemoveDeco (SkinDeco deco)
virtual bool CanShowContextMenu ()
void ShowContextMenu ()
void SetBaseContextMenu (UIContextMenu m)
virtual void OnSetContextMenu (UIContextMenu m)
void SetGridContextMenu (UIContextMenu m)
void SoundActivate ()
Static Public Member Functions
static void Toggle (Element e)
Static Public Member Functions inherited from EMono
static int rnd (int a)
Public Attributes
UIText text
Public Attributes inherited from Widget
Image imageBG
SoundData soundActivate
UIDragPanel dragPanel
RectTransform tipPivotLeft
RectTransform tipPivotRight
Static Public Attributes
static WidgetTracker Instance
Static Public Attributes inherited from EMono
static Core core
Properties
WidgetTracker.Extra extra [get]
Properties inherited from Widget
string ID [get]
Widget.Config config [get]
SkinRoot skinRoot [get]
bool IsSealed [get]
virtual bool ShowStyleMenu [get]
virtual bool AlwaysTop [get]
virtual bool IsStaticPosition [get]
virtual bool AlwaysBottom [get]
virtual Type SetSiblingAfter [get]
virtual bool ShowInBuildMode [get]
virtual bool RightClickToClose [get]
virtual bool AllowRightClickToClose [get]
Properties inherited from EMono
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SoundManager Sound [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static CoreDebug debug [get]
Private Member Functions
void OnEnable ()
void OnDisable ()
Private Attributes
FastString sb = new FastString(32)
FastString lastSb = new FastString(32)
Additional Inherited Members
Public Types inherited from Widget
enum WidgetType { Default , ZoomMenu }
enum State { Active , Inactive }
Protected Member Functions inherited from Widget
void ClampToScreenEnsured (Component c, Vector2 anchoredPos)
void ClampToScreen (RectTransform rect, float margin=10f)
Protected Attributes inherited from Widget
bool flip
Detailed Description
Definition at line 5 of file WidgetTracker.cs.
Member Function Documentation
CreateExtra()
override object WidgetTracker.CreateExtra () inline virtual
Reimplemented from Widget.
Definition at line 7 of file WidgetTracker.cs.
    {
        return new WidgetTracker.Extra();
    }
OnActivate()
override void WidgetTracker.OnActivate () inline virtual
Reimplemented from Widget.
Definition at line 51 of file WidgetTracker.cs.
    {
        WidgetTracker.Instance = this;
        this.Refresh();
    }
References Refresh().
OnDisable()
void WidgetTracker.OnDisable () inline private
Definition at line 62 of file WidgetTracker.cs.
    {
        base.CancelInvoke();
    }
OnEnable()
void WidgetTracker.OnEnable () inline private
Definition at line 57 of file WidgetTracker.cs.
    {
        base.InvokeRepeating("Refresh", 0.5f, 0.5f);
    }
OnSetContextMenu()
override void WidgetTracker.OnSetContextMenu (UIContextMenu m) inline virtual
Reimplemented from Widget.
Definition at line 113 of file WidgetTracker.cs.
    {
        m.AddToggle("showPotential", this.extra.potential, delegate(bool a)
        {
            this.extra.potential = a;
            this.Refresh();
        });
        m.AddButton("clear", delegate()
        {
            EMono.player.trackedElements.Clear();
            EMono.ui.widgets.DeactivateWidget(this);
        }, true);
        base.SetBaseContextMenu(m);
    }
References extra, EMono.player, Refresh(), Player.trackedElements, and EMono.ui.
Refresh()
void WidgetTracker.Refresh () inline
Definition at line 67 of file WidgetTracker.cs.
    {
        this.sb.Clear();
        HashSet<int> trackedElements = EMono.player.trackedElements;
        if (trackedElements.Count == 0)
        {
            this.sb.Append("none".lang());
        }
        else
        {
            int num = trackedElements.Last<int>();
            foreach (int num2 in trackedElements)
            {
                Element element = EMono.pc.elements.GetElement(num2);
                if (element != null)
                {
                    string text = element.Name + "  " + element.Value.ToString();
                    if (element.ShowXP)
                    {
                        text = text + "." + (element.vExp / 10).ToString("D2");
                    }
                    if (this.extra.potential)
                    {
                        text += (" (" + element.Potential.ToString() + ")").TagSize(13);
                    }
                    if (num2 != num)
                    {
                        text += "\n";
                    }
                    this.sb.Append(text);
                }
            }
        }
        if (this.sb.IsEmpty())
        {
            this.sb.Append("none".lang());
        }
        if (this.sb.Equals(this.lastSb))
        {
            return;
        }
        this.text.text = this.sb.ToString();
        this.lastSb.Set(this.sb);
        this.RebuildLayout(false);
    }
References Card.elements, extra, ElementContainer.GetElement(), lastSb, EMono.pc, EMono.player, Element.Potential, sb, Element.ShowXP, text, Player.trackedElements, and Element.Value.
Referenced by OnActivate(), OnSetContextMenu(), and Toggle().
Toggle()
static void WidgetTracker.Toggle (Element e) inline static
Definition at line 20 of file WidgetTracker.cs.
    {
        if (e.owner != EMono.pc.elements)
        {
            SE.Beep();
            return;
        }
        HashSet<int> trackedElements = EMono.player.trackedElements;
        if (trackedElements.Contains(e.id))
        {
            trackedElements.Remove(e.id);
            if (trackedElements.Count == 0 && WidgetTracker.Instance)
            {
                WidgetTracker.Instance.Close();
            }
        }
        else
        {
            trackedElements.Add(e.id);
            if (!WidgetTracker.Instance)
            {
                EMono.ui.widgets.ActivateWidget("Tracker");
            }
        }
        SE.ClickGeneral();
        if (WidgetTracker.Instance)
        {
            WidgetTracker.Instance.Refresh();
        }
    }
References Widget.Close(), Card.elements, Element.id, Instance, Element.owner, EMono.pc, EMono.player, Refresh(), Player.trackedElements, and EMono.ui.
Referenced by WindowCharaMini.Refresh(), WindowChara.RefreshSkill(), and WindowChara.RefreshStatic().
Member Data Documentation
Instance
WidgetTracker WidgetTracker.Instance static
Definition at line 128 of file WidgetTracker.cs.
Referenced by Toggle().
lastSb
FastString WidgetTracker.lastSb = new FastString(32) private
Definition at line 132 of file WidgetTracker.cs.
Referenced by Refresh().
sb
FastString WidgetTracker.sb = new FastString(32) private
Definition at line 130 of file WidgetTracker.cs.
Referenced by Refresh().
text
UIText WidgetTracker.text
Definition at line 134 of file WidgetTracker.cs.
Referenced by Refresh().
Property Documentation
extra
WidgetTracker.Extra WidgetTracker.extra get
Definition at line 12 of file WidgetTracker.cs.
    {
        get
        {
            return base.config.extra as WidgetTracker.Extra;
        }
    }
Referenced by OnSetContextMenu(), and Refresh().
The documentation for this class was generated from the following file:
Elin/WidgetTracker.cs