Elin Decompiled Documentation: HoardActor Class Reference
HoardActor Class Reference
Classes
class BG
Public Member Functions
void Activate ()
void RefreshZoom ()
void MakeSteady (CollectibleActor a)
void MakePair (CollectibleActor a, CollectibleActor b, float dist=0.26f)
void MakePair (CollectibleActor a, CollectibleActor b, Vector3 v)
void RefreshBG ()
void Clear ()
Public Attributes
Camera cam
Vector3 posCenter
float radiusX
float radiusY
float sizeMod
float sizeModCircle
float reflectMod
new bool debug
List< CollectibleActor > actors
List< RigidUpdate > updates
MeshPass passShadow
Material matReflection
Material matMani
AnimationCurve curveMani
SpriteRenderer srBG
SpriteRenderer srReflection
ParticleSystem psExplode
HoardActor.BG[] bgs
float groundY = -4f
float shdowLimitY = 1f
float alphaFix1 = 0.3f
float alphaFix2 = 0.5f
float alphaFix4 = 0.15f
float maxAplha = 0.6f
float sizeFixY = -0.1f
Static Package Functions
static void< Activate > g__DisableParticle (CollectibleActor a, int chance)
Properties
Hoard hoard [get]
HoardActor.BG bg [get]
Properties inherited from EMono
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SoundManager Sound [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static CoreDebug debug [get]
Private Member Functions
void Update ()
void FixedUpdate ()
bool< Activate > g__FindPair (CollectibleActor taker, string id, float dist)
Private Attributes
CollectibleActor renton
CollectibleActor ehe
bool angryEhe
float eheTimer = -5f
int eheCount
Additional Inherited Members
Static Public Member Functions inherited from EMono
static int rnd (int a)
Static Public Attributes inherited from EMono
static Core core
Detailed Description
Definition at line 7 of file HoardActor.cs.
Member Function Documentation
Activate()
void HoardActor.Activate () inline
Definition at line 25 of file HoardActor.cs.
    {
        this.passShadow.Init();
        this.hoard.score = 0;
        this.RefreshBG();
        this.RefreshZoom();
        RigidUpdate.leftX = -5f;
        RigidUpdate.rightX = 5f;
        if (this.actors.Count > 0)
        {
            this.Clear();
        }
        this.angryEhe = (EMono.rnd(2) == 0);
        Vector3 zero = Vector3.zero;
        int num = 0;
        foreach (Hoard.Item item in this.hoard.items.Values)
        {
            num += item.show;
        }
        IEnumerable<Hoard.Item> enumerable = new List<Hoard.Item>(this.hoard.items.Values).Shuffle<Hoard.Item>();
        string b = this.hoard.mode.ToString();
        foreach (Hoard.Item item2 in enumerable)
        {
            string filter = item2.Source.filter;
            if (this.hoard.mode == Hoard.Mode.all || filter.IsEmpty() || !(filter != b))
            {
                bool flag = item2.Source.tag.Contains("god");
                int num2 = item2.show;
                if (item2.random)
                {
                    num2 = Rand.rnd(num2 + 1);
                    if (num2 > 2 && num2 < 50)
                    {
                        num2 = Rand.rnd(num2 + 1) + 1;
                    }
                }
                if (num2 != 0)
                {
                    GameObject actor = this.hoard.GetActor(item2.id);
                    CollectibleActor component = actor.GetComponent<CollectibleActor>();
                    SpriteRenderer component2 = actor.GetComponent<SpriteRenderer>();
                    Vector3 extents = component2.bounds.extents;
                    int num3 = (int)(extents.x * extents.y * 10f);
                    if (num3 > 5)
                    {
                        num3 = 5;
                    }
                    float y = extents.y;
                    float z = flag ? -0.1f : 0f;
                    bool hasSound = !item2.Source.sound.IsEmpty();
                    if (this.debug)
                    {
                        string id = item2.id;
                        string str = "/";
                        Vector3 vector = extents;
                        Debug.Log(id + str + vector.ToString());
                    }
                    float num4 = Mathf.Sqrt(actor.GetComponent<Rigidbody2D>().mass);
                    if (num4 < 0.7f)
                    {
                        num4 = 0.7f;
                    }
                    BoxCollider2D component3 = actor.GetComponent<BoxCollider2D>();
                    if (component3)
                    {
                        component3.size = extents * this.sizeMod;
                    }
                    else
                    {
                        actor.GetComponent<CircleCollider2D>().radius = (extents.x + extents.y) * this.sizeModCircle * this.sizeModCircle;
                    }
                    string id2 = item2.id;
                    uint num5 = <PrivateImplementationDetails>.ComputeStringHash(id2);
                    if (num5 <= 2580362002U)
                    {
                        if (num5 <= 1166849410U)
{
                            if (num5 <= 622086627U)
{
                                if (num5 != 595338019U)
{
                                    if (num5 != 622086627U)
{
                                        goto IL_687;
                                    }
                                    if (!(id2 == "renton"))
{
                                        goto IL_687;
                                    }
                                    this.renton = component;
                                    if (!this.angryEhe)
{
                                        Util.Instantiate<SpriteRenderer>("UI/Layer/Hoard/Effect/sister", component);
                                        component.paired = true;
                                        this.MakeSteady(component);
                                        goto IL_687;
                                    }
                                    goto IL_687;
                                }
                                else if (!(id2 == "mine_dog"))
{
                                    goto IL_687;
                                }
                            }
                            else if (num5 != 1111712579U)
{
                                if (num5 != 1166849410U)
{
                                    goto IL_687;
                                }
                                if (!(id2 == "hat_magic"))
{
                                    goto IL_687;
                                }
                                goto IL_67F;
                            }
                            else
{
                                if (!(id2 == "tentacle"))
{
                                    goto IL_687;
                                }
                                goto IL_676;
                            }
                        }
                        else if (num5 <= 2122968502U)
{
                            if (num5 != 1891070888U)
{
                                if (num5 != 2122968502U)
{
                                    goto IL_687;
                                }
                                if (!(id2 == "mine"))
{
                                    goto IL_687;
                                }
                            }
                            else
{
                                if (!(id2 == "bat"))
{
                                    goto IL_687;
                                }
                                goto IL_67F;
                            }
                        }
                        else if (num5 != 2273286343U)
{
                            if (num5 != 2580362002U)
{
                                goto IL_687;
                            }
                            if (!(id2 == "mine_rock"))
{
                                goto IL_687;
                            }
                        }
                        else
{
                            if (!(id2 == "ehe"))
{
                                goto IL_687;
                            }
                            this.ehe = component;
                            goto IL_687;
                        }
                        actor.AddComponent<RigidExplode>().particle = this.psExplode;
                    }
                    else if (num5 <= 3274701990U)
                    {
                        if (num5 <= 3222636880U)
{
                            if (num5 != 2973714812U)
{
                                if (num5 == 3222636880U)
{
                                    if (id2 == "tentacle3")
{
                                        goto IL_676;
                                    }
                                }
                            }
                            else if (id2 == "pet_mani")
{
                                RigidExplode rigidExplode = actor.AddComponent<RigidExplode>();
                                rigidExplode.particle = this.psExplode;
                                rigidExplode.chance = 0.1f;
                                rigidExplode.intervalMin *= 2f;
                            }
                        }
                        else if (num5 != 3239414499U)
{
                            if (num5 == 3274701990U)
{
                                if (id2 == "sis")
{
                                    if (!this.hoard.voice)
{
                                        hasSound = false;
                                    }
                                }
                            }
                        }
                        else if (id2 == "tentacle2")
{
                            goto IL_676;
                        }
                    }
                    else if (num5 <= 3516364402U)
                    {
                        if (num5 != 3340080213U)
{
                            if (num5 == 3516364402U)
{
                                if (id2 == "mani")
{
                                    if (EMono.rnd(2) == 0)
{
                                        actor.AddComponent<RigidAngle>();
                                    }
                                    if (EMono.rnd(2) == 0)
{
                                        component2.material = this.matMani;
                                        UnityEngine.Object.DestroyImmediate(actor.GetComponent<RigidExplode>());
                                    }
                                    else
{
                                        RigidExplode rigidExplode2 = actor.AddComponent<RigidExplode>();
                                        rigidExplode2.particle = this.psExplode;
                                        rigidExplode2.radius *= 10f;
                                        rigidExplode2.force *= 10f;
                                        rigidExplode2.chance = 0.1f;
                                        rigidExplode2.intervalMin *= 2f;
                                    }
                                }
                            }
                        }
                        else if (id2 == "tentacle4")
{
                            goto IL_676;
                        }
                    }
                    else if (num5 != 3610891294U)
                    {
                        if (num5 == 4049731356U)
{
                            if (id2 == "chicken")
{
                                actor.AddComponent<RigidUpdateSound>();
                            }
                        }
                    }
                    else if (id2 == "hat_feather")
                    {
                        goto IL_67F;
                    }
                    IL_687:
                    if (item2.floating)
                    {
                        actor.AddComponent<RigidFloat>();
                    }
                    component.updates = actor.GetComponents<RigidUpdate>();
                    for (int i = 0; i < num2; i++)
                    {
                        object obj = (i == 0) ? actor : UnityEngine.Object.Instantiate<GameObject>(actor);
                        float num6 = this.radiusX;
                        zero.x = this.posCenter.x + UnityEngine.Random.Range(-num6, num6);
                        zero.y = this.posCenter.y + UnityEngine.Random.Range(0f, this.radiusY + 0.1f * (float)num) / num4;
                        zero.z = z;
                        object obj2 = obj;
                        obj2.transform.position = zero;
                        CollectibleActor component4 = obj2.GetComponent<CollectibleActor>();
                        Rigidbody2D component5 = obj2.GetComponent<Rigidbody2D>();
                        component4.item = item2;
                        component4.hasSound = hasSound;
                        component4.rb = component5;
                        this.actors.Add(component4);
                        if (component4.updates.Length != 0)
{
                            foreach (RigidUpdate rigidUpdate in component4.updates)
{
                                rigidUpdate.rb = component5;
                                this.updates.Add(rigidUpdate);
                            }
                        }
                        component4.shadow = num3;
                        component4.shadowY = y;
                    }
                    continue;
                    IL_676:
                    z = -0.05f;
                    goto IL_687;
                    IL_67F:
                    actor.AddComponent<RigidAngle>();
                    goto IL_687;
                }
            }
        }
        this.actors.Shuffle<CollectibleActor>();
        IEnumerable<CollectibleActor> enumerable2 = from a in this.actors
        where a.item.Source.tag.Contains("god")
        select a;
        IEnumerable<CollectibleActor> enumerable3 = from a in this.actors
        where a.item.Source.tag.Contains("chara")
        select a;
        foreach (CollectibleActor collectibleActor in this.actors)
        {
            if (!collectibleActor.paired)
            {
                string id2 = collectibleActor.item.id;
                uint num5 = <PrivateImplementationDetails>.ComputeStringHash(id2);
                if (num5 <= 2988676833U)
                {
                    if (num5 <= 1150570096U)
                    {
                        if (num5 != 460777894U)
{
                            if (num5 != 1111712579U)
{
                                if (num5 != 1150570096U)
{
                                    goto IL_D33;
                                }
                                if (!(id2 == "qulu"))
{
                                    goto IL_D33;
                                }
                                if (this.<Activate>g__FindPair|25_2(collectibleActor, "dragon", 0.3f))
{
                                    this.MakeSteady(collectibleActor);
                                    continue;
                                }
                                goto IL_D33;
                            }
                            else if (!(id2 == "tentacle"))
{
                                goto IL_D33;
                            }
                        }
                        else
{
                            if (!(id2 == "vesda"))
{
                                goto IL_D33;
                            }
                            HoardActor.<Activate>g__DisableParticle|25_3(collectibleActor, 50);
                            using (IEnumerator<CollectibleActor> enumerator4 = enumerable3.GetEnumerator())
{
                                while (enumerator4.MoveNext())
{
                                    CollectibleActor collectibleActor2 = enumerator4.Current;
                                    if (!collectibleActor2.paired && !(collectibleActor2 == collectibleActor))
{
                                        this.MakePair(collectibleActor, collectibleActor2, new Vector3(0f, -0.25f, -0.01f));
                                        collectibleActor2.transform.localEulerAngles = new Vector3(0f, 0f, 90f);
                                        collectibleActor2.GetComponent<SpriteRenderer>().flipX = false;
                                        break;
                                    }
                                }
                                continue;
                            }
                            goto IL_D2A;
                        }
                    }
                    else if (num5 != 1382054340U)
                    {
                        if (num5 != 2281206494U)
{
                            if (num5 != 2988676833U)
{
                                goto IL_D33;
                            }
                            if (!(id2 == "jure"))
{
                                goto IL_D33;
                            }
                            if (this.<Activate>g__FindPair|25_2(collectibleActor, "odina", 0.3f))
{
                                this.MakeSteady(collectibleActor);
                                continue;
                            }
                            goto IL_D33;
                        }
                        else
{
                            if (!(id2 == "itz"))
{
                                goto IL_D33;
                            }
                            if (EMono.rnd(2) == 0)
{
                                foreach (CollectibleActor collectibleActor3 in enumerable3)
{
                                    if (!collectibleActor3.paired && !(collectibleActor3 == collectibleActor) && collectibleActor3.item.Source.tag.Contains("fem"))
{
                                        this.MakePair(collectibleActor, collectibleActor3, new Vector3(0.02f, 0f, -0.01f));
                                        collectibleActor3.transform.localEulerAngles = new Vector3(0f, 0f, -90f);
                                        collectibleActor3.GetComponent<SpriteRenderer>().flipX = true;
                                        this.MakeSteady(collectibleActor);
                                        break;
                                    }
                                }
                                if (collectibleActor.paired)
{
                                    continue;
                                }
                            }
                            collectibleActor.GetComponentInChildren<ParticleSystem>().SetActive(false);
                            goto IL_D33;
                        }
                    }
                    else
                    {
                        if (!(id2 == "lar"))
{
                            goto IL_D33;
                        }
                        goto IL_C47;
                    }
                }
                else if (num5 <= 3340080213U)
                {
                    if (num5 != 3222636880U)
                    {
                        if (num5 != 3239414499U)
{
                            if (num5 != 3340080213U)
{
                                goto IL_D33;
                            }
                            if (!(id2 == "tentacle4"))
{
                                goto IL_D33;
                            }
                        }
                        else if (!(id2 == "tentacle2"))
{
                            goto IL_D33;
                        }
                    }
                    else if (!(id2 == "tentacle3"))
                    {
                        goto IL_D33;
                    }
                }
                else if (num5 != 3842579285U)
                {
                    if (num5 != 3907705998U)
                    {
                        if (num5 != 4161811998U)
{
                            goto IL_D33;
                        }
                        if (!(id2 == "dragon"))
{
                            goto IL_D33;
                        }
                        if (this.<Activate>g__FindPair|25_2(collectibleActor, "qulu", 0.3f))
{
                            this.MakeSteady(collectibleActor);
                            continue;
                        }
                        goto IL_D33;
                    }
                    else
                    {
                        if (!(id2 == "lomi"))
{
                            goto IL_D33;
                        }
                        if (this.<Activate>g__FindPair|25_2(collectibleActor, "lar", 0.15f))
{
                            this.MakeSteady(collectibleActor);
                            continue;
                        }
                        continue;
                    }
                }
                else
                {
                    if (!(id2 == "lulu"))
                    {
                        goto IL_D33;
                    }
                    goto IL_D2A;
                }
                using (IEnumerator<CollectibleActor> enumerator4 = enumerable3.GetEnumerator())
                {
                    while (enumerator4.MoveNext())
                    {
                        CollectibleActor collectibleActor4 = enumerator4.Current;
                        if (!collectibleActor4.paired && !(collectibleActor4 == collectibleActor))
{
                            this.MakePair(collectibleActor, collectibleActor4, new Vector3(0f, 0.25f, -0.01f));
                            collectibleActor.GetComponent<SpriteAnimation>().link = collectibleActor4.transform;
                            if (EMono.rnd(2) == 0)
{
                                collectibleActor4.GetComponent<SpriteRenderer>().flipX = true;
                            }
                            if (EMono.rnd(2) == 0)
{
                                collectibleActor.transform.SetLocalScaleX(collectibleActor.transform.localScale.x * -1f);
                                break;
                            }
                            break;
                        }
                    }
                    continue;
                }
                IL_C47:
                if (this.<Activate>g__FindPair|25_2(collectibleActor, "lomi", 0.15f))
                {
                    this.MakeSteady(collectibleActor);
                    continue;
                }
                continue;
                IL_D33:
                if (EMono.rnd(2) != 0 && collectibleActor.item.Source.tag.Contains("pair"))
                {
                    foreach (CollectibleActor collectibleActor5 in enumerable2)
                    {
                        if (!collectibleActor5.paired && !(collectibleActor5 == collectibleActor))
{
                            this.MakePair(collectibleActor, collectibleActor5, 0.26f);
                            break;
                        }
                    }
                    continue;
                }
                continue;
                IL_D2A:
                HoardActor.<Activate>g__DisableParticle|25_3(collectibleActor, 50);
                goto IL_D33;
            }
        }
        foreach (CollectibleActor collectibleActor6 in this.actors)
        {
            if (!collectibleActor6.paired && EMono.rnd(3) != 0)
            {
                collectibleActor6.GetComponent<SpriteRenderer>().flipX = true;
            }
        }
    }
References Activate(), actors, angryEhe, Clear(), debug, g__DisableParticle(), g__FindPair(), Hoard.GetActor(), hoard, MeshPass.Init(), CollectibleActor.item, Hoard.items, MakePair(), MakeSteady(), matMani, Hoard.mode, CollectibleActor.paired, passShadow, psExplode, radiusX, radiusY, RefreshBG(), RefreshZoom(), EClass.rnd(), EMono.rnd(), sizeMod, sizeModCircle, CollectibleActor.updates, updates, and Hoard.voice.
Referenced by Activate(), and LayerHoard.Reset().
Clear()
void HoardActor.Clear () inline
Definition at line 612 of file HoardActor.cs.
    {
        foreach (CollectibleActor collectibleActor in this.actors)
        {
            if (collectibleActor && collectibleActor.gameObject)
            {
                UnityEngine.Object.DestroyImmediate(collectibleActor.gameObject);
            }
        }
        this.actors.Clear();
        this.updates.Clear();
    }
References actors, and updates.
Referenced by Activate(), and LayerHoard.OnKill().
FixedUpdate()
void HoardActor.FixedUpdate () inline private
Definition at line 662 of file HoardActor.cs.
    {
        float num = RigidUpdate.delta = Time.fixedDeltaTime;
        if (this.angryEhe && this.renton && this.ehe && !this.ehe.rb.isKinematic && (Mathf.Abs(this.renton.transform.position.x - this.ehe.transform.position.x) > 0.6f || this.renton.transform.position.y > this.ehe.transform.position.y))
        {
            this.eheTimer += num;
            if (this.eheTimer > 2f)
            {
                this.ehe.rb.position = new Vector3(this.renton.transform.position.x, this.renton.transform.position.y + 4f, this.ehe.transform.position.z);
                this.ehe.PlaySound("teleport");
                this.eheTimer = 0f;
                this.eheCount++;
                if (this.eheCount > 5)
                {
                    this.renton.rb.constraints = RigidbodyConstraints2D.FreezePositionX;
                    this.renton.rb.gravityScale = 3f;
                }
            }
        }
        else
        {
            this.eheTimer = 0f;
        }
        foreach (RigidUpdate rigidUpdate in this.updates)
        {
            if (rigidUpdate.active)
            {
                rigidUpdate.OnFixedUpdate();
            }
        }
    }
References RigidUpdate.active, angryEhe, ehe, eheCount, eheTimer, RigidUpdate.OnFixedUpdate(), CollectibleActor.PlaySound(), CollectibleActor.rb, renton, and updates.
g__DisableParticle()
static void< Activate > HoardActor.g__DisableParticle (CollectibleActor a, int chance) inline static package
Definition at line 709 of file HoardActor.cs.
    {
        if (EMono.rnd(100) < chance)
        {
            ParticleSystem[] componentsInChildren = a.GetComponentsInChildren<ParticleSystem>();
            for (int i = 0; i < componentsInChildren.Length; i++)
            {
                componentsInChildren[i].SetActive(false);
            }
        }
    }
References EMono.rnd().
Referenced by Activate().
g__FindPair()
bool< Activate > HoardActor.g__FindPair (CollectibleActor taker, string id, float dist) inline private
Definition at line 695 of file HoardActor.cs.
    {
        foreach (CollectibleActor collectibleActor in this.actors)
        {
            if (collectibleActor.item.id == id && !collectibleActor.paired)
            {
                this.MakePair(taker, collectibleActor, dist);
                return true;
            }
        }
        return false;
    }
References actors, CollectibleActor.item, MakePair(), and CollectibleActor.paired.
Referenced by Activate().
MakePair() [1/2]
void HoardActor.MakePair (CollectibleActor a, CollectibleActor b, float dist = 0::26f) inline
Definition at line 585 of file HoardActor.cs.
    {
        float z = 0.01f;
        if (a.item.id != "lulu")
        {
            z = ((Rand.rnd(2) == 0) ? 0.01f : -0.01f);
        }
        this.MakePair(a, b, new Vector3(dist, 0f, z));
    }
References CollectibleActor.item, and MakePair().
Referenced by Activate(), g__FindPair(), and MakePair().
MakePair() [2/2]
void HoardActor.MakePair (CollectibleActor a, CollectibleActor b, Vector3 v) inline
Definition at line 595 of file HoardActor.cs.
    {
        b.transform.SetParent(a.transform, true);
        b.transform.localPosition = v;
        b.GetComponent<SpriteRenderer>().flipX = true;
        b.rb.isKinematic = true;
        b.GetComponent<Collider2D>().enabled = false;
        a.paired = (b.paired = true);
    }
MakeSteady()
void HoardActor.MakeSteady (CollectibleActor a) inline
Definition at line 580 of file HoardActor.cs.
    {
        (a.rb ?? a.GetComponent<Rigidbody2D>()).freezeRotation = true;
    }
Referenced by Activate().
RefreshBG()
void HoardActor.RefreshBG () inline
Definition at line 605 of file HoardActor.cs.
    {
        this.srBG.sprite = (this.srReflection.sprite = this.bg.sprite);
        this.matReflection.SetColor("_GrabColor", new Color(1f, 1f, 1f, this.bg.reflection * (0.01f * (float)this.hoard.reflection)));
        this.srReflection.SetActive(this.hoard.reflection > 0);
    }
References bg, Color, hoard, matReflection, Hoard.reflection, and srReflection.
Referenced by Activate(), and LayerHoard.OnClickConfig().
RefreshZoom()
void HoardActor.RefreshZoom () inline
Definition at line 570 of file HoardActor.cs.
    {
        if (this.hoard.pixelPerfect)
        {
            this.cam.orthographicSize = (float)Screen.height * 0.5f * 0.01f * 2f;
            return;
        }
        this.cam.orthographicSize = 5f;
    }
References hoard, and Hoard.pixelPerfect.
Referenced by Activate(), LayerHoard.OnClickConfig(), and Update().
Update()
void HoardActor.Update () inline private
Definition at line 625 of file HoardActor.cs.
    {
        this.RefreshZoom();
        this.matMani.SetFloat("_Space", this.curveMani.Evaluate(Time.timeSinceLevelLoad % 10f / 10f));
        float value = (this.cam.orthographicSize <= 5f) ? 0f : ((this.cam.orthographicSize - 5f) * this.reflectMod);
        this.matReflection.SetFloat("_Offset", value);
        EMono.scene.transAudio.position = new Vector3(0f, this.groundY, 0f);
        if (!this.hoard.shadow)
        {
            return;
        }
        float shadow = this.bg.shadow;
        foreach (CollectibleActor collectibleActor in this.actors)
        {
            if (collectibleActor.active)
            {
                float num = (collectibleActor.transform.position.y - this.alphaFix1) * this.alphaFix2;
                num = 1f - num * num * this.alphaFix4;
                if (num >= 0f)
                {
                    if (num > this.maxAplha)
                    {
                        num = this.maxAplha;
                    }
                    num *= shadow;
                    float num2 = (collectibleActor.transform.position.y + this.groundY) * 0.05f;
                    if (num2 > this.shdowLimitY)
                    {
                        num2 = this.shdowLimitY;
                    }
                    this.passShadow.Add(collectibleActor.transform.position.x, collectibleActor.shadowY * this.sizeFixY + this.groundY + num2, 0.8f, (float)((int)(num * 1000f) * 1000 + collectibleActor.shadow), 0f);
                }
            }
        }
        this.passShadow.Draw();
    }
References CollectibleActor.active, actors, MeshPass.Add(), alphaFix1, alphaFix2, alphaFix4, bg, cam, curveMani, MeshPass.Draw(), groundY, hoard, matMani, matReflection, maxAplha, passShadow, reflectMod, RefreshZoom(), CollectibleActor.shadow, Hoard.shadow, CollectibleActor.shadowY, and shdowLimitY.
Member Data Documentation
actors
List<CollectibleActor> HoardActor.actors
Definition at line 737 of file HoardActor.cs.
Referenced by Activate(), Clear(), g__FindPair(), Update(), and LayerHoard.Update().
alphaFix1
float HoardActor.alphaFix1 = 0.3f
Definition at line 771 of file HoardActor.cs.
Referenced by Update().
alphaFix2
float HoardActor.alphaFix2 = 0.5f
Definition at line 773 of file HoardActor.cs.
Referenced by Update().
alphaFix4
float HoardActor.alphaFix4 = 0.15f
Definition at line 775 of file HoardActor.cs.
Referenced by Update().
angryEhe
bool HoardActor.angryEhe private
Definition at line 761 of file HoardActor.cs.
Referenced by Activate(), and FixedUpdate().
bgs
HoardActor.BG [] HoardActor.bgs
Definition at line 755 of file HoardActor.cs.
cam
Camera HoardActor.cam
Definition at line 721 of file HoardActor.cs.
Referenced by Update().
curveMani
AnimationCurve HoardActor.curveMani
Definition at line 747 of file HoardActor.cs.
Referenced by Update().
debug
new bool HoardActor.debug
Definition at line 735 of file HoardActor.cs.
Referenced by Activate().
ehe
CollectibleActor HoardActor.ehe private
Definition at line 759 of file HoardActor.cs.
Referenced by FixedUpdate().
eheCount
int HoardActor.eheCount private
Definition at line 765 of file HoardActor.cs.
Referenced by FixedUpdate().
eheTimer
float HoardActor.eheTimer = -5f private
Definition at line 763 of file HoardActor.cs.
Referenced by FixedUpdate().
groundY
float HoardActor.groundY = -4f
Definition at line 767 of file HoardActor.cs.
Referenced by Update().
matMani
Material HoardActor.matMani
Definition at line 745 of file HoardActor.cs.
Referenced by Activate(), and Update().
matReflection
Material HoardActor.matReflection
Definition at line 743 of file HoardActor.cs.
Referenced by RefreshBG(), and Update().
maxAplha
float HoardActor.maxAplha = 0.6f
Definition at line 777 of file HoardActor.cs.
Referenced by Update().
passShadow
MeshPass HoardActor.passShadow
Definition at line 741 of file HoardActor.cs.
Referenced by Activate(), and Update().
posCenter
Vector3 HoardActor.posCenter
Definition at line 723 of file HoardActor.cs.
psExplode
ParticleSystem HoardActor.psExplode
Definition at line 753 of file HoardActor.cs.
Referenced by Activate(), and LayerHoard.Update().
radiusX
float HoardActor.radiusX
Definition at line 725 of file HoardActor.cs.
Referenced by Activate().
radiusY
float HoardActor.radiusY
Definition at line 727 of file HoardActor.cs.
Referenced by Activate().
reflectMod
float HoardActor.reflectMod
Definition at line 733 of file HoardActor.cs.
Referenced by Update().
renton
CollectibleActor HoardActor.renton private
Definition at line 757 of file HoardActor.cs.
Referenced by FixedUpdate().
shdowLimitY
float HoardActor.shdowLimitY = 1f
Definition at line 769 of file HoardActor.cs.
Referenced by Update().
sizeFixY
float HoardActor.sizeFixY = -0.1f
Definition at line 779 of file HoardActor.cs.
sizeMod
float HoardActor.sizeMod
Definition at line 729 of file HoardActor.cs.
Referenced by Activate().
sizeModCircle
float HoardActor.sizeModCircle
Definition at line 731 of file HoardActor.cs.
Referenced by Activate().
srBG
SpriteRenderer HoardActor.srBG
Definition at line 749 of file HoardActor.cs.
srReflection
SpriteRenderer HoardActor.srReflection
Definition at line 751 of file HoardActor.cs.
Referenced by RefreshBG().
updates
List<RigidUpdate> HoardActor.updates
Definition at line 739 of file HoardActor.cs.
Referenced by Activate(), Clear(), FixedUpdate(), and LayerHoard.Update().
Property Documentation
bg
HoardActor.BG HoardActor.bg get
Definition at line 17 of file HoardActor.cs.
    {
        get
        {
            return this.bgs[this.hoard.bg];
        }
    }
Referenced by RefreshBG(), and Update().
hoard
Hoard HoardActor.hoard get
Definition at line 9 of file HoardActor.cs.
    {
        get
        {
            return EMono.player.hoard;
        }
    }
Referenced by Activate(), RefreshBG(), RefreshZoom(), and Update().
The documentation for this class was generated from the following file:
Elin/HoardActor.cs