Elin Decompiled Documentation: GrowSystem.Stage Class Reference
GrowSystem.Stage Class Reference
Public Member Functions
void SetTile (int _tile)
void SetTile (int tileIdx, params int[] _tiles)
int Convert (int tile)
Public Attributes
int[] tiles
int idx
int tileEx
RenderData renderData
bool harvest
Detailed Description
Definition at line 5 of file GrowSystem.cs.
Member Function Documentation
Convert()
int GrowSystem.Stage.Convert (int tile) inline
Definition at line 31 of file GrowSystem.cs.
        {
            return renderData.ConvertTile(tile);
        }
References RenderData.ConvertTile(), and GrowSystem.Stage.renderData.
Referenced by GrowSystem.Stage.SetTile().
SetTile() [1/2]
void GrowSystem.Stage.SetTile (int _tile) inline
Definition at line 17 of file GrowSystem.cs.
        {
            tiles = new int[Convert(_tile)];
        }
References GrowSystem.Stage.Convert(), and GrowSystem.Stage.tiles.
Referenced by GrowSystem.SetGenericFirstStageTile(), GrowSystemTree.SetGenericFirstStageTile(), GrowSystem.SetStageTile(), GrowSystemTree.SetStageTile(), and GrowSystemTreeSingle.SetStageTile().
SetTile() [2/2]
void GrowSystem.Stage.SetTile (int tileIdx, params int[] _tiles) inline
Definition at line 22 of file GrowSystem.cs.
        {
            tiles = new int[_tiles.Length];
            for (int i = 0; i < tiles.Length; i++)
            {
                tiles[i] = Convert(_tiles[i] + tileIdx);
            }
        }
References GrowSystem.Stage.Convert(), and GrowSystem.Stage.tiles.
Member Data Documentation
harvest
bool GrowSystem.Stage.harvest
Definition at line 15 of file GrowSystem.cs.
Referenced by GrowSystem.CanHarvest(), and GrowSystem.OnRenderTileMap().
idx
int GrowSystem.Stage.idx
Definition at line 9 of file GrowSystem.cs.
Referenced by GrowSystemWheat.GetStageTile(), Zone.GrowPlants(), GrowSystem.IsWithered(), GrowSystem.Perish(), GrowSystem.SetStageTile(), and GrowSystemTree.SetStageTile().
renderData
RenderData GrowSystem.Stage.renderData
Definition at line 13 of file GrowSystem.cs.
Referenced by GrowSystem.Stage.Convert(), and GrowSystem.OnRenderTileMap().
tileEx
int GrowSystem.Stage.tileEx
Definition at line 11 of file GrowSystem.cs.
tiles
int [] GrowSystem.Stage.tiles
Definition at line 7 of file GrowSystem.cs.
Referenced by GrowSystem.GetStageTile(), and GrowSystem.Stage.SetTile().
The documentation for this class was generated from the following file:
Elin/GrowSystem.cs