Elin Decompiled Documentation: NewsList Class Reference
NewsList Class Reference
Classes
class Item
Static Public Member Functions
static void Init ()
static List< Item > GetNews (int seed)
Static Public Member Functions inherited from EClass
static int rndSeed (int a, int seed)
static int rnd (int a)
static int curve (int a, int start, int step, int rate=75)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Static Public Attributes
static Dictionary< string, List< Item > > dict
static List< Item > listAll = new List<Item>()
Static Public Attributes inherited from EClass
static Core core
Additional Inherited Members
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Detailed Description
Definition at line 4 of file NewsList.cs.
Member Function Documentation
GetNews()
static List< Item > NewsList.GetNews (int seed) inline static
Definition at line 80 of file NewsList.cs.
    {
        Init();
        Rand.SetSeed(seed);
        List<Item> list = new List<Item>();
        for (int i = 0; i < 1000; i++)
        {
            Item item = listAll.RandomItem();
            if (!list.Contains(item))
            {
                list.Add(item);
                if (list.Count >= 3)
                {
                    break;
                }
            }
        }
        Rand.SetSeed();
        return list;
    }
References Init(), item, listAll, seed, and Rand.SetSeed().
Referenced by LayerNewspaper.RefreshNews().
Init()
static void NewsList.Init () inline static
Definition at line 19 of file NewsList.cs.
    {
        if (dict == null)
        {
            dict = new Dictionary<string, List<Item>>();
            listAll.Clear();
            AddDir(CorePath.CorePackage.News);
        }
        static void AddDir(string path)
        {
            DirectoryInfo directoryInfo = new DirectoryInfo(path);
            Item item = null;
            FileInfo[] files = directoryInfo.GetFiles();
            foreach (FileInfo fileInfo in files)
            {
                if (!(fileInfo.Extension != ".txt"))
                {
                    string fileNameWithoutExtension = Path.GetFileNameWithoutExtension(fileInfo.Name);
                    List<Item> list = dict.TryGetValue(fileNameWithoutExtension);
                    StreamReader streamReader = new StreamReader(fileInfo.FullName);
                    string text = null;
                    while (!streamReader.EndOfStream)
                    {
                        string text2 = streamReader.ReadLine();
                        if (!string.IsNullOrEmpty(text2))
{
                            if (text2.StartsWith('@') && item != null)
{
                                string[] array = text2.TrimStart('@').Split(',');
                                foreach (string item2 in array)
{
                                    item.listImageId.Add(item2);
                                }
                            }
                            else if (text == null)
{
                                text = text2;
                            }
                            else
{
                                item = new Item
{
                                    title = text,
                                    content = text2
                                };
                                if (list == null)
{
                                    list = new List<Item>();
                                    dict.Add(fileNameWithoutExtension, list);
                                }
                                list.Add(item);
                                listAll.Add(item);
                                text = null;
                            }
                        }
                    }
                }
            }
        }
    }
References dict, item, listAll, CorePath.CorePackage.News, and title.
Referenced by GetNews().
Member Data Documentation
dict
Dictionary<string, List<Item> > NewsList.dict static
Definition at line 15 of file NewsList.cs.
Referenced by Init().
listAll
List<Item> NewsList.listAll = new List<Item>() static
Definition at line 17 of file NewsList.cs.
Referenced by GetNews(), Init(), and LayerNewspaper.RefreshNews().
The documentation for this class was generated from the following file:
Elin/NewsList.cs