Elin Decompiled Documentation: LayerEditPortrait Class Reference
LayerEditPortrait Class Reference
Public Member Functions
void Activate (Chara _chara, PCCData _pcc=null, Action< Color > _action=null)
void RefreshButtons ()
void OnClickClear ()
void RefreshHairColor ()
void RefreshList ()
Public Member Functions inherited from ELayer
override void OnBeforeAddLayer ()
void InitInspector ()
sealed override void Init ()
override void OnAfterAddLayer ()
void TryShowHelp ()
void AddLayerToUI (string id)
void TryShowHint (string _langHint=null)
void TalkHomeMemeber (string id)
void TalkMaid (string id)
override void OnRightClick ()
Public Member Functions inherited from Layer
virtual string GetTextHeader (Window window)
virtual bool HeaderIsListOf (int id)
virtual void Init ()
virtual void OnInit ()
virtual void OnAfterInit ()
virtual void ApplySkin ()
void ShowScreenLock (string id)
void UpdateInput ()
virtual void OnUpdateInput ()
virtual void OnRightClick ()
virtual bool OnBack ()
virtual void OnChangeLayer ()
virtual void OnCreate ()
void _AddLayer (string id)
Layer AddLayer (string id)
T AddLayer< T > ()
T AddLayer< T > (string id)
T AddLayerDontCloseOthers< T > ()
Layer AddLayerDontCloseOthers (Layer l)
T GetOrAddLayer< T > ()
virtual void OnBeforeAddLayer ()
virtual void OnAfterAddLayer ()
Layer AddLayer (Layer l)
void ToggleLayer (string id)
T ToggleLayer< T > (string id=null)
void WaitAndClose ()
void OnClickClose ()
virtual void Close ()
void CloseLayers ()
void RemoveLayers (bool removeImportant=false)
bool RemoveLayer< T > ()
void RemoveLayer (Layer l)
virtual void OnKill ()
Layer SetOnKill (Action action)
void DisableClose ()
void Delay (float duration=0.05f)
Layer SetDelay (float d)
Layer GetLayer (string id)
T GetLayer< T > (bool fromTop=false)
Layer GetTopLayer ()
void SwitchContent (int idWindow, int i)
virtual void OnSwitchContent (Window window)
Layer SetTitles (string langList, string idHeaderRow=null)
bool IsBlockWidgetClick ()
bool IsHideHud ()
bool IsAllowGeneralInput ()
bool IsUseBlur ()
bool IsPointerOnLayer ()
void ApplySkin ()
Public Attributes
Portrait portrait
Chara chara
UISlider sliderPortrait
UIColorPicker uiPicker
UIDynamicList list
PCCData pcc
UIButton buttonGender
UIButton buttonUnique
Color hairColor
Action< Color > action
Public Attributes inherited from Layer
Option option
UnityEvent onKill
Anime animeIn
Anime animeOut
bool closeOthers
bool defaultActionMode = true
Button screenLock
Layer parent
string idLayer
List< Layer > layers = new List<Layer>()
Vector2 lastParentPos
List< Window > windows = new List<Window>()
string langHint
Private Attributes
bool hasColorChanged
bool gender = true
bool unique
Additional Inherited Members
Static Public Member Functions inherited from ELayer
static int rnd (int a)
Static Public Member Functions inherited from Layer
static T Create< T > ()
static T Create< T > (string path)
static Layer Create (string path)
Static Public Attributes inherited from Layer
static int skipInput
static bool closeOnRightClick
static bool rightClicked
static bool cancelKeyDown
static bool ignoreSounds
static Transform blurStopInstance
static string[] searchPath = new string[3] { "Layer", "Layer/Dialog", "Layer/LayerHome" }
Protected Member Functions inherited from ELayer
sealed override void _Close ()
sealed override void Kill ()
Protected Member Functions inherited from Layer
virtual void Awake ()
virtual void _Close ()
virtual void Kill ()
Protected Attributes inherited from Layer
RectTransform _rect
bool isDestroyed
Properties inherited from ELayer
static Core core [get]
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static FactionBranch Branch [get]
static Faction Home [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static CoreConfig config [get]
static GameSetting setting [get]
static ColorProfile Colors [get]
static SourceManager sources [get]
static World world [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
bool IsFloat [get]
virtual string IdHelp [get]
Properties inherited from Layer
Layer TopLayer [get]
string uid [get]
virtual RectTransform rectLayers [get]
virtual bool blockWidgetClick [get]
Detailed Description
Definition at line 6 of file LayerEditPortrait.cs.
Member Function Documentation
Activate()
void LayerEditPortrait.Activate (Chara _chara, PCCData _pcc = null, Action< Color > _action = null) inline
Definition at line 34 of file LayerEditPortrait.cs.
    {
        chara = _chara;
        pcc = _pcc;
        action = _action;
        if (action == null)
        {
            action = delegate
            {
            };
        }
        portrait.SetChara(chara);
        if (chara.GetInt(105) == 0)
        {
            hairColor = portrait.GetRandomHairColor(chara);
        }
        else
        {
            hairColor = IntColor.FromInt(chara.GetInt(105));
        }
        if (pcc != null)
        {
            hairColor = pcc.GetHairColor();
        }
        uiPicker.SetColor(hairColor, hairColor, delegate(PickerState state, Color _c)
        {
            ColorUtility.TryParseHtmlString("#" + ColorUtility.ToHtmlStringRGBA(_c), out var color);
            if (pcc == null)
            {
                chara.SetInt(105, IntColor.ToInt(color));
            }
            else
            {
                pcc.SetColor("hair", color);
            }
            portrait.SetChara(chara, pcc);
            action(color);
            hairColor = color;
            hasColorChanged = true;
        });
        RefreshList();
        InvokeRepeating("RefreshHairColor", 0f, 0.1f);
        buttonGender = windows[0].AddBottomButton("portrait_gender", delegate
        {
            gender = !gender;
            RefreshButtons();
            list.List();
        });
        buttonUnique = windows[0].AddBottomButton("portrait_unique", delegate
        {
            unique = !unique;
            RefreshButtons();
            list.List();
        });
        RefreshButtons();
    }
References action, buttonGender, buttonUnique, chara, Color, IntColor.FromInt(), gender, BaseCard.GetInt(), Portrait.GetRandomHairColor(), hairColor, hasColorChanged, if(), list, UIDynamicList.List(), pcc, portrait, RefreshButtons(), RefreshList(), Portrait.SetChara(), UIColorPicker.SetColor(), BaseCard.SetInt(), IntColor.ToInt(), uiPicker, unique, and Layer.windows.
OnClickClear()
void LayerEditPortrait.OnClickClear () inline
Definition at line 99 of file LayerEditPortrait.cs.
    {
        SE.Trash();
        chara.c_idPortrait = null;
        portrait.SetChara(chara, pcc);
        action(hairColor);
    }
References action, chara, hairColor, pcc, portrait, and Portrait.SetChara().
RefreshButtons()
void LayerEditPortrait.RefreshButtons () inline
Definition at line 91 of file LayerEditPortrait.cs.
    {
        buttonGender.mainText.SetText("portrait_gender".lang() + " (" + (gender ? "On" : "Off") + ")");
        buttonUnique.mainText.SetText("portrait_unique".lang() + " (" + (unique ? "On" : "Off") + ")");
        buttonGender.RebuildLayout();
        buttonUnique.RebuildLayout();
    }
References buttonGender, buttonUnique, gender, UIButton.mainText, UIText.SetText(), and unique.
Referenced by Activate().
RefreshHairColor()
void LayerEditPortrait.RefreshHairColor () inline
Definition at line 107 of file LayerEditPortrait.cs.
    {
        if (hasColorChanged)
        {
            list.Redraw();
            hasColorChanged = false;
        }
    }
References hasColorChanged, list, and UIDynamicList.Redraw().
RefreshList()
void LayerEditPortrait.RefreshList () inline
Definition at line 116 of file LayerEditPortrait.cs.
    {
        list.Clear();
        list.callbacks = new UIList.Callback<ModItem<Sprite>, Portrait>
        {
            onClick = delegate(ModItem<Sprite> a, Portrait b)
            {
                list.Select(a);
                SE.Click();
                chara.c_idPortrait = a.id;
                portrait.SetChara(chara, pcc);
                action(hairColor);
            },
            onRedraw = delegate(ModItem<Sprite> a, Portrait b, int i)
            {
                b.mainText.SetText(a.id);
                b.SetPortrait(a.id, hairColor);
                b.tooltip.lang = a.id;
            },
            onList = delegate
            {
                int num = (gender ? chara.bio.gender : 0);
                IEnumerable<ModItem<Sprite>> enumerable = Portrait.ListPortraits(num, "c").Concat(Portrait.ListPortraits(num, "guard")).Concat(Portrait.ListPortraits(num, "special"))
                    .Concat(Portrait.ListPortraits(num, "foxfolk"));
                if (unique)
                {
                    enumerable = enumerable.Concat(Portrait.ListPortraits(0, "UN"));
                }
                foreach (ModItem<Sprite> item in enumerable.ToList())
                {
                    list.Add(item);
                }
            }
        };
        list.List();
        list.Select((ModItem<Sprite> a) => a.id == chara.c_idPortrait);
    }
References action, UIDynamicList.Add(), Card.c_idPortrait, chara, UIDynamicList.Clear(), gender, hairColor, ModItem< T >.id, item, list, UIDynamicList.List(), Portrait.ListPortraits(), UIButton.mainText, pcc, portrait, UIDynamicList.Select(), Portrait.SetChara(), Portrait.SetPortrait(), UIText.SetText(), and unique.
Referenced by Activate().
Member Data Documentation
action
Action<Color> LayerEditPortrait.action
Definition at line 26 of file LayerEditPortrait.cs.
Referenced by Activate(), OnClickClear(), and RefreshList().
buttonGender
UIButton LayerEditPortrait.buttonGender
Definition at line 20 of file LayerEditPortrait.cs.
Referenced by Activate(), and RefreshButtons().
buttonUnique
UIButton LayerEditPortrait.buttonUnique
Definition at line 22 of file LayerEditPortrait.cs.
Referenced by Activate(), and RefreshButtons().
chara
Chara LayerEditPortrait.chara
Definition at line 10 of file LayerEditPortrait.cs.
Referenced by Activate(), OnClickClear(), and RefreshList().
gender
bool LayerEditPortrait.gender = true private
Definition at line 30 of file LayerEditPortrait.cs.
Referenced by Activate(), RefreshButtons(), and RefreshList().
hairColor
Color LayerEditPortrait.hairColor
Definition at line 24 of file LayerEditPortrait.cs.
Referenced by Activate(), OnClickClear(), and RefreshList().
hasColorChanged
bool LayerEditPortrait.hasColorChanged private
Definition at line 28 of file LayerEditPortrait.cs.
Referenced by Activate(), and RefreshHairColor().
list
UIDynamicList LayerEditPortrait.list
Definition at line 16 of file LayerEditPortrait.cs.
Referenced by Activate(), RefreshHairColor(), and RefreshList().
pcc
PCCData LayerEditPortrait.pcc
Definition at line 18 of file LayerEditPortrait.cs.
Referenced by Activate(), OnClickClear(), and RefreshList().
portrait
Portrait LayerEditPortrait.portrait
Definition at line 8 of file LayerEditPortrait.cs.
Referenced by Activate(), OnClickClear(), and RefreshList().
sliderPortrait
UISlider LayerEditPortrait.sliderPortrait
Definition at line 12 of file LayerEditPortrait.cs.
uiPicker
UIColorPicker LayerEditPortrait.uiPicker
Definition at line 14 of file LayerEditPortrait.cs.
Referenced by Activate().
unique
bool LayerEditPortrait.unique private
Definition at line 32 of file LayerEditPortrait.cs.
Referenced by Activate(), RefreshButtons(), and RefreshList().
The documentation for this class was generated from the following file:
Elin/LayerEditPortrait.cs