Elin Decompiled Documentation: UIHangIcon Class Reference
UIHangIcon Class Reference
Public Member Functions
void OnClickCorner ()
void OnClick ()
void Refresh ()
Public Attributes
Image image
UIButton button
string id
bool rightClick
bool windowCorner
Static Public Attributes
static Sprite lastCorner
Static Public Attributes inherited from EMono
static Core core
Private Member Functions
void Awake ()
Private Attributes
Sprite original
Additional Inherited Members
Static Public Member Functions inherited from EMono
static int rnd (int a)
Properties inherited from EMono
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SoundManager Sound [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static CoreDebug debug [get]
Detailed Description
Definition at line 4 of file UIHangIcon.cs.
Member Function Documentation
Awake()
void UIHangIcon.Awake () inline private
Definition at line 20 of file UIHangIcon.cs.
    {
        if (!image && (bool)button)
        {
            image = button.image;
        }
        original = image.sprite;
        if ((bool)button && !rightClick)
        {
            button.onClick.AddListener(OnClick);
        }
        Refresh();
    }
References button, image, OnClick(), original, Refresh(), and rightClick.
OnClick()
void UIHangIcon.OnClick () inline
Definition at line 39 of file UIHangIcon.cs.
    {
        if (!EMono.core.IsGameStarted)
        {
            return;
        }
        ActionMode.DefaultMode.Activate();
        if (EMono.ui.contextMenu.isActive)
        {
            EMono.ui.contextMenu.currentMenu.Hide();
            EInput.rightMouse.Consume();
        }
        LayerCollectible layerCollectible = EMono.ui.ToggleLayer<LayerCollectible>();
        if (layerCollectible == null)
        {
            return;
        }
        EMono.ui.hud.hint.Show("h_hang");
        layerCollectible.onClick = delegate(Hoard.Item a)
        {
            EMono.player.hangIcons[id] = a.id;
            if (this != null && base.gameObject != null)
            {
                Refresh();
            }
            return true;
        };
    }
References ActionMode.Activate(), ButtonState.Consume(), EMono.core, ActionMode.DefaultMode, Player.hangIcons, id, Core.IsGameStarted, EMono.player, Refresh(), EInput.rightMouse, and EMono.ui.
Referenced by Awake().
OnClickCorner()
void UIHangIcon.OnClickCorner () inline
Definition at line 34 of file UIHangIcon.cs.
    {
        SE.Play("Ambience/Random/windchime1");
    }
Refresh()
void UIHangIcon.Refresh () inline
Definition at line 68 of file UIHangIcon.cs.
    {
        if (!Core.Instance)
        {
            return;
        }
        if (!EMono.core.IsGameStarted || (windowCorner && !EMono.core.config.ui.cornerHoard))
        {
            image.sprite = (lastCorner = EMono.core.refs.spritesCorner.NextItem(lastCorner));
        }
        else
        {
            string str = ((!windowCorner) ? EMono.player.hangIcons.TryGetValue(id) : EMono.player.hoard.items.RandomItem()?.id);
            if (!str.IsEmpty())
            {
                image.sprite = EMono.player.hoard.GetSprite(str);
            }
        }
        image.SetNativeSize();
    }
References Core.config, EMono.core, CoreConfig.UISetting.cornerHoard, Hoard.GetSprite(), Player.hangIcons, Player.hoard, image, Core.Instance, Core.IsGameStarted, Hoard.items, lastCorner, EMono.player, Core.refs, CoreRef.spritesCorner, CoreConfig.ui, and windowCorner.
Referenced by Awake(), UI.OnActivateZone(), and OnClick().
Member Data Documentation
button
UIButton UIHangIcon.button
Definition at line 8 of file UIHangIcon.cs.
Referenced by Awake().
id
string UIHangIcon.id
Definition at line 10 of file UIHangIcon.cs.
Referenced by OnClick().
image
Image UIHangIcon.image
Definition at line 6 of file UIHangIcon.cs.
Referenced by Awake(), and Refresh().
lastCorner
Sprite UIHangIcon.lastCorner static
Definition at line 18 of file UIHangIcon.cs.
Referenced by Refresh().
original
Sprite UIHangIcon.original private
Definition at line 16 of file UIHangIcon.cs.
Referenced by Awake().
rightClick
bool UIHangIcon.rightClick
Definition at line 12 of file UIHangIcon.cs.
Referenced by Awake().
windowCorner
bool UIHangIcon.windowCorner
Definition at line 14 of file UIHangIcon.cs.
Referenced by Refresh().
The documentation for this class was generated from the following file:
Elin/UIHangIcon.cs