Elin Decompiled Documentation: MsgLine Class Reference
MsgLine Class Reference
Public Member Functions
void Append (string s, FontColor col)
void Append (Sprite s, bool fitLine=true)
void Reset ()
Public Attributes
HorizontalLayoutGroup layout
RectTransform rect
MsgBlock block
Properties
MsgBox.Prefabs prefabs [get]
Private Member Functions
void Awake ()
void AddElement (Component c)
void AddElement (Component c, MsgLine line)
Detailed Description
Definition at line 5 of file MsgLine.cs.
Member Function Documentation
AddElement() [1/2]
void MsgLine.AddElement (Component c) inline private
Definition at line 43 of file MsgLine.cs.
    {
        if (rect.sizeDelta.x > block.box.maxWidth / 3f)
        {
            _ = rect.sizeDelta.x + c.Rect().sizeDelta.x;
            _ = block.box.maxWidth;
        }
    }
References block, MsgBlock.box, MsgBox.maxWidth, and rect.
Referenced by Append().
AddElement() [2/2]
void MsgLine.AddElement (Component c, MsgLine line) inline private
Definition at line 52 of file MsgLine.cs.
    {
        c.transform.SetParent(line.transform, worldPositionStays: false);
        line.layout.RebuildLayout();
    }
References layout.
Append() [1/2]
void MsgLine.Append (Sprite s, bool fitLine = true) inline
Definition at line 29 of file MsgLine.cs.
    {
        Transform transform = PoolManager.Spawn(prefabs.image, layout);
        Image componentInChildren = transform.GetComponentInChildren<Image>();
        componentInChildren.sprite = s;
        if (fitLine)
        {
            RectTransform rectTransform = transform.Rect();
            rectTransform.sizeDelta = new Vector2(rect.sizeDelta.y, rect.sizeDelta.y);
            componentInChildren.transform.Rect().sizeDelta = rectTransform.sizeDelta;
        }
        AddElement(transform);
    }
References AddElement(), layout, prefabs, rect, and PoolManager.Spawn().
Append() [2/2]
void MsgLine.Append (string s, FontColor col) inline
Definition at line 21 of file MsgLine.cs.
    {
        UIText uIText = PoolManager.Spawn(prefabs.text, layout);
        uIText.SetText(s, col);
        uIText.RebuildLayout();
        AddElement(uIText);
    }
References AddElement(), layout, prefabs, UIText.SetText(), and PoolManager.Spawn().
Awake()
void MsgLine.Awake () inline private
Definition at line 16 of file MsgLine.cs.
    {
        rect = this.Rect();
    }
References rect.
Reset()
void MsgLine.Reset () inline
Definition at line 58 of file MsgLine.cs.
    {
        for (int num = base.transform.childCount - 1; num >= 0; num--)
        {
            PoolManager.DespawnOrDestroy(base.transform.GetChild(num));
        }
        this.RebuildLayout();
    }
References PoolManager.DespawnOrDestroy().
Member Data Documentation
block
MsgBlock MsgLine.block
Definition at line 12 of file MsgLine.cs.
Referenced by AddElement().
layout
HorizontalLayoutGroup MsgLine.layout
Definition at line 7 of file MsgLine.cs.
Referenced by AddElement(), and Append().
rect
RectTransform MsgLine.rect
Definition at line 9 of file MsgLine.cs.
Referenced by AddElement(), Append(), and Awake().
Property Documentation
prefabs
MsgBox.Prefabs MsgLine.prefabs get
Definition at line 14 of file MsgLine.cs.
Referenced by Append().
The documentation for this class was generated from the following file:
Elin/Plugins.UI/MsgLine.cs