Elin Decompiled Documentation: LayerGachaResult Class Reference
LayerGachaResult Class Reference
Classes
class Data
Public Types
enum Mode { Chara }
Public Member Functions
void PlayGacha (int n, string id)
void Refresh ()
Public Member Functions inherited from ELayer
override void OnBeforeAddLayer ()
void InitInspector ()
sealed override void Init ()
override void OnAfterAddLayer ()
void TryShowHelp ()
void AddLayerToUI (string id)
void TryShowHint (string _langHint=null)
void TalkHomeMemeber (string id)
void TalkMaid (string id)
override void OnRightClick ()
Static Public Member Functions
static Chara Draw (string id="citizen")
Static Public Member Functions inherited from ELayer
static int rnd (int a)
Public Attributes
ItemGachaResult moldItem
LayoutGroup layout
UIButton buttonGetAll
UIButton buttonDumpAll
Mode mode
List< ItemGachaResult > items = new List<ItemGachaResult>()
Additional Inherited Members
Protected Member Functions inherited from ELayer
sealed override void _Close ()
sealed override void Kill ()
Properties inherited from ELayer
static Core core [get]
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static FactionBranch Branch [get]
static Faction Home [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static CoreConfig config [get]
static GameSetting setting [get]
static ColorProfile Colors [get]
static SourceManager sources [get]
static World world [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
bool IsFloat [get]
virtual string IdHelp [get]
Detailed Description
Definition at line 4 of file LayerGachaResult.cs.
Member Enumeration Documentation
Mode
enum LayerGachaResult.Mode
Enumerator
Chara
Definition at line 6 of file LayerGachaResult.cs.
    {
        Chara
    }
Member Function Documentation
Draw()
static Chara LayerGachaResult.Draw (string id = "citizen") inline static
Definition at line 62 of file LayerGachaResult.cs.
    {
        List<Data> list = new List<Data>();
        int num = 0;
        foreach (SourceChara.Row row in ELayer.sources.charas.rows)
        {
            switch (id)
            {
            case "citizen":
                if (!row.gachaFilter.Contains("resident"))
                {
                    continue;
                }
                break;
            case "livestock":
                if (!row.gachaFilter.Contains("livestock"))
                {
                    continue;
                }
                break;
            case "unique":
                if (!row.gachaFilter.Contains("resident") || row.quality != 4)
                {
                    continue;
                }
                break;
            default:
                if (!row.gachaFilter.Contains("resident") && !row.gachaFilter.Contains("livestock"))
                {
                    continue;
                }
                break;
            }
            int num2 = ((row.chance <= 0) ? 1 : row.chance);
            if (row.LV < 10)
            {
                num2 = num2 * 300 / 100;
            }
            else if (row.LV < 20)
            {
                num2 = num2 * 250 / 100;
            }
            else if (row.LV < 30)
            {
                num2 = num2 * 200 / 100;
            }
            else if (row.LV < 50)
            {
                num2 = num2 * 150 / 100;
            }
            list.Add(new Data
            {
                row = row,
                weight = num2
            });
            num += num2;
        }
        int num3 = ELayer.rnd(num);
        int num4 = 0;
        Data data = list[0];
        foreach (Data item in list)
        {
            num4 += item.weight;
            if (num3 < num4)
            {
                data = item;
                break;
            }
        }
        return CharaGen.Create(data.row.id);
    }
References SourceManager.charas, CharaGen.Create(), item, ELayer.rnd(), and ELayer.sources.
PlayGacha()
void LayerGachaResult.PlayGacha (int n, string id) inline
Definition at line 30 of file LayerGachaResult.cs.
    {
        layout.DestroyChildren();
        items.Clear();
        for (int j = 0; j < n; j++)
        {
            Chara c = Draw(id.Split('_').LastItem());
            ItemGachaResult itemGachaResult = Util.Instantiate(moldItem, layout);
            itemGachaResult.SetChara(c, this);
            items.Add(itemGachaResult);
        }
        ELayer.pc.things.AddCurrency(ELayer.pc, id, -n);
        Msg.Say("playedGacha", n.ToString() ?? "");
        buttonGetAll.onClick.AddListener(delegate
        {
            ELayer.Sound.Play("good");
            items.ForeachReverse(delegate(ItemGachaResult i)
            {
                i.Confirm(add: true);
            });
        });
        buttonDumpAll.onClick.AddListener(delegate
        {
            ELayer.Sound.Play("pay");
            items.ForeachReverse(delegate(ItemGachaResult i)
            {
                i.Confirm(add: false);
            });
        });
        Refresh();
    }
References ThingContainer.AddCurrency(), buttonDumpAll, buttonGetAll, ItemGachaResult.Confirm(), Draw, items, layout, moldItem, ELayer.pc, Refresh(), Msg.Say(), ItemGachaResult.SetChara(), ELayer.Sound, and Card.things.
Refresh()
void LayerGachaResult.Refresh () inline
Definition at line 134 of file LayerGachaResult.cs.
    {
        int num = 0;
        foreach (ItemGachaResult item in items)
        {
            num += item.GetMedal();
        }
        buttonDumpAll.mainText.text = "dumpAll".lang(num.ToString() ?? "");
    }
References item, and items.
Referenced by PlayGacha().
Member Data Documentation
buttonDumpAll
UIButton LayerGachaResult.buttonDumpAll
Definition at line 24 of file LayerGachaResult.cs.
Referenced by PlayGacha().
buttonGetAll
UIButton LayerGachaResult.buttonGetAll
Definition at line 22 of file LayerGachaResult.cs.
Referenced by PlayGacha().
items
List<ItemGachaResult> LayerGachaResult.items = new List<ItemGachaResult>()
Definition at line 28 of file LayerGachaResult.cs.
Referenced by ItemGachaResult.Confirm(), PlayGacha(), and Refresh().
layout
LayoutGroup LayerGachaResult.layout
Definition at line 20 of file LayerGachaResult.cs.
Referenced by PlayGacha().
mode
Mode LayerGachaResult.mode
Definition at line 26 of file LayerGachaResult.cs.
moldItem
ItemGachaResult LayerGachaResult.moldItem
Definition at line 18 of file LayerGachaResult.cs.
Referenced by PlayGacha().
The documentation for this class was generated from the following file:
Elin/LayerGachaResult.cs