Elin Decompiled Documentation: AI_Shopping Class Reference
AI_Shopping Class Reference
Public Member Functions
override IEnumerable< Status > Run ()
Public Member Functions inherited from AIAct
override string ToString ()
override MultiSprite GetStateIcon ()
virtual Point GetDestination ()
AIProgress GetProgress ()
string GetCurrentActionText ()
override bool IsToolValid ()
virtual void OnStart ()
void SetOwner (Chara c)
virtual void OnSetOwner ()
void SetChild (AIAct seq, Func< Status > _onChildFail=null)
void Start ()
override bool Perform ()
Status Restart ()
Status Success (Action action=null)
virtual void OnSuccess ()
bool TryCancel (Card c)
virtual Status Cancel ()
virtual void OnCancel ()
virtual void OnCancelOrSuccess ()
virtual bool CanManualCancel ()
Status KeepRunning ()
void Reset ()
virtual void OnReset ()
Status Tick ()
virtual IEnumerable< Status > Run ()
Status TickChild ()
Status Do (AIAct _seq, Func< Status > _onChildFail=null)
Status DoGotoInteraction (Point pos, Func< Status > _onChildFail=null)
Status DoGoto (Point pos, int dist=0, bool ignoreConnection=false, Func< Status > _onChildFail=null)
Status DoGoto (Card card, Func< Status > _onChildFail=null)
Status DoGoto (Card card, int dist, Func< Status > _onChildFail=null)
Status DoGotoSpot (Card card, Func< Status > _onChildFail=null)
Status DoGoto< T > (Func< Status > _onChildFail=null)
Status DoGotoSpot< T > (Func< Status > _onChildFail=null, bool ignoreAccessType=false)
Status DoGrab (Card card, int num=-1, bool pickHeld=false, Func< Status > _onChildFail=null)
Status DoGrab< T > ()
Status DoProgress ()
Status DoIdle (int repeat=3)
Status DoWait (int count=1)
virtual AIProgress CreateProgress ()
virtual void OnCreateProgress (Progress_Custom p)
virtual bool CanProgress ()
virtual void OnBeforeProgress ()
virtual void OnProgress ()
virtual void OnProgressComplete ()
void SimulateZone (int days)
virtual void OnSimulateZone (int days)
virtual void OnSimulatePosition ()
Public Member Functions inherited from Act
virtual CursorInfo GetCursorIcon (Card c)
virtual MultiSprite GetStateIcon ()
override Sprite GetSprite ()
virtual bool ShowMouseHint (Card c)
virtual bool IsValidTC (Card c)
virtual string GetHintText (string str="")
virtual string GetText (string str="")
virtual string GetTextSmall (Card c)
virtual Color GetActPlanColor ()
virtual bool Perform ()
virtual bool CanPerform ()
bool Perform (Chara _cc, Card _tc=null, Point _tp=null)
bool CanPerform (Chara _cc, Card _tc=null, Point _tp=null)
virtual bool IsToolValid ()
new void SetImage (Image image)
virtual void OnMarkMapHighlights ()
virtual bool ShouldMapHighlight (Point p)
virtual CursorInfo GetCursorIcon (Card c)
virtual MultiSprite GetStateIcon ()
override Sprite GetSprite ()
virtual bool ShowMouseHint (Card c)
virtual bool IsValidTC (Card c)
virtual string GetHintText (string str="")
virtual string GetText (string str="")
virtual string GetTextSmall (Card c)
virtual Color GetActPlanColor ()
virtual bool Perform ()
virtual bool CanPerform ()
bool Perform (Chara _cc, Card _tc=null, Point _tp=null)
bool CanPerform (Chara _cc, Card _tc=null, Point _tp=null)
virtual bool IsToolValid ()
new void SetImage (Image image)
virtual void OnMarkMapHighlights ()
virtual bool ShouldMapHighlight (Point p)
Public Member Functions inherited from Element
virtual SourceElement.Row GetSource ()
virtual int GetSourcePotential (int v)
virtual Sprite GetSprite ()
int GetMaterialSourceValue (Thing t, int v)
virtual int GetSourceValue (int v, int lv, SourceValueType type)
virtual Sprite GetIcon (string suffix="")
int SortVal (bool charaSheet=false)
virtual bool CanLink (ElementContainer owner)
bool HasTag (string tag)
void SetImage (Image i)
virtual string GetDetail ()
bool IsFactionElement (Chara c)
Element GetParent (Card c)
void WriteNote (UINote n, ElementContainer owner=null, Action< UINote > onWriteNote=null)
void WriteNoteWithRef (UINote n, ElementContainer owner, Action< UINote > onWriteNote, Element refEle)
void _WriteNote (UINote n, Chara c, Act act)
void _WriteNote (UINote n, ElementContainer owner, Action< UINote > onWriteNote, bool isRef, bool addHeader=true)
virtual void OnWriteNote (UINote n, ElementContainer owner)
virtual void OnChangeValue ()
void CheckLevelBonus (ElementContainer owner, UINote n=null)
int GetSortVal (UIList.SortMode m)
virtual Act.Cost GetCost (Chara c)
virtual int GetPower (Card c)
virtual void SetTextValue (UIText text)
virtual SourceElement.Row GetSource ()
virtual int GetSourcePotential (int v)
virtual Sprite GetSprite ()
int GetMaterialSourceValue (Thing t, int v)
virtual int GetSourceValue (int v, int lv, SourceValueType type)
virtual Sprite GetIcon (string suffix="")
int SortVal (bool charaSheet=false)
virtual bool CanLink (ElementContainer owner)
bool HasTag (string tag)
void SetImage (Image i)
virtual string GetDetail ()
bool IsFactionElement (Chara c)
Element GetParent (Card c)
void WriteNote (UINote n, ElementContainer owner=null, Action< UINote > onWriteNote=null)
void WriteNoteWithRef (UINote n, ElementContainer owner, Action< UINote > onWriteNote, Element refEle)
void _WriteNote (UINote n, Chara c, Act act)
void _WriteNote (UINote n, ElementContainer owner, Action< UINote > onWriteNote, bool isRef, bool addHeader=true)
virtual void OnWriteNote (UINote n, ElementContainer owner)
virtual void OnChangeValue ()
void CheckLevelBonus (ElementContainer owner, UINote n=null)
int GetSortVal (UIList.SortMode m)
virtual Act.Cost GetCost (Chara c)
virtual int GetPower (Card c)
virtual void SetTextValue (UIText text)
Static Public Member Functions
static bool TryShop (Chara c, bool realtime)
static bool TryRestock (Chara c, bool realtime)
static void SellChara (Chara c)
static void Buy (Chara c, Card dest, bool realtime, Card container)
Static Public Member Functions inherited from Act
static void SetReference (Chara _cc, Card _tc=null, Point _tp=null)
static void SetTool (Thing t)
static void SetReference (Chara _cc, Card _tc=null, Point _tp=null)
static void SetTool (Thing t)
Static Public Member Functions inherited from Element
static string GetName (string alias)
static SourceElement.Row Get (int id)
static Dictionary< int, int > GetElementMap (int[] list)
static Dictionary< int, int > GetElementMap (int[] list, Dictionary< int, int > map)
static SourceElement.Row GetRandomElement (int lv=1)
static Element Create (int id, int v=0)
static Element Create (string id, int v=1)
static int GetId (string alias)
static int GetResistLv (int v)
static int GetResistDamage (int dmg, int v)
static string GetName (string alias)
static SourceElement.Row Get (int id)
static Dictionary< int, int > GetElementMap (int[] list)
static Dictionary< int, int > GetElementMap (int[] list, Dictionary< int, int > map)
static SourceElement.Row GetRandomElement (int lv=1)
static Element Create (int id, int v=0)
static Element Create (string id, int v=1)
static int GetId (string alias)
static int GetResistLv (int v)
static int GetResistDamage (int dmg, int v)
Static Public Member Functions inherited from EClass
static int rnd (int a)
static int curve (int a, int start, int step, int rate=75)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Public Attributes
Card container
Card dest
Public Attributes inherited from AIAct
new Chara owner
Status status
IEnumerator< Status > Enumerator
AIAct child
AIAct parent
byte restartCount
Func< Status > onChildFail
Func< bool > isFail
Public Attributes inherited from Element
SourceElement.Row _source
int id
int vBase
int vExp
int vPotential
int vTempPotential
int vLink
int vSource
int vSourcePotential
ElementContainer owner
Additional Inherited Members
Public Types inherited from AIAct
enum Status { Running , Fail , Success }
Public Types inherited from Act
enum CostType {
None , MP , SP , None ,
MP , SP
}
enum CostType {
None , MP , SP , None ,
MP , SP
}
Static Public Attributes inherited from Act
static Chara CC
static Card TC
static Point TP = new Point()
static Thing TOOL
static int powerMod = 100
static bool forcePt
Static Public Attributes inherited from Element
const int Div = 5
static Element Void = new Element()
static int[] List_MainAttributes
static int[] List_MainAttributesMajor
static int[] List_Body
static int[] List_Mind
static List< SourceElement.Row > ListElements = new List<SourceElement.Row>()
static List< SourceElement.Row > ListAttackElements = new List<SourceElement.Row>()
Static Public Attributes inherited from EClass
static Core core
Static Package Functions inherited from Element
static string< _WriteNote > g__Calc (ref Element.<>c__DisplayClass103_0 A_0)
Properties inherited from AIAct
virtual bool IsRunning [get]
bool IsChildRunning [get]
bool IsMoveAI [get]
virtual int MaxRestart [get]
virtual new string Name [get]
virtual MultiSprite stateIcon [get]
virtual Sprite actionIcon [get]
virtual bool IsNoGoal [get]
virtual bool IsAutoTurn [get]
virtual bool IsIdle [get]
virtual bool PushChara [get]
virtual int MaxProgress [get]
virtual bool ShowProgress [get]
virtual bool UseTurbo [get]
virtual int CurrentProgress [get]
virtual bool ShowCursor [get]
virtual bool CancelWhenDamaged [get]
virtual bool CancelWhenMoved [get]
virtual bool InformCancel [get]
virtual Thing RenderThing [get]
AIAct Current [get]
override bool IsAct [get]
override bool ShowPotential [get]
override bool UsePotential [get]
override bool ShowRelativeAttribute [get]
virtual bool HasProgress [get]
Properties inherited from Act
override bool ShowPotential [get]
override bool UsePotential [get]
override bool ShowRelativeAttribute [get]
virtual CursorInfo CursorIcon [get]
virtual string ID [get]
virtual bool IsAct [get]
virtual bool WillEndTurn [get]
virtual bool CloseLayers [get]
virtual int LeftHand [get]
virtual int RightHand [get]
virtual int ElementPowerMod [get]
virtual bool ShowMapHighlight [get]
virtual bool ShowMapHighlightBlock [get]
virtual bool PickHeldOnStart [get]
virtual bool DropHeldOnStart [get]
virtual bool CanPressRepeat [get]
virtual bool CanAutofire [get]
virtual bool ResetAxis [get]
virtual bool RequireTool [get]
virtual bool IsHostileAct [get]
virtual bool HideRightInfo [get]
virtual bool HaveLongPressAction [get]
virtual float Radius [get]
virtual int PerformDistance [get]
virtual int MaxRadius [get]
virtual TargetType TargetType [get]
virtual bool LocalAct [get]
virtual bool CanRapidFire [get]
virtual float RapidDelay [get]
virtual bool ShowAuto [get]
virtual bool IsCrime [get]
Properties inherited from Element
SourceElement.Row source [get]
virtual int DisplayValue [get]
virtual int MinValue [get]
int Value [get]
int ValueWithoutLink [get]
virtual int MinPotential [get]
int Potential [get]
virtual bool CanGainExp [get]
bool IsFlag [get]
virtual string Name [get]
virtual string FullName [get]
virtual int ExpToNext [get]
virtual bool UseExpMod [get]
virtual int CostTrain [get]
virtual int CostLearn [get]
virtual bool ShowXP [get]
virtual bool ShowMsgOnValueChanged [get]
virtual bool ShowValue [get]
virtual bool ShowPotential [get]
virtual bool UsePotential [get]
virtual bool PotentialAsStock [get]
virtual bool ShowRelativeAttribute [get]
virtual bool ShowBonuses [get]
virtual string ShortName [get]
bool IsGlobalElement [get]
bool IsFactionWideElement [get]
bool IsPartyWideElement [get]
virtual bool ShowEncNumber [get]
bool IsTrait [get]
bool IsFoodTrait [get]
bool IsFoodTraitMain [get]
bool IsMainAttribute [get]
Act act [get]
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Detailed Description
Definition at line 4 of file AI_Shopping.cs.
Member Function Documentation
Buy()
static void AI_Shopping.Buy (Chara c, Card dest, bool realtime, Card container) inline static
Definition at line 149 of file AI_Shopping.cs.
    {
        Point point = dest.pos.Copy();
        int price = dest.GetPrice(CurrencyType.Money, sell: true, PriceType.PlayerShop);
        if ((dest.isThing && (dest.isDestroyed || dest.Thing.IsSharedContainer)) || (container == null && !dest.isSale) || (container != null && container.c_lockLv != 0))
        {
            return;
        }
        Card card = (dest.isChara ? dest : dest.Split(1));
        EClass.Branch.incomeShop += price;
        card.isSale = false;
        if (card == dest)
        {
            EClass._map.props.sales.Remove(card);
        }
        if (realtime)
        {
            c.Talk("shop_buy");
            c.PlaySound("money");
            Msg.alwaysVisible = true;
            Msg.Say("shop_buy", c, card, Lang._currency(price, "money"));
            if (card.isThing)
            {
                c.AddCard(card);
                c.c_allowance -= price;
                if (!c.TryUse(card.Thing))
                {
                    card.ModNum(-1);
                }
            }
            else
            {
                SellChara(card.Chara);
            }
        }
        else if (card.isThing)
        {
            card.ModNum(-1);
        }
        else
        {
            SellChara(card.Chara);
        }
        if (card.isStolen || card.isChara)
        {
            Guild.Thief.AddContribution((int)Mathf.Sqrt(price) / 2);
        }
        if (container != null)
        {
            if (container.things.Count == 0)
            {
                container.isSale = false;
                EClass._map.props.sales.Remove(container);
            }
        }
        else if (!dest.ExistsOnMap && dest.isThing)
        {
            Thing thing = ThingGen.Create("tag_sell");
            thing.isOn = true;
            thing.SetStr(11, dest.category.id);
            EClass._zone.AddCard(thing, point).Install();
        }
        EClass.Branch.Log("shop_buy", c, card, Lang._currency(price, "money"));
    }
References EClass._map, EClass._zone, Card.AddCard(), Zone.AddCard(), Faction.AddContribution(), EClass.Branch, Card.c_lockLv, Card.category, Card.Chara, container, Point.Copy(), ThingGen.Create(), dest, Card.ExistsOnMap, Card.GetPrice(), Card.Install(), Card.isChara, Card.isDestroyed, Card.isSale, Thing.IsSharedContainer, Card.isStolen, Card.isThing, FactionBranch.Log(), Card.ModNum(), Card.PlaySound(), Card.pos, Map.props, PropsManager.sales, Msg.Say(), SellChara(), BaseCard.SetStr(), Card.Split(), Card.Talk(), Guild.Thief, Card.Thing, Card.things, and Chara.TryUse().
Referenced by Run(), and TryShop().
Run()
override IEnumerable< Status > AI_Shopping.Run () inline virtual
Reimplemented from AIAct.
Definition at line 127 of file AI_Shopping.cs.
    {
        Card _dest = container ?? dest;
        if (_dest.ExistsOnMap)
        {
            yield return DoGoto(_dest.pos, 1);
        }
        if (!_dest.ExistsOnMap || !_dest.isSale)
        {
            yield return Success();
        }
        Buy(owner, dest, realtime: true, container);
        yield return Success();
    }
References Buy(), container, dest, AIAct.DoGoto(), Card.ExistsOnMap, Card.isSale, AIAct.owner, Card.pos, and AIAct.Success.
SellChara()
static void AI_Shopping.SellChara (Chara c) inline static
Definition at line 142 of file AI_Shopping.cs.
    {
        Msg.Say("sell_resident", c);
        c.homeBranch.BanishMember(c, sell: true);
        EClass.player.ModKarma(-1);
    }
References FactionBranch.BanishMember(), Chara.homeBranch, Player.ModKarma(), EClass.player, and Msg.Say().
Referenced by Buy().
TryRestock()
static bool AI_Shopping.TryRestock (Chara c, bool realtime) inline static
Definition at line 94 of file AI_Shopping.cs.
    {
        for (int i = 0; i < (realtime ? 1 : 10); i++)
        {
            bool flag = false;
            foreach (Thing thing2 in EClass._map.things)
            {
                if (EClass.rnd(2) == 0 || !thing2.IsInstalled || !(thing2.trait is TraitSalesTag { IsOn: not false }) || thing2.GetStr(11).IsEmpty())
                {
                    continue;
                }
                Thing thing = EClass._zone.TryGetRestock<TraitSpotStock>(thing2.GetStr(11));
                if (thing != null)
                {
                    if (realtime)
                    {
                        thing2.PlaySound("restock");
                    }
                    thing2.Destroy();
                    thing.isSale = true;
                    EClass._zone.AddCard(thing, thing2.pos).Install();
                    flag = true;
                    break;
                }
            }
            if (!flag)
            {
                break;
            }
        }
        return false;
    }
References EClass._map, EClass._zone, Zone.AddCard(), Card.Destroy(), BaseCard.GetStr(), Card.Install(), IsOn, Card.PlaySound(), Card.pos, EClass.rnd(), and Map.things.
Referenced by AI_Idle.Run().
TryShop()
static bool AI_Shopping.TryShop (Chara c, bool realtime) inline static
Definition at line 10 of file AI_Shopping.cs.
    {
        if (c.memberType != FactionMemberType.Guest || !EClass._zone.IsPCFaction || EClass._map.props.sales.Count == 0)
        {
            return false;
        }
        Card card = EClass._map.props.sales.RandomItem();
        int c_allowance = c.c_allowance;
        if (!EClass.debug.enable && c_allowance <= 0)
        {
            return false;
        }
        bool flag = card.IsContainer && card.things.Count > 0;
        List<Card> list = new List<Card>();
        if (flag)
        {
            foreach (Thing thing in card.things)
            {
                if (TraitSalesTag.CanTagSale(thing, insideContainer: true))
                {
                    list.Add(thing);
                }
            }
        }
        else
        {
            list.Add(card);
        }
        foreach (Card item in list)
        {
            int num = 25;
            int price = item.GetPrice(CurrencyType.Money, sell: true, PriceType.PlayerShop);
            if (price >= c_allowance)
            {
                num = num * 10 * price / c_allowance;
            }
            if (price >= 10000)
            {
                num *= 15;
            }
            else if (price >= 5000)
            {
                num *= 10;
            }
            else if (price >= 1000)
            {
                num *= 6;
            }
            else if (price >= 200)
            {
                num *= 3;
            }
            if (EClass.Branch != null)
            {
                if (EClass.Branch.policies.IsActive(2817))
                {
                    num = num * (300 + EClass.Branch.Evalue(2817)) / 100;
                }
                if (EClass.Branch.policies.IsActive(2816))
                {
                    num = num * (1000 + EClass.Branch.Evalue(2816) * 2) / 100;
                }
            }
            if (!realtime)
            {
                num /= 4;
            }
            if (EClass.debug.enable || EClass.rnd(num + 1) == 0)
            {
                if (realtime)
                {
                    c.SetAI(new AI_Shopping
                    {
                        container = (flag ? card : null),
                        dest = item
                    });
                    return true;
                }
                Buy(c, item, realtime: false, flag ? card : null);
            }
        }
        return false;
    }
References EClass._map, EClass._zone, EClass.Branch, Buy(), Card.c_allowance, TraitSalesTag.CanTagSale(), container, EClass.debug, dest, CoreDebug.enable, FactionBranch.Evalue(), Card.GetPrice(), PolicyManager.IsActive(), Zone.IsPCFaction, Chara.memberType, FactionBranch.policies, Map.props, EClass.rnd(), PropsManager.sales, and Card.things.
Referenced by AI_Idle.Run().
Member Data Documentation
container
Card AI_Shopping.container
Definition at line 6 of file AI_Shopping.cs.
Referenced by Buy(), Run(), and TryShop().
dest
Card AI_Shopping.dest
Definition at line 8 of file AI_Shopping.cs.
Referenced by Buy(), Run(), and TryShop().
The documentation for this class was generated from the following file:
Elin/AI_Shopping.cs