Elin Decompiled Documentation: ContentGallery Class Reference
ContentGallery Class Reference
Classes
class Page
Public Member Functions
override void OnSwitchContent (int idTab)
void Refresh ()
void OnClickHelp ()
void ToggleMode ()
Public Member Functions inherited from UIContent
virtual void OnSwitchContent (int idTab)
virtual void OnInstantiate ()
Public Member Functions inherited from UINote
void Clear ()
void Build ()
void Space (int sizeY=0, int sizeX=1)
UINote AddNote (string id)
UIItem AddHeader (string text, Sprite sprite=null)
UIItem AddHeaderCard (string text, Sprite sprite=null)
UIItem AddHeaderTopic (string text, Sprite sprite=null)
UIItem AddHeader (string id, string text, Sprite sprite=null)
UIItem AddText (string text, FontColor color=FontColor.DontChange)
UIItem AddText (string id, string text, FontColor color=FontColor.DontChange)
UIItem AddText (string id, string text, Color color)
UIItem AddItem (string id)
UIItem AddTopic (string id, string text, string value=null)
UIItem AddTopic (string text, string value=null)
void AddImage (Sprite sprite)
void AddImage (string idFile)
UIButton AddButton (string text, Action onClick)
UIButton AddButtonLink (string text, string url)
UIDropdown AddDropdown (string id="DropdownDefault")
UIButton AddToggle (string idLang="", bool isOn=false, Action< bool > action=null)
Transform AddPrefab (string path)
T AddExtra< T > (string path)
Public Attributes
Transform transBig
Image imageBig
UIBook book
UIText textCollected
GridLayoutGroup[] grids
Vector2[] gridSize
Public Attributes inherited from UINote
RectTransform target
UINoteProfile prof
SkinType skinType
string idDefaultText
LayoutGroup layout
RectTransform cur
bool extraRebuild
Static Public Attributes
static int lastPage
static bool listMode
Private Member Functions
void OnDestroy ()
Private Attributes
bool first = true
Detailed Description
Definition at line 6 of file ContentGallery.cs.
Member Function Documentation
OnClickHelp()
void ContentGallery.OnClickHelp () inline
Definition at line 102 of file ContentGallery.cs.
    {
        LayerHelp.Toggle("other", "gallery");
    }
References LayerHelp.Toggle().
OnDestroy()
void ContentGallery.OnDestroy () inline private
Definition at line 115 of file ContentGallery.cs.
    {
        lastPage = book.currentPage;
    }
References book, UIBook.currentPage, and lastPage.
OnSwitchContent()
override void ContentGallery.OnSwitchContent (int idTab) inline virtual
Reimplemented from UIContent.
Definition at line 55 of file ContentGallery.cs.
    {
        if (!first)
        {
            return;
        }
        if (EClass.debug.allArt)
        {
            EClass.player.sketches.Clear();
            foreach (int key in EClass.core.refs.dictSketches.Keys)
            {
                EClass.player.sketches.Add(key);
            }
        }
        Refresh();
        first = false;
    }
References CoreDebug.allArt, EClass.core, EClass.debug, CoreRef.dictSketches, first, UDictionary< TKey, TValue >.Keys, EClass.player, Refresh(), Core.refs, and Player.sketches.
Refresh()
void ContentGallery.Refresh () inline
Definition at line 73 of file ContentGallery.cs.
    {
        book.pages.Clear();
        GridLayoutGroup[] array = grids;
        for (int i = 0; i < array.Length; i++)
        {
            array[i].cellSize = gridSize[listMode ? 1 : 0];
        }
        Page page = new Page();
        List<int> list = EClass.player.sketches.ToList();
        list.Sort((int a, int b) => a - b);
        foreach (int item in list)
        {
            page.ids.Add(item.ToString() ?? "");
            if (page.ids.Count >= (listMode ? 8 : 2))
            {
                book.AddPage(page);
                page = new Page();
            }
        }
        if (page.ids.Count > 0)
        {
            book.AddPage(page);
        }
        book.currentPage = lastPage;
        book.Show();
        textCollected.SetText("sketch_collected".lang((list.Count * 100 / EClass.core.refs.dictSketches.Count()).ToString() ?? ""));
    }
References UIBook.AddPage(), book, EClass.core, UDictionary< TKey, TValue >.Count, CoreRef.dictSketches, grids, gridSize, item, lastPage, listMode, UIBook.pages, EClass.player, Core.refs, UIText.SetText(), UIBook.Show(), Player.sketches, and textCollected.
Referenced by OnSwitchContent(), and ToggleMode().
ToggleMode()
void ContentGallery.ToggleMode () inline
Definition at line 107 of file ContentGallery.cs.
    {
        listMode = !listMode;
        lastPage = (listMode ? (book.currentPage / 4) : (book.currentPage * 4));
        SE.Tab();
        Refresh();
    }
References book, UIBook.currentPage, lastPage, listMode, and Refresh().
Member Data Documentation
book
UIBook ContentGallery.book
Definition at line 45 of file ContentGallery.cs.
Referenced by OnDestroy(), Refresh(), and ToggleMode().
first
bool ContentGallery.first = true private
Definition at line 53 of file ContentGallery.cs.
Referenced by OnSwitchContent().
grids
GridLayoutGroup [] ContentGallery.grids
Definition at line 49 of file ContentGallery.cs.
Referenced by Refresh().
gridSize
Vector2 [] ContentGallery.gridSize
Definition at line 51 of file ContentGallery.cs.
Referenced by Refresh().
imageBig
Image ContentGallery.imageBig
Definition at line 43 of file ContentGallery.cs.
lastPage
int ContentGallery.lastPage static
Definition at line 37 of file ContentGallery.cs.
Referenced by OnDestroy(), Refresh(), and ToggleMode().
listMode
bool ContentGallery.listMode static
Definition at line 39 of file ContentGallery.cs.
Referenced by Refresh(), and ToggleMode().
textCollected
UIText ContentGallery.textCollected
Definition at line 47 of file ContentGallery.cs.
Referenced by Refresh().
transBig
Transform ContentGallery.transBig
Definition at line 41 of file ContentGallery.cs.
The documentation for this class was generated from the following file:
Elin/ContentGallery.cs