Elin Decompiled Documentation: HotItemEQSet Class Reference
HotItemEQSet Class Reference
Classes
class Item
Public Member Functions
HotItemEQSet Register ()
override void Perform ()
override void OnShowContextMenu (UIContextMenu m)
Public Member Functions inherited from HotAction
override void OnClick (ButtonHotItem b, Hotbar h)
virtual void Perform ()
override void OnShowContextMenu (UIContextMenu m)
Public Member Functions inherited from HotItem
string TextHotkey ()
virtual void OnClick (ButtonHotItem b, Hotbar h)
virtual void OnRightClick (ButtonHotItem b)
virtual bool CanAutoFire (Chara tg)
virtual void OnSetCurrentItem ()
virtual void OnUnsetCurrentItem ()
virtual void OnUnselect ()
virtual void SetImage (Image icon)
virtual bool TrySetAct (ActPlan p)
virtual void OnMarkMapHighlights ()
virtual void OnRenderTile (Point point, HitResult result, int dir)
Public Member Functions inherited from UIButton.Item
virtual Sprite GetSprite ()
virtual Sprite GetSprite (bool highlight)
virtual bool ShouldHighlight ()
virtual void OnAddedToBar ()
virtual void OnShowContextMenu (UIContextMenu m)
virtual void OnHover (UIButton b)
virtual void OnClick (UIButton b)
virtual void OnSetItem (UIButton b)
virtual void SetSubText (UIText t)
Public Attributes
List< int > ids = new List<int>()
Public Attributes inherited from HotAction
int _bgColor
string text
Public Attributes inherited from HotItem
ButtonHotItem button
Hotbar hotbar
bool disabled
Public Attributes inherited from UIButton.Item
bool always
Properties
override string Id [get]
override bool CanChangeIconColor [get]
override string TextTip [get]
Properties inherited from HotAction
Color bgColor [get, set]
override Color SpriteColor [get]
virtual string Id [get]
virtual bool CanChangeIconColor [get]
virtual bool CanName [get]
override string Name [get]
override string pathSprite [get]
Properties inherited from HotItem
override Sprite SpriteHighlight [get]
override bool IsSelectable [get]
override string TextTip [get]
virtual Thing RenderThing [get]
virtual Thing Thing [get]
virtual Thing Tool [get]
virtual bool IsTool [get]
virtual bool LookAtMouse [get]
virtual bool IsGameAction [get]
virtual bool UseUIObjMaterial [get]
Properties inherited from UIButton.Item
virtual string TextTip [get]
virtual string Name [get]
virtual Sprite SpriteHighlight [get]
virtual string pathSprite [get]
virtual bool IsSelectable [get]
virtual bool AdjustImageSize [get]
virtual bool UseIconForHighlight [get]
virtual bool KeepVisibleWhenHighlighted [get]
virtual Color SpriteColor [get]
virtual Vector3 SpriteScale [get]
virtual bool Hidden [get]
virtual Transition Transition [get]
Detailed Description
Definition at line 5 of file HotItemEQSet.cs.
Member Function Documentation
OnShowContextMenu()
override void HotItemEQSet.OnShowContextMenu (UIContextMenu m) inline virtual
Reimplemented from HotAction.
Definition at line 111 of file HotItemEQSet.cs.
    {
        base.OnShowContextMenu(m);
        m.AddButton("updateEQ", delegate
        {
            Register();
        });
    }
References UIContextMenu.AddButton(), and Register().
Perform()
override void HotItemEQSet.Perform () inline virtual
Reimplemented from HotAction.
Definition at line 52 of file HotItemEQSet.cs.
    {
        for (int j = 0; j < 2; j++)
        {
            Dictionary<int, Thing> dictionary = new Dictionary<int, Thing>();
            foreach (BodySlot slot2 in EClass.pc.body.slots)
            {
                if (slot2.elementId != 44 && slot2.thing != null && slot2.thing.blessedState >= BlessedState.Normal)
                {
                    dictionary.Add(slot2.thing.c_equippedSlot - 1, slot2.thing);
                    EClass.pc.body.Unequip(slot2.thing, refresh: false);
                }
            }
            Card card = null;
            foreach (int i in ids)
            {
                Thing thing = EClass.pc.things.Find((Thing t) => t.uid == i && !t.isEquipped);
                if (thing == null)
                {
                    continue;
                }
                BodySlot slot = EClass.pc.body.GetSlot(thing, onlyEmpty: true);
                if (slot == null || thing == slot.thing)
                {
                    continue;
                }
                Card parentCard = thing.parentCard;
                int invX = thing.invX;
                int invY = thing.invY;
                EClass.pc.body.Equip(thing, slot, msg: false);
                if (dictionary.ContainsKey(slot.index))
                {
                    Thing thing2 = dictionary[slot.index];
                    if (thing2.uid != thing.uid)
                    {
                        parentCard.AddThing(thing2);
                        card = parentCard;
                        thing2.invX = invX;
                        thing2.invY = invY;
                        dictionary.Remove(slot.index);
                    }
                }
            }
            if (card == null)
            {
                continue;
            }
            foreach (Thing value in dictionary.Values)
            {
                if (!value.isEquipped && !card.things.IsFull(value))
                {
                    card.AddThing(value);
                }
            }
        }
        SE.Equip();
        LayerChara.Refresh();
    }
References Card.AddThing(), Card.blessedState, Chara.body, Card.c_equippedSlot, card, BodySlot.elementId, CharaBody.Equip(), ThingContainer.Find(), CharaBody.GetSlot(), ids, BodySlot.index, Card.invX, Card.invY, Thing.isEquipped, Card.parentCard, EClass.pc, LayerChara.Refresh(), CharaBody.slots, BodySlot.thing, Card.things, Card.uid, and CharaBody.Unequip().
Register()
HotItemEQSet HotItemEQSet.Register () inline
Definition at line 38 of file HotItemEQSet.cs.
    {
        ids.Clear();
        foreach (BodySlot slot in EClass.pc.body.slots)
        {
            if (slot.elementId != 44 && slot.thing != null)
            {
                ids.Add(slot.thing.uid);
            }
        }
        SE.Equip();
        return this;
    }
References Chara.body, BodySlot.elementId, ids, EClass.pc, CharaBody.slots, BodySlot.thing, and Card.uid.
Referenced by OnShowContextMenu().
Member Data Documentation
ids
List<int> HotItemEQSet.ids = new List<int>()
Definition at line 17 of file HotItemEQSet.cs.
Referenced by Perform(), and Register().
Property Documentation
CanChangeIconColor
override bool HotItemEQSet.CanChangeIconColor get
Definition at line 21 of file HotItemEQSet.cs.
Id
override string HotItemEQSet.Id get
Definition at line 19 of file HotItemEQSet.cs.
TextTip
override string HotItemEQSet.TextTip get
Definition at line 23 of file HotItemEQSet.cs.
    {
        get
        {
            string text = base.text.IsEmpty("EQSet".lang()) + TextHotkey() + Environment.NewLine;
            foreach (int i in ids)
            {
                Thing thing = EClass.pc.things.Find((Thing t) => t.uid == i);
                text += ((thing == null) ? "missingEQ".lang() : thing.Name);
                text += Environment.NewLine;
            }
            return text.TrimEnd(Environment.NewLine.ToCharArray());
        }
    }
The documentation for this class was generated from the following file:
Elin/HotItemEQSet.cs