Elin Decompiled Documentation: WidgetFeed Class Reference
WidgetFeed Class Reference
Classes
class Extra
Public Member Functions
override object CreateExtra ()
override void OnActivate ()
override void OnDeactivate ()
void Talk (Card c, string id)
PopItem SayRaw (Card c, string text)
void SayRaw (string idPortrait, string text, string _idPop)
void Nerun (string text, string idPortrait="UN_nerun")
void System (string text)
override void OnSetContextMenu (UIContextMenu m)
Public Member Functions inherited from Widget
void Test ()
bool IsInRightMode ()
void Activate ()
void RefreshOrder ()
virtual void OnActivate ()
virtual object CreateExtra ()
void Deactivate ()
virtual void OnDeactivate ()
void Close ()
void Reactivate ()
virtual void OnManagerActivate ()
virtual void OnManagerDeactivate ()
void SetAnchor (RectPosition p)
void SetPivot (RectPosition p)
virtual void OnChangePivot ()
void UpdateConfig ()
virtual void OnUpdateConfig ()
void ClampToScreen ()
virtual void OnChangeResolution ()
void OnChangePosition ()
virtual void OnChangeActionMode ()
virtual void OnFlip ()
bool IsAlignTop ()
Layer AddLayer (Layer l, Transform trans)
void RefreshTipPivotPosition ()
SkinSet GetSkin ()
SkinConfig GetSkinConfig ()
void SetSkin (int id, int v=0)
void TestSkin ()
virtual void ApplySkin ()
virtual void OnApplySkin ()
void InstantiateDeco (SkinDeco deco)
void AddDeco (SkinDeco deco)
void RemoveDeco (SkinDeco deco)
virtual bool CanShowContextMenu ()
void ShowContextMenu ()
void SetBaseContextMenu (UIContextMenu m)
virtual void OnSetContextMenu (UIContextMenu m)
void SetGridContextMenu (UIContextMenu m)
void SoundActivate ()
void OnChangeResolution ()
SkinSet GetSkin ()
SkinConfig GetSkinConfig ()
Public Attributes
GameObject goDummy
PopManager pop
string[] idPop
string idPopGod
string idPopSystem
Public Attributes inherited from Widget
Image imageBG
SoundData soundActivate
UIDragPanel dragPanel
RectTransform tipPivotLeft
RectTransform tipPivotRight
Static Public Attributes
static WidgetFeed Instance
Static Public Attributes inherited from EMono
static Core core
Properties
static bool Intercept [get]
Extra extra [get]
override bool AlwaysTop [get]
override bool ShowStyleMenu [get]
bool IgnoreFeed [get]
Properties inherited from Widget
string ID [get]
Config config [get]
SkinRoot skinRoot [get]
bool IsSealed [get]
virtual bool ShowStyleMenu [get]
virtual bool AlwaysTop [get]
virtual bool IsStaticPosition [get]
virtual bool AlwaysBottom [get]
virtual Type SetSiblingAfter [get]
virtual bool ShowInBuildMode [get]
virtual bool RightClickToClose [get]
virtual bool AllowRightClickToClose [get]
Properties inherited from EMono
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SoundManager Sound [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static CoreDebug debug [get]
Additional Inherited Members
Public Types inherited from Widget
enum WidgetType { Default , ZoomMenu }
enum State { Active , Inactive }
Static Public Member Functions inherited from EMono
static int rnd (int a)
Protected Member Functions inherited from Widget
void ClampToScreenEnsured (Component c, Vector2 anchoredPos)
void ClampToScreen (RectTransform rect, float margin=10f)
Protected Attributes inherited from Widget
bool flip
Detailed Description
Definition at line 3 of file WidgetFeed.cs.
Member Function Documentation
CreateExtra()
override object WidgetFeed.CreateExtra () inline virtual
Reimplemented from Widget.
Definition at line 56 of file WidgetFeed.cs.
    {
        return new Extra();
    }
Nerun()
void WidgetFeed.Nerun (string text, string idPortrait = "UN_nerun") inline
Definition at line 93 of file WidgetFeed.cs.
    {
        SayRaw(idPortrait, text, null);
    }
References SayRaw().
Referenced by LayerInventory.CreateContainer(), Msg.Nerun(), Msg.SayHomeMember(), and CoreDebug.UpdateInput().
OnActivate()
override void WidgetFeed.OnActivate () inline virtual
Reimplemented from Widget.
Definition at line 61 of file WidgetFeed.cs.
    {
        Instance = this;
        System("Elin's Inn version " + EMono.core.version.GetText());
        System("Welcome, wanderer! Press '?' for help.");
        WidgetMainText.Refresh();
    }
References EMono.core, Version.GetText(), Instance, WidgetMainText.Refresh(), System(), and BaseCore.version.
OnDeactivate()
override void WidgetFeed.OnDeactivate () inline virtual
Reimplemented from Widget.
Definition at line 69 of file WidgetFeed.cs.
    {
        Instance = null;
        WidgetMainText.Refresh();
    }
References Instance, and WidgetMainText.Refresh().
OnSetContextMenu()
override void WidgetFeed.OnSetContextMenu (UIContextMenu m) inline virtual
Reimplemented from Widget.
Definition at line 106 of file WidgetFeed.cs.
    {
        m.AddChild("setting").AddSlider("style", (float a) => idPop[(int)a], extra.style, delegate(float a)
        {
            extra.style = (int)a;
            Msg.Nerun("this");
        }, 0f, idPop.Length - 1, isInt: true);
        SetBaseContextMenu(m);
    }
References UIContextMenu.AddChild(), UIContextMenu.AddSlider(), extra, idPop, Msg.Nerun(), Widget.SetBaseContextMenu(), and WidgetFeed.Extra.style.
SayRaw() [1/2]
PopItem WidgetFeed.SayRaw (Card c, string text) inline
Definition at line 81 of file WidgetFeed.cs.
    {
        PopItemText popItemText = pop.PopText(text, null, idPop[extra.style]);
        popItemText.GetComponentInChildren<Portrait>().SetChara(c as Chara);
        return popItemText;
    }
References extra, idPop, pop, PopManager.PopText(), and WidgetFeed.Extra.style.
Referenced by Nerun(), Msg.SayPic(), Msg.Talk(), and Talk().
SayRaw() [2/2]
void WidgetFeed.SayRaw (string idPortrait, string text, string _idPop) inline
Definition at line 88 of file WidgetFeed.cs.
    {
        pop.PopText(text, null, _idPop.IsEmpty(idPop[extra.style])).GetComponentInChildren<Portrait>().SetPortrait(idPortrait);
    }
References extra, idPop, pop, PopManager.PopText(), and WidgetFeed.Extra.style.
System()
void WidgetFeed.System (string text) inline
Definition at line 98 of file WidgetFeed.cs.
    {
        if (extra.intercept)
        {
            pop.PopText(text, null, idPopSystem, Msg.currentColor);
        }
    }
References Msg.currentColor, extra, idPopSystem, WidgetFeed.Extra.intercept, pop, and PopManager.PopText().
Referenced by OnActivate(), and Msg.SayRaw().
Talk()
void WidgetFeed.Talk (Card c, string id) inline
Definition at line 75 of file WidgetFeed.cs.
    {
        string text = GameLang.Convert(c.GetTalkText(id, stripPun: true));
        SayRaw(c, text);
    }
References GameLang.Convert(), Card.GetTalkText(), and SayRaw().
Member Data Documentation
goDummy
GameObject WidgetFeed.goDummy
Definition at line 16 of file WidgetFeed.cs.
idPop
string [] WidgetFeed.idPop
Definition at line 20 of file WidgetFeed.cs.
Referenced by OnSetContextMenu(), and SayRaw().
idPopGod
string WidgetFeed.idPopGod
Definition at line 22 of file WidgetFeed.cs.
idPopSystem
string WidgetFeed.idPopSystem
Definition at line 24 of file WidgetFeed.cs.
Referenced by System().
Instance
WidgetFeed WidgetFeed.Instance static
Definition at line 14 of file WidgetFeed.cs.
Referenced by WidgetMainText._ToggleLog(), UI.CheckWindowOrder(), LayerInventory.CreateContainer(), ELayer.Kill(), OnActivate(), OnDeactivate(), and CoreDebug.UpdateInput().
pop
PopManager WidgetFeed.pop
Definition at line 18 of file WidgetFeed.cs.
Referenced by WidgetMainText._ToggleLog(), ELayer.Kill(), SayRaw(), and System().
Property Documentation
AlwaysTop
override bool WidgetFeed.AlwaysTop get
Definition at line 40 of file WidgetFeed.cs.
extra
Extra WidgetFeed.extra get
Definition at line 38 of file WidgetFeed.cs.
Referenced by OnSetContextMenu(), SayRaw(), and System().
IgnoreFeed
bool WidgetFeed.IgnoreFeed get
Definition at line 44 of file WidgetFeed.cs.
    {
        get
        {
            if ((bool)WidgetMainText.Instance)
            {
                return WidgetMainText.Instance.box.isShowingLog;
            }
            return false;
        }
    }
Intercept
bool WidgetFeed.Intercept static get
Definition at line 26 of file WidgetFeed.cs.
    {
        get
        {
            if ((bool)Instance)
            {
                return Instance.extra.intercept;
            }
            return false;
        }
    }
Referenced by WidgetMainText._Refresh().
ShowStyleMenu
override bool WidgetFeed.ShowStyleMenu get
Definition at line 42 of file WidgetFeed.cs.
The documentation for this class was generated from the following file:
Elin/WidgetFeed.cs