Elin Decompiled Documentation: GenRoom Class Reference
GenRoom Class Reference
Public Member Functions
void Init (Dungen.Room room)
void Init (int _x, int _y, int w, int h)
void Populate ()
void SpawnMob (Point p)
virtual void OnPopulate ()
void Fill ()
void SetRandomPoint (Action< Point > action)
void SetRandomPointCentered (Action< Point > action)
Public Member Functions inherited from GenBounds
void SetFloor (BiomeProfile.Tile t, int x, int z)
void SetBlock (BiomeProfile.Tile t, int x, int z)
void SetFloor (int x, int z, int idMat, int idFloor, int direction=0)
void SetBlock (int x, int z, int idMat, int idBlock, int direction=0)
bool IsEmpty ()
List< Point > ListEmptyPoint ()
GenBounds GetBounds (int w, int h, bool ignoreBlock)
GenBounds GetBounds (Map map, Zone zone, int x, int y, int width, int height, int dw, int dh, bool ignoreBlock)
PartialMap TryAddMapPiece (MapPiece.Type type=MapPiece.Type.Any, float ruin=-1f, string tags=null, Action< PartialMap, GenBounds > onCreate=null)
Public Attributes
BiomeProfile.TileGroup group
MapGenDungen gen
Public Attributes inherited from GenBounds
Map map
Zone zone
int Size
int x
int y
int width
int height
int marginPartial
Func< Cell, bool > FuncCheckEmpty
Static Public Attributes
static int[] ListWrecks
Static Public Attributes inherited from EClass
static Core core
Properties
int Index [get]
virtual bool PopulateCluster [get]
virtual bool IsBigRoom [get]
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Private Attributes
Point _p = new Point()
global::Cell _c
Additional Inherited Members
Static Public Member Functions inherited from GenBounds
static GenBounds Create (Zone z)
Static Public Member Functions inherited from EClass
static int rnd (int a)
static int curve (int a, int start, int step, int rate=75)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Detailed Description
Definition at line 5 of file GenRoom.cs.
Member Function Documentation
Fill()
void GenRoom.Fill () inline
Definition at line 190 of file GenRoom.cs.
    {
        BiomeProfile.TileFloor floor = this.group.floor;
        BiomeProfile.TileBlock block = this.group.block;
        for (int i = this.x; i < this.x + this.width; i++)
        {
            for (int j = this.y; j < this.y + this.height; j++)
            {
                if (this.map.cells[i, j]._block != 0)
                {
                    base.SetBlock(i, j, block.mat, block.id, EClass.rnd(EClass.rnd(4) + 1));
                }
                base.SetFloor(i, j, floor.mat, floor.id, EClass.rnd(EClass.rnd(8) + 1));
            }
        }
    }
References BiomeProfile.Tile.id, BiomeProfile.Tile.mat, and EClass.rnd().
Referenced by MapGenDungen.g__SetRoom().
Init() [1/2]
void GenRoom.Init (Dungen::Room room) inline
Definition at line 31 of file GenRoom.cs.
    {
        this.x = room.x + 1;
        this.y = room.y + 1;
        this.width = room.width;
        this.height = room.height;
        this.Size = this.width * this.height;
    }
References GenBounds.height.
Referenced by MapGenDungen.OnGenerateTerrain().
Init() [2/2]
void GenRoom.Init (int _x, int _y, int w, int h) inline
Definition at line 40 of file GenRoom.cs.
    {
        this.x = _x;
        this.y = _y;
        this.width = w;
        this.height = h;
        this.Size = this.width * this.height;
    }
References GenBounds.height.
OnPopulate()
virtual void GenRoom.OnPopulate () inline virtual
Reimplemented in GenRoomMonsterHouse.
Definition at line 127 of file GenRoom.cs.
    {
        for (int i = 0; i < EClass.rnd(3 + this.Size / 8) + 1; i++)
        {
            this.SetRandomPoint(delegate(Point p)
            {
                int num = EClass.rnd(7);
                if (num > 1)
                {
                    if (num != 2)
                    {
                        this.SpawnMob(p);
                    }
                    else
                    {
                        if (EClass.rnd(5) != 0)
{
                            this.map.SetObj(p.x, p.z, GenRoom.ListWrecks.RandomItem<int>(), 1, 0);
                            return;
                        }
                        this.map.SetObj(p.x, p.z, 82, 1, 0);
                        if (EClass.rnd(2) == 0)
{
                            this.map.ApplyBackerObj(p, -1);
                            return;
                        }
                    }
                }
                else if (this.zone.biome.spawn.thing.Count > 0)
                {
                    Thing thing = ThingGen.CreateFromFilter(this.zone.biome.spawn.GetRandomThingId(), EClass._zone.DangerLv);
                    if (thing != null)
                    {
                        this.zone.AddCard(thing, p);
                        return;
                    }
                }
            });
        }
        if (this.Size > 25)
        {
            for (int j = 0; j < this.Size / 25 + EClass.rnd(this.Size / 25); j++)
            {
                this.SetRandomPoint(delegate(Point p)
                {
                    if (EClass.rnd(3) == 0)
                    {
                        Thing thing = ThingGen.CreateFromFilter(this.zone.biome.spawn.GetRandomThingId(), EClass._zone.DangerLv);
                        if (thing != null)
{
                            this.zone.AddCard(thing, p);
                            return;
                        }
                    }
                    else
                    {
                        this.SpawnMob(p);
                    }
                });
            }
        }
    }
References EClass._zone, Zone.AddCard(), Map.ApplyBackerObj(), Zone.biome, ThingGen.CreateFromFilter(), Zone.DangerLv, ListWrecks, GenBounds.map, EClass.rnd(), Map.SetObj(), SetRandomPoint(), GenBounds.Size, BiomeProfile.spawn, SpawnMob(), Point.x, Point.z, and GenBounds.zone.
Referenced by Populate().
Populate()
void GenRoom.Populate () inline
Definition at line 49 of file GenRoom.cs.
    {
        PartialMap partialMap = base.TryAddMapPiece(MapPiece.Type.Any, -1f, null, null);
        this.OnPopulate();
        BiomeProfile biome = this.zone.biome;
        if (biome.style.lights.Count > 0 && (partialMap == null || !partialMap.result.hasLight))
        {
            foreach (BiomeProfile.Cluster.ItemThing itemThing in biome.style.lights)
            {
                if (Rand.Range(0f, 1f) <= itemThing.chance)
                {
                    Thing thing = ThingGen.Create(itemThing.id, -1, -1);
                    Point point = new Point();
                    int i = 0;
                    while (i < 100)
                    {
                        if (!thing.TileType.UseMountHeight)
{
                            int a = Mathf.Min(i / 3 + 2, this.width / 2);
                            int a2 = Mathf.Min(i / 3 + 2, this.height / 2);
                            point.Set(this.x + this.width / 2 + EClass.rnd(a) - EClass.rnd(a), this.y + this.height / 2 + EClass.rnd(a2) - EClass.rnd(a2));
                            goto IL_1E0;
                        }
                        point.Set(this.x + EClass.rnd(this.width), this.y + EClass.rnd(this.height));
                        global::Cell cell = point.cell;
                        if (!cell.Left.hasDoor && !cell.Right.hasDoor && !cell.Front.hasDoor && !cell.Back.hasDoor)
{
                            if (cell.Left.HasBlock || cell.Right.HasBlock || cell.Front.HasBlock || cell.Back.HasBlock)
{
                                goto IL_1E0;
                            }
                        }
                        IL_23F:
                        i++;
                        continue;
                        IL_1E0:
                        if (!point.cell.blocked && !point.HasBlock && !point.HasObj && point.Installed == null)
{
                            int desiredDir = thing.TileType.GetDesiredDir(point, 0);
                            if (desiredDir != -1)
{
                                thing.dir = desiredDir;
                            }
                            this.zone.AddCard(thing, point).Install();
                            break;
                        }
                        goto IL_23F;
                    }
                    break;
                }
            }
        }
        if (this.PopulateCluster)
        {
            Point point2 = new Point();
            for (int j = this.x; j < this.x + this.width; j++)
            {
                for (int k = this.y; k < this.y + this.height; k++)
                {
                    point2.Set(j, k);
                    if (!point2.cell.isModified && !point2.cell.blocked)
                    {
                        biome.Populate(point2, true);
                    }
                }
            }
        }
    }
References Zone.AddCard(), Zone.biome, Algorithms.WeightCell.blocked, Point.cell, ThingGen.Create(), TileType.GetDesiredDir(), Point.HasBlock, Point.HasObj, GenBounds.height, Card.Install(), Point.Installed, Cell.isModified, OnPopulate(), BiomeProfile.Populate(), PopulateCluster, PartialMap.result, EClass.rnd(), Point.Set(), BiomeProfile.style, Card.TileType, TileType.UseMountHeight, GenBounds.width, GenBounds.x, GenBounds.y, and GenBounds.zone.
Referenced by MapGenDungen.OnGenerateTerrain().
SetRandomPoint()
void GenRoom.SetRandomPoint (Action< Point > action) inline
Definition at line 207 of file GenRoom.cs.
    {
        int a = Mathf.Max(this.width - 2, 1);
        int a2 = Mathf.Max(this.height - 2, 1);
        for (int i = 0; i < 100; i++)
        {
            this._p.x = this.x + 1 + EClass.rnd(a);
            this._p.z = this.y + 1 + EClass.rnd(a2);
            this._c = this.map.cells[this._p.x, this._p.z];
            if (!this._c.blocked && !this._c.HasBlock && !this._p.HasThing && !this._p.HasChara)
            {
                action(this._p);
                return;
            }
        }
    }
References EClass.rnd().
Referenced by OnPopulate().
SetRandomPointCentered()
void GenRoom.SetRandomPointCentered (Action< Point > action) inline
Definition at line 224 of file GenRoom.cs.
    {
        int a = Mathf.Max(this.width / 2 - 1, 1);
        int a2 = Mathf.Max(this.height / 2 - 1, 1);
        for (int i = 0; i < 100; i++)
        {
            this._p.x = this.x + this.width / 2 + EClass.rnd(EClass.rnd(a) + 1) - EClass.rnd(EClass.rnd(a) + 1);
            this._p.z = this.y + this.height / 2 + EClass.rnd(EClass.rnd(a2) + 1) - EClass.rnd(EClass.rnd(a2) + 1);
            this._c = this.map.cells[this._p.x, this._p.z];
            if (!this._c.blocked && !this._c.HasBlock && !this._p.HasThing && !this._p.HasChara)
            {
                action(this._p);
                return;
            }
        }
    }
References EClass.rnd().
SpawnMob()
void GenRoom.SpawnMob (Point p) inline
Definition at line 118 of file GenRoom.cs.
    {
        if (EClass.rnd(100) > 55 + this.zone.DangerLv * 3)
        {
            return;
        }
        this.zone.SpawnMob(p, null);
    }
References EClass.rnd(), Zone.SpawnMob(), and GenBounds.zone.
Referenced by OnPopulate().
Member Data Documentation
_c
global.Cell GenRoom._c private
Definition at line 257 of file GenRoom.cs.
_p
Point GenRoom._p = new Point() private
Definition at line 255 of file GenRoom.cs.
gen
MapGenDungen GenRoom.gen
Definition at line 243 of file GenRoom.cs.
group
BiomeProfile.TileGroup GenRoom.group
Definition at line 241 of file GenRoom.cs.
ListWrecks
int [] GenRoom.ListWrecks static
Initial value:
= new int[]
    {
        34,
        46,
        83,
        85,
        86,
        87
    }
Definition at line 245 of file GenRoom.cs.
Referenced by OnPopulate().
Property Documentation
Index
int GenRoom.Index get
Definition at line 7 of file GenRoom.cs.
    {
        get
        {
            return this.x + this.y * this.Size;
        }
    }
Referenced by MapGenDungen.g__SetRoom().
IsBigRoom
virtual bool GenRoom.IsBigRoom get
Definition at line 23 of file GenRoom.cs.
    {
        get
        {
            return false;
        }
    }
PopulateCluster
virtual bool GenRoom.PopulateCluster get
Definition at line 15 of file GenRoom.cs.
    {
        get
        {
            return true;
        }
    }
Referenced by Populate().
The documentation for this class was generated from the following file:
Elin/GenRoom.cs