Elin Decompiled Documentation: UDictionary< TKey, TValue > Class Template Reference
UDictionary< TKey, TValue > Class Template Reference
Public Member Functions
UDictionary ()
UDictionary (IEqualityComparer< TKey > comparer)
UDictionary (IDictionary< TKey, TValue > dictionary)
UDictionary (int capacity)
UDictionary (IDictionary< TKey, TValue > dictionary, IEqualityComparer< TKey > comparer)
UDictionary (int capacity, IEqualityComparer< TKey > comparer)
void OnAfterDeserialize ()
void OnBeforeSerialize ()
void GetObjectData (SerializationInfo info, StreamingContext context)
void OnDeserialization (object sender)
void Add (TKey key, TValue value)
bool ContainsKey (TKey key)
bool Remove (TKey key)
bool TryGetValue (TKey key, out TValue value)
void Add (KeyValuePair< TKey, TValue > item)
void Clear ()
bool Contains (KeyValuePair< TKey, TValue > item)
bool Remove (KeyValuePair< TKey, TValue > item)
IEnumerator< KeyValuePair< TKey, TValue > > GetEnumerator ()
Properties
bool IsFixedSize [get]
ICollection< TKey > Keys [get]
ICollection IDictionary. Keys [get]
ICollection< TValue > Values [get]
ICollection IDictionary. Values [get]
TValue this[TKey key] [get, set]
object IDictionary. this[object key] [get, set]
int Count [get]
bool IsReadOnly [get]
bool IsSynchronized [get]
object SyncRoot [get]
Private Member Functions
void IDictionary. Add (object key, object value)
bool IDictionary. Contains (object key)
void IDictionary. Remove (object key)
IDictionaryEnumerator IDictionary. GetEnumerator ()
void ICollection. CopyTo (Array array, int index)
void ICollection< KeyValuePair< TKey, TValue > >. CopyTo (KeyValuePair< TKey, TValue >[] array, int arrayIndex)
IEnumerator IEnumerable. GetEnumerator ()
Private Attributes
List< TKey > keys = new List<TKey>()
List< TValue > values = new List<TValue>()
Dictionary< TKey, TValue > dictionary
Detailed Description
Definition at line 12 of file UDictionary.cs.
Constructor & Destructor Documentation
UDictionary() [1/6]
UDictionary< TKey, TValue >.UDictionary () inline
Definition at line 72 of file UDictionary.cs.
    {
        dictionary = new Dictionary<TKey, TValue>();
    }
References UDictionary< TKey, TValue >.dictionary.
UDictionary() [2/6]
UDictionary< TKey, TValue >.UDictionary (IEqualityComparer< TKey > comparer) inline
Definition at line 77 of file UDictionary.cs.
    {
        dictionary = new Dictionary<TKey, TValue>(comparer);
    }
References UDictionary< TKey, TValue >.dictionary.
UDictionary() [3/6]
UDictionary< TKey, TValue >.UDictionary (IDictionary< TKey, TValue > dictionary) inline
Definition at line 82 of file UDictionary.cs.
    {
        this.dictionary = new Dictionary<TKey, TValue>(dictionary);
    }
References UDictionary< TKey, TValue >.dictionary.
UDictionary() [4/6]
UDictionary< TKey, TValue >.UDictionary (int capacity) inline
Definition at line 87 of file UDictionary.cs.
    {
        dictionary = new Dictionary<TKey, TValue>(capacity);
    }
References UDictionary< TKey, TValue >.dictionary.
UDictionary() [5/6]
UDictionary< TKey, TValue >.UDictionary (IDictionary< TKey, TValue > dictionary, IEqualityComparer< TKey > comparer) inline
Definition at line 92 of file UDictionary.cs.
    {
        this.dictionary = new Dictionary<TKey, TValue>(dictionary, comparer);
    }
References UDictionary< TKey, TValue >.dictionary.
UDictionary() [6/6]
UDictionary< TKey, TValue >.UDictionary (int capacity, IEqualityComparer< TKey > comparer) inline
Definition at line 97 of file UDictionary.cs.
    {
        dictionary = new Dictionary<TKey, TValue>(capacity, comparer);
    }
References UDictionary< TKey, TValue >.dictionary.
Member Function Documentation
Add() [1/3]
void UDictionary< TKey, TValue >.Add (KeyValuePair< TKey, TValue > item) inline
Definition at line 188 of file UDictionary.cs.
    {
        dictionary.Add(item.Key, item.Value);
    }
References UDictionary< TKey, TValue >.dictionary, and item.
Add() [2/3]
void IDictionary. UDictionary< TKey, TValue >.Add (object key, object value) inline private
Definition at line 143 of file UDictionary.cs.
    {
        if (key is TKey && (value is TValue || value == null))
        {
            dictionary.Add((TKey)key, (TValue)value);
        }
    }
References UDictionary< TKey, TValue >.dictionary.
Add() [3/3]
void UDictionary< TKey, TValue >.Add (TKey key, TValue value) inline
Definition at line 138 of file UDictionary.cs.
    {
        dictionary.Add(key, value);
    }
References UDictionary< TKey, TValue >.dictionary.
Referenced by CoreRef.RebuildBiomeList().
Clear()
void UDictionary< TKey, TValue >.Clear () inline
Definition at line 193 of file UDictionary.cs.
    {
        dictionary.Clear();
    }
References UDictionary< TKey, TValue >.dictionary.
Referenced by CoreRef.RebuildBiomeList(), and CoreRef.RebuildSketchList().
Contains() [1/2]
bool UDictionary< TKey, TValue >.Contains (KeyValuePair< TKey, TValue > item) inline
Definition at line 198 of file UDictionary.cs.
    {
        if (dictionary.ContainsKey(item.Key))
        {
            return dictionary[item.Key].Equals(item.Value);
        }
        return false;
    }
References UDictionary< TKey, TValue >.dictionary, and item.
Contains() [2/2]
bool IDictionary. UDictionary< TKey, TValue >.Contains (object key) inline private
Definition at line 156 of file UDictionary.cs.
    {
        if (!(key is TKey))
        {
            return false;
        }
        return dictionary.ContainsKey((TKey)key);
    }
References UDictionary< TKey, TValue >.dictionary.
ContainsKey()
bool UDictionary< TKey, TValue >.ContainsKey (TKey key) inline
Definition at line 151 of file UDictionary.cs.
    {
        return dictionary.ContainsKey(key);
    }
References UDictionary< TKey, TValue >.dictionary.
Referenced by ActEffect.DamageEle(), and SourceThingV.RestorePref().
CopyTo() [1/2]
void ICollection. UDictionary< TKey, TValue >.CopyTo (Array array, int index) inline private
Definition at line 207 of file UDictionary.cs.
    {
    }
CopyTo() [2/2]
void ICollection< KeyValuePair< TKey, TValue > >. UDictionary< TKey, TValue >.CopyTo (KeyValuePair< TKey, TValue >[] array, int arrayIndex) inline private
Definition at line 211 of file UDictionary.cs.
    {
    }
GetEnumerator() [1/3]
IDictionaryEnumerator IDictionary. UDictionary< TKey, TValue >.GetEnumerator () inline private
Definition at line 183 of file UDictionary.cs.
    {
        return ((IDictionary)dictionary).GetEnumerator();
    }
References UDictionary< TKey, TValue >.dictionary.
GetEnumerator() [2/3]
IEnumerator< KeyValuePair< TKey, TValue > > UDictionary< TKey, TValue >.GetEnumerator () inline
Definition at line 220 of file UDictionary.cs.
    {
        return dictionary.GetEnumerator();
    }
References UDictionary< TKey, TValue >.dictionary.
GetEnumerator() [3/3]
IEnumerator IEnumerable. UDictionary< TKey, TValue >.GetEnumerator () inline private
Definition at line 225 of file UDictionary.cs.
    {
        return dictionary.GetEnumerator();
    }
References UDictionary< TKey, TValue >.dictionary.
GetObjectData()
void UDictionary< TKey, TValue >.GetObjectData (SerializationInfo info, StreamingContext context) inline
Definition at line 128 of file UDictionary.cs.
    {
        dictionary.GetObjectData(info, context);
    }
References UDictionary< TKey, TValue >.dictionary.
OnAfterDeserialize()
void UDictionary< TKey, TValue >.OnAfterDeserialize () inline
Definition at line 102 of file UDictionary.cs.
    {
        dictionary.Clear();
        for (int i = 0; i < keys.Count; i++)
        {
            if (keys[i] != null && (!(keys[i] is UnityEngine.Object) || (bool)(UnityEngine.Object)(object)keys[i]))
            {
                dictionary.Add(keys[i], values[i]);
            }
        }
    }
References UDictionary< TKey, TValue >.dictionary, UDictionary< TKey, TValue >.keys, and UDictionary< TKey, TValue >.values.
OnBeforeSerialize()
void UDictionary< TKey, TValue >.OnBeforeSerialize () inline
Definition at line 114 of file UDictionary.cs.
    {
        keys.Clear();
        values.Clear();
        foreach (KeyValuePair<TKey, TValue> item in dictionary)
        {
            if (item.Key != null && (!(item.Key is UnityEngine.Object) || (bool)(UnityEngine.Object)(object)item.Key))
            {
                keys.Add(item.Key);
                values.Add(item.Value);
            }
        }
    }
References UDictionary< TKey, TValue >.dictionary, item, UDictionary< TKey, TValue >.keys, and UDictionary< TKey, TValue >.values.
OnDeserialization()
void UDictionary< TKey, TValue >.OnDeserialization (object sender) inline
Definition at line 133 of file UDictionary.cs.
    {
        dictionary.OnDeserialization(sender);
    }
References UDictionary< TKey, TValue >.dictionary.
Remove() [1/3]
bool UDictionary< TKey, TValue >.Remove (KeyValuePair< TKey, TValue > item) inline
Definition at line 215 of file UDictionary.cs.
    {
        return dictionary.Remove(item.Key);
    }
References UDictionary< TKey, TValue >.dictionary, and item.
Remove() [2/3]
void IDictionary. UDictionary< TKey, TValue >.Remove (object key) inline private
Definition at line 170 of file UDictionary.cs.
    {
        if (key is TKey)
        {
            dictionary.Remove((TKey)key);
        }
    }
References UDictionary< TKey, TValue >.dictionary.
Remove() [3/3]
bool UDictionary< TKey, TValue >.Remove (TKey key) inline
Definition at line 165 of file UDictionary.cs.
    {
        return dictionary.Remove(key);
    }
References UDictionary< TKey, TValue >.dictionary.
TryGetValue()
bool UDictionary< TKey, TValue >.TryGetValue (TKey key, out TValue value) inline
Definition at line 178 of file UDictionary.cs.
    {
        return dictionary.TryGetValue(key, out value);
    }
References UDictionary< TKey, TValue >.dictionary.
Referenced by DamageTextRenderer.Flush(), SourceMaterial.Row.Init(), UIInventory.OnInit(), TraitPaintBoard.OnRenderExtra(), TraitShrine.OnRenderExtra(), ActRanged.Perform(), AttackProcess.PlayRangedAnime(), ActEffect.ProcAt(), CardActor.SetOwner(), and CoreDebug.MatColorTest.Update().
Member Data Documentation
dictionary
Dictionary<TKey, TValue> UDictionary< TKey, TValue >.dictionary private
Definition at line 21 of file UDictionary.cs.
Referenced by UDictionary< TKey, TValue >.Add(), UDictionary< TKey, TValue >.Clear(), UDictionary< TKey, TValue >.Contains(), UDictionary< TKey, TValue >.ContainsKey(), UDictionary< TKey, TValue >.GetEnumerator(), UDictionary< TKey, TValue >.GetObjectData(), UDictionary< TKey, TValue >.OnAfterDeserialize(), UDictionary< TKey, TValue >.OnBeforeSerialize(), UDictionary< TKey, TValue >.OnDeserialization(), UDictionary< TKey, TValue >.Remove(), UDictionary< TKey, TValue >.TryGetValue(), and UDictionary< TKey, TValue >.UDictionary().
keys
List<TKey> UDictionary< TKey, TValue >.keys = new List<TKey>() private
Definition at line 15 of file UDictionary.cs.
Referenced by UDictionary< TKey, TValue >.OnAfterDeserialize(), and UDictionary< TKey, TValue >.OnBeforeSerialize().
values
List<TValue> UDictionary< TKey, TValue >.values = new List<TValue>() private
Definition at line 18 of file UDictionary.cs.
Referenced by UDictionary< TKey, TValue >.OnAfterDeserialize(), and UDictionary< TKey, TValue >.OnBeforeSerialize().
Property Documentation
Count
int UDictionary< TKey, TValue >.Count get
Definition at line 64 of file UDictionary.cs.
Referenced by CoreRef.RebuildSketchList(), and ContentGallery.Refresh().
IsFixedSize
bool UDictionary< TKey, TValue >.IsFixedSize get
Definition at line 23 of file UDictionary.cs.
IsReadOnly
bool UDictionary< TKey, TValue >.IsReadOnly get
Definition at line 66 of file UDictionary.cs.
IsSynchronized
bool UDictionary< TKey, TValue >.IsSynchronized get
Definition at line 68 of file UDictionary.cs.
Keys [1/2]
ICollection<TKey> UDictionary< TKey, TValue >.Keys get
Definition at line 25 of file UDictionary.cs.
Referenced by DramaOutcome.check_sketch(), DramaOutcome.give_sketch_special(), and ContentGallery.OnSwitchContent().
Keys [2/2]
ICollection IDictionary. UDictionary< TKey, TValue >.Keys get private
Definition at line 27 of file UDictionary.cs.
SyncRoot
object UDictionary< TKey, TValue >.SyncRoot get
Definition at line 70 of file UDictionary.cs.
this[object key]
object IDictionary. UDictionary< TKey, TValue >.this[object key] get set private
Definition at line 45 of file UDictionary.cs.
    {
        get
        {
            if (!(key is TKey))
            {
                return null;
            }
            return dictionary[(TKey)key];
        }
        set
        {
            if (key is TKey && (value is TValue || value == null))
            {
                dictionary[(TKey)key] = (TValue)value;
            }
        }
    }
this[TKey key]
TValue UDictionary< TKey, TValue >.this[TKey key] get set
Definition at line 33 of file UDictionary.cs.
    {
        get
        {
            return dictionary[key];
        }
        set
        {
            dictionary[key] = value;
        }
    }
Values [1/2]
ICollection<TValue> UDictionary< TKey, TValue >.Values get
Definition at line 29 of file UDictionary.cs.
Referenced by BiomeProfile.Init().
Values [2/2]
ICollection IDictionary. UDictionary< TKey, TValue >.Values get private
Definition at line 31 of file UDictionary.cs.
The documentation for this class was generated from the following file:
Elin/Plugins.basecore/UDictionary.cs