Elin Decompiled Documentation: Lang Class Reference
Lang Class Reference
Classes
class Words
Public Types
enum LangCode { None = 0 , JP = 10 , EN = 20 , CN = 30 }
Static Public Member Functions
static bool IsBuiltin (string id)
static void Init (string lang)
static string Get (string id)
static bool Has (string id)
static string TryGet (string id)
static string[] GetList (string id)
static string ParseRaw (string text, string val1, string val2=null, string val3=null, string val4=null, string val5=null)
static string Parse (string idLang, string val1, string val2=null, string val3=null, string val4=null, string val5=null)
static string LoadText (string id)
static string _Number (int a)
static string _currency (object a, string IDCurrency)
static string _currency (object a, bool showUnit=false, int unitSize=14)
static string _weight (int a, int b, bool showUnit=true, int unitSize=0)
static string _gender (int id)
static string _weight (int a, bool showUnit=true, int unitSize=0)
static string _rarity (int a)
static string _ChangeNum (int prev, int now)
static string[] GetDialog (string idSheet, string idTopic)
Static Public Attributes
static NaturalStringComparer comparer = new NaturalStringComparer()
static bool runUpdate
static Words words = new Words()
static string langCode = ""
static string suffix = ""
static string space = ""
static List< Dictionary< string, object > > listName
static List< Dictionary< string, object > > listAlias
static bool isJP
static bool isEN
static bool isBuiltin
static List< char[]> articlesToRemove
static LangGeneral General
static LangGame Game
static LangNote Note
static SourceData List
static LangSetting setting
static ExcelData alias
static ExcelData names
static ExcelData excelDialog
Detailed Description
Definition at line 5 of file Lang.cs.
Member Enumeration Documentation
LangCode
enum Lang.LangCode
Enumerator
None
JP
EN
CN
Definition at line 7 of file Lang.cs.
    {
        None = 0,
        JP = 10,
        EN = 20,
        CN = 30
    }
Member Function Documentation
_ChangeNum()
static string Lang._ChangeNum (int prev, int now) inline static
Definition at line 200 of file Lang.cs.
    {
        return prev + " ⇒ " + now;
    }
Referenced by LittlePopper._OnAddStockpile().
_currency() [1/2]
static string Lang._currency (object a, bool showUnit = false, int unitSize = 14) inline static
Definition at line 167 of file Lang.cs.
    {
        return $"{a:#,0}" + ((!showUnit) ? "" : ((unitSize == 0) ? "u_money".lang(a?.ToString() ?? "") : ("<size=" + unitSize + "> " + "u_money".lang(a?.ToString() ?? "") + "</size>")));
    }
References $.
_currency() [2/2]
static string Lang._currency (object a, string IDCurrency) inline static
Definition at line 162 of file Lang.cs.
    {
        return ("u_currency_" + IDCurrency).lang($"{a:#,0}");
    }
References $.
Referenced by Chara.ApplyDeathPenalty(), AI_Shopping.Buy(), FactionBranch.GetDailyIncome(), Faction.GetFactionSalary(), Thing.GetName(), Chara.GetName(), Faction.GetRankIncome(), Faction.GetResidentTax(), QuestDebt.GetTextProgress(), Faction.OnAdvanceMonth(), InvOwner.OnWriteNote(), InvOwner.Transaction.Process(), LayerShippingResult.Refresh(), PartialMapMenu.Refresh(), LayerDragGrid.RefreshCost(), UIInventory.RefreshList(), WindowChara.RefreshProfile(), AI_Idle.Run(), Faction.SetTaxTooltip(), and TraitSalesTag.TrySetHeldAct().
_gender()
static string Lang._gender (int id) inline static
Definition at line 177 of file Lang.cs.
    {
        return GetList("genders")[id];
    }
References GetList().
Referenced by Person.GetDramaTitle(), UICharaMaker.Refresh(), ButtonChara.SetChara(), and Biography.TextBio().
_Number()
static string Lang._Number (int a) inline static
Definition at line 157 of file Lang.cs.
    {
        return $"{a:#,0}";
    }
References $.
Referenced by UIRecipeInfo.RefreshBalance().
_rarity()
static string Lang._rarity (int a) inline static
Definition at line 187 of file Lang.cs.
    {
        return a switch
        {
            4 => "SSR",
            3 => "SR",
            2 => "R",
            1 => "C",
            0 => "K",
            _ => "LE",
        };
    }
Referenced by Hoard.Item.Name().
_weight() [1/2]
static string Lang._weight (int a, bool showUnit = true, int unitSize = 0) inline static
Definition at line 182 of file Lang.cs.
    {
        return (0.001f * (float)a).ToString("#0.0") + ((!showUnit) ? "" : ((unitSize == 0) ? "s" : ("<size=" + unitSize + "> s</size>")));
    }
_weight() [2/2]
static string Lang._weight (int a, int b, bool showUnit = true, int unitSize = 0) inline static
Definition at line 172 of file Lang.cs.
    {
        return (0.001f * (float)a).ToString("#0.0") + "/" + (0.001f * (float)b).ToString("#0.0") + ((!showUnit) ? "" : ((unitSize == 0) ? "s" : ("<size=" + unitSize + "> s</size>")));
    }
Referenced by InvOwnerDeliver._OnProcess(), UICurrency.Build(), Thing.GetHoverText(), QuestHarvest.GetTextProgress(), ZoneEventHarvest.OnReachTimeLimit(), WindowCharaMini.Refresh(), UIInventory.RefreshGrid(), UIInventory.RefreshList(), WindowChara.RefreshProfile(), ButtonGrid.SetCard(), Thing.ShowSplitMenu(), and Thing.ShowSplitMenu2().
Get()
static string Lang.Get (string id) inline static
Definition at line 91 of file Lang.cs.
    {
        if (!(General != null))
        {
            return id;
        }
        return General.Get(id);
    }
References General, and SourceLang< T >.Get().
Referenced by Dialog._Confetti(), UIContextMenu.AddButton(), UIContextMenu.AddChild(), LayerNewZone.Embark(), ActionMode.GetHintText(), Act.GetText(), DynamicAct.GetText(), DynamicAIAct.GetText(), Date.GetText(), Dialog.Gift(), Dialog.InputName(), ClassExtension.lang(), ClassExtension.langPlural(), Dialog.Ok(), WidgetSceneCustomizer.OnActivate(), UIText.OnChangeLanguage(), UIText.OnEnable(), LayerWidget.OnInit(), ContentConfigGame.OnInstantiate(), ContentConfigInput.OnInstantiate(), ContentConfigOther.OnInstantiate(), ContentConfigTest.OnInstantiate(), WidgetMouseover.OnManagerActivate(), Parse(), LayerGacha.PlayGacha(), Dialog.Recipe(), LayerConfig.Refresh(), LayerWidget.Refresh(), UITooltip.SetData(), UIText.SetLang(), ItemNumLog.SetLog(), ContentRanking.SwitchRanking(), TryGet(), Dialog.TryWarn(), and Dialog.YesNo().
GetDialog()
static string[] Lang.GetDialog (string idSheet, string idTopic) inline static
Definition at line 205 of file Lang.cs.
    {
        if (excelDialog == null)
        {
            string path = CorePath.CorePackage.TextDialog + "dialog.xlsx";
            excelDialog = new ExcelData();
            excelDialog.path = path;
        }
        excelDialog.BuildMap(idSheet);
        ExcelData.Sheet sheet = excelDialog.sheets[idSheet];
        string key = "text" + (isBuiltin ? ("_" + langCode) : "");
        Dictionary<string, string> dictionary = sheet.map.TryGetValue(idTopic);
        if (dictionary == null || !dictionary.ContainsKey(key))
        {
            return new string[1] { idTopic };
        }
        string text = dictionary[key];
        if (text.IsEmpty())
        {
            text = dictionary["text_EN"];
        }
        return text.Split(new string[3] { "\r\n", "\r", "\n" }, StringSplitOptions.None);
    }
References ExcelData.BuildMap(), excelDialog, isBuiltin, langCode, ExcelData.Sheet.map, and ExcelData.sheets.
Referenced by DramaCustomSequence.GetText(), and TraitFortuneCookie.OnEat().
GetList()
static string[] Lang.GetList (string id) inline static
Definition at line 114 of file Lang.cs.
    {
        return List.GetList(id);
    }
References SourceData< T, T2 >.GetList(), and List.
Referenced by _gender(), Chara._Move(), FortuneRollData.Prize.AddNote(), GameLang.ConvertDrama(), ActEffect.DamageEle(), AI_PlayMusic.Evaluate(), AttackProcess.GetAttackText(), Chara.GetHoverText(), Thing.GetName(), Cell.GetObjName(), Zone.GetProfile(), RankedZoneManager.GetRankText(), ConBuffStats.GetText(), AI_Shear.GetText(), AI_Slaughter.GetText(), BaseTaskHarvest.GetTextDifficulty(), Religion.GetTextTemper(), Window.Init(), Init(), ClassExtension.langList(), UICharaMaker.ListAge(), UICharaMaker.ListGender(), BaseArea.ListRoomNames(), WidgetSearch.OnActivate(), TraitBaseSpellbook.OnCreate(), LayerNewspaper.OnInit(), LayerWorldSetting.OnInit(), BaseListPeople.OnRefreshMenu(), ActionMode.OnShowExtraHint(), ListOwner< T1, T2 >.OnSwitchContent(), Scene.OnUpdate(), TraitDaggerGrave.OnUse(), UICharaMaker.Refresh(), UIHomeInfo.RefreshInfo(), AI_Craft_Snowman.Run(), AI_PlayMusic.Run(), UICharaMaker.SetChara(), ButtonElement.SetGrid(), TraitBaseSpellbook.SetName(), Window.SetTitles(), Biography.TextBioSlave(), Chara.UseAbility(), BaseListPeople.WriteHobbies(), and FortuneRollData.WriteNote().
Has()
static bool Lang.Has (string id) inline static
Definition at line 100 of file Lang.cs.
    {
        return General.map.ContainsKey(id);
    }
References General.
Referenced by Act.GetText(), LayerWorldSetting.Refresh(), ELayer.TryShowHint(), and Thing.WriteNote().
Init()
static void Lang.Init (string lang) inline static
Definition at line 71 of file Lang.cs.
    {
        setting = MOD.langs.TryGetValue(lang) ?? MOD.langs["EN"];
        langCode = lang;
        isJP = lang == "JP";
        isEN = lang == "EN";
        isBuiltin = lang == "JP" || lang == "EN";
        suffix = ((!isBuiltin) ? "_L" : (isJP ? "_JP" : ""));
        space = (setting.useSpace ? " " : "");
        char.TryParse("_comma".lang(), out words.comma);
        char.TryParse("_period".lang(), out words.period);
        SourceData.LangSuffix = suffix;
        articlesToRemove = new List<char[]>();
        string[] list = GetList("_articlesToRemove");
        foreach (string text in list)
        {
            articlesToRemove.Add(text.ToCharArray());
        }
    }
References articlesToRemove, Lang.Words.comma, GetList(), isBuiltin, isEN, isJP, langCode, MOD.langs, Lang.Words.period, setting, space, suffix, and words.
Referenced by Core.SetLang().
IsBuiltin()
static bool Lang.IsBuiltin (string id) inline static
Definition at line 62 of file Lang.cs.
    {
        if (!(id == "JP"))
        {
            return id == "EN";
        }
        return true;
    }
Referenced by ModManager.ParseExtra().
LoadText()
static string Lang.LoadText (string id) inline static
Definition at line 152 of file Lang.cs.
    {
        return null;
    }
Parse()
static string Lang.Parse (string idLang, string val1, string val2 = null, string val3 = null, string val4 = null, string val5 = null) inline static
Definition at line 147 of file Lang.cs.
    {
        return ParseRaw(Get(idLang), val1, val2, val3, val4, val5);
    }
References Get(), and ParseRaw().
Referenced by UIBook.Page.BuildNote(), Cell.GetBlockName(), Cell.GetBridgeName(), Person.GetDramaTitle(), Cell.GetFloorName(), Cell.GetLiquidName(), ClassExtension.lang(), ClassExtension.langPlural(), ContentTop.OnSwitchContent(), ContentHallOfFame.Refresh(), ButtonChara.SetChara(), Biography.TextAppearance(), Biography.TextBio(), Biography.TextBio2(), and Biography.TextBirthDate().
ParseRaw()
static string Lang.ParseRaw (string text, string val1, string val2 = null, string val3 = null, string val4 = null, string val5 = null) inline static
Definition at line 119 of file Lang.cs.
    {
        StringBuilder stringBuilder = new StringBuilder(text);
        stringBuilder.Replace("#1", val1 ?? "");
        if (val2 != null)
        {
            stringBuilder.Replace("#(s2)", (val2.Replace(",", "").ToInt() <= 1) ? "" : "_s".lang());
        }
        stringBuilder.Replace("#(s)", (val1.Replace(",", "").ToInt() <= 1) ? "" : "_s".lang());
        if (val2 != null)
        {
            stringBuilder.Replace("#2", val2);
        }
        if (val3 != null)
        {
            stringBuilder.Replace("#3", val3);
        }
        if (val4 != null)
        {
            stringBuilder.Replace("#4", val4);
        }
        if (val5 != null)
        {
            stringBuilder.Replace("#5", val5);
        }
        return stringBuilder.ToString();
    }
Referenced by ZoneEvent.GetText(), Act.GetText(), and Parse().
TryGet()
static string Lang.TryGet (string id) inline static
Definition at line 105 of file Lang.cs.
    {
        if (!General.map.ContainsKey(id))
        {
            return null;
        }
        return Get(id);
    }
References General, and Get().
Referenced by TraitPerfume.GetName(), TraitPotionRandom.GetName(), and TraitScrollRandom.GetName().
Member Data Documentation
alias
ExcelData Lang.alias static
Definition at line 56 of file Lang.cs.
articlesToRemove
List<char[]> Lang.articlesToRemove static
Definition at line 44 of file Lang.cs.
Referenced by Init(), and GameLang.Parse().
comparer
NaturalStringComparer Lang.comparer = new NaturalStringComparer() static
Definition at line 22 of file Lang.cs.
Referenced by LayerEditSkin.RefreshList(), Card.SecondaryCompare(), and LayerEditPCC.SetPortraitSlider().
excelDialog
ExcelData Lang.excelDialog static
Definition at line 60 of file Lang.cs.
Referenced by GetDialog().
Game
LangGame Lang.Game static
Definition at line 48 of file Lang.cs.
Referenced by LangGame.Has(), AI_Idle.IdleActText(), ClassExtension.langGame(), ZoneEventPhone.OnTickRound(), and Card.Say().
General
LangGeneral Lang.General static
Definition at line 46 of file Lang.cs.
Referenced by Get(), Has(), and TryGet().
isBuiltin
bool Lang.isBuiltin static
Definition at line 42 of file Lang.cs.
Referenced by CardRenderer.Draw(), SourceLang< T >.Get(), GetDialog(), LangList.GetList(), SourceData< T, T2 >.BaseRow.GetText(), SourceData< T, T2 >.BaseRow.GetTextArray(), Core.Init(), Init(), DramaManager.Load(), TraitStoryBook.OnRead(), and DramaManager.ParseLine().
isEN
bool Lang.isEN static
Definition at line 40 of file Lang.cs.
Referenced by Init().
isJP
bool Lang.isJP static
Definition at line 38 of file Lang.cs.
Referenced by UIText.ApplySkin(), Card.ApplyTone(), SourceLang< T >.Get(), LangList.GetList(), ToneDataList.GetToneID(), Init(), Scene.TryWarnLinuxMod(), and Scene.TryWarnMacScreen().
langCode
string Lang.langCode = "" static
Definition at line 28 of file Lang.cs.
Referenced by UIBook.Page.BuildNote(), UIBook.BuildPages(), CardRenderer.Draw(), GetDialog(), Init(), SkinManager.InitFont(), BaseModManager.InitLang(), TraitStoryBook.OnRead(), DramaManager.ParseLine(), LayerNewspaper.RefreshChat(), LayerNewspaper.RefreshVote(), Core.SetLang(), CoreConfig.BackerContentConfig.Show(), CoreDebug.UpdateAlways(), LayerUploader.Upload(), TraitMoongate.UseMoongate(), and ActEffect.Wish().
List
SourceData Lang.List static
Definition at line 52 of file Lang.cs.
Referenced by GetList().
listAlias
List<Dictionary<string, object> > Lang.listAlias static
Definition at line 36 of file Lang.cs.
listName
List<Dictionary<string, object> > Lang.listName static
Definition at line 34 of file Lang.cs.
names
ExcelData Lang.names static
Definition at line 58 of file Lang.cs.
Note
LangNote Lang.Note static
Definition at line 50 of file Lang.cs.
Referenced by Thing.GetName().
runUpdate
bool Lang.runUpdate static
Definition at line 24 of file Lang.cs.
Referenced by ModManager.ParseExtra().
setting
LangSetting Lang.setting static
Definition at line 54 of file Lang.cs.
Referenced by ClassExtension.AddArticle(), WidgetMainText.Append(), Card.ApplyTone(), SourceThing.Row.GetName(), UIItem.Hyphenate(), Init(), SkinManager.InitFont(), ClassExtension.langPlural(), GameLang.Parse(), UIText.SetText(), and ClassExtension.ToTitleCase().
space
string Lang.space = "" static
Definition at line 32 of file Lang.cs.
Referenced by CardRow.GetName(), Religion.GetTextBenefit(), Init(), and ActEffect.Wish().
suffix
string Lang.suffix = "" static
Definition at line 30 of file Lang.cs.
Referenced by SourceData< T, T2 >.BaseRow.GetTextArray(), and Init().
words
Words Lang.words = new Words() static
Definition at line 26 of file Lang.cs.
Referenced by Init(), ClassExtension.StripLastPun(), and ClassExtension.StripPun().
The documentation for this class was generated from the following file:
Elin/Plugins.basecore/Lang.cs