Elin Decompiled Documentation: LayerCraft Class Reference
LayerCraft Class Reference
Public Member Functions
override void RefreshCurrentGrid ()
override void ClearButtons ()
override string GetTextHeader (Window window)
override void OnAfterInit ()
override void OnKill ()
void SetFactory (Thing t)
void OnClickCraft ()
override List< Thing > GetTargets ()
override int GetReqIngredient (int index)
override void OnEndCraft ()
void OnCompleteCraft ()
void WaitUntilIdle ()
void RefreshInfo ()
void RefreshCategory (string cat, bool first=false)
void OnChangeIngredient ()
void RefreshRecipe (bool first)
void RefreshTrackButton ()
void RefreshInputNum ()
void RefreshProduct ()
bool IsQualityMet ()
void RefreshQuality ()
void OnClickExamine ()
virtual List< Thing > GetTargets ()
virtual int GetReqIngredient (int index)
virtual void RefreshCurrentGrid ()
virtual void ClearButtons ()
virtual void OnEndCraft ()
Public Member Functions inherited from ELayer
override void OnBeforeAddLayer ()
void InitInspector ()
sealed override void Init ()
override void OnAfterAddLayer ()
void TryShowHelp ()
void AddLayerToUI (string id)
void TryShowHint (string _langHint=null)
void TalkHomeMemeber (string id)
void TalkMaid (string id)
override void OnRightClick ()
Public Member Functions inherited from Layer
virtual string GetTextHeader (Window window)
virtual bool HeaderIsListOf (int id)
virtual void Init ()
virtual void OnInit ()
virtual void OnAfterInit ()
virtual void ApplySkin ()
void ShowScreenLock (string id)
void UpdateInput ()
virtual void OnUpdateInput ()
virtual void OnRightClick ()
virtual bool OnBack ()
virtual void OnChangeLayer ()
virtual void OnCreate ()
void _AddLayer (string id)
Layer AddLayer (string id)
T AddLayer< T > ()
T AddLayer< T > (string id)
T AddLayerDontCloseOthers< T > ()
Layer AddLayerDontCloseOthers (Layer l)
T GetOrAddLayer< T > ()
virtual void OnBeforeAddLayer ()
virtual void OnAfterAddLayer ()
Layer AddLayer (Layer l)
void ToggleLayer (string id)
T ToggleLayer< T > (string id=null)
void WaitAndClose ()
void OnClickClose ()
virtual void Close ()
void CloseLayers ()
void RemoveLayers (bool removeImportant=false)
bool RemoveLayer< T > ()
void RemoveLayer (Layer l)
virtual void OnKill ()
Layer SetOnKill (Action action)
void DisableClose ()
void Delay (float duration=0.05f)
Layer SetDelay (float d)
Layer GetLayer (string id)
T GetLayer< T > (bool fromTop=false)
Layer GetTopLayer ()
void SwitchContent (int idWindow, int i)
virtual void OnSwitchContent (Window window)
Layer SetTitles (string langList, string idHeaderRow=null)
bool IsBlockWidgetClick ()
bool IsHideHud ()
bool IsAllowGeneralInput ()
bool IsUseBlur ()
bool IsPointerOnLayer ()
void ApplySkin ()
Public Attributes
UIDynamicList list
UIRecipeInfo info1
UIRecipeInfo info2
Vector3 posInfo
Thing factory
Thing product
Recipe recipe
UIButton toggleRepeat
UIButton toggleCraftTo
UIButton buttonTrack
UIInputText inputNum
UIInputText moldInputNum
List< RecipeSource > newRecipes = new List<RecipeSource>()
Window windowList
bool showInfo
UIButton buttonRefuel
UIButton buttonAutoRefuel
Transform transFuel
UIText textFuel
UIText textQualityInvalid
UIText textQualityValid
Image imageQualityReq
Image imageQualityCurrent
float waitComplete
float qualityBarWidth
ButtonGrid lastB
Public Attributes inherited from Layer
Option option
UnityEvent onKill
Anime animeIn
Anime animeOut
bool closeOthers
bool defaultActionMode = true
Button screenLock
Layer parent
string idLayer
List< Layer > layers = new List<Layer>()
Vector2 lastParentPos
List< Window > windows = new List<Window>()
string langHint
Static Public Attributes
static LayerCraft Instance
Static Public Attributes inherited from Layer
static int skipInput
static bool closeOnRightClick
static bool rightClicked
static bool cancelKeyDown
static bool ignoreSounds
static Transform blurStopInstance
static string[] searchPath = new string[3] { "Layer", "Layer/Dialog", "Layer/LayerHome" }
Private Member Functions
void Update ()
Private Attributes
bool pickaxeCrafted
bool workbenchCrafted
int wcount
bool tabBuilt
Additional Inherited Members
Static Public Member Functions inherited from ELayer
static int rnd (int a)
Static Public Member Functions inherited from Layer
static T Create< T > ()
static T Create< T > (string path)
static Layer Create (string path)
Protected Member Functions inherited from ELayer
sealed override void _Close ()
sealed override void Kill ()
Protected Member Functions inherited from Layer
virtual void Awake ()
virtual void _Close ()
virtual void Kill ()
Protected Attributes inherited from Layer
RectTransform _rect
bool isDestroyed
Properties inherited from LayerBaseCraft
virtual bool CanCancelAI [get]
virtual bool RepeatAI [get]
Properties inherited from ELayer
static Core core [get]
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static FactionBranch Branch [get]
static Faction Home [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static CoreConfig config [get]
static GameSetting setting [get]
static ColorProfile Colors [get]
static SourceManager sources [get]
static World world [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
bool IsFloat [get]
virtual string IdHelp [get]
Properties inherited from Layer
Layer TopLayer [get]
string uid [get]
virtual RectTransform rectLayers [get]
virtual bool blockWidgetClick [get]
Detailed Description
Definition at line 6 of file LayerCraft.cs.
Member Function Documentation
ClearButtons()
override void LayerCraft.ClearButtons () inline virtual
Reimplemented from LayerBaseCraft.
Definition at line 75 of file LayerCraft.cs.
    {
        RefreshRecipe(first: true);
    }
References RefreshRecipe().
GetReqIngredient()
override int LayerCraft.GetReqIngredient (int index) inline virtual
Reimplemented from LayerBaseCraft.
Definition at line 209 of file LayerCraft.cs.
    {
        return recipe.ingredients[index].req * inputNum.Num;
    }
References Recipe.ingredients, inputNum, UIInputText.Num, and recipe.
GetTargets()
override List< Thing > LayerCraft.GetTargets () inline virtual
Reimplemented from LayerBaseCraft.
Definition at line 196 of file LayerCraft.cs.
    {
        List<Thing> list = new List<Thing>();
        foreach (Recipe.Ingredient ingredient in recipe.ingredients)
        {
            if (!ingredient.optional || (ingredient.thing != null && !ingredient.thing.isDestroyed))
            {
                list.Add(ingredient.thing);
            }
        }
        return list;
    }
References UIDynamicList.Add(), Recipe.ingredients, list, and recipe.
GetTextHeader()
override string LayerCraft.GetTextHeader (Window window) inline virtual
Reimplemented from Layer.
Definition at line 80 of file LayerCraft.cs.
    {
        return null;
    }
IsQualityMet()
bool LayerCraft.IsQualityMet () inline
Definition at line 494 of file LayerCraft.cs.
    {
        return true;
    }
OnAfterInit()
override void LayerCraft.OnAfterInit () inline virtual
Reimplemented from Layer.
Definition at line 85 of file LayerCraft.cs.
    {
        info1.searchMode = StockSearchMode.AroundPC;
        info1.ddList.pivot.SetActive(enable: true);
        Instance = this;
    }
References UIRecipeInfo.ddList, info1, Instance, and DropdownGrid.pivot.
OnChangeIngredient()
void LayerCraft.OnChangeIngredient () inline
Definition at line 406 of file LayerCraft.cs.
    {
        RefreshRecipe(first: true);
    }
References RefreshRecipe().
Referenced by DropdownGrid.Activate(), and ButtonGrid.SetIngredient().
OnClickCraft()
void LayerCraft.OnClickCraft () inline
Definition at line 138 of file LayerCraft.cs.
    {
        Dictionary<Thing, int> dictionary = new Dictionary<Thing, int>();
        foreach (Recipe.Ingredient ingredient in recipe.ingredients)
        {
            if (ingredient.thing != null)
            {
                if (!dictionary.ContainsKey(ingredient.thing))
                {
                    dictionary.Add(ingredient.thing, 0);
                }
                dictionary[ingredient.thing] += ingredient.req * inputNum.Num;
            }
        }
        foreach (KeyValuePair<Thing, int> item in dictionary)
        {
            if (item.Key.Num < item.Value)
            {
                SE.Beep();
                Msg.Say("craftDupError");
                return;
            }
        }
        if (inputNum.Num == 0)
        {
            SE.Beep();
            return;
        }
        TraitCrafter traitCrafter = factory?.trait as TraitCrafter;
        if (traitCrafter == null)
        {
            traitCrafter = Trait.SelfFactory;
            traitCrafter.owner = ELayer.pc;
        }
        (traitCrafter as TraitFactory).recipe = recipe;
        switch (recipe.id)
        {
        case "workbench":
            workbenchCrafted = true;
            break;
        case "axe":
        case "hammer":
        case "pickaxe":
            pickaxeCrafted = true;
            break;
        }
        recipe.SaveLastIngredients();
        ELayer.pc.SetAI(new AI_UseCrafter
        {
            crafter = traitCrafter,
            layer = this,
            recipe = recipe,
            num = inputNum.Num
        });
        ActionMode.Adv.SetTurbo();
        base.gameObject.SetActive(value: false);
    }
References ActionMode.Adv, factory, Recipe.id, Recipe.ingredients, inputNum, item, UIInputText.Num, ELayer.pc, pickaxeCrafted, recipe, Recipe.SaveLastIngredients(), Msg.Say(), Trait.SelfFactory, Chara.SetAI(), AM_Adv.SetTurbo(), Card.trait, and workbenchCrafted.
OnClickExamine()
void LayerCraft.OnClickExamine () inline
Definition at line 503 of file LayerCraft.cs.
    {
        ELayer.ui.AddLayer<LayerInfo>().Set(product);
    }
References product, and ELayer.ui.
OnCompleteCraft()
void LayerCraft.OnCompleteCraft () inline
Definition at line 219 of file LayerCraft.cs.
    {
        CancelInvoke("WaitUntilIdle");
        EInput.haltInput = true;
        TweenUtil.Tween(waitComplete, null, delegate
        {
            EInput.haltInput = false;
            base.gameObject.SetActive(value: true);
            foreach (Window window in windows)
            {
                window.SetInteractable(enable: true);
            }
            list.Redraw();
            RefreshRecipe(first: true);
            windowList.groupTab.RefreshButtons();
            list.Select((Recipe r) => recipe.id == r.id);
        });
    }
References Window.groupTab, Recipe.id, list, recipe, UIDynamicList.Redraw(), UISelectableGroup.RefreshButtons(), RefreshRecipe(), UIDynamicList.Select(), Window.SetInteractable(), waitComplete, windowList, and Layer.windows.
Referenced by OnEndCraft(), and TaskCraft.Run().
OnEndCraft()
override void LayerCraft.OnEndCraft () inline virtual
Reimplemented from LayerBaseCraft.
Definition at line 214 of file LayerCraft.cs.
    {
        OnCompleteCraft();
    }
References OnCompleteCraft().
Referenced by SetFactory().
OnKill()
override void LayerCraft.OnKill () inline virtual
Reimplemented from Layer.
Definition at line 92 of file LayerCraft.cs.
    {
        if (workbenchCrafted)
        {
            Tutorial.Play("middle_click");
        }
        if (pickaxeCrafted)
        {
            Tutorial.Play("hardness");
        }
        string key = ((factory == null) ? "hand" : factory.id);
        ELayer.player.lastRecipes[key] = recipe.id;
    }
References factory, Card.id, Recipe.id, Player.lastRecipes, pickaxeCrafted, Tutorial.Play(), ELayer.player, recipe, and workbenchCrafted.
RefreshCategory()
void LayerCraft.RefreshCategory (string cat, bool first = false) inline
Definition at line 281 of file LayerCraft.cs.
    {
        Dictionary<string, int> cats = new Dictionary<string, int>();
        RecipeManager.BuildList();
        list.callbacks = new UIList.Callback<Recipe, ButtonGrid>
        {
            onClick = delegate(Recipe a, ButtonGrid b)
            {
                if (recipe != null)
                {
                    recipe.SaveLastIngredients();
                }
                recipe = a;
                SE.Play("click_recipe");
                RefreshRecipe(first: true);
                ELayer.player.recipes.hoveredRecipes.Add(a.id);
                b.Dettach("recipe_new");
                list.Select(a);
            },
            onRedraw = delegate(Recipe a, ButtonGrid b, int i)
            {
                if (a.ingredients.Count == 0)
                {
                    a.BuildIngredientList();
                }
                b.SetCraftRecipe(a, ButtonGrid.Mode.Recipe);
                if (!ELayer.player.recipes.hoveredRecipes.Contains(a.id))
                {
                    b.Attach("recipe_new", rightAttach: false);
                }
                if (a.HasFirstTimeBonus())
                {
                    b.Attach("recipe_firstTime", rightAttach: false).GetComponent<Image>().SetAlpha((a.idSkin == 0) ? 1f : 0.5f);
                }
            },
            onList = delegate
            {
                newRecipes.Clear();
                foreach (RecipeSource item in ELayer.player.recipes.ListSources(factory, newRecipes))
                {
                    if (cat == "all" || item.row.Category.IsChildOf(cat))
                    {
                        Recipe o2 = Recipe.Create(item);
                        list.Add(o2);
                        if (item.row.skins != null && item.row.skins.Length != 0 && !item.row.HasTag(CTAG.noSkinRecipe))
{
                            for (int j = 0; j < item.row.skins.Length; j++)
{
                                o2 = Recipe.Create(item);
                                o2.idSkin = j + 1;
                                list.Add(o2);
                            }
                        }
                    }
                    SourceCategory.Row row = item.row.Category.GetSecondRoot();
                    if (row.id != "lightsource" && row.IsChildOf("armor"))
                    {
                        row = ELayer.sources.categories.map["armor"];
                    }
                    if (!cats.ContainsKey(row.id))
                    {
                        cats.Add(row.id, 1);
                    }
                    else
                    {
                        cats[row.id]++;
                    }
                }
                list.objects.Sort((object a, object b) => (b as Recipe).GetSortVal() - (a as Recipe).GetSortVal());
                _ = newRecipes.Count;
            },
            onSort = (Recipe a, UIList.SortMode m) => a.GetSortVal()
        };
        list.sortMode = UIList.SortMode.ByLevel;
        list.List();
        if (cats.Count > 1 && !tabBuilt)
        {
            windowList.AddTab("all", null, delegate
            {
                RefreshCategory("all");
            });
            foreach (KeyValuePair<string, int> c in cats)
            {
                windowList.AddTab(ELayer.sources.categories.map[c.Key].GetName() + "(" + c.Value + ")", null, delegate
                {
                    RefreshCategory(c.Key);
                });
            }
            tabBuilt = true;
            windowList.BuildTabs(0);
        }
        list.Scroll();
        if (list.rows.Count <= 0)
        {
            return;
        }
        object o = list.rows[0].objects[0];
        if (first)
        {
            string key = ((factory == null) ? "hand" : factory.id);
            if (ELayer.player.lastRecipes.ContainsKey(key))
            {
                string text = ELayer.player.lastRecipes[key];
                foreach (object @object in list.objects)
                {
                    if ((@object as Recipe).id == text)
                    {
                        o = @object;
                        break;
                    }
                }
            }
            list.Scroll(o);
            if (!list.Select(o, invoke: true))
            {
                list.Scroll();
                list.Select(list.rows[0].objects[0]);
            }
        }
        else
        {
            list.Select(o, invoke: true);
        }
    }
References UIDynamicList.Add(), Window.AddTab(), ButtonGrid.Attach(), Recipe.BuildIngredientList(), RecipeManager.BuildList(), Window.BuildTabs(), SourceManager.categories, Recipe.Create(), ButtonGrid.Dettach(), factory, Recipe.GetSortVal(), Recipe.HasFirstTimeBonus(), RecipeManager.hoveredRecipes, Card.id, Recipe.id, SourceCategory.Row.id, Recipe.idSkin, Recipe.ingredients, SourceCategory.Row.IsChildOf(), item, Player.lastRecipes, list, UIDynamicList.List(), RecipeManager.ListSources(), newRecipes, UIDynamicList.objects, ELayer.player, recipe, Player.recipes, RefreshCategory(), RefreshRecipe(), UIDynamicList.rows, Recipe.SaveLastIngredients(), UIDynamicList.Scroll(), UIDynamicList.Select(), ButtonGrid.SetCraftRecipe(), ELayer.sources, tabBuilt, and windowList.
Referenced by RefreshCategory(), and SetFactory().
RefreshCurrentGrid()
override void LayerCraft.RefreshCurrentGrid () inline virtual
Reimplemented from LayerBaseCraft.
Definition at line 70 of file LayerCraft.cs.
    {
        RefreshRecipe(first: true);
    }
References RefreshRecipe().
RefreshInfo()
void LayerCraft.RefreshInfo () inline
Definition at line 268 of file LayerCraft.cs.
    {
        ButtonGrid buttonGrid = InputModuleEX.GetComponentOf<ButtonGrid>();
        if ((bool)buttonGrid && buttonGrid.recipe == null)
        {
            buttonGrid = null;
        }
        if (!(buttonGrid == lastB))
        {
            lastB = buttonGrid;
        }
    }
References lastB.
Referenced by Update().
RefreshInputNum()
void LayerCraft.RefreshInputNum () inline
Definition at line 445 of file LayerCraft.cs.
    {
        inputNum.SetMinMax(1, recipe.GetMaxCount());
        inputNum.onValueChanged = delegate
        {
            RefreshProduct();
        };
        inputNum.Validate();
    }
References Recipe.GetMaxCount(), inputNum, recipe, RefreshProduct(), UIInputText.SetMinMax(), and UIInputText.Validate().
Referenced by RefreshProduct().
RefreshProduct()
void LayerCraft.RefreshProduct () inline
Definition at line 455 of file LayerCraft.cs.
    {
        RefreshInputNum();
        ELayer.screen.tileSelector.summary.countValid = inputNum.Num;
        ELayer.screen.tileSelector.summary.factory = factory;
        info1.RefreshBalance();
        if (factory != null)
        {
            textFuel.text = "craftFuel".lang(((int)((float)factory.c_charges / (float)factory.trait.MaxFuel * 100f)).ToString() ?? "");
            buttonAutoRefuel.mainText.text = (factory.autoRefuel ? "On" : "Off");
            buttonAutoRefuel.icon.SetAlpha(factory.autoRefuel ? 1f : 0.4f);
        }
        RefreshQuality();
        List<Thing> list = new List<Thing>();
        foreach (Recipe.Ingredient ingredient in recipe.ingredients)
        {
            if (ingredient.thing != null)
            {
                list.Add(ingredient.thing);
            }
        }
        Thing thing = recipe.Craft(BlessedState.Normal, sound: false, list, null, model: true);
        thing.SetNum(inputNum.Num);
        if (thing.sockets != null)
        {
            thing.sockets.Clear();
        }
        if (thing.IsEquipmentOrRangedOrAmmo)
        {
            foreach (Element item in thing.elements.dict.Values.ToList())
            {
                _ = item;
            }
        }
        info1.buttonProduct.SetCard(thing);
        thing.WriteNote(info1.note, null, IInspect.NoteMode.Product, recipe);
        product = thing;
    }
References UIDynamicList.Add(), Card.autoRefuel, buttonAutoRefuel, UIRecipeInfo.buttonProduct, Card.c_charges, Recipe.Craft(), ElementContainer.dict, Card.elements, factory, UIButton.icon, info1, Recipe.ingredients, inputNum, Card.IsEquipmentOrRangedOrAmmo, item, list, Trait.MaxFuel, UIRecipeInfo.note, UIInputText.Num, product, recipe, UIRecipeInfo.RefreshBalance(), RefreshInputNum(), RefreshQuality(), ButtonGrid.SetCard(), Card.SetNum(), Card.sockets, Card.trait, and Thing.WriteNote().
Referenced by RefreshInputNum(), RefreshRecipe(), SetFactory(), and DropdownGrid.TrySelect().
RefreshQuality()
void LayerCraft.RefreshQuality () inline
Definition at line 499 of file LayerCraft.cs.
    {
    }
Referenced by RefreshProduct().
RefreshRecipe()
void LayerCraft.RefreshRecipe (bool first) inline
Definition at line 411 of file LayerCraft.cs.
    {
        foreach (Recipe.Ingredient ingredient in recipe.ingredients)
        {
            if (info1.recipe != recipe || (!ingredient.optional && (ingredient.thing == null || ingredient.thing.isDestroyed)))
            {
                ingredient.SetThing();
            }
        }
        if (first)
        {
            toggleCraftTo.SetToggle(isOn: false);
            toggleRepeat.SetToggle(isOn: false);
            inputNum.Num = 1;
            info1.recipe = null;
        }
        info1.factory = factory;
        info1.SetRecipe(recipe);
        recipe.OnChangeIngredient();
        RefreshProduct();
        RefreshTrackButton();
    }
References factory, info1, Recipe.ingredients, Recipe.OnChangeIngredient(), recipe, UIRecipeInfo.recipe, RefreshProduct(), RefreshTrackButton(), UIRecipeInfo.SetRecipe(), UIButton.SetToggle(), toggleCraftTo, and toggleRepeat.
Referenced by ClearButtons(), OnChangeIngredient(), OnCompleteCraft(), RefreshCategory(), and RefreshCurrentGrid().
RefreshTrackButton()
void LayerCraft.RefreshTrackButton () inline
Definition at line 434 of file LayerCraft.cs.
    {
        QuestTrackCraft quest = recipe.GetQuestTrack();
        buttonTrack.SetOnClick(delegate
        {
            recipe.ToggleTrack(quest);
            RefreshTrackButton();
        });
        buttonTrack.icon.SetActive(quest != null && quest.idRecipe == recipe.id);
    }
References buttonTrack, Recipe.GetQuestTrack(), UIButton.icon, Recipe.id, QuestTrackCraft.idRecipe, recipe, RefreshTrackButton(), and Recipe.ToggleTrack().
Referenced by ItemQuestTracker.OnClickClose(), RefreshRecipe(), and RefreshTrackButton().
SetFactory()
void LayerCraft.SetFactory (Thing t) inline
Definition at line 106 of file LayerCraft.cs.
    {
        factory = t;
        RefreshCategory("all", first: true);
        bool flag = t != null && t.trait.IsRequireFuel;
        transFuel.SetActive(flag);
        if (!flag)
        {
            return;
        }
        buttonRefuel.SetOnClick(delegate
        {
            foreach (Window window in windows)
            {
                window.SetInteractable(enable: false, 0f);
            }
            LayerDragGrid.Create(new InvOwnerRefuel(t)).SetOnKill(delegate
            {
                if (!isDestroyed)
                {
                    OnEndCraft();
                }
            });
        });
        buttonAutoRefuel.SetOnClick(delegate
        {
            SE.Click();
            t.autoRefuel = !t.autoRefuel;
            RefreshProduct();
        });
    }
References Card.autoRefuel, buttonAutoRefuel, buttonRefuel, LayerDragGrid.Create(), factory, Layer.isDestroyed, Trait.IsRequireFuel, OnEndCraft(), RefreshCategory(), RefreshProduct(), Window.SetInteractable(), Layer.SetOnKill(), Card.trait, transFuel, and Layer.windows.
Update()
void LayerCraft.Update () inline private
Definition at line 247 of file LayerCraft.cs.
    {
        float axis = Input.GetAxis("Mouse ScrollWheel");
        if (Input.GetMouseButton(0))
        {
            wcount = 2;
        }
        if (axis != 0f)
        {
            wcount = 2;
        }
        else if (wcount > 0)
        {
            wcount--;
        }
        else
        {
            RefreshInfo();
        }
    }
References RefreshInfo(), and wcount.
WaitUntilIdle()
void LayerCraft.WaitUntilIdle () inline
Definition at line 238 of file LayerCraft.cs.
    {
        if (!ActionMode.Adv.IsActive || ELayer.pc.HasNoGoal)
        {
            CancelInvoke();
            Close();
        }
    }
References ActionMode.Adv, Layer.Close(), Chara.HasNoGoal, ActionMode.IsActive, and ELayer.pc.
Member Data Documentation
buttonAutoRefuel
UIButton LayerCraft.buttonAutoRefuel
Definition at line 46 of file LayerCraft.cs.
Referenced by RefreshProduct(), and SetFactory().
buttonRefuel
UIButton LayerCraft.buttonRefuel
Definition at line 44 of file LayerCraft.cs.
Referenced by SetFactory().
buttonTrack
UIButton LayerCraft.buttonTrack
Definition at line 28 of file LayerCraft.cs.
Referenced by RefreshTrackButton().
factory
Thing LayerCraft.factory
Definition at line 18 of file LayerCraft.cs.
Referenced by OnClickCraft(), OnKill(), RefreshCategory(), RefreshProduct(), RefreshRecipe(), and SetFactory().
imageQualityCurrent
Image LayerCraft.imageQualityCurrent
Definition at line 58 of file LayerCraft.cs.
imageQualityReq
Image LayerCraft.imageQualityReq
Definition at line 56 of file LayerCraft.cs.
info1
UIRecipeInfo LayerCraft.info1
Definition at line 12 of file LayerCraft.cs.
Referenced by OnAfterInit(), RefreshProduct(), and RefreshRecipe().
info2
UIRecipeInfo LayerCraft.info2
Definition at line 14 of file LayerCraft.cs.
inputNum
UIInputText LayerCraft.inputNum
Definition at line 30 of file LayerCraft.cs.
Referenced by GetReqIngredient(), OnClickCraft(), RefreshInputNum(), and RefreshProduct().
Instance
LayerCraft LayerCraft.Instance static
Definition at line 8 of file LayerCraft.cs.
Referenced by DropdownGrid.Activate(), GameUpdater.ThingUpdater.FixedUpdate(), OnAfterInit(), ItemQuestTracker.OnClickClose(), ButtonGrid.SetIngredient(), DropdownGrid.TrySelect(), and Thing.WriteNote().
lastB
ButtonGrid LayerCraft.lastB
Definition at line 66 of file LayerCraft.cs.
Referenced by RefreshInfo().
list
UIDynamicList LayerCraft.list
Definition at line 10 of file LayerCraft.cs.
Referenced by GetTargets(), OnCompleteCraft(), RefreshCategory(), and RefreshProduct().
moldInputNum
UIInputText LayerCraft.moldInputNum
Definition at line 32 of file LayerCraft.cs.
newRecipes
List<RecipeSource> LayerCraft.newRecipes = new List<RecipeSource>()
Definition at line 34 of file LayerCraft.cs.
Referenced by RefreshCategory().
pickaxeCrafted
bool LayerCraft.pickaxeCrafted private
Definition at line 40 of file LayerCraft.cs.
Referenced by OnClickCraft(), and OnKill().
posInfo
Vector3 LayerCraft.posInfo
Definition at line 16 of file LayerCraft.cs.
product
Thing LayerCraft.product
Definition at line 20 of file LayerCraft.cs.
Referenced by OnClickExamine(), RefreshProduct(), and ActionMode.UpdateInput().
qualityBarWidth
float LayerCraft.qualityBarWidth
Definition at line 62 of file LayerCraft.cs.
recipe
Recipe LayerCraft.recipe
Definition at line 22 of file LayerCraft.cs.
Referenced by GetReqIngredient(), GetTargets(), OnClickCraft(), OnCompleteCraft(), OnKill(), RefreshCategory(), RefreshInputNum(), RefreshProduct(), RefreshRecipe(), and RefreshTrackButton().
showInfo
bool LayerCraft.showInfo
Definition at line 38 of file LayerCraft.cs.
tabBuilt
bool LayerCraft.tabBuilt private
Definition at line 68 of file LayerCraft.cs.
Referenced by RefreshCategory().
textFuel
UIText LayerCraft.textFuel
Definition at line 50 of file LayerCraft.cs.
textQualityInvalid
UIText LayerCraft.textQualityInvalid
Definition at line 52 of file LayerCraft.cs.
textQualityValid
UIText LayerCraft.textQualityValid
Definition at line 54 of file LayerCraft.cs.
toggleCraftTo
UIButton LayerCraft.toggleCraftTo
Definition at line 26 of file LayerCraft.cs.
Referenced by RefreshRecipe().
toggleRepeat
UIButton LayerCraft.toggleRepeat
Definition at line 24 of file LayerCraft.cs.
Referenced by RefreshRecipe().
transFuel
Transform LayerCraft.transFuel
Definition at line 48 of file LayerCraft.cs.
Referenced by SetFactory().
waitComplete
float LayerCraft.waitComplete
Definition at line 60 of file LayerCraft.cs.
Referenced by OnCompleteCraft().
wcount
int LayerCraft.wcount private
Definition at line 64 of file LayerCraft.cs.
Referenced by Update().
windowList
Window LayerCraft.windowList
Definition at line 36 of file LayerCraft.cs.
Referenced by OnCompleteCraft(), and RefreshCategory().
workbenchCrafted
bool LayerCraft.workbenchCrafted private
Definition at line 42 of file LayerCraft.cs.
Referenced by OnClickCraft(), and OnKill().
The documentation for this class was generated from the following file:
Elin/LayerCraft.cs