Elin Decompiled Documentation: Dialog Class Reference
Dialog Class Reference
Public Types
enum InputType {
None , Default , Password , Item ,
DistributionFilter
}
Public Member Functions
override void OnAfterInit ()
void AddButton (string text, Action onClick=null, bool close=true)
override void OnUpdateInput ()
void OnEnterInput ()
override void OnKill ()
Public Member Functions inherited from ELayer
override void OnBeforeAddLayer ()
void InitInspector ()
sealed override void Init ()
override void OnAfterAddLayer ()
void TryShowHelp ()
void AddLayerToUI (string id)
void TryShowHint (string _langHint=null)
void TalkHomeMemeber (string id)
void TalkMaid (string id)
override void OnRightClick ()
Public Member Functions inherited from Layer
virtual string GetTextHeader (Window window)
virtual bool HeaderIsListOf (int id)
virtual void Init ()
virtual void OnInit ()
virtual void OnAfterInit ()
virtual void ApplySkin ()
void ShowScreenLock (string id)
void UpdateInput ()
virtual void OnUpdateInput ()
virtual void OnRightClick ()
virtual bool OnBack ()
virtual void OnChangeLayer ()
virtual void OnCreate ()
void _AddLayer (string id)
Layer AddLayer (string id)
T AddLayer< T > ()
T AddLayer< T > (string id)
T AddLayerDontCloseOthers< T > ()
Layer AddLayerDontCloseOthers (Layer l)
T GetOrAddLayer< T > ()
virtual void OnBeforeAddLayer ()
virtual void OnAfterAddLayer ()
Layer AddLayer (Layer l)
void ToggleLayer (string id)
T ToggleLayer< T > (string id=null)
void WaitAndClose ()
void OnClickClose ()
virtual void Close ()
void CloseLayers ()
void RemoveLayers (bool removeImportant=false)
bool RemoveLayer< T > ()
void RemoveLayer (Layer l)
virtual void OnKill ()
Layer SetOnKill (Action action)
void DisableClose ()
void Delay (float duration=0.05f)
Layer SetDelay (float d)
Layer GetLayer (string id)
T GetLayer< T > (bool fromTop=false)
Layer GetTopLayer ()
void SwitchContent (int idWindow, int i)
virtual void OnSwitchContent (Window window)
Layer SetTitles (string langList, string idHeaderRow=null)
bool IsBlockWidgetClick ()
bool IsHideHud ()
bool IsAllowGeneralInput ()
bool IsUseBlur ()
bool IsPointerOnLayer ()
void ApplySkin ()
Static Public Member Functions
static Dialog CreateNarration (string idImage, string idText)
static Dialog Ok (string langDetail, Action action=null)
static Dialog Choice (string langDetail, Action< Dialog > action)
static Dialog YesNo (string langDetail, Action actionYes, Action actionNo=null, string langYes="yes", string langNo="no")
static Dialog List< TValue > (string langDetail, ICollection< TValue > items, Func< TValue, string > getString, Func< int, string, bool > onSelect, bool canCancel=false)
static void TryWarn (string lang, Action action, bool yes=true)
static void TryWarnSlaughter (Action action)
static void TryWarnCrime (Action action)
static void TryWarnMana (Action action)
static void TryWarnDisassemble (Action action)
static Dialog Gift (string langHeader, bool autoAdd, params Card[] cards)
static Dialog Gift (string langHeader, bool autoAdd, List< Card > list)
static Dialog Gift (string langHeader, bool autoAdd, List< GridItem > list)
static Dialog Recipe (List< RecipeSource > list)
static Dialog Confetti (string langTitle, string langDetail, string langConfetti="Grats!")
static Dialog ConfettiSimple (string langTitle, string langDetail, string langConfetti="Grats!")
static Dialog _Confetti (string idPrefab, string langTitle, string langDetail, string langConfetti="Grats!")
static Dialog Keymap (EInput.KeyMap keymap)
static Dialog InputName (string langDetail, string text, Action< bool, string > onClose, InputType inputType=InputType.Default)
Static Public Member Functions inherited from ELayer
static int rnd (int a)
Static Public Member Functions inherited from Layer
static T Create< T > ()
static T Create< T > (string path)
static Layer Create (string path)
Public Attributes
Text textConfetti
Image image
UIText textDetail
UINote note
UIButtonList list
LayoutGroup layout
ScreenEffect effect
UIList listGrid
Transform spacer
List< GridItem > gridItems = new List<GridItem>()
UIInputText input
InputType inputType
EInput.KeyMap keymap
bool isInputEnter
Action< bool, string > onEnterInput
Public Attributes inherited from Layer
Option option
UnityEvent onKill
Anime animeIn
Anime animeOut
bool closeOthers
bool defaultActionMode = true
Button screenLock
Layer parent
string idLayer
List< Layer > layers = new List<Layer>()
Vector2 lastParentPos
List< Window > windows = new List<Window>()
string langHint
Static Public Attributes
static bool warned
Static Public Attributes inherited from Layer
static int skipInput
static bool closeOnRightClick
static bool rightClicked
static bool cancelKeyDown
static bool ignoreSounds
static Transform blurStopInstance
static string[] searchPath = new string[3] { "Layer", "Layer/Dialog", "Layer/LayerHome" }
Private Member Functions
void Update ()
Additional Inherited Members
Protected Member Functions inherited from ELayer
sealed override void _Close ()
sealed override void Kill ()
Protected Member Functions inherited from Layer
virtual void Awake ()
virtual void _Close ()
virtual void Kill ()
Protected Attributes inherited from Layer
RectTransform _rect
bool isDestroyed
Properties inherited from ELayer
static Core core [get]
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static FactionBranch Branch [get]
static Faction Home [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static CoreConfig config [get]
static GameSetting setting [get]
static ColorProfile Colors [get]
static SourceManager sources [get]
static World world [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
bool IsFloat [get]
virtual string IdHelp [get]
Properties inherited from Layer
Layer TopLayer [get]
string uid [get]
virtual RectTransform rectLayers [get]
virtual bool blockWidgetClick [get]
Detailed Description
Definition at line 6 of file Dialog.cs.
Member Enumeration Documentation
InputType
enum Dialog.InputType
Enumerator
None
Default
Password
Item
DistributionFilter
Definition at line 8 of file Dialog.cs.
    {
        None,
        Default,
        Password,
        Item,
        DistributionFilter
    }
Member Function Documentation
_Confetti()
static Dialog Dialog._Confetti (string idPrefab, string langTitle, string langDetail, string langConfetti = "Grats!") inline static
Definition at line 506 of file Dialog.cs.
    {
        Dialog d = Layer.Create(idPrefab) as Dialog;
        d.textConfetti.text = langConfetti.lang();
        d.textDetail.SetText(langDetail.lang());
        d.list.AddButton(null, Lang.Get("ok"), delegate
        {
            d.Close();
        });
        ELayer.ui.AddLayer(d);
        return d;
    }
References UIButtonList.AddButton(), Layer.Create(), Lang.Get(), list, UIText.SetText(), textDetail, and ELayer.ui.
Referenced by Confetti(), and ConfettiSimple().
AddButton()
void Dialog.AddButton (string text, Action onClick = null, bool close = true) inline
Definition at line 100 of file Dialog.cs.
    {
        list.AddButton(null, text, delegate
        {
            if (onClick != null)
            {
                onClick();
            }
            if (close)
            {
                Close();
            }
        });
    }
References UIButtonList.AddButton(), Layer.Close(), and list.
Referenced by ListPeopleCallReserve.OnInstantiate().
Choice()
static Dialog Dialog.Choice (string langDetail, Action< Dialog > action) inline static
Definition at line 235 of file Dialog.cs.
    {
        Dialog dialog = Layer.Create<Dialog>();
        dialog.textDetail.SetText(langDetail.lang() + " ");
        action(dialog);
        ELayer.ui.AddLayer(dialog);
        return dialog;
    }
References Layer.Create(), UIText.SetText(), textDetail, and ELayer.ui.
Referenced by ListPeopleCallReserve.OnInstantiate().
Confetti()
static Dialog Dialog.Confetti (string langTitle, string langDetail, string langConfetti = "Grats!") inline static
Definition at line 494 of file Dialog.cs.
    {
        ELayer.Sound.Play("confetti");
        return _Confetti("DialogConfetti", langTitle, langDetail, langConfetti);
    }
References _Confetti(), and ELayer.Sound.
ConfettiSimple()
static Dialog Dialog.ConfettiSimple (string langTitle, string langDetail, string langConfetti = "Grats!") inline static
Definition at line 500 of file Dialog.cs.
    {
        ELayer.Sound.Play("confettiSimple");
        return _Confetti("DialogConfettiSimple", langTitle, langDetail, langConfetti);
    }
References _Confetti(), and ELayer.Sound.
CreateNarration()
static Dialog Dialog.CreateNarration (string idImage, string idText) inline static
Definition at line 212 of file Dialog.cs.
    {
        Dialog dialog = Layer.Create<Dialog>("DialogNarration");
        dialog.image.SetActive(enable: true);
        dialog.image.sprite = Resources.Load<Sprite>("Media/Graphics/Image/Dialog/" + idImage);
        dialog.image.SetNativeSize();
        dialog.textDetail.SetText(IO.LoadText(CorePath.CorePackage.TextNarration + idText + ".txt"));
        return dialog;
    }
References Layer.Create(), image, UIText.SetText(), textDetail, and CorePath.CorePackage.TextNarration.
Referenced by LayerNewZone.Embark().
Gift() [1/3]
static Dialog Dialog.Gift (string langHeader, bool autoAdd, List< Card > list) inline static
Definition at line 425 of file Dialog.cs.
    {
        List<GridItem> list2 = new List<GridItem>();
        foreach (Card item in list)
        {
            list2.Add(new GridItemCard
            {
                c = item
            });
        }
        return Gift(langHeader, autoAdd, list2);
    }
References Gift(), item, and list.
Gift() [2/3]
static Dialog Dialog.Gift (string langHeader, bool autoAdd, List< GridItem > list) inline static
Definition at line 438 of file Dialog.cs.
    {
        Dialog d = Layer.Create<Dialog>();
        d.spacer.SetActive(enable: false);
        d.note.AddHeader(langHeader.IsEmpty("headerGift").lang());
        d.list.AddButton(null, Lang.Get("ok"), delegate
        {
            if (autoAdd)
            {
                foreach (GridItem item in list)
                {
                    item.AutoAdd();
                }
            }
            d.Close();
        });
        d.option.soundActivate = null;
        d.option.canClose = false;
        d.gridItems = list;
        ELayer.Sound.Play("good");
        ELayer.ui.AddLayer(d);
        return d;
    }
References UIButtonList.AddButton(), UINote.AddHeader(), Layer.Close(), Layer.Create(), Lang.Get(), item, list, note, ELayer.Sound, spacer, and ELayer.ui.
Gift() [3/3]
static Dialog Dialog.Gift (string langHeader, bool autoAdd, params Card[] cards) inline static
Definition at line 420 of file Dialog.cs.
    {
        return Gift(langHeader, autoAdd, new List<Card>(cards));
    }
References Gift().
Referenced by Gift(), DramaOutcome.nerun_gift(), DramaOutcome.nerun_gift2(), and DramaOutcome.nerun_gift3().
InputName()
static Dialog Dialog.InputName (string langDetail, string text, Action< bool, string > onClose, InputType inputType = InputType::Default) inline static
Definition at line 528 of file Dialog.cs.
    {
        Dialog d = Layer.Create<Dialog>("DialogInput");
        d.inputType = inputType;
        d.langHint = langDetail;
        d.note.AddText(langDetail.lang()).text1.alignment = TextAnchor.MiddleCenter;
        switch (inputType)
        {
        case InputType.DistributionFilter:
            d.input.field.characterLimit = 100;
            break;
        case InputType.Item:
            d.input.field.characterLimit = 30;
            break;
        case InputType.Password:
            d.input.field.characterLimit = 8;
            d.input.field.contentType = InputField.ContentType.Alphanumeric;
            break;
        }
        d.input.Text = text;
        d.onEnterInput = onClose;
        d.list.AddButton(null, Lang.Get("ok"), delegate
        {
            onClose(arg1: false, d.input.Text);
            d.Close();
        });
        d.list.AddButton(null, Lang.Get("cancel"), delegate
        {
            onClose(arg1: true, "");
            d.Close();
        });
        ELayer.ui.AddLayer(d);
        return d;
    }
References UIButtonList.AddButton(), UINote.AddText(), Layer.Close(), Layer.Create(), Lang.Get(), input, inputType, list, note, UIInputText.Text, and ELayer.ui.
Referenced by ActPlan._Update(), UICharaMaker.EditName(), BaseArea.ListInteractions(), BaseListPeople.OnClick(), HotAction.OnShowContextMenu(), Scene.OnUpdate(), TraitDetector.OnUse(), ContentConfigOther.OpenBackerCodeInput(), ActEffect.Proc(), LayerLoadGame.RefreshInfo(), UIInventory.RefreshMenu(), TraitCoreZone.TrySetAct(), TraitNote.TrySetAct(), TraitTeleporter.TrySetAct(), and TraitWaystone.TrySetAct().
Keymap()
static Dialog Dialog.Keymap (EInput::KeyMap keymap) inline static
Definition at line 519 of file Dialog.cs.
    {
        Dialog dialog = Layer.Create<Dialog>("DialogKeymap");
        dialog.textDetail.SetText("dialog_keymap".lang(("key_" + keymap.action).lang()));
        dialog.keymap = keymap;
        ELayer.ui.AddLayer(dialog);
        return dialog;
    }
References EInput.action, Layer.Create(), keymap, UIText.SetText(), textDetail, and ELayer.ui.
Referenced by ContentConfigInput.OnInstantiate().
List< TValue >()
static Dialog Dialog.List< TValue > (string langDetail, ICollection< TValue > items, Func< TValue, string > getString, Func< int, string, bool > onSelect, bool canCancel = false) inline static
Definition at line 268 of file Dialog.cs.
    {
        Dialog d = Layer.Create<Dialog>();
        d.textDetail.SetText(langDetail.lang() + " ");
        int num = 0;
        foreach (TValue item in items)
        {
            int _i = num;
            d.list.AddButton(null, getString(item).lang(), delegate
            {
                if (onSelect(_i, getString(item)))
                {
                    d.Close();
                }
            });
            num++;
        }
        d.option.canClose = canCancel;
        ELayer.ui.AddLayer(d);
        return d;
    }
References Layer.Create(), item, UIText.SetText(), textDetail, and ELayer.ui.
Ok()
static Dialog Dialog.Ok (string langDetail, Action action = null) inline static
Definition at line 222 of file Dialog.cs.
    {
        Dialog dialog = Layer.Create<Dialog>();
        dialog.textDetail.SetText(langDetail.lang() + " ");
        dialog.list.AddButton(null, Lang.Get("ok"), dialog.Close);
        if (action != null)
        {
            dialog.SetOnKill(action);
        }
        ELayer.ui.AddLayer(dialog);
        return dialog;
    }
References UIButtonList.AddButton(), Layer.Close(), Layer.Create(), Lang.Get(), list, Layer.SetOnKill(), UIText.SetText(), textDetail, and ELayer.ui.
Referenced by Steam.CreateUserContent2(), LayerConfig.Refresh(), and UI.ToggleFeedback().
OnAfterInit()
override void Dialog.OnAfterInit () inline virtual
Reimplemented from Layer.
Definition at line 51 of file Dialog.cs.
    {
        ELayer.ui.hud.textMouseHintRight.transform.parent.SetActive(enable: false);
        textDetail.SetActive(!textDetail.text.IsEmpty());
        listGrid.SetActive(gridItems.Count > 0);
        if (gridItems.Count >= 8)
        {
            GridLayoutGroup obj = listGrid.layoutItems as GridLayoutGroup;
            obj.constraint = GridLayoutGroup.Constraint.FixedColumnCount;
            obj.constraintCount = 8;
        }
        if (gridItems.Count > 0)
        {
            listGrid.Clear();
            listGrid.callbacks = new UIList.Callback<GridItem, ButtonGrid>
            {
                onInstantiate = delegate(GridItem a, ButtonGrid b)
                {
                    b.SetItem(a);
                },
                onClick = delegate(GridItem a, ButtonGrid b)
                {
                    a.OnClick(b);
                }
            };
            foreach (GridItem gridItem in gridItems)
            {
                listGrid.Add(gridItem);
            }
            listGrid.Refresh();
        }
        list.Refresh();
        this.RebuildLayout(recursive: true);
        GraphicRaycaster g = windows[0].GetComponent<GraphicRaycaster>();
        g.enabled = false;
        TweenUtil.Delay(0.3f, delegate
        {
            if ((bool)g)
            {
                g.enabled = true;
            }
        });
        if ((bool)input)
        {
            input.Focus();
        }
        EInput.WaitReleaseKey();
    }
References UIList.Add(), UIList.Clear(), UIInputText.Focus(), gridItems, input, list, listGrid, GridItem.OnClick(), UIList.Refresh(), UIListEx< T >.Refresh(), ButtonGrid.SetItem(), textDetail, ELayer.ui, EInput.WaitReleaseKey(), and Layer.windows.
OnEnterInput()
void Dialog.OnEnterInput () inline
Definition at line 192 of file Dialog.cs.
    {
        isInputEnter = true;
        Close();
    }
References Layer.Close(), and isInputEnter.
OnKill()
override void Dialog.OnKill () inline virtual
Reimplemented from Layer.
Definition at line 198 of file Dialog.cs.
    {
        ELayer.ui.hud.textMouseHintRight.transform.parent.SetActive(enable: true);
        if ((bool)input && onEnterInput != null)
        {
            onEnterInput(!isInputEnter, input.Text);
        }
        if ((bool)input)
        {
            input.field.DeactivateInputField();
        }
        EInput.WaitReleaseKey();
    }
References UIInputText.field, input, isInputEnter, onEnterInput, UIInputText.Text, ELayer.ui, and EInput.WaitReleaseKey().
OnUpdateInput()
override void Dialog.OnUpdateInput () inline virtual
Reimplemented from Layer.
Definition at line 123 of file Dialog.cs.
    {
        if ((bool)input && option.canClose && (Input.GetKeyDown(KeyCode.Return) || Input.GetKeyDown(KeyCode.KeypadEnter)))
        {
            isInputEnter = true;
            Close();
            return;
        }
        if (!input.gameObject.activeInHierarchy && this.list != null)
        {
            foreach (UIList.ButtonPair button in this.list.buttons)
            {
                UIButton uIButton = button.component as UIButton;
                if ((bool)uIButton && uIButton.interactable && !EInput.waitReleaseAnyKey && (bool)uIButton.keyText && !uIButton.keyText.text.IsEmpty() && uIButton.keyText.text == Input.inputString)
                {
                    uIButton.onClick.Invoke();
                    return;
                }
            }
        }
        if (keymap != null)
        {
            List<KeyCode> list = new List<KeyCode>
            {
                KeyCode.Mouse0,
                KeyCode.Mouse1,
                KeyCode.Mouse2,
                KeyCode.Mouse3,
                KeyCode.Mouse4,
                KeyCode.Escape,
                KeyCode.Return,
                KeyCode.LeftShift,
                KeyCode.Delete,
                KeyCode.Backspace
            };
            if (Input.GetKeyDown(KeyCode.Delete))
            {
                if (keymap.required)
                {
                    SE.Beep();
                    return;
                }
                SE.Tab();
                keymap.key = KeyCode.None;
                Close();
                return;
            }
            foreach (KeyCode value in Enum.GetValues(typeof(KeyCode)))
            {
                if (list.Contains(value) || !Input.GetKey(value))
                {
                    continue;
                }
                foreach (EInput.KeyMap item in ELayer.core.config.input.keys.List())
                {
                    if (item.key == value && item.GetGroup() == keymap.GetGroup())
                    {
                        item.key = keymap.key;
                    }
                }
                keymap.key = value;
                SE.Tab();
                Close();
                return;
            }
        }
        base.OnUpdateInput();
    }
References Layer.Option.canClose, Layer.Close(), Core.config, ELayer.core, CoreConfig.input, input, isInputEnter, item, keymap, CoreConfig.InputSetting.keys, UIButton.keyText, list, Layer.option, and EInput.waitReleaseAnyKey.
Recipe()
static Dialog Dialog.Recipe (List< RecipeSource > list) inline static
Definition at line 462 of file Dialog.cs.
    {
        Dialog d = Layer.Create<Dialog>();
        d.spacer.SetActive(enable: false);
        d.note.AddHeader("giftRecipe".lang());
        d.list.AddButton(null, Lang.Get("ok"), delegate
        {
            d.Close();
        });
        d.option.soundActivate = null;
        for (int i = 0; i < list.Count; i++)
        {
            RecipeSource recipeSource = list[i];
            List<Recipe.Ingredient> ingredients = recipeSource.GetIngredients();
            if (ingredients.Count > 0 && ELayer.sources.cards.map.ContainsKey(ingredients[0].id))
            {
                ELayer.sources.cards.map[ingredients[0].id].GetName();
            }
            d.note.AddText("" + recipeSource.Name.ToTitleCase());
            if (i >= 9 && list.Count > 10)
            {
                d.note.Space(6);
                d.note.AddText("moreRecipes".lang((list.Count - 10).ToString() ?? ""));
                break;
            }
        }
        d.SetOnKill(SE.Click);
        ELayer.Sound.Play("idea");
        ELayer.ui.AddLayer(d);
        return d;
    }
References UIButtonList.AddButton(), UINote.AddHeader(), UINote.AddText(), SourceManager.cards, Layer.Close(), Layer.Create(), Lang.Get(), RecipeSource.GetIngredients(), list, SourceCard.map, RecipeSource.Name, note, Layer.SetOnKill(), ELayer.Sound, ELayer.sources, UINote.Space(), spacer, and ELayer.ui.
TryWarn()
static void Dialog.TryWarn (string lang, Action action, bool yes = true) inline static
Definition at line 290 of file Dialog.cs.
    {
        Dialog d = Layer.Create<Dialog>();
        d.textDetail.SetText(lang.lang() + " ");
        d.SetOnKill(delegate
        {
            ELayer.core.actionsNextFrame.Add(delegate
            {
                ActPlan.warning = false;
            });
        });
        d.list.AddButton(null, Lang.Get("yes"), delegate
        {
            d.Close();
            Commit();
        });
        if (yes)
        {
            d.list.AddButton(null, Lang.Get("yes_dontask"), delegate
            {
                switch (lang)
                {
                case "warn_crime":
                    ELayer.core.config.game.ignoreWarnCrime = true;
                    break;
                case "warn_mana":
                    ELayer.core.config.game.ignoreWarnMana = true;
                    break;
                case "warn_disassemble":
                    ELayer.core.config.game.ignoreWarnDisassemble = true;
                    break;
                case "warn_slaughter":
                    ELayer.core.config.game.ignoreWarnSlaughter = true;
                    break;
                }
                d.Close();
                Commit();
            });
        }
        d.list.AddButton(null, Lang.Get("no"), delegate
        {
            d.Close();
        });
        if (!yes)
        {
            d.list.AddButton(null, Lang.Get("no_dontask"), delegate
            {
                string text = lang;
                if (!(text == "warn_parallels"))
                {
                    if (text == "warn_linuxMod")
                    {
                        ELayer.core.config.ignoreLinuxModWarning = true;
                    }
                }
                else
                {
                    ELayer.core.config.ignoreParallelsWarning = true;
                }
                d.Close();
            });
        }
        ELayer.ui.AddLayer(d);
        void Commit()
        {
            warned = true;
            action();
            warned = false;
        }
    }
References BaseCore.actionsNextFrame, UIButtonList.AddButton(), Layer.Close(), ELayer.core, Layer.Create(), Lang.Get(), list, Layer.SetOnKill(), UIText.SetText(), textDetail, ELayer.ui, and warned.
Referenced by TryWarnCrime(), TryWarnDisassemble(), Scene.TryWarnLinuxMod(), Scene.TryWarnMacScreen(), TryWarnMana(), and TryWarnSlaughter().
TryWarnCrime()
static void Dialog.TryWarnCrime (Action action) inline static
Definition at line 376 of file Dialog.cs.
    {
        if (!ELayer.core.config.game.warnCrime || ELayer.core.config.game.ignoreWarnCrime)
        {
            warned = true;
            action();
            warned = false;
            ActPlan.warning = false;
        }
        else
        {
            TryWarn("warn_crime", action);
        }
    }
References Core.config, ELayer.core, CoreConfig.game, CoreConfig.GameConfig.ignoreWarnCrime, TryWarn(), CoreConfig.GameConfig.warnCrime, and warned.
Referenced by ActPlan.Item.Perform().
TryWarnDisassemble()
static void Dialog.TryWarnDisassemble (Action action) inline static
Definition at line 406 of file Dialog.cs.
    {
        if (!ELayer.core.config.game.warnDisassemble || ELayer.core.config.game.ignoreWarnDisassemble)
        {
            warned = true;
            action();
            warned = false;
        }
        else
        {
            TryWarn("warn_disassemble", action);
        }
    }
References Core.config, ELayer.core, CoreConfig.game, CoreConfig.GameConfig.ignoreWarnDisassemble, TryWarn(), CoreConfig.GameConfig.warnDisassemble, and warned.
Referenced by ActPlan.Item.Perform().
TryWarnMana()
static void Dialog.TryWarnMana (Action action) inline static
Definition at line 391 of file Dialog.cs.
    {
        if (!ELayer.core.config.game.warnMana || ELayer.core.config.game.ignoreWarnMana)
        {
            warned = true;
            action();
            warned = false;
            ActPlan.warning = false;
        }
        else
        {
            TryWarn("warn_mana", action);
        }
    }
References Core.config, ELayer.core, CoreConfig.game, CoreConfig.GameConfig.ignoreWarnMana, TryWarn(), warned, and CoreConfig.GameConfig.warnMana.
Referenced by ActRanged.Perform(), and Chara.UseAbility().
TryWarnSlaughter()
static void Dialog.TryWarnSlaughter (Action action) inline static
Definition at line 361 of file Dialog.cs.
    {
        if (ELayer.core.config.game.ignoreWarnSlaughter)
        {
            warned = true;
            action();
            warned = false;
            ActPlan.warning = false;
        }
        else
        {
            TryWarn("warn_slaughter", action);
        }
    }
References Core.config, ELayer.core, CoreConfig.game, CoreConfig.GameConfig.ignoreWarnSlaughter, TryWarn(), and warned.
Referenced by TraitToolButcher.TrySetHeldAct().
Update()
void Dialog.Update () inline private
Definition at line 115 of file Dialog.cs.
    {
        if ((bool)input && option.canClose && Input.GetKeyDown(KeyCode.Escape))
        {
            Close();
        }
    }
References Layer.Option.canClose, Layer.Close(), input, and Layer.option.
YesNo()
static Dialog Dialog.YesNo (string langDetail, Action actionYes, Action actionNo = null, string langYes = "yes", string langNo = "no") inline static
Definition at line 244 of file Dialog.cs.
    {
        Dialog d = Layer.Create<Dialog>();
        d.textDetail.SetText(langDetail.lang() + " ");
        d.list.AddButton(null, Lang.Get(langYes), delegate
        {
            if (actionYes != null)
            {
                actionYes();
            }
            d.Close();
        });
        d.list.AddButton(null, Lang.Get(langNo), delegate
        {
            if (actionNo != null)
            {
                actionNo();
            }
            d.Close();
        });
        ELayer.ui.AddLayer(d);
        return d;
    }
References UIButtonList.AddButton(), Layer.Close(), Layer.Create(), Lang.Get(), list, UIText.SetText(), textDetail, and ELayer.ui.
Referenced by Player.ExitBorder(), Game.GotoTitle(), TraitNewZone.MoveZone(), LayerConfig.OnInit(), LayerMod.OnInit(), TraitDeed.OnRead(), TraitDeedRelocate.OnRead(), WidgetHotbar.OnSetContextMenu(), TraitRope.OnUse(), Game.Quit(), LayerHome.RefreshFeat(), AM_Copy.RefreshMenu(), ContentConfigOther.ResetWindows(), ContentQuest.SelectQuest(), LayerFeedback.Submit(), and TraitCoreZone.TrySetAct().
Member Data Documentation
effect
ScreenEffect Dialog.effect
Definition at line 29 of file Dialog.cs.
gridItems
List<GridItem> Dialog.gridItems = new List<GridItem>()
Definition at line 35 of file Dialog.cs.
Referenced by OnAfterInit().
image
Image Dialog.image
Definition at line 19 of file Dialog.cs.
Referenced by CreateNarration().
input
UIInputText Dialog.input
Definition at line 37 of file Dialog.cs.
Referenced by InputName(), OnAfterInit(), OnKill(), OnUpdateInput(), and Update().
inputType
InputType Dialog.inputType
Definition at line 39 of file Dialog.cs.
Referenced by InputName().
isInputEnter
bool Dialog.isInputEnter
Definition at line 45 of file Dialog.cs.
Referenced by OnEnterInput(), OnKill(), and OnUpdateInput().
keymap
EInput.KeyMap Dialog.keymap
Definition at line 42 of file Dialog.cs.
Referenced by Keymap(), and OnUpdateInput().
layout
LayoutGroup Dialog.layout
Definition at line 27 of file Dialog.cs.
list
UIButtonList Dialog.list
Definition at line 25 of file Dialog.cs.
Referenced by _Confetti(), AddButton(), LayerNewZone.Embark(), Gift(), InputName(), Ok(), OnAfterInit(), OnUpdateInput(), LayerGacha.PlayGacha(), Recipe(), TryWarn(), and YesNo().
listGrid
UIList Dialog.listGrid
Definition at line 31 of file Dialog.cs.
Referenced by OnAfterInit().
note
UINote Dialog.note
Definition at line 23 of file Dialog.cs.
Referenced by Gift(), InputName(), LayerGacha.PlayGacha(), and Recipe().
onEnterInput
Action<bool, string> Dialog.onEnterInput
Definition at line 47 of file Dialog.cs.
Referenced by OnKill().
spacer
Transform Dialog.spacer
Definition at line 33 of file Dialog.cs.
Referenced by Gift(), and Recipe().
textConfetti
Text Dialog.textConfetti
Definition at line 17 of file Dialog.cs.
textDetail
UIText Dialog.textDetail
Definition at line 21 of file Dialog.cs.
Referenced by _Confetti(), Choice(), CreateNarration(), Keymap(), List< TValue >(), Ok(), OnAfterInit(), TryWarn(), and YesNo().
warned
bool Dialog.warned static
Definition at line 49 of file Dialog.cs.
Referenced by ActRanged.Perform(), ActPlan.Item.Perform(), TryWarn(), TryWarnCrime(), TryWarnDisassemble(), TryWarnMana(), TryWarnSlaughter(), and Chara.UseAbility().
The documentation for this class was generated from the following file:
Elin/Dialog.cs