Elin Decompiled Documentation: BaseModManager Class Reference
BaseModManager Class Reference
Classes
class BaseResource
Public Member Functions
virtual void Init (string path, string defaultPackage="_Elona")
void InitLang ()
virtual void ParseExtra (DirectoryInfo dir, BaseModPackage package)
Static Public Member Functions
static void SubscribeEvent (string eventId, Action< object > handler)
static void SubscribeEvent (string eventId, Action handler)
static void SubscribeEvent< T > (string eventId, Action< T > handler)
static void UnsubscribeEvent (string eventId, Action< object > handler)
static void UnsubscribeEvent (string eventId, Action handler)
static void UnsubscribeEvent< T > (string eventId, Action< T > handler)
static void PublishEvent (string eventId, object data=null)
static void PublishEvent< T > (string eventId, T data=default(T))
static bool HasEventSubscriber (string eventId)
Public Attributes
DirectoryInfo dirWorkshop
int priorityIndex
List< BaseModPackage > packages = new List<BaseModPackage>()
Static Public Attributes
static BaseModManager Instance
static string rootMod
static string rootDefaultPacakge
static bool isInitialized
static List< string > listChainLoad = new List<string>()
Static Private Attributes
static readonly Dictionary< string, HashSet< Action< object > > > _eventHandlers = new Dictionary<string, HashSet<Action<object>>>()
static readonly Dictionary<(string, Delegate), Action< object > > _typedEventHandlers = new Dictionary<(string, Delegate), Action<object>>()
Detailed Description
Definition at line 7 of file BaseModManager.cs.
Member Function Documentation
HasEventSubscriber()
static bool BaseModManager.HasEventSubscriber (string eventId) inline static
Definition at line 216 of file BaseModManager.cs.
    {
        int? num = _eventHandlers.GetValueOrDefault(eventId)?.Count;
        if (num.HasValue)
        {
            return num.GetValueOrDefault() > 0;
        }
        return false;
    }
References _eventHandlers.
Init()
virtual void BaseModManager.Init (string path, string defaultPackage = "_Elona") inline virtual
Definition at line 46 of file BaseModManager.cs.
    {
        Debug.Log("Initializing ModManager:" + defaultPackage + "/" + path);
        Instance = this;
        rootMod = (rootDefaultPacakge = path);
        _eventHandlers.Clear();
        _typedEventHandlers.Clear();
        if (!defaultPackage.IsEmpty())
        {
            rootDefaultPacakge = rootMod + defaultPackage + "/";
        }
    }
References _eventHandlers, _typedEventHandlers, Debug, Instance, rootDefaultPacakge, and rootMod.
InitLang()
void BaseModManager.InitLang () inline
Definition at line 59 of file BaseModManager.cs.
    {
        Debug.Log("Initializing Langs: " + Lang.langCode);
        MOD.listAlias.Clear();
        MOD.listName.Clear();
        MOD.listTalk.Clear();
        MOD.listGodTalk.Clear();
        MOD.tones.Clear();
        LangSetting langSetting = MOD.langs.TryGetValue(Lang.langCode);
        if (langSetting == null)
        {
            Debug.LogError("Lang: " + Lang.langCode + " is not set");
            langSetting = MOD.langs.FirstItem();
        }
        FileInfo[] files = new DirectoryInfo(langSetting.dir + "Data").GetFiles();
        foreach (FileInfo fileInfo in files)
        {
            switch (fileInfo.Name)
            {
            case "Alias.xlsx":
                MOD.listAlias.Add(new ExcelData(fileInfo.FullName));
                break;
            case "Name.xlsx":
                MOD.listName.Add(new ExcelData(fileInfo.FullName));
                break;
            case "chara_talk.xlsx":
                MOD.listTalk.Add(new ExcelData(fileInfo.FullName));
                break;
            case "god_talk.xlsx":
                MOD.listGodTalk.Add(new ExcelData(fileInfo.FullName));
                break;
            case "chara_tone.xlsx":
                MOD.tones.Add(new ExcelData(fileInfo.FullName));
                break;
            }
        }
    }
References ExcelDataList.Add(), ExcelDataList.Clear(), Debug, LangSetting.dir, Lang.langCode, MOD.langs, MOD.listAlias, MOD.listGodTalk, MOD.listName, MOD.listTalk, and MOD.tones.
ParseExtra()
virtual void BaseModManager.ParseExtra (DirectoryInfo dir, BaseModPackage package) inline virtual
Definition at line 97 of file BaseModManager.cs.
    {
    }
Referenced by BaseModPackage.Parse().
PublishEvent()
static void BaseModManager.PublishEvent (string eventId, object data = null) inline static
Definition at line 192 of file BaseModManager.cs.
    {
        if (!_eventHandlers.TryGetValue(eventId, out var value))
        {
            return;
        }
        foreach (Action<object> item in value.ToList())
        {
            try
            {
                item(data);
            }
            catch (Exception arg)
            {
                Debug.LogError($"#event '{eventId}' throws error in one of the handlers\n{arg}");
            }
        }
    }
References $, _eventHandlers, Debug, and item.
Referenced by Card._OnDeserialized(), Feat.Apply(), Card.Create(), SourceManager.Init(), Scene.Init(), Game.Load(), Act.Perform(), PublishEvent< T >(), Game.Save(), Core.SetLang(), ReligionManager.SetOwner(), and Game.StartNewGame().
PublishEvent< T >()
static void BaseModManager.PublishEvent< T > (string eventId, T data = default(T)) inline static
Definition at line 211 of file BaseModManager.cs.
    {
        PublishEvent(eventId, (object)data);
    }
References PublishEvent().
SubscribeEvent() [1/2]
static void BaseModManager.SubscribeEvent (string eventId, Action handler) inline static
Definition at line 114 of file BaseModManager.cs.
    {
        if (handler != null)
        {
            Action<object> action = delegate
            {
                handler();
            };
            (string, Delegate) key = (eventId, handler);
            _typedEventHandlers[key] = action;
            SubscribeEvent(eventId, action);
        }
    }
References _typedEventHandlers, and SubscribeEvent().
SubscribeEvent() [2/2]
static void BaseModManager.SubscribeEvent (string eventId, Action< object > handler) inline static
Definition at line 101 of file BaseModManager.cs.
    {
        if (handler != null)
        {
            if (!_eventHandlers.TryGetValue(eventId, out var value))
            {
                value = new HashSet<Action<object>>();
                _eventHandlers[eventId] = value;
            }
            value.Add(handler);
        }
    }
References _eventHandlers.
Referenced by ElinActPerformAttribute.Register(), ElinCharaOnCreateAttribute.Register(), ElinPostLoadAttribute.Register(), ElinPostSaveAttribute.Register(), ElinPostSceneInitAttribute.Register(), ElinPreLoadAttribute.Register(), ElinPreSaveAttribute.Register(), ElinPreSceneInitAttribute.Register(), ElinThingOnCreateAttribute.Register(), ElinGameIOPropertyAttribute.Register(), SubscribeEvent(), and SubscribeEvent< T >().
SubscribeEvent< T >()
static void BaseModManager.SubscribeEvent< T > (string eventId, Action< T > handler) inline static
Definition at line 128 of file BaseModManager.cs.
    {
        if (handler == null)
        {
            return;
        }
        Action<object> action = delegate(object data)
        {
            if (!(data is T obj))
            {
                if (data != null)
                {
                    throw new InvalidCastException($"{handler.Method.DeclaringType?.Assembly.GetName()} " + "expects " + typeof(T).Name + ", got " + data.GetType().Name);
                }
                handler(default(T));
            }
            else
            {
                handler(obj);
            }
        };
        (string, Delegate) key = (eventId, handler);
        _typedEventHandlers[key] = action;
        SubscribeEvent(eventId, action);
    }
References $, _typedEventHandlers, and SubscribeEvent().
UnsubscribeEvent() [1/2]
static void BaseModManager.UnsubscribeEvent (string eventId, Action handler) inline static
Definition at line 166 of file BaseModManager.cs.
    {
        if (handler != null)
        {
            (string, Delegate) key = (eventId, handler);
            if (_typedEventHandlers.TryGetValue(key, out var value))
            {
                UnsubscribeEvent(eventId, value);
                _typedEventHandlers.Remove(key);
            }
        }
    }
References _typedEventHandlers, and UnsubscribeEvent().
UnsubscribeEvent() [2/2]
static void BaseModManager.UnsubscribeEvent (string eventId, Action< object > handler) inline static
Definition at line 154 of file BaseModManager.cs.
    {
        if (_eventHandlers.TryGetValue(eventId, out var value))
        {
            value.Remove(handler);
            if (value.Count == 0)
            {
                _eventHandlers.Remove(eventId);
            }
        }
    }
References _eventHandlers.
Referenced by UnsubscribeEvent(), and UnsubscribeEvent< T >().
UnsubscribeEvent< T >()
static void BaseModManager.UnsubscribeEvent< T > (string eventId, Action< T > handler) inline static
Definition at line 179 of file BaseModManager.cs.
    {
        if (handler != null)
        {
            (string, Delegate) key = (eventId, handler);
            if (_typedEventHandlers.TryGetValue(key, out var value))
            {
                UnsubscribeEvent(eventId, value);
                _typedEventHandlers.Remove(key);
            }
        }
    }
References _typedEventHandlers, and UnsubscribeEvent().
Member Data Documentation
_eventHandlers
readonly Dictionary<string, HashSet<Action<object> > > BaseModManager._eventHandlers = new Dictionary<string, HashSet<Action<object>>>() static private
Definition at line 35 of file BaseModManager.cs.
Referenced by HasEventSubscriber(), Init(), PublishEvent(), SubscribeEvent(), and UnsubscribeEvent().
_typedEventHandlers
readonly Dictionary<(string, Delegate), Action<object> > BaseModManager._typedEventHandlers = new Dictionary<(string, Delegate), Action<object>>() static private
Definition at line 37 of file BaseModManager.cs.
Referenced by Init(), SubscribeEvent(), SubscribeEvent< T >(), UnsubscribeEvent(), and UnsubscribeEvent< T >().
dirWorkshop
DirectoryInfo BaseModManager.dirWorkshop
Definition at line 39 of file BaseModManager.cs.
Instance
BaseModManager BaseModManager.Instance static
Definition at line 25 of file BaseModManager.cs.
Referenced by LayerPickPCC.GetPartProvider(), Init(), BaseModPackage.Parse(), and LayerPickPCC.PartSorter().
isInitialized
bool BaseModManager.isInitialized static
Definition at line 31 of file BaseModManager.cs.
listChainLoad
List<string> BaseModManager.listChainLoad = new List<string>() static
Definition at line 33 of file BaseModManager.cs.
Referenced by ModManager.ActivatePackages().
packages
List<BaseModPackage> BaseModManager.packages = new List<BaseModPackage>()
Definition at line 44 of file BaseModManager.cs.
Referenced by LayerPickPCC.GetPartProvider(), and LayerPickPCC.PartSorter().
priorityIndex
int BaseModManager.priorityIndex
Definition at line 41 of file BaseModManager.cs.
rootDefaultPacakge
string BaseModManager.rootDefaultPacakge static
Definition at line 29 of file BaseModManager.cs.
Referenced by ModManager.Init(), and Init().
rootMod
string BaseModManager.rootMod static
Definition at line 27 of file BaseModManager.cs.
Referenced by ModManager.Init(), Init(), ModManager.LoadLocalPackages(), and LayerMod.OnInit().
The documentation for this class was generated from the following file:
Elin/Plugins.basecore/BaseModManager.cs