Elin Decompiled Documentation: ZonePreEnterOnCompleteQuestInstance Class Reference
ZonePreEnterOnCompleteQuestInstance Class Reference
Public Member Functions
override void Execute ()
virtual void Execute ()
Public Attributes
int uidClient
int uidQuest
bool fail
Additional Inherited Members
Static Public Member Functions inherited from EClass
static int rnd (int a)
static int curve (int a, int start, int step, int rate=75)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Static Public Attributes inherited from EClass
static Core core
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Detailed Description
Definition at line 4 of file ZonePreEnterOnCompleteQuestInstance.cs.
Member Function Documentation
Execute()
override void ZonePreEnterOnCompleteQuestInstance.Execute () inline virtual
Reimplemented from ZonePreEnterEvent.
Definition at line 6 of file ZonePreEnterOnCompleteQuestInstance.cs.
    {
        EClass.player.returnInfo = null;
        if (this.uidQuest == 0)
        {
            return;
        }
        Quest quest = EClass.game.quests.Get(this.uidQuest);
        Chara chara = EClass._map.FindChara(this.uidClient);
        if (chara == null)
        {
            chara = EClass._map.deadCharas.Find((Chara c) => c.uid == this.uidClient);
            if (chara == null)
            {
                string[] array = new string[7];
                array[0] = this.uidClient.ToString();
                array[1] = "/";
                array[2] = this.uidQuest.ToString();
                array[3] = "/";
                array[4] = this.fail.ToString();
                array[5] = "/";
                int num = 6;
                Quest quest2 = quest;
                array[num] = ((quest2 != null) ? quest2.ToString() : null);
                Debug.Log(string.Concat(array));
                string str = "exception: quest not found:";
                Chara chara2 = chara;
                string str2 = (chara2 != null) ? chara2.ToString() : null;
                string str3 = "/";
                Quest quest3 = (chara != null) ? chara.quest : null;
                Debug.LogError(str + str2 + str3 + ((quest3 != null) ? quest3.ToString() : null));
                return;
            }
            chara.Revive(null, false);
        }
        if (chara.quest == null)
        {
            if (quest != null)
            {
                chara.quest = quest;
            }
            string[] array2 = new string[7];
            array2[0] = this.uidClient.ToString();
            array2[1] = "/";
            array2[2] = this.uidQuest.ToString();
            array2[3] = "/";
            array2[4] = this.fail.ToString();
            array2[5] = "/";
            int num2 = 6;
            Quest quest4 = quest;
            array2[num2] = ((quest4 != null) ? quest4.ToString() : null);
            Debug.Log(string.Concat(array2));
            string str4 = "exception: assigned quest to:";
            Chara chara3 = chara;
            Debug.LogWarning(str4 + ((chara3 != null) ? chara3.ToString() : null));
        }
        if (quest == null && chara.quest.uid == this.uidQuest)
        {
            quest = chara.quest;
        }
        if (quest == null)
        {
            return;
        }
        if (this.fail)
        {
            quest.Fail();
        }
        else
        {
            quest.Complete();
        }
        if (EClass.pc.IsAliveInCurrentZone)
        {
            chara.ShowDialog("_chara", this.fail ? "quest_fail" : "quest_success", "");
        }
    }
References EClass._map, Quest.Complete(), Map.deadCharas, Quest.Fail(), fail, Map.FindChara(), EClass.game, QuestManager.Get(), Chara.IsAliveInCurrentZone, EClass.pc, Chara.quest, Game.quests, Chara.Revive(), Chara.ShowDialog(), Chara.ToString(), Card.uid, Quest.uid, uidClient, and uidQuest.
Member Data Documentation
fail
bool ZonePreEnterOnCompleteQuestInstance.fail
Definition at line 88 of file ZonePreEnterOnCompleteQuestInstance.cs.
Referenced by Execute().
uidClient
int ZonePreEnterOnCompleteQuestInstance.uidClient
Definition at line 84 of file ZonePreEnterOnCompleteQuestInstance.cs.
Referenced by Execute().
uidQuest
int ZonePreEnterOnCompleteQuestInstance.uidQuest
Definition at line 86 of file ZonePreEnterOnCompleteQuestInstance.cs.
Referenced by Execute().
The documentation for this class was generated from the following file:
Elin/ZonePreEnterOnCompleteQuestInstance.cs