Elin Decompiled Documentation: GridItemCard Class Reference
GridItemCard Class Reference
Public Member Functions
override void SetButton (ButtonGrid b)
override void OnClick (ButtonGrid b)
override void AutoAdd ()
virtual void SetButton (ButtonGrid b)
virtual void OnClick (ButtonGrid b)
virtual void AutoAdd ()
Public Attributes
Card c
Additional Inherited Members
Static Public Member Functions inherited from EClass
static int rndSeed (int a, int seed)
static int rnd (long a)
static int rnd (int a)
static int curve (int a, int start, int step, int rate=75)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Static Public Attributes inherited from EClass
static Core core
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Detailed Description
Definition at line 1 of file GridItemCard.cs.
Member Function Documentation
AutoAdd()
override void GridItemCard.AutoAdd () inline virtual
Reimplemented from GridItem.
Definition at line 20 of file GridItemCard.cs.
    {
        EClass.player.AddInventory(c);
    }
References Player.AddInventory(), c, and EClass.player.
OnClick()
override void GridItemCard.OnClick (ButtonGrid b) inline virtual
Reimplemented from GridItem.
Definition at line 15 of file GridItemCard.cs.
    {
        EClass.ui.AddLayer<LayerInfo>().Set(c);
    }
References Layer.AddLayer(), c, and EClass.ui.
SetButton()
override void GridItemCard.SetButton (ButtonGrid b) inline virtual
Reimplemented from GridItem.
Definition at line 5 of file GridItemCard.cs.
    {
        b.mainText.text = c.Num.ToShortNumber();
        c.SetImage(b.icon);
        b.SetTooltip("note", delegate(UITooltip t)
        {
            c.WriteNote(t.note);
        });
    }
References c, UIButton.icon, UITooltip.note, Card.Num, Card.SetImage(), UIButton.SetTooltip(), and Card.WriteNote().
Member Data Documentation
c
Card GridItemCard.c
Definition at line 3 of file GridItemCard.cs.
Referenced by AutoAdd(), OnClick(), and SetButton().
The documentation for this class was generated from the following file:
Elin/GridItemCard.cs