Elin Decompiled Documentation: TextureManager Class Reference
TextureManager Class Reference
Public Member Functions
void Init ()
void AddBase (TextureData data, string path, MeshPass pass, string texName="_MainTex")
void Add (MeshPass to, TextureData from, string texName="_MainTex")
void AddList (TextureData data, string path)
void RefreshTextures ()
void OnDropFile (List< string > paths)
bool TryAddReplace (FileInfo file, TextureReplace.Source source=TextureReplace.Source.Mod, bool add=true, bool refresh=false)
void ApplyLocalReplace (string path)
Public Attributes
Dictionary< string, TextureData > texMap = new Dictionary<string, TextureData>()
Properties
string pathTex [get]
Detailed Description
Definition at line 5 of file TextureManager.cs.
Member Function Documentation
Add()
void TextureManager.Add (MeshPass to, TextureData from, string texName = "_MainTex") inline
Definition at line 77 of file TextureManager.cs.
    {
        this.texMap[from.id].listPass.Add(to);
    }
References TextureData.id, and texMap.
Referenced by Init().
AddBase()
void TextureManager.AddBase (TextureData data, string path, MeshPass pass, string texName = "_MainTex") inline
Definition at line 66 of file TextureManager.cs.
    {
        this.texMap[data.id] = data;
        data.path = this.pathTex + path;
        data.texName = texName;
        data.dictReplace.Clear();
        data.tileW = data.tex.width / (int)pass.pmesh.tiling.x;
        data.tileH = data.tex.height / (int)pass.pmesh.tiling.y;
        this.texMap[data.id].listPass.Add(pass);
    }
References TextureData.dictReplace, TextureData.id, MeshPass.pmesh, TextureData.tex, texMap, TextureData.tileH, and ProceduralMesh.tiling.
Referenced by Init().
AddList()
void TextureManager.AddList (TextureData data, string path) inline
Definition at line 82 of file TextureManager.cs.
    {
        data.path = this.pathTex + path;
        this.texMap[data.id] = data;
    }
References TextureData.id, and texMap.
Referenced by Init().
ApplyLocalReplace()
void TextureManager.ApplyLocalReplace (string path) inline
Definition at line 166 of file TextureManager.cs.
    {
        foreach (TextureData textureData in this.texMap.Values)
        {
            if (textureData.listReplaceLocal.Count > 0)
            {
                textureData.forceRefresh = true;
                foreach (TextureReplace textureReplace in textureData.listReplaceLocal)
                {
                    textureReplace.DestoryTex();
                    if (textureReplace.original != null)
                    {
                        textureData.dictReplace[textureReplace.index] = textureReplace.original;
                    }
                    else
                    {
                        textureData.dictReplace.Remove(textureReplace.index);
                    }
                }
            }
            textureData.listReplaceLocal.Clear();
        }
        string path2 = path + "Texture Replace";
        if (Directory.Exists(path2))
        {
            foreach (FileInfo file in new DirectoryInfo(path2).GetFiles())
            {
                this.TryAddReplace(file, TextureReplace.Source.Local, true, false);
            }
        }
        this.RefreshTextures();
    }
References TextureReplace.DestoryTex(), TextureData.dictReplace, TextureReplace.index, TextureData.listReplaceLocal, TextureReplace.original, RefreshTextures(), texMap, and TryAddReplace().
Init()
void TextureManager.Init () inline
Definition at line 15 of file TextureManager.cs.
    {
        BaseTileMap tileMap = EClass.scene.screenElin.tileMap;
        CoreRef.TextureDatas textureData = EClass.core.refs.textureData;
        this.AddBase(textureData.block, "blocks.png", tileMap.passBlock, "_MainTex");
        this.AddBase(textureData.floor, "floors.png", tileMap.passFloor, "_MainTex");
        this.AddBase(textureData.objs_SS, "objs_SS.png", tileMap.passObjSS, "_MainTex");
        this.AddBase(textureData.objs_S, "objs_S.png", tileMap.passObjS, "_MainTex");
        this.AddBase(textureData.objs, "objs.png", tileMap.passObj, "_MainTex");
        this.AddBase(textureData.objs_L, "objs_L.png", tileMap.passObjL, "_MainTex");
        this.AddBase(textureData.roofs, "roofs.png", tileMap.passRoof, "_MainTex");
        this.AddBase(textureData.shadows, "shadows.png", tileMap.passShadow, "_MainTex");
        this.AddBase(textureData.fov, "fov.png", tileMap.passFov, "_MainTex");
        this.AddBase(textureData.objs_C, "objs_C.png", tileMap.passChara, "_MainTex");
        this.AddBase(textureData.objs_CLL, "objs_CLL.png", tileMap.passCharaLL, "_MainTex");
        this.AddBase(textureData.block_snow, "blocks_snow.png", tileMap.passBlock.snowPass, "_MainTex");
        this.AddBase(textureData.floor_snow, "floors_snow.png", tileMap.passFloor.snowPass, "_MainTex");
        this.AddBase(textureData.objs_S_snow, "objs_S_snow.png", tileMap.passObjS.snowPass, "_MainTex");
        this.AddBase(textureData.objs_snow, "objs_snow.png", tileMap.passObj.snowPass, "_MainTex");
        this.AddBase(textureData.objs_L_snow, "objs_L_snow.png", tileMap.passObjL.snowPass, "_MainTex");
        this.Add(tileMap.passRamp, textureData.block, "_MainTex");
        this.Add(tileMap.passWaterBlock, textureData.block, "_MainTex");
        this.Add(tileMap.passFog, textureData.block, "_MainTex");
        this.Add(tileMap.passLiquid, textureData.block, "_MainTex");
        this.Add(tileMap.passBlockEx, textureData.block, "_MainTex");
        this.Add(tileMap.passInner, textureData.block, "_MainTex");
        this.Add(tileMap.passBlockMarker, textureData.block, "_MainTex");
        this.Add(tileMap.passEdge, textureData.floor, "_MainTex");
        this.Add(tileMap.passFloorEx, textureData.floor, "_MainTex");
        this.Add(tileMap.passFloorWater, textureData.floor, "_MainTex");
        this.Add(tileMap.passAutoTile, textureData.floor, "_MainTex");
        this.Add(tileMap.passShore, textureData.floor, "_MainTex");
        this.Add(tileMap.passAutoTileWater, textureData.floor, "_MainTex");
        this.Add(tileMap.passFloorMarker, textureData.floor, "_MainTex");
        this.Add(tileMap.passCharaL, textureData.objs_C, "_MainTex");
        this.Add(tileMap.passIcon, textureData.objs_S, "_MainTex");
        this.AddList(textureData.world, "world.png");
        this.AddList(textureData.bird, "bird1.png");
        foreach (FileInfo fileInfo in new DirectoryInfo(CorePath.user + "/Texture Replace").GetFiles())
        {
            if (fileInfo.Name.EndsWith(".png"))
            {
                this.TryAddReplace(fileInfo, TextureReplace.Source.User, true, false);
            }
        }
        foreach (FileInfo file in EClass.core.mods.replaceFiles)
        {
            this.TryAddReplace(file, TextureReplace.Source.Mod, true, false);
        }
    }
References Add(), AddBase(), AddList(), CoreRef.TextureDatas.bird, CoreRef.TextureDatas.block, CoreRef.TextureDatas.block_snow, EClass.core, CoreRef.TextureDatas.floor, CoreRef.TextureDatas.floor_snow, CoreRef.TextureDatas.fov, CoreRef.TextureDatas.objs, CoreRef.TextureDatas.objs_C, CoreRef.TextureDatas.objs_CLL, CoreRef.TextureDatas.objs_L, CoreRef.TextureDatas.objs_L_snow, CoreRef.TextureDatas.objs_S, CoreRef.TextureDatas.objs_S_snow, CoreRef.TextureDatas.objs_snow, CoreRef.TextureDatas.objs_SS, BaseTileMap.passAutoTile, BaseTileMap.passAutoTileWater, BaseTileMap.passBlock, BaseTileMap.passBlockEx, BaseTileMap.passBlockMarker, BaseTileMap.passChara, BaseTileMap.passCharaL, BaseTileMap.passCharaLL, BaseTileMap.passEdge, BaseTileMap.passFloor, BaseTileMap.passFloorEx, BaseTileMap.passFloorMarker, BaseTileMap.passFloorWater, BaseTileMap.passFog, BaseTileMap.passFov, BaseTileMap.passIcon, BaseTileMap.passInner, BaseTileMap.passLiquid, BaseTileMap.passObj, BaseTileMap.passObjL, BaseTileMap.passObjS, BaseTileMap.passObjSS, BaseTileMap.passRamp, BaseTileMap.passRoof, BaseTileMap.passShadow, BaseTileMap.passShore, BaseTileMap.passWaterBlock, CoreRef.TextureDatas.roofs, EClass.scene, Scene.screenElin, CoreRef.TextureDatas.shadows, MeshPass.snowPass, BaseGameScreen.tileMap, TryAddReplace(), and CoreRef.TextureDatas.world.
OnDropFile()
void TextureManager.OnDropFile (List< string > paths) inline
Definition at line 100 of file TextureManager.cs.
    {
        int num = 0;
        foreach (string fileName in paths)
        {
            FileInfo fileInfo = new FileInfo(fileName);
            if (this.TryAddReplace(fileInfo, TextureReplace.Source.User, false, false))
            {
                string text = CorePath.user + "/Texture Replace/" + fileInfo.Name;
                try
                {
                    if (File.Exists(text))
                    {
                        File.Delete(text);
                    }
                    fileInfo.CopyTo(text, true);
                }
                catch (Exception)
                {
                }
                this.TryAddReplace(new FileInfo(text), TextureReplace.Source.User, true, true);
                num++;
            }
        }
        Msg.Say("Imported " + num.ToString() + "image(s)");
    }
References Msg.Say(), text, and TryAddReplace().
Referenced by Core.Awake().
RefreshTextures()
void TextureManager.RefreshTextures () inline
Definition at line 88 of file TextureManager.cs.
    {
        foreach (TextureData textureData in this.texMap.Values)
        {
            textureData.TryRefresh();
        }
        if (EClass.core.IsGameStarted && EClass._zone != null && EClass._zone.isStarted)
        {
            EClass.scene.ApplyZoneConfig();
        }
    }
References EClass._zone, Scene.ApplyZoneConfig(), EClass.core, Zone.isStarted, EClass.scene, texMap, and TextureData.TryRefresh().
Referenced by ApplyLocalReplace(), Core.OnApplicationFocus(), and Core.Update().
TryAddReplace()
bool TextureManager.TryAddReplace (FileInfo file, TextureReplace::Source source = TextureReplace::Source::Mod, bool add = true, bool refresh = false) inline
Definition at line 127 of file TextureManager.cs.
    {
        string[] array = Path.GetFileNameWithoutExtension(file.Name).Split('_', StringSplitOptions.None);
        if (array.Length == 1)
        {
            return false;
        }
        string key = array[0];
        int index;
        if (!int.TryParse(array[1], out index))
        {
            return false;
        }
        if (!this.texMap.ContainsKey(key))
        {
            return false;
        }
        TextureData textureData = this.texMap[key];
        if (textureData.listPass.Count == 0)
        {
            return false;
        }
        if (add)
        {
            textureData.AddReplace(new TextureReplace
            {
                file = file,
                index = index,
                data = textureData,
                source = source
            });
            if (refresh)
            {
                textureData.TryRefresh();
            }
        }
        return true;
    }
References TextureData.AddReplace(), TextureData.listPass, texMap, and TextureData.TryRefresh().
Referenced by ApplyLocalReplace(), Init(), and OnDropFile().
Member Data Documentation
texMap
Dictionary<string, TextureData> TextureManager.texMap = new Dictionary<string, TextureData>()
Definition at line 199 of file TextureManager.cs.
Referenced by Add(), AddBase(), AddList(), ApplyLocalReplace(), RefreshTextures(), and TryAddReplace().
Property Documentation
pathTex
string TextureManager.pathTex get
Definition at line 7 of file TextureManager.cs.
    {
        get
        {
            return CorePath.packageCore + "Texture/";
        }
    }
The documentation for this class was generated from the following file:
Elin/TextureManager.cs