Elin Decompiled Documentation: ActRide Class Reference
ActRide Class Reference
Public Member Functions
override bool Perform ()
Public Member Functions inherited from Ability
override bool CanLink (ElementContainer owner)
override int GetSourceValue (int v, int lv, SourceValueType type)
override int GetPower (Card c)
override void OnChangeValue ()
Public Member Functions inherited from Act
virtual CursorInfo GetCursorIcon (Card c)
virtual MultiSprite GetStateIcon ()
override Sprite GetSprite ()
virtual bool ShowMouseHint (Card c)
virtual bool IsValidTC (Card c)
virtual string GetHintText (string str="")
virtual string GetText (string str="")
virtual string GetTextSmall (Card c)
bool IsTargetHostileParty ()
virtual Color GetActPlanColor ()
virtual bool Perform ()
virtual bool CanPerform ()
bool Perform (Chara _cc, Card _tc=null, Point _tp=null)
bool CanPerform (Chara _cc, Card _tc=null, Point _tp=null)
virtual bool IsToolValid ()
new void SetImage (Image image)
virtual void OnMarkMapHighlights ()
virtual bool ShouldMapHighlight (Point p)
Public Member Functions inherited from Element
virtual SourceElement.Row GetSource ()
virtual int GetSourcePotential (int v)
virtual Sprite GetSprite ()
int GetMaterialSourceValue (Thing t, int v)
virtual int GetSourceValue (int v, int lv, SourceValueType type)
virtual Sprite GetIcon (string suffix="")
bool IsActive (Card c)
int SortVal (bool charaSheet=false)
virtual bool CanLink (ElementContainer owner)
bool HasTag (string tag)
void SetImage (Image i)
virtual string GetDetail ()
bool IsFactionElement (Chara c)
Element GetParent (Card c)
void WriteNote (UINote n, ElementContainer owner=null, Action< UINote > onWriteNote=null)
void WriteNoteWithRef (UINote n, ElementContainer owner, Action< UINote > onWriteNote, Element refEle)
void _WriteNote (UINote n, Chara c, Act act)
void AddHeaderAbility (UINote n)
void _WriteNote (UINote n, ElementContainer owner, Action< UINote > onWriteNote, bool isRef, bool addHeader=true)
void AddEncNote (UINote n, Card Card, ElementContainer.NoteMode mode=ElementContainer.NoteMode.Default, Func< Element, string, string > funcText=null, Action< UINote, Element > onAddNote=null)
virtual void OnWriteNote (UINote n, ElementContainer owner)
virtual void OnChangeValue ()
void CheckLevelBonus (ElementContainer owner, UINote n=null)
int GetSortVal (UIList.SortMode m)
virtual Act.Cost GetCost (Chara c)
virtual int GetPower (Card c)
virtual void SetTextValue (UIText text)
virtual bool IsPurchaseFeatReqMet (ElementContainer owner, int lv=-1)
virtual void WritePurchaseReq (UINote n, int lv=1)
Static Public Member Functions
static void Ride (Chara host, Chara t, bool parasite=false, bool talk=true)
static void Unride (Chara host, Chara mount, bool talk=true)
static void Unride (Chara host, bool parasite=false, bool talk=true)
Static Public Member Functions inherited from Act
static void SetReference (Chara _cc, Card _tc=null, Point _tp=null)
static void SetTool (Thing t)
Static Public Member Functions inherited from Element
static string GetName (string alias)
static SourceElement.Row Get (int id)
static Dictionary< int, int > GetElementMap (int[] list)
static Dictionary< int, int > GetElementMap (int[] list, Dictionary< int, int > map)
static SourceElement.Row GetRandomElement (int lv=1)
static Element Create (int id, int v=0)
static Element Create (string id, int v=1)
static int GetId (string alias)
static int GetResistLv (int v)
static int GetResistDamage (int dmg, int v, int power=0)
Static Public Member Functions inherited from EClass
static int rndSeed (int a, int seed)
static int rnd (int a)
static int curve (int a, int start, int step, int rate=75)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Properties
virtual bool IsParasite [get]
Properties inherited from Ability
override bool ShowBonuses [get]
override bool CanPressRepeat [get]
Properties inherited from Act
override bool ShowPotential [get]
override bool UsePotential [get]
override bool ShowRelativeAttribute [get]
virtual CursorInfo CursorIcon [get]
virtual string ID [get]
virtual bool IsAct [get]
virtual bool WillEndTurn [get]
virtual bool CloseLayers [get]
virtual int LeftHand [get]
virtual int RightHand [get]
virtual int ElementPowerMod [get]
virtual bool ShowMapHighlight [get]
virtual bool ShowMapHighlightBlock [get]
virtual bool PickHeldOnStart [get]
virtual bool DropHeldOnStart [get]
virtual bool CanPressRepeat [get]
virtual bool CanAutofire [get]
virtual bool ResetAxis [get]
virtual bool RequireTool [get]
virtual bool IsHostileAct [get]
virtual bool HideRightInfo [get]
virtual bool HaveLongPressAction [get]
virtual float Radius [get]
virtual int PerformDistance [get]
virtual int MaxRadius [get]
virtual TargetType TargetType [get]
virtual bool LocalAct [get]
virtual bool CanRapidFire [get]
virtual float RapidDelay [get]
virtual bool ShowAuto [get]
virtual bool IsCrime [get]
Properties inherited from Element
SourceElement.Row source [get]
virtual int DisplayValue [get]
virtual int MinValue [get]
int Value [get]
int ValueWithoutLink [get]
virtual int MinPotential [get]
int Potential [get]
virtual bool CanGainExp [get]
bool IsFlag [get]
virtual string Name [get]
virtual string FullName [get]
virtual int ExpToNext [get]
virtual bool UseExpMod [get]
virtual int CostTrain [get]
virtual int CostLearn [get]
virtual bool ShowXP [get]
virtual bool ShowMsgOnValueChanged [get]
virtual bool ShowValue [get]
virtual bool ShowPotential [get]
virtual bool UsePotential [get]
virtual bool PotentialAsStock [get]
virtual bool ShowRelativeAttribute [get]
virtual bool ShowBonuses [get]
virtual string ShortName [get]
bool IsGlobalElement [get]
bool IsFactionWideElement [get]
bool IsPartyWideElement [get]
virtual bool ShowEncNumber [get]
bool IsTrait [get]
bool IsFoodTrait [get]
bool IsFoodTraitMain [get]
bool IsMainAttribute [get]
Act act [get]
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Additional Inherited Members
Public Types inherited from Act
enum CostType { None , MP , SP }
Public Attributes inherited from Element
SourceElement.Row _source
int id
int vBase
int vExp
int vPotential
int vTempPotential
int vLink
int vSource
int vSourcePotential
ElementContainer owner
Static Public Attributes inherited from Act
static Chara CC
static Card TC
static Point TP = new Point()
static Thing TOOL
static int powerMod = 100
static bool forcePt
static Act CurrentAct
Static Public Attributes inherited from Element
const int Div = 5
static Element Void = new Element()
static int[] List_MainAttributes = new int[9] { 70, 72, 71, 77, 74, 75, 76, 73, 79 }
static int[] List_MainAttributesMajor = new int[8] { 70, 72, 71, 77, 74, 75, 76, 73 }
static int[] List_Body = new int[4] { 70, 72, 71, 77 }
static int[] List_Mind = new int[4] { 74, 75, 76, 73 }
static List< SourceElement.Row > ListElements = new List<SourceElement.Row>()
static List< SourceElement.Row > ListAttackElements = new List<SourceElement.Row>()
Static Public Attributes inherited from EClass
static Core core
Detailed Description
Definition at line 3 of file ActRide.cs.
Member Function Documentation
Perform()
override bool ActRide.Perform () inline virtual
Reimplemented from Act.
Definition at line 7 of file ActRide.cs.
    {
        List<Chara> list = Act.TP.ListCharas();
        list.Reverse();
        bool flag = false;
        foreach (Chara item in list)
        {
            if (item.host != null || item.IsMultisize)
            {
                continue;
            }
            if (item == Act.CC)
            {
                if ((IsParasite && Act.CC.parasite != null) || (!IsParasite && Act.CC.ride != null))
                {
                    Unride(Act.CC, IsParasite);
                    flag = true;
                    break;
                }
                continue;
            }
            if (!item.trait.CanJoinPartyResident)
            {
                Msg.Say("ride_req");
                return false;
            }
            if (item.memberType == FactionMemberType.Default && (EClass.debug.enable || (item.IsPCFaction && item.trait.CanJoinParty)))
            {
                Ride(Act.CC, item, IsParasite);
                flag = true;
                break;
            }
        }
        if (!flag)
        {
            Msg.Say("noTargetFound");
        }
        return false;
    }
References Act.CC, EClass.debug, CoreDebug.enable, IsParasite, item, Point.ListCharas(), Chara.parasite, Ride, Chara.ride, Msg.Say(), Act.TP, and Unride().
Ride()
static void ActRide.Ride (Chara host, Chara t, bool parasite = false, bool talk = true) inline static
Definition at line 47 of file ActRide.cs.
    {
        if (parasite)
        {
            if (host.parasite != null)
            {
                Unride(host, parasite: true);
            }
            host.parasite = t;
            host.Say("parasite", host, t);
        }
        else
        {
            if (host.ride != null)
            {
                Unride(host);
            }
            host.ride = t;
            host.Say("ride", host, t);
        }
        if (!t.IsPCFaction)
        {
            t.MakeAlly();
        }
        EClass.pc.party.AddMemeber(t);
        if (!parasite)
        {
            if (t.race.tag.Contains("ride"))
            {
                Msg.Say("ride_good");
            }
            if (t.race.tag.Contains("noRide"))
            {
                Msg.Say("ride_bad");
            }
            if (host.HasElement(1417) && t.HasCondition<ConTransmuteBroom>())
            {
                Msg.Say("ride_broom");
            }
        }
        t.host = host;
        t._CreateRenderer();
        if (talk)
        {
            host.PlaySound("ride");
            t.Talk(parasite ? "parasite" : "ride");
        }
        host.SetDirtySpeed();
        t.SetDirtySpeed();
        host.SyncRide();
        t.noMove = false;
        host.Refresh();
    }
References Chara._CreateRenderer(), Party.AddMemeber(), Chara.HasCondition(), Card.HasElement(), Chara.IsPCFaction, Chara.MakeAlly(), Chara.parasite, Chara.party, EClass.pc, Card.PlaySound(), Chara.race, Chara.Refresh(), Chara.ride, Msg.Say(), Card.Say(), Chara.SetDirtySpeed(), Chara.SyncRide(), Card.Talk(), and Unride().
Referenced by TraitHitchingPost.OnActivateTrap(), and ConSleep.OnRemoved().
Unride() [1/2]
static void ActRide.Unride (Chara host, bool parasite = false, bool talk = true) inline static
Definition at line 109 of file ActRide.cs.
    {
        Chara chara = null;
        if (parasite)
        {
            chara = host.parasite;
            host.parasite = null;
            host.Say("parasite_unride", host, chara);
        }
        else
        {
            chara = host.ride;
            host.ride = null;
            host.Say("ride_unride", host, chara);
        }
        chara.host = null;
        chara._CreateRenderer();
        if (talk)
        {
            chara.Talk(parasite ? "parasite_unride" : "ride_unride", null, null, forceSync: true);
        }
        host.PlaySound("ride");
        host.SetDirtySpeed();
        chara.SetDirtySpeed();
        host.Refresh();
        Point randomPoint = host.pos.GetRandomPoint(1);
        if (randomPoint != null)
        {
            chara.MoveImmediate(randomPoint);
        }
    }
References Chara._CreateRenderer(), Point.GetRandomPoint(), Card.MoveImmediate(), Chara.parasite, Card.PlaySound(), Card.pos, Chara.Refresh(), Chara.ride, Card.Say(), Chara.SetDirtySpeed(), and Card.Talk().
Unride() [2/2]
static void ActRide.Unride (Chara host, Chara mount, bool talk = true) inline static
Definition at line 101 of file ActRide.cs.
    {
        if (host != null && (host.parasite == mount || host.ride == mount))
        {
            Unride(host, host.parasite == mount, talk);
        }
    }
References Chara.parasite, Chara.ride, and Unride().
Referenced by TraitHitchingPost.OnActivateTrap(), Perform(), Party.RemoveMember(), Ride(), AI_Slaughter.Run(), ConSleep.Tick(), and Unride().
Property Documentation
IsParasite
virtual bool ActRide.IsParasite get
Definition at line 5 of file ActRide.cs.
Referenced by Perform().
The documentation for this class was generated from the following file:
Elin/ActRide.cs