Elin Decompiled Documentation: ElementContainerZone Class Reference
ElementContainerZone Class Reference
Public Member Functions
override void OnLearn (int ele)
override void OnLevelUp (Element e, int lastValue)
Public Member Functions inherited from ElementContainer
void ApplyElementMap (int uid, SourceValueType type, Dictionary< int, int > map, int lv, bool invert=false, bool applyFeat=false)
void ApplyMaterialElementMap (Thing t, bool invert=false)
void ImportElementMap (Dictionary< int, int > map)
ElementContainer ImportElementMap (int[] ints)
void ApplyPotential (int mode=0)
int Value (int ele)
virtual int ValueBonus (Element e)
int ValueWithoutLink (int ele)
int ValueWithoutLink (string alias)
int GetFeatRef (int ele, int idx=0)
int Exp (int ele)
bool Has (int ele)
bool Has (SourceElement.Row row)
bool Has (string alias)
bool HasBase (int ele)
int Base (int ele)
void Learn (int ele, int v=1)
void Train (int ele, int a=10)
void ModExp (int ele, int a, bool chain=false)
virtual void OnLearn (int ele)
virtual void OnTrain (int ele)
virtual void OnLevelUp (Element e, int lastValue)
virtual void OnLevelDown (Element e, int lastValue)
Element SetBase (string alias, int v, int potential=0)
Element SetBase (int id, int v, int potential=0)
void SetTo (int id, int v)
void Remove (int id)
Element ModBase (int ele, int v)
virtual void OnChangeValue ()
Element ModPotential (int ele, int v)
Element ModTempPotential (int ele, int v, int threshMsg=0)
virtual void OnModTempPotential (Element e, int v, int threshMsg)
int GetSpellExp (Chara c, Element e, int costMod=100)
Element GetElement (string alias)
Element GetElement (int id)
Element CreateElement (int id)
Element GetOrCreateElement (Element ele)
Element GetOrCreateElement (string alias)
Element GetOrCreateElement (int id)
void SetParent (Card c)
void SetParent (ElementContainer newParent=null)
List< Element > ListElements (Func< Element, bool > shoudList=null, Comparison< Element > comparison=null)
List< Element > ListBestAttributes ()
List< Element > ListBestSkills ()
List< Element > ListGeneFeats ()
List< Element > ListLearnable (Chara c)
void CopyTo (ElementContainer container)
void AddNote (UINote n, Func< Element, bool > isValid=null, Action onAdd=null, NoteMode mode=NoteMode.Default, bool addRaceFeat=false, Func< Element, string, string > funcText=null, Action< UINote, Element > onAddNote=null)
void AddNoteAll (UINote n)
Additional Inherited Members
Public Types inherited from ElementContainer
enum NoteMode {
Default , CharaMake , CharaMakeAttributes , Domain ,
Trait
}
Static Public Member Functions inherited from ElementContainer
static int GetSortVal (Element a)
Static Public Member Functions inherited from EClass
static int rnd (int a)
static int curve (int a, int start, int step, int rate=75)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Public Attributes inherited from ElementContainer
Dictionary< int, Element > dict = new Dictionary<int, Element>()
ElementContainer parent
List< int > list
Static Public Attributes inherited from ElementContainer
const int sizeElement = 5
Static Public Attributes inherited from EClass
static Core core
Properties inherited from ElementContainer
virtual Card Card [get]
virtual Chara Chara [get]
virtual bool IsMeleeWeapon [get]
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Detailed Description
Definition at line 1 of file ElementContainerZone.cs.
Member Function Documentation
OnLearn()
override void ElementContainerZone.OnLearn (int ele) inline virtual
Reimplemented from ElementContainer.
Definition at line 3 of file ElementContainerZone.cs.
    {
        SE.DingSkill2();
        Msg.Say("learnSkillBranch", EClass._zone.Name, EClass.sources.elements.map[ele].GetName());
    }
References EClass._zone, SourceManager.elements, Spatial.Name, Msg.Say(), and EClass.sources.
OnLevelUp()
override void ElementContainerZone.OnLevelUp (Element e, int lastValue) inline virtual
Reimplemented from ElementContainer.
Definition at line 9 of file ElementContainerZone.cs.
    {
        if (EClass._zone.IsPCFaction)
        {
            if (!VirtualDate.IsActive)
            {
                SE.DingSkill2();
                Msg.Say("dingSkillBranch", EClass._zone.Name, e.Name);
                EClass.pc.pos.TalkWitnesses(EClass.pc, "ding_other", 4, WitnessType.ally);
                WidgetPopText.Say("popDing".lang(EClass._zone.Name, e.Name, lastValue.ToString() ?? "", e.vBase.ToString() ?? ""), FontColor.Good);
            }
            EClass.Branch.Log("bDing", EClass._zone.Name, e.Name, lastValue.ToString() ?? "", e.vBase.ToString() ?? "");
        }
    }
References EClass._zone, EClass.Branch, VirtualDate.IsActive, Zone.IsPCFaction, FactionBranch.Log(), Element.Name, Spatial.Name, EClass.pc, Card.pos, Msg.Say(), WidgetPopText.Say(), Point.TalkWitnesses(), and Element.vBase.
The documentation for this class was generated from the following file:
Elin/ElementContainerZone.cs