Elin Decompiled Documentation: SourceCategory Class Reference
SourceCategory Class Reference
Classes
class Row
Public Member Functions
override Row CreateRow ()
override Row CreateRowByMapping (IReadOnlyDictionary< string, int > mapping)
override void SetRow (Row r)
override IReadOnlyDictionary< string, int > GetRowMapping ()
override IReadOnlyDictionary< string, string > GetTypeMapping ()
override void OnInit ()
Public Member Functions inherited from SourceDataString< SourceCategory.Row >
override T GetRow (string id)
Static Public Attributes
static readonly IReadOnlyDictionary< string, int > RowMapping
static readonly IReadOnlyDictionary< string, string > TypeMapping
Detailed Description
Definition at line 4 of file SourceCategory.cs.
Member Function Documentation
CreateRow()
override Row SourceCategory.CreateRow () inline
Definition at line 193 of file SourceCategory.cs.
    {
        return new Row
        {
            id = SourceData.GetString(0),
            uid = SourceData.GetInt(1),
            name_JP = SourceData.GetString(2),
            name = SourceData.GetString(3),
            _parent = SourceData.GetString(4),
            recipeCat = SourceData.GetString(5),
            slot = Core.GetElement(SourceData.GetStr(6)),
            skill = Core.GetElement(SourceData.GetStr(7)),
            maxStack = SourceData.GetInt(8),
            tileDummy = SourceData.GetInt(9),
            installOne = SourceData.GetBool(10),
            ignoreBless = SourceData.GetInt(11),
            tag = SourceData.GetStringArray(12),
            idThing = SourceData.GetString(13),
            recycle = SourceData.GetStringArray(14),
            costSP = SourceData.GetInt(15),
            gift = SourceData.GetInt(16),
            deliver = SourceData.GetInt(17),
            offer = SourceData.GetInt(18),
            ticket = SourceData.GetInt(19),
            sortVal = SourceData.GetInt(20),
            flag = SourceData.GetInt(21)
        };
    }
References SourceData< T, T2 >.GetBool(), Core.GetElement(), SourceData< T, T2 >.GetInt(), SourceData< T, T2 >.GetStr(), SourceData< T, T2 >.GetString(), SourceData< T, T2 >.GetStringArray(), and gift.
CreateRowByMapping()
override Row SourceCategory.CreateRowByMapping (IReadOnlyDictionary< string, int > mapping) inline
Definition at line 222 of file SourceCategory.cs.
    {
        return new Row
        {
            id = SourceData.GetString(mapping["id"]),
            uid = SourceData.GetInt(mapping["uid"]),
            name_JP = SourceData.GetString(mapping["name_JP"]),
            name = SourceData.GetString(mapping["name"]),
            _parent = SourceData.GetString(mapping["_parent"]),
            recipeCat = SourceData.GetString(mapping["recipeCat"]),
            slot = Core.GetElement(SourceData.GetStr(mapping["slot"])),
            skill = Core.GetElement(SourceData.GetStr(mapping["skill"])),
            maxStack = SourceData.GetInt(mapping["maxStack"]),
            tileDummy = SourceData.GetInt(mapping["tileDummy"]),
            installOne = SourceData.GetBool(mapping["installOne"]),
            ignoreBless = SourceData.GetInt(mapping["ignoreBless"]),
            tag = SourceData.GetStringArray(mapping["tag"]),
            idThing = SourceData.GetString(mapping["idThing"]),
            recycle = SourceData.GetStringArray(mapping["recycle"]),
            costSP = SourceData.GetInt(mapping["costSP"]),
            gift = SourceData.GetInt(mapping["gift"]),
            deliver = SourceData.GetInt(mapping["deliver"]),
            offer = SourceData.GetInt(mapping["offer"]),
            ticket = SourceData.GetInt(mapping["ticket"]),
            sortVal = SourceData.GetInt(mapping["sortVal"]),
            flag = SourceData.GetInt(mapping["flag"])
        };
    }
References SourceData< T, T2 >.GetBool(), Core.GetElement(), SourceData< T, T2 >.GetInt(), SourceData< T, T2 >.GetStr(), SourceData< T, T2 >.GetString(), SourceData< T, T2 >.GetStringArray(), and gift.
GetRowMapping()
override IReadOnlyDictionary< string, int > SourceCategory.GetRowMapping () inline
Definition at line 256 of file SourceCategory.cs.
    {
        return RowMapping;
    }
References RowMapping.
GetTypeMapping()
override IReadOnlyDictionary< string, string > SourceCategory.GetTypeMapping () inline
Definition at line 261 of file SourceCategory.cs.
    {
        return TypeMapping;
    }
References TypeMapping.
OnInit()
override void SourceCategory.OnInit () inline
Definition at line 266 of file SourceCategory.cs.
    {
        foreach (Row row in rows)
        {
            row.children = new List<Row>();
        }
        foreach (Row row2 in rows)
        {
            if (!row2._parent.IsEmpty())
            {
                (row2.parent = map[row2._parent]).children.Add(row2);
            }
        }
    }
References SourceCategory.Row._parent.
SetRow()
override void SourceCategory.SetRow (Row r) inline
Definition at line 251 of file SourceCategory.cs.
    {
        map[r.id] = r;
    }
References SourceCategory.Row.id.
Member Data Documentation
RowMapping
readonly IReadOnlyDictionary<string, int> SourceCategory.RowMapping static
Initial value:
= new Dictionary<string, int>
    {
        ["id"] = 0,
        ["uid"] = 1,
        ["name_JP"] = 2,
        ["name"] = 3,
        ["_parent"] = 4,
        ["recipeCat"] = 5,
        ["slot"] = 6,
        ["skill"] = 7,
        ["maxStack"] = 8,
        ["tileDummy"] = 9,
        ["installOne"] = 10,
        ["ignoreBless"] = 11,
        ["tag"] = 12,
        ["idThing"] = 13,
        ["recycle"] = 14,
        ["costSP"] = 15,
        ["gift"] = 16,
        ["deliver"] = 17,
        ["offer"] = 18,
        ["ticket"] = 19,
        ["sortVal"] = 20,
        ["flag"] = 21
    }
Definition at line 141 of file SourceCategory.cs.
Referenced by GetRowMapping().
TypeMapping
readonly IReadOnlyDictionary<string, string> SourceCategory.TypeMapping static
Initial value:
= new Dictionary<string, string>
    {
        ["id"] = "string",
        ["uid"] = "int",
        ["name_JP"] = "string",
        ["name"] = "string",
        ["_parent"] = "string",
        ["recipeCat"] = "string",
        ["slot"] = "element_id",
        ["skill"] = "element_id",
        ["maxStack"] = "int",
        ["tileDummy"] = "int",
        ["installOne"] = "bool",
        ["ignoreBless"] = "int",
        ["tag"] = "string[]",
        ["idThing"] = "string",
        ["recycle"] = "string[]",
        ["costSP"] = "int",
        ["gift"] = "int",
        ["deliver"] = "int",
        ["offer"] = "int",
        ["ticket"] = "int",
        ["sortVal"] = "int",
        ["flag"] = "int"
    }
Definition at line 167 of file SourceCategory.cs.
Referenced by GetTypeMapping().
The documentation for this class was generated from the following file:
Elin/SourceCategory.cs