Elin Decompiled Documentation: ListPeopleExpedition Class Reference
ListPeopleExpedition Class Reference
Public Member Functions
override void OnClick (Chara c, ItemGeneral i)
override void OnList ()
override void SetSubText (Chara a, ItemGeneral b)
Public Member Functions inherited from BaseListPeople
virtual bool IsDisabled (Chara c)
override void List ()
override void OnInstantiate (Chara a, ItemGeneral b)
void AddSubButtonWork (ItemGeneral b, Chara a)
void WriteHobbies (UITooltip t, Chara a, BaseArea roomWork)
virtual void SetSubText (Chara a, ItemGeneral b)
override void OnClick (Chara c, ItemGeneral i)
override void OnList ()
override void OnRefreshMenu ()
Public Member Functions inherited from ListOwner< Chara, ItemGeneral >
virtual void OnClick (T1 a, T2 b)
virtual void OnInstantiate (T1 a, T2 b)
virtual void OnList ()
virtual void List ()
virtual void OnCreate ()
virtual void OnSwitchContent ()
virtual void OnRefreshMenu ()
void RefreshTab ()
void MoveToOther (object c)
Public Attributes
Dictionary< int, Expedition > expeditions = new Dictionary<int, Expedition>()
ExpeditionType type
Public Attributes inherited from BaseListPeople
Chara owner
FactionMemberType memberType
Public Attributes inherited from ListOwner< Chara, ItemGeneral >
Layer layer
Window window
UIMultiList multi
ListOwner other
UIList list
WindowMenu menu
Window.Setting.Tab tab
string textTab
string textHeader
bool main
int index
Properties
override bool ShowGoto [get]
override bool ShowHome [get]
Properties inherited from ListPeople
override string TextTab [get]
override bool ShowCharaSheet [get]
override bool ShowGoto [get]
override bool ShowHome [get]
override bool ShowShowMode [get]
Properties inherited from BaseListPeople
new LayerPeople layer [get]
override string IdHeaderRow [get]
virtual bool ShowCharaSheet [get]
virtual bool ShowShowMode [get]
virtual LayerPeople.ShowMode ShowMode [get]
virtual bool ShowGoto [get]
virtual bool ShowHome [get]
Properties inherited from ListOwner< Chara, ItemGeneral >
ListOwner Main [get]
virtual string IdTitle [get]
virtual string IdHeaderRow [get]
virtual string TextTab [get]
virtual string TextHeader [get]
Properties inherited from EClass
static Game game [get]
static bool AdvMode [get]
static Player player [get]
static Chara pc [get]
static UI ui [get]
static Map _map [get]
static Zone _zone [get]
static FactionBranch Branch [get]
static FactionBranch BranchOrHomeBranch [get]
static Faction Home [get]
static Faction Wilds [get]
static Scene scene [get]
static BaseGameScreen screen [get]
static GameSetting setting [get]
static GameData gamedata [get]
static ColorProfile Colors [get]
static World world [get]
static SourceManager sources [get]
static SourceManager editorSources [get]
static SoundManager Sound [get]
static CoreDebug debug [get]
Additional Inherited Members
Static Public Member Functions inherited from EClass
static int rnd (int a)
static int curve (int a, int start, int step, int rate=75)
static int rndHalf (int a)
static float rndf (float a)
static int rndSqrt (int a)
static void Wait (float a, Card c)
static void Wait (float a, Point p)
static int Bigger (int a, int b)
static int Smaller (int a, int b)
Static Public Attributes inherited from EClass
static Core core
Detailed Description
Definition at line 3 of file ListPeopleExpedition.cs.
Member Function Documentation
OnClick()
override void ListPeopleExpedition.OnClick (Chara c, ItemGeneral i) inline
Definition at line 13 of file ListPeopleExpedition.cs.
    {
        Expedition ex = expeditions[c.uid];
        if (!c.IsAliveInCurrentZone || !ex.costs.CanPay())
        {
            SE.Beep();
            return;
        }
        UIContextMenu uIContextMenu = EClass.ui.CreateContextMenuInteraction().SetHighlightTarget(i);
        uIContextMenu.AddButton("sendExpedition", delegate
        {
            EClass.Branch.expeditions.Add(ex);
            SE.MoveZone();
            list.List();
        });
        uIContextMenu.Show();
    }
References ExpeditionManager.Add(), UIContextMenu.AddButton(), EClass.Branch, Expedition.costs, FactionBranch.expeditions, expeditions, Chara.IsAliveInCurrentZone, ListOwner< Chara, ItemGeneral >.list, UIList.List(), UIContextMenu.Show(), EClass.ui, and Card.uid.
OnList()
override void ListPeopleExpedition.OnList () inline virtual
Reimplemented from BaseListPeople.
Definition at line 31 of file ListPeopleExpedition.cs.
    {
        foreach (Chara member in EClass.Branch.members)
        {
            if (!member.IsPCParty)
            {
                list.Add(member);
                expeditions[member.uid] = Expedition.Create(member, type);
            }
        }
    }
References UIList.Add(), EClass.Branch, Expedition.Create(), expeditions, Chara.IsPCParty, ListOwner< Chara, ItemGeneral >.list, FactionBranch.members, type, and Card.uid.
SetSubText()
override void ListPeopleExpedition.SetSubText (Chara a, ItemGeneral b) inline virtual
Reimplemented from BaseListPeople.
Definition at line 43 of file ListPeopleExpedition.cs.
    {
        Expedition expedition = expeditions[a.uid];
        string lang = "";
        if (a.IsAliveInCurrentZone)
        {
            lang = expedition.costs.GetText() + "subExpedition".lang((expedition.MinHour / 24).ToString() ?? "", (expedition.MaxHour / 24).ToString() ?? "");
        }
        else if (a.isDead)
        {
            lang = "isDead".lang();
        }
        else if (a.currentZone?.id == "somewhere")
        {
            lang = "isExploring".lang();
        }
        b.SetSubText(lang, 280);
    }
References Expedition.costs, Chara.currentZone, expeditions, Spatial.id, Chara.IsAliveInCurrentZone, Chara.isDead, Expedition.MaxHour, Expedition.MinHour, ItemGeneral.SetSubText(), and Card.uid.
Member Data Documentation
expeditions
Dictionary<int, Expedition> ListPeopleExpedition.expeditions = new Dictionary<int, Expedition>()
Definition at line 5 of file ListPeopleExpedition.cs.
Referenced by OnClick(), OnList(), and SetSubText().
type
ExpeditionType ListPeopleExpedition.type
Definition at line 7 of file ListPeopleExpedition.cs.
Referenced by OnList().
Property Documentation
ShowGoto
override bool ListPeopleExpedition.ShowGoto get
Definition at line 9 of file ListPeopleExpedition.cs.
ShowHome
override bool ListPeopleExpedition.ShowHome get
Definition at line 11 of file ListPeopleExpedition.cs.
The documentation for this class was generated from the following file:
Elin/ListPeopleExpedition.cs