Elin Decompiled Documentation: Elin/CustomDramaExpansion.cs File Reference
CustomDramaExpansion.cs File Reference
Classes
class CustomDramaExpansion
Functions
publicstaticboolParsection (stringaction, ramaManagerdm, ictionary< string, string >line)
static bool DefaultDramaInvokeExtActionParser (DramaManager dm, Dictionary< string, string > line)
static bool DefaultDramaEvalActionParser (DramaManager dm, Dictionary< string, string > line)
static bool eval (DramaManager dm, Dictionary< string, string > line, params string[] parameters)
static bool and (DramaManager dm, Dictionary< string, string > line, params string[] parameters)
static bool or (DramaManager dm, Dictionary< string, string > line, params string[] parameters)
static bool not (DramaManager dm, Dictionary< string, string > line, params string[] parameters)
static bool console_cmd (DramaManager dm, Dictionary< string, string > line, params string[] parameters)
static bool add_item (DramaManager dm, Dictionary< string, string > line, string itemId, string materialAlias="", int lv=-1, int count=1)
static bool apply_condition (DramaManager dm, Dictionary< string, string > line, string conditionAlias, int power=100)
static bool equip_item (DramaManager dm, Dictionary< string, string > line, string itemId)
static bool destroy_item (DramaManager dm, Dictionary< string, string > line, string itemId, int count=-1)
static bool remove_condition (DramaManager dm, Dictionary< string, string > line, string conditionAlias)
static bool join_faith (DramaManager dm, Dictionary< string, string > line, string religionId="")
static bool join_party (DramaManager dm, Dictionary< string, string > line)
static bool if_affinity (DramaManager dm, Dictionary< string, string > line, DramaValueExpression expr)
static bool if_condition (DramaManager dm, Dictionary< string, string > line, string conditionAlias, DramaValueExpression expr=null)
static bool if_currency (DramaManager dm, Dictionary< string, string > line, string currencyId, DramaValueExpression expr)
static bool if_element (DramaManager dm, Dictionary< string, string > line, string elementAlias, DramaValueExpression expr)
static bool if_faith (DramaManager dm, Dictionary< string, string > line, string religionId, DramaValueExpression expr=null)
static bool if_fame (DramaManager dm, Dictionary< string, string > line, DramaValueExpression expr)
static bool if_flag (DramaManager dm, Dictionary< string, string > line, string flagKey, DramaValueExpression expr=null)
static bool if_has_item (DramaManager dm, Dictionary< string, string > line, string itemId, DramaValueExpression expr=null)
static bool if_hostility (DramaManager dm, Dictionary< string, string > line, string expression)
static bool if_in_party (DramaManager dm, Dictionary< string, string > line, bool isInParty=true)
if (!match.Success)
static bool if_keyitem (DramaManager dm, Dictionary< string, string > line, string keyitemId, DramaValueExpression expr=null)
static bool if_lv (DramaManager dm, Dictionary< string, string > line, DramaValueExpression expr)
static bool if_race (DramaManager dm, Dictionary< string, string > line, string raceId)
static bool if_tag (DramaManager dm, Dictionary< string, string > line, string tag)
static bool if_zone (DramaManager dm, Dictionary< string, string > line, string zoneId, int zoneLv=99999)
static bool if_zone_2 (DramaManager dm, Dictionary< string, string > line, string zoneFullName)
static bool mod_affinity (DramaManager dm, Dictionary< string, string > line, DramaValueExpression expr)
static bool mod_currency (DramaManager dm, Dictionary< string, string > line, string currencyId, DramaValueExpression expr)
static bool mod_element (DramaManager dm, Dictionary< string, string > line, string elementAlias, int value=1, int potential=100)
static bool mod_element_exp (DramaManager dm, Dictionary< string, string > line, string elementAlias, DramaValueExpression expr)
static bool mod_fame (DramaManager dm, Dictionary< string, string > line, DramaValueExpression expr)
static bool mod_flag (DramaManager dm, Dictionary< string, string > line, string flagKey, DramaValueExpression expr=null)
static bool mod_keyitem (DramaManager dm, Dictionary< string, string > line, string keyitemId, DramaValueExpression expr=null)
static bool move_next_to (DramaManager dm, Dictionary< string, string > line, string charaId)
static bool move_tile (DramaManager dm, Dictionary< string, string > line, int xOffset, int yOffset)
static bool move_to (DramaManager dm, Dictionary< string, string > line, int x, int y)
static bool move_zone (DramaManager dm, Dictionary< string, string > line, string zoneId, int zoneLv=99999)
static bool move_zone_2 (DramaManager dm, Dictionary< string, string > line, string zoneFullName)
static bool play_anime (DramaManager dm, Dictionary< string, string > line, AnimeID animeId)
static bool play_effect (DramaManager dm, Dictionary< string, string > line, string effectId)
static bool play_effect_at (DramaManager dm, Dictionary< string, string > line, string effectId, int x, int y)
static bool play_emote (DramaManager dm, Dictionary< string, string > line, Emo emote, float duration=1f)
static bool play_screen_effect (DramaManager dm, Dictionary< string, string > line, string effectId)
static bool pop_text (DramaManager dm, Dictionary< string, string > line, string langText)
static bool set_portrait (DramaManager dm, Dictionary< string, string > line, string portraitId=null)
static bool set_portrait_override (DramaManager dm, Dictionary< string, string > line, string portraitId=null)
static bool set_sprite (DramaManager dm, Dictionary< string, string > line, string spriteId=null)
static bool show_book (DramaManager dm, Dictionary< string, string > line, string bookEntry)
Variables
$
RegexOptions. Compiled
Function Documentation
add_item()
static bool add_item (DramaManager dm, Dictionary< string, string > line, string itemId, string materialAlias = "", int lv = -1, int count = 1) static
Definition at line 258 of file CustomDramaExpansion.cs.
        {
            dm = dm,
            line = line
        };
        if (text.StartsWith("<<<"))
and()
static bool and (DramaManager dm, Dictionary< string, string > line, params string[] parameters) static
Definition at line 218 of file CustomDramaExpansion.cs.
                {
                    object obj = DeferredCompileAndRun();
                    if (obj is string result)
                    {
                        return result;
                    }
                    return (obj is bool && !(bool)obj) ? "" : jump;
                }
apply_condition()
static bool apply_condition (DramaManager dm, Dictionary< string, string > line, string conditionAlias, int power = 100) static
Definition at line 268 of file CustomDramaExpansion.cs.
            {
                throw new FileNotFoundException(text2);
            }
console_cmd()
static bool console_cmd (DramaManager dm, Dictionary< string, string > line, params string[] parameters) static
Definition at line 251 of file CustomDramaExpansion.cs.
    {
        string text = string.Join(',', parameters);
        if (text.IsEmpty())
DefaultDramaEvalActionParser()
static bool DefaultDramaEvalActionParser (DramaManager dm, Dictionary< string, string > line) static package
Definition at line 115 of file CustomDramaExpansion.cs.
                            :
                        num--;
                        break;
                    case ',':
                        if (num == 0)
{
                            string s2 = args[num2..i].Trim();
                            s2 = Unquote(s2);
                            list.Add(s2);
                            num2 = i + 1;
                        }
                        break;
                    }
                }
            }
            if (num2 < args.Length)
            {
                string text = args[num2..].Trim();
                if (text.Length > 0)
                {
                    list.Add(Unquote(text));
                }
            }
            return list.ToArray();
        }
        static string Unquote(string s)
        {
            if (s.Length >= 2 && ((s[0] == '"' && s[^1] == '"') || (s[0] == '\'' && s[^1] == '\'')))
            {
                return s[1..^1];
            }
            return s;
        }
    }
    [ElinDramaActionParser("i*")]
    [ElinDramaActionParser("invoke*")]
    internal static bool DefaultDramaInvokeExtActionParser(DramaManager dm, Dictionary<string, string> line)
    {
        string text = line["param"].Trim().RemoveNewline();
        if (text.StartsWith("//"))
        {
            return true;
        }
        var (invoke, parameters) = BuildInvokeExpression(text);
        if (invoke.Method == null)
        {
            ModUtil.LogModError("invalid drama invoke* expression '" + text + "'", new FileInfo(dm.path));
            return true;
        }
        string jump = line["jump"];
        if (!jump.IsEmpty())
        {
            dm.AddEvent(new DramaEventMethod(null)
            {
                jumpFunc = () => (!invoke.SafeInvoke(dm, line, parameters)) ? "" : jump
            });
            return true;
        }
        dm.AddEvent(new DramaEventMethod(delegate
        {
            invoke.SafeInvoke(dm, line, parameters);
        }));
        return true;
    }
    [ElinDramaActionParser("eval")]
References CustomDramaExpansion.Unquote().
DefaultDramaInvokeExtActionParser()
static bool DefaultDramaInvokeExtActionParser (DramaManager dm, Dictionary< string, string > line) static package
Definition at line 85 of file CustomDramaExpansion.cs.
        {
            if (args.IsEmpty())
            {
                return Array.Empty<string>();
            }
            List<string> list = new List<string>();
            int num = 0;
            int num2 = 0;
            char c = '\0';
            for (int i = 0; i < args.Length; i++)
            {
                char c2 = args[i];
                if (c != 0)
                {
                    if (c2 == c)
                    {
                        c = '\0';
                    }
                }
                else
                {
                    switch (c2)
                    {
                    case '"':
                    case '\'':
                        c = c2;
                        break;
                    case '(':
destroy_item()
static bool destroy_item (DramaManager dm, Dictionary< string, string > line, string itemId, int count = -1) static
Definition at line 282 of file CustomDramaExpansion.cs.
    {
        return parameters.All(delegate(string expr)
        {
            var (dramaInvokeDetail, parameters2) = BuildInvokeExpression(expr);
            return dramaInvokeDetail.SafeInvoke(dm, line, parameters2);
        });
    }
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    [ElinDramaActionInvoke("nodiscard")]
    public static bool or(DramaManager dm, Dictionary<string, string> line, params string[] parameters)
    {
        return parameters.Any(delegate(string expr)
        {
            var (dramaInvokeDetail, parameters2) = BuildInvokeExpression(expr);
            return dramaInvokeDetail.SafeInvoke(dm, line, parameters2);
        });
    }
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    [ElinDramaActionInvoke("nodiscard")]
    public static bool not(DramaManager dm, Dictionary<string, string> line, params string[] parameters)
    {
        return parameters.All(delegate(string expr)
        {
            var (dramaInvokeDetail, parameters2) = BuildInvokeExpression(expr);
equip_item()
static bool equip_item (DramaManager dm, Dictionary< string, string > line, string itemId) static
Definition at line 275 of file CustomDramaExpansion.cs.
        {
            return (bool)obj;
        }
eval()
static bool eval (DramaManager dm, Dictionary< string, string > line, params string[] parameters) static
Definition at line 185 of file CustomDramaExpansion.cs.
        {
            return true;
        }
        EScriptSubmission submission = EScriptSubmission.Create(dm.setup.book);
        EDramaScriptState state = new EDramaScriptState
        {
            dm = dm,
            line = line
        };
        string jump = line["jump"];
        bool flag = !jump.IsEmpty();
        bool flag2 = !line["id"].IsEmpty();
        if (!flag && flag2)
        {
            Dictionary<string, string> item = new Dictionary<string, string>(line)
            {
                ["action"] = "",
                ["param"] = ""
            };
            dm.ParseLine(item);
            dm.lastTalk.activeCondition = delegate
            {
                object obj2 = DeferredCompileAndRun();
                return obj2 is bool && (bool)obj2;
            };
            return true;
        }
        if (flag)
        {
if()
if_in_party.if (!match::Success)
Definition at line 449 of file CustomDramaExpansion.cs.
    {
        Chara chara = dm.GetChara(line["actor"]);
        if (chara.HasElement(elementAlias))
References DramaManager.GetChara(), and Card.HasElement().
Referenced by HotItemNoItem._TrySetAct(), ActPlan._Update(), HoardActor.Activate(), Zone.Activate(), LayerEditPortrait.Activate(), MeshPass.AddShadow(), CoreConfig.ApplyGrading(), CoreConfig.ApplyScale(), Scene.ApplyZoneConfig(), Chara.DestroyPath(), LayerPixelPaint.DialogLoad(), WidgetManager.DialogLoad(), WidgetManager.DialogSave(), BaseTileMap.Draw(), BaseTileMap.DrawRoof(), BaseTileMap.DrawTile(), TileMapElona.DrawTile(), PartialMap.ExportDialog(), Zone.ExportDialog(), QuestSupplySpecific.GetBonus(), Check.GetDC(), HomeResourceNature.GetDestValue(), TraitTicketFurniture.GetPrice(), Los.GetRushPoint(), BaseTileMap.GetThingPosition(), EloMap.GetTileInfo(), Zone.GrowPlants(), AM_Copy.ImportDialog(), Zone.ImportDialog(), Window.Init(), InvOwner.ListInteractions(), TaskDump.ListThingsToPut(), TraitSeed.MakeSeed(), SurvivalManager.MeteorThing(), CharacterSpacing.ModifyMesh(), Widget.OnChangePosition(), ContentConfigOther.OnClickDownloadWallpaper(), WidgetSceneCustomizer.OnClickLoad(), WidgetSceneCustomizer.OnClickSave(), TraitBookSkill.OnCreate(), TaskDrawWater.OnCreateProgress(), LayerConfig.OnInit(), LayerEditHouse.OnInit(), ListPeopleCallReserve.OnInstantiate(), GenRoom.OnPopulate(), AM_Populate.OnProcessTiles(), AM_Terrain.OnProcessTiles(), TraitDeed.OnRead(), FactionBranch.OnSimulateHour(), ContentQuest.OnSwitchContent(), Scene.OnUpdate(), Chara.PerformWork(), AttackProcess.Prepare(), ActEffect.Proc(), ActEffect.ProcAt(), FoodEffect.ProcNutrition(), UIDistribution.Refresh(), LayerCraftFloat.RefreshDisassemble(), LayerHome.RefreshFeat(), ButtonHotItem.RefreshItem(), ContentPolicy.RefreshPolicyList(), BaseGameScreen.RefreshPosition(), GameScreenElona.RefreshPosition(), WindowChara.RefreshSkill(), AI_HaulResource.Run(), AI_Idle.Run(), AI_PlayMusic.Run(), WidgetSearch.Search(), UIDynamicList.Select< T >(), GridItemRecipe.SetButton(), ButtonGrid.SetCard(), UIInventory.Sort(), Fov.TraceLine(), Chara.TryPush(), HotItemAct.TrySetAct(), HotItemHeld.TrySetAct(), TraitWell.TrySetAct(), TraitCatalyst.TrySetHeldAct(), LayerInventory.TryShowGuide(), Chara.TryTakeSharedItems(), FactionBranch.UpdateReqruits(), WidgetDebug.UpdateText(), TraitBed.ValidateOwners(), ActEffect.Wish(), and Thing.WriteNote().
if_affinity()
static bool if_affinity (DramaManager dm, Dictionary< string, string > line, DramaValueExpression expr) static
Definition at line 351 of file CustomDramaExpansion.cs.
        {
            foreach (Thing item in list)
            {
References item.
if_condition()
static bool if_condition (DramaManager dm, Dictionary< string, string > line, string conditionAlias, DramaValueExpression expr = null) static
Definition at line 358 of file CustomDramaExpansion.cs.
        {
            count = Math.Max(count, 0);
            foreach (Thing item2 in list)
            {
                if (count == 0)
                {
                    break;
                }
                if (item2.Num >= count)
                {
                    item2.ModNum(-count);
                    continue;
                }
if_currency()
static bool if_currency (DramaManager dm, Dictionary< string, string > line, string currencyId, DramaValueExpression expr) static
Definition at line 375 of file CustomDramaExpansion.cs.
if_element()
static bool if_element (DramaManager dm, Dictionary< string, string > line, string elementAlias, DramaValueExpression expr) static
Definition at line 382 of file CustomDramaExpansion.cs.
    {
        foreach (Condition item in dm.GetChara(line["actor"]).conditions.ToList())
        {
            if (item.source.alias == conditionAlias)
            {
                item.Kill();
            }
        }
        return true;
References Chara.conditions, DramaManager.GetChara(), and item.
if_faith()
static bool if_faith (DramaManager dm, Dictionary< string, string > line, string religionId, DramaValueExpression expr = null) static
Definition at line 393 of file CustomDramaExpansion.cs.
    {
        Chara chara = dm.GetChara(line["actor"]);
        if (religionId.IsEmpty())
        {
            chara.faith?.LeaveFaith(chara, EClass.game.religions.Eyth, Religion.ConvertType.Default);
        }
        else
        {
            EClass.game.religions.Find(religionId)?.JoinFaith(chara);
        }
        return true;
References ReligionManager.Eyth, Chara.faith, ReligionManager.Find(), EClass.game, DramaManager.GetChara(), Religion.JoinFaith(), Religion.LeaveFaith(), and Game.religions.
if_fame()
static bool if_fame (DramaManager dm, Dictionary< string, string > line, DramaValueExpression expr) static
Definition at line 408 of file CustomDramaExpansion.cs.
    {
        Chara chara = dm.GetChara(line["actor"]);
References DramaManager.GetChara(), Chara.MakeAlly(), and EClass.Sound.
if_flag()
static bool if_flag (DramaManager dm, Dictionary< string, string > line, string flagKey, DramaValueExpression expr = null) static
Definition at line 414 of file CustomDramaExpansion.cs.
    {
        Chara chara = dm.GetChara(line["actor"]);
        return expr.Compare(chara._affinity);
    }
if_has_item()
static bool if_has_item (DramaManager dm, Dictionary< string, string > line, string itemId, DramaValueExpression expr = null) static
Definition at line 425 of file CustomDramaExpansion.cs.
    {
        if (expr == null)
        {
            expr = ">=1";
        }
        foreach (Condition condition in dm.GetChara(line["actor"]).conditions)
        {
            if (condition.source.alias == conditionAlias)
References Chara.conditions, DramaManager.GetChara(), BaseStats.source, and BaseCondition.value.
if_hostility()
static bool if_hostility (DramaManager dm, Dictionary< string, string > line, string expression) static
Definition at line 436 of file CustomDramaExpansion.cs.
    {
        Chara chara = dm.GetChara(line["actor"]);
        return expr.Compare(chara.GetCurrency(currencyId));
if_in_party()
static bool if_in_party (DramaManager dm, Dictionary< string, string > line, bool isInParty = true) static
Definition at line 448 of file CustomDramaExpansion.cs.
    {
        Chara chara = dm.GetChara(line["actor"]);
if_keyitem()
static bool if_keyitem (DramaManager dm, Dictionary< string, string > line, string keyitemId, DramaValueExpression expr = null) static
Definition at line 454 of file CustomDramaExpansion.cs.
    {
        if (expr == null)
        {
            expr = ">=0";
        }
if_lv()
static bool if_lv (DramaManager dm, Dictionary< string, string > line, DramaValueExpression expr) static
Definition at line 468 of file CustomDramaExpansion.cs.
        {
            return expr.Compare(faith.giftRank);
        }
        return false;
    }
References faith.
if_race()
static bool if_race (DramaManager dm, Dictionary< string, string > line, string raceId) static
Definition at line 475 of file CustomDramaExpansion.cs.
    {
        return expr.Compare(EClass.player.fame);
    }
References Player.fame, and EClass.player.
if_tag()
static bool if_tag (DramaManager dm, Dictionary< string, string > line, string tag) static
Definition at line 481 of file CustomDramaExpansion.cs.
    {
        if (expr == null)
        {
if_zone()
static bool if_zone (DramaManager dm, Dictionary< string, string > line, string zoneId, int zoneLv = 99999) static
Definition at line 487 of file CustomDramaExpansion.cs.
    {
        if (expr == null)
        {
            expr = ">=1";
        }
        Chara chara = dm.GetChara(line["actor"]);
        return expr.Compare(chara.things.List((Thing t) => t.id == itemId).Count);
    }
    [ElinDramaActionInvoke("nodiscard")]
    public static bool if_hostility(DramaManager dm, Dictionary<string, string> line, string expression)
if_zone_2()
static bool if_zone_2 (DramaManager dm, Dictionary< string, string > line, string zoneFullName) static
Definition at line 506 of file CustomDramaExpansion.cs.
        {
            throw new ArgumentException("invalid expression " + expression);
        }
        string value = match.Groups["op"].Value;
join_faith()
static bool join_faith (DramaManager dm, Dictionary< string, string > line, string religionId = "") static
Definition at line 327 of file CustomDramaExpansion.cs.
    {
        dm.GetChara(line["actor"]).AddCondition(conditionAlias, power, force: true);
        return true;
    }
join_party()
static bool join_party (DramaManager dm, Dictionary< string, string > line) static
Definition at line 342 of file CustomDramaExpansion.cs.
    {
        dm.GetChara(line["actor"]).body.Equip(ThingGen.Create(itemId));
        return true;
    }
    [ElinDramaActionInvoke(null)]
References Chara.body, ThingGen.Create(), CharaBody.Equip(), and DramaManager.GetChara().
mod_affinity()
static bool mod_affinity (DramaManager dm, Dictionary< string, string > line, DramaValueExpression expr) static
Definition at line 514 of file CustomDramaExpansion.cs.
                                          {value}{result:D}").Compare(chara._cints[4]);
    }
    [ElinDramaActionInvoke("nodiscard")]
mod_currency()
static bool mod_currency (DramaManager dm, Dictionary< string, string > line, string currencyId, DramaValueExpression expr) static
Definition at line 522 of file CustomDramaExpansion.cs.
    {
        if (expr == null)
mod_element()
static bool mod_element (DramaManager dm, Dictionary< string, string > line, string elementAlias, int value = 1, int potential = 100) static
Definition at line 531 of file CustomDramaExpansion.cs.
        {
            return expr.Compare(value2);
        }
        return false;
    }
    [ElinDramaActionInvoke("nodiscard")]
    public static bool if_lv(DramaManager dm, Dictionary<string, string> line, DramaValueExpression expr)
    {
        Chara chara = dm.GetChara(line["actor"]);
        return expr.Compare(chara.LV);
    }
    [ElinDramaActionInvoke("nodiscard")]
    public static bool if_race(DramaManager dm, Dictionary<string, string> line, string raceId)
mod_element_exp()
static bool mod_element_exp (DramaManager dm, Dictionary< string, string > line, string elementAlias, DramaValueExpression expr) static
Definition at line 550 of file CustomDramaExpansion.cs.
    {
        return dm.GetChara(line["actor"]).source.tag.Contains(tag);
    }
    [ElinDramaActionInvoke("nodiscard")]
    public static bool if_zone(DramaManager dm, Dictionary<string, string> line, string zoneId, int zoneLv = 99999)
    {
mod_fame()
static bool mod_fame (DramaManager dm, Dictionary< string, string > line, DramaValueExpression expr) static
Definition at line 563 of file CustomDramaExpansion.cs.
        {
            return false;
        }
        if (currentZone.id == zoneId)
        {
mod_flag()
static bool mod_flag (DramaManager dm, Dictionary< string, string > line, string flagKey, DramaValueExpression expr = null) static
Definition at line 570 of file CustomDramaExpansion.cs.
    {
mod_keyitem()
static bool mod_keyitem (DramaManager dm, Dictionary< string, string > line, string keyitemId, DramaValueExpression expr = null) static
Definition at line 582 of file CustomDramaExpansion.cs.
    {
        Chara chara = dm.GetChara(line["actor"]);
        chara.ModAffinity(EClass.pc, expr.Diff(chara._affinity));
        return true;
    }
    [ElinDramaActionInvoke(null)]
    public static bool mod_currency(DramaManager dm, Dictionary<string, string> line, string currencyId, DramaValueExpression expr)
    {
        Chara chara = dm.GetChara(line["actor"]);
        int currency = chara.GetCurrency(currencyId);
        chara.ModCurrency(expr.Diff(currency), currencyId);
        return true;
    }
    [ElinDramaActionInvoke(null)]
    public static bool mod_element(DramaManager dm, Dictionary<string, string> line, string elementAlias, int value = 1, int potential = 100)
    {
        Chara chara = dm.GetChara(line["actor"]);
        Element orCreateElement = chara.elements.GetOrCreateElement(elementAlias);
        if (orCreateElement != null)
        {
move_next_to()
static bool move_next_to (DramaManager dm, Dictionary< string, string > line, string charaId) static
Definition at line 611 of file CustomDramaExpansion.cs.
                                                            : true);
            }
            else
            {
                chara.elements.SetBase(orCreateElement.id, value, potential);
            }
        }
        return true;
    }
    [ElinDramaActionInvoke(null)]
    public static bool mod_element_exp(DramaManager dm, Dictionary<string, string> line, string elementAlias, DramaValueExpression expr)
move_tile()
static bool move_tile (DramaManager dm, Dictionary< string, string > line, int xOffset, int yOffset) static
Definition at line 625 of file CustomDramaExpansion.cs.
        {
            return true;
        }
        chara.ModExp(orCreateElement.id, expr.Diff(orCreateElement.vExp));
        return true;
move_to()
static bool move_to (DramaManager dm, Dictionary< string, string > line, int x, int y) static
Definition at line 634 of file CustomDramaExpansion.cs.
    {
        EClass.player.ModFame(expr.Diff(EClass.player.fame));
        return true;
    }
References Player.fame, Player.ModFame(), and EClass.player.
move_zone()
static bool move_zone (DramaManager dm, Dictionary< string, string > line, string zoneId, int zoneLv = 99999) static
Definition at line 643 of file CustomDramaExpansion.cs.
    {
        if (expr == null)
        {
            expr = "=1";
        }
        Chara chara = dm.GetChara(line["actor"]);
        chara.SetInt(flagKey, expr.ModOrSet(chara.GetInt(flagKey)));
        return true;
    }
    [ElinDramaActionInvoke("nodiscard")]
    public static bool mod_keyitem(DramaManager dm, Dictionary<string, string> line, string keyitemId, DramaValueExpression expr = null)
    {
        if (!EClass.sources.keyItems.alias.TryGetValue(keyitemId, out var value))
        {
            return false;
        }
        if (expr == null)
References DramaManager.GetChara(), Card.GetInt(), and Card.SetInt().
move_zone_2()
static bool move_zone_2 (DramaManager dm, Dictionary< string, string > line, string zoneFullName) static
Definition at line 663 of file CustomDramaExpansion.cs.
        {
            SE.Play("keyitem");
            Msg.Say("get_keyItem", value.GetName());
        }
        else if (num > num2)
        {
            SE.Play("keyitem_lose");
            Msg.Say("lose_keyItem", value.GetName());
not()
static bool not (DramaManager dm, Dictionary< string, string > line, params string[] parameters) static
Definition at line 240 of file CustomDramaExpansion.cs.
                {
                    throw new FileNotFoundException(text);
                }
                expr = File.ReadAllText(path);
            }
            return submission.Compile<EDramaScriptState>(expr)?.Invoke(state);
        }
Referenced by DramaCustomSequence.Build(), Quest.Create(), Card.DamageHP(), Map.MineObj(), TaskBuild.OnProgressComplete(), and AI_Shopping.TryRestock().
or()
static bool or (DramaManager dm, Dictionary< string, string > line, params string[] parameters) static
Definition at line 229 of file CustomDramaExpansion.cs.
        {
            DeferredCompileAndRun();
        }));
        return true;
        object DeferredCompileAndRun()
        {
            if (expr.StartsWith("<<<"))
play_anime()
static bool play_anime (DramaManager dm, Dictionary< string, string > line, AnimeID animeId) static
Definition at line 679 of file CustomDramaExpansion.cs.
play_effect()
static bool play_effect (DramaManager dm, Dictionary< string, string > line, string effectId) static
Definition at line 686 of file CustomDramaExpansion.cs.
        {
            return false;
        }
play_effect_at()
static bool play_effect_at (DramaManager dm, Dictionary< string, string > line, string effectId, int x, int y) static
Definition at line 693 of file CustomDramaExpansion.cs.
play_emote()
static bool play_emote (DramaManager dm, Dictionary< string, string > line, Emo emote, float duration = 1f) static
Definition at line 700 of file CustomDramaExpansion.cs.
                                                : false);
        return true;
    }
play_screen_effect()
static bool play_screen_effect (DramaManager dm, Dictionary< string, string > line, string effectId) static
Definition at line 707 of file CustomDramaExpansion.cs.
    {
        Chara chara = dm.GetChara(line["actor"]);
        Point newPoint = new Point(x, y);
        chara.TryMove(newPoint, allowDestroyPath: false);
        return true;
References DramaManager.GetChara(), and Chara.TryMove().
pop_text()
static bool pop_text (DramaManager dm, Dictionary< string, string > line, string langText) static
Definition at line 714 of file CustomDramaExpansion.cs.
    {
        Chara chara = dm.GetChara(line["actor"]);
        if (zoneLv == 99999)
References DramaManager.GetChara().
publicstaticboolParsection()
_expressionRegex.publicstaticboolParsection (stringaction , ramaManagerdm , ictionary< string, string > line)
Definition at line 18 of file CustomDramaExpansion.cs.
References CustomDramaExpansion._actionParsers.
remove_condition()
static bool remove_condition (DramaManager dm, Dictionary< string, string > line, string conditionAlias) static
Definition at line 314 of file CustomDramaExpansion.cs.
    {
        string.Join(' ', parameters).EvaluateAsCommand();
        return true;
    }
    [ElinDramaActionInvoke(null)]
set_portrait()
static bool set_portrait (DramaManager dm, Dictionary< string, string > line, string portraitId = null) static
Definition at line 721 of file CustomDramaExpansion.cs.
                                                 {zoneId}@{zoneLv}");
        if (zone == null)
        {
            return false;
        }
        chara.MoveZone(zone, new ZoneTransition
        {
            state = ZoneTransition.EnterState.RandomVisit
        });
        return true;
    }
    [ElinDramaActionInvoke("nodiscard")]
    public static bool move_zone_2(DramaManager dm, Dictionary<string, string> line, string zoneFullName)
    {
        Chara chara = dm.GetChara(line["actor"]);
        Zone zone = ModUtil.FindZoneByFullName(zoneFullName);
        if (zone == null)
        {
            return false;
        }
        chara.MoveZone(zone, new ZoneTransition
        {
set_portrait_override()
static bool set_portrait_override (DramaManager dm, Dictionary< string, string > line, string portraitId = null) static
Definition at line 747 of file CustomDramaExpansion.cs.
set_sprite()
static bool set_sprite (DramaManager dm, Dictionary< string, string > line, string spriteId = null) static
Definition at line 754 of file CustomDramaExpansion.cs.
show_book()
static bool show_book (DramaManager dm, Dictionary< string, string > line, string bookEntry) static
Definition at line 761 of file CustomDramaExpansion.cs.
    {
        Effect.Get(effectId)?.Play(new Point(x, y));
        return true;
    }
    [ElinDramaActionInvoke(null)]
    public static bool play_emote(DramaManager dm, Dictionary<string, string> line, Emo emote, float duration = 1f)
    {
        dm.GetChara(line["actor"]).ShowEmo(emote, duration, skipSame: false);
        return true;
    }
    [ElinDramaActionInvoke(null)]
    public static bool play_screen_effect(DramaManager dm, Dictionary<string, string> line, string effectId)
    {
        ScreenEffect.Play(effectId);
Variable Documentation
$
$
Definition at line 16 of file CustomDramaExpansion.cs.
Referenced by Lang._currency(), Lang._Number(), Zone.Activate(), SourceCard.AddRow(), RecipeManager.Create(), DramaInvokeDetail.CreateConvertExpression(), ModPackage.ExportSourceLocalizations(), SourceData< T, T2 >.BaseRow.ExportTexts(), SpriteReplacer.GetSprite(), SourceImporter.HotInit(), SourceData< T, T2 >.ImportData(), SourceImporter.ImportFilesCached(), SourceData< T, T2 >.BaseRow.ImportTexts(), BookList.Init(), SourceMaterial.Row.Init(), SourceImporter.LoadBySheetName(), ElinGameIOPropertyAttribute.LoadGameIOProperty(), CustomCharaContent.OnGameLoad(), CustomZoneContent.OnGameLoad(), ModPackage.ParseLangMod(), ModPackage.ParseMap(), ModPackage.ParseMapPiece(), ModPackage.ParsePortrait(), ModPackage.ParseSound(), ModPackage.ParseTalkText(), ModPackage.ParseTexture(), ModPackage.ParseTextureReplace(), BaseModManager.PublishEvent(), ContentHomeRanking.Refresh(), SourceData< T, T2 >.RemoveDuplicateRows(), ElinGameIOPropertyAttribute.SaveGameIOProperty(), RenderRow.SetRenderData(), BaseModManager.SubscribeEvent< T >(), ClassExtension.Tag(), ClassExtension.ToFormat(), ClassExtension.ToHex(), CustomCharaContent.ToString(), CustomElementContent.ToString(), CustomGunEffectSetting.ToString(), CustomMerchantStock.ToString(), CustomThingContent.ToString(), HSLColor.ToString(), HSVColor.ToString(), and WidgetDebug.UpdateText().
Compiled
RegexOptions. Compiled
Definition at line 16 of file CustomDramaExpansion.cs.