Elin Decompiled Documentation: Elin/DramaManager.cs File Reference
DramaManager.cs File Reference
Classes
class DramaManager
Variables
$ && this[0]
CS$. text = CS$<>8__locals1.text.Replace(text2, this.tg.chara.GetTalkText(text2.Remove(0, 1), false, true))
Variable Documentation
text
CS$. text = CS$<>8__locals1.text.Replace(text2, this.tg.chara.GetTalkText(text2.Remove(0, 1), false, true))
Definition at line 1637 of file DramaManager.cs.
Referenced by Chara._CreateRenderer(), Chara._Move(), UIResourceTrack._Refresh(), WidgetDate._Refresh(), DramaCustomSequence._Talk(), DramaCustomSequence._TempTalk(), ActPlan._Update(), Element._WriteNote(), UIScreenshot.Activate(), WidgetManager.ActivateWidget(), LayerInteraction.Page.Add(), UICurrency.Add(), PopupManager.Add(), MsgLog.Add(), InspectGroup< T >.Add(), Thing.AddAttackEvaluation(), DialogDrama.AddChoice(), UICharaMaker.AddDomain(), WidgetInspector.AddLog(), ElementContainer.AddNote(), UIHomeInfo.AddReport(), WindowChara.AddStatus(), WidgetMainText.Append(), Feat.Apply(), Card.ApplyNewLine(), Person.ApplyTone(), Card.ApplyTone(), Core.Awake(), CoreDebug.BroadcastNext(), CardFilter.BuildList(), ContentGallery.Page.BuildNote(), DramaCustomSequence.BuildTextData(), CoreDebug.ChangeJob(), CoreDebug.ChangeRace(), Element.CheckLevelBonus(), CoreDebug.ClearLastWishFlag(), LayerFeedback.CollectFiles(), GameLang.Convert(), DramaActor.ConvertAdv(), GameLang.ConvertDrama(), GameLang.ConvertThirdPerson(), TraitCrafter.Craft(), RecipeCard.Craft(), SourceMaterial.Row.CreateByProduct(), Player.CreateEquip(), SourceBacker.CreateRow(), TraitNewZone.CreateZone(), ActEffect.DamageEle(), Card.DamageHP(), WidgetManager.DialogSave(), Card.Die(), Chara.Die(), CardRenderer.Draw(), Player.DreamSpell(), UICharaMaker.EditName(), Zone.ExportDialog(), CoreDebug.FirstAdventurer(), CoreDebug.Fix_EtherDisease(), ContentConfigInput.g___onInstantiate(), NewsList.g__AddDir(), LayerFeedback.g__Append(), LayerFeedback.g__ParseLog(), AttackProcess.g__Proc(), ModManager.g__TryAddLang(), UIHomeInfo.g__Write(), BackerContent.GakiConvert(), Player.GenerateBackgroundText(), Steam.GetAchievement(), Player.GetBackgroundText(), Quest.GetDetail(), QuestProgression.GetDetail(), QuestTrackCraft.GetDetail(), QuestGuild.GetDetailText(), Person.GetDramaTitle(), BaseCondition.GetElementSource(), ModManager.GetElinIni(), Thing.GetExtraName(), CardFilter.GetFilterItem(), FactionBranch.GetHearthHint(), Feat.GetHint(), ActionMode.GetHintText(), Chara.GetHoverText(), Thing.GetHoverText(), TraitBed.GetHoverText(), Chara.GetHoverText2(), TraitGacha.GetIdCoin(), LayerInspect.GetItem(), Recipe.GetName(), Recipe.Ingredient.GetName(), SourceChara.Row.GetName(), SourceThing.Row.GetName(), CardRow.GetName(), Thing.GetName(), Chara.GetName(), GameIO.GetNewId(), Cell.GetObjName(), Religion.GetOfferingValue(), LayerInteraction.GetPage(), CoreConfig.GetPostEffectProfile(), Card.GetPrice(), Zone.GetProfile(), AM_EditMarker.GetSimpleText(), Card.GetTalkText(), AttackProcess.GetText(), GameUpdater.GetText(), Happiness.GetText(), HappinessSummary.GetText(), HomeResource.CostList.GetText(), Stats.GetText(), UndoManager.GetText(), Check.GetText(), BaseTaskHarvest.GetText(), Religion.GetTextBenefit(), InvOwner.GetTextDetail(), Chara.GetTextHobby(), QuestCraft.GetTextProgress(), QuestDeliver.GetTextProgress(), Chara.GetTextWork(), QuestSequence.GetTitle(), Chara.GetTopicText(), Quest.GetTrackerText(), TaskHarvest.HarvestThing(), TaskHarvest.HaveHarvestThing(), AI_Idle.IdleActText(), TraitTrap.IgnoreWhenLevitating(), CardFilter.Init(), DramaEventEndRoll.Init(), MapPiece.Init(), UIDragGridInfo.Init(), Dialog.InputName(), CharaBody.IsEquippable(), TraitCrafter.IsIngredient(), CoreConfig.BackerContentConfig.IsJapanese(), CoreDebug.LastWish(), CoreDebug.ListChara(), BaseArea.ListInteractions(), InvOwner.ListInteractions(), Zone.ListLandFeats(), CoreDebug.ListThing(), DramaManager.Load(), FactionBranch.LogRaw(), GameIO.MakeBackup(), AI_Fish.Makefish(), AI_OpenGambleChest.MakeReward(), Msg.Nerun(), WidgetFeed.Nerun(), WidgetSearch.OnActivate(), TraitTrap.OnActivateTrap(), UIQueue.OnAdd(), Player.OnAdvanceRealHour(), SourceThingV.OnAfterImportData(), HotItemLayer.OnClick(), BaseListPeople.OnClick(), WidgetSceneCustomizer.OnClickSave(), InvOwner.OnDrag(), LayerAbility.OnDrag(), WidgetHotbar.OnDrag(), TextureManager.OnDropFile(), TraitFortuneCookie.OnEat(), LayerEditHouse.OnInit(), LayerUploader.OnInit(), UIInventory.OnInit(), ListPeopleCallReserve.OnInstantiate(), ElementContainerCard.OnLevelDown(), ElementContainerCard.OnLevelUp(), TaskCut.OnProgressComplete(), InspectGroupChara.OnSetActions(), ActionMode.OnShowExtraHint(), ContentQuest.OnSwitchContent(), Scene.OnUpdate(), TraitDaggerGrave.OnUse(), TraitDetector.OnUse(), CardInspector.OnValidate(), ContentConfigOther.OpenBackerCodeInput(), GameLang.Parse(), DramaManager.ParseLine(), ResearchPlan.ParseReward(), Act.Perform(), Check.Perform(), DramaEventMethod.Play(), EffectText.Play(), FoodEffect.Proc(), ActEffect.Proc(), ButtonElement.Refresh(), LayerTravel.Refresh(), PartialMapMenu.Refresh(), UICharaMaker.Refresh(), UICurrency.Refresh(), UIHangIcon.Refresh(), UIRecipeInfo.Refresh(), WidgetMouseover.Refresh(), WidgetStatsBar.Refresh(), UIRecipeInfo.RefreshBalance(), BuildMenu.RefreshCategory(), UIMagicChest.RefreshCats(), WindowChara.RefreshEquipment(), UIInventory.RefreshGrid(), ThingContainer.RefreshGrid(), LayerCollectible.RefreshInfo(), UIInventory.RefreshList(), UIInventory.RefreshMenu(), ModManager.RefreshMods(), BaseTileSelector.RefreshMouseInfo(), WindowChara.RefreshNote(), WindowChara.RefreshProfile(), WindowChara.RefreshStatic(), ActionMode.RefreshTexts(), LayerNewspaper.RefreshWeather(), CoreConfig.Reset(), SerializedCards.Restore(), AI_Idle.Run(), GameIO.SaveGame(), CardRenderer.Say(), WidgetPopText.Say(), UI.Say(), Msg.SayHomeMember(), Msg.SayPic(), Msg.SayRaw(), Card.SayRaw(), ContentQuest.SelectQuest(), LayerCollectible.SetButton(), CardInspector.SetCard(), ItemGeneral.SetChara(), DramaActor.SetChoice(), HUD.SetDragImage(), HUD.SetDragText(), LayerConfig.SetFont(), ButtonElement.SetGrid(), ButtonGrid.SetIngredient(), Trait.SetMainText(), TraitAbility.SetMainText(), TraitToolRange.SetMainText(), ItemResearch.SetPlan(), WindowChara.SetPortraitBG(), WindowChara.SetPortraitFrame(), ItemQuest.SetQuest(), Card.SetRandomTone(), RenderRow.SetRenderData(), ItemHomeResource.SetResource(), ContentConfig.SetSlider(), LayerConfig.SetSlider(), Recipe.SetTextDifficulty(), FactionRelation.SetTextHostility(), Religion.SetTextRelation(), GameDate.ShipGoods(), HotItemActionMode.ShouldHighlight(), TerrainMenu.Show(), ActionHint.Show(), ActPlan.ShowContextMenu(), UI.ShowLang(), UI.ShowSceneSelector(), Card.SpawnLoot(), Tactics.Tactics(), CoreExtension.TagColor(), Msg.Talk(), WidgetFeed.Talk(), DramaActor.Talk(), Card.TalkRaw(), Chara.TalkTopic(), AI_PlayMusic.ThrowReward(), UI.ToggleFeedback(), Msg.ToUpperFirst(), Religion.TryGetGift(), Card.TryMakeRandomItem(), TraitCoreZone.TrySetAct(), TraitNote.TrySetAct(), TraitTeleporter.TrySetAct(), TraitToolTorch.TrySetHeldAct(), Map.TryShatter(), ELayer.TryShowHint(), CardRenderer.TrySpawnOrbit(), GoalCombat.TryUseAbility(), LayerTextureViewer.Update(), LayerUploader.Update(), CoreDebug.UpdateInput(), WidgetDebug.UpdateText(), LayerUploader.Upload(), Chara.UseAbility(), SourceManager.ValidateLang(), ActEffect.Wish(), DNA.WriteNote(), Thing.WriteNote(), and ButtonGrid.WriteReqMat().
this[0]
$&& this[0]
Definition at line 1634 of file DramaManager.cs.