Elin Decompiled Documentation: Elin/DramaValueExpression.cs File Reference
DramaValueExpression.cs File Reference
Classes
class DramaValueExpression
Functions
publicramaValueExpression (stringexpression)
publicstaticboolTryParse (stringexpression, outramaValueExpressionvalueExpr)
publicstaticimplicitoperatorramaValueExpression (stringexpr)
publicstaticimplicitoperatorstring (ramaValueExpressionexpr)
publicintCalc (intlhs)
float Calc (float lhs)
float Diff (float lhs)
int Diff (int lhs)
float ModOrSet (float lhs)
int ModOrSet (int lhs)
bool Compare (float lhs)
bool Compare (int lhs)
Variables
$
RegexOptions. Compiled
publicstringExpression { get
publicstringOp { get
publicstringRhs { get
Function Documentation
Calc()
float Calc (float lhs)
Definition at line 13 of file DramaValueExpression.cs.
    {
        Expression = expression.Trim();
        Match match = _listSyntaxRegex.Match(Expression);
        Op = match.Groups["op"].Value;
        Rhs = match.Groups["number"].Value;
    }
    public static bool TryParse(string expression, out DramaValueExpression valueExpr)
    {
        valueExpr = new DramaValueExpression(expression);
Referenced by Element._WriteNote().
Compare() [1/2]
bool Compare (float lhs)
Definition at line 116 of file DramaValueExpression.cs.
        {
            return lhs;
        }
        string op = Op;
        if (!(op == "++"))
        {
            if (op == "--")
            {
                return lhs - 1;
            }
            if (!int.TryParse(Rhs, out var result))
            {
                return lhs;
            }
            switch (Op)
            {
            case "+":
                return lhs + result;
            case "-":
                return lhs - result;
            case "*":
            case "x":
                return lhs * result;
            case "/":
                return lhs / result;
            case "=":
            case "==":
                return result;
            case "":
                return result;
            default:
                return lhs;
            }
        }
        return lhs + 1;
    }
Referenced by ThingContainer.FindStealable(), BuildMenu.RefreshCategory(), and ActEffect.Wish().
Compare() [2/2]
bool Compare (int lhs)
Definition at line 154 of file DramaValueExpression.cs.
    {
        if (Expression.IsEmpty())
        {
            return false;
        }
        if (Op == "")
        {
            if (float.TryParse(Rhs, out var result))
            {
                return Mathf.Approximately(lhs, result);
            }
            return false;
        }
        if (!float.TryParse(Rhs, out var result2))
        {
            return false;
        }
        switch (Op)
        {
        case ">":
            return lhs > result2;
        case "<":
            return lhs < result2;
        case "=":
        case "==":
            return Mathf.Approximately(lhs, result2);
        case ">=":
            return lhs >= result2;
        case "<=":
            return lhs <= result2;
        case "!=":
            return !Mathf.Approximately(lhs, result2);
        default:
            return false;
        }
    }
Diff() [1/2]
float Diff (float lhs)
Definition at line 26 of file DramaValueExpression.cs.
    {
Diff() [2/2]
int Diff (int lhs)
Definition at line 31 of file DramaValueExpression.cs.
    {
ModOrSet() [1/2]
float ModOrSet (float lhs)
Definition at line 36 of file DramaValueExpression.cs.
    {
        if (Expression.IsEmpty())
        {
            return lhs;
        }
        if (!$"{lhs} {Expression}".TryEvaluateAsCalc(out int result, (object)null))
        {
            return lhs;
        }
        return result;
    }
    public float Calc(float lhs)
    {
        if (Expression.IsEmpty())
        {
            return lhs;
        }
        if (!$"{lhs} {Expression}".TryEvaluateAsCalc(out float result, (object)null))
        {
            return lhs;
        }
        return result;
    }
    public float Diff(float lhs)
    {
        return ModOrSet(lhs) - lhs;
    }
    public int Diff(int lhs)
    {
        return ModOrSet(lhs) - lhs;
    }
    public float ModOrSet(float lhs)
ModOrSet() [2/2]
int ModOrSet (int lhs)
Definition at line 76 of file DramaValueExpression.cs.
        {
            return lhs;
        }
        string op = Op;
        if (!(op == "++"))
        {
            if (op == "--")
            {
                return lhs - 1f;
            }
            if (!float.TryParse(Rhs, out var result))
            {
                return lhs;
            }
            switch (Op)
            {
            case "+":
                return lhs + result;
            case "-":
                return lhs - result;
            case "*":
            case "x":
                return lhs * result;
            case "/":
                return lhs / result;
            case "=":
            case "==":
                return result;
            case "":
                return result;
            default:
                return lhs;
            }
        }
        return lhs + 1f;
    }
    public int ModOrSet(int lhs)
publicintCalc()
_listSyntaxRegex.publicintCalc (intlhs)
Definition at line 38 of file DramaValueExpression.cs.
References $.
publicramaValueExpression()
_listSyntaxRegex.publicramaValueExpression (stringexpression)
Definition at line 14 of file DramaValueExpression.cs.
    {
        Expression = expression.Trim();
        Match match = _listSyntaxRegex.Match(Expression);
        Op = match.Groups["op"].Value;
        Rhs = match.Groups["number"].Value;
    }
References DramaValueExpression._listSyntaxRegex.
publicstaticboolTryParse()
_listSyntaxRegex.publicstaticboolTryParse (stringexpression , outramaValueExpressionvalueExpr)
Definition at line 22 of file DramaValueExpression.cs.
    {
        valueExpr = new DramaValueExpression(expression);
        return true;
    }
publicstaticimplicitoperatorramaValueExpression()
_listSyntaxRegex.publicstaticimplicitoperatorramaValueExpression (stringexpr)
Definition at line 28 of file DramaValueExpression.cs.
    {
        return new DramaValueExpression(expr);
    }
publicstaticimplicitoperatorstring()
_listSyntaxRegex.publicstaticimplicitoperatorstring (ramaValueExpressionexpr)
Definition at line 33 of file DramaValueExpression.cs.
    {
        return expr.Expression;
    }
Variable Documentation
$
$
Definition at line 6 of file DramaValueExpression.cs.
Referenced by publicintCalc().
Compiled
RegexOptions. Compiled
Definition at line 6 of file DramaValueExpression.cs.
publicstringExpression
publicstringExpression { get
Definition at line 8 of file DramaValueExpression.cs.
publicstringOp
publicstringOp { get
Definition at line 10 of file DramaValueExpression.cs.
publicstringRhs
publicstringRhs { get
Definition at line 12 of file DramaValueExpression.cs.