Elin Decompiled Documentation: IUISkin Interface Reference
IUISkin Interface Reference
Public Member Functions
void ApplySkin ()
Detailed Description
Definition at line 1 of file IUISkin.cs.
Member Function Documentation
ApplySkin()
void IUISkin.ApplySkin ()
Implemented in Layer, UIButton, UIHighlight, UIImage, UIRawImage, UISelectableGroup, UIText, Window, and WindowInner.
Referenced by Widget.ApplySkin(), Core.ApplySkins(), and UIInspector.Inspect().
The documentation for this interface was generated from the following file:
Elin/Plugins.UI/IUISkin.cs