Elin Decompiled Documentation: ICardParent Interface Reference
ICardParent Interface Reference
Public Member Functions
ICardParent GetRoot ()
void RemoveCard (Card c)
void OnChildNumChange (Card c)
Detailed Description
Definition at line 1 of file ICardParent.cs.
Member Function Documentation
GetRoot()
ICardParent ICardParent.GetRoot ()
Implemented in Card, and Zone.
Referenced by Card.GetRoot().
OnChildNumChange()
void ICardParent.OnChildNumChange (Card c)
Implemented in Card, and Zone.
Referenced by Card.ModNum().
RemoveCard()
void ICardParent.RemoveCard (Card c)
Implemented in Card, and Zone.
Referenced by Zone.AddCard(), Card.AddThing(), Card.Destroy(), Map.PutAway(), and ActRanged.TryReload().
The documentation for this interface was generated from the following file:
Elin/ICardParent.cs