Elin Decompiled Documentation: IMouseHint Interface Reference
IMouseHint Interface Reference
Public Member Functions
bool ShowMouseHintLeft ()
string GetTextMouseHintLeft ()
bool ShowMouseHintRight ()
string GetTextMouseHintRight ()
Detailed Description
Definition at line 1 of file IMouseHint.cs.
Member Function Documentation
GetTextMouseHintLeft()
string IMouseHint.GetTextMouseHintLeft ()
Implemented in ButtonAbility, and ButtonGrid.
Referenced by UI.ShowMouseHint().
GetTextMouseHintRight()
string IMouseHint.GetTextMouseHintRight ()
Implemented in ButtonAbility, and ButtonGrid.
Referenced by UI.ShowMouseHint().
ShowMouseHintLeft()
bool IMouseHint.ShowMouseHintLeft ()
Implemented in ButtonAbility, and ButtonGrid.
Referenced by UI.ShowMouseHint().
ShowMouseHintRight()
bool IMouseHint.ShowMouseHintRight ()
Implemented in ButtonAbility, and ButtonGrid.
Referenced by UI.ShowMouseHint().
The documentation for this interface was generated from the following file:
Elin/IMouseHint.cs