Elin Decompiled Documentation: IPathfinder Interface Reference
IPathfinder Interface Reference
Public Member Functions
void FindPath (PathProgress progress)
void Init (IPathfindGrid _grid, WeightCell[,] _weightMap, int size)
Detailed Description
Definition at line 3 of file IPathfinder.cs.
Member Function Documentation
FindPath()
void IPathfinder.FindPath (PathProgress progress)
Implemented in Algorithms.PathFinder.
Referenced by PathManager.RequestPathImmediate(), and PathThread.Start().
Init()
void IPathfinder.Init (IPathfindGrid _grid, WeightCell _weightMap[,], int size)
Implemented in Algorithms.PathFinder.
Referenced by Map.SetReference().
The documentation for this interface was generated from the following file:
Elin/IPathfinder.cs