Elin Decompiled Documentation: SFB.IStandaloneFileBrowser Interface Reference
SFB.IStandaloneFileBrowser Interface Reference
Public Member Functions
string[] OpenFilePanel (string title, string directory, ExtensionFilter[] extensions, bool multiselect)
string[] OpenFolderPanel (string title, string directory, bool multiselect)
string SaveFilePanel (string title, string directory, string defaultName, ExtensionFilter[] extensions)
void OpenFilePanelAsync (string title, string directory, ExtensionFilter[] extensions, bool multiselect, Action< string[]> cb)
void OpenFolderPanelAsync (string title, string directory, bool multiselect, Action< string[]> cb)
void SaveFilePanelAsync (string title, string directory, string defaultName, ExtensionFilter[] extensions, Action< string > cb)
Detailed Description
Definition at line 5 of file IStandaloneFileBrowser.cs.
Member Function Documentation
OpenFilePanel()
string[] SFB.IStandaloneFileBrowser.OpenFilePanel (string title, string directory, ExtensionFilter[] extensions, bool multiselect)
Implemented in SFB.StandaloneFileBrowserWindows.
Referenced by SFB.StandaloneFileBrowser.OpenFilePanel().
OpenFilePanelAsync()
void SFB.IStandaloneFileBrowser.OpenFilePanelAsync (string title, string directory, ExtensionFilter[] extensions, bool multiselect, Action< string[]> cb)
Implemented in SFB.StandaloneFileBrowserWindows.
Referenced by SFB.StandaloneFileBrowser.OpenFilePanelAsync().
OpenFolderPanel()
string[] SFB.IStandaloneFileBrowser.OpenFolderPanel (string title, string directory, bool multiselect)
Implemented in SFB.StandaloneFileBrowserWindows.
Referenced by SFB.StandaloneFileBrowser.OpenFolderPanel().
OpenFolderPanelAsync()
void SFB.IStandaloneFileBrowser.OpenFolderPanelAsync (string title, string directory, bool multiselect, Action< string[]> cb)
Implemented in SFB.StandaloneFileBrowserWindows.
Referenced by SFB.StandaloneFileBrowser.OpenFolderPanelAsync().
SaveFilePanel()
string SFB.IStandaloneFileBrowser.SaveFilePanel (string title, string directory, string defaultName, ExtensionFilter[] extensions)
Implemented in SFB.StandaloneFileBrowserWindows.
Referenced by SFB.StandaloneFileBrowser.SaveFilePanel().
SaveFilePanelAsync()
void SFB.IStandaloneFileBrowser.SaveFilePanelAsync (string title, string directory, string defaultName, ExtensionFilter[] extensions, Action< string > cb)
Implemented in SFB.StandaloneFileBrowserWindows.
Referenced by SFB.StandaloneFileBrowser.SaveFilePanelAsync().
The documentation for this interface was generated from the following file:
Elin/Plugins.basecore/SFB/IStandaloneFileBrowser.cs