Elin Decompiled Documentation: Version Struct Reference
Version Struct Reference
Public Member Functions
string GetText ()
int GetInt ()
int GetInt (int _major, int _minor, int _batch)
bool IsBelow (int _major, int _minor, int _batch)
bool IsBelow (Version v)
bool IsSameOrBelow (Version v)
bool IsBelow (int _int)
bool IsSaveCompatible (Version v)
override bool Equals (object obj)
override int GetHashCode ()
Static Public Member Functions
static Version Get (string str)
static Version Get (int i)
Public Attributes
int major
int minor
int batch
int fix
bool demo
Detailed Description
Definition at line 4 of file Version.cs.
Member Function Documentation
Equals()
override bool Version.Equals (object obj) inline
Definition at line 95 of file Version.cs.
    {
        Version version = (Version)obj;
        if (version.major == major && version.minor == minor)
        {
            return version.batch == batch;
        }
        return false;
    }
References batch, major, and minor.
Get() [1/2]
static Version Version.Get (int i) inline static
Definition at line 73 of file Version.cs.
    {
        Version result = default(Version);
        result.major = i / 1000000;
        result.minor = i / 1000 % 1000;
        result.batch = i % 1000;
        return result;
    }
Get() [2/2]
static Version Version.Get (string str) inline static
Definition at line 55 of file Version.cs.
    {
        if (str.IsEmpty())
        {
            return default(Version);
        }
        string[] array = str.Split('.');
        if (array.Length < 3)
        {
            return default(Version);
        }
        Version result = default(Version);
        result.major = array[0].ToInt();
        result.minor = array[1].ToInt();
        result.batch = array[2].ToInt();
        return result;
    }
Referenced by MapMetaData.IsValidVersion(), Net.DownloadMeta.IsValidVersion(), and BaseModPackage.IsValidVersion().
GetHashCode()
override int Version.GetHashCode () inline
Definition at line 105 of file Version.cs.
    {
        return GetInt();
    }
References GetInt().
GetInt() [1/2]
int Version.GetInt () inline
Definition at line 21 of file Version.cs.
    {
        return major * 1000000 + minor * 1000 + batch;
    }
References batch, major, and minor.
Referenced by Map.ExportMetaData(), GetHashCode(), IsBelow(), IsSameOrBelow(), Zone.OnVisit(), ModManager.ParseExtra(), LangSetting.SetVersion(), and Net.UploadFile().
GetInt() [2/2]
int Version.GetInt (int _major, int _minor, int _batch) inline
Definition at line 26 of file Version.cs.
    {
        return _major * 1000000 + _minor * 1000 + _batch;
    }
GetText()
string Version.GetText () inline
Definition at line 16 of file Version.cs.
    {
        return ((minor >= 23) ? "EA" : "Beta") + " " + minor + "." + batch + ((fix == 0) ? "" : (" Patch " + fix)) + (demo ? "demo".lang() : "");
    }
References batch, demo, fix, and minor.
Referenced by WidgetSystemIndicator._Refresh(), Core.Awake(), SourceData< T, T2 >.ExportTexts(), WidgetFeed.OnActivate(), WidgetMainText.OnActivate(), LayerFeedback.OnInit(), LayerTitle.OnInit(), LayerLoadGame.RefreshInfo(), LayerLoadGame.RefreshList(), and CoreConfig.TryLoadConfig().
IsBelow() [1/3]
bool Version.IsBelow (int _int) inline
Definition at line 50 of file Version.cs.
    {
        return GetInt() < _int;
    }
References GetInt().
IsBelow() [2/3]
bool Version.IsBelow (int _major, int _minor, int _batch) inline
Definition at line 31 of file Version.cs.
    {
        return GetInt() < GetInt(_major, _minor, _batch);
    }
References GetInt().
Referenced by IsBelow(), IsSameOrBelow(), IsSaveCompatible(), MapMetaData.IsValidVersion(), Net.DownloadMeta.IsValidVersion(), BaseModPackage.IsValidVersion(), and CoreConfig.TryLoadConfig().
IsBelow() [3/3]
bool Version.IsBelow (Version v) inline
Definition at line 36 of file Version.cs.
    {
        return IsBelow(v.GetInt());
    }
References GetInt(), and IsBelow().
IsSameOrBelow()
bool Version.IsSameOrBelow (Version v) inline
Definition at line 41 of file Version.cs.
    {
        if (v.GetInt() != GetInt())
        {
            return IsBelow(v.GetInt());
        }
        return true;
    }
References GetInt(), and IsBelow().
Referenced by Net.DownloadMeta.IsValidVersion().
IsSaveCompatible()
bool Version.IsSaveCompatible (Version v) inline
Definition at line 82 of file Version.cs.
    {
        if (IsBelow(v))
        {
            return false;
        }
        if (major == v.major)
        {
            return minor >= 21;
        }
        return false;
    }
References IsBelow(), major, and minor.
Referenced by GameIO.CanLoad(), LayerLoadGame.RefreshInfo(), and LayerLoadGame.RefreshList().
Member Data Documentation
batch
int Version.batch
Definition at line 10 of file Version.cs.
Referenced by Equals(), GetInt(), and GetText().
demo
bool Version.demo
Definition at line 14 of file Version.cs.
Referenced by GetText(), Card.LevelUp(), FactionBranch.ModExp(), LayerHelp.OnAfterInit(), LayerMod.OnInit(), TraitMoongate.OnUse(), TraitMoongateEx.OnUse(), Net.SendChat(), UI.ToggleFeedback(), TraitCoreZone.TrySetAct(), and TraitWaystone.TrySetAct().
fix
int Version.fix
Definition at line 12 of file Version.cs.
Referenced by GetText().
major
int Version.major
Definition at line 6 of file Version.cs.
Referenced by Equals(), GetInt(), and IsSaveCompatible().
minor
int Version.minor
Definition at line 8 of file Version.cs.
Referenced by Equals(), GetInt(), GetText(), and IsSaveCompatible().
The documentation for this struct was generated from the following file:
Elin/Plugins.basecore/Version.cs