Elin Decompiled Documentation: BitArray32 Struct Reference
BitArray32 Struct Reference
Public Member Functions
BitArray32 (uint bits)
void SetBit (int index)
void UnsetBit (int index)
uint GetBits (uint mask)
void SetBits (uint mask)
void UnsetBits (uint mask)
override bool Equals (object obj)
bool Equals (BitArray32 arr)
override int GetHashCode ()
int ToInt ()
void SetInt (int i)
override string ToString ()
void RequireIndexInBounds (int index)
Public Attributes
uint Bits
Properties
bool this[int index] [get, set]
int Length [get]
Detailed Description
Definition at line 4 of file BitArray32.cs.
Constructor & Destructor Documentation
BitArray32()
BitArray32.BitArray32 (uint bits) inline
Definition at line 31 of file BitArray32.cs.
    {
        Bits = bits;
    }
References Bits.
Member Function Documentation
Equals() [1/2]
bool BitArray32.Equals (BitArray32 arr) inline
Definition at line 74 of file BitArray32.cs.
    {
        return Bits == arr.Bits;
    }
References Bits.
Equals() [2/2]
override bool BitArray32.Equals (object obj) inline
Definition at line 65 of file BitArray32.cs.
    {
        if (obj is BitArray32)
        {
            return Bits == ((BitArray32)obj).Bits;
        }
        return false;
    }
References Bits.
GetBits()
uint BitArray32.GetBits (uint mask) inline
Definition at line 50 of file BitArray32.cs.
    {
        return Bits & mask;
    }
References Bits.
GetHashCode()
override int BitArray32.GetHashCode () inline
Definition at line 79 of file BitArray32.cs.
    {
        return Bits.GetHashCode();
    }
References Bits.
RequireIndexInBounds()
void BitArray32.RequireIndexInBounds (int index) inline
Definition at line 114 of file BitArray32.cs.
    {
    }
Referenced by SetBit(), and UnsetBit().
SetBit()
void BitArray32.SetBit (int index) inline
Definition at line 36 of file BitArray32.cs.
    {
        RequireIndexInBounds(index);
        uint num = (uint)(1 << index);
        Bits |= num;
    }
References Bits, and RequireIndexInBounds().
SetBits()
void BitArray32.SetBits (uint mask) inline
Definition at line 55 of file BitArray32.cs.
    {
        Bits |= mask;
    }
References Bits.
SetInt()
void BitArray32.SetInt (int i) inline
Definition at line 89 of file BitArray32.cs.
    {
        Bits = (uint)i;
    }
References Bits.
Referenced by AreaData._OnDeserialized(), Card._OnDeserialized(), WorkSession._OnDeserialized(), ClassExtension.IsOn(), SourcePref.OnAfterDeserialize(), and SerializedCards.Restore().
ToInt()
int BitArray32.ToInt () inline
Definition at line 84 of file BitArray32.cs.
    {
        return (int)Bits;
    }
References Bits.
Referenced by AreaData._OnSerializing(), Card._OnSerializing(), DNA._OnSerializing(), WorkSession._OnSerializing(), SerializedCards.Add(), and SourcePref.OnBeforeSerialize().
ToString()
override string BitArray32.ToString () inline
Definition at line 94 of file BitArray32.cs.
    {
        char[] array = new char[44];
        int i;
        for (i = 0; i < 11; i++)
        {
            array[i] = "BitArray32{"[i];
        }
        uint num = 2147483648u;
        while (num != 0)
        {
            array[i] = (((Bits & num) != 0) ? '1' : '0');
            num >>= 1;
            i++;
        }
        array[i] = '}';
        return new string(array);
    }
References Bits.
UnsetBit()
void BitArray32.UnsetBit (int index) inline
Definition at line 43 of file BitArray32.cs.
    {
        RequireIndexInBounds(index);
        uint num = (uint)(1 << index);
        Bits &= ~num;
    }
References Bits, and RequireIndexInBounds().
UnsetBits()
void BitArray32.UnsetBits (uint mask) inline
Definition at line 60 of file BitArray32.cs.
    {
        Bits &= ~mask;
    }
References Bits.
Member Data Documentation
Bits
uint BitArray32.Bits
Definition at line 6 of file BitArray32.cs.
Referenced by Player.Flags._OnSerializing(), SocketData._OnSerializing(), SurvivalManager.Flags._OnSerializing(), BitArray32(), Equals(), GetBits(), GetHashCode(), Chara.OnSerializing(), ClassWithBits.OnSerializing(), Game.Flags.OnSerializing(), Hoard.Item.OnSerializing(), Map.OnSerializing(), SkinDeco.OnSerializing(), Window.SaveData.OnSerializing(), Spatial.OnSerializing(), SetBit(), SetBits(), SetInt(), ToInt(), ToString(), UnsetBit(), and UnsetBits().
Property Documentation
Length
int BitArray32.Length get
Definition at line 29 of file BitArray32.cs.
this[int index]
bool BitArray32.this[int index] get set
Definition at line 8 of file BitArray32.cs.
    {
        get
        {
            uint num = (uint)(1 << index);
            return (Bits & num) == num;
        }
        set
        {
            uint num = (uint)(1 << index);
            if (value)
            {
                Bits |= num;
            }
            else
            {
                Bits &= ~num;
            }
        }
    }
The documentation for this struct was generated from the following file:
Elin/Plugins.basecore/BitArray32.cs