Elin Decompiled Documentation: Elin/Plugins.UI/UIBook.cs File Reference
UIBook.cs File Reference
Classes
class UIBook
class UIBook.Item
class UIBook.Page
Functions
list. Add (item3)
elseif (item!=null)
if (item3.idFile==idFirstFile &&item3.id==idFirstTopic)
list. Refresh ()
if (item!=null)
Variables
$
item3. title = item3.title.TrimStart('$')
else
Function Documentation
Add()
list. AddButtonClose.Add (item3)
Referenced by UIButtonList.AddButton(), UIItemList.AddItem(), PointList.Deserialize(), FactionBranch.GenerateGarbage(), DramaEventEndRoll.Init(), CoreDebug.InitDebugCommands(), GamePrincipal.ListItems(), Trait.OnBarter(), SourceFood.OnImportRow(), SourceMaterial.OnImportRow(), TraitGiftJure.OnUse(), WindowChara.RefreshNote(), FortuneRollData.RefreshPrize(), and GameDate.ShipRandomPackages().
elseif()
AddButtonClose.elseif (item! = null)
Definition at line 619 of file UIBook.cs.
            {
                list.Add(item3);
            }
if() [1/2]
AddButtonClose.if (item! = null)
Definition at line 634 of file UIBook.cs.
if() [2/2]
AddButtonClose.if (item3::idFile = =idFirstFile&&item3::id==idFirstTopic)
Definition at line 627 of file UIBook.cs.
        {
Referenced by HotItemNoItem._TrySetAct(), ActPlan._Update(), HoardActor.Activate(), LayerEditPortrait.Activate(), MeshPass.AddShadow(), CoreConfig.ApplyGrading(), CoreConfig.ApplyScale(), Scene.ApplyZoneConfig(), Chara.DestroyPath(), WidgetManager.DialogLoad(), WidgetManager.DialogSave(), BaseTileMap.Draw(), BaseTileMap.DrawRoof(), BaseTileMap.DrawTile(), TileMapElona.DrawTile(), PartialMap.ExportDialog(), Zone.ExportDialog(), QuestSupplySpecific.GetBonus(), Check.GetDC(), HomeResourceNature.GetDestValue(), TraitTicketFurniture.GetPrice(), Los.GetRushPoint(), BaseTileMap.GetThingPosition(), EloMap.GetTileInfo(), Zone.GrowPlants(), AM_Copy.ImportDialog(), Zone.ImportDialog(), Window.Init(), InvOwner.ListInteractions(), TaskDump.ListThingsToPut(), TraitSeed.MakeSeed(), CharacterSpacing.ModifyMesh(), Widget.OnChangePosition(), ContentConfigOther.OnClickDownloadWallpaper(), WidgetSceneCustomizer.OnClickLoad(), WidgetSceneCustomizer.OnClickSave(), TraitBookSkill.OnCreate(), TaskDrawWater.OnCreateProgress(), LayerConfig.OnInit(), LayerEditHouse.OnInit(), ListPeopleCallReserve.OnInstantiate(), GenRoom.OnPopulate(), AM_Populate.OnProcessTiles(), AM_Terrain.OnProcessTiles(), TraitDeed.OnRead(), FactionBranch.OnSimulateHour(), ContentQuest.OnSwitchContent(), Scene.OnUpdate(), DramaManager.ParseLine(), Chara.PerformWork(), AttackProcess.Prepare(), FoodEffect.Proc(), ActEffect.Proc(), UIDistribution.Refresh(), LayerCraftFloat.RefreshDisassemble(), LayerHome.RefreshFeat(), ButtonHotItem.RefreshItem(), ContentPolicy.RefreshPolicyList(), BaseGameScreen.RefreshPosition(), GameScreenElona.RefreshPosition(), WindowChara.RefreshSkill(), AI_HaulResource.Run(), AI_Idle.Run(), AI_PlayMusic.Run(), WidgetSearch.Search(), UIDynamicList.Select< T >(), GridItemRecipe.SetButton(), ButtonGrid.SetCard(), UIInventory.Sort(), Card.SpawnLoot(), Fov.TraceLine(), Chara.TryPush(), HotItemAct.TrySetAct(), HotItemHeld.TrySetAct(), TraitWell.TrySetAct(), TraitCatalyst.TrySetHeldAct(), LayerInventory.TryShowGuide(), Chara.TryTakeSharedItems(), FactionBranch.UpdateReqruits(), WidgetDebug.UpdateText(), TraitBed.ValidateOwners(), ActEffect.Wish(), and Thing.WriteNote().
Refresh()
list. AddButtonClose.Refresh ()
Referenced by Chara._MakeAlly(), Chara.AddCondition(), UIList.ChangeSort(), Chara.HealAll(), UIList.List(), Chara.MakeMinion(), Chara.OnCreate(), Chara.OnDeserialized(), TraitGeneratorWheel.OnStepped(), TraitGeneratorWheel.OnSteppedOut(), WindowCharaMini.OnSwitchContent(), UIBar.Refresh(), WindowCharaMini.Refresh(), Chara.ReleaseMinion(), Widget.SetBaseContextMenu(), WindowCharaMini.SetChara(), Chara.SetFeat(), UIList.SetPage(), and UIInventory.ShowDistribution().
Variable Documentation
$
$
Initial value:
{
                item = item3
Definition at line 613 of file UIBook.cs.
else
else
Initial value:
{
                list.Add(item3)
Definition at line 623 of file UIBook.cs.
title
item3. title = item3.title.TrimStart('$')
Definition at line 616 of file UIBook.cs.
Referenced by Net.GetFileList(), NewsList.Init(), BookList.Init(), SFB.StandaloneFileBrowserWindows.OpenFilePanel(), SFB.StandaloneFileBrowser.OpenFilePanel(), SFB.StandaloneFileBrowserWindows.OpenFilePanelAsync(), SFB.StandaloneFileBrowser.OpenFilePanelAsync(), SFB.StandaloneFileBrowser.OpenFolderPanel(), SFB.StandaloneFileBrowserWindows.OpenFolderPanel(), SFB.StandaloneFileBrowser.OpenFolderPanelAsync(), SFB.StandaloneFileBrowserWindows.OpenFolderPanelAsync(), UIBook.RefreshTopics(), SFB.StandaloneFileBrowserWindows.SaveFilePanel(), SFB.StandaloneFileBrowser.SaveFilePanel(), SFB.StandaloneFileBrowserWindows.SaveFilePanelAsync(), SFB.StandaloneFileBrowser.SaveFilePanelAsync(), UIBook.Show(), and Net.UploadFile().